### ISSUE TITLE
multiple speed profiles

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#10]

**Comment by daniel-j-h** [comment]
Nothing actionable here - by now we have
- multiple profiles
- [location-dependent profiles](https://github.com/Project-OSRM/osrm-backend/wiki/Using-location-dependent-data-in-profiles)
- [a feature to update arbitrary edges with live traffic](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic)
