### ISSUE TITLE
appart from #100 u-turns should be avoided by (big) penalty

### ISSUE THREAD

**Issue by DrVanScott** [Project-OSRM/osrm-backend#102]
I agree that using u-turns is good for pedestrian or bikers (and maybe cars) - if the u-turn is exactly on a via point. This is what #100 refers to.

Currently there is a problem that affects cars and bikers. Suppose following situation (without via point):

<pre>
      g
      |
- a - b - c - d - e -
          |
          f
</pre>

There is a restriction at b: Coming from a it is not allowed to turn left to g. In addition g and f are dead ends. If you route from a to g osrm is currently suggesting a route a - b - c - f - c - b - g. Is this intentional or a bug?
In real life this is a bad idea. It would be better to go on trying to find a loop, even if it looks like an penalty. So i vote for an u-turn penalty.

**Comment by JMGGarcia** [comment]
Hey! I'm working on a heavy vehicle routing system using OSRM. It has proven very useful but the issue mentioned by @DrVanScott is kinda annoying, has there been any work done on this? Using the car.lua file as the profile, I noticed there is a "u_turn_penalty" variable but changing it doesn't seem to have an effect. Am I missing something? Thanks in advance.
