### ISSUE TITLE
API parameter 'z'

### ISSUE THREAD

**Issue by rodo** [Project-OSRM/osrm-backend#1023]
In the documentation on the wiki about viaroute command there is nothing explained about the 'z' parameter, but it seems to be important when come of queries return 207 when it's not present, and return 0 with z=5 or anything else.

Samples

<pre>
http://router.project-osrm.org/viaroute?output=json&loc=42.330554,9.490555&loc=45.63677,4.73343&instructions=true'

{"status":207,"status_message": "Cannot find route between points"}</pre>

<pre>
http://router.project-osrm.org/viaroute?output=json&loc=42.330554,9.490555&loc=45.63677,4.73343&instructions=true&z=5'

{"status":0,"status_message": "Found route between points","route_geometry": "odtvoAyrfbQnuTwc...
</pre>

**Comment by zhiqiangZHAO** [comment]
I think another solution is routing engine handle this failure. If the route fail, enlarge the origin or destination search area, then retry.

**Comment by DennisOSRM** [comment]
The current release (4.5.0) does implement that now.

**Comment by DennisOSRM** [comment]
https://www.mapbox.com/blog/smart-neighbor/
