### ISSUE TITLE
Api Limit

### ISSUE THREAD

**Issue by Smokimo** [Project-OSRM/osrm-backend#1027]
Hello, my name is Andrej, I could not found how to contact with you, I create an application for Android phone and I would like to use your api :
(router.project-osrm.org/viaroute)
I think, the application will not so popular, but it will often call the api
Do you have any limit for this api ?
is it free ? 
your service is only way to decide my problem!
Thank you in advance!

**Comment by beargi** [comment]
Hi @DennisOSRM, what number of requests is considered to be "excessive"? 1000 within 24h?
Cheers,
Philipp

**Comment by daniel-j-h** [comment]
Just don't overdo it and implement some sort of rate limiting so you don't send 1000 requests at the same time. Note that we also don't provide any uptime guarantees for the demo server.

**Comment by Gonoshift** [comment]
> The demoserver will have a service-wide rate limit of 5000 req/minute. Looking at past logs, it stays below this about 98% of the time, but be prepared for HTTP 429 responses, and be aware that heavy usage may cause rate limiting for everyone else if you flood the server.

https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server
