### ISSUE TITLE
Compilation errors on RHEL 6.5 on EC2

### ISSUE THREAD

**Issue by emmexx** [Project-OSRM/osrm-backend#1046]
I followed the wiki tutorial and manage to get cmake to work.
Now I run make and the following is what I get:

```
make
Scanning dependencies of target COORDLIB
[  2%] Building CXX object CMakeFiles/COORDLIB.dir/DataStructures/Coordinate.cpp.o
In file included from /home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:28:
/home/ec2-user/src/Project-OSRM-master/Include/osrm/Coordinate.h:34: error: expected constructor, destructor, or type conversion before âfloatâ
In file included from /home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:31:
/home/ec2-user/src/Project-OSRM-master/DataStructures/../Util/StringUtil.h:78: error: âunderlying_typeâ in namespace âstdâ does not name a type
/home/ec2-user/src/Project-OSRM-master/DataStructures/../Util/StringUtil.h:78: error: expected initializer before â<â token
In file included from /home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:32:
/home/ec2-user/src/Project-OSRM-master/DataStructures/../Util/TrigonometryTables.h:35: error: expected constructor, destructor, or type conversion before âunsignedâ
/home/ec2-user/src/Project-OSRM-master/DataStructures/../Util/TrigonometryTables.h:722: error: expected constructor, destructor, or type conversion before âdoubleâ
/home/ec2-user/src/Project-OSRM-master/DataStructures/../Util/TrigonometryTables.h: In function âdouble atan2_lookup(double, double)â:
/home/ec2-user/src/Project-OSRM-master/DataStructures/../Util/TrigonometryTables.h:758: error: âatan_tableâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/../Util/TrigonometryTables.h:758: error: âSCALING_FACTORâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp: In member function âbool FixedPointCoordinate::isValid() constâ:
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:74: error: âCOORDINATE_PRECISIONâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp: In static member function âstatic double FixedPointCoordinate::ApproximateDistance(int, int, int, int)â:
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:96: error: âCOORDINATE_PRECISIONâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp: In static member function âstatic float FixedPointCoordinate::ApproximateEuclideanDistance(int, int, int, int)â:
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:140: error: âCOORDINATE_PRECISIONâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp: In static member function âstatic float FixedPointCoordinate::ComputePerpendicularDistance(const FixedPointCoordinate&, const FixedPointCoordinate&, const FixedPointCoordinate&)â:
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:155: error: âCOORDINATE_PRECISIONâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp: In static member function âstatic float FixedPointCoordinate::ComputePerpendicularDistance(const FixedPointCoordinate&, const FixedPointCoordinate&, const FixedPointCoordinate&, FixedPointCoordinate&, float&)â:
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:227: error: âCOORDINATE_PRECISIONâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp: In member function âvoid FixedPointCoordinate::Output(std::ostream&) constâ:
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:328: error: âCOORDINATE_PRECISIONâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp: In static member function âstatic float FixedPointCoordinate::GetBearing(const FixedPointCoordinate&, const FixedPointCoordinate&)â:
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:333: error: âCOORDINATE_PRECISIONâ was not declared in this scope
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp: In member function âfloat FixedPointCoordinate::GetBearing(const FixedPointCoordinate&) constâ:
/home/ec2-user/src/Project-OSRM-master/DataStructures/Coordinate.cpp:353: error: âCOORDINATE_PRECISIONâ was not declared in this scope
make[2]: *** [CMakeFiles/COORDLIB.dir/DataStructures/Coordinate.cpp.o] Error 1
make[1]: *** [CMakeFiles/COORDLIB.dir/all] Error 2
make: *** [all] Error 2
```

I don't have a clue how to fix those errors.
I'm using the osrm source files downloaded 2 or 3 days ago.

Thank you
  maxx

**Comment by deathbaba** [comment]
Got same linker program_options errors while compiling osrm. Please consider including boost as a submodule and including all necessary local build commands/toolchains for everything to work correctly.

**Comment by daniel-j-h** [comment]
@deathbaba which compiler (including version), and which Boost version are you on? I tried searching for a RHEL 6.5 package index similar to packages.debian.org but couldn't find one.

I checked the CMakeLists.txt and for the datastore we link in all the libraries the reports above contain undefined references to. Please provide a more detailed report.

**Comment by deathbaba** [comment]
Ubuntu 15.04 with boost libraries 1.55, clang3.6, tried with and without libc++.
Issue comes when system boost libraries (which are installed via package manager) are not built with the same compiler options/same environment. In general, it is much safer and painless practice to rebuild needed libraries in your own environment, that's why git submodules are a good solution.

**Comment by danpat** [comment]
@deathbaba If you use `g++` to build, it should work, as that will be ABI compatible with the Ubuntu system packages.  There are [known ABI incompatibilities](http://accu.org/content/conf2015/JonathanWakely-What%20Is%20An%20ABI%20And%20Why%20Is%20It%20So%20Complicated.pdf)  when mixing compiler/library versions.

In a nutshell, if you're going to link against system built packages, you will need to use the same compiler that they were built with (or at least one that is ABI compatible).  If you choose to switch compilers, then _you're on your own_, and you will likely need to re-build all the dependencies to get ABI compatible symbols.

**Comment by daniel-j-h** [comment]
Wait, that's different than this ticket's original intend. Ubuntu 15.04 compiles its libraries with gcc and stdlibc++.

For clang with stdlibc++ you have to

- compile stxxl yourself and disable openmp support, this may have changed with the latest clang version supporting openmp
- follow the build instructions and everything should be fine

For clang **with libc++** you have to

- build **every single library we link against** (that is everything that is not header only) yourself against libc++. This is not a problem of Boost in specific, but you can not mix different stdlib implementations.

That is the reason we do not bundle dependencies for the libc++ use case, as we would have to bundle lua, expat, boost, and so on. It's just that libc++ is hard to get into a system that by default uses stdlibc++ (sadly, as I like libc++ myself).

**Comment by deathbaba** [comment]
Thanks for detailed info, @daniel-j-h 
We have a lot of pain with OSRM support in @mapsme with clang :)

**Comment by daniel-j-h** [comment]
@deathbaba issues with getting clang + libc++ to work I can understand (compiling everything from source basically). But clang + stdlibc++ should work fine. If not please create separate issues for those cases.
