### ISSUE TITLE
highway=*_link should imply oneway=yes

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#106]
this is already implied for motorway_link, but should probably also be implied for:

trunk_link
primary_link
secondary_link
tertiary_link

**Comment by GITNE** [comment]
`oneway=no` does not seem to take precedence on `highway=trunk_link` here:
https://map.project-osrm.org/?z=17&center=40.902315%2C-72.882839&loc=40.902315%2C-72.882839&loc=40.898901%2C-72.882485&hl=en&alt=0

Routing should traverse way [`589993109`](https://www.openstreetmap.org/way/589993109).

Same problem here:
https://map.project-osrm.org/?z=18&center=40.744936%2C-72.871172&loc=40.743546%2C-72.870705&loc=40.743469%2C-72.870941&hl=en&alt=0
Routing should traverse way [`591201430`](https://www.openstreetmap.org/way/591201430).

In both situations even u-truns are permitted (and mapped). :thinking: I wonder if OSRM would route correctly if these ways would have a `lanes=2` tag.

@emiltin Can you take a look at this, please? Thank you!

**Comment by oxidase** [comment]
@GITNE  https://map.project-osrm.org uses https://router.project-osrm.org/ endpoint for routing requests that uses datasets prepared with modified Lua profiles. 

With vanilla Lua profiles both ways are traversable (local extracts with the current [master](https://github.com/Project-OSRM/osrm-backend/tree/06699132ebdf0711e624206e3ca1967682e8bbaf) beanch):

* http://localhost:9966/?z=18&center=40.742837%2C-72.872438&loc=40.743546%2C-72.870705&loc=40.743469%2C-72.870941&hl=en&alt=0
![screenshot from 2018-05-30 17-35-22](https://user-images.githubusercontent.com/4421046/40731344-183478d4-6431-11e8-9915-bf122bd1de3c.png)

* http://localhost:9966/?z=18&center=40.900383%2C-72.884604&loc=40.902404%2C-72.882834&loc=40.898978%2C-72.882319&hl=en&alt=0
 ![screenshot from 2018-05-30 17-37-04](https://user-images.githubusercontent.com/4421046/40731354-1d218d78-6431-11e8-8c68-7eb5ddbf3d2f.png)
