### ISSUE TITLE
GUI problem on dragging

### ISSUE THREAD

**Issue by sabas** [Project-OSRM/osrm-backend#1071]
When dragging towards the right while clicking the mouse wheel, this happens. (surely when drag starts on the gui instead of the map)
![cattura](https://cloud.githubusercontent.com/assets/1304918/3218650/259d5f66-efed-11e3-9bdc-8012f1a57792.PNG)

I reproduced this on Chrome in Windows. (the screenshot is from a friend)

**Comment by TheMarex** [comment]
Outdated.
