### ISSUE TITLE
Travel time matrix with origins and destinations?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1075]
Would it be possible to provide origins and destinations separately to the travel time matrix calculation?

For example, you could provide a list of homes and a list of stations, and get all travel times between home-station, but not between home-home or station-station.

**Comment by yusufumac** [comment]
Any update on this feature? I would be great to query with NXM matrices.

**Comment by TheMarex** [comment]
@yusufumac https://github.com/Project-OSRM/osrm-backend/pull/1452
If you want to lend a helping hand, let me know.

**Comment by rCarto** [comment]
+1

**Comment by frodrigo** [comment]
Released in 4.9.0 can be closed.
