### ISSUE TITLE
Feature request: Output profiles

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#1101]
This ticket captures an idea that came up during the conference call on elevation data (#1090).

Just like the input data is parsed by the LUA profiles there should be something similar for the output. One discussed use case was to fetch the elevation profile of a route after it has been computed.

**Comment by daniel-j-h** [comment]
Closing as not actionable.

The current way to annotate the route _after it has been calculated_ is to use the `annotations=true` parameter, which then adds OSM Node IDs to the response. Then either do the lookup manually or use

https://github.com/mapbox/route-annotator

which was built for this specific use-case.
