### ISSUE TITLE
Add turn costs to car profile

### ISSUE THREAD

**Issue by Newbie07** [Project-OSRM/osrm-backend#1121]
Please have a look at following example:
http://osrm.at/8qU

This should be:
http://osrm.at/8qR

I did check the data. All highways have maxspeed=50 and the primary road (B 3) also surface asphalt and at least one lane per direction.

I do not know, how the one second difference was calculated. Are traffic_signals evaluated ? The operating mode (button_push) is missing, so far. Would it make any differences ?

Any way, it is usually better to use the major route in situations like the above as you have to give way on both left turns and you have more curves, more altitude and smaller roads. The route itself is less complicated and saver.

**Comment by TheMarex** [comment]
Turn costs are currently not enabled in the car profile.

**Comment by danpat** [comment]
They were enabled with https://github.com/Project-OSRM/osrm-backend/commit/b3822d5802e7cfd57500ff4bf37570062a2a3bb8
