### ISSUE TITLE
GetEdgeData failed

### ISSUE THREAD

**Issue by escurzo** [Project-OSRM/osrm-backend#1122]
Hi,

I have a new machine for calculate routes.

ubuntu 14.04
osrm version v0.4.2b
32 cpu's
128GM RAM
2 x 300GB SSD

I was executed osrm-extract without errors but osrm-prepare fails!

oper@Aquiles:/ssd/Project-OSRM/build$ tail -200f nohup.out 
[info] Input file: planet-140709.osm.pbf
[info] Profile: profile.lua
[info] Threads: 32
[info] Using script profile.lua
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-MSG] 1 disks are allocated, total space: 1000000 MiB
[info] Using turn restrictions
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parsing in progress..
[debug] parsed 333666 blocks from pbf with 333668 groups
[info] Parsing finished after 13491.4 seconds
[extractor] Sorting used nodes        ... ok, after 549.983s
[extractor] Erasing duplicate nodes   ... ok, after 642.83s
[extractor] Sorting all nodes         ... ok, after 1884.9s
[extractor] Sorting used ways         ... ok, after 101.816s
[extractor] Sorting restrictions. by from... ok, after 0.573s
[extractor] Fixing restriction starts ... ok, after 60.811s
[extractor] Sorting restrictions. by to  ... ok, after 0.519s
[extractor] Fixing restriction ends   ... ok, after 61.501s
[info] usable restrictions: 275908
[extractor] Confirming/Writing used nodes     ... ok, after 3648.63s
[extractor] setting number of nodes   ... ok
[extractor] Sorting edges by start    ... ok, after 1105.34s
[extractor] Setting start coords      ... ok, after 4844.38s
[extractor] Sorting edges by target   ... ok, after 1216.28s
[extractor] Setting target coords     ... ok, after 7504.09s
[extractor] setting number of edges   ... ok
[extractor] writing street name index ... ok, after 6.441s
[info] Processed 484403380 nodes and 511684211 edges
[info] extraction finished after 35120.6s
[info] To prepare the data for routing, run: ./osrm-prepare **/ssd/planet-140709.osrm**

[info] Input file: planet-140709.osrm
[info] Restrictions file: planet-140709.osrm.restrictions
[info] Profile: profile.lua
[info] Threads: 32
[debug] traffic_signal_penalty: 20
[info] Importing n = 484403380 nodes 
[info]  and 511684211 edges 
[info] Graph loaded ok and has 511508009 edges
[info] 275908 restrictions, 162841 bollard nodes, 610217 traffic lights
[info] Generating edge-expanded graph representation
[info] merged 0 edges out of 1022868842
[info] Removing graph geometry while preserving topology
**.osrm-prepare: /home/oper/Project-OSRM/Contractor/EdgeBasedGraphFactory.cpp:417: void EdgeBasedGraphFactory::CompressGeometry(): Assertion `m_node_based_graph->GetEdgeData(forward_e1).nameID == m_node_based_graph->GetEdgeData(reverse_e1).nameID' failed.**

**Comment by antoinegiret** [comment]
Hi,

I'm sorry to reopen that issue, but I have the same problem with pedestrian areas (like in http://www.openstreetmap.org/way/8586379). How can I fix it without remove the assertion?

Thanks,
Antoine.

**Comment by DennisOSRM** [comment]
I wonder if its an issue with duplicated ways, i.e. the code expects data to be not broken.

**Comment by antoinegiret** [comment]
Ok, unfortunately this is a common issue in France.. So I will remove the
assertion for now ! Thanks !

2015-03-31 18:04 GMT+02:00 Dennis Luxen <notifications@github.com>:
