### ISSUE TITLE
Error during make in CentOS 7

### ISSUE THREAD

**Issue by rgs2014** [Project-OSRM/osrm-backend#1135]
Hello,

after trying to build the project in CentOS 6.5 and getting some error during make and moving to CentOS 7 for testing, I get the same error. The required libraries are installed and the the cmake step is performed correctly (cmake -DSTXXL_LIBRARY=/usr/local/lib/libstxxl_debug.a ..):

-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- Performing Test HAS_LTO_FLAG
-- Performing Test HAS_LTO_FLAG - Success
-- Performing Test HAS_LTO_PARTITION_FLAG
-- Performing Test HAS_LTO_PARTITION_FLAG - Success
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Intel TBB
-- Found Lua52: /usr/local/lib/liblua.so;/usr/lib64/libm.so
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES)
-- Looking for Luabind...
-- Found Luabind: /usr/local/lib/libluabind.a
-- Found Luabind: /usr/local/lib/libluabind.a
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.1")
-- Looking for STXXL...
-- Found STXXL: /usr/local/lib/libstxxl_debug.a
-- Found STXXL: /usr/local/lib/libstxxl_debug.a
-- Looking for OSMPBF...
-- Found OSMPBF: /usr/local/lib/libosmpbf.a
-- Found OSMPBF: /usr/local/lib/libosmpbf.a
-- Found PROTOBUF: /usr/lib64/libprotobuf.so
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Project-OSRM/build

After that, when the make step is started I always get the next error:
...
Scanning dependencies of target osrm-extract
[ 55%] Building CXX object CMakeFiles/osrm-extract.dir/extractor.cpp.o
[ 58%] Building CXX object CMakeFiles/osrm-extract.dir/Extractor/XMLParser.cpp.o
[ 61%] Building CXX object CMakeFiles/osrm-extract.dir/Extractor/BaseParser.cpp.o
[ 63%] Building CXX object CMakeFiles/osrm-extract.dir/Extractor/PBFParser.cpp.o
[ 66%] Building CXX object CMakeFiles/osrm-extract.dir/Extractor/ExtractorCallbacks.cpp.o
[ 69%] Building CXX object CMakeFiles/osrm-extract.dir/Extractor/ScriptingEnvironment.cpp.o
[ 72%] Building CXX object CMakeFiles/osrm-extract.dir/Extractor/ExtractionContainers.cpp.o
Linking CXX executable osrm-extract
/tmp/ccrOjJTt.lto.o: En la funciÃ³n `stxxl::sort_memory_usage_factor()':
extractor.cpp.o:(.text+0x1d276): referencia a`omp_get_max_threads' sin definir
/tmp/ccrOjJTt.lto.o: En la funciÃ³n `stxxl::check_sort_settings()':
extractor.cpp.o:(.text+0x34ea1): referencia a`omp_get_max_threads' sin definir
extractor.cpp.o:(.text+0x34ec1): referencia a `omp_get_nested' sin definir
/tmp/ccrOjJTt.lto.o: En la funciÃ³n`void std::__parallel::sort<stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InternalExtractorEdge, 0u, void>, InternalExtractorEdge, 37449ull>, CmpEdgeByTargetID, __gnu_parallel::default_parallel_tag>(stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InternalExtractorEdge, 0u, void>, InternalExtractorEdge, 37449ull>, stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InternalExtractorEdge, 0u, void>, InternalExtractorEdge, 37449ull>, CmpEdgeByTargetID, __gnu_parallel::default_parallel_tag) [clone .constprop.182]':
extractor.cpp.o:(.text+0x52347): referencia a `omp_get_max_threads' sin definir
extractor.cpp.o:(.text+0x52392): referencia a`omp_get_num_threads' sin definir
extractor.cpp.o:(.text+0x525a3): referencia a `omp_get_thread_num' sin definir
extractor.cpp.o:(.text+0x52f61): referencia a`omp_get_max_threads' sin definir
extractor.cpp.o:(.text+0x52f71): referencia a `omp_get_max_threads' sin definir
/tmp/ccrOjJTt.lto.o: En la funciÃ³n`void std::__parallel::sort<stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InternalExtractorEdge, 0u, void>, InternalExtractorEdge, 37449ull>, CmpEdgeByStartID, __gnu_parallel::default_parallel_tag>(stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InternalExtractorEdge, 0u, void>, InternalExtractorEdge, 37449ull>, stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InternalExtractorEdge, 0u, void>, InternalExtractorEdge, 37449ull>, CmpEdgeByStartID, __gnu_parallel::default_parallel_tag) [clone .constprop.174]':
extractor.cpp.o:(.text+0x57647): referencia a `omp_get_max_threads' sin definir
extractor.cpp.o:(.text+0x57692): referencia a`omp_get_num_threads' sin definir
extractor.cpp.o:(.text+0x578a3): referencia a `omp_get_thread_num' sin definir
extractor.cpp.o:(.text+0x58251): referencia a`omp_get_max_threads' sin definir
extractor.cpp.o:(.text+0x58261): referencia a `omp_get_max_threads' sin definir
/tmp/ccrOjJTt.lto.o: En la funciÃ³n`void std::__parallel::sort<stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InputRestrictionContainer, 0u, void>, InputRestrictionContainer, 74898ull>, CmpRestrictionContainerByTo, __gnu_parallel::default_parallel_tag>(stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InputRestrictionContainer, 0u, void>, InputRestrictionContainer, 74898ull>, stxxl::array_of_sequences_iterator<stxxl::typed_block<2097152u, InputRestrictionContainer, 0u, void>, InputRestrictionContainer, 74898ull>, CmpRestrictionContainerByTo, __gnu_parallel::default_parallel_tag) [clone .constprop.162]':
extractor.cpp.o:(.text+0x6b9ac): referencia a `omp_get_max_threads' sin definir
extractor.cpp.o:(.text+0x6b9f9): referencia a`omp_get_num_threads' sin definir
extractor.cpp.o:(.text+0x6bc13): referencia a `omp_get_thread_num' sin definir
extractor.cpp.o:(.text+0x6c678): referencia a`omp_get_max_threads' sin definir
extractor.cpp.o:(.text+0x6c687): referencia a `omp_get_max_threads' sin definir

Is there any library I need to include, or anything bad configured?

Thank you very much in advance.

**Comment by risicle** [comment]
@DennisOSRM could you perhaps mainline this build fix then please?

**Comment by DennisOSRM** [comment]
It's already in develop branch and will hit master with the upcoming release.
