### ISSUE TITLE
via_indices wrong take 2 (off by -1 for via_indices[k] wit 1<=k<viaindizes.length)

### ISSUE THREAD

**Issue by paulbalomiri** [Project-OSRM/osrm-backend#1145]
Hi, i have tried the following server request:

`https://router.project-osrm.org/viaroute?z=14&loc=40.712166,-74.005569&loc=34.052338,-118.243576&loc=32.780338,-96.800522`

 The decoded route geometry (decoded using the function  from [OSRM.RoutingGeometry.js](https://github.com/DennisSchiefer/Project-OSRM-Web/blob/develop/WebContent/routing/OSRM.RoutingGeometry.js)) returns a route_geometry like this:

```
site_data= //data from server
site_geom=decoder(site_data.route_geometry,6)
>  Array[31832]
site_data.via_indices
>  [0, 23048, 31832]
JSON.stringify(site_data.via_indices.map(function(x){return site_geom[x]}))
>"[[40.712164,-74.005569],[34.052217,-118.243389],null]"
```
 while this yields the proper points (0 stays the same,  the remaining indices are -1)
```
JSON.stringify([0,23047,31831].map(function(x){return site_geom[x]}))
> "[[40.712164,-74.005569],[34.052336,-118.24357599999999],[32.780338,-96.800536]]"
```
which approximately coincide with
```
JSON.stringify(site_data.via_points)
> "[[40.712166,-74.005569],[34.052338,-118.243576],[32.780338,-96.800537]]"
```

In [DescriptionFactory.h](https://github.com/Project-OSRM/osrm-backend/blob/develop/Descriptors/DescriptionFactory.h#L195-208)  you increment `necessary_pieces` **before** adding to `via_indices`, which adds `1+k` to via_indices for `i==0+k`

Perhaps the hint at the solution is a longshot, but i think this should be reopened

**Comment by TheMarex** [comment]
This was fixed [here](https://github.com/Project-OSRM/osrm-backend/issues/1020)

**Comment by paulbalomiri** [comment]
Thanks!
