### ISSUE TITLE
Using a type field to indicate road type during preprocessing

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#1165]
@systemed wrote

>  I'm not 100% sure that removing type is a good idea.
> 
> At present OSRM's instructions are a bit arbitrary in what they determine as a 'turn' - see #879, #956, >#684, #686, #282. Sometimes turns will not be shown in the instructions at all, or sometimes they'll be shown as "continue" even though they're a modest left turn. Conversely, sometimes a bogus turn will be generated just because the road changes name.
> 
> One way to fix this (and the way I'm intending to do it at cycle.travel) is to compare types. So, for example, if the route goes from a motorway to a motorway_link, that is by definition a left/right turn, even though the angle will be small. Or if the road changes name, but the angle is 0° and the road type remains the same, that isn't a turn.
> 
> By comparing road types, we should also be able to give a penalty when a minor road crosses a major one (without a crossing), which would be great for bike routing.
> 
> @DennisOSRM, any thoughts?

The idea is a good one. Unfortunately, @emiltin was right when he replied

> @systemed yes penalties for crossing big roads is something we miss too. see #592.
> however i don't think the current type field is the way to solve it.

I am in favor of properly implementing a type field that can be used during preprocessing / generation of instructions. OTOH, it should be set from the LUA script and then the instruction generation should also be handled by a LUA function as it doesn't make too much sense to hard-code road types in C++ land. 

CC: @emiltin @systemed

**Comment by hmaeda** [comment]
I am a bit new to this discussion, but was wondering how possible it would be to get [road type in the instructions](https://github.com/Project-OSRM/osrm-backend/issues/282). Failing the instructions from a [viaroute call](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#service-viaroute), how about when using a [nearest call](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#service-nearest). It sounds like by carrying out some pre-processing some new .osm files would be generated, and by using them, it might help...if so any suggestions on how that would be done?

**Comment by TheMarex** [comment]
@hmaeda usually people just encode the type in the street name that you can set from the lua profile.

**Comment by hmaeda** [comment]
@TheMarex Can you please give an example of how the profile.lua file would be changed to include type?

**Comment by emiltin** [comment]
take a look at the bike profile. it encodes the way type in the way name, when the normal name is empty:
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/bicycle.lua#L225
