### ISSUE TITLE
virtual memory exhausted: Cannot allocate memory

### ISSUE THREAD

**Issue by eoghanmurray** [Project-OSRM/osrm-backend#1170]
Trying to compile osrm on Ubuntu 14.04.1 LTS using instructions here:
https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu
When I perform the `make` step from the build directory, I get the following problem:

[  2%] Built target COORDLIB
[  5%] Configuring FingerPrint.cpp
[  5%] Built target FingerPrintConfigure
[  8%] Configuring FingerPrint.cpp
[ 10%] Building CXX object CMakeFiles/FINGERPRINT.dir/Util/FingerPrint.cpp.o
Linking CXX static library libFINGERPRINT.a
[ 10%] Built target FINGERPRINT
[ 13%] Built target GITDESCRIPTION
[ 18%] Built target IMPORT
[ 21%] Building CXX object CMakeFiles/OSRM.dir/Library/OSRM_impl.cpp.o
virtual memory exhausted: Cannot allocate memory
make[2]: **\* [CMakeFiles/OSRM.dir/Library/OSRM_impl.cpp.o] Error 1
make[1]: **\* [CMakeFiles/OSRM.dir/all] Error 2
make: **\* [all] Error 2

The vps has 1GB memory, and no virtual memory limit:
ulimit -a |grep virtual
virtual memory          (kbytes, -v) unlimited

Any ideas on what the problem could be?

**Comment by timusiiit123** [comment]
> That does not mean that you can not run out of disk space! What does `df -h` say?

Hey, I am having the same problem

```
ubuntu@ip-172-31-10-203:~/osrm/osrm-backend/build$ sudo make install
[  1%] Built target MICROTAR
[  1%] Building CXX object CMakeFiles/UPDATER.dir/src/updater/csv_source.cpp.o
virtual memory exhausted: Cannot allocate memory
CMakeFiles/UPDATER.dir/build.make:62: recipe for target 'CMakeFiles/UPDATER.dir/src/updater/csv_source.cpp.o' failed
make[2]: *** [CMakeFiles/UPDATER.dir/src/updater/csv_source.cpp.o] Error 1
CMakeFiles/Makefile2:817: recipe for target 'CMakeFiles/UPDATER.dir/all' failed
make[1]: *** [CMakeFiles/UPDATER.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
And when I did `df -h`, it did this log-
`
ubuntu@ip-172-31-10-203:~/osrm/osrm-backend/build$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            488M     0  488M   0% /dev
tmpfs           100M   11M   89M  11% /run
/dev/xvda1       31G   16G   16G  50% /
tmpfs           496M     0  496M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           496M     0  496M   0% /sys/fs/cgroup
tmpfs           100M     0  100M   0% /run/user/1000
`

**Comment by danpat** [comment]
@timusiiit123 1GB of RAM is not enough to compile OSRM.

You should either find a machine with more RAM, or enable some swap space.  Please google "how to enable swap space on Linux" for instructions on how to do that for your particular Linux distribution.

**Comment by timusiiit123** [comment]
Will it be fine If I do swap with 1 GB RAM?

> @timusiiit123 1GB of RAM is not enough to compile OSRM.
> 
> You should either find a machine with more RAM, or enable some swap space. Please google "how to enable swap space on Linux" for instructions on how to do that for your particular Linux distribution.

**Comment by silence48** [comment]
if you're using gcc you can set these cxx flags... it might help.

 CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768"
