### ISSUE TITLE
GPX File Export

### ISSUE THREAD

**Issue by drtbyk** [Project-OSRM/osrm-backend#1180]
I created a route on the OSRM Routing map and tested the GPX File download of my generated route. The GPX file is coded as a GPX Direct Route. This can yield thousands of route points. In addition, any intermediate destinations are also coded in to the route as a route point and as such their importance is lost. 

This GPX coding is problematic for any stand alone GPS device as the route will be interpreted as a Direct Route and will have more points in it than most GPS devices can accept for a Direct Route. A more productive GPX export would be to code the path as a GPX Track where point count is not as limited and code the Start, Stop and Intermediate Destinations as GPX Waypoints there by preserving their importance to the route on any GPX capable device.

**Comment by daniel-j-h** [comment]
GPX support was removed, also see ticket #1489.

**Comment by kolesar-andras** [comment]
I'm missing GPX output. Is there a chance to implement it again? Can I help you?

**Comment by TheMarex** [comment]
No we are not looking to support other formats in the backend. If you want to help, it would be great to have something that can transform an OSRM JSON response into GPX on the client. Maybe as Javascript library?

**Comment by daniel-j-h** [comment]
_hint hint_ https://github.com/tyrasd/togpx :)
