### ISSUE TITLE
Isochronic Travel Time

### ISSUE THREAD

**Issue by frankvandenbergh** [Project-OSRM/osrm-backend#1182]
Thank you for this nice component. I'm using it in a Windows VS C# project to calculate travel times for shipments.

Next I want to create iso travel times from depots (similar to isobars). You can think of a polygon around a depot where you drive 1 hour to each containing point. Currently there is no such feature present. Is it for example possible to return all nodes where the cumulative travel time has just passed the limit? Or is it much more complicated as a (highway) link can be very long and need some interpolation?

**Comment by Wilzi** [comment]
+1 for this feature, any update or ETA? thanks :)

**Comment by perliedman** [comment]
Depending on your requirements, you can try [osrm-isochrone](https://github.com/mapbox/osrm-isochrone). It's a brute force solution, but works for some cases.
