### ISSUE TITLE
__get_cpuid was not declared in this scope

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1193]
On my virtual machine, compilation fails with this error:

```
...
[ 78%] Building CXX object CMakeFiles/osrm-prepare.dir/Contractor/Prepare.cpp.o
In file included from /home/osm/osrm-backend/Contractor/Prepare.cpp:32:0:
/home/osm/osrm-backend/Contractor/../Algorithms/IteratorBasedCRC32.h: In member function ‘unsigned int IteratorbasedCRC32::cpuid() const’:
/home/osm/osrm-backend/Contractor/../Algorithms/IteratorBasedCRC32.h:115:46: error: ‘__get_cpuid’ was not declared in this scope
         __get_cpuid(1, &eax, &ebx, &ecx, &edx);
                                              ^
make[2]: *** [CMakeFiles/osrm-prepare.dir/Contractor/Prepare.cpp.o] Error 1
make[1]: *** [CMakeFiles/osrm-prepare.dir/all] Error 2
make: *** [all] Error 2
```

What's missing here?

**Comment by hmaeda** [comment]
I get a simialr issue... below is the error message

`[ 84%] Building CXX object CMakeFiles/osrm-prepare.dir/contractor/processing_cha                                                                             in.cpp.o
In file included from /data/osrm/osrm-backend/contractor/processing_chain.cpp:32                                                                             :0:
/data/osrm/osrm-backend/contractor/../algorithms/crc32_processor.hpp: In member                                                                              function ‘unsigned int IteratorbasedCRC32::cpuid() const’:
/data/osrm/osrm-backend/contractor/../algorithms/crc32_processor.hpp:115:46: err                                                                             or: ‘__get_cpuid’ was not declared in this scope
         __get_cpuid(1, &eax, &ebx, &ecx, &edx);
                                              ^
CMakeFiles/osrm-prepare.dir/build.make:100: recipe for target 'CMakeFiles/osrm-p                                                                             repare.dir/contractor/processing_chain.cpp.o' failed
make[2]: *** [CMakeFiles/osrm-prepare.dir/contractor/processing_chain.cpp.o] Err                                                                             or 1
CMakeFiles/Makefile2:678: recipe for target 'CMakeFiles/osrm-prepare.dir/all' fa                                                                             iled
make[1]: *** [CMakeFiles/osrm-prepare.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
root@xxxxxxxxx:/data/osrm/osrm-backend/build# uname -a
Linux UKVIR36214 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:55:08 UTC 2014 p                                                                             pc64le ppc64le ppc64le GNU/Linux`


Note I am on a powerpc64 architecture...any ideas what causes this issue?

**Comment by DennisOSRM** [comment]
It's a compiler intrinsic for x64 CPUs. 

I will look into predefined variables on powerpc64 that will fix a couple of #ifdefs

**Comment by hmaeda** [comment]
To add a bit of extra info...

I was following carried out the following commands

    root@xxxxxxxx:/data/osrm/osrm-backend/build# cmake ..
    -- Building on a 64 bit system
    -- Configuring OSRM in release mode
    -- LTO working
    -- Using gcc specific binutils for LTO.
    -- Boost version: 1.55.0
    -- Found the following Boost libraries:
    --   date_time
    --   filesystem
    --   iostreams
    --   program_options
    --   regex
    --   system
    --   thread
    --   unit_test_framework
    -- Found Intel TBB
    -- Looking for Luabind...
    -- Found Luabind: /usr/lib/libluabind.so
    -- Looking for LuaJIT 5.2
    -- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR)
    -- Performing Test LUABIND_WORKS
    -- Performing Test LUABIND_WORKS - Success
    -- Luabind/Lua5.2 combination working with /usr/lib/powerpc64le-linux-gnu/liblua5.2.so
    -- Looking for STXXL...
    -- Found STXXL: /usr/lib/libstxxl.so
    -- OpenMP support found. Linking just in case for stxxl
    -- Looking for OSMPBF...
    -- Found OSMPBF: /usr/lib/libosmpbf.a
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /data/osrm/osrm-backend/build
    root@xxxxxxx:/data/osrm/osrm-backend/build# sudo make install
    [  2%] Built target ANGLE
    [  7%] Built target COORDINATE
    [ 10%] Built target EXCEPTION
    [ 12%] Configuring revision fingerprint
    [ 12%] Built target FingerPrintConfigure
    Scanning dependencies of target FINGERPRINT
    [ 15%] Building CXX object CMakeFiles/FINGERPRINT.dir/util/fingerprint.cpp.o
    [ 15%] Built target FINGERPRINT
    [ 17%] Built target GITDESCRIPTION
    [ 23%] Built target IMPORT
    [ 25%] Built target LOGGER
    [ 28%] Built target MERCATOR
    [ 30%] Built target PHANTOMNODE
    Linking CXX static library libOSRM.a
    [ 53%] Built target OSRM
    [ 56%] Built target RESTRICTION
    Linking CXX executable osrm-datastore
    [ 58%] Built target osrm-datastore
    Linking CXX executable osrm-extract
    [ 76%] Built target osrm-extract
    [ 79%] Building CXX object CMakeFiles/osrm-prepare.dir/contractor/processing_chain.cpp.o
    In file included from /data/osrm/osrm-backend/contractor/processing_chain.cpp:32:0:
    /data/osrm/osrm-backend/contractor/../algorithms/crc32_processor.hpp: In member function ‘unsigned int IteratorbasedCRC32::cpuid() const’:
    /data/osrm/osrm-backend/contractor/../algorithms/crc32_processor.hpp:115:46: error: ‘__get_cpuid’ was not declared in this scope
             __get_cpuid(1, &eax, &ebx, &ecx, &edx);
                                                  ^
    CMakeFiles/osrm-prepare.dir/build.make:100: recipe for target 'CMakeFiles/osrm-prepare.dir/contractor/processing_chain.cpp.o' failed
    make[2]: *** [CMakeFiles/osrm-prepare.dir/contractor/processing_chain.cpp.o] Error 1
    CMakeFiles/Makefile2:678: recipe for target 'CMakeFiles/osrm-prepare.dir/all' failed
    make[1]: *** [CMakeFiles/osrm-prepare.dir/all] Error 2
    Makefile:113: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by DennisOSRM** [comment]
What cpu and operating system are you using?

**Comment by hmaeda** [comment]
root@xxxxxx:~/project# uname -a
    Linux xxxxxx 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:55:08 UTC 2014 ppc64le ppc64le ppc64le GNU/Linux

**Comment by hmaeda** [comment]
Is there a way that OSRM can run without LuaJIT?

**Comment by DennisOSRM** [comment]
Yes. Luajit is optional

**Comment by hmaeda** [comment]
Is the lack of LuaJIT when running the `sudo make install` command causing an issue?

**Comment by DennisOSRM** [comment]
No, this is unrelated. As explained above, it's a platform issue where it does not properly detect that it is not running on X64 hardware. We should have a fix shortly.

**Comment by DennisOSRM** [comment]
Try the latest code from develop branch. It's been a bit of an instrument flight, but it should _compile_ now.

**Comment by hmaeda** [comment]
Amazing that worked thank you!
