### ISSUE TITLE
luabind check doesn't find 5.2

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1196]
With the new luabind check in dev branch, compilation fails with:

```
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so  
-- Found Luabind: /usr/lib/libluabind.so
-- Found Lua52: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Failed
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Lua51 (missing: LUA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindLua51.cmake:76 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/check_luabind.cmake:24 (find_package)
  CMakeLists.txt:229 (include)
```

If I check out the commit before the new luabind check was introduced, b1bbf2ef8412baea127c23f5fa029ffe397c552d, compilation works:

```
-- Found Lua52: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so  
-- Found Luabind: /usr/lib/libluabind.so
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.1") 
...
```

The resulting binaries work as expected when compiling this older version.

Ping @alex85k.

**Comment by mrnnn** [comment]
Just wanted to quickly add to this that this error might still occur if you run low on memory:
```
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Failed
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Lua51 (missing: LUA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindLua51.cmake:76 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/check_luabind.cmake:26 (find_package)
  CMakeLists.txt:239 (include)
```

Even with the fixes that were committed to fix this bug. The error message is a bit vague, but boosting my vm up to 2GB fixed the check. My guess is the check just runs OOM and hence fails, even though everything is in place.

**Comment by salteggs** [comment]
I had the same problem when doing cmake on an Amazon EC2 Micro instance. Creating a swapfile fixed the problem.

**Comment by stvno** [comment]
I had the same problem with a new Ubuntu 14.04 upgraded to 16.04 machine with 32 GB RAM. In the end the solution was to install some `libluabind-dev` which was not on the wiki list

**Comment by daniel-j-h** [comment]
@stvno ah - your issue is a different one. We ripped out Luabind for good. The Wiki reflects the latest build instructions. If you're building OSRM before the Luabind change, you have to install Luabind, correct. The old build instructions are still in the Wiki's history. (This is one reason we want to put all documentation into the repo. to have the docs and code in sync)

**Comment by stvno** [comment]
Ah, that explains, I was building the latest release version 5.5.4, not the master, might be useful to add a note that the package instructions are for master and not for releases
