### ISSUE TITLE
geometry generalization too harsh?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1197]
Maybe the geometry generalization is a bit harsh at high zoom levels?

http://map.project-osrm.org/?hl=en&loc=55.663040,12.561625&loc=55.663067,12.561730&z=18&center=55.662937,12.561522&alt=0&df=0&re=0&ly=763558683

**Comment by MoKob** [comment]
By now this looks fine. Closing here. Feel free to re-open if you think the problem still persists.

**Comment by emiltin** [comment]
yes looks fine.
a thought - what happens if you use vector tiles and zoom into level 20 or 22? will the geometry be less generalized yet?

**Comment by daniel-j-h** [comment]
If you're referring to the vector tile debug endpoint as in:
http://map.project-osrm.org/debug/#13.69/37.7975/-122.4302

then no, this code path does not go through simplification:
https://github.com/Project-OSRM/osrm-backend/blob/306744e5cb705b501d6d78d7b34f5934636d24ff/src/engine/plugins/tile.cpp#L278-L432

**Comment by emiltin** [comment]
i was thinking of a normal map based on vector tiles, where the user zooms into e.g. level 20. how will the geometry look? if you specify overview=full it's not generalized?

**Comment by danpat** [comment]
@emiltin With `overview=full`, correct, there is no simplification, so you get every segment of the line geometry.

You may see some coordinate precision drift beyond about Z16.5 if you're referencing against vector tiles.  OSRM only stores 6 decimal places of precision.  OSM contains 7 decimal places, so you can generate vector tiles down to about Z20 with accurate visual alignment from OSM data.  Overlaying an OSRM-generated route could expose some mis-alignment at very high zooms.

Practically though, not many folks generate tiles below Z17/18, there are just too many, and the precision is usually unnecessary.  Mapbox GL will happily "overzoom" a Z16 tile to Z20, meaning that you get the precision from the Z16 tile expanded to Z20.  This means that any precision loss in OSRM is probably roughly the same as the precision lost when overzooming tiles.

FWIW, the per-pixel precision at the equator for a standard vector tile is:

`4310592.56279/(2^(zoom+12))`

where `zoom` is the zoom level you're interested in, and the result is in "pixels per metre".

**Comment by emiltin** [comment]
ok thanks for the explanation!
