### ISSUE TITLE
Questions about distance table

### ISSUE THREAD

**Issue by ricardoatsouza** [Project-OSRM/osrm-backend#1203]
Hello!

Just a few questions about the distance table service.
First, according to the documentation (Server API), the results of the table service are network distance in 10th of seconds. So, it's not a distance, it's time. Is there a way to transform these results into actual distance (meters for example)?

Second, if I am wrong and the result is actually a distance, is it a distance in straight line? Or is it a distance considering the route between the locations?

Thanks.

**Comment by faheemmughal** [comment]
Has there been any development on this? It's quite interesting to get distance instead of travel_time.
