### ISSUE TITLE
Ferry routing Swartz Bay ↔ Tsawwassen

### ISSUE THREAD

**Issue by oeon** [Project-OSRM/osrm-backend#1204]
I recommended OSRM the other day on Twitter https://twitter.com/oeon/status/514975704602386433 .. which led to an incorrect route. Upon further investigation of the OSM data, it seemed the ferry routes/ways indeed did connect - but why wasn't the correct route suggested?

In #osm IRC, this http://osrm.at/9zo was provided, which is an appropriate route - but it seems to have been 'pieced' together..not really an A to B routing input/output.

**Comment by TheMarex** [comment]
@emiltin any idea what a default speed for ferries would look like? [This OSM wiki entry](http://wiki.openstreetmap.org/wiki/Proposed_features/ferry) suggests 25km/h

**Comment by emiltin** [comment]
hmm. i think there's a wide range of speeds. some go slow, some go fast. in denmark, main ferrylines now use catamarans going 70km/h: http://da.wikipedia.org/wiki/Mols-Linien.

**Comment by TheMarex** [comment]
Seems to be fixed in `develop`. ![screenshot from 2016-01-20 23-43-25](https://cloud.githubusercontent.com/assets/606968/12465714/bceabb8a-bfcf-11e5-97ac-13c88accc887.png)
