### ISSUE TITLE
crash: luabind search finds wrong versions?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1213]
With latest dev branch, the code compiles on mac, but the binaries crash inside lua calls.
The search for lua looks weird, since it mentions 5.2 and 5.1 on the same line:

```
-- Looking for Luabind...
-- Found Luabind: /usr/local/lib/libluabind.dylib  
-- Found Luabind: /usr/local/lib/libluabind.dylib
-- Found Lua52: /usr/local/lib/liblua.dylib (found version "5.1.5")     # this looks wrong?
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /usr/local/lib/liblua.dylib
```

**Comment by TheMarex** [comment]
Is this fixed?

**Comment by emiltin** [comment]
looks ok on os x with only lua 5.1 installed, and cmake 3.1

-- Found Luabind: /usr/local/lib/libluabind.dylib  
-- Found Luabind: /usr/local/lib/libluabind.dylib
-- Could NOT find Lua52 (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR) 
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
-- Found Lua51: /usr/local/lib/liblua5.1.dylib (found version "5.1.5") 
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Success
-- Luabind works with Lua 5.1 at /usr/local/lib/liblua5.1.dylib
