### ISSUE TITLE
Make sharedmemory named so you can run multiple osrm-routed instances

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1221]
loading data into separate named stores with osrm-datastore would support:
- running multiple profiles on the same production machine (car, bike, foot..)
- isolating tests, to make sure if doesn't affect already running processes

**Comment by TheMarex** [comment]
Not sure about the complexity involved here. I get the point that is is bad to assume you only have on `osrm-routed` instance running.

What Dennis is getting at is a possible OSRMv2 where you can store multiple profiles in memory (different algorithm). But this is quite a while way..

**Comment by emiltin** [comment]
the use case is providing different routing profiles on the same server, like car and bike, and making the required server setup simpler.

**Comment by woodbri** [comment]
+1 on this feature

**Comment by bvbever** [comment]
For the moment, I have 6 different routing profiles on the same server. 
When I do an update, I restart the corresponding routing what results in a downtime of several minutes.
So I like this feature ;-)

**Comment by arcadas** [comment]
+1

**Comment by pfannkuchengesicht** [comment]
Hey, so I was wondering if there are any estimations as to when this feature might be available? 
I'm currently working on a project that integrates OSRM into PostgreSQL and as of now it's a bit limiting.
Anyhow, any work-around available for now? One way would probably be to load the files directly, but I'm quite sure that would really slow things down. Any suggestion would be really appreciated!

**Comment by danpat** [comment]
@pfannkuchengesicht Nobody is working on it at the moment AFAIK.  Patches are always welcome though!

**Comment by TheMarex** [comment]
This was implemented in #4982.
