### ISSUE TITLE
cache build dependencies and test environment on AppVeyor

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#1223]
AppVeyor now supports caching files and directories between builds as mentioned in another issue by @alex85k (https://github.com/Project-OSRM/osrm-backend/pull/889#issuecomment-59089437). Docs on how this works is [here](http://www.appveyor.com/docs/build-cache). To get this feature tight, we would need to check if the cached folders exist and download support files if they don't. Also, we need a way to _flush_ the cached directories in case of inconsistencies/updates.

cc: @alex85k

**Comment by daniel-j-h** [comment]
@BergWerkGIS can you take a look at this? If done or not relevant, feel free to close.

**Comment by BergWerkGIS** [comment]
Not needed, Windows support was dropped.
