### ISSUE TITLE
Instructions include length twice

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1225]
Route instructions include the length twice. For example ["8","E 18",9555,87,477,"9555m","E",94] include it as:

1. an integer specifying meter (9555)
2. a string with "m" appended. this ("9555m")

I don't really see the value in this since, since it's the same data duplicated, and by convention osrm uses meters everywhere. I would suggest removing the "9555m" part. It would requires changes to frontends though.

**Comment by TheMarex** [comment]
This will be fixed by https://github.com/Project-OSRM/osrm-backend/issues/519
