### ISSUE TITLE
How to write a LUA-profile route by rail?

### ISSUE THREAD

**Issue by flexnst** [Project-OSRM/osrm-backend#1234]
Hello Dennis! I want a write lua-profile for routing by rail, but my attempts to do so do not give, because I always produces an error: "[warn] The input data is empty, exiting.". If you do not mind, please help to write the correct profile.

Source my rail profile:
```lua
restriction_exception_tags = { "train", "public_transport", "rail" }

function get_exceptions(vector)
  for i,v in ipairs(restriction_exception_tags) do
    vector:Add(v)
  end
end

function node_function (node)
  if node.tags:Holds("railway") then
    if node.tags:Find("railway") == "rail" then
      node.bollard = true
    end
  end
end

function way_function (way)
  
  if way.tags:Holds("railway") and way.tags:Holds("gauge") and way.tags:Holds("service") then

      -- railway
      local railway = way.tags:Find("railway")
      -- if not buffer stop
      if railway ~= "buffer_stop" then
	return
      end

      -- gauge
      local gauge = way.tags:Find("gauge")	
      if (gauge ~= 1520) then
	return
      end
      
      if way.tags.:Holds("service") then
	local service = way.tags:Find("service")
	if service ~= "spur" then
	  return
	end
      end
      
      -- If not industrial path
      if way.tags:Holds("usage") then
	local usage = way.tags:Find("usage")
	if usage=="industrial" then
	  return
	end
      end
      
      local duration  = way.tags:Find("duration")
      if durationIsValid(duration) then
        way.duration = max( parseDuration(duration), 1 );
      end
	
      local name = way.tags:Find("name")

      if railway=='rail' then
	way.name = name
	way.speed = 10
	way.duration = 1
	way.backward_speed = way.speed-1
	way.direction = Way.bidirectional
	way.type = 1
      end
  end
  return
end
```

**Comment by flexnst** [comment]
I'm public my profile on my blog:
http://flexnst.ru/2015/11/20/osrm-railway-profile/

**Comment by JonathanBooker** [comment]
Did anything usable become of this/did a railway profile get created by someone? I would like to try integrate a rail profile into the application I am making. I have tried the above blog profile and had no luck with it.

**Comment by stavskal** [comment]
Hi I also need a railway profile, anyone had any luck?

**Comment by daniel-j-h** [comment]
There was someone on IRC a couple of weeks ago asking questions and posting some cool images regarding railway routing (I think it was around Amsterdam? Might be off here). Maybe hang out in the channel and ask from time to time.

**Comment by stavskal** [comment]
Thanks for bringing that to my attention. Unfortunately I cannot lurk your IRC frequently. If anyone hears from this guy please request a link / steps to reproduce the profile!

**Comment by JonathanBooker** [comment]
I did manage to get a *VERY* rough profile that worked just for railways however I was quite pushed for time while making it and there is a lot to be improved on/removed from it as it is based from one of the original scripts. It still contains a lot of un-necessary stuff from the original profile and I have seen some edge cases where it might not route correctly.

I am hoping to potentially do some work on it fairly soon and I will post it once it is all cleaned up.

**Comment by stavskal** [comment]
Until then, would it be possible to give me a copy of the draft? Maybe I can help improve it as well
