### ISSUE TITLE
bridge=yes and level=1

### ISSUE THREAD

**Issue by scirag** [Project-OSRM/osrm-backend#1239]
If there are nodes intersecting with different levels especially for way overlapping with bridge, we have a wrong routing result:

![image](https://cloud.githubusercontent.com/assets/8748853/4753873/271bb8dc-5aba-11e4-933f-ed05f288bb20.png)

Result contains turn left under the bridge(level=1) as if there is a way with the same level(level=0).

If nodes intersected with bridges are deleted, it is OK, but it would be nice if we can define a restriction w.r.t way levels by lua script or OSM parse can handle this issue

**Comment by kostadin24** [comment]
If check for 'shared node' is based on X,Y - what is problem to compare using 'level' tag too?

If this modification is not easy -> other approach can be to modify nodes coordinates, so nodes from top and bottom level ways will be different. How big have to be this modification - hope less than meter.

**Comment by danpat** [comment]
@kostadin24 OSRM does not look at the coordinates at all when considering how they're connected.

Take a look at: http://wiki.openstreetmap.org/wiki/Elements

In the OSM data there are "nodes" and "ways".  For a bridge situation like this, there needs to be two separate nodes with the same coordinate, one node for the upper level, one for the lower.

The `level` tag is used for rendering - this let's generators of visual maps know which `way` needs to be placed on top - it's not really useful for calculating the [network topology](https://en.wikipedia.org/wiki/Topology).

**Comment by kostadin24** [comment]
@danpat thanks a lot. This make me happy again :) because I have huge dataset with >100000 situations like this.
