### ISSUE TITLE
Turn instruction missing when road name is kept

### ISSUE THREAD

**Issue by agunnarsson** [Project-OSRM/osrm-backend#1251]
Sometimes important turn instructions are missing. This seems to be connected to locations where road name isn't changed or where road name changes on other locations than the actual node where road branches to multiple possible outgoing roads. The example is from <a href="http://map.project-osrm.org/?hl=en&loc=47.278355,16.091795&loc=47.282543,16.085482">this location</a>
![turn_instruction_missing](https://cloud.githubusercontent.com/assets/5629253/4880153/53db41aa-6337-11e4-9b7b-97db1b39c1b8.png)

**Comment by MoKob** [comment]
<img width="1004" alt="screen shot 2016-03-21 at 14 30 52" src="https://cloud.githubusercontent.com/assets/12932279/13920117/9e416fe0-ef71-11e5-91f6-14c2a7ca8a77.png">

On the demo-server you can experience better discovery already. In our upcoming version 5.0, these instructions will start to get even better.
