### ISSUE TITLE
Cannot parse result in JavaScript: "SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by chfritz** [Project-OSRM/osrm-backend#1252]
There seem to be special unicode characters in the response from the backend that break javascript. This is also notable in the node-osrm package that, as of not too long ago, seems to break with an "Unexpected end of input" error when parsing the result from the backend.

I've already tried to replace all U+2028 and U+2029 characters in JavaScript, as recommended here
http://timelessrepo.com/json-isnt-a-javascript-subset, but this didn't solve the issue. I still get "SyntaxError: Unexpected token" when trying to parse the response from the backend into a JSON object.

**Comment by DennisOSRM** [comment]
I have not been able to verify the issue at hand. 

@chfritz What data set have you been using? Does it occur with the 4.5.0 release? What's the unparsable output?

**Comment by TheMarex** [comment]
At least for `node-osrm` this should not be a problem anymore (no internal JSON parsing anymore). Please reopen if you can provide an example for the HTTP API and a recent OSRM version.

**Comment by chfritz** [comment]
Confirmed. Thanks.

**Comment by vgrichina** [comment]
I had the same issue with commit 9414a8085d64180d9242ce655b6d95daee82edca (recent develop branch).
Reverting to v4.7.1 helped.

Sample query with problem:
/viaroute?loc=49.2153234,28.4375806&loc=49.233687,28.463689&instructions=true
Used with this map data http://download.geofabrik.de/europe/ukraine-latest.osm.pbf

**Comment by vgrichina** [comment]
BTW, current demo server also has such issue http://router.project-osrm.org/viaroute?loc=49.2153234,28.4375806&loc=49.233687,28.463689&instructions=true

**Comment by TheMarex** [comment]
Should be resolved now @vgrichina. At least node parses the response form your query correctly.
