### ISSUE TITLE
Issue with the TBB on Windows

### ISSUE THREAD

**Issue by ghost** [Project-OSRM/osrm-backend#1257]
Hi, I'm trying to install OSRM and I'm having troubles with the TBB It shows me: "ERROR: Intel TBB not found", I've downloaded the TBB from the page as a zip and It didn't work. I hope someone could help me with this. 

Thanks

**Comment by huberttt** [comment]
Hi there, while compiling osrm on Windows during build_stxxl.bat compilation I'm receiving similar error (same code ) as u had so I thought i could write here. I dont really know what's the reason.
![bez tytulu](https://cloud.githubusercontent.com/assets/8050000/6016584/718d018a-ab84-11e4-8573-e997d504e098.png)

**Comment by ZupoLlask** [comment]
Any of the Windows builds available on http://build.project-osrm.org/ are based on develop branch?

Thanks.

**Comment by DennisOSRM** [comment]
Yes, it's always the latest and greatest from develop branch.
