### ISSUE TITLE
Crashes on Windows Debug builds

### ISSUE THREAD

**Issue by m-kuhn** [Project-OSRM/osrm-backend#1260]
Thanks to the work of @alex85k I could build osrm with help of the libs found on http://build.project-osrm.org

I adjusted `buildme.bat` as follows

    set PATH=%PATH%;C:\Program Files (x86)\CMake\bin
    set P=%CD%
    set P=%P:\=/%
    set Configuration=Debug
    mkdir build%Configuration%
    cd build%Configuration%
    echo Running cmake...
    call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
    set TBB_INSTALL_DIR=%P%/tbb
    set TBB_ARCH_PLATFORM=intel64/vc12
    cmake .. -G "Visual Studio 12 2013 Win64" ^
        -DCMAKE_BUILD_TYPE=%Configuration% ^
        -DBZIP2_INCLUDE_DIR=%P%/libs/include ^
        -DBZIP2_LIBRARIES="%P%/libs/lib/libbz2.lib" ^
        -DCMAKE_INSTALL_PREFIX=%P%/libs ^
        -DBOOST_ROOT=%P%/boost_min ^
        -DBoost_USE_STATIC_LIBS=ON ^
        -T CTP_Nov2013
    
    msbuild /clp:Verbosity=minimal /nologo OSRM.sln
    cd ..

Compiling and linking works fine. So do the steps to generate the required files to run osrm. However, as soon as I run a query against osrm-routed, I get an answer for exactly one query and then a crash.

Crash message:
    vector iterator not dereferencable

Anwer for `http://localhost:5000/viaroute?loc=47.37819,8.53689&loc=47.37948,8.50109`
> {"status_message":"Found route between points","status":0,"route_geometry":"kevjyAcl`hOqAfHgAdHbBdGrHhFzJdKzB|BjMvMjFjEzEzD``@fd@~ClLtExJjAvBxR|]|DhIbHdD|^j\\dUvWd]l^xJdFx_@`SrQjKpG~F`E`FtPlKVlKxKfs@hAzJlAvLrBzU|@xJp@lHp@xHH~Ho@hGoAvD{GpJkHdK_ExF_EfDsDH{CtGyA`EeA`EuEpRcFzSyOdo@kD~BaCbHkMxd@wApIa@bLq@hk@QnJ}@~r@o@jj@[hYa@tIe@rHy@|G}AxIwCrLyCxRyBrRDpPoOldAi@vDmD`Va@tC{AtIgGtJ}AhHqEhXkLrw@yB|U[~DyAtMyE~S}FzTqDnJ}CtJkB|GoFvPmEdMqF|NqC|GsC`HgV|n@qHnR}C~IcDxKwDvLuGtVaTts@gFbPkBzD_BpC{ALiC`DyCnHsAxEs@zKHhDeBbIq^vcAm_@peAmNp`@ci@h~Ag\\bbAcFjNwH|LoDnA_FbEgBzB_BtJCdDb@pDbBtEvCpDrFfBnChBtC|DxD~E|e@|r@lMjSx]vj@~DfG","route_summary":{"total_distance":3418,"total_time":344,"start_point":"Postbrücke","end_point":"Letzigraben"},"via_points":[[47.378025,8.536786],[47.379528,8.501012]],"via_indices":[0,128],"hint_data":{"checksum":3681250750,"locations":["3kEAAP_____kAwAAeQAAAI8AAAARAAAAAAAAAOuPCgBm7tIC0kKCAAEAEcw","KQMBADQDAQBGCgAAfQAAAA0AAAAAAAAARAAAANrtAQBI9NICFLeBAAAAEcw"]},"route_name":["",""],"found_alternative":false}

Same crash for the branches master and develop

Any idea what might go wrong here?

**Comment by daniel-j-h** [comment]
You can find my easy fix (in terms of changed lines of code) here: https://github.com/Project-OSRM/osrm-backend/pull/1690.
Make sure to read and understand the detailed commit message, though!
