### ISSUE TITLE
osrm-prepare hangs at preprocessing ... 90% .

### ISSUE THREAD

**Issue by benjamin-rty** [Project-OSRM/osrm-backend#1264]
afther extracting some data from europe:
"[info] Processed 27829229 nodes and 30783804 edges
[info] extraction finished after 303.613s"

I run osrm-prepare. It hangs on
"...
merged 138 edges out of 91044286
contractor finished initalization
initializing elimination PQ ...ok
preprocessing 21928454 nodes .... 10% . 20% . 30% . 40% . 50% . 60% . [flush 14390558 nodes]  70% . 80% . 90% ."

What happens afther the "90% ." that can cause the hanging (its running for more then 24 hrs and uses 100% CPU)?

I have 64GB ram and debian 7 linux and uses the osrm version v4.4.0.

**Comment by bjtaylor1** [comment]
bvbever, I don't suppose you would mind sharing whatever method  you used to remap the node ids? I'm currently seeing this same issue when processing a pbf of great-britain and france combined (i.e. merged  with osmosis), however if I just use great-britain  (as downloaded) it works ok. Might be something about france it doesn't like...?
