### ISSUE TITLE
primary+traffic_light preferred to primary_link shortcut

### ISSUE THREAD

**Issue by Zverik** [Project-OSRM/osrm-backend#1265]
http://osrm.at/a1I
It says that going through a traffic light would take 22s, while taking a shortcut (with [no specific restrictions](http://www.openstreetmap.org/way/44050554)) would take 28s. Is this a bug?

**Comment by TheMarex** [comment]
@Zverik the issue at hand seems to be fixed. Can we close?

**Comment by Zverik** [comment]
Yes, of course.
