### ISSUE TITLE
StaticGraph constructor not used

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1288]
https://github.com/Project-OSRM/osrm-backend/blob/fc1db35f27d03df8dfcf9ef5fa000435acd5e065/DataStructures/StaticGraph.h#L89

This constructor is not used (apart from the ```StaticGraphTest```). Instead the necessary values are build
externally and directly serialized:

https://github.com/Project-OSRM/osrm-backend/blob/75f9c0844550261d5e9c842d0a10b8f82eac2965/Contractor/Prepare.cpp#L241

Should we drop the constructor in favour of a factory function that can create the node array and edge array (so we can use it in ```Prepare.cpp``` and ```StaticGraphTest.cpp```)?

Similar ```InputEdge``` is also not used anymore (but various typdefs reference).

BTW. Do you know any utility to detect similar dead code?

/cc @DennisOSRM

**Comment by DennisOSRM** [comment]
We are using the c'tor in question now in the tiny components exploration. Again, good catch.
