### ISSUE TITLE
Allow routing on service roads at beginning and end of routes, and at ferries

### ISSUE THREAD

**Issue by rwelty1889** [Project-OSRM/osrm-backend#1309]
i understand why service routes usually cannot be used in the middle of routes, but there are numerous situation where a service route is reasonable.
it's also frequently the case that ferries in OSM are mapped with service routes to ferry boarding

**Comment by MoKob** [comment]
Both ferries and service routes are considered for routing by now. Ferries cannot be selected as start/end location, though.
