### ISSUE TITLE
Broken Time Matrix Return

### ISSUE THREAD

**Issue by jtok202** [Project-OSRM/osrm-backend#1310]
The time matrix is not returning the correct output. 

Using the example provided in the wiki, the output is actually. 

http://router.project-osrm.org/table?loc=52.554070,13.160621&loc=52.431272,13.720654&loc=52.554070,13.720654&loc=52.554070,13.160621&z=14

{
    "distance_table": [
        [2147483647, 2147483647, 2147483647, 2147483647],
        [2147483647, 993, 16956, 38677],
        [2147483647, 17023, 803, 39449],
        [2147483647, 38589, 39434, 922]
    ]
}

I am not sure what is going on but this makes it impossible/needlessly difficult to run matrix routes right now. 

Does anybody know when the last working version number was? 

Jacob

**Comment by DennisOSRM** [comment]
Thanks @themarex. 

@emiltin how much work is associated with implementing this testing?

**Comment by emiltin** [comment]
already pushed in

**Comment by emiltin** [comment]
i've marked a few with @todo since i expected -1 to mean unroutable but osrm returns int max

**Comment by emiltin** [comment]
in the test tables, left column indicate origin node, top row indicate destination node. the two lists must match.

**Comment by emiltin** [comment]
is the table test mechanism sufficent?

**Comment by TheMarex** [comment]
@emiltin looks good. Thanks! I think we are good here. Expect the should fix the -1 thing. Probably just replace it by MAX_INT?

**Comment by emiltin** [comment]
wouldn't it be more convenient if osrm would return -1? 2147483647 is not very handy if you ask me.

but in case we keep MAX_INT, then maybe we can have the test framework accept that in test tables, or maybe just use an empty strong to mean 2147483647.

**Comment by emiltin** [comment]
osrm could also return null for impossible routes, ie. [234,123,null,null,423]?

**Comment by DennisOSRM** [comment]
Null implies zero network distance not infinite

**Comment by emiltin** [comment]
to me it would imply no route

**Comment by TheMarex** [comment]
-1 is easier to handle, but do we want to break the API for this?

**Comment by emiltin** [comment]
for now i've updated the tests so empty cells means no route - at the moment signified by 2147483647 in api results.

i think it would be worth changing the api to make it cleaner, but the call is yours :-)

**Comment by DennisOSRM** [comment]
@emiltin right, I see your point about null as a JSON token.

**Comment by DennisOSRM** [comment]
Thought about it a little more. Using null could be the reasonable approach as consumers of the API would expect a _functional_ response. 

Note to self: implementation wise it's probably only replacing the vector.insert() in the distance table plugin with a std::transform call that takes a lambda as the fourth argument.

**Comment by woodbri** [comment]
FWIW, we use -1 in pgrouting to indicate not route is possible. I guess it would not be hard to check for null and convert that to -1 on the client side (which may not be Javascript).I consume OSRM output in PHP, C, C++, and Javascript.

**Comment by TheMarex** [comment]
In Javascript ```null``` is more used to indicate "no object" (I always read it like NULL in C/C++). Given the context I think we should stick to either ```-1``` or ```MAX_INT```.

**Comment by emiltin** [comment]
as long as we get rid of 2147483647 :-)

**Comment by DennisOSRM** [comment]
Null has the benefit of being a JSON entity where the others aren't. 

@jfirebaugh do you know what the best practice is to indicate infinity in JSON and JavaScript?

**Comment by emiltin** [comment]
in my view, infinity is a confusing concept in this context since it could indicate that a route exists, but the speed is zero.

**Comment by TheMarex** [comment]
This is fixed.
