### ISSUE TITLE
Adjust derived speeds per road class

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#1314]
right now there's a uniform scale factor. This should be replaced by a class-dependent factor and an additive correction.

**Comment by DennisOSRM** [comment]
@kapadia any updates?

**Comment by frankvandenbergh** [comment]
Is there really a need for a scale factor when you can set/use the average speed per type of road? You only have to check if it exceeds allowed speed limits.

I'm creating a lua for a truck. First I want to get the speeds more or less conform real life. I asked drivers, planners and analysed on board computer data. As it correlates to time of day and day of week I want to focus on averages outside rush hours.

Here are my preliminary settings, tested on several routes, but not compared to actual data yet.

I kept the scale factor, but set it at 0.9, and removed the +11.

I set the speed profiles as:
speed_profile = {
  ["motorway"] = 75/speed_reduction,
  ["motorway_link"] = 45,
  ["trunk"] = 71/speed_reduction,
  ["trunk_link"] = 40,
  ["primary"] = 65/speed_reduction
  
Set the max speed default table:
maxspeed_table_default = {
  ["urban"] = 50,
  ["rural"] = 80,
  ["trunk"] = 80,
  ["motorway"] = 80
}

Set the overruling of max speeds of roads:
-- List only exceptions
maxspeed_table = {
  ["be:highway"] = 80,
  ["nl:highway"] = 80,
  ["fr:highway"] = 80,
  ["nl:trunk"] = 80,
  ["be:trunk"] = 80...
  
And finally I altered the highway procedure:
if result.forward_speed == -1 then
    local highway_speed = speed_profile[highway]
    local max_speed = parse_maxspeed( way:get_value_by_key("maxspeed") )
    -- Set the avg speed on the way if it is accessible by road class
    if highway_speed then
	-- changed > into <
      if max_speed and max_speed>0 and max_speed < highway_speed then
        result.forward_speed = max_speed
        result.backward_speed = max_speed
      else
        result.forward_speed = highway_speed
        result.backward_speed = highway_speed
      end
    else
      -- Set the avg speed on ways that are marked accessible
      if access_tag_whitelist[access] then
        result.forward_speed = speed_profile["default"]
        result.backward_speed = speed_profile["default"]
      end
    --end
    if 0 == max_speed then
      max_speed = math.huge
    end
    result.forward_speed = min(result.forward_speed, max_speed)
    result.backward_speed = min(result.backward_speed, max_speed)
	end
  end

**Comment by utack** [comment]
Is it possible that this issue makes OSRM a bit "allergic" to motorways in Germany and seems to like alternative routs a bit too much?
If not, where should I start looking for this?

**Comment by TheMarex** [comment]
@utack do you have a specific example for that?

**Comment by utack** [comment]
@TheMarex sorry for taking so long to respond.

A "classic" example is going around Munich.

OSRM

![auswahl_054](https://cloud.githubusercontent.com/assets/8551234/12079168/d11ba630-b22f-11e5-8926-3186b6af40c0.png)


Mapzen

![auswahl_055](https://cloud.githubusercontent.com/assets/8551234/12079169/d61a0d98-b22f-11e5-8526-dfb7eba8e9c6.png)


Osmands Router

![screenshot_2016-01-03-15-15-48](https://cloud.githubusercontent.com/assets/8551234/12079170/d9d079c2-b22f-11e5-8f95-ff850ad6d08e.png)

Google

![auswahl_056](https://cloud.githubusercontent.com/assets/8551234/12079173/e0d656f6-b22f-11e5-84c3-32217803caf7.png)

Garmin device

![garmin](https://cloud.githubusercontent.com/assets/8551234/12079174/e594e9f0-b22f-11e5-9064-5cb5007029c3.jpg)

I can produce more of these examples if you want, two come to mind

**Comment by utack** [comment]
FWIW Garmin's routing with OSM data does not agree with you in this case but it does calculate the exact same route two other cases where OSRM avoided the highway. And in this specific case it also goes the exact same route through the city, when just navigating to a point 1km more north, so the algorithm difference with OSM data is minor.
This is not worth looking into, as there is definitly no objectively better route.

**Comment by danpat** [comment]
Rgere eh e

**Comment by danpat** [comment]
On Feb 9, 2016eh 07:26, "utack" <notifications@github.com> wrote:
>
> FWIW Garmin's routing with OSM data does not agree with you in this case
but it does calculate the exact same route two other cvebemeases ebb where
OSRM avoided the highway. And in this specific case it also goes the exact
same route through the city, when just navigating to a point 1km more
north, so the algorithm difference with OSM data is minor.
> This is not worth looking into, as there is definitly no objectively
better route.

**Comment by danpat** [comment]
Woah, pocket email, sorry!

**Comment by manjana** [comment]
It's an actual question before posted. May be someone can answer for a @TheMarex ?

**Comment by manjana** [comment]
Guys Is it possible that this issue makes OSRM a bit "allergic" to gravel road?

Google and other routes by 
![google1](https://cloud.githubusercontent.com/assets/411526/26538403/27f9351e-444f-11e7-822f-40c3fd74b32e.png)

Osrm routes by
![osrm1](https://cloud.githubusercontent.com/assets/411526/26538409/32a04d40-444f-11e7-88a6-714156ead90b.png)

Distances difference is very small (~ 2 km) , but counting machine wash, suspension repairs - much better ride through the asphalt.

**Comment by daniel-j-h** [comment]
Can you open a new issue with your problem and make some efforts into digging up the osm ways and how the tagging looks like there. Seems like the demo server is currently down so we might have to wait a bit for actual routes.

**Comment by emiltin** [comment]
http://www.openstreetmap.org/way/171809135
