### ISSUE TITLE
turn penalty vs traffic signal penalty

### ISSUE THREAD

**Issue by kaligrafy** [Project-OSRM/osrm-backend#1318]
traffic signal penalty is calculated with a factor 10 (since distances are calculated in 1/10 seconds in the code)
However, turn penalties in turn function are not multiplied by a factor 10. Maybe they should be to avoid ambiguity?

**Comment by MoKob** [comment]
I've prepared a small fix here: https://github.com/Project-OSRM/osrm-backend/pull/2773

**Comment by TheMarex** [comment]
This will be addressed by #1614 since the `turn_function` API changed.

**Comment by TheMarex** [comment]
This was fixed.
