### ISSUE TITLE
Weird routing problem via 'small' custom shapefile network

### ISSUE THREAD

**Issue by Svantulden** [Project-OSRM/osrm-backend#1321]
Hi, 

First of all, thanks for your amazing work on OSRM! I find it truly fascinating that such a solid routing engine is open source and actively contributed to. 

Now, I want to use OSRM to route via a relatively small route network shapefile. The way I accomplish this is by converting the shapefile to OSM, consisting of nodes and ways. It is a closed network, so we can assume it is fully routable. Then I add the `highway=customnetwork` tag to the ways, to set a speed constant and use it in the routing profile. 

I extract and prepare the OSM file and the routing works about 80% without issues. Though in some cases, I get weird results. To illustrate this, I made [this tiny extract](https://gist.github.com/Svantulden/6088eaa0eb850d12d85c) of the OSM file. 

![Wrong](https://cloud.githubusercontent.com/assets/7554912/5547260/1a01803c-8b57-11e4-9c63-18c58981a460.png)
^^ - Here it goes wrong. This uses [this API call](http://localhost:20010/viaroute?instructions=true&alt=true&loc=51.4638221883968,5.817440305750472&u=true&loc=51.44381962617868,5.825116287599811&u=true&loc=51.43831342481577,5.859856289621013&u=true). At the second waypoint, it searches the nearest 'fork', to 'turn' and go the same way back to the 3rd waypoint.
![Right](https://cloud.githubusercontent.com/assets/7554912/5547294/8a2f477c-8b57-11e4-96d7-93b1cd80bba6.png)
^^ - Here it goes right (the other direction). This uses [this API call](http://localhost:20010/viaroute?instructions=true&alt=true&loc=51.43831342481577,5.859856289621013&u=true&loc=51.44381962617868,5.825116287599811&u=true&loc=51.4638221883968,5.817440305750472&u=true).

In some cases, when I have three waypoints, routing from the 2nd to the 3rd, it takes a long detour to find the nearest turning circle or fork in the road where it can 'turn'. This is unexpected, especially because when routing the other way around, it routes normally between the junction nodes. Because of this, I thought it might had something to do with the engine assuming oneway. So I explicitly added the `oneway=false` tag, but the results were the same. 

Have you got any idea if I am doing something wrong here, or that it can be a bug in OSRM? 

**PS.** To reproduce the problem, you can download [the small OSM extract](https://gist.github.com/Svantulden/6088eaa0eb850d12d85c) I made of the network and use the same API calls beneath the screenshots.

**Comment by Svantulden** [comment]
Does this mean that the original issue in this OP is because JOSM (and OpenData) handles the converting process wrong? I am still wondering where the issue lies in the weird routing I am perceiving.

**Comment by DennisOSRM** [comment]
It's because of the fact that you place a location directly at the intersection. It's undefined which road segment the nearest one is in this case.

**Comment by Svantulden** [comment]
Sorry, I can understand that this could be the case when placing the locations exactly on the connecting nodes, but as I mentioned [above](https://github.com/Project-OSRM/osrm-backend/issues/1321#issuecomment-68049089), the problem also occurs when I place the locations not on the intersections themselves, but on a road segment before/after it. 

Because the routing is perfect for 80% of the time (both on and off intersections), I have a feeling there is some small quirk in the [OSM extract](https://gist.github.com/Svantulden/6088eaa0eb850d12d85c) or in OSRM that causes this.

Would you have an explanation for this?

**Comment by DennisOSRM** [comment]
> Would you have an explanation for this?

At this point we don't have a good explanation. Only things that come to mind are related to oneway streets and turn restrictions.

**Comment by Svantulden** [comment]
Alright, thank you for looking into this. I will experiment some more with different OSM extracts to hopefully pinpoint where the issue lies. I'll report back here when I make some progress.

**Comment by daniel-j-h** [comment]
Closing here --- if you are still seeing issues, feel free to open a new issue; also try out the latest 4.9 release just to be sure that it isn't already fixed.
