### ISSUE TITLE
File format set wrong

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1326]
During the renaming a few files switched from ```unix``` to ```dos``` file format.
This litters the diffs when using ```git diff``` and in general we should strive to only have unix encoded files.
When all this renaming is finished, we should convert the dos encoded files back to unix again.

**Comment by DennisOSRM** [comment]
Oh, this is inconvenient

**Comment by daniel-j-h** [comment]
Done --- I was unable to find files with dos encoding at this point in time.
