### ISSUE TITLE
Precision and symmetry: The angles in TurnInstruction

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#1330]
The angles in TurnInstruction's getTurnDirectionOfInstruction() seem off. Like I feel they should be 22.5 + (45 * N), but in your code not only do they not grow at a consistent rate, but they're not even symmetrical. Example: 23 != (360-336).

**Comment by MoKob** [comment]
@daniel-j-h not even sure what the issue here is supposed to be. Technically my calculations should be symmetrical. What that thing about 45*N is supposed to be... no idea. I guess we can close this for now.
