### ISSUE TITLE
I want use post method request table API, but fail.

### ISSUE THREAD

**Issue by solidsnake2013** [Project-OSRM/osrm-backend#1332]
I build a form
example :
<form id="aaa" method="post" action="http://localhost:5000/table"><input name="loc" type="text"><input name="loc" type="text"></form>

When I submit it.
service response error : 400 Bad Request (from cache)
response json : {"status": 400,"status_message":"Bad Request"}

I have to use the post way, because point too much.

The current version does not support the POST for table API?

**Comment by TheMarex** [comment]
No POST requests are not implemented yet. See #1293 for more info.

**Comment by solidsnake2013** [comment]
oh! we every time use point of 300-400.
and we We also need to use [table] and viaroute.

There is no other way?
