### ISSUE TITLE
Routing error: Hops between north and south mediterranean sea

### ISSUE THREAD

**Issue by MDamien** [Project-OSRM/osrm-backend#1334]
Hi,

I don't know if it's the right place to report this but here I go: 
The [routing between Geneva and Tunis](http://map.project-osrm.org/?hl=en&loc=44.750168,9.048590&loc=36.837769,10.305268&z=3&center=43.452919,-27.421875&alt=0&df=0&re=0&ly=763558683) has a big hop between the south and the north of the mediterranean sea. I think this is a problem with OSM data but I didn't manage to track it down for now.

And here is a screenshot to prove I'm not crazy :smiley: 
![Image of Yaktocat](http://i.imgur.com/3jPULvm.png)

Or we could add "Turn the car into flying mode" to the instructions :rocket:

**Comment by emiltin** [comment]
OSRM follow ferry routes. If you choose the standard osm map layout they're easier to see.

**Comment by DennisOSRM** [comment]
yep, it's a ferry connection.
