### ISSUE TITLE
error data 

### ISSUE THREAD

**Issue by ivantrouvetout** [Project-OSRM/osrm-backend#1336]
![erreur osrm](https://cloud.githubusercontent.com/assets/10398391/5665771/f1616d1c-975a-11e4-8198-7fb79a6585cc.png)

I think the problem comes from old data

**Comment by DennisOSRM** [comment]
Perhaps, want to share a location?

**Comment by ivantrouvetout** [comment]
15/44.8295/5.5940

**Comment by DennisOSRM** [comment]
data itself looks quite alright. i'll check if the planet dump file that is used has any issues.

**Comment by ivantrouvetout** [comment]
...

**Comment by ivantrouvetout** [comment]
the problem was resolved
