### ISSUE TITLE
I have modified the tableMatrix interface, How should I submit?

### ISSUE THREAD

**Issue by solidsnake2013** [Project-OSRM/osrm-backend#1340]
hi all,

I modified the table matrix interface.

In the previous code, it is only support the 100 coordinate calculate.

I modified it is to 1000.

Part of the code  :

Plugins/DistanceTablePlugin.hpp

line 94 : unsigned max_locations =
            std::min(100u, static_cast<unsigned>(raw_route.raw_via_node_coordinates.size()));
        PhantomNodeArray phantom_node_vector(max_locations);

to 

unsigned max_locations =
            std::min(1000u, static_cast<unsigned>(raw_route.raw_via_node_coordinates.size()));
        PhantomNodeArray phantom_node_vector(max_locations);

I have verified the results.

Whether can submit?

**Comment by solidsnake2013** [comment]
There is a problem,
We urgently need to increase the post submission.
Please provide some help...

thanks.

**Comment by emiltin** [comment]
An option was recently added to develop branch to change the max size of distance tables, see #1335.
There no way yet to use POST to send larger amounts of data, see #1293.

**Comment by DennisOSRM** [comment]
With the latest code from develop branch you can increase the max table size via the command line.

```bash
$ ./osrm-routed 
[info] osrm-routed <base.osrm> [<options>]:

Options:
  -v [ --version ]                     Show version
  -h [ --help ]                        Show this help message
  -c [ --config ] arg (="server.ini")  Path to a configuration file
  --trial [=arg(=1)]                   Quit after initialization

Configuration:
  --hsgrdata arg                       .hsgr file
  --nodesdata arg                      .nodes file
  --edgesdata arg                      .edges file
  --geometry arg                       .geometry file
  --ramindex arg                       .ramIndex file
  --fileindex arg                      File index file
  --namesdata arg                      .names file
  --timestamp arg                      .timestamp file
  -i [ --ip ] arg (=0.0.0.0)           IP address
  -p [ --port ] arg (=5000)            TCP/IP port
  -t [ --threads ] arg (=8)            Number of threads to use
  -s [ --shared-memory ] [=arg(=1)]    Load data from shared memory
  -m [ --max-table-size ] arg (=100)   Max. locations supported in distance 
                                       table query
```
