### ISSUE TITLE
Windows compile error with v4.5.0

### ISSUE THREAD

**Issue by frankvandenbergh** [Project-OSRM/osrm-backend#1345]
In the past I successfully compiled the OSRM project thanks to @alex85k.

Now I downloaded the new release v4.5.0. Tried to compile it, but got stuck at osrm-backend\Include\osrm\coordinate.hpp line 37:
constexpr static const float COORDINATE_PRECISION = 1000000.f;

Could you change this into:
#ifndef _MSC_VER
constexpr static const float COORDINATE_PRECISION = 1000000f;
#else
const static float COORDINATE_PRECISION = 1000000.;
#endif

c:\osrm2015\osrm-backend\Util\osrm_exception.hpp, line 47:
const char *what() const noexcept { return message.c_str(); }

into:
#ifndef _MSC_VER
    const char *what() const noexcept { return message.c_str(); }
#else
	const char *what() const throw() { return message.c_str(); }
#endif

It didn't compiled completely yet. I can dig into this, but need to know if you want these alterations.

**Comment by frankvandenbergh** [comment]
Regarding the noexcept, you might want to read this topic:
http://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio

**Comment by frankvandenbergh** [comment]
The noexcept will probably be introduced in VS14:
http://blogs.msdn.com/b/somasegar/archive/2014/06/03/first-preview-of-visual-studio-quot-14-quot-available-now.aspx

**Comment by DennisOSRM** [comment]
The min requirement for Windows support is VS 2013 Nov CTP

http://blogs.msdn.com/b/vcblog/archive/2013/11/18/announcing-the-visual-c-compiler-november-2013-ctp.aspx

**Comment by htmlrb** [comment]
hello @DennisOSRM,
How can I force cmake/nmake to use VS 2013 Nov CTP compiler ?
