### ISSUE TITLE
Turn restriction (via node) ignored

### ISSUE THREAD

**Issue by hlaw** [Project-OSRM/osrm-backend#1346]
http://osrm.at/aEd
![screenshot from 2015-01-16 01 23 19](https://cloud.githubusercontent.com/assets/4372879/5762735/443e928e-9d1f-11e4-928a-48e245ee13bc.png)

The sharp turn at the northwest of the route should not occur, as this should be prohibited by an "only" turn restriction:
http://www.openstreetmap.org/relation/2436379#map=18/22.32655/114.20857

Incidentally the "from" way of the turn restriction is also the "to" way in another turn restriction, similar to the case mentioned in #1041 (closed).  Not sure if this is relevant.

Thank you.

**Comment by DennisOSRM** [comment]
Thanks, will look into it

**Comment by hlaw** [comment]
I am trying to trace this and found two duplicate tests, [this](/Project-OSRM/osrm-backend/blob/master/extractor/extraction_containers.cpp#L137) and [this](/Project-OSRM/osrm-backend/blob/master/extractor/extraction_containers.cpp#L142), in the same chain of if-else statements in the turn restriction parsing code.

Seems to stem from the refactoring commit 0d9b70552eaa8efced6b45936d56e9496507ff8f for lines 140 / 142 of ExtractionContainers.cpp.  Not sure if this is related to this issue or perhaps the outstanding issues at #1286.

**Comment by emiltin** [comment]
good catch, looks wrong to me

**Comment by DennisOSRM** [comment]
Thanks for the pointer into the source code. I was able to remove redundant code and also found another issue where it miscalculated the total number of restrictions (and thus ignored some). Locally this looks much better now:

![screenshot 2015-01-16 15 34 29](https://cloud.githubusercontent.com/assets/1067895/5777766/d3fc544e-9d95-11e4-9dd3-b8fc110f043d.png)

I am now working on getting the patch into shape and will push it during the day to develop branch. Not sure how to put this edge case into a cucumber test though.

**Comment by DennisOSRM** [comment]
The fix should be live on the demo site in roughly 10-12 hours from now. Leaving the issue open until we verify it there.

**Comment by hlaw** [comment]
Looks good, thanks a lot!

**Comment by DennisOSRM** [comment]
Looking good now.

![screenshot 2015-01-21 09 27 15](https://cloud.githubusercontent.com/assets/1067895/5833129/c66f3a5e-a14f-11e4-880d-a7bc9f0d130b.png)
