### ISSUE TITLE
Cannot prepare the planet file

### ISSUE THREAD

**Issue by zbychuk** [Project-OSRM/osrm-backend#1348]
I am trying to extract and prepare planet file. I use the following settings:
Ubuntu 14.04 LTS, 64 GB RAM, /tmp - 300GB, stxxl - 300gb
Extract was finally succesful, but osrm-prepare crashes with not very useful message "Killed"
Just after displaying message "merged 0 edges out of 1083760438.
Is it lack of RAM? 
I do not care about the speed, if I can extract and prepare in less than 24 hours - it is fine,
but I would like to do it on 32 GB RAM machine, if possible

**Comment by TheMarex** [comment]
Yes that seems like the OOM killing osrm-prepare due to lack of RAM. Should work with 64GB of RAM.

**Comment by DennisOSRM** [comment]
Make sure you have swap space set up properly.

**Comment by zbychuk** [comment]
Swap file is 100GB, still crashing. Last night, one of the runs, after almost 24 hours finished generating some files, but not all.
Nothing else works on this server, top shows at some point that computer used all RAM and 50GB from swap.
Some people here said something about 4 hours running in my case it crashed (now) after 14 minutes with following output:
[info] Input file: planet-latest.osrm
[info] Restrictions file: planet-latest.osrm.restrictions
[info] Profile: profile.lua
[info] Threads: 8
[info] Importing n = 513171434 nodes
[info]  and 542092661 edges
[info] Graph loaded ok and has 541965453 edges
[info] 0 restrictions, 180954 bollard nodes, 668604 traffic lights
[info] Generating edge-expanded graph representation
[info] merged 0 edges out of 1083760438

I have redirected stream 2 to errlog, but it's empty

**Comment by DennisOSRM** [comment]
- What does `df -h` say?
- is anything else running on the machine?
- which branch/release are you using?

**Comment by zbychuk** [comment]
desktop@ns502423:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G  3.3G   15G  18% /
devtmpfs         32G  4.0K   32G   1% /dev
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            6.3G  3.2M  6.3G   1% /run
none            5.0M     0  5.0M   0% /run/lock
none             32G     0   32G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/md3        1.8T  556G  1.2T  33% /home

Swap is now defined as 200G file on /home, temp is mounted /home/tmp which is 300G and stxxl is 300G 
desktop@ns502423:~$ swapon -s
Filename                                Type            Size    Used    Priority
/home/swaparea                          file            209715196       14954864   -1
desktop@ns502423:~$ df /tmp
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       20026172 3403300  15582544  18% /

No - nothing else is running on it (except SSH server) 
As for version - I have downloaded latest two days ago and compiled it

BTW - I was on several foras (also some russian) and it seems that quite a lot of people have a problem converting whole planet. 
Maybe it would be worth to think about some kind of repository for extracted and prepared OSRM files (for each country and for a planet)? There is so much lost time and computing power around the world. 
I, for example, would not hesitate to spend some reasonable amount of money to just download ready files, rather than spending my time and money to hire special server to do it. 
Even assuming EC2 (or MS Azure) it would costs around $15-$30 to hire a sensible machine for one conversion. So If I could pay for example $30 per year and there would be 60 people like me, we could get 128GB machine from let's say OVH and generate those files daily or at least weekly for all of us

**Comment by zbychuk** [comment]
Finally, success! However the time it took os ridiciulous - almost 36 hours :)
[info] Expansion  : 6619.69 nodes/sec and 2888.84 edges/sec
[info] Contraction: 13703.2 nodes/sec and 78301.5 edges/sec
[info] finished preprocessing

real    1738m39.338s
user    2121m41.496s
sys     25m37.512s
desktop@ns502423:~/Downloads$

**Comment by DennisOSRM** [comment]
Did you run the develop or the master branch code. This certainly looks like a regression

**Comment by DennisOSRM** [comment]
After thinking about it, again, are you positive that you didn't build in debug mode? What's the output of the cmake call? Did you build in in external directory?

**Comment by zbychuk** [comment]
I just done cmake .. and make from build directory. I am not sure what you
mean by external directory.
I have no idea if it built debug or release. I have not saved output from
cmake, so - is there away to check it now? Like by size of the file?

As for source code - I have cloned latest from git (git clone http://....)
few days ago and again - I am not sure which version i got.

**Comment by emiltin** [comment]
if you run "git branch" it will show you what branch you're on. if you didn't change it you're probably on master.

**Comment by zbychuk** [comment]
Yes, it is master.

**Comment by emiltin** [comment]
dennis, what's the easiest wasy to tell if the build was debug or release? "osrm-build --version" includes a git hash if it's not build from a git tag, but i guess that could still be a release build.

**Comment by DennisOSRM** [comment]
go to build directory and run `cmake ..`. It should say somewhere something along the lines of

```
configuring in release/debug mode
```

**Comment by zbychuk** [comment]
definetely release :( (I am sad as I hope it was my screw-up and now
everything will be great)
BTW - is there a way to join prepared files? I in fact need UK, Irelend,
Benelux, Norway, Japan and USA for my project. At the moment I can ignore
all other countries.

desktop@ns502423:~/osrm-backend/build$ cmake ..
-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES)
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /usr/lib/x86_64-linux-gnu/
liblua5.2.so
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so
-- Looking for OSMPBF...
-- Found OSMPBF: /usr/lib/libosmpbf.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/desktop/osrm-backend/build
desktop@ns502423:~/osrm-backend/build$

**Comment by emiltin** [comment]
You cannot join or filter the prepared files. You can use osmosis to join/filter the source .pbf files before procesing with osrm.

**Comment by zbychuk** [comment]
I've found that this is likely to be an issue with insufficient RAM. I've been running this on a 64GB machine, and this is not enough for processing the entire planet, so it spills over into swap. Interestingly, it is the expansion rather than the contraction which has issues:

```
Edge-expanded graph ...                                                             
  contains 450681004 edges                                                          
  skips 0 turns, defined by 0 restrictions                                          
  skips 191841107 U turns                                                           
  skips 229099 turns over barriers                                                  
Timing statistics for edge-expanded graph:                                          
Geometry compression: 609.966s                                                      
Renumbering edges: 2.58986s                                                         
Generating nodes: 24348.7s                                                          
Generating edges: 57566.4s                                                          
building r-tree ...                                                                 
constructing r-tree of 541880219 edge elements build on-top of 513171434 coordinates
finished r-tree construction in 7862.2 seconds                                                 
...
[info] Contraction took 16252.6 sec                        
...          
[info] Preprocessing : 109828 seconds                      
[info] Expansion  : 6163.91 nodes/sec and 2689.93 edges/sec
[info] Contraction: 13779.2 nodes/sec and 78733.4 edges/sec
```

Processing on a server with more memory (256GB), as well as more cores, is far more sensible, on the order of 2 hours.

**Comment by emiltin** [comment]
would it maybe be useful to only allow swap if you pass on option like --allow-swap?

**Comment by DennisOSRM** [comment]
> Interestingly, it is the expansion rather than the contraction which has issues:

reminds me of an issue that was fixed recently in the develop branch. Have you tried that branch?

> would it maybe be useful to only allow swap if you pass on option like --allow-swap?

Swap is managed by the OS. One can hardly interfere with that.

**Comment by zbychuk** [comment]
I have tried with dev branch. It seems to improve speed significantly. Now it was 1721 minutes, i.e. around 28 hours (rather than 36 before).
I have also set `sudo sysctl vm.swappiness=60` as swap was not transferred back to memory even if there was free memory available

**Comment by TheMarex** [comment]
@zbychuk are we good to close here?

**Comment by zbychuk** [comment]
Yes, sure. Thanks for your help
