### ISSUE TITLE
Cannot start osrm-routed (file is missing!)

### ISSUE THREAD

**Issue by zbychuk** [Project-OSRM/osrm-backend#1349]
Cannot start whole world server getting funny error .namesIndex not found, is it possible that :it is red herring and in fact this is simply lack of memory?

zbyszek@Ubuntu1404:/data$ ls -l pl*
-rw-rw-r-- 1 zbyszek zbyszek 28296591799 Jan 19 04:11 planet-latest.osm.pbf
-rw-rw-r-- 1 zbyszek zbyszek 22847244955 Jan 19 03:41 planet-latest.osrm
-rw-rw-r-- 1 zbyszek zbyszek  5408173900 Jan 19 04:21 planet-latest.osrm.edges
-rw-rw-r-- 1 zbyszek zbyszek 26012372088 Jan 18 13:33 planet-latest.osrm.fileIndex
-rw-rw-r-- 1 zbyszek zbyszek  4407507356 Jan 18 11:31 planet-latest.osrm.geometry
-rw-rw-r-- 1 zbyszek zbyszek 16251734300 Jan 18 18:58 planet-latest.osrm.hsgr
-rw-rw-r-- 1 zbyszek zbyszek  6158057212 Jan 18 13:36 planet-latest.osrm.nodes
-rw-rw-r-- 1 zbyszek zbyszek   148372912 Jan 18 13:36 planet-latest.osrm.ramIndex
zbyszek@Ubuntu1404:/data$ ~/OSRM/osrm-backend/build/osrm-routed planet-latest.osrm
[warn] /home/zbyszek/OSRM/osrm-backend/build/osrm-routed could not be locked to RAM
[info] starting up engines, v4.5.0
[info] populating base path: planet-latest.osrm
[warn] exception: .namesIndex not found
zbyszek@Ubuntu1404:/data$

**Comment by TheMarex** [comment]
There should be a "planet-latest.osrm.names" file. Not sure why the error message says ".namesIndex".
Did the ```osrm-extract``` process really finish?

**Comment by zbychuk** [comment]
It has finished (in a sense that it returned to the prompt and time command
calculated the time it took), however also file .restriction is missing, so
I guess it kind of quietly died and sunk the exception.

**Comment by zbychuk** [comment]
Never mind, user error, I accidentally killed `osrm-extract` before it finished and wrote the `.names` file. Re-running it fixed the issue.
