### ISSUE TITLE
Descriptions for route instructions

### ISSUE THREAD

**Issue by trofimchyk** [Project-OSRM/osrm-backend#1351]
Sorry for a maybe stupid question but [this link](https://github.com/Project-OSRM/osrm-backend/blob/master/DataStructures/TurnInstructions.h) from wiki doesn't work. Is your docs a little bit outdated and where I can find correct descriptions for **driving directions**?

**Comment by DennisOSRM** [comment]
Here's the link: https://github.com/Project-OSRM/osrm-backend/blob/master/data_structures/turn_instructions.hpp

**Comment by DennisOSRM** [comment]
Also, updated the wiki. Thanks for the notification.

**Comment by trofimchyk** [comment]
@DennisOSRM, I will check it. Thank your for fast answer!
