### ISSUE TITLE
non square Matrix support?

### ISSUE THREAD

**Issue by norcis** [Project-OSRM/osrm-backend#1354]
I need to calculate Nx1 matrix (many to one), This may be N times more efficient than using NxN matrix calculation, which is supported now. Any plans implementing such function?

Now uri looks like /table?loc=54.676377,25.290076&loc=54.67720,25.28781&loc=54.676377,25.290076&z=14

but NxM matrix support is very welcome:

matrix?from_point=54.67720,25.28781&from_point=54.676937,25.306123&to_point=54.676377,25.290076

**Comment by emiltin** [comment]
See #1075
