### ISSUE TITLE
cmake/nmake & VS CTP_Nov2013  compiler

### ISSUE THREAD

**Issue by htmlrb** [Project-OSRM/osrm-backend#1358]
Hi all,
How can I force cmake/nmake to use VS CTP_Nov2013 compiler ? 
since constexpr and noexcept are not supported.

**Comment by htmlrb** [comment]
Well I think:
cmake .. -G "Visual Studio 12 Win64" -T CTP_Nov2013 -DCMAKE_BUILD_TYPE=Release ...

**Comment by DennisOSRM** [comment]
See here for how build the Windows binaries:

https://github.com/Project-OSRM/osrm-backend/blob/master/appveyor.yml#L41-L43

**Comment by htmlrb** [comment]
Thanks,
Now I get an issue with new configuration of cmake:
> cmake .. -G "Visual Studio 12 Win64" -T CTP_Nov2013 -DCMAKE_BUILD_TYPE=%VARIANT% -DCMAKE_INSTALL_PREFIX=%PREFIX% -DSTXXL_LIBRARY=%PREFIX%/lib/stxxl_debug.lib -DBZIP2_INCLUDE_DIR=%PREFIX%/include -DBZIP2_LIBRARIES=%PREFIX%/lib/libbz2.lib -DEXPAT_INCLUDE_DIR=%EXPAT%/Source/lib -DEXPAT_LIBRARY=%EXPAT%/Bin/libexpat.lib -DBOOST_ROOT=%BOOST_ROOT% -DBoost_USE_STATIC_LIBS=ON 

Output
> ....
-- The C compiler identification is MSVC 18.0.21114.0
-- The CXX compiler identification is MSVC 18.0.21114.0
-- Check for working C compiler using: Visual Studio 12 2013 Win64
-- Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Building on a 64 bit system
-- Configuring OSRM in debug mode
CMake Warning (dev) at CMakeLists.txt:112 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

>  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

> CMake Warning (dev) at CMakeLists.txt:141 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

>  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

> CMake Warning (dev) at CMakeLists.txt:145 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

>  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

> CMake Warning (dev) at CMakeLists.txt:158 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

>  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

> CMake Warning (dev) at CMakeLists.txt:161 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

>  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

> CMake Warning (dev) at CMakeLists.txt:174 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

>  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

>-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
--   date_time
--   chrono
--   zlib
-- Looking for include file pthread.h
-- Looking for include file pthread.h - not found
-- Found Threads: TRUE
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: d:/Repo/osrmenv/lib/luabind.lib
-- Found Luabind: d:/Repo/osrmenv/lib/luabind.lib
-- Found Lua52: d:/Repo/osrmenv/lib/lua.lib
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES)
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Failed
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
-- Found Lua51: d:/Repo/osrmenv/lib/lua.lib
-- Looking for LuaJIT 5.1
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES)
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Failed
CMake Error at cmake/check_luabind.cmake:38 (message):
  Luabind does not work with Lua 5.1 at d:/Repo/osrmenv/lib/lua.lib, no
  working Luabind found
Call Stack (most recent call first):
  CMakeLists.txt:239 (include)


> -- Configuring incomplete, errors occurred!
See also "D:/Garage/DevCamp/osrm-backend/build2/CMakeFiles/CMakeOutput.log".
See also "D:/Garage/DevCamp/osrm-backend/build2/CMakeFiles/CMakeError.log".

However, when I used the "NMake Makefiles" option, it worked (but fails after due to native compiler that does not support constexpr)

>cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%VARIANT% -DSTXXL_LIBRARY=%PREFIX%/lib/stxxl_debug.lib -DBZIP2_INCLUDE_DIR=%PREFIX%/include -DBZIP2_LIBRARIES=%PREFIX%/lib/libbz2.lib -DEXPAT_INCLUDE_DIR=%EXPAT%/Source/lib -DEXPAT_LIBRARY=%EXPAT%/Bin/libexpat.lib -DCMAKE_INSTALL_PREFIX=%PREFIX% -DBOOST_ROOT=%BOOST_ROOT% -DBoost_USE_STATIC_LIBS=ON 

>...
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
--   date_time
--   chrono
--   zlib
-- Looking for include file pthread.h
-- Looking for include file pthread.h - not found
-- Found Threads: TRUE
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: d:/Repo/osrmenv/lib/luabind.lib
-- Found Luabind: d:/Repo/osrmenv/lib/luabind.lib
-- Found Lua52: d:/Repo/osrmenv/lib/lua.lib
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES)
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with d:/Repo/osrmenv/lib/lua.lib
-- Found EXPAT: c:/Program Files (x86)/Expat 2.1.0/Bin/libexpat.lib (found version "2.1.0")
-- Looking for STXXL...
-- Found STXXL: d:/Repo/osrmenv/lib/stxxl_debug.lib
-- Found STXXL: d:/Repo/osrmenv/lib/stxxl_debug.lib
-- Looking for OSMPBF...
-- Found OSMPBF: d:/Repo/osrmenv/lib/osmpbf.lib
-- Found OSMPBF: d:/Repo/osrmenv/lib/osmpbf.lib
-- Found PROTOBUF: d:/Repo/osrmenv/lib/libprotobuf.lib
-- Found BZip2: d:/Repo/osrmenv/lib/libbz2.lib (found version "1.0.6")
-- Looking for BZ2_bzCompressInit in d:/Repo/osrmenv/lib/libbz2.lib
-- Looking for BZ2_bzCompressInit in d:/Repo/osrmenv/lib/libbz2.lib - not found
-- Found ZLIB: d:/Repo/osrmenv/lib/zlib.lib (found version "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Garage/DevCamp/osrm-backend/build

**Comment by DennisOSRM** [comment]
The warning generated by Cmake can be ignored as it appears. Can you provide a link to gist with the contents of these two files? Thanks

- "D:/Garage/DevCamp/osrm-backend/build2/CMakeFiles/CMakeOutput.log".
- "D:/Garage/DevCamp/osrm-backend/build2/CMakeFiles/CMakeError.log".

**Comment by htmlrb** [comment]
Here 
https://github.com/htmlrb/osrm-backend/blob/master/build/CMakeFiles/CMakeOutput.log
https://github.com/htmlrb/osrm-backend/blob/master/build/CMakeFiles/CMakeError.log

**Comment by htmlrb** [comment]
Hello @DennisOSRM,
it was only build type problem. Luabind built in release mode, and I was trying to build ORSM in Debug mode.
Now cmake works. However, I got this error when building:

12>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\ratio(122): error C2065: 'INTMAX_MAX' : undeclared identifier
12>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\ratio(133) : see reference to class template instantiation 'std::ratio<_Nx,_Dx>' being compiled

**Comment by htmlrb** [comment]
To solve it, one need to define "__STDC_LIMIT_MACROS"
