### ISSUE TITLE
HTTP 502 - Bad gateway

### ISSUE THREAD

**Issue by MKergall** [Project-OSRM/osrm-backend#1359]
Using OSMBonusPack (an Android library) and accessing OSRM public service with this url: 

http://router.project-osrm.org/viaroute?&loc=48.887746,2.272968&loc=48.865334999999995,2.2966569999999997&instructions=true&alt=false

, I get an "HTTP 502 - Bad gateway" return code. 

I tested with an Android device, and also with an emulator: same result. 
This issue was initially reported by an other user, with exactly the same results (see https://code.google.com/p/osmbonuspack/issues/detail?id=107). 

What is surprising is: 
- This url works perfectly when called from a browser - even from the browser on the device. 
- Accessing OSRM with OSMBonusPack was alright for some years now. 

Any clue?

**Comment by DennisOSRM** [comment]
This is a brief inconvenience and should be back to normal in the coming hours. There was a regression in the http handling code.

**Comment by DennisOSRM** [comment]
Should be fixed by now. The default behavior is a non-gzipped response again.
