### ISSUE TITLE
StayOnRoundAbout?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1362]
When is the turn instruction StayOnRoundAbout used?

**Comment by DennisOSRM** [comment]
Internally, to compute the turn instruction that says how many exits later to leave the roundabout.

**Comment by emiltin** [comment]
so it's never emitted in responses?

**Comment by DennisOSRM** [comment]
No, it's not.

**Comment by emiltin** [comment]
ok thanks
