### ISSUE TITLE
Use angle to improve roundabout instructions

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1363]
Using the angle between the arrival and departure roads could improve roundabout instructions.

Istead of:
Enter roundabout and take the first exit.
Enter roundabout and take the second exit.
Enter roundabout and take the third exit.

We could do for example:
Enter roundabout and go sharp right, first exit.
Enter roundabout and go straight on, second exit.
Enter roundabout and go left, third exit.

**Comment by MoKob** [comment]
For small roundabouts, this is implemented in https://github.com/Project-OSRM/osrm-backend/pull/2303. For larger roundabouts, that are not completely visible, this will probably not be done.
