### ISSUE TITLE
coordinate_calculation as namespace?

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1367]
Why is [coordinate_calculation](https://github.com/Project-OSRM/osrm-backend/blob/develop/data_structures/coordinate_calculation.hpp) a struct with static members and not a simply a namespace?

Also IMHO, it seems more appropriate to place it in ```algorithms``` or ```util```.

/cc @DennisOSRM

**Comment by DennisOSRM** [comment]
Yeah, fair point. Something to refactor on a slow day.

**Comment by daniel-j-h** [comment]
Fyi, the code base has more of those, e.g. `struct bearing`, `struct cast`, in the utils directory.
I already fixed those in https://github.com/Project-OSRM/osrm-backend/pull/1661.
