### ISSUE TITLE
running two servers on same machine (and on a different machine, and what's the best ec2 instance to use)

### ISSUE THREAD

**Issue by bjtaylor1** [Project-OSRM/osrm-backend#1368]
1) What is the software reason why two osrm servers flatly refuse to run on the same machine?
One runs fine, but as soon as I start another one it instantly bails with a 'bad_alloc' exception. They each have their own directory structure in independent folders alongside each other and don't share any files, and obviously attempt to listen on different ports.
Is there any way they can be 'encouraged' to?

2) I know it has been said on here in the past that osrm isn't designed to run on a 'different' machine to what it was built on.
However what I do is build and extract it on a 'beefy' EC2 instance, but then run it on a 'cheap' EC2 instance that is the exact same OS (ubuntu 14) but an "m2.micro" rather than either an "m3.xlarge" or a "hs2.2xlarge" or something.
I have to do this though, as it won't build on a micro instance, and I can't justify paying the amazon fees to run a beefy instance all the time; my server doesn't get that much traffic (or revenue). For most routes the micro instance still comes back within a couple of seconds at most which I find acceptable.
I was wondering if anyone can elaborate on exactly why it isn't designed to run on a 'different' machine and how I might be able to mitigate any potential issues this strategy may cause?
I know it builds a ".ramIndex" file and I wondered if this might have anything to do with the above.
On the micro instance I run on I use a swap file of 64M blocks x 32.
(is that the best block size to use? Does it matter?)

3) What is the best type of amazon EC2 instance to use to build it- e.g. is it best to go for compute optimized, memory optimized or storage optimized? I've already figured out how to use an stxxl config to tell it what disks are available and this seems to improve its extraction performance and gets rid of warnings, I did this on a storage optimized one (hs2) and it seemed to extract the whole of britain and france in probably under an hour, but just wondering if this was the best value.

**Comment by emiltin** [comment]
1: you're out of memory. you can run several instances on the same machine, but each will allocate memory.

2: you can build and run on different machine, as long as they are the same OS and you take care to use the same version of osrm for building and running. for our www.ibikecph.dk service we use separate machines without problems. swap will decrease performance a lot since it depends on disk access.

**Comment by bjtaylor1** [comment]
> you're out of memory. you can run several instances on the same machine, but each will allocate memory.

Ok cheers... but how much memory, is the question. Is it "greedy" in that it will use as much as it can find, or just use as much as it needs? 

Where I'm coming from is, a micro instance runs it ok with 64M x 16 swap (1GiB). 
It's also ok with 64M x 32 (2GiB) swap, but I can't run 2 instances with 64M x 32 swap.
Is there not any way I can tell the first instance to only allocate half the available memory (which I know empirically is enough for it) rather than allocating it all for itself...?

Could it be the case that this isn't currently possible with how it's currently programmed but it is theoretically possible, given my findings above, or am I reading something wrongly into it?

**Comment by bjtaylor1** [comment]
aha. I just found it does work with just more swap...I found the micro does have 1GiB ram of its own, so by increasing it to 2GiB I'm only effectively increasing it by 50%.
