### ISSUE TITLE
accessing way's id in lua

### ISSUE THREAD

**Issue by bjtaylor1** [Project-OSRM/osrm-backend#1369]
I used to (probably at least several months ago) be able to access a way's id in lua by just  "way.id" but this doesn't seem to work now, it is always "nil".

Any way I can do it?

I am using a fairly recent update of master branch.

**Comment by emiltin** [comment]
it should be possible. if not, sounds like a bug

**Comment by bjtaylor1** [comment]
I think it is a bug.
I just tried it with the standard car profile and put 

```lua
function way_function (way, result)
  if way.id ~= nil then
    print("got way id!"..way.id)
  else
    print ("no way id")
  end
...
end
```
in the top of the way function, and it always prints "no way id".

**Comment by emiltin** [comment]
i would start by lookin in https://github.com/Project-OSRM/osrm-backend/blob/725b93a961625a7b04d54806d7e0f80252a6bcd0/extractor/scripting_environment.cpp where the luabind link to c++ is defined

**Comment by bjtaylor1** [comment]
ok cheers, that works.
I can access it as a function and it returns the id.
Should I submit a merge request?

**Comment by emiltin** [comment]
maybe the access by function is intended. @DennisOSRM? if so, then the example should be updated.

**Comment by TheMarex** [comment]
This seems to be a regression from the switch to libosmium. @bjtaylor1 you added a binding for osmium::Way::id() ? Pull requests are always welcome! :+1:

**Comment by bjtaylor1** [comment]
Yes. I just created a pull request for it.
