### ISSUE TITLE
Osmium Compilation Error at cast.hpp "static_cast_with_assert"

### ISSUE THREAD

**Issue by htmlrb** [Project-OSRM/osrm-backend#1370]
Hi all,
When building OSRM on VS2013 I get this error (the osrm-extract failed)
>
13>D:\Garage\DevCamp\osrm-backend\third_party\osmium/util/cast.hpp(66): warning C4018: '<=' : signed/unsigned mismatch
13>          D:\Garage\DevCamp\osrm-backend\third_party\osmium/io/bzip2_compression.hpp(115) : see reference to function template instantiation 'T osmium::static_cast_with_assert<int,unsigned int,0>(const F)' being compiled
13>          with
13>          [
13>              T=int
13>  ,            F=unsigned int
13>          ]
13>D:\Garage\DevCamp\osrm-backend\third_party\osmium/util/cast.hpp(58): error C2338: unnecessary static_cast_with_assert when casting into type of equal or larger size
13>          D:\Garage\DevCamp\osrm-backend\third_party\osmium/io/bzip2_compression.hpp(224) : see reference to function template instantiation 'T osmium::static_cast_with_assert<unsigned int,size_t,0>(const F)' being compiled
13>          with
13>          [
13>              T=unsigned int
13>  ,            F=size_t
13>          ]
14>D:\Garage\DevCamp\osrm-backend\data_structures\hilbert_value.cpp(69): warning C4800: 'uint32_t' : forcing value to bool 'true' or 'false' (performance warning)
...
========== Build: 15 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by DennisOSRM** [comment]
Are you using stock VS2013 or the CTP?

**Comment by htmlrb** [comment]
CTP

**Comment by DennisOSRM** [comment]
Issue should be reported to lib osmium: https://github.com/osmcode/libosmium
