### ISSUE TITLE
Documentation bug: osrm-routed requires a map parameter

### ISSUE THREAD

**Issue by xicesky** [Project-OSRM/osrm-backend#1372]
I followed the instructions on: https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM
But the step "Running the Engine" fails with the ominous error message:
```
    [warn] exception: .hsgr not found: .hsgr
```

It works if you run it with the map as a parameter:
```
    osrm-routed map.osrm
```
But the documentation explicitly states: "If you run the command [...] without any parameters, it is fully controlled by a config file named server.ini."

Related bug:
https://github.com/Project-OSRM/osrm-backend/issues/1093

(Note: My server.ini *does* contain the correct path to the .hsgr file, i copied the one directly from the documentation)

**Comment by TheMarex** [comment]
Maybe a regression in the options parsing that requires a file name, always. Will investigate.

**Comment by DennisOSRM** [comment]
Thanks for the report. Updated the wiki page. `server.ini` was deprecated some time ago.
