### ISSUE TITLE
"Your route is being computed"

### ISSUE THREAD

**Issue by ZupoLlask** [Project-OSRM/osrm-backend#1376]
Dear Community,

I have already inspected and fixed all the potential issues detected in this area's ways (3 days ago).

Does anyone know why there's no routing between these 2 points?
- http://map.project-osrm.org/?loc=41.18515,-8.68462&loc=41.184467,-8.685338

Thanks!

**Comment by emiltin** [comment]
did you check turn restrictions?

**Comment by DennisOSRM** [comment]
There's temporary data (red in image below) of `highway=road`. These are ignored on purpose and easy to fix.

![screenshot 2015-02-09 14 11 44](https://cloud.githubusercontent.com/assets/1067895/6106894/ba0bf7c8-b065-11e4-821b-06739fb6e419.png)

**Comment by ZupoLlask** [comment]
Thanks @DennisOSRM ! I wasn't aware of that "temporary data" detail. Fixed.
