### ISSUE TITLE
turn restriction only_straight_on not respected

### ISSUE THREAD

**Issue by suschtenname** [Project-OSRM/osrm-backend#1377]
When editing OSM and doing some sanity checks with Project-OSRM, I encountered similar routing issues as in #1286.

In the route http://osrm.at/aVm the turn restriction http://www.openstreetmap.org/relation/4575219 was not respected. After inverting the direction of the from-role (way 252177264, http://www.openstreetmap.org/way/252177264), the correct route was calculated.

I tested with the latest version from the master branch (commit 725b93a961 from 6. Jan 2015).

**Comment by hlaw** [comment]
A similar issue at #1346 was subsequently fixed, which might perhaps also fix this issue?

**Comment by suschtenname** [comment]
I stripped down and simplified the OSM file and stored it on a [gist](https://gist.github.com/suschtenname/20f6ab3146f94322b02e) as reference.

**aarau-nok.osm** with the ignored turn restriction
![aarau-nok](https://cloud.githubusercontent.com/assets/10931510/6154112/7729ce2e-b229-11e4-8a54-9b324d66bed8.png)

**aarau-ok.osm** with correct routing
![aarau-ok](https://cloud.githubusercontent.com/assets/10931510/6154121/80a6301e-b229-11e4-8010-86ea8b4f258c.png)

The only difference between the two maps is the reversed direction of the street named Laurenzenvorstadt.

**Comment by DennisOSRM** [comment]
Thanks for preparing the file. Will be helpful when debugging this

**Comment by emiltin** [comment]
note that you can use load .osm files from cucumber tests

**Comment by MoKob** [comment]
<img width="1254" alt="screen shot 2016-08-16 at 11 28 35" src="https://cloud.githubusercontent.com/assets/12932279/17694543/a1f92dba-63a4-11e6-9c6a-71f34c931d7e.png">

This issue seems to be fixed by now.
