### ISSUE TITLE
Long requests fail to parse

### ISSUE THREAD

**Issue by neilbu** [Project-OSRM/osrm-backend#1379]
If a viaroute/table call is made with a large number of query string parameters (i.e. 1500+ characters), parsing will periodically fail because the request parser is constructed on demand.  Any state from parsing the previous part of the request is lost...apologies if this is a deliberate thing, but thought I'd mention it since it (occasionally) mars what is otherwise a work of pure genius!

**Comment by DennisOSRM** [comment]
Got an example call?

**Comment by neilbu** [comment]
Sorry - yes:

/viaroute?loc=52.4915809631348,-1.70719349384308&loc=52.33011,-2.06900&loc=52.33006,-2.06669&loc=52.35761,-2.10684&loc=52.36779,-2.09580&loc=52.30278,-1.87259&loc=52.38830,-1.83797&loc=52.38274,-1.83594&loc=52.41126,-1.83564&loc=52.41225,-1.83334&loc=52.41407,-1.80643&loc=52.40444,-1.79746&loc=52.39688,-1.77723&loc=52.38927,-1.73497&loc=52.37834,-1.74426&loc=52.37978,-1.75718&loc=52.35567,-1.77803&loc=52.29075,-1.77287&loc=52.29860,-1.94881&loc=52.30939,-1.94836&loc=52.30913,-1.96591&loc=52.30582,-1.96650&loc=52.30761,-1.96333&loc=52.41204,-1.52016&loc=52.51476,-1.50834&loc=52.52465,-1.49426&loc=52.52110,-1.45990&loc=52.50008,-1.44004&loc=52.52155,-1.47359&loc=52.52165,-1.47260&loc=52.48285,-1.48608&loc=52.48538,-1.46666&loc=52.38655,-1.26244&loc=52.38655,-1.26244&loc=52.37313,-1.27595&loc=52.37013,-1.25158&loc=52.36142,-1.29165&loc=52.35362,-1.28822&loc=52.36887,-1.28542&loc=52.39801,-1.24093&loc=52.40380,-1.24463&loc=52.31101,-1.31287&loc=52.32517,-1.20603&loc=52.39697,-1.47673&loc=52.39846,-1.46762&loc=52.39766,-1.44536&loc=52.39161,-1.42259&loc=52.38926,-1.46930&loc=52.38094,-1.46975&loc=52.38596,-1.49554&loc=52.37709,-1.51185&loc=52.38542,-1.52236&loc=52.28276,-1.51581&loc=52.27558,-1.50110&loc=52.27618,-1.52642&loc=52.30285,-1.53817&loc=52.30268,-1.53743&loc=52.30499,-1.51458&loc=52.25020,-1.54796&loc=52.29648,-1.58219&loc=52.27929,-1.59440&loc=52.27632,-1.57984&loc=52.15199,-1.51844&loc=52.15797,-1.50452&loc=52.23061,-1.74052&loc=52.23741,-1.68848&loc=52.19353,-1.70282&loc=52.18329,-1.68387&loc=52.17498,-1.78906&loc=52.40322,-1.58037&loc=52.41034,-1.59977&loc=52.21567,-1.43025&loc=52.21825,-1.42501&loc=52.16570,-1.44385&loc=52.39847,-1.51839&loc=52.42119,-1.52888&loc=52.42928,-1.51635&loc=52.42860,-1.51312&loc=52.43131,-1.51267&loc=52.43378,-1.51183&loc=52.44641,-1.51330&loc=52.42881,-1.50628&loc=52.45244,-1.47534&loc=52.43370,-1.48845&loc=52.43066,-1.47952&loc=52.46141,-1.68636&loc=52.39616,-1.64801&loc=52.46570,-1.56026&loc=52.50451,-1.56883&loc=52.46141,-1.53480&loc=52.35089,-1.56472&loc=52.35070,-1.56020&loc=52.36399,-1.44832&loc=52.39249,-2.25387&loc=52.39343,-2.24260&loc=52.38097,-2.23485&loc=52.42187,-2.36469&loc=52.34435,-2.27608&loc=52.37484,-2.48665&loc=52.43499,-2.14458&loc=52.29222,-1.19999&loc=52.19589,-2.21822&loc=52.15929,-1.95981&loc=52.14339,-1.92581&loc=52.17324,-1.92153&loc=52.20486,-2.21215&loc=52.21477,-2.20337&loc=52.21109,-2.18575&loc=52.20938,-2.19727&loc=52.33968,-2.14898&loc=52.25014,-2.13732

I came across it when putting together a wrapper around viaroute for distance (as opposed to time) tables, hence the slightly mad route...somewhat oddly, it would work fine on my local build (on Ubuntu Desktop 14.04) but fail when deployed on an Ubuntu server...because the request was only chopped up into smaller chunks on the server but would come through in one chunk when debugging.

I hope that makes some sort of sense!

Kind regards
Neil

**Comment by neilbu** [comment]
p.s. For my purposes, I just made the RequestParser a property of the connection object so that subsequent strings made it to the "we don't have a result yet, so continue reading" section of Connection::handle_read. With RequestParser created on demand, long requests were often (but not always) treated as bad requests because the new RequestParser was expecting the start of a request.

**Comment by DennisOSRM** [comment]
Patches are welcome :-)

If you like to share your changes, we can take that as a baseline to properly fix the issue.

**Comment by neilbu** [comment]
Will do!

**Comment by DennisOSRM** [comment]
Thx. Much appreciated

**Comment by TheMarex** [comment]
:+1: Closing.
