### ISSUE TITLE
Significant difference between OSRM and Google (or Bing Route)

### ISSUE THREAD

**Issue by zbychuk** [Project-OSRM/osrm-backend#1382]
I have planned route between two points in Japan ( osrm.at/aXA and https://goo.gl/maps/jZKsr)
As the route were different, U have forced Google to get more or less the same route as OSRM planned. 
What worries me is however significant difference in time (27 minutes when not considering traffic on 2 hours and 13 minutes route makes 20% difference)
Any idea what can cause it?

**Comment by TheMarex** [comment]
Thanks for you bug report!

20% is normal. The ETA on OSRM is a pretty rough estimate, but works reasonably well in most cases. You can help improve the ETA quality by adding corresponding "maxspeed" tags to the roads.

We are currently working on ways to derive more precise ETAs.

**Comment by DennisOSRM** [comment]
As @TheMarex pointed out there's some difference to be expected. One of the reasons is that we don't have too many country-specific rules in our setup yet. Default maxspeeds vary greatly countries and we may not be aware what they are and how they are tagged in OSM.

As of recently we started adding default speeds for a number of European countries, e.g. see [here](https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/car.lua#L105-L126). We are happy to add more and more country-specific rules to that list.

**Comment by zbychuk** [comment]
Sorry - did not mean my issue to sound as critisizm. Just a small issue for
your information. As for Japan - I have checked in wiki
http://en.wikipedia.org/wiki/Speed_limits_in_Japan
These are strange limits from European point of view
