### ISSUE TITLE
Distance by road shorter than flying bird distance distance 

### ISSUE THREAD

**Issue by zbychuk** [Project-OSRM/osrm-backend#1383]
According to your map (and service) distance by road: 
`http://map.project-osrm.org/?df=0&loc=52.981206,-1.236637&loc=52.981202,-1.236213` 
is 13m, while those point are 28m apart in straight line

**Comment by porjo** [comment]
I'm not sure I understand. The directions say:
```
Head east                                   12 m
Enter roundabout and leave at first exit    17 m
```
Route distance = 29m and straight line distance = 28m ... what's the problem?
