### ISSUE TITLE
Building Error FingerPrint::FingerPrint() no defined

### ISSUE THREAD

**Issue by Carsten64** [Project-OSRM/osrm-backend#1385]
Hello together,

I get struggled by building OSRM in Netbeans. When I try to build OSRM the following Error occur:

components.cpp:(.text+0x15e7): referencia a `FingerPrint::~FingerPrint()' sin definir
components.cpp:(.text+0x15f6): referencia a `FingerPrint::~FingerPrint()' sin definir
components.cpp:(.text+0x183a): referencia a `OGRLineString::~OGRLineString()' sin definir
components.cpp:(.text+0x1920): referencia a `FingerPrint::~FingerPrint()' sin definir
components.cpp:(.text+0x1937): referencia a `FingerPrint::~FingerPrint()' sin definir
build/Debug/GNU-Linux-x86/_ext/1483342605/io-benchmark.o: En la función `main':
io-benchmark.cpp:(.text+0x245): referencia a `g_GIT_DESCRIPTION' sin definir
build/Debug/GNU-Linux-x86/_ext/1483342605/simpleclient.o: En la función `main':
simpleclient.cpp:(.text+0x265): referencia a `g_GIT_DESCRIPTION' sin definir
build/Debug/GNU-Linux-x86/_ext/1483342605/springclean.o: En la función `main':
springclean.cpp:(.text+0x2a1): referencia a `g_GIT_DESCRIPTION' sin definir
build/Debug/GNU-Linux-x86/_ext/1483342605/unlock_all_mutexes.o: En la función `main':
unlock_all_mutexes.cpp:(.text+0x4c): referencia a `g_GIT_DESCRIPTION' sin definir
collect2: error: ld returned 1 exit status
make[2]: *** [dist/Debug/GNU-Linux-x86/osrm2] Error 1
make[2]: se sale del directorio «/home/wtprestamo3/osrm/project/osrm2»
make[1]: *** [.build-conf] Error 2
make[1]: se sale del directorio «/home/wtprestamo3/osrm/project/osrm2»
make: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 6m 45s)

means that all constructors and functions of  FingerPrint are not defined. After I looked in the folder I saw that just a FingerPrint.h is defined but not a FingerPrint.cpp. Is the *.cpp missing or how are the function defined?

Kind regards

Carsten

**Comment by DennisOSRM** [comment]
the fingerprint compile unit is generated by cmake every time a build is run. The contents of this file may change depending on changes in other files.
