### ISSUE TITLE
road preference

### ISSUE THREAD

**Issue by jzvc** [Project-OSRM/osrm-backend#1387]
Think there are some wrong settings for road vs distance preference.

http://www.openstreetmap.org/directions?engine=osrm_car&route=50.5810%2C13.9268%3B50.5771%2C13.9287#map=17/50.57886/13.92983

**Comment by DennisOSRM** [comment]
We have a number of issues on this problem. It essentially boils down to having some model that gives the penalties incurred by leaving a road to take shortcuts on somewhat less important roads.

**Comment by TheMarex** [comment]
However we should send a note to the OSM people because they seem to always pass ```z=14``` which causes the DP to be a little bit aggressive in this case.

![screenshot from 2015-02-18 18 29 18](https://cloud.githubusercontent.com/assets/606968/6252663/37da8fd8-b79c-11e4-83d0-7d6ddbcfe324.png)

**Comment by DennisOSRM** [comment]
> However we should send a note to the OSM people because they seem to always pass z=14 which causes the DP to be a little bit aggressive in this case.

Already done.

**Comment by jzvc** [comment]
For sure, it's not about map zoom, it's about Route>

Distance: 0.29 km
Duration: 21 s

Head southeast onto 8 	55 m
Turn slight right 	54 m
Turn slight right 	0.11 km
Turn slight left 	29 m
Turn slight right onto 8 	43 m

VS

Distance: 0.31 km
Duration:22 s

Head southeast onto 8 	0.14 km
Reaching intermediate destination on 8 	0.16 km

(from http://map.project-osrm.org/ with 3rd point for enforcement)	

When someone want use that in unknown locality... 
Maybe some sort of time/length penalization on road type can work? Say +30% for streets and little less for tertiarry/secondary/? And/Or some penalty for turns?

For that little example, when I use 1s (and in real, this is not possible) for turn, then I have not 21s vs 22s, but 25s vs 22s.

**Comment by TheMarex** [comment]
The only way to fix this is using a turn penalty. This is tracked in https://github.com/Project-OSRM/osrm-backend/issues/477
