### ISSUE TITLE
car.lua should strongly disprefer width<3 two-way streets

### ISSUE THREAD

**Issue by grinapo** [Project-OSRM/osrm-backend#1388]
Anything narrower than 2 meters is usually not fit for car traffic at all (regardless of whether it's permitted or not); anything less than 3 meters and two-way is strongly not preferred since you may have to go backwards the whole way if anyone comes in the opposite direction. 

Edit by @DennisOSRM:

- [x] implement width penalty
- [x] implement lane penalty

**Comment by DennisOSRM** [comment]
thats a good point. whats the tagging?

**Comment by TheMarex** [comment]
```width``` seems to be the one used for the actual width of a way:
http://taginfo.openstreetmap.org/keys/width#combinations
It is surprisingly common.

**Comment by DennisOSRM** [comment]
Good findings @TheMarex.

I'd say we ignore anything below 2m and also put a good penalty on anything below 3m. I am thinking of halving the speed.

Opionions @grinapo @TheMarex @emiltin ?

**Comment by lonvia** [comment]
There is also the [lanes](http://wiki.openstreetmap.org/wiki/Key:lanes) tag. `lanes=1` without oneway should get a mild penalty, too.

**Comment by DennisOSRM** [comment]
Good point @lonvia.

I am in the middle of preparing a pull request for that feature. Once it's there will ping everyone on this ticket.

**Comment by emiltin** [comment]
different vehicles have different width. for exaple ignoring narrow roads would make the profile much less functional for motorcycles. for this reason i would be careful with outright ignoring roads, and istead just lower the speed. like with maxspeed, i would compute a speed depending on with and lanes, and use it in the general maxspeed algorithm. if maxspeed is already 5km/h a narrow road should not lower the speed further.

**Comment by DennisOSRM** [comment]
PR https://github.com/Project-OSRM/osrm-backend/pull/1390 implements this now in a basic way. Happy to merge if there are no objections.

**Comment by emiltin** [comment]
i don't think speed should be simple scaled by half. if the spees is already low, then it doesn't make sense to further half it. i would look at it as just another 'maxspeed'

**Comment by Skippern** [comment]
Full stop at entry of the one-lane, and 25% off from maxspeed for possible waiting time sounds reasonable to me

Aun Johnsen

**Comment by DennisOSRM** [comment]
@emiltin can you elaborate on what you mean by another maxspeed?

**Comment by emiltin** [comment]
the maxspeed computation is basically taking the lowest of a number of inputs, rather than multiplying them. a narrow width could be another input to that algorith.

ex fast road, narrow road means you need to slow down:
```
highway=primary      => 80 km/h
maxspeed=50       => 50 km/h
width=2           => 20 km/h
result = min(80,50,20) = 20
```

ex slow road, narrow road doesn't cause further slow down:
```
highway=residential      => 40 km/h
maxspeed=10       => 10 km/h
width=2           => 20 km/h
result = min(40,10,20) = 10
```

**Comment by DennisOSRM** [comment]
make sense, thanks for the clarification. should be straight-forward to implement.

**Comment by DennisOSRM** [comment]
implemented as suggested by @emiltin

**Comment by DennisOSRM** [comment]
The width penalty support has been merged.

**Comment by socketpair** [comment]
Where I can read about all penalties implemented?

**Comment by TheMarex** [comment]
@socketpair have a look at the [profiles](https://github.com/Project-OSRM/osrm-backend/tree/develop/profiles)

**Comment by TheMarex** [comment]
All done.
