### ISSUE TITLE
Use Pearce SCC algorithm for component analysis

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#1392]
Will be faster and needs much less memory than Tarjans canonical algorithm.

**Comment by TheMarex** [comment]
We are talking about [this algorithm](http://damclubijmuiden.nl.server22.firstfind.nl/performance-rating/scc-10.1.1.102.1707-David-J-Pearce.pdf) right?

**Comment by DennisOSRM** [comment]
yep

**Comment by DennisOSRM** [comment]
Pearces algorithm is surprisingly simple. Implementing a recursive variant is a matter of copy-and-pasting the pseudo code from the paper. The more challenging aspect is implementing an iterative variant that doesn't use the system stack.

**Comment by DennisOSRM** [comment]
Note to self: push children in reverse order onto stack in iterative variant to preserve DFS order of the traversal.
