### ISSUE TITLE
obvious route remains unresolved

### ISSUE THREAD

**Issue by mitsol** [Project-OSRM/osrm-backend#1393]
This route remains unresolved, even though it seems all right!
http://map.project-osrm.org/?hl=de&loc=46.998797,12.482314&loc=47.000407,12.538834&z=16&center=46.996163,12.486273&alt=0&df=0&re=0&ly=763558683

**Comment by emiltin** [comment]
dragging across the point where the route disappears sometimes result in visual anomalities:


![screen shot 2015-02-24 at 21 47 23](https://cloud.githubusercontent.com/assets/66034/6358832/c919a2be-bc6e-11e4-9e2e-061230646f49.png)

**Comment by TheMarex** [comment]
http://www.openstreetmap.org/node/2430158089

Someone put a lift gate with a strange tagging there. Has anyone an idea how to tag this correctly?

@emiltin Do you have a link for the artifact?

**Comment by emiltin** [comment]
similar problem here? http://osrm.at/b6R
![screen shot 2015-02-25 at 07 50 31](https://cloud.githubusercontent.com/assets/66034/6366248/05c94b70-bcc3-11e4-8ad9-11a052811c35.png)

**Comment by emiltin** [comment]
sorry don't have a link to the artifact, it dissapeared when not dragging anymore. but you can see from the screenshot where the markers where placed.

**Comment by emiltin** [comment]
another gate, taggged with barrer=normally_open_lift_gate

https://www.openstreetmap.org/node/1393799172

**Comment by DennisOSRM** [comment]
This is crappy tagging, indeed. It should be a simple `barrier=lift_gate`.

The wiki has an extensive list on conditional access restrictions: http://wiki.openstreetmap.org/wiki/Conditional_restrictions

**Comment by ivantrouvetout** [comment]
same probleme 
http://map.project-osrm.org/?hl=fr&loc=44.833935,5.599008&loc=44.829521,5.607032&z=13&center=44.842603,5.626030&alt=0&df=0&re=0&ly=763558683

**Comment by DennisOSRM** [comment]
@ivantrouvetout the issue is unrelated. Let's not derail this ticket but stick to #1336 where the broken planet file is tracked.
