### ISSUE TITLE
Invalid shortcut on service road

### ISSUE THREAD

**Issue by paulmach** [Project-OSRM/osrm-backend#1394]
See example http://osrm.at/b6H

The loop in the secondary road gets bypassed because there is nice service road short cut. This doesn't make any sense. There is also a gate on the service road in the OSM data. Which should also be avoided/create high cost.

![screen shot 2015-02-23 at 11 48 20 pm](https://cloud.githubusercontent.com/assets/366320/6358477/b2e2336a-bc20-11e4-937f-77664aaed5af.png)

**Comment by emiltin** [comment]
turn penalties would help here too

**Comment by plett** [comment]
Another example of the same problem: http://osrm.at/b7d

It is not possible to join the dual-carriageway road at that point as there are gates which prevent it. The gates are in the OSM data

**Comment by DennisOSRM** [comment]
`access=no` and/or turn restrictions can be used. 

The semantics of `barrier=..` tags is unclear. If one is an actual barrier or not, or passable or not is not necessarily expressed thru the thing being a barrier but auxiliary tags.

**Comment by plett** [comment]
Thanks. The underlying OSM data in my example didn't have correct `access` tags on the gates (they disallowed foot traffic, but didn't mention anything else). I've changed them to be `access=no`.

However http://wiki.openstreetmap.org/wiki/Barriers says "Barriers with undocumented default access imply `access=no`" so in the general case OSRM should not route through barriers. This isn't relevant in my example though, as there were some `access` tags - just not accurate ones.

**Comment by DennisOSRM** [comment]
> so in the general case OSRM should not route through barriers.

And in general it doesn't. There's a number of barrier tags that are not blocking access. So, some have been white listed.

**Comment by paulmach** [comment]
This issue got derailed. Regardless of the gate, that route is incorrect. The image is of zoom 17. Such a shortcut is an incorrect route. It should stay on the secondary road.

**Comment by emiltin** [comment]
separating speed and impedance could also help in cases like this. even when speeds are similar on two types of roads, you can clearly prefer one over the other.

**Comment by DennisOSRM** [comment]
> separating speed and impedance could also help in cases like this. even when speeds are similar on two types of roads, you can clearly prefer one over the other.

duly noted.
