### ISSUE TITLE
Enter and exit roundabout at same node

### ISSUE THREAD

**Issue by jwass** [Project-OSRM/osrm-backend#1395]
I've found many cases where two OSM ways enter and exit a roundabout at the same node. (http://www.openstreetmap.org/edit#map=19/42.29635/-71.14512)
![screen shot 2015-02-25 at 9 47 21 am](https://cloud.githubusercontent.com/assets/1214350/6372961/7dc9b30a-bcd5-11e4-8da5-b5017f72e1e6.png)

If a route enters the roundabout at one of these nodes, it causes OSRM to either
* not detect the roundabout when taking the first exit (same node) http://osrm.at/b7h (says "slight right" in the example)
![screen shot 2015-02-25 at 9 46 55 am](https://cloud.githubusercontent.com/assets/1214350/6373481/10c53aa0-bcd9-11e4-8981-37b3d0b06f1b.png)

* miscount the exit number http://osrm.at/b7i (second exit counting as first exit)
![screen shot 2015-02-25 at 9 47 10 am](https://cloud.githubusercontent.com/assets/1214350/6373484/15adf61a-bcd9-11e4-89ba-fbf7eb344007.png)

The OSM documentation on `junction=roundabout` (http://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout) says "Each road has to be connected with the roundabout in a separate node, i.e. between these nodes a segment of the roundabout is required. Thus routers can safely recognise that a section of the roundabout has to be driven through." So this is really a problem that should be fixed in the road network, but enforcing this throughout OSM is probably impractical. I also just looked at a bunch of roundabouts near me and this setup is very common - on almost every roundabout.

Seems like OSRM should detect and handle this as if the route enters the roundabout...?

**Comment by DennisOSRM** [comment]
> Seems like OSRM should detect and handle this as if the route enters the roundabout...?

So, what we do is to trust the data to expose any issues. If the route enters a piece of road, i.e. an OSM way, that is tagged with `junction=roundabout` we believe the data. The data should be obvious in the sense that there is second-guessing necessary to figure out what's going on.

How would one distinguish the example you gave from the situation where it perfectly depicts the ground truth.

>  I also just looked at a bunch of roundabouts near me and this setup is very common - on almost every roundabout.

Yep, data is buggy in plenty of places. That's why we expose these issue to get them fixed.

> Each road has to be connected with the roundabout in a separate node, i.e. between these nodes a segment of the roundabout is required. Thus routers can safely recognise that a section of the roundabout has to be driven through."

Makes perfect sense.

@DennisSchiefer @TheMarex anything else to add?

**Comment by jwass** [comment]
@DennisOSRM Sounds good. Thanks.

I guess I was floating the idea that these might not be considered data bugs despite what the OSM wiki says, due to how prevalent these seems to be in OSM. And it seems like an intentional layout by many mappers. It's tough for me to imagine a case where the road would share the node with the roundabout like that but not be considered part of it.

In any case I'll get on fixing what I can. Thanks for taking a look.

**Comment by daniel-j-h** [comment]
![counting](https://cloud.githubusercontent.com/assets/527241/15675526/ac876a06-2742-11e6-917f-57ea25d365b1.png)

![roundabout](https://cloud.githubusercontent.com/assets/527241/15675525/ac5c77e2-2742-11e6-8b16-de2a5dd418f2.png)

:bow: @MoKob
