### ISSUE TITLE
How to create windows service for OSRM-ROUTED MAP.OSRM

### ISSUE THREAD

**Issue by diiogocosta** [Project-OSRM/osrm-backend#1398]
you can run the OSRM routed as windows service with a fixed map?
or how it would be possible to create a service? to run the engine without an active window?

thank you very much!

@DennisOSRM

**Comment by diiogocosta** [comment]
i use only backend for return distances.

**Comment by diiogocosta** [comment]
can you help me please?
@DennisOSRM

**Comment by DennisOSRM** [comment]
This is likely not possible right now. Things have not been implemented to run `osrm-routed` as a service.  The best way would be to use the NodeJS bindings for that purpose. They haven't been ported to Windows though. We'd be happy to consider a pull request.

**Comment by diiogocosta** [comment]
You can help with a example?
@DennisOSRM
