### ISSUE TITLE
bridge:movable (without highway=*) not considered for routing

### ISSUE THREAD

**Issue by kerosin** [Project-OSRM/osrm-backend#1399]
Hey,

Just found a [Note](http://www.openstreetmap.org/note/323257) that complains that routing by foot does not consider a transporter bridge.
![](http://upload.wikimedia.org/wikipedia/commons/a/a9/MovableBridge_transport.gif)

None of the existing routing services on osm.org is able to route across [this movable bridge]
(http://www.openstreetmap.org/way/24676774). car transport (4) and bicycle + foot should are possible. Every 15min this "ferry" is starting (also dependent on ship traffic).

Didn't know about [this scheme](https://wiki.openstreetmap.org/wiki/Key:bridge:movable) before.

Would be great to consider this for routing!

Thanks in advance!

**Comment by DennisOSRM** [comment]
thanks for the heads-up @kerosin. Will give this a good look now.

**Comment by DennisOSRM** [comment]
Feature has been implemented in #1400. Waiting for the CI build servers to confirm that the build is successful and that tests run fine. Will be merging shortly after that.

**Comment by kerosin** [comment]
Wow thanks that was quick! Will a tag like "duration=PT15M" be taken into account for a ferry/transporter bridge like above?

**Comment by DennisOSRM** [comment]
durations will be parsed, yes.

**Comment by DennisOSRM** [comment]
merged and tweeted: https://twitter.com/ProjectOSRM/status/570961190450540544

**Comment by kerosin** [comment]
Wow great thanks! :+1: That was really quick. One last question: Do you assume bridge:movable implements foot=yes; motor_vehicle=yes and bicycle=yes or any access=*? It is not defined in the wiki. Unbiased I would add these tags to the example above.

**Comment by DennisOSRM** [comment]
yeah, the usual access tags are respected. I am going to add capacity:car=* in a bit.

**Comment by emiltin** [comment]
should be implemeted in bike and foot profiles too..

**Comment by DennisOSRM** [comment]
@emiltin will arrive in a bit.

**Comment by emiltin** [comment]
sweet :-)

**Comment by kerosin** [comment]
![](http://i.imgur.com/fBrHA3c.png)
If you look at [this route](https://www.openstreetmap.org/directions?engine=osrm_car&route=54.29428%2C9.68225%3B54.29286%2C9.68306#map=18/54.29357/9.68268&layers=N) the time it takes to cross the canal, that is tagged with duration=PT10M, is calculated as "distance:: 167m. time:: 0:01".
So nearly all routes in that area are choosing this way instead of the tunnel which is most of the time the faster way to choose..
So is duration taken into account or is it maybe a data problem? Thanks for your efforts!

**Comment by DennisOSRM** [comment]
Ah, right ISO 8601 time periods. Will add parser support early next year week

**Comment by DennisOSRM** [comment]
ISO 8601 duration parsing is implemented. will be pushed in a few moments and then go live with the next full update cycle.

**Comment by kerosin** [comment]
Good Job thanks
