### ISSUE TITLE
HTTP service returning 400 Errors (Bad Request)

### ISSUE THREAD

**Issue by Phylogenesis** [Project-OSRM/osrm-backend#1402]
I am having issues with the HTTP service responding to requests with an HTTP 400 BAD REQUEST error when called using PHP's `file_get_contents()` function.

The issue is very intermittent, and a repeat of the exact request will return a valid response.

I have a tcpdump capture file showing two identical requests made seconds apart, where one gives a `400 BAD REQUEST` response and the other gives a `200 OK` response but I am unable to attach it to this issue. It is available on Dropbox [here](https://www.dropbox.com/s/jxn03oyjo1rnzqm/osrm.pcap?dl=0).

**Comment by porjo** [comment]
@Phylogenesis the packet capture shows the request header containing `Host: keuipssv700:5000`. Are you running a local instance of osrm-backend?

Also, try replicating the issue with a low-level tool such as curl. It will allow you to capture the request and response headers, which will be most useful in diagnosing the issue e.g.
```
curl -v "http://<osrm api host>/viaroute?loc=lon,lat&loc=lon,lat&z=18" -o /dev/null
```

**Comment by Phylogenesis** [comment]
@porjo Yes, this is a local instance running on a test server.

Is there actually any more to be gleaned from a curl request that isn't already present in the entire packet capture? However, I shall try to see if I can get it to reproduce using curl.

From the tcpdump output, I can see the HTTP service returning earlier than it should when it responds with a 400 error (it doesn't wait for the second \r\n that signals the end of the request before responding, for instance).

**Comment by vesse** [comment]
I am facing problems as well. Java app using [RxNetty](https://github.com/ReactiveX/RxNetty) receives the query string complaint `{"status_message":"Query string malformed close to position 0","status":400}` even though the query string is present. I've been trying to get the same response with telnet but have been unsuccessful. I too receive the response prematurely like @Phylogenesis:

```
vesse@asok:~/github/osrm-backend/build (master)$ telnet localhost 5000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /nearest?loc=61.497630,23.758859 HTTP/1.1
Host: localhost:5000
HTTP/1.0 400 Bad Request
Access-Control-Allow-Origin: *
Content-Length: 46
Content-Type: text/html

{"status": 400,"status_message":"Bad Request"}
```

If I add an empty line after `GET` the response is still returned before the `\r\n\r\n` but this time it comes with `HTTP 200` and correct result:

```
vesse@asok:~/github/osrm-backend/build (master)$ telnet localhost 5000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /nearest?loc=61.497630,23.758859 HTTP/1.1

Host: localhost:5000HTTP/1.0 200 OK
Content-Length: 75
Content-Type: application/json; charset=UTF-8
Content-Disposition: inline; filename="response.json"

{"name":"Hämeenkatu","mapped_coordinate":[61.497593,23.758871],"status":0}
```

**Comment by vesse** [comment]
OK, RxNetty problem was solved by creating a client separately. But still, that early response to telnet is odd.

**Comment by recallfx** [comment]
I got the same issue after today I updated my local OSRM instance. I have noticed that error is shown only when requests are made from a client browser and not from CURL. After some debugging, I found relevant change in this commit: 38251aa5135af99e3be8ad191b99b3fa9bc38119 file Server/Connection.cpp line 72 and complementary changes in file Server/Connection.h that is causing this issue. Reverting back to static `request_parser` error message is no longer there.

**Comment by danpat** [comment]
Can't reproduce this error with current `osrm-routed`, no updates on this ticket in over a year, no similar reports and our demo server keeps chugging along.

```
$ telnet localhost 5000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /route/v1/driving/103.84766578674316,1.370928586879165;103.84534299373627,1.3696629462731107 HTTP/1.1
Host: localhost:5000

HTTP/1.0 200 OK
Connection: close
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Access-Control-Allow-Headers: X-Requested-With, Content-Type
Content-Type: application/json; charset=UTF-8
Content-Disposition: inline; filename="response.json"
Content-Length: 490

{"waypoints":[{"location":[103.846348,1.370177],"hint":"BAAAgAUAAIADAAAAmAAAAAAAAAAAAAAAAAAAAF8AAABeAAAAAQAAgMyRMAZB6BQA8ZYwBjDrFAAAAAEBHNzTFg==","name":"ANG MO KIO AVENUE 6"},{"location":[103.845465,1.369656],"hint":"AQAAgAMAAIADAAAAFQAAACcAAAAAAAAAAAAAAGEAAABgAAAAAQAAgFmOMAY45hQA3o0wBj7mFAAAAAEBHNzTFg==","name":"ANG MO KIO AVENUE 6"}],"routes":[{"distance":143.8,"duration":20,"legs":[{"distance":143.8,"steps":[],"duration":20,"summary":""}],"geometry":"srjGunyxRRlDrA@"}],"code":"Ok"}
```
