### ISSUE TITLE
Code style and naming conventions

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1403]
Where are we going with the class/function naming conventions? Currently the code is in a flux between camel-case and underscore.
Lets capture this in an issue to avoid any unnecessary style fixes.

Current proposal:
- Capitalized camel-case class names
- Lower-case underscore variable names
- Lower-case underscore function names
- Lower-case underscore namespace names

**Comment by TheMarex** [comment]
Using something similar to the ROS C++ coding guidelines would be best. http://wiki.ros.org/CppStyleGuide

Seeing that almost all class names are CamelCase we should enforce this and make this consistent until the next release over the whole codebase.

**Comment by daniel-j-h** [comment]
Tasks:

- [ ] decide on style
- [ ] implement in a cncc style file
- [ ] update code base globally using cncc

References:

- [cncc](https://github.com/mapbox/cncc)
- [default cncc style file](https://gist.github.com/daniel-j-h/da8722321366764acef1) with all available kinds
- [dump_ast.sh](https://github.com/mapbox/cncc/blob/b6f5c61c314a2a2bd6ccf1e5a19b3c1b3e835d0e/util/dump_ast.sh) for generating the Clang AST

**Comment by TheMarex** [comment]
> decide on style

Given the current distribution of styles, I think we should favor CamelCase LLVM-like styling before std-like styling.

**Comment by TheMarex** [comment]
@daniel-j-h Let's do this in one go after @danpat merged his traffic data branch, to not make merging more painful than necessary.

**Comment by TheMarex** [comment]
Running this out post-release.

**Comment by TheMarex** [comment]
Was part of this https://github.com/Project-OSRM/osrm-backend/pull/1848 but I think `cncc` missed a fair amount of misnamed symbols. Any idea @daniel-j-h?

**Comment by daniel-j-h** [comment]
Hmm how did you invoke it? I can still find violations simply by doing

    find src -type f | xargs cncc --style .cncc.style --dbdir build

**Comment by daniel-j-h** [comment]
We might also have dead code that never gets compiled and thus never ends up in the compile commands db. Never thought about this actually.

**Comment by daniel-j-h** [comment]
Something went wrong here, look what I got from running it:

    $ wc -l cncc.txt
    461 cncc.txt

Here's the output / todo list:

https://gist.github.com/daniel-j-h/85acaf3f5d233c86dce7

**Comment by TheMarex** [comment]
Hm yes my output was a lot smaller. We can do a second round based on that list. Just would like to merge the two bigger PRs first.

**Comment by TheMarex** [comment]
I did a second pass on this. We have still some rough spots, but overall I think we are in a good position now.
