### ISSUE TITLE
Dont work routing on http://map.project-osrm.org/

### ISSUE THREAD

**Issue by altair86** [Project-OSRM/osrm-backend#1404]

**Comment by porjo** [comment]
Yes, public OSRM routing backend appears to be down. I'm getting HTTP 502 (bad gateway) errors. OSRM Twitter feed posted this tweet 9hrs ago:
> We appear to suffer from network issues internally. Bear with us while we look into it.

 I can only presume they are still working on it! :stuck_out_tongue_closed_eyes:

**Comment by DennisOSRM** [comment]
Thanks for the notifications. We are waiting for the server to come back on shortly.
