### ISSUE TITLE
strange course of a route at roundabouts (out of line with highway)

### ISSUE THREAD

**Issue by kerosin** [Project-OSRM/osrm-backend#1408]
![](http://i.imgur.com/qyMuqVH.png)
This happens on [osm.org](http://www.openstreetmap.org/directions?engine=osrm_car&route=54.28778%2C9.67845%3B54.28735%2C9.67907#map=19/54.28755/9.67861&layers=N) and [osrm.at](http://osrm.at/bf7). Couldn't reproduce this on osrm frontend2 because entering coordinates didn't work as expected.

When dragging the markers around everything falls back as you would expect a course on a roundabout.
This seems to occur only sometimes. See [another examples](http://www.openstreetmap.org/directions?engine=osrm_car&route=54.28460%2C9.66230%3B54.29220%2C9.68410#map=19/54.28746/9.67811) (zoom to roundabout).

//edit: hard to reproduce on osrm.at but also occurs there:
![](http://i.imgur.com/p0vAHAq.png)

**Comment by TheMarex** [comment]
The bug on OSM.org is known. Basically they don't use the API correctly.

The only way I can see how this could occur in project-osrm.org is if a response gets skipped/lost on zooming in.

Can you elaborate what was different when entering in coordinates in the v2 frontend?

**Comment by DennisOSRM** [comment]
cc @richardf

**Comment by DennisOSRM** [comment]
IIRC, there was a race condition (or something similar) in the V1 frontend, where you can end up with the geometry of another zoom level on display. This is less of a backend issue, but a frontend thing.

**Comment by systemed** [comment]
The coarser geometries on osm.org aren't really a bug per se - it's a tossup between having a greater zoom level and losing the "small islands" tolerance, which is currently [hardcoded](https://github.com/Project-OSRM/osrm-backend/blob/725b93a961625a7b04d54806d7e0f80252a6bcd0/data_structures/static_rtree.hpp#L577) to only apply at <z14. It would be good to be able to specify ignore_tiny_components separately in the query string.

**Comment by DennisOSRM** [comment]
> it's a tossup between having a greater zoom level and losing the "small islands" tolerance, which is currently hardcoded to only apply at <=z14. 

Good news. That behavior changed a couple of months ago. The zoom level only has influence on the level of geometry coarsening. It is not a threshold for ignoring small components anymore.

**Comment by systemed** [comment]
Excellent. What zoom level would you suggest as a default then? (Obviously we'd rather stick with one consistent zoom level rather than rerequesting at a different level every time the user zooms in/out.)

**Comment by DennisOSRM** [comment]
I'd say to request the route every time the user zooms in.

**Comment by kerosin** [comment]
@TheMarex 
>Can you elaborate what was different when entering in coordinates in the v2 frontend?

1) open http://project-osrm.org/osrm-frontend-v2/
2) search "54.28778, 9.67845" compare it to [osm.org](http://www.openstreetmap.org/?mlat=54.28778&mlon=9.67845) marker at same lat/lon (frontend1 is also displaying the wrong name of the street, but correct position of the marker)

**Comment by daniel-j-h** [comment]
Fixed:

http://map.project-osrm.org/?z=18&center=54.287552%2C9.678606&loc=54.287781%2C9.678453&loc=54.287369%2C9.679076&hl=en&ly=&alt=&df=&srv=

![roundabout](https://cloud.githubusercontent.com/assets/527241/12265890/2396858a-b940-11e5-83cc-ce037a0bcebc.png)


> The bug on OSM.org is known. Basically they don't use the API correctly.

Still an issue on osm.org, but nothing on our side. Closing here.
