### ISSUE TITLE
Problem with instructions when one of the instructions contains double quote

### ISSUE THREAD

**Issue by zbychuk** [Project-OSRM/osrm-backend#1410]
When requesting route and found route contains leg which has a name containing double quote, the returned json is incorrect.
For example (the name is Aleja "Solidarnosci") :
``http://router.project-osrm.org/viaroute?geometry=true&instructions=true&loc=52.24102,20.98586&loc=52.24236,20.99453``

**Comment by TheMarex** [comment]
Thanks for the bug report! Should be easy to fix.

**Comment by Grzegosh** [comment]
When will you fix this? 
This is very important thing.

**Comment by DennisOSRM** [comment]
thanks for the ping. I'll look into it.

**Comment by DennisOSRM** [comment]
A fix is only minutes away now. Was a rather dull error and indeed an easy fix. Will push once test suite returns positive locally.

**Comment by DennisOSRM** [comment]
The fix will be automatically deployed to the demo site with the next round of updates. That should occur within the next few hours.

**Comment by DennisOSRM** [comment]
Works now.
