### ISSUE TITLE
output of osrm-extract

### ISSUE THREAD

**Issue by crifepaul** [Project-OSRM/osrm-backend#1411]
I have build and installed OSRM and dowloaded the map great-britain-latest.osm. 
---------------
[root@osrm build]# osrm-extract great-britain-latest.osm
[info] Input file: great-britain-latest.osm
[info] Profile: profile.lua
[info] Threads: 1
[info] Using script profile.lua
[STXXL-MSG] STXXL v1.4.99 (prerelease/Release) (git b1fb9ce960fd76f4682cced0b10f4166245fd3ef) + gnu parallel(20140120)
[STXXL-MSG] Disk '/home/stxxl' is allocated, space: 9536 MiB, I/O implementation: syscall queue=0 devid=0
---------------

osrm-extract is running too long (15hrs) and still not completed. Is there any way to see the real-time status of this command, so that I can confirm its working or not?

VPS configuration is 1GB ram, 30GB disk space, 1 core processor.

**Comment by drewlesueur** [comment]
I would also like to know this. Mine has been running for about 8 hours, and I don't know if it's working or not.

PS. (OSRM is awesome)
