### ISSUE TITLE
Add option Direction of Travel  hints to start, end and via points

### ISSUE THREAD

**Issue by woodbri** [Project-OSRM/osrm-backend#1413]
We have a need to be able to specify the direction of travel when arriving or departing from starting, ending or via point. This is somewhat related to #1389 and maybe some other issues. The use case for this is that on two way roads if we have a location that is say on the right or left side of the street and we want to arrive at or depart from that location on that side of the street there is no easy way to control this. The use cases for this is pickup or delivery services. Think about children or handicapped and not wanting them to cross the street or package delivery or trash collection. All these cases require some means to the direction of approach/departure from the location. This issues was also discussed on osrm-talk.

**Comment by systemed** [comment]
Would also be really useful in the dual-carriageway case.

i.e. when planning a route from (lat1,lon1 heading east) to (lat2,lon2 heading east), start with the carriageway nearest to lat1,lon1 which has an eastbound one-way direction, even if the other carriageway is slightly nearer lat1,lon1.

**Comment by emiltin** [comment]
i think this is a duplicate to #605

**Comment by woodbri** [comment]
Yes, I thought there was another issue for this but I could not find it. I will move these comments to #605 and then close this one.

**Comment by woodbri** [comment]
closing as duplicate.
