### ISSUE TITLE
weird shape

### ISSUE THREAD

**Issue by zhiqiangZHAO** [Project-OSRM/osrm-backend#1415]
compare the 2 following results:
http://www.openstreetmap.org/directions?engine=osrm_car&route=38.95103%2C-77.40297%3B38.95082%2C-77.40479#map=18/38.95102/-77.40388

http://www.openstreetmap.org/directions?engine=osrm_car&route=38.95111%2C-77.40283%3B38.95082%2C-77.40479#map=18/38.95102/-77.40381

The shapes are so weird.

**Comment by emiltin** [comment]
It's the osm.org website that's using the osrm api a bit wrong (wrong z parameter), causing the geometry to be simplified too much.

**Comment by TheMarex** [comment]
Not really a bug on our side. Sorry. As @emiltin said, the nice folks that run osm.org should fix that.
