### ISSUE TITLE
Cannot find route between points

### ISSUE THREAD

**Issue by TheWind3** [Project-OSRM/osrm-backend#1417]
OSRM cannot find any route to sime point. For example, 55.726231,37.756256.

Viaroute requets/respose:
http://server:5000/viaroute?loc=55.726231,37.756256&loc=55.726231,37.759209
{"status":207,"status_message":"Cannot find route between points"}

Nearest request/response:
http://server:5000/nearest?loc=55.726231,37.756256
{"status":0,"mapped_coordinate":[55.726231,37.756256],"name":""}

This point (55.726231,37.756256) locates near service route, with is, in turn, locates near primary road.

Debug build of osrm-routed while processing viaroute request craches with message:
"Expression: vector iterator not dereferencable"

Environment:
Real machine (not VM), Windows server 2012 R2
osrm build date: March 10 2015 15:03:26

**Comment by TheMarex** [comment]
What osrm version are you using? The develop branch?

There seems to be indeed some sort of edge case for the small-component detection here.
http://map.project-osrm.org/?hl=en&loc=55.726282,37.756324&loc=55.726231,37.759209&z=18&center=55.726169,37.757156&alt=0&df=0&re=0&ly=763558683

The start is behind a ```lift_gate```, the coordinate lookup should find a node before the gate. Needs investigation.

**Comment by TheWind3** [comment]
TheMarex, thank you for your answer.

Yes, i am using last developer version of OSRM (at the moment when first message was written).

Your assumption about this OSRM behaviour reason was correct: I comments some code in node_function() in car.lua, and OSRM was able to compute route.
```lua
function node_function (node, result):
--MY COMMENT BEGIN
--[[
  -- parse access and barrier tags
  local access = find_access_tag(node, access_tags_hierachy)
  if access ~= "" then
    if access_tag_blacklist[access] then
      result.barrier = true
    end
  else
    local barrier = node:get_value_by_key("barrier")
    if barrier and "" ~= barrier then
      if barrier_whitelist[barrier] then
        return
      else
        result.barrier = true
      end
    end
  end
--]]
--MY COMMENT END
...
end
```

Also, there are some situations with similar behavior.
For example, OSRM can not find route from A to B:
http://localhost:5000/viaroute?loc=55.659624755041,37.551527188987&loc=55.612045640724,37.732799427242
... but can find reverse route, from B to A:
http://localhost:5000/viaroute?loc=55.612045640724,37.732799427242&loc=55.659624755041,37.551527188987
This is, perhaps, because one endpoint snaps to oneway road.
After commenting some oneway checks in car.lua OSRM was able to route:
```lua
function way_function (way, result)
...
--MY COMMENT BEGIN
--[[ 
  -- check if oneway tag is unsupported
  local oneway = way:get_value_by_key("oneway")
  if oneway and "reversible" == oneway then
    return
  end
--]] 
--MY COMMENT END
...
end
```

So, although there is an issue, you points me acceptable workaround. Thank you again :)
