### ISSUE TITLE
no_left_turn restriction ignored

### ISSUE THREAD

**Issue by dondos** [Project-OSRM/osrm-backend#1421]
http://osrm.at/bt5
![ruta](https://cloud.githubusercontent.com/assets/9431355/6769396/1cdc16ce-d0a2-11e4-945b-6590e3636350.png)

The route is wrong because left turning from "Calea Turzii" is prohibited:
http://www.openstreetmap.org/relation/4680475

**Comment by TheMarex** [comment]
@DennisOSRM are data updates broken? Turn restriction is two days old and seems to be tagged correctly.

**Comment by DennisOSRM** [comment]
Yes, updates were stalled. `/tmp` overflowed after upgrading some software packages. That caused the data updates to not consume any new data. I have reset everything s.t. it should catch up soon.

**Comment by DennisOSRM** [comment]
All issues have been fixed. It will take half a day or so until data updates will show up on the demo site. Will close here once that happened.

**Comment by dondos** [comment]
I can confirm that the mentioned issue was fixed. But the calculated route is still wrong. 
An only right turn restriction when exiting the filling station ("Mol Calea Turzii") is ignored: https://www.openstreetmap.org/relation/4719460
The route sould go up to the roundabout between "Calea Turzii" and "Buna Ziua".

**Comment by DennisOSRM** [comment]
Well, it enters the filling station at the southern entrance (exit?) and leaves at the northern one where there is not turn restriction. So, it does not ignore the restriction but takes a path that is okay according to the data. 

Looking at satellite imagery, I am unsure if the service way through the gas station should be a oneway or if there should be a another TR at the northern entrance/exit. Either would kind of fix the issue at hand.

**Comment by dondos** [comment]
Oops... silly me, I didn't look at the routing instructions. 
You are right, that service way should be one-way only. I'll fix that. Thank you:)

**Comment by DennisOSRM** [comment]
Ok, closing here.
