### ISSUE TITLE
One-way error

### ISSUE THREAD

**Issue by iagsav** [Project-OSRM/osrm-backend#1423]
The route is wrong, because it it one-way stret
![image](https://cloud.githubusercontent.com/assets/5525867/6822040/b6d0223c-d2ed-11e4-8cf6-f7695d80e36c.png)

Using MapQuest
![image](https://cloud.githubusercontent.com/assets/5525867/6822028/91a79c9c-d2ed-11e4-9313-9684deef1c8f.png)

**Comment by DennisOSRM** [comment]
Data updates have been lagging behind for a few days. Will be fixed with the next one.
