### ISSUE TITLE
osrm-prepare fails on ubuntu

### ISSUE THREAD

**Issue by normanb** [Project-OSRM/osrm-backend#1425]
running ubuntu 14.04 x64 osrm-prepare fails with 

[warn] Exception occured: std::bad_alloc

The following files are created;

north-america-latest.osrm.restrictions
north-america-latest.osrm.timestamp
north-america-latest.osrm
north-america-latest.osrm.names

**Comment by woodbri** [comment]
Check that your have swap space and space the stxxl files maybe in /tmp

**Comment by normanb** [comment]
I have a .stxxl file set as

disk=/tmp/stxxl,40000,syscall

and plenty of disk space

/dev/vda1       473G   62G  387G  14% /

and swap space

free -m
             total       used       free     shared    buffers     cached
Mem:         48303      18668      29635          0        225      17482
-/+ buffers/cache:        959      47343
Swap:         4095          0       4095

Same error.

**Comment by TheMarex** [comment]
Could you please post the full output of osrm-extract as [gist](http://gist.github.com)?
What is the size of the dataset you want to process? How much main memory is available?

**Comment by DennisOSRM** [comment]
OTOH, the machine runs out of error.

**Comment by normanb** [comment]
I don't think the machine is running out of memory and I have disabled the OOM Killer.

`free -m`

             total       used       free     shared    buffers     cached

Mem:         48303      18703      29600          0        237      17507

-/+ buffers/cache:        958      47345

Swap:         4095          0       4095

osrm-prepare gist is here https://gist.github.com/normanb/164a00836f68f41c2e7c

and

7.0G Mar 29 21:52 north-america-latest.osrm

**Comment by TheMarex** [comment]
@normanb Did you use lua 5.2.0? We recently found that this version leaks memory. 48GB main memory could be sufficient for north-america using the car profile, but for example the whole planet requires around around 80GB.

**Comment by daniel-j-h** [comment]
Please try again with latest develop and report back if you are still seeing issues.
