### ISSUE TITLE
Issue with nearest-neighbor search, i.e. SCC traversal of the road network

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#1427]
Currently blocking the release of 4.6.0:

During preprocessing, the road network is explored to identify _all_ strongly connected components. There appears to be an issue that does not properly identify all segments/SCCs correctly. Here's an example. The entire one-way should be discovered as a string of SCCs:

![screenshot 2015-04-01 17 18 26](https://cloud.githubusercontent.com/assets/1067895/6944334/98234ee4-d893-11e4-831b-95ae2a45b3dd.png)

The code didn't change drastically over time. So, the issue is most probably something minor such as an off-by-one or similar error.

**Comment by DennisOSRM** [comment]
I have some more intel on this issue, which is a pesky one.

It looks like SCCs are properly detected on an algorithmic level, but that there's something odd with how the ID of the SCC is computed/interpreted. Note that ID 0 has special meaning, i.e. _small component. Things to check:

- [ ] min() call
- [ ] serialization of IDs
- [ ] initialization of ID array

**Comment by TheMarex** [comment]
Do you have a test-case somewhere to reproduce this?

**Comment by TheMarex** [comment]
@DennisOSRM Since this is blocking, I'm going to jump on this myself if you are okay with that.

**Comment by TheMarex** [comment]
Okay could reproduce this by comparing a shapefile from ```osrm-components``` from ```develop``` and ```v4.5.0```:

https://api.tiles.mapbox.com/v4/themarex.1a592be3/page.html?access_token=pk.eyJ1IjoidGhlbWFyZXgiLCJhIjoiSXE4SDlndyJ9.ihcqCB31K7RtzmMDhPzW2g#17/52.50228/13.37518

**Comment by TheMarex** [comment]
The issue was introduced by fbce104f3b2d5385e0bfc04cfa29f1f7dbc2cb3c.

**Comment by DennisOSRM** [comment]
@TheMarex 

> Since this is blocking, I'm going to jump on this myself if you are okay with that.

Go for it.

**Comment by DennisOSRM** [comment]
@TheMarex 

> The issue was introduced by fbce104. Reverting this commit fixes the issue above. So there is probably a bug in StaticGraph.

Good finding. How about we check for differences of the graph implementations until Friday 5pm and if we don't have a fix just do a revert?

**Comment by DennisOSRM** [comment]
Added a tool to compare graph implementations: `tools/graph_compare.cpp` in branch feature/check_graph_implementations. No obvious differences on a functional level so far.

**Comment by TheMarex** [comment]
Might be an issue with a constructor from StaticGraph from a vector of edges. Its only used in the components tool and unit tests, might have broken some time ago. Currently refactoring that.

**Comment by DennisOSRM** [comment]
> The issue was introduced by fbce104. Reverting this commit fixes the issue above. So there is probably a bug in StaticGraph.

I just double-checked by replacing the static with the dynamic graph. The issue persists. Thus, the error was perhaps introduced with a different commit?

**Comment by DennisOSRM** [comment]
Got a lead. It looks like there's a difference between the FindEdge implementations. More details to follow.

**Comment by DennisOSRM** [comment]
Got it. Fix will be available later today. The difference was (as mentioned above) the implementation of the `FindEdge()` method. If an edge was not found, the dynamic graph implementation returned `EndEdges(node)` whereas the static implementation returned `SPECIAL_NODEID`. 

Here's the use case from `component.cpp`:

```C++
if (source < target || graph->EndEdges(target) == graph->FindEdge(target, source))
{
    // count edge length

    // serialize edge into shape file if either endpoint belongs to a small component.
}      
```

What does that do? It checks if source is smaller than target node to not serialize any edge twice. And in case it's a one-way street it's not supposed to find the reverse edge. The latter check failed as it returned a different value and this lead to the case that some edges where correctly identified as belonging to a small component but not serialized.

Fix upcoming.

**Comment by DennisOSRM** [comment]
@TheMarex pull request filed with #1440. Merge if you feel good about this.

**Comment by TheMarex** [comment]
@DennisOSRM wow, awesome! I will add some unit tests for StaticGraph/DynamicGraph to check that behavior.
