### ISSUE TITLE
Ambiguous --max-table-size command response

### ISSUE THREAD

**Issue by agoddijn** [Project-OSRM/osrm-backend#1428]
I tried running the `./osrm-routed --max-table-size 1000` command and got this as a response 

![screen shot 2015-04-02 at 15 10 21](https://cloud.githubusercontent.com/assets/9005741/6974782/6e01284a-d94a-11e4-9c8e-7da77ef58416.png)

Not sure if this means it has worked or not. We tried various different way of writing the command, which all responded with an error message. When we ran this, the server seemed to truncate responses past 100 visits (without throwing and error)

**Comment by woodbri** [comment]
the command should ``./osrm-routed /path/to/yourfile.osrm --max-table-size=1000``

**Comment by agoddijn** [comment]
@woodbri Silly error, thanks for your help :)
