### ISSUE TITLE
How to get node location in profile script

### ISSUE THREAD

**Issue by vesse** [Project-OSRM/osrm-backend#1432]
I need to check external resource in `node_function` and would need the coordinates and ID of a node to perform the check. Is the location of a node somehow accessible in the Lua script? Are the members and methods of the `way` and `node` objects documented somewhere?

Thanks!

**Comment by TheMarex** [comment]
Thanks for reporting this.Just added a PR to fix this. In general we don't have good documentation on this. You can find most information here https://github.com/Project-OSRM/osrm-backend/blob/develop/extractor/scripting_environment.cpp#L79

Maybe you want to help improving the documentation by adding that to the wiki?

**Comment by vesse** [comment]
Thanks! Maybe add also `.def("id", &osmium::Node::id)` while the PR is still open?

I'll see if I could help with the documentation once I have more experience with OSRM.

**Comment by DennisOSRM** [comment]
Closing here, tracking progress in #1433
