### ISSUE TITLE
Documentation hit list

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1434]
Some parts of the code really need a _lot_ better documentation.
- [x] Extractor:
  - [x] What files are created and who consumes them
  - [x] ExtractorCallbacks
  - [x] ScriptingEnvironment
  - [x] ExtractorContainers
  - [x] Extractor
  - [x] RestricionParser
- [x] Prepare
  - [x] What files are created and who consumes them
  - [x] Contractor: Especially add context + theoretical background
  - [ ]
- [ ] Routing Algorithms:
  - ....
- [ ] Server:
  - ....

Server API:
The documentation in the wiki is not really complete and needs a more consistent format.

Scripting API:
No(?) documentation expect the example profiles

**Comment by TheMarex** [comment]
Tracking in [this branch](https://github.com/Project-OSRM/osrm-backend/tree/doc/extractor).

**Comment by daniel-j-h** [comment]
Referenced branch is gone --- please update.

In general: is the Wiki the right place to accumulate documentation? Especially something like the man pages look like they would make more sense in the repository.

There is an easy way to generate beautiful man pages from markdown files using `pandoc`, that we could then provide and even install locally for the user.

**Comment by TheMarex** [comment]
We should primarily write docs for the public library API and do a cleanup for the internal docs.

**Comment by TheMarex** [comment]
@daniel-j-h tackled the internal API interface design. Maybe we should use https://github.com/jessevdk/cldoc the output looks much cleaner and we could publish this over travis.

I think we need to have some discussion about where the API documentation should live.

Current state:
- Public API documentation lives in the `osrm-backend` wiki (except C++ library interface)
- C++ library interface is documented over doxygen, but not published anywhere

Problems:
- Entries in wiki are not versioned with code. If someone changes the API the following things should be included and visible in the PR:
   - Changelog update
   - Documentation update
- Wiki is kind of hard to find, we link it in the README though
- C++ library documentation is not exposed
- `node-osrm` documentation is in the wrong repository

Proposal:
- Move to `osrm-backend` repository (and link from the wiki):
   - New HTTP API documentation
   - C++ Library documentation
- Keep old API documentation in wiki, with version tag and deprecated tag
- Move `node-osrm` documentation to repository (and link from the wiki)
- Display on `project-osrm.org`:
  - Documentation for latest release (e.g. `5.0.0`), HTTP, C++, node-osrm
  - Documentation for master, HTTP, C++, node-osrm

Mechanism:
- Doxygen or https://github.com/jessevdk/cldoc
- Update `project-osrm.org` repo over triggered builds (-> pulls `osrm-backend`, extracts docs -> publishes)

Estimated time to implement: Two days (weekend project).

Does anyone here have a strong opinion? @danpat @daniel-j-h @MoKob @freenerd ?

**Comment by MoKob** [comment]
For Guidance, we should hit a list of all instructions in combination with an example image and a proposed translation to give an impression of what we want to express when emitting the respective instruction.

**Comment by freenerd** [comment]
I'm very opinionated for documentation to live next to code. I have no experience with https://github.com/jessevdk/cldoc but it looks like it might work well. A year ago we had a try with [Documentation.js](https://github.com/documentationjs/documentation) on node-osrm ([PR](https://github.com/Project-OSRM/node-osrm/pull/102/)) and could also give that a try again, since it matured quite a bit since then.

Plan outlined looks good. Not sure how publishing and versioning would work, but let's find out on the way.

**Comment by TheMarex** [comment]
- [x] Move to `osrm-backend` repository (and link from the wiki):
   - [x] New HTTP API documentation
   - [ ] C++ Library documentation
- [x] Keep old API documentation in wiki, with version tag and deprecated tag
- [ ] Move `node-osrm` documentation to repository (and link from the wiki)
- [ ] Display on `project-osrm.org`:
  - [ ] Documentation for latest release (e.g. `5.0.0`), HTTP, C++, node-osrm
  - [ ] Documentation for master, HTTP, C++, node-osrm

**Comment by TheMarex** [comment]
@danpat finally implemented this http://project-osrm.org/docs/v5.5.2/api/#general-options 🎉
