### ISSUE TITLE
Better guidance

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#1436]
Here's a page from a Automobile club of America Tour book from 1910. It includes surprisingly well and concisely described long distance tours using a certain graphical notation system. The following looks like a frontend issue at first, but the generation of such things has to be done on the backend:

The legend:

![nypl digitalcollections ed8abf80-7238-0131-b7ea-58d385a7bbd0 007 q](https://cloud.githubusercontent.com/assets/1067895/7112180/6281e38a-e1c7-11e4-9a64-d6f4ffab0153.jpg)

Example tours:

![nypl digitalcollections ed8abf80-7238-0131-b7ea-58d385a7bbd0 056 q](https://cloud.githubusercontent.com/assets/1067895/7112191/85912868-e1c7-11e4-922f-08028c29e128.jpg)

**Comment by emiltin** [comment]
sweet :-)

**Comment by MoKob** [comment]
Nothing actionable. Closing here.
