### ISSUE TITLE
Is it possible to limit the osrm-routed memory footprint? 

### ISSUE THREAD

**Issue by frankvandenbergh** [Project-OSRM/osrm-backend#1438]
Thanks for this marvellous project. I want to create a trip simulation application and the distance matrix function is very useful and very very fast as well.

Is it possible to limit the osrm-routed memory footprint? 

I'm using a Windows machine, with europe-latest osrm-routed consumes 10 Gb (and some time to start up). For now I use Osmosis to crop the europe-latest. For this application I don't need names and gis info. It would be nice to have a configuration option to not load certain items. I don't know if something is possible at all. It is not an urgent matter.

**Comment by emiltin** [comment]
osrm can use swap space but it will be sloooow

**Comment by TheMarex** [comment]
Yeah, but there are probably better ways to reduce the memory footprint. You could sacrifice performance by replacing our graph representation with an extern memory variant. There is a wealth of research on that topic, but we don't plan to go down that route
.
If you want to give it a stab yourself, I'm happy to help in every way I can.

**Comment by mhyousefi** [comment]
I am also wondering if one can limit the amount of data loaded to the memory especially as @frankvandenbergh mentioned, in some cases some GIS info might not be used at all. I'm commenting as it is about 4 years since this issue was opened and wonder if things have changed.

**Comment by danpat** [comment]
Yes - `osrm-routed` now has an option called `--mmap on` - this will cause it to use virtually no memory, and read from files on disk on-demand.

Query times are quite a bit slower, but it works just fine, and can be run with a very small memory footprint (you still need enough RAM to be able to actually hold the working data during route calculation, but that is usually quite small, like 10s to 100s of MB per query, depending on the size).

**Comment by GabeMillikan** [comment]
For anyone coming from google, it's now just `--mmap` as a flag with no argument. For example

```
osrm-routed /data/data.osrm --algorithm MLD --mmap
```

And just PSA, it has almost no affect on routing times on my machine with a nice SSD.
