### ISSUE TITLE
Question about floating point / fixed point

### ISSUE THREAD

**Issue by fpacheco** [Project-OSRM/osrm-backend#1441]
I am reading data directly from the .nodes file. 

The results I get are something like:
1. 3317315637|-56196399|-34856851
  [for \<node id="3317315637" lat="-34.8568514" lon="-56.1963999"/> in my OSRM file]
2. 3330766918|-56391757|-34768008
  [for \<node id="3330766918" lat="-34.7680082" lon="-56.3917576"/> in my OSRM file]
3. 3317315629|-56070755|-34792688
 [for \<node id="3317315629" lat="-34.7926886" lon="-56.0707550"> in my OSRM file]

My questions are:
1. -56196399 should not be -56196400 ( round(-56.1963999 * 1000000) )?
2. -56391757 should not be -56391758?
3. -34792688 should not be -34792689?

Many thanks. Fernando.

**Comment by TheMarex** [comment]
Probably a problem with floating point precision. I don't think we can fix this.

If you rely on comparing floating point numbers, do so with an adequate epsilon comparison:
```if(std::abs(a - b) < epsilon) { do stuff }``` using for example ```epsilon = 0.000001```.
