### ISSUE TITLE
Make distance_table consistent regarding different phantom nodes

### ISSUE THREAD

**Issue by chaupow** [Project-OSRM/osrm-backend#1447]
Currently the distance table is getting a list of locations that might have more than one phantom node per input coordinate.
Distance table should be changes such that

1) when computing the distance table, for every location the same phantom node is used 
2) when returning output, there should not only be the information about the distances but also which phantom node was used in the process

**Comment by TheMarex** [comment]
More background here:

The main problem is [this part of the code](https://github.com/Project-OSRM/osrm-backend/blob/develop/routing_algorithms/many_to_many.hpp#L90-L104). The for _every location_ the `phantom_node_vector` that is returned by `StaticRTree` is inserted.  This vector usually contains up to 2 phantom nodes, one from a big and one from a small component.

Example: We have two locations `loc1`: `{a, b}` and `loc2`: `{c, d}`. The result of the query should be a table of size `2x2`. First step is to initialize the backward heap and run the backward search for each location. For `loc1` that would mean we insert `a` _and_ `b` in the heap and run the backward search. All nodes that are found by the backward search are marked with the distance to `a` _or_ `b`, depending on which one is shorter. But we don't save from which node the distance actually is.

- Retain the information for each node. When we do the backward search we retain information about the "original parent" in the heap data. This would mean modifying [this line](https://github.com/Project-OSRM/osrm-backend/blob/develop/routing_algorithms/many_to_many.hpp#L224) and [this line](https://github.com/Project-OSRM/osrm-backend/blob/develop/routing_algorithms/many_to_many.hpp#L230) to set the `parent` not to `node` but to parent of `node`. For all nodes found in the backward search in the example above that would yield nodes either marked `a` or `b`.

- Decide on exactly one phantom node. This would need similar logic as in [viaroute](https://github.com/Project-OSRM/osrm-backend/blob/develop/plugins/viaroute.hpp#L152-L160). Running this on the list of coordinates would discard all the small components if they are not from the same small component.

**Comment by danpat** [comment]
So, to clarify the behaviour we're going for here:

  - If all nodes snap to a big component, we simply route those
  - If some components snap to small components *and* have nearby big components, and everything snaps to a big component, snap to to the big components (i.e. city parks < 1100m from a big components).
  - If all components snap to the same small component, use that.
  - If some components snap *only* to a small component, use that (i.e. islands more than 1100m from a big component).

**Comment by TheMarex** [comment]
This was implemented to be consistent with `viaroute`. It uses the same snapping behavior.
