### ISSUE TITLE
output of osrm-extract. Is it working?

### ISSUE THREAD

**Issue by drewlesueur** [Project-OSRM/osrm-backend#1449]
Similar to issue #1411 
My osrm-extract has been running for about 8 hours. It could be working but I don't know if it is or not.
Is there anything I could look for to see if it's working?

    [info] Input file: all.osm
    [info] Profile: profile.lua
    [info] Threads: 16
    [info] Using script profile.lua
    [STXXL-MSG] STXXL v1.3.1 (release)
    [STXXL-MSG] 1 disks are allocated, total space: 200000 MiB

Thank you!

and by the way, I really like this project.

**Comment by drewlesueur** [comment]
I put some more logs in extractor/extractor.cpp, and I see that it's getting stuck at this step:

`const osmium::io::Header header = reader.header();`

It was stuck for 8 hours there it seems.
I used `osmconvert` to convert pbfs to oms, and then combine the oms. Maybe it generated bad data?

but my combined osm file starts like this:

    <?xml version='1.0' encoding='UTF-8'?>
    <osm version="0.6" generator="osmconvert 0.8.4" timestamp="2015-04-21T20:21:02Z">
            <bounds minlat="-45.95665" minlon="-179.9999" maxlat="85.04177" maxlon="156.0377"/>
            <node id="77875" lat="28.5997871" lon="-80.6180003" version="2" timestamp="2009-07-08T20:52:45Z" changeset="1776041" uid="131476" user="DMaximus"/>

**Comment by TheMarex** [comment]
How big is the file you want to parse? How much main memory has your machine? In general you should _not_ use large XML based files. Use ```.osm.pbf``` instead.

**Comment by drewlesueur** [comment]
Ok, thank you! I was trying to parse the a 154G .osm file.
I am going to switch to osm.pbf instead.
