### ISSUE TITLE
Start testing on OS X per-commit with Travis

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/osrm-backend#1453]
I've requested [multi-os support](http://docs.travis-ci.com/user/multi-os/) for our Travis builds and just got word that it was enabled.

I volunteer to help port the .travis.yml file to work in a cross platform way: best practice is to move most logic to standalone scripts per operating system and out of the .travis.yml.

**Comment by daniel-j-h** [comment]
Building on OSX with different XCode setups for a long time now, closing here.
