### ISSUE TITLE
Testing setup

### ISSUE THREAD

**Issue by lbud** [Project-OSRM/osrm-backend#1454]
@emiltin — 

I'm eager to get tests up and running/100% passing in order to work on contributing and have been hitting some walls. Yesterday @springmeyer and I worked on bootstrapping the initial setup on the [`masonize`](https://github.com/Project-OSRM/osrm-backend/compare/masonize) branch, which led us down quite a few Lua/Luabind/LuaJIT wormholes that seemed *maybe* OS-specific (we are both running OSX). Now I'm running Lua 5.1.0 with Luabind and without LuaJIT; Lua 5.3.0 led to Lua compile errors failing all cucumber tests. After figuring out which versions of Lua/Luabind to use my `cucumber` results (sans nice colors) are [here](https://gist.github.com/lbud/814f98e35c144dd9a2ab) — you can see at the bottom I've got
```
369 scenarios (33 failed, 336 passed)
1539 steps (33 failed, 1506 passed)
```
I'm trying to figure out the following:
* Why would my results be differing/not 100% passing? (for example: )
![image](https://cloud.githubusercontent.com/assets/3170312/7403191/4688527c-eea1-11e4-9650-c26567ec3887.png)
![image](https://cloud.githubusercontent.com/assets/3170312/7403198/51ea8662-eea1-11e4-93a3-9b9179136f9e.png)
* Could this be related to Lua or cucumber versions? (I also had a hard time getting cucumber to run on Ruby 2.+ and had to downgrade to 1.9.3 to run it)
* Could this be OS-specific?

Curious to see if you have any hunches here. Thanks!!
cc @TheMarex

**Comment by emiltin** [comment]
it looks to me like wrong routes are in fact returned, rather than a problem with ruby or the test framework.

could there be different version of osrm running?
could there be different/wrong datasets loaded through osrm-datastore?

latest develop branch works for me on both ubuntu 14 and os x. 10.9, with all tests passing. i'm using lua 5.2 on both.

**Comment by emiltin** [comment]
one major difference seems to be that i'm running lua 5.2 while you're using 5.1.

**Comment by springmeyer** [comment]
@emiltin thanks for the feedback and ideas! We'll try using Lua 5.2 as a next step. The reason we chose 5.1 was that I we realized that luajit would be a good thing to try eventually and luajit says it is compatible with lua 5.1.

@emiltin - as far as your general OS X setup: what version of ruby do you use, and how do you install it and other osrm-backend deps? Do you mainly use homebrew or source installs?

**Comment by emiltin** [comment]
i heard that lua and luajit are starting to become somewhat incompatible, ie. luajit not merging recent changes to lua, but don't know much about luajit.

i'm installing as much as possible through brew. ruby is installed via rbenv. i generally try to use the latest, currently 2.2.0.

**Comment by lbud** [comment]
@emiltin I tried to run lua 5.2, and was getting lua compile errors like
![image](https://cloud.githubusercontent.com/assets/3170312/7419915/3bb84014-ef46-11e4-8906-392fa3cb9954.png)
(same as I was seeing the other day with 5.3).

Upon looking into @springmeyer and I came across the fact that [this method is deprecated](http://hisham.hm/2014/01/02/how-to-write-lua-modules-in-a-post-module-world/) in Lua 5.2+, which is why [only the car tests were passing for me locally](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L2).

I inlined the access and maxspeed functions into bicycle.lua and foot.lua and now cucumber tests are 100% passing for me locally. I'm a bit baffled as to 
* why test results would differ from 5.1 to 5.2 (not that that's necessarily an OSRM problem, it seems like a major Lua weirdness)
* how travis is passing 100% on 5.1
* how 5.2 could be working with global requires

Any thoughts?

**Comment by emiltin** [comment]
The page you linked to states that with Lua 5.2 module() is only available with compatibility flags on. So it seems I must have that flag on, and you don't. how did you install lua 5.2?

The brew recipe for lua 5.2 inclues the compile flags LUA_COMPAT_ALL.

So the bicycle profile uses module, but car doesn't. So bicycle works on 5.1 since module() is defined. On 5.2 it only works if you have compatibility flags on.

**Comment by daniel-j-h** [comment]
Fixed in pull request https://github.com/Project-OSRM/osrm-backend/issues/1457.
