### ISSUE TITLE
compressed polyline multiplied not by 1e5 but 1e6 (?)

### ISSUE THREAD

**Issue by kkdd** [Project-OSRM/osrm-backend#1458]
Longitude and latitude seem to be multiplied not by 1e5 but 1e6 in the compressed (encoded) route geometries of OSRM's responses. They aren't correctly decoded by using google.maps.geometry.encoding.decodePath().

An example of the response is: {"matchings":[{"matched_points":[[35.576797,139.629349],[35.577625,139.630478],[35.577911,139.633392],[35.578751,139.635498],[35.579277,139.636826]],"indices":[0,1,2,3,4],"geometry":"y|lzbA{phiiGeYrLkDiQeLwj@u@qEeDyNoKyf@oE_XrT{HjEmkBuA@wOPuFR{Vv@sNmgA_Hai@yB_ScAcKqDcWoJyq@uL|B"}]}.

**Comment by emiltin** [comment]
osrm uses 6 decimals on purpose, to enhance precision

**Comment by TheMarex** [comment]
You can use this instead https://www.npmjs.com/package/polyline with a precision of 6 as @emiltin suggested.

**Comment by kkdd** [comment]
Thank you for your reply.
I have enhanced my program to allow a precision of 6 and it works. I would like the description of precision in the document if it doesn't exist.

**Comment by emiltin** [comment]
it's described int the wiki.
