### ISSUE TITLE
Error 2 when make

### ISSUE THREAD

**Issue by avesgit** [Project-OSRM/osrm-backend#1459]
Hi, i'm trying to setup Project-OSRM on Debian 7 in virtual machine with 6Gb RAM
oll ok, but when i do make command i see that:

[ 61%] Building CXX object CMakeFiles/osrm-extract.dir/extract.cpp.o
[ 64%] Building CXX object CMakeFiles/osrm-extract.dir/extractor/extraction_containers.cpp.o
[ 66%] Building CXX object CMakeFiles/osrm-extract.dir/extractor/extractor.cpp.o
In file included from /usr/include/osmpbf/osmpbf.h:5:0,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/detail/pbf.hpp:38,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/detail/pbf_input_format.hpp:53,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/pbf_input.hpp:47,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_input.hpp:48,
                 from /home/aves/distr/osrm-backend/extractor/extractor.cpp:49:
/usr/include/osmpbf/fileformat.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/usr/include/osmpbf/fileformat.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/usr/include/osmpbf/fileformat.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /usr/include/osmpbf/osmpbf.h:8:0,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/detail/pbf.hpp:38,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/detail/pbf_input_format.hpp:53,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/pbf_input.hpp:47,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_input.hpp:48,
                 from /home/aves/distr/osrm-backend/extractor/extractor.cpp:49:
/usr/include/osmpbf/osmformat.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/usr/include/osmpbf/osmformat.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/usr/include/osmpbf/osmformat.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/bzip2_compression.hpp:57:0,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_compression.hpp:45,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_input.hpp:46,
                 from /home/aves/distr/osrm-backend/extractor/extractor.cpp:49:
/home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/compression.hpp:269:24: warning: ‘osmium::io::{anonymous}::registered_no_compression’ defined but not used [-Wunused-variable]
             const bool registered_no_compression = osmium::io::CompressionFactory::instance().register_compression(osmium::io::file_compression::none,
                        ^
In file included from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_compression.hpp:45:0,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_input.hpp:46,
                 from /home/aves/distr/osrm-backend/extractor/extractor.cpp:49:
/home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/bzip2_compression.hpp:277:24: warning: ‘osmium::io::{anonymous}::registered_bzip2_compression’ defined but not used [-Wunused-variable]
             const bool registered_bzip2_compression = osmium::io::CompressionFactory::instance().register_compression(osmium::io::file_compression::bzip2,
                        ^
In file included from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_compression.hpp:46:0,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_input.hpp:46,
                 from /home/aves/distr/osrm-backend/extractor/extractor.cpp:49:
/home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/gzip_compression.hpp:234:24: warning: ‘osmium::io::{anonymous}::registered_gzip_compression’ defined but not used [-Wunused-variable]
             const bool registered_gzip_compression = osmium::io::CompressionFactory::instance().register_compression(osmium::io::file_compression::gzip,
                        ^
In file included from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/pbf_input.hpp:47:0,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_input.hpp:48,
                 from /home/aves/distr/osrm-backend/extractor/extractor.cpp:49:
/home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/detail/pbf_input_format.hpp:249:28: warning: ‘osmium::io::detail::{anonymous}::registered_pbf_input’ defined but not used [-Wunused-variable]
                 const bool registered_pbf_input = osmium::io::detail::InputFormatFactory::instance().register_input_format(osmium::io::file_format::pbf,
                            ^
In file included from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/xml_input.hpp:46:0,
                 from /home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/any_input.hpp:49,
                 from /home/aves/distr/osrm-backend/extractor/extractor.cpp:49:
/home/aves/distr/osrm-backend/third_party/libosmium/include/osmium/io/detail/xml_input_format.hpp:725:28: warning: ‘osmium::io::detail::{anonymous}::registered_xml_input’ defined but not used [-Wunused-variable]
                 const bool registered_xml_input = osmium::io::detail::InputFormatFactory::instance().register_input_format(osmium::io::file_format::xml,
                            ^

CMakeFiles/osrm-extract.dir/build.make:100: recipe for target 'CMakeFiles/osrm-extract.dir/extractor/extractor.cpp.o' failed
make[2]: *** [CMakeFiles/osrm-extract.dir/extractor/extractor.cpp.o] Error 1
CMakeFiles/Makefile2:635: recipe for target 'CMakeFiles/osrm-extract.dir/all' failed
make[1]: *** [CMakeFiles/osrm-extract.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TheMarex** [comment]
Which gcc version are you using? We require 4.8.

**Comment by avesgit** [comment]
all good with gcc
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by springmeyer** [comment]
> /usr/include/osmpbf/fileformat.pb.h:17:2: error: #error This file was generated by an older version of protoc which is

^^ I think that is the key error. To fix this you should install osmpbf from source so that the file is re-generated based on the protobuf version you have installed.

**Comment by avesgit** [comment]
thanks its solve this problem but after this next problem
>(google::protobuf::internal::RepeatedPtrFieldBase const&)':
(.text._ZN6google8protobuf8internal20RepeatedPtrFieldBase9MergeFromINS0_16RepeatedPtrFieldISsE11TypeHandlerEEEvRKS2_[_ZN6google8protobuf8internal20RepeatedPtrFieldBase9MergeFromINS0_16RepeatedPtrFieldISsE11TypeHandlerEEEvRKS2_]+0x6a): undefined reference to `google::protobuf::internal::StringTypeHandlerBase::New()'
collect2: error: ld returned 1 exit status
CMakeFiles/osrm-extract.dir/build.make:272: recipe for target 'osrm-extract' failed
make[2]: *** [osrm-extract] Error 1
CMakeFiles/Makefile2:635: recipe for target 'CMakeFiles/osrm-extract.dir/all' failed
make[1]: *** [CMakeFiles/osrm-extract.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by springmeyer** [comment]
@avesgit looks like you may have duplicate libprotobuf versions on your system.

**Comment by avesgit** [comment]
thanks i find problem i delete all from build folder and cmake.. and make again and all compile thanks
