### ISSUE TITLE
Building osrm-backend on a Hackintosh with OS X 10.10.3

### ISSUE THREAD

**Issue by wendibus** [Project-OSRM/osrm-backend#1461]
HI,

run a Hackintosh with OS X 10.10.3 (i7, 32 GByte, 250 GB SSD and two harddrives (4 and 2 TB).

I have tried to install OSRM there. I have opened the terminal and entered:

git clone https://github.com/Project-OSRM/osrm-backend.git

then I have entered:

mkdir -p build; cd build; cmake ..; make

errormessage: cmake not found

Next Step:
npm install cmake

it failed

**Comment by emiltin** [comment]
you need to install the cname build system, as well as other dependencies. see the wiki: https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM#mac-os-x-1071-1082.

**Comment by wendibus** [comment]
thanks I have not seed that one :-(

I used google to see if anyone had success with Mac OS X and somehow I missed the wiki on Mac OS X.
