### ISSUE TITLE
Problem Drive time 

### ISSUE THREAD

**Issue by zanda85** [Project-OSRM/osrm-backend#1462]
Hi, I have problems with the configuration car.lua .

my car profile ....

speed_profile = {
  ["motorway"] = 90,
  ["motorway_link"] = 45,
  ["trunk"] = 85,
  ["trunk_link"] = 40,
  ["primary"] = 65,
  ["primary_link"] = 30,
  ["secondary"] = 55,
  ["secondary_link"] = 20,
  ["tertiary"] = 20,
  ["tertiary_link"] = 20,
  ["unclassified"] = 5,
  ["residential"] = 5,
  ["living_street"] = 10,
  ["service"] = 15,
--  ["track"] = 5,
  ["ferry"] = 5,
  ["movable"] = 5,
  ["shuttle_train"] = 10,
  ["default"] = 10
}

in the file osm  Via Tristani!!

<way id="154193746">
    <nd ref="1667696791"/>
    <nd ref="1667696781"/>
    <nd ref="1667696772"/>
    <nd ref="1333682850"/>
    <nd ref="1667632419"/>
    <nd ref="302742161"/>
    <nd ref="302742163"/>
    <tag k="access" v="permissive"/>
    <tag k="access:conditional" v="no @ (21:00-07:00,15:30-17:00)"/>
    <tag k="bicycle" v="yes"/>
    <tag k="cycleway" v="no"/>
    <tag k="foot" v="yes"/>
    <tag k="highway" v="residential"/>
    <tag k="horse" v="yes"/>
    <tag k="lanes" v="1"/>
    <tag k="lit" v="yes"/>
    <tag k="maxspeed" v="50"/>
    <tag k="name" v="Via Tristani"/>
    <tag k="oneway" v="-1"/>
    <tag k="surface" v="asphalt"/>       
  </way>

This road should be traveled at 5 km/h  -> min(5,50,nil)-> 5!!!!    (nil=asphalt);

but the time is 

["2","Via Tristani",72,3,7,"72m","SE",119,1]     -> 37km/h     why?????????????

I tried everything . help me please!!!!!!!!

**Comment by emiltin** [comment]
I think you need to provide more info about your problem, like a link to the specific way at osm.org.

**Comment by zanda85** [comment]
thanks for your help!!
I'm sorry for my english!!.

I want to change the file car.lua
the driving time is very low.
I want to reduce the driving speed in some streets .
I use speed_reduction = 0.8
but this is not enough .

I want to reduce the speed in the streets with the tag "residential" .

speed_profile = {
  ...
  [ " residential " ] = 5 ,


in the streets of residential tags should go to 5 * 0.8 + 11 .

but this is not working .

a link of example :

http://www.openstreetmap.org/directions?engine=osrm_car&route=39.2232%2C9.1183%3B39.2318%2C9.1292


in my local server

http://localhost:5000/viaroute?loc=39.224174,9.118619&loc=39.231354,9.130036&instructions=true


{"status":0,"route_instructions":[["10","Via San Saturnino",18,0,10,"17m","NE",35,1],["2","",10,1,1,"10m","E",81,1],["1","",16,2,1,"15m","E",81,1],["2","Via Tristani",72,3,7,"72m","SE",119,1],["3","Via Giardini",6,6,1,"6m","S",178,1],["7","Vico 11 San Giovanni",22,7,2,"22m","E",91,1],["7","Via San Giovanni",93,8,10,"93m","N",8,1],["2","Vico 12 San Giovanni",132,12,10,"132m","NE",46,1],["1","",211,21,16,"210m","NE",59,1],["8","Via Giudice Torbeno",174,26,14,"173m","N",2,1],["1","",49,29,4,"48m","NE",49,1],["6","Via dei Giudicati",29,32,2,"29m","NW",309,1],["3","Via dei Visconti",29,35,2,"29m","N",0,1],["2","Via Giudicessa Benedetta",206,36,16,"205m","NE",59,1],["3","Via dei Donoratico",11,40,1,"11m","SE",113,1],["8","Via Nastro Azzurro",144,41,11,"144m","E",100,1],["11-2","Via Gabriello Chiabrera",290,48,23,"289m","N",20,1],["3","Via Gaspare Stampa",151,54,12,"151m","SE",119,1],["15","",0,56,0,"0m","N",0]],"route_name":["Via Giudicessa Benedetta","Via Gabriello Chiabrera"],"status_message":"Found route between points","via_indices":[0,57],"route_geometry":"{u`yiAuxpkPgGmFc@kFs@cJlCsHhKoG]{UxBCJ}NkJ}@mJFwTl@cGb@mH{KiDyCgFqBoBu@yDg@sNy@yJg@}BwCeA{B_B}Ey\\udAq@uBoRgl@mBaG}Ym@oBGabAiBsGaBkAeEy@oNaAzAAfLAdCcOA{g@yuAqEc`@cCcDmBgCrAiFVmDfAsrADgHwAsCkAcDoDu@kCbC}DyAuMwLcXeXs_@y^ga@}ZaUgN|Oof@xZyt@","route_summary":{"end_point":"Via Gaspare Stampa","start_point":"Via San Saturnino","total_time":136,"total_distance":1692},"via_points":[[39.224174,9.118619],[39.231354,9.130034]],"found_alternative":false,"hint_data":{"locations":["eIcCAP______BQAAIwAAADEAAAAxAAAAAAAAABPMAAAAAAAAboNWApsjiwAEABEA","R0QAAP____8ZBgAARQAAAIYAAAAAAAAAAAAAAP____8AAAAAeJ9WAjJQiwAAABEA"],"checksum":3253836409}}

**Comment by daniel-j-h** [comment]
This recent pull request https://github.com/Project-OSRM/osrm-backend/pull/1818 does exactly that. Take a look at the modification it does to the profile.
