### ISSUE TITLE
Allowing bus tag

### ISSUE THREAD

**Issue by jskidd3** [Project-OSRM/osrm-backend#1463]
I am trying to configure OSRM to route through public service vehicle only lanes like the one seen here: http://www.openstreetmap.org/way/177087237#map=19/53.37773/-1.46455

I set up my profile.lua to allow for the bus/psv tag but I just can't get the route to go through the waypoint. Instead it takes a nearby A road and goes a very long way around! My profile can be found here: http://pastebin.com/EM6PuKs1

I have re-prepared OSRM once I have made changes to the profile using `./osrm-prepare great-britain-latest.osrm`.

I would really appreciate any help!

**Comment by emiltin** [comment]
try adding "bus" to access_tag_whitelist.

**Comment by jskidd3** [comment]
@emiltin As in literally just a string called "bus" or in the ["bus"] format? I do have ["bus"] in the lua already: http://pastebin.com/EM6PuKs1

**Comment by emiltin** [comment]
sorry i missed that. not sure why then. yu can always try simplifying the profile just to find out what part is rejecting the way.

**Comment by TheMarex** [comment]
@jskidd3 which version of OSRM are you using? That profile seems outdated.
