### ISSUE TITLE
Fine tune stxxl::vector parameters

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1464]
Looking at http://stxxl.sourceforge.net/tags/master/design_vector.html#design_vector_generator we can fine tune a lot of parameters. Currently `osrm-extractor` uses a lot less memory than would be available to it. We might get a considerable speedup here.

**Comment by danpat** [comment]
Under what circumstances is `osrm-extractor` not using enough RAM?  I fired up a `r3.8xlarge` AWS instance (240GB RAM) and tried to run `osrm-extractor` on the North American pbf from Geofabrik.  Without a swapfile in place, the kernel killed the process for OOM every time.  I was looking at the `masonize` branch, is there a leak perhaps?

Using a smaller dataset (Australia/Oceania), I played with a few different block/page/cache sizes, there wasn't a huge benefit with lots of RAM available.  Re-arranged data during `stxxl::sort` still incurs a disk write for dirty pages.  I saw upwards of 20GB of RAM used with the default settings.

There is a huge speedup available if there's lots of RAM though, and that's to point STXXL to a tmpfs file, or use the `memory` filesystem driver in the `.stxxl` config file.  File parsing is largely unaffected (it seems CPU bound), but once work begins in `ExtractionContainers::PrepareData`, using tmpfs dropped processing time from 100 seconds down to 10 seconds for the Australia/Oceania dataset.  Given the full OSM PBF is about 28GB, it seems feasible to use tmpfs on high-performance hardware (for the time being).

One other hurdle with tweaking the `stxxl::vector` parameters is that they're compile-time only.  This might make it tricky to easily adjust for changing hardware.  Thoughts?

**Comment by emiltin** [comment]
if you have enough ram to, then stxxl would not even be needed?

**Comment by TheMarex** [comment]
> Under what circumstances is osrm-extractor not using enough RAM? I fired up a r3.8xlarge AWS instance (240GB RAM) and tried to run osrm-extractor on the North American pbf from Geofabrik. Without a swapfile in place, the kernel killed the process for OOM every time. I was looking at the masonize branch, is there a leak perhaps?

That is curious. 240GB should be too much for even a planet extract. This is what we do on our server to setup an stxxl file:
```
echo "disk=/mnt/stxxl,200000,syscall" >> .stxxl
```
With that the memory consumption should be around 10GB as far as I remember. The docs state that the default configuration creates an `.stxxl` file of 1GB size.

> Using a smaller dataset (Australia/Oceania), I played with a few different block/page/cache sizes, there wasn't a huge benefit with lots of RAM available. Re-arranged data during stxxl::sort still incurs a disk write for dirty pages. I saw upwards of 20GB of RAM used with the default settings.

So my motivation behind tweaking the vector parameters to speed up sorting was that external memory sorting works in two steps: First the data is divided into runs that fit into memory and sorted and then written to disk again. In a second step all sorted runs are merged (this does not take a lot of internal memory as you only need one page per run in memory at all times).
I just ran the numbers that were given for k-way-merge-sorting algorithm that is used by `stxxl::sort`: Your measurements are correct, the block size does not matter at all for the amount of data we work with (since we stay well below the threshold that would require multiple merge steps). So having fewer runs that are bigger has no advantage.

It is actually super interesting that this algorithm uses the same amount of IO operations, no matter how much memory you give it for caching (if you look at the OSRM source the parameter to `stxxl::sort` sets `UINT_MAX` as maximum usage).

Good work measuring this. :+1:

**Comment by TheMarex** [comment]
@danpat Oh if you would like to try this as well: stxxl supports multiple physical disks for caching. So it would be cool if you could test how much faster it gets by doing that. Ideally the speedup would be 2 for 2 disks, but it will be probably a bit lower than that.

**Comment by danpat** [comment]
I'll give that a look tomorrow.  

As a side-issue, there is definitely a memory leak on the `masonize` branch.  When linked statically with the libraries that `mason` pulls down, `osrm-extract` rapidly consumes RAM, at about 100MB/sec.  When linked against the system libraries, everything works expected with fairly constant memory usage.

**Comment by springmeyer** [comment]
@danpat - wow. Do you see this for a small extract too? Thinking about possible culprits... seeing the stxxl registers `atexit` handlers and those are likely not getting called when stxxl is not a dll: https://github.com/stxxl/stxxl/blob/1f6b6c481b317c0def58b91bce363828206126f7/lib/common/exithandler.cpp#L59-L66

**Comment by springmeyer** [comment]
btw, just published `stxxl_shared 1.4.1` mason package. Would be great if you could give that a spin in the morning and see if it might fix the leak.

**Comment by danpat** [comment]
FWIW, the behaviour is the same on Linux and OS/X (eating memory when statically linked).

**Comment by danpat** [comment]
Linking dynamically against `stxxl_shared 1.4.1` does not correct the leak on OS X.

**Comment by danpat** [comment]
Ok, so I ran this against multiple combinations of volumes (EBS devices with provisioned IOPS):

1 disk   = 119 seconds to parse, 112 seconds total
2 disks = 60 seconds to parse, 110 seconds total
4 disks = 60 seconds to parse, 110 seconds total
in memory (stxxl 'memory' driver)  = 60 seconds to parse, 78 seconds total
tmpfs = 60 seconds to parse, 80 seconds total

Note that I also ran this with STXXL 1.3.1 (Ubuntu 14.0LTS package), and it was about 2x slower in all cases, 1.4.1 is a big improvement speed-wise.

Looks like processing is mostly CPU bound, not IO.  These numbers are on a `r3.8xlarge` EC2 instance with 8 vCPUs and 30GB RAM.  I used EBS volumes with 1500 provisioned IOPS to stripe.

**Comment by TheMarex** [comment]
@danpat are those only the numbers when running `osrm-extract`? With parsing you mean the time before the `ExtractorConatiners::PrepareData` call?

So your findings are (please correct me if I got something wrong) that the parallelized parsing is currently IO bound: Adding more bandwidth improves the runtime.
However the serial sorting and filtering is CPU bound: Adding more bandwidth had no effect on the runtime. So potentially we could improve runtime here by adding more parallelization.

Regarding the stxxl memory leak we see the following behavior:

stxxl version | Ubuntu 14.04 static | Ubuntu 14.04 dynamic |  OS X  static |    OS X dynamic |
-----------------|--------------------------|-------------------------------|-------------------|----------------------|
1.3.1             |             /                   |            no leak               |          ?           |             ?             |
1.4.1             |          leak                 |            leak                   |         leak        |         leak            |

**Comment by danpat** [comment]
I just opened #1484 to track the memory leak problem.  It seems not related to STXXL.

I made a typo in those results, the 1-disk scenario results were:

1 disk = 60 seconds to parse, 112 seconds total

During parsing (before `ExtractorConatiners::PrepareData`), all CPU's were pegged to 100%.  `iotop` and `iostat` showed limited IO wait, and far less bandwidth consumption than the disks can provide.  My interpretation is that parsing is CPU bound at this stage.

Sorting also seems mostly CPU bound.  While changing to tmpfs/memory did give a pretty good speedup, a good chunk of the time is still tied to the CPU.  It seems that STXXL is single-threaded for `vector.sort()`, I observed just a single thread mostly pegged at 100% during the sort phase.

It looks like there could be some performance gain by introducing some parallelism during the sorting, but it's not obvious where.  `stxxl::vector` is not thread safe, but it looks like some of those sorts could be done in parallel.  Unfortunately, the bulk of the sort time is taken up by just a couple of operations (sorting all nodes, all edges) which look like they depend on each other.

**Comment by TheMarex** [comment]
We could get a parallelized sorting from stxxl, but they use GNU OpenMP which we removed as a dependency from OSRM a while ago an replaced with TBB (much nicer interface and better clang support). So, sadly no easy wins here. Thanks again @danpat for figuring this out!
