### ISSUE TITLE
Border used instead of village of the same name

### ISSUE THREAD

**Issue by cweiske** [Project-OSRM/osrm-backend#1466]
I tried to route from "Nitzschka" to "Dehnitz", and got routed into nowhere:

http://www.openstreetmap.org/directions?engine=osrm_car&route=51.3102%2C12.7591%3B51.3446%2C12.7435#map=13/51.3276/12.7568&layers=Q

Reason seems to be that there are two results for "Dehnitz"; one is the village itself, the other one is the border. OSRM should prefer the village.

**Comment by TheMarex** [comment]
Not a bug in OSRM but the geocoder Nominatim. Would be great if you could report it there.  :+1:

**Comment by cweiske** [comment]
@TheMarex: Why is this a bug in Nominatim? I thought that OSRM uses Nominatim for fetching the coordinates for a name, but OSRM has to decide which of the returned coordinates gets used? Or am I wrong in my thinking?
