### ISSUE TITLE
Show Lua runtime errors during extraction

### ISSUE THREAD

**Issue by systemed** [Project-OSRM/osrm-backend#1467]
At present Lua runtime errors encountered during extraction just throw a generic "Lua runtime error".

During contraction, however, the runtime error is reported fully:

    if (0 != luaL_dofile(lua_state, profile_path.string().c_str()))
    {
        std::cerr << lua_tostring(lua_state, -1) << " occured in scripting block" << std::endl;
        return false;
    }

I think OSRM used to show Lua errors during extraction too - I found this code in an old version:

	try {
		...
	} catch (const luabind::error &er) {
		std::cerr << er.what() << std::endl;
		lua_State* Ler = er.state();
		report_errors(Ler, -1);
	}

	...
	void BaseParser::report_errors(lua_State *L, const int status) const {
	    if( 0!=status ) {
	        std::cerr << "-- " << lua_tostring(L, -1) << std::endl;
	        lua_pop(L, 1); // remove error message
	    }
	}

**Comment by TheMarex** [comment]
Fixed.
