### ISSUE TITLE
route_geometry not properly encoded

### ISSUE THREAD

**Issue by hammady** [Project-OSRM/osrm-backend#1469]
When I use the `viaroute` API, I never get `route_geometry` properly encoded. When I try to decode the string using [google decoder](https://developers.google.com/maps/documentation/utilities/polylineutility) or using the [ruby gem](https://github.com/joshuaclayton/polylines), it gives wrong points.
Tried both local and [online](https://router.project-osrm.org/) router.
Example:

    curl "http://router.project-osrm.org/viaroute?loc=25.2686540247636,51.5151079014087&loc=25.2691148472725,51.5134895650915&instructions=true&output=json&geometry=true"

Returns:

    {"status":0,"route_instructions":[["10","Ali Bin Abi Talib Street",45,0,6,"45m","SW",234,1],["2","",72,1,5,"72m","W",250,1],["1","C Ring Road",92,5,4,"91m","NW",321,1],["15","",0,6,0,"0m","N",0]],"route_name":["Ali Bin Abi Talib Street","C Ring Road"],"status_message":"Found route between points","via_indices":[0,7],"route_geometry":"gygeo@qmfgaBbNnUnCjMCrE_@lBoHfOkg@nb@","route_summary":{"end_point":"C Ring Road","start_point":"Ali Bin Abi Talib Street","total_time":13,"total_distance":209},"via_points":[[25.268644,51.515114],[25.269146,51.513535]],"found_alternative":false,"hint_data":{"locations":["OjMAAP____9VAAAAIAAAAEAAAAAAAAAAAAAAAP____8AAAAApJGBAekOEgMAABEA","RDMAAP____9LAAAALAAAADkAAAAAAAAAAwAAAA0bAAAAAAAAmpOBAb4IEgMAABEA"],"checksum":1652815973}}

The route_geometry `gygeo@qmfgaBbNnUnCjMCrE_@lBoHfOkg@nb@` is definitely wrong.

However, if I use the gpx format, and encode the route points I get the correct geometry (verified from google decoder and the ruby gem above):

    <?xml version="1.0" encoding="UTF-8"?><gpx creator="OSRM Routing Engine" version="1.1" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 gpx.xsd"><metadata><copyright author="Project OSRM"><license>Data (c) OpenStreetMap contributors (ODbL)</license></copyright></metadata><rte><rtept lat="25.268644" lon="51.515113"/><rtept lat="25.268402" lon="51.514753"/><rtept lat="25.268330" lon="51.514523"/><rtept lat="25.268332" lon="51.514417"/><rtept lat="25.268348" lon="51.514362"/><rtept lat="25.268500" lon="51.514102"/><rtept lat="25.269146" lon="51.513534"/></rte></gpx>

The encoded string should be: `_hfyCmplyHn@fALl@?RCJ]r@aCpB`

Am I missing something?

**Comment by emiltin** [comment]
osrm uses 6 decimals. see the wiki.

**Comment by hammady** [comment]
Figured out it is scaled by 10, duplicate of #713
Thanks

**Comment by hammady** [comment]
Sorry, I couldn't find it clearly in the wiki, which page you mean?

**Comment by emiltin** [comment]
hmm i couldn't find it in the wiki either, so i added a note about it at https://github.com/Project-OSRM/osrm-backend/wiki/Server-api.

**Comment by TheMarex** [comment]
Thanks @emiltin for adding that to the wiki. Closing.
