### ISSUE TITLE
Get Edge Coordinates

### ISSUE THREAD

**Issue by camviluong** [Project-OSRM/osrm-backend#1470]
I have some question, can anyone help me, please!

+ How to get the coordinate of an edge?
+ how to get the end node of an edge in GetAdjacentEdge?

Thank you very much

**Comment by TheMarex** [comment]
To answer that question I need to know a little more of where in the source code you are trying to add code. :wink:

The node ids you get from `DynamicGraph` or `StaticGraph` in preprocessing are indices for a node array. In the server I would have a look at `InternalDataFacade`

**Comment by camviluong** [comment]
hi Marex,

I have implement my code in InternalDataFacade. Now, I f have a edgeId:
 + I need to identify all of vertices if this edge
 + How to I get begin nodeId and end nodeId (as I know, GetTarget(EdgeId) is function to get the end NodeId of a edge?

**Comment by fpacheco** [comment]
I have the same need. 
It know it has already asked in the OSRM list, but it is still  unanswered. 

Can anyone give me a hint about this issue.?. Thank you very much.

**Comment by TheMarex** [comment]
>  I need to identify all of vertices if this edge

Have a look at RoutingBase::UnpackPath() that produces the geometry from a list of nodes.

> How to I get begin nodeId and end nodeId (as I know, GetTarget(EdgeId) is function to get the end NodeId of a edge?

Well, how did you obtain the edge id? There is no easy way to get a mapping EdgeID -> NodeID that I'm aware of. Please note that you are dealing with an edge-based graph: Nodes in this graph are street segments and edges are turns.
