### ISSUE TITLE
How to count different kind streets for a route?

### ISSUE THREAD

**Issue by wendibus** [Project-OSRM/osrm-backend#1472]
Hi,

sorry for my maybe dumb question. What I would like to do is a small routing service for bicycles. And instead of one bicycle profile I would like to alter the profiles. One for ordinary bikes, one for racing bikes and one for mountain bikes. I have looked into the existing profiles and I guess that I understood how to use them.

No I would like to say that e.g. the route for the mountain bike has a certain percentage of this kind of road and a certain percentage of that kind of road.

Can this be done without changing osrm?

As far as I understood the result of the routing is a list like
if you would like to go from Point A to Point D you have to go via B and C.

Point A
Point B
Point C
Point D

I do receive these coordinates (depending on the lua profile). What I lack to understand is if it is possible to create the information

Point A "Service Road"
Point B "Road"
Point C ...

and make a summary like 23% Service Road etc.

Just to give an idea about what to expect on that route ...

I hope that I have expressed myself well enough. If not: Please ask

**Comment by emiltin** [comment]
There's no clean way to do this, but as a work-around you can stuff info into the street name, end extract it again in the front end. we use this hack on www.iibkecph.dk, to pass the way type so we can use it when the road has no name, eg "turn left on service road". see https://github.com/ibikecph/osrm-backend/blob/master/profiles/bicycle_fast.lua#L393.

See #1342 for a suggestion for a more organized way to do it.

**Comment by wendibus** [comment]
Thank you very much. I quote your beautiful web-site because there is a typo and I could not find it at once http://www.ibikecph.dk, it is a really nice one.

By the way: If you like support in translating your service to German. I could do so (but I would have to use the english version as basis).

And thanks for the #1342 hint. It shows the direction I was thinking about. I would not like to touch osrm itself. I guess I will follow that route ...

**Comment by emiltin** [comment]
ah, sorry about the type. thanks for you offer to translate to german! at this point I thinks it's too much work for us to maintain it in german, since it only works in danish. but the code for the rails app is open source and available here on github if anyone want to reuse it.
