### ISSUE TITLE
Bug in route with intermediate points

### ISSUE THREAD

**Issue by etorrano** [Project-OSRM/osrm-backend#1474]
We found a bug in a route that I have done in Montevideo with three intermediate points.

We saw a strange behaviour in the following route:
http://osrm.at/cle

But if you delete point three, the problem disappears:
http://osrm.at/clh

This problem could be similar to this issue: #1451

**Comment by emiltin** [comment]
here's a reduction: http://map.project-osrm.org/?hl=en&loc=-34.862991,-56.206753&loc=-34.863026,-56.206497&loc=-34.866505,-56.206902&z=17&center=-34.864960,-56.208608&alt=0&df=0&re=0&ly=-1171809665

**Comment by TheMarex** [comment]
Yes this is indeed strange. Flagging as bug.

**Comment by dkastl** [comment]
Is it similar to this example?
![osrm website](https://cloud.githubusercontent.com/assets/227762/7654747/4cb716ea-fb5a-11e4-8b42-1d6545600947.png)
http://osrm.at/cmO

To me it seems, that this is some sort of "turn". 
Moving the via point slightly makes it go also a longer route than I would expect:
![osrm website](https://cloud.githubusercontent.com/assets/227762/7654782/8600516e-fb5a-11e4-9c08-6450c059c3c9.png)
http://osrm.at/cmP

(There are no one way streets or restrictions in this area.)

**Comment by woodbri** [comment]
This issue is causing us major headaches. We would be grateful if this could be made a priority.

**Comment by fpacheco** [comment]
Look at this strange loops:
http://osrm.at/cmX
![2](https://cloud.githubusercontent.com/assets/89121/7655865/018dd1ac-fafd-11e4-940a-930c964e69e1.png)

Or this other: 
http://osrm.at/cmY
![3](https://cloud.githubusercontent.com/assets/89121/7655937/919869f6-fafd-11e4-8a29-141118921137.png)

There are no one way streets or turn restrictions in this area. 

![4](https://cloud.githubusercontent.com/assets/89121/7656021/357fab88-fafe-11e4-8e39-fa63297efd54.png)

Thanks. Fernando.

**Comment by woodbri** [comment]
@fpacheco Thank you for a great example of the problem we are having. In the 2nd example about the route is looping clockwise from the start 3 times around the block to pickup the via points in reverse order instead of once around the block counter-clockwise to pickup the via points in order.

**Comment by woodbri** [comment]
Here is an other example happening in New York. This might be a good test case because:
Works: http://osrm.at/cnh
Loops: http://osrm.at/cnj

**Comment by TheMarex** [comment]
Can someone replicate this with local extracts? The example in Uruguay from @emiltin only works on full planet extracts for some reason.

**Comment by woodbri** [comment]
Yes, I can reproduce this on an extract of just the city of Montevideo. My extract is here: http://imaptools.com:8080/dl/montevideo.osm.pbf

**Comment by emiltin** [comment]
i get 'forbidden' when trying to access the link.

**Comment by emiltin** [comment]
it would be nice to capture the bug in a cucumber test. you can load .pbf files in cuke tests.

**Comment by woodbri** [comment]
Sorry changed the permissions. try again. Also I'm in the process of doing  git bisect on the issue in #1451

**Comment by danpat** [comment]
@woodbri - look at 11c671354be8c791ef107e6ce6c4a38435417edb.  I bisected for #1429 a while ago, and that commit definitely affected how routes were weighted.

**Comment by woodbri** [comment]
This looks like it is working correctly on map.project-osrm.org now on develop after revering 11c6713

**Comment by fpacheco** [comment]
Luckily the loops disappeared, but now bug #1424 is active again !.
