### ISSUE TITLE
Problem routing small distances

### ISSUE THREAD

**Issue by afmenez** [Project-OSRM/osrm-backend#1475]
I frequently use the OSRM tool to test routing issues on OSM, and sometimes I ask for very small routes.  I found an issue with this one:

http://map.project-osrm.org/?hl=pt&loc=-29.152716,-51.163956&loc=-29.151793,-51.164680&z=18&center=-29.152627,-51.164773&alt=0&df=0&re=0&ly=-1171809665

It should just turn right, but goes around the "roundabout" first.  The issue does not show if the path is a little longer:

http://map.project-osrm.org/?hl=pt&loc=-29.152967,-51.161503&loc=-29.151793,-51.164680&z=18&center=-29.152627,-51.164773&alt=0&df=0&re=0&ly=-1171809665

**Comment by TheMarex** [comment]
Thanks for the report! Looks definitely like a bug on the OSRM side not the data side.

**Comment by woodbri** [comment]
I think this is the same as #1474 if you add an intermediate point http://osrm.at/clV you get the same loop about roundabout.

**Comment by afmenez** [comment]
Yep, the effect is similar, but issue #1474 seems to imply that an intermediate point is mandatory for the issue to appear, and in this case it is not.  If you consider that when you add an intermediate point you actually have two routes, we go back to the problem in short routes.  Which may even be the actual problem in #1474.

**Comment by woodbri** [comment]
We are using OSRM to compute billions of short routes to compute travel times in a VRP solver. While I have not identified a specific problem related to this, I'm sure we are also running into this issue also.

**Comment by afmenez** [comment]
I am not sure if there was a change in the map, the problem is intermittent or if it was fixed, but right now both the links I shared in the first post, the link shared by woodbri and the issues at #1474 seem to be routing fine.

**Comment by woodbri** [comment]
This looks like it is working correctly on map.project-osrm.org now on develop after revering 11c6713
