### ISSUE TITLE
How to setup OSRM in windows server

### ISSUE THREAD

**Issue by dqlabxqs** [Project-OSRM/osrm-backend#1477]
Where  can I find a lesson about OSRM running in windows server ? Thanks .

**Comment by TheMarex** [comment]
Have a look at the wiki https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation

**Comment by dqlabxqs** [comment]
Thanks a lot.

**Comment by dqlabxqs** [comment]
@TheMarex . I know how to build it. But I don't know how to running in windows.
