### ISSUE TITLE
viaroute and snapping

### ISSUE THREAD

**Issue by MannusEtten** [Project-OSRM/osrm-backend#1483]
i would like to use the viaroute-webservice for a bulk operation.
what are the limitations for this?

second, does the viaroute snapping? Lets assume i take a point which is not on the network, does the webservices starts at a location close to my point?

**Comment by chaupow** [comment]
Hi @MannusEtten!

I don't know so much about limitations for viarouting (what kind of limitations do you mean?) but I can answer this:

> second, does the viaroute snapping? Lets assume i take a point which is not on the network, does the webservices starts at a location close to my point?

yes, OSRM does coordinate snapping. The new node is called the phantom node which is a node on a street that is nearest to your request.

(@TheMarex, please correct me if I'm wrong)

**Comment by TheMarex** [comment]
> i would like to use the viaroute-webservice for a bulk operation. what are the limitations for this?

Please **don't do this** on the public demo server (e.g. `http://router.project-osrm.org`). You should set up your own instance for this kind of requests.

You might want to consider using the [distance table](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#service-table) service for this.
