### ISSUE TITLE
Memory leak when building statically with mason

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1484]
When building using the `masonize` branch, `osrm-extract` leaks memory rapidly during the parsing phase.

So far, I've tried the following combinations:

OS X all static with `mason` = leak
Linux all static with `mason` = leak
Linux dynamically linked with normal build script against system libs = no leak
Linux mostly static, with TBB and Lua 5.2/Luabind dynamically linked from system = no leak
Linux mostly static with TBB dynamically linked from system = leak

This hints that it's the static versions of Lua/Luabind that have problems.  Requires further research.

**Comment by springmeyer** [comment]
@danpat - have you tried using valgrind to see where in the code the leak is happening? Also, would it be possible to share the details of how you are replicating on osx? I ran `osrm-extract` on a berlin extract I have locally and did not yet track down the leak. I'm planning to look into this morn late afternoon today.

**Comment by danpat** [comment]
With smaller data sets, it's not quite so noticeable.  I'm using the Australia/Oceania data PBF from GeoFabrik that's about 400MB.

On OS/X, run `top -o vsize` on a long-running `osrm-extract` process and watch it grow.  When the leak is not present, `vsize` stays relatively constant.

**Comment by danpat** [comment]
Looks like it's the static `liblua.a` that triggers the leak.

Linux, does not leak using system dynamic `liblua5.2`:

    $ ldd osrm-extract
    linux-vdso.so.1 =>  (0x00007ffd4a9fb000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8467b8c000)
    libtbb.so.2 => /home/danpat/osrm-backend-masonize/mason_packages/.link/lib/libtbb.so.2 (0x00007f8467953000)
    liblua5.2.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007f8467721000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8467508000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8467204000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8466efd000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8466ce7000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8466922000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f8467db6000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f846671d000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8466515000)

Linux, leaks using static `liblua.a` from `mason`:

    $ ldd osrm-extract
    linux-vdso.so.1 =>  (0x00007ffd5f188000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f34d6932000)
    libtbb.so.2 => /home/danpat/osrm-backend-masonize/mason_packages/.link/lib/libtbb.so.2 (0x00007f34d66f9000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f34d64df000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f34d61db000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f34d5ed5000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f34d5cbe000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f34d58f9000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f34d6b5c000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f34d56f5000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f34d54ec000)

**Comment by danpat** [comment]
Leak disappears when static linking against `lua 5.1.0` and `luabind_lua51`.

**Comment by springmeyer** [comment]
Incredible work narrowing this down. So perhaps this is a lua 5.2.0 bug and is fixed in 5.2.1 or greater? I see a few memory related issues at http://www.lua.org/bugs.html#5.2.0-1. The reason `5.2.0` is used currently in the `masonize` branch is that we started with `5.3.0` as the latest release, then hit incompatibility with the profiles [that is now fixed](https://github.com/Project-OSRM/osrm-backend/pull/1457) and dropped to `5.2.0` to narrow down the issue without realizing there were more recent `5.2.x` releases.

So, what about I package `lua 5.2.4` + luabind and you can test if that fixes things?

**Comment by danpat** [comment]
Sounds like a good next step.  I played around with `valgrind`, but it didn't reveal any glaring leaks, whatever is building up doesn't seem to be totally lost.

**Comment by springmeyer** [comment]
@danpat ^^ ready. You should be able to do `rm -rf mason_packages/ && source bootstrap.sh` to get refreshed packages. There is no `mason unlink` or `mason uninstall` yet (we need these) so I tend to just clear out all of `./mason_packages` to be sure the new stuff comes down.

**Comment by danpat** [comment]
Yup, that seems to have fixed it.  Static linking against 5.2.4 doesn't exhibit the leaky behaviour.
