### ISSUE TITLE
Setting start/end markers gives wrong street names

### ISSUE THREAD

**Issue by Morphan** [Project-OSRM/osrm-backend#1486]
Hi,

target recognition when setting a marker seems a bit too off the mark: The street names in the route description are accurate, but the street names specified as start/end sometimes not. The misrepresentations are nearby roads, which are not necessarily connected to the "correct" street.

Example:
http://map.project-osrm.org/?hl=de&loc=51.428352,6.787983&loc=51.428658,6.789180&z=18&center=51.427971,6.787848&alt=0&df=0&re=0&ly=-1171809665

The start on "Memelstraße" is identified as "Hessenstraße", the destination on "Schönhauser Straße" as "Grabenstraße".
If I move the destination marker piecewise on the road to the northwest, the "Schönhauser Straße" is at some point properly identified. But at the turning circle it is erroneously indentified as "Bismarckstraße" (which lies on the other side of the block and is not connected to the destination street).

**Comment by TheMarex** [comment]
The wrong street names come form the geocoder https://github.com/twain47/Nominatim 
Would be awesome if you could report the problem there. :+1:

**Comment by lonvia** [comment]
Not necessarily Nominatim's fault. OSRM asks for the address on house level, so Nominatim returns the nearest house it can find which actually might belong to a different street. For example, in the case of [Memelstrasse](http://www.openstreetmap.org/?mlat=51.428352&mlon=6.787983&zoom=18) the closest address comes from the Hallenbad right next to your coordinate, which happens to have its official address on the 'Hessenstrasse'. I'm rather undecided what the right behaviour should be in this case. However, as OSRM shows the location only on street level anyways, I would recommend to add 'zoom=17' to the request to Nominatim which results in street-level precision of the reverse geocoding. In the example above that would yield the correct answers:

http://nominatim.osm.org/reverse?lat=51.428352&lon=6.787983&zoom=17

http://nominatim.osm.org/reverse?lat=51.428658&lon=6.789180&zoom=17
