### ISSUE TITLE
Feature request: use the correct case when displaying the names of instructions

### ISSUE THREAD

**Issue by socketpair** [Project-OSRM/osrm-backend#1488]
Unfortunatelly, in other languages, correct translation of (for example) `Turn left onto NAME` requires some transformations on `NAME` (change forms of the words in `NAME`). Without that, instructions are not looking good.

I will try to explain using mix of languages. Instead of `Turn left onto Уральская улица` it should be `Turn left onto УральскУЮ улицУ`. (I highlated changes using caps-lock).

i.e. instead of `Поверните налево на Уральская улица` it should be `Поверните налево на Уральскую улицу`.

Seems http://nlp.lsi.upc.edu/freeling/ or another Natural Language Processing libraries can help for that problem.

It will be nice if you can handle that in routing instructions. AFAIK no one implement that.

**Comment by TheMarex** [comment]
@socketpair natural language text is only handled in the frontend. OSRM only responds with the turn instruction as a number and the street name as it is specified in OpenStreetMap. Maybe have a look at https://github.com/perliedman/leaflet-routing-machine
