### ISSUE TITLE
Remove GPX output format

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1489]
Responses by the server should handled in JSON only.

- The response of most plugins has no meaningful mapping to GPX
- The current implementation of GPX is a hack that involves rendering JSON first and then transforming that into XML
- It creates an unneeded complexity in the response rendering code
- It is off little use in the current form https://github.com/Project-OSRM/osrm-backend/issues/1180

Since this breaks the API we should aim for 5.0

**Comment by stevage** [comment]
What does this mean for the current way GPX's are generated in OSRM-web? Is the "hack" that you refer to done in the client already, and hence this isn't needed?

**Comment by TheMarex** [comment]
@stevage no gpx is currently generated at the server. But it is pretty trivial for the client to transform JSON to XML if needed.

**Comment by TheMarex** [comment]
This was implemented as part of https://github.com/Project-OSRM/osrm-backend/pull/1851
