### ISSUE TITLE
Ignore access restrictions on crossings for bicycle profile

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1492]
Nodes that are tagged with `bicycle=no` get automatically classified as barriers. If the node has the tag `highway=crossing` the [semantics are different](http://wiki.openstreetmap.org/wiki/Key:crossing): It just means you are not allowed to ride a bicycle over the crossing that is perpendicular to the way.

So if the node is a crossing, it should ignore the access restrictions.

**Comment by TheMarex** [comment]
This is implemented. https://github.com/Project-OSRM/osrm-backend/pull/1507

**Comment by emiltin** [comment]
i think that tagging scheme is unfortunate. bicycle=dismount would be much more correct. bicycle=no usually means bikes not allowed, not even pushing them. but there is confusion about that evne for the general case of ways and paths.
