### ISSUE TITLE
TarjanSCC ignores turn restrictions and barriers

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1495]
The strongly connected component search currently ignores turn restrictions and barriers. This leads to strange results when combined with the nearest neighbor search algorithm: We think that we found an edge from a large component, but instead the edge belongs to a disconnected component. A great example for this are the [service roads around the Denver Airport](https://www.openstreetmap.org/node/2180891025). They are disconnected by a fence from the rest of the road network, but current OSRM classifies them as being connected.

A proposed fix is in [this PR](https://github.com/Project-OSRM/osrm-backend/pull/1493). However the Tarjan's algorithm in its naive implementation can not handle turn restrictions. However barriers should be fine (since they don't depend on direction).
My proposed fixed will make the algorithm a lot slower and I'm not 100% sure if it is actually correct (that is: I don't have a proof of correctness).

**Comment by TheMarex** [comment]
This was fixed by moving the TarjanSCC to the edge-based-graph.

**Comment by daniel-j-h** [comment]
> This was fixed by moving the TarjanSCC to the edge-based-graph.

Great!
