### ISSUE TITLE
Strange routing on polish road 61

### ISSUE THREAD

**Issue by kocio-pl** [Project-OSRM/osrm-backend#1498]
From this point routing tries to go around:

http://map.project-osrm.org/?hl=pl&loc=52.510853,21.049023&loc=52.506504,21.046484&z=18&center=52.510493,21.047485&alt=0&df=0&re=0&ly=-1171809665

but after this point it goes straight (as expected):

http://map.project-osrm.org/?hl=pl&loc=52.510704,21.048935&loc=52.506504,21.046484&z=18&center=52.510408,21.047839&alt=0&df=0&re=0&ly=-1171809665

**Comment by danpat** [comment]
In the first example, the start point has been placed closer the exit ramp than the highway.  The exit ramp is a one-way road, so the routing has no choice but to continue up the exit ramp, then re-enter the highway.

**Comment by kocio-pl** [comment]
[Longer distance](http://map.project-osrm.org/?hl=pl&loc=52.515972,21.053986&loc=52.506504,21.046484&z=18&center=52.515129,21.052849&alt=0&df=0&re=0&ly=-1171809665) doesn't help (the problem originally appeared when planning bigger journey) and MapQuest routing goes straight there.

**Comment by danpat** [comment]
Ah, I see.  Interesting that while dragging, the correct path is highlighted, but after dropping the pointer, the incorrect route is selected.

**Comment by TheMarex** [comment]
Ah, that is probably because when you drag a route `alt=false` is passed, which means the `shortest_path` algorithm is used instead of `alternative_path`. So this is most likely a side-effect of reverting the fix for #1429.

**Comment by TheMarex** [comment]
Seems like this is a bug in the data model. There is simply no edge from the segment before the first lane split to after the lane split. But there is a reverse edge, so the CH-search will find that.

So we are missing an edge. Steps to figure this out:
- Figure out edge based node ids before contraction
- Check if edge is present in the `Contractor`
   - before construction
   - after construction, before contraction
   - after contraction
- Check if edge is present in the `EdgeBasedFactory`

**Comment by kocio-pl** [comment]
Isn't [this bug](http://osrm.at/cPG) the same really, because it looks similar to me, or something else maybe?

**Comment by TheMarex** [comment]
This bug is not present in OSRM v4.5.0 https://www.mapbox.com/directions-feedback/mapbox/?profile=driving&route=21.04926288127899,52.51122761041336;21.04555606842041,52.50441504230562#19/21.04964/52.51091

**Comment by TheMarex** [comment]
Did a bisect: At least for `alternative_path` b15599f01e57751c306e5fd2a13d8bcb4db83f45 seems the origin of this.

**Comment by TheMarex** [comment]
Looks like another incarnation of bugs related to 11c671354be8c791ef107e6ce6c4a38435417edb. Bisecting with `&alt=false` brought this commit up. So this is broken in both `alternative_path` and `shortest_path` for different reasons.

**Comment by danpat** [comment]
@TheMarex in b15599f01e57751c306e5fd2a13d8bcb4db83f45, it looks like the sign changed from - to + for min_edge_offset.  @DennisOSRM 's comment indicates that it wasn't a logic change, just a code cleanup, so maybe just prepending "-" will fix it up.

**Comment by TheMarex** [comment]
This is fixed.
