### ISSUE TITLE
viaroute for one location fails locally but not on map.project-osrm.org

### ISSUE THREAD

**Issue by PureW** [Project-OSRM/osrm-backend#1499]
Hello,

I'm using the osrm-backend v4.6.1 and the car.lua-profile with the swedish datafiles from download.geofabrik.de/europe/ and I prepare the datafiles as in your documentation, see script here: https://gist.github.com/PureW/6128172a5a0b0e80a7dd

Now to my problem: The routing generally works fine and it's been a joy using your software. However I noticed yesterday that some viaroute-requests starting near the center of swedish city Linköping results in failed routing-requests. For example the following:

    curl http://localhost:5000/viaroute\?loc\=58.41087%2C15.621999\&loc\=58.587578%2C16.192509            
    {"status_message":"Cannot find route between points","status":207}

While a minor modification to latitude works fine:

    curl http://localhost:5000/viaroute\?loc\=58.41187%2C15.621999\&loc\=58.587578%2C16.192509
    {"hint_data":{"locations":["5QMAAP____8DAwAAPwAAAGEAAAAAAAAAagAAABWKAAAAAAAAoEp7A5Zf7gAAABEA","1C4AANZODABzAgAAQwAAABAAAAAAAAAAEgAAAG06EwAAAAAAtvl9A_0T9wAAABEA"],"checksum":2527338810},"route_name":["",""],"via_indices":[0,549],"via_points":[[58.411678,15.622038],[58.587578,16.192509]],"found_alternative":false,"route_summary":{"end_point":"Hantverkaregatan","start_point":"Ågatan","total_time":1897,"total_distance":42385},"route_geometry":"_idlnBkxnx\\`@bRdDdz@^za@eCnjAm@xR

The strange thing is that the first non-working example seems to work on your public site http://map.project-osrm.org/

**My questions are**: 
 * Have you seen this before? 
 * How do I debug this further?
 * Why does it seem to work fine on your public backend, do you preprocess the locations before sending it to /viaroute?

EDIT: I updated the datafiles and processed them again just now to see if there was an artifact in my datafiles but if so, it still remains.

**Comment by PureW** [comment]
Ok, I tested some more and compared to google maps. It is a tricky site because Linköping has lots of single-direction streets as well as car-free streets. It's not just simply my local OSRM that has problems, the public one has problems too. Google seems to handle it better, by driving on Storgatan which seems to be a pedestrian street.

Maybe I'll try to solve it by moving the start- or end-position a little if no route can be found.

**Comment by TheMarex** [comment]
@PureW give the current `develop` branch a try. I have seen some issues like this cropping up recently.

**Comment by PureW** [comment]
Unfortunately the development-branch is the same.

**Comment by TheMarex** [comment]
Okay, found the problem. It is indeed the nearest neighbor search: "Storgartan" is tagged as `private` for motor vehicles. However OSRM thinks it found an accessible street for some reason.

Can you try the demo server in 24h again? There is a change pending that might fix this.

**Comment by PureW** [comment]
It's been 19h, but it seems to be the same still. I made a link showing the probem: http://osrm.at/cEh

You can see google maps solution at http://bit.ly/1JcsJIP

I'll check again in a while in case the update hasn't gone through yet

**Comment by PureW** [comment]
I guess either the change wasn't applied yet or the change didn't fix the problem? http://osrm.at/cEh

**Comment by TheMarex** [comment]
@PureW yes didn't fix the problem. The problems that causes this is discussed in https://github.com/Project-OSRM/osrm-backend/pull/1493 but fixing it isn't easy.

**Comment by daniel-j-h** [comment]
Should be fixed with https://github.com/Project-OSRM/osrm-backend/pull/1565. Please try again and report back if you are still seeing issues.
