### ISSUE TITLE
osrm-datastore

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1511]
The requested memory should be page aligned to get `mlock` to work.

**Comment by daniel-j-h** [comment]
Grepping through the repository for mlock reveals only two mlockall calls.
One in [datastore.cpp](https://github.com/Project-OSRM/osrm-backend/blob/9967dbbaa93209809c9dab7a99aae2746ee687cf/datastore.cpp#L106-L107) and one in [routed.cpp](https://github.com/Project-OSRM/osrm-backend/blob/9967dbbaa93209809c9dab7a99aae2746ee687cf/routed.cpp#L94-L95).

Both do not require us to align memory, as they simply lock all current/future pages into the address space.

This is related to a different error code returned by mlockall, as documented in mlockall(2).

**Comment by TheMarex** [comment]
@daniel-j-h Okay so not really a bug on our side after all?

**Comment by daniel-j-h** [comment]
The call fails on missing capabilities (tested on my Gentoo and Ubuntu 15.04 machines).
Seems like CAP_IPC_LOCK has to be set, see `capabilities(7)`.

    $ sudo setcap "cap_ipc_lock=ep" osrm-routed

Check capabilities:

    $ getcap osrm-routed
    osrm-routed = cap_ipc_lock+ep

**Comment by TheMarex** [comment]
@daniel-j-h can you add that information to the wiki?

**Comment by daniel-j-h** [comment]
[Done](https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory#using-shared-memory), closing this.
