### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by AleksMx** [Project-OSRM/osrm-backend#1513]
Hello, I use Debian Wheezy x64, gcc 4.8 and I try to compile OSRM. I successfully complie 4.4.0 version, but when I try to build last version from git or v4.6.1, or v4.5.0 I have this error:

Scanning dependencies of target osrm-extract
[ 58%] Building CXX object CMakeFiles/osrm-extract.dir/extract.cpp.o
[ 61%] Building CXX object CMakeFiles/osrm-extract.dir/extractor/extraction_containers.cpp.o
[ 64%] Building CXX object CMakeFiles/osrm-extract.dir/extractor/extractor_callbacks.cpp.o
[ 66%] Building CXX object CMakeFiles/osrm-extract.dir/extractor/extractor.cpp.o
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_input_format.hpp:54:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/pbf_input.hpp:37,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:38,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_parser.hpp: In function ‘osmium::io::Header osmium::io::detail::parse_header_blob(const string&)’:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_parser.hpp:398:38: error: ‘class OSMPBF::HeaderBlock’ has no member named ‘has_osmosis_replication_timestamp’
                 if (pbf_header_block.has_osmosis_replication_timestamp()) {
                                      ^
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_parser.hpp:399:100: error: ‘class OSMPBF::HeaderBlock’ has no member named ‘osmosis_replication_timestamp’
                     header.set("osmosis_replication_timestamp", osmium::Timestamp(pbf_header_block.osmosis_replication_timestamp()).to_iso());
                                                                                                    ^
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_parser.hpp:402:38: error: ‘class OSMPBF::HeaderBlock’ has no member named ‘has_osmosis_replication_sequence_number’
                 if (pbf_header_block.has_osmosis_replication_sequence_number()) {
                                      ^
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_parser.hpp:403:103: error: ‘class OSMPBF::HeaderBlock’ has no member named ‘osmosis_replication_sequence_number’
                     header.set("osmosis_replication_sequence_number", std::to_string(pbf_header_block.osmosis_replication_sequence_number()));
                                                                                                       ^
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_parser.hpp:406:38: error: ‘class OSMPBF::HeaderBlock’ has no member named ‘has_osmosis_replication_base_url’
                 if (pbf_header_block.has_osmosis_replication_base_url()) {
                                      ^
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_parser.hpp:407:81: error: ‘class OSMPBF::HeaderBlock’ has no member named ‘osmosis_replication_base_url’
                     header.set("osmosis_replication_base_url", pbf_header_block.osmosis_replication_base_url());
                                                                                 ^
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/compression.hpp:52:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/bzip2_compression.hpp:48,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_compression.hpp:36,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:36,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/file_compression.hpp: In function ‘const char* osmium::io::as_string(osmium::io::file_compression)’:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/file_compression.hpp:60:9: warning: control reaches end of non-void function [-Wreturn-type]
         }
         ^
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/file.hpp:42:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/input_format.hpp:43,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/reader.hpp:55,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/pbf_input.hpp:36,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:38,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/file_format.hpp: In function ‘const char* osmium::io::as_string(osmium::io::file_format)’:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/file_format.hpp:66:9: warning: control reaches end of non-void function [-Wreturn-type]
         }
         ^
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_input_format.hpp:53:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/pbf_input.hpp:37,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:38,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf.hpp: In function ‘osmium::item_type osmium::osmpbf_membertype_to_item_type(OSMPBF::Relation::MemberType)’:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf.hpp:66:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/bzip2_compression.hpp:48:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_compression.hpp:36,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:36,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/compression.hpp: At global scope:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/compression.hpp:267:24: warning: ‘osmium::io::{anonymous}::registered_no_compression’ defined but not used [-Wunused-variable]
             const bool registered_no_compression = osmium::io::CompressionFactory::instance().register_compression(osmium::io::file_compression::none,
                        ^
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_compression.hpp:36:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:36,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/bzip2_compression.hpp:265:24: warning: ‘osmium::io::{anonymous}::registered_bzip2_compression’ defined but not used [-Wunused-variable]
             const bool registered_bzip2_compression = osmium::io::CompressionFactory::instance().register_compression(osmium::io::file_compression::bzip2,
                        ^
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_compression.hpp:37:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:36,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/gzip_compression.hpp:226:24: warning: ‘osmium::io::{anonymous}::registered_gzip_compression’ defined but not used [-Wunused-variable]
             const bool registered_gzip_compression = osmium::io::CompressionFactory::instance().register_compression(osmium::io::file_compression::gzip,
                        ^
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/pbf_input.hpp:37:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:38,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/pbf_input_format.hpp:227:28: warning: ‘osmium::io::detail::{anonymous}::registered_pbf_input’ defined but not used [-Wunused-variable]
                 const bool registered_pbf_input = osmium::io::detail::InputFormatFactory::instance().register_input_format(osmium::io::file_format::pbf,
                            ^
In file included from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/xml_input.hpp:37:0,
                 from /home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/any_input.hpp:39,
                 from /home/admin/source/osrm-backend-4.5.0/extractor/extractor.cpp:48:
/home/admin/source/osrm-backend-4.5.0/third_party/osmium/io/detail/xml_input_format.hpp:713:28: warning: ‘osmium::io::detail::{anonymous}::registered_xml_input’ defined but not used [-Wunused-variable]
                 const bool registered_xml_input = osmium::io::detail::InputFormatFactory::instance().register_input_format(osmium::io::file_format::xml,
                            ^
make[2]: *** [CMakeFiles/osrm-extract.dir/extractor/extractor.cpp.o] Error 1
make[1]: *** [CMakeFiles/osrm-extract.dir/all] Error 2
make: *** [all] Error 2

**Comment by TheMarex** [comment]
Are you sure you also have `g++` 4.8.0 as default compiler? What is the output of `cmake ..`?
