### ISSUE TITLE
Say "take the ramp to" rather than "continue on (unnamed)", for motorway_link

### ISSUE THREAD

**Issue by brycenesbitt** [Project-OSRM/osrm-backend#1514]
Consider the following result:

````
1. Follow Martin Luther King Jr Way	2.2km
2. Continue on Adeline Street	400m
3. Continue on Martin Luther King Jr Way	1400m
4. Continue on (unnamed)	50m
5. Continue on (unnamed)	120m
6. Continue on (unnamed)	170m
7. Continue on (unnamed)	40m
8. Continue on (unnamed)      10m
9. Continue on CA 24
````

This would benefit from two improvements: consolidating the no-branch motorway_links, and calling them a "ramp":

````
1. Follow Martin Luther King Jr Way	2.2km
2. Continue on Adeline Street	400m
3. Continue on Martin Luther King Jr Way	1400m
4. Take the ramp to CA 24	380m
5. Continue on CA 24
````

Or perhaps:

````
1. Follow Martin Luther King Jr Way	2.2km
2. Continue on Adeline Street	400m
3. Continue on Martin Luther King Jr Way	1400m
4. Take the connecting road to CA 24	380m
5. Continue on CA 24
````

Here the motorway_link was split up into bridges and additional branches of the motorway link merge into one road but don't affect the needed routing directions, except perhaps parenthetically:

````
1. Follow Martin Luther King Jr Way	2.2km
2. Continue on Adeline Street	400m
3. Continue on Martin Luther King Jr Way	1400m
4. Take the connecting road to CA 24 (two side roads will merge) 380m
5. Continue on CA 24
````

**Comment by brycenesbitt** [comment]
In particular we don't want people to add names to motorway_links, just to get them to look nicer in OSRM.

**Comment by daniel-j-h** [comment]
Could you check out our improved guidance? => http://map.project-osrm.org
By now we handle ramps, slip roads, collapse instructions and more!

**Comment by MoKob** [comment]
Closing as this is implemented in OSRM backend by now. We also have destination signs now to improve ramp handling even more.
