### ISSUE TITLE
OSRM file versioning via FingerPrint is broken due to dead code removal

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#1517]
Currently the intermediate osrm files are prefixed with a magic number (1297240911=OSRM) followed by an uuid of some file's md5sum.

The md5sum is generated by cmake [here](https://github.com/Project-OSRM/osrm-backend/blob/fd6daa580a7d3c7e2074a9c6ca1da41268274d26/cmake/FingerPrint-Config.cmake).
The concrete fingerprinting mechanism is implemented in the class [FingerPrint](https://github.com/Project-OSRM/osrm-backend/blob/fd6daa580a7d3c7e2074a9c6ca1da41268274d26/util/fingerprint.hpp) and implemented [here](
https://github.com/Project-OSRM/osrm-backend/blob/fd6daa580a7d3c7e2074a9c6ca1da41268274d26/util/fingerprint_impl.hpp.in).

Unfortunately, [the check if the magic number matches](https://github.com/Project-OSRM/osrm-backend/blob/fd6daa580a7d3c7e2074a9c6ca1da41268274d26/util/fingerprint_impl.hpp.in#L67) never returns false, **as it is removed by the optimizer as dead code**.

This is due to the fact that we're setting the magic number in the constructor and checking it later, without the compiler knowing that we "overwrite" a FingerPrint instance by memcpy-ing bytes into it. (Which, strictly speaking, is also not correct as std::is_trivial_t\<FingerPrint\> is false!).

This allows us to accidentally feed wrong paths (e.g. .pbf instead of .osrm prefix) into osrm.
This also allows us to feed JPEGs into osrm.
In all those cases an exception from the FingerPrint class is never thrown.

In addition the current process of creating the md5sum's via cmake directly in the source directory does not allow us to have multiple build directories, e.g. buildRelease and buildDebug from which to compile release and debug builds respectively.

**Comment by TheMarex** [comment]
Fixed by https://github.com/Project-OSRM/osrm-backend/pull/1538
