### ISSUE TITLE
Multiple destinations

### ISSUE THREAD

**Issue by SparrowA** [Project-OSRM/osrm-backend#1519]
I need to get information when I leave the city and some distance in a padded path occurs outside the city.

**Comment by woodbri** [comment]
I think you need to explain your problem/request in a little more detail. For example how do you define the city? is it a polygon? is it a named region? How do you differentiate between named neighborhoods, villages, and cities that might be nested? What to you mean by a padded path? What operations do you want to perform on this?

In general OSRM does not have tools, to do these type of operations. You might look at PostGIS that provides support for spatial operations between points, paths, and polygons.

**Comment by SparrowA** [comment]
I thought that there OSRM tool allows a route between the two regions, one of which is the town, and another such village and calculate the distance to be covered by the city / village and which between them.

**Comment by woodbri** [comment]
ok, yes this is partially true, the web interface geocodes your start and end locations and turns those into lat/lon values that are then given to OSRM. OSRM-backend does not handle that part of the request, it only does point to point routing in your example use case.

You might be able to do something along the lines of adding the city name to all the street segments and you could look at the driving directions and look for when the city name appended to the street name changes to get some indication of where that happens.

**Comment by SparrowA** [comment]
Oh, to develop a similar algorithm I think I can, but I was hoping that there is built-in tools allow you to do such a thing.

**Comment by TheMarex** [comment]
Sorry we don't have anything like that build in. :-)
