### ISSUE TITLE
Help with osrm-extract and Graph file (.gph) 

### ISSUE THREAD

**Issue by etorrano** [Project-OSRM/osrm-backend#1520]
I am trying to insert geometry restrictions to OSRM. First I drawed a geometry and saved it in PostgreSQL and then I put a SQL query in profile.lua in order to exclude the ways that intersected with this geometry(or set of geometries). Then I imported an OSM file in PostgreSQL in order to intersect the ways with the geometries, using IMPOSM.
The problem I had is that the ways were not divided having in count its intersections. This cause that there were segments of some ways, that they did not intersect with the geometries that were excluded too.
Then I imported the OSM file again, but this time using OSM2PO and I could see that the ways were splitted by those intersections but now the problem is that OSM2PO generates a Graph output file and I do not know how to use it with osrm-extract(because .gph is not admitted). 
I wanted to know if there is something to do with the Graph file like convert it to an OSM or PBF file or export it from PostgreSQL in order to extract it and to use it with OSRM.

**Comment by TheMarex** [comment]
I'm not sure which data `osm2po` generates, but it is defiantly not vanilla OSM and as such we are not looking to support it.
The best idea is to come up with your own translation from whatever you have stored in your database to .osm and feed that into OSRM:
