### ISSUE TITLE
Change road type with an azimut should be "turn slight [right|left]"

### ISSUE THREAD

**Issue by costales** [Project-OSRM/osrm-backend#1523]
Hi!

In the cities OSRM is working perfect, but in highways/roads the next step indicator is always "continue" and I think it should be turn slight [right|left] when it's an exit.

For example, in the attachment you can see an highway, but when you're near the exit to a national road the [JSON response](https://router.project-osrm.org/viaroute?z=16&output=json&jsonp=OSRM.JSONP.callbacks.route&loc=43.329814,-5.724542&loc=43.326114,-5.731516&instructions=true) is "1" = continue. I think it should be turn slight right.
![osrm](https://cloud.githubusercontent.com/assets/5886786/8064819/7e7dc91c-0edd-11e5-882f-fc3370fb5f11.png)

A hug and thanks for your awesome OSRM!

**Comment by TheMarex** [comment]
Thanks for flagging this. Better turn navigation is certainly on our radar.

**Comment by costales** [comment]
Great to hear that :) Thanks Patrick!

**Comment by MoKob** [comment]
By now, these exits should be discovered in most cases.

<img width="1095" alt="screen shot 2016-03-21 at 14 09 05" src="https://cloud.githubusercontent.com/assets/12932279/13919574/8eeb6274-ef6e-11e5-901c-efbe305d1d37.png">
