### ISSUE TITLE
Extract large file with 32 bits system

### ISSUE THREAD

**Issue by cocoto** [Project-OSRM/osrm-backend#1526]
I know that 32bits operating systems are not supported, but on my Linux i686 3.13.0 with gcc 4.8.2 it works very well !
I always used it for small file (sub-area, region), and encountered the following error for larger files (3GiB)
` Open failed for '[filename].pbf': Value too large for defined data type`

Adding the following line into the CMakeLists.txt after the warning bout 32bits systems solved my problem :
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FILE_OFFSET_BITS=64")`

I don't know if it's the correct manner, it's just for your information... :smile:

**Comment by TheMarex** [comment]
Thanks for the hint. Would be best if you add it to the wiki https://github.com/Project-OSRM/osrm-backend/wiki However we don't plan to officially support 32bit systems.
