### ISSUE TITLE
Turn restriction does not work!

### ISSUE THREAD

**Issue by socketpair** [Project-OSRM/osrm-backend#1528]
http://www.openrouteservice.org/?pos=60.6372720875453,56.89212036894405&zoom=17&layer=B000FTTTTTTTTTT&routeOpt=Car&avHigh=false&avToll=false&avArea=&wp=60.63425135545021,56.89077373047761,60.63426801344952,56.893014050102&lang=en&routeLang=en&distUnit=m&version=undefined&avUnpaved=false&avFerry=false&value_length=15&value_height=4&value_weight=7&value_width=4&surface=cobblestone:flattened&incline=6&slopedCurb=0.06

http://www.openstreetmap.org/node/2689922723

Turn restrictions was added long time ago.
![1](https://cloud.githubusercontent.com/assets/1157412/8129792/0e0592dc-1126-11e5-98cc-d2476bfdd168.png)

P.S.
I have removed `name=` from that point 5 minutes ago, in any case, `name=` should not affect routing.

**Comment by TheMarex** [comment]
Does it work on http://map.project-osrm.org/? I have no idea what routing engine openrouteservice uses.

**Comment by socketpair** [comment]
OOPS. reported to not-related project
