### ISSUE TITLE
Typo in routing instructions

### ISSUE THREAD

**Issue by Skippern** [Project-OSRM/osrm-backend#1533]
I noticed that routing instructions have a typo on it, when coming to an roundabout I am instructed to `takeexit 2` instead of `take exist 2`. Probably missing a space in a string file. This was seen on the routing at OSM site, I haven't had time to double check if it is only with the OSM implementation.

**Comment by TheMarex** [comment]
Since we don't generate textual instructions in the backend, but let this be handled by the client it is not a bug on our side. :-)

**Comment by Skippern** [comment]
So I should report this with OSM then? Or is it a different repo of @Project-OSRM ?

**Comment by TheMarex** [comment]
Since OSM does not use our frontend I would guess it is a bug on their side.

**Comment by Skippern** [comment]
Thanks, I will contact them and see where to file the report
