### ISSUE TITLE
Add std::is_trivial to all data that is serialized/deserialized

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1541]
To do safely serializen/deserialize structs @daniel-j-h pointed out we should use `std::is_trivial` + `static_assert`.

- [ ] Find all structs that are written to disk
- [ ] Add the mentioned checks, if they fail figure out why.

**Comment by daniel-j-h** [comment]
Subset of https://github.com/Project-OSRM/osrm-backend/issues/1685. Closing here.
