### ISSUE TITLE
table method not working

### ISSUE THREAD

**Issue by Prasanna1991** [Project-OSRM/osrm-backend#1543]
Hello community,
I am trying to get OSRM library setup for one of my application. I successfully implemented getRoute and getNearBy method but couldn't do table method. 
route_param.service="table";
route_param.output_format="json";

But, output is: {"distance_table" : [[0]]} but the same location give me good result from http request. What am I missing here?? Thanks in advance!!

**Comment by TheMarex** [comment]
Can you post the locations here and the exact code that you use to run the query?

**Comment by Prasanna1991** [comment]
route_param.coordinates.emplace_back(locations[i].lat , locations[i].lan);

where in location I put: 
Location dest = new Location();
            dest.setLat(27.684449600000000000);
            dest.setLan(85.305866400000010000);
            Location dest1 = new Location();
            dest1.setLat(27.716779800000000000);
            dest1.setLan(85.353673500000010000);

But this give me result if I query from http. And thanks for such quick response.

**Comment by chaupow** [comment]
Can you give us the whole source code? That might help us understand what the problem is.

(Btw, you can format your code by using three ``` as brackets so that the code looks like this:)

```
Location dest = new Location();
```

**Comment by daniel-j-h** [comment]
libosrm and node-osrm examples:

https://github.com/Project-OSRM/osrm-backend/blob/master/example/example.cpp
https://github.com/Project-OSRM/node-osrm/blob/master/example/server.js

Without more details this is not actionable for us.
