### ISSUE TITLE
KM Calculation problem with viaroute

### ISSUE THREAD

**Issue by mickdane** [Project-OSRM/osrm-backend#1544]
We have a bounce of positions that we use in a TRIP - We then need to calculate the distance for the complet trip.

Odometer in car say: 4,9 km and google about the same.
but we use http://homepage.com:5000/viaroute?instructions=false&alt=false&loc=55.679665,12.504361&loc=55.679665,12.504361&loc=55.678654,12.503779&loc=55.678371,12.496132&loc=55.677097,12.487261&loc=55.674587,12.484329&loc=55.672878,12.482371&loc=55.67271,12.483616&loc=55.672543,12.487333&loc=55.672493,12.489372&loc=55.672356,12.496887&loc=55.67231,12.503569&loc=55.672295,12.5042&loc=55.672153,12.506609&loc=55.677589,12.508578&loc=55.68129,12.510552&loc=55.681847,12.509563&loc=55.682129,12.50571&loc=55.682072,12.503895 ("&uturns=true" did test this too)

We have tried to do a locate on all positions, but we still end up with a  : 7,8KM

What are we doing wrong
Michael

**Comment by TheMarex** [comment]
The coordinates are snapped to the wrong ways, probably because the data in OSM is not aligned with whatever you use as source.

http://map.project-osrm.org/?hl=en&loc=55.679665,12.504361&loc=55.679665,12.504361&loc=55.678654,12.503779&loc=55.678413,12.497377&loc=55.677097,12.487261&loc=55.674679,12.484346&loc=55.672920,12.482437&loc=55.672604,12.483575&loc=55.672543,12.487333&loc=55.672497,12.489143&loc=55.672356,12.496887&loc=55.672245,12.503205&loc=55.672215,12.504137&loc=55.672157,12.506492&loc=55.677589,12.508578&loc=55.681297,12.510675&loc=55.681904,12.509533&loc=55.682129,12.505710&loc=55.682072,12.503895&z=15&center=55.675806,12.497849&alt=0&df=0&re=0&ly=-1171809665

**Comment by mickdane** [comment]
hi TheMarex
I am not sure I understand what you mean about "The coordinates are snapped to the wrong ways"
We get the Lan, Lat from a GPS unit - and we have installed the Denmark map as a test.

**Comment by danpat** [comment]
@mickdane - what he means is that the via-points you've supplied are not on the road you think they are.  The link that @TheMarex gave had all the points very slightly adjusted.

Here's your original route on map.project-osm.org:

http://map.project-osrm.org/?hl=en&loc=55.679665,12.504361&loc=55.679665,12.504361&loc=55.678654,12.503779&loc=55.678371,12.496132&loc=55.677097,12.487261&loc=55.674587,12.484329&loc=55.672878,12.482371&loc=55.67271,12.483616&loc=55.672543,12.487333&loc=55.672493,12.489372&loc=55.672356,12.496887&loc=55.67231,12.503569&loc=55.672295,12.5042&loc=55.672153,12.506609&loc=55.677589,12.508578&loc=55.68129,12.510552&loc=55.681847,12.509563&loc=55.682129,12.50571&loc=55.682072,12.503895&z=15&center=55.675806,12.497849&alt=0&df=0&re=0&ly=-1171809665

For the `viaroute` function, OSRM matches the *nearest way*.  If the GPS points are not perfectly accurate, then you may end up on the wrong side of the road.  In your example, there are some divided roads, so if the GPS point is closer to that side, the route will need to find a place to do a u-turn to loop back on the one-way segment.  Good example here:

![screen shot 2015-06-23 at 10 46 59 am](https://cloud.githubusercontent.com/assets/1892250/8313083/66d73fb0-1995-11e5-866a-65b9d65b919e.png)

Note that points 11 & 12 are on the one-way street going back (so a route had to be found to get there), and point 13 is slightly past the intersection on a one-way road, requiring the out-and-back loop.

What can you do about this?  Glad you asked.  OSRM has a "matching" feature, which when given a sequence of coordinates, tries to figure out the mostly likely correct path.  This can correct things like GPS points on the wrong side of a divided highway, etc.

Take a look at:

https://github.com/Project-OSRM/osrm-backend/wiki/Server-api

look for the `match` service.  Try running your GPS points through that (to get "corrected" points), and then re-execute your `viaroute` with the corrected coordinates.

**Comment by mickdane** [comment]
Ahh Great I was actually looking at MATCH and locate right now Will try it
Many Thanx

**Comment by mickdane** [comment]
Thanx to all - It worked 100%
