### ISSUE TITLE
Loop between intermediate points

### ISSUE THREAD

**Issue by etorrano** [Project-OSRM/osrm-backend#1546]
I wrote the same issue in bug #1424  that seems to be fixed, but in the following case, that appeared as an example of an U-turn problem, now appears a loop instead of the U-turn :

![30b85f12-0096-11e5-912e-80be204d6e40](https://cloud.githubusercontent.com/assets/9082428/8060539/586a4ea8-0e9c-11e5-9458-ef58cdbbd4b8.PNG)

http://osrm.at/cQt

![ruteos0](https://cloud.githubusercontent.com/assets/9082428/8062206/e1661342-0ea4-11e5-8cfb-c6472ebec3ce.png)

When I put an intermediate point in order to get a better route I get this:

http://osrm.at/cQu

![ruteos1](https://cloud.githubusercontent.com/assets/9082428/8062207/e188470a-0ea4-11e5-9572-17ed778e59f9.png)

I think this is the right route.

**Comment by Andygol** [comment]
@TheMarex 
May there is the same issue like reported above. I found it in ukrainian branch of the [forum.osm.org](http://forum.openstreetmap.org/viewtopic.php?pid=562312#p562312)

All depends on the angle of the line, if the angle is obtuse, the route goes around the circle, and if the angle is acute - all right

**obtuse angle**
![open source routing machine demo 2015-11-20 16-50-07](https://cloud.githubusercontent.com/assets/369696/11302678/748daa44-8fa7-11e5-8ca6-b70ced302d93.png)

**sharp angle**
![open source routing machine demo 2015-11-20 16-57-28](https://cloud.githubusercontent.com/assets/369696/11302779/fcebe126-8fa7-11e5-9284-54f9d10f98d9.png)



![osrm-weird-behavior](https://cloud.githubusercontent.com/assets/369696/11302144/49f21da4-8fa4-11e5-8cd4-f2a1c123c29f.gif)
http://map.project-osrm.org/?z=18&center=50.402454%2C30.485365&loc=50.403225%2C30.485097&loc=50.401926%2C30.486749&loc=50.401744%2C30.483579&hl=en&ly=&alt=&df=&srv=

**Comment by TheMarex** [comment]
Fixed on the demo server.

**Comment by etorrano** [comment]
I tested the bug through the links used above, in order to detect it, and it is all ok, thanks for the fix!
