### ISSUE TITLE
osrm-backend: one lane penalty / car profile 

### ISSUE THREAD

**Issue by flohoff** [Project-OSRM/osrm-backend#1548]
This commit added a one lane speed penalty. This should not happen on oneways as there is no two-way traffic causing a penalty. This would effect motorway ramps for example.

commit 86df55f5cca89baf1bfbbe52918828124fd43b7b
Author: Patrick Niklaus <patrick.niklaus@student.kit.edu>
Date:   Thu Jun 18 17:31:49 2015 +0200

     Add penalty if there is only one lane for both directions

**Comment by TheMarex** [comment]
Fixed.
