### ISSUE TITLE
Lua Profile to prevent multiple map matchings

### ISSUE THREAD

**Issue by BharathMG** [Project-OSRM/osrm-backend#1550]
Hi guys,

Can I modify  a profile.lua (bicyle, car) to always get a single map matching from a set of points in OSRM? I've been tweaking bicycle.lua to prevent multiple map matchings. But still I'm not able to script a solid one to always get a single map matching from a set of points. These are user ridden GPX files. So I must be able to get a single map matching if my profile.lua allows it right? 

Thanks,
Bharath

**Comment by TheMarex** [comment]
I'm not sure what you are trying to say. Do you mean you get multiple sub-matching back for a given input trace? This is to be expected, if the trace has a lot of noise. You can try to clean it up using https://github.com/mapbox/geojson-tidy first.
