### ISSUE TITLE
OSRM prefers hairpin turn via trunk_link instead of staying on trunk

### ISSUE THREAD

**Issue by lordsutch** [Project-OSRM/osrm-backend#1551]
There's something odd going on in this short route:

http://osrm.at/ddl

Instead of staying on the trunk road, the algorithm routes via an off ramp and back on, with an intervening 180-degree turn. Looking at the time reported, it apparently thinks this will take 2 seconds less than staying on the trunk despite being 300m longer.

Oddly enough there are several similar intersections along this highway, but this is the only one where OSRM routes you via a ramp.

**Comment by emiltin** [comment]
weird

**Comment by lbud** [comment]
Hey @lordsutch, it looks like you made some data edits that I assume fixed this after they cycled — I'm no longer able to reproduce this issue. Can you confirm?

**Comment by lordsutch** [comment]
Yep, it appears that whatever edits I made fixed/masked the issue.
