### ISSUE TITLE
segmentation fault while preparing

### ISSUE THREAD

**Issue by christol2** [Project-OSRM/osrm-backend#1552]
While running osrm-prepare I get a core dump.  

Running in debug gives me the following

/osrm/osrm7/BIKING$ osrm-prepare full.osrm   -p /home/ubuntu/osm-tools/osrm/profiles/bicycle.lua
[info] Input file: full.osrm
[info] Restrictions file: full.osrm.restrictions
[info] Profile: bicycle.lua
[info] Threads: 16
[debug] traffic_signal_penalty: 50
[info] Importing n = 383735439 nodes 
[info]  and 419012844 edges 
[info] Graph loaded ok and has 418560253 edges
[info] 0 restrictions, 188357 bollard nodes, 399407 traffic lights
[info] Generating edge-expanded graph representation
[info] merged 0 edges out of 806319922
[info] Removing graph geometry while preserving topology
osrm-prepare: /home/ubuntu/osm-tools/osrm/contractor/edge_based_graph_factory.cpp:382: void EdgeBasedGraphFactory::CompressGeometry(): Assertion `m_node_based_graph->GetEdgeData(forward_e1).nameID == m_node_based_graph->GetEdgeData(reverse_e1).nameID' failed.
Aborted (core dumped)

full.osrm was created by downloading about 50 pbf maps from geofabrik; converting them to .o5m; merging them with osm-convert and converting the result to pbf again. osrm-extract run without error.

Using the car and foot profile works fine.

This is on version 4.6.1

Any suggestions on how to solve this?

Thx!

**Comment by TheMarex** [comment]
Can you try 4.7.0?

**Comment by emiltin** [comment]
383735439 nodes is a lot. what size is the input file?

**Comment by christol2** [comment]
I’m currently re-running with 4.7.0.
It will take some time since the previous version cracked after 6 hours of processing

Thx

**Comment by christol2** [comment]
The pbf where I started from is about 15GB. It’s a merge of about 50 countries/states downloaded from geofabrik
The osrm-extract ran fine. osrm file is also about 15GB

The machine has 128GB of mem, 16 cores and 100GB swap.

**Comment by christol2** [comment]
The osrm-prepare has been running for over 30 hours on 4.7.0 with cpu usage maxed out. Last output message received is:

'initializing elimination PQ' 

which was over 20 hours ago.

Nothing has been written to disk since

Would starting from a planet file instead of my own merge of the countries/states needed work better?

Thx!

**Comment by chewmag** [comment]
I have the same problem on 4.7.1 with Russia's map from here - http://gis-lab.info/projects/osm_dump/.

[asko@Centos-31 4.7.1-test]# ./osrm-prepare RU.osrm -p profile.lua
[info] Input file: RU.osrm
[info] Restrictions file: RU.osrm.restrictions
[info] Profile: profile.lua
[info] Threads: 2
[info] Generating edge-expanded graph representation
[info]  - 37250 restrictions.
[info] Importing n = 18594256 nodes
[info]  - 16140 bollard nodes, 27727 traffic lights
[info]  and 19828794 edges
[info] Graph loaded ok and has 19828794 edges
[info] Removing graph geometry while preserving topology
Segmentation fault

**Comment by servok** [comment]
I have too this problem with RU.osrm file.

osrm-prepare compiled without debug printing
[info] Removing graph geometry while preserving topology
Segmentation fault

with debug
/osrm-backend/algorithms/graph_compressor.cpp:86: void GraphCompressor::Compress(const std::unordered_set<unsigned int>&, const std::unordered_set<unsigned int>&, RestrictionMap&, NodeBasedDynamicGraph&, CompressedEdgeContainer&): Assertion `SPECIAL_EDGEID != forward_e1' failed.

**Comment by servok** [comment]
I have this problem with RU.osrm file too.

osrm-prepare compiled without debug prints:
[info] Removing graph geometry while preserving topology
Segmentation fault

with debug:
[info] Graph loaded ok and has 19834077 edges
[warn] Could not find reverse edge
osrm-prepare: /home/silyin/osrm/osrm-backend/contractor/../data_structures/node_based_graph.hpp:229: std::shared_ptr<DynamicGraph<NodeBasedEdgeData> > NodeBasedDynamicGraphFromImportEdges(int, std::vector<NodeBasedEdge>&): Assertion `validateNodeBasedGraph(*graph)' failed.

**Comment by servok** [comment]
I have this problem with RU.osrm file too.

osrm-prepare compiled without debug prints:
[info] Removing graph geometry while preserving topology
Segmentation fault

with debug:
[info] Graph loaded ok and has 19834077 edges
[warn] Could not find reverse edge
osrm-prepare: /home/xxx/osrm/osrm-backend/contractor/edge_based_graph_factory.cpp:332: void EdgeBasedGraphFactory::CompressGeometry(): Assertion `SPECIAL_EDGEID != forward_e1' failed.

**Comment by marcioaguiar** [comment]
I have the same problem in a small extract from brazil (only 86mb). 
Download link: http://www.filedropper.com/alhighways

OSRM Version: 4.7.1

[info] Input file: al-highways.osrm
[info] Restrictions file: al-highways.osrm.restrictions
[info] Profile: profile.lua
[info] Threads: 2
[info] Generating edge-expanded graph representation
[info]  - 0 restrictions.
[info] Importing n = 337895 nodes 
[info]  - 1 bollard nodes, 182 traffic lights
[info]  and 368266 edges 
[info] Graph loaded ok and has 368266 edges
[info] Removing graph geometry while preserving topology
Segmentation fault

Ubuntu version
============================
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by TheMarex** [comment]
@marcioaguiar can you please try the current version from the `develop` branch? Thanks!

Could be related to invalid node references due to broken clipping algorithms in most extract tools.

**Comment by TheMarex** [comment]
Just ran this, there are indeed a lot of missing nodes, but it should not segfault because of that. Investigating.

**Comment by marcioaguiar** [comment]
@TheMarex almost the same; just got a segmentation fault earlier now

[info] Input file: al-highways.osrm
[info] Restrictions file: al-highways.osrm.restrictions
[info] Profile: profile.lua
[info] Threads: 4
[info] Generating edge-expanded graph representation
[info]  - 0 restrictions.
[info] Importing n = 337895 nodes 
[info]  - 1 bollard nodes, 182 traffic lights
[info]  and 368266 edges 
[info] Graph loaded ok and has 368266 edges
Segmentation fault

**Comment by olamedia** [comment]
same, tried master and v4.7.1 (RU.osrm, gis-lab.info)

**Comment by TheMarex** [comment]
This should be fixed now in `develop`.

**Comment by marcioaguiar** [comment]
Tested and it works. Thanks!!

**Comment by olamedia** [comment]
Didn't worked 
`# ./osrm-prepare ./RU.osrm  `
`[info] Input file: RU.osrm`
`[info] Restrictions file: RU.osrm.restrictions`
`[info] Profile: profile.lua`
`[info] Threads: 8`
`[info] Generating edge-expanded graph representation`
`[info]  - 38235 restrictions.`
`[info] Importing n = 18672258 nodes `
`[info]  - 16358 bollard nodes, 27813 traffic lights`
`[info]  and 19911746 edges `
`[info] Graph loaded ok and has 19911746 edges`
`[info] Removing graph geometry while preserving topology`
`Segmentation fault`
