### ISSUE TITLE
osrm-extract hangs in current git master 

### ISSUE THREAD

**Issue by flohoff** [Project-OSRM/osrm-backend#1553]
The commit:

commit 2777d53a12ca6753880f1dc025d8a7cc34377bcb
Author: Patrick Niklaus <patrick.niklaus@student.kit.edu>
Date:   Sun May 24 17:25:38 2015 +0200

    Direct edges in contractor correctly and add better graph validation.

introduced a possibility to let osrm-extract hang - which it does for me on all input files:

```c++
[...]
@@ -303,13 +308,18 @@ void ExtractionContainers::PrepareEdges()
     std::cout << "ok, after " << TIMER_SEC(sort_edges_by_renumbered_start) << "s" << std::endl;

     BOOST_ASSERT(all_edges_list.size() > 0);
-    for (unsigned i = 1; i < all_edges_list.size();)
+    for (unsigned i = 0; i < all_edges_list.size();)
     {
         // only invalid edges left
         if (all_edges_list[i].result.source == SPECIAL_NODEID)
         {
             break;
         }
+        // skip invalid edges
+        if (all_edges_list[i].result.target == SPECIAL_NODEID)
+        {
+            continue;
+        }
```
This chunk made it possible that we continue on a for loop which does not increment the edge count i.

Flo

**Comment by TheMarex** [comment]
Good catch. Fixed f19c57200da0f9c79cdda5c2bab274df09be79ac.
