### ISSUE TITLE
Foot: Ignore access=agricultural tag

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#1555]
Currently `access=agricultural` and `access=forestry` are on the blacklist for the [foot profile](https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/foot.lua#L8). 

These do not make sense for pedestrian routing and should probably be dropped from the blacklist. It looks like it was copied over from the car profile.

**Comment by lonvia** [comment]
OSRM is correct here, in most cases the tagging is wrong. `access=agricultural` refers to all means of transport including pedestrians. What is generally actually meant is `vehicle=agricultural/forestry` (no bikes either) or `motor_vehicle=agricultural/forestry` (bicycles allowed).

**Comment by planemad** [comment]
@lonvia aha thanks. There really should be a much better description of tags for the average mapper. After 8 years i'm still confused :monkey:
