### ISSUE TITLE
TarjanSCC in EdgeBasedGraphFactory finds weakly connected components

### ISSUE THREAD

**Issue by icokk** [Project-OSRM/osrm-backend#1556]
The NodeBasedDynamicGraph in EdgeBasedGraphFactory::GenerateEdgeExpandedNodes is constructed in such a way that it contains the reverse directions of all one-way roads (they are the edges with edgeBasedNodeID=-1 and have forward=false in EdgeData). Since TarjanSCC doesn't check whether the edge can be traversed in the forward direction, it works effectively on an undirected graph and finds only weakly connected components. Routing then gets stuck on small strongly connected components, which aren't ignored when creating phantom nodes as they should be.

The other application of TarjanSCC, in components.cpp, correctly constructs a StaticGraph by adding just one direction for one-way roads.

**Comment by TheMarex** [comment]
@icokk good catch. It has more issues than that see for example here https://github.com/Project-OSRM/osrm-backend/pull/1493

**Comment by TheMarex** [comment]
Should be resolved not that we moved to computing the SCC on the edge expanded graph.
