### ISSUE TITLE
Respect access=destination

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/osrm-backend#156]
Feature request: Don't route through streets with access=destination tag set, if start and/or target do not lie on them.

**Comment by derTobsch** [comment]
This Feature would be great! :+1: We used a version which pa5cal made for as at synyx with the fix in it. But i would be very good if this would be a real feature in osrm :)

**Comment by frodrigo** [comment]
The hack is still available somewhere ?

**Comment by pa5cal** [comment]
@frodrigo the hack was to modify the mentioned EdgeBasedGraphFactory.cpp in line 316-317 with:
```
if(!edgeData1.isAccessRestricted  &&  edgeData2.isAccessRestricted)  { 
    distance += 10*1200;  
}
```

**Comment by marcioaguiar** [comment]
Hi, @DennisOSRM 

Can we document the special cases so we can come up with a proper solution?

Thanks!

**Comment by danpat** [comment]
@marcioaguiar The proper solution is to implement https://github.com/Project-OSRM/osrm-backend/issues/77, which would allows us to put arbitrary penalties on `access=destination` without modifying ETA values.  There are a bunch of other related use cases that this feature will be helpful for.

**Comment by marcioaguiar** [comment]
Great! Thanks for the feedback, @danpat

**Comment by derTobsch** [comment]
Now in version 5.1.0 ? :-/ It feels like this is one of the most missing feature...maybe we can support you to get this done faster?

**Comment by danpat** [comment]
@derTobsch A patch that implements #77 would make this possible :smile:

**Comment by emiltin** [comment]
would you accept such a patch? it will increase ram usage

**Comment by danpat** [comment]
@emiltin Maybe someone will come up with a clever way to do it that doesn't use extra memory :-)

But seriously, if someone writes the patch, we can certainly make it a compile-time option, so it has no effect unless it's enabled.

**Comment by yuryleb** [comment]
Still [routing](http://map.project-osrm.org/?z=17&center=59.969201%2C30.313787&loc=59.969452%2C30.313989&loc=59.970060%2C30.309218&hl=en&alt=0) through [vehicle=destination](https://www.openstreetmap.org/way/172747175) :worried:
![osrm routes through vehicle destination](https://cloud.githubusercontent.com/assets/4529411/22245349/e7e68cdc-e248-11e6-8f10-1ca9e438706e.png)

**Comment by daniel-j-h** [comment]
Yes, OSRM does not respect the destination access _in the default profiles and on the demo server_ see

https://github.com/Project-OSRM/osrm-backend/blob/e0a1a4344900b3bf25bca0f10418350720cf7bdf/profiles/car.lua#L32

You're free to adapt the profile and run your own server if you want to avoid routing over it.

Check out [this pull request](https://github.com/Project-OSRM/osrm-backend/pull/3276) for how we will handle it in _the future_.

**Comment by danpat** [comment]
Now that #77 is closed, we can finally tackle this.

We can now update the `car.lua`.  As an initial hit-list, I suggest:

  - allow snapping to currently removed roads (`access=hov`), but discourage routing *though*
  - penalize routing through alleys (`highway=living_street`)
  - penalize routing through service roads (`highway=service`)
  - allow routing onto `access=destination` roads

Ideally these would be implemented as penalties on turns accessing these types of ways, but our `turn_function` does not yet have the metadata required.

We can, however, add weight to these road types, which will have a similar effect (it may fall down in some circumstances when weights are high and coordinates are dropped near edges of weighted areas).

I'd like to include this with 5.6.0 as the major rollout feature.

**Comment by emiltin** [comment]
hope you get a chance to consider mergin #3615 (factoring out common profile code to helper file) before working on using the weights to avoid access=destination.
