### ISSUE TITLE
Traffic signals ignored when extracting and/or preparing

### ISSUE THREAD

**Issue by kaligrafy** [Project-OSRM/osrm-backend#1563]
I updated my osm files for the Quebec province and i get a strange result now when preparing the osrm file:

[info] Importing n = 3481424 nodes 
[info]  - 447 bollard nodes, 0 traffic lights

There are no traffic lights included. I checked and the osm map for Quebec includes a lot of traffic lights (I did added a lot myself).
Since my foot profile uses penalties for traffic light, the results are ignoring penalties because it seems the extractor ignores them. Anybody knows why?

**Comment by TheMarex** [comment]
Which profile are you using?

**Comment by kaligrafy** [comment]
foot

**Comment by kaligrafy** [comment]
there seem to be a missing **s** at "result.traffic_signal = true" at the end of line 88 in the foot.lua profile:
car profile works well and at line 209, result.traffic_light**s** = true

**Comment by kaligrafy** [comment]
that was the problem! Could you fix it in the foot.lua profile? Thanks!

**Comment by TheMarex** [comment]
@kaligrafy wow good catch. Fixed in 486d7b6.

**Comment by kaligrafy** [comment]
Thanks very much. I checked bicycle.lua and it is correct there already.
