### ISSUE TITLE
Error when extracting osm.pbf file

### ISSUE THREAD

**Issue by pete363** [Project-OSRM/osrm-backend#1566]
Hi,
Specs: 
Ubuntu 14.04.2 LTS
6GB RAM
340GB DiskSpace

I am install the great-britain file from
http://download.geofabrik.de/europe/great-britain-latest.osm.pbf
usng the command 
wget -O gb.osm http://download.geofabrik.de/europe/great-britain-latest.osm.pbf
and get the following error on osrm-extract

osrm@osrm:~/osrm$ osrm-extract gb.osm
[info] Input file: gb.osm
[info] Profile: profile.lua
[info] Threads: 4
[info] Using script profile.lua
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-MSG] 1 disks are allocated, total space: 100000 MiB
[info] Parsing in progress..
[info] input file generated by unknown tool
[info] timestamp: n/a
[info] Using turn restrictions
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
**[warn] XML parsing error at line 1, column 0: not well-formed (invalid token)**
osrm@osrm:~/osrm$

and the it stops execution.

Surpirsingly when I tried the **England** file
 (http://download.geofabrik.de/europe/great-britain/england-latest.osm.pbf)
and it did extract properly and working with no errors. 
Can you please comment what could be possible issue.
Thanks
Pete

**Comment by deatwisedog** [comment]
Hello! You extract gb.osm or gb.osm.pbf? Maybe you saved map with wrong
extension?
10 июля 2015 г. 15:30 пользователь "pete363" <notifications@github.com>
написал:

**Comment by pete363** [comment]
Hi deatwisedog,
**Solved**. ::smile::Thanks for pointing out. the wget command was outputting to gb.osm but aparently this was not working. When i ran the wget command without givining output filename as below. It worked perfectly.

 wget -O http://download.geofabrik.de/europe/great-britain-latest.osm.pbf

Thanks a lot. I lost a week fighting with this.
Cheers
pete363
