### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by Cosmotan** [Project-OSRM/osrm-backend#1568]
Can some please compile osrm for windows and update the binaries here : http://build.project-osrm.org/ they are pretty outdated.
Or maybe someone who has already build it can upload it somewhere and make it available for download please ?

Thx

**Comment by BergWerkGIS** [comment]
@Cosmotan sure, will do.

**Comment by BergWerkGIS** [comment]
@Cosmotan 

The `release` build should be available as soon as this AppVeyor build finishes:
https://ci.appveyor.com/project/DennisOSRM/osrm-backend/build/1.0.956

For the time being, support files are available here:
https://mapbox.s3.amazonaws.com/windows-builds/windows-deps/osrm-deps-win-x64-14.0.7z

-------

**Caution**

1.
We had to switch to `VS2015 RC` as the `CTP Nov2013` wasn't able to compile the recent versions anymore.
To use the new binaries, you will need that, too.

2.
The final release of VS2015 by Microsoft is scheduled in one week, July 20th.
We plan to upgrade to that probably within about two or three weeks after release.

**Comment by Cosmotan** [comment]
BergWerkGIS, many thanks man, i really appreciate it. Can you update the win bin's in the future regulary from time to time ?

Thanks again

**Comment by BergWerkGIS** [comment]
@Cosmotan sure, from now on the binaries should be updated automatically every time something gets pushed to `develop` branch.

**Comment by bblu** [comment]
the package "windows-deps/osrm-deps-win-x64-14.0.7z" on amazonaws cannot access for me,<Error>
<Code>AccessDenied</Code></Error>! is there any other place that i can find the package ?
btw: where to find the build_base.bat or build_other.bat etc such bat files on the windows compliation wiki page?

**Comment by BergWerkGIS** [comment]
@bblu try this: https://mapbox.s3.amazonaws.com/windows-builds/windows-build-deps/osrm-deps-win-x64-14.0.7z

------

To just build `orsrm-backend` (pulls down the deps package in the background) you need:

* Visual Studio 2015 installed at the default location
* a recent cmake
* 7-zip

then 

```
git clone -b develop https://github.com/Project-OSRM/osrm-backend osrm-backend
```

change these paths https://github.com/Project-OSRM/osrm-backend/blob/69bc8a8b2214da798ffd39f6ebd98d82a1bf5103/build-local.bat#L14-L15

```
cd osrm-backend
build-local
```

------


To completely build it yourself (including deps) you need:

* Visual Studio 2015 installed at the default location
* a recent git 64bit installed at the default location

then 

```
git clone https://github.com/mapbox/windows-builds.git
cd windows-builds
settings
scripts\scripts\build_osrm.bat builddeps
```

Will create a 7z of the deps and osrm itself in the `windows-builds\bin` directory.

**Comment by bblu** [comment]
across the GFW, thanks a lot !
