### ISSUE TITLE
Upgrade to VS2015

### ISSUE THREAD

**Issue by BergWerkGIS** [Project-OSRM/osrm-backend#1569]
Release of final VS2015 is scheduled for July 20th.

* [x] Upgrade support files (`osrm_deps`)
* [x] Upgrade osrm-backend build, **availability on AppVeyor?**
* [ ] activate debug build again (or just `release` with debug symbols?)

**EDIT** continuing with `release`-only, as https://github.com/mapbox/windows-builds (used to create the binary dependencies package) is `release`-only (but with debug symbols).

**Comment by daniel-j-h** [comment]
Ping @BergWerkGIS. What came out of this?

**Comment by BergWerkGIS** [comment]
Done:
https://github.com/Project-OSRM/osrm-backend/blob/develop/appveyor.yml#L10
