### ISSUE TITLE
c-api?

### ISSUE THREAD

**Issue by tdihp** [Project-OSRM/osrm-backend#1570]
hi.

I think a c-api would be very nice, especially to make language bindings for osrm.

I've tried to write one [myself](https://github.com/tdihp/osrm-c), but I really think it's better to have something similar in osrm-backend directly.

**Comment by TheMarex** [comment]
At the moment we are not looking into supporting more than one official language binding. While I see your point in wrapping it in C, it just doesn't make sense for us to maintain that.

I guess you are looking into building a python wrapper?

**Comment by tdihp** [comment]
@TheMarex:

> I guess you are looking into building a python wrapper?

I have made a Python wrapper for my own use. It's working and OSRM is stunningly fast :-D.

But my point is, at the moment, it's hard to make bindings,
even with the `libOSRM.a`, and it's true for node-osrm too.
Writing cpp code is not particularly hard, but building the extension is.
specifically, as stated in [node-osrm](https://github.com/Project-OSRM/node-osrm#source-build),
to build such a binding, it's better to build osrm-backend in the same environment first.
and it's hard to just use a binary-release of OSRM and link against it.

Here's why
(I'm not that good at c++ template programming, please point out if I'm wrong):

`include/osrm/*.h` has dependency to external template libraries:
`mapbox/variant`, `boost/filesystem`, `boost/spirit`, and it's for the better to
assume that:

- things to compile against `libOSRM` should include the exact version of those headers
- things to compile against `libOSRM` should use the same compiler,
  with the same configuration (c++11),
  to make sure having consistent symbol as in `libOSRM.a`.

It will possibly get worse in windows (since you support that)
where most users will probably opt to download a binary release.

With an intentionally made, simple c interface, provided by the binary release as a library,
the only dependency to link against libOSRM will be libOSRM itself, user can use
any compiler, use any boost version of his/her choice.

That's why I think it's better to have a c wrapper maintained in OSRM.

**Comment by daniel-j-h** [comment]
For the record: your https://github.com/tdihp/osrm-c is great and I often point people there.

Supporting a C API natively is not on the todo list for the near future, but we might re-evaluate this when we're done with our larger cleanup effort going on right now.
