### ISSUE TITLE
Ignored access limits

### ISSUE THREAD

**Issue by osm-maps** [Project-OSRM/osrm-backend#1571]
OSRM routes (cars) over roads with the following tags:
traffic_sign=DE:250,DE:1026-38
vehicle=agricultural;forestry

These roads should be restricted for all vehicles (even bicycles), except for agricultural and forestry vehicles.

**Comment by lordsutch** [comment]
This is correct behavior unless access=no is also tagged.

**Comment by osm-maps** [comment]
Thanks for you reply.
I discussed this issue on the German OSM forum (http://forum.openstreetmap.org/viewtopic.php?id=31939). Most of the mappers think, that the tags, mentioned above, are correct.

**Comment by lonvia** [comment]
It's the semicolon that confuses OSRM. Choose vehicle=forestry or vehicle=agricultural and all will be well.

**Comment by osm-maps** [comment]
I see! Not quit correct, with regards to the traffic sign but a possible solution.
Any chance that OSRM will handle the semicolon in the future?
