### ISSUE TITLE
How to know max speed of current road?

### ISSUE THREAD

**Issue by costales** [Project-OSRM/osrm-backend#1572]
Hi!

I'm getting [this data](https://router.project-osrm.org/viaroute?z=15&output=json&jsonp=OSRM.JSONP.callbacks.route&checksum=2251055677&loc=43.523721,-5.663624&loc=43.305687,-5.693609&hint=G615Bf____8AAAAAAAAAAAkAAAAYAAAABwAAADJAcQQAAAAA1sqUAlcfqf8DABEA&instructions=true) from the API (for example, instruction step 7):
1095 meters & 40 secs. Then, 1095/40 = 27,375 m/s = 97.2 km/h
In the real road it's 100km/h.

Is there another **way to get an exactly max. speed for the current road?**

Thanks a lot in advance!

**Comment by TheMarex** [comment]
@costales we use a multiplier on the `maxspeed` to get saner average travel times for roads. You can modify the car profile and setup your on osrm instance to achieve that by removing the penalty.

**Comment by costales** [comment]
@TheMarex Thanks for the info :)
I suppose there isn't a way to *un*calculate the multiplier and get from the API  the road speed.
A big hug and thanks a lot for your support!

**Comment by emiltin** [comment]
As a hack, you can encode whatever info you need into the way name and extract it in the front-end. Example: 'Big Boulevard {"maxspeed"=60,"surface"="asphalt"}'. It will increase the size of the name file, of course. See #1342.
