### ISSUE TITLE
Profile postgis.lua out-of-date?

### ISSUE THREAD

**Issue by sebastian-fu** [Project-OSRM/osrm-backend#1573]
Hello there,

I just wanted to try using the postgis.lua profile.

However, it appears to me that the profile did not undergo changes which the other profiles did and is now not usable with the current code status. For example the change from "local highway = way.tags:Find("highway")" to "local highway = way:get_value_by_key("highway")". I edited this myself and the former error disappeared. Currently, I am struggling with the concatenated ID in the SQL statement. It says for me that the concatenation is invalid because it is a function value. 

Best

Sebastian

**Comment by TheMarex** [comment]
Thanks for flagging this. Will be fixed in the next release.

**Comment by sebastian-fu** [comment]
I edited the file (attached). The result is now that the extraction seems to be successful. However, in the following preparation step I encounter the error "[warn] [exception] osrm input file misses magic number. Check or reprocess the file". How could that be related?

-- Open PostGIS connection
lua_sql = require "luasql.postgres"           -- we will connect to a postgresql database
sql_env = assert( lua_sql.postgres() )
sql_con = assert( sql_env:connect("osm") ) -- you can add db user/password here if needed
print("PostGIS connection opened")

-- these settings are read directly by osrm
take_minimum_of_speeds   = true
obey_oneway             = true
obey_bollards           = true
use_restrictions         = true
ignore_areas             = true  -- future feature
traffic_signal_penalty   = 7      -- seconds
u_turn_penalty           = 20

-- nodes processing, called from OSRM
function node_function(node)
  return 1
end

-- ways processing, called from OSRM
function way_function (way, result)
  -- only route on ways with highway=*
  local highway = way:get_value_by_key("highway")
  if (not highway or highway=='') then
    return 0
  end

  -- Query PostGIS for industrial areas close to the way, then group by way and sum the areas.
  -- We take the square root of the area to get a estimate of the length of the side of the area, 
  -- and thus a rough guess of how far we might be travelling along the area. 

  local sql_query = " " ..
    "SELECT SUM(SQRT(area.area)) AS val " ..
    "FROM osm_roads way " ..
    "LEFT JOIN osm_landusages area ON ST_DWithin(way.geometry, area.geometry, 100) " ..
    "WHERE area.type IN ('industrial') AND way.osm_id=" .. way:id() .. " " ..
    "GROUP BY way.id"

  local cursor = assert( sql_con:execute(sql_query) )   -- execute querty
  local row = cursor:fetch( {}, "a" )                   -- fetch first (and only) row
  result.forward_speed = 20.0                                      -- default speed
  if row then
    local val = tonumber(row.val)                       -- read 'val' from row 
    if val > 10 then
      result.forward_speed = result.forward_speed / math.log10( val )         -- reduce speed by amount of industry close by 
    end
  end
  cursor:close()                                        -- done with this query

  -- set other required info for this way
  result.name = way:get_value_by_key("name")
  result.direction = way:get_value_by_key("direction") 
  result.type = 1
  return 1
end

**Comment by TheMarex** [comment]
Can you post the full command that you use to run `osrm-extract` and `osrm-prepare`?

**Comment by sebastian-fu** [comment]
yes, of course. I just assumed both times the same parameters:

./osrm-extract ../maps/berlin-ind3.osm -p ../profiles/examples/industrial3.lua

./osrm-prepare ../maps/berlin-ind3.osm -p ../profiles/examples/industrial3.lua

**Comment by TheMarex** [comment]
Try:

```
./osrm-prepare ../maps/berlin-ind3.osrm -p ../profiles/examples/industrial3.lua
```

(the `osrm-prepare` command need the `.osrm` file that is generated by `osrm-extract`)

**Comment by sebastian-fu** [comment]
thank you. That did the trick :)

**Comment by emiltin** [comment]
osrm-prepare should refuse or warn against .osm files as input.
