### ISSUE TITLE
Register Application

### ISSUE THREAD

**Issue by fhosen** [Project-OSRM/osrm-backend#1574]
First of all, I have to say that is a great service what you are providing, I thank you for that.

I want to use it in an application I am working on. I was using leaflet-routing-machine in the front end side and I read about your routing machine demo server, so I decided to use it in the back end.

I am new at this (building applications in general) and I would like to know what do I have to do in order to use osmr-backend in the backend side of my app.

I read the usage police and I notice that I have to register the App. Thank you in advance.

PS: I'm posting here because I didn't get a response via email, hope is ok.

**Comment by TheMarex** [comment]
@fhosen the demo server is free under fair-use if your application is Open Source and not commercial. For commercial applications please use a provider such as [Mapbox Directions](https://www.mapbox.com/developers/api/directions/).

**Comment by danpat** [comment]
Hi @fhosen.  `router.project-osrm.org` is made available for general use (subject to [the api usage policy](https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy)), and we make no guarantees for availability or performance.  For various reasons (volunteer time, project costs, etc) we may reduce or withdraw the service at any time.

If you're going to offer a service to users, you may be better off hosting your own server, installing your own copy of `osrm-backend` and offering your own directions

**Comment by fhosen** [comment]
Thank you for the quick replay. In deed, our proyect is open source, but it seems the best option is to have a server on our own.

Thanks!
