### ISSUE TITLE
C++ API Documentation

### ISSUE THREAD

**Issue by morganherlocker** [Project-OSRM/osrm-backend#1577]
The current docs only cover [the query function](https://github.com/Project-OSRM/osrm-backend/wiki/Library-api#c-library-interface). We should aim to cover at least the functionality underlying the [server API](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#available-services).

**Comment by TheMarex** [comment]
Yes the typical C++ way of adding documentation is to use http://www.stack.nl/~dimitri/doxygen/. Though I'm not sure how well this integrates with github pages or something like that. Any better options?

**Comment by morganherlocker** [comment]
I will try out doxygen and see how it goes. Doxygen allows for custom theming (the defaults leave a lot to be desired) and it should play nice with github pages. Also, the xml from doxygen can be piped to the pandoc markdown converter, if we want to just have an API.md file and/or update the wiki.

**Comment by TheMarex** [comment]
>  Also, the xml from doxygen can be piped to the pandoc markdown converter, if we want to just have an API.md file and/or update the wiki.

Oh that would be awesome.

**Comment by daniel-j-h** [comment]
@morganherlocker @TheMarex any updates on that front? Otherwise I would grab this.

Especially in regards to https://github.com/Project-OSRM/osrm-backend/issues/1434 and this week's housekeeping efforts.

**Comment by danpat** [comment]
See #1666

**Comment by morganherlocker** [comment]
I initially cut this ticket thinking that integration with the node-osrm docs would be a lot tighter. I think it makes sense to decouple this a bit (node-osrm docs should follow JS idioms, osrm-backend docs should cover internals more, etc.), and would love if someone on the osrm-backend side could run point.

**Comment by TheMarex** [comment]
Library API documentation is now also integrated into http://project-osrm.org/docs/v5.5.2/api/
