### ISSUE TITLE
Map matching algorithm

### ISSUE THREAD

**Issue by BharathMG** [Project-OSRM/osrm-backend#1578]
Hi,

I'm trying to map match few points. But it results in matching with wrong candidates. Below is the issue,

![screen shot 2015-07-24 at 5 11 44 pm](https://cloud.githubusercontent.com/assets/977859/8873761/79495840-3227-11e5-955a-e08baacc101d.png)

In the above picture, the third via_point falls on the North direction road segment (bidirectional road), whereas other points before it falls correctly on the South direction road segment. So, Shouldn't third point also fall within the South direction segment? 

Below is the expected behaviour,

![screen shot 2015-07-24 at 5 12 17 pm](https://cloud.githubusercontent.com/assets/977859/8873799/eb502bda-3227-11e5-8158-3836ebc4ceeb.png)

If I remove this third point, I'm getting correct map matched points. So, Is there any way I can detect this point which results in wrong map matching? Or is it a bug in map matching?

Thanks!

**Comment by TheMarex** [comment]
Can you send me the exact query that you tried to run? In the picture you are using the OSRM frontend which does not do map matching.

**Comment by BharathMG** [comment]
Sure! Here it is,

/match?z=10&loc=42.1691200,-71.6015000&loc=42.1689800,-71.6014500&loc=42.1688000,-71.6014100&loc=42.168550,-71.6014450&loc=42.1680900,-71.6013300&loc=42.1680600,-71.6018500


Thanks!

**Comment by BharathMG** [comment]
And also I'm trying to get turn instructions from the matched candidates in matching plugin. Because of this match, I'm getting wrong instruction.. Instead of "Turn Right" , I get "Turn Left" .

**Comment by BharathMG** [comment]
Does map matching take direction of the input coordinates into account?

**Comment by TheMarex** [comment]
Matching seems to work fine? http://bl.ocks.org/d/51c5e3a5d9c8361d9828

Which is the result of http://router.project-osrm.org/match?z=10&loc=42.1691200,-71.6015000&loc=42.1689800,-71.6014500&loc=42.1688000,-71.6014100&loc=42.168550,-71.6014450&loc=42.1680900,-71.6013300&loc=42.1680600,-71.6018500

```
{
    "matchings": [
        {
            "geometry": "_qxloAvteqgC~Bo@hCk@PAhBY|BS|BSAHfN_Ab\\qBFEGD??h@n_@??",
            "indices": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "matched_points": [
                [
                    42.169121,
                    -71.601501
                ],
                [
                    42.168976,
                    -71.601456
                ],
                [
                    42.1688,
                    -71.601425
                ],
                [
                    42.168556,
                    -71.601395
                ],
                [
                    42.168087,
                    -71.601334
                ],
                [
                    42.168068,
                    -71.601852
                ]
            ]
        }
    ]
}

```

**Comment by BharathMG** [comment]
Hi,
Thanks for the reply. If I get viaroute with the matched points, http://map.project-osrm.org/?instructions=true&loc=42.169121,-71.601501&loc=42.168976,-71.601456&loc=42.1688,-71.601425&loc=42.168556,-71.601395&loc=42.168087,-71.601334&loc=42.168068,-71.601852

I will get this U-turn route. So the 4th point in this coordinates is an outlier. If I remove the fourth point, and get the matched points, then I will get the correct traversed route with matched points, http://map.project-osrm.org/?instructions=true&loc=42.169121,-71.601501&loc=42.168976,-71.601456&loc=42.1688,-71.601425&loc=42.168556,-71.601395&loc=42.168068,-71.601845

Is there anyway this outlier can be detected? Or Does map matching not care about the actual route of the input coordinates? 

Thanks!

**Comment by TheMarex** [comment]
Seems like the point falls exactly on the endpoint of a segment, in which case `viaroute` decides to use the wrong edge for routing. The `match` plugin works, `viaroute` has just not enough information to decide which edge is meant by the coordinate.

I would suggest you try out https://github.com/Project-OSRM/osrm-backend/pull/1529 Which adds turn instructions to the result of the `match` request.

**Comment by BharathMG** [comment]
I tried that as well.. Unfortunately, as turn directions and instructions are derived from road segments, I'm getting wrong one for the matched points as the last one matched with the wrong segment. If matching took directions of input coords into account, would it match with the right segment?  As it is less likely to change the opposite direction suddenly.

**Comment by danpat** [comment]
Stale.

The `match` plugin can now return a full route response (instructions and all), and you can also supply a `bearing` filter on the URL to eliminate certain travel directions from consideration for each coordinate.
