### ISSUE TITLE
Test case in `via.feature` failing on OSX but not on Linux

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1581]
On OSX, on both `develop` and `master` I get:

    ./features/step_definitions/routing.rb:143:in `/^I route I should get$/'
    features/testbot/via.feature:110:in `When I route I should get'

    Failing Scenarios:
    cucumber -p verify features/testbot/via.feature:95 # Scenario: Via points on ring on the same oneway

    380 scenarios (1 failed, 379 passed)
    1582 steps (1 failed, 1581 passed)
    2m57.201s

However, on Ubuntu 15.05, I get all tests passing (although 2 fewer for some reason):

    379 scenarios (379 passed)
    1581 steps (1579 passed)
    1m20.734s

The test in question did run as part of the full suite, and can be run manually with:

    cucumber features/testbot/via.feature:95

**Comment by TheMarex** [comment]
Maybe related to lua weirednes on OSX or different compiler versions? You could try to print out the graph after contraction and compare it.

**Comment by TheMarex** [comment]
@danpat what is the status on this?

**Comment by daniel-j-h** [comment]
@MoKob is fixing that in https://github.com/Project-OSRM/osrm-backend/pull/1869. Closing here.
