### ISSUE TITLE
Reorganize root folder

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1583]
`data_structures` and `algorithms` includes a bunch of files that are either only used by `osrm-prepare`, `osrm-contract` or `osrm-routed`. We should separate that into own sub-directory like:

```
data_structures/
algorithms/
extract/
   data_structures/
   algorithms/
contract/
   data_structures/
   algorithms/
server/
   data_structures/
   algorithms/
```

That should make it a lot easier to see where a file is used just by placement in the file hierarchy.

**Comment by TheMarex** [comment]
New proposal:

```
features/
unit_tests/
include/
    contractor/
    extractor/
    engine/
    server/
    tools/
src/
    contractor/
    extractor/
    engine/
    server/
    tools/
```

Goals:

1. No relative include path
2. Each component will be compiled to`libosrm-COMPONENT` (static library)
3. All user facing binaries only use the corresponding `libosrm-COMPONENT` library (what is current `osrm-extract`, `osrm-prepare`, `osrm-routed`)
4. Each component has a clean public interface
5. Remove all legacy code (aka "If I can't remember why this is in the source tree, it gets removed")
6. Don't change anything user facing for now, this should just shuffle code/change build infrastructure

This will unlock:
- Expose `extract` / `prepare` through node (no need to bundle binaries anymore)
- Clean dependency structure

/cc @danpat @daniel-j-h @MoKob this will hurt _a little_ :syringe:  so I'm trying to run this out during the next week/first week in January.

**Comment by emiltin** [comment]
would also make it easier to enable cucumber testing directly from ruby without calling our to the normals bins. would require native ruby binding similar to osrm-node, eg something like ruby-osrm

**Comment by daniel-j-h** [comment]
@emiltin the libraries will have C++ interfaces and not C interfaces. For node this is no problem as we're using NAN anyway; not sure if and how ruby could interface with them as is.

**Comment by emiltin** [comment]
Yes, we would need to create a wrapper using eg. http://www.ibm.com/developerworks/library/os-extendruby/

**Comment by emiltin** [comment]
RICE on github: https://github.com/jasonroelofs/rice

**Comment by daniel-j-h** [comment]
Reorganization done, nothing actionable here. While we're at cleaning things up, we're putting in proper namespaces, sub-libraries, and so on. The codebase therefore will change a lot between 4.9 and 5.0.
