### ISSUE TITLE
Segmentation fault (core dumped) libc

### ISSUE THREAD

**Issue by sercoin** [Project-OSRM/osrm-backend#1585]
Hi,

OSRM showed ````Segmentation fault (core dumped)```` error and terminated when I send route request.  /var/log/syslog shows ````OSRM kernel: [64130.682635] osrm-routed[16248]: segfault at 2d39b9e ip 00007fb09d03f736 sp 00007fb072ffaf68 error 4 in libc-2.17.so[7fb09cee8000+1bf000]```` message. 

Two other OSRM running successfully on this server. I have a problem with the third one. I'm using v0.3.8. What could it be?

Regards

**Comment by TheMarex** [comment]
Without more information I can't tell you that. Do you have a debug build and can get me the whole backtrace? Otherwise could be any number of things. `3.8.0` is also quite old, maybe try `4.7.0` or develop.

**Comment by sercoin** [comment]
I'm using v0.3.8 master branch. git branch -vv result ````* master 966f1d6 [origin/master] Merge branch 'develop' for release v0.3.8````

**Comment by sercoin** [comment]
Is there any solution?

**Comment by danpat** [comment]
@sercoin Your code is >1 year old, we're currently working on v4.8.0, there are lots of things fixed.

If you want to debug a problem with the old code, you will need to do a DEBUG build, by specifying:

    `cmake -DCMAKE_BUILD_TYPE=Debug ..`

to generate debug makefiles.  Then, when the code crashes, you can get more information about the reason.  Please note that DEBUG builds run much slower.

**Comment by sercoin** [comment]
I build with debug but now I get this error 
````[info] Importing n = 3541072 nodes 
[info]  and 3810547 edges 
***** Internal Program Error - assertion (weight > 0) failed in NodeID readBinaryOSRMGraphFromStream(std::istream&, std::vector<T>&, std::vector<unsigned int>&, std::vector<unsigned int>&, std::vector<NodeInfo>*, std::vector<TurnRestriction>&) [with EdgeT = NodeBasedEdge; NodeID = unsigned int; std::istream = std::basic_istream<char>]:
/OSRM/osrm-backend/Util/GraphLoader.h(154): loaded null weight
Aborted (core dumped)````

**Comment by TheMarex** [comment]
@sercoin your data might be corrupted. Did you re-run `osrm-extract` and `osrm-prepare`?

**Comment by sercoin** [comment]
Yes. I extract data again with osrm-tools. I didn't get any error before debug build.

**Comment by sercoin** [comment]
Is there any solution?

**Comment by emiltin** [comment]
maybe try the latest version of osrm?

**Comment by sercoin** [comment]
I'm using osrm-tools and it doesn't support latest version. I have to use v0.3.7 or v0.3.8.

**Comment by TheMarex** [comment]
Sorry we are not going to support `0.3.8` anymore. You could try to take a stab at upgrading `osrm-tools`to a more recent version or find a different setup that does what you want. For further questions I would suggest using our [mailing list](mailto:osrm-talk@openstreetmap.org).
