### ISSUE TITLE
KM calculation problem with viaroute

### ISSUE THREAD

**Issue by mickdane** [Project-OSRM/osrm-backend#1587]
We are building a milageLog APP and get GPS positions from a installed GPS from the car.
What we need is to calculate the actually route the car went ! And we do not need to be restricted by any traffic rules!! Left turn not allowed, u-turn not allowed, etc.

We do a MATCH of the positions and then a via route but we keep on get "funny" turns, U-turns.

An ex here.
http://127.0.0.1:5000/viaroute?instructions=false&alt=false&loc=55.731003,12.576373&loc=55.730923,12.577146&loc=55.730923,12.577146&loc=55.730919,12.577164&loc=55.730919,12.57719&loc=55.730911,12.577244&loc=55.730793,12.578426&loc=55.730587,12.580394&loc=55.730556,12.580419&loc=55.729851,12.580579&loc=55.729832,12.580637&loc=55.729813,12.580823&loc=55.729748,12.580859&loc=55.729649,12.580825&loc=55.729141,12.580655&loc=55.729099,12.58058&loc=55.729137,12.580258&loc=55.729553,12.576521&loc=55.729511,12.576505&loc=55.729473,12.576487&loc=55.729156,12.576366&loc=55.727425,12.575853&loc=55.72694,12.575985&loc=55.726925,12.575991&loc=55.72686,12.576016&loc=55.726799,12.57604&loc=55.726685,12.575856&loc=55.726685,12.575785&loc=55.726692,12.575553&loc=55.728081,12.562121&loc=55.72765,12.552837&loc=55.727413,12.551148&loc=55.727039,12.550082&loc=55.726475,12.549217&loc=55.719849,12.542549&loc=55.719612,12.541764&loc=55.71936,12.540943&loc=55.719158,12.540608&loc=55.71347,12.535126&loc=55.712505,12.5342&loc=55.71225,12.533693&loc=55.711956,12.532664&loc=55.711704,12.531459&loc=55.70726,12.522228&loc=55.706959,12.52193&loc=55.702461,12.51988&loc=55.702423,12.519848&loc=55.702423,12.519848&loc=55.702423,12.519848&loc=55.702427,12.519849&loc=55.702427,12.519849&loc=55.702404,12.519828&loc=55.696121,12.512402&loc=55.693558,12.507412&loc=55.693264,12.506961&loc=55.68824,12.501525&loc=55.68824,12.501527&loc=55.688232,12.501515&loc=55.688019,12.501222&loc=55.687943,12.501119&loc=55.687782,12.501239&loc=55.687771,12.501335&loc=55.687714,12.501631&loc=55.687572,12.502108&loc=55.686958,12.50338&loc=55.686855,12.5043&loc=55.68671,12.506517&loc=55.686668,12.506608&loc=55.686504,12.506747&loc=55.685226,12.50753&loc=55.685169,12.507645&loc=55.685093,12.507939&loc=55.684254,12.512692&loc=55.684231,12.512677&loc=55.6842,12.512652&loc=55.684074,12.512557&loc=55.682018,12.510955&loc=55.682018,12.510955&loc=55.682018,12.510955&loc=55.682018,12.510953&loc=55.682018,12.510953&loc=55.681946,12.510979&loc=55.681843,12.510819&loc=55.681854,12.510582&loc=55.682201,12.503872&loc=55.681816,12.504054&loc=55.681816,12.504054&loc=55.681854,12.504031&loc=55.681854,12.504031&loc=55.681854,12.504031&loc=55.681854,12.50403 

Any one that has a solution for this ?

**Comment by mickdane** [comment]
Still nobody that had those problems. and a solutions...
The KM calculation is often 800 meters or more on very small trips 4.5km - Sometimes the calc is the same as the cars odometer but in most cases it's not - We have tried to reduce "NOISE" removing positions that are very near.

gps_precision and matching_beta parameter - Do they not work ??

Also looked at "Hidden Markov Map Matching Through Noise and Sparseness"

Have many many trips that we can test.

**Comment by TheMarex** [comment]
@mickdane can you send me a geojson of the route?

`gps_precision` standart deviation in meters of your GPS signal - try setting this much higher if your route has a lot of noise.

`matching_beta parameter` try increasing this value if your route has a low sample rate (e.g. less than 12 points/minute)

**Comment by muganda** [comment]
@TheMarex Thanks for this insight. @mickdane  and i work together and so i will take the liberty of responding in his absence. 
Here is the geojson for a trip whose actual odometer value is 7.2KM

{"type"=>"LineString", "coordinates"=>[["12.504521", "55.682422"], ["12.5044245", "55.6822913"], ["12.5044245", "55.6822913"], ["12.5044598", "55.6822908"], ["12.5128491", "55.6816916"], ["12.5128491", "55.6816916"], ["12.5198265", "55.6810915"], ["12.5226748", "55.680554"], ["12.5230798", "55.6805041"], ["12.525218", "55.6801961"], ["12.5276313", "55.680084"], ["12.5332406", "55.6791758"], ["12.5334235", "55.6791785"], ["12.5334956", "55.6792008"], ["12.533549", "55.6792438"], ["12.533603", "55.6793673"], ["12.5340858", "55.6809828"], ["12.5341031", "55.6809918"], ["12.5340991", "55.6810073"], ["12.534106", "55.6812118"], ["12.5342555", "55.681446"], ["12.5395395", "55.6861716"], ["12.541003", "55.6874785"], ["12.541003", "55.6874785"], ["12.541003", "55.6874785"], ["12.540997", "55.6874775"], ["12.540997", "55.6874775"], ["12.5410229", "55.687501"], ["12.5447205", "55.6907908"], ["12.5447395", "55.6908353"], ["12.5466155", "55.6924536"], ["12.546626", "55.6924581"], ["12.5466395", "55.6924601"], ["12.5468533", "55.6926551"], ["12.5469298", "55.6926773"], ["12.5475515", "55.693242"], ["12.5476025", "55.693238"], ["12.5483613", "55.6939028"], ["12.5484076", "55.6939585"], ["12.5484076", "55.6939585"], ["12.5484076", "55.6939585"], ["12.5484076", "55.6939585"], ["12.5484076", "55.6939585"], ["12.548463", "55.6939868"], ["12.5522286", "55.697373"], ["12.5522411", "55.6973913"], ["12.5522616", "55.6974045"], ["12.5539941", "55.6989141"], ["12.5539941", "55.6989141"], ["12.5539941", "55.6989141"], ["12.5539941", "55.6989141"], ["12.5539941", "55.6989141"], ["12.554041", "55.6989433"], ["12.558722", "55.7028288"], ["12.5621925", "55.7060055"], ["12.5621925", "55.7060055"], ["12.5621925", "55.7060055"], ["12.5621925", "55.7060055"], ["12.5621925", "55.7060055"], ["12.562248", "55.7060328"], ["12.5630576", "55.706344"], ["12.5701135", "55.7077215"], ["12.5701338", "55.7077241"], ["12.5701746", "55.7077286"], ["12.5756046", "55.7087415"], ["12.577129", "55.7090946"], ["12.577129", "55.7090946"], ["12.577129", "55.7090946"], ["12.5771223", "55.7090913"], ["12.5771223", "55.7090913"], ["12.5772218", "55.7090921"], ["12.5793381", "55.709174"], ["12.5847436", "55.7090683"], ["12.5850213", "55.7089216"], ["12.5851496", "55.7087193"], ["12.5852021", "55.7080973"], ["12.5852021", "55.7080973"], ["12.5852021", "55.7080973"], ["12.5852021", "55.7080973"], ["12.5852021", "55.7080973"], ["12.5852021", "55.7080973"], ["12.5860645", "55.7067123"], ["12.586162", "55.706685"], ["12.5862901", "55.7066833"], ["12.5865633", "55.7067043"], ["12.587623", "55.7068841"], ["12.5876648", "55.7068888"], ["12.5876936", "55.7068796"], ["12.5877376", "55.7068558"], ["12.5877376", "55.7068558"], ["12.5877376", "55.7068558"], ["12.587741", "55.706928"]]}

**Comment by mickdane** [comment]
@TheMarex Can you specify what we can or should use as values for 
gps_precision 
matching_beta

**Comment by mickdane** [comment]
Hi Patrick

Can you give me a ex on |gps_precision| |and matching_beta parameter|
|I have no Idea on what we should put there - I read some docs where 
bing was using 4.07meter for bing but That seams to be very little.

|
|matching_beta what is this ? and what should we use?|||||


Here is the geojson for a trip whose actual odometer value is 5.7KM

{"type"=>"LineString", "coordinates"=>[["12.543988", "55.694313"], 
["12.5439406", "55.6942565"], ["12.5439406", "55.6942565"], 
["12.5439245", "55.6942688"], ["12.5432796", "55.694784"], 
["12.5433286", "55.6948913"], ["12.5449166", "55.69653"], ["12.545148", 
"55.6966726"], ["12.5451788", "55.6966741"], ["12.5452173", 
"55.6966696"], ["12.5452783", "55.6966533"], ["12.5485583", 
"55.6943908"], ["12.5485811", "55.694385"], ["12.5486805", 
"55.6943576"], ["12.5487723", "55.6943551"], ["12.5487723", 
"55.6943551"], ["12.5488206", "55.6943548"], ["12.5488868", 
"55.6943686"], ["12.5489486", "55.6943953"], ["12.5551478", 
"55.6996558"], ["12.5616153", "55.7055095"], ["12.5625526", 
"55.706188"], ["12.5634741", "55.7064491"], ["12.5699919", 
"55.7076605"], ["12.5700171", "55.7076648"], ["12.5769771", 
"55.7090438"], ["12.5769771", "55.7090438"], ["12.5769771", 
"55.7090438"], ["12.5769733", "55.709046"], ["12.5769733", "55.709046"], 
["12.5770276", "55.7090635"], ["12.5774853", "55.7091835"], 
["12.5775388", "55.7092255"], ["12.5775951", "55.7093513"], 
["12.5776748", "55.714648"], ["12.5776748", "55.714648"], ["12.5776748", 
"55.714648"], ["12.577666", "55.7146796"], ["12.5771881", "55.7200701"], 
["12.5773408", "55.7213296"], ["12.5773458", "55.7213386"], 
["12.5777455", "55.7232646"], ["12.5777439", "55.7232746"], 
["12.5777395", "55.7232955"], ["12.5758911", "55.7278715"], 
["12.5765911", "55.7300418"], ["12.5765911", "55.7300418"], 
["12.5761728", "55.7309765"], ["12.5761904", "55.7309923"], 
["12.5762281", "55.7310063"], ["12.576284", "55.7310185"], 
["12.5764285", "55.7310215"], ["12.5767836", "55.7309908"], 
["12.5767385", "55.7309965"], ["12.5767576", "55.7310145"], 
["12.5767576", "55.7310145"], ["12.576986", "55.730949"]]}

**Comment by danpat** [comment]
Stale.
