### ISSUE TITLE
Strange routing result on a roundabout

### ISSUE THREAD

**Issue by Zverik** [Project-OSRM/osrm-backend#1589]
http://www.openstreetmap.org/directions?engine=osrm_car&route=56.85889%2C35.91154%3B56.85999%2C35.91127#map=18/56.85946/35.91202

Any route including ways from that roundabout produce strange result with absent roads.

**Comment by TheMarex** [comment]
@Zverik that is a known bug on openstreetmap.org - they use our API wrong.

**Comment by Zverik** [comment]
Thanks, but there are traces of this behaviour on osrm.at: http://osrm.at/edB (notice the small misalignment of the last segment).

**Comment by TheMarex** [comment]
Yes it is a small artifact of line simplification: Certain points in the geometry are disregarded if the "bend" is too small. This reduces the bandwidth used for geometries dramatically, but comes at certain costs. OSM.org has tuned up that parameter way too high.
