### ISSUE TITLE
Include starting bearing for each step in JSON descriptor

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-backend#1590]
JSONDescriptor [includes a bearing](https://github.com/Project-OSRM/osrm-backend/blob/02b561edd222def8c0abd74667acbdbf74d8feab/descriptors/json_descriptor.hpp#L355) in each instruction row, but it’s the bearing of the road you turn onto. Turn-by-turn clients would typically need to know the bearing of the road you turn _from_. For example, for a right turn, the user would expect to see a view of the intersection with the itinerary coming from the bottom of the screen and leaving the right edge of the screen, rather than coming from the right and leaving the top edge. JSONDescriptor should record both bearings for each instruction row.

**Comment by danpat** [comment]
This would be fairly straightforward to add here:

https://github.com/Project-OSRM/osrm-backend/blob/develop/descriptors/json_descriptor.hpp#L321-L366

we just need to keep track of the previous segment, and add it's heading to the result array if a turn instruction is needed.  @TheMarex this would involve changing the JSON response.  If we did it by adding an element at the end of the array, I don't see it causing too many backward-compatibility issues, but do we have a policy/regular procedure for this?

**Comment by TheMarex** [comment]
Good catch @1ec5!

@danpat Yes main problem here is breaking the API. We can add it as temporary fix for `4.8.0`. I was planning on [breaking it in 5.0.0](https://github.com/Project-OSRM/osrm-backend/issues/519).

The line you cited is probably not the correct position to add it - DescriptionFactory already simplifies the turn instructions a lot so the bearing value from the last instruction might not actually be from the previous street (but 200km away).

You would probably need to add it around here: https://github.com/Project-OSRM/osrm-backend/blob/develop/descriptors/description_factory.cpp#L182-L197 and move the bearing value into `SegmentInformation`.

**Comment by emiltin** [comment]
the information could also be extracted from the the geometry (even if this would be slow)?

**Comment by 1ec5** [comment]
> the information could also be extracted from the the geometry (even if this would be slow)?

Would that approach correctly handle gently sloped curves, where the geometry would include multiple short segments that would be elided from the route instructions?

**Comment by emiltin** [comment]
i guess it would depend on how you analysed the geometry. it's correct that you might need to look at more than simply the angle right at the turn point. another challenge might be that the geometry is simplified to varying degrees depending on the z parameter.

**Comment by emiltin** [comment]
so yeah, at best it would be a work around.

**Comment by TheMarex** [comment]
Implemented. Added two new fields to the instructions array.

**Comment by arnekaiser** [comment]
I think the pre-azimuth has a bug, because it is always the opposite (+-180°) of the post-azimuth. 

The post-azimuth is the bearing from the first to the second point and the pre-azimuth is the bearing from the second to the first point.

`const double post_turn_bearing = coordinate_calculation::bearing(first.location, second.location);`
`const double pre_turn_bearing = coordinate_calculation::bearing(second.location, first.location);`

But the pre-azimuth should be the bearing from the point before the first point to the first point.

**Comment by TheMarex** [comment]
@arnekaiser good catch. Should be fixed by https://github.com/Project-OSRM/osrm-backend/pull/1935
