### ISSUE TITLE
Strange routing although directly connected

### ISSUE THREAD

**Issue by al--** [Project-OSRM/osrm-backend#1592]
http://map.project-osrm.org/?hl=de&loc=48.20884,16.24235&loc=48.20830,16.24314

![Strange routing](https://cloud.githubusercontent.com/assets/1458456/9150662/d3806532-3de5-11e5-88be-77b4441e28a8.png)

The streets are directly connected in OSM, traffic can go straight in both directions, no turning limits set.

**Comment by TheMarex** [comment]
There is a barrier in the way. http://www.openstreetmap.org/node/3056908567

Probably should be tagged with http://wiki.openstreetmap.org/wiki/Key:traffic_calming rather than `barrier=chicane`

**Comment by the-knife** [comment]
The barrier does not seem to be a problem here : osrm.at/f39
Are barrier=gate considered as opened by os?

**Comment by TheMarex** [comment]
@the-knife yes gates are considered open if there is no `access` tag restriction. The data updates on the demo server seem to be not working at the moment, that is why it is still broken even after the change.

**Comment by the-knife** [comment]
@TheMarex thanks for the explanation
