### ISSUE TITLE
install lib luabind: b2: command not found

### ISSUE THREAD

**Issue by thanghm8** [Project-OSRM/osrm-backend#1599]
Hello,
I try to build OSRM in Centos 6.5. I installed:
- scons lib
- libxml2-devel lib
- boost-devel lib
- bzip2-devel lib
- libosmpbf-dev lib
- sttxl-devel lib
- lua lib
When install luabind ( luabind-0.9.1) with command:
b2 --toolset=gcc link=static variant=release -sBOOST_ROOT=../boost_1_52_0/ -sLUA_PATH=/usr/local

have error: b2: command not found
Please tell me the missing library

Thanks and regards
ThangHM

**Comment by daniel-j-h** [comment]
`b2` is the executable for Boost's build system, see:
> http://www.boost.org/build/doc/html/bbv2/faq/names.html

Also not how it was called `bjam` before. With that in mind, take a look at:
> https://github.com/Project-OSRM/osrm-backend/issues/1306

**Comment by thanghm8** [comment]
I have run successfully.
Thank you for your help

regards
ThangHM

**Comment by daniel-j-h** [comment]
Glad I could help.
