### ISSUE TITLE
Highlighting small components at inaccessible nodes

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#1602]
Came across an unroutable junction where all the oneway roads were leading out of it. 

<img width="626" alt="screenshot 2015-08-18 15 31 44" src="https://cloud.githubusercontent.com/assets/126868/9327898/d492d958-45c1-11e5-94cd-c4c8650d489d.png">
http://osrm.at/f2j

It took some time to figure out where the issue was since the small component layer had no segment to highlight. It would really help to highlight nodes as well with which we can easily spot such cases and those where there are barriers with access restrictions.

cc @TheMarex

**Comment by daniel-j-h** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/3570 adds GeoJSON from / to / type properties to the components output. You can use these to style your map. Closing as resolved. If you need more properties or a different feature set, feel free to re-open or open a new ticket.
