### ISSUE TITLE
traffic_data branch, should be able to select traffic_segment_codes on individual segments, not just on ways

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1607]
On the traffic_data branch, all segments now have a `traffic_segment_code` attached.  Unfortunately, it's only settable in the `way_function`, so the best granularity you can get is at the level of a way.

There should be the option to do it on a per-segment basis as well, by iterating over all edges and giving them the opportunity to replace the `traffic_segment_code` with a more specific code for each segment.

Geometry compression should look at the traffic_segment_code value to determine whether segments can be joined or not (it already does this, just re-iterating here).

**Comment by TheMarex** [comment]
Just to capute here @lbud already implemented a segment function which should be usable for exactly this task (if we extend the parameters of the functions a little bit).

**Comment by danpat** [comment]
This is done.
