### ISSUE TITLE
a newbie asks: Router Distance Table weirded out, what should I do?

### ISSUE THREAD

**Issue by benlewis-tes** [Project-OSRM/osrm-backend#1608]
Hi,

I have been using the router to find travel times between secondary schools (works a treat mostly, thank you), but I've got a few weird cases where instead of coming back with an error the project table posts a travel time of 214748364.7 secs.   

Is there a reason you can see why this is happening?  I can build a work around by moving the co-ords until I get a sensible answer but would be nice to understand what's really happening.

Here's an example:
http://router.project-osrm.org/table?loc=52.623077,-1.951208&loc=53.689807,-1.0368679
==>
{"distance_table":[[0,2147483647],[61601,0]]}

**Comment by daniel-j-h** [comment]
The problem with the distance table is that in your case there does not exist a path from your first point to the second point. But there exists a path from the second to the first point:

> http://router.project-osrm.org/viaroute?loc=52.623077,-1.951208&loc=53.689807,-1.0368679
> http://router.project-osrm.org/viaroute?loc=53.689807,-1.0368679&loc=52.623077,-1.951208

This can happen e.g. in case of oneway streets.

Currently edge weights are represented internally as ints, but the distance table's value type is unsigned. In the case of an error, you get an value indicating 'invalid' (`std::numeric_limit<int>::max()`) --- this is exactly what you are seeing in the public API.

This is probably not the best design, but there's no way to change it and break the API by now.

Does this explain your questions?

**Comment by emiltin** [comment]
could osrm return null instead of 2147483647?

**Comment by benlewis-tes** [comment]
Thanks for explaining - makes total sense.   

I was wondering whether there's anything I can do to change the node link as all my references are for schools that should have an in & out path really...

**Comment by emiltin** [comment]
if you can run osrm locally, you cn define your own routing profile (lua script) that ignores oenways

**Comment by benlewis-tes** [comment]
aye, just thinking of future users - I have 3 schools out of 3,500 that have this problem.  Would be good to root them out.

**Comment by emiltin** [comment]
if it's a bug in the osm data, then it can maybe just be fixed?

**Comment by benlewis-tes** [comment]
Is there a handy FAQ on how to do this?  Sorry, I'm a complete newbie with OSM..

**Comment by daniel-j-h** [comment]
Just start at http://www.openstreetmap.org. You can then locate the one way street, query it, add a note for mappers or create an account and start mapping yourself! Hope that helps.

There are also services out there that do the conversion to `null` in error cases in pass-through mode:

https://www.mapbox.com/blog/distance-api/
https://www.mapbox.com/developers/api/distance/

Closing this ticket as this is the distance table's expected behavior (right now).
