### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1624]
We are planning to use OSRM as a base and implement a different pre-processing
algorithm that uses the modern three phase approach of `preparation`, `customization` and `query`. Currently customization and preparation are mixed together, which means you need to re-run the whole pre-processing for each profile update. Three phase approaches move the main work to the initial profile independent pre-processing step, while the customization should be as fast as possible.

Work on this will start in a different repository in parallel to `5.0.0`. It is unclear at the moment if this can fully replace CH. As such it is yet undecided if this will replace the CH-based OSRM (e.g. `6.0.0`) or whether we can support both approaches. We will try to keep the overall tooling and API as compatible as possible.

### OSRM 4.8.0

- Preliminary raster data support
- TSP support
- Partial CH support (pre-processing + query)
- Restructuring of the `osrm-prepare`:
  - split out the geometry compression from EBGF
  - add tests for geometry compression

### OSRM 4.9.0

- Traffic data integration
  - fast ingestion of history and 'live' edge weights
  - support in `match` plugin to establish OSM mappings
- extend `segment_function` for finer grained weight data
- Investigate low hanging fruit to improve bike and pedestrian routing
- Further refactors and tests for pre-processing components

### OSRM 5.0.0

Last CH based release, probably only minor features and bug-fix releases from this point.
We can use this opportunity to break backwards compatibility since it is a major version bump.

- API cleanup
- Preparations for different pre-processing algorithm
  - Maybe restructure pre-processing utils

### OSRM 5.x.y

One of the bigger weaknesses of OSRM is the guidance. There are a few things to unlock to do good car guidance:

- Support for lanes
- Do more work in pre-processing to identify complex intersections and generate more
  sensible turn instructions

Obviously bike/pedestrian guidance is a whole different beast, but we will try to keep it as
general as possible.

/cc @lbud @daniel-j-h @chaupow @emiltin @freenerd @danpat

**Comment by emiltin** [comment]
Thank you, happy to see you're planning ahead.

Is it correctly understood that the customization phase will allow you to change edge weights, but not the network? Meaning it can be used for fast updates based on things like live traffic data or opening hours, while updates to the OSM data will require a rerun of the prepation phase as well (ie a full update)?

Will this affect the query performance? It sounds like you plan to leave the CH algorithm from versin 6 in favour of something else, I assume to get more flexibility in how queries can be done? For example, by adjusting preference on a by-query basis?

Regarding bike instructions, I think you're right that it can be improved quite a bit.

At the City of Copenhagen we're happy to provide what input we can regarding bike routing. We're currently working on a version 2.0 of out I Bike CPH app for Android and iOS, still uses OSRM to provide turn-by-turn GPS navigation, three types of bike routes (fastest, cargobikes and greenest), as well as the ability for user to collect GPS data and share it with the city so we can use it for things like improving/adjusting green waves for bikes (ie adjusting the timing of traffic signals). Data could potentially also be used as live traffic data, providing more realistic travel time estimates for bikes. (Yes we have crowding on some bike lanes, even thought they're 3 lanes wide...) Work is happening open source at the https://github.com/ibikecph/ibikecph-ios and https://github.com/ibikecph/ibikecph-android.

**Comment by TheMarex** [comment]
>Will this affect the query performance? 

Yes, queries will be somewhat slower. I'm still not sure how bad the slow-down is going to be, some implementations can still get around 1-5ms per query (I would guess we will get somewhere around 10-20ms). But still a lot faster than network latency. The real problems are Many-To-Many queries which would be much slower as far as I can see.

> For example, by adjusting preference on a by-query basis?

No, but you will be able to swap in new edge weights at runtime, for example to do traffic updates. In theory you could update single edges in a matter of milliseconds.

**Comment by emiltin** [comment]
Ok, so it's correctly understood that the customization phase will allow you to change edge weights, but not the network? Meaning it can be used for fast updates based on things like live traffic data or opening hours (diffrent parks might open/close at different times..), while updates to the OSM network will require a rerun of the prepation phase as well (ie a full update)?

**Comment by TheMarex** [comment]
@emiltin yes exactly.

**Comment by emiltin** [comment]
alright. thanks.

**Comment by systemed** [comment]
It would be great to have #482 (route relation support) in 4.8.0 or 4.9.0. At present I'm still running cycle.travel on a version of 0.3.10 incorporating @emiltin's original relations code; as soon as relations land in trunk I'd love to move to a newer version, and in turn might be able to contribute back some fixes/features.

**Comment by MKergall** [comment]
Are you are really planning integration of "live" traffic data? Like Waze? 
This would be a really exiting news! 
But it is also quite ambitious: need for world-wide traffic data; Server capacity to handle the (hopefully) numerous updates. 

Do you plan to publish an API allowing to "feed" those data from end-user devices? 
I would be happy to integrate that in OSMBonusPack - to provide simple access to all Android/osmdroid app developers.

**Comment by MoKob** [comment]
With 5.3. released, I guess we can close this discussion.
