### ISSUE TITLE
Remove protobuf dependencies no longer required due to protozero

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#1628]
libosmium 2.3.0+ [no longer requires the protobuf and osmpbf dependencies](https://github.com/osmcode/libosmium/wiki/Libosmium-dependencies), as it bundles [protozero](https://github.com/mapbox/protozero).

Yay for that.

Now let's remove those dependencies from our system as soon as [libosmium 2.3.0 gets merged in](https://github.com/Project-OSRM/osrm-backend/pull/1626).

Todo / tracking progress:

- [x] update wiki
- [x] update docker/Dockerfile
- [x] update CMakeLists.txt
- [x] update cmake/CPackDebianConfig.cmake
- [x] delete cmake/FindOSMPBF.cmake
- [x] update .travis.yml
- [x] remove from binary deps package created with [`windows-builds`](https://github.com/mapbox/windows-builds/blob/master/scripts/build_osrm_deps.bat) /cc @BergWerkGIS
- [x] proper fix for `stxxl`: `C2039: '_strtoi64': is not a member of 'std'`  /cc @BergWerkGIS

This is what I found silver-searchin' through the repository.

**Comment by TheMarex** [comment]
We now use 2.3.0, this should be unblocked.

**Comment by daniel-j-h** [comment]
@deatwisedog it seems like you added instructions to [the wiki on how to build OSRM on CentOS 6](https://github.com/Project-OSRM/osrm-backend/wiki/Bulding-OSRM-backend-on-CentOS-6/_history). I think `OSM-binary` is not needed, as the bundled `libosmium` handles reading / writing `.pbf` files and no longer requires any protobuf dependency. Could you check that?

**Comment by daniel-j-h** [comment]
Pull request at https://github.com/Project-OSRM/osrm-backend/issues/1635.

@BergWerkGIS it's on you now :)

**Comment by BergWerkGIS** [comment]
Done, AppVeyor is green with new binary deps package:
https://ci.appveyor.com/project/DennisOSRM/osrm-backend/build/1.0.1340
