### ISSUE TITLE
CentOS 7 compile stxxl 

### ISSUE THREAD

**Issue by cheburan** [Project-OSRM/osrm-backend#1631]
Trying to compile stxxl for OSRM on CentOS7 according to Building-OSRM guid

On the step of 
"cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/osrm_infrastructure/stxx -DBUILD_STATIC_LIBS=ON .."

reciving an error message (screenshot atached below)
![image](https://cloud.githubusercontent.com/assets/11454021/9546625/00f5c32e-4d9d-11e5-9a61-3502b8efa074.png)

**Comment by TheMarex** [comment]
Can you please open an issue for this at https://github.com/stxxl/stxxl? Thanks. :-)
