### ISSUE TITLE
Missing update of OSRM database, because turn-restriction without effect?

### ISSUE THREAD

**Issue by stephan75** [Project-OSRM/osrm-backend#1632]
I added a turn restriction on 16. August 2015 in Germany, Niedersachsen, Neu Wulmstorf:

http://www.openstreetmap.org/relation/5443120

But OSRM routing does not pay attention to that, see screenshot:
![osrm-nw](https://cloud.githubusercontent.com/assets/5250044/9548247/bcc1f59e-4d9f-11e5-9137-5d01e3229658.jpg)

Permalink for routing: http://osrm.at/fce

Is there an error in that turn restriction, or will I have to wait for a data update of OSRM?
If I am not wrong we had daily updates so far? 

When looking at the date hint on the web page at "settings" it says:
data:   n/a

**Comment by TheMarex** [comment]
The demo server is still somewhat broken. Data is very old, we are working on a fix.

**Comment by Michael21011** [comment]
Is demo server still broken?

**Comment by TheMarex** [comment]
We are currently moving servers. This needs some time. Sorry.

**Comment by Michael21011** [comment]
Thank you a lot for fast answer. Is there any estimation when I could check
my changes with new routing, please?
22 Сен 2015 г. 16:46 пользователь "Patrick Niklaus" <
notifications@github.com> написал:

**Comment by stephan75** [comment]
It seems that we have at least three updates:

project site http://project-osrm.org is in new design, but with fewer information,

routing demo website http://map.project-osrm.org/ is in new design ... but no more hint about database date?

and finally routing database of OSRM seems to be up-to-date again ... try online routing on http://osm.org

Mayn thanks to the developers' efforts!!

Will there be any official blog posting about these news, so that we can include it in the Wochennotiz blog or weeklyOSM.eu ?

( I think that https://www.mapbox.com/blog/osrm-4.8/ is aiming to much at mapbox)

**Comment by daniel-j-h** [comment]
@stephan75 there has been an [official mailinglist post](https://lists.openstreetmap.org/pipermail/osrm-talk/2015-September/000903.html) for the `v4.8.0` OSRM release a few days ago.

Regarding the demo server(s) and their OSM data date: please give us a few days, we're currently working on a bigger infrastructure change. With all these related questions (rightfully) popping up in the last days --- in form of tickets, mailinglist posts and IRC questions --- there will probably be an announcement once we complete the switchover.

**Comment by daniel-j-h** [comment]
By now we released `v4.9.0`; the demo server has some hiccups from time to time due to the nature of it being a demo server --- we guarantee no stability. Closing here.
