### ISSUE TITLE
Return snapped coordinate in distance table plugin

### ISSUE THREAD

**Issue by peterqliu** [Project-OSRM/osrm-backend#1637]
If I request driving directions from `A to B`, with C being the nearest routable neighbor to B, the reported duration is really of `A to C`. If B and C are very distant from each other, the duration prediction can be way off.

This issue becomes more significant when the new Distances API doesn't report C at all, making it difficult to gauge just how near the nearest neighbor is, and, by extension, how reliable the estimate is.

I don't have an ideal solution, but something that may work better would account for walking from and to the origin and destination, respectively.

**Comment by TheMarex** [comment]
You mean, you don't know which coordinate the nearest neighbor search snapped to, thus making it hard to debug the travel time given in the matrix? Very good point.

We should add this to the response of the `table` plugin - only problem here is that we currently add all the candidates to the heap and never check which one is used.

Also related to https://github.com/Project-OSRM/osrm-backend/issues/1447

**Comment by TheMarex** [comment]
This was implemented in our v5 API, we now return the snapped location of every input coordinate.
