### ISSUE TITLE
Add block barriers to foot whitelist

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#1643]
`barrier=block` are meant to stop larger vehicles according to the [wiki](http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dblock).

This is a possible candidate for the barrier whitelist in the foot and bicycle profiles. We're seeing Strava cycling/walking activity on roads with blocks. 

Example location:https://www.openstreetmap.org/node/959123752

**Comment by TheMarex** [comment]
Something for the `foot` whitelist at least. Not sure about bikes.

**Comment by emiltin** [comment]
i would also whitelist for bicycles. my guess is that barrier=block is used mainly when it's blocks with space between, rather that a low wall. a bicycle doesn't need much space to pass.

**Comment by daniel-j-h** [comment]
I solved this in https://github.com/Project-OSRM/osrm-backend/pull/1651 --- merged, closing here.
