### ISSUE TITLE
[Trip Plugin] Computing trips without returning to the start point

### ISSUE THREAD

**Issue by chaupow** [Project-OSRM/osrm-backend#1644]
Feature request which is similar to #1623:

Given a start point A and an end point B and other points C, D, E, ... a trip should be computed that starts at A, ends at B and visits all other points _without_ the need to return to point A again.

**Comment by zavan** [comment]
I have an use case which I believe is a specialization of this one: The only difference is that the end point can be any point, only the starting point is fixed, not sure how common that is.

**Comment by drew-py** [comment]
This would be a wonderful and very useful addition to the feature. :+1:

**Comment by daniel-j-h** [comment]
Not returning to the start and fixing start and end was implemented here

- backend https://github.com/Project-OSRM/osrm-backend/pull/3408
- node bindings https://github.com/Project-OSRM/node-osrm/pull/296

Closing as resolved.
