### ISSUE TITLE
Wrong: Fastest through residential and not over secondary

### ISSUE THREAD

**Issue by AllroadsNL** [Project-OSRM/osrm-backend#1645]
http://osrm.at/fhP

Same problem as in grasshopper
https://graphhopper.com/maps/?point=52.701666%2C5.861721&point=52.711957%2C5.867118&locale=nl-NL&layer=Omniscale

https://github.com/graphhopper/graphhopper/issues/511

This is wrong, taking two turns extra over residential Breestraat, this cost extra time, and over residential road.

The whole village is 30km/h. also secondary.

Allroads

**Comment by danpat** [comment]
Yes, both roads are marked as 30 km/h, and there are currently no penalties for turns, so OSRM is simply choosing the shortest route by distance (the side-road "cuts the corner").

We have *just* merged a change that will enable a simple turn penalty on the car profile (https://github.com/Project-OSRM/osrm-backend/commit/b3822d5802e7cfd57500ff4bf37570062a2a3bb8).  It should resolve this situation.

However, `router.project-osrm.org` hasn't been updated for a while and we're not sure when we will be able to deploy this new version there.  If you run your own routing setup, the above fix should correct things for you.

**Comment by TheMarex** [comment]
This works now. :cat:
