### ISSUE TITLE
Consider bundling a recent luabind version, unclear upstream

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#1646]
Currently we rely on the user's package manager to install luabind for us. The problem is that even in recent distributions, such as Ubuntu 15.04 the bundled luabind is still the [version 0.9.1](http://packages.ubuntu.com/vivid/libluabind-dev) from freaking 2010, with some patches added by the distribution's developers e.g. to make it work with lua5.2.

There are at least these divergent forks:

- https://github.com/luabind/luabind
- https://github.com/DennisOSRM/luabind
- https://github.com/rpavlik/luabind
- https://github.com/Oberon00/luabind

and probably some more with no clear upstream for sending in fixes (as I'd like to do).

We should strongly consider bundling a recent and maintained version of luabind.

To be done:

- [x] check for most recent / maintained fork
- [x] get in touch with original luabind developers / maintainers
- [ ] bundle as dependency instead of using the user's package manager's version

**Comment by daniel-j-h** [comment]
For example, luabind requires `boost::ref` and does not work with `std::ref` because of SFINAE [here](https://github.com/luabind/luabind/blob/457f28ab5a0d6331409883348588b43e3a0bc944/luabind/detail/convert_to_lua.hpp#L49). Without a clear upstream, how can we send in fixes?

**Comment by lbud** [comment]
@springmeyer do you have thoughts on this?
re https://github.com/Project-OSRM/osrm-backend/blob/masonize/bootstrap.sh#L15 / https://github.com/mapbox/mason/blob/luabind_lua524-dev/script.sh / https://github.com/mapbox/luabind

**Comment by springmeyer** [comment]
I would think a reasonable approach would be 1) Project-OSRM team forks latest luabind, 2) we start bundling it inside OSRM sources so that its no longer an external dep, 3) we revise the OSRM docs on building from source such that users know they do not need to install it externally.

If luabind maintainership improves in the future this could be rolled back. Or an alternative to luabind could then be switched out without users needing to adapt.

**Comment by TheMarex** [comment]
I'm really against bundling a version in our source tree. `luabind` is not a header-only library. It would increase the build system complexity to build two libraries in tree.

Alternatives:
- Provide an official fork in `/mapbox` and only build from there - consider renaming the library
- Completely drop `luabind` as dependency and use the raw lua C API

**Comment by daniel-j-h** [comment]
Reached out to fork maintainers and also original project devs (the source for what gets bundled in distributions). After a week, I only heard back from the https://github.com/Oberon00/luabind maintainer. He understandably does not really have the time to maintain a proper upstream project but would gladly contribute his changes (which are mostly bugfix related. He also runs his fork with the goal of being source and C++03 compatible, which may block some improvements re. C++11 / C++14.

The situation is really not the best. How to move forward here? Should be wait another week for responses? Should I invest some hours into how we are using Luabind, estimating if a switch to the raw Lua C API is possible at all, without building our own abstractions?

**Comment by TheMarex** [comment]
@daniel-j-h yes we should consider switching to raw C API. If that does not work, let's fork `luabind` to `mapbox/` and try to get people to use that (e.g. push out a new release).

**Comment by daniel-j-h** [comment]
@TheMarex there is already a https://github.com/mapbox/luabind forked from https://github.com/DennisOSRM/luabind. I will take a look at how exactly we are using luabind's features, in order to estimate how painful a switch to the raw C API would be.

**Comment by systemed** [comment]
This looks like an interesting fork: https://github.com/decimad/luabind-deboostified. No Boost dependency and appears to be active (i.e. commits within the last month).

**Comment by daniel-j-h** [comment]
Due to the sad state the Lua / Luabind ecosystem is in, we're planing to initially abstract the profiles in the code base (ref: https://github.com/Project-OSRM/osrm-backend/issues/1974) and in a second step to completely rip out Lua / Luabind.
