### ISSUE TITLE
Problem installing OSRM in Windows

### ISSUE THREAD

**Issue by a6datta** [Project-OSRM/osrm-backend#1648]
Hi, I have downloaded windows build from http://build.project-osrm.org/. The release folder looks like below

05/09/2015  01:33    <DIR>          .
05/09/2015  01:33    <DIR>          ..
04/09/2015  13:42                35 .stxxl.txt
04/09/2015  13:39           825,856 algorithm-tests.exe
04/09/2015  13:26            14,011 bicycle.lua
04/09/2015  13:26            13,458 car.lua
04/09/2015  13:37           944,128 datastructure-tests.exe
05/09/2015  01:25       633,726,109 england-latest.osm.pbf
04/09/2015  13:26    <DIR>          examples
04/09/2015  13:26             6,969 foot.lua
04/09/2015  13:26    <DIR>          lib
27/08/2015  16:45           487,936 libexpat.dll
27/08/2015  16:45           242,176 lua.dll
04/09/2015  13:36           471,040 osrm-datastore.exe
04/09/2015  13:41         1,795,584 osrm-extract.exe
04/09/2015  13:37           888,832 osrm-prepare.exe
04/09/2015  13:42         1,238,016 osrm-routed.exe
05/09/2015  01:32            53,502 profile.lua
04/09/2015  13:26             1,290 rasterbot-interp.lua
04/09/2015  13:26             1,278 rasterbot.lua
04/09/2015  13:32           126,464 rtree-bench.exe
05/09/2015  01:33                 0 stxxl.errlog
05/09/2015  01:33               233 stxxl.log
27/08/2015  16:49           188,928 tbb.dll
27/08/2015  16:49            89,088 tbbmalloc.dll
27/08/2015  16:49            31,232 tbbmalloc_proxy.dll
04/09/2015  13:26             3,442 testbot.lua
04/09/2015  13:26               167 turnbot.lua

profile.lua was not there. I manually downloaded and copied it there. 

When I try profile.lua with 'profiles/car.lua' it says syntax error '/'. If I move car.lua in root and change profile.lua to 'car.lua' then the error is syntax error near eof.

Any help would be greatly appreciated.

Thanks

**Comment by a6datta** [comment]
I have changed the profile.lua to 

require("lib/access")
require("profiles/car")

Now it's stuck 
C:\Users\Anup\Downloads\osrm_Release (1)>osrm-extract england-latest.osm.pbf
[info] Input file: england-latest.osm.pbf[0m
[info] Profile: profile.lua[0m
[info] Threads: 4[0m
[info] Using script profile.lua[0m
[STXXL-MSG] STXXL v1.4.99 (prerelease/Release) (git f7389c79e946430f5e3f7efc15e5bcc29183d200) + gnu parallel(__GLIBCXX__)
[STXXL-MSG] Disk 'c:\temp\stxxl' is allocated, space: 10000 MiB, I/O implementation: wincall queue=0 devid=0
[info] Parsing in progress..[0m
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)[0m
[info] timestamp: 2015-09-03T21:23:02Z[0m
[info] Using turn restrictions[0m
[info] Found 3 exceptions to turn restrictions:[0m
[info]   motorcar[0m
[info]   motor_vehicle[0m
[info]   vehicle[0m

**Comment by a6datta** [comment]
I managed to get it worked.

**Comment by TheMarex** [comment]
What was broken?

**Comment by a6datta** [comment]
It was fine. I thought it was stuck.
