### ISSUE TITLE
Map Matching coming with route instructions

### ISSUE THREAD

**Issue by hmaeda** [Project-OSRM/osrm-backend#1649]
I noticed that the Map-Matching functionality was recently improved to be more robust and [merged](https://github.com/Project-OSRM/osrm-backend/pull/1630). Please can the map-matching be enhanced further by including route instructions as an output as well? Furthermore, how are/could the timing between those given in the call and those provided by the route instructions be reconciled?

**Comment by hmaeda** [comment]
Furthermore, could a via_indices output that matches the route_geometry be added too?

**Comment by arnekaiser** [comment]
There is already a pull request (#1529).

**Comment by hmaeda** [comment]
[This](https://github.com/Project-OSRM/osrm-backend/pull/1529#issuecomment-138378315) suggests that it will look like multiple `viaroute` responses...This sounds good to me!

**Comment by TheMarex** [comment]
This is merged. https://github.com/Project-OSRM/osrm-backend/pull/1672
