### ISSUE TITLE
Using library API within dot net project

### ISSUE THREAD

**Issue by a6datta** [Project-OSRM/osrm-backend#1650]
Hi,

Is there any way to use the library API within a c# project. I know using c++ library is not straight forward but it can be done. However I will need a DLL to be able to call the functions. I have downloaded the windows build but which DLL should I use?

Thanks.

**Comment by BergWerkGIS** [comment]
@a6datta 

Thanks for pointing out, that the library files are missing.
I've assigned myself to add them.

> Is there any way to use the library API within a c# project.

We don't provide an official .Net Wrapper and haven't tested that way of interacting with osrm.

But there are two ways you can use a C++ library from C#:

* Pinvoke directly from C# ([MSDN: Platform Invoke Tutorial](https://msdn.microsoft.com/en-us/library/aa288468(v=vs.71).aspx))
* Write a `Managed Visual C++` project that acts as an intermediate layer

**Comment by a6datta** [comment]
Thanks. I can try to write a managed class. I will wait for the library files.

**Comment by BergWerkGIS** [comment]
@a6datta 
`osrm.lib` is now included in the download.
Let me know, if anything else is missing.

**Comment by daniel-j-h** [comment]
In case a C wrapper is of any help check out [osrm-c](https://github.com/tdihp/osrm-c).
