### ISSUE TITLE
Windows: datastructure-tests.exe is failing

### ISSUE THREAD

**Issue by BergWerkGIS** [Project-OSRM/osrm-backend#1653]
https://ci.appveyor.com/project/DennisOSRM/osrm-backend/build/1.0.1270#L1854

![image](https://cloud.githubusercontent.com/assets/4549888/9718791/3e79fb40-557f-11e5-8de5-a14cd2d29151.png)

FYI:
Despite the failed test the AppVeyor build succeeded, because I had temporarily removed the check for failed tests (it's on now again) to get a new artifact for:
https://github.com/Project-OSRM/osrm-backend/issues/1650

**Comment by daniel-j-h** [comment]
[Raster source unit test](https://github.com/Project-OSRM/osrm-backend/blob/b734d4bbc169df7a33c2fdccaf6f0de34420118d/unit_tests/data_structures/raster_source.cpp#L51) and the [file it's loading](https://github.com/Project-OSRM/osrm-backend/blob/b734d4bbc169df7a33c2fdccaf6f0de34420118d/unit_tests/fixtures/raster_data.asc).

Something to do with how Windows handles paths?

/cc @lbud

**Comment by TheMarex** [comment]
https://github.com/Project-OSRM/osrm-backend/commit/d2080808db1bbddfd2ad2ea271b24d28cfcb4a73#diff-b7e93f1c9fb3ce0d3288e25edeaeed0eL70

This removes my fix for running the tests. They expect to be run from `build/` not `build/Release` or `build/Debug`. The paths given in the test are relative.

**Comment by BergWerkGIS** [comment]
@TheMarex OOPS. thanks. Will change and test later (running a mapnik build at the moment).

**Comment by BergWerkGIS** [comment]
`raster_test` now passes again:
https://ci.appveyor.com/project/DennisOSRM/osrm-backend/build/1.0.1273

But this problem surfaced another one: https://github.com/Project-OSRM/osrm-backend/issues/1654
