### ISSUE TITLE
Windows: fatal error in "raster_test": std::exception: Failed to parse raster source correctly.

### ISSUE THREAD

**Issue by BergWerkGIS** [Project-OSRM/osrm-backend#1654]
Despite the `raster_test` passing on AppVeyor, I get error this locally:

```
running datastructure-tests.exe ...
Running 28 test cases...
unknown location(0): fatal error in "raster_test": std::exception: Failed to parse raster source correctly.
C:\Projects\osrm\unit_tests\data_structures\range_table.cpp(51): last checkpoint

*** 1 failure detected in test suite "datastructure tests"
```

### Problem: git and line endings

The problem stems from the default behavior of git when cloning text files.

In our case:
```
unit_tests/fixtures/raster_data.asc
```

A **default install of `git` on Windows** automatically converts line endings of text files during `clone` (to the system default line endings: `CRLF`=`\r\n`) and during `commit`  back to Linux line endings (`LF`=`\n`).

**On AppVeyor** the test passes, because the default behavior of git has been overridden to keep the `LF` line endings.

It seems that the different possible line endings are not accounted for in [`raster_source.hpp::RasterGrid`](https://github.com/Project-OSRM/osrm-backend/blob/bed0598530540c1b2459bb271727511ebedaa80e/data_structures/raster_source.hpp#L88-L102)

### Possible solutions

* add `.gitattributes` to tell git to keep `LF` despite the default settings
* change the code to be platform independent and work with `LF` and `CRLF`

My preference is the second option.
The first option would make the test pass, but would also create problems for Windows users who create their own raster files with Windows line endings.

**Comment by BergWerkGIS** [comment]
FYI:
[Auto new line detection in mapnik csv plugin](https://github.com/mapnik/mapnik/blob/ee6587315965109ab8579e6962df78fff1103571/plugins/input/csv/csv_utils.hpp#L139-L161)

**Comment by TheMarex** [comment]
@lbud any idea why `boost::algorithms::trim` does not catch this? https://github.com/Project-OSRM/osrm-backend/blob/develop/data_structures/raster_source.hpp#L82

**Comment by daniel-j-h** [comment]
@TheMarex it should: http://coliru.stacked-crooked.com/a/5293bb5c58cb4581 --- but as the `ifstream` a few lines above is not opened with the `binary` flag, I suppose the stream behaves differently with files on both platforms.

**Comment by BergWerkGIS** [comment]
@daniel-j-h good catch!

Changing 
https://github.com/Project-OSRM/osrm-backend/blob/bed0598530540c1b2459bb271727511ebedaa80e/data_structures/raster_source.hpp#L67

```cpp
boost::filesystem::ifstream stream(filepath);
```

to 

```cpp
boost::filesystem::ifstream stream(filepath, std::ios::binary);
```

makes the test pass on Windows with `CRLF` and `LF` line endings.

**Comment by daniel-j-h** [comment]
@BergWerkGIS I'm not an expert in this, but take a look what I found with a quick search:

```
daniel@x1c /t/osrm-backend> ag ifstream|ag -v bin
datastore.cpp:317:            boost::filesystem::ifstream timestamp_stream(timestamp_path);
datastore.cpp:354:        std::ifstream geometry_input_stream(geometries_data_path.string().c_str(),
third_party/variant/test/catch.hpp:3954:        std::ifstream f( _filename.c_str() );
third_party/libosmium/test/data-tests/include/check_wkt_handler.hpp:20:        std::ifstream in(filename, std::ifstream::in);
third_party/libosmium/test/include/catch_orig.hpp:4175:        std::ifstream f( _filename.c_str() );
third_party/libosmium/test/include/catch.hpp:4175:        std::ifstream f( _filename.c_str() );
server/data_structures/internal_datafacade.hpp:89:            boost::filesystem::ifstream timestamp_stream(timestamp_path);
data_structures/static_rtree.hpp:340:    boost::filesystem::ifstream leaves_stream;
data_structures/raster_source.hpp:67:        boost::filesystem::ifstream stream(filepath);

```

For portability shouldn't all of those be constructed with the `binary` flag then?

- [datastore.cpp](https://github.com/Project-OSRM/osrm-backend/blob/bed0598530540c1b2459bb271727511ebedaa80e/datastore.cpp#L317)
- [static_rtree.hpp](https://github.com/Project-OSRM/osrm-backend/blob/bed0598530540c1b2459bb271727511ebedaa80e/data_structures/static_rtree.hpp#L340)
- [internal_datafacade.hpp](https://github.com/Project-OSRM/osrm-backend/blob/bed0598530540c1b2459bb271727511ebedaa80e/server/data_structures/internal_datafacade.hpp#L89)

It shouldn't make a difference as long as we're just reading e.g. a timestamp. What's your take on this?

**Comment by BergWerkGIS** [comment]
@daniel-j-h 
Yes, generally speaking, we should have consistent behavior with any **text** file access.
Binary files don't matter in this case.

Specifically, differences only appear if there are new lines in the text files.

Any chance to expose those `ifstream` occurrences via tests?
Like in the `raster_test` that surfaced this problem.

**Comment by daniel-j-h** [comment]
> Binary files don't matter in this case.
> 
> Specifically, differences only appear if there are new lines in the text files.

Does that mean, when we open binary files in text mode and there is a `10 :: int` / `\n :: char` byte in them, Bad Things (tm) could happen?


> Any chance to expose those ifstream occurrences via tests?
> Like in the raster_test that surfaced this problem.

The other `ifstream` occurrences are somewhat buried in the code base, we would have to write tests for dumping and then loading an rtree for example. Nor sure how feasible that is.

**Comment by BergWerkGIS** [comment]
> when we open binary files in text mode

Does this make sense?
Why would we want to do that?

> and there is a `10 :: int` / `\n :: char` byte in them, Bad Things (tm) could happen?

Yes, also happens with text editors that suppose every file you throw at them is text and don't have a binary/hex mode to open files as binaries.
Or, even when you `type` a binary file to the console: strange things might happen, like new lines or the speaker beeping.

> > Specifically, differences only appear if there are new lines in the text files.

I was thinking about files like `raster_data.asc` that contain plain text and several lines.

**Comment by daniel-j-h** [comment]
> when we open binary files in text mode
> 
> Does this make sense?
> Why would we want to do that?

Well, the default open mode for `ifstream`'s constructor is [not binary](http://en.cppreference.com/w/cpp/io/basic_ifstream/basic_ifstream) from what I can tell. Therefore, in all cases that I mentioned above, we already open the files in text mode --- or do I miss something here?

**Comment by BergWerkGIS** [comment]
From my understanding that's exactly the problem (files opened in text mode).
**But**, I have no experience with `boost` and I might be completely wrong, but I think this additional API layer might be causing our troubles.

---

On Windows, C file streams transparently convert `\n` to `\r\n`.
e.g. on the console (which is a stream) `type myfile-with-LF-endings.txt` will show a nice output:

![image](https://cloud.githubusercontent.com/assets/4549888/9767357/1f936af4-571e-11e5-843b-6cd2ef56bd10.png)

which looks exactly like a file with CRLF:
![image](https://cloud.githubusercontent.com/assets/4549888/9767389/42703250-571e-11e5-8c03-bdc7ac291d1e.png)

So, I suppose, when using the default `boost::filesystem::ifstream` the file will go through several stream objects that all alter the stream, trying to `LF->CRLF` when there are already `CRLF`s, resulting in something like `\r\r\n`.

Telling boost to read the file as binary doesn't change the line endings and then the next stream object can work its magic correctly.

Ref:
http://en.cppreference.com/w/cpp/io/c#Binary_and_text_modes

---

In `C#` we have a pretty thing called `System.Environment.Newline`, which evaluates to the OS specific new line.
Does something similar exist in C++?

**Comment by daniel-j-h** [comment]
> Does something similar exist in C++?

For opening in binary mode, there is `ios::binary`. For portable line endings pushing `'\n'` into a stream should suffice, as the stdlib is responsible for converting it to the platform specific line ending.

To summarize: add `ios::binary` everywhere and Windows is happy? :P

**Comment by BergWerkGIS** [comment]
> To summarize: add `ios::binary` everywhere and Windows is happy? :P

Cannot tell for sure, we have to test, as `ios::binary` is also counter intuitive for me.

Maybe `boost::spirit::qi::parse` uses a text file stream somewhere, that is responsible for the double conversion `LF->CRLF`. (Then again, as mentioned above, this is just my hunch).

**Comment by daniel-j-h** [comment]
We're dropping Windows support. There was no one standing up as a Windows dev / maintainer.
Ref: https://lists.openstreetmap.org/pipermail/osrm-talk/2016-May/001214.html

Closing this ticket, no longer actionable.
