### ISSUE TITLE
osrm-backend deploy on windows

### ISSUE THREAD

**Issue by longtq-setacinq** [Project-OSRM/osrm-backend#1656]
Please instruct us how to deploy on window environment of osrm-backend project, we need to build and deploy a webservice based on module osrm-backend.Thanks

**Comment by daniel-j-h** [comment]
Here are the Windows builds:
http://build.project-osrm.org/

If you want to build it on your own you can find instructions in the Wiki:
https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM

And here's a Gist with some additional information:
https://gist.github.com/alex85k/8637217

And this is how you run it:
https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

**Comment by longtq-setacinq** [comment]
Hi @daniel-j-h , could you please instruct me how to run osrm-backend on windows? I want to deploy this system on window, similar to this: http://router.project-osrm.org/table

**Comment by daniel-j-h** [comment]
This is a high level summary of what you can find in the Wiki and the links I posted above:

- grab a Windows binary or build it yourself
- get an OSM dataset for your specific region or the planet.pbf
- run `osrm-extract` to pre-process the dataset
- run `osrm-prepare` to prepare for routing
- run `osrm-routed` to start the HTTP Server

**Comment by TheMarex** [comment]
Checkout the AppVeyor [build script](https://github.com/Project-OSRM/osrm-backend/blob/master/appveyor-build.bat). Closing.
