### ISSUE TITLE
Ubuntu 14.04 64 bit Error when Building OSRM

### ISSUE THREAD

**Issue by longtq-setacinq** [Project-OSRM/osrm-backend#1657]
During the building osrm-backend process, i encountered some errors as:
longtran@longtran:~/osrm-backend/build$ make
make: *** No targets specified and no makefile found.  Stop.

Steps i implemented this building osrm backend process are:
git clone https://github.com/Project-OSRM/osrm-backend.git
cd osrm-backend
mkdir -p build
cd build
cmake ..
make

Please help me on this bug.Thanks

**Comment by danpat** [comment]
The `cmake ..` command should generate a `Makefile` file in `build`.

It sounds likely that there was an error during `cmake ..`, and the `Makefile` wasn't created.  Re-run `cmake ..` and look for errors.  The problem is most likely a missing dependency.

**Comment by daniel-j-h** [comment]
Try the following:

    mkdir build
    cmake .. -DCMAKE_BUILD_TYPE=Release
    cmake --build .

Also check with `pwd` and `ls` in the build directory that you actually called `cmake` from the build directory, it seems like no makefile was created from what I can tell reading the error message.

Check this and if it doesn't help post a `pwd` and `ls` output in your build directory.

**Comment by longtq-setacinq** [comment]
longtran@longtran:~/osrm-backend/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- LTO working
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES) 
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /usr/lib/x86_64-linux-gnu/liblua5.2.so
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so
-- OpenMP support found. Linking just in case for stxxl
-- Looking for OSMPBF...
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OSMPBF (missing: OSMPBF_LIBRARY OSMPBF_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOSMPBF.cmake:46 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:283 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/longtran/osrm-backend/build/CMakeFiles/CMakeOutput.log".
See also "/home/longtran/osrm-backend/build/CMakeFiles/CMakeError.log".


longtran@longtran:~/osrm-backend/build$ cmake --build
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Don't merge stdout/stderr output and pass the
                   original stdout/stderr handles to the native
                   tool so it can use the capabilities of the
                   calling terminal (e.g. colored output).
  --             = Pass remaining options to the native tool.


Please help me.

**Comment by daniel-j-h** [comment]
First of all, you are missing the `osmpbf` dependency. Please install `libprotoc-dev libprotobuf8 \
protobuf-compiler libprotobuf-dev libosmpbf-dev`, just to make sure you really have all dependencies.


Then, you forgot to specify the current build directory `.` in `cmake --build .`, also if `cmake` errors out you can't just go on.

**Comment by longtq-setacinq** [comment]
I have set up library. But i still can not build it on ubuntu
Ubuntu 14.04+

sudo apt-get install build-essential git cmake pkg-config \
libbz2-dev libstxxl-dev libstxxl-doc libstxxl1 libxml2-dev \
libzip-dev libboost-all-dev lua5.1 liblua5.1-0-dev libluabind-dev libluajit-5.1-dev libtbb-dev



longtran@longtran:~$ cd osrm-backend
longtran@longtran:~/osrm-backend$ cd build
longtran@longtran:~/osrm-backend/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- LTO working
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES) 
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /usr/lib/x86_64-linux-gnu/liblua5.2.so
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so
-- OpenMP support found. Linking just in case for stxxl
-- Looking for OSMPBF...
-- Found OSMPBF: /usr/lib/libosmpbf.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/longtran/osrm-backend/build
longtran@longtran:~/osrm-backend/build$ cmake --build
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Don't merge stdout/stderr output and pass the
                   original stdout/stderr handles to the native
                   tool so it can use the capabilities of the
                   calling terminal (e.g. colored output).
  --             = Pass remaining options to the native tool.
longtran@longtran:~/osrm-backend/build$

**Comment by daniel-j-h** [comment]
You are still missing the `.` in `cmake --build .`.
Add a `.` at the end. It even says,
> Project binary directory to be built.

**Comment by longtq-setacinq** [comment]
Thanks. Done :)

Linking CXX executable osrm-routed
[100%] Built target osrm-routed
longtran@longtran:~/osrm-backend/build$

.........................................

Could you please instruct me to deploy osrm-backend on ubuntu? I want to deploy this system on ubuntu, similar to this: http://router.project-osrm.org/table

**Comment by TheMarex** [comment]
@longtq-setacinq just need a few bash scripts and I cron job. I'm sure you can figure it out using the [wiki](https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM).
