### ISSUE TITLE
can't computes distance tables for given coordinates

### ISSUE THREAD

**Issue by longtq-setacinq** [Project-OSRM/osrm-backend#1658]
http://localhost:5000/table?loc=21.034,105.79043&loc=21.3454,105.4545

After deploying and running on that address, i received results as:

{"distance_table":[[0,0],[0,0]]}

, i dont know the reason for this error, please instruct me in order that it can work as this:  http://router.project-osrm.org/table?loc=21.034,105.79043&loc=21.3454,105.4545

{"distance_table":[[0,63023],[32447,0]]}

**Comment by freenerd** [comment]
This might be an issue with your underlying data. Are you sure the data you use has the coordinates you are querying and that there is indeed a route between the points?

Anyways: if you run into problems setting up OSRM yourself, maybe you would like to just give an API a spin? We at Mapbox have the [Distance API](https://www.mapbox.com/developers/api/distance/) that might be exactly what you are looking for.
