### ISSUE TITLE
`noexcept` specifier placed on functions that may indeed throw

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#1660]
First example I could find: [bearing.hpp](https://github.com/Project-OSRM/osrm-backend/blob/fd6daa580a7d3c7e2074a9c6ca1da41268274d26/util/bearing.hpp#L35), marks the `get` function with `noexcept`, guaranteeing to never throw. If the function does throw, the program gets terminated.

The problem here is that `std::string` can indeed throw in its constructor (e.g. in the out of memory case). This is just an example based on the first occurrence I could fine --- have to check all of them.

References:

- C++14 standard: 15.4 "Exception specifications" [except.spec]
- Effective Modern C++: "Item 14: Declare functions noexcept if they won’t emit exceptions."
- http://en.cppreference.com/w/cpp/language/noexcept_spec

**Comment by TheMarex** [comment]
Can we check this in an automated case?

**Comment by daniel-j-h** [comment]
From the top of my head I don't think there is an automated way to do it.

There's also the [`noexcept` operator](http://en.cppreference.com/w/cpp/language/noexcept) that allows for conditionally `noexcept`, such as `noexcept(fn())`.

**Comment by daniel-j-h** [comment]
I fixed this in #1882.
