### ISSUE TITLE
motorway_link is not implied oneway

### ISSUE THREAD

**Issue by ghost** [Project-OSRM/osrm-backend#1662]
According to https://github.com/gravitystorm/openstreetmap-carto/issues/1820 and the wiki OSRM routing rules are incorrect.

**Comment by TheMarex** [comment]
@planemad Could you take a look at how many `motorway_link` would be affected by that?

I have a feeling that there are a lot of `motorway_link` roads that are not tagged with `oneway=yes` and would break the routing.

**Comment by planemad** [comment]
@TheMarex 

- 98% of `highway=motorway_link` have a `oneway=*` tag (94%=yes, 4%= no)

http://taginfo.openstreetmap.org/tags/highway=motorway_link#combinations
