### ISSUE TITLE
Make `osrm-cli` more robust against missing arguments

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#1665]
As reported on IRC by user winwaed_, `osrm-cli` has the default behavior of horribly crashing.

````
daniel@x1c /t/o/build> ./osrm-cli
[info] starting up engines, v4.7.1-1-g40443d1
[warn] caught exception: Start canary of block corrupted.
````

Better way of handling missing arguments would be to print the `--help` output.

**Comment by emiltin** [comment]
is osrm-cli desribed in the wiki? haven't heard about the tool.

**Comment by daniel-j-h** [comment]
`osrm-cli` [gets built](https://github.com/Project-OSRM/osrm-backend/blob/a1e273e9839f9688de9e3b09d8c8172209eeac1b/CMakeLists.txt#L313) from the [tool's directory](https://github.com/Project-OSRM/osrm-backend/tree/40443d1e25a5053d543621d03e106cffbfa37ff4/tools) based on the [`simpleclient.cpp`](https://github.com/Project-OSRM/osrm-backend/blob/40443d1e25a5053d543621d03e106cffbfa37ff4/tools/simpleclient.cpp).

That is, it's just an example for how to use `libosrm` and do queries against it.

**Comment by daniel-j-h** [comment]
`osrm-cli` is gone, have a look at `example/example.cc` for how to use libosrm instead.
