### ISSUE TITLE
model of turn penalties?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#167]
i understand turn penalties are not that far away, and what's essentially missing is just a good model.  copenhagen university is intersted in helping out and provide parameters based on their research and data, but we need a better understanding of what such a model should consist of.

to get things started - 
i imagine that there are 3 types of turns: normal turns, sharp turns, and u-turns, and that a penalty value is needed for each type of turn. so maybe something like:

```
side    type          angle range  penalty
--------------------------------------------
left    turn          20..160      0.1
left    sharp turn    140..160     0.3
left    u-turn        160..180     0.6
right   turn          -20..-160    0.1
right   sharp turn    -140..-160   0.3
right   u-turn        -160..--180  0.6
````

an alternative could be generalize this into a single 'continuous' formula that takes the angle as input and returns a penalty.

thoughts?

**Comment by TheMarex** [comment]
We are exploring using a data driven approach as opposed to a model driven one via https://github.com/Project-OSRM/osrm-backend/pull/2306

**Comment by TheMarex** [comment]
We are determined to make this work with a data driven approach. Closing this for now.
