### ISSUE TITLE
Integrate coverage report with coveralls.io

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#1673]
Try out integration with https://coveralls.io.

Here's the user-contributed C++ support repository:
https://github.com/eddyxu/cpp-coveralls

Steps to take:

- [x] investigate coveralls.io setup
- [x] build system option to pass down cxxflags `-fprofile-arcs -ftest-coverage`
- [x] travis integration

**Comment by lbud** [comment]
@springmeyer was working on getting this working with the `masonize` branch a few months ago. We left off here: https://coveralls.io/github/Project-OSRM/osrm-backend and can probably convince him to come back and help out :)

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/pull/2235.
