### ISSUE TITLE
Strange routing

### ISSUE THREAD

**Issue by Debeet** [Project-OSRM/osrm-backend#1674]
Route: http://osrm.at/fmu

You can see that OSRM refuses to use the ramp and goes straight forward only to do make a very sharp turn later on.

1. Is this an issue with the map or the routing engine?
2. Shouldn't OSRM avoid making such sharp turns?

**Comment by danpat** [comment]
The data sitting behind `router.project-osrm.org` is getting a bit stale (it hasn't updated for a while).  We're working on a fix.  It's possible that this problem is related to the older OSM data that is being used.

**Comment by MoKob** [comment]
Fixed with current releases.
