### ISSUE TITLE
Routing by relation

### ISSUE THREAD

**Issue by svatok13** [Project-OSRM/osrm-backend#1676]
I have some big routing: 
![screenshot from 2015-09-11 14 38 57](https://cloud.githubusercontent.com/assets/10708438/9814069/c313f470-5893-11e5-96e7-5ffe364ffe68.png)
I need to have it built on the relation with 'M12' ref tag, but sometimes it builds like this:
![screenshot from 2015-09-11 14 39 23](https://cloud.githubusercontent.com/assets/10708438/9814122/378436c6-5894-11e5-95c6-f7af496d4295.png)
I have only the start and end points and don`t know how to find some guide points. Is there a solution of this issue?

**Comment by floscher** [comment]
I guess you use https://openstreetmap.org to calculate your route?! On that website there is currently no possibility to add stopovers to a route.

For calculating such routes with OSRM you have to use other websites like http://map.project-osrm.org . By clicking and dragging the blue line you can add stopovers over there. Like this: http://osrm.at/fnR

**Comment by svatok13** [comment]
floscher, thank`s for your reply. You don`t understand me. I am build routing with my application. I have only start and end points and build route, using viaroute service on the backend.

**Comment by emiltin** [comment]
if you're running your own osrm route server, you can modify the lua script to prioritize ways any wasy you like, for example increase priority of ways with ref=* tags.

**Comment by svatok13** [comment]
emiltin, can you please show me, how to do it on some example?

**Comment by emiltin** [comment]
take at look at profiles/car.lua. it parses the ref tag, but only for naming way:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L335


you can do something like:

```lua
  if "M12" == ref then  -- go really fast on M12
    result.forward_speed = result.forward_speed * 2
    result.backward_speed = result.backward_speed * 2
  end
```

this make routes prefer M12. but note that since osrm dosn't yet have a way to specify speed and priority separately, it will have the side effect of making the reported travel time unrealistic.

**Comment by daniel-j-h** [comment]
Nothing actionable here, closing. The example above is the way to do it!
