### ISSUE TITLE
osrm-routed.exe not working

### ISSUE THREAD

**Issue by maximd1** [Project-OSRM/osrm-backend#1679]
Hello,

yesterday I've prepared all of stuff for the whole planet (97GB of data in several files after the ~2 days of processing). Trying to run osrm-routed in Windows 10, but facing following issue:

D:\Work\osrm\engine>osrm-routed.exe
[info] Reading options from: server.ini←[0m
[info] starting up engines, v4.5.0-627-gfe0fe18←[0m
[info] populating base path: ←[0m
[info] not a regular file←[0m
←[31m[warn] exception: .hsgr not found: .hsgr←[0m

Content of osrm data storage (this is a NAS folder, but the same issue is on the local hard drive):

M:\osrm>dir
 Volume in drive M is NAS
 Volume Serial Number is 8263-03BB

 Directory of M:\osrm

12.09.2015  22:31    <DIR>          .
31.08.2015  06:33    <DIR>          ..
09.09.2015  17:29    31 150 304 187 planet-latest.osm.pbf
12.09.2015  22:45                20 planet-latest.osrm.timestamp
12.09.2015  20:26    25 042 652 488 planet-latest.osrm
12.09.2015  20:26         6 388 544 planet-latest.osrm.restrictions
10.09.2015  20:10    16 277 665 276 planet-latest.osrm.edges
10.09.2015  20:29    31 202 729 880 planet-latest.osrm.fileIndex
10.09.2015  18:23       118 231 318 planet-latest.osrm.names
10.09.2015  20:14     6 593 136 844 planet-latest.osrm.nodes
10.09.2015  20:29       213 792 704 planet-latest.osrm.ramIndex
12.09.2015  01:50    <DIR>          install
11.09.2015  22:55    42 737 078 200 planet-latest.osrm.hsgr
              10 File(s) 153 341 979 461 bytes
               3 Dir(s)  2 915 604 164 608 bytes free

My server.ini:

Threads = 4
IP = 0.0.0.0
Port = 5000

hsgrData=M:\osrm\planet-latest.osrm.hsgr
nodesData=M:\osrm\planet-latest.osrm.nodes
edgesData=M:\osrm\planet-latest.osrm.edges
ramIndex=M:\osrm\planet-latest.osrm.ramIndex
fileIndex=M:\osrm\planet-latest.osrm.fileIndex
namesData=M:\osrm\planet-latest.osrm.names

OSRM backend is from the latest build:

Release build (September 11 2015 11:07:16 CEST)

What I am doing wrong?

Thank you.

**Comment by danpat** [comment]
Have you tried running `osrm-routed.exe M:\osrm\planet.osrm` without using `server.ini` ?

**Comment by maximd1** [comment]
It gives me:

D:\Work\osrm\engine>osrm-routed.exe M:\osrm\planet-latest.osrm
[info] starting up engines, v4.5.0-627-gfe0fe18←[0m
[info] populating base path: M:\osrm\planet-latest.osrm←[0m
←[31m[warn] exception: .geometry not found←[0m

**Comment by danpat** [comment]
Try:
```
M:
cd osrm
D:\Work\osrm\engine\osrm-routed.exe planet-latest.osm
```

i.e. run `osrm-routed.exe` from the directory that contains `planet-latest.osrm`.  I am trying to determine whether it's a filename parsing problem for absolute paths on Windows.

**Comment by maximd1** [comment]
I see.

Two variants:

M:\osrm>D:\Work\osrm\engine\osrm-routed.exe planet-latest.osm
[info] starting up engines, v4.5.0-627-gfe0fe18←[0m
[info] populating base path: planet-latest.osm←[0m
[info] not a regular file←[0m
←[31m[warn] exception: .hsgr not found: planet-latest.osm.hsgr←[0m

M:\osrm>D:\Work\osrm\engine\osrm-routed.exe planet-latest.osrm
[info] starting up engines, v4.5.0-627-gfe0fe18←[0m
[info] populating base path: planet-latest.osrm←[0m
←[31m[warn] exception: .geometry not found←[0m

P.S. server.ini is still renamed to server.ini1.

**Comment by danpat** [comment]
Ok, so it's not a relative pathname problem.  There should be a file ending in `.geometry` there as well.  You've run both `osrm-extract` and `osrm-prepare`, right?

**Comment by maximd1** [comment]
yes, sure. I used AWS' m4.4large for that.

**Comment by daniel-j-h** [comment]
Unrelated to this problem, but a more conceptual one: if you run the pre-processing on an aws linux machine and then copy over the files to a windows machine, it is not going to work. Period.

This is first and foremost because the intermediate files contain non-portable data structures that are not suited for passing around. It could even crash if you pre-process with version x and try to run it with version y of osrm.

Don't mix the pre-processing and routed architecture, compiler, stdlib and osrm version.

**Comment by maximd1** [comment]
If I run this on Linux box it loads up to the moment when it can't allocate more memory (this is a problem with shared memory I've said before). But it works.

**Comment by daniel-j-h** [comment]
> (this is a problem with shared memory I've said before)

Do you have a link for that? What problem? That you do not have enough memory?

If you need more memory, try creating a swapfile (even though it might get slow), see this comment for how you can do it: https://github.com/Project-OSRM/osrm-backend/issues/1669#issuecomment-139188350.

**Comment by maximd1** [comment]
I did a quick test with ukraine-latest.osm.pbf (just downloaded from download.geofabrik.de). The same issue, even if I extract&prepare on Windows machine.

D:\Work\osrm\engine>osrm-routed.exe
[info] Reading options from: server.ini←[0m
[info] starting up engines, v4.5.0-627-gfe0fe18←[0m
[info] populating base path: ←[0m
[info] not a regular file←[0m
←[31m[warn] exception: .hsgr not found: .hsgr←[0m

Second - extract&prepare on Linux box. The same issue. And Linux version does NOT produce .geometry!

**Comment by daniel-j-h** [comment]
In your first comment:

> 11.09.2015 22:55 42 737 078 200 planet-latest.osrm.hsgr

So, there is a ".hsgr" file, but it still says not regular, correct? Can you make sure it is 1/ indeed not there, and 2/ can you also make sure it's on a local filesystem, not symlinked or on a network share?

**Comment by maximd1** [comment]
Yes, this file is on a network share, mapped to disk M. But when I try to put files to the local disk, the issue is still persists (see my previous comment).

**Comment by BergWerkGIS** [comment]
@maximd1 
Works for me. 
Although I tried with `Windows Server 2012 R2` and not `Windows 10`.

This is what I did (equals to a short version of https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM):

* downloaded `Release build` from http://build.project-osrm.org/
* extracted to a directory of my choice
* changed `C:\temp\stxxl` and memory in `.stxxl.txt` to point to a valid and writeable location
* copied `car.lua` -> `profile.lua`
* downloaded http://download.geofabrik.de/europe/ukraine-latest.osm.pbf directly into the extracted osrm directory (just for convience)
* `osrm-extract.exe ukraine-latest.osm.pbf`
* `osrm-prepare.exe ukraine-latest.osrm`
* `osrm-routed.exe ukraine-latest.osrm`
* `http://localhost:5000/viaroute?z=13&output=json&loc=50.450107,30.524050&loc=50.462640,30.495987&instructions=true`

![image](https://cloud.githubusercontent.com/assets/4549888/9835962/d0a1a4a0-59f3-11e5-8450-6cdfc34a6159.png)


These files were created during the process:

![image](https://cloud.githubusercontent.com/assets/4549888/9835954/2a61c0b6-59f3-11e5-9070-f8ce242126f7.png)

The binaries are built with VS2015, maybe you need to install the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by maximd1** [comment]
@BergWerkGIS Thanks, it works for me too (if I say to use .osrm file directly to osrm-routed.exe). BUT - files prepared on AWS (or other Linux box) are not working in Windows. Files, extracted and prepared in Windows, are perfectly work in Linux. One thing I noticed: looks like .osrm file extracted in Linux contains .geometry, because size of Linux' .osrm file is the ~same as .osrm+.geometry extracted in Windows. Probably, that is why osrm-routed.exe does not accept linux version of .osrm file. Is there any way to extract .geometry from linux file?

**Comment by BergWerkGIS** [comment]
It's like @daniel-j-h said [above](https://github.com/Project-OSRM/osrm-backend/issues/1679#issuecomment-139817908):

> if you run the pre-processing on an aws linux machine and then copy over the files to a windows machine, it is not going to work

The `*.osrm.*` files are not intended to be interchangeable.
You have to prepare **and** consume them with the same OS **and** same `osrm-backend` version.

BTW:
Tried with Windows 10 in the meantime and it worked, too.

**Comment by maximd1** [comment]
Okay, I see. Will raise another issue about Linux shared memory then. 

Thank you.
