### ISSUE TITLE
wrong route?

### ISSUE THREAD

**Issue by gitGOwin** [Project-OSRM/osrm-backend#1680]
Hello. There's a route here [0] that I've been trying to figure out for a few weeks no. I couldn't find any error with any of the roads. I wonder if you can tell me why it generates a long way around to the destination, instead of a "simple left." :)

Thanks!

[0] http://osrm.at/fnB

**Comment by TheMarex** [comment]
The data that is used on the demo server is pretty outdated. Working on fixing this.

**Comment by gitGOwin** [comment]
Thanks! I've been banging my head on that for a while now. :smile_cat:

**Comment by TheMarex** [comment]
Works now. :smile:

**Comment by gitGOwin** [comment]
Thanks @TheMarex !
