### ISSUE TITLE
osrm-routed does not use swap

### ISSUE THREAD

**Issue by maximd1** [Project-OSRM/osrm-backend#1681]
Hello,

I have files extracted and prepared on AWS for further processing. When I try to run them on our Linux box (CentOS 6.7, osrm-backend is the same as on AWS), osrm-routed consumes all of available physical memory and then dying after the 1-2 minutes of work. Shared memory is configured according to https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory.

Linux machine has 8GB physical memory and 100GB swap (performance is not critical).

[root@OSRM osrm-backend-0.3.7]# ./osrm-routed
[info] Reading options from: server.ini
[info] starting up engines, HEAD-HASH-NOTFOUND, compiled at Aug 11 2015, 22:58:44
[info] HSGR file:       "/mnt/pbf/planet-latest.osrm.hsgr"
[info] loading graph data
[info] loading graph from /mnt/pbf/planet-latest.osrm.hsgr
Killed

server.ini:

Threads = 2
IP = 0.0.0.0
Port = 5000

hsgrData=/mnt/pbf/planet-latest.osrm.hsgr
nodesData=/mnt/pbf/planet-latest.osrm.nodes
edgesData=/mnt/pbf/planet-latest.osrm.edges
ramIndex=/mnt/pbf/planet-latest.osrm.ramIndex
fileIndex=/mnt/pbf/planet-latest.osrm.fileIndex
namesData=/mnt/pbf/planet-latest.osrm.names

/var/log/messages:

Sep 13 15:35:43 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: osrm-routed invoked oom-killer: gfp_mask=0x280da, order=0, oom_adj=0, oom_score_adj=0
Sep 13 15:35:44 OSRM kernel: osrm-routed cpuset=/ mems_allowed=0
Sep 13 15:35:44 OSRM kernel: Pid: 1771, comm: osrm-routed Not tainted 2.6.32-573.3.1.el6.x86_64 #1
Sep 13 15:35:44 OSRM kernel: Call Trace:
Sep 13 15:35:44 OSRM kernel: [<ffffffff810d6dd1>] ? cpuset_print_task_mems_allowed+0x91/0xb0
Sep 13 15:35:44 OSRM kernel: [<ffffffff8112a5d0>] ? dump_header+0x90/0x1b0
Sep 13 15:35:44 OSRM kernel: [<ffffffff81232cbc>] ? security_real_capable_noaudit+0x3c/0x70
Sep 13 15:35:44 OSRM kernel: [<ffffffff8112aa52>] ? oom_kill_process+0x82/0x2a0
Sep 13 15:35:44 OSRM kernel: [<ffffffff8112a991>] ? select_bad_process+0xe1/0x120
Sep 13 15:35:44 OSRM kernel: [<ffffffff8112ae90>] ? out_of_memory+0x220/0x3c0
Sep 13 15:35:44 OSRM kernel: [<ffffffff8113786c>] ? __alloc_pages_nodemask+0x93c/0x950
Sep 13 15:35:44 OSRM kernel: [<ffffffff8117035a>] ? alloc_pages_vma+0x9a/0x150
Sep 13 15:35:44 OSRM kernel: [<ffffffff81152b1d>] ? handle_pte_fault+0x73d/0xb20
Sep 13 15:35:44 OSRM kernel: [<ffffffff810537b7>] ? pte_alloc_one+0x37/0x50
Sep 13 15:35:44 OSRM kernel: [<ffffffff8118be29>] ? do_huge_pmd_anonymous_page+0xb9/0x3b0
Sep 13 15:35:44 OSRM kernel: [<ffffffff81153199>] ? handle_mm_fault+0x299/0x3d0
Sep 13 15:35:44 OSRM kernel: [<ffffffff811533fa>] ? __get_user_pages+0x12a/0x430
Sep 13 15:35:44 OSRM kernel: [<ffffffff81155130>] ? __mlock_vma_pages_range+0xb0/0x200
Sep 13 15:35:44 OSRM kernel: [<ffffffff81156e6f>] ? vma_adjust+0x11f/0x5e0
Sep 13 15:35:44 OSRM kernel: [<ffffffff81155318>] ? mlock_vma_pages_range+0x98/0xa0
Sep 13 15:35:44 OSRM kernel: [<ffffffff81159192>] ? mmap_region+0x302/0x5b0
Sep 13 15:35:44 OSRM kernel: [<ffffffff81159775>] ? do_mmap_pgoff+0x335/0x380
Sep 13 15:35:44 OSRM kernel: [<ffffffff8114889a>] ? sys_mmap_pgoff+0x7a/0x2d0
Sep 13 15:35:44 OSRM kernel: [<ffffffff81012459>] ? sys_mmap+0x29/0x30
Sep 13 15:35:44 OSRM kernel: [<ffffffff8100b0d2>] ? system_call_fastpath+0x16/0x1b
Sep 13 15:35:44 OSRM kernel: Mem-Info:
Sep 13 15:35:44 OSRM kernel: Node 0 DMA per-cpu:
Sep 13 15:35:44 OSRM kernel: CPU    0: hi:    0, btch:   1 usd:   0
Sep 13 15:35:44 OSRM kernel: CPU    1: hi:    0, btch:   1 usd:   0
Sep 13 15:35:44 OSRM kernel: Node 0 DMA32 per-cpu:
Sep 13 15:35:44 OSRM kernel: CPU    0: hi:  186, btch:  31 usd:   5
Sep 13 15:35:44 OSRM kernel: CPU    1: hi:  186, btch:  31 usd:   0
Sep 13 15:35:44 OSRM kernel: Node 0 Normal per-cpu:
Sep 13 15:35:44 OSRM kernel: CPU    0: hi:  186, btch:  31 usd:  49
Sep 13 15:35:44 OSRM kernel: CPU    1: hi:  186, btch:  31 usd:   0
Sep 13 15:35:44 OSRM kernel: active_anon:680 inactive_anon:714 isolated_anon:0
Sep 13 15:35:44 OSRM kernel: active_file:19 inactive_file:21 isolated_file:0
Sep 13 15:35:44 OSRM kernel: unevictable:1910053 dirty:0 writeback:730 unstable:0
Sep 13 15:35:44 OSRM kernel: free:25821 slab_reclaimable:2255 slab_unreclaimable:15376
Sep 13 15:35:44 OSRM kernel: mapped:1547 shmem:21 pagetables:4147 bounce:0
Sep 13 15:35:44 OSRM kernel: Node 0 DMA free:15668kB min:124kB low:152kB high:184kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15272kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:0kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
Sep 13 15:35:44 OSRM kernel: lowmem_reserve[]: 0 2896 7946 7946
Sep 13 15:35:44 OSRM kernel: Node 0 DMA32 free:44792kB min:24584kB low:30728kB high:36876kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:56kB unevictable:2648392kB isolated(anon):0kB isolated(file):0kB present:2965572kB mlocked:111900kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:188kB slab_unreclaimable:588kB kernel_stack:0kB pagetables:2204kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no
Sep 13 15:35:44 OSRM kernel: lowmem_reserve[]: 0 0 5050 5050
Sep 13 15:35:44 OSRM kernel: Node 0 Normal free:42824kB min:42868kB low:53584kB high:64300kB active_anon:2720kB inactive_anon:2856kB active_file:76kB inactive_file:28kB unevictable:4991820kB isolated(anon):0kB isolated(file):0kB present:5171200kB mlocked:74076kB dirty:0kB writeback:2920kB mapped:6188kB shmem:84kB slab_reclaimable:8832kB slab_unreclaimable:60916kB kernel_stack:1568kB pagetables:14384kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:8768 all_unreclaimable? yes
Sep 13 15:35:44 OSRM kernel: lowmem_reserve[]: 0 0 0 0
Sep 13 15:35:44 OSRM kernel: Node 0 DMA: 3*4kB 1*8kB 4*16kB 3*32kB 2*64kB 0*128kB 0*256kB 0*512kB 1*1024kB 1*2048kB 3*4096kB = 15668kB
Sep 13 15:35:44 OSRM kernel: Node 0 DMA32: 32*4kB 19*8kB 12*16kB 8*32kB 5*64kB 10*128kB 22*256kB 16*512kB 14*1024kB 3*2048kB 2*4096kB = 44824kB
Sep 13 15:35:44 OSRM kernel: Node 0 Normal: 231*4kB 86*8kB 35*16kB 79*32kB 164*64kB 64*128kB 16*256kB 6*512kB 8*1024kB 2*2048kB 0*4096kB = 42844kB
Sep 13 15:35:44 OSRM kernel: 2337 total pagecache pages
Sep 13 15:35:44 OSRM kernel: 724 pages in swap cache
Sep 13 15:35:44 OSRM kernel: Swap cache stats: add 2899, delete 2175, find 0/1
Sep 13 15:35:44 OSRM kernel: Free swap  = 68082096kB
Sep 13 15:35:44 OSRM kernel: Total swap = 68093688kB
Sep 13 15:35:44 OSRM kernel: 2097136 pages RAM
Sep 13 15:35:44 OSRM kernel: 108419 pages reserved
Sep 13 15:35:44 OSRM kernel: 4827 pages shared
Sep 13 15:35:44 OSRM kernel: 1956983 pages non-shared
Sep 13 15:35:44 OSRM kernel: [ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj name
Sep 13 15:35:44 OSRM kernel: [  494]     0   494     2868       66   1     -17         -1000 udevd
Sep 13 15:35:44 OSRM kernel: [ 1156]     0  1156     2280       70   1       0             0 dhclient
Sep 13 15:35:44 OSRM kernel: [ 1211]     0  1211     6899      121   0     -17         -1000 auditd
Sep 13 15:35:44 OSRM kernel: [ 1233]     0  1233    63854      155   1       0             0 rsyslogd
Sep 13 15:35:44 OSRM kernel: [ 1403]     0  1403    16556       84   0     -17         -1000 sshd
Sep 13 15:35:44 OSRM kernel: [ 1482]     0  1482    20217      222   1       0             0 master
Sep 13 15:35:44 OSRM kernel: [ 1489]    89  1489    20280      211   1       0             0 qmgr
Sep 13 15:35:44 OSRM kernel: [ 1496]     0  1496    29215      145   0       0             0 crond
Sep 13 15:35:44 OSRM kernel: [ 1509]     0  1509     1016      122   1       0             0 mingetty
Sep 13 15:35:44 OSRM kernel: [ 1511]     0  1511     1016      122   1       0             0 mingetty
Sep 13 15:35:44 OSRM kernel: [ 1513]     0  1513     1016      122   1       0             0 mingetty
Sep 13 15:35:44 OSRM kernel: [ 1515]     0  1515     1016      122   1       0             0 mingetty
Sep 13 15:35:44 OSRM kernel: [ 1519]     0  1519     3100       97   0     -17         -1000 udevd
Sep 13 15:35:44 OSRM kernel: [ 1520]     0  1520     3100       97   0     -17         -1000 udevd
Sep 13 15:35:44 OSRM kernel: [ 1521]     0  1521     1016      122   0       0             0 mingetty
Sep 13 15:35:44 OSRM kernel: [ 1523]     0  1523     1016      122   0       0             0 mingetty
Sep 13 15:35:44 OSRM kernel: [ 1710]    89  1710    20237      211   0       0             0 pickup
Sep 13 15:35:44 OSRM kernel: [ 1723]     0  1723    24994      391   0       0             0 sshd
Sep 13 15:35:44 OSRM kernel: [ 1727]     0  1727    27076      268   1       0             0 bash
Sep 13 15:35:44 OSRM kernel: [ 1743]     0  1743    31713      570   1       0             0 mc
Sep 13 15:35:44 OSRM kernel: [ 1745]     0  1745    27076      269   0       0             0 bash
Sep 13 15:35:44 OSRM kernel: [ 1771]     0  1771 10443752  1910103   0       0             0 osrm-routed
Sep 13 15:35:44 OSRM kernel: Out of memory: Kill process 1771 (osrm-routed) score 70 or sacrifice child
Sep 13 15:35:44 OSRM kernel: Killed process 1771, UID 0, (osrm-routed) total-vm:41775008kB, anon-rss:7634192kB, file-rss:6220kB
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.
Sep 13 15:35:44 OSRM kernel: Purging GPU memory, 0 bytes freed, 24576 bytes still pinned.

Please help.

Thank you.

**Comment by TheMarex** [comment]
@maximd1 sorry this will just not work. 8GB is ridiculous for the whole planet. You should get an instance with 32GB at least (better go for >40GB), or use a smaller dataset. Even if it would be using all your swap space it would be completely unusable since there is random access on certain memory blocks.
