### ISSUE TITLE
Add libraries for Ubuntu 14.04 compilation

### ISSUE THREAD

**Issue by manelclos** [Project-OSRM/osrm-backend#1683]
Hi,

Following the compilation instructions on
https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu

the "cmake .." fails both for osmpbf and protobuf libraries

Adding "libosmpbf-dev libprotobuf-dev" packages to the apt-get step fixes it.

**Comment by daniel-j-h** [comment]
Please see: https://github.com/Project-OSRM/osrm-backend/issues/1628

Summary: we no longer need those requirements in `4.8.0`, thus we ripped them completely out of the buildsystem and documentation. Unfortunately, the planned release of `4.8.0` at the beginning of September was delayed, introducing a mismatch between what `master` and `develop` requires.

If you take a look e.g. at the [Wiki's history](https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu/_history) you can still see the old revisions.

There is a `4.8.0-rc` in testing right now. Once we make this release official and merge the `develop` branch into `master`, the instructions are correct again.

Sorry for the inconvenience.
