### ISSUE TITLE
Replace internal JSON serialization code with RapidJSON

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1692]
Placeholder ticket to look at:  https://github.com/miloyip/rapidjson
It's header-only.

Not a huge win, but less code of our own to maintain.  Should be included via `third_party`.

**Comment by daniel-j-h** [comment]
A quick note on this one: while RapidJSON is a solid choice, maybe our use case is simple enough to just make use of [Boost.PropertyTree](http://www.boost.org/doc/libs/1_59_0/doc/html/property_tree.html).

I used it a year ago for a small toy project that extracts and groups warnings from Clang's `-Weverything` flag --- [here](https://github.com/daniel-j-h/claudia/blob/17b2d4c68f47809fb041084121c2bfe848618603/src/parser.cc#L57-L66) is an example of how the code looks like.

[This](http://www.boost.org/doc/libs/1_59_0/doc/html/property_tree/reference.html#header.boost.property_tree.json_parser_hpp) is the documentation for the JSON parser (read, write functions). I think there was an issue with the default property tree typedef to always use strings, not sure about that though.

**Comment by TheMarex** [comment]
I think the JSON code is already as minimal as possible. The variant based implementation allows us to convert it to V8 objects every efficiently: We never actually generate strings.
The string serialization is only used in `osrm-routed`.

**Comment by daniel-j-h** [comment]
In case we keep it, we (I?) should at least review it and make it more robust.

For example, this is the first thing I saw when opening the variant typedef you mentioned:
[undefined behavior](https://github.com/Project-OSRM/osrm-backend/blob/a6b44a14709bf760425cfef288d1f14a6914f569/include/osrm/json_container.hpp#L52) when passing a `nullptr`.

**Comment by daniel-j-h** [comment]
What I realized after the recent mailinglist post on how to use the JSON response on the library's user call site is this: we include `json_container.hpp` in the public library, resulting in the heterogeneous [Value](https://github.com/Project-OSRM/osrm-backend/blob/a6b44a14709bf760425cfef288d1f14a6914f569/include/osrm/json_container.hpp#L76-L82) sum type exposing the `mapbox::util::variant` implementation detail.

That is, a user working with the OSRM JSON response object has to use the `mapbox/variant` features for creating a visitor and applying it to the instance.

This makes it hard to modify the implementation as it would be a breaking API change.

On the other hand, returning a type-safe JSON response always requires us to expose some sort of variant type.

**Comment by TheMarex** [comment]
Having a nice C++ interface is not really a priority. Application code that needs this can be written as a plugin and for everything else there are the node bindings. It is almost always the wrong approach to use libosrm directly.

**Comment by daniel-j-h** [comment]
Objections against ripping out `third_party/variant` and just using `boost::variant` in the two remaining places (after my `use_boost` branch is merged) in osrm? This will also affect the bindings, but should be an easy drop in replacement.

**Comment by TheMarex** [comment]
Closing here as we stay with our own serialization for now.
