### ISSUE TITLE
Via points in the match instructions

### ISSUE THREAD

**Issue by agruss** [Project-OSRM/osrm-backend#1694]
The match-service creates lots of viapoints with the instructions parameter.

Example:
Request: 
``match?locs=ge{bbBot{pM_v@oi@_mBolA{@sDcGoFgJSkRsDsNgOcQk\{EkCwLcGwLwB_IbBkMoAs]wQ{E_IcG{h@cj@gzAkRoPw[kf@kWwVoPw[c`@_l@gEoKsb@cj@_]oZ{JoF_N{O_{@os@_v@cVoPwBsq@w[gJ_Igc@gTgJkH_b@cVwe@cQsXsIwQoA_]kM_jAkWsSwB{^_No}@{Tco@cLgJ_Dcj@_Doi@kHco@wBgh@f@sNbBwL?wGcBwe@SwQg@gTsDwGoF{ERkCoASgE?wcAwBcBgESsDsDkMf@cLjCgYvLcGf@sDkHcB{dB?sDbBSwBf@zE?&instructions=true``

Result:
``"instructions":[["10","Gartenstraße \/ K 8",116,0,6,"115m","N",352,1],
["9","Gartenstraße \/ K 8",219,7,84,"218m","N",20,1],
["9","Gartenstraße \/ K 8",6,14,8,"5m","NE",33,1],
["9","Gartenstraße \/ K 8",17,15,12,"17m","NE",32,1],
["9","Gartenstraße \/ K 8",17,16,16,"17m","NE",32,1],
["9","Gartenstraße \/ K 8",33,17,24,"33m","NE",30,1],
["9","Gartenstraße \/ K 8",33,20,14,"32m","NE",28,1],
["9","Gartenstraße \/ K 8",42,21,7,"42m","NE",27,1],
["9","Gartenstraße \/ K 8",13,23,27,"13m","NE",23,1],
["9","Gartenstraße \/ K 8",26,27,7,"26m","N",21,1],...``

I think the viapoints are a little bit too much, especially when you're displaying them on a map (you can only see the viapoints in this case).

**Comment by TheMarex** [comment]
It creates a via point for every given input coordinate which is consistent with the behavior of all other plugin that we use. If this does not work for your application you should try to fix it on that level.
