### ISSUE TITLE
How to run Europe on 8GB?

### ISSUE THREAD

**Issue by maximd1** [Project-OSRM/osrm-backend#1697]
Hi everyone,

please advice how to run Europe on machine A with 8GB of RAM. I have another one Linux box B where it is running with following characteristics:

28012 root      20   0 8482m 7.9g 6228 S  0.0 51.3   0:31.36 osrm-routed

So, in theory I can play with Europe on the machine A, right? No other applications there, only clean OS.

Thank you.

**Comment by danpat** [comment]
If you don't have enough RAM, make sure you have lots of swap space.  Performance won't be great, but it will work.

`osrm-prepare` for the whole planet requires about 115GB of memory to process, and it takes about 60GB to run `osrm-routed`.  I have not run the numbers for just an EU extract, but it will be less than that.
