### ISSUE TITLE
Split and parallelize Cucumber tests onto several Travis CI VMs

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#1699]
Running the full Cucumber test suite on Travis CI takes really really long, e.g. see the small test @freenerd added yesterday, but had to wait hours for Travis CI to give the ok.

There is a way to split Cucumber tests on several VMs in order to run them in parallel.
This is described [in detail here](http://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-RSpec%2C-Cucumber-and-Minitest-on-multiple-VMs).

@emiltin if you have some time to spare, do you think you can take a look at it, if it's worth the effort at all? I think you have the most experience with the Cucumber test suite around here. If you think it's not worth the effort, that's also fine, then just close this issue :).

**Comment by emiltin** [comment]
I don't have experiene with knapsack or parallelizing cucumber tests across vms, but it it does what it says then it should make things faster.

other ideas:
- benchmark scenarios to see where time is being spend
- store cached test files between test runs (different server?)
- #884
- reduce the minimum storage/memory sizes, so less is allocated/free when just running tests

**Comment by emiltin** [comment]
parallelizing would require some changes to the way osrm is currently launched, since we're currently launching it only once for all tests. that would break if we're on multiple vms.

**Comment by daniel-j-h** [comment]
> store cached test files between test runs (different server?)

Caching arbitrary directories is [quite easy](https://github.com/daniel-j-h/cpp-travis-setup/blob/83f3817704164f943dc743cccc684bbe38fb5342/.travis.yml#L5-L8) with the new Travis container infrastructure. The hard question is cache-invalidation on breaking changes.

> build a native ruby binding for osrm, to avoid launching prcesseses

Unfortunately, we do not provide a C library (although there is the unofficial [osrm-c](https://github.com/tdihp/osrm-c)), so I guess this would be rather involving.


> benchmark scenarios to see where time is being spend, then optimize

That's a good idea anyway! Hmm maybe for a start we could manually split the tests based on tags (determined by tests on which tags require the longest) on a fixed and low number of Travis containers, by setting and dispatching on appropriate environment variables [as we do for release and debug builds](https://github.com/daniel-j-h/cpp-travis-setup/blob/83f3817704164f943dc743cccc684bbe38fb5342/.travis.yml#L119).

**Comment by emiltin** [comment]
caching is quite robust since:
- it caches the generation of .osm files from cucumber scenarios files, which does not depend on osrm implementation. cache invalidation is based on sha1 hashing the input data
- it cached preprocessed files based on sha1 of the relevant bins, input data and lua profiles. a change in osrm-extract or osrm-prepare will therefore trigger the relevant reprocessing steps.

**Comment by daniel-j-h** [comment]
This sounds great!
So all we would have to do is cache the `test` directory and we're good to go, correct?

I will write this on my todo list:
- [ ] try out caching the `test` directory
- [ ] split work onto several nodes based on tags

**Comment by emiltin** [comment]
i think so yes. not sure if there will be issues with parallelization.
one thing to consider is occasionally cleaning up old cached files. everytime the code changes, old caches files will be left behind. eventually they will take up considerable amount of space.

**Comment by daniel-j-h** [comment]
Is there a way to automate this on the cucumber side? I'm currently experimenting with caching in Travis' new container infrastructure and the only way to [clear caches](http://docs.travis-ci.com/user/caching/#Clearing-Caches) is somewhat manually.

**Comment by emiltin** [comment]
we could keep track of what files we use from cucumber, then after each run delete all other cache files. or delete all files once per week/month.

**Comment by daniel-j-h** [comment]
Caching was implemented in https://github.com/Project-OSRM/osrm-backend/pull/2449. Closing here as not actionable.
