### ISSUE TITLE
Strange route is being generated

### ISSUE THREAD

**Issue by SamSalman** [Project-OSRM/osrm-backend#1700]
Hello,

OSRM api is generating totally wrong routes, please see the attached screen shots:

![screenshot from 2015-09-22 10 33 20](https://cloud.githubusercontent.com/assets/3371099/10013159/7d7cf240-6117-11e5-90f3-04f9ebfad547.png)
![screenshot from 2015-09-22 10 33 03](https://cloud.githubusercontent.com/assets/3371099/10013160/7d808194-6117-11e5-91eb-ae2c98b37bf9.png)

I also tested in OSRM project website and its also generating the same result as show in the screen shot:
Here are the two coordinates that are used: 
Start_coordinates: [
60.3440953,
25.5111328
]

End_coordinates: [
60.2206872,
25.187002
]

Thank you in advance.

**Comment by BergWerkGIS** [comment]
Seems to be a connectivity data error in OSM in the harbour area.

Even this results in a route like in the images above:

![image](https://cloud.githubusercontent.com/assets/4549888/10013486/20b7ba86-6112-11e5-903f-7904ee4e1b6d.png)

![image](https://cloud.githubusercontent.com/assets/4549888/10013419/a06e4156-6111-11e5-8db4-2587ed5ce7ea.png)

**Comment by SamSalman** [comment]
@BergWerkGIS Thanks for your quick response. Is there any solution for that since no one want to go in a route where they have to travel 1827 KMs :D whereas actual route is of few KMs.

Thanks

**Comment by BergWerkGIS** [comment]
This radiation detector (https://www.openstreetmap.org/node/1136468204) blocks routing through this area (thanks @planemad for finding out).

/cc @TheMarex

**Comment by BergWerkGIS** [comment]
@SamSalman props to @planemad who changed the attributes of the monitoring station in the Open Street Map data:

![image](https://cloud.githubusercontent.com/assets/4549888/10046762/ef02aa2e-620a-11e5-82e9-5ef458284d91.png)

With fresh OSM data your routing should now work as expected.

**Comment by SamSalman** [comment]
@BergWerkGIS Thanks for your comments. But I just tested and it still generate the same result. Also I tested in OSRM project and open street map website (https://www.openstreetmap.org/directions?engine=osrm_car&route=60.353%2C25.520%3B60.220%2C25.187#map=6/57.398/21.995), they give the same false route. Would please have a look it again. Thanks in advance.

**Comment by planemad** [comment]
@SamSalman it takes around 6-12 hours from OSRM to reindex the data, the new route should reflect within a day.

**Comment by daniel-j-h** [comment]
@SamSalman @planemad note that the openstreetmap.org router for OSRM sends its queries against the project-osrm.org demo server, which currently has stale data and does not run on the latest release.

We have a new demo server ready, we're just waiting for the switch over so that the domain points at it. Until then, you won't see updates at all.

**Comment by SamSalman** [comment]
@daniel-j-h Thank you for clarifying it. It would be great if you drop a message here when the server gets ready so that I can perform my testing. I really appreciate a time you guys spent to resolve discussed issue.

**Comment by BergWerkGIS** [comment]
@SamSalman looks good now:

![image](https://cloud.githubusercontent.com/assets/4549888/10161754/8d1c03aa-66a6-11e5-9594-5a0725953f38.png)

Also check out the new design of http://map.project-osrm.org/

**Comment by SamSalman** [comment]
@BergWerkGIS Its excellent now. 
Thanks alot.
