### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by maximd1** [Project-OSRM/osrm-backend#1703]
Hello,

just a quick one - is there any support of modern GPUs (AMD or NVIDIA) in the osrm-extract&prepare? Would it be significant benefit in calculations if osrm-extract&prepare have this support enabled?

For example, I have AMD A10-7700K with 4 CPU cores & 6 GPU cores. It would be brilliant to include GPUs to extract&preparation process.

What do you think?

Thank you.

**Comment by danpat** [comment]
It has been discussed, and there is some potential there, but so far, nobody with the right expertise has stepped forward to give it a go.

`osrm-extract` is mostly IO bound, so will unlikely benefit much.  If you have some expertise in this area, we'd love to discuss :-)

**Comment by TheMarex** [comment]
The pre-processing stage heavily relies on sorting + transferring large data sets. Sorting relies heavily on branch instructions. GPUs in general handle those rather badly (each shade unit has a shared instruction pointer, thus branch handling is awkward).

GPUs shine if you need to calculate simple mathematical operations en-mass that don't depend on each other (or can be pipe-lined). Sadly this problem set is not one of those.
