### ISSUE TITLE
Shortest path through specified points (that are unordered)

### ISSUE THREAD

**Issue by vladim1** [Project-OSRM/osrm-backend#1704]
I have a source and destination points (A and B) and a few intermediate points (C, D, E, F, J...) that an object has to visit.
Is there an opportunity to build a route that will calculate an optimal (shortest) route through this points if there is no order of visiting points?
As I understand Dijkstra algorithm can be used to resolve this issue

**Comment by daniel-j-h** [comment]
This sounds similar to the [Traveling Salesman Problem]( https://en.wikipedia.org/wiki/Travelling_salesman_problem). With the latest v4.8.0 release we expose the [trip plugin](https://github.com/Project-OSRM/osrm-backend/blob/8f6fc0146ba76d34d20c5b7a87b75249bbb12b82/plugins/trip.hpp) that can solve exactly those questions. The API looks like the following:

    http://localhost:5000/trip?loc=52.51642978796417,13.441085815429688&loc=52.51601193890388,13.448638916015625

/cc @chaupow

**Comment by vladim1** [comment]
@daniel-j-h  Thanx for the response. 
And yes, Traveling Salesman Problem is very similar to specified issue except the fact, that the destination point differs from the start point. But I need a case with Traveling Salesman Problem also.
Is there any information, when the version 4.8.0 is going to be released? As I can see all issues are already closed for this milestone.

**Comment by emiltin** [comment]
4.8.0 is is already released.

**Comment by vladim1** [comment]
Where can I find more documentation about the trip plugin?
BTW, I have tried to use the link on the demo server and it didn't work.
```
http://router.project-osrm.org/trip?loc=52.51642978796417,13.441085815429688&loc=52.51601193890388,13.448638916015625
```
But then I have tried to use the link on localhost and I have gotten some result. but I don't know how to use it. So I am looking for more docs.

**Comment by daniel-j-h** [comment]
@TheMarex just added initial docs for the trip plugin to the Wiki, take a look:
https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#service-trip

The demo router at project-osrm.org currently runs on stale data and does not yet have the latest release. Bringing @freenerd into this ticket: he is currently working on resolving this; should be done in the next days.

**Comment by vladim1** [comment]
OK, thanks. This is a great announcement!!

**Comment by freenerd** [comment]
The project-osrm.org demo server should be fixed soon again (run on develop branch with recent OSM dataset). Only waiting on @DennisOSRM here to switch the domain to new infrastructure.

**Comment by TheMarex** [comment]
This should be good now.
