### ISSUE TITLE
Fast method for updating edge weights from alternate speed/travel time data sources

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1709]
We're looking at ways to ingest data from real-time traffic sources and update edge weights to affect routing.  @TheMarex and I discussed some of the technicalities by voice this morning, this ticket is to capture what we talked about and create a forum for discussion before I go ahead and implement it.

# What we want to do
We want to update edge weights across the road graph when fed data from a variety of sources

# Why it's hard
 - We need to re-run `osrm-prepare` (specifically, the contraction phase) if the edge weights are changed
 - We want to avoid re-running the fairly expensive early parts of `osrm-extract`
 - To minimize turnaround times, we only want to re-run the parts we absolutely have after to we import the latest traffic data
 - Modifying edge compression could lead to an increase in memory usage, which we really want to avoid
 - Identifying the correct edges to update after data has been converted between structures a few times is currently impossible

# What we came up with
We will modify the workflow and insert two new steps.  It will now look like this:

`osrm-extract`
  - Parse OSM
  - Construct node-based graph
  - Compress edges
  - Perform edge expansion **NEW** (moved here from `osrm-prepare`)
  - Save segment-to-expanded-edge lookup table  **NEW**.  "segment" means a coordinate pair that are joined by a navigable edge in the original OSM data source, i.e. `nodeA -> nodeB`

`osrm-update-edges`  **NEW** optional phase to quickly update edge weights
  - Modify edge-expanded graph weights using segment-to-expanded-edge mapping file
  - This may or may not be a separate tool to `osrm-prepare`, TBD.

`osrm-prepare`
  - ~~Perform edge expansion~~ Moved to `osrm-extract`
  - Load edge-expanded graph
  - Contract graph

`osrm-routed`
  - Unchanged

With this in place, it will be possible to quickly update edge weights on a partially processed datafile.  I expect `osrm-update-edges` should take < 60s to update a full-sized planet, it will be a linear-ish operation.  Combined with new `-k` parameter to `osrm-prepare`, should enable processing turnaround times fast enough to ingest traffic data and get usable data back to users of the service in enough time to be useful.  We're aiming for total turnaround speeds of <15 minutes for USA sized road networks (tunable).

The segment lookup table will look something like this:

Expanded EdgeID | OSM From NodeID | OSM To NodeID | Length (metres)
---|---|---|---
12376 | 1234 |  3423 | 342
12376 | 3423 |  8237 | 983
12376 | 8237 | 8732 | 22

This file will be quite large, there will be a row for every routable segment in the road graph.  I expect many GB for a full-planet sized dataset.

We store the length because we expect incoming data to most likely be `speed` values, and we need to calculate total expanded edge travel time.

The work then becomes coming up with traffic data values -> segment mappings.  This, unfortunately, will be left as an exercise for the reader (most traffic data sources are proprietary).

# Future considerations
We have plans to implement MLD (Multi-Level Dijkstra) as an alternative for the current CH (Contraction Heiracy) approach.  This will allow faster post-traffic-update processing and lower memory usage, at the expense of query time.  The approach above, so far, should be compatible with that, we are just beginning to prototype MLD.  We will be keeping the CH function to support high-volume query features, like the `trip` plugin.

**Comment by TheMarex** [comment]
> Compress edges
> Perform edge expansion NEW (moved here from osrm-prepare)

Just keep in mind that we need to retain a mapping across these two steps. That means:
- keep the compressed edge buckets around
- for each generated edge expaneded edge, lookup geometry id
- extract node list from geometry bucket
- re-name node ids to original OSM node id
- compute length of the segment 
- save that to the mapping table

**Comment by danpat** [comment]
The edge-expansion phase has been moved into `osrm-extract`.  This means that `osrm-prepare` is now only doing graph contraction.  I'm starting work on creating lookup files for edge->segment values now.

**Comment by frodrigo** [comment]
The project of supporting MLD is still alive ?
I'm interested in the runtime evaluation function (mainly to avoid areas at all or slow down)

**Comment by danpat** [comment]
This was implemented for https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

@frodrigo we frequently discuss alternative graph structures that might give us some more flexibility.  There's a lot of externally-visible (i.e. guidance/api) work happening at the moment, but once that settles, focus will return to core engine improvements.
