### ISSUE TITLE
Strange routing with a via point 

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#1714]
Picked up some loopy routing suggestions when playing with via points

![untitled](https://cloud.githubusercontent.com/assets/126868/10161539/70c894fe-66c2-11e5-86de-e2a3d54524d1.gif)
http://map.project-osrm.org/?z=16&center=36.836956%2C-87.473198&loc=36.839266%2C-87.479936&loc=36.837729%2C-87.480783&loc=36.834397%2C-87.474153&hl=en&ly=&alt=&df=&srv=

Not sure what going on here since moving that via point should not have made any difference to the suggested route.

cc @TheMarex

**Comment by emiltin** [comment]
looks similar to other old issues e.g. #412, #726.

**Comment by MoKob** [comment]
might be related to https://github.com/Project-OSRM/osrm-backend/pull/1869

**Comment by MoKob** [comment]
Seems to be fixed by now. At least the example above works.
