### ISSUE TITLE
traffic signals very close to start/end point?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#172]
signal penalty tests shows one peculiarity: if you start right on top of a signal node, it might, or might not, trigger the penalty.

for example, if a way abc has a signal at b, then going from b to c causes a delay, but going from b to a doesn't. there's a test that demonstrates this in features/penalty.feature:46: "Scenario: Starting or ending at a traffic signal should not incur a delay".

from a technical perspective it's natural, since when you start right at a junction, what street osrm will pick, is in practice undefined. but from a users perspective, it might be confusing.

if the current behaviour is not desired, a solution might be to ignore traffic signals if they're very close (say 1 or 5m) to the start/end point.

**Comment by TheMarex** [comment]
Ignoring traffic signals on start nodes will just not work with the current graph model. This is not actionable sadly. Closing.
