### ISSUE TITLE
Advisory speed limits

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-backend#1722]
The car profile should account for [advisory speed limits](https://en.wikipedia.org/wiki/Advisory_speed_limit) ( [`maxspeed:advisory`](http://taginfo.openstreetmap.org/keys/maxspeed%3Aadvisory), `maxspeed:advisory:forward`, `maxspeed:advisory:backward`) in addition to legal speed limits (`maxspeed`). Advisory speed limits are relevant for highway off-ramps and sharp turns on rural roads that have high legal speed limits.

Even better would be penalties imposed automatically on sharp turns: #860.

/cc @daniel-j-h

**Comment by danpat** [comment]
@1ec5 Are these typically tagged only on short ways?  Where they exist on a long way, are people splitting the ways appropriately for the speed advisory zone?

**Comment by emiltin** [comment]
turn penalties was recently activated for the car profile with b3822d58

**Comment by 1ec5** [comment]
I spot-checked the `maxspeed:advisory` tags in OSM, particuarly in the Los Angeles and Toronto areas, where the tag is extremely common. When used on curved highway ramps (slip roads) in cloverleaf interchanges, the tag is applied to the entire ramp. Otherwise, the tag is used on an individual curve in a road, with the road appropriately split right around the curve. In all cases, the tag seems to match where you’d expect to see advisory speed limit signage (at least according to U.S./Canadian engineering standards).

**Comment by TheMarex** [comment]
@1ec5 Very valuable insight. These kind of signs have been abolished in Germany, curved roads are usually marked with lower `maxspeed` signs here (+ warning sign that the road is curved).

Should be an easy change. To the car profile. :+1:

**Comment by TheMarex** [comment]
Implemented.
