### ISSUE TITLE
Permission issue for osrm-datastore + libosrm multi-user setup (e.g. root vs user)

### ISSUE THREAD

**Issue by hoerup** [Project-OSRM/osrm-backend#1724]
If you try to run osrm-datastore as non-root user, it dies on a exception.

Maybe it should start with testing that the calling user has the necesarry permissions ?

$ osrm-datastore
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  Permission denied
Aborted

**Comment by daniel-j-h** [comment]
Could you trace back from where the exception is thrown? (Debug build + GDB)

It might be that we just have to modify some [permissions](http://www.boost.org/doc/libs/1_55_0/doc/html/boost/interprocess/permissions.html) on our side.

**Comment by daniel-j-h** [comment]
There's nothing we can do without further details.
Please try again on master and / or provide more context.

**Comment by jcoupey** [comment]
I'm getting the same exception when trying to _access_ shared memory with libosrm. This only happens when the client code is run by a different user than the one that launched `osrm-datastore`.

I'm not sure this is actually a bug, it looks like a normal behaviour related to the permissions settings (see http://stackoverflow.com/questions/8758896/setting-permission-for-shared-memory-created-by-boost).

**Comment by daniel-j-h** [comment]
/cc @TheMarex this is following up on the conversation on IRC the other day.
System is Ubuntu 16.04, exception comes from:
 
https://github.com/Project-OSRM/osrm-backend/blob/532fda267f48af273d75c934240fc8901c06c03d/src/tools/store.cpp#L103-L107

**Comment by jcoupey** [comment]
Just adding another comment to make things more clear regarding the previous IRC discussion.

My initial problem was not to be able to run `osrm-datastore` (and any code relying on libosrm) as a non-root user ([warn] caught exception: Permission denied). This is now fixed for me, not really sure how, but I found the exception disappeared after my next reboot.

So it all comes down to  this: the actual setting seems to require that `osrm-datastore` and any code using libosrm are run on behalf of the same user.

**Comment by danpat** [comment]
On Unix, shared memory blocks have ownership, just like files.

If, for some reason, you ran `osrm-datastore` as root, leaving root-owned shared memory blocks lying around, then later tried to run it as a regular user, then `Permission denied` is the expected response.

We could probably improve the error handling here (check for permissions on existing SHM blocks), but it's not "fixable" without becoming the root user and removing those shared memory blocks.

**Comment by jcoupey** [comment]
@danpat thanks, this indeed explains the `Permission denied` I was experiencing and why it vanished at reboot. I must have run `osrm-datastore` as root in the first place (maybe before I managed to configure user limits right). My mistake then.

The ownership does have another impact though. If I run `osrm-datastore` as user `osrm`, I can check ownership all right:

```bash
$ ls -hal /dev/shm/
total 16K
drwxrwxrwt  2 root root  120 Jun 21 09:55 .
drwxr-xr-x 20 root root 4.3K Jun 17 14:34 ..
-rw-r--r--  1 osrm osrm  104 Jun 21 09:50 no_running_queries
-rw-r--r--  1 osrm osrm   32 Jun 21 09:50 sem.pending_update
-rw-r--r--  1 osrm osrm   32 Jun 21 09:50 sem.query
-rw-r--r--  1 osrm osrm   32 Jun 21 09:50 sem.update
```

but then another regular user is unable to make use of shared memory via libosrm.

```bash
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  Permission denied
```

As I said before, not sure if you will consider this a bug or a normal behaviour.

**Comment by danpat** [comment]
This is normal behavior.  But, we could fix it by adding options to osrm-datastore for setting the uid/gid/permissions on the block when it's created.

That could get weird if you call it twice and forget the flags the second time...

Maybe play with http://linuxplayer.org/2013/04/change-shared-memory-ownership-and-permission and see if that solves your problem first?

**Comment by danpat** [comment]
Ah, I see the problem.

Unfortunately the *reader* process needs write access - it's responsible for swapping datasets for the hot swap feature.

This is not good design and should be changed, but this whole part of the codebase is pretty ugly, and hasn't been a priority to clean up yet.

**Comment by jcoupey** [comment]
So that's why it's happening despite everyone having the *read* access.

I just came across this because it made sense to run code from different users in my setting. But I can definitely live with having to run client code with the same user as the one running `osrm-datastore`.

**Comment by danpat** [comment]
Related: https://github.com/Project-OSRM/osrm-backend/issues/2570

**Comment by daniel-j-h** [comment]
Closing as resolves / unintuitive memory hot-swap semantics.

**Comment by TheMarex** [comment]
This will not go away sadly. `osrm-routed` still has to relinquish ownership of the shared memory segment (ownership works like a `shared_ptr` basically). We will not be able to solve this in the current setup of two processes (`osrm-datastore` + `osrm-routed`) as this requires a long-running process that could oversee all shared memory managing.
