### ISSUE TITLE
osrm-datastore needs usage info screen

### ISSUE THREAD

**Issue by hoerup** [Project-OSRM/osrm-backend#1725]
The other osrm-* programs has a nice usage info screen - but osrm-datastore lacks this 

# osrm-extract
[info] osrm-extract <input.osm/.osm.bz2/.osm.pbf> [options]:

Options:
  -v [ --version ]                      Show version
  -h [ --help ]                         Show this help message
  -c [ --config ] arg (="extractor.ini")
                                        Path to a configuration file.

Configuration:
  -p [ --profile ] arg (="profile.lua") Path to LUA routing profile
  -t [ --threads ] arg (=7)             Number of threads to use

**Comment by daniel-j-h** [comment]
The datastore exposes [visible options](https://github.com/Project-OSRM/osrm-backend/blob/e45656e5bfb0b61a2859f0c754e66322996f1640/util/datastore_options.hpp#L116) if you request help.
Those consist of [generic and config options](https://github.com/Project-OSRM/osrm-backend/blob/e45656e5bfb0b61a2859f0c754e66322996f1640/util/datastore_options.hpp#L98) that are defined [here](https://github.com/Project-OSRM/osrm-backend/blob/e45656e5bfb0b61a2859f0c754e66322996f1640/util/datastore_options.hpp#L48-L76).

> but osrm-datastore lacks this

You then go on posting the extract help output --- is this by accident?

**Comment by hoerup** [comment]
no accident - it was just to show your other executables react on being called with out parameters

**Comment by daniel-j-h** [comment]
Right, datastore should print the help in case no arguments are given and no ini file is available.

**Comment by karenzshea** [comment]
A fix will be merged in with https://github.com/Project-OSRM/osrm-backend/commit/4afa69db31f90b94a6747a0fe6d2c2c6aba8f545
