### ISSUE TITLE
Automatically snap phantom nodes to start/endpoints of ferry routes

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1726]
It seems unlikely that people will board ferries in the middle of the ocean:

![screen shot 2015-10-08 at 9 41 44 am](https://cloud.githubusercontent.com/assets/1892250/10373539/ec45aa36-6da2-11e5-807d-0dd3ee2d4dc1.png)

We should consider snapping phantom nodes to edge endpoints for sections where the `travel_mode` is not speed-based.

**Comment by emiltin** [comment]
note that some ferry routes touch land more than two places

**Comment by TheMarex** [comment]
Resolved on `develop`.

**Comment by danpat** [comment]
Now that I've had a good long time to think about this, there is a case where this is a reasonable thing:  you're on a ferry, with your phone, and you ask for a route from your current position to some destination.

In this case, it's reasonable to snap the start point to the ferry - in fact, it's probably desirable, as otherwise, you could snap to some nearby, but otherwise inaccessible-to-you roadway.

@jakepruitt has since done some experiments using alternate weighting: https://github.com/Project-OSRM/osrm-backend/pull/3276  which might get us close to what we want to do.
