### ISSUE TITLE
"bad allocation" in osrm-extract

### ISSUE THREAD

**Issue by grudolf** [Project-OSRM/osrm-backend#1728]
osrm-extract dies with **[warn] bad allocation** when I'm trying to process a bigger map. 

I'm running latest Windows build on Windows 7 with 12GB of RAM.

	c:\prog\osrm>osrm-extract europe-latest.osm.pbf 
	[info] Input file: europe-latest.osm.pbf
	[info] Profile: profile.lua
	[info] Threads: 8
	[info] Using script profile.lua
	[STXXL-MSG] STXXL v1.4.99 (prerelease/Release) (git f7389c79e946430f5e3f7efc15e5bcc29183d200) + gnu parallel(__GLIBCXX__)
	[STXXL-MSG] Disk 'c:\temp\stxxl' is allocated, space: 75000 MiB, I/O implementation: wincall queue=0 devid=0
	[info] Parsing in progress..
	[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
	[info] timestamp: 2015-10-06T21:22:02Z
	[info] Using turn restrictions
	[info] Found 3 exceptions to turn restrictions:
	[info]   motorcar
	[info]   motor_vehicle
	[info]   vehicle
	[info] Parsing finished after 2514.93 seconds
	[info] Raw input contains 1565729219 nodes, 191634793 ways, and 2659728 relations, and 0 unknown entities
	[extractor] Sorting used nodes        ... ok, after 31.2009s
	[extractor] Erasing duplicate nodes   ... ok, after 23.1391s
	[extractor] Sorting all nodes         ... ok, after 391.964s
	[extractor] Building node id map      ... ok, after 352.78s
	[extractor] setting number of nodes   ... ok
	[extractor] Confirming/Writing used nodes     ... ok, after 159.646s
	[info] Processed 194135592 nodes
	[extractor] Sorting edges by start    ... ok, after 204.379s
	[extractor] Setting start coords      ... ok, after 787.457s
	[extractor] Sorting edges by target   ... ok, after 217.429s
	[extractor] Computing edge weights    ... ok, after 899.788s
	[extractor] Sorting edges by renumbered start ... ok, after 212.646s
	[extractor] Writing used egdes       ... ok, after 62.0375s
	[extractor] setting number of edges   ... ok
	[info] Processed 203631869 edges
	[extractor] Sorting used ways         ... ok, after 9.75665s
	[extractor] Sorting 296696 restriction. by from... ok, after 0.12591s
	[extractor] Fixing restriction starts ... ok, after 59.2153s
	[extractor] Sorting restrictions. by to  ... ok, after 0.095464s
	[extractor] Fixing restriction ends   ... ok, after 12.3924s
	[info] usable restrictions: 283588
	[extractor] writing street name index ... ok, after 4.89903s
	[info] extraction finished after 6042.16s
	[info] Generating edge-expanded graph representation
	[info]  - 283588 restrictions.
	[info] Importing n = 194135592 nodes 
	[info]  - 122525 bollard nodes, 270898 traffic lights
	[info]  and 203631869 edges 
	[info] Graph loaded ok and has 203631869 edges
	[warn] bad allocation

The .osrm.ebg file is not created. osrm-extract and osrm-prepare do work fine with a smaller map.

**Comment by daniel-j-h** [comment]
> The .osrm.ebg file is not created.

`.ebg`?

I need a little more information here:

- which osrm version are you running on?
- how much memory _and_ swap space do you have?

Also check https://github.com/Project-OSRM/osrm-backend/issues/1698 and see if the techniques I explain at the bottom of the thread help.

**Comment by TheMarex** [comment]
> I'm trying to process a bigger map.

Form the log output I would guess it is Europe from Geofabrik? The file alone is 15GB. You will either need more memory or more swap (and a lot more time).

**Comment by grudolf** [comment]
.ebg as in pull #1719 ?

Yes, I'm trying to process Europe on my dev computer. OSRM v4.8.0 is running on Windows 7 64 bit with 12 GB RAM, swap set to automatic (14 GB currently allocated). STXXL seems happy with 75 GB.

**Comment by daniel-j-h** [comment]
This pull request isn't in v4.8.0, but only in develop right now.

What do you mean with automatic? 12GB RAM and 14GB swap space is also not enough.

**Comment by grudolf** [comment]
I'm using the binaries from http://build.project-osrm.org/ and with the smaller map, osrm-extract does create a mapname.osrm.ebg file which is then read by osrm-prepare. 

Automatic as Windows manages the paging file size. If I understand it correctly, max. should be 3x amount of physical RAM, =36GB on this machine. I checked the other thread - I'll need 100GB of swap in addition to 75GB already allocated to STXXL?

**Comment by daniel-j-h** [comment]
Yeah, those binaries are nightly builds.

On Linux there is a way to say "use as much swap as you need, but max. 100 GB, and don't pre-allocate that space". Thus, you probably don't need the full 100GB for Europe.

/cc @BergWerkGIS

**Comment by BergWerkGIS** [comment]
Already on it, but it's still running.
Used binaries from http://build.project-osrm.org/ - downloaded.
Europe.osm downloaded today.

Machine has 32GB RAM and I used `stxxl` with 100GB.

During the step, where the OP's crash happened `osrm-extract.exe` used **+23GB RAM**.

So I think 12GB RAM + 36GB swap + 75GB `stxxl` could be enough.
Although processing might come to a crawl, when 12GB RAM are used up and swap comes into play.

**Comment by BergWerkGIS** [comment]
oh, dang.
it crashed during I wrote the last message, so I don't know what was going on, when it happened.

```
λ osrm-extract.exe europe-latest.osm.pbf
[info] Input file: europe-latest.osm.pbf
[info] Profile: profile.lua
[info] Threads: 16
[info] Using script profile.lua
[STXXL-MSG] STXXL v1.4.99 (prerelease/Release) (git f7389c79e946430f5e3f7efc15e5bcc29183d200) + gnu parallel(__GLIBCXX__)
[STXXL-MSG] Disk 'Z:\stxxl' is allocated, space: 100000 MiB, I/O implementation: wincall queue=0 devid=0
[info] Parsing in progress..
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
[info] timestamp: 2015-10-08T21:23:02Z
[info] Using turn restrictions
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parsing finished after 1375.6 seconds
[info] Raw input contains 1566726441 nodes, 191770478 ways, and 2664970 relations, and 0 unknown entities
[extractor] Sorting used nodes        ... ok, after 28.022s
[extractor] Erasing duplicate nodes   ... ok, after 17.5877s
[extractor] Sorting all nodes         ... ok, after 844.44s
[extractor] Building node id map      ... ok, after 231.601s
[extractor] setting number of nodes   ... ok
[extractor] Confirming/Writing used nodes     ... ok, after 108.093s
[info] Processed 194217707 nodes
[extractor] Sorting edges by start    ... ok, after 110.002s
[extractor] Setting start coords      ... ok, after 280.035s
[extractor] Sorting edges by target   ... ok, after 113.206s
[extractor] Computing edge weights    ... ok, after 357.791s
[extractor] Sorting edges by renumbered start ... ok, after 106.888s
[extractor] Writing used egdes       ... ok, after 44.6491s
[extractor] setting number of edges   ... ok
[info] Processed 203715730 edges
[extractor] Sorting used ways         ... ok, after 6.53993s
[extractor] Sorting 296995 restriction. by from... ok, after 0.087821s
[extractor] Fixing restriction starts ... ok, after 2.0042s
[extractor] Sorting restrictions. by to  ... ok, after 0.074172s
[extractor] Fixing restriction ends   ... ok, after 1.81681s
[info] usable restrictions: 283867
[extractor] writing street name index ... ok, after 1.06346s
[info] extraction finished after 3698.8s
[info] Generating edge-expanded graph representation
[info]  - 283867 restrictions.
[info] Importing n = 194217707 nodes
[info]  - 122625 bollard nodes, 271005 traffic lights
[info]  and 203715730 edges
[info] Graph loaded ok and has 203715730 edges
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.188393
[info] Edge compression ratio: 0.225837
. 10% . 20% . 30% . 40% . 50% [warn] bad allocation
```

**Comment by BergWerkGIS** [comment]
ran it again with 140GB `stxxl`, crashed at the same point.

When reaching `50%` `osrm.extract.exe` used ~16GB RAM.
Then it dropped to ~300MB.
Then it rose to several GB.
Then it dropped to ~600MB and just went away.

`stxxl.log` and `stxxlerror.log` don't show any errors.

```
...
...
[info] usable restrictions: 283867
[extractor] writing street name index ... ok, after 1.00777s
[info] extraction finished after 3060.47s
[info] Generating edge-expanded graph representation
[info]  - 283867 restrictions.
[info] Importing n = 194217707 nodes
[info]  - 122625 bollard nodes, 271005 traffic lights
[info]  and 203715734 edges
[info] Graph loaded ok and has 203715734 edges
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.188393
[info] Edge compression ratio: 0.225837
. 10% . 20% . 30% . 40% . 50% [warn] bad allocation
```

**Comment by daniel-j-h** [comment]
The edge compressor takes stdlib containers and writes to restriction map (contains stdlib containers), edge container (contains stdlib containers) and a dynamic graph (contains stdlib containers and a deallocating vector). So the memory reserved for stxxl won't help much from what I can tell _at this point in the pipeline_. Try with more swap space, instead of more stxxl resources.

**Comment by BergWerkGIS** [comment]
Success: `osrm-extract.exe` ran thru and generated 24.5GB worth of files:

![image](https://cloud.githubusercontent.com/assets/4549888/10398279/7fad9694-6eac-11e5-9bef-cfff7f0a25d3.png)

Additionally to 140GB stxxl I set the virtual memory paging size to 100GB (just to make sure).

So, my setup was:
* 32GB physical RAM
* 140GB stxxl
* 100GB paging file

During the whole process all available RAM (32GB) was used 100% and `Comitted` memory in Task Manager showed **~53GB**.

@grudolf according to your comments and my findings, I think these should suffice for you.

* 70GB stxxl
* 45GB paging

If not, I suggest to increase paging size even more.

**Comment by grudolf** [comment]
Thank you, I'll try to process the file over the weekend.

**Comment by grudolf** [comment]
I went with:
- 12GB physical RAM
- 75GB STXXL
- 64GB Windows paging (had to set both initial and maximum size, setting only maximum didn't work)

osrm-extract took 10 hours and osrm-prepare another 2:

    07.10.2015  18:27    16.969.064.265 europe-latest.osm.pbf                 
    09.10.2015  22:15                20 europe-latest.osrm.timestamp          
    09.10.2015  23:49     7.178.807.412 europe-latest.osrm                    
    09.10.2015  23:50         4.537.564 europe-latest.osrm.restrictions       
    09.10.2015  23:50        54.425.245 europe-latest.osrm.names              
    10.10.2015  01:25     1.711.233.068 europe-latest.osrm.geometry           
    10.10.2015  08:02     1.969.162.960 europe-latest.osrm.edges              
    10.10.2015  08:31     9.770.099.100 europe-latest.osrm.fileIndex          
    10.10.2015  08:31        56.535.644 europe-latest.osrm.ramIndex           
    10.10.2015  08:32     2.329.627.108 europe-latest.osrm.nodes              
    10.10.2015  08:33     3.281.938.428 europe-latest.osrm.ebg                
    10.10.2015  10:27     8.738.782.264 europe-latest.osrm.hsgr               
    10.10.2015  10:27                 4 europe-latest.osrm.core               
                  13 File(s) 52.064.213.082 bytes                             
                   0 Dir(s)  77.855.539.200 bytes free                        

osrm-routed seems to be working fine.

**Comment by BergWerkGIS** [comment]
:fireworks: :fireworks: :fireworks:

**Comment by TheMarex** [comment]
Cool. Closing.

**Comment by aheiX** [comment]
This worked for me: 16GB RAM, 140GB STXXL, 70GB Windows paging

`osrm-extract europe-latest.osm.pbf -p car.lua`
~20 hours

`osrm-contract  europe-latest.osrm`
~ 6 hours
