### ISSUE TITLE
routing through destination roads

### ISSUE THREAD

**Issue by kdano** [Project-OSRM/osrm-backend#1734]
The router seems to ignore the access=destination and vehicle=destination tags. (And I'm guessing all the other destination tags, as well.)

[Example 1](http://www.openstreetmap.org/directions?engine=osrm_car&route=47.50155%2C19.05493%3B47.50243%2C19.05344#map=18/47.50180/19.05381) (access=destination)
[Example 2](http://www.openstreetmap.org/directions?engine=osrm_car&route=47.48537%2C19.06215%3B47.48718%2C19.06131#map=18/47.48635/19.06172) (vehicle=destination [here](http://www.openstreetmap.org/way/24262578))

**Comment by TheMarex** [comment]
Thanks for reporting this. :+1:

This is already tracked in https://github.com/Project-OSRM/osrm-backend/issues/156
