### ISSUE TITLE
osrm-prepare: [exception] std::bad_alloc

### ISSUE THREAD

**Issue by colcen** [Project-OSRM/osrm-backend#1736]
I googled and found this similar issue reported and seems no answer is given, so I create a new one.

I am trying to run osrm-backend server on ubuntu 15.04. the version I tried are 4.8.1 and latest master(8f6fc0146ba76d34d20c5b7a87b75249bbb12b82)
the map file I am using is  california-latest.osm.pbf(519M)
I successful executed osrm-extract california-latest.osm.pbf,
the file generated are as follow:
-rw-r----- 1 james james 519M Oct  8 11:20 california-latest.osm.pbf
-rw-rw-r-- 1 james james 409M Oct  8 12:13 california-latest.osrm
-rw-rw-r-- 1 james james  93M Oct 12 18:06 california-latest.osrm.geometry
-rw-rw-r-- 1 james james 3.6M Oct  8 12:13 california-latest.osrm.names
-rw-rw-r-- 1 james james  89K Oct  8 12:13 california-latest.osrm.restrictions
-rw-rw-r-- 1 james james   20 Oct  8 12:02 california-latest.osrm.timestamp

 however, the command "osrm-prepare california-latest.osrm" throws exception:
[info] Input file: california-latest.osrm
[info] Restrictions file: california-latest.osrm.restrictions
[info] Profile: profile.lua
[info] Threads: 8
[info] Generating edge-expanded graph representation
[info]  - 5668 restrictions.
[info] Importing n = 11615699 nodes 
[info]  - 2268 bollard nodes, 26989 traffic lights
[info]  and 12146143 edges 
[info] Graph loaded ok and has 12146143 edges
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.148594
[info] Edge compression ratio: 0.185719
. 10% . 20% . 30% . 40% . 50% .[warn] [exception] std::bad_alloc

the output of "free -m" 
             total       used       free     shared    buffers     cached
Mem:          7665       5616       2049        401        114       1303
-/+ buffers/cache:       4198       3467
Swap:        89344        158      89186

lua -v
Lua 5.3.1  Copyright (C) 1994-2015 Lua.org, PUC-Rio

can anyone help on this.

**Comment by mk112014** [comment]
Increase reserved disk capacity in .stxxl.txt file. If it doesn't solve your problem, add more RAM.

**Comment by daniel-j-h** [comment]
@colcen is it working now for you? Any more problems here?

**Comment by colcen** [comment]
@daniel-j-h it doesn't work for me. I increased the reserved disk capacity to 150G and it doesn't work. I just don't have more RAM to add.

**Comment by danpat** [comment]
@colcen We have seen some https://github.com/Project-OSRM/osrm-backend/issues/1484 memory leaks with Lua in the past.  Can you try re-building against a different Lua version?

For reference, `california.osm.pbf` is easily processable on my MacBook Pro with 16GB.  While I haven't tested it explicitly, I feel like you should be able to do it on your machine.  There is no memory locking done during processing, so although it might be slow, swap space should be used.  STXXL will auto-grow the allocated file if it runs out of space, so I don't think that's the problem.

Also, is this a 32bit or 64bit machine?

**Comment by daniel-j-h** [comment]
@colcen do I understand you correctly: you only changed the stxxl reserved disk capacity, right?
This is independent of your memory / swap space, though. Take a look at this comment and increase your swapfile as described: https://github.com/Project-OSRM/osrm-backend/issues/1698#issuecomment-142744361. If this does not help, please report back with more details, such as how much memory you have and how large your swap space is.

**Comment by colcen** [comment]
by building against Lua5.1, now there is no problem to run the command.

**Comment by colcen** [comment]
@danpat & @daniel-j-h  thanks for the help.

**Comment by daniel-j-h** [comment]
> by building against Lua5.1, now there is no problem to run the command.

Can you make sure this was really caused by Lua 5.3.1 and not by lack of larger swap file / more memory? Because if so, we are probably running into this more often, once people start using more recent Lua versions.
