### ISSUE TITLE
Fix small components layer on map.project-osrm.org

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#1745]
Breaking out from https://github.com/Project-OSRM/osrm-backend/issues/1738#issuecomment-148921638

The small components layer should be fixed, we used to upload to Geofabrik and need to figure out if we can get that rolling again. Uploads to Mapbox are blocked by file size limitations.

**Comment by freenerd** [comment]
@TheMarex do you have a contact at Geofabrik you could ping?

**Comment by TheMarex** [comment]
@joto do you know if Frederik would be still up for this?

**Comment by woodpeck** [comment]
If you could generate a ssh key that you want to use for uploading the small components shape files and send that to me (at frederik dot remote dot org), I'll set things up on the OSMI server and tell you what to do (essentially: scp islands.* $SERVER; ssh $SERVER "sh update.sh").

**Comment by freenerd** [comment]
@woodpeck thanks frederik. dropped you an email.

**Comment by freenerd** [comment]
@woodpeck thanks, this is running now. The small components layer hosted on Geofabrik now gets updated every night \o/
