### ISSUE TITLE
Bearing+location heuristic for choosing ways in /viaroute

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1749]
Using bearing in /match was recently implemented in #605. Implementation is based on a bearing filter.

For use in /viaroute and navigation where the bearing comes from mobile device sensors, a heuristic is needed that chooses the best way based on both the location and the bearing. 

During navigation, bearing is typically only known for the current user location (ie. start location) so /viaroute needs to support this.

Suggested steps:

1. use location to identify candidate ways
2. use bearing+location heuristic to rank candidate ways
3. pick highest ranking candidate

As a first attempt, the heuristic might look something like `distance^2 + k*angle^2`, where lowest score is best. k is a konstant to weight distance and angle relative to each other.

Distance and location factors should probably be added, rather than multiplied, since multiplication would result in 0 (best possible score) if either distance or angle is a perfect match, which is not what we want, since a perfect location or angle is no good if the other parameter is completely wrong.

Squaring might be helpful to prefer ways that score well on both parameters, rarther than ways that score very well on one but poorly on the other. Turn penalties currently uses angle^2 which might lend some support to squaring.

**Comment by daniel-j-h** [comment]
v5 allows setting bearings and radiuses for all services now:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#general-options

Does this solve your problems @emiltin? (If so, please close this ticket)

**Comment by emiltin** [comment]
Yes, thanks a lot.

**Comment by sdafni** [comment]
hi, was bearing eventually implemented as filter or as rank? 
according to the api documentation: "**Limits** the search to segme..."  it seems routes that don't match thew bearing are excluded.
how does this solve Emil's problems? 
thanks,
Yuval Dafni
