### ISSUE TITLE
Viaroute returns a much longer route with lots of viapoints vs 1 request per leg

### ISSUE THREAD

**Issue by zavan** [Project-OSRM/osrm-backend#1751]
When I [request  the viaroute for 184 points all together](http://router.project-osrm.org/viaroute?loc=-23.581959,-46.783094&loc=-23.536292,-46.724398&loc=-23.536491,-46.725055&loc=-23.536456,-46.725297&loc=-23.536235,-46.725437&loc=-23.536009,-46.725581&loc=-23.535996,-46.725589&loc=-23.53596,-46.725569&loc=-23.53561,-46.725894&loc=-23.535112,-46.726137&loc=-23.535084,-46.726207&loc=-23.53485,-46.725843&loc=-23.534605,-46.7258&loc=-23.534639,-46.725884&loc=-23.534485,-46.726033&loc=-23.534427,-46.726136&loc=-23.534385,-46.726128&loc=-23.533947,-46.726532&loc=-23.533944,-46.725985&loc=-23.533072,-46.725497&loc=-23.533256,-46.725777&loc=-23.532961,-46.725774&loc=-23.532865,-46.725819&loc=-23.53273,-46.725889&loc=-23.532371,-46.726022&loc=-23.532201,-46.725874&loc=-23.532028,-46.726005&loc=-23.531988,-46.725592&loc=-23.531829,-46.725467&loc=-23.531675,-46.725389&loc=-23.531381,-46.724535&loc=-23.53126,-46.724638&loc=-23.531009,-46.724072&loc=-23.530926,-46.724074&loc=-23.530877,-46.724222&loc=-23.530996,-46.724712&loc=-23.530497,-46.724797&loc=-23.529105,-46.725737&loc=-23.528609,-46.725906&loc=-23.528898,-46.72635&loc=-23.529089,-46.726624&loc=-23.529441,-46.726761&loc=-23.529814,-46.726828&loc=-23.529935,-46.72658&loc=-23.530139,-46.726668&loc=-23.530482,-46.726308&loc=-23.530665,-46.726013&loc=-23.530921,-46.725876&loc=-23.530864,-46.725667&loc=-23.531157,-46.725837&loc=-23.532816,-46.726528&loc=-23.532866,-46.726801&loc=-23.533598,-46.727345&loc=-23.533479,-46.727575&loc=-23.53384,-46.728018&loc=-23.53269,-46.72786&loc=-23.532395,-46.728145&loc=-23.532046,-46.728502&loc=-23.531951,-46.728393&loc=-23.53188,-46.728449&loc=-23.531647,-46.728559&loc=-23.53146,-46.72862&loc=-23.531358,-46.728986&loc=-23.530818,-46.72923&loc=-23.530459,-46.729924&loc=-23.53116,-46.729695&loc=-23.531307,-46.729644&loc=-23.531263,-46.729874&loc=-23.530583,-46.728582&loc=-23.530442,-46.728529&loc=-23.529812,-46.727655&loc=-23.528535,-46.727853&loc=-23.528476,-46.727959&loc=-23.52953,-46.729144&loc=-23.529781,-46.729941&loc=-23.529263,-46.729843&loc=-23.529116,-46.729639&loc=-23.529324,-46.729929&loc=-23.528743,-46.729749&loc=-23.528304,-46.729792&loc=-23.528306,-46.730238&loc=-23.527979,-46.730577&loc=-23.527323,-46.730782&loc=-23.527221,-46.731228&loc=-23.526866,-46.731246&loc=-23.526479,-46.731433&loc=-23.526298,-46.731971&loc=-23.526254,-46.73206&loc=-23.525892,-46.732234&loc=-23.52558,-46.732532&loc=-23.525513,-46.732856&loc=-23.525304,-46.732747&loc=-23.524272,-46.733351&loc=-23.523688,-46.733424&loc=-23.522728,-46.733363&loc=-23.522005,-46.733545&loc=-23.521478,-46.734067&loc=-23.52135,-46.733922&loc=-23.521613,-46.734257&loc=-23.52304,-46.735952&loc=-23.523189,-46.736183&loc=-23.523563,-46.736734&loc=-23.523311,-46.735043&loc=-23.523282,-46.734781&loc=-23.523945,-46.734801&loc=-23.524614,-46.733941&loc=-23.524538,-46.73545&loc=-23.523969,-46.735331&loc=-23.525524,-46.734425&loc=-23.526504,-46.734741&loc=-23.52642,-46.734827&loc=-23.527148,-46.735542&loc=-23.5273,-46.733658&loc=-23.526517,-46.732853&loc=-23.526688,-46.732491&loc=-23.526717,-46.732384&loc=-23.526991,-46.732104&loc=-23.527096,-46.731983&loc=-23.527318,-46.7328&loc=-23.527585,-46.732385&loc=-23.528549,-46.732236&loc=-23.524317,-46.735779&loc=-23.531962,-46.726579&loc=-23.532192,-46.726921&loc=-23.531627,-46.726633&loc=-23.531804,-46.726884&loc=-23.531443,-46.726738&loc=-23.531563,-46.727058&loc=-23.531559,-46.727062&loc=-23.531749,-46.727377&loc=-23.531405,-46.727355&loc=-23.531088,-46.727545&loc=-23.530711,-46.72785&loc=-23.530731,-46.727987&loc=-23.530653,-46.727907&loc=-23.531832,-46.723502&loc=-23.531785,-46.722766&loc=-23.531871,-46.722427&loc=-23.531629,-46.722159&loc=-23.531857,-46.722073&loc=-23.531663,-46.722056&loc=-23.531663,-46.721967&loc=-23.531809,-46.72192&loc=-23.531802,-46.721696&loc=-23.531903,-46.721524&loc=-23.531791,-46.721231&loc=-23.53177,-46.720981&loc=-23.5325,-46.720287&loc=-23.532567,-46.720313&loc=-23.533156,-46.720604&loc=-23.532521,-46.720525&loc=-23.532941,-46.721355&loc=-23.533106,-46.721458&loc=-23.532777,-46.721891&loc=-23.532685,-46.721961&loc=-23.533009,-46.722178&loc=-23.533043,-46.722199&loc=-23.533045,-46.722356&loc=-23.532951,-46.722886&loc=-23.533334,-46.723242&loc=-23.533695,-46.723353&loc=-23.534018,-46.723192&loc=-23.534103,-46.722539&loc=-23.534107,-46.722188&loc=-23.534733,-46.723042&loc=-23.534749,-46.722892&loc=-23.533479,-46.722308&loc=-23.534101,-46.723779&loc=-23.534446,-46.723974&loc=-23.534521,-46.723721&loc=-23.53454,-46.724157&loc=-23.534164,-46.724951&loc=-23.53476,-46.725025&loc=-23.534722,-46.724949&loc=-23.534723,-46.725498&loc=-23.53531,-46.725264&loc=-23.535424,-46.724981&loc=-23.535863,-46.724789&loc=-23.534741,-46.723281&loc=-23.533074,-46.724&loc=-23.532527,-46.72332&loc=-23.532531,-46.722933&loc=-23.532983,-46.724976&loc=-23.532947,-46.724946&instructions=true&alt=false) I get a much longer/slower route (48139 meters/4859 seconds on demo OSRM instance, 44360 meters/4088 seconds on my OSRM instance) vs when I make one request per leg (pair of chained viapoints, like: [0, 1], [1, 2], [2, 3]...)  and sum each response distance/time to get the totals (25239 meters/2182 seconds on my OSRM instance).

I have confirmed that the total distances returned for the route are correct by calculating the polyline length with the haversine formulae. 

Any idea why this happens?

PS.: The viapoints are almost all pretty close to each other, and were ordered through a heuristic method, if that matters.

**Comment by zavan** [comment]
For comparison, I have a bussiness Google Maps API account, and requesting in slices of 24 viapoints I get a total of ~24000 meters/4740 seconds for this route.

**Comment by zavan** [comment]
In slices of 24 points, in my OSRM instance, I get 43356 meters/3971 seconds.

**Comment by zavan** [comment]
Does OSRM change the viapoints order in any way?

**Comment by TheMarex** [comment]
@zavan if you request each leg independently it will allow u-turns to happen at the via points. Per default `viaroute` only allows u-turns at intersections. You can enable u-turns at via by passing `uturn=true`. I just saw that we didn't document this in the wiki, so I added it to the [API docs](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#service-nearest).

**Comment by zavan** [comment]
@TheMarex Perfect! Solved.
Thank you very much!
