### ISSUE TITLE
no valid coredata file given in ini file

### ISSUE THREAD

**Issue by JendaPlhak** [Project-OSRM/osrm-backend#1752]
Hello. I am trying to use OSRM backend for routing, but whenever I try to create object OSRM I get error "no valid coredata file given in ini file". The program also consumes massive amount of memory (8Gb+). Is that normal behaviour?

**Comment by daniel-j-h** [comment]
Did you close this ticket by accident, or could you solve your problem? (If so, how?)

**Comment by JendaPlhak** [comment]
I was just being stupid. It turned out, that I had wrong line in paths. 
What I had was { "core", ".core" }. But correct is { "coredata", ".core" }.
