### ISSUE TITLE
Best practise approach for using z= parameter for `viaroute` calls

### ISSUE THREAD

**Issue by mmd-osm** [Project-OSRM/osrm-backend#1753]
First of all, this ticket is asking for advise on how the `viaroute` call should be ideally called. It is related to [the following ticket I raised for main osm.org site](https://github.com/openstreetmap/openstreetmap-website/issues/1077), where we experienced somewhat imprecise routing results in special cases. Please refer to this ticket for actual test cases and more details.

I've noticed that osm.org uses z=14 consistently for all `viaroute` calls, as [it is hard-coded](https://github.com/openstreetmap/openstreetmap-website/blob/3932c6b7f28223819fb71920b2458fc1180cba82/app/assets/javascripts/index/directions/osrm.js#L36). On the other hand, the web site at map.project-osrm.org seems to employ a different, more sophisticated strategy and triggers a *second* `viaroute` call in some cases.

@tomhughes [asked me](https://github.com/openstreetmap/openstreetmap-website/issues/1077#issuecomment-150906431) for some sensible approach on what conditions should trigger those additional calls. Unfortunately, I'm not familiar enough with the implementation on map.project-osrm.org to answer that question in detail.

My impression is, that the routing result is initially shown on the map and the map zoomed accordingly to fit the bounding box of the route. Probably as a result of zooming the map (zoomend event?), a second `viaroute` call is triggered, this time with the current zoom level as `z=` parameter. Assuming that the first `viaroute` was called with z=14 and the second call with z=18, I would expect more precise results in the end.

I was hoping that you could provide us some guidance  on how this is actually solved on map.project-osrm.org and what approach to call `viaroute` you would generally recommend for osm.org.

I'm not sure if this belongs to some mailing list, if so, please let me know.

Thanks in advance!

**Comment by tomhughes** [comment]
I'll just add that contrary to the claims in the OSM ticket I can't find any sign of any code in either the OSRM frontend repository or the leaflet-routing-machine repository that would retry at increased z based on some sort of condition...

**Comment by tomhughes** [comment]
Incidentally rerouting on a zoom change is exactly what I was considering but I could find no sign of any code in the OSRM site that would do that.

**Comment by mmd-osm** [comment]
@tomhughes : I just found a comment in the [project readme](https://github.com/Project-OSRM/osrm-frontend-v2/blob/gh-pages/README.md), that the current frontend is heavily based on the Leaflet Routing Machine created by @perliedman. In his repository, I also found the `zoomend` event handler, which triggers the second routing call:

https://github.com/perliedman/leaflet-routing-machine/blob/001a83748439ada4176f0faaab4f2a5493edfc16/src/L.Routing.Control.js#L52

I placed a breakpoint in Firebug in bundle.raw.js around line 4860: that's the location where the OSRM service url gets assembled. You'll notice that there's also a *zoomend* event eventually hitting this location.

```javascript
			return this.options.serviceUrl + '?' +
				'instructions=' + computeInstructions.toString() + '&' +
				'alt=' + computeAlternative.toString() + '&' +
				(options.z ? 'z=' + options.z + '&' : '') +
				locs.join('&') +
				(this._hints.checksum !== undefined ? '&checksum=' + this._hints.checksum : '') +
				(options.fileformat ? '&output=' + options.fileformat : '') +
				(options.allowUTurns ? '&uturns=' + options.allowUTurns : '');
```

**Comment by danpat** [comment]
If no `z=` parameter is supplied, OSRM returns the z=18 equivalent, i.e. the full geometry.

If you supply another zoom value, we run the Douglas-Peucker line simplification algorithm over the route line.  The `z=` parameter governs the corner-removal threshold.  The lower the `z` value, the more the geometry is simplified.  It'll give you less data in the response and will be faster to draw.

`z=14` results will definitely look funny if you view them at a Z=18 scale, there will be lots of detail missing.  AFAIK, LRM adapts the request as you zoom in and out.

You can run `z=18` at all levels, but there's a lot of redundant data there, particularly for longer routes.

**Comment by perliedman** [comment]
@tomhughes Leaflet Routing Machine makes new routing calls when the map is zoomed when the option [`useZoomParameter`] is enabled; see the [options for `L.Routing.Control`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control) (disabled by default).

The relevant part of the code is here: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Control.js#L50

**Comment by tomhughes** [comment]
@perliedman Thanks for that - I think I had been looking "lower down the stack" in LRM ;-)

**Comment by tomhughes** [comment]
@danpat There is a comment from @systemed on https://github.com/openstreetmap/openstreetmap-website/issues/1077#issuecomment-151191895 now about why we always use z14 and don't go any higher...

**Comment by danpat** [comment]
@tomhughes Ah, thanks.  I think the info that decision is based on might be outdated, `z=` no longer has an effect on viapoint snapping.

**Comment by mmd-osm** [comment]
Thanks everyone again, I'm closing this one in favor of https://github.com/openstreetmap/openstreetmap-website/issues/1077
