### ISSUE TITLE
Directions not snapping to coordinates

### ISSUE THREAD

**Issue by tristen** [Project-OSRM/osrm-backend#1754]
This query fails and I suspect it's because the destination coordinates do not land on a road:

http://map.project-osrm.org/?z=13&center=43.678674%2C-79.354162&loc=43.702298%2C-79.357431&loc=43.654174%2C-79.380812

Snapping in the scenario above doesn't appear to be working.

cc @TheMarex

**Comment by TheMarex** [comment]
@planemad Can you take a look at this? Looks like indoor foot paths. They are all tagged with `access=permissive` but should be `pedestrian=permessive`, right?

**Comment by planemad** [comment]
@TheMarex we've found this before with an inconsistent use of `access=*` on a non motorable way. We can assume the mapper meant `pedestrian=permissive` but there is no way to be sure without confirming with the mapper first.

`access=*` has been used on [10,000+](http://taginfo.openstreetmap.org/tags/highway=pedestrian#combinations) `highway=pedestrian` and 171,000 `highway=footway` objects  and its not feasible for us to manually retag every one without confirming first.

**Comment by TheMarex** [comment]
Fixed the tagging in OSM.
