### ISSUE TITLE
Unable to process the planet.osm.bz2

### ISSUE THREAD

**Issue by mehany** [Project-OSRM/osrm-backend#1755]
I get the following error when i prepare the planet after osrm-extract.  when I run <b>osrm-prepare planet-151019.osrm -p profile.lua</b>

    osrm input file misses magic number. Check or reprocess the file

I reprocessed the file ( which took exactly 15 hours ) but still no joy, I get the same error. Not sure what I am missing or did wrong! I followed <a href="https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04" target="_Blank"> this</a> tutorial to get started. 

So far, this happens only when i process the planet, if I process a state in the US, it works. 
I notice that <b>osrm-extract</b> command stops and does not generate all the necessary <i>osrm</i> files, here is the output I get after extracting:

    >> osrm-extract planet-151019.osm.bz2
    [info] Input file: planet-151019.osm.bz2
    [info] Profile: profile.lua
    [info] Threads: 1
    [info] Using script profile.lua
    [STXXL-MSG] STXXL v1.3.1 (release)
    [STXXL-MSG] 1 disks are allocated, total space: 1000000 MiB
    [info] Parsing in progress..
    [info] input file generated by planet-dump-ng 1.1.2
    [info] timestamp: n/a
    [info] Using turn restrictions
    [info] Found 3 exceptions to turn restrictions:
    [info]   motorcar
    [info]   motor_vehicle
    [info]   vehicle
    [info] Parsing finished after 53439.5 seconds
    [info] Raw input contains 3068847595 nodes, 312396826 ways, and 3716719 relations, and 34701399 unknown entities
    [extractor] Sorting used nodes        ... ok, after 94.728s
    [extractor] Erasing duplicate nodes   ... ok, after 72.4137s
    [extractor] Sorting all nodes         ... ok, after 1800.8s
    [extractor] Building node id map      ... Killed

P.S.
 
Then this is what get generated:
    
    planet-151019.osrm
    planet-151019.osrm.timestamp

Here is the directory structure where I run <i>osrm</i> commands:

    lib -> osrm-backend/profiles/lib/
    osrm-backend/
    planet-151019.osm.bz2
    planet-151019.osrm
    planet-151019.osrm.timestamp
    profile.lua -> osrm-backend/profiles/car.lua
    .stxxl
    stxxl.errlog
    stxxl.log

**Comment by danpat** [comment]
@mehany it looks like `osrm-extract` is not completing.  The `Killed` message is coming from your kernel, it looks like you are running out of RAM.  `osrm-prepare` is complaining because it is only finding half-completed files.

To process the full planet, you need about 60GB of RAM, or equivalent swap space (this will be *very very slow*), plus about 150-200GB of free disk space for the STXXL layer.

**Comment by mehany** [comment]
@danpat that makes sense, thanks. I will try to extract only USA instead and increase RAM somehow.
