### ISSUE TITLE
Segmentation Fault in osrm-extract

### ISSUE THREAD

**Issue by waltonseymour** [Project-OSRM/osrm-backend#1759]
Hey I'm trying to get osrm-extract to work with a osm file that I have.
It consistently gives me ``Segmentation fault: 11`` right after ``[extractor] Fixing restriction starts ...``

Could this be due to a lack of restrictions referenced in #34?
I've tried this on master and development branches.

**Comment by danpat** [comment]
A lack of restrictions alone shouldn't cause a crash, I process files without restriction relations all the time.

Can you post a link to the datafile you've got?  If not, can you do a debug build by:

```
cd build
rm -rf CMake*
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```

Then, run `osrm-extract` under `gdb` and get a backtrace on the crash?

```
gdb ./osrm-extract
> run -p ../profiles/car.lua yourfile.osm
** CRASH **
> bt
```

**Comment by waltonseymour** [comment]
The osm file is about 100GB so I'll just run the debugger.
Each run takes about an hour so I'll message back when it's done.

**Comment by danpat** [comment]
Oh, that's too bad.  Unfortunately, the debug build will be a *lot* slower, as it has a lot of the optimizations disabled.

**Comment by daniel-j-h** [comment]
What came out of this?

Try building with `-fno-omit-frame-pointer` to get a proper stack trace, and use the sanitizers to detect undefined behavior and memory issues, e.g. do:

    CXXFLAGS="-fsanitize=undefined,address -g -ggdb -fno-omit-frame-pointer"
    export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer)

**Comment by waltonseymour** [comment]
I ended up giving up on using that specific osm file. After switching to a different file, it worked properly.
