### ISSUE TITLE
routed option -m is ambiguous

### ISSUE THREAD

**Issue by hoerup** [Project-OSRM/osrm-backend#1762]
osrm-routed -m 200
[warn] exception: option '-m' is ambiguous and matches '--max-matching-size', and '--max-table-size'

**Comment by daniel-j-h** [comment]
For the record: [routed_options.hpp](https://github.com/Project-OSRM/osrm-backend/blob/a62c10321c0a269e218ab4164c4ccd132048f271/util/routed_options.hpp#L187-L190)

**Comment by TheMarex** [comment]
This is fixed in `4.9.0` by removing the short version.
