### ISSUE TITLE
Bug: Underground route to overground aim 

### ISSUE THREAD

**Issue by ghagerer** [Project-OSRM/osrm-backend#1763]
See the following example for explanation:

Route starting point: Denninger Straße 84, 81925 München
Route end point: Richard-Strauss-Straße 71, 81679 München

What OSRM suggests: http://tinyurl.com/oo7m8bp
What OSRM should suggest: http://tinyurl.com/oefrd4o

Background: The street, in which the aim is located (Richard-Strauss-Straße), lies over a tunnel (Richard-Strauss-Tunnel). The end point is converted to a GPS coordinate, which lies nearer to the tunnel than to the street. This is why the tunnel is suggested by OSRM. Nonetheless, the tunnel is underground in opposite to the actual aim, which is overground. Thereby a significant detour is taken (turn right from Denninger Straße to Richard-Strauss-Straße to get into the tunnel instead of turning left, which would bring you directly to the aim). 

Possible solution: I would suggest that a tunnel should never be considered as the correct route, when the aim is over it, also not if it appears to be nearer.

**Comment by emiltin** [comment]
might be solved by #1749

**Comment by emiltin** [comment]
related: #1263

**Comment by TheMarex** [comment]
> The end point is converted to a GPS coordinate, which lies nearer to the tunnel than to the street. This is why the tunnel is suggested by OSRM. Nonetheless, the tunnel is underground in opposite to the actual aim, which is overground.

Sadly we can't really guess the intention of the user like this. Using complicated heuristics is really screws with exceptions of what is going to happen. As @emiltin already mentioned we are adding additional query parameters that help the user to state his intention more explicitly. In this case however I don't see a way around specifying the correct coordinate.

**Comment by ghagerer** [comment]
Another way of solving this could be a new tag like "underground=true", that can be added to buildings. If underground is set, a tunnel as end part of a route is acceptable, otherwise not.

**Comment by ghagerer** [comment]
In my humble non-expert opinion, most OSM-based navigation apps (e.g. osmAnd, MapFactor Navigator, Magic Earth) don't take care about what kind of coordinates OSRM or other routing engines accept. The standard way of specifying coordinates is passing the correct ones. As I said, I am no expert, but I guess that this standard behaviour won't ever change.
