### ISSUE TITLE
Distances corresponding to the time(distance) matrix

### ISSUE THREAD

**Issue by ilansen** [Project-OSRM/osrm-backend#1767]
@DennisOSRM 
I would like to get corresponding distances for the time matrix generated by the service 'table'. Currently, I get the distances of the fastest routes one by one using the service 'viaroute', which is quite time consuming. Is there a way to get the distances corresponding to each element of time matrix in a more efficient manner?
I have seen a similar thread on this topic. There it was mentioned that you are planning on making available the above functionality. Will this be available any time soon?
Thank you.

**Comment by TheMarex** [comment]
It is here in an unfinished state. It will get merged when someone picks it up, as it is not a priority right now.

https://github.com/Project-OSRM/osrm-backend/pull/1452
