### ISSUE TITLE
native ruby bindings

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1769]
it would be great to have native ruby binding, like the node bindings, so you can run queries directly ruby.
it might also speed up tests, since queries could be run without calling out to osrm-routed.

**Comment by emiltin** [comment]
for use in cucumber testing, it would be useful to have native bindings not only to route queries, but also for preprocessing data.

**Comment by daniel-j-h** [comment]
I'm closing this as not actionable for us. We switched to cucumberjs for tests. I built https://github.com/daniel-j-h/libosrmc which allows easy FFI integration (with Ansi C / Python / Haskell examples).
