### ISSUE TITLE
extract ruby interface to osrm bins to a ruby gem

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1770]
the cucumber test framework has quite a bit of code that handles interfacing with the osrm bins. it would be nice to extract this to a ruby gem, so it's easy to reuse in other ruby code. the whole cucumber framework has also grown a lot over time, and could use some refactoring/cleanup.

**Comment by daniel-j-h** [comment]
See https://github.com/Project-OSRM/osrm-backend/issues/1769#issuecomment-222754870: I'm closing this as not actionable.
We switched to cucumberjs for tests. :bow: @lbud 

FFI integration (with Ansi C / Python / Haskell examples) is done in
https://github.com/daniel-j-h/libosrmc
