### ISSUE TITLE
Does osrm-routed support processing multiple requests concurently and are there limits?

### ISSUE THREAD

**Issue by kostadin24** [Project-OSRM/osrm-backend#1771]
I saw in source - engine use multiple threads. I have configuration with 4 threads. What will happen when 6-7 requests arrive in same time? Do requests over limit wait some time for free thread or I have to manage requests to not exceed 4 at same time?

**Comment by TheMarex** [comment]
There is a queue. No request will be dropped. :-)

**Comment by danpat** [comment]
The incoming requests get queued, and served by worker threads.

See:  https://github.com/Project-OSRM/osrm-backend/blob/develop/server/server.hpp#L61-L78

You don't need to limit requests to 4 concurrently, but the queue will get longer and longer if you're averaging requests faster than they can be served.

**Comment by kostadin24** [comment]
Any way to obtain queue status/size via request?
It wil be good if usage is growing and system needs upgrade.

**Comment by danpat** [comment]
No, there is currently no way to gain this insight.

You should monitor CPU usage and API response times from an external service.  If requests are slowing down, you've saturated `osrm-routed`.
