### ISSUE TITLE
osrm-extract stuck at "Parsing in progress.."

### ISSUE THREAD

**Issue by p4bloch** [Project-OSRM/osrm-backend#1773]
I'm trying to extract `new-york_new-york.osm.pbf` with a modified bicycle profile which tries to use a table on a postgresql (see link below to the profile) and when I run `osrm-extract` it gets stucked in `[info] Parsing in progress..` it stayed `18 hours` with that message (and no huge cpu or memory usage).

Here's the [bicycle.lua profile](https://gist.github.com/p4bloch/e2e282e59afaad303cdb) I'm using.

Maybe the connection to the pgsql is not done properly, but I don't see any relevant error on its output. What do you recommend to debug what the profile is doing, or how to know when/if it dies?

Thank you

**Comment by danpat** [comment]
Have you tried running the standard bicycle profile without the Postgresql connection?  How much memory does your machine have?

**Comment by MoKob** [comment]
To me it looks like the profile you've supplied might be broken. Around line 227, it looks like either a function is missing or the return should not be there.

Can you verify whether the profile you are using is correct?

**Comment by p4bloch** [comment]
@danpat without the postgresql connection it works great. We have a VPS with 1GB RAM and 3GB swap, which was enough to extract without the postgresql stuff.

@MoKob it'd be super helpful to test the profile without actually running it within osrm-extract, or at least have some prints in the stdout from within the profile in the extract process... how can one debug this process efficiently?

**Comment by emiltin** [comment]
tips for debugging:
- try running a very small extract, possible an .osm file that you can inspect manually.
- you can print from lua. to avoid printing too much, us an if statement to only print when the osm id matches a known value.

**Comment by p4bloch** [comment]
Thanks for the tips, @emiltin, it really helped me.
Just used a smaller pbf for the extract and the compiler throwed the error right away.

**Comment by emiltin** [comment]
good to hear. what are you doing with osrm, sql and bicycles? working with ibikecph.dk i'm of course curious :-)

**Comment by p4bloch** [comment]
@emiltin yes! ibikecph, of course! I'm working with [Bikestorming](http://twitter.com/bikestorming), now trying to see if we can use OSRM to offer better/custom routing for NYC :)

**Comment by emiltin** [comment]
cool. can you say anything about how you're going beyond osm data?

**Comment by TheMarex** [comment]
This is fixed then right? Can we close here?

**Comment by MoKob** [comment]
Closing, as it seems fixed.
