### ISSUE TITLE
Windows service for routed engine. Place to keep.

### ISSUE THREAD

**Issue by kostadin24** [Project-OSRM/osrm-backend#1781]
I made windows service to start routed engine. It works fine. Now I'm wondering where to place code - in osrm-backend project or in separate project?
As far as osrm-backend is not focused on specific operating system - probably better way is to keep service in separate project. From other side after each new release of osrm-backend I have to configure sources, includes, libs and etc.

**Comment by TheMarex** [comment]
@kostadin24 would that be something you can add to [the wiki](https://github.com/Project-OSRM/osrm-backend/wiki).

**Comment by richbleeker** [comment]
@kostadin24 I am interested in using your solution, if possible? Could you give me more details?
