### ISSUE TITLE
Missing pkg-config Libs.private libraries

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#1786]
The pkg-config file only lists Boost in Libs.private, but we surely use more, e.g. zlib, expat etc. from libosmium.

https://github.com/Project-OSRM/osrm-backend/blob/d8ca58a04e6e2cd6ab34569682fca6bf2ef35c6a/cmake/pkgconfig.in

**Comment by TheMarex** [comment]
Should be fixed in `4.9.0`-
