### ISSUE TITLE
test protobuffer import without requiring osmosis/JAVA

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1788]
testing pbf import currently uses osmosis, which requires a java installation. if you don't have one, you will get a system popup on os x asking if if you want to install java.

osmosis is used for converting xml (.osm) to pbf.

**Comment by daniel-j-h** [comment]
libosmium comes with a tool that is able to convert from osm xml to osm pbf --- but that's not all we're using osmosis for, is it?

**Comment by TheMarex** [comment]
@daniel-j-h I actually think that is the only current usecase. That is the only reference that I found grepping for osmosis.

```
unless system "osmosis --read-xml #{osm_file}.osm --write-pbf #{osm_file}.osm.pbf omitmetadata=true >>#{PREPROCESS_LOG_FILE} 2>&1"
```

**Comment by emiltin** [comment]
yes only use. does libosmium come with a binary for converting?
another solution would be to include a pbf file in the repo, but i think it would make it less flexible and clear what we're testing.

**Comment by lonvia** [comment]
Is this conversion even needed now that the osm data is parsed with libosmium? It should be able to read the xml directly.

**Comment by emiltin** [comment]
the default for tests is to load xml. but if we want to also test loading pbf files we need a few tests that load pbf files.

**Comment by lonvia** [comment]
In theory it would be the job of the libosmium test suite to check that pbf is read correctly in terms of content. Consequently, it would be completely sufficient to have a single test that reads a fixed pbf file and makes sure that libosmium is used correctly by OSRM. In practice, it all depends on how much you trust libosmium.

**Comment by TheMarex** [comment]
Since this are integration tests we want to make sure our whole stack is working, so we should probably not just drop the tests. In any case its just like three test cases, we don't rerun all test on `pbf` and `xml`.

 :+1: for removing osmosis and replacing with the equivalent `osmium` based tool.

**Comment by emiltin** [comment]
osmium is build with c++, so we would get rid of java?

**Comment by daniel-j-h** [comment]
@emiltin note that you have to build [osmium_convert](https://github.com/osmcode/libosmium/blob/0008e8c2de92583bcf7ae2984a6b588fd8e84446/examples/osmium_convert.cpp) explicitely by means of setting [`BUILD_EXAMPLES`](https://github.com/osmcode/libosmium/blob/0008e8c2de92583bcf7ae2984a6b588fd8e84446/CMakeLists.txt#L50).

Right now, we do not build the examples, but use libosmium as header only drop-in.

**Comment by emiltin** [comment]
we would then build the osmium tools as part of the osrm build process?

**Comment by daniel-j-h** [comment]
Correct; without building the tests or other features, just the examples. Then use the `osmium_convert` tool to convert between xml and pbf.

**Comment by daniel-j-h** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/1877 rips out osmosis / the java dependency.
