### ISSUE TITLE
Add option to disable hint_data output.

### ISSUE THREAD

**Issue by ardanika** [Project-OSRM/osrm-backend#1789]
When using the Match service, the response contains hint_data. This additional data doubles the size of the response from the match query and is not needed unless you're also using the viaroute service. It would be nice to have a command line option or service request parameter that disables the output of hint_data at least for the Match service.

**Comment by daniel-j-h** [comment]
The v5 API still sends the hint every time:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

Did we forget to add a switch for that during the v4 -> v5 transition or what is the idea behind it? @TheMarex
