### ISSUE TITLE
forbid an specific type of edge to enter the routing

### ISSUE THREAD

**Issue by george-silva** [Project-OSRM/osrm-backend#1790]
Hello guys,

I have a very specific need but it does not look like I'm being to handle it.

Well, just want to route on a specific type of edge, which has an specific name, let's say foo.

Basically, from looking at the other examples, I'm just returning an empty result on the way_function on my profile.

Example:

```lua
  if "foo" ~= ref and "foo" ~= name then
    return
  end
```
What is the best way to exclude other ways from routing?

**Comment by TheMarex** [comment]
instead of just `return` set `result.forward_mode = 0` and `result.backward_mode = 0`.

**Comment by george-silva** [comment]
Cool. Let me try.

**Comment by emiltin** [comment]
@TheMarex but it can make improve performance to return immediately after you set mode to 0, right?

**Comment by TheMarex** [comment]
@emiltin yes of course.
