### ISSUE TITLE
Not routing from the nearest turn-restrictions

### ISSUE THREAD

**Issue by srividyacb** [Project-OSRM/osrm-backend#1794]
Not snapping to the nearest road when near the turn-restriction.

[Link](https://www.mapbox.com/osrm-frontend-v2/?z=18&center=48.245043%2C14.236945&loc=48.244817%2C14.237250&loc=48.245268%2C14.236640&hl=en&ly=&alt=&df=&srv=) to OSRM

When the start point is near the turn restriction, the routing fails instead of snapping to the nearest road out. 

[Link](http://www.openstreetmap.org/#map=19/48.24501/14.23736) to area in OpenStreetMap.

![screenshot 2015-11-25 17 03 42](https://cloud.githubusercontent.com/assets/3423533/11396299/883a87b8-9396-11e5-8896-03c0b68af578.png)

![ddd](https://cloud.githubusercontent.com/assets/3423533/11397009/1903543c-939c-11e5-9783-81ae1ea15237.gif)

cc @TheMarex

**Comment by MoKob** [comment]
Seems to work in the current hierarchy. Are there other places where this still occurs, or is this actually fixed?

**Comment by srividyacb** [comment]
@MoKob 
The roads in and around this turn-restriction is not been mapped/changed from 2months. There is nothing changed for the routing to happen. I have no idea on how this is fixed as all tags looks as it is. Will post if I come across similar issue.

**Comment by TheMarex** [comment]
Fixed.
