### ISSUE TITLE
Start osrm-routed

### ISSUE THREAD

**Issue by kostadin24** [Project-OSRM/osrm-backend#1799]
Hello,
On my developer PC osrm-routed works perfect - windows 8 x64.
When I'm trying to start osrm-routed on Windows server 2003R2 Standard x64 Edition - result is:
"osrm-routed.exe is not a valid win32 application.
Do I have to install c++ runtime?

**Comment by BergWerkGIS** [comment]
Yes, you need the Visual C++ Redistributable for Visual Studio 2015:
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by kostadin24** [comment]
Version of osrm-routed is from 8 oct 2015.
After installing Visual C++ Redistributable for Visual Studio 2015:
result is the same: 'osrm-routed.exe is not a valid Win32 application'
I can't find what is missing comparing with developer machine, because on dev machine I have lot of runtimes,sdks, visual studios and stuff.

Is Windows Server 2003 R2 x64 supported by vc++2015 runtime?

**Comment by kostadin24** [comment]
Version of osrm-routed is from 8 oct 2015.
After installing Visual C++ Redistributable for Visual Studio 2015
result is the same: 'osrm-routed.exe is not a valid Win32 application'

**Comment by kostadin24** [comment]
Certainly Windows version problem - trying on Server 2008 is OK after adding runtime. Server 2003 isn't supported by Microsoft. MSDN info is false.

**Comment by BergWerkGIS** [comment]
@kostadin24 thanks for getting back, I was just starting to investigate.
