### ISSUE TITLE
Review 'Profiles' documentation

### ISSUE THREAD

**Issue by harry-wood** [Project-OSRM/osrm-backend#1800]
I've just created a new documentation page about "Profiles"

_https://github.com/Project-OSRM/osrm-backend/wiki/Profiles_

...because it seemed to be missing. I was looking for it, coming to this fresh-faced a couple of days ago.  [Richard Marsden was looking for it](https://lists.openstreetmap.org/pipermail/osrm-talk/2015-October/000961.html) and [udoh was looking for it](https://help.openstreetmap.org/questions/45999/configuring-osrm-profile).

making a minor dent in the documentation issue: https://github.com/Project-OSRM/osrm-backend/issues/1434

But I have only been looking at OSRM profiles the past couple of days, so I'm not the most qualified person to write this, so...  **needs review** I would say. In case I guessed wrongly on any of that 

Also it can be expanded. I was thinking maybe explaining some of the global variables e.g. the [speed_profile](https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/car.lua#L15) hash seems like an important one. And udoh is asking how to  "assign higher than normal cost to bridges".

**Comment by daniel-j-h** [comment]
Great that you took the time to document the profiles, I think this is where we could provide more documentation!

Small nitpicking: you don't have to symlink the profile every time, you can specify it at runtime e.g.

    osrm-extract -p ../profiles/car.lua planet-latest.osm.pbf

**Comment by harry-wood** [comment]
OK added.
Any other improvements? As mentioned, I think there's a need to explain some of the global variables. 
But if I didn't make any major gaffs, feel free to clear away this issue

**Comment by MoKob** [comment]
Should we prepare an overview of all the different features OSRM can read/use from a profile?

**Comment by JMGGarcia** [comment]
@MoKob that would be very useful, right now is a bit difficult to make any significant changes to the profile file without ruining everything. I would also recommend to specify what any of the functions receive as parameters and what they return.

**Comment by daniel-j-h** [comment]
Closing as not actionable. I removed the outdated information from the Wiki and updated it with recent and correct information: https://github.com/Project-OSRM/osrm-backend/wiki/Profiles.

Please re-open with concrete suggestions if you need more details there.

**Comment by harry-wood** [comment]
yeah this issue should've been closed back when I wrote the docs in 2015. Just wanted to ensure somebody sanity checked it back then.

Gosh. You've [blown away quite of lot of my explanation there recently](https://github.com/Project-OSRM/osrm-backend/wiki/Profiles/_compare/ae0944c3c493485af4876251068c806cb1503625...3f41657a888aa1d63943baf4ce2a9d5a4b58eeec).  Is it really no longer valid to explain the way_function etc?

**Comment by daniel-j-h** [comment]
There is no longer the profile.lua symlink and @emiltin re-wrote the car profile more or less completely, check out the way function now:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L671-L729

I think it's important to have these two profiles in there, from which users can see how the basics work:
- [profiles/testbot.lua](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/testbot.lua)
- [profiles/turnbot.lua](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/turnbot.lua)

**Comment by emiltin** [comment]
my plan is to refactor the bike and foot profile as well.
