### ISSUE TITLE
Nearest location is not routable in major german cities

### ISSUE THREAD

**Issue by dcdieci** [Project-OSRM/osrm-backend#1801]
Hi,
I try to route from some major german cities, e.g. Freiburg, Heilbronn, Erfurt .These cities have their city centre located in a pedestrian area and I get a 207 error.
Hence I want to resolve the location. But the resolved location is neither routable.
```

/nearest?loc=47.995992,7.852135
{
name: "Münsterplatz",
mapped_coordinate: [
47.996017,
7.85207
],
status: 0
}
http://40.114.149.87:5000/viaroute?loc=47.999468,7.844131&loc=47.996017,7.85207&z=1
```

Is there any option to black list theses pedestrian areas?

**Comment by TheMarex** [comment]
You can try to filter them out by modifying the `profile/car.lua` file here:

https://github.com/Project-OSRM/osrm-backend/blob/9005fe2f61aa5478c5bf0bef5ec76843af04f93e/profiles/car.lua#L219

And add something like:

```lua
if highway == "pedestrian" then
    result.forward_mode = 0
    result.backward_mode = 0
    return
end
```

**Comment by dcdieci** [comment]
@TheMarex thanks for the quick reply.
What i just tried out is blacklisting destination.

["destination"] = true,

This works for for me. But frankly speaking I am not entirely sure about side effetcs

**Comment by TheMarex** [comment]
Side effect is that you will not be able to route to roads that only allow motor vehicle access if your destination is on the road.

**Comment by dcdieci** [comment]
I just prepared the data again with 

```
if highway == "pedestrian" then
    result.forward_mode = 0
    result.backward_mode = 0
    return
end
````
and it works.
@TheMarex Thanks a lot for the swift solution!

**Comment by dcdieci** [comment]
Unfortunately I stumbled upon another scenario, where it does not work out
In this city with location 49.755413,6.639186 the nearest routable returns a street "49.755413,6.639186". But this street is bounded by a pedestrian area. So the routing fails

**Comment by TheMarex** [comment]
Sadly there is no easy way to fix these errors other than fixing the query locations.

**Comment by dcdieci** [comment]
@TheMarex Changing the location also popped into my mind. I just shift the location now by increasing the lat lon values by some "meters" until I find a routable solution.This approach works alright for me

**Comment by TheMarex** [comment]
Thanks for your feedback. Closing for now since its not acitonable.
