### ISSUE TITLE
Appvayor fails at last step

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1803]
AppVayor build tend to fail at the last step https://ci.appveyor.com/project/TheMarex/osrm-backend/build/1.0.287#L2107

@BergWerkGIS can you take a look why this happens from time to time?

**Comment by BergWerkGIS** [comment]
@TheMarex there is no FTP server address defined. You have to add it to `appveyor.yml` (publicly visible) or via project settings in the AppVeyor GUI:
https://ci.appveyor.com/project/TheMarex/osrm-backend/settings/deployment

**Comment by TheMarex** [comment]
This is fixed now after fixing the double build of PRs.
