### ISSUE TITLE
Order of via_points in /trip response

### ISSUE THREAD

**Issue by prateeksachan** [Project-OSRM/osrm-backend#1806]
Firing a query like:

`http://{IP_ADDRESS}:5000/trip?loc=18.9457243,72.8237605&loc=18.9457243,72.8237605&loc=18.9414821,72.8284626&loc=18.9457243,72.8237605&loc=18.9629992,72.8175748&loc=18.9352599,72.8371511&loc=19.1227498,72.8932321`

The order of the points in the response in `via_points` object was:

1. 19.123192,72.892303
2. 18.935261,72.837151
3. 18.941444,72.828468
4. 18.945871,72.82399
5. 18.945871,72.82399
6. 18.945871,72.82399
7. 18.962875,72.817871
8. 19.123192,72.892303

Why don't the points follow the order in which they were input in the query? Why are the points changed in `via_points` and appear slightly different than the original ones supplied in the query?

Also, is the last `loc` (in the query) always the first and last `via_point`?

**Comment by TheMarex** [comment]
@prateeksachan Changing the order of the input coordinates is exactly what `trip` is supposed to do. It finds the shortest path through that points.

If you want to have the shortest path without changing the order use `viaroute`. For more documentation see the docs https://github.com/Project-OSRM/osrm-backend/wiki/Server-api

**Comment by prateeksachan** [comment]
@TheMarex
Thanks for the insight. I was looking into an API implementation like the Google maps one, where the start and end points are fixed (and same) and optimization is done for the points between them for this complete round trip.

Thanks.
