### ISSUE TITLE
Ruby net::HTTP POST API can not handle real OSRM API

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1810]
Arguments in the OSRM API are position depended. For example:
`/viaroute?loc=1,2&b=1&loc2,3` is not the same as `/viaroute?loc=1,2&loc2,3&b=1`.

However the API for `post_form_uri` takes a `Hash` of `Arrays` which will discard the original ordering. The offending line is here:

https://github.com/Project-OSRM/osrm-backend/pull/1804/files#diff-079dd5b69545a075b484ad4b63f902f5R26

/cc @freenerd

**Comment by freenerd** [comment]
This was fixed for the tests with https://github.com/Project-OSRM/osrm-backend/pull/1838
