### ISSUE TITLE
Test cases for better turn instructions

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1816]
`5.0.0` will feature a rewrite of our API and as such we will use this opportunity to push hard on better turn instructions. Scope of this issues:

- Capture cases where our turn instructions suck
- Capture the expected response
- If possible: Capture what kind of information is needed to generate the expected response (lane count, intersection shape, context of previous 10 edges, street type etc.)

We want to use this to synthesis a new turn instruction vocabulary that goes beyond simple `Turn left/right` instructions.

/cc @MoKob @daniel-j-h

**Comment by utack** [comment]
Is "Capture cases where our turn instructions suck" done a specific way or would a simple location with turn instructions given be helpful?
I think i can remember some places and reproduce it on the demo server.

**Comment by TheMarex** [comment]
@utack specific cases are always welcome. We can aggregate them here.

**Comment by utack** [comment]
For example [this](http://map.project-osrm.org/?z=18&center=49.461210%2C11.090650&loc=49.461444%2C11.089046&loc=49.460820%2C11.091895&hl=en&ly=&alt=&df=&srv=) was the worst case I encountered. On way 283221226 It has turn lanes left:right|right and the instruction was "continue". Technically southwest clarifies it, but that is not very helpful while driving.

**Comment by daniel-j-h** [comment]
As of now we have over 4k lines of guidance cucumber test scenarios:
https://github.com/Project-OSRM/osrm-backend/tree/master/features/guidance

As an example, see this ticket for how guidance is getting attention at the moment: https://github.com/Project-OSRM/osrm-backend/issues/1395

Closing this ticket.
