### ISSUE TITLE
Assertion failure using match service

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1819]
Using `/match` and a `CMAKE_BUILD_TYPE=Debug` build from 5a9bee052753ab6c978e60ac2ca331f2ed378aa8, I am getting the following assertion for some routes:

```
Assertion failed: (search_from_forward_node == search_to_forward_node), function operator(), 
file /Users/danpat/mapbox/osrm-backend/library/../data_structures/../routing_algorithms/shortest_path.hpp, line 406.
```

**Comment by TheMarex** [comment]
@danpat can you please include the query url?

**Comment by danpat** [comment]
Fixed by https://github.com/Project-OSRM/osrm-backend/commit/24e7d00af54c51ff80c71e6468457bdb869aa98f
