### ISSUE TITLE
[Trip Plugin] Simple VRPPD addition Feature Request

### ISSUE THREAD

**Issue by Zaptor** [Project-OSRM/osrm-backend#1821]
Hi There,

Wondering if anyone would have the time to implement a simple VRP with Pickup and Delivery option into the existing Trip Plugin? I know the word "Simple" and any VRP, TSP problem do not mix...

I'm not looking for a complex solution like Jsprit with vehicle capacity and time windows etc.

I could see it working something like this request below:

/trip?loc=-79.51855,43.79877&GroupID=1876901&Priority=1&loc=-79.55859,43.78895&GroupID=1876901&Priority=2&loc=-79.51191,43.71301&GroupID=1871001&Priority=1&loc=-79.45818,43.61893&GroupID=1871001&Priority=2

Each set of locations has a unique GroupID and each location has a priority 1=Pickup 2=Deliver.

I'm not sure what the request would look like once priority 1 has been completed and only priority 2 is left in the group to complete.

Thoughts?

It's not a lot but I could offer $200usd for a working solution.  

Thanks for your time.

**Comment by jcoupey** [comment]
Hi,

Solving VRPPD doesn't sound like just an additional feature over the trip plugin to me, as it is quite a different problem altogether. ;-)

Not sure exactly what you have in mind here. Does the term "priority" relate to the approach, maybe some kind of delivery-first pick-up second strategy?

And does the GroupID information imply that you would be pre-clustering locations yourself?

**Comment by Zaptor** [comment]
Jcoupey,

The trip plugin returns an optimized route of stops which is why I thought that would be a good starting place. 

Priority is just a way of saying you have to visit priority 1 location before you can go to priority 2 location. An example is fedex has to pickup the package from amazon before they can deliver it to your home and the same fedex driver could pickup a package from walmart and deliver it to your home at the same time as the amazon package (optimized route).

Think of GroupID as a tracking number, I just didn't want to use industry terms. One GroupID (Tracking Number) contains two locations (Pickup and Deliver)

I apologize if I'm not explaining myself clear enough.

Thanks!

**Comment by jcoupey** [comment]
Ok, the use-case does make it clear. So if you don't care about capacities and all, you basically want the TSP solution to secure additional precedence constraints, right?

**Comment by Zaptor** [comment]
Capacities and all that other jazz are cool but my use case does not require them at this time.

Exactly, The other difference I believe TSP returns back to the starting point at the end of the route but that would not work for me.

**Comment by jcoupey** [comment]
The not-going-back-to-the-starting-point bit is already the subject of another topic: #1623.

**Comment by Zaptor** [comment]
How many hours do you think it would take some one with OSRM dev experience to put together what I'm looking for? 4? 40? 400?

**Comment by danpat** [comment]
@Zaptor I'd ballpark it in the 200hrs+ kind of range to get it right, tested and integrated properly, possibly longer.  I would recommend looking again at jsprit, and the VRPPD module: https://github.com/jsprit/jsprit/wiki/Benchmark-VRPPD

You would use OSRM in combination with jsprit.  OSRM for the distance tables, jsprit to solve the VRPPD problem.

**Comment by daniel-j-h** [comment]
As one example for my FFI bindings https://github.com/daniel-j-h/libosrmc I integrated Google's Operations Research Tools (or-tools). With it you can use OSRM's distance tables as a building block to solve more complex vehicle routing problems.

**Comment by daniel-j-h** [comment]
Closing here => https://github.com/mapbox/node-or-tools
