### ISSUE TITLE
.hsgr not found

### ISSUE THREAD

**Issue by EvanOdell** [Project-OSRM/osrm-backend#1829]
When I'm trying to run ./osrm-routed on my own local server I get the following error:

    Evan-Odells-MacBook-Pro:build evan odell$ ./osrm-routed england-latest.osrm.
    [info] starting up engines, v4.9.0
    [info] populating base path: england-latest.osrm.
    [warn] [exception] .hsgr not found

What could be causing this? england-latest.osrm.hsgr is in my build directory after running ./osrm-extract and ./osrm-prepare, but ./osrm-routed isn't able to identify it.

**Comment by danpat** [comment]
@EvanOdell You've got a trailing period at the end of your `.osrm` filename.  You need to remove that.
