### ISSUE TITLE
Load arbitrary turn costs from data files

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1830]
The edge-based graph edge weights are made up of two parts: cost values from traversing node-based-edges (segments), and costs from turning movements.

OSRM already has the ability to load arbitrary segment speed values from files prior to graph contraction [see here](https://github.com/Project-OSRM/osrm-backend/blob/da11113bf1becaf0de2c59ad9d157ec5edb19aa3/contractor/processing_chain.cpp#L177-L190).  However, the turning movement costs are currently only set by the Lua profile, and are not adjustable on a per-intersection basis.

If real measurements are available, we should be able to load them in at the same time.

OSRM identifies a *turning movement* using 3 node-based-nodes: u, v, w

```
    u
    |
    v---w
    |
   ...
```

The angle between uv and uw is what is currently passed to the `turn_function` in the Lua profile.

I propose we take a similar approach here to what was done for the segment speed lookups:

  1.   During generation of the edge-based-graph, write out a lookup file between the three nodes involved in the uvw turn, and the new edge-based-edge ID.  Node order is important, as it specifies which turn through an intersection has been taken.
  2.  An offline process can use the original OSM geometry and output a file that contains:
    `u,v,w,duration` (perhaps CSV to keep things simple?)
  3.  During `osrm-prepare`, as the edge-based graph is loaded, we can use the lookup file from (1) in combination with data generated offline in (2) to set a "real" value for the turn penalty, rather than simply basing it on the results of the `turn_function`.  This would slot right in [here](https://github.com/Project-OSRM/osrm-backend/blob/da11113bf1becaf0de2c59ad9d157ec5edb19aa3/contractor/processing_chain.cpp#L262).

Out of scope for this feature is discussing exactly what the weight value represents or how these turn costs are actually measured.  It would be great to see some exploration in this space

**Comment by TheMarex** [comment]
What we want to model with turn penalties is: `how long does a car take to cross an intersection`. 

![turn_model](https://cloud.githubusercontent.com/assets/606968/11900314/70a1a250-a5a5-11e5-8af6-d3d8b34af131.png)

Our current weight for a arc in the edge-based graph is the weight of the blue segment. The assumption here is that streets don't have an area and can thus be represented by their center lines.

However in reality streets do have an area and intersections as well (:wave: grid system cities). And we need to somehow capture the added time it takes to make a turn. A simplistic solution would be to measure the time that it takes a driver to cover the dark-gray area. However just adding that to the weight of the blue segment would measure the part of the blue segment (the part that is covered by the intersection) twice. We could adjust for that, but it would require a lot of tuning.

A more simple approach would be to measure all trips going from the blue to the red node and figure out how much is not accounted for by the given edge weights. That would mean we already need a model for each edge, subtract both values from the trip time which yields the "turn time".

**Comment by emiltin** [comment]
A turn typically requires you to lower your speed, with a sharper turn requiring a bigger slow down. You typically brake before the turn, and accelerate after, so just measuring the time inside the grey area where the actual turn happens might not be enough.

**Comment by emiltin** [comment]
If you're thinking of somehow measuring the delay of each turn (GPS data?) in intersections, I think you will find that the traffic signals cause much more variance in delay than the geometry of the turn. Even in the same intersection, signal programs typically change for morning/day/evening.

For this reason i doubt how much an improvement a turn-penalty file will provide, compared to a heuristic like computing the delay based on angle. I think the ability to factor in the from/to way types and intersection tags would be an easier way to improve turn costs.

For example, for bikes a common situation is that turning left from a big road into a smaller sideroad is typically incurs more delay if there's no traffic signals.

**Comment by danpat** [comment]
@emiltin One of the motivating factors for us is time-of-day variance.  Some turns are fast at midnight, but incur significant delays during rush hour, even when the streets they are between are relatively free-flowing.  During high-traffic times, turning across traffic (left in the US) is often much more expensive than hugging the corner (turning right in the US).

Per-intersection turn costs will also allow us to support driving-on-the-left-vs-driving-on-the-right penalties, as long as the offline generation of the turn costs knows how to identify the driving side.

Another motivator is missing meta-data in OSM, and the lack of consensus for partial stop-sign implementations for partially stop-signed intersections.  We look at driving in San Francisco a lot, where there are lots of grid-like streets, and stop-signs, many of which are poorly labelled in OSM.  Per-intersection analysis of GPS data lets us assign penalties to intersections where the OSM meta-data has nothing to say, for various reasons, and we can use the difference between the OSRM default penalty and the a data-based penalty to highlight locations in OSM that might need attention.

**Comment by emiltin** [comment]
alright i see. one challenge with the approach could be that without enough gps data, and advanced processing of the data, for the mode in question you cannot get good turn costs. in other words, osm data is not enough anymore

**Comment by danpat** [comment]
@TheMarex We currently set the weights in the edge-based graph as AB+turn:

![screen shot 2015-12-24 at 7 58 55 am](https://cloud.githubusercontent.com/assets/1892250/11996273/4113969c-aa14-11e5-9a72-96b413f67f13.png)

However, we could also do AB/2 + BC/2 + turn.  Doing this might eliminate the question of "how much of AB and BC do we remove to allow for the turn delay".

We would need to modify the phantom node offset logic (eek!), but otherwise, if just `car.lua` was used, the results should be the same.  However, this does make it a lot simpler to use GPS data to measure timings from midpoints, and then simply import it.

If done like this, then we would not import turn penalties, but rather complete edge-based-edge weights based on offline-processed data.

**Comment by MoKob** [comment]
I have to say that I do not see any benefit in changing the model in the graph.
The way we measure the added time for a turn is independent of the routing representation, isn't it?
With the current model, the car simply turns on the spot an continues driving along a new segment. The turn on the spot takes a different time, which is the turn penalty from the file. Given a trace, we can compute penalties just like you propose in the AB/2 + BC/2 + turn way in comparison to an expected through speed (simply distance divided by average speed). The difference between the two would be the turn penalty.
In the actual graph logic, we do not have to change the phantom n ode logic, or am I missing something?

**Comment by danpat** [comment]
@MoKob The main reason to move to AB/2+BC/2 would be to make it consistent about how to make real-world measurements.  Instead of needing to decide things like "what distance do I start measuring the intersection from", you just do everything from halfway points.

It seems like this might make phantom node offsets complicated - if AB/2 != BC/2, then linear interpolation won't get the correct offset.  So we'd gain a simpler model for performing real-world measurements, but end up with more complicated offset calculation (if it's even possible, I don't know, I'm just thinking out loud here).

**Comment by MoKob** [comment]
@danpat I still think there is a difference between measuring the turn cost and the representation in the routing. 
For me, the turn cost is the additional cost in relation to a "ideal" world in which we can with full speed.
Consider `a-b-c` in a `node-based` graph. Our current model uses the `nodes` `(ab)` and `(bc)`. The cost in the phantom node is the cost of traversing The arc connecting `ab` to `bc` consists of the cost for traversing `ab` and the additional cost for the turn `t_1`. The same way, we have an arc from `bc` to `ab` for the cost of traversing `bc` and performing the turn `t_2`.

The traversal cost are computed at free-flow speed.

Why cant we keep this model in the graph and simply assign `t_1` = c(AB/2 -> BC/2)-(ab/2+bc/2), so the difference of the measured speed.

The part we currently do not consider at all is a penalty for accelerating / decelerating in the begin/end of a journey. But The turn-model in the graph itself is independent of the measurement, isn't it? Technically we would be slightly inaccurate if the journey ends directly after the turn. But that could not be corrected for either, if we were to locate the phantom nodes at the middle of the segments.

**Comment by danpat** [comment]
Specifically, this is where we would replace the "fixed penalty" with the new value: https://github.com/Project-OSRM/osrm-backend/blob/develop/src/contractor/contractor.cpp#L417

**Comment by danpat** [comment]
The data file format for this feature will be CSV (similar to edge-weight imports).  The form will be:

`from-node,via-node,to-node,duration`

Where the `-node` values are directly connected OSM node ids, and the `duration` is a value in seconds.

We'll need to create a turn-to-edge-based-node lookup file using the three node IDs available here:

https://github.com/Project-OSRM/osrm-backend/blob/develop/src/extractor/edge_based_graph_factory.cpp#L911-L912

**Comment by mvl22** [comment]
What narration (if any) in the import indicates that the turns file has been read correctly?

I realise that if the file is not in the right format, and error is given, but is there actually a confirmation line about the number of confirmed node trios?

**Comment by daniel-j-h** [comment]
See

- https://github.com/Project-OSRM/osrm-backend/blob/110e6c36895fc488fde6150e74713bce26ab7125/src/contractor/contractor.cpp#L431-L432
- https://github.com/Project-OSRM/osrm-backend/blob/110e6c36895fc488fde6150e74713bce26ab7125/src/contractor/contractor.cpp#L466-L468
