### ISSUE TITLE
Time matrix to distance calculation

### ISSUE THREAD

**Issue by faheemmughal** [Project-OSRM/osrm-backend#1831]
Is there a way to approximate the distance in meters from travel time returned by table service? Would the following work: Say 10 second travel time is equal to 10*x for car where car is a modified car profile to have uniform speed everywhere?

**Comment by emiltin** [comment]
yes, if you set the same speed for all ways, you can compute the distance easily, but the routes will be unrealistic.

**Comment by faheemmughal** [comment]
ah snap. I thought I had something there. Really need distance matrix and my C-jutsu is just not that strong to implement myself.

**Comment by TheMarex** [comment]
@faheemmughal just make a profile that sets `result.forward_speed = 3.6` and `result.backward_speed = 3.6` (== 1 meter/second). Then the entries in the table will correspond to the distance value.

But as @emiltin already pointed out this will lead to routes that are _shortest distance_ - which in most cases is not the fastest route.

There is already an issue on returning both, closing here for now.

**Comment by sweco-semtne** [comment]
@TheMarex Is there an example of such a profile available somewhere?

**Comment by daniel-j-h** [comment]
@sweco-semtne you can use the default car profile and scale both forward and backward speed there as described above: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua

**Comment by emregurler** [comment]
@TheMarex and @daniel-j-h you said that we should set result.backward_speed and also forward speed to 3.6. I have 2 questions for this:
1- What is difference between setting these values and changing weight_name in car.lua as "distance" ? Will outputs same or not?
2- I am not close with lua language and also this project structure. If setting "result.forward_speed" and "result.backward_speed" are only way to get distance based table, where should we actually set these values? I am just guessing about it.  I think I set in process_way function in car.lua, am I wrong? 
Forgive me for these easy questions, thanks.

**Comment by danpat** [comment]
@emregurler This ticket is now somewhat deprecated.

OSRM 5.16 supports a new parameter that looks like `&annotations=distances,durations` which will return distances in the `/table` response structure.

No need to do weighting tricks like this any more.

**Comment by emregurler** [comment]
Oh my god, how did I miss. Thank you. Is there any limit for ? I set `max table size` to 5000, while I was using duration table. Is  this enough to get distance matrix of 5000 nodes ?

**Comment by danpat** [comment]
@emregurler if you're running your own instance, then there's no limit, just your available CPU and RAM.

Note that requests will be quite a bit slower if you request distances - a bunch of extra calculations have to be made that are avoided if you only request durations.

**Comment by emregurler** [comment]
Thank you @danpat . Nice to see this feature :)
