### ISSUE TITLE
missing dependencies for Debian Wheezy in documentation

### ISSUE THREAD

**Issue by madbob** [Project-OSRM/osrm-backend#1833]
In the page
https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM#debian-wheezy
there should be listed also `libosmpbf-dev` and `libprotobuf-dev` as dependencies installable by `apt-get`.
Source: http://gis.stackexchange.com/questions/161955/trying-to-build-osrm-could-not-find-osmpbf
Verified, and works.

**Comment by daniel-j-h** [comment]
This is not needed, since we're using a recent libosmium release that includes protozero for protobuf handling itself. If you're on develop or master (that is, a stable release), you do not need the protobuf dependencies.

**Comment by madbob** [comment]
No, I'm not referring to master branch. Accordly to the documentation and to comments in #1333, on Debian Wheezy I'm compiling release 4.4.0.

**Comment by daniel-j-h** [comment]
OSRM 4.4.0 is over a year old. We don't support that version anymore and strongly recommend you update to the latest release / the master branch. If you check the Wiki's history, it was updated to be in sync. with the libosmium changes.
