### ISSUE TITLE
CentOS Install Script Doesn't Git Latest

### ISSUE THREAD

**Issue by elemenopy** [Project-OSRM/osrm-backend#1837]
[extractor] Sorting used ways         ... ok, after 6.02684s
[extractor] Sorting restrctns. by from... ok, after 7.0578s
[extractor] Fixing restriction starts ... ok, after 8.02402s
[extractor] Sorting restrctns. by to  ... ok, after 0.00833201s
[extractor] Fixing restriction ends   ... ok, after 2.39055s
[info] usable restrictions: 46546
[extractor] Confirming/Writing used nodes     ... ok, after 201.625s
[extractor] setting number of nodes   ... ok
[extractor] Sorting edges by start    ...

Restrictions is spelled wrong :)

**Comment by danpat** [comment]
@elemenopy Wanna make a pull request?

**Comment by elemenopy** [comment]
This appears to be a weird bug that is not in the latest version. I did some research and discovered that the documentation at https://github.com/Project-OSRM/osrm-backend/wiki/Bulding-OSRM-backend-on-CentOS-6 actually has a script that performs an install. If you read towards the bottom of the script you can see that it is installing version 3.7. The typo existed in 3.7 but no longer does. Can someone modding this by chance publish an updated CentOS script for us?

**Comment by danpat** [comment]
@elemenopy Can you confirm that simply replacing `0.3.7` with `4.8.1` works for those instructions?  If so, I'll update the script.  Note that 0.3.7 was published on Nov 20, 2013...a lot has changed since then!

**Comment by elemenopy** [comment]
Yea I am having a cloud instance spun up now with nothing but SSD's. When it's online I can deploy to that much faster and leave this instance running / routing to not cause interruption.

**Comment by elemenopy** [comment]
Yes replacing that version number seems to have worked miracles from top to bottom. Everything is running smoothly and this is on the latest weekly geofabrik.de download for Texas. I did not see any errors at any point and everything compiled fine. Below is the suggested block for the download version.

#Installing OSRM package
cd /opt
wget -O Project-OSRM-4.8.1.zip https://github.com/DennisOSRM/Project-OSRM/archive/v4.8.1.zip
unzip Project-OSRM-4.8.1.zip
cd osrm-backend-4.8.1
sed -i 's| -pedantic||' CMakeLists.txt
mkdir build
cd build
cmake -DLUABIND_INCLUDE_DIR=/opt/osrm_infrastructure/luabind-0.9.1/include -DLUABIND_LIBRARY=/opt/osrm_infrastructure/luabind-0.9.1/lib/libluabindd.so -DLUAJIT_LIBRARIES=/opt/osrm_infrastructure/LuaJIT-2.0.2/lib/libluajit-5.1.so -DLUAJIT_INCLUDE_DIR=/opt/osrm_infrastructure/LuaJIT-2.0.2/include/ -DSTXXL_LIBRARY=/opt/osrm_infrastructure/stxx/lib/libstxxl.a -DSTXXL_INCLUDE_DIR=/opt/osrm_infrastructure/stxx/include -DOSMPBF_LIBRARY=/tmp/OSM-binary/build/src/libosmpbf.a -DOSMPBF_INCLUDE_DIR=/tmp/OSM-binary/include -DBOOST_ROOT=/tmp/boost_1_57_0 -DBOOST_LIBRARYDIR=/tmp/boost_1_57_0/lib ..
make -j$Threads

**Comment by danpat** [comment]
Awesome, thanks for confirming.  I've updated the wiki page for CentOS to point to the more recent version.
