### ISSUE TITLE
local server returns {"status_message":"Cannot find route between points","status":207}

### ISSUE THREAD

**Issue by browarq** [Project-OSRM/osrm-backend#1843]
/usr/local/bin/osrm-routed -p 5000 europe-latest.osrm

When I try to find a route via link

http://myserver:5000/viaroute?loc=50.254874,19.187408&loc=50.1364042,14.4504888

I`ve got response 

{"status_message":"Cannot find route between points","status":207}

This is only for some routes only
Strange is that when i try to find a route via http://router.project-osrm.org/viaroute?loc=50.254874,19.187408&loc=50.1364042,14.4504888
then this service return route

I think so that there is something in my server settings but I don`t know what i sholud check more. 
Bellow there is output from myserver

[warn] /usr/local/bin/osrm-routed could not be locked to RAM
[info] starting up engines, v4.5.0
[info] populating base path: europe-latest.osrm
[info] HSGR file:       "europe-latest.osrm.hsgr"
[info] loading graph data
[info] loading graph from europe-latest.osrm.hsgr
[info] number_of_nodes: 82154350, number_of_edges: 399249784
[info] loaded 82154350 nodes and 399249784 edges
[info] Data checksum is 788891594
[info] loading edge information
[info] loading geometries
[info] loading r-tree
[info] loading timestamp
[info] Loading Timestamp
[info] loading street names
[info] loaded plugin: table
[info] loaded plugin: hello
[info] loaded plugin: locate
[info] loaded plugin: nearest
[info] loaded plugin: timestamp
[info] loaded plugin: viaroute
[info] http 1.1 compression handled by zlib version 1.2.8
[info] running and waiting for requests
[info] 29-12-2015 15:37:31 172.28.110.165 - Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0 /viaroute?loc=50.254874,19.187408&loc=50.1364042,14.4504888

**Comment by TheMarex** [comment]
@browarq what OSRM version are you using? `4.9.0`?

**Comment by browarq** [comment]
Hi , my current version is 4.5.0


2015-12-29 22:10 GMT+01:00 Patrick Niklaus <notifications@github.com>:

**Comment by TheMarex** [comment]
Please try 4.9.0.

**Comment by browarq** [comment]
@TheMarex it works at 4.9.0, thank You for help.
