### ISSUE TITLE
Actual system requirements for full planet

### ISSUE THREAD

**Issue by kudm761** [Project-OSRM/osrm-backend#1845]
Hello, 
what are the actual system requirements for planet-latest.osm.pbf ?
Is it possible to extract, prepare + routed with 64 GB RAM?
What size of swap and stxxl should i have with 64 GB RAM and what is the total size of all resulting files? (i want to know final capacity of SSD disk for all operations)
Thank you!

**Comment by TheMarex** [comment]
Depends on the profile.Our demo server runs with 128GB RAM and 220GB stxxl, 100GB swap. Might be a little too large, but you need to measure this yourself.

**Comment by kudm761** [comment]
We use default car profile, is it possible to handle planet with 64GB RAM and 200GB swap SSD for example?

**Comment by danpat** [comment]
Hi Dmitry,

  Yes, but it will be *very* slow.  Processing using the default car profile uses about 90GB of RAM, and 200GB of STXXL files, in addition to the data files that are generated (about another 100GB).  If you only have 64GB of RAM, you can always use swap space to make up the extra 30-40GB, but it makes processing very very slow.

daniel

**Comment by kudm761** [comment]
Guys, thank you for detailed explanation!
