### ISSUE TITLE
Problem with osrm-prepare

### ISSUE THREAD

**Issue by browarq** [Project-OSRM/osrm-backend#1846]
Hi,
I made upgradre to 4.9.0
osrm-extract output give following result :

[info]   contains 157057719 edges
[info]   skips 317995 turns, defined by 256158 restrictions
[info]   skips 68300172 U turns
[info]   skips 125157 turns over barriers
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 3.28768s
[info] Generating nodes: 86.1526s
[info] Generating edges: 424.353s
[info] building r-tree ...
[info] large component [27903]=81690767
[info] large component [28611]=1418
[info] large component [29038]=1749
[info] large component [29301]=10156
[info] large component [29367]=21920
[info] large component [29982]=3404
[info] large component [30239]=1464
[info] large component [34903]=3769
[info] large component [35764]=1438
[info] large component [36620]=1142
[info] large component [36873]=1527
[info] large component [37078]=26236
[info] large component [40084]=1135
[info] large component [40384]=2947
[info] large component [40511]=1676
[info] large component [42998]=2338
[info] large component [44368]=1917
[info] large component [52477]=9861
[info] large component [52485]=1224
[info] large component [61839]=1020
[info] large component [70257]=1306
[info] large component [73387]=1654
[info] large component [81217]=1717
[info] large component [84819]=1008
[info] large component [101592]=1062
[info] SCC run took: 12.564s
[info] constructing r-tree of 193683712 edge elements build on-top of 184616322 coordinates
[info] finished r-tree construction in 121.216 seconds
[info] writing node map ...
[extractor] Writing edge-based-graph egdes       ... ok, after 2.33105s
[info] Processed 157057719 edges
[info] Expansion  : 191560 nodes/sec and 85657 edges/sec
[info] To prepare the data for routing, run: ./osrm-prepare /data/osm/osrm-backend/europe-latest.osrm

But when i try to make osrm-prepare 
/usr/local/bin/osrm-prepare -t 16  -p "/data/osm/osrm-backend/profile.lua"   /data/osm/osrm-backend/europe-latest.osrm > europe-prepare.2015.12.31.log

I get only following warining 
[warn] The recommended number of threads is 4! This setting may have performance side-effects.
[warn] [exception] osrm input file misses magic number. Check or reprocess the file

I see that europe-latest.osrm.ebg file is empty but I don`t know that is fine or not.

 8306138968 Dec 31 11:50 europe-latest.osrm
          0 Dec 31 12:10 europe-latest.osrm.ebg
 1884692632 Dec 31 12:07 europe-latest.osrm.edges
 9294465644 Dec 31 12:10 europe-latest.osrm.fileIndex
 1626686492 Dec 31 11:58 europe-latest.osrm.geometry
   52087753 Dec 31 11:51 europe-latest.osrm.names
  589066240 Dec 31 12:10 europe-latest.osrm.nodes
   53015188 Dec 31 12:10 europe-latest.osrm.ramIndex
    8223580 Dec 31 11:51 europe-latest.osrm.restrictions
         20 Dec 31 09:16 europe-latest.osrm.timestamp

**Comment by TheMarex** [comment]
@browarq maybe you ran out of disk space? The file should not be empty.

**Comment by browarq** [comment]
I will try on second disk

Pozdrawiam
Piotr Chmielnik

2016-01-04 10:22 GMT+01:00 Patrick Niklaus <notifications@github.com>:

**Comment by browarq** [comment]
@TheMarex It was problem with disc space, thank You for help :)
