### ISSUE TITLE
total distance != sum(route_instructions)

### ISSUE THREAD

**Issue by root-11** [Project-OSRM/osrm-backend#1849]
When routing I get a difference of 1.422 km on 1335 km between ['route_summary']['total_distance'] and summing up the values in ['route_instructions']

Am I missing some logic or is it a bug?

    sum(int(i[2]) for i in d['route_instructions']),   # summing the meter integer field = 1336186
    d['route_summary']['total_distance'] # reading the sum provided by the web api  = 1337608
    difference = 1422 # meters.

[result_dict.txt](https://github.com/Project-OSRM/osrm-backend/files/76997/result_dict.txt)

**Comment by daniel-j-h** [comment]
Thanks for reporting!

This is already tracked in ticket https://github.com/Project-OSRM/osrm-backend/issues/1575. Closing here in favor of the already existing ticket.
