### ISSUE TITLE
Prepare a graph without alleys

### ISSUE THREAD

**Issue by evz** [Project-OSRM/osrm-backend#1852]
I'm attempting to prepare a graph which excludes alleys. In the Wiki you mention that this kind of thing should be done in the `profile.lua` script. What I'm not entirely sure about is where to place the restriction. Is it a `service_tag_restriction` or part of a `service_tag_blacklist`? When I regenerate the graph with directives such as: 

```
service_tag_restricted = { ["parking_aisle"] = true, ["alley"] = true }
```

or:

```
service_tag_blacklist = { ["alley"] = true }
```

It seems like it's generating the same graph. Thanks for any help you can offer!

**Comment by fgregg** [comment]
Can you add your lua file to the repo?

**Comment by rparanjpe-tesla** [comment]
Does your osm have ways with the key-value pair for service-alley? e.g.
```<way id="12345">
<tag k="service" v="alley" />
</way>```

**Comment by evz** [comment]
Yeah. I'm using the [Chicago metro extract from Mapzen](https://mapzen.com/data/metro-extracts/) and a quick grep of the osm xml file gives me ~15,000 ways that are tagged that way. 

```
$ grep chicago_illinois.osm -i '<tag k="service" v="alley"/>' | wc -l
15129
```

I guess more to the point, the directives that I am adding into the ``profile.lua`` script should be working? Which one? The blacklist approach or the restricted approach? Should I do both?

**Comment by danpat** [comment]
@evz To exclude a way from the routing graph, you basically need to get the `way_function` to return before populating anything in the `result` object.  An example is here:

https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/car.lua#L244-L247

The most straightforward thing to do is probably to just add the following [here (line 248)](https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/car.lua#L248):

    local alley_tag = way:get_value_by_key("service")
    if service and service == "alley" then
        return
    end

You also add `service` into `access_tags_heirachy` and `["alley"] = true` into `access_tag_blacklist` which *should* have the same effect (it will trigger a condition to make the `way_function` return [here](https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/car.lua#L244)

**Comment by rparanjpe-tesla** [comment]
@danpat I think you meant to write `local service = way:get_value_by_key("service")`

**Comment by danpat** [comment]
Oh dang it, edited above.

**Comment by evz** [comment]
Thanks! That seems to have done the trick!
