### ISSUE TITLE
Consuming huge distance tables

### ISSUE THREAD

**Issue by kostadin24** [Project-OSRM/osrm-backend#1856]
Hello,
I made request for 10k x 10k table. Time and ram for computation are acceptable for me.
The annoying thing is speed of consuming result.
As far as I succeeded to measure time spent for request and time for parsing result - 50-60% of time gone to parse json. For parse I'm using newtonJSON in C#.
Of course I will write custom parser, because structure of response is not complex.
But... Is there another way to consume result? Because engine construct json and after that immediately json has to be converted back to objects.
Consuming directly result as object will be great.

**Comment by emiltin** [comment]
You can compile osrm into your own c++ code and get direct access to the various results.

**Comment by kostadin24** [comment]
Yep! From the other side - is it good idea to use swig?
For example or-tools allows to use c++ based engine in .net projects.

**Comment by daniel-j-h** [comment]
This is a good starting point for using `libosrm`:
- Wiki https://github.com/Project-OSRM/osrm-backend/wiki/Library-api
- Interface https://github.com/Project-OSRM/osrm-backend/tree/v4.9.0/include/osrm
- Example https://github.com/Project-OSRM/osrm-backend/blob/v4.9.0/tools/simpleclient.cpp

If you need a C API there is `osrm-c` which might be helpful:
- https://github.com/tdihp/osrm-c
