### ISSUE TITLE
Crash at first request to osrm-backend [Windows x64]

### ISSUE THREAD

**Issue by SergeFranchois** [Project-OSRM/osrm-backend#1859]
Build : v4.5.0-647-g3e113db, but seen on any recent successful build (Windows).
Tag: @BergWerkGIS 
Issue: At the first request, the osrm-backend crashes with "osrm-backend has stopped working"
Platform : Windows 7 x64

Reproduction: 
download the above build (or any recent successful build FWIW)
unzip in a folder
start the backend binary with a valid osrm file. I used illinois-latest.osrm from mapzen.com. No other options 

C:\osrm2>osrm-routed.exe  ..\osm\illinois-latest.osrm

[info] starting up engines, v4.5.0-647-g3e113db
[info] populating base path: ..\osm\illinois-latest.osrm
[info] HSGR file:       "..\osm\illinois-latest.osrm.hsgr"
[info] loading graph data
[info] loading graph from ..\osm\illinois-latest.osrm.hsgr
[info] number_of_nodes: 2268483, number_of_edges: 15372488
[info] loaded 2268483 nodes and 15372488 edges
[info] Data checksum is 1069422914
[info] loading edge information
[info] loading core information
[info] loading geometries
[info] loading r-tree
[info] loading timestamp
[info] Loading Timestamp
[info] loading street names
[info] loaded plugin: table
[info] loaded plugin: hello
[info] loaded plugin: locate
[info] loaded plugin: nearest
[info] loaded plugin: match
[info] loaded plugin: timestamp
[info] loaded plugin: viaroute
[info] loaded plugin: trip
[info] http 1.1 compression handled by zlib version 1.2.8
[info] running and waiting for requests

From a browser, enter a request

http://localhost:5000/viaroute?loc=50.855185,4.343325&loc=50.833359,4.345013&instructions=true&alt=false

The request arrives at the backend, making it crash instantly, with the message "backend-osrm.exe has stopped working"
The request is printed on stdout as below

[info] 06-01-2016 10:18:20 127.0.0.1 - Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0 /viaroute?loc=50.855185,4.34
3325&loc=50.833359,4.345013&instructions=true&alt=false

**Comment by BergWerkGIS** [comment]
@SergeFranchois tried to reproduce your error:

* downloaded latest osrm: http://build.project-osrm.org/latest/osrm_Release.zip
* pointed the path in `.stxxl.txt` to a valid directory
* downloaded https://s3.amazonaws.com/metro-extracts.mapzen.com/chicago_illinois.osm.pbf
* `osrm-extract.exe ..\chicago_illinois.osm.pbf`
* `osrm-prepare.exe ..\chicago_illinois.osrm`
* `osrm-routed.exe ..\chicago_illinois.osrm`

Opening the browser at

```
http://localhost:5000/viaroute?loc=50.855185,4.343325&loc=50.833359,4.345013&instructions=true&alt=false
```

returns the result shown below (no crash).

----

How did you extract and prepare your `osrm` file?

`osrm` files have to be created with the same OS and osrm version that is going to consume them.
e.g: you cannot create the `osrm` file on Linux with `4.5` and use it on Windows with `4.9`.


-----

```json
{
  "found_alternative": false,
  "via_points": [
    [
      41.65987,
      -87.066147
    ],
    [
      41.65987,
      -87.066147
    ]
  ],
  "route_geometry": "{|umnAv`baeD??",
  "route_instructions": [
    [
      "10",
      "",
      0,
      0,
      1,
      "0m",
      "N",
      0,
      1,
      "N",
      0
    ],
    [
      "15",
      "",
      0,
      1,
      0,
      "0m",
      "N",
      0,
      "N",
      0
    ]
  ],
  "hint_data": {
    "checksum": 1229636408,
    "locations": [
      "_VQLADgUDgAAAAAABQAAAAAAAAAAAAAAAAAAAP_____TAQCAXwAAAN6tewLkec_6AAABAQ",
      "_VQLADgUDgAAAAAABQAAAAAAAAAAAAAAAAAAAP_____TAQCAXwAAAN6tewLkec_6AAABAQ"
    ]
  },
  "route_summary": {
    "total_distance": 0,
    "end_point": "",
    "total_time": 0,
    "start_point": ""
  },
  "via_indices": [
    0,
    1
  ],
  "route_name": [
    "",
    ""
  ],
  "status_message": "Found route between points",
  "status": 200
}
```

**Comment by SergeFranchois** [comment]
Hi Wilhelm

Thank you for pointing this out. I had no idea the files were not portable. My bad.
They were indeed generated on Ubuntu or CentOS as far as I recall. Because I didn't want to redo the preparation, i copied them over and tried to load with the Windows OSRM backend.

I prepared the files again on Windows,and all worked as expected.

Issue may be closed (or rejected)

Thanks again!
