### ISSUE TITLE
Markers are confusing

### ISSUE THREAD

**Issue by derickr** [Project-OSRM/osrm-backend#186]
Hi!

I keep getting confused about what each of the markers mean. Red sounds more like start, and Green more like finish. Could I suggest to use a finish flag on the end marker?

cheers,
Derick

**Comment by TheMarex** [comment]
This is fixed in the new frontend by explicitly color coding the input field for start/end.

**Comment by waldyrious** [comment]
> I think the core issue (markers distinguished by color alone being confusing) still stands.

Why not using both colors and labels to ensure this works without the need to look up what each color means (c.f. @derickr's original comment about swapping the meaning of green/red)? That would be useful (possibly even critical) for color-blind people as well.
