### ISSUE TITLE
Cucumber on OSX

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#1861]
Currently cucumber features/testbot/via.feature:96 is failing on OSX.
The via plugin does not return a valid route for the via features.

As a result, the testing is currently disabled for OSX.
https://github.com/Project-OSRM/osrm-backend/blob/develop/.travis.yml#L77

We should fix these errors.

**Comment by MoKob** [comment]
Superseded by https://github.com/Project-OSRM/osrm-backend/issues/1863, Keeping this open to remind us to enable cucumber tests on OSX again.

**Comment by TheMarex** [comment]
This is fixed now with the PR merged.
