### ISSUE TITLE
tools/simpleclient

### ISSUE THREAD

**Issue by JIGR1969** [Project-OSRM/osrm-backend#1868]
Hi,

I have OSRM-ROUTED working fine, however, looking for more speed from the command line. Tried to compile the simplclient.cpp in the tools sub directory but it keeps erroring. 

The command I use is : g++ -c -std=c++11 -I/osrm/osrm-backend/library/ simpleclient.cpp

And I get the error : 
In file included from simpleclient.cpp:29:0:
../util/json_renderer.hpp:37:35: fatal error: osrm/json_container.hpp: No such file or directory
 #include <osrm/json_container.hpp>
                                   ^
compilation terminated.

Any help would be gratefully received.

Cheers

**Comment by daniel-j-h** [comment]
The interface for `libosrm` (read: the headers) live in `include/osrm/`, specify the include path accordingly: add `-I include`. You also have to build the `libosrm` library (either static library `libosrm.a` or shared library `libosrm.so` and then link it in via `-losrm`.

**Comment by daniel-j-h** [comment]
To be more specific here: if you installed osrm-backend, you have `libosrm.a` (and maybe `libosrm.so` depending if you specified the shared lib to CMake) available in the compiler's default lib search path at `/usr/lib/` and the needed includes at `/usr/include/osrm`. In this case, you do not need to tell your compiler these locations.

If you do not want to install osrm-backend, things get a little bit more involved.

1/ Build `libosrm.a`

    mkdir -p build
    pushd build
    cmake .. -DCMAKE_BUILD_TYPE=Release
    cmake --build .
    popd

2/ Tell pkg-config to look for the `libosrm.pc` file for `libosrm` in the build directory

    export PKG_CONFIG_PATH=build
    pkg-config --cflags --libs --static libosrm

Note that the libs and flags pkg-config returns is suited for a installed `libosrm`. So let's grab the libs and flags that pkg-config gives and and modify both the lib directory and include directory to point to our local directories. The full command (with pkg-config expanded) should look roughly like this:

```
g++ -Wall -Wextra -pedantic -std=c++11 \
  -I include -I build/include -I third_party  \
  src/tools/simpleclient.cpp -o simpleclient \
  build/libOSRM.a \
  -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lboost_unit_test_framework \
  -ltbb -ltbbmalloc \
  -pthread -lrt
```

In case you installed `libosrm` on your system, you do not need these adjustments.

Does this help?

**Comment by JIGR1969** [comment]
It did help, as I understand it better now than before. However, I'm still getting the same error message.

I've installed OSRM-BACKEND in a directory called /osrm/osrm-backend (imaginatively). If I ran the commands, export and pkg-config and then amending the src/tools/simpleclient.cpp locations since it is simply tools/simpleclient.cpp, it then complains that it cannot locate "util/version.hpp".

It I now change into the tools directory, amend the paths in the export and pkg-config command, and run the G++ command from the tools directory, it still complains about not being able to find 

    /osrm/osrm-backend/util/json_renderer.hpp:37:35: fatal error: osrm/json_container.hpp: No such file or directory
     #include <osrm/json_container.hpp>
                                       ^
    compilation terminated.

 Changing all of the paths involved to use the full path name, in the export command, the pk-config command, in the simpleclient.cpp and in the G++ command, I still get it complaining about not being able to find OSRM/JOSN_CONTAINER.HPP.

Sorry to be a right royal pain in the rear.

Cheers

**Comment by JIGR1969** [comment]
No worries, I've finally compiled it. I missed out a single path which was the important one, the include! Doh! 

It has now compiled and I thank you for your assistance.
