### ISSUE TITLE
Public demo server down

### ISSUE THREAD

**Issue by tyrasd** [Project-OSRM/osrm-backend#1873]
From https://github.com/openstreetmap/openstreetmap-website/issues/1129:

The OSRM routing mode on osm.org currently doesn't produce routes. The javascript console shows a `No 'Access-Control-Allow-Origin' header is present` error. The following request is sent, but produces a strage result:
 
````
$ curl "http://router.project-osrm.org/viaroute?z=14&output=json&instructions=true&loc=46.493665357623804%2C11.326904296875&loc=47.00086080525212%2C11.502685546875" --verbose
* Hostname was NOT found in DNS cache
*   Trying 141.3.85.1...
* Connected to router.project-osrm.org (141.3.85.1) port 80 (#0)
> GET /viaroute?z=14&output=json&instructions=true&loc=46.493665357623804%2C11.326904296875&loc=47.00086080525212%2C11.502685546875 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: router.project-osrm.org
> Accept: */*
> 
	< HTTP/1.1 302 Found
* Server nginx/1.1.19 is not blacklisted
< Server: nginx/1.1.19
< Date: Sun, 10 Jan 2016 09:40:14 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
< Location: http://magento-experimental.test.signifyd.com:80/
< 
* Connection #0 to host router.project-osrm.org left intact
````

The new [osrm-frontend-v2](https://github.com/Project-OSRM/osrm-frontend-v2) at [osrm.at](http://osrm.at) requests routes from `http://api-osrm-routed-production.tilestream.net/` instead of `http://router.project-osrm.org/`. Maybe the URL has to be updated on osm.org as well? On the other hand, the [documentation](https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy#server-name) here still lists the "old" broken endpoint…

**Comment by danpat** [comment]
@tyrasd It looks like `router.project-osrm.org` is broken (perhaps compromised based on the weird redirect it's giving?).  It's maintained by @DennisOSRM, but he's only intermittently accessible these days, so it might be a little while before it gets fixed.  Unfortunately, nobody else has access :-(

**Comment by perliedman** [comment]
@danpat are you aware of any work done to improve this situation?

I appreciate the demo server is just that, a demo, and comes without any guarantees or SLA, but I'm a bit worried the problems in the last couple of months make the project as a whole look bad. Since OSRM is also the default router on openstreetmap.org, one could also argue it affects the perception of OSM as reliable. On a personal level, every time the demo server goes down, I end up with a couple of complaints that my plugin (Leaflet Routing Machine) is broken, and I guess it's the same for all other projects that indirectly use the demo server.

Another thing I note from the complaints when the server is down, is that quite a few people seem to rely on it for production use. It makes me wonder if the docs should perhaps make it more clear that this is not something you should do.

Please don't take this as criticism or whining, just want to discuss possibilities for improving the situation!

**Comment by freenerd** [comment]
Sorry for all the trouble. https://router.project-osrm.org is up again. We've also taken measures to ensure it will be more stable in the future, by removing an intermediate proxy and pointing DNS more directly at the demo server.

**Comment by perliedman** [comment]
:+1:

**Comment by RikdeBoer** [comment]
Issue has resurfaced a couple of days ago on   router.project-osm.org 

In its response header the server must explicitly state which sites may access it. Like so:

Access-Control-Allow-Origin: *

However there is nothing of this kind in the response header, so all calls fail.

**Comment by RikdeBoer** [comment]
It just started working again. Yay!

**Comment by bjmak** [comment]
It is down again for over a day.

**Comment by daniel-j-h** [comment]
Works for us, from several different geographical locations.
The last small hiccup on our side was on 07/06/2016.

**Comment by mmilito** [comment]
Hi, the original issue seems to be happening again and routing is failing. I am using Leaflet Routing Machine in a production project ... @perliedman , are you getting complaints again?  

Are we OK to use the routing machine in production (is there a way to point it to a more robust server? It's an awesome tool!)  TIA for any info!

**Comment by freenerd** [comment]
@mmilito the demo server is exactly that, a server for demos. It's [API usage policy](https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy) does not restrict production use, but also does not give guarantees.

If you need OSRM for production use, then you can either host it yourself, or use a commercial vendor like http://www.geofabrik.de/data/routing.html or https://www.mapbox.com/directions/

**Comment by RikdeBoer** [comment]
'Access-Control-Allow-Origin' issue again.

Service broken.
Demo page, http://map.project-osrm.org, consequently also broken. 

Google Chrome console:

XMLHttpRequest cannot load https://router.project-osrm.org/route/v1/driving/-77.0907211303711,38.87740…85156,38.91000307716011?overview=false&alternatives=true&steps=true&hints=;. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://map.project-osrm.org' is therefore not allowed access. The response had HTTP status code 504.

**Comment by daniel-j-h** [comment]
The demo server had some hiccup in the last days. We restarted it a couple of hours ago and it's currently re-processing the planet. This will take a while.

**Comment by csalmeida** [comment]
Hi everyone,

Is the server down again by any chance? A couple of days ago I've had the error @RikdeBoer had but now I have this one:

`XMLHttpRequest cannot load http://router.project-osrm.org/route/v1/driving/-2.5468,51.4998;-2.5603,51.5055?alternatives=true&steps=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 404.`

Any thoughts on how to solve this issue would be deeply appreciated.

**Comment by daniel-j-h** [comment]
Yes the demo server is currently down. We fixed the issue and are currently running processing. This will take a bit. Should be fixed soon.

**Comment by karim-ecov** [comment]
Is still this server down now? Do you know how many time it can take to fix it? 
 Has everyone an alternative server for routing with leaflet?

**Comment by daniel-j-h** [comment]
Yes it is still down. Maybe processing the planet will get faster if we all cheer up the demo server a bit.

If you can't bear the downtimes our experimental demo server has every now and again maybe you want to set up your own instance or pay someone for a hosted solution.

Please don't revive those old issues or ping every other hour. It adds nothing of value.

**Comment by karim-ecov** [comment]
Sorry for this...  the question was just about the kind of time scale it can take (I've no idea about this processing)... it was not any kind of reproach that we can have in hotline of non-free services... sorry for the missunderstood...

**Comment by mecoFarid** [comment]
I believe it's down again, right?

**Comment by perliedman** [comment]
@mecoFarid try one of these:

* Building (and installing) OSRM, official OSRM docs: https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM
* OSRM using Docker: https://github.com/Project-OSRM/osrm-backend/wiki/Docker-Recipes
* How to install OSRM on Ubuntu 14.04 (should mostly apply to later versions as well): https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04

**Comment by daniel-j-h** [comment]
DigitalOcean tutorial is outdated, please follow the wiki
https://github.com/Project-OSRM/osrm-backend/wiki

and the Quick Start here
https://github.com/Project-OSRM/osrm-backend#quick-start
