### ISSUE TITLE
Missing ways in map matching

### ISSUE THREAD

**Issue by kbbaker** [Project-OSRM/osrm-backend#1884]
I am testing the matching algorithm implemented in OSRM, but I have some trouble understanding some of the responses I get.

Reading the documentation on the wiki about the match plugin, I expected that a missing way in OSM along a GPX track would results in splitting up the 'matchings' in the output. However, I often get a status 208 message stating 'Could not find a matching segment for coordinate x' where x is the first coordinate on a missing way. I constructed an example on following link:

http://router.project-osrm.org/match?loc=50.7631735,3.8665866&loc=50.76422,3.86937&loc=50.76637,3.8806&loc=50.76998,3.88014&loc=50.77393,3.8868199999999&loc=50.77157,3.88892&loc=50.77422,3.89198&instructions=true

Is this behavior expected or am I doing something wrong?

**Comment by TheMarex** [comment]
@kbbaker with `4.9.0` the behavior of matching changed slightly. You most likely have to adjust the `gps_precision` parameter, it governs the search radius for coordinates. If you are searching in very sparse areas, you might want to increase that from `5` (default value) to `10`.

**Comment by kbbaker** [comment]
Increasing the gps_precision parameter does seem to do the trick.
