### ISSUE TITLE
Deadlock using `osrm-datastore` while requests are being served

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1888]
Under some circumstances, it seems that `osrm-datastore` can deadlock if routing requests are being served at the same time.

To reproduce the problem:

  1. Run `osrm-datastore whatever.osrm` to load the initial dataset
  2. Run `osrm-routed -s` to load data from shared memory.
  3. Set up a request running in a rapid loop: `while true ; do curl 'http://localhost:5000/viaroute?loc=39.22693426244916,-75.59280395507812&loc=39.06451486901886,-75.465087890625' ; done`
  4. Now while that loop is running, do the same with `osrm-datastore`, like so:  `while true ; ./osrm-datastore whatever.osrm ; done`

In a perfect world, the locking would work properly and routing wouldn't be interrupted.  However, very shortly after starting the `osrm-datastore` loop, I start seeing errors like this:

![screen shot 2016-01-12 at 3 58 55 pm](https://cloud.githubusercontent.com/assets/1892250/12280774/69d8ad0c-b945-11e5-8851-3042cccd271b.png)

![screen shot 2016-01-12 at 4 03 12 pm](https://cloud.githubusercontent.com/assets/1892250/12280855/0c02063c-b946-11e5-95c5-dccc067364b1.png)

Then, within a few seconds, everything stops completely, and `osrm-routed` appears to be stuck in a busy loop.

Killing the `curl` loop does not unlock things.  `osrm-routed` responds to requests with `{"status": 500,"status_message":"Internal Server Error"}` and does not close the socket (leading to `curl` hanging).

Killing the `osrm-datastore` loop does not resurrect `osrm-routed`.

Killing the `osrm-datastore` loop and restarting `osrm-routed` does seem to bring things back to life, so it doesn't look like any routing data is getting corrupted, just locking state.

**Comment by danpat** [comment]
Simpler reproduction recipe:

   1.  Run `osrm-datastore whatever.osrm`
   2.  Run `osrm-routed -s`
   3.  Run `osrm-datastore whatever.osrm`
   4.  Run `osrm-datastore whatever.osrm`
   5.  Run `curl http://localhost:5000/viaroute?loc=1,1&loc=2,2`

You can now kill `osrm-routed`, and restarting it (without running further `osrm-datastore` commands) will lead to errors like this:

```
danpat@rundle:~/mapbox/osrm-backend/build$ ./osrm-routed -s
[info] starting up engines, v4.9.0
[debug] Loading from shared memory
[debug] Threads:	8
[debug] IP address:	0.0.0.0
[debug] IP port:	5000
[debug] writeable memory allocated 12 bytes
[debug] deallocating prev memory
[debug] deallocating prev memory
[warn] caught exception: No such file or directory, code 7
[warn] [exception] No such file or directory
danpat@rundle:~/mapbox/osrm-backend/build$
```

**Comment by daniel-j-h** [comment]
Can reproduce, perfect.

I could hunt it down to the line where the `SharedMemory` object [is being constructed](https://github.com/Project-OSRM/osrm-backend/blob/466251287f4bd5d9c8b24d7e6e838a829f4a0d27/include/datastore/shared_memory_factory.hpp#L346).

**Comment by daniel-j-h** [comment]
`SharedMemoryFactory::Get` returns a `new`ed pointer to a `SharedMemory` object.
On the call sites no one ever calls `delete` on that, so its destructor is never invoked.

**Comment by danpat** [comment]
The problem here is caused by toggling between LAYOUT_1 and LAYOUT_2.  `SharedDataFacade` only updates its internal pointer when a request comes in.

If `osrm-datastore` is run such that we toggle from LAYOUT_1 -> LAYOUT_2 -> LAYOUT_1 without `SharedDataFacade` being updated, then the `CheckAndReloadFacade` method will erroneously call `Remove()` on the very data that it's supposed to start using.

**Comment by danpat** [comment]
There appears to be a race condition, where `SharedDataFacade` can perform it's `CheckAndReloadFacade` while a query is still in-progress on another thread.  This can cause all kinds of undefined behaviour, including lockups and segfaults, depending on exactly where the query thread is up to when `CheckAndReloadFacade` resets all the data structures the query thread is looking at.

Generally, single-threaded requestors against a single `osrm-routed` instance won't trigger this problem, it requires concurrent requests and a new dataset from `osrm-datastore`.

**Comment by TheMarex** [comment]
This needs a bigger restructuring of `osrm-datastore` and in general the data backend. Tracking here: https://github.com/Project-OSRM/osrm-backend/issues/1907

Closing after the partial fix is merged.
