### ISSUE TITLE
Wrong distance result when using table with src/dst parameters

### ISSUE THREAD

**Issue by faheemmughal** [Project-OSRM/osrm-backend#1893]
When using table service with new src/dst parameters, it returns a really large distance (travel time):

```
table?dst=-33.86965%2C151.20674&src=-33.87073%2C151.19768

{  
   "status":200,
   "source_coordinates":[  
      [  
         -33.87073,
         151.197685
      ]
   ],
   "destination_coordinates":[  
      [  
         -33.869634,
         151.20674
      ]
   ],
   "distance_table":[  
      [  
         2147483647
      ]
   ]
}
```

While using the same service with location parameters:

```
table?loc=-33.86965%2C151.20674&loc=-33.87073%2C151.19768

{  
   "status":200,
   "source_coordinates":[  
      [  
         -33.869793,
         151.206938
      ],
      [  
         -33.87073,
         151.197685
      ]
   ],
   "destination_coordinates":[  
      [  
         -33.869793,
         151.206938
      ],
      [  
         -33.87073,
         151.197685
      ]
   ],
   "distance_table":[  
      [  
         0,
         5981
      ],
      [  
         5366,
         0
      ]
   ]
}
```

If it helps, I have used mapzen's map for Sydney (https://s3.amazonaws.com/metro-extracts.mapzen.com/sydney_australia.osm.pbf).

**Comment by faheemmughal** [comment]
cc: @fab-girard

**Comment by fab-girard** [comment]
Hello,
destinations should have at least 2 coordinates ;) 
You should not authorized to use only one.

Fab

**Comment by faheemmughal** [comment]
That is a strange limitation. Especially when `loc` works with two coordinates. And single `src`, single `dst` works for most cases I have tested. 

I would use `loc` or a different service but that seems wasteful when all I need is travel time between arbitrary number of sources and destinations. Is this a hard limitation or would it be possible to have a single `dst` in future?

**Comment by TheMarex** [comment]
Indeed while `1x1` does not really make sense overhead wise it should be possible.

**Comment by fab-girard** [comment]
Hello,
I've reproduced this bug with Sydney OSM data.
It seems to be caused by this point:
http://www.openstreetmap.org/search?query=-33.86965%2C151.20674#map=18/-33.86936/151.20665
which is located in a street only routed by "George Street" tagged "in construction" in OSM.
In fact when phantoms nodes are calculated for distance_table matrix, I think the phantom node is set on Temperance Lane which is not convex (outside main network).
@TheMarex; maybe an issue near `NearestPhantomNodeWithAlternativeFromBigComponent` but not sure...

I didn't succeed in finding the correction...

Fabien

**Comment by TheMarex** [comment]
We set a minium size of 2x2 in the new API. This would now generate an invalid request error.

**Comment by frodrigo** [comment]
But the issue was not related to matrix size, but to phantom node position calculation with seem different than in viaroute.

**Comment by TheMarex** [comment]
@frodrigo ah okay, misread the summary. Snapping is now done on all coordinates consistently as well in the new api (the src and dst mechanism changed, read up on it [here](https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#service-table))

**Comment by faheemmughal** [comment]
Just reporting similar issue for book keeping. I suspect it is fixed in new version as @TheMarex said.

A query like,
```
/table?dst=-33.895626%2C151.194399&src=-33.90332%2C151.17956&src=-33.9026%2C151.20474
```
results in all distances set to 2147483647

However the same query done using `loc=` parameters 
```
/table?loc=-33.895626%2C151.194399&loc=-33.90332%2C151.17956&loc=-33.9026%2C151.20474
```
returns correct distances.

I will update to latest released source code and report back if that fixes the problem.

**Comment by daniel-j-h** [comment]
Please make sure to test this with the (not yet releases) v5 version, it's in the `rewrite/new-api` branch.

https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

**Comment by faheemmughal** [comment]
@daniel-j-h I tried compiling master. It failed with errors. Do you have a known good revision for v5 that I can use?

Error Log is at:
https://gist.github.com/faheemmughal/412886ca81d2d9d4b309a99ebd10fd1c

**Comment by daniel-j-h** [comment]
For the record, if you clone the Github repo. you get the `develop` branch by default (which is the v5 API already). You can check out our latest RC2 from here: https://github.com/Project-OSRM/osrm-backend/tree/v5.0.0-rc.2, but at the moment develop and rc2 are pretty much the same.

Looking at your logs, the relevant lines are here:
```
[ 29%] Building CXX object CMakeFiles/EXTRACTOR.dir/src/extractor/extractor.cpp.o
c++: internal compiler error: Killed (program cc1plus)
```

This is your compiler (gcc 4.8) crashing internally.

Can you try a more recent compiler, e.g. on a Ubuntu machine do:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo aptitude update && sudo aptitude safe-upgrade
sudo aptitude install g++-5

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20
sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-5 20
```

We know of certain critical gcc 4.8 bugs e.g. we have to disable link time optimization on gcc < 4.9, and disable some protected qualifiers, but this crash is new as far as I can remember.

What's the Linux distribution you're on? Maybe I can try reproducing it.

**Comment by danpat** [comment]
`c++: internal compiler error: Killed (program cc1plus)` looks like the kernel OOM killer to me.

@faheemmughal you may not have enough free RAM.  If you don't have much, try increasing your operating system swap space.

**Comment by faheemmughal** [comment]
```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/EXTRACTOR.dir/src/extractor/extractor.cpp.o] Error 4
make[1]: *** [CMakeFiles/EXTRACTOR.dir/all] Error 2
make: *** [all] Error 2
```

@daniel-j-h I have tried using gcc 5 on ubuntu 16.04 with fresh repository clone in a docker. It still is crashing.

@danpat good idea. So I killed a bunch of processes and make ~10GB RAM available. It still crashed at the same place.
