### ISSUE TITLE
Error "mem index file does not exist" with --shared-memory

### ISSUE THREAD

**Issue by frodrigo** [Project-OSRM/osrm-backend#1894]
I use osrm-datastore with osrm-routed and node bindings.
Despite the reload of data with osrm-datastore and after a delete of old .osrm and al. file, osrm-routed and nodejs keep old .ramIndex file open and finally fail with "Error: mem index file does not exist".

**Comment by TheMarex** [comment]
@frodrigo what exactly is your workflow? Can you give us the exact paths/order of commands you are running?

**Comment by xals** [comment]
@TheMarex I am the one who defined the workflow. Here it is:
  * Download or update OSM file
  * Create a link to OSM file with the profile and datetime (example: france-bicycle-20160118.osm.pbf -> france/france-10260118.osm.pbf
  * Extract data : /usr/bin/osrm-extract -p /srv/osrm/profiles/profile-bicycle.lua /srv/osrm/data/france-bicycle-20160118.osm.pbf
  * Prepare data : /usr/bin/osrm-extract -p /srv/osrm/profiles/profile-bicycle.lua /srv/osrm/data/france-bicycle-20160118.osrm
  * Reload data with osrm-datastore : /usr/bin/osrm-datastore /srv/osrm/data/france-bicycle-20160118.osrm

Extraction and preparation are done in independent Docker containers (using docker run) with /srv/osrm/data and /srv/osrm/profiles as persistent volumes.
Reload is done in the container already running osrm-routed (using docker exec). Those containers use an image I created with a custom Dockerfile.

**Comment by frodrigo** [comment]
Plus, once the datastore is reloaded the old osrm files are deleted.

**Comment by xals** [comment]
Oh, yes, thanks @frodrigo, I forgot the most important step… I haved updated my comment.

**Comment by TheMarex** [comment]
The confusing thing is that `.ramIndex` should only be open for the duration of loading the data, independently of you use `osrm-datastore` or the internal memory.

I could see a possible problem with `.fileIndex` as `osrm-routed` continuously reads from that file. Can you double check if its really `.ramIndex`?

I could also imagine a race-condition here, as data is reloaded lazily on request. You could try something like waiting a few seconds/minutes before deleting the file.

**Comment by xals** [comment]
Sorry, the deleted files are .fileIndex ones, not .ramIndex ones. It seems there were only .fileIndex opened deleted files last time I checked.

**Comment by TheMarex** [comment]
I think the problem here is that you probably are deleting the files before the reload is completed. This might take a while since first all currently running queries have to finish, then the swap occurs and finally each thread has to update that parameter.

This is clearly a bug on our side, but will take a while before we can fix it, as it requires a bigger restructuring on how we load shared memory data. Can you try to add a delay?

**Comment by xals** [comment]
Sure. How much?

**Comment by TheMarex** [comment]
@xals I think 2 minutes should be safe on your dataset size.

**Comment by xals** [comment]
I have some data on an extended europe dataset too, osrm file is abount 13Go, I think I should set more time for it?

**Comment by TheMarex** [comment]
@xals I would go with an absurdly big value (like an hour) and work my way down. Are you constrained on update frequency?

**Comment by xals** [comment]
I don't think this is an issue. I will schedule the deletion one hour after the update using "at" command and go on with next preparation (I have 4 France and 1 Europe datasets to prepare).

**Comment by xals** [comment]
I deleted the files after more than 1h, and they are still opened. It seems they are the only files opened by orm-routed:
# lsof | grep europe-interurban
osrm-rout  2177             root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177             root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177             root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177             root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2190       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2190       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2190       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2190       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2191       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2191       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2191       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2191       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2192       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2192       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2192       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2192       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2193       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2193       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2193       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2193       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2194       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2194       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2194       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2194       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2195       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2195       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2195       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2195       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2196       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2196       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2196       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2196       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2197       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2197       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2197       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2197       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2198       root    8r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2198       root    9r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2198       root   10r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)
osrm-rout  2177  2198       root   11r      REG                9,2 15158973068    9455648 /srv/osrm/data/europe-interurban-20160119.osrm.fileIndex (deleted)

**Comment by TheMarex** [comment]
@xals `/srv/osrm/data/europe-interurban-20160119.osrm.fileIndex` is the old dataset? The new one is never loaded?

I'll try to replicate this locally. Thanks for posting back.

**Comment by TheMarex** [comment]
This should be fixed in `5.1.0`. The StaticRTree is now updated immediately on a data update.
