### ISSUE TITLE
Remove JSONP option

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1895]
Our API will switch to JSON-only output in 5.0, that means JSONP will retire as well. CORS is better replacement and https://github.com/mapbox/corslite makes it work even for IE<10.

/cc @perliedman

**Comment by perliedman** [comment]
Sounds good! I see no reason to use JSONP these days.

LRM has used CORS since the 2.0 release, so I don't think this should be an issue for LRM users at least!

**Comment by TheMarex** [comment]
Done.
