### ISSUE TITLE
Scope 4.9.1 release

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1900]
I see release options:

### Small fix

- Fix current critical issues
- Minimum amount of changes
- Predictable and fast to run out
- Risk of master/develop conflicts because of back ports (only risk here is missing changes in `develop` that are in `master`, we can fix the merging with `git merge --ours`)

TODO
- [x] Port back map matching parameter fix
- [x] Port back Disney Land fix (both the error handling and the pre-processing)
- [x] Port back trip plugin error
- [x] Port back datastore fix (not sure if the change will be too big)

### Incremental merge

- Aim for maximum of stability to make `4.9.1` an option we can support for a while.
- Just merge `develop` into `master`
- Will include a lot of fixes but also a lot of the restructuring we have begun for `5.0`.
- Might need changes in `node-osrm` due to changed buildsystem structure
- Higher risk of running this out in a short amount of time

TODO
- [x] Merge Disney Land https://github.com/Project-OSRM/osrm-backend/pull/1899
- [x] Merge trip segmentation fault https://github.com/Project-OSRM/osrm-backend/pull/1891
- [ ] Fix datastore problem https://github.com/Project-OSRM/osrm-backend/pull/1892
- [ ] Merge loop problem https://github.com/Project-OSRM/osrm-backend/pull/1869

Currently I am leaning towards the small fix in `4.9.1`.
/cc @freenerd @daniel-j-h @danpat @MoKob

**Comment by freenerd** [comment]
@TheMarex are the changes keeping apis stable? do you think the restructuring towards 5.0 is stable (not reverted soon again)? If both is true, than the incremental merge sounds like the better option, with `4.9.1` landing early next week?

**Comment by TheMarex** [comment]
@freenerd we have had the following breaking changes in `develop`:
- removing GPX support (was never exposed in `node-osrm`)
- breaking C++ API for `libosrm` (added namespaces and renamed library)

Most likely that won't affect a lot of people but nothing for a `.1` release I think. We will have this problem down the road anyway, if we merge the API redux we can't use `devlop` -> `master` merges for `4.9.2` anymore.

**Comment by TheMarex** [comment]
:+1: `v4.9.1` is released.
