### ISSUE TITLE
.ebg file empty and no error

### ISSUE THREAD

**Issue by xals** [Project-OSRM/osrm-backend#1905]
I am following the issue #1846. I had the same error while running osrm-prepare (), and watching the disc usage graph, I saw the free space eaten, but osrm-extract exited with code 0, resulting in osrm-prepare to be executed but with an empty .ebg file.

I think osrm-extract can detect if it can't write in this file and exit with a non-zero code.

**Comment by daniel-j-h** [comment]
Yes you are correct. Already tracked in https://github.com/Project-OSRM/osrm-backend/issues/1682. Closing as duplicate.

We're in the progress of cleaning up these little annoyances in `osrm-backend`, but it takes its time.

Thanks for reporting!

**Comment by xals** [comment]
Ok, I didn't find any related bugs, thanks for the reference.
