### ISSUE TITLE
Random size of elemens in route_instructions, no keys too

### ISSUE THREAD

**Issue by maximd1** [Project-OSRM/osrm-backend#1908]
Hi Team,

I use osrm-backend 4.8.0 for my application. The issue I am facing with is that route_instructions of server response contains an array of arrays with random number of sub-elements - I catch IndexOutOfBoundsException when I try to access them.

I work with json.simple to parse JSON response and iterate through the each sub-element of route_instructions. According to https://github.com/Project-OSRM/osrm-backend/wiki/Server-api every entry can contain up to 11 elements. Example shows that there are only 9 (and even 8!) elements in the response. My live server also doesn't return full response - only 9 fields. Why (and which?) rest of fields are ignored?

The problem compounded by the fact that ordering of fields in the response not guaranteed too - I am not sure that, for example, driving directions code is a strictly first parameter. So, keys are very, very desirable. Maybe, there is a special undocumented parameter for the /viaroute service to switch them on in a response?

Thank you.

**Comment by danpat** [comment]
Hi @maximd1 

Parameters 10 and 11 are new in 4.9.0, I'll add that to the wiki page, sorry that it's not clear.

The `instruction` entry with only 8 values (10 in 4.9.0) is the last instruction - this looks like a bug here:   https://github.com/Project-OSRM/osrm-backend/blob/develop/include/engine/guidance/textual_route_annotation.hpp#L115-L124, it looks like we've forgotten an entry for the `travel_mode`.

/cc @TheMarex

**Comment by maximd1** [comment]
@danpat 
Thank you for your help, the issue is resolved now.
