### ISSUE TITLE
Error in route_instructions: driving directions code is not an integer number

### ISSUE THREAD

**Issue by maximd1** [Project-OSRM/osrm-backend#1910]
Hi Team,

my test query to the server returns following strange sentence: ["11-1","Радянська вулиця (М-18)",702,2520,32,"701m","SE",132,1]. Why the first value is not an integer number as mentioned in the https://github.com/Project-OSRM/osrm-backend/wiki/Server-api?

Query is /viaroute?loc=50.345,30.89472&loc=48.07361,37.73972&output=json&instructions=true
osrm-backend 4.8.0

Map is http://download.geofabrik.de/europe-latest.osm.pbf, it has been downloaded, extracted and prepared 10 days ago.

Thank you.

P.S. alternative_instructions - the same.

**Comment by TheMarex** [comment]
@maximd1 instruction type `11` is a exit roundabout instruction. `11-1` means `exit roundabout at exit 1`. Will update the documentation.
