### ISSUE TITLE
Assertion in coordinate_calculation.

### ISSUE THREAD

**Issue by ryanbartley** [Project-OSRM/osrm-backend#1912]
Hello,

I can't seem to figure out what I'm doing wrong here. The assertion is happening [here](https://github.com/Project-OSRM/osrm-backend/blob/466251287f4bd5d9c8b24d7e6e838a829f4a0d27/src/util/coordinate_calculation.cpp#L64) and it's from [this](https://github.com/Project-OSRM/osrm-backend/blob/6991a38703e52b457893f779d51a1bab2f52d523/include/util/rectangle.hpp#L118) branch of execution. The gps coordinates that I give to RunQuery are these...40.7411, -73.9941 and 40.7628, -73.9776. Mapping these on osrm lands me smack in the [middle of new york city](http://map.project-osrm.org/?z=15&center=40.752373%2C-73.984280&loc=40.740454%2C-73.994516&loc=40.762918%2C-73.977486&hl=en&ly=&alt=&df=&srv=). I'm running this on both the [us-northeast-latest.osm.pbf](http://download.geofabrik.de/north-america/us-northeast-latest.osm.pbf) and also [new-york-latest.osm.pbf](http://download.geofabrik.de/north-america/us/new-york-latest.osm.pbf) (after extracting and preparing both). I can't seem to make it through two iterations of [this](https://github.com/Project-OSRM/osrm-backend/blob/f875e26fbf1c19222f5bfc84259d168bb1b3cd14/include/util/static_rtree.hpp#L444) for loop. It always crashes on i == 1. I'm running 64bit Windows. Any help would be greatly appreciated! 

Thanks so much!

**Comment by danpat** [comment]
@ryanbartley are you multiplying your values by `osrm::COORDINATE_PRECISION` ?  The value passed in the `route_parameters` object needs to be a scaled integer.

See the example here:

https://github.com/Project-OSRM/osrm-backend/blob/develop/src/tools/simpleclient.cpp#L52-L56

**Comment by ryanbartley** [comment]
@danpat, Thanks for getting back to me so fast. Yes, I am multiplying it by that number. Here's my setup of the RunQuery function, in case you see anything strange.
```
RouteParameters route_parameters;
route_parameters.zoom_level = 18;           // no generalization
route_parameters.print_instructions = true; // turn by turn instructions
route_parameters.alternate_route = false;    // get an alternate route, too
route_parameters.geometry = true;           // retrieve geometry of route
route_parameters.compression = false;        // polyline encoding
route_parameters.check_sum = -1;            // see wiki
route_parameters.service = "viaroute";      // that's routing
route_parameters.output_format = "json";
route_parameters.jsonp_parameter = ""; // set for jsonp wrapping
route_parameters.language = "";        // unused atm

std::vector<vec2> retPoints;
int i = 0;
for( auto & taxi : taxiData ) {
	if( i % 100 == 0 )
		cout << i << ": Route from {" << taxi.pickupPos.lat << "," 
				  << taxi.pickupPos.lon << "} to {" << taxi.dropoffPos.lat << ", " 
				  << taxi.dropoffPos.lon << "}" ;

	route_parameters.coordinates.clear();
	// start_coordinate
	route_parameters.coordinates.emplace_back( taxi.pickupPos.lat * COORDINATE_PRECISION,
										       taxi.pickupPos.lon * COORDINATE_PRECISION );
	// target_coordinate
	route_parameters.coordinates.emplace_back( taxi.dropoffPos.lat * COORDINATE_PRECISION,
										       taxi.dropoffPos.lon * COORDINATE_PRECISION );
	osrm::json::Object json_result;
	const int result_code = mRoutingMachine->RunQuery( route_parameters, json_result );
```

**Comment by TheMarex** [comment]
@ryanbartley please use the member functions provided by `RouteParameters` instead of modifying the members themselves. `AddCoordinate` should work. (takes also doubles so remove the ` * COORDINATE_PRECISION`).

**Comment by ryanbartley** [comment]
I changed the above to what you suggested and it still breaks at the same place. However, I realized that the logging was muted, which I fixed, and when it broke this time, it reported 
```
broken lat: -214...(min int) bits: 10000000000.....
broken lon: -214...(min int) bits: 10000000000.....
```
I saw that this was the case when I was looking through the code I linked above but don't know where it's being logged.

**Comment by danpat** [comment]
@ryanbartley Can you create a reproduction case for this, maybe using `new-york-latest.osm.pbf`.  Please list all the commands you use to generate the data, the GITSHA of the codebase you're using, and a minimal C++ program to cause the problem.  Based on what you've described, I haven't been able to reproduce the assertion, so it must be something you haven't included so far.  If you're using a custom profile, please include that too.

**Comment by daniel-j-h** [comment]
Not actionable for us without further information. By now we also changed our coordinate abstractions, hiding the coordinate's precision. Please have a look at `example/example.cc` for how to use libosrm now.
