### ISSUE TITLE
Performance Bug of Map Matching with Core factor != 1

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#1920]
The function [get_network_distance](https://github.com/Project-OSRM/osrm-backend/blob/develop/include/engine/routing_algorithms/routing_base.hpp#L706) is designed only for a core factor of 1. If a core CH is used as underlying search, we loose performance by a suboptimal stopping criterion if we reach the core.

Two possible solutions for a core CH:
 * Split the search from the distance computation and use the appropriate `search` or `searchWithCore`
 * Prune `get_network_distance` by upper bounds based on https://github.com/Project-OSRM/osrm-backend/blob/develop/include/engine/routing_algorithms/map_matching.hpp#L197 and a reasonable min-speed (e.g 1cm/s should already suffice to prune a lot)

**Comment by MoKob** [comment]
Suggestion for the second fix in: https://github.com/Project-OSRM/osrm-backend/pull/1921

**Comment by freenerd** [comment]
@TheMarex is this change in https://github.com/Project-OSRM/osrm-backend/pull/1935 already?

The referenceless comment in https://github.com/Project-OSRM/osrm-backend/pull/1921#issuecomment-194991829 is annoying.

**Comment by MoKob** [comment]
@freenerd This is implemented in https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/include/engine/routing_algorithms/routing_base.hpp#L806-L812 of https://github.com/Project-OSRM/osrm-backend/pull/1935, closing here.
