### ISSUE TITLE
U-Turn on by default?

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#1922]
Breaking out of https://github.com/Project-OSRM/osrm-backend/issues/519#issuecomment-173686918 where I proposed to enable U-Turns by default.

Response by @TheMarex:

> I don't think it is a safe assumption that executing a u-turn is in general always possible. This can lead to absurd (and unsafe) suggestions like doing u-turns in the middle of high traffic streets.

How should a user know that uturns should be enable for a certain waypoint?

> This can lead to absurd (and unsafe) suggestions like doing u-turns in the middle of high traffic streets.

Sometimes these u-turns will be the right move though? The alternative would be doing a loop around the block then (eg three right turns and one left turn instead of one uturn)?

Isn't this just a question of penalizing u-turns harshly and potentially also differently depending on road type, allowed speed, etc?

**Comment by MoKob** [comment]
Related: https://github.com/Project-OSRM/osrm-backend/issues/1898

**Comment by MoKob** [comment]
>I don't think it is a safe assumption that executing a u-turn is in general always possible. This can lead to absurd (and unsafe) suggestions like doing u-turns in the middle of high traffic streets.

Is this not the case already at essentially any intersection that does not forbid `u-turns`?

I'd say that our `u-turn-penalty` of 20 is just way too low. Increasing it would essentially forbid u-turns, unless absolutely necessary.

For the search, I am currently a bit puzzled if we are missing a `u-turn` penalty for the [searchWithUTurn](https://github.com/Project-OSRM/osrm-backend/blob/develop/include/engine/routing_algorithms/shortest_path.hpp#L54) function.

**Comment by TheMarex** [comment]
@MoKob we add edges for u-turns that have a penalty during the run of `EdgeExpandedGraphFactory`. U-Turns at intersections are a lot more feasible than at the middle of the road. But you are correct 20 seconds is too low.

**Comment by MoKob** [comment]
On via-nodes, from what I can tell, we do not use any U-Turn penalty at all. That is something we have to consider.

**Comment by danpat** [comment]
At least one jurisdiction I know of practically forbids U-turns in almost every situation:

http://www.transportation.alberta.ca/2000.htm

**Comment by frodrigo** [comment]
Yes is mainly a problem of jurisdiction and country. Not all countries allow or forbid u-turn by default.

I'm not sure, but I don't think OSM address this problem of default u-turn value by country. BTW I already see contributor spam OSM with no U-turn restriction where is the default behaviour on the country... probably for routing issues.

**Comment by freenerd** [comment]
Discussion in https://github.com/Project-OSRM/osrm-backend/issues/2012 now
