### ISSUE TITLE
Undefined Behaviour due to Special Case Handling

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#1923]
https://github.com/Project-OSRM/osrm-backend/blob/a03eac8e48bba1e5933c74e675508dfe5613327a/include/engine/routing_algorithms/shortest_path.hpp#L205-L212

Introduces special case handling. This could result in undefined behaviour in:

https://github.com/Project-OSRM/osrm-backend/blob/a03eac8e48bba1e5933c74e675508dfe5613327a/include/engine/routing_algorithms/shortest_path.hpp#L343-L356

The code seems just to be necessary to handle special map-matching cases. I am not sure whether the undefined behaviour can actually occur. Nevertheless, I would assume that there should be a better way of handling the map-matching geometry extraction apart from introducing the special case handling in the shortest-path search.

**Comment by daniel-j-h** [comment]
@MoKob can you update the links and press y for URL canonicalization (if this is still an issue).

**Comment by MoKob** [comment]
@daniel-j-h I am not a hundred percent sure whether I got the correct locations, since I am not perfectly sure whether these special cases are the ones I had in mind. But I've updated the locations. Will look into it to make sure we get a clarified statement of whats going on and what would be necessary to solve it.

**Comment by TheMarex** [comment]
This is need for map matching and does not result in UB.

**Comment by danpat** [comment]
Just to be clear - yes, there are some codepaths here that could possibly lead to undefined behaviour.

However, they should never occur (it should be impossible to inject data that puts us into this state), and we have never seen an instance of this happen.

Ideally, there would be an assertion in place to verify this, but this codepath is quite old and seems pretty stable (at least, so far, 😉  @TheMarex).

**Comment by daniel-j-h** [comment]
fwiw this was flagged again by clang tidy from llvm 4.0, see
- https://github.com/Project-OSRM/osrm-backend/issues/3820
- https://github.com/Project-OSRM/osrm-backend/pull/3830

I checked it and it's safe. We always check if we moved via invalid edge weight.

(@MoKob sorry I haven't seen this issue earlier, the code location was exactly what I was looking at)
