### ISSUE TITLE
HSRG file missing after osrm-extract

### ISSUE THREAD

**Issue by kilowatthours** [Project-OSRM/osrm-backend#1924]
I'm currently running OSRM on two separate servers, one for testing and one for production. The test machine is running v4.5.0 while the production machine is running v4.9.0. osrm-extract is completing without error on the 4.9.0 machine, however there is no .hsgr file afterwards. What's more confusing is there is a .ebg file on the 4.9.0 machine but not on the 4.5.0 machine. Did something change between these versions? Is this expected?

v4.9.0 file listing:
-rw-r--r-- 1 root root  24G Jan 21 15:19 planet-latest.osrm
-rw-r--r-- 1 root root 7.5G Jan 21 15:54 planet-latest.osrm.ebg
-rw-r--r-- 1 root root 5.6G Jan 21 15:49 planet-latest.osrm.edges
-rw-r--r-- 1 root root  27G Jan 21 15:53 planet-latest.osrm.fileIndex
-rw-r--r-- 1 root root 4.6G Jan 21 15:35 planet-latest.osrm.geometry
-rw-r--r-- 1 root root 117M Jan 21 15:19 planet-latest.osrm.names
-rw-r--r-- 1 root root 8.5G Jan 21 15:54 planet-latest.osrm.nodes
-rw-r--r-- 1 root root 158M Jan 21 15:53 planet-latest.osrm.ramIndex
-rw-r--r-- 1 root root  14M Jan 21 15:19 planet-latest.osrm.restrictions
-rw-r--r-- 1 root root   20 Jan 21 12:54 planet-latest.osrm.timestamp

v4.5.0 file listing:
-rw-r--r-- 1 root root 23281264117 Mar 25  2015 planet-latest.osrm
-rw-r--r-- 1 root root  5504782924 Mar 26  2015 planet-latest.osrm.edges
-rw-r--r-- 1 root root 26506684824 Mar 26  2015 planet-latest.osrm.fileIndex
-rw-r--r-- 1 root root  4490629036 Mar 26  2015 planet-latest.osrm.geometry
-rw-r--r-- 1 root root 16532044660 Mar 26  2015 planet-latest.osrm.hsgr
-rw-r--r-- 1 root root    97693909 Mar 25  2015 planet-latest.osrm.names
-rw-r--r-- 1 root root  6275262952 Mar 26  2015 planet-latest.osrm.nodes
-rw-r--r-- 1 root root   151192252 Mar 26  2015 planet-latest.osrm.ramIndex
-rw-r--r-- 1 root root     6007600 Mar 25  2015 planet-latest.osrm.restrictions
-rw-r--r-- 1 root root          20 Mar 25  2015 planet-latest.osrm.timestamp

**Comment by danpat** [comment]
@kilowatthours Yes, the `.ebg` file is new, and it's quite large.  Check your free disk space, the error checking still needs some work, so it might have silently failed to output the `.hsgr`.

**Comment by TheMarex** [comment]
> however there is no .hsgr file afterwards. 

@kilowatthours that file is generated by `osrm-prepare`. You need to run both.

**Comment by kilowatthours** [comment]
@danpat thanks for the heads-up about the new .egb file.
@TheMarex thanks as well. I guess I never realized when that file was created.

Cheers and sorry for the false alarm!
