### ISSUE TITLE
Project-OSRM -> osrm?

### ISSUE THREAD

**Issue by lxbarth** [Project-OSRM/osrm-backend#1927]
Minor.

`Project-OSRM` is quite the fingerful. Rename organization to simply `osrm`? The full organization name can stay "Project OSRM".

**Comment by daniel-j-h** [comment]
@TheMarex I think you're the only one with admin rights to do this. For users nothing should change:

https://help.github.com/articles/renaming-an-organization/

If you want to keep the Project prefix, please close this ticket.

**Comment by TheMarex** [comment]
I think we will just leave it as is right now, to avoid confusion. Sorry Alex. 😉
