### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#1940]
We should have simple performance tests in OSRM for each service. It's probably enough to have just one test case and execute it many times, outputting runtime then.

Goal is to catch major performance regressions and automatically have numbers to reason about changes. Not sure if the tests should contribute to failing test suites, maybe with very high ceilings. Variability will be high based on execution environment (hello travisci).

The tests can be done in Cucumber. A very early version is https://github.com/Project-OSRM/osrm-backend/blob/develop/features/stress/launch.feature by @emiltin but this only executes many times, not looks at actual performance.

**Comment by freenerd** [comment]
Similarly we should measure memory and disk usage for:

- osrm-extract
- osrm-prepare
- osrm-datastore

**Comment by emiltin** [comment]
you could combine it with the ability to load data from a file if you want a somewhat larger dataset to test on

**Comment by daniel-j-h** [comment]
The current Travis setup is already slow and a pain to work with. Do we really want to run performance tests on the same Travis setup, especially when we want to run them on somewhat larger extracts to reliably benchmark our toolchain?

What other options are there? Creating benchmark scripts and running them once before a new release with optional git-bisecting? Running them once for every bigger change? This is how we handle the more expensive tools like the static analyzer, clang-modernize and clang-tidy already. Take a look at the scripts directory.

**Comment by TheMarex** [comment]
@daniel-j-h can we maybe in-cooperate this in our demo server setup? That machine has plenty of room for post-build benchmarks.

**Comment by daniel-j-h** [comment]
@TheMarex yes, that's a way better option. I still like the idea of having the scripts available in the open, so that others can run it themselves.

**Comment by TheMarex** [comment]
@daniel-j-h we can basically either integrate this into cucumber and add tags to the test that are not run by default. Something like `cucumber --tags @benchmark` and pipe the output log in a publicly readable file or something.

**Comment by daniel-j-h** [comment]
Referencing ticket for service specific benchmarks: https://github.com/Project-OSRM/osrm-backend/issues/2258
