### ISSUE TITLE
osrm-datastore loads data but osrm-routed says "Resource unavailable"

### ISSUE THREAD

**Issue by PureW** [Project-OSRM/osrm-backend#1944]
Hello,

I just tried running the osrm-datastore as I would like to make better use of many cpu's for the same amount of RAM by increasing the number of osrm-routed-processes.

My old setup runs the osrm-routed process in a docker-container and it's been working quite well. For the shared memory approach I am testing in a single docker-container.

I have the problem that the osrm-routed process wont read the shared memory. See the output below.

*Disclaimer, I program mostly python, but occasionally C++, often distributing my work over many processes but I haven't really dealt with shared memory in this way before so I may be doing some silly mistake. But I tried following the wiki completely.*

> 
> root@e748a9c8a8c8:/# free -h
>              total       used       free     shared    buffers     cached
> Mem:          2.9G       520M       2.4G       1.6M        36M       240M
> -/+ buffers/cache:       243M       2.7G
> Swap:         6.0G         0B       6.0G
> root@e748a9c8a8c8:/# /osrm-backend/build/osrm-datastore /data/osrm-data/europe-latest-extracted.osrm
> [info] load names from: "/data/osrm-data/europe-latest-extracted.osrm.names"
> [info] name offsets size: 17663
> [info] allocating shared memory of 1066637251 bytes
> [info] all data loaded
> root@e748a9c8a8c8:/# free -h
>              total       used       free     shared    buffers     cached
> Mem:          2.9G       1.5G       1.4G       1.0G        36M       1.2G
> -/+ buffers/cache:       245M       2.7G
> Swap:         6.0G         0B       6.0G
> root@e748a9c8a8c8:/# /osrm-backend/build/osrm-routed --shared-memory=yes
> [info] starting up engines, v4.8.1
> [warn] caught exception: Resource temporarily unavailable, code 8
> [warn] [exception] Resource temporarily unavailable
> root@e748a9c8a8c8:/#

*shmmax* seems large enough:

> root@e748a9c8a8c8:/# cat /proc/sys/kernel/shmmax
> 18446744073692774399

Host is running Ubuntu 14.04:

> ? uname -a
> Linux packer-trusty 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

And the docker-version is 

> ? docker -v
> Docker version 1.9.1, build a34a1d5

Docker-container is also running ubuntu 14.04.

OSRM-version is fca4aeb50b92a26d4c44a02491a24a203526c0d4.

**Comment by danpat** [comment]
@PureW `osrm-routed` is multi-threaded - by default it detects the CPU count on your machine and will start up 1 thread for each CPU you have.  The demo server at `router.project-osrm.org` runs like this.  You can alter the thread count with `--threads=N`.

Back to the problem at hand though:  can you run `ipcs -a` after you've done `osrm-datastore X.osrm` and dump the output here?  It's a bit hard to guess where the `Resource temporarily unavailable` error is happening, but the first place to look is to see if the shared memory data was loaded properly, and `ipcs -a` should show some allocated shared memory segments if it worked.

**Comment by PureW** [comment]
Yes, I see that it's multithreaded, but I'm having trouble increasing the load above 5 on my 16-core server. I figured it might be because of synchronizing issues in the single-process, multi-threaded osrm-routed process. My hope was that I would be able to increase the load with more processes only sharing memory.

Here's the output of the command:

> root@e748a9c8a8c8:/# ipcs -a
> 
> ------ Shared Memory Segments --------
> key        shmid      owner      perms      bytes      nattch     status      
> 0x0339005b 0          root       644        288        0                 locked
> 0x0439005b 32769      root       644        1066637251 0                 locked
> 0x0039005b 65538      root       644        12         0                 locked
> 
> ------ Semaphore Arrays --------
> key        semid      owner      perms      nsems     
> 
> ------ Message Queues --------
> key        msqid      owner      perms      used-bytes   messages    
> 
> root@e748a9c8a8c8:/# 
>

**Comment by TheMarex** [comment]
@PureW check your disk performance. Every query that does through OSRM needs to read from the `fileIndex` file to snap the coordinates to street segments. Depending on your disk speed that means IO will be your bottle-neck. You will not be able to speed this up by multiple processes (unless they all read their data from independent disks of course).

[This posting](http://stackoverflow.com/questions/22569805/boost-thread-throwing-exception-thread-resource-error-resource-temporarily-una) might indicate the error is coming from the boost threading library that we use. You might want to try adding `-t 1` to osrm-routed.

**Comment by danpat** [comment]
On that topic, try putting the `.fileIndex` on a ramdisk if you can find the space (maybe copy it to ramdisk and symlink to it).

**Comment by daniel-j-h** [comment]
@TheMarex the error message is the representation for errno `EAGAIN`, so I wouldn’t blame it on Boost.Thread without further investigation.

**Comment by PureW** [comment]
@danpat I put the .fileIndex on /dev/shm and symlinked to it. `sudo iotop` now shows negligible disk read/write but still having trouble going above 4-5 in load...

**Comment by PureW** [comment]
I'm closing this issue. Putting the fileIndex into ram and increasing calling process to 16 green threads on the 8 core server keeps the OSRM-process working and takes me to 7.5 in load which is acceptable.

**Comment by PureW** [comment]
@danpat Is your advice still valid for v5.0.0?
> On that topic, try putting the .fileIndex on a ramdisk if you can find the space (maybe copy it to ramdisk and symlink to it).

**Comment by danpat** [comment]
Yes, it's still valid.

If you have the inclination, you can play with the RTree branching factor and leaf node size by changing these values:

https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/static_rtree.hpp#L45-L46

generally, larger leaf nodes perform better on spinning disk media, smaller values for random-access capable layers like SSD.  I don't know what values will work best on `tmpfs`, but you can probably squeeze a little more speed out of it with some work.  You'll need to re-compile from source and re-generate data from scratch between each change.  Note that there's some interplay between the total amount of data you have, and which values work best.  The current values are chosen based on SSD access for planet-sized data.
