### ISSUE TITLE
Apache 5000 port

### ISSUE THREAD

**Issue by bado57** [Project-OSRM/osrm-backend#1948]
Hi , Im install apache server. Than I default port 5000 in httpd.conf. But I running http://82.196.8.79:5000/nearest?loc=52.4224,13.333086 on the webpage, Its give me 404 not found. Please help me. additionally thanks for everything.

**Comment by danpat** [comment]
@bado57 If you've started Apache on port 5000 and haven't configured it for anything else, then the 404 error is perfectly normal.

If you want to run `osrm-routed`, you don't need Apache.  Stop Apache and run `osrm-routed yourfile.osrm`, and `osrm-routed` will listen on port 5000 by default.

Please see this document for details on how to prepare your data files and run `osrm-routed` to serve requests:

https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

**Comment by bado57** [comment]
Hi Dear, we install all steps in this link https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM but we have one problem for the opening webservices. Our error is 

> sudo
>  supervisorctl statusosrm 
> BACKOFF Exited too quickly (process log may have details)

Please help us thank you so much
