### ISSUE TITLE
Running on Server

### ISSUE THREAD

**Issue by bado57** [Project-OSRM/osrm-backend#1949]
Hi Dear, we install all steps in this link https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM but we have one problem for the opening webservices. Our error is

sudo
supervisorctl statusosrm 
BACKOFF Exited too quickly (process log may have details)
Please help us thank you so much

**Comment by bado57** [comment]
My log is INFO gave up: osrm entered FATAL state, too many start retries too quickly

**Comment by emiltin** [comment]
try running it manually or look at the log file to see why it's existing?

**Comment by danpat** [comment]
@bado57 The errors you pasted:

```
supervisorctl statusosrm 
BACKOFF Exited too quickly (process log may have details)
```

and 

```
INFO gave up: osrm entered FATAL state, too many start retries too quickly
```

are not coming from OSRM.  It looks like there is something wrong with your `supervisord` configuration, which is not part of OSRM.
