### ISSUE TITLE
Routing of Public Transport based on GTFS

### ISSUE THREAD

**Issue by rafapereirabr** [Project-OSRM/osrm-backend#1961]
Are there any plans to incorporate routing for Public Transport based on GTFS data ?

**Comment by TheMarex** [comment]
Sorry we don't plan to support public transport as it needs a completely different approach than street-network level routing.

**Comment by daniel-j-h** [comment]
For the record, what I wrote on the OSRM mailinglist a few month ago re. public transport and gtfs:

I recently looked into this for a few hours. This may help you getting started:

GTFS transit feed specification, examples, ecosystem:
https://developers.google.com/transit/gtfs/#overview-of-a-gtfs-feed
https://github.com/google/transit/tree/master/gtfs-realtime

Publicly listed GTFS feeds:
https://code.google.com/p/googletransitdatafeed/wiki/PublicFeeds

Good overview; you can find tools in OtherTools:
https://code.google.com/p/googletransitdatafeed/w/list

(e.g. a routing server for gtfs feeds)

If you want to implement the transit routing yourself, a solid start is
Connection Scan --- "Intriguingly Simple and Fast Transit Routing"

quite easy to implement but also has its limitations.

**Comment by davidmurray** [comment]
Here is a library that let's one do transit routing based on GTFS: github.com/chairemobilite/trRouting

**Comment by rafapereirabr** [comment]
Hi all. I understand there no plans to include support for routing with GTFS data in `osrm`. There are quite a few tools with this capability these days (all of which used OSM data in .pbf format. I list a few of these tools below. BTW, I didn't know trRouting. Thanks @davidmurray.

### R
- [r5r](https://github.com/ipeaGIT/r5r): Rapid Realistic Routing with R5 in R
- [opentripplanner](https://github.com/ropensci/opentripplanner): OpenTripPlanner for R
- [mr4a](https://github.com/ATFutures/m4ra): Many-to-Many Multi-Modal Routing Aggregator

### Python
  - [r5py](https://github.com/r5py/r5py): Rapid Realistic Routing with R5 in Python
  - [urbanaccess](https://github.com/UDST/urbanaccess)

ps. 1. I haven't seen any packages built around the [GraphHopper](https://github.com/graphhopper/graphhopper) routing engine.

ps.2 r5r and r5py are built on top of [Conveyal's **R5** Routing Engine](https://github.com/conveyal/r5). I'm biased (as I'm involved in the development of both r5r and r5py) but I have the impression R5 is problably the more refined option theses days, with multiple capabilities and with very flexible parameters while being very efficient at the same time.

**Comment by nilsnolde** [comment]
It's not ready yet, but it will be in a few weeks and I know I'll forget to update here:
https://github.com/valhalla/valhalla/pull/3700
