### ISSUE TITLE
How much space is needed to extract, prepare, and route the europe map (16gb) OSRM server

### ISSUE THREAD

**Issue by astritzeqiri** [Project-OSRM/osrm-backend#1967]

**Comment by TheMarex** [comment]
Are you talking about disk space or RAM? I would say for preparing plan >100GB disk space and 64GB RAM to be on the safe side.

**Comment by astritzeqiri** [comment]
Thank you vey much..

iI have another question is there a way that i could join two maps together 

Ex. Germany an France or Great britain

**Comment by danpat** [comment]
@astritzeqiri There are directions here:

http://wiki.openstreetmap.org/wiki/Osmconvert#Merging_two_or_more_Geographical_Areas

You will need to ensure that your extracts share some OSM node IDs and have some overlap so they can be properly connected.
