### ISSUE TITLE
POST requesting API

### ISSUE THREAD

**Issue by SergioVasquezGeocentrix** [Project-OSRM/osrm-backend#1969]
Good afternoon,

I am really new to OSRM and I need to do a huge table request and the GET request is not enough for sending all the data that I have. I read that it is possible to make a POST request but I have not seen any example or even the API of this feature.

I will appreciate any information about that POST topic, because I am trying to avoid to make shared memory communication.

Best regards,
Sergio Vásquez

**Comment by daniel-j-h** [comment]
Does this example help? https://github.com/Project-OSRM/osrm-backend/issues/1805

**Comment by SergioVasquezGeocentrix** [comment]
Not exactly. I was expecting to communicate a Json to the POST request.

**Comment by TheMarex** [comment]
We only support URL encoded POST requests.
