### ISSUE TITLE
Switch test from Ruby to Javascript based cucumber

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1973]
Currently our integration tests rely on cucumber which runs on Ruby. We want to reduce our dependencies and switch from Ruby to Javascript using: 

https://github.com/cucumber/cucumber-js

Since we are breaking the API we would need to rewrite a lot of the support code anyway. Let's use this as an opportunity to clean this up. An additional thing we might want to make sure is that our new support code could easily be replace by calls to `node-osrm` instead of hitting the HTTP API.

My current brain dump of how we could be doing this:
- Update https://github.com/Project-OSRM/osrm-client-js to use our [new HTTP API](https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api)
- Rewrite the [support code](https://github.com/Project-OSRM/osrm-backend/tree/develop/features/support) and the [step definitions](https://github.com/Project-OSRM/osrm-backend/tree/develop/features/step_definitions):
  - [x] write code to generate `.osm` files from tables
  - [x] write the code to run the pipeline
  - [x] write the code to run queries against `osrm-routed` using `osrm-client-js`
 
@lbud  would you like to investigate how much effort this will be?

**Comment by lbud** [comment]
> @lbud would you like to investigate how much effort this will be?

on it :ok_hand:

**Comment by emiltin** [comment]
I think this is a very good idea. It will reduce dependencies and can run faster with direct calls to node-osrm. In case we still want to test the HTTP API we can always add a few test specifically for that.

The support code handing the various tables types etc. have grown quite a lot over time and could benefit from some refactoring.

**Comment by TheMarex** [comment]
This has been merged :tada:
