### ISSUE TITLE
Broken UK route between A20 to Dover. Can someone help us solve this please?

### ISSUE THREAD

**Issue by kushagrabhargava** [Project-OSRM/osrm-backend#1977]
Hello,

We are using our OSRM instance for routing applications and since our last update on 1st Feb we have ran into a routing problem.

We have observed a problem on one of our route which were correct before between A20 Archcliffe Road (51.11420, 1.30183) going east 300meters approx to A20 Archcliffe Road (51.1146, 1.3043) over a roundabout. This route now goes all round A20 west via B2011 and A256 giving a total route of 12kms.

Please see the link below:

https://www.openstreetmap.org/directions?engine=osrm_car&route=51.1143%2C1.3023%3B51.1146%2C1.3043#map=14/51.1151/1.2765

Using Mapzen the routing works correctly as plotted below:

https://www.openstreetmap.org/directions?engine=mapzen_car&route=51.1143%2C1.3023%3B51.1146%2C1.3043#map=19/51.11449/1.30330

I have tried to correct this problem on the OpenStreetMap editor by removing a barrier tag which was at the start of this roundabout which looked like a possible cause. But it hasn’t worked and routing is still incorrect for OSRM.

Also, when trying to fix this problem found another.

Generate a straight route from a junction exit on A20 roundabout B2011 (51.10479, 1.24031) to exit of B2011 to A20 (51.10479, 1.24031) and the OSRM routing fails.

The route is blocked at the exit of B2011 round about. So the route generated is very long via Folkestone Road, A256 and back on A20 on other side of the carriage way. Please see the link below:

https://www.openstreetmap.org/directions?engine=osrm_car&route=51.10565%2C1.23703%3B51.10434%2C1.24182#map=14/51.1151/1.2753

If I select the Mapzen routing for the same the correct route is displayed as plotted below:

https://www.openstreetmap.org/directions?engine=mapzen_car&route=51.1057%2C1.2370%3B51.1043%2C1.2418#map=18/51.10501/1.23943

Can someone please be able to help with this routing problem as these routes are very crucial for our systems.

Thank you.

Kind regards,
Kushagra Bhargava

**Comment by TheMarex** [comment]
I don't see your routing problems. Could it be that the data update already fixed it?

**Comment by scaidermern** [comment]
This question was also asked at [help.openstreetmap.org](https://help.openstreetmap.org/questions/48106/broken-uk-route-between-a20-to-dover-can-someone-help-us-solve-this-please). According to the comments the routing problem disappeared after removing a strange barrier. So there seems to be no bug.

**Comment by kushagrabhargava** [comment]
Hi there, yes I checked this few hours back and the changes I made to remove the barrier were updated and fixed the problem for both the roundabouts mentioned above. Thanks.
