### ISSUE TITLE
Large table size for time route matrix only using one thread

### ISSUE THREAD

**Issue by daguix** [Project-OSRM/osrm-backend#1979]
Hi,

  I am using osrm-routed for a very large table size (3000x3000). I moved from a 1-vCPU instance to a 36-vCPU but I see no gain in speed. What am I missing please?

Regards.

**Comment by danpat** [comment]
`osrm-routed` will handle multiple requests in parallel, but each request is single threaded.

**Comment by daguix** [comment]
So I need to split the request myself and gather the data at the end. OK I got it.
