### ISSUE TITLE
highway=road not in car profile

### ISSUE THREAD

**Issue by frodrigo** [Project-OSRM/osrm-backend#1980]
The OSM `highway=road` is in cycle and pedestrian profiles, but not in cars profile.

After looking around in issues, I found this one #1376. With the interesting part:
>  DennisOSRM commented on 9 Feb 2015
> 
> There's temporary data (red in image below) of highway=road. These are ignored on purpose and easy to fix.

But it's not coherent on using `highway=road` not for cars but using it in other profiles.

I propose to add `highway=road` on car profile with some default speed value.

**Comment by daniel-j-h** [comment]
If you read the [OSM wiki on this tag](http://wiki.openstreetmap.org/wiki/Tag:highway%3Droad) it implies a generic and unclassified road, that needs to get fixed before any meaning can be assigned to it. But then again taking a look at Taginfo shows [300k of these](http://taginfo.openstreetmap.org/tags/highway=road).

**Comment by frodrigo** [comment]
Hopefully `highway=road` are unfrequent. But not so far of the `motorway_link` number. And we need `road` or `motorway_link` highway type to ensure network continuity.
In my mind default car profile should be usable, not a debug tool.

**Comment by daniel-j-h** [comment]
I don't understand you regarding `motorway_link`.

The [car profile](https://github.com/Project-OSRM/osrm-backend/blob/f14352f49427711500b911b804e849ad7cfb16e4/profiles/car.lua#L17) already handles `motorway=link`. Could you elaborate on that?

**Comment by frodrigo** [comment]
`motorway_link` was an example, there are 500k `motorway_link` on tag info. But we need it to assure continuity, and I think it's the same about `road`.

**Comment by daniel-j-h** [comment]
I understand.

What default value would you set for `highway=road` in the car profile? Using a low speed value to be _on the safe-side_ has on the one hand the benefit that we can route over it. On the other hand it greatly distorts ETAs since we have no information whatsoever for the underlying road.

**Comment by TheMarex** [comment]
Since we can't reason about what a `highway=road` is, I opt to only include the "safe" cases that actually set a `maxspeed` and `access` tag. Otherwise we might include a bunch of `highway=track` in the network, sending people over definitely unusable streets.

**Comment by chtnha** [comment]
[OSM Inspector](http://tools.geofabrik.de/osmi/) shows that `highway=road`s are distributed more in where forest/mountains are covered, I don't see any major cities mapped more with this tag. Any of the above discussions relates these words?

**Who mapped these roads and how?**

* Newbies to OSM
* Users who don't have ideas on [highway classifications](http://wiki.openstreetmap.org/wiki/Highways). 
* Looking into old imagery.

**Comment by frodrigo** [comment]
http://tools.geofabrik.de/osmi/?view=highways&lon=28.24464&lat=59.48446&zoom=6&overlays=type_road

**Comment by frodrigo** [comment]
`highway=road` + `access` 4k items
`highway=road` + `maxspeed` 2k items
I don't know what is most annoying, bad EAT because we use a misclassified highway (that can be a track) or a detour of many kilometres because we totaly avoid the `highway=road`

**Comment by emiltin** [comment]
wrong ETA could be solved by separating speed and weight

**Comment by frodrigo** [comment]
For fighting agains highway=road I added I new check in Osmose-QA, despite there is already a map in OSMI:
http://osmose.openstreetmap.fr/map/#item=4061&class=40611

**Comment by daniel-j-h** [comment]
Awesome, thanks a lot for this! I will definitely show this around for checking and fixing important ways.
