### ISSUE TITLE
Allow multiple traffic update files, and track them in debugging output

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1983]
Currently, you can only apply a single `.csv` file to traffic updates, like this:

  `osrm-prepare --segment-speed-file updates.csv somefile.osrm`

Any segments in `updates.csv` will be applied to the edge-based graph, and the updates be visible in the debugging GeoJSON.

It's simple enough to join multiple traffic sources together by concatenating `.csv` files together, but it would be useful to be able to keep them separate (save some IO time) so we can add meta-data to the debugging output and expose which source edges got their weights from.

To achieve this, we need to:

   - [x] Load multiple files instead of just one: https://github.com/Project-OSRM/osrm-backend/blob/develop/src/contractor/contractor.cpp#L179-L188  Suggested simple approach: `--segment-speed-files updates1.csv,updates2.csv,updates3.csv`
   - [x] Along with each edge speed, store the filename that it gets loaded from: https://github.com/Project-OSRM/osrm-backend/blob/develop/src/contractor/contractor.cpp#L172   Instead of being `std::unordered_map<std::pair<OSMNodeID, OSMNodeID>, unsigned> segment_speed_lookup;`, this should be something like:  `std::unordered_map<std::pair<OSMNodeID, OSMNodeID>, std::pair<unsigned,std::string>> segment_speed_lookup;`, where the string part is the filename.
   - [x] When we write out the `properties {}` GeoJSON object, we should also write out the filename that was the source of this particular speed value.

One optimization here would be to put the filenames in an array, and just store the index in the array for the filename.  Storing a `std::string` for every edge would be quite expensive.

/cc @karenzshea

**Comment by daniel-j-h** [comment]
Hint for the argparser

     ("segment-speed-files", boost::program_options::value<std::vector<std::string>>()->multitoken()->composing())

is what you need for parsing `--segment-speed-files a b c`.

**Comment by daniel-j-h** [comment]
This landed! In addition lookups should be noticeable faster now with the flat map + binary search approach. We also log the datasources used and their contribution during merging.
