### ISSUE TITLE
osrm server search by postal code not latitude

### ISSUE THREAD

**Issue by astritzeqiri** [Project-OSRM/osrm-backend#1985]
i get the distance between two points with osrm but it isnt showing it right so i want to get it from the postal codes.

one solution i made was getting the lat,lng from google by sending the postal code then feeding the locations to osrm but that is not working quiet well.

so is there any other way to do this.

**Comment by TheMarex** [comment]
Try to use http://wiki.openstreetmap.org/wiki/Nominatim. Geocoding is not the scope of this project.
