### ISSUE TITLE
Experiment with mmap in StaticRTree

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1987]
We can possibly save the cost of a syscall in our StaticRtree here:

https://github.com/Project-OSRM/osrm-backend/blob/908a9e9fa1aa818b634b5196758192dfd369ec6c/include/util/static_rtree.hpp#L445-L460

by using `mmap` to access the leaf node data.

This StackOverflow ticket: http://stackoverflow.com/a/5589622
talks about some of the tradeoffs.  Because we do quite a lot of IO on each nearest-neighbor search, it's not clear to me whether we're a good candidate for `mmap`.  We should measure this.

/cc @daniel-j-h

**Comment by daniel-j-h** [comment]
Hints

- [file_mapping / mapped_region](https://github.com/mapbox/tmpfs-mmap-zero-copy/blob/d324965f5e15ffbb5d70d4f17d27dbd01061ca0f/mapping.h#L30)
- [non-owning array_view](https://github.com/mapbox/tmpfs-mmap-zero-copy/blob/d324965f5e15ffbb5d70d4f17d27dbd01061ca0f/core.cc#L87-L89)

**Comment by TheMarex** [comment]
This is implemented as part of https://github.com/Project-OSRM/osrm-backend/pull/2385

**Comment by TheMarex** [comment]
Landed.

**Comment by daniel-j-h** [comment]
Did you try setting hints such as madvise or pre-faulting pages? I think the Boost.IOStream's mmap features are very basic only and do not support this. Boost.Interprocess' mapped_region is more advanced in this regard. (Otherwise ifdef and syscalls)
