### ISSUE TITLE
Use of urban speed limits in profile

### ISSUE THREAD

**Issue by kostadin24** [Project-OSRM/osrm-backend#1989]
Hello,
I have question about limiting speed in urban areas.
I have speed table like default car.lua and urban speed limit there is 50km/h.
How does this limit applies on roads in city?
I'm not sure that all roads in urban area have tag with info is there a urban area or not.

**Comment by TheMarex** [comment]
We sadly rely on explicit tagging of `maxspeed` values. There is no easy way to derive if a road is governed by urban speed limits.
