### ISSUE TITLE
Completely broken in Firefox Nightly and less but almost completely in FF45 Beta

### ISSUE THREAD

**Issue by mcepl** [Project-OSRM/osrm-backend#1990]
Hi,

when opening your page in Firefox 45 (Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0) I get page displayed, but when I try to find a route, I fail. When I enter to the first box "rue gambetta, treguier" and press ENTER, the location gets displayed, but when I enter to the second box "roissy-en-france" (hoping to get http://osm.org/go/0BPlKcx?relation=530470) and press ENTER, I get no response from the site.

The same goes for Firefox Nightly (Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0).

**Comment by TheMarex** [comment]
@mcepl thanks for your bug request. Could you move this to https://github.com/Project-OSRM/osrm-frontend-v2 which is what powers our demo website. Thanks!

**Comment by mcepl** [comment]
Done, https://github.com/Project-OSRM/osrm-frontend-v2/issues/157
