### ISSUE TITLE
Could not find a matching segment

### ISSUE THREAD

**Issue by Pieter-Vdm** [Project-OSRM/osrm-backend#1992]
When I match tracks that contain segments that are not in OSM, I get the following error message:
`{"status":208,"status_message":"Could not find a matching segment for coordinate x"}`
Based on the documentation I would expect an answer with different subtraces where the outliers are removed.

Example call:
`https://router.project-osrm.org/match?loc=50.78563,3.79882&loc=50.78474,3.79741&loc=50.78347,3.8002799999999&loc=50.78125,3.8019400000001&loc=50.77927,3.8028899999999&loc=50.77828,3.8029300000001&loc=50.77791,3.8027999999999&loc=50.77792,3.8031599999999&loc=50.7765,3.804&loc=50.77492,3.80521&loc=50.77482,3.80672&loc=50.77498,3.80781&loc=50.77443,3.80981&loc=50.77425,3.81161&loc=50.77376,3.81242&loc=50.77215,3.8141900000001&loc=50.77134,3.81442&loc=50.77173,3.8185599999999&loc=50.77043,3.81903&loc=50.76772,3.82194&loc=50.76625,3.82326&loc=50.76363,3.82736&loc=50.76325,3.82736&loc=50.76283,3.8276&loc=50.76129,3.82913&loc=50.75967,3.8300400000001&loc=50.7566,3.83287&loc=50.75632,3.8324&loc=50.75491,3.83214&loc=50.75372,3.83164&loc=50.75231,3.83192&loc=50.75174,3.83185&loc=50.75181,3.83268&loc=50.75228,3.83383&loc=50.75241,3.83484&loc=50.753,3.83596&loc=50.75312,3.83731&loc=50.75323,3.83759&loc=50.75356,3.83725&loc=50.75514,3.84221&loc=50.75618,3.84446&loc=50.75763,3.84977&loc=50.75803,3.85238&loc=50.75787,3.85317&loc=50.75709,3.8536799999999&loc=50.75678,3.85411&loc=50.75773,3.85538&loc=50.75801,3.8562899999999&loc=50.75864,3.85695&loc=50.75982,3.85893&loc=50.76068,3.86107&loc=50.7612,3.8614700000001&loc=50.7614,3.86135&loc=50.76253,3.86357&loc=50.76267,3.86446&loc=50.76209,3.86632&loc=50.76221,3.8669199999999&instructions=true&gps_precision=5`

Response:
`{"status":208,"status_message":"Could not find a matching segment for coordinate 13"}`

**Comment by TheMarex** [comment]
Yes should be possible to automatically split the trace in that case.

**Comment by TheMarex** [comment]
This is fixed in the 5.0 API branch.
