### ISSUE TITLE
Is route_summary::total_time  when doing viaroutes request wrong?

### ISSUE THREAD

**Issue by SergioVasquezGeocentrix** [Project-OSRM/osrm-backend#1993]
Hey everyone,

I am using the total_time that is returned and also checking the time till every stop using the timing in every route_instructions, but they never add up to the same value, even in your example in [osrm-backend/Server-api ](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api) it is possible to see this:

"route_summary": {
        "end_point": "Krautstra\u00dfe",
        "start_point": "Adalbertstra\u00dfe",
        "total_distance": 2034,
        "total_time": **164**
    },

and 

"route_instructions": [
        ["10", "Adalbertstra\u00dfe", 251, 0, **26**, "250m", "NE", 23, 1],
        ["3", "Bethaniendamm", 719, 9, **53**, "719m", "E", 99, 1],
        [1", "Schillingbr\u00fccke", 90, 41, **6**, "90m", "NE", 27, 1],
        ["1", "An der Schillingbr\u00fccke", 108, 43, **12**, "108m", "NE", 28, 1],
        ["1", "Andreasstra\u00dfe", 533, 46, **40**, "532m", "N", 13, 1],
        ["7", "Singerstra\u00dfe", 212, 62, **22**, "212m", "W", 281, 1],
        ["3", "Krautstra\u00dfe", 120, 66, **12**, "120m", "N", 13, 1],
        ["15", "", 0, 69, **0**, "0m", "N", 0]
    ],
where 26 + 53 + 6 + 12 + 40 + 22 + 12 + 0 = **171**

Why is there this difference? Is this an expected behaviour?

Best Regards,
Sergio Vásquez

**Comment by daniel-j-h** [comment]
Thanks for reporting, this is already tracked in https://github.com/Project-OSRM/osrm-backend/issues/1575.

Closing here. Please read the linked ticket and head over there.
