### ISSUE TITLE
Return camel-case codes

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#2005]
In `develop` the body of successful responses returns `"code": "ok"` but to stay in line with the documentation this should be camel-case `"code": "Ok"`

**Comment by freenerd** [comment]
Looks like codes generally aren't camel cased at the moment, e.g.

```
{ code: 'no-route', message: 'Impossible route between points' }
```

**Comment by emiltin** [comment]
it might be a matter of style, but i prefer lowercase 'ok' and 'no-route'

**Comment by freenerd** [comment]
@emiltin there is definitely no right or wrong answer here. the only weak argument i have is that [5 days ago](https://github.com/Project-OSRM/osrm-backend/issues/519#issuecomment-185918004) we already discussed this and the docs have camel case now.

**Comment by TheMarex** [comment]
Done.
