### ISSUE TITLE
Compiler LTO binutils detection for gcc >= 4.9 seems to be broken on some platforms

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2006]
[These lines in CMakeLists.txt](https://github.com/Project-OSRM/osrm-backend/blob/69bc8a8b2214da798ffd39f6ebd98d82a1bf5103/CMakeLists.txt#L136-L141) make sure we use gcc's binutils like `gcc-ar` for LTO on gcc >= 4.9.

[The Ubuntu packages for gcc >= 4.9](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+files/gcc-5_5.2.1-23ubuntu1~12.04_amd64.deb) name their binaries with a version suffix, such as `gcc-ar-5`

With gcc 5.2 on Travis, [we see the code path for gcc specific binutils triggers](https://travis-ci.org/Project-OSRM/node-osrm/jobs/111112018#L691) but then [trying to invoke `gcc-ar` fails](https://travis-ci.org/Project-OSRM/node-osrm/jobs/111112018#L788) since there is no binary named like that (i.e. the version suffix is missing).

Fix naming scheme to `gcc-ar-4.9` in `CMakeLists.txt`.

Blocks:
- https://github.com/Project-OSRM/osrm-backend/pull/1975 and
- https://github.com/Project-OSRM/node-osrm/pull/153

**Comment by springmeyer** [comment]
See also #2120, which is the new blocker for https://github.com/Project-OSRM/node-osrm/pull/153 since I'd prefer to use clang++ over g++ because:

  - We dodge the problem of not easily being able to upgrade from g++ 5.2 -> 5.3 on `sudo:false` machines
  - Clang++ is much faster to compile OSRM

**Comment by springmeyer** [comment]
>Blocks:
> #1975 and
> Project-OSRM/node-osrm#153

Both of those issues are solved and #2120 is also now solved which means:

  - We support c++14
  - We support -flto with clang++ 3.8.x + binutils 2.27

@daniel-j-h anything more to do around gcc before closing this? /cc @TheMarex

**Comment by daniel-j-h** [comment]
Some platforms are still hitting this issue (see https://github.com/Project-OSRM/osrm-backend/issues/3441) which makes compilation fail by default.
Even on master (the soon-to-be 5.5 stable release).

**Comment by daniel-j-h** [comment]
Closing as resolved. We disable lto now by default: https://github.com/Project-OSRM/osrm-backend/pull/3524.

If you know what you're doing you can pass `-DNEBALE_LTO` to cmake in order to re-enable LTO.
