### ISSUE TITLE
StaticRTree math broken

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2015]
StaticRTree saves the bounding boxes of all segments in the Longitude/Latitude coordinate system. The distance metric used is the "great circle distance" which calculates the distance on a sphere. However this metric is **not euclidean**.

The `GetMinDist` code assumes we are in an euclidean space. This is wrong. There are points within the bounding box that are nearer than this lower bound. This breaks the nearest neighbor searches and I have a test case for this.

I see two options:
- Stick completely to euclidean measurements in StaticRTree:
  - "pretend longitude and latitude just normal coordinates"
  - Euclidean distance will **not** be in meters -> never expose, only good for relative sorting of the query queue
  - would work with what the user expects visually, snapping will not be at the actually nearest point
- Fix `GetMinDist` to not assumes stuff is in euclidean space
  - There might be a clever method here I don't see

/cc @danpat

**Comment by TheMarex** [comment]
Started implementing this [here](https://github.com/Project-OSRM/osrm-backend/tree/fix/euclidean_rtree) but I'm going to post-pone after the 5.0 merge.

**Comment by danpat** [comment]
@themarex we could store coordinates in EPSG:3857 instead of wsg84, then GetMinDist could remain euclidean (I think).  I worry about the additional overhead of sorting by great circle or haversine distance during the search. The nn lookup is already the slowest part of a query.

Coordinates EPSG:3857 should give results close to metres for local comparisons.

**Comment by daniel-j-h** [comment]
For min queries what about using a technique similar to `comparable_distance` from Boost.Geometry? Take a look at a dev's blog here: http://barendgehrels.blogspot.de/2010/07/efficient-distances.html

Good enough for _internal_ sorting (and way faster!).

**Comment by TheMarex** [comment]
Main problem I see is this we expose the search radius now over the `radiuses` parameter. That means whatever we use for internal sorting, we need to be able to translate the external maximum search radius into the internal metric.

So one way we could try to do this is the following:
- internally we use projected coordinates + comparable distance to sort the queue
- for each segment we need to compute the distance twice: comparable distance when inserted in the queue and real distance when we terminate the search.

This would still mean we would not find the actual nearest segment w.r.t. the "real" on the ground distance, but only the nearest segment visually on the map. (which is IMHO okay)

**Comment by TheMarex** [comment]
Fixed by #2175.
