### ISSUE TITLE
Cars being routed on pedestrian paths

### ISSUE THREAD

**Issue by kvvok** [Project-OSRM/osrm-backend#2017]
OSRM is responding with a route for a car taking a pedestrian path (see image and link below). 

![image](https://cloud.githubusercontent.com/assets/13138412/13328772/6666eb16-dba5-11e5-9711-bee82acb07ba.png)
https://www.openstreetmap.org/directions?engine=osrm_car&route=43.64733%2C-79.38299%3B43.64820%2C-79.37954#map=18/43.64781/-79.38129&layers=T

Details about data:
![image](https://cloud.githubusercontent.com/assets/13138412/13328906/25c07fa4-dba6-11e5-9730-4b977982ebc5.png)
https://www.openstreetmap.org/way/368367342

**Comment by TheMarex** [comment]
All these footways are tagged wrong. `access=permissive` means access for all modes of transportation. They should be tagged `foot=permissive`.

**Comment by kvvok** [comment]
Thanks @TheMarex.  Any ideas on how we can go about updating the tags systematically?
