### ISSUE TITLE
hint/hint_data docu

### ISSUE THREAD

**Issue by AlexanderLanin** [Project-OSRM/osrm-backend#2018]
Hi all,

I'm new to osrm and therefore I was reading https://github.com/Project-OSRM/osrm-backend/wiki/Server-api which refers to https://github.com/Project-OSRM/osrm-backend/wiki/API%20Usage%20Policy

It states users MUST implement "hinting mechanism" however there is absolutely no documentation to be found (or I'm just too stupid). Anyway if it's a MUST then it MUST be linked.

I can definitely say that the few words in API documentation are not enough to get someone new started on using hints.

**Comment by TheMarex** [comment]
You can have a look at the current implementation in Leaflet Routing Machine [here](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.OSRM.js). 
You are right it needs better documentation but it should be much easier in the new API.

That said the API is going to change in a few weeks (on the demo server) [quite dramatically](https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api) so you might hold of on implementing this yourself.

For me its more important that you make sure your user agent is identifiable and you don't plan on putting this into commercial offerings.

**Comment by daniel-j-h** [comment]
Hint is better documented now, please see:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#properties-4
