### ISSUE TITLE
Rework osrm::exeption implementation

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2022]
`osrm::exception` from `util/exception.hpp` holds a `std::string` and implements its own `.what()` member function. But we actually never catch for `osrm::exception` and call `.what()` on it. Instead we inherit from `std::exception`, so that by means of subtyping we're getting caught anyway.

Better: inherit from `std::runtime_error` which already handles message handling / `.what()` for us. Also, only declare exception type in header, define in implementation file.

Should be the following ~3 lines instead of the (incorrect) ~10 lines at the moment:

```
struct OSRMException final : std::runtime_error {
  explicit OSRMException(const char* msg) : std::runtime_error{msg} {}
};
```

**Comment by TheMarex** [comment]
Main problem here is that `runtime_error` takes a `const char*` but we often put in `std::string` since we use runtime concatenation to generate error messages.

**Comment by daniel-j-h** [comment]
We can either call `.c_str()` on the `std::string` in those situations or provide a single non-explicit

    OSRMException(const std::string& s) : std::runtime_error{s} {}

**Comment by daniel-j-h** [comment]
Inheriting from `std::runtime_error` would break the API as `libosrm` users can notice the change in behavior. I'm scheduling this for 6.0 where we can and should change this.
