### ISSUE TITLE
Debug geoJSON mode giving empty file - please help!

### ISSUE THREAD

**Issue by MikeLeonard** [Project-OSRM/osrm-backend#2024]
Hi all

Please can someone help me get osrm-prepare working with the new --debug-geometry option? I have the --debug-turns option working for osrm-extract, but using osrm-prepare with --debug-geometry only gives me an empty geoJSON file!

It's empty but does write something at least... it looks like this:
{"type":"FeatureCollection", "features":[

]}

MORE DETAILS:

Relevant links:

The initial commit: https://github.com/Project-OSRM/osrm-backend/pull/1785
An update to the commit: https://github.com/Project-OSRM/osrm-backend/pull/1966 and https://github.com/Project-OSRM/osrm-backend/issues/1956

A recent 'Vector tile plugin' branch that seems to be related: https://github.com/Project-OSRM/osrm-backend/issues/1953 and https://github.com/Project-OSRM/osrm-backend/pull/2000

Why do I need this?

I need to extract from OSM a map of the road networks. I can do this with various tools (e.g. osm-extract, overpass-api, etc.). However if I do this then the road network I get won't exactly tie up with the road network that OSRM is using, which I need it to do for my purposes. 

I could try to match how the car.lua file keeps and discards various OSM tags of course (and will be trying to do this if I can't get the geometry geoJSON out using --debug-geometry)... however I would really prefer the geoJSON file for two key reasons: 
(1) it aligns perfectly with the road network that OSRM is using internally, and 
(2) the geoJSON file from what I've read also comes with the speed values calculated by the car.lua file which would be really useful to have for my application.

I need the geoJSON file for the whole of the UK, and am happy if this takes ages to create or is many GB in size.

What have I tried?

I've pasted my exact steps below. I've repeated the same steps using the most recent version of the develop branch as well as going back in 'detached-head mode' in git and going back to the relevant merges of the features into develop (just in case something recently broke the functionality). All these produce the same empty geoJSON file unfortunately.

Note: I've also quickly tried reading the .osrm file and other intermediate files produced by osrm-extract and osrm-prepare. However I couldn't really get passed the binary format of these and so have focused on the geoJSON from --debug-geometry instead as that format would be perfect and it already comes with the speed values which I need.

Solutions:

I'm assuming that someone has had this working before and that I'm doing something wrong. Is that right?

Assuming it's me: are there any other new system requirements I need for this feature. I've turned on debugging when compiling with cmake. It's strange that --debug-turns works for me but --debug-geometry doesn't - does anyone know why this might be? Unfortaunelyt I don't know any C++ to work this out myself (although I have a friend here who can help me if we get pointed in the right direction).

Thank you in advance:

As I said above having the road network that osrm (via the car.lua profile) creates is super important to me at the moment so I just wanted to express my gratitude to anyone that can help! Thanks very much in advance.

Thanks

Mike

System:
AWS EC2 ubuntu instance. Happy to provide more details of my system if that would help!

Exact steps taken so far: 
(I can paste the screen output of these steps if that would help)

cd ~
git clone https://github.com/Project-OSRM/osrm-backend.git
[git checkout: here I tried a few different commits in the develop branch to test if one would work but no luck]
cd osrm-backend
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TOOLS=1 -DDEBUG_GEOMETRY=1
sudo cmake --build . -- -j
wget http://download.geofabrik.de/europe/great-britain/england/dorset-latest.osm.pbf

./osrm-extract -p ~/osrm-backend/profile.lua dorset-latest.osm.pbf --debug-turns turns
./osrm-prepare -p ~/osrm-backend/profile.lua dorset-latest.osrm --debug-geometry geometry

...the 'turns' file is perfect... however the 'geometry' geoJSON file is empty. Please help! Thanks so much in advance :)

**Comment by danpat** [comment]
@MikeLeonard The `--debug-geometry` feature was implemented specifically to help diagnosing problems when importing traffic data.  As such, it only activates properly when traffic data is imported.

Fortunately, the quick hack is to just supply an empty file.  You'll need to do this:

`osrm-extract --generate-edge-lookup --debug-turns turns.geojson -p profile.lua  yourosmfile.osm.pbf`

then:

`touch emptyspeedfile.csv`

then:

`osrm-prepare --segment-speed-file emptyspeedfile.csv --debug-geometry geometry.geojson -p profile.lua yourosmfile.osrm`

and that should trigger the necessary logic.

Just to give you an idea of the data size, the GeoJSON output for the USA is about 180GB.  Dorset should be quite a lot smaller.

Please note that this whole feature has been deprecated in favour of the vector tile plugin that can be used with Mapbox GL (or other vector tile viewer, like perhaps this: http://giswiki.hsr.ch/Vector_Tiles_Reader_QGIS_Plugin) for visualizing the road network directly from a running OSRM instance.

**Comment by danpat** [comment]
No longer pertinent, we now generate vector tiles directly from `osrm-routed` for serving up in realtime.
