### ISSUE TITLE
Document public libosrm API

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2026]
The header files. Not in the Wiki, not on The Web (tm). But directly in the header files. Maybe with Doxygen-style comments, to eventually generate beautiful looking docs from it.

**Comment by freenerd** [comment]
Companion tickets on node-osrm https://github.com/Project-OSRM/node-osrm/issues/99 https://github.com/Project-OSRM/node-osrm/issues/149

**Comment by daniel-j-h** [comment]
We expect users to use `libosrm` but don't really provide beginner-friendly documentation (or documentation at all). The [Wiki on Library API](https://github.com/Project-OSRM/osrm-backend/wiki/Library-api) is incomplete and not ready for v5.

With the `POST` feature removal from routed this is getting even more important.

I did a brain dump on how to use `libosrm` [over here](https://github.com/Project-OSRM/osrm-backend/issues/2163#issuecomment-203327232) that needs some polishing and updating the Github URLs once we have documentation and a release in place, but then I would love to update the Wiki with something like this.

----------------------------------------------------------------------------------------------------------------------------

- [ ] add beautiful code comments to publicly facing `libosrm` interface
- [ ] update Library API wiki page

**Comment by daniel-j-h** [comment]
Done. Wiki: https://github.com/Project-OSRM/osrm-backend/wiki/Library-api, Code: https://github.com/Project-OSRM/osrm-backend/issues/2190.

**Comment by TheMarex** [comment]
Perfect merged.
