### ISSUE TITLE
Do not rely on Boost.Filesystem's basename function

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2027]
Deprecated. Rationale and alternative solutions in the references below.

Once done, do this:

> For new code, defining BOOST_FILESYSTEM_NO_DEPRECATED before including filesystem headers is strongly recommended. This prevents inadvertent use of old features, particularly legacy function names, that have been replaced and are going to go away in the future.

`add_definitions(-DBOOST_FILESYSTEM_NO_DEPRECATED)`

References:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=565504
- http://lists.boost.org/Archives/boost/2010/01/160905.php

**Comment by daniel-j-h** [comment]
Stumbled over this again today, https://github.com/Project-OSRM/osrm-backend/blob/4d864b8267faf003f395f839abf0ed5458de2a41/CMakeLists.txt#L223-L224.

**Comment by TheMarex** [comment]
Fixed by referencing commit.
