### ISSUE TITLE
Initialize server paths from base paths

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2030]
There is no reason we expect users to [set 9 (!) different paths](https://github.com/Project-OSRM/osrm-backend/blob/df20245096c3926de7a601808ecf569d66298078/example/example.cpp#L35-L44) for initializing an osrm engine.

The user should only have to set the base path from which all server paths are derived (with the option to change specific paths in "advanced mode"; e.g. to put the fileIndex on tmpfs without the need for a symlink).

routed already has a internal and local populate_base_paths function, why not actually use this idea?

**Comment by emiltin** [comment]
That's how it already work? You only need to pass the path to the .osrm file, and it will find all the other files as long as they're in the same folder.

**Comment by daniel-j-h** [comment]
You are right for using the `osrm-*` binaries. But only because each of the binaries derives the file names itself (see below for two examples). Using `libosrm` you have to do this yourself like [this](https://github.com/Project-OSRM/osrm-backend/blob/df20245096c3926de7a601808ecf569d66298078/example/example.cpp#L35-L44) (which is ugly).

- https://github.com/Project-OSRM/osrm-backend/blob/04765d82ba563b8725d72117f0743331e97224df/include/util/routed_options.hpp#L29-L106
- https://github.com/Project-OSRM/osrm-backend/blob/04765d82ba563b8725d72117f0743331e97224df/src/tools/store.cpp#L90-L202

**Comment by emiltin** [comment]
ok get it

**Comment by TheMarex** [comment]
@daniel-j-h This is an artifact from the ini-support we had (and removed). :+1: To moving to a single path parameter.
