### ISSUE TITLE
Provide an "osrm-config" command as alternative to pkg-config

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/osrm-backend#2033]
It is great that osrm-backend provides a libosrm.pc for use with pkg-config because it is foreseeable that various tools might use this.

However the pkg-config support was originally created for the use of node-osrm and ideally node-osrm would depend not on pkg-config but rather a custom named command called `osrm-config`. The reasons are:

 - Having an extra dependency on pkg-config is annoying when all node-osrm needs is a few things like library and include paths
 - When osrm-backend is installed in a custom location to be able to use pkg-config the PKG_CONFIG_PATH needs to be set.

Providing an `osrm-config` would make things better by:

  - Reducing another dependency of the node-osrm build
  - Allowing only PATH to be set to point at a custom `osrm-config` location (and not having to set PKG_CONFIG_PATH).

**Comment by daniel-j-h** [comment]
What _exactly_ do you need `osrm-config` to do? Can we precisely constrain the requirements?
Is printing compiler flags on `--cflags` and libs on `--libs` good enough?
Does it have to support both statically linked libraries and shared objects?
What subset of `pkg-config` do we have to implement?

**Comment by BergWerkGIS** [comment]
I think @springmeyer is thinking about something similar to [mapnik-config](https://github.com/mapnik/mapnik/blob/master/utils/mapnik-config/mapnik-config.template.sh).

`osrm-config` would also have the advantage of being cross plattform.
No `pkg-config` on Windows per default.

**Comment by TheMarex** [comment]
> Having an extra dependency on pkg-config is annoying when all node-osrm needs is a few things like library and include paths

I don't see this as a big dependency - `pkg-config` is pretty lightweight itself. We can assume `pkg-config` exists on the platforms we want to support. Windows is somewhat of an oddball here, but we are not running this in production anyway. Having Windows support in our backend only is there to be resilient against compiler specific behavior. We don't really need `node-osrm` packages.

I see setting `PKG_CONFIG_PATH` as easier than support yet another build system layer. I don't think we should move forward here. We might have a documentation hole w.r.t. `PKG_CONFIG_PATH` in `node-osrm` and we should probably run a check and error if `pkg-config libosrm` does return a not-found.

**Comment by BergWerkGIS** [comment]
Dropped Windows support.
https://lists.openstreetmap.org/pipermail/osrm-talk/2016-May/001214.html
