### ISSUE TITLE
osrm-extract fails with XML parsing error on metro extract .osm files

### ISSUE THREAD

**Issue by Reddemonfox** [Project-OSRM/osrm-backend#2035]
demon@demon-Lenovo-Z50-70:~/osrm$ osrm-extract map.osm
[info] Input file: map.osm
[info] Profile: profile.lua
[info] Threads: 4
[info] Using script profile.lua
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-MSG] 1 disks are allocated, total space: 40000 MiB
[warn] XML parsing error at line 1, column 7: not well-formed (invalid token)

**Comment by Reddemonfox** [comment]
i am new to this please help me resolving this, i am trying this on my local machine 
Thank you

**Comment by daniel-j-h** [comment]
Your XML seems to be invalid. I can not help you any further by only looking at that line.

Where did you get the `map.osm` file from? I recommend using

- http://www.geofabrik.de/data/download.html for larger extracts
- https://mapzen.com/data/metro-extracts/ for metro extracts

**Comment by Reddemonfox** [comment]
hi daniel !
i got my map.osm file from metro-extract only, and i've tried 3,4 osm files all of them are showing the same errors,
please would you help me in choosing the file extension type osm file i need to download for ubuntu OS.
and please give me link of any small size map.osm file so that i can check if it is the only problem or not.
Thank you

**Comment by daniel-j-h** [comment]
Did you download a `.pbf` file and save it as `.xml` file by accident?

Can you make sure your `.osm` file looks like this:

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmconvert 0.7T" timestamp="2016-02-27T00:25:02Z">
        ...
```

The following works without problems for me

    $ wget https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf
    $ ./osrm-extract -p ../profiles/car.lua zurich_switzerland.osm.pbf

also with the XML file

    $ wget https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.bz2
    $ ./osrm-extract -p ../profiles/car.lua zurich_switzerland.osm.bz2

or even better use the small Liechtenstein extract from http://download.geofabrik.de/europe/liechtenstein.html.

**Comment by Reddemonfox** [comment]
Thank you very much daniel, it is extracted with your way with some  warnings saying 'Found invalid node reference 4294967295"
 and after that when i try to run command " osrm-prepare zurich_switzerland.osm.pbf" 
it is showing error "
[warn] [exception] osrm input file misses magic number. Check or reprocess the file
"
what does it mean actually and what might be the reason for this.
Thank you in advance

**Comment by danpat** [comment]
@Reddemonfox You need to run two different commands:

`osrm-extract -p ../profiles/car.lua zurich_switzerland.osm.pbf`

then

`osrm-prepare zurich_switzerland.osrm`

Note the different file extensions given to each command.

**Comment by Reddemonfox** [comment]
hi ! @danpat ,
thank you for the help but can you please tell me why am i getting the error i'd mentioned in my previous comment while executing extraction command 
"Found invalid node reference 4294967295"

**Comment by danpat** [comment]
@Reddemonfox it's a warning, it sounds like the OSM/PBF file you're using contains broken ways, usually on the edges.  It will depend on how the small extract you're using was created when it was extracted from the whole planet file.

**Comment by Reddemonfox** [comment]
@danpat  ohhh !!! that make sense,
one more thing the command you mentioned 
osrm-extract -p ../profiles/car.lua zurich_switzerland.osm.pbf
in that command in place of "../profiles/car.lua" i need to write only "profile.lua" because while compiling osrm i didn't get any directory name "profiles" instead there is a file named "profile.lua"

**Comment by danpat** [comment]
@Reddemonfox `osrm-backend/profile.lua` is a symbolic link to `osrm-backend/profiles/car.lua`.  There are `car`, `walk` and `bicycle` profiles, depending on what kind of routing results you want.

It sounds like you've got everything working, I'm going to close this issue.  Please re-open if you think there is a bug here.

**Comment by Reddemonfox** [comment]
Thank you very much, :+1:  i am new to this, so it was a great help fro both of you @daniel-j-h  and @danpat

**Comment by Reddemonfox** [comment]
@daniel-j-h  how can i get the address using url ?? i mean 
http://my_server_ip:5000/nearest?loc=47.379758,8.505128
which port is it? because using this URL i am not getting anything .

**Comment by Reddemonfox** [comment]
{"status_message":"Query string malformed close to position 8","status":400} 
this is the string returned when i call that url with lat long

**Comment by daniel-j-h** [comment]
http://router.project-osrm.org/nearest?loc=52.4224,13.333086

the same should work locally, that is using `localhost:5000`.

(Assuming you cloned and compiled the master or develop branch)

**Comment by Reddemonfox** [comment]
i want to create one reverse geocoding server what should i prefer ? mysql database or xml file for storing data?

**Comment by daniel-j-h** [comment]
Geocoding is not our territory, OSRM does routing. Nearest returns the nearest _street segment_ only.

Take a look at Nominatim, Mapzen's advances in this area or the [Mapbox Geocoding service](https://www.mapbox.com/geocoding/) and its [API](https://www.mapbox.com/developers/api/geocoding/).

**Comment by Reddemonfox** [comment]
so using Nominatim and mapzen i can create a server for reverse geocoding?

**Comment by daniel-j-h** [comment]
Sure.

**Comment by SMaisto** [comment]
I'm trying to setup a OSRM server locally, I followed all the steps in the guide https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM, and I've tried various .pbf maps but still I get the error

{"message":"URL string malformed close to position 8: \"est?lo\"","code":"InvalidUrl"}

Someone could give me a hint to resolve this?

**Comment by Reddemonfox** [comment]
What is the URL you are calling?

**Comment by SMaisto** [comment]
I got the server running with the command

osrm-routed map.osrm

and the URL is

http://127.0.0.1:5000/nearest?loc=40.9723321,14.2116783

**Comment by TheMarex** [comment]
@SMaisto you are using the wrong API version. Use this version: https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

Going to lock the issue now.
