### ISSUE TITLE
Two profiles at the same time

### ISSUE THREAD

**Issue by Worvast** [Project-OSRM/osrm-backend#2044]
Hi, sorry if the question is repeated I have not found anything about it:

Seeing run tutorial i see no instructions about launch a second profile without deleting the previous profile data extracted

I see i can use for run: 

    ./osrm-routed map.osrm -p 5010

for run in other port the second profile, but i only think in different folders for the extracted data because in osrm-routed i not see option for profile.

Does anyone have enabled multiple profiles (example: car and foot) on the same server at the same time or can say me one issue/post/file/folder to see how continue to try it? 

Thank you.

**Comment by daniel-j-h** [comment]
`osrm-extract` is the only binary that takes a Lua profile, so you have to extract multiple times with different profiles (e.g. into multiple directories).

The run `osrm-contract` on these files and ultimately run `osrm-routed`.

**Comment by Worvast** [comment]
ok, thank you very much for the answer now I feel pretty stupid lol

The IP option of osrm-route, what mean specifically?

**Comment by daniel-j-h** [comment]
It's the endpoint for the tcp socket to bind to, listening for connections. The default should be good enough except if you want to bind do a specific interface.

For your use-case you probably want to do something like this

    pushd cardir/ && osrm-routed -p 5000 carextract.osrm 2> car.log &
    pushd bikedir/ && osrm-routed -p 5001 bikeextract.osrm 2> bike.log &

**Comment by TheMarex** [comment]
Closing as solved. :+1:
