### ISSUE TITLE
Tagging shared turn lanes in the middle during turn lanes mapping for navigation.

### ISSUE THREAD

**Issue by abhisheksaikia** [Project-OSRM/osrm-backend#2049]
During turn lanes mapping, our data team at Mapbox are coming across different scenarios such as #2048, and we are unsure how certain tags influence navigation. One such scenario is:

**Shared turn lanes**:

These are the lanes marked with symbol representing both directions at a time.

  ![turn:lanes:both_ways](https://cloud.githubusercontent.com/assets/8401827/12642951/0162ff9c-c5df-11e5-8a14-a41f263ae086.png)

Tag used for such lanes are `turn:lanes:both_ways=*`

At present, we are ignoring adding this tag and also not counting that lane when we tag `lanes=*`. 

Ideally, we are proposing the above scheme of tagging for this scenario:
> `lanes=5`
   `lanes:forward=2`
   `lanes:backward=2`
   `turn:lanes:both_ways=left`

Will this be the best way to tag it for guidance in navigation? The doubt regarding adding `lanes=5` is that the middle lane is not exclusively used for traffic but as shared turn lane for traffic from both directions.

cc @freenerd @MoKob @Andygol @planemad @jothirnadh

**Comment by MoKob** [comment]
I think the format proposed looks consistent with the road.
Is the way to tagging `turn:lanes:both_ways=left/right` accepted in the OSM community? If thats the case, I would agree with the approach.

**Comment by abhisheksaikia** [comment]
@MoKob what will be your take on the number of lanes for this stretch of the road? Will it be `lanes=5` or `lanes=4` considering the fact that the middle lane does not handle any through traffic?

> Is the way to tagging turn:lanes:both_ways=left/right accepted in the OSM community? If thats the case, I would agree with the approach.

@Andygol can you please clarify if the  `turn:lanes:both_ways=*` is an accepted tag in the OSM community?

**Comment by MoKob** [comment]
@abhisheksaikia the setting lanes=5, in combination with forward/backward lanes looks like a good compromise for me.

**Comment by Andygol** [comment]
@MoKob @abhisheksaikia 
> Is the way to tagging `turn:lanes:both_ways=left/right` accepted in the OSM community?

:point_up: This tagging is in the proposal stage - http://wiki.openstreetmap.org/wiki/Proposed_features/Suffix_both_ways

along with `placement` tagging - http://wiki.openstreetmap.org/wiki/Proposed_features/placement

This tags are actively promoted via JOSM `Lanes and Road Attributes` mappaint style - https://josm.openstreetmap.de/wiki/Styles/Lane_and_Road_Attributes

**Comment by MoKob** [comment]
Closing here, since nothing actionable in OSRM-backend and discussion seems stale. Feel free to re-open if further _guidance_ is needed.
