### ISSUE TITLE
url lenght (handle POST data)

### ISSUE THREAD

**Issue by NaWer** [Project-OSRM/osrm-backend#205]
To route via a lot of coordinates, the current API handle only GET request :
http://server:5000/viaroute?loc=lat1,lon1&loc=lat2,lon2&loc=lat3,lon3&loc=lat4,lon4&...

there's limit to the url length in most browser and url libs [1], reached quickly, especially with hint_data
It may be better to use POST in this case.
GET and POST data are generally associative array (url encoded, look like this : loc%5B1%5D=lat1,lng1&loc%5B2%5D=lat2,lng2...)

[1] http://www.boutell.com/newfaq/misc/urllength.html

**Comment by DennisOSRM** [comment]
closing in favor of #1293
