### ISSUE TITLE
Separate Meta Data and Nodes

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2052]
The edge-based nodes contain some meta-data that is only used in guidance (e.g. `name_id`, `travel_mode_forward`, and `travel_mode_backward`).

For further improvements on guidance -- think parts of this road are restricted, mind the road conditions, or similar --, this list might even have to grow.

For every non-compressed geometry, which happens for every intersection along a road, this information is even duplicated.

To reduce the impact of adding additional data and reduce the duplication overhead, I propose to separate this meta-data from the edges.
It would require an additional indirection to lookup the required information but, at the same time, would reduce unnecessary data stored within the edge-based-node.

Whats your take on this?

**Comment by emiltin** [comment]
Sounds like #1342?

**Comment by MoKob** [comment]
It would make it easier to enable it, but I think it goes a step further.

**Comment by MoKob** [comment]
@daniel-j-h btw, this is the ticket I was talking to you about. Do you see a timeframe on when you can get on this?

**Comment by daniel-j-h** [comment]
Does it block v5? If not let's table if for 5.1. I'm still on https://github.com/Project-OSRM/osrm-backend/pull/2088 which blocks v5.

**Comment by MoKob** [comment]
No. Its definitely 5.1, but is required for many features in there. Should be a priority after 5.0

**Comment by TheMarex** [comment]
Problem here is that the data stored in the `EdgeBasedNodes` is currently on disk, which is also the prime reason why its stored with each segment individually.

To make this work the `EdgeBasedNode` and the `EdgeBasedEdges` (or rather `OriginalEdgeData` in memory) would need to use the same de-duplicated index (== no additional memory usage). This would mean in the `EdgeBasedGraph` factory we need a way to de-duplicate data tuples.

We can evaluate this restructuring once it becomes really necessary.

**Comment by MoKob** [comment]
After the amazing results for the RamIndex https://github.com/Project-OSRM/osrm-backend/issues/2472, I've had a look at what we could potentially save.

So for what I can see, `EdgeBasedNode` often shares the following fields:
 * forward_segment_id
 * reverse_segment_id
 * name_id
 * component;
 * travel_mode (forward/backward)

The fileIndex for an extract of California, on a local extract is 420 MB. This is distributed over 12070961 Edge Based Nodes, 2291534 of which offer a unique set of these entries above.

Using the split, we would need an additional ID in EdgeBasedNode. This would result in 276MB in EdgeBasedNodes and an additional 40 MB in de-duplicated data..
A total result of 330MB, reducing the fileIndex (currently one of our largest files) approximately 25%.

**Comment by deniskoronchik** [comment]
If OSRM doesn't make node based node, that overlap two  or more way segments with different names, then this very good idea to store name_id's for each node instead of edge, because number of nodes usually less then number of non-shortcut edges. Have you any progress on it?
