### ISSUE TITLE
Km's travelled per country

### ISSUE THREAD

**Issue by frankvandenbergh** [Project-OSRM/osrm-backend#2053]
Hi,
I want to calculate the number of km's driven per country. My idea is to add the country name to the node's name in the profile and parse the result instruction set by my app.

Is this a good approach and if so, please tell me how to get the country's node.

**Comment by emiltin** [comment]
It's a bit of a hack, but you can encode extra info into the street names. eg. 'Vesterbrogade {"country":"Denmark"}'. You can then extract the info in the front-end.

You can also do spatial analysis on the route geometry, using eg. PostGIS.

**Comment by danpat** [comment]
@frankvandenbergh @emiltin 's suggestions are spot on.  This kind of analysis is outside the scope of OSRM.

One geospatial analysis approach would be to obtain polygons of country borders, then clip the route line with each candidate country, then measuring the lengths of each clipped geometry.  This isn't something that's a natural extension to OSRM, but is a fairly standard geospatial task.
