### ISSUE TITLE
Simplify osrm-extract file output

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2055]
Edge-based-graph expansion was moved into `osrm-extract` by simply transposing the code from `osrm-prepare`.

The code is inefficient, in that it writes the node-based graph to disk, then re-reads it, and performs edge expansion.  Now that all these steps happen inside `osrm-extract`, there are some steps that can just stay in memory, rather than going via intermediate files.

This would save some IO, and remove a few of the output files.

The code that was moved from `osrm-prepare` starts here: https://github.com/Project-OSRM/osrm-backend/blob/54ee76bcefd392ad0636517c6b3a043b47a33c39/src/extractor/extractor.cpp#L253

**Comment by daniel-j-h** [comment]
Can we table this for 5.1? I see no immediate priority in pushing this forward in the next days.

Let's ship v5.

**Comment by TheMarex** [comment]
Alright, my main goal for `5.1` is to redo our storage layer anyway.
