### ISSUE TITLE
[travis] ccache being used when no benefit

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/osrm-backend#2057]
Since https://github.com/Project-OSRM/osrm-backend/commit/5379a555db696f5a9f17deb75285d12c003c0247 the osrm-backend cmake build automatically uses `ccache` if found. My understanding is that there is a measurable performance hit to the first-run build with ccache (when creating caches for the first time). Because `ccache` is installed by default on travis, the build on linux is automatically using ccache.

Possible fixes:

  - Apt-get uninstall ccache on linux machines to avoid its use
  - Add ability to disable ccache auto-use in osrm-backend
  - Port the .travis.yml to use `sudo:false` so that caching can be enabled (and major benefit from using ccache should be seen)
  - Roll our own caching.

**Comment by TheMarex** [comment]
Actually we don't really require sudo (well we install our self-compiled binaries for the example, but we could also do that in a user-defined path), its just that Travis not yet has a separate infrastructure for Ubuntu `14.04` builds. We can probably just hold of on this until travis enables `sudo:false` for Ubuntu `14.04`.

**Comment by daniel-j-h** [comment]
The C++14 branch already has a [CMake option for ccache](https://github.com/Project-OSRM/osrm-backend/blob/c++14/CMakeLists.txt#L32) and the corresponding node-osrm pull request disables ccache on Travis (for other reasons though).

The initial use-case was caching the ccache directory on Travis for faster builds, this requires `sudo:false` for `14.04` as mentioned above.

**Comment by daniel-j-h** [comment]
Cherry-picked https://github.com/Project-OSRM/osrm-backend/commit/d19e953e44be90108e2ab76ac1fe467e7abeb850 closing here.
