### ISSUE TITLE
Wrong version in the osrm-routed log

### ISSUE THREAD

**Issue by maximd1** [Project-OSRM/osrm-backend#2060]
Just a small remark - I have 4.9.1 build, but routed's log still contains previous version:

`[info] starting up engines, v4.9.0`

**Comment by daniel-j-h** [comment]
Thanks for reporting. I think this is already the second time we forgot about it. @TheMarex any ideas here? What about a `make_release` script that updates the version, sets a tag, does some sanity checks / linting ...?

**Comment by TheMarex** [comment]
@daniel-j-h yeah a release script would make sense.
