### ISSUE TITLE
Debug tiles need turn penalty data

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2066]
Currently, the debugging tiles only expose the node-based-edge weights.

However, when we route, we use the edge-based graph, and the weights on the edge-based graph are the sum of the node-based-edge weights, *plus* some additional turn/stop/u-turn costs.

In the previous iteration of graph debugging, when we were printing out GeoJSON, we dumped turn data here:

https://github.com/Project-OSRM/osrm-backend/blob/d0644bace9e121963dce87d935e1e2555842ef7a/src/extractor/edge_based_graph_factory.cpp#L470

https://github.com/Project-OSRM/osrm-backend/blob/d0644bace9e121963dce87d935e1e2555842ef7a/src/extractor/edge_based_graph_factory.cpp#L459

(and it looks like we were missing output for this spot:  https://github.com/Project-OSRM/osrm-backend/blob/d0644bace9e121963dce87d935e1e2555842ef7a/src/extractor/edge_based_graph_factory.cpp#L473, although the code for this *did* exist at one point:  https://github.com/Project-OSRM/osrm-backend/blob/d0644bace9e121963dce87d935e1e2555842ef7a/include/util/debug_geometry.hpp#L199).

But now, we can't see these numbers when debugging.

@daniel-j-h Can you take a look and see if you can expose vector tile `Point` elements with some of these properties?

Brain dump of thoughts:

   1. Getting the turn angles is going to be difficult - it's going to require walking the graph, getting packed geometries and finding the first/last segments for each node-based-edge, then calculating the angle.
   2. Turn weights are also going to need to be calculated - add up the weights of the node-based-edge, then subtract from the edge-edge.

I suspect u-turn and stop-light penalties are going to be impossible to expose individually - best we can do is identify the "turn" and the "penalty" that goes along with it.

Ideally, the output we're going for could be rendered something like this:

https://api.mapbox.com/v4/danpat.f040b156/page.html?access_token=pk.eyJ1IjoiZGFucGF0IiwiYSI6ImI0WThCVWMifQ.BP_j7Kiv5SNL-p-kTfXNxg#19/37.77515/-122.41548

(This map is missing traffic-light penalties, which apply to straight-through intersections).

**Comment by TheMarex** [comment]
How urgent is this? Can it wait until `5.1.0`?
