### ISSUE TITLE
Add debug tiles to docs

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2071]
Debug tiles should be captured in the docs. https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

/cc @karenzshea @danpat

**Comment by danpat** [comment]
Done.

**Comment by willwhite** [comment]
Link?

**Comment by willwhite** [comment]
Ah found it. https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#service-tile
