### ISSUE TITLE
Disable alternatives when core factor is < 1

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2072]
We should not attempt to generate an an alternative route when core factor is < 1 because it will be extremely slow. We should ignore the user's request for an alternative and only return one route.

/cc @TheMarex

**Comment by daniel-j-h** [comment]
The core factor is only used during contraction. That is, later stages in the pipeline do not know about this. 

Can't this be easily solved on the call site? That is user contracting with a core factor < 1 are also responsible for disallowing alternative routes.

**Comment by willwhite** [comment]
> later stages in the pipeline do not know about this 

@TheMarex indicated that this information was already available.

> user contracting with a core factor < 1 are also responsible for disallowing alternative routes

We can implement this upstream, but it feels like a common use case, and it basically amounts to the same thing - some metadata that contains what core factor was used to generate the dataset.

Could osrm expose this (and other) metadata about the dataset that's loaded into memory?

**Comment by TheMarex** [comment]
Yeah we have the information to actually handle this since we also need to be able to dynamically disable/enable core based searches.
