### ISSUE TITLE
Phonemes

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2079]
For text to speech systems, we should start thinking about phonemes for road names.

Next to the question of a good fallback -- currently its only a [proposed feature](http://wiki.openstreetmap.org/wiki/Proposed_features/Phonetics) in OSM, next to  some discussion on a `pronunciation` tag -- we should discuss how to enable it in OSRM.

A possible way of solving this would be to make our name-hash aware of phonetics and keep a phonetics hash with the same ID.

This would require:

 - [x] update name hash to check for phonetics
 - [x] store phonetics next to the names
 - [x] report phonetics in output
       - [x] add tag into json response
       - [x] augment instructions to also report phonetic names

Problematic here: how are we handling country level support/different pronunciations in different languages?

/cc @freenerd @TheMarex

**Comment by emiltin** [comment]
Could this be handled by #1342?

**Comment by TheMarex** [comment]
This is handled by https://github.com/Project-OSRM/osrm-backend/pull/2465

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/pull/2465.
