### ISSUE TITLE
simplified is a bit too simplistic

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2083]
Splitting out from https://github.com/Project-OSRM/osrm-backend/pull/1935#issuecomment-188886340 for proper tracking/discussion.

----

<img width="358" alt="screen shot 2016-02-25 at 16 27 05" src="https://cloud.githubusercontent.com/assets/25713/13327906/287f487e-dbec-11e5-8a4a-558e1a3fdccb.png">

@TheMarex:
- Code makes wrong assumptions
- Needs to use same algorithm as https://github.com/mapbox/geo-viewport/blob/master/index.js

**Comment by TheMarex** [comment]
This is addressed by the reference commit.
