### ISSUE TITLE
Как построить комбинированный маршрут?

### ISSUE THREAD

**Issue by denny123** [Project-OSRM/osrm-backend#2094]
Как построить комбинированный маршрут в OSRM(например пешком до автодороги и далее на машине)?

**Comment by kostadin24** [comment]
1. Сделай маршрут для машине.
2. Сделай маршрут с началной позиции до начало маршрут для машина.
3. Тоже самое для финал.

**Comment by denny123** [comment]
Этот вариант я хотел обойти(надо сервер загружать несколькими запросами), рассматриваю варианты, может еще что есть или есть готовые lua профайлы.

**Comment by kostadin24** [comment]
Если все ето на одно машине сделат разница будет не болше чем несколко милисекунд. Все таки дистанция пешком не будет настол велика.

**Comment by kostadin24** [comment]
Я ето деляю несколко лет уже. Имею 4 маршрута на автобусе. Для каждой делаю 2 заказа пешком, что бьи не направлял людей через рекой или долгих заграждениях. И все не стои мне болше чем 0.5 секунд.

**Comment by kostadin24** [comment]
МЕнят транспорт ето уже MultiModal routing алгоритм. OSRM ето не делает. Ест другие open source проектьи. Там все наладено. Даже реалновременное инфо об тяжелой трафик .

**Comment by denny123** [comment]
Ясно, рассмотрю вариант через собственный profile.lua(если язык потяну), в случае неудачи тогда  уже этим вариантом воспользуюсь.

**Comment by denny123** [comment]
Еще вопрос возник. Как выбрать оптимальный маршрут автобуса(или нескольких) и как вообще прописать построение по маршрутам автобуса? Неужели тоже путём нескольких запросов к серверу?
