### ISSUE TITLE
Print host and port on which osrm-routed listen

### ISSUE THREAD

**Issue by frodrigo** [Project-OSRM/osrm-backend#2097]
After osrm-routed boostrap add host and port:

Replace:
```
[info] running and waiting for requests
```

By:
```
[info] running and waiting for requests on http://0.0.0.0:5000
```

Explanation: system can choose an available port by using the value '0' like this
```
./build/osrm-routed --port 0 andorra-latest.osrm
```

**Comment by daniel-j-h** [comment]
The following is already reported in debug mode:
```
[info] Threads: 8
[info] IP address: 0.0.0.0
[info] IP port: 5001
```
Changing to always showing it.

**Comment by frodrigo** [comment]
Thank you for your quick fix. But there is an issue with port. Since the requested value is 0, the real port is an other one. Your fix still print 0.

**Comment by daniel-j-h** [comment]
You're right. The way to get this from the API seems to be via http://www.boost.org/doc/libs/1_60_0/doc/html/boost_asio/reference/ip__basic_endpoint/port.html in `server.hpp` but I will have to test if it returns zero, too.

**Comment by daniel-j-h** [comment]
Both ASIO's endpoint `.port()` member function as well as piping the endpoint into an `ostream`shows the port as `0` (and the address as `0.0.0.0` for the record). I'm leaving this ticket open as unresolved.

**Comment by daniel-j-h** [comment]
Eventually found a way

    [info] Listening on: 0.0.0.0:58249
