### ISSUE TITLE
Table service does not conform to v5 API `TooBig` error code for config limits

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2100]
Per the v5 API spec config limit violations return code `TooBig`:
https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

Table is the only service not returning `TooBig` in this case:
https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/src/engine/plugins/table.cpp#L52

**Comment by TheMarex** [comment]
This landed. :tada:
