### ISSUE TITLE
Error build develop version!

### ISSUE THREAD

**Issue by denny123** [Project-OSRM/osrm-backend#2103]
cmake return error like " Building on a 32 bit system is unsupported" on Ubuntu.

**Comment by daniel-j-h** [comment]
Yes, building on a 32bit system is not supported in any way. What does `uname -m` or `arch` say?

**Comment by denny123** [comment]
uname -m 
i686

**Comment by daniel-j-h** [comment]
Yes, you're on a 32bit Ubuntu. We don't support building on 32bit platforms and you will probably run into some issues regarding a different data models (fundamental type widths, some static assertions might trigger) and other assumptions the code makes.

(Note: you can rip out the check in `CMakeLists.txt` and see how far you can go with that, but it's unsupported for a reason)
