### ISSUE TITLE
How use postgis.lua?

### ISSUE THREAD

**Issue by denny123** [Project-OSRM/osrm-backend#2104]
I dont undestand how use postgis.lua? May be example? What needed for this?

**Comment by daniel-j-h** [comment]
You run `osrm-extract` with a profile. In this profile you can make arbitrary Lua calls, e.g. against a PostGIS database. For documentation on profiles take a look e.g. at `profiles/car.lua` and see:

https://github.com/Project-OSRM/osrm-backend/wiki/Profiles

What do you want to accomplish? What did you try so far, and what are specific problems?

**Comment by emiltin** [comment]
See also this example:
https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/examples/postgis.lua

**Comment by denny123** [comment]
I try 'osrm-extract postgis.lua' and returned help only, i think needed *.osm or *.pbf or other file, but what the FILE if i want import data from postgis? And where connection properties(ip,port)?

**Comment by daniel-j-h** [comment]
For running osrm, see the documentation at

https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

In your profile you then setup a connection to a PostGIS server matching e.g. way ids.

Just for clarification, you _don't_ need a PostGIS setup for running osrm on its own, it's just if you want to bring in additional data. Give the following a try: download a pbf extract from

http://download.geofabrik.de

and run osrm on it as described in the documentation I linked above.

**Comment by denny123** [comment]
I have running OSRM, but data from *.osm files and i want data from postgis(for better update). I dont need pbf/osm files, i have data in postgis exported with osm2pgsql from *.osm. Can i do it and may be example?

**Comment by daniel-j-h** [comment]
Wait, if you have your extract already as `.osm` file you don't need the extra indirection through PostGIS. Just feed it to osrm instead of the `.pbf` file.

**Comment by denny123** [comment]
Yes, but i have 3 osrm-routed(car, bicycle and foot) from 1 *.osm file, and for update data better postgis.

**Comment by daniel-j-h** [comment]
Importing extracts directly from PostGIS is not supported. You can import from .osm/.pbf and use PostGIS by means of a profile for bringing in extra metadata.

**Comment by denny123** [comment]
So, postgis used and needed ONLY for metadata?

**Comment by daniel-j-h** [comment]
Correct. The profiles only provide callbacks that osrm runs for every node/way in your extract.
Use for example `osmosis` to read from PostGIS and write a .osm file.

**Comment by denny123** [comment]
Ok, i undestand, thnx.
