### ISSUE TITLE
Nearest service does not conform to v5 API `InvalidOptions` error code for no coordinates

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2108]
Per the v5 API spec precondition violations return code `InvalidOptions`:
https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

Nearest returns `TooBig` in case no coordinates are provided:
https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/src/engine/plugins/nearest.cpp#L29-L32

**Comment by TheMarex** [comment]
This landed :tada:
