### ISSUE TITLE
Move Guidance Decisions into Profile

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2113]
The new static turn instructions include a few hard-coded decisions that need to be moved out into the profile.
- [x] [Fork discovery](https://github.com/Project-OSRM/osrm-backend/blob/features/guidance-features-5-0/include/extractor/guidance/toolkit.hpp#L391-L407): Forks can only happen if one road isn't clearly superior to the other. The current priority solution is very tentative. We should move the discovery function to the profiles in the profile overhaul to make sure these can be set for different preferences
- [x] [Road Classification and Ramp Discovery](https://github.com/Project-OSRM/osrm-backend/blob/features/guidance-features-5-0/include/extractor/guidance/classification_data.hpp#L21-L48) Most road classifications can have impact on how to treat a road. We treat motorways and ramps differently from other types, although only trunk and motorway ramps are treated as actual ramps. Both the road classification and what to treat as a ramp should be moved to the profile as well

We could also discuss in how far we want to allow configuration of [internal constants](https://github.com/Project-OSRM/osrm-backend/blob/features/guidance-features-5-0/include/extractor/guidance/classification_data.hpp#L21-L48).
- [ ] internal constants
- [ ] further hard-coded decisions?

For Bikes/and or Walking we have to consider further improvements:
- [ ] allow different classifications per direction (e.g. classification for pushing over cycling)

**Comment by emiltin** [comment]
Good idea. Fore example bike infrastructure can also include forks and merging.

**Comment by MoKob** [comment]
A first step is implemented in https://github.com/Project-OSRM/osrm-backend/pull/2586. It allows to set a fixed number of road classes to experiment with desired behaviour.
We can define link-classes, what is seen as motorway-like, roads that offer only connectivity.

**Comment by daniel-j-h** [comment]
- [ ] Threshold for [Staggered Intersections](https://github.com/Project-OSRM/osrm-backend/pull/2738)
- [ ] Threshold for [Lane Anticipation](https://github.com/Project-OSRM/osrm-backend/blob/7f71f0ed120e11ada57496da16e3f3c17f80ee13/include/engine/guidance/lane_processing.hpp#L23)

**Comment by oxidase** [comment]
Copied from #4075 
> the current behaviour does not work for foot and bike routing. even for cars i'm not sure i think the current behaviour makes sense, e.g. in the example no matter what exit you take, you get 'take 1st exit':
http://map.project-osrm.org/?z=19&center=55.739332%2C12.494454&loc=55.739479%2C12.494186&loc=55.739174%2C12.494679&hl=en&alt=0

/cc @emiltin

**Comment by emiltin** [comment]
maybe also the ability to turn off guidance altogether for modes like walking?

**Comment by TheMarex** [comment]
This issue has no clear actionable items. If we need constants to be configurable by the profile, we need to come up with a use case and open an own issue.
I moved the roundabout counting issue to [here](https://github.com/Project-OSRM/osrm-backend/issues/4716), but I don't think we can fix it by exposing more stuff in the profile.
