### ISSUE TITLE
Division By Zero in Turn Analysis

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2117]
@MoKob

    src/extractor/guidance/turn_analysis.cpp:870:63: runtime error: division by zero

https://github.com/Project-OSRM/osrm-backend/blob/a558e5de4f34eadda73827152f04dfd894eedab8/src/extractor/guidance/turn_analysis.cpp#L868-L872

**Comment by MoKob** [comment]
should be solved with: https://github.com/Project-OSRM/osrm-backend/pull/2080/commits/b9cea7454d65537a11a6ecbd805c683f767dd3bb
