### ISSUE TITLE
osrm-datastore killed while loading new dataset

### ISSUE THREAD

**Issue by gene7ic** [Project-OSRM/osrm-backend#2123]
Hi, I got a problem with reloading a new dataset with osrm-datastore.

1.) Load the old planet-extract:
~/osrm-backend/build$ ./osrm-datastore ../../osrm-map/201609_planet-latest.osrm
[info] load names from: "../../osrm-map/201609_planet-latest.osrm.names"
[info] name offsets size: 385443
[info] allocating shared memory of 33523669241 bytes
[info] all data loaded

2.) Start the engine:
~/osrm-backend/build$ ./osrm-routed -s 1
[info] starting up engines, v4.9.0
[info] set checksum: 1249779356
[info] number of geometries: 578533637
[info] loaded plugin: table
[info] loaded plugin: hello
[info] loaded plugin: nearest
[info] loaded plugin: match
[info] loaded plugin: timestamp
[info] loaded plugin: viaroute
[info] loaded plugin: trip
[info] http 1.1 compression handled by zlib version 1.2.8
[info] running and waiting for requests

Requests beeing answered correctly.

3.) Load the old planet-extract:
~/osrm-backend/build$ ./osrm-datastore ../../osrm-map/201611_planet-latest.osrm
[info] load names from: "../../osrm-map/201611_planet-latest.osrm.names"
[info] name offsets size: 386377
[info] allocating shared memory of 33644175369 bytes
Killed

Syslog:
[  519.105367] Out of memory: Kill process 2181 (osrm-datastore) score 145 or sacrifice child
[  519.105839] Killed process 2181 (osrm-datastore) total-vm:32883796kB, anon-rss:572kB, file-rss:15965240kB

The machine is running with 48G RAM and 60G of SWAP:
~# free -m
             total       used       free     shared    buffers     cached
Mem:         48305      48020        284      47553          0      47556
-/+ buffers/cache:        464      47840
Swap:        59077         82      58994

When I start step 3.) and monitor the free command, the SWAP-Space will not be used. 
How much RAM do I need? 33523669241 + 33644175369  Bytes?
Why isn't the SWAP used and cleaned up after an successful import of the new osrm-datastore?

**Comment by daniel-j-h** [comment]
`osrm-datastore` [locks the virtual address space to RAM](https://github.com/Project-OSRM/osrm-backend/blob/develop/src/storage/storage.cpp#L85-L92) in order to avoid swapping (as hitting the disk would be fatal for latency). If you don't care about that, feel free to comment out the lines and see if that helps. If not, provide more RAM.
