### ISSUE TITLE
Demo server switchover to OSRM 5.0 and new HTTP API

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#2126]
For a while we've been working on OSRM 5.0.0, which will bring big changes to the osrm-routed HTTP API. You can see the new [HTTP API here](https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api). This ticket is to keep you updated about when `https://router.project-osrm.org` will be switched over to the new API:

- We will announce the exact date and time of the switchover 7 days in advance in this issue and on the [osrm mailing list](https://lists.openstreetmap.org/listinfo/osrm-talk)
- We will release a _release candidate_ before doing the switchover
- We will not release the final version of OSRM 5.0 before doing the switchover
- If you want to test the new API now already, set it up yourself from this branch https://github.com/Project-OSRM/osrm-backend/pull/1935
- We will not provide the old and new API at the same time, but do a hard switchover of the demo server
- Drop a comment on this issue to be notified of changes and/or give us input

Downstream projects with update tickets:

- openstreetmap.org https://github.com/openstreetmap/openstreetmap-website/issues/1161
- Leaftlet Routing Machine https://github.com/perliedman/leaflet-routing-machine/pull/217
- OsmBonusPack https://github.com/MKergall/osmbonuspack/issues/212
- more to be added ...

**Comment by MKergall** [comment]
"We will not provide the old and new API at the same time, but do a hard switchover of the demo server"
=> On mobile apps (like the apps using OsmBonusPack lib), this will imply a service failure, until the user upgrades his app. No way to provide a transition period with both APIs?

**Comment by freenerd** [comment]
@MKergall providing both APIs at the same time is a big engineering effort and requires us to use double the amount of servers we use to provide the API. Getting out the new server API at all is already a huge project, providing both APIs at the same time is just not feasible for us.

I understand that this will break native OsmBonusPack users, but the best option forward will be to upgrade them to the new API as fast as possible.

**Comment by MKergall** [comment]
I understand. 

In the "New Server api page", could you provide responses Examples? 
For instance to the Request Example: http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false

I have a doubt about the value of "code" string when success: is it "Ok", or "ok" ? (as both are mentioned in the wiki page).

**Comment by TheMarex** [comment]
@MKergall yes we caught that a little late _after_ we did the RC1. For some reason it was not correctly capitalized. RC2 will indeed feature `Ok`.

**Comment by MKergall** [comment]
In the previous API, the road name was provided in route_instructions[1], allowing to build textual instructions like: "Turn left on Mozart Avenue". 

This road name disapeared in V5?

**Comment by daniel-j-h** [comment]
Take a look at

https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#routestep
> `name`: The name of the way along which travel proceeds.

and

https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#stepmaneuver
> `new name`: The road name changes (after a mandatory turn)

**Comment by MKergall** [comment]
Thanks Daniel!

**Comment by freenerd** [comment]
We reverted my position on running v4 and v5 simulatiously.

We have now set up the old v4 and new v5 server side-by-side on `https://router.project-osrm.org`.

You can use the new URL scheme right away, e.g. http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=full&steps=true

v5 is potentially still buggy, it runs the latest `develop` branch.

We have not yet set a policy on the deprecation of v4, we'll post news on that once we know more.

**Comment by MKergall** [comment]
Very good news! This will be really helpful on our side to validate the new client code - and maybe to raise feedback to OSRM team.

**Comment by gmiskos** [comment]
I have install v4 months ago in a LTS 14.04 Ubuntu server. How can i upgrade to v5 ?

**Comment by danpat** [comment]
@gmiskos The process is basically the same - get the code, compile it, process the data files.

You will need to start from scratch - the data files are not compatible between releases.

**Comment by freenerd** [comment]
As @TheMarex posted on the mailinglist, this Friday we will shut down the demoserver for 4.9 for good https://lists.openstreetmap.org/pipermail/osrm-talk/2016-August/001275.html

**Comment by freenerd** [comment]
Even though way later than actually planned, we have just switched off version 4 of the API and it's version 5 only now.
