### ISSUE TITLE
Incorrect results in trip when changing order of viapoints in request. Start equal Finish

### ISSUE THREAD

**Issue by Ganipolsky** [Project-OSRM/osrm-backend#2129]
Hi!
http://router.project-osrm.org/trip?instructions=false&loc=55.574920,37.655074&loc=55.755170,37.831960&loc=55.815700,37.811570&loc=55.789710,37.768870&loc=55.815690,37.732320&loc=55.760180,37.695580&loc=55.818840,37.752160&loc=55.750860,37.720820&loc=55.574920,37.655074
Result 
[**8**,7,5,3,4,6,2,1,**0**],"found_alternative":false,"route_summary":{"total_distance":**91060**,"total_time":5401
excellent
_The same points in a different order_
http://router.project-osrm.org/trip?instructions=false&loc=55.574920,37.655074&loc=55.789710,37.768870&loc=55.760180,37.695580&loc=55.818840,37.752160&loc=55.750860,37.720820&loc=55.815700,37.811570&loc=55.815690,37.732320&loc=55.755170,37.831960&loc=55.574920,37.655074
Result
[**8**,4,2,1,6,5,7,0,**3**],"found_alternative":false,"route_summary":{"total_distance":**172542**,"total_time":9211

Why last point 3? I think that last point always must be 0 if first point 8

**Comment by jcoupey** [comment]
You're not actually getting an **incorrect** result, rather a **different** solution.

A different ordering of the locations raising different solutions - though surprising - is highly dependant on the way the solving heuristic operates...

As to the fact that you get a very sub-optimal solution in the second case (same location not visited in a row), this is probably only because your use-case triggers a bias in the solving heuristic.

**Comment by Ganipolsky** [comment]
Ok! How change parameters in request to have solution than star=start point and finish = finish point

**Comment by jcoupey** [comment]
There is no need for you to repeat the first location at the end of the request in order to get a round trip.

When the permutation is `[4,3,1,2,0]`, all costs should include "closing" the round trip with the 0->4 route.

**Comment by Ganipolsky** [comment]
Ok.
I test request 
1. start point, other points
2. other points,start point
More appropriate solutions were in the second case. But not always the border was start point

**Comment by jcoupey** [comment]
As the solution is a round trip anyway, which location is the "start" is not really relevant if you just care about the ordering, e.g. `[4,3,1,2,0]` and `[2,0,4,3,1]` are actually the same solution. Then just use `[0,4,3,1,2]` in case you wish to start at location 0.

**Comment by Ganipolsky** [comment]
Thank you, you're right

**Comment by Ganipolsky** [comment]
For 12 point 
http://router.project-osrm.org/trip?instructions=false&geometry=false&loc=55.574920,37.655074&loc=55.744380,37.499190&loc=55.800220,37.543990&loc=55.784000,37.560021&loc=55.833198,37.497207&loc=55.840699,37.487208&loc=55.855594,37.478292&loc=55.865270,37.437910&loc=55.858200,37.426900&loc=55.809860,37.461470&loc=55.806611,37.466557&loc=55.789470,37.478830
 Result
permutation":[1,3,2,11,10,9,4,7,8,0]
Absent point 5 and 6

**Comment by jcoupey** [comment]
This is another problem altogether, maybe you should open a dedicated issue.

**Comment by Ganipolsky** [comment]
Ok
