### ISSUE TITLE
Drop per-file paths for osrm-extract/contract/routed

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2130]
Currently you can specify the path for each input file separately for each of those utilities, leading to enormous boost::program_option definitions. In practice, nobody uses that but only uses the derived names from the `path/to/file.osrm`. We should drop the per-file options to simplify our code dramatically.

/cc @daniel-j-h @danpat @MoKob

**Comment by daniel-j-h** [comment]
For the record, I did this already for the example in https://github.com/Project-OSRM/osrm-backend/issues/2030 and users are lovin' it *.

\* _and by users I mean I quite liked it in my libosrm using sideproject_

**Comment by TheMarex** [comment]
This landed. :tada:
