### ISSUE TITLE
Route service v5 spec violations / ambiguities revealed in my unit tests

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2134]
Here's the [Route test suite as of ddea7934e4](https://github.com/Project-OSRM/osrm-backend/blob/ddea7934e41941cc4cf7002d3fb023eb790bed64/unit_tests/library/route.cpp#L16) for testing a Route call with three times the same coordinate. Please either prove my assumptions wrong and then update and / or clarify the [v5 spec](https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api).

##### alternatives=true

```
unit_tests/library/route.cpp(61): error: in "route/test_route_same_coordinates": check routes.size() > 1 has failed
```

[Test](https://github.com/Project-OSRM/osrm-backend/blob/ddea7934e41941cc4cf7002d3fb023eb790bed64/unit_tests/library/route.cpp#L58-L61)

`alternative=true` by default and the v5 spec says
> Return an alternative route

is an alternative optional? If so clarify.

##### Durations != 0

route duration:

```
unit_tests/library/route.cpp(71): error: in "route/test_route_same_coordinates": check duration == 0 has failed [16.600000000000001 != 0]
```

[Test](https://github.com/Project-OSRM/osrm-backend/blob/ddea7934e41941cc4cf7002d3fb023eb790bed64/unit_tests/library/route.cpp#L70-L71)

leg duration:

```
unit_tests/library/route.cpp(88): error: in "route/test_route_same_coordinates": check duration == 0 has failed [8.3000000000000007 != 0]
```

[Test](https://github.com/Project-OSRM/osrm-backend/blob/ddea7934e41941cc4cf7002d3fb023eb790bed64/unit_tests/library/route.cpp#L87-L88)

##### Geometry empty

```
unit_tests/library/route.cpp(110): error: in "route/test_route_same_coordinates": check !geometry.empty() has failed
```

[Test](https://github.com/Project-OSRM/osrm-backend/blob/ddea7934e41941cc4cf7002d3fb023eb790bed64/unit_tests/library/route.cpp#L108-L110)

Please clarify.

**Comment by MoKob** [comment]
@daniel-j-h alternative is always optional, since it can never be guaranteed.

a -- b does only offer a single route, no matter how many alternatives you request.

**Comment by daniel-j-h** [comment]
Great, please clarify this in the v5 spec.

**Comment by MoKob** [comment]
I've added a note about that in https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

**Comment by TheMarex** [comment]
> Durations != 0 on same coordinate

this is definitely a bug. Maybe wrong offsets.

> Geometry empty

This should also not happen, it should always be at least one coordinate.

**Comment by daniel-j-h** [comment]
Issues seem to be fixed as https://github.com/Project-OSRM/osrm-backend/pull/2229 passes all unit tests.
