### ISSUE TITLE
Cucumber OOM

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2136]
Currently the cucumber-js tests https://github.com/Project-OSRM/osrm-backend/pull/2084 seem to use an absurd amount of memory.

I'm trying to capture the current knowledge here:
- We are running on node v4.4
- It OOMs only on OSX boxes which have 3 GB of RAM
- Running it locally we get waring amounts of resident memory 
- From running the test it seems there is a build-up phase of about 10 seconds were most of the memory is allocated. After that the memory usage remain about the same.
- A heapdump that I did mid-process claims that 43% of nodes heap memory is used for closures

Todo:

- use https://github.com/bnoordhuis/node-heapdump to get multiple snapshots of the data
- drill down on where the memory is accumulated

**Comment by miccolis** [comment]
Updated issue title, as this isn't a osx issue, and we've got this down to a single failure; `COMPILER='clang++-3.8' BUILD_TYPE='Debug' RUN_CLANG_FORMAT=ON`

**Comment by TheMarex** [comment]
This was fixed by https://github.com/Project-OSRM/osrm-backend/pull/2084/commits/06951ca5879f33fc3e03d0eaec2e352108b2125c

**Comment by daniel-j-h** [comment]
Neither Github can find the commit you linked to nor can I locally

> fatal: bad object 06951ca5879f33fc3e03d0eaec2e352108b2125c

What was the reason here and how did we fix it?
I saw a comment about some checksume node module?
