### ISSUE TITLE
Upgrade mapbox/variant release to v1.1.0 (currently on release from April 2015)

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2140]
Right in time for v5 mapbox/variant made a second release after the first one happening in April 2015.

We should update asap and see if things break and then incorporate into the v5 release.

See: `scripts/upodate_dependencies.sh`

https://github.com/mapbox/variant/releases/tag/v1.1.0

Note: this is causing some troubles https://github.com/Project-OSRM/osrm-backend/pull/2010 otherwise I would do the switch away from mapbox/variant immediately.

**Comment by TheMarex** [comment]
Fixed.
