### ISSUE TITLE
Unit tests for v5

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2141]
Backlog after #2088 merge:

- [ ] guidance assembly should be tested
  - [ ] assemble_overview
  - [ ] assemble_geometry
  - [ ] assemble_steps
  - [ ] assemble_route
  - [ ] assemble_legs
- [x] typed services need to be tested
  - [x] `osrm.Route()`
  - [x] `osrm.Match()`
  - [x] `osrm.Table()`
  - [x] `osrm.Nearest()`
  - [x] `osrm.Trip()`
  - [x] `osrm.Tile()`
- [x] `parameter_parser.cpp` The current unit tests don't test all parameter types

/cc @daniel-j-h

**Comment by daniel-j-h** [comment]
For the record:

Work on Table happening here https://github.com/Project-OSRM/osrm-backend/pull/2254.
Work on Trip happening here https://github.com/Project-OSRM/osrm-backend/pull/2246.
Work on Tile happening here https://github.com/Project-OSRM/osrm-backend/issues/2198.

**Comment by TheMarex** [comment]
This has landed. We should have a look at the coverage to extend this.
