### ISSUE TITLE
Low driving speed guessed for maxspeed=none

### ISSUE THREAD

**Issue by utack** [Project-OSRM/osrm-backend#2145]
Your debug map confirmed the suspicion I had about [this route](https://www.openstreetmap.org/directions?engine=osrm_car&route=49.50363%2C11.29023%3B49.47557%2C11.16616#map=13/49.4897/11.2282)
The highway is avoided because the speeds on it are estimated far too low
[Here](http://map.project-osrm.org/debug/#13.6/49.4841/11.2519) you can see that [maxspeed=none on this part](https://www.openstreetmap.org/way/248868540#map=14/49.4816/11.2636) results in a far underestimed real speed of 83km/h and [maxspeed=120 on this part](https://www.openstreetmap.org/way/308241043) results in a bit more realistic speed of 107km/h (still a bit low, but the difference between the two is what really stands out)
Seems like [this rule](https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/car.lua#L121) is not really working

**Comment by TheMarex** [comment]
Yes you are right, this should not fall back to motorway defaults as it apparently does. Currently we don't seem to support `maxspeed=none` at all. The `source:maxspeed=signals` seems curious? Shouldn't that either be `de:motorway` or `sign`?

**Comment by utack** [comment]
Could you consider this as 5.0 milestone?
You probably have all sorts of internal restructuring going on, but this is a user facing bug that can reduce the quality of the calculated routes significantly.
