### ISSUE TITLE
Round float values in JSON response

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2146]
API responses on v5 contain values like this:

`{"bearing_after":164.80370777858784,"bearing_before":153.46737476365607}`
`"distance":639.7530175504655`

Those values are way too precise, and increase the API response size unnecessarily.  We should, at best, round to the nearest 0.1 or whole number.

- [x] reduce `bearing_after` and `bearing_before` precision
- [x] reduce `distance` precision - total distance should be kept consistent with sum of step distances

**Comment by TheMarex** [comment]
This was fixed by https://github.com/Project-OSRM/osrm-backend/pull/1935/commits/058263d58bb8bfe7c15141ccd033e4657b90d4cc but we will still see some rounding issues because of float representation issues.

**Comment by danpat** [comment]
@TheMarex the suggestion was primarily about float->string serialization.  This is where the real problem lies IMO:

https://github.com/Project-OSRM/osrm-backend/blob/develop/include/util/json_renderer.hpp#L44

and anything similar.  Of course, we'd need a way to allow printing precise values for lon/lat.

**Comment by TheMarex** [comment]
@danpat oh that renderer is not even used. we use the `ArrayRenderer` which does correct rounding.

**Comment by daniel-j-h** [comment]
> reduce distance precision - total distance should be kept consistent with sum of step distances

https://github.com/Project-OSRM/osrm-backend/pull/1935/commits/058263d58bb8bfe7c15141ccd033e4657b90d4cc rounds the leg's and step's `duration` and `distance` but does not sync. the route based on the rounded values, from what I see. That is, we are now producing situations where summing the legs does not equal the route's `duration` / `distance`.

**Comment by daniel-j-h** [comment]
Reopening because of issue mentioned above. If it's not a concern, please elaborate and close again.

**Comment by TheMarex** [comment]
@daniel-j-h Good point. The maximum error per-step is `0.005`. That means the total error is `0.005 * #steps`. For an error of 1 second we need trips with 200 steps. A cross-country trip over the US from SF to DC has 186 steps. As such I think we are good with any significant errors?

**Comment by daniel-j-h** [comment]
_Technically correct_, the best kind of correct. Should work :+1:
