### ISSUE TITLE
(Trip Plugin) Segementation Fault / Issue in FarthestInsertionTrip 

### ISSUE THREAD

**Issue by K-Leon** [Project-OSRM/osrm-backend#2147]
I just encountered an unroutable Trip in latest stable.

Using [this Route](https://router.project-osrm.org/trip?loc=46.9622733,7.4801433&loc=46.9621183,7.480145&loc=46.9621383,7.4801533&loc=46.9621633,7.4801717&loc=46.9621617,7.480165&loc=46.9621883,7.48015&loc=46.96225,7.4802083&loc=46.9622783,7.4801783&loc=46.9622517,7.4802083&loc=46.9616883,7.4803667&loc=46.96228,7.4801117) results in a crash.

These trips resolve more or less to these two segments. So we have several Waypoints without a real distance between each other.
46.962396,7.480171
46.961509,7.479702

**Results in:**
**osrm-routed: /src/library/../plugins/../algorithms/trip_farthest_insertion.hpp:212:** std::vector<unsigned int> osrm::trip::FarthestInsertionTrip(const NodeIDIterator&, const NodeIDIterator&, std::size_t, const DistTableWrapper<int>&) [with NodeIDIterator = __gnu_cxx::__normal_iterator<const unsigned int*, std::vector<unsigned int> >; std::size_t = long unsigned int]: **Assertion `max_from >= 0' failed.**

Anyone knows what could have caused this?

**Comment by daniel-j-h** [comment]
I can reproduce the error on latest develop and an Switzerland extract from Geofabrik.

--------------------------------------------------------------------------------------------------------------------------------

For the record, this is the v5 query:

    curl 'http://127.0.0.1:5000/trip/v1/driving/46.9622733,7.4801433;46.9621183,7.480145;46.9621383,7.4801533;46.9621633,7.4801717;46.9621617,7.480165;46.9621883,7.48015;46.96225,7.4802083;46.9622783,7.4801783;46.9622517,7.4802083;46.9616883,7.4803667;46.96228,7.4801117'

and I can not reproduce the issue with v5.

--------------------------------------------------------------------------------------------------------------------------------

What seems odd, though is the following:

Here's the `Trip` query for [46.962396,7.480171](http://www.openstreetmap.org/#map=18/46.962396,7.480171) and [46.96245/7.47965](http://www.openstreetmap.org/#map=18/46.96245/7.47965):

    http --body 'http://127.0.0.1:5000/trip/v1/driving/46.962396,7.480171;46.961509,7.479702'

Response: https://gist.github.com/daniel-j-h/476eafc2279a0fb309c2abdf7cd53c51

And now the same with the `Route` query:

    http --body 'http://127.0.0.1:5000/route/v1/driving/46.962396,7.480171;46.961509,7.479702'

Response: https://gist.github.com/daniel-j-h/4202a5ba08701b90e6c9248f00728cae

Now compare both `Trip` and `Route` response.

@K-Leon we're looking into it, thank you for reporting this!

**Comment by daniel-j-h** [comment]
Okay, this is what happens.

When you use the Route service we snap your coordinates differently to when you  use the Trip service. This is due to how the Trip service handles strongly-connected components (for an example see the demo server's small components layer, bottom left on the map).

The Route service snaps to the small component only when all coordinates are in the small component, and snaps to the big component otherwise.

The Trip service decomposes trips across components, so that you e.g. can get trips for coordinates on multiple islands.

With the changes I did in https://github.com/Project-OSRM/osrm-backend/pull/2172 you should at least no longer see the assertion being triggered.

**Comment by K-Leon** [comment]
Thank you very much for your hard work! 

This also explains related snapping issues. The different snapping logic leads at least at that point to (false) snapping on small unconnected road (racing track) instead of the Main Road at nearly equal distance of each other. The mapping at this point is a little bit questionable, but as far as i could see this is a fairly common error while working with 'unclean' position data.

[Trip](http://router.project-osrm.org/trip?loc=47.36176,7.31083&loc=46.9616883,7.4803667&loc=46.96228,7.4801117)

Corresponding [Viaroute](http://router.project-osrm.org/viaroute?loc=47.36176,7.31083&loc=46.9616883,7.4803667&loc=46.96228,7.4801117)

[Location in Question](https://www.openstreetmap.org/search?query=47.36176%2C7.31083#map=19/47.36176/7.31083)

If there's anything that could be done to solve this globally i would create a sepearte ticket.

**Comment by daniel-j-h** [comment]
The fact that snapping in different from Route to Trip is unfortunate (but there is a reason behind it, as outlined above). We _might_ want to change it at some point in time, but not in the foreseeable future as we're currently heads down on releasing v5.

@TheMarex what's your take on this?
