### ISSUE TITLE
Wrong car routing through motor_vehicle=delivery

### ISSUE THREAD

**Issue by marcows** [Project-OSRM/osrm-backend#2150]
See http://map.project-osrm.org/?z=17&center=49.318213%2C8.572083&loc=49.316863%2C8.575462&loc=49.316517%2C8.574700&hl=en&alt=0
The two streets connecting each service area with the street over the motorway are tagged with motor_vehicle=delivery, so they shouldn't be used.

Further info:
https://lists.openstreetmap.org/pipermail/talk/2016-February/075526.html

See also @Fujnky's [comment](https://github.com/Project-OSRM/osrm-backend/issues/256#issuecomment-145653584) on issue #256 illustrating a similar problem.

**Comment by daniel-j-h** [comment]
Thank you for reporting this. I looked into it and this is what I found:

If you take a look at the [car profile](https://github.com/Project-OSRM/osrm-backend/blob/0d291cb68ec5cb800b71856382963e55c8e7a98a/profiles/car.lua) you can see `access=motor_vehicle` in the whitelist, so we're currently routing over it unconditionally. `motor_vehicle=delivery` is something different. Here's its [taginfo](http://taginfo.openstreetmap.org/keys/motor_vehicle).

If you take a look at the [`access_tag_restricted`](https://github.com/Project-OSRM/osrm-backend/blob/0d291cb68ec5cb800b71856382963e55c8e7a98a/profiles/car.lua#L9) list you can find `access=delivery` in there. But `access_tag_restricted` is not used at the moment and will only be used in the future to augment the route response e.g. for guidance.

**Comment by marcows** [comment]
`access=motor_vehicle` is something different, we only talk about `motor_vehicle` as a key, not as a value (which catches wrong mapping like `access=motor_vehicle` I guess - or are these preprocessed tags, not directly related to OSM tags?).

I just tried and learned OSRM also routes through roads with `motor_vehicle=destination`. Is this on purpose because detection of whether the routing target is inside a destination area is not implemented yet?

I've read the car profile lua code (which I only skimmed through before writing this issue) and conclude that `access_tag_whitelist` only has any influence for highway values not included in `speed_profile` (highway=track or unknown highway values) - and then only on the speed, not on access. For prohibiting access, `access_tag_blacklist` has to contain the concerned access value.

> But access_tag_restricted is not used at the moment and will only be used in the future to augment the route response e.g. for guidance.

I don't understand what "to augment the route response e.g. for guidance" means.

So in my opinion the following patch (untested) might fix this issue as long as restricted access is not implemented (at least from what I currently think `restricted` means in case of OSRM):

```diff
diff --git a/profiles/car.lua b/profiles/car.lua
index f6bfd23..8e0fd74 100644
--- a/profiles/car.lua
+++ b/profiles/car.lua
@@ -5,7 +5,7 @@ local find_access_tag = require("lib/access").find_access_tag
 -- Begin of globals
 barrier_whitelist = { ["cattle_grid"] = true, ["border_control"] = true, ["checkpoint"] = true, ["toll_booth"] = true, ["sally_port"] = true, ["gate"] = true, ["lift_gate"] = true, ["no"] = true, ["entrance"] = true }
 access_tag_whitelist = { ["yes"] = true, ["motorcar"] = true, ["motor_vehicle"] = true, ["vehicle"] = true, ["permissive"] = true, ["designated"] = true, ["destination"] = true }
-access_tag_blacklist = { ["no"] = true, ["private"] = true, ["agricultural"] = true, ["forestry"] = true, ["emergency"] = true, ["psv"] = true }
+access_tag_blacklist = { ["no"] = true, ["private"] = true, ["agricultural"] = true, ["forestry"] = true, ["emergency"] = true, ["psv"] = true, ["delivery"] = true }
 access_tag_restricted = { ["destination"] = true, ["delivery"] = true }
 access_tags = { "motorcar", "motor_vehicle", "vehicle" }
 access_tags_hierachy = { "motorcar", "motor_vehicle", "vehicle", "access" }
```

**Comment by daniel-j-h** [comment]
>>    But access_tag_restricted is not used at the moment and will only be used in the future to augment the route response e.g. for guidance.

>I don't understand what "to augment the route response e.g. for guidance" means.

In case we have to route you over those, we want to notify you about it in the user interface / the instructions. The `access_tag_restricted` list itself does not prevent routing over its values.

I had to take a deeper look at the profiles myself, so here's a guided tour through the car profile:

The [find_access_tag](https://github.com/Project-OSRM/osrm-backend/blob/c34fff5e7a06b662f6f5694cbb88ef5ec48c3ee3/profiles/lib/access.lua#L5-L13) function takes a node or a way and checks if there are values for the keys: "motorcar", "motor_vehicle", "vehicle", "access" [as listed in the `access_tags_ hierachy` list](https://github.com/Project-OSRM/osrm-backend/blob/c34fff5e7a06b662f6f5694cbb88ef5ec48c3ee3/profiles/car.lua#L11).

[For nodes](https://github.com/Project-OSRM/osrm-backend/blob/c34fff5e7a06b662f6f5694cbb88ef5ec48c3ee3/profiles/car.lua#L185-L188) we check if the value is in the [`access_tag_blacklist`](https://github.com/Project-OSRM/osrm-backend/blob/c34fff5e7a06b662f6f5694cbb88ef5ec48c3ee3/profiles/car.lua#L8) and if so mark the node as a barrier.

[For ways](https://github.com/Project-OSRM/osrm-backend/blob/c34fff5e7a06b662f6f5694cbb88ef5ec48c3ee3/profiles/car.lua#L240-L244) we check if the value is in the [`access_tag_blacklist`](https://github.com/Project-OSRM/osrm-backend/blob/c34fff5e7a06b662f6f5694cbb88ef5ec48c3ee3/profiles/car.lua#L8) and if so discard that way.

Your proposed change therefore effects the following nodes and ways:

http://taginfo.openstreetmap.org/tags/motorcar=delivery
http://taginfo.openstreetmap.org/tags/motor_vehicle=delivery
http://taginfo.openstreetmap.org/tags/vehicle=delivery
http://taginfo.openstreetmap.org/tags/access=delivery

Which looks fine to me for preventing routing over delivery-only nodes or ways. I will create a pull request with your changes and let @TheMarex take a final look.
