### ISSUE TITLE
Douglas Peucker algorithm uses bad approximation

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2151]
Currently the Douglas Peucker algorithm we use for geometry simplification uses an approximate distance metric that leads to results like this:

http://bl.ocks.org/d/867d579ec59bfc965bf1

The turn coordinate should not be removed at this zoom level, however the geometry contains almost co-linear points that are preserved.

**Comment by danpat** [comment]
You think it would make sense to only simplify the geometry between turn coordinates?

**Comment by TheMarex** [comment]
No we need to replace the approximation by the correct method. We are not dependent on the precise turn coordinates being present in the geometry anymore since we moved that to the `Maneuver` object.

**Comment by TheMarex** [comment]
The offending code is [here](https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/src/engine/douglas_peucker.cpp#L21-L57) this needs to be replaced by the point-segment distance from `coordinate_calculation`.

**Comment by TheMarex** [comment]
This is fixed.
