### ISSUE TITLE
Are "river upstream" / "river downstream" modes reversed?

### ISSUE THREAD

**Issue by lbud** [Project-OSRM/osrm-backend#2156]
I'm not very sure what rivers in the OSM sense even are, but based on what I'm seeing in [features/testbot/mode.feature](https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api-tests/features/testbot/mode.feature) I'm highly suspicious that `river upstream` and `river downstream` are either reversed, _or_ the notations in the previous cucumber tests were incorrect (I translated the numbers in `modes` based on [these annotations](https://github.com/Project-OSRM/osrm-backend/blob/8d275c91d92d98550d7bd4859531921116adc61e/features/testbot/mode.feature#L7-L8)), but I suspect the former… @MoKob @TheMarex (tagging `@mokob @2166`)

**Comment by MoKob** [comment]
https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/include/extractor/travel_mode.hpp#L53-L54 indicate `river upstream == 10`  and `river downstream == 11` where previously `river downstream == 3` and `river upstream == 4`

It looks like these travel_modes are hardcoded into the backend now. So the annotations in the profiles are not correct anymore. @TheMarex are there other changes here that could influence this?

**Comment by MoKob** [comment]
Assigning @TheMarex as not directly a guidance but a refactor question

**Comment by TheMarex** [comment]
No, I probably swapped it by accident when porting the profiles to string-identifiers.

**Comment by MoKob** [comment]
With the cucumber tests passing again, this has been fixed (https://github.com/Project-OSRM/osrm-backend/pull/2229)
