### ISSUE TITLE
Optimize Douglas Peucker line simplification

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2160]
https://github.com/Project-OSRM/osrm-backend/pull/2153 changed the way our implementation of the Douglas Peucker algorithm selected points for removal.

The upside is that it's more accurate.  The downside is that it's slower - the point-distance-from-line calculation is fairly expensive, and we call it a lot more than we should.

We should optimize this:

  1. We should pre-calculate and cache projected coordinates - we don't need to do this every loop.
  2. Consider if there is some faster arithmetic that might achieve the same precision (perhaps we can take advantage of this approach? http://barendgehrels.blogspot.com/2010/07/efficient-distances.html)

**Comment by TheMarex** [comment]
Implemented both of this in the `makeitfaster` branch with great success. Instead of real distances in meters we go the route over pixel which is actually what matters on the screen. This also enables using the squaredEuclideanDistance which is orders of magnitude faster.
