### ISSUE TITLE
Need to JSON-escape error context in JSON reply

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2164]
https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/src/server/request_handler.cpp#L112

If an error occurs that triggers this code path, and JSON control-chacarters are included in `context`, the returned JSON may be invalid.

We need to apply `escape_JSON` to the `context` from here: https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/include/util/string_util.hpp#L62

Example bad response:

`{"code":"InvalidUrl","message":"URL string malformed close to position 0: \"\/vi\""}`

/cc @miccolis @TheMarex

**Comment by daniel-j-h** [comment]
I looked into this and I think the whole context handling is borked, take a look here and note the `X` that I use to force an error at different locations:

```json
daniel@x1c /t/o/build> curl 'http://127.0.0.1:5000/Xroute/v1/driving/'
{"message":"URL string malformed close to position 0: \"v\"\"\/Xr\"","code":"InvalidUrl"}

daniel@x1c /t/o/build> curl 'http://127.0.0.1:5000/route/Xv1/driving/'
{"message":"URL string malformed close to position 0: \"\/ro\"","code":"InvalidUrl"}

daniel@x1c /t/o/build> curl 'http://127.0.0.1:5000/route/v1/driving/'
{"message":"URL string malformed close to position 0: \"vin\/ro\"","code":"InvalidUrl"}
```

Position is always `0`, and the context is never useful (it's not even correct).

**Comment by TheMarex** [comment]
Actually the JSON escaping seems correct. User error. :-)
