### ISSUE TITLE
Report speed file statistics

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2178]
`osrm-contract` should report statistics for supplied speed files showing what percentage of the road network in terms of count (and *maybe* distance?) received an edge weight from each speed file. This will give users a sense for how much each input file is contributed to the outputted graph.

Output could look something like:

```
speedfileA.csv 163423908 segments (24%)
speedfileB.csv 211089215 segments (31%)
speedfileC.csv 129377260 segments (19%)
profile 177042567 segments (26%)
```

**Comment by daniel-j-h** [comment]
@willwhite: last week @freenerd implemented statistics in https://github.com/Project-OSRM/osrm-backend/pull/2440.
Does this solve your problems? If so please close this ticket.
