### ISSUE TITLE
Superflous name change instruction

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2183]
>  cucumber features/testbot/via.feature:50 # Scenario: Multiple via points

@MoKob this contains a superflous name change instruction.

**Comment by MoKob** [comment]
Currently I cannot reproduce this error. It seems it may be fixed already by @danpats change to the post-processing to use meters instead of epsilon?

**Comment by TheMarex** [comment]
Fixed.
