### ISSUE TITLE
missing translation (ferry)

### ISSUE THREAD

**Issue by mtmail** [Project-OSRM/osrm-backend#2191]
Going `Newhaven, England` to `Dierre, France` includes a ferry. 

http://www.openstreetmap.org/directions?engine=osrm_car&route=50.7887%2C0.0484%3B49.9246%2C1.0791#map=9/50.3639/0.5672&layers=C

Step 17 shows `[missing "en-US.javascripts.directions.instructions.ferry_without_exit" translation]`

I checked the` openstreetmap-website`, `osrm-backend` and `osrm-frontend` sources and can't find where that would go. 

![2](https://cloud.githubusercontent.com/assets/3727288/14212504/80abd70c-f833-11e5-892c-6efa8b18c120.png)

**Comment by danpat** [comment]
Moving this ticket to `osrm-frontend`, the translation happens at the UI layer.

https://github.com/Project-OSRM/osrm-frontend/issues/169
