### ISSUE TITLE
StaticRTree changeover when using shared memory is slow

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2194]
When using shared memory, particularly with large datasets, it can take some time (multiple seconds) for the new thread-specific StaticRTree object to be created.  This blocks queries until the new rtree is in place.

We should look into re-structuring the RTree memory layout so that this initial construction can be minimized, speeding up the swapover.  As an alternative, we should see if we can construct the RTree without blocking queries.

The specific problem is here:
https://github.com/Project-OSRM/osrm-backend/blob/aa90d7b4b7373beb6d4c9a86fc2d1a1f542bd123/include/engine/datafacade/shared_datafacade.hpp#L105

other data loading functions are fast, because they're fairly linear data structures - we just update some pointers and then move on.  The StaticRTree does some expensive initialization, which we should see if we can avoid.

**Comment by TheMarex** [comment]
The main problem is that each StaticRTree contains a file handle that needs to be modified. The ways we are currently solving this is quite overkill: Have one StaticRTree object per thread.

I see two ways to address this:

1. Make the file handle thread-specific in StaticRTree => `Nearest()` would be thread-safe
2. Move the whole RTree to mmap, which eliminates the need of an explicit file handle and access would always be thread-safe (and const)

**Comment by daniel-j-h** [comment]
Option 2 is ticketed out in https://github.com/Project-OSRM/osrm-backend/issues/1987.

**Comment by TheMarex** [comment]
This will be fixed by https://github.com/Project-OSRM/osrm-backend/pull/2385

**Comment by TheMarex** [comment]
Landed.
