### ISSUE TITLE
Add tests for tile plugin

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2198]
The tile plugin broke between `.7` and `.rc.1`. The only reason why we caught it, is because of failing `node-osrm` tests. We need a meaningful test-case in cucumber and `unit_tests/library/tile.cpp`.

**Comment by danpat** [comment]
:+1: On it.  @TheMarex what broke?

**Comment by TheMarex** [comment]
@danpat the rectangle query. I already fixed the issue in `rewrite/new-api`.

**Comment by TheMarex** [comment]
This still needs to happen:
- [ ] cucumber test: decode pbf and do a sanity check
- [ ] unit tests: Add call to tile plugin

I can jump on this, I feel like doing some JS.

**Comment by danpat** [comment]
Sanity checks implemented as unit tests.
