### ISSUE TITLE
osrm did not see stxxl

### ISSUE THREAD

**Issue by H91011** [Project-OSRM/osrm-backend#2199]
Hi, 

I build osrm and with [digital ocean document](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04) . I create .stxxl file and its : disk=/tmp/stxxl,25000,syscall like this and this file in osrm directory with osrm-backend directory and I try osrm-extract map.osm.pbf  in osrm-backend directory and output here: 

```
[info] Input file: turkey-latest.osm.pbf

[info] Profile: profile.lua

[info] Threads: 8

[info] Using script profile.lua

[STXXL-MSG] STXXL v1.3.1 (release)

[STXXL-ERRMSG] Warning: no config file found.

[STXXL-ERRMSG] Using default disk configuration.

[STXXL-MSG] 1 disks are allocated, total space: 1000 MiB

[info] Parsing in progress..

[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)

[info] timestamp: 2016-04-02T19:14:02Z

[info] Using turn restrictions

[info] Found 3 exceptions to turn restrictions:

[info]   motorcar

[info]   motor_vehicle

[info]   vehicle

^C
```

It is not see my stxxl disk, why ? 

its my disk : 
```
Filesystem     1K-blocks    Used Available Use% Mounted on
udev            28851632      12  28851620   1% /dev
tmpfs            5771304     400   5770904   1% /run
/dev/sda1       30202916 2075012  26861872   8% /
none                   4       0         4   0% /sys/fs/cgroup
none                5120       0      5120   0% /run/lock
none            28856504       0  28856504   0% /run/shm
none              102400       0    102400   0% /run/user
none                  64       0        64   0% /etc/network/interfaces.dynamic.d
/dev/sdb1      412716208   71960 391656448   1% /mnt
```

**Comment by H91011** [comment]
I fixed this I create .stxxl in osrm-backend directory

**Comment by daniel-j-h** [comment]
Interesting. For the record, OSRM no longer needs the packges `libosmpbf-dev libprotobuf-dev` from the tutorial. I also recommend checking out a specific tag if you want a stable release, e.g. `v4.9.1` as the default branch will get you the development version where we e.g. renamed `osrm-prepare` to `osrm-contract`.

I will reach out to get the tutorial updated!
