### ISSUE TITLE
Keep waypoints on the left/right

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2201]
If you're a taxi driver planning a route, it might be preferable to approach a waypoint on the side of the road that deposits/picks up your passenger without needing to cross the road, and then continue routing you without issuing a u-turn.

This is partly implemented by the "allow u-turns at waypoints" parameter in the Lua profiles.

We could implement a query-time parameter called "keep waypoints on the left/right".  When constructing phantom nodes, we would eliminate edges that do not put the foot segment on the specified side.  The behaviour would be similar to the bearing filter - only the relevant edges would be seeded on the query heap.

It should be a query-time parameter to allow for left/right side driving, allowing localized apps to specify the desired side.

**Comment by frodrigo** [comment]
This feature is also interesting in start/end point and on matrix computation, since matrix is just route segments for TSP optimization. Sometimes I recompute only segment of route, but still interested on waypoints on the left/right.

**Comment by jperaltamalvar** [comment]
This feature would be useful for buses, since they only have doors on one side, either on the left (british ones) or on the right (others), as well as some kind of trucks, like [this one](https://stoysnetcdn.com/brud/brud2761/brud2761.jpg).

In Network Analyst this is the `CurbApproach `parameter.

**Comment by emiltin** [comment]
Also relevant for bike and foot routing, since crossing bigger roads is often only possible at intersections.

**Comment by TheMarex** [comment]
This was addressed with the `approaches` parameter.
