### ISSUE TITLE
Travis builds using clang-3.8 are failing

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2206]
Currently we can't build OSRM on `clang 3.8` because the compiler is not found. Seems like a breakage in the repository, since this used to work just fine.

/cc @daniel-j-h

**Comment by daniel-j-h** [comment]
With the LLVM 3.8 release from two weeks ago the [LLVM apt repository](http://llvm.org/apt/) no longer tracks 3.8 but 3.9 (nightly) instead. Let's pin LLVM 3.8 (stable) instead. Working on this.

**Comment by daniel-j-h** [comment]
Yep that was the issue. Fixed in https://github.com/Project-OSRM/osrm-backend/issues/2207.
