### ISSUE TITLE
Response body code should be capitalized `Ok`

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#2209]
In https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#response the `code` property in responses is `Ok` for successful responses. It returns lower-case 'ok' for distance matrix and route requests though.

/cc @TheMarex

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/commit/0f18426575fc85b9e8f5de137b5552215b884684.

Hopefully this late fix won't break downstream too much. We should definitely write about that in the changelog for the next RC / the final release.
