### ISSUE TITLE
Disable steps and alternatives by default

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2215]
We inherited the default setting of `steps=true` and `alternatives=true` from upstream. In practice we see that most people don't actually use the steps or alternative, but won't bother to change the default settings. That means the server does a lot of computational work for nothing.

Proposal:
- `steps=false` by default
- `alternatives=false` by default

/cc @freenerd

**Comment by daniel-j-h** [comment]
Done in https://github.com/Project-OSRM/osrm-backend/issues/2217.
