### ISSUE TITLE
Unit tests: server-tests are broken on v5 (unit_tests/server/parameters_parser.cpp)

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2218]
Not sure when we introduced a commit that broke it, but I can see a ton of assertions being triggered and a memory access violation. Investigate.

**Comment by MoKob** [comment]
Should be fixed with the merge of https://github.com/Project-OSRM/osrm-backend/pull/2229 and its prerequisite https://github.com/Project-OSRM/osrm-backend/pull/2133
