### ISSUE TITLE
Internal Server Error on v5.0.0-rc.1

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#2219]
I'm compiling at `v5.0.0-rc.1`, extracting/contracting using the default car profile on berlin-160314.osm.pbf from geofabrik.

The request 
```
/route/v1/car/13.33,52.59;13.21,52.46;13.35,52.42;13.4,52.3;13.45,52.27;13.47,52.46;13.33,52.59?alternatives=false&steps=false&overview=full
``` 
works as expected, but if I append `&uturns=true` at the end, I get a `{"code": "InternalError","message":"Internal Server Error"}` response.

See full `osrm-routed` log:

```
[info] 05-04-2016 11:39:24 127.0.0.1 - Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 /route/v1/car/13.33,52.59;13.21,52.46;13.35,52.42;13.4,52.3;13.45,52.27;13.47,52.46;13.33,52.59?alternatives=false&steps=false&overview=full&uturns=true
[warn] [server error] code: vector::_M_range_check: __n (which is 2147483648) >= this->size() (which is 171601), uri: /route/v1/car/13.33,52.59;13.21,52.46;13.35,52.42;13.4,52.3;13.45,52.27;13.47,52.46;13.33,52.59?alternatives=false&steps=false&overview=full&uturns=true
```

**Comment by daniel-j-h** [comment]
Thanks, we will look into this! Related: https://github.com/Project-OSRM/osrm-backend/issues/2213.

**Comment by MoKob** [comment]
Should be fixed with: https://github.com/Project-OSRM/osrm-backend/pull/2221

The removal of u-turns as parameter will render the respective code-path obsolete, though.

**Comment by daniel-j-h** [comment]
Solved!
