### ISSUE TITLE
Make use of Appveyor: missing tests, libosrm compilation, sync with Travis

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2226]
Appveyor is missing at least

- [ ] [library tests](https://github.com/Project-OSRM/osrm-backend/blob/a33bd9dfe6dcf651bae89c29cdcee8bc7587b861/.travis.yml#L168)
- [x] server tests (we're not running them on Travis, too --- why? @TheMarex ideas?),
- [ ] building the example, making sure FindOSRM works as expected (that is, libosrm is actually usable)
- [ ] now that we have cucumberjs, maybe running those. Case in point: @MoKob is seeing different results on Linux and on OSX for some tests, running them on multiple platforms only helps

Now that we are able to [build OSRM on Windows again](https://github.com/Project-OSRM/osrm-backend/pull/2118) it makes sense to actually use this.

/cc @BergWerkGIS

**Comment by TheMarex** [comment]
> server tests (we're not running them on Travis, too --- why? @TheMarex ideas?),

That is a bug. Enabled in 8b6da4d2fe2c073ceee69d23df7c5a83ecf26825.

**Comment by springmeyer** [comment]
:+1: would be great to get more working/tested on windows. Per voice with @BergWerkGIS he is tied up this week, but might have time to help later next week.

**Comment by BergWerkGIS** [comment]
Locally and [on AppVeyor](https://ci.appveyor.com/project/DennisOSRM/osrm-backend/build/1.0.3246#L3441) I get the following error during `eslint`:

```
> eslint -c .eslintrc features/step_definitions/ features/support/
 
Node Version v4.4.3
Using default port 5000
Using default timeout 5000
crypto.js:70
  this._handle.update(data, encoding);
               ^
 
TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:70:16)
    at ReadFileContext.callback (C:\projects\osrm\features\support\hash.js:15:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
npm ERR! Test failed.  See above for more details.
```

Any ideas how to get past this?

**Comment by BergWerkGIS** [comment]
Added `console.log` and get:

```
path: c:\mb\osrm-backend\build/osrm-extract
data: undefined
```

I suppose `osrm-extract` should point to the binary (on Windows `build\Release\osrm_extract.exe`), correct?

**Comment by daniel-j-h** [comment]
Seems like this is the problem (see the nice todo :P)

1. https://github.com/Project-OSRM/osrm-backend/blob/64307ea882bcbd98ff86800cac2b92cb24eda9b6/features/support/env.js#L39-L48
2. https://github.com/Project-OSRM/osrm-backend/blob/64307ea882bcbd98ff86800cac2b92cb24eda9b6/features/support/run.js#L28

I don't think we can reliably verify that check without access to a Windows machine. @BergWerkGIS can you see if you can fix it yourself? It should be good enough to get the command assembly working.

/cc @lbud

**Comment by BergWerkGIS** [comment]
@daniel-j-h thanks, I'm already past that two.

Currently battling here:

```
.F.F.F.F.F.F.F.F.F...c:\mb\osrm-backend\node_modules\cucumber\lib\cucumber\support_code\step_definition.js:112
      var timeoutInMilliseconds = options.timeout || defaultTimeout;
                                         ^

TypeError: Cannot read property 'timeout' of undefined
    at nextTickCallbackWith0Args (node.js:420:9)
    at Immediate._tickCallback [as _onImmediate] (node.js:349:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 npm ERR! Test failed.  See above for more details.
```

**Comment by BergWerkGIS** [comment]
> https://github.com/Project-OSRM/osrm-backend/blob/64307ea882bcbd98ff86800cac2b92cb24eda9b6/features/support/run.js#L28

You are right about that, not yet past it.

`test/cache` looks like this:

![image](https://cloud.githubusercontent.com/assets/4549888/14959199/b4b13576-107d-11e6-846b-06026125903e.png)

Associated `cmd`:

```
"c:\mb\osrm-backend\build\Release/osrm-datastore.exe" c:\mb\osrm-backend\test\cache\0a044fecccceeee980c857aeb202e1280591e8a4_e2c229fd87d7d1cf9ba17d2f6abe34271055f4fd_265d921358754a2ad6e0f60464bf21508f27f096.osrm 2>c:\mb\osrm-backend\test\error.log
```

`test/error.log`:
```
[warn] Invalid file path given!
```

----

I suppose `osrm` files shouldn't have the extension `timestamp`?

**Comment by BergWerkGIS** [comment]
hm, `osrm-routed` doesn't seem to be running.

**Comment by lbud** [comment]
@BergWerkGIS 🙀 I'm happy to jump in on fixing the cucumber tests actually, being the perpetrator of a lot of the current support code — I'll be back in the SF office tomorrow where I _think_ there is a windows laptop I can borrow ( @springmeyer or @lucaswoj can you confirm?)

**Comment by BergWerkGIS** [comment]
@lbud yeah, that would be great. Haven't yet grasped the whole concept how everything fits together within the tests.
Just pushed my latest changes: https://github.com/Project-OSRM/osrm-backend/pull/2352

**Comment by springmeyer** [comment]
@lbud - yes, happy to help you get things going on windows.

**Comment by BergWerkGIS** [comment]
Great, thanks @springmeyer, I updated the Windows instructions today:
https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation

**Comment by BergWerkGIS** [comment]
##### `osm-extract` is working now (more or less).

Problem is the [redirect into the log file](https://github.com/Project-OSRM/osrm-backend/blob/2dfda1782e0dcf326ae51e45a2ea5fbc73a38624/features/support/data.js#L215-L218).
I commented it for now.

The command works when issued directly on the console but it seems that node messes something up when spanning.
Error message is:
```
Too Many Positional Arguments
```

----

##### workaround for https://github.com/Project-OSRM/osrm-backend/issues/2362

I managed to get it working by copying `access.lua` and `maxspeed.lua` into a new directory:

```
ROOT_FOLDER\build\lib\lua\
```

----

##### Next steps:
* look into why `osrm-routed` is not running
* revisit `span\exec\execFile` and redirect `>>`
* `lua`'s `require` with relative Windows paths

**Comment by BergWerkGIS** [comment]
Tests try to start `osrm-routed` via

```
c:\mb\osrm-backend\build\Release\osrm-routed.exe --shared-memory=1 -p5000
```

which results in

```
[info] starting up engines, v5.1.0
[info] Loading from shared memory
[info] Threads: 8
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:5000
[warn] [exception] End canary of block corrupted.
```

Same error when I use the above command on the console.
What are the pre-requisites for this command to succeed?
What do I have to enter on the console manually to see what should happen?

**Comment by daniel-j-h** [comment]
If you want `osrm-routed` to load data from shared memory, you need to use the datastore first to pin data into memory. Try using the path to the `.osrm` file instead:

    ./osrm-routed ../test/data/monaco.osrm

For the record: we dump four bytes for "OSRM" at the front of the `.osrm` file, as in:

    head -c 4 ../test/data/monaco.osrm | xxd -g 1
    0000000: 4f 53 52 4d                                      OSRM

and throw an error in case we get files that don't have these four bytes at the front.

**Comment by BergWerkGIS** [comment]
Ah, thanks. 
Yes, `osrm-datastore` is the problem.
I only monitored via Process Explorer if it runs, which it does.
But cucumber/node::execFile hid the fact that it crashed:

```
"c:\mb\osrm-backend\build\Release/osrm-datastore.exe" c:\mb\osrm-backend\test\cache\8254ae986fb991c00b26cecceed1627d0208ebb4_37eddc9412e7a5da452a0747e671da4258e2db2b_265d921358754a2ad6e0f60464bf21508f27f096.osrm
```

```
[info] load names from: "c:\mb\osrm-backend\test\cache\8254ae986fb991c00b26cecceed1627d0208ebb4_37eddc9412e7a5da452a0747e671da4258e2db2b_265d921358754a2ad6e0f60464bf21508f27f096.osrm.names"
[info] name offsets size: 1
[info] allocating shared memory of 4196 bytes
```

![image](https://cloud.githubusercontent.com/assets/4549888/15014210/346296a8-11f4-11e6-8e3d-32943b24415e.png)

I thinks it's really high time create a debug build.

**Comment by BergWerkGIS** [comment]
same error with `monaco.osm.pbf`:

```
λ build\Release\osrm-datastore.exe test\data\monaco.osrm
[info] load names from: "test\data\monaco.osrm.names"
[info] name offsets size: 36
[info] allocating shared memory of 2031474 bytes
CRASH
```

```
build\Release\osrm-extract.exe test\data\monaco.osm.pbf --profile profiles\bicycle.lua
build\Release\osrm-contract.exe test\data\monaco.osrm
build\Release\osrm-datastore.exe test\data\monaco.osrm
```

^^ is this the correct way to prepare the data?

**Comment by daniel-j-h** [comment]
`osrm-datastore` uses shared memory to pin regions into RAM. It's implementation is platform specific (I don't know we we're not using the portable Boost shm abstractions.. probably historic reason) e.g. see:

https://github.com/Project-OSRM/osrm-backend/blob/6018fcf490ea7ba4f1d27ea70125e9492c3301c5/include/storage/shared_memory.hpp

So I can't help you there without more information / a debug build.

How you prepare the data looks fine; `osrm-routed` without the shared memory flag works, correct?

**Comment by danpat** [comment]
@BergWerkGIS @springmeyer @daniel-j-h I just put out a call for a Windows maintainer on the OSRM-Talk mailing list (https://lists.openstreetmap.org/pipermail/osrm-talk/2016-May/001214.html).

Given that we don't develop on, or use OSRM on any Windows platforms, there's a big question in my mind whether we need to invest time in supporting that platform.  If someone with a vested interest is willing to step up to the role, that'd be great, but I think we can pause on this work for now.

Another option on the horizon is Docker for Windows (https://blog.docker.com/2016/03/docker-for-mac-windows-beta/), which claims to offer native-like performance using Hyper-V.  If it works as promised, we could get Windows support for free, and no longer need any Windows-specific code - our target would be Linux in all cases.

**Comment by daniel-j-h** [comment]
We're dropping Windows support. There was no one standing up as a Windows dev / maintainer.
Ref: https://lists.openstreetmap.org/pipermail/osrm-talk/2016-May/001214.html

Closing this ticket, no longer actionable.
