### ISSUE TITLE
Re-Enable Spirit invalid parsing test

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2236]
I've temporarily [disabled](https://github.com/Project-OSRM/osrm-backend/pull/2229/files#diff-9a83ed8ae9e8bf98b3adb26f7e700d31R89) a parser tests in the unit-tests. It is a known issue and should be fixed with https://github.com/Project-OSRM/osrm-backend/pull/2188.

When https://github.com/Project-OSRM/osrm-backend/pull/2188 gets merged, the test needs to be re-enabled.

**Comment by daniel-j-h** [comment]
Done in https://github.com/Project-OSRM/osrm-backend/pull/2188#issuecomment-207414813.
