### ISSUE TITLE
Malfunction of the trip service - 2 trips for road without island

### ISSUE THREAD

**Issue by dawadam** [Project-OSRM/osrm-backend#2238]
Hi,
Trip service is very interesting, but I feel it is not working properly.
Anyway this example proves.
I've been testing a trip between some cities in France:
- Chambéry
- Clermont-Ferrand
- Troyes
- Lyon
- Grenoble

http://router.project-osrm.org/trip?compression=false&loc=45.56639,5.92083&loc=45.77972,3.08694&loc=48.29889,4.07806&loc=45.75889,4.84139&loc=45.1872,5.7266

Answer contains two trips.
The first is Clermont-Ferrand and the second is the rest of the trip.
Yet there is no island !
Problem is even adding the point on the first city at the end of the query.
Regards

**Comment by daniel-j-h** [comment]
The Trip plugin de-composes trips across components.
Here is a detailed explanation: https://github.com/Project-OSRM/osrm-backend/issues/2147#issuecomment-203477681.

If you take a look at Clermont-Ferrand here

http://map.project-osrm.org/?z=18&center=45.780097%2C3.088215&loc=45.779956%2C3.087092&hl=en&alt=0

and enable the "Small Components" layer (bottom, left) you can see "Rue des Bohèmes" not being connected to the road network at all. Unfortunately this is the road you're getting when adding a via point for Clermont-Ferrand.

This is a data problem. Feel free to fix it in OSM :)

**Comment by daniel-j-h** [comment]
Closing as it's not actionable on our side. As I outlined above, it's a data issue in OSM.

See "Rue des Bohèmes" not being connected to the road network at all. Unfortunately this is the road you're getting when adding a via point for Clermont-Ferrand.

**Comment by dawadam** [comment]
Thank you, I'll study that.
