### ISSUE TITLE
Error during osrm-extract with OSRM 5.0

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2243]
While setting up the v5 OSRM demo server, this error occurred during `osrm-extract` when processing the current planet file (see timestamps below for the exact file in use):

```
[Sun, 10 Apr 2016 00:47:32 GMT] [2016-04-09-203750] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[Sun, 10 Apr 2016 00:47:32 GMT] [2016-04-09-203750] [info] Generated 617517573 nodes in edge-expanded graph
[Sun, 10 Apr 2016 00:47:32 GMT] [2016-04-09-203750] [info] generating edge-expanded edges
[warn] bad numeric conversion: positive overflow
```

/cc @TheMarex @MoKob

**Comment by danpat** [comment]
This looks like it's coming from one of the `boost::numeric_cast` statement.  I'm running a full-planet extract in debug mode with some added assertions to see if I can figure out which one is doing it.

Possible candidates so far: uninitialized coordinate passed to `computeAngle`.

Work is on `fix/2243` branch.

**Comment by danpat** [comment]
We are explicitly checking the node count (https://github.com/Project-OSRM/osrm-backend/blob/fix/2243/src/extractor/extraction_containers.cpp#L198) and the edge count (https://github.com/Project-OSRM/osrm-backend/blob/fix/2243/src/extractor/extraction_containers.cpp#L508) which are the only two other places where we're using `numeric_cast` in the extractor.  Definitely seems like a bad coordinate has made it through.

**Comment by freenerd** [comment]
Seeing this error now

```
[warn] /mnt/ebs/osrm/util/coordinate_calculation.cpp:41
in: double osrm::util::coordinate_calculation::haversineDistance(osrm::util::Coordinate, osrm::util::Coordinate): lat2 != std::numeric_limits<int>::min()
```

**Comment by TheMarex** [comment]
@danpat just to clarify since you tagged this `5.0`: We are talking about the 5.0 prepare process here, right?

**Comment by danpat** [comment]
@TheMarex the above errors came from `develop` this weekend, so yes, `osrm-extract` for the upcoming 5.0 release.

**Comment by danpat** [comment]
Looks like this is being caused by a math error in `coordinate_calculation::circleCenter`.  Under some circumstances, the `lat` value returned is `nan`.

**Comment by danpat** [comment]
It seems that the `circleCenter` function isn't handling cases where coordinates are colinear in the Y axis.
The following coordinates cause it to return an invalid value:

```
(lldb) print C1
(const osrm::util::Coordinate) $6 = {
  lon = (x = -112096234)
  lat = (x = 41147101)
}
(lldb) print C2
(const osrm::util::Coordinate) $7 = {
  lon = (x = -112096606)
  lat = (x = 41147101)
}
(lldb) print C3
(const osrm::util::Coordinate) $8 = {
  lon = (x = -112096419)
  lat = (x = 41147259)
}
(lldb) print lon
(const double) $9 = -112.09641999999999
(lldb) print lat
(const double) $10 = NaN
```

**Comment by MoKob** [comment]
@danpat good catch... I checked all divisions except for that one 😦 ... Your fix is broken though. I corrected it to solve the math correctly now.
