### ISSUE TITLE
Inside or outsite of the route

### ISSUE THREAD

**Issue by jonatasfreitasv** [Project-OSRM/osrm-backend#2256]
is there any way to know if a certain position (lat -long ) is inside or outside of route ?

**Comment by daniel-j-h** [comment]
What do you mean with "inside or outside of route"? Do you want to know if a specific route goes over / near a specific coordinate?

**Comment by jonatasfreitasv** [comment]
For example , I have a route from city A to city B ok ?

I have the position of the vehicle a lat and long.

I need to know if the vehicle is in or out of the route , you know?

**Comment by danpat** [comment]
@jonatasfreitasv A naive way to do this is to calculate the distance from your lon/lat to each segment of the route line:

  https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_line

An example of this using Javascript would be to first use:

  http://turfjs.org/static/docs/module-turf_point-on-line.html

then:

  http://turfjs.org/static/docs/module-turf_distance.html

and if the distance is greater than a threshold you decide on, then you are not on the route.

If you want to get really fancy, you can use the `match` service and a few previous GPS coordinates (say, the last 1 minute) to map-match your current GPS trace.  If the `confidence` is very high, then you're probably on the route still.  If your `confidence` is low, you are probably going off the route.

In both cases, you will need to perform the logic on the client side, it is not a feature of OSRM.

**Comment by jonatasfreitasv** [comment]
Thx a lot @danpat.
