### ISSUE TITLE
Add persistent benchmarks for libosrm

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2258]
We need simple micro-benchmarks for each library function. These can use a set of automatically generated but fixed routes on a _real_ dataset (e.g. monaco).

For this we need to evaluate and pick a benchmarking framework:
- https://github.com/google/benchmark
- https://github.com/nickbruun/hayai
- https://github.com/DigitalInBlue/Celero

Then implement performance tests for:
- [ ] Route
- [ ] Match
- [ ] Trip
- [ ] Nearest
- [ ] Table
- [ ] Tile

**Comment by daniel-j-h** [comment]
Duplicate or splitted off from https://github.com/Project-OSRM/osrm-backend/issues/2211 ?
