### ISSUE TITLE
Response code 400 and code: InvalidUrl

### ISSUE THREAD

**Issue by tmpsa** [Project-OSRM/osrm-backend#2259]
I have compiled and installed osrm-backend on my Ubuntu 14 box, and created osrm files for Sweden. I believe it's done by the book. (cmake complained about libgdal and Doxygen, 'apt-get install libgdal-dev' silenced the first complaint).

My osrm-routed starts nicely, but a test request results in a response code 400!

Request:
http://lab.facilitylabs.com:5000/viaroute?loc=59.49046,18.05939&loc=59.4354,18.05546

Server console output:
13-04-2016 11:17:07 37.46.173.154 - Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0 /nearest?loc=52.4224,13.333086

Response:
{"message":"URL string malformed close to position 9: \"ute?lo\"","code":"InvalidUrl"}

What's wrong?
(I can leave our server available on port 5000 for a short while if it helps).

**Comment by daniel-j-h** [comment]
> (cmake complained about libgdal and Doxygen, 'apt-get install libgdal-dev' silenced the first complaint).

libgdal is only needed for the small components tool (see the demo server's layer, bottom left); doxygen is optional, too, and gives you some code docs primarily for development.

I guess you compiled from the develop branch? In that case, you're already getting the v5 API.

https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

`ute?lo` looks like you want to query the old API à la `viaroute?loc=..`. This won't work with the v5 API, resulting in exactly the error you see.


I recommend you switch to the v5 API. If you really have to use v4, check out the `pre5-api` branch.

**Comment by tmpsa** [comment]
Thanks! I got the source using
git clone https://github.com/Project-OSRM/osrm-backend.git

New API? Ok, so I tried 
http://lab.facilitylabs.com:5000/route/v5/driving?59.49046,18.05939;59.4354,18.05546

And got
{"message":"URL string malformed close to position 17: \"ing?59\"","code":"InvalidUrl"}

Try it yourself at http://lab.facilitylabs.com:5000

(The wiki page is not clear about correct value for {version}, and a few more working examples would be nice).

**Comment by daniel-j-h** [comment]
If you carefully read the v5 spec you will find the url format for queries to be

    http 'http://localhost:5000/route/v1/driving/7.416351,43.731205;7.420363,43.736189'

Example:

    http 'http://lab.facilitylabs.com:5000/route/v1/driving/59.49046,18.05939;59.4354,18.05546' | jq '.code'
    "Ok"

**Comment by daniel-j-h** [comment]
Closing here as not actionable for us. Your setup works, have fun! :rocket:

**Comment by tmpsa** [comment]
It appears that I unfortunately need the pre5-api branch. I'm not an expert on git, what the equivalent to the vanilla command 'git clone https://github.com/Project-OSRM/osrm-backend.git' ?

**Comment by daniel-j-h** [comment]
You can go here https://github.com/Project-OSRM/osrm-backend/tree/pre5-api and simply click on the "Download Zip" button at the right.

The same with Git:

    git clone --depth 1 --branch pre5-api https://github.com/Project-OSRM/osrm-backend.git
