### ISSUE TITLE
Collapse Turns / Remove Unnecessary Instructions

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2263]
To improve our OSRM guidance past 5.0, we want to remove unnecessary instructions and collapse some instructions into a single one.

Currently, I am thinking off the following cases (if you can think of more, please feel free to comment)

### Name Changes

 - [x] crossing a bridge - problematic scenarios: turn right after the end of a bridge? If its modelled strangely. Also turns on bridges could offer a challenge. https://github.com/Project-OSRM/osrm-backend/pull/2289
       - [x] test cases added
       - [x] scenario handled

 - [x] passing through a tunnel - problematic cases: same as a bridge. 
       - [x] test cases added
       - [x] scenario added

 - [x] segregated intersections - the roads in between can be modelled as part of any of the connected roads
       - [x] test cases added
       - [x] scenario handled

 - [x] name suffix - requires a list of known suffices in profiles 
       - [x] test case added
       - [x] scenario handled

Related: https://github.com/Project-OSRM/osrm-backend/issues/1811

### Collapsed Instructions

 - [x] u-turn at segregated intersection (possibly turn around at)
       - [x] test case added
       - [x] scenario handled

 - [x] roundabout turns - small roundabout (`radius <= 5` or similar), at most four connected roads. Report as `at the roundabout turn right/left`
       - [x] test case added
       - [x] scenario handled

## Pull Requests
 requires https://github.com/Project-OSRM/osrm-backend/pull/2327

**Comment by emiltin** [comment]
turning left/right at intersections on bike or foot. often this involves multiple small turns due to the way the intersection is modelled.

ex: https://www.ibikecph.dk/#!/x5lbg.7hk8y/x5kdu.7hmvq

**Comment by MoKob** [comment]
The wiki is updated, issue done.
