### ISSUE TITLE
URL string malformed

### ISSUE THREAD

**Issue by Humphaz** [Project-OSRM/osrm-backend#2265]
Hi,

I have built an Ubuntu 5.10 version of OSRM, everything works including frontend, the map is a full copy of Maryland in the US except.

My issue is the actual service, it runs and seems to be listening but always says the line is malformed.

e.g.

`localhost:5000/nearest?loc=39.135360,-77.110250`

Using the same code and point to the public API service:

`router.project-osrm.org/nearest?loc=39.135360,-77.110250`

Works fine.

The message I get back is:
`{"message":"URL string malformed close to positon 8: \"est?lo\"","code":"InvalidUrl"}`

I've delved into the code, even debugged, but the actual parser code goes all over the place so I'm not able to track it (I'm very rusty!).

Any help is appreciated, also the lend of a hat as I have now pulled all my hair out!

**Comment by TheMarex** [comment]
Which version are you running? `develop` as is current 5.0.0 RC2 which uses the [new API](https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api). The API query you posted is for `4.9.1` (we still haven't switched over the demo server, it supports both).

Your request would now be:

```
localhost:5000/nearest/v1/driving/-77.110250,39.135360.json
```

Notice the `lon,lat` order in contrast to previously `lat,lon`.

**Comment by Humphaz** [comment]
BRILLIANT!!!

Yes I was using v5, now returning results as expected, although plenty new information there.

I can not thank you enough for such a quick response, cheers Marex!

**Comment by Humphaz** [comment]
Is there a switch to get FrontEnd to use the new API methods?

**Comment by TheMarex** [comment]
No we didn't get around to port it yet. We first need to fix upstream leaflet routing machine. Glad this worked for you. :+1:
