### ISSUE TITLE
Support Left-Sided Driving

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2269]
This requires OSRM to be country aware. 

At the moment, we only support right-handed driving per default and assume it to be the general mode of driving.
This can result in broken instruction handling in left-handed driving countries.

When we get some sort of country-awareness into OSRM, we need to have a look at guidance and make sure to address left-handed driving.

**Comment by danpat** [comment]
@MoKob Can you list some specific examples?

**Comment by MoKob** [comment]
https://github.com/Project-OSRM/osrm-backend/blob/develop/src/extractor/guidance/roundabout_handler.cpp#L74 would be such a case.

**Comment by MoKob** [comment]
In general, when I noticed it during coding, I labeled the locations with `//FIXME` items

**Comment by willwhite** [comment]
In the case of the roundabout handler above, what would be broken? For example, would the guidance just say "turn right out of the traffic circle" instead of "turn left out of the traffic circle"?

**Comment by MoKob** [comment]
@willwhite the count for intersections is wrong in some cases. it may say take the first instead of the second. The angles themselves are independent of the side of driving.

**Comment by emiltin** [comment]
related: #333 #883

**Comment by miccolis** [comment]
@MoKob any sense of what follow up work will remain after https://github.com/Project-OSRM/osrm-backend/pull/4415 merges?

**Comment by MoKob** [comment]
I am not aware of many situations that actually change in left-sided conditions. We already have some roundabout-handling based on profile flags. This would need to be implemented on a `byCountryFlag` basis, rather than on global level. The main handling works, we just need to ensure the behaviour is adjusted based on countries, so we can have a single graph with both left/right handed driving.

Turn lane handling for roundabouts assumes right-sided driving. We currently have them disabled anyhow, though. When we redo them to work at all, we should take left-sided driving into account.
Other cases might be optimised for right-hand detection. The code requires a general overhaul though, which could be best done, after we have maneuvers in extraction, since lane handling on OSRMs data model is a game of chance right now.

With this flag, we would also be able to switch to a `TurnType::UTurn` and `DirectionModifier::Left\Right`. The main issue here is, that this would constitute a breaking API change, since it cannot be interpreted as a normal turn. A former uturn might suddenly be announced as a `Turn Left`.

**Comment by daniel-j-h** [comment]
Lane Anticipation:

https://github.com/Project-OSRM/osrm-backend/blob/11e7b6e911886feb5b05228b0817bcfc670630e8/src/engine/guidance/lane_processing.cpp#L193

and I came across a few comments sprinkled throughout the code base a while ago

https://github.com/Project-OSRM/osrm-backend/blob/288155ead07f0e26c2dc6777f4b8c27d9a9331e7/src/extractor/guidance/intersection_normalizer.cpp#L259-L260

https://github.com/Project-OSRM/osrm-backend/blob/5ece65cadef0e9b4534e82915a75ed16310c4b1b/src/extractor/guidance/turn_lane_handler.cpp#L279

**Comment by cmhh** [comment]
This is a massive issue for left-side driving countries (of which there are a lot!).  I'm trying to use the `trip` service to solve the TSP, and the results are unusable--the sorted order of the waypoints is essentially in the reverse order from what would be correct in most cases. I have set `approach` to `curb` for all waypoints, but the result has them all visited on the right-hand side of the road.  I could be missing something, of course?...

**Comment by danpat** [comment]
@cmhh OSRM now has basic support driving side.  The demoserver calculates driving side during pre-processing and returns it with routing results.

If you're running your own OSRM server, you'll need to add the `--location-dependent-data data/driving_side.geojson` flag to `osrm-extract` so that it performs the lookup for each road.

As noted above, there are probably still some corner cases around guidance, but the `approach=curb` property should work.

If you're seeing a specific problem, please open a new ticket with a recipe to reproduce the data you're using, a sample query, the results you're seeing, and the results you expect.

**Comment by cmhh** [comment]
Great!  I was looking down the barrel at doing this with ArcMap's Network Analyst (yuck), or implementing something bespoke myself.  I made a Docker image with this flag set and it seems to be working pretty well.

Thanks heaps.

**Comment by murphy-paul** [comment]
I've been trying to enable the above mention support for driving side on our OSRM service using the `location-dependent-data` but the response is still returned with driving_size = right. I've also tried this on the OSRM demo server and the result is the same. For coordinates in Ireland the driving side should be left

`curl --location --request GET 'http://router.project-osrm.org/trip/v1/driving/-7.700471878051758,52.35865823116153;-7.700697183609009,52.3519350813739?overview=full&steps=true&roundtrip=false&source=first&destination=last'`

I'm using docker to process the osrm files and run the routing engine. Commands I use are below. II'm using the latest docker builder (image id: d45a54a4bc52)

```
docker run --rm -t -v "${PWD}/data:/data" osrm/osrm-backend osrm-extract --location-dependent-data "/data/driving_side.geojson" -p "/opt/car.lua" "/data/britain-and-ireland-latest.osm.pbf"
docker run --rm -t -v "${PWD}/data:/data" osrm/osrm-backend osrm-partition "/data/britain-and-ireland-latest.osrm"
docker run --rm -t -v "${PWD}/data:/data" osrm/osrm-backend osrm-customize "/data/britain-and-ireland-latest.osrm"
docker run -t -i -p 5000:5000 -v "${PWD}/data:/data" --name osrm_test osrm/osrm-backend osrm-routed --max-trip-size 1000 --algorithm mld "/data/britain-and-ireland-latest.osrm"
```

The only way I could get driving_side to be left is to change the `left_hand_driving` of the profile to be true.

**Comment by danpat** [comment]
Looks like `driving_side.geojson` as messed up in commit 3c607a4570 - there should be `"properties": { "driving_side": "left" },` on each feature in that `.geojson` file.

Try adding `"driving_side": "left"` to the properties of each geojson feature in that file and see if it fixes your problem.

**Comment by murphy-paul** [comment]
That's it. That fixed the problem for me. Thanks again for the super fast response @danpat .

**Comment by danpat** [comment]
If you have time, a PR fixing the file in the repo would be appreciated!

**Comment by murphy-paul** [comment]
I don't have permissions is to push a branch. Do I need to do this on a fork @danpat ?
