### ISSUE TITLE
Nearest Way

### ISSUE THREAD

**Issue by Humphaz** [Project-OSRM/osrm-backend#2270]
Hi,

This is a feature request or maybe just a question.

I'm trying to get the nearest way when selected with a location, essentially returning a polyline if the actual way selected rather than an edge.

Is this possible?

**Comment by daniel-j-h** [comment]
The Nearest service only locates the nearest street segment, returning Waypoints.

https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#service-nearest
https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#waypoint

At the moment we discard OSM ids, so you have to do pre-processing yourself (e.g. by creating an RTree and doing nearest neighbour lookups based on the service's response).

There is an open ticket about exposing OSM ids here: https://github.com/Project-OSRM/osrm-backend/pull/2165

**Comment by Humphaz** [comment]
Thanks Daniel.

You guys are great on here, I feel bad it so long me replying!

I've found overpass-api, that gives me what I need for this, just I favour OSRM data as you have some pretty nice fixing of the network and road speeds. (expect to see similar comment again and again!)

**Comment by TheMarex** [comment]
Thanks for posting back. :+1: Closing.
