### ISSUE TITLE
Whole carriage ways

### ISSUE THREAD

**Issue by Humphaz** [Project-OSRM/osrm-backend#2271]
Hi,

This is a feature request or maybe just a question.

I would like to be able to identify whole carriage ways, e.g. I270 or A4 and have the whole of it returned as polyline or co-ordinates.

Is this possible or is it new?

**Comment by daniel-j-h** [comment]
> I would like to be able to identify whole carriage ways, e.g. I270 or A4 and have the whole of it returned as polyline or co-ordinates.

Maybe I'm not understanding you correctly, but this has nothing to do with routing. This is simply filtering an OSM extract based on tags. Or do you want to do post-processing based on routing results?

Please elaborate,

**Comment by Humphaz** [comment]
I find the OSRM data for roads far better than any other OSM data set derivative.

I was hoping to massage the speeds and names etc. back over the ways information from other OSM tools.

I'm relatively new to OSM and still finding my way, there are so many tools available to do so many different kinds of queries on the OSM sets, just wish they had less issues with the data.

Have/Will you ever look at creating an OSM update set, is there a way to link them so I can traverse OSRM but look up in OSM. I may be asking the same question from two different issues.

Apologies if I am, guess I'm a stumbling noob in this area!

**Comment by daniel-j-h** [comment]
You might be interested in our debug endpoint, showing the OSM road network but also the actual speeds OSRM sets for edges: http://map.project-osrm.org/debug/#12.21/52.5233/13.3987

**Comment by Humphaz** [comment]
That is great Daniel.

One thing I'm struggling with now is the differences between the OSRM and OSM ways, for example the I270 in Maryland, one of the main ways next to the clover leaf is huge, crossing over loads of intersections. I'm trying to get OSRM to give me the same kind of thing but with the correct ways.

My idea had been to use it to designate the significant points (intersections) and then use OSRM to pull out the smaller length.

Again, apologies if I'm sounding dim or missing something obvious, I promise to eventually start talking sense about GIS! and OSM!

**Comment by danpat** [comment]
@Humphaz if you're running your own OSRM server, the best way to get what I think you're after is to:

  1.  Modify the `car.lua` profile and append the `way.id` field to the `result.name`
  2.  Your route response will now contain all the way IDs that your route touches.  You can use something like the Overpass API to fetch all the tags for those way IDs.

This isn't something you'll be able to do with the OSRM demo server.

OSRM doesn't store all the tags attached to the roads.  We use the tags to filter out what roads are interesting for routing, but once that is done, the only things that are kept are the travel speed (either `maxspeed` tags or based on the `highway` type), the name (the `name` tag), the valid directions of travel (the `oneway` tag) and the coordinate data.  

This means that the response can't return all the other data attached to the ways, unless you do something tricky, like the suggestion above.

**Comment by Humphaz** [comment]
It is simpler or maybe more complicated than that. My requirement is to be able to pick ways as s poly line, but the issue is on the I270 a way on the main road goes for miles. Crossing loads of off and on ramps. 

I need to be able to select the highway between junctions .

I'd hoped that pan as it fixed for on of ramps could be a method of creating more sensible way results. 

I only need the name, speed and these divisions of long ways. 

I had an idea of extracting nodes which have no more edges than two (start and end) and build the ways from that. 

BTW, I owe you guys a keg never mind a pint!

----- Reply message -----

**Comment by danpat** [comment]
In OSM, a  real-world road can be made up of many ways.  Example:

http://www.openstreetmap.org/way/37320098

obviously, this motorway is much longer than that particular "way".

To obtain the whole geometry for "I270", you'll need to write custom code.  OSRM internally does something like this to calculate where to issue route instructions - we look for changes of name, changes of travel mode (e.g. driving->ferry).  But OSM itself has no strict way structure that guarantees you'll get everything.  There might be one small <way> that has a mis-spelled "name" tag.

You might want to look into OSM <relations>.  These are structures to groups <ways> so that you can fetch everything at once.  They don't exist for all data, but they might if what you're looking for are highways.  For example, here's the I270 relation:

http://www.openstreetmap.org/relation/1695584

**Comment by danpat** [comment]
@Humphaz One important note about relations: they're just groupings of ways.  This means that they're not necessarily a strict single line - there might be forks and loops included as well.  The most reliable geometry type would probably be something like a MultiLinestring, you can't assume you will have just two endpoints.

**Comment by daniel-j-h** [comment]
Closing this as not actionable for us.
