### ISSUE TITLE
Too many fork instructions

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#2272]
Often on long highway routes, I see a lot of consecutive "take a left/right at the fork" instructions usually intending to stay on one highway for a few miles. It seems like the real intent is to say "Take the ramp onto {way_name}, stay on until you reach the fork for {new highway}". 

Could this optimization be made in osrm-backend, without needing more data?

cc @MoKob @daniel-j-h

**Comment by MoKob** [comment]
@karenzshea what dataset are you using this on? A highway fork usually is only emitted if there are two motorways leaving at a motorway intersection. To suppress a turn on two motorways is something we could do on the backend, but would end up making actual highway crossings less clear.

In most cases, this should be a data issue.

**Comment by MoKob** [comment]
In personal conversation from chat: turned out it really was a data issue.
