### ISSUE TITLE
Snapping to motorways may not always be reasonable

### ISSUE THREAD

**Issue by tuukkapuranen** [Project-OSRM/osrm-backend#2277]
This may be related to or duplicate of #930, #1749, and #1796, and may be possible to resolve with existing mechanisms, but I could not yet find a way.

When considering the nearest route to snap to, is it possible to define that a profile that is allowed to _use_ certain way, should not _snap_ to it? Here is an example of a reasonable snapping near a motorway:

http://map.project-osrm.org/?z=17&center=39.092445%2C-77.174857&loc=39.091433%2C-77.174406&loc=39.094252%2C-77.174701&hl=en&alt=0

![image](https://cloud.githubusercontent.com/assets/5907626/14606243/f4317818-0584-11e6-93e8-3890e5cbc403.png)

And here is the result with slightly different coordinates:

http://map.project-osrm.org/?z=17&center=39.092445%2C-77.174857&loc=39.091458%2C-77.174578&loc=39.094252%2C-77.174701&hl=en&alt=0

![image](https://cloud.githubusercontent.com/assets/5907626/14606263/0e3fa626-0585-11e6-8041-768a017cb597.png)

This may be reasonable if we assume that the vehicle is on the motorway and traveling, but perhaps not if we are at the parking lot that happens to be near a highway. Also, I am not sure if the direction hint helps in this case. Is there, for example, a way to define a minimum velocity hint required to snap to a specific highway class? If not, what would be the best approach to handle these kind of cases?

**Comment by TheMarex** [comment]
We already have this for `ferry`s:

https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/car.lua#L463

You need to set `result.is_startingpoint = false` for highways if you don't like that behaviour.

The reason we allow highways is that we don't know when someone switches on his or her navigation device. The might actually be in the middle of the motorway.

For influencing snapping behavior there are two parameters is the [new API](https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api).

- `bearings`: Set directions of movement as bearing for the start point. This is a filter parameter so make sure the range you allow is enough to capture inaccuracies.
- `radiuses`: The search radius in meter. You should limit this if you know your location is within certain precision bounds (like 100 meter)

**Comment by tuukkapuranen** [comment]
So `result.is_startpoint = (result.forward_mode == mode.driving or result.backward_mode == mode.driving) and highway ~= "motorway_link" and highway ~= "motorway"` should do the trick when we know the car is parked on the parking lot?

It's true that the vehicle can also be on the motorway. For handling both cases, can we use `radiuses` to control the snapping distance per highway type? That is, snap to motorway, say, when within 5 meters, and snap to other roads when within 100 meters?

**Comment by daniel-j-h** [comment]
Take a look at the `radiuses` and `bearings` description here:
https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#general-options

You can set both on a **coordinate-by-coordinate basis**.

I think it could be worthwhile to try using the Nearest service to first snap to N street segments (playing with `radiuses` and `bearings`):
https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#service-nearest

The Nearest service then returns you locations, distance and names.
https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api#waypoint

Then do a single asymmetric Nx1 Table service request from all N locations to your destination and see how responses vary.

**Comment by tuukkapuranen** [comment]
Great, thanks!

> Then do a single asymmetric Nx1 Table service request from all N locations to your destination and see how responses vary.

Come to think of it, one way could be simply querying N nearest and then choosing the result based on the waypoint properties. However, as the waypoint has no type information for the underlying road, and choosing by name may be difficult, as you say, we most likely have to make an additional table query to see which kind of road we snapped to. I have to think how to best interpret the Nx1 table results, I'm not yet sure how to robustly choose the appropriate road based on this information.

**Comment by daniel-j-h** [comment]
I'm closing this as not actionable for us. There is also https://github.com/mapbox/route-annotator that could give you arbitrary tags based on a route, so you can do additional tag-based lookups.
