### ISSUE TITLE
Suppress `mode: movable bridge`

### ISSUE THREAD

**Issue by bsudekum** [Project-OSRM/osrm-backend#2278]
> "Continue straight on I-95 over the bridge"

Telling the user they are going to go over a bridge seems redundant. Ideally, any event `mode: 'movable bridge'` would be removed from the response. 

/cc @MoKob @karenzshea @TheMarex

**Comment by MoKob** [comment]
These mode changes are a profile decision. Its less a decision to suppress it but to configure the profile to supply reasonable modes for the driving part. I guess bridges are among the first to consider here as a mode not to emit.

**Comment by TheMarex** [comment]
I think we should just remove it as a mode of transportation. IMHO bridges don't really qualify as such.
