### ISSUE TITLE
Route description should include motorway junctions

### ISSUE THREAD

**Issue by joakimfors** [Project-OSRM/osrm-backend#228]
It would be nice if the route description included some indication when turning of from a motorway or other high level highway on to a link road.

e.g.

http://map.project-osrm.org/jF
http://map.project-osrm.org/jG

Something like "Keep right" instead of "Continue". If there's a highway=motorway_junction tag on the junction node then it could display the name or ref. Don't know how hard it is to detect such junctions if they are not motorway junctions. Perhaps support for hinting with junction=yes on the connecting node would be a solution?

**Comment by 1ec5** [comment]
In [this example](http://www.openstreetmap.org/directions?engine=osrm_car&route=37.3547%2C-121.9119%3B37.3453%2C-121.9067#map=16/37.3500/-121.9085), OSRM says to continue down two unnamed roads. [MapQuest](http://www.openstreetmap.org/directions?engine=mapquest_car&route=37.3547%2C-121.9119%3B37.3453%2C-121.9067#map=16/37.3500/-121.9084) does a much better job, saying “Take the Taylor Street exit, EXIT 7,” then “Keep right to take the ramp toward Taylor Street West.” Highway exit information in OSM can be [very nuanced](http://wiki.openstreetmap.org/wiki/Exit_Info), but MapQuest shows that merely considering `ref` on `highway=motorway_junction` nodes and the name of the following way can greatly improve the turn instructions.

**Comment by TheMarex** [comment]
This is implemented in the v5 API.
