### ISSUE TITLE
Reading Names File

### ISSUE THREAD

**Issue by Humphaz** [Project-OSRM/osrm-backend#2280]
HI (again),

I'm trying to parse the names file output from the extractor, but it just isn't making sense.

When I look at the length offsets they are huge in comparison to the names, the positional jumps seem huge.

I've looked through the code and I see that it is referring to blocks rather than characters but still seems a weirdly large jumps.

e.g.

`db 0f 00 00 6a af 0f 00 00 00 00 00 f8 00 00 00`

From, this I discern that there are `0x0fdb` names in the list which have a total size of `0x0faf6a` and the firs is at `0x0` the second text is offset `0xf8` (the next is `0x01e8)` which is saying that the first element is 248 long, the second is 240, the 246 etc.

What glaringly obvious thing am I missing.

Thanks in advance.

**Comment by Humphaz** [comment]
Thanks Daniel,

I guess I'm going to have to create my own C++ based on osrm_extract, I suppose at that point at least I have all the data sets available from OSM to all of the OSRM ones too.

More work but will probably end up far more powerful.

It all comes back to (at the moment) needing to be able to pull out a sensible section of road that unfortunately doesn't correlate to ways or routes or anything really.

**Comment by daniel-j-h** [comment]
> It all comes back to (at the moment) needing to be able to pull out a sensible section of road that unfortunately doesn't correlate to ways or routes or anything really, its a logical section of road between points of interest (junctions/ramps).

I don't know what you mean by "sensible section of the road" but maybe you're interested in @danpat's

https://github.com/mapbox/route-annotator

then. I wrote some Node.js bindings and an Express.js server the other day.

https://github.com/mapbox/route-annotator/blob/master/example-server.js
https://github.com/mapbox/route-annotator/blob/master/src/nodejs_bindings.hpp
https://github.com/mapbox/route-annotator/blob/master/src/nodejs_bindings.cpp

With it you can get all tags for a list of node ids or coordinates, e.g. to annotate a route.

**Comment by TheMarex** [comment]
Closing here as not actionable.
