### ISSUE TITLE
Ability to only compile osrm-routed

### ISSUE THREAD

**Issue by noblige** [Project-OSRM/osrm-backend#2283]
Currently CMake configuration does not provide for ability to only compile osrm-routed without other tools and extra dependencies.
Use case scenario: running osrm-routed on an embedded device and having maps compiled on the host.

**Comment by danpat** [comment]
@noblige If you're building for an embedded device, wouldn't you just copy `osrm-routed` over to the target device after it's built with a cross-compiler on the host?

**Comment by noblige** [comment]
@danpat Yes, problem is that I can only compile whole osrm-backend currently (including osrm-extract, contract, etc) - which requires whole bunch of libraries (which I will also have to cross-compile, along with their dependencies).
Just osrm-routed (as far as I can tell) only requires STLXX and Boost.

I'm currently hacking CMakeList.txt to do that, but would be nice to have this option in mainline.

Hope that clears things up. Thanks!

**Comment by daniel-j-h** [comment]
> Use case scenario: running osrm-routed on an embedded device and having maps compiled on the host.

Fair warning: please read this and the linked tickets before you run into this yourself: https://github.com/Project-OSRM/osrm-backend/issues/2242

**Comment by noblige** [comment]
implemented in https://github.com/Project-OSRM/osrm-backend/pull/2503 (`-DROUTED_STANDALONE=ON`)

**Comment by daniel-j-h** [comment]
Stale.
