### ISSUE TITLE
Additional Data For Guidance

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2284]
To enable the support of visual indicators (https://github.com/Project-OSRM/osrm-backend/issues/2267) and turn lanes (requires separate issue), we have to store additional data in OSRM and push it through the pipeline. Possibly, we also have to handle intersection classes, which will be part of another issue (needs to be opened).

### Sign Indicators
 
Sign indicators can be seen as one of two types:

 - motorway ramps
 - everything else

Motorways ramps don't have dedicated names, and even if they should, the sign is what people use to follow them. We can handle motorway ramps transparently by storing the name of the exit with the ramp itself.

Everything else is a small set of possible signs. For these, we have `#signs << #roads`. For such datatypes, we have to implement a dedicated small dataset storage.

### Small Dataset Storage

We can handle a small set of data, that is not part of most edges, using a sorted storage. Usually, a `hash-map` would be the ideal type, but it wouldn't mix with our `SharedMemoryDatafacade`.
This storage would consist of a sorted list of pairs `<EdgeID,DATA_TYPE>`. Using BinarySearch, we can look-up the data on demand.
To avoid the costly look-up for most edges, we have to store a single bit with the `EdgeBasedEdge` to indicate whether such a look-up is required.

### Lane Guidance

For turn lanes, we will most likely have to increase the edges by a small index into a look-up table.
For every turn lane combination `lane a_i,a_i+1.. -> lane b_j,b_j+1,...` (including multiple possible turn lanes to take at a road), we have to store an ID with the edge-based edges.
Such a turn lane information would contain a tupel `(number_of_lanes_in_turn,first_lane_of_in_road,first_lane_of_out_road)`, numbering the lanes from right to left. The hope is to have the number of these limited by at most 256 of these. But at the most we should be limited by two bytes per edge.

### Intersection Classification

For the intersection classification we see two possible outcomes:

A) Dedicated API. Using the exposed node ids (https://github.com/Project-OSRM/osrm-backend/issues/2054) we could use the route-annotator to post-annotate the route on demand.
This would require a synchronisation between the annotator and OSRM and a dedicated service.

B) We add an intersection class to every node (probably in the order of two bytes). Together with a normal look-up table in the datafacades, we could annotate the route in OSRM itself.

Since turn classifications can reduce ambivalences in guidance quite considerably, I would prefer option B.

## Overheads

In total we end up with the following overhead, when we implement all of these features:

 - signs and indicators: a few MB for the strings/small dataset storage and an additional bit per edge
 - turn lanes: two byte per edge for the lookup-table index, a few MBs for the table itself
 - intersection classification: two byte per node + few MBs (<100MB) for the data itself.

## Next Steps

Decide between option A) and B) for intersection classification. Open dedicated issues for the intersection classification and turn lanes and update https://github.com/Project-OSRM/osrm-backend/issues/2267 accordingly for the data tasks.

**Comment by emiltin** [comment]
is intersection classifications things like 4-way, T, etc? or something else?

**Comment by MoKob** [comment]
@emiltin no, it is a list of available turns, discretised to a certain degree with attached further information. What kind of information is something we have to figure out, yet.
Given such information, a GUI could supply a visual representation of the intersection, distinguishing between very similar turns.

**Comment by emiltin** [comment]
ok, so a way to compress info about geometric layout of the intersection?

**Comment by MoKob** [comment]
It will most likely be more than just the geometric layout, but for starters, you could imagine it this way.

**Comment by MoKob** [comment]
Opened https://github.com/Project-OSRM/osrm-backend/issues/2296 and https://github.com/Project-OSRM/osrm-backend/issues/2295 for further discussion. @daniel-j-h when you have updated https://github.com/Project-OSRM/osrm-backend/issues/2267, you can close this intermediate ticket.

**Comment by TheMarex** [comment]
These discussions can now happen in the corresponding specific tickets. Closing here for now.
