### ISSUE TITLE
Error extracting map data

### ISSUE THREAD

**Issue by Vortec4800** [Project-OSRM/osrm-backend#2288]
I'm getting an error when trying to extract the NA maps.

I created a link from car.lua profile.lua. I also created a link to the /profiles/lib/ directory.

I run the osrm-extract command and I get this error:

```
[info] Input file: north-america-latest.osm.pbf
[info] Profile: profile.lua
[info] Threads: 8
[info] Using script profile.lua
[STXXL-MSG] STXXL v1.4.1 (prerelease/Release)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
[info] Parsing in progress..
[warn] ERROR occured in profile script:
profile.lua:132: attempt to index a nil value (global 'properties')
[STXXL-ERRMSG] Removing disk file: /var/tmp/stxxl
```

Any ideas what would cause this error? I'm on OS X and I'm using the binaries downloaded using the npm module.

**Comment by danpat** [comment]
@Vortec4800 It looks like you're using old profiles with new OSRM binaries.  You don't mention which actual version you're using, but I suspect it's 5.0-rc2 ?

Profiles from older OSRM releases won't work with the new 5.0 series binaries.  There have been some new required variables added (including the `properties` object mentioned in your error output).

You can grab the latest profiles here that will work with a 5.0 series node module:

https://github.com/Project-OSRM/osrm-backend/tree/develop/profiles

**Comment by Vortec4800** [comment]
Great, thanks. I was using the profiles from what I thought was the latest in Github, perhaps I was on the wrong branch or something by mistake.

Here's another odd question... how do you know if it's working? It says Parsing in progress, but then it seems like it doesn't progress. The log file doesn't get any additional entries, and while I see the stxxl file created in the tmp directory it doesn't seem like it's getting any changes written to it. I also don't really see any CPU or disk activity. It's been sitting at this prompt for a couple hours now and I'm not sure what to try.

**Comment by danpat** [comment]
@Vortec4800 you should see lots of disk and/or CPU activity.  If not, something isn't right, but it's hard to say what without details.

**Comment by Vortec4800** [comment]
Hmm. Any suggestions on the best way to try and debug this?

**Comment by danpat** [comment]
@Vortec4800 the usual next step is to try using a Debug build of OSRM.  The debug builds have a bunch of extra checks built in and will usually catch weird stuff.

You can *try* attaching to the running/hung process with a debugger and see where it's stuck.

Do:

`gdb -p $(ps -eaf | grep osrm-extract | awk '{print $2}')`

then enter `bt` to get a backtrace.  Paste that output here, maybe we can get something out of it.  It might not be useful, as the Release builds are missing lots of useful information for debugging, but maybe we'll get lucky.

Another thing you can try is run `osrm-extract` with `--threads 1`.  If there's some kind of multi-threading deadlock, this should avoid it, at the expense of only using 1 CPU at a time.
