### ISSUE TITLE
table_parameter_grammar.hpp does not compile on 32-bit linux

### ISSUE THREAD

**Issue by noblige** [Project-OSRM/osrm-backend#2290]
Can someone more versed in boost and c++11 look into this?
`gcc 4.8.4` + `libboost1.54` on i686:

[err.txt](https://github.com/Project-OSRM/osrm-backend/files/230491/err.txt)

**Comment by danpat** [comment]
@noblige looks like this is tripping you up your build:

https://github.com/Project-OSRM/osrm-backend/blob/develop/include/server/api/table_parameter_grammar.hpp#L33

For GCC, we could add a test for  `__x86_64__` there to work around this.  AFAIK, there's no portable flag, so we'd need to find one for `clang` as well.

**Comment by noblige** [comment]
@danpat Thank you for pointing me to the right direction, here's my fix, take a look if it makes sense:
```
diff --git a/include/server/api/table_parameter_grammar.hpp b/include/server/api/table_parameter_grammar.hpp
index 00fe703..32e559e 100644
--- a/include/server/api/table_parameter_grammar.hpp
+++ b/include/server/api/table_parameter_grammar.hpp
@@ -31,7 +31,12 @@ struct TableParametersGrammar final : public BaseParametersGrammar
             parameters.sources = std::move(sources);
         };
 // TODO: ulonglong -> size_t not only on Windows but on all 32 bit platforms; unsupported anyway as of now
-#ifdef WIN32
+#if defined(__SIZEOF_SIZE_T__) && (__SIZEOF_SIZE_T__ == 4)
+        destinations_rule = (qi::lit("destinations=") > (qi::uint_ % ";")[set_destiantions]) |
+                            qi::lit("destinations=all");
+        sources_rule =
+            (qi::lit("sources=") > (qi::uint_ % ";")[set_sources]) | qi::lit("sources=all");
+#elif defined(WIN32)
         destinations_rule = (qi::lit("destinations=") > (qi::ulong_long % ";")[set_destiantions]) |
                             qi::lit("destinations=all");
         sources_rule =
```

**Comment by oxidase** [comment]
Hi, please check if dac2f93 fixes the issue. I added a condition to use `qi::ulong_long` only if `BOOST_HAS_LONG_LONG` is defined and `std::is_same<std::size_t, unsigned long long>::value`
otherwise it falls back to `qi::ulong_`.

**Comment by noblige** [comment]
@oxidase I can compile `master` now on i686. thanks!
