### ISSUE TITLE
Intersection Classifications

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2295]
Currently, some turn instructions might be unclear on complex intersections.

If multiple possible turns exist that similar to each other. A possible example would be taking a right turn at this intersection.

<img width="149" alt="screen shot 2016-04-22 at 12 42 29" src="https://cloud.githubusercontent.com/assets/12932279/14739436/c2505d40-0887-11e6-971e-0ae5b85cf6de.png">

Even if we could distinguish them, saying `right` and `sharp right`, the same could be done with `right` and `slight right` as well as `sharp right` and `slight right`.

This ambiguity indicates a reason to augment turns with intersection classifications.

In a first step, this classification should contain a list of available turns at the location, as well as an indication of they are possible turns or not. In combination with the in/out bearings, we could enable a front-end to supply an improved visual representation of the turn itself and what roads are the ones that participate in it.

The resulting representation of the intersection could be used to generate Turn Symbols:
![representation](https://cloud.githubusercontent.com/assets/12932279/15011877/9485ad2c-11f4-11e6-9372-ab68d2128dcd.png)

The output for this turn could look like this:

```
"maneuver":
 {
    type: turn,
    modifier: right,
    bearing_before: 90,
    bearing_after:  130,
    location":[xx.xxxx,yy.yyyy]
    intersection:
   {
      out_bearing: 135,
      connections: [ 
       {
         entry_allowed: true,
         bearing: 45
       },
      {
         entry_allowed: true,
         bearing: 90
       },
       {
         entry_allowed: true,
         bearing: 135
       },
       {
          entry_allowed: true,
          bearing: 225
       },
       {
         entry_allowed: false,
         bearing: 270
       }
    ]
}
```
The discretisation results in differences between `intersection:out_bearing` and `bearing_after` would be a result of discretization.

We could also imagine giving out angles and normalising the output to the direction of travel (always have a 0-angle for the u-turn and all discretised turn_angles instead of the bearing values).
This would represent the view of the intersection a driver would actually have.

The Implementation requires the following tasks:

 - [x] classify all turns during preprocessing. This has to be done prior to the merging of segregated roads. Initial classification should consist of
   - [x] available roads and their bearings
   - [x] allowed entry flag

 - [x] add the classification ID to all intersections (if it turns out that keeping contracted nodes results in more nodes than ways, we should consider storing it with the edges).

 - [x] report intersection data in the API

 - [x] with the changes to the API as described in https://github.com/Project-OSRM/osrm-backend/issues/2295#issuecomment-216895155, the cucumber tests need to be updated for the new format

**Comment by emiltin** [comment]
in relation to allowed entry, keep mode changes in mind, e.g. you might not be able to bike, but still push the bike, or take a ferry

**Comment by MoKob** [comment]
A few initial findings.

A discretisation with about 15 degrees (360/24) seems like a reasonable choice. Smaller degrees result in a rather large number of possible entry/exit combinations. As far as my extraction of north america got, using 15 degrees results in already ~6300 different turn angle combinations and 202 possible variations of entry/exit flags.

**Comment by MoKob** [comment]
So I am able to push intersection data in form of bearings and entry-flags through the pipeline.
What we need is to decide on a valid format to expose the intersection data.

I would propose to add an intersection section to every step:

```
[intersection] = {[entry_allowed] = true | false; [angle] = discrete_angle;}^+;
                         [out_angle] = discrete_angle; 
```

This would replicate the turn-angle technically, but would take the load of finding the correct road off the client.

Collapsed instructions are kind of difficult for these situation. In this case we could go for an array of these items? Opinions?

/cc @TheMarex @daniel-j-h @freenerd @karenzshea

**Comment by freenerd** [comment]
`out_angle` is the same as `bearing_after`? If yes, we could remove `out_angle`?

What is the use case for `entry_allowed`?

Can you give examples of how you imagine this would look to the end user when implemented for example in a mobile app? Would this aid with overlays over a map or be used to show turn instructions symbols? How would `entry_allowed` be shown there? Would love to see some simple drawings, ideally with examples of `intersection` object payload and how it would be visualized then.

**Comment by 1ec5** [comment]
> Would this aid with overlays over a map or be used to show turn instructions symbols?

Certainly this kind of information would be required for showing a turn instruction symbol that includes other ways, like Apple Maps does:

![apple](https://cloud.githubusercontent.com/assets/1231218/15009796/5e10ad2a-119d-11e6-8512-38cab4e6ffcc.png)

> Collapsed instructions are kind of difficult for these situation. In this case we could go for an array of these items?

How is https://github.com/Project-OSRM/osrm-backend/pull/2116#issuecomment-199808578 currently exposed? If two maneuvers are collapsed into one, would either be included in the `intersections` field described in that comment? If not, I think the client would somehow need the coordinates of all the collapsed maneuvers in order to display turn arrows either on the map or separately.

**Comment by MoKob** [comment]
@freenerd bearing_after sadly is a bit different, since we discretize angles. So bearing in response and this bearing do not match.

The symbol is what I am aiming for (and looks way better than my current drawings).
For some intersections the information about possible entry can be used to simplify the intersection.
I am thinking of stuff like:

<img width="589" alt="screen shot 2016-05-04 at 11 21 09" src="https://cloud.githubusercontent.com/assets/12932279/15010113/b6385bfe-11ea-11e6-9c6e-ef4aa9f67afa.png">

Using smaller roads, other colors, dashing... I am not a designer but there are possibilities to use it.

**Comment by MoKob** [comment]
@1ec5 currently  #2116 data is only exposed as exit numbers. Its quite a long list of potential data.
We need to decide on a good format here as well. Most instructions should handle these intermediate intersections correctly, at least.

**Comment by MoKob** [comment]
©️ @freenerd (from chat) a possible example would be:

```
bearing_after: 300,
intersection: {
  out_angle: 315,
  [ 
    {
      entry_allowed: true,
      angle: 315
    },
    {
      entry_allowed: false,
      angle: 285
    }
  ]
}
```

The matching of 300 to 315/285 is not trivial and is best be done in the backend. Therefor we would require the additional out_angle to make sure we get the correct representation.

**Comment by zugaldia** [comment]
@MoKob If I understand this correctly, with this ^^^ proposal you'd only expose the two possible right turns, indicating with `true` the one the user needs to take, but you wouldn't expose other ways in the intersection, is that right? In the OP I could see two more ways in the map.

I think we should expose all ways at the intersection to be able to eventually provide the visual cues @1ec5 shows in https://github.com/Project-OSRM/osrm-backend/issues/2295#issuecomment-216805748.

**Comment by MoKob** [comment]
@zugaldia I added some clarifications to the initial post on the ticket. The aim is to expose all available bearings or turn angles. The `true/false` indicates whether a turn would be allowed. This can be used to highlight them in a different way in the turn angle.

**Comment by TheMarex** [comment]
```
"intersections": [{
      "bearings": [45, 90, 135, 225, 270],
      "entry": [true, true, true, false]
      "in": 1,
      "out": 2
}],
"maneuver":
 {
    "type": "turn",
    "modifier": "right",
    "location":[xx.xxxx,yy.yyyy]
}
```

- Remove `bearing` fields (breaks API)
- Add array `intersections` that contains all intersections traversed by a step
- The maneuver always happens at the _first_ intersection no referencing needed

If this is still too big (we need to measure this!) we need to move to a different format that looks more like this:

```
"intersections": [{
      "type": "5_10_3"
      "in": 1,
      "out": 2
}],
"maneuver":
 {
    "type": "turn",
    "modifier": "right",
    "location":[xx.xxxx,yy.yyyy]
}
```
Were we apply dictionary encoding on the data.

**Comment by MoKob** [comment]
> Add array intersections that contains all intersections traversed by a step

@TheMarex the current discussion is on a single intersection and the available bearings. Do I understand you correctly that you want to add

```
"intersections": [{
      "bearings": [45, 90, 135, 225, 270],
      "entry": [true, true, true, false]
      "in": 1,
      "out": 2
},
[{
      "bearings": [90, 180, 270],
      "entry": [true, true, true, false]
      "in": 0,
      "out": 1
}]
```
To every step?

**Comment by TheMarex** [comment]
To total `RouteStep` object would look like this:

```
"distance": 10,
"duration": 20,
"geometry": "_abhsad",
"mode": "driving",
"name", "Hauptstraße"
"intersections": [{
      "bearings": [45, 90, 135, 225, 270],
      "entry": [true, true, true, false]
      "in": 1,
      "out": 2
}],
"maneuver":
 {
    "type": "turn",
    "modifier": "right",
    "location":[xx.xxxx,yy.yyyy]
}
```

**Comment by MoKob** [comment]
It turns out that we can find some scenarios that are difficult to handle using any discretisation of available turn-angles.

A possible example is located here: http://www.openstreetmap.org/search?query=33.84896%20-118.284773#map=19/33.84896/-118.28477

<img width="134" alt="screen shot 2016-05-09 at 14 45 43" src="https://cloud.githubusercontent.com/assets/12932279/15113481/d773a13a-15f4-11e6-9ae9-5938c20081b4.png">

The turn angle between the two exiting motorways is just three degrees. If we want to expose these intersection shapes (and the angle can get even smaller), we have to find a way to handle these subtle differences between turns.

The number of these turns on California - Data is within the low hundreds.

Currently I see three ways of handling this:

1) Don't handle these differences. If such differences arise, simply ignore both ways and use the generated instruction to build a symbolised version of the intersection.
This would fail in cases like:
![not-possible-ignore](https://cloud.githubusercontent.com/assets/12932279/15113706/3376c5f6-15f6-11e6-91f1-87d9f74c5326.png)
since we don't know anything about other left-turns.

But it would work on forks, handling the most prominent cases like motorways/ ramps in a reasonable way:
![fork](https://cloud.githubusercontent.com/assets/12932279/15113829/e7747260-15f6-11e6-813a-898ccfef12e3.png)
(intersection; straight, fork right, fork left, sharp right-coming from the top)

It would be unnecessarily complicated to handle anything but normal forks on highways. The forks/exits on highways should be the most prominent though.

2) Don't discretise on these turns. Would require 360 bit per intersection if we store a bit per angle or approximately 4 * 9 Bit + 8 bit per intersection class + 4 Bytes per intersection to store the intersection ID (these are currently used anyhow, so the overhead would the data to store the intersection classes).
The in my view cleanest solution would work in any case. Due to data types we would probably have to use short and store approximately 5 shorts per type.

3) Use intersection classes with discretised entries, but store them with turns instead of intersections. In this case we would end up with four bytes per edge instead of  four bytes per node. Here we could easily find a approximated representation that is designed to represent the intersection in relation to the actual turn.

For the fork, this would look like this:
![fork-at-turn](https://cloud.githubusercontent.com/assets/12932279/15114346/cfadf63a-15f9-11e6-8bd8-7a5df75cb909.png)

The problem with this approach is that we have to make sure that the actual bearings at the turn can be matched to the correct road of the representation. This could result in very inaccurate representations. In the example, going nearly straight would result in a turn representation. In addition, the memory overhead is an argument against the approach.

Opinions?

**Comment by emiltin** [comment]
what about discretising them and then use the ordering to show exits that are on the same degree?
ie two existing motorwats might be 2 degrees apart, and will get the same angle. but the ordering can be used to show using a default angle like 3 degree, in the right order?

**Comment by MoKob** [comment]
@emiltin does not change the storage requirements, since we need a way to store angles of identical degree. Doing so we cannot use a bitfield of fixed size and have to use a storage like b).

The ordering is also something we cannot get from other information in the data. We only can find out about the bearing of a given turn, not about anything else at the intersection.
Turns themselves to not know about the full intersection.
If we have an ambiguous turn, the bearings don't tell us if its the first, second, or third possible one. The moment we cannot match the bearing to a discretised angle in a unique form, we cannot handle these assignments.

The available information at a turn is restricted to previous node, current node and next node as well as the geometry along the path. In addition we know the turn-instruction that was calculated using the full intersection.
We have to base our assignment/classification operation purely on this set of data.

**Comment by emiltin** [comment]
ok, so we only have the angles of each way. but can't the angles be used to order them clockwise?

e.g. say we have unordered way angles [a=133, b=49, c=130, d=244]. discretised to nearest 10 degree and ordering we get [b=50, c=130, a=130, d=240]. the front-end can then display ways with the same 
angled spread out using a small default angle, like [b=50, c=128, a=132, d=240]

btw, can't the entry way be removed if you normalize other ways according to the entry angle? the entry angle into the intersection is provided elsewhere?

**Comment by MoKob** [comment]
@emiltin well, we have the angles during classification, not during query times.

In your example, we I get an angle of 133 during query time, I don't know whether it is the first or the second one. So I can give a picture of the intersection but I cannot say which ones of the available turns I am taking.

Given a setting like this, we would end up with a discrete representation on like on the right side.
![unclear-match](https://cloud.githubusercontent.com/assets/12932279/15116467/c297f46e-1603-11e6-910d-bb41015adba8.png)
If I find a bearing during query time that is not exactly the one given, I cannot say which of the outgoing edges I would draw is actually the one that represents the turn.
To find the correct one, I need a 1:1 mapping between what is drawn in the turn-symbol and the single angle I know of at query time.
Remember that the problem is not the classification itself but the mapping at query time where I only know of a single bearing, the outgoing bearing at the intersection. In your example, I would get an angle of 133 for a. But how do I know that `a` is the second one of the two 130's? It could be 133 and 135 that resulted in 130,130.

**Comment by emiltin** [comment]
ok. i was thinking the discretisation happened at query time. so my idea requires storing the full angles, corresponding to your option 2 above.

if you want to only store the discretised angles to save save, what about storing the order separately, but only do it in case there are ways with the same discretised angles? you don't even need any bits to indicate wether order data is stored, since it's implied when two ways have the same angle.

ex [a=123, b=49, c=130, d=244]:
discretised to [b=50, c=120, a=130, d=240]
=> no need to order data, order is implied by angles since that are all unique

ex [a=129, b=49, c=130, d=244]:]
discretised to [b=50, c=130, a=130, d=240]
=> need to store order for c and a since they have the same discretised angles: [a,c]


at query time, we fetch:
[b=50, c=130, a=130, d=240]
 since c and a have same angles we look up the order data for the intersection which is [a,c]. this is used to reshuffle the ways to get:
[b=50, a=130, c=130, d=240]
optionally we spread ways with the same angles to something like:
[b=50, a=128, c=132, d=240]

**Comment by MoKob** [comment]
As long as I am storing angles, the additional order will only introduce an additional level of complication.

My current approach to reduce the number of intersection classes as best as possible while still allowing correct results is closely based on b).

Consider a desired discretisation in steps of 10 degrees and the intersections:

`A = [a=45, b=55, c=187, d=274],  B =  [a=49, b=52, c=181, d=274], C = [a=41, b=49, c=57, d=187, e=274]`.

Discretised they would yield: `D(A) = [a=40, b=50, c=180, d=270], D(B) = [a=40,b=50,c=180,d=270], D(C) = [a=40,b=40,c=50,d=180,e=270]`

Instead of trying to fit C into the classes, we can store a class of higher resolution for `C`, using `D(C) = [a=40,b=45,c=50,d=180,e=270]`.
As long as we make sure every bearing of an actual intersection is closest to exactly one of the discrete angles, we can match them back correctly.
This way I will not have to introduce an additional concept of ordering vertices, counts of how many conflicting angles there are.
A and C will continue to share an intersection class, C will get its own, without any conflict handling.

**Comment by MoKob** [comment]
Small update on this approach: without any optimisation to use smaller discretisation on conflicting classes, using a full representation in degrees and a discretisation in steps of 15 degrees whenever possible, we get 17015 intersection classes, instead of 510229 for a general full representation on California.

For two intersections 'a=12, b=17, c=37` and `a=12,b=22,c=37` and a discrete step size of 10, we get intersections `a=10, b=10, c=30` which is in conflict and stored as full resolution: `a=12,b=17,c=37` as a result. The second discrete representation is `a=10,b=20,c=30` and not in conflict. As a result we use the discretised class.

This approach provides a reduction in the number of classes by a factor of 30. The amount of memory stored on disk is largely dominated by the IDs we have to store for every node/edge, though.
Therefore the file-size to store the data only reduces from 59 to 45 MB.
For the moment, I would argue that data like USA will result in few enough similar intersection classes that is justifies not to explore a multi-level discretisation, resolving conflicts with lesser and lesser step sizes, until the conflicts are resolve.

Given a step size of 10, we could theoretically discretise `a=12, b=17,c=37` to `a=10, b=10,c=30` and resolve the conflict to `a=10,b=15,c=30` (c remains at step size 10, only a,b use step-size 5, since they are in conflict). This way we could find a few additional equal classes, the expected benefit does not justify this additional overhead in my view.

**Comment by MoKob** [comment]
Currently I am able to output the intersections as partly discretized, partly accurate intersections.
The format we get is currently:

```
{"distance":11.1,
"duration":0.8,
"name":"Brunnenstraße",
"maneuver":{"type":"new name","modifier":"straight"},
"geometry":"_fu_IywvpAF\\",
"mode":"driving",
"intersections":[
    {"location":[13.392768,52.542559],
    "bearings":["60","150","240","330"],
     "bearing_before":0,
     "bearing_after":2,
     "entry":["false","false","true","true"]}
]}
```

The intersection for this maneuver is a normal four way intersection with one oneway street, not allowing the u-turn.

If we not give explicit bearings in the step itself, depart and arrive need to offer an intersection as well.
In my view it would probably be better to keep `bearing_before`/`bearing_after` in the initial `depart` and the final `arrive`. And use `bearing_in_id`/`bearing_out_id` or similar in the intersection to avoid confusion.

**Comment by TheMarex** [comment]
My current proposal for the API response:

For normal instructions (not `depart`/`arrive`):

```
{"distance":11.1,
"duration":0.8,
"name":"Brunnenstraße",
"maneuver":{"type":"new name","modifier":"straight"},
"geometry":"_fu_IywvpAF\\",
"mode":"driving",
"intersections":[
    {"location":[13.392768,52.542559],
    "bearings":["60","150","240","330"],
     "in":0,
     "out":2,
     "entry":[false,false,true,true]}
]}
```

For `depart`/`arrive`:

In case its in the middle of a segment with bearing `42`:

```
{"distance":11.1,
"duration":0.8,
"name":"Brunnenstraße",
"maneuver":{"type":"new name","modifier":"straight"},
"geometry":"_fu_IywvpAF\\",
"mode":"driving",
"intersections":[
    {"location":[13.392768,52.542559],
    "bearings":["220","40"],
     "in":0,
     "out":1,
     "entry":[true,true]}
]}
```

If it is at a segment endpoint (do we know this?) and the intersection is degree > 2 use the normal format to represent that intersection like in the not `depart`/`arrive` cases.

**Comment by MoKob** [comment]
@TheMarex I believe we could find out if its an endpoint via the offsets.

We would need to discuss how to represent initial/final bearings in the cases where we use the normal intersection class, though, and whether this separation between two representations for depart/arrive does not introduce more confusion than benefit.

Consider a T-Intersection. The convention so far has been to keep bearings pre depart to `0`, same as `bearings post arrive`.
If we use a normal intersection, the bearing `0` might not be available.
I feel that this could be handled by omitting `in` for `depart` and `out` for arrive.

Depart would look like this, assuming start on a oneway street of bearing 40:

```
{"distance":11.1,
"duration":0.8,
"name":"Brunnenstraße",
"maneuver":{"type":"depart"},
"geometry":"_fu_IywvpAF\\",
"mode":"driving",
"intersections":[
    {"location":[13.392768,52.542559],
    "bearings":["220","40"],
     "out":1,
     "entry":[false,true]}
     , ....
]}
```

If we find an intersection, the format would simply include more bearings. A problem in this case is that the phantom-node snapping would result in possibly inconsistent entry-tags.
Since we don't allow u-turns and have turn restrictions, the node we are snapping to decides which road is traversable.

For an intersection like this:

![turn-restriction](https://cloud.githubusercontent.com/assets/12932279/15208007/c47b1ef0-1829-11e6-8558-182dd6a35c6b.png)

We would get the entry flags `[true,true,false,false]` (coming from the south, not allowing the u-turn and the left turn) and `[true,true,true,false]` from the west, not allowing only the u-turn.

The u-turn can be fixed by looking at the phantom-node itself, the turn restriction cannot be ignored, since we don't know anything about the other phantom node that could have been selected as well.

**Comment by TheMarex** [comment]
This has been merged.
