### ISSUE TITLE
V5 - Route Algorithm Crash => Assert start_index <= end_index

### ISSUE THREAD

**Issue by K-Leon** [Project-OSRM/osrm-backend#2309]
Hello,

I just gave the new V5 Version a spin ( great work btw! ) and stumbled over an issue in Route Plugin.

> [warn] [server error] code: /var/osrm/osrm-backend/include/engine/routing_algorithms/routing_base.hpp:376
> in: void osrm::engine::routing_algorithms::BasicRoutingInterface<DataFacadeT, Derived>::UnpackPath(RandomIter, RandomIter, const osrm::engine::PhantomNodes&, std::vector<osrm::engine::PathData>&) const [with RandomIter = __gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int> >; DataFacadeT = osrm::engine::datafacade::BaseDataFacade; Derived = osrm::engine::routing_algorithms::DirectShortestPathRouting<osrm::engine::datafacade::BaseDataFacade>]: start_index <= end_index
> , uri: /route/v1/driving/8.7475533,47.4976083;8.7475417,47.4976133?geometries=polyline&steps=false

URL: [router.project-osrm.org/route/v1/driving/8.7475533,47.4976083;8.7475417,47.4976133?geometries=polyline&steps=false](http://router.project-osrm.org/route/v1/driving/8.7475533,47.4976083;8.7475417,47.4976133?geometries=polyline&steps=false)

@daniel-j-h I think it could be very similar to issue #2147 you fixed for v4 trip Plugin (thanks again). These coords also resolve more or less to the same Location as far as i can tell. 

One of these 'situations' in a long Routing Request is enough.

Best Regards,
Leon

**Comment by daniel-j-h** [comment]
@MoKob it seems like you introduced the assertion in https://github.com/Project-OSRM/osrm-backend/commit/ef1fb08723565bc968a64d0cba4b947d1a6746ef#diff-ffa2e7ac24f3bebb547c6fe24552431bR376 --- care to take a look?

**Comment by MoKob** [comment]
Should work with: https://github.com/Project-OSRM/osrm-backend/pull/2316

**Comment by TheMarex** [comment]
This is a critical bug and will be included in `5.0.1`.
