### ISSUE TITLE
V5 - Crash - Route Plugin - Post Processing trimShortSegments

### ISSUE THREAD

**Issue by K-Leon** [Project-OSRM/osrm-backend#2310]
Hello,

Sorry to be a bit spammy. Checking Logs for fishy requests and could verify another issue with current debug build. 

> [warn] [server error] code: /var/osrm/osrm-backend/src/engine/guidance/post_processing.cpp:349
> in: void osrm::engine::guidance::trimShortSegments(std::vector<osrm::engine::guidance::RouteStep>&, osrm::engine::guidance::LegGeometry&): geometry.segment_offsets[1] == 1
> , uri: /route/v1/driving/6.1306817,46.1948783;6.1306183,46.1949117?geometries=polyline&steps=true&overview=full

[http://router.project-osrm.org/route/v1/driving/6.1306817,46.1948783;6.1306183,46.1949117?geometries=polyline&steps=true&overview=full](http://router.project-osrm.org/route/v1/driving/6.1306817,46.1948783;6.1306183,46.1949117?geometries=polyline&steps=true&overview=full)

Best Regards,
Leon

PS: If there's anything to help you with just shoot me a message - I'll dig into the OSRM Code for sure in the near feature until then i can only open an issue :/

**Comment by MoKob** [comment]
Fixed in https://github.com/Project-OSRM/osrm-backend/pull/2317

**Comment by TheMarex** [comment]
This is a critical bug and will be included in `5.0.1`.
