### ISSUE TITLE
V5 - Route Algorithm Crash => loop unpacking routing_base

### ISSUE THREAD

**Issue by K-Leon** [Project-OSRM/osrm-backend#2311]
Hello,

I just noticed another crash:

> [warn] [server error] code: /var/osrm/osrm-backend/include/engine/routing_algorithms/routing_base.hpp:564
> in: void osrm::engine::routing_algorithms::BasicRoutingInterface<DataFacadeT, Derived>::Search(osrm::engine::SearchEngineData::QueryHeap&, osrm::engine::SearchEngineData::QueryHeap&, int32_t&, std::vector<unsigned int>&, bool, bool, int) const [with DataFacadeT = osrm::engine::datafacade::BaseDataFacade; Derived = osrm::engine::routing_algorithms::ShortestPathRouting<osrm::engine::datafacade::BaseDataFacade>; osrm::engine::SearchEngineData::QueryHeap = osrm::util::BinaryHeap<unsigned int, unsigned int, int, osrm::engine::HeapData, osrm::util::UnorderedMapStorage<unsigned int, int> >; int32_t = int]: forward_heap.GetData(middle).parent == middle && reverse_heap.GetData(middle).parent == middle
> , uri: /route/v1/driving/6.2528300,46.4239633;6.2528067,46.4239533;7.0409333,46.6235917

[http://router.project-osrm.org//route/v1/driving/6.2528300,46.4239633;6.2528067,46.4239533;7.0409333,46.6235917](http://router.project-osrm.org//route/v1/driving/6.2528300,46.4239633;6.2528067,46.4239533;7.0409333,46.6235917)

Best Regards,
Leon

**Comment by MoKob** [comment]
should be fixed for the moment with #2319 . It may fail to find a route in some cases due to #2016, though, which is the reason this error surfaces in the first place.
