### ISSUE TITLE
V5 crash on some points

### ISSUE THREAD

**Issue by niraviitm** [Project-OSRM/osrm-backend#2315]
I have noticed that V5 crashes, when I try to find distance between some particular points..Following is one of such scenario in which V5 crashes with NewYork map (http://download.geofabrik.de/north-america/us/new-york.html).

`

    // The following shows how to use the Route service; configure this service
    RouteParameters params;
	params.coordinates.push_back({util::FloatLongitude(-73.87455750), util::FloatLatitude(40.77410126)});
	params.coordinates.push_back({util::FloatLongitude(-73.87448120), util::FloatLatitude(40.77410126)});
	params.coordinates.push_back({util::FloatLongitude(-73.94281769), util::FloatLatitude(40.74612045)});
	params.coordinates.push_back({util::FloatLongitude(-73.98728180), util::FloatLatitude(40.73074722)});

    // Response is in JSON format
    json::Object result;

    // Execute routing request, this does the heavy lifting
    const auto status = osrm.Route(params, result);`

Following is the trace of crash.

`0x00000000004433d7 in void osrm::engine::routing_algorithms::BasicRoutingInterface<osrm::engine::datafacade::BaseDataFacade, osrm::engine::routing_algorithms::ShortestPathRouting<osrm::engine::datafacade::BaseDataFacade> >::UnpackPath<__gnu_cxx::__normal_iterator<unsigned int const*, std::vector<unsigned int, std::allocator<unsigned int> > > >(__gnu_cxx::__normal_iterator<unsigned int const*, std::vector<unsigned int, std::allocator<unsigned int> > >, __gnu_cxx::__normal_iterator<unsigned int const*, std::vector<unsigned int, std::allocator<unsigned int> > >, osrm::engine::PhantomNodes const&, std::vector<osrm::engine::PathData, std::allocator<osrm::engine::PathData> >&) const ()`

**Comment by daniel-j-h** [comment]
It looks like you're hitting https://github.com/Project-OSRM/osrm-backend/issues/2309.

@MoKob just fixed it in https://github.com/Project-OSRM/osrm-backend/pull/2316, can you try with the branch `fix/2309` and see if this helps?

**Comment by TheMarex** [comment]
Closing as outdated.
