### ISSUE TITLE
Crash in Match Service (as reported on IRC)

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2320]
Capturing from yesterday night's IRC logs:

```
23:59 < strom> i think i borked my osrm server trying a match request :p
00:00 < strom> then i tried requesting the url from the router.project-osrm.org and it gave me a {"code": "InternalError","message":"Internal Server Error"}
00:01 < strom> guys the link i tried is at http://pastebin.com/UGh7Qmx2
00:02 < strom> danieljh: try the link at http://pastebin.com/UGh7Qmx2 , it crashed my osrm server, then i tried it on the router.project-osrm.org that also gave me an internal server error
```

This is the query in question:

    http://router.project-osrm.org/match/v1/driving/74.26376,31.503645;74.263016,31.504053;74.26348,31.503666;74.262825,31.503717;74.263535,31.50374;74.264084,31.503439;74.26345,31.503819;74.264275,31.503391;74.26343,31.5037;74.26282,31.504107;74.26365,31.503666;74.26294,31.503452;74.26384,31.503942;74.262985,31.50395;74.263626,31.503675;74.26466,31.503317;74.26309,31.503914;74.26357,31.503214;74.26339,31.504034;74.26366,31.503538;74.26316,31.503883;74.26823,31.500244;74.263275,31.503723;74.26261,31.504074;74.263374,31.503704;74.26288,31.504078;74.263565,31.50361;74.262344,31.50436;74.263275,31.50385;74.26331,31.503176?radiuses=46.0;52.5;2.0;96.0;35.0;64.0;96.0;64.0;96.0;75.0;38.0;96.0;64.0;52.5;37.0;96.0;45.0;96.0;96.0;24.0;48.0;64.0;48.0;96.0;96.0;80.756;12.0;39.0;29.0;96.0&timestamps=1461421254;1461518434;1461518456;1461518560;1461518616;1461518904;1461519115;1461519819;1461519837;1461520321;1461520403;1461520417;1461520496;1461520543;1461520583;1461520617;1461520624;1461520694;1461520735;1461520893;1461521234;1461521886;1461521901;1461521948;1461521971;1461522257;1461522266;1461522339;1461522359;1461522466

No further information so far. Have to investigate.

**Comment by TheMarex** [comment]
This request does not crash anymore. Probably fixed by @MoKob fixes.
