### ISSUE TITLE
The route within the administrative boundaries

### ISSUE THREAD

**Issue by vvk95** [Project-OSRM/osrm-backend#2322]
Hello

First of all, sorry for my English.
I want to ask how to do the calculation of the route within the administrative boundaries.
To prevent the occurrence of the following situations: [example](
http://map.project-osrm.org/?z=10&center=54.125834%2C25.650330&loc=54.081951%2C25.497894&loc=54.326936%2C25.805511&hl=en&alt=0)

I think there are several solutions to this problem.

1) Check `barrier=border_control`
This mean:
a) Delete `["border_control"] = true` from "barrier_whitelist" in car.lua.
b) Add few lines to "node_function":
```
function node_function (node, result)
  -- parse access and barrier tags
  local access = find_access_tag(node, access_tags_hierachy)
  if access and access ~= "" then
    if access_tag_blacklist[access] then
      result.barrier = true
    end
>    local barrier = node:get_value_by_key("barrier")
>     if barrier and barrier == "border_control" then
>       result.barrier = true
>     end
  else
    local barrier = node:get_value_by_key("barrier")
    if barrier and "" ~= barrier then
      --  make an exception for rising bollard barriers
      local bollard = node:get_value_by_key("bollard")
      local rising_bollard = bollard and "rising" == bollard

      if not barrier_whitelist[barrier] and not rising_bollard then
        result.barrier = true
      end
    end
  end
```

c) Add "`barrier=border_control`" to all border control nodes for roads crossing the lines with "`boundary=administrative`" and "`admin_level=2`".
But what if there is no border control barriers, such as within the European Union?

2) Add information about the country for each road to tables in the PostGIS database.
And then get it with the SQL query in the lua "way_function".

3) Extract the country polygon from the OSM data, and then do a check for each road in the lua "way_function" whether the road is inside the polygon.

Maybe there is an easier way to check road intersection with the administrative boundaries?

**Comment by TheMarex** [comment]
> Maybe there is an easier way to check road intersection with the administrative boundaries?

1. Do you have more than one country you want to route in?
2. Can you run multiple osrm instances?

By far the easiest solution in case there is only one country or you can run multiple `osrm-routed` instances is to just slice the data with [osmconvert](http://wiki.openstreetmap.org/wiki/Osmconvert) and route on each separately.

**Comment by daniel-j-h** [comment]
https://github.com/Project-OSRM/osrm-backend/issues/77 is about making travel time and edge weights independent. Once this is implemented, this allows you to set arbitrary penalties without screwing your ETAs. Just flagging this here for cross-referencing purpose, please don't count on us to implement this in the next weeks :)

**Comment by vvk95** [comment]
@TheMarex Thank you very much for your reply!
Running multiple server instances and slicing the map seems to be really the best solution compared to my.

**Comment by vvk95** [comment]
@daniel-j-h Wow! It will be a very useful solution, which will help to solve some current problems...
But in this case I don't quite understand how to distinguish by tags the road of one country from the other.
Probably will have to somehow get access to the relations?

**Comment by daniel-j-h** [comment]
> But in this case I don't quite understand how to distinguish by tags the road of one country from the other.

For example, by doing point-in-polygon checks on the locations in the Lua profile.

**Comment by vvk95** [comment]
@daniel-j-h  Ok. Now everything is clear, thank you. And I look forward to when it will be possible to try to edit edge weights! :)

**Comment by dhjw** [comment]
Is there an easy way to do this yet? I would love to be able to calculate routes between two cities in the same country without crossing borders.

**Comment by daniel-j-h** [comment]
By now you edge weights are independent from edge speeds. You could now add very high penalties for border crossings in the profiles. I think we do something similar for destination tags at the moment.
