### ISSUE TITLE
The speedup of v5.0.0

### ISSUE THREAD

**Issue by free-ionia** [Project-OSRM/osrm-backend#2325]
Comparing to v4.9.1,the map matching speed of v5.0.0 gets great improvement while it's overhead of computing decreases. I am really interested how did you make that happen, by new data strucure,advanced algorithm,In-Memory Computing or anything else?Thanks for your amazing job.

**Comment by DeepAnchor** [comment]
Likely due to the improvements listed in the [release candidate notes](https://github.com/Project-OSRM/osrm-backend/issues/2253):

> 
>       - Optimize StaticRTree code: speedup 2x (to RC1)
>       - Optimize DouglasPeucker code: speedup 10x (to RC1)
>       - Optimize WebMercator projection: speedup 2x (to RC1)

amazing improvements indeed!

**Comment by danpat** [comment]
Actually, the commit that improved map-matching performance was mainly this: https://github.com/Project-OSRM/osrm-backend/commit/adc3bacea960b7bdd8d01f24c21454a9c0f1fff5#diff-5a3c991e5f7a5eea11ab44e1b44a4979

which is not really mentioned in the changelog.  I think we just forgot about it :-)

Basically, this commit sets a cap on what the map-matching search bothers to look at, it avoids searching graph edges where the travel speed would end up being unreasonably slow.

Closing this ticket as not actionable, but the thanks are appreciated by everyone on the team!

/cc @TheMarex @MoKob

**Comment by TheMarex** [comment]
It was a combination of all of the above. Map matching used to spend at least half the time in the static r tree finding candidates. 

The change @danpat linked mainly improved performance on datasets with core factor (basically bringing it down to the normal numbers).
