### ISSUE TITLE
table service limit on the public API

### ISSUE THREAD

**Issue by rCarto** [Project-OSRM/osrm-backend#2326]
I understand that there is a limit in the `table` output (10 000 durations). 
Maybe this limit should be indicated in the wiki (https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy). 
This limit seems fine when `sources` & `locations` are not used. A query with 100 locations will work and output a 100*100 matrix (10 000 durations).
A query with 100 sources and 100 destinations will work fine also (10 000 durations). 
But if I ask for 1 source and 1000 destinations (just 1 000 durations) the query won't work (I guess that the URL is too long?). Should this limit (in URL size ?) be indicated somewhere?

**Comment by daniel-j-h** [comment]
See the discussion behind the POST HTTP Method removal: https://github.com/Project-OSRM/osrm-backend/issues/2163, https://github.com/Project-OSRM/osrm-backend/pull/2182.
You can use Polyline encoding as documented in the [v5 spec](https://github.com/Project-OSRM/osrm-backend/wiki/Server-API-v5,-current).

But then again, if you're repeatedly doing large queries like that maybe you want to run OSRM locally. I recommend not going through HTTP but to either use node-osrm or libosrm directly. The HTTP server included in OSRM (routed) is for development and has it's shortcomings e.g. it does not support KeepAlive. All of that only applies, if your use-case allows for it.

**Comment by TheMarex** [comment]
The actual time spend for table queries is mostly O(#sources and targets) not really in the size of the matrix. (the query is fast, the coordinate lookup and transport encoding is not)

We will not increase that limit on our public HTTP API. Please note that we will decrease limits arbitrary if we detect users spamming our server with large requests. I would follow  @daniel-j-h suggestion.

**Comment by rCarto** [comment]
Ok, I will try the Polyline encoding.
I understand the need of limits for the public API so I also run an OSRM instance locally (v5, works perfectly).  
Many thanks for the quick reply.

**Comment by Anyaoha** [comment]
Can someone please teach me how to run OSRM locally so I can use in in R studio for a larger osrmRoute analysis. 
Thanks

**Comment by Anyaoha** [comment]
@daniel-j-h and @TheMarex can you please help

**Comment by danpat** [comment]
@Anyaoha Your best option is probably to follow the instructions here: https://github.com/Project-OSRM/osrm-backend/wiki/Docker-Recipes

**Comment by Anyaoha** [comment]
@danpat thanks for your response. I'm trying to follow that. But it seems that's ubuntu. 
I'm new on how to set up localhost but I don't mind taking the babysteps since my work in R is important. I'd keep looking though. Thanks once again :)

**Comment by jhagenauer** [comment]
Mhm, I am running the latest docker image and still facing the 100x100 limit. Is there a way how I can turn off this limit locally? Thanks!
