### ISSUE TITLE
Segfault on osrm@5.0.0

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#2329]
Not sure what I'm seeing here. Important line seems to be the one below:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fcba79b9f15 in void osrm::engine::routing_algorithms::BasicRoutingInterface<osrm::engine::datafacade::BaseDataFacade, osrm::engine::routing_algorithms::AlternativeRouting<osrm::engine::datafacade::BaseDataFacade> >::UnpackPath<__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > > >(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, __gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, osrm::engine::PhantomNodes const&, std::vector<osrm::engine::PathData, std::allocator<osrm::engine::PathData> >&) const () from /usr/local/src/app/node_modules/osrm/lib/binding/osrm.node
```

- [Full trace as gist](https://gist.github.com/freenerd/f5b86f63abc41dfe494ed6617d0f580a)
- Stack trace generated via `gdb node /coredumps/ -ex "set pagination 0" -ex "thread apply all bt"``
- Using `node-osrm@5.0.0`
- Current OSM planet

I'll keep digging, trying to find the request that triggers this

**Comment by daniel-j-h** [comment]
Looks like one of the UnpackPath calls here:

- https://github.com/Project-OSRM/osrm-backend/blob/3f0deadf01c4c995669f048cd72ed5c3847d14c9/include/engine/routing_algorithms/alternative_path.hpp#L325
- https://github.com/Project-OSRM/osrm-backend/blob/3f0deadf01c4c995669f048cd72ed5c3847d14c9/include/engine/routing_algorithms/alternative_path.hpp#L350

**Comment by freenerd** [comment]
Here is a route triggering the segfault:

http://map.project-osrm.org/?z=18&center=43.674505%2C1.417923&loc=43.674514%2C1.418320&loc=43.674606%2C1.418328&hl=en&alt=0

Against `master` it seems to be fixed already (note: i'm running `osrm-backend@5.0.0`)

https://router.project-osrm.org/route/v1/driving/1.4180490374565125,43.67446982614228;1.418327987194061,43.67460562420462

**Comment by daniel-j-h** [comment]
@MoKob fixed that one in https://github.com/Project-OSRM/osrm-backend/pull/2319. We have to make a hotfix release for those critical issues.

Closing here as not actionable.
