### ISSUE TITLE
Route Instructions 

### ISSUE THREAD

**Issue by dr-teddygenesis** [Project-OSRM/osrm-backend#2334]
Hi, I have successfully return a JSON objects for driving directions with the viaroute api call. 
---------
"route_instructions":[["10","R Street Northwest",92,0,13,"91m","W",270,1,"E",90]
---------
Have anyone done a middleware that converts the indices into readable context, I know there is leaflet routing library that does that but it you have to incorporate the _'L.Routing.control'_ at the front end but I'm thinking is there a way to write a service so that other platforms (Java, Objective C) can consume there driving instructions (like bearing left,right .....)

**Comment by TheMarex** [comment]
Try the new version `v5.0.1` that features human-readable responses https://github.com/Project-OSRM/osrm-backend/wiki/Server-API-v5,-current
