### ISSUE TITLE
v5.0.1 crashes on some points when I Iincrease RADIUS_MULTIPLIER to 25.Is it normal?

### ISSUE THREAD

**Issue by free-ionia** [Project-OSRM/osrm-backend#2335]
Hello,after fixation,v5.0.1 becomes much more robust than v5.0.0.While using v5.0.1 to preprocess data,I discover a bug crashing the OSRM which,I guess,may be the same to #2315 and #2309.The bug,Segment fault (core dump),occurs at the 8th point when I enter the following http request to FireFox:

http://127.0.0.1:5000/match/v1/driving/113.513,22.1741;113.514,22.1743;113.515,22.1748;113.516,22.1755;113.517,22.1761;113.517,22.1757;113.518,22.1756;113.517,22.1759;113.517,22.1763;113.518,22.1769;113.519,22.1775;113.521,22.1806?overview=falsle

After visualizing above 12 points,it is clear that points 5、6、7、8 and 9 are gathering around a building,like pick-up or drop-off location.

Best Regards,
JUN CHEN

**Comment by TheMarex** [comment]
Just fixed this in master. Will be in `5.0.2`. Great bug report. Thank you. :+1:
