### ISSUE TITLE
Gateway error

### ISSUE THREAD

**Issue by booper** [Project-OSRM/osrm-backend#2336]
Get this error:
![osrm](https://cloud.githubusercontent.com/assets/583898/14888354/888fa4c8-0d62-11e6-86c8-ffbd1fc27ea4.png)

5 mins ago everything works just great

**Comment by daniel-j-h** [comment]
Thanks for the report, the demo server currently has some hiccups. @TheMarex is already investigating.

**Comment by TheMarex** [comment]
This is fixed now. Restarted the server.
