### ISSUE TITLE
Update WIKI for Windows build instructions

### ISSUE THREAD

**Issue by BergWerkGIS** [Project-OSRM/osrm-backend#2341]
https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation is outdated

**Comment by daniel-j-h** [comment]
Related: https://github.com/Project-OSRM/osrm-backend/issues/2184

**Comment by BergWerkGIS** [comment]
Done: https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation

**Comment by daniel-j-h** [comment]
:+1: thanks for keeping the docs up to date!

What is your plan wrt. CMake 3.5? Is there a ticket for this upstream already? ([ref](https://github.com/Project-OSRM/osrm-backend/pull/2118))

**Comment by daniel-j-h** [comment]
Ah, and I just noted the Wiki saying:
> Latest Visual Studio 2015 (Community or better) - earlier versions are not supported

I think we should adapt the build system to this [here](https://github.com/Project-OSRM/osrm-backend/blob/64307ea882bcbd98ff86800cac2b92cb24eda9b6/CMakeLists.txt#L28-L30).

**Comment by BergWerkGIS** [comment]
> I think we should adapt the build system to this [here](https://github.com/Project-OSRM/osrm-backend/blob/64307ea882bcbd98ff86800cac2b92cb24eda9b6/CMakeLists.txt#L28-L30).

Yes, should be updated to `1900`
https://cmake.org/cmake/help/v3.5/variable/MSVC_VERSION.html

> What is your plan wrt. CMake 3.5? Is there a ticket for this upstream already? ([ref](https://github.com/Project-OSRM/osrm-backend/pull/2118))

Quick solution was to download `3.5.1` in the background if `3.5.0` was found:
https://github.com/Project-OSRM/osrm-backend/blob/64307ea882bcbd98ff86800cac2b92cb24eda9b6/appveyor-build.bat#L13-L22

**Comment by daniel-j-h** [comment]
Great, the workaround should be fine for now (I forgot about the fix in 3.5.1).

Updated requirement to VS 2015+ in https://github.com/Project-OSRM/osrm-backend/pull/2353. Done here, thanks again :+1:.
