### ISSUE TITLE
Hint option with v5 api

### ISSUE THREAD

**Issue by gielhoogstraten** [Project-OSRM/osrm-backend#2356]
I tried to get the hint option included in the v5 api request for trip and route. The request fails if the last location in the string is an empty element. In the way we use it, this is a common use case. I'm quite new to this, so maybe there is an easy solution (which I'm obviously missing) on how to pass an empty hint element for the last location. Is there a way to pass an empty hint element for the last location?

**Comment by TheMarex** [comment]
Can you post an example query string?

**Comment by gielhoogstraten** [comment]
I use this query strings:
http://router.project-osrm.org/trip/v1/driving/4.891362190246582,52.37313639562877;5.857654809951782,51.84737108641299;5.121324062347412,52.090728536302144?hints=EhtFg____39LiwgAAAAAAAMAAAAaAAAAaQEAANeURAjymYsCgq8AAB-gSgCQJh8D4qJKAJAmHwMBAAEBABtDVQ==;OopQgOH-J4qMegAAEQAAAA0AAAAJAAAAMgAAAFyJUgBGqVMAgq8AAJ1iWQCAIRcDdmFZAMsgFwMCAAEBABtDVQ==;&geometries=polyline&overview=full

or for the route:
http://router.project-osrm.org/route/v1/driving/4.891362190246582,52.37313639562877;5.857654809951782,51.84737108641299;5.121324062347412,52.090728536302144?hints=EhtFg____39LiwgAAAAAAAMAAAAaAAAAaQEAANeURAjymYsCgq8AAB-gSgCQJh8D4qJKAJAmHwMBAAEBABtDVQ==;OopQgOH-J4qMegAAEQAAAA0AAAAJAAAAMgAAAFyJUgBGqVMAgq8AAJ1iWQCAIRcDdmFZAMsgFwMCAAEBABtDVQ==;&geometries=polyline&overview=full

I double checked, but I also get an error message when passing an empty element in an other position then last. Did I miss something?

**Comment by TheMarex** [comment]
Thanks for reporting this. :+1: Can confirm this seems to be a bug. I'm currently trying to find out what broke.

**Comment by oxidase** [comment]
Hi, i will take a look, it can be due to dac2f93383f2f6c43b1277181f68c77c663f28ea

**Comment by TheMarex** [comment]
Ah sorry forgot to close the issue. This was already fixed.

**Comment by gielhoogstraten** [comment]
Great. Thanks for fixing this that fast!
