### ISSUE TITLE
Windows compilation Error C2899: typename cannot be used outside a template declaration

### ISSUE THREAD

**Issue by jperaltamalvar** [Project-OSRM/osrm-backend#2359]
I'm compiling on Windows 10, and I'm getting this error:
C:\Dev\OSRM\osrm-backend\src\storage\storage.cpp(42): error C2899: typename cannot be used outside a template declaration [C:\Dev\OSRM\osrm-backend\build\STORAGE.vcxproj]

[build_errors.txt](https://github.com/Project-OSRM/osrm-backend/files/246608/build_errors.txt)

**Comment by daniel-j-h** [comment]
Hotfix: remove `typename` from [storage.cpp:42](https://github.com/Project-OSRM/osrm-backend/blob/30af544919cb86f0a75bae7edbd9aefeb3fd7520/src/storage/storage.cpp#L42):

```diff
diff --git a/src/storage/storage.cpp b/src/storage/storage.cpp
index 67fd122..43967dc 100644
--- a/src/storage/storage.cpp
+++ b/src/storage/storage.cpp
@@ -39,7 +39,7 @@ namespace osrm
 namespace storage
 {
 
-using RTreeLeaf = typename engine::datafacade::BaseDataFacade::RTreeLeaf;
+using RTreeLeaf = engine::datafacade::BaseDataFacade::RTreeLeaf;
 using RTreeNode =
     util::StaticRTree<RTreeLeaf, util::ShM<util::Coordinate, true>::vector, true>::TreeNode;
 using QueryGraph = util::StaticGraph<contractor::QueryEdge::EdgeData>;
```

**Comment by daniel-j-h** [comment]
Does this solve your compilation issues? For the record, which Visual Studio version are you using? Our Appveyor continuous integration did not complain on that one from what I can see.

**Comment by daniel-j-h** [comment]
The changes in https://github.com/Project-OSRM/osrm-backend/issues/2360 should do the trick.

Your linking issue is coming from a missing xml dependency. Did you follow the instructions at https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation?

Looping in @BergWerkGIS here.

**Comment by jperaltamalvar** [comment]
Thanks @daniel-j-h

I am using Visual Studio Community 2015 (14.0.23107.0 D14REL). Now compiling with changes in  https://github.com/Project-OSRM/osrm-backend/pull/2360 and https://github.com/Project-OSRM/osrm-backend/pull/2363. 

I'll open an specific issue about the linking error I'm getting, just to make it easier to follow up.

**Comment by BergWerkGIS** [comment]
@jperaltamalvar Interesting, I'm able to build latest master without problems, as does AppVeyor.

> I am using Visual Studio Community 2015 (14.0.23107.0 D14REL)

Seems to be a bit old.
You might want to upgrade to the latest `VS 2015 Update 2` or at least `Update 1` as the binary dependencies that get downloaded during build are compiled with `Update 1`.
