### ISSUE TITLE
Supporting conditional turn restrictions

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#2374]
Previously: https://github.com/Project-OSRM/osrm-backend/issues/583

The data team at Mapbox has been on a mapping sprint of [missing turn restrictions from Mapillary](https://github.com/mapbox/mapping/issues/177) and we have encountered [over 100 of them in SF](http://overpass-turbo.eu/s/g3j).

Many of the existing conditional restrictions are tagged like this:
<img width="307" alt="screenshot 2016-05-05 15 19 26" src="https://cloud.githubusercontent.com/assets/126868/15040775/cdcf5a66-12d4-11e6-86bf-a889ba49c8eb.png">
_[wiki](http://wiki.openstreetmap.org/wiki/Relation:restriction#Tags)_

There is no well defined tagging scheme for conditional turn restrictions, so the team is going to follow the [conditional restriction format](http://wiki.openstreetmap.org/wiki/Conditional_restrictions) like this:  `restriction:conditional=no_left_turn @ (Mo-Fr 07:00-10:00,15:00-19:00)` . [Details](https://github.com/mapbox/mapping/issues/177#issuecomment-217108678).

Two questions:
- Would be good to get some inputs if ^ is a good format for OSRM to use in the future?
- When migrating old restrictions to this scheme, we add the `restriction:conditional` tag, but leave the original `restriction` tag unmodified. Will OSRM continue to treat these as a normal turn restriction?

cc @danpat @daniel-j-h @MoKob @oini

**Comment by danpat** [comment]
@planemad This change of tagging will affect OSRM.  If `restriction:conditional` is seen on a relation, we'll skip the whole thing, the assumption being that its better to allow turns than restrict them most of the time (assuming conditions are only usually for short periods).

The *current* tagging scheme (as shown in your example) would mean that the restriction is always honoured.  The change of tagging will mean that it's always ignored.

**Comment by planemad** [comment]
@danpat while updating the existing restrictions, the old tags are left intact. So the final version has both `restriction` and `restriction:conditional` like http://www.openstreetmap.org/relation/3792881 . To confirm, these will now be ignored as a turn restriction, yes?

Also any feedback on the tagging scheme itself. Given that there is no consensus on OSM on how to tag such features, it would be good to have an OSRM perspective of what would work best to implement this in future.

**Comment by danpat** [comment]
@planemad That's correct, the addition of the extra `restriction:conditional` tag will cause OSRM to skip the restriction entirely.

OSRM has no ability to support time-dependent features at all right now.  As long as the syntax is well-structured and machine readable, that's probably all you need to do at the moment.

I just opened https://github.com/Project-OSRM/osrm-backend/issues/2377 to discuss one (difficult) approach for possibly supporting this, but it's not going to be easy to implement.

**Comment by daniel-j-h** [comment]
@oxidase is working on this in https://github.com/Project-OSRM/osrm-backend/pull/3415.

Closing in favor of https://github.com/Project-OSRM/osrm-backend/issues/3414.

cc @oxidase the scenarios outlined above are already great test cases! :)
