### ISSUE TITLE
Elevation and speedlimit

### ISSUE THREAD

**Issue by Timo86** [Project-OSRM/osrm-backend#2375]
Hello i'm new with osrm. And i want to know can i display max_speed in the result and my pbf file contain the elevation how can i get back ?

**Comment by danpat** [comment]
@Timo86 Can you re-state your question, I'm not sure I understand.  Do you want speed-limits and elevation data in the returned routing results somehow?

**Comment by Timo86** [comment]
Sorry my english is bad. I'm trying to compute consumption of electrical car but i need the speed between two node not for all the route. And in my osm.pbf file i have a tag elev (from srtm), it's possible to get it back like in geometry [lng/lat/elev] (i don't know) or other solution to get the height difference of one way.

I hope you will understand :/.

**Comment by danpat** [comment]
@Timo86 No, there's no way to get that extra data right now from OSRM without hacking at the C++ layer.

You could take a look at this project:

https://github.com/mapbox/route-annotator

You would take a route from OSRM, then feed it to `route-annotator`, and it will give you back all the tags from the `<way>`s along that route.  It does not currently give you the `<node>` tags, but that seems like it would be a reasonable feature to add.  Feel free to submit a patch!

**Comment by Timo86** [comment]
Thank you for your reply. The project is to huge for me to go in C++ know. But i will look at your link. :)

**Comment by vinayrachapalli** [comment]
hey @TimoPtr , are you able to complete your project? I've also started a similar kind of project, need to calculate fuel needed for a vehicle. Can you help me?

**Comment by TimoPtr** [comment]
Sadly I didn't get the time to do it
