### ISSUE TITLE
Luabind does not work with Lua 5.1.

### ISSUE THREAD

**Issue by RyanWangGit** [Project-OSRM/osrm-backend#2382]
I'm currenlt building the OSRM on CentOS 6 and followed the bash script on wiki, however I keep getting this error message
```
-- Found Osmium: /opt/osrm-backend-5.0.2/third_party/libosmium/include  
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   chrono
--   atomic
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: /opt/osrm_infrastructure/luabind-0.9.1/lib/libluabindd.so  
-- Found Luabind: /opt/osrm_infrastructure/luabind-0.9.1/lib/libluabindd.so
-- Found Lua52: /usr/local/lib/liblua.a;/usr/lib64/libm.so (found version "5.1.4") 
-- Looking for LuaJIT 5.2
-- Found LUAJIT: /opt/osrm_infrastructure/LuaJIT-2.0.2/lib/libluajit-5.1.so  
-- Found LuaJIT: LUAJIT_LIBRARY-NOTFOUND
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Failed
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
-- Found Lua51: /usr/local/lib/liblua.a;/usr/lib64/libm.so (found version "5.1.4") 
-- Looking for LuaJIT 5.1
-- Found LuaJIT: LUAJIT_LIBRARY-NOTFOUND
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Failed
CMake Error at cmake/check_luabind.cmake:38 (message):
  Luabind does not work with Lua 5.1 at /usr/lib64/liblua-5.1.so, no working
  Luabind found
Call Stack (most recent call first):
  CMakeLists.txt:252 (include)
```
Is there anything wrong with the lua 5.1 or luabind 0.9.1?

**Comment by daniel-j-h** [comment]
Please read the tickets linked in https://github.com/Project-OSRM/osrm-backend/issues/1974#issuecomment-189187428 see if you're hitting the Lua problems outlined there.

**Comment by daniel-j-h** [comment]
For the record, you have to make sure your Luabind build is linked against the same Lua version OSRM is pulling in. You can do this by cloning this repo. https://github.com/mapbox/luabind

then using e.g. the ncurses CMake frontend

    mkdir build
    pushd build
    ccmake .. -DCMAKE_BUILD_TYPE=Release

and changing the Lua libraries it links against. Then install it

    sudo make install

or tell OSRM's CMake where to look for it by passing the following to CMake

    -DLUABIND_INCLUDE_DIR=/home/daniel/gcc-dev-6.1/include \
    -DLUABIND_LIBRARY=/home/daniel/gcc-dev-6.1/lib/libluabind.a

Linking Luabind against Lua X and then using Lua Y for OSRM won't work.
