### ISSUE TITLE
OSRM via route does not run

### ISSUE THREAD

**Issue by jagarga** [Project-OSRM/osrm-backend#2387]
Hi.

I have installed OSRM in a Ubuntu 14.04 Virtual machine apparently without any problem.

If i do this:

http://192.168.1.138:5000/route/v1/driving/-0.380407,39.472297;-0.380960,39.472361;-0.380960,39.469595?overview=false&steps=true

The application runs, but if i try to use viaroute or nearest plugins i obtain the following answer:

http://192.168.1.138:5000/viaroute?loc=39.45,-0.40&loc=39.49,-0.36&compression=false&instructions=true

{"message":"URL string malformed close to position 9: \"ute?lo\"","code":"InvalidUrl"}

I have see something strange:

root@javier-VirtualBox:~/osrm# osrm-routed spain-latest.osrm
[info] starting up engines, v5.1.0
[info] Threads: 8
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:5000
[info] loading graph data
[info] loading graph from spain-latest.osrm.hsgr
[info] number_of_nodes: 5495780, number_of_edges: 27575261
[info] loaded 5495780 nodes and 27575261 edges
[info] Data checksum is 2490194888
[info] loading edge information
[info] loading core information
[info] loading geometries
[info] loading datasource info
[info] loading timestamp
[info] Loading Timestamp
[info] loading profile properties
[info] loading street names
[info] loading rtree
[info] running and waiting for requests

  I see other people that after running and waiting request the server registers the plugins

can someone help me?

**Comment by TheMarex** [comment]
Hey @jagarga. Seem like you are trying to use the old API. The `route` plugin _is_ the `viaroute` of the 4.9 version.

Please see the documentation of our new API:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

**Comment by jagarga** [comment]
I have installed 5.1 version:

![image](https://cloud.githubusercontent.com/assets/5622738/15105180/ce5c9618-15bf-11e6-91d7-260434d1c5b7.png)

I can see the plugins in the folders of my instalaltion:

![image](https://cloud.githubusercontent.com/assets/5622738/15105192/ed2b11e6-15bf-11e6-98f1-3bd057358c48.png)

I have followed this tutorial:

https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04

**Comment by perliedman** [comment]
@jagarga that tutorial is written for versions of OSRM before 5.0. As @TheMarex says, the API has changed in 5.0, you have to use the new URL structure.

**Comment by jagarga** [comment]
What url structure ?

**Comment by perliedman** [comment]
@jagarga the one that @TheMarex linked in his response above: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

**Comment by jagarga** [comment]
Ok, thanks.
but i need to use viaroute version. How i can to update my api version?

**Comment by perliedman** [comment]
If you for some reason need to use the old URL format, you have to install OSRM 4.9 or earlier.

**Comment by jagarga** [comment]
Hi.
The url that you send me is the documentation for the last version?

Viaroute is from an older versión?

**Comment by perliedman** [comment]
@jagarga It's hosted in the repository, and I linked from master, so it's the latest committed.

I guess you can check the version from the version tag if you want to be exactly sure what it looked like when the version you're running was released.

**Comment by jagarga** [comment]
Ok. Now is clear. How I see "route/v1" I thought that this was an older version.

Thanks for the help

**Comment by derak29** [comment]
Hi OSRM node route extraction error. Anybody can explain how i can solve it? Please

Thanks 

[warn] Missing/Broken File: azerbaijan-latest.osrm.partition
[warn] Missing/Broken File: azerbaijan-latest.osrm.cells
[warn] Missing/Broken File: azerbaijan-latest.osrm.mldgr
[info] starting up engines, v5.7.0
[info] Threads: 8
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:5000
[info] load names from: "azerbaijan-latest.osrm.names"
[info] set checksum: 88966982
[info] running and waiting for requests
