### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by nacho8** [Project-OSRM/osrm-backend#2388]
Hello!

Is it possible to create a lua for people in wheelchairs ( people with disabilities / silla de ruedas)?

Thanks!

-----------------------------------------------------------------------
Hola!,

Es posible crear un archivo .lua para personas en silla de ruedas ??

Gracias!

**Comment by emiltin** [comment]
Yes, if the required data is in OpenStreetMap then you can create a custom LUA routing profile and run your own OSRM server.

If the data is not in OSM but you have it e.g in a PostGIS database, it's still possible but requires more work.

**Comment by nacho8** [comment]
Hello emiltin!,

Thanks for your answer. Another question: 

if the osm file I add the information I need in some way. Would it be feasible ?

Example: I add every way a property that is accessible, according to my information 
and then generate my lua that includes this case.

Sorry for my language, I do not speak English well.

**Comment by emiltin** [comment]
Yes but you need to follow the estrablished tagging schemes, e.g:
http://wiki.openstreetmap.org/wiki/Key:wheelchair
http://wiki.openstreetmap.org/wiki/Accessibility

Some existing services provide guidance for wheelchairs based on OSM data (and maybe other sources, I don't know):

http://wheelmap.org/en/map

**Comment by nacho8** [comment]
Okey!,

We already seek services that provide this function , but found none. This http://wheelmap.org/en/map  has the information , but do not generate routes based on that. 

Our idea was to build an application that will generate routes based on accessible ways, so I consulted the feasibility of adding information to OSM file on accessibility and generate our own wheelchairs.lua

Anyway you told us that information is going to be useful. Thank you very much!

**Comment by daniel-j-h** [comment]
Note that OSRM does not handle indoor routing as in

http://wiki.openstreetmap.org/wiki/Indoor_Mapping
http://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging

which is probably the most interesting part here. You _could_ write Lua profiles to re-write the indoor tagging (e.g. levels) to pseudo-streets and highway-tagged ways, but this is nothing but a hack.

**Comment by nacho8** [comment]
Hello daniel-j-h!
Thanks for your time!,

I understand what you want to tell me and is a viable alternative. 
I make another question: do you know of any application to do something similar to what we want to do ?. We might be useful to take an example.

What we do is basically an application that generates routes for people with disabilities.

Again, thank you very much for your help.

**Comment by daniel-j-h** [comment]
There is a Projects section in the OSM wiki
http://wiki.openstreetmap.org/wiki/Indoor_Mapping#Projects
other than that, I have no experience with indoor mapping.

Just to be clear here, OSRM is fine for outdoor routing and you can certainly write a custom profile for it.

You may have more luck either on some of the OSM mailinglists and / or OSM IRC channels.

**Comment by TheMarex** [comment]
Not actionable closing.
