### ISSUE TITLE
osrm build fails on ubuntu16.04

### ISSUE THREAD

**Issue by stvno** [Project-OSRM/osrm-backend#2393]
I'm trying to build osrm 5.1.0 on a 64bit ubuntu 16.04 machine. I have installed all the dependencies for 15.10 as per https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu (since the 16.04 list is not yet available).
However it fails while building osrm-components
```
[ 95%] Linking CXX executable osrm-components
/tmp/ccSgjAcD.ltrans0.ltrans.o: In function `main':
<artificial>:(.text.startup.main+0x1aef): undefined reference to `OGRLineString::addPoint(double, double)'
<artificial>:(.text.startup.main+0x1b27): undefined reference to `OGRLineString::addPoint(double, double)'
collect2: error: ld returned 1 exit status
CMakeFiles/osrm-components.dir/build.make:123: recipe for target 'osrm-components' failed
make[2]: *** [osrm-components] Error 1
CMakeFiles/Makefile2:555: recipe for target 'CMakeFiles/osrm-components.dir/all' failed
make[1]: *** [CMakeFiles/osrm-components.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
I have tried both from the latest git and the official release. I'm running GDAL 2.1 which might be an issue?
``` 
ogrinfo --version
GDAL 2.1.0, released 2016/04/25
```

**Comment by danpat** [comment]
@stvno Yeah, it won't compile against GDAL 2, see https://github.com/Project-OSRM/osrm-backend/issues/1738

The only thing that links against GDAL is the `osrm-components` tool, and I think it's unlikely that you actually need that.  Try running `cmake` with:

`cmake -DBUILD_COMPONENTS=OFF ..`

this will disable the `osrm-components` tool build and skip any GDAL-related problems.

FWIW, I'm using GDAL 1.11.3 on Ubuntu 16.04 and everything builds cleanly using GCC 5.3.

**Comment by stvno** [comment]
It indeed builds without osrm-components so it is a duplicate of #1738
