### ISSUE TITLE
osrm-prepare missing

### ISSUE THREAD

**Issue by YAN02** [Project-OSRM/osrm-backend#2401]
Hi 

where is osrm-prepare ??

i'm doing this tuto : 
https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04

After step 4 (make install),
i have only 4 cmd : 
osrm-contract   osrm-datastore  osrm-extract    osrm-routed

osrm-prepare is missing

Thanks

**Comment by danpat** [comment]
@YAN02 That tutorial refers to OSRM 4.x.  The latest code is OSRM 5.x and `osrm-prepare` is now called `osrm-contract`.

**Comment by daniel-j-h** [comment]
I talked to Tommaso Urli (the original tutorial author) a month ago and pinged him again today. Maybe there is a way for us to help update this tutorial to v5, as this seems to be a common use-case.
