### ISSUE TITLE
check_luabind.cmake mixes lua5.2 and lua5.1 libraries for LUA_LIBRARIES

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2404]
On a system with both lua5.2 and lua5.1 libraries and a libluabind linked against lua51, `check_luabind.cmake` sets the following CMake vars:

```
LUA_INCLUDE_DIR                 */usr/include/lua5.1
LUA_LIBRARIES                   */usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so
LUA_LIBRARY                     */usr/lib/x86_64-linux-gnu/liblua5.1.so
LUA_MATH_LIBRARY                */usr/lib/x86_64-linux-gnu/libm.so
```

See how 5.2 appears in the `LUA_LIBRARIES`.

**Comment by danpat** [comment]
It looks to me like `LUA_LIBRARIES` is unused.  It's set internally by `FindLua52.cmake`, but `check_luabind.cmake` only uses `LUA_LIBRARY`.

**Comment by daniel-j-h** [comment]
Yep you are right I had another issues that made the linking fail. Hmm, having both FindLua51 and FindLua52 writing into LUA_ prefixed vars is scary, we're one step away from errors.
