### ISSUE TITLE
OSRM route mode

### ISSUE THREAD

**Issue by jagarga** [Project-OSRM/osrm-backend#2406]
Hi.

Is possible use other alternative that does not be driving?

For example i want to offer the possibility of calculate bike or walk routes using the general service:

http://router.project-osrm.org/route/v1/driving/-0.40,39.45;-0.36,39.49?geometries=geojson&steps=true

Thanks.

**Comment by frodrigo** [comment]
The other modes are available through other profile. But the demo server (http://router.project-osrm.org) does not have the other this profiles.
You have to setup your own server.

**Comment by MoKob** [comment]
As @frodrigo already stated, the graphs for the profiles you ask for are totally different.

Not all routes you are allowed to walk along are allowed for bikes. In addition, the travelling speeds vary greatly.
The profiles are used to allow a choice between the two different modes of travel, you require a server running for each of them, though.
