### ISSUE TITLE
How to create  Xcode project of osrm-backend on mac

### ISSUE THREAD

**Issue by DavidLiuGitHub** [Project-OSRM/osrm-backend#2409]
Is there any specification to introduce how to do that?  I met many  linking issues always.

**Comment by daniel-j-h** [comment]
We're using CMake as a buildsystem management tool. You can simply use its XCode generator.

Have a look at CMake's beautiful docs for this: https://cmake.org/cmake/help/v3.0/generator/Xcode.html


    mkdir build
    pushd build
    cmake -G Xcode ..

If this does not work, please provide more detailed information.

**Comment by DavidLiuGitHub** [comment]
@daniel-j-h 
Thanks for your reply, yes and I also used cmake, I got the latest code and generated the Xcode project by cmake, and the detailed linking errors as below and I can not find "/Users/liudongxu/git_repo/osrm-backend/debug/Debug/libosrm_store.a",   pls help me to take a look.

mkdir debug
cd debug
cmake -G Xcode  -DCMAKE_BUILD_TYPE=Debug ..

open the project file with Xcode, then compile it, I got the error as below.

`Ld debug/Debug/osrm-datastore normal x86_64
    cd /Users/liudongxu/git_repo/osrm-backend
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/liudongxu/git_repo/osrm-backend/debug/Debug -F/Users/liudongxu/git_repo/osrm-backend/debug/Debug -filelist /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/osrm-datastore.build/Objects-normal/x86_64/osrm-datastore.LinkFileList -mmacosx-version-min=10.11 -Xlinker -no_deduplicate -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/UTIL.build/Objects-normal/x86_64/assert.o /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/UTIL.build/Objects-normal/x86_64/coordinate.o /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/UTIL.build/Objects-normal/x86_64/coordinate_calculation.o /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/UTIL.build/Objects-normal/x86_64/exception.o /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/UTIL.build/Objects-normal/x86_64/fingerprint.o /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/UTIL.build/Objects-normal/x86_64/hilbert_value.o /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/UTIL.build/Objects-normal/x86_64/name_table.o /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/UTIL.build/Objects-normal/x86_64/simple_logger.o /Users/liudongxu/git_repo/osrm-backend/debug/Debug/libosrm_store.a /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libtbb.dylib /usr/local/lib/libtbbmalloc.dylib -Xlinker -dependency_info -Xlinker /Users/liudongxu/git_repo/osrm-backend/debug/OSRM.build/Debug/osrm-datastore.build/Objects-normal/x86_64/osrm-datastore_dependency_info.dat -o /Users/liudongxu/git_repo/osrm-backend/debug/Debug/osrm-datastore

clang: error: no such file or directory: **'/Users/liudongxu/git_repo/osrm-backend/debug/Debug/libosrm_store.a'`**

**Comment by daniel-j-h** [comment]
Thanks for the log! Paging @danpat @lbud @springmeyer who can probably help with XCode issues on OSX (running Linux myself).

The CMake buildsystem looks fine. Here is the dependency chain for this particular target:
- https://github.com/Project-OSRM/osrm-backend/blob/d5294bb5d04d3d677c5e0eb4666c95b7b5300f4e/CMakeLists.txt#L287
- https://github.com/Project-OSRM/osrm-backend/blob/d5294bb5d04d3d677c5e0eb4666c95b7b5300f4e/CMakeLists.txt#L336

**Comment by daniel-j-h** [comment]
Any update on this one? Could you get it to work?

@danpat @lbud @springmeyer have you ever used XCode with osrm-backend?

**Comment by danpat** [comment]
I just tried with XCode 7.2, I'm seeing the same problem:

<img width="742" alt="screen shot 2016-05-28 at 9 05 11 am" src="https://cloud.githubusercontent.com/assets/1892250/15628334/6c6329f6-24b3-11e6-9d09-52a9e5d5c86a.png">

I'll do a little digging and see if I can fix it.

**Comment by danpat** [comment]
It looks like the target names are generated strangely for the XCode project.  I found:

```
danpat@rundle:~/mapbox/osrm-backend/debug$ find . -name '*.a'
./OSRM.build/Debug/CONTRACTOR.build/Objects-normal/libCONTRACTOR.a
./OSRM.build/Debug/STORAGE.build/Objects-normal/libSTORAGE.a
./OSRM.build/Debug/UTIL.build/Objects-normal/libUTIL.a
```

**Comment by daniel-j-h** [comment]
Interesting. Here are the targets:

https://github.com/Project-OSRM/osrm-backend/blob/a5c5faa21d842245143a4c547579e11b8a213559/CMakeLists.txt#L64-L69

reading the `add_library(... OBJECT ...)` docs:

> add_library(<name> OBJECT <src>...)
> Creates a special “object library” target. An object library compiles source files but does not archive or link their object files into a library. 

https://cmake.org/cmake/help/v3.0/command/add_library.html

On linux this only creates `.o` object files, e.g. `build/CMakeFiles/CONTRACTOR.dir/src/contractor/contractor.cpp.o`. We then reference those object files later on e.g. here for `osrm_store`:

https://github.com/Project-OSRM/osrm-backend/blob/a5c5faa21d842245143a4c547579e11b8a213559/CMakeLists.txt#L81

**Comment by daniel-j-h** [comment]
Stale. If this is still an issue feel free to open a new ticket.
We're not working with this setup so can't help much in resolving it.

**Comment by springmeyer** [comment]
I tried and found a workaround.

1) Create an empty `src/dummy.cpp`

2) Apply this patch:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index dc541d4..4cc1a6c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -141,10 +141,10 @@ add_executable(osrm-extract src/tools/extract.cpp)
 add_executable(osrm-contract src/tools/contract.cpp)
 add_executable(osrm-routed src/tools/routed.cpp $<TARGET_OBJECTS:SERVER> $<TARGET_OBJECTS:UTIL>)
 add_executable(osrm-datastore src/tools/store.cpp $<TARGET_OBJECTS:UTIL>)
-add_library(osrm src/osrm/osrm.cpp $<TARGET_OBJECTS:ENGINE> $<TARGET_OBJECTS:UTIL> $<TARGET_OBJECTS:STORAGE>)
-add_library(osrm_extract $<TARGET_OBJECTS:EXTRACTOR> $<TARGET_OBJECTS:UTIL>)
-add_library(osrm_contract $<TARGET_OBJECTS:CONTRACTOR> $<TARGET_OBJECTS:UTIL>)
-add_library(osrm_store $<TARGET_OBJECTS:STORAGE> $<TARGET_OBJECTS:UTIL>)
+add_library(osrm src/osrm/osrm.cpp $<TARGET_OBJECTS:ENGINE> $<TARGET_OBJECTS:UTIL> $<TARGET_OBJECTS:STORAGE> src/dummy.cpp)
+add_library(osrm_extract $<TARGET_OBJECTS:EXTRACTOR> $<TARGET_OBJECTS:UTIL> src/dummy.cpp)
+add_library(osrm_contract $<TARGET_OBJECTS:CONTRACTOR> $<TARGET_OBJECTS:UTIL> src/dummy.cpp)
+add_library(osrm_store $<TARGET_OBJECTS:STORAGE> $<TARGET_OBJECTS:UTIL> src/dummy.cpp)
 
 if(ENABLE_GOLD_LINKER)
     execute_process(COMMAND ${CMAKE_C_COMPILER} -fuse-ld=gold -Wl,--version ERROR_QUIET OUTPUT_VARIABLE LD_VERSION)
```

3) Then this works:

```
mkdir build
cd build
cmake ../ -G Xcode -DENABLE_MASON=ON -DBUILD_TOOLS=1
cd xcodebuild -project OSRM.xcodeproj
```

I looked for a cmake bug for this but came up short. I did find another user who hit this and worked around it with a dummy file: https://github.com/mosra/magnum/commit/fede9f3f8d72acd531f17c2ac7c4ee0bffa58c0c#diff-7bd884c6cdaf3305b9dd281ec22b5dacR26

**Comment by daniel-j-h** [comment]
@springmeyer you re-opened this - do you see anything actionable here on our side? Care to do a PR?

**Comment by ReneBrueggemann** [comment]
I found a solution for OSX 10.11.6, Xcode 8.2.1 without the dummy.cpp. Works fine so far, can someone test it for Ubuntu pls.

**Comment by wangyoucao577** [comment]
@springmeyer I had a try and it also works for me. Thanks! 
Why not just create a PR for this to merge the dummy.cpp into repo?

**Comment by springmeyer** [comment]
@DennisOSRM 👋🏼 hi :) Thanks for the issue cleanup!
