### ISSUE TITLE
Routing with Steps Crashes OSRM Server

### ISSUE THREAD

**Issue by leeedwin005** [Project-OSRM/osrm-backend#2413]
Entering URL: "http://127.0.0.1:5000/route/v1/driving/103.8960784,1.3676869;103.880996,1.375114?overview=full&steps=true" will cause the server to crash.
Using URL:"http://127.0.0.1:5000/route/v1/driving/103.8960784,1.3676869;103.880996,1.375114?overview=full&steps=false" is fine though

A "osrm-routed.exe has stopped working" warning box will appear.

What is going on?
What solutions is there?

**Comment by TheMarex** [comment]
Which version are you using and which dataset? I can't reproduce this on the demo server:

http://router.project-osrm.org/route/v1/driving/103.8960784,1.3676869;103.880996,1.375114?overview=full&steps=false

**Comment by Maximkaaa** [comment]
I've built v5.1.0-rc.2 on Windows and I have the same issue. And yes, it's not reproduced on demo-server.

**Comment by danpat** [comment]
As of 5.1, we've officially dropped Windows support.  None of the core development team have Windows machines or experience to debug this.  While we're not *actively* removing Windows support, we may add functionality at any time that does not work on Windows.

Someone with C++ and debugging experience on Windows will need to work on this.  Any volunteers?
