### ISSUE TITLE
Prefers 1st roundabout exit to a perfectly good right turn

### ISSUE THREAD

**Issue by roman-yepishev** [Project-OSRM/osrm-backend#2421]
At roundabout http://map.project-osrm.org/?z=17&center=42.528191%2C-83.359430 OSRM routes through the roundabout instead of the right turn 3/4 times:

![screenshot from 2016-05-19 13-37-26](https://cloud.githubusercontent.com/assets/601685/15403420/de809f44-1dc6-11e6-92f5-47f112292646.png)
![screenshot from 2016-05-19 13-34-10](https://cloud.githubusercontent.com/assets/601685/15403368/a8a19e1e-1dc6-11e6-8e86-349f6d08f42f.png)
![screenshot from 2016-05-19 13-33-53](https://cloud.githubusercontent.com/assets/601685/15403366/a899ace0-1dc6-11e6-9b0f-2682c33843e3.png)

When routed East from South OSRM picks the correct right turn:
![screenshot from 2016-05-19 13-34-47](https://cloud.githubusercontent.com/assets/601685/15403365/a897c786-1dc6-11e6-9a69-101f37cbb5c5.png)

I've reconfigured the roundabout about 3 days ago and made sure to follow the linking guidelines (there is a separate node for every road entering/exiting).

Could you please advise?

**Comment by danpat** [comment]
@roman-yepishev You can view the raw routing map here:

http://map.project-osrm.org/debug/

It will show you the exact speeds assigned to all roads.  If you look at your roundabout, the speed values for those turn roads you've added are very low - perhaps you need to adjust the tagging?

We usually update the map on the demo server daily.

The speed values are set based on the tags on the way.  This script:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua

is what decides on the final speed value.  You can get a rough idea of what roads get what speeds by looking at the `speed_profile` array near the top of that file.

**Comment by roman-yepishev** [comment]
@danpat, this debug view is amazing! Ok, I'll see what I can do, thank you!

**Comment by danpat** [comment]
No problemo, glad you're contributing to OSM!

I don't think there's anything actionable for OSRM here, this looks like a data problem.
