### ISSUE TITLE
CMakeLists for example.cpp could use libosrm.pc instead of FindBoost

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/osrm-backend#2432]
The result of `pkg-config --libs --static` should be enough to find and link all the required boost libraries. This could be used instead of the `FindBoost` usage at: 
https://github.com/Project-OSRM/osrm-backend/blob/c2e520ad9d354645123a6a97a501761e7846dc14/example/CMakeLists.txt#L29

The advantage would be that the same boost versions would be used that osrm-backend is built against (if duplicates were on the system) without needing to provide any extra cmake flags to point at custom boost locations.

**Comment by TheMarex** [comment]
This is fixed now. :tada:
