### ISSUE TITLE
why isn't the file osrm.level loaded in osrm-routed?

### ISSUE THREAD

**Issue by swanli** [Project-OSRM/osrm-backend#2441]
The level information is so important in CH algorithm, but I can't find any level value is used in routing service.  Haven't I missed something? Thanks very much.

**Comment by danpat** [comment]
The .level file is a cache of the contraction order.  It's only used when
you use the traffic data loading feature.  In that case, the .level cache
is used to avoid the expensive sorting step of the contraction process when
you run it for a second time top load in traffic information.

**Comment by swanli** [comment]
What is the specific meaning of  'traffic data loading feature'。 Isn't it true that in RoutingStep, we should only extend the higher level nodes to use the shortcuts as we can？

**Comment by danpat** [comment]
https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

The level cache governs the order of contraction when you are doing
frequent updates to edge weights.  The first time we contract, we cache the
order.  If we update edge weights with new speeds, we must re-contract the
graph.  Loading traffic data is usually time-sensitive, so we use the
previous contraction order to avoid that expensive step.

The cached contraction order is not optimal, but as long as the road speeds
don't change _too_ much, the contracted graph is still reasonably good for
fast queries.

**Comment by danpat** [comment]
The hierarchy is implied in the OSRM data structures - edges are sorted by
importance.  The .level file is just for multiple contraction runs.

**Comment by swanli** [comment]
Much clear now. Would you please show some code places about 'edges are sorted by
importance.'?  Thanks very much. You are so helpful.

**Comment by daniel-j-h** [comment]
https://github.com/Project-OSRM/osrm-backend/blob/ce5ae411c1f3cf12f40861831e2dcea3e8eb7979/src/contractor/contractor.cpp#L106-L109 and the `ContractGraph` function call below.

**Comment by swanli** [comment]
OK. This is the use of level cache for faster re-run. Where is the code about  'edges are sorted by
importance.'? Thanks :)

**Comment by daniel-j-h** [comment]
In the second link I posted, not only check the highlighted branch but look out for the branches where we don't have the cache (and priorities have to be assigned by means og `EvaluateNodePriority`).

**Comment by TheMarex** [comment]
Closing as solved.
