### ISSUE TITLE
Log peak STXXL/memory usage

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2445]
Because OSRM is so resource heavy (disk, RAM), we should log resource usage as an aid for server planning.

Specifically:
- [x] Track and log peak real RAM allocation
- [x] Track and log peak STXXL usage

**Comment by daniel-j-h** [comment]
@danpat hint: dump [capacity() / raw_capacity()](https://github.com/stxxl/stxxl/blob/5b9663e6b769748f3b3d3a9a779b4b89e24d7a27/include/stxxl/bits/containers/vector.h#L1037-L1047) for `stxxl::vector`.

**Comment by daniel-j-h** [comment]
This was done in https://github.com/Project-OSRM/osrm-backend/pull/3440. Closing here.

@karenzshea @miccolis might be a good idea to get statistics and alarms in place for these numbers; example how it looks like:

```
[info] STXXL: peak bytes used: 150994944
[info] STXXL: total disk allocated: 1048576000
[info] RAM: peak bytes used: 1011208192
```
