### ISSUE TITLE
Use osrm-extract output as vector tile source for map rendering?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2455]
For routing services, it's preferably that the map shown is in  sync with the routing. Achieving this typically requires duplicating the same complicated tag processing in the map render style and the OSRM Lua profiles. For example, showing oneway arrows correctly on a bike map requires handling all the relevant tags like access, oneway, oneway:bicycle, cycleway, etc.

Could the output of osrm-extract be used as a vector tile source for rendering maps with eg. mapbox gl?  That way the map styling could reuse eg. the computed forward/backward accessibility and mode for each way.

The debug vector tile server already do something like this, but as I understand it only provides the speed.

**Comment by danpat** [comment]
@emiltin Probably the best way to do this is to use the same `.pbf` file from OSM that you give to `osrm-extract` and run it through a process to create the matching tiles at the same time.

See https://osmlab.github.io/osm-qa-tiles/ for an example of this; the key tools are `mijnur`, `tippecanoe` and `tilereduce`.  There might be better workflows out there as well.

The debug tiles are extremely un-optimized for rendering - they're very inefficiently packed and would perform poorly for general use (each debug tile contains far more individual geometries than a render-optimized tile would contain, this slows down rendering speed and increases tile sizes significantly).  Storing/indexing all the tag data for rendering would also be a bit painful - there are existing tools that can do this, I don't think it'd be a good idea to bolt this onto OSRM.

**Comment by emiltin** [comment]
alright. what would be nice would be to somehow reuse the same lua profile, to avoid duplicating all the tag processing logic.

**Comment by danpat** [comment]
@emiltin yeah, the debug tiles are so temptingly close, but there's definitely a big jump from what they're doing now to usable-for-rendering :-(

**Comment by TheMarex** [comment]
Closing here, this is sadly not feasible.
