### ISSUE TITLE
pkg-config reports that libosrm depends on libtbb

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/osrm-backend#2463]
Because the code for libosrm does not depend on libtbb we should avoid pushing it into the result of `pkg-config libosrm --libs --static` to avoid downstream deps like node-osrm needing to link (and potentially bundle it).

**Comment by springmeyer** [comment]
Will work on this in #2461

**Comment by springmeyer** [comment]
Through manually removing libs and testing linking it also appears that libosrm.dylib does not depend on boost_date_time, boost_regex, libstxxl, and libz. So I'm working on trimming those libs as well.

**Comment by springmeyer** [comment]
Interesting, looks like tbb is required in Debug mode: https://travis-ci.org/Project-OSRM/osrm-backend/builds/133400593:

```
[100%] Built target osrm-contract
libosrm.a(engine.cpp.o): In function `tbb::task::~task()':
/usr/include/tbb/task.h:533: undefined reference to `vtable for tbb::task'
libosrm.a(engine.cpp.o): In function 
```

**Comment by springmeyer** [comment]
Looks like engine.cpp eventually pulls in `static_rtree.hpp` which uses tbb. So this makes sense it is needed...

**Comment by oxidase** [comment]
@springmeyer tbb in static_rtree is used only during initialization. tbb dependency can be removed after splitting initialization and query parts.

**Comment by danpat** [comment]
Clarification - there's a single constructor in `static_rtree` that makes use of `tbb`, and that constructor is only called during `osrm-extract`.

Other uses of `static_rtree` (in `osrm-contract`, `osrm-routed` and `node-osrm`) don't use that constructor, and `tbb` is not required.

We could fix this by splitting `static_rtree.hpp` into two parts (one for building/serializing the tree, one for queries).

**Comment by springmeyer** [comment]
@oxidase @danpat - thanks for the explanation. I'm comfortable keeping -ltbb in the pkg-config output given that it currently is a valid dependency of osrm-extract. I don't think it is worth splitting just for this issue. If splitting is desirable still, please feel free to create a new issue on that.
