### ISSUE TITLE
Confusing INVALID_NAME_ID and INVALID_NAMEID constants

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2466]
We have two confusingly similar constants:

`INVALID_NAMEID == std::numeric_limits<unsigned>::max()`
https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/typedefs.hpp#L72

`INVALID_NAME_ID == 0`
https://github.com/Project-OSRM/osrm-backend/blob/master/include/extractor/guidance/constants.hpp#L23

We should reconcile the logic for these, and only have one.  Possible simple option: rename `INVALID_NAME_ID` to `EMPTY_NAME_ID`.

/cc @MoKob

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/issues/2469! :tada:
