### ISSUE TITLE
Roundabout exit bearing may not always be correct

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2467]
This line:

https://github.com/Project-OSRM/osrm-backend/blob/4de64a92cb09bad75cfa43251d942dd022a63893/src/engine/guidance/post_processing.cpp#L206

is using `.back()`, but this should probably be `.front()`.  The `.intersections` list may contain all intersections that belong to the step, and the *first* one is the one immediately exiting the intersection, not the last.

We're currently getting away with `.back()` because we're in the process of building `.intersections`, but this is implied behaviour, and we should be explicit and correct about which intersection part we look at.

/cc @MoKob @TheMarex

**Comment by TheMarex** [comment]
This landed with 797f2a196b6035d5bac9e9fb60529bed7f2c86a0
