### ISSUE TITLE
Reduce ramIndex size

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#2472]
Hello, in https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/static_rtree.hpp#L431 the bottom-most level is used only to keep only one LeafNode index value  and the rectangle. 
I would suggest to remove the last level by moving the bounding rectangle into LeafNode because there are still 32 unused padding bytes in 4096 bytes pages. 

The negative side is only in moving child_is_on_disk into children id so it will reduce number of possible tree and leaf nodes to 2^31. But this should not be a problem, because the current number of leaf nodes is  22G/4K < 5400000.

The change must reduce the ramIndex size by factor 2.

**Comment by TheMarex** [comment]
This is a good suggestion. Breaking the data format for this seems fine to me. :+1: Also have no reservations with 2^31 limit on leaf nodes.

**Comment by oxidase** [comment]
@TheMarex i have created PR. i have underestimated the reduction factor, so it  must be about 128.

BTW, is there any way to check online planet statistics like in #2242 ?

**Comment by danpat** [comment]
@oxidase Here are the current filesizes from `router.project-osrm.org`:

```
    4 May 27 02:31 latest.osrm.core
    8 May 26 22:58 latest.osrm.datasource_indexes
   12 May 26 21:23 latest.osrm.properties
   12 May 26 22:58 latest.osrm.datasource_names
   20 May 26 21:23 latest.osrm.timestamp
  15M May 26 21:23 latest.osrm.restrictions
 121M May 26 21:23 latest.osrm.names
 998M May 27 02:31 latest.osrm.level
 998M May 26 22:52 latest.osrm.enw
 2.3G May 26 22:50 latest.osrm.icd
 2.8G May 26 22:56 latest.osrm.ramIndex
 5.9G May 26 22:49 latest.osrm.edges
 7.9G May 26 22:58 latest.osrm.ebg
 8.9G May 26 22:57 latest.osrm.nodes
  11G May 26 21:51 latest.osrm.geometry
  18G May 27 02:31 latest.osrm.hsgr
  22G May 26 22:56 latest.osrm.fileIndex
  25G May 26 21:23 latest.osrm
  33G May 26 17:16 latest.osm.pbf
```

**Comment by TheMarex** [comment]
This landed in `master` :tada:
