### ISSUE TITLE
Retrieve polylines with a precision of 6

### ISSUE THREAD

**Issue by Florian77711** [Project-OSRM/osrm-backend#2485]
I have noticed that in the current HTTP API (release v5.1.0) the polyline returned by e.g. the route service has a precision of 1e5.
I'm still running a server (version 4.7.1) which provides the polyline with a precision of 6.
Is there a parameter or any chance to get the polyline returned with a precision of 1e6 in the new version, or is the precision 'lost' at the extract / contract process?

I haven't found anything in the Wiki, and after serching the repository, the line 15 of the following file seems to make the precision hardcoded:
https://github.com/Project-OSRM/osrm-backend/blob/807aa71a7c80b714b7a89db9c99c15720572ba25/include/engine/polyline_compressor.hpp

**Comment by danpat** [comment]
@Florian77711 We changed the default precision to 5 to match the default precision in Google's `polyline.js` library.  Although it can be changed to 6, most people weren't, and we were fielding a constant stream of questions about it.  We decided to switch to 5 just to stop the flood of problems.

One way to approach this might be to support `polyline6` as a separate type.  I can understand the desire for 1e6 precision, but I can't think of many use-cases for anything beyond that (or less than 1e5).

@TheMarex thoughts?  This could simplify (and speed up) some of our internal API code as well....

**Comment by TheMarex** [comment]
I don't see a problem with offering `polyline6` as well.

**Comment by thrownblown** [comment]
For what its worth, changing the include/engine/polyline_compressor.hpp back to 1e6 was a trivial change.
I just finished rebuilding and reparsing my planet files and everything works as expected. If anyone else is having this issue here's my fix:
https://github.com/thrownblown/osrm-backend/commit/244f0b07810607b2cd2da6270bc8ac0b7a92e75b

**Comment by danpat** [comment]
This landed with PR #3220 , a new `geometries=polyline6` option is available.

**Comment by thrownblown** [comment]
Rad!

*Alex Farioletti*
*415.312.1674*
*tcbcourier.com <http://tcbcourier.com> *
