### ISSUE TITLE
Not clear how the shortcuts are taken precedence over original edges in RoutingStep

### ISSUE THREAD

**Issue by swanli** [Project-OSRM/osrm-backend#2486]
In a  DynamicGraph, a node has two elements: first_edge, edges. In the contraction stage, the shortcuts are added as:

 Edge &edge = edge_list[node.first_edge + node.edges];
 edge.target = to;
 edge.data = data;
 ++number_of_edges;
 ++node.edges; 

So the shortcuts are appended after to a node's original edges list.

In 'RoutingStep' function, the edges are scanned using 'facade->GetAdjacentEdgeRange(node)'  which gives a range (first_edge, first_edge + edges). So how the shortcuts strategy( or hierarchy or only search to higher level nodes) takes effect here?

**Comment by MoKob** [comment]
The hierarchy only has access to edges leading to nodes that are higher up in the hierarchy. All other edges are removed from the graph.

In how far a shortcut or another node is used is dependent of the order in which Dijkstra's algorithm scans the vertices. Usually a shortcut will reach a node earlier and be preferred over a route using multiple hops. These cases can happen if a shortcut was inserted even though it was not necessary.

For the most part, the searches to limit the use of unnecessary shortcuts during contraction should limit these cases to only very few instances.

In general, which of many equivalent routes the search may find is not possible to specify without an exact contraction order.

**Comment by MoKob** [comment]
Closing here since not actionable. Feel free to reopen if question still remains.
