### ISSUE TITLE
Some understanding problems in 'struct SearchEngineData'

### ISSUE THREAD

**Issue by swanli** [Project-OSRM/osrm-backend#2487]
Can anybody give a clear explanation about the usage of the six heaps in 'struct SearchEngineData':

static SearchEngineHeapPtr forward_heap_1;
static SearchEngineHeapPtr reverse_heap_1;
static SearchEngineHeapPtr forward_heap_2;
static SearchEngineHeapPtr reverse_heap_2;
static SearchEngineHeapPtr forward_heap_3;
static SearchEngineHeapPtr reverse_heap_3;

For a bidirection Dijkstra search, I think two heaps are enough? I know there are some corner issues, I just can't get a clear clue now :) Thanks very much.

**Comment by danpat** [comment]
@swanli On a simple search, you're correct, only two heaps are needed.  However, OSRM supports a few additional search types, such as:

  - searching on partially contracted graphs (requires a separate heap for core search)
  - alternative path finding (requires separate heap for alt route)

If you simply `grep` the codebase for the variables you've listed above, you'll notice that the `_2` and `_3` heaps are used in certain specialized places.  The basic `shortest_path` case on a fully contracted graph (no core) only uses `forward/reverse_heap_1`.

It's probably a bit of a design smell to have them declared as `_2` and `_3` like this, as it's not obvious what they're for.

**Comment by swanli** [comment]
Got it。 Thanks a lot. Issue https://github.com/Project-OSRM/osrm-backend/issues/2486 is my last big confuse now. You are so helpful if you can give me some explanations.

**Comment by TheMarex** [comment]
Closing as not actionable.
