### ISSUE TITLE
Relase OSRM 5.2.0 RC2

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2494]
- [x] Merge in `node-osrm` https://github.com/Project-OSRM/node-osrm/pulls (currently working on a `docs` rebase, can be merged later)
- [x] revert https://github.com/Project-OSRM/osrm-backend/pull/2489
- [x] Merge in `osrm-backend` https://github.com/Project-OSRM/osrm-backend/milestones/5.2.0
- [x] Check if changelog is up to date
- [x] Tag `osrm-backend` `5.2.0-rc.2`
- [x] Pin `osrm-backend` version in `package.json` in `node-osrm` to `rc.2`
- [x] Check if build is passing
- [x] Publish binaries: `git commit --allow-empty -m "[publish binary] v5.2.0-rc.2"`
- [x] Tag `node-osrm` `5.2.0-rc.2`

**Comment by MoKob** [comment]
Added a revert of https://github.com/Project-OSRM/osrm-backend/pull/2489, due to broken behaviour.

**Comment by freenerd** [comment]
Released 🎉
