### ISSUE TITLE
Polyline encoding produces coordinates with the decimal point in the wrong place

### ISSUE THREAD

**Issue by andrewharvey** [Project-OSRM/osrm-backend#2498]
The request [`https://router.project-osrm.org/viaroute?instructions=true&z=10&loc=-33.867984,151.209825&loc=-33.869081,151.209677`](https://router.project-osrm.org/viaroute?instructions=true&z=10&loc=-33.867984,151.209825&loc=-33.869081,151.209677) returns a polyline `|kcr_A_ubl_HrcAdH`. 

According to both https://github.com/mapbox/polyline and https://developers.google.com/maps/documentation/utilities/polylineutility this polyline is
`[[-338.67983,1512.09824],[-338.69081,1512.09677],[-338.69087,1512.09677]]` The decimal places are out!

This is affecting the production Mapbox Directions API too... https://api.mapbox.com/v4/directions/mapbox.driving/151.21%2C-33.868%3B151.272675%2C-33.890417.json?geometry=polyline&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpbG10dnA3NzY3OTZ0dmtwejN2ZnUycjYifQ.1W5oTOnWXQ9R1w8u3Oo1yA demonstrates this.

**Comment by johnnyluu** [comment]
+1 Having the same issue

**Comment by TheMarex** [comment]
1. You are hitting the deprecated API endpoint. Please use the OSRM 5.0 API format: https://router.project-osrm.org/route/v1/driving/151.209825,-33.867984;151.209677,-33.86908?steps=true This has a polyline with precision 5.

2. Your are hitting the old API endpoint for Mapbox Directions. Try https://api.mapbox.com/directions/v5/mapbox/driving/151.21%2C-33.868%3B151.272675%2C-33.890417.json?geometries=polyline&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpbG10dnA3NzY3OTZ0dmtwejN2ZnUycjYifQ.1W5oTOnWXQ9R1w8u3Oo1yA This has a polyline with precision 5.

3. The docs for the _old_ APIs specified that we encode the polyline with precision 6.  https://github.com/Project-OSRM/osrm-backend/wiki/Server-API---v4,-old and https://www.mapbox.com/api-documentation/directions-v4.html

**Comment by daniel-j-h** [comment]
You're using v4 both locally as well as in the Mapbox Directions API.

In v4 the polyline format had a precision of 6 (more precise than the default), which led to users regularly stumbling into the exact same problem you are seeing :) That's the reason we changed it to the default precision of 5 in v5.

v4: https://github.com/Project-OSRM/osrm-backend/wiki/Server-API---v4,-old#response-1 
v5: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#request

Either specify the precision for your polyline library (or divide it out), or simply use the latest stable v5 release.

**Comment by andrewharvey** [comment]
Thanks for the explanations, that makes sense now.

**Comment by mecoFarid** [comment]
@daniel-j-h I believe Mapbox Navigation still uses precision 6 to decode the LineString. I printed out route in Mapbox Navigation and, yes it was decode with precision 6. Do you, by chance, know any way to change default decoding precision to 5 in MapBox Navigation? Sorry for almost unrelated question.

**Comment by daniel-j-h** [comment]
The Mapbox Directions API allows you to request precision 5 and precision 6 polyline encoded geometries, check the geometries parameter here:

https://www.mapbox.com/api-documentation/#retrieve-directions
