### ISSUE TITLE
Support running on 32bit platforms

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2502]
By cleaning up a lot of the assumptions in the codebase, it should be possible to run OSRM on a 32bit platform.  64bit CPU/memory is not strictly required if your dataset is small enough.  We shouldn't need a lot of `#ifdef`, we just to be explicit about some assuptions, and add some bounds checking.

Off the top of my head, the hitlist of things that would need fixing are:
- [ ] Fix usages of `std::size_t` to a known bitsize
- [ ] Ensure datafile compatibility between 32/64bit platforms (i.e. we currently write `std::size_t` values to files, which change between platforms) Related: https://github.com/Project-OSRM/osrm-backend/issues/2242
- [ ] Check explicitly for overflows at critical spots - we definitely know we have datasets that won't fit

/cc @oxidase

**Comment by oxidase** [comment]
@danpat  please check #2504. I have added two Travis jobs: 
* gcc-5-release-i686 that builds 32bit intel code with SSE FP to have the same FP behavior as x86_64 and runs all tests
* gcc-4.8-release-armhf that just cross-compiles without running tests. There is no technical problems to build and run tests in ARM emulation environment , but it will be slow.

I  checked npm and unit tests on Raspberry Pi 3 with MATE  - the tests are ok with 18a4903. Without 18a4903 neon/vfp optimizations must be switched off.

The three points:
* just found 2 related places where i changed size_t to uint64_t in e15cfe8
* i checked compatibility with the patch
[0001-hashing.txt](https://github.com/Project-OSRM/osrm-backend/files/310872/0001-hashing.txt)
that allows to use preprocessed data by 32/64 bit tools in npm tests.
* did not address the last point, i would need statistics for the planet data or datasets that could overflow 32bit
