### ISSUE TITLE
Hangs on [extractor] Building node id map

### ISSUE THREAD

**Issue by tanjentman** [Project-OSRM/osrm-backend#2506]
Hi everyone, whenever I try to perform **osrm-extract -p profile.lua NorthAmerica.osm.pbf** (where profile is car and NorthAmerica is from Geofabrik) my computer hangs for over 24 hours on **[extractor] Building node id map**.  The file size is around 7GB.  Now if I perform the same operation on a 1.7GB file like US-South.osm.pbf it completes in around 2-3 hours.  I have my .stxxl.txt set to **disk=C:\OSRM\stxxl,600G,wincall**.  Any suggestions?

**Comment by danpat** [comment]
@tanjentman How much RAM do you have available?  Even with STXXL, the `extract` process requires quite a lot of memory.  If you exceed the RAM requirements and start to use swap space, you will see an enormous slowdown.

As a reference point, I cannot process `north_america.osm.pbf` from Geofabrik on my laptop with 16GB of RAM without inducing a swap storm.  I have never bothered trying to run it to completion.

**Comment by tanjentman** [comment]
Hi danpat, thanks for the quick response!  I was afraid you might say that.  I am only running 8GB on my machine...looks like it's time to try processing on an Amazon EC2 server.  Any recommendation on the RAM?

**Comment by danpat** [comment]
I have been able to process `us_west.osm.pbf` locally with 16GB.  I'd try whatever EC2 instances is the next size up from 16GB.

Here at Mapbox, we process north-america extracts on much bigger machines (we multi-purpose these machines), and they take about an hour.  If it takes more than 2-3 hours, then I'd stop the job and make the machine bigger.

**Comment by tanjentman** [comment]
Thank you!
