### ISSUE TITLE
Could an example curl request be shown in the documentation for the match service

### ISSUE THREAD

**Issue by hmaeda** [Project-OSRM/osrm-backend#2507]
Hello I would like to use the [match service](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-match) from osrm, as it is not clear how the timestamps would be incorporated into the curl requests.

Please can a simple working example be provided in the documentation.

Thanks,

HLM

**Comment by ardanika** [comment]
Here is one example:
http://router.project-osrm.org/match/v1/driving/-79.304673,43.668978;-79.304166,43.669123;-79.304229,43.669109?timestamps=1466604780;1466604790;1466604804&overview=full

**Comment by daniel-j-h** [comment]
Thanks for this example. Seems like this ticket slipped through. Sorry for that.

I'm closing this as not actionable. The documentations says for the `timestamps` parameter:
> {timestamp};{timestamp}[;{timestamp} ...]
