### ISSUE TITLE
match service misses out the first point?

### ISSUE THREAD

**Issue by hmaeda** [Project-OSRM/osrm-backend#2510]
Hello, i am using the match service with the following example.

`http://router.project-osrm.org/match/v1/driving/-2.90170001983643,53.2753219604492;-2.90952491760254,53.2695121765137;-2.90631008148193,53.246208190918;-2.89598321914673,53.2206382751465;-2.89439177513123,53.1976165771484;-2.89574503898621,53.1803092956543?timestamps=1412209106;1412209226;1412209346;1412209466;1412209586;1412209706&overview=full&geometries=geojson&annotations=true`

And it looks like it works...but from the 6 GPS points provided as input, it looks like only the last 5 have been map matched....when running other routes through the match service the full route seems to be fully picked up...is it a problem with the first point that has been provided? or a broader problem with the match service?

**Comment by TheMarex** [comment]
If you look at the first entry in `tracepoints` it is `null`. That means it could not be map matches because it is too nosy or does not fit to the rest of the route. Please read the documentation https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#response-4
