### ISSUE TITLE
meta data when `annotations=true`

### ISSUE THREAD

**Issue by hmaeda** [Project-OSRM/osrm-backend#2511]
when running a API `match` or `route` service query using the following options 

`overview=full&geometries=geojson&annotations=true`

This sometimes results in multiple legs, what is the cause of multiple legs?

From looking a fair few results, for each leg...the number of elements of node data returned is always 1 greater than the number elements of distance and duration data.

For a single leg response, the number of nodes matches the number of lat-long pairs provided by the geometry coordinates, so I assume the order of the nodes matches that of the order of the lat-long pairs? If this is the case, where can I find the database that matches node to lat-long.

When there are multiple legs, the total number of nodes provided across all legs is sometimes different to the total number of lat-long pairs provided by the geometry coordinates. Should there not be a 1-1 match between the number of lat-long pairs vs the number of nodes provided? and similarly how would the distance and duration data points from the response be allocated across the geometry coordinates?

Finally specifically for the `match` service, is there a way to re-estimate the full route with the interpolated timestamps as well as the map-matched coordinates?

**Comment by TheMarex** [comment]
> This sometimes results in multiple legs, what is the cause of multiple legs?

The expected response of the match public is that you see `#trace-points - 1` legs. This can be lower if trace points are dropped due to noise.

> From looking a fair few results, for each leg...the number of elements of node data returned is always 1 greater than the number elements of distance and duration data.

There is an id entry for each node, but a distance/duration entry for each segment (#nodes - 1).

> total number of lat-long pairs provided by the geometry coordinates. 

You will see duplicates due to the end-points of legs. If you have two legs `(1, 2, 3)` and (`3, 4, 5, 6)` the geometry will contain the points `1, 2, 3, 4, 5, 6` but if you simply concatenate the node ids it will be `(1, 2, 3, 3, 4, 5, 6)` because you neglected to deduplicate the intermediate point `3`.

> Finally specifically for the match service, is there a way to re-estimate the full route with the interpolated timestamps as well as the map-matched coordinates?

Can you explain more? I'm not sure what you mean by this.

**Comment by hmaeda** [comment]
Thank you for your detailed comments that is very helpful.

With regard to your comments about not being able to 'simply concatenate the node ids' can you please help me in understanding how I would be able to get the correct node ids corresponding to each row in the geometry coordinates for the following curl request:

`http://router.project-osrm.org//match/v1/driving/-2.90133333206177,53.2752685546875;-2.91326332092285,53.2777099609375;-2.93595004081726,53.2710990905762;-2.92908668518066,53.2621765136719;-2.92908668518066,53.2621765136719;-2.92908668518066,53.2621765136719;-2.92908668518066,53.2621765136719;-2.92908668518066,53.2621765136719;-2.92908668518066,53.2621765136719;-2.92908668518066,53.2621765136719;-2.92545509338379,53.2642478942871;-2.9108567237854,53.2651519775391;-2.90671324729919,53.276294708252;-2.90268158912659,53.275634765625?timestamps=1412228691;1412228811;1412228931;1412229051;1412229171;1412229291;1412229411;1412229531;1412229651;1412229771;1412229891;1412230011;1412230131;1412230251&overview=full&geometries=geojson&annotations=true`

I think the issue here is that the input data includes duplicated lat-longs when the vehicle was stationary for while. How is this handled via the map-matching algo?

With regard to my comment about timestamps that you were asking for more information about. Given the main purpose of map-matching might be to re-create a trip from 'sparse' GPS data using timestamps  to help the algorithm. However despite the map-matching service taking in timestamps, it only outputs geospatial locations (lat-longs) of a map-matched route. It currently does not output the implied timestamps for the map-matched route. The current service does have some duration data in the output, but it does not match up to input timestamps. So I was wondering if it would be possible to use both the input timestamps as well as the expected durations of different parts of a route to create a new set of interpolated timestamps for each lat-long pair of the geometry coordinates data.

**Comment by danpat** [comment]
@hmaeda The input timestamps are used to estimate speeds between coordinates, nothing more.  OSRM has no concept of "a route at a particular time", so we can't return adjusted timestamps.  A route starts at time 0, and continues until it reaches the total duration.  If you like, you can simply add each returned duration to your own initial timestamp, but given that OSRM only contains a model of vehicle travel speeds, it likely won't align with the timestamps in your original data.

**Comment by danpat** [comment]
Nothing actionable for OSRM here, the `match` service will not interpolate user-supplied timestamps.
