### ISSUE TITLE
purpose of version and profile options in api calls?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2512]
the documentation states:

version: Version of the protocol implemented by the service.
profile: Mode of transportation, is determined by the profile that is used to prepare the data

for version, only "v1" works. when will this change?

the profile option doesn't have any effect since the profiles really depends on how you prepared the data. so why is in it the api? is the intention to use e.g. apache to rewire to different osrm instances depending on this part of the url? (something we already do with v4 for our ibikecph service)

**Comment by TheMarex** [comment]
> for version, only "v1" works. when will this change?

This will be bumped when we break the API version. It is meant to allow easy URL switches:

`route/v1` goes to OSRM 5.2.0, `route/v2` goes to OSRM 6.0.0

> the profile option doesn't have any effect since the profiles really depends on how you prepared the data. so why is in it the api?

No this is just reserved for future usage and would enable to use multiple profiles with the same osrm instance (think named datasets).

**Comment by emiltin** [comment]
ok thanks. 
why not use v5, v6 etc?

**Comment by TheMarex** [comment]
Each API is versioned independently so you will know exactly what broke or didn't on a major osrm version bump.

**Comment by daniel-j-h** [comment]
Closing this since it's not actionable for us.
