### ISSUE TITLE
Add cross-compilation support for ARMv7 on Travis

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2513]
In the vein of https://github.com/Project-OSRM/osrm-backend/pull/2503 we should make sure this does not regress again. The best way to do this is to add an automatic test.

@springmeyer how hard do you think it would be to use the gcc-cross-compiler toolchain on travis? (For building `osrm-routed` only - initially). Getting the tests to run will be a little more involved but that is a different problem.

**Comment by oxidase** [comment]
Hi, i tested already armhf build locally and it builds ok, so i can add another travis build similar to -m32. It is also possible to run unit tests and npm tests via qemu, but have no idea about performance due to doubled virtualization.
