### ISSUE TITLE
I get InvalidUrl 

### ISSUE THREAD

**Issue by zzyber** [Project-OSRM/osrm-backend#2515]
Can someone help me out here? I have installed according to the tutorial https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04 but I'm stucked when I give the command osrm-routed map.osrm and then test it with http://your_server_ip:5000

I use a system called traccar today and in the backend we have https://router.project-osrm.org/match to handle "snap to roads". I now try to make our own service but can't figure out how to setup the last part and test it.
If i try https://router.project-osrm.org/match I get "invalid coordinates"
and if I try http://your_server_ip:5000/match  I get "invalid Url"
So I read the path should be /match/v1/driving but still I get "Invalid Url"

What is wrong here, help appreciated very much right now.

**Comment by emiltin** [comment]
you need to add locations as part of the url. check the docs at https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

**Comment by zzyber** [comment]
Thanks but I do not need that in https://router.project-osrm.org/match where I get invalid coordinates. Something is not right.
Can you suggest an URL that would do it for me. 
When I try this: http://your_server_ip:5000/route/v1/driving/7.416351,43.731205;7.420363,43.736189 I get something......am I on the right track here?

**Comment by zzyber** [comment]
For now its up and running on 188.240.222.181 if someone wants to try it out to direct me. Thanks

**Comment by danpat** [comment]
I just hit `http://188.240.222.181:5000/route/v1/driving/7.416351,43.731205;7.420363,43.736189` and it returns:

```
{"code":"Ok","routes":[{"geometry":"gy_qIadgmA??","legs":[{"summary":"","duration":0,"steps":[],"distance":0}],"duration":0,"distance":0}],"waypoints":[{"hint":"HgEVgCABFYAAAAAAAAAAAAcAAAAAAAAAzwAAAH6FAwDHcAQANQEAACqjwwBsEE0DHypxAAVJmwIAAAEB906gEQ==","name":"","location":[12.82129,55.382124]},{"hint":"HgEVgCABFYAAAAAAAAAAAAcAAAAAAAAAzwAAAH6FAwDHcAQANQEAACqjwwBsEE0DyzlxAH1cmwIAAAEB906gEQ==","name":"","location":[12.82129,55.382124]}]}
```

Are you using a command-line tool to hit that URL?  If so, make sure you put quotes around it, the `;` is a command separator in `sh`.

**Comment by zzyber** [comment]
No I´m using my browser. The /match path is what I want to get my grip on and it makes me so frustrating that  https://router.project-osrm.org/match gives wrong coordinates but when I issue http://188.240.222.181:5000/match/v1/driving/ I get {"message":"URL string malformed close to position 18: \"ng\/\"","code":"InvalidUrl"}

**Comment by danpat** [comment]
@zzyber `router.project-osrm.org` is running both OSRM v4.x (`/match`) and OSRM v5.x (`/match/v1/driving`), for backwards compatibility.  If you've done your own build from the `master` branch, you will only have v5.x locally.

If I hit `http://188.240.222.181:5000/match/v1/driving/7.416351,43.731205;7.420363,43.736189` I get `{"message":"Could not find a matching segment for any coordinate.","code":"NoSegment"}`, which is a normal error if no match is found.

**Comment by zzyber** [comment]
Thanks, that was exactly what I needed to hear, I can rest and go forth then.
