### ISSUE TITLE
Dependence of output data from input data variations

### ISSUE THREAD

**Issue by emmexx** [Project-OSRM/osrm-backend#2516]
I'm trying to narrow down the cause of routing problems using custom osm-like data.
I use qgis to manage bike routes saved on postgresql/postgis/geoserver.
I created a postgresql functions that transform the db data to a format compatible with osm.
Then I use osmosis to create a pbf file from those data.
Finally I use that pbf with osrm.

The problem:
when I change the data with qgis (even if I move only one node) i get undesired consequences on routing. Ways that were connected aren't anymore. Ways that should be connected aren't.

I don't know where the problem arises. So my question is: a small variation in input data (pbf with a single node coordinates changed) can change the routing result or give way to disconnected ways?

  maxx

**Comment by emiltin** [comment]
there might be two or more possible routes from A to B that are almost the same distance. changing a single mode might cause osrm to pick another route that could be very different.

**Comment by emmexx** [comment]
The bike routes are from a national network and rather sparse. The alternate routes proposed are usualy tens or hundreds of kilometers away.
One thing I found out is that qgis uses a different approximation of the coordinates. I used josm to create the bulk of the routes and josm approximates at 6 decimals. qgis approximates at 10 or 12 decimals. Rounding all nodes coordinates to 6 decimals solved part of the routing problem, I don't know why.

**Comment by emiltin** [comment]
osmosis can read postgis and write osm (as pbf or xml), as long as you use the right postgis scheme:
http://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.44#--read-pgsql_.28--rp.29

**Comment by emmexx** [comment]
I followed the Osmosis help when creating the tables that I use to generate the pbf.

**Comment by TheMarex** [comment]
I would guess that the import/export form QGIS somehow destroys the connectivity. That means ways that would be connected at endpoints are not connected anymore. I'm not sure what format QGIS uses internally but if it identifies nodes only over coordinate position not over ID rounding errors would create such disconnected ways.

Anyway I don't think this is an OSRM related problem. This is something for stackoverflow or the QGIS bug tracker.

**Comment by emmexx** [comment]
I agree. Rounding coordinates to 6 decimals (I did it after posting here) solved 90% of the problems.
Qgis doesn't use ids or topology to connect lines.

**Comment by karme** [comment]
emmexx <notifications@github.com> writes:

> I agree. Rounding coordinates to 6 decimals (I did it after posting here) solved 90% of the problems.
> Qgis doesn't use ids or topology to connect lines.

afair there was some option to fake topology editing? (but i may be wrong there)

**Comment by emmexx** [comment]
There is the snapping feature with topology options but anyway my postgis table doesn't use topology.
