### ISSUE TITLE
Error in bilinear interpolation in raster_source

### ISSUE THREAD

**Issue by kaligrafy** [Project-OSRM/osrm-backend#2518]
Line 16 of src/extractor/raster_source.cpp should be:
 `const float fromLeft = (lon - left * xstep - xmin) / xstep;`
instead of
 `const float fromLeft = (lon - left * xstep + xmin) / xstep;`

Can somebody confirm it should be a minus sign before xmin?

Pull request: https://github.com/Project-OSRM/osrm-backend/pull/2517

**Comment by lightmare** [comment]
The expression looks unnecessarily complicated, which may have contributed to the error. Your corrected version can be simplified to:
```c++
const float fromLeft = xthP - left;
```

**Comment by TheMarex** [comment]
@lightmare good catch. Adapted the code and fixed this.
