### ISSUE TITLE
Can't get the match service to work.

### ISSUE THREAD

**Issue by ardanika** [Project-OSRM/osrm-backend#2522]
I can't get results for a **match** query using v5.2.0-rc.2. I doesn't seem to work with the demo server either. I get {"message":"Could not find a matching segment for any coordinate.","code":"NoSegment"} response. If I use the version 4 api it works fine.

V5
http://router.project-osrm.org/match/v1/driving/43.554423,-80.555322;43.554622,-80.55542;43.554822,-80.555516;43.555026,-80.555614;43.55523,-80.555715;43.555433,-80.555815;43.555638,-80.555916;43.555842,-80.556016;43.556045,-80.556116;43.556247,-80.556215;43.556449,-80.556314?timestamps=1462834789;1462834790;1462834791;1462834792;1462834793;1462834794;1462834795;1462834796;1462834797;1462834798;1462834799

V4
http://router.project-osrm.org/match?loc=43.554423,-80.555322&loc=43.554622,-80.55542&loc=43.554822,-80.555516&loc=43.555026,-80.555614&loc=43.55523,-80.555715&loc=43.555433,-80.555815&loc=43.555638,-80.555916&loc=43.555842,-80.556016&loc=43.556045,-80.556116&loc=43.556247,-80.556215&loc=43.556449,-80.556314

**Comment by danpat** [comment]
@ardanika The coordinate order in V5 change to `lon,lat`.  Try swapping your coordinates.

**Comment by ardanika** [comment]
@danpat Thanks. Did the order of lat and lng also changed when encoding/decoding polylines?

**Comment by danpat** [comment]
@ardanika No, the polyline spec defines `lat/lon` order, so they need to stay the same.  However, the polyline precision has changed from 6 places to 5, so if you see results like `-1333.723` degrees when you expect `-133.3723`, then check that you're using 5 decimal places, not 6.

Closing here as there's nothing actionable on our end.
