### ISSUE TITLE
new name - when road turns?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2523]
docs states that "new name" maans that "no turn is taken, but the road name changes. The Road can take a turn itself, following modifier"

if find this a bit confusing. if you turn and the way also changes name, isn't that a normal turn? or is "new name" only emitted if you cannot turn into any other way?

**Comment by MoKob** [comment]
@emiltin it's only emitted if its the only choice.
Situations like [here](http://www.openstreetmap.org/#map=18/52.41278/13.20165) emit a `new name` with a direction modifier.
You can't do anything but follow the road, but the name changes.

**Comment by emiltin** [comment]
thank you. i intended to update the wiki to clarify this a bit, but i now realise i actually edited the following file in the master branch, since the documentation now lives in the repo:

https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

sorry for that, hope it's not a problem.
