### ISSUE TITLE
what modifiers can accompany each turn instruction?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2524]
what modifiers can accompany the different instructions?

i ask because i'm trying to create i18n string for the various instructions and i'm wondering if i need strings for edge cases like merge using straight ahead or fork with sharp/slight right.

**Comment by emiltin** [comment]
i looked at the osrm demo (and thus LRM) but it seems it handles merge, fork, end of road etc. like normal turns. are there any examples of how to generate natural language strings for instructions like merge, fork, end of road, etc?

**Comment by MoKob** [comment]
@emiltin I will try and get you a comprehensive list of what is possible (updating the documentation that is). But it might take me a few days.

**Comment by emiltin** [comment]
thanks

**Comment by MoKob** [comment]
This is an overview at its current state: Keep in mind that this could always change and that it is not a comprehensive list created from the planet:


| Type | uturn | sharp right | right | slight right | straight | slight left | left | sharp left |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| New Name | - | + | + | + | + | + | + | + |
| Continue | + | + | + | + | + | + | + | + |
| Turn | + | + | + | + | + | + | + | + |
| Merge | - | - | + | + | - | + | + | - |
| OnRamp | - | + | + | + | + | + | + | + |
| OffRamp | - | - | + | + | (+) | + | + | - |
| Fork | - | - | + | + | + | + | + | - |
| EndOfRoad | - | - | + | - | - | - | + | - |
| Notification | - | + | + | + | + | + | + | + |
| Roundabout Types | + | + | + | + | + | + | + | + |
| Use Lane | - | - | - | - | + | - | - | - |

 - I am not a hundred percent sure, but off ramps going straight should be suppressed
 - Straight Fork requires a tripple fork
 - The problem with roundabouts is that the mapping in OSM is not very consistent and often stuff is tagged wrongly as roundabout. These are not yet all captured, so roundabouts can have all types. For roundabout - turns it is naturally true that all types can be returned. For others we would expect only left/right types.

**Comment by MoKob** [comment]
@emiltin when you don't have follow-up questions, feel free to close here as nothing would be actionable anymore.

**Comment by emiltin** [comment]
Thank you, that's useful. Closing.
