### ISSUE TITLE
should not emit continue uturn when going sharp left

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2528]
seems continue sharp left would make more sense in the following situation.

situation:
![screen shot 2016-06-10 at 14 25 04](https://cloud.githubusercontent.com/assets/66034/15964125/36446d12-2f17-11e6-8b20-62c1ce28cea8.png)

response:
```json
{
  "waypoints": [{
    "location": [12.580808, 55.657071],
    "hint": "mUwAgP___39fBQAAngAAACUBAADNBAAAeAAAAMUsAADBLAAAVwcAAMj3vwBvQlED3ve_AG5CUQMKAAYGwiCf8g==",
    "name": "{highway:path}"
  }, {
    "location": [12.581422, 55.656831],
    "hint": "mkwAgP___39fBQAARAAAAGIAAADmAAAAyAEAAL0sAADILAAAVwcAAC76vwB_QVEDLPq_AIhBUQMFAAYGwiCf8g==",
    "name": "{highway:path}"
  }],
  "routes": [{
    "distance": 91.9,
    "duration": 72.4,
    "legs": [{
      "distance": 91.9,
      "steps": [{
        "distance": 42.3,
        "duration": 42.6,
        "name": "{highway:path}",
        "maneuver": {
          "type": "depart",
          "location": [12.580808, 55.657071],
          "bearing_before": 0,
          "bearing_after": 187
        },
        "geometry": "uourIaexkAf@F`@N",
        "mode": "pushing bike",
        "intersections": [{
          "location": [12.580808, 55.657071],
          "bearings": [187],
          "entry": [true],
          "out": 0
        }]
      }, {
        "distance": 49.6,
        "duration": 29.8,
        "name": "{highway:path}",
        "maneuver": {
          "type": "continue",
          "modifier": "uturn",
          "bearing_before": 194,
          "bearing_after": 71,
          "location": [12.580691, 55.656697]
        },
        "geometry": "kmurIidxkACQAYEQK]?QAc@",
        "mode": "pushing bike",
        "intersections": [{
          "location": [12.580691, 55.656697],
          "bearings": [75, 195],
          "entry": [true, true],
          "in": 0,
          "out": 0
        }]
      }, {
        "distance": 0,
        "duration": 0,
        "name": "{highway:path}",
        "maneuver": {
          "type": "arrive",
          "location": [12.580691, 55.656697],
          "bearing_before": 81,
          "bearing_after": 0
        },
        "geometry": "enurI{hxkA",
        "mode": "pushing bike",
        "intersections": [{
          "location": [12.581422, 55.656831],
          "bearings": [261],
          "entry": [true],
          "in": 0
        }]
      }],
      "duration": 72.4,
      "summary": "{highway:path}"
    }],
    "geometry": "uourIaexkAf@F`@NCQAYEQK]?QAc@"
  }],
  "code": "Ok"
}
```

**Comment by MoKob** [comment]
@emiltin this is due to miss-use of the name-tags. OSRM by now highly uses names to find where a route continues on the same path. Since all of the roads here miss-use the name tag, the behaviour breaks.

**Comment by emiltin** [comment]
well, our bike profile encodes the highway tag into the name field if the osm name empty. this enable the front-end to display meaningful information like 'turn left at bicycle path'.

in any case, why is the modifier "uturn"? the actual turn has angle 194-71 = 123. this seems like a sharp turn, not a u-turn, as can also be seen from the image.

**Comment by MoKob** [comment]
Because this is not distinguishable from a situation like:
```
d --- c
                  e   --------  f
a --- b
```
Where a road with a middle island merges into a single street.
You can turn from a--b to c---d which would be a u-turn in this case.

**Comment by MoKob** [comment]
A possible solution here could be to use an *escape scheme* in the names that allows to detect encoded data in comparison to normal names and treat it as such.

**Comment by emiltin** [comment]
or have a proper way to pass required osm tags, instead of having to stuff them into the name

**Comment by emiltin** [comment]
announcing a 120 degree turn as a u-turn doesn't seem optimal. mayobe two or more turns within a certain range (e.g. 20-30 m) be viewed as a u-turn?

120 degree (my example)= sharp turn 
120 degree followed by 60 degree ( your example) = 180 = u-turn

**Comment by MoKob** [comment]
@emiltin I can now go through OSM and find all the instances were it does make sense to announce it as a u-turn.

Roads that have the same name and are connected directly to each other are considered the same road.

<img width="866" alt="screen shot 2016-06-13 at 09 44 32" src="https://cloud.githubusercontent.com/assets/12932279/16000258/8fb85062-314b-11e6-96ed-39ddb84699ed.png">

The case above does not fall into your criterion but is definitely a u-turn as you are travelling in the same direction on the street.
I will have a look and see if I can improve that behaviour. Since you are miss-using OSM tags for something that is not intended in OSRM, the behaviour will always be unexpected.

**Comment by MoKob** [comment]
I've looked at the code, and from what I see your path should never emit u-turn, since all roads can be entered. [Here](https://github.com/Project-OSRM/osrm-backend/blob/e9a0beb4e883e4f020fe8c5a50fd78ade040c8f9/src/extractor/guidance/intersection_generator.cpp#L186) we check if one of the roads cannot be entered.

I also wrote a cucumber test
```
Node Version v4.0.0
@routing @guidance @bike
Feature: Unnamed Paths

  Scenario: Turn off a road with missued names   # features/guidance/bike/unnamed-bike-paths.feature:8
    Given the profile "bicycle"                  # features/step_definitions/data.js:8
    Given a grid size of 30 meters               # features/step_definitions/data.js:20
    Given the node map                           # features/step_definitions/data.js:45
      | a |  | d |
      |   |  |   |
      |   |  |   |
      |   |  |   |
      | b |  |   |
      |   |  |   |
      | c |  |   |
    And the ways                                 # features/step_definitions/data.js:128
      | nodes | highway | name           |
      | abc   | path    | {highway:path} |
      | bd    | path    | {highway:path} |
    When I route I should get                    # features/step_definitions/routing.js:4
      | waypoints | route                                        | turns                             |
      | a,d       | {highway:path},{highway:path},{highway:path} | depart,continue sharp left,arrive |

1 scenario (1 passed)
5 steps (5 passed)
0m00.166s
```

Which version of OSRM are you using. At least with the current build, this seems not to be an issue after all.

**Comment by emiltin** [comment]
I'm using the tag v5.2.0.

Encoding the highway in the way name is done in the standard bike profile here:
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/bicycle.lua#L224

```lua
result.name = "{highway:"..highway.."}"
```

**Comment by MoKob** [comment]
I am just saying: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/bicycle.lua#L223

**Comment by emiltin** [comment]
i can't reproduce this on master either, so closing.
