### ISSUE TITLE
also emit slight_left/right direction modifers in arrival instructions

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2532]
for arrival instructions, it seems the modifier can only have the following values: left, straight, right.

it should use slight_left and slight_right as well, if the destination is close to +/- 45 degree ahead from the end of the road network.

situation (currently emits modifier=straight):
![screen shot 2016-06-11 at 09 51 23](https://cloud.githubusercontent.com/assets/66034/15983982/1b8595e8-2fba-11e6-8889-e5dfb3b6d807.png)

**Comment by MoKob** [comment]
@emiltin what would you feel would be the improvement in the instruction? Your destination is `slightly ahead of you and to the left` feel weird to me.

**Comment by emiltin** [comment]
i think it might useful to indicate in what direction the final goal is.
it might also be more consistent with other instructions that can emit slight, normal, sharp.

**Comment by TheMarex** [comment]
This is only a heuristic anyway. I don't think we need to be overly verbose here. Three directions are enough for everyone. :wink:
