### ISSUE TITLE
osrm-prepare uses excessive memory, really really really

### ISSUE THREAD

**Issue by kolstad** [Project-OSRM/osrm-backend#2534]
I am trying to make a map to route North America and have downloaded the sub-map of the world.
I am having trouble finishing the osrm-prepare operation.
The 'top' program reports that it wants more than 430GB of RAM.  I made what I thought was a
pretty big swap space, but alas.
I believe I've built the latest sources.
Can there be any relief for this? LUA is linked from version 5.2.

kolstad@ubuntu:~/osrm$ free -k
              total        used        free      shared  buff/cache   available
Mem:       99004504      392980    97842344        4224      769180    98065856
Swap:     399359992      157696   399202296

Thanks for any suggestions.

RK

**Comment by danpat** [comment]
430GB of RAM is excessively high.  Processing `planet.osm` with the `car.lua` profile should be doable with in 10's of GB of RAM, not 100's.

There are some versions of Lua that have been known to trigger memory leaks.  It's possible you have one of those.   See this ticket for some possible avenues to explore:  https://github.com/Project-OSRM/osrm-backend/issues/1484

If you've got an executable called `osrm-prepare`, then you don't have the latest release, that program was renamed to `osrm-contract` for 4.9.0, and the latest tag is 5.2-rc2.

**Comment by kolstad** [comment]
Thanks for being so responsive. I do have osrm-contract; I keep trying to
keep up with documentation -- this is a large system IMHO :) .

I've got lua 5.3 installed.  I am not, however, a cmake guy.  Any hints on
how
I might achieve linking against it?  I see a Cmake module that is
searching for 5.2...

RK

  ====================================================================
            /\      Rob Kolstad                                 Delos
     /\    /  \     rob.kolstad@gmail.com   15235 Roller Coaster Road
    /  \/\/    \    +1 719 481 6542        Colorado Springs, CO 80921
   /    \ \     \                              Phone: +1 719 481 6542
  ====================================================================


On Sat, Jun 11, 2016 at 10:18 PM, Daniel Patterson <notifications@github.com

**Comment by TheMarex** [comment]
@kolstad please provide the following information:

- OSRM release (try `master`)
- output of `cmake ..`
- source of the dataset (are we talking about the geofabrik NA extract?)
- profile used

**Comment by kolstad** [comment]
Superceded by another report.
