### ISSUE TITLE
RAM (VIR/RES) use increased from OSRM 4.9 to 5.1?

### ISSUE THREAD

**Issue by bvbever** [Project-OSRM/osrm-backend#2538]
For Europe I have used  my own lua and processed the europe.pbf 
- in OSRM 4.9.1 => 'htop': 12 GB VIR and 11 GB RES
- in OSRM 5.1.0 => 'htop': 20 GB VIR and 14 GB RES

It it normal that the new osrm use so much more memory while using the exact same lua profile ?

**Comment by danpat** [comment]
@bvbever Yes, this is expected.  We've been concentrating on adding features rather than optimizing memory usage.  In the near future, we're going to put some effort into trimming some things down, there is quite a lot of duplicated data that doesn't need to be that way.

**Comment by bvbever** [comment]
I have 8 different routingtypes for europe. It means 80GB more VIR and 24GB more RES. That's a lot more RAM use....
The purpose of the format change is more routingtypes within one run? What will be the behavior of the ramsize then ?

**Comment by danpat** [comment]
@bvbever The best place to see what's changed is to check the CHANGELOG:

https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md

The specific changes that have increased memory needs are:

  - dynamic calculation of RTree offset data - this reduced the `.fileIndex` size, but added some RAM usage
  - all geometries are now compressed, previously 2-node geometries were not
  - some changes related to guidance may have increased the size of the edge-based-graph a bit (but I'm not 100% clear on this one)

For 5.2, you can expect *more* memory usage again:

  - intersection classification data (angles for all roads at intersections)
  - destination sign data
  - ability to return OSM node ID values for returned route (at least 6% growth here)

@bvbever There are definitely some memory usage inefficiencies.  At the moment, fixing these is not a priority for the core team, but if you're willing to dive into some C++ work, patches are more than welcome.

**Comment by TheMarex** [comment]
Closing as not actionable.
