### ISSUE TITLE
idea: reload map data on SIGHUP signal

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#254]
from the linux upstart cookbook:

This will send a running job the . By convention, daemons receiving a SIGHUP signal reload their configuration or in some way re-initialize themselves (keeping the same PID).

perhaps OSRM could reload the map files when receiving a SIGHUP signal? it would make it easier to reload data, and would especially help speed up tests.

**Comment by TheMarex** [comment]
This is obsolete with `osrm-datastore`.
