### ISSUE TITLE
Too many trace coordinates error

### ISSUE THREAD

**Issue by tanjentman** [Project-OSRM/osrm-backend#2543]
Hey everyone, I am getting the following error when running the Route API over http with 112 lat/lon points.  Is there somewhere to change the limit?  Thanks.

{"code":"TooBig","message":"Too many trace coordinates"}

**Comment by TheMarex** [comment]
You need to set `--max-matching-size=SIZE`

**Comment by tanjentman** [comment]
Thanks TheMarex!  I searched for about an hour yesterday and couldn't find any documentation on options like this.  Do you have a link or could you point me in the right direction?

**Comment by daniel-j-h** [comment]
For `osrm-routed`:

    ./osrm-routed --help
    
    --max-matching-size arg (=100)        Max. locations supported in map matching query
    

and for `libosrm`: [`EngineConfig`](https://github.com/Project-OSRM/osrm-backend/blob/532fda267f48af273d75c934240fc8901c06c03d/include/engine/engine_config.hpp#L43-L69).

**Comment by tanjentman** [comment]
Thanks daniel!
