### ISSUE TITLE
Handling Walking Profile Routing Errors

### ISSUE THREAD

**Issue by oini** [Project-OSRM/osrm-backend#2545]
For the `Walking Profile`, routing via `motorways` and `trunk roads` aren't allowed unless they have designated sidewalks or have the `foot=yes` tag. This results in many routing errors. Take into account [this example in Sri Lanka](https://www.mapbox.com/osrm-frontend-v2/?z=18&center=6.873216%2C81.047782&loc=6.872738%2C81.046965&loc=6.873693%2C81.048599&hl=en&ly=&alt=&df=&srv=&profile=mapbox.walking) where the start and destination is lesser than 500meters away but since the only possible connection between the two points is a `trunk road`, this route fails.

In most South East Asian and African countries, these highways do not have designated sidewalks and there is no law that forbids walking on highways (trunk/motorways). In fact, it is highly common for people to walk along the sides of national and inter-state highways in most of these countries. For example:
- _In India, not only do people walk alongside national and inter-state highways, but also cattle is taken on such roads_

![image](https://cloud.githubusercontent.com/assets/1933377/16037358/bebf7e60-323d-11e6-8318-e2879f3b4ab5.png)
- _Kids walking alongside the Nairobi-Mombasa highway_

![image](https://cloud.githubusercontent.com/assets/1933377/16037329/9dc8692e-323d-11e6-8315-160758ca6f7f.png)

In my mind, these routing errors can be fixed by either of the two methods:
- Mechanically edit all trunk and motorways in these areas to add a `foot=yes` tag
- Handle these requests on the backend in a location-specific manner (by checking for the region in which the start and end points are situated)

Any suggestions would be helpful.

**Comment by daniel-j-h** [comment]
That's an interesting use-case! Unfortunately, at the moment we _do not_ handle tags differently based on their location. Therefore, we do not route over highways in the foot profile.

In theory users could 1/ run different profiles based on geographic areas or 2/ adapt our default profiles and do a check against a geographic area in the Lua profiles and then handle tags differently.

Here are some related tickets: https://github.com/Project-OSRM/osrm-backend/issues/576 https://github.com/Project-OSRM/osrm-backend/issues/333

**Comment by planemad** [comment]
@daniel-j-h what led to the decision of making trunk roads non walkable by default? Seems biased to the developed world which is car centric and not the ground reality in most of the world.

**Comment by MoKob** [comment]
@planemad believe it or not, people actually follow directions like these, even if it may involve severe danger. As OSRM started out as a project in a car-centric environment and the walk profile was added on, it is saver for the western part not to send people on trunk roads.

Introducing an understanding of country-based handling into the profiles is something that has to happen. Its most definitely a shortcoming in the current state, just like many other features that require knowledge on the country and traffic-laws within them.

**Comment by TheMarex** [comment]
Very interesting! In the rural parts of Sweden it is also very common to walk on the side of trunk roads (since they are the only roads available).

Another option would be to base the routing not around shortest duration but also incorporate a (very high) safety penalty like we for example do for the bike profile. Though we still would need to filter out motorway roads for most of Europe/NA since it is actually illegal (and really dangerous) to walk there.

For solving this we need:
- Implement https://github.com/Project-OSRM/osrm-backend/issues/333
- Implement #77 for enabling adding penalties easily
- Adapt lua profiles with a whitelist of countries where walking on motorways is not illegal
- Add safety penalty for walking over motorways
