### ISSUE TITLE
Provide OSM node ids in `nearest` response

### ISSUE THREAD

**Issue by vkurchatkin** [Project-OSRM/osrm-backend#2548]
It would be useful to have node ids of matched segment in `nearest` response. To be specific, that could be used to simplify building traffic data CSV from raw GPS data

**Comment by TheMarex** [comment]
For an existing solution try using the `match` service. Since `5.2` we expose the OSM ids for each `RouteLeg` if you set `annotations=true`.

**Comment by vkurchatkin** [comment]
@TheMarex already doing that, but I thought it would be nice to have an easier way to do this. If you are interested in such a feature, I would like to take a stab

**Comment by danpat** [comment]
@vkurchatkin Go for it :-)

**Comment by SiarheiFedartsou** [comment]
Done in https://github.com/Project-OSRM/osrm-backend/pull/4436/files
