### ISSUE TITLE
Dealing with unfound routes in table using libosrm

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#2552]
I installed v5.1.0 with `sudo cmake --build . --target install`. According to the specs, unfound routes result in json `null` values in the `durations` table, which is convenient to check with plain json.

As I'm using libosrm, I need to check for `json::Null()` in the JSON sum type based on mapbox/variant. There is a `Comparator` struct used in `compare` at https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/json_deep_compare.hpp that would be just what I need but it seems to be unavailable from the library.

Is there a simple way to do this? Currently when unfound routes show up in a table call, I get an error with `get<json::Number>().value`, as one would expect.

**Comment by daniel-j-h** [comment]
With variants (that's how we represent the JSON structure) you have two options of dispatching based on a type:

1/ Write a visitor, overload its `operator()` on the possible types and do the work there.

2/ Check directly similar to `get<>()`: mapbox/variant has a `bool is<T>()` function, Boost's variant has an equivalent as a `get<T*>` function overload for pointers that returns `nullptr` in case of a type mismatch.

Here's a quick variant example showing the visitor use-case (and a trick how to use polymorphic lambdas to do the same): https://gist.github.com/daniel-j-h/04efdc54dae50c1b9bff688ec354e693

**Comment by jcoupey** [comment]
@daniel-j-h thanks for the insight on the two patterns!

I was actually hoping to just use the existing `compare` function mentioned above.
I managed to do that by copying `json_deep_compare.hpp` and `integer_range.hpp` from `osrm-backend/include/util/` to my local include folder: `/usr/local/include/osrm/util/`.

But this is really just a workaround and the resulting code would not compile out-of-the-box on another install...

**Comment by daniel-j-h** [comment]
Unless I'm missing something, it should be as easy as this for each table entry:

```c++
if (entry.is<json::Null>()) {
  handle_null();
}
```

or similar with `json::Number`.

**Comment by jcoupey** [comment]
Quite easy indeed! I'm the one who missed it.

Thanks and sorry for the noise.
