### ISSUE TITLE
Problem with osrm-prepare

### ISSUE THREAD

**Issue by gpietran** [Project-OSRM/osrm-backend#2556]
I am running osrm from my macbook. When trying to extract a map I always get stock at this point:

[info] Processed 332454 edges
[info] Expansion  : 74967 nodes/sec and 66074.1 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract /Users/Giusi/Desktop/berlin-latest.osrm

./_osrm_prepare.sh: line 4: ./osrm-prepare: No such file or directory

Any advise?

Thanks in advance

**Comment by danpat** [comment]
@gpletran It looks like your scripts (what is `_osrm_prepare.sh` ??) are written for an older release of OSRM.  The `osrm-prepare` tool was renamed to `osrm-contract` in version 4.9.1.

Closing, as this doesn't look like a bug on our end.
