### ISSUE TITLE
compile error OSRM > 5.1.0

### ISSUE THREAD

**Issue by bvbever** [Project-OSRM/osrm-backend#2557]
In the past I have succesfully used OSRM 5.1.0 on LINUX Debian GNU/Linux 8 (jessie)
While compiling OSRM > 5.1.0 

`-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- LTO working
-- Using gcc specific binutils for LTO.
-- Setting linker optimizations
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
-- Found Intel TBB
-- TBB interface version: 7003
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR)
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /usr/lib/x86_64-linux-gnu/liblua5.2.so
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so
-- OpenMP support found. Linking just in case for stxxl
-- Enabling json logging
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done`

I have always the same error when I run `cmake --build .`

`Scanning dependencies of target osrm-contract
[ 95%] Building CXX object CMakeFiles/osrm-contract.dir/src/tools/contract.cpp.o
Linking CXX executable osrm-contract
'_ZN3tbb10empty_taskD1Ev' referenced in section '.data.rel.ro._ZTVN3tbb10empty_taskE[_ZTVN3tbb10empty_taskE]' of /tmp/ccBbchYm.ltrans10.ltrans.o: defined in discarded section '.gnu.linkonce.t._ZN3tbb10empty_taskD5Ev' of contractor.cpp.o (symbol from plugin)
'_ZN3tbb10empty_taskD0Ev' referenced in section '.data.rel.ro._ZTVN3tbb10empty_taskE[_ZTVN3tbb10empty_taskE]' of /tmp/ccBbchYm.ltrans10.ltrans.o: defined in discarded section '.gnu.linkonce.t._ZN3tbb10empty_taskD5Ev' of contractor.cpp.o (symbol from plugin)
collect2: error: ld returned 1 exit status
CMakeFiles/osrm-contract.dir/build.make:99: recipe for target 'osrm-contract' failed
make[2]: *** [osrm-contract] Error 1
CMakeFiles/Makefile2:342: recipe for target 'CMakeFiles/osrm-contract.dir/all' failed
make[1]: *** [CMakeFiles/osrm-contract.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by daniel-j-h** [comment]
I just double checked the build system and the only suspicious lines I could find are the following:

https://github.com/Project-OSRM/osrm-backend/blob/306744e5cb705b501d6d78d7b34f5934636d24ff/CMakeLists.txt#L208-L211

Try removing them and see if it helps for now as a workaround (we still have to look into this).

Can you tell me a bit about your system, for example are you using the packages from the package manager or did you compile some packages locally? Are you using the system's default gcc?

If we can't figure it out that way, another option would be to identify the commit where it starts to break. There is a Git bisect example script in [scripts/bisect_cucumber.sh](https://github.com/Project-OSRM/osrm-backend/blob/306744e5cb705b501d6d78d7b34f5934636d24ff/scripts/bisect_cucumber.sh) for doing a bisection based on the test suite. You can remove the `cucumber` line and it should Just Work (tm).

**Comment by gredin** [comment]
Same here on Debian Jessie 64.

**Comment by gredin** [comment]
@daniel-j-h The workaround doesn't work.

**Comment by daniel-j-h** [comment]
Thanks for confirming; I just reproduced it locally in a Docker container. Will look into it.

**Comment by daniel-j-h** [comment]
Running the automatic bisect script over night found the first bad commit to be: https://github.com/Project-OSRM/osrm-backend/commit/ee7bb8731a3ee0b09e98882e0857a6c136db37d3 which introduces TBB's `parallel_invoke` into the contractor for the first time.

**Comment by daniel-j-h** [comment]
Here's a fix for this issue: https://github.com/Project-OSRM/osrm-backend/issues/2573. With it I was able to compile master in a Debian Jessie container.

```bash
apt-get install -y git g++ cmake libboost-all-dev libstxxl-dev libxml2-dev libbz2-dev libzip-dev liblua5.1-0-dev libluabind-dev pkg-config libtbb-dev
git clone --depth 1 --branch fix/2557 https://github.com/Project-OSRM/osrm-backend.git
cd osrm-backend
mkdir build && cd build
cmake .. && make -j $(nproc)
```

**Comment by gredin** [comment]
@daniel-j-h I was able to compile with these instructions. Thanks!
