### ISSUE TITLE
support access=delivery

### ISSUE THREAD

**Issue by cobra** [Project-OSRM/osrm-backend#256]
access=delivery isn't supported yet. IMHO this should be handled like access=destination.

**Comment by Fujnky** [comment]
This doesn't seem like a good way to get on the Autobahn: http://map.project-osrm.org/?z=16&center=51.467503%2C7.596874&loc=51.463954%2C7.592196&loc=51.471306%2C7.600458&hl=en&ly=&alt=&df=&srv= The way is tagged access=delivery as well.
![](https://cloud.githubusercontent.com/assets/293544/10292149/ea0e61fa-6bad-11e5-8eaa-22cd48124472.png)
