### ISSUE TITLE
Need an advice

### ISSUE THREAD

**Issue by boooch** [Project-OSRM/osrm-backend#2560]
Hi, can you give me an advice, I need to set max speed in some places lower than usual when I calculate the route. For example , in the evening and in the morning max speed in the city will be for 20 km/h lower than usual, so the route through the city will take more time  than usual and route around the city will be faster .  May be some undocumented parameters in the backend rest API ?

**Comment by TheMarex** [comment]
Daniel already outlined the ways we can handle time dependent edge weights. Closing here now as not actionable.
