### ISSUE TITLE
osrm-datastore and shared memory removal

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#2561]
I'm running v5.1.0 on ubuntu 16.04 and I seem to be unable to free the shared memory using the `-s` option from `osrm-datastore`.

What I do:
```bash
$osrm-datastore france.osrm
[info] load names from: "france.osrm.names"
[info] name offsets size: 35283
[info] allocating shared memory of 2091370656 bytes
Copying 11 chars into name data ptr
[info] all data loaded
```
I'm then able to run any code using shared memory via libosrm. Then if I try to remove all regions in shared memory, I get the very same output:

```bash
osrm-datastore -s france.osrm
[info] load names from: "france.osrm.names"
[info] name offsets size: 35283
[info] allocating shared memory of 2091370656 bytes
Copying 11 chars into name data ptr
[info] all data loaded
```
The memory usage doesn't decrease and I'm still able to run successfully the previous command using shared memory.

**Comment by daniel-j-h** [comment]
Although `osrm-datastore` seem to provide a `-s` flag (see [store.cpp](https://github.com/Project-OSRM/osrm-backend/blob/b98431e8e63846672dd0bf1ea6bde6f1d63bdaf7/src/tools/store.cpp#L20)) I can't see it getting used anywhere in the code. I _think_ the reason for this is of historical nature (/cc @TheMarex ?), and we now have the `osrm-springclean` tool for removing shared memory segments.

**Comment by jcoupey** [comment]
Ok. It doesn't look like `osrm-springclean` is available with a release build on v5.1.0. Is there a specific way to build it?

**Comment by daniel-j-h** [comment]
Ah yes, it's [behind `-DBUILD_TOOLS=1`](https://github.com/Project-OSRM/osrm-backend/blob/510ca0d22c248833ea56af68e918e8e8f67bf1f9/CMakeLists.txt#L384-L399).

**Comment by jcoupey** [comment]
Thanks!

Closing as everything is fine when using `osrm-springclean`.
