### ISSUE TITLE
Distance at the point sequence (table service)

### ISSUE THREAD

**Issue by alik-datsko** [Project-OSRM/osrm-backend#2567]
Tell me, how can I get the distance between points with fixed route (0=>1; 1=>2; 2=>3...)
Thank you.

**Comment by daniel-j-h** [comment]
At the moment, the Table service does not return distances, see the open ticket at: https://github.com/Project-OSRM/osrm-backend/issues/544. Looking at your example:

> points with fixed route (0=>1; 1=>2; 2=>3...)

You can add multiple coordinates to a single Route request, though. Take a look at the documentation:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#http-api

the format is
> {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline})

There is an example with three coordinates here:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#examples

The route query then returns you the following response object:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#result-objects

Its `legs` attribute is an array of routes between waypoints. Each of those has both an attribute for `distance` as well as `duration`.

**Comment by TheMarex** [comment]
Closing as not actionable.
