### ISSUE TITLE
Starting osrm-routed on a big dataset takes several seconds

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2574]
Currently it seems that starting osrm-routed on a planet wide dataset takes several seconds. This should not be the case when using shared memory as must not be any IO/setup. This leads me to believe some parts of the ShareDatafacade are implemented wrong and actually load data from disk or copy data.

**Comment by danpat** [comment]
@TheMarex is this still the case?  We've done some major refactors on a lot of the code related to this.

**Comment by TheMarex** [comment]
No this was fixed after removing the mlock call in osrm-routed.
