### ISSUE TITLE
Refactor compressed geometry

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2575]
Currently we save `node id`, `weight` and soon `duration` as interleaved structs in the `.geometry` file. We need to decompose this into three separate vectors, one for each member.

This will enable:
- [ ] DataFaces can just return ranges to the vector: zero-copy for `GetUncompressedGeometry` + `GetUncompressedWeights` + `GetUncompressedDurations`
- [ ] Updating the weight values in osrm-contract will be a lot faster: We only need to write one (or two) vector containing the weights (or durations) the structure is never changed.
- [ ] No dependency on CompressedContainer::CompressedEdge in `engine/`

**Comment by danpat** [comment]
This should get included in https://github.com/Project-OSRM/osrm-backend/issues/2592

**Comment by TheMarex** [comment]
Actually this is a requirement for https://github.com/Project-OSRM/osrm-backend/pull/2399 since it would enable us to conditionally only load the duration to memory if applicable.

**Comment by jakepruitt** [comment]
This was closed with #3093
