### ISSUE TITLE
Hard-abort on critical exceptions

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2579]
At the moment we catch-all exceptions at the top e.g. coming from `boost::numerical_cast`.

This gives us no information as to where the issue occured, all we get is a
> [warn] overflow happened

(or similar)

Here's what we should do:

- `-DENABLE_ASSERTIONS` already enables custom Boost assertion handler
- we already overwrite provide a custom assertion handler [here](https://github.com/Project-OSRM/osrm-backend/blob/6dedd9cb724633756602c23523ecc54d3e46c892/src/util/assert.cpp#L13)
- with catch-alls littered throughout the code we should either throw a different exception type and then not catch it (which then calls terminate, which calls abort) or hard abort ourselves directly

-----------------------------------------------------------------------------------------

![termination](https://raw.githubusercontent.com/adishavit/Terminators/master/termination_graph.png) (from https://github.com/adishavit/Terminators)

**Comment by TheMarex** [comment]
This landed with #2579.

**Comment by daniel-j-h** [comment]
For the record, it's only enabled with `-DENABLE_ASSERTIONS`. Without this (e.g. in release builds, node-osrm binaries, ..) we still simply swallow such errors..
