### ISSUE TITLE
How to calculate the index for the instruction? 

### ISSUE THREAD

**Issue by dmitrykhramov** [Project-OSRM/osrm-backend#2589]
Hello!
I'm working with leaflet-touting-machine and OSRM as a default route service. I'm trying to implement multimode routing. When the request is sent to the OSRM I get the response object with all information for building the route. I'm intrested in how is the index for the instruction is calculated (route_instructions[1].3). I can't find it in the code, can you please write the formula which is used to calculate this index or say where in the code I can find this algorithm?

**Comment by danpat** [comment]
@dmitrykhramov You're using the OSRM 4.x API.  You should use the 5.x API, which is the one currently documented at https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

We're hosting both APIs at `router.project-osrm.org` for now, but the v4 API will be shut down in the near future (within a couple of months).  Of course, if you're running your own server, you can do whatever you like.

The code for the `route_instructions` element in the v4 API can be found if you look back at old releases.  It's also documented here:  https://github.com/Project-OSRM/osrm-backend/wiki/Server-API---v4,-old

Nothing actionable for us here, closing.
