### ISSUE TITLE
maxspeed:practical

### ISSUE THREAD

**Issue by d1g** [Project-OSRM/osrm-backend#2591]
[Some of us](http://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Practical_maxspeed#Comments_after_voting_period) would appreciate hints about practical/physical max speed.

* Not always dangerous/curved roads marked with max speed signs
* over-parked roads (illegally or not)
* we cannot truly deduce value of "surface=unpaved + note=horrible road" unlike number (25,30)

It was created in [Russian community first](http://wiki.openstreetmap.org/wiki/RU:Key:maxspeed:practical) with 442-message long discussion about it and when/why to use it

In April'16 it was extended with [methology how to enter values](http://wiki.openstreetmap.org/w/index.php?title=RU%3AKey%3Amaxspeed%3Apractical&type=revision&diff=1288157&oldid=1286202)

Using "debug" layer of OSRM I was able to find roads with 40-56 km/h "defaults" where in the real world you won't able to travel faster than 20-30. I know that there many places in the world where you can never drive faster than (number known to locals). Using this value wisely would improve routing results without drawbacks.

This tag was supported for years now, thanks to @liosha and his [osm2mp](https://github.com/liosha/osm2mp/search?utf8=%E2%9C%93&q=maxspeed%3Apractical) [1](http://forum.openstreetmap.org/viewtopic.php?id=694) [2](http://forum.openstreetmap.org/viewtopic.php?id=2367)

**Comment by d1g** [comment]
As was pointed by Marek kleciak, not all of deprecation arguments makes sense: http://wiki.openstreetmap.org/wiki/Proposed_features/Practical_maxspeed#Voting

Some of them are pure "bad faith assumptions": "Absolutely pointless. Every mapper would tag this different".

We made precise description why and how to evaluate and tag maxspeed:practical in Russian, please use it,t translate it and tag it :)

**Comment by d1g** [comment]
My suggestion is to evaluate weather condition and other coefficients _after_ base cost of _maxspeed:practical_. 

It was never claimed that maxspeed:practical is about wet/weather conditions.

**Comment by TheMarex** [comment]
We are not going to support `maxspeed:practical` in the default profile. It is a **subjectve** value. For getting precise ETAs there is no way around integrating real world _ measured_ average speeds for every road (or rather learn real speed models depending on the time for each road). This can be achieved by GPS probe data. Projects like https://github.com/opentraffic try to make data like this accessible to the general public and sure could need some additional support.

Using a single value to give practical speed is rather futile and I would not waste a huge effort in adding support for this.
