### ISSUE TITLE
Luabind can't find trimLaneString, throws exception in osrm-extract

### ISSUE THREAD

**Issue by nigun** [Project-OSRM/osrm-backend#2594]
ubuntu 14.04 LTS
map->http://data.gis-lab.info/osm_dump/dump/latest/RU-MOS.osm.pbf
running: ln -s ../profiles/car.lua profile.lua
running: ./osrm-extract -p profile.lua ./RU-MOS.osm.pbf 
i have error:
[info] Using script profile.lua
[info] Input file: RU-MOS.osm.pbf
[info] Profile: profile.lua
[info] Threads: 4
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] 1 disks are allocated, total space: 1000 MiB
[info] Parsing in progress..
[info] input file generated by 0.44.1
[info] timestamp: n/a
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
terminate called after throwing an instance of 'osrm::util::exception'
  what():  ERROR occurred in profile script:
No matching overload found, candidates:
std::string trimLaneString(std::string,int,int)
Aborted (core dumped)

**Comment by daniel-j-h** [comment]
Can you be more specific about
- osrm-backend version
- compiler and stdlib version
- operating system
- lua and luabind version
- ldd libluabind.so to see which lua version luabind was linked against
- the cmake output

**Comment by MoKob** [comment]
This looks

**Comment by nigun** [comment]
osrm-backend  - curent version (clone yesterday)
stdlib version -how to look?
lua and luabind version 5.1.5 (run aptget install lua5.1 liblua5.1-0-dev libluabind-dev )
cmake output:
-- Building on a 64 bit system
-- Configuring OSRM in debug mode
-- Setting linker optimizations
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
-- Found Intel TBB
-- TBB interface version: 7000
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR)
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /usr/lib/x86_64-linux-gnu/liblua5.2.so
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so
-- OpenMP support found. Linking just in case for stxxl
-- Enabling assertions
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /osrm-backend/build

**Comment by nigun** [comment]
i`m edit function getTurnLanes(way)  in car.lua:
...
--add check 
if (fw_psv==nil) then print ('f') end
if (bw_psv==nil) then print ('b') end
..
start exctract
i have outprint 'b' once
add code in  car.lua:
if (turn_lanes ~=nil and fw_psv~=nil and bw_psc~=nik) then
(
turn_lanes =trimLaneString(turn_lanes,bw_psv,fw_psv)
)
end

start excreact -->

**Comment by MoKob** [comment]
It seems that, for some reason, your system generates a `nil` value for empty strings. So the issue seems `luabind` dependent. You can try using https://github.com/Project-OSRM/osrm-backend/pull/2598.
This should fix your issues.

**Comment by MoKob** [comment]
Fixed by https://github.com/Project-OSRM/osrm-backend/pull/2598. Waiting for merge.
