### ISSUE TITLE
Implement new features for the "nearest" function

### ISSUE THREAD

**Issue by temporaryaccount** [Project-OSRM/osrm-backend#2600]
It would be nice to have some more options when requesting the nearest points. For example, to return only the points which have a non-empty *name* field, or to get the English version of the names instead of the local ones, or to get only some specific types of nearest objects (i.e. only streets, or only cities as I may want to know which are the nearest cities).

By the way, is there a way of getting through the API *where* a point is? I.e. to get the name of the city or the region (if outside of cities) or the country (if there are no regions) or the name of the sea/ocean if in international waters of any provided X,Y point?

Thanks.

**Comment by danpat** [comment]
@temporaryaccount What you're describing is known as a "reverse geocoder".  OSRM is primarily a routing engine, finding a path from A to B.  We only provide minimal "nearest" functions to support routing.  OSRM doesn't store most of the data you're describing, it's not necessary for routing.

You might want to look at http://wiki.openstreetmap.org/wiki/Nominatim
