### ISSUE TITLE
matching result not correct

### ISSUE THREAD

**Issue by bvbever** [Project-OSRM/osrm-backend#2602]
While testing the newest version op OSRM comparing with my local OSRM 5.1.0, I have something not correct:
When I use the polyline in the following match (you can visalise the polyline [here](https://developers.google.com/maps/documentation/utilities/polylineutility) by copy past it in the 'Encoded Polyline') the result is not what to be excepted. The endpoint has to be in 
the Seyntexlaan and not in Bosakkerstraat.

https://router.project-osrm.org/match/v1/driving/polyline(c|cvH{loScA|@wAhAmAjA{BlDsBfFi@lBi@tBs@fESlACl@A`@Bf@^~EDl@b@jEDd@@Z?\CLIXWf@_AtAu@pAa@~@]|@yAzEwArECZ@VFRj@|AdAzCfAzCzAtERr@t@vDo@d@k@r@m@z@o@v@uDvF{AxB_D~EGHGPCPAXKHXhA^zBPbA?bFCdIA|BaDQ)?overview=full&steps=true&timestamps=0;15;33;50;81;116;131;147;172;182;187;191;196;223;228;253;258;261;265;267;271;277;293;307;317;326;357;387;390;393;396;410;432;455;485;492;516;526;536;547;558;603;625;665;667;670;672;675;678;688;704;713;740;778;793;823

**Comment by bvbever** [comment]
update: When I add the parameter `geometries=geojson`, the result is fine.
Is there something wrong with the polyline encoding in OSRM ?

**Comment by TheMarex** [comment]
I just decode the polyline with https://github.com/mapbox/polyline and the result is exactly what you would expect:

http://bl.ocks.org/d/ee0a3f67fc5903f2efd84ae9c3269f05

Could this be an incomparability with Google?

**Comment by bvbever** [comment]
The jsonviewer-plugin in Notepad++ has changed the polyline encoding.
So there is nothing wrong: The polyline can still be decoded with Google.
So @TheMarex, thanks for checking.
