### ISSUE TITLE
Drop Windows support

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#2606]
As discussed in https://lists.openstreetmap.org/pipermail/osrm-talk/2016-May/001214.html, we don't have a use for Windows builds at the moment  (except somebody steps up still).

It's time to pull the plug:

- Clean up code from Windows build code
- Shut down Appveyor builds

**Comment by kostadin24** [comment]
Windows users can build project if they know versions of dependencies.
Not so easy, but there is no better way for now.

**Comment by TheMarex** [comment]
We are keeping the current infrastructure and are waiting for someone to fix it.
