### ISSUE TITLE
Deduplicate Enter / Leave Roundabout Logic

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2608]
Ticketing so we don't forget about it. Compare:

- [include/extractor/guidance/toolkit.hpp](https://github.com/Project-OSRM/osrm-backend/blob/49221995e8b58c634c9abcd0867e63cf91493458/include/extractor/guidance/toolkit.hpp#L534-L555)
- [include/engine/guidance/toolkit.hpp](https://github.com/Project-OSRM/osrm-backend/blob/49221995e8b58c634c9abcd0867e63cf91493458/include/engine/guidance/toolkit.hpp#L24-L45)

**Comment by MoKob** [comment]
Done and done.
