### ISSUE TITLE
Adding restrictions at traffic islands for correct routing

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#2611]
There are numerous instances of restrictions on OSM at junctions with free turns and traffic islands like this for correct routing.

![screenshot 2016-06-30 18 34 27](https://cloud.githubusercontent.com/assets/126868/16489053/4aff7d5c-3ef1-11e6-9564-049c3516221e.png)
_A [no right restriction](https://www.openstreetmap.org/relation/6257391) added at a junction with a separate free right turn_

<img width="579" alt="java openstreetmap editor 2016-06-30 15-42-40" src="https://cloud.githubusercontent.com/assets/126868/16489172/ec69825a-3ef1-11e6-8e3f-acb9f2338662.png">
_Satellite image showing left turn lanes on the same road to the junction_

The issue here is:
- Many of these junctions don't have any physical `No Right` traffic sign, that can be used to verify the restriction, and goes against the recommended practice of mapping what is visible. What is a consistent approach to mapping such restrictions?
- There are possibly millions of such junctions with free turns and traffic islands, do they all warrant a turn restriction similar to this?
- In this particular case, the from way has only left turn lanes, clearly indicating that a straight and right turn  is not possible. Could this possibly used to influence routing instead of using turn restrictions?

cc @andygol @maning

**Comment by danpat** [comment]
The problem here isn't a missing turn restriction, it's the differences in road speeds leading to a bad calculation inside OSRM.

Here are the timings for each segment that OSRM has internally:

![screen shot 2016-06-30 at 7 38 16 am](https://cloud.githubusercontent.com/assets/1892250/16492797/e3983d1a-3e97-11e6-940d-4dfc495d5ceb.png)

From A->B, there are two choices: via the slip-road, it'll take 6.1s.  Via the main road, it'll take 6.0s.  There *should* be a turn penalty value where I've got `????`, but maybe we've got a bug in OSRM here and it's not working.

It's probably just a matter of very tiny differences in time (e.g. 0.1s in this case).  OSRM is pretty brutal about that -> the fastest is the fastest.

Thanks for highlighting the bad routing here.  Do *not* add turn restrictions to fix this if they're not valid on the ground - we need to adjust the turn penalties and road speeds in OSRM for this to work properly.

**Comment by TheMarex** [comment]
> Do not add turn restrictions to fix this if they're not valid on the ground - we need to adjust the turn penalties and road speeds in OSRM for this to work properly.

Well it is not quite that simple. Looking at the lane indications in the above picture they explicitly state that are are supposed to turn _left_. That means they imply a only-left restriction. I think it is completely valid to tag them in this case. Road markings are just one way of indicating turn restrictions.

**Comment by Andygol** [comment]
I just put here a scheme of this junction with indication of allowed movement directions 
![image](https://cloud.githubusercontent.com/assets/369696/16518921/58b910c8-3f8e-11e6-92cd-2b1be195e5e5.png)

**Comment by MoKob** [comment]
> I think it is completely valid to tag them in this case. Road markings are just one way of indicating turn restrictions.

Fully agree on that. I even use lane markings partly already to disable some turns during the graph generation.

**Comment by planemad** [comment]
Here's another example

<img width="499" alt="screenshot 2016-07-05 15 01 45" src="https://cloud.githubusercontent.com/assets/126868/16580318/7136be12-42c1-11e6-915d-5d90efdb3973.png">
https://www.openstreetmap.org/relation/5771246

<img width="516" alt="screenshot 2016-07-05 15 06 07" src="https://cloud.githubusercontent.com/assets/126868/16580424/0808ca10-42c2-11e6-91ca-d87f66174498.png">

@MoKob are the road intersections angles used in anyway to penalize such a turn or is a restriction necessary?

> Fully agree on that. I even use lane markings partly already to disable some turns during the graph generation.

Is this something that could be used to propose some revised mapping conventions, like `avoid adding turn restrictions unnecessary if the turn lane tags can indicate what turns are restricted at the junction'?

**Comment by MoKob** [comment]
@planemad Turn angles can be penalised in the profiles via a turn_function. The penalisation should not influence whether a turn is allowed or not. If the turn is not allowed, it should be in the data. It could always be that a different route would require a significant detour, resulting in the turn still being used.

The same can be said for:
>>Fully agree on that. I even use lane markings partly already to disable some turns during the graph generation.

>Is this something that could be used to propose some revised mapping conventions, like `avoid adding turn restrictions unnecessary if the turn lane tags can indicate what turns are restricted at the junction'?

While I try and get the maximum out of the data, heuristics should not be a reason to exclude valid mappings. If a turn is not allowed, the data should reflect so.
What I do in processing is just a heuristic to find if there might be some missing data that I can handle. Missing data remains missing data, though.

**Comment by danpat** [comment]
The conclusion here is that restrictions based on lane markings seem like a reasonable thing to do, and OSRM already supports that.  Nothing actionable on the OSRM side here, closing.
