### ISSUE TITLE
Traffic. How to deny the route the road segment?

### ISSUE THREAD

**Issue by sayr777** [Project-OSRM/osrm-backend#2615]
Hi All!

I am use the variable  "edge_speed_in_km_h" in file "update.csv"

If  "edge_speed_in_km_h" =1 (>0) then  All OK. A route is generated correctly.
If "edge_speed_in_km_h" =0 then route in this segment a priority. 

Attached screenshots:
![route_if_edge_speed_0_km_h](https://cloud.githubusercontent.com/assets/6581264/16528025/ae062a32-3fc2-11e6-8f47-04711c67acb2.jpg)
![route_if_edge_speed_1_km_h](https://cloud.githubusercontent.com/assets/6581264/16528022/adfb61ec-3fc2-11e6-800a-6dcd79d6d378.jpg)
![edge_speed_0_km_h](https://cloud.githubusercontent.com/assets/6581264/16528023/adfe862e-3fc2-11e6-9521-35d467da8180.jpg)
![edge_speed_1_km_h](https://cloud.githubusercontent.com/assets/6581264/16528024/ae008492-3fc2-11e6-8b17-9785a932cede.jpg)

**Comment by TheMarex** [comment]
Good catch. I think this might be a divide by zero.

/cc @danpat

**Comment by danpat** [comment]
Very likely, I'll look into this this evening.  If we set a road to 0, we should effectively remove it from routing.

**Comment by TheMarex** [comment]
Fixed in #2688 will be in the next release. Thanks for reporting this. :+1:
