### ISSUE TITLE
how much set GB for syscall in stxxl file ?

### ISSUE THREAD

**Issue by H91011** [Project-OSRM/osrm-backend#2616]
Hi I build Turkey map and I create stxxl file for building, I set 70 GB  for syscall, is this enough for build or runnig ? How can I see usage stxxl ? Is there a log file for this ? how it works osrm ? It caching all map data to RAM or stxxl path ?

**Comment by danpat** [comment]
We generally do not know.  It depends on your basemap, and which profile you're using.  We have no strict formula.

Basically, the answer is:  try it and see.

For processing `planet.osm.pbf`, and the `car.lua` profile, we use a 200GB `.stxxl` file on a machine with 120GB of RAM and fast SSD disks.   It takes about 6 hours to run `osrm-extract` and `osrm-contract` with that configuration.

Feel free to post back to this ticket with your results, but there's nothing actionable for us here, it's currently unknowable ahead of time.
