### ISSUE TITLE
Two osrm instances generated with same profile produce different /route API response when given same coordinates input

### ISSUE THREAD

**Issue by fubupc** [Project-OSRM/osrm-backend#2617]
As the title said: two osrm instances generated with same profile and same osm.pbf file will produce different `/route` API response (`duration`, `distance`) when given same coordinates input.

I did some experiments as following:

1. Make two osrm instances with same osm.pbf and speed profile. Run them in different port.
2. Test `/route` API of both instances with exactly the same coordinates set.
3. Compare `duration`, `distance`  of both test set, you will find that most test produce same result, but a few of them have a random difference.

Some other observations:
1. An OSRM instance always returns same result for same input. (only `/route` API tested.)
2. Most of input will give same result among different OSRM instance. But different pairwise instances disagree on different subset of input.

PS: And I wrote some scripts (with sample data) to help reproducing the problem. please check it at: https://github.com/fubupc/osrm-test

**Comment by danpat** [comment]
@fubupc This is possible where there are possible routes of the same **duration**.

During pre-processing (`osrm-extract`/`osrm-contract`) there is multi-threaded work occurring where it becomes possible that data does not get processed exactly the same each time you do it.  While it should be correct (we hope!) for actually finding the fastest path, if there are two possible paths of equal duration, there is no guarantee as to which one will be selected.

Note that this happens during **pre-processing**, not during an actual routing request.  Two `osrm-routed` instances using the same `.osrm` files should produce the same results.

Can you please check that your differing results have equal `duration` values?  If not, we might have a bug.  If `durations` are equal, then the behaviour is expected.

**Comment by fubupc** [comment]
@danpat some tests did show different `duration` as well :(

Below are several testings I made:

```
    id     |           start            |            end             |    time compare     |   distance compapre   
----------------------------------------------------------------------------------------------------------
1655       | 106.99289800,-6.24160800   | 106.99268600,-6.24614600   |  +0.0   77.6 77.6   |     -0.3    815.9 816.2   
2125       | 106.87364700,-6.19923800   | 106.86550400,-6.20224800   |  +1.4    379 377.6  |     +0.0   4734.4 4734.4  
2413       | 106.87440500,-6.21346800   | 106.87220000,-6.21454800   |  +1.4   84.8 83.4   |     +0.0   1120.1 1120.1  
2516       | 106.72717900,-6.19996700   | 106.71997400,-6.19612800   |  +0.0  181.2 181.2  |     +2.0   1781.1 1779.1  
2801       | 106.72780600,-6.20115700   | 106.72433500,-6.19491600   |  +0.0  114.2 114.2  |     +2.0   1013.4 1011.4  
2852       | 106.86048700,-6.14145800   | 106.87307400,-6.14614800   |  +0.0  182.7 182.7  |     -0.9   2036.1 2037    
3145       | 106.72751600,-6.19961300   | 106.71921500,-6.19404500   |  +0.0  197.4 197.4  |     +2.1   2081.4 2079.3 
```

```
    id     |           start            |            end             |    time compare     |   distance compapre   
----------------------------------------------------------------------------------------------------------
680        | 106.89358300,-6.15800100   | 106.88813600,-6.15968800   |  +0.0    106 106    |     +0.5    879.9 879.4   
709        | 106.73481500,-6.14846400   | 106.72792600,-6.15224300   |  +0.5    136 135.5  |     +0.0   1747.5 1747.5  
733        | 106.86894200,-6.23868600   | 106.87219900,-6.24277600   |  -0.9  306.4 307.3  |     +0.0   5014.1 5014.1  
2404       | 106.86884700,-6.24302500   | 106.86645700,-6.24868500   |  -0.9    351 351.9  |     +0.0   5966.9 5966.9  
2516       | 106.72717900,-6.19996700   | 106.71997400,-6.19612800   |  +0.0  181.2 181.2  |     +2.0   1781.1 1779.1  
2778       | 106.91134900,-6.37549500   | 106.91329000,-6.37320100   |  +0.0    253 253    |     -0.7   2607.6 2608.3  
2801       | 106.72780600,-6.20115700   | 106.72433500,-6.19491600   |  +0.0  114.2 114.2  |     +2.0   1013.4 1011.4  
2821       | 106.76489300,-6.31594000   | 106.76944700,-6.32313700   |  +0.0  141.2 141.2  |     +9.7   1278.8 1269.1  
2878       | 106.86817300,-6.22460300   | 106.86818300,-6.22099800   |  +0.0  175.6 175.6  |     +9.1   1863.5 1854.4  
3145       | 106.72751600,-6.19961300   | 106.71921500,-6.19404500   |  +0.0  197.4 197.4  |     +2.1   2081.4 2079.3 
```
PS: same id have same input start and end coordinates.

We can see that there are some tests does have different duration although very few.  ( about 1 case out of 1000 test ).

**Comment by oxidase** [comment]
@fubupc thanks for the nice test setup. I have checked some routes and it is as said by @danpat is an effect of non-determinism during pre-processing. 
Here https://gist.github.com/oxidase/a90d746bfea46de6575a7a88aa6d2a7b is an example with different durations and distances for
```
354        | 106.70390100,-6.12293700   | 106.70558300,-6.13411000   |  -1.0  134.7 135.7  |    +44.7   1753.7 1709    
```

Here https://gist.github.com/oxidase/a90d746bfea46de6575a7a88aa6d2a7b  is an example with different distances but equal durations for 
```
3276       | 106.85259500,-6.24221000   | 106.85661100,-6.23863000   |  +0.0   81.8 81.8   |    +61.3    877.2 815.9
```

@danpat could it be a bug?

**Comment by danpat** [comment]
All the routing is done based on durations - distances are only calculated after the route is found.  Differing distances given the pre-processing non-determinism is reasonable.

But, those differing times are not.  There's definitely a bug in here somewhere.  I suspect we're incorrectly adding the first turn penalty after the initial (or last) PhantomNode (snapped coordinate).

I don't think this is drastically breaking routing - overall, routes are probably correct, but some durations are probably wrong by a second or two, and many routes will be unaffected by this, because there are no equivalent.

I'm flagging this as a bug, someone can dig into it when they have time.

**Comment by danpat** [comment]
@fubupc Can you test and see if @oxidase 's pull request #2624 fixes your problem?  It's available in the latest `master` code.

**Comment by fubupc** [comment]
@danpat Sorry for late response. I just tested several times and it should be OK now.
PS: even distance is exactly the same now. (maybe because my test set is not large enough)

Great work @oxidase ! Thank you all guys!

**Comment by danpat** [comment]
Great, thank you!
