### ISSUE TITLE
Handle subsequent lane changes going straight

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2625]
At the moment we handle subsequent lane changes only if they happen in a [left / right turn](https://github.com/Project-OSRM/osrm-backend/blob/0e4061f85816b5499896022eb151a1402ae3aad0/src/engine/guidance/lane_processing.cpp#L83).
https://github.com/Project-OSRM/osrm-backend/pull/2612 adds roundabouts to the mix.

We should handle going straight as well.

**Comment by MoKob** [comment]
Has been moved to advanced lanes, closing here.
