### ISSUE TITLE
Windows build break with the introduction of __attribute((packed))

### ISSUE THREAD

**Issue by ssuluh** [Project-OSRM/osrm-backend#2627]

**Comment by daniel-j-h** [comment]
Great you found your way to the issue tracker and thanks for taking over Windows issues (as per mail).

Here's where we left off a couple of weeks ago:
- https://github.com/Project-OSRM/osrm-backend/issues/2226
- https://github.com/Project-OSRM/osrm-backend/pull/2352

/cc @BergWerkGIS

**Comment by ssuluh** [comment]
PR #2629  is merged by @TheMarex .  Closing the issue.

**Comment by MoKob** [comment]
Closing as of: https://ci.appveyor.com/project/DennisOSRM/osrm-backend/build/1.0.4049
