### ISSUE TITLE
lots of "[warn] Found invalid node reference" in release build

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2630]
When extracting, i get a lot of ""[warn] Found invalid node reference" filling up the log file. Could it maybe be moved to debug level, so it's not shown in release builds?

**Comment by emiltin** [comment]
I get thousands of the same warning, and most of them referr to the same node id, in this case 4294967295.

**Comment by karme** [comment]
Emil Tin <notifications@github.com> writes:

> I get thousands of the same warning, and most of them referr to the
> same node id, in this case 4294967295.

very suspicious

4294967295
2^32 =
4294967296

**Comment by daniel-j-h** [comment]
The node id you're seeing is `numeric_limits<unsigned>::max();` ("invalid node").

Are you running on an OSM extract? Did you cut it yourself?

**Comment by eostermann** [comment]
I am getting lot of these warnings as well when running osrm-extract on osm.pbf files (Europe extracts) downloaded from geofabrik.de and latest osrm-backend (version 5.3.0)

**Comment by emiltin** [comment]
i was using an pbf cut with osmosis

**Comment by TheMarex** [comment]
What should never be the case is that you use ways with node ids that are missing. That will break your routing graph.

For edges we have this on warning level for a reason: This caused severe problems when OSRM was fed some corrupted OSM extracts.

For restrictions I can see how this would be low priority enough.

**Comment by emiltin** [comment]
could ways with missing nodes be excluded instead of breaking the graph?
