### ISSUE TITLE
Update Cucumber to remove \| vs & hack

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2632]
Currently we have to workaround cucumber not allowing us to specify lanes as in

    left\|through\|right\|right

instead we workaround it with

    left\|through&right&right

and transform this later for the OSM files.

The issue over at Cucumber is here: https://github.com/cucumber/cucumber-js/issues/417 (resolved now).

Update Cucumber to >= 1.2.1 (`package.json`), remove workaround.

**Comment by TheMarex** [comment]
:+1: Should be a simple `npm install cucumber@1.2.1 --save`

**Comment by MoKob** [comment]
This is implemented and only waiting for merge over in #2635
