### ISSUE TITLE
No left turn using a via way is ignored 

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#2634]
Found this no turn relation with a way with a way as 'via':
<img width="353" alt="openstreetmap___relation__6187972" src="https://cloud.githubusercontent.com/assets/126868/16652081/add5db28-4465-11e6-87c0-f4df039b5567.png">
https://www.openstreetmap.org/relation/6187972#map=19/37.77332/-122.42359

OSRM seems to ignore the restriction and route through it anyway.
<img width="224" alt="screenshot 2016-07-07 17 14 15" src="https://cloud.githubusercontent.com/assets/126868/16652165/4c5d8692-4466-11e6-85c8-aa4541ca2ec2.png">
http://map.project-osrm.org/?z=18&center=37.773111%2C-122.423857&loc=37.773263%2C-122.423996&loc=37.773280%2C-122.423792&hl=en&alt=0

According to the [OSM Wiki](http://wiki.openstreetmap.org/wiki/Relation:restriction#Members) this looks like a valid restriction.

cc @andygol

**Comment by daniel-j-h** [comment]
Duplicate: https://github.com/Project-OSRM/osrm-backend/issues/483:
> Support way as via role in turn restriction

**Comment by MoKob** [comment]
Closing as duplicate.
