### ISSUE TITLE
Handle lanes with different access designation

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2638]
http://wiki.openstreetmap.org/wiki/Lanes#Crossing_with_a_designated_lane_for_bicycles

Not sure how well this is tagged OSM-wide, but we should make sure to not accidentally put drivers in bike lanes if we're using the `car` profile.

```
lanes=3
turn:lanes=left|through|through|right
vehicle:lanes=yes|yes|no|yes
bicycle:lanes=yes|no|designated|yes
```

Even though `lanes=3`, there are 4 mentioned in `turn:lanes`.  For the `car` profile, we might need to compact `turn:lanes` based on `vehicle:lanes`.

/cc @1ec5 @MoKob @daniel-j-h

**Comment by MoKob** [comment]
Not a big problem (500ish tags right now), but a rather simple fix. Will implement it just to be on the safe side.

**Comment by MoKob** [comment]
This is only waiting for review/merge over in #2640. The problem itself is solved.
