### ISSUE TITLE
osrm-extract command using one core ?

### ISSUE THREAD

**Issue by H91011** [Project-OSRM/osrm-backend#2641]
Hi, 

I extract the map and I looked to htop command output for cpu usage. Only one core using for extract the map, is too little is it for this process? Why is not using all cores ?

**Comment by daniel-j-h** [comment]
`osrm-extract` uses [multiple threads](https://github.com/Project-OSRM/osrm-backend/blob/b00b15ab98612c7c3041d0932b3747cb8dcfef17/src/tools/extract.cpp#L37-L40) (the default depends on your system).
You can change the default via its `-t` option:

    osrm-extract --help
    ...
      -t [ --threads ] arg (=16)             Number of threads to use

If `osrm-extract` still is not able to keep more than one of your CPUs busy, you may be I/O bound. As in, you may have not enough RAM so you're swapping (slow), or you have really slow disks / network mounted share.

If this is not the case and you still can't get more than one CPU busy, we definitely need more information about your specific setup.

**Comment by H91011** [comment]
Thanks it is  enough for me. I use stxxl instead large ram. Its good well I have only 4 core and 8 GB ram.

**Comment by daniel-j-h** [comment]
Great! Closing here as not actionable for us!
