### ISSUE TITLE
Parse complex access tags

### ISSUE THREAD

**Issue by utack** [Project-OSRM/osrm-backend#2643]
Access tags can be quite uncomfortable.
One example of routing that should not happen:
https://www.openstreetmap.org/way/145766152

> motor_vehicle=destination;agricultural;forestry

You should be able to solve this with a simple logic however
First check for all the keys, for your vehicle, listed in the profile
For cars that would be "access, vehicle, motor_vehicle, motorcar"
Then, if some are found, use the most specific one for the vehicle in the profile and check if with one of the comma or semicolon specified tags it is explicitly whitelisted on this way/node
Not much though has gone into this, but I guess that should work? Probably needs some handling for poorly tagged ways

**Comment by emiltin** [comment]
an example of something that should be handles consistently across all profiles, and thus an argument for refactoring into reusable components, e.g #2032.
