### ISSUE TITLE
How do I create the segment-speed-file that can be fed to the contraction phase.i

### ISSUE THREAD

**Issue by srikary** [Project-OSRM/osrm-backend#2648]
I would like to collect GPS traces and update speed of each road segment based on the traffic in that segment. I read here (https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) that I can create a file which specifies the speed between two nodes. To do this, I assume that I would need to map the GPS trace point to a road segment. For this , I would need to know the coordinates of each road segment. How do I read in the mapping between node-id and lat, lon from the intermediate files after the osrm-extract phase? Are there tools to do this? My end goal is to create the speed-segment-file. Any pointers on how to create this from GPS data would be very helpful. 
Thanks in advance.

**Comment by daniel-j-h** [comment]
Using `--generate-edge-lookup` for `osrm-extract` generates a file for mapping from/to OSM ids to internal graph edges. You're not supposed to use and / or modify that file. Instead, you have to provide a CSV file to `osrm-contract`'s `--segment-speed-file` option with the format:

    from_osm_id,to_osm_id,edge_speed_in_km_h

Now the question is how to map from (potentially noisy) GPS traces to from/to OSM ids. OSRM provides Map Matching (snapping a trace to the road network) with its Match service for exactly this use-case:

https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-match

In https://github.com/Project-OSRM/osrm-backend/issues/2054 and https://github.com/Project-OSRM/osrm-backend/pull/2418 @lbud then exposed node ids in the response roughly a month ago. With this in place, you should be able to match GPS traces against the road network and get back node ids using the `annotations` feature.

Please tell us how it goes! :)

**Comment by srikary** [comment]
Thanks for the response Daniel. Will report back soon. After I posted this question, I was trying the postgres approach
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/examples/postgis.lua

**Comment by emiltin** [comment]
@srikary, since the Postgis example was written, a segment_function() has been added to the LUA scripts, allowing you to adjust the speed on individual segments of ways, not only per way. It will usually be slower, but enables more fine-grained adjustment of speeds.
We're using this to approach to prioritize green routes for cyclists, based on spatial queries for parks, green areas, lakes, etc. We preprocess osm tags when importing to Postgis with osm2pgsql, using the LUA script import option.

**Comment by danpat** [comment]
Nothing actionable here.
