### ISSUE TITLE
Enable routing over multipolygons (needed for pedestrian routing)

### ISSUE THREAD

**Issue by species** [Project-OSRM/osrm-backend#2655]
Currently, when a pedestrian area has their highway=tags set on the relation and not on the outer ways, routing is not even possible on the boundaries of the area.

Please enable a mechanism to 'copy' all relation tags to all member ways, so at least routing around the edges of multipolygon areas would be possible.

**Comment by danpat** [comment]
@species Patches welcome!

**Comment by emiltin** [comment]
see #482 for discussion on processing relations

**Comment by answerquest** [comment]
hello, any updates on this? I looked over the linked issue.. 
I marked a polygon which is accessible to pedestrians with `highway=pedestrian` and `area=yes`. That opened it up for routing, but the osrm router is sticking to the boundaries.

ref: https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=12.97990%2C80.24194%3B12.97861%2C80.24100#map=18/12.97913/80.24143

**Comment by systemed** [comment]
This is #64 and unlikely to be solved unless someone steps up and provides code, I suspect.

**Comment by ManDay** [comment]
I think this is more related to #482 (which is closed w/ fixed) than #64, routing *through* squares is not even asked for. Just that areas defined by multipolygon rels behave like their equivalent area counterparts.

OSRM routes *along* the `highway=pedestrian; area=yes` **area** but not *along* the `highway=pedestrian; area=yes` **relation** ([e.g.](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=42.01827%2C23.07887%3B42.01896%2C23.07849)). Shouldn't this already be fixed as by closure of #482?

**Comment by dreua** [comment]
I find it quite confusing that the routing along the edges works for regular areas but as soon as it is a multipolygon it is just not routeable at all. Using multipolygons to cut out a part of the area is nowadays quite common, for example if there is a small building (like a kiosk) or a large fountain on a pedestrian area or a steps leading to an underground tunnel on a railway platform (Mainz Hbf has this on an all platforms).
