### ISSUE TITLE
Improve Detection Mechanism for Successive Lane Changes / Improve Roundabout Lane announcements

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2661]
Currently, the detection mechanism for deciding which lanes to treat as one set of consecutive turns is relying on a single constant ([see here](https://github.com/Project-OSRM/osrm-backend/blob/50cbba16209182e0be451ae59d0626dd2bf1f56e/src/engine/guidance/lane_processing.cpp#L25)).

This has some serious drawbacks when it comes to roundabouts. The current test-case ([here](
https://github.com/Project-OSRM/osrm-backend/blob/50cbba16209182e0be451ae59d0626dd2bf1f56e/features/guidance/anticipate-lanes.feature#L262-L287)) that connects two roundabouts is passing more or less out of sheer luck.

The problems in that situation arise from two different decisions in the current code base.
For one, we only provide a single instruction for the full roundabout maneuver. In addition, lane-anticipation works in two steps. 
 * First: roundabout enter and exit are compared and, if required, the lanes are restricted (this is a heuristic that could be improved by also considering the `stay-on-roundabout` instructions in between). This is done separate, since roundabouts behave different than normal turns.
 * Second: A general lane-anticipation step is used to anticipate lanes for maneuvers spanning other instructions as well.

The resulting instructions, after we collapsed the full set of `enter, stay, stay, stay, ... , exit` into a single `roundabout-exit-n` instruction is that the duration between the enter and the next instruction does not consider the location of the exit anymore. Technically, we need to consider the time it takes from the exit to reach the next turn. The duration for the traversal of the roundabout and the following segment is combined into the single roundabout instruction, though.

To correctly anticipate maneuvers that include a roundabout, we need to keep these distances/improve the checking for durations to consider more than a single constant.
The roundabout itself will need to be considered as a single entity, at least since it is a continuous maneuver.

![locations-considered](https://cloud.githubusercontent.com/assets/12932279/16874908/83dc6214-4a9c-11e6-8f74-6b57fe604a21.png)

Right now, the green locations are considered during lane anticipation spanning roundabouts. We need to consider the red locations as well, though.

**Comment by daniel-j-h** [comment]
Roundabouts no longer have lanes to anticipate. Decision behind this is is https://github.com/Project-OSRM/osrm-backend/pull/2693. The single multi-hop roundabout instruction, represented by one enter instruction, is still problematic, though.
