### ISSUE TITLE
matching with or without realitic timestamp gives not the same result

### ISSUE THREAD

**Issue by bvbever** [Project-OSRM/osrm-backend#2668]
`https://router.project-osrm.org/match/v1/driving/polyline(evetHo{~VgFgPKQKEQHk@j@{@d@y@Fa@Ci@O_@Q]YGKBWNLd@Zp@Pb@Bl@It@a@NQNMNONQRSPUHG)?overview=full&steps=true&hints=jjMAgDLhAIARRgAAAAAAAHUQAADjNAAAHHAAAJCcAACPnAAAAQAAAND9OwB9BgUD0P07AH4GBQMcAAEBAjV37g==;;;;;;;;;;;;;;;;;;;;;;;;;;`

vs

`https://router.project-osrm.org/match/v1/driving/polyline(evetHo{~VgFgPKQKEQHk@j@{@d@y@Fa@Ci@O_@Q]YGKBWNLd@Zp@Pb@Bl@It@a@NQNMNONQRSPUHG)?overview=full&steps=true&timestamps=1;78;81;83;87;97;109;120;126;134;140;146;148;151;154;162;172;179;188;199;203;206;210;214;218;222;224&hints=jjMAgDLhAIARRgAAAAAAAHUQAADjNAAAHHAAAJCcAACPnAAAAQAAAND9OwB9BgUD0P07AH4GBQMcAAEBAjV37g==;;;;;;;;;;;;;;;;;;;;;;;;;;`

The first one uses a hint (startpoint) and without timestamps. This result seams correct.
But the same case **with realistic timestaps** drop's the first point.
Seams not correct.

**Comment by danpat** [comment]
@bvbever Adding timestamps changes the thresholds in the map-matching algorithm.  If no timestamps are applied, it's assumed that the coordinates are sampled at equal intervals.

https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/routing_algorithms/map_matching.hpp#L100-L109

If you supply timestamps, a heuristic is used to identify outliers.  There's a 77 second jump from your first sample to the second, but then the rest of them are usually about 5-6 seconds apart.  This is causing the first sample to get pruned.
