### ISSUE TITLE
Move Turn Lanes into Intersections

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2675]
After some internal discussion, we decided to move the turn lanes to the intersection object associated with every route segment.

This allows both the announcement of turn lanes for `maneuvers` as well as a visual indication for integrated guidance systems.

The API format would look like:

```json
{
 "distance":152.3,
 "duration":15.6,
 "name":"Lortzingstraße",
 "maneuver":{
     "type":"turn",
     "modifier":"right",
     },
 "geometry":"{lu_IypwpAVrAvAdI",
 "mode":"driving",
 "intersections":[
    {"location":[13.39677,52.54366],
    "in":3,
    "out":1,
    "bearings":[10,92,184,270],
    "entry":[false,"true","true"],
    "lanes":[
         {"indications":["left","straight"], "valid":"false"},
         {"indications":["right"], "valid":"true"}
    ]},
    {"location":[13.394718,52.543096],
    "in":0,
    "out":2,
    "bearings":[60,150,240,330],
    "entry":["false","true","true","true"],
    "lanes":[
         {"indications":["straight"], "valid":"true"},
         {"indications":["right"], "valid":"false"}
     ]}
]}
```

In this format, a turn has turn-lanes if the very first intersection in this list offers turn lanes.

The type `use lane` will persist for maneuvers that require an actual action of the driver. An example would be the restriction to one lane out of a larger subset of lanes.

Did I capture this correctly?

/cc @TheMarex @freenerd @daniel-j-h

**Comment by MoKob** [comment]
Required to decide when to emit use-lane: https://github.com/Project-OSRM/osrm-backend/pull/2666

**Comment by freenerd** [comment]
What is the design if an intersection does not have lane information? Will there be an empty object or a `null` in the response?

Is there a guarantee that the number of intersections and the number of lanes is always the same? What happens if there is no lane information at all or if only the first intersection has lane information, but the following don't?

**Comment by TheMarex** [comment]
> Is there a guarantee that the number of intersections and the number of lanes is always the same? What happens if there is no lane information at all or if only the first intersection has lane information, but the following don't?

- If there are no lanes, the `lanes` property will be `undefined`
- Each `Intersection` object either has a `lanes` property or not. they only describe the lanes _at the intersection_ hence there is no semantic link of lane information between intersections.

**Comment by freenerd** [comment]
@TheMarex Thanks. I updated the docs to reflect `undefined` https://github.com/Project-OSRM/osrm-backend/commit/f76e3d4522c5a4e8d03aeff0d73041224673e48c

I guess this ticket is ready to close?

**Comment by daniel-j-h** [comment]
Yes done.
