### ISSUE TITLE
Lanes Left / Right of Turn Lanes

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2679]
https://github.com/Project-OSRM/osrm-backend/commit/0e017a6ce53bf471b7e5671cddd745fa3a158914 as well as https://github.com/Project-OSRM/osrm-backend/pull/2671 need to know the lanes left of / right of a turn's lanes.

Such a feature should live in a toolkit header rather than duplicating the logic.

We should do this once advanced-lanes https://github.com/Project-OSRM/osrm-backend/pull/2614 is merged into master.
Otherwise it's too much of a headache to rebase all depending branches.

**Comment by daniel-j-h** [comment]
To be clear here: we should have two functions in `toolkit.hpp` for calculating the lanes to the left and to the right as in comparing the lane description and the lane tuple. See https://github.com/Project-OSRM/osrm-backend/commit/0e017a6ce53bf471b7e5671cddd745fa3a158914#diff-99adcb8bccf8e94a176bdf92509ff070R1170 for an example and the links above.

**Comment by TheMarex** [comment]
This was implemented in #3010.
