### ISSUE TITLE
Consider Staleness of Priorities

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2680]
The original publication of Contraction Hierarchies considers a method called `lazy updating`.
In this process, node-priorities are considered to be monotonously increasing and we can update them on-demand without making much of an error.
The process operates on a priority queue and introduces some serialisation we don't want in the contraction process.

We could think about methods of introducing it into OSRM nevertheless. The benefit here is that the general node-priorities don't change as often as it is currently assumed in the contractor and are a heuristic to begin with. Small errors might be acceptable if the benefit in processing time outweighs the penalty due to a slightly worse hierarchy.

The function in question is [UpdateNodeNeighbours](https://github.com/Project-OSRM/osrm-backend/blob/0e017a6ce53bf471b7e5671cddd745fa3a158914/include/contractor/graph_contractor.hpp#L998-L1027).
Updating all priorities of connected nodes is one of the main contributions to runtime. With node degrees increasing, every contraction is followed by `degree` numbers of additional Dijkstra computations to update the node-priority.

Reducing this number of computations can significantly speed-up the contraction. I've tested two very simple versions. Using our normal contraction, I was able to contract an extract of California in `1707` seconds. Adding a simple heuristic that doesn't update priorities every time, I reduced the time to `1141` seconds (close to a 30% reduction in processing time) for a graph that was only 3% larger than the normal CH.
For my heuristic, I only updated the priorities of neighbours at every second level. This heuristic is purely random and not reasonable at all, the effects are promising, though.

This is not a high priority task right now but something we could consider to reduce processing overheads with low impact on performance.

**Comment by danpat** [comment]
@MoKob how does this compare to choosing a different (less expensive) ordering heuristic?

**Comment by MoKob** [comment]
What kind of less expensive ordering heuristics are we talking about. It is essentially the same idea, since you don't keep the ordering heuristic updated all the time
