### ISSUE TITLE
Curl command in "running" guide does not work

### ISSUE THREAD

**Issue by eyaldev** [Project-OSRM/osrm-backend#2683]
I downloaded and compiled and ran the server.
Now I came to test it, and encountered the following issues.
The two examples you give on https://github.com/Project-OSRM/osrm-backend/blob/master/README.md are:
curl http://127.0.0.1:5000/13.388860,52.517037;13.385983,52.496891?steps=true&alternatives=true
and
curl https://router.project-osrm.org/13.388860,52.517037;13.385983,52.496891?steps=true&alternatives=true

However running these commands in Ubuntu/Windows/Firefox results in {"status_message":"Query string malformed close to position XXX","status":400}

I've also noticed that the examples are not quoted and contain special characters such as ampersends and semicolons. So I also tried to use all kinds of quotes. I also tried pasting the url in firefox.

The output on my osrm-routed looks like this:
[info] 21-07-2016 14:26:57 127.0.0.1 - Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 400 /13.388860,52.517037;13.385983,52.496891?steps=true&alternatives=true

**Comment by TheMarex** [comment]
Good catch. :+1: Fixed those.
