### ISSUE TITLE
HTTP API - route weird behaviour

### ISSUE THREAD

**Issue by dresende** [Project-OSRM/osrm-backend#2692]
I'm having this weird "butterfly" effect on some routes when this kind of highway exits occur. This is at `40.649380, -8.623711`, using `v5.3.0`. I pass the 4 points in the screenshot and ask osrm-routed (`/route/v1/driving/`) to give me the probable route. I'm also passing `overview=full` and `continue_straight=false` (although without them it behaves the same way).

I tried your demo page but it seems buggy or not working. I opened openstreetmap page and routed the points and it works fine (it's using your server but not version 5 - it's using the deprecated `viaroute`).

![screen shot 2016-07-22 at 17 49 19](https://cloud.githubusercontent.com/assets/157494/17064552/f71a4a5a-5034-11e6-9ece-e56c10a3fab3.png)

Any ideas if I'm doing something wrong?

**Comment by TheMarex** [comment]
Thanks for reporting. Could you provide us with the full request?

**Comment by dresende** [comment]
Well, curiously, if I construct the a custom query with the 4 points on the image, I draws correctly. If I try the full route it gives me the "butterfly effect". Here's the full route:

```
GET /route/v1/driving/-8.64286,40.6305963;-8.6431241,40.6304573;-8.6500625,40.6248265;-8.6518145,40.6259605;-8.6561156,40.6346243;-8.6553873,40.6355563;-8.6556605,40.6356705;-8.6559325,40.6353341;-8.6557365,40.630792;-8.6553528,40.6309926;-8.6550318,40.630743;-8.6544628,40.6302821;-8.6548925,40.630034;-8.6571826,40.6317198;-8.6573901,40.6316493;-8.6587178,40.6331656;-8.6564895,40.6351761;-8.6553081,40.6354216;-8.658109,40.637709;-8.65966,40.6385816;-8.658648,40.6419876;-8.6592376,40.6420008;-8.6608865,40.6410886;-8.6612208,40.6414863;-8.6532258,40.6466606;-8.6328626,40.6535585;-8.6228731,40.6484993;-8.6233138,40.6480535;-8.6240331,40.6482408;-8.62409,40.648798;-8.6094055,40.6665055;-8.6098721,40.6667891;-8.6097961,40.6669555;-8.6099251,40.666973?overview=full&continue_straight=false&geometries=geojson
```

Here's a gist with the geometry of the response:

https://gist.github.com/anonymous/8dd04eeefc91148a3b5b351ac61060c7

**Comment by dresende** [comment]
There is another side effect on another point of the route but I believe this might be caused by the same problem. I'm still not sure if I'm the one doing something wrong or not..

**Comment by daniel-j-h** [comment]
[This](http://map.project-osrm.org/?z=18&center=40.649630%2C-8.623114&loc=40.6305963%2C-8.64286&loc=40.6304573%2C-8.6431241&loc=40.6248265%2C-8.6500625&loc=40.6259605%2C-8.6518145&loc=40.6346243%2C-8.6561156&loc=40.6355563%2C-8.6553873&loc=40.6356705%2C-8.6556605&loc=40.6353341%2C-8.6559325&loc=40.630792%2C-8.6557365&loc=40.6309926%2C-8.6553528&loc=40.630743%2C-8.6550318&loc=40.6302821%2C-8.6544628&loc=40.630034%2C-8.6548925&loc=40.6317198%2C-8.6571826&loc=40.6316493%2C-8.6573901&loc=40.6331656%2C-8.6587178&loc=40.6351761%2C-8.6564895&loc=40.6354216%2C-8.6553081&loc=40.637709%2C-8.658109&loc=40.6385816%2C-8.65966&loc=40.6419876%2C-8.658648&loc=40.6420008%2C-8.6592376&loc=40.6410886%2C-8.6608865&loc=40.6414863%2C-8.6612208&loc=40.6466606%2C-8.6532258&loc=40.6535585%2C-8.6328626&loc=40.6484993%2C-8.6228731&loc=40.6480535%2C-8.6233138&loc=40.6482408%2C-8.6240331&loc=40.648798%2C-8.62409&loc=40.6665055%2C-8.6094055&loc=40.6667891%2C-8.6098721&loc=40.6669555%2C-8.6097961&loc=40.666973%2C-8.6099251&hl=en&alt=0
) is your query on the demo server:


![1](https://cloud.githubusercontent.com/assets/527241/17326627/cc8eeae4-58b2-11e6-8106-1075e4842284.png)

here you can see how your via is a bit off, forcing the route to a segment behind the one you're probably intending. Here I'm adjusting the via a bit:

![2](https://cloud.githubusercontent.com/assets/527241/17326626/cc8d786c-58b2-11e6-845d-19abcf817cd1.png)

Not sure why you're setting such a high amount of vias in the first place, but you better be sure about your via positions if you do so.

I'm closing this already as not actionable for us, feel free to comment.

**Comment by dresende** [comment]
The vias are positions recorded along a period, they have errors. I'm just trying to draw the possible/expected route along the recordings. Can I add an error to the via points?

**Comment by daniel-j-h** [comment]
In case you have GPS traces (since it's starting to look like it) maybe the Match service is what you want:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-match

Otherwise the only option I see would be to test a few different locations nearby for each via and see how the snapping changes the route. I can't think of a better way to do this at the moment.

**Comment by dresende** [comment]
Yes, those are GPS traces. I'll try your suggestion, thank you 👍

**Comment by danpat** [comment]
@dresende Yes, the `match` service is probably what you're after - it tries snapping the points to all nearby edges, and selects the *most probable* route.

The `route` service simply snaps your points to the nearest edge then routes between those points, it's not really intended for snapping entire GPS traces.

**Comment by dresende** [comment]
It works, although I wanted the route (to draw inside streets and not straight lines). I'm using overview=full and it seems to work almost flawlessly (assuming there are GPS errors). The overview produces a lot of points but leaflet seems to handle it to draw a line string just fine. Thank you very much!
