### ISSUE TITLE
Support for time-dependent ETAs

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2695]
This ticket is to sketch out how we might support post-routing ETA adjustments.

True time-dependent routing (considering weight values from the future as the route search progresses) is quite difficult in general, and _particularly_ difficult in a CH.  It's out of reach for now.

However, in situations where there is a historical profile available for traffic conditions, even if we can't provide the perfect **route** for future conditions, we can at least consider adjusting the ETA for the returned route.  This would mean stepping over each segment in the route, and updating the duration based on a future prediction that understands how far the route has gone so far.  Roughly, convert our 1xM weight data array into a NxM weight data array at fixed intervals.  The CH would still only route on M[0].

This requires a lot of data, so it's not going to be for everyone - i.e. this feature needs to be optional.

Rough outline of a naive implementation:
1. Extend `osrm-extract` to import time-bucketd traffic data files, and generate multiple compressed weight arrays in the `.geometry` file (it would make sense to split these out).
2. Add a parameter to supply a "start at" timestamp
3. Extend `GetUncompressedWeights` to understand multiple time buckets
4. Modify [this](https://github.com/Project-OSRM/osrm-backend/blob/59057081112ca5c39b5b581b11e730717a83feb5/include/engine/routing_algorithms/routing_base.hpp#L328) and [this](https://github.com/Project-OSRM/osrm-backend/blob/59057081112ca5c39b5b581b11e730717a83feb5/include/engine/routing_algorithms/routing_base.hpp#L394) to look at future buckets as the route progresses instead of just a static bucket.

Several things immediately jump to mind:
1. There's an obvious second modification to supply an "arrive by" variant of the logic (i.e. unpack the route in reverse).
2.  The dataset here is likely to be huge - it might make sense to only have a couple of hours of future data in memory.  Careful use of `mmap` and `madvise` might be the way to go here.
3.  The above implementation assumes dense data - it might be worth thinking about how this would look for sparse data (i.e. major road traffic data only).
4.  If real data isn't available, it could still be possible to provide a dynamic function (in Lua/JS?) that provides the future data, rather than just doing a lookup.  This would be slower, but would allow people without data to create usable models.  An alternative to dynamic support would be a tool to generate big lookup files.
5.  Handling turn penalties needs to be thought about - the above idea just covers segment weights, not turn costs.
6.  This opens the timezone/daylight-savings can-of-worms.

To get an idea of the data sizes involved for California:

The `.geometry` file contains all possible segments, and their weights.  We can get a count of all segments withwith:

```
$ head -c 4 california-latest.osrm.geometry | od -An -D
4529801
```

Thus, we're storing (unsigned int) `4 * 4,529,801 = 18,119,204` bytes for segment weights for California.

My working assumption is that a weekly historical profile would work (anyone got any references that backs that up?).  If we support adjusting traffic every 15 minutes, we'll need 672 profiles for a week.  In a naive approach, this means 12,176,105,088 (12GB) of profile data for California.  For 5 minutes, this grows by 3x to 36,528,315,264 (36GB).

Looking at the OSRM demo server, it looks like the OSM planet has 280,377,201 weight values, so we're looking at 188,413,479,072 (188GB) for 15 minute increments, or 565,240,437,216 (565GB) for 5 minute increments.

There are obvious inefficiencies here and I think it's worth discussing what could be done to address them:
1. overnight periods probably don't change much and are mostly the same
2. as a counterpoint to this, if we do this on a global scale, it's always peak hour somewhere 😛 
3. It's _really_ unlikely that we're going to need more than a couple of hours of future data to be fast-accessible at any time.  Again, `mmap` and `madvise` might be the solutions here.
4. Storing 4 bytes per weight might be overkill - we could probably just store differences here.

As a nifty side-effect, we could consider doing this for our main route and our alternative route, and if it turns out the alternative route is better after updates, returning that as the "fastest".

@TheMarex @daniel-j-h @MoKob thoughts?

**Comment by emiltin** [comment]
Sounds cool, but at the moment the basic ETA is very inaccurate, since weight and speed is not independent and you therefore have to misuse the speed to prioritize e.g. green routes for cyclists. Currently we have to ignore the ETA provided my OSRM and compute it in the front-end simply as distance/avg_speed. Might be worth fixing first.

For bicycles, the ETA is heavily dependent on the cyclist since people ride with very different speeds, and a data-driven ETA might therefore not be very precise anyways, or at least would have to incorporate the type of cyclist.

**Comment by danpat** [comment]
@emiltin This is primarily aimed at car routing where almost everyone goes the same speed.

Do you have any travel speed data for bikes? I'd be interested to see it.

**Comment by emiltin** [comment]
I think time-depending ETA is also useful for bikes. In Copenhagen we have crowding on many bike tracks in rush hours, causing travel times to increase (although it's nothing like cars in a queue). It's just that the individual speed of the cyclist has a bigger influence, and thus might be worth handling first.
We (the City of Copenhagen) don't yet have any big GPS dataset of bike trips. But we do have measurements of the distribution of bike speeds on specific corridors. We use it for e.g. VISSIM simulations.
We also expect to collect more data on the bike traffic in the coming years, probably in large parts via mobile apps that collect GPS traces. Either via our own our I Bike CPH app or from commercial suppliers that source data from various apps.

**Comment by jcoupey** [comment]
Just curious about how this approach might possibly affect (enhance) the `table` requests?

My understanding is that the use-case would be limited to `route` requests, as for matrices only the costs are computed and the actual route geometries are not unpacked from CH.

**Comment by Vishwajit1986** [comment]
@danpat , i have historical traffic data for every 15 min for car profiles. could you help me to achieve True time-dependent routing?

**Comment by danpat** [comment]
@Vishwajit1986 Only on a whiteboard - OSRM doesn't support it currently.

**Comment by adityadarak** [comment]
@danpat Is there any plan for implementing this? I am planning to work on this and would need some help from your side. This update will definitely improve the ETA. Is there any future plans of working on this?

**Comment by wangyoucao577** [comment]
> Thus, we're storing (unsigned int) 4 * 4,529,801 = 18,119,204 bytes for segment weights for California.
> 
> My working assumption is that a weekly historical profile would work (anyone got any references that backs that up?). If we support adjusting traffic every 15 minutes, we'll need 672 profiles for a week. In a naive approach, this means 12,176,105,088 (12GB) of profile data for California. For 5 minutes, this grows by 3x to 36,528,315,264 (36GB).
> 
> Looking at the OSRM demo server, it looks like the OSM planet has 280,377,201 weight values, so we're looking at 188,413,479,072 (188GB) for 15 minute increments, or 565,240,437,216 (565GB) for 5 minute increments.

@danpat How about consider the 672 profiles as a curve for each segment. For each segment store a curve id for it, for OSM planet need about `280,377,201 * 4` = 1.1GB for curve ids. Store all `curve-id ~ 672 profiles` mapping in another file, then consider some way to reduce the data. For a whole plane, there're totally about `280,377,201` curves, each curve have `672` sampling data. Many of these curves should be very similar (e.g. especially use speed as each sampling data), we can use some method like machine learning classification to remove similar ones only keep a representative one. Even it will lose some precision, but it can reduce a lot of data.
