### ISSUE TITLE
Split a way's "Name (Ref)" into name, ref fields

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2704]
Currently we re-write a way's name to

    "Name (ref)"

where ref could be the destination if there is no ref. This string-representation is hachky at best and makes it harder for clients to build great guidance.

Task: have independent `name`, `ref`, `destination` fields and expose them to clients.

cc @freenerd @1ec5 @bsudekum

Impl. note: will break hard coded hacks like:
- https://github.com/Project-OSRM/osrm-backend/blob/c7a1576100cb947af0e970644fb3f70dde63a9eb/include/extractor/guidance/toolkit.hpp#L166-L168

**Comment by 1ec5** [comment]
Should ref and destination be simple strings, or should they be something more complex like arrays of strings? It's already possible for a way to have multiple refs and multiple destinations delimited by semicolons in OSM data. It wouldn't be the end of the world for a client to split strings by this delimiter, but an array would be more semantically correct.

Looking ahead to #482, if OSRM ever gains built-in support for route relations, each ref would need to be a dictionary with separate network and (numeric) ref fields. But that's clearly a bit further off.

**Comment by daniel-j-h** [comment]
We're passing name, ref, destination through the pipeline and deduplicating them based on their string representation anyway.

What we could do in post-processing is the split+trim dance on the strings already for you, returning arrays if that's more convenient.

**Comment by TheMarex** [comment]
I would be more comfortable with passing through `name`, `ref` and `destination` directly from the base map. Running string processing that makes assumptions about structure in OSRM is something we want to get away from. Changing this to arrays would be a breaking API change that I'm not willing to do right now.

**Comment by 1ec5** [comment]
How would the use of arrays be a breaking change? Separate ref and destination fields haven't been introduced yet.

In any case, there's still a possibility of the frontend to split the strings into an array so the client doesn't have to. (That would be especially important if route relation support were on the roadmap, in which case a single string wouldn't be flexible enough.)

**Comment by daniel-j-h** [comment]
We do have a `destinations` field since 5.2 (=> [Changelog](https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#520)).

**Comment by TheMarex** [comment]
We already expose `destinations` as string:

https://github.com/Project-OSRM/osrm-backend/blob/fb4834458eb0157c06075c85dca3e791a05d1d6e/docs/http.md#routestep

https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/api/json_factory.cpp#L233

**Comment by 1ec5** [comment]
Ah, sorry, I conflated the situation for ref with the situation for destination. I think my point still stands for the former, though: a client is likely to be able to use the destination verbatim, but the ref would need to be more structured in order to reliably support UI niceties like proper route shields or [TTS-optimized](https://mapzen.com/blog/voice-guidance) guidance instructions.

**Comment by daniel-j-h** [comment]
@1ec5 @bsudekum keeping you in the loop here:

@karenzshea is working on this in https://github.com/Project-OSRM/osrm-backend/pull/2857. Once this lands, the response will have fields for

- name
- ref
- destinations

and we no longer use string-based "name (ref / destination)" hacks. Since we're only adding fields to the response technically speaking this is not a breaking change. The client logic has to change anyway. Anything from your side here?

(We aimed for getting this into 5.4; it looks like we have to wait for 5.5 since an RC for 5.4 is already out)

**Comment by 1ec5** [comment]
The frontend already parses out the destination from the way name; now it needs to look at the separate field instead (and fall back to string parsing for the v4 translation?).

On the client side, we'll have to serialize the new field as well: mapbox/MapboxDirections.swift#67.

**Comment by MoKob** [comment]
Implemented on the OSRM backend-side.
