### ISSUE TITLE
v5 demo server hits another lane assertion during extraction

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2706]
Bad week for the demo server, it's currently hitting another one:

```
[assert] /mnt/ebs/osrm/2016-07-26-110507/src/extractor/guidance/turn_lane_augmentation.cpp:285
in: osrm::extractor::guidance::lanes::LaneDataVector osrm::extractor::guidance::lanes::handleNoneValueAtSimpleTurn(osrm::extractor::guidance::lanes::LaneDataVector, const Intersection&): connection_count + 1 == lane_data.size()
terminate called without an active exception
```

https://github.com/Project-OSRM/osrm-backend/blob/c7a1576100cb947af0e970644fb3f70dde63a9eb/src/extractor/guidance/turn_lane_augmentation.cpp#L283-L286

this is on the `5.3` branch.

**Comment by TheMarex** [comment]
Currently processing on `v5.1.0-rc.1` to narrow down when this was introduced.

**Comment by TheMarex** [comment]
Processing failed due to a wrong assertion on `RC1`. Trying processing before we introduced lane guidance on `2a05b70dfcdee1bf3f1ffa4fd1a6e1b1663984fc`.

**Comment by TheMarex** [comment]
Hitting a different assertion now:

> [assert] /mnt/ebs/osrm/2016-07-27-083413/src/extractor/edge_based_graph_factory.cpp:407
in: void osrm::extractor::EdgeBasedGraphFactory::GenerateEdgeExpandedEdges(const string&, lua_State*, const string&, const string&, bool): terminate called without an active exception

Going to try `2868f702a5da7eaeaa4d07032006cf5472407f8c` to narrow this down even more.

**Comment by daniel-j-h** [comment]
@danpat [`fix/2706-debug`](https://github.com/Project-OSRM/osrm-backend/tree/fix/2706-debug) currently runs on a separate demo server instance, which should help us to produce cucumber tests for this issue and have a look at the lane data.  [`fix/2706`](https://github.com/Project-OSRM/osrm-backend/tree/fix/2706) removes the wrong assertion and should then contain regression cucumber scenarios for lane access tags https://github.com/Project-OSRM/osrm-backend/commit/7d076e93445a4d016422a575f1132b267cd13c29.

**Comment by TheMarex** [comment]
Crash seems to be connected to a specific dataset - running 5.2.7 to confirm.

**Comment by daniel-j-h** [comment]
```
[assert] /mnt/ebs/osrm/2016-07-27-173001/src/extractor/guidance/turn_lane_handler.cpp:356
in: osrm::extractor::guidance::lanes::TurnLaneHandler::isSimpleIntersection(const LaneDataVector&, const Intersection&) const::<lambda()>: lane_data.front().tag == TurnLaneType::uturn
```

https://github.com/Project-OSRM/osrm-backend/blob/d8a692740a6b774a5704ac553fd6779e3c63a314/src/extractor/guidance/turn_lane_handler.cpp#L356

**Comment by TheMarex** [comment]
Hitting this on `5.2.7` on current planet:

> [warn] /mnt/ebs/osrm/2016-07-28-082311/src/extractor/edge_based_graph_factory.cpp:407in: void osrm::extractor::EdgeBasedGraphFactory::GenerateEdgeExpandedEdges(const string&, lua_State*, const string&, const string&, bool):

Points a weirdly broken input file or quite old bug in pre-processing.

**Comment by TheMarex** [comment]
Going to deploy `5.2.7` + europe from geofabrik to narrow down the problem.

**Comment by TheMarex** [comment]
Europe is fine.

Going to deploy 5.2.7 + north america from geofabrik to narrow down the problem.

**Comment by TheMarex** [comment]
Problem seems to be in the africa dataset. Going to try the dataset from 01.07 to confirm that this is our breaking change.

**Comment by TheMarex** [comment]
Isolated the breaking dataset as Egypt which has suffered some failed imports/vandalism. Currently trying to figure out what make OSRM choke by stepping through the datasets.

**Comment by TheMarex** [comment]
I'm down to one of these changesets breaking data updates:

```
<?xml version=1.0 encoding=UTF-8?>
<osm version=0.6 generator=OpenStreetMap server copyright=OpenStreetMap and contributors attribution=http://www.openstreetmap.org/copyright license=http://opendatacommons.org/licenses/odbl/1-0/>
  <changeset id=40938983 user=Mohawow uid=3502717 created_at=2016-07-21T23:37:01Z closed_at=2016-07-22T01:05:27Z open=false min_lat=31.0545268 min_lon=29.7586905 max_lat=31.205582 max_lon=29.9209474 comments_count=0>
    <tag k=created_by v=JOSM/1.5 (10526 en)/>
    <tag k=comment v=Adding new roads/>
  </changeset>
  <changeset id=40938855 user=Mohawow uid=3502717 created_at=2016-07-21T23:21:16Z closed_at=2016-07-21T23:28:00Z open=false min_lat=29.258551 min_lon=31.1791404 max_lat=29.3632231 max_lon=31.2855153 comments_count=0>
    <tag k=created_by v=JOSM/1.5 (10526 en)/>
    <tag k=comment v=Adding new roads/>
  </changeset>
  <changeset id=40938776 user=AlexOlpe uid=3503900 created_at=2016-07-21T23:14:04Z closed_at=2016-07-21T23:14:06Z open=false min_lat=26.8346476 min_lon=33.9440244 max_lat=26.8402262 max_lon=33.9548791 comments_count=0>
    <tag k=comment v= />
    <tag k=locale v=de/>
    <tag k=host v=https://www.openstreetmap.org/id/>
    <tag k=imagery_used v=Bing/>
    <tag k=created_by v=iD 1.9.7/>
  </changeset>
  <changeset id=40938752 user=AlexOlpe uid=3503900 created_at=2016-07-21T23:11:44Z closed_at=2016-07-21T23:11:45Z open=false min_lat=26.8350506 min_lon=33.9443454 max_lat=26.8386918 max_lon=33.9541472 comments_count=0>
    <tag k=comment v= />
    <tag k=locale v=de/>
    <tag k=host v=https://www.openstreetmap.org/id/>
    <tag k=imagery_used v=Bing/>
    <tag k=created_by v=iD 1.9.7/>
  </changeset>
  <changeset id=40938676 user=eric22 uid=160949 created_at=2016-07-21T23:04:30Z closed_at=2016-07-21T23:04:35Z open=false min_lat=31.9483018 min_lon=34.892613 max_lat=31.9533531 max_lon=34.8972207 comments_count=0>
    <tag k=created_by v=JOSM/1.5 (9979 en)/>
    <tag k=comment v=streets and buildings, lod, israel/>
  </changeset>
</osm>
```

**Comment by TheMarex** [comment]
It is this changeset http://www.openstreetmap.org/changeset/40938983#map=14/31.1423/29.8277

There are some overlapping edges at http://bl.ocks.org/d/973b5d919ad4b904c4f5c46002c841c9 that cause the edge de-duplication to fail as it seems.
