### ISSUE TITLE
height data

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#271]
avoiding hill can be important to bicycles.

we have a height model of copenhagen, based on a 2x2 meter grid. the current format is ArcInfo Binary Grid. what format would be needed if osrm was to use it?

i suppose the data would have to somehow be combined with the NASA data that covers outside copenhagen.

**Comment by perliedman** [comment]
For anyone else finding this issue, like I did, I wrote up how I added elevation for bike routing in OSRM: http://www.liedman.net/2015/04/13/add-elevation-data-to-osrm/

Parts heavily inspired from what I read in this issue and others.

Note: there are probably lots of other/better ways to do this, but this works fairly well for me so far.

**Comment by emiltin** [comment]
nice work per!
you write you only considers ways with highway=*. are you also handling other tag combinations that indicate that you can cycle? from bicycle.lua:

```lua
  -- initial routability check, filters out buildings, boundaries, etc
  local highway = way:get_value_by_key("highway")
  local route = way:get_value_by_key("route")
  local man_made = way:get_value_by_key("man_made")
  local railway = way:get_value_by_key("railway")
  local amenity = way:get_value_by_key("amenity")
  local public_transport = way:get_value_by_key("public_transport")
  if (not highway or highway == '') and
  (not route or route == '') and
  (not railway or railway=='') and
  (not amenity or amenity=='') and
  (not man_made or man_made=='') and
  (not public_transport or public_transport=='')
  then
    return
  end
```

**Comment by perliedman** [comment]
@emiltin that's an interesting question. Currently, I only do calculations for `highway`.

My guess is that `railway` and `public_transport` should not be affected by elevation, but perhaps the other ones?

**Comment by TheMarex** [comment]
Support for raster data has landed in `develop`.
