### ISSUE TITLE
Handle HOV lane information

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2711]
http://wiki.openstreetmap.org/wiki/Key:hov

Especially HOV-only routed are a problem at the moment as they're faster and therefore always preferred in finding the shortest path.

cc @danpat

**Comment by danpat** [comment]
Just to clarify the issue here:  road sections that are HOV-only, like this bypass:

http://www.openstreetmap.org/way/11198595

should probably be excluded from the default routing profile.  The profile should make enabling/disabling use of HOV-exclusive ways configurable, and default to "off".

**Comment by daniel-j-h** [comment]
This already landed in https://github.com/Project-OSRM/osrm-backend/pull/2724 disabling hov-only ways by default. Closing here.
