### ISSUE TITLE
Overflow in speed updates

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2713]
@danpat thinks there's an overflow still in the speed updates.  If a speed of 0 is found, we set the whole edge weight to INVALID_EDGE_WEIGHT.  But then we still add the turn penalty.

Overflowing here when `new_weight == INVALID_EDGE_WEIGHT`:

https://github.com/Project-OSRM/osrm-backend/blob/master/src/contractor/contractor.cpp#L823

- write a test case for this and https://github.com/Project-OSRM/osrm-backend/pull/2688
- fix it

**Comment by daniel-j-h** [comment]
If you build `osrm-backend` with `CXXFLAGS="-fsanitize=integer"` you should see the exact location where the overflow occurs.
