### ISSUE TITLE
Question on the ability to download the OSRM map to hard drive and ping the downloaded map via OSRM functions

### ISSUE THREAD

**Issue by layzre** [Project-OSRM/osrm-backend#2714]
Hello,

I am fairly new to R and OSRM. I realized that last week there was a problem with the OSRM Public API and that the OSRM was not responding. In order to avoid this problem in the future, I am trying to install my own instance of OSRM onto my hard drive, and then somehow reconfigure the implementation of the OSRM functions such as "osrmTABLE" to ping the downloaded map. I would like to pick your guys' brains and see where you recommend I start with 1) downloading the OSRM map, and 2) how to ping the downloaded map when using OSRM functions. 

Thanks in advance!

**Comment by layzre** [comment]
I am running OSRM on R on a Windows computer

**Comment by daniel-j-h** [comment]
There are pre-built Windows binaries at
http://build.project-osrm.org/

and a Wiki page for how to compile OSRM on Windows
https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation

That said, I'm not sure about the state of OSRM on Windows to be honest.

Our primary targets are Linux and OSX.

**Comment by TheMarex** [comment]
Closing here as not actionable anymore.
