### ISSUE TITLE
More Robust Roundabout Radius Calculation

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2716]
For three-or-more-node roundabouts we're currently only using the first three nodes for calculating the roundabout's radius. This results in problems when the roundabout is not perfectly round but instead nodes later on are places far outside the perfect circle.

Consider this partial example:
```
    *
 *
    *
       *
           *                                *
                *                         *
                     *                 *
                            *     *

```

or when a rotary way is modelled in detail:
```
     *
   *
      *
     *
       *
         *
            *
                *
```

The first three _roundabout nodes_ make up for a small radius, therefore we never consider this a rotary.

Location: https://github.com/Project-OSRM/osrm-backend/blob/b0873e2aa42f05825183faa2919b2f8d5502c455/src/extractor/guidance/roundabout_handler.cpp#L292-L309

**Comment by oxidase** [comment]
One possibility could be an MSE fitting of a circle into coordinate points, so it will give the center and the radius of the roundabout. There are many approximations to avoid costly QP, like Kåsa fit http://people.cas.uab.edu/~mosya/cl/MATLABcircle.html

**Comment by MoKob** [comment]
Just a note: For all calculations we have to keep in mind that the radius computations need to be identical coming from all entries/exits. I have to have a look at the different options, but right now my feeling would be that getting the extremes (min/max lat/lon) and selecting three fitting vertices could be a simple way.

**Comment by MoKob** [comment]
An alternative approach that came to me would be to use the circumference of the roundabout rather than the radius (or guess a radius from the circumference). If the circles don't follow an actual circle, this could be more robust and less error-prone.

@daniel-j-h @oxidase Whats your take on this?

**Comment by oxidase** [comment]
This sounds good, but it requires two assumptions:
* all points are in the convex hull
* points are ordered

Otherwise it would require construction of the convex hull.

**Comment by MoKob** [comment]
Well, we don't need to have a correct radius. We can make the full assumption on when to announce as roundabout/rotary based on `duration` that we are in the roundabout. So if a full traversal of a roundabout takes `x` seconds, we assume it to be small. Or if it is at least `m` meters long, we assume it to be a rotary.

Using this we would not need a complex calculation of the radius but rather only traverse all edges for their length.

This might be just as robust, if not even more. The distance calculation is even already available. Currently its just not stored with the edges of the graph.
