### ISSUE TITLE
Road not returning from android application(OSMBonusPack and an application based on that)

### ISSUE THREAD

**Issue by Isratmity01** [Project-OSRM/osrm-backend#2722]
I've been trying to use your routing api 
"http://router.project-osrm.org/route/v1/driving/X1,Y1;X2,Y2?alternatives=false&overview=full&steps=true"

I'm not receiving any result. Is the API functioning? I've tried to use this from both OSMBonusPack and also an android application I'm currently working on. Can you suggest what should be done?

**Comment by TheMarex** [comment]
Our demo server is currently down because we hit a problem during data processing (say hi to the Egypt data import... :wave: ). We have a likely fix but it will take a few hours until this is processed. Stay tuned.
