### ISSUE TITLE
Unncessary turn instructions at Hermannstraße/Brücke

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#2725]
@MoKob This should be silent.

<img width="836" alt="screen shot 2016-08-01 at 15 27 33" src="https://cloud.githubusercontent.com/assets/25713/17295486/a6612dfc-57fc-11e6-9f11-6492f8762b48.png">

https://map.project-osrm.org/?z=18&center=52.466712%2C13.432256&loc=52.466161%2C13.432084&loc=52.468099%2C13.430915&hl=en&alt=0

Interestingly when coordinates are reversed, no instructions are emitted.

<img width="769" alt="screen shot 2016-08-01 at 15 29 05" src="https://cloud.githubusercontent.com/assets/25713/17295504/b705309a-57fc-11e6-93a0-7b3505b832a6.png">

https://map.project-osrm.org/?z=18&center=52.466712%2C13.432256&loc=52.466161%2C13.432084&loc=52.468099%2C13.430915&hl=en&alt=0

The fork leading up to the bridge seems about symmetrical, so not sure why different directions lead to different instructions.

**Comment by daniel-j-h** [comment]
Thanks for flagging, thi is interesting not only because of the issues you mentioned but because of the following (notice the instructions):

![right](https://cloud.githubusercontent.com/assets/527241/17302508/d56902c6-581c-11e6-9001-949c7936505f.png)

![left](https://cloud.githubusercontent.com/assets/527241/17302509/d56eed62-581c-11e6-815b-b9ed93004aa3.png)

flipping from right to left --- looking into this now.

**Comment by daniel-j-h** [comment]
- [Mapillary Trace](https://www.mapillary.com/app/?lat=52.46648333333334&lng=13.431908333333325&z=17&focus=photo&pKey=LWXnKqoGqUNLnG0lofiO0Q)
- [OSM data layer](http://www.openstreetmap.org/#map=19/52.46747/13.43158&layers=D)

**Comment by daniel-j-h** [comment]
Response `type: depart, modifier: left`:

    http --body 'https://router.project-osrm.org/route/v1/driving/13.431537,52.466593;13.430915,52.468099?steps=true&alternatives=false

Response `type: depart, modifier: right`:

    http --body 'https://router.project-osrm.org/route/v1/driving/13.432143,52.466675;13.430915,52.468099?steps=true&alternatives=false

Per the [v5 API](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md):
> depart/arrive     modifier indicates the position of departure point and arrival point in relation to the current direction of travel

`depart left`, `depart right` does not mean "make a turn to the left / right" but instead "the departure point is to the left / right". The v5 responses are correct, the frontend just does a bad job at communicating this.

cc @1ec5 flagging for potential interest in response behavior.

**Comment by MoKob** [comment]
The initial problem is correct. I will look into this. The going straight part should be silent.

**Comment by MoKob** [comment]
For some reason I can't replicate this on the demo-server anymore. Don't know what could have changed this. Although some improvements got merged in between.

**Comment by MoKob** [comment]
With https://github.com/Project-OSRM/osrm-backend/pull/2727, this issue should be solved
