### ISSUE TITLE
Do not emit merge on residential road

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#2726]
This feels wrong. It's a `merge slight left` but I would have expected a `turn slight right`. I guess what we see here is merge behaviour intended for highways, but instead we are looking for turn behaviour on residential roads here. Maybe we should just generally disable merges on all highway classes below primary?

<img width="1161" alt="screen shot 2016-08-01 at 15 35 01" src="https://cloud.githubusercontent.com/assets/25713/17295663/86ba2822-57fd-11e6-9379-b9d3e38ca9bb.png">

https://map.project-osrm.org/?z=18&center=52.475251%2C13.431108&loc=52.475017%2C13.429220&loc=52.474909%2C13.432862&hl=en&alt=0

/cc @MoKob

**Comment by TheMarex** [comment]
I think this was fixed with https://github.com/Project-OSRM/osrm-backend/pull/2657

**Comment by daniel-j-h** [comment]
Yes, 2657 constrains merges to motorway classes only. Closing here as fixed.
