### ISSUE TITLE
Better caching for cucumber

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2745]
Currently cucumber caches files depending on the hash of `osrm-contract`, `osrm-extract` and the pre-processing tools. However this cache is never cleared if the hash of any dependency changes.
This leads to big problems on travis since we cache `test/cache` and this file just keeps growing util we can't upload it anymore.

Furthermore we put all files in a single directory, which makes path lockups notoriously slow. So we should nest the directories.

**Comment by TheMarex** [comment]
I think a new much simpler caching scheme will work better:

```
test/cache/{feature_uri}/{FEATURE_FILE_HASH}/{SCENARIO_TOKEN}.osm
test/tmp/{feature_uri}/{SCENARIO_TOKEN}.osrm*
```

That means we will only cache the `osm` files not the OSRM files.

**Comment by springmeyer** [comment]
> Furthermore we put all files in a single directory, which makes path lockups notoriously slow.

Just noticed another side effect of this, so 👍  to using some directory structure:

```
rm -rf test/cache/*
-bash: /Users/dane/.homebrew/opt/coreutils/libexec/gnubin/rm: Argument list too long
```

**Comment by emiltin** [comment]
Good idea to improve this. But why don't you want to cache osrm files? That means you will have to run extraction and contraction again even if the binaries didn't change at all.

**Comment by TheMarex** [comment]
Yes caching OSRM files is desirable but the dependencies are just complicated to track. Maybe the following scheme would also work:

```
test/cache/{feature_uri}/{FEATURE_FILE_HASH}/{SCENARIO_TOKEN}.osm
test/cache/{feature_uri}/{FEATURE_FILE_HASH}/{OSRM_HASH}/{SCENARIO_TOKEN}.osrm*
```

I realized just caching the OSM files will not give us a big speed-up since we need to generate them anyway internally (to fill the lookup tables for translating names).
