### ISSUE TITLE
OSRM 5.x API returning 504 GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by mikini** [Project-OSRM/osrm-backend#2757]
As reported in https://github.com/openstreetmap/openstreetmap-website/issues/1263 the OSRM 5.x API is currently returning HTTP status code 504 GATEWAY_TIMEOUT. This breaks routing on openstreetmap.org.

I suspect this could be connected to https://github.com/openstreetmap/openstreetmap-website/issues/1161 and the API shutdown announced at https://lists.openstreetmap.org/pipermail/osrm-talk/2016-August/001275.html.

**Comment by danpat** [comment]
@mikini A critical bugfix was pushed to `master`, and the OSRM demo server was bounced in order to pick up the change.  Unfortunately, this involves a roughly 6-8hr data-reprocessing lag.  The demo server isn't quite set up well enough to provide high-availability at this stage.

**Comment by TheMarex** [comment]
Yes I had to cycle the server. Sorry for the down time.
