### ISSUE TITLE
Issue on installing windows verison

### ISSUE THREAD

**Issue by bgani** [Project-OSRM/osrm-backend#2761]
I tried to install windows version, but i faced with an issue.
Below steps, that i did: 
1) I download [Release build](http://build.project-osrm.org/) and extract it
2) Created profile.lua file with content :  
`require("lib/access")
require("profiles/car")`
3) Dowload  [pbf file ](http://download.geofabrik.de/)
4) I set command `C:\osrm-backend>osrm-extract kazakhstan-latest.osm.pbf`. osrm-extract. And i get :  
`C:\osrm-backend>osrm-extract kazakhstan-latest.osm.pbf
[info] Using script profile.lua←[0m
[info] Input file: kazakhstan-latest.osm.pbf←[0m
[info] Profile: profile.lua←[0m
[info] Threads: 4←[0m
[STXXL-MSG] STXXL v1.4.99 (prerelease/Release) (git 1babe452214b4613a2a488d80073
f4185c05a0b3) + gnu parallel(__GLIBCXX__)
[STXXL-MSG] Disk 'c:\temp\stxxl' is allocated, space: 10000 MiB, I/O implementat
ion: wincall queue=0 devid=0
[info] Parsing in progress..←[0m`
Then appeared dialog window with message : `osrm-extract.exe has stopped working` 
What i am doing wrong ?

**Comment by daniel-j-h** [comment]
cc @ssuluh @BergWerkGIS

**Comment by BergWerkGIS** [comment]
Sounds similar to https://github.com/Project-OSRM/osrm-backend/issues/2735

It was solved there by using

<pre>
osrm-extract<b>.exe</b>
</pre>

instead of just

```
osrm-extract
```

**Comment by bgani** [comment]
@BergWerkGIS  Thank you, problem was on profile.lua content. To solve it, i delete profile.lua and rename car.lua to profile.lua .  Can i use multiple profiles, and if it is possible how to do it ?

**Comment by daniel-j-h** [comment]
Great it worked! You can use the `-p` flag as in

    osrm-extract data.osm.pbf -p profiles/car.lua

to specify the profile getting used.

For running multiple profiles simultaneously you have to extract/contract for all of the profiles. Then start multiple `osrm-routed` servers on different ports pointing them to the `*.osrm` file for each profile.

Closing here already as not actionable for us. Feel free to comment.

**Comment by bgani** [comment]
@daniel-j-h  How to point port on execute osrm-routed ? I didn't find in wiki .  Is it correct workflow below ?

1) execute osrm-extract.exe and  osrm-contract.exe for each profile: 

> data-car.osm.pbf for car.lua,  data-foot.osm.pbf for foot.lua

2) start osrm-routed.exe on different ports.
