### ISSUE TITLE
Wrong response from server

### ISSUE THREAD

**Issue by bgani** [Project-OSRM/osrm-backend#2762]
Requset: 
`http://192.168.1.25:5000/route/v1/car/51.17436,71.42486;51.16998,71.41272?geometries=polyline&overview=simplified`

Response:
`{
    "waypoints": [
        {
            "location": [
                61.149053,
                54.078186
            ],
            "name": "75К-400",
            "hint": "pmgBgEt9AoDaagAAFwAAAAAAAACoLwAAAAAAAHJzAACI8QIAVwAAAH0PpQPqKjkD2NsMA1zbQQRGAAEBFNp2jg=="
        },
        {
            "location": [
                61.149053,
                54.078186
            ],
            "name": "75К-400",
            "hint": "pmgBgEt9AoDaagAAFwAAAAAAAACoLwAAAAAAAHJzAACI8QIAVwAAAH0PpQPqKjkDvMoMA_CrQQRGAAEBFNp2jg=="
        }
    ],
    "routes": [
        {
            "distance": 0,
            "duration": 0,
            "legs": [
                {
                    "distance": 0,
                    "duration": 0,
                    "summary": "",
                    "steps": []
                }
            ],
            "geometry": "ucaiIqdftJ??"
        }
    ],
    "code": "Ok"
}`

**Comment by danpat** [comment]
@bgani I'm sorry, we're going to need a lot more information if we're to figure out what's going wrong.

Two things spring to mind:
  1. What dataset/OSM file have you loaded?  We will snap to the nearest coordinates even if they're quite a long way away.
  2. The URL parameters need to be in `longitude,latitude` order - you've got a latitude of 71.42 degrees, that's pretty up there, are you sure that's correct?

**Comment by TheMarex** [comment]
Closing here in favor of stackoverflow thread.

**Comment by daniel-j-h** [comment]
For the record, it is this one:
http://stackoverflow.com/questions/38895717/getting-wrong-response-from-osrm
