### ISSUE TITLE
Best setup for extracing planet with lots of RAM?

### ISSUE THREAD

**Issue by hubsw** [Project-OSRM/osrm-backend#2767]
I'm trying to extract the planet file on a server with 384 GB RAM. The server is a physical server and no other non-OS processes are being executed during the extraction process. I have Fedora 24, the latest OSRM, and Lua 5.1. However, I am a little bit puzzled what is the best setup for this case. I have tried the following so far:

a) Using stxxl with "disk=empty,250000,memory" failed after graph compression (printing node+edge compression ratio) with a bad_alloc exception.

b) Using stxxl with "disk=.....,250000,syscall" makes the extraction process *very* slow, although I use a 1 TB SSD, which never showed any real performance issue so far. After the initial parsing phase, the cpu usage is often neglectable, around 5-10% (often not listed in top -c at all). 

In both cases I had used swap file of approx. 30GB. (In case b, the swap space is never actually used). 

Do you have any ideas which setup (stxxl+swap) fits best in my case? From the numbers I saw in other issues, I would think that my amount of RAM should be sufficient for the whole extraction process to finish within 2-6 hours.

Thanks for your help!

Btw:  I use Lua 5.1, since Lua 5.3 apparently has a huge memory leak: With Lua5.3 I was out of RAM even during the initial parsing stage with 250GB stxxl on disk.

**Comment by danpat** [comment]
CPU usage should be continuously high during `osrm-extract`.  Can you try attaching to the `osrm-extract` process with GDB and running `thread apply all bt` to see what it's doing?  Dump the output here.

You should have enough resources available - the OSRM demo server has 120GB of RAM and re-processes the whole planet (both `osrm-extract` and `osrm-contract`) in about 6-7 hours.  It has a similar `.stxxl` configuration to your `syscall` setup, and has SSD disks (non-SSD drives *are* very slow).

**Comment by hubsw** [comment]
Thanks for your comment! Just now, I succeeded with the following setup:

stxxl: disk=empty,350000,memory
swap: 100 GB on an external HD (not even an SSD)

The whole process (extraction/contraction) took around 3.5 hours with 32 threads. According to my logs, the swap file hasn't been used at all. Although a little bit strange, but I guess my case can be closed. I will not run osrm-extract too soon again, given my experiences in the last two days with lua memory leaks and trial-and-error osrm-extract runs (which unfortunately always just failed after several hours). :-(

I know it is hard to predict the actual memory usage for any input pbf (particular with frequent changes to the osrm code base), but maybe an initial sanity check about whether the given setup allows to parse the input planet file would prevent other users from my planet-trial/error experience.

Anyway, thanks a lot for your impressive work on OSRM!

**Comment by MoKob** [comment]
Well. Since the profile has a big influence on the memory consumption, it is pretty much impossible to predict.

I guess we all agree that having easier ways to describe the necessity of resources or even a very early failure state would be preferable.
