### ISSUE TITLE
Strange route being calculated

### ISSUE THREAD

**Issue by naoliv** [Project-OSRM/osrm-backend#2771]
We are noticing a strange route calculated by OSRM:

![](https://cloud.githubusercontent.com/assets/982338/17685456/5c4145a6-633a-11e6-99c6-0a17a45f36ef.png)

Other routers can calculate the proper route, like this:
![](https://cloud.githubusercontent.com/assets/982338/17685459/683ce3c4-633a-11e6-907e-e392ed4d5c62.png)

It seems that OSRM cant use this link somehow https://www.openstreetmap.org/way/111047027 but we can't find anything wrong in the data.

[OSRM route is here](http://map.project-osrm.org/?z=14&center=-23.766454%2C-46.587353&loc=-23.744772%2C-46.597867&loc=-23.757067%2C-46.567183&hl=en&alt=0)

**Comment by danpat** [comment]
@naoliv OSRM defaults to not routing on toll ways, and way 111047027 has `toll=yes` .  The Lua profile is configurable here: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L152-L153

The demo server at `router.project-osrm.org` uses the default car profile, so routes you get from there will not traverse `toll=yes` roads.

**Comment by naoliv** [comment]
Didn't know about this, thanks!

**Comment by daniel-j-h** [comment]
Follow up here: we reverted not routing over `toll=yes` by default in https://github.com/Project-OSRM/osrm-backend/pull/2782 since some major roads are toll-only roads. For a couple of weeks we had the behavior in master and on the demo server, sorry.
