### ISSUE TITLE
Complex Turn Lane Cases

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2774]
Capturing from notes from @MoKob:

> We are handling turn lane cases only that can be assigned more or less directly. We are missing cases that cannot be handled as one-to-one assignment (e.g. left-arrow to left-turn).

/cc @MoKob

**Comment by MoKob** [comment]
This is more or less a duplicate of whats in https://github.com/Project-OSRM/osrm-backend/issues/2553
