### ISSUE TITLE
Not all turn lane cases are marked right to the intersection

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2776]
Capturing from notes from @MoKob:

> Often, due to traffic lights or possibly segregated intersections, the markings are prior to the turn itself. Right now we discover these lanes simply by walking back to the most straight turn coming in. This method is a potentially very bad heuristic and needs improvement.

**Comment by MoKob** [comment]
Duplicate of https://github.com/Project-OSRM/osrm-backend/issues/2553
