### ISSUE TITLE
Most lane merges can be ignored

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2777]
Capturing from notes from @MoKob:

> Most lane merges can be ignored (since the instruction is not necessary, two lanes continue as one lane -> obviously we need to merge). It can happen at intersections as well, though, which requires us to handle the merge tag in these cases.

**Comment by MoKob** [comment]
Also a duplicate of https://github.com/Project-OSRM/osrm-backend/issues/2553
