### ISSUE TITLE
Pass options to profiles

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2781]
Currently all profiles are self-contained: All options are specified in the file itself. The only mechanism to pass options (say set toll-roads to true/false) is by modifying that file.

This becomes problematic if we want to test the behavior of a profile with changed options. For example it is not possible to test the behavior of `car.lua` if toll roads are disabled, if the default is to enable them.

For this to work we would need a mechanism to pass external variables to the lua profile. There are two implementation options I see:
- Use environment variables and directly query them from the lua profile (`os.getenv("OSRM_IGNORE_TOLLS")`)
- Implement a custom options parser à la cmake: `osrm-extract --variable=IGNORE_TOLLS:true`

**Comment by danpat** [comment]
> Use environment variables and directly query them from the lua profile 

👍  on this approach.  It's simple to implement.

**Comment by TheMarex** [comment]
The immediate need for this in the cucumber tests was removed via https://github.com/Project-OSRM/osrm-backend/pull/2954

**Comment by daniel-j-h** [comment]
Can we close this, then?

We probably should open another ticket re. Cucumber tests default profile options toggled.
