### ISSUE TITLE
osrm-extract crash on Windows x64

### ISSUE THREAD

**Issue by tibobliss** [Project-OSRM/osrm-backend#2783]
Trying to extract the map for a first test with OSRM using the release binary. The map is a Metro Extract from OSM (Montreal, Canada, XML format).

`osrm-extract montreal_canada.osm`
returns the following error:
`[STXXL-MSG] CreateFile() error on path=C:\temp\stxxl mode=28, retrying without DIRECT mode.`
`[STXXL-MSG] Error allocating disk 'C:\temp\stxxl', space: 10000 MiB, I/O implementation: wincall queue=0 devid=0`
and osrm-extract crashes.

I've checked the PC's swap file size and it is 26 Gb, I'm guessing that the issue does not arise from there. Any idea on what could be causing this problem?

Windows 10, 64-bits, 16 Gb RAM

Edit: Formatting

**Comment by g2server** [comment]
Check to see if the C:\temp folder exists. I had the same issue on Server2016, creating that folder resolved it.

**Comment by tibobliss** [comment]
That was my first thought, but the problem stays even if I create the directory.

**Comment by danpat** [comment]
The error is coming from the STXXL library that we use.  It needs to create some temporary files.

You can check the STXXL docs here:

http://stxxl.sourceforge.net/tags/master/install_config.html

You should be able to create a `.stxxl.txt` file that specifies where STXXL creates the temporary files, see the link above for how to create the `.txt` file and where to put it.

Read the docs above and try the various options.  This looks like either a bug with STXXL, or a problem with your system, OSRM doesn't do much but *use* STXXL, so if it's failing, the error is somewhat outside our control.

**Comment by tibobliss** [comment]
The `.stxxl.txt` was already present in the binaries directory. Here is its content:
`disk=c:\temp\stxxl,10000,wincall `
I'll try some of the options and keep you posted.

**Comment by tibobliss** [comment]
Found a solution in the STXXL documentation, thanks @danpat!

`disk=c:\temp\stxxl.tmp, 10000, **memory**`

The `memory` mode keeps the files in the RAM instead of writing them to disk. That seems to circumvent the problem with STXXL creating temp files on the disk.

**Comment by danpat** [comment]
@tibobliss The `memory` options does everything in RAM.  It's a good option to use if you have enough.  If you're processing the OSM planet, you will need about 300GB :-P

**Comment by tibobliss** [comment]
Yeah, right now the Montreal area seems manageable. Seems like my 16GB RAM is finally proving useful!

**Comment by danpat** [comment]
@tibobliss A couple of other notes before I close this ticket:

  - use the `.pbf` extract format when you can.  `osrm-contract` works quite a bit faster with it compared to the XML format.
  - I assume you had 10GB free disk space for your initial test?  (that's how much STXXL was trying to pre-allocate)

Other than that, I don't think there's anything actionable for us here, closing.

**Comment by tibobliss** [comment]
Duly noted. And yes, there were 311GB free on the drive, no issue there. Thanks for your help!

**Comment by dstowe** [comment]
I know this is late, but I had to change back slashes to forward in .stxxl file :)

Here is what I'm using:
disk=c:/temp/stxxl,200000,wincall
