### ISSUE TITLE
osrm-extract triggers the address sanitizer

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2788]
There is an access violation during the RTree generation. The error can be found here:

https://travis-ci.org/Project-OSRM/osrm-backend/jobs/153525915#L1824-L1882

I'm not sure if this is a false positive or points to bad code.

**Comment by oxidase** [comment]
Just created an issue https://github.com/google/sanitizers/issues/715

As a workaround the alignment could be completely removed or increased to 1024  in the failed test.

**Comment by TheMarex** [comment]
Just updating from the linked issue, this is expected to go away with gcc >6.1.1. Thanks for looking into this @oxidase!

**Comment by oxidase** [comment]
@TheMarex  committed to the branch fix for  some "memory leaks" in TBB, that  is correct behavior to prevent deinitialization fiasco for lazy-initialized `tbb::task_scheduler_init` in rtree.

Also there is another intended memory leak in osrm-datastore that requires change at https://github.com/Project-OSRM/osrm-backend/blob/master/include/storage/shared_memory.hpp#L70

**Comment by TheMarex** [comment]
Sadly GCC 6.1 and `-fsanitizer` have their problems in the [ubuntu packages](http://stackoverflow.com/questions/37603238/fsanitize-not-using-gold-linker-in-gcc-6-1). For whatever reason that breaks the compilation of the example code.
