### ISSUE TITLE
Wrong snapping on road

### ISSUE THREAD

**Issue by zummach** [Project-OSRM/osrm-backend#2789]
Given the coordinate (lat: -9.617389, lng:-41.801694), OSRM snaps the location to a different place without roads (http://map.project-osrm.org/?z=13&center=-9.401821%2C-41.770105&loc=-9.401821%2C-41.770105&hl=en&alt=0)

Entering the same coordinate on OSM (https://www.openstreetmap.org/search?query=-9.617389%2C%20-41.801694#map=14/-9.6174/-41.8017). The coordinate is nearest a street.

**Comment by danpat** [comment]
@zummach This looks like it might be a geocoding problem.  If I enter the coordinate explicitly:

http://map.project-osrm.org/?z=12&center=-9.489530%2C-41.678524&loc=-9.617389%2C-41.801694&loc=-9.528977%2C-41.813278&hl=en&alt=0

When you enter " -9.617389,-41.801694", the frontend is reverse-geocoding that to "Bem-Bom, Casa Nova, Microrregião de Juazeiro, Região Administrativa Integrada de Desenvolvimento do Polo Petrolina e Juazeiro, Mesorregião do Vale São-Franciscano da Bahia, Bahia, Northeast Region, Brazil", 

We use Nominatim for geocoding, and it looks like the coordinate returned for that is the centroid of a polygon:

https://nominatim.openstreetmap.org/search.php?q=+-9.617389%2C-41.801694&polygon=1&viewbox=

which is the coordinate you're seeing used for snapping.  I agree, this seems wrong, but it's not a problem with `osrm-backend`, but rather the web frontend and how we're handling geocoding behaviour.

Please open a ticket in `osrm-frontend` describing this problem.
