### ISSUE TITLE
Masonize build-system

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2790]
Currently we build `osrm-backend` against dependencies from stock Ubuntu trusty + the toolchain PPA. This results in non-portable binaries since we don't link statically against most system libraries.

Hence to enable binaries for `node-osrm` and `node-pre-gyp` it uses mason to download stable binary packages build with clang. This means we maintain an additional build-system for `osrm-backend` in `node-osrm`. This opens multiple ways in which build regressions can be introduced in `node-osrm` without us noticing.

To migrate this we should masonize `osrm-backend`. There are some restrictions around this:

1. `osrm-backend` should not depend on mason. Building with mason should be a build option.
2. Mason should be integrated into cmake. Enabling mason should be as easy as `cmake -DENABLE_MASON=ON`. This makes sure that established conventions for building a cmake-based project are maintained.
3. We need the option to build OSRM in a non-mason environment on travis: 32bit support and shared library support are inherently incompatible with mason binaries (x86_64 only, statically linked)

/cc @springmeyer @daniel-j-h @kkaefer

**Comment by springmeyer** [comment]
👍  this is great thinking @TheMarex. I think the steps you've sketched out are solid. I'll further share how I see this working:

 - `-DENABLE_MASON=OFF` (the default) will keep the current build system working as-is without any changes
  - external dependencies will be found with FindPackage at the normal file system search paths.
 - `-DENABLE_MASON=ON` will be opt-in and will trigger downloading and building against pure mason-based libraries
  - This functionality will be very simple to add into the osrm-backend `CMakeLists.txt` based on the cmake support now in mason core thanks to @kkaefer. We can learn from the [mapbox-gl-native usage](https://github.com/mapbox/mapbox-gl-native/blob/d2246b22e00ef1b189b3e2f279f6b1af056ef995/CMakeLists.txt#L4-L32). 
  - This will work on both Linux and OS X, creating portable binaries for each against the same exact dependency versions
  - Linux: the resulting osrm-backend binaries will be portable to any other linux system assuming the minimum documented GLIBCXX and GLIBC.
  - OS X: the result osrm-backend binaries will be portable to all OS X systems >= 10.8 (this is controlled by [this line in mason](https://github.com/mapbox/mason/blob/2d47ca993e05787b89f363c7559df5c83f8e0e8b/mason.sh#L56))
  - These linked library dependencies from mason will be static archives and statically linked by osrm tools (to make portability of the linked osrm tools straightforward) with the exception of libtbb (which, last I checked, must be distributed as a shared library and therefore will require custom relative @rpath handling)

**Comment by springmeyer** [comment]
Done with #3119. Followups:

  - https://github.com/Project-OSRM/node-osrm/pull/268
  - https://github.com/Project-OSRM/osrm-backend/pull/2687
  - https://github.com/Project-OSRM/osrm-backend/issues/3183
