### ISSUE TITLE
Route is found in OpenStreetMap but not in the API 

### ISSUE THREAD

**Issue by ambodi** [Project-OSRM/osrm-backend#2792]
I have this example from a route in Sweden that shows up:

https://www.openstreetmap.org/directions?engine=osrm_car&route=59.3366%2C18.0506%3B59.3084%2C18.0663#map=13/59.3212/18.0644

Now if I wanna use the API version < 5, I am getting this:

```
{ status: 200,
  hint_data:
   { locations:
      [ '_lsAABIqOwMaYgAANAAAABoAAAAAAAAALQAAAHLWAADkHqkEargAAJZniQNobhMBAAABAQ',
        '_lsAABIqOwMaYgAANAAAABoAAAAAAAAALQAAAHLWAADkHqkEargAAJZniQNobhMBAAABAQ' ],
     checksum: 2165676233 },
  route_name: [ 'Dalagatan', 'Dalagatan' ],
  found_alternative: false,
  route_summary:
   { total_distance: 0,
     total_time: 0,
     end_point: 'Dalagatan',
     start_point: 'Dalagatan' },
  route_instructions:
   [ [ '10', 'Dalagatan', 0, 0, 3, '0m', 'N', 0, 1, 'N', 0 ],
     [ '15', '', 0, 0, 0, '0m', 'N', 0, 1, 'N', 0 ] ],
  via_points: [ [ 59.336598, 18.050664 ], [ 59.336598, 18.050664 ] ],
  via_indices: [ 0, 0 ],
  status_message: 'Found route between points',
  route_geometry: 'kxrdpBoevla@' }
```

If I use the new API, I am getting this:

http://router.project-osrm.org/route/v1/driving/59.3365763,18.0505745;59.3083918,18.0662992

```    
{"code":"Ok","routes":[{"legs":[{"steps":[],"summary":"","duration":0,"distance":0}],"geometry":"wlzrB}bz_J??","duration":0,"distance":0}],"waypoints":[{"hint":"aZPAg3tJ7oYAAAAAAAAAABMAAADKAAAAcxEAAJr7GgN8kpkFFrgAAHoecgOUpCEBgGeJAw5uEwEBAAEBk4rgGg==","name":"","location":[57.810554,18.982036]},{"hint":"aZPAg3tJ7oYAAAAAAAAAABMAAADKAAAAcxEAAJr7GgN8kpkFFrgAAHoecgOUpCEBZ_mIA3urEwEBAAEBk4rgGg==","name":"","location":[57.810554,18.982036]}]}
```

What am I doing wrong here? I get no time no duration at all and no info on the legs neither.

I also tried to setup my own OSRM and downloading the Sweden's data there ```http://osrm.osrm.3e0a1363.svc.dockerapp.io:5000/route/v1/driving``` but still no luck!

**Comment by systemed** [comment]
OSRM v5 is lon/lat order, not lat/lon order. So: http://router.project-osrm.org/route/v1/driving/18.0505745,59.3365763;18.0662992,59.3083918

See https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

**Comment by MoKob** [comment]
This is indeed a lat/lon switch problem. If you switch the order of your coordinate input, you will get a correct result again.

**Comment by ambodi** [comment]
@systemed @MoKob Yeah guys, I was clumsy! Thanks for the help 👍
