### ISSUE TITLE
Don't add restrictions when we don't understand the tag

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2802]
In https://github.com/Project-OSRM/osrm-backend/issues/2801, @codain found a relation with `type=restriction` and `restriction=yield`, which is not a documented type.

However, our restriction parser treated this like a `restriction=no_turn`, and prevented turns from a slip-road onto a major highway.

The tagging is bad, but we should also not fail so badly when we hit a tag like this.

Currently, the restriction parser only looks for `type=restriction`, and then tests if it's `restriction=only*`.  If it's any other `restriction=*` value, we treat it like a `no_turn` and remove edges from the graph.

We should, at a minimum, check that the restriction is one of the values on the OSM wiki http://wiki.openstreetmap.org/wiki/Relation:restriction:

> If the first word is "no_", then no routing is possible from the "from" to the "to" member. If it is "only_", then you know that the only routing originating from the "from" member leads to the "to" member. 

We aren't checking for `no_*` at the moment, we should probably change that.

**Comment by Codain** [comment]
Proposal:

It looks like the code is in the following function of the file `src/extractor/restriction_parser.cpp`:

```
boost::optional<InputRestrictionContainer>
RestrictionParser::TryParse(const osmium::Relation &relation) const
```

I think that changing from:

```
if (value.find("only_") == 0)
{
            is_only_restriction = true;
}
```

To:

```
if (value.find("only_") == 0)
{
            is_only_restriction = true;
}
else if (value.find("no_") == 0) // See the nota reguarding this check and whether to add it or not
{
            is_only_restriction = false;
}
else
{
            // Restriction not supported, ignore it
            return {};
}
```

Should make the trick (but I don't have a development environment to check).

Nota: The second check may increase an already existing side effect. Today in some circumstances (`restriction=no_*` lead to `false` and then `restriction:<*>=only_*` leads to `true`) the last restriction value of type `only_` will override the previous ones regarding the variable `is_only_restriction` (which will be set as `true`). With this patch it will be even more visible and the last restriction will always override `is_only_restriction`. To solve this already existing case will require some additional steps/a rewriting of the whole algorithm. But at a first step and to close this issue **ignoring the second if and adding only the else statement** will solve the issue without changing the existing behavior.

Hope this helps...
