### ISSUE TITLE
Build breaks on current CentOS

### ISSUE THREAD

**Issue by rkcpi** [Project-OSRM/osrm-backend#2804]
Currently the build fails on CentOS (and seemingly Ubuntu, though I haven't confirmed that myself), because CentOS comes with gcc 4.8.5 which doesn't support C++14.

The error encountered is the following:
```
CMake Error at cmake/check_luabind.cmake:38 (message):
Luabind does not work with Lua 5.1 at
/usr/lib/x86_64-linux-gnu/liblua5.1.so, no working Luabind found
```

Also see the discussion regarding this in 71d64e8cd9892beb1220511323b5459aa9809645.

**Comment by james-gould** [comment]
Have you tried any fixes in #1196? This may be of help: https://github.com/Project-OSRM/osrm-backend/issues/1196#issuecomment-97706794

**Comment by rkcpi** [comment]
@james-gould the problem is that there's no c++14 support in CentOS's gcc. luabind worked fine all along, the error message does not tell us the real problem

i already opened a pull request #2805 that fixes this issue

**Comment by pongo710** [comment]
I think this issue can be closed. The referenced pull request was merged.
