### ISSUE TITLE
turn restrictions not working on version 5.x

### ISSUE THREAD

**Issue by caoyang1024** [Project-OSRM/osrm-backend#2806]
I have an osrm instance running version 4.8.1, the turn restrictions works fine. But using the same .osm data running on version 5.3.2. It seems the turn restrictions not working as expected.

Google map
![screenshot 2016-08-24 11 20 34](https://cloud.githubusercontent.com/assets/1715357/17917317/dd6c47e8-69ed-11e6-89c1-26f1003f59f1.png)

working on 4.8.1
![screenshot 2016-08-24 11 22 10](https://cloud.githubusercontent.com/assets/1715357/17917321/e771a7ce-69ed-11e6-84a5-bb7b5a154e9a.png)

not working on 5.3.2
![screenshot 2016-08-24 11 25 11](https://cloud.githubusercontent.com/assets/1715357/17917324/e9a3e1c4-69ed-11e6-9e42-b545b55650bd.png)

osm files contains restriction
![screenshot 2016-08-24 12 17 31](https://cloud.githubusercontent.com/assets/1715357/17918123/db5da396-69f4-11e6-8575-aaa2cea22c22.png)

**Comment by danpat** [comment]
@caoyang1024 Can you post the `.osm` file you're using?

I can't really see from your screenshot, but the restriction relation requires a `via` tag with the intersection node ID, as well as the `from` and `to` entries.  Your screenshot does not show the `via`, do you have one?

http://wiki.openstreetmap.org/wiki/Relation:restriction#Members

**Comment by caoyang1024** [comment]
@danpat sorry that i can't post the .osm file here.
i checked with the data, it has the via node infor
![screenshot 2016-08-24 14 45 41](https://cloud.githubusercontent.com/assets/1715357/17920870/89f8464a-6a09-11e6-9925-ce2f99d19007.png)
mation.

**Comment by danpat** [comment]
@caoyang1024 Hmm.  It is difficult to debug this without the data.

Does the Lua profile you're using have `properties.use_turn_restrictions = true` ?

If you could make a tiny extract from your map, even of just the few streets shown in your last screenshot, that would be very helpful.

**Comment by caoyang1024** [comment]
@danpat 

yes, properties.use_turn_restrictions = true.

here is the sample osm file. thank you.
[amk.osm.zip](https://github.com/Project-OSRM/osrm-backend/files/438498/amk.osm.zip)

**Comment by danpat** [comment]
@caoyang1024 Your extract was missing the `from`, `via` and `to` roles on the relation.  I added them with JOSM and saved it, and here's what I get:

![screen shot 2016-08-25 at 9 25 12 pm](https://cloud.githubusercontent.com/assets/1892250/17994075/8280bb8e-6b0a-11e6-8fa5-926bb787e94a.png)

I'm using OSRM `master` (pre-5.4.0), with the commands:

```
osrm-extract -p profiles/car.lua amk.osm
osrm-contract amk.osrm
osrm-routed amk.osrm
```

Other than the missing roles, the only thing that stood out to me was the Node/Way ID values - they're negative.  OSRM assumes that these values will be positive, and I do not know if it behaves well if negative IDs are supplied.  It seemed to work on my small sample with small negative values, but the code assumes positive in many locations, so there might be some funny business there.

Here's the updated data file:
```
<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' upload='true' generator='JOSM'>
  <node id='-23' action='modify' visible='true' lat='1.37017758856' lon='103.84634800646' />
  <node id='-25' action='modify' visible='true' lat='1.37007802656' lon='103.84548314446' />
  <node id='-27' action='modify' visible='true' lat='1.36942146956' lon='103.84545690646' />
  <node id='-29' action='modify' visible='true' lat='1.37169909255' lon='103.84538169246' />
  <node id='-31' action='modify' visible='true' lat='1.37053544956' lon='103.84550142346' />
  <way id='-33' visible='true'>
    <nd ref='-23' />
    <nd ref='-25' />
    <tag k='fea_id' v='58938.00000000000' />
    <tag k='highway' v='motorway' />
    <tag k='maxspeed' v='15.00000000000' />
    <tag k='name' v='ANG MO KIO AVENUE 6' />
    <tag k='objectid' v='58938' />
    <tag k='oneway' v='no' />
    <tag k='source' v='SG Road Data' />
  </way>
  <way id='-35' visible='true'>
    <nd ref='-25' />
    <nd ref='-27' />
    <tag k='fea_id' v='58935.00000000000' />
    <tag k='highway' v='motorway' />
    <tag k='maxspeed' v='40.00000000000' />
    <tag k='name' v='ANG MO KIO AVENUE 6' />
    <tag k='objectid' v='58935' />
    <tag k='oneway' v='no' />
    <tag k='source' v='SG Road Data' />
  </way>
  <way id='-37' visible='true'>
    <nd ref='-29' />
    <nd ref='-31' />
    <nd ref='-25' />
    <tag k='fea_id' v='14372.00000000000' />
    <tag k='highway' v='motorway' />
    <tag k='maxspeed' v='40.00000000000' />
    <tag k='name' v='ANG MO KIO AVENUE 6' />
    <tag k='objectid' v='14372' />
    <tag k='oneway' v='no' />
    <tag k='source' v='SG Road Data' />
  </way>
  <relation id='-39' action='modify' visible='true'>
    <member type='way' ref='-35' role='from' />
    <member type='node' ref='-25' role='via' />
    <member type='way' ref='-33' role='to' />
    <tag k='restriction' v='no_right_turn' />
    <tag k='type' v='restriction' />
  </relation>
  <relation id='-41' action='modify' visible='true'>
    <member type='way' ref='-33' role='from' />
    <member type='node' ref='-25' role='via' />
    <member type='way' ref='-37' role='to' />
    <tag k='restriction' v='no_right_turn' />
    <tag k='type' v='restriction' />
  </relation>
</osm>
```

**Comment by danpat** [comment]
Just so it's clear, this is what you sent through:

```
  <relation id='-353266' action='modify' visible='true'>
    <member type='way' ref='-353248' role='' />
    <member type='node' ref='-353252' role='' />
    <member type='way' ref='-353250' role='' />
    <tag k='restriction' v='no_right_turn' />
    <tag k='type' v='restriction' />
  </relation>
```

The `role` field is blank, and OSRM requires `from`, `via` and `to` in order to recognize the restriction.

**Comment by caoyang1024** [comment]
@danpat 
in fact, i checked the role, it's correct in the original file. 
i'm currently validate the osm file, found some error and warning in the file, trying to resolve them and will have a try later. 
thanks a lot !

**Comment by MoKob** [comment]
@caoyang1024 any update on that validation? OSRM cannot handle turn-restrictions with a via-way. Apart from that issue, we can't see any violations on our side.

Closing here. Feel free to re-open if the actual problem should still persist for a valid via-node restrictions.

**Comment by caoyang1024** [comment]
@MoKob yes, it's fixed on our side after solving all validation warnings and errors. thanks a lot.
