### ISSUE TITLE
Catch osrm::util::exception with libosrm

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#2813]
With libosrm installed from v5.1.0, I don't see how I could catch an osrm::util::exception in my client code as I don't find any relevant header to include from `/usr/local/include/*`.

Of course I can still catch it as a `std::exception` but this is ugly and the use case seems fairly common. This happens any time a user forgets to run `osrm-datastore` prior to running the client code.

Maybe I'm missing something here?

**Comment by TheMarex** [comment]
You are right, this is a bug, we should expose the `osrm::exception`.

**Comment by daniel-j-h** [comment]
Argh sorry for never ticketing this, I noticed this already back when I played around with the C wrapper https://github.com/daniel-j-h/libosrmc/blob/03ed2189f682726edfb1845d4533fb626f25a92d/libosrmc/osrmc.cc#L43.

https://github.com/Project-OSRM/osrm-backend/pull/2826 resolves this.

@jcoupey you should be able to cherry-pick it if you already want to develop your code with this change.

**Comment by jcoupey** [comment]
Thanks for the fix!

I'm currently still on 5.1 so I might indeed cherry-pick for my own install. Nevertheless, I'll have to stick with a `std::exception` for [the client code](https://github.com/VROOM-Project/vroom/blob/develop/src/main.cpp#L198-L205) to keep support for out-of-the-box OSRM installs prior to 5.4.
