### ISSUE TITLE
RHEL 6.7 Installation

### ISSUE THREAD

**Issue by capitalfact** [Project-OSRM/osrm-backend#2815]
I am trying to install osrm-backend-master on Red Hat Enterprise Linux Server release 6.7 (Santiago).

I am using the lastest master version.

/# cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=1 -
DSTXXL_LIBRARY=/opt/osrm_infrastructure/stxx/lib/libstxxl.a -DSTXXL_INCLUDE_DIR=/opt/osrm_infrastructure/stxx/include
-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- LTO working
-- Using gcc specific binutils for LTO.
-- Setting linker optimizations
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
-- Found Intel TBB
-- TBB interface version: 4001
-- Looking for Luabind...
-- Found Luabind: /usr/local/lib/libluabind.so
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES)
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /usr/local/lib/liblua.a
-- Looking for STXXL...
-- Found STXXL: /opt/osrm_infrastructure/stxx/lib/libstxxl.a
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Activating OSRM internal tools
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/osrm-backend-master/build

I note the test failures "OpenMP_FLAG_DETECTED", but move on. Perhaps they are related, but I cannot resolve these issues.

/# make -j4 && make install
Scanning dependencies of target ENGINE
Scanning dependencies of target FingerPrintConfigure
Scanning dependencies of target EXTRACTOR
[  1%] Configuring revision fingerprint
[  1%] Built target FingerPrintConfigure
Scanning dependencies of target SERVER
[  1%] Building CXX object CMakeFiles/CONTRACTOR.dir/src/contractor/contractor.cpp.o
[  2%] Building CXX object CMakeFiles/EXTRACTOR.dir/src/extractor/restriction_map.cpp.o
[  4%] Building CXX object CMakeFiles/SERVER.dir/src/server/request_handler.cpp.o
[  5%] Building CXX object CMakeFiles/EXTRACTOR.dir/src/extractor/extractor_callbacks.cpp.o
[  7%] /tmp/osrm-backend-master/src/contractor/contractor.cpp:28:42: fatal error: tbb/concurrent_unordered_map.h: No such file or directory
compilation terminated.

/# yum install tbb
Package tbb-2.2-3.20090809.el6.x86_64 already installed and latest version

Can someone point me in the right direction here?

**Comment by danpat** [comment]
@capitalfact The latest version of TBB is 4.4, your distribution is very out of date.  It looks like the `tbb/concurrent_unordered_map.h` isn't included in your version.  Note the datestamp on your package version 2009-08-09.

**Comment by capitalfact** [comment]
Thanks @danpat, I updated TBB and now unfortunately face further problems.

In file included from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/detail/convert_to_lua.hpp:28:0,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/detail/call_member.hpp:30,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/wrapper_base.hpp:31,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/back_reference.hpp:27,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/class.hpp:93,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/luabind.hpp:28,
                 from /opt/osrm/osrm-backend-5.3.2/include/util/lua_util.hpp:11,
                 from /opt/osrm/osrm-backend-5.3.2/src/extractor/edge_based_graph_factory.cpp:7:
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/detail/policy.hpp: In member function ‘std::string luabind::default_converter<std::basic_string<char> >::from(lua_State*, int)’:
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/detail/policy.hpp:748:71: error: ‘lua_strlen’ was not declared in this scope
         return std::string(lua_tostring(L, index), lua_strlen(L, index));
                                                                       ^
In file included from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/detail/call_member.hpp:34:0,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/wrapper_base.hpp:31,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/back_reference.hpp:27,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/class.hpp:93,
                 from /opt/osrm_infrastructure/luabind-0.9.1/include/luabind/luabind.hpp:28,
                 from /opt/osrm/osrm-backend-5.3.2/include/util/lua_util.hpp:11,
                 from /opt/osrm/osrm-backend-5.3.2/src/extractor/edge_based_graph_factory.cpp:7:
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/object.hpp: In function ‘typename luabind::adl::enable_binary<bool, LHS, RHS>::type luabind::adl::operator==(const LHS&, const RHS&)’:
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/object.hpp:214:1: error: there are no arguments to ‘lua_equal’ that depend on a template parameter, so a declaration of ‘lua_equal’ must be available [-fpermissive]
 LUABIND_BINARY_OP_DEF(==, lua_equal)
 ^
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/object.hpp:214:1: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/object.hpp: In function ‘typename luabind::adl::enable_binary<bool, LHS, RHS>::type luabind::adl::operator<(const LHS&, const RHS&)’:
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/object.hpp:215:1: error: there are no arguments to ‘lua_lessthan’ that depend on a template parameter, so a declaration of ‘lua_lessthan’ must be available [-fpermissive]
 LUABIND_BINARY_OP_DEF(<, lua_lessthan)
 ^
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/object.hpp: In function ‘std::ostream& luabind::adl::operator<<(std::ostream&, const luabind::adl::object_interface<T>&)’:
/opt/osrm_infrastructure/luabind-0.9.1/include/luabind/object.hpp:228:53: error: there are no arguments to ‘lua_strlen’ that depend on a template parameter, so a declaration of ‘lua_strlen’ must be available [-fpermissive]
         std::size_t len = lua_strlen(interpreter, -1);

Appreciate the help, again I'm hoping for a push in the right direction.

**Comment by danpat** [comment]
@capitalfact what versions of Lua do you have installed?  The `luabind-0.9.1` library you're trying to link against is looking for Lua functions that aren't available.

**Comment by capitalfact** [comment]
Yep, I was pointing at the wrong Lua version. All installed now. Thanks.
