### ISSUE TITLE
Choose bewteen many profiles in one server

### ISSUE THREAD

**Issue by rollin-s** [Project-OSRM/osrm-backend#2816]
Hello !
I did actually setup my OSRM server, everything went fine.

But I have a question. I want, in my app, to choose between walking, driving, biking, etc.. Is that possible without having many servers ?
I didn't find anything about that online.. And I'm pretty concerned about that.

Thanks you.

**Comment by danpat** [comment]
@rollin-s no, you will need to run many servers to do this.

Old ticket for this which nobody has ever implemented: https://github.com/Project-OSRM/osrm-backend/issues/10

Support for this for `osrm-datastore`: https://github.com/Project-OSRM/osrm-backend/issues/1221

Closing this as a duplicate of #10.
