### ISSUE TITLE
Add traffic lights in the response of route calculation

### ISSUE THREAD

**Issue by antoinegiret** [Project-OSRM/osrm-backend#2819]
Hello,

Is it possible to add traffic lights in the response of the route calculation? For exemple in the RouteStep object? 

Thanks.

**Comment by danpat** [comment]
Traffic lights are considered when *calculating* the route.

@antoinegiret What's your use case for having light information in the route response itself?  If it would go anywhere, it would make sense to include it in the intersection classification data.

**Comment by daniel-j-h** [comment]
If you take a look at the [v5 API](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-route) there is a `annotations=true` flag adding OSM node ids onto the response. If you store all OSM node ids from your extract with `highway=traffic_signals` you can do the lookup quite easily.

Relevant: annotating a route response:
https://github.com/mapbox/route-annotator

**Comment by MoKob** [comment]
I don't see a use-case for this in OSRM since no route-planner I know of actually includes traffic lights, except for specific situations that where a traffic light might be hidden due to bad visibility.
It might be an item for the route-annotator. Not actionable here, though.
