### ISSUE TITLE
output the highway tag in instructions

### ISSUE THREAD

**Issue by rodo** [Project-OSRM/osrm-backend#282]
Hi,

This is a feature request, is it possible to add in route_instructions the highway tag ? It will be useful to show total time by highway type, in web services we can show something like "3 hours on road, and 4 hours on ferry".

Thanks

**Comment by daniel-j-h** [comment]
Here's an update as of v5.5:

don't encode arbitrary strings into the way's name, ref, pronunciation or other similar properties. Doing so will completely screw the internal guidance heuristics and will probably lead to unusable / far too noisy announcements (think: multiple continues after each other).

Here's the recommended way of doing this: use the `annotations=true` parameter:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

this adds OSM Node IDs to the route response. Then either do the lookup

    OSM Node ID -> arbitrary metadata

yourself or use https://github.com/mapbox/route-annotator which was built exactly for this use-case.

**Comment by MoKob** [comment]
related: #4203

**Comment by daniel-j-h** [comment]
5.9 has the road class in the intersection object:

https://github.com/Project-OSRM/osrm-backend/blob/5.9/docs/http.md#intersection-object

the default car profile sets `toll`, `ferry`, `restricted`, `motorway` road classes:

https://github.com/Project-OSRM/osrm-backend/blob/5.9/profiles/lib/handlers.lua#L280-L310

and you can change that in your own profile.

Closing this as resolved.
