### ISSUE TITLE
PBF error: invalid BlobHeader Size

### ISSUE THREAD

**Issue by rollin-s** [Project-OSRM/osrm-backend#2820]
Hello ! 

I am actually trying to run osrm-extract with a small map (300 Mo).
It worked once, but when I want to launch the command again, with a different profile, I have this error.
I tried to delete all the *.osrm file from the old command, nothing changed.

I also tried to add a .stxxl config file with more memory space, nothing changed.
And I also tried to add a 10 Go swap file, nothing changed.

I work on ubuntu 16.04, I have 8Gb RAM, and an IntelCore i7.

[info] Input file: lorraine.osm.pbf
[info] Profile: profile.lua
[info] Threads: 8
[STXXL-MSG] STXXL v1.4.1 (prerelease/Debug)
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 100000 MiB, I/O implementation: syscall queue=0 devid=0
terminate called after throwing an instance of 'osmium::pbf_error'
  what():  PBF error: invalid BlobHeader size (> max_blob_header_size)
Abandon (core dumped)

Thanks

**Comment by daniel-j-h** [comment]
This is `libosmium` complaining about your pbf file. Where did you get the extract from?

Could you try a small extract from Geofabrik such as [Monaco](http://download.geofabrik.de/europe/monaco.html) and make sure it works with that.

**Comment by rollin-s** [comment]
Oh. I feel stupid. I tried with monaco, it worked.. So I just had to download again the original file.. And it worked.

Sorry for the inconvenience, and thanks for you help.

**Comment by daniel-j-h** [comment]
Great it works now! Could have been a data corruption issue or maybe you accidentally downloaded a .osm xml file and renamed it to .pbf or something like that :) Happy routing!
