### ISSUE TITLE
Luabind does not work with Lua51 if LuaJit is getting detected

### ISSUE THREAD

**Issue by Pradyumna007** [Project-OSRM/osrm-backend#2831]
Hi ... I have downloaded osrm-backend from git ... Now when I am making cmake, it is throwing this error ... check this -->

$ /Maps work/osrm/osrm-backend/build$ sudo cmake .. $CMAKEOPTIONS -DBUILD_TOOLS=1
-- Building on a 64 bit system
CMake Warning at CMakeLists.txt:135 (message):
  GNU gold linker isn't available.

-- Configuring OSRM in release mode
-- LTO working
-- Disabling LTO on GCC < 4.9.0 since it is broken, see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57038
-- Setting linker optimizations
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
-- Found Intel TBB
-- TBB interface version: 6000
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so
-- Looking for LuaJIT 5.2
-- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Failed
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
-- Looking for LuaJIT 5.1
-- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Failed
CMake Error at cmake/check_luabind.cmake:38 (message):
  Luabind does not work with Lua 5.1 at LUA_LIBRARY-NOTFOUND, no working
  Luabind found
Call Stack (most recent call first):
  CMakeLists.txt:307 (include)

-- Configuring incomplete, errors occurred!

and i also tried using sudo cmake ..

Expecting reply

**Comment by danpat** [comment]
@Pradyumna007 Your version of `libluabind` needs to match the edition of `Lua` you have installed.

Generally, `libluabind` and `lua-5.1` work best together.  You seem to have `libluajit-5.1` installed.  Try removing that and installing vanilla Lua5.1.

**Comment by Pradyumna007** [comment]
Can you suggest me how to Install ?? i messed up the whole thing with installation ... I installed many times and uninstalled ... Now am not able to figure out where to start .??? 

I have libluabind
I dont know how to install lua-5.1 (I installed from luarocks)

where to go further ??

**Comment by daniel-j-h** [comment]
What's your Linux distribution? You should be able to install Lua through your package manager (and uninstall LuaJit using your package manager, too).

For Luabind there should also be a package in your package manager. In case that does not work, there is https://github.com/mapbox/luabind which you can install with

    mkdir build && cd build
    cmake .. -DCMAKE_BUILD_TYPE=Release
    make
    sudo make install

**Comment by Pradyumna007** [comment]
LuaJit is not installed anywhere

**Comment by daniel-j-h** [comment]
> -- Found Luabind: /usr/lib/libluabind.so

Uninstall the global luabind. Use the mapbox/luabind I posted above instead.

**Comment by Pradyumna007** [comment]
I deleted it ... and installed from the git location u gave ... but it is throwing the same error again

**Comment by pongo710** [comment]
Seems to be the same issue described here: https://github.com/Project-OSRM/osrm-backend/issues/2804

In the current master version this should be fixed. Which OSRM-Version are you using?

**Comment by Pradyumna007** [comment]
IDK which version ... but I downloaded the latest from git .... and I didnt get the #2804 is wat all abt

**Comment by daniel-j-h** [comment]
Good catch @pongo710, thanks.

@Pradyumna007 #2804 describes a fix for gcc 4.8 (which you are using). This fix is now in master. Please pull (or simply git clone again).

**Comment by Pradyumna007** [comment]
@daniel-j-h  You mean to say that new osrm-5.0.0.rc-1 version ?

I downloaded it and trying to set it up ... still it is popping error

**Comment by pongo710** [comment]
Try to use the current master version by downloading it with git:
`git clone https://github.com/Project-OSRM/osrm-backend.git`

**Comment by Pradyumna007** [comment]
@pongo710  From here only I downloaded osrm ....

**Comment by Pradyumna007** [comment]
@pongo710 @daniel-j-h I have tried installing by using 
https://travis-ci.org/Project-OSRM/osrm-backend/jobs/59878713  
and I got this error

-- Looking for Luabind...
-- Found Luabind: /usr/local/lib/libluabind.a  
-- Found Luabind: /usr/local/lib/libluabind.a
-- Could NOT find Lua52 (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR) 
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
CMake Error at /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Lua51 (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.2/Modules/FindLua51.cmake:94 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/check_luabind.cmake:26 (find_package)
  CMakeLists.txt:307 (include)


-- Configuring incomplete, errors occurred!
See also "/home/local/ANT/sprsn/Maps/osrm/Project-OSRM/osrm-backend/build/CMakeFiles/CMakeOutput.log".
See also "/home/local/ANT/sprsn/Maps/osrm/Project-OSRM/osrm-backend/build/CMakeFiles/CMakeError.log".

**Comment by daniel-j-h** [comment]
> Could NOT find Lua51

CMake couldn't detect Lua51, did you uninstall it by accident while uninstalling luajit?

**Comment by Pradyumna007** [comment]
I didnt not install luajit ... and and uninstall lua51

**Comment by daniel-j-h** [comment]
The link you posted is Travis, our CI that runs Ubuntu Trusty. Don't follow that.

Repeating what I said
- You need Lua 5.1, install it using your package manager
- If your luabind is too old, use https://github.com/mapbox/luabind

**Comment by Pradyumna007** [comment]
I am trying to install your luabind from first  ... first time it got installed ... now in those comments i found that ... so installed ... now wen am trying nt getting installed 


CMake Error at /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Lua51 (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.2/Modules/FindLua51.cmake:94 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:58 (find_package)

**Comment by Pradyumna007** [comment]
@daniel-j-h I have installed Lua 5.1 from sudo apt-get install liblua5.1 and installed luabind from the git you have suggested. .... As @pongo710  suggested I am installing osrm-backend from link above which i previously did .... in that way only am getting this error 


-- Found Luabind: /usr/local/lib/libluabind.a
-- Could NOT find Lua52 (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR) 
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
-- Found Lua51: /usr/lib/x86_64-linux-gnu/liblua5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.4") 
-- Looking for LuaJIT 5.1
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Failed
CMake Error at cmake/check_luabind.cmake:38 (message):
  Luabind does not work with Lua 5.1 at
  /usr/lib/x86_64-linux-gnu/liblua5.1.so, no working Luabind found
Call Stack (most recent call first):
  CMakeLists.txt:307 (include)


Now I am not understanding wt is the prob ?

**Comment by Pradyumna007** [comment]
Hey U can close the ticket ... It is working fine in ubuntu 14.04 ... thank you so much for the links and help
