### ISSUE TITLE
How to calculate state miles.

### ISSUE THREAD

**Issue by mdhanju** [Project-OSRM/osrm-backend#2836]
Any idea how to calculate state miles.
For example i travel from Los Angles to Dellas TX, need miles travelled in each state, CA, AZ, NM, and TX.

**Comment by danpat** [comment]
I would do the following:

  1.  Get a copy of some state outlines, e.g. http://eric.clst.org/Stuff/USGeoJSON
  2. Get the route line from OSRM
  3. Load these shapes into PostGIS or QGIS
  4. "clip" the route line using the state polygon using an intersect operation
  5. measure the length of the clipped line
  6. repeat for each state

Some useful links:

http://gis.stackexchange.com/questions/56874/how-to-split-line-layer-at-polygons-boundary-of-a-polygon-layer

http://postgis.net/docs/ST_Intersection.html

http://gis.stackexchange.com/questions/78835/how-to-clip-a-line-layer-based-on-polygons-with-qgis

This is not a feature OSRM would include, this is post-processing you would need to do on the route geometry.

**Comment by mdhanju** [comment]
Thank You... 
I will follow above steps.
