### ISSUE TITLE
Problem with .shp file.

### ISSUE THREAD

**Issue by gmiskos** [Project-OSRM/osrm-backend#2838]
I've imported greece-latest.osm.pbf in osrm planner that i've installed in an ubuntu 14.04 server. I tried some routing, but the results was wrong because, for example,  a highway has null maxspeed value.

Then i've downloaded greece-latest.shp.zip file and added the maxspeed value with qgis, but i can't converted back to osm.pfb to import again for testing.

Any ideas?

**Comment by daniel-j-h** [comment]
> I've imported greece-latest.osm.pbf in osrm planner that i've installed in an ubuntu 14.04 server. I tried some routing, but the results was wrong because, for example, a highway has null maxspeed value.

Please use
- http://www.openstreetmap.org/directions#map=19/59.78764/17.66230 and/or
- http://map.project-osrm.org

and show us the way / location where you see this happening.

There is also http://map.project-osrm.org/debug/ where you can see the derived speeds OSRM is using.

> Then i've downloaded greece-latest.shp.zip file and added the maxspeed value with qgis, but i can't converted back to osm.pfb to import again for testing.

This is a different issue and unrelated to OSRM.

**Comment by gmiskos** [comment]
Thank you very much!

**Comment by MoKob** [comment]
Seems like it is not actionable for us? Closing here.
