### ISSUE TITLE
Return country code in the results

### ISSUE THREAD

**Issue by theoctomore** [Project-OSRM/osrm-backend#2848]
Hi all,

First, I'd like to thank all the contributors of OSRM for this amazing tool.
I'm using the C++ API for research purposes to study some properties of the road network.
A thing that would be useful to me is to have in the results (for example of a nearest query) the country code of the node.

I'd be grateful if one of you could point me in the right direction regarding how I could implement this. in particular what files I should be looking into. I now understand the data structures used to do queries but I am not familiar at all with the rest of the code.

Thanks for your time!

**Comment by danpat** [comment]
@theoctomore I would:

  1.  Grab some shape files for country/state borders, like https://mapzen.com/data/borders/
  2. Construct an RTree (e.g. using boost RTree) with the bounding boxes for each country
  3. Do a collision test for your coordinate with the RTree
  4. Do a point-in-polygon tests for all the collisions to determine the correct country

We could *probably* implement this as part of the `nearest` plugin.  In theory, country borders exist inside the OSM files (https://help.openstreetmap.org/questions/13615/extract-all-country-borders), but it's probably easier to use a separate shapefile source.

**Comment by theoctomore** [comment]
Thanks for the reply. Indeed it seems hard to extract borders from the OSM.
My hope was in the country tags associated with the nodes in the OSM 
files. But I just realized that, although many nodes have it, it is not 
systematic.

**Comment by danpat** [comment]
@theoctomore there are nearly 3.5 billion nodes in OSM, it would not be very space efficient to tag each with a country code :-)

**Comment by daniel-j-h** [comment]
I'm closing this here as not actionable for us at the moment.

What you also can do is use the `annotations=true` flag in the [v5 API](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md) which will augment the route response with OSM node ids. You can then do route annotation based on OSM node ids, e.g. using:

https://github.com/mapbox/route-annotator

(or speaing more generally do arbitrary OSM node id -> x lookups)
