### ISSUE TITLE
not write _link

### ISSUE THREAD

**Issue by awikatchikaen** [Project-OSRM/osrm-backend#285]
It's weird to read, in middle of route instructions, lines like that :

"Continue                                                0.59km"

I watch the datas and it appears essentially on motorway. Those highway have no ref and name because they are junction between two. I think, the name of motorway junction should be used instead. And, in case of it not exists, use a text like "take the entrance / take the exit".

**Comment by 1ec5** [comment]
In [this example](http://www.openstreetmap.org/directions?engine=osrm_car&route=37.3547%2C-121.9119%3B37.3453%2C-121.9067#map=16/37.3500/-121.9085), OSRM says to continue down two unnamed roads. [MapQuest](http://www.openstreetmap.org/directions?engine=mapquest_car&route=37.3547%2C-121.9119%3B37.3453%2C-121.9067#map=16/37.3500/-121.9084) does a much better job, saying “Take the Taylor Street exit, EXIT 7,” then “Keep right to take the ramp toward Taylor Street West.” Highway exit information in OSM can be [very nuanced](http://wiki.openstreetmap.org/wiki/Exit_Info), but MapQuest shows that merely considering `ref` on `highway=motorway_junction` nodes and the name of the following way can greatly improve the turn directions.

**Comment by 1ec5** [comment]
I guess this would be covered by #228, actually.
