### ISSUE TITLE
Strange Roundabout Contraption

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2856]
http://www.openstreetmap.org/#map=19/47.23318/-1.56563 shows a roundabout that we currently can't handle correctly in osrm-backend.

This setup can break the creation of instructions.

**Comment by daniel-j-h** [comment]
Throughabout http://wiki.openstreetmap.org/wiki/Throughabout
https://en.wikipedia.org/wiki/Roundabout#Hamburger_roundabout

**Comment by MoKob** [comment]
The issue here was an invalid roundabout-tag on the bottom side of the roundabout.
As a result, our roundabout handling broke.

**Comment by MoKob** [comment]
Defective roundabout tagging is now detected in the roundabout handler.
