### ISSUE TITLE
Mark libosrm public interface threadsafe / const

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2861]
@jcoupey just noted the overly restrictive `libosrm` interface: our publicly facing functions are not marked `const` although internally we're logically const and threadsafe.

I _think_ it should be good enough sprinkling `const`-ness throughout the `OSRM` and `Engine` type.

We need to check this with our example code and more importantly with `node-osrm`.

**Comment by jcoupey** [comment]
@daniel-j-h You beat me at reporting speed. ;-)

Just to elaborate on how this is restricting in my use case: I wish to have an `OSRM` object as a class member (so I can re-use it at several occasions), but I can't use it in a `const` member function. More details if required at https://github.com/VROOM-Project/vroom/issues/34#issuecomment-244816177.

**Comment by daniel-j-h** [comment]
This was resolved in https://github.com/Project-OSRM/osrm-backend/pull/2862 and already merged into the v5 release, since it's only lifting restrictions from the interface. Closing as done.
