### ISSUE TITLE
How to translate old viaroute to route?

### ISSUE THREAD

**Issue by Christoph999** [Project-OSRM/osrm-backend#2863]
I am not very familiar with API programming. How can I make the following command work: `http://router.project-osrm.org/route/v1/driving/47.168,8.117,46.978,8.335`? I need the output as json. When using V4.0 we used `http://router.project-osrm.org/viaroute?loc=47.168,8.117&loc=46.978,8.335&instructions=true`. See also [here](http://stackoverflow.com/questions/39353149/how-to-use-the-new-route-command-from-osrm-v5-formerly-viaroute)

**Comment by danpat** [comment]
@Christoph999 The new URL format would be is:

```
http://router.project-osrm.org/route/v1/driving/8.117,47.168;8.33,46.978?steps=true
```

Note the semicolon to separate coordinates `;`, and that the coordinate is in `<longitude>,<latitude>` order, which is the opposite of the 4.x API.

The JSON response body has changed a lot, so if you have code that parses the old 4.x response, you will need to update it.

The full details on the URL format and JSON structure of the response are in the HTTP API docs here: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-route

**Comment by Christoph999** [comment]
Thank you. Could you add the example to the docs? It might be helpful for others as well.

One additional question: Is there any reason why the server is down quite some time? It feels like that happens in about 50% of the time.

Thank you very much for your support!

**Comment by daniel-j-h** [comment]
There is now an example at:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-route

The demo server runs directly from master and the latest OSM planet. It's not using stable releases but more like "nightly builds". We do this to rather let the demo server crash often instead of us releasing a stable release with issues in it.

**Comment by Christoph999** [comment]
Thanks...

**Comment by Christoph999** [comment]
At the moment it is almost impossible to work with the API as there is no result returned in most of the time. As result my code crashes (timeout) or takes forever. What would you recommend? (I am working on a windows 8 machine)

**Comment by daniel-j-h** [comment]
Either wait a bit until the hiccups are over or see if you can spin up a Linux VM running your own test server. Running it e.g. on france or monaco or any other small dataset should be easy and fast.

- https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM
- https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

**Comment by Christoph999** [comment]
Ok... When do you think that a windows server will be running stable?

**Comment by danpat** [comment]
@Christoph999 There is no Windows server, there never has been.  Some people run OSRM themselves on Windows, but the demo server at `router.project-osrm.org` runs Linux, and that is the only platform we regularly test against.

The demo server is there as just that - a demo.  If you need a more reliable service, there are numerous paid providers that have uptime and stability guarantees.  You are always welcome to run your own server using the instructions @daniel-j-h linked to in the previous ticket.

**Comment by Christoph999** [comment]
Ok, now it is clear to me! Thank you very much for your time...

**Comment by Christoph999** [comment]
Sorry, I just faced another broken window in our code: How can I retrieve the former `route$route_geometry`? Do I need `route$geometry` from `http://router.project-osrm.org/route/v1/driving/47,8;48,9?overview=full"`? Thanks again...

**Comment by daniel-j-h** [comment]
Please read the docs at:

- https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-route

If you want the simplified overview geometry you can access it in the `routes[].geometry` field. It's polyline encoded by default, but you can change that to GeoJSON if you want to, as in:

    http 'https://router.project-osrm.org/route/v1/driving/27.1728,45.7030;27.18,45.69?geometries=geojson' | jq '.routes[0].geometry'

Note:
- adding `steps=true` gives you all steps and their geometry
- adding `overview=full` no longer simplifies the overview geometry

**Comment by neilRGS** [comment]
Hi Daniel.
Unfortunately, for me, the documentation isn't very helpful.
For example, route_geometry for a route using v4 is about 7,400 chars in length. Using v5, for the same route, routes.geometry is 11 chars in length. Each step has a geometry, the first ending in ?? but the first 9 chars are the same both both steps (this route has 2):
ou~aIdzhN??
ou~aIdzhN
There is clearly a huge difference with how the routes object is now built up and I am sure I am not the only one who would appreciated a change doc, or a mapping list between v4 and v5, as to how the objects now relate to each other.
For example, v4 gives a route object with (amongst other things) route_geometry, via_points, route_instructions; what are their equivalents using v5?

Thanks in advance.

**Comment by neilRGS** [comment]
Ah, hang on.
It appears my lon lat was being flipped by a function the previous dev was using with OpenLayers. 
Ignore this for now.

I have a decent-looking json object now (though the route isn't being drawn - the polyline doesn't seem to be getting passed correctly to the readGeometry function.
Still diggin'...

Thanks.

**Comment by daniel-j-h** [comment]
Check the docs at http://project-osrm.org/docs/v5.7.0/api/#route-service

```
geometries 	polyline (default), polyline6 , geojson
overview 	simplified (default), full , false
```

For frontend integration we recommend http://www.liedman.net/leaflet-routing-machine/ - but a different one should work fine, too. Good luck!

**Comment by neilRGS** [comment]
Thanks Daniel.
I'll take a look at the leaflet link.
I'm getting good Jason from the osrm engine now, which is great, and really fast.

Great work!

Neil.

On 23 May 2017 5:05 pm, "Daniel J. H." <notifications@github.com> wrote:

Check the docs at http://project-osrm.org/docs/v5.7.0/api/#route-service

geometries      polyline (default), polyline6 , geojson
overview        simplified (default), full , false


For frontend integration we recommend http://www.liedman.net/leaflet-routing-machine/ - but a different one should work fine, too. Good luck!

**Comment by neilRGS** [comment]
Hi Daniel.
Thanks for that docs link.
I simply had to change my geometries option from polyline to polyline6 and it now works.

Thanks again,
Neil.
