### ISSUE TITLE
Testcases are Broken on Master

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2867]
With the premature merge of https://github.com/Project-OSRM/osrm-backend/pull/2849, we introduced some breaking test-cases into master.

We obviously need to fix these.
Most cases are a simple fix, modifying the reported speed/time values.

A lane case however is broke more thoroughly. I currently fixed it adding a turn-restriction to force the routes on the correct path. This needs to be investigated further, though.

**Comment by MoKob** [comment]
With #2868 merged, most cases are working again.
We need to investigate https://github.com/Project-OSRM/osrm-backend/blob/802b93fa9a019b7eb20af4919ff9653ec30a7472/features/guidance/turn-lanes.feature#L505-L507, since the turn restriction is currently the only reason for this test to pass. The restriction itself shouldn't be necessary. The u-turn using the two four-way intersection is cheaper than the dedicated u-turn lane, though.

**Comment by miccolis** [comment]
Assuming this is stale. @MoKob please re-open if I'm wrong.

**Comment by MoKob** [comment]
The test is still including a turn restriction that shouldn't have to be there. It isn't a pressing issue though. I am fine with having this closed as a wont-fix.
