### ISSUE TITLE
{"message":"Coordinates are invalid","code":"InvalidOptions"} getting this error while older api was working fine

### ISSUE THREAD

**Issue by Rajmendra** [Project-OSRM/osrm-backend#2874]
Hey Guys,

I m getting this invalid coordinates error. for my request

http://router.project-osrm.org/table/v1/driving/37.318776,-121.97259700000001;37.5365343,-122.24250330000001

but if i change 121(three digits) and 122(three digits to 12(two digits) and 12(two digits) it works.

http://router.project-osrm.org/table/v1/driving/37.318776,-12.97259700000001;37.5365343,-12.24250330000001

**Comment by danpat** [comment]
The coordinate order is `longitude,latitude`, you've got them backwards, -121 is not a valid latitude.
