### ISSUE TITLE
Nearest Service - 500 Internal Server Error

### ISSUE THREAD

**Issue by jonataswalker** [Project-OSRM/osrm-backend#2875]
Example: http://router.project-osrm.org/nearest/v1/driving/13.388860,52.517037?number=3&bearings=0,20

**Comment by daniel-j-h** [comment]
Nearest is currently disabled on the demo server. Reason is we saw exhaustive graph traversals for users requesting thousands of nearest service results and impossible bearings. We're working on restricting these in:

https://github.com/Project-OSRM/osrm-backend/pull/2873

This will hopefully land today and will be in the 5.4 RC we're planing to tag today.

Closing here, we're working on it.
