### ISSUE TITLE
tolls

### ISSUE THREAD

**Issue by FilipeCB** [Project-OSRM/osrm-backend#288]
hi,

It is not good that the OSRM return the route depending on there are tolls?

**Comment by MoKob** [comment]
Removing Guidance flag as this is a pure routing-model question, not guidance question.

**Comment by naoliv** [comment]
I guess it's related with #2771
Couldn't OSRM by default calculate the routes using toll highways and just issue a warning saying that "This route has tolls"? (or something like that)

As it is now we see some uncommon results.

**Comment by danpat** [comment]
@naoliv You can modify the default toll behaviour by editing `profiles/car.lua` and setting `ignore_toll_ways` to `false`.

The demo server at `router.project-osrm.org` only has the capacity to run one version of the profile, and we use the default of `ignore_toll_ways = true`.  If you deploy your own server, you can customize your own defaults.

**Comment by naoliv** [comment]
@danpat I know that profiles can be modified and customized, but isn't it expected (from the users) to route through toll highways by default? (like all the other routers do)
Wouldn't it be better to enable it by default in the demo server? Or there are some specific needs to have it disabled, please?

**Comment by TheMarex** [comment]
@naoliv Yes I agree it is not a good default:

http://map.project-osrm.org/?z=12&center=37.852086%2C-122.483826&loc=37.852086%2C-122.483826&loc=37.784825%2C-122.460823&hl=en&alt=0

Every sane driver would rather pay the tolls on the Golden Gate Bridge then take that detour.

**Comment by MoKob** [comment]
While, at the same time, any sane driver would prefer the just as good non-toll route if its only a few seconds longer.
Unless we get #77 to penalise toll roads for preference, either way will be bad in some sense. The question here is whether we prefer to not have bad detours in areas like the bay area or prefer toll roads (which are often the slightly shorter choice) in areas that offer multiple alternatives.

**Comment by TheMarex** [comment]
Re-enabling in https://github.com/Project-OSRM/osrm-backend/pull/2782

**Comment by TheMarex** [comment]
Default routing in SF is fixed.
