### ISSUE TITLE
Dynamic Edge Update QA: Dump / Warn on High Delta

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2882]
We allow users to dynamically update edge weights via:
https://github.com/Project-OSRM/osrm-backend/wiki/Traffic.

The first time an update happens we update the internal speeds (based on profiles) with the user-provided speed files. This happens in [the contractor](https://github.com/Project-OSRM/osrm-backend/blob/eebda5c0a5c1260453e408f4ad02100066a69569/src/contractor/contractor.cpp).

It would be great to have an (optional) check for when the update changes speeds by either
- a high relative delta (as in the new speed is twice as high) and / or
- a high absolute delta (as in the new speed is 100km/h higher)

(for both too high / low deltas --- maybe configurable)

This would allow us to catch either mis-taggings or errors on the speed profile side.

**Comment by MoKob** [comment]
@daniel-j-h twice as high I wouldn't find that confusing. Consider a traffic jam on the motorway. When you can normally drive 200km/h and suddenly go with less than 20km/h. This would even give you a factor of 10.
So you can check for improvements (e.g. limit the maximum you would want to see in speeds), but limiting the minimum in this way without a lot of false positives is hard, I guess.

**Comment by daniel-j-h** [comment]
Yes you are right. The minimum is more important for verifying accumulated speeds, as in historic speed profiles. @karenzshea is looking into this and for a first iteration checking for speed improvements that are "too high" is a good start.

**Comment by karenzshea** [comment]
Initial pass at this has been implemented.
