### ISSUE TITLE
why reconstruct the graph when processing 65% contractor

### ISSUE THREAD

**Issue by eryalee** [Project-OSRM/osrm-backend#2887]
number_of_contracted_nodes > static_cast<NodeID>(number_of_nodes\*0.65\*core_factor)

**Comment by daniel-j-h** [comment]
https://github.com/Project-OSRM/osrm-backend/commit/a5c5f4c02c55a00e94f67680416d3d4c33aee23d

https://github.com/Project-OSRM/osrm-backend/commit/57b3f42b034e329229a1854bbe9ff5b94e87d410

**Comment by eryalee** [comment]
@daniel-j-h Got it~thanks.
