### ISSUE TITLE
Check Semantics of EMPTY_NAMEID Callsites

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2909]
@MoKob capturing from today's chat so we don't forget about this (feel free to add more or clarify):

We're using `EMPTY_NAMEID` in guidance; now with the ref / name split we have to make sure the semantic behind checking the id is still correct or if we rather have to check e.g. for empty name or empty ref.

**Comment by TheMarex** [comment]
Maybe the name `EMPTY_STRING` would be more fitting, as the dictionary contains more then just names at this point.

**Comment by MoKob** [comment]
@daniel-j-h with your name-change heuristic merged, is this resolved?

**Comment by daniel-j-h** [comment]
Yes - this landed. Closing here.
