### ISSUE TITLE
false polyline is returned by route

### ISSUE THREAD

**Issue by SimonTreu** [Project-OSRM/osrm-backend#2910]
The polyline string returned by /routes is false. The route gets messed up at some point (it is the same as the geojson up to some point and then differs and goes to a different point. The coordinates are also not on any streets any more). It might be related to
http://stackoverflow.com/questions/14637088/google-maps-v3-error-drawing-encoded-polyline

I decoded the polyline using https://developers.google.com/maps/documentation/utilities/polylineutility

To reconstruct the error: 
search
``` /route/v1/bicycle/13.39598,52.532453;13.397864,52.50168?alternatives=true&overview=full&geometries=polyline ```
using the bicycle profile.

It is correct up to "Georgenstraße"

The polyline string is: ```yfs_IskwpABABABAh@QzAs@jD}AXMXORI~DeBTKTCnBGPbA`CxMx@lEt@`ErE}B`@An@ZTPXLPJVApAl@DBVLXLFB|Ar@|CpApBbAVJRDF@nBDP@T@tFm@^Ej@GNC\\EDADAPvH@b@pDa@^@vCSnDa@F@TCXERDpBQ|AQRKlDa@`@ChCUHAhDYpDa@vD[VArCYzBUp@GC}AA]AIEaB?YCc@CyApD_@nD]~Da@fCQAONUvAcGz@aEVObAgFH_@bA_FfBz@fDxAdD|Ar@Z^N~@`@@```

The Geojson is:
[geojson.txt](https://github.com/Project-OSRM/osrm-backend/files/471694/geojson.txt)

**Comment by SimonTreu** [comment]
I found out what the issue is. The problem is that there are two Backslashs instead of one. If you replace ``` \\  ```
by
``` \ ```
you get the proper polyline.

**Comment by MoKob** [comment]
@SimonTreu these `\\` you are seeing are following the specs over at http://json.org/ . Any `\` character has to be escaped as `\\`.

A simple copy of that JSON string into the polyline decoder will result in the broken geometries you see.
