### ISSUE TITLE
Could NOT find LUAJIT AND DOXYGEN

### ISSUE THREAD

**Issue by Havok56** [Project-OSRM/osrm-backend#2911]
Hi,

I was two errors during cmake .. : 

Looking for LuaJIT 5.2
-- **Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR)**
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /usr/lib/x86_64-linux-gnu/liblua5.2.s
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so
-- Found STXXL: /usr/lib/libstxxl.so
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- OpenMP support found. Linking just in case for stxxl
-- **Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)**
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   unit_test_framework

How can I solve it ?

Thanks.

**Comment by daniel-j-h** [comment]
Both are optional. If CMake can't find them you can for example not build the documentation with doxygen. Nothing to worry about, simply continue in the build process.

In the build direcctory:

    cmake ..
    cmake --build .

I'm closing this issue as not actionable for us. Feel free to comment anyway.

**Comment by Havok56** [comment]
Ok, thank you !!
