### ISSUE TITLE
Separate turn time and turn weight

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2921]
Just like speed and weight should be separated, it might be good to separate turn time and turn weight.

In my experience (with bike routing), people prefer a route with few turns, even if it's slightly longer, since It makes the route easier to remember and to follow. As width speeds/weights, if you only have the time penalty to tweak and not a separate weight, there's no way to achieve this without distorting the travel time.

If additional data becomes available to the turn function, you might want to avoid turning to/from/across specific types of roads or lanes based on this data, without affecting the travel time.

Related to #2918.

**Comment by MoKob** [comment]
@emiltin from my understanding, this should fall out of #77 if implemented correctly. We might need to adjust the turn function to return both a time and a penalty, but apart from that we should be fine. Timing-penalties need to be added to the time, weight penalties to the weight part and the rest should be handled transparently.

**Comment by emiltin** [comment]
sounds good!

**Comment by daniel-j-h** [comment]
Closing this in favor of speed / weight split done in https://github.com/Project-OSRM/osrm-backend/pull/2399.
