### ISSUE TITLE
Make cucumber node maps easier to read

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2925]
I suggest changing the format of node maps used in cucumber tests to make them easier to read/view.

Current syntax:

```gherkin
Given the node map
    |   |   | i | l |   |   |
    |   |   |   |   |   |   |
    | d |   | c | b |   | a |
    | e |   | f | g |   | h |
    |   |   |   |   |   |   |
    |   |   | j | k |   |   |
```

Proposed syntax:
```gherkin
Given the node map
    |     i l     |
    |             |
    | d   c b   a |
    | e   f g   h |
    |             |
    |     j k     |
```

The benefit is that the geometry is visually clearer and the tables are simpler. Current tables have the oddity that they are stretched to double width horizontally due to all the pipe "|" symbols.

The new syntax would also allow subtle visual queues when appropriate, ie. to indicate where ways are:

```gherkin
Given the node map
    |     i l     |
    |     . .     |
    | d . c b . a |
    | e . f g . h |
    |     . .     |
    |     j k     |
```

Such extra characters would simply be ignored, they are only to make the test easier to read.

Existing tables could be converted to the new syntax using a small script, since existing node names are fortunately limited to single characters. Both syntaxes could co-exists for a while if needed.

A possible drawback: Cucumber tables can be aligned automatically in most editors which is very practical. The new format can still be aligned, however some (all?) editors will left-align the cell content, which can mess up the map.

A way to avoid this drawback would be to enforce dots at empty node locations:

```gherking
Given the node map
    | . . i l . . |
    | . . . . . . |
    | d . c b . a |
    | e . f g . h |
    | . . . . . . |
    | . . j k . . | 
```

As long as you have nodes or dots at the left-most position, left-alignments will not change the content. It does gives you a kind of grid to work on which can be beneficial, but I feel it makes it harder to read the table.

**Comment by MoKob** [comment]
I feel this is a very good idea. I have encountered this problem very often myself.

**Comment by emiltin** [comment]
Cucumber trims leading spaces from the column string, ie. "    j k    "  is returned as "j k". Seems we would need to use dots for empty nodes or add quotes, which is a bit annoying.

**Comment by emiltin** [comment]
There is no way to preserve leading spaces in cucumber tables. The best might to to switch to doc strings, either using a minimalist layout:

```gherkin
        Given the node map
            """
                a    
                b    
            d c   g h
                e    
                f    
            """
```

Or with a convention of eg. pipes or other symbols on the sides to provide a visual frame:

```gherkin
        Given the node map
            """
            |     a     |
            |     b     |
            | d c   g h |
            |     e     |
            |     f     |
            """
```

Thoughts? Do you think this is an improvement? @MoKob

**Comment by emiltin** [comment]
Here's a branch that work with the alternative doc string syntax and has an example of an updated feature file:
https://github.com/Project-OSRM/osrm-backend/blob/refactor/node_maps/features/guidance/roundabout.feature

**Comment by MoKob** [comment]
I have to say that seeing these large maps, I'd favour the limitation to the left and right. No alignment chars make the node maps hard to align on longer distances. I'd love the possibility to indicate roads via points (as an optional feature).

@emiltin whats your take here?

**Comment by emiltin** [comment]
I would go with a layout without left/right borders. Most node maps are quite small (unlike the big ones in the files above) and the borders seems to complicate things and make the maps harder to edit.

However it will be possible to add dots or other symbols when needed, eg. to provide guidelines for alignment in special cases. These extra symbols will simply be ignored when parsing the map.

Regarding your comment on "the possibility to indicate roads via points (as an optional feature)". If mean the ability to add additional symbols which are ignored when parsing the map, then I agree this is practical, eg. to make it easier to understand the layout of ways:

```gherkin
            """
            a     b
              .   .
                . .
                  b
            """
```

But it's not a way to automatically define ways - you still need to use a separate table for that.

**Comment by MoKob** [comment]
I agree with the visual aid only (otherwise the connectivity is not clear) for adding dots.

 However I disagree with the `quite small` part. For our guidance I had to add quite complicated maps and I feel that they might only get worse when we manage to tackle bike instructions/walk instructions.
Having at least a left/right border (it should make parsing not much different, right? After all its only trimming the very first/last char) would be a clear advantage for readability for tests that span many rows.

**Comment by emiltin** [comment]
Right,  parsing is not a problem. It's more a question of whether we want to enforce borders or make them optional.

**Comment by MoKob** [comment]
Well. If its possible to have them but not enforced, I'd be alright with that. @daniel-j-h any takes here?

**Comment by emiltin** [comment]
We could also choose to enforce borders on all four sides, eg.:

```gherkin
"""
  – – – –   
| a     b |
|   .   . |
|     . . |
|       b |
  – – – –  
"""
```

But again, it might take more effort to edit maps.

**Comment by MoKob** [comment]
I'd prefer an optional solution. After all, it's only necessary on larger tests and could be used to give hints, just like the dots.

**Comment by daniel-j-h** [comment]
Love the dots a visual clues and for quickly understanding Cucumber scenarios. I'm fine with changes in that direction, as long as it doesn't make our Cucumber support code much more complicated; it's already getting out of hand.

**Comment by emiltin** [comment]
The support code does not change much. Parsing a doc string is not really more complicated than dealing with a table object.

@daniel-j-h any thoughts on whether borders should be enforced or optional?

**Comment by daniel-j-h** [comment]
No strong opinions on that as long as it's documented.

**Comment by emiltin** [comment]
Has now been implemented.

**Comment by MoKob** [comment]
Thx again @emiltin for this improvement.
