### ISSUE TITLE
osrm-extract hangs on generating edge-expanded edges

### ISSUE THREAD

**Issue by rkcpi** [Project-OSRM/osrm-backend#2927]
We're currently trying to use osrm-extract on the following map: http://download.geofabrik.net/europe-latest.osm.pbf.

However, osrm-extract seems to stop on the `generating edge-expanded edges` step:
```
...
[extractor] writing street name index ... ok, after 0.537011s
[info] Writing turn lane masks...
[info] done (0.000127)
[info] extraction finished after 4976.04s
[info] Generating edge-expanded graph representation
[info]  - 341223 restrictions.
[info] Importing n = 382120223 nodes 
[info]  - 1094928 bollard nodes, 294824 traffic lights
[info]  and 402322465 edges 
[info] Graph loaded ok and has 402322465 edges
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.17176
[info] Edge compression ratio: 0.213348
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 402321631 nodes in edge-expanded graph
[info] generating edge-expanded edges
```
It's been like this for several hours now, usually it completes within one to two hours. It also doesn't seem to do much: load avergae is 1.00, only one CPU seems to be used.

This happens with a current master build (commit aa5f8dce23fc178a3dd8e45a9d79393d29d93986), stxxl v1.3.1 on a CentOS 7.2.1511 box.

This was fine with the build we used before this one (master d3a6b5a77ed4ec9663f68aea24f960ecfb70619a)

Might be related to #2852?

**Comment by daniel-j-h** [comment]
Thanks for reporting.

Looks related to turn analysis being stuck in a loop. @MoKob can you have a look on Monday?

@rkcpi what you already can do is attach gdb to the running process and manually do some sampling: break and note the function you're in. I guess this works best with debug symbols:

    cmake .. -DCMAKE_BUILD_TYPE=Debug

This way you should be able to localize where the loop is happening exactly.

**Comment by MoKob** [comment]
I will look into it. Just on a side-note: the "[info] generating edge-expanded edges" is sequential, so having only one CPU at work is expected.

**Comment by MoKob** [comment]
We just merged a fix that should, hopefully solve the hang you are expecting. Can you report back and close here, if the newest master solves your problem?

**Comment by pongo710** [comment]
Thanks for the fast fix. We will test and report if this fixes the issue for us.

**Comment by pongo710** [comment]
I just successfully preprocessed the map: http://download.geofabrik.net/europe-latest.osm.pbf

Thanks for fixing the bug. The issue can be closed.
