### ISSUE TITLE
Service route not giving results for all location.

### ISSUE THREAD

**Issue by nkafle89** [Project-OSRM/osrm-backend#2930]
First I would like to apologize that I do not have much knowledge about using the OSRM APIs. Maybe my question would be something hat can be easily fixed or I am making some mistakes. I couldn't find a solution to my problem anywhere, so I am posting my question here.
For my research, I need routing distance between all two-point-pairs out of the 312 points (I have lat and long for these points) in Chicago.

I found something useful on this page. It can be easily done using osrm api with the following command.
http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false

But this doesn't work for the co-ordinates around Chicago area. For example, when I enter following (with the lat/long of Chicago area) I get distance as 0.

http://router.project-osrm.org/route/v1/driving/41.896,-87.632;41.907,-87.625?overview=false

I don't know what is wrong. Any help would be appreciated.

**Comment by danpat** [comment]
@nkafle89 The coordinate order is `<longitude>,<latitude>`.  Your Chicago coordinates are somewhere in Antarctica.

Try:

http://router.project-osrm.org/route/v1/driving/-87.632,41.896;-87.625,41.907?overview=false
