### ISSUE TITLE
Non correct drawing of route segments with waypoints which was dropped by matching service.

### ISSUE THREAD

**Issue by wiva-koikoi** [Project-OSRM/osrm-backend#2933]
Server (v5.3.3):
`osrm-routed --max-matching-size 300 australia_oceania.osrm`
Request:
`http://127.0.0.1:5000/match/v1/driving/115.76226333333334,-31.997935;115.76111,-31.997926666666665;115.76161166666667,-31.996100000000002;115.76421833333333,-31.989806666666663;115.76401,-31.989635;115.76177000000001,-31.989596666666664;115.75265666666668,-31.989784999999998;115.75210999999999,-31.993105;115.752105,-31.997988333333335;115.75322666666668,-32.013645;115.75327,-32.01392166666667;115.75203166666667,-32.016435;115.75114666666666,-32.03100333333334;115.74965500000002,-32.030615;115.74788500000001,-32.030899999999995;115.74598333333333,-32.035830000000004;115.74685166666669,-32.036190000000005;115.75162833333334,-32.03724666666667;115.75538666666668,-32.03644166666666;115.75402333333335,-32.036995000000005;115.75400999999998,-32.03715666666667;115.75522833333335,-32.04282833333333;115.75820166666666,-32.04209166666667;115.75815166666668,-32.04170333333333;115.75805999999999,-32.041491666666666;115.75737499999998,-32.041534999999996;115.75572500000001,-32.04192;115.75569333333333,-32.04186833333333;115.75569333333333,-32.04186833333333;115.75576333333332,-32.041788333333336;115.75718333333334,-32.04145833333334;115.76,-32.04111;115.76037999999998,-32.040855;115.76307999999999,-32.034915;115.76307333333334,-32.027474999999995;115.76340833333333,-32.02731666666667;115.76762166666667,-32.026444999999995;115.76883333333332,-32.02725;115.76926,-32.029554999999995;115.78221666666668,-32.03009833333333;115.79485333333332,-32.02921833333333;115.79586833333333,-32.02753666666667;115.79688166666668,-32.028083333333335;115.79751999999999,-32.028415;115.79801666666665,-32.028704999999995;115.79925,-32.02726;115.80017000000001,-32.02744;115.80139666666668,-32.025885;115.80346333333334,-32.02674666666667;115.80409166666668,-32.02615333333333;115.80600833333334,-32.02715;115.80602333333333,-32.027095;115.80602333333333,-32.027095;115.80597166666666,-32.026955;115.80595999999998,-32.027008333333335;115.80593166666668,-32.02707;115.81115,-32.029183333333336;115.81192666666666,-32.02929166666667;115.81262333333333,-32.029853333333335;115.81348000000001,-32.03136333333334;115.81969166666667,-32.029945;115.840745,-32.01673;115.85686499999998,-32.00928333333333;115.85697166666665,-32.00948666666667;115.85894833333332,-32.01406;115.86067333333334,-32.014195;115.86411500000001,-32.01156;115.86405666666666,-32.011536666666665;115.86375833333335,-32.01168166666666;115.86366333333332,-32.0118;115.86360666666666,-32.01195833333334;115.86366333333332,-32.01195833333334;115.86367333333334,-32.011905;115.86367333333334,-32.011905;115.86355833333333,-32.01197333333334;115.863615,-32.01202833333333;115.86356166666668,-32.011975;115.86356166666668,-32.012026666666664;115.86350666666667,-32.01199666666666;115.86356666666667,-32.01204;115.86354333333333,-32.011988333333335;115.86358166666666,-32.01204666666667;115.86363333333333,-32.01208;115.86360833333335,-32.01213166666666;115.86358999999999,-32.01208;115.86354333333333,-32.01202333333333;115.86360166666667,-32.011945;115.86374666666667,-32.011735;115.86376833333334,-32.011563333333335;115.86409333333334,-32.01172;115.86411166666667,-32.01177833333334;115.86374333333333,-32.012296666666664;115.86232166666666,-32.013175000000004;115.859665,-32.01432333333333;115.85711500000001,-32.01321333333333;115.85495833333334,-32.01045333333333;115.84549333333334,-32.0145;115.83407833333334,-32.020356666666665;115.83060333333333,-32.02327833333333;115.81569333333333,-32.03087166666667;115.81170500000002,-32.03181333333334;115.78506,-32.03615833333333;115.76309833333335,-32.04089833333333;115.76294166666666,-32.04081333333333;115.76242666666667,-32.04111;115.76231166666666,-32.041061666666664;115.76198500000001,-32.041153333333334;115.76010166666669,-32.04174166666667;115.76009833333335,-32.042003333333334;115.76009833333335,-32.042003333333334;115.76012333333334,-32.04190166666667.json?bearings=0,120;0,120;44,120;3,120;297,120;273,120;217,120;168,120;178,120;135,120;209,120;185,120;245,120;287,120;219,120;178,120;114,120;72,120;249,120;188,120;178,120;106,120;30,120;348,120;301,120;255,120;298,120;0,120;0,120;55,120;110,120;59,120;47,120;359,120;43,120;54,120;97,120;146,120;96,120;83,120;20,120;72,120;113,120;120,120;56,120;102,120;43,120;93,120;48,120;110,120;33,120;0,120;0,120;318,120;219,120;111,120;51,120;96,120;148,120;75,120;75,120;61,120;104,120;163,120;121,120;57,120;336,120;293,120;136,120;185,120;94,120;214,120;0,120;0,120;137,120;323,120;122,120;305,120;127,120;306,120;131,120;259,120;20,120;260,120;307,120;136,120;72,120;348,120;103,120;252,120;177,120;221,120;235,120;279,120;321,120;263,120;242,120;197,120;220,120;274,120;253,120;254,120;345,120;261,120;201,120;314,120;251,120;176,120;202,120;201,120;13,120&steps=false&geometries=geojson&annotations=false&overview=full&timestamps=1473809139;1473809184;1473809215;1473809292;1473809297;1473809311;1473809401;1473809438;1473809488;1473809636;1473809642;1473809665;1473809777;1473809787;1473809800;1473809837;1473809844;1473809875;1473809982;1473810014;1473810016;1473810073;1473810098;1473810103;1473810117;1473810126;1473810164;1473810258;1473810267;1473810277;1473810309;1473810358;1473810363;1473810439;1473810537;1473810540;1473810575;1473810586;1473810614;1473810722;1473810831;1473810869;1473810881;1473810888;1473810897;1473810924;1473810938;1473810969;1473810991;1473811005;1473811031;1473811039;1473811965;1473811974;1473811978;1473811990;1473812053;1473812073;1473812082;1473812107;1473812152;1473812333;1473812520;1473812523;1473812555;1473812569;1473812619;1473812624;1473812641;1473812650;1473812699;1473812705;1473812707;1473814451;1473814452;1473814472;1473814509;1473814584;1473814619;1473814623;1473814660;1473814662;1473814745;1473814754;1473814766;1473814868;1473814898;1473814907;1473814916;1473814956;1473815017;1473815024;1473815034;1473815053;1473815070;1473815097;1473815208;1473815357;1473815384;1473815537;1473815563;1473815743;1473815952;1473815958;1473816004;1473816063;1473816067;1473816089;1473816095;1473816096;1473816120&radiuses=15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15`
Result:
Tracepoint 16 was dropped ( == "null" in reply ).
Segment between waypoints 15-17 is simple line, but nice polyline expected.
See attached image.
![2016-09-20-111320_1680x1050_scrot_edited](https://cloud.githubusercontent.com/assets/22316621/18665199/be5e085e-7f2e-11e6-8f96-5b4c4ca21f6a.jpg)

**Comment by MoKob** [comment]
Can you provide some more details on how this is a osrm-backend issue? If the trace-point is dropped, osrm fails to provide a matching and as direct consequence a route including the respective point.

 It looks to me that whatever frontend is used here does not expect `null` in the results and simply skips the point, connecting the node 15 and 17 directly.

If you are looking to improve your results, you could adjust GPS precision (see https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#request-4).
In addition, it might be that your requested bearings don't match the segment-bearings at the GPS coordinate. 

The drawing issue itself seems unrelated to osrm itself to me.

**Comment by wiva-koikoi** [comment]
> Can you provide some more details on how this is a osrm-backend issue?
It is simply:
1. "Frontend" is:
`L.polyline (waypoints, {color: color, opacity: _options.draw.opacity, weight: _options.draw.weight,}).addTo(mymap)`
neither more nor less. All points are taken from "matching" reply.
2. If I want to receive "matched" waypoints only, I set "overview=false" mode. And if I set "overview=full" I expect to take nice polyline.
3. Let's run through some examples, from simplest:
 - We need to draw route from A to B:
```
   In "overview=false" mode as result we receive waypoints **A**, **B**.
   In "overview=full" --> **A**, A1, A2, A3, **B**  ( == we can draw nice polyline).
```
 Right? Go next:
 - We need to draw route from A to F through B, C, D, E **without** dropped waypoints.
```
   In "overview=false" --> points **A**, **B**, **C**, **D**, **E**, **F**
   In "overview=full" --> **A**, A1, **B**, B1, B2, **C**, C1, **D**, D1, D2, D3, **E**, E1, **F** (also nice polyline)
```
 - We need to draw route from A to F through B, C, D, E **with** dropped waypoint D.
```
   In "overview=false" --> points **A**, **B**, **C**, **E**, **F**
   In "overview=full" --> (in fact) **A**, A1, **B**, B1, B2, **C**, **E**, E1, **F**
   In "overview=full" --> (expected) **A**, A1, **B**, B1, B2, **C**, C1, C2, C3, C4, C5, **E**, E1, **F**
```
What is difference between routing with simple A-B (1 example) and C-E (without D in 3 example)?
It looks like OSRM:
1 step: add intermediate points for nice drawing
2 step: "match" points and drop incorrect ones
3 step: rudely cut the dropped point and all its neighbors
I expect:
1 step: "match" points and drop incorrect ones
2 step: add intermediate points for nice drawing.

**Comment by danpat** [comment]
@wiva-koikoi It sounds like you are misunderstanding the API response and how the map-matching algorithm works.

The elements of `matchings` are not connected - if your trace matches without error, then `matchings` array should only have 1 entry.  The fact that you've got 4 means that OSRM split your coordinates into 4 partial matches with gaps between.  The matching algorithm is probabilistic and your GPS data is noisy - it's not going to give you a perfect result every time.

For coordinate [16], you've supplied a `radius` of 15m.  OSRM will search for up to 3x that distance for a road to snap to, and will give up if it can't find one.

Here's that point highlighted:

http://bl.ocks.org/d/a69a9c1a98f28a4cc69ada4cfdd58e8e

You've specified a bearing of 74 +/- 120 for this coordinate.  The nearest road that matches that is about 65m away.  This coordinate is failing to snap to anything and is being discarded, causing a break in your trace.

You should not draw the `matchings` geometries as connected - they are not, they represent partial matches from your original sequence of coordinates.

The `tracepoints` array are your original points, and the the `matching_index` and `waypoint_index` properties tell you which partial match each tracepoint was included in.  If your trace is clean and matches well, then they will all have `matching_index: 0`.

Given how far from the road your coordinate [16] is, it sounds like you need to check your GPS accuracy reading - it was much worse than 15m.

You can try iteratively removing these failed points yourself - if you get a `null` response, drop that point and re-try the request, see if the matches get connected.  Note that there's a ~500m max distance between points before traces get split.

The map-matching algorithm was tuned based on GPS data from a car arriving at about 10 second intervals, with ~5m accuracy.  If your data is much coarser than that, then you will see a high number of splits.

**Comment by wiva-koikoi** [comment]
Your answer is worthy of a hundred ("googled") other.
Thanks!

**Comment by MoKob** [comment]
From the last comment, I consider this issue solved.
