### ISSUE TITLE
libosrm performance on OS X

### ISSUE THREAD

**Issue by JMDelhGit** [Project-OSRM/osrm-backend#2938]
Hello,

I did succeed in compiling the orsm-backend on iMac OS X Yosemite 10.10.5. ( see issue #2928)
After the preparation of the map.osrm based on Belgium country, I can now run locally as a server and had significant gains in performance: a query for 5000 requests takes less than 50 seconds against 30 minutes via external server.

Next step, I try to use libosrm with different scenarii increasing in complexity targeting the use of the library in a Objective-C GUI Cocoa project.

1) Compile example.cpp using Xcode
    Once I could include all dependencies and libraries : Ok

2) Mix a simple Cocoa Objective-C GUI and a C++ class derived from the example.
    I created a C++ class and isolated the osrm config in the constructor. I then use a method to compute the routes using the same process as shown in example.cpp. 
    The GUI is used to enter the coordinates of 2 points and returns the distance and the duration between these 2 points.
I had to change 2 sources in the osrm package to avoid duplicate symbols Cocoa <> osrm:
   The conflict is related to NameID declared in Util/typedefs.hpp. 
   I altered the includes based on a previous similar issue ( #2466)
   1) Util/typedefs.hpp: 
      a) "using NameID = std::uint32_t;"
       changed for "using Name_ID = std::uint32_t;"
      b) "static const NameID INVALID_NAMEID = std::numeric_limits<NameID>::max();"
     changed for "static const Name_ID INVALID_NAME_ID = std::numeric_limits<Name_ID>::max();"
     c) "static const NameID EMPTY_NAMEID = 0;"
     changed for "static const Name_ID EMPTY_NAME_ID = 0;"

  2) Engine/Phantom_node.hpp:
     a) "(component.id != INVALID_COMPONENTID) && (name_id != INVALID_NAMEID);"
     changed for "(component.id != INVALID_COMPONENTID) && (name_id != INVALID_NAME_ID);"
    b) " bool IsValid() const { return location.IsValid() && (name_id != INVALID_NAMEID); }"
    changed for "bool IsValid() const { return location.IsValid() && (name_id != INVALID_NAME_ID); }"

   With these changes, I could successfully compile and run this project. Results are ok.

3) Based on the previous point,  I  now use osrm in a Cocoa project computing large numbers of routes.

Are these changes ok?

Thank you in advance

Jean Marie

**Comment by danpat** [comment]
@JMDelhGit The example client is single threaded, so you are probably not using all the processing capacity on your machine.

Also, make sure to re-use the `OSRM` object, do not build a new one for each request - constructing this object is expensive (it loads all the datafiles from disk).  The `OSRM.Route()` method is thread-safe, so you can perform many queries in parallel.

I have no idea why you'd need to rename `INVALID_NAMEID` to `INVALID_NAME_ID` in the current code.  Ticket #2466 was fixed, there should be no conflict.  Can you paste the errors you're seeing here please?

Also, please mention which version of OSRM you're trying to build.

**Comment by JMDelhGit** [comment]
Oops, the performance issue was my mistake. I forgot to notify the GUI for the end of the computations. Apologies!

I already created one OSRM object and re-initiated the route parameters using params.coordinates.clear()
I'm now at 15 seconds for 5000 requests :-) 

Meanwhile, I will use multi thread to  compare.  

For the compilation error, this is what I received in Xcode:
`osrm/include/util/typedefs.hpp:59:7: Redefinition of 'NameID' as different kind of symbol`
for the line 89

The error induced other errors when using NameID
I have the error when mixing Objective-C and C++
Using C++ Xcode project shows no errors

The osrm version is 5.3.0

**Comment by daniel-j-h** [comment]
Our typedef header is not namespaced, polluting the global namespace as soon as you pull it in:
https://github.com/Project-OSRM/osrm-backend/blob/8aa93f32ccd02ed3cdde2429715cdc9366be87f3/include/util/typedefs.hpp#L28

There might be name clashes with other libraries --- ouch.
Changing this would be a breaking API change, though.

**Comment by JMDelhGit** [comment]
@daniel-j-h Is there something I need to do for testing or other?

**Comment by daniel-j-h** [comment]
I already made a pull request fixing this on our side: https://github.com/Project-OSRM/osrm-backend/pull/2941.

Strictly speaking this changes the `libosrm` API but as long as you're not making direct use of the types in `typedef.hpp` you can run from that branch and / or cherry-pick 64b8456f1ac8a126e51f1f60a93fd116b186e18a already now.

This should allow you to compile your code without having to change the name id variable.

**Comment by daniel-j-h** [comment]
And since the performance issue is resolved, too, I'm already closing this issue (feel free to comment, though). Thanks for bringing this issue to our attention!

Ticket and pull request:
- https://github.com/Project-OSRM/osrm-backend/issues/2940
- https://github.com/Project-OSRM/osrm-backend/pull/2941

**Comment by JMDelhGit** [comment]
I just modify ` typedef.hpp `  based on  `64b8456` 
The project  using Cocoa Objective-C++ in XCode with libosrm C++ compiles without any error.
Thank you
