### ISSUE TITLE
Trip Plugin Hitting Assertion

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2939]
We just got an alarm that the trip-plugin fails to complete correctly, due to an assertion we hit.

The assertion triggered is:

```/include/engine/api/trip_api.hpp:92
in: osrm::util::json::Array osrm::engine::api::TripAPI::MakeWaypoints(const std::vector<std::vector<unsigned int> >&, const std::vector<osrm::engine::PhantomNode>&) const: !trip_index.NotUsed()
```

Our logs don't show any trip requests during the time the assertion triggers, so we are without knowledge what kind of request triggered this assertion.

**Comment by MoKob** [comment]
Turns out this happens in farthest insertion when we only see same coordinates. It is an unreasonable request, but we shouldn't fail on it.

**Comment by daniel-j-h** [comment]
@chaupow would you be so kind and have a look at this.
