### ISSUE TITLE
car profile with no restrictions

### ISSUE THREAD

**Issue by cordovapolymer** [Project-OSRM/osrm-backend#2947]
I want to make a car profile that will route without obeying any restrictions made for cars, such as:
```
motor_vehicle 	no
motorcar 	no
motorcycle 	no
```
How can I do this? I tried these tags from access_tag_whitelist, but it gave no result.

**Comment by daniel-j-h** [comment]
Setting

> properties.use_turn_restrictions = false

[here](https://github.com/Project-OSRM/osrm-backend/blob/8aa93f32ccd02ed3cdde2429715cdc9366be87f3/profiles/car.lua#L147) should do the trick.

Closing as not actionable for us, feel free to comment and report back your findings!

**Comment by daniel-j-h** [comment]
Hm re-reading your comment I _think_ what you actually mean is access tags and not restrictions.

In that case search `car.lua` for `access_tag` and modify the callsites / remove the checks. For example, we're setting node barriers and discarding ways based on the `access_tag_blacklist`.

**Comment by cordovapolymer** [comment]
Yes, I mean access tags. 
So there are two arrays
```
access_tag_whitelist = { ["yes"] = true, ["motorcar"] = true, ["motor_vehicle"] = true, ["vehicle"] = true, ["permissive"] = true, ["designated"] = true, ["destination"] = true }
access_tag_blacklist = { ["no"] = true, ["private"] = true, ["agricultural"] = true, ["forestry"] = true, ["emergency"] = true, ["psv"] = true, ["delivery"] = true }

```

Can they be modified so it would allow car driving via roads marked as

```
motor_vehicle   no
motorcar    no
motorcycle  no
```

Or I should modify the code?

**Comment by daniel-j-h** [comment]
`access_tag_whitelist` is used to
- determine if a way is accessible to set default speeds

`access_tag_blacklist` is used to
- set barriers on OSM Nodes
- discard ways that are not accessible using the `access_tags_hierarchy`

Please check `car.lua`. If you only want to enable the `=no` tagged ways you posted above, it should be good enough to remove the "no" entry from the `access_ tag_blacklist`. If you want to remove all access tag checks it should suffice to clear the `access_tag_hierarchy`.

In all cases, yes you have to modify the `car.lua` profile and run `osrm-extract` (and then `osrm-contract`) with your modified profile.
