### ISSUE TITLE
Check if map covers a particular location or not

### ISSUE THREAD

**Issue by NBallaney** [Project-OSRM/osrm-backend#2948]
Hi, my OSRM server uses the map of only a certain area. How can I check if a particular location falls on that map or not? Thanks!

**Comment by daniel-j-h** [comment]
Hi! This is unrelated to routing. What you want to do is a point-in-polygon check against the base map's boundary. You can and should do this in front of your OSRM server to filter requests you can not serve.

If you _really_ want to use OSRM for this you could do a [Nearest](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-nearest) request and check the result's waypoint distance. Note: OSRM will always return a "nearest" coordinate in the sense that if your base map is San Francisco and you make a nearest request in Antarctica you will get the "nearest" coordinate in your base map wrt. the distance to Antarctica.

I'm closing this as not actionable for us, feel free to comment and report back your findings!
