### ISSUE TITLE
Rip out LuaJIT for good

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2955]
At the moment our build system happily searches for LuaJIT and uses it when for example no other Lua installation is found or works with Luabind. This is dangerous since LuaJIT is not a first-class citizen in OSRM: we never test with it, don't run any setups with it and users are reporting crashes on various platforms and setups. Let's rip it out for good, since Lua/Luabind is already a pain in itself.

Instead of justifying a (potential?) performance improvement during extraction using LuaJIT we rather should explore for example not context switching between Lua and C++ on every Node / Way: https://github.com/Project-OSRM/osrm-backend/issues/1777.

- [ ] no longer try to use it in `CMakeLists.txt`
- [ ] do not test if Luabind compiles with it in `cmake/check_luabind.cmake`
- [ ] remove CMake module searching for Luajit `cmake/FindLuaJIT.cmake`

**Comment by springmeyer** [comment]
👍

**Comment by MoKob** [comment]
Landed in master
