### ISSUE TITLE
viaroute sample in the new version please

### ISSUE THREAD

**Issue by gonen52** [Project-OSRM/osrm-backend#2960]
I used the following http request
http://router.project-osrm.org/viaroute?hl=en&loc=63.86054,20.342641&loc=64.507369,16.747951&loc=64.931506,15.757998&alt=false&compression=false

to get route waypoints.

It stopped working and I get this message
The OSRM Demo server has moved to API Version 5. Documentation for the new version can be found at https://github.com/Project-OSRM/osrm-ba … cs/http.md

I was unable to set the new http request to get the route waypoints like I had before...

Can someone help and show me the substitute url for :

http://router.project-osrm.org/viaroute?hl=en&loc=63.86054,20.342641&loc=64.507369,16.747951&loc=64.931506,15.757998&alt=false&compression=false

many thanks

**Comment by daniel-j-h** [comment]
Here are the docs for the Route service:

https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-route

And here is an example with three coordinates in Berlin:

http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false

Note the lat,lon -> lon,lat switch from v4 to v5. I'm closing this as not actionable for us, feel free to comment and / or provide more information about your issue.
