### ISSUE TITLE
Distance Table?

### ISSUE THREAD

**Issue by gdinant** [Project-OSRM/osrm-backend#2964]
Hi,

I used to work with the previous version of the table service providing a list of computed distances for some src / dst points.

In the new version the distances have been replaced by durations even though the service description is: computes **distance tables** for given coordinates

I absolutely need those distances.

Any workaround?

Thanks,

Gabriel

**Comment by MoKob** [comment]
@gdinant our service never computed distance tables. It has always been travel-durations. The service name just has been updated.

There is a long, ongoing discussion over at https://github.com/Project-OSRM/osrm-backend/issues/1353.

Closing here in favour of that discussion.

**Comment by gdinant** [comment]
Thanks for your prompt answer @MoKob.

Perhaps I have been misled by the parameter names renamed from distance_table to durations and its type from int to float. Is it possible to have access to the previous API documentation, version < 5.x?

**Comment by MoKob** [comment]
I assume you are talking about: https://github.com/Project-OSRM/osrm-backend/wiki/Server-API---v4,-old?

**Comment by gdinant** [comment]
Exactly, thanks a lot :).
