### ISSUE TITLE
Table with Polyline

### ISSUE THREAD

**Issue by gdinant** [Project-OSRM/osrm-backend#2966]
Hi,

Is there a current open issue with the use of polyline in a table request?

The one from the documentation doesn't work:

GET http://router.project-osrm.org/table/v1/driving/qikdcB}~dpXkkHz?sources=0;1;3&destinations=2;4

response:
{
  "message": "Query string malformed close to position 18",
  "code": "InvalidQuery"
}

btw, InvalidQuery is also not mentioned in the documentation.

I tried with my own coordinates, and it ended up the same way.

Gabriel

**Comment by MoKob** [comment]
You have two problems here.

The docs are broken for that request and the polyline is not actually a correct polyline.

Using `http://router.project-osrm.org/table/v1/driving/polyline(egs_Iq_aqAppHzbHulFzeMe%60EuvKpnCglA)?sources=0;1;3&destinations=2;4`, you can see the correct results.

I already prepared a PR that will update the documentation and also fix a related parsing bug (https://github.com/Project-OSRM/osrm-backend/pull/2967).

**Comment by gdinant** [comment]
Thanks again @MoKob , it fixed my issue.
