### ISSUE TITLE
JSON truncated

### ISSUE THREAD

**Issue by soupman99** [Project-OSRM/osrm-backend#2970]
Working on a very large trip request.  The returned data is 1375962 bytes.  Works great, except that when my request gets this large the data becomes truncated.  

Any idea what can be done to resolve this?  Is it something to do with OSRM, or could it be another problem? Thx!

**Comment by daniel-j-h** [comment]
Here's a expensive DC -> SF query:

    $ http --body 'http://router.project-osrm.org/route/v1/driving/-77.035961,38.897579;-122.435760,37.746286?alternatives=true&steps=true&annotations=true&geometries=geojson&overview=full' > response.json
    $ ll -h response.json 
    -rw-rw-r-- 1 daniel daniel 4.6M Sep 29 16:18 response.json

resulting in a (uncompressed) 4.6 MB response, and

    $ http --header 'http://router.project-osrm.org/route/v1/driving/-77.035961,38.897579;-122.435760,37.746286?alternatives=true&steps=true&annotations=true&geometries=geojson&overview=full' | ag length
    Content-Length: 1639206

roughly 1.6 MB on the wire.

Please tell us more about your setup and how you're using OSRM, because I can't see this issue. I assume it's the client / library you are using to make the request / parse the response.

I'm already closing the issue as not actionable for us, please feel free to commend and report back.

**Comment by soupman99** [comment]
I'm using this docker-ized setup.
https://github.com/cartography/osrm-backend-docker

I used `wget` to fetch the data.  Sometimes it works fine, other times I see this:

```
HTTP request sent, awaiting response... 
  HTTP/1.0 200 OK
  Connection: close
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Methods: GET
  Access-Control-Allow-Headers: X-Requested-With, Content-Type
  Content-Type: application/json; charset=UTF-8
  Content-Disposition: inline; filename="response.json"
  Content-Length: 1178906
Length: 1178906 (1.1M) [application/json]
Saving to: ‘-117.46147967428149,35.082266694392416;-87.62480718301322,41.87955231183639;-97.58774242640168,35.51151448736239;-97.48156916799057,35.65285532730471;-97.50834554209646,35.49332229486923;-97.50326955549241,35.52101674189646;-97.49427905.1’

                             -117.46147967428149,35.08226669  19%[==========================>                                                                                                                   ] 220.31K  1.08MB/s               
                            -117.46147967428149,35.082266694  39%[======================================================>                                                                                       ] 451.53K  1.10MB/s               
-117.46147967428149,35.082266694392416;-87.62480718301322,41  94%[====================================================================================================================================>         ]   1.06M  1.11MB/s    in 1.0s    

2016-09-29 10:06:28 (1.11 MB/s) - Connection closed at byte 1113818. Retrying.
```

I realize it's on an OSRM issue, but maybe you can point me in the right direction since you seem to know more about these types of things than I do.  Thanks for you help, I appreciate it!

**Comment by soupman99** [comment]
Kept chopping & realized its something with my internal network.  Thanks for helping to point me in the right direction.

**Comment by daniel-j-h** [comment]
Glad to hear! Have fun routing! :)

:car: :bike: :walking:
