### ISSUE TITLE
Update internals docs

### ISSUE THREAD

**Issue by systemed** [Project-OSRM/osrm-backend#2977]
There are two helpful pages on the wiki explaining the internals of OSRM:

* https://github.com/Project-OSRM/osrm-backend/wiki/Graph-representation
* https://github.com/Project-OSRM/osrm-backend/wiki/Quick-start-to-Code

However, both are a bit old (the Graph Representation page was last updated in 2013) and they don't have definitions of the datatypes used in OSRM.

It would be great if one of the OSRM devs could spend a few minutes updating these and explaining the difference between (say) NodeBasedEdge, NodeBasedEdgeData, EdgeBasedEdge and so on, what they do and when/where they're used: it would make it easier for newcomers to hack on the OSRM codebase (and hopefully submit patches!).

**Comment by daniel-j-h** [comment]
Thanks for bringing this up, there is a related ticket at https://github.com/Project-OSRM/osrm-backend/issues/2184 for cleaning up the Wiki. These days we're trying to bring as much as possible into the repository to keep the docs in sync with versions.

@danpat I know you made a fabulous introductory post internally with fancy graphs showing off your Inkscape skills. Could you try locating your post and making it publicly available under the `doc` directory as some kind of introductory readme on pipeline / internals.

In the meantime @systemed feel free to ask your specific questions already here or on IRC.

**Comment by daniel-j-h** [comment]
Just letting you know @danpat just added some schematics for OSM -> OSRM's internal graph representation: https://github.com/Project-OSRM/osrm-backend/wiki/Graph-representation#graph-edge

**Comment by daniel-j-h** [comment]
Closing in favor of https://github.com/Project-OSRM/osrm-backend/issues/2184. Added it to the task list there.
