### ISSUE TITLE
Try GCC 6 on travis

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2982]
We should investige using GCC 6 on travis since it addresses https://github.com/Project-OSRM/osrm-backend/issues/2788 and would enable us to run tests with sanitizers enabled by default.

**Comment by daniel-j-h** [comment]
Note: GCC 6 requires at least Intel TBB 4.4u6; older TBB versions still have an UB issue. See https://github.com/Project-OSRM/osrm-backend/issues/2414.

**Comment by TheMarex** [comment]
This was done.
