### ISSUE TITLE
nearest node id in nearest service:

### ISSUE THREAD

**Issue by rorschach1592** [Project-OSRM/osrm-backend#2985]
Hi,
I want to get the nearest node_ids for a given coordinate(longitude,latitude), but the nearest service is just returning the coordinate. Is there a way to get the nearest node id for that given coordinate.

Thank you.

**Comment by daniel-j-h** [comment]
I'm closing this as duplicate of https://github.com/Project-OSRM/osrm-backend/issues/2548.

There is already a pull request implementing this https://github.com/Project-OSRM/osrm-backend/pull/2581 but it's not in master yet.
