### ISSUE TITLE
Match service result queries

### ISSUE THREAD

**Issue by ankitsoni9989** [Project-OSRM/osrm-backend#2986]
Hi,
I am currently using the match service by supplying the coordinates(longitude,latitude) with gps accuracy and timestamps, I need a few confirmations on the result:

- In the match service the matchings in the result are the different matching segments of the original trace points supplied, so what are the different criteria that split those points into different parts(matchings). Also I have read an issue #2933, in there it is mentioned that “ there's a ~500m max distance between points before traces get split” is this one of the criteria of that splitting of the complete traces into different matchings?
- How does the timestamps are being used in the match service, how they are getting used in the algorithm.
- How do we differentiate between a U-turn and a case when while moving forward we get a point behind the previous trace due to gps error, how will that point will be taken as, or will be eliminated?
- In the annotations section of result the obtained node ids, are those corresponds to the node ids referring to the turns or road intersection on the map?

Thank you

**Comment by TheMarex** [comment]
> ~500m max distance between points before traces get split

It is more like a calculation that checks if there is a viable path between two points that you would be able to drive given the time indicated by the timestamp. If you have two points A and B and their timestamp indicates they are 10sec appart, but all the routes we find between them are like 10km long - something is amiss and the algorithm decides to split the trace there in order not to screw matching of all the other points.

> How do we differentiate between a U-turn

Every point usually considers multiple candiates. On of those candidates might indicate that the receiver did not move at all, as opposed to turned around. The hidden markov model will select the candidate that seems the most likely given all previous and future GPS points.
A zig-zag pattern will usually lead to some detour that makes that hypothesis get discarded.

That said I've seen this fail often when there is a big blob of points (like from standing at a red light). That is why I would usually advice pre-processing the trace and removing point-blobs from the trace prior to feeding it to OSRM (geojson-tidy is a JS module that does just that). Not doing this in OSRM itself was a rather bad design decision and we are probably going to implement it one day.

> are those corresponds to the node ids referring to the turns or road intersection on the map?

These are the IDs of all the OSM nodes that are passed by the route.

**Comment by ankitsoni9989** [comment]
Thanks @TheMarex  for the answer. Also I wanted to clear one more thing:
In the HTTP api - osrm-routed map.osrm
Lets say I have 100 gps traces for a vehicle at around 6-30 seconds each. If pass these to the match service I will get the node IDs for the route nodes. Is there a way we can identify which trace points have been resolved to which node ID?

I have tried to get the node ID for the coordinates returned by the tracepoints in the match service and by the nearest api. But those coordinates does not corresponds to any of the osm ID from coords_callback(I have used imposm parser to read the pbf file to get the osm IDs for all coordinates).
Let me know if there is a way if I can get the node IDs specific to the start and end of the each segment trace out of those 100 since I am passing all of them together.

**Comment by TheMarex** [comment]
@ankitsoni9989 

- Run the query with `annotations=true`
- For every input coordinate `i` determine the `tracpoints[i].matchings_index` and `tracepoints[i].waypoints_index`.
- For every input trace but the last one do: `matchings[matchings_index].legs[waypoints_index].annotations.nodes[0]`
- For the last one that becomes `matchings[matchings_index].legs[waypoints_index].annotations.nodes[length - 1]`

**Comment by ankitsoni9989** [comment]
Thank you @TheMarex  for this, it really helped except one error:
for some 1726 tracepoints I ran it and for the last trace I am getting this:

> {'hint': 'kkUAgPyYAAB8AgAAJAAAAA4AAABHAAAARQAAAPc5AABUKAEALQAAACY4oQT1H8YARTihBM8fxgADAAEBzF_NoA==',
>  'location': [77.674534, 12.984309],
>  'matchings_index': 142,
>  'name': '6th Cross',
>  'waypoint_index': 2}

so the matching_index is 142 and waypoint_index is 2, but when I am passing it in the matchings as specified, then I have just 2 rows in legs which is index 0 and index 1 so I am getting an IndexError for that since I do not have waypoint index = 2 for that.
Please let me know where am I missing on this. Here is the error:

> json_response["matchings"][142]["legs"][2]["annotation"]["nodes"]
>
> IndexError                                Traceback (most recent call last)
> <ipython-input-36-4707aa003c83> in <module>()
> ----> 1 json_response["matchings"][142]["legs"][2]["annotation"]["nodes"]
> 
> IndexError: list index out of range

In this I have checked that the length of json_response["matchings"][142]["legs"] is just 2 so that will fulfil 0,1 index only
I am using requests lib in python to get the json response from HTTP api and working on that.

Thank you

**Comment by TheMarex** [comment]
You need n waypoints for n-1 legs. 0 and 1 form the first 1 and 2 the second. You need special case handling for the last waypoint of each leg.

**Comment by ankitsoni9989** [comment]
Thanks @TheMarex for the explanations, it helped a lot.

**Comment by ernstjan2** [comment]
@TheMarex I have an further question on the discussion above. I would like to match a set of GPS tracks and moreover couple these tracks with the existing OSM network. Is there any way for deducting the OSM_ID's of the matched route (links from the osm_line table) with a longitudinal position start and end at each osm_id? 

I would like to use this information for researching car following behavior based on gps tracks; for checking whether vehicles are travelling on the same roadway (an not on a slipway or parallel section etc.) would like to deduct the exact route and the accompanying characteristics such as maxspeed, numlanes.

Based on the osm nodes I should be able to retrieve the links; but is there any faster way instead of querying the results of the  match in another database? Or am I missing something?

**Comment by TheMarex** [comment]
@ernstjan2 going over OSM IDs of the nodes seems like the best way to me. Add the `annotations=true` query parameter: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#example-1

**Comment by PinkFLoyd92** [comment]
Hi, how can I get the latitude and longitude from a Node ID using OSRM?

**Comment by daniel-j-h** [comment]
If you want to get latitude and longitude based on a OSM Node ID you can use e.g. [libosmium](https://github.com/osmcode/libosmium), walk all nodes and pull the location out of the node you are looking for.

But usually OSRM already returns you locations / geometry.
