### ISSUE TITLE
Deduplicate code between InternalDataFacade and osrm-datastore

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2989]
In osrm-datastore there is a lot of code for loading all the `.osrm.*` files into memory. This code replicates a lot of the code that we wrote for the `InternalDataFacade`.

We should try to deduplicate this as much as possible, because having duplicate code is error prone. The easiest way I see to do factor this out into a shared header in `inlcude/storage`. Something like `include/storage/io.hpp` that implements loading this data to somewhere in memory.

A trivial example for the new interface for `.osrm.properties` in `io.hpp`:

``` cpp
size_t GetProfilePropertiesSize(boost::filestream::ifstream &input_stream);
void ReadProfileProperties(boost::filestream::ifstream &input_stream, ProfileProperties* buffer, size_t size);
```

Both `osrm-datastore` and `InternalDataFacade` can use this to load data: Either into internal or shared memory.

I recommend doing this one file at a time.

**Comment by TheMarex** [comment]
Straight forward:

- [ ] `.hsgr` file `InternalDataFacde::LoadGraph()` (there is already a function `readHSGRFileFromStream`) that can be adapted
- [ ] `.nodes` `InternalDataFacade::LoadNodeAndEdgeInformation`
- [ ] `.edges` `InternalDataFacade::LoadNodeAndEdgeInformation`
- [ ] `.datasource_names` `InternalDataFacade::LoadDatasourceInfo`
- [ ] `.datasource_indexes` `InternalDataFacade::LoadDatasourceInfo`
- [ ] `.timestamp` `InternalDataFacade::LoadTimestamp`
- [ ] `.profile_properties` `InternalDataFacade::LoadProfileProperties`
- [ ] `.ramIndex` `InternalDataFacde::LoadRTree()`

Need more investigation:

- [ ] `.tld` `InternalDataFacade::LoadLaneDescriptions`
- [ ] `.tls` `InternalDataFacde::LoadLaneTupleIdPairs`
- [ ] `.names` `InternalDataFacade::LoadStreetNames` (has own de-serialization code: in `range_table.hpp` implemented as `operator>>`)
- [ ] `.core` `InternalDataFacade::LoadCoreInformation` (look at the packing logic needed for `std::vector<bool>` in `storage.cpp`)
- [ ] `.icd` `InternalDataFacade::LoadIntersectionClasses` (has own de-serialization code: in `range_table.hpp`)

Don't touch:

- [ ] `.geometries` `InternalDataFacade::LoadGeometries()` (WARNING Jake is current refactoring this)

Is not loaded into memory:

- [ ] `.fileIndex` `InternalDataFacde::LoadRTree()`

/cc @chaupow @karenzshea @miccolis @danpat

**Comment by TheMarex** [comment]
Going to port `.hsgr` as an example.

**Comment by chaupow** [comment]
@TheMarex @karenzshea 

My thoughts on how to name the functions in `io.hpp` consistently:

* We had `readHSGRSize` and `readHSGR` in the beginning
* We then changed to `readHSGRHeader` and `readHSGR` cause the header in HSGR included more than just the size
* Now I have `datasource_names` and I need to read out metadata that are not written as a file header in the `.datasource_names` file 

So I am thinking of renaming all functions into `readFILENAMEMetaData` and `readFILENAME`.

**Comment by danpat** [comment]
#3165 consolidated all the file loading code, we now only have one version of everything.

Discussion on cleaning up the actual file formats and file I/O code is progressing on https://github.com/Project-OSRM/osrm-backend/issues/2242

@TheMarex given the above do we still need this ticket?
