### ISSUE TITLE
How to merge two osm.pbf (ex. Germany + Austria) files to one, in order to add data in OSRM??

### ISSUE THREAD

**Issue by gmiskos** [Project-OSRM/osrm-backend#3001]
I ve installed OSRM in an ubuntu 14.04 server machine. I ve extracted Greece and is working like a charm. But now i want to add Italy.

Can i added seperately or i have to merge the two osm.pbf files, and exctract again the merged file?

**Comment by daniel-j-h** [comment]
You can merge two base map pbfs. You can't merge two .osrm files.

.osrm files are binary dumps, and can not easily be merged. You have to merge your pbfs first and then run osrm on this amalgamation. In theory, this should work with maybe some issues at borders (I don't know how tools handle merging multiple pbfs).

Osmosis seems to provide such a merge feature for base maps / pbfs:
http://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.45#--merge_.28--m.29

**Comment by systemed** [comment]
osmfilter/osmconvert also enable you to merge pbfs.
