### ISSUE TITLE
osrm-routed should validate input coordinates better

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#3007]
http://router.project-osrm.org/route/v1/driving/-74.735667,5.207041;-74.721057,5.202046;-74697224,5.191564;-74.59997,5.069609?overview=false&alternatives=true&steps=true&hints=;;;

> [server error] code: bad numeric conversion: negative overflow

**Comment by daniel-j-h** [comment]
Yes, we shouldn't throw an exception there.

Great motivation for https://github.com/Project-OSRM/osrm-backend/issues/2916 (this would have been an undetectable overflow without the numeric cast).

**Comment by TheMarex** [comment]
Don't think this needs its own status code. This should be a 400 `InvalidQuery`.

**Comment by daniel-j-h** [comment]
`InvalidQuery` is not in the [v5 spec](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md) - but you're right seems like we return this in some cases already.
