### ISSUE TITLE
osrm-datastore updates shared memory while queries are running

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3016]
[This code](https://github.com/Project-OSRM/osrm-backend/blob/master/src/storage/storage.cpp#L741-L748) is supposed to ensure that we never swap the dataset while queries are running, because that would cause bad race conditions.

However since the member `barrier.number_of_queries` is _process local_ and this always 0 this code will never execute. This means we happily update the datasets even if queries are executed on it.

This will cause race conditions if you run osrm-datastore twice while a queries is executed. (because OSRM datastore will assume that the shared memory region that is currently in use, is actually free and start to write to it)

**Comment by MoKob** [comment]
This issue was solved, right?

**Comment by TheMarex** [comment]
Yes fixed by e82f678.
