### ISSUE TITLE
Build Error in ubuntu 14.04

### ISSUE THREAD

**Issue by ankitsoni9989** [Project-OSRM/osrm-backend#3018]
I am building OSRM on my local machine, by the steps:

> mkdir -p build
> cd build
> cmake .. -DCMAKE_BUILD_TYPE=Release
> cmake --build .
> sudo cmake --build . --target install

but in the 3rd one 

> cmake .. -DCMAKE_BUILD_TYPE=Release

 I am getting an error:

> Could NOT find Lua: Found unsuitable version "5.2.3", but required is exact version "5.2" (found /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so)
> -- Could NOT find Lua: Found unsuitable version "5.2.3", but required is exact version "5.1" (found /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so)
> CMake Error at cmake/FindLuabind.cmake:15 (MESSAGE):
>   Lua 5.1 or 5.2 was not found.
> Call Stack (most recent call first):
>   CMakeLists.txt:308 (find_package)

I tried Installing libluabind-dev but that is not working

Please suggest me where I am going wrong.

Already have this:
```
 dpkg --get-selections | grep lua
liblua5.1-0:amd64				install
liblua5.1-0-dev:amd64				install
liblua5.2-0:amd64				install
liblua5.2-dev:amd64				install
libluabind-dev					install
libluabind0.9.1					install
libluajit-5.1-common				install
lua5.1						install
luajit						install
```

Thank you

**Comment by daniel-j-h** [comment]
Thanks for reporting, looks like this commit from two days ago is making the Lua check too strict:

https://github.com/Project-OSRM/osrm-backend/pull/3011

I just created a pull request over at:

https://github.com/Project-OSRM/osrm-backend/pull/3020

can you try if this works for you by checking out the `fix-strict-lua-check` branch?

**Comment by ankitsoni9989** [comment]
thanks @daniel-j-h that worked for 
`cmake .. -DCMAKE_BUILD_TYPE=Release`

but again in 
`cmake --build .`
I am getting error as:
```
make[2]: *** [CMakeFiles/ENGINE.dir/src/engine/engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/ENGINE.dir/all] Error 2
make: *** [all] Error 2
```
Please let me know if I am missing something.
Thanks

**Comment by daniel-j-h** [comment]
Could you save your build log and upload it as a Gist? I need to see the actual compiler / linker error.

**Comment by ankitsoni9989** [comment]
Hi @daniel-j-h , sorry for a late reply (was out of town).
Here is the link for the build log for "cmake --build ." command

https://gist.github.com/ankitsoni9989/e2648343f6e39859fbbbfaac2049ffed

Thanks

**Comment by ankitsoni9989** [comment]
Hi, I got it running now.
I used the 5.4.0 version tag to install.

Thanks for help
