### ISSUE TITLE
Speed scaling in car profile exceeds maxspeed

### ISSUE THREAD

**Issue by holgersoft** [Project-OSRM/osrm-backend#3023]
The debug map shows for highway=residential + maxspeed=30 a speed of 35km/h.  The car profile has some speed scaling in it (`scaled_speed = result.forward_speed*speed_reduction + 11`) that seems to calculate the final speed.  Should it really be more than maxspeed?  Does that model that no one adheres to speed limits anyway?

**Comment by daniel-j-h** [comment]
Thanks for reporting! This was introduced in https://github.com/Project-OSRM/osrm-backend/commit/40ff7ad999cdea479cb23bf1639d3501a1192cd8 back in 2014.

I talked to @TheMarex yesterday evening and it seems like we're applying a scaling factor plus an offset (the 11 here), which was determined by doing a linear regression fit over real world data. I will remove the offset, grab some real world traces and check again. On my todo list.

**Comment by daniel-j-h** [comment]
Scaling speeds by .8 seems to be good enough as we heavily fine tuned the profile in the last two years.

Tasks:
- [ ] remove the constant offset from all profiles
- [ ] adapt all cucumber tests
- [ ] verify ETA against traces again

**Comment by daniel-j-h** [comment]
@holgersoft if you wait a day or two until the demo server cycled-in new data and nightly builds, you should be able to see a small difference in the speeds reported at http://map.project-osrm.org/debug/#12.21/52.5233/13.3987.

**Comment by holgersoft** [comment]
For `maxspeed=30` the displayed speed is 24 (km/h) now, for `maxspeed=50` it is down from 51 to 40.  Thanks for looking into this.
