### ISSUE TITLE
Segfault with foot/bicycle profile in 5.3.0 upwards

### ISSUE THREAD

**Issue by woodpeck** [Project-OSRM/osrm-backend#3033]
I observed a segmentation violation when trying to osrm-extract Europe for foot.lua or bicycle.lua with all OSRM versions starting with commit 2b466b2fb29c416149b4d881c151349218a63e1e.

The issue is detailed in https://lists.openstreetmap.org/pipermail/osrm-talk/2016-October/001334.html, I'm giving a tl;dr here:
- The problem is always reported as "double free or corruption (fasttop)" and leads to a segfault in osrm-extract on Ubuntu 16.04.
- The problem affects all OSRM versions from commit 2b466b2fb29c416149b4d881c151349218a63e1e on (this means v5.2.7 is the last-known-good release). I read through that commit and couldn't immediately see anything that looks broken.
- The problem does not occur with the "car" profile but it does occur with the "bicycle" and "foot" profiles.
- The problem does not occur with data extracts smaller than ~ 2 GB but it does occur with larger ones. Sadly that made it impossible for me to find a very small input file that would provoke the crash, and any
  "valgrind" debugging was out of the question.

It appears that @oxidase confirmed the problem.

**Comment by oxidase** [comment]
@woodpeck the problem at https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/extraction_containers.cpp#L87-L90 that can be a data-dependent issue. At the moment i am running bisect for edges of the europe foot profile. The current range is 12637448 edges with ~ 6 hours per trial, so i would need ~ 6 days to find a hint.

**Comment by oxidase** [comment]
@woodpeck i have a proposal in fix/3033 . Please could you try the branch and say whether it fixes segfaults for your case. I have found a pretty complicated set of preconditions for the segfault in my case.

**Comment by daniel-j-h** [comment]
Ping - @woodpeck any updates on your side? If this solves your issue feel free to close this ticket.

**Comment by woodpeck** [comment]
Sorry I was slow with this, but have now successfully managed to run osrm-extract under the same conditions that previously caused the crash and it worked. Thank you for following up on this!
