### ISSUE TITLE
bearing and range parameters

### ISSUE THREAD

**Issue by cordovapolymer** [Project-OSRM/osrm-backend#3040]
I'm trying to use bearings to tell osrm about the movement direction, I hope that it would give me better matches. What range parameter is recommended for use for matching car gps tracks?

**Comment by danpat** [comment]
I'm assuming you're using the `match` API, not the `route` API.

By default, the search radius is 5m (OSRM searches 3x the radius).  If your GPS data is accurate to within 2m (i.e. high quality), then this should work well.  With 2m accuracy, all your points should fall within the 15m search radius, and you won't be checking too many unnecessary candidate edges.

Only you know how accurate your GPS data is - I cannot tell you what to set the range to, as I don't know your data.  The defaults are set for fairly high-quality data.

If your GPS data is noisy, you may need to increase the radius above 5m.  Only you know the quality of your GPS data, I cannot suggest what to use.  Do note that the larger you make the radius, the more potential matches there are and the slower the `match` plugin will become.

The `bearing` parameter is useful if you know which direction your probes are heading.  Supplying this parameter will filter out candidate edges that do not match your supplied bearing, and this will speed up the match.  If your `bearing` measurements from your GPS trace are not very accurate and you end up filtering out the edges you want to match to, then you may want to widen the bearing range (it defaults to +/- 10 degrees).  Often +/- 90 degrees works quite well as a general filter.

**Comment by daniel-j-h** [comment]
Here's an additional hint for noisy data: it can make a huge difference to tidy up your traces first.

Have a look: red (raw trace), blue (tidied), green (map matched the tidied trace)
http://bl.ocks.org/anonymous/raw/3434747370929f977db4ba56a91a96cb/
(filtering < .9 confidence matches)

Here's a tool to clean your data:
https://github.com/mapbox/geojson-tidy

**Comment by cordovapolymer** [comment]
@danpat 
Thank you for a complete answer, It deserves a wiki page!
@daniel-j-h cheers, I'm already using geojson-tidy :)

**Comment by daniel-j-h** [comment]
Closing as resolved.
