### ISSUE TITLE
Match http service query

### ISSUE THREAD

**Issue by rorschach1592** [Project-OSRM/osrm-backend#3041]
Hi,
I am currently running OSRM on local machine to use the match service. Also I am passing upto some 3000 gps points to the match service, so used this to run the OSRM machine:
`osrm-routed --max-matching-size=5000 bengaluru_india.osrm`

In this when I pass the query as url (using the requests.get in python or directly pasting the link in the browser), I am getting a strange kind of response from the OSRM api.
What it does is, it sometimes returns me the response instantly and sometimes it keeps running in the background giving no output.
I am passing the coordinates, radius(gps accuracy) and the time-stamps to the OSRM.
sample url :

> http://127.0.0.1:5000/match/v1/driving/77.6740704,12.9736818;77.6739884,12.9736924;77.6740202,12.9736786;77.6740422,12.9736724;77.6740089,12.9736777;77.6739745,12.973697;77.6740328,12.9736777;77.6740701,12.9737027;77.673997,12.9736846;77.6740461,12.973708;77.6739748,12.9737139;77.6733833,12.9735199;77.67500333333334,12.977298333333332;77.6733833,12.9735199;77.67180833333333,12.986011666666665;77.6733833,12.9735199;77.6703056,12.9879882;77.6703201,12.9879688;77.6704149,12.9878427;77.6703398,12.9878145;77.6703981,12.9878868;77.6703149,12.9880122;77.6703149,12.9880122;77.6703149,12.9880122;77.6703149,12.9880122;77.6703149,12.9880122;77.6703149,12.9880122;77.67027333333334,12.986101666666665;77.66987666666667,12.985928333333334;77.66987666666667,12.985928333333334;77.66879833333334,12.985961666666666;77.66844333333333,12.985831666666664;77.66817666666667,12.98564;77.66714333333333,12.985430000000001;77.666955,12.985005000000001;77.666995,12.984725;77.66682833333333,12.983953333333334;77.66662,12.982916666666664;77.66662,12.982916666666664;77.66628666666666,12.982626666666667;77.66649000000001,12.982261666666666;77.66706833333333,12.982221666666666;77.66696,12.982753333333335;77.66794833333333,12.982433333333331;77.66794833333333,12.982433333333331;77.66782666666667,12.982133333333335;77.66692833333333,12.982213333333334;77.66651666666667,12.982106666666668;77.66611833333333,12.98214;77.66579499999999,12.982128333333332;77.66574166666666,12.981601666666666;77.66584833333333,12.981415;77.66608333333333,12.981411666666668;77.667645,12.981125;77.66707333333333,12.981458333333334;77.666908,12.9810921;77.66651666666667,12.981525;77.666908,12.9810921;77.66739666666668,12.981509999999998;77.66775,12.981543333333331;77.66799999999999,12.981428333333334;77.668285,12.981341666666667;77.66791333333335,12.98143;77.66791333333335,12.98143;77.66803833333333,12.981378333333335;77.66805833333333,12.981371666666666;77.66789,12.98148;77.66791166666667,12.981488333333335;77.66769,12.98157;77.66735666666666,12.981598333333332;77.667085,12.98163;77.66695833333333,12.981440000000001;77.666925,12.980858333333334;77.66694666666668,12.980558333333333;77.66704,12.980438333333332;77.66711000000001,12.980739999999999;77.66711000000001,12.980739999999999;77.66716166666667,12.980756666666666;77.66705833333334,12.980641666666667;77.66716,12.980728333333332;77.66658000000001,12.980781666666667;77.66694166666666,12.981351666666667;77.6668097,12.9808926;77.66694166666666,12.981351666666667;77.66646999999999,12.981605000000002;77.66638333333334,12.981186666666668;77.66557166666666,12.981391666666665;77.66544666666667,12.980984999999999;77.66585,12.980758333333332;77.666115,12.980788333333331;77.66608833333333,12.980796666666667;77.66608833333333,12.980796666666667;77.666165,12.980746666666668;77.66601166666666,12.980805000000002;77.66618333333332,12.980838333333335;77.66585166666667,12.980831666666665;77.66601833333334,12.980635;77.665685,12.980348333333332;77.665715,12.980476666666668;77.665715,12.980476666666668;77.665715,12.980476666666668;77.665715,12.980476666666668;77.6667432,12.9807813;77.66572166666667,12.980751666666666;77.66628,12.980938333333333;77.66627,12.980855;77.66602666666667,12.98081;77.66588499999999,12.980783333333333;77.66595000000001,12.980790000000002;77.66570666666667,12.980806666666668;77.66533666666666,12.980816666666666;77.66522,12.981076666666668;77.66524833333332,12.981355;77.66565333333332,12.98143;77.66556333333332,12.981813333333331;77.66555666666666,12.982093333333333;77.66567,12.982271666666668;77.66577000000001,12.982286666666669;77.665775,12.982330000000001;77.665625,12.982408333333334;77.665625,12.982408333333334;77.66538,12.982215;77.66572833333333,12.982294999999999;77.66569,12.9825;77.66581,12.982305;77.66615666666667,12.982249999999999;77.66582,12.982348333333334;77.66585833333333,12.982375000000001;77.66592166666666,12.982336666666667;77.665685,12.982248333333333;77.66553833333334,12.982448333333332;77.66518500000001,12.982701666666665;77.66522,12.982926666666666;77.66522,12.982926666666666;77.66513666666667,12.982916666666664;77.66473333333333,12.983388333333334;77.66450166666667,12.983676666666668;77.66465166666667,12.98359;77.66450166666667,12.983675000000002;77.66460833333333,12.983608333333333;77.66456833333334,12.983635;77.66456166666667,12.983661666666668;77.66463666666667,12.983661666666668;77.66452,12.983703333333334;77.664575,12.983676666666668;77.66454666666667,12.983663333333334;77.66466999999999,12.983600000000001;77.66464333333333,12.983563333333333;77.66465333333333,12.983623333333332;77.66461,12.98356;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.66475,12.983665;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6638037,12.9899505;77.6637688,12.9910198;77.6637688,12.9910198;77.6637688,12.9910198;77.6637688,12.9910198;77.6637688,12.9910198;77.6633087,12.9943496;77.6633087,12.9943496;77.6520484,12.9902242;77.6617681,12.9896064;77.6617409,12.9896092;77.6618821,12.9896543;77.661783,12.9895893;77.6616789,12.9895513;77.6616789,12.9895513;77.6616789,12.9895513;77.6617886,12.9896397;77.6617442,12.9895907;77.6614368,12.9894787;77.6597639,12.9903146;77.662045,12.9903925;77.6620656,12.9903811;77.6620893,12.9903938;77.6620893,12.9903938;77.6620893,12.9903938;77.6620727,12.990388;77.6620889,12.9903914;77.6620889,12.9903914;77.6620889,12.9903914;77.6634119,12.9893754;77.663397,12.9895853;77.6625696,12.989953;77.6679765,12.9817365;77.674462,12.9736815;77.674456,12.9737037;77.6744615,12.9736726;77.6744548,12.9736982;77.6744634,12.973677;77.6744575,12.9737269;77.6744679,12.9736293;77.6733833,12.9735199;77.6744679,12.9736293;77.6733833,12.9735199;77.6744676,12.9736293;77.6744555,12.9737929;77.6744543,12.9737577;77.6744566,12.9736943;77.6744546,12.973796;77.6744628,12.9736668;77.6744682,12.9736296;77.6733833,12.9735199;77.6744637,12.9736788;77.6743588,12.9736643;77.6744576,12.9737355;77.6744555,12.9737747;77.6744626,12.9736703;77.6744611,12.9736799;77.6744635,12.9736293;77.6744607,12.9736808;77.6744679,12.9736293;77.6744608,12.9736894;77.6744555,12.9737822;77.6744542,12.9737929;77.6744605,12.9736755;77.6744561,12.9737617;77.6744558,12.9736952;77.6744573,12.9737967;77.6744549,12.9737668;77.6744681,12.9736286;77.6733833,12.9735199;77.6744618,12.9736664;77.6744626,12.9736817;77.6744679,12.9736293;77.6744605,12.9736755;77.6733833,12.9735199?annotations=true&radiuses=37.0;40.0;36.0;36.0;39.0;40.0;33.0;40.0;45.0;42.0;48.0;783.0;93.4000015258789;783.0;112.30000305175781;783.0;26.0;24.0;28.0;30.0;26.0;28.0;28.0;28.0;28.0;28.0;28.0;0.0;0.0;0.0;46.70000076293945;86.5999984741211;0.0;80.5999984741211;85.69999694824219;72.30000305175781;94.5;89.0999984741211;89.0999984741211;79.0;103.0;95.30000305175781;60.099998474121094;51.20000076293945;51.20000076293945;89.69999694824219;89.0;89.80000305175781;87.5999984741211;99.30000305175781;80.4000015258789;93.30000305175781;79.19999694824219;99.4000015258789;82.5999984741211;64.0;98.9000015258789;64.0;95.4000015258789;50.400001525878906;82.19999694824219;93.0;82.0999984741211;82.0999984741211;97.0999984741211;123.4000015258789;62.5;97.5;62.099998474121094;81.5999984741211;79.4000015258789;56.70000076293945;90.5;74.4000015258789;0.0;79.0999984741211;79.0999984741211;69.4000015258789;78.5;0.0;89.4000015258789;68.0999984741211;40.0;68.0999984741211;79.0999984741211;82.9000015258789;69.80000305175781;53.599998474121094;75.5;75.19999694824219;0.0;0.0;0.0;0.0;0.0;0.0;143.89999389648438;0.0;117.5999984741211;117.5999984741211;117.5999984741211;117.5999984741211;87.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;161.39999389648438;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;126.0;137.89999389648438;136.8000030517578;147.10000610351562;147.60000610351562;158.8000030517578;157.0;0.0;0.0;0.0;123.5999984741211;125.4000015258789;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;20.0;20.0;20.0;20.0;20.0;20.0;20.0;20.0;20.0;20.0;20.0;37.0;37.0;37.0;37.0;37.0;669.0;669.0;754.0;72.0;75.0;61.0;24.0;62.0;62.0;62.0;70.0;75.0;43.0;784.0;39.0;33.0;31.0;31.0;31.0;40.0;30.0;30.0;30.0;23.0;39.0;764.0;764.0;36.0;72.0;40.0;37.0;37.0;61.0;36.0;783.0;36.0;783.0;40.0;48.0;51.0;38.0;48.0;39.0;40.0;783.0;36.0;91.0;55.0;70.0;37.0;40.0;48.0;42.0;36.0;36.0;61.0;57.0;37.0;51.0;72.0;55.0;52.0;40.0;783.0;39.0;37.0;36.0;37.0;783.0&timestamps=0;71;128;173;218;263;308;353;398;443;488;538;4285;4290;4837;4837;4972;5017;5062;5107;5152;5197;5326;5347;5379;5412;5433;5525;5553;5673;5717;5722;5728;5739;5748;5757;5768;5781;5850;5901;5912;5924;5940;5953;6021;6073;6090;6099;6106;6115;6126;6132;6138;6147;6157;6206;6206;6260;6355;6368;6375;6391;6400;6451;6465;6476;6488;6492;6498;6504;6509;6516;6525;6533;6540;6551;6640;6661;6694;6726;6741;6752;6753;6753;6763;6775;6785;6796;6808;6823;6859;6871;6886;6893;6899;6911;7002;7018;7106;7152;7166;7222;7253;7253;7259;7265;7270;7274;7280;7285;7292;7300;7307;7312;7318;7323;7328;7336;7351;7360;7431;7444;7465;7481;7491;7503;7509;7515;7521;7530;7540;7548;7556;7651;7684;7701;7719;7736;7749;7766;7779;7796;7809;7828;7845;7857;7870;7886;7899;7920;7936;7959;8320;8346;8391;8770;8942;8985;9256;9293;9905;10394;10541;11284;11326;11358;11584;11658;11681;11946;12054;12076;12353;12604;12657;12679;12778;12935;12960;13376;13497;13639;13843;14429;14494;14606;14648;14693;14738;14783;14792;14918;14963;14983;15008;15026;15061;15143;15188;15298;15424;15504;15525;15801;15829;15915;15954;16016;16404;16405;16495;16539;16584;16629;16764;16809;16854;17238;17418;17489;17580;17623;17668;17714;17758;17803;17849;17894;18119;18164;18209;18254;18299;18344;18389;18479;18524;18569;18614;18659;18704;18749;18794;18839;18884;19064;19109;19199;19289;19469;19514

**Comment by TheMarex** [comment]
> What it does is, it sometimes returns me the response instantly and sometimes it keeps running in the background giving no output.

That is not under load right? Only thing that comes to mind that might explain the sometimes long query times is that the index that translates from coordinate to node in the graph (StaticRTree) which is located on disk and mmaped to RAM. On cache hit these queries would be extremely fast, on miss it could be very slow.

You can try to add some logging output around this block https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/plugins/match.cpp#L129-L153 to confirm the suspicion.

**Comment by daniel-j-h** [comment]
Stale. Feel free to re-open if you have anything to add.
