### ISSUE TITLE
Match http service - non OSM road network

### ISSUE THREAD

**Issue by gac55** [Project-OSRM/osrm-backend#3044]
Hi all,

I have a series of GPS polylines that I wish to map to an underlying road network. 

In this case, I will not be using the OSM road network, but a GeoJSON file. I can access the polylines from this network quite easily. Is it possible to make use of the [service match](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-match) with this non-OSM underlying network?

Many thanks!

Gerry

**Comment by daniel-j-h** [comment]
OSRM is a routing engine working on OSM data.

The transformations you can see here and the full pipeline works on OSM base maps:
https://github.com/Project-OSRM/osrm-backend/wiki/Graph-representation#graph-edge

If you want to run OSRM on a road network in any other format than OSM, you have to convert this file format into the OSM format: .osm.xml or .pbf with the OSM tagging scheme.

**Comment by danpat** [comment]
@gac55 You can try something like https://www.npmjs.com/package/geojson2osm

OSRM only knows how to construct the road network from OSM-structured data, you'll need to transform your GeoJSON into well-connected OSM form first, *or* if your original data is something else, convert *that* to OSM form and skip the GeoJSON intermediary.

The main difference is that the OSM data ensures that roads are well-connected - with GeoJSON data, there's no sense of connectivity between linestrings.  Do shared coordinates mean the roads touch, or is it an overpass?  Same for linestrings that cross.  The GeoJSON file format is not super-well suited to representing road connectivity.

**Comment by danpat** [comment]
pgRouting provides the `pgr_create-topology` function that uses geometry information to create the graph topology.  This forms a similar role to `geojson2osm` in the previous comment.

http://docs.pgrouting.org/2.3/en/src/topology/doc/pgr_createTopology.html#pgr-create-topology

At this stage, I don't think there's anything actionable here for us - we will continue to only parse OSM-form data.  External tools can fill the gap of converting geometry data into the OSM topography we need.

@daniel-j-h we have no internal use-case for file format adapters, but do you think it's worth keeping this ticket open in case someone has the energy to contribute file format converters?

In some ways, it might be cool to be able to do `osrm-extract -p profile.lua custom_streets.shp`, but we have no use for it at this stage.

**Comment by daniel-j-h** [comment]
I don't see a clean way of doing this with the current extractor design.

**Comment by daniel-j-h** [comment]
Closing as not actionable for us.
