### ISSUE TITLE
segmentation fault while using parameter geometries=geojson

### ISSUE THREAD

**Issue by bvbever** [Project-OSRM/osrm-backend#3050]
I have noticed that while using the parameter `geometries=polyline`(default)  when a route can't be found you'll get the answer `{"message":"Impossible route between points","code":"NoRoute"}`. So far so good.
But when I change the parameter to `geometries=geojson` while using the same coordinates, I get an 
`segmentation fault` error.

I can't give an example because the demoserver doesn't work. (Not my fault, It was before I discoverd this issue on our own routingservers). I can tell you where to find one: [issue 1968](https://github.com/Project-OSRM/osrm-backend/issues/1968) =>`http://router.project-osrm.org/route/v1/driving/-0.34655726,49.1716783;-0.34673758,49.17131276`
should give the code `NoRoute`. When adding `geometries=geojson`, it should crash...

**Comment by daniel-j-h** [comment]
While the demo server is down and we're waiting for it to come up again I tried to reproduce it.

I grabbed http://download.geofabrik.de/europe/france/basse-normandie.html  ran osrm master and the query you posted with and without `geometries=geojson`:

    http 'http://localhost:5000/route/v1/driving/-0.34655726,49.1716783;-0.34673758,49.17131276?geometries=geojson'

both results in

```json
{
  "code": "NoRoute",
  "message": "No route found between points"
}
```

Same with master or the 5.4 branch.

**Comment by danpat** [comment]
@bvbever What version of OSRM are you running?

**Comment by bvbever** [comment]
v5.3.0
The result is 'message: Impossible route between points'. It is perhaps not the same as 'No route found betweeen points' ?

**Comment by bvbever** [comment]
with `https://router.project-osrm.org/route/v1/driving/-4.482421875,40.58058466412761;-75.498046875,39.90973623453719` => `{"message":"Impossible route between points","code":"NoRoute"}` When adding `geometries=geojson` => still ok.
I can not reproduce it with the current master branch...
