### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by dmalisani** [Project-OSRM/osrm-backend#3051]
Error 404 
try:
curl https://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true&alternatives=true

Demo in home page neither works

**Comment by daniel-j-h** [comment]
Yep, it's currently processing a new planet file.

The demo server is running nightly builds and the latest planet file; we don't give any guarantees.

**Comment by perliedman** [comment]
While I fully understand that the demo server will be down every now and then, and see not issue with that in itself, it would be _immensely_ helpful if the 404s, 503s, 500s and whatever other error messages from the server included the `Access-Control-Allow-Origin` header: for a browser client, it's not possible to determine _anything_ more than that an HTTP error occured: _not even the HTTP status code_ (http://stackoverflow.com/a/6734427/890).

Including `Access-Control-Allow-Origin` in the error response would make it possible to make better error messages, and hopefully reduce the amount of issues like this one (I get a ton of them for LRM as well).

**Comment by daniel-j-h** [comment]
At the moment the `osrm-routed` HTTP binary adds those headers; this has to happen in front of it already. cc @freenerd
