### ISSUE TITLE
"At the end of the street turn left" instruction provided in Russian

### ISSUE THREAD

**Issue by IknowJoseph** [Project-OSRM/osrm-backend#3057]
Openstreetmap.org's routing is providing the above instruction in Russian:

http://www.openstreetmap.org/directions?engine=osrm_car&route=38.25458%2C-76.96989%3B38.24909%2C-76.96200#map=17/38.25130/-76.96504

![screenshot from 2016-10-14 13-36-22](https://cloud.githubusercontent.com/assets/1896882/19387615/3931914e-9213-11e6-9622-8138250e81fb.png)

**Comment by daniel-j-h** [comment]
Thanks for reporting,

osrm-backend only returns identifiers such as "Turn", or "EndOfRoad" - generating (potentially localized) text instructions is done by clients. I skimmed the OSM site's code and it looks like it's done here:

https://github.com/openstreetmap/openstreetmap-website/blob/e3357b27e61c3ee4f4cf51c87fdc94deeaaa7c6f/app/assets/javascripts/index/directions/osrm.js#L106

Please open a ticket with them.

Closing as not actionable on our side.
