### ISSUE TITLE
Travis cache still growing

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3062]
@daniel-j-h reported that our cache breached the 2GB limit again. That means there must be something that does not get cleaned up. We can investigate this by sshing into a travis box.

**Comment by daniel-j-h** [comment]
For the record the Travis cache for master grew to 3 GB again - timespan: ~6 days.

**Comment by daniel-j-h** [comment]
@TheMarex is there a reason for keeping this open?

Caches for master seem to be stable at roughly 2 GB - which is more or less what we expect with 8 builds and a ccache limit of 8 * 256 MB + caching Cucumber datasets. I'm surprised it's not higher actually.

**Comment by TheMarex** [comment]
No, if this works now that is great. :+1:
