### ISSUE TITLE
Rip out Fingerprint logic

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3063]
Since we enforce versioning now and the checks are not even enforced over all files we generate, I think we should remove this legacy code.

**Comment by daniel-j-h** [comment]
Context: as a basic check for data file version mismatched there is a fingerprint mechanism in place which works as follows: we generate a hash over the source files (think some .h, .cpp) files and write it as first couple of bytes to the data files we dump out (i.e. *.osrm* files).

Then when reading these files in again, we read in the first couple of bytes (the fingerprint) and make sure they're equal to the current version's fingerprint: this is a simple check to compare two hashes.

Searching for `FingerPrint::GetValid` should reveal all places where we check the fingerprint, e.g. see

https://github.com/Project-OSRM/osrm-backend/blob/8ed6bb8a1b2c21819822da714b81a4f7b72bde58/include/util/graph_loader.hpp#L38-L46

In [CMakeLists.txt](https://github.com/Project-OSRM/osrm-backend/blob/8ed6bb8a1b2c21819822da714b81a4f7b72bde58/CMakeLists.txt#L63-L68) we let CMake generate this fingerprint hashing some .h, .cpp files (check cmake/FingerPrint-Config.cmake).

Here is the custom Fingerprint Type:
- https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/fingerprint.hpp
- https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/fingerprint_impl.hpp.in

**Comment by TheMarex** [comment]
Since we refactored this now into a nicer abstract file handling I think we should really move in 5.6.0 on simplifying this a lot. Currently it is impossible to tell if a change will create a new fingerprint or not. This already bit me during deployments of RC4 to RC5: I knew the file format was compatible but the Fingerprint changed anyway.

This could bite us even more if we release a patch release that changes the fingerprint accidentally.

Since we already employ semantic versioning and encode data file compatibility over that we should do replace the Fingerprint with the version number check (equal major and minor version).

/cc @daniel-j-h @danpat

**Comment by danpat** [comment]
I think there's a path to keep the fingerprint - we just need to be smarter about what's included in its fingerprint calculation.  It's getting easier as we refactor the I/O code.

We could do something like the following:

  1. Copy `src/storage/storage.cpp` to a temp file
  2. Run `gcc -E storage.cpp.tmp` (this works with clang and gcc)
  3. Filter that file and remove any expanded includes from outside our source path
  4. MD5sum the result

This would capture everything that could change on the I/O side.  It's still sensitive to changes in spacing, comments, etc, but perhaps we could also include a "normalize" step using clang-format, and strip comments.

Not sure how this would work with with MSVC.  It's also complicated.  The scheme above doesn't capture the files not used by `osrm-routed`.

On the plus side, it's automated.

**Comment by TheMarex** [comment]
I don't think the added safety check during development is really worth keeping this logic and even extending it. During development you need to know what you are doing anyway, when in doubt reprocess.

Our testing infrastructure does not rely on the fingerprint at all. It is even more primitive and uses the SHA of the binaries.

For releases we have to be able to trust our versioning decision. So I don't think it is a problem to rely on our semantic versioning guarantees, that we already have baked into tools like s3osrm and such.

**Comment by TheMarex** [comment]
Was done by @danpat in #3467.
