### ISSUE TITLE
Make Trip Features uniquely valid

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3067]
Currently, the outcome of our trip tests in `features/testbot/trips` is random. Since all tests use roundtrips of the same length, the success / failure of the tests is purely random.

Trips can fail in any random situation, making adjustments to the fixtures necessary. We should replace all tests with checks that have unique results.

**Comment by chaupow** [comment]
should be solved when fixing https://github.com/Project-OSRM/osrm-backend/issues/1939

**Comment by daniel-j-h** [comment]
What's blocking here? Is this resolved by now?

**Comment by MoKob** [comment]
If the first coordinate is always chosen as the result, this should be resolved.
