### ISSUE TITLE
Starter Tasks that could use more details in the description

### ISSUE THREAD

**Issue by ghoshkaj** [Project-OSRM/osrm-backend#3068]
Some starter tasks are pretty vague about how to implement a solution. A good example of starter-task is here: https://github.com/Project-OSRM/osrm-backend/issues/3027 and https://github.com/Project-OSRM/osrm-backend/issues/2841. Here's a list of currently vague starter tasks:
1. Debug tiles aren't always fetching all visible geometry near tile edges #3064
2. ~~Rip out Fingerprint logic #3063~~
3. Travis cache still growing #3062
4. Log peak STXXL/memory usage #2445
5. Keep waypoints on the left/right #2201
6. ~~Importing a .osm file with no name tags breaks osrm-extract #2045~~
7. The Big Cleanup III #1971
8. Add option to disable hint_data output. #1789
9. Cycles dont route over ferries #1675

cc @danpat

**Comment by daniel-j-h** [comment]
We resolved half of these already and added more docs to the other half. Closing here as not actionable. Feel free to open another ticket or ping on specific tickets.
