### ISSUE TITLE
Parallelize Turn Penalty Updates

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3070]
We provide two ways for ingesting real-time'ish data: a csv file for 1/ updating edge weights and 2/ a csv file for updating turn penalties. Both files are getting ingested by `osrm-contract` - specifically this happens in the [contractor.cpp](https://github.com/Project-OSRM/osrm-backend/blob/8ed6bb8a1b2c21819822da714b81a4f7b72bde58/src/contractor/contractor.cpp) file.

In https://github.com/Project-OSRM/osrm-backend/pull/2412 we made 1/ faster by doing more in parallel and using a flat-map + binary search approach instead of a hash table.

Now the same has to be done for loading turn penalties.

Tasks:
- [x] I can't find docs for loading turn penalties: get yourself familiar with how updating turn penalties works and write docs for the Wiki (maybe Traffic page)
- [ ] Measure / profile where we spent the most time, what should be prioritized
- [ ] Follow the contractor's code path for updating edge speeds: updating turn penalties has to be adapted to this more or less 1:1
- [ ] parallelize / flat-map turn penalty updating similar to edge weight updating
- [ ] Measure speedup

cc @karenzshea

**Comment by karenzshea** [comment]
Also included in this will be a refactor to use boost's [flat_map](http://www.boost.org/doc/libs/1_58_0/doc/html/boost/container/flat_map.html)
