### ISSUE TITLE
Make U-Turn a type (U-Turn left vs U-Turn right)

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3077]
Right now, `u-turn` is a direction modifier, rather than a turn type itself.

We should consider making `uturns` a turn-type:
- we could then indicate whether a u-turn is to the left or to the right (consider left-sided driving, or maybe special cases)
- we could free up the `uturn` modifier to be `invalid` and to better describe invalid turns
- having a turn-type for u-turns removes ambiguity for having `turn uturn` and `continue uturn`.

Due to the removal of `uturn` as a modifier, and since it's not really well announed as a `turn`, this change has to be considered an API change and could only be implemented with the next major version.

**Comment by TheMarex** [comment]
The original need for this was due to left/right hand driving. This was fixed [by adding `driving side`](https://github.com/Project-OSRM/osrm-backend/pull/4649), so I don't think we need this anymore.
