### ISSUE TITLE
move turn-discovery to tools / rip it out completely?

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3079]
The dedicated file `turn_discovery.hpp/.hpp` is only providing a single function. The function should be integrated into a greater utility set for guidance.

The necessity for finding previous turns is mainly due to how lanes are stored in OSM/OSRM.

What we often see is situations where the lanes are drawn up to a traffic light, but not to the intersection.

```
                 |     |
------------ ---
    -^       |
------------ ---
    -v       |
------------ ---
                 |     |
```

Since we don't compress these segments ([see here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/graph_compressor.cpp#L114-L116)), the above situation ends up like this:

```
         d
         |
a  - b - c
         |
         e
```

And `turn:lanes:forward = 'left|right` only on `ab`, `bc` not showing any lanes.

When we want to have turn-lanes for `b-c` to `c-d` or `c-e`, we need to compute the previous intersection. If we can find a way to correctly propagate the turn lanes to the correct locations ahead of time, we could potentially get rid of this part completely.

**The part of ripping it out completely could be considered a bit too advanced to be a starter task.**

**Comment by TheMarex** [comment]
This is obsolete since we now compress traffic lights.
