### ISSUE TITLE
prioritize cycleways in bike routing

### ISSUE THREAD

**Issue by emmexx** [Project-OSRM/osrm-backend#308]
From what I understand looking at the code, osrm is not giving an advantage to cycleways (highway=cycleway or highway=* AND cycleway=*) when calculating edge weights.
As a consequence I noticed that almost always osrm chooses a "normal" street instead of the cycleway that runs parallel to it.

I don't know enough the algorythm used to choose a way or another but, from what I understand, in the current version of osrm only the speed is used as a weight edge.
Is there any plan to change this behaviour?

thank you
   maxx

**Comment by daniel-j-h** [comment]
Outdated; take a look at the bicycle.lua profile.
