### ISSUE TITLE
Create a toolkit for combining steps

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3080]
Every route coming from OSRM that includes step undergoes some post-processing.

During this post-processing we can decide to collapse multiple steps into a single turn instruction.
In that process, we call the functions `elongate` ([here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/guidance/post_processing.cpp#L562-L593)) and `forwardStepSignage` ([here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/guidance/post_processing.cpp#L51-L59)).

Since our RouteSteps contain more and more data, we should move these functions out into a general toolkit to combine steps.

I imagine a function that takes as input two steps `A` and `B` as well as a combination scenario. This scenario should describe which one of the two will be the location of the turn and which meta-data to preserve.

E.g. in

```
 a - b - c - e
     |   |
     f   d
```

When turning from `d` via `c` and `b` onto `a`, we might end up with two steps. The first indicating a turn and the second indicating a new name (since the intersection b-c can belong to any of the roads).

In this situation we would like to keep the location of the first turn (`d-c` onto `c-b`) but want to have the name of `c-b to`a-b`which will in the end return`turn left onto `a-b`.

To improve readability of post-processing, having a clear toolkit function for this would help a lot.

**Comment by MoKob** [comment]
As a first step, https://github.com/Project-OSRM/osrm-backend/pull/3261 allows to test for turn locations to ensure the correct turn location is announced.

**Comment by TheMarex** [comment]
`elongate` and similar functions should be made superfluous by not generating `RouteStep` objects for these intermediate instructions in the first place.
