### ISSUE TITLE
Refactor Obvious Turn Discovery

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3081]
The code to find which of the possible turns at an intersection could be considered `obvious` has grown a lot and needs to be refactored (see [here](https://github.com/Project-OSRM/osrm-backend/blob/9af00b19256c51de3d700024357199287e6b8ad3/src/extractor/guidance/intersection_handler.cpp#L377-L711))

I advice being very careful, though, since the discovery of obvious turns affects close to every turn scenario and is a very central component of the guidance process. Be advised that things will fall apart when you change it.

The main goal of obvious turn discovery is, as stated in the name, to decide which turn is obvious.
At a first glance, if you are on a road and there is a road with the same name, staying on it should be obvious.

But you don't always connect roads with same names, still passing straight over an intersection should be considered obvious.

At the same time, you can have intersections where the same road is actually not the obvious one to follow (e.g. [here](http://www.openstreetmap.org/#map=18/52.54578/13.33237)).

In general, we need to consider a lot of different factors like turn angles, road classes, names, other valid turns.... Therefore, the complexity has grown to where it is now. It has grown, however, and could be reduced and cleaned-up considerably.

**Comment by daniel-j-h** [comment]
- [ ] `findObviousTurn` should return an `boost::optional<size_t>` to indicate if an obvious turn was found `boost::make_optional(index)` or not `boost::none`. Call sites then do `if (obv) use(*obv);`.
