### ISSUE TITLE
Ascii-Art into tests for better readability

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3083]
With the improved cucumber syntax, we introduced the possibility to add ASCII art to our cucumber features (https://github.com/Project-OSRM/osrm-backend/tree/master/features/guidance).

We should make use of this to better illustrate the different tests.

**CAREFUL: Be sure only to replace, and don't add any spaces. Otherwise turn angles can be modified and thresholds can be missed**

We have many files that can be checked for their visual appearance and can be improved:
- [ ] advanced-lanes.feature
- [ ] continue.feature
- [ ] motorway.feature
- [ ] rotary.feature
- [ ] suppressed.feature
- [ ]  ~~anticipate-lanes.feature~~ already done
- [ ] dedicated-turn-roads.feature
- [ ] new-name.feature
- [ ] roundabout-bike.feature
- [ ] trimming.feature
- [ ] bicycle-sliproads.feature
- [ ] destination-signs.feature
- [ ] notification.feature
- [ ] roundabout-turn-bike.feature
- [ ] turn-lanes.feature
- [ ] bridges_and_tunnels.feature
- [ ] end-of-road.feature
- [ ] perception.feature
- [ ] roundabout-turn.feature
- [ ] turn.feature
- [ ] bugs.feature
- [ ] fork.feature
- [ ] post-processing.feature
- [ ] roundabout.feature
- [ ] collapse-detail.feature
- [ ] intersections.feature
- [ ] ramp.feature
- [ ] staggered-intersections.feature
- [ ] collapse.feature
- [ ] merge.feature
- [ ] rotary-bike.feature
- [ ] suffix-changes.feature

The goal here is turn a thing like

```
"""
a           b
"""
```

into 

```
"""
a - - - - - b
"""
```

Due to popular demand, I recommend a restriction to the following set of characters:

`,.'*<>^/\|-_+{}:;=`

**Comment by emiltin** [comment]
Might be useful with a small guideline (ie examples) on what's the recommended style to use, so we don't end up with too many weird ascii chars.

**Comment by danpat** [comment]
> too many weird ascii chars.

Do we support UTF-8?  There are so many possibilities:

⑂⑃↱↲↳↴↵↶↷↰⇄⇇⇈ 🚏

**Comment by emiltin** [comment]
We might run into issues with how different editors, github, travis, etc. display UTF symbols. Some of the above symbols result in incorrect horizontal alignment in both textmate and sublime, even with fixed width fonts:

TextMate 1
![screen shot 2016-10-19 at 08 23 10](https://cloud.githubusercontent.com/assets/66034/19507833/996230ee-95d5-11e6-80b1-35f32f2b2ce2.png)

SublimeText
![screen shot 2016-10-19 at 08 23 20](https://cloud.githubusercontent.com/assets/66034/19507826/8e37cf4e-95d5-11e6-9024-b72931d70d07.png)

Browser:
```
................
🚏.🚦.⛴.🚷.🚳.⛔.
................
⑂⑃↱↲↳↴↵↶........
```

For this reason I would recommend staying with standard characters. 
Standard symbols are also much easier to write, which I think also matters.

**Comment by daniel-j-h** [comment]
No UTF-8 symbols, no emojis - let's keep it simple, boring and maintainable.

**Comment by TheMarex** [comment]
I don't think it makes sense to have an issue open for this. It is general practice now for writing new cucumber tests and most of the old tests have been migrated.
