### ISSUE TITLE
Roundabout Handler Seems to Break / Assertion on Demo Server

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3085]
We are seeing an assertion on the demo server:

```
[assert] src/engine/guidance/post_processing.cpp:265
in: void osrm::engine::guidance::{anonymous}::closeOffRoundabout(bool, std::vector<osrm::engine::guidance::RouteStep>&, std::size_t): leavesRoundabout(steps[1].maneuver.instruction) || steps[1].maneuver.instruction.type == TurnType::StayOnRoundabout || steps[1].maneuver.instruction.type == TurnType::Suppressed || steps[1].maneuver.instruction.type == TurnType::NoTurn
```
triggering https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/guidance/post_processing.cpp#L262-L265.

This route seems to trigger the issue: `https://router.project-osrm.org/route/v1/driving/20.027888,50.079578999999995;19.94622,50.068037999999994?alternatives=false&overview=full&steps=true`

Needs investigation to find the roundabout in question.

**Comment by MoKob** [comment]
Turned out that this was only a broken assertion. Fix in #3098

**Comment by daniel-j-h** [comment]
Context for @TheMarex - https://github.com/Project-OSRM/osrm-backend/pull/3098 isn't merged yet, that's why you're still seeing this assertion.

We should resolve this asap.

**Comment by daniel-j-h** [comment]
This just landed in master.
