### ISSUE TITLE
Change GetUncompressed* methods of Datafacades to return views instead of copies

### ISSUE THREAD

**Issue by jakepruitt** [Project-OSRM/osrm-backend#3094]
After https://github.com/Project-OSRM/osrm-backend/pull/3093 is merged, which turns the internal representation of geometries and weights into separate vectors, and @danpat finishes https://github.com/Project-OSRM/osrm-backend/issues/3072, which will consolidate the underlying datatypes for shared memory and internal memory, we will be able to return a view of the internal arrays instead of copying values out and returning the copies.

cc/ @TheMarex

**Comment by SiarheiFedartsou** [comment]
Seems to be done in https://github.com/Project-OSRM/osrm-backend/commit/be123cd72f4cfb994ce87c7a96dd7cd9832471a7
