### ISSUE TITLE
Modifying the graph to support destination tags

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3096]
Certain OSM tags mean "you can route into here, or out of here, but not through here".  This includes things like `access=destination` (no-through-road, local traffic only) and `access=private`.

One approach for implementing this is to add a large speed penalty to the areas.  With our current implementation, this means that ETAs become incorrect.

When #77 is merged, we will have the ability to put a routing penalty on these areas, without affecting the ETA.

However, it's likely that there will be some problems - two markers dropped near the ends of a long alley may prefer to route around on the faster main roads, rather than taking the heavily penalized no-through-road.

An alternative approach would be to modify the graph structure.  When a way (or cluster of ways) has restricted access, we could make a N copies of the restricted sub-graph, and attach each copy to the main road network by only one access point.

For example, an alley with 2 entries but restricted access would be transformed into something like this (i.e. two dead-end overlapping ways):

<img width="524" alt="screen shot 2016-10-18 at 5 49 05 pm" src="https://cloud.githubusercontent.com/assets/1892250/19500608/0ab9568e-955c-11e6-8d93-6a8278c4dec3.png">

This would prevent through routing, but allow routing within, in, and out, with no special weighting required.

For a more complex restricted region, like a private subdivision, there would be one copy of the restricted road network per access point from the main road network.

Problems to solve:
  1. How to identify the routable sub-regions?
  2. How to handle nested versions of these?
  3. How to handle PhantomNode snapping (suggestion: attempt routing to/from all copies).
  4. Evaluate how common this is and how much bigger the graph would get.

**Comment by daniel-j-h** [comment]
cc @lonvia

**Comment by MoKob** [comment]
To summarise from chat:

we don't need to penalise the segment within these regions. All we need to do is to identify entry/exit points.
If we use penalties for entry/exit (#77 needed for this) turns, we essentially implement the approach @danpat was describing without actually destroying the connectivity in the graph and without copies.

We will still see some strange behaviour (e.g. preferring to stay in an area if access=destination is in the start and end region, but I feel the problem should be rare).

**Comment by danpat** [comment]
@MoKob pointed out that one of the main problems is that adding the copies creates a potential O(n²) number of routes to test (each entry/exit combination).  This is only practical for very small cases (alleys).  This impacts not just routing, but other plugins like map-matching and the table.

Closing this as informative, but not practical.
