### ISSUE TITLE
Refactor Basic Turn Assignment

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3100]
Two functions describe basic turn assignments. They are what is used as the most common way of assigning turns.

The implementation for both is at https://github.com/Project-OSRM/osrm-backend/blob/3f0f0e306b3c2ee5eada6512c3ce3ab00b1b0460/src/extractor/guidance/intersection_handler.cpp#L48-L167.

Both `findBasicTurnType`, the instruction used for all standard turns that are not obvious, in a fork or other distinct situation and `getInstructionForObvious` have grown quite a bit and require refactoring.

FindBasicTurnType ([here](https://github.com/Project-OSRM/osrm-backend/blob/3f0f0e306b3c2ee5eada6512c3ce3ab00b1b0460/src/extractor/guidance/intersection_handler.cpp#L48-L68))
- [ ]  should consider our name heuristic [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/guidance/toolkit.hpp#L158)
- [ ] and handle on/off ramp correctly (currently hacked into [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/turn_analysis.cpp#L101-L107)

FindInstructionForObvious should see a general refactor.

**Comment by TheMarex** [comment]
The links in the issue description are broken and the task is described in an actionable way. Closing this as non-actionable.
