### ISSUE TITLE
Revise Through Streets

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3102]
The discovery of [definition](https://github.com/Project-OSRM/osrm-backend/blob/3f0f0e306b3c2ee5eada6512c3ce3ab00b1b0460/include/extractor/guidance/intersection_handler.hpp#L86)/[implementation](https://github.com/Project-OSRM/osrm-backend/blob/3f0f0e306b3c2ee5eada6512c3ce3ab00b1b0460/src/extractor/guidance/intersection_handler.cpp#L345-L375) requires revision.

Currently it does not consider our [same-name-heuristic](https://github.com/Project-OSRM/osrm-backend/blob/3f0f0e306b3c2ee5eada6512c3ce3ab00b1b0460/include/util/guidance/toolkit.hpp#L158) [here](https://github.com/Project-OSRM/osrm-backend/blob/3f0f0e306b3c2ee5eada6512c3ce3ab00b1b0460/src/extractor/guidance/intersection_handler.cpp#L367).

In addition, it should be implemented as an std::algorithm.
We could also rework it into a more general function that can find connections between any two roads in an intersection.

Knowledge about connections in the ways can become handy in other turn scenarios.

**Comment by daniel-j-h** [comment]
The Sliproad Handler has its own through-street implementation:

https://github.com/Project-OSRM/osrm-backend/pull/3199/files#diff-1f6e065aa1c27c5f49099d439a0f5d7fR316

After this issue is resolved, we should rip out the custom one for the Sliproad handler.

**Comment by daniel-j-h** [comment]
- [x] implemented the [same name heuristic](https://github.com/Project-OSRM/osrm-backend/blob/f88ac989ea3003d19ba10f34bff7a1e1e497b097/src/extractor/guidance/intersection_handler.cpp#L363) in https://github.com/Project-OSRM/osrm-backend/pull/2945

**Comment by TheMarex** [comment]
The major issue mentioned here was addressed in #2945, the only remaining issue is a refactor. The linked code in the slip road handler only seem marginally related and quite custom. I don't think it pays off to try to refactor this specific case. A more general refactor could help, but that is out of scope of this issue.
