### ISSUE TITLE
Refactor Roundabout Handler

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3108]
The roundabout handler should see some refactoring.

We should tackle the following tasks:
- [x] make handler work for left sided driving and ride sided driving (it might suffice to simply use turn angles in mathematical negative direction over positive direction) ([possible impact here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/roundabout_handler.cpp#L103)
- [ ] remove own [coordinate calculation](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/roundabout_handler.cpp#L184-L189) in favour of https://github.com/Project-OSRM/osrm-backend/pull/2779
- [ ] handle traffic lights / sliproads on exits (https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/roundabout_handler.cpp#L169)
- [ ] ~~maybe throw in https://github.com/Project-OSRM/osrm-backend/issues/2943~~
- [ ] revisit distinction criteria ([here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/roundabout_handler.cpp#L199-L209))
- [ ] refactor roundabout type detection [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/roundabout_handler.cpp#L214-L357)
- [x] refactor roundabout handling [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/roundabout_handler.cpp#L359-L439)
- [x] finally split up into enter/exit roundabout instruction
   - cleaner handling in post-processing
   - far less error prone
   - actual location of exit will be known to application
   - distances / names can be fixed: rotary_name can be removed

**Comment by TheMarex** [comment]
Description of the items here is either too unspecific to warrant an issue, outdated, or covered by other issues. Closing as non-actionable.
