### ISSUE TITLE
Refactor Sliproad Handler

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3109]
A sliproad is supposed to be s small road at a turn.

| satellite | roads |
| --- | --- |
| <img width="300" alt="screen shot 2016-10-19 at 17 19 30" src="https://cloud.githubusercontent.com/assets/12932279/19525162/549df9ac-9620-11e6-8274-98f740ead390.png"> | <img width="300" alt="screen shot 2016-10-19 at 17 19 59" src="https://cloud.githubusercontent.com/assets/12932279/19525167/56fc0554-9620-11e6-90db-fb7de8b4a638.png"> |

These small roads are not supposed to end up as a normal turn.

We should revisit how the sliproad handler works and clear it up considerably.
The handler assigns a sliproad turn type to enter the sliproad, which is an indication to the postprocessing to always collapse the next two turns.

Right now the code is very complicated and bad to read. Adding a clearer structure based on std::algorithms and clearer functions could improve it a lot.

In addition, we should revisit what we consider a sliproad and make sure not to detect normal intersections as false positives.

**Comment by daniel-j-h** [comment]
First pass is over at https://github.com/Project-OSRM/osrm-backend/pull/3199.
