### ISSUE TITLE
Make Compilation / Runtime Requirements Explicit

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3111]
@TheMarex @springmeyer let's make requirements explicit.

Both in the Wiki / Building Instructions but also e.g. in the CMakeLists:
- CMake version
- Boost version
- stxxl, luabind (interaction with Boost since luabind is outdated)
- gcc, clang
- soon v8
- what else?

Idea here: require latest Ubuntu LTS +.

Tasks:
- [x] figure out deps ^ versions from latest Ubuntu LTS
- [x] make clear in Wiki / Building Instructions
- [x] enforce in CMakeLists / warn user if unsupported
- [ ] start using new features (e.g. https://github.com/Project-OSRM/osrm-backend/issues/2859 would be resolved instantly by using a recent irange)

**Comment by springmeyer** [comment]
@daniel-j-h are you proposing dropping support for ubuntu older than xenial? Or are you proposing putting more effort into docs and work targeting xenial?

**Comment by daniel-j-h** [comment]
Both (if you want v8-based profiles).

v8 will be an optional compile-time dependency; mason should bundle the Ubuntu 16.04 LTS dependencies so that we don't have to support multiple v8 versions and users can still compile osrm without the need for mason.

**Comment by daniel-j-h** [comment]
Just updated the Wiki instructions to the current requirements and made them also explicit in the CMakeLists. Closing here as resolved for now.
