### ISSUE TITLE
Turn restrictions not working.

### ISSUE THREAD

**Issue by gorn** [Project-OSRM/osrm-backend#3115]
This way http://www.openstreetmap.org/directions?engine=osrm_car&route=49.74339%2C13.38016%3B49.74401%2C13.38105#map=19/49.74363/13.38097 is technically forbidden, because the turn to left is prohibited on the crossing when coming from west. Please note, that the turn restriction is more then year old, so there should be no issue with data. I have tried to "repair" it few minutes ago by creating "turnlanes" relations, but the restriction http://www.openstreetmap.org/relation/4552349 should be sufficient to forbid this.

**Comment by daniel-j-h** [comment]
There is an

`except=bicycle;hgv;moped;motorcar;psv`

on

http://www.openstreetmap.org/relation/4552349

allowing cars go make the turn.

**Comment by danpat** [comment]
Closing this as not-an-OSRM bug.

**Comment by gorn** [comment]
I am really sorry, I was not aware of that tag. It is clearly data problem then. My apology.

**Comment by daniel-j-h** [comment]
No worries at all :)

For the record, here is OSRM's internal view of the road network. Maybe that helps:
http://map.project-osrm.org/debug/#12.21/52.5233/13.3987
