### ISSUE TITLE
Update Taginfo / Make Validation Script Smarter

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3117]
We're missing `except=motorcar, ...` from [here](https://github.com/Project-OSRM/osrm-backend/blob/ab1a9271c8c163a1bd514e17489cd35c6db22dc9/profiles/car.lua#L15) in `taginfo.json` resulting in the tag not showing up in http://taginfo.openstreetmap.org/projects/osrm. There are probably more of these. Needs to be checked and the taginfo file needs to be updated.

**Comment by daniel-j-h** [comment]
cc @joto @karenzshea @miccolis - our taginfo file is missing some tags and also targets the car profile.

This needs to change before we can filter the planet with tools based on the `taginfo.json` file.

**Comment by emiltin** [comment]
what about a way to gather a list of all the tags that a specific profile fetches? ie run osrm-extract --collect-tags and get a list of tags

**Comment by daniel-j-h** [comment]
@emiltin and where do you get the list of tags from? The profile exposes them itself? This is what the `taginfo.json` file already does to some degree.

**Comment by emiltin** [comment]
By looking at what tags the profiles fetches, ie. intercept calls to get_value_by_key(). After running an extract yoiu would have the complete list of tags keys that's actually used. It's hard to keep this list updated by hand, especially with helpers that fetch :forward, :backward etc. variants.

**Comment by emiltin** [comment]
I constructed this list in pure lua in the debug.lua file when I were using a lua cache mechanism. It also allowed me to see the number of fetches for each tag (which would optimally be reduced to 1). But now we're using a call into C++ to get tag values.

**Comment by daniel-j-h** [comment]
Note: there are some tags in the C++ code - for example all of the turn restriction handling, where we care for `only_*` and `no_*` turn restrictions (and `except` exceptions).

**Comment by emiltin** [comment]
good point

**Comment by joto** [comment]
Just an idea: To check whether the tag list (created manually or semi-automatically or so) is correct, we can filter the planet with this list and then re-run the import. If the resulting files are identical, it at least means we are not missing any tags. (Of course we could have too many in the list.) Of course that's expensive to do, but could be done occasionally after larger changes or so.
