### ISSUE TITLE
Revisit Intersection Classification

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3124]
Creating bearing classes is currently operating on two extremes:
- If all angles are distinct enough, we simply use discrete angles, based on a discretisation interval
- If two angles are close to each other, we store all angles at full accuracy

We should revisit this setup ([here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/turn_classification.cpp#L63-L92)).

At the same time, we should check if we can split this into two functions. I imagine a setup that computes discretisation factor for each vector first and after does a simple std::transform on the setup.

E.g. on 40 degree discretisation and a list of `[12,22,81]`, we should get `[40,40,40]` since all items are distinct (think [-20,20],[20,60],[60,100]... for different classes). The discrete items would be `[0,40,80]` (the middle of each of the intervals.

For `[9,19,81]`, we should see discrete interval sizes of `[20,20,40]` and `0,20,80` as resulting angles.
In general, the interval size of two neighbouring items needs to be smaller, if both items share the same interval.
`(left(x) < (x-0.5 I) && right(x) > (x+0.5*I))` for the interval size `I`. We wan't to find the maximum `I` for all entries with `I <= ACCURACY`

**Comment by TheMarex** [comment]
This refactor is low priority and given that we don't have a clear use case of intersection shapes, I don't see us doing this.
