### ISSUE TITLE
Refactor Turn Lane Data/Turn Lane Description

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3125]
We receive turn lane data in the form of Masks per lane. Right now we transform these into LaneDataVectors that combine consecutive sets of lanes into a single entry.

We should have a look at that conversion ([here](https://github.com/Project-OSRM/osrm-backend/blob/5e167b8745954dece49dd7502a2f5d247d0d1c1e/src/extractor/guidance/turn_lane_data.cpp#L68-L137)).
The current conversion is overly complicated and should be possible to adjust to the use of a std::algorithm.

We need to loop over the available lanes and either merge with the previous entry or add a new one (if lane masks don't overlap).

Special cases to consider here are the availability of shared indications that need to end up in multiple parts.

**Comment by TheMarex** [comment]
Unclear description of the problem. If we need to touch this code again, we will refactor it.
