### ISSUE TITLE
Refactor/Improve Turn Lane Augmentation

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3126]
We should look at the turn lane augmentation for refactoring/improvement.

Turn lane augmentation has to deal with the `none` tag that can be found in the OSM data a lot.
None describes a lane that is without any specific indication. It can be part of multiple entries.

Turn lane augmentation has to create the entries that are not specifically presented in the scenario.
For example:

```
a-b-c
  |
  d
```

And turn lanes `a-b` equal to `none|through|right` are equivalent to `through|through|right`,
but `through|none|right` can be either `through|through|right`, `through|right|right`, or through|through;right|right`, depending on the lanes at`bc`and`bd`.

None values can also be at different locations of the turn lanes.
For example `through|none|through|right|none|right` would be a way of expressing `through|through|through|right|right|right`. The `none` tag is often not specified directly but given as `through||through|right||right`.

The handler should get restructured to a pre-work, considering scenarios that are easy to adjust (e.g. `none` between identical tags) and those where the solution depends on the actual matched roads.

In general it should get refactored for better readability.

**Comment by TheMarex** [comment]
From what I can tell we are already handling these cases here https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/turn_lane_augmentation.cpp#L38-L164.

> In general it should get refactored for better readability.

Is not really specific enough to be actionable, so I think this issue should be closed.
