### ISSUE TITLE
Refactor Turn Lane Handler

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3128]
We should revisit the turn lane handler and improve it. I currently see a few issues that should be addressed:
- [ ] we should only consider previous intersections only if they are unique. Right now we introduce more strange behaviour than it helps. We need better handling of segregated roads on the graph level to correctly assign lanes to all entries at these intersections.
- [ ] [isSimpleIntersection](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/turn_lane_handler.cpp#L382-L497) should be replaced by a simulated matching run
- [ ] general refactor, make use of std::algorithm. Clarify scenarios by cleaner code.
  - [ ] [partitioning](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/turn_lane_handler.cpp#L499-L654)
  - [ ] [sliproad turns](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/turn_lane_handler.cpp#L678-L782)
  - [ ] [scenario discovery](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/turn_lane_handler.cpp#L151-L349)

**Comment by TheMarex** [comment]
None of the items mentioned here are detailed enough to be actionable. Closing.
