### ISSUE TITLE
Test LUA profiles directly

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#3131]
A lot of the Cucumber tests are really just testing the tag parsing that happens in the LUA profiles. It would be simpler and faster to have tests that tests the lua code directly, rather than having to go through constructing an .osm file, extracting, contracting and querying.

Testing would simply load the LUA file, provide and input way/node and check the output.

One issue is that there are a few C++ methods that are called from LUA. Testing LUA code would be simpler if this could be avoided.

**Comment by daniel-j-h** [comment]
Related: having pure-Lua profiles would also allow for https://github.com/Project-OSRM/osrm-backend/issues/3864
