### ISSUE TITLE
RTree size reduction - encoding only edge-based-nodes at the leaf

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3136]
Currently, the StaticRTree stores every road segment (coordinate pair) in order to perform a nearest neighbor search.

In addition, we store the complete road geometry in the `.geometry` file.  The RTree stores bounding boxes for each segment, and the `.geometry` has box coordinates as well.

This is duplicated data that we could potentially do some tradeoff with.  Right now, searching the RTree will take you directly to your road segment.

At the expense of a little performance, we could possibly greatly reduce the amount of data stored in our RTree.  Instead of storing individual road segments as objects in the tree, we could store, for example, just the EdgeBasedNode and the bounding box for that node's geometry.

This would make rtree searches require more steps - we'd have a less optimal list of candidates that we'd need to iterate over, because the EdgeBasedNode geometry decomposition is unlikely to match the optimal RTree division.

However, we currently query the RTree leafnodes from disk.  If the above alternative significantly reduces the rtree leaf node data size, there could be a net gain by being able to store the leaf node data in RAM.

/cc @TheMarex

**Comment by TheMarex** [comment]
> This would make rtree searches require more steps - we'd have a less optimal list of candidates that we'd need to iterate over, because the EdgeBasedNode geometry decomposition is unlikely to match the optimal RTree division.

What this basically will boil down to is how much overlap the RTree leaves will have. Using the whole compressed edge will include very long geometries like motorways that could cause serious performance problems.

Measuring this should be rather simple:

- Iterate over every compressed geometry, generate a bounding box
- Run the same algorithm we use for creating the RTree on bounding boxes
- Inspect the result for overlap

If our goal is to reduce the size of the StaticRTree I think there are some more low-hanging fruit around consolidating all the per-segment data we store.
