### ISSUE TITLE
Extracting maps

### ISSUE THREAD

**Issue by firefox159** [Project-OSRM/osrm-backend#314]
After succesfully compiling OSRM I am currently extracting maps. 
I need to extract a map of europe (so I download one @ GEOFABRIK) 
However I run out of memory each time I try to extract the map...

I am running a ubuntu 64bit system that has a max of 4 GB Ram & 128Gig of diskspace. 

If there is no way arround this, is there a way to download pre-extracted map files, to avoid my problem? 
Is merging of maps also possible? (For example I only need Benelux + france+germany)

Thank you very much for helping me out !

**Comment by mzubair1s** [comment]
I am following the website https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04#step-6-%E2%80%94-extract-the-map
here when i run the command 
osrm-extract map.osm
Its showing that 
osrm-extract command not found help me.

**Comment by TimMcCauley** [comment]
I guess the command is not path of your binary path:

```
Building with sudo is necessary here because the install target will copy some executables in the system’s binary path, including some which we will need. Namely:

osrm-extract which opens the map file and runs a first pre-processing step on the data.
osrm-prepare which processes the output of osrm-extract and computes the traveling times for all the map edges according to a given Lua speed profile.
osrm-routed the actual web service daemon, which allows us to query for distances and locations.
```
