### ISSUE TITLE
respond code 400 not getting

### ISSUE THREAD

**Issue by nikhilve99** [Project-OSRM/osrm-backend#3144]
HI ,

i am new in OSRM and recently installed on ubuntu 14.04. i used below link to install osrm.
my osrm v5.4 
my issue is "whenever i am trying to test my server and giving address on my browser (http://localhost:5000) the error i am getting is:
{"message":"URL string malformed close to position 1: \"\/\"","code":"InvalidUrl"}

kindly help to solve this issue.

Regards
Nikhil

**Comment by MoKob** [comment]
@nikhilve99 you need to specify a full and valid URL.

On the demo server,

`https://router.project-osrm.org/route/v1/driving/-1.576672,47.206839;-1.531338,47.252596?steps=true` will provide a route,

`https://router.project-osrm.org/` will show your exact error.

**Comment by nikhilve99** [comment]
thanks for your reply.
i am getting proper response from the server after using full URL.
i have one more question.
i have configured osrm-backend and frontend too but i am not able to connect them both.
even when i am using my frontend my server is not showing the routes also.

Regards
Nikhil

**Comment by MoKob** [comment]
Without a proper error description, it is near impossible to help here.

You need to follow the instruction in the README and do:

> The most common modifcation is to add your own OSRM endpoint. For this open `src/leaflet_options.js`:
> 
> ```
>   services: [{
>     label: 'Car (fastest)',
>     path: 'http://myserver.example.com/route/v1'
>   }],
> ```
> 
> Replace the path with whatever your endpoint looks like.

If you don't see your instance of osrm-routed printing log information, you probably didn't provide the correct url to your service.

Else, you should check the debug console to find potential errors in your frontend.
