### ISSUE TITLE
InvalidValue is not in the v5 spec

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3150]
Plugins `viaroute`, `match`, `trip` may return `InvalidValue` response code.

This return code is not documented in the v5 spec at

https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

**Comment by MoKob** [comment]
Well, they may be returning this, but it's not an intended return. We should probably not expose internal items in the documentation? The default fallback mechanism we require is asking to treat everything as a turn, which would be a valid fallback here.

**Comment by MoKob** [comment]
From chat: was thinking about different issue. Documentation is go
