### ISSUE TITLE
Routing with Traffic in India

### ISSUE THREAD

**Issue by Smartauto** [Project-OSRM/osrm-backend#3153]
Hi
We are trying to experience OSRM, Need to know if Distance and Direction can be show as per current traffic. 
Is there a active Traffic layer for India. If yes then how can we can use the same.
We have some 20000 Cabs which can give feedback of live traffic .

Looking for  some idea on how to achive the above

**Comment by daniel-j-h** [comment]
Yes, you can incorporate the current traffic! Here's a quick overview:

https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

There is no open traffic layer as far as I know. For other options send me a mail (see my profile).

**Comment by daniel-j-h** [comment]
Closing here as not actionable for us.

**Comment by sroycode** [comment]
@Smartauto We are working on something similar , there is an incomplete project by opentraffic.io that can be used to push traffic data and modify the speed of road segments , in turn that can be fed into osrm by the process described.

**Comment by DarthSidddd** [comment]
Hi Guys, can any one let me know what is the minimum system requirement to deploy OSRM india-latest.pbf?

**Comment by wangyoucao577** [comment]
I had a try with india-latest.pbf months ago, it uses 4~ 7GB memory for running.

**Comment by DarthSidddd** [comment]
@wangyoucao577 , thanks for the reply :)
