### ISSUE TITLE
Separate Post Processing Tasks

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3158]
Post Processing currently uses a series of steps to update a route. These steps happen in the route-api ([here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/api/route_api.hpp#L145-L156).

Two main restructuring efforts should be taken here:
### Encapsulate Post Processing

The post-processing starts of with removing short segments and ends with syncing geometry entries. To avoid possible errors with order/make it transparent to the api, we should encapsulate the full post-processing into a dedicated class.
### Restructure Post Processing

Currently some tasks in postprocessing ([here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/guidance/post_processing.cpp#L826) and ff are mixed up. We should restructure this to separate different tasks from one-another, even though this requires additional passes over the data.

**Comment by TheMarex** [comment]
This will be solved my moving most of the post-processing logic to pre-processing.
