### ISSUE TITLE
Set up crashes in Ubuntu 14.10

### ISSUE THREAD

**Issue by gastonillanes** [Project-OSRM/osrm-backend#3159]
Hi,

I'm trying to set up OSRM on Ubuntu 14.10. After following the "Building on Ubuntu" examples, I run into an issue after calling "cmake --build .". To be specific, I get the following error:

make[2]: *** [CMakeFiles/ENGINE.dir/src/engine/engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/ENGINE.dir/all] Error 2
make: *** [all] Error 2

I saw that issue #3018 also regarded this error, but unlike the user in that issue, I cannot cmake version 5.4.0. (That is, I get the same error following the commands:
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
)

Here is a link to the build log:
https://gist.github.com/gastonillanes/5bbe43f9c6d63812748cb97ee32b745b

Thanks!

**Comment by danpat** [comment]
@gastonillanes Our build now requires a C++14 capable compiler - GCC 4.8 (the default on Ubuntu 14.10) doesn't support the `make_unique` function call (the first error in your build log).

You can try installing GCC 5 from:

https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

and see if it clears up the problem.  It looks like our Ubuntu 14.10 docs are out of date, we only recently transitioned to `std::make_unique`.

**Comment by daniel-j-h** [comment]
https://github.com/Project-OSRM/osrm-backend/issues/3111
> Make Compilation / Runtime Requirements Explicit

**Comment by gastonillanes** [comment]
Great, this solved the issue, thanks!
