### ISSUE TITLE
[help wanted] OSRM isn't building for me

### ISSUE THREAD

**Issue by glifchits** [Project-OSRM/osrm-backend#3161]
Hey all, thanks for this awesome project and all the great work done here.

I have been trying to set up an instance of OSRM in house and I cannot figure out why I always get this STXXL "No space left on device" error:

```
Step 8 : RUN ./osrm-extract /osrm-data/hugedata.osm.pbf
 ---> Running in 10ba7e361bdf
[info] Using script profile.lua
[info] Input file: hugedata.osm.pbf
[info] Profile: profile.lua
[info] Threads: 16
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-MSG] 1 disks are allocated, total space: 200000 MiB
[info] Parsing in progress..
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
[info] timestamp: 2016-10-23T19:29:02Z
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[STXXL-ERRMSG] io_error thrown in ~vector(): Error in function virtual void stxxl::syscall_file::serve(const stxxl::request*): Info:  this=0x25583d0 call=::write(fd,buffer,bytes) path=/tmp/stxxl fd=5 offset=0 buffer=0x7f8edae9c000 bytes=2097152 type=WRITE rc=-1 No space left on device
[STXXL-ERRMSG] io_error thrown in ~vector(): Error in function virtual void stxxl::syscall_file::serve(const stxxl::request*): Info:  this=0x25583d0 call=::write(fd,buffer,bytes) path=/tmp/stxxl fd=5 offset=1956642816 buffer=0x7f8ee76a2000 bytes=2097152 type=WRITE rc=-1 No space left on device
[warn] Error in function virtual void stxxl::syscall_file::serve(const stxxl::request*): Info:  this=0x25583d0 call=::write(fd,buffer,bytes) path=/tmp/stxxl fd=5 offset=1950351360 buffer=0x7f8ee70a2000 bytes=2097152 type=WRITE rc=-1 No space left on device
```

This particular instance has 128GB of RAM and 320GB of disk. As you can see from the logs above the .stxxl file is over 209 GB.

I should note that I'm running this in a Docker container.

I am working with the North America data from Geofabrik (http://download.geofabrik.de/north-america-latest.osm.pbf)

**Comment by danpat** [comment]
@glifchits What version of OSRM are you building?  Can you share your Dockerfile?

**Comment by daniel-j-h** [comment]
Can you make sure it works without the extra layer the Docker container provides?

We wanted to switch over the demo server to a Docker-based setup recently (see https://github.com/Project-OSRM/osrm-backend-docker - feel free to update this or open issues there) and stumbled over https://github.com/Project-OSRM/osrm-backend-docker/issues/1.

**Comment by glifchits** [comment]
The base image that I am using grabs OSRM v5.2.6 (https://github.com/cartography/osrm-backend-docker)

FWIW the Docker container approach worked for building a much smaller OSM dataset (my tests worked on Berlin).

```Dockerfile
FROM cartography/osrm-backend-docker:latest

# OSM data, update this in the docker compose file
ARG PBF
RUN curl $PBF > /osrm-data/hugedata.osm.pbf

ARG STXXL_SIZE
RUN echo "disk=/tmp/stxxl,$STXXL_SIZE,syscall" > .stxxl

# Prepare the OSM data
RUN ./osrm-extract /osrm-data/hugedata.osm.pbf
RUN ./osrm-contract /osrm-data/hugedata.osrm

# Run the server
RUN echo "/osrm-build/osrm-routed /osrm-data/hugedata.osrm --max-table-size 8000" > /runserver.sh
RUN chmod +x /runserver.sh
ENTRYPOINT /runserver.sh
```

**Comment by danpat** [comment]
@glifchits I think you're hitting https://github.com/docker/docker/issues/21611

It seems by default, the Docker engine creates a 100GB sparse disk pool that's shared between all containers.  That ticket describes how to create a larger pool.  When STXXL initially creates the datafile, I believe it simply performs a sparse allocation - the disk space isn't actually claimed until you start using STXXL.

Can you try the suggestions in the ticket above and see if that resolves your problem?

Another option would be to bind-mount an external volume with `-v`, but we came across https://github.com/Project-OSRM/osrm-backend-docker/issues/1 using that approach (that might not be a problem for you).

**Comment by glifchits** [comment]
@danpat I tried following the steps in that issue, it did not seem to help. Here's what I did:
```
root@osrm-docker:~# service docker stop
root@osrm-docker:~# rm -rf /var/lib/docker
root@osrm-docker:~# mkdir -p /var/lib/docker/devicemapper/devicemapper
root@osrm-docker:~# fallocate -l 300G /var/lib/docker/devicemapper/devicemapper/data
root@osrm-docker:~# service docker start
root@osrm-docker:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             63G     0   63G   0% /dev
tmpfs            13G  3.5M   13G   1% /run
/dev/vda1       335G  302G   20G  94% /
tmpfs            63G     0   63G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            63G     0   63G   0% /sys/fs/cgroup
tmpfs            13G     0   13G   0% /run/user/0
root@osrm-docker:~# free -h
              total        used        free      shared  buff/cache   available
Mem:           125G        364M        114G        3.5M         10G        124G
Swap:            0B          0B          0B
   ...
root@osrm-docker:/osrm# dc build
   ...
Step 7 : RUN ./osrm-extract /osrm-data/hugedata.osm.pbf
 ---> Running in 9eb8767dccb5
[info] Using script profile.lua
[info] Input file: hugedata.osm.pbf
[info] Profile: profile.lua
[info] Threads: 16
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-MSG] 1 disks are allocated, total space: 200000 MiB
[info] Parsing in progress..
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
[info] timestamp: 2016-10-24T19:28:02Z
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[STXXL-ERRMSG] io_error thrown in ~vector(): Error in function virtual void stxxl::syscall_file::serve(const stxxl::request*): Info:  this=0xef93d0 call=::write(fd,buffer,bytes) path=/tmp/stxxl fd=5 offset=0 buffer=0x7f6ff6f34000 bytes=2097152 type=WRITE rc=-1 No space left on device
[STXXL-ERRMSG] io_error thrown in ~vector(): Error in function virtual void stxxl::syscall_file::serve(const stxxl::request*): Info:  this=0xef93d0 call=::write(fd,buffer,bytes) path=/tmp/stxxl fd=5 offset=1956642816 buffer=0x7f700373a000 bytes=2097152 type=WRITE rc=-1 No space left on device
[warn] Error in function virtual void stxxl::syscall_file::serve(const stxxl::request*): Info:  this=0xef93d0 call=::write(fd,buffer,bytes) path=/tmp/stxxl fd=5 offset=1950351360 buffer=0x7f700313a000 bytes=2097152 type=WRITE rc=-1 No space left on device
ERROR: Service 'osrm' failed to build: The command '/bin/sh -c ./osrm-extract /osrm-data/hugedata.osm.pbf' returned a non-zero code: 1
```

**Comment by danpat** [comment]
@glifchits Hmm.  Can you execute a `df` command inside your container, and see what kind of disk space it sees?  I still think you're hitting some kind of container constraint - with North America-sized data, you'll need 10GB for the PBF, another 20GB for the generated files during `osrm-extract`, *plus* the space for STXXL external memory files.

You've got a good chunk of RAM there - as a workaround, you could also try doing `echo "disk=/tmp/stxxl,75000,memory" > .stxxl`.  This will do everything in RAM, rather than using the STXXL external memory feature.  I think you should have enough to process North America with the `car` profile.

**Comment by glifchits** [comment]
Hey @danpat thanks for your help, its greatly appreciated.

Running this on a fresh instance, fresh Docker build (did not do the disk pool allocation trick):

```
Step 7 : RUN df -h
 ---> Running in d3b98d55c83d
Filesystem                                Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:1-131624-cef20d...  10G  8.2G  1.9G  82% /
tmpfs                                      63G     0   63G   0% /dev
tmpfs                                      63G     0   63G   0% /sys/fs/cgroup
/dev/vda1                                 335G  9.6G  312G   3% /etc/hosts
shm                                        64M     0   64M   0% /dev/shm
 ---> 35b6af17836c
Removing intermediate container d3b98d55c83d
Step 8 : RUN free -h
 ---> Running in 951eccddde05
             total       used       free     shared    buffers     cached
Mem:          125G       9.2G       116G       3.5M        34M       8.5G
-/+ buffers/cache:       697M       125G
Swap:           0B         0B         0B
 ---> 7e29e01ffca2
```

Does Docker only uses the 10G `/dev/mapper/docker-...` device for its filesystem? The container doesn't have access to /dev/vda1?

**Comment by danpat** [comment]
@glifchits Correct, it looks like your container only has 10GB disk available.  This explains the failure on the larger dataset, but the fact that works on smaller data.

I'm not a Docker expert, but I did find this PR for Docker https://github.com/docker/docker/pull/14709, but it seems to have regressed in the current code:

https://github.com/rhvgoyal/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L37-L39

I also came across this: https://esalagea.wordpress.com/2015/10/05/increase-disk-size-of-docker-containers-when-using-device-mapper/

but it's nearly a year old, so I have no idea if it still works.

The alternative here is to use a bind-mounted volume - don't use the internal docker FS, mount an external volume that doesn't have the image size restrictions.

**Comment by glifchits** [comment]
I specified that stxxl use RAM instead of disk using your trick above, and the extract step is now chugging along. I am worried that it will crash when it tries to write the data since it's still only got 10GB of disk, but I'll keep you posted.

**Comment by glifchits** [comment]
@danpat thanks for those resources, I simultaneously found these [docs](https://docs.docker.com/engine/reference/commandline/dockerd/#/devicemapper-options) which also note the ability to set the devicemapper default size. Will try that next.

**Comment by glifchits** [comment]
@danpat extract step ended up failing, but I got this error:

`[warn] osrm input file misses magic number. Check or reprocess the file`

Worth noting I also saw this error while testing this Docker configuration on Canada OSM data (~2.1 GB) in a very small instance (1GB RAM, 30GB disk)

Full logs for the North America data, stxxl using memory:

```
Step 8 : RUN df -h
 ---> Running in bebb157956e1
Filesystem                                 Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:1-131624-9fa880...   10G  8.2G  1.9G  82% /
tmpfs                                       63G     0   63G   0% /dev
tmpfs                                       63G     0   63G   0% /sys/fs/cgroup
/dev/vda1                                  335G   12G  310G   4% /etc/hosts
shm                                         64M     0   64M   0% /dev/shm
 ---> cf7a3db2f928
Removing intermediate container bebb157956e1
Step 9 : RUN free -h
 ---> Running in 72b9821cb56c
             total       used       free     shared    buffers     cached
Mem:          125G        11G       114G       3.5M        40M        10G
-/+ buffers/cache:       749M       125G
Swap:           0B         0B         0B
 ---> 22de7d8ec3cb
Removing intermediate container 72b9821cb56c
Step 10 : RUN ./osrm-extract /osrm-data/hugedata.osm.pbf
 ---> Running in 6f5a68bf300c
[info] Using script profile.lua
[info] Input file: hugedata.osm.pbf
[info] Profile: profile.lua
[info] Threads: 16
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-MSG] 1 disks are allocated, total space: 100000 MiB
[info] Parsing in progress..
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
[info] timestamp: 2016-10-24T19:28:02Z
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parsing finished after 1302.84 seconds
[info] Raw input contains 864576589 nodes, 60624889 ways, and 559133 relations, and 0 unknown entities
[extractor] Sorting used nodes        ... ok, after 31.6025s
[extractor] Erasing duplicate nodes   ... ok, after 11.8549s
[extractor] Sorting all nodes         ... ok, after 348.479s
[extractor] Building node id map      ... ok, after 118.58s
[extractor] setting number of nodes   ... ok
[extractor] Confirming/Writing used nodes     ... ok, after 61.5163s
[info] Processed 180232712 nodes
[extractor] Sorting edges by start    ... ^A^Aok, after 92.2532s
[extractor] Setting start coords      ... ok, after 96.5913s
[extractor] Sorting edges by target   ... ok, after 66.6395s
[extractor] Computing edge weights    ... ok, after 133.122s
[extractor] Sorting edges by renumbered start ... ok, after 56.8196s
[extractor] Writing used edges       ... ok, after 10.6072s
[extractor] setting number of edges   ... ok
[info] Processed 189512712 edges
[extractor] Sorting used ways         ... ok, after 4.02063s
[extractor] Sorting 71141 restriction. by from... ok, after 0.016136s
[extractor] Fixing restriction starts ... [warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
...
[warn] Restriction references invalid way: 448899235
[warn] Restriction references invalid way: 448899235
[warn] Restriction references invalid node: 4294967295
ok, after 0.900249s
[extractor] Sorting restrictions. by to  ... ok, after 0.016913s
[extractor] Fixing restriction ends   ... ok, after 0.816063s
[info] usable restrictions: 63346
[extractor] writing street name index ... ok, after 0.300074s
[info] extraction finished after 2379.95s
[info] Generating edge-expanded graph representation
[warn] osrm input file misses magic number. Check or reprocess the file
ERROR: Service 'osrm' failed to build: The command '/bin/sh -c ./osrm-extract /osrm-data/hugedata.osm.pbf' returned a non-zero code: 1
```

Dockerfile:
```Dockerfile
FROM cartography/osrm-backend-docker:latest
MAINTAINER george
ARG PBF
RUN curl $PBF > /osrm-data/hugedata.osm.pbf
ARG STXXL_SIZE
ARG STXXL_TYPE
RUN echo "disk=/tmp/stxxl,$STXXL_SIZE,$STXXL_TYPE" > .stxxl
RUN df -h
RUN free -h
RUN ./osrm-extract /osrm-data/hugedata.osm.pbf
RUN ./osrm-contract /osrm-data/hugedata.osrm
```

docker-compose.yml:
```yml
version: '2'
services:
  osrm:
    build:
      context: .
      args:
        - PBF=http://download.geofabrik.de/north-america-latest.osm.pbf
        - STXXL_SIZE=100000
        - STXXL_TYPE=memory
    ports:
      - 5000:5000
```

**Comment by danpat** [comment]
@glifchits I'm betting that you're out of disk, and we're not catching the error properly inside the code.  The "missing magic number" indicates that one of the files is corrupt, my guess is that we failed to write it properly due to insufficient disk, but didn't report the error.

**Comment by glifchits** [comment]
Thanks @danpat. I'll close this issue since we're pretty confident in the issue. The frustration of increasing the Docker container volume size has made me pretty frustrated, so I will proceed with setting up OSRM the old fashioned way.

**Comment by danpat** [comment]
@glifchits If you want to keep hammering on the Docker approach, you can try the recipe here:

  https://hub.docker.com/r/osrm/osrm-backend/

I've published a Docker image containing the OSRM 5.4.1 release at `osrm/osrm-backend:v5.4.1`.  The instructions on the page above show how to do file processing *outside* the container in a bind-mounted volume.

The only thing missing from that recipe is a `.stxxl` file.  The WORKDIR is `/opt` inside the container, so you could just do `docker run sh -c "echo disk=/data/stxxl,100000,syscall > /opt/.stxxl && osrm-extract -p car.lua /data/yourfile.pbf`

**Comment by glifchits** [comment]
@danpat I finally got North America building in a Docker container! I stuck with the cartography image I was using before. What ultimately saved the day for me was:
1. Ensuring Docker was using the AUFS storage driver instead of devicemapper (followed [these](https://gist.github.com/parente/025dcb2b9400a12d1a9f) steps to set up AUFS support)
2. Running on a high-memory instance with in-memory .stxxl (128GB RAM, 110000MiB stxxl memory)

**Comment by pocman** [comment]
@danpat @glifchits could you edit the [Docker Recipes](https://github.com/Project-OSRM/osrm-backend/wiki/Docker-Recipes) to document how to set the .stxxl at docker run time ?

**Comment by danpat** [comment]
@pocman Done - https://github.com/Project-OSRM/osrm-backend/wiki/Docker-Recipes#note-on-stxxl-usage

It's pretty easy - just drop your `.stxxl` configuration file in the directory that gets mounted at `/data` inside the container.

**Comment by pocman** [comment]
@danpat thanks, I though that It had to be done in the cmd.
Your previous example places the .stxxl in the /opt directory, not the /data.
