### ISSUE TITLE
Osrm-extract error

### ISSUE THREAD

**Issue by gastonillanes** [Project-OSRM/osrm-backend#3167]
Hi,

I am running the following error when running osrm-extract:

~/Documents/Research/WSLCB/liquor_paper/osrm$ osrm-extract -p profile.lua washington-latest.osm.pbf 
[info] Using script profile.lua
[info] Input file: washington-latest.osm.pbf
[info] Profile: profile.lua
[info] Threads: 4
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-MSG] 1 disks are allocated, total space: 20000 MiB
[info] Parsing in progress..
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
[info] timestamp: 2016-10-23T19:29:02Z
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
terminate called after throwing an instance of 'osrm::util::exception'
  what():  ERROR occurred in profile script:
No matching overload found, candidates:
void <unknown>(RoadClassification&,unsigned char)
Aborted (core dumped)

I am trying to extract a map for the state of Washington, obtained from http://download.geofabrik.de/north-america/us/washington.html

Thanks!

**Comment by danpat** [comment]
This should be fixed by https://github.com/Project-OSRM/osrm-backend/pull/3160

Please grab a copy of the latest `master` code, recompile OSRM and give it another go.

**Comment by gastonillanes** [comment]
That solved the problem, thanks!
