### ISSUE TITLE
Move node-osrm into osrm-backend

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3183]
- [x] move `node-osrm` code with history using git subtree import from https://github.com/Project-OSRM/node-osrm into osmr-backend source tree.
- [x] Integrate into cmake build system using `node-cmake`
- [ ] update releasing docs and README / Wiki

Basically redo https://github.com/Project-OSRM/osrm-backend/pull/2420 properly with an updated node-osrm version and history.

**Comment by daniel-j-h** [comment]
Can we get an update what is blocking here? And / or link node-osrm tickets.

**Comment by TheMarex** [comment]
Nothing blocking as far as I know (other then priorities and lack of time).

**Comment by TheMarex** [comment]
We actually did this.
