### ISSUE TITLE
not able to understand code 

### ISSUE THREAD

**Issue by nikhilve99** [Project-OSRM/osrm-backend#3187]
hi team,

As recently i have installed OSRM in my org. and found some confusing code while putting below link on my browser : 
 http://localhost:5000/nearest/v1/driving/77.092961,28.511443?number=3&bearings=0,20

and getting OUTPUT: 

{"waypoints":[{"distance":33.610302,"hint":"r8UAgP___39YNgAALwAAAEMAAAAKAQAAKwAAAEKhAACgAQAAF1eYBH4MswFhWJgE0wyzAQUAAQFkuK-M","name":"","location":[77.092631,28.511358]},{"distance":40.797718,"hint":"r8UAgP___39YNgAAAAAAACsAAABNAQAAAAAAAEKhAACgAQAA1VaYBEcNswFhWJgE0wyzAQYAAQFkuK-M","name":"","location":[77.092565,28.511559]},{"distance":69.580998,"hint":"EcUAgP___38AAAAAIQAAADUAAABqAQAAAAAAAMqgAACgAQAApVWYBGEMswFhWJgE0wyzAQUAAQFkuK-M","name":"","location":[77.092261,28.511329]}],"code":"Ok"}

kindly help me to understand the code which osrm producing after "hint" , can we encode the code in plain text,  if yes then how.

kindly find the image attached here for your ref.

Regards
Nikhil
![code](https://cloud.githubusercontent.com/assets/3167200/19754330/00103c50-9c2a-11e6-9adb-b2e72760acca.png)

**Comment by danpat** [comment]
@nikhilve99 The `hint` property can be used to speed up follow-up queries - the `hint` tells OSRM the internal network ID it needs to being a search.  It has no useful human-readable version.

You can supply the hints to later queries using the `&hints=` URL parameter documented here: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#general-options, this reduces the amount of work OSRM needs to perform to respond to your query.

See also: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#properties-7

**Comment by nikhilve99** [comment]
@Danpat Thanks for your your quick revert , can you help in creating the API request for us to identify the nearest point to the location asked for.

The API that we triggered is as below:
**http://localhost:5000/nearest/v1/driving/77.092961,28.511443?number=3&bearings=0,20**

and getting OUTPUT:

**{"waypoints":[{"distance":33.610302,"hint":"r8UAgP___39YNgAALwAAAEMAAAAKAQAAKwAAAEKhAACgAQAAF1eYBH4MswFhWJgE0wyzAQUAAQFkuK-M","name":"","location":[77.092631,28.511358]},{"distance":40.797718,"hint":"r8UAgP___39YNgAAAAAAACsAAABNAQAAAAAAAEKhAACgAQAA1VaYBEcNswFhWJgE0wyzAQYAAQFkuK-M","name":"","location":[77.092565,28.511559]},{"distance":69.580998,"hint":"EcUAgP___38AAAAAIQAAADUAAABqAQAAAAAAAMqgAACgAQAApVWYBGEMswFhWJgE0wyzAQUAAQFkuK-M","name":"","location":[77.092261,28.511329]}],"code":"Ok"}**
So What The Respone means is
1> There is a Point at distance 33.61 meters away.
2> Location of that point is [77.092631,28.511358]

**What is the Human readable address for this point?** 
Please help in making API query for the same.

**Comment by danpat** [comment]
@nikhilve99 OSRM does not return address names, it only returns the nearest location on the road network.

What you are looking for is known as "reverse geocoding", this is not an OSRM function, but you can try looking at http://wiki.openstreetmap.org/wiki/Nominatim#Reverse_Geocoding for more information.

**Comment by danpat** [comment]
I guess in theory we could include the street name in the `nearest` API response, but we cannot perform anything more advanced than that (addresses, off-street points-of-interest, etc).
