### ISSUE TITLE
Invalid definition of makeRouteStep function

### ISSUE THREAD

**Issue by deniskoronchik** [Project-OSRM/osrm-backend#3188]
When we try to use makeRouteStep function from engine/api/json_factory.hpp outside, we found a problem: we had a linked error. The problem with makeRouteStep definition, it doesn't equal to this function signature in cpp file.

**Comment by deniskoronchik** [comment]
Add pull request to fix this one #3189

**Comment by MoKob** [comment]
Thanks for this fix.
