### ISSUE TITLE
Can't provide a custom ServiceHandler into server

### ISSUE THREAD

**Issue by deniskoronchik** [Project-OSRM/osrm-backend#3190]
For some testing purposes we need to implement our version of osrm-routed application, without changing original. 
So that would be good to make possible to provide a custom ServiceHandler into server, also original OSRM has a function for this:

``` cpp
void RegisterServiceHandler(std::unique_ptr<ServiceHandler> service_handler_)
{
        request_handler.RegisterServiceHandler(std::move(service_handler_));
}
```

Main idea to make a base interface for ServeiceHandler and work with it.

``` cpp
void RegisterServiceHandler(std::unique_ptr<ServiceHandlerInterface> service_handler_)
{
        request_handler.RegisterServiceHandler(std::move(service_handler_));
}
```

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/issues/3191.
