### ISSUE TITLE
problem with path in your and your site as well

### ISSUE THREAD

**Issue by imbhaumik** [Project-OSRM/osrm-backend#3192]
today i found out a problem in my implemented api which was working fine earlier. then i investigated and found same problem in your site. when i try to draw route it doesnt show route and add a waypoint somewhere near LA, USA. here is the [screenshot](http://s13.postimg.org/rjfumsp9z/OSRM.png)

**Comment by danpat** [comment]
The demo server is currently only returning routes within California - there is a bug in the latest OSRM code that's preventing us from offering the whole planet.

We will update the demo server with whole-planet routing once we get to the bottom of the bug.

**Comment by imbhaumik** [comment]
what will be the expected time duration for that changes?

**Comment by daniel-j-h** [comment]
Hopefully today or tomorrow - @freenerd should be able to give you updates on this.

**Comment by imbhaumik** [comment]
its working now.  thanks.
