### ISSUE TITLE
Getting InvalidValue on route service

### ISSUE THREAD

**Issue by Robatjazi** [Project-OSRM/osrm-backend#3200]
Hi Guys,

I am new on using ors' and just run it on a test machine.
I am using alberta-latest.osm.pbf file for getting routes. But by calling route service with sample long an lat, I get InvalidValue response. Here is an example:

http://127.0.0.1:5000/route/v1/driving/53.451142,-113.565070;53.491257,-113.578827?steps=false&alternatives=true

Should long/lat be converted? I see example and always they are positive numbers.

Also when I just send some positive long/lat always get:
{
    waypoints: [
    {
        location: [
            -109.499977,
            52.405866
        ],
        name: "",
        hint: "J78HgP-qC4CMXgEAfwAAAAAAAAAaOQAAAAAAAOCoBAB-AAAAtyl5-    WqmHwN8hZ4ArVghA1wAAQGbTcgn"
    },
    {
        location: [
            -109.499977,
            52.405866
        ],
        name: "",
        hint: "J78HgP-qC4CMXgEAfwAAAAAAAAAaOQAAAAAAAOCoBAB-AAAAtyl5-WqmHwPPy8sA-wkhA1wAAQGbTcgn"
    }
    ],
    routes: [
    {
        distance: 0,
        duration: 0,
        legs: [
            {
                distance: 0,
                duration: 0,
                summary: "",
                steps: [ ]
            }
        ],
        geometry: "uoz~Hzui{S??"
    }
    ],
code: "Ok"
}

Is there a default value for long/lat if send long/lat does not exist? 

Regards

**Comment by daniel-j-h** [comment]
The format is `lon, lat`, see
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-route

And the extract you're running OSRM with has to to cover your request.

Also re. demo server: https://github.com/Project-OSRM/osrm-backend/issues/3186#issuecomment-256535566 if you're testing there. tl;dr only CA until the demo server re-processes the latest planet with the latest osrm nightly builds:

http://map.project-osrm.org/?z=7&center=38.406254%2C-115.191650&loc=37.020098%2C-112.840576&loc=43.221190%2C-118.410645&hl=en&alt=0
