### ISSUE TITLE
Implement Dummy Partitioner

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3204]
Implement a dummy partitioner e.g. doing geographic partitioning either on the node based graph and then try to infer partitions for the edge based graph, or already on the edge based graph with some heuristics. The output should be a mapping from node ids to partition ids.

**Comment by danpat** [comment]
A very simple approach for this could be a tile/quadkey approach.  Definitely not optimal, but should be simple to implement, and would allow us to work out the kinks on the other interfaces.

**Comment by daniel-j-h** [comment]
Stale. We went for the full blown solution (again) in https://github.com/Project-OSRM/osrm-backend/pull/3603. No love for dummy partitioners.
