### ISSUE TITLE
Support I/O operation for js profiles

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#3206]
After https://github.com/Project-OSRM/osrm-backend/pull/2687 has landed, initially with just static v8 functionality, explore adding I/O functionality to javascript based profiles.

https://github.com/pmed/v8pp looks like it could be promising to use, e.g. https://github.com/pmed/v8pp#creating-a-v8-context-capable-of-using-require-function

**Comment by SiarheiFedartsou** [comment]
Probably #2687 will never be landed :-/
