### ISSUE TITLE
building problem 5.4.0

### ISSUE THREAD

**Issue by bvbever** [Project-OSRM/osrm-backend#3221]
Building the 5.4.1 gets an error while building with  `-DCMAKE_BUILD_TYPE=Release`.
While building with `-DCMAKE_BUILD_TYPE=Debug` its get through.

cmake 3.0.2 & lua 5.2.3

xxx@xxx:/osrm-v5.4.1/build$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
xxx@xxx:/osrm-v5.4.2/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- Building on a 64 bit system
-- Using GNU gold as linker.
-- Disabling gc-sections on gold binutils < 2.26, see: https://sourceware.org/bugzilla/show_bug.cgi?id=17639
-- Configuring OSRM in release mode
-- Configuring release mode optimizations
-- LTO working
-- Using gcc specific binutils for LTO.
-- Setting linker optimizations
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   date_time
--   chrono
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
-- Found Intel TBB
-- TBB interface version: 7003
-- Could NOT find Lua: Found unsuitable version "5.2.3", but required is exact version "5.2" (found /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so)
-- Could NOT find Lua: Found unsuitable version "5.2.3", but required is exact version "5.1" (found /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so)
-- Using Lua 5.2.3
-- Found Luabind: /usr/lib/libluabind.so
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- OpenMP support found. Linking just in case for stxxl
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/osrm-v5.4.1/build

xxx@xxx:/osrm-v5.4.1/build$ cmake --build .
[  0%] Built target CONTRACTOR
[ 23%] Built target ENGINE
[ 56%] Built target EXTRACTOR
[ 58%] Configuring revision fingerprint
-- Fingerprint unchanged, not regenerating
[ 58%] Built target FingerPrintConfigure
[ 74%] Built target SERVER
[ 77%] Built target STORAGE
[ 92%] Built target UTIL
[ 94%] Built target osrm
[ 94%] Built target osrm_contract
Linking CXX executable osrm-contract
/tmp/cczGqj0V.ltrans10.ltrans.o:cczGqj0V.ltrans10.o:vtable for tbb::empty_task: error: undefined reference to 'tbb::empty_task::~empty_task()'
/tmp/cczGqj0V.ltrans10.ltrans.o:cczGqj0V.ltrans10.o:vtable for tbb::empty_task: error: undefined reference to 'tbb::empty_task::~empty_task()'
collect2: error: ld returned 1 exit status
CMakeFiles/osrm-contract.dir/build.make:106: recipe for target 'osrm-contract' failed
make[2]: *** [osrm-contract] Error 1
CMakeFiles/Makefile2:342: recipe for target 'CMakeFiles/osrm-contract.dir/all' failed
make[1]: *** [CMakeFiles/osrm-contract.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
xxx@xxx:/osrm-v5.4.1/build$

**Comment by daniel-j-h** [comment]
Try turning LTO off:

    cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=OFF

I can reproduce locally but don't have the time to look into this today or tomorrow.

**Comment by bvbever** [comment]
cmake .. -DBUILD_TOOLS=1 seams to work. Is this also ok ?

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/issues/3224.
