### ISSUE TITLE
Remove {highway: type} fallback from default bike / walk profile

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3231]
See https://github.com/Project-OSRM/osrm-text-instructions/issues/62: there is no reason to ever return an encoding not intended for humans in the response. We removed it from the car profile long ago, and although at the moment we focus on car routing, bike and walk should return reasonable responses.

- [x] remove https://github.com/Project-OSRM/osrm-backend/blob/4ba8ccfcce50c1d1c6e91df34b85ecc98a116ec2/profiles/foot.lua#L157
- [x] remove https://github.com/Project-OSRM/osrm-backend/blob/4ba8ccfcce50c1d1c6e91df34b85ecc98a116ec2/profiles/bicycle.lua#L221

**Comment by daniel-j-h** [comment]
cc @ghoshkaj @emiltin

**Comment by emiltin** [comment]
Is there another way to get the highway tag?

**Comment by daniel-j-h** [comment]
No, but the _default_ profiles shouldn't encode the highway type at least.
