### ISSUE TITLE
Add functionality to lua for specifying node ids.

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3233]
As per https://github.com/Project-OSRM/osrm-backend/pull/3177#discussion_r86125128 we need to add a way to cucumber to specify the nodes that come from the node map.

Proposal would be:

```
        And the nodes
            | node | id |
            | a    | 1  |
            | b    | 2  |
            | c    | 3  |
            | d    | 4  |
            | e    | 5  |
            | f    | 6  |
            | g    | 7  |
```

/cc @danpat @MoKob

**Comment by TheMarex** [comment]
Actually we do have that. Thanks again to the person that added that. :bowing_man:

**Comment by emiltin** [comment]
i added that as part of the syntax change to node maps. there's one potential issue: ids are first assignmed sequentially when the node map is read. ids can then be changed with the table, but there's no guard against already used ids.

**Comment by emiltin** [comment]
another option would be to define a default mapping from name to id, like a=1, b=2, c=3.... that way we guarantee that id's a stable, but you don't have to defined them in a table unless you need something our of the ordinary.
