### ISSUE TITLE
Encapsulate Functionality in RouteStep

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3236]
Member functions for `RouteStep`: at the moment our types are dumb structs, functionality is provided all over the place where it is needed (e.g. see post processing .h/.cpp).

First candidate to refactor this is `RouteStep`: think adding `invalidate`, `elongate`, lane handling etc. to `RouteStep`.

There should be no need for the call site having to know in which of our current three toolkit headers lane support for a `RouteStep` is implemented in. Or is it implemented in postprocessing.h/.cpp? Or lane-pocessing.h/.cpp?

This is just confusion and making it hard to get into the code base.

**Comment by MoKob** [comment]
This was implemented in #3474. Further functionality can be added.
