### ISSUE TITLE
Constrain Staggered Intersection Classification

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3256]
Breaking out of https://github.com/Project-OSRM/osrm-backend/pull/3255#discussion_r86793694.

[Staggered Intersection classification](https://github.com/Project-OSRM/osrm-backend/blob/3e18e31bc916e711f20f7502c5b0f68fbc6c00bb/src/engine/guidance/post_processing.cpp#L806-L846) should be constrained to handle exactly the very short zig-zags in rural areas as described in #2738 - not more, not less.

This means e.g. checking for
- ~~mode changes~~ (resoled by #3324 )
- road classes
- number of lanes to derive road width etc.

Basically all information available in a [RouteStep](https://github.com/Project-OSRM/osrm-backend/blob/3e18e31bc916e711f20f7502c5b0f68fbc6c00bb/include/engine/guidance/route_step.hpp#L57-L74) which makes sense.

To fully solve this, we need to move the check for staggered intersections to its own location (prior to name changes?) instead of tagging it onto other scenarios. Code duplication that might become necessary would be the target of collapse refactoring.

When fully solved, cases like: https://github.com/Project-OSRM/osrm-backend/issues/3376 should be possible to handle.

**Comment by karenzshea** [comment]
Started in https://github.com/Project-OSRM/osrm-backend/tree/constrain-staggering

**Comment by daniel-j-h** [comment]
Hm road class is not available there. What you can check is the [Intersection](https://github.com/Project-OSRM/osrm-backend/blob/3e18e31bc916e711f20f7502c5b0f68fbc6c00bb/include/engine/guidance/route_step.hpp#L73) array in a `RouteStep`: intersections[0] corresponds to the `StepManeuver`, everything else describes intersections on the way. There should be no additional intersections in between the two steps.

**Comment by TheMarex** [comment]
This was merged. :tada:

**Comment by karenzshea** [comment]
No, @MoKob feels that the scope of this ticket is wider than what was addressed in [this pr](https://github.com/Project-OSRM/osrm-backend/issues/3324https://github.com/Project-OSRM/osrm-backend/issues/3324) so we're leaving open for anyone who can tackle the rest.

**Comment by karenzshea** [comment]
Criteria for staggered intersections addressed in the last PR were mode changes and intermediary restrictions. Everything else in the OP is still open.

**Comment by MoKob** [comment]
Moving remaining items to 5.6

**Comment by TheMarex** [comment]
This will be solved by our work on complex intersections, since we will contract these staggered intersections. That moves the work of making sure we don't break any of the items mentioned in the issue description to the contraction code not the staggered intersection code as it exists now.
