### ISSUE TITLE
Detect Difference between On/Off-ramps when looking at forks in motorways

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3257]
At [this](http://www.openstreetmap.org/#map=18/37.82607/-122.27469) location, 

<img width="887" alt="screen shot 2016-11-08 at 09 57 46" src="https://cloud.githubusercontent.com/assets/12932279/20092780/187fd2fe-a59a-11e6-9bd1-3bd927eba538.png">

we are currently emitting a `fork` instruction. Based from how the intersection looks, it might be better to emit an `exit` for the turn to the right and `no` instruction for the turn to the left.

We could think about looking ahead on forks in motorways to see if the next intersection is a merge onto a motorway or an exit. If we see a normal intersection, we could switch to exit (could be confusing if we told someone to use the ramp before?) and if we see a motorway on the other side, we could include that fact in making the turn to stay on the motorway the obvious one.

Question here: is staying on the motorway always more obvious than taking an exit?

**Comment by willwhite** [comment]
Another heuristic might be lane information (if available). This example has two lanes to the left and one to the right. Maybe that situation could always be treated like an exit/ramp?

**Comment by MoKob** [comment]
@willwhite looking at the picture, that is exactly what I thought as well. @chaupow you could use lanes to better distinguish forks.

However, this would only result in a `turn right`. We still would need some additional heuristic to detect the `exit` part here. (e.g. we could check for available exit numbers?)

**Comment by daniel-j-h** [comment]
Can be worked around on the client side: if there' exit information always announce as an exit:

https://github.com/Project-OSRM/osrm-text-instructions/issues/128

**Comment by MoKob** [comment]
This is a duplicate of #4295 .
