### ISSUE TITLE
Avoid copying string data in data facades

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3265]
Our data facades provide means to access [name, ref, pronunciation and destination](https://github.com/Project-OSRM/osrm-backend/blob/ef2261661c91405902abf55db4765818e956b674/include/engine/datafacade/datafacade_base.hpp#L162-L168) string data.

The fact that we're using `std::string` in the facade API here is unfortunate:

internally we store string data as a huge chunk of memory anyway. [Here](https://github.com/Project-OSRM/osrm-backend/blob/ef2261661c91405902abf55db4765818e956b674/include/engine/datafacade/internal_datafacade.hpp#L650-L695) we have to construct a `std::string` out of the correct sub-part of that chunk of memory, copying the char data into a string.

What we really want is a view onto that huge chunk of memory, which should then behave as a string.

Enter [string_ref](http://www.boost.org/doc/libs/1_61_0/libs/utility/doc/html/string_ref.html).

`string_ref` is a non-owning view on top of an arbitrary chunk of memory for representing string data without the need for allocations.

The proposed change here would be to switch out all `std::string` usages in the facades and replace it with non-owning `string_ref` views into our internal chunk of memory. Then only at the `libosrm` boundary we have to create `std::string`s.

(The same should be possible for other types in the facade API - this ticket is only about strings for now)

**Comment by daniel-j-h** [comment]
cc @danpat since you're re-working the facades currently.

**Comment by oxidase** [comment]
@daniel-j-h string_ref is deprecated. It was removed once and reverted back in https://github.com/boostorg/utility/commit/0b492bee9cca261066846216f0ba36602e2216b8 
it is better to use https://github.com/boostorg/utility/blob/develop/include/boost/utility/string_view.hpp and than switch directly to std::string_view with c++17

**Comment by daniel-j-h** [comment]
`string_view` was introduced in mid 2015 from what I can tell.
Which means not even Boost 1.55 has it yet :/

**Comment by oxidase** [comment]
yeah, it will require Boost 1.61
