### ISSUE TITLE
Undefined Behavior due to Type Punning

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3267]
I _think_ we're invoking undefined behavior here and in related situations

- https://github.com/Project-OSRM/osrm-backend/blob/cf35bbeb50824b38bad9154b44899000bc3a5cc6/src/contractor/contractor.cpp#L530-L531
- https://github.com/Project-OSRM/osrm-backend/blob/cf35bbeb50824b38bad9154b44899000bc3a5cc6/include/util/static_rtree.hpp#L384

These functions casts a `char* ` (alignment requirement of 1) to a target with higher alignment requirements. This is undefined behavior (and could fail e.g. on platforms other than x86 or if you enable SSE and the compiler wants to make use of alignment guarantees).

All of these have to e.g. go through a [bit_cast](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0476r0.html).
See e.g. https://github.com/jfbastien/bit_cast for JF's proposal.

@oxidase could you double-check I'm understanding the situation correctly?

**Comment by daniel-j-h** [comment]
Here are some static asserts which have to hold from what I understand: https://github.com/Project-OSRM/osrm-backend/pull/3268 Hint: they don't.

**Comment by TheMarex** [comment]
> These functions casts a char* (alignment requirement of 1) to a target with higher alignment requirements. 

From my understanding it is a little bit more subtle then that. Casting an _unaligned_ char* address might be UB but if the address is actually aligned, this is fine and not UB.

The static assertions you added do not test what needs to be tested: Is the address aligned at the time of casting. Your checks only check if casting any byte-aligned address to a `LeafNode` would be fine, it is not.

What we need is a check [here](https://github.com/Project-OSRM/osrm-backend/blob/cf35bbeb50824b38bad9154b44899000bc3a5cc6/src/contractor/contractor.cpp#L654) that make sure this address is aligned prior to casting.

**Comment by oxidase** [comment]
@daniel-j-h alignment requirement for object types will be the strictest requirement for members. So assertion will pass only for structs that consist of 'char's like { char x; char y[42]; }.

There is a general problem of converting a byte stream that has weakest alignment requirement 1 to some stricter alignment requirements. Here http://stackoverflow.com/questions/32589328/unaligned-access-through-reinterpret-cast some quotes from the standard that it is  **unspecified behavior**, but not undefined one. For example, this could lead to a factor 2 performance decrease for reads for x86_64 as here http://www.alexonlinux.com/aligned-vs-unaligned-memory-access , or an alignment exception for vectorized instructions. 

@TheMarex it will be a runtime check, LeafNode is 4096-bytes aligned and should match alignment of get_address result. 
Also for an array of tightly packed structures a pointer alignment will be correct only for the first element. Other elements can be eventually aligned and this depends on size of a packed structure and alignment requirement. So alignment correctness must be discussed together with structure packing, IO and performance/memory trade-off.

I will check OSRM tests on ARMv8. It proofs almost nothing, but just to check implementation of unspecified behavior.

**Comment by oxidase** [comment]
@daniel-j-h For the original places 
*    https://github.com/Project-OSRM/osrm-backend/blob/cf35bbeb50824b38bad9154b44899000bc3a5cc6/src/contractor/contractor.cpp#L530-L531
*    https://github.com/Project-OSRM/osrm-backend/blob/cf35bbeb50824b38bad9154b44899000bc3a5cc6/include/util/static_rtree.hpp#L384
think would be enough to assert that pointers returned by `get_address` satisfy alignment requirements. 

What can be checked or improved in terms of the issue.
 [GetAlignedBlockPtr](https://github.com/Project-OSRM/osrm-backend/blob/master/include/storage/shared_datatype.hpp#L145) aligns only the first item in the block. If the `entry_size` is not divisible by `entry_align` than the second item in the block will be misaligned. I would suggest just to put an assertion to check this condition and fix possible misalignments if any in terms of normalized read/write tickets.

**Comment by daniel-j-h** [comment]
Yes a runtime check for alignment is good enough. Your plan looks good!

**Comment by daniel-j-h** [comment]
With the code changes and now runtime-checks in place, can this be closed @oxidase?

**Comment by oxidase** [comment]
Yes, closed via 559c88b36d0647e9f6372a73de0c64b56408f42e
