### ISSUE TITLE
Text and routing issue

### ISSUE THREAD

**Issue by boothym** [Project-OSRM/osrm-backend#3282]
Noticed a few issues with this route: https://www.openstreetmap.org/directions?engine=osrm_car&route=56.06440%2C-3.23100%3B56.06360%2C-3.22170#map=17/56.06266/-3.22621

1.  Missing translation error - "en-GB.javascripts.directions.instructions.slight_right_with_exit" - I couldn't find the slight_right_with_exit text anywhere in Project-OSRM.
2.  Surely at the roundabout it should say continue straight on/take the 2nd exit, instead of slight right?
3.  The route diverts from the primary A921 road to use the Craigholm Lane service road, which isn't really suitable as a shortcut. It's a narrow one lane road for access to the backs of housing, see street view: https://goo.gl/maps/DSDiQM4RaQ12 Don't know whether that is an issue with the router, or something that can be fixed with the OSM data.

(Apologies for the issue title, didn't know what to write!)

**Comment by daniel-j-h** [comment]
I saw the same translation error today on someone else's phone with German locale. This please open a ticket in https://github.com/openstreetmap/openstreetmap-website/issues where the translation happens.

This is a Roundabout Intersection, see this ticket for an explanation:
https://github.com/Project-OSRM/osrm-backend/pull/2718

(probably should have a different icon)

Here's your route on the demo server.

http://map.project-osrm.org/?z=17&center=56.063193%2C-3.223672&loc=56.064501%2C-3.231493&loc=56.063244%2C-3.223211&hl=en&alt=0

**Comment by daniel-j-h** [comment]
This was discussed on IRC yesterday; translation issue is ticketed at
https://github.com/openstreetmap/openstreetmap-website/issues/1369

Closing here.

**Comment by boothym** [comment]
Just wondering, how often does the debug map update?

**Comment by danpat** [comment]
It updates at the same time as the routing - the view is dynamically rendered by the routing engine, so it changes as soon as the data does.

**Comment by boothym** [comment]
Ok. I notice on the map that two similar roads have different speeds in the debug map: http://map.project-osrm.org/debug/#17.64/56.06277/-3.22708. This no doubt affecting the routing away from the primary road.
This service road is 26km/h - https://www.openstreetmap.org/way/75549910
While this residential road is 16km/h - https://www.openstreetmap.org/way/75550158
Any idea why there is a differences in speeds? Both have lanes=1 and 20mph speed limit.

**Comment by daniel-j-h** [comment]
Read: usually once a day, depends if we're hitting a but since we're also running nightly osrm builds there.

**Comment by boothym** [comment]
I notice the debug map has now updated to take into account the lanes=1, and the service road is no longer used for routing. Although it now uses the one way road just above it, instead of the primary road (see http://map.project-osrm.org/?z=17&center=56.063193%2C-3.223672&loc=56.064501%2C-3.231493&loc=56.063244%2C-3.223211&hl=en&alt=0)

**Comment by daniel-j-h** [comment]
For the route you posted:

http://map.project-osrm.org/?z=17&center=56.063199%2C-3.223672&loc=56.064501%2C-3.231493&loc=56.063244%2C-3.223211&hl=en&alt=0

this is its duration in seconds:

    http 'http://router.project-osrm.org/route/v1/driving/-3.231493,56.064501;-3.223211,56.063244' | jq '.routes[0].duration'
    111.7

now if we set a way point to force the route to stay on A921:

http://map.project-osrm.org/?z=17&center=56.063199%2C-3.223672&loc=56.064501%2C-3.231493&loc=56.060536%2C-3.229970&loc=56.063244%2C-3.223211&hl=en&alt=0

this is its duration in seconds:

    http 'http://router.project-osrm.org/route/v1/driving/-3.231493,56.064501;-3.229970,56.060536;-3.223211,56.063244' | jq '.routes[0].duration'
    121.3

So for OSRM staying on A921 is the worse option here.

Check out the debug map at this location for how speeds are determined:
http://map.project-osrm.org/debug/#17.02/56.06162/-3.22683
