### ISSUE TITLE
Implement Policy Based Data Loading

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3300]
Similar as to what @daniel-j-h already has tried to introduce once (https://github.com/daniel-j-h/osrm-backend/blob/39383855dd6958a0de3b9981b2780b4a37ce4b56/io/osrm_writer.hpp), we could consider implementing policies to do all the initialisation in the data facades.

In the [facade](https://github.com/Project-OSRM/osrm-backend/blob/04f8b653c946143360c43788b2f3d22bb5046ab3/include/engine/datafacade/bigramblock_datafacade_base.hpp#L139-L144) that is about to get merged, we see the following behaviour a lot.

 - request block ptr
 - resize owned memory / create a shared memory vector of it
 - copy memory / do some final initialisation with it

This behaviour is repeated all over the file and a prime candidate to do policy based loading and to reduce duplicated code.

In addition: Every entry we have in the storage should know how to get initialised from a chunk of memory, removing the responsibility from the facade to handle all of the initialisation. Any `ShM<T,true>` should behave just the same.

**Comment by TheMarex** [comment]
Policy is not the right design pattern here. Closing this as outdated.
