### ISSUE TITLE
Parsing Raster-Data causes exception

### ISSUE THREAD

**Issue by georgbachmann** [Project-OSRM/osrm-backend#3302]
Hello,
I'd like to make my routing elevation-data aware. I am following this awesome tutorial at https://www.mapbox.com/blog/third-party-data-in-osrm/ as it look exactly what I need. I also have a .asc file (used gdal to convert my geotiff) and stipped out the header-information so that the file only contains datapoints. I also provided min/max lat/lng in wgs84 format, but I end up getting this exception while parsing my data: 

```
terminate called after throwing an instance of 'osrm::util::exception'
  what():  ERROR occurred in profile script:
std::exception: 'Failed to parse raster source correctly.'
```

Any idea what I am doing wrong?

And... one more question... I can only use .asc files, right? So for a large region that would be a huge file?!?

**Comment by daniel-j-h** [comment]
The error comes from this location:

https://github.com/Project-OSRM/osrm-backend/blob/78583d2c8c639466bdde01c848398b2a48b72f44/include/extractor/raster_source.hpp#L67-L81

it's trying to parse a list of ints separated by spaces and fails doing so.
Seems like your data file does not follow this schema.

cc @lbud

**Comment by georgbachmann** [comment]
True, they are floats... (which all of our DEM data is). And NODATA is negative MAX-FLOAT.
For a test I'll try to convert that to ints with 0 as NODATA...

What would be a strategy for using very large DEM data sets? Cause as uncompressed .asc files, it's quite impossible, isn't it? Would it be possible to merge multiple .osrm files afterwards?

**Comment by daniel-j-h** [comment]
No merging osrm files is not really possible - if you need performance your best bet is to re-implement the raster grid data loading part linked above.

**Comment by daniel-j-h** [comment]
Closing as not actionable for us. Your data has to conform to the current expected format, as outlined above. If you want to expand or change this format, feel free to open a pull request with your ideas.
