### ISSUE TITLE
Osmium 2.10 crashes on larger datasets

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3303]
The Osmium 2.10 upgrade got merged without testing it on the planet: https://github.com/Project-OSRM/osrm-backend/pull/3296.
Smaller datasets / monaco / our tests seem to work out fine.

Today @MoKob reported a crash on BaWue:

> libc++abi.dylib: terminating with uncaught exception of type osmium::io_error: failed to uncompress data: data error

cc @joto

**Comment by emiltin** [comment]
I got this as recently as well, extracting a 200 MB dataset while working on #3266.

**Comment by joto** [comment]
That error should only happen if the input data is corrupt. Do debug this, test the input file with, for instance, `osmium_read` from the examples that are part of libosmium. That is about the simplest program you can think of that tests this case. It just reads a file and does nothing with the data. Or, if you have the osmium tool installed, use `osmium fileinfo -e FILENAME` to test. If you still get that error, it is definitely in libosmium and you can open an issue there (supply a link to the file you are using). If it doesn't happen there, it could be a data corruption problem somewhere else, or a library compatibility problem.

**Comment by daniel-j-h** [comment]
@emiltin can you confirm you're on macOS? We can't reproduce on Linux machines.

**Comment by emiltin** [comment]
yes mac

**Comment by MoKob** [comment]
newest master of libosmium fixes the crash on my end

**Comment by emiltin** [comment]
example with latest master on, mac, fresh download from geofabrik:

```
~/code/osrm-backend/sandbox$ (master) time ../build/osrm-extract finland.osm.pbf -p ../profiles/car.lua
[info] Using script ../profiles/car.lua
[info] Input file: finland.osm.pbf
[info] Profile: car.lua
[info] Threads: 4
[STXXL-MSG] STXXL v1.4.1 (prerelease/Release)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
[info] Parsing in progress..
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
[info] timestamp: 2016-11-12T20:28:02Z
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
libc++abi.dylib: terminating with uncaught exception of type osmium::io_error: failed to uncompress data: buffer error
Abort trap: 6

real	1m18.522s
user	4m8.944s
sys	0m16.053s
```

Sometimes i get:

```
Segmentation fault: 11
```

**Comment by daniel-j-h** [comment]
For the record @joto just fixed a bug upstream in libosmium - as soon as a proper release is done, we will include it and everything should be back to normal again.

**Comment by daniel-j-h** [comment]
@MoKob @emiltin please give https://github.com/Project-OSRM/osrm-backend/pull/3323 a try bundling @joto fixes from yesterday.

This should resolve your issues.
