### ISSUE TITLE
loadNodesFromFile should write into sets directly

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3306]
We deserialize into vectors but then immediately transform them to sets here:

- https://github.com/Project-OSRM/osrm-backend/blob/538bbd47d1ee169764b66df3ef67ecfe131cdfec/include/util/graph_loader.hpp#L65-L68
- https://github.com/Project-OSRM/osrm-backend/blob/78583d2c8c639466bdde01c848398b2a48b72f44/src/extractor/extractor.cpp#L429-L431

**Comment by MoKob** [comment]
Done in #3309
