### ISSUE TITLE
osrm::storage::Storage shouldn't contain shared memory logic

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3312]
`osrm-datastore` calls `::Storage::Run()` in order to allocate shared memory, and load data from files into it.

Because of https://github.com/Project-OSRM/osrm-backend/pull/3165, the `Storage` class is now used by non-shared-memory consumers as well.

The shared-memory specific logic should be refactored into a new class, and `Storage` should only be about loading data from disk into a pre-allocated memory block.

**Comment by TheMarex** [comment]
This follows the same pattern as `osrm-extract` -> `Extractor::Run`, `osrm-contract` -> `Contractor::Run`, `osrm-datastore` -> `Storage::Run`. `Storage` should contain the application specific code for `osrm-datastore`.

If we re-use some of that functionality somewhere else it should be split into an own class/function.
