### ISSUE TITLE
Re-use intersection forms

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3313]
In creating the edge-expanded graph, the workload for creating correct intersection forms has increased quite a lot from OSRM 5.4 to 5.5.

One thing we could do is to reduce the work performed [here](https://github.com/Project-OSRM/osrm-backend/blob/3235f30a988a77a3f0dcb100d65c8f37eac244c8/src/extractor/edge_based_graph_factory.cpp#L366-L378) by re-using intersection shapes.

The general problem is that we look at every intersection in the form
`node_u -> edge_u_v -> node_v` for every `node_v`. So if a node has four incoming roads, we compute the intersection shape at `node_v` four times (once for each road).

However: the general shape of the intersection does not change, depending on the incoming road.
We should make sure to re-use the intersection shape during the computation an only change the (possibly influenced by turn restrictions) flags that indicate allowed entry.

To do so, we need to restructure the processing the following way:

 - [ ] make [this](https://github.com/Project-OSRM/osrm-backend/blob/3235f30a988a77a3f0dcb100d65c8f37eac244c8/src/extractor/edge_based_graph_factory.cpp#L366) loop go over all intersections
  - [ ]  instead of [here](https://github.com/Project-OSRM/osrm-backend/blob/3235f30a988a77a3f0dcb100d65c8f37eac244c8/src/extractor/edge_based_graph_factory.cpp#L378) compute the intersection shape (at node_u) [here](https://github.com/Project-OSRM/osrm-backend/blob/3235f30a988a77a3f0dcb100d65c8f37eac244c8/src/extractor/edge_based_graph_factory.cpp#L368)
 - [ ] loop over all incoming edges [here](https://github.com/Project-OSRM/osrm-backend/blob/3235f30a988a77a3f0dcb100d65c8f37eac244c8/src/extractor/edge_based_graph_factory.cpp#L369) and set the correct turn-types/entry-allowed-flags [here](https://github.com/Project-OSRM/osrm-backend/blob/3235f30a988a77a3f0dcb100d65c8f37eac244c8/src/extractor/edge_based_graph_factory.cpp#L378-L384)

From the potential, we could be looking at a speed-up in creating the edge-based graph factory anywhere between two and three (given that the turn analysis still isn't free and the average degree of all nodes is somewhere around 2-4).

**Comment by TheMarex** [comment]
Sounds good. :+1:

If you are at it, could we also rename `node_u` and `node_v` to more sensible names? `source_node, via_node, target_node` would probably help make that loop more readable.

**Comment by MoKob** [comment]
This just landed
