### ISSUE TITLE
Alignment errors in the shared data facade

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#3326]
The current behavior in the shared data facade is to use 4 bytes alignment. The result of it some  UB sanitizer errors https://gist.github.com/oxidase/4b27137799ee8fc1c453f3a381ebe816
The output is for monaco.osrm with bold 8 bytes aligned data that could lead to UB

| Bid | #items | sizeof T | alignof T |
| --- | --- | --- | --- |
| FILE_INDEX_PATH | 77 | 1 | 1 | 
| NAME_OFFSETS | 102 | 4 | 4 | 
| NAME_BLOCKS | 102 | 16 | 1 | 
| NAME_CHAR_LIST | 8492 | 1 | 1 | 
| LANE_DESCRIPTION_OFFSETS | 3 | 4 | 4 | 
| LANE_DESCRIPTION_MASKS | 0 | 2 | 2 | 
| VIA_NODE_LIST | 6552 | 4 | 4 | 
| NAME_ID_LIST | 6552 | 4 | 4 | 
| TRAVEL_MODE | 6552 | 1 | 1 | 
| PRE_TURN_BEARING | 6552 | 1 | 1 | 
| POST_TURN_BEARING | 6552 | 1 | 1 | 
| TURN_INSTRUCTION | 6552 | 1 | 1 | 
| LANE_DATA_ID | 6552 | 2 | 2 | 
| ENTRY_CLASSID | 6552 | 2 | 2 | 
| HSGR_CHECKSUM | 1 | 4 | 4 | 
| GRAPH_NODE_LIST | 4022 | 4 | 4 | 
| GRAPH_EDGE_LIST | 13129 | 12 | 4 | 
| R_SEARCH_TREE | 1 | 532 | 4 | 
| **PROPERTIES** | 1 | 24 | 8 | 
| TIMESTAMP | 20 | 1 | 1 | 
| CORE_MARKER | 0 | 4 | 4 | 
| COORDINATE_LIST | 15706 | 8 | 4 | 
| **OSM_NODE_ID_LIST** | 8099 | 8 | 8 | 
| GEOMETRIES_INDEX | 2531 | 4 | 4 | 
| GEOMETRIES_NODE_LIST | 18700 | 4 | 4 | 
| GEOMETRIES_FWD_WEIGHT_LIST | 18700 | 4 | 4 | 
| GEOMETRIES_REV_WEIGHT_LIST | 18700 | 4 | 4 | 
| DATASOURCES_LIST | 0 | 1 | 1 | 
| DATASOURCE_NAME_DATA | 11 | 1 | 1 | 
| **DATASOURCE_NAME_OFFSETS** | 1 | 8 | 8 | 
| **DATASOURCE_NAME_LENGTHS** | 1 | 8 | 8 | 
| BEARING_CLASSID | 15706 | 4 | 4 | 
| BEARING_OFFSETS | 52 | 4 | 4 | 
| BEARING_BLOCKS | 52 | 16 | 1 | 
| BEARING_VALUES | 2559 | 2 | 2 | 
| ENTRY_CLASS | 20 | 4 | 4 | 
| TURN_LANE_DATA | 0 | 4 | 2 | 

Related issue #3267

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/issues/3318 and https://github.com/Project-OSRM/osrm-backend/issues/3328. Closing here. Thanks for investigating!
