### ISSUE TITLE
use different profiles for different areas

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#333]
in our region there's a number of municipality, who each have specific way to organize bike traffic. they often want this reflected  in how the routes works in their area. some want to put a high a priority on cycleways, others don't.

the differences only get bigger when you route across countries. one example would be left/right side driving and turn restrictions.

so it might be useful to be able to change/override speedprofile/lua parameters depending on the area you're extracting.

**Comment by danpat** [comment]
@TheMarex and I were discussing this in the context of turn profiles (left/right bias, depending on country).  

It would also be useful to do this on an even-more-granular level, like state/province/city.  One example for this is "right-turn-on-red", which is permitted in many north american locations, but is forbidden in New York City, unless permitted by a sign, and also in Montréal.

**Comment by TheMarex** [comment]
I would like to implement this on a lua-level similar to how we implemented the raster feature.

- function to load admin boundary polygons and build and index from them (R-Tree based + point-in-polygon test on lowest level)
- function to query from lua `get_country(bounding_box)` which returns the country code like `de` or `gb`

Blocked by:
- Not having the coordinate of the referenced nodes (=> no bounding box) when calling `way_function`

**Comment by TheMarex** [comment]
We might want to expose this country information alongside with country specific information in the response. This includes:
- handedness of the country (`left`, `right`)

/cc @1ec5

**Comment by danpat** [comment]
I started sketching out support for this in this PR: https://github.com/Project-OSRM/osrm-backend/pull/4167

The aim here would be to supply a GeoJSON file with polygons defining the boundaries of the regions you're intersted in, then the `way_function` would be passed a table of the regions that the current way belongs to.

**Comment by daniel-j-h** [comment]
Using location-dependent data is now possible in the profiles:

https://github.com/Project-OSRM/osrm-backend/wiki/Using-location-dependent-data-in-profiles

Also see
- https://github.com/Project-OSRM/osrm-backend/pull/4167
- https://github.com/Project-OSRM/osrm-backend/pull/4415

**Comment by TimMcCauley** [comment]
@emiltin @danpat maybe you can help me out on a specific issue I am trying to solve. Given a polygon, e.g. Paris or London, am I able to decrease the OSM speeds by X percent with this location dependent data logic? The OSM speeds make total sense for more rural areas, however diving in to metropolitan regions and comparing them to proprietary services they are too optimistic (which obviously makes sense). I think a factor would do most of the job; I'm just trying to figure out the best approach.

**Comment by TimMcCauley** [comment]
Leaving this information here for anybody trying to achieve the same. In your lua file you can add this snippet after the maxspeed etc. handling.

```
  ...
  forward_sp = result.forward_speed
  backward_sp = result.backward_speed

  factor = 1.0
  if way:get_location_tag('london') then
    factor = 0.7
  end

  if forward_sp and forward_sp > 0 then
    result.forward_speed = forward_sp * factor
  end

  if backward_sp and backward_sp > 0 then
    result.backward_speed = backward_sp * factor
  end
  ...
```

And then just provide a (multi)polygon when you run `osrm-extract`... 

`docker run -t -v "${PWD}:/data" osrm/osrm-backend:v5.23.0 osrm-extract -p /data/car-custom.lua --location-dependent-data=/data/london.geojson /data/britain-and-ireland-latest.osm.pbf`
