### ISSUE TITLE
osrm-contract seems to hang with foot profile on Moscow extract

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3331]
A user reported in Slack that running `osrm-contract` seems to hang after 90% (they waited 3 days) when processing https://s3.amazonaws.com/mapbox/playground/danpat/moscow_russia.osm.pbf extracted using `foot.lua`.  This extract was copied from Mapzen's metro-extracts page a couple of weeks ago.

I've reproduced the problem locally (I waited a couple of hours), and @TheMarex has also confirmed that contraction runs very slowly for this extract.  Other maps of a similar `.pbf` size don't seem to have this problem.

There's a good chance that the problem is simply an exploding CH, an unfortunate combination of this profile and this map and there's not much we can do without modifying how we're calculating the node priority order.

**Comment by nextstopsun** [comment]
Tried to workaround with the patch provided by @danpat and @TheMarex. Applied patch against current master, rebuilt, but now it got stuck even earlier - on 70% for 6 hours already. Used the same osm pbf as before. I can provide `osrm-extract` results for debugging if necessary.

**Comment by TheMarex** [comment]
@nextstopsun what is your build environment? This seems like there is going something wrong with an old tbb version maybe? I ran this yesterday on my tiny laptop and it finished in 25mins on that dataset (with the patch).

**Comment by nextstopsun** [comment]
I'm building on OS X with latest XCode. @TheMarex Can you please point me where to look for missing/outdated stuff?

**Comment by TheMarex** [comment]
`osrm-contract` dependencies I could see breaking this:

- libtbb
- libboost

On a side note: You are compiling in release mode, right?

**Comment by nextstopsun** [comment]
Yep, compiling in release mode. Maybe compiling in debug mode makes sense?

**Comment by daniel-j-h** [comment]
@danpat @TheMarex what's the state of this?

@MoKob is seeing a similar issue with the car profile on Argentina.

**Comment by nextstopsun** [comment]
I've tried with some later extracts, but no luck - contraction step still freezes forever.

**Comment by zabuTNT** [comment]
Hi,
I had a similar issue with Italy-N.E. map and foot profile:
http://download.geofabrik.de/europe/italy/nord-est.html
It stucks at 90%, I didn't wait days, but with car profile there are no problems, and all ends in half an hour.

There is a solution to this? If I use the Europe map or full Italy map change somethings? (I ask it before to launch a similar task for nothing)

Thanks in advance

**Comment by miccolis** [comment]
This issue appears stale. Please re-open if this issue persists.

**Comment by daniel-j-h** [comment]
For the record this is still an issue and there are similar tickets around. Let's track in https://github.com/Project-OSRM/osrm-backend/issues/3876.
