### ISSUE TITLE
Refactor weight/penalty update logic

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3349]
In preparation for https://github.com/Project-OSRM/osrm-backend/projects/3, we need to move the weight/penalty update part of `osrm-contract` into a re-usable class.  Once MLD lands, we will want to perform the same traffic update logic from the `osrm-customize` tool.

Both `osrm-contract` and `osrm-customize` will operate on the Edge Based Graph, so the logic should basically be the same.

**Comment by TheMarex** [comment]
This landed in `master` as the `updater` module which is used by `osrm-customize` and `osrm-contract`.
