### ISSUE TITLE
Implement MLD query algorithm

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3351]
As part of https://github.com/Project-OSRM/osrm-backend/projects/3, we will be generating an alternative speedup datastructure for OSRM called MLD.

Generating routes from the MLD overlay requires a modified search algorithm - the bidirectional Dijkstra search as implemented is specific to our CH graph.

The MLD search algorithm depends on the output of https://github.com/Project-OSRM/osrm-backend/issues/3350.

This work should start after https://github.com/Project-OSRM/osrm-backend/issues/3203 and https://github.com/Project-OSRM/osrm-backend/issues/3350 are complete, and should provide a third routing algorithm that various plugins can use.

**Comment by daniel-j-h** [comment]
Related: https://github.com/Project-OSRM/osrm-backend/issues/3208

**Comment by TheMarex** [comment]
1. Extend `Storage` to support optional files:
    - Load `.hsgr` file if present
    - Load `.overlay` file if present (see #3553)
    - Load `.partition` file if present (see #3552)
2. Make datafacade conditionally load either MLD or CH information based on algorithm
3. Implement a query based on MLD:
    - `RoutingBaseInterface::Search()` needs to be specialized for MLD using #3208
    - `RoutingBaseInterface::UnpackPath()` needs to be specialited for MLD using #3208  
    - `SearchEngineData` probably needs to be adapted for MLD to have a cache for unpacking paths (needs mutable state)

Search:
- Bi-directional Dijkstra
- Take node out of queue
- Determine level it is relevant for search (via #3552)
- If the level is 0 (base graph) scan all outgoing (or incoming) edges
- If the level higher then one:
  - Scan all outgoing (or incoming) edges that lead to vertices in different cells (on its level)
  - Scan all outgoing (or incoming) edges represented by the cell which can be retrieved via (#3553)

Unpacking:
- Top-Down: For a pair of border vertices `i` and `j` at level `l` find shortest path at level `l-1` only using the cell matrices of `l-1`.
- Add resulting edges of the shortest path to a queue
- Unpack pair from the queue until we hit level 0 at which we need to do a search on the base graph
- Assemble resulting route on the base graph and return result as list of Edge-Based-Edge ids

**Comment by TheMarex** [comment]
This shipped with #3759.
