### ISSUE TITLE
Update Variant to latest Release

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3356]
We're currently running with the Mapbox Variant release 1.1.0 from February. Update to 1.1.4.

This should get us (among other fixes and features)

- https://github.com/mapbox/variant/pull/128 `.match` which is great for downstream users (cc @jcoupey)
- https://github.com/mapbox/variant/pull/126 (hashable response)

**Comment by danpat** [comment]
Done with 29b3caf5293586cf3f790daaa8402c232ba27b90 and #3392

**Comment by daniel-j-h** [comment]
I like your pragmatism but did you just push to master break our subtree and not use or update the dependency script?
