### ISSUE TITLE
Opensource Android client for OSRM

### ISSUE THREAD

**Issue by MKergall** [Project-OSRM/osrm-backend#336]
Just for information, osmbonuspack (an opensource library for building Android apps using OSM) provides routing feature based on OSRM service. 
Project repository is here: http://code.google.com/p/osmbonuspack/
And a comparison of routing services is here: http://code.google.com/p/osmbonuspack/wiki/WhichRoutingService

**Comment by apacha** [comment]
I would be interested in offline OSRM too. Anything we can refer to?

**Comment by daniel-j-h** [comment]
maps.me bundles osrm for offline maps and routing. Nothing from out side here.

**Comment by apacha** [comment]
I just found maps.me too. Awesome. Thanks for the hint.
