### ISSUE TITLE
Handle junction=circular for Not-a-Roundabouts

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3361]
We have multiple roundabout'ish situations to handle:

- Proper Roundabouts. Think: "at the roundabout take the nth exit".
- Roundabout Intersections. These are roundabouts with up to four ways and turn angles which makes the turns obvious. Think: "at the roundabout turn left".
- Rotaries. These are large and named roundabouts. Think: "at Meinplatz take the nth exit".

There is one additional edge-case which we want to handle now: **Not-a-Roundabout**. There are situations where one of the entering road has right of way, which disqualifies the scenario for being classified as a roundabout. The Wiki has a [section on these Not-a-Roundabouts](http://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout#Not_a_roundabout):

> In all these cases, the key “junction” is not necessary at all. You need no special tagging.
Most of these Not-a-Roundabouts have a note on them, telling users not to
tag them as junction=roundabout as this is a common mistake. Here are two
examples in Berlin:

- [Bersarinplatz](http://www.openstreetmap.org/way/288767318#map=19/52.51849/13.45355&layers=D
)
- [Kottbusser Tor](http://www.openstreetmap.org/way/159155852#map=19/52.49898/13.41881&layers=D)
- [Strausberger Platz](http://www.openstreetmap.org/way/30825182#map=19/52.51850/13.42896&layers=D)
- [Grosser Stern](http://www.openstreetmap.org/way/4413638#map=18/52.51456/13.35041&layers=D)

The routing engine is not able to issue special instructions since there is no tag to parse. And
parsing note tags for the occurrence of roundabout is not a solution.

---------------------------------------------------------------------------------------------------------------------

After some discussion on the [tagging mailinglist](https://lists.openstreetmap.org/pipermail/tagging/2016-November/030520.html
) we now have a `junction=circular` tag for exactly this. And by now all the roundabouts above are already tagged with it!

Here is its Wiki page for now: https://wiki.openstreetmap.org/wiki/Tag:junction%3Dcircular

Let's handle it!

I'll implement this asap so we can see the change in behavior on the demo server in 1-2 days.

**Comment by polarbearing** [comment]
The funny thing is that in #3362 I find the previous announcements more intuitive than the new ones. As you realise already, the small roads can spoil your exit counting: the service lane here, and the small residential roads at Kotti. 

And in your implementation you call the circular junction a roundabout, which might cause confusion. 

Now look into Grosser Stern, which has the "spiralling out" lane layout. The driver needs much more assistance to pick the correct lane, than to ask her to count exits, which has its difficulties with the 5 main arms and the dual carriageways joining. 

And indeed lane support would be helpful for both junction=roundabout and =circular, since the next one you go through is Ernst-Reuter-Platz, which is a true roundabout and has spiralling lanes as Grosser Stern.

**Comment by MoKob** [comment]
@polarbearing service roads are a general problem in roundabouts. https://github.com/Project-OSRM/osrm-backend/pull/3363 adds logic (which sadly introduces some ambiguity) adds logic to not announce these as dedicated exists.

A normal road is still something that would be considered.

For the lanes issue, we are not able yet to handle lanes in roundabouts (which makes not treating them as roundabouts not an option to solve it), which would make no difference so far from which lanes to take. At some point we would love to change this.

However, we don't announce these as roundabouts, but as rotaries/traffic circles. The format so far is the same as in a roundabout (single instruction), but from the OSM notes and people tagging these circles as roundabout all the time you can imagine that these `circular` junctions are often conceived as `roundabout`. In OSRM 6.0 we are planning to switch to a `two` instruction layout (enter/exit) which in turn would make it similar to the current instruction format but allows us to better detect that we are staying on the traffic circle.
Currently it is very hard to distinguish between staying on the road/exiting. This would lead to multiple `turn slight left` instructions to simply stay on the road.

**Comment by polarbearing** [comment]
Thanks, I see the overall situation is well considered by you, folks. I understood that from the tagging perspective you needed the support for reporting the correct ground truth, which we have now with the new ```junction=circular``` tag. Make the best out of it :) 
I had added the turn:lanes to most of these large circles a while ago, would be good to see them in action.

**Comment by MoKob** [comment]
@polarbearing We will do our best to increase support for lanes. I agree that especially in situations like _Grosser Stern_, having lanes would be more than desirable.

**Comment by daniel-j-h** [comment]
Here is some context for why we removed lanes from all roundabouts when we looked into the situation in our initial lanes and especially lane anticipation efforts https://github.com/Project-OSRM/osrm-backend/pull/2693. And here is the ticket to get proper lane support in roundabouts back https://github.com/Project-OSRM/osrm-backend/issues/2843.

**Comment by daniel-j-h** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/3362 just landed in master - `junction=circular` should be visible on the demo server on next data cycling (once per day). As outlined above this is a first step in the right direction and a building block for further roundabout improvements. Closing this ticket here.
