### ISSUE TITLE
optimize tag access from LUA profiles

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#3369]
Calling into C++ from LUA incurs a context-switch. This means that fetching each tags from the profile with a call to way:get_value_by_key() is slow. The car profile typically fetches 40-50 tags per way (most of which will typically be nil).

It might be faster to pass all tags directly to LUA in a table when calling the way_function(), so that the LUA code can access tags in a LUA table, without calling into C++.

Ie. instead of:

```lua
function way_function(way, result)
  if way:get_value_by_key('highway') then
    -- something
  end
end
```

you would do:

```lua
function way_function(way,tags, result)
  if tags.highway then
    -- something
  end
end
```

To avoid copying tags the profile will not need, the profile should have a property listing the that should be passed to LUA. This might have the added benefit of making it easy to update the osrm tag info.

Thoughts?

**Comment by daniel-j-h** [comment]
This means changing the callback's API and therefore has to be scheduled for a major release.

I'd love to have this since doing so many context switches for comparing some string tags is just crazy. Any ideas on how to do this without breaking the API? Providing two interfaces for the time being and deprecating the old one?

Related: instead of switching from C++ to Lua on every Node, Way we could do the parsing in chunks of n Nodes, Ways and wrap the Lua callbacks in a loop: https://github.com/Project-OSRM/osrm-backend/issues/1777.

**Comment by TheMarex** [comment]
I like that new interface. I'm not sure how easy this would be to build with luabind / sol2 though (maybe this would be as easy as exposing a `std::unordered_map`).

We might want to run out a prototype to see if always copying all tags to lua is faster then doing it on-demand with context-switch penalties.

w.r.t. breaking the API, I think we should aim decouple breaking API changes with new features. Thus like @daniel-j-h suggested we could go with providing two interfaces, officially deprecating the old one and removing in the next major release. This is already how we handle HTTP API changes.

In the same spirit we could try to make #2399 non-API breaking.

**Comment by emiltin** [comment]
I tried it with the following code in LuaScriptingEnvironment::ProcessElements:

```c++
case osmium::item_type::way:
    result_way.clear();
    if (local_context.has_way_function)
    {
        const osmium::Way& way = static_cast<const osmium::Way &>(*entity);
        luabind::object tags = luabind::newtable(local_context.state);
        tags["highway"] = way.get_value_by_key("highway");
        tags["oneway"] = way.get_value_by_key("oneway");
        tags["width"] = way.get_value_by_key("width");
        tags["lanes"] = way.get_value_by_key("lanes");
        tags["service"] = way.get_value_by_key("service");
        tags["route"] = way.get_value_by_key("route");
        tags["bridge"] = way.get_value_by_key("bridge");
        tags["area"] = way.get_value_by_key("area");
        tags["toll"] = way.get_value_by_key("toll");
        tags["impassable"] = way.get_value_by_key("impassable");
        tags["status"] = way.get_value_by_key("status");
        tags["duration"] = way.get_value_by_key("status");
        tags["side_road"] = way.get_value_by_key("side_road");
        tags["surface"] = way.get_value_by_key("surface");
        tags["tracktype"] = way.get_value_by_key("tracktype");
        tags["smoothness"] = way.get_value_by_key("smoothness");    
        tags["junction"] = way.get_value_by_key("junction");    
        tags["capacity:car"] = way.get_value_by_key("capacity:car");    
        tags["name"] = way.get_value_by_key("name");    
        tags["name:pronunciation"] = way.get_value_by_key("name:pronunciation");    
        tags["ref"] = way.get_value_by_key("ref");    
        tags["hov"] = way.get_value_by_key("hov");    
        tags["hov:lanes"] = way.get_value_by_key("hov:lanes");    
        tags["hov:lanes:forward"] = way.get_value_by_key("hov:lanes:forward");    
        tags["hov:lanes:backward"] = way.get_value_by_key("hov:lanes:backward");    
        tags["maxspeed"] = way.get_value_by_key("maxspeed");    
        tags["maxspeed:forward"] = way.get_value_by_key("maxspeed:forward");    
        tags["maxspeed:backward"] = way.get_value_by_key("maxspeed:backward");    
        tags["maxspeed:advisory"] = way.get_value_by_key("maxspeed:advisory");    
        tags["maxspeed:advisory:forward"] = way.get_value_by_key("maxspeed:advisory:forward");    
        tags["maxspeed:advisory:backward"] = way.get_value_by_key("maxspeed:advisory:backward");    
        tags["lanes:psv"] = way.get_value_by_key("lanes:psv");    
        tags["lanes:psv:forward"] = way.get_value_by_key("lanes:psv:forward");    
        tags["lanes:psv:backward"] = way.get_value_by_key("lanes:psv:backward");    
        tags["destination"] = way.get_value_by_key("destination");    
        tags["destination:forward"] = way.get_value_by_key("destination:forward");    
        tags["destination:backward"] = way.get_value_by_key("destination:backward");    
        tags["destination:ref"] = way.get_value_by_key("destination:ref");    
        tags["destination:ref:forward"] = way.get_value_by_key("destination:ref:forward");    
        tags["destination:ref:backward"] = way.get_value_by_key("destination:ref:backward");                        
        local_context.processWay(way, result_way, tags);
    }
    resulting_ways.push_back(std::make_pair(x, std::move(result_way)));
    break;
```

We create a LUA table and assign all the fields we might need (manually since this is just test), and pass it to way_function(). I also adapted the car profile and helpers to fetch all tags via the table.

Unfortunately I see a slow down. Processing time of the parsing step increases from around 6.0 s to 6.6 s.

If I don't only assign the highway tag to the table (to avoid early abort in the profile), it takes around 5.5 s. (The processing will be a bit different because some tags are missing, but it should still be an valid approximate value.) 

It seems to indicate that the slow part is one of:

1. the osmium call to get_value_by_key()
2. assigning/accessing the LUA table
3. fetching all tags, even though we often dont' need to.

Maybe it would improve if we don't create the table each time, but reuse and clear a table object?

**Comment by MoKob** [comment]
I am not firm on the details of luabind/c++ interaction. But could every one of  these calls: `tags["destination:ref:backward"] = way.get_value_by_key("destination:ref:backward");` imply a context switch in the other direction than we had before?

After all, every one of these calls is now passing the `c++` to `lua` barrier the other way around, right? We still have to do a single communication between both worlds to pass data, or am I off here?

**Comment by emiltin** [comment]
But something like that is probably happening. I tried assigning raw strings to the table, instead of fetching from osmium, e.g:

```c++
tags["highway"] = "highway";
```

This is even slower, at 7.3 s. Probably because the assignment/fetching is still slow, and having all tags set trigger additional processing in the profile?

Any ideas for how to pass tags effective to LUA?

**Comment by MoKob** [comment]
Sadly I don't think that it is possible to avoid the context switches while keeping the same flexibility. After all, transferring single items between lua/c++ should have to pass the barrier every time.
Only if we were to provide a strange encoding scheme that can be transferred as a single entity (e.g. string) and then understood in lua, we could reduce the number of context switches.

**Comment by emiltin** [comment]
With the code shown above I thought I created the table in C++ land, and then transferred it in a single step. You think the context switch happens when we assign or when we later read?

Passing and parsing a string would be an option, but whether it's effective I don't know.

**Comment by danpat** [comment]
@emiltin https://github.com/osmcode/libosmium/blob/9c0d4bb41d14da3e1d768a2eb14ca27685e59c14/include/osmium/osm/tag.hpp#L109-L112

Looks like calling `get_value_for_key()` triggers a linear search over the tags on a way each time.  

Can you try something like this?

```
std::unordered_set<std::string> interesting_keys  {"highway","oneway",....}

case osmium::item_type::way:
    result_way.clear();
    if (local_context.has_way_function)
    {
        const osmium::Way& way = static_cast<const osmium::Way &>(*entity);
        luabind::object tags = luabind::newtable(local_context.state);
        for (const auto tag : way.tags()) {
          if (interesting_tags.find(tag.key()) != interesting_tags.end()) {
            tags[tag.key()] = tag.value()
          }
        }
        local_context.processWay(way, result_way, tags);
    }
    resulting_ways.push_back(std::make_pair(x, std::move(result_way)));
    break;
```

This should eliminate the linear search overhead for the tags we want (replacing it with the lookup overhead of std::unordered_map(), which should be constant time).

**Comment by danpat** [comment]
Looking at it, `std::unordered_map<std::string,bool>` and `count()` might be better -> `std::unordered_map` is constant lookup timing, so it probably does better overall than `std::set`

**Comment by emiltin** [comment]
thanks @danpat this is certainly a good idea.

but it seems the problem is that luabind::newtable() creates the table inside the lua context, and each time we assign to it, we incur a slow context switch. we need to find a faster way to pass the tags to way_function(), perhaps as @MoKob as a single encoded string that we rthen unpack on the lua side.

it tried such a single string approach but couldn't figure out how to pass a string to way_function, it keeps crashing. seems like it should be easy...

btw, can osmium filter tags at an earlier stage when reading the input file, or is the loop we're looking at here already the earliest chance to filter the input data?

**Comment by emiltin** [comment]
@danpat i tried your suggestion using std::set<std::string>, but it's a bit slower. but anyways the main issue is to find a faster way to pass the tags to lua, as mentioned above.

**Comment by danpat** [comment]
@emiltin Given that you're just experimenting, do you think you can push things to the Lua stack directly?  I have no idea if this will work, but it might be worth a shot.  Here's what I came up with based on some of the Lua docs:

```cpp

std::unordered_map<std::string,bool> interesting_keys  {
  {"highway",true},
  {"oneway",true},
...
}

case osmium::item_type::way:
    result_way.clear();
    if (local_context.has_way_function)
    {
        const osmium::Way& way = static_cast<const osmium::Way &>(*entity);
        lua_newtable(local_context.state);
        for (const auto &tag : way.tags()) {
          if (interesting_tags.count(tag.key()) > 0) {
            lua_pushstring(local_context.state, tag.key()); // push the key into the table
            lua_pushstring(local_context.state, tag.value()); // push the value into the table
          }
        }
        lua_setglobal(local_context.state, "way_tags");  // sets a global table called "way_tags"
        local_context.processWay(way, result_way, tags);
    }
    resulting_ways.push_back(std::make_pair(x, std::move(result_way)));
    break;
```

It seems pretty light-weight.

**Comment by emiltin** [comment]
I tried your unordered_map + pushstring approach. I needed to add a lua_settable(local_context.state, -3) for each tag.

But it's just as slow, around 6.7 s. The original code which fetches each tag via C++ is around 6.0 s.

I will try passing a single encoded string.

**Comment by joto** [comment]
Libosmium does a linear search on the tags, but that should be plenty fast for almost all cases. Most objects have only very few tags and a linear search means linear memory access in the area where the tags are located. Creating a tree (std::map) or a hash (std::unordered_map) will have an immense overhead for the common case.

I don't know much about Lua, but maybe you can give the whole `tags()` data to Lua in one buffer and then use Lua to get the tags out. Basically what is behind `tags()` is a continuous piece of memory with a header (containing type and length) and then `key1\0value1\0key2\0value2\0`... If you can interpret this from Lua, you can reimplemen the `get_value_by_key()` function in Lua and maybe have less overhead. Of course this has the drawback that you are tied to the libosmium C++ implementation details, which is, strictly speaking, not okay. But if this is something that helps a lot we can think about documenting this properly in libosmium.

A cleaner, but a bit less flexible method would be to go through the tags first on the C++ side and create an array of pointers such that tags[0] -> highway value, tags[1] -> maxspeed value etc. Then give this table to Lua. You can't have a faster access than that. But building the array of pointers takes time independant of how many of the tags will be used later. This is probably still fast, because you only iterate over the tags once, checking all possible keys for each existing key. If you order your key checks by how often you expect the keys to appear, so `highway` first, `maxspeed` later, it should be reasonably fast etc:

    for (const auto& tag : tags) {
        if (! strcmp(tag.key(), "highway")) tag_lookup[0] = tag.key();
        if (! strcmp(tag.key(), "maxspeed")) tag_lookup[1] = tag.key(); 
    }

Of course this also needs some way of accessing the strings through the `tag_lookup` array from Lua and I don't know enough about Lua to see whether that's possible.

**Comment by MoKob** [comment]
Even though I brought up the idea, it was meant in no way as a suggestion. An intermediate format in some other encoding is nothing we should go for. The problems regarding maintainability are a price I wouldn't agree to pay.

I'd expect any reasonable structure we can create will always imply a context switch for any access.

**Comment by emiltin** [comment]
A context switch yes, but hopefully we don't need one for each tags?

**Comment by MoKob** [comment]
If there is a data-structure in luabind that can be transferred and decoded simply, then yes. But otherwise we will have a switch for every tag. I believe that there probably is no support for transferring anything else but plain data types (which would make structured data require multiple switches). But I am not firm on the details of luabind, its just an assumption.

**Comment by emiltin** [comment]
I tried encoding all tags into a string and passing it to the way_function:

```c++
const osmium::Way& way = static_cast<const osmium::Way &>(*entity);
std::string tags = "";
for (const auto &tag : way.tags()) {
    if (tag.value()[0] != 0 ) {
        tags += tag.key();
        tags += "\n";
        tags += tag.value();
        tags += "\n";
    }
}

local_context.processWay(way, result_way, tags.c_str());
```

and then decoding in lua:

```lua
function way_function(way, result, tags_string)
  local tags = {}
  local key = nil
  for line in tags_string:gmatch("[^\n]+") do  -- split into lines
    if key then
      tags[key] = line
      key = nil
    else
      key = line
    end
  end
```

And then accessing tags via tags[] instead of way:get_value_by_key(). It works, but it's still slow, around 7 s. (Master is around 6 s.) Only encoding tags the we're interested in (as par @danpat's suggestion) doesn't make any real difference.

**Comment by emiltin** [comment]
Going to close this for now, especially in light of luabind being replaced by sol in #3382.
