### ISSUE TITLE
How to decode a hint and what is a hint?

### ISSUE THREAD

**Issue by chasenicholl** [Project-OSRM/osrm-backend#3375]
Hey all,

When using the nearest function, for example http://osrm.server.com/nearest/v1/driving/-73.995014,40.693194.json

The response is...

```
{
"waypoints":[
    {
        "hint":"7FgEgP___3-EfgEAUwAAAFkAAAAAAAAAAAAAALRRLQCnRy0AZQQAAOzslvuT7WwC-uyW-8rtbAIAAAEBKoRsEg==",
        "distance":6.230339,
        "name":"Joralemon Street",
        "location":[-73.995028,40.693139]
    }
    ],
    "code":"Ok"
}
```

That isn't a valid Base64 string, yet the docs say it should be. What is the hint exactly, and how do I decode it? Any insight would be much appreciated, thanks all.

**Comment by danpat** [comment]
The "hint" is a private representation of the coordinate that was found.  You can re-used the value in subsequent requests to speed things up - providing the hint bypasses the somewhat expensive "rtree search" part of each request.

They're not intended to be decoded on the client side.

https://github.com/Project-OSRM/osrm-backend/blob/v5.4.3/docs/http.md#general-options
