### ISSUE TITLE
Allow collapsing staggered intersections with mode changes

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#3376]
With this pr https://github.com/Project-OSRM/osrm-backend/pull/3324 we're allowing intersections to be considered staggered if there is a mode change between the staggered same name streets. E.g.,

```
      """
          j
      a b c
          d
          e f g
          h
      """
| way   | name      | mode    |
| abc   | first st  | pushing |
| efg   | first st  | cycling |
| jbdeh | second st | cycling |

route a to g
```

However, [the following `compatible()` check](https://github.com/Project-OSRM/osrm-backend/blob/fe5cc55b0e98204b7e56037fba7c2f8b2adbd9b2/src/engine/guidance/post_processing.cpp#L1178) does not allow mode changes between previous previous step and current step, regardless of what `isStaggeredIntersection()` returned. The obvious solution of using a redundant `|| isStaggeredIntersection()` results in a socket hangup of some kind and needs further investigation.

This change might require a bigger change and should probably be considered during a refactor of all of post-processing.

cc @MoKob

**Comment by TheMarex** [comment]
Similar to #3256, we will not tackle this issue because we will be replacing the surrounding logic.
