### ISSUE TITLE
Version flag for profiles

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3384]
Currently when we want to make changes to the profiles that are not backward compatible we would do a major version bump of `osrm-backend`.

However that also means that profiles that were not ported properly will fail (maybe even silently) if they are not adjusted to API changes.

To make this explicit and open up the possibility for supporting multiple profile API version we should add a version flag to `ProfileProperties` so we could load the appropriate version of the scripting context.

**Comment by daniel-j-h** [comment]
Interesting. 

For a start can't we simply expose the OSRM version we set in CMaketo Lua and _also_ set a required version in the Lua profiles? Then the profiles could check their version against the OSRM version currently running.

This would catch profile mismatches and would even allow the profiles to specify required version bounds. Think of profiles specifying `> 5.4 && < 5.5` and the OSRM version bound via Luabind then reporting `5.4.3`.

**Comment by TheMarex** [comment]
Hrm you think that will be less error prone then doing another sequential version like we do for the HTTP API? I was thinking about something like:

```lua
properties.version = 1 -- (default value for everything below 5.5)
```
When we load the scripting context we use that version number to load the appropriate bindings. The default value makes sure that at least every current profile in existence will be backward compatible and needs to be upgrade explicitly once we change the profile API.

We could throw a deprecation warning if your profile does not expose the current version, but still support older versions.

**Comment by TheMarex** [comment]
For the record we settled on a global `api_version = 1` in every profile file.

**Comment by daniel-j-h** [comment]
This landed with https://github.com/Project-OSRM/osrm-backend/pull/3487.
