### ISSUE TITLE
car profile should respect oneway:vehicle, etc.

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#3387]
The car profile does not respect the mode specific oneway tags:

oneway:motorcar
oneway:motor_vehicle
oneway:vehicle

These should reflect the access tags hierrachy:

access_tags_hierarchy = Sequence {
  'motorcar',
  'motor_vehicle',
  'vehicle',
  'access'
}

**Comment by daniel-j-h** [comment]
We handle these mode-specific values for restriction parsing and except tags internally based on this list:

https://github.com/Project-OSRM/osrm-backend/blob/560d8ffec090bf0cdd67d9a561e356f2bbb73957/profiles/car.lua#L63-L64

**Comment by emiltin** [comment]
Yes,. That list is equal to this list, except from the root 'access':
https://github.com/Project-OSRM/osrm-backend/blob/560d8ffec090bf0cdd67d9a561e356f2bbb73957/profiles/car.lua#L47

We should get rid one of the lists.

**Comment by emiltin** [comment]
fixed with the recent refactoring of profiles
