### ISSUE TITLE
Windows Build is broken

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3388]
With the recent merge of the io refactor, it seems the windows build broke:

 - [ ] fix failing test on appveyor (C:/projects/osrm/unit_tests/util/io.cpp(125): fatal error: in "osrm_io/io_read_lines": Expected the first line to be A)

/cc @danpat

**Comment by daniel-j-h** [comment]
For the record: 

https://github.com/Project-OSRM/osrm-backend/blob/5775679f64747702342b9f5a536817d17ec2c60b/unit_tests/util/io.cpp#L125

This should not fail cc @ghoshkaj

**Comment by daniel-j-h** [comment]
By the way printing the expected error messages in the tests there is somewhat confusing:

> Error opening non_existent_test_io.tmp:No such file or directory
> Error reading from file_too_small_test_io.tmp: Unexpected end of file
> Fingerprint mismatch in corrupt_fingerprint_file_test_io.tmp
> C:/projects/osrm/unit_tests/util/io.cpp(126): fatal error: in "osrm_io/io_read_lines": Expected the first line to be A

the first three lines are expected (!) errors. The last one is not.

**Comment by ghoshkaj** [comment]
Fixed with https://github.com/Project-OSRM/osrm-backend/pull/3391
