### ISSUE TITLE
assertion while osrm-extract stage.

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#3396]
I got an assertion message
```
[info] generating edge-expanded edges
[assert] /osrm-backend/src/extractor/guidance/coordinate_extractor.cpp:1087
in: double osrm::extractor::guidance::CoordinateExtractor::ComputeInterpolationFactor(double, double, double) const: distance_to_first < desired_distance
```
when I built master and called the osrm-extract for map with NYC inside.

I called osrm-extract with parameters: ```-p osrm-backend/profile.lua --generate-edge-lookup```

**Comment by gardster** [comment]
extracting with HEAD~50 version helped me.

**Comment by MoKob** [comment]
I've just fixed two errors in the coordinate extraction over in #3397 . Using the new york extract of today it works fine on my end, when it did not before.

**Comment by TheMarex** [comment]
@MoKob on the demo server we just hit:

```
in: double osrm::extractor::guidance::CoordinateExtractor::ComputeInterpolationFactor(double, double, double) const: distance_to_second >= desired_distance
[assert] /mnt/ebs/osrm/2016-12-02-173001/src/extractor/guidance/coordinate_extractor.cpp:1090
```

Is this the same bug? The line number is different. Happend around 0:36 UTC not sure which gitsha.

**Comment by gardster** [comment]
I recontract the map and now it works on master. Thank you for the quick fix!

**Comment by MoKob** [comment]
From the assertion alone it's impossible to tell if that is the same error or not. Could be, but I can't tell. I've fixed two errors leading to calls with invalid arguments, but I can't tell if the above error is due to the these.
