### ISSUE TITLE
Strip spaces around tag values

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3405]
Running `osrm-extract` over `north_america_latest.osm.pbf` from GeoFabrik in Debug mode gave me the following warnings:

```sh
[info]   vehicle
[debug] Unsupported lane tag found: " slight_right"
[debug] Unsupported lane tag found: " slight_right"
[debug] Unsupported lane tag found: " slight_right"
[debug] Unsupported lane tag found: " slight_right"
[debug] Unsupported lane tag found: "though"
```

We should strip the spaces around tokens before using them - although technically this is mis-tagged, it's an easy situation for us to handle.

`though` vs `through` though - that should be fixed in the data.

**Comment by daniel-j-h** [comment]
How many of those are in the data? We had the discussion yesterday about supporting wrong data or not (cc @TheMarex). There should be an incentive for mappers to fix the data and not the software.

**Comment by TheMarex** [comment]
Yeah I know this is an easy case, but this is a slippery slope to also fixing common misspellings etc. Bad data should be bad data in my opinion.

**Comment by daniel-j-h** [comment]
Closing as data issue.

**Comment by daniel-j-h** [comment]
I think Osmose has some lane-related checks. Not sure if this is already in there or a good candidate for inclusion: lane tags with individual indications not conforming to the tags on the Wiki.

cc @frodrigo

**Comment by frodrigo** [comment]
Yes, Osmose-QA already check for this.
