### ISSUE TITLE
Turning onto a divided road - naming of the joining section

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3412]
When turning onto a divided road, the instruction you get depends on how the mapper in OSM chose to name the connecting road section.  In some cases, we issue a nice "turn left", in other cases, we issue a nice "at the end of the road turn left".

The following test cases describe the scenarios.  I've set these tests up to expect `end of road left`, but this fails in the case where the mapper has named the joining section the same as the divided road.

@MoKob In both cases we're doing a good job issuing a "turn left onto main st", the only question is the "end of road" modifier.  I'm describing this ticket so we have clarity, I'm happy to simply close it if this behaviour is deemed acceptable.

I took a look through the existing suite and didn't spot a similar scenario, sorry in advance if I missed it.

```
@routing  @guidance
Feature: Divided road entry

    Background:
        Given the profile "car"
        Given a grid size of 5 meters

    Scenario: Join on a divided road named after the main road
        Given the node map
            """
            a-------b-----c
                    |
            d-------e-----f
                    |
                    |
                    g
            """

        And the ways
            | nodes  | name    | highway     | oneway |
            | abc    | main st | residential | -1     |
            | def    | main st | residential | yes    |
            | be     | main st | residential |        |
            | eg     | side st | residential |        |

       When I route I should get
            | waypoints | route                  | turns                   |
            | g,a       | side st,main st,main st| depart,end of road left,arrive |


    # Similar to previous one, but the joining way is tagged with the side-street name
    Scenario: Undisturbed name Change
        Given the node map
            """
            a-------b-----c
                    |
            d-------e-----f
                    |
                    |
                    g
            """

        And the ways
            | nodes  | name    | highway     | oneway |
            | abc    | main st | residential | -1     |
            | def    | main st | residential | yes    |
            | beg    | side st | residential |        |

       When I route I should get
            | waypoints | route    | turns                           |
            | g,a       | side st,main st,main st| depart,end of road left,arrive |


    # Center join named after crossroad
    Scenario: Undisturbed name Change
        Given the node map
            """
                    h
                    |
            a-------b-----c
                    |
            d-------e-----f
                    |
                    |
                    g
            """

        And the ways
            | nodes  | name    | highway     | oneway |
            | abc    | main st | residential | -1     |
            | def    | main st | residential | yes    |
            | hbeg    | side st | residential |        |

       When I route I should get
            | waypoints | route    | turns                           |
            | g,a       | side st,main st,main st| depart,turn left,arrive |

    # Join named after divided road
    Scenario: Undisturbed name Change
        Given the node map
            """
                    h
                    |
            a-------b-----c
                    |
            d-------e-----f
                    |
                    |
                    g
            """

        And the ways
            | nodes  | name    | highway     | oneway |
            | abc    | main st | residential | -1     |
            | def    | main st | residential | yes    |
            | be     | main st | residential |        |
            | hb     | side st | residential |        |
            | eg     | side st | residential |        |

       When I route I should get
            | waypoints | route    | turns                           |
            | g,a       | side st,main st,main st| depart,turn left,arrive |
```

**Comment by MoKob** [comment]
This is related to https://github.com/Project-OSRM/osrm-backend/issues/3365

**Comment by MoKob** [comment]
@danpat before the refactor, all of these would have emitted end of the road. Due to the road to the left now being recognised as obvious (as only allowed turn), no matter how short the in-segment is, we don't recognise this as a normal turn anymore in certain places.
The ones where you see `end of the road`, we don't recognise an obvious turn.
In my opinion, this should all emit `end of the road`, but it #3365 has to be fixed to do so.

**Comment by MoKob** [comment]
@danpat can you clarify here? All of these tests (when run) show the expected outcome right now.
Do these tests model unwanted behaviour? If so, could you specify what behaviour you would be looking for?
To me, all these tests would look like how they are supposed to behave.

**Comment by danpat** [comment]
@MoKob if the tests are all passing now, then the behaviour has changed since I opened this ticket.  The problem was that depending on which name the the `b-e` segment was given, different instruction types were being emitted when they shouldn't have been.

If the tests are all passing, they should just be added to our test suite (unless they duplicate something else that's already there).
