### ISSUE TITLE
Refactor bicycle profile

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#3413]
Should be done along the line of what was done with the car profile. The bicycle profile is more complex because it must handle pushing of bikes.

The approach will be to do things as similar as possible to the car profile, so common steps can later be factored out into helpers.

I've started on this issue.

**Comment by daniel-j-h** [comment]
This landed with https://github.com/Project-OSRM/osrm-backend/pull/3654 :sparkles:
