### ISSUE TITLE
Unnecessary Intersection Generation / Coordinate Extraction

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3416]
Intersection generation and coordinate extraction is next to graph traversal the expensive part in pre-processing.

We should check all intersection handlers and make sure we only ever generate intersections and extract coordinates where we need to. This also means re-ordering checks by cheapest first.

Our interfaces and especially the graph walker makes unnecessary intersection generation quite easy and hidden out of plain sight.

One example here: the Sliproad handler aborts if the Sliproad's target intersection is not of size three. At the moment we use the graph walker to get to the next intersection and then check the intersection's size. Instead we could traverse the graph, check out degrees, abort early and only then generate the intersection if needs be.

**Comment by TheMarex** [comment]
This is not really a refactor but a performance problem. I think this will be less of a problem once we start to contract complex intersections, since there will not be a need for using constructs like the graph walker. Closing as won't fix/not actionable right now.
