### ISSUE TITLE
limit for locate ,nearest or viaroute

### ISSUE THREAD

**Issue by pranavk** [Project-OSRM/osrm-backend#342]
how much is the limit for locate , nearest or viaroute plugins, I mean to what decimal place my latitude and longitude value will be rounded off to find the nearest road. 

And Is it possible to alter this value in the program, for eg :: i want to alter it for a place where i feel that road network quality is not that good in OSM and OSRM is not able to find routes for any two locations using its existing nearest/locate settings.

**Comment by hukhuk** [comment]
I just got osrm installed on my own ubuntu box (14.04), built from the sources in here. Running osrm-routed -v outputs [info] v4.7.0. Still, it seems as if the "3 mile limit" exists on my box. I randomly checked one coordinate that was along a road that was not present on my data set, and running nearest on that location got me a status 207. I then tried moving the coordinate a little closer to a major road, and it found the road just fine.
I then did the same, trying the middle of a lake. Again, 207. The weird thing is, if I run the same coordinates on router.project-osrm.org, they all work just fine. Could there be a problem in my configuration or am I just doing something wrong?

**Comment by TheMarex** [comment]
@hukhuk there was a change in how we find street segments recently that improved the behavior a lot. should be included in the next OSRM release.

**Comment by hukhuk** [comment]
@TheMarex thanks, good to know. Any idea of the timeline of said next release?

**Comment by maxdeepfield** [comment]
It would be nice to have this setting configurable.
