### ISSUE TITLE
Point should not be "coordinates": [[lon, lat]], but [lon, lat] when setting "geometry=geojson"

### ISSUE THREAD

**Issue by kkdd** [Project-OSRM/osrm-backend#3425]
Hello,
At present, a query with`geometry=geojson` results in:

```
$ curl "http://localhost:5000/route/v1/driving/133.540336,33.558187;133.540937,33.55841?steps=true&geometries=geojson" | jq -c '.routes[0].legs[].steps[].geometry | select(.type == "Point")'

{"type":"Point","coordinates":[[133.540906,33.558277]]}
```

But a correct geojson should be the following:
```
{"type": "Point", "coordinates": [133.540906, 33.558277]}
(or {"type": "MultiPoint", "coordinates": [[133.540906, 33.558277]]}).
```

**Comment by daniel-j-h** [comment]
You're right, quoting [the spec](http://geojson.org/geojson-spec.html#point):
> 2.1.2. Point
> For type "Point", the "coordinates" member must be a single position.
>
> 2.1.3. MultiPoint
> For type "MultiPoint", the "coordinates" member must be an array of positions.

and for [Position](http://geojson.org/geojson-spec.html#positions):
> 2.1.1. Positions
> 
> A position is the fundamental geometry construct. The "coordinates" member of a geometry object is composed of one position (in the case of a Point geometry), an array of positions (LineString or MultiPoint geometries), an array of arrays of positions (Polygons, MultiLineStrings), or a multidimensional array of positions (MultiPolygon).
> 
> A position is represented by an array of numbers. There must be at least two elements, and may be more. The order of elements must follow x, y, z order (easting, northing, altitude for coordinates in a projected coordinate reference system, or longitude, latitude, altitude for coordinates in a geographic coordinate reference system). Any number of additional elements are allowed -- interpretation and meaning of additional elements is beyond the scope of this specification.

**Comment by TheMarex** [comment]
Urg yeah this is an API bug, fixing this would be a breaking API change though.

What would work is not not emit `Point` at all anymore but only `LineString`, but maybe with the same coordinate twice. Client code already needs to handle both cases, we would just not emit one of them anymore. Always emitting `LineString` might also be more consistent with the idea of step geometries.

**Comment by daniel-j-h** [comment]
For the record: https://github.com/Project-OSRM/osrm-backend/pull/3426 fixed this by no longer emitting a `Point` in the single coordinate case. Instead we now always emit a `LineString` with the single coordinate duplicated. Backwards compatible.

Thanks for reporting and sorry for not noticing this edge case earlier.

**Comment by kkdd** [comment]
In a geojson, "LineString" should have two or more coordinates. See a pull request of "Adhere to GeoJSON spec by not return invalid LineStrings #2286" (Project-OSRM/osrm-backend).

**Comment by daniel-j-h** [comment]
Yes now a `LineString` has two coordinates if the geometry would have been a `Point`.

    Before: Point coord
    After:  LineString [coord, coord]

**Comment by TheMarex** [comment]
Yeah the original "fix" was a bad call on my side. LineString makes much more sense, as for these segments the start and endpoint coincide (zero length segments, such as the last segment of a route that marks the `Arrive` instruction.)
