### ISSUE TITLE
version 4.4.0 with latest map data of Russian part building wrong ways

### ISSUE THREAD

**Issue by denbip** [Project-OSRM/osrm-backend#3433]
Running the latest map data of Russian part on OSRM 4.4.0 give me incorrect ways. With data map of April 2016 all is ok. I have tried to run the newest version of OSRM, but it seems that ways are incorrect too

![err](https://cloud.githubusercontent.com/assets/23192718/21052343/9278a55a-be35-11e6-8651-d4cbbbc4ce64.png)

**Comment by daniel-j-h** [comment]
> OSRM 4.4.0

What you're seeing are OSM Node Id overflows / wrap arounds. You really should upgrade to the latest stable release. In a couple of days we will release 5.5.

Closing as not actionable for us. See https://github.com/Project-OSRM/osrm-backend/issues/2803.

**Comment by denbip** [comment]
Thanks! I've changed type of NodeID and now it works just fine!)
