### ISSUE TITLE
Change parsing parallelization to work on osmium::Buffer objects

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3447]
Currently we read one buffer object [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/extractor.cpp#L172) and then split it apart [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/scripting_environment_lua.cpp#L307-L312).

This should be changed to operate on a Buffer-per-thread to save the cost of splitting the buffer apart and possibly unlock using the libosmium handler interface.

/cc @daniel-j-h @joto

**Comment by daniel-j-h** [comment]
Here are some docs for `begin(reader), end(reader)` returning `InputIterators`:

http://docs.osmcode.org/libosmium/latest/namespacestd.html#a112cb4bdf62ee6fd00d04362d06d0eef

Over which we can walk in parrallel with `parallel_for_each(begin(reader), end(reader), body);`

https://www.threadingbuildingblocks.org/docs/help/hh_goto.htm?index.htm#reference/algorithms/parallel_for_each_func.html

One issue I'm seeing is the `ExtractorCallbacks` not handling synchronization at all.

https://github.com/Project-OSRM/osrm-backend/blob/f88f51fd98331d78da08378204c4182db5e38863/src/extractor/extractor.cpp#L193-L210

**Comment by TheMarex** [comment]
> One issue I'm seeing is the ExtractorCallbacks not handling synchronization at all

Yes. Main blocker here is that all the backing containers are non-threadsafe (stxxl). We could add synchronization for each function or in-memory buffering + synchronized flush.

But this only blocks us from using the nicer interface. We can still always take out only N blocks, process them and then have the same serial routines run that we have now.
