### ISSUE TITLE
Math behind Table service durations

### ISSUE THREAD

**Issue by carrbrpoa** [Project-OSRM/osrm-backend#3449]
I was wondering what is the Math behind the response of distance/duration Table service, I didn't manage to find in documentation. I think it considers a continuous speed, but which one?

Thanks

**Comment by danpat** [comment]
@carrbrpoa Currently, all requests to OSRM consider travel time.  The response you get from the `table` plugin is the travel time between each pair of coordinates.

Internally, OSRM represents the road network as a graph, and all edges have a `weight`.  The Lua profiles are responsible for setting the weight on the edges, and the ones we ship with OSRM all set the weight based on speed - i.e. it's travel time.

You can create a new profile where you set all "speed" values to 3.6km/h - this will effectively mean that OSRM will now route based on distance, and any duration value returned from the various APIs will be effectively in meters.

Closing as not actionable on our end.
