### ISSUE TITLE
Windows build - distance is always 0

### ISSUE THREAD

**Issue by a6datta** [Project-OSRM/osrm-backend#3450]
Hi, I understand no one is maintaining windows build. I will try to build it when I have free time. For now I have downloaded release binaries from http://build.project-osrm.org/. But when I make http calls (route service) with two or more waypoints it returns a different waypoint which is fixed for all points and distance is always 0.

http://localhost:5000/route/v1/driving/51.5034070,-0.1275920;51.4597800,-0.0203130;51.5048440,0.0495180?continue_straight=false
{
  "waypoints": [
    {
      "location": [
        -3.039823,
        43.356421
      ],
      "name": "Portsmouth - Bilbao",
      "hint": "XAIAgNADAIB0BAAA7CUAAAAAAABIvQwA2EsAAHIBAAARAACAsZ3R_wWRlQIv4REDmA3-_1YAAgJ38mxD"
    },
    {
      "location": [
        -3.039823,
        43.356421
      ],
      "name": "Portsmouth - Bilbao",
      "hint": "XAIAgNADAIB0BAAA7CUAAAAAAABIvQwA2EsAAHIBAAARAACAsZ3R_wWRlQLENhEDp7D__1YAAgJ38mxD"
    },
    {
      "location": [
        -3.039823,
        43.356421
      ],
      "name": "Portsmouth - Bilbao",
      "hint": "XAIAgNADAIB0BAAA7CUAAAAAAABIvQwA2EsAAHIBAAARAACAsZ3R_wWRlQLM5hEDbsEAAFYAAgJ38mxD"
    }
  ],
  "routes": [
    {
      "distance": 0,
      "duration": 0,
      "legs": [
        {
          "distance": 0,
          "duration": 0,
          "summary": "",
          "steps": []
        },
        {
          "distance": 0,
          "duration": 0,
          "summary": "",
          "steps": []
        }
      ],
      "geometry": "s`sgGzupQ????"
    }
  ],
  "code": "Ok"
}

**Comment by danpat** [comment]
@a6datta You've got your coordinate order swapped - OSRM takes `longitude,latitude`.

The points you've supplied are way out in the middle of the ocean, and they're being snapped to the closest road in your road network, which is all the same spot.

**Comment by a6datta** [comment]
This time it says "Impossible route between points". The same points works on demo server as well as on old version. I have been using the old version for more than 6 months.

**Comment by a6datta** [comment]
It now returns "Impossible route between points". The same points work on demo server as well as on old version. I have been using old version for more than 6 months. 
http://router.project-osrm.org/route/v1/driving/0.0495180,51.5048440;-0.4542950,51.4700220

**Comment by danpat** [comment]
@a6datta How did you prepare your data?  Please describe:

  1. What OSM file you're using.
  2. What commands you used to prepare the data.

**Comment by a6datta** [comment]
@daniel-j-h 

I downloaded great-britain-latest.osm.pbf from here
http://download.geofabrik.de/europe/great-britain.html
and england-latest.osm.pbf from http://download.geofabrik.de/europe/great-britain/england.html

How I processed data
Old Version
I don't recall exactly as it was a while ago. But I remember profiles directory was missing on release build. I got it from somewhere. Then I ran osrm-extract england-latest.osm.pbf and osrm-prepare england-latest.osrm. After that I was able to user server API and it was working fine until now. 
Recently I needed to add whole of UK. So I downloaded great-britain-latest.osm.pbf and processed the data as I did previously. However now the service returns incorrect route. When I draw the points on a map, it starts wrong direction then takes very big jump on straight line. 

Then I downloaded new version
New Version
I copied the profiles diectory from old version. Then ran osrm-extract great-britain-latest.osm.pbf and osrm-contract great-britain-latest.osrm. But new service returns "Impossible route between points".

**Comment by daniel-j-h** [comment]
> Then I downloaded new version
> New Version
> I copied the profiles diectory from old version.

This won't work. You can't mix profiles from one osrm-backend version with a different one.

Please do the following: get yourself the latest v5.5.0 stable release. Then use the profiles in the v5.5.0 release e.g. at `profiles/car.lua`. Then report back.

**Comment by a6datta** [comment]
It's working now. Thanks

**Comment by daniel-j-h** [comment]
Perfect! Closing as resolved.
