### ISSUE TITLE
Alternative route sometimes faster than fastest route?

### ISSUE THREAD

**Issue by tyrasd** [Project-OSRM/osrm-backend#346]
Sometimes the alternative "B" route is faster than the fastest "A" route. I noticed this (quite rare?) behavior especially on very long routes. You can also get "faster than fastest" routes by dragging a via-point accordingly.

Example: http://osrm.at/XB (route A is 40 minutes slower [and 35 km longer] than route B)

**Comment by jcrochavera** [comment]
Hi, I got this:

A:
Distance:	2.84 km
Duration:	3 min

B:
Distance:	2.54 km
Duration:	3 min

http://map.project-osrm.org/?hl=es&loc=-16.492384,-68.149681&loc=-16.498964,-68.135155&z=16&center=-16.495391,-68.145483&alt=0&df=0&re=0&ly=763558683

**Comment by woodbri** [comment]
The routes are sort by duration so the real values (rather than the rounded display values) might be:
A: 3.01 min
B: 3.02 min

Distances does not come into play when ordering the routes>
