### ISSUE TITLE
vector::_M_range_check

### ISSUE THREAD

**Issue by davidmir** [Project-OSRM/osrm-backend#3463]
Hi,

What could cause this error? I am using the v4 API and am getting this error for the following request: /table?loc=40.3968537,-8.2325058&loc=40.3968537,-8.2325058.
Can I get any more information about the error (debug mode)?

Thanks

**Comment by TheMarex** [comment]
This means you have an out-of-bounds access somewhere. We don't support the v4 API at all anymore.

Please post back if you can re-produce this on v5.5.0.

**Comment by daniel-j-h** [comment]
Here's the v5 request:

```
$ http 'http://router.project-osrm.org/table/v1/driving/-8.2325058,40.3968537;-8.2325058,40.3968537' | jq '.code'
"Ok"
```

Might be related to both locations being the same and us not handling this in v4 properly.

As said, please update to the latest [v5 release](https://github.com/Project-OSRM/osrm-backend/releases), we don't support v4 any longer.

Closing as not actionable for us. If you can reproduce with v5 feel free to re-open.
