### ISSUE TITLE
Unable to generate Xcode project — Intel TBB NOT found

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-backend#3465]
Per https://github.com/Project-OSRM/osrm-backend/issues/2409#issuecomment-219609327, I ran this on OS X 10.11.6 with Xcode 8.2 and CMake 3.7.1 installed against a checkout of 37051e15832b7a13ddb9bc9dd1b25d1efa13427a:

```bash
mkdir debug
cd debug
cmake -G Xcode -DCMAKE_BUILD_TYPE=Debug ..
```

and it failed to even generate the project (so I couldn’t even verify #2409):

```
-- Building on a 64 bit system
CMake Warning at CMakeLists.txt:164 (message):
  GNU gold linker isn't available.


-- Configuring OSRM in debug mode
-- Configuring debug mode flags
-- Using unknown linker, not setting linker optimizations
-- Set Architecture to x64 on OS X
-- linking against libc++
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   date_time
--   chrono
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
--   atomic
ERROR: Intel TBB NOT found!
-- Looked for Threading Building Blocks in /Library/Frameworks/Intel_TBB.framework/Versions
CMake Error at cmake/FindTBB.cmake:272 (message):
  Could NOT find TBB library.
Call Stack (most recent call first):
  CMakeLists.txt:463 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/mxn/hub/osrm-backend/debug/CMakeFiles/CMakeOutput.log".
```

Nothing unusual appears in the CMakeOutput.log file, except perhaps for this bit at the end:

```c
File /Users/mxn/hub/osrm-backend/debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

/cc @daniel-j-h

**Comment by TheMarex** [comment]
How did you install Intel TBB? From what I could gather you have two options:

> brew install tbb

Or build cmake with `-DENABLE_MASON=On` which should use TBB from mason.

**Comment by 1ec5** [comment]
Also had to `brew install libstxxl`, but I’m able to generate the project now.

**Comment by daniel-j-h** [comment]
Yeah you have to grab more or less the same dependencies as for other environments, e.g. [Ubuntu](https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu). There is also a osrm brew package, just in case you haven't seen it already.

Great to hear CMake is able to generate a project now. Are you using the hack from https://github.com/Project-OSRM/osrm-backend/issues/2409#issuecomment-267724066?

**Comment by 1ec5** [comment]
No, I was not.
