### ISSUE TITLE
Add --force flag to osrm-datastore

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3466]
Currently we bail out if we detect any left-over locks when running `osrm-datastore`. That becomes inconvenient when `osrm-datastore` or `libosrm` fails to release a lock for whatever reason.

We should add a `--force` flag that reset any external state so we safely recover:

- Remove all shared memory regions owned by OSRM
- Remove all shared memory locks

This combines the functionality from `osrm-springclean` and `osrm-unlock-all` and would make them obsolete.

/cc @miccolis

**Comment by danpat** [comment]
@TheMarex hmm, if we want to remove `osrm-springclean`, we might want something like:

```
osrm-datastore --cleanup --force
  - basically osrm-springclean, overrides locks

osrm-datastore --force datafile.osrm
  - loads new data, overrides locks, removes old shared memory regions

osrm-datastore datafile.osrm
  - respects locks
```

I can't think of many situations where you would practically want to remove the shared memory regions without replacing them with different data, but it could be useful.

**Comment by TheMarex** [comment]
Obsolete with new locking code.
