### ISSUE TITLE
Re-Use discovered intersections in Merge-Segregated-Roads Handlers/Improve Detectors

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3473]
As a follow up to https://github.com/Project-OSRM/osrm-backend/pull/3211, we should improve the required algorithmic overhead.

The different detectors (e.g. HaveSameDirection/IsNarrowTriangle) perform their own graph walking. We should see if we can re-use the discovered information in other handlers.

The order in which detectors operate could also be a point for optimisation, since the algorithmic overheads are quite different and the probability to trigger as well. We should probably optimise to use the most likely detectors first.

Finally, all handlers are pure heuristics. Even though they are tuned quite well, there are still many situations where small roads influence the detection quality. Further improvement can always be made.

**Comment by MoKob** [comment]
Adding from: https://github.com/Project-OSRM/osrm-backend/pull/3211#discussion_r94311210, we should also see if we can implement specialised graph walkers that don't require intermediate intersections.

**Comment by TheMarex** [comment]
We won't do this, since we will replace most of the segregated roads logic with graph contraction.
