### ISSUE TITLE
Last leg is missing from matching results

### ISSUE THREAD

**Issue by gfhuertac** [Project-OSRM/osrm-backend#3488]
Hi:
I am trying to add timestamp to the matched geometry, and in order to do that I traverse the tracepoints array, obtain the waypoint and matchings indexes and search them in the matchings array. However, the legs inside the matching array do not have the expected length.

This is the request I am using

`
https://router.project-osrm.org/match/v1/driving/-71.556786,-33.040679;-71.557474,-33.0510863;-71.5585618,-33.0592663;-71.5562495,-33.0658391;-71.5501775,-33.0748386;-71.5464063,-33.0815671;-71.5430127,-33.0870443;-71.5454406,-33.0960088;-71.5482477,-33.1005571;-71.5527644,-33.1076973;-71.5602613,-33.1140839;-71.560861,-33.1196814;-71.5618714,-33.1283295;-71.5626422,-33.1356589;-71.5621538,-33.14219;-71.5593209,-33.1479594;-71.5507981,-33.1567887;-71.5422867,-33.1611356;-71.5363439,-33.1641529;-71.5285008,-33.1682002;-71.5227189,-33.1711586;-71.5135881,-33.175801;-71.5042332,-33.1825763;-71.4982451,-33.1900818;-71.4923635,-33.1973578;-71.4839167,-33.2057548;-71.4768187,-33.2123747;-71.4732962,-33.2166788;-71.4696295,-33.2235919;-71.4621174,-33.234148;-71.4509704,-33.2426946;-71.4441887,-33.2511802;-71.4392734,-33.2575235;-71.4345634,-33.2646205;-71.4318555,-33.2711075?steps=true&geometries=geojson&timestamps=1467403178;1467403868;1467403943;1467403988;1467404078;1467404123;1467404153;1467404198;1467404228;1467404273;1467404303;1467404333;1467404363;1467404393;1467404408;1467404438;1467404483;1467404513;1467404528;1467404558;1467404573;1467404603;1467404648;1467404678;1467404708;1467404753;1467404783;1467404798;1467404828;1467404873;1467404918;1467404948;1467404978;1467405008;1467405023
`

From that I am receiving an object with one matching and the matching has 33 legs.
However, the last tracepoint contains the following:
`
{
	"waypoint_index": 33,
	"location": [-71.431868, -33.271111],
	"name": "Autopista del Pacífico",
	"hint": "_evai____3-wL4wAIwAAACQAAACWAAAAuwQAAHtMqgQ2-QAARAm--7lSBP5RCb77vVIE_gQAAQHEwdXo",
	"matchings_index": 0
}
`

As you can see the waypoint index is 33, but the last index is 32, and therefore and index out of bounds error is triggered.
What I am doing now is to just use the location of the tracepoint, but it does not seem right.

**Comment by TheMarex** [comment]
Legs are the segments connecting waypoints. If you have `n` waypoints there will be exactly `n-1` legs. The first leg `0` is the connection between `waypoint[0]` and `waypoint[1]`, the second leg `1` between `waypoint[1]` and `waypoint[2]` and so on.

You need special-case handling because this is not meant to be translated 1:1 into the leg indices.

**Comment by gfhuertac** [comment]
Thanks.
I think that this should be clarified then because when I read previous issues such as 2949 or 2986 it does not mention that the last tracepoint does not have a leg. I was expecting one with a single point (there are tracepoints with a single point as a leg)
