### ISSUE TITLE
Refactor `isThroughStreet`/Intersection options

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3491]
Breaking out from https://github.com/Project-OSRM/osrm-backend/pull/3211

@daniel-j-h raised the following points in [this context](https://github.com/Project-OSRM/osrm-backend/pull/3211#discussion-diff-93431942R134).

Also is this actually getting used at the moment? I thought about the function in the context of the `isThroughStreet` check. We have two of them (\*)

```c++
 bool isThroughStreet(const std::size_t index, const Intersection &intersection) const; // IntersectionHandler
 bool isThroughStreet(const EdgeID from, const IntersectionView &intersection) const; // SliproadHandler
```

(disregard the Intersection vs IntersectionView difference for now)

Now in the SliproadHandler we only have the eid on the callsite, so I could use `findEdge` to get the road and then get the index with distance. But this would be expensive iterating all intersection roads i guess.

What's your take on our abstractions here, on what level of abstraction should (in this case) a through street be checked for?

(\*)

- https://github.com/Project-OSRM/osrm-backend/blob/0a2f934c87b68fa09a5db7b7032f192a68cea5e9/include/extractor/guidance/intersection_handler.hpp#L92-L93
- https://github.com/Project-OSRM/osrm-backend/blob/0a2f934c87b68fa09a5db7b7032f192a68cea5e9/include/extractor/guidance/sliproad_handler.hpp#L54-L55

The general scope of what is attached to an intersection should be revisited.

**Comment by daniel-j-h** [comment]
Related: https://github.com/Project-OSRM/osrm-backend/issues/3102

**Comment by TheMarex** [comment]
This is an easy refactor that removes a duplicate implementation and potentially opens up to unit test this:

- [ ] Remove `SliproadHandler::isThroughStreet`
- [ ] Find index of `sliproad_edge` over `std::find` on intersection
- [ ] Move `Intersection::isThroughStreet` to own file/free function and template the type of `Intersection`.

**Comment by ghoshkaj** [comment]
@TheMarex is this good to close? Or is there more to do here?
