### ISSUE TITLE
Separate Interface/Implementation for intersections

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3493]
Branching out from https://github.com/Project-OSRM/osrm-backend/pull/3211

@daniel-j-h pointed out

I think we should start separating interface and implementation [here](https://github.com/Project-OSRM/osrm-backend/pull/3211#discussion_r93430811): in the intersection header, provide the interface with comments. Then maybe in a "intersections mixins" header provide shared ops and impl.

We should also think about how to document the mixins alread in the intersection / view, otherwise they are hard to discover when they are defined far away from the type they're attached to.

**Comment by TheMarex** [comment]
We are going to move way from the intersection handler abstraction, this issue is outdated.
