### ISSUE TITLE
OSRM-EXTRACTOR RUNNING FROM 3 HOURS

### ISSUE THREAD

**Issue by amogh-balachandra** [Project-OSRM/osrm-backend#3494]
Hello all , am trying to extract maldives.pbf  downloaded from download.geofabrik.de , its just 1MB file though Extractor is running more than 3 hours . I used this as a test case as other pbf are more in size. 

Please find the attached screenshot , 
![osrm_ext_err](https://cloud.githubusercontent.com/assets/21061262/21454751/fe04fdc6-c940-11e6-87d3-fa1327444619.png)

Am running on osrm-backend-4.8.1 and Amazon EC2-m3.xlarge instance also specified Swapfile of 4 GB . 

Is this an error or should i wait till the process completes.

Also how do i remove STXXL error, i have installed STXXL as per https://github.com/Project-OSRM/osrm-backend/wiki/Bulding-OSRM-backend-on-CentOS-6.

**Comment by TheMarex** [comment]
Please upgrade to 5.5 and report back if the problem still exists. 4.8.1 is unsupported due to the fact that OSM breached the 32bit boundary for ids.

**Comment by daniel-j-h** [comment]
Just checked with master and

http://download.geofabrik.de/asia/maldives-latest.osm.pbf

Works fine.

**Comment by amogh-balachandra** [comment]
Hello i tried installing 5.5 but getting these Errors , pls help

opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:38:39: error: parameter declared ‘auto’
     return [base_bearing](const auto &lhs, const auto &rhs) {
                                       ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:38:56: error: parameter declared ‘auto’
     return [base_bearing](const auto &lhs, const auto &rhs) {
                                                        ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:39:57: error: ‘lhs’ was not declared in this scope
         return util::angleBetweenBearings(base_bearing, lhs.bearing) <
                                                         ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:40:57: error: ‘rhs’ was not declared in this scope
                util::angleBetweenBearings(base_bearing, rhs.bearing);
                                                         ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In function ‘auto osrm::extractor::guidance::makeCompareAngularDeviation(double)’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:46:32: error: parameter declared ‘auto’
     return [angle](const auto &lhs, const auto &rhs) {
                                ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:46:49: error: parameter declared ‘auto’
     return [angle](const auto &lhs, const auto &rhs) {
                                                 ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:47:39: error: ‘lhs’ was not declared in this scope
         return util::angularDeviation(lhs.angle, angle) < util::angularDeviation(rhs.angle, angle);
                                       ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:47:82: error: ‘rhs’ was not declared in this scope
         return util::angularDeviation(lhs.angle, angle) < util::angularDeviation(rhs.angle, angle);
                                                                                  ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In member function ‘auto osrm::extractor::guidance::EnableIntersectionOps<Self>::valid() const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:137:36: error: parameter declared ‘auto’
         auto comp = [](const auto &lhs, const auto &rhs) { return lhs.CompareByAngle(rhs); };
                                    ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:137:53: error: parameter declared ‘auto’
         auto comp = [](const auto &lhs, const auto &rhs) { return lhs.CompareByAngle(rhs); };
                                                     ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:137:67: error: ‘lhs’ was not declared in this scope
         auto comp = [](const auto &lhs, const auto &rhs) { return lhs.CompareByAngle(rhs); };
                                                                   ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:137:86: error: ‘rhs’ was not declared in this scope
         auto comp = [](const auto &lhs, const auto &rhs) { return lhs.CompareByAngle(rhs); };
                                                                                      ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In member function ‘auto osrm::extractor::guidance::EnableIntersectionOps<Self>::isDeadEnd() const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:193:36: error: parameter declared ‘auto’
         auto pred = [](const auto &road) { return road.entry_allowed; };
                                    ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:193:51: error: ‘road’ was not declared in this scope
         auto pred = [](const auto &road) { return road.entry_allowed; };
                                                   ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In member function ‘auto osrm::extractor::guidance::EnableIntersectionOps<Self>::countEnterable() const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:200:36: error: parameter declared ‘auto’
         auto pred = [](const auto &road) { return road.entry_allowed; };
                                    ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:200:51: error: ‘road’ was not declared in this scope
         auto pred = [](const auto &road) { return road.entry_allowed; };
                                                   ^
In file included from /opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:6:0,
                 from /opt/osrm-backend-5.5.2/include/extractor/guidance/motorway_handler.hpp:6,
                 from /opt/osrm-backend-5.5.2/include/extractor/guidance/turn_analysis.hpp:8,
                 from /opt/osrm-backend-5.5.2/include/extractor/edge_based_graph_factory.hpp:14,
                 from /opt/osrm-backend-5.5.2/include/extractor/extractor.hpp:3 ,
                 from /opt/osrm-backend-5.5.2/include/storage/serialization.hpp:5,
                 from /opt/osrm-backend-5.5.2/src/storage/storage.cpp:10:
/opt/osrm-backend-5.5.2/include/extractor/guidance/node_based_graph_walker.hpp: In constructor ‘osrm::extractor::guidance::DistanceToNextIntersectionAccumulator::DistanceToNextIntersectionAccumulator(const osrm::extractor::guidance::CoordinateExtractor&, const NodeBasedDynamicGraph&, double)’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/node_based_graph_walker.hpp:218:68: warning: a temporary bound to ‘osrm::extractor::guidance::DistanceToNextIntersectionAccumulator::extractor’ only persists until the constructor exits [-Wextra]
         : extractor{extractor_}, graph{graph_}, threshold{threshold}
                                                                    ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/node_based_graph_walker.hpp:218:68: error: use of deleted function ‘osrm::util::DynamicGraph<osrm::util::NodeBasedEdgeData>::DynamicGraph(const osrm::util::DynamicGraph<osrm::util::NodeBasedEdgeData>&)’
In file included from /opt/osrm-backend-5.5.2/include/util/node_based_graph.hpp:6:0,
                 from /opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:13,
                 from /opt/osrm-backend-5.5.2/include/extractor/guidance/turn_analysis.hpp:5,
                 from /opt/osrm-backend-5.5.2/include/extractor/edge_based_graph_factory.hpp:14,
                 from /opt/osrm-backend-5.5.2/include/extractor/extractor.hpp:3 ,
                 from /opt/osrm-backend-5.5.2/include/storage/serialization.hpp:5,
                 from /opt/osrm-backend-5.5.2/src/storage/storage.cpp:10:
/opt/osrm-backend-5.5.2/include/util/dynamic_graph.hpp:23:37: note: ‘osrm::util::DynamicGraph<osrm::util::NodeBasedEdgeData>::DynamicGraph(const osrm::util::DynamicGraph<osrm::util::NodeBasedEdgeData>&)’ is implicitly deleted because the default definition would be ill-formed:
 template <typename EdgeDataT> class DynamicGraph
                                     ^
/opt/osrm-backend-5.5.2/include/util/dynamic_graph.hpp:23:37: error: use of deleted function ‘std::__atomic_base<_IntTp>::__atomic_base(const std::__atomic_base<_IntTp>&) [with _ITp = unsigned int]’
In file included from /usr/include/c++/4.8.3/atomic:41:0,
                 from /opt/osrm-backend-5.5.2/include/util/log.hpp:4,
                 from /opt/osrm-backend-5.5.2/include/storage/shared_datatype.hpp:6,
                 from /opt/osrm-backend-5.5.2/include/storage/storage.hpp:31,
                 from /opt/osrm-backend-5.5.2/src/storage/storage.cpp:1:
/usr/include/c++/4.8.3/bits/atomic_base.h:359:7: error: declared here
       __atomic_base(const __atomic_base&) = delete;
       ^
In file included from /opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:6:0,
                 from /opt/osrm-backend-5.5.2/include/extractor/guidance/motorway_handler.hpp:6,
                 from /opt/osrm-backend-5.5.2/include/extractor/guidance/turn_analysis.hpp:8,
                 from /opt/osrm-backend-5.5.2/include/extractor/edge_based_graph_factory.hpp:14,
                 from /opt/osrm-backend-5.5.2/include/extractor/extractor.hpp:3 ,
                 from /opt/osrm-backend-5.5.2/include/storage/serialization.hpp:5,
                 from /opt/osrm-backend-5.5.2/src/storage/storage.cpp:10:
/opt/osrm-backend-5.5.2/include/extractor/guidance/node_based_graph_walker.hpp:218:68: warning: a temporary bound to ‘osrm::extractor::guidance::DistanceToNextIntersectionAccumulator::graph’ only persists until the constructor exits [-Wextra]
         : extractor{extractor_}, graph{graph_}, threshold{threshold}
                                                                    ^
In file included from /opt/osrm-backend-5.5.2/include/extractor/guidance/motorway_handler.hpp:6:0,
                 from /opt/osrm-backend-5.5.2/include/extractor/guidance/turn_analysis.hpp:8,
                 from /opt/osrm-backend-5.5.2/include/extractor/edge_based_graph_factory.hpp:14,
                 from /opt/osrm-backend-5.5.2/include/extractor/extractor.hpp:3 ,
                 from /opt/osrm-backend-5.5.2/include/storage/serialization.hpp:5,
                 from /opt/osrm-backend-5.5.2/src/storage/storage.cpp:10:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In member function ‘std::size_t osrm::extractor::guidance::IntersectionHandler::findObviousTurn(EdgeID, const IntersectionType&) const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:152:60: error: parameter declared ‘auto’
     auto sameOrHigherPriority = [&in_way_data](const auto &way_data) {
                                                            ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:153:16: error: ‘way_data’ was not declared in this scope
         return way_data.road_classification.GetPriority() <=
                ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In member function ‘std::size_t osrm::extractor::guidance::IntersectionHandler::findObviousTurn(EdgeID, const IntersectionType&) const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:156:41: error: parameter declared ‘auto’
     auto IsLowPriority = [](const auto &way_data) {
                                         ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:157:16: error: ‘way_data’ was not declared in this scope
         return way_data.road_classification.IsLowPriorityRoadClass();
                ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In member function ‘std::size_t osrm::extractor::guidance::IntersectionHandler::findObviousTurn(EdgeID, const IntersectionType&) const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:163:46: error: parameter declared ‘auto’
     const auto RoadCompare = [&](const auto &lhs, const auto &rhs) {
                                              ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:163:63: error: parameter declared ‘auto’
     const auto RoadCompare = [&](const auto &lhs, const auto &rhs) {
                                                               ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:164:65: error: ‘lhs’ was not declared in this scope
         const EdgeData &lhs_data = node_based_graph.GetEdgeData(lhs.eid);
                                                                 ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:165:65: error: ‘rhs’ was not declared in this scope
         const EdgeData &rhs_data = node_based_graph.GetEdgeData(rhs.eid);
                                                                 ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In member function ‘std::size_t osrm::extractor::guidance::IntersectionHandler::findObviousTurn(EdgeID, const IntersectionType&) const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:189:54: error: parameter declared ‘auto’
     const auto RoadCompareSameName = [&](const auto &lhs, const auto &rhs) {
                                                      ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:189:71: error: parameter declared ‘auto’
     const auto RoadCompareSameName = [&](const auto &lhs, const auto &rhs) {
                                                                       ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:190:65: error: ‘lhs’ was not declared in this scope
         const EdgeData &lhs_data = node_based_graph.GetEdgeData(lhs.eid);
                                                                 ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:191:65: error: ‘rhs’ was not declared in this scope
         const EdgeData &rhs_data = node_based_graph.GetEdgeData(rhs.eid);
                                                                 ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In member function ‘std::size_t osrm::extractor::guidance::IntersectionHandler::findObviousTurn(EdgeID, const IntersectionType&) const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:263:76: error: parameter declared ‘auto’
         count_if(++begin(intersection), end(intersection), [&](const auto &way) {
                                                                            ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:264:64: error: ‘way’ was not declared in this scope
             return IsContinueRoad(node_based_graph.GetEdgeData(way.eid));
                                                                ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In member function ‘std::size_t osrm::extractor::guidance::IntersectionHandler::findObviousTurn(EdgeID, const IntersectionType&) const’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:267:76: error: parameter declared ‘auto’
         count_if(++begin(intersection), end(intersection), [&](const auto &way) {
                                                                            ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection_handler.hpp:268:64: error: ‘way’ was not declared in this scope
             return IsContinueRoad(node_based_graph.GetEdgeData(way.eid)) && way.entry_allowed;
                                                                ^
In file included from /opt/osrm-backend-5.5.2/include/util/static_graph.hpp:5:0,
                 from /opt/osrm-backend-5.5.2/include/storage/serialization.hpp:12,
                 from /opt/osrm-backend-5.5.2/src/storage/storage.cpp:10:
/opt/osrm-backend-5.5.2/include/util/percent.hpp: In constructor ‘osrm::util::Percent::Percent(osrm::util::Log&, unsigned int, unsigned int)’:
/opt/osrm-backend-5.5.2/include/util/percent.hpp:20:82: error: invalid initialization of non-const reference of type ‘osrm::util::Log&’ from an rvalue of type  <brace-enclosed initializer list>’
     explicit Percent(Log &log_, unsigned max_value, unsigned step = 5) : log{log_}
                                                                                  ^
In file included from /opt/osrm-backend-5.5.2/src/storage/storage.cpp:13:0:
/opt/osrm-backend-5.5.2/include/storage/shared_memory.hpp: In function ‘std::unique_ptr<osrm::storage::SharedMemory> osrm::storage::makeSharedMemory(const IdentifierT&, uint64_t, bool)’:
/opt/osrm-backend-5.5.2/include/storage/shared_memory.hpp:251:16: error: ‘make_unique’ is not a member of ‘std’
         return std::make_unique<SharedMemory>(lock_file(), id, size, read_write);
                ^
/opt/osrm-backend-5.5.2/include/storage/shared_memory.hpp:251:45: error: expected primary-expression before ‘>’ token
         return std::make_unique<SharedMemory>(lock_file(), id, size, read_write);
                                             ^
In file included from /opt/osrm-backend-5.5.2/include/contractor/graph_contractor.hpp:10:0,
                 from /opt/osrm-backend-5.5.2/src/contractor/contractor.cpp:3:
/opt/osrm-backend-5.5.2/include/util/percent.hpp: In constructor ‘osrm::util::Percent::Percent(osrm::util::Log&, unsigned int, unsigned int)’:
/opt/osrm-backend-5.5.2/include/util/percent.hpp:20:82: error: invalid initialization of non-const reference of type ‘osrm::util::Log&’ from an rvalue of type  <brace-enclosed initializer list>’
     explicit Percent(Log &log_, unsigned max_value, unsigned step = 5) : log{log_}
                                                                                  ^
[ 20%] Building CXX object CMakeFiles/UTIL.dir/src/util/coordinate.cpp.o
/opt/osrm-backend-5.5.2/include/storage/shared_memory.hpp: In instantiation of  std::unique_ptr<osrm::storage::SharedMemory> osrm::storage::makeSharedMemory(const IdentifierT&, uint64_t, bool) [with IdentifierT = osrm::storage::SharedDataType; LockFileT = osrm::storage::OSRMLockFile; uint64_t = long unsigned int]’:
/opt/osrm-backend-5.5.2/src/storage/storage.cpp:73:63:   required from here
/opt/osrm-backend-5.5.2/include/storage/shared_memory.hpp:251:62: warning: right operand of comma operator has no effect [-Wunused-value]
         return std::make_unique<SharedMemory>(lock_file(), id, size, read_write);
                                                              ^
/opt/osrm-backend-5.5.2/include/storage/shared_memory.hpp:251:68: warning: right operand of comma operator has no effect [-Wunused-value]
         return std::make_unique<SharedMemory>(lock_file(), id, size, read_write);
                                                                    ^
[ 21%] Building CXX object CMakeFiles/EXTRACTOR.dir/src/extractor/extraction_containers.cpp.o
[ 23%] Building CXX object CMakeFiles/ENGINE.dir/src/engine/polyline_compressor.cpp.o
In file included from /opt/osrm-backend-5.5.2/include/extractor/guidance/turn_analysis.hpp:5:0,
                 from /opt/osrm-backend-5.5.2/include/extractor/edge_based_graph_factory.hpp:14,
                 from /opt/osrm-backend-5.5.2/src/contractor/contractor.cpp:6:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In function ‘auto osrm::extractor::guidance::makeCompareShapeDataByBearing(double)’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:38:39: error: parameter declared ‘auto’
     return [base_bearing](const auto &lhs, const auto &rhs) {
                                       ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:38:56: error: parameter declared ‘auto’
     return [base_bearing](const auto &lhs, const auto &rhs) {
                                                        ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:39:57: error: ‘lhs’ was not declared in this scope
         return util::angleBetweenBearings(base_bearing, lhs.bearing) <
                                                         ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:40:57: error: ‘rhs’ was not declared in this scope
                util::angleBetweenBearings(base_bearing, rhs.bearing);
                                                         ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In function ‘auto osrm::extractor::guidance::makeCompareAngularDeviation(double)’:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:46:32: error: parameter declared ‘auto’
     return [angle](const auto &lhs, const auto &rhs) {
                                ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:46:49: error: parameter declared ‘auto’
     return [angle](const auto &lhs, const auto &rhs) {
                                                 ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp: In lambda function:
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:47:39: error: ‘lhs’ was not declared in this scope
         return util::angularDeviation(lhs.angle, angle) < util::angularDeviation(rhs.angle, angle);
                                       ^
/opt/osrm-backend-5.5.2/include/extractor/guidance/intersection.hpp:47:82: error: ‘rhs’ was not declared in this scope
         return util::angularDeviation(lhs.angle, angle) < util::angularDeviation(rhs.angle, angle);

**Comment by daniel-j-h** [comment]
Your compiler is too old for C++14. You have to update it.

In theory we guard against this already in the CMakeLists:

https://github.com/Project-OSRM/osrm-backend/blob/ed9d10e96c8a2c6527bb7efabfa66bef25f8e829/CMakeLists.txt#L94-L103

Could you tell us your compiler and its specific version. And add a

    message(STATUS ">>> $CMAKE_CXX_COMPILER_ID - $CMAKE_CXX_COMPILER_VERSION")

to the CMakeLists.txt file and show us the output.

**Comment by amogh-balachandra** [comment]
Thanks @daniel-j-h finally relived from struggle.

**Comment by daniel-j-h** [comment]
Perfect - closing here.
