### ISSUE TITLE
More information about map matching process in answers.

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#3508]
I suggest to add some additional functions in the current matching engine to support incremental matching.
Current matching API is quite good, but it describes input as a separate complete track. There are not information about states during the call. And last track points may have bad confidence, because several routes are possible with same probability. There are not reliable methods to obtain the last point with good confidence and drop several points from the end.

I suggest to add additional parameters to matching API:

Point probability flag. This flag will add point probability information inside a tracepoints (or any other section) for the every input point.

I think this change will allow to use matching widely.

**Comment by TheMarex** [comment]
> Point probability flag.

This is an interesting idea. I'm just not sure which probability we should expose here?

1. Expose the state emission probability:
    - how probable is it to see the GPS location given the matched street segment
    - this value is independent of any context
2. Expose the transition probability:
    - how probable is it that the street segment occurs after the previous street segment in a trace
    - does only account for context but not the actual matching point -> segment
3. Expose the join transition + emission probability
   - accounts for both

The main problem with just exposing these values is that the absolute values doesn't tell you much: They should always be looked on in relation to the other candidates for the same point. So we would need to come up with a mapping that normalizes this to an easily understandable range `0 .. 1` like we do for the `confidence` value of the whole trace.

An idea would be:

1. For every trace point save `transition + emission` log-probability of every candidate
2. When returning the trace compute the relative probability of the selected candidate.  `p_selected = e^logp_selected` and `p_scale = e^(logp_max - logp_min)` resulting in `p_confidence = p_selected / p_scale` which should normalize it to a usable value in the `0 .. 1` range.

**Comment by gardster** [comment]
Thank you for explanation. Probability really seems really hard to expose. But for incremental matching most interesting think is how many alternative routes left inside the Viterbi algorithm. Because even they have good probabilities, if they don't participate in the Viterbi algorithm they will never be reached. This approach I suggest in my PR #3531 
More probabilistic functions requires more information about probabilities and links inside the Viterbi network (by intuition probability of the each inner tracepoint depends on score of the whole path in the Viterbi "network" and on score of all alternatives paths). It will take a lot of time to calculate all this scores.
What do you think if we add just alternative routes count field to the final output?

**Comment by TheMarex** [comment]
@gardster interesting idea! This could also be useful for optimizations that look for "fixed points" in the map matching: Timestamps for which only one viable candidate is used by the next timestamp. At points like this we can forget all previous state and potentially save some memory/runtime later on.

My only concern is on how we would present this to the user: Alternative count is value that depends on the number of final candidates. This will vary based on the number of final states. How would a user interpret this value? Should we normalized by the number of final states?

**Comment by gardster** [comment]
I think, that we can present it, like: Alternative count is a value which describes a number of possible routes that leads to the final point at this trace point. If this value is 1, it means that there is no other routes, that can reach final point. If it is greater than 1, than there are other routes in the algorithm and the OSRM can change geometry output here if you will add several new trace points to the end of the track.

I believe, that alternatives count is a most simple and oblivious parameter for the user. Also, I considered a inverted value `1/alternative_count` as an alternative. We will obtain normalized metric, similar to route probability (in case if all candidates states are equiprobable). But I think, that it is harder to interpret for the user. I think, that most of users will check whether it 1 or not (can they drop previous data) in both cases.
