### ISSUE TITLE
Rounding problem in matching tracepoints location

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#3516]
For the matching request

http://router.project-osrm.org/match/v1/car/-73.99039000003845,40.75171000001269;-73.99025999998277,40.75148000000408?radiuses=26;10&annotations=true&steps=true&geometries=geojson&overview=full

I got in geometry:

>"geometry": {
>        "coordinates": [
>          [
>            -73.990134,
>            40.75165 _**8**_
>          ],
>          [
>            -73.990263,
>            40.751481
>          ]
>        ]

and in tracepoints:

>tracepoints": [
>    {
>      "waypoint_index": 0,
>      "location": [
>        -73.990134,
>        40.75165 _**7**_
>      ],
>      "name": "West 35 Street",
>      "hint": "QAZGgP___38oKRIAfwEAAH8BAAAaAAAAAAAAANxENADf5gAACgCX-ynSbQIK_5b7XtJtAgEAAQHEwdXo",
>      "matchings_index": 0
>    }

Must not these coordinates be similar? 
When I have several legs in matching answer, how do I get tracepoints this leg lies between?

**Comment by TheMarex** [comment]
> Must not these coordinates be similar?

Yes they should be the same. This looks like some weird rounding bug to me that needs investigating.

> When I have several legs in matching answer, how do I get tracepoints this leg lies between?

You will need to build a mapping `leg idx -> tracepoints idx` which you can do over iterating over `tracepoints` and do something like `to_start_index[tracepoint.matchings_idx][tracepoint.waypoint_index] = idx`,
`to_target_index[tracepoint.matchings_idx][tracepoint.waypoint_index-1] = idx` (except for `tracepoint.waypoint_index == 0` which is of course only a start point).

**Comment by TheMarex** [comment]
This was fixed by #3578.
