### ISSUE TITLE
Put fingerprints/headers on all datafiles

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3520]
https://github.com/Project-OSRM/osrm-backend/pull/3467 adds semver-like versioning to our files.

We should add this 8 byte header to all datafiles, and check it when we read things back.

**Comment by duizendnegen** [comment]
I'm interested in maybe picking this up along with creating a serialization layer for the different modules - might work well combined.

Or, were you thinking in terms of adding `VerifyFingerprint` & `GenerateFingerprint` to every `FileReader`/`FileWriter` call? That'd be very easy to get done, can also pick that up.

**Comment by danpat** [comment]
@duizendnegen the second option - no reason to not have a header on every file that gets verified IMO.

**Comment by duizendnegen** [comment]
This one can be closed, #3951 tracks the remainder.
