### ISSUE TITLE
Let Travis builds fail hard if dependency download failed

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3527]
In https://github.com/Project-OSRM/osrm-backend/pull/3526 we were hit by the following sequence of events:

- We updated Clang from 3.8 to 3.9 which was only recently added to mason
- Out vendored third_party/mason does not yet include those changes
- The Travis script then fails to get Clang 3.9 and fails silently
- The build continues with the system's default Clang 3.5 compiler

Check:
- https://travis-ci.org/Project-OSRM/osrm-backend/jobs/189152203#L1969
- https://travis-ci.org/Project-OSRM/osrm-backend/jobs/189152203#L1988

We only noticed this since the Clang 3.5 debug build hits an issue with type deduction.

An error in the mason setup should fail builds hard.

**Comment by springmeyer** [comment]
This is a systemic problem with our travis.yml. We use a lot of `if` statements and any failure inside them will not stop the build (as you would expect). See http://steven.casagrande.io/articles/travis-ci-and-if-statements/ for a good explanation. This is the reason that node-osrm moved nearly all logic into a single bash script https://github.com/Project-OSRM/node-osrm/blob/fc560d42eb2d1cbef6fe9373a05b369c80d8d14b/.travis.yml#L47 and I think we should do the same for osrm-backend.
