### ISSUE TITLE
The demo server has some Errors

### ISSUE THREAD

**Issue by emilvrany** [Project-OSRM/osrm-backend#3532]
The demo server has an error when you try to make a route:

https://router.project-osrm.org/route/v1/driving/26.08333,44.5;26.021031,44.933619?overview=false&steps=true;

Error: 
Failed to load resource: the server responded with a status of 404 (File not found)

**Comment by danpat** [comment]
@emilvrany Known issue - the demo server runs the latest `master` code, so sometimes comes across bugs - it's currently re-processing a new planet file, it's about 95% complete (as I write this message).

**Comment by daniel-j-h** [comment]
Resolved. The demo server is up again and your request works. Closing here.
