### ISSUE TITLE
Assertions should log coordinates wherever possible

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3533]
We've got lots of assertions all over the codebase, which is great.

What's not so great is that if we hit one when dealing with planet-sized data, it's often very difficult to track down what the cause was.

Many errors are location specific - they are caused due to specific network shape or properties.

We should create a wrapper to `BOOST_ASSERT`, called `OSRM_ASSERT_WITH_LOCATION`, where we pass in location data.  If the assertion is thrown, we should log the coordinates in addition to the failed assertion information.  This would (hopefully) make it much faster to track down datasets to reproduce the problem.

This is not always going to be possible, but it would massively speedup debugging for location-specific assertion failures.

**Comment by daniel-j-h** [comment]
Now _someone_ only needs to use it ;)
