### ISSUE TITLE
Maximum number of parallel calls

### ISSUE THREAD

**Issue by pocman** [Project-OSRM/osrm-backend#3539]
Hi, 

I'm running OSRM using [this docker image](https://hub.docker.com/r/cartography/osrm-backend-docker/) on one AWS t2.medium instance.
I have timeout error when trying to run more than 4000 simple route queries in parallel even if cpu is <10% and memory ~60%. `http://me-url-here/route/v1/car/3.06714200,50.63505140;3.05399900,50.60952340`

How can I increase the number of accepted concurrent calls ? 
Can I active some logs to see what is happening ?

**Comment by daniel-j-h** [comment]
Sidenote: we have official Docker images for the latest stable releases:
https://hub.docker.com/r/osrm/osrm-backend/

Can you elaborate on your timeout issue? From what I can see your Docker image is running extract, contract and then is simply starting the osrm-routed http server:

https://github.com/cartography/osrm-backend-docker/blob/402e0d828ac96c47a3b27c955123af54f8fac3c9/docker-entrypoint.sh#L19

There should be no limit other than imposed by your environment. For example, is your http server hitting the max. amount of memory? Are you swapping? We need more details here.

**Comment by TheMarex** [comment]
Could also be disc access for the coordinate lookup. Depending on the docker version there are known problems for slow disk access.

**Comment by daniel-j-h** [comment]
Good point - follow this ticket and linked refs https://github.com/Project-OSRM/osrm-backend-docker/issues/1 for context.

**Comment by pocman** [comment]
My docker-entrypoint.sh is only running : 
```
#!/bin/bash
DATA_PATH=${DATA_PATH:="/osrm-data"}

_sig() {
  kill -TERM $child 2>/dev/null
}
if [ $# -eq 4 ]; then
  pip install awscli
  aws s3 cp $4/latest/ $DATA_PATH/ --recursive
fi
if [ "$1" = 'osrm' ]; then
  trap _sig SIGKILL SIGTERM SIGHUP SIGINT EXIT

  ./osrm-routed $DATA_PATH/$2.osrm --max-table-size 8000 &
  child=$!
  wait "$child"
else
  exec "$@"
fi
```
The extraction process is done in another docker image that upload the data to s3.

It looks like the memory is steady to 60% of the machine and the cpu is really low.
I'm running a request in parallel at least as fast as Play2.5 can handle a Future.sequence on an array of futures.

**Comment by daniel-j-h** [comment]
Can you check and see if the problem goes away when not using Docker?

You can easily get binaries via `npm install osrm` - check the `node_modules/osrm/lib/binding/` directory and extract, contract your base map with those (you will also find profiles in there).

**Comment by pocman** [comment]
@daniel-j-h are you able to run the following without timeout ?
```
ulimit -Sn 1000
ab -c 1000 -n 10000 "http://osrm-url/route/v1/car/3.06714200,50.63505140;3.05399900,50.60952340"
```

**Comment by daniel-j-h** [comment]
Just tried to reproduce this in a clean environment

```
docker run -it ubuntu:16.04 /bin/bash`
```

then following the instructions in the readme and spinning up `osrm-routed`. Now running the benchmark

```
ab -c 1000 -n 10000 'http://127.0.0.1:5000/route/v1/driving/13.388860,52.517037;13.385983,52.496891'
```

```
Completed 10000 requests
Finished 10000 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            5000

Document Path:          /route/v1/driving/13.388860,52.517037;13.385983,52.496891
Document Length:        86 bytes

Concurrency Level:      1000
Time taken for tests:   2.949 seconds
Complete requests:      10000
Failed requests:        0
Non-2xx responses:      10000
Total transferred:      3840000 bytes
HTML transferred:       860000 bytes
Requests per second:    3391.14 [#/sec] (mean)
Time per request:       294.886 [ms] (mean)
Time per request:       0.295 [ms] (mean, across all concurrent requests)
Transfer rate:          1271.68 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  118 298.1     19    1036
Processing:     5   73  94.4     46    1633
Waiting:        3   63  92.8     39    1633
Total:         19  191 347.6     64    2631

Percentage of the requests served within a certain time (ms)
  50%     64
  66%     80
  75%    110
  80%    133
  90%   1034
  95%   1084
  98%   1274
  99%   1464
 100%   2631 (longest request)
```

looks good for me. I can not reproduce your issue.

**Comment by daniel-j-h** [comment]
@pocman any updates on your side? Otherwise I'm inclined to close this as can't-reproduce.

**Comment by pocman** [comment]
Hi,
I'm not able to reproduce it without a significant network lag.
You can close the issue. Thanks for your time.

**Comment by daniel-j-h** [comment]
Perfect, great to hear. Happy routing!
