### ISSUE TITLE
500 error on demo server

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#3540]
Request `https://router.project-osrm.org/match/v1/car/-73.96537000003526,40.75900000000774;-73.9659099999901,40.75874999999795?radiuses=12;16&annotations=true&steps=true&geometries=geojson&overview=full` cause http 500 error on the demo server.

**Comment by daniel-j-h** [comment]
Perfect thanks for figuring out the crashing request, @MoKob is already looking into it.

**Comment by gardster** [comment]
Seems to be fixed.

**Comment by markus-hentschel** [comment]
It doesn't seem to be fixed? I try 
https://router.project-osrm.org/route/v1/foot/13.0,54.31;13.01,54.3?overview=simplified&geometries=geojson
and get the 500 Internal Error...

**Comment by MoKob** [comment]
The demo server is constantly crashing due to some bad request. It seems to be broken for specific request, even though the request is working fine at other times. Currently investigating this issue.

**Comment by MoKob** [comment]
Figured out the problem: it is connected to our sliproad refactor which can mess up the combination of sliproads and roundabouts. One example can be found here: http://www.openstreetmap.org/search?query=-34.504853%20-56.049853#map=19/-34.50527/-56.04901 which combines a sliproad that enters a roundabout, breaking the combination of both.
