### ISSUE TITLE
Route geometry overview granularity. 

### ISSUE THREAD

**Issue by midhunkrishna** [Project-OSRM/osrm-backend#3549]
When requesting for route like http://router.project-osrm.org/route/v1/car/-88.9981995,34.4866676;-86.5933484,34.7560044;-86.6027908,33.6213493;-86.85601,33.284164?alternatives=false&geometries=polyline&overview=full, with overview=full gives ~18000 pairs of lat-longs

Requesting the same, with overview=simplified, http://router.project-osrm.org/route/v1/car/-88.9981995,34.4866676;-86.5933484,34.7560044;-86.6027908,33.6213493;-86.85601,33.284164?alternatives=false&geometries=polyline&overview=simplified returns only 44 pairs of lat-longs. 

Is there any way to adjust the zoom level of the overview other than these two settings?

**Comment by danpat** [comment]
@midhunkrishna Those are the only two externally visible options.

The amount of simplification applied with `overview=simplified` varies depending on the bounding box of the route line - the larger the area, the more aggressive the simplification.

The actual code for this lives here:

https://github.com/Project-OSRM/osrm-backend/blob/1153b78c0671120d7ea467a9f21995c74226141a/src/engine/guidance/assemble_overview.cpp#L74-L78

but it's not configurable at runtime.

How would you use an adjustable option?

**Comment by daniel-j-h** [comment]
What you can also do already at the moment:
- get yourself the most detailed geometry
- run simplification (Douglas Peucker) until the granularity suits your needs

this can all happen on the client side, with the only downside of having to transfer a high-detailed geometry.

**Comment by daniel-j-h** [comment]
Closing this as not actionable on our side. Use simplification as described above.

If you want a query parameter open a feature request ticket, with use-case and outline for this.
