### ISSUE TITLE
make alternative route optional?

### ISSUE THREAD

**Issue by karme** [Project-OSRM/osrm-backend#357]
maybe it would be a good idea to make the alternative route calculation optional as it is quite slow at the moment?

**Comment by sanju74** [comment]
Hello, Is it possible to get minimum one alternate route using routing API. Now we have option if we need alternate route or not can we have option to specify minimum 1,2,3 alternate route? Thanks!

**Comment by woodbri** [comment]
@sanju74  No, currently you can ask for an alternate route and IF one can be found it will be returned. Only one alternate is looked for and it is possible that no alternates will be found. There are specific rules for deciding what is an alternate route, but I don't remember all the details.
