### ISSUE TITLE
Regression introduced in #3575

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3582]
Backporting https://github.com/Project-OSRM/osrm-backend/pull/3575 to the 5.5 branch I can see failures in the perception feature but not on master.

Here are the changes I could pinpoint it to:
- https://github.com/Project-OSRM/osrm-backend/blob/5.5/include/extractor/guidance/intersection.hpp#L36-L42
- https://github.com/Project-OSRM/osrm-backend/blob/master/include/extractor/guidance/intersection.hpp#L47-L53

and comparator in use https://github.com/Project-OSRM/osrm-backend/pull/3575/files#diff-5ba817e16c4faf2ff01b312c1802f695R145.

We need to resolve this before doing a 5.5.4 release. cc @danpat @MoKob

**Comment by MoKob** [comment]
This seems to be an issue between 5.5 and master. The order in master and 5.5 have diverged for this function in [the refactor of merging roads](https://github.com/Project-OSRM/osrm-backend/commit/e6ff17ab2ac37518b9da108191d3aad2dce5d1b5), I don't remember why that was exactly. This PR is not part of 5.5, so the order has to be switched for this function in the backport.

**Comment by daniel-j-h** [comment]
Cherry-picked and adapted: https://github.com/Project-OSRM/osrm-backend/commit/bfbdd18834560f69c51d88fead3ffd292ee53837. Phew.

5.5.4 should be ready to do.
