### ISSUE TITLE
Significant difference between OSRM and Google/Bing

### ISSUE THREAD

**Issue by oddg** [Project-OSRM/osrm-backend#3584]
I have been puzzled by a factor 2 difference between the ETA given by OSRM and the ETA given by Google between two points:
- [osm](http://map.project-osrm.org/?z=11&center=-38.722751%2C145.993195&loc=-38.826044%2C145.998129&loc=-38.631468%2C145.729574&hl=en&alt=0) says 1 hour 10 minutes
- [Google](https://www.google.ca/maps/dir/60+Seaview+Dr,+Walkerville+VIC+3956,+Australia/49+Bayview+Ave,+Inverloch+VIC+3996,+Australia/@-38.7314682,145.7692891,11z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x6b2a4646c5e4cc89:0x5e537f193de4cd47!2m2!1d145.9989027!2d-38.8243708!1m5!1m1!1s0x6b2a13bf0e722f13:0x589a78a31388814c!2m2!1d145.732227!2d-38.631574!3e0) says 33 minutes
- Bing says 40 minutes

A coworker updated the [max-speed](https://wiki.openstreetmap.org/wiki/Key:maxspeed) on the [route](http://www.openstreetmap.org/way/315550975#map=12/-38.7580/145.9097) but it did not solve the issue. Is there anything else we can do?

**Comment by danpat** [comment]
@oddg Prior to the `maxspeed` change, the road was tagged as `highway=tertiary`, which OSRM sets to 32km/h.  That explains why it takes an hour to make a 42km trip.

The OSRM demo server updates when it can - we try to do it daily, but it runs the latest unstable code, so sometimes bugs prevent new data from being loaded in a timely manner.  Right now, the map being used by the OSRM demo server is about a week old - too old to include your colleague's change.

Once it arrives, the `maxspeed` should take effect and reduce the ETA to something more reasonable.

**Comment by oddg** [comment]
Great news! Thank you.

PS: I could not figure out when was the last update of the data used by OSRM demo server. Is this information publicly available?

**Comment by danpat** [comment]
@oddg You can hit:

http://router.project-osrm.org/status

and you'll get some details about what version of the code it's running and the OSM data in use.  Looks like there's a bug on that, the `OSM` field should be showing a date.

Currently, it looks like data was last processed about 3 days ago.

**Comment by oddg** [comment]
Thanks, that exactly what I was looking for.

**Comment by daniel-j-h** [comment]
For digging deeper check the debug map:

http://map.project-osrm.org/debug/#13.2/-38.7213/145.8827

It shows internal maxspeeds derived from all osm tags (and if you zoom in further even turn penalties).

**Comment by daniel-j-h** [comment]
I'm closing this as a data issue. Not much we can do there on our side.
