### ISSUE TITLE
OSRM uses man_made=bridge lines to route?

### ISSUE THREAD

**Issue by yuryleb** [Project-OSRM/osrm-backend#3588]
Please look at very strange route of your demo server: http://map.project-osrm.org/?z=18&center=59.923917%2C30.390326&loc=59.923916%2C30.390327&loc=59.924363%2C30.388628&hl=en&alt=0
![route through man_made bridge line](https://cloud.githubusercontent.com/assets/4529411/22125968/432a7d44-deaf-11e6-9bf8-ed909963c00f.png)

As I could see, it proposes to make U-turn on non-highway line (man_made=bridge)??? Or demo server uses obsolete/wrong OSM data in this area (Saint Petersburg, Russia) and should not be used there?

BTW destination is not "Проспект Обуховской Обороны", this way is "площадь Александра Невского" in OSM.

**Comment by danpat** [comment]
This looks like bad OSM tagging.  `man_made=bridge` should be on the outline, `bridge=movable` should be on the road.

http://wiki.openstreetmap.org/wiki/Key:bridge
http://wiki.openstreetmap.org/wiki/Key:man_made

Here you can see how we route around the bridge outline:

![screen shot 2017-01-19 at 1 44 04 pm](https://cloud.githubusercontent.com/assets/1892250/22126663/753cd500-de4d-11e6-8bd2-678e69612a71.png)

![screen shot 2017-01-19 at 1 44 14 pm](https://cloud.githubusercontent.com/assets/1892250/22126667/7ba49ff4-de4d-11e6-97c3-8e457bb63cc1.png)

**Comment by yuryleb** [comment]
Maybe (although it's quite strange to distribute bridge structure properties between different entities), but nevertheless routing through non-highway looks very disputable. Especially for car profile.

**Comment by danpat** [comment]
Hmm, there is a more detailed description here:

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge

The wiki states that `bridge=movable` should be applied to the area, so the tagging here actually does look valid.

Our `car` profile only looks for the presence of the `bridge=` tag, it doesn't require it in combination with a `highway=` tag - that might be a mistake.

http://keepright.at/ has checks for bridge tags:

> bridge-tags: Someone draws a bridge and forgets to tag it as highway... A bridge should always have one of the 'major' tags that its direct neighbour ways have. Currently these are: highway, railway, cycleway, waterway, footway, piste, aerialway, pipeline, building, via_ferrata

We should strongly consider only routing over bridges that also have one of those corresponding tags (at least the ones relevant to car routing).  Browsing around KeepRight, the number of `bridge=` ways with no corresponding `highway=` seems to be quite low.

@daniel-j-h @TheMarex thoughts?  If we make this switch, we might break routability in a few spots where we currently allow it, but I think we'd be more correct and in those cases, OSM should be fixed.

**Comment by yuryleb** [comment]
Calling ~~Ktulu~~ @zverik as one of authors of these extended bridge tags :smirk: This could affect to Maps.me routing too.

IMHO it's enough just to exclude `bridge=` checking at all from all OSRM profiles. No highway (circleway, etc) - no routing.

**Comment by Zverik** [comment]
I don't know why osrm has decided to route via `man_made=bridge`: nothing in that tag says you can drive along it. Maps.me has a different routing engine now, so it won't use such contours.

I invented the tag so that there will be some tags on bridge contours. I don't expect anybody to use them.

**Comment by TheMarex** [comment]
> @daniel-j-h @TheMarex thoughts?

`highway` + `bridge` seems sane to me. Are there any other conventions like that which we could be missing?

> we might break routability

Can we do a query of all ways that we use which have a `bridge` tag but no `highway` tag?

**Comment by daniel-j-h** [comment]
Can we do a query of all ways that we use which have a `bridge` tag but no `highway` tag?

Yes we can.

Looks bad at first

![map0](https://cloud.githubusercontent.com/assets/527241/22151898/7246c72e-df20-11e6-865a-cf8fb0ae5332.png)

In addition filtering out railway tags

![map1](https://cloud.githubusercontent.com/assets/527241/22151897/7244ec24-df20-11e6-9566-98c90e3f9763.png)

See here, click Wizard and play with it.

http://overpass-turbo.eu/s/lnS

**Comment by yuryleb** [comment]
As I could see, most results of query above are `man_made=pipeline` ways. There are also real pedestrian bridges like [this one](https://www.openstreetmap.org/way/405475171) but all they have valid footways. Is there any other reason to exclude `bridge=*` checking from all profiles at all?

**Comment by pnorman** [comment]
> Our car profile only looks for the presence of the bridge= tag, it doesn't require it in combination with a highway= tag - that might be a mistake.

Yes, that is a mistake. As seen above, bridge=* is validly applied to lots of stuff that isn't a highway. I also find it somewhat surprising that OSRM even cares about bridge tags.

**Comment by yuryleb** [comment]
Proposed commit fixed OSRM routing (built from current master state):
![ubuntu 64-bit-2017-02-21-15-30-12](https://cloud.githubusercontent.com/assets/4529411/23168834/0839917a-f863-11e6-9c10-2245dffe2b38.png)

**Comment by yuryleb** [comment]
Fixed with #3739

**Comment by daniel-j-h** [comment]
Thanks!
Note that the demo server is currently pre-processing.
If you wait roughly a day you should see it live, too!
