### ISSUE TITLE
Name Change Heuristic should work on String Views

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3590]
Splitting off from https://github.com/Project-OSRM/osrm-backend/pull/3459 to unblock getting it merged: the facades all return string views now (non-owning, read-only string access to the underlying block of memory). This is great, since we no longer copy strings around having to pay for unnecessary allocations when the strings are fixed in memory anyway.

As a result, all mutating callsites need to be adapted (which the initial PR does) - there is one location left: the [name change heuristic](https://github.com/Project-OSRM/osrm-backend/blob/a48cf58468df49cc8275195ea64f426a3cbd364e/include/util/guidance/name_announcements.hpp#L28-L39) mutating strings in-place.

We should re-write this and then provide `requiresNameAnnounce` overloads working on string views.

**Comment by oxidase** [comment]
`requiresNameAnnounce` for string views is implemented in 742c32d936f2b08043d3f05b9ffdfa1b595bfdbc
