### ISSUE TITLE
osrm-datastore stucks in v5.5.3

### ISSUE THREAD

**Issue by Behizz** [Project-OSRM/osrm-backend#3594]
Hello
I've installed OSRM v5.5.3 on my ubuntu 14.04 server, when I'm trying to make it running sometimes osrm-datastore stucks and prints this message (it happens a lot):
[info] Waiting for all queries on the old dataset to finish:

I've waited so long for queries to finish but didn't help. What is the problem?

Thanks

**Comment by oxidase** [comment]
Hi, data storage was recently changed to prevent similar dead locks. It is not reflected in https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.5.4 but it is in commits 774b8688cace7d07b454dc1e6e20d5965ded3708..70e899378d4a7485ed991d04faf5675ccd9dc10c

/cc @danpat

**Comment by danpat** [comment]
Hmm, we could backport that, but I think we'll be releasing OSRM 5.6 in the very near future, so I think we'll just wait until then.

@Behizz you can switch to running the latest code from `master` which should address this, but that comes with its own risks.

**Comment by TheMarex** [comment]
Closing as not actionable/no feedback from user.

**Comment by Behizz** [comment]
Thanks @danpat , I switched to master branch and it's working fine.
