### ISSUE TITLE
Error: no rule to make target /usr/lib64/libtbbmalloc.so

### ISSUE THREAD

**Issue by Fabian-Manurung** [Project-OSRM/osrm-backend#3596]
`make[2]: *** No rule to make target '/usr/lib64/libtbbmalloc.so', needed by 'osrm-contract'. Stop. 
make[1]: *** [CMakeFiles/osrm-contract.dir/all] Error 2
make: *** [all] Error 2`

I installed the most packages from source code, TBB aswell because my repo (CentOS 6) only supports TBB 2.1 and needed was 4.4 but i get this error every time i try to run the make command. 

I included tbb by the cmake parameters: 
     -DTBB_INCLUDE_DIR=/opt/osrm_infrastructure/tbb44/include
     -DTBB_LIBRARY_DIR=/opt/osrm_infrastructure/tbb44/lib

but the libtbbmalloc.so library still gives me this error
I tried everything i could to run OSRM on CentOS but it just wont run... 
I followed the steps on the wiki page but some Packages i couldn't install with `yum`, because in my repo where only older versions than neccessary, so i had to build them from source and now i have this error.

**Comment by daniel-j-h** [comment]
Disclaimer: we don't have much experience with CentOS. It seems like every now and then users build it there but you probably have to do quite a bit of manual work to get all needed recent dependencies.

That said the easiest way is to use the pre-built Docker image:
https://hub.docker.com/r/osrm/osrm-backend/tags/

If that's not an option use `ccmake` to get a ncurses gui, configure and check where the TBB paths are set to. Also after you ran cmake check

    build/CMakeFiles/osrm-contract.dir/flags.make
    build/CMakeFiles/osrm-contract.dir/link.txt

in there you should find the include dir and library dir. If not, cmake was unable to pick them up.

**Comment by Fabian-Manurung** [comment]
Now i get this error:
`Linking CXX static library libosrm_contract.a
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ar terminated with signal 11 [Segmentation fault], core dumped
make[2]: *** [libosrm_contract.a] Error 1
make[1]: *** [CMakeFiles/osrm_contract.dir/all] Error 2
make: *** [all] Error 2`

but i could modify some Paths with the `ccmake` command

**Comment by daniel-j-h** [comment]
Segfault during linking? There seems to be quite something off with your environment.
Are you sure you are not mixing compilers, stdlibs or compilation flags there?

Without more information I can't help you much.

Note: you said you built all dependencies from source. Did you make sure to use the same compiler and the same stdlib there? I would also recommend building static libraries (except for TBB) as it will make your life easier.

**Comment by Fabian-Manurung** [comment]
I build only these five from source:
>Lua 5.1
>LuaJIT-2.0.2
>STXXL
>Boost 1.57
>TBB 4.4

all other I installed with `yum` 

do i need to include the libosrm_contract.a? I thought it will be automatic included because it's in the osrm-backend folder.

It seems that all is correctly included as i saw in the `ccmake` command.
Is there a way to save the informations from the `ccmake` command so i can show them to you?

**Comment by daniel-j-h** [comment]
(You don't need LuaJIT)

No you don't need to manually include any library, the steps outlined [here](https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM) (for Ubuntu) should be fine.

Here's my take on what could happen: you built the dependencies with a different compiler or stdlib (or link-time optimization?) and are now hitting a compiler issue. I have no insight into your environment or build process there. That's why we recommend going the Docker route and only building from source if you have to. Or you're out of luck and hitting a specific linker issue which only manifests on CentOS.


What you can try is: upgrade your compiler, build all deps from source as static libraries (`-DBUILD_STATIC_LIBS=ON`), then build `osrm-backend` again. Make sure the compiler and stdlib for all these is the same.

**Comment by daniel-j-h** [comment]
@Fabian-Manurung any update here? Otherwise I'm inclined to close this.

Although we'd like OSRM to be compilable on different platforms the reality is there are too many combinations of compiler, stdlib, dependencies, etc. for us to test and debug ourselves.

**Comment by daniel-j-h** [comment]
Closing. Please re-open if this still is an issue and you think we can help you there. As said, we don't have much experience with CentOS but users seem to be able to compile it there from what we know.
