### ISSUE TITLE
Make edge weight a strongly defined type

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#3601]
Working on #2399 found different weight types 
* `unsigned` https://github.com/Project-OSRM/osrm-backend/blob/a5d0707dd0f081c6b4b98fdc36201567a2cfbbfe/include/contractor/contractor_graph.hpp#L29
*  `std::int32_t` https://github.com/Project-OSRM/osrm-backend/blob/a5d0707dd0f081c6b4b98fdc36201567a2cfbbfe/src/engine/routing_algorithms/routing_base.cpp#L23
* `int` https://github.com/Project-OSRM/osrm-backend/blob/a5d0707dd0f081c6b4b98fdc36201567a2cfbbfe/src/engine/routing_algorithms/many_to_many.cpp#L131

PR #2399 unifies weight types as `EdgeWeight` but compile-time type checking is required to check all places. 
It would also good to define strongly typed `EdgeDuration`, `TurnWeight` and `TurnDuration` to have compile-type checks and avoid problems by mixing edge/turn weights and durations.

**Comment by daniel-j-h** [comment]
Yes, yes please. I poked @danpat often enough some time ago that we ended up building and incorporating

https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/strong_typedef.hpp#L43
https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/typedefs.hpp#L40-L44

which is similar to the one in Boost, except that it does not allow implicit conversions.

**Comment by danpat** [comment]
@oxidase yeah, you want to take a look and see if `OSRM_STRONG_TYPEDEF` is usable here?  Check the `OSMNodeID` type as an example (also, include/util/coordinate.hpp where we use it to prevent lon/lat swap mistakes).

It *should* be fully optimized away under `-O3`, and will give the compile-time checking you're after.

**Comment by TheMarex** [comment]
This has no clear priority right now. We should have a look at this when we got some downtime for refactors.
