### ISSUE TITLE
How to apply the Delta changes on OSRM

### ISSUE THREAD

**Issue by subbuj9** [Project-OSRM/osrm-backend#3626]
I have implemented and loaded North America data and working as expected.

Now i want to apply the delta changes(like .osc files). How to do this ??

**Comment by danpat** [comment]
@subbuj9 There is no delta update feature in OSRM - you will need to generate and updated .osm.xml or .pbf file and re-run the OSRM tools.

Unfortunately, OSRM's internal data structures are not designed with delta updates in mind, so add this capability would be extremely difficult.

**Comment by subbuj9** [comment]
Hi Danpat, thanks for your quick reply.

Is it possible to generate OSRM files in one server(Offline Server) and run osrm-routted service in different server?

**Comment by danpat** [comment]
@subbuj9 yes, you can do that, as long as the servers have similar configurations (CPU type, operating system, libraries, etc).

The OSRM datafiles are basically just memory dumps - if the two servers are similar, the files work fine.  Generating files on Windows and running `osrm-routed` on Linux usually doesn't work.  Unfortunately, OSRM has no good built-in checks, the only way you'll know is if it crashes, or gives very weird results.

**Comment by danpat** [comment]
I'm closing this ticket as non-actionable.  If at some point in the future we want to dive into supporting deltas in some form, we can open a new ticket.
