### ISSUE TITLE
osrm-extract triggers on demo server

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3629]
seeing

`[assert][140281425536896] /mnt/ebs/osrm/2017-01-30-173002/src/extractor/extractor_callbacks.cpp:149` (triggering [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/extractor_callbacks.cpp#L149))

on the demo server. This seems to be most likely to be connected to the merge of https://github.com/Project-OSRM/osrm-backend/pull/2399 on https://github.com/Project-OSRM/osrm-backend/issues/77 since it introduces the assertion [here](https://github.com/Project-OSRM/osrm-backend/commit/279f8aabfb67bda62b51cc32542ea18a812e4823#diff-8713a422b8d487cb0e1670bdfcc7fde0R149).

/cc @oxidase @TheMarex

**Comment by oxidase** [comment]
assertion occurs at http://www.openstreetmap.org/node/181295699 The current car profile allows to use the street http://map.project-osrm.org/?z=18&center=53.077581%2C8.808975&loc=53.077405%2C8.808852&loc=53.077689%2C8.809131&hl=en&alt=0
