### ISSUE TITLE
Make trip only return a trip if all waypoints can be included

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3634]
Currently we run an SCC analysis on every distance table we generate for the trip plugin and only compute trips for each each component.

This can have unexpected results when users accidentally include waypoints from other continents. In that case the trip plugin will return multiple trips, one for each component. This behavior is notably different then for example the `route` plugin which would generate an error in that case.

The most extreme case is when each waypoint is in an own component leading to 0 duration trips that only contain one waypoint each.

To make this more consistent with the `/route` plugin I would suggest just throwing an `NoTrip` error if a single trip with all waypoints is impossible.

To make migration easier we should add a parameter to `TripParameters` e.g. `bool TripParameters::split_trip = true`. That way we would only need to switch the default from `true` -> `false` for the next API iteration.

/cc @freenerd @chaupow @ghoshkaj

**Comment by chaupow** [comment]
> To make migration easier we should add a parameter to TripParameters e.g. bool TripParameters::split_trip = true. That way we would only need to switch the default from true -> false for the next API iteration.

Can you explain a bit? Does that mean, that we should still return multiple trips if all waypoints can't be reached?

Implementation-wise, the easiest solution would be to throw `NoTrip` if there are two points that can't be reached. 

But that would break the current API right? How does `TripParameters::split_trip = true` help here? If we will set `true -> false` it will be an API break anyways, right? Can't we throw it every time then?

**Comment by TheMarex** [comment]
Capturing from voice: The current behavior is more a bug then intended behavior. We are going to fix it in the next release, without adding a query parameter for it.
