### ISSUE TITLE
Treat surface=sett like surface=cobblestone:flattened for bicycles

### ISSUE THREAD

**Issue by ftrebien** [Project-OSRM/osrm-backend#3649]
I would like to ask for the surface speed of surface=sett to be considered the same as surface=cobblestone:flattened in bicycle.lua. OSM's wiki says that cobblestone:flattened is an inadequate description of sett, which is used much more often according to TagInfo.

**Comment by daniel-j-h** [comment]
Thanks for reaching out!

Sounds reasonable! Adding it in https://github.com/Project-OSRM/osrm-backend/pull/3657.

**Comment by daniel-j-h** [comment]
A fix for this just landed in master! If you see other issues with the profiles, please report them to us! :)

**Comment by ftrebien** [comment]
Great, thanks!

Actually, I would like to propose speeds for smoothness and tracktype, which are currently empty. By comparison with the current surface speeds and from the wiki definitions, it would be something like this:

smoothness
excellent/good: default_speed (similar to asphalt)
intermediate: 10 (similar to compacted)
bad/very_bad/horrible/very_horrible: 6 (similar to grass/earth)

tracktype
grade1: default_speed (similar to asphalt)
grade2-5: 6 (similar to gravel/earth)

Maybe this could be compared to [GraphHopper's speeds](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java), which suggest a little bit more variation could be used (grade2 could be 12 like track). They don't use smoothness though, and some of their speeds don't make much sense to me (such as for surface=unpaved).

As a tiny refinement, surface=concrete could be defined as default_speed too, like asphalt.

**Comment by emiltin** [comment]
sounds like a good idea
