### ISSUE TITLE
Set speeds for smoothness and tracktype in the bicycle profile

### ISSUE THREAD

**Issue by ftrebien** [Project-OSRM/osrm-backend#3680]
I would like to propose speeds for smoothness and tracktype, which are currently empty. By comparison with the current surface speeds and from definitions in OSM's wiki, it would be something like this:

_smoothness_
excellent = default_speed (like asphalt)
good = default_speed (like asphalt)
intermediate = 10 (like compacted/sett/paving_stones)
bad = 6 (like grass)
very_bad = 5 (a little worse)
horrible = 4 (a little more worse)
very_horrible = 3 (like sand)

_tracktype_
grade1 = default_speed (like asphalt)
grade2 = 6 (like gravel)
grade3 = 5 (even mixture of gravel/pebblestone and sand)
grade4 = 4 (sand with some gravel/pebblestone)
grade5 = 3 (like sand)

**Comment by daniel-j-h** [comment]
:wave: Hey hey, thanks for reaching out - I think @emiltin is in a good position to give you feedback for all these bike related improvements. What you can do to speed things up is this:

- Clone this repository
- Make your proposed changes
- (Optional: build osrm, then npm install && npm test and see tests failing - adapt and add new tests)
- Open a Pull Request and tag @emiltin for review

**Comment by emiltin** [comment]
i think it's a good idea to add speeds for smoothness and tracktype.
