### ISSUE TITLE
Speed for surface=fine_gravel too low for bicycles

### ISSUE THREAD

**Issue by ftrebien** [Project-OSRM/osrm-backend#3681]
Currently the speed for surface=fine_gravel is 6, the same as for other surfaces in which the cyclist is assumed to be walking. OSM's wiki, however, says that fine gravel means "surface of firm, granular grit ... easy to walk, jog, cycle or ride on ... bicycles tires will not leave any imprints at least in dry weather".

This sounds similar to surface=compacted, "the surface is more stable than loose gravel ... mixture and compacting leads to more grip and stability". From that description, I think fine gravel should be considered  at least as fast as surface=compacted.

For comparison, [GraphHopper](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java) considers fine gravel as fast as the default speed in asphalt.

**Comment by emiltin** [comment]
i also think that some of the current speed reduction should be replaced by change in rates. ie. the speed might be almost the same, but it's less attractive
