### ISSUE TITLE
Usage of negative turn penalties

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#3683]
Some tests in OSRM make turn penalties updates with negative value. This introduces incorrect behavior in snapping start points and may lead to quite non-obvious problems like #3647 and #3641. 
Practically, negative turn penalties would make turns more preferable instead of going straight with 0 turn penalty. This can be achieved also by using a positive bias value and making all turn weight penalties positive. Duration values are not used as key values in heaps and can be negative.

 - [ ] clarify domain of turn penalties
- [ ] review tests features/car/traffic_turn_penalties.feature and features/testbot/traffic_turn_penalties.feature 
- [ ] adjust updates https://github.com/Project-OSRM/osrm-backend/blob/005124fe1c5c2e71a17531023b2437685b08ff6e/src/contractor/contractor.cpp#L832-L841 
- [ ] add non-negativity check of weights at https://github.com/Project-OSRM/osrm-backend/blob/005124fe1c5c2e71a17531023b2437685b08ff6e/src/contractor/contractor.cpp#L460-L467
- [ ] add at https://github.com/Project-OSRM/osrm-backend/blob/005124fe1c5c2e71a17531023b2437685b08ff6e/src/engine/routing_algorithms/routing_base.cpp#L112 assertion that `to_weight >= 0`

/cc @danpat

**Comment by danpat** [comment]
I think that we should allow for negative turn penalty values.

Consider a simple intersection where most of the traffic is *not* taking the straight maneuver - 25% of the traffic volume goes straight, 75% makes the right-hand turn:

![screen shot 2017-02-13 at 4 09 07 pm](https://cloud.githubusercontent.com/assets/1892250/22909076/cc047560-f206-11e6-9145-f20e4a241cae.png)


Let's say we have samples of all cars passing the "Average speed" measurement point.  It's likely that the average speed is biased towards cars making the turning maneuver.

In this case, it would make sense for the 25% straight through traffic to receive a "negative turn penalty" - it's faster than average to proceed straight.

Of course, the validity of this idea depends on these biases existing.  If the speed approaching the intersection is the average of the vehicles making the fastest maneuver, then all penalties can be positive for the same effect, and the fastest maneuver would have a penalty of 0.
