### ISSUE TITLE
Refactor `annotations` paramater

### ISSUE THREAD

**Issue by chaupow** [Project-OSRM/osrm-backend#3684]
Crossposting from https://github.com/Project-OSRM/node-osrm/issues/297:

**tl;dr: node-osrm doesn't pass all tests anymore and its probably due to a bug in #3628**

<img width="1343" alt="screenshot 2017-02-10 11 35 09" src="https://cloud.githubusercontent.com/assets/804027/22823731/21f0ded4-ef85-11e6-908b-d2c30c9575d0.png">
https://travis-ci.org/Project-OSRM/node-osrm/builds

tests are failing due to response not having `annotations` even though the request is set to `annotations=true`

this is a blocker for 5.6

/cc @danpat @TheMarex

**Comment by chaupow** [comment]
In oder to implement https://github.com/Project-OSRM/osrm-backend/issues/3563
and to not add a breaking API change, we currently have two parameter member variables:
```
bool annotations
AnnotationsType annotations_type
```

this makes node-osrm have to handle two parameters. it should be made such that there's only one parameter:
```
AnnotationsType annotations
```

and still making sure `annotations=true|false` doesnt fail.

**Comment by daniel-j-h** [comment]
@chaupow this is already ticketed for v6 in https://github.com/Project-OSRM/osrm-backend/issues/3644.

Until then, node-osrm handles Javascript. Therefore for node-osrm you can handle

    annotations=true

keeping the old API and at the same time support

    annotations='speed'

and support the new API in Javascript.

**Comment by chaupow** [comment]
> @chaupow this is already ticketed for v6 in #3644.

awesome. missed this. so this can be closed as the bug is fixable in `node-osrm`only.
