### ISSUE TITLE
Routing result is not visible on slow connections

### ISSUE THREAD

**Issue by erkinalp** [Project-OSRM/osrm-backend#3694]
Routing results are not visible on connections slower than ~10Mbps. i.e. You drop the position marks, geocode returns very fast, however, route is not displayed after choosing source and destination. Any routable source-destination pair works for reproduction.

**Comment by danpat** [comment]
This doesn't seem to have anything to do with 10Mbps connections, it simply looks like the OSRM demo server is not working right now.

```
GET https://router.project-osrm.org/route/v1/driving/-77.00832366943358,38.9591…2031,38.96434747083963?overview=false&alternatives=true&steps=true&hints=; 503 (Service Unavailable: Back-end server is at capacity)
```

**Comment by erkinalp** [comment]
OSRM died again?

**Comment by erkinalp** [comment]
@danpat: The problem mentioned in the first post also happens when OSRM is alive.

**Comment by danpat** [comment]
@erkinalp Can you check the demo server again please?  It is responding normally, I am unable to reproduce your problem, even when simulating a slow connection.  I can slow it down to as low as 50kbps and it works fine (a little slow perhaps, but there are no errors).

**Comment by erkinalp** [comment]
It works now.
