### ISSUE TITLE
http://router.project-osrm.org/table/v1/driving  is not working

### ISSUE THREAD

**Issue by boooch** [Project-OSRM/osrm-backend#3699]
http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219
this is URL from example. Answer:

```
Error response

Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI.
```

**Comment by goclem** [comment]
Same problem here, looks like the OSRM API is down...

**Comment by daniel-j-h** [comment]
Yes the osrm demo server is currently down. We fixed the issue and started a new processing run. Should be resolved in the next days. Please wait a bit.
