### ISSUE TITLE
`osrm-contract`crashed when empty segment speed file is supplied

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3702]
Previous to 5.6. we supported empty CSV speed file for `osrm-contract` now it is crashing with:

```
terminate called after throwing an instance of 'osrm::util::exception'
  what():  CSV file empty.csv malformed on line 1 (at src/contractor/contractor.cpp:277)
```

This is a regression to 5.5 and should be fixed for the final 5.6 release.

**Comment by mhsekhavat** [comment]
I am getting this error on v5.13.0:

    $ head updates.csv
    34032109,30893015,100.98683448412422
    27123603,27208167,86.59250961420997
    27208167,27123603,57.935196222999394
    26456139,26456140,61.9307160745025
    1653118112,3814100280,30.967910819793072
    3814100280,1653118112,49.991436688527536
    819644487,1189404212,27.977900453478394
    31128256,1896672085,39.000908228658005
    2784134658,906571905,41.01301807210246
    26366225,27193419,122.20893680068741

    $osrm-extract --version
    v5.13.0

**Comment by danpat** [comment]
@mhsekhavat the third column must be an integer - `100` instead of `100.9863....`

**Comment by mhsekhavat** [comment]
@danpat Thanks! Another question, third column is speed or duration? In [wiki](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) I found two lines which seems one of them is wrong: 

* In first paragraph (edge_speed): 

> each line has to follow the format from_osm_id,to_osm_id,edge_speed_in_km_h(,edge_rate?,(anything else)?)?

* In examples (duration):
`25296,25295,24          <- duration will be updated, weight will be updated to match duration`

**Comment by danpat** [comment]
It's speed, in km/h.
