### ISSUE TITLE
Routing is broken at demo site (and openstreetmap.org)

### ISSUE THREAD

**Issue by vgeorge** [Project-OSRM/osrm-backend#3707]
The router API is returning 404 status for routing requests, affecting OSRM page's demo and OpenStreetMap main website.

Example route:

http://map.project-osrm.org/?z=13&center=38.899517%2C-77.026863&loc=38.913476%2C-77.035446&loc=38.901587%2C-77.022915&hl=en&alt=0

**Comment by daniel-j-h** [comment]
Thanks for reporting, we're already aware of the issue and a fix landed in master this morning. The demo server has to do a full processing run again. This will take some hours. Please be patient.

**Comment by fernabel** [comment]
thanks!
