### ISSUE TITLE
OSRM without terminal open

### ISSUE THREAD

**Issue by tweemaalj1988** [Project-OSRM/osrm-backend#3714]
Hi there,

I have my own OSRM on my server online and activited (using Ubuntu). 
I have it installed on a webserver in a datacenter. 

I contact the webserver with SSH from my macbook at home. When i start the server in my terminal with: osrm-routed berlin-latest.osrm
it starts, and i can use a http request succesfull. 

But when i close the therminal on my macbook (or close my macbook etc.), the OSRM stops. 

Is it really necessaire to have my macbook terminal open all the time? To use OSRM on a webserver in a datacenter? Or is there another way? 

Much thanks!
Greetings!

**Comment by danpat** [comment]
@tweemaalj1988 This is not an OSRM problem, but rather a question of how to create a persistent daemon service on a Unix/Ubuntu machine.

This document is a starting point for how to do it: http://askubuntu.com/questions/351879/how-to-create-a-service-on-ubuntu-upstart

Use the search terms "how to create a service ubuntu" to find more links.

**Comment by oxidase** [comment]
@tweemaalj1988 you can do `nohup osrm-routed berlin-latest.osrm`, but correct would be to create own OSRM service.

@danpat would it make sense to add `osrm.service` as an example?

**Comment by danpat** [comment]
@oxidase sigh, I'm not sure.  We *could*, but then we'd end up fielding questions about how to work with upstart/SysVinit/systemd/whatever comes next.  I'd rather leave that part of the deployment problem to users, there are way too many systems out there for us to support.

I don't know how we'd reliably maintain the scripts either, as none of the core team would be using them.
