### ISSUE TITLE
The code function in wiki not found 

### ISSUE THREAD

**Issue by jhljx** [Project-OSRM/osrm-backend#3725]
In the wiki about Processing-Flow, just the following url.
https://github.com/Project-OSRM/osrm-backend/wiki/Processing-Flow

In the section of **Build Grid**, it says "WritableGrid::ConstructGrid() creates a datastructure that enables fast lookup of nearest node from a location. (a type of Location Sensitive Hashing?) ". But I couldn't find the function WritableGrid::ConstructGrid() in the source code. I think maybe the function has been changed. I find in the file of 'src/extractor/extractor.cpp', the function 'Extractor::BuildRTree' is the same meaning of WritableGrid::ConstructGrid().

**Comment by danpat** [comment]
@jhljx That wiki page is years out of date - we now use an RTree.

**Comment by jhljx** [comment]
Yes, I see. Thanks!

**Comment by danpat** [comment]
I updated the wiki page to indicate it's out of date.  One day, someone might find the time to update it.
