### ISSUE TITLE
Take care of lower speed than maxspeed in the handlers.lua

### ISSUE THREAD

**Issue by frankvandenbergh** [Project-OSRM/osrm-backend#3726]
In the handlers.lua the following function is present:
` function Handlers.handle_maxspeed(way,result,data,profile)
  local keys = Sequence { 'maxspeed:advisory', 'maxspeed' }
  local forward, backward = Tags.get_forward_backward_by_set(way,data,keys)
  forward = Handlers.parse_maxspeed(forward,profile)
  backward = Handlers.parse_maxspeed(backward,profile)
  
  if forward and forward > 0 then
	result.forward_speed = forward * profile.speed_reduction
  end

  if backward and backward > 0 then
    result.backward_speed = backward * profile.speed_reduction
  end
end`

I'm using a truck profile with in general much lower average speeds per road type than the maxspeed. In my profile I've 71 km/h for the highway and herafter the maxspeed is handled, that will result in say 80% of 130 km/hour = 104 km/hour.

What if the following code will be used:
`  if forward and forward > 0 and forward<result.forward_speed then
	result.forward_speed = forward * profile.speed_reduction
  end`

**Comment by Steffaan** [comment]
@frankvandenbergh I'm also using a truck profile and experience the same problem. How did you fix this? Did the above mentioned code give you correct results?

BTW: would you be willing to share your truck profile with me? Maybe we can help each other enhancing a truck profile that gives comparable results to then profiles of TLN-planner (PTV).

**Comment by frankvandenbergh** [comment]
Hi Stefan,

My truck.lua is derived from the car.lua.

I altered the diverse (max)speed arrays.

I commented  WayHandlers.maxspeed,

And I added the following code before the WayHandlers.run:
```
   -- max weight 40 tonnes  
  local maxweight = math.huge
  local maxweight_string = way:get_value_by_key("maxweight")
  if maxweight_string and tonumber(maxweight_string) then
    maxweight = tonumber(maxweight_string)
  end
  if maxweight < 40 then
     return
  end
    
  -- min 18 meters length
  local maxlength = way:get_value_by_key("maxlength")
  if maxlength and maxlength ~= "" then
     --print ("maxlength: " .. maxlength .. ", route: " .. route )
	 if tonumber(maxlength:match("%d*")) then
	    if tonumber(maxlength:match("%d*")) < 18 then
		   return
		end
	 end
  end
  
    -- no goods allowed
  local goods = way:get_value_by_key("goods")
  if goods and goods ~= "" then
     --print ("goods: " .. goods .. ", route: " .. route )
	 return
  end
  
  -- no heavy vehicles
  local hgv = way:get_value_by_key("hgv")
  if hgv and "no" == hgv then
    return
  end
```
I know this is not perfect, but for my project this was enough. I noticed some tags where not very accurate in openstreetmap (tunnels with chemical restrictions, no max height etcetera). In my test I had to alter some of the streetmap source.
