### ISSUE TITLE
Add an option to the lua scripts that will allow to ignore all conditional oneway roads. 

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#3727]
There are many conditional oneway roads inside OSM data. http://overpass-turbo.eu/s/mO8
Now OSRM looks only at `oneway` tag. It is normal for routing, but when I use it for matching, it fails to process tracks in case if `oneway=yes` and `oneway:conditional=no@(some options)`. So I want to have an additional option on the extract stage to ignore all conditional restrictions, that will choose weakest restriction. `oneway=no` for oneway roads.

**Comment by daniel-j-h** [comment]
cc @oxidase who worked on a tool to dump and ingest time-dependent conditional restrictions.

**Comment by daniel-j-h** [comment]
This landed with https://github.com/Project-OSRM/osrm-backend/pull/3728 :sparkles:
