### ISSUE TITLE
Further Work on Partitioning

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3731]
To not keep partitioning on a separate branch any longer, @daniel-j-h and I would like to move further tasks into `post-merge` land.

Multiple groups of issues can be worked on further:

## Optimisation

 - [ ] ~~Optimise balance for cuts: .25 ratio may result in .25 / .75 cuts (somewhat possible via annotation tool)~~
 - [x] Transform partition ids to edge based graph, outlined in https://github.com/Project-OSRM/osrm-backend/issues/3205
- [x] Border cases in the partition should probably be resolved in a smarter way (ebg - part I) (@daniel-j-h -- could you add some more context here ?)

## Documentation

 - [x] document the `.osrm.cnbg` `.osrm.nbg_to_ebg` files in our Wiki file listing
 - [x] document the new `osrm-partition` tool, its parameters and what it does

## Testing

 - [ ] ~~unit test edge-based-graph loader~~
 - [x] unit test annotation tool

## Output generation

- [ ] ~~Ebg loader could benefit from a  refactored with what the contractor does (if possible)~~  Covered by general graph refactor.
- [x] The Annotation tool can be augmented to output partition information for MLD
- [x] We need to write out the new transformed edge based graph for customize ( ebg - part II)

**Comment by TheMarex** [comment]
Remaining tasks are not actionable or covered by other issues.
