### ISSUE TITLE
Matching: force use every points

### ISSUE THREAD

**Issue by kaligrafy** [Project-OSRM/osrm-backend#3740]
Is it possible to force the match plugin to pass through the radius of every points provided, even if the confidence stays low? I use the matching algorithm to create bus routes passing through stops, but sometimes, when stops are too far apart, the resulting path just ignores them. I understand I am not using the algorithm for its intended purpose, but I have yet to find anything better than the match plugin for this (route algorithm is too precise and creates all kind of loops when the stop is not exactly on the right direction of the road or at the right corner of the street). See #3464 for more info about this.

**Comment by TheMarex** [comment]
@kaligrafy hrm, not sadly we don't have that option. What you are basically fighting against is our outlier detection algorithm.

You could try to disable a part in the code that could cause this https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/routing_algorithms/map_matching.cpp#L212-L216.
However sometimes all transitions are classified as impossible, the map matching algorithm could not continue with the point included. Sadly I don't have a good fix for you :-/

**Comment by kaligrafy** [comment]
Thanks, it seems to work pretty well! We could also add this as a parameter later on, but that is not urgent.
