### ISSUE TITLE
OSRM matching returns not valid JSON

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#3742]
Some requests, like:

http://router.project-osrm.org/match/v1/driving/-73.96225072895813,40.71787997347684;-73.96271938717034,40.718177439142494;-73.96332956622574,40.71856649081482;-73.96346430206849,40.718651418175114;-73.96374327734934,40.71878974758127;-73.96401431284875,40.71890965966577;-73.96414269808527,40.719266445983834;-73.96374716781024,40.71965763098896;-73.96340869764123,40.71952494286549;-73.9631843476825,40.71938734008776;-73.96286273618081,40.71925563430551;-73.96254116358708,40.7195560373697;-73.96209391311795,40.71997961715891;-73.96162893327617,40.72040563011518;-73.9608686437302,40.72110993701844;-73.95971792889554,40.72218073544323;-73.9590492952997,40.72281177252742;-73.95782451373314,40.723947667580916;-73.95758670940425,40.72500026486637;-73.9573233416442,40.72642265923241;-73.95707493748455,40.72704139386224;-73.95659683372773,40.72708662028779;-73.95551552396248,40.727382077345794;-73.95527041937137,40.72747030946252;-73.95462136260325,40.72768989358232;-73.95360721140307,40.728025855883345;-73.95278140256997,40.728298137810526;-73.95189764223838,40.72858578928205;-73.95126017577002,40.7288031739194;-73.95059373355274,40.729022753641146;-73.95085741286474,40.72948826025515;-73.95115849195719,40.72999455583147;-73.95165107968289,40.73090579062608;-73.95184811477402,40.73198617296703;-73.95201327654193,40.73299179404691;-73.95216105286005,40.73391184260808;-73.95233200977721,40.73462357717165;-73.95254538324491,40.735420327866166;-73.95266189197739,40.736127951581835;-73.95287941882933,40.73746001468595;-73.9527669205095,40.73851260180152;-73.9525606735901,40.73911853081549;-73.95228795039105,40.73993733420829;-73.9520612492314,40.74060760898075;-73.951786131879,40.7414205274855;-73.95160932711272,40.74197394140543;-73.95136862133938,40.742578922665245;-73.95130675339446,40.742771873535474;-73.95105261409034,40.742879070336954;-73.95054939010818,40.74277741830636;-73.95053799071982,40.74254473462656;-73.9506211730477,40.74231304057875;-73.95075260129033,40.74208247360281;-73.95091686969685,40.74207560222857;-73.95105567401338,40.74195824316615;-73.95137159893136,40.741716114972434;-73.95164853701291,40.74167902729772;-73.95203815490353,40.74164162376525;-73.95245054453957,40.74166753434875;-73.95284173445587,40.74166503513814;-73.95327491121175,40.741618294468736;-73.95372266498069,40.7415637992419;-73.95406310552204,40.741553886442546;-73.95493850880479,40.74152610850959;-73.95573553129951,40.74166281824904;-73.95665579328585,40.741832771686916;-73.95728074798767,40.74195267121243;-73.95778835604466,40.74205021642939;-73.95830535183228,40.74218992938219;-73.95898181647563,40.74241674230598;-73.95961597801447,40.742721772412324;-73.96010036460916,40.743030909714406;-73.96066327971461,40.7433916078497;-73.96157242001145,40.74397275025527;-73.96602870408249,40.746811328451514;-73.96743717634608,40.74768201233928;-73.96942484195696,40.74814385452069;-73.9704915402389,40.74780669005747;-73.97209105261372,40.74610937860683;-73.9735824252919,40.746072582303356;-73.97444182651235,40.74636395116016;-73.97542891216604,40.74676388686453;-73.97611411994653,40.74680806682281;-73.97652087094745,40.74639498306746;-73.97706330884743,40.74614980019197;-73.97805054267168,40.74656745879423;-73.97884433588438,40.746900768130075;-73.97964585245464,40.74724288906074;-73.98063322729868,40.74766003670746;-73.98114293053942,40.74753923475981;-73.98163326570503,40.74687063568308;-73.98197142421303,40.746343349178204;-73.98222715393364,40.74589762197863;-73.98242160661955,40.74560230310868;-73.98282761659156,40.74522331895071;-73.98347034905316,40.74548808893374;-73.98400998255966,40.74571911286151;-73.98428065587441,40.745944944463616;-73.98402540065985,40.74630835002944?radiuses=2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0;2.0&overview=full&annotations=true&geometries=geojson&steps=true

makes OSRM return not valid JSON answers. They have ```"speed": [6.8, 7.2, 1, inf],``` in the annotation filed.

**Comment by TheMarex** [comment]
Good catch. 👍  We need to clamp these values. This needs needs to be fixed before 5.6.
