### ISSUE TITLE
Penalize turns onto ways with restricted access: fees, customers

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3745]
In https://github.com/Project-OSRM/osrm-backend/pull/3721 @karenzshea implemented a penalty for turns onto restricted ways (think destination routing, hov ways, etc.). This makes sure we prefer alternative routes but we can still route you there _if you really want to go there_.

There is currently a discussion going on about zoos and other areas where customers have acces and / or you have to pay a fee for entry.

http://lists.openstreetmap.org/pipermail/talk-de/2017-February/113797.html

It would be great to support those tags (and maybe more?) in the same way.

- https://wiki.openstreetmap.org/wiki/Tag:access%3Dcustomers
- http://wiki.openstreetmap.org/wiki/Key:fee

cc @karenzshea

**Comment by daniel-j-h** [comment]
@bhousel just mentioned we should do the same for [`highway=track`](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack).

**Comment by daniel-j-h** [comment]
Same with the [toll=*](http://wiki.openstreetmap.org/wiki/Key:toll) tag (and related namespaced tags). Note there are "except" tags. Also fee tags.

**Comment by TheMarex** [comment]
> highway=track

There are some implications on data size that I think are worthwhile for ignoring this road-class for now.

**Comment by tyrasd** [comment]
[`highway=living_street`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street#National_specialities) does imply such a restriction in some countries, e.g. Austria.

**Comment by daniel-j-h** [comment]
Adding [`amenity=weighbridge`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dweighbridge) and similar weigh station tags.

**Comment by MichalPP** [comment]
is there a way to make `profile.restricted_penalty` different for different source and target ways? do I have a complete list of tags on source and target ways?

eg penalize left furn from primary & lanes > 1 to anything is duration+30

(looks like no: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md )

**Comment by daniel-j-h** [comment]
@MichalPP 

- [Here](https://github.com/Project-OSRM/osrm-backend/blob/1f69df0d892c8aa9d7694819f517aff0c01c7be4/profiles/car.lua#L418-L421) we apply the turn penalty in the turn function
- [Here](https://github.com/Project-OSRM/osrm-backend/blob/1f69df0d892c8aa9d7694819f517aff0c01c7be4/src/extractor/scripting_environment_lua.cpp#L375-L391) we bind the C++ turn to the Lua environment
- [Here](https://github.com/Project-OSRM/osrm-backend/blob/1f69df0d892c8aa9d7694819f517aff0c01c7be4/include/extractor/extraction_turn.hpp#L15-L33) is the C++ turn type

As you can see the turn object in the turn function does not know about tags anymore.
That said, we played around with passing more information to the turn function:
- https://github.com/Project-OSRM/osrm-backend/pull/2912
- https://github.com/Project-OSRM/osrm-backend/pull/3009

but this get de-prioritized.

Feel free to pick this up or help out here if it fits your needs.
We need to make the turn function smarter, for sure.

**Comment by MichalPP** [comment]
well, my C skills are really small.

if the `turn` in `process_turn(profile, turn)` function had a turn.source (listing all tags on source way), turn.target (listing all tags on target) and turn.node (all tags on the node the turn is on), it would fulfill all my dreams :)

another use case is than in hiking routing, penalize turns from marked route to an unmarked path. or in car profile, add a small penalty when changing to lower class highways so that shortcuts through residential areas are avoided (even though they are not destination only)
