### ISSUE TITLE
Don't penalize button-operated traffic lights

### ISSUE THREAD

**Issue by yuryleb** [Project-OSRM/osrm-backend#3747]
IMHO it's possible to don't assign penalty to [button-operated](https://wiki.openstreetmap.org/wiki/Key:button_operated) [traffic lights](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals). They are really usually at [pedestrian crossings](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcrossing) and used infrequently on on-demand basis.

**Comment by daniel-j-h** [comment]
Yes it's possible to do so, have a look here

https://github.com/Project-OSRM/osrm-backend/blob/5739c27ef4220d535c42cb4f4e460ac2533d85e6/profiles/car.lua#L280-L282

Not sure if it's a valid assumption to make, though.

**Comment by duizendnegen** [comment]
From my personal experience of going around in Hamburg and Amsterdam, button-operated traffic lights are as much a pain for the cars - they're used so much they should be seen as normal traffic lights I think.

I'd be happy to push some code to the default lua profile if we reach consensus here.

**Comment by yuryleb** [comment]
Seems you're so "lucky" driver as me :wink:

Of course, just excluding such traffic lights is the simpliest solution but not the best. It's really 2-3 strings code change in lua. But this also requires some new cucumber test and/or adopting/extending a lot of existing ones - and so I didn't push anything for this issue yet.

But actually this issue is the just preparation for another, the much important for me - increasing common traffic lights penalty to more realistic value than current 2 seconds. I already prepared some comparison of the same route with different traffic lights penalties but got quite strange results with previous OSRM v5.5.4 - the changing only one penalty type seems to break overall balance of all others. Maybe OSRM v5.6.0 will act better.

**Comment by emiltin** [comment]
the problem with just raising the traffic light penalty is that intersections are often modelled with multinodes nodes having traffic lights. but multiple traffic ligths changing together shouldn't incur a larger penalty. see #31 and #1250.

**Comment by yuryleb** [comment]
BTW it will be enough just to update LUA with new `button_operated` tag usage to get them extracted from OSM data into OSRM datafiles or something else like [taginfo.json](https://github.com/Project-OSRM/osrm-backend/blob/master/taginfo.json) should be also extended?

**Comment by daniel-j-h** [comment]
Hm right now we only support `highway=traffic_signals`. I quickly sampled some intersections in Berlin
- http://www.openstreetmap.org/node/961984568
- http://www.openstreetmap.org/node/392182854

and it seems like they're using the `crossing=traffic_signals` tag in combination with `button_operated`.

The first node has

```
crossing    traffic_signals
highway     crossing
```

the second one

```
button_operated    no
crossing           island;traffic_signals
highway            crossing
```

The Wiki makes an explicit distinction between traffic signal tags for pedestrians and cars:
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Traffic_signals_for_cars

It also states
> Add the following tags **in addition to highway=traffic_signals** for pedestrian crossings if the entire crossing is represented by a single node, **or to each highway=crossing nodes** if the pedestrian crossings are tagged on their own (strongly recommended).

A single traffic signal can have many crossings - I'm not sure if we should just add a penalty to _all_ crossings in addition to a penalty for the traffic signal. It seems like @emiltin's comment above is spot on.

**Comment by yuryleb** [comment]
I'm going to **don't** add penalties to `highway=traffic_signals` + `button_operated=yes` instead :wink:

**Comment by daniel-j-h** [comment]
Closing here - we can't do it _in the default planet-wide profiles_.
