### ISSUE TITLE
Running osrm-routed getting error

### ISSUE THREAD

**Issue by billystalnaker** [Project-OSRM/osrm-backend#3749]
Hi, I ran osrm-routed on a north-america file and received this output:
```[info] starting up engines, v5.5.0
[info] Threads: 8
[info] IP address: 0.0.0.0
[info] IP port: 80
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:80
[info] load names from: "/usr/src/osrm/osrm-backend/north-america-latest.osrm.names"
[info] set checksum: 823789383
[info] running and waiting for requests
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  remote_endpoint: Transport endpoint is not connected
```

I'm not sure how to handle this error. exact command: `osrm-routed -p 80 north-america-latest.osrm`

**Comment by oxidase** [comment]
@billystalnaker could you give more information about your system and osrm configuration. there were some related regressions in boost 1.54

**Comment by billystalnaker** [comment]
uname -a `4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Mem: 2G
 CPU's 1

As far as osrm configuration I'm not sure what you want. We are using the car.lua profile. Hope that helps

**Comment by oxidase** [comment]
for osrm configuration i mean output of cmake with an empty cache: `cd build && rm CMakeCache.txt && cmake ..`. The output will contain configuration flags and found library versions.

**Comment by billystalnaker** [comment]
Does that `cmake ..` rebuild the entire project? I don't want to go through that again...

**Comment by daniel-j-h** [comment]
No it will just generate the Makefile and related files again. You can also use https://hub.docker.com/r/osrm/osrm-backend/tags/ and try if you have the same issues with it.

@oxidase `osrm-routed` really is just a dev server for testing - nothing to prioritize there.

**Comment by oxidase** [comment]
@billystalnaker the most important is the boost version . if boost libraries  are installed as deb packages and used from the system than output of `dpkg -l | grep libboost-system` would be enough. But any other locally installed version can be used in the osrm configuration. If the boost version is 1.54 than it can be a problem in Boost.Asio and you can try to update boost version and rebuild osrm.
If the boost version >= 1.55 than problem can be on a client side, but i can not guess what could happen. The error just says that a client dropped connection for whatever reason. Probably tcpdump or wireshark can show what happened with the connection. 

@daniel-j-h basically thread loop must contain try/catch around `io_service::run`. But handling exception will not solve the original problem :disappointed:

**Comment by billystalnaker** [comment]
@daniel-j-h what do you mean by osrm-touted being a dev server? I was under the impression that this is the command to serve all requests to the  osrm package.. I will take a look into the boost library on Monday

**Comment by daniel-j-h** [comment]
No, `osrm-routed` is a ad hoc development HTTP server it doesn't even supper HTTP KeepAlive for example. We recommend https://github.com/Project-OSRM/node-osrm for production use.

**Comment by billystalnaker** [comment]
`ubuntu:  dpkg -l | grep libboost-system`
```ii  libboost-system-dev:amd64              1.58.0.1ubuntu1                   amd64        Operating system (e.g. diagnostics support) library (default version)
ii  libboost-system1.58-dev:amd64          1.58.0+dfsg-5ubuntu3.1            amd64        Operating system (e.g. diagnostics support) library
ii  libboost-system1.58.0:amd64            1.58.0+dfsg-5ubuntu3.1            amd64        Operating system (e.g. diagnostics support) library
```
In the quick start maybe it should say something like "If you're using this in production, then use node-osrm."? I was under the impression that we were good to go with just the `osrm-routed` command.

**Comment by billystalnaker** [comment]
Please bare with me on this. But I've installed `node-osrm` on my server. and used `make` to make the files.. What do I do now? I am supposed to be running a node server..?

**Comment by daniel-j-h** [comment]
You can do `npm install osrm` to get the latest release. Then check binaries and profiles in `node_modules/osrm` and prepare your data with them. Then see

https://github.com/Project-OSRM/node-osrm/blob/master/example/server.js
