### ISSUE TITLE
what():  Could not open /opt/osrm/OSRMfiles/france-latest.osrm.properties for writing. (at src/extractor/extractor.cpp:316)

### ISSUE THREAD

**Issue by Armays** [Project-OSRM/osrm-backend#3750]
Hello I have an error when extracting the France map. I created the OSRMfiles folder as sudo and gave it all the rights, and I ran the extract executable with sudo too, why do i have a permission error ?

terminate called after throwing an instance of 'osrm::util::exception'
  what():  Could not open /opt/osrm/OSRMfiles/france-latest.osrm.properties for writing. (at src/extractor/extractor.cpp:316)
Aborted (core dumped)

Sorry I think I found my issue, I forgot the EBS volume was 10 Go, and OSRM extracts the map in the same folder where the map is, which sounds logic.

**Comment by daniel-j-h** [comment]
> Sorry I think I found my issue, I forgot the EBS volume was 10 Go, and OSRM extracts the map in the same folder where the map is, which sounds logic.

Perfect. Closing here.
