### ISSUE TITLE
Add Feature:  Interface layer in Python 2.7

### ISSUE THREAD

**Issue by arita37** [Project-OSRM/osrm-backend#3756]
Just wondering if there is a way to use Boost or SWIG to get an interface in Python 2.7 ?
It would help usability.

There is also PyBInd Gen for easy intefacing.
https://github.com/pybind/pybind11

**Comment by daniel-j-h** [comment]
Hey - you can use the HTTP API via any language. If you really want to use `libosrm` without going through HTTP: I wrote some C bindings (last tested with 5.4 _should_ work with 5.6, too) and then built Python and Haskell FFI bindings on top of that.

https://github.com/daniel-j-h/libosrmc

It's by no means complete - I just played around a bit with FFI bindings.

Let me know if you have concrete use-cases for this and maybe if you want to work on it :)

**Comment by arita37** [comment]
Hello,
Thx for highlight.
It seems built over Linux  libosrm.so package, have this project  been compiled in Windows ?

Just want to integrate into Python framwork as  a package, although not specialist
(am working on optimizing technical system using gentic programming        , having a lack of time...).

**Comment by daniel-j-h** [comment]
Yes I tested it only on my Linux machine - for Windows you need at least some dllexport and dllimport hooks in the `osrmc.h` header and make the Python lib search for the so/dll in a cross-platform way, i.e.

    libosrm = ctypes.cdll.LoadLibrary(ctypes.util.find_library('osrm'))

As I said, it was a weekend of playing around with FFI bindings - not on my or our priority list at all. If you need this you have to invest some time yourself and help out.

**Comment by daniel-j-h** [comment]
Closing here as not actionable on our side.

**Comment by rburcham** [comment]
Hi Daniel.  I'm interested in revisiting this, and I'm willing to help in whatever way I can.

https://github.com/daniel-j-h/libosrmc/issues/4
