### ISSUE TITLE
troubles with segment_function and forward_rate

### ISSUE THREAD

**Issue by MichalPP** [Project-OSRM/osrm-backend#3757]
after upgrade to 5.6.0, I have troubles to make segment_function() working. previous tutorial https://github.com/Project-OSRM/osrm-backend/wiki/Integrating-third-party-raster-data is probably out of date, 

new profile at https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/rasterbotinterp.lua returns `Computing edge weights    ... terminate called after throwing an instance of 'sol::error'
  what():  lua: error: lua: error: bike-city.lua:167: sol: attempt to index (get) nil value "source" on userdata (bad (misspelled?) key name or does not exist)`
in the profile, it is referring to my segment.source.lon which is nil:
`function segment_function (segment)
  local out_of_bounds = false
  if
     segment.source.lon < LON_MIN or segment.source.lon > LON_MAX or
     segment.source.lat < LAT_MIN or segment.source.lat > LAT_MAX or
     segment.target.lon < LON_MIN or segment.target.lon > LON_MAX or
     segment.target.lat < LAT_MIN or segment.target.lat > LAT_MAX then
        out_of_bounds = true
  end
....
`

**Comment by MichalPP** [comment]
adding `api_version =  1` did the trick, thank you

**Comment by daniel-j-h** [comment]
Perfect - we should probably document that somewhere.

**Comment by MichalPP** [comment]
i've updated https://github.com/Project-OSRM/osrm-backend/wiki/Integrating-third-party-raster-data

**Comment by siljuovix** [comment]
> @MichalPP please check that `api_version = 1` is set at the begin of the profile. `segment.source` can be undefined if Lua [falls back to pre-issue 77 API](https://github.com/Project-OSRM/osrm-backend/blob/18a50d357f508026e88b41a396fd92c30340eb0b/src/extractor/scripting_environment_lua.cpp#L635-L636) and `segment` is the source coordinate argument. You can also print out values and check what is `segment` in `segment_function`:
> 
> ```
> print ('api_version ' .. api_version)
> function segment_function (segment)
>   print (segment)
>   print (segment.source)
> ... 
> 
> Wiki page is outdated after the weights/durations split.
> ```

Does the previous mean that api_version = 4 does not support segment_function ?

**Comment by wangyoucao577** [comment]
@siljuovix  Of course not. Actually there're several `segment_function` definitions, different `api_version` for different definitions. Refer to https://github.com/Project-OSRM/osrm-backend/blob/e86d93760f51304940d55d62c0d47f15094d6712/src/extractor/scripting_environment_lua.cpp#L1130-L1153
