### ISSUE TITLE
Replace BinaryHeap implementation

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3764]
Our current binary heap implementation is tuned towards not using a lot of memory but not being very efficient for each heap operation.

This is fine with CH since the search space is so small it hardly matters.This was already not the case for `CoreCH` anymore, but okay for our use-case.

With MLD we will increase the heap operations dramatically, so we will need to fine-tune this. A few ideas:

1. Eat the cost of saving 64bit per node per thread (potentially multiple GB) for the heaps to maintain NodeID -> HeapIndex lookup
2. Investigate 4-ary-Heap instead of binary heap
3. Investigate if the current heap architecture of saving all data makes sense, or if we should go for explicit parent and cost vectors.

**Comment by daniel-j-h** [comment]
Related: https://github.com/Project-OSRM/osrm-backend/issues/1765 want to close this, then?

**Comment by TheMarex** [comment]
@oxidase profiles our usage patterns and found excessive use of `std::unordered_map<>::find()` for the NodeID -> HeapIndex translation. There are a few ways to migrate this:

1. Use an array storage for the lookup (a lot of memory)
2. Use a hash-map that is not pointer based (but linear-probing) like https://github.com/sparsehash/sparsehash

**Comment by daniel-j-h** [comment]
For 2 - libosmium should already bundle various hash map impls.

**Comment by TheMarex** [comment]
Random datapoint: Just switching from `UnorderedMapStorage` to `ArrayStorage` gives a speedup of `2.02` on MLD queries.

**Comment by oxidase** [comment]
Fixed via #3931
