### ISSUE TITLE
make install not deploying all headers

### ISSUE THREAD

**Issue by mloskot** [Project-OSRM/osrm-backend#3776]
I'm building the current master on Linux, with success.

The `make install`, however, does not deploy all headers:

```
$ ls /usr/local/include/osrm/
bearing.hpp     engine_config.hpp   match_parameters.hpp    partition             storage_config.hpp    util
contractor      exception.hpp       nearest_parameters.hpp  route_parameters.hpp  table_parameters.hpp
coordinate.hpp  extractor           osrm_fwd.hpp            status.hpp            tile_parameters.hpp
engine          json_container.hpp  osrm.hpp                storage               trip_parameters.hpp

$ ls /usr/local/include/osrm/extractor
extractor_config.hpp  extractor.hpp  travel_mode.hpp

$ grep \#include /usr/local/include/osrm/extractor/extractor.hpp 
#include "extractor/edge_based_edge.hpp"
#include "extractor/edge_based_graph_factory.hpp"
#include "extractor/extractor_config.hpp"
#include "extractor/graph_compressor.hpp"
#include "util/guidance/bearing_class.hpp"
#include "util/guidance/entry_class.hpp"
#include "util/guidance/turn_lanes.hpp"
#include "util/typedefs.hpp"
```

As you can see, `/usr/local/include/osrm/extractor/extractor.hpp` includes at least two headers which are missing:
```
#include "extractor/edge_based_edge.hpp"
#include "extractor/edge_based_graph_factory.hpp"
```

There might be more.

**Comment by TheMarex** [comment]
Urg sorry the `libosrm_extractor.{a,so}` libraries were experimental, we currenly only use them to link against out internal binary tool `osrm-extract`. Maybe you can just use those?

If you need this as a library, the best course of action would be to migrate this behind a pimpl-facade like we do we `libosrm.{so,a}`. https://github.com/Project-OSRM/osrm-backend/blob/master/src/osrm/osrm.cpp

Basically:
- Add new files `src/osrm/extractor.cpp`, `include/osrm/extractor.hpp`
- `extractor.hpp` basicalliy just contains one function `osrm::extract(ExtractorConfig &config)`
- `extractor.cpp` implements that function by creating an `Extractor` object and calling `Extractor::run()`

You woul need to do the same with `osrm_contract.so` for the full toolchan.

**Comment by mloskot** [comment]
@TheMarex Gotcha. Thanks for the hints.

I'll leave it to you to decide if this issue should be closed.

**Comment by mloskot** [comment]
In #3787, I proposed implementation of the idea suggested by @TheMarex
