### ISSUE TITLE
Add the option to remove the trace split check in the match method

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#3778]
The match method has difficulties at tunnels processing, because there are no points during the tunnel. 
http://bl.ocks.org/d/35c59aaffa581712ad7e89db9b3c8872
This is happening because of the trace split check. To fix this at client side I need to add the interpolated point to have points often than 'median_sample_time * MAX_BROKEN_STATES'. Or filter the outer track to have 'median_sample_time' big enough. Both methods are tricky and seems like a black magic. I propose to add the special parameter to the request, that will say that I'm sure in my track and it doesn't require additional filtration or processing. So OSRM will not split my track against my will.

**Comment by daniel-j-h** [comment]
This landed with https://github.com/Project-OSRM/osrm-backend/pull/3815. Closing here.
