### ISSUE TITLE
ColumnIterator missing RandomAccessIterator ordering requirement

### ISSUE THREAD

**Issue by mloskot** [Project-OSRM/osrm-backend#3792]
`ColumnIterator` does not satisfy all of the random access iterator requirements.

Namely, ordering relation seems missing: it1 < it2

------

Originally posted as review/comment to the merged PR:
https://github.com/Project-OSRM/osrm-backend/pull/3738#discussion_r105129714

Being unsure how this GH review workflow work, I've opened this as new issue.

**Comment by oxidase** [comment]
@mloskot yeah, the simplest fix would be to use `boost::iterator_facade`.
Just curious, is it an automatic policy check or an observation?

**Comment by mloskot** [comment]
@oxidase During compilation w/ VS2015 and higher `_ITERATOR_DEBUG_LEVEL`, iterator range validation failed.
