### ISSUE TITLE
[document] build from source 5.6

### ISSUE THREAD

**Issue by kkdd** [Project-OSRM/osrm-backend#3794]
Hello,
Maintenance needed for building v.5.6.x from source.

Is it OK for osx building, for example, as follows?

```
$ brew install boost cmake libzip libstxxl libxml2 tbb lua
$ cd osrm-backend
$ mkdir -p build
$ cd build
$ cmake ..
$ make
```

**Comment by daniel-j-h** [comment]
What's your specific issue? You can simply use the Mason build as described here

https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM

otherwise you have to get all deps.

**Comment by kkdd** [comment]
Is luabind required to build OSRM 5.6 from source?

> OSRM v5.6.0
> We also dropped our dependency on Luabind and replaced it with the awesome sol2 that we can bundle as header-only library.
>  https://github.com/Project-OSRM/osrm-backend/releases


> OS X (ENABLE_MASON=OFF)
> Please install the homebrew package system. It will provide all necessary dependencies:
>  `brew install boost git cmake libzip libstxxl libxml2 lua51 luabind tbb ccache`
> To be able to compile tools:
>    `brew install GDAL`
> https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM

**Comment by daniel-j-h** [comment]
Until 5.6 yes. Starting from 5.6 no.

**Comment by daniel-j-h** [comment]
Closing this as not actionable on our side. Please use the Mason build, or get the dependencies yourself. Or even better, use our Docker images which work by default: https://hub.docker.com/r/osrm/.

**Comment by kkdd** [comment]
Can I remove a designation of luabind out of the following line in [wiki/Building-OSRM](https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM) if adequate?

> OS X (ENABLE_MASON=OFF)
> Please install the homebrew package system. It will provide all necessary dependencies:
> brew install boost git cmake libzip libstxxl libxml2 lua51 luabind tbb ccache

When removed, it would be changed as follows:
> brew install boost git cmake libzip libstxxl libxml2 lua tbb ccache

**Comment by daniel-j-h** [comment]
Yes :+1:
