### ISSUE TITLE
Osrm merges instructions incorrectly

### ISSUE THREAD

**Issue by Behizz** [Project-OSRM/osrm-backend#3801]
Hello guys,
I'm using the latest osrm (v.5.6.0) and I'm facing some new instruction issues that I didn't encounter in the earlier osrm 5 version. 
One of the issues is that osrm merges instructions in some streets entrances (first image) and rounabouts (second image). 
Osrm returns an instruction at the red point for the entire yellow line, although they are two different ways with different types and names and they should not merge.
![ramp2](https://cloud.githubusercontent.com/assets/5261029/23785681/26a2caa0-057e-11e7-8f0e-610bd170b23d.png)

In this route, osrm merges the roundabout entrance instruction with the roundabout exit instruction. Is it possible to split them?
![rotary2](https://cloud.githubusercontent.com/assets/5261029/23785684/2aae674e-057e-11e7-83c8-042f717a9028.png)

Thanks

**Comment by MoKob** [comment]
@Behizz could you specify exact locations of these instances?

For the roundabout: OSRM does only support a single roundabout instruction, right now. We are planning to change this behaviour some way down the line (https://github.com/Project-OSRM/osrm-backend/issues/3108).

For the second situation I am unable to give any insight, as long as I don't know the exact location.

**Comment by Behizz** [comment]
@MoKob 
Thank you for your answer. I'm using a custom osm for routing and the same route on the http://map.project-osrm.org/ doesn't have the above issue.

**Comment by MoKob** [comment]
In that case, I am closing this as not actionable on our side.

For your own research into the problem: There are a few situations how an instruction can end up not being shown. We suppress name changes, if they are only for short segments, to not clutter the instructions with new road informations (e.g. highways often change references).
If a turn is obvious next to other turns, we might not show it.
For the rest, you would have to look into collapsing of turns.

**Comment by Behizz** [comment]
@MoKob 
This is a sample (attached file) from my custom osm, where I have the merging issue.
When I request a route from [59.55188,36.284948] to [59.563011,36.299424], it just returns 1 instruction for the whole route (blvd -> tunnel -> blvd). I think it should return 1 instruction for entering the tunnel and one instruction for exiting the tunnel and entering the blvd. Can you tell me what is the problem?

Thanks

[sample.osm.zip](https://github.com/Project-OSRM/osrm-backend/files/835650/sample.osm.zip)

**Comment by MoKob** [comment]
@Behizz the image I see for your route is:

<img width="1256" alt="screen shot 2017-03-13 at 08 54 08" src="https://cloud.githubusercontent.com/assets/12932279/23845929/26414074-07cb-11e7-8afc-8f8505954f9b.png">

We see the roundabout + one new road. Please accept that we cannot spent a lot of time debugging custom data sources. If you need more input, you would have to provide a lot more information in terms of what turns you would expect where.
Note, however, that we suppress any information that we don't consider helpful for a driver on purpose.
E.g. if you are driving through a tunnel, we will not announce the tunnel as such. It is, after all, not anything you would tell to your driver if you would give instructions.

However, one thing you can try is to set a different value [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/guidance/collapsing_utility.hpp#L27) in case it is a series of new names.
If the road reference stays the same, or the name changes from `a` to `b` and back to `a`, we will not announce any new names.

If you want to see all instructions, you could disable [this line](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/api/route_api.hpp#L170) and [this line](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/api/route_api.hpp#L173) (make sure to do `leg.steps = guidance::postProcess(std::move(steps));` in the now new first line below) and see if you are happy with those instructions.
Be aware, though, that the instructions might get much more verbose.
