### ISSUE TITLE
postgis queries from profiles are serialized?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#3814]
We compute greenest routes for cyclists (preferring parks, along lakes, etc) by querying PostGIS from our LUA profile.

I've noticed that postgres is running only at 100% CPU, even though our server has 32 CPUs. Normally the LUA processing happen in parallel, and PostGIS itself fully supports parallel queries. So it seems either OSRM or the LUA postgres lib serialized queries.

W're running OSRM 5.2.6 and installed LUA postgres bindings with 'apt install lua-sql-postgres'. This seems to install the lib described at http://keplerproject.github.io/luasql/. LUA version is 5.1.5.

Any idea why this happens?

Maybe try LUA 5.2?

**Comment by daniel-j-h** [comment]
[Here](https://github.com/Project-OSRM/osrm-backend/blob/v5.2.8/src/extractor/extractor.cpp#L159-L203) is the code in question parsing osm objects in parallel _in v5.2.8_. [Here](https://github.com/Project-OSRM/osrm-backend/blob/c2727f202975414ffdaf9bfb8a4dd54615bcb9d0/src/extractor/scripting_environment_lua.cpp#L477-L525) is the same code in master.

A few things to look out for wrt. profiles:
- Lua53 has a garbage collection issue with larger datasets (think: planet). We recommend Lua51 or Lua52.
- We switched away from Luabind and to sol2 in v5.6. Profiles stay the same.

Neither of those should cause your issue, though.

Are you using a connection pool, or are you creating a connection every time a callback is created? Do you have locks on your tables? Are you reading only? Can you debug this by running dummy postgres queries such as `select 10 as speed;` and see if those happen in parallel.

**Comment by emiltin** [comment]
Thanks, didn't think about the connection. I'm creating it in the global part of the profile. I suppose that's called only once, not once per thread? That would result in all LUA threads sharing the same db connection.


```lua
-- connect to postgis
lua_sql = require "luasql.postgres"
sql_env = assert( lua_sql.postgres() )
sql_con = assert( sql_env:connect("osm", "osm", "") )
```

Unfortunately it seems luasql does not provide any kind of connection pooling. To do it myself, I think I would need to either tknow when a query is done and the connection can be reused, or find a way to create and assign a separate db connection to each LUA thread?

**Comment by emiltin** [comment]
Can I get the current thread number from LUA?

**Comment by emiltin** [comment]
looking at https://github.com/Project-OSRM/osrm-backend/blob/a572719484cd86dc066500af92ac3270460b0ae1/include/extractor/scripting_environment_lua.hpp, we're using thread-local storage for the script context. does that mean the global part of the profile is in fact called for each thread?

**Comment by daniel-j-h** [comment]
If you need the thread id you could probably bind [std::this_thread::get_id](http://en.cppreference.com/w/cpp/thread/get_id) to Lua in the scripting env.

Yes you should have as many scripting envs as you have threads. You can check this: insert some global print statements into the profiles.

**Comment by MichalPP** [comment]
hi, any successful howto on using multiple postgis connections? (I use it to penalize segment "close" to major/noisy roads)

**Comment by emiltin** [comment]
not yet. i got stalled on this, but it seemed like the the global part of the profile is in fact called once per thread. so not sure why postgis is using only one thread.

**Comment by MichalPP** [comment]
maybe it has something to do with lua not having "real" threading (whatever that means, but a lot of forums mention this), maybe having just one environment is a problem. but I did not find anybody else with such problem.

**Comment by daniel-j-h** [comment]
@emiltin any progress here?

I'm inclined to close this because at least from the osrm side it should be fine.

**Comment by emiltin** [comment]
ok let's close for now.
