### ISSUE TITLE
Match-Service returns `NoSegment` unexpectedly

### ISSUE THREAD

**Issue by skeleten** [Project-OSRM/osrm-backend#3817]
Hello,
I'm writing a custom application consuming libosrm (under windows) which queries the Match service.
Even though my data (https://gist.github.com/skeleten/8595f23492628b0c615e668c1c687938) is well within my extract (I'm using the geofabrik osm.pbf file of germany), I always get an error with 
`code: NoSegment` as well `message: NoSegment`.
However, I'd expect this data to return a valid result.

**Comment by TheMarex** [comment]
You swapped latitude and longitude.

However in general map matching uses a limited search radius for each input coordinate. All street segment candidates need to be inside `3*radius` to be considered.

Example:

http://router.project-osrm.org/match/v1/driving/8.6845216751099,49.861270904541;8.6846780776978,49.86088180542?radiuses=10;10

**Comment by skeleten** [comment]
I've already tried swapping longitude and latitude, though

**Comment by skeleten** [comment]
Hi,
I've tried swapping longitude/latitude before, and it (still) gives me the same results.
Also, note that I am *not* using the http API, but the libosrm C++ one, if that changes anything.

**Comment by danpat** [comment]
@skeleten The `NoSegment` error in the match service comes from here:

https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/plugins/match.cpp#L178-L188

What this means is that *none* of your coordinates snapped to any nearby road segments.

There are a few possible reasons that this could happen:

  1. You've got the lon/lat the wrong way around - this would put the coordinates a long way away from your roads
  2. You haven't loaded road network data for the area where you're trying to match
  3. You've got unlucky and your coordinates are *all* >15m away from the roads
  4. You've messed up your custom profile and you've actually got no roads loaded in your routing graph.

Can you post the output of your `osrm-extract` processing?

Also, given that you're using `libosrm`, a short snippet showing how you're constructing the OSRM and `MatchParameters` objects would be helpful to make sure you're not doing something wrong.

**Comment by skeleten** [comment]
Hi,
this is the output of `osrm-extract`: https://gist.github.com/skeleten/4b9707b212ff15f8aa8cfb4c68ac9641
this is how I construct my objects and use them: https://gist.github.com/skeleten/5e3650a9d46d67b7ed004324f81a2bd8

As stated above, I'm certain, that the data is correct. I also tried to swap longitude/latitude but to no avail.

Thanks for the help!

**Comment by danpat** [comment]
@skeleten Hmm, the edge count seems very low for all of Germany.  If I process just Hessen from
http://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf, I get:

```
# from hessen-latest.osm.pbf
[info] constructing r-tree of 1780581 edge elements build on-top of 1683834 coordinates
```

You've only got
```
# from your map.pbf
[info] constructing r-tree of 571191 edge elements build on-top of 530839 coordinates
```

I think either your `map.pbf` file is of the wrong area, or you've modified the `car.lua` profile to filter out many important roads.  If you haven't modified `car.lua`, then you've got the wrong map file.  I would recommend not calling the file `map.pbf` and keeping the original upstream name, so you know what geographic region it represents.

**Comment by skeleten** [comment]
Oh, that was just the region my route was actually located in (for speed reasons), so the edge count shouldn't be that high; sorry for the confusion

**Comment by danpat** [comment]
Please double/triple check that you've got the correct bounding box then - `NoSegment` would be the error you would get if your bounding box is in the wrong spot.

One way to visualize the routing graph that OSRM knows about is to use the debug viewer.

Grab a copy of:

  https://github.com/Project-OSRM/osrm-frontend

then start up `osrm-routed map.osrm`, then use osrm-frontend/debug to connect to the local vector tile server - routable roads will appear coloured according to their travel speeds.

(see the demo server debug viewer at http://map.project-osrm.org/debug/, you can run this locally to see what roads your OSRM datafiles know about).

**Comment by skeleten** [comment]
I was testing it with the whole data of germany as well, it still gave me `NoSegment`. I will check the frontend tommorow though, thanks for that hint!

**Comment by skeleten** [comment]
It seems the `osrm-frontend/debug/index.html` does not connect to my locally running `osrm-routed`. It colours roads worldwide and does so even without the `osrm-routed` service running :(

**Comment by daniel-j-h** [comment]
Did you adjust the path URL to your local endpoint?

See https://github.com/Project-OSRM/osrm-frontend#local-osrm-instance

**Comment by skeleten** [comment]
Yes I did -as stated above- and the data I'm feednig OSRM is definetly correct.

**Comment by daniel-j-h** [comment]
Ah sorry - have a look here:
https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/debug/index.html#L128

**Comment by skeleten** [comment]
Hi, I've definetly got the debug frontend to work with my local service (I got infos about the requests on my console). It matches the data I was expecting and needed to feed to OSRM

**Comment by danpat** [comment]
@skeleten ok - if you've got `osrm-routed` working, can you try running some `/match` queries with your coordinates over the HTTP interface, like @TheMarex suggested above?

If those work, but your C++ doesn't, then it probably points to a bug in your code.

**Comment by skeleten** [comment]
Hi, I've tried to query the API on the local routed service with the first 40 or so of my datapoints manually using Firefox. It indeed did return a Valid result.
I've already posted how I am using the API above, though.

**Comment by skeleten** [comment]
It seems there was a bug in my code that parsed the my points from a CSV file, which is unrelated to the libOsrm. Sorry fo the inconvenience
