### ISSUE TITLE
Segment speed file has a `weight` column instead of a `rate` column

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3823]
I noticed this while working on the update code: The current format we expect for speed files is currently:

```
from,to,speed,weight
```

However what we really want is `rate` (e.g. a speed-like) value instead of `weight` which is an absolute value like `duration`. In my mind this is an API bug: Somehow I did not catch this in the review process.

My proposal would be to change this to:

```
from,to,speed,rate
```

and backport a fix to 5.6.

@danpat @oxidase opinions?

**Comment by oxidase** [comment]
:+1: i would suggest also to make it a required field, related to #3805

**Comment by danpat** [comment]
👍 Agreed, this should be `rate`, using `weight` makes things awfully fragile when matching generated data against the map, `rate` is much more forgiving.

**Comment by TheMarex** [comment]
We forgot about this in the `5.6` series, we should fix it now.

**Comment by TheMarex** [comment]
This was fixed by #3926
