### ISSUE TITLE
Routing service is down at demo site

### ISSUE THREAD

**Issue by fernabel** [Project-OSRM/osrm-backend#3824]
I got the error
Routing error: Object {status: -1, message: "OSRM request timed out."}
here and example link:
http://router.project-osrm.org/route/v1/driving/-100.0634765625,37.23032838760387;-100.8984375,35.817813158696616?geometries=geojson

**Comment by daniel-j-h** [comment]
Yep seems like the demo server has some hiccups currently. We're looking into it.

**Comment by jonathanengelbert** [comment]
Thanks, Daniel, 
came here with the same issue.
 I am using it in a project and is not working for me locally either.

Thanks again.

**Comment by TheMarex** [comment]
... and we are back.
