### ISSUE TITLE
Roundtrip param not available?

### ISSUE THREAD

**Issue by pedro** [Project-OSRM/osrm-backend#3828]
Hi folks!

I can't seem to pass `roundtrip=false` to the Trip service.

The sample request for a trip with 3 stops in Berlin works normally:

```
curl 'http://router.project-osrm.org/trip/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219'
```

But when I append `?roundtrip=false` to it I get a 400 back:

```
{"message":"This request is not supported","code":"NotImplemented"}
```

I believe to be in the latest version:

```
$ osrm-routed --version
v5.7.0
```

Let me know if you have any pointers, and thanks for this amazing project <3

**Comment by danpat** [comment]
@pedro Try adding:

`?roundtrip=false&source=first&destination=last`

This is the only combination currently supported for `roundtrip=false`.

**Comment by pedro** [comment]
oh! works :+1: I thought it was supported for any/any

I take that's not implemented yet?

**Comment by danpat** [comment]
Heh, yes, that's what `NotImplemented` means :-)  It would probably be reasonable for us to automatically assume `source=first&destination=last` if you only supply `roundtrip=false`.  Feel free to open a ticket requesting that, or go ahead and add the feature, it should be a fairly straightforward change.

**Comment by Shkarface** [comment]
Is there any plans to support `source=first&destination=any&roundtrip=false` ? this is very useful when solving logistics problems
