### ISSUE TITLE
Bearing value > 180 degrees result to invalidOptions contradicts to what the document say!

### ISSUE THREAD

**Issue by hellracer** [Project-OSRM/osrm-backend#3837]
curl "http://router.project-osrm.org/nearest/v1/driving/120.9690734,14.6519971?number=3&bearings=0,200"

{"message":"","code":"InvalidOptions"}

**Comment by daniel-j-h** [comment]
value > 180 degree is fine, range > 180 degree is not

http://project-osrm.org/docs/v5.6.0/api/#requests

> bearing 	{value},{range} integer 0 .. 360, integer 0 .. 180
