### ISSUE TITLE
Quick-fix I/O error handling for OSRM 5.6

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3838]
OSRM 5.7 includes a [nice refactor](https://github.com/Project-OSRM/osrm-backend/pull/3496) of the I/O writing code, with much better error handling.

However, OSRM 5.6 doesn't have this yet, and well, sometimes the demoserver behaves badly if it runs out of disk space and `osrm-extract` doesn't notice.

We should add a quick-fix to the 5.6 branch where we simply do `if (!stream.good()) throw ...` after each file write.  This code would not be backported to `master`, it's just to quickly improve the behaviour of the stable release of OSRM while we wait for 5.7 to land (hopefully in a few weeks).

**Comment by TheMarex** [comment]
There is also `stream.exceptions ( ifstream::failbit | ifstream::badbit )`

**Comment by daniel-j-h** [comment]
Landed with https://github.com/Project-OSRM/osrm-backend/issues/3843.
