### ISSUE TITLE
Add options to configure partitions parameters to osrm-partition

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3847]
We need to expose options to configure partitions parameters for `osrm-partition`:

- Number of levels
- Number of maximum child cells per level

**Comment by oxidase** [comment]
Configuration of [bisectionToPartition](https://github.com/Project-OSRM/osrm-backend/blob/master/src/partition/partitioner.cpp#L164-L168) instead of hardcoded 32, 32 * 16, 32 * 16 * 32 and for different number of levels. Required bits size of  `PartitionID` must be checked

**Comment by oxidase** [comment]
@TheMarex i think all partitioning parameters are covered now. Can it be closed?
