### ISSUE TITLE
Adjust tests for node bindings for using coordinates in Monaco not Berlin

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3851]
Last task from https://github.com/Project-OSRM/osrm-backend/pull/3768 is still todo: Adjusting the node-osrm tests to use the monaco dataset.

This also means we need to run the node tests on Travis.

**Comment by daniel-j-h** [comment]
Thanks for ticketing, will take this one.

**Comment by TheMarex** [comment]
Was merged with #3877.
