### ISSUE TITLE
Incorrect travel speed on cycleway travelling against a oneway

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3853]
When using the bicycle profile, this way:

http://www.openstreetmap.org/way/19937708

is assigned a travel speed of 15km/h in both directions. The forward travel mode is `cycling` but the reverse mode is set to `push bike`.

The reverse travel speed should be set to the `push bike` speed of 6km/h.

Here's an example route that has been chosen based on the fast reverse travel speed on Rue La Roche:

![screen shot 2017-03-22 at 1 49 23 pm](https://cloud.githubusercontent.com/assets/1892250/24220187/a1a3f5ee-0f06-11e7-8b23-bfda2e9b39df.png)

But the JSON response indicates that it should be `push bike` along Rue La Roche:

![screen shot 2017-03-22 at 1 52 13 pm](https://cloud.githubusercontent.com/assets/1892250/24220272/f2ac2d4e-0f06-11e7-94cd-c3813dbdd99a.png)

So it looks like the profile is setting the mode correctly, but the speed value isn't being set to match :-(

This is causing calculated routes to have large sections of "push bike" because the travel speeds for pushing is not penalized (in the example route above, about 50% of the 2.4km route is pushing).

**Comment by emiltin** [comment]
i think this is because the way has both oneway=yes and cycle=lane. the code for pushing bike first assigns mode=push and speed=walk. afterwards the code checking for cycleway assigns speed=bike in both directions.

this is in some of the old code still not refactored. i can have a look at fixing it.

**Comment by danpat** [comment]
Confirmed that this change fixes this route:

![screen shot 2017-04-10 at 9 45 15 am](https://cloud.githubusercontent.com/assets/1892250/24872985/241f05be-1dd4-11e7-91d9-d3203f877828.png)
