### ISSUE TITLE
block not working

### ISSUE THREAD

**Issue by paolobenve** [Project-OSRM/osrm-backend#3856]
http://www.openstreetmap.org/directions?engine=osrm_car&route=44.42718%2C8.77864%3B44.42738%2C8.77915#map=19/44.42729/8.77897 :   the routing absolutely wants cross a block

**Comment by daniel-j-h** [comment]
OSRM should not route over `barrier=block`, here's a test for it:

https://github.com/Project-OSRM/osrm-backend/blob/379380abd8e8d884b707d8ab0287935b18d74d66/features/car/barrier.feature#L22

Looking at the history the barrier is only a couple of days old
 Looks like the demo server cycled on the 22nd: http://router.project-osrm.org/status

Let's wait a day or two to give the demo server a chance to cycle anew before investigating here.

**Comment by daniel-j-h** [comment]
I just looked into the demo server and found out why pre-processing got killed last week. I fixed it and re-triggered a pre-processing run. We should see the next dataset live by tomorrow.

**Comment by paolobenve** [comment]
http://www.openstreetmap.org/directions?engine=osrm_car&route=44.42719%2C8.77867%3B44.42751%2C8.77938#map=19/44.42736/8.77902
: status has been updated, but the block isnt' respected


don Paolo Benvenuto

2017-03-27 12:22 GMT+02:00 Daniel J. H. <notifications@github.com>:

**Comment by daniel-j-h** [comment]
Looks like your barrier is not part of the way at all

http://www.openstreetmap.org/node/4743817636

compare e.g. with

http://www.openstreetmap.org/node/493605843

Please fix your mapping, this is a data issue.

**Comment by paolobenve** [comment]
fixed

thank you


don Paolo Benvenuto

2017-03-29 9:43 GMT+02:00 Daniel J. H. <notifications@github.com>:

**Comment by daniel-j-h** [comment]
:+1:
