### ISSUE TITLE
Speed up/down gradient

### ISSUE THREAD

**Issue by OnlyMate** [Project-OSRM/osrm-backend#3861]
I've got a question about elevation data in **OSRM**.
Is there a way to speed up downhill and speed down uphill? 

And another question: 
For example I got a uphill way. Then I have a _positive_ gradient. If I go this way now back, I've got a _negative_ gradient. Is there a way that I can define in the _segment_function_ of the lua-profile the uphill and downhill weight/duration? 

<img width="350" alt="bildschirmfoto 2017-03-27 um 10 30 53" src="https://cloud.githubusercontent.com/assets/25883227/24347409/85d729aa-12d8-11e7-8312-360b4b7886b7.png">

I want that the weight/duration of the two sides on the way are independent. 
I'm working with the master.

My primary goal is, that I got different estimated travel time depends on elevation data.

**Comment by daniel-j-h** [comment]
Yes this should be possible using the raster data feature @lbud built into osrm. Have a look here:

- https://github.com/Project-OSRM/osrm-backend/wiki/Integrating-third-party-raster-data
- https://www.mapbox.com/blog/third-party-data-in-osrm/

You probably need to investigate a bit and play around with penalties.

- [Here](https://github.com/Project-OSRM/osrm-backend/blob/v5.6.4/include/extractor/extraction_segment.hpp) is the `ExtractionSegment`
- [Here](https://github.com/Project-OSRM/osrm-backend/blob/v5.6.4/src/extractor/scripting_environment_lua.cpp#L352-L362) we bind it to Lua
- [Here](https://github.com/Project-OSRM/osrm-backend/blob/v5.6.4/src/extractor/extraction_containers.cpp#L407-L409) we are calling the user's `segment_function` (if available) for all (!) edges
- [Here](https://github.com/Project-OSRM/osrm-backend/blob/v5.6.4/src/extractor/scripting_environment_lua.cpp#L622-L640) is the `ProcessSegment` function translation to Lua

Hope that helps as a start.

**Comment by OnlyMate** [comment]
@daniel-j-h Thank you! I'll give it a try. 👍

**Comment by OnlyMate** [comment]
Is there a way to get the elevation data from _source_function_ in the _way_function_?
```lua
function source_function ()  
  raster_source = sources:load(
    "/data/swiss.asc",
    5.9559,           -- lon_min
    10.492099999214,  -- lon_max
    45.818,           -- lat_min
    47.808400001144,  -- lat_max
    2388,             -- nrows
    5443              -- ncols
  )
end
```

In the segment function I can get easy the elevation data from this source. But what about the _way_function_ ?

**Comment by OnlyMate** [comment]
My problem is: If I change the duration/weight of a segment, both sides are changed. In the _way_function_ I can easily change the backward/forward speed, but I have no height data in this function. In _segment_function_ I've got the height data but cannot set the weight/duration independent.

**Comment by daniel-j-h** [comment]
Interesting, you are right. Here's the problem: for `a-b` we only split it into a forward `a->b` and a backward `b->a` if the edges are "compatible" (think same speed). Otherwise we only keep a single `a-b`:

https://github.com/Project-OSRM/osrm-backend/blob/827a595b6c603239468eea29286fe4225b29dd4c/src/extractor/extractor_callbacks.cpp#L325-L330

https://github.com/Project-OSRM/osrm-backend/blob/827a595b6c603239468eea29286fe4225b29dd4c/src/extractor/extractor_callbacks.cpp#L75-L83

This reduces storage requirements substantially but now when we call the segment function later on there is no forward and backward edge - only a single one.

I will ticket this separately - for now, what you could do as a workaround is make the edges "incompatible" to always force splitting. You can do this e.g. by setting `forward_speed = backward_speed * 0.01`. Urgh. Ugly, but should do for now.

Note: this will blow up your graph a bit. Seeing that you're using the Swiss extract you should be fine, though.

**Comment by OnlyMate** [comment]
I have exported a small **osm xml file**

```xml
<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' upload='true' generator='JOSM'>
  <bounds minlat='47.1476083' minlon='9.5186931' maxlat='47.1477287' maxlon='9.5191196' origin='CGImap 0.5.8 (16004 thorn-02.openstreetmap.org)' />
  <node id='3668934653' timestamp='2015-07-27T16:12:38Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1470504' lon='9.5216004' />
  <node id='3668934654' timestamp='2015-07-27T16:12:38Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1475196' lon='9.5208335' />
  <node id='3668934655' timestamp='2015-07-27T16:12:38Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1475881' lon='9.520664' />
  <node id='3668934656' timestamp='2015-07-27T16:12:38Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476023' lon='9.5204022' />
  <node id='3668934657' timestamp='2015-07-27T16:12:39Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476049' lon='9.5197557' />
  <node id='3668934658' timestamp='2015-07-27T16:12:39Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476919' lon='9.5190052' />
  <node id='3668934659' timestamp='2015-07-27T16:12:39Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476923' lon='9.5187653' />
  <node id='3668934660' timestamp='2015-07-27T16:12:39Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476363' lon='9.5185668' />
  <way id='28712192' timestamp='2015-07-27T16:12:48Z' uid='2110714' user='captain_slow' visible='true' version='4' changeset='32912926'>
    <nd ref='3668934653' />
    <nd ref='3668934654' />
    <nd ref='3668934655' />
    <nd ref='3668934656' />
    <nd ref='3668934657' />
    <nd ref='3668934658' />
    <nd ref='3668934659' />
    <nd ref='3668934660' />
    <tag k='highway' v='residential' />
    <tag k='motorcar' v='destination' />
    <tag k='motorcycle' v='destination' />
    <tag k='name' v='Brandiserweg' />
  </way>
</osm>
```

Then I did this: 
```lua
function segment_function (segment)
  local sourceData = sources:query(raster_source, segment.source.lon, segment.source.lat)
  local targetData = sources:query(raster_source, segment.target.lon, segment.target.lat)

  io.write("\n @source (lat:lon):" .. segment.source.lat .. ":" .. segment.source.lon ..
  " @target (lat:lon): " .. segment.target.lat .. ":" .. segment.target.lon .. "\n")
end
```

And this is the output: 
<img width="621" alt="bildschirmfoto 2017-03-28 um 15 19 20" src="https://cloud.githubusercontent.com/assets/25883227/24407035/f8de45ae-13c9-11e7-8ab6-d4d612f9a4e9.png">

I think the problem is, that _source_ and _target_ two times are the same? I was expecting that _source_ and _target_ should be switched.
