### ISSUE TITLE
Raster feature broken: segment_function requires split edges

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3869]
In https://github.com/Project-OSRM/osrm-backend/issues/3861 @OnlyMate tried to use our experimental raster / elevation feature and hit a problem with the segment function not properly getting called with the forward and backward edge.

The problem is non-split edges. For a-b we only split it into a forward a->b and a backward b->a if the edges are "compatible" (think same speed). Otherwise we only keep a single a-b:

https://github.com/Project-OSRM/osrm-backend/blob/827a595b6c603239468eea29286fe4225b29dd4c/src/extractor/extractor_callbacks.cpp#L325-L330

https://github.com/Project-OSRM/osrm-backend/blob/827a595b6c603239468eea29286fe4225b29dd4c/src/extractor/extractor_callbacks.cpp#L75-L83

This reduces storage requirements substantially but now when we call the segment function later on there is no forward and backward edge - only a single one.

The raster / elevation feature needs all non-split edges to work correctly for forward and backward edge.

Workaround: set `forward_speed = backward_speed * 1.01` to force splitting.

cc @lbud

**Comment by oxidase** [comment]
I think #3625 and  #3775 have the same origin

**Comment by MichalPP** [comment]
I looks like segment_function() calls each segment twice, but with the same source and target (judging by printing source and target lat/lon which are always twice the same, they should be reversed in the second call).

setting different speed/rate did not help in my case.

**Comment by OnlyMate** [comment]
@MichalPP : I wrote something in [https://github.com/Project-OSRM/osrm-backend/issues/3861#issuecomment-289767152](url). Is this the same behavior?

Setting different speed/rate did not helped in my case too. Or I don't know how to set it correctly. :)

**Comment by MichalPP** [comment]
@OnlyMate yes, it's the same behaviour

**Comment by oxidase** [comment]
@MichalPP looks like a bug as no flipping of segment end-points for reversed edges

**Comment by OnlyMate** [comment]
I've got a very ugly solution for me. I need this feature for _slope sensitive routing_. 
I'm using the **bicycle profile** from **OSRM** and added this: 

```lua
function source_function ()
  raster_source = sources:load(
    "/data/swiss.asc",
    5.9559,           -- lon_min
    10.492099999214,  -- lon_max
    45.818,           -- lat_min
    47.808400001144,  -- lat_max
    2388,             -- nrows
    5443              -- ncols
  )
end

local index = 0
-- https://www.mapbox.com/blog/third-party-data-in-osrm/
function segment_function (segment)
  local sourceData = nil
  local targetData = nil
  -- Very ugly, works for testing. :]
  if index % 2 == 0 then
    sourceData = sources:query(raster_source, segment.source.lon, segment.source.lat)
    targetData = sources:query(raster_source, segment.target.lon, segment.target.lat)
  else
    sourceData = sources:query(raster_source, segment.target.lon, segment.target.lat)
    targetData = sources:query(raster_source, segment.source.lon, segment.source.lat)
  end
  index = index + 1

  local elev_delta = targetData.datum - sourceData.datum
  local penalize = 0

  slope = math.abs(elev_delta / segment.distance)
  if elev_delta < 0 then
     slope = slope / 3
  end

  if slope < 0.01 then
     penalize = 0
  elseif slope < 0.05 then
     penalize = 0.25
  elseif slope < 0.1 then
     penalize = 0.65
  else
     penalize = 0.9
  end

  segment.weight = segment.weight * (1 - penalize)
  segment.duration = segment.duration * (1 - penalize)

end
```

The result looks like this:
<img width="348" alt="bildschirmfoto 2017-03-29 um 09 03 46" src="https://cloud.githubusercontent.com/assets/25883227/24442486/ab13ca34-145e-11e7-811a-a44ff14d0efe.png">

The duration and weight are now depending on the elevation data. This _workaround_ works for me pretty good. This way I can test some parameters for _slope sensitive routing_. :)

**Comment by oxidase** [comment]
@OnlyMate you workaround uses an incorrect duplication of backward edges that must be fixed as it potentially doubles number of segments in `all_edges_list` and also segments order is not stable.
PR #3873 must fix it, so your workaround after merging.

When PR will be merged into master you can do in `profiles/rasterbotinterp.lua`
```
  result.forward_speed = 15
  result.backward_speed = 15.01
```
so segments will be
```
 @source (lat:lon):47.14705:9.5216 @target (lat:lon): 47.14752:9.520834
 @source (lat:lon):47.14752:9.520834 @target (lat:lon): 47.14705:9.5216
 @source (lat:lon):47.14752:9.520834 @target (lat:lon): 47.147588:9.520664
 @source (lat:lon):47.147588:9.520664 @target (lat:lon): 47.14752:9.520834
 @source (lat:lon):47.147588:9.520664 @target (lat:lon): 47.147602:9.520402
 @source (lat:lon):47.147602:9.520402 @target (lat:lon): 47.147588:9.520664
 @source (lat:lon):47.147602:9.520402 @target (lat:lon): 47.147605:9.519756
 @source (lat:lon):47.147605:9.519756 @target (lat:lon): 47.147602:9.520402
 @source (lat:lon):47.147605:9.519756 @target (lat:lon): 47.147692:9.519005
 @source (lat:lon):47.147692:9.519005 @target (lat:lon): 47.147605:9.519756
 @source (lat:lon):47.147692:9.519005 @target (lat:lon): 47.147692:9.518765
 @source (lat:lon):47.147692:9.518765 @target (lat:lon): 47.147692:9.519005
 @source (lat:lon):47.147692:9.518765 @target (lat:lon): 47.147636:9.518567
 @source (lat:lon):47.147636:9.518567 @target (lat:lon): 47.147692:9.518765
```

imho, correct solution would be to add a flag `split_edges` to specify edges splitting in profiles explicitly
```
  result.forward_speed = 15
  result.backward_speed = 15
  result.split_edges = true
```

/cc @daniel-j-h
