### ISSUE TITLE
Expand build matrix for more node versions

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3878]
Currently we only build the node binaries for the `Release` target and node `4`. We should expand the build matrix to capture the same configurations as `node-osrm`:

- Linux Node 4 `Release`
- Linux Node 6 `Release`
- Linux Node 4 `Debug`
- Linux Node 6 `Debug`
- OSX Node 4 `Release`
- OSX Node 6 `Release`
- OSX Node 4 `Debug`
- OSX Node 6 `Debug`

This is a lot of build jobs to add to our already huge matrix, so we should find a way to only enable them conditionally. Options:

- Add each configuration and `exit 0` for non-releases
- Try to get Travis to support `branches` in `matrix.include`: https://github.com/travis-ci/travis-ci/issues/2778
- Use Travis API to run jobs via CLI only when we need to.

**Comment by daniel-j-h** [comment]
Targeting 5.7 here - we need proper releases at least for the LTS node versions.

Especially given that Node v4 goes from active LTS into maintenance mode starting April.

https://github.com/nodejs/LTS#lts-schedule

**Comment by daniel-j-h** [comment]
This landed with https://github.com/Project-OSRM/osrm-backend/pull/3915.
