### ISSUE TITLE
Expose libosrm fully in NodeJs bindings

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3882]
We need to make a pass over libosrm and make sure to expose all options to our node bindings. We're missing a few for sure (e.g. we were missing the generate hints parameter until some weeks ago).

Check `include/osrm` and transitive headers, and sync with `src/nodejs`.

**Comment by danpat** [comment]
@daniel-j-h Any ideas for automating this test?

Anything that we have to manually keep in sync is always going to be a source of errors.  I don't know of any existing tools, but I could definitely imagine:

  1.  Enforce strict code documentation standards in libosrm headers
  2.  Enforce same standards on node bindings
  3.  Write small tool to extract function signatures and compare.

**Comment by daniel-j-h** [comment]
There are some problems with automatic checks. Our public headers are often only shims including our private (!) headers (needs to be fixed in v6 https://github.com/Project-OSRM/osrm-backend/issues/2031). In order to keep member attributes in sync. we can put static asserts for the objects we wrap into the node bindings, think:

    static_assert(sizeof(osrm::Engine) == 2, "I think I am out of sync with libosrm")

But we won't be able to catch e.g. changes in libosrm's constructors or functions this way.

**Comment by daniel-j-h** [comment]
Here's another idea to keep at least the members in sync.

We could write a generic v8 objects to C++ objects translator. Think: `v8::Number` -> `int32_t` (and other primitives), and also collections such as `v8::Array<v8::Number>` -> `vector<int32_t>`. We could then adapt our types so that we can walk over its members and call the translator for every member attribute.

I did this once to automatically generate argument parsers:

```c++
namespace Http {
  struct Options {
    std::string host;
    std::int32_t port;
  };

  using boost::fusion::operator<<;  // makes type cout'able
}

// tells fusion about members, so we can walk members at compile time
BOOST_FUSION_ADAPT_STRUCT(Http::Options, host, port)
```

We can then automatically generate a command line option parser at compile-time.

Usage for this example would be

```c++
auto opts = get<Options>(argc, argv, "Options for the Http connection");
```

https://github.com/daniel-j-h/argparse-generic

We could do the same for the v8 -> C++ translation, automatically checking for the right types, generating error messages etc. - again, this works for arguments, but not for functions.
