### ISSUE TITLE
How to build the examples?

### ISSUE THREAD

**Issue by haspok** [Project-OSRM/osrm-backend#3885]
CMake newbie here.

I can build OSRM fine on Ubuntu following the wiki instructions.

However, I don't know how to build the example application. If I run `cmake` from the `example` directory, I get "In-source builds are not allowed.(...)"

If I try to run `cmake ../example` from the ../build directory, I get 

```
CMake Error: The source "/home/haspok/src/osrm-backend/example/CMakeLists.txt" does not match the source "/home/haspok/src/osrm-backend/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
```

If I try to run `cmake` from anywhere else I get

```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibOSRM (missing: LibOSRM_LIBRARY_DIRS LibOSRM_CXXFLAGS
  LibOSRM_LIBRARIES LibOSRM_DEPENDENT_LIBRARIES LibOSRM_INCLUDE_DIR)
```

There are no instructions for this on the Wiki.

**Comment by oxidase** [comment]
@haspok :wave: you need to install OSRM library locally with `cd  build && sudo make install`, so you can use the installed library in the example as
```
mkdir example/build
cmake .. -DCMAKE_BUILD_TYPE=Debug
make
```

The CI steps for the example building are [here](https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L183-L192)

**Comment by haspok** [comment]
Thanks @oxidase , problem solved :)
