### ISSUE TITLE
How much memory needed for North American route 

### ISSUE THREAD

**Issue by tman77** [Project-OSRM/osrm-backend#3886]
I've been trying to setup osrm, via

osrm-extract north-america-latest.osm.pbf -p osrm-backend/profiles/car.lua -t 10
osrm-contract north-america-latest.osrm

Everytime I've run the osrm-extract command, I've ended up getting a bad_alloc, see below.

[info] Graph loaded ok and has 282126544 edges
[error] [exception] std::bad_alloc
[error] Please provide more memory or consider using a larger swapfile

I've tried on a machine with 32 GB of ram.  I saw that lua5.2 has some memory issues, so am going to retry with lua5.3, as well as with a large swapfile, but curious if there is a minimum amount of memory needed for what I'm trying to do...

**Comment by daniel-j-h** [comment]
Lua53 has the issues, Lua51 and Lua52 are fine.

Can you provide a swap file as documented in https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM if you don't have more memory available. Also try latest master, just to be sure.

**Comment by tman77** [comment]
Ah thank you for that link, I wasn't able to find that.  Ok, so 5.3 has the issue, I saw an earlier post saying 5.2 does as well.  

I'm currenlty running on a box with 32 GB or memory and a 32 GB swap file with lua 5.3, guess I'll see if it succeeds...

**Comment by daniel-j-h** [comment]
Closing this as not actionable on our side.

If you have some numbers to share feel free to add them to the Wiki.
