### ISSUE TITLE
Update Profile from OSRM Version 4.5 to OSRM Version 5.6

### ISSUE THREAD

**Issue by OnlyMate** [Project-OSRM/osrm-backend#3894]
I'm trying to update our Lua Profile from OSRM Version 4.5 to OSRM Version 5.6.

I'm struggling at the "Handlers". Are the handlers necessary? 
If I add this code to my way_function it's working like charm:
```lua
  local handlers = Sequence {
    -- set the default mode for this profile. if can be changed later
    -- in case it turns we're e.g. on a ferry
    'handle_default_mode',

    -- check various tags that could indicate that the way is not
    -- routable. this includes things like status=impassable,
    -- toll=yes and oneway=reversible
    'handle_blocked_ways',
  }

  if Handlers.run(handlers,way,result,data,profile) == false then
    return
  end
```

My problem now the following code:
```lua
  local handlers = Sequence {
    -- compute speed taking into account way type, maxspeed tags, etc.
    'handle_surface',

    -- handle turn lanes and road classification, used for guidance
    'handle_classification',

    -- handle various other flags
    'handle_roundabouts',
    --'handle_startpoint',

    -- set name, ref and pronunciation
    'handle_names'
  }

  Handlers.run(handlers,way,result,data,profile)
```

This code expects that I'm setting e.g. _surface_speed_ in the local _profile_ variable. 
But we're using something like a _surface_factor_ and used it like this: 

```lua
 -- Code from Version 4.5!
 -- surface
 if surface then
      surface_factor_value = surface_factor[surface]
      if surface_factor_value and surface_factor_value < factor_value then
	      factor_value = surface_factor_value
      end
 end

result.forward_speed = result.forward_speed * factor_value
result.backward_speed = result.backward_speed * factor_value
```

Is there a way to add the factors to the handlers? 
Or to reword: Are there any short ways to update the profiles?

**Comment by emiltin** [comment]
the code in Handlers was factored out from the various profiles. ie. it's common code that most profiles need. but it's up to you which ones you use.

there's no easy way to customize each handler, apart from changing the parameters in the profile table. if you need more than that you can write your own function for processing eg. surfaces.

note that you can call Handlers.run() several times, placing your own code in between.

regarding surface_factor, my experience is that you get better results with speeds, especially when other factors affect the speed too.

i'm looking into changing the list of handlers from string to function references, so it's possible to simply insert your own functions in the list of handlers to run.

**Comment by OnlyMate** [comment]
Is it necessary to set a "default" **result.forward_mode/result.backward_mode**? 
If I add the tagged lines to the begin of the _way_function_ all works good. Without the two lines the result isn't the expected result.
```lua
result.backward_mode = mode.cycling -- this
result.forward_mode = mode.cycling -- and this
-- [...]
  if 	(not highway or highway == '') and
  (not use_public_transport or not route or route == '') and
  (not use_public_transport or not railway or railway=='') and
  (not amenity or amenity=='') and
  (not man_made or man_made=='') and
  (not public_transport or public_transport=='') and
  (not bridge or bridge=='')
  then
    return
  end
-- [...]

```

**Comment by daniel-j-h** [comment]
Default forward and backward modes are "inaccessible" if you do not set them.

- [Here](https://github.com/Project-OSRM/osrm-backend/blob/2cd4ba9a0abb677c68feee3f55e2399f5eefe9e0/include/extractor/extraction_way.hpp#L56-L57) are the defaults in the `ExtractionWay` (the type we bind to the Lua way `result`)
- [Here](https://github.com/Project-OSRM/osrm-backend/blob/2cd4ba9a0abb677c68feee3f55e2399f5eefe9e0/src/extractor/extractor_callbacks.cpp#L77-L86) we handle the Lua way and dispatch on the travel modes

**Comment by OnlyMate** [comment]
@daniel-j-h Thank you!

**Comment by lisboeta** [comment]
"osrm-backend/include/engine/api/match_parameters_tidy.hpp"

Hello daniel-j-h, how are you?
I find a bug this file on line 88, the variable 'last_good' is not used. When install that, show me this error. 

How to fix?

Cumps.

**Comment by danpat** [comment]
@lisboeta Is your question related to this ticket?  If not, please open a new ticket with more details.

**Comment by lisboeta** [comment]
all right, sorry, ;) I created now. thnks

**Comment by OnlyMate** [comment]
I think we can close this. :)
