### ISSUE TITLE
Use 20bit for segment weights and durations

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3896]
Currently we use 32bit for every edge segment (that means pair of OSM node ids, that would represent a street segment) to store the weight an duration. That is very generous considering these segments are usually only a few hundred meters long at the most.

In a 16bit unsigned integer we can store 65535 deci-seconds, or 1.8 hours. That should be plenty of time for such short segments. Of course we should measure this, but I fill this is a safe limit for any reasonable setting.

**Comment by kostadin24** [comment]
18 hours are plenty of time if you travel with car, but what about route with walk? If we have 5kph walk speed 18 hours make 90km distance. It is not too big distance if we have contracted ways.

**Comment by TheMarex** [comment]
This would only be for the very short segments that we need to compute start / target offsets from (like starting in the middle of the street instead of one of the endpoints). There is no contraction happening on those.

**Comment by TheMarex** [comment]
Of course this would have been too simple. Let me introduce you to the reason why we can't have nice things: https://www.openstreetmap.org/way/441977614#map=11/47.4648/9.3998 13km of uninterrupted ferry travel.

We might be able to use a var-int or packed storage instead.

**Comment by TheMarex** [comment]
Evaluated our options here for saving file sizes. Packing everything into 20bits is the least-effort solution and will yield 40% size reduction. Encoding speeds in km/h would allow us to get a 75% size reduction, but introduces some problems with units (km/h uses most of the 8bits, while m/s would only use 6bits which reduces precision).

# Use 20bits fixed size

- 20/32 =~ 40% reduction in size
- Needs fixes for PackedVector for random access
- Implementation overhead: low

# Encode as speed + distance

- don't encode duration as speed in km/h 0..255
- encoding as m/s would need a range of 180/3.6 ~= 50
- problem with weight: rate is encoded in something like m/s not km/h (does not fit in 0..255 range)
- Potentially 1 byte per value (4 bytes for forward/backward speed/rate)
- 75% reduction in size (if we don't encode the distance explicitly)
- Updates faster (no conversion speed -> duration)
- More overhead in query (PhantomNode generation needs to compute distance from coordinates, multiply with speed to compute the offset)

# Varint encoding

- We can't have a shared index for each range -> 4 bytes per GeometryID per foward/backward weight/duration for the index
- Varint encodings use at least 8bits per entry, but we would only see gains over speed-based encoding if we can go below 8 bits per entry
- Needs separate update data structure and query data structure (because of varint reencoding)

# Dictionary encoding

- Frequenly the forward/backward duration/weight is the same
- 4x 4 Bytes IntegerRangeID per GeometryID
- Reduces the number of 32bit entries by X%
- Needs separate update data structure and query data structure (because of reencoding)

# Measurements on Bayern

- Segments: `6854816`
- Geometries: `1413442`

Bits needed for encoding segment speeds in km/h:

![speed_distance_bits](https://cloud.githubusercontent.com/assets/606968/25185508/0e5b49be-250d-11e7-9f4b-d3b6f6bd5788.png)

Bits needed for encoding segment durations/weights:

![weight_duration_bits](https://cloud.githubusercontent.com/assets/606968/25185511/10e3ae42-250d-11e7-8d78-27f40f67d208.png)

**Comment by TheMarex** [comment]
This was merged with using 22bit,
