### ISSUE TITLE
Performance Numbers, switch to node-osrm?

### ISSUE THREAD

**Issue by tman77** [Project-OSRM/osrm-backend#3898]
This is more of a discussion than an issue.  I recently built osrm-backend on an M4.xlarge AWS instance (8 cores, 32 GB ram), and after tweaking some tcp settings, I was able to load test it using seige.  I was able to get 3,300 to 3,400 transactions per second using osrm-routed against the North-American Car map.

I have two questions:

1.  Is this inline with what others are seeing? 
2. I see where some are recommending that for production environment, one should run node-osrm.  Has anyone tested to see how much, if any, performance improvement running with node-osrm provides over using osrm-routed?

Thank you,

**Comment by danpat** [comment]
@tman77 your numbers sound in the right ballpark.  Most requests should be served in around 5ms, the exact performance will depend on the exact routes you selected (long routes take longer to calculate and send a response over the network).

The recommendation to use `node-osrm` isn't driven by performance, it's driven by robustness.  `osrm-routed`, while it works (and is what the OSRM demo server uses), is not, by any stretch of the imagination, battle-hardened code.  It's never been thoroughly security analyzed, and we suspect it wouldn't take much effort to uncover a bunch of compromise-capable bugs.

The node bindings will be, in absolute terms, a bit slower.  There is overhead involved at the NodeJS binding layer (moving objects from C++ land to Node land takes time).

If you're running a private service that's protected, `osrm-routed` is fine to use - but if you're at all worried about attack vectors, I'd think twice.

**Comment by tman77** [comment]
Thank you for the response and guidance, that makes sense.

**Comment by danpat** [comment]
Nothing actionable here, closing.

**Comment by daniel-j-h** [comment]
A node-osrm based server may also support Http KeepAlive, which osrm-routed does not.
