### ISSUE TITLE
[HELP] | ERROR IN- "osrm-backend/include/engine/api/match_parameters_tidy.hpp"

### ISSUE THREAD

**Issue by lisboeta** [Project-OSRM/osrm-backend#3900]
"osrm-backend/include/engine/api/match_parameters_tidy.hpp"

Hello @daniel-j-h , how are you?
I need your help please,
I find a bug this file on line 88, the variable 'last_good' is not used. When install that, show me this error.

How to fix?

Cumps.

**Comment by danpat** [comment]
@lisboeta Please supply more details.  Please include the output of your `cmake` command, and a copy of the actual error you're receiving.

Note that you can put code/plain text in backticks (``) so that you can show a nice fixed-width font to make things easy to read: `like this`.

**Comment by lisboeta** [comment]
Hello @danpat, when I run this 'make install' command, it reaches 75% shows me this error:
`On file included from /home/<usersname>/osrm/osrm-backend/include/engine/api/match_api.hpp:5:0, from /home/<usersname>/osrm/osrm-backend/src/engine/plugin/match.cpp:4: /home/<usersname>/osrm/osrm-backend/include/engine/api/match_parameters_tidy.hpp: In function 'osrm::engine::api::tidy::Result osrm::engine::api::tidy::tidy(const osrm::engine::api::MatchParameters&, osrm::engine::api::tidy::Thresholds)':/home/<usersname>/osrm/osrm-backend/include/engine/api/match_parameters_tidy.hpp:88:17: warning: variable 'last_good' set but not used [-Wunused-but-set-variable]
std::size_t last_good = 0`

**Comment by daniel-j-h** [comment]
> warning: variable 'last_good' set but not used [-Wunused-but-set-variable]

It's a warning only. You can ignore it. Compilation / linking does not stop because of this warning.

Closing here.

**Comment by lisboeta** [comment]
But after the installation, I run this command
`Ln -s osrm-backend / profiles / car.lua profile.lua`
`Ln -s osrm-backend / profiles / lib`

And then I execute this `osrm-extract map.osm` command, it shows the error" profile.lua not found "

**Comment by daniel-j-h** [comment]
That's a completely different issue. Just follow the steps outlined here:

https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM
