### ISSUE TITLE
Build fails with linking error to `stxxl`

### ISSUE THREAD

**Issue by s1992vivek** [Project-OSRM/osrm-backend#3901]
I was trying to install OSRM on Ubuntu 16.04 following the [instructions](https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM). After configuring with default options, when I build the project using `cmake --build .`, I get the following error:

    $ cmake --build .
    # trimmed 
    [ 59%] Built target osrm_extract
    [ 59%] Linking CXX executable osrm-extract
    libosrm_extract.a(extractor.cpp.o):extractor.cpp:function void stxxl::block_manager::delete_block<2097152u>(stxxl::BID<2097152u> const&): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
    libosrm_extract.a(extractor_callbacks.cpp.o):extractor_callbacks.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::dump() const'
    libosrm_extract.a(extractor_callbacks.cpp.o):extractor_callbacks.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
    libosrm_extract.a(extractor_callbacks.cpp.o):extractor_callbacks.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
    libosrm_extract.a(extraction_containers.cpp.o):extraction_containers.cpp:function void stxxl::block_manager::delete_block<2097152u>(stxxl::BID<2097152u> const&) [clone .part.432]: error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
    libosrm_extract.a(extraction_containers.cpp.o):extraction_containers.cpp:function stxxl::singleton<stxxl::config, true>::create_instance(): error: undefined reference to 'stxxl::config::init(char const*)'
    libosrm_extract.a(extraction_containers.cpp.o):extraction_containers.cpp:function stxxl::singleton<stxxl::config, true>::create_instance(): error: undefined reference to 'stxxl::config::init(char const*)'
    collect2: error: ld returned 1 exit status
    CMakeFiles/osrm-extract.dir/build.make:126: recipe for target 'osrm-extract' failed
    make[2]: *** [osrm-extract] Error 1
    CMakeFiles/Makefile2:249: recipe for target 'CMakeFiles/osrm-extract.dir/all' failed
    make[1]: *** [CMakeFiles/osrm-extract.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2

The above cmake output is when I ran the build command for the second time.
Does someone have a solution to this problem?

I've STXXL 1.4.1 installed from the Ubuntu repositories, and I'm trying to build the head from master (e568b600f0c4ad5a2cd9b8f97868ef9b1b7fc6b2).

**Comment by daniel-j-h** [comment]
Can not reproduce in a fresh Ubuntu 16.04 Docker container, building master (8cd40b9e) with the instructions from [here](https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM) and then dependencies from [here](https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu).

    docker run -it ubuntu:16.04 /bin/bash

**Comment by s1992vivek** [comment]
@daniel-j-h Thanks a lot for taking a look.  I'll double check my build environment and report back with more information.

**Comment by s1992vivek** [comment]
I think there was a problem with my installation of stxxl. After struggling for quite a while, I reinstalled everything from scratch, which fixed the issue.  Thank you for your time.

**Comment by daniel-j-h** [comment]
We also package up both the backend and the frontend in ready-to-use Docker images:

- https://hub.docker.com/r/osrm/osrm-backend/
- https://hub.docker.com/r/osrm/osrm-frontend/

Should make it easier installing a local routing engine.
