### ISSUE TITLE
Use `jemalloc` as part of published Docker image

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3906]
`osrm-extract` can benefit greatly from the use of `jemalloc`.  We should ensure that gets used in our base Docker image.

**Comment by daniel-j-h** [comment]
Alpine's take on replacing the allocator (in the context of its C stdlib musl)

> > The fourth issue is much bigger: replacing malloc is UB and does not
> > work, especially not on musl. :-)

http://www.openwall.com/lists/musl/2014/08/08/11

**Comment by daniel-j-h** [comment]
Yup,

    export LD_PRELOAD /usr/lib/libjemalloc.so.2

results in `Bus error (core dumped)`.

**Comment by freenerd** [comment]
Maybe we should switch to Ubuntu then? It adds a [hefty 238 MB though](https://github.com/phusion/baseimage-docker).

**Comment by daniel-j-h** [comment]
Did we ever benchmark the default musl C stdlib allocator? We found switching from Ubuntu's GNU C stdlib allocator to `jemalloc` beneficial. But we have no data for musl's allocator yet.

**Comment by danpat** [comment]
@daniel-j-h the only benchmarks I have were in https://github.com/Project-OSRM/osrm-backend-docker/issues/1 where I noted that the docker images seemed slow.  It could be the memory allocator, I never really dived in.

We should try the Ubuntu images.  If necessary, we can use https://github.com/goldmann/docker-squash and some additional image cleanup to reduce the image size after it's built.

**Comment by daniel-j-h** [comment]
Sure - switching the base image should not be the problem. All I'm saying is if we optimize for performance we should benchmark the Alpine image first before jumping to conclusions.

**Comment by daniel-j-h** [comment]
Stale. Does not work with Alpine-based images and maybe isn't even needed given that musl uses a completely different memory allocator than glibc.

cc @freenerd could be of interest if you see performance problems during your ecs quest
