### ISSUE TITLE
Reactor heaps interface

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#3908]
PR  #3895 introduces a workaround for MLD heaps by adding ["core" heaps](https://github.com/Project-OSRM/osrm-backend/blob/59350f0b16288b6ebad6f7bf4cc5315e53ddf3bb/include/engine/search_engine_data.hpp#L78-L80) that are only needed in the shortest plugin for [`Clear` calls](https://github.com/Project-OSRM/osrm-backend/blob/59350f0b16288b6ebad6f7bf4cc5315e53ddf3bb/src/engine/routing_algorithms/shortest_path.cpp#L147-L148)

The implementation of algorithm-aware heaps should not be exposed and used in plugins code with the following steps:
* heaps implementation details must be hidden in `routing_algorithms::{ch,corech,mld}` namespaces, ATM input phantom nodes are placed into heaps and passed into `search` functions.  `search` functions must get phantom nodes as input and a reference to heaps structure. 
* `search` functions should internally clear heaps and place phantom nodes into heaps
* cleanup of algorithm-dependent heaps
* remove static heaps members and make heaps structure members life-time in scope of engines life-time

**Comment by daniel-j-h** [comment]
This landed with https://github.com/Project-OSRM/osrm-backend/pull/3931.
