### ISSUE TITLE
access=customers should be treated as private

### ISSUE THREAD

**Issue by MichalPP** [Project-OSRM/osrm-backend#3913]
restricting access to customers should be treated as either delivery (very significant turn penalty) or private (disallow traffic). 

after I've allowed a lot of barriers ( #3890 ) in the foot profile, many shortcuts through shops became routable, even though they were correctly marked as `access=customers`. 

how is `access=customers` treated in your regions?

**Comment by daniel-j-h** [comment]
We put a high turn penalty on turns onto such restricted ways. Check out
- [Making Travel Time and Edge Weights Independent](https://www.openstreetmap.org/user/happygo/diary/40564) (en)
- [Trennung von Geschwindigkeiten und Kantengewichten](https://www.openstreetmap.org/user/happygo/diary/40565) (de)
- https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L84-L89
- https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L419-L421
- and if you have ideas for more tags https://github.com/Project-OSRM/osrm-backend/issues/3745

**Comment by daniel-j-h** [comment]
Noting here: this is active in the car profile only at the moment. I see no reason we shouldn't do this in the bike and walk profile - @karenzshea any insights here? Was this intentionally left out of the bike and walk profile?

cc @emiltin

**Comment by emiltin** [comment]
seems like a good idea to avoid these type of ways for foot and bike as well
