### ISSUE TITLE
Lua Profile - Property "weight_precision" strange behavior 

### ISSUE THREAD

**Issue by OnlyMate** [Project-OSRM/osrm-backend#3917]
Hello! 

I got a strange behavior if I set the property _weight_precision_. 
Here my scenario: 

My _way_function_ contains this:
```lua
  result.weight = 1

  if highway then
    result.forward_speed = 10.5
    result.backward_speed = 10.5
  end

  if bicycle then
    result.forward_speed = 10.5
    result.backward_speed = 10.5
  end
```
I'm just setting the **weight** of each result to 1. 

### Properties
```lua
properties.weight_name = "routability"
properties.weight_precision = 1
```
### Result
<img width="350" alt="bildschirmfoto 2017-04-07 um 10 09 58" src="https://cloud.githubusercontent.com/assets/25883227/24791676/5937570c-1b7b-11e7-85fe-de0696fea58e.png">

### Properties
```lua
properties.weight_name = "routability"
properties.weight_precision = 2 -- I just changed the precision to '2'
```
### Result
<img width="350" alt="bildschirmfoto 2017-04-07 um 10 19 29" src="https://cloud.githubusercontent.com/assets/25883227/24791772/be4df33a-1b7b-11e7-8879-2901a6d3537b.png">

I just changed the precision, nothing else and the calculated route is another one. Is this working as it should?

**Comment by oxidase** [comment]
@OnlyMate it can be a result of round off errors for paths with close weights. The upper bound for difference between will paths weights is 0.1 * number of segments in the path. Pls, could you post results for both queries as
```
curl -s `query` | | jq '.routes[] | [.weight, .duration|tostring] | join(" ")'
```

**Comment by OnlyMate** [comment]
**Scenario 1** 
"1.7 104.5"

**Scenario 2**
"1.63 91.1"

**Comment by oxidase** [comment]
0.07 difference looks reasonable to prefer the second path with the weight precision 2, but the first path can be shorter if with the weight precision is 1. The accumulated roundoff error could be 0.1 or 0.2 so the weight of the second path can be 1.7 and 1.8 for the weight precision 1 and it will not be shorter than the first one.

It is hard to say what is the weight of the first path with higher precision as OSRM returns only the shortest path, but you can set the weight precision to 3 and could try to find a separation point.

**Comment by OnlyMate** [comment]
Okay. Thanks for your replay! I was just wondering. :)
