### ISSUE TITLE
Fingerprint magic number or checksum is invalid

### ISSUE THREAD

**Issue by davidmir** [Project-OSRM/osrm-backend#3918]
Hi,

When I run osrm-route I am getting the following error:
Fingerprint magic number or checksum is invalid in /mnt/data/osrm/planet-latest.osrm.nodes

What causes this error?
Thanks

**Comment by daniel-j-h** [comment]
Your osrm-extract, osrm-contract and osrm-routed binary's version is out of sync.

You need to run the toolchain with the same version.

https://github.com/Project-OSRM/osrm-backend#quick-start

**Comment by davidmir** [comment]
But how can I do what version I ran when I did the extract and contract? This is a world wide file (which takes days to run) so I wanted to see if I would not have to run this process again.

**Comment by danpat** [comment]
@davidmir For old versions of OSRM, there is no good way to tell what version the files were created with.  Sorry :-(

Starting with OSRM 5.6, we include a version number header - files generated with 5.6 and onwards will now trigger this compatibility message:

```
[error] planet-latest.osrm.nodes is not compatible with this version of OSRM
[error] It was prepared with OSRM 5.5.0 but you are running 5.6.5
[error] Data is only compatible between minor releases
```

If your files are from pre-5.6, you'll get the message you are getting - sorry, there's no fix for this other than to generate the files again.
