### ISSUE TITLE
Does the public API service no longer work?

### ISSUE THREAD

**Issue by petrovnn** [Project-OSRM/osrm-backend#3921]
Here is the link from the documentation, it does not work. Returns the 504 timeout error.

http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false

Will this feature work?
Or can I use another service?

**Comment by danpat** [comment]
@petrovnn Looks like the server is down - it runs the latest unreleased code, so this happens sometimes.

The demo server is provided as just that - a demo of the software.  If you need a reliable service, you can always run your own copy.

Someone will take a look at it on Monday.

**Comment by TheMarex** [comment]
Works again.
