### ISSUE TITLE
OSRM Add Local Data

### ISSUE THREAD

**Issue by mkmrad** [Project-OSRM/osrm-backend#3924]
Greetings;

I`ve downloaded Lebanon data as .pbf file from geofabric site.
I`ve start osrm-routed for the .osrm data
All is good.

I need to add new roads to the downloaded data and supports those roads in the route service.

Any help is highly appreciated.

Mazen

**Comment by TheMarex** [comment]
Adding map data to Open Street Map is covered best by this guide: http://wiki.openstreetmap.org/wiki/Beginners%27_guide

This is not really specific to OSRM, but here are some links to how to reach out to people in the OSM community:

- http://forum.openstreetmap.org/
- http://wiki.openstreetmap.org/wiki/Mailing_lists
