### ISSUE TITLE
osrm-extract resulting error "terminate called after throwing an instance of 'osrm::util::exception'"

### ISSUE THREAD

**Issue by Raghvendradubey** [Project-OSRM/osrm-backend#3927]
Hi
  I am working on latest osrm master branch, and when I am trying to extract using osrm-extract 
(osrm-extract india-latest.osm.pbf -p profile/car.lua)  I am getting error i.e
 terminate called after throwing an instance of 'osrm::util::exception'
  what():  Error writing to india-latest.osrm.turn_penalties_index
Aborted (core dumped)

the  log file looks like this

[info] Parsing finished after 113.416 seconds
[info] Raw input contains 54314961 nodes, 6771884 ways, and 35082 relations
[info] Sorting used nodes        ... ok, after 5.65175s
[info] Erasing duplicate nodes   ... ok, after 5.38616s
[info] Sorting all nodes         ... ok, after 26.9978s
[info] Building node id map      ... ok, after 34.489s
[info] setting number of nodes   ... ok
[info] Confirming/Writing used nodes     ... ok, after 21.7488s
[info] Processed 17952044 nodes
[info] Sorting edges by start    ... ok, after 32.7863s
[info] Setting start coords      ... ok, after 62.1478s
[info] Sorting edges by target   ... ok, after 34.107s
[info] Computing edge weights    ... ok, after 65.5272s
[info] Sorting edges by renumbered start ... ok, after 33.2879s
[info] Writing used edges       ... ok, after 17.9049sProcessed 18908267 edges
[info] Sorting used ways         ... ok, after 3.66746s
[info] Sorting 1546 restriction. by from... ok, after 0.091869s
[info] Fixing restriction starts ... ok, after 0.585595s
[info] Sorting restrictions. by to  ... ok, after 0.019205s
[info] Fixing restriction ends   ... ok, after 0.025976s
[info] usable restrictions: 1140
[info] writing street name index ... ok, after 0.115197s
[info] extraction finished after 494.903s
[info] Generating edge-expanded graph representation
[info]  - 1140 restrictions.
[info] Importing number_of_nodes new = 17952044 nodes 
[info]  - 164 bollard nodes, 2788 traffic lights
[info]  and 18908267 edges 
[info] Graph loaded ok and has 18908267 edges
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.156096
[info] Edge compression ratio: 0.198772
[info] Generating edge expanded nodes ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 18908230 nodes in edge-expanded graph
[info] Generating edge-expanded edges 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% .
terminate called after throwing an instance of 'osrm::util::exception'
  what():  Error writing to india-latest.osrm.turn_penalties_index
Aborted (core dumped)

I am using india-latest.osm.pbf http://download.geofabrik.de/asia/india-latest.osm.pbf 

Please help me to figure out this problem.

Thanks

**Comment by danpat** [comment]
The most likely explanation is that you've run out of disk space.  Can you check how much you have available?

**Comment by Raghvendradubey** [comment]
yes, it is disk space problem.
Thanks for help
