### ISSUE TITLE
/nearest and /table APIs use points very far away from original points

### ISSUE THREAD

**Issue by Jorl17** [Project-OSRM/osrm-backend#3930]
Hi,

We seem to have run into a strange issue (or perhaps are misunderstanding the API). Take for example the following coordinates:
```
41.6231515,-8.2141202
40.20993,-8.411699
```

If we run the **/table service** we get 

```
[
   [0,4121.4],
   [4116.9,0]
]
```

Which makes the time distance between the two points about an hour. However the real and accurate time is 2 hours. This is the consequence of the API fixing our points to other, vastly different coordinates (the **/nearest service does this too**). In fact, the following happens:
* **`41.6231515,-8.2141202` gets corrected to `39.881521, -7.747428`**
* **`40.20993,-8.411699` gets corrected to `39.746448, -7.974193`**

However **if we use the route API (e.g. `https://router.project-osrm.org/route/v1/driving/-8.2074062,41.623507;-8.41207807983568,40.20979165?overview=false&steps=false`) we get the expected 2h**. This is however not very practical for when we have more than 2 points and want a distance matrix.

Notice that this issue with coordinates getting corrected to points very far away happens in several places. For example, notice the following two coordinates:
* **Paris: `48.854973,2.267261` gets corrected to `47.34759,3.874155`**
* **New York: `40.821604,-74.199140` gets corrected to a whooping `53.735564,-65.84724`**

In addition, **we do not see this issue when using OSRM v4**, which we are trying to migrate from.

Is this a misunderstanding of ours regarding the API? Is there a bug? If it is a misunderstanding, then what is the recommended way to obtain a distance matrix with the correct values, without this issue?

Thanks!

**Comment by daniel-j-h** [comment]
> Notice that this issue with coordinates getting corrected to points very far away happens in several places. For example, notice the following two coordinates:
> 
>     Paris: 48.854973,2.267261 gets corrected to 47.34759,3.874155

I can not reproduce:

    curl 'http://router.project-osrm.org/nearest/v1/driving/2.267261,48.854973' | jq '.'

```c++
{
  "waypoints": [
    {
      "distance": 31.883435,
      "hint": "wzIqgP___390igsAjwAAAJUAAAAAAAAA3AAAAI8AAACVAAAAAAAAANwAAAD_EyMA278AAAuZIgDMeOkCfZgiAL136QIAAAEBcOdKQQ==",
      "name": "Rue de l'Assomption",
      "location": [
        2.267403,
        48.855244
      ]
    }
  ],
  "code": "Ok"
}
```

can you double check you 1/ have an large enough osm extract 2/ are not mixing lat, lon

**Comment by Jorl17** [comment]
You were right! Such a foolish mistake, we were mixing latitude and longitude, except for the route requests.

Thank you very much for your help and sorry to waste your time with such a silly issue!

**Comment by daniel-j-h** [comment]
Great it works now! :sparkles:
