### ISSUE TITLE
Can't restrict u-turns during Trip calculations

### ISSUE THREAD

**Issue by JohnGrace85** [Project-OSRM/osrm-backend#3944]
Hello everyone! 

I've been using OSRM for a long time (great work!) and recently I needed to compute a trip between around 120 points. I was using the v4 version of OSRM and it was returning some weird results (e.g. going back and forward two or three times between twos points it had already visited). I don't know if this version had any problem with the large amount of points, but I decided it was time to upgrade to the newer version. 

Now, the computed route seems to be working great, but only with one problem: it is taking some liberties with u-turns, which is something I want to avoid. Firstly, I tried to use the `continue_straight=true` variable in the request but I found out it is only supported for `route` and not for `trip`. Then, in the `car.lua` file, I set `u_turn_penalty` to 1000, but it seems it has no effect (the is also the `continue_straight_at_waypoint` property, but it is already set to true). I tried to search but I found nothing that addressed the problem or that mentions anything related to the support of restricting u-turns in trip calculations (closest I came to was this: #2355). 

Can you provide some help of what I might be doing wrong? Thanks!

**Comment by MoKob** [comment]
@JohnGrace85 right now it is not possible to completely disable all u-turns in the output. To explain it completely, you need to differentiate between different types of u-turns.

One that you mentioned is controlled via `continue_straight_at_waypoint`:
On `s -- v -- t`, a route using an intermediate `via` coordinate `v`, this flag specifies that when you arrive at `v` from `s`, you don't do a `u-turn` to reach `t`. But it is only concerned about u-turns at `v`.

The remaining u-turns are in the road network. In general we only allow u-turns on dead-ends. So you will usually not see `a - b - c` result in a route with a u-turn at `b`. But this is, sadly, limited to single turns.
What we currently cannot avoid is:
```
g - f - e (main road)
    d
a - b - c (main road)
```
When going `a - b - d - f - g`, the two local instructions at `b` and `f` are `turn left`. In an effort to improve instruction quality, these two instructions from `main road` to `main road` are combined into a `turn uturn`. 
The engine itself currently does not support multi-hop restrictions. This is tracked over at https://github.com/Project-OSRM/osrm-backend/issues/2681.

**Comment by JohnGrace85** [comment]
@MoKob thank you for you answer. The issue that you mention is not the problem at hand. Actually, it's the first thing that you mentioned (the `s -- v -- t`which in this case is more `s -- v1 -- v2 -- ... -- vx -- s). On my end, the routing engine is making u-turns at some via points, which, from what I understand from what you said, is not supposed to. This is happening in a network of simple residential roads which are not dead-ends. (If you deem it necessary, I can try and find an example of this happening).

**Comment by MoKob** [comment]
@JohnGrace85 an example for a u-turn against the `continue_straight_at_waypoint` parameter would be great. This is not supposed to happen. Even at dead-ends, you should see the road extend to the end of the road to perform a u-turn.

**Comment by JohnGrace85** [comment]
@MoKob  It happens, for example, when I make [this request](http://localhost:5000/trip/v1/driving/50.591938,26.103805;50.570942,26.120321;50.569881,26.118781;50.569409,26.11876;50.568898,26.11857;50.569118,26.11888;50.570258,26.11924;50.570376,26.118923;50.570974,26.119099;50.572727,26.119424;50.572602,26.118351?overview=full&source=first), you can see it first happening near point `50.572602, 26.118351`. I'm using the car profile with the only thing changed being the u-turn penalty parameter and I'm using v5.6.0. I'm using [this map](http://download.geofabrik.de/asia/gcc-states.html).

The response being: `{"waypoints":[{"location":[50.599577,26.107509],"hint":"ZkkFgP___38AAAAAGAAAAMsAAAAgAwAA0gEAABgAAADLAAAAIAMAANIBAAAxzQMATQwAAJkWBAN1Xo4BwvgDA_1PjgEHAAEBFYafKg==","waypoint_index":0,"name":"","trips_index":0},{"location":[50.570948,26.120323],"hint":"xEUFgARHBYAAAAAAHgAAAEMAAAAAAAAAAAAAAB4AAABDAAAAAAAAAAAAAABUywMATQwAAMSmAwODkI4BvqYDA4GQjgEAAAEBFYafKg==","waypoint_index":1,"name":"","trips_index":0},{"location":[50.569894,26.118746],"hint":"3kUFgAJHBYAAAAAAJAAAABYAAAAAAAAAAAAAACQAAAAWAAAAAAAAAAAAAABlywMATQwAAKaiAwNaio4BmaIDA32KjgEAAAEBFYafKg==","waypoint_index":5,"name":"","trips_index":0},{"location":[50.569343,26.118924],"hint":"skUFgLRFBYAAAAAAGgAAAFMAAAAAAAAAAAAAABoAAABTAAAAAAAAAAAAAABGywMATQwAAH-gAwMMi44BwaADA2iKjgEAAAEBFYafKg==","waypoint_index":7,"name":"","trips_index":0},{"location":[50.568919,26.118581],"hint":"tkUFgE9GBYAAAAAAEwAAABcAAAAAAAAAAAAAABMAAAAXAAAAAAAAAAAAAABJywMATQwAANeeAwO1iY4Bwp4DA6qJjgEAAAEBFYafKg==","waypoint_index":9,"name":"","trips_index":0},{"location":[50.569129,26.118854],"hint":"skUFgLRFBYAAAAAAOwAAADIAAAAAAAAAAAAAADsAAAAyAAAAAAAAAAAAAABGywMATQwAAKmfAwPGio4Bnp8DA-CKjgEAAAEBFYafKg==","waypoint_index":8,"name":"","trips_index":0},{"location":[50.570263,26.119228],"hint":"q0UFgK1FBYAAAAAAnAAAACkAAAAAAAAAAAAAAJwAAAApAAAAAAAAAAAAAABBywMATQwAABekAwM8jI4BEqQDA0iMjgEAAAEBFYafKg==","waypoint_index":6,"name":"","trips_index":0},{"location":[50.570384,26.118904],"hint":"3UUFgPhGBYAAAAAAJgAAAB4AAAAAAAAAAAAAACYAAAAeAAAAAAAAAAAAAABkywMATQwAAJCkAwP4io4BiKQDAwuLjgEAAAEBFYafKg==","waypoint_index":4,"name":"","trips_index":0},{"location":[50.570979,26.119084],"hint":"-kYFgAFHBYAAAAAAPAAAAFcAAAAAAAAAAAAAADwAAABXAAAAAAAAAAAAAAARzAMATQwAAOOmAwOsi44B3qYDA7uLjgEAAAEBFYafKg==","waypoint_index":3,"name":"","trips_index":0},{"location":[50.572741,26.119393],"hint":"wEYFgMRGBYAAAAAApgAAAFQAAAAAAAAAAAAAAKYAAABUAAAAAAAAAAAAAAD5ywMATQwAAMWtAwPhjI4Bt60DAwCNjgEAAAEBFYafKg==","waypoint_index":10,"name":"","trips_index":0},{"location":[50.572571,26.118425],"hint":"SEUFgFVFBYAAAAAAmwAAAFUAAAAAAAAAAAAAAJsAAABVAAAAAAAAAAAAAAAKywMATQwAAButAwMZiY4BOq0DA8-IjgEAAAEBFYafKg==","waypoint_index":2,"name":"","trips_index":0}],"code":"Ok","trips":[{"distance":12711.9,"weight_name":"routability","legs":[{"distance":7201.1,"steps":[],"duration":453.2,"weight":453.2,"summary":""},{"summary":"","weight":59.1,"duration":59.1,"steps":[],"distance":324.9},{"distance":240.3,"steps":[],"duration":41.2,"weight":41.2,"summary":""},{"distance":62.7,"steps":[],"duration":9,"weight":9,"summary":""},{"summary":"","weight":7.4,"duration":7.4,"steps":[],"distance":52},{"summary":"","weight":20.8,"duration":20.8,"steps":[],"distance":91.4},{"summary":"","weight":14.1,"duration":14.1,"steps":[],"distance":97.9},{"summary":"","weight":3.3,"duration":3.3,"steps":[],"distance":22.7},{"distance":56.1,"steps":[],"duration":13.3,"weight":13.3,"summary":""},{"distance":445.3,"steps":[],"duration":64.5,"weight":64.5,"summary":""},{"distance":4117.5,"steps":[],"duration":274.9,"weight":274.9,"summary":""}],"duration":960.8,"weight":960.8,"geometry":{"type":"LineString","coordinates":[[50.599577,26.107509],[50.601111,26.104958],[50.602225,26.103085],[50.602557,26.102536],[50.60291,26.101997],[50.603301,26.101464],[50.603964,26.100559],[50.604788,26.09954],[50.605,26.099282],[50.605302,26.098947],[50.605621,26.09862],[50.605784,26.098472],[50.605988,26.098264],[50.606041,26.098208],[50.606127,26.098117],[50.606246,26.098161],[50.606164,26.098242],[50.606063,26.098354],[50.605905,26.098539],[50.605736,26.098718],[50.605172,26.099307],[50.604102,26.100587],[50.603608,26.101246],[50.60313,26.101928],[50.602338,26.103137],[50.599512,26.107878],[50.59861,26.109375],[50.595375,26.114814],[50.59466,26.116017],[50.593364,26.118193],[50.593123,26.118667],[50.592763,26.119399],[50.592434,26.120125],[50.59214,26.120889],[50.591984,26.121356],[50.591774,26.122127],[50.591703,26.122435],[50.591687,26.122594],[50.591703,26.122715],[50.591849,26.122931],[50.59201,26.123073],[50.592151,26.123257],[50.592227,26.123385],[50.592268,26.123517],[50.592267,26.123722],[50.592215,26.1239],[50.592128,26.124029],[50.591964,26.124125],[50.59177,26.124182],[50.591525,26.124174],[50.591277,26.124116],[50.591111,26.124033],[50.590979,26.123947],[50.59086,26.123799],[50.590796,26.123691],[50.590606,26.123366],[50.590496,26.123211],[50.590415,26.12311],[50.590259,26.122972],[50.590013,26.122818],[50.588849,26.122075],[50.586519,26.120473],[50.583788,26.118548],[50.583339,26.118236],[50.583232,26.118365],[50.583072,26.118505],[50.582884,26.118626],[50.582672,26.118708],[50.577832,26.120582],[50.577461,26.120725],[50.577307,26.120777],[50.576926,26.120902],[50.572823,26.122335],[50.572704,26.122381],[50.57261,26.122304],[50.57249,26.122162],[50.572358,26.122103],[50.570423,26.12139],[50.570475,26.121279],[50.570609,26.120987],[50.57065,26.12091],[50.570871,26.120498],[50.570948,26.120323],[50.57112,26.119933],[50.571278,26.119575],[50.571387,26.119612],[50.571555,26.119248],[50.57167,26.118999],[50.571761,26.118801],[50.57184,26.118631],[50.571917,26.118464],[50.57202,26.118241],[50.572571,26.118425],[50.57202,26.118241],[50.571917,26.118464],[50.57184,26.118631],[50.571761,26.118801],[50.57167,26.118999],[50.571555,26.119248],[50.570979,26.119084],[50.570578,26.11897],[50.570384,26.118904],[50.570135,26.118818],[50.569894,26.118746],[50.570135,26.118818],[50.570001,26.119138],[50.570263,26.119228],[50.570001,26.119138],[50.569516,26.11898],[50.569343,26.118924],[50.569129,26.118854],[50.568806,26.118749],[50.568919,26.118581],[50.569048,26.118389],[50.569312,26.118045],[50.570284,26.11846],[50.570706,26.11863],[50.57167,26.118999],[50.572741,26.119393],[50.573277,26.11959],[50.5738,26.119777],[50.573594,26.120356],[50.575027,26.120835],[50.575881,26.121146],[50.576496,26.120943],[50.576894,26.120803],[50.577243,26.120684],[50.577381,26.120639],[50.578106,26.120361],[50.580447,26.119462],[50.581683,26.118976],[50.582476,26.118663],[50.582763,26.118551],[50.5828,26.118529],[50.582939,26.11845],[50.583093,26.118312],[50.583216,26.11815],[50.583275,26.11812],[50.58334,26.1181],[50.583384,26.118133],[50.583536,26.118248],[50.585723,26.119738],[50.586242,26.120092],[50.58992,26.122587],[50.590015,26.122652],[50.590246,26.122798],[50.59041,26.122888],[50.590571,26.122936],[50.590746,26.122953],[50.590845,26.122941],[50.590981,26.122898],[50.591059,26.122851],[50.591258,26.122667],[50.591429,26.122488],[50.59152,26.122301],[50.591578,26.122075],[50.591594,26.122015],[50.591757,26.121401],[50.592025,26.120541],[50.592378,26.11968],[50.592548,26.119329],[50.592703,26.119058],[50.593062,26.118423],[50.593322,26.11795],[50.594748,26.115572],[50.59566,26.114074],[50.598467,26.109364],[50.599366,26.10786],[50.599577,26.107509]]}}]}`

I can also say that what that situation with the dead-ends is also happening (i.e. it is turning right at the via point instead of going until it reaches the end of the road).

**Comment by danpat** [comment]
The problem with this example is that the graph isn't modeling a u-turn - it's two left-hand-turns.

Our guidance code knows how to collapse these into a u-turn, but unfortunately, that occurs *after* routing is complete.  There's a slight disconnect between what the routing engine considers a u-turn (directly turning around on the same graph edge) and what guidance considers a u-turn (it performs additional checks once the route geometry is known).

[This ticket](https://github.com/Project-OSRM/osrm-backend/issues/2681) kind of sums up the complexity for restricting multi-way turns like the one in this example.  Nobody has had the time to really dive in and implement this yet.

@JohnGrace85 This is one specific scenario however - do you have others?

**Comment by JohnGrace85** [comment]
@danpat thank you for your answer, but I'm finding it hard to see how that can be the situation at hand. I can see how that situation applies at the u-turn at King Hamad Highway (right at the beginning of the route), but not on the intersection between roads 711 and 741, which doesn't seem to be the situation you pointed out.

**Comment by MoKob** [comment]
@JohnGrace85 can you verify that the option `continue_straight` is checked in the request you do? The link provided does not specify the parameter.
Simply based on the waypoints you provide, I cannot see a reason for a u-turn in there. Since we also use OSM data from that region, the result should just be the same as on our demo-server.
Using your request on the demo-server, I don't see any u-turns in the result ([link](http://router.project-osrm.org/trip/v1/driving/50.591938,26.103805;50.570942,26.120321;50.569881,26.118781;50.569409,26.11876;50.568898,26.11857;50.569118,26.11888;50.570258,26.11924;50.570376,26.118923;50.570974,26.119099;50.572727,26.119424;50.572602,26.118351?overview=full&source=first&steps=true)).
In this request I can see the trip taking a u-turn. For some reason I cannot specify `continue_straight=true` on the demo-server, which might be a related bug? (/cc @daniel-j-h)

**Comment by JohnGrace85** [comment]
@MoKob The trip end point does not accept the `continue_straight` parameter, only the route end-point does (from what I can see in the API documentation).

**Comment by MoKob** [comment]
Ah. For some reason I didn't see that you were using the trip plugin. In the trip plugin you have the problem that everything is based on a distance matrix. This matrix will allow u-turns at every destination. So if you want to ensure that your trip does not have u-turns, you could use the order returned by the trip plugin and request a viaroute with `continue_straight` enabled. That way you would fully avoid u-turns.

**Comment by JohnGrace85** [comment]
Hm, that's slightly disappointing, but I can understand the complexity of the algorithm which could handle this would be very high. Thanks for taking the time to answer my questions!
