### ISSUE TITLE
Couldn't install npm packages osrm@5.6.5 and @5.7.0-rc.2

### ISSUE THREAD

**Issue by irnc** [Project-OSRM/osrm-backend#3945]
`yarn add osrm@5.6.5` fails with error `node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.6.5/Release/node-v51-linux-x64.tar.gz`

While `yarn add osrm@5.7.0-rc.2` fails with error `node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.7.0-rc.2/Release/node-v51-linux-x64.tar.gz`

```
node-pre-gyp info using node-pre-gyp@0.6.34
node-pre-gyp info using node@7.7.2 | linux | x64
```

**Comment by TheMarex** [comment]
We only build binary packages for node 4 and node 6 at the moment.

You could try to do a source build:

```
git checkout v5.7.0-rc.2
./scripts/node_install.sh
```

5.7.0 RC3 will hopefully fix the build-from-source fallback, so `yarn add 5.7.0-rc.3` will hopefully call `scripts/node_install.sh` automatically.

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/pull/3914

**Comment by rhwang201** [comment]
> We only build binary packages for node 4 and node 6 at the moment.

Is that still the case? I could only `npm install -g osrm` on node v4.x.x, not v6.x.x

**Comment by daniel-j-h** [comment]
Nope looks good here:

    $ nvm use 6
    Now using node v6.10.3 (npm v5.0.1)

    $ npm install osrm
    
    osrm@5.7.3 install /tmp/node6osrm/node_modules/osrm
    node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

    [osrm] Success: "/tmp/node6osrm/node_modules/osrm/lib/binding/node_osrm.node" is installed via remote

    $ ls node_modules/osrm/lib/binding/
    libtbb.a        libtbbmalloc_proxy.so    libtbbmalloc.so    libtbb.so    node_osrm.node   osrm-contract   osrm-datastore  osrm-partition
    libtbbmalloc.a  libtbbmalloc_proxy.so.2  libtbbmalloc.so.2  libtbb.so.2  osrm-components  osrm-customize  osrm-extract    osrm-routed
