### ISSUE TITLE
Where is defined the profile name ?

### ISSUE THREAD

**Issue by pocman** [Project-OSRM/osrm-backend#3946]
Hi, 

In the documentation, it's said that _Mode of transportation, is determined statically by the Lua profile that is used to prepare the data using  osrm-extract_.

I ran osrm-extract with 4 profiles `car.lua`, `car_datacity.lua`, `bicycle.lua` and `bicycle_datacity.lua` but I can't use *car_datacity* and *bicycle_datacity* as profile values in my requests (*car* is working for .osrm generated with both `car.lua`, `car_datacity.lua`, same for *bicycle*).

Are the profile defined by some value inside the .lua file ?
Can I changed that by hand in the .osrm files or do I need to run osrm-extract again ?

**Comment by danpat** [comment]
`osrm-routed` can only serve requests for one `.osrm` file at a time.  One `.lua` profile creates one set of `.osrm` files.

In order to support multiple profiles, you will need to run osrm-extract/osrm-contract multiple times and copy the resulting `.osrm` files to different names/locations, then run multiple copies of `osrm-routed` on different TCP ports.

**Comment by daniel-j-h** [comment]
Closing as not acitonable on our side here.
We want to support this in the future :) nothing for now, though.

**Comment by pocman** [comment]
Up.

**Comment by danpat** [comment]
@pocman The profile name in the URL for `osrm-routed` isn't actually used - it's there for API future-proofness for when we finally *do* support `osrm-routed/libosrm.a` loading multiple profiles into memory in a single instance.  Right now it's just an unused token in the URL path.

If you've got a load balancer, you would do the following:

  1. Run `osrm-extract/osrm-contract` for each of your `.lua` profiles, saving the datafiles into separate locations.
  2. Run 4 copies of `osrm-routed` on different TCP ports, each pointing to a different datafile set.
  3. In your load balancer, setup routing rules to look at the `profile` part of the URL, and send requests to the appropriate backend - `osrm-routed` ignores the `profile` string in the URL, so you can pass the requests through unmodified.

**Comment by danpat** [comment]
This is the ticket for multiple profile support:

https://github.com/Project-OSRM/osrm-backend/issues/10

The ticket is a bit old (#10!!!), but believe it or not, we have plans to implement this over the next few months, after 6 years of a holding pattern :-)
