### ISSUE TITLE
Building a route without crossing certain coordinates

### ISSUE THREAD

**Issue by DZRock** [Project-OSRM/osrm-backend#3947]
Hello! Can I specify coordinates in the route construction that will be ignored osrm-backend? I want in real time mark some streets as ignored and build a way around them.

**Comment by danpat** [comment]
@DZRock the best way to do this right now is to use the "traffic update" feature - set the road speeds to 0, and they will be removed.

Take a look at this wiki page for instructions on how to use this feature: https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

You will need to know the OSM node IDs for the roads you want to close.

**Comment by DZRock** [comment]
@danpat thx, that's what I need
