### ISSUE TITLE
Change some .edges data to be indexed by node

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3954]
Currently we index a lot of data by `turn_id` instead of by node ID as can be seen [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/extractor/turn_data_container.hpp#L114-L121). Some of these values don't depend on the turn, but only on the start node. Namely:

- Street name (4 byte)
- Geometry ID (4 byte)
- Travel Mode (1 byte)

We already have this data indexed by node ID, but we currently are saving it in `.fileIndex` on disk. https://github.com/Project-OSRM/osrm-backend/pull/3446 would conveniently move this data to memory.

To take advantage of this we need to change the unpacking logic in [`annotatePath`](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/routing_algorithms/routing_base.hpp#L94-L311) to not only use a list of `EdgeID`s but also a list of `NodeID`s.

The file data saving for this would be 50% of the .edges file.

**Comment by oxidase** [comment]
@danpat This PR directly depends on #3446 at https://github.com/Project-OSRM/osrm-backend/blob/0e39aa9488bff97cffda1d12fb18cdeb537e0c03/include/engine/routing_algorithms/routing_base.hpp#L119 and some other places where node-id-indexed data is needed.

After merging #3446 this PR reduces to removing duplicated data from `TurnDataContainerImpl`, adjustment  of datafacades, changing `annotatePath` argument from `const std::vector<EdgeID> &unpacked_edges` to `const std::vector<NodeID> &path_nodes`, changing algorithm-dependent unpacking to return `const std::vector<NodeID> &path_nodes` and using `datafacade.GetNodeData` that will be introduced in #3446

**Comment by oxidase** [comment]
Fixed by #3994. In #3446 https://github.com/Project-OSRM/osrm-backend/blob/a9d3e6188403a39c7d501658e017780107eaff52/src/extractor/edge_based_graph_factory.cpp#L242-L333 should be refactored
