### ISSUE TITLE
Reduce file sizes

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3955]
Over the last years we added a lot of additional data OSRM for different purposes. We never payed too much attention to the data size, which results in huge files when using a global data set. This ticket tries to capture the overall efforts for 5.8 to reduce this.

Especially problematic are files that are not only used during pre-processing but also during the query.

Below is a list of files and their relative size. I used `Bayern` as a test dataset (537 MB .osm.pbf).

The raw numbers can be found in https://docs.google.com/spreadsheets/d/1NWB4TMK_ML5lh8efTQWMAgIMsiVcgcELG-69XXPw_fQ/edit#gid=0

Below the numbers for files needed by `osrm-routed`:

| File | Uncompr. | Compr. | Compr. % | CH | MLD |
|------|--------------|------------|-----------------|-----------|------------|
| .osrm.cells | 18,133,264 | 15,218,265 | 83.92% | | 2.45% |
| .osrm.datasource_names | 66,056 | 314 | 0.48% |  0.01% | 0.01% |
| **.osrm.edges** | 81,466,456 | 37,258,846 | 45.74% | 11.33% | 11.00% |
| **.osrm.fileIndex** | 175,460,352 | 87,107,319 | 49.65% | 24.41% | 23.69% |
| **.osrm.geometry** | 149,604,972 | 77,460,725 | 51.78% | 20.81% | 20.20% |
| **.osrm.hsgr** | 205,638,788 | 63,342,142 | 30.80% | 28.61% | |
| .osrm.icd | 20,921,226 | 4,706,191 | 22.49% | 2.91% | 2.82% |
| .osrm.level | 16 | 35 | 218.75% | 0.00% | 0.00% |
| **.osrm.mldgr** | 187,405,744 | 21,176,981 | 11.30% |  | 25.30% |
| .osrm.names | 1,912,656 | 1,283,449 | 67.10% | 0.27% | 0.26% |
| .osrm.nodes | 63,178,848 | 63,178,927 | 100.00% |  8.79% | 8.53% |
| .osrm.partition | 21,969,136 | 2,678,274 | 12.19% | | 2.97% |
| .osrm.properties | 296 | 69 | 23.31% | 0.00% | 0.00% |
| .osrm.ramIndex | 180,364 | 179,412 | 99.47% | 0.03% | 0.02% |
| .osrm.timestamp | 28 | 47 | 167.86% | 0.00% | 0.00% |
| .osrm.tld | 1,992 | 1,982 | 99.50% | 0.00% | 0.00% |
| .osrm.tls | 3,558 | 2,866 | 80.55% | 0.00% | 0.00% |
| .osrm.turn_duration_penalties | 10,183,314 | 5,881,479 | 57.76% | 1.42% | 1.37% |
| .osrm.turn_weight_penalties | 10,183,314 | 5,911,832 | 58.05% | 1.42% | 1.37% |

Marked the files that promisee the most data compression. No big surprises here:

- The inflated `.mldgr` file size is due to https://github.com/Project-OSRM/osrm-backend/issues/3779 pending.
- Possible >40% reduction of `.geometries` file https://github.com/Project-OSRM/osrm-backend/issues/3896
- Possibly >50% reduction of `.fileIndex` file https://github.com/Project-OSRM/osrm-backend/pull/3446
- Possible 50% reduction pf `.edge` file https://github.com/Project-OSRM/osrm-backend/issues/3954  DONE!

/cc @daniel-j-h @danpat @oxidase

**Comment by TheMarex** [comment]
The outcome here is that we changed the bytes read by `osrm-routed` during startup from `740,671,592` to `518,394,615` which is a 30% reduction.

**Comment by kostadin24** [comment]
Possible >40% reduction of .geometries?
Does this size reduction reflect on accuracy of coordinates?

**Comment by danpat** [comment]
No.  We store 6 decimal places of precision, the same as the original OSM data.  For longitude values between -180/+180, that only needs about 28 bits, not the full 32 bits of an `std::uint32_t`, and latitude needs even less.

The change packs the data more closely, not wasting those padding bits.  No precision is lost.
