### ISSUE TITLE
Can match service be configured to return full way geometry?

### ISSUE THREAD

**Issue by andrewkouri** [Project-OSRM/osrm-backend#3957]
I'm trying to modify the car.lua profile to support outputting the _full_ geometry of the way instead of just the geometries of certain legs in the matching service.  Is there a feasible way to do this?

So far:
```
          nodes = []
          for _, node in ipairs(way:get_nodes()) do
            nodes.append([node:lon(), node:lat()])
          end
```
And then I would want to output the polyline as a property on the way. New to lua...

**Comment by danpat** [comment]
This is unlikely to work reliably.  There are no general purpose properties on the way other than `name`, and because of guidance heuristics, we don't guarantee to return a `step` for every street name a route crosses (in some cases, instructions are merged so you don't get both street names).

Can you describe a bit more about the problem you're trying to solve?  Ways in OSM can span arbitrary numbers of intersections, they're not guaranteed to be of any particular length.

**Comment by andrewkouri** [comment]
Thanks for the response :)
I've already used up the "name" field for way id. 
Basically what I'm trying to do is make a map of all the ways I've map-matched. I could use the raw GPS trace, but that wouldn't be too slick.  So instead, I thought I would create the map from the clean OSM geometry.  Since I'm running this on planet.osm, I wanted to "lazily" populate the way geometry table with the ways that I've traveled rather than using osm2pgsql to dump the entire way table.

**Comment by danpat** [comment]
Maybe check out https://github.com/mapbox/route-annotator - this would be a second step after you've map-matched the route.

Note that the JSON response you're getting right now is not guaranteed to contain all way names - OSRM is designed to return instructions that are optimal for presenting to a user in a navigation context - we suppress many instructions (i.e. road names) when there is no need to give it to the user (i.e. when a road name changes but there is nothing to do but go straight).

What *would* work would be to do the following:

  1. Use OSRM to map-match your route - get the full geometry back with `overview=full`
  2. Use `route-annotator` to get all the way IDs touched by that route.
  3. Construct an OverPass query and retrieve the actual geometry for each way from the http://wiki.openstreetmap.org/wiki/Overpass_API

Quite a few steps, but it would work.

If you're using the map-matching API, the route geometry returned *is* the OSM geometry though - are you looking for the extra bits that extend past the end of your traces?

**Comment by andrewkouri** [comment]
Thanks, this makes sense.

Way IDs are subject to change, correct? Do you know how the overpass API handles differences in OSM versions? I think I would have to make sure that my planet.osm is always in sync with the overpass API's planet.osm... nevertheless, I think this still seems the most promising.

Yea, the map-matching API returns the route geometry, but only for the points that match the segment of the way that the GPS traces correspond to -- since I'm making a visualization of ways I'd like to show the whole way, not just the pieces that were snapped to

**Comment by danpat** [comment]
@andrewkouri Have you put `overview=full` on your request URL?  The map-matching plugin should give you the full geometry of the underlying OSM data that your trace matches to, not just your coordinates snapped to the road network.  You should get the full OSM geometry between your start and end points.

**Comment by danpat** [comment]
@andrewkouri oh yes, that's working as intended.  You'll get the full geometry for any complete ways that you've traversed with your GPS trace, but for partials like this one, you'll just get the portion you touched.

Honestly, "ways" isn't a great measure of anything in OSM - there's nothing stopping someone from splitting this road into 4 separate ways that just happen to be connected and have the same name.  Generally people don't do that, but there's absolutely no guarantees.  Splits do happen on property changes, like changes of speed limits.

Looking around OSM at the example coordinates you gave, everything seems pretty neatly organized and mapped - this is absolutely not always the case, so I wouldn't depend on it.

Can you describe in a bit more detail what you're trying to do?

**Comment by andrewkouri** [comment]
Thanks @danpat for the clarification! I agree -- mapping on ways seems pretty arbitrary, but short of splitting up my traces by closest node, I cannot think of any other identifier that would better "chunk" up the roads into segments.

I see you're at Mapbox -- I'll come say hi and show you what I'm building next time I'm in the office.

Closing for now, since it doesn't seem like an issue or feature of OSRM.
