### ISSUE TITLE
No traffic_light penalties applied for degree=2 nodes

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3958]
I think our turn_function is not applying penalties to nodes that it should (specifically, traffic lights):

https://github.com/Project-OSRM/osrm-backend/blob/e96545be2ebebee67791dff9afaed1c6f05462b2/profiles/car.lua#L395

For nodes like this:

http://www.openstreetmap.org/node/1675470014#map=18/53.48624/-2.33026

we tag the turn type as `no_turn` - this means that we apply no penalty in the `turn_function`.  We're missing traffic light penalties in these scenarios.

![c0d9ee5c-243a-11e7-8f10-a4406c4ef293](https://cloud.githubusercontent.com/assets/1892250/25157414/0e071bc6-2456-11e7-97c3-60a65fa25b07.png)

**Comment by TheMarex** [comment]
@danpat great catch. Looking in the profile, this is indeed the case here.
