### ISSUE TITLE
Does osrm-routed reload osrm data when updated? 

### ISSUE THREAD

**Issue by pocman** [Project-OSRM/osrm-backend#3960]
Hi, 

I'm trying to set a small internal production server based on the docker recipes and I would like to know if the osrm-routed is reloading the graph when the .osrm files are updated? 

Do you configure that in order to make daily updates, I only need to extract and contract and replace the previous version of the generated files? 

Is there a nice cloudformation template doing that our do you have the scripts used by the demo server? 
I try using the official docker and aws elastic container service but it's tricky since I need to schedule extraction, contraction and upload to s3. I also need to sync an s3 bucket before running the osrm-routed docker image. 

Thanks for your help.

**Comment by zabuTNT** [comment]
I think you have to use the shared memory. Load your OSRM file in RAM, than load a new OSRM.

https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory#using-shared-memory

**Comment by daniel-j-h** [comment]
Yep, either that or for a more simply (read: hacky) solution just spawn up a second `osrm-routed`; with `SO_REUSEPORT` it should just start listening on the same port. Then kill the old one.

For a production server you should really consider using the Node.js bindings.
The `osrm-routed` binary is more a local development server.

**Comment by pocman** [comment]
@zabuTNT Ok, so I will just go with spawning a new docker instance with the updated data behind an AWS load balancer that will do the job.

@daniel-j-h If I understand correctly, I will have to code my own api with the Node.js binding ? I don't really want to do that since I want the same as the [Referenced api](http://project-osrm.org/docs/v5.6.4/api/#general-options).

Is there a docker image running the node backend server ?

**Comment by daniel-j-h** [comment]
Yes, you are correct. You have to put e.g. a small Express HTTP server in front of the bindings and then do proper logging, monitoring etc. - I started to port `osrm-routed` to the Node.js bindings (https://github.com/Project-OSRM/osrm-backend/pull/3887) but it's blocked by some internal decisions.

There isn't a Docker image for the node bindings, you can `npm install osrm` - the rest is up to you.

**Comment by pocman** [comment]
@daniel-j-h Perfect. I'll stick with the docker recipes for now, looking forward to #3887 !

**Comment by daniel-j-h** [comment]
Great, closing here.
