### ISSUE TITLE
Capping Distance/Time or just returing K Nearest Points in Table Service

### ISSUE THREAD

**Issue by jamaps** [Project-OSRM/osrm-backend#3963]
Greetings OSRM,

I'm setting up OSRM to compute several large OD matrices (each ~ 15,000 x 15,000) for a large portion of southern Ontario. 

I was wondering if there's a way to limit the size of the search e.g. only return points and durations that are less than a certain distance or time threshold - or only return the closest k number of points. I only need to analyze travel times for nearby points, not those on opposite sides of my map. Plus I would like to save some computation time if possible.

I did some searching but couldn't find anything. Apologies if this has been answered elsewhere.

Cheers,

- JA

**Comment by daniel-j-h** [comment]
Your description sounds suspiciously like isochrones? There is an experimental pull request: https://github.com/Project-OSRM/osrm-backend/pull/3652

There is no option for stopping a Table request "early" on in the API.

For matrices this large you can also try
- Use the node bindings or even libosrm directly (avoid http if you can)
- Save results more efficiently than in json format
- Decompose a single big request into smaller ones (run in parallel) and re-assemble them again; might come with some coordinate to internal data structure overhead, so keep the smaller matrices still as big as possible

**Comment by danpat** [comment]
To add to this - you can use the `sources` and `destinations` option on the `table` plugin to perform a 1:N query - generate coordinates in a radius around your centerpoint, and gradually repeat queries until you have no more coordinates within range.

Other than that, the `table` service isn't really intended for this.  There are a couple of work-in-progress PR's for true isochrone searches https://github.com/Project-OSRM/osrm-backend/pull/3652 https://github.com/Project-OSRM/osrm-backend/pull/2477 and sort of https://github.com/Project-OSRM/osrm-backend/pull/3903, but none are in the main codebase yet and all need some work.

**Comment by jamaps** [comment]
Thanks guys! I've decided to divide and conquer in parallel which seems to do the trick faster than anticipated.
