### ISSUE TITLE
Refactor extract-conditionals tool libraries to read geojson timezone files

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#3967]
Including `libshp-dev` and `libshp2` dependencies have proven to be difficult for the current setup.

### Blockers
- Ubuntu 14.04 Trusty ships with `libshp-dev` and `libshp1`, but is missing implementation for several functions, e.g. `DBFOpen`, `SHPReadObject`, `SHPClose` etc
- Upgrading to Xenial is a big lift for OSRM builds and users. I don't think we can justify the switch for shapefile support
- Using/making a ppa for `libshp2` would also be a comparably big lift 

### instead
For now we should switch to using geojson based version of the timezone files and switch to using a library like rapidjson to do the file loading.

- See if geojson files are small enough to roll into osrm-backend
- Replace usage of shapefile in `LoadLocalTimesRTree` to use rapidjson for loading geojson into rtree

cc @oxidase

**Comment by daniel-j-h** [comment]
Looks like want to bundle rapidjson in the repo. now. A few questions wrt. that:

Is rapidjson packaged in Linux distributions we care about and can we use that?

If not, is it worth it to bundle rapidjson just for parsing geojson shapefiles? Or can we convert the shapefile polygones (?) into e.g. WKT we can then read with boost geometry's [`read_wkt`](http://www.boost.org/doc/libs/1_64_0/libs/geometry/doc/html/geometry/reference/io/wkt/read_wkt.html)?
