### ISSUE TITLE
File write/out-of-disk problems - don't throw exception to main

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3968]
Currently, the exception handling strategy for `osrm-extract` et. al. is to let exceptions propagate all the way up the stack and trigger the C++ `std::terminate()` built-in.

By default, `std::terminate()` logs the exception to `stdout`, then calls `std::abort()`, which in turns kills the process with `SIGABRT`.  [`SIGABRT`](http://man7.org/linux/man-pages/man7/signal.7.html) is one of the signals that will trigger a core dump, which is handy for debugging some exceptions.

However, we're currently throwing some exceptions for which we could be doing normal error handling.  Specifically, when our `FileWriter` encounters writing problems due to out-of-disk conditions, there's no reason to have such ugly error handling - we could throw a specific exception, then handle it gracefully at `main()`, returning a specific error code and making integration with large-scale production infrastructure easier.

The specific action here:  change our tooling throw a specific exception for file write problems, catch it in main, log an error, and return a specific error code, rather than just letting the exception trigger `std::terminate()`.

**Comment by danpat** [comment]
Hmm.  I'm not seeing a good way to change this behaviour without breaking our ABI.

We currently document that things like `osrm::extractor::extract(..)` will throw `osrm::util::exception` and `osmium::io_error`, and it has a `void` return type.

Given that, I'm tempted to just leave this ticket for a later release when we can change the ABI.

@TheMarex thoughts?

**Comment by TheMarex** [comment]
Given that I get alarms daily concerning this I would naturally like to fix a this in `5.8.0`.

I don't think going `void` -> `int` is a breaking API change.

**Comment by danpat** [comment]
A little bit of research revealed that while it's not defined by a standard, no C++ compilers use the return type as part of the mangled symbol name.  It generally doesn't make any sense to do so anyway, because it would indicate support for  ambiguous function overloading.

We should be ABI and source-code safe to change the return type of these externally visible functions.  I'll go ahead and implement that, and document the return codes.

**Comment by TheMarex** [comment]
Fixed by #4096.
