### ISSUE TITLE
There are no edges remaining after parsing

### ISSUE THREAD

**Issue by novikk** [Project-OSRM/osrm-backend#3970]
I had a shapefile which I converted to OSM for use with project OSRM. After running osrm-extract, I get the following error:

```
[info] Raw input contains 18609123 nodes, 4479847 ways, and 0 relations
terminate called after throwing an instance of 'osrm::util::exception'
  what():  There are no edges remaining after parsing. (at src/extractor/extractor.cpp:238)
```

Is there a problem with using osm files generated by ogr2osm?

**Comment by daniel-j-h** [comment]
Either your conversion has its issues and we are unable to parse your file's tags or your profile simply discards all ways. Which profile are you using? Can you provide a small self-contained test-case?

**Comment by novikk** [comment]
I'm using the default car.lua profile. Which tags are needed for osrm to work? I might be able to get them into the OSM by using a translation file for ogr2osm.

What do you mean by a self-contained test-case?

**Comment by daniel-j-h** [comment]
You can take a look at the car profile here:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua

for ways it's mostly highway and related tags that are accessible. With small self-contained test-case I mean e.g. a small part of your generated xml / pbf. Otherwise we can't help you much.

**Comment by danpat** [comment]
@novikk OSRM is designed for use with the full OpenStreetMap planet file, which contains buildings, trees, rivers and a whole lot of stuff that's not routable.

The `car.lua` script is responsible for filtering - it looks at the tags on `way`s and decides whether it's routable or not.  The error you've got indicates that none of the ways in your files had tags that `car.lua` considered useful.

Your conversion from a shapefile needs to tag ways in the OpenStreetMap style.  As @daniel-j-h said, you can read the `car.lua` script to see what it does, but basically, your converted data needs to look very OpenStreetMap-ey - `highway=residential` on residential roads, `highway=motorway` on motorways, etc.  The `car.lua` script expects these types of tags, and if it doesn't find them, it discards the ways.

`ogr2osm` does convert shapefile fields to tags, but if they're not the right ones, `car.lua` will ignore them.  You may need to either rename the fields in your shapefile, or run a conversion script over the output of `ogr2osm` to rename tags to something that `car.lua` can understand.

**Comment by emiltin** [comment]
an alternative is to create your own lua profile that reads the tags that ogr2osm exports, or if you don't care about way types, simply set speed and mode to the same value for all roads.

**Comment by novikk** [comment]
@daniel-j-h @emiltin Thank you both, that was of great help. I've developed my own translation file for ogr2osm setting the necessary highway tags according to what I had on the SHP file and OSRM and the car profile can now handle it properly.

**Comment by daniel-j-h** [comment]
Perfect, happy routing! Closing here as resolved!
