### ISSUE TITLE
Bike profiles route through alleys in Montreal - this is less than desirable

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3971]
In Montréal, our bike profile likes to send people down alleys:

![screen shot 2017-04-24 at 10 56 09 am](https://cloud.githubusercontent.com/assets/1892250/25351164/a90ec6f2-28dc-11e7-8867-e725633c0f3e.png)

however, at least in Montréal, routing via `highway=service, service=alley` class roads highly undesirable:

http://www.openstreetmap.org/way/21062511

There are two reasons we should consider avoiding alleys for bikes:

  1. The road surface could be a bit iffy
  2. You typically need to cross a through-street at the end of each alley - this is a lot less preferable than traveling with the flow of traffic.

We should consider making two changes:

  1. Slow down travel speeds in alleys - they're currently set to 15km/h, just like all other roads.
  2. Add some entry/exit penalties - either via https://github.com/Project-OSRM/osrm-backend/pull/3721, or https://github.com/Project-OSRM/osrm-backend/pull/2912 / https://github.com/Project-OSRM/osrm-backend/pull/2399

Related old ticket: https://github.com/Project-OSRM/osrm-backend/issues/592

**Comment by danpat** [comment]
@emiltin Do you have any thoughts on this one?  Can you think of any bad consequences of globally penalizing `highway=service service=alley` for the cycling profile?

**Comment by emiltin** [comment]
well, it depends on whether you think alleys are attractive or not. in some places, choosing smaller roads might be preferrably, as long as the route is not longer.

in any case, when computing fastest route, i don't think the current route in the example above makes sense. it's longer, and also have more turns, so something should be changed. maybe the first thing to clarify is why the alley is choosen?

**Comment by vincentsarago** [comment]
Also this is strange because there is a cycle path on `Rue Rachel Est` ...

**Comment by TheMarex** [comment]
Did some leg work here and looked at the possible impact across a few cities by searching for `highway=service` + `service=alley`:

# Berlin
![berlin alley](https://cloud.githubusercontent.com/assets/606968/25725720/ca9cfdac-3110-11e7-89bc-f6d7996ca5ec.png)
# Amsterdam
![bike alley amsterdam](https://cloud.githubusercontent.com/assets/606968/25725723/cbf7035a-3110-11e7-8b55-3e29c3b6fbbd.png)
# Copenhagen
![bike alley copenhagen](https://cloud.githubusercontent.com/assets/606968/25725725/cfed0022-3110-11e7-9008-5b88292f0c6b.png)
# London
![bike alley london](https://cloud.githubusercontent.com/assets/606968/25725732/d27c2dfe-3110-11e7-85df-7870eb752315.png)
# Montreal
![bike alley montreal](https://cloud.githubusercontent.com/assets/606968/25725735/d4604b6e-3110-11e7-86a4-b2a8b23918ec.png)

As you can see alleys are really uncommon in other major bike cities. I spot checked them in each of the cities above and I don't think putting penalties on them would impact route quality at all. Most of them are just short connection streets to buildings that you can't drive through anyway.

I will move forward with adding weight penalties to `service=alley` roads.

**Comment by emiltin** [comment]
ok. but why would the alley be choosen in the first place`in the original example, when the route is longer than just following the main road Rue Rachel?

**Comment by danpat** [comment]
@emiltin Hmm, that's a good question.

Here's a screenshot of the debug map for the bike profile at this location:

![screen shot 2017-05-05 at 11 01 41 am](https://cloud.githubusercontent.com/assets/1892250/25758161/42829e82-3182-11e7-8683-6ebb7561ed4a.png)

Unless we have a connectivity problem (maybe a turn restriction?), I can't see why we'd route down the alley here rather than taking Rue Rachel - it certainly seems to be the shorter path, and most roads are 15km/hr.

I'll dig a little more.

**Comment by TheMarex** [comment]
The detour is caused by our safety penalty on major streets, sadly we can't see this in the debug tiles yet, since we don't display weight but only duration.

**Comment by almithani** [comment]
@TheMarex does the safety penalty apply to cycleways?  The entire route along Rachel Est has tags cycleway = right and oneway:bicycle = no (http://www.openstreetmap.org/way/393785994)

**Comment by emiltin** [comment]
for copenhagen, it certainly would not make sense to choose a small sideroad, since we have cycletracks on all important roads, and most cyclists would choose this over a detour.

**Comment by emiltin** [comment]
it does odd to add penalties to both allays and main roads.
