### ISSUE TITLE
Question: Running OSRM engine on Azure

### ISSUE THREAD

**Issue by neilRGS** [Project-OSRM/osrm-backend#3975]
Hi all.

I am rather new to this, so please bear with me.

I need to investigate running three instances of OSRM on Azure, and would appreciate any tips and pointers as to the best way of going about this.

I do not wish to run a VM, as that will be prohibitive in cost, so I am looking at Compute, and possibly creating a Web Jobs project and including the .exe in that.

Does anyone have any experience with this that you'd be able to share please?

Many thanks in advance,

Neil.

**Comment by daniel-j-h** [comment]
Running OSRM on Azure should not be a problem - we just don't have any experience with it and the Windows build is not really battle-tested or in production here. For example I don't even know if the Node.js bindings work on Windows, we at least don't publish binaries for them. You may have better luck on the mailing list. Maybe someone has the same use case.

That said here are some resources for getting started:
- https://github.com/Project-OSRM/osrm-backend/wiki
- https://hub.docker.com/r/osrm/

**Comment by neilRGS** [comment]
Thanks Daniel.
I have subscribed to the mailing list and have asked my question.
In the meantime, continuing digging, it would appear that I may be able to use either an Azure Web Apps service or Service Fabric, to run the OSRM cli exe.
I am going to give that a go and will post back what I learn, so that others might be able to accomplish the task without having to dig through the incredibly large mine of somewhat confusing information about the various Azure options.

**Comment by daniel-j-h** [comment]
Great! I'm closing this here already as not actionable for us. We don't have experience with Azure at all. Sorry. If you can run Linux builds I would recommend doing so.

**Comment by neilRGS** [comment]
Ok, I’ll take that advice on board.

Many thanks,

Neil.


[cid:image003.png@01D239BC.F4B170B0]

Neil McLeish | Software Development Engineer
Email: neil.mcleish@rgsit.com<mailto:neil.mcleish@rgsit.com> | Tel: 0845 8550 550 | Web: www.rgsit.com<http://www.rgsit.com>

**Comment by TIGarupa** [comment]
@neilRGS do you have any update on running on Azure?
