### ISSUE TITLE
Investigate timed out builds - gcc-6-debug-cov-asan

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#3976]
`gcc-6-debug-cov-asan` build on travis consistently times out and fails builds (e.g. [current master](https://travis-ci.org/Project-OSRM/osrm-backend/jobs/225271061)).

Can we split the address sanitzer compiling and the test running from the current `-asan` builds? This will mean a bigger build matrix but shorter builds. 

At the same time we could move the `clang-format` check build into a separate build as well.

**Comment by daniel-j-h** [comment]
Landed with https://github.com/Project-OSRM/osrm-backend/issues/3985
