### ISSUE TITLE
Generate routing graph problem - after merging 2 pbf files.

### ISSUE THREAD

**Issue by kostadin24** [Project-OSRM/osrm-backend#3982]
Hello,
I have 2 pbf files /lets say 'A.osm' and 'B.osm'/ for generate routing graph.
I'm using osmconvert64 to merge them to all.pbf

1. If I use one of them - routing graph is generated correctly and works OK. Time to generate graph is about 10-15 minutes.

2. If I merge files with osmconvert - merged file wasn't proceed for more than 3 hours. On console last row that I see is "initializing elimination PQ".
Merged pbf file is 45mb. Occupied memory when I see "initializing elimination PQ" is 900mb. I have 8GB on machine and 6gb are free. CPU shows me 80-90% usage.

If I download same amount of data from OSM as one file - generation of graph works fine for hour.

I suspect that merge proccess not works correctly for some reasons.
In osm files i put - first nodes ordered by ID, then ways ordered by ID, then relations ordered by ID.
Is this mandatory order for data? Or data can be mixed? I'm asking because if osmconvert64 doesn't merge in expected order - I will have to write my oswn merger tool.

**Comment by kostadin24** [comment]
Tool hang because of data in pbf file is corrupted - bad merge.
Reasons for bad merge is overlapping ID sets :)

**Comment by emiltin** [comment]
try merging with another tool, like osmosis?
