### ISSUE TITLE
Printing bugs in 5.0.6 on Mac OS X

### ISSUE THREAD

**Issue by woll** [Project-OSRM/osrm-backend#399]
Printing the routing map on map.project-osrm.org, from the Safari web browser (5.0.6 on Mac OS X 10.5.8), using the "Print" menu item, has various problems.

1) When the left-hand (mis-named?) "Main window" panel (i.e. list of directions) is visible, then the only thing printed is that panel, without the map. The panel doesn't fit into the width of the printed page, but is a tall, thin column on the left-hand side of the page. Normally users would expect Safari to print the "whole page" i.e. the panel and the map.

2) If the "Main window" panel is not visible, then the page printed is essentially empty. There is no map. The only things printed are the top-left "Show main window" arrow button, and the 2 buttons at the bottom-right ("Configuration" and "Mapping Tools").

3) After attempting to print, in scenario 2 above, the whole window of the browser goes completely blank apart form the top-left "Show main window" button. The map is redrawn if the browser window is resized, or the "Main window" panel is revealed.

There are no apparent error messages in the browser/javascript error consoles.

If the "print icon" in the "Main window" panel is pressed, then it does appear to produce something that can be printed (the list of instructions, followed by a map that shows the whole route), but it doesn't seem to be possible to print "what can be seen in the browser" properly. i.e. if the user wants to print out a zoomed-in map of the end of the route, then that's not possible, because what's shown in the browser window can't be printed.

**Comment by TheMarex** [comment]
Outdated.
