### ISSUE TITLE
OSRM extract error

### ISSUE THREAD

**Issue by thangarajk** [Project-OSRM/osrm-backend#4002]
Hi,
I am getting the following error while running osrm-extract command in ubuntu 16.04

[info] Using script osrm-backend/profiles/car.lua
[info] Input file: new-york-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 2
[info] Parsing in progress..
[STXXL-MSG] STXXL v1.4.1 (prerelease/Debug)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
[info] input file generated by osmium/1.5.1
[info] timestamp: 2017-05-02T20:44:00Z
terminate called after throwing an instance of 'osrm::util::exception'
  what():  Error opening data/new-york-latest.osrm.timestamp
Aborted (core dumped)

I tried older version of osm.pbf file and increased my RAM size but same error.

**Comment by oxidase** [comment]
@thangarajk osrm does not show detailed OS error messages. Pls, could you add an output of 
`strace -e open ./osrm-extract -p ../profiles/car.lua map.osm`

**Comment by thangarajk** [comment]
@oxidase i tried your command and getting following details
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libbz2.so.1.0", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libexpat.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/liblua5.2.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/libstxxl.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libtbb.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libgomp.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libicui18n.so.55", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libicuuc.so.55", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libicudata.so.55", O_RDONLY|O_CLOEXEC) = 3
open("/sys/devices/system/cpu", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/proc/meminfo", O_RDONLY)         = 3
[info] Using script osrm-backend/profiles/car.lua
open("/usr/lib/x86_64-linux-gnu/libirml.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
[info] Input file: new-york-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 2
open("data/new-york-latest.osm.pbf", O_RDONLY) = 3
[info] Parsing in progress..
open("stxxl.log", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
open("stxxl.errlog", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
[STXXL-MSG] STXXL v1.4.1 (prerelease/Debug)
open("./.stxxl", O_RDONLY)              = -1 ENOENT (No such file or directory)
open("/home/ubuntu/.stxxl", O_RDONLY)   = -1 ENOENT (No such file or directory)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
open("/var/tmp/stxxl", O_RDWR|O_CREAT|O_DIRECT, 0660) = 4
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
open("osrm-backend/profiles/car.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/access.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/access.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/set.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/set.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/sequence.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/sequence.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/handlers.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/handlers.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/guidance.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/guidance.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/tags.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/tags.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/destination.lua", O_RDONLY) = 5
open("/srv/osrm/osrm-backend/profiles/lib/destination.lua", O_RDONLY) = 5
[info] input file generated by osmium/1.5.1
[info] timestamp: 2017-05-02T20:44:00Z
open("data/new-york-latest.osrm.timestamp", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
terminate called after throwing an instance of 'osrm::util::exception'
  what():  Error opening data/new-york-latest.osrm.timestamp
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=1522, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)

**Comment by oxidase** [comment]
There are some problems with file permissions
```
open("stxxl.log", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
open("stxxl.errlog", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
open("data/new-york-latest.osrm.timestamp", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
```
probably write access is missing, but it is not related to OSRM

**Comment by thangarajk** [comment]
thank you oxidase, problem with root Permission

**Comment by bakshiavinash** [comment]
Hi,
I am getting the following error while running osrm-extract command in ubuntu 16.04 , I have downloaded map.xml 
 
`ubuntu@~/osrm-backend$ osrm-extract map.xml -p profiles/foot.lua
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script profiles/foot.lua
[info] Input file: map.xml
[info] Profile: foot.lua
[info] Threads: 2
[info] Parsing in progress..
[info] input file generated by Overpass API 0.7.54.13 ff15392f
[info] timestamp: n/a
[info] Using profile api version 2
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Parsing finished after 0.005743 seconds
[info] Raw input contains 0 nodes, 0 ways, and 0 relations, 0 restrictions
terminate called after throwing an instance of 'osrm::util::exception'
  what():  There are no edges remaining after parsing.src/extractor/extractor.cpp:623
Aborted (core dumped)
`

Thanks in advance .

**Comment by danpat** [comment]
@bakshiavinash This ticket is closed, please don't add follow-up unrelated questions here.

That said, your problem is that there are no ways in your `map.xml` that have tags that are accepted by the `foot.lua` profile.  The line:

```
[info] Raw input contains 0 nodes, 0 ways, and 0 relations, 0 restrictions
...
what(): There are no edges remaining after parsing.src/extractor/extractor.cpp:623
```

indicates that there were no walkable ways in your `map.xml`, so the routing graph is empty.  Check that you have at least some `highway=` ways in your `map.xml`, or some other walkable way.
