### ISSUE TITLE
Build with Node support

### ISSUE THREAD

**Issue by humasak** [Project-OSRM/osrm-backend#4003]
hi..i have build OSRM in Mac. When i tried to execute this command: cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_NODE_BINDINGS=On -DENABLE_MASON=On, i got result:
-- Enabling mason
-- Building on a 64 bit system
CMake Warning at CMakeLists.txt:171 (message):
  GNU gold linker isn't available.

-- Configuring OSRM in release mode
-- Configuring release mode optimizations
-- Using unknown linker, not setting linker optimizations
-- Set Architecture to x64 on OS X
-- linking against libc++
-- Installing dependencies via mason
-- Using ccache to speed up incremental builds
-- Building node_osrm
-- NodeJS: Using node, version v4.4.7
-- Configuring node_osrm bindings for NodeJs v4.4.7
-- node_osrm artifacts will be copied to: /Users/oak/osrm-backend-5.7.0/lib/binding
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/oak/osrm-backend-5.7.0/build

After that i go to /Users/oak/osrm-backend-5.7.0/lib/binding/ and i did not see any node_osrm artifacts there. What is solution for this?

**Comment by daniel-j-h** [comment]
Do you actually build the binaries? After `cmake` do you call `make`? Then the Node.js module and the required libraries should be in `lib/binding/*` - what's your use-case for building the Node.js bindings yourself, is `npm install osrm` not an option?

**Comment by humasak** [comment]
tks daniel. i tried it and success.

**Comment by daniel-j-h** [comment]
:tada:
