### ISSUE TITLE
How to take Road id from OSRM?

### ISSUE THREAD

**Issue by humasak** [Project-OSRM/osrm-backend#4004]
dear all,

i want to get osm id or (road id) from routing result. Is it possible to extract it in OSRM? Ho i can do it (if it is possible)?

**Comment by daniel-j-h** [comment]
Check out the docs and look out for the `annotations` option:

http://project-osrm.org/docs/v5.7.0/api/

using annotations you can get OSM IDs attached to the route response.

**Comment by linquize** [comment]
osm node ID but not way ID
