### ISSUE TITLE
Incorrect U-turn instruction 

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#4005]
For http://map.project-osrm.org/?z=16&center=52.200995%2C9.550055&loc=52.197195%2C9.558145&loc=52.201853%2C9.541964&hl=en&alt=0   [bearingsAreReversed](https://github.com/Project-OSRM/osrm-backend/blob/a9d3e6188403a39c7d501658e017780107eaff52/src/engine/guidance/collapse_scenario_detection.cpp#L151-L155) computes an angle between [reversed in-angle (165°) at the orange intersection and out-angle (135°) at the red intersection](https://gist.github.com/oxidase/a68b3f77d3719c7f8da6edc7f7be9d88) . The difference is 30° so [bearingsAreReversed](https://github.com/Project-OSRM/osrm-backend/blob/a9d3e6188403a39c7d501658e017780107eaff52/src/engine/guidance/collapse_scenario_detection.cpp#L31) returns true and later  `instruction = {type = OnRamp (5), direction_modifier = Right (2)}` is changed to `{type = Continue (2), direction_modifier = UTurn (0)}`

The expected behavior is `OnRamp,Right` instruction.

**Comment by MoKob** [comment]
This is solved by now:

![screen shot 2017-06-15 at 10 37 35 2](https://user-images.githubusercontent.com/12932279/27172796-ba2aec10-51b6-11e7-996f-ddb5ae26a5bd.png)
