### ISSUE TITLE
Reverse coordinates order

### ISSUE THREAD

**Issue by sirpope** [Project-OSRM/osrm-backend#4012]
Since v5.0, the Route object returns coordinates as an Array of Longitude, Latitude. Wouldn't it be more feasible to return them as an Array of Latitude, Longitude, as most of GIS/Mapping software expect the first coordinate in a pair to be the Latitude?

`[[26.008739,44.94802],[26.008756,44.947965],[26.008761,44.947863],[26.008758,44.947793],[26.008746,44.947723],[26.008719,44.947615],[26.008589,44.947479],[26.008349,44.947237],[26.007791,44.947496],[26.007492,44.947648],[26.006924,44.947881],[26.006084,44.948191],[26.005683,44.948345],[26.004406,44.948861],[26.004706,44.949156],[26.005071,44.949515]]`

**Comment by daniel-j-h** [comment]
Not going into an argument about latitude / longitude order here :) It is longitude, latitude and we can't and won't break the API. You can easily switch order on the client side as the API consumer.

Closing as not actionable for us.

**Comment by danpat** [comment]
Just a couple of notes on top of this:

  1) When you specify `geometries=geojson`, we give back valid GeoJSON data, which specifies `longitude,latitude` as the normal order.  We comply with that standard.  Any software that understands the GeoJSON standard will expect this order.
  2) If you specify `geometries=polyline` or `geometries=polyline6`, we give back an [encoded polyline](https://developers.google.com/maps/documentation/utilities/polylineutility), and *this* standard specifies `latitude,longitude`, and we do the correct thing here too.

@sirpope Hope that helps clarify why things are the way they are.  We didn't just make this stuff up :-)

Note that if you're using Javascript to process the response JSON, swapping the coordinates is a pretty short one-liner:

    var latloncoords = result.routes[0].geometry.coordinates.map(c => [c[1],c[0]]);
