### ISSUE TITLE
Debug tiles are missing rate attribute on edges

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#4018]
Now that we support #77 , we need to be able to visualize values for route debugging.

The debug tiles expose the following attributes for road segments:

  - speed
  - is_small
  - datasource
  - weight
  - duration
  - name

Missing from this list is `rate`, which is `length / weight`.  We have `weight`, but we have no normalize value (like `speed) that makes it easy to see where penalized weights are in play.

The task here is to add the `rate` attribute - it should be a simple duplication of how the `speed` is calculated and exposed.

**Comment by daniel-j-h** [comment]
Related: https://github.com/Project-OSRM/osrm-backend/issues/3793

**Comment by daniel-j-h** [comment]
@danpat https://github.com/Project-OSRM/osrm-backend/issues/4162 added rate to the debug tiles; anything left here that you want to add? Can you update your comment or close here please.

**Comment by danpat** [comment]
Ah, thanks for the reminder.  This is done.
