### ISSUE TITLE
Expose Map Matching `gaps` and `tidy` parameters in Node.js bindings

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4021]
With [v5.7](https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#570) there are two new map matching options (impl. was done in https://github.com/Project-OSRM/osrm-backend/pull/3815):
- option gaps=split|ignore to enable/disbale track splitting
- option tidy=true|false to simplify traces automatically

neither is exposed in the Node.js bindings.

Tasks:

- [ ] parse flags and set options [here](https://github.com/Project-OSRM/osrm-backend/blob/2f02384d22a7e5caac9e1918961d114158fab532/include/nodejs/node_osrm_support.hpp#L968-L1022)
- [ ] write docs in `docs/nodejs/api.md`

**Comment by oxidase** [comment]
Closed via  #4145
