### ISSUE TITLE
Master segfaults in osrm-extract on planet

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4024]
On the demo server running `osrm-extract from master segfaults on the planet.

> Segmentation fault

Without further details. The kernel shows a protection violation:

> kernel: [38657.099205] traps: osrm-extract[21443] general protection ip:5b327d sp:7ffccdd89a90 error:0 in osrm-extract[400000+310000]

Instruction pointer was `0x5b327d` when we got killed.

I could get my hands on the binaries leading to the segfault:

```asm
(gdb) info symbol 0x5b327d
osrm::extractor::guidance::RoundaboutHandler::invalidateExitAgainstDirection(unsigned int, unsigned int, osrm::extractor::guidance::Intersection&) const + 365 in section .text

(gdb) x/i 0x5b327d
   0x5b327d <osrm::extractor::guidance::RoundaboutHandler::invalidateExitAgainstDirection(unsigned int, unsigned int, osrm::extractor::guidance::Intersection&) const+365>:
    movzbl 0x10(%rax),%eax
```

https://github.com/Project-OSRM/osrm-backend/blob/a5bfcd876f601861958f0b4955f35292b45373cf/src/extractor/guidance/roundabout_handler.cpp#L106-L173

Introduced in https://github.com/Project-OSRM/osrm-backend/pull/3980

Unfortunately I could not find a core dump so I don't have a location or a concrete scenario ready.

cc @freenerd @oxidase

**Comment by oxidase** [comment]
The failing case is http://www.openstreetmap.org/way/149545759 , extracted osm 
[map.osm.txt](https://github.com/Project-OSRM/osrm-backend/files/992711/map.osm.txt)

**Comment by daniel-j-h** [comment]
@oxidase fixed this in https://github.com/Project-OSRM/osrm-backend/pull/4031 🙇  - closing as resolved.
