### ISSUE TITLE
How can I run on debugging mode?

### ISSUE THREAD

**Issue by emregurler** [Project-OSRM/osrm-backend#4026]
Hi friends, I followed the instructions which are in documentation and I finally build the project. Now, i can request some locations to program on the browser, and it returns me the json output.
This machine gives duration matrix,  I need distance matrix of locations which are requested. I dont know how you can calculate it, but i guess ,first you should find the distance between locations somewhere in code. Am I thinking wrong ? If it is true, machine can generate distance matrix of locations that i need. I have approximately 2000 places. 
On the other hand, i am trying to run on debug mode, but I havent found the right way yet. I tried both linux and windows OS, and worked on VS 2017 and CLion IDEs. If you know solution for me, i would like to be informed about it. Thank you

**Comment by daniel-j-h** [comment]
If you want to optimize based on duration and have distance in the response, check https://github.com/Project-OSRM/osrm-backend/pull/2764. If zou want to optimize based on distance and have distance in the response you can adapt the `car.lua` profile.

For debug binaries,

    cmake .. -DCMAKE_BUILD_TYPE=Debug

**Comment by emregurler** [comment]
Thank you for your fast reply. I read all pages related with #2764, but i still in trouble. I am interested in niemeier-PSI's work. I downloaded the project from his page and I built it. Although I can get same result(durations table), i couldnt get distance table. I wrote the payload code after cmake installization and contracting the map. What is missing here? What is done wrong? I appreciate if you guide me.

**Comment by daniel-j-h** [comment]
@emregurler 

> I am interested in niemeier-PSI's work.

then please keep the discussion in pull request https://github.com/Project-OSRM/osrm-backend/pull/2764.

**Comment by emregurler** [comment]
My main language is c# and java, so I understand this code just slightly. Can you please let me know how should i manipulate car.lua in current version. Which lines should be changed? I will be very happy for it, because I have been reading lots of linked pages for a week.

**Comment by daniel-j-h** [comment]
Distance values for the table API are only available in this branch: https://github.com/Project-OSRM/osrm-backend/pull/2764

It sounds like you want to optimize based on distance? Then check https://github.com/Project-OSRM/osrm-backend/issues/1831.

**Comment by SericWong** [comment]
how can I get the response.debug ?
