### ISSUE TITLE
MLD vs CRP and Microsoft patents

### ISSUE THREAD

**Issue by dmitry-akimov-dXgjvQjNiMuVYecJ** [Project-OSRM/osrm-backend#4032]
Greetings, dear OSRM contributors. Keep up the great work.

I could not find anything with keywords "patent" or "Microsoft" in the discussions for this project, but you have likely discussed this already, so excuse me in advance for bringing up the same topic again.

The question is how close is the MLD implementation in OSRM to the [CRP algorithm](https://www.microsoft.com/en-us/research/publication/customizable-route-planning/) (implementation on GitHub: [https://github.com/michaelwegner/CRP](https://github.com/michaelwegner/CRP)) and could it possibly be affected by the following Microsoft's patents:

* [Customizable route planning, US20120310523A1](https://patents.google.com/patent/US20120310523A1/en)
* [Query scenarios for customizable route planning, US20140107921A1](https://patents.google.com/patent/US20140107921A1/en)
* [Customizable route planning using graphics processing unit, US20150356759A1](https://patents.google.com/patent/US20150356759A1/en)

Best regards

**Comment by dmitry-akimov-dXgjvQjNiMuVYecJ** [comment]
It's been over a month now. Can anyone give me a heads up on this question: is it wrong, irrelevant, somebody is looking into it, nobody cares, etc.?

**Comment by dmitry-akimov-dXgjvQjNiMuVYecJ** [comment]
Would be nice to hear someone's thoughts on this.

**Comment by dmitry-akimov-dXgjvQjNiMuVYecJ** [comment]
@emocanu Great news!

**Comment by insford** [comment]
[Customizable route planning, US20120310523A1](https://patents.google.com/patent/US20120310523A1/en) is abandoned
but, [Query scenarios for customizable route planning, US20140107921A1](https://patents.google.com/patent/US20140107921A1/en) is activated

I think both patents are similar to each other.
is it a problem?

**Comment by dmitry-akimov-dXgjvQjNiMuVYecJ** [comment]
This seems kind of complicated. I am not a lawyer, but an abandoned patent should become public domain. The [Query scenarios for customizable route planning, US20140107921A1](https://patents.google.com/patent/US20140107921A1/en) also claims the algorithm itself, but it was filed later, also the [Customizable route planning, US20120310523A1](https://patents.google.com/patent/US20120310523A1/en) is already abandoned and should have gone into public domain, so it should be prior art now. One would have to consult with a lawyer to tell for sure.

These kinds of software patents should burn in Hell, that's what I can say for sure.

**Comment by dmitry-akimov-dXgjvQjNiMuVYecJ** [comment]
Okay. I read more about it, and it seems that the patent may be actually active on the algorithm.  The [Query scenarios for customizable route planning, US20140107921A1](https://patents.google.com/patent/US20140107921A1/en) was filed before the [Customizable route planning, US20120310523A1](https://patents.google.com/patent/US20120310523A1/en) was published. The list of authors is different though, which is important.

I am totally not a lawyer, so now I have no clue on what to think.

**Comment by systemed** [comment]
The patent appears to have expired earlier this year "Due to NonPayment of Maintenance Fees": https://patentcenter.uspto.gov/applications/13649114

**Comment by tenindra** [comment]
Came across this randomly and leaving some additional info. FYI, there is a research paper on a method called ROAD pre-dating CRP by several years: https://dl.acm.org/doi/epdf/10.1145/1458082.1458260 (plus there is a longer follow-up journal paper in TKDE 2012)

The idea of a multi-level Dijkstra algorithm (i.e., hierarchical partitioning with shortcuts between partition border vertices) appears to have originated in the ROAD paper
