### ISSUE TITLE
Foot and bike are returning the same route as car

### ISSUE THREAD

**Issue by costales** [Project-OSRM/osrm-backend#4034]
Hi, I'm trying to get routes for foot or bike, but they are the same as in car.
For example:
```
http://router.project-osrm.org/route/v1/car/-73.9865811,40.7305991;-73.99772644042967,40.753824164148995
http://router.project-osrm.org/route/v1/foot/-73.9865811,40.7305991;-73.99772644042967,40.753824164148995
http://router.project-osrm.org/route/v1/bike/-73.9865811,40.7305991;-73.99772644042967,40.753824164148995
```
They are returning the same route.

But because of the documentation:
http://project-osrm.org/docs/v5.7.0/api/#general-options
They should return the right route. Am I missing something?

Thanks in advance!

**Comment by danpat** [comment]
@costales The demo server only services up the `car` profile - changing the profile name in the URL has no effect.

If you want bike or walk routing, you'll need to set up your own server.

**Comment by costales** [comment]
Thanks for the info @danpat :)

**Comment by ingphillip** [comment]
> @costales The demo server only services up the `car` profile - changing the profile name in the URL has no effect.
> 
> If you want bike or walk routing, you'll need to set up your own server.

hello and good day,

Exists any book or blog tha speak about intall the tree types of routes, becaouse when extract the data for example by the car and then extract the info of the bicycle the result is the same only return a path to bicycle, not is important what is the url rute, allways return the last instalation type bicycle or foot.

Thanks

**Comment by danpat** [comment]
@ingphillip If you prepare multiple datasets with different Lua profiles, you will need to run multiple `osrm-routed` servers, one for each, typically listening on a different TCP port.

**Comment by ingphillip** [comment]
> @ingphillip If you prepare multiple datasets with different Lua profiles, you will need to run multiple `osrm-routed` servers, one for each, typically listening on a different TCP port. One `osrm-routed` process cannot serve multiple profiles.

yes, tanks for you response, when intent up the other instance to byke for example, throw the next exception

[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.ramIndex[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.fileIndex[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.hsgr[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.nodes[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.edges[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.core[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.geometry[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.timestamp[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.datasource_indexes[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.datasource_indexes[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.names[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.properties[0m
[33m[warn] Missing/Broken File: C:\osrm-data\bike\colombia-latest.osrm.icd[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.ramIndex" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.fileIndex" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.hsgr" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.nodes" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.edges" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.core" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.geometry" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.timestamp" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.datasource_names" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.datasource_indexes" is not found[0m
[33m[warn] "C:\osrm-data\bike\colombia-latest.osrm.names" is not found[0m

**Comment by danpat** [comment]
@ingphillip Those errors mean that your data processing step probably failed.

**Comment by ingphillip** [comment]
> @ingphillip Those errors mean that your data processing step probably failed.

Oh excueme, I have one error, working fine now! thanks @danpat

**Comment by zugspitze** [comment]
@danpat the demo server has options for biking and foot. I am not sure why you say it services only for car.

**Comment by danpat** [comment]
@zugspitze when my comment was written, in 2017, it was correct, we only hosted the `car` profile.

**Comment by zugspitze** [comment]
@danpat Thanks a lot for the quick reply. I had similar issues as routing with `foot` profile using Demo server. I used the following API for the documentations:

```
curl 'http://router.project-osrm.org/route/v1/foot/12.932971,47.569928;12.921235,47.554053?annotations=true&overview=full' | jq "."
```

It is not able to find this hiking route, do you have any ideas what I did wrong here. In the demo server, they are using another API for routing (https://routing.openstreetmap.de/routed-foot/route/v1/driving/10.986297,47.421215;11.047812,47.429497?overview=false) that works.

Can you please tell me if I am doing something wrong.

**Comment by kux** [comment]
@danpat If the bike and foot profiles are not available and a client makes a request for them, wouldn't it make more sense to return an error instead of doing a fallback to the car profile?

Otherwise the client falsely assumes that the bike profile works and blindly uses inefficient routes.

**Comment by DiarmaidNagle** [comment]
There still seems to be an issue with the server providing identical metrics for driving, walking and cycling transport modes. In my case, switching to routing.openstreetmap.de resolves the problem and provides distinct results for driving, cycling, and walking.
If others are still seeing this, it might be worth reopening or documenting the server-specific behavior.

**Comment by SignorTacco** [comment]
> There still seems to be an issue with the server providing identical metrics for driving, walking and cycling transport modes. In my case, switching to routing.openstreetmap.de resolves the problem and provides distinct results for driving, cycling, and walking. If others are still seeing this, it might be worth reopening or documenting the server-specific behavior.

Thank you!!! It works now
