### ISSUE TITLE
Segfault on „Generating edge-expanded edges“

### ISSUE THREAD

**Issue by timojuez** [Project-OSRM/osrm-backend#4038]
Hi people,

I try to osrm-extract the osm-file and get a segmentation fault. What can I do please?

Thank you,

Timo

Debug output:
Starting program: /home/timo/Dokumente/studium/aktuelles Semester/bewegungsprofile/osrm/osrm-backend/build/osrm-extract Dresden.osm -p ../profiles/foot.lua
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[info] Using script ../profiles/foot.lua
[info] Input file: Dresden.osm
[info] Profile: foot.lua
[info] Threads: 2
[New Thread 0xb592db40 (LWP 27316)]
[New Thread 0xb4efeb40 (LWP 27317)]
[info] Parsing in progress..
[STXXL-MSG] STXXL v1.4.1 (prerelease/Debug)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
[info] input file generated by osmconvert 0.8.4
[info] timestamp: n/a
[New Thread 0x9a25eb40 (LWP 27318)]
[Thread 0xb592db40 (LWP 27316) exited]
[Thread 0xb4efeb40 (LWP 27317) exited]
[info] Parsing finished after 35.7135 seconds
[info] Raw input contains 2587351 nodes, 445129 ways, and 0 relations
[New Thread 0xb592db40 (LWP 27335)]
[info] Sorting used nodes        ... [New Thread 0xa742bb40 (LWP 27336)]
ok, after 0.577053s
[info] Erasing duplicate nodes   ... ok, after 0.468767s
[info] Sorting all nodes         ... ok, after 3.29639s
[info] Building node id map      ... ok, after 1.90283s
[info] setting number of nodes   ... ok
[info] Confirming/Writing used nodes     ... ok, after 1.51424s
[info] Processed 557704 nodes
[info] Sorting edges by start    ... ok, after 1.99433s
[info] Setting start coords      ... ok, after 3.16936s
[info] Sorting edges by target   ... ok, after 2.2304s
[info] Computing edge weights    ... ok, after 4.27239s
[info] Sorting edges by renumbered start ... ok, after 3.53869s
[info] Writing used edges       ... ok, after 0.151055sProcessed 605710 edges
[info] Sorting used ways         ... ok, after 0.331718s
[info] Sorting 0 restriction. by from... ok, after 0s
[info] Fixing restriction starts ... ok, after 1e-06s
[info] Sorting restrictions. by to  ... ok, after 0s
[info] Fixing restriction ends   ... ok, after 0s
[info] number of restrictions saved to memory: 0
[info] number of conditional restrictions written to disk: 0
[info] writing street name index ... ok, after 0.051161s
[info] extraction finished after 63.2622s
[info] Generating edge-expanded graph representation
[info] Importing number_of_nodes new = 557704 nodes 
[info]  - 2688 bollard nodes, 1104 traffic lights
[info]  and 605710 edges 
[info] Validating loaded edges...
[info] Graph loaded ok and has 605710 edges
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.302031
[info] Edge compression ratio: 0.357349
[info] Generating edge expanded nodes ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 605710 nodes in edge-expanded graph
[info] Generating edge-expanded edges 
[info] [assert][3048421760] /home/timo/Dokumente/studium/aktuelles Semester/bewegungsprofile/osrm/osrm-backend/src/extractor/guidance/intersection_generator.cpp:373
in: osrm::extractor::guidance::IntersectionView osrm::extractor::guidance::IntersectionGenerator::TransformIntersectionShapeIntoView(NodeID, EdgeID, const osrm::extractor::guidance::IntersectionShape&, const osrm::extractor::guidance::IntersectionShape&, const std::vector<osrm::extractor::guidance::IntersectionNormalizationOperation>&) const: intersection_view[0].angle >= 0. && intersection_view[0].angle < std::numeric_limits<double>::epsilon()
terminate called without an active exception

Thread 1 "osrm-extract" received signal SIGABRT, Aborted.
0xb7fd9cf9 in __kernel_vsyscall ()
(gdb)

**Comment by daniel-j-h** [comment]
Which OSRM version are you on? v5.7 or master?

Where did you get the OSM file from?

**Comment by timojuez** [comment]
To get the OSRM version I did a git clone of the repo today. I cannot use the docker because of my 32-bit system.

The OSM-file comes from http://download.bbbike.org/osm/bbbike/Dresden/. I also tried sachsen-latest.osm.pbf from https://download.geofabrik.de/europe/germany.html resulting in the same error.

**Comment by oxidase** [comment]
@timojuez thanks for report! The issue will be fixed in 5.7.1, related PR https://github.com/Project-OSRM/osrm-backend/pull/4031

**Comment by oxidase** [comment]
Reproduced the issue with 32bit build at http://www.openstreetmap.org/?mlat=51.0166&mlon=13.737#map=19/51.0166/13.737
```
LD_LIBRARY_PATH=/opt/i386/usr/lib:/opt/i386/usr/lib/i386-linux-gnu/ ./osrm-extract -p ../../profiles/foot.lua sachsen-latest.osm.pbf 
[info] [Location] http://www.openstreetmap.org/?mlat=51.0166&mlon=13.737#map=19/51.0166/13.737
[assert][4113916480] /home/miha/mapbox/osrm-backend/src/extractor/guidance/intersection_generator.cpp:375
in: osrm::extractor::guidance::IntersectionView osrm::extractor::guidance::IntersectionGenerator::TransformIntersectionShapeIntoView(NodeID, EdgeID, const osrm::extractor::guidance::IntersectionShape&, const osrm::extractor::guidance::IntersectionShape&, const std::vector<osrm::extractor::guidance::IntersectionNormalizationOperation>&) const: intersection_view[0].angle >= 0. && intersection_view[0].angle < std::numeric_limits<double>::epsilon()
```

**Comment by daniel-j-h** [comment]
This got fixed in https://github.com/Project-OSRM/osrm-backend/issues/4053 for 32 bit environments.

Closing as resolved here.

@timojuez can you give it a try again with master and re-open when you still see issues.
