### ISSUE TITLE
Suggest update to wiki Build-OSRM - Mac build

### ISSUE THREAD

**Issue by Skippern** [Project-OSRM/osrm-backend#4042]
I wasn't able to install with the suggestions in the wiki (Mac OS X 10.11 El Capitan), but after manually installing stxxl[0] (downloaded source from sourceforge and compiled), and the rest of the dependencies installed with MacPorts, I was able to  get it working.

[0] https://sourceforge.net/projects/stxxl/files/stxxl/

```
port install build-essential git cmake pkg-config libbz2 libxml2 libzip boost lua tbb
```

Compiling instructions as Linux

**Comment by daniel-j-h** [comment]
Did you try using mason on macOS or brew for all dependencies?

If all you want to do is _use_ osrm we provide ready-to-use Docker images for both backend as well as frontend (https://hub.docker.com/r/osrm/) and I think there is also a brew formula for installing osrm directly.

**Comment by Skippern** [comment]
I downloaded the latest release (v5.7.0), and could not find the files for Mason, so didn't try Mason no.

MacPorts is an alternative to homebrew, like difference between apt-get and yum in different flavours of Linux

Tried docker, but didn't work for me, always terminated with some obscure error messages.

**Comment by daniel-j-h** [comment]
Thanks, feel free to add your instructions to the macOS section in the Wiki 👍 

Closing here already.

**Comment by Skippern** [comment]
Added to wiki

**Comment by daniel-j-h** [comment]
Thank you!
