### ISSUE TITLE
New Service ( Tour )

### ISSUE THREAD

**Issue by ReneBrueggemann** [Project-OSRM/osrm-backend#4045]
Hey there, as a part of my master thesis, I would like to write a new service named "round_route" or "tour". The goal is to find a good jogging or cycling route with one starting node (end node equals starting node) and a specific length. I got a [Paper](http://i11www.iti.kit.edu/extra/publications/gpwz-ecjr-13.pdf) from Gemsa et al. about "Efficient Computation of Jogging Routes" and the  [bachelor thesis](https://i11www.iti.kit.edu/_media/teaching/theses/ba-zuendorf-12.pdf) from Tobias Zündorf which describes the problem as well and gave some solving strategies.
 
At first I tried to figure out the involved parts:

* engine/api/tour_parameter.hpp
* engine/engine.hpp
* engine/plugins/tour.hpp
* engine/plugins/tour.cpp
 
* osrm/osrm.hpp
* osrm/osrm.cpp
* osrm/tour_parameters.hpp
 
* server/api/tour_parameters_grammar.hpp
* server/api/parameter_parser.cpp
* server/service/tour_service.hpp
* server/service/tour_service.cpp
* server/service/service_handler.cpp
 

Algorithm 4.5 is a heuristic solution where three points are sought for our tour.
The distance of each leg should be between _len ∈ [ (1-e) * len/4 , (1+e) * len/4 ]_ and the result-route/tour is the shortes path between the four points, e.g.:
_ShortestPath( (s , p1, m, p2, s) ) = SP(s, p1) o SP(p1, m) o SP(m, p2) o SP(p2, s)_

State of the implementation:
Like the TripService, the TourService inherits from the BaseService/Plugin and RouteGrammar/Api/Parameters.

inherits from:

TourService		<- 	BaseService
TourPlugin		<-	BasePlugin
TourGrammar		<- 	RouteGrammar
TourApi			<-	RouteApi
TourParameters	<-	RouteParameters 

Can you give me some advises and feedback to create my service in a way that can get merged?

**Comment by ReneBrueggemann** [comment]
@danpat Only the length is required as a parameter through the url. 

> do you intend on having it operate on the existing graphs?

Yes I would like to operate on the existing graph if there are solutions for the problems below.


> Have you put any thought into how it will be implemented on the CH graph, or will this plugin only work on the base graph for the MLD algorithm?

Thats what I try to figure out next / currently. It would be nice if it works on both kind of graphs.


First problem is, that I need a dijkstra-algorithm like
`(w', c', parent') <- dijkstra(s, (1+e)*l/4)`

- c'[v] is the distance from s to v ( see Problem 2 )
- w'[v] = c'[v] / weight ( current distance )
- parent'[v] = u with distance(s - u - v) < (1+e) * len/4 and u ∈ V

Another problem might be, that I need the length of the leg before it was divided by the weight, to decide which nodes are candidates for further calculation.  
`K <- { v ∈ V | c'[v] ∈ [ (1-e) * len/4 , (1+e) * len/4 ] `
I guess w'[v] is the current distance and weight must be multiplied.

Thanks for your help @danpat  :)

**Comment by SiarheiFedartsou** [comment]
Stale.
