### ISSUE TITLE
How to improve accuracy of map matching 

### ISSUE THREAD

**Issue by havardl** [Project-OSRM/osrm-backend#4048]
Hi, and thank you very much for a great open source project! 

I'm currently working on map matching a variety of bicycle trips with OSRM, but I'm not really getting any improved results compared to the original tracks. I've tried to pre-process with both the car.lua and bicycle.lua profiles, with more or less the same results for the given tracks. I've tried to use data extracts from Geofabrik and BBBike (for Denmark/Copenhagen), also with the same result. So I just wanted to check if anyone has some tips to how to improve the accuracy of the map matching feature? 

Below is an example of where I'm currently at, where the purple line is the original track, the yellow is the track suggested by OSRM and the red line is the actual traveled track.

![osrm - bike](https://cloud.githubusercontent.com/assets/8808065/26073979/9f627c86-39b0-11e7-9623-3301d5d36f3e.png)

This was generated with the following query: 
```
http://localhost:5000/match/v1/bike/[coordinates]?timestamps=[timestamps]&overview=simplified&tidy=false&steps=false
```

Actually, the inclusion of time stamps did not increase accuracy. Is that expected behavior?

**Comment by danpat** [comment]
@havardl what part of the `/match` API response are you looking at?

The yellow line looks like the path of the snapped coordinates.  The full geometry of the path between each snapped coordinate is available in the `matchings` array object in the response.  It looks like you've just plotted the `tracepoints` data, which is not the full route.

**Comment by havardl** [comment]
Ah, I see @danpat . My mistake, I thought the tracepoints array was the returned set of matched coordinates. Thanks for the fast feedback!

However, what role does the timestamps play in the algorithm? Seems I can run the map matching without them, but I imagine the increase accuracy?

**Comment by danpat** [comment]
@havardl the timestamps help the algorithm recognize when candidate matches are unreasonable - If you don't supply timestamps, the algorithm assumes that the coordinates are evenly spaced (in time).  If your data isn't at regular intervals, you may get fewer bad matches.

**Comment by havardl** [comment]
Given a date (2017-04-20 19:30:53) - is there a specific way I should generate the timestamps? I've tried in a couple of different ways, but including timestamps does not seem to improve the matched route, there are actually more split routes when I include the timestamps.

**Comment by danpat** [comment]
@havardl well, ideally you will use the real timestamps

By default, the API will split traces if the distance between points is > 2000m.

https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/routing_algorithms/map_matching.cpp#L31-L33

if you spply timestamps, this changes to the "median sample time x max_speed_for_map_matching" (which is baked into your data by the Lua profile, from https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L12, defaults to 180km/h).

The timestamp values are in Unix seconds-since-epoch:

```
$ date
Tue May 16 14:25:20 PDT 2017
$ date +%s
1494969923    <- use this value
```

**Comment by daniel-j-h** [comment]
Closing this as not actionable on our side. Feel free to re-open if needs be.

🐝
