### ISSUE TITLE
--max-matching-size is not honored, getting TooBig as response code.

### ISSUE THREAD

**Issue by amit1rrr** [Project-OSRM/osrm-backend#4051]
Hey,

I want to enable OSRM map matching for large input trace. I am starting OSRM with max-matching-option below

```
osrm-routed india-latest.osrm --max-matching-size=3000
```

As soon as I restart OSRM and try a large query in the browser, it succeeds. After a while I see responses with "TooBig" response codes in my application logs where input trace size is well below 3000. When I try the same query again in my browser then it fails until I restart OSRM again. It's almost like the configuration got reversed to default of 100 somehow in the flow. 

Any ideas?

I'm open to changing the value in one of the source files as a quick fix.

**Comment by daniel-j-h** [comment]
The only location where the map matching limit is enforced is [here](https://github.com/Project-OSRM/osrm-backend/blob/16f492026aeb6cf87bfa226e6c59a64282a3d173/src/engine/plugins/match.cpp#L126-L131) where the `TooBig` response code is generated. Can you double check your queries - there is no mutable state inside osrm-routed wrt. limits. Once osrm-routed started the limits are fixed.

**Comment by amit1rrr** [comment]
Thank you for quick response. If I remove this `if` condition in my local match.cpp and restart osrm, would it take effect or do I have to build again etc. Please excuse my ignorance with cpp packages.


I double checked the queries they look fine. New observation I just noticed is: Requests that are failing with Python urllib2 client are succeeding when tried from browser. Seems unlikely, but any logic based on client header/type etc?

**Comment by daniel-j-h** [comment]
If you modify the source then yes you have to build again,

    make

> Requests that are failing with Python urllib2 client are succeeding when tried from browser.

This more and more sounds like a logic problem in your program - are you sure you're not querying e.g. the demo server on your Python app by chance? And no we don't set limits depending on client or any other HTTP header. As I said above once osrm-routed is running there is no way to modify the static limits. All requests pass the same code path.

**Comment by amit1rrr** [comment]
Hey,
It was my supervisord config which was re-running the osrm server with same old settings as soon as I killed it. So my new command (with max-matching-size) was not taking effect properly. 

Resolving.
