### ISSUE TITLE
Dynamic street blacklist due to temporal events

### ISSUE THREAD

**Issue by diegocando** [Project-OSRM/osrm-backend#4055]
Hi, I have a question, is it possible to have street blacklist during a call to a service, I mean like a part of street closure due to maintenance, natural disaster or something like that (a list of routes to avoid in the routing algorithm) to avoid modifications in the map source or reprocessing the whole map.

I’m getting familiar with the code to perform a modification if needed but it will surely take some time

If anyone can help with any lead with this particular that would be awesome

**Comment by daniel-j-h** [comment]
Blacklisting from the user-side via the API is not possible. What you  can do is make use of https://github.com/Project-OSRM/osrm-backend/wiki/Traffic but that needs to be done on the server side.

If that's not possible for your use-case you will have a bad time - with the way CH does pre-processing your use-case will not be possible and with MLD the [Avoid-X feature](https://github.com/Project-OSRM/osrm-backend/issues/4006) is the closest. But even then pre-processing needs to know about this.

**Comment by diegocando** [comment]
Thank you Daniel, I'll check that (it's a good start) but I think I might be making a modification myself, anyway, thank you for the advice.

**Comment by danpat** [comment]
@diegocando as @daniel-j-h pointed out - with the CH algorithm, you *will* need to reprocess the graph if you adjust its shape (remove edges) or change weights.  You will invalidate the search graph if you don't re-process, and routing results will be incorrect.

You might have more luck if you implement a naive Dijkstra search on the base graph available with MLD processed data, but you will need to add the flags you want to the base graph (not easy), and query speed will be slow - fast queries generally require a pre-processing step.

**Comment by daniel-j-h** [comment]
Good luck! ✨
