### ISSUE TITLE
'Route' Requests Are Mostly Timing Out

### ISSUE THREAD

**Issue by dyanikoglu** [Project-OSRM/osrm-backend#4058]
`curl 'http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false'
`

As an example, I'm trying to get response for this request on terminal(and tried sending request directly on a browser), but my requests are mostly timing out. Is this a server related issue or a problem on my network?

My personel project calculates 40-50 routes per a special user request, it's unable to do this job because of this request timed out problem. It was working about 1 week ago.

If it's needed, I can attach my operating system & hardware details.

**Comment by oxidase** [comment]
@dyanikoglu thanks for reporting! The `osrm-routed` service was restarted. 
Please note that it is not stable and runs on the master branch https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

**Comment by dyanikoglu** [comment]
Can be marked as resolved, timeout problem is resolved.
