### ISSUE TITLE
Edge-weights update warning cucumber test is flunky

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#4065]
Repeated execution of `features/options/contract/edge-weight-updates-over-factor.feature` will cause `https://travis-ci.org/Project-OSRM/osrm-backend/jobs/233362124#L2296` as the test will modify the `.geometry` file in-place.

This will cause the check to fail since the old value is already the high value.

**Comment by oxidase** [comment]
Closed via #4199
