### ISSUE TITLE
Fix weights of start nodes and check related issues

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#4069]
At the moment there are some issues that looks different but have a common problem:

* https://github.com/Project-OSRM/osrm-backend/issues/3953
* https://github.com/Project-OSRM/osrm-backend/pull/4019 (it is not real fix, but a workaround to prevent UB)
* https://github.com/Project-OSRM/osrm-backend/issues/3429
* probably https://github.com/Project-OSRM/osrm-backend/issues/3647
* https://github.com/Project-OSRM/osrm-backend/issues/2016
* https://github.com/Project-OSRM/osrm-backend/issues/3969
* https://github.com/Project-OSRM/osrm-backend/blob/5c61f00ffa18a676de91c7869c831d73dd3d6162/include/engine/guidance/assemble_geometry.hpp#L101-L103 as part of https://github.com/Project-OSRM/osrm-backend/issues/3606

The problem is in computation weights for the starting edge-based-node and weights for its neighboors that are computed as `-weight(as) + [weight(ab) + turn_penalty(adc)]` for segments like `a---s---b-------c`. The reason for this is the total [`EdgeBasedEdge::EdgeDate::weight`](https://github.com/Project-OSRM/osrm-backend/blob/5c61f00ffa18a676de91c7869c831d73dd3d6162/src/extractor/edge_based_graph_factory.cpp#L503-L504), so it is not possible to compute directly `weight(sb) + turn_penalty(adc)`.  Another problem occurs if at least one segment in `as` has `INVALID_EDGE_WEIGHT` value, so `weight(as)` can not be computed and there is no possibility to compute route even if `weight(sb)` has a valid value.

The solution can be as discussed with @TheMarex:
*  ~~adding `TurnPenalty` and `TurnDuration` to [`EdgeBasedEdge::EdgeData`](https://github.com/Project-OSRM/osrm-backend/blob/5c61f00ffa18a676de91c7869c831d73dd3d6162/include/extractor/edge_based_edge.hpp#L47-L50) (+4 bytes per turn)~~ We already have this https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/datafacade/contiguous_internalmem_datafacade.hpp#L624-L634
* only filtering out edges with **all** `INVALID_EDGE_WEIGHT` segments (atm edges with **at least one** `INVALID_EDGE_WEIGHT` segment are filtered out of the base graph)
* inserting `weight(sb) + turn_penalty(adc)` initial values in heaps
* fixing self loops by treating `a---s----t--->b` special cases separately from the Dijkstra search, because of another case `a--xxx--s----t--xxx-->b` (here `xxx` are segments with `INVALID_EDGE_WEIGHT`)
* fixing unpacked path annotation and guidance post-processing for edge cases
* correct trimming of source and target points based on weights (if `sb=0`) but not distances

The issue implies checking the referenced tickets and their relatives.

**Comment by TheMarex** [comment]
One thing that came to my mind to circumvent the current problems we are having with CH and path unpacking:

Given an compressed edge `a--1--2--3---b` and turns `(a, b, c)`, `(b, a, d)` during updating we don't save the full weight of `weight(a,b) + penalty(a, b, c)` or `weight(b,a) + penalty(b, a, d)`, but first search for the last segment that is `INVALID_SEGMENT_WEIGHT` and save `weight(i, b) + penalty(a, b, c)`. (in the backward case we would use the first segment that is `INVALID_SEGMENT_ID` and save `weight(i, a) + penalty(b, a, d)`)

**Comment by TheMarex** [comment]
We encountered some edge cases here that made this work more complicated. Pushing to `5.9.0`.
