### ISSUE TITLE
Counting of service exits on service roundabouts

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#4075]
OSM has [13150 ways `["highway"="service"]["junction"="roundabout"];`](http://overpass-turbo.eu/s/peb) in which service exits will be suppressed and guidance instructions will be `"take the 1st exit"`. Most of the service roundabouts are located in large parking areas like [airports or hospitals](http://overpass-turbo.eu/s/pee) and guidance can be confusing in these areas. 

For http://map.project-osrm.org/?z=18&center=40.479392%2C-3.477795&loc=40.478358%2C-3.479485&loc=40.480883%2C-3.477607&hl=en&alt=0
![screenshot from 2017-05-23 11-55-33](https://cloud.githubusercontent.com/assets/4421046/26349021/dcdb7dd4-3fae-11e7-9695-f3640c0a909d.png)
the third instruction must be "take the 2bd exit"

In #4073 commit 588563c29246b1ba5804f6043bb66c73db429882 changed the exits counting, but not related to the PR.

**Comment by emiltin** [comment]
with the current work on roundabouts, keep in mind that roundabout exit instructions are kind of broken for cyclists and pedestrians, eg. https://github.com/Project-OSRM/osrm-backend/issues/2533.

here's an example of a roundabout with highway=path on both the roundabout and all exists:
https://www.openstreetmap.org/way/119182066

and a roundabout with a cycleway exit:
https://www.openstreetmap.org/way/8131031

**Comment by emiltin** [comment]
here's a roundabout with one residential exit, two service roads, and a cycleway:
https://www.openstreetmap.org/way/22999368
https://www.google.dk/maps/@55.7395107,12.4945035,3a,75y,31.51h,75.59t/data=!3m7!1e1!3m5!1sjcniSTl7sapWU_o0FI8gmw!2e0!6s%2F%2Fgeo2.ggpht.com%2Fcbk%3Fpanoid%3DjcniSTl7sapWU_o0FI8gmw%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D304.90176%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

**Comment by oxidase** [comment]
@emiltin thanks for pointing to the issue for non-car profiles! i will check in scope of this pr, but ignoring service roads on normal roundabouts atm is expected behavior for car profiles. Here http://map.project-osrm.org/?z=19&center=55.739516%2C12.494368&loc=55.739479%2C12.494186&loc=55.739648%2C12.494454&hl=en&alt=0  "the 1st exit" is correct.

Maybe a special handling for cyclists and pedestrians is needed, but i would open a PR after check.

**Comment by emiltin** [comment]
yes my point is that the current behaviour does not work for foot and bike routing.
even for cars i'm not sure i think the current behaviour makes sense, e.g. in the example no matter what exit you take, you get 'take 1st exit':
http://map.project-osrm.org/?z=19&center=55.739332%2C12.494454&loc=55.739479%2C12.494186&loc=55.739174%2C12.494679&hl=en&alt=0
