### ISSUE TITLE
Reusing a built OSRM file (North America)

### ISSUE THREAD

**Issue by glifchits** [Project-OSRM/osrm-backend#4082]
I'm looking into how we can quickly bring up several instances of OSRM for horizontal scaling. **I'm using Docker.** My current approach is to choose a PBF and do `osrm-extract` and `osrm-contract` in the Docker build, yielding a `north-america-latest.osrm` file that lives in the Docker image. Then I use the Node bindings and reference the `north-america-latest.osrm` file. (Note: I'm doing this for car.lua and foot.lua)

This approach seems to work fine for a smaller PBF (~2.2 GB), but I can't do it on the North America PBF. Here's what my testing looks like:
```
> // This works
> var OSRM = require('osrm')
undefined
> var x = new OSRM('/data/canada-latest.osrm')
undefined
> x
OSRM {}
```
```
> // This doesn't work
> var OSRM = require('osrm')
undefined
> var x = new OSRM('/data/north-america-latest.osrm')
... Consumes 17G of memory (23G for foot), then hangs with no output
```

So I know this approach works. However there is clearly some upper bound that I'm hitting, and there's no error to guide my debugging. Any ideas?

**Comment by TheMarex** [comment]
@glifchits big datasets like this I would recommed using shared-memory storage, which has the advantage of allowing for fast process restarts (in case of an internal error) and the use of `node-cluster`.

Add this to you docker file prior to starting up the server:
```
./osrm-datastore /data/north-america-latest.osrm
```

Then just initialize node with:

```js
const OSRM = require('osrm');
let osrm = new OSRM();
```

The likely cause of this error is that node/V8 doesn't like to have 22GB of additional memory being used in the same process (maybe this screws with their GC?).

**Comment by glifchits** [comment]
Thanks @TheMarex, giving this a try. Will circle back here with results.

**Comment by glifchits** [comment]
Thank you, using shared memory worked for North America car and foot profiles! I appreciate the help.

**Comment by TehNrd** [comment]
@glifchits Could you add a little more detail on your solution? When/where exactly are you calling `./osrm-datastore`? And are you using `docker run` to start your Docker container?

Did you put that command in the actual Dockerfile that builds the image with a `RUN` command?

**Comment by TehNrd** [comment]
Got it! No need to add...
```
./osrm-datastore /data/north-america-latest.osrm
```
...to the "Docker file", just need to add it to the node.js start file (app.js,index.js,etc) AND make sure you don't pass any arguments in to `let osrm = new OSRM(nothingHereIfUsingSharedMemory);` I forgot to remove this and had some nasty crashes with no stack trace.

Final solution:
```javascript
code = execSync('./node_modules/osrm/lib/binding/osrm-datastore ./osrm-datastore/osm.osrm'); 
logger.log(code.toString());  

var osrm = new OSRM();

app.get("/delaware", function(req, res) {
	
	var options = {
		coordinates: [
			[-75.573527, 39.738402],
			[-75.528694, 39.750988]	
		],
		source: "first",
		destination: "last",
		roundtrip: false
	} 

	osrm.trip(options, function (err, response) {
		if (err){
			logger.error(err);
			res.send(err);
		} else {
			res.send(response);
		}
	});
});
```
