### ISSUE TITLE
Geolocation error

### ISSUE THREAD

**Issue by oxk4r01** [Project-OSRM/osrm-backend#4083]
Hi. I'm developing an app for guiding in a series of routes with Leaflet and Routing Machine, using the demo server for testing pruposes, and since a few hours ago, I'm getting this error:
Geolocation error: Network location provider at 'https://www.googleapis.com/' : Returned error code 403..

I was wondering about it's origin. New in this kind of apps develoing so I'm a little lost...
Thanks in advance for the help.

**Comment by TheMarex** [comment]
This has nothing to do with out endpoint. As the error message suggest you are getting blocked by the google API (403 means forbidden access). Check your token, this is definitely not related to our service.

**Comment by oxk4r01** [comment]
Ok, thank you.
