### ISSUE TITLE
Matching plugin suspicious stops matching the trace

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#4084]
Example trace: /match/v1/driving/-73.90605,40.65499;-73.90723,40.65479;-73.90819,40.65465;-73.90937,40.65452;-73.91007,40.65568;-73.90933,40.65595;-73.90852,40.65609;-73.9076,40.65623;-73.90712,40.65544;-73.90696,40.65471;-73.9047,40.65501;-73.90369,40.65516;-73.90194,40.65594;-73.90094,40.65666;-73.89984,40.65721;-73.89854,40.65739;-73.89725,40.65757;-73.89625,40.65769;-73.895,40.65756;-73.89384,40.65741;-73.89273,40.65747;-73.89209,40.65777;-73.89126,40.6581;-73.8903,40.65803;-73.88968,40.65718;-73.88895,40.6562;-73.88852,40.65565;-73.88769,40.65455;-73.88723,40.65392;-73.88672,40.65322;-73.88624,40.65253;-73.88567,40.65173;-73.88513,40.65103;-73.88452,40.65022;-73.88369,40.64944;-73.88283,40.64867;-73.88199,40.64791;-73.88114,40.64717;-73.88035,40.64646;-73.87963,40.64579;-73.87864,40.64492;-73.87788,40.64423;-73.87725,40.64367;-73.87718,40.64276;-73.87728,40.64169;-73.87772,40.64068;-73.87817,40.63976;-73.87857,40.63891;-73.87912,40.63775;-73.87994,40.63628;-73.88097,40.63486;-73.88207,40.63359;-73.88312,40.63267;-73.88441,40.63168;-73.88559,40.63093;-73.88666,40.63022;-73.88787,40.62941;-73.88886,40.62875;-73.88945,40.62834;-73.89012,40.62789;-73.89087,40.62742;-73.89207,40.62668;-73.89374,40.62562;-73.89521,40.62449;-73.89629,40.62338;-73.89689,40.62248;-73.89717,40.6219;-73.89738,40.62137;-73.89758,40.62059;-73.89766,40.61986;-73.89762,40.61904;-73.89754,40.61831;-73.89741,40.6174;-73.89729,40.61687;-73.89713,40.61607;-73.89701,40.61521;-73.89699,40.61448;-73.89698,40.61371;-73.89699,40.61291;-73.89702,40.612;-73.89704,40.61135;-73.89724,40.61034;-73.89742,40.60965;-73.89759,40.60905;-73.89794,40.60803;-73.89822,40.60725;-73.89857,40.60646;-73.89869,40.60585;-73.8988,40.60506;-73.89893,40.60408;-73.89908,40.60353;-73.89942,40.60287;-73.89984,40.60229;-73.90033,40.60168;-73.90087,40.60113;-73.90211,40.60034;-73.90289,40.59995;-73.90385,40.59957;-73.90476,40.59917;-73.90679,40.59547;-73.90523,40.5941;-73.9038,40.59282;-73.90239,40.59142;-73.901,40.59014;-73.89983,40.58908;-73.89892,40.58826;-73.89786,40.58731;-73.89669,40.58626;-73.89546,40.58515;-73.89427,40.58409;-73.89316,40.58309;-73.89194,40.58208;-73.89078,40.58111;-73.88968,40.58011;-73.88893,40.57946;-73.88789,40.57833;-73.88748,40.57765;-73.88683,40.57655;-73.88636,40.57578;-73.88594,40.5751;-73.88553,40.57443;-73.88508,40.57369;-73.88467,40.57301;-73.88421,40.57223;-73.88368,40.57135;-73.883,40.57024;-73.88229,40.56906;-73.88137,40.56787;-73.87964,40.56735;-73.87773,40.56814;-73.8756,40.56915;-73.87373,40.57005;-73.8718,40.57094;-73.86978,40.57123;-73.8683,40.57216;-73.86735,40.57341;-73.86566,40.57422;-73.86391,40.575;-73.86245,40.57602;-73.86102,40.57686;-73.86012,40.57735;-73.8587,40.5781;-73.85714,40.57893;-73.85552,40.5798;-73.85386,40.58068;-73.85216,40.58141;-73.8506,40.58168;-73.84864,40.58177;-73.8469,40.58175;-73.84515,40.58145;-73.84354,40.58149;-73.84193,40.58157;-73.8405,40.58163;-73.83957,40.58169;-73.83871,40.58171;-73.83811,40.58126;-73.83784,40.58076;-73.83756,40.58025;-73.83741,40.58007?radiuses=18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;19;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18;18&steps=true&annotations=false&geometries=geojson&overview=full&timestamps=1495134662;1495134692;1495134702;1495134712;1495134732;1495134746;1495134770;1495134903;1495134958;1495135005;1495135035;1495135045;1495135065;1495135075;1495135085;1495135095;1495135105;1495135115;1495135125;1495135135;1495135159;1495135178;1495135199;1495135257;1495135267;1495135277;1495135285;1495135345;1495135355;1495135365;1495135375;1495135385;1495135395;1495135405;1495135415;1495135425;1495135435;1495135445;1495135455;1495135465;1495135485;1495135495;1495135505;1495135515;1495135525;1495135535;1495135545;1495135555;1495135565;1495135575;1495135585;1495135595;1495135605;1495135615;1495135625;1495135635;1495135645;1495135655;1495135665;1495135675;1495135685;1495135695;1495135706;1495135716;1495135726;1495135736;1495135746;1495135756;1495135766;1495135776;1495135786;1495135796;1495135816;1495135826;1495135836;1495135846;1495135856;1495135878;1495135888;1495135898;1495135908;1495135928;1495135938;1495135948;1495135973;1495135983;1495135993;1495136003;1495136013;1495136023;1495136033;1495136043;1495136053;1495136063;1495136073;1495136093;1495136103;1495136113;1495136130;1495136251;1495136261;1495136271;1495136281;1495136291;1495136301;1495136311;1495136321;1495136331;1495136341;1495136351;1495136361;1495136371;1495136381;1495136391;1495136401;1495136421;1495136431;1495136451;1495136461;1495136471;1495136481;1495136491;1495136501;1495136511;1495136521;1495136531;1495136541;1495136551;1495136561;1495136571;1495136581;1495136591;1495136601;1495136611;1495136621;1495136631;1495136641;1495136651;1495136661;1495136671;1495136681;1495136711;1495136721;1495136731;1495136741;1495136751;1495136761;1495136801;1495136811;1495136821;1495136831;1495136841;1495136851;1495136892;1495136902;1495136941;1495136951;1495136961;1495136968&gaps=ignore&tidy=false

**Comment by TheMarex** [comment]
Can you elaborate a little bit more of what symptom you are seeing?

**Comment by gardster** [comment]
Matching plugin returns matched track for a short piece of route without visible problems at the point where matching stops. This is happens when `gaps=ignore` parameter is set and track has places where proper matching is impossible according to given accuracy or timestamps.

**Comment by daniel-j-h** [comment]
You fixed this in https://github.com/Project-OSRM/osrm-backend/pull/4085, no? @gardster want to close this issue or is there anything to be done here?

**Comment by gardster** [comment]
Yes. Fixed in #4085 .
