### ISSUE TITLE
[Help] Match the trajectory -> give internal server error: 500

### ISSUE THREAD

**Issue by humasak** [Project-OSRM/osrm-backend#4087]
I need a help. I am trying to map trajectory using OSRM using node js, but the post result is internal server error  / 500. below i attached my code. What is the error happen in my code? thank you.
-------------------------------------
router.post('/', function (req, res) {
    generateMapMatching(res);
});

function generateMapMatching(res){
           var options = {
                coordinates: [[-1.48705868803094,53.37633159610329],[-1.487045541759221,53.37638287553591],[-1.487248487950045,53.37680062607262],[-1.486302999834602,53.3768748571542],[-1.487011224308355,53.37637059740518],[-1.486237770430629,53.37615732551673],[-1.486178575241304,53.37667845500587],[-1.485566852840159,53.37694214379437],[-1.485033835355963,53.37748623170953],[-1.483948873724068,53.37732911587538],[-1.484020933072991,53.37786694714728],[-1.484203345222093,53.37832027338951],[-1.483596529702868,53.37796488986215],[-1.483062365802644,53.37835793726251],[-1.482655359991836,53.37889860373465],[-1.481713187019891,53.37908127655188],[-1.481652336372732,53.37964547584655],[-1.481222884157771,53.38002457178255],[-1.480767962583462,53.3803821736719],[-1.48093568902759,53.38089705885552],[-1.480360097704228,53.38144616679796],[-1.480568924462216,53.38089035161219],[-1.479026250993213,53.38008678994493],[-1.47960280085746,53.3807600826573]],
                timestamps: [1486455654,1486455667,1486455687,1486455711,1486455722,1486455729,1486455792,1486455863,1486455916,1486455949,1486455968,1486455981,1486456027,1486456085,1486456111,1486456162,1486456201,1486456246,1486456344,1486456390,1486456510,1486456510,1486456559,1486456559],
                annotations: true,
                geometries: 'geojson'
            };
            if (timestamps.length == 0 || coordinates.length == 0) {
                res.writeHead(200, "empty", {
                    'Content-Type': 'application/json'
                });
                res.end(JSON.stringify(coordinates));
            }
            else {
                osrm.match(options, function (err, res) {
                    if (err) {
                        console.log(err + "");
                        this.response.writeHead(500, "No results found");
                        this.response.end();
                    } else {
                        console.log(res.tracepoints); // array of Waypoint objects
                        console.log(res.matchings); // array of Route objects
                        var revisedPoints = [];
                        //read matching result
                        for (var ix = 0; ix < res.matchings.length; ix++) {
                            var match = res.matchings[ix];
                            var coords = match.geometry.coordinates;
                            for (var index in coords) {
                                var coord = coords[index];
                                var nc = {latitude: coord[1], longitude: coord[0]};
                                revisedPoints.push(nc);
                            }
                        }
                        var coordinates=[];
                        for (var ix = 0; ix <  this.initialCoordinates.length; ix++) {
                            // this is an array [long, lat]
                            var match = this.coor[ix];
                            var nc = {latitude: match[1], longitude: match[0]};
                            coordinates.push(nc);
                        }
                        var finalResult= {initial: coordinates, final:revisedPoints};
                        finalJsonResult= JSON.stringify(finalResult);
                        this.response.send(finalJsonResult);
                    }
                }.bind({initialCoordinates:coordinates, response:res}));
            }
    }
}

**Comment by TheMarex** [comment]
Without the actual error that is returned by OSRM in the callback to `osrm.match` I can't help you.

**Comment by humasak** [comment]
The error just something like this: POST / 500 71.239 ms - 1141.

Actually, i call osrm.match in a loop (run match several time). is it possible?

**Comment by TheMarex** [comment]
You need to show me the actual error that is returned in the `err` object. There are any number of things that can cause 500 errors, your code could just be broken.

**Comment by daniel-j-h** [comment]
@humasak any updates on your side here? Without more details I'm inclined to close this ticket.

**Comment by humasak** [comment]
I already solved the problem. the problem is not in osrm library, but that's related to node js asynchronous programming. I am sorry for late response. thanks
