### ISSUE TITLE
any temporary files that can be removed?

### ISSUE THREAD

**Issue by mentinghfreightcenter** [Project-OSRM/osrm-backend#4092]
After running `osrm-extract` and `osrm-contract`, are there any large temporary files that I can remove from the system? Trying to optimize my AWS EC2 instance.

**Comment by jcoupey** [comment]
@mentinghfreightcenter yes, there are. Have a look at https://github.com/Project-OSRM/osrm-backend/wiki/Toolchain-file-overview to find out which files are used and how.

**Comment by mentinghfreightcenter** [comment]
awesome, thank you, had to click a link (show 13 more pages...) in the wiki menu in order to find that page after you mentioned it.
