### ISSUE TITLE
Error input file ... not found 

### ISSUE THREAD

**Issue by przelew** [Project-OSRM/osrm-backend#4095]
Sorry for probably stupid question, But I tried everything. I'm strugling with first command for installing docker image:

docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf

This is my terminal:
[https://ibb.co/ddtvTF](
https://ibb.co/ddtvTF)
I tried even download this file under docker image to "/data" catalog - the same
I tried to pass folder from few places under Ubuntu main system - the same

Please help.
Last image, Ubuntu 16, last docker version

**Comment by danpat** [comment]
@przelew You're missing a leading `/` in front of `data/poland-latest.osm.pbf`.

The flag `-v $(pwd):/data` creates the directory `/data` inside the docker container, and makes `$(pwd)` available there.  The file `/data/poland-latest.osm.pbf` inside the container is referring to `/home/ubuntu/poland-latest.osm.pbf` on the host.

**Comment by przelew** [comment]
@danpat  I did few things and it started to work (also your suggestion), thank you.

**Comment by MikeMpapa** [comment]
what did you do?? I have the exact same prob ...

**Comment by Lifeuser** [comment]
+1 on "what did you do??"

It's all exactly the same but on latest mac os with latest docker...

![screen shot 2017-07-07 at 14 50 52](https://user-images.githubusercontent.com/2346053/27956784-f74e0f36-6323-11e7-9318-4260b4983348.png)

**Comment by daniel-j-h** [comment]
For the record: solution is here: https://github.com/Project-OSRM/osrm-backend/issues/4253#issuecomment-313667032: - paths were wrong.

**Comment by radumas** [comment]
I feel like the README should be updated to be more clear to everyone who's run into this issue.
