### ISSUE TITLE
Demo server not responding

### ISSUE THREAD

**Issue by ArcanaCorvus** [Project-OSRM/osrm-backend#4101]
I'm using the demo server to test some queries for an upcoming implementation and the demo server isn't responding.

Most of the time I get a 504 Gateway Timeout and occasionally a 500 Internal Server Error

**Comment by oxidase** [comment]
Will be fixed in #4100

**Comment by daniel-j-h** [comment]
Keep in mind the demo server has basically no uptime guarantees. We try to keep it stable and working but it's running the latest commits and osm planet - so there will be hiccups every now and then.

Here's how to run a routing engine locally on a small extract if that's good enough for you:

https://github.com/Project-OSRM/osrm-backend#quick-start
