### ISSUE TITLE
Terminate called after throwing an instance of 'std::bad_alloc' - Using OSRM Docker Image

### ISSUE THREAD

**Issue by ArcanaCorvus** [Project-OSRM/osrm-backend#4109]
I'm attempting to use the OSRM Docker image for the north-america map data. The data is downloaded and I ran the extract command which finished parsing after 1329.8 seconds and then began to "sort used nodes"

This very quickly exited with the "terminate called after throwing an instance of 'std::bad_alloc'" error. I found an issue from 2011 regarding this which suggested it was an out of memory issue and that the maps required approximately 64 GB of memory to process.

It seems a lot has changed since then however and I'm wondering is this still the case and what solutions are there to this problem?

**Comment by danpat** [comment]
Yes, `std::bad_alloc` is an internal C++ exception thrown when you're out of memory.  We we should be [catching that](https://github.com/Project-OSRM/osrm-backend/blob/master/src/tools/extract.cpp#L171) and printing a nice error message though.

Can you describe exactly what version of OSRM you're using?  What's the docker image ID?  What was your exact command invocation?

**Comment by ArcanaCorvus** [comment]
I'm using the version and instructions from [here](https://hub.docker.com/r/osrm/osrm-backend/), given the "last pushed 8 hours ago", I assume I'm using the most up to date version.

Docker SHA is 5b990ee53e9a5457951338d9d5111a1ffda5127ad95f43d0ab0285a503b5074a

The command invocation was:
$ sudo docker run -t -v $(pwd):/media/large/docker/map/data osrm/osrm-backend osrm-extract -p /opt/car.lua /media/large/docker/map/data/north-america-latest.osm.pbf

**Comment by daniel-j-h** [comment]
How much memory do you have for your North America base map? Can you try with a smaller extract (e.g. monaco, france, etc.) to make sure it runs through.

> I found an issue from 2011 regarding this which suggested it was an out of memory issue and that the maps required approximately 64 GB of memory to process.

Not sure if these numbers are still valid - a lot has changed since 2011 :)

**Comment by daniel-j-h** [comment]
Any updates here? Otherwise I'm inclined to close this with: you need to provide more memory.
