### ISSUE TITLE
Traffic speed test depends on non-deterministic snapping behavior

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4110]
The following test depends on random behavior and how snapping works out:

https://github.com/Project-OSRM/osrm-backend/blob/f3558260b6c0d73bcaf40171a63ccacd9a698a35/features/testbot/traffic_speeds.feature#L86-L117

There is no way to `g` (see the [network a bit above](https://github.com/Project-OSRM/osrm-backend/blob/f3558260b6c0d73bcaf40171a63ccacd9a698a35/features/testbot/traffic_speeds.feature#L4-L31)) and @MoKob pointed out snapping at `b` could be `eb` or `ab`. The test failure is currently on the [`mld/alternatives` branch](https://github.com/Project-OSRM/osrm-backend/pull/4047) but it's not the cause for it (it's not hitting the alternatives code path at all).

Here's the test diff:

https://travis-ci.org/Project-OSRM/osrm-backend/jobs/237850494#L2198

cc @danpat for non-deterministic snapping behavior

**Comment by TheMarex** [comment]
The whole test case should be rewritten using a node map and a more obvious graph structure.

**Comment by oxidase** [comment]
The test case fail is not related to snapping and shows a data race in the assignments https://github.com/Project-OSRM/osrm-backend/blob/42f3401dd730a03b5b757449bc759d8947119642/src/updater/updater.cpp#L230 and 
https://github.com/Project-OSRM/osrm-backend/blob/42f3401dd730a03b5b757449bc759d8947119642/src/updater/updater.cpp#L263 during parallel segment weights update
