### ISSUE TITLE
Stuck on generating edge-expanded edges

### ISSUE THREAD

**Issue by Denis-Davydov** [Project-OSRM/osrm-backend#4112]
Hi,

I am following the the steps on [here](https://github.com/Project-OSRM/osrm-backend#quick-start) to install OSRM on my Mac OS X.  I am using Docker and am stuck on the first line.

    docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/mexico-latest.osm.pbf

 Trying to work with mexico-latest.osm.pbf, I get stuck on generating edge-expanded edges.

    [info] Using script /opt/car.lua
    [info] Input file: mexico-latest.osm.pbf
    [info] Profile: car.lua
    [info] Threads: 4
    [info] Parsing in progress..
    [STXXL-MSG] STXXL v1.4.1 (prerelease/Release) (git e7d36edd8152c73b115bd36cbcf566626d995434)
    [STXXL-ERRMSG] Warning: no config file found.
    [STXXL-ERRMSG] Using default disk configuration.
    [STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
    [info] input file generated by osmium/1.5.1
    [info] timestamp: 2017-05-30T20:43:14Z
    [info] Found 3 turn restriction tags:
    [info]   motorcar
    [info]   motor_vehicle
    [info]   vehicle
    [info] Parsing finished after 35.3032 seconds
    [info] Raw input contains 17476622 nodes, 1740511 ways, and 1828 relations
    [info] Sorting used nodes        ... ok, after 1.18971s
    [info] Erasing duplicate nodes   ... ok, after 0.772208s
    [info] Sorting all nodes         ... ok, after 2.21792s
    [info] Building node id map      ... ok, after 4.7524s
    [info] setting number of nodes   ... ok
    [info] Confirming/Writing used nodes     ... ok, after 37.224s
    [info] Processed 7771938 nodes
    [info] Sorting edges by start    ... ok, after 4.21008s
    [info] Setting start coords      ... ok, after 8.69918s
    [info] Sorting edges by target   ... ok, after 4.2293s
    [info] Computing edge weights    ... ok, after 10.1508s
    [info] Sorting edges by renumbered start ... ok, after 3.97565s
    [info] Writing used edges       ... ok, after 2.03903sProcessed 8868977 edges
    [info] Sorting used ways         ... ok, after 0.961331s
    [info] Sorting 1828 restriction. by from... ok, after 0.000258s
    [info] Fixing restriction starts ... ok, after 0.562106s
    [info] Sorting restrictions. by to  ... ok, after 0.000224s
    [info] Fixing restriction ends   ... ok, after 0.009085s
    [info] number of restrictions saved to memory: 1728
    [info] number of conditional restrictions written to disk: 0
    [info] writing street name index ... ok, after 0.6209s
    [info] extraction finished after 120.614s
    [info] Generating edge-expanded graph representation
    [info] Importing number_of_nodes new = 7771938 nodes 
    [info]  - 373 bollard nodes, 8685 traffic lights
    [info]  and 8868977 edges 
    [info] Graph loaded ok and has 8868977 edges
    [info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
    [info] Node compression ratio: 0.304352
    [info] Edge compression ratio: 0.390376
    [info] Generating edge expanded nodes ... 
    [info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
    [info] Generated 6419043 nodes and 8868632 segments in edge-expanded graph
    [info] Generating edge-expanded edges 
    [info] . 10% .

Is it a possible issue with the file?

**Comment by danpat** [comment]
@Denis-Davydov How much RAM does your machine have?  It looks like processing is progressing, but it can be very slow if your machine is starved for RAM.

**Comment by Denis-Davydov** [comment]
8GB of RAM. And I am worrying because the 10% come pretty quickly but then the progress stops. Ltet it run a few hours, but nothing.

**Comment by danpat** [comment]
@Denis-Davydov I just did this using the latest code from master (not using Docker, but close enough).

Total processing time on my 16GB Macbook Pro was around 3 minutes.  Here's the trick though:

```
[info] RAM: peak bytes used: 4104253440
```

`osrm-extract` uses >4GB of RAM to process Mexico.  Make sure you've got that amount free and that Docker allows your process to use it.

If not, your operating system will start swapping RAM to disk, and this will slow things down by orders of magnitude.

The processing phase you're stuck on (generation of edge-expanded edges) gradually uses more and more RAM, so it's possible you were OK at the beginning, and now your operating system has run out.

Use `Activity Montitor.app` on macOS to explore what's running and how much free memory you have available.

**Comment by Denis-Davydov** [comment]
Yes you are right. I see that RAM is kind of blocked around 2GB. Anyway I can increase this or am I just supposed to have more RAM?

**Comment by danpat** [comment]
You should modify your Docker configuration to allow memory usage up to 4.5GB for the `mexico-latest.osm.pbf`.

If you don't, it's likely that processing will be very slow for a while, then it will fail with an out-of-memory error.

**Comment by Denis-Davydov** [comment]
Thank you @danpat. This was exactly the issue. Worked.
