### ISSUE TITLE
Error when calling from javascript

### ISSUE THREAD

**Issue by tecinformatico** [Project-OSRM/osrm-backend#4113]
Hi, this is my first question here. I'm sorry for my English.

I have installed osrm-backend on a debian virtual machine running:
`apt-get install git g++ cmake libboost-dev libboost-filesystem-dev libboost-thread-dev \
libboost-system-dev libboost-regex-dev libstxxl-dev libxml2-dev libsparsehash-dev libbz2-dev \
zlib1g-dev libzip-dev libgomp1 liblua5.1-0-dev \
pkg-config libgdal-dev libboost-program-options-dev libboost-iostreams-dev \
libboost-test-dev libtbb-dev libexpat1-dev

```
git clone https://github.com/Project-OSRM/osrm-backend.git
cd osrm-backend
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
sudo cmake --build . --target install
cd ..
wget http://download.geofabrik.de/europe/spain-latest.osm.pbf
osrm-extract spain-latest.osm.pbf -p profiles/car.lua
osrm-contract spain-latest.osrm
osrm-routed spain-latest.osrm --port 5544 --ip 0.0.0.0
```

When I run `curl http://127.0.0.1:5544/route/v1/driving/36.527061,-6.288596;36.685006,-26074?steps=true` from the server itself. All ok

Using the postman (aka restclient) using get `http://192.168.5.83:5544/route/v1/driving/-6.288596200000029,36.5270612;-6.126074399999993,36.6850064?overview=false&alternatives=true&steps=true&hints=;`
. All ok

I have a VPS with my website and I have the ports open to my virtual machine.
From the SSH console of the VPS I run. `Http: // (MY PUBLIC IP): 5544 / route / v1 / driving / -6.288596200000029,36.5270612; -6.126074399999993,36.6850064? Overview = false & alternatives = true & steps = true & hints =;` EVERYTHING OK.

Now from the same VPS server I created a web with this code
```
`<Script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </ script>
<Script>
$ (Document) .ready (function () {
    $ ("Button"). Click (function () {
        $ .get ("http: // (MY PUBLIC IP): 5544 / route / v1 / driving / 36.527061, -6.288596; 36.685006, -6.126074? Steps = true", function (data, status)
           $ ('. Result'). Html ("Date:" + data + "\ nStatus:" + status);
        });
    });
});
</ Script>
<Button> btn </ button>
<Div class = "result"> </ div>`
```

But I get error in the console
GET `http: // (MY PUBLIC IP): 5544 / route / v1 / driving / 36.527061, -6.288596; 36.685006, -6.126074? Steps = true` net :: ERR_CONNECTION_REFUSED.

I get exactly the same error using the leaflet routing machine plugin, pointing to my server.
 Does anyone have any idea of ​​what may be going on

**Comment by daniel-j-h** [comment]
Make sure your box is available from the outside - nothing we can help you with here.
Also maybe test with `curl` to make sure your client code is not the problem here.

Note that `osrm-routed` is only a development HTTP server.
You might be better off using `node-osrm` for production.
