### ISSUE TITLE
Duplicated Test Runs

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#4115]
CLANG_VERSION='4.0.0' BUILD_TYPE='Release' ENABLE_MASON=ON ENABLE_LTO=ON JOBS=3
https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L190 
env: CLANG_VERSION='4.0.0' BUILD_TYPE='Debug' ENABLE_MASON=ON ENABLE_LTO=ON JOBS=3
https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L213
CLANG_VERSION='4.0.0' BUILD_TYPE='Release' ENABLE_MASON=ON ENABLE_LTO=ON JOBS=3 NODE="6"
https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L236 
env: CLANG_VERSION='4.0.0' BUILD_TYPE='Debug' ENABLE_MASON=ON ENABLE_LTO=ON JOBS=3 NODE="6"
https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L259

as well in general for non sanitised i686 builds (which is all but https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L124)
`[ -z "${ENABLE_SANITIZER}" ] && [ "$TARGET_ARCH" != "i686" ];`
https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L361

Finally we also do an extra run of `conditionals` on all mason builds (https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L365), which seems to be part of all other test runs, anyhow. Or are these excluded from `npm test` for some reason. If so, why?

The second part duplicates some cucumber codes, the node-js part is only running on monaco. Still we should probably run each test only once.

**Comment by SiarheiFedartsou** [comment]
Seems to be irrelevant
