### ISSUE TITLE
Build `latest` docker image with RelWithDebInfo

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#4119]
How bad would be the performance/size impact of always building the docker images with `BuildType=RelWithDebInfo`? It would make debugging problems on master easier, while still retaining debug possibility. For actual tagged releases i'd keep it with `BuildType=Release`.

**Comment by daniel-j-h** [comment]
`RelWithDebInfo` comes with assertions enabled (see [here](https://github.com/Project-OSRM/osrm-backend/blob/a92674022a23b98b688c7d738006d33abebe4749/CMakeLists.txt#L206)) and adds some compiler flags for helping gdb. If you disable assertions in the `RelWithDebInfo` build it's a good question how bad performance will be - not sure we will see a large drop to be honest.

Other downside I can think of is debug symbols make the binaries large(er). Also not sure about numbers here - please try out and report back.
