### ISSUE TITLE
Traveling salesman problem with time windows?

### ISSUE THREAD

**Issue by chrismanderson** [Project-OSRM/osrm-backend#4123]
Hello! Do you all have support time windows when calculating the Traveling Salesman Problem? I was searching through the issues to see if it had been asked or requested before, but 'time' and 'schedules' is sadly a tough thing to search for.

**Comment by daniel-j-h** [comment]
Not for the Trip plugin, no. But look no further than

https://github.com/mapbox/node-or-tools#node-or-tools

:)

**Comment by chrismanderson** [comment]
Cheers, thanks!
