### ISSUE TITLE
OSRM-routed always gives the same node

### ISSUE THREAD

**Issue by cfriedrichh** [Project-OSRM/osrm-backend#4124]
I followed the instructions here: https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM
(and used netherlands-latest.osm.pbf from GeoFabrik instead of berlin-latest).

After running osrm-extract and osrm-contract, osrm-routed does not seem to work as expected. It always returns the same one node.

Running "http://localhost:5000/route/v1/car/51.2270468,3.8001583;53.216052,6.500543" returns:
`{"waypoints":[{"location":[6.01906,50.751527],"hint":"AbEZgK9AHoBAZgcAAwAAAAAAAAB1AQAATgEAAAMAAAAAAAAAdQEAAE4BAACLiw8A1AQAAPTXWwAnaAYDp6kNA178OQAcAAEBeqpHjQ==","name":"Route des Trois Bornes"},{"location":[6.01906,50.751527],"hint":"AbEZgK9AHoBAZgcAAwAAAAAAAAB1AQAATgEAAAMAAAAAAAAAdQEAAE4BAACLiw8A1AQAAPTXWwAnaAYDNAMsA78wYwAcAAEBeqpHjQ==","name":"Route des Trois Bornes"}],"routes":[{"distance":0,"weight_name":"routability","legs":[{"distance":0,"steps":[],"duration":0,"weight":0,"summary":""}],"duration":0,"weight":0,"geometry":"alwtHcrvc@??"}],"code":"Ok"}`

The same request from the official OSRM demo server is different and correct (https://router.project-osrm.org/route/v1/car/51.2270468,3.8001583;53.216052,6.500543). Moreover, every routing or "nearest" request always gives the same node as response.

Is there an issue with osrm file generation or did the API change?

Output from osrm-extract and -contract attached.
[log.txt](https://github.com/Project-OSRM/osrm-backend/files/1049601/log.txt)

**Comment by daniel-j-h** [comment]
> Running "http://localhost:5000/route/v1/car/51.2270468,3.8001583;53.216052,6.500543"

For Netherlands you mixed up latitude and longitude. The reason runs the full planet. In contrast if you only load Netherlands into your server, the initial snapping to the nearest coordinate in your data set will most likely always return the same coordinate.

Already closing here, feel free to report if this works for you.

**Comment by cfriedrichh** [comment]
Thank you very much! Slightly stupid mistake by me ;)
