### ISSUE TITLE
distance being calculated as 0

### ISSUE THREAD

**Issue by yogesh-12** [Project-OSRM/osrm-backend#4125]
http://router.project-osrm.org/route/v1/driving/28.55307,77.20115;29.5535294,78.2015257?overview=false

With this url your api is giving a distance and duration 0 whereas the below one gives a non-zero value of distance and duration.
http://router.project-osrm.org/route/v1/driving/28.55307,77.20115;30.5535294,79.2015257?overview=false
 Is it required to maintain a threshold distance between the points to get a non-zero value?

**Comment by oxidase** [comment]
@yogesh-12 thanks for reporting! The first result is correct as source and target points are projected to the same location http://map.project-osrm.org/?z=18&center=71.168260%2C25.779470&loc=77.201150%2C28.553070&loc=78.201526%2C29.553529&hl=en&alt=0

The second result with non-zero distance looks wrong and must be checked http://map.project-osrm.org/?z=8&center=70.617136%2C26.569885&loc=77.201150%2C28.553070&loc=79.201526%2C30.553529&hl=en&alt=0

**Comment by yogesh-12** [comment]
http://router.project-osrm.org/route/v1/driving/28.679216,77.263320;28.579802,77.198787?overview=false
The above url gives a distance of zero whereas if i plot the same points it gives a distance of 16.5 km.
http://map.project-osrm.org/?z=12&center=28.624574%2C77.260510&loc=28.679216%2C77.263320&loc=28.579802%2C77.198787&hl=en&alt=0
this is the link for plot.

**Comment by oxidase** [comment]
@yogesh-12 OSRM uses `lon,lat` pairs in queries, but frontend uses `lat,lon`. So for the first query a [zero distance path](http://map.project-osrm.org/?z=6&center=78.068805%2C22.478027&loc=77.263320%2C28.679216&loc=77.198787%2C28.579802&hl=en&alt=0) is correct. For the second query  the corresponding OSRM request is http://router.project-osrm.org/route/v1/driving/77.263320,28.679216;77.198787,28.579802?overview=false and returns a 16.5km path

**Comment by daniel-j-h** [comment]
So this can be closed as lat,lon swap @oxidase?

**Comment by oxidase** [comment]
@daniel-j-h hm, it can be closed as "lat,lon problem", but http://map.project-osrm.org/?z=17&center=71.168682%2C25.780331&loc=77.201150%2C28.553070&loc=79.201526%2C30.553529&hl=en&alt=0 looks weired, i will check it and open a new ticket if it is a real problem
