### ISSUE TITLE
Is there possible to use polyline6 as coordinates in request?

### ISSUE THREAD

**Issue by superstas** [Project-OSRM/osrm-backend#4126]
Hello, is there possible to use polyline6 as coordinates in request.
Let's take a look at example

My coordinates: 
> [[40.714701, -73.990171], [40.717571, -73.991801], [40.715651, -73.985751]]

Polyline5: 
`polyline.encode([[40.714701, -73.990171], [40.717571, -73.991801], [40.715651, -73.985751]],5);` = **{aowFperbM}PdI~Jyd@**

https://router.project-osrm.org/route/v1/car/polyline(%7BaowFperbM%7DPdI~Jyd@)?annotations=false&continue_straight=true&geometries=polyline6&overview=false&steps=true - **polyline5 works**

Polyline6:
`polyline.encode([[40.714701, -73.990171], [40.717571, -73.991801], [40.715651, -73.985751]],6);` = **y{_tlAt`_clCkrDzdB~vBcyJ**
https://router.project-osrm.org/route/v1/car/polyline6(y%7B_tlAt%60_clCkrDzdB~vBcyJ)?annotations=false&continue_straight=true&geometries=polyline6&overview=false&steps=true - **polyline6 doesn't work**

Polylines were built by https://npm.runkit.com/polyline

Is this way valid?
Thank you

**Comment by daniel-j-h** [comment]
Polyline6 got implemented during the last year in the response - having it as an option in the request URL probably makes sense, too. It's not supported at the moment.

Here's what needs to be done:
- [Similarly to polyline5 and polyline6 encoding](https://github.com/Project-OSRM/osrm-backend/blob/f88ac989ea3003d19ba10f34bff7a1e1e497b097/include/engine/polyline_compressor.hpp#L26-L27) decoding needs to be made generic wrt. precision
- In the [grammar](https://github.com/Project-OSRM/osrm-backend/blob/master/include/server/api/base_parameters_grammar.hpp#L124-L129) add a rule for parsing "polyline6" and then decode the polyline chars accordingly

**Comment by superstas** [comment]
Thank you, @gardster
