### ISSUE TITLE
Diiferent routing data in Debug and Release /Windows/

### ISSUE THREAD

**Issue by kostadin24** [Project-OSRM/osrm-backend#4138]
Hello,
I have downloaded v5.7.0 and build in release. Works fine.
Then switched to debug mode. Does not work with routing data prepared with release version.
After extract and contract with debug version - everything is OK.
In the past with version 4.8.0 I didn't have such problems.

Any ideas?

**Comment by oxidase** [comment]
@kostadin24 the situation you described looks like a regression bug. Please could you put more context which OSM file was prepared in release mode and which query was not ok with `osrm-routed` in debug mode?

**Comment by kostadin24** [comment]
Private data prepared.
If prepare and use it with debug - OK
if prepare and use it with release - OK
If prepare with debug, but use in release - Broken/missing files :(

**Comment by oxidase** [comment]
just realized that it is a problem with a windows build. Windows builds are checked on AppVeyor only for `RelWithDebInfo` build type, so probably it is pure msvc  Debug build problem.
 
With gcc the following steps work ok
```
cmake -DCMAKE_BUILD_TYPE=Release .. && make -j4 && ./osrm-extract -p ../profiles/car.lua berlin-latest.osm.pbf && ./osrm-contract berlin-latest.osrm
cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j4 && ./osrm-routed berlin-latest.osrm
```

**Comment by kostadin24** [comment]
So how are build windows release version for download?
It is not problem to prepare and use data in release only, but it is interesting to know differences in binary data.

**Comment by danpat** [comment]
@kostadin24 Can you please include a complete debug log showing the problem?  The exact error messages (with full context) will help us diagnose where the issue might be.

**Comment by daniel-j-h** [comment]
@kostadin24 any updates here?

**Comment by daniel-j-h** [comment]
Stale. Please re-open when you can provide more details.
