### ISSUE TITLE
how to get road segment from OSRM result?

### ISSUE THREAD

**Issue by humasak** [Project-OSRM/osrm-backend#4142]
dear all,

is there anything i can do to get road segment from match result? Actually, i got the node (orsmid), but the information i need is road segment. thank you for the help.

**Comment by danpat** [comment]
@humasak what is a "road segment"?

The only details that OSRM keeps that you can link back to OSM data is the OSM node IDs.  If you want more metadata about a road, you will probably need to use those IDs to query either the OSM API or the Overpass API, separately from OSRM.

**Comment by humasak** [comment]
@danpat thank you for your answer. actually, from the pbf file, I already extracted OpenStreetMap data to the PostgreSQL database. Tables that i have are planet_osm_line, planet_osm_point, planet_osm_polygon, planet_osm_roads and spatial_ref_sys. 

What I need is I want to map the OSM node IDs (that i got from osrm) to the specific location (latitude and longitude). I am still confuse how to connect/map this OSM node IDs with those tables that i already extracted from openstreetmap data. thank you for the help.

**Comment by danpat** [comment]
If you've got a database schema that contains all the data from `osm2pgsql`, then you should have everything you need to query way attributes from node ID values.

Something like this will be close:

`SELECT tags FROM planet_osm_ways WHERE nodes @> ARRAY[NODE1,NODE2];`

`osm2pgsql` uses Postgresql `ARRAY` types for both the `nodes` and `tags` field on the `planet_osm_ways` table.  The query above will match any way that contains both `NODE1` and `NODE2` (replace these values with the OSM node IDs you get from OSRM).

It doesn't check for ordering, you may need to make the query a little fancier than that for it to be strictly correct, but it should work for most situations (it is fairly rare for two ways to share more than one node, especially for roads).

You'll probably also want to use PostgreSQL's various `array_*` functions to unpack the `tags` column to extract the data you want.

There's nothing actionable for us here in OSRM land, closing.
