### ISSUE TITLE
Problem trying to use node bindings with OSRM v5.7.0

### ISSUE THREAD

**Issue by joseflorido** [Project-OSRM/osrm-backend#4144]
Hi!

I did install OSRM v5.7.0 on Ubuntu 16.04 following your quick start guide, building it from source.

I was able to prepare osrm file for north america and it runs OK with osrm-routed.

Now, to have it running on a production server, I'd like to use nodeJS bindings. I installed them with `npm install osrm` and created a simple Express app following /example/example.js.

When I run `node app.js` I get error: Error: Cannot find module './binding/node_osrm.node'

What am I missing?

Thanks!

**Comment by joseflorido** [comment]
Update: I was able to import bindings with `var OSRM = require('./node_modules/osrm');`.
Now when I run `node app.js` I get error:
`TypeError: Fingerprint mismatch in /root/berlin-latest.osrm.hsgr (at include/storage/io.hpp:61)`

Any pointers?
Thanks!

**Comment by daniel-j-h** [comment]
Can you tell us

    node --version
    npm --version

for your first issue.

For the fingerprint mismatch: you have to prepare your osm data with the same osrm version the node plugin bundles. That's the reason we bundle the matching osrm binaries with the node osrm plugin at `node_modules/osrm/lib/bindings`. Use these to be sure you're always in sync.

**Comment by joseflorido** [comment]
Hi Daniel!
`node --version -> v6.11.0
npm --version -> 3.10.10`

I was able to prepare data with binaries at node_modules/osrm/lib/bindings and it is working fine now, Thanks!!

**Comment by daniel-j-h** [comment]
> I was able to prepare data with binaries at node_modules/osrm/lib/bindings and it is working fine now, Thanks!!

Great!
