### ISSUE TITLE
Provide an IntersectionValidationHandler

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4146]
Our intersection handlers (and derived handlers such as the Sliproad handler) run in the `osrm-extract` tool for each internal intersection type. We should create a new (optional) handler running last which reports issues with the intersections and checks their integrity.

Issues we should detect and report (feel free to add more):
- Sharp turns onto ramps
- Uturns (or two quick-turns) with a high speed
- ..

Here's the intersection handler:

https://github.com/Project-OSRM/osrm-backend/blob/9d308172949416701f375535c4a94c9291c4f283/include/extractor/guidance/intersection_handler.hpp#L29-L117

cc @joto @danpat

**Comment by MoKob** [comment]
There is quite a few other situations that we could also check easily:

- roundabout issues
  - The roundabout handler checks for circular connectivity in roundabouts
  - we have an invalid roundabout if we see roundabout + non-roundabout tags but no roundabout instruction
- sliproad issues
  - if we detect a sliproad, the next road should probably not allow a turn
  - we can compare the next intersection for the turn that is covered by the sliproad
- motorway ramps: exit->entry
  - in addition to the sharp turn onto ramps, we could check for sharp turns between ramps
  - the check would need to check for road_classifications and link classes
  - report an error when there is a sharp turn between two ramps
- turn lanes:
  - some lanes can be seen as invalid (e.g. turn right, but there is no right turn for some while)
  - inconsistencies between number of lanes / turn lanes
- unexpected mode changes
  - mode changes when entering/exiting roundabouts (travel mode for in/out edge + roundabout type)

**Comment by emiltin** [comment]
turns on railways would also be unexpected i think.
mode change on roundabout could happen on a bike, if you have to push the bike on entry/exit.

**Comment by MoKob** [comment]
@emiltin are railway lines not modelling the actual tracks? In ferries there is an official OSM convention that different lines should use different ways, even though they might follow the same route for a while.
On railways, I am not sure whether this is also the case.
For the mode changes, I agree with you. We should make sure that we change this behaviour if we should be running the bike profile. Walk/Push should be at least kept out of the list of unexpected changes. We were only thinking of roundabouts directly connected into ferries (which was the case in a few situations)

**Comment by b-jazz** [comment]
I've done a couple hundred edits now for intersections that were caught by the "sharp turns onto ramps" validation and I've seen a non-trivial portion of them be false positives. In the area that I've worked on, there are on-ramps that are on the overpass or underpass that are "sharp" enough to be triggered and are typically controlled by a stop sign/light, but they all have a long ramp with plenty of time to get from 0 MPH to freeway merging speeds. I wonder if you can add another metric where you check the length of the on ramp and factor that into the decision. I can see a short ramp and a 20 degree angle is probably a problem with turn restrictions. But a 75 degree angle and a very long ramp probably is a false positive. 

Just a thought.

**Comment by daniel-j-h** [comment]
That's great feedback! It should be possible to check this in the validation handler we have all the geometry at hand and can use it. I already experimented with checking only fast roads for sharp turns but that didn't turned out to be precise enough. Mostly because of missing road features such as traffic signals, stop signs, etc.

**Comment by daniel-j-h** [comment]
This got :hocho:-ed.
