### ISSUE TITLE
for_each_pair possible optimization

### ISSUE THREAD

**Issue by joto** [Project-OSRM/osrm-backend#4148]
[for_each_pair](https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/for_each_pair.hpp#L15) takes a Function argument by value. Reference should be enough? and it returns the function for some reason. That returned function is never used in the OSRM code.

**Comment by daniel-j-h** [comment]
The reason it takes a functor by value is it mimics the stdlib. Same with returning the functor. The stdlib's reason for returning the functor is you can use it e.g. as:

    return for_each(first, last, functor).sum;

when your accumulating functor has a `.sum` attribute.

If you don't want your functor to be copied there is `std::cref`.
