### ISSUE TITLE
How to build OSRM in Ubuntu without sudo priviledge?

### ISSUE THREAD

**Issue by humasak** [Project-OSRM/osrm-backend#4150]
hi all,

I want to build OSRM in ubuntu server in my local directory. Actually, I do not have sudo privilege. is there anyone have the experience to build OSRM in Ubuntu without sudo privilege? May please share the steps? thank you in advanced.

**Comment by daniel-j-h** [comment]
You don't need `sudo` for building osrm from source. Just follow the steps [here](https://github.com/Project-OSRM/osrm-backend#building-from-source) and leave out the global installation step. Then you can just use the osrm binaries in the build directories.

Or tell CMake to install to a local directory:

    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/user/osrm

In case you also don't have the dependencies around you need to build them locally before, too.

**Comment by humasak** [comment]
thanks @daniel-j-h 

I already tried. But, when I tried to execute command: 
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/user/osrm

I got this error: 
-- Building on a 64 bit system
CMake Error at CMakeLists.txt:101 (message):
  GCC>=4.9 required.  In case you are on Ubuntu upgrade via
  ppa:ubuntu-toolchain-r/test
-- Configuring incomplete, errors occurred!

I already installed  GCC 5.2.0 locally. But. i do not know how to solve this error. please help. tks

**Comment by danpat** [comment]
Try doing:

```
export CXX=g++-5
export CC=gcc-5
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/user/osrm
```

(here, `g++-5` is the name of your GCC 5.2 executable, and it should be on your `PATH` somewhere)

**Comment by humasak** [comment]
@danpat I already tried it, but it still gives the same error.

actually, my .bashrc contain these:
export PATH=~/gcc-5.2.0/bin:$PATH
export LD_LIBRARY_PATH=~/gcc-5.2.0/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/gcc-5.2.0/lib/../lib64:$LD_LIBRARY_PATH

I do not know what it still gives the same error. need help...

**Comment by danpat** [comment]
@humasak There is something wrong with your GCC installation.  We cannot really help with that.  I would recommend that you use the Ubuntu Toolchain test builds PPA at:

  https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

and install pre-packaged binaries/libraries for GCC there.

We have instructions on the Wiki here: https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu which has step-by-step instructions for installing the updated packages you need to make the build work.

The other option is to use pre-built binary images via Docker or NodeJS.  See the Wiki for instructions.
