### ISSUE TITLE
Matching plugin splits tracks with the gaps=ignore option

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#4163]
The match plugin splits good and physically possible track if there is a huge gap in coordinates inside this track.
![error](https://user-images.githubusercontent.com/1862559/27185528-4fb78e00-51ee-11e7-8c8e-50cba12907b8.png)

**Comment by ankitsoni9989** [comment]
Hi,
I have seen a few times that match service does return multiple matchings even when `gaps=ignore` is supplied as input, what could be the possible reason/s for that? I have attached an example:

> http://127.0.0.1:5000/match/v1/car/76.8395028,30.6934667;76.8402503,30.6936606;76.8405394,30.6939434;76.8402829,30.6942707;76.8398813,30.6946538;76.8396002,30.6949999;76.8398675,30.6953184;76.838714,30.6965572;76.838234,30.696407;76.837875,30.6961983;76.8378868,30.6958083;76.8398705,30.6975055;76.8395771,30.6980431;76.8389174,30.6996206;76.8391447,30.7004599;76.838807,30.7013919;76.8374105,30.7072916;76.8361681,30.7074911;76.8355832,30.7073659;76.8355775,30.7069908;76.835971,30.7068391;76.8364112,30.707102;76.8370545,30.7070416;76.8375311,30.7071512;76.8381529,30.7071841;76.8386261,30.7071072;76.8390004,30.7073084;76.8392439,30.7077858;76.8398152,30.7085753;76.8379538,30.7080006;76.8337036,30.7098353;76.8331016,30.7099563;76.832382,30.7101297;76.8311765,30.7110855;76.8325899,30.7120769;76.8331288,30.7124152;76.833017,30.7129707;76.8328338,30.7136925;76.8314033,30.7148749;76.8311831,30.715998;76.8308713,30.7155462;76.8306836,30.7152207;76.8316634,30.7164048;76.8322951,30.7168241;76.8324719,30.7174047;76.8324351,30.7177697;76.8330243,30.7171083;76.8333887,30.7172871;76.8338149,30.7173746;76.8341968,30.717545;76.8344133,30.7179081;76.8341826,30.7182362;76.8337573,30.7173655;76.833327,30.7173427;76.8329368,30.7170438;76.8326111,30.7175154;76.8322909,30.7177829?radiuses=16;24;10;15;16;15;10;16;24;26;32;32;48;32;21;32;47;25;11;18;17;16;27;28;48;15;10;31;22;29;31;36;49;31;29;12;24;48;43;32;15;18;22;19;24;21;30;15;10;13;10;23;27;13;24;23;38&timestamps=1529306432;1529306443;1529306474;1529306575;1529306585;1529306595;1529306616;1529306820;1529306830;1529306841;1529306906;1529307060;1529307070;1529307119;1529307342;1529307363;1529307423;1529307473;1529307494;1529307694;1529307719;1529307800;1529307825;1529307846;1529307989;1529308010;1529308149;1529308307;1529308337;1529308446;1529308498;1529308513;1529308530;1529308548;1529308568;1529308579;1529308589;1529308600;1529308630;1529308641;1529308662;1529308921;1529309052;1529309064;1529309082;1529309092;1529309137;1529309246;1529309289;1529309391;1529309422;1529309523;1529309759;1529309819;1529309955;1529310026;1529310046&bearings=74,45;57,45;3,45;321,45;321,45;0,45;358,45;285,45;242,45;207,45;111,45;10,45;337,45;356,45;357,45;345,45;314,45;268,45;218,45;147,45;84,45;75,45;85,45;80,45;93,45;79,45;40,45;27,45;321,45;273,45;289,45;284,45;299,45;1,45;52,45;22,45;348,45;330,45;332,45;280,45;208,45;206,45;43,45;33,45;4,45;68,45;101,45;68,45;69,45;44,45;357,45;265,45;234,45;247,45;278,45;321,45;314,45&geometries=geojson&gaps=ignore


The following are the snapshots for the above query:

- Orange points are the raw points supplied to match

- Red points are the snap to road points resolved by match api (comes under `tracepoints` in the response)

- lines are the geometry for each leg in the response, each leg of different color.


1. 
![image](https://user-images.githubusercontent.com/20557574/42627816-c0956f0c-85eb-11e8-96d8-14449a52fc9a.png)

2. 

![image](https://user-images.githubusercontent.com/20557574/42628043-82cc066c-85ec-11e8-94ce-0857a578352a.png)

3. 
![image](https://user-images.githubusercontent.com/20557574/42628113-b54e23f4-85ec-11e8-80c6-3260be65c62d.png)
