### ISSUE TITLE
Windows Binaries Release History

### ISSUE THREAD

**Issue by waydec** [Project-OSRM/osrm-backend#4165]
I have found the latest Windows binaries at http://build.project-osrm.org
Is there a page with a release history for Windows binaries?

**Comment by daniel-j-h** [comment]
There is no release history with old releases for Windows. You can grad a release from here

https://github.com/Project-OSRM/osrm-backend/releases

and compile it yourself

https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation

Sorry but we don't have active Windows developer and no one from the community stepping up to handle all the Windows issues and open tasks.
