### ISSUE TITLE
Publish Node.js bindings for Windows

### ISSUE THREAD

**Issue by duizendnegen** [Project-OSRM/osrm-backend#4171]
`403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.8.0-latest.1/Release/node-v48-win32-x64.tar.gz`

Tried to guess the correct URL for a bit but then gave up.

**Comment by daniel-j-h** [comment]
We only build binaries for Linux and macOS (and only for Node 4 and 6, the LTS versions).

I guess you can always build from source,

    npm install --build-from-source

**Comment by SiarheiFedartsou** [comment]
We already publish it for Windows
