### ISSUE TITLE
Stricter vtile test

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/osrm-backend#4177]
The test at https://github.com/Project-OSRM/osrm-backend/blob/99b02cedfbfc6fb24f6b07dedd6df37e885690a9/test/nodejs/tile.js#L11 is not strict. We should ideally assert the exact length to be able to detect unexpected changes.

**Comment by daniel-j-h** [comment]
@danpat do you remember why the tile size changed a bit every now and then? I can vaguely remember we had an issue there. If this is fixed can you make the test strict, if not close here and link ticket.

**Comment by danpat** [comment]
We were *previously* adding features to the files in a non-deterministic order - depending on the platform you were on, the PBF encoder generated different byte sequences for equivalent data (only different was feature order).

This should be fixed now and we can make the test strict.
