### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [Project-OSRM/osrm-backend#4179]
Based on https://github.com/Project-OSRM/osrm-backend/releases it's not clear to me whether 5.7.0 or 5.8.0 is the current stable release version. Could you please clarify which should be in Homebrew designated as the stable version? Thanks!

**Comment by daniel-j-h** [comment]
Hey @ilovezfs - @TheMarex just tagged a v5.8 stable release and we're still in the process of writing release mails and drafting a Github release. Expect this to roll out in the next hours. 5.8 is stable now.

You're a bit too fast for us on this one :)

**Comment by ilovezfs** [comment]
Thanks for clarifying!
