### ISSUE TITLE
Width of way elements

### ISSUE THREAD

**Issue by thunder39** [Project-OSRM/osrm-backend#4180]
Hello,

Is it possible to access/calculate the width of an area in OSRM when there is no width tag? As far as I know streets, railtracks, waterways are mapped as area. I believe this information needs to be somewhere to render the maps correctly even if you don't specifically add a tag. The question is if you can create a routing where wider roads are preferred over smaller ones.

Thanks in advance for any help!

**Comment by daniel-j-h** [comment]
We don't do area routing, see https://github.com/Project-OSRM/osrm-backend/issues/64. Streets are mapped as [ways](http://wiki.openstreetmap.org/wiki/Elements).

In the default profiles we add penalties for ways based on their width [here](
https://github.com/Project-OSRM/osrm-backend/blob/99b02cedfbfc6fb24f6b07dedd6df37e885690a9/profiles/lib/handlers.lua#L308).

You can do the same adapt your profile and in the `way_function` to adjust weights and speeds based on a street's width tag (and maybe also lanes tags to derive the street width).

- http://wiki.openstreetmap.org/wiki/Key:width
- http://wiki.openstreetmap.org/wiki/Lanes

**Comment by thunder39** [comment]
Thanks! Got it! In my case I'm actually looking for routing on water and want to decide which river to take. I assume if there's no width tag present there's no chance for me to route accordingly?
Or I've to start tagging all the rivers with the width tag myself. Correct?

**Comment by daniel-j-h** [comment]
I don't know anything about water tagging - sorry. You have to check the OpenStreetMap wiki for the tagging schema and ask around on the OpenStreetMap IRC channel and/or tagging mailinglist.

From a conceptual point of view you won't get good instructions out of osrm when routing on water (same applies e.g. to railway routing). Speeds, ETAs and geometry should be fine, I guess.

**Comment by daniel-j-h** [comment]
Closing here as not actionable on our side.

Feel free to report back when you're doing waterway routing ;-)
