### ISSUE TITLE
restricted area

### ISSUE THREAD

**Issue by boooch** [Project-OSRM/osrm-backend#4183]
Hello!
I need to implement one feature. I have several vehicles and every of them have their own restricted zones, pointed by polygon on the map.  When I ask in OSRM for some route for one of my vehicle, how can I  tell OSRM to ignore all nodes in restricted zones for special vehicle. I cannot use several instances of OSRM because I can have 100 vehicles with 100 restricted zones, so I need to tell OSRM what to ignore on the fly. 
How can I implement this functionality?
Thanks for advise.

**Comment by daniel-j-h** [comment]
Without multiple instances and doing the decision at query time your only option will be: https://github.com/Project-OSRM/osrm-backend/issues/4006

Closing here as not actionable on our side - we're already working on the runtime avoid feature.
