### ISSUE TITLE
[Docker] pbf parsing error

### ISSUE THREAD

**Issue by neilRGS** [Project-OSRM/osrm-backend#4184]
Hi all. I hope someone can throw some light onto my issue.
No matter how much I try, changing the size in the .stxxl file and so on, I keep getting an iostream error.

Here is my latest attempt at parsing europe-latest.osm.pbf

```
[ec2-user@ip-172-31-31-167 osrmdata]$ sudo docker run -e STXXLCFG=/data/.stxxl -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/foot.lua /data/europe-latest.osm.pbf
[info] Using script /opt/foot.lua
[info] Input file: europe-latest.osm.pbf
[info] Profile: foot.lua
[info] Threads: 4
[info] Parsing in progress..
[STXXL-MSG] STXXL v1.4.1 (prerelease/Release) (git e7d36edd8152c73b115bd36cbcf566626d995434)
[STXXL-MSG] Disk '/tmp/stxxl' is allocated, space: 38146 MiB, I/O implementation: syscall autogrow queue=0 devid=0
[info] input file generated by osmium/1.5.1
[info] timestamp: 2017-06-15T20:43:50Z
TBB Warning: Exact exception propagation is requested by application but the linked library is built without support for it
terminate called after throwing an instance of 'tbb::captured_exception'
  what():  Error in virtual void stxxl::syscall_file::serve(void*, stxxl::file::offset_type, stxxl::file::size_type, stxxl::request_interface::request_type) :  this=0x7f3fccbdb560 call=::write(fd,buffer,bytes) path=/tmp/stxxl fd=6 offset=9219080192 buffer=0x7f3fc36c2000 bytes=2097152 type=WRITE rc=-1 : I/O error: iostream error: iostream error
```
If anyone has any ideas as to where I am going wrong, it would be hugely appreciated.

Many thanks,

Neil.

**Comment by danpat** [comment]
Looks sort of like you're running out of space.  I think STXXL might allocate a sparse file at startup, so disk does actually get used until it's touched by data.

**Comment by neilRGS** [comment]
Thanks Daniel.
Any idea how much space it needs? I have an 80GB drive with 59G free and allocated 45G in stxxl.
europe-latest.osm.pbf is about 18G, so perhaps the extraction needs a whole lot more than I have.

Are there any figures anywhere as to space recommendations for these, I wonder?

Advice, as always, is appreciated.

N.

**Comment by danpat** [comment]
The only number we track regularly is the processing that the demo server does - it takes about 300GB of disk and 170GB of RAM for the whole planet with the car profile.

Actual needs are based on the OSM extract you use, and the profile you select - the foot profile has the biggest needs because it includes the most number of ways (you can walk more places than you can drive).

Last time I checked I think the foot profile needed about 245GB of RAM for the planet on the foot profile. I'd expect a corresponding jump in STXXL usage as well, but I don't have the numbers handy.

**Comment by neilRGS** [comment]
Thanks Daniel.
That's food for thought indeed.

Regards,
Neil.

**Comment by danpat** [comment]
Closing this as not actionable by us - @neilRGS if you uncover something that is *not* a simple out-of-space problem, please re-open this ticket.
