### ISSUE TITLE
How to move phantom node to the junction of the closest way

### ISSUE THREAD

**Issue by frodrigo** [Project-OSRM/osrm-backend#4192]
We are trying to route from the closest junction of the closest osm segment of the starting point.

We are trying to recompute the phantom node to move it to one ends of the osm segment where the phantom node was. But we can't achieve to code a working solution by patching geospatial_query.hpp

The main idea beyond this is to not enter in the street for a via point when the overall route is the shortest by just passing at the closest junction. Especially interesting when no u-turn is possible or on one way street.

Please, can you give us a hint on this ?

**Comment by daniel-j-h** [comment]
Discussion in https://github.com/Project-OSRM/osrm-backend/pull/4272. Closing as not easily feasible and not on actionable on our side.
