### ISSUE TITLE
maximum input size of service match 

### ISSUE THREAD

**Issue by hesseljonker** [Project-OSRM/osrm-backend#4195]
Hey,

I want to match a gps trace of 160 coordinates with the service match but this is limited to 100 coordinates. Can I change this limited? And if so, how can I do this locally?

Hessel

**Comment by danpat** [comment]
Assuming you're using `osrm-routed`, you can get the configurable options by running `osrm-routed --help`.

The maximum coordinate count for map matching can be configured there.

**Comment by hesseljonker** [comment]
Thank you for your response. 

Issue #4051 answers my question.

**Comment by wangzi6578** [comment]
hello,how could i change that
