### ISSUE TITLE
Best way to update OSRM maps

### ISSUE THREAD

**Issue by amit1rrr** [Project-OSRM/osrm-backend#4196]
I have an existing OSRM setup with country X maps loaded into it. Now I want to update the maps with country Y (in addition to X). Is there a process for update or do I have to get these pbf files merge it and run a new setup from scratch?

**Comment by danpat** [comment]
You will need to merge the `.pbf` files and re-run the processing from scratch.  The data structures inside OSRM are not designed to be added to after-the-fact.
