### ISSUE TITLE
Expose user-defined class information

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#4203]
Breaking this out from https://github.com/Project-OSRM/osrm-backend/issues/4006 we need a way to set a user-defined class per edge and use this in the server. This will enable features like displaying when a route is using a toll road, or a private road.

### Lua profile

Instead of hard-coding specific classes for #4006 we want to keep this more general. This requires us to have an interface in the profiles to mark ways with `true`/`false` if they fall into that class.

```lua
function way_function(way, result)
   result.classes['highway'] = way:get_value_by_key('highway') == 'motorway'
   result.classes['ferry'] =  way:get_value_by_key('route') == 'ferry'
end
```

### HTTP/node

We can expose this as a new property `classes` in the `RouteStep` object, that is only there if there is class information for that step.

- `classes`: An array of strings signifying the classes of the road as specified in the profile.

Example:

```json
{
   "geometry" : "{lu_IypwpAVrAvAdI",
   "mode" : "driving",
   "classes": ["toll", "highway"],
   "duration" : 15.6,
   "weight" : 15.6,
   "intersections" : [
      {  "bearings" : [ 10, 92, 184, 270 ],
         "lanes" : [
            { "indications" : [ "left", "straight" ],
               "valid" : "false" },
            { "valid" : "true",
               "indications" : [ "right" ] }
         ],
         "out" : 2,
         "in" : 3,
         "entry" : [ "true", "true", "true", "false" ],
         "location" : [ 13.39677, 52.54366 ]
      },
      {  "out" : 1,
         "lanes" : [
            { "indications" : [ "straight" ],
               "valid" : "true" },
            { "indications" : [ "right" ],
               "valid" : "false" }
         ],
         "bearings" : [ 60, 240, 330 ],
         "in" : 0,
         "entry" : [ "false", "true", "true" ],
         "location" : [ 13.394718, 52.543096 ]
      }
   ],
   "name" : "Lortzingstraße",
   "distance" : 152.3,
   "maneuver" : {
      "modifier" : "right",
      "type" : "turn"
   }
}
```

**Comment by danpat** [comment]
We should probably add something to `annotations` as well, in case someone wants the full route details:

```
annotations : { "classes" : [ ["highway","ferry"], ["highway"],["highway"],["highway"],["ferry"],["ferry"],["highway","ferry"] ] }
```

This would allow for correct rendering of various route sections if desired.

**Comment by emiltin** [comment]
how will this work together with the mode, they are still separate flags?
for example, if the mode is ferry, i could potentially indicate 8 different types of ferry routes with the classes?

**Comment by TheMarex** [comment]
@emiltin yep separate flags.

**Comment by TheMarex** [comment]
This was added with #4204.
