### ISSUE TITLE
node-osrm produces TypeError: vector::_M_default_append

### ISSUE THREAD

**Issue by pailakka** [Project-OSRM/osrm-backend#4207]
Running:
```
wget http://download.geofabrik.de/europe/finland-latest.osm.pbf
sudo docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/finland-latest.osm.pbf
sudo docker run -t -v $(pwd):/data osrm/osrm-backend osrm-contract /data/finland-latest.osrm
```
and then using node-osrm:
```
npm install osrm
node -e "var OSRM = require('osrm'); var r = new OSRM('finland-latest.osrm');"
```

produces
```
TypeError: vector::_M_default_append
    at TypeError (native)
    at Object.<anonymous> (/home/ubuntu/gtfs-shape-router/generate_shapes.js:9:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

osrm-backend and node-osrm are both version v5.8.0

**Comment by daniel-j-h** [comment]
What's your operating system you're trying to run the Node.js bindings on? This might be a C++ ABI issue.

Also: make sure your `osrm-*` binaries match the Node.js binding version. The easiest way to do so is to use the `osrm-*` binaries we ship with the bindings:

    npm install osrm

    ./node_modules/osrm/lib/binding/osrm-extract ...

https://github.com/Project-OSRM/osrm-backend/blob/master/docs/nodejs/api.md#osrm

Then make sure your stdlib is recent enough, see

https://github.com/Project-OSRM/osrm-backend#using-the-nodejs-bindings

**Comment by pailakka** [comment]
```
ubuntu@ip-10-0-0-197:~/osrm-backend$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

I'll try using shipped binaries, good to know they exists :)

**Comment by pailakka** [comment]
Using shipped osrm-backend binaries seems to work like a charm. Thanks!

**Comment by daniel-j-h** [comment]
Great to hear - happy routing! ✨
