### ISSUE TITLE
osrm 5.8.0 doesn't build for node v7

### ISSUE THREAD

**Issue by stvno** [Project-OSRM/osrm-backend#4216]
Installing osrm 5.8.0 fails on node v7 with the following error:
```
-- Building node_osrm
CMake Error at src/nodejs/CMakeLists.txt:11 (include):
  include could not find load file:

    NodeJS

CMake Error at src/nodejs/CMakeLists.txt:12 (nodejs_init):
  Unknown CMake command "nodejs_init".
```
Using node 7.10:
```
$ node -v
v7.10.0
```
and installing osrm 5.8.0 as such:
```
 "dependencies": {
    "osrm": "^5.8.0"
    }
```

However using node v6 there is no issue
```
$ node -v
v6.11.0
```

```
$ npm install osrm

> osrm@5.8.0 install /path/node_modules/osrm
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

[osrm] Success: "/path/node_modules/osrm/lib/binding/node_osrm.node" is installed via remote
```

**Comment by TheMarex** [comment]
You will need to compile from source, since we don't build binaries for node 7 yet.

What should work is:

```
# first install NodeCMakeJS
npm install --ignore-scripts
# Now run the build/fallback
npm install
```

**Comment by stvno** [comment]
That works, thanks!
Though I never had this problem before; it would build from source when necessary on a `npm install osrm`. I've been running osrm on node v7 for quite some time now.

**Comment by TheMarex** [comment]
Yes the first step with `--ignore-scripts` should not be necessary. Maybe we introduced a cyclic dependency by accident, needs investigation.

**Comment by TheMarex** [comment]
Capturing from slack:

We need to move the following packages to `bundledDependency`:

- [ ] `node-cmake`
- [ ] `nan`
