### ISSUE TITLE
Update OpenStreetMap Wiki for OSRM

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4223]
It looks like the OpenStreetMap wiki is badly outdated wrt. OSRM. We should update at least some screenshots, tell people about the features we added in the last ~2 years and bring the information up to date.

Pages I found (there may be more):
- http://wiki.openstreetmap.org/wiki/Open_Source_Routing_Machine
- http://wiki.openstreetmap.org/wiki/Routing

**Comment by daniel-j-h** [comment]
cc @1ec5 ;-)

**Comment by 1ec5** [comment]
I did my best with the OSRM article. Let me know if I’m missing anything, or feel free to improve the article as you see fit. 🙂 Another important task is ensuring that OSRM is mentioned on all the relevant pages at the wiki.

**Comment by 1ec5** [comment]
Also updated and corrected [the Spanish translation](https://wiki.openstreetmap.org/wiki/ES:Open_Source_Routing_Machine). I can’t help with the [French translation](https://wiki.openstreetmap.org/wiki/FR:Open_Source_Routing_Machine) (which has some additional content).

**Comment by daniel-j-h** [comment]
🚀
