### ISSUE TITLE
Car profile should discard construction highways

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4230]
We check for `avoid.construction` here

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/handlers.lua#L475

but do not have it in the car profile's avoid sequence here

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L107-L114

we have it in the bike profile, though.

**Comment by danpat** [comment]
@daniel-j-h under-construction highways are tagged as `highway=construction` - the `construction` value of the `highway=` key is not a value we recognize, so the road won't be included.

A quick test with `profiles/debug_example.lua` shows that the `car` profile doesn't include `highway=construction` tags:

```
$ lua debug_car.lua
{
  highway = 'construction',
  name = 'Magnolia Boulevard'
}
=>
{
  backward_mode = 1,
  backward_speed = -1,
  duration = 0,
  forward_mode = 1,
  forward_speed = -1,
  road_classification = {}
}
```

It looks like the `bicycle.lua` profile behaves differently here - all `highway=` tags are considered valid, except for items in the `avoid` list:

Here, I've removed `avoid.construction`, and the `bicycle` profile includes the way:

```
$ lua debug_bicycle.lua
{
  highway = 'construction',
  name = 'Magnolia Boulevard'
}
=>
{
  backward_mode = 0,
  backward_speed = -1,
  duration = 0,
  forward_mode = 0,
  forward_speed = -1,
  name = 'Magnolia Boulevard',
  road_classification = {
    may_be_ignored = true,
    road_priority_class = 31
  }
}
```

So the logic is a bit different in each profile.  That's probably not ideal, but the good news is that we're not routing cars over `highway=construction`.

**Comment by 1ec5** [comment]
There’s also an older way to tag roads under construction:

```
highway=cycleway
construction=yes
```

or even in the planning stages:

```
highway=motorway
proposed=yes
```

Like most renderers and routers these days, OSRM ignores the `construction=yes` and `proposed=yes` tags. I guess that’s fine as long as we double-check any existing uses: osmlab/to-fix#215.

Many of these tags were added several yeras ago, so it’s entirely possible that OSRM gets lucky and the `construction=yes` ways have long finished construction. On the other hand, `proposed` ways are always a big question mark: some mappers zealously draw out planned road corridors as proposed roads, even though the plans aren’t precise enough to map as roads by that stage.

**Comment by emiltin** [comment]
just to clarify, the bike profile does not route on way with unknown highway tag values, unless access tags are set. the output above shows the mode is set to 0, which makes it unroutable.

we should add 'construction' in the list of things to avoid for cars. and why not improve update the handler to avoid ways tagged the old scheme construction=yes or proposed=yes

**Comment by 1ec5** [comment]
> we should add 'construction' in the list of things to avoid for cars. and why not improve update the handler to avoid ways tagged the old scheme construction=yes or proposed=yes

That’s reasonable. At the same time, any occurrence of the old tagging scheme is likely to be outdated and should be double-checked for accuracy.

**Comment by emiltin** [comment]
right. it's possible it's better to just ignore the old tags
