### ISSUE TITLE
Consider Lanes in Fork Discovery

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#4233]
Forks can be a useful instruction, if used right. In the context of highway ramps, they might feel out of place sometimes.

For example at this location: [osm](https://www.openstreetmap.org/way/59763350#map=19/37.79994/-122.46978) [mappilary](https://www.mapillary.com/app/?lat=37.80004444444444&lng=-122.46944166666668&z=17&pKey=euHn7YCR1kjmZwsFL5iUGQ&x=0.5015436464349068&y=0.617299372749043&zoom=1&focus=photo).

![thumb-2048](https://user-images.githubusercontent.com/12932279/27823276-ddc8a026-60a8-11e7-8078-58ae263e55db.jpg)

To improve fork detection, we could make use of the number of lanes at roads:

![lanes-at-forks](https://user-images.githubusercontent.com/12932279/27823156-7140113c-60a8-11e7-9037-aa40a85c0e46.png)

If two lanes enter + exit with a nearly straight angle and a third one turns, the situation is most likely not a fork and we could emit a `turn right` for exiting.

Actions to achieve this would be:

 - [ ] Find a set of test locations that match the above criteria
 - [ ] detect the above scenario in the fork handler
 - [ ] expose correct instructions
   - [ ] decide on best instructions for continuing (probably no instruction at all?)
   - [ ] decide on best instruction for turning: `keep right` `take the ramp` (ramp from ramp)?
- [ ] Verify that changes applied to the test locations
- [ ] Verify that changes do not change unrelated forks

**Comment by willwhite** [comment]
@MoKob it's not clear what the problematic behavior is on this issue. Can you like to a route and describe the behavior that you don't like?

**Comment by danpat** [comment]
@willwhite Example route:

http://map.project-osrm.org/?z=18&center=37.800483%2C-122.468290&loc=37.798908%2C-122.469422&loc=37.801523%2C-122.469379&hl=en&alt=0

We currently issue a "keep left at the fork", or "keep right at the fork", depending on which way direction your route goes.

Instead, we could be doing "continue straight" for the straight-looking, two-lane highway (or not issuing any instruction at all if it's the obvious way to go), and "take the ramp on the right" for the ramp that splits off.

**Comment by MoKob** [comment]
#4295 is probably the better place for discussion here. Lanes might be just a way to do this. Keeping the discussion at #4295 and closing here.
