### ISSUE TITLE
Handle `no_entry` and `no_exit` turn restrictions

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4241]
Currently we only handle `(fromWayId, viaNodeId, toWayId)` turn restrictions and work for handling way-vias is in progress https://github.com/Project-OSRM/osrm-backend/issues/2681.

What we don't consider at all is `no_entry` and `no_exit` which can have _multiple from and to_ ways, respectively - see spec: http://wiki.openstreetmap.org/wiki/Relation:restriction#Members

What we should do is
- [ ] detect `no_entry` and `no_exit` turn restrictions
- [ ] insert multiple `(from, via, to)` turn restrictions for all `from` and for all `to` ways
- [ ] add cucumber tests for `no_entry` and `no_exit` (might require updating support code)
- [ ] update `taginfo.json`
- [ ] update changelog

**Comment by MoKob** [comment]
@daniel-j-h I just checked taginfo, it seems like there are 5 tags using `no_entry`, none for `no_exit`. I guess we can skip on supporting these?

**Comment by daniel-j-h** [comment]
You need to check for `relation=no_entry/no_exit`

- https://taginfo.openstreetmap.org/tags/restriction=no_entry 419
- https://taginfo.openstreetmap.org/tags/restriction=no_exit 170

given that these transform to multiple simple turn restrictions I would love to have them in.

**Comment by daniel-j-h** [comment]
@MoKob with your turn restriction work merged into master what's your assessment here? What specifically needs to be done and can we simply add multiple "simple" turn restrictions for these tags?

**Comment by MoKob** [comment]
@daniel-j-h yes, we would need to translate the single restriction into multiple ones to allow this.
It requires:

 - [ ] translating a restriction into multiple node restrictions
        - adjust [this](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/restriction_parser.cpp#L133-L181) to not handle single from/via/to but multiple
        - output multiple node-restrictions for all n*m combinations

 - [ ] hand off multiple restrictions [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/scripting_environment_lua.cpp#L652-L657)
