### ISSUE TITLE
Load graph before opening a socket in the osrm-routed

### ISSUE THREAD

**Issue by gardster** [Project-OSRM/osrm-backend#4245]
Amazon ELB balancer can't determine osrm-routed start on redeploy.

When we use a tcp health check it determines osrm-routed opened port and sends requests while osrm-routed loads a road graph.
When we use a http health check on a large graph it kills it after 120 seconds of loading data without answer.

Also it looks strange, that port open, but requests will not processed for some time.

**Comment by TheMarex** [comment]
Fixed by issue #4246
