### ISSUE TITLE
Multiple requests at the same time

### ISSUE THREAD

**Issue by CharlFM** [Project-OSRM/osrm-backend#4250]
I would like to push multiple requests to the OSRM backend at once.  Since, I need to do this for more than 2m rows... So I would like to know if I can send the docker image multiple requests at the same time?

What I am doing currently is something like : 
curl "http://127.0.0.1:5000/route/v1/driving/10.01,50.05;10.05,52.02?overview=false"
curl "http://127.0.0.1:5000/route/v1/driving/10.51,51.09;10.64,51.33?overview=false"

My current solution is to include multiple points and take the result of each distance:
curl "http://127.0.0.1:5000/route/v1/driving/10.01,50.05;10.05,52.02;10.51,51.09;10.64,51.33;10.53,51.19;10.62,51.22;10.11,51.32;10.12,51.55;11.11,51.11;11.43,52.43?overview=false"

However, this request is much slower than the initial. 

Any suggestions?

**Comment by emiltin** [comment]
for best speed, you include the osrm lib directly in your code. this will eliminate all the http overhead.

**Comment by daniel-j-h** [comment]
Yep, either use node-osrm (Node.js) or libosrm (C++) directly, or if possible use the table service just in case you're trying to compute a drive-time matrix with those requests:

http://project-osrm.org/docs/v5.7.0/api/#table-service

Note: you will find duration and weight in there but currently not distance - what you can do is adapt the car profile and spawn up a local instance or look into https://github.com/Project-OSRM/osrm-backend/pull/2764.

Also you're curl calls above don't have to be serialized, `osrm-routed` happily answers requests in parallel

    curl &
    curl &
    wait

or look into `xargs -P` or GNU `parallel`.

**Comment by CharlFM** [comment]
Thanks for the comments! I really appreciate it, I am coding in R. So coding in C++ is not possible for me (unfortunately for the moment).
If you would know how to embed the osrm lib in R, please let me know. Otherwise from what @daniel-j-h mentioned, I assume what you mean is, I can do:

curl "http://127.0.0.1:5000/route/v1/driving/10.01,50.05;10.05,52.02?overview=false" &
curl "http://127.0.0.1:5000/route/v1/driving/10.51,51.09;10.64,51.33?overview=false" &
wait

is this indeed what you meant?

**Comment by CharlFM** [comment]
Sorry if the questions might be a bit basic...

**Comment by daniel-j-h** [comment]
I know someone created an R library (https://github.com/rCarto/osrm) maybe it helps with your use-case.

In bash the `&` at the end of the line spawns a new process and the `wait` waits until all are done.

**Comment by CharlFM** [comment]
@daniel-j-h I just tried the bash with the &, and indeed this speeds it up significantly! 

Thanks a lot for the advice!

**Comment by daniel-j-h** [comment]
Great to hear! Happy routing! :)
