### ISSUE TITLE
[error] Input file .osm.pbf not found!

### ISSUE THREAD

**Issue by Lifeuser** [Project-OSRM/osrm-backend#4253]
Hello everyone! I have the same issue as this one:
https://github.com/Project-OSRM/osrm-backend/issues/4095

File sharing with docker by default works with /Users and its subdirectories...

Don't know what to do really...

MacOS Sierra 10.12.5 , latest docker and container.

![screen shot 2017-07-07 at 15 11 54](https://user-images.githubusercontent.com/2346053/27957377-ed367d5a-6326-11e7-8650-4ec4f785c703.png)

**Comment by oxidase** [comment]
@Lifeuser the OSM file path must be in a docker image file system. The option `-v $(pwd):/data` mounts the current work directory on the host to `/data` mounting point in the image. 

You can try `/data/central-fed-district-latest.osm.pbf` if the host working directory is `/Users/lifeuser`

**Comment by Lifeuser** [comment]
Got it now! Works fine, thank you!
