### ISSUE TITLE
.gitattributes file causing repository checkout/update/etc. issues

### ISSUE THREAD

**Issue by gsmcwhirter** [Project-OSRM/osrm-backend#4257]
After a clean clone of the repository onto an ubuntu 16.04 machine, I am perpetually stuck with the following:

    On branch master
    Your branch is up-to-date with 'origin/master'.
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)
    
            modified:   cmake/FindTBB.cmake
            modified:   example/cmake/FindTBB.cmake
    
    no changes added to commit (use "git add" and/or "git commit -a")

Some research led me to figuring out that this is related to the .gitattributes file that was apparently added 4 days ago.

What I was generally trying to accomplish was:
1. `clone` repo (ok)
2. pull tag list with `git fetch` (ok)
3. check out a particular tag (fails due to modified files in the working set)

I also tried doing `git stash`es, `git reset --hard`s, `git clean -df`s, and nothing fixed it. I am currently cloning the repository directly to the desired tag with `git checkout --branch <tag>` but that is not exactly ideal.

**Comment by daniel-j-h** [comment]
Yep ran across the same yesterday - this should fix the problem https://github.com/Project-OSRM/osrm-backend/pull/4254
