### ISSUE TITLE
mode inference

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#4262]
OSRM already handles map matching. A related task is inferring the mode of each part of a trip, ie. walk, bike, car, public transport, etc.

Work is currently ongoing to make it possible for OSRM to handle several routing profiles in a single process. This would make it possible to work with mode inference.

Mode inference is build into iOS and Android, but is not always very accurate. Or data might be collected from GPS equipment that can't do any kind of mode inference.

Inference would involve estimating what routing profile best matches each part of the trip and could be based on things that differ between profiles, like:

- Network and access restrictions
- Max/min/average speed
- Turn restrictions
- Barriers
- Possible start/stop/change points

**Comment by daniel-j-h** [comment]
What you already can do is map match your traces against three stacks in parallel: car, bike, walk.

The compare the matching confidence.

Is this what you want to do?

**Comment by emiltin** [comment]
close, but what if the car/bike/walk results have different start/stop points? i would prefer to pass the gps points to a single api call and get back a best guess of what transport mode was used for what parts of the route.

it might also be possible to implement it so it's faster than running the same query against all three stacks.

**Comment by MoKob** [comment]
@emiltin I don't believe that having a single stack alone would solve these issues. We would still require to find a mode and based on this do different start points / queries. A car query from a park that only allows walking would surely fail. Having many datasets accessible does no necessarily help here.
When starting with map-matching, the main problem would be that the fastest route between two points would surely be the car route. The map-matching algorithm assumes that between two points you will take the fastest route. So I believe that there needs to be some investment before we could assume a mode simply based on matching the GPS to a graph containing all metrics.

**Comment by daniel-j-h** [comment]
Closing as not actionable on our side.

**Comment by emiltin** [comment]
i still think it would be an extremely useful feature, and i have a sense that the building blocks are there - but ofcourse that easy for me to say :-)
