### ISSUE TITLE
Pre-compute segregated intersections

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#4273]
![roads](https://user-images.githubusercontent.com/12932279/28023950-a6fb116e-658f-11e7-97f3-b02da0825ba9.png)

In post-processing, we can only access the information along the shortest path. This information is limited in what we can access, especially with regards to the roads connected to the path itself.
For specific situations, we need to know about all the ways associated with the intersection of two turns.

In the above scenario, I would consider the two situations different based on the assigned names.
In I), we see a segregated intersection and we would consider the maneuvers shown to the right.

If we only change a minor detail, having a road `a` and  road `b` running next to each other, I would consider all of the turns at the intersection as two distinct maneuvers.
The distinction in post-processing between those situations is not possible, though.

Therefore I would like to propose a change in the paradigm of post-processing: Introduce an additional pre-requisite which shows that a turn is part of a complex intersection.
We could compute in pre-processing and for every turn if it is part of a complex maneuver (essentially identifying segregated intersections in pre-processing).
This would allow us to see locations that would actually partake in a collapse scenario (which we could evaluate on a map, rather than on routes coming in one at a time) and construct scenarios that get access to a lot more information, since we can actually traverse the full graph at that time.

Technically, we could implement a dedicated post-processing for MLD, but as long as we want to support multiple algorithms, we need to assume the graph as untraversable.

This would require:

 - [ ] detect segregated intersections in turn analysis
 - [ ] add a flag to instructions indicating whether they are part of maneuvers
 - [ ] update post-processing to require said flag on instructions (where appropriate)

The immediate benefits I see in this approach:
 - more resilient post-processing (we know where it happens)
 - simpler scenarios in post-processing (we did the leg-work already)
 - more advanced detection (e.g. like this double turn) [osrm](http://map.project-osrm.org/?z=18&center=38.903403%2C-77.019412&loc=38.905140%2C-77.015748&loc=38.904347%2C-77.015941&hl=en&alt=0)

![screen shot 2017-07-10 at 16 59 12 2](https://user-images.githubusercontent.com/12932279/28024497-29ebe8ea-6591-11e7-8c37-d5286cfa5524.png)

**Comment by TheMarex** [comment]
What would be the difference between dedicated flag and making the first left turn `Suppressed`?

**Comment by vng** [comment]
<img width="841" alt="screen shot 2017-09-25 at 5 16 14 pm" src="https://user-images.githubusercontent.com/175612/30816140-c3a855e0-a21d-11e7-8868-1a9a5c531c40.png">

Take a look here http://88.99.58.38/segregated.html
There is a first algorithm implementation that detects segregated nodes in real time for tile.

**Comment by MoKob** [comment]
@vng can you provide a bit more context on how that visualisation is chosen? What factors you consider?
From my understanding, what we desire would be more in the form of:
<img width="841" alt="30816140-c3a855e0-a21d-11e7-8868-1a9a5c531c40" src="https://user-images.githubusercontent.com/12932279/30816369-1895536c-a216-11e7-9976-ac84e732cef6.png">
Only the circled part should be an internal edge.

**Comment by MoKob** [comment]
I've looked closer on a random segment of the map. My understanding of the internal nodes would be as illustrated in this picture (Little Five Points, Atlanta):
![screen shot 2017-09-26 at 10 29 51 2](https://user-images.githubusercontent.com/12932279/30850873-31796198-a2a7-11e7-9501-b3a2ee9e2320.png)

Red shouldn't be an internal node. Yellow might be, depends on a view of satellite imagery to ensure correctness and green should be internal. As in my previous post, there might also be parts missing, but I can't find some immediately on the current screen shot.
Let me know if you want to chat about the current heuristics and whether we can come up with improvements together.

**Comment by vng** [comment]
1. Missing possible internal edge here http://www.openstreetmap.org/#map=19/38.90551/-77.01466 isn't detected because the only possible driving direction there is forward on New Jersey av nw. The road is oneway and left turns are forbidden.

2. I have some thoughts about how to eliminate some false internal edges and will work about it. Will keep in touch with the updates soon.

**Comment by vng** [comment]
http://88.99.58.38/segregated.html Updated demo to check current algorithm status.

**Comment by vng** [comment]
Linked some fresh issues, to check later.
https://github.com/Project-OSRM/osrm-backend/issues/4428
https://github.com/mapbox/directions-feedback/issues/635
https://github.com/mapbox/directions-feedback/issues/717

**Comment by oxidase** [comment]
Released in 5.17.0 :tada:
