### ISSUE TITLE
Deriving the most probable route from a set of sampled GPS coordinates

### ISSUE THREAD

**Issue by zoharby** [Project-OSRM/osrm-backend#4277]
We have an SDK (iOS + Android) which collects locations in the backround from mobile devices. These can be with varying accuracies, from several meters (GPS) up to hundreds of meters (3G cell triangulation).

I would like to be able to translate the locations sampled along a user's drive to the "most probable route" using OSRM. Using the naive solution of a waypoint for each sampled location produces poor results, because for example any location sample which falls slightly off a highway could be matched so some other small road, causing very long loops/bypasses which most likely didn't really happen.

This is illustrated in the following example, where the gray waypoint is just slightly off the highway but creates a very unlikely result:
![image](https://user-images.githubusercontent.com/6084508/28069796-69fe26c4-6653-11e7-8973-ebc4ff2fa87e.png)

Is there any solution to this problem using the current OSRM backend? Ideally, I'd like to pass a radius/accuracy for each waypoint, and instruct the server to choose the "best" route which falls inside the radius from this point.

**Comment by MoKob** [comment]
This is called map-matching. We have a service endpoint available. You can find the docs [here](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#match-service).

**Comment by zoharby** [comment]
Thanks! wasn't aware this existed...
