### ISSUE TITLE
`osrm-customize` missing from Docker image

### ISSUE THREAD

**Issue by saabeilin** [Project-OSRM/osrm-backend#4281]
I wanted to test the new MLD but unfortunately the newly introduced `osrm-customize` tool missing from official docker images, both `5.8.1` and `latest`:

From inside the container:
```
# ls /usr/local/bin/osrm-*
/usr/local/bin/osrm-components  /usr/local/bin/osrm-datastore   /usr/local/bin/osrm-partition
/usr/local/bin/osrm-contract    /usr/local/bin/osrm-extract     /usr/local/bin/osrm-routed
```

**Comment by danpat** [comment]
Woops, looks like it's missing from CMakeLists.txt.

I'll make a PR to fix this, but it won't show up until the next release.

**Comment by saabeilin** [comment]
Thanks in advance. Would be happy to test on latest/master/etc. image.

P.S. The `latest` tag on Docker hub refers really to `master` or... ?

**Comment by danpat** [comment]
@saabeilin yes - `latest` images point to `master`, and they're build automatically by Docker Cloud.  I think it takes an hour or two for the images to be published after changes are merged to `master`.

You can watch the builds progress here:

https://cloud.docker.com/app/osrm/repository/docker/osrm/osrm-backend/general
