### ISSUE TITLE
Map matching result quality

### ISSUE THREAD

**Issue by amit1rrr** [Project-OSRM/osrm-backend#4285]
I am evaluating OSRM map matching result. And have some observations to share using which we can improve the quality of the match. In the screenshots you can see input gps points (yellow dots), OSRM matched output (purple line), gmaps snap_to_roads output (green line).

**Issue 1**: For slightly longer distances OSRM match doesn't seem to interpolate points in between. As you can see there is straight purple line for curved road on right where as nice smooth line for curved road on left. On the other hand gmaps has interpolated points in between for both the curves and has smooth roads. Is there a distance threshold beyond which OSRM considers set of points as 2 separate segments? Can this threshold be configurable?

<img width="1654" alt="screen shot 2017-07-13 at 2 07 51 pm" src="https://user-images.githubusercontent.com/1350490/28160238-2c8246f0-67dd-11e7-8cbd-c8bb1febc66c.png">

**Issue 2**: OSRM match just plain removes points sometimes even though they are on road. You can see in the screen shot that 6 points after the turn got removed with match output. The street/way exists in the OSM database. What could be going on here? 

<img width="1433" alt="screen shot 2017-07-13 at 2 11 07 pm" src="https://user-images.githubusercontent.com/1350490/28160314-72a0d336-67dd-11e7-8567-7fc6903761f6.png">

Any inputs are appreciated. Thanks.

**Comment by daniel-j-h** [comment]
You should probably use `geojson-tidy` to tidy your traces or the `tidy=true` option when map matching for blob removal (see your first image top right) / resample your data.

You can force osrm not to split using the `gaps` option when map matching.

Check `tidy` and `gaps` here:

http://project-osrm.org/docs/v5.7.0/api/#match-service

And check the splitting implementation [here](https://github.com/Project-OSRM/osrm-backend/blob/30b8225812beb01360bd1efab5267d227ab960e9/src/engine/routing_algorithms/map_matching.cpp#L30).

**Comment by TheMarex** [comment]
@amit1rrr the problem is that you are not using the "interpolated" points but just the matched input points. If you use `matchings[i].geometry` you will get OSM-level resolution.

**Comment by amit1rrr** [comment]
@daniel-j-h 
So the tidy definition said,
"Allows the input track modification to obtain better matching quality for noisy tracks."

Currently I set tidy=False because I perform bunch of pre-processing to remove noise from raw recordings. Hence I don't expect OSRM match to remove noisy points or do input track modification but just perform match functionality in order to snap traces onto road. Will still give a try with tidy=true.

Going to also set gaps=ignore as there was about 7 minute time difference in the first issue where it probably split.

I'm still not sure about issue 2 and whether/how split or gaps option would help there. 

@TheMarex
I do use interpolated points. I iterate through all 'matchings' and then through all ['geometry']['coordinates'] of each matching, let me know if I am missing something.

**Comment by TheMarex** [comment]
@amit1rrr ah, I think passing `overview=full` might fix your problem. By default the geometry is simplified.

**Comment by amit1rrr** [comment]
Going to close this issue. I set tidy=True and it has helped. Setting gaps=ignore or overview=full have both shown regressions in the matching quality in my test suite.  ovetrview=full also returns super bloated result, which is probably not needed for our purpose.

We still randomly see some good points on the road being removed by OSRM match. My plan is to fill in these gaps with OSRM route. Will open a separate issue if I face more problems.

**Comment by rbhatia46** [comment]
@amit1rrr Can you please tell me how to visualize the output of map matching obtained from the osm backend?
I have installed osrm-frontend but cant seem to figure out how to visualize the output

**Comment by nurgasemetey** [comment]
@rbhatia46 Just copy geojson from response and visualize on https://geojson.io
