### ISSUE TITLE
Don't emit `Notification` instructions for class changes

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#4290]
As per voice with @bsudekum we decided to not emit `Notification` instructions on `classes` changes.

I would this propose the following change:

Move the `classes` from `RouteStep` to the `Intersection`:

```json
{
    "location":[13.394718,52.543096],
    "in":0,
    "out":2,
    "bearings":[60,150,240,330],
    "entry":["false","true","true","true"],
    "lanes":{
        "indications": ["left", "straight"],
        "valid": "false"
    },
    "classes": ["toll", "highway"]
}
```

**Comment by daniel-j-h** [comment]
Ah, so we will always have the classes available and the client can detect 1/ a new class was added and 2/ an existing class was removed - see https://github.com/Project-OSRM/osrm-backend/pull/4204#issuecomment-313340990.

**Comment by daniel-j-h** [comment]
This landed with https://github.com/Project-OSRM/osrm-backend/issues/4292.
