### ISSUE TITLE
Any option to use car.lua and foot.lua together?

### ISSUE THREAD

**Issue by emregurler** [Project-OSRM/osrm-backend#4297]
Hi, I am very grateful to use your project.
Nowadays, I need to use 2 option together: car.lua and foot.lua . I know that we choose profile at the beginning (OSRM-extract) with -p. 
However, I sometimes need foot profile instead of car. Is there any option to do in the same time? I mean I run extract command just for once, and I expect that I can do request for car and also foot depends on my need. I searched this in the issues, but i didn't find my answer.
Thanks.

**Comment by daniel-j-h** [comment]
Not possible at the moment. You have to run the full pipeline per profile.

This may change in the future but for now what we recommend is running the pipeline for car and bike independently of each other and then starting two `osrm-routed` servers.

**Comment by emregurler** [comment]
Thansk for fast reply.
