### ISSUE TITLE
default profile settings

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#4307]
should we have default profile settings for things like suffix_list, construction_whitelist, restricted_access_tag_list and service_tag_forbidden? stuff that's usually the same for most profiles. a profile would still be free to change a default setting.

it would be easy to do with the v2 profile api where you can include a base profile which would set the defaults.

pros:
- avoid duplicated settings, less maintenance?
- less settings to define when writing a new profile. easier to get started?

cons:
- more complexity due to including a base profile?
- harder to find out where a settings was defined?

**Comment by SiarheiFedartsou** [comment]
Stale.
