### ISSUE TITLE
foot profile should support railway

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#4316]
there are no tests and actual support for going on railsways also seem to be missing

**Comment by MoKob** [comment]
@emiltin could you be a bit more specific? I guess without timetables, supporting railways isn't very helpful? Or are you aiming at something else than actual public transit routing?

**Comment by emiltin** [comment]
i was thinking of simple routing on railway without time-table support. of course this is not ideal, but might be preferable to not having connection. i guess it's up for discussion about whether we want to support this - we currently do for bike, which is why i added this issue.

if we route on railways, it should be with a low rate, so it's only used as  last resort.

**Comment by MichalPP** [comment]
do you think https://wiki.openstreetmap.org/wiki/Proposed_features/Headway would help? (after we have some relation support)

**Comment by emiltin** [comment]
in principle such a tag indicating the frequency of a particular service could be useful, however, if we want to even use railways at all, they should be with a very low rate to make them unattractive, even if they're faster, since the point of a foot or bike profile is to go by foot or bike, even when it might be faster to go by train.
