### ISSUE TITLE
InvalidUrl for polyline encoded route service

### ISSUE THREAD

**Issue by msyrus** [Project-OSRM/osrm-backend#4325]
I am getting InvalidUrl response for polyline encoded string
```
{bcpCu|yfPPBb@Ep@EV@Ha@Dc@BaA@q@IeADs@h@@VBXBx@DVBVB\E\D\@^DPOBc@Dy@Hw@Ae@?WRI~@NzB@nAJv@J`Ab@x@T^@xoCrv@
```
from route service, but this polyline string is generated by node mapbox polyline library. I am guessing that I am getting the error response due to `\` character in the string. I am using the docker latest image.

**Comment by daniel-j-h** [comment]
Could you give us a bit more details:
- The raw coordinates
- The full url you are trying
- How you encode the polyline (esp. the precision)

**Comment by daniel-j-h** [comment]
Closing here - @msyrus please provide more details, we can't debug it as is. Feel free to re-open.
