### ISSUE TITLE
Turn angle calculation needs to respect initial road order

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#4331]
<img width="840" alt="screen shot 2017-07-25 at 09 03 42" src="https://user-images.githubusercontent.com/12932279/28559771-42a92a54-7118-11e7-8ca4-9ded103bc7ab.png">

When a fork turns, simply using the turn angle to compute the direction modifier can result in misleading directions. Forks should be hard limited to `left` and `right` to distinguish between the two possibilities, ignoring the actual turn angle.

[osrm link](http://map.project-osrm.org/?z=17&center=37.810161%2C-122.197827&loc=37.811361%2C-122.198964&loc=37.810615%2C-122.198267&hl=en&alt=0)

**Comment by MoKob** [comment]
Turns out, that the fork handler already assigns (slight) left/right only. There seems to be a mixup in turn-angle computation here.

**Comment by MoKob** [comment]
My findings show that the main problem at the given intersection is that multiple version of turn angle calculation interact badly with each other given the very small angle where the roads actually turn.

To fix this, we need to ensure that the initial order of turn angles is kept when changing computation from looking at the very first coordinate to some more advanced modelling.

**Comment by miccolis** [comment]
Is there any lingering work here?  Appears that with #4332 merged this should be closed.

**Comment by MoKob** [comment]
To capture the state here: #4332 was only a symptomatic fix. @oxidase has prepared a correct fix in #4443 which is currently up for review.
