### ISSUE TITLE
Requests to Router HTTP API Returning "HTTP Error 503"

### ISSUE THREAD

**Issue by dyanikoglu** [Project-OSRM/osrm-backend#4334]
I'm unable to make HTTP requests to HTTP API for routing service.

Tried with curl, chrome and firefox. Each of them returns 503 HTTP Error, Service Unavailable.

**Comment by daniel-j-h** [comment]
Yep the demo server is currently having a bad time. Try again in a bit we're working on it.

Note that we don't guarantee anything wrt. the demo server:

https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy

**Comment by daniel-j-h** [comment]
Should be up again.
