### ISSUE TITLE
Disallow crossing closed roads

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#4336]
When parades and major events happen, roads get closed.  Very often, not only is a road itself closed, but crossing that road is also not permitted.

Currently, *even* if we supported various access tags for major events, our edge-based-graph generation will still happily *cross* closed roads, which may or may not be the right thing to allow.

I don't think the OSM tagging scheme currently has sufficient detail to differentiate between "you can't drive on this road but you can cross it" vs "you can't drive on this road *and* you can't cross it", and we don't have any other mechanism to handle this either.

**Comment by MoKob** [comment]
@danpat could we potentially model crossing a closed road with very high turn penalties?

**Comment by danpat** [comment]
Just so this is clear, we're talking about this type of scenario:
![4th-avenue-airel-in-brooklyn](https://user-images.githubusercontent.com/1892250/28630877-577f4058-71e0-11e7-96e9-0f4e1f528d3f.jpg)

@MoKob yes, effectively it'd would be a `restriction=no_entry` relation with the from/to as the crossing streets, and the `via` as the crossing node.

```
      E
      |
A-----B------------C----------D
      |
      F
```

Here, the "parade" would be along the road ABCD.  There would be no crossing at B, so traversing EBF should not be allowed.
