### ISSUE TITLE
Error when deleting `.ebg_nodes`

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#4338]
After the extract/contract phases, I usually delete the files that are not used by `osrm-routed`. This is the first time I do it for `v5.8.1` so I've updated my file list based on https://github.com/Project-OSRM/osrm-backend/wiki/Toolchain-file-overview, and I'm getting an error on `osrm-routed` launch:

```
[error] Missing File: [...].osrm.ebg_nodes
[error] Required files are missing, cannot continue
```

Probably this file should just be flagged as used by `osrm-routed` in the wiki?

**Comment by daniel-j-h** [comment]
@oxidase I think this is related to the file split you did? Can you clarify and / or just update the Wiki.

**Comment by oxidase** [comment]
`.ebg_nodes` is used by `osrm-routed` ->  updated the Wiki

**Comment by daniel-j-h** [comment]
Thank you :bow:
