### ISSUE TITLE
osrm-routed gives same impossible result every time

### ISSUE THREAD

**Issue by fsanchez24899** [Project-OSRM/osrm-backend#4344]
Hi. I'm using `osrm-routed` on a Massachusetts map to route between points in Boston. However, whenever I `curl` a request with Boston coordinates it returns route data about "Berliner-Strasse" with all the numbers for duration, distance, etc. being 0, regardless of the coordinates I give it. If I flip the coordinate order it does the same thing but with another place in Berlin called "Fontaneallee." I downloaded and used a Berlin Map from when I was doing the tutorial set up but I am now on a different drive on my computer and am running `osrm-routed massachusetts-latest.osrm` instead of using the Berlin Map (which I have deleted). Even after I shut down `osrm-routed` when I curl a request I get the same response with "Berliner-Strasse" or "Fontaneallee." I assume for some reason `osrm-routed` is still running my Berlin map. How can I fix this issue?

**Comment by danpat** [comment]
It sounds like you still have the tutorial `osrm-routed` process running.

If you don't know how to find the process and kill it, the simple fix is to restart your machine.

**Comment by fsanchez24899** [comment]
Killing the process worked. Thanks!
