### ISSUE TITLE
Left_hand_driving 's value.

### ISSUE THREAD

**Issue by sophia-xll** [Project-OSRM/osrm-backend#4345]
Hello everyone
    The car is left rudder while traffic rules ask driving on the right side of the road.What the value of 'left_hand_driving' attribute should be? True or false? Thanks for any answer.

**Comment by MoKob** [comment]
The `left_hand_driving` is used for indicating the side of the road, not the side of the steering wheel. The reasoning here is that we switch penalties and some behaviour around guidance based on this value.
So if you drive on the `right` side of the road, set it to `false`.
