### ISSUE TITLE
spurious errors on travis

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#4347]
lately i've seen a number of times where travis reports spurious errors. pushing an empty commit to retrigger travis then results in a green run.

for example in #4240, commit b669618 fails, but c6889b4 (which is just an empty commit) succeeds.

the fail happens in only a single build, in a seemingly unrelated test:

1) Scenario: Don't Turn through potential through lanes - features/guidance/turn-lanes.feature:1178
   Step: When I route I should get - features/guidance/turn-lanes.feature:1193
   Step Definition: features/step_definitions/routing.js:4
   Message:
     Error: osrm-extract exited with code 1: /home/travis/build/Project-OSRM/osrm-backend/build-osrm/osrm-extract --profile /home/travis/build/Project-OSRM/osrm-backend/profiles/car.lua /home/travis/build/Project-OSRM/osrm-backend/test/cache/guidance/turn-lanes.feature/73050acbe63ce6502bdce9f910670714/ed903b3624d2a294e8bd13c4e7ea3153/1178_dont_turn_through_potential_through_lanes.osm
         at /home/travis/build/Project-OSRM/osrm-backend/features/support/data.js:188:37
         at ChildProcess.exithandler (child_process.js:207:5)
         at emitTwo (events.js:87:13)
         at ChildProcess.emit (events.js:172:7)
         at maybeClose (internal/child_process.js:862:16)
         at Socket.<anonymous> (internal/child_process.js:338:11)
         at emitOne (events.js:77:13)
         at Socket.emit (events.js:169:7)
         at Pipe._onclose (net.js:490:12)

**Comment by oxidase** [comment]
@emiltin sanitizer reported memory leaks in TBB behind messages like https://travis-ci.org/Project-OSRM/osrm-backend/jobs/257464962#L1773 Fixed now by upgrading TBB to 2017_u7

**Comment by emiltin** [comment]
ok. but i don't see that in the travis log?

**Comment by oxidase** [comment]
yes, the error message is in  `osrm-extract` stderr output and not printed

**Comment by emiltin** [comment]
thanks for clarifying

**Comment by oxidase** [comment]
the error occurs again https://travis-ci.org/Project-OSRM/osrm-backend/jobs/260142777#L2447-L2466 also for 2017_U7. We need to add an asan suppressions list to avoid  fails that not related to osrm

**Comment by daniel-j-h** [comment]
Is this still actionable @oxidase?

**Comment by oxidase** [comment]
yes, i think a suppression file for tbb leaks could be a good solution

**Comment by oxidase** [comment]
Closed via c50a6f77dc4e60eb90d251a0b7e2f37a977b1b2f
