### ISSUE TITLE
Review slip-road handlers

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#4348]
## Scenario 1

`primary` via `primary_link` onto secondary.

![screen shot 2017-07-27 at 12 48 34 2](https://user-images.githubusercontent.com/12932279/28667018-f61b34da-72c9-11e7-81af-314f95c9d4ed.png)
[osrm](http://map.project-osrm.org/?z=18&center=38.778487%2C-76.084764&loc=38.778978%2C-76.084764&loc=38.778527%2C-76.087232&hl=en&alt=0)

This feels like a _primary_ candidate for a sliproad. 

 - [x] investigate handler that discards it
 - [x] adjust if possible
 - [x] evaluate other affected locations

## Scenario 2

`tertiary` via `tertiary_link` onto second residential. 

![screen shot 2017-07-27 at 12 51 59 2](https://user-images.githubusercontent.com/12932279/28667141-7f5f4fce-72ca-11e7-80ca-258f2b7895b2.png)

[osrm](http://map.project-osrm.org/?z=18&center=37.803280%2C-122.437145&loc=37.803599%2C-122.436983&loc=37.803075%2C-122.437386&hl=en&alt=0)

Looks very similar to scenario 3, only down two road categories. Actions remain the same:

 - [x] investigate handler that discards it
 - [x] adjust if possible
 - [x] evaluate other affected locations

## Scenario 3

`residential_road` via `residential_road` onto `residential_road`

![screen shot 2017-07-27 at 12 55 54 2](https://user-images.githubusercontent.com/12932279/28667255-1714adf0-72cb-11e7-8608-6b0315007e36.png)

[osrm](http://map.project-osrm.org/?z=18&center=37.804175%2C-122.439741&loc=37.804325%2C-122.439778&loc=37.803994%2C-122.439923&hl=en&alt=0)

This one is tricky, due to no `link` class. Given the matching names and the short segment, we might be able to detect these.

 - [x] investigate handler that discards it
 - [x] adjust if possible
 - [x] evaluate other affected locations

## Scenario 4

`motorway_link` via `motorway_link` onto `primary`

![screen shot 2017-07-27 at 12 58 30 2](https://user-images.githubusercontent.com/12932279/28667494-092d24f0-72cc-11e7-9811-898db1fcfe6f.png)

[osrm](http://map.project-osrm.org/?z=18&center=37.576379%2C-77.462561&loc=37.576921%2C-77.463323&loc=37.575629%2C-77.463076&hl=en&alt=0)

This might be influenced with us treating motorways differently than normal roads. 

 - [x] investigate handler that discards it
 - [x] adjust if possible
 - [x] evaluate other affected locations

**Comment by oxidase** [comment]
@MoKob in the 4th scenario sliproad handler  discards [the sliproad candidate](https://www.openstreetmap.org/way/146689490) at
https://github.com/Project-OSRM/osrm-backend/blob/e512431388f7a416d179dcc21df694d9f417968a/src/extractor/guidance/sliproad_handler.cpp#L713 
because [`first` road](https://www.openstreetmap.org/way/46849528) is also  a `motorway_link`

**Comment by oxidase** [comment]
All four cases are merged as separate PRs
