### ISSUE TITLE
Understanding weight and rate in Profiles

### ISSUE THREAD

**Issue by creatorness** [Project-OSRM/osrm-backend#4349]
Hello there,

I do not quite understand the relationship between speed and rate.

According to the documentation, I have to increase the rate if I want to prefer certain ways.
This does not works the rate is always the same in the debug tile url
In addition, the rate has other values than I have (set 1000 but is 0.4 etc.)

I set the rate as follows

result.forward_rate = (result.forward_speed / 3.6) * rate
result.backward_rate = (result.backward_speed / 3.6) * rate

Best regards

**Comment by emiltin** [comment]
maybe you later set `weight`? it's a shortcut for setting both forward_rate and backward_rate. note that some of the functions in WayHandlers set the weight and rates.

**Comment by creatorness** [comment]
I have changed "properties.weight_name" to something else.
Also, I tested that result.weight is -1 at the end of "function way_function"

**Comment by creatorness** [comment]
I noticed something strange.
If I set the rate to 0, on ways that I do not prefer, then also disappear paths, where I have not reckoned with
These are initially filtered out, the path id does not appear in my function, but only at the beginning of the "function way_function"
The odd thing is, when I set the rate to 0.1, the paths are displayed in the debug tile, even those that have never reached my function
