### ISSUE TITLE
map match to correct side of the road

### ISSUE THREAD

**Issue by achimhoth** [Project-OSRM/osrm-backend#4350]
Is it possible to map match to the correct side of the road and not just the middle of the road (driving profile)?

![bildschirmfoto 2017-07-27 um 16 04 29](https://user-images.githubusercontent.com/5278493/28674414-9e22718c-72e5-11e7-9155-523169b90163.png)

**Comment by TheMarex** [comment]
We map match to the geometry that is in the underlying dataset. In our case OSM models roads as line strings in the center of the road, if it's not divided by a barrier (like for example motorways).

You could try to do some pre-processing yourself that takes OSM data and splits every way into multiple distinct lanes. There is sadly no build-in way in OSRM to do this, and I think it is unlikely that we will ever want to add modeling for that. Sorry!

**Comment by yterletskyi** [comment]
That's interesting because mapbox traffic has done it on OSM map. Take a look https://mapbox.github.io/mapbox-gl-traffic/examples/traffic-day.html (Enable traffic in top right corner). Do you think it's some processing on osrm-backend results?

**Comment by danpat** [comment]
@yterletskyi In that demo, it's done at the visual layer.  The road geometry in the vector tiles remains a single centerline, but what the traffic layer does is render two lines, one for each direction of travel, with the drawing order oriented along the direction of travel.  Those lines are then offset sideways using the Mapbox GL `line-offset` primitive.

In the example above, you can see it in this file:

https://mapbox.github.io/mapbox-gl-traffic/mapbox-gl-traffic.js

on line 76:

```js
      'line-offset': {
        'base': 1.5,
        'stops': [
          [
            14,
            2
          ],
          [
            20,
            18
          ]
        ]
      },
```

The demo you linked above doesn't cater for mixed left/right driving countries, it's always offsetting to the right (positive values for `line-offset`).
