### ISSUE TITLE
Strange nearest results via API calls

### ISSUE THREAD

**Issue by Leon53** [Project-OSRM/osrm-backend#4351]
I am trying to use demo server , and for query like curl.exe 'http://router.project-osrm.org/nearest/v1/driving/49.337816,28.573575' , I constantly receive incorrect results, while entering same coords on http://map.project-osrm.org/ returns correct place.

**Comment by danpat** [comment]
I suspect you've got your lon/lat mixed up - the API takes `longitude,latitude` values.  The point you've provided (lon:49.337816, lat:28.573575) is in the middle of the Persian Gulf:

![screen shot 2017-07-27 at 9 15 32 am](https://user-images.githubusercontent.com/1892250/28680777-39452306-72ac-11e7-8f0c-93d4a890be2d.png)

For historical reasons, the `map.project-osrm.org` UI uses `lat,lon` order.

The `lon,lat` order for the API is documented here: http://project-osrm.org/docs/v5.9.1/api/#requests
