### ISSUE TITLE
Unexpected end of file: planet-latest.osrm.geometry

### ISSUE THREAD

**Issue by MichaleRayG** [Project-OSRM/osrm-backend#4354]
I installed and ran OSRM on an AWS Ubuntu node and extracted and processes the latest-planet.osrm.pbf file successfully (it looked to be successful and I was able to run the osrm-routed without error).  I transferred all of the latest planet files to my own Ubuntu Server and when I tried to run the same command I got the following error:

Unexpected end of file: planet-latest.osrm.geometry

These are the file sizes of the files that I have 

lrwxrwxrwx  1 administrator administrator          45 Jun  7 17:35 lib -> /home/administrator/osrm-backend/profiles/lib
drwxrwxr-x 20 administrator administrator        4096 Jul 28 15:08 osrm-backend
-rw-r--r--  1 administrator administrator 30005893580 Jul 27 12:52 planet-latest.osrm
-rw-r--r--  1 administrator administrator  7711799000 Jul 27 13:50 planet-latest.osrm.cnbg
-rw-r--r--  1 administrator administrator  2446492672 Jul 27 13:26 planet-latest.osrm.cnbg_to_ebg
-rw-r--r--  1 administrator administrator          16 Jul 27 18:46 planet-latest.osrm.core
-rw-r--r--  1 administrator administrator       66056 Jul 27 14:43 planet-latest.osrm.datasource_names
-rw-r--r--  1 administrator administrator 11569349684 Jul 27 14:01 planet-latest.osrm.ebg
-rw-r--r--  1 administrator administrator  4050923652 Jul 27 14:00 planet-latest.osrm.ebg_nodes
-rw-r--r--  1 administrator administrator  4049272429 Jul 27 13:49 planet-latest.osrm.edges
-rw-r--r--  1 administrator administrator  1157406760 Jul 27 13:56 planet-latest.osrm.enw
-rw-r--r--  1 administrator administrator 13891989600 Jul 27 14:00 planet-latest.osrm.fileIndex
-rw-r--r--  1 administrator administrator 14174477589 Jul 27 13:49 planet-latest.osrm.geometry
-rw-r--r--  1 administrator administrator 26941883320 Jul 27 18:46 planet-latest.osrm.hsgr
-rw-r--r--  1 administrator administrator  2634450666 Jul 27 13:49 planet-latest.osrm.icd
-rw-r--r--  1 administrator administrator  1157406760 Jul 27 18:46 planet-latest.osrm.level
-rw-r--r--  1 administrator administrator   153849567 Jul 27 12:52 planet-latest.osrm.names
-rw-r--r--  1 administrator administrator  7980230080 Jul 27 14:00 planet-latest.osrm.nbg_nodes
-rw-r--r--  1 administrator administrator        2344 Jul 27 12:52 planet-latest.osrm.properties
-rw-r--r--  1 administrator administrator    55343232 Jul 27 14:00 planet-latest.osrm.ramIndex
-rw-r--r--  1 administrator administrator          16 Jul 27 12:52 planet-latest.osrm.restrictions
-rw-r--r--  1 administrator administrator          28 Jul 27 12:52 planet-latest.osrm.timestamp
-rw-r--r--  1 administrator administrator       14220 Jul 27 13:49 planet-latest.osrm.tld
-rw-r--r--  1 administrator administrator       32856 Jul 27 13:49 planet-latest.osrm.tls
-rw-r--r--  1 administrator administrator  1156934982 Jul 27 13:49 planet-latest.osrm.turn_duration_penalties
-rw-r--r--  1 administrator administrator  6941609796 Jul 27 13:49 planet-latest.osrm.turn_penalties_index
-rw-r--r--  1 administrator administrator  1156934982 Jul 27 13:49 planet-latest.osrm.turn_weight_penalties
lrwxrwxrwx  1 administrator administrator          49 Jun  7 17:35 profile.lua -> /home/administrator/osrm-backend/profiles/car.lua
-rw-rw-r--  1 administrator administrator           0 Jun 10 15:24 stxxl.errlog
-rw-rw-r--  1 administrator administrator          94 Jun 10 15:24 stxxl.log

Any ideas what the issue could be?

**Comment by danpat** [comment]
@MichaleRayG Are you using exactly the same version of OSRM on both servers?  I [added a change yesterday to `master`](https://github.com/Project-OSRM/osrm-backend/pull/4352) that modifies the `.geometry` file format.  The `master` branch is considered unstable, so if you've used two different builds of OSRM from `master`, it's likely this is the problem.

**Comment by danpat** [comment]
Also, machine architectures need to match (specifically, [endianness](https://en.wikipedia.org/wiki/Endianness) and [word size](https://en.wikipedia.org/wiki/Word_(computer_architecture))), but this is unlikely a problem as long as both machines have similar CPUs (i.e. Intel x86_64).

**Comment by MichaleRayG** [comment]
That may very well be the issues.  I used **git clone https://github.com/Project-OSRM/osrm-backend.git** 2 days ago on AWS and then again on my server today (so once before Yesterday and once after).  Do you happen to know the repository path of the version from before yesterday I can use to update my server?

**Comment by danpat** [comment]
@MichaleRayG you'll need to track down the SHA of the version you checked out.

If you look at the commit history on `master` at https://github.com/Project-OSRM/osrm-backend/commits/master, you can see the changes that have been made in the last few days.

I would try doing:

`git checkout 0affec8f1732e9d3cb56bff4f4d08da42f250943`

in your workspace on your local machine - this is 1 commit before my recent changes and the data should be compatible.  Re-build and try re-running `osrm-routed`.

Generally, unless you really need `master`, I'd recommend using the released tags for stability.

**Comment by MichaleRayG** [comment]
That was it.  I checked out the project you suggested and re-ran `osrm-routed` and I am up and running.  Thank you.
