### ISSUE TITLE
[warn] [server error] code: std::bad_alloc,  on a table query with 174k points

### ISSUE THREAD

**Issue by diegocando** [Project-OSRM/osrm-backend#4359]
Hi, I'm using osrm 5.3.0, the table query I'm running is a large one, a little over 174k points, I've made a change in the /src/engine/plugins/table.cpp file to solve a issue regarding this line of code(56):

static_cast<std::size_t>(max_locations_distance_table * max_locations_distance_table)

to

static_cast<std::size_t>( static_cast<std::size_t>(max_locations_distance_table) * static_cast<std::size_t>(max_locations_distance_table))

because 174k ^2 goes over int max, this solved the first issue (message to many points), but this lead me to another issue, now the server returns this message

[warn] [server error] code: std::bad_alloc

As I understand is a problem with the memory during execution time, I also monitored the ram and swap use during the execution but it seems that the swap is not used during the execution, do you guys know how this issue can be solved? BTW the swap assigned is 100gb and the system reports as only 10gb are used.

the system have 16gb of ram, appers like 3 gb free and osrm-routed is using 80% of the total ram available.

Thank you in advance for any help you can provide me.

**Comment by danpat** [comment]
@diegocando 

At a very minimum, your request will use 174k * 174k * 4 bytes = 121,104,000,000  = 120GB of RAM.  This data is then serialized into a JSON struct, which is probably another 200GB of in-memory data, before the response is sent to the client.

I would suggest you use the `sources=` and `destinations=` option and calculate your large matrix in parts, and stitch together the results as a post-processing step.

I wrote this script a while back:

https://gist.github.com/danpat/83eaed80b6241310ebdf1c0bef04a524

which uses the Mapbox Matrix API (which uses the OSRM table API in the background), which shows the general logic.  However, you'll need to do something different to construct the final result on the client-side - I don't know that you want to hold these results entirely in memory at once, they're quite large.

**Comment by danpat** [comment]
@diegocando Note, that it's probably failing to allocate the storage buffer before the calculations even begin - you won't see the memory usage because it tries to pre-allocate and fails.

**Comment by Cubillosxy** [comment]
Hi, I'm using Osrm Docker, but i have a problem with the maximum number of coordinates when I try to get the destination matrix, the limit is 100 points, how i can extend this limite?

```
http://router.project-osrm.org/table/v1/driving/
```

**Comment by danpat** [comment]
@Cubillosxy Run `osrm-routed --help` - you can adjust the limit on the command line.

**Comment by Cubillosxy** [comment]
@danpat Thank you , actually I solved this runing docker osrm with adittional config lines .  

from https://hub.docker.com/r/osrm/osrm-backend/ 
```
docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf
docker run -t -v $(pwd):/data osrm/osrm-backend osrm-contract /data/berlin-latest.osrm
docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed /data/berlin-latest.osrm

```
you can add config lines like this 

```
docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed --max-table-size 500 /data/colombia-latest.osrm
```
where colombia-latest.osrm is my map

**Comment by diegocando** [comment]
Thank you @danpat I'll just send multiple request with sources limitation.

**Comment by sroycode** [comment]
This project may help https://github.com/sroycode/fawcet
