### ISSUE TITLE
Extract maxspeed

### ISSUE THREAD

**Issue by MouadSb** [Project-OSRM/osrm-backend#4376]
Hello everyone, I want to extract maxspeed from a way information is there any route or function that i can use?

**Comment by daniel-j-h** [comment]
Care to elaborate a bit more?

In the profiles (e.g. car.lua) you calculate a max speed based on all available OSM tags (such as the maxspeed tag, lane tag, surface tag, etc.) - where do you want to extract a maxspeed now?

If you're looking for speeds along the route geometry, see the `annotations=speee` flag:

http://project-osrm.org/docs/v5.10.0/api/#route-service

**Comment by jpandco** [comment]
The resulat that i really want is the maxspeed tag , is similarly to query on overpass-turbo
`way(around:400,43.746710, 7.430990)[maxspeed];`

(Sorry for my english)

**Comment by daniel-j-h** [comment]
If you only want the maxspeed tag you don't need a routing engine at all.

Either make an overpass turbo query or write a small [osmium](http://osmcode.org/pyosmium/) handler to walk over all ways and fetch the maxspeed tag from there.

**Comment by jpandco** [comment]
Thanks for your time @daniel-j-h

**Comment by MouadSb** [comment]
Thanks for your time @daniel-j-h
