### ISSUE TITLE
Add street name to intersections array

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4379]
How difficult/expensive would it be to add street names to the intersection array? This would help us label cross streets and build a departure announcement like "Head south towards U St NW".

/cc @ericrwolfe

**Comment by daniel-j-h** [comment]
It's possible but it's expensive: both in the engine as well as in the response size. Currently we don't have the crossing roads available when we create the response based on the route found.

**Comment by ericrwolfe** [comment]
@daniel-j-h what would be the cost within the engine or even after routing as a post processing step to add the intersection names? I don't think response size (with gzip + an optional query param) is as much of a concern.

This would make custom cross street labeling for turn-by-turn navigation much, much easier. The current ideas are centered around trying to feature query the rendered map at each intersection, and match geometries with the bearings from each intersection.

**Comment by 1ec5** [comment]
> This would make custom cross street labeling for turn-by-turn navigation much, much easier. The current ideas are centered around trying to feature query the rendered map at each intersection, and match geometries with the bearings from each intersection.

Cross-street labeling requires cross-street geometry, which map tiles can provide via feature querying. The geometry is used to offset the label to either side, so that it unambiguously points to the cross street instead of pointing to the intersection and obscuring the route line.

At first glance, the `bearings` in each Intersection object would appear to be useful for offsetting the labels. However, I don’t think that field is suitable, because a street may intersect at a 90° angle yet curve shortly thereafter – we wouldn’t want the label to be placed atop a building because the road curved.

**Comment by MoKob** [comment]
The options here in the routing engine depend on the underlying algorithm and are quite complicated in parts. I wouldn't favour any of the implementation methods. Also I would like to raise the question in how far we are shifting responsibilities from the client into the routing engine.

I can see the use-case for a `depart towards` instruction. The remaining cross street labelings would seem like a pure visualisation feature to me.
In terms of implementation options, I see the following list:

 - user r-tree query for nearest segments along intersection
    - (+) works on both CH and MLD
    - (-) very expensive (r-tree searches used to make up a large part of the navigation cost, is this still the same?)
    - (+) but not too expensive for single use, could be used to implement depart towards instruction

- MLD: use the base graph to explore neighbouring roads, add their names to the response
   - (+) relatively cheap
   - (-) dedicated implementation for MLD only, more maintenance during 

- CH
   - not possible from algorithm data alone
   - requires addition of data: add all names to intersections at the end of an edge along the way (~4 name-ids per edge) or ordered like bearings: ~4 name-ids per node + possible index datastructure
   - (-) requires a lot of additional memory
   - (-) adds data only necessary for CH / dedicated implementation

In total, I wouldn't favour any of these alternatives, unless we can make a strong argument for why this data belongs into the route result. After all, we had multiple discussions that even telling the new name of the road we are driving on would be too much. Adding information about a lot of roads that are not relevant to the navigation seems conflicting to that notion to me.

**Comment by daniel-j-h** [comment]
Closing - realistically it does not make sense in the routing engine and is not actionable from our side.
