### ISSUE TITLE
Permalink with a Destination but without Start

### ISSUE THREAD

**Issue by efred** [Project-OSRM/osrm-backend#438]
It would be nice, if there will be a possibility to make a permalink (Generate Link) with a Destination but without Start. Until now, its not possible with OSRM, but  p.e. at [OpenRouteService its possible](http://openrouteservice.org/index.php?end=7.2689253,46.7889612&pref=Fastest&lang=de&noMotorways=false&noTollways=false&zoom=16). But I would make it with OSRM, because the datas are much more up to date.
The reason for this Feature Request is: if the people would organize some events and would publish it on their website it would be kind, if they can also publish a permalink to the location and the visitors can add just a start-location - this would be really visitor-friendly.

**Comment by TheMarex** [comment]
Obsolete with `osrm-frontend-v2`.
