### ISSUE TITLE
GeoJSON printer needs to be adapted for QueryNode -> Coordinate + OSM node split

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4394]
In https://github.com/Project-OSRM/osrm-backend/commit/7f6e0c478bca48df8128a9778e88ac259a831c01 we split the QueryNode into its coordinate part and the osm node id.

I just came across the geojson printer (which is not used by default) for printing intersections and debugging guidance issues - needs to be adapted to the split so it can be used again.

**Comment by MoKob** [comment]
There is already a commit we could cherry-pick, make into a dedicated PR: https://github.com/Project-OSRM/osrm-backend/pull/4341/commits/c388c23bee455ac532e7e2b82238c6a0b453992a
