### ISSUE TITLE
Error "dataset not compatible with CH"

### ISSUE THREAD

**Issue by joseflorido** [Project-OSRM/osrm-backend#4401]
Hi!

I am running 5.10 and tried to prepare OSM data with:
node_modules/osrm/lib/binding/osrm-extract europe-latest.osm.pbf -p node_modules/osrm/profiles/car.lua
node_modules/osrm/lib/binding/osrm-partition europe-latest.osrm
node_modules/osrm/lib/binding/osrm-customize europe-latest.osrm
node_modules/osrm/lib/binding/osrm-datastore europe-latest.osrm

When I run my nodejs app I get an error saying that dataset is not compatible with CH. Is there a way to run it with data loaded in shared memory and use MLD? Or how should I prepare data to be compatible with CH?

Thanks!

**Comment by danpat** [comment]
You need to initialize the node object with the algorithm to use - it defaults to `CH`.

Try:

```
var osrm = new OSRM({ algorithm: 'MLD'});
```

**Comment by joseflorido** [comment]
It worked! Thanks! 👍
