### ISSUE TITLE
osrm-routed Dataset is not compatible

### ISSUE THREAD

**Issue by neilRGS** [Project-OSRM/osrm-backend#4403]
Hi.
I hope someone can advise.
I have built planet-latest on an AWS EC2 machine.
All seems to have gone well, in that extract and contract ran with no errors.
I have moved the resulting files onto a Windows server and have installed v5.10, the same version as I used to do the compile.
On running osrm-routed, I am given this error
```
>E:\OSM\OSRM-Backend\osrm-routed.exe E:\OSM\Planet\foot\planet-latest.osrm -p 5000
[info] starting up engines, v5.11.0←[0m
[info] Threads: 8←[0m
[info] IP address: 0.0.0.0←[0m
[info] IP port: 5000←[0m
←[31m[error] [exception] Dataset is not compatible with CH←[0m
```
This suggests that the Windows version is v5.11, and although I downloaded both Linux and Windows releases on the same day, the version I got for Windows is one ahead of the Linux version.

Is there a repository of older Windows releases, so that I can get the version I need to run (v5.10) rather than spending more money on AWS to recompile to v5.11?

Any help on this will be appreciated.

Many thanks,

Neil.

**Comment by daniel-j-h** [comment]
Did you pre-process the planet on a Linux ec2 box and now try to use it on a Windows box? Files are not compatible across operating systems (and strictly speaking not even across different architectures and compilers). I recommend using the same Linux (e.g. Ubuntu 16.4) for pre-processing _and_ routing.

We don't have much production experience with Windows and we're lacking folks maintaining both code and builds for Windows.

**Comment by neilRGS** [comment]
Hi Daniel.
Thanks for the info.
Yes, that's exactly what was done :)

Maybe that will help me coerce the purse-holders into getting a Linux VM in place.

Cheers,

Neil.

**Comment by neilRGS** [comment]
Hi Daniel.
Just a quick one, I hope:

Will 244GB RAM be enough to run 3 instances of osrm-routed with the planet?
I want to run an instance for each of foot, bike and (possibly) car.

I'm looking at the i3.8xlarge EC2, as it is a touch cheaper then the r3.8xlarge.

Many thanks,

Neil.

**Comment by daniel-j-h** [comment]
You will need roughly 64 GB of RAM for routing _with the car profile_. Other profiles contain more data (e.g. walk includes ways you can not drive on). Feel free to update this Wiki if you have up-to-date numbers:

https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements

**Comment by neilRGS** [comment]
Great, thanks Daniel. I knew I had seen that link somewhere :)

As soon as I have this up and running, I will happily add numbers to the wiki.

Cheers,

Neil.

**Comment by daniel-j-h** [comment]
Closing here as not actionable for us. Feel free to add your findings to the Wiki :) Happy routing!
