### ISSUE TITLE
[profile][car] barrier_whitelist, checkpoint is not a barrier value tag, but a military one

### ISSUE THREAD

**Issue by frodrigo** [Project-OSRM/osrm-backend#4405]
The car profile whitelist the node tag `barrier=checkpoint`, but the right checkpoint tag is `military=checkpoint`.
The other profiles does not have checkpoint in the whitelist.
I suppose we want to pass trough checkpoints in all profiles.

cc @emiltin @braktar

https://wiki.openstreetmap.org/wiki/Tag:military%3Dcheckpoint
https://taginfo.openstreetmap.org/keys/barrier#values

**Comment by daniel-j-h** [comment]
You're right there is no `barrier=checkpoint` - we should probably re-check all barrier tags we handle.

Feel free to whitelist `military=checkpoint` in the profiles.

**Comment by frodrigo** [comment]
I will do it.
The other tags are ok.

**Comment by emiltin** [comment]
military=* is not considered in the profiles at all at the moment, so the current behaviour should be correct, except that we allow access on access=checkpoint (which is not in common use anyway since it's incorrect tagging)?

are there other values for military=* which should prevent access?

**Comment by frodrigo** [comment]
I see nothing more of interest:
https://taginfo.openstreetmap.org/keys/military?filter=nodes#values

**Comment by emiltin** [comment]
me neither. then it seems all there is to do is to remove checkpoint from the whitelist, for clarity

**Comment by daniel-j-h** [comment]
Removed in https://github.com/Project-OSRM/osrm-backend/pull/4408.
