### ISSUE TITLE
Using example.cpp

### ISSUE THREAD

**Issue by AegisOfImmortal** [Project-OSRM/osrm-backend#4419]
I installed lib osrm via the following commands on ubuntu:
mkdir build 
cd build
cmake ..
make
sudo make install
Then I tried to use osrm-routed using docker, it succeeded. Then I wanted to learn how to use libosrm, so I checked the example files, and did the followings in the /example folder:
mkdir build 
cmake ..
make
sudo make install
I thought this would install the libraries, but when I used the commend
g++ example.cpp
It still give errors telling about missing libraries
In file included from /usr/local/include/osrm/match_parameters.hpp:31:0,
                 from example.cpp:1:
/usr/local/include/osrm/engine/api/match_parameters.hpp:31:43: fatal error: engine/api/route_parameters.hpp: No such file or directory
compilation terminated.

**Comment by AegisOfImmortal** [comment]
@danpat Sorry this might seem to be an elementary question, but what exactly was the example.cpp supposed to do? The make command (using example/makefile) only gave me the same bunch of executable ( osrm-*) as in the osrm root directory, did it compile example.cpp?

**Comment by danpat** [comment]
Here's a transcript of what you should see when you build the example (note, I'm on OSX, but it works the same on Linux):

```
$ cmake ..
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building on a 64 bit system
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Found LibOSRM: /usr/local/lib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/danpat/osrm-backend/example/build
$ make
Scanning dependencies of target osrm-example
[ 50%] Building CXX object CMakeFiles/osrm-example.dir/example.cpp.o
[100%] Linking CXX executable osrm-example
[100%] Built target osrm-example
$ ls
CMakeCache.txt		CMakeFiles		Makefile		cmake_install.cmake	osrm-example
$ ./osrm-example
Usage: ./osrm-example data.osrm
```

The example performs a `route` request between two fixed coordinates - https://github.com/Project-OSRM/osrm-backend/blob/master/example/example.cpp#L43-L44, you'll need an OSRM datafile prepared for Monaco for the example to work as-is (you need to generate `data.osrm` using the `osrm-extract` and `osrm-contract` tools).

**Comment by danpat** [comment]
Closing here as there's no bug that I can see.  @AegisOfImmortal please re-open if the example doesn't actually do what it's supposed to.

**Comment by AegisOfImmortal** [comment]
Thanks a lot. I think the problem is I missed to get the cmake folder some how.
