### ISSUE TITLE
Traffic update Wiki

### ISSUE THREAD

**Issue by yadunathg** [Project-OSRM/osrm-backend#4424]
I am trying to update traffic information on the OSRM server as per the [documentation](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic), but am facing below challenges:
- Format of the update file requires OSM IDs of the nodes to specify the speed and duration of an edge. How can we get the OSM IDs of all the nodes in an area of interest?
- Update file accepts weights only for directly connected node pairs. Is there a way to check the adjacency of nodes? OR is it possible to get the sequence of nodes in a path defined by source and destination locations?

Are these functionalities available in the current version of OSRM? If yes, can the Wiki page be updated to make its easier for people to use traffic update feature?

**Comment by daniel-j-h** [comment]
You can use libosmium or the pyosmium bindings to extract node ids from an osm base map:
- https://github.com/osmcode/libosmium
- https://github.com/osmcode/pyosmium

If you want get the node ids for a specific route you can also use osrm's `annotations=nodes`.

**Comment by oxidase** [comment]
Another possibility is to use http://overpass-turbo.eu/ with [`query-overpass`](https://github.com/perliedman/query-overpass)

For example nodes in polygon that used in ways with `highway` tag http://overpass-turbo.eu/s/r3j
```
way(poly:"48.14 11.5 48.16 11.5 48.15 11.55")["highway"];
node(w)(poly:"48.14 11.5 48.16 11.5 48.15 11.55");
out geom;
```

or nodes in area by coordinate and admin level http://overpass-turbo.eu/s/r3k
```
is_in(48.157226, 11.584471);area._["admin_level"=10]->.boundaryarea; 
way(area.boundaryarea)["highway"];
node(w)(area.boundaryarea);
out geom;
```

**Comment by yadunathg** [comment]
@daniel-j-h Thanks a lot. Your suggestions worked perfectly.

**Comment by daniel-j-h** [comment]
Great, happy routing! ✨
