### ISSUE TITLE
Collapse u-turn when connecting way is a link

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4428]
We fail to recognize a u-turn here and instead announce `Take the ramp on the left towards I 280 South`. Can we make our u-turn recognize these?

https://www.mapbox.com/get-directions/#19.28/37.43518/-122.2436?coordinates=-122.243571,37.435288;-122.243401,37.435176

**Comment by oxidase** [comment]
Fixed in 5.17.0
![screenshot from 2018-04-25 15-40-15](https://user-images.githubusercontent.com/4421046/39249471-058be0da-489f-11e8-8c07-e65089b6040f.png)
