### ISSUE TITLE
macOS binaries for node v6 missing

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4432]
From https://github.com/Project-OSRM/osrm-backend/issues/4431: it seems like we do not build binaries for macOS Node.js v6. Here's what we published for v5.11.0 (vXY are Node.js ABI version numbers corresponding to Node 4 (v46) and Node 6 (v48)):

```
node-v46-darwin-x64.tar.gz
node-v46-linux-x64.tar.gz
node-v48-linux-x64.tar.gz
```

Here's our macOS Travis build:

https://github.com/Project-OSRM/osrm-backend/blob/e7abe37b1093f14d6b1a03d3a29706d3c97aa8a0/.travis.yml#L143-L149

**Comment by danpat** [comment]
Ugh - the OSX build is currently by far the slowest, *and* we have to wait the longest for the build to start.  Adding another OSX build configuration would make things even slower.

I don't see any way around it though, we should add the Node v6 configuration.

**Comment by Jma353** [comment]
Any follow-up on this?  Would love to have a working configuration :)

**Comment by danpat** [comment]
@Jma353 I've just opened a PR to do this, but it'll only take effect once we push the next OSRM release out.

In the meantime, you can always build locally.  Try the following:

```
git clone https://github.com/Project-OSRM/osrm-backend.git
cd osrm-backend
mkdir build
cd build
cmake -DENABLE_MASON=ON -DENABLE_NODE_BINDINGS=ON ..
make
cd ..
npm link
```

This should build everything locally, and link the build libraries into your global `node_modules`.  You should then be able to `npm install osrm` from other projects locally, and it'll use your local build.

**Comment by daniel-j-h** [comment]
This got fixed in https://github.com/Project-OSRM/osrm-backend/pull/4440 - closing here.
