### ISSUE TITLE
bearing implementation, filter or score?

### ISSUE THREAD

**Issue by sdafni** [Project-OSRM/osrm-backend#4437]
hi, was bearing eventually implemented as filter or as rank?
according to the api documentation: "Limits the search to segme..." it seems routes that don't match the bearing are excluded.
how does this solve Emil's problems (https://github.com/Project-OSRM/osrm-backend/issues/1749)?
thanks,
Yuval Dafni

**Comment by daniel-j-h** [comment]
It's a hard filter. You can do multiple requests and change the bearing parameter if needs be.

**Comment by daniel-j-h** [comment]
Diary post here https://www.openstreetmap.org/user/daniel-j-h/diary/40795 - closing as not actionable.
