### ISSUE TITLE
Deprecate CoreCH algorithm

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#4444]
Since we now have feature parity with MLD, there is no reason to keep CoreCH around - it is slower and has less features then MLD.

Removing CoreCH will let us remove the following flags for `osrm-contract`:

- `core-factor`
- `use-level-cache`
- `.level` file
- `.core` file

We might be able to remove the code for handling `CoreCH` by automatically falling back to a plain `CH` (and printing warnings).

**Comment by danpat** [comment]
Some of these changes already happened for the 5.12 release - moving this to the 5.13 release so the deprecation can be deliberate.
