### ISSUE TITLE
Separate destination and destination:ref

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4447]
Right now, we combine `destination` and `destination:ref` (and maybe more?) into a single `destination` fields. We are loosing the fidelity around which is which. Can we retain that by adding a separate `destination:ref` field?

/cc @miccolis

**Comment by daniel-j-h** [comment]
Closing as duplicate of
- https://github.com/Project-OSRM/osrm-backend/issues/3304
- https://github.com/Project-OSRM/osrm-backend/issues/3329
