### ISSUE TITLE
Routing says make uturn (should be left turn and is illegal) for a turn

### ISSUE THREAD

**Issue by davols** [Project-OSRM/osrm-backend#4457]
Mentioned it quickly on irc with @daniel-j-h 

Read through some other opened issues but don't feel they match the issue completely. (Also it might be two separate issues). I apologize beforehand if this is already known or a badly constructed issue.

[Example Route](http://map.project-osrm.org/?z=18&center=59.330383%2C18.063535&loc=59.335214%2C18.063755&loc=59.333988%2C18.066609&hl=en&alt=0)

> Make a U-turn onto Herkulesgatan

1. Should this not technically be a sharp left turn and not a uturn? 

2. Left turns (sharp left or the uturn) are illegal there. Speaking to the OSM contributor at our office he mentioned it's marked as a one way and the left turn should be restricted already. (Have we failed the tagging in OSM or is the restriction ignored because the engine says it's a u-turn and not a left turn?) 

cc @danpat 

Adding picture to save people from a click (and possible other routes)
![screen shot 2017-08-30 at 13 01 12](https://user-images.githubusercontent.com/1420172/29869474-58882320-8d83-11e7-808d-a0b84749d35a.png)
Coming out of the tunnel, the top line, left (uturn) back to the tunnel in the other lane (seperate one way tunnels)

**Comment by danpat** [comment]
@davols OSRM will never send you *against* a one-way, but that doesn't seem to be the prbolem here.  It looks like some turn restrictions need to be mapped.

The best imagery I could find for mapping from my desk was:

https://www.mapillary.com/app/?lat=59.32975609&lng=18.0621365&z=17&pKey=WKaTLjN97TryHnL1ni2etw&focus=photo&x=0.48520501854026465&y=0.5859904278149684&zoom=0

which doesn't quite show the intersection.  If you are local and know there is a no-left-turn sign there, you can map it with iD like this:

In iD, the small "Turn restrictions" window on the left allows you to define which turns are restricted.

![screen shot 2017-08-30 at 9 57 00 am](https://user-images.githubusercontent.com/1892250/29884860-9e27f1fe-8d69-11e7-9e47-3e717b5b365e.png)

You'll probably need them on both those traffic lights that cross Herkulesgatan if turns are not possible.

I'm not 100% sure that we should worry about the "sharp left" vs "u-turn" problem here - the turn shouldn't be possible, so this is sort of a case of bad data messing with the guidance logic.

**Comment by davols** [comment]
Thanks,
I'll check tomorrow at the office. My bad, didn't mean it was against the
traffic in a one way. Was told it was classed as a one way (going the
correct way, the road following out before taking the turn/uturn) and that
would have meant no left turns are allowed.

I'll also talk to the people who are more experienced in the Stockholm
traffic. But left turns are definitely illegal there.

Got a bit curious if it could be other places where the maneuver is
incorrect, randomly stumbled upon this while out testing navigation.

On 30 Aug 2017 18:59, "Daniel Patterson" <notifications@github.com> wrote:

@davols <https://github.com/davols> OSRM will never send you *against* a
one-way, but that doesn't seem to be the prbolem here. It looks like some
turn restrictions need to be mapped.

The best imagery I could find for mapping from my desk was:

https://www.mapillary.com/app/?lat=59.32975609&lng=18.0621365&z=17&pKey=
WKaTLjN97TryHnL1ni2etw&focus=photo&x=0.48520501854026465&y=
0.5859904278149684&zoom=0

which doesn't quite show the intersection. If you are local and know there
is a no-left-turn sign there, you can map it with iD like this:

In iD, the small "Turn restrictions" window on the left allows you to
define which turns are restricted.

[image: screen shot 2017-08-30 at 9 57 00 am]
<https://user-images.githubusercontent.com/1892250/29884860-9e27f1fe-8d69-11e7-9e47-3e717b5b365e.png>

You'll probably need them on both those traffic lights that cross
Herkulesgatan if turns are not possible.

I'm not 100% sure that we should worry about the "sharp left" vs "u-turn"
problem here - the turn shouldn't be possible, so this is sort of a case of
bad data messing with the guidance logic.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Project-OSRM/osrm-backend/issues/4457#issuecomment-326054224>,
or mute the thread

**Comment by davols** [comment]
@danpat and cc @daniel-j-h 
The same example route now (quite visible on the map) has two left turns that the instructions format to a u-turn. For this new update I think it's fine (the lesser more informative instructions the better, so one uturn instead of 2 basically at the same time and place).

Wondering if it can be an issue with guidance logic and the instructions in other situations. Where it ought to be a sharp left turn or similar instead of a u-turn. But this specific issue can be closed.
