### ISSUE TITLE
Car Profile: Handling of `highway=primary/secondary/…` + `construction!=yes`

### ISSUE THREAD

**Issue by Nakaner** [Project-OSRM/osrm-backend#4462]
While testing the *osrm-components* and comparing the output of different profiles, I found a routing error which is strange to my understanding as an experienced mapper.

This issue is related to #4230.

![amorbach](https://user-images.githubusercontent.com/3611273/29921062-93a02d40-8e50-11e7-9d1b-c9c557e292a5.png)

The primary road B 47 eastwards between the two roundabouts is flagged as border. It took some time to discover why it was flagged: The [western roundabout](https://www.openstreetmap.org/way/234580798#map=19/49.64671/9.21963) is tagged `highway=primary` + `construction=primary`. This is a left-over of the time when it was build (according to `note=*` tags in that area in May 2014).

While [Daniel's pull request](https://github.com/Project-OSRM/osrm-backend/pull/4258) improved the handling of `highway=primary/secondary/…` + `construction=yes`, it broke the handling of these partially broken tagging like this roundabout in Amorbach.

The number of `highway=primary/secondary/…` + `construction=yes` will decline in the next months because Geofabrik will add two additional layers to the OpenStreetMap Inspector which highlight misleading tagging (`highway/railway/shop/amenity=<under operation>` + `construction=yes`) in a few days. As a side effect, they will also mark `construction!=no` with `highway!=construction`.

Used OSRM version: 5.9.2, OSM data less than 3 days old

**Comment by emiltin** [comment]
I think what you're describing is a mapping error, or do you propose any change to the code?

**Comment by Nakaner** [comment]
It is a mapping error but `construction=yes` + `highway=primary` is also a mapping error but supported by the car profile (it treats it as construction). I propose either a change to the code or a "won't fix" statement.

**Comment by daniel-j-h** [comment]
We discard construction ways (except: no, widening, minor) in the default profile on purpose to incentivize proper tagging. Feel free to disable the construction tag handling in your own profile modifications.

Note: the same applies to the proposed tag.

**Comment by maraf24** [comment]
> We discard construction ways (except: no, widening, minor) in the default profile on purpose to incentivize proper tagging. 

This doesn't really work. There are thousand of roads with construction=<category> leftovers in osm data and OSRM doesn't route through them today.
Fixing this is non-ending work, as people are generally unaware of the problem and the most popular editor, iD, is main culprit here.

**Comment by danpat** [comment]
Yes, it will - but similar to `construction=yes`, I've found that the majority of those are stale too.
