### ISSUE TITLE
Loss of precision in annotations speed

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#4463]
This is somehow close to #3744 but different: `speed` values in annotations sometimes go crazy when duration is reported as (close to) 0, e.g. in [that request](http://router.project-osrm.org/route/v1/car/-0.1596971,51.4897874;-0.1610354,51.4906511?annotations=true).

Maybe not such a big deal as the documentation states that `speed` is just a "convenience" field and this corner case can be filtered by looking directly at  `duration` and `distance` values. Can be surprising though for someone relying on the returned speed values.

**Comment by daniel-j-h** [comment]
See https://github.com/Project-OSRM/osrm-backend/issues/4283

**Comment by jcoupey** [comment]
@daniel-j-h didn't find that one before posting, sorry for the duplicate.

**Comment by daniel-j-h** [comment]
No worries, I hit it by accident during map matching :)
