### ISSUE TITLE
Building OSRM-backend takes too long 

### ISSUE THREAD

**Issue by RSA77** [Project-OSRM/osrm-backend#4464]
When building OSRM-backend on Ubuntu 17.0, the "cmake --build ." command seems succeed to build the following targets:

- Updater
- UTIL
- osrm_update
- CONTRACTOR
- STORAGE
- osrm_store
- osrm_contract
But it seems hanging when compiling parameters_parser.cpp
For more than 1 hour (maybe more even), nothing happens and the last message displayed at the prompt is the following:

"[20%] building CXX object CMakeFiles/SERVER.dir/src/server/api/parameters_parser.cpp.o"

1- Is it normal that it takes such long time to compile ? If yes, anyone has an idea how long it takes to compile all OSRM-backend (approximately) ?
2- If not, could you please help me investigating this issue ?

Thanks,

**Comment by daniel-j-h** [comment]
How much memory do you have? LTO needs quite a bit.

Usual build times are in the minutes.

**Comment by RSA77** [comment]
Thanks for your quick reply Daniel and for this hint. I was at 1Gb ram aloocated to my VM and I processor.
I increased settings to 2 processors and 4Gb RAM and now it's much better, SERVER module is built !
I should have thought about this by myself !
Many thanks :)
