### ISSUE TITLE
Foot profile producing unexpected routing

### ISSUE THREAD

**Issue by neilRGS** [Project-OSRM/osrm-backend#4468]
I have compiled a profile for Foot, using europe-latest, and am getting some interesting results from it.
In particular, there is a hill in the town in which I live, which has a footpath on each side of it.
Starting at the bottom of the hill and plotting a route approx. 500m in length, up the hill, and across the road at the top, works fine for Car and Bicycle (image 1), but for Foot, causes the route to go wildly off and produces a route of approx. 27.5km (image 2)

What might be the cause of this, and is there something I would need to modify in the lua script to fix it?

Thanks in advance,

Neil.

Image1
![image](https://user-images.githubusercontent.com/12459731/29960095-29859c2c-8ef2-11e7-981d-116f7398ab6d.png)

Image 2
![image](https://user-images.githubusercontent.com/12459731/29960113-39f01dee-8ef2-11e7-9594-baa773ad54ee.png)

**Comment by emiltin** [comment]
Are you using the default foot profile? Adams Hill http://www.openstreetmap.org/way/6012337 is tagged as a trunk road, which is not routable by foot by default. Kind Edward Road and Northwich Road are also trunk roads, and it seems there is no where in the map where a pedestrian can cross, ie. there are no direct cross-roads. This is probably why the route ends up on a huge detour.

If you can in fact walk along these trunk roads, they need to be tagged in foot=yes or separate paths need to be added to the road.

**Comment by neilRGS** [comment]
Hi Emil.
Thanks for your response.

Yes, I am using the default foot profile.
So it seems like the map needs changing then.
Indeed, the roads are walkable and there are a number of official pedestrian crossings, one being at the top of Adam's Hill, so the walking route is almost identical to the bike and car routes :)

I'll close this now, as you have kindly answered my question.

Have a good weekend!

N.
