### ISSUE TITLE
Routing service api returns wrong coordinates in response

### ISSUE THREAD

**Issue by adarsh9975** [Project-OSRM/osrm-backend#4469]
i'm working on a project for which i need to send a route request to osrm api to send me route form coordinate A and end at coordinate B.
here is the request i send:

http://router.project-osrm.org/route/v1/driving/18.6523446,73.7617461;18.6521637,73.7623703?alternatives=false&steps=false&geometries=geojson&overview=false&annotations=false

The response i get is : 

{
   "code":"Ok",
   "waypoints":[
      {
         "hint":"2PqDj9n6g48WAAAAAAAAAEIAAAAAAAAAFgAAAAAAAABCAAAAAAAAAJbkCIC3am4Bjp08BLmcHAHSg2UEBACvE3NqiII=",
         "location":[
            24.013495,
            71.081358
         ],
         "name":""
      },
      {
         "hint":"2PqDj9n6g48WAAAAAAAAAEIAAAAAAAAAFgAAAAAAAABCAAAAAAAAAJbkCIC3am4Bjp08BAScHAFChmUEBACvE3NqiII=",
         "location":[
            24.013495,
            71.081358
         ],
         "name":""
      }
   ],
   "routes":[
      {
         "legs":[
            {
               "steps":[
               ],
               "weight":0,
               "distance":0,
               "summary":"",
               "duration":0
            }
         ],
         "weight_name":"routability",
         "weight":0,
         "distance":0,
         "duration":0
      }
   ]
}

Note that the route i requested is 18.6523446,73.7617461 to 18.6521637,73.7623703 but what i receive is a wrong route that starts and ends at the coordinate 24.013495,71.081358 . 
I don't know what's wrong. when i plot the same route on osrm demo i get a proper route :
 
![image](https://user-images.githubusercontent.com/31591230/30003680-eb3b7af6-90de-11e7-92ef-89ecbc3e36b1.png)

so i think that its possible for osrm service to plot the route around this premises, but then why does api fail to do the same. i have double checked the structure of request as per osrm documentation and also cross verified the coordinates that i'm feeding in request by means of google maps. Am i doing something wrong ?

**Comment by daniel-j-h** [comment]
Order is longitude,latitude.

**Comment by danpat** [comment]
@adarsh9975 yes, @daniel-j-h is correct, you need to swap the longitude/latitude values in your request.   The correct URL for you is:

http://router.project-osrm.org/route/v1/driving/73.7617461,18.6523446;73.7623703,18.6521637?alternatives=false&steps=false&geometries=geojson&overview=false&annotations=false

**Comment by adarsh9975** [comment]
Oh... That was a silly mistake on my part... I'll try it  out when the server is back up. 

By the way... Do you know that the routing service is down ? It says that the service is unavailable

**Comment by adarsh9975** [comment]
Thanks :)
