### ISSUE TITLE
osrm-extract hangs with planet file

### ISSUE THREAD

**Issue by pir1981** [Project-OSRM/osrm-backend#4470]
Hi, 
I am extracting the planet file, but it now takes 4 days (so really slow and the last 1.5 days it just doesn't seem to do anything anymore.). 

```
[info] Using script /usr/local/share/osrm/profiles/car.lua
[info] Input file: planet-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 8
[info] Parsing in progress..
[info] input file generated by planet-dump-ng 1.1.4
[info] timestamp: 2017-08-21T01:59:41Z
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parsing finished after 2044.33 seconds
[info] Raw input contains 4035672578 nodes, 431724615 ways, and 685807 relations
[info] Sorting used nodes        ... ok, after 9.62709s
[info] Erasing duplicate nodes   ... ok, after 1.35161s
[info] Sorting all nodes         ... ok, after 778.607s
[info] Building node id map      ... ok, after 194.672s
[info] setting number of nodes   ... ok
[info] Confirming/Writing used nodes     ... ok, after 217.938s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 664012987 nodes
[info] Sorting edges by start    ... ok, after 999.159s
[info] Setting start coords      ... ok, after 1618.83s
[info] Sorting edges by target   ... ok, after 828.415s
[info] Computing edge weights    ... ok, after 1591.22s
[info] Sorting edges by renumbered start ... ok, after 906.929s
[info] Writing used edges       ... ok, after 153.955sProcessed 701474435 edges
[info] Sorting used ways         ... ok, after 58.6426s
[info] Sorting 685807 restriction. by from... ok, after 0.958929s
[info] Fixing restriction starts ... ok, after 1147.09s
[info] Sorting restrictions. by to  ... ok, after 0.022017s
[info] Fixing restriction ends   ... ok, after 119.233s
[info] number of restrictions saved to memory: 660298
[info] number of conditional restrictions written to disk: 0
[info] writing street name index ... ok, after 32.0895s
[info] extraction finished after 10728.4s
[info] Generating edge-expanded graph representation
[info] Importing number_of_nodes new = 664012987 nodes
[info]  - 142782 bollard nodes, 928817 traffic lights
[info]  and 701474435 edges
[info] Graph loaded ok and has 701474435 edges
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.191604
[info] Edge compression ratio: 0.227412
```

Maybe my swap and stxxl is just not set up inappropriately, but I have done Europe on another system previously and that one was done in 4h....

I have the following system

2HDs 

- 4 TB SATA 6 Gb/s 7200 rpm HDD Enterprise-Class
- 64 GB DDR4 RAM
- Intel® Core™ i7-6700 Quad-Core Skylake incl. Hyper-Threading

HD1 has the
- system
- programs
- osm.pbf file on it
- the extracted data should go on this one
- partition with 32G swap
- running osrm 5.9.0 in docker and do have libstxxl1 and libstxxl-dev 

 HD2 mostly is empty (but the space is going to be needed for some other big data)

My extract approach was to set up another swap of 300G on HD2 and stxxl of 300G on HD2. But it seems to be too slow. iotop has some reading and some writing activity on it, but nothing major. htop does not show any significant cpu usage(at the mentioned end point). I start with 8 processes.

1.  Is there a better way to set up the additional swap and stxxl (maybe the swap on HD1 and only the stxxl on HD2)?

2. If I could move the files and target locations of the extracted data as wanted, would it be even better to maybe do .pbf on HD1, all swap and stxxl on HD1 and extracted data on hd2(and then just copy it to HD1)?

3. Did maybe something change between 5.6 (this is the one I had success with using stxxl) and 5.9 Versions? I tried to restart and just leave stxxl away and I didn't get any error messages. I also can't find any stxxl files in the file I specified in .stxxl....

4. I am looking at your own docker image and you don't specify any .stxxl creation/location in that help section either (yet it is installed in the image). Do you recommend running without it in docker?

Thanks

**Comment by pir1981** [comment]
I just started your image:latest with and without .stxxl and osrm does not complain about stxxl (it did in previous versions). 

[info] Using script /opt/car.lua
[info] Input file: planet-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 8
[info] Parsing in progress..
[info] Using profile api version 2
[info] input file generated by planet-dump-ng 1.1.4
[info] timestamp: 2017-08-21T01:59:41Z
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Using profile api version 2
[info] Using profile api version 2
[info] Using profile api version 2
[info] Using profile api version 2
[info] Using profile api version 2
[info] Using profile api version 2
[info] Using profile api version 2

my .stxxl is
disk=/osrm/hd1/tmp/stxxl,250000,syscall

I also thought that in the previous version I saw a stxxl being created in the folder where the .stxxl pointed to, but nothing show up in my folders now

**Comment by pir1981** [comment]
```
[info] Parsing finished after 5482.94 seconds
[info] Raw input contains 4035672578 nodes, 431724615 ways, and 703372 relations
[info] Sorting used nodes        ... ok, after 14.9717s
[info] Erasing duplicate nodes   ... ok, after 1.35013s
[info] Sorting all nodes         ... ok, after 1363.96s
[info] Building node id map      ... ok, after 288.818s
[info] setting number of nodes   ... ok
[info] Confirming/Writing used nodes     ... ok, after 155.814s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 664012987 nodes
[info] Sorting edges by start    ... ok, after 1460.3s
[info] Setting start coords      ... ok, after 2369.12s
[info] Sorting edges by target   ...

```
the times are even worse with the pulled image....

**Comment by daniel-j-h** [comment]
Check if you're swapping - you probably are.

We disabled stxxl a couple of versions ago and the Dockerfile wasn't updated to explicitly enable stxxl. I think the reasoning was that for "casual" use-cases our pre-built binaries and Docker images should not require the user to set up complicated stxxl config.

If you're processing the planet you should know that the Docker abstraction layer adds quite a bit overhead to processing. Anyway, I recommend compiling manually with

    cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_STXXL=On -DENABLE_LTO=On

https://github.com/Project-OSRM/osrm-backend/blob/master/CMakeLists.txt#L29

Hope that helps

**Comment by pir1981** [comment]
Yes, I do use swap (RAM is full).

I will rebuild. 

But, why do you recommend to turn stxxl on again though, if you had a good reason to turn it off completely? Or is it just that there is an expectation that people running planet, turn it on themselves?

Any suggestion on the split of file, swap, stxxl and target folder across 2HDs?

**Comment by pir1981** [comment]
should there be a warning if stxxl is build in and not used?
I am testing europe on another machine and get with the above updated build and not defining .stxxl

```
[info] Using script /usr/local/share/osrm/profiles/car.lua
[info] Input file: europe-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 24
[info] Parsing in progress..
[info] Using profile api version 2
[info] input file generated by osmium/1.5.1
[info] timestamp: 2017-08-23T20:43:02Z
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
```

I recall there was a warning message in previous versions


and here the code when using .stxxl, but I see no stxxl created in the folder that I specified in .stxxl and also the .stxxl is gone right after starting osrm-extract

```
[info] Using script /usr/local/share/osrm/profiles/car.lua
[info] Input file: europe-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 24
[info] Parsing in progress..
[info] Using profile api version 2
[info] input file generated by osmium/1.5.1
[info] timestamp: 2017-08-23T20:43:02Z
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle

```

**Comment by danpat** [comment]
@pir1981 STXXL is only used for some data structures - other parts still require regular RAM.

The problem is that you do not have enough to process `planet.pbf` quickly.

I just checked the OSRM demo server - it uses about 150GB for `osrm-extract` and 110GB for `osrm-contract` - the STXXL and disk space is *in addition* to this RAM requirement.

If you have less RAM than that (and you only have 64GB+32GB swap), then it will be very (very) slow, and will probably fail.  It takes about 16 hours for the demo server to process a planet.pbf, and our server has 244GB of RAM available.  If you end up using swap space, it will be *much* slower.

**Comment by pir1981** [comment]
Hmm I though 64G RAM+32 swap partion was enought (+swap of 300G on HD2 and stxxl of 300G on HD2), but I guess the emphasis is on very, very slow..... very, very slow (even with the huge swap)

[https://github.com/Project-OSRM/osrm-backend/issues/1845](https://github.com/Project-OSRM/osrm-backend/issues/1845)
[https://github.com/Project-OSRM/osrm-backend/issues/754 ](https://github.com/Project-OSRM/osrm-backend/issues/754 )

Prior to closing this, can you please help me on the stxxl. I'd like my code to at least be clean, so when we move to a bigger instance, we are up and running in seconds.

> I recall there was a warning message in previous versions
> 
> and here the code when using .stxxl, but I see no stxxl created in the folder that I specified in .stxxl and also the .stxxl is gone right after starting osrm-extract

**Comment by daniel-j-h** [comment]
Maybe don't check a ticket from 2013 for system requirements :P 

Here is a Wiki page with memory and disk requirements which should be up to date, more or less:

https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements

Here is a Wiki page about running osrm and configuring the stxxl subsystem:

https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

If you don't specify a stxxl config I think by default a stxxl file will be created at `/var/tmp/stxxl`.

**Comment by pir1981** [comment]
> Maybe don't check a ticket from 2013 for system requirements :P

I will remember that :)

I actually do create a .stxxl in the folder where I have the .pbf and where I also extract, but as I said, I would expect that in the folder mentioned in .stxxl I would see a stxxl. And also that the .stxxl would stay where I put it, rather than disaperaing after start.

**Comment by danpat** [comment]
@pir1981 RAM vs SSD is a big speed difference, particularly for random access like OSRM does during pre-processing.  This list is a handy reference:

https://gist.github.com/jboner/2841832

RAM = 100ns per read
SSD = 150,000ns per read

That's (very) roughly the slowdown you'll see if OSRM can't use pure RAM.

As of OSRM 5.11, `osrm-extract` no longer uses STXXL, so you won't see it getting initialized when you use that tool.  It is still used for `osrm-contract` and some other tools.

**Comment by pir1981** [comment]
@danpat & @daniel-j-h thank you for your time and explanations. I guess I will have to find a different way. I just tried Europe car `extract` and `contract` and that ran all together under 2h (and is quarter of the world by GB already). So I guess as you say, the slowdown is from swapping.

I would love to see if there was a possibility to prepare data that can actually be run on a machine, to be also pre-processed on that machine. I guess it is probably quite difficulty to either merge the different world areas, if processed separately, or somehow just read smaller chunks of data into RAM and when maybe 1/5 is pre-processed then move to the next chunk....

**Comment by daniel-j-h** [comment]
If you want to process the planet what you can do is use the osmium-tool's extract command to cut out disconnected areas from the planet, pre-process them independently and then spawn up multiple osrm-routed instances. Then schedule requests onto the osrm-routed instance responsible for the area or abort on cross-continent routes. There's no way to merge multiple .osrm\* files into a single one.

Good luck!

**Comment by danpat** [comment]
@pir1981 Unfortunate, the primary routing algorithm in OSRM (Contraction Heirarchies) requires access to the complete routing graph during pre-processing.  It would require some serious re-engineering in order to make it chunkable.

**Comment by alexey-gl** [comment]
Hello,
I think about memory consumption reduсing during preprocessing. 
Tell me please, does it have much sense to filter data (i.e. with [osmfiler](http://wiki.openstreetmap.org/wiki/Osmfilter)) before extract/contract phases?
I mean to leave objects exactly with roads that will used beforehand, just not to do it during extract phase.
Would it help?

**Comment by danpat** [comment]
@alexey-gl Pre-filtering will not make a huge difference - the basic job of `osrm-extract` is to filter the `.pbf` file - OSM ways that are not needed are discarded as soon as they are read from the file.

Pre-filtering the planet will save *some* memory, as unused OSM nodes will not be present (and they get cached until the end of `osrm-extract`), but this is not the largest memory consumer of the pipeline.

**Comment by alexey-gl** [comment]
@danpat
Thanks for answer!
