### ISSUE TITLE
Problem with secondary-link road routing

### ISSUE THREAD

**Issue by AlekseiSolonkov** [Project-OSRM/osrm-backend#4477]
Hi! There is a problem with building a route through secondary-link toll road. 
https://prnt.sc/gh912w
Route from 59.96093, 30.21868 to 59.95567, 30.20865
Mapzen can build route
https://prnt.sc/gh91md
But OSRM can not
https://prnt.sc/gh91xi

**Comment by MoKob** [comment]
You are running into problems related to the construction tag. [this way](https://www.openstreetmap.org/way/302687686#map=19/59.95836/30.23536) is marked as `construction`, which currently results in OSRM excluding it from the graph.

The resulting graph considers the `secondary_link` (and its bridges) as a series of small components, not routing between them.
This issue will automatically resolve if the `construction` tag is removed.

**Comment by daniel-j-h** [comment]
Closing as not actionable on our side; see Moritz's comment above about construction tags.
