### ISSUE TITLE
503 (Service unavailable)

### ISSUE THREAD

**Issue by martinnicolas** [Project-OSRM/osrm-backend#4483]
Hi!.. I'm having a 503 error. Any problem with demo service?..

**Comment by P2W2** [comment]
Me too.

**Comment by martinnicolas** [comment]
Is there any maintenance period for the server that should be considered?

**Comment by miccolis** [comment]
The demo service does not have any guarantees around availability.

If you needs a routing service that is always available I'd suggest looking at [Mapbox](https://www.mapbox.com/api-documentation/#directions), who sponsors OSRM development & is where I work. Our directions service is based on OSRM and should be fairly easy to switch to if you're already using OSRM.

**Comment by martinnicolas** [comment]
Interesting.. I'll consider that.. thanks!

**Comment by willwhite** [comment]
See https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server for an update about the demo server, some alternative recommendations, and a poem.
