### ISSUE TITLE
./node_modules/osrm/lib/binding folder is missing

### ISSUE THREAD

**Issue by juergengunz** [Project-OSRM/osrm-backend#4485]
The folder with the node binding is missing? I cannot get this to work for hours.

I am using Ubuntu 16 and 
nodejs --version v4.2.6

Is there any step by step documenation?

**Comment by daniel-j-h** [comment]
Care to provide more details?

Did you add `osrm` to your `package.json` and or used npm with

    npm install osrm

?

**Comment by juergengunz** [comment]
What I did:
I followed the instruction at "Building from Source" and managed to get my custom .osrm map file. So far so good.

But now I want to use node to access the routing engine.

I did "npm install osrm"
and I am using the node example.js 
I am getting errors like:
Cannot find module './lib/bindings/node_osrm.node'

**Comment by daniel-j-h** [comment]
> Error: Module version mismatch. Expected 48, got 46.

Intesting - looks like your Node ABI changed from v48 (Node 6) to v46 (Node 4). Did you switch Node.js versions between installation and running the example by chance?

**Comment by juergengunz** [comment]
hmm not really..

what's weird:
if i do node --version i get v8.4.0
if i do nodejs --version i get v4.2.6

2017-09-07 14:13 GMT+02:00 Daniel J. H. <notifications@github.com>:

**Comment by daniel-j-h** [comment]
Debian / Ubuntu calls the binary `nodejs` because reasons. See this ticket for previous problems:

https://github.com/cjntaylor/node-cmake/pull/24

I recommend uninstalling the system-wide outdated and weirdly named `nodejs` package for a quick fix.

**Comment by juergengunz** [comment]
ok i managed that problem but now i get following error:

2017-09-07 15:06 GMT+02:00 Daniel J. H. <notifications@github.com>:

**Comment by daniel-j-h** [comment]
Check `server.js` line 10: do you require the osrm module and create an object? Smth. like

    const osrm = OSRM(path);

Sorry but I can't really debug your script.

**Comment by juergengunz** [comment]
yes this is line 10:
var osrm = new OSRM("./map.osrm");

**Comment by danpat** [comment]
@juergengunz you should do:

```
var OSRM = require('osrm');
```

instead.  If you absolutely must do it the way you're doing it, you need to do:

```
var OSRM = require('./lib/binding/node_osrm.node').OSRM;
```

**Comment by juergengunz** [comment]
i managed to get it working , finally.
i removed node completely and reinstalled everything and now it is working
as expected.

thanks for your help :)

2017-09-07 16:35 GMT+02:00 Daniel Patterson <notifications@github.com>:
