### ISSUE TITLE
OSRM returns 0 distance sometimes.

### ISSUE THREAD

**Issue by virattara** [Project-OSRM/osrm-backend#4489]
The coordinates are in the correct sense as opposed to the previous posts. When I refresh the browser for requesting repetitively there are times when I get the correct result but sometimes it returns 0 distance. 
/route/v1/driving/76.810808,30.719047;76.774762,30.7328271

**Comment by danpat** [comment]
@virattara We need more information to help you.

Are you using your own server, or router.project-osrm.org?  If it's your own server, what datafile are you using?

The OSRM demo server is currently not working (and may never come back) - you may be seeing a cached response sometimes, but not on a browser refresh.

**Comment by virattara** [comment]
1. I'm using my own server.
2. Data file india-latest.osm.pbf, downloaded from geofabrik.

**Comment by virattara** [comment]
Also, I found out that not all my requests get logged in the terminal. Quite weird, is OSRM using something to cache results?(I don't think so.)
Any help would be appreciated. Thanks!

**Comment by virattara** [comment]
One more thing, its happening for berlin lat longs too. Sometimes 0 and sometimes the correct result.

**Comment by virattara** [comment]
Anything?

**Comment by danpat** [comment]
@virattara Sounds like your client code has a bug and is not sending all requests.  Can you share the core of your code that requests routes from OSRM?

I'm not aware of any problems like this on the OSRM side - it's used in many high-performance situations over HTTP with no problems.  I suspect your code may have a bug.

**Comment by danpat** [comment]
One thing to check:  many `osrm-routed` servers can run at once, and your operating system (docker) may distribute requests between them.  Check that you don't have more than one `osrm-routed` service running.

**Comment by virattara** [comment]
Actually, I haven't altered the code. I have tried making curl requests to /route/v1/driving/76.810808,30.719047;76.774762,30.7328271 directly and get the same results.
BUT, I think this might be happening that I might be running multiple osrm-routed servers.
How can I check this? Thanks!

**Comment by danpat** [comment]
If you're not sure how to check for multiple running processes (a quick Google search will show you several ways to do this), then restarting your computer is probably the simplest solution.

**Comment by virattara** [comment]
Everything falling into place, missing logs specifically.
The problem was multiple processes.
Thanks again!
