### ISSUE TITLE
API adaptation from v4 to v5

### ISSUE THREAD

**Issue by Facj** [Project-OSRM/osrm-backend#4491]
I have a program that was built to make queries using the server API v4 and  I want to adapt it to the v5 API. I have searching though both API descriptions but I have several doubts.

- Are these query and response fields equivalent?:

```
Old query: 
/viaroute?loc=52.48100391365505,13.385788454768415&loc=52.55954404045714,13.338676039958967&z=18

New query:
/route/v1/foot/13.516778639348594,52.530909810742955;13.359039843535346,52.50079778912763

```

Response fields:
```
           Old                              New 
          route_geometry                    routes->geometry
          route_summary->total_distance     routes->distance
          route_summary->total_time         routes->duration
          route_summary->start_point        waypoints->name (first one)
          route_summary->end_point          waypoints->name (last one) 
```
- I have realized that when a route between two given points cannot be provided (for instance points outside the area), the response consists on a JSON message where all fields in` routes`are 0.  Is that the appropriate way to check that the route cannot be provided? Or is there any other way to check that?

Thanks!

**Comment by daniel-j-h** [comment]
API docs are here:

http://project-osrm.org/docs/v5.10.0/api/#general-options

You will find response codes such as `NoRoute` in there.
