### ISSUE TITLE
Getting more routes

### ISSUE THREAD

**Issue by Behizz** [Project-OSRM/osrm-backend#4492]
hello
I want to generate more than two routes in each osrm answer. Is it possible?
Setting alternate parameter to a value more than 1 results a bad request error and the alternate route doesn't always show up in the results.

**Comment by daniel-j-h** [comment]
You can use the MLD pipeline

```
osrm-extract berlin.osm.pbf
osrm-partition berlin.osrm
osrm-customize berlin.osrm
osrm-routed --algorithm=MLD berlin.osrm
```

then you will get [this alternative routes impl.](https://github.com/Project-OSRM/osrm-backend/pull/4047).

If you start `osrm-routed` e.g. with `--max-alternatives 10` you will get up to 10 alternative routes.

There's no guarantee we will find a single one, though. If you check the implementation there are a few knobw you could tune to trade alternative routes quality with number of alternatives you will get back.

HTH
