### ISSUE TITLE
Validating/Debugging new profiles

### ISSUE THREAD

**Issue by lennartba** [Project-OSRM/osrm-backend#4496]
I try to build some scripts for profile comparison.
Using `&annotations=true` in requests gives me a list of nodes. Is there any easy way of getting a list of way/node attributes together with the route? 
The goal is to compare an old and new (potentially better) profile on a large set of start/finish points and generate some statistics of used highway types.

**Comment by daniel-j-h** [comment]
`?annotation=nodes` will give you osm node ids; there's no feature for way ids - osrm does not store way ids at all.

Same with osm tags: `osrm-extract` uses the profile to extract properties based on osm tags (think: speed, weight, ..). When we're done with running the profiles over the osm base map we no longer have access - or even store - osm tags.

What you can do is use `annotations=nodes` to get osm node ids and then query OpenStreetMap yourself for way ids and tags. Here's an example how to do this: https://github.com/mapbox/route-annotator

**Comment by lennartba** [comment]
Thank you for the hint!

**Comment by lennartba** [comment]
Do steps in OSRM responses correlate with ways?

**Comment by daniel-j-h** [comment]
No, that's why annotations are not in the RouteStep response object.

Annotations are for osm ids and / or osm segments (two adjacent osm ids):

http://project-osrm.org/docs/v5.10.0/api/#routeleg-object

**Comment by daniel-j-h** [comment]
Closing as not actionable from our side; hope my explanation above helps for your use-case.

Happy routing! 🚗
