### ISSUE TITLE
Using the wrong coordinates in API

### ISSUE THREAD

**Issue by faridcboy** [Project-OSRM/osrm-backend#4498]
Im trying to use the service for calculating road distance between to coordinates. However, the coordinates used for calculation in response message are not the I've sent in the request. 

For instance, Consider [this request](http://router.project-osrm.org/trip/v1/driving/38.048682,46.357241;38.068366,46.299005?source=first&destination=last). I've asked for a trip information between `(38.048682,46.357241) and (38.068366,46.299005)` but the response gave the answer for `(38.048001,46.427703) and (38.218883,46.324331)` and you can [check ](http://map.project-osrm.org/?z=14&center=38.055627%2C46.345310&loc=38.048192%2C46.358849&loc=38.068295%2C46.298778&hl=en&alt=0)this trip in the front-end and make sure that there is actually a path between those two coordinates.

This is making the project unusable for me, since it doesn't do the one thing it's supposed to do.

**Comment by danpat** [comment]
@faridcboy Please take a read of the documentation at:

http://project-osrm.org/docs/v5.10.0/api/#general-options

You have missed a few details:

  1.  The `/trip` API is for performing route optimization.  If you've only got 2 coordinates, you probably want `/route`
  2.  Coordinates need to be supplied as `<longitude>,<latitude>`.  If interpreted as `lon,lat`, the coordinates you've supplied are out in the ocean - you need to flip them around.

Also note that the OSRM demo server is just that - a demo server.  Please don't rely on it for anything important, you should run your own service, or use a commercial hosted instance of OSRM.

**Comment by faridcboy** [comment]
@danpat 
Thank you very much,
I've tried /trip too but that wasn't working either. the trick was that the coordinates were put reverse, I still dont get how they're in different order than the Front-end version but it does the job so dont care!

Also, I was in the process of setting my own server with docker till I hit a problem and got here

Thank you
