### ISSUE TITLE
how to find segments around a point?

### ISSUE THREAD

**Issue by mrmrn** [Project-OSRM/osrm-backend#4502]
I am using osrm for 2 days. The performance of matching points to geographical segments was so impressing.
I can find a route between 2 segments very fastm but finding surrounding segments is very time consuming but how OSRM can find surrounding segment so fast?

**Comment by oxidase** [comment]
@mrmrn for finding the nearest segment OSRM uses R-Tree of segments https://github.com/Project-OSRM/osrm-backend/blob/a5776288f6d54d2b3699c0f5cc9193171f3bf1fa/include/util/static_rtree.hpp#L64-L133 with packing via Hilbert values of segment centroid points. Here some references:
```
//[1] "On Packing R-Trees"; I. Kamel, C. Faloutsos; 1993; DOI: 10.1145/170088.170403
//[2] "Nearest Neighbor Queries", N. Roussopulos et al; 1995; DOI: 10.1145/223784.223794
//[3] "Distance Browsing in Spatial Databases"; G. Hjaltason, H. Samet; 1999; ACM Trans. DB Sys
// Vol.24 No.2, pp.265-318
```

For map-matching it uses the Viterby algorithm to compute the best path in a HMM
```
[1] "Hidden Markov Map Matching Through Noise and Sparseness"; P. Newson and J. Krumm; 2009; ACM GIS
```

**Comment by mrmrn** [comment]
thank you.
