### ISSUE TITLE
truck Weight and Width Restrictions - how was this resolved

### ISSUE THREAD

**Issue by tomduffey** [Project-OSRM/osrm-backend#4504]
Weight and Width Restrictions #439
this was closed with a recommendation to modify profile.lua to restrict roads tagged with weight restrictions 

Was it determined that this was a viable solution?

I would like to route on roads that allow heavy trucks. The above issue was open and closed. It suggested modifying profile.lua to exclude those roads.  Is this the viable solution and are there any more details on how to go about doing this?

**Comment by tomduffey** [comment]
has anyone created a profile for this purpose of routing heavy trucks?

**Comment by daniel-j-h** [comment]
Here's an experimental pull request for height and weight: https://github.com/Project-OSRM/osrm-backend/pull/4409

**Comment by tomduffey** [comment]
https://github.com/rodo/osrm-profiles

this has a profile for trucks that looks dated - for older version of osrm

**Comment by daniel-j-h** [comment]
Closing here - WIP is tracked in https://github.com/Project-OSRM/osrm-backend/pull/4409.
