### ISSUE TITLE
[error] Input file not found!

### ISSUE THREAD

**Issue by nixxholas** [Project-OSRM/osrm-backend#4510]
With reference to this issue https://github.com/Project-OSRM/osrm-backend/issues/4253#issuecomment-313667032

What a try hard I am, yes I know. :)
<img width="721" alt="screen shot 2017-09-16 at 3 31 29 pm" src="https://user-images.githubusercontent.com/4703269/30510299-25f95cc0-9af4-11e7-9df9-5ddf409deb44.png">

Host working directory: /Users/nixholas

**Comment by danpat** [comment]
@nixxholas I think you've missed the one combination that should work:

Try this:

```
docker run -t -v ~/Projects/VoltOSRM:/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/asia-latest.osm.pbf
```

This assumes that you've put `asia-latest.osm.pbf` in `~/Projects/VoltOSRM` outside the docker container.  

Note that I added a `/` to the `/data/asia-latest.osm.pbf` - the default working directory when the docker image is launched is `/opt` or `/src`, so `data/asia-latest.osm.pbf` would be relative to one of those, which is not correct (which explains why several of your attempts don't work).

**Comment by nixxholas** [comment]
Thank you! Solution solved.

**Comment by RobertSellers** [comment]
I had a similar "mapping" issue on Ubuntu. The following worked without the ~ tilde.

```bash
sudo docker run -t -v /data/osrm_data:/data/ osrm/osrm-backend osrm-extract -p /opt/car.lua /data/northkorea.osm.pbf
```
