### ISSUE TITLE
Routing over military landuse?

### ISSUE THREAD

**Issue by dooley** [Project-OSRM/osrm-backend#4522]
http://map.project-osrm.org/?z=16&center=48.210225%2C11.591102&loc=48.209010%2C11.595340&loc=48.211276%2C11.582122&hl=en&alt=0

The only restriction i can find in the relevant data is @ https://www.openstreetmap.org/node/1248612371

In the car.lua (foot, bicycle also) the keys *=private beat access=no.

I'm not sure how this can be solved - of course it is not allowed for the public to drive over military landuses, therefore it should not be allowed by default. 

The Mapbox Directions Engine (which uses also OSRM, i think), as well as Grashopper or Mapzen does not route not over the military landuse.

https://www.openstreetmap.org/directions?engine=osrm_car&route=48.2113%2C11.5821%3B48.2090%2C11.5954#map=16/48.2098/11.5884
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=48.2113%2C11.5821%3B48.2090%2C11.5954
https://www.openstreetmap.org/directions?engine=mapzen_car&route=48.2113%2C11.5821%3B48.2090%2C11.5954

**Comment by dooley** [comment]
I solved it by preprocessing the input data.

**Comment by systemed** [comment]
I've come across this a few times. Really, roads within military areas should be tagged with `access=no` or `access=private` and it's a mapping error if they're not. There are public access roads (often with limited opening hours) within military areas in some countries, so you can't just infer it from the landuse.

**Comment by dooley** [comment]
True, i found that out after cut out all ways inside/crossing landuse=military before throwing the data into osrm-extract. I.e. L 169, which crosses Truppenübungsplatz Baumholder in Germany is valid to drive.

**Comment by AndreyGurevich** [comment]
> I've come across this a few times. Really, roads within military areas should be tagged with `access=no` or `access=private` and it's a mapping error if they're not. There are public access roads (often with limited opening hours) within military areas in some countries, so you can't just infer it from the landuse.

Tag "access=military" exist in OSM now. Could it be more appropriate?
