### ISSUE TITLE
multiple osrm on centOS7

### ISSUE THREAD

**Issue by hapi100** [Project-OSRM/osrm-backend#4523]
I am having 5 different aws centOS7 running osrm. I am using the docker osrm instance. 

git clone https://github.com/Project-OSRM/osrm-backend.git
docker build -t my_osrm:latest -f docker/Dockerfile .

	sudo docker run -t -v /root:/data my_osrm:latest osrm-extract -p /opt/car.lua /data/orrm_state1.osm
	sudo docker run -t -v /root:/data my_osrm:latest osrm-contract /data/orrm_state1.osrm
	sudo docker run -t -p 5000:5000 -v /root:/data my_osrm:latest osrm-routed /data/orrm_state1.osrm &

Can i move all these instance into one and run on different ports? Do i need different osrm-backend compiled or I can use the same code base?

sudo docker run -t -p 5000:5000 -v /root:/data my_osrm:latest osrm-routed /data/orrm_state1.osrm &
sudo docker run -t -p 5001:5001 -v /root:/data my_osrm:latest osrm-routed /data/orrm_state2.osrm &
sudo docker run -t -p 5002:5002 -v /root:/data my_osrm:latest osrm-routed /data/orrm_state3.osrm &

**Comment by daniel-j-h** [comment]
Depends on what you want to do. If you want to run a single box responsible for routing all your states, you have to merge your smaller pbfs into a large one (check out osmium-tool for that) and then run the osrm toolchain on that merged pbf.

If you want to keep running smaller instances for states and the instances are truly the same you can run extract and contract on a single box and then save all the `.osrm*` files e.g. to s3. Then your instances for serving the files can fetch from s3 again.

If you want to run all routed binaries on a single instance you can do that, too. Check out @danpat's comment [here](https://github.com/Project-OSRM/osrm-backend/issues/4517#issuecomment-330359238) for a nginx re-write rule to dispatch based on url.

**Comment by hapi100** [comment]
Thanks @daniel-j-h , we just have driving routes requirement.  Options 1 sounds to be good. Only thing I have to look out is how big the combined file gets and if i run into memory issues.

**Comment by daniel-j-h** [comment]
Perfect - happy routing! 🚗
