### ISSUE TITLE
[osrm-routed] Requests are blocked by long-running request despite other cores and threads are available

### ISSUE THREAD

**Issue by klesniewski** [Project-OSRM/osrm-backend#4529]
We have two types of requests that we run against OSRM:
- fast /nearest and /rotue requests, which are processed under millisecond
- long running /match requests, which depending on input data can take 1 to 500 seconds (500 seconds for larger batch of low accuracy position samples matched against road network)

We noticed, that despite osrm-routed has available threads and vCPUs, a long-running request can block other requests (the other requests will be completed only after the long-running request finishes). Because of that, the processing time of fast requests can be as long as 500 seconds instead of sub millisecond.

It looks as if the requests processing thread pool was assigning requests to all, even busy threads, and not to the available threads. Another possibility is that other requests are blocked by a mutex or another synchronization mechanism.

**Expected behavior**
When osrm-routed is busy processing a longer requests, while there are still free processing threads and CPU power, other requests should be served immediately.

**Actual behavior**
When osrm-routed is busy processing a longer request, serving other requests may or may not be delayed until processing of the longer request has finished, despite processing threads and vCPUs are available.

**Steps to reproduce**
1. Run many concurrent fast requests to verify, that these can be processed right away.
2. Start long running requests.
3. Again, run many concurrent fast requests. This time some requests will not complete.

To reproduce the issue, I used ApacheBench (`apt-get install apache2-utils`):

```
# Step 1
ubuntu@vtg-osrm-bench-01-a:~$ ab -n 5000 -c 2 -s 5 'http://osrm:5002/nearest/v1/main/6.0565166473389,51.406173706055?number=1&generate_hints=false'
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking osrm (be patient)
Completed 500 requests
Completed 1000 requests
Completed 1500 requests
Completed 2000 requests
Completed 2500 requests
Completed 3000 requests
Completed 3500 requests
Completed 4000 requests
Completed 4500 requests
Completed 5000 requests
Finished 5000 requests


Server Software:
Server Hostname:        osrm
Server Port:            5002

Document Path:          /nearest/v1/main/6.0565166473389,51.406173706055?number=1&generate_hints=false
Document Length:        94 bytes

Concurrency Level:      2
Time taken for tests:   1.597 seconds
Complete requests:      5000
Failed requests:        0
Total transferred:      1915000 bytes
HTML transferred:       470000 bytes
Requests per second:    3131.46 [#/sec] (mean)
Time per request:       0.639 [ms] (mean)
Time per request:       0.319 [ms] (mean, across all concurrent requests)
Transfer rate:          1171.24 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:     0    0   0.1      0       1
Waiting:        0    0   0.1      0       1
Total:          0    1   0.1      1       2

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      1
  95%      1
  98%      1
  99%      1
 100%      2 (longest request)

# Step 2: Now start a long running request
ubuntu@vtg-osrm-bench-01-a:~$ curl -g 'http://osrm:5002/match/v1/main/polyline(}oq{HcsuZ`zDiqFjdDg}LxfPbw@rgQwkK|gKy_rAhmB}tj@p|SqmWwzCynn@r{D_nn@brLgff@`a@s~@lfFstDlcMchJ|rGyud@n`T}yAhg@orTnnNsga@nyK}a[xbCadFnhHzwC~kArjB|sLd[`jK}ce@ttVq qVf|W}iXtwRwul@hnSw|Kf}Qq_@~vYsw\d`NwxOncAsyUdp@zjDumCwgcAhdUeiFjp]bvDpjPi_Dt}UiqB`fBocKpaAwmIx_Aq}DwLdi@rtAqtCp`Mi}GpoV~cK|{FrlBvt^nuF~mFboTetDttMecAbqA|qAe}CuqG~bB_hOanCkvIsrMuhTi~H_wTjuAo_BgoAelB{zAk`Ar|Da|InrI_rJgCauRbqC{qi@yAuhOpkMp sI`qv@_{G|uT_|]jjZkeQhmVw`Td`DsfP~yXomY~cb@apPldKu{Nj}KspJcuEesH`|O{jItbFmkCdxTazIncV_rQtzg@{fGr}_@)?radiuses=200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200 ;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200;200&generate_hints=false&overview=full&timestamp s=1499772578;1499774187;1499774971;1499775754;1499776537;1499778102;1499778890;1499779678;1499780467;1499781250;1499782033;1499782817;1499783615;1499784409;1499785200;1499785984;1499786766;1499787560;1499788343;1499789127;1499789925;1499 790709;1499791495;1499792277;1499793061;1499793842;1499794630;1499795411;1499796191;1499796980;1499797761;1499798542;1499799322;1499800883;1499801674;1499802454;1499803234;1499804016;1499804804;1499805583;1499807921;1499808701;1499809498 ;1499810278;1499811057;1499811844;1499812624;1499813404;1499814186;1499862596;1499863377;1499864164;1499864945;1499865735;1499866521;1499867309;1499868092;1499869052;1499887659;1499888440;1499889228;1499890013;1499890793;1499891573;14998 92353;1499893134;1499893924;1499894706;1499895488;1499896270;1499897052;1499897830;1499898608;1499899393;1499900176;1499900954;1499901733;1499902511;1499903290;1499904067' &>/dev/null &
[1] 23764

# Step 3: Run fast, concurrent requests again. Note that requests concurrency is 2, while osrm-routed has 3 threads, and machine has 4 vCPUs
ubuntu@vtg-osrm-bench-01-a:~$ ab -n 5000 -c 2 -s 5 'http://osrm:5002/nearest/v1/main/6.0565166473389,51.406173706055?number=1&generate_hints=false'
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking osrm (be patient)
apr_pollset_poll: The timeout specified has expired (70007)
Total of 53 requests completed

# Repeating Step 3 - number of succeeded requests is random - it really depends on luck whether your request will get through or not
ubuntu@vtg-osrm-bench-01-a:~$ ab -n 5000 -c 2 -s 5 'http://osrm:5002/nearest/v1/main/6.0565166473389,51.406173706055?number=1&generate_hints=false'
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking osrm (be patient)
Completed 500 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 686 requests completed
```

As our tests show, number of completed requests is random. We assume that it is due ApacheBench workers (concurrent clients) not progressing when blocked by long running request.

**Setup**
OSRM v5.11.0
Ubuntu 16.04 LTS
AWS EC2 c4.xlarge (4 vCPUs)
Railway data set for the whole planet - needs only around 1 GB of memory
osrm-routed with 3 threads to process requests

**Current workaround**
We have two OSRM processes running, and Nginx in front, which based on request (/match or not /match) directs traffic to specific process. This way long running requests are isolated from fast running requests. For larger data sets (road network, 45GB of memory), we load data into shared memory and make two osrm-routed processes use it.

**Comment by daniel-j-h** [comment]
Please don't use osrm-routed for anything serious and especially not for your production setup.

We recommend using the Node.js bindings on top of libosrm or libosrm directly.

osrm-routed is really just a development server and should not be used for production workloads.

**Comment by klesniewski** [comment]
I see. Thank you for the information.

I have been reading some posts [1|https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04] and issues, and I never saw it mentioned, that osrm-routed should not be used for production use. We have noticed however some issues with it (the above one + not really timing out requests, what makes it easy to throw bunch of long requests and keep it busy for a while), and now we know we shouldn't be using it as provided. We will write a Node.js server then.

I guess we can close this issue then. Thanks.
