### ISSUE TITLE
Does the demo server support different profiles?

### ISSUE THREAD

**Issue by astridx** [Project-OSRM/osrm-backend#4530]
Is there a way to use different profiles - car, bike or foot - with the demo server ?
http://map.project-osrm.org

**Comment by daniel-j-h** [comment]
The demo server only runs a single profile (car) - if you want multiple profiles you have to run a routing engine yourself or use hosted services such as Mapbox (disclaimer: core devs are with Mapbox).

- https://www.mapbox.com/api-documentation/#directions
- https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

**Comment by astridx** [comment]
Thank you very much for your answer.
