### ISSUE TITLE
Show if there are hov lanes in the route

### ISSUE THREAD

**Issue by joseflorido** [Project-OSRM/osrm-backend#4533]
Hi!

Is it possible to include in the response if the route includes hov lanes?

Thanks
Jose

**Comment by danpat** [comment]
@joseflorido Yes, but it will require some modification of the pre-processing Lua scripts.

Every response with `steps=true` contains `intersection` objects (http://project-osrm.org/docs/v5.10.0/api/#intersection-object).  These intersections have a `classes` property that describe the road class of each road exiting the intersection.

If you add a new class called `hov_only` here:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L103

Then modify the `WayHandlers.classes` function here:  https://github.com/Project-OSRM/osrm-backend/blob/fa1a4e8bf6589f8483ff8fe412ee289db3615d52/profiles/lib/way_handlers.lua#L282

Then the `intersections` object will contain `hov_only` entries in the `classes` property for road sections that you tagged with the `hov_only` class.

**Comment by joseflorido** [comment]
Thanks! That sounds great.

So, after editing the profile and the lib way hander, I imagine I need to prepare (extract, partition, customize) dataset again, right? Do I also need to compile OSRM from source after the change?

Also, to be able to get the geography (polyline) of the way with a particular class (hov or toll for example), is it possible to get it from OSRM? Otherwise, is it possible to get the OSM way ID and then query a pgsql imported dump of osm by ID and get the geometry from there? All I am trying to do is be able to color code parts of a route based on hov_lane availability and also based on toll/no toll type of road.

Thanks!
Jose

**Comment by danpat** [comment]
Yes, you'll need to re-run the complete toolchain, but you don't need to re-compile OSRM - the `.lua` scripts are used by `osrm-extract` to figure out what to do with the OSM data that it reads.

You'll need to do some math to get the class-specific geometry segments.  The `intersection` objects have the coordinate of each intersection, and the class of the outgoing roads.  You will have to use that data, and the route geometry to locate the spots the classes start/stop, and snip out the geometries that represent them.

**Comment by joseflorido** [comment]
Thanks!

Oh, great, the approach of extracting the segment of the total step geometry using the lat,lng of the intersections sound much simpler than what I had in mind :)
