### ISSUE TITLE
Release version branch build is broken when osrm-deps is updated to the latest in master

### ISSUE THREAD

**Issue by ssuluh** [Project-OSRM/osrm-backend#4534]
As of right now all the older releases build is broken because osrm-deps-win-x64-14.0.zip is not versioned. 
Is there a possibility to version this zip files so older releases can be built ?
Also it'll be good to have access to all the previous release build artifact, so far it seems we only keep the latest.

Environment: Windows build
Step to reproduce:
1. Clone the repo and checkout 5.12 release branch
2. Execute ./build-local.bat

**Comment by oxidase** [comment]
@ssuluh Hi, i have reverted to the previous state `osrm-deps-win-x64-14.0.7z` and opened https://github.com/mapbox/windows-builds/pull/116 to add a date version suffix to osrm dependencies archive. 

Please, could you check if it fixed the issue?

**Comment by ssuluh** [comment]
@oxidase, thank you for resolving the issue
