### ISSUE TITLE
Support "continue" for forks

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4536]
> We classify any turn as a `continue` when the road name doesn’t change. However, we can overwrite this classification with a different maneuver type (e.g. `fork`) later in the pipeline.

I believe this means it is impossible to have an instruction that is both a `continue` and a `fork`, which means clients cannot implement instructions like "Keep left at the fork **to stay on** Main St".

Is this something we can support?

**Comment by SiarheiFedartsou** [comment]
Stale.
