### ISSUE TITLE
Enable osrm-routed to talk https

### ISSUE THREAD

**Issue by mvl22** [Project-OSRM/osrm-backend#4537]
Running this from say port 5000 talks HTTP, but it would be useful to have an option to enable HTTPS instead, to avoid cross-origin issues when directly loading from a map on an HTTPS site.

A flag like `--https` would be useful.

**Comment by daniel-j-h** [comment]
`osrm-routed` really is a development server and should not be used for production or anything that needs TLS. I recommend using [node-osrm](https://www.npmjs.com/package/osrm) for production setups or build a robust solution on top of `libosrm`.

**Comment by systemed** [comment]
Using Apache's mod_proxy and ProxyPass directive with osrm-routed is a long-standing solution and works fine with HTTPS (though @daniel-j-h is right, of course, osrm-routed is not exactly a battle-hardened webserver).

**Comment by danpat** [comment]
I'm going to close this as WONTFIX - if you need HTTPS support, you should run `osrm-routed` behind a reverse proxy (see https://github.com/Project-OSRM/osrm-backend/issues/4517#issuecomment-330359238 for an `nginx` recipe), or use the node bindings to build your own server with NodeJS.
