### ISSUE TITLE
use realistic speeds for trains and ferries, with appropriate rates

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#4543]
speeds on trains and ferries are typically set to 5 or 10 km/h, which is unrealistic, especially for trains. it's probably a remnant from the time where there was no way to specify speed and rate separately.

we should assign realistic speeds for routes, coupled with low rates, so they are only used when there are no other suitable way.

**Comment by daniel-j-h** [comment]
👍 I think the profiles in general do not make use of the speed / weight split a lot other than in the car profile for a few things. For example the bike profile probably wants high weights on bad surfaces, no?

Related to this ticket:
- https://github.com/Project-OSRM/osrm-backend/issues/3849 use `ferry=*` tag
- https://github.com/Project-OSRM/osrm-backend/issues/1405 data from relation
- https://github.com/Project-OSRM/osrm-backend/issues/494 care to have a look here @emiltin and check if still actionable
