### ISSUE TITLE
Lane information along whole route

### ISSUE THREAD

**Issue by tttmaksko** [Project-OSRM/osrm-backend#4548]
Is it possible to gather all available lane information along route (not only on turns)? Such as count of lanes.

**Comment by daniel-j-h** [comment]
We only process and store lane information on a per-intersection basis. You can get lanes for intersections along the route between steps via the intersections array in the response:

http://project-osrm.org/docs/v5.10.0/api/#general-options

You can use the annotations feature to get OSM node ids for all segments and then query OSM for arbitrary tags in a separate annotation step:

https://github.com/mapbox/route-annotator
