### ISSUE TITLE
Routing past destination

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4550]
Seeing very odd routes on this road with the Mapbox traffic stack only:

https://www.mapbox.com/get-directions/#15.35/37.7904/-122.4503?coordinates=-122.452313,37.79106;-122.453375,37.790845

The recommended route drives _past_ my destination and then doubles back.

**Comment by MoKob** [comment]
Does this behaviour only show up when driving? I cannot reproduce it with the provided link.

**Comment by miccolis** [comment]
Oh interesting, something is up with speed updates. I could easily reproduce this yesterday after @willwhite opened this ticket. Maybe we should dig up the dataset from that time.

**Comment by MoKob** [comment]
![screen shot 2017-09-28 at 14 52 48 2](https://user-images.githubusercontent.com/12932279/30967498-c32826f4-a45c-11e7-9b14-55fa882cf196.png)
Might be I am missing something. All I see is the shown behaviour. Any screenshot of the undesired behaviour could help.

**Comment by oxidase** [comment]
@miccolis do you remember time  and how the weired route looked?

**Comment by miccolis** [comment]
Yes, I mean when will posted it `Sept 27, 2017, 11:34 AM EDT` if was certainly happening. We should still have the usca dataset that produced this problem on S3. @oxidase if you could look it would be great, this was very worrying behavior.

**Comment by oxidase** [comment]
@miccolis the issues is reproducible with s3://mapbox-eu-west-1/directions-traffic/directions-processing-5-12-0-production/osm-car-traffic-usca/1506526338784/
![screenshot from 2017-10-02 11-56-12](https://user-images.githubusercontent.com/4421046/31072988-663f96f0-a76a-11e7-8883-07356a4c0018.png)

But what i found there is a regression in MLD alternatives:
```
curl -s 'localhost:5000/route/v1/driving/-122.454852,37.790617;-122.455153,37.790544?alternatives=true' | jq ".routes[].weight"
194.6
curl -s 'localhost:5000/route/v1/driving/-122.454852,37.790617;-122.455153,37.790544' | jq ".routes[].weight"
3.1
```

If the original request contains `alternatives=true` parameter it can be a reason for incorrect behavior.

**Comment by oxidase** [comment]
with #4563 fixed i can reproduce the issue with dataset s3://mapbox-eu-west-1/directions-traffic/directions-processing-5-12-0-production/osm-car-traffic-usca/1506526083597/
![screenshot from 2017-10-02 15-24-51](https://user-images.githubusercontent.com/4421046/31079509-2ed359ec-a786-11e7-9fa2-59f34ce24c57.png)

**Comment by oxidase** [comment]
@miccolis  #4563 fixes a potential issue with MLD alternatives. As discussed `get-directions` uses alternatives, but what confuses me is a question why the problem is not 100% reproducible. I would suggest to close the issue and later reopen or open a new one with OSRM query parameters and timestamps  if the problem will reappear.
