### ISSUE TITLE
Inconsistance between method name and type of return value

### ISSUE THREAD

**Issue by tttmaksko** [Project-OSRM/osrm-backend#4554]
Return type of methods
```
    virtual std::vector<EdgeWeight> GetUncompressedForwardDurations(const EdgeID id) const = 0;
    virtual std::vector<EdgeWeight> GetUncompressedReverseDurations(const EdgeID id) const = 0;
```
of `class BaseDataFacade` doesn't correspont to the methods names.
`EdgeDuration` shoud be  used instead of EdgeWeight

See
* \osrm-backend\include\engine\datafacade\datafacade_base.hpp
* \osrm-backend\include\engine\datafacade\contiguous_internalmem_datafacade.hpp

**Comment by oxidase** [comment]
Related #3696
