### ISSUE TITLE
Speed limits in the Netherlands are scaled by 0.8

### ISSUE THREAD

**Issue by stavskal** [Project-OSRM/osrm-backend#4557]
After creating an OSRM extract using the car profile I noticed that the speed at many roads of the Netherlands is scaled by 0.8. For instance in roads that are motorway_link I would expect 130 but instead get 104. Same goes for roads that I expected to be 80 but instead we receive 64. If I check on OpenStreetMaps the values are correct there.

What could be going wrong?

**Comment by MoKob** [comment]
@stavskal this is an explicit choice in the profiles. You can change that behaviour [here](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L35). OSRM does not utilise the full speed, as often the full-speed does not represent the average speed on a road, due to traffic.

**Comment by stavskal** [comment]
@MoKob Does OSRM expose in any way the OSM speed limits unmodified? If so, how?
