### ISSUE TITLE
Running planet instance with 128GB of RAM

### ISSUE THREAD

**Issue by joseflorido** [Project-OSRM/osrm-backend#4573]
Hi!

I am trying to prepare data from the planet.osm dump on a machine with 128GB of RAM using the latest version of the node bindings. I keep getting:
```
terminate called after throwing an instance of 'tbb::captured_exception'
  what():  std::bad_alloc
Aborted
```
After a few minutes of osrm-extract execution.
I imagine it needs more ram to prepare data, if that is the case, is there a way to prepare data using less RAM (even if it's slower)?
Also, do you think 128gb is enough to run a production OSRM planet server?

Thanks!
Jose

**Comment by danpat** [comment]
@joseflorido For *routing*, you will only need about 40GB, but the `osrm-extract` step will require much more.

There are three typical ways to deal with this:

  1. Rent a very large server temporarily to do the processing, then move the datafiles onto a smaller machine for routing.
  2. Split the file into smaller regions (north america, africa/europe/asia) - this will half the processing requirements, but there is no way to stitch the files back together - you would need to create a reverse proxy that knows how to perform routing on different datasets.
  3. Enable a swap partition on your box - this is *very* not-recommended, it's about 100x slower, it could take weeks to finish processing the planet.

**Comment by joseflorido** [comment]
Thanks!
Firing a large VPS right now :)
