### ISSUE TITLE
Route via ice road eventhough tagged access:conditional = no @ may-oct

### ISSUE THREAD

**Issue by Perkiefect** [Project-OSRM/osrm-backend#4575]
Hi,
A route between 68.37983, 22.81959 and 68.43927, 22.46283 suggests a route via Kuttainen ice road. This road is tagged access:conditional = no @ may-oct in OSM: http://www.openstreetmap.org/edit#map=16/68.3854/22.8278
Does OSRM/Mapbox directions ignore the tag access:conditonal or what may be the reason why it suggests the ice road?

Cheers /Pelle@hitta.se

**Comment by daniel-j-h** [comment]
Yep conditional access tags are currently not handled but on our backlog, see https://github.com/Project-OSRM/osrm-backend/issues/4231.

Closing as duplicate.
