### ISSUE TITLE
Sharp left instead of u-turn

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4578]
This u-turn is miscategorized as a sharp left:

https://www.mapbox.com/get-directions/#18.61/37.30249/-121.8423?coordinates=-121.842297,37.302489;-121.84245246887191,37.30243119255495

**Comment by oxidase** [comment]
It is a data issue but the problem arises at [`MergableRoadDetector::HaveSameDirection`](https://github.com/Project-OSRM/osrm-backend/blob/d23a5fcfc4b2cb6cd899d2e4e09ff31d6416ccf6/src/extractor/guidance/mergable_road_detector.cpp#L351)
with 
```
p distance_between_roads
$55 = 14.144935386977751
(gdb) p combined_road_width + MAXIMAL_ALLOWED_SEPARATION_WIDTH
$56 = 11.25
```
where `combined_road_width` is 3.25 meters because one lane is assumed and roads will not be merged.

Adding `"lanes"="3"` tag https://www.mapillary.com/app/?lat=37.30271827433006&lng=-121.84278653014621&z=17&pKey=irIyBcCw4CsVPUfGXz3O8w&focus=photo&x=0.5146899738283921&y=0.6629990919076538&zoom=0 on both roads will fix the issue
```
p combined_road_width
$60 = 9.75
p combined_road_width + MAXIMAL_ALLOWED_SEPARATION_WIDTH
$62 = 17.75
(gdb) p distance_between_roads <= combined_road_width + MAXIMAL_ALLOWED_SEPARATION_WIDTH
$63 = true
```
and the instruction will be "Make a U-turn onto Senter Road"
![screenshot from 2017-10-06 15-37-22](https://user-images.githubusercontent.com/4421046/31280422-9942f278-aaac-11e7-86ea-38ad33500bd9.png)

**Comment by miccolis** [comment]
Oh, very interesting. @oxidase thanks for digging in here, very useful. I've got a two questions;

* I'm not sure that adding lane data to every place this sort of transition exists is realistic. Are there situations we've seen where we'd want to issue a 'sharp left' for a geometry like this? ...or should we adjust our math?
* I'm afraid to suggest this, but should we examine the road names and one-way tags in a situation like this? (I'm thinking the answer is no)

**Comment by oxidase** [comment]
@miccolis adjusting maths would mean changing some hardcoded parameters, but this could lead to more issues, also  'sharp left' instructions could be possible for one-lane roads with 14 meters distance, but i have no examples.

Heuristics about roads merging is in [`CanMergeRoad`](https://github.com/Project-OSRM/osrm-backend/blob/d23a5fcfc4b2cb6cd899d2e4e09ff31d6416ccf6/src/extractor/guidance/mergable_road_detector.cpp#L63-L103)  method where the first check [`EdgeDataSupportsMerge`](https://github.com/Project-OSRM/osrm-backend/blob/d23a5fcfc4b2cb6cd899d2e4e09ff31d6416ccf6/src/extractor/guidance/mergable_road_detector.cpp#L130-L152) considers directions and names.

**Comment by miccolis** [comment]
I did some looking at turning diameters (not radius, not sure why but car spec sheets use diameter) to see how our threshold of 11.25 meters compares:

* [Honda Civic](https://www.caranddriver.com/honda/civic/specs) "Turning Diameter - Curb to Curb : ft,  35.7" (10.88 meters)
* [BMW x3](https://www.caranddriver.com/bmw/x3/specs) "Turning Diameter - Curb to Curb : ft,  39" (11.89 meters)

Now, I'm not sure if we can compare these numbers directly; our figure is probably a centerline one, the spec sheets have curb to curb. Still, what I'm seeing is that a turn of 11.25 meters is close to the limit of what small car can do, and probably impossible for a medium to large size vehicle.

I'm gonna look a bit more closely about the heuristics and the order they are applied and the test cases we have. I'm sure there is a reason for the preset order things are evaluated in and I want to understand it a bit better.

**Comment by Andygol** [comment]
I specified number of lanes for the above ☝️ mentioned place -
 https://www.openstreetmap.org/changeset/54596051

**Comment by oxidase** [comment]
Fixed in master  http://map.project-osrm.org/?z=18&center=37.303858%2C-121.844081&loc=37.302366%2C-121.842166&loc=37.302277%2C-121.842268&hl=en&alt=0 by
