### ISSUE TITLE
Forward and backward classes in a single step

### ISSUE THREAD

**Issue by Boskovits** [Project-OSRM/osrm-backend#4579]
Running the following query:
localhost:5000/match/v1/truck/19.855664,47.72727;19.857225,47.728672?steps=true
with a profile where a forward and a backward class is added, and the names are the osm ids of the segments gives after filtering with jq .matchings[0].legs[0].steps[0]
the following results:
```
{
  "intersections": [
    {
      "classes": [
        "backward"
      ],
      "location": [
        19.855664,
        47.72727
      ],
      "bearings": [
        36
      ],
      "entry": [
        true
      ],
      "out": 0
    },
    {
      "classes": [
        "forward"
      ],
      "out": 0,
      "location": [
        19.856632,
        47.728166
      ],
      "bearings": [
        30,
        45,
        210
      ],
      "entry": [
        false,
        true,
        false
      ],
      "in": 2
    }
  ],
  "geometry": "mvhbH{`exBiAoAiBqBcBwB",
  "mode": "driving",
  "duration": 10.4,
  "maneuver": {
    "bearing_after": 36,
    "location": [
      19.855664,
      47.72727
    ],
    "bearing_before": 0,
    "type": "depart"
  },
  "ref": "3",
  "weight": 10.4,
  "distance": 194.9,
  "name": "195817621"
}
```
My problem with that there are intersections tagged with forward and ones with backward, however there is no u-turn.

Am I misinterpreting this result, or is this really wrong?

I expected that in a single step there should be only forward  or only backward classes on the same segment.

**Comment by SiarheiFedartsou** [comment]
Stale.
