### ISSUE TITLE
Network Status: 503. Is OSRM down?

### ISSUE THREAD

**Issue by Asterrea** [Project-OSRM/osrm-backend#4581]
I was trying  to visit `http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false` from the examples of OSRM HTTP and its returning a 503 base from network stats. 
Similarly, there seems to be no routing event happening at the demo site.

I tried using Linux terminal and it showed this error in detail:
`HTTPError: HTTP Error 503: Service Unavailable: Back-end server is at capacity`

Is OSRM currently down? Thanks!

**Comment by daniel-j-h** [comment]
Yep router backend is currently down: https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

You can use https://github.com/mapbox/get-directions instead.

You also could
- Set up your own routing engine locally, see https://github.com/Project-OSRM/osrm-backend#open-source-routing-machine and https://github.com/Project-OSRM/osrm-backend/wiki
- Use a hosted provider such as Mapbox (disclaimer: devs are with Mapbox)

I'm closing this already as not actionable on our side.

**Comment by Asterrea** [comment]
Ok! Thanks for the update and all the links! @daniel-j-h

**Comment by Asterrea** [comment]
Oh and will this be permanent already?

**Comment by daniel-j-h** [comment]
Yeah the demo server will probably down for a long time and we're thinking about just pointing the URLs to a Mapbox-powered endpoint.

**Comment by Asterrea** [comment]
@daniel-j-h I'm having quite a hard time getting a work around on the mapbox rate limit. I'm trying to use a timeout but it still ends up with the 429: Too many requests error. This never happened to me in OSRM before and I'm just recalibrating the same set of data that I had OSRM to fix before. Are setting timeouts in mapbox not enough? 

Sorry if I'm asking here, I kind of need a quick response from someone who knows the loop around :(

**Comment by miccolis** [comment]
@Asterrea that's a limit on the Mapbox side that can be changed. You'll need to reach out to their support however. Sorry you're running into this.
