### ISSUE TITLE
Hash Annotation Data

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#4585]
Many road segments in OSM offer the same meta data from the viewpoint of OSRM, since we do not store all data entries that are possible in OSM and require a way to be split.

With https://github.com/Project-OSRM/osrm-backend/pull/4556 we introduced a meta-data store for all edge-based nodes / node-based edges. This store is currently populated based on OSM ways. The moment a way is split into multiple segments, we end up storing the same meta-data multiple times, increasing memory usage.

For example https://www.openstreetmap.org/way/231285502, https://www.openstreetmap.org/way/320630988, and https://www.openstreetmap.org/way/320630989 offer the same annotation.

We can reduce our annotation memory footprint by ensuring that we store unique sets of annotations only once.

**Comment by TheMarex** [comment]
Implemented by #4585, saved about 1% total memory consumption of `osrm-routed`.
