### ISSUE TITLE
Driving-side aware sliproads handler

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#4587]
At the moment we detect sliproads for both right and left turns:

* turn is detected via a sliproad road
![screenshot from 2017-10-09 17-09-12](https://user-images.githubusercontent.com/4421046/31346704-3e8015da-ad1a-11e7-8c26-8a6ee725e895.png)

* two turn is detected without a sliproad detected
![screenshot from 2017-10-09 17-09-55](https://user-images.githubusercontent.com/4421046/31346691-364295d2-ad1a-11e7-960a-8da329462c01.png)

After #4415 it is possible to consider `is_left_hand_driving` flag to filter out left-turn sliproads in right-side-driving countries and vice versa

/cc @MoKob

**Comment by miccolis** [comment]
Not sure I follow why the second scenario would be preferred. What am I missing?

**Comment by oxidase** [comment]
Closed as non-actionable
