### ISSUE TITLE
CH returns wrong U-Turn 

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#4589]
Running comparison of random queries for CH vs MLD shows an example where CH returns an incorrect U-turn  if both source and target are on the same edge
![ch](https://user-images.githubusercontent.com/4421046/31401564-955b624a-adf3-11e7-895d-9e1d8e5822e3.png)

There is no problem in MLD
![mld](https://user-images.githubusercontent.com/4421046/31401586-a5942c00-adf3-11e7-9df7-7e5ea2881340.png)

also there is no problem after re-running `osrm-contract` 
http://map.project-osrm.org/?z=14&center=52.451563%2C13.214579&loc=52.453637%2C13.215447&loc=52.454975%2C13.217716&hl=en&alt=0

**Comment by MoKob** [comment]
@oxidase could this be the same as in https://github.com/Project-OSRM/osrm-backend/issues/3359? Our unpacking routines fail if source/target are the same segment.

**Comment by miccolis** [comment]
Should be fixed now that #3359 is resolved
