### ISSUE TITLE
Getting way ids from OSRM on a particular route

### ISSUE THREAD

**Issue by shravan91** [Project-OSRM/osrm-backend#4591]
Is there a way to get way ids instead of node ids from a particular route? 

For example
> I want to get all the way ids of the route from Karlsruhe to Mannheim when routing through A5.

**Comment by daniel-j-h** [comment]
Not in the OSRM response, but what you can do is use the annotations feature to get OSM node id pairs.

Then query OpenStreetMap and do lookups from node ids `(s,t)` to way ids.

Either build an index with (py)osmium or look into

https://github.com/mapbox/route-annotator

Closing as not actionable on our side; good luck!

**Comment by shravan91** [comment]
Thanks @daniel-j-h 👍
