### ISSUE TITLE
Routing and reverse direction

### ISSUE THREAD

**Issue by MouadSb** [Project-OSRM/osrm-backend#4599]
Hello,

I'm currently trying to use OSRM with leaflet to draw a route between multiple coordinates ( using Route service ) everthing is ok, but as you know, the gps sometimes sends wrong coordinates.

e.g : A vehicle moving from **point 1** to **point 3** and send three points the first coordinate in direction one, the second one in the reverse direction, and the third coordinate in the same direction as the first point, Is OSRM able to identify the wrong coordinate ( in this case the coordinate number 2 ) ?

![image](https://user-images.githubusercontent.com/22788332/31494534-9bcd4d42-af4b-11e7-9661-6628b53882a5.png)

The coordinate number 2 must be deleted or corrected, there is any service on OSRM that can handle this particular case?

( the desired result )

![image](https://user-images.githubusercontent.com/22788332/31494988-8fc51848-af4d-11e7-93c8-8687350f89f9.png)

**Comment by daniel-j-h** [comment]
Try the map-matching service

> Match - Snaps noisy GPS traces to the road network in the most plausible way

If you use the route service the route _has to go_ through the waypoints you send.

**Comment by MouadSb** [comment]
with the map-matching service i got this 

![image](https://user-images.githubusercontent.com/22788332/31500193-b1dc9274-af5e-11e7-9a0b-3f228c25dc50.png)

**Comment by danpat** [comment]
@MouadSb Screenshots are not enough detail for us to really help here.

What API call are you using with the map-matching API to generate the above result?

**Comment by MouadSb** [comment]
Thanks for replay
I've install the OSRM-backend on my server and use it with leaflet to display a route that links the points, i've a gps data on my database server and there are erroneous coordinates in these data because of the signal satelitte, what I am trying to do is detecting those erroneous coordinates and project them on the right highway, like the example on the ScreenShots
Firstly i've used the service route :  /route/v1/{profile}/{coordinates}?alternatives={true|false}&steps={true|false}&geometries={polyline|polyline6|geojson}&overview={full|simplified|false}&annotations={true|false} and like daniel said " the route service the route has to go through the waypoints you send. "
i've got the same result when i've tried with the service match : 
/match/v1/{profile}/{coordinates}?steps={true|false}&geometries={polyline|polyline6|geojson}&overview={simplified|full|false}&annotations={true|false}

**Comment by danpat** [comment]
@MouadSb Please paste the exact request you made, and the response you got.

**Comment by MouadSb** [comment]
The request : http://217.182.138.60:5001/route/v1/driving/-7.6324029,33.5874736;-7.634779,33.58955?overview=false&alternatives=true&steps=true
and the response : 
`{
    "code": "Ok",
    "routes": [
        {
            "legs": [
                {
                    "steps": [
                        {
                            "intersections": [
                                {
                                    "out": 0,
                                    "entry": [
                                        true
                                    ],
                                    "bearings": [
                                        136
                                    ],
                                    "location": [
                                        -7.632401,
                                        33.587476
                                    ]
                                },
                                {
                                    "out": 1,
                                    "location": [
                                        -7.632192,
                                        33.587294
                                    ],
                                    "bearings": [
                                        45,
                                        135,
                                        315
                                    ],
                                    "entry": [
                                        true,
                                        true,
                                        false
                                    ],
                                    "in": 2
                                }
                            ],
                            "geometry": "w`_lEnuqm@d@i@JM`@m@",
                            "mode": "walking",
                            "duration": 47.7,
                            "maneuver": {
                                "bearing_after": 136,
                                "location": [
                                    -7.632401,
                                    33.587476
                                ],
                                "bearing_before": 0,
                                "type": "depart"
                            },
                            "weight": 47.7,
                            "distance": 66.2,
                            "name": "Boulevard Mohamed Zerktouni"
                        },
                        {
                            "intersections": [
                                {
                                    "out": 2,
                                    "location": [
                                        -7.63189,
                                        33.587061
                                    ],
                                    "bearings": [
                                        120,
                                        195,
                                        255,
                                        315
                                    ],
                                    "entry": [
                                        true,
                                        true,
                                        true,
                                        false
                                    ],
                                    "in": 3
                                },
                                {
                                    "out": 3,
                                    "location": [
                                        -7.63212,
                                        33.587023
                                    ],
                                    "bearings": [
                                        75,
                                        135,
                                        270,
                                        315
                                    ],
                                    "entry": [
                                        false,
                                        true,
                                        true,
                                        true
                                    ],
                                    "in": 0
                                },
                                {
                                    "out": 2,
                                    "location": [
                                        -7.632913,
                                        33.58773
                                    ],
                                    "bearings": [
                                        135,
                                        225,
                                        315
                                    ],
                                    "entry": [
                                        false,
                                        true,
                                        true
                                    ],
                                    "in": 0
                                },
                                {
                                    "out": 2,
                                    "location": [
                                        -7.63336,
                                        33.588173
                                    ],
                                    "bearings": [
                                        135,
                                        225,
                                        315
                                    ],
                                    "entry": [
                                        false,
                                        true,
                                        true
                                    ],
                                    "in": 0
                                },
                                {
                                    "out": 2,
                                    "location": [
                                        -7.633721,
                                        33.588543
                                    ],
                                    "bearings": [
                                        135,
                                        225,
                                        315
                                    ],
                                    "entry": [
                                        false,
                                        true,
                                        true
                                    ],
                                    "in": 0
                                },
                                {
                                    "out": 2,
                                    "location": [
                                        -7.634255,
                                        33.589083
                                    ],
                                    "bearings": [
                                        135,
                                        225,
                                        315
                                    ],
                                    "entry": [
                                        false,
                                        true,
                                        true
                                    ],
                                    "in": 0
                                },
                                {
                                    "out": 2,
                                    "location": [
                                        -7.634632,
                                        33.589474
                                    ],
                                    "bearings": [
                                        135,
                                        225,
                                        315
                                    ],
                                    "entry": [
                                        false,
                                        true,
                                        true
                                    ],
                                    "in": 0
                                }
                            ],
                            "geometry": "c~~kEhrqm@BTBVaBlBk@n@wAxAiAfAkBjBmAhAUT",
                            "mode": "walking",
                            "duration": 284.7,
                            "maneuver": {
                                "bearing_after": 258,
                                "type": "continue",
                                "modifier": "uturn",
                                "bearing_before": 130,
                                "location": [
                                    -7.63189,
                                    33.587061
                                ]
                            },
                            "weight": 284.7,
                            "distance": 395.5,
                            "name": "Boulevard Mohamed Zerktouni"
                        },
                        {
                            "intersections": [
                                {
                                    "in": 0,
                                    "entry": [
                                        true
                                    ],
                                    "bearings": [
                                        141
                                    ],
                                    "location": [
                                        -7.634735,
                                        33.58958
                                    ]
                                }
                            ],
                            "geometry": "{m_lEbdrm@",
                            "mode": "walking",
                            "duration": 0,
                            "maneuver": {
                                "bearing_after": 0,
                                "type": "arrive",
                                "modifier": "left",
                                "bearing_before": 321,
                                "location": [
                                    -7.634735,
                                    33.58958
                                ]
                            },
                            "weight": 0,
                            "distance": 0,
                            "name": "Boulevard Mohamed Zerktouni"
                        }
                    ],
                    "distance": 461.7,
                    "duration": 332.4,
                    "summary": "Boulevard Mohamed Zerktouni, Boulevard al Massira al Khadra",
                    "weight": 332.4
                }
            ],
            "distance": 461.7,
            "duration": 332.4,
            "weight_name": "duration",
            "weight": 332.4
        }
    ],
    "waypoints": [
        {
            "hint": "uNIGgPRTB4AZAAAAygAAABIBAAAAAAAAGQAAAMoAAAASAQAAAAAAAAEAAADviYv_FIEAAu2Ji_8SgQACAgCPCLUSlG4=",
            "name": "Boulevard Mohamed Zerktouni",
            "location": [
                -7.632401,
                33.587476
            ]
        },
        {
            "hint": "FtIGgBvTBoBtAAAATgIAAAAAAAAAAAAAbQAAAE4CAAAAAAAAAAAAAAEAAADRgIv_TIkAAqWAi_8uiQACAAAPFLUSlG4=",
            "name": "Boulevard Mohamed Zerktouni",
            "location": [
                -7.634735,
                33.58958
            ]
        }
    ]
}`

for the match service : http://217.182.138.60:5001/match/v1/driving/-7.632948,33.588097;-7.633409,33.588168;-7.635254,33.590411?overview=full

the result : 
`{
    "code": "Ok",
    "matchings": [
        {
            "confidence": 0,
            "geometry": "wd_lE`yqm@JL|@aA^c@PSh@o@JM`@m@BTBVaBlBk@n@wAxACBeAbAkBjBmAhAgCbCcAbA_AhACKEIIGjBkB",
            "legs": [
                {
                    "steps": [],
                    "distance": 359.7,
                    "duration": 258.8,
                    "summary": "",
                    "weight": 258.8
                },
                {
                    "steps": [],
                    "distance": 474.7,
                    "duration": 341.9,
                    "summary": "",
                    "weight": 341.9
                }
            ],
            "distance": 834.4,
            "duration": 600.7,
            "weight_name": "duration",
            "weight": 600.7
        }
    ],
    "tracepoints": [
        {
            "alternatives_count": 0,
            "waypoint_index": 0,
            "location": [
                -7.632972,
                33.588118
            ],
            "name": "Rue Sebou",
            "hint": "ZTUAgN3RBgBGAwAAQQAAAAAAAAAAAAAARgMAAEEAAAAAAAAAAAAAAAEAAAC0h4v_loMAAsyHi_-BgwACAAAvDrUSlG4=",
            "matchings_index": 0
        },
        {
            "alternatives_count": 1,
            "waypoint_index": 1,
            "location": [
                -7.633377,
                33.58819
            ],
            "name": "Boulevard Mohamed Zerktouni",
            "hint": "MLYHgEO2BwARAAAAbQEAAAAAAAAAAAAAEQAAAG0BAAAAAAAAAAAAAAEAAAAfhov_3oMAAv-Fi__IgwACAAAPFLUSlG4=",
            "matchings_index": 0
        },
        {
            "alternatives_count": 5,
            "waypoint_index": 2,
            "location": [
                -7.635314,
                33.59037
            ],
            "name": "Boulevard Mohamed Zerktouni",
            "hint": "y9EGANzdEIAXAAAALgIAAAAAAAAAAAAAFwAAAC4CAAAAAAAAAAAAAAEAAACOfov_YowAAsp-i_-LjAACAAAPFLUSlG4=",
            "matchings_index": 0
        }
    ]
}`

**Comment by danpat** [comment]
@MouadSb I can see two problems:

  1. the one-way road doesn't seem to be honoured here - your route goes backwards, which should not be possible.  Did you modify `car.lua`, or use non-OSM map data here?  If your data isn't OSM, you're missing the one-way tags on these roads.

  2. if you add `&radiuses=30;30;30` to your `/match` request, it will do what you expect - your points are too far from the correct road to work properly with the default search radius.

**Comment by MouadSb** [comment]
Thank you for your response , i use a OSM map data and yes the radiuses option helped me for the issue.
