### ISSUE TITLE
Time-dependent routing with OSRM

### ISSUE THREAD

**Issue by xydinesh** [Project-OSRM/osrm-backend#4607]
Do you have any recommendations on how to incorporate historical traffic patterns into distance/time table calculation. For example, time to travel from point A->B may be different based on the time of the day. 

I'm looking for something similar to "departure" option in HERE.

https://developer.here.com/documentation/routing/topics/resource-calculate-matrix.html

**Comment by daniel-j-h** [comment]
Please read https://github.com/Project-OSRM/osrm-backend/issues/4449 and see if it helps.

**Comment by daniel-j-h** [comment]
Closing as not actionable on our side.
