### ISSUE TITLE
Running osrm-contract without core factor prints deprecation warning

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#4615]
Running osrm-contract datset.osrm prints a deprecation warning about a core factor, even though no core factor is used.

Steps to reproduce: Extract any dataset and run e.g. `./osrm-contract "../data/berlin-latest.osrm"`:

Results in:
```
[info] RAM: peak bytes used: 261259264
[info] Input file: ../data/berlin-latest.osrm
[info] Threads: 4
[warn] Using core factor is deprecated and will be ignored. Falling back to CH.
```

/cc @karenzshea

**Comment by TheMarex** [comment]
Fixed by https://github.com/Project-OSRM/osrm-backend/commit/0cc4c4380ab6be219a225d8e0c4ca676276fd93e
