### ISSUE TITLE
Remove CoreCH algorithm support

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#4617]
Follow up ticket to https://github.com/Project-OSRM/osrm-backend/pull/4601 - now that we have deprecated CoreCH by removing any support for core_factors other than 1.0 and adding deprecation notices for corech options, we can easily remove any mention of CoreCH in 6.0.

**Comment by SiarheiFedartsou** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/6920
