### ISSUE TITLE
posible error routing or osm error data

### ISSUE THREAD

**Issue by geopamplona** [Project-OSRM/osrm-backend#4628]
Hello, 

Im looking resolve this problema routing

http://map.project-osrm.org/?z=14&center=28.177955%2C-16.790199&loc=28.191969%2C-16.820626&loc=28.188206%2C-16.818995&hl=en&alt=0

![imagen](https://user-images.githubusercontent.com/25028240/31808007-981d3186-b571-11e7-9d40-509489c82297.png)

https://router.project-osrm.org/route/v1/driving/-16.820626,28.191969;-16.818995,28.188206?overview=false&alternatives=true&steps=true&hints=;

I think it looks like an OSM information problem.
but looking at the linestring of the roads with JOSM, but everything seems correct.
is it possible that it is a priority problem in the osrm profile? or osm information?
this happens in the municipality of playa san juan, province of Santa Cruz de Tenerife, spain ..

I really need to discard problems with osrm, and to know if I should edit osm, and how much the address is the problem.

my experience with osrm and osm is very poor
any help at least is welcome.

edit:
I try to make an alternative route that should be correct according to the shortest route, and still the problem persists.
http://map.project-osrm.org/?z=16&center=28.185785%2C-16.814296&loc=28.191818%2C-16.821270&loc=28.183667%2C-16.817847&hl=en&alt=0

![imagen](https://user-images.githubusercontent.com/25028240/31808338-fc1ac378-b572-11e7-94e0-b733abed59a8.png)

https://router.project-osrm.org/route/v1/driving/-16.821269989013672,28.191818101419507;-16.81784749031067,28.18366664611828?overview=false&alternatives=true&steps=true&hints=-pbXg_l7pYp1AAAAIAAAAHYAAACGAAAAdQAAACAAAAB2AAAAhgAAACviAACzU__-WSyuAepT__5KLK4BAgAfAScs_IU=;CpfXg____38zAAAASAAAAAAAAAAAAAAAMwAAAEgAAAAAAAAAAAAAACviAABDYf_-cAyuAUlh__5zDK4BAAD_FCcs_IU=

**Comment by emiltin** [comment]
the road was set to oneway (have since been changed)

**Comment by geopamplona** [comment]
how i can fix it?

**Comment by emiltin** [comment]
it's already fixed in the osm data. the demo server should soon catch up

**Comment by geopamplona** [comment]
thanks ! i will close issue
