### ISSUE TITLE
Route duration calculation is way off

### ISSUE THREAD

**Issue by MaartenDeen** [Project-OSRM/osrm-backend#463]
Previously, the speed calculation of OSRM was pretty good. Some days/weeks ago it changed to giving a mucht too long time. Compared with Google maps: google maps used to give a slightly longer time than reality, OSRM now gives a much longer time.

Doing some tests, it seems that the speed on motorways is set to 90 km/h. See http://map.project-osrm.org/1rj which gives a distance of 57 km and a time of 38 minutes. The maxspeed tag on the motorway is 120 or 130 km/h.
This imposes a 10 minute penalty on this distance.
Does OSRM take the maxspeed tags of ways into account?

I did a longer trip last weekend: http://map.project-osrm.org/1rk
OSRM shows 330 km and 3:55, Google said 3:24, in reality it was 3:15, with a speed never in excess of 120 km/h.

**Comment by dkakkar** [comment]
@MaartenDeen, @DennisOSRM  - How did you fix this issue? We are using OSRM http request to estimate travel time but that is coming significantly different from Google. OSRM is not using Highway speed on Highway as using city speed which is causing difference in time with Google. I am not sure how we can resolve, could either of you please help. Thanks!

**Comment by danpat** [comment]
@dkakkar Google uses measured real-world traffic data to improve road speed estimates.  OSRM doesn't have that by default.

There are mechanisms to feed speed data into OSRM, see https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

but you will still need a source of such data.  They are not common.
