### ISSUE TITLE
Routingerror with motorcar destination

### ISSUE THREAD

**Issue by dooley** [Project-OSRM/osrm-backend#4631]
As suggested by Daniel Hofmann on osrm-talk mailinglist i open a ticket here:

> I wonder why OSRM 5.11 / 5.12 with car profile does not use highways tagged with
> 
> motor_vehicle     destination
> motorcar     destination
> motorcycle     destination
> 
> for routing start or end like this highway:
> 
> https://www.openstreetmap.org/way/24181646
> 
> You'll see OSRM is not using it: https://www.openstreetmap.org/directions?engine=osrm_car&route=51.7546%2C7.4508%3B51.7440%2C7.4679#map=15/51.7501/7.4657
> 
> Why is that? Bug in the profile?

**Comment by daniel-j-h** [comment]
Thanks for reporting here - this looks like a bug.

If you look at the debug map

http://map.project-osrm.org/debug/#15.14/51.7445/7.4713

you will see the road is not in the routing graph.

The unclassified highway tag should be fine, I guess it's related to the access tags.

**Comment by dooley** [comment]
I added unclassified to restricted_highway_whitelist - like oxidase did in changeset [https://github.com/Project-OSRM/osrm-backend/commit/6cab5e84375857f27f43a122e93dd5b5758a041b](url) - and the highways show up in the debug page and are routable.

**Comment by oxidase** [comment]
@dooley thanks for reporting! Closing here as the fix just landed in master
