### ISSUE TITLE
Left/right reversed

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4633]
OSRM mixes up `slight left` and `slight right` on these two routes:

- https://www.mapbox.com/get-directions/#16.32/39.8319/-104.74809?coordinates=-104.74727088141051,39.83339742772378;-104.7480855297552,39.83190034986842
- https://www.mapbox.com/get-directions/#16.32/39.83176/-104.7476?coordinates=-104.74727088141051,39.83339742772378;-104.74759522368315,39.83176163209268

**Comment by oxidase** [comment]
It is fixed in https://github.com/Project-OSRM/osrm-backend/pull/4443 by https://github.com/Project-OSRM/osrm-backend/tree/2532d56b856934c57c0a5f8cc68cc9ea0167ac1d  and will be visible after 5.13 release.

**Comment by miccolis** [comment]
Fixed!
