### ISSUE TITLE
relation in profile bicycle.lua

### ISSUE THREAD

**Issue by creatorness** [Project-OSRM/osrm-backend#4635]
Hello,

I wanted to try the release v5.13.0-rc.2 regarding the relation support.
I have also tested it with the car profile and see if it works.
Then I have added in the bicycle.lua the api_version to 3 and the parameter relations to the functions process_way,
but the variable relations is nil or empty.
Do I still have something to consider or is it still not working ?

**Comment by daniel-j-h** [comment]
cc @deniskoronchik

**Comment by SiarheiFedartsou** [comment]
Stale.
