### ISSUE TITLE
Map matching. Save not matched points

### ISSUE THREAD

**Issue by pavellp7** [Project-OSRM/osrm-backend#4638]
Hello!
In my case vehicle is tractor and it turns off the road in the field. In the result all `tracepoints` after turning are `null` and `match geometry (red)` ends at the turn.
Is there any option to save not matched points in the result? - that the result consisted of `matched points`, and then bad initial points in field.
![default](https://user-images.githubusercontent.com/32450695/32002293-d353d1ce-b9a4-11e7-99c9-396c77a3fe18.JPG)

**Comment by pavellp7** [comment]
Now I run on `tracepoints array` and find match coordinates on `matchings_index` and `waypoint_index` properties; when `tracepoint` is `null` I skip it.
But when `>5 tracepoints` in a row is `null`, I take appropriate initial coordinates - it looks +- fine, but is there a more elegant solution? 
![2017-10-26 11-35-29](https://user-images.githubusercontent.com/32450695/32043828-80f537a6-ba44-11e7-8131-0f60079f0177.png)

**Comment by wangzi6578** [comment]
hello,
i am new about it ,i want to know how could i show the matched points on map,when i matched the points,it just respond in terminal,thank you for your time

**Comment by SiarheiFedartsou** [comment]
Stale.
