### ISSUE TITLE
Error using the {nearest} service (even the example). Minimum number of coordinates is 2 (?) 

### ISSUE THREAD

**Issue by vhfdoliveira** [Project-OSRM/osrm-backend#4645]
Hi everybody. I ran across your project because the 'nearest' service does exactly what I want, which is to know the nearest road of a given coordinate.
In the documentation of this 'service' it's clear to me that it does what I described, it even says "Where coordinates only support a single {longitude},{latitude} entry."

But when I try the example in python, with the code below

`import requests`
`url = 'http://router.project-osrm.org/nearest/v1/driving/13.388860,52.517037?number=3&bearings=0,20'`
`response = requests.get(url)`

`print(response.text)`

it gives me the following error:

`{"message":"Not enough input coordinates given; minimum number of coordinates is 2.","code":"InvalidInput"}`

I also try simplest requisitions, but they all ended in the same error.

Can anyone help me?

Thanks a lot,
Victor Hugo.

**Comment by oxidase** [comment]
@vhfdoliveira atm router.project-osrm.org is in a transition state, so it is a problem at the proxy level /cc @danpat 

Local extract returns 3 points as expected:
```
curl -s 'http://localhost:5000/nearest/v1/driving/13.388860,52.517037?number=3&bearings=0,20' | jq .
{
  "waypoints": [
    {
      "nodes": [
        2264199819,
        0
      ],
      "location": [
        13.3888,
        52.517033
      ],
      "hint": "tUECAHNCAoAUAAAAIAAAAAcAAAAAAAAACgAAABAAAAAEAAAAAAAAALsAAAAATMwAqVghAzxMzACtWCEDAQDfCk9TUk0=",
      "name": "Friedrichstraße",
      "distance": 4.085341
    },
    {
      "nodes": [
        2045820592,
        0
      ],
      "location": [
        13.388782,
        52.517134
      ],
      "hint": "tUECAHNCAoAHAAAAAAAAAAAAAAA0AAAABAAAAAAAAAAAAAAAGgAAALsAAADuS8wADlkhAzxMzACtWCEDAADvCk9TUk0=",
      "name": "Friedrichstraße",
      "distance": 12.011369
    },
    {
      "nodes": [
        0,
        21487242
      ],
      "location": [
        13.388776,
        52.517171
      ],
      "hint": "tkECgMJBAgAAAAAAGwAAAAAAAAA8AAAAAAAAABsAAAAAAAAAPAAAALsAAADoS8wAM1khAzxMzACtWCEDAAAvFk9TUk0=",
      "name": "Friedrichstraße",
      "distance": 15.951904
    }
  ],
  "code": "Ok"
}
```

**Comment by danpat** [comment]
Yes, this is a problem with the `osrm-routed.js` parameter validation, which was deployed to the demoserver yesterday.

I'm working on a fix in this branch https://github.com/Project-OSRM/osrm-backend/pull/4604, and I'll deploy it once I figure out what's going wrong.

**Comment by vhfdoliveira** [comment]
Ok, thanks very much. I will wait for the fix.

**Comment by danpat** [comment]
I've found the problem, I'll try to get it deployed to the demoserver in the next few hours.  Of course, you can always run your own server, as @oxidase pointed out, the bug exists in how the demoserver is deployed, not OSRM itself.

**Comment by vhfdoliveira** [comment]
Actually, I'm running my own server and getting my work done. 

Thanks a lot.

**Comment by danpat** [comment]
Fix has been deployed to the demoserver, the requests listed above are now working as expected.
