### ISSUE TITLE
OSRM response to geojson

### ISSUE THREAD

**Issue by giorgim** [Project-OSRM/osrm-backend#4651]
Is it possible or are you aware of a library that would convert the response from OSRM, to geoJSON data? (so that I could draw that shape on the Leaflet map - leaflet is good at handling geoJSON data)

**Comment by danpat** [comment]
Check out:

  https://github.com/perliedman/leaflet-routing-machine

which supports drawing OSRM responses on a map.

Also, take a look at the `overview=full` and `geometries=geojson` request parameters - this will return a full  GeoJSON LineString object for the complete route.

These options are documented here: http://project-osrm.org/docs/v5.10.0/api/#requests
