### ISSUE TITLE
Access tag interpretation bug in car profile? (Routing over highway=path + access=permissive)

### ISSUE THREAD

**Issue by Nakaner** [Project-OSRM/osrm-backend#4658]
Hi,

a user of the Islands layer of OpenStreetMap Inspector complained about false positives ([example](https://www.openstreetmap.org/way/533974299). I investigated a bit and it seems that the car profile treats `highway=path` + `access=permissive` as suitable for cars ([example](http://tools.geofabrik.de/osmi/?view=routing&lon=4.25695&lat=50.73793&zoom=18&overlays=duplicate_ways,islands,sinks_and_sources)). The Islands layer is generated using following steps:

```sh
osrm-extract planet.osm.pbf -p profiles/car.lua
osrm-components planet.osrm islands-sinks-sources.geojson
ogr2ogr -f SQlite islands-sinks-sources.sqlite islands-sinks-sources.geojson <some parameters to tune SQlite but I don't know them by heart>
```

The OSMI server runs an older version of OSRM (something around 2.8) but I can reproduce the issue with 5.13.0.

Is it intended that access tags overwrite the road type if the type indicates the unsuitability of the road? The edges in question are flagged at OSMI because OSRM treats them as suitable for cars but they are an isolated subnetwork because the way connecting them with the rest of the graph [is a footway](https://www.openstreetmap.org/way/387509869).

Best regards

Michael (from Geofabrik)

**Comment by TheMarex** [comment]
👋 @Nakaner 

This is a case of an ambiguous `access` tag. We interpret the `access` tag like the wiki right now still suggests, which means that `access=permissive` means its accessible for all modes of transportation. (`foot=permissive` would be the correct tagging as per wiki)

Personally I would like to see [default values](http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions) get approved, in which case we could interpret `access` to only apply to modes of transportation that are accessible by default.

**Comment by Nakaner** [comment]
> Personally I would like to see default values get approved […]

The wiki page is not a proposal. Does "approve" mean getting them approved by other OSRM maintainers or approved due to a discussion in OSM?

**Comment by SiarheiFedartsou** [comment]
Stale.
