### ISSUE TITLE
Which lane when making uturn as a pedestrian

### ISSUE THREAD

**Issue by martinprevas** [Project-OSRM/osrm-backend#4666]
Hi,

I am having some trouble identifying which lane a pedestrian must take when making a uturn. If its a trail in the forest, its easy but when the road has two lanes the pedestrian must cross the road and take the sidewalk on the opposite side of the road. Maybe the lanes are marked as one-way and despite using the foot profile the user must still adhere to this rule?

Best regards
Martin Bang Andersen

**Comment by SiarheiFedartsou** [comment]
Stale.
