### ISSUE TITLE
Collapse legs in map matching response

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#4669]
The `match` plugin currently returns a `RouteLeg` object for every pair of matched coordinates.

If you supply a fairly detailed GPS trace (e.g. coordinates every 25m), you end up with a `Route` object with lots of very very short `RouteLegs` - each usually having just a `depart` and a `arrive` `RouteStep`.

We could add a parameter to the `match` plugin, like `waypoints=0,24` that indicates which of supplied coordinates are to be used as waypoints.  Currently, *all* coordinates are used as waypoints, leading to all the legs.

If a trace is split and waypoints are supplied, we should return an error that no route can be found.

**Comment by TheMarex** [comment]
We would need to change how we construct the `InternalRouteResult` objects [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/plugins/match.cpp#L221).

The easiest implementation just merges the legs after the fact.

**Comment by ericrwolfe** [comment]
> The easiest implementation just merges the legs after the fact.

If we had a generalized solution to merge legs, that might also help implement "via" points.

**Comment by coxchapman** [comment]
>If you supply a fairly detailed GPS trace (e.g. coordinates every 25m),

When do we do this? What's the urgency or need here?

**Comment by coxchapman** [comment]
Capturing some context from chat: this would support refreshing ETAs along a routeline. We would use GPS to match you back to the routeline, and then provide a new ETA.

This could be helpful as part of a wider conversation on ETAs (projecting future traffic, live ETA updates, etc) but we need to focus on time-to-deploy and other tech metrics right now.

**Comment by danpat** [comment]
🤔 `waypoints=0,24` could also work for the `route` plugin - would enable some control of routes without emitting legs for every pair.

**Comment by TheMarex** [comment]
Some more context on why it would be beneficial to do this before generating the actual API object:

In guidance post-processing we collapse several instructions based on the context of the path. The simple example is a round-a-bout. Let's say you have a leg that ends in a roundabout, simply concatenating the instructions of the current and the next leg will give you different instructions and would potentially break the exit counting. The client would need to adjust these values after merging the legs.

**Comment by coxchapman** [comment]
@danpat @TheMarex have we made a decision on the right place and scope to do this?

**Comment by karenzshea** [comment]
It could make sense to implement this right now behind a `waypoints=x,y` parameter, and then in 6.0 make the default behavior to treat the first and last matched coordinates as the waypoints, unless otherwise specified.

**Comment by karenzshea** [comment]
Implementation plan:

## Goal

Expose an option on the map matching plugin that can return multiple map matched coordinates as part of one RouteLeg object, depending on the indices of the input coordinates that the user specifies as coordinates to treat as `waypoints`.

## API changes

### HTTP/node
We'll implement a parameter on the map matching plugin to indicate the indices of input coordinates that should be treated as `waypoints` of the returned Route object.

- `waypoints` semicolon-delimited list of numbers corresponding to input coordinates. Default=all

Example:
localhost:5000/match/v1/car/13.406184911727905,52.520764737491305;13.411238193511963,52.52338900208765;13.414725065231323,52.52628726139225;13.415744304656982,52.526894304997;13.416967391967772,52.528304180352336.json?access_token=pk.eyJ1IjoiaGFwcHlnbyIsImEiOiJpejZNbjFzIn0.81qeT6sOKwqH5UCFNXwB4Q&steps=true&waypoints=0;4

## Implementation changes
1. After the map matching result has been returned by the map matching algorithm plugin, merge every `sub_match` into the same `InternalRouteResult` objects, delineated by the user provided `waypoints` indices. Will require a `MergeSubMatch` function or so.
2. Add a new parameter to the map matching plugin, `waypoints`. Store as a std::vector<std::size_t> like sources/destinations in table plugin are parsed. Will require changes to
- include/engine/api/match_parameters.hpp
  - new `waypoints` member on parameters class
  - add a check on the `IsValid()` call
- src/engine/plugins/match.cpp
  - check that waypoints indices correspond to a coordinate
  - use indices to create new `InternalRouteResult` objects while creating response object

**Comment by coxchapman** [comment]
@karenzshea this looks great. Small design question -- can we make the `waypoints` parameter default to `none`? I realize there may be greater implications to the question (ie, what happens if the request lacks a `waypoints` parameter) but I think the desired default behavior is that a typical match request results in a single route.

**Comment by TheMarex** [comment]
@coxchapman for the moment we can't change the default behavior, as that would be a breaking API change. We could reconsider this for the next iteration of the API.

**Comment by coxchapman** [comment]
Ah, got it. Sounds good -- it should be enough to make it available in the near term.

**Comment by karenzshea** [comment]
Just wanted to point out that I suggested making this the default as well in https://github.com/Project-OSRM/osrm-backend/issues/4669#issuecomment-345748408 and clarify that the desired default here sounds like `&waypoints={first_index};{last_index}` not `none`, as it wouldn't really make sense in any context, for none of the input coordinates to be treated as waypoints.
