### ISSUE TITLE
bicycle navigation based on routes

### ISSUE THREAD

**Issue by MichalPP** [Project-OSRM/osrm-backend#4672]
there are several cases with ways of `vehicle=no` (not `motor_vehicle=no`), which are a part of `route=bicycle`. what to do in this case? allow or disallow routing over this way?

the OSM data is correct, IRL there are traffic sign disallowing bicycles and signs showing that it's a bike route on the same pole. but the traffic sign is not enforced by police.

with the new relations support, it would be easy to override access tags.

@emiltin , your opinion?

**Comment by emiltin** [comment]
hmm that's tricky. generally i would probably give priority to tags on ways, but vehicle=no sounds like disallowing bicycles was unintended.

**Comment by MichalPP** [comment]
that's the problem in countries where bicycles are not a priority.
there is one segment of Eurovelo in Bratislava which is officially vehicle=no. it was probably unintentional, but the traffic sign is there. as a bonus, it's a bridge so any route around is very long.

should I create a handler that will override way access tags based on route? it will work also for hiking routes.

**Comment by emiltin** [comment]
As previously mentioned I would give priority to tags on way (over being part of a route), since ways are more local and specific.

Thus I would block bicycles if a way have vehicle=no, even if it's part of a bicycle route. The problem is wrong tagging, and should be fixed by changing the way tag to motor_vehicle=no, or adding bicycle=yes.

**Comment by MichalPP** [comment]
the problem is that the tagging is correct (sometimes). there is traffic sign 
![image](https://user-images.githubusercontent.com/3583700/32653604-b3b40fb2-c608-11e7-8b86-dea254ec5b6e.png) so the tagging should be `vehicle=no`(?), but it's a part of bicycle route (approved by police).

**Comment by emiltin** [comment]
this is legal problem and osrm cannot solve it.  i think the best we can do is to respect vehicle=no

**Comment by MichalPP** [comment]
I believe it's about deciding which of the "on the ground truths" is "the truth". is it thousands of cyclists using that way or some traffic sign (which is neither respected nor enforced)?

**Comment by emiltin** [comment]
for a municipalitty like us, we cannot suggest that people ignore road signs. that would be asking people to break traffic laws.
