### ISSUE TITLE
How many request per second OSRM/Backend docker can handle?

### ISSUE THREAD

**Issue by fmr683** [Project-OSRM/osrm-backend#4677]
Is there a limit, that following API can handle request per second, if I hosted in our own server?

http://127.0.0.1:5000/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true

I did exactly what has mentioned in the https://hub.docker.com/r/osrm/osrm-backend/ link to run the OSRM docker instruction.  (Note I'm not using front-end)

Everything seems working fine, even If I execute the following API (note here the source limit is 3)
http://127.0.0.1:5000/table/v1/driving/79.865184,6.856469;79.867051,6.858589;79.862052,6.860068;79.863039,6.862401?sources=1;2;3&destinations=0

I'm getting response in 44ms.

However, if I increase the **sources** information in above API like for 50 and send 1000 request per second, I'm getting 7 to 8 second response time and the CPU usage goes for 60-70 usage.

Here is my server and OSRM file size info:
map.osrm file size: 1.6GB
16 Core CPU
24GB Ram
ulimit -n 1024

I tried Nginx load balancing also as follows briefly:

docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed --algorithm mld /data/map.osrm
 docker run -t -i -p 5001:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed --algorithm mld /data/map.osrm

and accessed the API as:

http://127.0.0.1/table/v1/driving/79.865184,6.856469;79.867051,6.858589;79.862052,6.860068;79.863039,6.862401?sources=1;2;3&destinations=0

nginx.conf brief setup as follows:

```
worker_processes auto;

events {
        worker_connections 2048;
         multi_accept on;
}

 upstream myapp1 {
                server 127.0.0.1:5000 weight=1;
                server 127.0.0.1:5001 weight=2;

        }

        server {
                listen 192.168.180.93:80;

                location / {
                        proxy_pass http://myapp1;
                }
        }
```

Now my question is how can I make/keep it the response time very low  (below 100ms) even if I increase it to 50 or more?

**Comment by krypt-n** [comment]
One approach could be to run osrm with the contraction hierarchy preprocessing. See the comparison graphs here: https://github.com/Project-OSRM/osrm-backend/pull/4547

**Comment by oxidase** [comment]
@fmr683 44ms is pretty fair result for MLD matrix computation. 7-8 seconds can be a queue waiting time part as one worker can handle only 15-20 requests per second.

**Comment by danpat** [comment]
@fmr683 I'll try to summarize:

  1. Use CH (`osrm-extract` + `osrm-contract`) instead of MLD - queries will be faster.
  2. You may need to force the `--threads` parameter to `osrm-routed` - normally OSRM tries to detect the CPU count, but that may go a bit wonky inside a docker container.

In general, the `osrm-routed` server is pretty performant, and can saturate your CPU capacity with a single running instance.
