### ISSUE TITLE
Error : ConnectFailure

### ISSUE THREAD

**Issue by Pirlog** [Project-OSRM/osrm-backend#4683]
Hello everybody, I'm actually working on a C# project using OSRM via http request:
I used to this code for my requests :

            HttpWebRequest request;
            /*url = https://router.project-osrm.org/route/v1/driving/2.102301,48.783317;2.041223,48.797461;2.043520,48.775459;2.043737,48.775063;2.044357,48.775072;2.045424,48.775038;2.048896,48.774519?steps=false&alternatives=false&geometries=polyline6&overview=full*/
            request = (HttpWebRequest)HttpWebRequest.Create(url);
            HttpWebResponse myHttpWebResponse = null;
            request.Accept = null;
            try {
                myHttpWebResponse = (HttpWebResponse)request.GetResponse();
            }
            catch (WebException e)
            {
                Debug.Log(e);
                yield break;
            }
            var stream = myHttpWebResponse.GetResponseStream();
            var reader = new StreamReader(stream);
            html = reader.ReadToEnd();
            while (reader.ReadToEnd() != "")
            {
                yield return new WaitForSeconds(1.0f);
            }
            responseText = html;
            // Release resources of response object
            myHttpWebResponse.Close();

But for some time now, this code don't work anymore.
I don't know if somebody can help me, awareness news about http response of OSRM.
When I put the URL in my browser, it works. But in this code it doesn't work.
The error I get is the following : 

System.Net.WebException: Error: ConnectFailure (Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
) ---> System.Net.Sockets.SocketException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
 at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP, Boolean requireSocketPolicy) [0x00000] in <filename unknown>:0 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at NavigationBase+<routingRequest>c__Iterator0.MoveNext () [0x000cc] in C:\Users\Public\Documents\SVN\[A-IVI]\Assets\Scripts\Applications\Navigation\NavigationBase.cs:52 

Thanks in advance for your understanding.
Best regards !

**Comment by danpat** [comment]
@Pirlog I suggest there is a problem somewhere in your system or network (a firewall perhaps?)

Requests to https://router.project-osrm.org/route/v1/driving/ are currently working fine, and the system has multiple servers behind it, in several geographic locations.

Check that you can access the `router.project-osrm.org` address from your web browser (try testing http://map.project-osrm.org/ and make a route).

I don't think there is anything that we can do to fix this problem.

**Comment by Pirlog** [comment]
Hello,

Thanks you for your answer !
Best regards,

Pierre-Louis Gournay

Le 14 nov. 2017 17:28, "Daniel Patterson" <notifications@github.com> a
écrit :
