### ISSUE TITLE
Memory requirement for RunTime

### ISSUE THREAD

**Issue by jbfondo** [Project-OSRM/osrm-backend#4688]
I have 2 servers with 64 GB RAM. Both are running osrm-backend with whole planet. 
One of them is running osrm-backend v5.2.0 (from about 15 moths ago). Memory consumption on this machine es about 44 GB.
Recently I set up the second server with docker image tagged with v5.12.0 and I noticed the higher memory consumption, up to 140 GB. It's using 64 GB RAM and about 74 GB swap.

What is the reason for this increased memory consumption? (very large increase, I think)
Am I doing something wrong? What can I do to lower this comsumption?
Thanks.

**Comment by jbfondo** [comment]
Both of them are using car profile.

**Comment by daniel-j-h** [comment]
For the car profile and running on the planet, requirements are definitely higher than what you posted; see: https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements

Be aware of the differences between pre-processing and runtime.

Also you really don't want to hit swap, ever. It will be terribly slow.

**Comment by oxidase** [comment]
If the above numbers are for preprocessing than potentially RAM memory consumption increased by disabling STXXL in a default configuration. It makes `280 GB of STXXL disk space` unnecessary, but `osrm-extract` will use a swap disk instead of an STXXL disk file if RAM memory is not enough.

**Comment by jbfondo** [comment]
I passed the pre-processing stage (osrm-extract and osrm-contract)... yes, it takes a lot of time to do all the process (a bit more than 1 motnh) and it swapped a lot, but it's done now. 
I'm running now osrm-routed and I noticed the difference between the 2 versions in the amount of memory needed. It's the scenario that I described in first post.

**Comment by jbfondo** [comment]
The question is that the requirements for Runtime are 64 GB RAM but when I try to run the docker v5.12.0 with whole planet, the memory consumption is about 140 GB. It uses swap file to be able to run. Any idea?

**Comment by SiarheiFedartsou** [comment]
Stale.
