### ISSUE TITLE
InvalidUrl with polyline

### ISSUE THREAD

**Issue by thiefjim** [Project-OSRM/osrm-backend#4690]
Hi I am using osrm-backend in docker.
The following request 
`http://localhost:5000/route/v1/car/polyline(iviwFlukbMn\umD)?steps=true`
get response is
```
StatusCodeError: 400 - "{\"message\":\"URL string malformed close to position 34: \\\"bMn\\/um\\\"\",\"code\":\"InvalidUrl\"}" 
```
I think the polyline encode cause "invalidUrl".
The lat,lon pair is [ 40.68725, -73.95687 ], [ 40.68253, -73.92892 ]

I have tried offical api
`http://router.project-osrm.org/route/v1/driving/polyline(iviwFlukbMn\umD)?steps=true`
```
{
    "message": "Not Found"
}
```

Also, I have tried routing on website(osrm-frontend). By input  40.68725, -73.95687 at start and 40.68253, -73.92892 at end. It can be solved.
![image](https://user-images.githubusercontent.com/4970547/32893841-e3466146-cb15-11e7-9bc5-cad74fb554e9.png)

**Comment by oxidase** [comment]
@thiefjim polyline `iviwFlukbMn\umD` is decoded by `decodePolyline` to `{{-73.95687, 40.68725}, {-73.92892, 40.68253}}`.

You have to use `%5C` instead of a backslash 
```
curl -s 'http://localhost:5000/route/v1/car/polyline(iviwFlukbMn%5CumD)?steps=true' | jq ".code, .routes[].duration"
"Ok"
354.3
```

@danpat  is there a polylines support in proxy?
```
curl 'http://router.project-osrm.org/route/v1/driving/polyline(iviwFlukbMn\umD)?steps=true'
{"message":"Not enough input coordinates given; minimum number of coordinates is 2.","code":"InvalidInput"}
```

**Comment by thiefjim** [comment]
@oxidase 
I will try to use [Query String](https://nodejs.org/api/querystring.html).
Thanks for the response.

**Comment by oxidase** [comment]
Fixed at `router.project-osrm.org` proxy
```
 curl -s 'http://router.project-osrm.org/route/v1/driving/polyline(iviwFlukbMn\umD)' | jq .code
"Ok"
```
