### ISSUE TITLE
contrasting behaviour map-matching: dc9b4bc e327632

### ISSUE THREAD

**Issue by lindowman** [Project-OSRM/osrm-backend#4694]
Hello,
When using git version dc9b4bc  and version e327632, there is a major slow-down for large map-matching requests.
e.g. using 40000 point-pairs (lat + long) with version e327632 is a lot faster than version dc9b4bc.
for larger number of point-pairs the client never receives the response. The response is calculated and the log shows a 200 OK, but the client never receives the response and eventually times out.  It seems to be stuck waiting on the socket descriptor to become available.
I only mention these two releases because I think it's where the change in behaviour occurs. Things seem to be fine for large map-matching requests before and including e327632.
Please let me know if there is any further detail I can provide.

System Details:
Using Ubuntu GLIBC 2.23-0ubuntu9
Ubuntu 16.04.3 LTS

**Comment by wangzi6578** [comment]
hello,
     i got a problem that when i use more than 200 point-pairs it will respond an error:TooBig", "Too many trace coordinates. and i dont know how to fix it

**Comment by lindowman** [comment]
wangzi658
please start the routing engine using the --max-matching-size=X where X > 200
Thank you

**Comment by wangzi6578** [comment]
thank you for your respond, should i input that in terminal? it will back an error"too many positional options have been specified on the command line",can you tell some detail,thank you  again

**Comment by wangzi6578** [comment]
thank you for your respond ,it woorks!!!!! thank you

**Comment by wangzi6578** [comment]
when i using 4000 points-pairs it shows an error : bash: /usr/local/bin/curl: argument list too long,i just use the way documents says,is there something wrong?

**Comment by lindowman** [comment]
wangzi: shows an error : bash: /usr/local/bin/curl: argument list too long ...
This isn't osrm related. I suggest looking at using a config file with curl. Please check this link https://ec.haxx.se/ . Hope that helps.

**Comment by wangzi6578** [comment]
ok,i'm gonna to learn it,i'm new here, maybe i have too many question,there is the last one,how could i draw the trace in the demo map.

**Comment by lindowman** [comment]
Some further input about the original problem off different behaviour in map-matching. The request with large point-pairs has timestamps spread over a few days. I believe the change introduced in git version dc9b4bc, causes several recalculations in the mapMatching() function, lengthening the overall running time. If the request is treated without timestamps the response from the routing engine gets back to the client. Infact, if both the client and server are located on the same host the response gets back to the client with or without timestamps.
What I would like to understand is if there is a way to change the profile e.g. maximum matching speed or some other config, so that timestamps can still be sent in the request?
Also, is there way to figure out what the "threshold timeout" is,   beyond which the response never gets sent back to a remote -not located on the same host as the- client?

**Comment by danpat** [comment]
> Infact, if both the client and server are located on the same host the response gets back to the client with or without timestamps.

This is suspicious.  It hints at some kind of network limitation.  Certainly, with 40000 coordinates, you have a very long URL and might be hitting a network/server  limit somewhere.  Can you dig more into this part?  A few thoughts:

  1. Is there CPU usage on the server while the client is hanging?  If the algorithm is busy, I would expect to see 1 CPU at 100% doing calculations until the response is returned.
  2. Can you use a packet tracker (like `tcpdump`) to examine whether the request and/or response is actually happening?  Do this on both the server and client machines.

`osrm-routed` has no limit for URL length.

**Comment by lindowman** [comment]
Thank you for your response danpat.
I don't think the URL length is cause for problem. I have tried a request with approx. 120K coordinates and there is a response. Prior to dc9b4bc  the client received always received the server response - no matter the relative location of the client/server.
It seems that the data I have, being spread over a few days, causes the clean() method of the HMM model to be invoked. The subsequent recalculations/reallocations prolong the overall processing. The response is calculated. The async_write is invoked in but the associated write handler  is never invoked. Yet no data gets back to the client. Connection between server and client is still extant. Log file shows the 200 ok response along with the original request message.
CPU usage is 100% while the response is being calculated. It drops as soon as the network transfer is initiated.
I don't have the tcpdump, but here is an abbreviated strace from the server. It shows the sendmsg where some part of the response is sent. But the descriptor never receives a 'wake-up' after the buffer. I see the client is still connected.
This is on one thread:
munmap(0x7f12442af000, 5967872)         = 0
sendmsg(15, {msg_name(0)=NULL, msg_iov(31)=[{"HTTP/1.0 200 OK\r\n", 17}, {"Connection", 10}, {": ", 2}, {"close", 5}, {"\r\n", 2}, {"Access-Control-Allow-Origin", 27}, {": ", 2}, {"*", 1}, {"\r\n", 2}, {"Access-Control-Allow-Methods", 28}, {": ", 2}, {"GET", 3}, {"\r\n", 2}, {"Access-Control-Allow-Headers", 28}, {": ", 2}, {"X-Requested-With, Content-Type", 30}, {"\r\n", 2}, {"Content-Type", 12}, {": ", 2}, {"application/json; charset=UTF-8", 31}, {"\r\n", 2}, {"Content-Disposition", 19}, {": ", 2}, {"inline; filename=\"response.json\"", 32}, {"\r\n", 2}, {"Content-Length", 14}, {": ", 2}, {"6923433", 7}, {"\r\n", 2}, {"\r\n", 2}, {"{\"code\":\"Ok\",\"matchings\":[{\"conf"..., 65242}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 65536
sendmsg(15, {msg_name(0)=NULL, msg_iov(1)=[{"\",\"weight\":0}],\"distance\":0,\"dur"..., 65536}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 42504
sendmsg(15, {msg_name(0)=NULL, msg_iov(1)=[{",\"distance\":0,\"duration\":0,\"summ"..., 65536}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(12, EPOLL_CTL_MOD, 15, {EPOLLIN|EPOLLPRI|EPOLLOUT|EPOLLERR|EPOLLHUP|EPOLLET, {u32=939526336, u64=139716225665216}}) = 0
futex(0x55ac4a792d5c, FUTEX_WAIT_PRIVATE, 731, NULL

Then some time later the connection is closed by the server. I can confirm that there is no one connected to the server. Although the client doesn't receive this close - the client is still hung waiting for the response.

This is on another thread - this is the thread receiving the incoming request.
futex(0x55ac4a792d5c, FUTEX_WAIT_PRIVATE, 729, NULL) = 0
futex(0x55ac4a792d30, FUTEX_WAKE_PRIVATE, 1) = 0
epoll_wait(12, [{EPOLLIN|EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=939526336, u64=139716225665216}}], 128, -1) = 1
futex(0x55ac4a792d5c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x55ac4a792d58, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
sendmsg(15, {msg_name(0)=NULL, msg_iov(1)=[{",\"distance\":0,\"duration\":0,\"summ"..., 65536}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ETIMEDOUT (Connection timed out)
munmap(0x7f12376e0000, 9568256)         = 0
munmap(0x7f1244860000, 7868416)         = 0
epoll_ctl(12, EPOLL_CTL_DEL, 15, 0x7f12465835f0) = 0
close(15)                               = 0
futex(0x55ac4a792d5c, FUTEX_WAIT_PRIVATE, 733, NULL

Originally when I was working through the problem I used one thread. So this is the first time I see that the close() is issued on another thread. Is it usual to have the response sent back on 2 different threads - The 200 OK goes back on one thread and the thread doing the close() also is sending some part of the response back.

**Comment by lindowman** [comment]
An update after running tcpdump.
Request packets received by the server and the servers response are in the tcp trace. There is no close in the tcp trace (tcp-fin) flag. The server doesn't send one out. The client doesn't receive any.
For one of my tests:
The last request packet was received at 11:53:24 by the server. This was acknowledge by the server
The osrm computed response was sent out at 13:27:44 according to the tcp trace. But the client side trace doesn't show any incoming packets. The server retries the response 16 times. Still there is no tcp-fin packet in the tcp trace. Throughout this time the server shows the connection as being established as does the client. After the server side connection is dropped, the client still shows the connection as being established.
So the response is computed but it just doesn't go back to the client. Should I be adjusting some system network parameters?

**Comment by lindowman** [comment]
closed without prejudice
