### ISSUE TITLE
tagless ways missing

### ISSUE THREAD

**Issue by MichalPP** [Project-OSRM/osrm-backend#4697]
some highways do not have any tags, but the multipolygon relation they are in, has tags. currently these tagless ways are removed from processing (but when I any tag, they are included). 

with the awesome relation support, I've created myself a function that inherits some tag from relation to way
```
function get_from_rel(relations, way, key, value, ret)
    -- if any of way's relation have key=value, return tag ret; else return NULL
    local rel_id_list = relations:get_relations(way)
    for i, rel_id in ipairs(rel_id_list) do
        local rel = relations:relation(rel_id);
        local p = rel:get_value_by_key(key);
        if value == '*' and p then return rel:get_value_by_key(ret); end
        if p == value then return rel:get_value_by_key(ret); end
    end
    return nil;
end
```

then call `if not data.highway or data.highway == '' then data.highway = get_from_rel(relations, way, "highway", '*', "highway"); end`

what would be a proper way to include it so that it adds highway tags to tagless ways? (it works on ways that have any tag).

**Comment by emiltin** [comment]
isn't this a case of bad mapping? do you have an example way you can link to?

**Comment by MichalPP** [comment]
[this](http://www.openstreetmap.org/relation/2940615) is probably the best case (or [this](http://www.openstreetmap.org/way/4418701) or [this](http://www.openstreetmap.org/way/23920493) one.) 

[wiki](https://wiki.openstreetmap.org/wiki/Key:highway) says that highway tag should work on relations.

**Comment by MichalPP** [comment]
a solution could be to include those tagless ways, that are members of interesting relations (those defined by `relation_types` )

**Comment by emiltin** [comment]
I see, you're referring to areas/squares defined by relations of ways. Adding tags will of course only enable routing along the edge of the square, which doesn't really provide an good user experience.  See #64 for a discussion of routing across squares.

**Comment by SiarheiFedartsou** [comment]
Stale.
