### ISSUE TITLE
mapmatching interpolate corners (gmaps style)

### ISSUE THREAD

**Issue by vihoth** [Project-OSRM/osrm-backend#4700]
Hey guys,

I think it would be neat if the mapmatching alogrithm would spit out points that follow the roads around corners and tunnels. Right now it cuts corners if there are not enough points available. Google maps already does this (see interpolate): https://developers.google.com/maps/documentation/roads/snap

Best, Achim

**Comment by TheMarex** [comment]
@vihoth try using `gaps=ignore`  with `overview=full` and use `.matchings[0].geometry`
