### ISSUE TITLE
osrm-example util exception

### ISSUE THREAD

**Issue by kkyiss** [Project-OSRM/osrm-backend#4702]
Hello
I've read the OSRM api document, and wanted to try the libosrm instead of HTTP interface.
It led me to the example directory. After I successfully build the example.cpp, and got a osrm-example.exe
Also with  /test/data/monaco.osrm ready (generated from /test/data/makefile too)

I run 

> osrm-backend-5.13.0/example/build$ ./osrm-example ../../test/data/monaco.osrm

and got:

> terminate called after throwing an instance of 'osrm::util::exception'
>    what( ):  Required files are missing, cannot continue. Have all the pre-processing steps been run?
>    Abosrted (core dumped)

Am i doing something wrong?
thanks for any reply

**Comment by daniel-j-h** [comment]
- check if you ran all pre-processing documented [here](https://github.com/Project-OSRM/osrm-backend#quick-start)
- if you ran MLD pre-processing you have to set the algorithm to MLD in the engine config [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/engine_config.hpp#L66-L67)

**Comment by kkyiss** [comment]
Thanks @daniel-j-h for the quick reply!
And it works perfectly :)

**Comment by daniel-j-h** [comment]
Great - happy routing! ✨ 🚗

**Comment by meizhuwang** [comment]
I'm having the same issue, only difference is that I have done all the per-processing by following the docker commands exactly in https://hub.docker.com/r/osrm/osrm-backend/ and copied all the created files into the same build folder that includes osrm-example. Can someone tell me exactly how to prepare the files? Many thanks!

**Comment by Mohammadabd** [comment]
I’m having same issue even after running all the preprocessing steps. I use MLD so I did extract-partition-custommize
