### ISSUE TITLE
adjust rate

### ISSUE THREAD

**Issue by buxinator** [Project-OSRM/osrm-backend#4711]
Hi,
I try to adjust rates for some ways in foot.lua, to use them preferred without setting speed higher. 
But actually I don't know where to do it. Please help

**Comment by oxidase** [comment]
@buxinator rates for `routability` weights are specified in [`WayHandlers.penalties`](https://github.com/Project-OSRM/osrm-backend/blob/6fd0b56e32bc0ec932d64dfb940022bbe4d85b5f/profiles/lib/way_handlers.lua#L379-L389), for `distance` in [`WayHandlers.weights`](https://github.com/Project-OSRM/osrm-backend/blob/6fd0b56e32bc0ec932d64dfb940022bbe4d85b5f/profiles/lib/way_handlers.lua#L480-L491), and for `duration` there is a fallback to speed values in c++ if rates are not set in a Lua profile. 

You can add a custom weight name and a way handler in [`handlers`](https://github.com/Project-OSRM/osrm-backend/blob/6fd0b56e32bc0ec932d64dfb940022bbe4d85b5f/profiles/foot.lua#L205-L245) that will set higher rates for preferred ways without modifying speed values.

**Comment by buxinator** [comment]
@oxidase can you help me with a bit of example code since i am not used to Lua scripting?

**Comment by oxidase** [comment]
@buxinator let specific road has id 524005927. You can add to `WayHandlers.weights`
```
   if profile.properties.weight_name == 'custom' then
      if (way:id() == 524005927) then
         if (result.forward_mode ~= mode.inaccessible and result.forward_speed > 0) then
            print ('Changing forward rate of way ' .. tostring(way:id()) .. ' from ' ..
                      tostring(result.forward_rate) .. ' to ' .. tostring(result.forward_speed * 5))
            result.forward_rate = result.forward_speed * 5
         end
         if (result.backward_mode ~= mode.inaccessible and result.backward_speed > 0) then
            print ('Changing backward rate of way ' .. tostring(way:id()) .. ' from ' ..
                      tostring(result.backward_rate) .. ' to ' .. tostring(result.backward_speed * 5))
            result.backward_rate = result.backward_speed * 5
         end
      end
   end
```
and change [`weight_name = 'duration'`](https://github.com/Project-OSRM/osrm-backend/blob/6fd0b56e32bc0ec932d64dfb940022bbe4d85b5f/profiles/foot.lua#L14) to `weight_name = 'custom'`
and you will see in `osrm-extract` output
```
Changing forward rate of way 524005927 from -1 to 25
Changing backward rate of way 524005927 from -1 to 25
```
Other ways will have "durations" weights.

**Comment by buxinator** [comment]
Thanks @oxidase !

Short Explanation what my goal is: 
I want to use railway ways preffered and it should route as fast as possible from starting point by foot to railway lines.


if profile.properties.weight_name == 'custom' then
    if (way:get_value_by_key('railway')) then.......


When I change weight_name='custom', routing only selects railway lines and nothing else.
When I use 'duration' instead of 'custom' in WayHandlers.weights the routing does not change at all. Do  you have any Idea why?

**Comment by oxidase** [comment]
@buxinator sorry, just forgot that rates must be specified for all ways if the weight name is not `duration`
Here is the correct handler with the `else` branch:
```
   if profile.properties.weight_name == 'custom' then
      if (way:id() == 524005927) then
         -- preferred ways
         if (result.forward_mode ~= mode.inaccessible and result.forward_speed > 0) then
            print ('Changing forward rate of way ' .. tostring(way:id()) .. ' from ' ..
                      tostring(result.forward_rate) .. ' to ' .. tostring(result.forward_speed * 5))
            result.forward_rate = result.forward_speed * 5
         end
         if (result.backward_mode ~= mode.inaccessible and result.backward_speed > 0) then
            print ('Changing backward rate of way ' .. tostring(way:id()) .. ' from ' ..
                      tostring(result.backward_rate) .. ' to ' .. tostring(result.backward_speed * 5))
            result.backward_rate = result.backward_speed * 5
         end
      else
         -- other ways
         result.forward_rate = result.forward_speed
         result.backward_rate = result.backward_speed
      end
   end
```

**Comment by daniel-j-h** [comment]
Stale.

**Comment by AveryPenningtonGSI** [comment]
It would be great to have a new example explaining the details of setting custom weights for each of the different modes of transport, explaining how to tune the route recalculation. It's quite easy to set weights high to eliminate a particular segment, but harder to understand how to tune the weight calculation to balance different priorities (especially with additional raster data used as input to weights.)
