### ISSUE TITLE
boost unit test cpp_main undefined reference error

### ISSUE THREAD

**Issue by eryalee** [Project-OSRM/osrm-backend#4714]
when i'm running make tests, undefined reference to cpp_main() link error show. After add an empty cpp_main() function in every unit_test/*_tests.cpp, no one case will run,  it appears that the main() function does not atomically generated correctly.
does anyone meet the problem before? thanks so much.
boost lib is static linked, version is 1.55.0

**Comment by daniel-j-h** [comment]
Could you test 1/ in a Docker container with Ubuntu 14/16 LTS so that we can reproduce and/or 2/ with dependencies from mason. Documentation how to run out both is [in the wiki](https://github.com/Project-OSRM/osrm-backend/wiki).

**Comment by daniel-j-h** [comment]
Stale. Feel free to re-open if you can reproduce this or provide us with a Dockerfile so that we can reproduce it.
