### ISSUE TITLE
Duration time shown on the local is different to the one shown on route.project-osrm

### ISSUE THREAD

**Issue by maheshnathwani** [Project-OSRM/osrm-backend#4715]
Hi,
There's a huge difference (almost 2x) in the duration times generated on the local server and the demo server for any Indian coordinate pair.
I'm running osrm v 5.14 on the local machine last updated from the repo on 1-12-17.
I've taken the map extract from `http://download.geofabrik.de/asia/india-latest.osm.pbf` on 1-12-17
I've run osrm in TLD mode. 

The problem is that there is a difference in the duration time shown on the demo server and the local host for the same route between any coordinates in India. I did check the previous similar issues where in it was pointed that the demo server uses traffic updates from mapbox but then there isn't any traffic data for India at mapbox.

Here's the snippet of the duration matrix from the table service

**Local Server** url: `localhost:5000/table/v1/driving/72.835746,19.218494;72.818561,19.215680;72.828822,19.232229;72.856684,19.229317`

Response: 
`{
    "code": "Ok",
    "durations": [
        [
            0,
            209.8,
            183.5,
            267.4
        ],
        [
            213.1,
            0,
            270.9,
            382
        ],
        [
            183.3,
            260.9,
            0,
            199.4
        ],
        [
            262.1,
            379.8,
            197.2,
            0
        ]
    ],
    "destinations": [
        {
            "hint": "LQNWgPJCCYAAAAAAZAAAAAAAAAAAAAAAAAAAAGQAAAAAAAAAAAAAADkCAAD_XVcESD8lAaJiVwQ-QCUBAADvEE9TUk0=",
            "name": "",
            "location": [
                72.834559,
                19.218248
            ]
        },
        {
            "hint": "QwlWgF0JVoADAQAAqAAAAEwAAAAAAAAAAwEAAKgAAABMAAAAAAAAADkCAAB1H1cExDUlAYEfVwRANSUBAQBfBU9TUk0=",
            "name": "",
            "location": [
                72.818549,
                19.215812
            ]
        },
        {
            "hint": "rEwJgBhjVoAXAAAAKQAAAAAAAAAAAAAAFwAAACkAAAAAAAAAAAAAADkCAACxR1cEgnYlAZZHVwTldSUBAAB_EU9TUk0=",
            "name": "Gorai Borivali Road; Lokmanya Tilak Road",
            "location": [
                72.828849,
                19.232386
            ]
        },
        {
            "hint": "8kYJgL9GCYAgAAAAFAAAACIAAAAAAAAAIAAAABQAAAAiAAAAAAAAADkCAACZslcEF2slAWy0VwSFaiUBAwAvAU9TUk0=",
            "name": "Swami Vivekanand Road",
            "location": [
                72.856217,
                19.229463
            ]
        }
    ],
    "sources": [
        {
            "hint": "LQNWgPJCCYAAAAAAZAAAAAAAAAAAAAAAAAAAAGQAAAAAAAAAAAAAADkCAAD_XVcESD8lAaJiVwQ-QCUBAADvEE9TUk0=",
            "name": "",
            "location": [
                72.834559,
                19.218248
            ]
        },
        {
            "hint": "QwlWgF0JVoADAQAAqAAAAEwAAAAAAAAAAwEAAKgAAABMAAAAAAAAADkCAAB1H1cExDUlAYEfVwRANSUBAQBfBU9TUk0=",
            "name": "",
            "location": [
                72.818549,
                19.215812
            ]
        },
        {
            "hint": "rEwJgBhjVoAXAAAAKQAAAAAAAAAAAAAAFwAAACkAAAAAAAAAAAAAADkCAACxR1cEgnYlAZZHVwTldSUBAAB_EU9TUk0=",
            "name": "Gorai Borivali Road; Lokmanya Tilak Road",
            "location": [
                72.828849,
                19.232386
            ]
        },
        {
            "hint": "8kYJgL9GCYAgAAAAFAAAACIAAAAAAAAAIAAAABQAAAAiAAAAAAAAADkCAACZslcEF2slAWy0VwSFaiUBAwAvAU9TUk0=",
            "name": "Swami Vivekanand Road",
            "location": [
                72.856217,
                19.229463
            ]
        }
    ]
}`

**Demo Server** url: 
`https://router.project-osrm.org/table/v1/driving/72.835746,19.218494;72.818561,19.215680;72.828822,19.232229;72.856684,19.229317`

Response:

`{
    "durations": [
        [
            0,
            462.8,
            405.8,
            825.5
        ],
        [
            472,
            0,
            626.2,
            1150.8
        ],
        [
            438.8,
            670.8,
            0,
            563.2
        ],
        [
            775,
            1067.7,
            565.9,
            0
        ]
    ],
    "destinations": [
        {
            "hint": "hYgkhoiIJIYAAAAAfwEAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAEbZAAD_XVcESD8lAaJiVwQ-QCUBAADvEF_CVUc=",
            "name": "",
            "location": [
                72.834559,
                19.218248
            ]
        },
        {
            "hint": "GiwhhjQsIYblAwAAhAIAACUBAAAAAAAA8gEAAEIBAACTAAAAAAAAAEbZAAB1H1cExDUlAYEfVwRANSUBAQBfBV_CVUc=",
            "name": "",
            "location": [
                72.818549,
                19.215812
            ]
        },
        {
            "hint": "9nnhgVNsJIZNAAAAigAAAAAAAAAAAAAATQAAAIoAAAAAAAAAAAAAAEbZAACxR1cEgnYlAZZHVwTldSUBAAB_EV_CVUc=",
            "name": "Gorai Borivali Road; Lokmanya Tilak Road",
            "location": [
                72.828849,
                19.232386
            ]
        },
        {
            "hint": "taBtgMSgbYD-AAAAhwAAAAYBAAAAAAAA_gAAAIcAAAAGAQAAAAAAAEbZAACZslcEF2slAWy0VwSFaiUBAwAvAV_CVUc=",
            "name": "Swami Vivekanand Road",
            "location": [
                72.856217,
                19.229463
            ]
        }
    ],
    "sources": [
        {
            "hint": "hYgkhoiIJIYAAAAAfwEAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAEbZAAD_XVcESD8lAaJiVwQ-QCUBAADvEF_CVUc=",
            "name": "",
            "location": [
                72.834559,
                19.218248
            ]
        },
        {
            "hint": "GiwhhjQsIYblAwAAhAIAACUBAAAAAAAA8gEAAEIBAACTAAAAAAAAAEbZAAB1H1cExDUlAYEfVwRANSUBAQBfBV_CVUc=",
            "name": "",
            "location": [
                72.818549,
                19.215812
            ]
        },
        {
            "hint": "9nnhgVNsJIZNAAAAigAAAAAAAAAAAAAATQAAAIoAAAAAAAAAAAAAAEbZAACxR1cEgnYlAZZHVwTldSUBAAB_EV_CVUc=",
            "name": "Gorai Borivali Road; Lokmanya Tilak Road",
            "location": [
                72.828849,
                19.232386
            ]
        },
        {
            "hint": "taBtgMSgbYD-AAAAhwAAAAYBAAAAAAAA_gAAAIcAAAAGAQAAAAAAAEbZAACZslcEF2slAWy0VwSFaiUBAwAvAV_CVUc=",
            "name": "Swami Vivekanand Road",
            "location": [
                72.856217,
                19.229463
            ]
        }
    ],
    "code": "Ok"
}`

**Comment by daniel-j-h** [comment]
From https://lists.openstreetmap.org/pipermail/osrm-talk/2017-October/001545.html

```
    1. We'll be switching from `osrm.routed`, to `osrm-routed.js` (
https://github.com/Project-OSRM/osrm-backend/pull/4604).  I've tried my
best to make it fully compatible, but, well, there are always bugs.
    2. The demoserver will only run stable releases, it will no longer run
from master.
    3. The dataset is a slightly modified car.lua, *plus* Mapbox's freeflow
traffic data over the top - this should give more accurate ETAs in areas
where Mapbox has traffic coverage than plain car.lua.
    4. Hints are disabled on the new setup - the hint= parameter is
accepted but ignored.  This is because we're cycling the dataset every few
hours behind the scenes, hints get invalidated quickly.
    5. The demoserver will have a service-wide rate limit of 5000
req/minute.  Looking at past logs, it stays below this about 98% of the
time, but be prepared for HTTP 429 responses, and be aware that heavy usage
may cause rate limiting for everyone else if you flood the server.
    6. Some error messages will change - this is mostly the result of the
switch from osrm-routed to osrm-routed.js and using a different URL parsing
library.
```

I will add a note to https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server.

HTH

**Comment by maheshnathwani** [comment]
@daniel-j-h  Is there any way to get the access of the car.lua used for the demo server?
Thanks

**Comment by daniel-j-h** [comment]
Not really - it's more or less the default `car.lua` with minor adaptions.
But the traffic data will make the primary difference here anyway.

**Comment by emiltin** [comment]
@maheshnathwani writes Mapbox has no traffic data for India?

**Comment by maheshnathwani** [comment]
@emiltin This page [https://www.mapbox.com/api-documentation/pages/traffic-countries.html](url) shows the countries in which mapbox provides traffic support.
@daniel-j-h can you please be more precise with the adaptations required in the car.lua file? Would  changes in the highway field do?

**Comment by Clever91** [comment]
@maheshnathwani , Are you found this problem ?

**Comment by kumaranshu72** [comment]
can you please share the car.lua being used on demo server?
