### ISSUE TITLE
Error message when using polyline

### ISSUE THREAD

**Issue by RLstat** [Project-OSRM/osrm-backend#4720]
Hi, 

I am trying the query example in the doc: http://project-osrm.org/docs/v5.5.1/api/#general-options

it seems when sending as polyline, for example:
Using polyline:
curl 'http://router.project-osrm.org/route/v1/driving/polyline(ofp_Ik_vpAilAyu@te@g`E)?overview=false'

it will return: 
{"message":"Not enough input coordinates given; minimum number of coordinates is 2.","code":"InvalidInput"}

I can only send as coordinate for now, for example the corresponding following would work:
Query on Berlin with three coordinates:
curl 'http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false'

it returns: 
{"routes":[{"legs":[{"summary":"","weight":422.6,"duration":326.6,"steps":[],"distance":1884.9},{"summary":"","weight":540.1,"duration":465.4,"steps":[],"distance":2947.3}],"weight_name":"routability","weight":962.7,"duration":792,"distance":4832.200000000001}],"waypoints":[{"hint":"rvcJgAbxRoYQAAAAGwAAAAYAAAAAAAAAEAAAABsAAAAGAAAAAAAAAM_ZAAAATMwAqVghAzxMzACtWCEDAQDfCvGSOH8=","name":"Friedrichstraße","location":[13.3888,52.517033]},{"hint":"JRsUgBB87YEKAAAACAAAABsBAAAAAAAACgAAAAgAAAAbAQAAAAAAAM_ZAAB_bswAGIkhA4JuzAD_iCEDAgCfEPGSOH8=","name":"Torstraße","location":[13.397631,52.529432]},{"hint":"2yQZgP___38dAAAA2AAAACIAAADcAAAAHQAAAGwAAAAiAAAAbwAAAM_ZAABK58wA53AhA0vnzADTcCEDAwC_EPGSOH8=","name":"Platz der Vereinten Nationen","location":[13.428554,52.523239]}],"code":"Ok"}

Aren't this two should give similar returned results?

Anyone else experiencing this? 

Thanks for help.

**Comment by oxidase** [comment]
@RLstat thanks for flagging the issue! The fix is on the way to be deployed.

Closing here as the issue duplicates #4690 and is related to the OSRM demo server proxy
