### ISSUE TITLE
crashes with invalid hints

### ISSUE THREAD

**Issue by datendelphin** [Project-OSRM/osrm-backend#4724]
I am experiencing crashes with osrm-routed when I try to run multiple instances (without osrm-datastore)

It looks a bit random. But there is always one graph which works, and the other ones crash upon the first request (with an assertion). It seems that it does not depend on the graph, as the calculation is working fine and I have exchanged them several times with fresh ones (from an updated planet). All three profiles worked at some point. Memory is sufficient to run at least two, with a bit swap all three.

I am using v5.14.1
The profiles can be found here: https://github.com/datendelphin/cbf-routing-profiles

I attached a few sample backtraces. It usually works like this: I start one profile, test it, and it works (sometimes multiple starts required). Once it works it does not seem to crash at all, calculating happily different routes. But once I switch back to another profile and request the same route from that profile, osrm-routed crashes, and only the last one I started survives. And that one will still happily calculate routes.

[bike_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535795/bike_backtrace.txt)
[bike2_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535796/bike2_backtrace.txt)
[bike3_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535797/bike3_backtrace.txt)
[bike4_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535798/bike4_backtrace.txt)
[car_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535799/car_backtrace.txt)
[car2_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535800/car2_backtrace.txt)
[car3_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535801/car3_backtrace.txt)
[car4_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535802/car4_backtrace.txt)
[foot_backtrace.txt](https://github.com/Project-OSRM/osrm-backend/files/1535803/foot_backtrace.txt)

**Comment by datendelphin** [comment]
I'm now pretty convinced it is related to running the exact same query on a different profile. If I run a different one, it seems to work. As soon as I run an identical one, it crashes.

**Comment by oxidase** [comment]
@datendelphin in stack traces queries have hints that can be used only on the same dataset that generates hints. Please could try tests without `&hints=` query parameters?

**Comment by datendelphin** [comment]
indeed, I can confirm that it does not crash when I remove the hint parameter. The deduction I make from this is not nice.

**Comment by danpat** [comment]
`hint` values are tightly coupled to the dataset that was in use when they were created - they're simply a serialization of some internal OSRM data.

If you swap to a new dataset, the `hint` value is no longer correct and shouldn't be used.

I'd suggest only using hints when you really need the performance boost they supply for repeat queries, *and* you're not changing datasets without invalidating the hints.

The OSRM demoserver ignores hints for this reason - we're updating the dataset every few hours, so hints become invalid very quickly.

**Comment by datendelphin** [comment]
Yes, sure. It is a bug in my interface. But it is also a possibility for a DOS attack. So how do I disable it?

**Comment by daniel-j-h** [comment]
Couple of options I can think of here:
- run a proxy in front of your servers and rewrite urls dropping the hints query parameter, or
- in the [base grammar](https://github.com/Project-OSRM/osrm-backend/blob/994fae0ef6f08eb2c184d6d1ffe158fa3332da69/include/server/api/base_parameters_grammar.hpp#L78-L88) stop passing through parsed hints, or
- in the [plugins](https://github.com/Project-OSRM/osrm-backend/blob/994fae0ef6f08eb2c184d6d1ffe158fa3332da69/include/engine/plugins/plugin_base.hpp#L29) stop using hints

the last two options require you to change code and compile from source. Also you should add `generate_hints=false` to your queries to stop returning hints for requests.

**Comment by emiltin** [comment]
if you're using osrm-routed, you could also use the nodejs server instead, and not pass hints to the osrm lib.

**Comment by datendelphin** [comment]
thank you. I disabled hints in the base grammar, and that prevents the crashes successfully.

**Comment by SiarheiFedartsou** [comment]
https://github.com/Project-OSRM/osrm-backend/issues/4741
