### ISSUE TITLE
Incorrect weight values for duplicated edge-based nodes.

### ISSUE THREAD

**Issue by vng** [Project-OSRM/osrm-backend#4731]
Seems like it's a bug here:
https://github.com/Project-OSRM/osrm-backend/blob/2e97c78181d294fe9d1d358df323457e6189ecbf/src/extractor/edge_based_graph_factory.cpp#L378

Push back weight to EBN-indexed weight's vector by getting the value from the same vector using NBE-index. This indices are different according to nbe_to_ebn_mapping vector in EdgeBasedGraphFactory.

Why not to do simple:
```
m_edge_based_node_weights.push_back(edge_data.weight);
```
?

**Comment by oxidase** [comment]
@vng good catch!
