### ISSUE TITLE
osrm-routed.exe has stopped working

### ISSUE THREAD

**Issue by ariuandrea** [Project-OSRM/osrm-backend#4734]
Hi all,

I get the following error when trying to prepare the map:
"osrm-routed.exe has stopped working"
I am running the program on STATA14.2 in a server. Any advice? 

Thank you

Andrea

**Comment by daniel-j-h** [comment]
We need more output and / or debug messages to help here.

You may be running out of memory..

**Comment by ariuandrea** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	osrm-routed.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5696e649
  Fault Module Name:	MSVCP140.dll
  Fault Module Version:	6.3.9600.18821
  Fault Module Timestamp:	59ba86db
  Exception Code:	c0000135
  Exception Offset:	00000000000ece70
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	1033
  Additional Information 1:	ac05
  Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional Information 3:	ac05
  Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by daniel-j-h** [comment]
@ariuandrea sorry but without debug logs why osrm-routed crashed we can't help much.

**Comment by oxidase** [comment]
@ariuandrea binaries at http://build.project-osrm.org/latest/osrm_Release.zip compiled with a DLL-specific version of run-time libraries, eg,  MSVCP140.dll:
```
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\dumpbin.exe" /DEPENDENTS osrm-routed.exe
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file osrm-routed.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    ADVAPI32.dll
    MSVCP140.dll
    WS2_32.dll
    MSWSOCK.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
```

Error c0000135 says that MSVCP140.dll is missing in OS, so the easiest "fix" is installing runtime DLLs from https://www.microsoft.com/en-us/download/details.aspx?id=48145
(SO link https://stackoverflow.com/questions/39904402/c-windows-service-and-msvcp140-dll)

On other side, building with a static version of run-time libraries requires recompiling OSRM and dependencies https://github.com/mapbox/windows-builds/blob/master/scripts/build_osrm_deps.bat with `/MT` flag

**Comment by daniel-j-h** [comment]
Stale.
