### ISSUE TITLE
host multiple profiles in same backend server.

### ISSUE THREAD

**Issue by xydinesh** [Project-OSRM/osrm-backend#4736]
Is there a way to serve preprocessed files using foot, bike and auto profiles in same server ?
For example, I would put preprocessed data in following locations,

/data/foot
/data/bike
/data/car

Is there a way to stand up a server that can serve requests for "foot", "bike" or "car" ? I know it can be done with three separate servers. I want to do it in same server if I can (because of infrastructure costs).

**Comment by emiltin** [comment]
You need separate osrm processes, but they can run on the same server, if you have sufficient memory. A way to manage them is to use Docker containers.

**Comment by daniel-j-h** [comment]
See https://github.com/Project-OSRM/osrm-backend/issues/4517#issuecomment-330359238. I will add this to the wiki now. Happy routing. 🚗 🎉
