### ISSUE TITLE
Is it a right link to a route by foot?

### ISSUE THREAD

**Issue by marioerro** [Project-OSRM/osrm-backend#4737]
I'd want to take a route by foot between two points but the server always get me a driving route

What have I got wrong?

http://router.project-osrm.org/route/v1/bike/-3.6918982000,42.3528001000;-3.6988084300,42.3406573900?alternatives=false&overview=full&steps=true&alternatives=true

Thanks a lot

**Comment by systemed** [comment]
router.project-osrm.org only has a car profile installed on it. You could substitute "bike" or "foot" or "snowmobile" or "badger" for "driving", it still won't make any difference. If you want to find a foot route you can either set up your own instance of OSRM or use a third-party service that provides one.

**Comment by miccolis** [comment]
`<shameless plug>`Mapbox, which sponsors OSRM development, offers a walking profile. Docs are available at https://www.mapbox.com/api-documentation/#directions `</shameless plug>`

Hope that helps!
