### ISSUE TITLE
Get a matrix duration with zero values when I call the table service

### ISSUE THREAD

**Issue by boaniben** [Project-OSRM/osrm-backend#4740]
Hi,

I get a matrix duration with zero values when I call the table service:
The points are about 5 km apart. But if I call the table service with points that have a big distance between them then it does return a result
Here is a example with the 2 points and the return durations is: "durations":[[0,0],[0,0]]
http://router.project-osrm.org/table/v1/driving/31.7709773,34.6408181;31.8068197,34.6479119

Regards,
Ben

**Comment by TheMarex** [comment]
If you look at the points there are both in the middle of the Ocean. Both points snap to the same road on a nearby Island, thus the distance is correct.
