### ISSUE TITLE
database interface [feature request]

### ISSUE THREAD

**Issue by kkdd** [Project-OSRM/osrm-backend#4742]
Helllo,
Will OSRM have database interface in the future?
I would like to feed OSM data into OSRM not from a file but from database (e.g., postgresql).

**Comment by daniel-j-h** [comment]
OSRM uses libosmium to extract data; you can use formats libosmium understands (preferably pbf). If you want to read directly from a database you have to re-write a good portion of the extractor.

Either convert from postgres to xml or write a small helper script to convert from postgres to pbf directly (e.g. using pyosmium). Providing a pluggable road network source is out of scope for us.
