### ISSUE TITLE
Add turn limit.

### ISSUE THREAD

**Issue by cuixiaohui233** [Project-OSRM/osrm-backend#4743]
Why is it still available on the navigation map after the JOSM editor is used to add turning restrictions? Is it wrong for me to add? I read a lot of information, and I did it with the examples, but I was not able to do it. I was upset and hoped to get the right guidance. Thank you.

**Comment by daniel-j-h** [comment]
When you add a turn restriction with JOSM or iD it takes a while for the data to propagate through the pipeline for the demo server. Usually a day or two to be on the safe side.

If you want to see changes immediately you can set up your own routing engine

https://github.com/Project-OSRM/osrm-backend#quick-start

and then download an OpenStreetMap extract with your changes and route on it.

Happy routing! 🎉 🚗
