### ISSUE TITLE
could i change the map?

### ISSUE THREAD

**Issue by wangzi6578** [Project-OSRM/osrm-backend#4744]
hello, 
 is there a method for me to change the map for osrm? i want match gps points on other map, which part code should be changed to realise that?

**Comment by emiltin** [comment]
You need to run your own OSRM server, and then process the map you want to use. You don't need to change any code. Only OSM input data is supported directly though.

**Comment by daniel-j-h** [comment]
See https://github.com/Project-OSRM/osrm-backend/issues/4742.

**Comment by wangzi6578** [comment]
thank you for your responds. i got this and appreciate it






At 2017-12-19 16:24:51, "Emil Tin" <notifications@github.com> wrote:


You need to run your own OSRM server, and then process the map you want to use. You don't need to change any code. Only OSM input data is supported directly though.
