### ISSUE TITLE
how to get the id of the street

### ISSUE THREAD

**Issue by wangzi6578** [Project-OSRM/osrm-backend#4745]
hello,
after matched the gps to road, it will return a name, but is there have a parameter for sub-road,fore example, we can split a whole road to many smaller road and use a special num for road-1,road-2,road-3.

**Comment by TheMarex** [comment]
You can set any arbitrary name in the Lua profile [here](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua#L36).

**Comment by wangzi6578** [comment]
is there have a default one ?
