### ISSUE TITLE
2 differents routes between local and demo server

### ISSUE THREAD

**Issue by pislastdecimal** [Project-OSRM/osrm-backend#4746]
I
I'm probably facing the same problem mentioned here :[#4654](https://github.com/Project-OSRM/osrm-backend/issues/4654)

I'm working on a fresh osm france-latest and a "out of the box" master osrm-backend (using routabiltity in car.lua)

### This is what my local server returns to
localhost:5000/route/v1/driving/44.69308,-0.086441;44.660876,-0.184663?geometries=geojson

> {"code":"Ok","routes":[{"geometry":{"coordinates":[[9.264189,41.363115],[9.264189,41.363115]],"type":"LineString"},"legs":[{"summary":"","weight":0,"duration":0,"steps":[],"distance":0}],"weight_name":"routability","weight":0,"duration":0,"distance":0}],"waypoints":[{"hint":"mEtVgI-czIAMAAAAAAAAAG8AAAAAAAAADAAAAAAAAABvAAAAAAAAAJQ4AIA9XI0AqyZ3Alj2qQJXrv7_BAAfCa_4RH0=","name":"","location":[9.264189,41.363115]},{"hint":"mEtVgI-czIAMAAAAAAAAAG8AAAAAAAAADAAAAAAAAABvAAAAAAAAAJQ4AIA9XI0AqyZ3Aox4qQKpLv3_BAAfCa_4RH0=","name":"","location":[9.264189,41.363115]}]}

Here it's the blue track
![capture1](https://user-images.githubusercontent.com/5421587/34153962-2cfe1e0c-e4b4-11e7-9038-ef1f0607e888.png)

### and what demo server returns to 
https://router.project-osrm.org/route/v1/driving/44.69308,-0.086441;44.660876,-0.184663?geometries=geojson

> {"routes":[{"geometry":{"coordinates":[[44.025197,1.103833],[44.025197,1.103833]],"type":"LineString"},"legs":[{"summary":"","weight":0,"duration":0,"steps":[],"distance":0}],"weight_name":"routability","weight":0,"duration":0,"distance":0}],"waypoints":[{"hint":"FH1_hRV9f4UAAAAATAAAAAAAAAAsAwAAAAAAACYAAAAAAAAAlgEAAKXbAABtxZ8C2dcQAFj2qQJXrv7_AABfAmMvpBQ=","name":"","location":[44.025197,1.103833]},{"hint":"FH1_hRV9f4UAAAAATAAAAAAAAAAsAwAAAAAAACYAAAAAAAAAlgEAAKXbAABtxZ8C2dcQAIx4qQKpLv3_AABfAmMvpBQ=","name":"","location":[44.025197,1.103833]}],"code":"Ok"}

![capture2](https://user-images.githubusercontent.com/5421587/34154070-91c1d1a8-e4b4-11e7-910d-511f80e04ea3.png)

I also use the "distance" weight propertie which gives me the black track on the first image above
and it appears to be the  shortest AND fastest (weight routability)

where can i find the same profile as in demo server? or at least how can i get the same result for routability? 

thanks

**Comment by TheMarex** [comment]
The demo server uses our internal empirical weights that are not part of the standard Lua profile, so different routes are to be expected.
