### ISSUE TITLE
I want to use osrm lib in my c++ project but I really don't know how to get started...how can I use the library?

### ISSUE THREAD

**Issue by JialinYan96** [Project-OSRM/osrm-backend#4749]
I only need the map-matching function and how can I run my project like the example.cpp. Don't know how to include the library correctly

**Comment by daniel-j-h** [comment]
Clone the osrm-backend reposiroty. Compile from source --- get libosrm.

Then link in libosrm and append include/osrm to your project's compile and link flags.

See the example dir for a CMake based setup and it's FindLibOSRM in the cmake directory:

https://github.com/Project-OSRM/osrm-backend/tree/master/example

Building from source and the libosrm C++ API is described in

https://github.com/Project-OSRM/osrm-backend/wiki

**Comment by JialinYan96** [comment]
Is it possible to install the libosrm in Windows?

**Comment by daniel-j-h** [comment]
Yes it is possible. Check out

https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation

Good luck!

**Comment by AndrewSatMap** [comment]
Did you get anywhere with this? I also wish to use the Windows libOSRM, but son't get started either. Also, there doesn't seem to be a FindLibOSRM in the cmake directory.
