### ISSUE TITLE
the street id and nodes id 

### ISSUE THREAD

**Issue by wangzi6578** [Project-OSRM/osrm-backend#4752]
hello,
i use the annotation to get the nodes id ,can i use the id to get coordiantes by osrm ?can i get the id of segment of steet  of osm map just like nodes id?

**Comment by daniel-j-h** [comment]
OSRM does not store OSM way ids - all you can get is OSM node ids via the annotations feature. If you want to resolve OSM node ids into their location (or their tags, or the way(s) they're included in) I recommend:
- using libosmium (or the Python bindings pyosmium)
- building an index (map) from node ids to locations (or the metadata you want)
- at runtime using the annotations feature to get OSM ids and then querying your index


There's an example here to annotate a route with arbitrary OSM metadata:

https://github.com/mapbox/route-annotator

Good luck!
