### ISSUE TITLE
the weights of osrm engindon`t update with osrm-datastore

### ISSUE THREAD

**Issue by mrmrn** [Project-OSRM/osrm-backend#4757]
hi,
I used a csv file for updating segments speed in osrm engine.
```
/home/user/routing/osrm-customize /home/user/routing/aa.osrm  --segment-speed-file /home/user/routing/update.csv -t 16
/home/user/routing/osrm-datastore /home/user/routing/aa.osrm
```
When I use osrm debugging mode, sometimes the weights are not updated but the csv file updates correctly with the database weights.

how can I update osrm weights correctly?

**Comment by oxidase** [comment]
@mrmrn please could you provide a minimal reproducible example  of `aa.osm` and `update.csv` files that  reproduce the issue?

**Comment by mrmrn** [comment]
I updated car.lua and it works now. thank you
