### ISSUE TITLE
Why I got different results locally?

### ISSUE THREAD

**Issue by hopewise** [Project-OSRM/osrm-backend#4758]
I have used the latest image of docker to test locally Jordan country, and I have downloaded the latest Jordan man from OpenStreetMap.

I got different results for locally hosted OSRM than at http://router.project-osrm.org/

Here is the results for local host:

    "durations":[[0,468.2,42.9],[393.7,0,395.4],[41.4,457.3,0]]

and as for the same request at http://router.project-osrm.org/

    "durations":[[0,857.6,78],[722.2,0,727.6],[75.7,830.8,0]]

Any idea?

**Comment by daniel-j-h** [comment]
Your local instance does not come with traffic data. You route on OSM tags (e.g. highway, maxspeed tags) only. The demo server instance comes with freeflow traffic:

https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

> The dataset is a slightly modified car.lua, plus Mapbox's freeflow traffic data over the top - this should give more accurate ETAs in areas where Mapbox has traffic coverage than plain car.lua.

If you want current + historic traffic you should give the Mapbox service with `mapbox/driving-traffic` profile a try. Disclaimer: I'm with Mapbox.

https://www.mapbox.com/api-documentation/#directions

Closing here as not actionable.

**Comment by hopewise** [comment]
Thanks @daniel-j-h , an interesting thing I've noticed is that the result of local docker container is almost proportional to the results of the demo server instance, although I have no traffic data.

For example: `demo_durations[i, j] / local_durations[i, j] ` ~ 1.83 +- 0.02 , what would be the explanation?

Also, why should I consider current + historic traffic ? isn't current sufficient? what's the range of current?

Last question please, what are the options I have if I want to go open-source with the traffic data that is compatible with OSRM backend?  Is Mapbox's freeflow traffic data is free? where to download it?

**Comment by daniel-j-h** [comment]
Depends on the location for your queries, the time and date you make the query, etc.

Speeds derived from Lua have the best coverage (due to OSM) but often are rough approximations only. Historic speeds help with accuracy but there has to be coverage. Live traffic is the most accurate but also the sparsest source of traffic information. You can think of it as layers.

Regarding traffic sources there is http://opentraffic.io (not sure in which state it's in); the Mapbox Traffic sources are not openly available. You have to use the Mapbox service for that.

**Comment by hopewise** [comment]
Thanks, can you please tell me where can I read about Lua? is it the programming language Lua? if so, what does it has to do with OSRM which is based on C++ ?

**Comment by TimMcCauley** [comment]
@hopewise why don't you just google Lua? Seriously, these questions can be answered by using a little thought and research. Please also use OSRM's wiki for this, it explains most of your questions. RTFM :-)

- https://github.com/Project-OSRM/osrm-backend/wiki
- https://en.wikipedia.org/wiki/Lua_(programming_language)

**Comment by hopewise** [comment]
I did Google, found that Lua is a programming language, but didn't know why it was used, any way, thanks for the profiles link, I will read the manual.
