### ISSUE TITLE
Table service with negative coordenates

### ISSUE THREAD

**Issue by ragapack** [Project-OSRM/osrm-backend#4760]
Hi,
How I can make a table request like this
http://router.project-osrm.org/table/v1/driving/-20.2758825,-50.2649832;-23.4701500,-46.4719191;-22.2240202,-50.8809195;-23.5038242,-46.8586905?sources=0

It gives me this result:
{"durations":[[0,0,0,0]],"destinations":[{"hint":"968_hOawP4S8BQAAAAAAAFMeAAAAAAAA3gIAAAAAAAAqDwAAAAAAABuwAoDe9EP_ShjK_VWdyv5pBAH9EAC_D_S4HDM=","name":"","location":[-12.323618,-37.087158]},{"hint":"968_hOawP4S8BQAAAAAAAFMeAAAAAAAA3gIAAAAAAAAqDwAAAAAAABuwAoDe9EP_ShjK_brfmf4R5Tr9EAC_D_S4HDM=","name":"","location":[-12.323618,-37.087158]},{"hint":"968_hOawP4S8BQAAAAAAAFMeAAAAAAAA3gIAAAAAAAAqDwAAAAAAABuwAoDe9EP_ShjK_WzjrP5onvf8EAC_D_S4HDM=","name":"","location":[-12.323618,-37.087158]},{"hint":"968_hOawP4S8BQAAAAAAAFMeAAAAAAAA3gIAAAAAAAAqDwAAAAAAABuwAoDe9EP_ShjK_TBcmf49_jT9EAC_D_S4HDM=","name":"","location":[-12.323618,-37.087158]}],"sources":[{"hint":"968_hOawP4S8BQAAAAAAAFMeAAAAAAAA3gIAAAAAAAAqDwAAAAAAABuwAoDe9EP_ShjK_VWdyv5pBAH9EAC_D_S4HDM=","name":"","location":[-12.323618,-37.087158]}],"code":"Ok"}

**Comment by oxidase** [comment]
@ragapack coordinates in OSRM have [{longitude},{latitude}](http://project-osrm.org/docs/v5.10.0/api/#general-options) format.

With flipped coordinates http://router.project-osrm.org/table/v1/driving/-50.2649832,-20.2758825;-46.4719191,-23.4701500;-50.8809195,-22.2240202;-46.8586905,-23.5038242?sources=0
returns 
```
{
"durations": [
[
0,
21156.2,
30793.4,
20008.3
]
],
...
```

**Comment by daniel-j-h** [comment]
Solved!
