### ISSUE TITLE
Add support for non-numerical `maxheight` units 

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#4763]
Parsing `maxheight` does not include [non-numerical units](https://wiki.openstreetmap.org/wiki/Key:maxheight#Non-numerical_values).

The profile settings must include the default maximum height that must be used instead of ignoring height restrictions.

**Comment by frodrigo** [comment]
I add it to my TODO list.

**Comment by SiarheiFedartsou** [comment]
Seems to be done in https://github.com/Project-OSRM/osrm-backend/commit/2987292cc0b6ce1b36b1804c0efb07ff62d3625f
