### ISSUE TITLE
Group http request

### ISSUE THREAD

**Issue by SwannL** [Project-OSRM/osrm-backend#4769]
Hello, 

in the api we can use something like : 
`curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219'`
in order to send only one request to get the distance from several points to many other points. The issu is that it won't check on wich side of the road the user is. If the user has to go backward, osrm will suppose the user is on the opposite side of the road. 

So then, i used 
`curl 'http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false'`
The system now know the user is going from first point to second point so it knows on which side of the road the user is, and i can find the real time to go to the third point. 

The problem is now that if i want to fill a distance matrix 500*500, with the first method i'll have just wrong values and with the second, i'll need 500*500=250 000 http request. It would be great to solve the first problem in the table request or to create a web service that allows us to send only one request to get all the values formatted as the second method. 

Thank you for reading, 

Have a nice day ! :)

Swann

**Comment by TheMarex** [comment]
@SwannL You can use [`approaches=curb;curb;curb`](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#requests) with the `table` plugin to constrain the side of the road.

I don't think we will ever implement batching HTTP requests, handling requests of this type is what the `table` plugin is for.

**Comment by SwannL** [comment]
@TheMarex Thank you for your answer. Is there any documentation about this "approaches"? I don't really understand what it does. 
For instance, I have tried this : 

`http://router.project-osrm.org/table/v1/driving/-1.564557,47.206851;-1.564868,47.207197`

I got : [[0,8.1],[9,0]]

`http://router.project-osrm.org/table/v1/driving/-1.564557,47.206851;-1.564868,47.207197?approaches=curb;curb`

I got : [[0,8.1],[81,0]]

`http://router.project-osrm.org/table/v1/driving/-1.564557,47.206851;-1.564868,47.207197?approaches=curb;unrestricted`

I got : [[0,8.1],[140.9,0]]

So something actualy changed, but i cannot figure what that curb approaches really mean. 

Then i don't really understand how i can use it to determine which side of the road the user is coming from.
