### ISSUE TITLE
Clicking "Read the API usage policy" in README.md leads to a empty wiki page. 

### ISSUE THREAD

**Issue by Mafii** [Project-OSRM/osrm-backend#4773]
What are/Where is the API usage policy(ies)?

**Comment by daniel-j-h** [comment]
Thanks - fixed the link.

https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

> Note: the demo server usage is restricted to reasonable, non-commercial use-cases. We provide no guarantees wrt. uptime, latency, or data updates. If in doubt please ping us and ask first. Or use a commercial service such as Mapbox.
