### ISSUE TITLE
Different results for path with multiple coordinates

### ISSUE THREAD

**Issue by brunobruck** [Project-OSRM/osrm-backend#4777]
Hello, I'm using OSRM to build a very large distance and time matrices for a set of points. If I perform a single query for each pair of points using the `route` service it takes way too long time. So what I tried to do is combine a few queries in a single route with multiple points, hoping that it can speed up the process, and in the end have less queries. 

Suppose I have three points A, B and C, and assume, for simplicity, that I only want the distances between A -> B and B -> C. As a first option, one could create two queries, one for each route. Alternatively, one could create a single query for route A -> B -> C and take the values of the two legs. To my understanding, both methods should generate the same results. However, that is not what happens.

For example, consider the following points:

```
A) 11.339478,44.495731
B) 11.354113,44.506986
C) 11.392050,44.500497
```

- Query A -> B ([link](http://router.project-osrm.org/route/v1/driving/11.339478,44.495731;11.354113,44.506986)) results in `distance = 2673.2` and `duration = 520.2`
- Query B -> C ([link](http://router.project-osrm.org/route/v1/driving/11.354113,44.506986;11.392050,44.500497)) results in `distance = 7030.9` and `duration = 720.2`
- Query A -> B -> C ([link](http://router.project-osrm.org/route/v1/driving/11.339478,44.495731;11.354113,44.506986;11.392050,44.500497)) results in leg A ->B having the expected values, but leg B -> C has `distance = 7128.4` and `duration = 831.6`

Is this supposed to happen or is it an issue?

ps: I only used the demo to present the issue, I'm not running all my queries on it.

Thank you in advance,
Bruno

**Comment by jcoupey** [comment]
You need to be careful that the `B -> C` route might differ from the `B -> C` route leg in `A -> B -> C` depending on how the transition on the waypoints are handled (uturns might be allowed or not).

[Adding](http://router.project-osrm.org/route/v1/driving/11.339478,44.495731;11.354113,44.506986;11.392050,44.500497?continue_straight=false) `continue_straight=false` to the `A -> B -> C` query yields the expected distance and duration.

**Comment by brunobruck** [comment]
Thanks, that does seem to work.
