### ISSUE TITLE
Problem withe new OSRM and the trunk u-turns

### ISSUE THREAD

**Issue by Behizz** [Project-OSRM/osrm-backend#4780]
Hello guys
I've recently updated my OSRM server to the latest version (v15.14.2) and I see that there are some changes in the directions and one of them is a wrong one. In highways (trunks) when there is a u-trun in the route, the type will be "off ramp" and the modifier will be "sharp left" but in the earlier versions the type was "continue" and the modifier "u-turn" which is correct.

This is an example for this issue, but unfortunately the osrm map doesn't return a routing result for some countries.
http://map.project-osrm.org/?z=17&center=36.367388%2C-300.501920&loc=36.366753%2C-300.505975&loc=36.366010%2C-300.507671&hl=en&alt=0

Can you tell me how can I fix this?
Thanks

**Comment by oxidase** [comment]
@Behizz the original request has invalid longitudes. http://map.project-osrm.org/?z=18&center=36.367085%2C59.494085&loc=36.366753%2C59.494025&loc=36.366010%2C59.492329&hl=en&alt=0 has corrected longitudes and shows the route. 

OSRM does not collapse ramp turns into a U-turn instruction after commit ceaf065d0e86f72bb720d497de4016113a9a467d in #4074

You can try locally add after line https://github.com/Project-OSRM/osrm-backend/blob/6d801e7086cf7c12384611bda4f441ac3ce4dc17/src/engine/guidance/collapse_scenario_detection.cpp#L172
```
        !hasTurnType(*step_entering_intersection, TurnType::OnRamp) &&
        !hasTurnType(*step_entering_intersection, TurnType::OffRamp) &&
```

but the proper fix would be handling  the intersection in post-processing  as a segregated one (related issue #4273).

**Comment by Behizz** [comment]
Thanks @oxidase

**Comment by oxidase** [comment]
Happy routing!
