### ISSUE TITLE
How to adjust the value for confidence of map matching

### ISSUE THREAD

**Issue by DavidLiuGitHub** [Project-OSRM/osrm-backend#4784]
I have some gps traces that's reported by bicycler  and I built a osrm engine and data to adjust it, most cases can match successfully but the confidence value is too low even the gps points looks good for bicycler. 
I checked the code there are some values for laplace distribution in confidence processing, is there any way to adjust it(is there any paper showing it)? or is there any way to  increase the confidence using the same traced distance and matching distance

```
    MatchingConfidence()
        : // the values were derived from fitting a laplace distribution
          // to the values of manually classified traces
          classifier(map_matching::LaplaceDistribution(0.005986, 0.016646),
                     map_matching::LaplaceDistribution(0.054385, 0.458432),
                     0.696774) // valid apriori probability
```

**Comment by TheMarex** [comment]
[This](https://github.com/mapbox/osrm-matching-inspection/blob/master/bin/calibrate_classification.py#L118) is the python script I originally used to create the parameters for the classifier. I use the SciPy `fit` method to derive the parameters for a Laplacian distribution. What you need for that however is some labeled traces (correctly matched vs. incorrectly matched).

In general the problem with your bicycle traces is probably that the sampling rate/speed is different then for the car traces I used to derive the classifier. You could also try to use the raw probabilities from the Viterbi model, but these heavily depend on the length of the trace - not sure if it will help all that much for deriving a confidence.

**Comment by DavidLiuGitHub** [comment]
@TheMarex Thanks for your reply.
I looked into [This](https://github.com/mapbox/osrm-matching-inspection/blob/master/bin/calibrate_classification.py) script, Is there any more details about how to label the traces as the "invalid feature" or "valid feature", I saw it in code as below, but what's the 1,2,3,4?
        
```
       if m['cls'] == 2 or m['cls'] == 3:
            invalid_features.append(f)
        elif m['cls'] == 1 or m['cls'] == 4:
            valid_features.append(f)
```
And another question is  the priori probability（[code](https://github.com/mapbox/osrm-matching-inspection/blob/master/bin/calibrate_classification.py#L122)） of valid or invalid would return the int 0, is this a bug?

**Comment by SiarheiFedartsou** [comment]
Closed as stale.
