### ISSUE TITLE
Remove "can't parse value" log messages

### ISSUE THREAD

**Issue by miccolis** [Project-OSRM/osrm-backend#4794]
Back in c7b1d0c131c8a3598c32977bc1aede86bb5e7fbd we began logging values for max weight and height that we couldn't parse. This has lead to a lot of messages like ` "Can't parse value:     default"` during extract.

It's not clear to me if they are useful. Questions I have are;

* What exactly does the string `default` mean in when it's used for the OSM [maxheight](https://wiki.openstreetmap.org/wiki/Map_Features/Units#Explicit_specifications) tag? Is it just a mistag?
* Do we lose anything valuable it we just remove these log messages? ...or are they being relied on in anyway?

**Comment by oxidase** [comment]
Related issue https://github.com/Project-OSRM/osrm-backend/issues/4763

**Comment by danpat** [comment]
The OSM wiki [describes what `default` means for `maxheight`](https://wiki.openstreetmap.org/wiki/Key:maxheight#Non-numerical_values):

> There isn't any traffic sign indicating a legal maxheight limit, and the physical height is sufficient for the country specific height limit of general traffic. In some countries a missing traffic sign clearly indicates that this is true.
> In Germany (Europe?) this does also imply a physical height of at least 4.5m.

The wiki also notes that `default` is the most commonly used value for `maxheight`.

To support this, we could use the location-dependent data feature, and document the default values for different regions.    [In the US](https://ops.fhwa.dot.gov/freight/publications/size_regs_final_rpt/index.htm#cmv), there is no federal limit, max commercial vehicle heights are defined on a state-by-state basis.

**Comment by daniel-j-h** [comment]
Done in https://github.com/Project-OSRM/osrm-backend/pull/4810.
