### ISSUE TITLE
Is there an example on how to do map-matching with liborsm in C++?

### ISSUE THREAD

**Issue by JialinYan96** [Project-OSRM/osrm-backend#4802]
Is there an example on how to do map-matching with liborsm in C++?I'm new to this and there are so many source files. I'm confused....

**Comment by TheMarex** [comment]
You could have a look at our library unit tests [for an example](https://github.com/Project-OSRM/osrm-backend/blob/master/unit_tests/library/match.cpp#L18-L65).

**Comment by chaupow** [comment]
Can I close this? 
@JialinYan96 In case you have a follow-up question, just reopen this issue 😄

**Comment by JialinYan96** [comment]
OK~

Sent from Jialin Yan

________________________________
