### ISSUE TITLE
more detailed summary for routes

### ISSUE THREAD

**Issue by MichalPP** [Project-OSRM/osrm-backend#4803]
currently osrm provides only basic summary for each computed route (distance, duration). more detailled summary would be nice, for example
- in car profile, how many km was on motorways and how many on residential roads
- in bike profiles, how many km is on major roads, how many on cycleways
- in foot profile, how many km in parks vs in industrial areas

could OSRM make a summary of distance and duration for
- each mode (which I could do in the frontend)
- each exclude class (which is hidden for the frontend)
?

**Comment by TheMarex** [comment]
Couldn't you do this by just aggregating these values all steps with the appropriate `class`? Why would we need this on the server?

**Comment by MichalPP** [comment]
for mode, yes. however, I could not find any info on exclude class(es) on each step in the json output.

shoud I change subject to "display exclude classes on each step"?

**Comment by TheMarex** [comment]
You get them in even a higher resolution, per [intermediate segment](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#intersection-object) (see the `classes` property: 
`routes[].legs[].steps[].intersections[].classes` should give you what you need.

**Comment by MichalPP** [comment]
thanks, I was blind. I will experiment little bid.
