### ISSUE TITLE
no_right_turn_on_red restriction is handled as a right turn restriction

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#4804]
Restriction [`no_right_turn_on_red`](https://www.openstreetmap.org/relation/7879054) is used as a ["no turn" restriction](https://github.com/Project-OSRM/osrm-backend/blob/5943fcf406e28824ec511ed87e95a3bbffc5f67a/src/extractor/restriction_parser.cpp#L115-L118)  in OSRM. This leads to incorrect detours like http://map.project-osrm.org/?z=18&center=37.850965%2C-122.270778&loc=37.850370%2C-122.270676&loc=37.852069%2C-122.269979&hl=en&alt=0

`RestrictionParser` should use either a list of restriction values {`no_right_turn`, `no_left_turn`, `no_u_turn`, `no_straight_on`} or use a white list values like `no_right_turn_on_red`.

/cc @1ec5

**Comment by 1ec5** [comment]
A whitelist is a good idea, considering the [long tail of `restriction` values](https://taginfo.openstreetmap.org/keys/restriction#values), which are unaccounted for in OSRM’s tests and largely undocumented.

If it’s infeasible to switch to a whitelist, the 112 occurrences of `restriction=no_right_turn_on_red`, `no_turn_on_red`, and `no_left_turn_on_red` can probably be replaced with a different tagging scheme without much fuss, as long as there’s a suitable replacement.
