### ISSUE TITLE
Route plugin annotations mismatch

### ISSUE THREAD

**Issue by quiqua** [Project-OSRM/osrm-backend#4805]
# Problem

When making a request to the route plugin (via NodeJs + Express) with:

```
{
	"coordinates": [[13.35057 ,52.52297], [13.35126, 52.53073], [13.35697, 52.54094]],
	"annotations": ["duration" ,"speed"]
}
```

then the annotation array for `duration` doesn't match the summary for this annotation per leg.

(Request to demo server: `https://router.project-osrm.org/route/v1/driving/13.35057,52.52297;13.35126,52.53073;13.35697,52.54094?annotations=duration`)

Response:
```
{
	"routes": [{
		"geometry": "ukq_IconpAeTcG_Z`DQ{@eCuLyI|Gi\\y{@eOvUwBnA^dC",
		"legs": [{
			"annotation": {
				"duration": [44.9, 3.7, 3, 2.5, 55.9, 2.9, 13.8, 17.9, 3.8, 20.2, 1.6, 12.1, 29.1, 8.1]
			},
			"summary": "",
			"weight": 313.1,
			"duration": 228.1,
			"steps": [],
			"distance": 893.7
		}, {
			"annotation": {
				"duration": [12.2, 1.2, 3.3, 1.9, 0.6, 5.9, 11.3, 5.6, 8.7, 16.7, 6.7, 19.2, 0.8, 2.1, 2.1, 2.5, 8.5, 14, 3.8, 6.2, 2.3, 3.7, 3.7, 7.5, 2.6, 1.5, 3.7, 2.1, 1, 2.3, 6.2, 28.7, 25.6, 5.7, 4.6, 1, 2.7, 2.9, 2.5, 1.4, 2.1, 1.4, 1.5, 2.8, 4.1, 1.8, 9.4, 6.9, 2, 16, 3.2, 4.9, 0.6, 2.1, 1.6, 10.6, 8.3, 1, 2.1, 10.9]
			},
			"summary": "",
			"weight": 635.7,
			"duration": 379.5,
			"steps": [],
			"distance": 1721.4
		}],
		"weight_name": "routability",
		"weight": 948.8000000000001,
		"duration": 607.6,
		"distance": 2615.1000000000004
	}],
	"waypoints": [{
		"hint": "BYATgAKBE4A1AQAAcAIAAKUAAAA4AAAANQEAAHACAAAtAAAAOAAAAEfgAAATtssA8G8hA6q2ywDabyEDAgAfDF2nUx0=",
		"name": "Thomasiusstraße",
		"location": [13.350419, 52.522992]
	}, {
		"hint": "CnATgDhxE4BRAAAAbgAAAAAAAAC1AAAAUQAAAG4AAAAAAAAAPQAAAEfgAAApucsAaY4hA1y5ywAqjiEDAAD_A12nUx0=",
		"name": "Kruppstraße",
		"location": [13.351209, 52.530793]
	}, {
		"hint": "g6MTgP___39tAAAAKAQAAAAAAAAAAAAAbQAAABQCAAAAAAAAAAAAAEfgAAC9z8sA7rUhA6rPywAMtiEDAACPD12nUx0=",
		"name": "Kiautschoustraße",
		"location": [13.356989, 52.54091]
	}],
	"code": "Ok"
}
```

| Leg               | Sum of `routes[0].legs[i].annotation.duration` array | Summary `routes[0].legs[i].duration` object |
|-------------------|------------------------------------------------------|---------------------------------------------|
| routes[0].legs[0] | 219.5 seconds                                        | 228.1 seconds                               |
| routes[0].legs[1] | 338.3 seconds                                        | 379.5 seconds                               |

## Expected result

The sum of `routes[0].legs[i].annotation.duration` should be equal to `routes[0].legs[i].duration`.

I assume that the elements are not accurate, because if we look at the coordinates, we have `n` coordinates and `n-1` annotations, which seems ok.

**Comment by quiqua** [comment]
Is this because of https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#annotation-object :

> duration: The duration between each pair of coordinates, in seconds. Does not include the duration of any turns

If so, is there a way to get the duration including turns? If I just take `distance` and `speed` to calculate the `duration` for the coordinate-pairs, I'll still end up with wrong durations as `speed` is defined as `calculation of distance / duration`.

**Comment by TheMarex** [comment]
@quiqua seems like you already found the culprit yourself. This is indeed because we don't include the turn cost in the annotations. The reasoning here is motivated by the application the annotations were added for: Extracting the speed of a segment for displaying traffic on the route line.

Maybe you can share what you are trying to use it for?

**Comment by quiqua** [comment]
We are building some sort of vehicle simulation to process data for multiple Vehicle Routing Problems.

As we advance our virtual world by "x seconds", we need to know where the each vehicle will be since the last update.
Thus, we are using the annotations (`speed` and `duration` in particular) to figure out the distance travelled per coordinate pair `coordinate[i], coordinate[i+1]` during that duration.

Now let's say we have the start of the route, and want to know where the one vehicle might be in 35 seconds, we calculate the distance based on those (and also split up the annotations):

A Route with 3 coordinates and the following annotations:

```
    30 secs
+------------------>        40 secs
    5 m/s           +-------------------->
                            7 m/s
```

The same route with interpolated annotations after 35 seconds:

```
    30 secs                         35 secs
+------------------>    5 secs  +---------->
    5 m/s           +---------->    5 m/s
                       7 m/s
```

Is it possible to add a new annotation which has the turn-duration included or would this cause too much memory overhead?
If not, could you point me to a place to start this with? :)

**Comment by TheMarex** [comment]
Interesting application! It is quite simple to hack OSRM to include the turn penalty [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/guidance/assemble_geometry.hpp#L94-L95) just remove the subtraction of `path_point.duration_of_turn` and `path_point.weight_of_turn` and you should be good.

I'm not sure if we want to add this to the general API, since it runs counter to our original design of what annotations should be used for.

**Comment by quiqua** [comment]
We are now smoothing out the values based on the difference `routes[0].legs[i].duration - sum_n(routes[0].legs[i].annotation.duration[n])`. 

Thanks for you input :)
