### ISSUE TITLE
Question: Do OSRM supports Multi-Model routing?

### ISSUE THREAD

**Issue by mdakram** [Project-OSRM/osrm-backend#4813]
This is more a question than issue. Do OSRM supports Multi-Model Routing? It seems its not, Do we have any paln to support it in near future? As Mapzen is shutting down and they were providing [Multi-Model Routing](https://mapzen.com/projects/multimodal-transit-demo/) more people will come towards OSRM.

**Comment by TheMarex** [comment]
There is only a very limited support for it, the biggest limitation is our public transportation routing that can't use any timetable information.

- `car` profile: Car routing and ferries (assuming fixed duration)
- `bicycle` profile: Bike, foot (pushing the bike), ferry and public transportation routing (the latter not using time-table information)
- `foot` profile: Foot and ferry routing

We are not sure yet what the road toward multi-modal is going to be.
