### ISSUE TITLE
Lane Coverage

### ISSUE THREAD

**Issue by fungus1487** [Project-OSRM/osrm-backend#4821]
I have a use case where selecting a series of waypoints should provide coverage to the roads in both directions. Imagine the case of bin collection where the driver has to travel down the road and back up it in the opposite direction to collect all the bins.

Is there any way using the driving api to force the engine to use a certain lane and then use the opposite direction for future waypoints? I am fairly new to OSRM and am also investigating the documentation.

**Comment by daniel-j-h** [comment]
There is an approach parameter you can set to curb or unrestricted. Other than that you can not force specific lanes. Lanes are metadata on ways only but are not getting used for routing (hand-wavey).
