### ISSUE TITLE
barrier=height_restriction should not prevent routing

### ISSUE THREAD

**Issue by osrmuser** [Project-OSRM/osrm-backend#4823]
I think I have found a problem related to the handling of barrier=height_restriction on http://map.project-osrm.org/?z=18&center=52.140220%2C11.631485&loc=52.139836%2C11.630348&loc=52.139675%2C11.631544&hl=en&alt=0. It looks like OSRM avoids node https://www.openstreetmap.org/node/3247447825, probably beacause it is handled as an unpassable barrier without something like an explicit access=yes. But https://wiki.openstreetmap.org/wiki/Tag%3Abarrier%3Dheight_restrictor does not mention any explicit acces rule as required. 

Since I have found a barrier whitelist in https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L49, which seems to take care of similar problems, height_restriction probably should be added there (and maybe in other profiles too).

**Comment by MichalPP** [comment]
maybe it's time to switch from barrier_whitelist to barrier_blacklist #3890

**Comment by osrmuser** [comment]
Verified fixed, thx MichalPP and TheMarex
