### ISSUE TITLE
OSRM Docker seems to fail periodically from too many requests

### ISSUE THREAD

**Issue by radumas** [Project-OSRM/osrm-backend#4824]
Similar to #4723, but doesn't seem reproducible. I just pulled the latest image with `sudo docker pull osrm/osrm-backend:latest`.

We set up the docker image on a Ubuntu 16.04 LTS VPS (on Amazon EC2). It has 8GB of RAM and the following processors:
```shell
*-cpu:0
          description: CPU
          product: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
          bus info: cpu@0
          slot: CPU 1
     *-cpu:1
          description: CPU
          bus info: cpu@1
          slot: CPU 2
```

We set up the docker container similar to the quickstart guide for Toronto, Canada, using [this `.lua`](https://github.com/SAUSy-Lab/retro-gtfs/blob/master/etc/ttc.lua) file to get only transit directions. We're trying to process transit GPS data and the script makes requests for directions for a batch of GPS points in order to snap them to transit stops. Even making requests in a single thread, the process will make about 10 requests or so and the OSRM just stops responding...

Happy to provide more info, not sure what else is helpful for debugging.

**Comment by danpat** [comment]
What's CPU usage like inside the container?  After requests stop being answered, is the CPU idle or busy?

Does it change if you run `osrm-routed --threads 1` to limit concurrency?

**Comment by radumas** [comment]
mildly embarrassing but how I check cpu usage inside container?

**Comment by radumas** [comment]
Hmm... I think this might be related to #4825 somehow, since this problem doesn't appear to occur with `v.5.14.3` which I just downgraded to. Will investigate further tomorrow

**Comment by danpat** [comment]
If you encounter the problem in #4825, you will fail to create a dataset, and you will get *no* routing results at all - `osrm-routed` will fail to start.

**Comment by radumas** [comment]
I will play with different recent versions tomorrow. We definitely get some routing results, but then osrm just appears to stop responding.

**Comment by f3d0r** [comment]
I'm having a similar issue with this, any updates here?

**Comment by NumberPiOso** [comment]
I am having the same problem.

I have the set up in ubuntu 18.04 inside WSL 2.

The CPU idles and `osrm-routed --threads 1` did not work.

**Comment by ogtayhuseynov0** [comment]
I am having the same problem.

updates?

**Comment by holdmygithub** [comment]
I have also faced a similar issue. OSRM stops responding when bombarded with calls. Manually setting to sleep for some time between calls seems to do the job

**Comment by hoerup** [comment]
@holdmygithub could you try with latest code and if that helps? https://github.com/Project-OSRM/osrm-backend/commit/56a427f83909940060c154dc7b550de61991ca41

**Comment by SiarheiFedartsou** [comment]
Stale.
