### ISSUE TITLE
osrm-extract fails with what():  Profile used unknown class name: tunnel

### ISSUE THREAD

**Issue by radumas** [Project-OSRM/osrm-backend#4825]
Using [this `.lua` file](https://github.com/SAUSy-Lab/retro-gtfs/blob/master/etc/ttc.lua) I'm running `sudo docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /data/etc/ttc.lua /data/toronto_canada.osm.pbf` and getting:
```shell
...
[info] Collecting start/end information on 4133 restrictions...ok, after 0.002969s
[info] writing street name index ... ok, after 0.024966s
terminate called after throwing an instance of 'osrm::util::exception'
  what():  Profile used unknown class name: tunnel
```
 I can't seem to find `tunnel` in that file. This process works with `v5.14.3`

**Comment by danpat** [comment]
The tunnel class was added in 5.15.  If you've got a custom Lua profile (and it seems you do), you'll need to adapt it for changes made in 5.15's car.lua:

https://github.com/Project-OSRM/osrm-backend/pull/4812/files

Note the changes made to `car.lua` in that PR - make the same changes to your `ttc.lua` file.

**Comment by daniel-j-h** [comment]
Resolved.
