### ISSUE TITLE
Support way as via role in turn restriction

### ISSUE THREAD

**Issue by S0Cool** [Project-OSRM/osrm-backend#483]
OSRM does not route properly through crossing http://osrm.at/1y3.
Probably the reason is applying role "via" in routing relation "only_straight_on" not on node but way. The tagging in OSM database seems to be used correctly but routing algorithms do not include such situation.
Another routing service provides correct driving directions.
![Comparison](https://dl.dropbox.com/u/21938796/OSRM.PNG)

**Comment by woodbri** [comment]
@DennisOSRM Any idea/update on where this might fit into your plans time wise?

**Comment by daniel-j-h** [comment]
The plan for handling via way restrictions is outlined in https://github.com/Project-OSRM/osrm-backend/issues/2681. Closing this in favor of https://github.com/Project-OSRM/osrm-backend/issues/2681.
