### ISSUE TITLE
New name suppression ignores ref changes

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-backend#4830]
@dgearhart reported that, in [this route](http://map.project-osrm.org/?z=15&center=40.268802%2C-76.679592&loc=40.242299%2C-76.708537&loc=40.285722%2C-76.651079&hl=en&alt=0), OSRM doesn’t appear to issue a “continue straight” or “keep left” instruction at [the Ephrata exit](http://www.openstreetmap.org/node/666724455) along U.S. 322 East near Hershey, Pennsylvania.

<img src="https://user-images.githubusercontent.com/1231218/35431341-ebacafdc-0230-11e8-80ca-8b6e3497d301.png" width="321" alt="steps">

OSRM assumes that, because the branch to the right is a `motorway_link` as opposed to a `motorway`, this junction is an ordinary highway exit rather than a fork. The change of `ref` from `US 322` to `US 422` at this point should cause OSRM to emit a `new name` instruction, but I suspect that [`osrm::util::guidance::requiresNameAnnounced()`](https://github.com/Project-OSRM/osrm-backend/blob/a5e0d7011b0357b540810f7f67eef62caed3b43c/include/util/guidance/name_announcements.hpp#L108) returns `false` in this case:

* The `name` remains unchanged as an empty string on both the preceding and following `motorway` ways.
* [`obvious_change`](https://github.com/Project-OSRM/osrm-backend/blob/a5e0d7011b0357b540810f7f67eef62caed3b43c/include/util/guidance/name_announcements.hpp#L155-L158) is `true`
* because [`is_suffix_change`](https://github.com/Project-OSRM/osrm-backend/blob/a5e0d7011b0357b540810f7f67eef62caed3b43c/include/util/guidance/name_announcements.hpp#L145) is `true`
* because all four conditions of [`checkForPrefixOrSuffixChange()`](https://github.com/Project-OSRM/osrm-backend/blob/a5e0d7011b0357b540810f7f67eef62caed3b43c/include/util/guidance/name_announcements.hpp#L141-L142) are `true`
* because [`checkTable()`](https://github.com/Project-OSRM/osrm-backend/blob/a5e0d7011b0357b540810f7f67eef62caed3b43c/include/util/guidance/name_announcements.hpp#L137-L139) returns `true` on an empty string, and [`decompose()`](https://github.com/Project-OSRM/osrm-backend/blob/a5e0d7011b0357b540810f7f67eef62caed3b43c/include/util/guidance/name_announcements.hpp#L135) [returns a bunch of empty strings](https://github.com/Project-OSRM/osrm-backend/blob/a5e0d7011b0357b540810f7f67eef62caed3b43c/include/util/guidance/name_announcements.hpp#L82-L85) if [the longest common substring](https://github.com/Project-OSRM/osrm-backend/blob/a5e0d7011b0357b540810f7f67eef62caed3b43c/include/util/guidance/name_announcements.hpp#L66) is empty

/cc @oxidase

**Comment by dgearhart** [comment]
@oxidase here is another [example](http://map.project-osrm.org/?z=16&center=40.071594%2C-76.319350&loc=40.073055%2C-76.330647&loc=40.069205%2C-76.308954&hl=en&alt=0)
![screenshot from 2018-01-26 10-06-57](https://user-images.githubusercontent.com/7515853/35445779-b60415c8-0280-11e8-9a56-0d9328b2a799.png)
PA 283 East ends and the user should be instructed to continue on US 30 East

**Comment by oxidase** [comment]
@dgearhart #4832 adds a new instruction `Merge left onto US 30` at https://www.openstreetmap.org/node/107398202#map=19/40.07055/-76.31835&layers=D
![screenshot from 2018-01-26 10-26-40](https://user-images.githubusercontent.com/4421046/35446855-06d871b2-0284-11e8-989f-0ab52701ec0d.png)

**Comment by dgearhart** [comment]
@oxidase the merge looks good - what happened to the highway suffix direction? PA 283 `East` and US 30 `East`

**Comment by oxidase** [comment]
@dgearhart locally i use a profile [without cardinal directions parsing](https://github.com/Project-OSRM/osrm-backend/blob/84f96774241708444443d78a3ea484bb7ed1da97/profiles/car.lua#L38). With enabled cardinal directions the instruction is `Merge left onto US 30 $east`
