### ISSUE TITLE
Question: OSRM routing on Android/iOS?

### ISSUE THREAD

**Issue by mbukovy** [Project-OSRM/osrm-backend#4831]
Hello,

I need to run OSRM routing offline on Android and iOS.
What we do now: Currently we use osrm-backend build on our server with our own weights (segment-speed-file) to provide (sort of special) routing service online from the app. Everything works fine, but there is a need to do it offline, without internet connection.
What we want: We want to provide routing (route geometry and steps) with our weights completely offline on Android and iOS.

I've searched a bit, found some old threads about it and my best bet for now is the source code of Maps.me app. I'm going to investigate it for sure!
I just want to ask here - has anyone already managed to do this? Can you share some knowledge on how to do this?

**Comment by TheMarex** [comment]
This is a significant technical lift if you want to do routing on big datasets like North America. The main problem is two things: Memory usage and file size. To get the datasets to fit on a phone you need to compress and potentially remove a lot of the data that we provide by default. It is definitely doable (we have a prototype for this internally) but it will take some time until we can Incorporate this into mainline.

**Comment by mbukovy** [comment]
Thank you, for your comment!
I know, it's technically difficult, but this is not a question for now. I want to know now, **how to get a route on Android/iOS**. Let's have an **infinitely powerful phone** - how to get a casual osrm routing request on it?
Then I can figure out, how to do it efficiently. I just don't want to develop my own routing engine, when OSRM works flawlessly :-)

**Comment by TheMarex** [comment]
@mbukovy You should be able to compile OSRM on ARM, so you can build `libosrm` and use that as C++ library on Android.

**Comment by daniel-j-h** [comment]
Not actionable on our side. Check out the open old maps.me code base they used to include osrm.
