### ISSUE TITLE
exclude classes sometime ignored and route incorrectly

### ISSUE THREAD

**Issue by MichalPP** [Project-OSRM/osrm-backend#4833]
for my foot profile, I've created exclude class to fit wheelchair users (essentially it adds an exclude class on highway=steps). however, "sometimes" the classes are ignored and OSRM returns a route including steps

[like here](https://www.freemap.sk/?map=19/48.140186/17.104950&layers=O&tool=route-planner&points=48.140048/17.105128,48.140156/17.104814&transport=foot-stroller) - if you fiddle around with the start, sometimes it routes over steps, sometimes it correctly goes over a nearby ramp.

(maybe it is connected to #4818 )

**Comment by TheMarex** [comment]
Which version of OSRM are you running? I recently fixed https://github.com/Project-OSRM/osrm-backend/issues/4770 which might be the culprit here.

**Comment by MichalPP** [comment]
I think that latest v5.15, but I will rebuild the graph over this weekend and let you know.

**Comment by MichalPP** [comment]
upgrade to v5.15 fixed this, thank you
