### ISSUE TITLE
Http documentation missing examples for mode of transportation

### ISSUE THREAD

**Issue by Yiyio** [Project-OSRM/osrm-backend#4834]
Hi,

The documentation here: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

mentions one of the parameters is 'mode', but the only example provided is 'driving'. What are the names for other modes like foot, bike...?

**Comment by TheMarex** [comment]
@Yiyio do you mean the `profile` parameter? This is currently ignored by the HTTP bindings and only reserved for future use if we implement multi-profile support.

**Comment by Yiyio** [comment]
@TheMarex I meant the 'mode' under RouteStep object section: "mode: A string signifying the mode of transportation."

**Comment by chaupow** [comment]
@Yiyio Hi you can find them here:
https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/scripting_environment_lua.cpp#L110

**Comment by Demetrio92** [comment]
@TheMarex this should probably be mentioned somewhere in the docs. For now the website proudly claims 
> Supports car, bicycle, walk modes; easily customized through profiles.
and the docs explain that there is a "profile" and where to put it. But then the backed actually just ignores it.

**Comment by SiarheiFedartsou** [comment]
Stale.
