### ISSUE TITLE
Maximum coordinates number to table service?

### ISSUE THREAD

**Issue by hopewise** [Project-OSRM/osrm-backend#4836]
As for table service, in the documentation:

    GET /table/v1/{profile}/{coordinates}?{sources}=[{elem}...];&destinations=[{elem}...]

but, I could not find the maximum number of coordinates I can send  in `{coordinates}` ? what is the limitation?

**Comment by TheMarex** [comment]
Technically there is no hard limit, you can configure it when running [`osrm-routed`](https://github.com/Project-OSRM/osrm-backend/blob/master/src/tools/routed.cpp#L125-L127). The default is 100 coordinates. The node and C++ bindings have no default limit. Though, there are a few practical limitations:

1. The size of a HTTP GET request can be quite limited depending on the library you use.
2. Computing large quadratic matrices uses a lot of memory, so a 10000 x 10000 memory is likely to exhaust your servers memory.

**Comment by hopewise** [comment]
Thanks @TheMarex , yea, the practical limitations are known, but what exactly do I have to re-compile after changing the default value? can you please point me to the related documentation for this?
I am currently using OSRM-backend using docker..

**Comment by danpat** [comment]
@hopewise No need to recompile anything.  If you're using `osrm-routed`, try running `osrm-routed --help`.  There are several limits you can configure as command-line parameters to `osrm-routed`, and the `--max-table-size` is the one you'll want to change (it defaults to 100 for `osrm-routed`).

**Comment by danpat** [comment]
Please re-open if there is a bug using the `--max-table-size` parameter.
