### ISSUE TITLE
Coordinates are inverted for router request

### ISSUE THREAD

**Issue by igormcoelho** [Project-OSRM/osrm-backend#4838]
Dear all, when requesting a route to the router project, the coordinates seem to be inverted. For example, http://router.project-osrm.org/route/v1/driving/-43.9364852,-19.915462;-43.9435495,-19.9166798  represents coordinates [-19.915462,-43.9364852] and [-19.9166798,-43.9435495]. This is very harmful to our systems, and it would be nice to have it fixed in a near future to achieve a better standard.

**Comment by danpat** [comment]
@igormcoelho The coordinates part of the OSRM HTTP API at `router.project-osrm.org` uses `longitude,latitude` format, as documented here:

http://project-osrm.org/docs/v5.10.0/api/#requests

I'm struggling to see how this is harmful, and we will not be "fixing" this behaviour, it is not incorrect.  If you work with coordinates, you need to be aware that different software will accept parameters encoded in different orderings.

You may be interested in this page which shows different software supporting different coordinate definitions:

https://macwright.org/lonlat/
