### ISSUE TITLE
Unrecommended u-turn

### ISSUE THREAD

**Issue by srividyacb** [Project-OSRM/osrm-backend#4850]
The u-turn when the junction is modelled in triangular fashion is not recommended. 

All the roads in the junction are connecting to each other - but we are not recommending the turn from A-B via the cross-roads connecting the dual carriageway. And taking extra maneuver in another junction to reach destination. See this type of routing in junction which has triangularly modelled intersection. (_did check for two separate junction_)

[Example route link](http://map.project-osrm.org/?z=18&center=39.319052%2C-76.656160&loc=39.319097%2C-76.656230&loc=39.319164%2C-76.656616&hl=en&alt=0)

![image](https://user-images.githubusercontent.com/3423533/35758808-cffd63ee-0843-11e8-8ed1-6d7a6f0e156a.png)

cc @danpat

**Comment by srividyacb** [comment]
Not sure how consistent the problem is - but here are more examples to debug the issue 🐛 

- This example routes through the triangular junction - [example](http://map.project-osrm.org/?z=18&center=40.048191%2C-75.520089&loc=40.048166%2C-75.520266&loc=40.048150%2C-75.520148&hl=en&alt=0)
- While this [example1](http://map.project-osrm.org/?z=18&center=39.607664%2C-75.852978&loc=39.608234%2C-75.853606&loc=39.608494%2C-75.853322&hl=en&alt=0), [example2](http://map.project-osrm.org/?z=18&center=39.785237%2C-75.546150&loc=39.784977%2C-75.547791&loc=39.785224%2C-75.547560&hl=en&alt=0), [example3](http://map.project-osrm.org/?z=18&center=39.778171%2C-75.564786&loc=39.777730%2C-75.565628&loc=39.777820%2C-75.565901&hl=en&alt=1), [example4](http://map.project-osrm.org/?z=18&center=39.776303%2C-75.594944&loc=39.776542%2C-75.594757&loc=39.776711%2C-75.594279&hl=en&alt=0) doesn't and prefers extra maneuver.

![image](https://user-images.githubusercontent.com/3423533/35768644-31bf8f42-08cd-11e8-9d69-841f98d43d32.png)

**Comment by oxidase** [comment]
@srividyacb [route](http://map.project-osrm.org/?z=18&center=40.048053%2C-75.520685&loc=40.048166%2C-75.520266&loc=40.048150%2C-75.520148&hl=en&alt=0) has a `sharp left` instruction instead of a U-turn one because roads have no names and this prevents merging. 

Adding road names should fix the issue, but probably route will be different because U-turn instructions have higher penalty than left turns and some detour route will be preferable.

I have described current conditions for roads merging in OSRM  in  a paper doc https://paper.dropbox.com/doc/How-OSRM-merges-separated-roads-Z2e3e0M25ptiOT7doaszI

**Comment by srividyacb** [comment]
Referring the document and the conditions for a pencil junction to get merged and to issue a `u-turn` instruction 👇 

![image](https://user-images.githubusercontent.com/3423533/35831775-e77e669c-0a98-11e8-9209-b729dabb3fa3.png)

In my opinion, if there is no turn-restriction these - turns are valid to make and OSRM should be recommending a route through such cross-roads just like a usual u-turn via way 👇 . The reason for this recommendation is that - there are many places in OpenStreetMap where the junction is modelled in triangular fashion and OSRM will fail in all such cases if the above conditions are not satisfied.

![image](https://user-images.githubusercontent.com/3423533/35831884-3dc3a9b8-0a99-11e8-8c9f-8215fb36e011.png)

**Comment by SiarheiFedartsou** [comment]
Stale.
