### ISSUE TITLE
fatal error during building extract-conditionals

### ISSUE THREAD

**Issue by Behizz** [Project-OSRM/osrm-backend#4852]
Hello
I'm trying to make extract-conditionals using these two commands:

```
cmake -DBUILD_TOOLS=ON ..
make osrm-extract-conditionals
```

my boost version is 1.62.0 but during building it returns a fatal error
```
src/tools/extract-conditionals.cpp:1:42: fatal error: tools/extract-conditionals.hpp: No such file or directory
compilation terminated.
CMakeFiles/osrm-extract-conditionals.dir/build.make:62: recipe for target 'CMakeFiles/osrm-extract-conditionals.dir/src/tools/extract-conditionals.cpp.o' failed
make[3]: *** [CMakeFiles/osrm-extract-conditionals.dir/src/tools/extract-conditionals.cpp.o] Error 1
```
It looks like the extract-conditionals.hpp does not exist in files. How can I find/fix it?

Thanks

**Comment by oxidase** [comment]
@Behizz `osrm-extract-conditionals` is a testing tool for collecting OSM features with conditionals. It is not supported since moving the code part to the updater library and will be removed from the code base.

To compile `osrm-extract-conditionals` you can checkout 12f47708cdc42771667afb6feedbb31a85ae6a32

**Comment by Behizz** [comment]
Thanks for the answer @oxidase , I used the tool but it's not storing anything to the file. 
I'm using the latest OSRM version, is it needed to use a csv file for using conditional restrictions now or OSRM doesn't use it anymore and extracts it from the OSM file?

**Comment by oxidase** [comment]
You don't need to use csv files. `osrm-extractor --parse-conditional-restrictions`   saves conditional restrictions to `.restrictions` files and later conditions can be used in contraction as `osrm-contract --parse-conditionals-from-now 1517908115 --time-zone-file tz.json`

**Comment by Behizz** [comment]
Thanks @oxidase

**Comment by Behizz** [comment]
@oxidase Sorry if I'm asking too much questions, but I'm experiencing some weird behaviors in applying conditional restrictions. It appears that the conditionals doesn't change status (applicable/not applicable according to the time restriction) unless running the MLD pipeline again. I mean there's something wrong with the clock/time of the OSRM although I've set the timezone and the timestamp correctly.
Do you have any idea what is the problem?

**Comment by oxidase** [comment]
@Behizz to update conditional restrictions in a road graph you have to re-run `osrm-contract` or `osrm-customize` with `--parse-conditionals-from-now <new UTC timestamp> --time-zone-file tz.json` arguments and reload the updated graph in OSRM engine. You also can check if  `tzdata` package is installed: 
```
TZ=America/New_York date -d @1500000000 "+%Y%m%d %H%M"
```
must return `20170713 2240`. `tzdata` package is required for conversion of UTC timestamps into conditional restrictions local time.

**Comment by Behizz** [comment]
@oxidase I'm doing just the same things that you said, the timezone is OK but it's not working until I start from extract, partition, ...
what else should I check?

**Comment by slavanap** [comment]
@oxidase Could you please list all set of OSRM commands to enable conditional restrictions checks? How to get tz.json from tzdata file? How to use http://efele.net/maps/tz/world/tz_world.zip ?
Imho, there's not enough information here to start for people who are not familiar with the subject
https://github.com/Project-OSRM/osrm-backend/wiki/Check-conditional-restrictions

Right now I'm using
```
osrm-extract --parse-conditional-restrictions -p /opt/car.lua /data/map.osm.bz2
osrm-partition /data/map.osm
osrm-customize /data/map.osm
```
