### ISSUE TITLE
incorrect results of map matching, with detours

### ISSUE THREAD

**Issue by jobryant** [Project-OSRM/osrm-backend#4853]
I'm confused that the matched trace took a detour by trying to turn at an incorrect crossing and run in an inverse direction. By the way, the original trace started from the right blue point. 
Disappointedly, most of my traces got this problem. Could anyone give some advice? Thanks, very much.

coordinates:
[[-8.585694,41.148603],[-8.585757,41.148684],[-8.585712,41.148882],[-8.585757,41.148963],[-8.585838,41.148954],[-8.586063,41.148972],[-8.586171,41.148972],[-8.587323,41.149152],[-8.588007,41.149386],[-8.588736,41.149602],[-8.591031,41.150187],[-8.592165,41.150484],[-8.592201,41.150493],[-8.593389,41.150844],[-8.59455,41.150664],[-8.595918,41.149872],[-8.596647,41.149431]]

my params:
overview: 'full',
gaps: 'ignore',
tidy: 'true',

profile:
car.lua

original trace:
![image](https://user-images.githubusercontent.com/9425287/35785749-dede1658-0a5d-11e8-8892-0731eda46ebf.png)

after matching:
![image](https://user-images.githubusercontent.com/9425287/35785768-f0852ee6-0a5d-11e8-8579-887ee709a92b.png)

**Comment by jobryant** [comment]
There is the wrong stopping point.
![image](https://user-images.githubusercontent.com/9425287/35786047-9dcb3090-0a5f-11e8-8975-74680eaa27ed.png)

**Comment by TheMarex** [comment]
You probably need to increase the GPS precision to something bigger than 5 meters. Try adding `radiuses: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]`.

**Comment by jobryant** [comment]
thanks for your advice, I really appreciate it!
I've tried radiuses from 1 to 50. It seems radiuses = [10,...] get better performance in some other traces than default radiuses.
However, In the above case, which I thought it's easy to match, the radiuses didn't solve it.
May this problem be related to the configuration of profile? I used the default car.lua

**Comment by TheMarex** [comment]
Maybe there is a turn restriction that would cause to take an erratic turn like this? You could try to run a few routes between the matched endpoints to find out why it takes that weird route.
