### ISSUE TITLE
match search algorithm changed: radius of 20m is "too big"

### ISSUE THREAD

**Issue by donnut** [Project-OSRM/osrm-backend#4857]
I have been using version 5.7 a lot for map matching using the example query:
```
 curl "http://10.7.1.122:5000/match/v1/driving/7.65277099609375,51.93421936035156;7.652750015258789,51.934200286865234;7.652730464935303,51.93418884277344;7.6526689529418945,51.93415069580078?steps=true&overview=full&annotations=true&geometries=geojson&radiuses=20;20;20;20&timestamps=1486119132;1486119134;1486119135;1486119137"
```
In version 5.15.* the query returns:
```
{"message":"Radius search size is too large for map matching.","code":"TooBig"}
```
When I reduce the search radius to a default of 5m, the query returns result. 

Was there any change in the search algorithm of the matcher? Is 20 m really too big?

**Comment by jcoupey** [comment]
Seems like you're hitting a default max value for that parameter that maybe changed between versions:
https://github.com/Project-OSRM/osrm-backend/blob/84b6ef43403b75ec683a4e50dde58b20c476ac24/src/tools/routed.cpp#L137-L139

If you run your own server, you should be able to use the `--max-matching-radius` option.

**Comment by donnut** [comment]
Thanks, I'll give that a try.

**Comment by TheMarex** [comment]
This is actually a good point, the default here should be unlimted to no break requests.

**Comment by TheMarex** [comment]
Fixed by #4866.

**Comment by ZephD** [comment]
> If you run your own server, you should be able to use the --max-matching-radius option.
Thanks for this, as we're currently running the version before the merge request.

Is it possible to set the default radius instead of the max?
For example, I would like all searches to use a default of 10m instead of a default of 5m, without the need to add `&radiuses=10;10;10;...` to every query.
Thanks.

**Comment by danpat** [comment]
@ZephD Not without recompiling the code.  A pull request adding this feature would be welcome though!
