### ISSUE TITLE
Compilation issues on ppc64le

### ISSUE THREAD

**Issue by Fred-Byrd** [Project-OSRM/osrm-backend#4861]
Hi folks,

I just wanted to share an issue which came up when building osrm-backend from source on RHEL 7 with PowerPC architecture.

Before we get into it, I am aware of the docker option (which I am grateful for). However, my organization does not have a Docker EE subscription, and Docker CE is not supported on RHEL (installation is possible but a pain and quite buggy, but I digress).

Anyway, after satisfying all dependencies, I kept running into a puzzling compiler error when building from source. Lines 24-25 in the coordinate_calculation header:

`const constexpr long double DEGREE_TO_RAD = 0.0174532925199432954743716805978693;
const constexpr long double RAD_TO_DEGREE = 1. / DEGREE_TO_RAD;`

caused the following error:

`error: ‘(1.0e+0l / 1.74532925199432954743716805978693e-2l)’ is not a constant expression
 const constexpr long double RAD_TO_DEGREE = 1. / DEGREE_TO_RAD;`

I did some digging and found that it might have something to do with the fact that PPC is unique in how it treats long doubles, which you can read about [here](https://en.wikipedia.org/wiki/Long_double#Implementations).

Why this might cause a compiler error is beyond me. However **changing this declaration to be double instead fixes the issue.** I went ahead and posted a [question](https://stackoverflow.com/questions/48553127/error-with-long-doubles-on-powerpc-when-compiling-with-gcc) about it on stackoverflow, and got a variety of responses, some of which seem helpful, and some not (nitpicking your constant naming conventions :eyeroll:).

I'm no expert, but I hope this was helpful. Not sure if a patch would be simple to implement or if it should just be documented somewhere in the wiki.

Cheers,

Fred

**Comment by danpat** [comment]
@Fred-Byrd That smells like a compiler bug for sure.

I'm not sure if we need the precision given by `long double` here - if you'd like to make a pull request that changes it so it works for you, please go ahead and open one - opening a PR will trigger a build to run through (on travis-ci.org), and that'll be a good smoke test to see if we actually depend on the ~30 decimal places of precision here :-P

@TheMarex looks like you added this constant when OSRM v5 rolled around - any recollection of where the number came from or why it's so precise?

**Comment by TheMarex** [comment]
@danpat afaik I was working around a MSVC bug with not being able to use `PI` in a constexpr, that might have changed with more recent versions, so we could try that.

**Comment by Fred-Byrd** [comment]
PR submitted. Looks like build completed successfully.

Are unit tests included there? I can't find them, if so. Interested to see how accuracy is affected by this change. I routed my commute home and the result seems fine, but that's highly anecdotal.

**Comment by daniel-j-h** [comment]
Done in https://github.com/Project-OSRM/osrm-backend/pull/4880.
