### ISSUE TITLE
Investigate Assertion when merging relations

### ISSUE THREAD

**Issue by chaupow** [Project-OSRM/osrm-backend#4865]
When extracting a concatinated osm.pbf file of california+mexico+massachusetts+sweden the assertion
https://github.com/Project-OSRM/osrm-backend/blob/master/include/extractor/extraction_relation.hpp#L130
was hit. 

Current guess is that there might be duplicated relations at the border of california&mexico.
when inserting the relation `res.second` returns false because it already exists.

Investigate and reevaluate whether this should be an assertion in the first case

**Comment by daniel-j-h** [comment]
Looks like the assertion is wrong in the case when we have the relation multiple times (e.g. due to different osm base maps). Want to fix this?
