### ISSUE TITLE
Allow read-only route links

### ISSUE THREAD

**Issue by mackerski** [Project-OSRM/osrm-backend#487]
When requesting a route link, often one wishes to share the link with others who wish to view but not modify it. The current UI makes it easy to drag the route around, and such users may not realise the danger or that they have done so. A checkbox to make linked routes read-only would be a practical solution to this.

**Comment by TheMarex** [comment]
This is not part of OSRM scope anymore Leaflet-Routing-Machine has an option to satisfy this.
