### ISSUE TITLE
Highway name change at border

### ISSUE THREAD

**Issue by frankvandenbergh** [Project-OSRM/osrm-backend#4870]
When you ask for a route between Eindhoven (NL) and München (DE) in the demo server, you'll pass the border at Venlo. Just before the border you drive on the A73 for say 8 km, next the A74 for a km or so, then you enter Germany on the A61 for many km's. The A74 changes name at the border into A61.

`http://map.project-osrm.org/?z=8&center=50.611132%2C6.830750&loc=51.448557%2C5.450123&loc=48.137108%2C11.575382&hl=en&alt=0`

The route instructions just say "Keep left at the fork towards A74; 350 km". I'd expect to read about the A61.

**Comment by jguthrie100** [comment]
I wonder if it's worth having a generic `Crossing into Germany/France/Belgium` message whenever a border is crossed?

**Comment by frankvandenbergh** [comment]
That might be usefull. 
But reporting the right roadname is more important, especially if you want to use it for guidance.

Google maps writes something (translated by me): 
turn left on A74 for 1,9 km
continue on the A61, you are now entering Germany

**Comment by oxidase** [comment]
a similar case  was reported by @chaupow in #4896:

> Routing this way A5 -> A67:

> http://map.project-osrm.org/?z=15&center=49.857215%2C8.602273&loc=49.871102%2C8.600750&loc=49.848803%2C8.596029&hl=en&alt=0

> does not have an instruction (even though there is a name change)

**Comment by frankvandenbergh** [comment]
This issue is solved in v5.16.0
