### ISSUE TITLE
Map Matching blank names for routes

### ISSUE THREAD

**Issue by jhosn13** [Project-OSRM/osrm-backend#4871]
I am trying to understand why the output includes None in tracepoints. What do these mean?

>[**None, None, None**, {u'waypoint_index': 0, u'name': u'West Washington Street',

And then the algorithm would return a coordinate sometimes without a street name. Are these erroneous output?

>{u'waypoint_index': 26, **u'name': u'**', u'hint': u'eWK6g____382AAAAjwAAAAAAAAB-AAAADQAAACQAAAAAAAAAHwAAAJo5AAB55FH5-qL-AY3kUfkRo_4BAAAvE3jrEvY=', u'matchings_index': 0, u'location': **[-112.073607, 33.465082]**, u'alternatives_count': 0}

**Comment by TheMarex** [comment]
`None` means that the point couldn't be matched. The street name can be empty if the street in OSM has no `name` field.

**Comment by daniel-j-h** [comment]
Resolved.
