### ISSUE TITLE
Implement unaccellerated Dijkstra as own algorithm

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#4874]
In order to be able to support more dynamic features, we need a routing algorithm without any pre-processing that is metric dependent. This gives us a dummy implementation we can use to implement advanced dynamic API features.

Since we have all the abstractions layers already in place, this is quite straight forward:
- Add a new algorithm https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/algorithm.hpp#L10-L26
- Add a new `AlgorithmDataFacade` that uses the MLD base graph
- Add a new implementation for `Search()` in `routing_base.hpp`

**Comment by chaupow** [comment]
Btw, this is a superb intro task for someone who likes shortest paths algorithms and c++ and osrm and has not written a Dijkstra before.... 

well no, even if you have implemented Dijkstras already. You can never implement too many DIjkstras in life.
