### ISSUE TITLE
Shortest path and fastest path

### ISSUE THREAD

**Issue by SD-OSRM** [Project-OSRM/osrm-backend#4879]
Hi,

Is there any possibility to specify that the shortest path is required in the answer of **route** service?
Currently, the service returns the fastest result first.

If "alternatives=true" parameter is specified then route service returns several results. However, the fastest path is still first in the answer and there is no guarantee that the shortest path exists among the alternatives.

Are there any undocumented parameters like "routeMode=fastest" or "routeMode=shortest"?
For example https://www.graphhopper.com service provides "weighting" parameter. And it is possible to request the fastest route ("weighting=fastest") or the shortest route ""weighting=shortest". Is it possible in OSRM route service?
Or it is easier to request several alternatives and choose answer with the shortest route?

Kind regards

**Comment by danpat** [comment]
@SD-OSRM Currently no.  The dataset that OSRM calculates routes on is optimized to answer a single metric - minimizing the duration of the route.  OSRM doesn't actually have a graph available that it could calculate the shortest distance route on.  The alternatives returned are all based on variations of the fastest route.

There is a ticket tracking the support for multiple routing metrics here: https://github.com/Project-OSRM/osrm-backend/issues/4007

You can deploy *two* OSRM servers with different datasets - one for fastest time, one for fastest distance, but it will double your server running needs, they cannot share data.
