### ISSUE TITLE
Installing OSRM on Windows

### ISSUE THREAD

**Issue by Grigorsuv** [Project-OSRM/osrm-backend#4886]
Hi,trying to build osrm and getting this error 
![a](https://user-images.githubusercontent.com/28960079/36246543-c86cb688-1249-11e8-9bcf-12438aa29365.PNG)
Also getting error installing npm osrm,with node versions 6,8.9 and 9.5
![b](https://user-images.githubusercontent.com/28960079/36246706-712ae9e8-124a-11e8-9984-0a6ec698e70b.PNG)

**Comment by Grigorsuv** [comment]
Is there any news for windows users ?

**Comment by Grigorsuv** [comment]
@TheMarex

**Comment by TheMarex** [comment]
I'm not familiar with out windows build system setup. Please ask on StackOverflow or use the linux setup.
