### ISSUE TITLE
[missing "en-US.javascripts.directions.instructions.uturn_with_exit" translation]

### ISSUE THREAD

**Issue by zayuim** [Project-OSRM/osrm-backend#4891]
It seems like this instruction is missing a translation. https://www.openstreetmap.org/directions?engine=osrm_car&route=-27.48778%2C152.99054%3B-27.48698%2C152.99020#map=18/-27.49066/152.99035

Just so you know, this route is legit (although it looks strange), since a right turn isn't allowed.

**Comment by danpat** [comment]
@zayuim You'll need to report this as a bug against the OSM website, it's the thing responsible for turning responses from OSRM into text displayed on the website.

The OSRM demo server shows the correct instructions:

http://map.project-osrm.org/?z=17&center=-27.489733%2C152.989903&loc=-27.487707%2C152.990831&loc=-27.487077%2C152.990527&hl=en&alt=0

here, we use https://github.com/Project-OSRM/osrm-text-instructions to generate the readable sentences.
