### ISSUE TITLE
Bug: Unneccessary u-turn

### ISSUE THREAD

**Issue by jguthrie100** [Project-OSRM/osrm-backend#4892]
If you get directions from Knutsford, UK to Manchester, UK, then the routing instructs to do a u-turn where it seems none is required..

http://map.project-osrm.org/?z=16&center=53.463443%2C-2.239441&loc=53.307874%2C-2.372051&loc=53.479130%2C-2.244101&hl=en&alt=0

(On Greenheys Lane, near Manchester city centre)

**Comment by jguthrie100** [comment]
Turns out someone had set a set of traffic lights to be "No straight on", which I've now fixed on OSM

**Comment by oxidase** [comment]
@jguthrie100 Thanks for fixing the issue! Closing here as the roads graph was updated.
