### ISSUE TITLE
How does OSRM derive its speed between any two adjacent OSM nodes?

### ISSUE THREAD

**Issue by zyrgit** [Project-OSRM/osrm-backend#4894]
Hi, thanks in advance! I have a question regarding the internal derivation of average speed between any two nodes.
When I do match query with annotation enabled, OSRM returns a list of OSM node ids and the travel time between each pair of nodes, how does OSRM derive the speed?
I understand that there is a LUA script in profiles that sort of estimate the speed limit and adjust the speed according to surface condition and so on, but when I query match API, it returns seemingly fine grained travel time/ speed info. I guess there must be something more fine-grained than speed limit, when calculating the average speed between two nodes.
So can anyone suggest the way OSRM estimates the speed? Thanks!

**Comment by zyrgit** [comment]
Thank you! So I am wondering what the speed source you used in OSRM so that when I use Match/Route service API with "&annotations=true", it can return "distance/duration" in URL response. I'm wondering if it is possible to gain access to such a speed source? Thanks!

**Comment by daniel-j-h** [comment]
You have to collect your traffic data from _some source_ :) Closing as not actionable on our side.
