### ISSUE TITLE
Missing instruction at a ramp bifurcation

### ISSUE THREAD

**Issue by oxidase** [Project-OSRM/osrm-backend#4895]
At ramp bifurcations OSRM suppresses obvious instructions 
http://map.project-osrm.org/?z=18&center=33.645919%2C-84.444394&loc=33.645961%2C-84.443981&loc=33.646068%2C-84.445086&hl=en&alt=0
![screenshot from 2018-02-19 10-02-21](https://user-images.githubusercontent.com/4421046/36369609-1a61e462-155c-11e8-95c9-83368e0a7d70.png)

Valhalla does not suppress turn instructions in similar case and produces for the above route  [ `Keep right to take I 85 South toward I 285/Montgomery.`](https://valhalla.github.io/demos/routing/index.html#loc=18,33.646053,-84.444542&locations=[{%22lat%22:33.646018730864775,%22lon%22:-84.4440883398056},{%22lat%22:33.64609911436225,%22lon%22:-84.44499492645264}]&costing=%22auto%22) instruction due to condition [`maneuver.ramp() && prev_edge->IsRampUse()`](https://github.com/valhalla/valhalla/blob/69e1d050a6f0845cb0ad58c9ba401cb1fdacf68d/src/odin/maneuversbuilder.cc#L1570)

In order to synchronize guidance instructions OSRM should handle a case of ramp bifurcations as non-obvious. The current OSRM ramp bifurcations implementation is captured by the feature tests:
- [Kreuz Oranienburg](https://github.com/Project-OSRM/osrm-backend/blob/a8bc2cf8a78c1831b259701ad66ce575c7f5768a/features/guidance/anticipate-lanes.feature#L136)
- [Fork on motorway links - don't fork on through](https://github.com/Project-OSRM/osrm-backend/blob/a8bc2cf8a78c1831b259701ad66ce575c7f5768a/features/guidance/fork.feature#L369)
- [Fork on motorway links - don't fork on through but use lane](features/guidance/turn-lanes.feature:860)

/cc @srividyacb @dgearhart

**Comment by dgearhart** [comment]
@oxidase Are you saying the [Kreuz Oranienburg](https://github.com/Project-OSRM/osrm-backend/blob/a8bc2cf8a78c1831b259701ad66ce575c7f5768a/features/guidance/anticipate-lanes.feature#L136) test case will be fixed?
![screenshot from 2018-02-19 10-29-33](https://user-images.githubusercontent.com/7515853/36385269-186297a2-1560-11e8-8561-7da295783370.png)
so both will now say `Keep left at the fork...`

**Comment by oxidase** [comment]
@dgearhart yes, the third instruction will be `Keep left at the fork towards A 111: Berlin`

**Comment by dgearhart** [comment]
@oxidase excellent! Thanks
