### ISSUE TITLE
osrm-routed starting very slowly

### ISSUE THREAD

**Issue by donnut** [Project-OSRM/osrm-backend#4897]
We have a local copy of osrm running (in a docker container) using the extracted/partitioned/customized planet file of the world. 
It is a pretty fast machine (2T ssd, 64G ram, intel i7), but is takes about 30+ minutes to start up (osrm-routed). Its using about 80G of mem (partly in swap) and its running on 8 threats. 
(Both data and osrm-routed are on one machine, thus it is not related to #3407)

Is 30+ minutes a normal startup time for osrm-routed?

**Comment by donnut** [comment]
BTW I use v1.15.1.
Probably unrelated, but when starting v1.15.2, osrm-routed keeps having a load of 600% for more than 2.5 hours, without handling any request.

**Comment by donnut** [comment]
Mean ignore the remark about version 1.15.2. It's caused by something else.

I'm still curious to learn something more about 'normal' startup times.

**Comment by daniel-j-h** [comment]
Look into shared memory:

https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory

and use `osrm-datastore` to lock the dataset to shared memory once and then use `osrm-routed` and instantly attach to this shared memory segment.
