### ISSUE TITLE
Are forest roads ignored?

### ISSUE THREAD

**Issue by IonicaBizau** [Project-OSRM/osrm-backend#4898]
I'm using OSRM for the first time and I'm pretty happy so far.

I was playing with the REST apis and I wanted to find the distance between two points:

```
    A --(1)----forest road---[mountain]----forest-road----- B
     \__(2)______________Road for the cars________/
```

It always returns on the second one (~100km), instead of the first one (which I know it's about 20km).

I noticed the Map application doesn't handle that either:

![image](https://user-images.githubusercontent.com/2864371/36418532-d2203938-1637-11e8-9e22-1b1df6b01895.png)

How can I start debugging this?

My current API call looks like this:

> http://localhost:8001/route/v1/bike/...;...?alternatives=3

**Comment by frodrigo** [comment]
tracks are not in the default car profile:
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L136

**Comment by IonicaBizau** [comment]
@frodrigo Ah, good point! Can you please tell me what to add there to include _all_ the roads (e.g. forest roads or even smaller roads only for walking/biking or something like that)?

**Comment by lamaux** [comment]
For more information about profiles see https://github.com/Project-OSRM/osrm-backend/wiki/Profiles

**Comment by daniel-j-h** [comment]
Closing here. Not actionable on our side; happy routing! :tada: :car: :bike: :walking_woman:

**Comment by IonicaBizau** [comment]
Thanks. Haven’t tried yet, but probably choosing the right profile is the answer.
