### ISSUE TITLE
Wrong polyline decoded by the server

### ISSUE THREAD

**Issue by eestein** [Project-OSRM/osrm-backend#4902]
It seems to me the polyline is being incorrectly decoded on server side, or maybe I'm missing something here...

The reason why I think it might be related to a server side decoding issue is that I have this URL:

> http://router.project-osrm.org/route/v1/driving/polyline(k_vpAofp_Iyu@ilAg`Ete@bwF_W)?overview=false

If you make a request to that URL, you'll see it returns empty legs, and the waypoints are only one location. Output:

```
{
    "routes": [
        {
            "legs": [
                {
                    "summary": "",
                    "weight": 0,
                    "duration": 0,
                    "steps": [],
                    "distance": 0
                },
                {
                    "summary": "",
                    "weight": 0,
                    "duration": 0,
                    "steps": [],
                    "distance": 0
                },
                {
                    "summary": "",
                    "weight": 0,
                    "duration": 0,
                    "steps": [],
                    "distance": 0
                }
            ],
            "weight_name": "routability",
            "weight": 0,
            "duration": 0,
            "distance": 0
        }
    ],
    "waypoints": [
        {
            "hint": "Kqv5hi-r-YYAAAAAXAAAAAAAAADYAAAAAAAAAC4AAAAAAAAAawAAAE3pAACBIzADWLTBALBYIQM8TMwAAABvAiprV7g=",
            "name": "",
            "location": [
                53.486465,
                12.694616
            ]
        },
        {
            "hint": "Kqv5hi-r-YYAAAAAXAAAAAAAAADYAAAAAAAAAC4AAAAAAAAAawAAAE3pAACBIzADWLTBAAKJIQN-bswAAABvAiprV7g=",
            "name": "",
            "location": [
                53.486465,
                12.694616
            ]
        },
        {
            "hint": "Kqv5hi-r-YYAAAAAXAAAAAAAAADYAAAAAAAAAC4AAAAAAAAAawAAAE3pAACBIzADWLTBANRwIQNG58wAAABvAiprV7g=",
            "name": "",
            "location": [
                53.486465,
                12.694616
            ]
        },
        {
            "hint": "Kqv5hi-r-YYAAAAAXAAAAAAAAADYAAAAAAAAAC4AAAAAAAAAawAAAE3pAACBIzADWLTBANR_IQMyTMwAAABvAiprV7g=",
            "name": "",
            "location": [
                53.486465,
                12.694616
            ]
        }
    ],
    "code": "Ok"
}
```
I tried encoding for html safety (I read on an issue here), but it didn't work as well:

> http://router.project-osrm.org/route/v1/driving/polyline(k_vpAofp_Iyu%40ilAg%60Ete%40bwF_W)?overview=false

Now, if I go to google's online polyline tool: https://developers.google.com/maps/documentation/utilities/polylineutility
and use the same polyline it works as expected:

![screen shot 2018-02-20 at 14 40 23](https://user-images.githubusercontent.com/2049255/36439538-08dd53a2-164c-11e8-8f14-ef0da5a69888.jpg)

What am I missing here? Are the algorithms different? If so, how do I proceed?

Thanks!

**Comment by danpat** [comment]
@eestein You've got the coordinate order flipped.

I decoded your polyline which gives the following coordinate pairs:

```
[ [ 13.38886, 52.51704 ],
  [ 13.39763, 52.52941 ],
  [ 13.42855, 52.52322 ],
  [ 13.38885, 52.52706 ] ]
```

The polyline encoding format uses `lat,lon` internally, so the values above are "latitude, longitude".  Plotting these on a map shows that they're all out in the middle of the Arabian Sea:

<img width="578" alt="screen shot 2018-02-20 at 9 49 08 am" src="https://user-images.githubusercontent.com/1892250/36439997-66ba4d28-1623-11e8-9c2c-b307260b4b31.png">

This matches the screenshot you showed above.

If I flip the coordinates around, it looks like they're in Berlin, which looks much more sensible.

In the OSRM response, the `waypoints` coordinates are in `longitude, latitude` order - you can see that they've all snapped to the exact same location, hence the `0` distances between them in the results.

**Comment by eestein** [comment]
@danpat thanks, that was it! Any idea why the order is reversed here?

Thanks for your help!

**Comment by eestein** [comment]
@danpat thanks man, I'll take a look at that. I had no idea.
