### ISSUE TITLE
Wrong waypoint index?

### ISSUE THREAD

**Issue by eestein** [Project-OSRM/osrm-backend#4904]
I'm trying to use OSRM to get a list of locations ordered by the distance between them. For that I'm using the Trip service (https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#trip-service).

Given the encoded polyline:

`omq~Fji_vOg@sHQcnAjCtrAkCs|AvHpcBwCeeB`

I receive the following:

    "waypoints": [
    		{
    			"waypoint_index": 0,
    			"trips_index": 0,
    			"hint": "RzfEg1U3xIPaAAAAJgAAAAAAAAAAAAAANgAAAAoAAAAAAAAAAAAAAHM6AACFecb6__B-AoR5xvoQ8X4CAACPBd_PZ4A=",
    			"name": "",
    			"location": [
    				-87.656059,
    				41.873663
    			]
    		},
    		{
    			"waypoint_index": 2,
    			"trips_index": 0,
    			"hint": "OTfEg5M4xINDAwAAnwEAAAAAAAAAAAAA0AAAAGgAAAAAAAAAAAAAAHM6AACJf8b6xvF-Aoh_xvrY8X4CAADPEN_PZ4A=",
    			"name": "",
    			"location": [
    				-87.654519,
    				41.873862
    			]
    		},
    		{
    			"waypoint_index": 5,
    			"trips_index": 0,
    			"hint": "WuVchFzlXIQ6AwAAbwUAAAAAAAAAAAAAzgAAAFwBAAAAAAAAAAAAAHM6AAD3sMb6EPN-Avywxvoy8n4CAACfBd_PZ4A=",
    			"name": "",
    			"location": [
    				-87.641865,
    				41.874192
    			]
    		},
    		{
    			"waypoint_index": 1,
    			"trips_index": 0,
    			"hint": "PDfEg343xIOuAQAAggQAAAAAAAAAAAAAawAAACEBAAAAAAAAAAAAAHM6AACsfMb6su9-Aq58xvp2734CAADPEN_PZ4A=",
    			"name": "",
    			"location": [
    				-87.655252,
    				41.87333
    			]
    		},
    		{
    			"waypoint_index": 3,
    			"trips_index": 0,
    			"hint": "VuVchFjlXITqAQAA0QEAAAAAAAC1BAAAegAAAHUAAAAAAAAALQEAAHM6AACYtsb6L_J-AjK3xvoy8n4CAABvFt_PZ4A=",
    			"name": "",
    			"location": [
    				-87.640424,
    				41.873967
    			]
    		},
    		{
    			"waypoint_index": 6,
    			"trips_index": 0,
    			"hint": "6WJUhBgEhoTTBAAAdgQAAAAAAAAAAAAANAEAAB4BAAAAAAAAAAAAAHM6AAAJesb6H-x-Alh4xvoa7H4CAAB_Ft_PZ4A=",
    			"name": "",
    			"location": [
    				-87.655927,
    				41.872415
    			]
    		},
    		{
    			"waypoint_index": 4,
    			"trips_index": 0,
    			"hint": "TOVchFDlXIRTAgAAhQEAACoAAADuAAAAlAAAAGIAAAAKAAAAPAAAAHM6AAAtuMb6FvB-Aja4xvoS734CAQCPBd_PZ4A=",
    			"name": "",
    			"location": [
    				-87.640019,
    				41.87343
    			]
    		}
    	]

URL for testing: http://router.project-osrm.org/trip/v1/driving/polyline(omq~Fji_vOg@sHQcnAjCtrAkCs|AvHpcBwCeeB)?overview=false

This is how they were plotted (for better understanding):
[![enter image description here][1]][1]

If I understood the docs correctly, `waypoint_index` was supposed to provide the order of the locations by distance. If so, it doesn't seem to be working given the result. Check it here:

### Wanted

    Group 1
    lat: 41.87368, lon: -87.65606
    lat: 41.87388, lon: -87.65452
    lat: 41.87327, lon: -87.65525
    lat: 41.87241, lon: -87.65636
    
    Group 2
    lat: 41.87317, lon: -87.64001
    lat: 41.87397, lon: -87.64186
    lat: 41.87397, lon: -87.64027

### Actual

    Group 1
    lat: 41.873663, lon: -87.656059
    lat: 41.87333, lon: -87.655252
    lat: 41.873862, lon: -87.654519
    
    Group 2
    lat: 41.873967, lon: -87.640424
    lat: 41.87343, lon: -87.640019
    lat: 41.874192, lon: -87.641865
    
    Group 1
    lat: 41.872415, lon: -87.655927

As you can see the order provided by `waypoint_index` under __Actual__  does exclude the last item from its supposed group (1). **I think this might be related to the roundtrip option, is this the case?** If so, is there an option I can set on the trip service that will provide me with the result I need? 

Or, is there another service that will receive a list of locations and return them ordered by the distance between them? Given that I can't provide the start/end. 

I'd like to just send a list of locations and receive them ordered by proximity, not using roundtrip (if that's what's breaking the previous request).

Looking at the image the four locations on the left should be close to each other in the ordered list and last three as well, but because of the roundtrip option one of the first four is actually the last (not close to the first three in an ordered list).

I hope I was able to express the problem correctly... :/

Thanks!

  [1]: https://i.stack.imgur.com/n8LPH.jpg

**Comment by malizahid** [comment]
Hi Estein ,

I am somehow getting the same issue . My waypoints index from API are incorrect as per the my supplied waypoints order which i passed in URL . Did you find any solution for this ? 

Thanks ,
Ali

**Comment by danpat** [comment]
@eestein sorry I missed this ticket a while back.

OSRM contains on service to "return a list of locations ordered by distance between them".  To get that, you should try using the `/table` service - it will give you the travel time from one location to all others, then you can sort the results yourself once you have all the data.

The `/trip` plugin returns a single route line, and it will visit the waypoints in the order that minimizes the total trip duration.  There is no guarantee that the ordering of the waypoints will be in "increasing distance".

@malizahid Per your other ticket (https://github.com/Project-OSRM/osrm-backend/issues/4987), I think you want to use the `/route` service, not `/trip` - `/trip` will specifically re-order your waypoints.

**Comment by malizahid** [comment]
@danpat  Thanks for your quick response . I do understand that the waypoints sequence will be different from my supplied ordered and the result of the waypoint index order would be according to TSP algorithm .  So let me explain what i did . I used the table matrix and from that i manually applied TSP algorithm from my c# code and i got a sequence . But the sequence of waypoint index does not match either google sequence or my manual calculation sequence which i calculated from table matrix .

**Comment by eestein** [comment]
@malizahid yes, I ended up creating my own implementation using the table service. Then locally I validate the distances between each location and order them accordingly.

**Comment by danpat** [comment]
Depending on how many coordinates you supply, OSRM will either use a brute force search (<10 coordinates), or a [farthest insertion](https://users.cs.cf.ac.uk/C.L.Mumford/howard/FarthestInsertion.html) heuristic.

If you are performing your own optimization on a <10 node problem, you *should* get the same result as OSRM, assuming you also use a brute-force approach.

**Comment by eestein** [comment]
@danpat the thing is, the title of the issue is not true. I was asking a question because I didn't know how it was supposed to work. Now I understand the idea is to provide the best driving route, not to group closest points to each other. For my scenario, trip service provided me with the correct answer, it just wasn't the one I needed. 

So I decided to use the table service and locally validate them so I could have two separate groups of locations (seen on image), instead of one ordered by the distance between them.

Since for my case I need to group addresses close to each other (considering the driving distance) and create actual groups, so in my example I'd have two sets of addresses not only one, and I couldn't see an option to have OSRM provide me with that information, I ended up creating my own implementation and it's working, so it's ok :)

**Comment by danpat** [comment]
@eestein Ah, in that case, yes, the `/table` plugin plus [some clustering analysis](https://en.wikipedia.org/wiki/Cluster_analysis) sounds like what you need - OSRM doesn't offer the latter out-of-the-box, but the `/table` results would be useful input to such analysis.  Glad you figure it out.
