### ISSUE TITLE
Internal Intersections - Turn Angle Adjustments

### ISSUE THREAD

**Issue by kdiluca** [Project-OSRM/osrm-backend#4913]
In completing our Internal Intersection analysis work, we are still seeing a few cases that are being incorrectly identified as an internal intersection based on the turn angle settings.  I'd like to slightly adjust these, based on our Valhalla turn angle settings to fix cases like this:
![image](https://user-images.githubusercontent.com/12497844/36603946-58d49e02-188a-11e8-9bea-45509f6dbe41.png)
We should not be identifying an internal intersection on the road where Miraloma Dr becomes Portola Dr.

Current OSRM Turn Types:
inline guidance::DirectionModifier::Enum getTurnDirection(const double angle)
{
    // An angle of zero is a u-turn
    // 180 goes perfectly straight
    // 0-180 are right turns
    // 180-360 are left turns
    if (angle > 0 && angle < 60)
        return guidance::DirectionModifier::SharpRight;
    if (angle >= 60 && angle < 140)
        return guidance::DirectionModifier::Right;
    if (angle >= 140 && angle < 160)
        return guidance::DirectionModifier::SlightRight;
    if (angle >= 160 && angle <= 200)
        return guidance::DirectionModifier::Straight;
    if (angle > 200 && angle <= 220)
        return guidance::DirectionModifier::SlightLeft;
    if (angle > 220 && angle <= 300)
        return guidance::DirectionModifier::Left;
    if (angle > 300 && angle < 360)
        return guidance::DirectionModifier::SharpLeft;
    return guidance::DirectionModifier::UTurn;
}

Current Valhalla Turn Types:
Turn::Type Turn::GetType(uint32_t turn_degree) {
  turn_degree %= 360;
  if ((turn_degree > 349) || (turn_degree < 11)) {
    return Turn::Type::kStraight;
  } else if ((turn_degree > 10) && (turn_degree < 45)) {
    return Turn::Type::kSlightRight;
  } else if ((turn_degree > 44) && (turn_degree < 136)) {
    return Turn::Type::kRight;
  } else if ((turn_degree > 135) && (turn_degree < 170)) {
    return Turn::Type::kSharpRight;
  } else if ((turn_degree > 169) && (turn_degree < 191)) {
    return Turn::Type::kReverse;
  } else if ((turn_degree > 190) && (turn_degree < 225)) {
    return Turn::Type::kSharpLeft;
  } else if ((turn_degree > 224) && (turn_degree < 316)) {
    return Turn::Type::kLeft;
  } else if ((turn_degree > 315) && (turn_degree < 350)) {
    return Turn::Type::kSlightLeft;
  }
  throw std::runtime_error("Turn degree out of range");
}

**Comment by miccolis** [comment]
@kdiluca Did you open a PR for this? Also, I'm trying to get a understanding of who should be involved make a call on moving forward with this change. @oxidase maybe?

**Comment by kdiluca** [comment]
This issue was written to move Valhalla and OSRM logic closer. Not sure if it is needed - @dgearhart what do you think?

**Comment by dgearhart** [comment]
@kdiluca @miccolis the example above was fixed with other logic updates - I believe this can be closed
