### ISSUE TITLE
Question about versions

### ISSUE THREAD

**Issue by dinapappor** [Project-OSRM/osrm-backend#4916]
Hi! I am the port maintainer of osrm-backend in FreeBSD. https://www.freshports.org/www/osrm-backend/

Currently you have 2 versions released and tagged (v5.15.3 and v5.16.0). To which version do you recommend I upgrade the port to?

**Comment by danpat** [comment]
I just pushed the 5.15.3 release so we could update some internal systems, the fixes there will also be backported next week to create 5.16.1.

5.15.3 will be old news fairly soon, but it does contain a fix that 5.16.0 is still missing.

Both are stable, but 5.16.0 contains a known bug.

**Comment by dinapappor** [comment]
Alright, so I will at this point update to 5.15.3 and then update to 5.16.1 once that's released. Thank you. I guess you can close this issue. :)
