### ISSUE TITLE
duration is depended of previous path

### ISSUE THREAD

**Issue by morruth** [Project-OSRM/osrm-backend#4922]
I've found that if i ask routes A→B, B→C, A→B→C, and table of durations between A,B,C through API,
the duration on leg B→C is different (it's longer in A→B→C than in table or route B→C)
But I don't understand , why? ( and sum of durations in annotations is identical in both cases, but lesser)
What added to final result?

**Comment by danpat** [comment]
@morruth Without knowing your exact route and network shape, the answer is probably "the cost of uturns" and "routes prefer to continue straight at waypoints".

Try adding `continue_straight=false` to your `/route` query for A->B->C and see if that changes thing.

However, it could also be the cost of making u-turns.  Example:

```
A-----B---------+
|               |
|               |
|               |
|               |
+----------C--------+
```

In this case, A->C is 17 if you go south.  A->B is 6.  B->C 24 if you go east first, and 22 if you go west first.

If you go A->B->(east)->C, the total is 30.  A->B->(uturn, west)->C, the total is 28.

You would think that A->B (6) + B->C (west, 22) = 28 would be the route *but* when B is a waypoint and it it requires a u-turn, a "uturn penalty" is added.  If the u-turn penalty is "3" or higher, then it will mean that A->B->(east)->C would be the cheaper route, as it doesn't incur the cost of the u-turn.  That route costs 30, which does not equal the sum of A->B + B->C(west).

There are two things you can do to adjust this behaviour:

  1. Change the u-turn penalty: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L25
  2. Change the "continue_straight_at_waypoints" parameter https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L26 *or* add it to your `/route` query URL as `&continue_straight=false`.  Note that the `/table` plugin does not use this option, it's only for routes with waypoints.
