### ISSUE TITLE
Profile set on car but result for foot

### ISSUE THREAD

**Issue by saderi** [Project-OSRM/osrm-backend#4926]
I am getting wrong response for my own server.

I am using http://download.geofabrik.de/asia/iran.html

`osrm-extract -p ../osrm-backend/profiles/car.lua iran-latest.osm.pbf`
`osrm-partition iran-latest.osrm`
`osrm-customize iran-latest.osrm`
`osrm-routed --algorithm mld iran-latest.osrm`

but I am getting wrong distance, after checked with Option steps=true, it gives foot's profile result instead of car. because routeing do not care about traffic signs.

**Comment by TheMarex** [comment]
> but I am getting wrong distance, after checked with Option steps=true, it gives foot's profile result instead of car. because routeing do not care about traffic signs.

Do you mean the car route is using a foot path? Please check if the `access` tagging is correct, footpaths should be tagged with `foot=yes|no` in general.

**Comment by saderi** [comment]
Yes, exactly car route is using a foot path. do you mean in this file ?

`osrm-backend/profiles/car.lua`
I used this file without any change

**Comment by TheMarex** [comment]
@saderi I mean there might be a problem in the data from OpenStreetMap. You can investigate this on `openstreetmap.org` -> Edit and check out the tags for the street where you are seeing the problems.

**Comment by saderi** [comment]
@TheMarex When we are testing with [demo server](router.project-osrm.org) every think is Ok. this means openstreetmap is OK. is't it ?

**Comment by TheMarex** [comment]
> When we are testing with demo server every think is Ok. this means openstreetmap is OK. is't it ?

There should not be a big difference between the two except maybe data age and route weighting.

@saderi can you post the route responses for you failing query to `gist.github.com`? That would really help to figure out what is going on here.

**Comment by saderi** [comment]
I got iran-latest.osm.pbf yesterday. 

@TheMarex  This is my result https://gist.github.com/saderi/e5d7e1acd45812981bdefd63c5e8d622

**Comment by TheMarex** [comment]
@saderi I looked at [your route](http://bl.ocks.org/d/87200bdf74aaeb0db699a2f41ded4d76) and I don't see any foot paths that were used, can you please point me at which foot path was used exactly?

**Comment by saderi** [comment]
@TheMarex Is it possible test those coordinates with reverse directions ?
This is [openstreetmap](https://www.openstreetmap.org/directions?engine=osrm_car&route=38.0557%2C46.2305%3B38.0748%2C46.3861#map=13/38.0524/46.3223) result and it is Ok.

**Comment by saderi** [comment]
@TheMarex I think my config do't use highways for routing. How can I set priority on highways for routing
