### ISSUE TITLE
Demoserver not properly parsing URL control characters inside polylines

### ISSUE THREAD

**Issue by eestein** [Project-OSRM/osrm-backend#4927]
Hi, when I add two locations with the same latitude, the application throws an error:

```
{
"message":"Not enough input coordinates given; minimum number of coordinates is 2.",
"code":"InvalidInput"
}
```

The problem is... the latitudes are the same, but the longitudes are not, so they are different locations. I could understand if some rule enforced the same location not to be added twice, but that's not the case here.

Example:

Group 1
```
lat: 41.87368, lon: -87.65606
lat: 41.87388, lon: -87.65452
lat: 41.87327, lon: -87.65525
lat: 41.87241, lon: -87.65636
lat: 41.87317, lon: -87.64001
lat: 41.87397, lon: -87.64186 <-- equal latitudes, different longitudes
lat: 41.87397, lon: -87.64027 <-- equal latitudes, different longitudes
```

If you change any of the items from `41.87397` to `41.87398` the request works perfectly. For the sake of providing a more detailed issue I also tested with the same longitude and the error is the same. So if you use the same latitude or longitude but a different counterpart the error is thrown.

Here are the requests and polylines for both cases:

### Error

Repeated latitude: 41.87397 (as seen above)

Request: `http://router.project-osrm.org/table/v1/driving/polyline(omq~Fji_vOg@sHxBpCjD|EwCeeB_DpJ?}H)`
Polyline: `omq~Fji_vOg@sHxBpCjD|EwCeeB_DpJ?}H`

### Success

Different latitude: 41.87398 instead of 41.87397

Request: `http://router.project-osrm.org/table/v1/driving/polyline(omq~Fji_vOg@sHxBpCjD|EwCeeB_DpJA}H)`
Polyline `omq~Fji_vOg@sHxBpCjD|EwCeeB_DpJA}H`

If you use google's polyline tool you can see both are correct:

https://developers.google.com/maps/documentation/utilities/polylineutility

**Comment by TheMarex** [comment]
@eestein to clarify your input coordinates match the following:

http://bl.ocks.org/anonymous/raw/f0e736dadb07a0634b228e9ff55fcbf9/

**Comment by eestein** [comment]
@TheMarex yup, that's correct. But I don't follow, you're just providing visual aid, or was that supposed to be the answer? Sorry, I just didn't quite understand.

**Comment by TheMarex** [comment]
@eestein I'm just trying to make sure the polyline encoding/decoding is what we both expect.

**Comment by eestein** [comment]
@TheMarex  cool, it is :) thanks!

**Comment by danpat** [comment]
The problem here is that `expressjs` (which does the HTTP parameter parsing on the demoserver) is interpreting the `?` character as "start of query options".  The polyline string that's then decoded is truncated, and returns an invalid number of coordinates, leading to the error message reported.

IMO this is a bug on our side - the `?` character is only special if we choose it to be, we should be parsing all characters until we hit the closing `)` of the `polyline(` block.

A quick workaround on the client side is to replace `?` with `%3F`, which causes `expressjs` to treat the character "normally", but we should make it so it's not necessary (the `osrm-routed` in C++ doesn't have this problem: https://github.com/Project-OSRM/osrm-backend/blob/master/src/server/api/url_parser.cpp#L32)

**Comment by eestein** [comment]
@danpat 
Spot on! Before posting here I looked at the source code and got to that file, but could not tell what was wrong. I encoded my polyline and now it works properly, thanks!

I do agree with you the server should be prepared to receive the polyline as is, since it's how most services seem to work. If not, at least document we should encode it before sending. Thank you for your help!

One more thing though... not sure I should open a new issue for this one or if you could help me. I've noticed the lat/lon set returned from the APIs is different than the one I sent.

For instance the lat/lon set: `41.87368, -87.65606` becomes `41.873663, -87.656059` when returned from the server. 

The problem with that is I can't relate the response items with the ones sent, since they are not the same anymore. At first I thought it was converting to precision 6 somewhere and returning it, but after testing a little bit more it doesn't seem to be the case:

I tried adding a sixth digit to see if it would work with no success. The set `41.873681, -87.656061` also becomes `41.873663, -87.656059`. 

So if I had to guess, I'd say the server is trying to "snap" the sent location to a known one.

**Is there a fix for that?** **Is this a known issue or should I open a new one?**

Thanks again!
