### ISSUE TITLE
Osrm stuck at datastore

### ISSUE THREAD

**Issue by Behizz** [Project-OSRM/osrm-backend#4932]
Hello guys

I'm using OSRM v5.14.1 and I have a problem with datastore and shared memory. I've done everything that is written [here](https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory) but after a while that the system is running, it stucks at datastore and it won't be fixed until I kill the datastore and remove the locks. This happens frequently.
How can I prevent this kind of issue?

**Comment by TheMarex** [comment]
This is weird, we run `osrm` using this setup in production with frequent data updates under load and we have not seen any problems. Can you tell us more about your setup? What distribution are you using? How often do you switch data? Do you frequently experience crashes that could corrupt the locks?

**Comment by Behizz** [comment]
Thanks for the reply @TheMarex 
It's a 32 core Ubuntu Server 16.04 with 40GB RAM and the storage is a SAN storage and we didn't have any crashes that could corrupt them. 
We update the speeds every 5 minutes with a csv speed file that is around 300MB and has 9 million records. The data that is loaded into RAM is around 800MB.

**Comment by TheMarex** [comment]
Hrm yeah that is pretty close to what we run, too. :thinking: Do you maybe have some log ouput from `osrm-datastore`/`osrm-routed`? I'm interested in seeing in which phase of the update it gets stuck.

**Comment by Behizz** [comment]
@TheMarex The log doesn't say anything special. The datastore stuck at Allocating shared memory and the routed stucks at listening on port and does nothing (doesn't accept any request).

datastore output:
```
[info] RAM: peak bytes used: 1553166336
[info] Loading data into REGION_1
[info] load names from: "iran.osrm.names"
[info] Allocating shared memory of 867829136 bytes
```
routed output:

```
[info] starting up engines, v5.14.1
[info] Loading from shared memory
[info] Threads: 40
[info] IP address: 0.0.0.0
[info] IP port: 5000
```

**Comment by chaupow** [comment]
Sorry, seems this was unanswered till now.
Do you still have this problem @Behizz?
I'm going to close this for now but feel free to reopen it again.

**Comment by safe-bug** [comment]
@chaupow I still have this issue with the osrm

![screenshot from 2018-11-27 15-48-43](https://user-images.githubusercontent.com/5261029/49082075-09cbd100-f25e-11e8-9d9f-23fc43fef427.png)
