### ISSUE TITLE
How to find Tehran traffic data

### ISSUE THREAD

**Issue by smoqadam** [Project-OSRM/osrm-backend#4933]
Hi,

Thanks for your great works,

I read [this](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) section but I don't get it.

I'm looking for traffic data for Tehran. Is there any data file for Tehran traffic. If yes, where can I find it. If no, how can I generate it?

thanks

**Comment by TheMarex** [comment]
@smoqadam OSRM uses a bring-your-own-data approach to traffic as there is no publicly available source. Sorry. :-/

**Comment by chaupow** [comment]
> If no, how can I generate it?

The CSV for uploading your own traffic data needs the format
`from_osm_id, to_osm_id, edge_speed_in_km_h (,edge_rate?)`

The `edge_rate` is optional. To understand the rate, read https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md#understanding-speed-weight-and-rate

**Comment by RobertSellers** [comment]
Sorry to hijack, but, how is implemented in MLD?  Your docs suggest that the MLD pipeline is the way to go with traffic data but the link for using traffic data goes right back to CH. Most everything shows the primary command being the osrm-contract command (i.e. osrm-contract something.pbf --segment-speed-file traffic.csv).  I can't seem to run this command on osrm-customize without getting a pretty lengthy error.

**Comment by danpat** [comment]
@RobertSellers No, you've got it right - using MLD, you would do `osrm-customize --segment-speed-file foo.csv yourmap.osrm`

If you're getting an error, it would be helpful to know what it is.

**Comment by RobertSellers** [comment]
`TBB Warning: Exact exception propagation is requested by application but the linked library is built without support for it
terminate called after throwing an instance of 'osrm::util::exception'
  what():  CSV file /data/traffic.csv malformed on line 1:
 from_osm_id,to_osm_id,edge_speed_in_km_h,edge_rate
include/updater/csv_file_parser.hpp:120include/updater/csv_file_parser.hpp:85
`

**Comment by danpat** [comment]
@RobertSellers Does your CSV file have a header line?  If so, remove it, OSRM doesn't support parsing those.

**Comment by RobertSellers** [comment]
@danpat I wish that were the case.  I have tried quite a few "versions" of the csv, even making sure the single sample nodes were contained in the .pbf file extent.  Same error and not really any clue why it's not reading.

**Comment by danpat** [comment]
@RobertSellers Well, the error message from `osrm-contract` is saying that there is a header line in the CSV:

```
CSV file /data/traffic.csv malformed on line 1: from_osm_id,to_osm_id,edge_speed_in_km_h,edge_rate 
```

Our code logs the error message, and the line from the CSV file that it read https://github.com/Project-OSRM/osrm-backend/blob/faff2c774d09a7227c77ae4fa40d22d54bb00b45/include/updater/csv_file_parser.hpp#L117-L119

the line it's complaining about is:

```
from_osm_id,to_osm_id,edge_speed_in_km_h,edge_rate 
```

which looks awfully like a header line to me.

**Comment by RobertSellers** [comment]
@danpat This seems to have gotten me to the next step. Thanks for your guidance on this.
