### ISSUE TITLE
Biking on cobblestone

### ISSUE THREAD

**Issue by chaupow** [Project-OSRM/osrm-backend#4937]
<img width="422" alt="screenshot 2018-03-06 13 34 27" src="https://user-images.githubusercontent.com/804027/37032530-291589da-2143-11e8-9a33-ef6fe1f32a99.png">

This route in Berlin sent me through horrible cobblestone even though a detour over a non-cobblestone wouldn't add too much of a detour.

I think the cobblestone penalty should be higher for bike.

Todo:

- [ ] get a request with undesired behaviour
- [ ] adjust profile params

**Comment by SiarheiFedartsou** [comment]
Stale.
