### ISSUE TITLE
Confused about the access tag

### ISSUE THREAD

**Issue by donnut** [Project-OSRM/osrm-backend#4939]
It's probably a stupid question, but I'm really confused about the access `no` tag in car.lua.
My goal is to allow cars to access `ways` that have the Allowed Access tag set to `no`.

What I did is:

- remove `no` from `barrier_whitelist`
- add `no` to `access_tag_whitelist`, next to the existing `yes`
- remove `no` from the `access_tag_blacklist`

Is this enough to allow a car to access those ways?

**Comment by SiarheiFedartsou** [comment]
Stale.
