### ISSUE TITLE
incorrect duration of ferry route segments

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#494]
there's a problem with the way duration of routes are calculated:

```
  Scenario: Bike - Ferry duration, individual parts # features/bicycle/ferry.feature:117
    Given the node map                              # features/step_definitions/data.rb:9
      | x | y |  | z |  |  | v |
      | a | b |  | c |  |  | d |
    And the ways                                    # features/step_definitions/data.rb:50
      | nodes | highway | route | bicycle | duration |
      | xa    | primary |       |         |          |
      | yb    | primary |       |         |          |
      | zc    | primary |       |         |          |
      | vd    | primary |       |         |          |
      | abcd  |         | ferry | yes     | 1:00     |
    When I route I should get                       # features/step_definitions/routing.rb:190
      | from | to | route | time      |
      | a    | d  | abcd  | 3600s +-1 | <-- ok
      | a    | b  | abcd  | 600s +-1  | <-- expected ..
      | a    | b  | abcd  | 1201s     | <-- .. got
      | b    | c  | abcd  | 1200s +-1 | <-- ok
      | c    | d  | abcd  | 1800s +-1 | <-- expected ..
      | c    | d  | abcd  | 1201s     | <-- .. got
      Tables were not identical (Cucumber::Ast::Table::Different)
```

the tests are included in the commit https://github.com/DennisOSRM/Project-OSRM/commit/7493d8aa49b56c396f12704e737492c6b793aaa0

the problem is that osrm assumed each segment has the same duration/length, but this is not always the case. it's possible to route on part of the route, even when ignoreInGrid is set to true (see the test above) in whcih case the returned duration is wrong.

the test above assume that the speed is the same on all segments, which i think is a valid assumption.

**Comment by daniel-j-h** [comment]
@emiltin care to have a look again here? The `ignore_in_grid` is gone by now. There's also a discussion https://github.com/Project-OSRM/osrm-backend/commit/ed7ca73d13f3f29fe430194c59a15ca0facce43e#commitcomment-11120728 which might be related.
