### ISSUE TITLE
[Question] What is the effect of 'makePermutation' after 'bisectionToPartition' during partition

### ISSUE THREAD

**Issue by ce39906** [Project-OSRM/osrm-backend#4942]
As the topic , @oxidase,can you explain the problem for me

**Comment by oxidase** [comment]
@ce39906 the purpose of `makePermutation` is to make a nodes ID permutation for cache-friendly access to graph data. Related issue is #3779

**Comment by ce39906** [comment]
@oxidase,thanks for your answer.
