### ISSUE TITLE
Memory usage increase for routing between v5.5 and v5.16

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#4953]
I'm running OSRM `v5.5.4` on a full planet for [demo purpose](http://map.vroom-project.org/) and I'm planning an upgrade to the `v5.16` series. I successfully ran the `extract` / `contract` toolchain to use `CH` with `osrm-routed`.

I noticed a huge increase in the amount of memory required for routing only, going from 47.4G for `v5.5.4` to 93.6G for `v5.16.1`.  Of course the planet extracts used differ a bit but I've reproduced that on a single extract of France from geofabrik with the same magnitude in increase: from 2.26G with `v5.5.4` to 3.89G with `v5.16.3`.

1. Is this something that is expected, maybe due to data addition along the way?
2. Is there a way to reduce memory usage for routing, considering I don't care about guidance and turn-by-turn instructions? (I've tried dropping all names in the osm extracts without much luck so far)

**Comment by TheMarex** [comment]
> Is this something that is expected, maybe due to data addition along the way?

There are two things that are probably responsible for this:
1. Split of `duration` and `weight`, if you want to disable this you can do it [here](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L20-L21) but it also removes penalties for turning into private streets etc
2. Exclude flags, if you want to disable this you can do it [here](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L117-L122) by changing it to an empty sequence.

There might be other things that increase the memory usage but this should help.

**Comment by chaupow** [comment]
Can you see whether the memory jump happens in `extract` or `contract`?

I was looking around for this too [here](https://github.com/Project-OSRM/osrm-backend/issues/4826) and [this](https://github.com/Project-OSRM/osrm-backend/issues/4590). Does that help?

**Comment by jcoupey** [comment]
Thanks for your answers.

@chaupow I'm only concerned about memory usage for the routing phase here so the numbers reported are only for `osrm-routed` (I did not track what happened during `extract` or `contract`).

@TheMarex I'd rather not mess with the penalty logic so I'll avoid changing the `weight_name`. I guess removing the exclude layers will have a significant impact so I'll be trying that and report.

**Comment by jcoupey** [comment]
Thanks for your answers.

@chaupow I'm only concerned about memory usage for the routing phase here so the numbers reported are only for `osrm-routed` (I did not track what happened during `extract` or `contract`).

@TheMarex I'd rather not mess with the penalty logic so I'll avoid changing the `weight_name`. I guess removing the exclude layers will have a significant impact so I'll be trying that and report.

**Comment by jcoupey** [comment]
I re-run the `extract` / `contract` phases on the same planet file after emptying the `excludable` sequence in the car profile and memory usage for `osrm-routed` is down to 70.7G. This is a nice decrease (nearly 25%) from the previous value, but sadly still a bit high for me to run on the same box I used with `v5.5`.

I've also tried switching  `weight_name` from 'routability' to `duration` on smaller extracts but I don't notice any significant difference in memory usage for `osrm-routed`. I suspect this changes what values are used for routing but weights are still stored anyway?

I'm currently trying to comment out some `WayHandlers` calls in the profile when they look only guidance-related (I came up with `destinations`, `classification`, `names` and `way_classification_for_turn`). I hope this will reduce (remove?) storage of textual data.

**Comment by jcoupey** [comment]
I gave a try to `v5.11` which is the last stable before the `exclude` feature was introduced. Memory usage for `osrm-routed` decreases to 62.6G. My conclusion is that I can't upgrade OSRM *and* keep planet coverage on the same box.

I'll just keep updating the dataset for now sticking to `v5.5.4` and probably make other plans for later upgrade.
