### ISSUE TITLE
How you remove unconnected ways from entire network?

### ISSUE THREAD

**Issue by CraigglesO** [Project-OSRM/osrm-backend#4954]
I've been copiously studying your code / discussion, but during pre-processing, I can't seem to figure out how you guys determined to remove nodes not part of the main network.

For instance, walking, these nodes and edges should be removed:
![alt-1](https://cdn.pbrd.co/images/HbD5OLL.png)

Is there a simple algorithm to achieve this?

using a bellman ford, and finding the nodes that are still at INF would be a bad/slow approach but the only one that has come to mind.

Thanks,
Craig.

**Comment by danpat** [comment]
@CraigglesO The nodes and edges aren't removed.

What we do is construct the complete graph.  Then we run [Tarjan's SCC](https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm) algorithm over the graph, and flag edges with a "component id".  Nodes and edges that share a component ID are strongly connected and can be routed between.

Later, when a routing request comes in, we make sure to select candidate edges that share component IDs.  This ensures that routes get found between points, but can sometimes lead to not-immediately-obvious snapping behaviour.

There's a couple-of-year-old blog post here: https://blog.mapbox.com/robust-navigation-with-smart-nearest-neighbor-search-dbc1f6218be8  that has some animations that demonstrate the final behaviour.

In the case above, if you drop both start and end coordinates inside the park, you'll get a route that follows those trails.  However, if one of your coordinates is closer to the main road and sidewalks/footpaths, then *both* coordinates will be snapped to the main road network, and the paths in the park will be avoided completely (and it'll sort of appear like they're not considered).

**Comment by danpat** [comment]
Just for fun, here are all the edges around Seattle that are flagged as not belonging to the main road/walk network:

<img width="780" alt="screen shot 2018-03-12 at 8 05 41 pm" src="https://user-images.githubusercontent.com/1892250/37320416-dd462d96-2630-11e8-9e6b-100d25872ac5.png">

There are a lot :-)  Parks and gardens are common, as are things behind barriers (closed gates), areas flagged as private access, etc.

**Comment by danpat** [comment]
Closing, as I don't think there's anything actionable here.

**Comment by CraigglesO** [comment]
Sorry! I totally forgot to respond. Thanks for your help @danpat !!! You totally pointed me in the right direction, I still removed the "disconnected" nodes, but this made it drastically faster.
