### ISSUE TITLE
Contract failed with missing files error

### ISSUE THREAD

**Issue by neilRGS** [Project-OSRM/osrm-backend#4956]
Hi.
I hope someone can advise.

I have a 16 Core 256MB Azure machine with 500GB additional storage (d:).
I am running osrm-backend release as at Feb 1 2018

I am attempting to build the planet (ambitious!)

My .stxxl.txt file looks like this:
```
disk=d:\osrm\stxxl,295000,wincall
```
The directory, d:\osrm\ does exist and is accessible to Everyone (world-writable)
After approximately 16 to 18 hours, the extract process completes, seemingly successfully.
However, on running osrm-contract, I get the following error messages:
```
Missing/Broken File: d:\pbf\planet-latest.osrm.ebg
Missing/Broken File: d:\pbf\planet-latest.osrm.ebg_nodes
```
Indeed, these two files do not exist and whilst watching the folder periodically, I didn't see them present at any point.

Any idea why this has happened?

One thing I noticed was that no actual stxxl file gets created. Should it be created straight away or only if RAM is not sufficient and it is needed?

RAM usage got very close to 100% but didn't seem to exceed that, although it may have done during the times I was not watching.
CPU reached 100% which I would expect it to.

Many thanks for any that guidance anyone can give.

Neil.

**Comment by danpat** [comment]
@neilRGS Do you have a capture of the console output?  Please post it here.

It's possible that the file-write error handling isn't working right on Windows, and osrm-extract has silently completed but failed to write the files.  We've seen holes in our error handling like this in the past, and while I thought we'd captured them all, some situations might still be leading to unfortunately misleading "everything is OK" messages.

**Comment by neilRGS** [comment]
Thanks Dan.
Unfortunately, after that attempt, I didn't capture the console output.

The last line I do remember:
RAM: peak bytes used: <not implemented on Windows>[0m

That probably won't be of much use to you though.

I have set it running again and should it fail this time, I will make sure to grab as much of the output as I can.

Thanks,
Neil.

**Comment by oxidase** [comment]
> One thing I noticed was that no actual stxxl file gets created. Should it be created straight away or only if RAM is not sufficient and it is needed?

@neilRGS STXXL library is not used with the default cmake settings. To enable STXXL you can use `-DENABLE_STXXL=On` flag.

**Comment by neilRGS** [comment]
@oxidase Thanks for the info. I think that may be the issue, as it failed again with a Bad Allocation error. I have seen that before if the RAM was insufficient and no STXXL was in use.  The machine I have has 256GB RAM, which I thought would be enough.

I am pressing for our client to bite the bullet and let us get them a very hefty Linux box for this - to compile and serve, so for now, we can close this off.

Thanks for your help, chaps.

Neil.

**Comment by sercanerhan** [comment]
Something familiar.

In my scenerio, after executing osrm-extract, these files created:

- turkey-latest-osm.osrm             
turkey-latest-osm.osrm.names       
turkey-latest-osm.osrm.properties
- turkey-latest-osm.osrm.cnbg        
turkey-latest-osm.osrm.nbg_nodes   turkey-latest-osm.pbf

But, when I try to execute the osrm-partition, it cannot find the .ebg files.

`[error] Input file "/data/turkey-latest-osm.osrm.ebg" not found!`

**Comment by chiragpoddar12** [comment]
**[warn] Missing/Broken File: /data/mahalaxmi-map.osrm.ebg
[warn] Missing/Broken File: /data/mahalaxmi-map.osrm.ebg_nodes**

mahalaxmi-map is of 300KB and I am working with 8GB ram. Is it still small a size for 300KB osm file?

----------------------------------------------------
This is the trace of osrm-extract[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: mahalaxmi-map.osm
[info] Profile: car.lua
[info] Threads: 1
[info] Parsing in progress..
[info] input file generated by CGImap 0.6.1 (3853 thorn-02.openstreetmap.org)
[info] timestamp: n/a
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Parsing finished after 0.088627 seconds
[info] Raw input contains 1418 nodes, 103 ways, and 3 relations, 0 restrictions
[info] Sorting used nodes        ... ok, after 2e-05s
[info] Erasing duplicate nodes   ... ok, after 4e-06s
[info] Sorting all nodes         ... ok, after 3.9e-05s
[info] Building node id map      ... ok, after 6e-06s
[info] Confirming/Writing used nodes     ... ok, after 0.001949s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 101 nodes
[info] Sorting edges by start    ... ok, after 1e-05s
[info] Setting start coords      ... ok, after 1e-05s
[info] Sorting edges by target   ... ok, after 2.9e-05s
[info] Computing edge weights    ... ok, after 3.2e-05s
[info] Sorting edges by renumbered start ... ok, after 9e-06s
[info] Writing used edges       ... ok, after 0.000932s -- Processed 101 edges
[info] Writing way meta-data     ... ok, after 0.001102s -- Metadata contains << 20 entries.
[info] Sorting used ways         ... ok, after 6e-06s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 4e-06s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 3e-06s
[info] Collecting start/end information on 0 restrictions...ok, after 4e-06s
[info] Collecting start/end information on 0 restrictions...ok, after 3e-06s
[info] writing street name index ... ok, after 0.009835s
[info] extraction finished after 0.137615s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.326733
[info] Edge compression ratio: 0.326733
[info]  graph compression removed 9 annotations of 20 in 2.1e-05 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 0.000191s
[info] Segregated edges count = 0
[info] Writing nodes for nodes-based and edges-based graphs ...
[info] Geometry successfully removed:
  compressed edges: 100
  compressed geometries: 202
  longest chain length: 12
  cmpr ratio: 0.49505
  avg chain length: 2.02
[info] Generating edge expanded nodes ...
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ...
[info]
[info] Generated 50 nodes (0 of which are duplicates)  and 101 segments in edge-expanded graph
[info] Generating edge-expanded edges
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100% 100%
[info] Sorting and writing 0 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 101 edge based node segments
[info] Node-based graph contains 50 edges
[info] Edge-expanded graph ...
[info]   contains 71 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 8e-06s
[info] Generating nodes: 0.013773s
[info] Generating edges: 0.054389s
[info] Generating guidance turns
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100% 100%
[info] done.
[info] Created 7 entry classes and 28 Bearing Classes
[info] Handled: 0 of 0 lanes: -nan %.
[info] Assigned 71 turn instruction types:
[info]   new name: 2 (2.82%)
[info]   continue: 10 (14.08%)
[info]   turn: 17 (23.94%)
[info]   end of road: 5 (7.04%)
[info]   enter rotary: 8 (11.27%)
[info]   (noturn): 5 (7.04%)
[info]   (suppressed): 8 (11.27%)
[info]   exit rotary: 8 (11.27%)
[info]   (stay on roundabout): 8 (11.27%)
[info] Assigned 71 turn instruction modifiers:
[info]   uturn: 10 (14.08%)
[info]   sharp right: 3 (4.23%)
[info]   right: 8 (11.27%)
[info]   slight right: 4 (5.63%)
[info]   straight: 17 (23.94%)
[info]   slight left: 1 (1.41%)
[info]   left: 24 (33.80%)
[info]   sharp left: 4 (5.63%)
[info] Guidance turn annotations took 0.011502s
[info] Writing Intersection Classification Data
[info] ok, after 0.014474s
[info] Writing Turns and Lane Data...
[info] ok, after 0.024583s
[info] Saving edge-based node weights to file.
[info] Done writing. (0.009008)
[info] Computing strictly connected components ...
[info] Found 8 SCC (0 large, 8 small)
[info] SCC run took: 1.0658e-05s
[info] Building r-tree ...
[info] Constructing r-tree of 101 segments build on-top of 101 coordinates
terminate called after throwing an instance of 'osrm::util::exception'
  what():  File "/data/mahalaxmi-map.osrm.fileIndex" mapping failed: failed mapping file: Invalid argument: iostream errorinclude/util/mmap_file.hpp:59

[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: mahalaxmi-map.osm
[info] Profile: car.lua
[info] Threads: 1
[info] Parsing in progress..
[info] input file generated by CGImap 0.6.1 (3853 thorn-02.openstreetmap.org)
[info] timestamp: n/a
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Parsing finished after 0.088627 seconds
[info] Raw input contains 1418 nodes, 103 ways, and 3 relations, 0 restrictions
[info] Sorting used nodes        ... ok, after 2e-05s
[info] Erasing duplicate nodes   ... ok, after 4e-06s
[info] Sorting all nodes         ... ok, after 3.9e-05s
[info] Building node id map      ... ok, after 6e-06s
[info] Confirming/Writing used nodes     ... ok, after 0.001949s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 101 nodes
[info] Sorting edges by start    ... ok, after 1e-05s
[info] Setting start coords      ... ok, after 1e-05s
[info] Sorting edges by target   ... ok, after 2.9e-05s
[info] Computing edge weights    ... ok, after 3.2e-05s
[info] Sorting edges by renumbered start ... ok, after 9e-06s
[info] Writing used edges       ... ok, after 0.000932s -- Processed 101 edges
[info] Writing way meta-data     ... ok, after 0.001102s -- Metadata contains << 20 entries.
[info] Sorting used ways         ... ok, after 6e-06s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 4e-06s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 3e-06s
[info] Collecting start/end information on 0 restrictions...ok, after 4e-06s
[info] Collecting start/end information on 0 restrictions...ok, after 3e-06s
[info] writing street name index ... ok, after 0.009835s
[info] extraction finished after 0.137615s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.326733
[info] Edge compression ratio: 0.326733
[info]  graph compression removed 9 annotations of 20 in 2.1e-05 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 0.000191s
[info] Segregated edges count = 0
[info] Writing nodes for nodes-based and edges-based graphs ...
[info] Geometry successfully removed:
  compressed edges: 100
  compressed geometries: 202
  longest chain length: 12
  cmpr ratio: 0.49505
  avg chain length: 2.02
[info] Generating edge expanded nodes ...
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ...
[info]
[info] Generated 50 nodes (0 of which are duplicates)  and 101 segments in edge-expanded graph
[info] Generating edge-expanded edges
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100% 100%
[info] Sorting and writing 0 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 101 edge based node segments
[info] Node-based graph contains 50 edges
[info] Edge-expanded graph ...
[info]   contains 71 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 8e-06s
[info] Generating nodes: 0.013773s
[info] Generating edges: 0.054389s
[info] Generating guidance turns
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100% 100%
[info] done.
[info] Created 7 entry classes and 28 Bearing Classes
[info] Handled: 0 of 0 lanes: -nan %.
[info] Assigned 71 turn instruction types:
[info]   new name: 2 (2.82%)
[info]   continue: 10 (14.08%)
[info]   turn: 17 (23.94%)
[info]   end of road: 5 (7.04%)
[info]   enter rotary: 8 (11.27%)
[info]   (noturn): 5 (7.04%)
[info]   (suppressed): 8 (11.27%)
[info]   exit rotary: 8 (11.27%)
[info]   (stay on roundabout): 8 (11.27%)
[info] Assigned 71 turn instruction modifiers:
[info]   uturn: 10 (14.08%)
[info]   sharp right: 3 (4.23%)
[info]   right: 8 (11.27%)
[info]   slight right: 4 (5.63%)
[info]   straight: 17 (23.94%)
[info]   slight left: 1 (1.41%)
[info]   left: 24 (33.80%)
[info]   sharp left: 4 (5.63%)
[info] Guidance turn annotations took 0.011502s
[info] Writing Intersection Classification Data
[info] ok, after 0.014474s
[info] Writing Turns and Lane Data...
[info] ok, after 0.024583s
[info] Saving edge-based node weights to file.
[info] Done writing. (0.009008)
[info] Computing strictly connected components ...
[info] Found 8 SCC (0 large, 8 small)
[info] SCC run took: 1.0658e-05s
[info] Building r-tree ...
[info] Constructing r-tree of 101 segments build on-top of 101 coordinates
terminate called after throwing an instance of 'osrm::util::exception'
  what():  File "/data/mahalaxmi-map.osrm.fileIndex" mapping failed: failed mapping file: Invalid argument: iostream errorinclude/util/mmap_file.hpp:59
