### ISSUE TITLE
[Question] Why don't use Inertial Flow Partitioner get partitions directly?

### ISSUE THREAD

**Issue by ce39906** [Project-OSRM/osrm-backend#4959]
In  current partition work flow,  inertial flow partitioner splits the graph and store the information to BisectionID of each node . After mapping node based node to edge based node, we use function **bisectionToPartition** change BisectionID to partitions.
What puzzles me is that why didn't assign cells directly use inertial flow partitioner?
current flow : inertial flow ---> BisectionID ---> partitions. And why not like this below
inertial flow ---> partitions

@daniel-j-h @TheMarex ，could you explain that for me?

**Comment by TheMarex** [comment]
@ce39906 Inertial flow is a simple bisection based partitioning scheme so it generates `BisectionID` (basically a packed representation of the bisection). Preserving the original bisection information opens the door for implementing other partition-based algorithms like CCH. Hope this helps.
