### ISSUE TITLE
v5.14.2 is the latest?

### ISSUE THREAD

**Issue by kkdd** [Project-OSRM/osrm-backend#4962]
Hello.
Is it correct that v5.14.2 is the [latest](https://github.com/Project-OSRM/osrm-backend/releases/latest)?

**Comment by oxidase** [comment]
@kkdd no, the latest release is v5.16.4. I have just drafted the latest release and added a new step about drafting Github releases to `docs/releasing.md`  in #4964

**Comment by TheMarex** [comment]
Thanks for fixing this @oxidase!
