### ISSUE TITLE
Profile for emergency vehicles

### ISSUE THREAD

**Issue by MHarbi** [Project-OSRM/osrm-backend#4967]
I am applying map matching on GPS locations for emergency vehicles. The results are fine, but there are some splits in the resultant trajectories and changing in the roads due to breaking the rules of those vehicles. I am thinking to adjust [the car profile (.lua)](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua) to make it fit those kind of vehicles. I notice there are a great deal of parameters on that file. Any suggestion for this modification?

**Comment by rASOUL82** [comment]
Hi,
Is there any chance that you came up with a solution, as I am working on the same issue?

**Comment by parville** [comment]
Hello, would be pleased to have some news also. 

We use OSRM for EMS response teams ( called SMUR ) in France. And you ?

The fact is that even with creating a dedicated car profile we actually are often pessimist on predictive delay of arrival at destination. 

Regards

**Comment by MHarbi** [comment]
@rASOUL82 @parville 
Unfortunately, we could not come up with a car profile that imitate the emergency vehicle behavior. These vehicles sometime break the traffic rules, including driving in the reverse direction thru the road margin, in order to expedite their arrival. We could not copy such behavior.

**Comment by parville** [comment]
I agree about the fact that Emergency vehicle is sometimes out of the rules.
But, I did consider that this would be done "à la marge", _id est_ in a very few part of the trip so that normally we should be able to compute a trip and more important a delay to endpoint (to choose between several EMS teams).

Actually did not find time to study the quite important records of real trips comparing to time computed .

**Comment by Manu1400** [comment]
- [ ] first, remove this code
https://github.com/Project-OSRM/osrm-backend/blob/db7946d76246cb10a5710c8f2851997417940b55/profiles/car.lua#L109-L111

- [ ] then, remove `emergency` in this blacklist
https://github.com/Project-OSRM/osrm-backend/blob/db7946d76246cb10a5710c8f2851997417940b55/profiles/car.lua#L78-L82

- [ ] support [emergency](https://wiki.openstreetmap.org/wiki/FR:Key:emergency)=* => emergency=yes ; emergency=[designated](https://taginfo.openstreetmap.org/tags/emergency=designated)
- [ ] support [except](https://taginfo.openstreetmap.org/keys/except)=emergency

## optional
- [ ] add a small penalty for [barrier](https://taginfo.openstreetmap.org/keys/barrier)=toll_booth
