### ISSUE TITLE
osrm compute heading the close point is too low

### ISSUE THREAD

**Issue by starwin-james** [Project-OSRM/osrm-backend#4970]
DESIRED_COORDINATE_DIFFERENCE only 2 metre
LOOKAHEAD_DISTANCE_WITHOUT_LANES only 10 metre
the mini value must 15metre；and motorclass cant 1.6x15metre；and trunk 1.4x15metre。

**Comment by oxidase** [comment]
@starwin-james please could you add locations of intersections in OSM  as examples that show why new values are better than the current.
