### ISSUE TITLE
Error on list of exclude classes

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#4979]
The `http.md` docs states that the exclude parameter is an "additive list of classes to avoid" in the form `{class}[,{class}]`. Providing a single class works fine and as expected. Yet I'm getting errors when providing several classes, e.g. with the following query:

```
/route/v1/car/4.97,47.2;3.39,47.55?exclude=toll,motorway
```

On my local server running  v5.16.4, I'm getting: 

```json
{"message":"Exclude flag combination is not supported.","code":"InvalidValue"}
```
and the same code on the demo server without `message`.

I tried to dig a bit in the code where I gathered that `exclude` in `base_parameters.hpp` is really supposed to hold several values, as it's a `std::vector<std::string>`.

Is there something weird happening on the parsing side or am I missing something here?

**Comment by TheMarex** [comment]
@jcoupey sorry for the confusion, the allowed combinations are set in the profile [here](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L118-L122).

To exclude both `toll` and `motorway` at the same time you could change that to:

```lua
 excludable = Sequence {
        Set {'toll', 'motorway'}
},
```

**Comment by jcoupey** [comment]
OK, I didn't get that right, thanks for the clarification!

**Comment by tmbp95** [comment]
I was trying to execute the following by GET request: 
http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407?exclude=motorway as the [documentation ](http://project-osrm.org/docs/v5.24.0/api/#)explains (for curl requests) 
and it seems to return the exact same error that you mentioned: 
**"{"message":"Exclude flag combination is not supported.","code":"InvalidValue"}"**

Is this something expected? What am I doing wrong? 😅
Best Regards

**Comment by danpat** [comment]
@tmbp95 This likely means that the processing steps needed for excludes have not been done on the demoserver - @datendelphin ?

**Comment by mjjbell** [comment]
See #6031

**Comment by datendelphin** [comment]
The server behind router.project-osrm.org can no longer support excludes due to capacity, sorry. Each exclude uses quite a bit of resources. You will have to use your own instance where you can enable exclude classes.
