### ISSUE TITLE
Propose the creation of overpass queries repository for osrm

### ISSUE THREAD

**Issue by kaligrafy** [Project-OSRM/osrm-backend#4980]
It would be really great if someone could provide a guide/default for overpass queries to make sure we include all the required tags for importing in osrm, without superfluous osm information. Geofabrik extracts are great but sometimes, we need more smaller extracts or extracts without the unnecessary data.

**Comment by daniel-j-h** [comment]
Filter with https://github.com/Project-OSRM/osrm-backend/blob/master/taginfo.json
