### ISSUE TITLE
OSRM doesn't show actual route while plotting from osrm-backend JSON response 

### ISSUE THREAD

**Issue by fazlerabbi37** [Project-OSRM/osrm-backend#4981]
While trying to test routing using OSRM Demo server I sent GET request with the following url:

http://router.project-osrm.org/route/v1/driving/90.4007354,23.7936502;90.3925568,23.7746739?steps=true

When I plot the intersections on a web map with OpenStreetMap tiles in the background I get the following route.:

 ![issue](https://user-images.githubusercontent.com/11360512/38074012-1ed84d18-334f-11e8-83ef-37f749ffb519.JPG) 

But when I use the same cordinate in the [OSRM Demo Server's front-end](http://map.project-osrm.org/) I get the following route:

![osrm_frontend](https://user-images.githubusercontent.com/11360512/38074134-8cb8495a-334f-11e8-94e1-8738337ba16f.png)

I have also check that the JSON response from the OSRM Demo Server's front-end which is the same as the response from the url I requested. From the first screenshot we can see that the while routing the flyover is being ignored and the starting and the ending point of flyover are being connected with a straight line when plotted but that is not the case for the OSRM Demo Server's front-end. What am I doing wrong? Can anybody please help?

**Comment by chaupow** [comment]
hi @fazlerabbi37 !

Can you try adding the `overview` parameter set to `full`?
```
http://router.project-osrm.org/route/v1/driving/90.4007354,23.7936502;90.3925568,23.7746739?steps=true&overview=full
```
The default is set to `simplified` which ... returns you a simplified geometry :) 
There's documentation here:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#route-service

**Comment by fazlerabbi37** [comment]
Still not working, please see the attached plotting.

![custom_plot_1](https://user-images.githubusercontent.com/11360512/38081577-2f84735a-3366-11e8-882e-1fbc479378d1.JPG)
 
Thought I am using Google Maps Tiles but still flyover's start and end point is being connected by a single straight line.

**Comment by lamaux** [comment]
solved, see https://gis.stackexchange.com/questions/277567/osrm-doesnt-show-actual-route-while-plotting-from-osrm-backend-json-response
