### ISSUE TITLE
Error running osrm-routed [error] I/O error occurred: (possible cause: "Success")

### ISSUE THREAD

**Issue by svenvarennes** [Project-OSRM/osrm-backend#4983]
When running:
` osrm-routed --algorithm=MLD fastest/planet-latest.osrm`

I get the following error:
`[error] I/O error occurred: fastest/planet-latest.osrm.mldgr :  (possible cause: "Success") (at include/storage/tar.hpp:59)`

I already checked that the files are not corrupted, retransferred them even. The same extract works just fine on another server (the server that generated it)

Both machines are running Ubuntu 16.04 and OSRM V5.17.0

I am noticing that include/storage/tar.hpp:59 got updated 3 days ago, the files were generated on a version that didn't have these changes, could it be this change made the extract incompatible?

**Comment by svenvarennes** [comment]
Confirmed, a52213c8853aa81d8cc2c1dbf239410bbe72ec27 breaks exports.

**Comment by danpat** [comment]
@svenvarennes have you re-created the .osrm file after building from the latest code?

Although `master` has the `5.17.0` label in the configuration files, it is not yet an official release, and thus, file compatibility is not guaranteed.

If you haven't already, try re-running `osrm-extract/osrm-partition/osrm-customize` to re-create your .osrm files.

**Comment by danpat** [comment]
@TheMarex Whatever the root cause here, the error message there is a bit misleading however, we probably need to address that.

**Comment by joseflorido** [comment]
I am seeing this same error with v5.17.2. Is there a fix?
