### ISSUE TITLE
Question: how can i configure log format and destination?

### ISSUE THREAD

**Issue by GrigorievNick** [Project-OSRM/osrm-backend#4986]

**Comment by danpat** [comment]
@GrigorievNick The OSRM logger is not configurable, so if you want to change the output format and destination, you'll need to edit:

https://github.com/Project-OSRM/osrm-backend/blob/master/src/util/log.cpp

and recompile the code.  We have no plans to integrate a configurable logging subsystem into OSRM.

**Comment by GrigorievNick** [comment]
thanks a lot.
