### ISSUE TITLE
Missing exit information when steps are merged

### ISSUE THREAD

**Issue by srividyacb** [Project-OSRM/osrm-backend#4991]
In below route - the ramp information (`destination:ref` and `destination`) is picked for instruction but exit information is suppressed. [Node with exit information](https://www.openstreetmap.org/node/5521901698) which is not picked. 

Current instruction - `Take the ramp towards US 1 South: Pentagon City`
Expected instruction - `Take exit 8C on the left towards US 1 South: Pentagon City`

http://map.project-osrm.org/?z=18&center=38.869249%2C-77.047213&loc=38.870558%2C-77.046652&loc=38.868441%2C-77.048095&hl=en&alt=0

When the route endpoint is at the [first segment of the motorway_link](https://www.openstreetmap.org/way/50583099), the instruction is as expected. The suppression is happening when destination is away from the junction. 👇 

http://map.project-osrm.org/?z=18&center=38.869595%2C-77.047395&loc=38.870558%2C-77.046652&loc=38.868858%2C-77.047698&hl=en&alt=0

cc @TheMarex

**Comment by oxidase** [comment]
@srividyacb  i think it is a data issue as https://www.openstreetmap.org/way/50583099 has no `ref="US 1"` and is not merged with https://www.openstreetmap.org/way/296139720.

In OSRM [`exits` member is overwritten](https://github.com/Project-OSRM/osrm-backend/blob/01e65629ff66663106cb1f24471a1cf5ab9d6e6e/include/engine/guidance/route_step.hpp#L189)  by an empty value in `TransferSignageStrategy` as the unmerged segment has a short length.

**Comment by srividyacb** [comment]
Nice catch @oxidase 👍 The issues is fixed after adding the `ref` tag. Closing the ticket.
