### ISSUE TITLE
osrm-routed does not start if --max-matching-size and/or --max-table-size are set to 1  

### ISSUE THREAD

**Issue by svenvarennes** [Project-OSRM/osrm-backend#4994]
`osrm-routed --algorithm=MLD planet-latest.osrm -t 6 --max-matching-size 1 --max-table-size 1 `results in a quiet exit.

 On a side note: Could one disable the table / map matching endpoints entirely and if so, would that lower RAM requirements?

**Comment by danpat** [comment]
> On a side note: Could one disable the table / map matching endpoints entirely and if so, would that lower RAM requirements?

No, they are simply algorithms that run on top of the same data - we don't store table or map-matching specific properties.
