### ISSUE TITLE
Can I know what map-matching algorithm is implemented in this peoject ?

### ISSUE THREAD

**Issue by JialinYan96** [Project-OSRM/osrm-backend#5005]
`Can I know what map-matching algorithm is implemented in this peoject? Is it hmm plus vertebi?

**Comment by TheMarex** [comment]
We cite the algorithm in the implementation [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/routing_algorithms/map_matching.cpp#L447).

**Comment by JialinYan96** [comment]
thanks~
