### ISSUE TITLE
Can not load OSRM lib with Nodejs

### ISSUE THREAD

**Issue by playerthong** [Project-OSRM/osrm-backend#5011]
Hi Team 

I 'm finding the way to using OSRM lib with my website nodejs

This is my code

var OSRM = require('osrm');
var path = require('path');
var osrm = new OSRM({algorithm: 'MLD', path:"vietnam-latest.osrm",use_shared_memory:false});

But I have one bug
"Required files are missing, cannot continue.  Have all the pre-processing steps been run?"

I read code and see it
    // First, check that necessary core data is available
    if (!config.use_shared_memory && !config.storage_config.IsValid())
    {
        throw util::exception("Required files are missing, cannot continue.  Have all the "
                              "pre-processing steps been run?");
    }

How could I config storage in nodejs ?

**Comment by danpat** [comment]
@playerthong What steps did you use to prepare the datafiles?  If you're using `MLD` as the algorithm, the pre-processing steps are:

```
./osrm-extract -p your_profile.lua vietnam-latest.osm.pbf
./osrm-partition vietnam-latest.osrm
./osrm-customize vietname-latest.osrm
```

If you used the `CH` algorithm tools (`osrm-extract`/`osrm-contract`), then the error message is correct (although not exactly super clear).

**Comment by daniel-j-h** [comment]
Stale.
