### ISSUE TITLE
Too many table coordinates error in table service

### ISSUE THREAD

**Issue by ifle** [Project-OSRM/osrm-backend#5022]
Hi,

I have "Too many table coordinates" error in table service. I didn't find any info about osrm-backend limits and how to configure them?

thanks

**Comment by chaupow** [comment]
Hi @ifle !
How do you call the table service? 

* If you run tests against the demoserver (e.g. calling something like `curl 'http://router.project-osrm.org/table/v1/driving/[...]'`) then you would get rate limited because we don't want the demo server to crash.
* If you are running your own server yourself, can you paste the exact error message that you see here? 🙂

**Comment by ifle** [comment]
@chaupow Thanks for your response.
I run my own server. From server return following response
```json
{"code":"TooBig","message":"Too many table coordinates"}
```

**Comment by ifle** [comment]
Thanks.

**Comment by iedmrc** [comment]
> @ifle If you're running `osrm-routed`, do `osrm-routed --help` - you can change the default limits there.

Thanks. That suggestion solved the issue. Just make it more clear, here is a part of the output of the `osrm-routed --help` and the limits that can be changed:

```
  --max-viaroute-size arg (=500)        Max. locations supported in viaroute query
  --max-trip-size arg (=100)            Max. locations supported in trip query
  --max-table-size arg (=100)           Max. locations supported in distance table query
  --max-matching-size arg (=100)        Max. locations supported in map matching query
  --max-nearest-size arg (=100)         Max. results supported in nearest query
  --max-alternatives arg (=3)           Max. number of alternatives supported in the MLD route query
  --max-matching-radius arg (=-1)       Max. radius size supported in map matching query. Default: unlimited.
```
