### ISSUE TITLE
Difference in route detalization between osrm-routed and nodejs

### ISSUE THREAD

**Issue by tetafro** [Project-OSRM/osrm-backend#5028]
My setup: docker image osrm/osrm-backend:v5.16.1, and nodejs server from [this](https://github.com/door2door-io/osrm-express-server-demo) example (same version - 5.16.1).

I'm getting different level of route detalization (points in `routes[0].geometry.coordinates`) from osrm-routed and nodejs+osrm library. For example, this request

```
curl 'http://localhost:5002/route/v1/car/7.42193,43.73909;7.41655,43.73563?overview=simplified&geometries=geojson'
```

gives me [the following](https://www.darrinward.com/lat-long/?id=5ad27ae4813178.58925777) array of points from osrm-routed, and [this](https://www.darrinward.com/lat-long/?id=5ad27a9d5ddd59.69577065) from nodejs. You can see that the second one is more detailed.

So my question is there any way to make nodejs server gives my the same result, as osrm-routed?

**Comment by TheMarex** [comment]
@tetafro Thanks for reporting this! It could be that node wrapper does not support all the options or doesn't pass them correctly to node.

Can you try the following test case locally to verify this is not a problem with the node bindings themselves:

```js
var OSRM = require('osrm');
var osrm = new OSRM('YOUR DATA PATH');
osrm.route({
 coordinates: [[7.42193,43.73909], [7.41655,43.73563]],
 geometries: 'geojson',
 overview: 'simplified'
}, function(err, response) {
   console.log(JSON.stringify(response));
});
```

**Comment by quiqua** [comment]
The provided NodeJs wrapper uses some defaults for the options as defined here:
https://github.com/door2door-io/osrm-express-server-demo/blob/master/app/src/routes/route.js#L12-L27
```
  const options = {
    coordinates: req.body.coordinates,
    alternatives: req.body.alternatives || false,
    // Return route steps for each route leg
    steps: req.body.steps || false,
    // Return annotations for each route leg
    annotations: req.body.annotations || false,
    // Returned route geometry format. Can also be geojson
    geometries: req.body.geometries || "polyline",
    // Add overview geometry either full, simplified according to
    // highest zoom level it could be display on, or not at all
    overview: req.body.overview || "false",
    // Forces the route to keep going straight at waypoints and don't do
    // a uturn even if it would be faster. Default value depends on the profile
    continue_straight: req.body.continue_straight || false
  };
```

Especially `overview` will default to `false` in the example if you don't provide it in the JSON request payload to this `POST` endpoint.

Could you provide the payload you sent to the `POST` endpoint for the NodeJs wrapper application as well?

**Comment by tetafro** [comment]
@quiqua Sorry, you're right. I totally forgot I've changed the code to receive `GET`-requests. Looks like something wrong with `overview` paramater as you said. Tried with unchanged code from https://github.com/door2door-io/osrm-express-server-demo and everything works as expected.

Thanks for helping.
