### ISSUE TITLE
Time based roundtrips

### ISSUE THREAD

**Issue by svenvarennes** [Project-OSRM/osrm-backend#5034]
More a feature request than an issue:

Graphhopper supports roundtrips based on distance, i.e. one provides a starting point and gives a desired rountrip distance and the engine returns a route that matches the criteria.

OSRM expects one to pass waypoints to it.

Would it be possible to implement this feature in OSRM?

**Comment by danpat** [comment]
@svenvarennes Anything is possible, but it's not simple.

Most of OSRM is constructed around various solutions to the [Shortest Path Problem](https://en.wikipedia.org/wiki/Shortest_path_problem).  In particular, we structure the routing graph in certain ways to accelerate shortest path queries.  One of the downsides to doing this is that it makes some other graph exploration algorithms impossible, as the full base network isn't always available in the way you'd expect.

We've [got a ticket](https://github.com/Project-OSRM/osrm-backend/issues/4874) that describes adding support for an unaccelerated query algorithm - part of doing this would involve loading the unmodified road network, which would open the doors for all kinds of interesting algorithms to be implemented.

However, it's a fair amount of work, not just a simple tweak to the existing code.

**Comment by svenvarennes** [comment]
@danpat thank you for the explanation, really helps. Thanks ! :)
