### ISSUE TITLE
what():  failed to uncompress data: buffer error

### ISSUE THREAD

**Issue by TylerKapushinski** [Project-OSRM/osrm-backend#5038]
Hello,

I'm trying to get osrm working for a customer of mine.  When I try to extract the North America data set I'm getting this error:
```
> docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/north-america-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: north-america-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 288
[info] Parsing in progress..
[info] input file generated by osmium/1.5.1
[info] timestamp: 2018-04-17T20:44:02Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
TBB Warning: Exact exception propagation is requested by application but the linked library is built without support for it
terminate called after throwing an instance of 'tbb::captured_exception'
  what():  failed to uncompress data: buffer error
```

I looked at some of the other issues raised but couldn't find one related to mine.  There is plenty of RAM and disk space (over 400G of each).  Am I doing something wrong?

**Comment by danpat** [comment]
> failed to uncompress data: buffer error

@TylerKapushinski assuming you downloaded your data from:

http://download.geofabrik.de/north-america.html

Can you check the md5sum on the file?  Perhaps your file got corrupted.

**Comment by TylerKapushinski** [comment]
Hey @danpat,

Thanks for the response.  I re-downloaded the file, but this one also doesn't check out with the md5sum:

```
>md5sum north-america-latest.osm.pbf
3e3e8f237ddf6062383211d9f1e2f9e1  north-america-latest.osm.pbf
```

I'm going to close this issue for now until I get my check to line up with the one on geofabrik's site:

cf0bcefb5ec6b550df9d560794fd6ab6

Thanks.
