### ISSUE TITLE
Cucumber tests should have special value to delete way rags

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#5042]
When specifying ways in cucumber tests, we should have a special field vale like `<no tag>` that causes the cucumber test to generate no tag at all for that tag key.

Currently, blank columns in way tags will result in empty value tags being added.  This can be undesirable when you want blank to indicate default value, such as implied oneway values.

**Comment by emiltin** [comment]
This is already supported, by using (ni)l:
| (nil) |

Example:
https://github.com/Project-OSRM/osrm-backend/blob/faff2c774d09a7227c77ae4fa40d22d54bb00b45/features/bicycle/way.feature#L13
