### ISSUE TITLE
Take roundabout properties into account in segregated intersection classification

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#5044]
While debugging https://github.com/Project-OSRM/osrm-backend/issues/5039 I noticed that in a request like
> curl 'localhost:5000/route/v1/car/171.13076090812683,-42.584583226690306;171.12908989191055,-42.58448843359357?steps=true'

![image](https://user-images.githubusercontent.com/5521326/39044177-b9656ad6-448f-11e8-9536-330c36ac87c9.png)

 when stepping through the steps vector in post-processing, the segment that enters the roundabout is classified as `is_segregated`
> std::vector of length 8, capacity 14 = {{is_segregated = false, name = "Taramakau Highway", instruction = {type = 17 '\021', direction_modifier = 0 '\000'}}, {is_segregated = true, name = "Taramakau Highway", instruction = {type = 18 '\022', direction_modifier = 4 '\004'}}, {is_segregated = false, name = "Kumara Junction", instruction = {type = 12 '\f', direction_modifier = 5 '\005'}}, {is_segregated = false, name = "Kumara Junction", instruction = {type = 25 '\031', direction_modifier = 3 '\003'}},  ... }

@oxidase suggested that [in segregated intersection classification](https://github.com/Project-OSRM/osrm-backend/blob/6f7f8f95e0adbcfd92a3f1a90dee88277fdc4daf/src/guidance/segregated_intersection_classification.cpp#L183) a check that the segments are part of a rotary or roundabout could avoid misclassification here. The segment in this example above ^ is not technically part of the roundabout, but the following steps after it have roundabout instructions.

### Questions
- Is this intended behavior? Do we want to classify roads entering roundabouts as segregated, or do we want to leave them to emit "enter roundabout" type instructions?

cc @dgearhart @kdiluca

**Comment by dnesbitt61** [comment]
Valhalla does not classify it as an internal intersection edge (not segregated)  due to the outbound turn degree being classed as "nearly straight"  - turn degree = 347. However, I would also agree that any edge that connects to a roundabout (either entering or exiting) should not be marked as segregated.
