### ISSUE TITLE
Bad value of EARTH_RADIUS

### ISSUE THREAD

**Issue by cffk** [Project-OSRM/osrm-backend#5051]
EARTH_RADIUS is earth's radius for use in great circle calculations where the earth is treated as a sphere.  The recommended value for such a quantity is [the mean radius](https://en.wikipedia.org/wiki/Earth_radius#Mean_radius) = (2*a* + *b*)/3 = 6371 km.  The value defined in coordinate_calculation.hpp and haversine.hpp is about (3*a* + *b*)/4 = 6372.8 km.  There's no justification for this value.

**Comment by danpat** [comment]
@cffk Ultimately, the 6372.8km value comes from http://math.wikia.com/wiki/Ellipsoidal_quadratic_mean_radius

Whether it's the right thing to use or not is another question.  We have a PR open at the moment here https://github.com/Project-OSRM/osrm-backend/pull/5041 that will likely deprecate this constant.

**Comment by cffk** [comment]
Yes, I know about this source.  Unfortunately, I can't make head or tail of it.  There's a long discussion between me and Kaimbridge, the proponent of the quadratic mean radius [here](https://en.wikipedia.org/wiki/Talk:Great-circle_distance/Archive_1).  Click on the "show" for the "extended discussion".

**Comment by 1ec5** [comment]
The constant is still there:

https://github.com/Project-OSRM/osrm-backend/blob/4930d2ef054542851729c4ea5f8b7a61de2e0789/include/util/coordinate_calculation.hpp#L22-L24

But nothing uses it anymore as of #6315.
