### ISSUE TITLE
loop in route steps

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5055]
In some situations OSRM (v5.17.2 and also older versions) produces loops in route steps. As you can see in the screen shot it's looping around the intersection, although the speed of the looping segment is less than the straight route. I've seen so many of these cases in the network. What is the problem? (I can confirm it's not a network issue)

![hammer](https://user-images.githubusercontent.com/5261029/39230521-ff8c2f46-487b-11e8-971d-a3326adf67a9.png)
![hammer3](https://user-images.githubusercontent.com/5261029/39230644-7865672a-487c-11e8-8698-c0bbf422c9fd.png)

**Comment by SiarheiFedartsou** [comment]
Stale.
