### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by aginpatrick** [Project-OSRM/osrm-backend#5059]
Hi,
I'm trying to build the Dockerfile in order to include my own .lua profile. So I ran the command (in the Dockerfile directory):
   
    docker build --build-arg DOCKER_TAG=xyz -t myimage -f Dockerfile ..

but I get compilation errors:

    ...
    Scanning dependencies of target CONTRACTOR
    [ 23%] Building CXX object CMakeFiles/CONTRACTOR.dir/src/contractor/contractor.cpp.o
    [ 25%] Building CXX object CMakeFiles/GUIDANCE.dir/src/guidance/roundabout_handler.cpp.o
    [ 25%] Building CXX object     CMakeFiles/CONTRACTOR.dir/src/contractor/contractor_search.cpp.o
    [ 25%] Building CXX object CMakeFiles/EXTRACTOR.dir/src/extractor/extractor.cpp.o
    [ 25%] Building CXX object     CMakeFiles/GUIDANCE.dir/src/guidance/segregated_intersection_classification.cpp.o
    [ 26%] Building CXX object CMakeFiles/CONTRACTOR.dir/src/contractor/graph_contractor.cpp.o
    [ 28%] Building CXX object CMakeFiles/GUIDANCE.dir/src/guidance/sliproad_handler.cpp.o
    [ 28%] Built target CONTRACTOR
    [ 28%] Building CXX object CMakeFiles/EXTRACTOR.dir/src/extractor/extractor_callbacks.cpp.o
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://gcc.gnu.org/bugs.html> for instructions.
    make[2]: *** [CMakeFiles/UTIL.dir/build.make:279:     CMakeFiles/UTIL.dir/src/util/opening_hours.cpp.o] Error 4
    make[1]: *** [CMakeFiles/Makefile2:476: CMakeFiles/UTIL.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 28%] Building CXX object     CMakeFiles/GUIDANCE.dir/src/guidance/suppress_mode_handler.cpp.o
    ....
    [ 50%] Built target EXTRACTOR
    make: *** [Makefile:130: all] Error 2
    The command '/bin/sh -c NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) &&     echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories &&     apk update &&     apk upgrade &&     apk add git cmake wget make libc-dev gcc g++ bzip2-dev boost-dev zlib-dev expat-dev lua5.2-dev libtbb@testing libtbb-dev@testing &&     NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) &&     echo "Building OSRM ${DOCKER_TAG}" &&     git show --format="%H" | head -n1 > /opt/OSRM_GITSHA &&     echo "Building OSRM gitsha $(cat /opt/OSRM_GITSHA)" &&     mkdir -p build &&     cd build &&     BUILD_TYPE="Release" &&     ENABLE_ASSERTIONS="Off" &&     BUILD_TOOLS="Off" &&     case ${DOCKER_TAG} in *"-debug"*) BUILD_TYPE="Debug";; esac &&     case ${DOCKER_TAG} in *"-assertions"*) BUILD_TYPE="RelWithDebInfo" && ENABLE_ASSERTIONS="On" && BUILD_TOOLS="On";; esac &&     echo "Building ${BUILD_TYPE} with ENABLE_ASSERTIONS=${ENABLE_ASSERTIONS} BUILD_TOOLS=${BUILD_TOOLS}" &&     cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DENABLE_ASSERTIONS=${ENABLE_ASSERTIONS} -DBUILD_TOOLS=${BUILD_TOOLS} -DENABLE_LTO=On &&     make -j${NPROC} install &&     cd ../profiles &&     cp -r * /opt &&         strip /usr/local/bin/* &&     rm -rf /src /usr/local/lib/libosrm*' returned a non-zero code: 2

Anyone can help?

**Comment by danpat** [comment]
@aginpatrick You've run out of memory:

> c++: internal compiler error: Killed (program cc1plus)

This is the docker container OOM killer killing the compiler because there is no RAM left.

Increase the amount of RAM allocated to your container, and it should work.

Alternatively, you can reduce the parallelism of the build so that fewer parallel compile tasks are running.  This line:

https://github.com/Project-OSRM/osrm-backend/blob/master/docker/Dockerfile#L26

is running as many parallel tasks as your machine has CPUs - remove the `-j${NPROC}` part of that line and it will build one file at a time.  It'll take longer, but it'll need less peak RAM.

**Comment by aginpatrick** [comment]
Thanks @danpat , you were right.
