### ISSUE TITLE
Exclude classes not working

### ISSUE THREAD

**Issue by antoinegiret** [Project-OSRM/osrm-backend#5065]
Hi,

I rewrite a LUA profile containing a sequence of classes and a sequence of excludable ones (as sequence of sets, such as car profile).

```lua
local Set = require 'lib/set'
local Sequence = require 'lib/sequence'

function setup()
   return {
      --some setup

      excludable = Sequence {
         Set {'steps'},
         Set {'primary', 'steps'},
      },

      classes = Sequence {
         'steps', 'primary'
      },
   }
}

return {
   setup = setup
}
```

The route service works well, as long as I do not provide the "exclude" parameter in my query (e.g. http://127.0.0.1/route/v1/bike/0.668211,47.392147;0.678057,47.394393?exclude=steps). "Exclude flag combination is not supported" error is throwed. I look at the code and I do not understand the condition below:

https://github.com/Project-OSRM/osrm-backend/blob/faff2c774d09a7227c77ae4fa40d22d54bb00b45/include/engine/plugins/plugin_base.hpp#L54

Why throw an error if exclude is not empty ?

**Comment by TheMarex** [comment]
@antoinegiret would it be possible to get the full profile so I can investigate this locally? Thanks!

**Comment by antoinegiret** [comment]
@TheMarex I can give you the code of the setup function :

```lua
function setup()
   return {
      properties = {
         weight_name = 'cyclability',
         use_turn_restrictions = false,
         continue_straight_at_waypoint = false,
         max_speed_for_map_matching = 110/3.6, -- kmph -> m/s
         traffic_light_penalty = 2,
         turn_penalty = 6,
         u_turn_penalty = 20,
         turn_bias = 1.4,
         default_mode = mode.cycling,
         default_speed = 15,
      },

      excludable = Sequence {
         Set {'steps'},
         Set {'steps', 'primary'},
      },

      classes = Sequence {'steps', 'primary'},

      allowed_start_modes = Set {
         mode.cycling,
         mode.pushing_bike,
      },

      restrictions = Sequence {'bicycle'},
   }
end
```
and the code to determine classes:

```lua
function process_way()
  --some code

  if data.highway == 'steps' then
    if result.forward_mode ~= mode.inaccessible then
      result.forward_classes['steps'] = true
    end
    if result.backward_mode ~= mode.inaccessible then
      result.backward_classes['steps'] = true
    end
  end

  if data.highway == 'primary' then
    if result.forward_mode ~= mode.inaccessible then
      result.forward_classes['primary'] = true
    end
    if result.backward_mode ~= mode.inaccessible then
      result.backward_classes['primary'] = true
    end
  end

  --some code
end
```
Thank you :)

**Comment by antoinegiret** [comment]
I think I have found where my problem comes from. I increased in the cpp code the maximum number of classes (too low for our needs) and therefore the properties appear to be badly written in the osrm.properties file (there are still only 8 classes written). Is it due to a maximum buffer size?

**Comment by TheMarex** [comment]
@antoinegiret yes it is hard limited to 8 right now. You can modify the C++ code [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/extractor/class_data.hpp#L15-L18) to change the `ClassData` to 16 bit or 32 bit to allow 16 or 32 exclude classes.

**Comment by antoinegiret** [comment]
@TheMarex That was so easy... Its working, thanks a lot :smile:
