### ISSUE TITLE
Route over barrier=kerb

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#5067]
Someone on IRC just flagged that we're not routing over `barrier=kerb` which might be tagged e.g. on driveways. It looks like it's only whitelisted in the foot profile. Investigate.

https://github.com/Project-OSRM/osrm-backend/blob/faff2c774d09a7227c77ae4fa40d22d54bb00b45/profiles/foot.lua#L38

**Comment by MichalPP** [comment]
maybe #3890 ?
