### ISSUE TITLE
TooBig error code with no message.

### ISSUE THREAD

**Issue by eestein** [Project-OSRM/osrm-backend#5069]
I read #5022 but it looks like I'm not running into the same problem.
I also receive the `TooBig` error code, but no message, here's the returned data:

```json
{  
   "sources":null,
   "destinations":null,
   "durations":null,
   "code":"TooBig",
   "message":null,
   "waypoints":null
}
```

This is the URL:

> http://router.project-osrm.org/table/v1/driving/polyline(hne%7BBtu%7DtFghPmdD%7EloA%7Cbk%40_m_A%7D_Ufp%7B%40vsRrHchAyrw%40wca%40ABtfw%40tbc%40fDycAs%40xjAo%7DeAgoc%40nveA%7Enb%40sx%7C%40k%7Bb%40%5BfD_Na%5Ene%40j%7B%40%7BSozAsLTzm%40f_%40ud%40%60BcpJwi%40%3Fh%40eH%60e%40hReNrMgIrAhKmJf%5Br%40cH%7CCcVdGxAwwC%60VnwoAhgg%40wu%7D%40gai%40e%7CMli%40wiAlr%40t%7E%40eMfhFpA%7BIv%5Db%5D%5B%7Dt%40%7DI%7BoBnAxaCz%40kf%40%7DDffHa%7D%40_jP%7CRbdKlfG_jHkqF%60pF%7Df%40%7Eh%40paH%3F%3F%7D%7DGy%7CGvvFqgAuwHkp%40vlJzxKkaFscFquCeKdvJvlFgf%40u_Gys%40qaAl%7BA%7CbI_%60KgwF%60_KdyFAaEyeJqkFzeJbsEkqJ%7B%7BJx%7CHvvBssIaxCrv%40fJv%5D%7EsEx%7EFcpCygIunAfgHvbKo%7CG%7DjDer%40slEdv%40rQ%7EGe%5Esm%40zS%60_%40nIc%5BcOr%7E%40lJjfHdvEkhIwtF%7Di%40rc%40%7EBgM%7Ck%40uh%40npAjwBivBw%60AreGhbDspAiCsiCm_D%7Bt%40%7BY%7ElAtBh%7BCf%7DC%7B%5Bv%7C%40%60%7CAos%40eBhX_CeA%40hCm_ADfDgb%40rkA%7C%5CiVMa%40NapA%7DF%60hCcBgu%40gArk%40xBat%40zIr%7D%40gI%7DoCyTtmAv%5BumAw%5Bpd%40yB%7EnA%7Cc%40pSoNcfBgFun%40%7CKbKwAd%7BBmBud%40%60PcsAyCfn%40cDan%40mFEpKxfJmpAa_C%7D%7B%40%60_C%7C%7B%40sg%40jRkuAcrA%7E%7DBv%7E%40ioA%7DUorJxsAxtC%7CKsDbB%7DiArT%7CiAsTu%7DAwLldBbPxyAprAyqBcoBzcIws%40%3F%3Fq_Aea%40dNjPsrBlgBpjEqrAqiE%7EjAxcE%7DkAmlLzu%40bdFzDhaFw%7D%40%3F%3Fc_GyGkaEpi%40dmKm%5EiqJls%40dqHepAacC%7EVwcEvf%40apJoyA%7CgQjhB%3F%3F_%7EEx%40%7E%7DEy%40mx%5EkdJ%7Ctg%40tjOyhk%40o%7DMj%7Dj%40ztTugg%40_jUlyc%40fyUozOp_MzhLyqN%7BStXcAyw%40%7BxAinHyXdY%3F%3FtqEqkB_iEr%7EAlqEg%7BAfs%40jZnmD%7EjB_qM%7BjAntMf_DicDgbEteDfzBym%40eb%40ahLgt%40z%7EKfcApnAdX%7BgDu%7BBpb%40dDuX_Dg%7CIxd%40nrN%7EeC%7BtMwxBrpKxZomAelAxn%60%40foOyn%60%40goOr%7Ds%40%7El%60%40acv%40sz%60%40nav%40lqb%40u%7Du%40_bb%40%7EFoJxt_%40pbRrzZzuRgcBqaIm%7BA%60yClhE%7C%7CDgrb%40ioZ%7Cc%5C%60oVugYgwUjy_%40bzYgo%60%40wyY%7EBpDpg%60%40rwYkgb%40ijZjgb%40hjZz%7DBdlAjaK%7CnGihJudFem%7CAm_p%40b%7DzAlrn%40uxAm%5BomxAc%7Bm%40xsyAhaq%40_uyA%7Bnq%40_Mqe%40rSuQmPbHk%40p%7E%40hk%40rk%40wa%40kmAzB%7BRw%40B%60Kje%40e%5EoqBetH_wHx%5EjH%7CqGzhH%7DsZmlFlb%40mg%40llYtuF%7DiZ%7DiEwt%40%60Qz%7Cy%40r%7ETjVha%40yG%7CgErd%40mxGoeAvf%40p%7EB_lAyBmA)

I'm sending about 300 pairs of lat/long in the URL. I'm not sure what's going on here, is it the amount of pairs or the size of the URL, or maybe even something else?

**Comment by danpat** [comment]
@eestein The OSRM demoserver limits `/table` requests to 100 coordinates.  If you need to run requests with more than that, you'll need to run your own server.

**Comment by eestein** [comment]
@danpat I see, thanks Dan!
By the way, can I run the OSRM server on Azure or AWS for instance? Those are the only two servers that come to mind  (I have an Azure subscription and could use the free AWS tier). Do you guys provide any tutorial on how to deploy OSRM to any of those? Or any other?

Thanks man!

**Comment by danpat** [comment]
OSRM runs on most Linux boxes (and Windows apparently, although I have no experience with that).

Check https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements for some slightly dated specs on what you'll need to offer planet-scale routing.

The smaller the geographic area you need to cover, the less memory/CPU/disk you'll need.

**Comment by eestein** [comment]
@danpat sorry to chime in again :/

But I couldn't find a viable solution (for my case). According to the requirements page I'd need a server with 64GB of RAM, which is just not possible for me... it's a non profit website and the table service is seldomly used. I tried to look for alternatives like MapBox, but they have even more restrictive limits with only 25 coordinates per request. 

Do you have any suggestion on what I could do here?

I thought about breaking the requests into chunks of 100 coordinates, but I'm still trying to wrap my head around how I'd consolidate the 3 results...

I appreciate if you could point me in the right direction.

Thanks again!

**Comment by eestein** [comment]
@danpat I'd like to serve at least US and Brazil.

**Comment by danpat** [comment]
@eestein 16GB probably won't be quite enough to serve that type of geographic area.  You'll need a much bigger box to *generate* the data as well (although you can shut that down once you've generated datafiles, unless you want to update from a newer map regularly).

Unfortunately, this is what it takes to answer these types of queries.  There are simply a lot of roads in that type of geographic region, it needs a lot of memory.

You *could* try generating the data, then running it on a smaller system with swap space.  It won't run as fast, but it should work.  I don't know exactly how much slower queries will be - it will depend on how randomly they're distributed across the road network (which will affect how well the operating system page cache will function).

Unfortunately, I don't have any great answers for you here.  You could give Valhalla a try (https://github.com/valhalla/valhalla), but while it behaves a bit better under constrained memory conditions, the price you'll pay is speed - a 300x300 matrix will take a lot longer to generate.

**Comment by eestein** [comment]
@danpat thank you for your insight and well explained answer. These queries would take place quite rarely throughout the month, I imagine about 5 times a month, tops! Still, I think the host approach might be too complicated to try. 

I think I'm going to spend more time studying how can I split this matrix in 3 requests and then consolidate them...

All the best!

**Comment by danpat** [comment]
@eestein Here's a little Javascript tool I wrote to do just that: 
https://gist.github.com/danpat/83eaed80b6241310ebdf1c0bef04a524

This tool is written to hit the Mapbox Matrix API, but the interface is very similar to OSRM - adapting this script to hit the OSRM demo server should be fairly easy.

Note that the demoserver can return a HTTP 429 response at any time (rate limiting) - you may need to adapt the script to handle this error and re-try if necessary.

**Comment by eestein** [comment]
@danpat you're the man! Thank you very much! That script will come in handy :) 

>Note that the demoserver can return a HTTP 429 response at any time (rate limiting) - you may need to adapt the script to handle this error and re-try if necessary.

Thanks for the tip, I already handle HTTP 429 responses in my code.

You are truly a scholar and a gentleman.

**Comment by eestein** [comment]
@danpat I was studying your code and if I understood correctly you break the matrix into smaller requests and then merge them into a single result. But, if I understood correctly..., that wouldn't work for situation.

For example:

```
Request 1:
- Coord 1
- Coord 2
...
- Coord 10

Request 2:
- Coord 11
- Coord 12
...
- Coord 20
```

The result would provide distances only to the elements of that request. With that, I wouldn't know the distance between Coord1 and Coord 12, for instance, right?

I was studying your code because I was going to translate it to C#. I asked you a question a few weeks ago and you recommended I created my own cluster analysis implementation, and I did that...

https://github.com/Project-OSRM/osrm-backend/issues/4904#issuecomment-377980328

So now, I was trying to work with a larger set (my actual production set) and I ran into this issue. 

Anyway, this text was only to explain why I need to think about how to do that request split properly. It's not only a matter of breaking into smaller requests.

Kind regards!

**Comment by eestein** [comment]
@danpat oh, ok! I missed that! Cool, thank you! :)

**Comment by carlosen14** [comment]
@danpat , you did mention that OSRM demo server limits the queries to 100 locations at a time. I have my own on a server, this is running using Docker, it is your official instance, and also limit the HTTP queries to 100. Is there any configuration to remove the limitation? Or it is just necessary to run it on NodeJS binding C++, to use NodeJS as a HTTP interface to communicate and a bridge.

Regards!

**Comment by danpat** [comment]
@carlosen14 If you run `osrm-routed --help` it prints out command-line switches you can use to adjust the default limits.

**Comment by carlosen14** [comment]
i am not able to install `osrm`, it just appears failed to build from source, i am using node 6 LTS.. 

appart, `osrm-routed` will appear when `npm i -g osrm --build-from-source`?

**Comment by danpat** [comment]
@carlosen14 This ticket is getting off-topic.  Please open a new ticket with specific error details if you're having problems.
