### ISSUE TITLE
Error cont find file after extraction in docker run - doing something wrong?

### ISSUE THREAD

**Issue by prasath003** [Project-OSRM/osrm-backend#5070]
i have the the pbf file in folder called osmdata..

Prasaths-MacBook-Pro:~ Prasath$ docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/osmdata/india-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: india-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 4
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2018-05-07T20:00:01Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
Prasaths-MacBook-Pro:~ Prasath$ docker run -t -v $(pwd):/data osrm/osrm-backend osrm-partition /data/india-latest.osrm
[error] Input file "/data/india-latest.osrm.ebg" not found!
Prasaths-MacBook-Pro:~ Prasath$ docker run -t -v $(pwd):/data osrm/osrm-backend osrm-partition /data/osmdata/india-latest.osrm
[error] Input file "/data/india-latest.osrm.ebg" not found!

**Comment by danpat** [comment]
@prasath003 After the first run of `osrm-extract`, the error message is:

`[error] Input file "/data/berlin-latest.osrm.ebg" not found!`

But your invocation passed in `india-latest.osm.pbf`.

This makes no sense to me.  `berlin-latest` is not hard-coded anywhere in our scripts.  Are you using the official docker container?  Have you copy/pasted the error message and console output above correctly?

**Comment by prasath003** [comment]
Forgive me, tried with Berlin also I forgot to remove that, updated the error message properly now

**Comment by danpat** [comment]
@prasath003 The last message in the `osrm-extract` log is now:

```
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
```

There should be a lot more output.  It seems that the job has not completed yet.  Did you kill it, or are there any system errors logged anywhere?  I would check your docker logfiles and ensure that the container wasn't killed due to insufficient memory or some similar problem.

AFAIK, but default, Docker on MacOS only assigns 2GB of RAM to containers - this is likely not enough to run `osrm-extract` on the `india-latest.osm.pbf` file.  I suspect the `osrm-extract` process is running out of memory and being killed by the Docker daemon.  I believe docker daemon logs on macOS are available in `Console.app`.

**Comment by prasath003** [comment]
Hi, can we run this in https can any one help me with that

**Comment by daniel-j-h** [comment]
There is no HTTPS support in `osrm-routed`. Either add a proxy in between for HTTPS or use libosrm or node-osrm and put a HTTPS server on top of it.

**Comment by iedmrc** [comment]
> @prasath003 The last message in the `osrm-extract` log is now:
> 
> ```
> [info] Using profile api version 4
> [info] Using profile api version 4
> [info] Using profile api version 4
> ```
> 
> There should be a lot more output. It seems that the job has not completed yet. Did you kill it, or are there any system errors logged anywhere? I would check your docker logfiles and ensure that the container wasn't killed due to insufficient memory or some similar problem.
> 
> AFAIK, buy default, Docker on MacOS only assigns 2GB of RAM to containers - this is likely not enough to run `osrm-extract` on the `india-latest.osm.pbf` file. I suspect the `osrm-extract` process is running out of memory and being killed by the Docker daemon. I believe docker daemon logs on macOS are available in `Console.app`.

Increasing the memory limit on MacOS did the trick. Thanks!

**Comment by MobileMon** [comment]
I believe I'm running into the memory issue when trying to do the same for North America

Only problem is I don't have any more memory to give! I dedicated all 32GB of RAM that are on my machine

I noticed that when using a smaller amount, the process ends sooner than if I were to allocate more RAM so I've concluded it must be the RAM issue

What can I do?

**Comment by iedmrc** [comment]
Not sure but I think 32 GB of memory should be enough. I just increased memory to 6 GiB and that was enough to process the Turkish map. I increased the CPU to 4 core and swap to 2 GiB as well.

**Comment by wangyoucao577** [comment]
@MobileMon 32GB RAM is not enough to `osrm-extract` North America. The peak memory is about 70GB when I did it. You have to increase your memory, or just use a smaller data set.

**Comment by MobileMon** [comment]
@wangyoucao577 How am I supposed to find a computer with 70GB of RAM?!?!

Is there any way you could share me your docker file with it already extracted?

**Comment by danpat** [comment]
There are basically 3 options when you have memory limits:

  1. Rent a big machine from AWS or GCP for a short period
  2. Build OSRM with the `-DENABLE_STXXL=ON` which will move some memory work onto disk
  3. Enable a large swap partition

I'd recommend 1 or 2.  Option 3 will take a very long time to process.

**Comment by nilsnolde** [comment]
4. Try Valhalla, Graphhopper or Openrouteservice

**Comment by wangyoucao577** [comment]
@danpat Does the `-DENABLE_STXXL=ON` only affects `osrm-extract`? Can I only use it for `osrm-extract` but not use it for `osrm-customize/osrm-routed`?

**Comment by wangyoucao577** [comment]
@MobileMon Suggest to rent a big machine from AWS. The compiled data of North America is about 19GB after compress, I don't know how to share you such a big data for free.
