### ISSUE TITLE
routing on "unmaintained track roads" with unexpected results

### ISSUE THREAD

**Issue by caleb87** [Project-OSRM/osrm-backend#5071]
I tried OSRM with the following: http://map.project-osrm.org/?z=15&center=42.295929%2C-110.264540&loc=42.296104%2C-110.280762&loc=42.261887%2C-110.194605&hl=en&alt=0

It doesn't use unmaintained track roads, even though there is nothing else to use. These happens to be actual roads for the most part.

Is it possible for OSRM to use them as a last resort, rather than just going right off the main road as shown in the example?

The bottom route is from graphhopper.

![comparison](https://user-images.githubusercontent.com/6970514/39792303-d25d387a-52f4-11e8-8432-b7fd53a93a06.jpg)

https://www.openstreetmap.org/edit#map=17/42.2961236/-110.2806809

**Comment by danpat** [comment]
@caleb87 The OSRM demo server serves up routes appropriate for the `car` profile that OSRM comes with, and the decision made a long time ago was to not route over `highway=track` roads, as they're not usually passable by regular cars.

You can certainly modify your own `car.lua` profile to include these roads, but it would involve you running your own OSRM server.  We won't change this behaviour on the public OSRM demo server, it would likely be a nasty surprise to other folks who expect the demoserver to behave as it currently does.

**Comment by caleb87** [comment]
@danpat Thanks Dan! I am setting up a server, and modifying the lua profile is what I needed. I didn't see a value that would represent the "unmaintained track road" that the iD editor called it in the car.lua. 

Is there a way to easily reference and/or define these values? "unmaintained track road" = "impassable"?



```
    avoid = Set {
      'area',
      -- 'toll',    -- uncomment this to avoid tolls
      'reversible',
      'impassable',
      'hov_lanes',
      'steps',
      'construction',
      'proposed'
    },
```

**Comment by danpat** [comment]
@caleb87 The fact that it's missing from the profiles is why OSRM doesn't route over it.

You need to add a `track` entry to the speeds list, along with a speed guesstimate for that class of road:

https://github.com/Project-OSRM/osrm-backend/blob/3b4e2e83ef85983df1381dbeacd0ea5d4b9bbbcb/profiles/car.lua#L135

**Comment by caleb87** [comment]
Thanks Dan!
