### ISSUE TITLE
bicycle profile - allow bike pushing when bicycle=no and foot=yes

### ISSUE THREAD

**Issue by MichalPP** [Project-OSRM/osrm-backend#5072]
in bike profile, currently if tags disallow bicycle (eg `bicycle=no`) but allow foot (eg `foot=yes`), this way/node is blocked from routing. 

Proposed behaviour if way is disallowed for bicycle and allowed for foot:
- way: allow for routing, mode=pushing_bike, speed=walking_speed, rate=rate/4 (or another huge penalty)
- maybe differentiate penalty: if it's `bicycle=no` higher penalty than `vehicle=no`
- (if its a part of `route=bicycle`, no huge penalty; consider access tags a tagging error)
- node: allow for routing, (penalty blocked by  #3862)

implementationwise, it would be nice to be able to reach into foot profile and see `access_tags_hierarchy` and `access_tag_blacklist`.

**Comment by emiltin** [comment]
The way osm tags are defined, bicycle=no forbids bicycles, even if pushed. If pushing should be allowed, bicycle=dismount should be used instead. Unfortunately, this is tagged incorrected many places.

**Comment by matkoniecz** [comment]
Note that `bicycle=no` is a de facto equivalent of `bicycle=dismount`.

While roads/footways completely banning even pushing bicycles are quite rare compared to ones where just cycling is not allowed, bicycle=no is far more popular. It is used over [942 000 times](https://taginfo.openstreetmap.org/tags/bicycle=no#combinations) together with highway=* while bicycle=dismount just [73 000 times](https://taginfo.openstreetmap.org/tags/bicycle=dismount#combinations). It indicates that majority of mappers is using bicycle=no to indicate places where pushing bicycle is OK. 

Even if someone is using bicycle=no with intention to state that pushing/carrying bicycle there is forbidden it is impossible to distinguish bicycle=no mapped with meaning "no cycling" and "no presence of bicycles is allowed". It makes this two tags a de facto equivalent.

Usage of `bicycle=no` for "you must dismount and push bicycle" also matches how this tag is used in my region (Kraków, Poland with some limited activity elsewhere) and how I always mapped.

> Unfortunately, this is tagged incorrected many places.

At this point given tag usage I would say that claimed OSM Wiki definition is wrong.

Disclaimer: I am one of people discussing on OSM mailing list and very active editor on Wiki (for example I am the sole author of https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Ddismount )

**Comment by SiarheiFedartsou** [comment]
Stale.
