### ISSUE TITLE
Routing from exact node location

### ISSUE THREAD

**Issue by ZsoltMedgyesi-Itineris** [Project-OSRM/osrm-backend#5073]
The problem is , when i try routing from a position, which is an exact location of an intersection node, not all the ways from that node are taken into account (in the example case, the link).

Like such:
![Relavant OSM segment](https://user-images.githubusercontent.com/39079788/39811782-534be176-538a-11e8-8c0a-156798bd4474.png)

![Planning schematic](https://user-images.githubusercontent.com/39079788/39811781-5323b890-538a-11e8-92b4-7090c16e2e3e.PNG)

Notes:
- The green arrow marks the prefered outcome.
- Black line is the actual outcome (does a turn-around , when its possible, several km-s away).
- I tried with both _routability_ and _duration_ weight settings, same outcome
- The profile is based on car.lua
- Multiple alternatives are turned on, but it does not produce the prefered outcome.
- All the turn-restrictions and one-ways are checked

**Comment by oxidase** [comment]
@ZsoltMedgyesi-Itineris OSRM uses the nearest OSM way segment to the input location as a starting point of the route. If the input location is exactly at an intersection node and distances from the input point to ways segments are 0 then the first allowed segment in will be used. The order of segments is fixed during  generation of the R-tree for segments lookup  and can not be changed at the query phase. 

A possible solution can be in adding a small delta to the input coordinate in the required direction.

**Comment by ZsoltMedgyesi-Itineris** [comment]
@oxidase Thanks for the clarification. The problem is, that in the given application waypoints can be 1-10 min apart. Which means the direction of the delta in the required way cannot be defined reliably. Trying in multiple directions probably would be a solution, but not an elegant/efficient one.

May you have any other suggestion, or should we close this issue?

**Comment by oxidase** [comment]
@ZsoltMedgyesi-Itineris sorry, i don't know other "easy" solution without OSRM modifications. The correct fix would be to use multiple source/target nodes that have the same distances to the input location that sounds like an easy fix, but the devil is in the detail: 

* [`NearestPhantomNodeWithAlternativeFromBigComponent`](https://github.com/Project-OSRM/osrm-backend/blob/3b4e2e83ef85983df1381dbeacd0ea5d4b9bbbcb/include/engine/geospatial_query.hpp#L202) functions must be adjusted to return `std::pair<std::vector<PhantomNode>, std::vector<PhantomNode>>`.

* [`GetPhantomNodes`](https://github.com/Project-OSRM/osrm-backend/blob/3b4e2e83ef85983df1381dbeacd0ea5d4b9bbbcb/include/engine/plugins/plugin_base.hpp#L262) must return `std::vector<std::vector<PhantomNode>>`, also [the check that all phantom nodes are in the same component](https://github.com/Project-OSRM/osrm-backend/blob/3b4e2e83ef85983df1381dbeacd0ea5d4b9bbbcb/include/engine/plugins/plugin_base.hpp#L85-L94) must be adjusted.

* [`insertNodesInHeaps`](https://github.com/Project-OSRM/osrm-backend/blob/3b4e2e83ef85983df1381dbeacd0ea5d4b9bbbcb/include/engine/routing_algorithms/routing_base.hpp#L48) must be adjusted to insert multiple source and target phantom nodes.

* [`getNodeQueryLevel`](https://github.com/Project-OSRM/osrm-backend/blob/3b4e2e83ef85983df1381dbeacd0ea5d4b9bbbcb/include/engine/routing_algorithms/routing_base_mld.hpp#L34) functions also will need an adjustment.

So almost all parts of `osrm::engine` that are related to the initialization of routing plugins must be modified.

The current issue duplicates https://github.com/Project-OSRM/osrm-backend/issues/2167, but the previous issue was about synthetic feature tests and the current one presents a real use case. 

So I think it is ok to keep it open and close #2167 instead.
