### ISSUE TITLE
All distances and durations are zeros

### ISSUE THREAD

**Issue by spumer** [Project-OSRM/osrm-backend#5083]
I'm download and process `russia-latest` from http://download.geofabrik.de/russia.html
And use recipes from https://github.com/Project-OSRM/osrm-backend/wiki/Docker-Recipes

But any requests returng zeroes
``
{"code":"Ok","routes":[{"legs":[{"steps":[],"distance":0,"duration":0,"summary":"","weight":0},
... etc
``

Request:
``
/route/v1/driving/55.833693,49.128782;55.828106,49.124776;55.831893,49.122611;55.829578,49.118586;55.832545,49.121658;55.837358,49.116906;55.837363,49.114535;55.836393,49.112918;55.839775,49.109774;55.839572,49.102803;55.832298,49.104123;55.827874,49.103622;55.82635,49.109499;55.832298,49.104123;55.836393,49.112918;55.826276,49.111049;55.825001,49.111651;55.823287,49.125728;55.824169,49.125829;55.829087,49.130516;55.828571,49.1311;55.827727,49.129321;55.833693,49.128782;55.837323,49.124506;55.835311,49.121578;55.838329,49.121335;55.837323,49.124506;55.839102,49.124973;55.841968,49.129213;55.838329,49.121335;55.839967,49.112765;55.841579,49.101159;55.839775,49.109774;55.839967,49.112765;55.837358,49.116906;55.836706,49.114589;55.836393,49.112918;55.829578,49.118586;55.826276,49.111049?overview=false
``

Where i made mistake?

**Comment by TheMarex** [comment]
@spumer seems like you swapped latitude and longitude in your request and it is all snapping to one point.

**Comment by spumer** [comment]
@TheMarex  It's works fine for public api http://router.project-osrm.org

**Comment by TheMarex** [comment]
@spumer yes because in the public API we have a dataset of the whole world, including the regions outside of Russia. The distances you get beck are bogus however (they snap to somewhere in Kirghistan).

**Comment by spumer** [comment]
First point of route it's a part of Russia: 55.833693,49.128782 - https://en.wikipedia.org/wiki/Kazan
If swap - 49.128782, 55.833693 - it will be https://en.wikipedia.org/wiki/Kazakhstan

and for swapped addreses (in Kazakhstan) i got really strange results. I expect zeroes cause it's not Russia, but got very large distances instead.

Answer:
``
{"code":"Ok","routes":[{"geometry":"e`xsI{mzjH_e~U}us^u{W}vIdexVbh__@","legs":[{"steps":[],"distance":1067929.4,"duration":1124.3,"summary":"","weight":1124.3}],"distance":1067929.4,"duration":1124.3,"weight_name":"routability","weight":1124.3}]
``

Request:
``
/route/v1/driving/49.128782,55.833693;49.124776,55.828106
``

:(

**Comment by TheMarex** [comment]
The order is `lon,lat` for OSRM (and GeoJSON). This is what your first point looks like:

![image](https://user-images.githubusercontent.com/606968/40359166-43183440-5db1-11e8-82b0-2556af296ff3.png)

**Comment by spumer** [comment]
See the answer, same coords in each waypoint:
``
{"code":"Ok","routes":[{"legs":[{"steps":[],"distance":0,"duration":0,"summary":"","weight":0}],"distance":0,"duration":0,"weight_name":"routability","weight":0}],"waypoints":[{"hint":"vR1CgModQoAAAAAAQQAAAEsAAAAcAwAAAAAAACiDkELdpqdCxHUSRAAAAABBAAAASwAAABwDAAD_AwAAzspRA77WAwNd9FMDTqXtAgEA7xBn3Ycl","name":"","location":[55.691982,50.58323]},{"hint":"vR1CgModQoAAAAAAQQAAAEsAAAAcAwAAAAAAACiDkELdpqdCxHUSRAAAAABBAAAASwAAABwDAAD_AwAAzspRA77WAwOK3lMDqJXtAgEA7xBn3Ycl","name":"","location":[55.691982,50.58323]}]}
``

Request:

``
/route/v1/driving/55.833693,49.128782;55.828106,49.124776?overview=false
``

In container logs all fine:
``
[info] 22-05-2018 11:18:58 0.718964ms 172.21.0.1 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0 200 /route/v1/driving/55.833693,49.128782;55.828106,49.124776?overview=false
``

**Comment by spumer** [comment]
Yea, you are right.
``
points = []  # point_index -> (location.latitude, location.longitude)
``
I did not validate OSRM format

Thanks! Now works fine!
