### ISSUE TITLE
osrm-extract failing in release 5.18.0 with error "attempt to index field 'service_access_tag_blacklist'"

### ISSUE THREAD

**Issue by farialima** [Project-OSRM/osrm-backend#5084]
I've built osrm-backend-5.18.0 on https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu , I'm extracting from  http://download.geofabrik.de/north-america-latest.osm.pbf and I get a failure:

```
ubuntu@ip-172-31-42-154:/mnt/osrm/work$ ../osrm-backend-5.18.0/build/osrm-extract -p profile.lua north-america-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script profile.lua
[info] Input file: north-america-latest.osm.pbf
[info] Profile: profile.lua
[info] Threads: 16
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2018-05-23T20:00:02Z
[info] Using profile api version 2
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 2
[info] Using profile api version 2
TBB Warning: Exact exception propagation is requested by application but the linked library is built without support for it
terminate called after throwing an instance of 'tbb::captured_exception'
  what():  lua: error: /mnt/osrm/work/lib/way_handlers.lua:87: attempt to index field 'service_access_tag_blacklist' (a nil value)
Aborted (core dumped)
ubuntu@ip-172-31-42-154:/mnt/osrm/work$ 
```

**Comment by TheMarex** [comment]
What profile do you use?

**Comment by farialima** [comment]
Ah, I was using a profile based on car.lua in 5.11Ah, I was using a profile based on car.lua in 5.11 ( https://github.com/Project-OSRM/osrm-backend/blob/v5.11.0/profiles/car.lua) and there have been many changes, including the addition of a `service_access_tag_blacklist` tag... 

now shouldn't I have gotten an error earlier, knowing that the new files have `api_version = 4` and mine had `api_version = 2`

in anywise, closing the PR which is really not correct

**Comment by TheMarex** [comment]
The API version basically only governs the general functions exposed to the profile, but not the lua code itself (like tall the WayHandler stuff). Thanks for digging here, glad it works now!
