### ISSUE TITLE
Exclude flag doesn't apply more than one item

### ISSUE THREAD

**Issue by Behizz** [Project-OSRM/osrm-backend#5091]
It seems that OSRM does not apply more than one exclude class type in the runtime. When I send two flags (like ferry and toll) as documented here #4006  (separated with commas) the server returns Bad Request message and when I send them like "exclude=ferry&exclude=toll" it only excludes the first type!

This is an example from the OSRM map engine:
https://router.project-osrm.org/route/v1/driving/-76.9815444946289,38.92843409820933;-77.05089569091797,38.91427736345278?overview=false&alternatives=true&steps=true&exclude=ferry,toll

**Comment by TheMarex** [comment]
@Behizz did you extend the profile to allow for this combination? You will need to add:
```
Set {'ferry', 'toll'}
```
at [this](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L119-L121) location.

**Comment by Behizz** [comment]
@TheMarex Opps! My bad, thanks.

**Comment by AndreyGurevich** [comment]
Just to be sure: do you mean that I should add all possible combinations like this:
```
    excludable = Sequence {
        Set {'toll'},
        Set {'motorway'},
        Set {'ferry'},
        Set {'ferry', 'toll'},
        Set {'ferry', 'toll', 'motorway'},
        Set {'ferry', 'motorway'},
    },

**Comment by jcoupey** [comment]
@AndreyGurevich yes, at least this is what I gather from https://github.com/Project-OSRM/osrm-backend/issues/4979#issuecomment-376952114.

My understanding is that you'll basically be duplicating pre-processing steps in `osrm-contract` (when using CH) for all combinations, which will result in (much) longer preparation times.

**Comment by wangyoucao577** [comment]
> @AndreyGurevich yes, at least this is what I gather from [#4979 (comment)](https://github.com/Project-OSRM/osrm-backend/issues/4979#issuecomment-376952114).
> 
> My understanding is that you'll basically be duplicating pre-processing steps in `osrm-contract` (when using CH) for all combinations, which will result in (much) longer preparation times.

Any much bigger file size & memory usage.

**Comment by rodrigokuck** [comment]
Through the same idea, can I exclude highways with the tertiary flag from the route?

I put it like that in car.lua and then osrm-extract and osrm-contract but it didn't work for me, what am I doing wrong?

`classes = Sequence {'toll', 'tertiary'},
excludable = Sequence {
        Set {'toll'},
        Set {'tertiary'}
        Set {'toll', 'tertiary'},
}
`

**Comment by AndreyGurevich** [comment]
I'm not sure, but may be the root is the colon:
`classes = Sequence {'toll', 'tertiary'}, excludable = Sequence { Set {'toll'}, Set {'tertiary'} Set {'toll', 'tertiary'}, }`
`classes = Sequence {'toll', 'tertiary'}, excludable = Sequence { Set {'toll'}, Set {'tertiary'}, Set {'toll', 'tertiary'} }`

**Comment by AndreyGurevich** [comment]
I'm not sure, but may be the root is the colon:
`classes = Sequence {'toll', 'tertiary'}, excludable = Sequence { Set {'toll'}, Set {'tertiary'} Set {'toll', 'tertiary'}, }`
`classes = Sequence {'toll', 'tertiary'}, excludable = Sequence { Set {'toll'}, Set {'tertiary'}, Set {'toll', 'tertiary'} }`

**Comment by rodrigokuck** [comment]
Sorry, I copied it wrong. The points are correct. Actually the problem is that when making the route, even if I define that I want to exclude highways with the tertiary tag from the route, it always creates the same route, not excluding when I want to. I don't know if there are any more steps that I have to do besides putting tertiary in excludable?
