### ISSUE TITLE
How to get turn restriction conditionals working 

### ISSUE THREAD

**Issue by mzervens** [Project-OSRM/osrm-backend#5093]
Hi, I am having trouble getting the turn restrictions working that have time condition restrictions.

Im running these commands:

```
osrm-extract merge.osm -p car_bkp.lua --parse-conditional-restrictions
osrm-partition merge.osrm 
osrm-customize merge.osrm --parse-conditionals-from-now $(date +%s) --time-zone-file /home/london.geojson
osrm-datastore merge.osrm
osrm-routed merge.osrm
```

And heres an example of restriction in the osm file:

```
<relation id="162131" version="6" timestamp="2015-09-01T08:22:48Z" changeset="0">
		<member type="way" ref="36834407" role="from"/>
		<member type="node" ref="26609133" role="via"/>
		<member type="way" ref="36834404" role="to"/>
		<tag k="type" v="restriction"/>
		<tag k="hour_on" v="07:00"/>
		<tag k="hour_off" v="22:00"/>
		<tag k="restriction" v="no_left_turn"/>
		<tag k="restriction:conditional" v="none @ (19:00-17:00)"/>
	</relation>
```

Im not sure about the time zone file, I created my own based on the example here: https://github.com/Project-OSRM/osrm-backend/blob/master/test/data/tz/win/london.geojson

The data im working with are in https://wiki.openstreetmap.org/wiki/WikiProject_Latvia

so I created the time zone file like so (a rectangle like polygon over Latvia):
```

{
"type": "FeatureCollection",

"features": [
{ "type": "Feature", 
"properties": { "tzid": "GMT0BST" }, 
"geometry": { "type": "Polygon", 
				"coordinates": [ [ [ 19.6196212, 58.2725539 ], [ 30.3905072, 58.1131632 ], [ 29.0095676, 55.1953941 ], [ 20.2997764, 55.4583059 ], [ 19.6196212, 58.2725539 ] ] ] } }
]
}

```

As I understand when the routing server is running (currently using the demo server) it looks at the server time and checks from which region the routing request comes from to determine if the restrictions are valid?

**Comment by mzervens** [comment]
Using described commands results that the turn restrictions that have conditional time restrictions are not present, but regular turn restrictions still work.

Checked this by using osrm frontend debug map

**Comment by mzervens** [comment]
Thanks for the info, as I remember I experimented by providing different Unix timestams without desired effects but I guess I could try it again at some time

**Comment by jerrybach** [comment]
Hi ,

I got the same problem, it seems doesn't work as expected or I just did wrong things.
My steps is are:
1) Set the conditional access : access: conditional = no @ (Mo-Su 00:00-23:00) -> for testing purpose
2) Save the osm file into my local , I've checked and found it has been exported successfully 
![image](https://user-images.githubusercontent.com/48954316/90311615-e875b180-df26-11ea-8f79-627f7969844a.png)
3) osrm-extract with commend: docker run -t -v d:/osrm:/data osrm/osrm-backend osrm-extract -p /data/car.lua /data/customizemap.osm --parse-conditional-restrictions
4) osrm-contract with comment: docker run -t -v d:/osrm:/data osrm/osrm-backend osrm-contract /data/customizemap.osrm --time-zone-file /data/combined.json --parse-conditionals-from-now 1597488923
5) finally run the osrm-backend : docker run -t -i -p 5000:5000 -v d:/osrm:/data osrm/osrm-backend osrm-routed /data/customizemap.osrm

Everything works perfectly except conditional access.

Can you guys help to advise ? Do I need to modify the car.lua profile or include the "access:conditional" in wayhandlers?

Thank you very much.
