### ISSUE TITLE
Which profile does the website use

### ISSUE THREAD

**Issue by neimanpinchas** [Project-OSRM/osrm-backend#5096]
I am using a local osrm instance, but getting sometimes some bad routing results, i think its profile related

Using the standard osm data

## here is my osrm-extract commands
osrm-extract.exe ny.osm -p car.lua
osrm-partition.exe ny.osrm
osrm-customize.exe ny.osrm
osrm-routed.exe --algorith=MLD ny.osm

## here is the startup command
osrm-routed --algorithm=MLD ny.osrm

car.lua is from github
but /route/v1/driving/-74.039397,41.10445;-74.0644514829455,41.1226549247688?overview=false&alternatives=true&steps=true
Is acurate in online, but shows half the time in my local instance

Where can i get the script project-osrm.org is using?

**Comment by frodrigo** [comment]
The demo server use real time traffic in top of default profile.

**Comment by daniel-j-h** [comment]
Details in https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server
