### ISSUE TITLE
Availability of nodes location cache from lua profile

### ISSUE THREAD

**Issue by frodrigo** [Project-OSRM/osrm-backend#5098]
Maybe I'm wrong, but the location cache is not available from lua.
Currently without disabling location cache
```lua
node:location():valid() -- With node a NodeRef from way if false
```

The location of way node's can be available using the cache and not by preprocessing the .pbf with `osmium add-locations-to-ways`?

**Comment by alexkavon** [comment]
Updating because solution was never listed, but you need to add the node location data using the `osmium-tool`, for example:

```
osmium add-locations-to-ways -n -o germany-low.osm.pbf germany.osm.pbf
```

**Comment by danpat** [comment]
Actually, there's another way:

```
$ echo '{"type":"FeatureCollection","features":[]}' > empty.geojson
$ ./osrm-extract --location-dependent-data empty.geojson -p profiles/car.lua yourmap.osm.pbf
```

Using the `--location-dependent-data` flag will cause OSRM to internally cache locations and make them available in the Lua environment.  We should just make a flag that enables this on its own.
