### ISSUE TITLE
The 'table' API can return negative distances.

### ISSUE THREAD

**Issue by barqshasbite** [Project-OSRM/osrm-backend#5106]
Running the latest release, v5.18.0, it is possible for the newly improved 'table' API to return negative distance values.

For example, a simple 1x1 table for relatively close coordinates:
http://localhost:5000/table/v1/CAR/103.904473,1.399301;103.904673,1.399722?annotations=distance,duration&sources=0&destinations=1

Results in:
{"code":"Ok","sources":[{"name":"","location":[103.904473,1.399301]}],"destinations":[{"name":"","location":[103.904673,1.399722]}],"durations":[[12.4]],"distances":[[-86.8]]}

**Comment by barqshasbite** [comment]
I should also note that the result of a regular 'route' API call for the same coordinates is:

{"code":"Ok","routes":[{"geometry":"shpG}ydyRsAg@","legs":[{"steps":[],"distance":51.8,"duration":12.4,"summary":"","weight":24.9}],"distance":51.8,"duration":12.4,"weight_name":"routability","weight":24.9}],"waypoints":[{"name":"","location":[103.904473,1.399301]},{"name":"","location":[103.904673,1.399722]}]}

The duration value matches the 'table' API, but the distance value does not. The value of 51.8 matches what Google Maps returns, to the 'route' API is correct.

**Comment by TheMarex** [comment]
Thank you for reporting this! This seems bad indeed, we will investigate.

**Comment by TheMarex** [comment]
I think I have a fix for this in https://github.com/Project-OSRM/osrm-backend/pull/5060

**Comment by barqshasbite** [comment]
I have tested with the latest master and the issue of negative distances appears to be resolved. I tested it with over 250,000 coordinate pairs that were previously returning negative distance values, and all of them are now returning positive values. There are, however, still some small differences in the distance values returned by the 'table' API and the 'route' API, as described in issue #5151. Even in cases where there is only one possible way to get from the origin to the destination. In these cases, the durations are the same, only distance differs.

**Comment by TheMarex** [comment]
@barqshasbite thanks for checking! Closing here in favor of #5151.

**Comment by alain-andre** [comment]
Hi @barqshasbite I'm having negative value for distance matrix with those coordinates *50.627582,1.655818,50.628006,1.656199*

Can you have a check on your test with them to be sure I'm not doing something wrong ? I'm using version 5.19 of the osrm-backend
