### ISSUE TITLE
Steps array empty when using Curl

### ISSUE THREAD

**Issue by Yamakasi** [Project-OSRM/osrm-backend#5107]
Hi,

When access a URL with ?steps=true using a browser I get a steps array but when request the same URL using curl the steps array is empty.

Is this a bug ?

**Comment by TheMarex** [comment]
@Yamakasi can you give us an example URL?

**Comment by TheMarex** [comment]
@Yamakasi works for me using `curl`. Please note that you most likely are hitting a `Too Many Requests` error since the demo server seems pretty maxed out right now.

**Comment by Yamakasi** [comment]
@TheMarex I know about the `Too Many Requests` but that is not the case. It's happening on the Json response and I have someone else let it test also which came with the same result. The rest of the data, up to `Ok` is there.

**Comment by TheMarex** [comment]
@Yamakasi are you sure you did the escaping right? In bash you should put the URL in `"`.

**Comment by Yamakasi** [comment]
@TheMarex It should be, I'm calling it from PHP. I'm compiling my own OSRM server at the moment to see what's happening then.

**Comment by Yamakasi** [comment]
@TheMarex update: Own compiled server, same issue (much faster tho 👍)

**Comment by danpat** [comment]
@Yamakasi Can you post the sample code you're using to make the request - the URL format looks fine to me, and works from the command-line when properly quoted.

**Comment by Yamakasi** [comment]
@danpat @TheMarex It's working! There was a little fault in my code, I was parsing the URL as debug with the parameters but it was used without them in CURL, I pasted it after the curl command so it was not added to the URL variable.

Sorry for the commotion but at least I installed my own OSRM server because of it with success!! 

Thanks for the help!
