### ISSUE TITLE
Trying to Load OSRM for Bengaluru error

### ISSUE THREAD

**Issue by SoumyajyotiBanerjee** [Project-OSRM/osrm-backend#5110]
CF-LP00043:india soumyajyoti$ docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/bengaluru_now.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: bengaluru_now.osm.pbf
[info] Profile: car.lua
[info] Threads: 4
[info] Parsing in progress..
[info] input file generated by osmium/1.2.1
[info] timestamp: n/a
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 1.16795 seconds
[info] Raw input contains 261266 nodes, 51815 ways, and 56 relations, 73 restrictions
[info] Sorting used nodes        ... ok, after 0.004129s
[info] Erasing duplicate nodes   ... ok, after 0.000855s
[info] Sorting all nodes         ... ok, after 0.000457s
[info] Building node id map      ... ok, after 0.000826s
[info] Confirming/Writing used nodes     ... ok, after 0.787385s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 159958 nodes
[info] Sorting edges by start    ... ok, after 0.009499s
[info] Setting start coords      ... ok, after 0.009977s
[info] Sorting edges by target   ... ok, after 0.010138s
[info] Computing edge weights    ... ok, after 0.032986s
[info] Sorting edges by renumbered start ... ok, after 0.009303s
[info] Writing used edges       ... ok, after 0.040231s -- Processed 190028 edges
[info] Writing way meta-data     ... ok, after 0.003053s -- Metadata contains << 40626 entries.
[info] Sorting used ways         ... ok, after 0.002026s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0.000418s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 5e-06s
[info] Collecting start/end information on 73 restrictions...ok, after 0.00117s
[info] Collecting start/end information on 73 restrictions...ok, after 6.3e-05s
[info] writing street name index ... ok, after 0.004087s
[info] extraction finished after 2.09806s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.49925
[info] Edge compression ratio: 0.578475
[info]  graph compression removed 38619 annotations of 40626 in 0.026338 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 0.334008s
[info] Segregated edges count = 1169
[info] Writing nodes for nodes-based and edges-based graphs ...
[info] Geometry successfully removed:
  compressed edges: 219900
  compressed geometries: 380078
  longest chain length: 355
  cmpr ratio: 0.578565
  avg chain length: 1.72841
[info] Generating edge expanded nodes ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ... 
[info] 
[info] Generated 212839 nodes (0 of which are duplicates)  and 190022 segments in edge-expanded graph
[info] Generating edge-expanded edges 
[info] . 10% . 20% . 30% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 56907, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=12.985786&mlon=77.558501
. 40% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 77320, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=12.963108&mlon=77.473392
 50% . 60% . 70% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 119104, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=13.045464&mlon=77.513671
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 119146, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=13.048513&mlon=77.514737
. 80% . 90% .
[info] Sorting and writing 0 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 190022 edge based node segments
[info] Node-based graph contains 212726 edges
[info] Edge-expanded graph ...
[info]   contains 448258 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 0.003183s
[info] Generating nodes: 0.072788s
[info] Generating edges: 2.46385s
[info] Generating guidance turns 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .
[info] done.
[info] Created 50 entry classes and 2572 Bearing Classes
[info] Handled: 0 of 88 lanes: 0 %.
[info] Assigned 508558 turn instruction types:
[info]   new name: 5483 (1.08%)
[info]   continue: 16262 (3.20%)
[info]   turn: 226301 (44.50%)
[info]   merge: 230 (0.05%)
[info]   on ramp: 149 (0.03%)
[info]   off ramp: 135 (0.03%)
[info]   fork: 968 (0.19%)
[info]   end of road: 89152 (17.53%)
[info]   enter roundabout: 60 (0.01%)
[info]   enter and exit roundabout: 3 (0.00%)
[info]   enter rotary: 26 (0.01%)
[info]   enter and exit rotary: 4 (0.00%)
[info]   enter roundabout turn: 4 (0.00%)
[info]   (noturn): 3433 (0.68%)
[info]   (suppressed): 166065 (32.65%)
[info]   exit roundabout: 69 (0.01%)
[info]   exit rotary: 27 (0.01%)
[info]   exit roundabout turn: 4 (0.00%)
[info]   (stay on roundabout): 91 (0.02%)
[info]   (sliproad): 92 (0.02%)
[info] Assigned 508558 turn instruction modifiers:
[info]   uturn: 15509 (3.05%)
[info]   sharp right: 5040 (0.99%)
[info]   right: 151726 (29.83%)
[info]   slight right: 5162 (1.02%)
[info]   straight: 166024 (32.65%)
[info]   slight left: 5212 (1.02%)
[info]   left: 154774 (30.43%)
[info]   sharp left: 5111 (1.00%)
[info] Guidance turn annotations took 1.94893s
[info] Writing Intersection Classification Data
[info] ok, after 0.009602s
[info] Writing Turns and Lane Data...
[info] ok, after 0.031467s
[info] Saving edge-based node weights to file.
[info] Done writing. (0.015583)
[info] Computing strictly connected components ...
[info] Found 404 SCC (1 large, 403 small)
[info] SCC run took: 0.0157363s
[info] Building r-tree ...
[info] Constructing r-tree of 190022 segments build on-top of 159958 coordinates
[info] finished r-tree construction in 0.059009 seconds
[info] Writing edge-based-graph edges       ... 
[info] ok, after 2.57286s
[info] Processed 448258 edges
[info] Expansion: 29680 nodes/sec and 39492 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "/data/bengaluru_now.osrm"
[info] RAM: peak bytes used: 106745856
CF-LP00043:india soumyajyoti$ docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed --algorithm mld bengaluru_now.osrm
[warn] Missing/Broken File: bengaluru_now.osrm.ramIndex
[warn] Missing/Broken File: bengaluru_now.osrm.fileIndex
[warn] Missing/Broken File: bengaluru_now.osrm.edges
[warn] Missing/Broken File: bengaluru_now.osrm.geometry
[warn] Missing/Broken File: bengaluru_now.osrm.turn_weight_penalties
[warn] Missing/Broken File: bengaluru_now.osrm.turn_duration_penalties
[warn] Missing/Broken File: bengaluru_now.osrm.datasource_names
[warn] Missing/Broken File: bengaluru_now.osrm.names
[warn] Missing/Broken File: bengaluru_now.osrm.properties
[warn] Missing/Broken File: bengaluru_now.osrm.icd
[warn] Missing/Broken File: bengaluru_now.osrm.maneuver_overrides
[error] Required files are missing, cannot continue

Though I have file in docker still it's throwing error.

**Comment by danpat** [comment]
@SoumyajyotiBanerjee You are missing two steps.

```
docker run -t -i -v $(pwd):/data osrm/osrm-backend osrm-partition bengaluru_now.osrm

docker run -t -i -v $(pwd):/data osrm/osrm-backend osrm-customize bengaluru_now.osrm
```

The `osrm-partition` and `osrm-customize` tools must be run on the data after `osrm-extract`, but before you can run `osrm-routed --algorithm mld`.

**Comment by danpat** [comment]
@SoumyajyotiBanerjee Check the file paths in your command line.  You probably need to refer to the file as `/data/bengaluru_now.osrm`.

https://github.com/Project-OSRM/osrm-backend/blob/master/docker/Dockerfile#L43

The default working directory inside the docker container is `/opt`, so if your files aren't in `/opt` (and hint: they aren't), then you'll need to refer to them by absolute full pathname.

**Comment by SoumyajyotiBanerjee** [comment]
@danpat  Is duration will give me the distance???

curl "http://127.0.0.1:5000/table/v1/driving/80.220010,30.897650;80.324120,10.811040?sources=0"
{"code":"Ok","durations":[[0,4586.3]],"destinations":[{"hint":"h14CgPleAoAAAAAAKQAAAAAAAAClFgAAAAAAAIvykkIAAAAAOH8jRgAAAAApAAAAAAAAAKUWAABNAAAA1VKfBOXhygBqD8gE8nXXAQAALwpC3pl5","name":"Doddaballapur Road","location":[77.550293,13.296101]},{"hint":"lIsAgKSLAIAMAAAAAAAAAHkWAAAAAAAAwttYQQAAAACwnMdFAAAAAAwAAAAAAAAAeRYAAAAAAABNAAAAiuyiBDG8wwAYpskEoPakALYADwVC3pl5","name":"","location":[77.78625,12.827697]}],"sources":[{"hint":"h14CgPleAoAAAAAAKQAAAAAAAAClFgAAAAAAAIvykkIAAAAAOH8jRgAAAAApAAAAAAAAAKUWAABNAAAA1VKfBOXhygBqD8gE8nXXAQAALwpC3pl5","name":"Doddaballapur Road","location":[77.550293,13.296101]}]}CF-LP00043:

??
"durations":[[0,4586.3]]

**Comment by danpat** [comment]
@SoumyajyotiBanerjee add the `?annotations=durations,distances` parameter to the request and you'll get distances back as well.
