### ISSUE TITLE
distance returning null

### ISSUE THREAD

**Issue by SoumyajyotiBanerjee** [Project-OSRM/osrm-backend#5111]
curl "http://127.0.0.1:5000/table/v1/driving/77.644811,12.89188;77.629451099999997,12.949284?sources=0"
{"code":"Ok","durations":[[0,null]],"destinations":[{"hint":"AY4AgMsUAIAbAAAADQAAACYAAADCAAAA6NaZQdNyC0E1XNRBNVzUQRsAAAANAAAAJgAAAMIAAABNAAAA-sOgBOW2xAALxKAE6LbEAAEAfwrX7_PR","name":"","location":[77.644794,12.891877]},{"hint":"RooBgFiKAYAUAAAAMQAAAEoAAAAAAAAAI1S6QX4vVkKE9KRCAAAAABQAAAAxAAAASgAAAAAAAABNAAAAuoGgBF2TxQALiKAEJJfFAAIATwnX7_PR","name":"Ejipura Main Road","location":[77.627834,12.948317]}],"sources":[{"hint":"AY4AgMsUAIAbAAAADQAAACYAAADCAAAA6NaZQdNyC0E1XNRBNVzUQRsAAAANAAAAJgAAAMIAAABNAAAA-sOgBOW2xAALxKAE6LbEAAEAfwrX7_PR","name":"","location":[77.644794,12.891877]}]}CF-LP00043:git soumyajyoti$ curl "http://127.0.0.1:5000/table/v1/driving/77.644794,12.891877;77.627834,12.948317?sources=0"
{"code":"Ok","durations":[[0,null]],"destinations":[{"hint":"AY4AgMsUAIAbAAAADQAAACYAAADCAAAA6NaZQdNyC0E1XNRBNVzUQRsAAAANAAAAJgAAAMIAAABNAAAA-sOgBOW2xAD6w6AE5bbEAAEAfwrX7_PR","name":"","location":[77.644794,12.891877]},{"hint":"RooBgFiKAYAUAAAAMQAAAEoAAAAAAAAAI1S6QX4vVkKE9KRCAAAAABQAAAAxAAAASgAAAAAAAABNAAAAuoGgBF2TxQC6gaAEXZPFAAIATwnX7_PR","name":"Ejipura Main Road","location":[77.627834,12.948317]}],"sources":[{"hint":"AY4AgMsUAIAbAAAADQAAACYAAADCAAAA6NaZQdNyC0E1XNRBNVzUQRsAAAANAAAAJgAAAMIAAABNAAAA-sOgBOW2xAD6w6AE5bbEAAEAfwrX7_PR","name":"","location":[77.644794,12.891877]}]}CF-LP00043:git soumyajyoti$ 

Can you please explain what is wrong in this?
I am running the server using:

run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed --algorithm mld /data/bengaluru_now.osrm

**Comment by AtnesNess** [comment]
you need to be more attentive while reading docs :) 
>durations array of arrays that stores the matrix in row-major order. durations[i][j] gives the travel time from the i-th waypoint to the j-th waypoint. Values are given in seconds. Can be **null** if no route between i and j can be found.
distances array of arrays that stores the matrix in row-major order. distances[i][j] gives the travel distance from the i-th waypoint to the j-th waypoint. Values are given in meters. Can be **nul** l if no route between i and j can be found. Note that computing the distances table is currently only implemented for CH. If annotations=distance or annotations=duration,distance is requested when running a MLD router, a NotImplemented error will be returned.


https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

**Comment by SoumyajyotiBanerjee** [comment]
@AtnesNess  How can i get distance using this??
Tried this:
curl "http://localhost:5000/table/v1/distance/-118.241483,34.072504;-118.329545,34.092053?sources=0&output_components=distances"
{"message":"Query string malformed close to position 72","code":"InvalidQuery"}

Not working..

**Comment by SoumyajyotiBanerjee** [comment]
and if this is lat,long or long,lat???

**Comment by AtnesNess** [comment]
@SoumyajyotiBanerjee I meant that line of docs: `Can be null if no route between i and j can be found`

**Comment by AtnesNess** [comment]
@SoumyajyotiBanerjee long, lat

**Comment by AtnesNess** [comment]
@SoumyajyotiBanerjee what is  `output_components`  exactly? You must have mistaken and wanted to write `annotations` ?:)

**Comment by SoumyajyotiBanerjee** [comment]
@AtnesNess  if there is no approx. distance measure.

**Comment by SiarheiFedartsou** [comment]
Stale.
