### ISSUE TITLE
cmake cannot find pthreads?

### ISSUE THREAD

**Issue by retorquere** [Project-OSRM/osrm-backend#5118]
cmake has problems finding pthreads for me:

```
Linking C executable cmTryCompileExec703583191
/cm/shared/apps/cmake-3.1.3/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec703583191.dir/link.txt --verbose=1
/cm/local/apps/gcc/6.3.0/bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create   CMakeFiles/cmTryCompileExec703583191.dir/CheckFunctionExists.c.o  -o cmTryCompileExec703583191 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: Leaving directory `/scistor/guest/ehs215/osrm-backend/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTryCompileExec703583191] Error 1
gmake: *** [cmTryCompileExec703583191/fast] Error 2
```
but I don't know what I can do to diagnose the problem further (or fix it).

**Comment by danpat** [comment]
@retorquere Not sure, but it seems like your system might be a bit messed up.

Under Linux, you should have something like `/lib/x86_64-linux-gnu/libpthread-2.23.so` - it's part of `libc`.

You can try typing `ldconfig -p | grep pthread` and see if `ldconfig` knows where it is, maybe it's in a different spot.

If it's missing, then, well, that's your problem.  I notice that your file paths have things like `/cm/...` as a prefix which is pretty non-standard, so if you've built some kind of custom machine image to do the compilation, maybe you've forgotten something.

**Comment by retorquere** [comment]
It's not my system, it's part of the linux cluster at my uni. `find /lib -name \*pthread\*` doesn't give any output, `ldconfig -p | grep pthread` gives `libevent_pthreads-2.0.so.5 (libc6,x86-64) => /lib64/libevent_pthreads-2.0.so.5`. I'll ask the admins, but it's a multi user system that's been up for years, it'd be fairly strange for it to be messed up and noone would have noticed.

**Comment by danpat** [comment]
@retorquere Indeed, that is strange.  On debian-based systems, it's included with `libc`:

```
# dpkg -S /lib/x86_64-linux-gnu/libpthread*
libc6:amd64: /lib/x86_64-linux-gnu/libpthread-2.23.so
libc6:amd64: /lib/x86_64-linux-gnu/libpthread.so.0
```

And it's such a core library, that tools like `tar` use it:

```
# ldd `which tar` | grep pthread
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1f1c6b6000)
```

(These paths are from an Ubuntu 16.04 machine image).

So I can only assume that it's *somewhere* on your system, but in a different spot that cmake isn't searching?  If you can find it, the fix should *hopefully* be to do:

```
LDFLAGS=-L<location to libpthreads> cmake ..
``

**Comment by retorquere** [comment]
Ha, the tar trick did it for me. It lives in /lib64/libpthread.so.0.

**Comment by retorquere** [comment]
Man this cluster is a strange system. Now cmake can't find libevent. There is a `/lib64/libevent-2.0.so.5`. Is it plausible these do the same, and if so, can I convince cmake to use it?

**Comment by danpat** [comment]
Looks like this is https://wiki.debian.org/Multiarch/TheCaseForMultiarch coming into play.  Most of the core dev team use Ubuntu, which has foregone `/lib64` in favour of `/lib/x86_64-linux-gnu`.

Doing `LDFLAGS=-L/lib64 cmake ..` I would expect to catch most of these problems.

**Comment by retorquere** [comment]
In this case most isn't enough :smile:. Any idea on this libevents-2?

**Comment by retorquere** [comment]
I've found `/lib64/libpthread.so.0 `, but running this

```
export CC=`which gcc`
export CXX=`which g++`
export LDFLAGS="-L/lib64"
if test -n "$LD_LIBRARY_PATH"; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lib64"
else
  export LD_LIBRARY_PATH=/lib64
fi
rm -rf build
mkdir -p build
cd build
pwd
cmake .. -DENABLE_MASON=ON -DCMAKE_INSTALL_PREFIX=~/ -DCMAKE_BUILD_TYPE=Release
```

still gives me 

```
cm/local/apps/gcc/6.3.0/bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec4018769912.dir/CheckFunctionExists.c.o   -c /cm/shared/apps/cmake-3.1.3/share/cmake-3.1/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec4018769912
/cm/shared/apps/cmake-3.1.3/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec4018769912.dir/link.txt --verbose=1
/cm/local/apps/gcc/6.3.0/bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create   -L/lib64 CMakeFiles/cmTryCompileExec4018769912.dir/CheckFunctionExists.c.o  -o cmTryCompileExec4018769912 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: Leaving directory `/scistor/guest/ehs215/osrm-backend/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTryCompileExec4018769912] Error 1
gmake: *** [cmTryCompileExec4018769912/fast] Error 2
```

even though:

```
$ nm -D /lib64/libpthread.so.0 | grep create
00000000000080a0 T pthread_create
000000000000c6e0 T __pthread_key_create
000000000000c6e0 T pthread_key_create
```

**Comment by retorquere** [comment]
The cmake output says it did find pthreads_create though:

```
- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Installing dependencies via mason
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Configuring incomplete, errors occurred!
See also "/scistor/guest/ehs215/osrm-backend/build/CMakeFiles/CMakeOutput.log".
See also "/scistor/guest/ehs215/osrm-backend/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by daniel-j-h** [comment]
Closing as stale. You need to debug this by checking the log files or at least provide more information.
