### ISSUE TITLE
Lane assist does not highlight the to-be-used lane

### ISSUE THREAD

**Issue by Penegal** [Project-OSRM/osrm-backend#5121]
Hello, there.

![image](https://user-images.githubusercontent.com/13777824/41836662-b5088112-785b-11e8-9ff9-1cac56732b84.png)

As you can see, the last instruction before arrival includes lane assist, but does not highlight the lane to be used, unlike the instruction above it.

Regards.

**Comment by danpat** [comment]
@Penegal Actually, if you look closely, the "straight" arrow is a slight blue tinge here.

I think this is a UI problem on the `osrm-frontend` project - can you please re-open this ticket there?

**Comment by yuryleb** [comment]
IMHO problem is on backend side instead - I suppose backend collapses two maneuvers into the one and merges lanes from 1st and direction from 2nd into one step.
