### ISSUE TITLE
Get side roads for route

### ISSUE THREAD

**Issue by retorquere** [Project-OSRM/osrm-backend#5124]
I'm trying to get all side roads for a route (where side roads are roads that connect to the route in such a way that the driver could have taken any of those side roads, or that other drivers could have joined the route from those side roads). I'm looking at the intersections when I get a route back, and those seem to get me mostly there; I take the intersection location, add intersection exit bearing + 25meters, look up the road, voila. But 

1. I'm thinking there must be an easier way to do this, and
2. Some exits off the route (offramps from an highway=secondary) are not listed in the step intersections with steps=true&annotations=true; should I be passing other arguments?

**Comment by danpat** [comment]
@retorquere The `intersections` object on each step should contain what you need.  Can you point to an example of (2) where an intersection is missing?

There is no easier way to do it if you want to only use the data in the OSRM response object.  You might be able to do more if you can perform a secondary lookup in another database once you have the route, but if you can do that, then you probably wouldn't be opening this ticket :-)

**Comment by retorquere** [comment]
My mistake -- the offramp is there, it's just that the intersection is a fair way ahead of it, which makes sense for routing I guess.

I can do a secondary lookup but I'm not sure what to look on. The intersections do not contain node ids or way ids. Can I add them in some way? I'm already adding info by hacking around in WayHandlers.names(profile,way,result,data) (I'm putting json-ified road info in the name returned).

**Comment by danpat** [comment]
You should be able to concatenate all `intersections` together for all steps along the whole route, and get the complete list.  There are some nuances about whether intersections come *before* or *after* steps, but considered as a whole, the list should be complete.

If you add `annotations=nodes`, you'll get back OSM node IDs for every coordinate along the route.  Unfortunately, you'll need to do a coordinate comparison to figure out which intersections belong at which coordinate positions, the API response should have an geometry index for intersections, but it does not (kind of a known API smell).

**Comment by retorquere** [comment]
Does annotations=nodes give more node info than annotations=true? I tried doing lookups on those nodes I got earlier but I didn't see all intersections.

**Comment by danpat** [comment]
`annotations=true` returns all annotations, `annotations=nodes` will give you just the node details.

You should get a node for every coordinate along the route, and all intersections have coordinates, by definition.

You'll need to make sure that your map lookup source, and your routing data are in sync - edits to OSM can change node ID values, so if you get a route that mentions some nodes, they may not exist in your lookup data.

**Comment by retorquere** [comment]
I built the osrm's from the osm myself. I'm trying a rebuild now, but in the files I had, I had one intersection that didn't show up in the nodes. Perhaps I'm walking the osm.pbf incorrectly.

**Comment by retorquere** [comment]
Just to make clear: I'm getting [this route](http://localhost:5000/route/v1/driving/5.859516,51.953171;5.948372,51.991109?steps=true&annotations=true), which returns [this response](https://gist.github.com/retorquere/b43961a638e0ede0081532a5f004aad8). This returns to me one leg, because there's only two waypoints (right?). `response['routes'][0]['legs'][0]['annotation']['nodes']` has all  the nodes along the route, including intersections.

The thing is that I know that there exists at least one intersection at `Vlamoven` (which is in the intersections list). I've built my nodes cache using [pyosmium](https://gist.github.com/c98ddbd177929c6c7ef99d110de3d8bf), and then I'm running this script:

```
routes = requests.get('http://localhost:5000/route/v1/driving/5.859516,51.953171;5.948372,51.991109?steps=true&annotations=true').json()
nodes = list(set(routes['routes'][0]['legs'][0]['annotation']['nodes']))
visited = set()
query = f'SELECT DISTINCT nodes.node, ways.name FROM nodes LEFT JOIN ways ON ways.way = nodes.way WHERE nodes.node IN ({",".join([str(node) for node in nodes])})'
print(len(nodes), query)
for node in cur.execute(query):
  print(node, node[0] in nodes)
  visited.add(node[0])
print('not found:', set(nodes) - visited)
```
This shows me that all nodes have been matched (not found is empty) but I don't see the [Vlamoven intersection](https://www.google.com/maps/place/51%C2%B058'39.9%22N+5%C2%B057'43.3%22E/@51.9777516,5.9609308,18z/data=!3m1!4b1!4m14!1m7!3m6!1s0x47c7a40b456d1bd9:0xab3e6ea2c199367c!2sVlamoven,+Arnhem!3b1!8m2!3d51.9762148!4d5.9582424!3m5!1s0x0:0x0!7e2!8m2!3d51.9777447!4d5.9620297) mentioned.

**Comment by retorquere** [comment]
Meh, I'm over-complicating things. The bearing gets me close enough. Thanks for your help!
