### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "MSYS Mak                                                               efiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

### ISSUE THREAD

**Issue by kamuluprashanth** [Project-OSRM/osrm-backend#5125]
i am working on masari-wallet-gui when running cd masari-wallet-gui then run ./build.sh
at that time i am getting this error.
Configuring build for MINGW64..
CMake Error: CMake was unable to find a build program corresponding to "MSYS Mak                                                               efiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a differen                                                               t build tool.
CMake Error: CMake was unable to find a build program corresponding to "MSYS Mak                                                               efiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a differen                                                               t build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be                                                                built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be                                                                built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: C:/masari-wallet-gui/monero/build                                                               /release/CMakeFiles/3.3.2/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be                                                                built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be                                                                built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file: C:/masari-wallet-gui/monero/build                                                               /release/CMakeFiles/3.3.2/CMakeCXXCompiler.cmake
CMake Error at CMakeLists.txt:44 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_C_COMPILER to the full path to the compiler, or to the compiler name
  if it is in the PATH.

CMake Error at CMakeLists.txt:44 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_CXX_COMPILER to the full path to the compiler, or to the compiler
  name if it is in the PATH.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program.
-- Configuring incomplete, errors occurred!

**Comment by systemed** [comment]
You appear to have ended up on the wrong issue tracker. This is OSRM (Open Source Routing Machine), not masari-wallet-gui.

**Comment by SiarheiFedartsou** [comment]
Closing as stale.
