### ISSUE TITLE
Why no follow right?

### ISSUE THREAD

**Issue by eveyeti** [Project-OSRM/osrm-backend#5129]
http://map.project-osrm.org/?z=17&center=-33.525140%2C-70.676851&loc=-33.523204%2C-70.677109&loc=-33.526549%2C-70.678750&hl=en&alt=0

What happend with optimal path, why ?  I checked the openstreetmap data and it's fine, all the arcs are connected.

![2018-07-03_18-43-38](https://user-images.githubusercontent.com/1249934/42249324-a35c7164-7ef8-11e8-87a8-59a674bcfcc5.png)

**Comment by eveyeti** [comment]
Hi danpat,

Whe I use https://graphhopper.com/api/1/examples/#routing it works, 

![2018-07-03_22-12-54](https://user-images.githubusercontent.com/1249934/42253144-4a3311a4-7f0e-11e8-931b-97127b93aa88.png)

**Comment by eveyeti** [comment]
Hi danpat: 

It is possible the problem resides in osrm-extract /osrm-contract/ osrm-partition/ osrm-customize to get correct network graph ?

**Comment by danpat** [comment]
@eveyeti Well, the routing is definitely wrong, but I cannot say exactly what the problem is right now.  I will not have time to dig deeply into this to figure it out, but maybe one of the other core developers will have a chance.  I may be missing something obvious, but it seems weird/buggy.

**Comment by eveyeti** [comment]
Thank a lot Daniel! 

I test MapBox too ( that I think using this project too),  and it has the same behavior, see image below.

![2018-07-06_09-14-33](https://user-images.githubusercontent.com/1249934/42381749-19e363c0-8100-11e8-8cf1-d456239c2b74.png)

I report them the bug, I hope they able to get the solution. 

Regards,
