### ISSUE TITLE
Performance issue with /table/v1/driving and multithread

### ISSUE THREAD

**Issue by grib0** [Project-OSRM/osrm-backend#5130]
Hi,

I ran into a performance issue when using OSRM v5.18.0 in a docker container with the new distance and duration table matrix API.

The docker command line is as follow :
```sh
docker run -d -p 5000:5000 -v /data:/data osrm/osrm-backend:v5.18.0 sh -c "osrm-routed /data/france-latest.osrm --algorithm mld --max-table-size 1000"
```

The requests are sent by a gatling performance test doing many requests like :

```
http://localhost:5000/table/v1/driving/5.78507,45.13369;5.95876,45.1165;6.11078,45.01316;5.70948,45.04911;5.9695,45.26191;5.38237,45.39179;5.72072,45.02177;5.58973,44.92504;5.81966,44.87054;5.85956,44.94264;6.10169,45.37748;5.58709,45.30124;5.73664,45.14726;5.41452,45.33932;5.82054,44.90911?sources=14&destinations=0;1;2;3;4;5;6;7;8;9;10;11;12;13&annotations=duration,distance&generate_hints=false
```

The performance where good in an server with 2 to 4 cpu, but they were very poor in a server with 32 cpu.

The vmstat command shows that the context switch changed from 300 to 300K with the 32 cpu instances. Also the cpu where idle most of the time, performance where 10x slower than the instance with 4cpu.

I recreated my docker container by adding --thread 1 in the osrm command line, started a container per cpu, added a nginx in front loadbalancing the 32 instances and have a great scalable solution.

But I think it would simplier if the --thread 32 where providing the same performance

**Comment by danpat** [comment]
@grib0 `osrm-routed` hasn't really been benchmarked like this too much, so it's not that surprising that there's a bottleneck as the thread count increases.

One option that comes to mind is:

  1) Load data with `osrm-datastore`
  2) Run multiple copies of `osrm-routed -s` with a small thread count

`osrm-routed` uses the `SO_REUSEPORT` option, so many `osrm-routed` processes listening on the same socket can be started, and the Linux kernel will round-robin connections between the processes.  If there is internal contention allocating work to threads, this may be one way to avoid that.

Another thing to try could be to look at the NodeJS re-write of `osrm-routed` that exists on this PR: https://github.com/Project-OSRM/osrm-backend/pull/4604

If you use this, it'll use a different threading library (`libuv`), and you can tune the number of NodeJS workers/threads-per-worker to see if you can get better performance.

There are no real docs for how to use it - it's assumed you're somewhat familiar with the NodeJS ecosystem, and the PR is still a work-in-progress.

Other than that, it's time to pull out a profiler and debug the C++ code.

**Comment by grib0** [comment]
Thank you for your answer, I tried 1. and 2. but measure no performance increase, is it because of docker usage ? see #5134 

The SO_REUSEPORT is not available in docker container, each docker container must use a different port.
The nginx solution for round robin to multiple docker container is great, but the problem is that for 8 docker containers spawned, I need 8x4Go RAM. So I would like to know if using shared memory can avoid the 8x4Go of RAM ?

I'm not confortable with nodeJS for developpement nor for production use, so I would rather find a solution in the build from sources or docker image.

**Comment by TheMarex** [comment]
>  I used this PR #4141 for that and end up that when many users request the /table/v1/driving , performances increase x5 with same configuration with ubuntu based image.

Oh wow didn't know musl performes that badly in multi-threaded environments.

**Comment by danpat** [comment]
Indeed TIL - I only picked Alpine for the original Docker images because the image size came out nice and small - I never bothered benchmarking it.

**Comment by grib0** [comment]
Close with v5.20.0 using debian base image with glibc
