### ISSUE TITLE
completely excluding a way in process_way, still calls process_segment

### ISSUE THREAD

**Issue by bjtaylor1** [Project-OSRM/osrm-backend#5132]
I want to use `process_segment` to set rates based on elevation, land use etc.
However, I also want to completely avoid some ways in `process_way` .

I have excluded the ways by adding a handler to the ones called by `process_way`, setting
`result.forward_rate = 0`
and
`result.backward_rate = 0`
and also doing
`return false`

I have checked it is running this code by use of `io.write` .

I am finding that it still calls `process_segment` for the ways that I have excluded though, and there is non-zero weight on the result.

Is this normal behaviour?
My understanding (based on the order in which my `io.write` logging statements are received) is that `process_way` is called before `process_segment`.
If so, is there a way of getting it to only call `process_segment` for ways that are going to be routed over?
Or some way of telling during `process_segment` whether the way the segment belongs to has been excluded?
If the code in `process_way` contains expensive operations e.g. database calls then it makes sense not to call it for data that isn't going to be used anyway I would have thought.

Just thought I'd check what I should be expecting to see here, as it could be that I haven't excluded the ways correctly.

Thanks
Ben

**Comment by TheMarex** [comment]
Try setting `result.mode = mode.inaccessible`, because that will cause the way handler to filter out the way [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/extractor_callbacks.cpp#L100).
