### ISSUE TITLE
For understand this project

### ISSUE THREAD

**Issue by ghanIn** [Project-OSRM/osrm-backend#5138]
(First, if this question is strange at this board tell me i will delete)

Hi, I'm new OSRM 
I want understand this project for customize myself
So please tell me what i have to do
(example: study about C++, OOP ,,,,,,)

Thank you very much

**Comment by danpat** [comment]
@ghanIn There's no simple answer to this question, but at a minimum, you'd want:

  - Passable understanding of C++ so you can read the code
  - Good general understanding of data structures and algorithms
  - Some specific understanding on routing algorithms and graph theory

These are pretty broad topics.  Depending on how you want to customize OSRM, you may need none or all of these.  The above is not an exhaustive list of technologies/topics that OSRM uses.

Unfortunately, OSRM is a fairly complex thing, and we have never had time to invest in a "getting started working on OSRM" guide (and I don't see one appearing any time soon).  I think the unfortunate answer, like so many complex open source things, is that you're just going to have to hack away at it until you figure it out.

I would suggest focusing on a very small specific change you want to make, then working through how to make it - OSRM is too large to make sweeping changes to without a thorough understanding of the code, and that takes lots of time and effort to achieve.
