### ISSUE TITLE
OSMR doesn't recognize new route 

### ISSUE THREAD

**Issue by JairoBarzola** [Project-OSRM/osrm-backend#5139]
Hi,
I have added a route to OSM and it has been successfully added to the map,Now I wanted to perform a navigation. Where I want to go is to the red point with the new Road that I have added but the OSMR  does not recognize it yet as a road, I do not know if there is a configuration so that OSMR can go through the new route that I have added.
Help me please
<img width="1195" alt="captura de pantalla 2018-07-11 a la s 18 53 26" src="https://user-images.githubusercontent.com/22141461/42605111-c48c87a4-853b-11e8-8399-c6bf4066f67c.png">

**Comment by danpat** [comment]
@JairoBarzola We only update the routing map from OSM about once a day.  Please wait longer.
