### ISSUE TITLE
destinations on left/right side

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#515]
it would be nice if the instructions would indicate whether the destination (or via point) is on the left or right side of the road.

ie. "your destination is on your left hand".

**Comment by MoKob** [comment]
Will be part of 5.0 with https://github.com/Project-OSRM/osrm-backend/pull/1935/commits/fbdafca4f2d34cb093d3e00a10e1ff8d86e1eb4e
