### ISSUE TITLE
Suboptimal routing result

### ISSUE THREAD

**Issue by ZsoltMedgyesi-Itineris** [Project-OSRM/osrm-backend#5152]
The issue is the following:
while routing between 2 points, not the optimal route is chosen on a subsegment.
Conditions:
- No blocking mapfeatures are present (turn-restrictions, one-ways,...)
- All the crossings can be routed through individually
- Profile is based on _car.lua_
- _alternatives_ are turned on, but no alternative route were given

Test environment:
- Around Hajdúsámson, Hungary, on way ref. 471 
- The suboptimal part is around 50sec longer in duration, than the optimal would be.
- Speeds of the thest environment 
![image](https://user-images.githubusercontent.com/39079788/43136497-3d737120-8f49-11e8-969c-530e88307914.png)
(**UPDATE**: speed-limits are altered in the area since the test, and now it gives correct results in this scenario, but the original cause is/could be still present)

Suboptimal result (duration: 166sec):
![image](https://user-images.githubusercontent.com/39079788/43134983-27db47e8-8f44-11e8-8408-321bfefb4bac.png)

Optimal result produced with an additional waypoint (duration: 118sec):
![image](https://user-images.githubusercontent.com/39079788/43135274-1e90f16e-8f45-11e8-9d6d-dfedf49b8617.png)

**Comment by danpat** [comment]
@ZsoltMedgyesi-Itineris I can't reproduce this problem using the OSRM demoserver:

http://map.project-osrm.org/?z=14&center=47.591723%2C21.747694&loc=47.599710%2C21.753230&loc=47.582431%2C21.715336&hl=en&alt=0

<img width="1079" alt="screen shot 2018-07-24 at 7 34 24 am" src="https://user-images.githubusercontent.com/1892250/43145353-09f6ad7e-8f14-11e8-9ac2-2d3422c04ee9.png">

It will be difficult to figure out what the problem was if we can't reproduce the issue.  Are you using OSM data?  If so, I would guess that maybe there was a data issue.

**Comment by ZsoltMedgyesi-Itineris** [comment]
Yes, i am using OSM data, but the difference probably comes from the different profile, that i use.
The only modifications in the profile are in the speeds (which are btw the legally allowed speeds for trucks in Hungary).
Using the original profile, it produces the same result as the demo server.
The files (osm.pbf, profile, osrm routing files), wherewith this issue is repruducable, can be found [HERE](https://1drv.ms/u/s!AoMxkBHfqdXlwzjcfc0nxvhjHk4L).

**Comment by danpat** [comment]
The problem, I believe, is the `lanes=1` tag on the 471 road.

OSRM calculates routes based on the "weight" of a road.  The weight is based on speed, but there are some parts of the Lua script that adjust the weight to bias routes toward/away from certain types of roads.

In your case, road 471 has `lanes=1`.  This means that a multiplier of `0.5` is applied here: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua#L400-L402

The road to the south-east (this one: https://www.openstreetmap.org/way/172062959) has `lanes=2`.

When you applied your changes to the `car.lua` profile, you increased the speed for many road types, including the south-east road.  Combine this with the lane width multiplier, and this road has become "faster" from OSRM's perspecitive for the route.

OSRM choses the "minimum weight" path, not the shortest distance.

**Comment by ZsoltMedgyesi-Itineris** [comment]
@danpat  Thank you for your answer. It saved me from a great share of trouble.

I was familiar with the concept of weights, but i have not examined it as thoroughly, as it seems i should have. 

As for a shortcut solution, for the given example, by setting `weight_name ='duration'` in the profile, the weights are calculated without these penalties, and gives the expected result. Of course, in long term, its worth to keep the map data up-to-date, which i intend to do.
