### ISSUE TITLE
Wrong detours (probably bad coordinates)

### ISSUE THREAD

**Issue by edwardffs** [Project-OSRM/osrm-backend#5158]
Hi!

I started using OSRM a while, mainly to keep track of some trips I made. Therefore, I ping some coordinates  and then give it to OSRM, running on LeafLet. However, it makes strange detours, something my really amateur knowledge about the matter tells me it's because of inaccuracy of my coordinates. Since points somehow are in opposed lanes, it assumes I made a huge detour to be there, when in reality I followed the main road. 

This can be seen here. I kept on that orange main roard, however that's what OSRM returned. Is there any way I can solve this kind of situations, or can it only be solved by getting better coordinates? I have all the default profiles downloaded from this repository.

![capturar](https://user-images.githubusercontent.com/5982482/43576267-da0e5aba-9640-11e8-8c1a-450f5fb6d8bc.PNG)

(The black antennas are the points I registered)

**Comment by edwardffs** [comment]
With further testing on this specific route, I found out that if I remove the waypoint at the exit of the second roundabout (I'm headed top-down) it traces my route beautifully. What rule/paremeter could be messing my route?

**Comment by danpat** [comment]
@edwardffs For debugging this kind of problem, it's helpful if you can provide some specifics - what is the exact API call you're making (including all parameters)?

Off the top of my head, this looks like a case where you want to be using the `/match` API, not the `/route` API.  The `/match` API will try several nearby roads to find the "best" path, whereas the `/route` API only uses the closest road it finds (which can lead to these detours like you're seeing).

**Comment by edwardffs** [comment]
@danpat  Thank you for your time! I'm using LeafLet Routing Machine: http://www.liedman.net/leaflet-routing-machine/api/

And yes, LRM uses `/route`. Tried changing it to `/match` just for kicks, it crashes 😒

**Comment by danpat** [comment]
@edwardffs I don't think LRM supports the `/match` endpoint, although the response is similar enough to `/route` that it could with a little bit of work.  You could try opening a ticket in the LRM repo for this.  Of course, a pull-request that actually implements it would probably be the most well recieved :-)

Unfortunately, I don't think the problem here is OSRM - what you're trying to do really requires the logic that `/match` has, not what `/route` does.  `/match` is specifically designed to have some wiggle-room to handle error in recorded GPS signals, whereas `/route` is not.

**Comment by edwardffs** [comment]
@danpat  I see. Well, at least now I know it won't work like this. Thank you for you insight. I'll look into the `/match` service.

**Comment by edwardffs** [comment]
@danpat Just came here to tell you I tried out the `/match` API. Works like a charm. The detail when it returns the tracepoints with the outliers nulled out, spot on. Thank you again for the tip ;)

**Comment by danpat** [comment]
@edwardffs No worries.  You can also mess around with the `radiuses=` parameter a bit.  Increasing it from the default of 5 will give the algorithm more options for snapping, which can improve the matches when outliers are only a little bit bad.

**Comment by llimz** [comment]
@edwardffs I have a similar problem. Please, can you explain a bit how you move to `/match` api as I'm using also Leaflet Routing Machine using `/route`? Are you drawing the road by yourself as explained in the link below

https://stackoverflow.com/questions/37345416/how-to-use-osrm-match-api-in-leaflet-to-draw-a-route
