### ISSUE TITLE
open data question, planet.osrm files

### ISSUE THREAD

**Issue by victusfate** [Project-OSRM/osrm-backend#5159]
I've been looking around for preprocessed planet files (extract, partition, customize) for both car and foot traffic. This would be nontrivial to recreate over and over so I was hoping preprocessed osrm files may be available for planet routing. Any help would be appreciated.

for reference, rerunning this on the latest data is my fallback plan.
https://github.com/lonvia/Project-OSRM/wiki/OSRM--on-whole-planet-.-Requirements-and-Statistics

also saw this comment in another issue thread which would lead me to believe that the processed files are very much cache only (non transferrable)
"Files are not compatible across operating systems (and strictly speaking not even across different architectures and compilers)."

**Comment by danpat** [comment]
@victusfate If you want to keep up-to-date with OSM, then yep, that's pretty much your only option.

There are a couple of reasons why the processed files aren't often shared:

  1. People often want to customize the profiles, so shared datafiles aren't useful.
  2. OSRM datafiles aren't compatible between versions, which creates all kinds of confusion and headaches that folks just don't want to deal with.
  3. We've made no attempt to make them cross-platform compatible.  If the source and target machines are the same OS/architecture, then it should work fine, but all kinds of weird problems might crop up if you try to say, use Linux-generated `.osrm` files on a Windows box.

I think these three problems need to be solved before it would be practical for anyone to publish regular pre-processed datafile updates.

**Comment by victusfate** [comment]
Thanks for the quick response @danpat -> here's to hoping that format standardizes in the coming years.

**Comment by danpat** [comment]
@victusfate Pull requests implementing a stabilized file format are always welcome :-)
