### ISSUE TITLE
Local server returns durations which are almost 50% lower than the osrm online service

### ISSUE THREAD

**Issue by j0nd0n7** [Project-OSRM/osrm-backend#5161]
Deploying a local server returns durations which are almost 50% lower than the osrm online service.
The online value is the "expected" where the local is too optimistic. I also compared against gmaps to have another reference.

Local Server version: 5.18.0
Map data: http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
Note: reproducible with different country map files (and versions)

Commands to deploy:
```
docker run -it --rm -v $(pwd)/data:/data osrm/osrm-backend:v5.18.0 osrm-extract -p /opt/car.lua /data/maps/berlin.osm.pbf
docker run -t --rm -v $(pwd)/data:/data osrm/osrm-backend:v5.18.0 osrm-partition /data/maps/berlin.osm
docker run -t --rm -v $(pwd)/data:/data osrm/osrm-backend:v5.18.0 osrm-customize /data/maps/berlin.osm
docker run -t -i -p 5000:5000 -v $(pwd)/data/maps:/data osrm/osrm-backend:v5.18.0 osrm-routed --algorithm mld /data/berlin.osm
```

Example request:

`http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.385983,52.496891`

Online return
```
{
  "routes": [
    {
      "geometry": "mfp_I__vpAdmA}Kl@dV~P_HnSc@rKqBwAxT",
      "legs": [
        {
          "summary": "",
          "weight": 899.5,
          "duration": 628.4,
          "steps": [],
          "distance": 2829.5
        }
      ],
      "weight_name": "routability",
      "weight": 899.5,
      "duration": 628.4,
      "distance": 2829.5
    }
  ],
  "waypoints": [
    {
      "hint": "ydsJgG5Y54QhAAAALQAAAAwAAAAAAAAAeOI0QY6li0FoZYRAAAAAACEAAAAtAAAADAAAAAAAAADVowAAAEzMAKlYIQM8TMwArVghAwEA3wrNHudk",
      "name": "Friedrichstraße",
      "location": [
        13.3888,
        52.517033
      ]
    },
    {
      "hint": "GPqXgLSlmoDJAAAA5gAAAAAAAAAAAAAACiuSQjMSs0IAAAAAAAAAAMkAAADmAAAAAAAAAAAAAADVowAAgEDMAKYIIQP_QMwA-wkhAwAArxHNHudk",
      "name": "Obentrautstraße",
      "location": [
        13.385856,
        52.49655
      ]
    }
  ],
  "code": "Ok"
}
```

Local return:
```
{
  "code": "Ok",
  "routes": [
    {
      "geometry": "mfp_I__vpAn_AuIv@vZl]qNlTk@rKqBwAxT",
      "legs": [
        {
          "steps": [],
          "distance": 2882.3,
          "duration": 316.8,
          "summary": "",
          "weight": 330.9
        }
      ],
      "distance": 2882.3,
      "duration": 316.8,
      "weight_name": "routability",
      "weight": 330.9
    }
  ],
  "waypoints": [
    {
      "hint": "RSUCgMMlAoAUAAAAIAAAAAcAAAAAAAAAeOI0QY6li0FoZYRAAAAAAAoAAAAQAAAABAAAAAAAAADvAAAAAEzMAKlYIQM8TMwArVghAwEA3wrCZIZ-",
      "name": "Friedrichstraße",
      "location": [
        13.3888,
        52.517033
      ]
    },
    {
      "hint": "lwgAgNkcAoBtAAAAhgAAAAAAAAAAAAAACiuSQjMSs0IAAAAAAAAAAG0AAACGAAAAAAAAAAAAAADvAAAAgEDMAKYIIQP_QMwA-wkhAwAArxHCZIZ-",
      "name": "Obentrautstraße",
      "location": [
        13.385856,
        52.49655
      ]
    }
  ]
}
```
**Note online duration is 628.4 where local is 316.8, also the routes are slightly different and the  weights are different too 899.5 vs 330.9**

To give more context, this is the output of the executed commands to deploy the local server:
>**docker run -it --rm -v $(pwd)/data:/data osrm/osrm-backend:v5.18.0 osrm-extract -p /opt/car.lua /data/maps/berlin.osm.pbf**
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: berlin.osm.pbf
[info] Profile: car.lua
[info] Threads: 4
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2018-08-07T19:59:02Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 10.1025 seconds
[info] Raw input contains 5075237 nodes, 748360 ways, and 1128 relations, 1174 restrictions
[info] Sorting used nodes        ... ok, after 0.005818s
[info] Erasing duplicate nodes   ... ok, after 0.001249s
[info] Sorting all nodes         ... ok, after 0.004099s
[info] Building node id map      ... ok, after 0.00617s
[info] Confirming/Writing used nodes     ... ok, after 0.760813s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 250065 nodes
[info] Sorting edges by start    ... ok, after 0.008378s
[info] Setting start coords      ... ok, after 0.020535s
[info] Sorting edges by target   ... ok, after 0.009203s
[info] Computing edge weights    ... ok, after 0.049992s
[info] Sorting edges by renumbered start ... ok, after 0.009992s
[info] Writing used edges       ... ok, after 0.055728s -- Processed 278473 edges
[info] Writing way meta-data     ... ok, after 0.003499s -- Metadata contains << 69428 entries.
[info] Sorting used ways         ... ok, after 0.000328s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0.000819s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0s
[info] Collecting start/end information on 1174 restrictions...ok, after 0.002088s
[info] Collecting start/end information on 1174 restrictions...ok, after 0.00088s
[info] writing street name index ... ok, after 0.003708s
[info] extraction finished after 11.0798s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.371008
[info] Edge compression ratio: 0.43155
[info]  graph compression removed 55975 annotations of 69428 in 0.062243 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 0.363013s
[info] Segregated edges count = 5424
[info] Writing nodes for nodes-based and edges-based graphs ...
[info] Geometry successfully removed:
  compressed edges: 238900
  compressed geometries: 562020
  longest chain length: 57
  cmpr ratio: 0.425074
  avg chain length: 2.35253
[info] Generating edge expanded nodes ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 219199 nodes (59 of which are duplicates)  and 276698 segments in edge-expanded graph
[info] Generating edge-expanded edges 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 215867, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=52.514754&mlon=13.389043
. 90% .
[info] Sorting and writing 0 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 276698 edge based node segments
[info] Node-based graph contains 219022 edges
[info] Edge-expanded graph ...
[info]   contains 413069 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 0.003905s
[info] Generating nodes: 0.080268s
[info] Generating edges: 2.03025s
[info] Generating guidance turns 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .
[info] done.
[info] Created 42 entry classes and 2570 Bearing Classes
[info] Handled: 2764 of 5055 lanes: 54.6785 %.
[info] Assigned 499877 turn instruction types:
[info]   new name: 12156 (2.43%)
[info]   continue: 31832 (6.37%)
[info]   turn: 191504 (38.31%)
[info]   merge: 93 (0.02%)
[info]   on ramp: 212 (0.04%)
[info]   off ramp: 91 (0.02%)
[info]   fork: 1276 (0.26%)
[info]   end of road: 80440 (16.09%)
[info]   notification: 12 (0.00%)
[info]   enter roundabout: 68 (0.01%)
[info]   enter and exit roundabout: 2 (0.00%)
[info]   enter rotary: 94 (0.02%)
[info]   enter and exit rotary: 7 (0.00%)
[info]   enter roundabout turn: 51 (0.01%)
[info]   (noturn): 52272 (10.46%)
[info]   (suppressed): 129103 (25.83%)
[info]   roundabout: 2 (0.00%)
[info]   exit roundabout: 71 (0.01%)
[info]   rotary: 7 (0.00%)
[info]   exit rotary: 100 (0.02%)
[info]   exit roundabout turn: 49 (0.01%)
[info]   (stay on roundabout): 210 (0.04%)
[info]   (sliproad): 225 (0.05%)
[info] Assigned 499877 turn instruction modifiers:
[info]   uturn: 21786 (4.36%)
[info]   sharp right: 4602 (0.92%)
[info]   right: 140574 (28.12%)
[info]   slight right: 7765 (1.55%)
[info]   straight: 176073 (35.22%)
[info]   slight left: 7770 (1.55%)
[info]   left: 136284 (27.26%)
[info]   sharp left: 5023 (1.00%)
[info] Guidance turn annotations took 2.96206s
[info] Writing Intersection Classification Data
[info] ok, after 0.008909s
[info] Writing Turns and Lane Data...
[info] ok, after 0.017446s
[info] Saving edge-based node weights to file.
[info] Done writing. (0.03104)
[info] Computing strictly connected components ...
[info] Found 1122 SCC (1 large, 1121 small)
[info] SCC run took: 0.0117914s
[info] Building r-tree ...
[info] Constructing r-tree of 276698 segments build on-top of 250065 coordinates
[info] finished r-tree construction in 0.090491 seconds
[info] Writing edge-based-graph edges       ... 
[info] ok, after 1.50287s
[info] Processed 413069 edges
[info] Expansion: 40496 nodes/sec and 35497 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "/data/maps/berlin.osrm"
[info] RAM: peak bytes used: 249556992

> **docker run -t --rm -v $(pwd)/data:/data osrm/osrm-backend:v5.18.0 osrm-partition /data/maps/berlin.osm**
> [info] Computing recursive bisection
> [info] Loaded compressed node based graph: 238818 edges, 250065 nodes
> [info]  running partition: 128 1.2 0.25 10 1000 # max_cell_size balance boundary cuts small_component_size
> [info] Found 157686 SCC (1 large, 157685 small)
> [info] SCC run took: 0.016632s
> [info] Full bisection done in 2.69942s
> [info] Loaded node based graph to edge based graph mapping
> [info] Loaded edge based graph for mapping partition ids: 825208 edges, 219199 nodes
> [info] Fixed 102 unconnected nodes
> [info] Edge-based-graph annotation:
> [info]   level 1 #cells 1090 bit size 11
> [info]   level 2 #cells 85 bit size 7
> [info]   level 3 #cells 6 bit size 3
> [info]   level 4 #cells 1 bit size 1
> [info] Renumbered data in 0.269287 seconds
> [info] MultiLevelPartition constructed in 0.049966 seconds
> [info] CellStorage constructed in 0.016653 seconds
> [info] MLD data writing took 0.080007 seconds
> [info] Cells statistics per level
> [info] Level 1 #cells 1090 #boundary nodes 21934, sources: avg. 13, destinations: avg. 18, entries: 334185 (2673480 bytes)
> [info] Level 2 #cells 85 #boundary nodes 3460, sources: avg. 26, destinations: avg. 36, entries: 105556 (844448 bytes)
> [info] Level 3 #cells 6 #boundary nodes 369, sources: avg. 40, destinations: avg. 50, entries: 16841 (134728 bytes)
> [info] Level 4 #cells 1 #boundary nodes 0, sources: avg. 0, destinations: avg. 0, entries: 0 (0 bytes)
> [info] Bisection took 3.36264 seconds.
> [info] RAM: peak bytes used: 49963008

> **docker run -t --rm -v $(pwd)/data:/data osrm/osrm-backend:v5.18.0 osrm-customize /data/maps/berlin.osm**
> [info] Loaded edge based graph: 825208 edges, 219199 nodes
> [info] Loading partition data took 0.198269 seconds
> [info] Cells customization took 6.32522 seconds
> [info] Cells statistics per level
> [info] Level 1 #cells 1090 #boundary nodes 21934, sources: avg. 13, destinations: avg. 18, entries: 334185 (2673480 bytes)
> [info] Level 2 #cells 85 #boundary nodes 3460, sources: avg. 26, destinations: avg. 36, entries: 105556 (844448 bytes)
> [info] Level 3 #cells 6 #boundary nodes 369, sources: avg. 40, destinations: avg. 50, entries: 16841 (134728 bytes)
> [info] Level 4 #cells 1 #boundary nodes 0, sources: avg. 0, destinations: avg. 0, entries: 0 (0 bytes)
> [info] Unreachable nodes statistics per level
> [warn] Level 1 unreachable boundary nodes per cell: 0.00275229 sources, 0.000917431 destinations
> [warn] Level 2 unreachable boundary nodes per cell: 0.0235294 sources, 0.0117647 destinations
> [warn] Level 3 unreachable boundary nodes per cell: 0.166667 sources, 0 destinations
> [info] Unreachable nodes statistics per level
> [warn] Level 1 unreachable boundary nodes per cell: 0.00275229 sources, 0.000917431 destinations
> [warn] Level 2 unreachable boundary nodes per cell: 0.0235294 sources, 0.0117647 destinations
> [warn] Level 3 unreachable boundary nodes per cell: 0.166667 sources, 0 destinations
> [info] Unreachable nodes statistics per level
> [warn] Level 1 unreachable boundary nodes per cell: 0.123853 sources, 0.0853211 destinations
> [warn] Level 2 unreachable boundary nodes per cell: 0.682353 sources, 0.447059 destinations
> [warn] Level 3 unreachable boundary nodes per cell: 1.33333 sources, 0.833333 destinations
> [info] Unreachable nodes statistics per level
> [warn] Level 1 unreachable boundary nodes per cell: 0.00366972 sources, 0.00183486 destinations
> [warn] Level 2 unreachable boundary nodes per cell: 0.0235294 sources, 0.0117647 destinations
> [warn] Level 3 unreachable boundary nodes per cell: 0.166667 sources, 0 destinations
> [info] MLD customization writing took 0.065948 seconds
> [info] Graph writing took 0.090356 seconds
> [info] RAM: peak bytes used: 54009856
>

**Comment by systemed** [comment]
The online server additionally uses traffic data from Mapbox so its results are not comparable to those from a local installation.

**Comment by jdonzet** [comment]
Mmm, so it is a "demo server", with extra features beyond this project.
It should be called different, IMO demo means "what you see is what it is".

I follow the link you provided to me and I read that also a different car.lua is used. Do you know which modifications I have to do in the car.lua in order to return twice the duration?

Thanks!

**Comment by daniel-j-h** [comment]
Always returning twice the duration is not what you want to do. You want an accurate traffic model for both speeds as well as weights for optimization. Without that all you can do is tune the heuristics using OSM tags further.

**Comment by WClouds** [comment]
@daniel-j-h I meet the same problem, and you said `Without that all you can do is tune the heuristics using OSM tags further`. So what is the meaning of tune the heuristics using OSM tags further? What can I do for it?

**Comment by daniel-j-h** [comment]
It's not a problem it's just inherent in missing an accurate traffic model.

You can have a look at the Lua profiles and see if you can tune them even further using osm tags as heuristics. But in the end nothing beats a live-traffic model (or even a historic traffic model).
