### ISSUE TITLE
Return the disconnected waypoints in case of "NoTrips" error

### ISSUE THREAD

**Issue by pjmazenot** [Project-OSRM/osrm-backend#5169]
Hi,

first of all, thanks for the great work! OSRM has been working perfectly and is helping me a lot in my projects!

I'm interested to know if it would be possible/interesting to someone else to include the disconnected waypoints in a trip that return a "NoTrips" error.

In this case I'm working with a database of hundreds of thousands of points and roundtrips that have on average a hundred waypoints so when I get the error it's making it next to impossible to find the culprit(s).

Looking forward to hearing your thoughts on this,
Thanks,

Pj

**Comment by daniel-j-h** [comment]
Check out the `osrm-components` tool or the the debug layer

https://www.mapbox.com/get-directions/debug/

it's showing disconnected components in pink.

You should be able to figure out which nodes are in which components and then do your analysis on top of it.
