### ISSUE TITLE
performance question on osrm nodejs module and /table 

### ISSUE THREAD

**Issue by victusfate** [Project-OSRM/osrm-backend#5170]
I was doing some local benchmarks for both the built in osrm-routed http server and a local nodejs http server using module native bindings. osrm-routed ran with the default threads (8?), and the nodejs http server was a single process (similar performance although the built in module had some timeouts). My laptop is a quad core 2012 MBP

For 100 places (100x100 matrix of times) I was seeing 25 requests per second does this sound about right? (500 requests in 18-19sec)
The payload sizes were 94,724 bytes 

I also did some truncation on the inbound lon,lat pairs to represent a grid approach and brought the pairs down from 100 to 43 with .01 truncation. This yielded ~50 requests per second (so linear with the number of places per request)

I'd expect with caching I could improve the performance but I'm trying to get a feel of how this may run in production on heavier instances

To wrinkle the numbers even more, I'm running a long going batch of osmosis extractions on planet osm for 100 cities, I can rerun the bench after that job is done later this week/early next.

**Comment by danpat** [comment]
@victusfate Performance will vary quite a bit with what your inputs look like.  You also don't describe whether you're using the CH (`osrm-contract`) or MLD (`osrm-partition/osrm-customize`) algorithms, which will have a huge effect.

To give you a rough idea, I've been doing some large matrix requests locally, doing a 500x2000 (using the `sources/targets` parameters).  These requests calculate 1,000,000 routes and take about 1.5sec on my 2018 MBP with CH, and 15 sec with MLD (600k routes/sec CH, 60kroutes/sec MLD).

For your 100x100 matrix (10k routes), I'd expect a single request to take 16-20ms.  In theory that means you should would be seeing 50 req/sec single-threaded on my laptop, and it should scale up with CPUs at least for a couple of CPUs (there is another ticket about some possible contention with large CPU counts).

**Comment by victusfate** [comment]
Wonderful.
Thanks, this is very helpful to plan for scale and I have had success with node cluster before. And it matches with my local test runs.

Will more node processes help as I'm cpu limited by OSRM which is already multiprocess (I can observe all cores utilized when running)

Routing Algorithm: Ch (had to read up on Contraction Heirarchies, using bidrectional dijsktras similar to A*?)

**Comment by victusfate** [comment]
I'll close this out, much appreciate the information @danpat !

**Comment by danpat** [comment]
How you balance the `libuv` thread pool and the number of cluster nodes will depend on your workload and codebase.  I would try a few different cluster node/thread-pool size configurations and see how they perform for your situation.  You want to make sure that it's OSRM using all the CPU, not nodejs forwarding/serializing the request/response.

**Comment by victusfate** [comment]
I'm now running with release 5.22 with a global configuration on ec2 m5 xlarge (on 2 servers).
What I'm seeing for many matrix requests (on the order of ~100 places) is response times in the range of seconds.

What can I do to speed up these request times?

Attaching an example of a Kibana worst case timing chart
<img width="1018" alt="Screen Shot 2019-07-25 at 1 38 42 PM" src="https://user-images.githubusercontent.com/107623/61895957-ea1aa480-aee1-11e9-9bf2-4dc32ecb4763.png">

**Comment by danpat** [comment]
@victusfate Without a more detailed description of how you're making queries, and how you're serving them, I can't begin to guess.  Did it change with a switch to 5.22?  Did anything else change?  Are you using MLD or CH data?  Node bindings? osrm-routed? etc, etc

If you're seeing 100x100 matrix requests take several seconds, then you've got a bottleneck somewhere in your config, or you're overloading something.

**Comment by victusfate** [comment]
node bindings: very light vanilla nodejs http wrapper to customize to our needs - can handles thousands of requests / sec no issue
alg -> ch
data -> global osm data
profile -> car only

Is there any chance it's a disk seek issue, those servers don't have a ton of ram (I wasn't able to nail down a RAM requirement)

**Comment by danpat** [comment]
m5.xlarge has 16GB of RAM, which isn't enough for global data - you likely need closer to 40-50GB.  The RAM required is roughly equal to the size of the files on disk - we just read them raw into blocks of memory.

Try disabling swap on the box and see if OSRM will even start - you should get an OOM error if there isn't sufficient RAM and there is no swap available.

Disk seeking issues could definitely be the cause of random-ish slowdowns like this.

**Comment by victusfate** [comment]
expected as much, thanks for the confirmation. Will remedy our hosting instance this week w/o swap and ensuring it runs! Thanks a bunch @danpat

**Comment by victusfate** [comment]
got a chance to test it out on an r5 2xlarge (64GB RAM)

so far I'm still seeing some slow requests (seconds) so I assume I'm still swapping or memory mapping.

I updated the osrm configs with
```
const bMapMemory = CONFIG.environment === 'production' ? false : true;

const oOSRM = new OSRM({ 
  algorithm: 'CH', // 'CH', 'CoreCH', 'MLD' and must be preprocessed appropriately
  path: sOsrmFile,
  mmap_memory: bMapMemory
})
```
which sets that flag to false 

Is there any other config setting I need to make to try have it run without memory mapping/swapping?

**Comment by danpat** [comment]
@victusfate You can use `iostat` or `vmstat` to watch disk activity under load.  For maximum performance, we typically disable swap altogether, and use `osrm-datastore` to pre-load all data into shared memory blocks - this guarantees that there's never any I/O, but it does make startup a bit slower.

**Comment by victusfate** [comment]
Fantastic @danpat -> htop shows 0 swap, and I'll try those commands as well.
Also I'll follow your suggestion to using osrm-datastore and startup with the dataset_name initializer.

**Comment by rajat23495** [comment]
Can you share your results i am sharing a code snippet to load graph but i feel the datafile is not loaded into the memory..
```
const os = require("os");

process.env.UV_THREADPOOL_SIZE = Math.ceil(os.cpus().length * 1.5);

const OSRM = require("osrm");

function loadGraph(options) {
  const opts = { path: options.osrmDataPath, algorithm: "MLD" };
  return new OSRM(opts);
}

module.exports = {
  loadGraph
};
```

**Comment by victusfate** [comment]
@rajat23495 you need  to let OSRM know  to load all data into memory
```
mmap_memory: bMapMemory
```

docs -> https://github.com/Project-OSRM/osrm-backend/blob/master/docs/nodejs/api.md
