### ISSUE TITLE
convert data human readable

### ISSUE THREAD

**Issue by ghanIn** [Project-OSRM/osrm-backend#5171]
i want to change result data human readable for understanding about osrm project 
is it possible??

**Comment by ghanIn** [comment]
@danpat  thanks for reply but maybe its not for me
i want to change result file( .osrm.nodes , .osrm.edges .....)  human readable,  osrm-text-instruction can do this work??

**Comment by danpat** [comment]
@ghanIn No, if you read the project description for `osrm-text-instructions`, it's for converting routing results into human readable form.

Can you explain in more detail what you are trying to achieve?  It doesn't make sense to convert the `.osrm.nodes` and `.osrm.edges` files into "human readable form" without more context.

**Comment by ghanIn** [comment]
@danpat Ok i will explain more detail, i want to understand osrm-backend Extract(data build) process, 
So i want to check the file step by step.
For example 
![image](https://user-images.githubusercontent.com/15894443/44453904-2b9d3280-a635-11e8-9965-f7f9d1b9f4d0.png)
this is osm data before Extract 
and after Extract we can get many files like this
![image](https://user-images.githubusercontent.com/15894443/44454067-83d43480-a635-11e8-9cff-167047887caf.png)

BUT we can't read this files its not humand readable when i open the file
![image](https://user-images.githubusercontent.com/15894443/44454144-b120e280-a635-11e8-8d82-f0de3e6add68.png)
its  maybe binary..

So i want to read the file context(binary) !

**Comment by chaupow** [comment]
What are you trying to achieve/see/understand/find out from the extract output? Do you want the graph structure?

**Comment by daniel-j-h** [comment]
Closing here; we don't have an API for the in-memory datastructures we dump to disk.
