### ISSUE TITLE
Grab speed limits from match service

### ISSUE THREAD

**Issue by gillesgerlo** [Project-OSRM/osrm-backend#5172]
Hi,

I've been using the match service to snap car journeys to the road network with great results. One of the main purposes for my doing this is to check whether the cars are speeding. Is there any way I could edit for example the car.lua file to add these speed limits to the annotations that are currently being returned? Or alternatively is it possible to return the matched ways rather than the nodes, as that's where the maxspeed information resides...

Thanks in advance!

**Comment by stavskal** [comment]
It would be great to know if OSRM is possible to expose OSM speed limits as they are, without modifications

**Comment by daniel-j-h** [comment]
There is an `annotations=speed` otherwise you can get the (s, t) osm node id pairs (segments) and use e.g.

https://github.com/mapbox/route-annotator

or build your own lookup table going from osm segments to your annotation metadata.
