### ISSUE TITLE
issue with bearings

### ISSUE THREAD

**Issue by Vishwajit1986** [Project-OSRM/osrm-backend#5174]
I have configured the local OSRM instance using india.pbf.
without bearings all seems OK.

when i am trying to use bearings we are getting the error message:-

**"{"message":"Query string malformed close to position 187","code":"InvalidQuery"}"**

Request sample is: http://localhost:5000/route/v1/driving/77.2678201092097,28.5501319826502%3B77.26429,28.544359%3B77.2277299999998,28.61306.json?alternatives=true&geometries=polyline&overview=full&steps=true&continue_straight=true&language=en-IN&voice_instructions=true&voice_units=metric&bearings=170.534482016374,90.0;0.0,180.0;0.0,180.0
Thanks in advance!

**Comment by danpat** [comment]
@Vishwajit1986 `bearings=` only supports integer numbers.  Remove the decimal places.
