### ISSUE TITLE
Problems with reading raster data

### ISSUE THREAD

**Issue by AveryPenningtonGSI** [Project-OSRM/osrm-backend#5177]
I am attempting to use the rasterbot profile and load a raster file in order to modulate the route times based on the raster data. Unfortunately the raster data doesn't appear to be being read. An excerpt of the output is given below:

~~~~


 sourceData.datum: 2147483647 targetData.datum 2147483647
segment.source.lat  -1.288742 segment.source.lat 51.689949
segment.weight: 22.815285234913  segment.duration22.815285234913
slope 0
scaled_weight: 22.815285234913  scaled_duration22.815285234913


 sourceData.datum: 2147483647 targetData.datum 2147483647
segment.source.lat  -1.274953 segment.source.lat 51.69684
segment.weight: 14.099872304804  segment.duration14.099872304804
slope 0
scaled_weight: 14.099872304804  scaled_duration14.099872304804


 sourceData.datum: 2147483647 targetData.datum 2147483647
segment.source.lat  -1.274179 segment.source.lat 51.697061
segment.weight: 14.099872304804  segment.duration14.099872304804
slope 0
scaled_weight: 14.099872304804  scaled_duration14.099872304804

... (many thousands of entries like this)
~~~~

The rasterbot profile I am using is:

~~~~

api_version = 2

function setup()
  local raster_path = "/home/avery/osrm-backend/data/diagonal_line_gap.asc"
  return {
    properties = {
      force_split_edges = true,
      process_call_tagless_node = false,
    },

    raster_source = raster:load(
      raster_path,
      -1.103655,   -- lon_min    
      -1.387372,  -- lon_max
      51.172252,  -- lat_min
      51.925993,  -- lat_max
      64,    -- nrows
      64     -- ncols
    )
  }
end

   


function process_way (profile, way, result)
  local highway = way:get_value_by_key("highway")
  local name = way:get_value_by_key("name")

  if name then
    result.name = name
  end

  result.forward_mode = mode.cycling
  result.backward_mode = mode.cycling

  result.forward_speed = 15
  result.backward_speed = 15
end

function process_segment (profile, segment)
  local sourceData = raster:query(profile.raster_source, segment.source.lon, segment.source.lat)
  local targetData = raster:query(profile.raster_source, segment.target.lon, segment.target.lat)
  io.write("\n\n " )
  io.write("sourceData.datum: " .. sourceData.datum .. " targetData.datum " .. targetData.datum .. "\n")
  io.write("segment.source.lat  " .. segment.source.lon .. " segment.source.lat " .. segment.source.lat .. "\n")
  
  io.write("segment.weight: " .. segment.weight .. "  segment.duration" .. segment.duration .. "\n")
  local invalid = sourceData.invalid_data()
  local scaled_weight = segment.weight
  local scaled_duration = segment.duration

 
  if sourceData.datum ~= invalid and targetData.datum ~= invalid then
    local slope = (targetData.datum - sourceData.datum) / segment.distance
    scaled_weight = scaled_weight / (1.0 - (slope * 5.0))
    scaled_duration = scaled_duration / (1.0 - (slope * 5.0))
    io.write("   slope: " .. slope .. "\n")
    io.write("   was weight: " .. segment.weight .. "\n")
    io.write("   new weight: " .. scaled_weight .. "\n")
    io.write("   was duration: " .. segment.duration .. "\n")
    io.write("   new duration: " .. scaled_duration .. "\n")
  

  else
    io.write("invalid data result\n")
  end

  
  segment.weight = scaled_weight
  segment.duration = scaled_duration


end

return {
  setup = setup,
  process_way = process_way,
  process_segment = process_segment
}

~~~~

The  .asc file used is the following (should be 128 columns including spaces or 64 without, by 64 rows)

~~~~

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
~~~~

Any assistance you could provide regarding how to resolve this issue and utilise third-party raster data would be very welcome.

Best wishes,

Avery Pennington

**Comment by AveryPenningtonGSI** [comment]
I notice that the documentation suggests that:

"They both return an instance of RasterDatum with a member std::int32_t datum. Out-of-bounds queries return a specific int std::numeric_limits<std::int32_t>::max(), which is bound as a member function to the lua state as invalid_data()."

I assume that the output I am getting, such as 
"sourceData.datum: 2147483647 targetData.datum 2147483647" 
is telling me that the raster function thinks that I am sending it out of bounds data. 
I have attempted to check this and don't think that this is the case. Is there a problem with the underlying raster reading functionality?

Thanks very much,
Avery

**Comment by emiltin** [comment]
Maybe check (or try) if lat / lon has been switched around either when you load data, or when you query.

Btw, this line incorrectly reports lon as "lat":
  io.write("segment.source.lat  " .. segment.source.lon .. " segment.source.lat " .. segment.source.lat .. "\n")

**Comment by penningav** [comment]
Hi,

Thank you, that would be great and an easy fix, but no that doesn't appear to be the problem. It's true that one of the print statements was mislabeled, thanks. The function call and argument order for raster:query was taken from the rasterbot.lua file in the osrm-backend distribution.

**Comment by AveryPenningtonGSI** [comment]
Hi,

Thank you, that would be great and an easy fix, but no that doesn't appear to be the problem. It's true that one of the print statements was mislabeled, thanks. The function call and argument order for raster:query was taken from the rasterbot.lua file in the osrm-backend distribution.

**Comment by AveryPenningtonGSI** [comment]
Ultimately, it was some kind of data formatting issue. Thanks.

**Comment by kazvin810** [comment]
im having the same issue, how did u fix "data formating issue"?

**Comment by penningav** [comment]
Hi,

I made sure that the ASCII formatted raster images were between 0 and 255
(this may not be necessary).
I made sure that the row and column size were exactly right.
I made sure that the corners of the map were always exactly aligned with
the corners of the raster, by cropping the map to the raster.
I used the raster:interpolate(profile.raster_source, segment.source.lon,
segment.source.lat), function to read the raster.
I also had to make sure I used "the most negative" value as the minimum
longitude, rather than the value closest to 0.  I had that backwards for a
bit.

I'm loading the raster with the following
    raster_source = raster:load(
      raster_path,
      -1.186577286620207,    -- lon_min
      -1.1230428196518962,  -- lon_max
      51.878731022703064,    -- lat_min
      51.91989754998965,  -- lat_max
      267,
      173
    )

Beyond that I studied the SRTM data in ASCII.
I think the feature works with both CH and MLD algorithms but I'm not
entirely sure about this, or whether there are differences in the routes
calculated between the different algorithms.

Kind regards,

Avery

**Comment by AveryPenningtonGSI** [comment]
Hi,

I made sure that the ASCII formatted raster images were between 0 and 255
(this may not be necessary).
I made sure that the row and column size were exactly right.
I made sure that the corners of the map were always exactly aligned with
the corners of the raster, by cropping the map to the raster.
I used the raster:interpolate(profile.raster_source, segment.source.lon,
segment.source.lat), function to read the raster.
I also had to make sure I used "the most negative" value as the minimum
longitude, rather than the value closest to 0.  I had that backwards for a
bit.

I'm loading the raster with the following
    raster_source = raster:load(
      raster_path,
      -1.186577286620207,    -- lon_min
      -1.1230428196518962,  -- lon_max
      51.878731022703064,    -- lat_min
      51.91989754998965,  -- lat_max
      267,
      173
    )

Beyond that I studied the SRTM data in ASCII.
I think the feature works with both CH and MLD algorithms but I'm not
entirely sure about this, or whether there are differences in the routes
calculated between the different algorithms.

Kind regards,

Avery

**Comment by kazvin810** [comment]
thanks a lot but it didnt work, all seems to be fine, changed the query for interpolate but still not working. Maybe it has to something with the projection? im runnning out of ideas :/.

Atte.
Kaz810

**Comment by kazvin810** [comment]
the only thing i havent done is to keep the data bewteween 0-255, how do i do that?

Atte.
Kaz810

**Comment by AveryPenningtonGSI** [comment]
Hi,

I just loaded my original .TIF file as a numpy array, and scaled it. Then exported as ASCII. I found the raster functionality and particularly the error messages or lack thereof very tricky to get going. I'll have a think if I have missed anything out. api=4 may be important in the lua profile.

Good luck,

Avery



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by siljuovix** [comment]
Hi, Avery

Can you elaborate on "api=4 may be important in the lua profile"?

In the [wiki](https://github.com/Project-OSRM/osrm-backend/wiki/Integrating-third-party-raster-data) the example uses api=1.  I am unable to find details on this in the docs.
