### ISSUE TITLE
Triangle inequality violations

### ISSUE THREAD

**Issue by cssartori** [Project-OSRM/osrm-backend#5178]
I'm using OSRM to get data related to distance/duration between a set of coordinates, in order to create a graph with which my application will later work. I'm using the C++ API on my local machine.

However, when obtaining this matrix there appears to be certain points that do not hold the triangle inequality. In other words, there are coordinates A, B and C, where 

d(A,B) + d(B,C) < d(A,C)  , where d(X,Y) is the distance between coordinates X and Y. 

This does not seem right to me, because if going A-B-C is faster/shorter than directly A-C, OSRM should return route A-B-C as the one to go from A to C. This effect happens even if I allow alternative paths to be considered (alternative = true) and I take the faster/shorter path between each pair of coordinates. This effect happens for both distance and duration data, though with distance the number of violations is usually bigger (I have no clue why).

Is there anything I should know about this issue? Or is anyone else experiencing this? I've tried searching for related problems, but all I could find were two issues a couple of years old, which I'm not sure are still valid considering the current updates to OSRM. Also, is there a way to overcome this, besides making the adjustments by hand (as in d(A,C) = d(A,B)+d(B,C))?

An example with three points is (my input data is OSM Berlin from Geofabrik):
A = ( 52.561346 , 13.504229 )
B = ( 52.492262 , 13.321100 )
C = ( 52.491818 , 13.321137 )

The distance data returned by OSRM is the following:
d(A,B) = 16278.20
d(B,C) = 84.10
d(A,C) = 16430.30
And: 16278.20 + 84.10 = 16362.30 < 16430.30
I would expect it to provide d(A,C) = 16362.30 instead.

**Comment by danpat** [comment]
Can you check if the equality is violated with `durations` as well?  

There are some bugs in the distance calculation for the `/table` plugin, it's possible this is what you're seeing:

https://github.com/Project-OSRM/osrm-backend/issues/5151

**Comment by cssartori** [comment]
Unfortunately duration is violated as well.
For the same example I gave, OSRM gives me the following information on duration (I'll refer as t(X,Y)):
t(A,B) = 1676.00
t(B,C) = 15.00
t(A,C) = 1698.10
And: 1676.00 + 15.00 = 1691.00 < 1698.10

**Comment by jcoupey** [comment]
Given that OSRM provides optimal routes, we should expect the triangle inequality to hold on _the underlying metric_, which is neither duration, nor distance, but weight.

Weights are derived from speed/duration in the profile, this is probably why you experience a lower number of violations with duration than with distance.

**Comment by cssartori** [comment]
Thank you for the clarification @jcoupey regarding this weight issue, I was actually not entirely aware of that.

Is there anyway to overcome this? Or anyway I could tell the router to use the best metric for my purpose?

On a side question: when I ask for alternative paths between two points, OSRM returns alternative paths that are somehow equally optimal based on this weight metric? Or does it return some paths that may be "more optimal" regarding distance, or duration?

**Comment by jcoupey** [comment]
@cssartori you can adjust the routing metric in the profile here: https://github.com/Project-OSRM/osrm-backend/blob/v5.18.0/profiles/car.lua#L18-L23.

**Comment by TheMarex** [comment]
This is an interesting side-effect, I guess that means for a few VRP related algorithms the durations of the minimal-weight routes might cause problems. Good catch @jcoupey! Closing as "solved".

**Comment by selting** [comment]
I came across this issue because I had the same problem. Once I had figured out how to run the docker container with the adjusted profile (Thanks to @jcoupey's [comment](https://github.com/Project-OSRM/osrm-backend/issues/5178#issuecomment-415133620)) the issue initially seemed fixed. However, I have now found an example, where the triangle inequality is violated:

**request:**
`http://127.0.0.1:5001/table/v1/car/16.50193972187905,48.25315162838145;16.36271274210034,48.1945653714254;16.30897039533933,48.15882063983586?annotations=distance`

**response:**
`{
    "code": "Ok",
    "distances":
    [
        [
            0,
            13848,
            20430.1
        ],
        [
            14561.8,
            0,
            6582
        ],
        [
            20206.5,
            6924.9,
            0
        ]
    ],
    "destinations":
    [
        {
            "hint": "BTgBgEw4AYCGAgAApgEAAAAAAAAAAAAAJDiBQpiQKEIAAAAAAAAAAGAAAABAAAAAAAAAAAAAAABSAQAA_8v7AOxI4AK0zPsA4EjgAgAAnwtyhU9c",
            "distance": 13.501771,
            "name": "Schukowitzgasse",
            "location":
            [
                16.501759,
                48.253164
            ]
        },
        {
            "hint": "7-MCgP___3_cAAAA-gAAAGYBAABuAAAAzQKxQXeFOUCFOg9ClW4wQSAAAAAlAAAANgAAABEAAABSAQAAUaz5AFFk3wLZrPkABWTfAgEAzw1yhU9c",
            "distance": 13.180577,
            "name": "Margaretenstraße",
            "location":
            [
                16.362577,
                48.194641
            ]
        },
        {
            "hint": "Sg0DgIcNA4DTAgAAMAIAAAAAAAAAAAAAAPGQQnvIX0IAAAAAAAAAAGwAAABVAAAAAAAAAAAAAABSAQAAStr4ABnY3gLq2vgAZdjeAgAADwlyhU9c",
            "distance": 14.595354,
            "name": "Karl-Heinz-Straße",
            "location":
            [
                16.30881,
                48.158745
            ]
        }
    ],
    "sources":
    [
        {
            "hint": "BTgBgEw4AYCGAgAApgEAAAAAAAAAAAAAJDiBQpiQKEIAAAAAAAAAAGAAAABAAAAAAAAAAAAAAABSAQAA_8v7AOxI4AK0zPsA4EjgAgAAnwtyhU9c",
            "distance": 13.501771,
            "name": "Schukowitzgasse",
            "location":
            [
                16.501759,
                48.253164
            ]
        },
        {
            "hint": "7-MCgP___3_cAAAA-gAAAGYBAABuAAAAzQKxQXeFOUCFOg9ClW4wQSAAAAAlAAAANgAAABEAAABSAQAAUaz5AFFk3wLZrPkABWTfAgEAzw1yhU9c",
            "distance": 13.180577,
            "name": "Margaretenstraße",
            "location":
            [
                16.362577,
                48.194641
            ]
        },
        {
            "hint": "Sg0DgIcNA4DTAgAAMAIAAAAAAAAAAAAAAPGQQnvIX0IAAAAAAAAAAGwAAABVAAAAAAAAAAAAAABSAQAAStr4ABnY3gLq2vgAZdjeAgAADwlyhU9c",
            "distance": 14.595354,
            "name": "Karl-Heinz-Straße",
            "location":
            [
                16.30881,
                48.158745
            ]
        }
    ]
}`

**triangle inequality violation:**
`distances[0][2] > distances[0][1] +distances[1][2]`
20430.1 > 13848 + 6582

the car **profile** has been adjusted as follows:
`properties = {
      max_speed_for_map_matching      = 180/3.6, -- 180kmph -> m/s
      -- For routing based on duration, but weighted for preferring certain roads
      -- weight_name                     = 'routability',
      -- For shortest duration without penalties for accessibility
      -- weight_name                     = 'duration',
      -- For shortest distance without penalties for accessibility
      weight_name                     = 'distance',
      process_call_tagless_node      = false,
      u_turn_penalty                 = 20,
      continue_straight_at_waypoint  = true,
      use_turn_restrictions          = true,
      left_hand_driving              = false,
      traffic_light_penalty          = 2,
    },`
(`weight_name` was set from `routability` to `distance`, nothing else was changed, I double checked)

Yes, the violation is absolutely minimal (0.1), but still, I think this shouldn't be happening.
Can anyone spot a mistake in my workflow/setup?
Could this be an issue with floating-point precision?
