### ISSUE TITLE
Compiling Example in Windows

### ISSUE THREAD

**Issue by lthomasJeeper** [Project-OSRM/osrm-backend#5179]
Hi,

I was able to build the osrm-backed using build-local.bat.   Now i want to build  example that uses Libosrm.

When I tried cmake it gives below error

Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibOSRM (missing: LibOSRM_LIBRARY_DIRS LibOSRM_CXXFLAGS
  LibOSRM_LIBRARIES LibOSRM_DEPENDENT_LIBRARIES LibOSRM_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibOSRM.cmake:58 (find_package_handle_standard_args)
  CMakeLists.txt:32 (find_package)

How to build the example given in the example directory in Windows?

thanks,
L thomas

**Comment by daniel-j-h** [comment]
It looks like you are missing the pkg-config executable CMake uses to figure out dependencies.
