### ISSUE TITLE
How to Building OSRM  on my fedora 26

### ISSUE THREAD

**Issue by geogeorgejoseph** [Project-OSRM/osrm-backend#5183]
### How to Building OSRM on my fedora 26 and how to run it.

**i just used the below steps, but it is not working properly.**

```
git clone https://github.com/Project-OSRM/osrm-backend.git
cd osrm-backend
mkdir build
cd build
cmake .. -DENABLE_MASON=ON
make
make install


```

**Comment by geogeorgejoseph** [comment]
### How to get the serviceUrl after doing below steps

```
git clone https://github.com/Project-OSRM/osrm-backend.git
cd osrm-backend
mkdir build
cd build
cmake .. -DENABLE_MASON=ON
make
make install
```

**Comment by chaupow** [comment]
Try the steps in `Quickstart`:
https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM#quickstart

**Comment by geogeorgejoseph** [comment]
After completing the all steps i got the map.

But some issues coming after selecting source and destination points.



![osrm-demo](https://user-images.githubusercontent.com/25584016/44839691-fd36dd00-ac5c-11e8-988a-666f574edb51.png)

**Comment by daniel-j-h** [comment]
Closing here; looks like you got it compiling after all.

I recommend simply starting out with the backend and frontend pre-built docker images.

To debug routes you can check e.g. the `/debug` endpoint; see an example in action here https://www.mapbox.com/get-directions/debug/
