### ISSUE TITLE
RUNTIME Disk and Memory Requirements for Planet

### ISSUE THREAD

**Issue by neilRGS** [Project-OSRM/osrm-backend#5184]
Hi.
Our client is about to order a machine at Rackspace so are asking for RAM requirements.
Is the planet compilation requirement unchanged from last July, i.e. still around 248GB RAM for foot?
[ https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements ]
I'm wondering if I should recommend 384GB rather than 256GB.

Your thoughts would be appreciated.

Many thanks and best regards,

Neil.

**Comment by neilRGS** [comment]
Hello again.
Actually, as the customer wishes to run all three profiles, I think it might be safer to use a machine with 512GB RAM.

Does that make sense or am I in danger of over-engineering it.

Regards,

Neil.

**Comment by neilRGS** [comment]
Hi.
I updated the question to make it a bit more specific.
To summarise, what I am looking for is how big are the combined files for foot, bicycle and car?
I intend to run all three profiles on different ports, one, large machine but need a steer on how much RAM to give the machine.
It is not going to be a virtual machine (client's choice), so I need to be able to give a realistic number.

Kind regards,

Neil.

**Comment by danpat** [comment]
@neilRGS I don't think anyone has a concrete answer to this, it's not something we formally track, and it changes over time as OSM evolves.

My recommendation would be to try it: spend a few $$$ and rent a very big machine on AWS/Google Cloud/etc temporarily, and do the processing and run the routing server, then *measure* the usage.  I can't think of a way to get more definitive than that.

Note that you do need to allow some overhead - each request that is processed requires some RAM, so you'll need extra to support the size + concurrency of your incoming request load.

**Comment by neilRGS** [comment]
Ok. Thanks @danpat 
I'll make that suggestion to the client.

All the best,

Neil.
