### ISSUE TITLE
Two or more geometries agregated in one step

### ISSUE THREAD

**Issue by flacombe** [Project-OSRM/osrm-backend#5190]
I recently discovered that osrm may aggregate several different geometries in one single step in its responses.
Nevertheless, those geometries are really different and it makes the process of the response really hard.

In the following output, step 0 have many more nodes than it should (only first 6) and remaining have to go in a separate step since both don't have the same speed nor the same rate (not to mention the same name)

```
{
	"code": "Ok",
	"routes": [{
		"legs": [{
			"steps": [{
				"intersections": [{
					"out": 0,
					"entry": [true],
					"bearings": [338],
					"location": [-1.20108, 48.82753]
				}, {
					"out": 2,
					"location": [-1.202647, 48.832119],
					"bearings": [165, 255, 330],
					"entry": [false, true, true],
					"in": 0
				}, {
					"out": 2,
					"location": [-1.20278, 48.832321],
					"bearings": [60, 150, 330],
					"entry": [true, false, true],
					"in": 1
				}, {
					"out": 1,
					"location": [-1.203486, 48.832763],
					"bearings": [105, 195, 285],
					"entry": [false, true, true],
					"in": 0
				}, {
					"out": 1,
					"location": [-1.203488, 48.832756],
					"bearings": [15, 300],
					"entry": [false, true],
					"in": 0
				}, {
					"out": 1,
					"location": [-1.203991, 48.833011],
					"bearings": [177, 353, 357],
					"entry": [false, false, true],
					"in": 0
				}],
				"driving_side": "right",
				"geometry": {
					"coordinates": [
						[-1.20108, 48.82753],
						[-1.20123, 48.827775],
						[-1.201429, 48.82828],
						[-1.201428, 48.828308],
						[-1.201419, 48.828575],
						[-1.201364, 48.828912],
						[-1.201114, 48.82936],
						[-1.201017, 48.82964],
						[-1.201042, 48.829924],
						[-1.201191, 48.830198],
						[-1.201774, 48.830732],
						[-1.202019, 48.830999],
						[-1.202167, 48.831215],
						[-1.202647, 48.832119],
						[-1.20278, 48.832321],
						[-1.202901, 48.832452],
						[-1.203048, 48.832595],
						[-1.203319, 48.832723],
						[-1.203486, 48.832763],
						[-1.203487, 48.832759],
						[-1.203488, 48.832756],
						[-1.203653, 48.832814],
						[-1.203982, 48.832879],
						[-1.203991, 48.833011],
						[-1.203997, 48.83309]
					],
					"type": "LineString"
				},
				"mode": "walking",
				"duration": 23251.3,
				"maneuver": {
					"bearing_after": 338,
					"type": "depart",
					"modifier": "left",
					"bearing_before": 0,
					"location": [-1.20108, 48.82753]
				},
				"ref": "D 999",
				"weight": 658.3,
				"distance": 709,
				"name": "38140772"
			}, {
				"intersections": [{
					"out": 3,
					"location": [-1.203997, 48.83309],
					"bearings": [75, 173, 177, 256],
					"entry": [true, false, false, true],
					"in": 1
				}, {
					"out": 2,
					"location": [-1.20408, 48.833076],
					"bearings": [75, 180, 255],
					"entry": [false, false, true],
					"in": 0
				}, {
					"out": 2,
					"location": [-1.205026, 48.832878],
					"bearings": [75, 165, 255],
					"entry": [false, false, true],
					"in": 0
				}, {
					"out": 2,
					"location": [-1.205372, 48.833004],
					"bearings": [150, 210, 330],
					"entry": [false, false, true],
					"in": 0
				}],
				"driving_side": "right",
				"geometry": {
					"coordinates": [
						[-1.203997, 48.83309],
						[-1.20408, 48.833076],
						[-1.204378, 48.833023],
						[-1.204403, 48.833018],
						[-1.205026, 48.832878],
						[-1.20512, 48.832856],
						[-1.205122, 48.832857],
						[-1.205287, 48.832915],
						[-1.205372, 48.833004],
						[-1.205404, 48.833036]
					],
					"type": "LineString"
				},
				"mode": "walking",
				"duration": 4.8,
				"maneuver": {
					"bearing_after": 254,
					"type": "turn",
					"modifier": "left",
					"bearing_before": 355,
					"location": [-1.203997, 48.83309]
				},
				"weight": 23.3,
				"distance": 116.1,
				"name": "602124960"
			}],
		"distance": 1087.9,
		"duration": 23266.6,
		"weight_name": "surface",
		"weight": 734.2
	}]
}
```

Have a look to debug view and route below
![capture du 2018-08-27 12-07-38](https://user-images.githubusercontent.com/5690599/44989001-c3334700-af8c-11e8-8d66-3a81b8cf3942.png)
![capture du 2018-08-27 12-08-33](https://user-images.githubusercontent.com/5690599/44989005-c595a100-af8c-11e8-9d56-cd320a06102a.png)

**Comment by flacombe** [comment]
@danpat can you eventually explain me why this is happening if you're knowledgeable about this issue please?

**Comment by danpat** [comment]
In the example above, can you confirm the request you made to generate that big list of coordinates?

If I map them at GeoJSON.io, it looks like the startpoint for the route is actually further south:

![Screen Shot 2020-01-13 at 1 30 17 PM](https://user-images.githubusercontent.com/1892250/72293678-e05c3900-3608-11ea-9f02-d0881f452068.png)

Are you sure you've got the right response body to go with your request in this example?

**Comment by flacombe** [comment]
Thank you to have a look at it
Yes, I'm sure of it. Even if my screen actually shows a shorter answer.

The most important point is for a single OSRM step, you've got a big slice of "Rue des Etangs" OSM ways and the end of my custom geometry while I expect to have two separate steps as the attributes of them two are really different. The speed is 10 km/h for Rue des Etangs and 90 km/h for my custom geometry.

Even if we can't get the two steps expected, it would be nice to know which criteria allows the aggregation of such different ways.

The only fix I was told about is to use nodes annotations to get back the original geometries from a database (which works actually)

**Comment by danpat** [comment]
Oh, I think I understand the question - it's not so much about the start point, it's more about which maneuvers show up in the steps in the API response.

For doing any kind of quantitative analysis, OSRM steps are likely not a very reliable thing.  The "steps" are designed to be "human consumable instructions" - there are a huge pile of heuristics in place that decide when and where to collapse steps together because a human doesn't need to hear superfluous instructions.

What you could try would be commenting out all the "guidance improvement" logic here:

https://github.com/Project-OSRM/osrm-backend/blob/f520379419aa2d5f11b6c0dfa25fb16967f63e04/include/engine/api/route_api.hpp#L916-L965

At the beginning, the `assembleSteps` function returns the raw sequence of steps - every time there is a maneuver (a turn, change of road properties, etc), a step is generated.  The code block linked above then collapses many of these together as "not useful for humans" - in your case, it sounds like you want them all.
