### ISSUE TITLE
Adding custom weights to route calculation and returning them via json output

### ISSUE THREAD

**Issue by AveryPenningtonGSI** [Project-OSRM/osrm-backend#5191]
Hi,
I am attempting to load raster values that will not be used to modify the actual duration of a segment. However, I do want to incorporate this value into the calculation of the route, and to return the weight in the json output of osrm-routed.

For example, if I have a "scenic beauty" score on a raster map, I want to be able to find the route that has a higher "scenic beauty". Is this custom-weighting of the route possible? 

Currently "weight" in the returned json output is essentially duration (which makes sense if the raster value is used for slope, but not for this application). Is it possible to add a parameter to the output geojson?

Is this feature documented? Any assistance would be really appreciated. 

Thanks very much,

Avery

**Comment by AveryPenningtonGSI** [comment]
Does the routing engine only modify routes based on duration? I am modifying the weight, but it doesn't seem to affect the calculated routes, only modifying the segment.duration seems to?

Thanks,

Avery

**Comment by dineshnagarit** [comment]
Any updates on this so far? Eagerly waiting.

**Comment by AveryPenningtonGSI** [comment]
Can anyone who knows how to use raster values please comment? It would be extremely helpful.

**Comment by AveryPenningtonGSI** [comment]
Apparently one can only change the name of the weight, as a tag to use in the .lua code.
