### ISSUE TITLE
Windows builds broken due to number formatting optimizations

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#5198]
This PR https://github.com/Project-OSRM/osrm-backend/pull/5188 broke our Windows builds, because it depends on https://code.google.com/archive/p/msinttypes/, which I neglected to include.

We should third_party https://code.google.com/archive/p/msinttypes/, and add it to the include path on Windows

**Comment by PrefabPanda** [comment]
I've been having trouble building the source too, sadly my C++ is rather limited so I've got with a revert on my local repo for this commit to hopefully see if it'll work!

**Comment by SiarheiFedartsou** [comment]
Windows CI is green now.
