### ISSUE TITLE
Docker image not found for 5.19.0

### ISSUE THREAD

**Issue by pierreinglebert** [Project-OSRM/osrm-backend#5207]
It seems that the [v5.19.0](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.19.0) version is not available on DockerHub https://hub.docker.com/r/osrm/osrm-backend/tags/

**Comment by amirmasud** [comment]
The same for 5.20

**Comment by pierreinglebert** [comment]
as I'm now using the v5.22.0. I'm closing the issue.
