### ISSUE TITLE
npm install node-pre-gyp@0.6.36

### ISSUE THREAD

**Issue by 185866519** [Project-OSRM/osrm-backend#5210]
os：centos7.2  osrm 能够在centos7.2系统执行么，

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/documentation/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by danpat** [comment]
@185866519 Warnings during `npm install` are common - I cannot see any fatal errors there, and none of those messages are specific to OSRM.
