### ISSUE TITLE
Roundabouts ignored?

### ISSUE THREAD

**Issue by hutch120** [Project-OSRM/osrm-backend#5211]
Hi Guys,

Hoping someone can help.. I've been directed here by Mapbox support.

I'm having an issue with the steps returned by the Mapbox API for the smaller roundabouts in this area:
https://www.openstreetmap.org/#map=19/-38.37506/144.87518

Here is a google map of a trip through one of the small roundabouts. It correctly includes the roundabout and says, "At the roundabout continue straight..." https://goo.gl/maps/viRpUmNB2bu

Unfortunately, this step is missing from Mapbox instructions, as shown in the JSON output from Mapbox directions API here:
https://gist.github.com/hutch120/9b4bb816bdc3b7101dbed4bd8e6853ba

Actual API request (needs token).
https://api.mapbox.com/directions/v5/mapbox/driving/144.87506%2C-38.37456%3B144.87500%2C-38.37549.json?access_token=[ACCESS_TOKEN]&steps=true

Is there an attribute or something I need to add to the roundabouts in OSM to get them to be recognised as steps in the route?

Regards,
Simon

**Comment by danpat** [comment]
Currently, OSRM only pays attention to the `junction=roundabout` tag, despite there being several other roundabout-related tags available.  When the radius is <15m, and has 4 entry/exits, OSRM treats it as a normal intersection, and just announces it as a turn.  The intention here is to avoid "take the 3rd exit"-like instructions, when a simple "turn right" would do.

The logic is here:

https://github.com/Project-OSRM/osrm-backend/blob/72e03f9af9824cbb1d26cba878f242eb0feae584/src/guidance/roundabout_handler.cpp#L354-L359


Ultimately, what I think OSRM needs is a broader understanding of other OSM roundabout tags:

https://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout#Possible_misinterpretations

If we did this, we'd emit turn-only instructions for `highway=mini_roundabout` only, and remove the radius calculation from the heuristic altogether.

In your example, the radius of these roundabouts is about 13m, so it's triggering the "roundabout intersection" logic, and just emitting a simple turn.

A hacky fix would be to grow the roundabouts a bit, so they're larger than 15m across in OSM.

**Comment by hutch120** [comment]
@danpat Thank you so much for a quick and concise response!

I've adjusted the size of the roundabouts in OSM... awaiting import into Mapbox.

Very much appreciated!

**Comment by hutch120** [comment]
It appears I didn't wait long enough (waited overnight), for the data to get into Mapbox... this morning, it is now categorising them as roundabouts.
