### ISSUE TITLE
It which cases is it acceptable to reuse OSRM preprocessed data?

### ISSUE THREAD

**Issue by htaunay** [Project-OSRM/osrm-backend#5213]
A while ago I was looking for preprocessed extracts of OSM planet data with OSRM, since the memory requirements were quite high to extract but not necessarily so to run the backend server.

Quickly I was informed that apparently there is no such thing, since there are little guarantees that osrm data preprocessed in once system would work in a different one.

I'm interested in understanding more about this limitation, and what exactly influences osrm data being system specific. Are we talking only about OS + CPU architecture? Also, has anyone experienced issues with re-using osrm data in non-identical systems?

**Comment by systemed** [comment]
I've found that creating files locally on an HP box running Ubuntu, then uploading to a Hetzner server running (a different version of) Ubuntu, is absolutely fine. But creating files on the same HP box, then uploading to a Microsoft Azure instance running Ubuntu, doesn't work.

**Comment by daniel-j-h** [comment]
Most of the file are in-memory datastructure dumps to disk. Therefore it depends on how your compiler lays out the datastructures, endianess, padding, your stdlib, etc.

There is a bit of information in tickets such as https://github.com/Project-OSRM/osrm-backend/issues/2242 and others. But in general until we use a proper self-contained and portable serialization format such as CapnProto or FlatBuffers I would be very careful.

**Comment by xruiz** [comment]
Now that there is a docker image with all dependencies and a stable environment, is still having the same issues?
