### ISSUE TITLE
Osrm routing api - highway tags

### ISSUE THREAD

**Issue by bcoghe** [Project-OSRM/osrm-backend#5221]
Is it possible to get the highway tags with osrm routing? If so, how?

**Comment by chaupow** [comment]
Where do you need the tags? 
- During extraction to change the or turn or edge weights? Maybe [profiles](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md) can help, Here an example of how the highway tags are used to set the speed: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L140
- After receiving the response? Depends. You can see things [eg. ramps](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#stepmaneuver-object) in the response or use the [route-annotator](https://github.com/Project-OSRM/osrm-backend/issues/5202#issuecomment-425112575)

Without more information this question is not easy too answer. I hope the pointers a helpful, if not feel free to open another issue with more details.
