### ISSUE TITLE
Access denied on http://router.project-osrm.org/ 

### ISSUE THREAD

**Issue by retorquere** [Project-OSRM/osrm-backend#5222]
When accessing http://router.project-osrm.org/ I get

```
<Error><script/><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>873B2333D02AFF2D</RequestId><HostId>TjyJ55qvpVPlm7QDzomXh7b2sMrCACmj0x1Vi0pIlO6vQlka8B6jJDE1X9Wh2wW7rRcnM996fjI=</HostId></Error>
```

**Comment by danpat** [comment]
@retorquere The root path `/` does not serve anything useful - you need to append `/viaroute/v1/driving/....` to make a proper API request.

**Comment by retorquere** [comment]
I'm also getting a 403 on http://router.project-osrm.org/match/v1/car/5.862511,51.954638;5.867173,51.954135;5.868375,51.954518?overview=full&annotations=true

**Comment by danpat** [comment]
@retorquere That link is working perfectly for me, and I can see plenty of requests showing up in our logs.
