### ISSUE TITLE
Unable to start routing with --shared-memory enabled

### ISSUE THREAD

**Issue by alexeystrakh** [Project-OSRM/osrm-backend#5223]
I'm trying to combine a few regions into under a single routing backend. I want to use --shared-memory and load there all my regions data. When I run the following container to put region data into shared memory I get an error:

> docker run -t -v $(pwd):/data osrm/osrm-backend osrm-datastore "/data/mycoolregion-latest.osrm"

```
**[warn] Could not request RAM lock**
[info] Data layout has a size of 1894 bytes
[info] Allocating shared memory of 75870424 bytes
**[warn] could not lock shared memory to RAM**
[info] Data layout has a size of 1661 bytes
[info] Allocating shared memory of 168078576 bytes
**[warn] could not lock shared memory to RAM**
[info] All data loaded. Notify all client about new data in:
[info] /static  0
[info] /updatable       1
[info] All clients switched.
```

And then when I tried to start the `osrm-route` it fails because (I assume) is unable to find shared memory data:

> docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed --algorithm mld --shared-memory

```
[info] starting up engines, v5.20.0
[info] Loading from shared memory
[info] Threads: 2
[info] IP address: 0.0.0.0
[info] IP port: 5000
terminate called after throwing an instance of 'osrm::util::exception'
  what():  No shared memory block 'osrm-region' found, have you forgotten to run osrm-datastore?include/storage/shared_monitor.hpp:83
```

I've followed this [Shared Memory](https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory) guide to increase my shared memory limits with no luck to run `osrm-datastore`:

- updated system limits by editing /etc/sysctl.conf
- sysctl -p
- update user limits by editing /etc/security/limits.conf
- activated user limits by editing /etc/pam.d/su and /etc/pam.d/common-session
- sudo -i -u root

```
    Distributor ID: Ubuntu
    Description:    Ubuntu 18.04.1 LTS
    Release:        18.04
    Codename:       bionic
```

What could be wrong in my setup?

**Comment by danpat** [comment]
@alexeystrakh Take a look at this SO description of sharing IPC shared memory blocks beween Docker containers: https://stackoverflow.com/questions/23889187/is-it-possible-to-share-memory-between-docker-containers

I believe your problem is that your containers are isolated from each other - the shared memory you allocated in the first invocation is simply not visible to the second container you launch.  The link about describes how to get containers to share IPC namespace, which is what you need for the `--shared-memory` flag and `osrm-datastore` to communicate properly.

**Comment by alexeystrakh** [comment]
@danpat thank you for the response, it totally makes sense. My ultimate goal is to run two (or more) regions under a single server endpoint (osrm-routed). I decided to configure everything inside a single docker to make it simpler and the issue is still the same, osrm-routed is unable to build routes using multiple regions:

```
> osrm-datastore --spring-clean
> osrm-datastore --dataset-name="region1" "/data/region1-latest.osrm"
> osrm-datastore --dataset-name="region2" "/data/region2-latest.osrm"
> osrm-datastore --list
# [info] name     shm key timestamp       size
# [info] region1/static   0       1       75870424
# [info] region1/updatable        1       1       168078576
# [info] region2/static   2       1       249865060
# [info] region2/updatable        3       1       545426113
```
all started and loaded without an issue, I can see shared memory storages fine.  But when I start the osrm-routed engine, it's unable to load that shared-memory dataset:

```
> osrm-routed --algorithm mld --shared-memory
# [info] starting up engines, v5.20.0
# [info] Loading from shared memory
# [info] Threads: 2
# [info] IP address: 0.0.0.0
# [info] IP port: 5000
# terminate called after throwing an instance of 'osrm::util::exception'
#   what():  Could not find a shared memory region for "/data". Did you run osrm-datastore?
# Aborted (core dumped)
```
I can start it only by specifying the dataset name. The following works fine and I can build routes for region1 but not for region2:

```
> osrm-routed --dataset-name region1 --algorithm mld --shared-memory
```

If I load the datasets without specifying the dataset-name, every next dataset replaces previous. I know that I can start two instances of osrm-routes and then use nginx to proxy calls to a specific region but that is not what I want, because that will add client-side work to keep track of every region and map it to a specific osrm-routed instance.

How can I load both regions and build routes having a single osrm-routed engine?

**Comment by danpat** [comment]
@alexeystrakh I see - you want a single OSRM to serve routes from two separate geographies?

Unfortunately, the dataset name feature doesn't work like this.  Using the approach you've got currently, you would need to run two copies of `osrm-routed` on different port numbers, then insert some kind of reverse proxy (like nginx) in front that knows how to direct requests to the correct `osrm-routed` instance.

`osrm-routed` doesn't know how to select between multiple datasets like this - it can only use one at a time.

To achieve what you want, you would need to pre-merge the `.osm.pbf` files *before* processing, and serve it all from a single `osrm-routed` process.

**Comment by alexeystrakh** [comment]
@danpat I got it, thanks for clarifications! It answers my question 👍
