### ISSUE TITLE
Generating edge-expanded graph representation

### ISSUE THREAD

**Issue by Elentary** [Project-OSRM/osrm-backend#5224]
While trying to deploy OSRM-backend via docker on my server, the process is getting stuck at 

> [info] writing street name index ... ok, after 11.362s
[info] extraction finished after 33423.1s
[info] Generating edge-expanded graph representation

CPU usage is around 10%, RAM - 94%, swap - 29/96 GB
I ran it by executing `docker run -t -v $(pwd):/data osrm/osrm-backend:v5.18.0-d
ebug osrm-extract -p /opt/car.lua /data/europe-latest.osm.pbf`

On version v5.19.0 (latest docker build) it stucks at 80% of `[info] Generating edge-expanded graph representation`

Server configuration:
Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, 4 cores
8GB RAM
96GB swap

Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M  752K  797M   1% /run
/dev/vda1       155G  129G   27G  83% /
tmpfs           3.9G   28K  3.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/vda15      105M  3.4M  102M   4% /boot/efi
tmpfs           798M     0  798M   0% /run/user/1000

**Comment by jcoupey** [comment]
@Elentary 8GB RAM is really not enough to process OSM data for Europe, and relying on swap just makes things veeeeeeeeery slow.

**Comment by Elentary** [comment]
> @Elentary 8GB RAM is really not enough to process OSM data for Europe, and relying on swap just makes things veeeeeeeeery slow.

Okey, so what is the minimal configuration for Europe ?

**Comment by Elentary** [comment]
Okey, I have run osrm-extract on another machine with 100gb RAM and it seems to be successful. Can I then transfer all the files to my old 8gb RAM machine and run other commands there ?

**Comment by danpat** [comment]
@Elentary You can try :-)

OSRM datafiles are *generally* portable between similar machines, but because they contain raw memory dumps, they sometimes won't be.  Windows<->Linux copies don't work, for example.

The `osrm-contract` / `osrm-partition/osrm-customize` steps use *less* RAM, but still require more than `osrm-routed`.
