### ISSUE TITLE
Question: FIles created by osrm-contract

### ISSUE THREAD

**Issue by neilRGS** [Project-OSRM/osrm-backend#5228]
Hi.
I have run the osrm-extract and then osrm-contract on a planet-latest data set.

At the end of the osrm-contract process, the only file additional to those created by osrm-extract is planet-latest.osrm.datasource_names.

Is this expected?

Here's my list of files, after both -extract and -contract process have run:

```
-rw-rw-r-- 1 osrmuser osrmuser  42G Oct  4 04:04 planet-latest.osm.pbf
-rw-rw-r-- 1 osrmuser osrmuser  50G Oct  8 15:26 planet-latest.osrm
-rw-rw-r-- 1 osrmuser osrmuser 3.8G Oct  8 17:06 planet-latest.osrm.cnbg
-rw-rw-r-- 1 osrmuser osrmuser 3.8G Oct  8 17:11 planet-latest.osrm.cnbg_to_ebg
-rw-rw-r-- 1 osrmuser osrmuser  68K Oct 10 08:40 planet-latest.osrm.datasource_names
-rw-rw-r-- 1 osrmuser osrmuser  20G Oct  8 18:07 planet-latest.osrm.ebg
-rw-rw-r-- 1 osrmuser osrmuser 5.7G Oct  8 18:06 planet-latest.osrm.ebg_nodes
-rw-rw-r-- 1 osrmuser osrmuser 6.7G Oct  8 17:57 planet-latest.osrm.edges
-rw-rw-r-- 1 osrmuser osrmuser 3.8G Oct  8 17:58 planet-latest.osrm.enw
-rwx------ 1 osrmuser osrmuser  23G Oct  8 18:06 planet-latest.osrm.fileIndex
-rw-rw-r-- 1 osrmuser osrmuser  25G Oct  8 17:58 planet-latest.osrm.geometry
-rw-rw-r-- 1 osrmuser osrmuser 4.4G Oct  8 17:57 planet-latest.osrm.icd
-rw-rw-r-- 1 osrmuser osrmuser 6.0K Oct  8 17:25 planet-latest.osrm.maneuver_overrides
-rw-rw-r-- 1 osrmuser osrmuser 167M Oct  8 15:26 planet-latest.osrm.names
-rw-rw-r-- 1 osrmuser osrmuser  14G Oct  8 17:06 planet-latest.osrm.nbg_nodes
-rw-rw-r-- 1 osrmuser osrmuser 6.0K Oct  8 15:26 planet-latest.osrm.properties
-rw-rw-r-- 1 osrmuser osrmuser  93M Oct  8 18:06 planet-latest.osrm.ramIndex
-rw-rw-r-- 1 osrmuser osrmuser 4.0K Oct  8 17:26 planet-latest.osrm.restrictions
-rw-rw-r-- 1 osrmuser osrmuser 3.5K Oct  8 17:57 planet-latest.osrm.tld
-rw-rw-r-- 1 osrmuser osrmuser 5.5K Oct  8 17:57 planet-latest.osrm.tls
-rw-rw-r-- 1 osrmuser osrmuser 2.0G Oct  8 17:26 planet-latest.osrm.turn_duration_penalties
-rw-rw-r-- 1 osrmuser osrmuser  12G Oct  8 17:26 planet-latest.osrm.turn_penalties_index
-rw-rw-r-- 1 osrmuser osrmuser 2.0G Oct  8 17:26 planet-latest.osrm.turn_weight_penalties
```

Advice will be appreciated.

Kind regards,

Neil.

**Comment by danpat** [comment]
@neilRGS Looks ike somethign went wrong - there should be *at least* a file called `planet-latest.osrm.hsgr` - this file contains the actual CH graph structure, and without it, the data is unusable.

Check the output from your `osrm-contract` invocation - I suspect it died with an error before completing.

**Comment by neilRGS** [comment]
Hi Dan.
I thought there was something amiss.  In a previous European dataset, I have an .hsgr and also a .timestamp file (though the latter is tiny).
I'll run the contract process again and see what happens this time.  I am running with nohup so the output will go to a file and I can close my ssh session.

N.

**Comment by danpat** [comment]
👍 I'd guess that you ran out of RAM or something similar.  `foot.lua` creates the largest graph, because it considers many OSM way types as walkable.
