### ISSUE TITLE
Avoid certain polygon(s) while generating route

### ISSUE THREAD

**Issue by carlosen14** [Project-OSRM/osrm-backend#5229]
Will be there a way yo avoid certain polygon área?

Example: 
Point A is up, point B is bottom, normal route will give you the red line as a route. But if you specify a polygon to restrict that area, then will give you a route like blue line.

I know OSRM doesn't support this for now, but do you have any hint to start with it?

![geojson io 1](https://user-images.githubusercontent.com/9368632/46822995-98d66580-cd52-11e8-91d7-5469ec474e32.png)

**Comment by danpat** [comment]
This type of query adjustment will likely never be possible with the CH algorithm - but it's probably possible for MLD and A*.

Currently, OSRM supports all features on all routing algorithms - supporting this kind of feature just for a subset of the routing algorithms would require some rework, and would make OSRM a bit more complicated to understand.

This ticket should stay open as a feature request, but there are no current plans for anyone to work on it.

**Comment by carlosen14** [comment]
Example:

```javascript
var osrm = new OSRM("berlin-latest.osrm");
osrm.route(
{
coordinates: [[13.438640,52.519930], [13.415852,52.513191]],
avoid: [ /*PolygonA*/
  [latA1, lngA1], [latA2, lngA2], [latA3, lngA3]
], [/*PolygonB*/
  [latB1 ,lngB1], [latB2, lngB2], [latB3, lngB3]
]
}, function(err, result) {
  if(err) throw err;
  console.log(result.waypoints); // array of Waypoint objects representing all waypoints in order
  console.log(result.routes); // array of Route objects ordered by descending recommendation rank
});
```

**Comment by carlosen14** [comment]
> This ticket should stay open as a feature request, but there are no current plans for anyone to work on it.

Ok, i understand.. thanks!

**Comment by imSaharukh** [comment]
HI, 
i also looking for this feature

**Comment by AyushmanSaxenaLepton** [comment]
has anyone found the answer to solve  the problem of avoiding certain polygon área ??

**Comment by nilsnolde** [comment]
you'll need to look at other routing engines, for sure valhalla can do this and graphhopper IIRC
