### ISSUE TITLE
map-matching has many nulls in the tracepoints

### ISSUE THREAD

**Issue by retorquere** [Project-OSRM/osrm-backend#5230]
I have the map for the netherlands loaded; when I fire off [this](http://localhost:5000/match/v1/car/5.626924,51.661011200000004;5.626868,51.6610304;5.626728,51.6610176;5.6266344,51.66104;5.6265404000000006,51.6610304;5.6264612000000005,51.661008;5.6263868,51.660959999999996;5.6262924000000005,51.660911999999996;5.6261764,51.6608736;5.626045599999999,51.6608352;5.6259008,51.660790399999996;5.6257448,51.66074879999999;5.6255632,51.660707200000004;5.6253459999999995,51.6606592;5.625056,51.660534399999996;5.6248168,51.660451200000004;5.6246008000000005,51.6603936;5.624394000000001,51.6603456;5.6241596,51.660300799999995;5.623928,51.6602624;5.6236996,51.6602336;5.623476,51.660208000000004;5.623254,51.660185600000005;5.62303,51.66016;5.6228068,51.6601376;5.6225816,51.660112;5.62235,51.6600832;5.6221144,51.6600576;5.621887999999999,51.660032;5.6216608,51.6600032;5.6214319999999995,51.6599808;5.6212124,51.659955200000006;5.620998,51.659936;5.6207888,51.6599232;5.6205852,51.659907200000006;5.6203908,51.6598848;5.6202012,51.6598592;5.6200116,51.6598336;5.619830400000001,51.659804799999996;5.619658,51.65977279999999;5.6194924,51.6597568;5.6193288,51.659744;5.6191672,51.6597312;5.618998400000001,51.6597184;5.618828,51.6597088;5.6186664,51.659699200000006;5.6185208,51.6596896;5.6184128,51.6597088;5.6183,51.6597472;5.6182032,51.65977279999999;5.6181028,51.659804799999996;5.618024,51.659852799999996;5.617952,51.6598944;5.6178672,51.65992;5.617782,51.6599232;5.6176712,51.6599232;5.6175488,51.6599328;5.617436799999999,51.6599648;5.61733,51.6600096;5.617223200000001,51.6600544;5.6171328,51.660108799999996;5.6170608,51.6601824;5.6170108,51.6602592;5.61698,51.660329600000004;5.616926,51.6603872;5.6168448,51.660432;5.6167416,51.6604864;5.6166436,51.66056;5.616558,51.6606432;5.616468,51.6607296;5.616373599999999,51.6608288;5.6162788,51.660928000000006;5.616184400000001,51.661024;5.6160904,51.661116799999995;5.6159988,51.661206400000005;5.615909200000001,51.661296;5.615819999999999,51.6613888;5.6157356,51.661488;5.61565,51.6615904;5.615564,51.661696;5.615480000000001,51.66180479999999;5.615374,51.6619296;5.615284,51.66205120000001;5.6152008,51.662176;5.615121599999999,51.66229439999999;5.6150459999999995,51.662416;5.6149684,51.6625344;5.6148948,51.6626528;5.6148264,51.662768;5.614754799999999,51.6628832;5.614682,51.662995200000005;5.6146136,51.6631136;5.6145596,51.6632352;5.6145244000000005,51.66336;5.614508,51.6634912;5.614496,51.66361920000001;5.6144864000000005,51.6637472;5.6144808,51.663872;5.6144648,51.6639968;5.614436799999999,51.664128000000005;5.614392400000001,51.664259200000004;5.6143279999999995,51.6643776;5.614240000000001,51.6644896;5.6141347999999995,51.6646016;5.6140328,51.6647072;5.6139316,51.6648128;5.6138288,51.6649152;5.6137312,51.6650208;5.613644,51.6651296;5.613548799999999,51.665244799999996;5.613476,51.6653632;5.613412,51.665488;5.6133512,51.6656096;5.6132964,51.665728;5.613251999999999,51.6658464;5.613221599999999,51.665968;5.6131988,51.6660896;5.6131704000000004,51.6662112;5.6131224,51.666329600000005;5.6130644,51.6664544;5.613011599999999,51.666576;5.6129652000000005,51.6666976;5.6129228,51.666816;5.6128848,51.6669248;5.612849199999999,51.6670304;5.6128127999999995,51.6671232;5.6127744,51.6671968;5.6127412,51.6672576;5.612718,51.667305600000006;5.6127068,51.6673408;5.6127108,51.667372799999995;5.6127268,51.6673952;5.6127668,51.667420799999995;5.612847599999999,51.667446399999996;5.612904400000001,51.6674784;5.6129652000000005,51.66752;5.61302,51.667552;5.613063200000001,51.6675776;5.6130884000000005,51.667580799999996;5.6131176,51.6675744;5.6131384,51.667571200000005;5.6131528,51.667568;5.6131568,51.667568;5.6131660000000005,51.667568;5.613169999999999,51.667568;5.613172799999999,51.667568;5.6131752,51.667568;5.613176,51.667568;5.613176,51.667568;5.613176,51.667568;5.613176,51.667568;5.613176,51.667568;5.6131768,51.667568;5.6131776,51.667568?overview=full&annotations=nodes&tidy=true) query I get [this](https://gist.github.com/retorquere/61fc30555b62ea4ccbfc0b6d4d05b7c2) result. The output has

```
{
         "name" : "{\"name\":\"Mellesingel\",\"lanes\":\"1\",\"maxspeed\":\"50\",\"type\":\"tertiary\"}",
         "matchings_index" : 0,
         "waypoint_index" : 0,
         "alternatives_count" : 0,
         "hint" : "e-gFgP___38EAAAABAAAALkAAAAAAAAAe66aQAAAAAAx7k1DAAAAAAQAAAAEAAAAuQAAAAAAAACsBQAAM9xVAPxIFAMs3FUA00gUAwMADxDRGzQ2",
         "location" : [
            5.626931,
            51.661052
         ]
      },
      null,
      null,
      {
         "location" : [
            5.626602,
            51.661057
         ],
         "hint" : "W1cdgP___38AAAAAAgAAAAYAAAAAAAAAkEF_P5c30z9fyvhAAAAAAAAAAAACAAAABgAAAAAAAACsBQAA6tpVAAFJFAMK21UA8EgUAwMAzw3RGzQ2",
         "alternatives_count" : 0,
         "waypoint_index" : 1,
         "name" : "{\"type\":\"tertiary\",\"maxspeed\":\"50\",\"name\":\"Rotonde Kennedylaan\",\"lanes\":\"1\"}",
         "matchings_index" : 0
      },
```
in the tracepoints where the corresponding locations for the `null`s are  `5.626868,51.6610304` and `5.626728,51.6610176` (I think) but if I plug those into google maps they clearly fall on the same road as the first point.

**Comment by retorquere** [comment]
Sorry for the missing context. I build the .osrm file using these commands,

```
  ./build/osrm-extract netherlands.osm.pbf -p ./profiles/car.lua
  ./build/osrm-contract netherlands.osrm
```

using this patch against `profiles/lib/way_handlers.lua`:

```
--- osrm-backend/profiles/lib/way_handlers.lua  2018-10-11 23:37:34.316784591 +0200
+++ osrm-backend-patches/profiles/lib/way_handlers.lua  2018-10-01 10:56:30.740363082 +0200
@@ -9,6 +9,7 @@
 local get_destination = require("lib/destination").get_destination
 local Tags = require('lib/tags')
 local Measure = require("lib/measure")
+local json = require('lib/json')
 
 WayHandlers = {}
 
@@ -31,20 +32,22 @@
 -- handles name, including ref and pronunciation
 function WayHandlers.names(profile,way,result,data)
   -- parse the remaining tags
-  local name = way:get_value_by_key("name")
-  local pronunciation = way:get_value_by_key("name:pronunciation")
   local ref = way:get_value_by_key("ref")
-  local exits = way:get_value_by_key("junction:ref")
-
-  -- Set the name that will be used for instructions
-  if name then
-    result.name = name
-  end
-
   if ref then
     result.ref = canonicalizeStringList(ref, ";")
   end
 
+  local name = way:get_value_by_key("name") or ref or ""
+  local highway = way:get_value_by_key("highway") or ""
+  local maxspeed = way:get_value_by_key("maxspeed") or json.null
+  local lanes = way:get_value_by_key("lanes") or json.null
+
+  local pronunciation = way:get_value_by_key("name:pronunciation")
+  local exits = way:get_value_by_key("junction:ref")
+
+  -- Set the name that will be used for instructions
+  result.name = json.encode({["type"] = highway, ["maxspeed"] = maxspeed, ["lanes"] = lanes, ["name"] = name})
+
   if pronunciation then
     result.pronunciation = pronunciation
   end
```

but removing tidy seems to have done it!

**Comment by danpat** [comment]
Great - I think this is intended behaviour when you use `tidy=true` - some points are removed from matching deliberately to "clean it up".

I don't think there's anything actionable here, please re-open if you disagree.

**Comment by retorquere** [comment]
Nope, I misread the purpose of `tidy`, I thought `tidy` was required to get the matched coordinates. Everything fine!
