### ISSUE TITLE
throwing an instance of 'osrm::util::exception'

### ISSUE THREAD

**Issue by u02249** [Project-OSRM/osrm-backend#5233]
when I run script:

cd /var/osrm/update
if [ ! -f  asia-latest.osm.pbf ]; then
        wget https://download.geofabrik.de/asia-latest.osm.pbf
fi

if [ ! -f  russia-latest.osm.pbf ]; then
        wget https://download.geofabrik.de/russia-latest.osm.pbf
fi

if [ ! -f  asia-with-russia.osm.pbf ]; then
        osmosis  --read-pbf file="asia-latest.osm.pbf"  --read-pbf file="russia-latest.osm.pbf"  --merge --write-pbf file="asia-with-russia.osm.pbf"
fi

if [ ! -f asia-aparu.osm.pbf ]; then
        osmosis --read-pbf file="asia-with-russia.osm.pbf" --bounding-polygon file="filter.txt" --write-pbf file="asia-aparu.osm.pbf"
fi
if [ ! -f asia-aparu.osm.osrm ]; then
        docker run -t -v /var/osrm/update:/data osrm/osrm-backend osrm-extract -p car.lua /data/asia-aparu.osm.pbf
fi

I get error:

[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 951.644 seconds
[info] Raw input contains 168340080 nodes, 0 ways, and 0 relations, 0 restrictions
terminate called after throwing an instance of 'osrm::util::exception'
  what():  There are no edges remaining after parsing.src/extractor/extractor.cpp:634

Please tell me, Why I get this error?

**Comment by daniel-j-h** [comment]
You are probably filtering out everything from the pbf. Check your bounding box. Check your result pbf.

Also I recommend using https://github.com/osmcode/osmium-tool

https://docs.osmcode.org/osmium/latest/osmium-extract.html

**Comment by danpat** [comment]
Yes, @daniel-j-h is right.  The key message is:

> what(): There are no edges remaining after parsing

and:

> [info] Raw input contains 168340080 nodes, 0 ways, and 0 relations, 0 restrictions

Note that it says `0 ways` - something has gone wrong with your `osmosis` merge operation - none of the OSM ways have been written to the output.
