### ISSUE TITLE
`nearest` service - output explained

### ISSUE THREAD

**Issue by tufixm** [Project-OSRM/osrm-backend#5239]
I am trying to understand the output of the [`nearest`](http://project-osrm.org/docs/v5.15.2/api/?language=Python#nearest-service) service from the OSRM API.

For example, for the following query:
`http://{server}/nearest/v1/driving/-0.34864629999999996,39.4611833?number=3`

The output is:

    {'waypoints': [{'nodes': [0, 253705180],
       'location': [-0.348949, 39.461195],
       'hint': 'RzVcgP___38DAAAAEwAAAAAAAAArAAAAHOevQAIf5kEAAAAAOgwJQgMAAAATAAAAAAAAACsAAADyFAAA66z6_0shWgLvrPr_UyFaAgAALxLCNWkx',
       'name': 'Avinguda de les Balears',
       'distance': 0.953808},
      {'nodes': [0, 253705180],
       'location': [-0.348885, 39.461186],
       'hint': 'RjVcgP___38BAAAATQAAAAAAAAAAAAAAfdlzP45rUUIAAAAAAAAAAAEAAABNAAAAAAAAAAAAAADyFAAAK636_0IhWgLvrPr_UyFaAgAAPwHCNWkx',
       'name': 'Carrer de Vicente Beltrán Grimal',
       'distance': 5.488372},
      {'nodes': [4057399437, 3270269414],
       'location': [-0.348889, 39.461178],
       'hint': 'ZTVcgP___38DAAAAAwAAAOAAAAAAAAAAWsjsPwAAAABCXhtDAAAAAAMAAAADAAAA4AAAAAAAAADyFAAAJ636_zohWgLvrPr_UyFaAgUADwHCNWkx',
       'name': 'Carrer de Vicente Beltrán Grimal',
       'distance': 5.554942}],
     'code': 'Ok'}

My questions are:

1. What does the `nodes` field represent? Namely what are these pairs of nodes supposed to represent with respect to the queried location and the corresponding `location` fields in the response?

2. What is the meaning of a 0-value node inside the `nodes` array?

**Comment by lcoimbra** [comment]
Hello, have you been able to find an answer to these questions?

**Comment by danpat** [comment]
The `nodes` field are the OSM node IDs on either end of the line that the coordinate snapped to.  They're populated in the code here: https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/api/nearest_api.hpp#L41

Looks like our API documentation is missing this, a PR would be welcome if someone has the time.

The `0` value looks like a bug.  The coordinate above has snapped to this way: https://www.openstreetmap.org/way/115600567, which is marked as oneway - the forward/reverse logic in the code above is likely incorrect for oneways.

**Comment by lcoimbra** [comment]
In the documentation, the [example](http://project-osrm.org/docs/v5.22.0/api/#nearest-service) shows a case returning node IDs `0` both in the variable `to_node` and `from_node` (initialized [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/api/nearest_api.hpp#L47)):
`"nodes": [
            2264199819,
            0
         ]`
`"nodes": [
            2045820592,
            0
         ]`
`"nodes": [
            0,
            21487242
         ]`

I also noticed the [comment](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/api/nearest_api.hpp#L74): `// In the case of one way, rely on forward segment only`. If it is indeed a bug, can it be just missing an assignment, so it avoids keeping the default value?

**Comment by SiarheiFedartsou** [comment]
Stale.
