### ISSUE TITLE
distance property documented but missing from waypoints

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#5247]
Our docs mention in several places that `waypoint` objects in responses to pretty much all APIs should contain a `distance` property.

However, only the `nearest` plugin actually does this - other APIs (`table`, `route`, etc) don't include a `distance` property for waypoints.

In many of our sample snippets in the docs, the `distance` property is shown for `waypoint` objects, even though we don't actually emit one.

We should just be consistent here and return it always.  The `nearest` plugin here:

https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/api/nearest_api.hpp#L43-L44

shows how the property can be added - although this could be moved to the BaseAPI and just done for all cases.

Once it's consistently available, we should also update the docs.

**Comment by danpaz** [comment]
Released in 5.21.0
