### ISSUE TITLE
Docker OSRM

### ISSUE THREAD

**Issue by ObregonRafa** [Project-OSRM/osrm-backend#5254]
![image](https://user-images.githubusercontent.com/39303663/47797462-25969280-dd05-11e8-8d0e-93fb33a8fd0b.png)

Hi, According to image, when I execute the command, the process does not finish, it goes until 
![image](https://user-images.githubusercontent.com/39303663/47797598-67bfd400-dd05-11e8-8b3f-1a6992fae019.png). Can someone help me?

**Comment by Dimacru** [comment]
+1

**Comment by Dimacru** [comment]
I solved the problem
Increase RAM limit to docker

**Comment by ObregonRafa** [comment]
Hi, Dimitri ... I was able to solve the problem by creating a new file with the area that I really needed ... I believe the other file was very large ... Thanks a lot for the return ... Regarding RAM where do I change the configuration?
