### ISSUE TITLE
Problem with deadends routing

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5260]
I have a problem with routing in deadends and two-way roads that don't connect to other ways at the end. The problem is that when I set the bearing towards the end of the road the response is go to the end of the road and the turn back instead of turning back immediately. 

I mean it does something like this when I want to get a route to 15th ST N:
https://map.project-osrm.org/?z=18&center=38.888448%2C-77.099937&loc=38.887734%2C-77.099749&loc=38.889020%2C-77.099969&hl=en&alt=0

**Comment by safe-bug** [comment]
I still have this issue with OSRM

**Comment by danpat** [comment]
I mean, this is expected behaviour - if you set a bearing, then it forces the route to head off in the direction you requested.  If that's towards a dead-end, then what else do you expect it to do?

If you *don't* want it to head off toward the dead-end, remove the `bearing` that you supply - that'll allow it to depart in any direction from the start location.

**Comment by safe-bug** [comment]
@danpat Thanks for the reply, I'm using this service for a navigator and it's not possible to detect if the route is going to the end of a deadend street to remove the bearing from the request. Do you have any other solution for it?

**Comment by danpat** [comment]
Well, I mean OSRM has the same problem - it doesn't know that the point is on a dead-end street either, until after the final route is calculated.

Your only option would be to examine the results - if there's a u-turn in the result, repeat the request but remove the bearing.

**Comment by neilRGS** [comment]
-- 
rgs-html-sig.html

cid:image003.png@01D239BC.F4B170B0

	

*Neil McLeish**|*Platforms Engineer, Certified GDPR Practitioner

*Email:*neil.mcleish@rgsit.com 
<mailto:neil.mcleish@rgsit.com>*|**Tel:*0845 8550 550 *|**Web:*www.rgsit.com

<http://www.rgsit.com/>

	

Image result for microsoft partner logo Image result for gdpr 
practitioner logo
