### ISSUE TITLE
Profile with sidewalks handling

### ISSUE THREAD

**Issue by YaroShkvorets** [Project-OSRM/osrm-backend#5264]
Has anyone seen or tried to implement a walking profile with proper sidewalk handling? I mean when roads are tagged with `sidewalk=both/left/right/no`
So walking is not allowed/discouraged on a side of a road without sidewalk for example.

**Comment by PinkDuck** [comment]
This is particularly needed in the foot.lua profile, especially for where there are sidewalks along trunk roads, otherwise OSRM completely avoids them, as well as legally walkable highway=trunk ways as in the UK.
