### ISSUE TITLE
Disk and Memory Requirements

### ISSUE THREAD

**Issue by raquelgdes** [Project-OSRM/osrm-backend#5265]
Hi! I just want to use OSRM for routes in a country (Portugal), do I need the same requirements described here: https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements, or can I work with 4/16 GB of RAM?

**Comment by jcoupey** [comment]
@raquelgdes 16 GB is OK to run on a France extract so it should be fine for Portugal too. Probably less would also do, given the OSM extract is much smaller. Your best bet is to try.

**Comment by buildscientist** [comment]
Any estimate on what it would take to run N. America? Thanks

**Comment by RamYadlapalli** [comment]
> Any estimate on what it would take to run N. America? Thanks

I processed entire North America (https://download.geofabrik.de/north-america.html) with 64 GB RAM and 4 cores. I tried with 32 GB first and end up getting not enough RAM error while running OSRM-contract

**Comment by mkallaoun** [comment]
I am having trouble finding a linux server hosting solution with this much ram thats not astronomically priced per year. You guys have any advice on a hosting solution?

**Comment by danpat** [comment]
@mkallaoun There is no magic solution here - it's expensive to use this software on a large scale.

One suggestion: it takes significantly more RAM to *process* the data than it does to *host* it.  As long as you keep the operating systems/machine architectures the same, you can rent a huge box for a short period to generate the routing files, then move them to a smaller box to actually perform route calculations on.

If query performance isn't super important to you, you can also look at the `--mmap` option of `osrm-routed` - this will "memory map" the datafiles and read parts of them off-disk on-demand.  This slows down queries, but may be OK for your use-case.  Typically, if you've got some hot spots where lots of routes are calculated, the filesystem cache will eventually have most of the important parts of the files in memory and queries can be reasonably fast.

**Comment by erlangp** [comment]
to much RAM sir.. i even can try in my laptop :(

**Comment by danpat** [comment]
@erlangp If you just want to *try* the software out, you can use a small country map extract from OSM, like Moldova.  These only require a few 10s of MB of RAM.

**Comment by systemed** [comment]
@mkallaoun Hetzner or OVH

**Comment by jfpalngipang** [comment]
How did the osrm for Portugal on 16GB RAM work for you, @raquelgdes?

**Comment by kaushikray1** [comment]
> Any estimate on what it would take to run N. America? Thanks

I did this with docker and it looks about 74Gb ram to render and then about 36 to run the car profile.

**Comment by kaplgarg1** [comment]
any idea about how much time it will take for INDIA ANd resources required for that?

**Comment by kaushikray1** [comment]
I am not sure as I didn't do it. I have the servers to run them email me at at Ray@siliconbrane.com and may be I can generate the map files for you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by broomfn** [comment]
Does anyone know the specs that the demo site is running on here?....https://map.project-osrm.org/

**Comment by nilsnolde** [comment]
you can get some ballpark numbers from https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements
