### ISSUE TITLE
Guidance on osrm-contract in AWS

### ISSUE THREAD

**Issue by djMax** [Project-OSRM/osrm-backend#5267]
We are trying to bring up an OSRM instance for North America in AWS in a Kubernetes cluster. We ran expansion in a couple of hours (car profile), but contraction has taken 3 days and still going. I'm wondering if we're doing anything dumb, and if it will ever end. Also wondering if it's worth stopping and running on a different instance type or reconfigured somehow (I've heard Ubuntu might be better, but not sure by how  much) Relevant details:

Machine Type: r5.2xlarge 8 vCPUs 64GB ram
The data is on an EFS volume (does that have much impact on perf?)
Release 5.18.0 from Alpine docker images

Top as of now:
```
Mem: 33700736K used, 31452988K free, 204812K shrd, 113892K buff, 10940148K cached
CPU:  77% usr  18% sys   0% nic   4% idle   0% io   0% irq   0% sirq
Load average: 7.62 7.63 7.58 10/371 339
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   18     8 root     R   26877m  39%   6  96% osrm-contract /data/north-america-latest.osrm
```

Logs:
```
[info] Input file: /data/north-america-latest.osrm
[info] Threads: 8
[info] Reading node weights.
[info] Done reading node weights.
[info] Loading edge-expanded graph representation
[info] merged 133428 edges out of 379446524
[info] initializing node priorities... ok.
[info] preprocessing 85597695 (89.5709%) nodes...
[info] .
 10%
.
 20%
.
 30%
.
 40%
.
 50%
.
 60%
.
[renumbered] 70%
.
 80%
.

[info] Converting contracted graph with 472045028 to edge list (9440900560 bytes)
[info] Getting edges of minimized graph .
 10%
.
 20%
.
 30%
.
 40%
.
 50%
.
 60%
.
 70%
.
 80%
.
 90%
.
 100%
[info] initializing node priorities... ok.
[info] preprocessing 9965007 (10.4276%) nodes...
[info] [renumbered].
 10%
.
 20%
.
 30%
.
 40%
.
 50%
.
 60%
.
 70%
.
 80%
.
 90%
.
 100%
[info] Converting contracted graph with 115775402 to edge list (2315508040 bytes)
[info] Getting edges of minimized graph .
 10%
.
 20%
.
 30%
.
 40%
.
 50%
.
 60%
.
 70%
.
 80%
.
 90%
.
 100%
[info] initializing node priorities... ok.
[info] preprocessing 9965007 (10.4276%) nodes...
[info] [renumbered].
 10%
.
 20%
.
 30%
.
 40%
.
 50%
.
 60%
.
 70%
.
 80%
.
 90%
.
 100%
[info] Converting contracted graph with 115543327 to edge list (2310866540 bytes)
[info] Getting edges of minimized graph .
 10%
.
 20%
.
 30%
.
 40%
.
 50%
.
 60%
.
 70%
.
 80%
.
 90%
.
 100%
[info] initializing node priorities... ok.
[info] preprocessing 9965007 (10.4276%) nodes...
[info] [renumbered].
 10%
.
 20%
.
```

**Comment by TimMcCauley** [comment]
@djMax have you tried a smaller pbf? Are you experiencing the same issues then? E.g. https://download.geofabrik.de/north-america/us/new-jersey-latest.osm.pbf

**Comment by djMax** [comment]
I did Massachusetts, and that was pretty quick to expand and maybe 6 hours to contract.

**Comment by djMax** [comment]
It doesn't seem to be performing that much better.

**Comment by daniel-j-h** [comment]
Give the ML pipeline a try and see how it goes in comparison. Check the readme, you will need to partition and customize instead of contract.

**Comment by TimMcCauley** [comment]
@djMax please also read this thread, might help debugging - https://github.com/Project-OSRM/osrm-backend/issues/5231

**Comment by djMax** [comment]
Mine doesn't stop, but I had read that thread. I just turned on syslog. So currently I have:

* 8 vCPU, 64GB running default car profile on north america, 6 days now, seemingly looping on "preprocessing 9965007 (10.4276%)
* 8 vCPU, 64GB running car profile with NO exclusions on north america, 2 days now, first pass at 95%
* 96 vCPU, 64GB running default car profile on NA, 15 hours now, 10% on first pass. What's strange about this one is that the "CPU" is exactly 50% loaded, implying that it's only using 48 cores. Possible?

I'm about to go down to Microcenter and just build a beast and see what that does.

**Comment by djMax** [comment]
I've killed the 96 vCPU and repurposed it to run the MLD. Any guidance on how long one would expect the stages of that to take?

**Comment by djMax** [comment]
It's been about 30 minutes so far, logs say:

```
[info] Computing recursive bisection
[info] Loaded compressed node based graph: 99862910 edges, 207829768 nodes
[info]  running partition: 128 1.2 0.25 10 1000 # max_cell_size balance boundary cuts small_component_size
[info] Found 169384624 SCC (9 large, 169384615 small)
[info] SCC run took: 10.6924s
```

**Comment by TimMcCauley** [comment]
Can you try an older version @djMax https://hub.docker.com/r/osrm/osrm-backend/tags/ ?

**Comment by ImreSamu** [comment]
@djMax 
>Release 5.18.0 from Alpine docker images

Check the Debian based docker images.  
* https://github.com/Project-OSRM/osrm-backend/pull/5262  ( `latest`) 

Alpine is very slow: https://github.com/Project-OSRM/osrm-backend/issues/4692#issuecomment-430986950

**Comment by djMax** [comment]
Debian is definitely a big piece of the solution, though I'm still confused why customize has been running for hours on alpine+96vCPU and still isn't done. Does that process ONLY need the osrm file? If so maybe I'll kill it and bring it up under debian.

**Comment by djMax** [comment]
Thanks all for the help. Debian was the key. I ran both MLD and CH in hours on the 96 vCPU box with Debian, but days and days in Alpine and it did not seem close to done, judging by the logs.
