### ISSUE TITLE
Compiliing Error with STXXL

### ISSUE THREAD

**Issue by nandutee123** [Project-OSRM/osrm-backend#5268]
51%] Linking CXX executable osrm-contract
libosrm_contract.a(contractor.cpp.o):contractor.cpp:function void stxxl::block_manager::delete_block<2097152u>(stxxl::BID<2097152u> const&): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
libosrm_contract.a(contractor.cpp.o):contractor.cpp:function void osrm::contractor::GraphContractor::GetEdges<osrm::contractor::QueryEdge>(osrm::util::DeallocatingVector<osrm::contractor::QueryEdge, (8388608)/(sizeof (osrm::contractor::QueryEdge))>&): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function stxxl::singleton<stxxl::config, true>::create_instance(): error: undefined reference to 'stxxl::config::init(char const*)'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function stxxl::singleton<stxxl::config, true>::create_instance(): error: undefined reference to 'stxxl::config::init(char const*)'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::dump() const'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)' 51%] Linking CXX executable osrm-contract
libosrm_contract.a(contractor.cpp.o):contractor.cpp:function void stxxl::block_manager::delete_block<2097152u>(stxxl::BID<2097152u> const&): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
libosrm_contract.a(contractor.cpp.o):contractor.cpp:function void osrm::contractor::GraphContractor::GetEdges<osrm::contractor::QueryEdge>(osrm::util::DeallocatingVector<osrm::contractor::QueryEdge, (8388608)/(sizeof (osrm::contractor::QueryEdge))>&): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function stxxl::singleton<stxxl::config, true>::create_instance(): error: undefined reference to 'stxxl::config::init(char const*)'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function stxxl::singleton<stxxl::config, true>::create_instance(): error: undefined reference to 'stxxl::config::init(char const*)'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::dump() const'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
libosrm_contract.a(graph_contractor.cpp.o):graph_contractor.cpp:function void stxxl::DiskAllocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*): error: undefined reference to 'stxxl::DiskAllocator::add_free_region(long long, long long)'
collect2: error: ld returned 1 exit status
CMakeFiles/osrm-contract.dir/build.make:108: recipe for target 'osrm-contract' failed
make[2]: *** [osrm-contract] Error 1
CMakeFiles/Makefile2:396: recipe for target 'CMakeFiles/osrm-contract.dir/all' failed
make[1]: *** [CMakeFiles/osrm-contract.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
collect2: error: ld returned 1 exit status
CMakeFiles/osrm-contract.dir/build.make:108: recipe for target 'osrm-contract' failed
make[2]: *** [osrm-contract] Error 1
CMakeFiles/Makefile2:396: recipe for target 'CMakeFiles/osrm-contract.dir/all' failed
make[1]: *** [CMakeFiles/osrm-contract.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Ubuntu 16.04

**Comment by daniel-j-h** [comment]
Please provide
- compiler, ocmpiler version
- stdlib
- stxxl version and where you got it from

**Comment by frodrigo** [comment]
STXXL support is now removed.
