### ISSUE TITLE
Failure while connecting to the OSRM server

### ISSUE THREAD

**Issue by dilipwk** [Project-OSRM/osrm-backend#5271]
Followed the instructions to install vroom application. When I try to run vroom express and make an API call I got error : {"code":1,"error":"Failure while connecting to the OSRM server."}

I have installed OSRM for mac https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM

OSRM Build also completed.

**Comment by daniel-j-h** [comment]
This looks like a vroom issue / user error. Not actionable on our side.
