### ISSUE TITLE
how to compute shortest path with custom cost and elevation data for electric vehicles

### ISSUE THREAD

**Issue by gstecca** [Project-OSRM/osrm-backend#5273]
Dear all,
 I am looking help in order to compute shortest path with a custom arc cost function. In particular, I would like to add to the arc distance some other information which allow me to compute shortest path for electric vehicles. 

These are the steps I don't know how to achieve.

-- Given (supposed) that I can retrieve elevation data from open-elevation initiative, how to enrich the ORSM graph? In which step and how I can provide this information to the standard OSM data downloaded by geofabric?
-- After that, in which function of orsm-bakend can I work on in order to provide my specific arc cost function to the shortest path algorithm? I would like to use the elevation data, the distance and some other information in order to modify the arc cost (e.g. the estimated acceleration).

Do you have any guided step to achieve this?

Thank you very much for the help.

**Comment by danpat** [comment]
I'll add to this https://github.com/Project-OSRM/osrm-backend/wiki/Integrating-third-party-raster-data which can be used to integrate elevation information.

Nothing specifically actionable on this ticket, so closing.
