### ISSUE TITLE
Routing : Different results on local engine (NoRoute) than from demo server

### ISSUE THREAD

**Issue by dev-indb** [Project-OSRM/osrm-backend#5282]
Similar to #3410

**Version of OSRM: 5.16**
**Data extract used on local machine:**

- Link: http://download.geofabrik.de/europe/france-latest.osm.pbf
- Download date: 2018.10.01

**Command-lines used to prepare the data :** 
```
osrm-extract -p car.lua france-latest.osm.pbf
osrm-partition france-latest.osm
osrm-customize france-latest.osm
osrm-routed --algorithm MLD france-latest.osm
```
**Local server query :**
http://localhost:5000/route/v1/car/5.225146,46.193715;1.466786,43.598279
```
{
    "code": "NoRoute",
    "message": "No route found between points"
}
```

**Demo server query :**
http://router.project-osrm.org/route/v1/car/5.225146,46.193715;1.466786,43.598279
```
{
    "routes": [
        {
            "geometry": "ce}xGip{^pfYcgS`nTroDdzOpmVdvDdl]ynQvot@zcTdkD_mGrfPm_Dbrj@pgLr_y@ucGzzSmaB~lYlsEtkX{aG|~]xlNxmrAcqShVegKpbLdtBrrQxuLnkK|fLns\\`g[hmP|dIhsj@~|Spp[nV~wS`qIzlYdcZjce@a_AhmVlhHfq[wlDfsFvh[tnQju[kbJzs`@dvGlxZu~N`cPxgMbxp@~X~`]u{Gbeu@tsl@rh_Asa^",
            "legs": [
                {
                    "summary": "",
                    "weight": 22504.4,
                    "duration": 22231.7,
                    "steps": [],
                    "distance": 640313.2
                }
            ],
            "weight_name": "routability",
            "weight": 22504.4,
            "duration": 22231.7,
            "distance": 640313.2
        }
    ],
    "waypoints": [
        {
            "hint": "9p3WgomaboNIEQAABgAAAOnLAQAIAAAAeXWOQBP9akA5EexCTHCUQg8AAAAGAAAAqAEAAAgAAAATqAAAz7pPANPbwAK6uk8AM9zAAgMAXxD7AK0o",
            "name": "Rue Saint-Roch",
            "location": [
                5.225167,
                46.193619
            ]
        },
        {
            "hint": "sPNpgP___385AAAAHwMAAAAAAAAcAAAA6QkMQltq2kIAAAAApzcQQzkAAACQAQAAAAAAAA4AAAATqAAAzWEWANBBmQKiYRYAx0GZAgAATwr7AK0o",
            "name": "Rue du Sergent Vigné",
            "location": [
                1.466829,
                43.598288
            ]
        }
    ],
    "code": "Ok"
}
```

**Comment by dev-indb** [comment]
According to [Running OSRM](https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM)

I prepared France data like this :

> osrm-extract france-latest.osm.pbf
> osrm-contract france-latest.osrm

... because I don't need real times updates (only distance calculations) and I chose the CHM algorithm.

Works better now.

**Comment by marinagavr** [comment]
Hi, when I run OSRM with CH algorithm, everything works perfect
1) >osrm-extract.exe canada-latest.osm.pbf -p car.lua (note: takes a while to generate canada-latest.osrm)
2) >osrm-contract.exe canada-latest.osrm
3) >osrm-routed.exe canada-latest.osrm

However, when I specify the MLD one, I get {"code":"NoRoute","message":"No route found between points"}
1)>osrm-extract.exe canada-latest.osm.pbf -p car.lua
2) >osrm-partition.exe canada-latest.osrm
3) >osrm-customize.exe canada-latest.osrm
4) >osrm-routed.exe --algorithm=MLD canada-latest.osrm

What am I doing wrong?

**Comment by danpat** [comment]
@marinagavr What are the points you're using?

There should be no difference between MLD and CH in terms of route selection.

**Comment by marinagavr** [comment]
http://localhost:5000/route/v1/driving/-79.578853,44.027592;-79.408924,43.65222?overview=false

**Comment by marinagavr** [comment]
@danpat : any idea what might be wrong?

**Comment by danpat** [comment]
@marinagavr Nope, it works just fine for me.  Make sure you don't have a different `osrm-routed` server running somewhere that's serving up a different map (like a stale process or something).  `osrm-routed` runs with `SO_REUSEPORT` enabled, so you can have multiple `osrm-routed` processes running, and requests will get distributed amongst them.

**Comment by marinagavr** [comment]
![Screenshot (255)](https://user-images.githubusercontent.com/41552869/55009846-9773bf00-4fb9-11e9-98aa-e38fa2ec72fc.png)
@danpat  I checked, no OSRM processes are running. Attached is the screenshot of what I get. When I run it without the MLD algorithm specified, it works. Thoughts?

**Comment by arrecio** [comment]
got same issue, u solved it?

**Comment by katherine-shiqi** [comment]
same issue, how did you solve it?
