### ISSUE TITLE
execute permissions removed from /opt directory in Dockerfile

### ISSUE THREAD

**Issue by chesty** [Project-OSRM/osrm-backend#5283]
Hi,

Is this intentional?

RUN chmod 0644 -R /opt

**Comment by xydinesh** [comment]
Yes, I thought we don't need execute permission for the /opt directory. Only read and write would be enough. For example,
```
osrm-extract -p /opt/car.lua berlin-latest.osm.pbf
```
only `osrm-extract` need to have execute permission whereas `/opt/car.lua` read in as a parameter. I may have missed other use cases on how we use /opt. I'm ok to add those if we have a need to add execute permission to /opt.

**Comment by chesty** [comment]
OK, it means you can't cd to /opt as a non root user, but I guess that's not really required.
ie directories usually have the execute permission
```
# ls -ld /opt/ /etc /usr /var
drwxr-xr-x 28 root root 70 Dec 13 07:39 /etc
drw-r--r--  4 root root 14 Dec 13 07:37 /opt/
drwxr-xr-x 13 root root 13 Nov 12 00:00 /usr
drwxr-xr-x 11 root root 13 Nov 12 00:00 /var
```

**Comment by xydinesh** [comment]
No problem. Make sense to leave /opt at 755, will fix this one too.
