### ISSUE TITLE
precision of map matching

### ISSUE THREAD

**Issue by kitcatkai** [Project-OSRM/osrm-backend#5285]
I will like to confirm my understanding that the map matching algorithm is only precise up till a certain decimal point? or is the precision of the map matching algorithm dependent on the decimal points of the input coordinates?

**Background**

When I zoom in the map matched point(see below), the map matched point starts to diverge from the road segment, represented by a line. 

![map matched](https://user-images.githubusercontent.com/11278735/49055495-b728ef80-f232-11e8-83c8-88b3258f1754.png)

**Comment by quiqua** [comment]
Seems similar to https://github.com/Project-OSRM/osrm-backend/issues/5122#issuecomment-400361257 ?

**Comment by kitcatkai** [comment]
thanks @quiqua, it is indeed due to inherent precision limit!
