### ISSUE TITLE
Wrong route

### ISSUE THREAD

**Issue by csabakeszegh** [Project-OSRM/osrm-backend#5287]
I found a wrong [route](http://map.project-osrm.org/?z=18&center=47.595805%2C19.053965&loc=47.594906%2C19.053206&loc=47.596219%2C19.054086&hl=en&alt=0):

<img width="256" alt="screen shot 2018-12-01 at 10 58 02" src="https://user-images.githubusercontent.com/4716654/49326820-2b77d180-f558-11e8-87f1-c0ebf364a1d6.png">

instead of going straight from A to B, it makes a detour. I'm new to OSM, and OSRM, so not sure if it's a map problem, or an issue with the routing algorithm. Checking on the map, the Turn Restrictions seem to be correct.

<img width="1088" alt="screen shot 2018-12-01 at 10 48 38" src="https://user-images.githubusercontent.com/4716654/49326778-a7bde500-f557-11e8-9ec3-4ff721e9b006.png">

Thank you in advance.

**Comment by danpat** [comment]
@csabakeszegh Looks like there is a incorrect turn restriction relation in place here:

https://www.openstreetmap.org/relation/2886231

I talked to @bhousel, the author of iD - it looks like there's a bug in the editor that's hiding this relation from the restriction view you posted - https://github.com/openstreetmap/iD/issues/5548.

I'll delete this relation, it seems like bad data to me, perhaps a leftover from previous edits at this intersection.

**Comment by csabakeszegh** [comment]
With latest [Hungary map](http://download.geofabrik.de/europe/hungary-latest.osm.pbf) from Geofabrik, now the route is as expected. I had to regenerate the OSRM data as recommended in #4196). Thanks for the prompt actions!
![screen shot 2018-12-04 at 11 53 35](https://user-images.githubusercontent.com/4716654/49437449-d805bd80-f7bb-11e8-9bba-fd5fc960e874.png)
