### ISSUE TITLE
left turn is not properly reflected in driving instructions

### ISSUE THREAD

**Issue by jose1711** [Project-OSRM/osrm-backend#529]
please take a look at the following example: http://osrm.at/1QT. eventhough there is 90 deg. left turn at the junction, instructions show through traffic all the time. this could be very misleading.

**Comment by MoKob** [comment]
Since 4.9, these kind of turns are discovered better. Currently we report a slight-left turn, since the angle of the road is very slight.
For future releases, we aim at discovering longer turns better.
