### ISSUE TITLE
osrm-routed responds without routes

### ISSUE THREAD

**Issue by thomsson** [Project-OSRM/osrm-backend#5292]
after setup with curent installations instrcutions osrm-routed runs without errors but the http query responds with "ok" but no routing informations at all.

starting with
osm@ubuntu-osm:/var/log$ osrm-routed ~/data/bayern-latest.osrm -l DEBUG -i 10.10.0.222 --memory_file ~/osrm.ram
[info] starting up engines, v5.18.0
[info] Threads: 4
[info] IP address: 10.10.0.222
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.11
[info] Listening on: 10.10.0.222:5000
[info] running and waiting for requests
05-12-2018 09:04:59 2.97032ms 10.10.0.116 - Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 200 /route/v1/driving/48.13402,11.662610;48.31901,11.69266

querieng with
http://10.10.0.222:5000/route/v1/driving/48.13402,11.662610;48.31901,11.69266

http result
{"code":"Ok","waypoints":[{"hint":"JlaXglqXuoQAAAAAQQAAAAAAAAC-LwAAAAAAAGeaM0IAAAAA0OkERgAAAABBAAAAAAAAAL4vAAAVhAGANmmlAp9kMgKEd94CEvWxAAAArwIO3bdJ","location":[44.394806,36.856991],"name":""},{"hint":"JlaXglqXuoQAAAAAQQAAAAAAAAC-LwAAAAAAAGeaM0IAAAAA0OkERgAAAABBAAAAAAAAAL4vAAAVhAGANmmlAp9kMgIiSuECdGqyAAAArwIO3bdJ","location":[44.394806,36.856991],"name":""}],"routes":[{"legs":[{"steps":[],"weight":0,"distance":0,"summary":"","duration":0}],"weight_name":"routability","geometry":"es}_Fqz}mG??","weight":0,"distance":0,"duration":0}]}

i get no error information and there is nothing mentioned in the error log. what went wron?

**Comment by danpat** [comment]
@thomsson Add `steps=true` to your request URL - by default, the route response only returns a summary overview geometry and total trip length.

**Comment by thomsson** [comment]
Yes, the swapped coords where the problem, I didn't realized the differen coords in the response.
Thank you!
