### ISSUE TITLE
missing instructions depending on startpoint

### ISSUE THREAD

**Issue by linuzer** [Project-OSRM/osrm-backend#5293]
I've a strange issue where huge part of the instructions are "disappearing" depending on the exact location of the starting point. Please consider the following link:
[http://map.project-osrm.org/?z=18&center=50.312302%2C7.306002&loc=50.312191%2C7.305372&loc=50.423736%2C7.575664&hl=en&alt=0](http://map.project-osrm.org/?z=18&center=50.312302%2C7.306002&loc=50.312191%2C7.305372&loc=50.423736%2C7.575664&hl=en&alt=0)

All instrucctions are included, just as it should be. But if you move the starting point just a little more into the roundabout (or any position south of it), the output is lacking all the instructions regarding the A48 highway:
[http://map.project-osrm.org/?z=16&center=50.311550%2C7.313043&loc=50.312064%2C7.305543&loc=50.423736%2C7.575664&hl=en&alt=0](http://map.project-osrm.org/?z=16&center=50.311550%2C7.313043&loc=50.312064%2C7.305543&loc=50.423736%2C7.575664&hl=en&alt=0)

Now I'm unsure if it is a problem in the OSM-data (I did look at it, but was unable to find any problem), or a problem in the OSRM-engine itself. Could somebody please help me to clarify the exact source of this issue? And in case it is the OSM-data, how to fix it?
Thanks a lot!

**Comment by danpat** [comment]
@linuzer I tried to reproduce this problem using the links and descriptions above, and I can't see the problem.

Can you double-check and see if this is still happening?  We haven't changed anything significant that should affect anything like this recently, so I'm at a bit of a loss.  If there's another way to demonstrate the problem, please update this ticket.

**Comment by linuzer** [comment]
You are right, now the results are consistently correct in this example... very strange!

I will see, if I find another example, but could take same time...
