### ISSUE TITLE
Using Table to slot a waypoint in a route?

### ISSUE THREAD

**Issue by djMax** [Project-OSRM/osrm-backend#5309]
I have a situation where I get a polyline route between point A and B (let's say it's from Google Maps and takes traffic into account in a way that OSRM can't) and I have a waypoint W that I want to compute the "delta" between a trip from A to B (using Google's route) and a trip from A to W to B. where W is slotted into SOME step in Google's route. Is this what the Table service is for? If so, am I just throwing in A as a start and "everything else" as a destination? Or worse - everything as start and destination?

Or is Table the wrong way to do this? I can't see an easy heuristic that lets me know where to slot W in the route.

Alternatively if there's a source of "high quality" traffic data for OSRM, maybe that's my better option.

**Comment by danpat** [comment]
@djMax I don't really understand what you're trying to do here.  The `table` plugin is for calculating the duration of many routes - from all the sources to all the destinations.

Google's API supports waypoints, can't you just make two queries (A->B and A->W->B) and compare themn?

Mapbox has traffic data which we use with OSRM, but it's not available for sale ATM.  You can use it and OSRM together by proxy by hitting the Mapbox Directions API (we use OSRM to power our stack).  Note: I work for Mapbox.

**Comment by djMax** [comment]
Our use case is we have N candidate points (gas stations, I work at GasBuddy) and we want to figure out which one is the smallest deviation from your route. But because we don't have traffic data, I'm hoping to use Google's route for A->B. It would be cost prohibitive to use it for A->[N]->B (as would Mapbox's API one would imagine). So I was trying to figure out how to "bias" OSRM to use Google's route and stick the waypoint at "the best place."

**Comment by danpat** [comment]
@djMax Ah, I see.  To solve that problem, what I'd do is make a matrix request like:

```
sources=A,gas1,gas2,gas3&destinations=B,gas1,gas2,gas3
```

This will give you all the data you need to loop over all the combinations and find the fastest overall path.  i.e. try A->gas1->B, A->gas2->B, A->gas3->B.

Once you've figured out the fastest sequence, request that route using gasN as a waypoint from your routing provider.

Of course, this assumes that what you want to optimize for is "fastest overall trip".  Minimizing detour from the primary A->B route would be a lot more tricky.

**Comment by danpat** [comment]
Closing here - this optimization problem isn't really what OSRM is designed to solve.
