### ISSUE TITLE
HTTP Persistent Connection in osrm-routed

### ISSUE THREAD

**Issue by tmpsa** [Project-OSRM/osrm-backend#531]
We are running osrm-routed on a local box, and send thousands of requests to it. Then our client runs out of 'Ephermal Ports', probably because a new HTTP/TCP connection is created for each request.

Does osrm-routed check and use the HTTP header 'Connection: keep-alive' (which should control the SO_KEEPALIVE socket option)? Or does it close the connection immediately? Our client (using Java SDK) sends the header in the request, but the response does not appear to have it.

How, exactly, does osrm-routed handle Persistent Connections?

**Comment by mehany** [comment]
Hi, does this issue still persist? @drieks do I still need to apply the work around you suggested? and where?

**Comment by drieks** [comment]
Hi @mehany, sorry but I can't tell you because I'm not working on this for some time...

**Comment by TheMarex** [comment]
The example HTTP server is really not suited very well for production. We mostly keep it around for debugging and make small deployments easier. I would highly recommend to use the node bindings or the C++ API if you really have production requirements.
