### ISSUE TITLE
Multiple destinations results in wrong routing!

### ISSUE THREAD

**Issue by bryanibit** [Project-OSRM/osrm-backend#5319]
This is the [dataset and results](https://drive.google.com/drive/folders/1qS8Z_kCPc-wghHL9m3m8zjXSgCcKTg0P?usp=sharing) I used and got. RoutingX-X-X.kml means routing result using OSRM.  The routing order is presented by number order shown in google earth.
dataset.osm is the dataset for routing. I just choose several points from the 4 points as shown in routing_plan_point.kml and .txt. As you can see, the route(via 10-12) is right but the route(via 10-12-13) is wrong and not the shortest path. The most surprising routing result is the route(via 9-10-12-13), which is a circle that can not be understood.
Is there anyone to help me to explain the situation? Thank you!

**Comment by danpat** [comment]
@bryanibit By default, the `car.lua` profile will continue straight at waypoints.

Try adding `continue_straight=false` to your request and see if that fixes things - with this enabled, the route should head immediately south from 12->13.

For others reading tickets, here's an image of the scenario (black lines are geometry from the supplied `dataset.osm`, ways are mostly unnamed and tagged as `highway=residential`):

<img width="429" alt="screen shot 2018-12-18 at 9 31 04 am" src="https://user-images.githubusercontent.com/1892250/50168012-ae629100-02a7-11e9-8309-7ec0dbfc9eea.png">

**Comment by bryanibit** [comment]
@danpat I adopted what you said and got the right result fundamentally. I still wonder that the different number of nodes and coordinates with command ```overview=full annotations=true geometries=geojson```, which is symmetry for node and coordinate shown in #5256.

**Comment by SiarheiFedartsou** [comment]
Stale.
