### ISSUE TITLE
Segmentation fault on alpine package while using osrm-extract

### ISSUE THREAD

**Issue by salimkayabasi** [Project-OSRM/osrm-backend#5321]
I am trying to use osrm-extract in order to parse my `.osm.pbf` file. Everytime, it is failing while parsing source. It looks like some of dependencies are missing but I couldn't discover which one is missing.

I've also tried to install all dependencies which are listed here 
https://github.com/Project-OSRM/osrm-backend/blob/v5.20.0/docker/Dockerfile

Berlin file is from geofabrik
~52M in size
bc494e3779764b07a471190d05e7ec70

osrm-extract seg fault issue
https://asciinema.org/a/217537
osrm-extract seg fault issue --debug
https://asciinema.org/a/217536

```
# Dockerfile
FROM node:10-alpine
RUN apk add libc6-compat gdb

ENV APP /app/
WORKDIR $APP

RUN npm init -y
RUN npm i osrm@v5.20.0 --debug

COPY data/berlin-latest.osm.pbf $APP/data/berlin-latest.osm.pbf

# cat Dockerfile.testing
# docker build -t osrm-node-alpine:testing -f Dockerfile.testing . && docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -it osrm-node-alpine:testing sh -c "gdb /app/node_modules/osrm/lib/binding/osrm-extract"
# run -p /app/node_modules/osrm/profiles/car.lua /app/data/berlin-latest.osm.pbf

# docker build -t osrm-node-alpine:testing -f Dockerfile.testing . && docker run -it osrm-node-alpine:testing sh -c "/app/node_modules/osrm/lib/binding/osrm-extract -p /app/node_modules/osrm/profiles/car.lua /app/data/berlin-latest.osm.pbf || echo $?"
```

**Comment by danpat** [comment]
@salimkayabasi Can you try two things?

`npm install osrm@5.20.0 --debug` - this will get you a "debug" build of OSRM.

Then, when you run `osrm-extract`, wrap it in `gdb`, like `gdb ./node_modules/osrm/lib/binding/osrm-extract --args ./node_modules/osrm/profiles/car.lua berlin-latest.osm.pbf`

You'll need to install `gdb` in your image to do this.  I'd also suggest doing the `gdb` command in interactive mode - `gdb` will catch the segfault.

Once `gdb` catches the segfault, type `bt full`, and paste the output here - this will tell us where `osrm-extract` crashed.

**Comment by salimkayabasi** [comment]
After switching to `node:10-slim` instead of `node:10-alpine`, it is working as expected.
It looks like some of the linked libraries are not matching

**Comment by danpat** [comment]
@salimkayabasi Can you try installing the `libc6-compat` package in your `node:10-alpine` image?

The `npm install osrm@` packages are build on a Ubuntu box, and link against GNU libc there.  Alpine uses `musl` instead of GNU `libc`, that's where the weird linkage is coming from.  On alpine, you'll need to supply the missing compatibility layer.

**Comment by salimkayabasi** [comment]
hi @danpat 

if u look on my ticket description, `libc6-compat` is already installed as package on top of `node:10-alpine` so it is not enough to run against `alpine` distro

**Comment by danpat** [comment]
Interesting - `ldd` reports:

```
Error loading shared library ld-linux-x86-64.so.2
```

According to https://pkgs.alpinelinux.org/contents?file=ld-linux-x86-64.so.2&path=&name=&branch=&repo=&arch=

that should be in either the `gcompat` or `libc6-compat` apks.  Can you open a shell on your container and see if that file is actually there?
