### ISSUE TITLE
osrm-routed docker crash  

### ISSUE THREAD

**Issue by raj00565** [Project-OSRM/osrm-backend#5326]
Hi guys,
I am running the osrm-routed with docker,the container just stops running, there is no crash logs in docker. 
I installed and build osrm with below reference : https://gist.github.com/akiatoji/42c04598535e823637ba18a54747fca5

I am running osrm-routed GCP with 16 Core processor and 104 GB RAM with 500 SSD .
running the docker with below command :
docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed  --max-viaroute-size=15000 --max-trip-size=3000 --max-table-size=3000 --algorithm  mld /data/north-america-latest.osrm

**Comment by danpat** [comment]
@raj00565 Without more detail, it's a bit hard to guess.

What I would to do to get more information:

  1. Use the `*-debug` tags when you pick the image - these will have more information on the crash available (https://cloud.docker.com/u/osrm/repository/docker/osrm/osrm-backend/tags)
  2. Launch the container into a shell, with:

docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend /bin/bash

  3. Install a debugger, like `apt-get install gdb`
  4. Run `osrm-routed` via the debugger with:

```
gdb --args $(which osrm-routed) --max-viaroute-size=15000 --max-trip-size=3000 --max-table-size=3000 --algorithm mld /data/north-america-latest.osrm
```

Then try to trigger the crash - if it's a real crash, `gdb` will stop execution.  You can type `bt` or `bt full` to get some detailed info about the crash location.

**Comment by knowname** [comment]
i came across the same problem (since it changed to debian base image instead of alpine, 5.20 -> 5.21).
But i get an error message :)

```
 [...]
 Processing triggers for libc-bin (2.27-8) ...           
 osrm-routed: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by osrm-routed)
```
if i logged into the container and did update `libc-bin` and `libc6` it worked.
`apt update && apt upgrade -y` will do it as well.

**Comment by danpat** [comment]
The original message here said the error was:

```
osrm-routed: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by osrm-routed)
```

which is fixed by https://github.com/Project-OSRM/osrm-backend/pull/5338
