### ISSUE TITLE
Map matching splits over penalized turns

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#5327]
With the implementation of https://github.com/Project-OSRM/osrm-backend/pull/5297, it's now possible to map-match over roads that were marked `is_startpoint=false` - this included `highway=service access=private` and ferries.

However, matching can still fail in some scenarios.  When using the `car.lua` profile and `weight_name=routability`, we set large weight penalties on maneuvers into `access=private` roads.

If you attempt to map-match a trace that makes a turn into a private area, it's possible (not always) that the path weight over the turn exceeds the map matching weight threshold https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/routing_algorithms/map_matching.cpp#L220

There are a few possible fixes to this:

  1. Reduce the weight we apply to restricted turns so that it stays below the matching split threshold (this comes at the risk of not avoiding things that shouldn't be used during routing).
  2. Increase the matching split threshold (this comes at a risk of matching when we should *not*).
  2. Make further changes to the routing graph so that edges can have different weights depending on whether we're routing or matching (in this option, there would be no penalty for matching).

**Comment by emiltin** [comment]
would it be possible to provide a list of private areas that you have access to, when routing or map matching? after all, private doesn't mean that nobody has access, but rather that only some have.
