### ISSUE TITLE
health check for Docker

### ISSUE THREAD

**Issue by skk2010** [Project-OSRM/osrm-backend#5328]
Hi. 
Can't find health check for docker.
Something like GET /health will return just 200 code.
Is there something like this?

**Comment by danpat** [comment]
I'd suggest that you make your health check verify a real route, like:

```
HEALTHCHECK curl -f 'http://localhost:5000/route/v1/driving/A,B;C,D' | exit 1
```

Where `A,B;C,D` are coordinates within your dataset where you expect a route.

**Comment by skk2010** [comment]
Hi. Thanks it's ok for health check in docker file but the problem is that
some services, for example  aws elb, will not apply some letters (comma) in
health check. And aws balancer is integrated with ECS and health check is
required as far as I know.
 Is it possible to have simple health check?

чт, 3 янв. 2019 г., 0:07 Daniel Patterson notifications@github.com:

**Comment by danpat** [comment]
`osrm-routed` will url-decode percent-encoded chars before parsing the URL - try configuring AWS ALB with 

```
aws elb configure-health-check --load-balancer-name my-load-balancer --health-check Target=HTTP:5000/route/v1/driving/A%2CB%3BC%2CD
```

**Comment by skk2010** [comment]
Thanks for idea. Definitely will check and come back with the result.
Anyway could you recommend which API is less cpu usage?

чт, 3 янв. 2019 г., 20:13 Daniel Patterson notifications@github.com:

**Comment by danpat** [comment]
@skk2010 The `/nearest` API probably does the least work, but if you want to use `/route`, just use two coordinates that are quite close together and the amount of work will be minimal.

**Comment by skk2010** [comment]
Thanks @danpat. I've configured `/route` with encoded parameters. It works.
