### ISSUE TITLE
Example file for traffic layer with postgis

### ISSUE THREAD

**Issue by vgvaibhav1996** [Project-OSRM/osrm-backend#5329]
I have gps data with every 5 second time interval. I am trying to add traffic layer to my engine with this data by calculating distance and time duration. I have seen that we can provide CSV file in particular format to osrm and it will update accordingly. But in that format, 
`from_osm_id, to_osm_id, edge_speed_in_km_h (,edge_rate?)`

what are these osm_id , and how do i calculate these from my latitude and longitudes. 

> 

28.317792 | 76.89305 | 2018-09-25 17:48:50
-- | -- | --
28.31718 | 76.892333 | 2018-09-25 17:48:47
28.316604 | 76.891643 | 2018-09-25 17:48:46
28.316058 | 76.890962 | 2018-09-25 17:48:18

My data looks something like this. So i am getting distance between two pairs and duration between them to get the traffic layer.
Please suggest if someone has already done it.

**Comment by danpat** [comment]
@vgvaibhav1996 There are no built-in tools to generate this data.

If you have consecutive GPS coordinates collected at regular intervals, you could use the `/match` plugin along with `annotations=nodes` to generate the sequence of nodes that a GPS trace traverses.  You would then need to figure out the distance traversed between coordinates and the speed from that, then decide what statistic to use to assign a speed to each pair of nodes.  You could then generate the required CSV file from that.

There are no plans currently to provide tooling to do this.
