### ISSUE TITLE
What are the benefits of node-osrm over osrm-routed in production?

### ISSUE THREAD

**Issue by RajibChanda** [Project-OSRM/osrm-backend#5331]

**Comment by danpat** [comment]
Some work has been done to replace `osrm-routed` C++ with a NodeJS/ExpressJS equivalent, but neither has been merged yet.  It's on my "I want to get this finished one day" list:

https://github.com/Project-OSRM/osrm-backend/issues/3832
https://github.com/Project-OSRM/osrm-backend/pull/4604

**Comment by quiqua** [comment]
There is also this example https://github.com/door2door-io/osrm-express-server-demo, but still uses OSRM v5.16

**Comment by danpat** [comment]
Nothing actionable here - #3832 and #4604 track the NodeJS `osrm-routed` implementation.
