### ISSUE TITLE
map matching gives the same result for different profiles

### ISSUE THREAD

**Issue by int001024** [Project-OSRM/osrm-backend#5334]
Hi,

I tried to match points to 'car' 'bike' and 'foot' ways. But the results are the same.

Example requests:
http://router.project-osrm.org/match/v1/foot/13.388812,52.517023;13.388752,52.517194?
http://router.project-osrm.org/match/v1/car/13.388812,52.517023;13.388752,52.517194?
http://router.project-osrm.org/match/v1/bike/13.388812,52.517023;13.388752,52.517194?

**Comment by jcoupey** [comment]
Same as #4868.

**Comment by danpat** [comment]
I'd forgotten about this.  I've finally updated the OSRM demoserver to:

  1. Returns valid results for `/<plugin>/v1/driving/` and `/<plugin>/v1/car/` - both are on the `car.lua` profile
  2. Returns HTTP 404 for all other URLs
