### ISSUE TITLE
route works but table doesn't work for v5.15.2

### ISSUE THREAD

**Issue by chenerg** [Project-OSRM/osrm-backend#5335]
the latest api is forv5.15.2 so I download v5.15.2， however when I change route to table，it doesn't work

**Comment by danpat** [comment]
@chenerg I'm sorry, you'll need to be more specific about what's not working.  Can you include the exact request you're trying, the error you're getting, and a description of what you expect?

Note that the latest release is 5.21.0, but the online docs are a bit out of date.

**Comment by chenerg** [comment]
Thanks. I know the problem. The steps parameter is not supported for table api.
