### ISSUE TITLE
Have Osrm supported restriction on vehicle and time of turn Restriction ?

### ISSUE THREAD

**Issue by NguyenSen** [Project-OSRM/osrm-backend#5339]
if OSRM supported then how to config time because i country in time zone +7

**Comment by danpat** [comment]
You can configure your OSRM dataset to represent conditions at a certain time by doing the following:

  1.  `osrm-extract --parse-conditional-restrictions` - this will build an index of conditional time-based restrictions.
  2. Use `osrm-contract/osrm-customize` with the `--parse-conditionals-from-now NNN` where NNN is the timestamp you want represented in your routing data.  You will also need `--time-zone-file X` and supply a GeoJSON file with polygons describing your timezones.  We don't supply one, you can use something like https://github.com/evansiroky/timezone-boundary-builder to build one.

Note that this encodes the time condition in your entire dataset - OSRM does not support supplying a `start_time` or any other API parameter to adjust conditions on-the-fly.  It also does not support varying vehicle type conditions.

**Comment by NguyenSen** [comment]
Thanks you,i 'm try 👍
