### ISSUE TITLE
Map matching and distance

### ISSUE THREAD

**Issue by rgugliel** [Project-OSRM/osrm-backend#5344]
Hello,
I'm facing a result from a match query that I don't fully understand.

The context is the following:
I have a GPS trace in Paris of around 1700, that comes from the following journey:
https://www.google.com/maps/dir/48.870856,+2.342875/48.857898,2.307158/@48.8664598,2.3186734,15.25z/data=!4m17!4m16!1m13!2m2!1d2.342875!2d48.870856!3m4!1m2!1d2.3104721!2d48.862324!3s0x47e66fd9f701a3eb:0x24b6aa8a6b668b71!3m4!1m2!1d2.307392!2d48.8560377!3s0x47e67027704214cb:0xd63a6bcef681d1a6!1m0!3e2

I query osrm-backend 5.20, to get the match and compute the total distance of the route (I sum the distances over all the `matchings`)

If I call the match service with all the points, I get a distance of around 1000m.
On the other hand, if I filter the points to ensure that they are not too close (as advised in the article https://infolab.usc.edu/csci587/Fall2016/papers/Hidden%20Markov%20Map%20Matching%20Through%20Noise%20and%20Sparseness.pdf ), I get a distance of 4364m, which is close to what Google gives.

What I don't understand is the following:

- Why is the difference so big?
- Why is the distance with more points smaller (I would have expected the opposite)?

Note: I draw on a map the path returned by OSRM. In both cases, they are very similar so it seems that the path is correct but the distance computation may have an issue.

What did I miss?

Thanks a lot.

**Comment by danpat** [comment]
@rgugliel Can you share the GPS trace you're matching, and the exact API calls you're making to OSRM?

**Comment by rgugliel** [comment]
https://pastebin.com/5syp20iG
Gives a distance of 2255.5

https://pastebin.com/bzGwV4fV
Gives a distance of 4356.6

The trace: https://pastebin.com/FuxgtPuH

**Comment by rgugliel** [comment]
Hello!
Is there some news regarding this issue?

Can I help by trying to find the problematic piece of the trace?
