### ISSUE TITLE
Update wiki docs

### ISSUE THREAD

**Issue by amirmasud** [Project-OSRM/osrm-backend#5348]
As #2977 said previously, It would be great if one of the OSRM devs could spend a few minutes updating the docs, so we newcommers can be get more familiar with the codebase and be able to help to improve it.
From the release of the MLD till now I couldn't find any docs about it (except how to build and run) and I'd appreciate if you update docs and mention the changes made. I'll be thankful if you update the docs including these pages:

-  [Processing Flow](https://github.com/Project-OSRM/osrm-backend/wiki/Processing-Flow) 
-  [Traffic](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) (#5340)
-  [Graph-representation](https://github.com/Project-OSRM/osrm-backend/wiki/Graph-representation)

Thank you very much in advance

**Comment by wangyoucao577** [comment]
We also met similar issue when we read OSRM source codes. So we wrote some additional docs by ourselves when we reading the codes. Hope these docs can help you too: 

- [Understanding OSRM Graph Representation](https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/understanding_osrm_graph_representation.md)
- [OSRM Traffic Update](https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/osrm_traffic_update.md)

More docs please refer to our main page: 
- [OSRM In Telenav](https://github.com/Telenav/open-source-spec/blob/master/osrm/README.md)

**Comment by mmesbah** [comment]
I think this is an indispensable task for OSRM. Please consider to do it ASAP.
