### ISSUE TITLE
How can I set default radius for a request in match service

### ISSUE THREAD

**Issue by giser-yugang** [Project-OSRM/osrm-backend#5349]
I can set radius like `http://127.0.0.1:5000/match/v1/bike/104.060851,30.656241;104.060443,30.653564;104.05951,30.653629;104.059971,30.652789?geometries=geojson&radiuses=15;15;15;15` in match service.

But I wonder if I can set a default radius instead of passing in duplicate numbers based on points number  for a request. This means that radius is the same in one request, but different in different requests.

Thank you in advance.

**Comment by danpaz** [comment]
@giser-yugang I like this idea. Especially for requests with hundreds of coordinates, passing the same radius for every coordinate makes the url unnecessarily long. 

The question in my mind is what the API for setting a default radius should look like, have you thought about it? Maybe something like `radius=all:15` would work to set the same value for all coordinates?
