### ISSUE TITLE
How to derive travel time given list of OSM nodes?

### ISSUE THREAD

**Issue by zyrgit** [Project-OSRM/osrm-backend#5351]
I have a question about deriving travel time given a list of OSM nodes like [5371582342, 2458643672, 2458643670, 5377378282]. Note that this sequence of nodes is not necessarily a routing results of OSRM, otherwise the duration could be obtained from the json result. Do I need to query duration of every pair of nodes and sum the duration up? Thanks for the answer.

**Comment by danpat** [comment]
@zyrgit OSRM has no index from OSM node to coordinate.  Your best option would be to get the coordinates of those nodes, then do a `/route` query, using the coordinates as waypoints.

**Comment by zyrgit** [comment]
Thank you for the reply. I can easily get the Lat Lng of the OSM nodes, but when doing route query with waypoints, like "/route/v1/driving/-88.22219,40.114936;-88.2193765,40.1164187;-88.2527876,40.1347753;-88.2579482,40.1446107" if the coordinates are exactly at the intersections, it will give detour routes, I think OSRM didn't get the correct edges the coordinates are on. Even if I specify radius to "blur" waypoints, like pending "?radiuses=20;20;20;20" to the query, it still gives not the fastest route. Do you know how to solve this? Thank you.

**Comment by danpat** [comment]
Try using `/match` instead

**Comment by zyrgit** [comment]
Got it, thank you!
