### ISSUE TITLE
Override profile to drive both directions on a one-way road?

### ISSUE THREAD

**Issue by RobertSellers** [Project-OSRM/osrm-backend#5363]
https://github.com/Project-OSRM/osrm-backend/blob/9ba60d0d5c823cf5abe7b0f6452339d3c3485d53/profiles/car.lua#L34

Is this what the following accomplishes?  Or is there another known method?

```
oneway_handling  = false,
```

**Comment by danpat** [comment]
@RobertSellers yes.  Ultimately, that variable controls this:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua#L543

You can set it to `true`, `false, `specific`, or `conditional`.  `specific` is used by the walk profile, because you can walk against a lot of oneways, unless it's marked specifically as oneway for foot traffic.

**Comment by RobertSellers** [comment]
Ok. Excellent.  Testing it out now.  Thank you very much.  

Also, related: there isn't a method to convert two-way to one-way at run-time is there?  I assume not, but thought I'd ask.

**Comment by danpat** [comment]
@RobertSellers There currently is not.  The acceleration structures that OSRM builds to speed up queries essentially bake-in the travel directions, and changing that requires re-creating the acceleration structures.

I've been toying with some ways to make some properties run-time adjustable over in https://github.com/Project-OSRM/osrm-backend/pull/5332

For cases like map-matching (where people might have a GPS trace that breaks the road rules, but should still snap to the actual path followed), I think it would be best if it was like you suggest - all roads can be two-way for some purposes (map matching), but one-way for others (route finding).

Not an easy problem to solve and keep things fast.

**Comment by RobertSellers** [comment]
OK - that was my overall impression as well but it's good to get confirmation. The idea might be best to provide multiple "baked in" options and manage things by swapping around profile states.
