### ISSUE TITLE
Route not generated between two valid locations

### ISSUE THREAD

**Issue by pgdhuri** [Project-OSRM/osrm-backend#5368]
I have two locations from Oman as follows
A. 23.0792175,57.6732554
B. 23.4996593,58.1991536

The locations are valid and the roads are also present in these locations but still the system can not generate a shortest route between these locations. I get the following message.
{"message":"Impossible route between points","code":"NoRoute"}.
The same route is available by Google map or grasshopper api.

Please find following screen shots explaining the same situation.

![grasshopper](https://user-images.githubusercontent.com/31301963/53014173-26dcfe00-3461-11e9-8ed1-e577f1d4be91.png)
![osrm](https://user-images.githubusercontent.com/31301963/53014175-26dcfe00-3461-11e9-9fda-5675624ca23c.png)

**Comment by danpat** [comment]
@pgdhuri It looks like there are `barrier=checkpoint` nodes blocking access:

https://www.openstreetmap.org/node/532471096

and there does not appear to be any other road to access Jebel Akhdar.

Do you know if this checkpoint is generally passable?  We may need to add `barrier=checkpoint` to the [barrier whitelist](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L54)

**Comment by pgdhuri** [comment]
Yes these check points are passable only by 4X4 all wheel drive vehicles and heavy vehicles as well. Normal cars which are not 4X4 are not allowed to go.

**Comment by danpat** [comment]
In that case, I'm inclined to say OSRM is correct here - there is no route for a `Car` (which is what the routing is designed for).

The OSM tagging could probably be improved in this area, adding something like `access=no` and `4wd_only=yes` which would make it clearer as to why.
