### ISSUE TITLE
Number of tracepoints does not match number of input coordinates

### ISSUE THREAD

**Issue by jjetrifork** [Project-OSRM/osrm-backend#5372]
I am having trouble understanding the output of the match service.

Every now and then I come across a request where the number of tracepoints is larger than the number of input coordinates even though there is only one match.

Given a prepared and running local server (version 5.20.0):

<pre>osrm-routed --max-matching-size 2147483647 --algorithm mld /data/denmark-latest.osrm</pre>

Consider the following request with `413` input coordinates:
<details>
  <summary>Click for full request<pre>http://localhost:5000/match/v1/driving/...?timestamps=...&radiuses=...&annotations=nodes&generate_hints=false&overview=false</pre></summary>
Full request:
<pre>http://localhost:5000/match/v1/driving/8.44361922690158,55.580081767877;8.44370839656175,55.580014694522;8.4438214270606,55.580027598432;8.44398329213046,55.579992945556;8.44405580347626,55.5798817532001;8.44420145421732,55.5798359732402;8.44435502249459,55.5797863132908;8.44448939365328,55.5797354018893;8.44460654037465,55.579667587581;8.44475549179609,55.5795478635549;8.44487787618326,55.5793691796929;8.44495946466814,55.5791790834396;8.44500802699112,55.5789896718154;8.44506293443578,55.578775511791;8.44512409435784,55.5785369647146;8.44518343885807,55.5783147743269;8.44528553189755,55.5780925252941;8.44541626820511,55.5778945698555;8.44559330157644,55.5776886383478;8.44579098254223,55.5775017935739;8.44601786835067,55.5773221316699;8.44625608298704,55.5771503719556;8.44648621802554,55.5769844378675;8.44673729926193,55.5768034009585;8.44696622110286,55.5766383416213;8.44721409068458,55.5764596204093;8.44745123355517,55.5762886334694;8.44767801753244,55.5761251155944;8.44791260645295,55.5759559701271;8.44814158919856,55.5757908668759;8.44839452087153,55.5756084957481;8.44864945209722,55.5754241273013;8.44890192056704,55.5752418533396;8.44915715025189,55.5750575858711;8.44940593137156,55.5748784995411;8.44967996028359,55.5746820427537;8.44994289385936,55.574493540434;8.45018802151733,55.5743179145364;8.45042774507194,55.5741467944592;8.45066745297438,55.5739756855548;8.45089377755983,55.5738141299638;8.45112726937691,55.5736475217327;8.45135336948308,55.5734868404672;8.45161112100333,55.5733036656728;8.45184754341852,55.5731356487111;8.45207089348746,55.5729769217988;8.452298270647,55.5728153329771;8.45253417854918,55.5726476816614;8.45278787764098,55.5724673867831;8.45302479458916,55.5722990183745;8.45324452421314,55.5721428643831;8.45348720606892,55.5719692501835;8.45373146512392,55.5717944438287;8.45398416470967,55.5716121263572;8.4542268642725,55.5714366256887;8.45446510027639,55.5712632886393;8.45469460033671,55.5710960644633;8.45494454877196,55.5709139406717;8.45518680812995,55.5707374194914;8.45542556170664,55.5705625305944;8.45566515017365,55.5703828521601;8.45590210543115,55.5702045807529;8.45612661287464,55.5700337174926;8.45635355575857,55.56986100072;8.4565469486551,55.5697105974427;8.4567713614945,55.5695322264977;8.456964831341,55.5693734509045;8.45714026590904,55.56920168472;8.45726096521186,55.5690386595604;8.45736959434691,55.5688715515099;8.45747173018512,55.5686912420263;8.45757342538909,55.5684954076496;8.45766754788282,55.568287242113;8.45773840656233,55.5681002734369;8.45780683816771,55.5679102412745;8.45787244830884,55.567714055713;8.45793104219252,55.567513492931;8.45796983713618,55.5673193401917;8.45800578515364,55.5671318393045;8.45803692091378,55.5669471880091;8.45806802144891,55.5667610506769;8.45810135835618,55.5665629065563;8.45825982092276,55.5663929419418;8.45836347811765,55.5662031255263;8.45851360636186,55.5659973059745;8.45870895135597,55.5657998552772;8.45899439993351,55.5656671781229;8.45929012817761,55.5655471280694;8.45960661114798,55.56542310597;8.4598784363828,55.565317167316;8.46019959468655,55.5651920020478;8.46050703005213,55.5650721850306;8.46079640139602,55.5649594081183;8.46110840437666,55.5648378109611;8.46140984885067,55.5647203287786;8.46173264151965,55.564594526548;8.46205982849997,55.5644670117192;8.46235323175253,55.564352663448;8.46269334211433,55.5642201119799;8.4629844408232,55.5641064313989;8.46326171786093,55.5639981392404;8.46356138745472,55.5638811015391;8.46376506837558,55.5638015527718;8.46416880974342,55.563641822006;8.46444952854307,55.563530753965;8.46474628375551,55.5634133410232;8.46507114831225,55.5632848064542;8.46532513822672,55.5631843138536;8.4655907774857,55.5630792121214;8.46585858402286,55.5629732528929;8.46615118652928,55.5628574829935;8.46644175496697,55.5627425178854;8.46668799239064,55.5626450926032;8.466936705639,55.5625466877465;8.46719467104317,55.56244462222;8.46744145996099,55.5623469787359;8.4676528754467,55.5622633309579;8.46788050705364,55.5621977445636;8.46811717971807,55.5621528875341;8.46824174695831,55.5621355783859;8.46864349966548,55.5620949181518;8.46895218410754,55.5620663563642;8.46929680668249,55.5620344693126;8.46962412487672,55.5620044072543;8.46997787873531,55.5619731678039;8.47030453929233,55.5619459850298;8.47052234385091,55.5619280005014;8.47079208097019,55.5619056849924;8.47108812998118,55.5618811926853;8.47142076399578,55.5618520123777;8.47179349531039,55.5618190590145;8.4721168743542,55.5617904689103;8.47244777122218,55.5617612141516;8.47277222125768,55.5617325293606;8.4731068070656,55.5617029484608;8.47344395384511,55.5616731411442;8.47379485979817,55.5616421173722;8.47407044258356,55.5616177529593;8.47449044069722,55.5615810384334;8.4748902883549,55.5615454196379;8.475133557145,55.5615237431053;8.475639974988,55.5614788294332;8.47600389275062,55.5614435671574;8.47637136167049,55.5613921255892;8.47673694258169,55.5613288442034;8.4771130219901,55.5612588970148;8.47744925758273,55.5611963603965;8.47778744974513,55.5611318437647;8.47808126731918,55.5610753887059;8.47841578983786,55.5610116176732;8.47871003443199,55.5609555251342;8.47898479227218,55.560903147401;8.47926498499809,55.5608497336027;8.47952944353983,55.560799319249;8.47976841211844,55.5607537641069;8.47998806976874,55.5607118902524;8.48010353772543,55.5606898783243;8.48028099758159,55.5606604950193;8.48037510681099,55.5606308975203;8.48048584978826,55.5605778397441;8.48052668483268,55.5605534655146;8.48055154104483,55.5605352041746;8.48071574144915,55.5603865156115;8.48071638796876,55.560387783317;8.48067674853001,55.5603100577014;8.48062376399148,55.5602061648109;8.48060944957192,55.5601780968788;8.4805408046679,55.5600434969049;8.48053861518565,55.5600392037348;8.48053861518565,55.5600392037348;8.48053861518565,55.5600392037348;8.48023500271565,55.5595140264006;8.48009962047072,55.5593733839273;8.47995268773148,55.5592230260568;8.47978013770632,55.5590474538948;8.47962319080916,55.5588792550245;8.47946516579667,55.5587020209955;8.4792908046479,55.5585314387439;8.47910406644582,55.5583611385661;8.4789330368303,55.5581918171328;8.47875675683864,55.5580115573136;8.47856670917112,55.5578278520973;8.4783910273945,55.5576544942164;8.47818501689529,55.5574538651477;8.47751641314327,55.557391946966;8.47734037695302,55.5571847051302;8.47715152910538,55.5569623805291;8.4769714076085,55.556750329188;8.47685080695887,55.5566083498601;8.47662080003102,55.5563499993944;8.47644338792836,55.5561507847537;8.47614536653944,55.5558560264949;8.47593993501147,55.5556595714641;8.47573233157777,55.5554579998971;8.47552945631131,55.5552619566523;8.47533973607554,55.5550812958202;8.47514577372873,55.5548774068563;8.47496004549188,55.5546644474617;8.47477271047674,55.5544502039875;8.47458941742881,55.5542350861389;8.47441743401063,55.5540347942336;8.47422746105615,55.553821972214;8.47406840557292,55.5536311736791;8.47390408808192,55.5534440076274;8.47374068408458,55.5532549155166;8.47359023485831,55.5530784100093;8.47341739696413,55.5528781790707;8.4732632676653,55.5526972563827;8.47310337842753,55.5525089155069;8.47292466390823,55.5523057515504;8.47275494650585,55.5521172507572;8.47257817231961,55.5519213701177;8.47242497974087,55.5517337927465;8.47226926348944,55.5515395848997;8.47211022277706,55.5513443711161;8.4719446194,55.5511417918468;8.47177227909382,55.5509219382252;8.47158949785744,55.5507038574556;8.47141587288789,55.5505003444474;8.4712533060675,55.5503019389237;8.47109701244481,55.5501183085355;8.4709224965447,55.5499241266586;8.47075214343762,55.5497250322453;8.47058977799693,55.5495323535755;8.47040511844015,55.5493263890572;8.47023610032483,55.549130095301;8.47006825552627,55.5489204148819;8.46990724690675,55.5487192821974;8.46976486180641,55.5485169355889;8.469612097092,55.548327581866;8.46944801583699,55.5481329312381;8.46928241526741,55.5479369320282;8.4691178614425,55.5477402561861;8.46896137734548,55.547548075428;8.46880970407763,55.5473549282263;8.46865230932126,55.5471532521461;8.46849351294076,55.5469609437477;8.46831813310956,55.5467583351106;8.46815150066396,55.5465610277436;8.46799038285717,55.5463606662787;8.46783937199451,55.5461642295356;8.46766542893522,55.5459668984408;8.46749036082323,55.5457765348176;8.46733310234895,55.5455797168165;8.46716866210637,55.5453642877155;8.46702001977852,55.5451611247979;8.46686624888344,55.544953641143;8.46670113328458,55.5447572290116;8.46656313918284,55.5445439359203;8.46640390337623,55.5443396228161;8.46623164918053,55.5441359213966;8.46607176531533,55.5439423980279;8.46591351351368,55.5437459387586;8.4657369166579,55.543540651584;8.46556059531691,55.5433335070921;8.46540413982417,55.5431429995213;8.46524006477952,55.5429430112126;8.46507325587713,55.5427466196818;8.46489902516322,55.542539228609;8.46473521650816,55.5423380525963;8.46455034384887,55.5421287548665;8.46441120483086,55.5419140218079;8.46427795783913,55.5417080965603;8.46410907798443,55.5415026904083;8.46394430788088,55.5413019780344;8.46380349717386,55.5411382734369;8.46360912167648,55.5409028285278;8.46344401570186,55.5407142038849;8.46328621156239,55.540531987066;8.46310788788288,55.5403420511484;8.46294397102923,55.540143107475;8.46279851780251,55.5399482508858;8.46264774348301,55.539753798802;8.46249085603477,55.5395645586851;8.46234059150181,55.5393812573763;8.4621872185916,55.5391874813898;8.46205173841568,55.5389958587984;8.46190807539467,55.5387920542355;8.46177483134343,55.5385811972445;8.46165473157306,55.5383790239738;8.46154099374118,55.5381803060073;8.46144989910548,55.5379590234127;8.46136070467869,55.5377646205538;8.4612574505735,55.5375780167439;8.46115725251497,55.5373909188795;8.46105396338607,55.5371949392038;8.46096718266495,55.5370062184126;8.46087960591141,55.53680080687;8.46079315912782,55.5365951091103;8.46070521369486,55.5363772688241;8.46062306371356,55.5361714842074;8.46055303331423,55.5359637489866;8.46048892159327,55.5357541340215;8.46044214005604,55.5355521646109;8.46038546404058,55.5353383137764;8.46032444547762,55.5351249949612;8.46026506164829,55.5349119517668;8.46021187540921,55.534696449884;8.4601563338019,55.5344818218317;8.46010437614503,55.5342733050817;8.46005116026426,55.5340713477883;8.45999435656175,55.533861293193;8.45997622825931,55.5336664694001;8.45995334126887,55.5334531555197;8.45992909832216,55.5332551114992;8.45987257651898,55.5330508615407;8.45980871130685,55.5328439102959;8.45974601942941,55.532638714745;8.4596886314589,55.5324348858584;8.45963335337154,55.5322368077555;8.45957501816804,55.5320325669562;8.45950573611031,55.5318241864168;8.45944624718287,55.5316250112282;8.45939689460843,55.5314218069377;8.45935148960283,55.531223312851;8.45930972037488,55.5310384044743;8.45925492276082,55.5308485851076;8.45920123378011,55.5306748306303;8.45915400470462,55.530485742636;8.45910783510615,55.5302960354551;8.45909093125595,55.5301112042645;8.45905799293238,55.5299328633207;8.45901359334657,55.5297624676207;8.4589718212341,55.5295951436854;8.45892858660709,55.5294336865843;8.45887925206728,55.5292668331635;8.45884070244391,55.5291143140048;8.45879932275854,55.5289644002569;8.45874985241687,55.528815477796;8.45870729002677,55.5286717848796;8.45866675458206,55.5285416338276;8.45865871458058,55.5284009063509;8.45862108330235,55.5282642560118;8.45858329684877,55.5281440615575;8.45854471740427,55.5280238199846;8.45849713526936,55.5278954144544;8.45847466713954,55.5277860296593;8.45844676168292,55.5277003320079;8.45839852630521,55.5275508155561;8.45836528609617,55.5274477765318;8.4583342787994,55.5273516591577;8.45830391250543,55.5272575287838;8.4582365901362,55.5271615262952;8.45819462195742,55.5271025690374;8.45819230312449,55.527099311521;8.45817668831199,55.5270927961713;8.45810939485853,55.5270955647529;8.45786871454719,55.5271062421315;8.45773457738977,55.5271342969296;8.45757359287328,55.5271674064246;8.45739887937071,55.5272033395439;8.45723269793557,55.5272472555896;8.45706765880896,55.5272961708546;8.45690884936408,55.5273430590476;8.45675678749101,55.527387687324;8.45675770467371,55.5273874181423;8.45640165673497,55.5274963410006;8.45624494238115,55.5275443043693;8.45607293976853,55.5275971823717;8.45590792585359,55.5276476735957;8.45573389178456,55.5277008764733;8.4555369533781,55.5277610812941;8.45533937598993,55.527821481454;8.45513643154457,55.5278835223437;8.4549354850386,55.5279449524558;8.45473670357073,55.5280057207074;8.45454851225968,55.5280632515078;8.45434977940968,55.5281240048968;8.45414005617643,55.5281881180878;8.45396499788857,55.528241634073;8.45380728450719,55.5282898476543;8.45362703406329,55.5283449509013;8.45342529914692,55.5284066220335;8.45321954258518,55.5284695890022;8.4530205019866,55.5285305268019;8.45282608139422,55.5285900501515;8.45262582860552,55.5286513443187;8.45243185170778,55.5287106897769;8.45221960465728,55.5287756248212;8.45200519731245,55.5288412207879;8.45179609138255,55.5289051948352;8.45158762841758,55.5289689721732;8.45141137108911,55.5290228964912;8.45121624750908,55.5290825927663;8.45104690043166,55.5291344029562;8.45090356881163,55.5291782225949;8.45076946889505,55.5292193219733;8.45066418989801,55.5292515882226;8.45058107205406,55.5292741785767;8.45053238392841,55.5292077747309;8.45048149251931,55.5291530817754;8.4504327729018,55.5291007228425;8.45037246043296,55.5290359050818;8.45029914685512,55.52895711504;8.45022870392476,55.5288814100807;8.45015390124074,55.5288010196977;8.45005857046175,55.5286985677879;8.44994869960084,55.5285805530327;8.44985783734129,55.5284830271144;8.44976639749335,55.5283848812485;8.4496809445118,55.528293161314;8.44959266827197,55.5281984110689;8.44949844552296,55.5280972782095;8.44941177965863,55.5280042564417;8.44933565543026,55.5279225494127;8.44927174849802,55.5278539556722;8.44923422333309,55.5278136784857;8.44921358536142,55.5277883109438;8.44926891433111,55.5277516930487;8.44933984084408,55.5277255694462;8.44941697504949,55.5277044015455;8.4494889900714,55.5276913917445;8.44955802098412,55.5276956927899?timestamps=1550562811;1550562812;1550562813;1550562815;1550562816;1550562817;1550562818;1550562819;1550562820;1550562821;1550562822;1550562823;1550562824;1550562825;1550562826;1550562827;1550562828;1550562829;1550562830;1550562831;1550562832;1550562833;1550562834;1550562835;1550562836;1550562837;1550562838;1550562839;1550562840;1550562841;1550562842;1550562843;1550562844;1550562845;1550562846;1550562847;1550562848;1550562849;1550562850;1550562851;1550562852;1550562853;1550562854;1550562855;1550562856;1550562857;1550562858;1550562859;1550562860;1550562861;1550562862;1550562863;1550562864;1550562865;1550562866;1550562867;1550562868;1550562869;1550562870;1550562871;1550562872;1550562873;1550562874;1550562875;1550562876;1550562877;1550562878;1550562879;1550562880;1550562881;1550562882;1550562883;1550562884;1550562885;1550562886;1550562887;1550562888;1550562889;1550562890;1550562891;1550562892;1550562893;1550562894;1550562895;1550562896;1550562897;1550562898;1550562899;1550562900;1550562901;1550562902;1550562903;1550562904;1550562905;1550562906;1550562907;1550562908;1550562909;1550562910;1550562911;1550562912;1550562913;1550562914;1550562915;1550562916;1550562917;1550562918;1550562919;1550562920;1550562921;1550562922;1550562923;1550562924;1550562925;1550562926;1550562927;1550562928;1550562929;1550562930;1550562931;1550562932;1550562933;1550562934;1550562935;1550562936;1550562937;1550562938;1550562939;1550562940;1550562941;1550562942;1550562943;1550562944;1550562945;1550562946;1550562947;1550562948;1550562949;1550562950;1550562951;1550562952;1550562953;1550562954;1550562955;1550562956;1550562957;1550562958;1550562959;1550562960;1550562961;1550562962;1550562963;1550562964;1550562965;1550562966;1550562967;1550562968;1550562969;1550562970;1550562971;1550562972;1550562973;1550562974;1550562975;1550562976;1550562977;1550562978;1550562979;1550562980;1550562981;1550562982;1550562983;1550562984;1550562985;1550562986;1550562987;1550562988;1550562989;1550562990;1550562991;1550562992;1550562993;1550562994;1550562995;1550562996;1550562997;1550562998;1550562999;1550563000;1550563001;1550563002;1550563003;1550563004;1550563005;1550563006;1550563007;1550563008;1550563009;1550563010;1550563011;1550563012;1550563013;1550563014;1550563015;1550563016;1550563017;1550563018;1550563019;1550563020;1550563021;1550563022;1550563023;1550563024;1550563025;1550563026;1550563027;1550563028;1550563029;1550563030;1550563031;1550563032;1550563033;1550563034;1550563035;1550563036;1550563037;1550563038;1550563039;1550563040;1550563041;1550563042;1550563043;1550563044;1550563045;1550563046;1550563047;1550563048;1550563049;1550563050;1550563051;1550563052;1550563053;1550563054;1550563055;1550563056;1550563057;1550563058;1550563059;1550563060;1550563061;1550563062;1550563063;1550563064;1550563065;1550563066;1550563067;1550563068;1550563069;1550563070;1550563071;1550563072;1550563073;1550563074;1550563075;1550563076;1550563077;1550563078;1550563079;1550563080;1550563081;1550563082;1550563083;1550563084;1550563085;1550563086;1550563087;1550563088;1550563089;1550563090;1550563091;1550563092;1550563093;1550563094;1550563095;1550563096;1550563097;1550563098;1550563099;1550563100;1550563101;1550563102;1550563103;1550563104;1550563105;1550563106;1550563107;1550563108;1550563109;1550563110;1550563111;1550563112;1550563113;1550563114;1550563115;1550563116;1550563117;1550563118;1550563119;1550563120;1550563121;1550563122;1550563123;1550563124;1550563125;1550563126;1550563127;1550563128;1550563129;1550563130;1550563131;1550563132;1550563133;1550563134;1550563135;1550563136;1550563137;1550563138;1550563139;1550563140;1550563141;1550563142;1550563143;1550563144;1550563145;1550563146;1550563147;1550563148;1550563149;1550563150;1550563151;1550563152;1550563153;1550563154;1550563155;1550563156;1550563157;1550563158;1550563159;1550563160;1550563161;1550563162;1550563163;1550563164;1550563165;1550563166;1550563167;1550563168;1550563169;1550563170;1550563171;1550563172;1550563173;1550563174;1550563175;1550563176;1550563177;1550563178;1550563179;1550563180;1550563181;1550563182;1550563183;1550563184;1550563185;1550563186;1550563187;1550563188;1550563189;1550563190;1550563191;1550563192;1550563193;1550563194;1550563195;1550563196;1550563197;1550563198;1550563199;1550563200;1550563201;1550563202;1550563203;1550563204;1550563205;1550563206;1550563207;1550563208;1550563209;1550563210;1550563211;1550563212;1550563213;1550563214;1550563215;1550563216;1550563217;1550563218;1550563219;1550563220;1550563221;1550563222;1550563223;1550563224&radiuses=32;48;48;24;24;24;16;16;24;24;24;24;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;24;24;24;24;24;24;24;32;32;32;32;32;32;32;32;24;24;32;32;32;24;24;32;32;32;32;32;32;24;24;24;24;16;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;32;32;32;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16;16&annotations=nodes&generate_hints=false&overview=false</pre>
</details>

Which yields the following response (and commented with my understanding):
  <pre>
  $ cat response | python -mjson.tool | grep confidence
            "confidence": 0.982963, // only one match
  $ cat response | python -mjson.tool | grep alternatives_count | wc -l
       442 // total number of trace points
  $ cat response | python -mjson.tool | grep alternatives_count | sort -u
            "alternatives_count": 0, // 441 of these
            "alternatives_count": 1, // only one of these, indicating that with more input this one point could be a different point, ignorable
  $ cat response | python -mjson.tool | grep matchings_index | wc -l
       442 // total number of trace points
  $ cat response | python -mjson.tool | grep matchings_index | sort -u
            "matchings_index": 0, // 442 of these, meaning there is just one route
  $ cat response | python -mjson.tool | grep annotation | wc -l
       441 // total number of legs
  $ cat response | python -mjson.tool | grep null | wc -l
       20 // total number of input coordinates that could not be matched to the route</pre>

Full response: https://pastebin.com/Nvu8xpcM

There is a surplus of 28 additional trace points. This surplus seems unrelated to the 20 unmatched input coordinates.

The number of legs pair perfectly with the number of trace points... _but how do I pair up the orginal 413 coordinates with the 441 trace points?_

Curiously the indicies 3 to 416 in the trace points lines up near perfectly with the input coordinates.

I hope someone can provide me with a little insight :)

**Comment by rdkt** [comment]
I am encountering similar mismatch issues. I've noticed the problem is less prevalent for smaller matches. As an aside @jjetrifork I notice you set `--max-matching-size 2147483647`. Have you been able to run matches of on the order of 10^4 or 10^5 coordinates? This is something I'm looking to do - thanks!

**Comment by jjetrifork** [comment]
@rdkt  For my use case the mean number of matches is ~1200 and I have to match all in one go :/ However I don't think I have exceeded 50.000 yet, I looked up the datatype for max matching size and chose the maximum for the data type.
