### ISSUE TITLE
libosrm on Windows 10

### ISSUE THREAD

**Issue by Eichenherz** [Project-OSRM/osrm-backend#5376]
I'm having trouble compiling osrm for C++ dev under Windows.
I tried the wiki guide, it doesn't work on my machine. I managed to link osrm.lib into my project but then I had Boost link errors( I did linked it too ). 
I tried with libosrm_Release and it doesn't work, maybe because it's outdated.
Regards !

**Comment by SiarheiFedartsou** [comment]
Our CI builds it for Windows https://github.com/Project-OSRM/osrm-backend/blob/bfb74c2dad0d7c653919271b3329b70c9863e756/scripts/ci/windows-build.bat#L5
