### ISSUE TITLE
Healthcheck in docker container

### ISSUE THREAD

**Issue by djonik1562** [Project-OSRM/osrm-backend#5383]
Hello.
I run docker container with image **osrm/osrm-backend:v5.22.0**. 
I want check health of service, but curl or wget not install into container for test cmd like 
```
healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:5000/route/v1/driving/37.687266,55.736505;37.7198,55.78874?overview=false"]
```
Help, how i can monitoring service? Maybe add curl to docker build? 
Thank you.

**Comment by grib0** [comment]
If you want healthcheck, then you'll need to create your own dockerfile as helthcheck is not present in the osrm-backend dockerfile.
You can then install curl inside your dockerfile based from `osrm/osrm-backend:v5.22.0`
And instead of using curl, you can use netstat to check if port 5000 is listening, see https://stackoverflow.com/questions/46362935/how-to-add-a-docker-health-check-to-test-a-tcp-port-is-open

**Comment by djonik1562** [comment]
Thank you for your answer.
I want do docker image from sources, edit dockerfile for curl and build it. 
Socket may be listening, but not answer. Curl better check for healthcheck, for me.
Thank you.

**Comment by djonik1562** [comment]
> If you want healthcheck, then you'll need to create your own dockerfile as helthcheck is not present in the osrm-backend dockerfile.
> You can then install curl inside your dockerfile based from `osrm/osrm-backend:v5.22.0`
> And instead of using curl, you can use netstat to check if port 5000 is listening, see https://stackoverflow.com/questions/46362935/how-to-add-a-docker-health-check-to-test-a-tcp-port-is-open

I try to test healthcheck by
```
netstat -an | grep 5000
```
and get error `netstat: command not found`

**Comment by grib0** [comment]
You have to add the install of netstat in your Dockerfile

**Comment by daniel-j-h** [comment]
Health checking by testing connectivity is not a good idea. You want to test that you are able to route on your base map, and not that a connection to the server works. Use a dummy request against e.g. the nearest service or the route service. Snapping should handle cases where your dataset is small, too.

**Comment by djonik1562** [comment]
I want testing route test. 
Working on my dockerfile for osrm-backend.

**Comment by SiarheiFedartsou** [comment]
Closing as stale.

**Comment by konstantinosZartaloudis** [comment]
printf "GET / HTTP/1.1\n\n" > /dev/tcp/127.0.0.1/5000
