### ISSUE TITLE
Default car height is too high

### ISSUE THREAD

**Issue by Zverik** [Project-OSRM/osrm-backend#5388]
2.5 meters is okay for a van, but really, even the largest SUVs are under 2 meters. This default prevents routing over some US expressways, notably CT 15.

**Comment by trigpoint** [comment]
Should SUVs be considered normal as a 2m height restriction causes unnecessary restrictions on routing for normal cars.
Eurotunnel has two routes through it teminals for passenger vehicles.

The trains are divided into two sections, a high vehicle section and a section for standard cars with a height limit of 1.85m. OSRM is unable to follow this route as car.lua has a maximum height of 2m.

The issue of car.lua also causes issues here https://map.project-osrm.org/?z=17&center=52.616433%2C-2.442065&loc=52.615993%2C-2.441604&loc=52.615302%2C-2.442162&hl=en&alt=0&srv=0

https://www.geograph.org.uk/photo/4893893

Height restrictions of 6ft/1.8m are not uncommon on the entrance to car parks.

Should normal cars be restricted to places where SUVs can go?
