### ISSUE TITLE
osrm-extract fails on latest Singapore excerpt 

### ISSUE THREAD

**Issue by xdmiodz** [Project-OSRM/osrm-backend#5390]
OSM excerpt is taken from 
https://download.bbbike.org/osm/bbbike/Singapore/Singapore.osm.pbf

The failure log: 

```
╰─$ osrm-extract -p profiles/car.lua Singapore.osm.pbf --location-dependent-data data/driving_side.geojson
[info] Parsed 27 location-dependent features with 27 GeoJSON polygons
[info] Using script profiles/car.lua
[info] Input file: Singapore.osm.pbf
[info] Profile: car.lua
[info] Threads: 4
[info] Parsing in progress..
[info] input file generated by osmconvert 0.8.4
[info] timestamp: 2019-02-25T02:00:01Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
terminate called after throwing an instance of 'sol::error'
  what():  lua: error: invalid location
[1]    5243 abort (core dumped)  osrm-extract -p profiles/car.lua Singapore.osm.pbf
```

The issue is happens only with `--location-dependent-data data/driving_side.geojson`. Without it works fine, but turn-by-turn navigation gives incorrect driving side

**Comment by danpat** [comment]
When the `--location-dependent-data` option is used, it's assumed that the OSM file will have coordinates for the first node on each way.

Try using a different Singapore OSM extract - I suspect the one at bbbike.org is not trimmed correctly, and has ways that reference non-existent nodes.  The ones at Geofabrik are properly clipped and include all nodes for all referenced ways:

https://download.geofabrik.de/asia/malaysia-singapore-brunei.html

When used without the `--location-dependent-data` option, OSRM will ignore the missing nodes, but the current logic requires them with `--location-dependent-data` gets used.

**Comment by xdmiodz** [comment]
Thanks!
