### ISSUE TITLE
Have osrm support to evaluation way by user?

### ISSUE THREAD

**Issue by GFZRZK** [Project-OSRM/osrm-backend#5391]
I may have some special options，so I want to implement the function which evaluates the way by myself, have osrm support this feature? Thanks!

**Comment by chaupow** [comment]
When extracting the osm file, OSRM uses a lua profile to evaluate the data. 

You can change and adjust the lua profile as you need. Take a look at 
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua

Especially at 
- function process_way(profile, way, result, relations)

You can add your own [wayhandler](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua) or edit the ones available.

**Comment by GFZRZK** [comment]
@chaupow So, in my understanding, the way to evaluate the road is in the process of constructing data, not in the process of searching, is this correct? Thank you for your answer

**Comment by chaupow** [comment]
Yes, that's correct :)
