### ISSUE TITLE
Route MAP API

### ISSUE THREAD

**Issue by timusiiit123** [Project-OSRM/osrm-backend#5392]
Hi,
I am using this link: 
[https://router.project-osrm.org/route/v1/driving/79.137005,28.0286498;77.171695,28.627393?overview=full&alternatives=true&steps=false&hints=o0tChYNMQoUTAAAAiQEAAMEAAAAAAAAAbEJ2QR5KmEMS5xVDAAAAABMAAACJAQAAwQAAAAAAAABRWAAAHIG3BA2qqwHtiLcE6q6rAQEATxTeW_ME;aWlFhWppRYUAAAAAfwAAAAAAAADSAAAAAAAAAJZNcEIAAAAA4CTHQgAAAAB_AAAAAAAAANIAAABRWAAAO5OZBJXUtAHvi5kEwdG0AQAAzwPeW_ME](https://router.project-osrm.org/route/v1/driving/79.137005,28.0286498;77.171695,28.627393?overview=full&alternatives=true&steps=false&hints=o0tChYNMQoUTAAAAiQEAAMEAAAAAAAAAbEJ2QR5KmEMS5xVDAAAAABMAAACJAQAAwQAAAAAAAABRWAAAHIG3BA2qqwHtiLcE6q6rAQEATxTeW_ME;aWlFhWppRYUAAAAAfwAAAAAAAADSAAAAAAAAAJZNcEIAAAAA4CTHQgAAAAB_AAAAAAAAANIAAABRWAAAO5OZBJXUtAHvi5kEwdG0AQAAzwPeW_ME) to get the distance between the two position points.

My question is when I try to access this link very frequently, it sends me this-
`{
    "message": "Too Many Requests"
}` 

But after sometime, it sends me the correct response. I want to know how to remove this. And I am not familiar with C++ APIs. Can anyone tell where I can find the above link code?

**Comment by quiqua** [comment]
You are using a demo version of OSRM and is rate-limited:
Please have a look for further discussion on this at this issue https://github.com/Project-OSRM/osrm-backend/issues/5142 & https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

**Comment by timusiiit123** [comment]
Thanks.
If I do this at my own server, I will not get any kind of this message. Right?
`{ "message": "Too Many Requests" }`

**Comment by quiqua** [comment]
> If I do this at my own server, I will not get any kind of this message. Right?

Yep :)

**Comment by timusiiit123** [comment]
Thank you. 👍

**Comment by Samek-eng** [comment]
how can i host osrm server in my host?
