### ISSUE TITLE
Distance in destinations from Table service different to distances from annotations=distance

### ISSUE THREAD

**Issue by brokenwrists** [Project-OSRM/osrm-backend#5393]
Hi team

I have look through a couple of tickets and checked the wiki but can't find anything to point me in the right direction. I am running OSRM 5.21 on Debian 9 on the https://download.geofabrik.de/australia-oceania/new-zealand-latest.osm.pbf mapset running on the MLD algorithm.

My call is: `table/v1/driving/171.204495,-42.432732;171.174443,-42.500393;171.211212,-42.453574;171.195902,-42.465387;170.538913,-43.147823;170.974163,-42.721578;171.574526,-41.76170?sources=0&annotations=distance,duration`

which returns:
```
{
    "code": "Ok",
    "sources": [
        {
            "hint": "z0kEgBdKBIA2AAAAAAEAAAAAAAAAAAAA04oYQr4vMUMAAAAAAAAAADYAAAAAAQAAAAAAAAAAAADCAQAAZGA0CvmGeP2PXzQKJId4_QAA_wCD5rou",
            "distance": 18.168871,
            "name": "Fitzgerald Street",
            "location": [
                171.204708,
                -42.432775
            ]
        }
    ],
    "destinations": [
        {
            "hint": "z0kEgBdKBIA2AAAAAAEAAAAAAAAAAAAA04oYQr4vMUMAAAAAAAAAADYAAAAAAQAAAAAAAAAAAADCAQAAZGA0CvmGeP2PXzQKJId4_QAA_wCD5rou",
            "distance": 18.168871,
            "name": "Fitzgerald Street",
            "location": [
                171.204708,
                -42.432775
            ]
        },
        {
            "hint": "bT8EgHQ_BICiAAAALwAAAGsAAAAAAAAA-GThQhowAEIABZRCAAAAAKIAAAAvAAAAawAAAAAAAADCAQAAUekzCg9_d_0r6jMK1353_QEAfwyD5rou",
            "distance": 18.962127,
            "name": "Keith Road",
            "location": [
                171.174225,
                -42.500337
            ]
        },
        {
            "hint": "WkkEgHJJBIBJAAAALAAAAAAAAAAAAAAAkBmjQrkMQUIAAAAAAAAAAEkAAAAsAAAAAAAAAAAAAADCAQAAJHk0Cvs1eP3MeTQKujV4_QAA_wyD5rou",
            "distance": 15.588308,
            "name": "Alexander Street",
            "location": [
                171.211044,
                -42.453509
            ]
        },
        {
            "hint": "CUMEgCNDBIC9AAAA5QAAALUAAAAAAAAAjDkDQ0vyHkNa4_pCAAAAAL0AAADlAAAAtQAAAAAAAADCAQAAQT00CtwHeP3-PTQKlQd4_QEArwGD5rou",
            "distance": 17.428769,
            "name": "Milton Road",
            "location": [
                171.195713,
                -42.465316
            ]
        },
        {
            "hint": "7TsFgPI7BYCgAAAAjgEAALkCAAA7AAAASouyQ_3LXUQ3CMJEo08DQ6AAAACOAQAAuQIAADsAAADCAQAAnzcqCo6cbf2hNyoK0Z1t_QUArwWD5rou",
            "distance": 35.883692,
            "name": "Whataroa Highway",
            "location": [
                170.538911,
                -43.148146
            ]
        },
        {
            "hint": "sTgFgBU5BYAuAAAAPwAAAAAAAAAAAAAAaCxNQo-PjEIAAAAAAAAAAC4AAAA_AAAAAAAAAAAAAADCAQAAXNwwCmIfdP3T2zAK1h50_QAA3weD5rou",
            "distance": 19.177576,
            "name": "Stafford Street",
            "location": [
                170.9743,
                -42.721438
            ]
        },
        {
            "hint": "5G8EgOVvBIAAAAAAKwAAAKAAAAAjBwAAAAAAANGr7EEvGt1CJ7WeRAAAAAArAAAAoAAAACMHAADCAQAAcAY6CkHFgv3-BDoKXMSC_QQArwiD5rou",
            "distance": 39.916101,
            "name": "McPadden Road",
            "location": [
                171.574896,
                -41.761471
            ]
        }
    ],
    "durations": [
        [
            0,
            926.1,
            433.1,
            600.1,
            5877.8,
            2490.2,
            5175.2
        ]
    ],
    "distances": [
        [
            0,
            9560.7,
            3271.4,
            5099.1,
            115367.9,
            42643.5,
            101336.2
        ]
    ]
}
```

Now the durations and distances values look great and compare well with other mapping tools. My question is am I understanding the "distance" found in the list of "destinations" wrong? Does it not mean distance? How can something be 115367.9M away but the distance value is 35.88?

**Comment by danpat** [comment]
@brokenwrists The `sources` and `destinations` tell you where the coordinates you supplied snapped to the road network.  The `distance` value there is the straight-line distance from the coordinate you supplied to the location we snapped to for the actual route calculation.  We supply it as a convenience, you could calculate it yourself based on your original coordinates and the `location` property on each source or destination.

The `distances` array tells you the actual route length from the `source` snapped location to each `destinations` snapped location.

**Comment by brokenwrists** [comment]
> @brokenwrists The `sources` and `destinations` tell you where the coordinates you supplied snapped to the road network. The `distance` value there is the straight-line distance from the coordinate you supplied to the location we snapped to for the actual route calculation. We supply it as a convenience, you could calculate it yourself based on your original coordinates and the `location` property on each source or destination.
> 
> The `distances` array tells you the actual route length from the `source` snapped location to each `destinations` snapped location.

Hi @danpat thanks for getting back to me. In my example it's a 1*7 matrix with index 0 being the starting point, how can the SLD be            ```
 "hint": "7TsFgPI7BYCgAAAAjgEAALkCAAA7AAAASouyQ_3LXUQ3CMJEo08DQ6AAAACOAQAAuQIAADsAAADCAQAAnzcqCo6cbf2hNyoK0Z1t_QUArwWD5rou",
            "distance": 35.883692,
            "name": "Whataroa Highway",
            "location": [
                170.538911,
                -43.148146
            ]
``` suggested to be 35.88KM when the straight line distance as the crow flies is approxmiately 96KM?

"The distance value there is the straight-line distance from the coordinate you supplied to the location we snapped to for the actual route calculation. " - so in my example my coordinate I supplied is the first index because source = 0 .. so would it not be calculated from ```
171.204708,-42.432775``` to   `170.538911,-43.148146`

**Comment by danpat** [comment]
You're misunderstanding the result.

The `sources` and `destinations` parts only tell you about where we had to move the input coordinates to in order to start route calculations.  If you don't drop a coordinate exaclty on a road, we have to "snap" it.  The `distance` property describes how far we moved your supplied coordinates to be exactly on a road.  The values are in metres, not km.

<img width="530" alt="screen shot 2019-03-05 at 8 21 53 pm" src="https://user-images.githubusercontent.com/1892250/53855988-ced7e880-3f84-11e9-84d5-b1046b84ada4.png">

To find the road-network distance, you need to look at the `result.distances[]` array, it's at the bottom of your example.  It shows the distance from the source you specified to each of the destinations, following the road network.  These values are also in metres.

**Comment by brokenwrists** [comment]
> You're misunderstanding the result.
> 
> The `sources` and `destinations` parts only tell you about where we had to move the input coordinates to in order to start route calculations. If you don't drop a coordinate exaclty on a road, we have to "snap" it. The `distance` property describes how far we moved your supplied coordinates to be exactly on a road. The values are in metres, not km.
> 
> <img alt="screen shot 2019-03-05 at 8 21 53 pm" width="530" src="https://user-images.githubusercontent.com/1892250/53855988-ced7e880-3f84-11e9-84d5-b1046b84ada4.png">
> 
> To find the road-network distance, you need to look at the `result.distances[]` array, it's at the bottom of your example. It shows the distance from the source you specified to each of the destinations, following the road network. These values are also in metres.

Ahh that makes sense. Thanks!
