### ISSUE TITLE
Connecting Postgis to OSRM for map matching

### ISSUE THREAD

**Issue by alex6H** [Project-OSRM/osrm-backend#5397]
Hello,

It's not an issue but i can find a place to post my question. Let me know if there is a better place. 

Is there a way to connect a PostGis database to an OSRM local server to make multiple request? 
I tried to find information on the subject but without success.

I work on the GPS position database of firefighters truck and ambulance in my city. The accuracy of GPS tracks is quite poor and I would like to make a map matching of all tracks. After that, load all the match in the db, get the emergency speed of each road in town.

Thanks,

**Comment by danpat** [comment]
The usual way to do this is to write a script that does something like:

 1. Extract the geometry from your database
 2. Make a HTTP or NodeJS call to OSRM to perform the map-matching
 3. Parse the OSRM response and extract the data you want
 4. Re-insert it into your database.

If you're familiar with NodeJS, there's an example here:

https://github.com/Project-OSRM/osrm-backend/blob/master/example/example.js

that shows how to call OSRM's map-matching functions directly.  You would need to add code there to query and re-insert data into your database - there are Postgres drivers available for Node that would allow you to do this.
