### ISSUE TITLE
strange choice of routing between two points

### ISSUE THREAD

**Issue by ivantrouvetout** [Project-OSRM/osrm-backend#5398]
with the latest version of OSRM, we have rather strange routing choices
Do you have a particular weight that will explain the choice of the longest route ?

http://map.project-osrm.org/?z=14&center=49.968724%2C3.134880&loc=49.980495%2C3.121319&loc=49.980395%2C3.121592&loc=49.952214%2C3.122520&hl=en&alt=0
![image](https://user-images.githubusercontent.com/10398391/54194716-30d0aa80-44bd-11e9-89cf-4e17fe1b828b.png)
![image](https://user-images.githubusercontent.com/10398391/54194591-e6e7c480-44bc-11e9-9437-7af15473f71d.png)

http://map.project-osrm.org/?z=14&center=49.965577%2C3.133979&loc=49.980495%2C3.121319&loc=49.980395%2C3.121592&loc=49.952932%2C3.123035&hl=en&alt=0
![image](https://user-images.githubusercontent.com/10398391/54194686-1d254400-44bd-11e9-9c6b-848aa2ea557a.png)
![image](https://user-images.githubusercontent.com/10398391/54194638-fbc45800-44bc-11e9-9788-666197828235.png)

**Comment by systemed** [comment]
This appears to be fixed now so was presumably a data issue.
