### ISSUE TITLE
Overpass API query for foot.lua

### ISSUE THREAD

**Issue by teresaejunior** [Project-OSRM/osrm-backend#5404]
Hi! Nobody replied to me on StackExchange, could you please help? I need to create "walking" routes in various different places of the world, but I don't have the hardware for Planet.osm. So I will process data from Overpass API for every area separately (for the *Table* and *Route* services).

If I create a route linking various places inside a bbox or polygon, I need to consider, for example, a path that joins two places but goes through roads which are outside the polygon.

Which way would you please recommend me to query for these areas? By adding ~1km radius around the area to include more roads? by using "recurse" on all nodes and ways around it? will I need things like relations too? I'm sorry, I can't understand much how all this stuff works...

Some samples:

All nodes, ways, and relations inside the area:
```c#
(
  node(poly:"50.7 7.1  50.7 7.105  50.7025 7.1025");
  way(poly:"50.7 7.1  50.7 7.105  50.7025 7.1025");
  rel(poly:"50.7 7.1  50.7 7.105  50.7025 7.1025");
);
out;
```

Adding 1km of data outside the area:
```c#
(
  node(around:1000, 50.7,7.1, 50.7,7.105, 50.705,7.1025);
  way(around:1000, 50.7,7.1, 50.7,7.105, 50.705,7.1025);
  rel(around:1000, 50.7,7.1, 50.7,7.105, 50.705,7.1025);
);
out;
```

Include ways which reference nodes up to 1km around the area (excludes relations..?):
```c#
node(around:1000, 50.7,7.1, 50.7,7.102, 50.7015,7.101);
way(bn);
(._; >;);
out;
```

All ways and relations to nodes 1km around the area (returns a lot of data, and may return things like the whole country border, very extensive rivers and roads, etc.):
```c#
(
  node(around:1000,50.7,7.1,50.7,7.102,50.7015,7.101);
  <;
  >;
);
out;
```

**Comment by danpat** [comment]
I would recommend getting pre-cut downloads from https://download.geofabrik.de/, and merging them together with `osmium`.  They may be a bit larger than you want, but it'll be significantly simpler.

If you must fetch from Overpass, I'd suggest filtering out anything with `building=yes` - these are by far the largest set of data that won't be used by the `foot.lua` script.

**Comment by teresaejunior** [comment]
> I would recommend getting pre-cut downloads from https://download.geofabrik.de/, and merging them together with `osmium`. They may be a bit larger than you want, but it'll be significantly simpler.

I will use many areas around the world, and this wouldn't differ much from processing Planet.osm. I will need small areas of a few blocks each.

> If you must fetch from Overpass, I'd suggest filtering out anything with `building=yes` - these are by far the largest set of data that won't be used by the `foot.lua` script.

Will do that, thanks! My concern remains about the roads, though!
