### ISSUE TITLE
Error On Project-OSRM/osrm-backend When make

### ISSUE THREAD

**Issue by robotsp** [Project-OSRM/osrm-backend#5405]
[ 75%] Linking CXX executable osrm-partition
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function parseArguments(int, char**, std::string&, osrm::partitioner::PartitionerConfig&): error: undefined reference to 'operator delete(void*, unsigned long)'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function parseArguments(int, char**, std::string&, osrm::partitioner::PartitionerConfig&): error: undefined reference to 'operator delete(void*, unsigned long)'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function boost::any::holder<unsigned long>::~holder(): error: undefined reference to 'operator delete(void*, unsigned long)'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function boost::any::holder<double>::~holder(): error: undefined reference to 'operator delete(void*, unsigned long)'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function boost::system::error_category::std_category::~std_category(): error: undefined reference to 'std::_V2::error_category::~error_category()'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function boost::system::error_category::std_category::~std_category(): error: undefined reference to 'std::_V2::error_category::~error_category()'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function boost::system::error_category::std_category::equivalent(std::error_code const&, int) const: error: undefined reference to 'std::_V2::generic_category()'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function boost::system::error_category::std_category::equivalent(std::error_code const&, int) const: error: undefined reference to 'typeinfo for std::_V2::error_category'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const: error: undefined reference to 'std::_V2::generic_category()'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const: error: undefined reference to 'typeinfo for std::_V2::error_category'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:function std::__throw_regex_error(std::regex_constants::error_type, char const*): error: undefined reference to 'std::runtime_error::runtime_error(char const*)'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:typeinfo for boost::system::error_category::std_category: error: undefined reference to 'typeinfo for std::_V2::error_category'
CMakeFiles/osrm-partition.dir/src/tools/partition.cpp.o:partition.cpp:vtable for boost::system::error_category::std_category: error: undefined reference to 'std::_V2::error_category::_M_message(int) const'

In file included from /data/Project-OSRM/osrm-backend/include/storage/shared_data_index.hpp:4:0,
                 from /data/Project-OSRM/osrm-backend/include/engine/datafacade/contiguous_block_allocator.hpp:4,
                 from /data/Project-OSRM/osrm-backend/include/engine/datafacade/contiguous_internalmem_datafacade.hpp:5,
                 from /data/Project-OSRM/osrm-backend/include/engine/datafacade.hpp:4,
                 from /data/Project-OSRM/osrm-backend/include/engine/routing_algorithms/tile_turns.hpp:5,
                 from /data/Project-OSRM/osrm-backend/src/engine/routing_algorithms/tile_turns.cpp:1:
/data/Project-OSRM/osrm-backend/include/storage/shared_datatype.hpp:102:26: warning: inline function ‘virtual void* osrm::storage::BaseDataLayout::GetBlockPtr(void*, const string&) const’ used but never defined
     virtual inline void *GetBlockPtr(void *base_ptr, const std::string &name) const = 0;
                          ^~~~~~~~~~~
[ 87%] Built target ENGINE
make: *** [all] Error 2

**Comment by robotsp** [comment]
Centos 7.4,

I follow the guidance : https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM
-Centos 7.x, but fail when make, logs are above, thanks@!

**Comment by wangyoucao577** [comment]
Default compiler is gcc 4.8.5 on CentOS7.4, which is too old for OSRM. If it's the reason, please follow the document https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM#red-hat-enterprise-linux-fedora-or-centos to update newer version gcc first. 

My main platform is also CentOS7.4, and I use gcc6.5 as my compiler. It works well.

**Comment by robotsp** [comment]
Thanks! Finally the problem fixed, but with another problem coming out:


terminate called after throwing an instance of 'osrm::util::exception'
  what():  There are no edges remaining after parsing.src/extractor/extractor.cpp:645
Aborted

./build/osrm-contract map.xml.osrm
[warn] Missing/Broken File: map.xml.osrm.ebg
[warn] Missing/Broken File: map.xml.osrm.ebg_nodes
[warn] Missing/Broken File: map.xml.osrm.properties

./build/osrm-routed map.xml.osrm
With the log output:
[error] Required files are missing, cannot continue

**Comment by rgugliel** [comment]
Maybe close this issue since the new issue is #5407 ?

**Comment by newdha** [comment]
> Centos 7.4,
> 
> I follow the guidance : https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM
> -Centos 7.x, but fail when make, logs are above, thanks@!

I face the same problem......
How do you fix it?
