### ISSUE TITLE
5.22.0 vs 5.20.0 major speedup in both extract and contract

### ISSUE THREAD

**Issue by cyril23** [Project-OSRM/osrm-backend#5406]
I am just wondering about a significant speedup during preprocessing using 
the new docker `osrm-backend:v5.22.0` vs the old `osrm-backend:v5.20.0`

Of course I am glad that the new version is faster. My question is: 

**Do you guys have any idea why the preprocessing is so much faster now?**

- I used `europe-latest.osm.pbf` by downloading 
https://download.geofabrik.de/europe-latest.osm.pbf
- My preprocessing bash script: 

```
OSRM_BACKEND_VERSION="osrm-backend:v5.22.0"
TRANSPORTATION_PROFILE="/opt/car.lua"
PP_EXTRACT="/var/log/preprocessing_02_extract.log"
PP_CONTRACT="/var/log/preprocessing_03_contract.log"
OSM_FILE="europe-latest.osm.pbf"
# extract:
(cd $OSRM_INSTALL_DIR && docker run -t -v $(pwd):/data osrm/$OSRM_BACKEND_VERSION osrm-extract -p $TRANSPORTATION_PROFILE /data/$OSM_FILE >> $PP_EXTRACT 2>&1)
# contract:
(cd $OSRM_INSTALL_DIR && docker run -t -v $(pwd):/data osrm/$OSRM_BACKEND_VERSION osrm-contract /data/$OSM_FILE >> $PP_CONTRACT 2>&1)
```

### Log Files

- [v5.20.0 preprocessing_02_extract.log](https://github.com/Project-OSRM/osrm-backend/files/3008132/v5.20.0-preprocessing_02_extract.log)
- [v5.20.0 preprocessing_03_contract.log](https://github.com/Project-OSRM/osrm-backend/files/3008133/v5.20.0-preprocessing_03_contract.log)
- [v5.22.0 preprocessing_02_extract.log](https://github.com/Project-OSRM/osrm-backend/files/3008137/v5.22.0-preprocessing_02_extract.log)
- [v5.22.0 preprocessing_03_contract.log](https://github.com/Project-OSRM/osrm-backend/files/3008138/v5.22.0-preprocessing_03_contract.log)

### Benchmark

| task        | v5.20.0           | v5.22.0  | speedup |
|:-------------:|-------------:| -----:|-----:|
| extract: nodes/sec (see .log)      | 69720 | 176416 | **2.5** |
| extract: edges/sec (see .log)      | 30662 |   77581 | **2.5** |
| extract: begin<br>extract: end<br>extract: hours      | 21.03.2019 16:52<br>21.03.2019 19:39<br>2.78 | 25.03.2019 13:22<br>25.03.2019 14:11<br>0.82 | <br><br>**3.4** |
| contract: seconds (see .log) | 169623 | 9119 | **18.6** |
| contract: begin<br>contract: end<br>contract: hours      | 21.03.2019 19:39<br>23.03.2019 18:47<br>47.13 | 25.03.2019 14:11<br>25.03.2019 16:44<br>2.55 | <br><br>**18.5** |

### System information
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```
- Intel Xeon E5-1650 V3 @ 3.50GHz (i.e. 6 cores, 12 threads)
- 256 GB RAM, 480 GB SSD

### Server Monitoring

![Dok1](https://user-images.githubusercontent.com/5645872/55001489-fb57b100-4fd4-11e9-8006-b375f7b09d0e.png)

**Comment by danpat** [comment]
IIRC, nothing significant changed between 5.20 and 5.22 that would explain this.

In OSRM 5.20, we switched from Alpine Linux to Debian, and I *would* expect a big difference from pre-5.20 to post 5.20 (memory allocation is much faster by default under GNU `libc` than `musl`)

Does your data still generate routes properly?  The kind of slowdown you're describing is usually only explainable by:

  a. Using the wrong profile and not admitting many edges to the graph
  b. Using `debug`/non-optimized versions of the binaries

https://github.com/Project-OSRM/osrm-backend/blob/5.22/CHANGELOG.md

**Comment by cyril23** [comment]
> Does your data still generate routes properly?

I have verified several testcases with 5 to 1000 waypoints, the routes are pretty much identical to the old ones.

> Using the wrong profile and not admitting many edges to the graph

The log file looks normal, doesn't it? The files are about the same sizes.

> Using debug/non-optimized versions of the binaries

I just use the official docker images.

As far as I remember even pre v5.20.0 was simlilar in preprocessing speed, v5.22.0 is the first huge improvement. It feels like using CH vs. MLD in preprocessing speed. But I have verified, the routing queries response time is still CH speed (distance matrix of 1000 randomized waypoints in southern Germany takes about 2 seconds; MLD takes about 95 seconds here).

**Comment by danpat** [comment]
Hmm.  Well, you can compare the two versions here:

https://github.com/Project-OSRM/osrm-backend/compare/v5.20.1...v5.22.0?expand=1

There's nothing significant I can see that would explain this - none of the contraction code has been touched recently.

The image base *did* switch from Debian `buster` to `slim`, but I would not expect that to deliver an 18x speedup, particularly if you didn't see a huge change from the switch from Alpine to Debian.

Anecdotally, 47 hours is a *really* slow `osrm-contract` step in your old setup, the current 2.55 hours is more in line with what I'd expect.

My spidey sense feels that some point of CPU contention changed in your docker setup (CPU limits, other things running on the box?).  By default, Docker *exposes* all the host CPUs, but it may have been limiting the CPU time given to tasks running in your container.

**Comment by grib0** [comment]
As far as I remember the 5.20.0 was supposed to be based on a debian, but there were some issue in osrm-extract functions and it has been re-published as an alpine based image .
You can see the image size in https://hub.docker.com/r/osrm/osrm-backend/tags it's 9Mo for the v5.20.0 wich is the same size as previous version. Version v5.21.0 is the first release with came with a debian base image, and yes as @danpat said it's because of musl vs glibc performance comparaison in memory allocation

**Comment by SiarheiFedartsou** [comment]
Closing as probably non-actionable.
