### ISSUE TITLE
terminate called after throwing an instance of 'osrm::util::exception'

### ISSUE THREAD

**Issue by robotsp** [Project-OSRM/osrm-backend#5407]
terminate called after throwing an instance of 'osrm::util::exception'
what(): There are no edges remaining after parsing.src/extractor/extractor.cpp:645
Aborted

./build/osrm-contract map.xml.osrm
[warn] Missing/Broken File: map.xml.osrm.ebg
[warn] Missing/Broken File: map.xml.osrm.ebg_nodes
[warn] Missing/Broken File: map.xml.osrm.properties

./build/osrm-routed map.xml.osrm
With the log output:
[error] Required files are missing, cannot continue

**Comment by danpat** [comment]
Try running `osrm-routed -a CH map.xml.osrm`

**Comment by prusswan** [comment]
I had a similar error, when elements in the osm file are missing expected tags relevant to topology, such as `'highway'`.

**Comment by answerquest** [comment]
Hi @danpat , on my end the same error is happening at `osrm-extract` stage.
```
osrm-extract -p profiles/foot-modified.lua place.pbf
```
But that leads to : there is no `map.xml.osrm` to work with. I only have a `.pbf`. How can one get a `.xml.osrm` ?
