### ISSUE TITLE
osrm-datastore requires 2x memory for realtime updates, right?

### ISSUE THREAD

**Issue by TehNrd** [Project-OSRM/osrm-backend#5408]
It would appear that you need 2x the amount of memory required for the osrm data if you want to perform real-time updates with no downtime.

Assuming planet coverage with the default car profile requires around 78GB of memory...run this command:
```
osrm-datastore --dataset-name=car osm-car.osrm
```
It allocates a memory block of 78GB and fills it up with the data. Server gets new .osrm data. Run the command again and it requests a new block of 78GB, fills it up with the data, redirects clients to use it, and then unlocks the original 78GB. Therefore this operation requires 156GB of memory to complete.

78GB of memory sitting around doing nothing most of the time is quite expensive and it seems better just to spin up a brand new server behind a load balancer with the latest data and then kill the old server. 

Is there a better way to go about this? Perhaps running `osrm-datastore --spring-cleaning` first and then reloading the data into memory, but with this approach there would be a few minutes in which RAM wouldn't be used and performance would drop until the shared memory is refilled, correct?

I realize this is a bit beyond the scope of core OSRM and gets into architecture, but I was wondering if there was an approach that I perhaps was not considering given the experts here.

**Comment by danpat** [comment]
It's a bit more complex than that.  The various `.osrm` files are broken up into two sets:  ones that don't change after traffic updates (e.g. road geometry, names, intersection descriptions, graph partitions, etc), and ones that do (graph with edge weights).

Here's a quick example with some files I had lying around:

```
$ ./osrm-datastore colorado-latest.osrm
[info] Data layout has a size of 1745 bytes
[info] Allocating shared memory of 119762478 bytes
[info] Data layout has a size of 1052 bytes
[info] Allocating shared memory of 306961760 bytes
[info] All data loaded. Notify all client about new data in:
[info] /static	0
[info] /updatable	1
[info] All clients switched.
$ ./osrm-datastore --list
[info] name	shm key	timestamp	size
[info] /static	0	1	119762478
[info] /updatable	1	1	306961760
```

There are two shared memory blocks allocated - the `/static` block which contains data that doesn't change, and `/updatable` which contains data that changes after a traffic update.

If you generate new traffic files (by *only* running `osrm-customize`), then you can do:

```
$ ./osrm-datastore --only-metric=on colorado-latest.osrm
[info] Data layout has a size of 1052 bytes
[info] Allocating shared memory of 306961760 bytes
[info] All data loaded. Notify all client about new data in:
[info] /updatable	2
[info] Marking old shared memory region 1 for removal...
[info] ok.
[info] Waiting for clients to detach...
[info]  ok.
[info] All clients switched.
```

and it only requires 2x the RAM for the `/updatable` block.

**Comment by TehNrd** [comment]
Got it, very helpful. Thank you.

So for doing real-time traffic updates or other metric updates, you will need at least an extra amount of free RAM equal to the `/updatable` block size.

If you are pulling down new .osrm files generated from a latest .pbf file you will need 2x the sum of `/updatable` and `/static` as the road names, graphs, intersections, etc (everything) are being updated.

It's good to know about the extra memory requirements for traffic and `/updatable`. 

If real-time traffic updates are not needed and you only need periodic updates to the underlying osm data it seems like the most cost-effective solution is to just spin up a new box with the latest data, fill the RAM once, and then kill the old box.
