### ISSUE TITLE
How to prevent sharp turn for rail transport (tram)

### ISSUE THREAD

**Issue by Finardin** [Project-OSRM/osrm-backend#5412]
Hello. 
Need for help.

I found train profiler in the Network and slightly modified it to make it a tram profiler. Source сode is here:
[Tram.txt](https://github.com/Project-OSRM/osrm-backend/files/3016554/Tram.txt)

Almost everything is OK, but i have one problem with turns. Tram (like any other rail transport actually) can't use sharp turns. But when i build a route with this OSRM, i get this turn: 
![image](https://user-images.githubusercontent.com/7420672/55136868-9325de00-5140-11e9-924a-401722b57cbb.png)

Are there some ways to prevent such sharp turns? Should i modify process_turn function in any way? 

Thank you in advance.

**Comment by chaupow** [comment]
Hi @Finardin,

you can use the [`angle` information in process_turn](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md#process_turnprofile-turn) to filter out turns that you cannot take.

To filter out a turn, set the weight to max as shown here:

[`turn.weight = constants.max_turn_weight`](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L488)

**Comment by Finardin** [comment]
> Hi @Finardin,
> 
> you can use the [`angle` information in process_turn](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md#process_turnprofile-turn) to filter out turns that you cannot take.
> 
> To filter out a turn, set the weight to max as shown here:
> 
> [`turn.weight = constants.max_turn_weight`](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L488)

Thank you for answer. 
But still doesn't work. ( 
Even if i use such code: 
`function process_turn(profile, turn)
turn.weight = constants.max_turn_weight             
end`
without any condition, nothing change. ( 
I have feeling the process_turn function in my profiler does not any effect on OSRM's work.

**Comment by chaupow** [comment]
Hi,

Hmmm 🤔 How do you know it doesn't work? By setting `turn.weight = constants.max_turn_weight`, we're not removing the turn from the graph but we're setting the weight very high, hoping that when we do a shortest-path routing request, we will ignore the turn. If you set all turns to a high weight, I am not sure what outcome even to expect.

Can you try checking the debug tiles as described [here](https://github.com/Project-OSRM/osrm-backend/issues/3370#issuecomment-465071932)?

You should be able to see the turn weights at that turn and can verify whether or not your profile is applied correctly.

It should look similar to this (the info in white are the turn weights):
<img width="509" alt="Screenshot 2019-03-29 10 19 55" src="https://user-images.githubusercontent.com/804027/55222463-48719800-520c-11e9-84d6-333155a7ea62.png">

**Comment by Finardin** [comment]
@chaupow 
I'm beginning to understand now. 
Changing "turn.weight" parameter i'm able to make the turn as unprofitable as possible. But there is no way to ignore the turn at all, right?

**Comment by chaupow** [comment]
> Changing "turn.weight" parameter i'm able to make the turn as unprofitable as possible. But there is no way to ignore the turn at all, right?

That is correct if the only thing you can adjust is the profile. You cannot ignore a turn with the profile.

Alternatively, you could map a turn restriction in the OSM data: https://wiki.openstreetmap.org/wiki/Relation:restriction

OSRM considers restricted turns if they are defined in the OSM data and filters them out.
