### ISSUE TITLE
documentation examples don't work 

### ISSUE THREAD

**Issue by ahmedmdl** [Project-OSRM/osrm-backend#5414]
I tried the examples in https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

# Returns a 3x3 duration matrix:
curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219'

all i want is the distances matrix which the documentation clearly states `distances array of arrays that stores the matrix in row-major order` but i never get it 

the rest examples fail because `annotations` is preceded by a `?` and it executes when preceded by a `&`

Am i missing out something

**Comment by danpat** [comment]
The demoserver doesn't support the `annotations=` parameter on the table plugin, it's a bit behind the `master` version.

You'll need to run the `osrm-routed` server yourself if you want to use the `annotations=` option on `/table` requests.
