### ISSUE TITLE
Route with via multiple points

### ISSUE THREAD

**Issue by Anyaoha** [Project-OSRM/osrm-backend#5421]
I had plotted the routes of some locations using this package in R. The maximum number of locations allowed for routing using the OSRM is 100 coordinate points.

Is there a way to calculate and plot the Trip or Route of more than 100 locations. 
Thanks

**Comment by danpat** [comment]
Yes.  If you run your own `osrm-routed` server, you can pass in the `--max-viaroute-size X` size, where you can set X as high as you like.

The OSRM demoserver is limited to 100 coordinates.

**Comment by Anyaoha** [comment]
@danpat could you point me to the direction of how I can get this done.
I would appreciate your help.

**Comment by Anyaoha** [comment]
@danpat could you point me to the direction of how I can get this done. Since I'm using R studio. 
I would appreciate your help.

**Comment by danpat** [comment]
I don't know how the R studio module works.  If it's making requests to the OSRM demo server at `https://router.project-osrm.org/`, then you'll need to learn how to install and build OSRM separately, then run `osrm-routed` with the option I posted above.

**Comment by Anyaoha** [comment]
Thanks :)

**Comment by Anyaoha** [comment]
Thanks @danpat  I got osrm to work using the local host. I can now use the `osrmTable` for more than 100 coordinate points but I have concerns about `osrmTrip` because I still get errors of The OSRM server returned an error: `Error: TooBig Too many trip coordinates` when I try to use in for analysis greater than 100 coordinates.
I need help please.

Running `osrm-routed `server, cannot by-pass  the `osrmTrip` when I use `--max-viaroute-size X `size

**Comment by danpat** [comment]
Try using `--max-trip-size`
