### ISSUE TITLE
Unable to deploy osrm routing engine server

### ISSUE THREAD

**Issue by kkarakk** [Project-OSRM/osrm-backend#5422]
i'm following along with https://hub.docker.com/r/osrm/osrm-backend on windows.   

```
docker run -t -v D:/docker:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/india-latest.osm.pbf
docker run -t -v D:/docker:/data osrm/osrm-backend osrm-partition /data/india-latest.osrm
docker run -t -v D:/docker:/data osrm/osrm-backend osrm-customize /data/india-latest.osrm
```

All run successfully ie they display the maximum amount of ram used which i understand means that the process has completed successfully

The generated files are as 

> 
> Mode                  LastWriteTime               Length        Name
> ----                -------------         ------ ----
> -a----         4/3/2019   4:41 PM      610651399   india-latest.osm.pbf
> -a----         4/4/2019   1:27 PM     1468381696   india-latest.osrm
> -a----         4/4/2019   3:02 PM        9524224   india-latest.osrm.cells
> -a----         4/4/2019   3:08 PM     1279197184 india-latest.osrm.cell_metrics
> -a----         4/4/2019   1:29 PM       86952448 india-latest.osrm.cnbg
> -a----         4/4/2019   3:01 PM       86952448 india-latest.osrm.cnbg_to_ebg
> -a----         4/4/2019   3:07 PM          69632 india-latest.osrm.datasource_names
> -a----         4/4/2019   3:02 PM      517693952 india-latest.osrm.ebg
> -a----         4/4/2019   3:01 PM      127709696 india-latest.osrm.ebg_nodes
> -a----         4/4/2019   1:30 PM      151004672 india-latest.osrm.edges
> -a----         4/4/2019   3:02 PM      127344128 india-latest.osrm.enw
> -a----         4/4/2019   3:01 PM      612777120 india-latest.osrm.fileIndex
> -a----         4/4/2019   1:31 PM      635018240 india-latest.osrm.geometry
> -a----         4/4/2019   1:30 PM      117411840 india-latest.osrm.icd
> -a----         4/4/2019   3:02 PM           5120 india-latest.osrm.maneuver_overrides
> -a----         4/4/2019   3:09 PM      531004928 india-latest.osrm.mldgr
> -a----         4/4/2019   1:27 PM         998912 india-latest.osrm.names
> -a----         4/4/2019   1:29 PM      355362304 india-latest.osrm.nbg_nodes
> -a----         4/4/2019   3:02 PM       84915200 india-latest.osrm.partition
> -a----         4/4/2019   1:27 PM           6144 india-latest.osrm.properties
> -a----         4/4/2019   1:31 PM        2446848 india-latest.osrm.ramIndex
> -a----         4/4/2019   1:30 PM           4096 india-latest.osrm.restrictions
> -a----         4/4/2019   1:25 PM           3584 india-latest.osrm.timestamp
> -a----         4/4/2019   1:30 PM           4096 india-latest.osrm.tld
> -a----         4/4/2019   1:30 PM           6144 india-latest.osrm.tls
> -a----         4/4/2019   1:30 PM       43144192 india-latest.osrm.turn_duration_penalties
> -a----         4/4/2019   1:30 PM      258845696 india-latest.osrm.turn_penalties_index
> -a----         4/4/2019   1:30 PM       43144192 india-latest.osrm.turn_weight_penalties

From my shallow understanding, this might be correct as generated osrm file is larger than the osm.pbf file

however when i 

`docker run -t -i -p 5000:5000 -v D:/docker:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/india-latest.osrm
`
i get the output 

> [info] starting up engines, v5.22.0
> [info] Threads: 4
> [info] IP address: 0.0.0.0
> [info] IP port: 5000
> terminate called after throwing an instance of 'osrm::util::exception'
>   what():  data block /mld/metrics/routability/exclude/3/durations not found include/storage/shared_data_index.hpp:90
> 
 i get the same error if i use the ch algorithm
what could be the reason for this?

**Comment by Raghuvaranpulijala** [comment]
hii @kkarakk iam new to docker and osrm api .unable to connect indian maps to osrm api
docker run -t -v C:\osrm_data:/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/india-latest.osm.pbf
only i file has been generated i.e india-latest.osrm.timestamp 
i even tried by changing the docker memory to 4gb 
![Screenshot (26)](https://github.com/Project-OSRM/osrm-backend/assets/90614505/02ca0735-a603-4d03-a83e-f3e0768c2fb6)
docker run -t -v C:\osrm_data:/data osrm/osrm-backend osrm-partition /data/india-latest.osm.pbf
it shows "/data/india-latest.osrm.ebg not found" in cmd prompt
please help with this

**Comment by kkarakk** [comment]
Never got it working, ended up using a paid solution.
