### ISSUE TITLE
incorrect routing on india map

### ISSUE THREAD

**Issue by vinayrachapalli** [Project-OSRM/osrm-backend#5424]
I tried routing service on India map, it's not showing proper route. Instead it's showing some long lat, which is in Pakistan. Please someone help me.

Even for the Nearest service, it's showing the same lat, long.

![Screenshot from 2019-04-05 11-30-42](https://user-images.githubusercontent.com/16594628/55606734-94d25000-5797-11e9-91c2-38c5fd814cbc.png)

**Comment by vinayrachapalli** [comment]
I should give geo-coordinates in {longitude},{latitude} format, not as {latitude},{longitude}

**Comment by yashtriv13** [comment]
I have the same problem. the routing seems to be a bit messed up with Indian coordinates. I earlier thought it was an issue with my local server, but the same results from the call to the OSRM demo server !

**Comment by danpat** [comment]
@yashtriv13 The original ticket noted that coordinates need to be supplied in `<longitude>,<latitude>` order - if you've got them reversed accidentally, you will see very strange results.

**Comment by yashtriv13** [comment]
Got it! I was mentioning <lat,lng>. I wasn't clear on what rachha meant by his last comment.
