### ISSUE TITLE
Qustion - "Nice route" profile?

### ISSUE THREAD

**Issue by TomQv** [Project-OSRM/osrm-backend#5426]
It is becoming popular to offer a profile for routing which tries to calculate a "nice" route.
Often offered for motorbikes.
They try to take into consideration, how curvy a road is, how much changes in elevation, avoid main roads and crossing villages etc.
I'm wondering if you guys are also busy in these technologies to integrate this into OSRM?

**Comment by systemed** [comment]
In theory that can be done with a Lua profile, though you'll have to preprocess the data to calculate those features that aren't discernible from tags. You might want to investigate Graphhopper which has some of these features built in: https://github.com/graphhopper/graphhopper/pull/534

**Comment by emiltin** [comment]
You might be intested in haivng a look at how we implemented a similar feature for OSRM, based on Postgis queries: https://github.com/ibikecph/osrm-backend/blob/green_v5/profiles/green.lua. It worked by preprocesssing a green score in Postgis, and querrying these via Postgis from processing in OSRM.
