### ISSUE TITLE
Documentation for custom plugins

### ISSUE THREAD

**Issue by datwelk** [Project-OSRM/osrm-backend#5428]
Is there any documentation available on how to add custom plugins to OSRM? I can extract some information for example from [this pending pull request](https://github.com/Project-OSRM/osrm-backend/pull/3652/files) for an isochrome plugin. However I'm not sure how up to date it is, and especially parameter parsing seems hard to figure out. Any pointers would be much appreciated!

**Comment by danpat** [comment]
That PR is probably the best reference - there is no other documentation, and as adding plugins isn't one of the primary things people do with OSRM, I doubt anyone will ever write any docs on this (I know I certainly don't have time to).

**Comment by datwelk** [comment]
Gotcha, thank you @danpat
