### ISSUE TITLE
Route not generate over roundabout

### ISSUE THREAD

**Issue by xmattonix** [Project-OSRM/osrm-backend#5429]
I installed the default OSRM installation (the newest) and when I try to plan a way between two points through a roundabout, the system avoids a particular roundabout. Other roundabouts work. I tried to change the settings in the .lua profile and without result.

How to force the road to cross the roundabout?

If I try to plan a route through the OSRM demo is used a particular roundabout.

Czech republic /route/v1/driving/17.922981977462772,49.91442477286673;17.916222810745243,                                                                                                             49.911654332464146?overview=false&alternatives=true&steps=true;

Info about roundabout:
https://www.openstreetmap.org/way/178430327

My Car.lua (not default) but with default also not working:
 
properties = {
       max_speed_for_map_matching     = 180/3.6, -- 180kmph -> m/s      
       weight_name                     = 'routability',
       process_call_tagless_node      = false,
       u_turn_penalty                 = 20,
       continue_straight_at_waypoint  = false,
       use_turn_restrictions          = false,
       left_hand_driving              = false,
       traffic_light_penalty          = 2  
 },

default_mode              = mode.driving,   
default_speed             = 10,
oneway_handling           = false,
side_road_multiplier      = 0.8,
turn_penalty              = 7.5,
speed_reduction           = 0.8,
turn_bias                 = 1.075,
cardinal_directions       = false, ...

I've tried to set up everything that is possible. Same speed to make the route as short as possible, etc.

Any idea how to do it?

![Roundabout1](https://user-images.githubusercontent.com/48992091/55951868-93ea6400-5c58-11e9-931e-d98d3bf6e406.PNG)

**Comment by danpat** [comment]
@xmattonix That roundabout has `construction=` on it - by default, OSRM won't route over things that are marked as construction.

https://wiki.openstreetmap.org/wiki/Key:construction

You can either update OSM if it's incorrect, or search for the word `construction` in the profiles and disable construction detection.
