### ISSUE TITLE
Mismatching routes returned between local build and map.project-osrm.org

### ISSUE THREAD

**Issue by AshwinTayson** [Project-OSRM/osrm-backend#5432]
I have downloaded india-latest.osm.pbf

And ran

```
osrm-extract -p /opt/car.lua india-latest.osm.pbf
osrm-contract india-latest.osrm
```

but when I run
`
osrm-routed --algorithm mld india-latest.osrm`

it throws the error

> 
> [info] starting up engines, v5.22.0
> [info] Threads: 8
> [info] IP address: 0.0.0.0
> [info] IP port: 5000
> terminate called after throwing an instance of 'osrm::util::exception'
>   what():  Could not find any metrics for MLD in the data. Did you load the right dataset?

but if I run

`osrm-routed india-latest.osrm`

then the server starts fine and give results for my request. But cross verifying with the results from http://map.project-osrm.org the results are not optimised. The local machine always gives results which is atleast 2-3kms farther from the optimised solution in the web.

Why adding the param --algorithm mld throws error and how to solve it? Maybe that will help me yield the same results as the web version of osrm.

After scouring the docs I was supposed to run

osrm-partition india-latest.osrm
osrm-customize berlin-latest.osrm

But now the paths returned even more longer than the paths returned by CH algorithm or the map.project-osrm.org. Updated the issue title.

**Comment by chaupow** [comment]
OSRM can be run with two different algorithms. You can preprocess the data and run it _either_ with Contraction Hierarchies (CH) or Multi-level Dijkstra (MLD). You cannot do both. You have to choose one.

When you run the following commands, you run it with CH:
```
osrm-extract berlin-latest.osm.pbf -p profiles/car.lua
osrm-contract berlin-latest.osrm

osrm-routed berlin-latest.osrm
```


if you want to run it with MLD, you have to use the binaries like this:
```
osrm-extract berlin.osm.pbf
osrm-partition berlin.osrm
osrm-customize berlin.osrm

osrm-routed --algorithm=MLD berlin.osrm 
```


As you can see, you preprocessed the data with CH. if you try to run `routed` with MLD, it fails.


As for the the differences between the webserver and your own version: The demopage runs on a server with own traffic data. That means that the webserver uses different speeds than the default speeds you get with `profile/car.lua`. The traffic data is not public. More Info: https://github.com/Project-OSRM/osrm-backend/issues/4715#issuecomment-348918850

**Comment by AshwinTayson** [comment]
Is it possible to show what are the minor adaptations taken to integrate the traffic data into car.lua? Any pointers or code would be helpful
