### ISSUE TITLE
Usage of exclude=toll may result in "No Route"

### ISSUE THREAD

**Issue by slavanap** [Project-OSRM/osrm-backend#5433]
Hi!

Here's an example:
`https://router.project-osrm.org/route/v1/driving/-74.00549291,40.65649304;-74.014462,40.635196?exclude=toll`

If you remove `?exclude=toll` part, then you'll get a route.
I think it makes sense to include toll roads into a route even if `exclude=toll` is specified, but only the smallest segment.

Is there any other method to get result for this route request with `exclude=toll`? Maybe there's some other parameter I don't know about?

**Comment by danpat** [comment]
This is known behaviour - the `exclude=` flag was implemented as a *strict* exclude, not "avoid".  Leaving this ticket open and flagging as a feature request - not sure anyone has any plans to work on it any time soon though.

**Comment by slavanap** [comment]
Well, I _expect_ to see the waypoint mapped from toll road to another free road and then get results, but I see only "No Route" result. This is my concern. 
For instance, if you load small map to OSRM and try to route from outside the map, you won't get a "No Route" message -- you'll get partial route from the closest point which resides in the map.
So, instead of just assuming these toll roads doesn't exists with `exclude=toll` flag specified, you forbid building routes if any of waypoints reside on a toll road.

**Comment by slavanap** [comment]
@danpat I'm sorry, could you show me a toll road on this route I've specified in the first message?
Because I don't see any: https://www.google.com/maps/dir/40.65649304+-74.00549291/40.635196+-74.014462/@40.6508837,-74.0111568,14.21z/am=t/data=!4m10!4m9!1m3!2m2!1d-74.0054929!2d40.656493!1m3!2m2!1d-74.014462!2d40.635196!3e0

**Comment by slavanap** [comment]
I think, it's a bug.

**Comment by danpat** [comment]
@slavanap The first coordinate has snapped to the hov-only lane on the Govanus Expressway.  While it is not tolled, there is no way off it (at least, as mapped in OSM), until you hit the bridge at https://www.openstreetmap.org/way/622841190 - and when you switch on `exclude=toll`, that bridge is no longer accessible, hence the "no route found".

**Comment by slavanap** [comment]
@danpat why it doesn't return alternative path then for `exclude=toll`? (There's one in this case)
http://map.project-osrm.org/?z=17&center=40.635385%2C-74.016373&loc=40.660287%2C-74.001492&loc=40.634917%2C-74.014187&hl=en&alt=0

**Comment by danpat** [comment]
@slavanap The other direction has the same problem - eventually you'll hit https://www.openstreetmap.org/way/622841169 and there's no way to avoid it.  If you start on this piece of dedicated HOV road, there's no way to get off it without paying a toll - assuming the OSM mapping is correct.

**Comment by slavanap** [comment]
@danpat And that's because GPS coordinates point to another side of the road. Got it.
Thanks!
