### ISSUE TITLE
global processing routes on ec2

### ISSUE THREAD

**Issue by victusfate** [Project-OSRM/osrm-backend#5434]
Wanted to share a recent global routing process using osrm 5.22, and the april global osm pbf, and the default car profile.
I configured an ec2 instance, started with the r5.4x but blew memory, and ended up having to start over and move up to r4.8x.

Peak memory during extraction was ~150-160GB. 

3-4 hours to extract
contraction is still running from earlier this morning but I'll update my findings.

**Comment by victusfate** [comment]
the CH contraction pass took a little over 12 hours and generated 150+ GB of output files

Now when I'm serving that route info with the osrm backend (using the osrm nodejs module and a light http front end) how much memory will I need in practice? Current testing is showing it only using a few hundred MB of ram, but I expected much higher required.

**Comment by carlos-mg89** [comment]
@victusfate I'm a bit curious about how much RAM did you end up using for management of requests.

I intend to set up a production server for my project, so I can handle requests for our users, and it'll by only for Europe. For a combined OSM.PBF that comprises France, Andorra and Spain (4,4GB) that I have processed it's using about 9GB of RAM for processing requests. Although the generated files take about 20GB of space.

**Comment by victusfate** [comment]
I ended up going with 177GB of ram for smooth/fast requests to both matrix and routes

You can run on a smaller instance without memory mapping though and deal with the request slow down

Here's the parameter I swapped in my local config, this was nodejs small http server in front of osrm
```
const bMapMemory = CONFIG.environment === 'production' ? false : true;

const oOSRM = new OSRM({ 
  algorithm: 'CH', // 'CH', 'CoreCH', 'MLD' and must be preprocessed appropriately
  path: sOsrmFile,
  mmap_memory: bMapMemory
})
```

**Comment by victusfate** [comment]
You'll want 20GB +/- to be able to have requests process fast

**Comment by danpat** [comment]
Note that for route calculation, you don't need as much RAM as for pre-processing - roughly the size of the files on disk, or less.  You need a lot more space to run `osrm-extract`/`osrm-contract`, but once that is done, you can move the datafiles to a smaller box and save some money.

A large matrix request (2000x2000) requires about an additional 2GB of temporary working RAM, so if you're doing lots of those concurrently, consider that.  A single simple route request only needs a few hundred kilobytes or a few MB.

**Comment by victusfate** [comment]
also @danpat @carlos-mg89 closing this ticket out as it's been resolved
maybe the readme/docs can grow to handle some of these operational questions over time

**Comment by carlos-mg89** [comment]
Thanks for all the information, it's been certainly useful and it's more or less what I expected based on my readings and tests.

Sure, we can close this ticket :)
