### ISSUE TITLE
Question about Requests API profiles

### ISSUE THREAD

**Issue by TakuHum** [Project-OSRM/osrm-backend#5436]
Hi!

We want to generate routes such as foot and car from a same map.osrm file.

However, in the current OSRM, this profile is not used and it is ignored even if profile is specified. (The response will be the same whether it is driving or walking)
https://github.com/Project-OSRM/osrm-backend/issues/4868

As shown below, it is considered necessary to apply reverse proxy when running multiple profiles on one machine.
https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

Does OSRM project plan to support routing the different types of route with different profiles of API from a same map.osrm file?
If not, why is it a technical issue?

Best regard,

**Comment by danpat** [comment]
@TakuHum There's nothing blocking doing it, but nobody has implemented it yet.  If you have the time to write a pull request that implements the feature in a nice way, I'm sure we can get it merged.

**Comment by TakuHum** [comment]
@danpat 
Certainly.  If so, we consider to impelement the feature.  Thanks.
