### ISSUE TITLE
foot profile: Should accept routing when highway=residential and access=private ?

### ISSUE THREAD

**Issue by Joxit** [Project-OSRM/osrm-backend#5437]
Hi!

I'm using OSRM for foot routing and I'm facing a problem in a residential area with the default foot profile.

The issue is that the pedestrian profile of OSRM does not use OSM ways with tags  `highway=residential` and `access=private` even if this can be walkable.

Here is an request example : /route/v1/foot/3.85095,43.6003;3.85099,43.6002;3.85095,43.5999;3.85059,43.5982
And the private way from OSM : https://www.openstreetmap.org/way/81229700

This issue is only for foot profile, this works fine in car profile.

**Comment by FlorianBruniaux** [comment]
+1 same issue
