### ISSUE TITLE
OSRM distance matrix

### ISSUE THREAD

**Issue by sweenzor** [Project-OSRM/osrm-backend#544]
Heyo!

Is there any equivalent (or plans for one) in OSRM to google's [distance matrix](https://developers.google.com/maps/documentation/distancematrix/)? I end up just doing loads of http requests to emulate this functionality, which isn't terribly efficient.

Description of the functionality:

> The Google Distance Matrix API is a service that provides travel distance and time for a matrix of origins and destinations. The information returned is based on the recommended route between start and end points, as calculated by the Google Maps API, and consists of rows containing duration and distance values for each pair.

**Comment by jornedeblaere** [comment]
@linux-devil I 'm as well interested for a distance table in meters. Did you found a solution jet?

**Comment by kinju** [comment]
This kind of needs is very good for routing planification / optimization. It could be a good idea to not have only the times, but also the distances for some reports or I don't know ;)

**Comment by pglotov** [comment]
So just making sure, no distance in meters so far?

**Comment by alecava58** [comment]
+1 for the distance in meters.

**Comment by zavan** [comment]
+1 for the distance in meters.

**Comment by pgarin** [comment]
+1 for the distance in meters.

**Comment by keesklopt** [comment]
If you are going to implement meters, could you please make it optional ?
As i fear this could have a significant impact on generation times, network size and most important memory usage.

**Comment by cosmin-petrescu** [comment]
+1 for the distance in meters.

**Comment by rCarto** [comment]
+1 for the distance in meters.

**Comment by TheMarex** [comment]
Locked because of the :+1: noise.
