### ISSUE TITLE
osrm_contract exception full planet car profile

### ISSUE THREAD

**Issue by lindowman** [Project-OSRM/osrm-backend#5440]
Hello,
Running osrm-contract on the full planet car profile throws an exception in ContractedEdgeContainer::Merge

platform: Ubuntu Server 18.04 LTS
osrm-backend: v5.22.0  (Commit id: e86d93760) built Debug version from source
profile: car (using without any local changes)
coverage area: full planet (using planet-latest.osm.pbf)

Extraction was successful.
Contraction seemed to be going well. Until, the following...

....(stuff deleted)
[info] Converting contracted graph with 446059263 to edge list (10705422312 bytes)
[info] Getting edges of minimized graph .
 10%
..... (removed the incremental percent updates)
.
 90%
.
 100%
[assert][139931439740864] /osrm-backend/include/contractor/contracted_edge_container.hpp:130
in: void osrm::contractor::ContractedEdgeContainer::Merge(std::vector<osrm::contractor::QueryEdge>): static_cast<int>(edges_size) >= new_edges_size
terminate called without an active exception

Please let me know if any additional info needs to be provided to identify the problem source.
Also, if osrm were to be built without assertions enabled and assuming there are no other errors on retrying the process, would this be unsafe usage of the routing daemon? Unsafe meaning the router throws or loops forever or some such anomalous behaviour.
Thank you

**Comment by danpat** [comment]
Here's the assertion in question - I think there's a bug in here somewhere, likely an overflow:

```
    126         // append new edges
    127         edges.insert(edges.end(), new_edges.begin(), new_end);
    128         auto edges_size = edges.size();
    129         auto new_edges_size = std::distance(new_edges.begin(), new_end);
    130         BOOST_ASSERT(static_cast<int>(edges_size) >= new_edges_size);
    131         flags.resize(edges_size);
    132         std::fill(flags.begin() + edges_size - new_edges_size, flags.end(), flag);
```

I can't see a fault in the merging logic, *but*, the `static_cast<int>(edges_size)` part of the assertion gives me pause - particularly the `static_cast` part.

Almost without exception, OSRM is using `std::uint32_t` or `unsigned` to represent edge/node indexes on internal types.  My suspicion is that the value here is overflowing the `int` type, causing the assertion to fail.

I know this will take a while, but can you try adding changing the `BOOST_ASSERT` to the following two assertions:

```
BOOST_ASSERT(edges_size >= new_edges_size);
BOOST_ASSERT(edges_size < std::numeric_limits<std::uint32_t>::max());
```

I think if these pass, then the code is safe to run.  What I think is happening is that the number of edges is overflowing the `int` type, and it's triggering the assertion, but that assertion with `int` is not correct, it should be the two above instead.

**Comment by lindowman** [comment]
Hello danpat,
Thank you for your suggestion. It worked - the contraction process finished without errors.
This statement: BOOST_ASSERT(edges_size >= new_edges_size);
ran afoul of the compiler setting to catch signed/unsigned comparisons.
I got around it by casting new_edges_size to unsigned int. I used the old/c style cast.
Please close the issue or can I do it myself?
Thank you.

**Comment by lindowman** [comment]
closed: using the workaround described above.
