### ISSUE TITLE
osrm-backend fails to build on macOS with Boost 1.70.0

### ISSUE THREAD

**Issue by fxcoudert** [Project-OSRM/osrm-backend#5441]
osrm-backend fails to build on macOS with Boost 1.70.0, with error message:

```
Undefined symbols for architecture x86_64:
  "boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)", referenced from:
      _main in components.cpp.o
```

We found out as part of the Homebrew testing to update boost to its latest version: https://github.com/Homebrew/homebrew-core/pull/38890

**Comment by DennisOSRM** [comment]
macOS build has been fixed already. Thanks for reporting.

```
% ninja
[17/17] Linking CXX executable osrm-extract
```
