### ISSUE TITLE
traffic data is not used from csv file

### ISSUE THREAD

**Issue by aydar-musin** [Project-OSRM/osrm-backend#5444]
Hello. First of all thank you for the great project!

I have a problem with traffic data importing. Could you please explain me why it does not use speeds from file?

I execute:

```
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/central.osm.pbf --generate-edge-lookup

docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/central.osrm

docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/central.osrm --segment-speed-file /data/traffic.csv

```

The result of ``osrm-customize``  begins with: 

```
[info] Loaded /data/traffic.csv with 2values
[info] In total loaded 1 file(s) with a total of 2 unique values
[info] Used 14079140 speeds from LUA profile or input map
[info] Used 0 speeds from /data/traffic.csv
...
```

As you can see it didn't use speeds from file.
Here is what ``traffic.csv`` contains:
```
272712606,5379459324,5
5379459324,272712606,5
```

I ran ``osrm-routed`` to make sure that traffic data really was not used.

File ``central.osm.pbf`` downloaded from http://download.geofabrik.de/russia/central-fed-district.html

Thank you!

**Comment by danpat** [comment]
@aydar-musin The node pairs must be directly connected.  Because there are potentially multiple paths from A->B, it's required that they be immediate neighbours to avoid ambiguity.

To update everything from 272712606 to 5379459324 in one direction, you need:

```
272712606,986352182,5
986352182,5371369656,5
5371369656,5372941713,5
5372941713,5371369663,5
5371369663,5372941690,5
5372941690,5371369666,5
5371369666,5371369675,5
5371369675,5379459848,5
5379459848,253480204,5
253480204,1707917032,5
1707917032,5379459343,5
5379459343,3640945776,5
3640945776,5379459335,5
5379459335,5379459333,5
5379459333,5379459324,5
```

and also the inverse for the reverse direction (not included here for brevity).

**Comment by aydar-musin** [comment]
Thank you @danpat !

Could you please also share with me how did you get this intermediate nodes or the way how I can find them myself?

**Comment by danpat** [comment]
@aydar-musin I mean, I clicked on the map on www.openstreetmap.org and copy/pasted the IDs for the way.  I did it manually.

There's no open tool that I know of for generating traffic profiles for import into OSRM.  You'll have to build something.

**Comment by salarnz** [comment]
@danpat 
Hi
after this years , do you know any tools for generating traffic profiles for import into OSRM?

thanks
