### ISSUE TITLE
Different results between Table and Route when there are points over disconnected components

### ISSUE THREAD

**Issue by cayetanobv** [Project-OSRM/osrm-backend#5446]
Hi all,

I've detected a different behaviour between Table and Route services when there is at least one point over a disconnected component (using CH). 

PROBLEM: Table (A, B) is correct but Table (A, B, C) is not correct because it does not exist a B->A route. A and B snap both over a disconected component. See results and maps below.

Points (before snapping):
A: -8.210687,52.8604766
B: -8.210546,52.860317
C: -8.21140293,52.86107590

Points over OSM map:
(Diamond red: A, Diamond green: B, Diamond blue: C)
![image](https://user-images.githubusercontent.com/7315379/57241784-1553cd00-7032-11e9-9666-4b28934fb0ff.png)

Components extracted with osrm-components CLI (Red line):
![image](https://user-images.githubusercontent.com/7315379/57241801-200e6200-7032-11e9-8676-9c035c412ec5.png)

Route A->B
```
"routes": [
    {
      "geometry": "{hsaI~sbq@Ze@",
      "legs": [
        {
          "annotation": {
            "duration": [
              4.7
            ]
          },
          "steps": [],
          "distance": 19.7,
          "duration": 4.7,
          "summary": "",
          "weight": 4.7
        }
      ],
      "distance": 19.7,
      "duration": 4.7,
      "weight_name": "routability",
      "weight": 4.7
    }
  ]
```
Route B->A
```
{"message":"No route found between points","code":"NoRoute"}
```

Table (A, B)
```
Durations
  [
    [
      0,
      4.7
    ],
    [
      null,
      0
    ]
  ]
```

Table (A, B, C)
```
Durations:
  [
    [
      0,
      0.1,
      32.9
    ],
    [
      0.1,
      0,
      33
    ],
    [
      29.6,
      29.7,
      0
    ]
  ]
```

Thanks!

**Comment by chaupow** [comment]
Thanks for reporting!

These are probably all related:

- https://github.com/Project-OSRM/osrm-backend/issues/4448
- https://github.com/Project-OSRM/osrm-backend/issues/5266

**Comment by cayetanobv** [comment]
Thanks @chaupow . I think this problem is very similar to reported by @jcoupey in #4448

BTW: I've using OSRM version 5.22.0.
