### ISSUE TITLE
libosrm for Android

### ISSUE THREAD

**Issue by GEOXER123** [Project-OSRM/osrm-backend#5451]
How could I build  libosrm  for Android?  Or what shoud I do to start ?

**Comment by danpat** [comment]
@imhxs I do know that this has been done in the past, but afaik, there is no direct support for it in the main codebase.  Issues you'll likely come across:

  1. Data preparation/execution in 32bit environments is not regularly tested, and a lot of Android machines are 32bit.
  2. Endian-ness/word size consistency between Android CPUs is likely highly varied - it may be difficult to have a single dataset that will work on all Android hosts.  OSRM datafiles are are primarily raw memory dumps, so preparation on different architectures to where the data is used can lead to corruption problems.

If you're not familiar with native code development for Android, I'd suggest you get started with a small project based on the documentation at https://developer.android.com/studio/projects/add-native-code, and build up from there.

**Comment by SDeveloper30** [comment]
Have you been able to complete the task in shape or form?
