### ISSUE TITLE
Segmentation fault - osrm-routed v5.22.0

### ISSUE THREAD

**Issue by yue-dongchen** [Project-OSRM/osrm-backend#5453]
I get this error when I try routing to a particular area of Sydney, Australia using data "australia-latest.osm.pbf". The same issue is also present using data extracted by osmium from planet.osm.pbf.

> [info] MLD customization writing took 0.195497 seconds
[info] Graph writing took 0.464309 seconds
[info] RAM: peak bytes used: 1165901824
[info] starting up engines, v5.22.0
[info] Threads: 4
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.11
[info] Listening on: 0.0.0.0:5000
[info] running and waiting for requests
[info] 10-05-2019 19:54:27 28.1163ms 127.0.0.1 http://localhost:9966/?z=10&center=-33.762595%2C151.686172&loc=-33.765912%2C151.067977&loc=-33.880677%2C151.127930&hl=zh-Hans&alt=0 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36 200 /route/v1/driving/151.067977,-33.765912;151.12793,-33.880677?overview=false&alternatives=true&steps=true&hints=;
[info] 10-05-2019 19:54:30 6.02126ms 127.0.0.1 http://localhost:9966/?z=13&center=-33.851528%2C151.182604&loc=-33.765912%2C151.067977&loc=-33.880677%2C151.127930&hl=zh-Hans&alt=0 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36 200 /route/v1/driving/151.067977,-33.765912;151.18371963500977,-33.87454883447813?overview=full&alternatives=true&steps=false&hints=O34OgIt-DoCyAAAA8wAAAAAAAAAKAAAAI0LGQgjIJ0MAAAAAhN7nQI4AAADzAAAAAAAAAAoAAABCEAAAjx8BCW7G_P1JHQEJ6MX8_QAATwqEz-hp;
Segmentation fault

**Comment by Pynoob6** [comment]
Could it be due to broken data? If so, is there a way of inspecting it?

**Comment by danpat** [comment]
We'll need a bit more info to properly debug.

Can you build OSRM in debug mode, and run it inside a debugger?  To do this, do:

```
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```

This creates a debug build, then run `osrm-routed` via `gdb` with:

```
gdb osrm-routed --args yourfile.osrm
run
```

Then send it one of your queries.  When the segfault occurs, `gdb` will pause the program, and you can type `bt full` to get a stack trace with details about the crash.  If you can paste that here, it may highlight the problem.

**Comment by Pynoob6** [comment]
> [info] 11-05-2019 15:44:27 15.4198ms 127.0.0.1 http://localhost:9966/?z=12&center=-33.859725%2C151.173420&loc=-33.764022%2C151.058235&loc=-33.791417%2C151.057549&hl=zh-Hans&alt=0 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36 200 /route/v1/driving/151.058235,-33.764022;151.05754852294922,-33.79141716310221?overview=false&alternatives=true&steps=true&hints=;
[debug] [req][140737136023296] /route/v1/driving/151.058235,-33.764022;151.20964050292966,-33.891507453683126?overview=false&alternatives=true&steps=true&hints=fS0DgAguA4BIAAAAUAAAAAAAAAAAAAAAw5w1QnVrRUIAAAAAAAAAAEEAAABIAAAAAAAAAAAAAAB3AgAAEfUACfjM_P079wAJSs38_QAAnwpBEGHm;
[assert][140737136023296] /home/higer/Downloads/osrm-backend-5.22.0-customsnapping.3/include/util/query_heap.hpp:304
in: void osrm::util::QueryHeap<NodeID, Key, Weight, Data, IndexStorage>::DecreaseKey(NodeID, Weight) [with NodeID = unsigned int; Key = unsigned int; Weight = int; Data = osrm::engine::MultiLayerDijkstraHeapData; IndexStorage = osrm::util::TwoLevelStorage<unsigned int, int>]: !WasRemoved(node)
terminate called without an active exception

Thread 5 "osrm-routed" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffeaffd700 (LWP 11386)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
