### ISSUE TITLE
Configure car.lua for motorbikes

### ISSUE THREAD

**Issue by ajay2611** [Project-OSRM/osrm-backend#5457]
I want to configure my car.lua file for motorbikes. Moreover, I want to allow bikes to take cycleways and tracks as well. Can somebody guide me on how to configure it?

**Comment by danpat** [comment]
@ajay2611 There is no motorcycle profile in OSRM.  You're going to have to build it yourself.

The basic process would be to copy `car.lua` to `motorbike.lua`, then start making adjustments.  You may want to consider modifying `bicycle.lua` instead if it's already closer to what you want.

Either way, you will need to read and understand the scripts, then have an idea of the OSM tagging for ways you want to consider, then update the Lua scripts to allow the new types, and set the correct properties on them.  This will be a moderate amount of work, particularly if you're not super familiar with those things already.

**Comment by emiltin** [comment]
Of course I don't know your use case, but are you sure you want to guide motorcycles onto cycleways? At least in Denmark that would be illegal and also dangerous.

**Comment by ajay2611** [comment]
@danpat I've read those scripts and have some idea about tags in OSM data. I was assuming that there is some sort of a list in which I can add `cycleways` or any other roads to allow routing through them. Is it possible?
