### ISSUE TITLE
Using external data (elevation, polution, traffic...) in lua profiles 

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#546]
What would be the most elegant way to support the use of various external data when pre-processing data? 

Data types could include:

- Elevation maps: speed would be lower when going uphill
- Statistical traffic data: prefer streets with less traffic
- Pollution data: avoid areas with a lot of pollution
- Green areas: prefer walking/biking in green areas

It might be possible to create a common way to handle all these cases, since it seems they all involve sampling an external data set, and translating it into modified cost/speed of the individual way segments.

- What are the use cases?
- How would the data be imported?
- How would the data be sampled?
- How should the lua interface look like?
- What, if any, changes would be needed to osrm internals?
- What's the best way for people to help out?  
- Should the data be displayed in the route sumamry/instructions? If so, how?

The issue #271 has a discussion on elevation data.

@prozessor13

**Comment by TheMarex** [comment]
Raster support has landed in `develop`.

**Comment by georgbachmann** [comment]
@emiltin I was just reading this issue here and found that your postgis.lua profile is a 404 now ... do you still have it somewhere to have a look at? Looks very promising to find nicer routes f.e. for a hiking trip

**Comment by daniel-j-h** [comment]
@georgbachmann here's the example profile [`postgis.lua`](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/examples/postgis.lua) --- in theory it should still work, not sure if anyone tested it with all the recent changes, though.

**Comment by georgbachmann** [comment]
Thanks... I already found it... looks very promising! nice!
Btw. is the IRC the best place to ask questions? There is no Slack channel, right?

**Comment by daniel-j-h** [comment]
For real-time communication, yes. For everything that needs to persist or could potentially be of interest to more people => tickets.

There's a webchat IRC client: http://webchat.oftc.net
