### ISSUE TITLE
Missing/Broken File X.osrm.datasource_names

### ISSUE THREAD

**Issue by alexandremazars** [Project-OSRM/osrm-backend#5466]
I am currently trying to create a dockerfile which would create a local osrm server. Currently I have this as Dockerfile:
````
FROM osrm/osrm-backend
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /data
RUN  wget http://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf -O /data/ile-de-france-latest.osm.pbf


RUN  /usr/local/bin/osrm-extract -p /opt/car.lua /data/ile-de-france-latest.osm.pbf && \
     /usr/local/bin/osrm-partition /data/ile-de-france-latest.osrm && \
     /usr/local/bin/osrm-customize /data/ile-de-france-latest.osrm


ENTRYPOINT /usr/local/bin/osrm-routed --algorithm mld /data/ile-de-france-latest.osrm
````

When building  I have these warnings : 
![Capture d’écran 2019-05-23 à 12 19 42](https://user-images.githubusercontent.com/36403975/58245451-19cbf580-7d55-11e9-8ff9-4d85f7f703da.png)

And when running I have this issue:
```
Creating network "localenv_default" with the default driver

[warn] Missing/Broken File: /data/ile-de-france-latest.osrm.datasource_names

[error] Required files are missing, cannot continue
```

**Comment by danpat** [comment]
Did you try firing up the container using `/bin/bash` as the entrypoint and confirm that the file is actually there?

**Comment by alexandremazars** [comment]
I fail to understand what you are saying :/

In order to solve my issue, I commented the entrypoint, went in the container with `docker exec -it` and re ran the commands 

```
RUN  /usr/local/bin/osrm-extract -p /opt/car.lua /data/ile-de-france-latest.osm.pbf && \
     /usr/local/bin/osrm-partition /data/ile-de-france-latest.osrm && \
     /usr/local/bin/osrm-customize /data/ile-de-france-latest.osrm

```

I then un commented the Entrypoint line and rebuilt, it did the trick, but I am not sure what was the issue previously.
The files were missing in the container, but rerunning the command lines actually created them as expected

Afterwards even when I deleted the docker image with `docker rmi`, my issue did not come back, so I guess it's a good thing?
