### ISSUE TITLE
how to get nodes of way

### ISSUE THREAD

**Issue by ujwalaz** [Project-OSRM/osrm-backend#5467]

**Comment by ujwalaz** [comment]
i want node id of a way in lua profile. Is there any way to get node id and its location of way?

**Comment by rgugliel** [comment]
Not really related to osrm-backend but you can find all this information if you parse the raw xml data, e.g., you take the _OSM XML gzip'd_ here [https://download.bbbike.org/osm/bbbike/Bremen/](https://download.bbbike.org/osm/bbbike/Bremen/)

**Comment by rdkt** [comment]
You can look into the `imposm` library
