### ISSUE TITLE
osrm profile: weight for distance ?

### ISSUE THREAD

**Issue by thucnc** [Project-OSRM/osrm-backend#5469]
I know that osrm profile can adjust the duration via `weight` setting, but I also want to adjust the `distance` returned by the same weight ? Is it possible ?

A work-around is to use 2 profiles: one with weight=1 and one with customized weight, then get the ratio from 2 results of 2 profiles and apply it for `distance` ?

**Comment by danpat** [comment]
OSRM stores 3 "accumulatable" properties per edge: weight, duration, and distance.

Only the "weight" value is used in the actual routing algorithm.  The other two are simply added up to give the values in the API response.

What this means is that you can have correct durations and distances on edges, but you can vary the types of routes returned - e.g. if you set weight == distance in the Lua profiles, then you get shortest distance routes, if you set weight == duration, you get shortest duration paths (they often end up similar, but not always).

In the `car.lua` script, if you set the `weight_name` to `distance` (https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L23), then you'll get shortest distance routes, but with still-correct route ETAs (well, as good as can be expected based on our speed estimates).

**Comment by thucnc** [comment]
@danpat thanks a lot. But I'm still confused. Maybe my question is not clear enough. 
I want the osrm `route` api with annotation=distance will return a biased/opinionated distance based on my customized osrm profile. The fact is I want to use osrm `route` api replace google map `direction` api, with a bike-friendly profile. However, our drivers somehow feel the distance is not practical (maybe because some roads are hard to drive) so I think adjusting the distance to be `fairer` ?

**Comment by thucnc** [comment]
Hi, I found way to adjust weight value based on https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L23. Thanks
