### ISSUE TITLE
Does OSRM Backend support Multiple Vehicle Routing Problem

### ISSUE THREAD

**Issue by konabharat1** [Project-OSRM/osrm-backend#5474]
Given 100 stops and 10 vehicles, is there an API which gives the optimal routes for 10 vehicles?

**Comment by nilsnolde** [comment]
Look no further:
https://github.com/VROOM-Project/

**Comment by danpat** [comment]
While OSRM has a basic TSP solver in the form of the `trip` plugin, it's not the intent of this project to be an all-encompassing VRP engine.
