### ISSUE TITLE
Nearest service with driving profile returns coordinates alleys that are not accessible to cars

### ISSUE THREAD

**Issue by kux** [Project-OSRM/osrm-backend#5476]
I have recently moved from google's nearest service to osrm's nearest and looked at a sample of coordinates where the two services return different results.

The pattern I noticed is that OSRM considers many dead end narrow alleys, parking area entrances, bus stations and even park alleys when returning the nearest road.

Should these roads be filtered out from the driving profile?

I'll try to provide a few examples I noticed.

```
curl 'http://router.project-osrm.org/nearest/v1/driving/2.40304,48.85586'
... "name":"Impasse Satan","location":[2.403041,48.85586] ...
```
Example above returns a point on a dead end alley where a car wouldn't even be able to turn.
![dead_end_alley](https://user-images.githubusercontent.com/568447/58553081-a62a5c80-821c-11e9-8330-101ae9bddff2.png)

```
curl 'http://router.project-osrm.org/nearest/v1/driving/2.28018,48.86799'
..."name":"Accès Parking Victor Hugo - Pompe","location":[2.280555,48.867716] ...
```
Example above returns a point on a subterranean parking entrance.
![parking_entrance](https://user-images.githubusercontent.com/568447/58553092-b0e4f180-821c-11e9-9e90-42ff0dfa41b1.png)

```
curl 'http://router.project-osrm.org/nearest/v1/driving/2.44677,48.79023'
..."name":"","location":[2.446483,48.789886]...
```
Example above returns a point in an inaccessible private parking lot.
![private_parking](https://user-images.githubusercontent.com/568447/58553114-bcd0b380-821c-11e9-95e9-334e2b84f0e6.png)

**Comment by danpat** [comment]
@kux What behaviour would you prefer here?  OSRM doesn't do anything fancy - it simply measures the distance to nearby drivable geometry and returns the closest ones.

For each case, I suspect the solution is different:

  1. https://www.openstreetmap.org/way/90658337 - maybe this should be tagged with `motor_vehicle=no` as it's not really drivable?
  2. What would you prefer here, and what heuristic would you suggest for selecting the "right" road?  If you supply a point that's nearest to the parking lot entrance, why wouldn't we return that?
  3. https://www.openstreetmap.org/way/144106770 <- looks like it needs `access=private` ?  This won't prevent OSRM from snapping there however.

Overall, what's "nearest" is definitely a matter of opinion.  If you can think of a systematic way to describe how to filter what's nearest, it might be a helpful addition to the API.  But it's a hard problem :-/

**Comment by kux** [comment]
I see that for cases 1 and 3 in the links you provided there is a `highway=service` tag.
Would it make sense for the API to include an optional field that would allow clients to specify a list of tags that can be excluded from the search?

**Comment by danpat** [comment]
@kux when faced with that kind of decision in the past (e.g. the `exclude=` feature), we've decided to abstract the interface a little bit - exposing OSM tags directly would tightly couple the OSRM interface to OSM, and so far that has been avoided (which is good IMO).

I think there are two paths forward here:

  1. You can run your own OSRM server, and you can customize the `lib/way_handlers.lua` `WayHandlers.startpoint` function and set `.is_startpoint` to `false` on roads you don't want snappable.  The `nearest` service should honour this attribute.
  2. Develop a new API parameter that lets you choose at runtime how to do nearest snapping - there are lots of side-effects on this, so I suspect it'll be a tricky PR.

I personally don't have time to work on (2), and that likely means that it won't get to the OSRM demoserver any time soon.  Your best bet is probably to look into doing (1), which will mean running your own OSRM service.

**Comment by kux** [comment]
Fair point on avoiding the coupling of OSRM and OSRM.

I'll most likely go for option no. 1

I'll close the issue.
Thanks a lot for the support!

**Comment by albivivianihpa** [comment]
@kux do you have any update on the solution for option 1? I have ran into the same problem. 

Thank you!
