### ISSUE TITLE
Does traffic jams affects route summary

### ISSUE THREAD

**Issue by LokiTheCreator** [Project-OSRM/osrm-backend#5477]
In different time of day you can get to one point in different time, considering traffic situation. Does it work in osrm? For example if I request route in rush hour and the same route in night, will their summary be different? Will duration of route I requested in rush hour be more than duration of route requested in night hour when there is little traffic on road?

**Comment by systemed** [comment]
You need to supply OSRM with appropriately formatted traffic data. OSRM does not provide this for you. Very few places supply this data openly, but here's a starting point: https://github.com/graphhopper/open-traffic-collection . Getting the supplied data into a format OSRM can use will not be a trivial task.
