### ISSUE TITLE
Is it possible to provide OSRM with different weights based on time of day?

### ISSUE THREAD

**Issue by AnthonyGio** [Project-OSRM/osrm-backend#5479]
For example, if I theoretically had map data reflecting traffic at noon, and a different dataset for 6am, 6pm, etc. Would it be possible to get trip duration and pathing based on the traffic at that time of day?

**Comment by gardster** [comment]
You can use this: https://github.com/Project-OSRM/osrm-backend/wiki/Traffic to redefine edges weight.

**Comment by AnthonyGio** [comment]
@gardster 

Ideally I would, but I can't find any data that provides the edge-weight updates, so I was thinking of just using different datasets for difference time periods as a workaround. Maybe this is a bad idea but I can't think of anything better so far unless I find the traffic update CSV file for the United States.
