### ISSUE TITLE
Problem with routing when one-way road is between two points

### ISSUE THREAD

**Issue by de-profundis** [Project-OSRM/osrm-backend#5482]
Hi,
there is one-way road between two points, it doesn’t route in both directions and NULLs in the matrix appear. OSRM can find a way in only one direction.
These are exemplary coords:

53.498371 18.758002 
53.491872 18.748115

Everything is okay with route and matrix in that direction: 53.491872 18.748115 --> 53.498371 18.758002  
http://map.project-osrm.org/?z=16&center=53.495105%2C18.753126&loc=53.491874%2C18.748120&loc=53.498408%2C18.757960&hl=en&alt=0
but in opposite direction 53.498371 18.758002 --> 53.491872 18.748115 it doesn't find a route and returns NULLs.
http://map.project-osrm.org/?z=16&center=53.494939%2C18.753319&loc=53.498408%2C18.757960&loc=53.491874%2C18.748120&hl=en&alt=0

I checked road network - nodes, road directions, relations are ok, everything is connected. I don't know what it is caused by? Is it a problem with an algorithm or the data? What should I do to make it look for a bit longer path, but with no NULLs?

Have you ever heard about similar problem?

**Comment by kd509** [comment]
Possible same problem here:

**This is correct:**
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=54.9015%2C8.3180%3B54.7792%2C8.8257#map=11/54.8430/8.5783&layers=N

**In opposite direction it is not:**
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=54.7792%2C8.8257%3B54.9015%2C8.3180#map=10/54.9666/8.6160&layers=N



When you switch to graphhopper as routing engine you get a correct result in both cases. So road network seems to be ok.

Regards

**Comment by systemed** [comment]
This appears to be working fine now.
