### ISSUE TITLE
Something wrong with the geojson result.

### ISSUE THREAD

**Issue by hxm841946123** [Project-OSRM/osrm-backend#5483]
http://127.0.0.1:5000/route/v1/driving/40.501599,-74.462539;40.715502,-74.045838?steps=true&geometries=geojson&overview=full

This is the API I use.

{"code":"Ok","routes":[{"geometry":{"coordinates":[[-74.865252,38.942311],[-74.865252,38.942311]],"type":"LineString"},"legs":[{"steps":[{"intersections":[{"out":0,"entry":[true],"bearings":[162],"location":[-74.865252,38.942311]}],"driving_side":"right","geometry":{"coordinates":[[-74.865252,38.942311],[-74.865252,38.942311]],"type":"LineString"},"mode":"driving","duration":0,"maneuver":{"bearing_after":162,"location":[-74.865252,38.942311],"bearing_before":0,"type":"depart"},"weight":0,"distance":0,"name":""},{"intersections":[{"in":0,"entry":[true],"bearings":[342],"location":[-74.865252,38.942311]}],"driving_side":"right","geometry":{"coordinates":[[-74.865252,38.942311],[-74.865252,38.942311]],"type":"LineString"},"mode":"driving","duration":0,"maneuver":{"bearing_after":0,"location":[-74.865252,38.942311],"bearing_before":162,"type":"arrive"},"weight":0,"distance":0,"name":""}],"distance":0,"duration":0,"summary":"","weight":0}],"distance":0,"duration":0,"weight_name":"routability","weight":0}],"waypoints":[{"hint":"-QQCgPsEAoAAAAAAZAAAAAAAAABfBQAAAAAAAE1GQUIAAAAAG90mRAAAAABGAAAAAAAAAMIDAABoAQAAnKWJ-2c2UgJfAWoCtcqP-wAAbxVbwMNy","distance":17526536.370885,"name":"","location":[-74.865252,38.942311]},{"hint":"-QQCgPsEAoAAAAAAZAAAAAAAAABfBQAAAAAAAE1GQUIAAAAAG90mRAAAAABGAAAAAAAAAMIDAABoAQAAnKWJ-2c2UgLuRG0CciaW-wAAbxVbwMNy","distance":17518720.038372,"name":"","location":[-74.865252,38.942311]}]}

This the result I got from the backend. It give me all the same coordinate which is [-74.865252,38.942311]. How to fix it?

**Comment by jcoupey** [comment]
The zero distances and durations usually suggest that the provided locations have been snapped by OSRM to the same node on the road network (typically happens when coordinates are outside the data extract area).

It looks like you've been using lat,lon for coordinates when OSRM expects lon,lat.

**Comment by hxm841946123** [comment]
@jcoupey  Thank you so much!
