### ISSUE TITLE
Walkthrough for building libosrm

### ISSUE THREAD

**Issue by AlexBNelson** [Project-OSRM/osrm-backend#5486]
Would be very useful to have a walkthrough in the wiki for building the example.cpp file and adding libosrm to it.

**Comment by jcoupey** [comment]
You can follow pretty much the same instructions described for [building OSRM](https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM#building). Once `libosrm` is installed on your system, move to the `example` folder containing the `example.cpp` file, then run:

```
mkdir build
cd build
cmake ..
cmake --build .
```

**Comment by AlexBNelson** [comment]
Thanks, that worked for me
