### ISSUE TITLE
Is it possible to deploy osrm-backend to AWS Lambda/GCF (Serverless)

### ISSUE THREAD

**Issue by tambovflow** [Project-OSRM/osrm-backend#5491]
I'm wondering if it's possible to deploy osrm-backend to AWS Lambda or Google Cloud Functions. I can't find any documentation in the repo.

Thank you.

**Comment by danpat** [comment]
Technically yes, I've done it (although not for an open project).  However, the use-cases where it's useful are limited - the big problem is that the running code needs access to the routing datafiles, which can tend to be pretty large.  You can store them on something like S3 and fetch them as the first step of the serverless function, but simply downloading files is going to totally dominate your runtime, and it'll happen every time you invoke the function.  The use-case where I did this only had *tiny* (10s of roads) maps.

**Comment by giacomorebonato** [comment]
Files could be fetched from Elastic File System connected to Lambda.
Curious to know if there are any examples of this, given that AWS Lambda no supports also custom Docker images.

**Comment by danpat** [comment]
Even if you could get it to work, I still think the scenarios where it's useful are limited.  EFS is *slow*, so you'd basically be throwing away all of OSRM's performance advantages.  When you do a routing request, the algorithm performs lots of fairly random seeks across the dataset - if you're using the `mmap` mode (which you'd want to, for fast start), there is still a lot of data touched, and it benefits from fast disk.  The network round-trips of EFS will destroy performance.

As far as custom docker images not being supported:  you can use the NodeJS bindings in a Lambda function - this is what I did.  I remember there being some issues with `libstdc++` versions inside the Lambda environment, but it was a while ago, so I don't know if they still occur.

**Comment by HankieCodes** [comment]
I know this is old, but I just published a Lambda layer that makes it easy to run OSRM within Lambda (specifically NodeJS v22 right now). I’m indeed downloading `.osrm` files from S3 when lambda starts up, and they stay available/warm as long as the function isn’t idle too long. Plus file copy from S3 to Lambda is milliseconds at most.

https://github.com/hnryjms/aws-lambda-layer-osmtools/releases
