### ISSUE TITLE
Ability to batch processing of route or trip services (1 to 1)

### ISSUE THREAD

**Issue by frinux** [Project-OSRM/osrm-backend#5493]
Hello,

I have the need to process a huge amount of routes and/or trips. **Each one is independent**. I Actually call the OSRM API for each route, but it adds overhead.

Table service is able to process multiple routes, but maps each source to each destination, so it computes too much routes (for 3 routes to compute, table will process 3^2 routes, 6 of them are useless to me).

Is it possible to batch process routes/trips?

Thanks

**Comment by danpat** [comment]
No, there's no batch API like this currently.

I have been faced with this situation before.  At that point, I usually start looking at avoiding the HTTP overhead and using either the Javascript or direct C++ interface.  With a CH graph (`osrm-contract`) and a reasonable machine, you can achieve ~50-100 routes/sec per CPU.

I'd take a look in the `examples` directory at the C++ samples - this interface has the least overhead.

If you only need travel times (or distance), a 1:1 table call like this (or its C++ equivalent):

`/table/v1/driving/1,1;2,2&sources=0&destinations=1`

has the least processing overhead.

**Comment by frinux** [comment]
Thanks, very clear answer.
