### ISSUE TITLE
Lack of documentation for the routing with custom dataset

### ISSUE THREAD

**Issue by toton6868** [Project-OSRM/osrm-backend#5494]
I am finding for proper documentation where I can get step by step instruction of building OSRM routing with a custom dataset. Is there any link which I missed?

**Comment by danpaz** [comment]
There are more detailed instructions in the wiki: https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

**Comment by toton6868** [comment]
I mentioned custom dataset that means prepare routing from Custom Road network, not the OSM data. This could be newly digitized shapefile or any other GIS format rather than OSM/PBF. In the link you provided its only deal with osm.pbf data.

**Comment by danpat** [comment]
OSRM only supports loading OSM data - if you have a shapefile or other GIS file, you must first convert it to OSM form.

**Comment by toton6868** [comment]
@danpat , I am failing to do so. I have created a newly digitized custom road network similar to OSM shapefile format with a little bit changes. It has the following columns

<img width="691" alt="Screenshot 2019-07-17 at 10 56 17 AM" src="https://user-images.githubusercontent.com/1884539/61348929-21ef6f80-a884-11e9-91ac-6e1be4726e92.png">

And the **_fclass_** is classified as OSM as well like the following

<img width="346" alt="Screenshot 2019-07-17 at 10 59 59 AM" src="https://user-images.githubusercontent.com/1884539/61349023-75fa5400-a884-11e9-87aa-b72e0099c3e5.png">

The structures are almost similar but I tried to mention the lack of documentation on how to use this shapefile or convert the shapefile to use those class with OSRM. I can take care of LUA profile. If you help me to convert and create a custom routing system then I can create a document on the wiki about the step by step guide how to use custom network datasets with OSRM. As there is a huge user in the GIS world is dealing with shapefile I think this will be very helpful.

**Comment by danpat** [comment]
@toton6868 OSM data is not columnar.

You can read about the OSM formats here: https://wiki.openstreetmap.org/wiki/OSM_file_formats

OSRM is tightly coupled to OSM's data format - a large part of the `osrm-extract` program is dealing specifically with OSM format details.

You might try something like https://github.com/pnorman/ogr2osm - that should take care of the technical file format conversion.  However, you will need to ensure that the Lua script you use matches the tags you apply to edges.  If you've come up with your own tagging scheme, you'll need to spend some time modifying the `car.lua` profile to match your tags.  It's usually easier to try to transform your data into the tags that OSRM expects (based on the OSM docs at https://wiki.openstreetmap.org/wiki/Map_Features).

**Comment by toton6868** [comment]
@danpat According to your suggestion I was successful to convert my shapefile to OSM format data through ogr2osm. For checking the data I have again extracted the osm data to postgis with osm2pgsql and both shapefile and OSM data seems well and overlapping each other nicely. Now I have started the osrm-extract, osrm-contract and osrm-routed process. I got no errors. Finally I tested the routing result through my map service. There I found a lot of nodes missing and the routing is not overlapping the roads.

Here is the scenario
<img width="1680" alt="Screenshot 2019-07-17 at 7 50 09 PM" src="https://user-images.githubusercontent.com/1884539/61381752-59363e80-a8cd-11e9-888f-f16c62265aec.png">
Even you can see the orange line, the alternative route and the blue line, the shortest route, is not overlapping on the same road. I am using car.lua as profile. The part on the image we didn't change anything compared to osm. We actually added few roads in remote areas. I am worried if I am missing any important part of OSRM. 

And very very much thanks for your earlier suggestions.

**Comment by danpat** [comment]
> not overlapping the roads

@toton6868 If you're using road geometry from one source, and using a background map from another (in the above, it looks like OpenStreetmap), then it's pretty normal for the geometry to not align.  If you want perfect alignment of the route geometry and the background map, you'll need to ensure that ... the geometry of the two maps is the same.  Either use OSM as your routing data, or render background map tiles from your road network data.

**Comment by toton6868** [comment]
At that point the osm data and my custom data geometry are same.  Ialso checked with my geometr.  Its lack of nodes.  Is projection related to OSRM? I am using a custom projection system. I am currently changing the projection system and doing the things again. I will let you know. Thanks

**Comment by danpat** [comment]
@toton6868 Which part of the OSRM API response are you rendering on the screen?

If you're using the `overview`, make sure you add `&overview=full&geometries=polyline6` or `&overview=full&geometries=geojson` to your HTTP query - by default, the OSRM route overview geometry is simplified (coordinates dropped) to reduce network bandwidth for long routes.

**Comment by toton6868** [comment]
@danpat `&overview=full` that's the tricky part. Thanks a lot. Closing. Do I add any documentation in the wiki or that will arise more complicacy to users?

**Comment by geocept** [comment]
> @danpat `&overview=full` that's the tricky part. Thanks a lot. Closing. Do I add any documentation in the wiki or that will arise more complicacy to users?

@toton6868: could you please provide some documentation about routing with custom dataset. It looks like you found a great solution and sitting on the some problem at the moment: I want to use own dataset that had been created by gps tracker.
