### ISSUE TITLE
Lua for third party raster data

### ISSUE THREAD

**Issue by siljuovix** [Project-OSRM/osrm-backend#5496]
Hi all, 

I am trying to customise the car.lua profile using elevation data. I am following the [wiki](https://github.com/Project-OSRM/osrm-backend/wiki/Integrating-third-party-raster-data) on the topic. Got an .asc file in which I removed the first six lines and added the source_function and segment_function in the profile that I am calling truck.lua. Nevertheless, in the wiki it states that api version 1 must be used. 

This is what I changed in the lua file, which is just a copy of the car.lua adding the two functions: 

```
-- Truck profile

api_version = 1--version 1 should be kept #3757 osrm/backend 

...

--changes from integrating third party data

properties.force_split_edges = true

function source_function()
  raster_source = sources:load("/Users/user/osrm-backend/profiles/srtm_berlin.asc",
        50 * constants.precision,--tonumber(os.getenv("LON_MIN"))
        55 * constants.precision,--tonumber(os.getenv("LON_MAX"))
        10 * constants.precision,--tonumber(os.getenv("LAT_MIN"))
        15 * constants.precision,--tonumber(os.getenv("LAT_MAX"))
        6000,
        6000
        )
end

function segment_function (segment)
  local out_of_bounds = false
  if segment.source.lon < LON_MIN or segment.source.lon > LON_MAX or
     segment.source.lat < LAT_MIN or segment.source.lat > LAT_MAX or
     segment.target.lon < LON_MIN or segment.target.lon > LON_MAX or
     segment.target.lat < LAT_MIN or segment.target.lat > LAT_MAX then
        out_of_bounds = true
  end

  if out_of_bounds == false then
    local sourceData = sources:interpolate(raster_source, segment.source.lon, segment.source.lat)
    local targetData = sources:interpolate(raster_source, segment.target.lon, segment.target.lat)
    local elev_delta = targetData.datum - sourceData.datum

    local slope = 0
    local penalize = 0

    if distance ~= 0 and targetData.datum > 0 and sourceData.datum > 0 then
      slope = elev_delta / segment.distance
    end
    
    -- these types of heuristics are fairly arbitrary and take some trial and error
    if slope > 0.08 then
        penalize = 0.6
    end

    if slope ~= 0 then
      segment.weight = segment.weight * (1 - penalize)
      -- a very rought estimate of duration of the edge so that the time estimate is more accurate
      segment.duration = segment.duration * (1+slope)
    end
  end
end

-- end of changes from third party

return {
  setup = setup,
  process_way = process_way,
  process_node = process_node,
  process_turn = process_turn,
 
}

```
When I run the extraction 

```sh
./osrm-extract berlin-latest.osm.pbf -p /Users/user/osrm-backend/profiles/truck_berlin.lua
```

I get:

> [info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /Users/user/osrm-backend/profiles/truck_berlin.lua
[info] Input file: berlin-latest.osm.pbf
[info] Profile: truck_berlin.lua
[info] Threads: 8
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2019-07-17T20:15:02Z
[info] Using profile api version 1
[info] [source loader] Loading from /Users/user/osrm-backend/profiles/srtm_berlin.asc  ...
[info] [source loader] ok, after 0.937112s
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 1
[info] [source loader] Loading from /Users/user/osrm-backend/profiles/srtm_berlin.asc  ...
[info] [source loader] ok, after 0.943008s
[info] Using profile api version 1
[info] [source loader] Loading from /Users/user/osrm-backend/profiles/srtm_berlin.asc  ...
[info] [source loader] ok, after 0.950825s
[info] Using profile api version 1
[info] [source loader] Loading from /Users/user/osrm-backend/profiles/srtm_berlin.asc  ...
[info] [source loader] ok, after 0.974545s
[info] Using profile api version 1
[info] [source loader] Loading from /Users/user/osrm-backend/profiles/srtm_berlin.asc  ...
[info] [source loader] ok, after 0.966387s
[info] Using profile api version 1
[info] [source loader] Loading from /Users/user/osrm-backend/profiles/srtm_berlin.asc  ...
[info] [source loader] ok, after 0.945247s
[info] Using profile api version 1
[info] [source loader] Loading from /Users/user/osrm-backend/profiles/srtm_berlin.asc  ...
[info] [source loader] ok, after 0.939925s
[info] Using profile api version 1
[info] [source loader] Loading from /Users/user/osrm-backend/profiles/srtm_berlin.asc  ...
[info] [source loader] ok, after 0.947729s
[info] Parsing finished after 8.37255 seconds
[info] Raw input contains 5324037 nodes, 783034 ways, and 0 relations, 0 restrictions
libc++abi.dylib: terminating with uncaught exception of type osrm::util::exception: There are no edges remaining after parsing.src/extractor/extractor.cpp:645
Abort trap: 6

Using api version 4 runs the extraction regardless of the file name in 
```
    sources:load("/Users/user/osrm-backend/profiles/srtm_berlin.asc",...
```

Does anybody know what version is the one to use in this case and how to use it correctly?

**Comment by siljuovix** [comment]
Simply put : Does api version 4 support the incorporation of raster data?

Thank you in advance.

**Comment by MichalPP** [comment]
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/rasterbot.lua shows usage in api 2, works in api 4 as well
