### ISSUE TITLE
Problem compiling on RaspberryPi 3 ARM

### ISSUE THREAD

**Issue by Kradenko** [Project-OSRM/osrm-backend#5514]
Hi all,

I am trying to compile osrm-backend on Raspberry Pi 3. Waiting for my Raspberry Pi 4 4GB to arrive. I have made a decent swap space in the meantime to offset the limited memory on the Pi 3.

I get to around 98% compiled and then I get the below error which I cannot find any information online about. What am I missing or doing wrong?

```
[  1%] Built target MICROTAR
[ 10%] Built target UTIL
[ 12%] Linking CXX executable osrm-components
CMakeFiles/osrm-components.dir/src/tools/components.cpp.o:components.cpp:function void osrm::extractor::files::readRawNBGraph<boost::iterators::function_output_iterator<osrm::tools::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::util::static_graph_details::SortableEdgeWithData<void>, std::allocator<osrm::util::static_graph_details::SortableEdgeWithData<void> > >&)::{lambda(auto:1)#1}>, osrm::tools::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::util::static_graph_details::SortableEdgeWithData<void>, std::allocator<osrm::util::static_graph_details::SortableEdgeWithData<void> > >&)::{lambda(auto:1)#1}, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0> >(boost::filesystem::path const&, boost::iterators::function_output_iterator<osrm::tools::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::util::static_graph_details::SortableEdgeWithData<void>, std::allocator<osrm::util::static_graph_details::SortableEdgeWithData<void> > >&)::{lambda(auto:1)#1}>, osrm::tools::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::util::static_graph_details::SortableEdgeWithData<void>, std::allocator<osrm::util::static_graph_details::SortableEdgeWithData<void> > >&)::{lambda(auto:1)#1}, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::extractor::NodeBasedEdge, std::allocator<osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&> >&, std::vector<osrm::extractor::NodeBasedEdgeAnnotation, std::allocator<std::vector<osrm::extractor::NodeBasedEdge, std::allocator<osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&> >&> >&): error: undefined reference to '__atomic_compare_exchange_8'
CMakeFiles/osrm-components.dir/src/tools/components.cpp.o:components.cpp:function void osrm::extractor::files::readRawNBGraph<boost::iterators::function_output_iterator<osrm::tools::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::util::static_graph_details::SortableEdgeWithData<void>, std::allocator<osrm::util::static_graph_details::SortableEdgeWithData<void> > >&)::{lambda(auto:1)#1}>, osrm::tools::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::util::static_graph_details::SortableEdgeWithData<void>, std::allocator<osrm::util::static_graph_details::SortableEdgeWithData<void> > >&)::{lambda(auto:1)#1}, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0> >(boost::filesystem::path const&, boost::iterators::function_output_iterator<osrm::tools::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::util::static_graph_details::SortableEdgeWithData<void>, std::allocator<osrm::util::static_graph_details::SortableEdgeWithData<void> > >&)::{lambda(auto:1)#1}>, osrm::tools::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::util::static_graph_details::SortableEdgeWithData<void>, std::allocator<osrm::util::static_graph_details::SortableEdgeWithData<void> > >&)::{lambda(auto:1)#1}, std::vector<osrm::util::Coordinate, std::allocator<osrm::util::Coordinate> >&, osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&, std::vector<osrm::extractor::NodeBasedEdge, std::allocator<osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&> >&, std::vector<osrm::extractor::NodeBasedEdgeAnnotation, std::allocator<std::vector<osrm::extractor::NodeBasedEdge, std::allocator<osrm::util::detail::PackedVector<osrm::Alias<unsigned long long, tag::osm_node_id>, 33u, (osrm::storage::Ownership)0>&> >&> >&): error: undefined reference to '__atomic_compare_exchange_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/osrm-components.dir/build.make:140: osrm-components] Error 1
make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/osrm-components.dir/all] Error 2
```

This is the full compile including the error. I have seen a few other people also trying to compile this without any success.

**Comment by danpat** [comment]
The problem is this error:

`error: undefined reference to '__atomic_compare_exchange_8'`

Looks like the (`std::atomic`)(https://en.cppreference.com/w/cpp/atomic/atomic) functions/types we use in some places either aren't implemented on the rPI (doubtful), or need some extra compiler flags to get working.

I found this ticket: https://github.com/pytorch/pytorch/issues/22898#issuecomment-511692921 which might offer a solution, but I don't have a RPI to test on.  Can you give it a go and let us know if it fixes things?

**Comment by Kradenko** [comment]
> The problem is this error:
> 
> `error: undefined reference to '__atomic_compare_exchange_8'`
> 
> Looks like the [`std::atomic`](https://en.cppreference.com/w/cpp/atomic/atomic) functions/types we use in some places either aren't implemented on the rPI (doubtful), or need some extra compiler flags to get working.
> 
> I found this ticket: [pytorch/pytorch#22898 (comment)](https://github.com/pytorch/pytorch/issues/22898#issuecomment-511692921) which might offer a solution, but I don't have a RPI to test on. Can you give it a go and let us know if it fixes things?

Perfect, will give it a go now and let you know. Thanks!

**Comment by Kradenko** [comment]
Package libatomics-ops-dev doesn't exist on my Raspbian OS. I added the line as stated in the second part of his correction

> Change CMAKE_CXX_FLAGS variable in CMakeLists.txt file (in the main directory). i.e. add line set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -latomic")

This allowed be to complete the build. When I start it now I get an insufficient memory error:

`[info] starting up engines, v5.22.0
[info] Threads: 3
[info] IP address: 192.168.0.16
[info] IP port: 5000
terminate called after throwing an instance of 'osrm::util::exception'
  what():  File "/home/pi/all/all.osrm.fileIndex" mapping failed: failed mapping file: Cannot allocate memory: iostream errorinclude/util/mmap_file.hpp:33
./start_routing.sh: line 1:  1195 Aborted                 osrm-routed -i 192.168.0.16 -t 3 /home/pi/all/all.osrm`

So will just wait for my Pi 4 with 4GB of memory to arrive. Then I can get it all going. Thanks for the assistance!

**Comment by danpat** [comment]
@Kradenko Hmm, that error is also odd - at this part of the code, not much actual memory is being allocated, the `mmap()` call maps a file to a virtual memory block, but doesn't consume any (well, maybe a little bit for bookkeeping) memory.

By default, OSRM needs approximately as much RAM as the size of the datafiles - most of them are loaded directly into RAM, byte for byte.  You can also use the `--mmap` option to `osrm-routed` to not load anything into RAM but `mmap()` everything - useful for low memory environments where performance isn't super-critical.

Couple of things I can think of:

  1. Did you generate the files on the rPI, or on another machine?
  2. Is the Raspbian build you're using 32 or 64 bit?

If you generated the files on a different box, then all bets are off - OSRM datafiles are basically raw memory dumps of the generated data structures, and if you say, generated on an Intel box, then transferred to an ARM machine, I'd suspect it just won't work (and the errors will be weird, as OSRM on ARM may mis-interpret the content of the files, as it makes some assumptions about how it's laid out relative to the CPU you're running the code on).

**Comment by Kradenko** [comment]
Spot on, did it on my Intel machine and transferred the files. I might just try generate the files on the pi and see if it works then. Thanks again! Will report back once it's done.

**Comment by jrcichra** [comment]
https://github.com/pytorch/pytorch/issues/22898#issuecomment-552196831

For me it was libatomic-ops-dev on a raspberry pi 4
