### ISSUE TITLE
[error] Input file not found!

### ISSUE THREAD

**Issue by thomasvuong** [Project-OSRM/osrm-backend#5516]
I have tried everything of similar posts but none work for me.
Setting: macos sierra 10.12.5, docker running, 4GB ram setting, shared /users and other folder in setting (preference)

I tried all different set of commands but nothing work for me
Please check the screenshots of all my tried
<img width="1280" alt="Screen Shot 2019-08-14 at 2 08 41 PM" src="https://user-images.githubusercontent.com/4253875/62998130-1dc36b80-be9d-11e9-82e0-9b93ad9a70eb.png">
<img width="1280" alt="Screen Shot 2019-08-14 at 2 07 57 PM" src="https://user-images.githubusercontent.com/4253875/62998132-1e5c0200-be9d-11e9-9707-2980b9e488cc.png">

**Comment by danpat** [comment]
You're using lower case `pwd`, which is incorrect.  The `${something}` syntax expands an environment variable, and the environment variable for the current working directory is `PWD`, not `pwd`.

Try:

```
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/malaysia-singapore-brunei-latest.osm.pbf
```

**Comment by thomasvuong** [comment]
You are right sir ! I can run that command you showed. Million thanks ! 
But after that I run these
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/malaysia-singapore-brunei-latest.osrm
then:
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/malaysia-singapore-brunei-latest.osrm
then:
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/malaysia-singapore-brunei-latest.osrm

for the last one the output is:
[info] starting up engines, v5.22.0
[info] Threads: 2
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:5000
[info] running and waiting for requests

Then on browser I have tried:
http://127.0.0.1:5000/table/v1/driving/103.849576389,1.27582919242;103.855447156,1.27625146424;103.875891919,1.36156056826;103.800385266,1.30378744394?annotations=duration,distance

or

http://0.0.0.0:5000/route/v1/driving/-0.380407,39.472297;-0.380960,39.472361;-0.380960,39.469595?overview=false&steps=true

or 

http://0.0.0.0:5000/viaroute?loc=39.45,-0.40&loc=39.49,-0.36&compression=false&instructions=true

nothing can work, browser says "This site can't be reached"
<img width="570" alt="Screen Shot 2019-08-14 at 6 01 58 PM" src="https://user-images.githubusercontent.com/4253875/63012915-a4884080-bebd-11e9-958b-5019bee20b97.png">

**Comment by danpat** [comment]
When you run the last command (the `osrm-routed` one), you must tell Docker to expose the TCP port that `osrm-routed` is listening on - it does not by default.

You need `-p 5000:5000` on that last command to expose port 5000.

I will note that all of these details are shown in the steps at https://hub.docker.com/r/osrm/osrm-backend/

**Comment by thomasvuong** [comment]
Yes, I did see it in the instruction but I tried on windows or some different tried in other machine I see some cases I no need to input the port parameter -p
One thing is looking at the output on terminal I can see it indicates that it is listening on port 5000 and IP port is 5000, so it makes me convince that it is running normally. (Attached is the images of 2 commands with and without port parameter and the terminal outputs are the same.)
But you are right, after putting that, I can get output on this link on browser:
http://127.0.0.1:5000/table/v1/driving/103.849576389,1.27582919242;103.855447156,1.27625146424;103.875891919,1.36156056826;103.800385266,1.30378744394?annotations=duration,distance
<img width="574" alt="Screen Shot 2019-08-15 at 9 53 13 AM" src="https://user-images.githubusercontent.com/4253875/63067646-8add0c80-bf42-11e9-8da9-af56ff6df004.png">
Thank you, I will close this thread here ! Hope this helps others in the future too :)

**Comment by danpat** [comment]
@thomasvuong OSRM is running normally in both cases, *inside* a Docker container.

However by default, Docker containers have no inbound network access.  It's worth reading https://docs.docker.com/network/ to understand how networking works in a Docker environment.
