### ISSUE TITLE
table annotations not valid

### ISSUE THREAD

**Issue by ecotner** [Project-OSRM/osrm-backend#5517]
I'm trying to use the service to get a distance matrix between some points, and when testing out the request with the demo server, I am getting an "Unrecognized parameter 'annotations'" error. I am running this URL (which is copied verbatim from the documentation): `http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance,duration`. When I remove the `?annotations=distance,duration` piece everything works fine, but it only returns a duration matrix (and I need distance).

**Comment by akashihi** [comment]
Probably some old version is installed on `http://router.project-osrm.org`, but with latest master it works perfectly

**Comment by brunogonzal** [comment]
I just tried the same Url and i'm getting the same error. Any ideas on what to do?

**Comment by ecotner** [comment]
@brunogonzal, I think it is as @akashihi says - the version on the demo server is kind of old, and distance is not provided yet. I think you will have to install your own version from source if you want to get distance matrices. That is what I did and it works properly after that.
