### ISSUE TITLE
all routes return distance 0?

### ISSUE THREAD

**Issue by lieuzhenghong** [Project-OSRM/osrm-backend#5519]
I ran the following commands to set up OSRM backend:

```
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/alabama-latest.osm.pbf
[info] To prepare the data for routing, run: ./osrm-contract "/data/alabama-latest.osrm"
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-contract /data/alabama-latest.osrm
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/alabama-latest.osrm
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/alabama-latest.osrm
```

Everything seems to work well, and I can start the server with the following:

```
sudo docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/alabama-latest.osrm
```

But querying seems to give me a nonsensical response:
`curl 'http://127.0.0.1:5000/route/v1/driving/30.486889,-87.892470;31.2267,-87.81193'`

```json
{"code":"Ok","routes":[{"geometry":"yx}{Dly{eO??","legs":[{"steps":[],"distance":0,"duration":0,"summary":"","weight":0}],"distance":0,"duration":0,"weight_name":"routability","weight":0}],"waypoints":[{"hint":"57sFgPC7BYBXAAAAAAAAALoLAAAAAAAAPRIFQwAAAACsBY9FAAAAAFcAAAAAAAAAugsAAAAAAACvAAAAfL_u-iNo2AFpMdEBCt7C-gkAXwuxefG9","distance":17361788.937753,"name":"Timberlane Road","location":[-85.016708,30.959651]},{"hint":"57sFgPC7BYBXAAAAAAAAALoLAAAAAAAAPRIFQwAAAACsBY9FAAAAAFcAAAAAAAAAugsAAAAAAACvAAAAfL_u-iNo2AFMe9wBphjE-gkAXwuxefG9","distance":17405753.746003,"name":"Timberlane Road","location":[-85.016708,30.959651]}]}((base)
```

On Google Maps this is [perfectly fine](https://www.google.com/maps/dir/'30.486889,-87.892470'/'31.22697,-87.811913'/@30.7304642,-88.0258301,10z/data=!4m10!4m9!1m3!2m2!1d-87.89247!2d30.486889!1m3!2m2!1d-87.811913!2d31.22697!3e0) and gives me the response I expect.

Have I done something wrong in the setup? I tried following the instructions as best I can.

**Comment by danpat** [comment]
OSRM uses longitude,latitude coordinate order in URLs.  This puts 30.486889,-87.892470 somewhere in Antarctica.

Swap your coordinate pairs around and you should get more sensible results.

**Comment by lieuzhenghong** [comment]
D'oh --- I feel like an idiot now. That fixed it, thank you!
