### ISSUE TITLE
What is excludable classes ?

### ISSUE THREAD

**Issue by augusto3691** [Project-OSRM/osrm-backend#5522]
I have a group of nodes in JOSM and i trying to tag then to be excludable class in profiles of OSRM i tagged then like this:

https://i.stack.imgur.com/juH96.png

and my excludable part of OSRM profile is like that:

classes = Sequence {
    'toll', 'motorway', 'ferry', 'restricted', 'tunnel','secondary','tertiary'
},

-- classes to support for exclude flags
excludable = Sequence {
    Set {'toll'},
    Set {'motorway'},
    Set {'ferry'},
      Set {'secondary'},
      Set {'tertiary'}
},

but when i send the exclude in HTTP request (for example "&exclude=secondary") is still passing through secondary tagged roads, what i'm doing wrong?

**Comment by SiarheiFedartsou** [comment]
Stale.
