### ISSUE TITLE
OSRM Production Ready Setup

### ISSUE THREAD

**Issue by rajat23495** [Project-OSRM/osrm-backend#5524]
Hi, 
I am planning to host OSRM for production ready env.
Which is the preferred way? osrm-routed or node-osrm.
Docker environment or something else
@daniel-j-h  @danpat

**Comment by daniel-j-h** [comment]
Please do not cc folks if you have generic questions. For production ready set up you will find old issues talking about this thoroughly with different solutions and their pros and cons.

If you don't want to investigate time and effort on your own here maybe a better solution is to use a hosted routing service and pay for their support.
