### ISSUE TITLE
Is OSRM with MLD deterministic?

### ISSUE THREAD

**Issue by stastnypremysl** [Project-OSRM/osrm-backend#5526]
Let's have points A and B. 

I would like to compute path from A to B without geometric details and later, if needed, compute them. Is it possible please?

If OSRM is deterministic, it is easy to implement. Is it please?

**Comment by gardster** [comment]
You can use the `table` plugin to calculate only distance/duration. And then calculate route with geometry and guidance by the `route` plugin

**Comment by chaupow** [comment]
@stastnypremysl it should be deterministic so you can do what you're attempting to do.

In the past I've noticed a couple of snapping differences when setting different `overview` params (I guess due to rounding errors) but those are 0.0001% of cases.
