### ISSUE TITLE
Merge Files

### ISSUE THREAD

**Issue by pat841** [Project-OSRM/osrm-backend#553]
I dont have enough RAM to extract the northeast.pbf. I was wondering if I can merge states such as MA and CT into one file?

Or is there an alternative for extracting with about 8 GB RAM

**Comment by aop** [comment]
For future reference for anyone ending up here through Google the magic spell is
`osmosis --rb finland-latest.osm.pbf --rb sweden-latest.osm.pbf --m --wb merged.osm.pbf`
