### ISSUE TITLE
Is there an easier way to run hundreds different profile(the differences lie at height and weight) on one machine?

### ISSUE THREAD

**Issue by hxm841946123** [Project-OSRM/osrm-backend#5530]
I'm doing a school project which is designing a truck navigator. There are 25 different heights and 25 different weights of the truck. So there are 625 combinations of the height and weight, so I have to compile 625 different profiles. I know I can use nginx.conf to run multiple profiles on one machine. But I just wondering if there is an easier way to do so?

**Comment by danpat** [comment]
No, this is one of OSRM's major drawbacks - the shape of the routing graph is specific to the profile, and much is pre-calculated.

For things like truck routing, where there are a large number of possible filters, it's not super practical to pre-calculate all the variations of the graph.  You either need a specialized, metric-independent speedup system, or just something like A* and calculate edge admissibility/weight at query time based on parameters.

You might want to take a look at the Valhalla routing engine https://github.com/valhalla - it has a truck profile that lets you adjust these kinds of parameters on a per-request basis.  The downside is some query performance, but that's not always a problem if your request volumes are not absurdly high.

**Comment by hxm841946123** [comment]
Thank you so much.
