### ISSUE TITLE
Cannot start OSRM - Checksum error

### ISSUE THREAD

**Issue by elgoots** [Project-OSRM/osrm-backend#5531]
Hi Everyone,

I am having an issue where I am trying to start OSRM and its giving me a checksum error.

I am running centos 7x and the command I am using to start is: `osrm-routed --algorithm=MLD /usr/local/share/osrm/profiles/australia-latest.osrm`

It fails to start. The full term info is below:

```
[root@server1 ~]# osrm-routed --algorithm=MLD /usr/local/share/osrm/profiles/australia-latest.osrm
[info] starting up engines, v5.22.0
[info] Threads: 24
[info] IP address: 0.0.0.0
[info] IP port: 5000
terminate called after throwing an instance of 'osrm::util::exception'
  what():  Connectivity checksum 933351272 in /usr/local/share/osrm/profiles/australia-latest.osrm.hsgr does not equal to checksum 2376735897 in /usr/local/share/osrm/profiles/australia-latest.osrm.edges
Aborted

```

any insight would be greatly appreciated.

**Comment by gardster** [comment]
recalculate data files with your osrm binary

**Comment by elgoots** [comment]
Thanks for taking the time to reply. 

I think I have done that already, however just to be sure. Are you able to let me know how to do that via centos
