### ISSUE TITLE
Windows binaries request

### ISSUE THREAD

**Issue by JasperRev** [Project-OSRM/osrm-backend#5532]
I am in a situation where our servers are using windows, unfortunately.  What i really need is to be able to generate the latest binaries for windows, something that supports http keep-alive.  

I attempted to follow the steps and all the old software requirements like vs2015, etc.  With a few tweaks to some of the batch files, which didn't like cmake, i was able to build.  However, upon executing osrm backend, a null reference was created.  

I attempted nodejs, but the build-from-source gave me tons of errors.

The last set of prebuilt binaries was feb 2018.  i get that windows isn't your primary target.  What is the best way for me to proceed on windows with allowing me to use either node or osrm backend with keep alive support?  We are getting thousands of connections.  Perhaps there is an alternative to keep alive, but this is what i'm at.  Help appreciated!

**Comment by danpat** [comment]
Unfortunately, not many people that work on OSRM use Windows as their primary platform.  We see lots of *users* who want it, but, well, it's open source, and if devs don't want to use Windows, it's going to suffer some bitrot.

Have you tried running OSRM inside a Linux Docker container on Windows, or using [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) ?

**Comment by JasperRev** [comment]
Those are nice suggestions but not practical for my immediate situation.  Long term i'd like Linux all the way, but sadly i can not at this time.  I understand the dilemma.  But it would sure be nice maybe once every 3 months to refresh the windows binaries.  I can use the table service to assist me, but i really mostly need keep alive.

**Comment by chansbest** [comment]
docker works like charm using linux containers. that's best way moving on windows.
