### ISSUE TITLE
url incorrect but live demo ok?

### ISSUE THREAD

**Issue by elgoots** [Project-OSRM/osrm-backend#5534]
i just setup and installed osrm-backend and got the australian region downloaded and setup. its running on the server. however its giving me a invalidurl message in browser. not sure what i have missed as from what i can see i am calling it correctly?

example:
mapapi/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true]

**Comment by gardster** [comment]
it seems that you have mistakes when on url rewriting rule when you cutting `mapapi`. What url logs osrm-routed server?

**Comment by elgoots** [comment]
Hi Gardster.

Thank you. You were right, it was my apache proxy. I have changed it and now got it returning accurately except for it is now giving no data back. 

must be something wrong with my mapping data?

https://www.zibeno.com/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false


mapping data i downloaded: http://download.geofabrik.de/australia-oceania-latest.osm.pbf

I have tried running it straight off that such as:  `osrm-routed --algorithm=MLD ~/osrm-backend/profiles/australia-latest.osm.pbf`

i have also tried doing:

osrm-extract australia-latest.osm.pbf
osrm-partition australia-latest.osrm
osrm-customize australia-latest.osrm
osrm-routed --algorithm=MLD ~/osrm-backend/profiles/australia-latest.osrm

again, same result  :/

obviously im stupid and cannot follow instructions? I cant work out what I have done wrong.

**Comment by gardster** [comment]
You request coordinates in Berlin but have map of Australia.

**Comment by elgoots** [comment]
sorry, wrong link. here for example ( these should be australia)

https://www.zibeno.com/route/v1/driving/152.725408,-27.480898;152.725408,-27.480898?overview=false

**Comment by gardster** [comment]
And where is the problem? You ask the same point - you got the response
from one point with distance 0.

пн, 2 сент. 2019 г. в 15:14, elgoots <notifications@github.com>:
