### ISSUE TITLE
Different results from osrm-backed and public OSRM server with latest data

### ISSUE THREAD

**Issue by bobbymaher** [Project-OSRM/osrm-backend#5538]
I have having different results from osrm-backed and the public OSRM server.
I am using latest data from geofabrik, and I have also tried using and export direct from openstreetmap.org. This issue was also happening with a data snapshot that was a few months old.

**Steps to reproduce:**
download this small dataset - takes only a minute or two to get fully running

```
mkdir temp-osrm
cd temp-osrm
wget http://download.geofabrik.de/europe/great-britain/england/greater-manchester-latest.osm.pbf -O map.osm.pbf
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/map.osm.pbf
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/map.osrm
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/map.osrm
docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/map.osrm

```

then visit this page:
https://jsfiddle.net/bobbymhr/cjv5zq3p/5/

on the top left of the map is a dropdown bar that will load the local docker or public OSRM server for a route.

It should load the dropdown for the local docker, then if you switch to OSRM public servers, it gives a better route. 
sometimes the public server returns a 429 error so wait a while and click reload and it should work.

I see on https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server it mentions :
"The dataset is a slightly modified car.lua"

Is there any possibility we can see the modified car.lua to see if this will help? Or there any other suggestions?

**Comment by systemed** [comment]
https://github.com/Project-OSRM/osrm-backend/wiki/Frequently-Asked-Questions

"The demo server uses Mapbox traffic data to influence routing. Your server does not. This data is not freely available."

**Comment by bobbymaher** [comment]
I was aware about the traffic data, but the routes looks so much different i had to discount that. the demo server is using a much shorter route, while the open source backend is going a very long way around. maybe the demo server is using a different source for the routing data

**Comment by bobbymaher** [comment]
ok i think it may be down to  
 left_hand_driving   = false in car.lua

will look into it more and report back if it fixes the problem

**Comment by bobbymaher** [comment]
I have tried doing many modifications to the car script, but nothing is working, I have got the route successfully working with graphopper

It appears the public version of OSRM is having issues with a certain junction https://imgur.com/a/U1rTVfO

**Comment by bobbymaher** [comment]
Solved!

in car.lua

`    avoid = Set {
      'area',
      -- 'toll',    -- uncomment this to avoid tolls
      'reversible',
      'impassable',
      'hov_lanes',
      'steps',
      'construction',
      'proposed'
    },`


remove "construction" - this was a recently built road, demo OSRM bust be doing the same
