### ISSUE TITLE
Routing/table service fails if source and destination too far away

### ISSUE THREAD

**Issue by ecotner** [Project-OSRM/osrm-backend#5540]
I'm trying to measure distances between two points (and eventually use the table service to get distances between multiple points), but am having some trouble. I installed the docker image and downloaded maps for North America (https://download.geofabrik.de/north-america-latest.osm.pbf) just fine, but when I run route queries against the server, they inexplicably fail if the source and destination are too far away. For example, when I run
`http://localhost:9091/route/v1/car/-74.013248,40.707336;-73.972573,40.754954` (short trip from the bottom to the middle of Manhattan), everything works fine, and I get a response like
```
{"code":"Ok","routes":[{"geometry":"{smwFxuvbMu\\oRrCiI}BqSlEyHbB~@gAmBfGyIqByA`JcJuFw`@oP~@]_LwGl@c@kMqr@sWaErLyNkJiK~[iLgBbAgD_N}IbKy[ycC_`BaDw@{Rzm@}ByAzDyL","legs":[{"steps":[],"distance":10084.3,"duration":1329.6,"summary":"","weight":1329.6}],"distance":10084.3,"duration":1329.6,"weight_name":"routability","weight":1329.6}],"waypoints":[{"hint":"dafAhP___38aAAAANQAAABoAAAAiAAAA9PW7QfrvwUFHeLlB9HH0QRoAAAA1AAAAGgAAACIAAAAzRAAAv6WW-wglbQLApZb7CCVtAgIArwHa5MRx","distance":0.084486,"name":"Trinity Place","location":[-74.013249,40.707336]},{"hint":"9REagP___39gAAAAaAAAAAAAAAB4AAAArzmFQlJVrkAAAAAA8dGnQmAAAABoAAAAAAAAAHgAAAAzRAAAn0SX-wTfbQKjRJf7Ct9tAgAAbwfa5MRx","distance":0.746976,"name":"East 48th Street","location":[-73.972577,40.754948]}]}
```
When making the same request against the demo server
`http://router.project-osrm.org/route/v1/car/-74.013248,40.707336;-73.972573,40.754954`, I also get a similar response.

However, if I try and find a route not much further away, for example
`http://localhost:9091/route/v1/car/-74.013248,40.707336;-73.938496,40.821413`
(bottom to the top of Manhattan), it fails and I get
`{"message":"No route found between points","code":"NoRoute"}`, whereas making the same request against the demo server
`http://router.project-osrm.org/route/v1/car/-74.013248,40.707336;-73.938496,40.821413`
gives me a response like
```
{"routes":[{"geometry":"{smwFxuvbMUcGnYrNdDuCuBuLdItBgm@gwAiLmnBaHeN}xAoc@aN[_NxKeZ`Fom@yQmcEusDkr@|C{OkXmc@yXsUcb@cVuDyVdEmXa`@{[xg@_q@wEm@xVsJ~Z","legs":[{"summary":"","weight":2140.2,"duration":1871.9,"steps":[],"distance":19156.7}],"weight_name":"routability","weight":2140.2,"duration":1871.9,"distance":19156.7}],"waypoints":[{"hint":"zFeug____39MAAAAkwAAAEwAAABeAAAA9PW7QfrvwUFHeLlB9HH0QUwAAABKAAAATAAAADAAAABCQAAAv6WW-wglbQLApZb7CCVtAgIArwFqcw83","distance":0.08448616484082538,"name":"Trinity Place","location":[-74.013249,40.707336]},{"hint":"jCwCgCWtroPoAQAAFAAAAAAAAAAAAAAAAF9ZQ0UN4EAAAAAAAAAAAOgBAAAUAAAAAAAAAAAAAABCQAAAtMmX-5XibgLAyZf7peJuAgAArxJqcw83","distance":2.0449274510090882,"name":"West 145th Street","location":[-73.938508,40.821397]}],"code":"Ok"}
```

I've also tried this in multiple other locations in North Carolina, Nebraska, etc, and it seems to have the same behavior - once the distance between source/destination passes some threshold, the requests fail. Same thing when using the table service - I get a bunch of null entries when the locations are too far away. Any idea what is going on here?

**Comment by ecotner** [comment]
Just to provide some more context - these are the series of commands that I ran to get the server up and running using the docker image:
```
wget https://download.geofabrik.de/north-america-latest.osm.pbf
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/north-america-latest.osm.pbf
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/north-america-latest.osrm
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/north-america-latest.osrm
sudo docker run -t -i -p 9091:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/north-america-latest.osrm
```

**Comment by ecotner** [comment]
Is there some kind of configuration file that sets maximum route distance for which the service will operate?

**Comment by danpat** [comment]
@ecotner there's no limit like this in OSRM.  Typically in other systems it's implemented for performance reasons - a long-distance request can take a lot of memory/computation time. OSRM's specialized graph structures mean it can calculate routes from Paris to Singapore in milliseconds, with low memory usage, so we've never implemented a distance limit like this in the code.

The `NoRoute` scenario should only occur when you place coordinates on two disconnected parts of the road network, and even then, only if those parts are fairly large (dropping a coordinate on a small isolated parking lot will trigger some special logic that moves coordinates to common connected networks).

Something else is going wrong here, but it's not obvious to me based on the details you've provided.  Have you modified the `car.lua` profile in any way?

**Comment by ecotner** [comment]
Hi @danpat, sorry for the delay in answering. I eventually got it to work by using contraction hierarchies rather than MLD. Not sure why that fixed it, but there doesn't seem to be any issue now. I did not modify anything; just ran the commands as listed in the quick start, in order.
