### ISSUE TITLE
Update `Table service` documentation

### ISSUE THREAD

**Issue by vasyl-zhurba** [Project-OSRM/osrm-backend#5541]
Hi,

Could you please update `Table service` HTTP documentation and include `annotations` query parameter to allow readers know that it is possible to use it to get different type of data, such as distances.

`?annotations=duration,distance`

Relates to #1353

**Comment by wangyoucao577** [comment]
I think it's already here: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#table-service

**Comment by vasyl-zhurba** [comment]
Thank you!

**Comment by appmo92** [comment]
This doesn't work. If you add the ?annotations=distance you will get the error message "Unrecognized parameter 'annotations'"

**Comment by vasyl-zhurba** [comment]
This [link](http://router.project-osrm.org/route/v1/driving/17.973056,59.354483;18.071802,59.336085?annotations=distance) works for me

**Comment by appmo92** [comment]
But if you try <a href="http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance">this</a> you will get the error message. When you look in the documantation of OSMR,  it should work.....

**Comment by vasyl-zhurba** [comment]
Interesting, indeed. I have tried these settings on my local OSRM and it worked. I have tried all cases for `annotations` parameter (`distance`, `duration`, `distance,duration`, `duration,distance`). All worked well. Probably there is a problem on demo server?

**Comment by danpat** [comment]
Yes - the demo server implementation is lagging behind `master`.  The documentation is correct for the current code.

**Comment by appmo92** [comment]
Will be there an update for the demo server?
