### ISSUE TITLE
Does not route California 1

### ISSUE THREAD

**Issue by mario947** [Project-OSRM/osrm-backend#5544]
Hi, 
We have local osrm-backend running for a while already and recently discovered strange issue: it does not route thru few parts of California 1.
Demo servers works fine though: 
https://router.project-osrm.org/route/v1/driving/-121.873685,36.298839;-121.764361,36.228385.json?alternatives=true&overview=simplified

Save query returns very long route on our server:
![Screenshot from 2019-09-08 15:37:15](https://user-images.githubusercontent.com/12518323/64488347-79400980-d24f-11e9-9c6f-6f7a7a557e6d.png)

vs DEMO:
http://map.project-osrm.org/?z=13&center=36.261300%2C-121.770658&loc=36.295689%2C-121.867733&loc=36.228296%2C-121.764398&hl=en&alt=0

How can I check if 2 years old OSM data we imported has holes in there?

Thanks

**Comment by systemed** [comment]
> 2 years old OSM data

This is probably your issue: https://www.nbcnews.com/news/weather/video/landslide-buries-stretch-of-famous-hwy-1-at-california-s-big-sur-952679491985

**Comment by mario947** [comment]
Yes, you are right. 

I've setup docker OSRM-frontend and pointed it to our backend instance and see Big Sur is closed.
Also I've checked on latest data and it works fine.

Thanks for advice
