### ISSUE TITLE
Table and route results different

### ISSUE THREAD

**Issue by JasperRev** [Project-OSRM/osrm-backend#5552]
I am receiving slightly different results from a table calc vs a route calc.  I don't care about 40 some odd meters of difference, i just want to know if the 2 calcs are in fact different, for a route vs a table.  It is also possible I'm doing something wrong or missing an argument, but i noticed this when validating a larger set, so i narrowd it down to 2 points for an example.  The times appear to match, the distances are slightly off.

Currently using the latest osrm-backend:latest docker image against north america.

/table/v1/driving/-71.818160900000000,41.321416200000000;-72.101717100000000,41.347645800000000?sources=0&annotations=distance,duration

  "durations": [
        [
            0,
            2104.8
        ],
        [
            1984,
            0
        ]
    ],
    "distances": [
        [
            0,
            35929.7
        ],
        [
            33736.7,
            0
        ]
    ]
}

/route/v1/driving/-71.818160900000000,41.321416200000000;-72.101717100000000,41.347645800000000
 "distance": 35887,
            "duration": 2104.8,

**Comment by danpat** [comment]
For historical reasons, there are a few different copies of distance calculation math inside OSRM - I'm pretty sure what you're seeing here is some divergence in precision between the method used by the `table` plugin and the method used by the `viaroute` plugin.

This issue summarizes the core problem: https://github.com/Project-OSRM/osrm-backend/issues/5316

Alas, I no longer have the bandwidth to do significant work on OSRM, so the pull request to fix this will need to come from the community.

**Comment by JasperRev** [comment]
No worries, that makes sense.  Thank you.
