### ISSUE TITLE
Bicycle and oneway, routing wrong

### ISSUE THREAD

**Issue by AllroadsNL** [Project-OSRM/osrm-backend#5557]
[Location routing.](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.93771%2C4.46357%3B51.93683%2C4.46091#map=19/51.93709/4.46224)

At the red circle, de bicycle route against a oneway=yes, this is wrong.

![oneway](https://user-images.githubusercontent.com/8817345/65052350-af297000-d96a-11e9-8120-d8e46bd7ea41.JPG)

On this road, there is a bicycle=use_sidepath tagged, because of a nearby cycleway and no traffic_sign for bicycle on the road. By law rule, bicycle must use the cycleway, there are exceptions. 

My question.
Is oneway routing wrong?

Or the use of bicycle=use_sidepath, then oneway=yes is ignored? ( This is wrong too. )

In the Netherlands, bicycle wider then 75 centimeter can use the roads with use_sidepath, other should use the sidepath (cycleway).

Although the route start at a road with use_sidepath, the oneway=yes should not be ignored.

Edit: I did search and read other related issue.
There was changed a lot over the years in the code.
Because this is a basic issue, I made a new issue.

**Comment by jdhoek** [comment]
OSRM seems to be ignoring **bicycle=use_sidepath**, routing cyclists over dangerous thoroughfares.

[Example](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=53.19747%2C5.81751%3B53.19646%2C5.81750#map=19/53.19687/5.81746):

![Screenshot from 2019-11-27 12-50-49](https://user-images.githubusercontent.com/683699/69721184-98468d00-1114-11ea-9e55-57a3c4fa766e.png)

The **highway=secondary** road is tagged with:

| tag | value |
| -- | -- |
| bicycle | use_sidepath |
| foot | no |
| highway | secondary |

Routing over the **highway=footway** crossing at the bottom is okay if the rider is expected to dismount of course, but this is not reflected in the routing instructions (yet?).
