### ISSUE TITLE
OSRM doesn't create track due the osm point

### ISSUE THREAD

**Issue by Finardin** [Project-OSRM/osrm-backend#5559]
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=60.03769%2C30.22452%3B60.03788%2C30.22428

I have the same situation on my own osm server.
Could somebody explain please, whats wrong with this part of road? Why OSRM doesn't create direct track between two points?

**Comment by danpat** [comment]
My guess would be that https://www.openstreetmap.org/way/724416579 is a newly mapped way (6 days old as I write this) and may not exist in the routing data on the FOSSGIS OSRM server, or your own data dump.

Try getting a fresh extract from OSM and see if that fixes it.  I don't know how often they update the FOSSGIS routing server.

**Comment by Finardin** [comment]
At least i removed "construction", "proposed" tags from avoid set in profiler. And now OSRM build tracks with all roads
