### ISSUE TITLE
Traffic data updates with GPS data

### ISSUE THREAD

**Issue by rasamimalala** [Project-OSRM/osrm-backend#5562]
Hi all,
We have a lot of cars which are geolocated and we would like to update traffic data in osrm.

We try to make a csv file to update the traffic data but when we try to load this csv file with osrm-customize, osrm-customize does not read speed which are inside csv file.
This is the log (We use the latest docker image):
```
[info] Loaded /data/updates.csv with 1values
[info] In total loaded 1 file(s) with a total of 1 unique values
[info] Used 381686 speeds from LUA profile or input map
[info] Used 0 speeds from /data/updates.csv
[info] Updating segment data took 17.27ms.
[info] In total loaded 0 file(s) with a total of 0 unique values
[info] Done reading edges in 251.969ms.
[info] Loaded edge based graph: 176826 edges, 45240 nodes
[info] Loading partition data took 0.321236 seconds
[info] Cells customization took 0.068885 seconds
[info] Cells statistics per level
[info] Level 1 #cells 215 #boundary nodes 3329, sources: avg. 10, destinations: avg. 15, entries: 37269 (298152 bytes)
[info] Level 2 #cells 16 #boundary nodes 494, sources: avg. 20, destinations: avg. 30, entries: 11554 (92432 bytes)
[info] Level 3 #cells 1 #boundary nodes 0, sources: avg. 0, destinations: avg. 0, entries: 0 (0 bytes)
[info] Level 4 #cells 1 #boundary nodes 0, sources: avg. 0, destinations: avg. 0, entries: 0 (0 bytes)
[info] Unreachable nodes statistics per level
[info] Unreachable nodes statistics per level
[info] Unreachable nodes statistics per level
[info] Unreachable nodes statistics per level
[info] MLD customization writing took 0.002284 seconds
[info] Graph writing took 0.003513 seconds
[info] RAM: peak bytes used: 19591168
```
Maybe `from_osm_id` and `to_osm_id` are wrong? We identified `from_osm_id` and `to osm_id` from a graph loaded to Postgresql by using `osm2pgsql`.

Any idea or suggestion to identify `from_osm_id` and `to_osm_id` of an edge where the car is on?

Thank you!

**Comment by danpat** [comment]
My first guess would be that the `from_osm_id` and `to_osm_id` nodes are not directly connected.  If you have a curved road, you must put a CSV entry in for every connected pair of nodes.

If your road network is:

```
A---B---C---D
```

then your CSV file must contain:

A,B,25
B,C,25
C,D,25
D,C,25
C,B,25
B,A,25
```

in order to update all edges and directions in the graph with a speed of 25 km/h.

Another option may be that you've used a version of the graph in PostGresql that doesn't match your datafile (i.e. extracts from OSM at two different times) and the node IDs have changed, or are have been moved/split.

**Comment by rasamimalala** [comment]
@danpat , thanks for your reply! We found solution by using `match` service. With this, we can identify nodes ids by making `annotations` parameter to `true`. So, no need to use a postgresql database.

**Comment by afitas** [comment]
> @danpat , thanks for your reply! We found solution by using `match` service. With this, we can identify all nodes ids by making `annotations` parameter to `true`. So, no need to use a postgresql database.

thanks for this hint it's very usefull
