### ISSUE TITLE
What are these gaps called? Where to set them up?

### ISSUE THREAD

**Issue by EmelyanovKonstantin** [Project-OSRM/osrm-backend#5564]
I worked whith own OSRM server and Leaflet Routing Mashine.

There was a problem building the route:
![Безымянный](https://user-images.githubusercontent.com/54404460/65770371-9e34e780-e13e-11e9-94cf-3a3dd03707ce.png)

I am building a route for cars( car.lua profile). OSRM from the starting point leads through the forest to a longer route.
But the road passes right through the start point. This is highway = tertiary. 

Why OSRM behaves this way?
What is the name of this "forest gap"?
Where to read about it?
What settings are responsible for this: profile.lua or server request?

At first I thought that highway = tertiary is not connected to the road network. But in profile car.lua there is highway = tertiary.
![property](https://user-images.githubusercontent.com/54404460/65770517-ece28180-e13e-11e9-8d4d-36b0b251ca0c.png)

**Comment by danpat** [comment]
@EmelyanovKonstantin The likely cause here is that the tertiary road is not connected to the main road network, or has other tags on it that make it unroutable.  Perhaps there is a gate somewhere that blocks passage.

OSRM implements a "smart nearest neighbour" approach, which is described here:

https://blog.mapbox.com/robust-navigation-with-smart-nearest-neighbor-search-dbc1f6218be8

If your destination coordinate cannot be reached on the tertiary road, OSRM will snap the start point to the nearest location where it *can* be routed from.

A good way to debug this is to use the `osrm-frontend` debug map viewer, which you can find here:

https://github.com/Project-OSRM/osrm-frontend/tree/gh-pages/debug

Roads that show up highlighted in pink are isolated from the main road network, and you'll see this kind of snapping behaviour when you place coordinates near them.

I would check that the tertiary road is actually connected (follow it and make sure it joins something else), is not impassible (check `access=` tags and other things that may limit access), and look for barriers along the way (gates, fords, etc).

**Comment by EmelyanovKonstantin** [comment]
@danpat 
Thanks for the detailed answer. I followed your advice and installed OSRM-FrontEnd on my server.For comparison, I built a route on my server and on the map.project-osrm.org server<br>
map.project-osrm.org server:<br>
![osrm](https://user-images.githubusercontent.com/54404460/65793338-3c8c7180-e16e-11e9-9966-f023c8b00fa2.png)
my osrm server:<br>
![Myosrm](https://user-images.githubusercontent.com/54404460/65793364-4a41f700-e16e-11e9-88c7-2dd8f78d106c.png)

I think somewhere near the lake there is a barrier. Or the road to the lake has some properties.<br>
I am using OSM databases in August 2019. Do you think this is a database problem? Or a problem with my server settings? And how can I handle this?

**Comment by dooley** [comment]
Take a look: [car profile](https://github.com/Project-OSRM/osrm-backend/blob/f520379419aa2d5f11b6c0dfa25fb16967f63e04/profiles/car.lua#L41) vehicle-width is set to max. 1.9

The one highway (as seen on you upper shreenshot) is defined with width 1.5. I'm pretty sure this is the problem.
