### ISSUE TITLE
[5.22 car.lua] Routing-Bug from highway=motorway to highway=motorway_link

### ISSUE THREAD

**Issue by dooley** [Project-OSRM/osrm-backend#5568]
What would cause one cannot drive from german A5 to A45 (Gambacher Kreuz)? [See here](https://routing.openstreetmap.de/?z=18&center=50.463345%2C8.721141&loc=50.463071%2C8.721004&loc=50.464129%2C8.721766&hl=de&alt=0&srv=0).

OSM-Data seems untouched since 2017 and i cannot find the reason for that routing error, Graphopper as well as Magic Earth use that motorway-junction. I also have a local setup with OSRM 5.22 and original car.lua (only changing weight_name from routability to distance) with same results.

Edit: [OSRM-Debug page](https://routing.openstreetmap.de/debug/car.html#14/50.4714/8.7215)

**Comment by systemed** [comment]
Appears to be fixed now.
