### ISSUE TITLE
Is there way to ignore living streets during generating routes?

### ISSUE THREAD

**Issue by Finardin** [Project-OSRM/osrm-backend#5573]
I really need to ignore roads with tags "living_street=yes" and "highway=living_street", but I just can't understand how i should modify the car-profiler to get it. 
No matter what I do but OSRM uses this roads in any case.

Could somebody tell is it possible to exclude such roads completely or at least to set some big penalties for using these roads?

Thank you in advance.

**Comment by Finardin** [comment]
Any ideas? Anybody?

**Comment by danpat** [comment]
It should be as simple as removing all lines in `car.lua` that mention`living_street` - if OSRM doesn't recognize the value in the `highway=` tag, then that way will not be included in the routing grpah.

**Comment by Finardin** [comment]
> It should be as simple as removing all lines in `car.lua` that mention`living_street` - if the `car.lua` script doesn't tell OSRM what to do with a particular `highway=` value, then the way is ignored by default.

Thanks, but highway='living_street' is only one case and used not very often

The the most common combination is highway='service' and living_street='yes'
Is it possible to avoid such roads during creating routes?

**Comment by danpat** [comment]
Yes.   The way the Lua profiles work, is that there are 3 primary functions:

  - `process_node`
  - `process_way`
  - `process_turn`

For every node on the input file (pbf), the `process_node` function is called.  For every way in the input file, `process_way` is called.

If `process_way` returns without setting any properties on the way, then that way is dropped from the routing graph.

There are a bunch of helper functions in the scripts already to allow some kind of structure, but if all you want to do is filter out a specific combination, then you can just add something like this inside the `process_way` function:

```
function process_way(profile, way, result, relations)
begin

local my_data = {
    highway = way:get_value_by_key('highway'),
    living_street = way:get_value_by_key('living_street')
}

if (data.highway == 'service' and data.living_street == 'yes')
  then
    return
  end
...
```

**Comment by Finardin** [comment]
danpat 
That's all I need, thanks a lot!
