### ISSUE TITLE
Tile service - How to display the 2 lanes of roads in OpenLayers

### ISSUE THREAD

**Issue by rasamimalala** [Project-OSRM/osrm-backend#5575]
Hello all,
I'm trying to display the 2 lanes of roads in Openlayers 3 with the tile service. But it seems like the 2 lanes are superposed.

![Screenshot_2019-10-07 Traffic state](https://user-images.githubusercontent.com/43367147/66292227-77b83e80-e8ec-11e9-981b-e0dfc12e4f67.png)

My solution is to make an offset. But what properties should I use to identify if a road is a oneway or have 2 lanes? Which lane is the right lane and which lane is the left lane? If I display the feature properties in Openlayers, I only have the following:
```
ends_: Array [ 4 ]​
extent_: Array(4) [ 5290655.795158222, -2139938.5084253373, 5290751.565380186, … ]
flatCoordinates_: Array(4) [ 5290655.795158222, -2139938.5084253373, 5290751.565380186, … ]
flatInteriorPoints_: null
flatMidpoints_: null
id_: 1
properties_: {…}
    datasource: "traffic-0728"
    duration: 684.9000244140625​​
    is_small: false​​
    is_startpoint: true​​
    layer: "speeds"​​
    name: "Làlana Profesora Zafy Albert"​​
    rate: 0​​
    speed: 1​​
    weight: 684.9000244140625
```
Thanks!

**Comment by danpat** [comment]
The features in the tiles don't have a property that indicates the driving side for that location.  They *are* oriented in the direction of travel, so you could do something programmatic to either offset "right" if you know your map is being viewed in a right-driving country, and left if the opposite.  There's a GeoJSON file in the OSRM repo in the `data/` directory that has polygons for known left-driving countries that you could use as a starting point.

**Comment by rasamimalala** [comment]
Thanks for your reply @danpat. I resolve this issue by using ol-ext linestring offset.
