### ISSUE TITLE
Intermittent connection refused - linux 

### ISSUE THREAD

**Issue by JasperRev** [Project-OSRM/osrm-backend#5577]
On two identical amazon ec2 instances, one box refuses to start up with the osrm backend docker container.  The log files stop after line 4 below .... when it doesn't start up.... so it doesn't get to the http compression line nor the listening on line.  It just hangs forever.  After several reboots of the box, somehow, and then waiting for 15 minutes, it gave me a complete log file.

Is there a way to get diagnostics or determine what might be causing this?

[info] starting up engines, v5.22.0
[info] Threads: 16
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:5000
[info] running and waiting for requests

**Comment by danpat** [comment]
The `osrm-routed` server is loading data into RAM at that point - it can take quite a while if your map is big, or you have some kind of RAM limitation (like more data than RAM, so swap gets used).

Try adding `--mmap` to the command-line - this will map the files directly on disk instead of copying them into memory.  Startup will be faster, but queries will start out slower until filesystem pages are well cached.

**Comment by JasperRev** [comment]
@danpat that makes sense.  i'm using all of north america.  But on an identical box it loads within 1 minute.  For a while i thought it just wasn't going ot start up at all.

**Comment by danpat** [comment]
Well, it sounds like some kind of system contention - I think you're going to have to spelunk what's happening on the system with tools like `vmstat`, `iostat`, etc - see if something else is fighting OSRM for disk I/O, or whether there's a lot of swapping going on.

The primary work that OSRM does at startup is to read files from disk and load them into RAM, pretty much sequentially.  If that activity is going slowly, then my first guess is that reads from disk are being slowed down by something - perhaps something else on the system competing for disk I/O.

**Comment by JasperRev** [comment]
i will do that, thank you.
