### ISSUE TITLE
Instructions for my own trace

### ISSUE THREAD

**Issue by Yass-in** [Project-OSRM/osrm-backend#5578]
Hi,
I'm trying to use OSRM to get route instruction from route that I already have in db but I don't really know how to pass my pts to OSRM.
Should I use Match service or Route service and pass all my coordinates in the request ? (i've seen the max is 500 pts so it's quite annoying because the route can be 110km long ).

Thx

**Comment by danpat** [comment]
@Yass-in You should use the `/match` service for this.  If you're running your own OSRM server, there's no actual limit on the maximum size, you can set it as high as you like.  However, the more points you pass in, the slower the request becomes, so you'll want to test.

Another thing you can do is filter out noise - run something like https://github.com/mapbox/geosimplify-js over your trace before passing it to `/match` - this will remove coordinates that are in straight lines, which are redundant for matching - you'll get the same result with or without them, so you might as well drop them for performance sake.
