### ISSUE TITLE
Install of latest osrm (5.22.0) fails on latest Node LTS (v12.13.0)

### ISSUE THREAD

**Issue by bolt-juri-gavshin** [Project-OSRM/osrm-backend#5582]
Node v12 became LTS today, install of `osrm@5.22.0` fails on `node@v12.13.0`:
```node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.13.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/Users/xxx/xxx/node_modules/osrm/lib/binding/node_osrm.node\" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.22.0/Release/node-v72-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.22.0/Release/node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! install error
```

**Comment by danpat** [comment]
OSRM 5.22.0 was published before Node 12 existed - we don't have a mechanism for publishing binaries for old builds (and there's no guarantee it'd even build cleanly).

**Comment by bolt-juri-gavshin** [comment]
@danpat , thanks for the answer.
I didn't imply there should be a build for version 5.22.
What I wanted to say is that it's not possible to use latest version (5.22) on active LTS.
Is there a plan to release a new version, that will be usable on Node 12.13+?

**Comment by danpat** [comment]
@bolt-juri-gavshin No plans for a new release at this time.

If you have the ability to build OSRM yourself, I *believe* the node bindings code supports N-API that would work with Node 12+, but I have not tested it myself, and probably won't get a chance to any time soon.

**Comment by bolt-juri-gavshin** [comment]
@danpat , is there anything I can do to speed-up new release, compatible with Node 12?

**Comment by pcernek-spare** [comment]
This would be most helpful.

**Comment by SiarheiFedartsou** [comment]
Closing as we have green CI with node 12/14/16/18, but feel free to re-open if problem still exists.
