### ISSUE TITLE
Getting error "There are no edges remaining after parsing"

### ISSUE THREAD

**Issue by iamvinayak** [Project-OSRM/osrm-backend#5589]
I am trying to convert the OSM data into OSRM format using the steps documented on Wiki. However, while executing osrm-extract, I am receiving an error. Here is the output snippet of esrm-extract command. I am using the default car.lua profile which ships with OSRM profiles.

>-bash-4.2$ osrm-extract Streets.osm
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script profiles/car.lua
[info] Input file: Streets.osm
[info] Profile: car.lua
[info] Threads: 8
[info] Parsing in progress..
[info] input file generated by unknown tool
[info] timestamp: n/a
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 12.0085 seconds
[info] Raw input contains 245560 nodes, 182119 ways, and 0 relations, 0 restrictions
terminate called after throwing an instance of 'osrm::util::exception'
  what():  There are no edges remaining after parsing.src/extractor/extractor.cpp:645
Aborted

**Comment by iamvinayak** [comment]
I am not sure how I can share the OSM file which I am using, but here is a sample WAY from my OSM file. Any insights will be helpful.

`<way id="-245561">
<nd ref="-1"/>
<nd ref="-2"/>
<nd ref="-3"/>
<nd ref="-4"/>
<tag k="LINK_ID" v="16830462"/>
<tag k="N_SHAPEPNT" v="2"/>
<tag k="ADDR_TYPE" v="B"/>
<tag k="LANE_CAT" v="1"/>
<tag k="FERRY_TYPE" v="H"/>
<tag k="ST_NAME" v="31ST AVE"/>
<tag k="FEAT_ID" v="732933529"/>
<tag k="ST_LANGCD" v="ENG"/>
<tag k="NUM_STNMES" v="1"/>
<tag k="ST_TYP_AFT" v="AVE"/>
<tag k="R_NREFADDR" v="120-01"/>
<tag k="ST_NM_BASE" v="31ST"/>
<tag k="AR_MOTOR" v="Y"/>
<tag k="REF_IN_ID" v="39825346"/>
<tag k="ST_TYP_ATT" v="N"/>
<tag k="UNDEFTRAFF" v="N"/>
<tag k="FR_SPD_LIM" v="25"/>
<tag k="L_REFADDR" v="120-98"/>
<tag k="L_NREFADDR" v="120-00"/>
<tag k="L_ADDRSCH" v="E"/>
<tag k="L_ADDRFORM" v="H"/>
<tag k="DIR_TRAVEL" v="B"/>
<tag k="R_REFADDR" v="120-99"/>
<tag k="VANITYNAME" v="N"/>
<tag k="R_ADDRSCH" v="O"/>
<tag k="AR_BUS" v="Y"/>
<tag k="TO_SPD_LIM" v="25"/>
<tag k="SPEED_CAT" v="6"/>
<tag k="R_ADDRFORM" v="H"/>
<tag k="NREF_IN_ID" v="39825335"/>
<tag k="TO_LANES" v="0"/>
<tag k="FUNC_CLASS" v="5"/>
<tag k="FROM_LANES" v="0"/>
<tag k="ENH_GEOM" v="N"/>
<tag k="DIVIDER" v="N"/>
<tag k="TOLLWAY" v="N"/>
<tag k="L_AREA_ID" v="21085307"/>
<tag k="R_AREA_ID" v="21085307"/>
<tag k="L_POSTCODE" v="11354"/>
<tag k="R_POSTCODE" v="11354"/>
<tag k="L_NUMZONES" v="4"/>
<tag k="R_NUMZONES" v="4"/>
<tag k="MULTIDIGIT" v="N"/>
<tag k="NUM_AD_RNG" v="2"/>
<tag k="LOW_MBLTY" v="2"/>
<tag k="AR_AUTO" v="Y"/>
<tag k="AR_TAXIS" v="Y"/>
<tag k="AR_CARPOOL" v="Y"/>
<tag k="JUNCTIONNM" v="N"/>
<tag k="AR_PEDEST" v="Y"/>
<tag k="AR_TRUCKS" v="Y"/>
<tag k="AR_TRAFF" v="Y"/>
<tag k="AR_DELIV" v="Y"/>
<tag k="AR_EMERVEH" v="Y"/>
<tag k="PAVED" v="Y"/>
<tag k="PRIVATE" v="N"/>
<tag k="FRONTAGE" v="N"/>
<tag k="BRIDGE" v="N"/>
<tag k="TUNNEL" v="N"/>
<tag k="RAMP" v="N"/>
<tag k="POIACCESS" v="N"/>
<tag k="CONTRACC" v="N"/>
<tag k="ROUNDABOUT" v="N"/>
<tag k="INTERINTER" v="N"/>
<tag k="MAXATTR" v="Y"/>
<tag k="REVERSIBLE" v="N"/>
<tag k="SPECTRFIG" v="N"/>
<tag k="INDESCRIB" v="N"/>
<tag k="MANOEUVRE" v="N"/>
<tag k="DIVIDERLEG" v="N"/>
<tag k="INPROCDATA" v="N"/>
<tag k="FULL_GEOM" v="Y"/>
<tag k="URBAN" v="N"/>
<tag k="EXPLICATBL" v="Y"/>
<tag k="NAMEONRDSN" v="Y"/>
<tag k="POSTALNAME" v="N"/>
<tag k="STALENAME" v="N"/>
<tag k="EXITNAME" v="N"/>
<tag k="COVERIND" v="N0"/>
<tag k="PLOT_ROAD" v="N"/>
<tag k="CARPOOLRD" v="N"/>
<tag k="EXPR_LANE" v="N"/>
<tag k="PHYS_LANES" v="0"/>
<tag k="PUB_ACCESS" v="Y"/>
<tag k="SPD_LM_SRC" v="2"/>
<tag k="_clipped" v="no"/>
</way>`

**Comment by ImreSamu** [comment]
> Any insights will be helpful.  
> `<way id="-245561"> `   , `<tag k="RAMP" `

imho:
* check the referential integrity of your OSM input file : https://docs.osmcode.org/osmium/latest/osmium-check-refs.html
* the OSM tags are small letters .. ; see OSM Tags used by OSRM: https://taginfo.openstreetmap.org/projects/osrm#tags ; and  no [`higway=`](https://wiki.openstreetmap.org/wiki/Key:highway)  tags...
* you can download osm `india` extract  from http://download.geofabrik.de/asia/india.html 
* the osm india taginfo - highway statistics : https://taginfo.openstreetmap.in/keys/highway#values

**Comment by danpat** [comment]
Yes, @ImreSamu is right - while the data here is in OSM XML format, it is not usable by OSRM.

OSRM only understands the tagging conventions from the OSM Wiki - you cannot just make `<way>s` and exepect routable output.  The ways must be tagged properly, according to the normal OSM scheme.

In addition, I can see that you have invalid node references:

```
<way id="-245561"> <nd ref="-1"/> <nd ref="-2"/> <nd ref="-3"/> <nd ref="-4"/>
```

Negative numbers in IDs and refs are not valid - OSRM expects these numbers to be positive.

**Comment by iamvinayak** [comment]
thanks @ImreSamu and @danpat.
I added logging statements in LUA profile to check where the extraction process was breaking. It was due to missing OSRM specific tags like 'highway'.

I have requested my vendor to prepare the OSM file as per OSRM tags specification.
