### ISSUE TITLE
hosting solution for n. america

### ISSUE THREAD

**Issue by mkallaoun** [Project-OSRM/osrm-backend#5590]
Having issues finding an optimal hosting solution for linux using enough gb of ram for north america. I have tried using 32gb server (costing me $4K / year) and that is not enough. I need to bump it up to 64 gb of ram, but prices are astronomical at least with godaddy. 

Any help would be appreciated.

**Comment by danpat** [comment]
If query performance can be compromised, look at using the `--mmap` option.  You can run `osrm-routed` on a very small memory box with that, but queries will be slow as it will read from disk on-demand.  The more memory your have, the more disk reads will be cached and things will eventually speed up.

**Comment by systemed** [comment]
Lots of people use Hetzner or OVH for this sort of application: https://www.hetzner.com/dedicated-rootserver
