### ISSUE TITLE
osrm-prepare command not found

### ISSUE THREAD

**Issue by bsnyh** [Project-OSRM/osrm-backend#5591]
Hi, I'm following this link https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04 to set up OSRM server to my Ubuntu 18. I skip the step 2, because I have downloaded a .osm file earlier. I followed all the steps. Now, the thing is, the commands osrm-extract, and osrm-routed work out well. But osrm-prepare not work at all. 

$ osrm-extract
osrm-extract <input.osm/.osm.bz2/.osm.pbf> [options]:

Options:
  -v [ --version ]                      Show version
  -h [ --help ]                         Show this help message
  -l [ --verbosity ] arg (=INFO)        Log verbosity level: NONE, ERROR, 
                                        WARNING, INFO, DEBUG

Configuration:
  -p [ --profile ] arg (="profiles/car.lua")
                                        Path to LUA routing profile
  -d [ --data_version ] arg             Data version. Leave blank to avoid. 
                                        osmosis - to get timestamp from file
  -t [ --threads ] arg (=12)            Number of threads to use
  --small-component-size arg (=1000)    Number of nodes required before a 
                                        strongly-connected-componennt is 
                                        considered big (affects nearest 
                                        neighbor snapping)
  --with-osm-metadata                   Use metadata during osm parsing (This 
                                        can affect the extraction performance).
  --parse-conditional-restrictions      Save conditional restrictions found 
                                        during extraction to disk for use 
                                        during contraction
  --location-dependent-data arg         GeoJSON files with location-dependent 
                                        data
  --disable-location-cache              Use internal nodes locations cache for 
                                        location-dependent data lookups
$ osrm-prepare
osrm-prepare: command not found
$ osrm-routed
osrm-routed <base.osrm> [<options>]:

Options:
  -v [ --version ]                      Show version
  -h [ --help ]                         Show this help message
  -l [ --verbosity ] arg (=INFO)        Log verbosity level: NONE, ERROR, 
                                        WARNING, INFO, DEBUG
  --trial [=arg(=1)]                    Quit after initialization

Configuration:
  -i [ --ip ] arg (=0.0.0.0)            IP address
  -p [ --port ] arg (=5000)             TCP/IP port
  -t [ --threads ] arg (=12)            Number of threads to use
  -s [ --shared-memory ] [=arg(=1)] (=0)
                                        Load data from shared memory
  --memory_file arg                     DEPRECATED: Will behave the same as 
                                        --mmap.
  -m [ --mmap ] [=arg(=1)] (=0)         Map datafiles directly, do not use any 
                                        additional memory.
  --dataset-name arg                    Name of the shared memory dataset to 
                                        connect to.
  -a [ --algorithm ] arg (=CH)          Algorithm to use for the data. Can be 
                                        CH, CoreCH, MLD.
  --max-viaroute-size arg (=500)        Max. locations supported in viaroute 
                                        query
  --max-trip-size arg (=100)            Max. locations supported in trip query
  --max-table-size arg (=100)           Max. locations supported in distance 
                                        table query
  --max-matching-size arg (=100)        Max. locations supported in map 
                                        matching query
  --max-nearest-size arg (=100)         Max. results supported in nearest query
  --max-alternatives arg (=3)           Max. number of alternatives supported 
                                        in the MLD route query
  --max-matching-radius arg (=-1)       Max. radius size supported in map 
                                        matching query. Default: unlimited.

Could anyone kindly let me know how to fix this or point me to some references ?

**Comment by danpat** [comment]
Those instructions are out-dated - they only apply to OSRM 4.x and earlier, the current version is 5.x.

See the GitHub Wiki pages for this project for instructions on the commands to run.

**Comment by bsnyh** [comment]
Thank you so much!

**Comment by bsnyh** [comment]
@danpat I was wondering,  in the README.md file,  it indicates that in Windows, the status is build passing, while in Linux/macOS, the status is build error..... So, is there anything I need to pay attention to with my Linux Ubuntu 18 computer? Or do I need to install a windows OS to use OSRM (I hope not).
