### ISSUE TITLE
OSRM response time too high

### ISSUE THREAD

**Issue by rajat23495** [Project-OSRM/osrm-backend#5593]
Hi everyone,
I have deployed osrm via nodejs bindings on AWS ECS cluster of 244Gb RAM machine.
The data server is reading is mounted on an EFS for whole planet data which will be shared across multiple nodejs servers spawning when scaling out.
The response time i am getting for route service is around 900ms and as soon as i increase the load on nodejs server, it starts showing accumulated errors.
I have not set any limit on load balancer. 
What is the expected behaviour and response time?
Thank you

**Comment by danpat** [comment]
For routing, 244GB is likely way more than you need - at worst, OSRM will need to load all datafiles into RAM, which should be a lot less than 244GB, even for the whole planet.

The *preprocessing* steps need a lot more RAM than actually running queries.

I'd expect closer to 9ms for route requests than 900 - it sounds like something is very off with your configuration.  What options are you using when attaching your nodeJS code to the OSRM datafiles?  Are you using the `mmap` options?  If so, then yes, you can expect significantly lower query performance until the cache is warmed.  If you have 244GB RAM available, I'd suggest not using the `mmap` option and just loading all data into RAM and disabling swap.

**Comment by rajat23495** [comment]
Thanks for the reply @danpat swap is disabled on my EC2 machines. I will check for the mmap options once and loading planet-latest.osrm file into RAM right?
Also, for table service response does not seem give distance matrix, despite in the documentation it says you can optionally return distance matrix.
Documentation does not mention how to return distance as well as duration matrix - https://github.com/Project-OSRM/osrm-backend/blob/master/docs/nodejs/api.md
osrm-backend:v5.22.0

**Comment by danpat** [comment]
Looks like the node API docs are stale.  The option to get distances for the `table` plugin is:

```
  annotations: ['duration','distance']
```

(from here: https://github.com/Project-OSRM/osrm-backend/blob/master/include/nodejs/node_osrm_support.hpp#L1241-L1279)

Feel free to submit a PR to fix the docs :-)

**Comment by rajat23495** [comment]
These changes are available in v5.22.0 docker image right? I tried including that in my table.js file pfa code
`const express = require("express");
const logfmt = require("logfmt");

const router = express.Router();

router.post("/", (req, res) => {
  if (!req.body.coordinates) {
    return res.status(422).json({ error: "Missing coordinates" });
  }

  const osrm = req.app.get("osrm");
  const options = {
    coordinates: req.body.coordinates,
    sources: req.body.sources,
    destinations: req.body.destinations
    annotations: req.body.annotations
  };

  if (!req.body.sources || !req.body.destinations) {
    delete options.sources;
    delete options.destinations;
  }

  try {
    osrm.table(options, (err, result) => {
      if (err) {
        return res.status(422).json({ error: err.message });
      }
      return res.json(result);
    });
  } catch (err) {
    logfmt.error(new Error(err.message));
    return res.status(500).json({ error: err.message });
  }
});

module.exports = router;
`

it showed me the following error.
`yarn run v1.17.3
$ node src/run.js
/usr/src/app/src/routes/table.js:16
    annotations: req.body.annotations
    ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/src/app.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by rajat23495** [comment]
@danpat and how much response time do you expect for table service for whole planet to get the distance and duration matrix, i implemented it following is the response time for the two services route and table -
```
ip=::ffff:172.31.33.213 time=2019-11-14T08:28:32.421Z method=POST path=/foot/route status=200 content_length=600 content_type="application/json; charset=utf-8" elapsed=45ms
ip=::ffff:172.31.9.6 time=2019-11-14T08:07:59.588Z method=POST path=/foot/table status=200 content_length=876 content_type="application/json; charset=utf-8" elapsed=526ms
```

**Comment by danpat** [comment]
@rajat23495 the time taken to compute results depends on the shape of the query.  A 1000 coordinate `/table` request will take longer than a 2 coordinate one.  You haven't given enough detail (i.e. the actual requests made) to make any kind of judgement.

I will note that *large* matrices and *long* routes can suffer a bit at the NodeJS<->C++ boundary, as lots of Node objects are passed across the fence.

**Comment by rajat23495** [comment]
I did this loadtest using apache workbench and concurrency level at 1000. And i was generating just a 2*2 distance as well as duration matrix. Our requirement is just a 2*2 matrix. 
Request was with these coordinates as i have given distance, duration annotation as default
{"coordinates": [[13.3976, 52.5205], [13.3979, 52.5206]]}
I am using AWS ECS and all the graphs are extracted on NFS storage which is shared across n replicas (each different for bike, car, foot). This is done so that while spawning the preprocessing part is not required.
ab -k -p data.json -T application/json -c {concurrency level} -n {no. of requests} {URL}

**Comment by danpat** [comment]
I would suggest that the bottleneck might be the NFS storage.

There is one file - the `.fileIndex` file, which is read on-the-fly from disk, even if you load all other data into RAM.  It is used for initial coordinate snapping.  I *would* expect the first query to a particular coordinate to be a bit slow on NFS - it'll have to hit the network volume.  However, I'd expect the important pages to get cached by the filesystem quickly, so performance should improve.

At this stage, I think your only option will be to invest in some profiling tooling to try to identify where your bottleneck is.  For a 2x2 query like this, the response times you're seeing are unreasonably slow.  I would start by eliminating variables (e.g. NFS, concurrency, etc) to see if you can produce a case where it *does* perform fast, then try adding things back in to see what factors are introducing the slowness.

**Comment by rajat23495** [comment]
But suppose my ECS containers are scaling up, for that we need to provision them with extracted maps right i.e. share file system across all the containers so that extraction does not happen every time during scaling process. If i remove nfs, is there any other way i can provision these extracted maps for the subsequent containers?
I will check for abnormalities with EFS. I will check cache for the systems as well. because some frequently used files are supposed to be cached to reduce the response time.
Thanks for your suggestions. If you think any other architecture will suffice my needs please let me know.

**Comment by danpat** [comment]
I mean, you can simply copy files to local storage from somewhere on a shared network service (e.g. S3).  You do not need to re-run the `osrm-extract/contract` process each time.  Copying data like this will slow down boot time, but mean that when the service is ready to run queries, performance will be maximized.

**Comment by rajat23495** [comment]
But suppose if the boot time is too high then the point of autoscaling will be violated. As you said about the .fileindex and other files if loaded into memory should work faster right since they would not have to read the flies on the fly so that should rather improve my performance time.

**Comment by danpat** [comment]
You cannot have your cake and eat it too.  It's not possible to autoscale a "whole planet" OSRM system quickly, *and* maintain fast query performance as soon as a node comes online (via EFS).  These two things are fundamentally incompatible.

There are really just two options:

  1. Shard the data into smaller regions geographically - this would involve cutting up your map into different parts, and running multiple OSRM instances for different geographies.  You would need a reverse proxy that knows how to send requests to the right backend.  Because the shards would have less data, they could autoscale faster.

  2. Be at peace with the fact that OSRM cannot scale up quickly *and* perform fast at the same time.  Set your autoscaling thresholds low, and surrender to the fact that you must maintain quite a bit of capacity overhead so that you have enough time to scale up as traffic increases.

You can bring OSRM nodes online quickly by using lazy data loading, like EFS and `--mmap`, but the price you pay for this fast startup is query performance - OSRM cannot calculate routes quickly until data is locally available to the CPU in RAM.  EFS reads blocks over the network on-demand, so every read from a file incurs a network round trip, until the filesystem cache is sufficiently warm.
