### ISSUE TITLE
Wrong Result in Example.cpp / How to extract Waypoints

### ISSUE THREAD

**Issue by SegfaultCreator** [Project-OSRM/osrm-backend#5596]
Hi everyone,

when i use the C++ API, i get a different result from the frontend query (or the curl variant). 
I compiled the original example.cpp and get the following result using profiles/car.lua for osrm-extract:

> Distance: 2381.4 meter
> Duration: 253.8 seconds

In comparison, curl query for a car (https://router.project-osrm.org/route/v1/driving/7.419758,43.731142;7.419505,43.736825) gives me: 

> "duration":512.9,"steps":[],"distance":1985.5`

Is there a way to find out the Waypoints of the offline calculated route for Debugging? 
I only managed to find out, that i only have one leg. When i query the Json Route for "Geometry", i can only use the template for a json::string, which is not interpretable then. 

> Leg Distance of first leg:2381.4
> Geometry String:ch|iGuchl@aAcFo@qC[oA[u@KMIEICGCIAQBE@KBIFKHSRQLMFOJk@RGBODSFA@A?EBIBC@KBUHKBE@IBC@YHYFA@KBE@C?I@G@A@M@UDC?I@I@K@OBK@I?e@BYBG?I@[@G?K?Q?IAa@AA?[EA?SEGCKASIICKEAAm@a@IKIQCE??GMESEa@IuACk@ACCWGm@??OgAEYCO?EKu@Ee@C_@A_@Ca@?CA_@AMCMAKAEQs@Og@EQEQESACCQ?EIq@AMC[?EAGI[GQCECGEEGIGECCEAEAI?I?IDIBEFEDEHYn@EFUd@EFa@`AQ\IJEDGDKBK@IASIG?E@EDCH_@~AVLXRLFFBbBz@E`@A\B^Jh@`@x@BBHNDRBN@J@J?NCAA?C@C@ABAB?B?DOFk@L[HKHEB_@f@QZKJl@lBz@dEJh@DP@HBNBP@N?PANARCLAJALAL?ZBTFNZb@DDJDVNRHN@\KFCFCLKDILULg@BIH]Ro@HONIHAP@JDNNn@v@JPLP@@

Code (i used another scope and indent to mark the spot i changed from original example.cpp): 

```
int main(int argc, const char *argv[])
{
    if (argc < 2)
    {
        std::cerr << "Usage: " << argv[0] << " data.osrm\n";
        return EXIT_FAILURE;
    }

    using namespace osrm;

    // Configure based on a .osrm base path, and no datasets in shared mem from osrm-datastore
    EngineConfig config;

    config.storage_config = {argv[1]};
    config.use_shared_memory = false;

    // We support two routing speed up techniques:
    // - Contraction Hierarchies (CH): requires extract+contract pre-processing
    // Die Funktionen sind osrm-extract und osrm contract
    // - Multi-Level Dijkstra (MLD): requires extract+partition+customize pre-processing
    //
    // config.algorithm = EngineConfig::Algorithm::CH;
    config.algorithm = EngineConfig::Algorithm::CH;

    // Routing machine with several services (such as Route, Table, Nearest, Trip, Match)
    const OSRM osrm{config};

    // The following shows how to use the Route service; configure this service
    RouteParameters params;

    // Route in monaco - sind nicht mehr originialwerte
    params.coordinates.push_back({util::FloatLongitude{7.419758}, util::FloatLatitude{43.731142}});
    params.coordinates.push_back({util::FloatLongitude{7.419505}, util::FloatLatitude{43.736825}});

    params.overview = osrm::engine::api::RouteParameters::OverviewType::Full;
    params.steps = true;

    // Response is in JSON format
    engine::api::ResultT result = json::Object();

    // Execute routing request, this does the heavy lifting
    const auto status = osrm.Route(params, result);

    auto &json_result = result.get<json::Object>();
    if (status == Status::Ok)
    {
        auto &routes = json_result.values["routes"].get<json::Array>();

        // Let's just use the first route
        auto &route = routes.values.at(0).get<json::Object>();
        const auto distance = route.values["distance"].get<json::Number>().value;
        const auto duration = route.values["duration"].get<json::Number>().value;
        {
            auto legDist = route.values["legs"]
                               .get<json::Array>()
                               .values.at(0)
                               .get<json::Object>()
                               .values["distance"]
                               .get<json::Number>()
                               .value;

            auto geometryString = route.values["geometry"].get<json::String>().value;
            std::cout << "Leg Distance of first leg:" << legDist << std::endl;
            std::cout << "Geometry String:" << geometryString << std::endl;
        }

        // Warn users if extract does not contain the default coordinates from above
        if (distance == 0 || duration == 0)
        {
            std::cout << "Note: distance or duration is zero. ";
            std::cout << "You are probably doing a query outside of the OSM extract.\n\n";
        }

        std::cout << "Distance: " << distance << " meter\n";
        std::cout << "Duration: " << duration << " seconds\n";
        // std::cout << "Waypoints: " << geometry.c_str();

        return EXIT_SUCCESS;
    }
    else if (status == Status::Error)
    {
        const auto code = json_result.values["code"].get<json::String>().value;
        const auto message = json_result.values["message"].get<json::String>().value;

        std::cout << "Code: " << code << "\n";
        std::cout << "Message: " << code << "\n";
        return EXIT_FAILURE;
    }
}
```
Thanks in Advance :)

**Comment by jcoupey** [comment]
This is likely related to the [demo server setting](https://github.com/Project-OSRM/osrm-backend/wiki/Frequently-Asked-Questions#why-are-my-routestimes-different-from-the-project-osrmorg-demo-server).

**Comment by SegfaultCreator** [comment]
Thanks for the quick answer!

You are referring to the missing traffic data, right? 
But how could this influence, that the offline route becomes longer than the online, traffic affected, route?

And is there a plausible reason why arent there any waypoints in the route, apart from the start and end point?

The offline query leads to the following result
> curl "http://127.0.0.1:5000/route/v1/driving/7.419758,43.731142;7.419505,43.73682?steps=false"
{"code":"Ok","waypoints":[{"hint":"XgAAgP___38PAAAAngAAAI0AAAAAAAAA5mUtQdfTxUKDX8NCAAAAAA8AAACeAAAAjQAAAAAAAAAnAAAA6zZxALFJmwJuN3EAxkibAgMATwQrhcrg","distance":28.162868,"location":[7.419627,43.731377],"name":"Tunnel Rocher Palais"},{"hint":"6wAAgKEBAIAEAAAAAQAAAPMAAAAAAAAAKkTlQMIk0j8ePbdDAAAAAAQAAAABAAAA8wAAAAAAAAAnAAAAjjZxAN5emwJxNnEA9F6bAhkA7wIrhcrg","distance":3.381596,"location":[7.419534,43.736798],"name":"Boulevard Rainier III"}],"routes":[{"legs":[{"steps":[],"weight":253.8,"distance":2381.8,"summary":"","duration":253.8}],"weight_name":"routability","geometry":"ch|iGuchl@mCeM[u@g@[m@FyAfAkBn@}FlAwEHeAQyAw@e@eAmAaMMsC{@sDWeC_@aAs@W_@V_CzEYNw@Gi@nBjDhBC~AJh@n@lALz@Qb@iBl@}@nA|BxJHbAMtBf@hAlAf@l@S`@k@n@_Cb@[l@VjA~A","weight":253.8,"distance":2381.8,"duration":253.8}]}(base)

**Comment by SegfaultCreator** [comment]
Found a way to solve - just found out the details about the polylinestring format used for the geometry. Issue is closed therefore

**Comment by danpat** [comment]
@SegfaultCreator If it's simpler for you, you can set `geometries=geojson` and you'll get back a geojson object instead of an encoded polyline.
