### ISSUE TITLE
osrm-extract stops with "Killed."

### ISSUE THREAD

**Issue by JanisE** [Project-OSRM/osrm-backend#560]
Hello!

I call osrm-extract, it runs for about 10 hours and ends with a message "Killed" - no explanation.

The full output is:

<pre>$ ./osrm-extract /home/k/europe.osm.pbf profile_fastest.lua
[info Extractor/ScriptingEnvironment.cpp:33] Using script profile_fastest.lua
[info extractor.cpp:59] extracting data from input file /home/k/europe.osm.pbf
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-MSG] 1 disks are allocated, total space: 25000 MiB
Killed</pre>

I found #314 and #319, however they both are closed.

So, if I get a message "Killed", does it 100% mean that it is an insufficient memory problem?
Does it mean that in order to successfully prepare OSRM data, I must have the necessary amount of RAM, and I cannot use the disk+more time in exchange?

I'm currently testing on a rather modest machine — 2GB RAM and 160GB disk space —, but even for the public instance, I doubt I will be able to afford 64GB RAM or more.

**Comment by Glitchfix** [comment]
if you are running this inside docker please set a memory limit I was trying this out for India and it kept crashing I set my memory limit to 12GB in the docker compose and it worked like a charm
`mem_limit: 12g`
