### ISSUE TITLE
The libosrm_guidance library is not installed

### ISSUE THREAD

**Issue by jdesgats** [Project-OSRM/osrm-backend#5603]
When using the shared library mode (`-DBUILD_SHARED_LIBS=ON`), the `libosrm_guidance.so` library is build but not installed. But the `osrm-extract` binary needs that lib and therefore cannot run in that case.

**Comment by codekesh** [comment]
I'm still having problem with this libosrm_guidence.dylib when add -DBUILD_SHARED_LIBS=ON on cmake?!
it's work without export shared library
