### ISSUE TITLE
Routing issue near Grand Teton Naitonal Park

### ISSUE THREAD

**Issue by kasunvp** [Project-OSRM/osrm-backend#5605]
This image explains everything. 

![routing-issue](https://user-images.githubusercontent.com/56943/68986071-bd203380-07e9-11ea-8fef-29ab853907c4.png)

**Comment by danpat** [comment]
I'm sorry, but you're going to need to supply more detail.  What were you expecting to happen here?  What routing server were you using at the time, your own, or the OSRM demoserver?  What profile were you using to request the route?

The Lake of the Crags Trail is marked as `highway=path` - i.e. it's a walking-only trail.  If you're using the OSRM demoserver at `router.project-osrm.org`, then it only supports the driving profile, and from what I can see, the route provided is the nearest feasible route to the coordinates you've provided.

If you don't want OSRM to snap to the nearest road at indefinite distances, you'll need to supply a `radiuses=` parameter to your API calls.  If you did that in this case and set it to say, 10m, then you'd get  "NoRoute" response from OSRM instead.

**Comment by kasunvp** [comment]
Thanks so much for your quick reply here @danpat 

> I'm sorry, but you're going to need to supply more detail. What were you expecting to happen here? What routing server were you using at the time, your own, or the OSRM demoserver? What profile were you using to request the route?

Sorry I thought I had the url in the screenshot. 
Yes I was simply using the demo server https://map.project-osrm.org/ So I suppose it uses the `driving` profile as you said. 

> The Lake of the Crags Trail is marked as highway=path - i.e. it's a walking-only trail. If you're using the OSRM demoserver at router.project-osrm.org, then it only supports the driving profile, and from what I can see, the route provided is the nearest feasible driving route to the coordinates you've provided.
> If you want a walking route, you'll need to use a different OSRM server that supports the walking profile.

We actually use Mapbox with `mapbox/walking` profile. The problem started there and we were investigating why. So in the process I tried the documentation http://project-osrm.org/docs/v5.5.1/api/#route-service with different services and the profile `foot`. 

> If you don't want OSRM to snap to the nearest road at indefinite distances, you'll need to supply a radiuses= parameter to your API calls. If you did that in this case and set it to say, 10m, then you'd get "NoRoute" response from OSRM instead.

We actually need snapping and that’s why we’re looking into this.

**Comment by SiarheiFedartsou** [comment]
Stale.
