### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by snezhkoigor** [Project-OSRM/osrm-backend#5609]
Hi. Tell me please about multiple profiles. I need run different OSRM backand instance for each profiles (car, foot etc)? Or I can do this “ docker run -t -v $(pwd):/data osrm/osrm-backend:vX.Y.Z osrm-extract -p /opt/car.lua /data/monaco-latest.osm.pbf” with multiple profiles?

**Comment by danpat** [comment]
You need a separate OSRM instance and datafiles for each profile.
