### ISSUE TITLE
Own OSRM map

### ISSUE THREAD

**Issue by snezhkoigor** [Project-OSRM/osrm-backend#5610]
Hi. Can I use my own (modified, with my extra graph info) osrm map in extract process?

**Comment by bsnyh** [comment]
Yes, you can. You may follow this link: https://lists.openstreetmap.org/pipermail/osrm-talk/2016-October/001366.html. What do you mean your extra graph info?

**Comment by snezhkoigor** [comment]
"What do you mean your extra graph info?" - for example paid roads
