### ISSUE TITLE
OSRM mapmatching api low throughput / high latency

### ISSUE THREAD

**Issue by JatinderSingh** [Project-OSRM/osrm-backend#5611]
I had setup OSRM server on ec2 m5ad 2xlarge. I am trying to map match couple of coordinates using CH algorithm for india data pulled from geofabrik servers.

latency and throughput numbers measured for by using wrk for map match api do seem very low. Below are benchmark numbers. 

```
./wrk -c5 -t1 -L -R5 -d1000s "http://<osrm-server>/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&radiuses=20.766;16.188;15.154;15.636;11.352;16.523;12.675;15.781;13.655;12.501&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393"


 Thread calibration: mean lat.: 1698.435ms, rate sampling interval: 4894ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.21m    40.10s    2.39m    57.99%
    Req/Sec     3.99      0.10     4.00    100.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.22m 
 75.000%    1.78m 
 90.000%    2.13m 
 99.000%    2.35m 
 99.900%    2.39m 
 99.990%    2.40m 
 99.999%    2.40m 
100.000%    2.40m 

  4291 requests in 16.67m, 22.70MB read
  Socket errors: connect 0, read 5, write 0, timeout 0
Requests/sec:      4.29
Transfer/sec:     23.24KB
```

Is there something wrong in the setup? Or is performance of map matching api generally having low throughput and high latency?

This issue gets compounded in case timeouts are put on client side and retrials are build. Server never recovers (always 100% cpu) and osrm-routed needs to be restarted.

**Comment by danpat** [comment]
The performance of map-matching is quite sensitive to input parameters and road network density.

Try it again but remove the `radiuses=` parameter - this reduces the amount of work the algorithm has to do, at the expense of possibly failing to find a match due to imprecise GPS coordinates.

The matching algorithm considers every road edge within 3x the radius you supply - if the road network is dense, and you supply a large-ish radius, this can mean that the matching algorithm needs to check *lots* of possibilities for every coordinate.

This is the fundamental tradeoff of the algorithm.  Better matches are found for imprecise inputs with larger radiuses, at the expense of computation time.

**Comment by JatinderSingh** [comment]
Thanks @danpat I tried after removing radiuses option and throughput increased but only to number range around 80req/sec and latency was still high 

./wrk -c80 -t1 -L -R1000 -d100s "http://<server>/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=1482859;1482928;1482989;1483018;1483093;1483138;1483183;1483243;1483348;1483393"
Running 2m test @ http://<server>/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=1482859;1482928;1482989;1483018;1483093;1483138;1483183;1483243;1483348;1483393
  1 threads and 80 connections
  Thread calibration: mean lat.: 4562.080ms, rate sampling interval: 16556ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    50.34s    23.66s    1.59m    57.85%
    Req/Sec    81.40      0.49    82.00    100.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%   50.33s 
 75.000%    1.18m 
 90.000%    1.39m 
 99.000%    1.51m 
 99.900%    1.57m 
 99.990%    1.59m 
 99.999%    1.59m 
100.000%    1.59m 

Is there some missing configuration to improve on latency / throughput?

**Comment by danpat** [comment]
There's definitely something wrong with your setup, but I can't guess what.  I downloaded `india-latest.osm.pbf` from GeoFabrik and use `osrm-extract/partition/customize` to generate an MLD dataset (not CH, I used MLD because it doesn't take as long to generate, and for your trace, I wouldn't expect the match time to be very different).  I re-ran your benchmark but just for 30 seconds both with and without radiuses, and I get 45 req/sec and 270 req/sec.

I did this all locally on my Mac laptop with 16GB of RAM and a 3.5GHz Core i7 CPU.

```
$ wrk -c5 -t1 --latency -d30s "http://localhost:5000/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&radiuses=20.766;16.188;15.154;15.636;11.352;16.523;12.675;15.781;13.655;12.501&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393"
Running 30s test @ http://localhost:5000/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&radiuses=20.766;16.188;15.154;15.636;11.352;16.523;12.675;15.781;13.655;12.501&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393
  1 threads and 5 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   110.24ms   28.51ms 247.82ms   72.08%
    Req/Sec    45.18     10.07    70.00     74.92%
  Latency Distribution
     50%  103.31ms
     75%  126.35ms
     90%  151.23ms
     99%  198.07ms
  1358 requests in 30.00s, 7.14MB read
Requests/sec:     45.26
Transfer/sec:    243.56KB
✔ ~/mapbox/vorpal-sword [danpat_client_gallo L|✚ 1…29⚑ 25]
09:03 $ wrk -c5 -t1 --latency -d30s "http://localhost:5000/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393"
Running 30s test @ http://localhost:5000/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393
  1 threads and 5 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    18.59ms    9.27ms 139.07ms   88.38%
    Req/Sec   275.78     45.25   350.00     69.90%
  Latency Distribution
     50%   16.22ms
     75%   21.17ms
     90%   28.68ms
     99%   55.15ms
  8247 requests in 30.03s, 45.33MB read
Requests/sec:    274.61
Transfer/sec:      1.51MB
```

There's something really wrong in your setup somewhere, but I don't know where it is - I don't think it's fundamentally OSRM.  Is your server massively overloaded or swapping somehow?

**Comment by JatinderSingh** [comment]
I am using aws instance with 32gb ram and 8 cores. And only osrm-routed is running started with options `osrm-routed -p 8080 /home/ubuntu/ch/india-latest.osrm` I do not expect swapping as more than 23Gb is available as free ram. 

Do i need to start osrm-routed with some specific options for higher throughput?

below are values when i retested with wrk2 running locally
./wrk -c5 -t1 --latency -d100s -R100 "http://localhost:8080/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393"
Running 2m test @ http://localhost:8080/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393
  1 threads and 5 connections
  Thread calibration: mean lat.: 2021.480ms, rate sampling interval: 7213ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    10.43s     3.72s   17.02s    57.83%
    Req/Sec    22.50     27.73    60.00     66.67%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%   10.41s 
 75.000%   13.66s 
 90.000%   15.61s 
 99.000%   16.75s 
 99.900%   17.01s 
 99.990%   17.04s 
 99.999%   17.04s 
100.000%   17.04s 
  2565 requests in 1.67m, 14.19MB read
  Socket errors: connect 0, read 0, write 0, timeout 140
Requests/sec:     25.64
Transfer/sec:    145.27KB

Two difference which i can see are :-
1.)  i am facing timeouts on client
2.)  wrk2 which is being used here corrects latency measurement by accounting for coordinated omission as well. so latency observed by wrk2 is higher / more accurate, but numbers seem drastically different. 

Above results were when attempted request rate by client was 100 requests/sec if we reduce same to 50 requests/sec and run benchmark numbers change to below, One thing to observe here is osrm-routed was not restarted in between the two tests.

./wrk -c5 -t1 --latency -d100s -R50 "http://localhost:8080/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393"
Running 2m test @ http://localhost:8080/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393
  1 threads and 5 connections
  Thread calibration: mean lat.: 80.078ms, rate sampling interval: 187ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    80.05ms   10.34ms  99.14ms   46.44%
    Req/Sec    22.78     24.93    53.00     72.35%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%   77.89ms
 75.000%   91.46ms
 90.000%   93.82ms
 99.000%   96.13ms
 99.900%   97.02ms
 99.990%   99.20ms
 99.999%   99.20ms
100.000%   99.20ms
  2565 requests in 1.67m, 14.19MB read
  Socket errors: connect 0, read 0, write 0, timeout 120
Requests/sec:     25.64
Transfer/sec:    145.27KB

**Comment by danpat** [comment]
Ah, I see, you're using `wrk2`, not `wrk`.  I used `wrk` which simply runs concurrent threads that send off new requests when previous ones are started.  This generally tests the max throughput of the system.

`wrk2` on the other hand, attempts to force a constant request rate.  This better simulates a real world situation where you don't control how many requestors there are and how often they make requests.

The reason you're seeing 10 sec+ requests is that your server cannot keep up with 100 requests/second.  As time goes on, requests sit in the queue for longer and longer before being processed.  The results show that your server is handling 25 req/sec.  This means that there's a defecit of 75 req/sec that aren't getting served.  The high latency values in the histogram are likely the requests sent near the end of the test run that had to wait a long time until they got handled.

The TL;DR is your server can sustain 25/sec throughput, but your test is sending 100/sec, so naturally you'll see high latency.

Now, as to why your expensive server is 10x slower than my (admittedly expensive) laptop is another question.

I'm running `osrm-routed -a MLD india-latest.osm.pbf` - the main difference here is that I generated data using the MLD pipeline instead of the CH one to save time.

I'd also check that you've compiled OSRM in "Release" mode - it should be the default, but maybe you've picked up a debug version of the build somehow - this will be quite a lot slower.

If I use a debug build of OSRM, I get significantly slower results with `wrk`:

```
wrk -c5 -t1 --latency -d30s "http://localhost:5000/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393"
Running 30s test @ http://localhost:5000/match/v1/car/77.622856,12.931771;77.62375,12.934619;77.62511,12.936615;77.6265,12.937581;77.62742,12.940875;77.627945,12.94194;77.628334,12.942883;77.62854,12.943808;77.629,12.945539;77.62781,12.945153?overview=full&geometries=geojson&timestamps=2859;2928;2989;3018;3093;3138;3183;3243;3348;3393
  1 threads and 5 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   138.71ms   38.12ms 417.36ms   73.46%
    Req/Sec    35.97      9.13    60.00     75.51%
  Latency Distribution
     50%  131.77ms
     75%  158.32ms
     90%  187.57ms
     99%  270.96ms
  1078 requests in 30.02s, 5.93MB read
Requests/sec:     35.90
Transfer/sec:    202.10KB
```

**Comment by danpat** [comment]
Also, check that `osrm-routed` is actually detecting all 8 of your CPUs - it prints out a message like this at startup:

```
$ ./osrm-routed india-latest.osrm -a MLD
[info] starting up engines, v5.24.0
[info] Threads: 4
[info] IP address: 0.0.0.0
[info] IP port: 5000
```

The `Threads: 4` line says it detected 4 CPUs.  You can force the worker thread count with `--threads N`, but if OSRM is mis-detecting, you should ensure that you actually have access to all 8 of those cores (perhaps there's some  `cgroup` magic going on that's limiting what your processes can do).

**Comment by JatinderSingh** [comment]
I had setup OSRM using https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM
stable version. And all 8 cores of instance were being 100% utilised on load. Htop cpu usage confirms same. Below is osrm version being used `osrm-routed --version
v5.22.0
`

Latency numbers without coordinated emission correction also nearly match. 

Is there a benchmark of osrm map matching available using some other http server besides osrm-routed?

**Comment by danpat** [comment]
The only thing I can think is that you're not using a "release" build of OSRM.  Exactly how did you obtain the binaries you're running?  Did you build them yourself, or install them from a package?

Do you see `[debug]` lines in the OSRM logging output?

**Comment by JatinderSingh** [comment]
yes binaries were compiled on server and i also see` [debug] `lines in console output of osrm.

**Comment by danpat** [comment]
You need to recompile osrm in Release mode.  Do `cmake -DCMAKE_BUILD_TYPE=Release ..` - this should've been the default, so I'm not sure how you ended up with debug binaries.

You do not need to regenerate routing datafiles if you rebuild the OSRM program files.
