### ISSUE TITLE
Throws an Exception(latest Build is unstable) 

### ISSUE THREAD

**Issue by shivansh7seth** [Project-OSRM/osrm-backend#5615]
Hi Team,

I followed the documentation and north America .osm.pbf file I faced this issue at the last step.
The work that I am doing is critical and quick help will be appreciated. PFB the exception

docker run -t -i -p 5000:5000 -v "C:\Users\shivansh\Documents\USTax\data:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/north-america-latest.osm.pbf
[info] starting up engines, v5.22.0
[info] Threads: 3
[info] IP address: 0.0.0.0
[info] IP port: 5000
terminate called after throwing an instance of 'osrm::util::exception'
what(): data block /mld/multilevelgraph/edge_array not found include/storage/shared_data_index.hpp:90

**Comment by danpat** [comment]
You are passing the `.pbf` filename to `osrm-routed`, but you need to pass the `.osrm` filename instead.

**Comment by shivansh7seth** [comment]
Hi Danpat,
Thanks for your quick response I tried with .osrm file still got the same error -:

docker run -t -i -p 5000:5000 -v "C:\Users\shivansh\Documents\USTax\data:/data" docker.io/osrm/osrm-backend:v5.22.0 osrm-routed --algorithm mld /data/north-america-latest.osrm
[info] starting up engines, v5.22.0
[info] Threads: 3
[info] IP address: 0.0.0.0
[info] IP port: 5000
terminate called after throwing an instance of 'osrm::util::exception'
  what():  data block /mld/multilevelgraph/edge_array not found include/storage/shared_data_index.hpp:90

Looking forward for some help!

**Comment by shivansh7seth** [comment]
HI Daniel,

Could u pls help?

**Comment by danpat** [comment]
I suspect your preprocessing steps did not complete properly - did `osrm-extract`, `osrm-partition`, or `osrm-customize` print out an error, or stop before printing out a success message?

**Comment by shivansh7seth** [comment]
Thanks Daniel..finally it worked..
