### ISSUE TITLE
add approach on the opposite side of the road

### ISSUE THREAD

**Issue by asaveljevs** [Project-OSRM/osrm-backend#5616]
This feature request is a continuation of #2201 issue and, specifically, #4039 pull request. Even though #4039 initially implemented three types of approaching a waypoint, it ended just adding `approach` of `curb` and `unrestricted`, because no use case was seen for the `opposite`. In this request, we would like to describe one use case for the `opposite` approach.

The use case is the same as in #5586, where we are solving a VRP problem with large, long trucks. In that problem, trucks generally like to continue in the direction they are going - if a truck approaches a waypoint heading West, then it continues from that waypoint also heading West.

In a routing problem, this may be solvable using `continue_straight_at_waypoint` profile parameter, but this is a VRP problem, meaning that we first have to calculate a distance matrix before solving. For each pair of waypoints, A and B, that matrix should contain the following four values for the distance from A to B:

- distance, if we leave A from the curb side of the road and approach B on the curb side
- distance, if we leave A from the curb side of the road and approach B on the opposite side
- distance, if we leave A from the opposite side of the road and approach B on the curb side
- distance, if we leave A from the opposite side of the road and approach B on the opposite side

With just `curb` and `unrestricted`, it is not possible to calculate this matrix. Besides, distance is not the only thing that matters - another thing that matters is whether the truck is carrying load or is driving empty. For instance, here OSRM by default approaches the red node on the right side using the shortest path:

![example](https://user-images.githubusercontent.com/1382964/69623840-3e7a9000-104c-11ea-8caf-68b1496e789a.png)

However, it will be doing a pickup on the red node and the intention is to drive with as less load as possible, especially when making u-turns, because u-turns with heavy load are more damaging to the roads. This means that we would rather first drive past the red node, make a u-turn at the special loop, and then approach the red node from the opposite side. This is longer, but that makes driving with load from the red node to the next node shorter.

**Comment by danpat** [comment]
To properly solve this for a VRP, I believe what you'd need are multiple entries in the Matrix, an entry for every possible combination of departure/arrival for each pair.  If you had that, then you'd be able to apply a u-turn penalty at waypoints in your VRP costing model.  You could use this to bias solutions toward routes that don't require u-turns.

There's an earlier ticket about doing this here: https://github.com/Project-OSRM/osrm-backend/issues/5438.  The same question was asked in the Valhalla repository, and a partial implementation was submitted (https://github.com/valhalla/valhalla/pull/1815).

An edge case for this is what to do when you snap to intersections - the ticket above assumes you've only got two departure direction options, but that's not true if you snap to an intersection.  This problem is described here: https://github.com/Project-OSRM/osrm-backend/issues/4465

**Comment by asaveljevs** [comment]
Yes, to clarify a bit, we want to use the `table` service (http://project-osrm.org/docs/v5.22.0/api/#table-service) to calculate the matrix. For each original point P, our intention is to pass two points to the `table` service, one with `curb` approach and another with `opposite` approach, like so:

```
.../table/v1/driving/X1,Y1;X1,Y1;X2,Y2;X2,Y2?approaches=curb;opposite;curb;opposite...
```

We are already using a similar approach in a different project and that approach works (also using u-turn penalties at waypoints there), but that project uses our own router and OSRM is much more efficient (great work!), so we would like to use OSRM.

Thank you for pointing out the intersection edge case! That is interesting and we (well, I) have not considered it before, but, from a practical perspective, we could live with it if it snaps to a random edge, since those cases are going to be rare enough.

**Comment by asaveljevs** [comment]
For completeness, GraphHopper recently added a similar functionality: https://github.com/graphhopper/graphhopper/pull/1697 .

**Comment by danpat** [comment]
What are your feelings about the *literal* corner case - when a coordinate is closest to an intersection (https://github.com/Project-OSRM/osrm-backend/issues/4465).  In those cases, there can be more than 1 snapping candidate.

**Comment by asaveljevs** [comment]
While I currently do not have a solution for the literal corner case, my _feelings_ are that that corner case should not stand in the way of implementing the opposite approach feature, as it is largely independent. As mentioned above, from the practical perspective (if we are talking about our matrix calculation), the benefit of having the opposite approach outweighs the potential problems with that corner case, because it is very likely to be rare.

**Comment by asaveljevs** [comment]
This is just a short update that this functionality is still relevant (or, rather, indispensable) for us and, while it is not implemented in the main version of OSRM, we are using the original patch with `approach=opposite` from #4039.

**Comment by mjjbell** [comment]
OSRM added support for snapping to multiple edge candidates in #5953, so the intersection edge-case is no longer a problem. 

The edge-case I do still foresee though, is when the waypoint is already on the road - the selection of curb/opposite will be arbitrary. This will already be a problem for existing `approach=curb` queries though, so perhaps it's a separate issue.

In any case, this seems simple enough to implement. It looks like it was dropped from the PR as nobody advocated for it at the time, but it exists in other routing engines, so I think it's worth adding.

**Comment by asaveljevs** [comment]
@mjjbell, thank you so much for taking the initiative and making this functionality available in the main version of OSRM!
