### ISSUE TITLE
Error loading south-america-latest.osm.pbf

### ISSUE THREAD

**Issue by markoperich** [Project-OSRM/osrm-backend#5617]
Trying to load `south-america-latest.osm.pbf` downloaded from [Geofabrik](http://download.geofabrik.de/south-america-latest.osm.pbf), I'm getting the following error:

```
$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/south-america-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: south-america-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 2
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2019-11-25T21:19:02Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
TBB Warning: Exact exception propagation is requested by application but the linked library is built without support for it
terminate called after throwing an instance of 'tbb::captured_exception'
  what():  std::bad_alloc
```

Please check if this is a problem in docker image. This file has no problem to load in nominatim using 
`osm2pgsql`

Thanks.

**Comment by danpat** [comment]
`std::bad_alloc` means you've run out of RAM.  Make sure your docker container isn't limited.  To process south america, you'll need at least tens of GB of RAM for the `osrm-extract` phase.

**Comment by markoperich** [comment]
Thanks @danpat  for your quick response. I was able to extract chile-latest.osm.pbf.
It is possible to load file individually to complete South America in a "per country" basis?

**Comment by danpat** [comment]
No, there is no way to merge processed files together after-the-fact.

Processing does take many more resources (disk, CPU, RAM) than routing.  A common approach is to temporarily rent a big server (e.g. from AWS) for a few hours to process the data, then you can use it on a much smaller machine for routing.

**Comment by markoperich** [comment]
Thank you. Now i know. :-)
Greetings and GREAT WORK!!!
