### ISSUE TITLE
Getting No route for some Co -ordinates and Incorrect value for others

### ISSUE THREAD

**Issue by shivansh7seth** [Project-OSRM/osrm-backend#5618]
Hi Team,

I have used North America.som.pbf and latest image of the project.
I set up the entire thing on one VM and the project is up and responding to my requests.
But I am getting discrepancies in terms of responses (all coordinates are from North America) - 

**using Demo -:**
http://router.project-osrm.org/route/v1/driving/-83.773504,40.347534;-83.788813,40.362391?overview=false

**Demo Response**

{"routes":[{"legs":[{"summary":"","weight":517.9,"duration":340.8,"steps":[],"distance":3784.6}],"weight_name":"routability","weight":517.9,"duration":340.8,"distance":3784.6}],"waypoints":[{"hint":"SHuXgP1aA4Y3AAAAMQAAAAAAAABJAAAAOXC8QkX7n0IAAAAAYWfwQjcAAAAxAAAAAAAAAEkAAACaQwAAtLcB-winZwLAtwH7jqdnAgAA3wXAA1IV","distance":14.914136892653563,"name":"West Lake Avenue","location":[-83.773516,40.3474]},{"hint":"H1sDhv___3-kAAAANQEAALkCAAAAAAAAHLaRQdLJgEFHz5pCAAAAAFIAAACbAAAAXQEAAAAAAACaQwAA3HsB-5nhZwLzewH7l-FnAgIAbwDAA1IV","distance":1.9659084471300463,"name":"","location":[-83.788836,40.362393]}],"code":"Ok"}

**Local Call**

http://127.0.0.1:5000/route/v1/driving/-83.773504,40.347534;-83.788813,40.362391?overview=false

Response 

{"code":"Ok","routes":[{"legs":[{"steps":[],"distance":301534.8,"duration":177.6,"summary":"","weight":247.2}],"distance":301534.8,"duration":177.6,"weight_name":"routability","weight":247.2}],"waypoints":[{"hint":"3aWTgAwG-YVUAAAASAAAAAAAAABsAAAAOXC8QkX7n0IAAAAAYWfwQlQAAABIAAAAAAAAAGwAAAAASAAAtLcB-winZwLAtwH7jqdnAgAA3wV_6m2w","distance":14.914137,"name":"West Lake Avenue","location":[-83.773516,40.3474]},{"hint":"Lgb5hf___38rAAAAUgAAALoAAAAAAAAAHLaRQdLJgEFHz5pCAAAAACsAAABSAAAAugAAAAAAAAAASAAA3HsB-5nhZwLzewH7l-FnAgIAbwB_6m2w","distance":1.965908,"name":"","location":[-83.788836,40.362393]}]}

NO ROUTE Example -:

http://router.project-osrm.org/route/v1/driving/-86.718829,33.658388;-84.901683,35.135628?overview=false

{"routes":[{"legs":[{"summary":"","weight":10148.2,"duration":9899.1,"steps":[],"distance":271037.6}],"weight_name":"routability","weight":10148.2,"duration":9899.1,"distance":271037.6}],"waypoints":[{"hint":"uw4MhL4ODIQlAAAA3wAAAAAAAAAYAQAA0AvwQSZalEIAAAAAkhy6QiUAAADfAAAAAAAAABgBAACaQwAARMPU-kGYAQKTxtT6FJYBAgAAbwLAA1IV","distance":99.93227268302475,"name":"Carson Boulevard","location":[-86.719676,33.658945]},{"hint":"nQ9YhrcPWIbWAQAAlAAAACEAAAAAAAAAG3ecQ8aBs0KCE61BAAAAANYBAACUAAAAIQAAAAAAAACaQwAAJIHw-mogGALNgPD6jCAYAgEA3wzAA1IV","distance":8.78151824337167,"name":"Refreshment Lane Southwest","location":[-84.901596,35.135594]}],"code":"Ok"}

Local

http://127.0.0.1:5000/route/v1/driving/-86.718829,33.658388;-84.90168299999999,35.135628000000004?overview=false
{"message":"No route found between points","code":"NoRoute"}

Any help will be highly appreciated.
Thanks!

**Comment by shivansh7seth** [comment]
Hi Daniel,

Any help on this will be highly appreciated,

Thanks

**Comment by danpat** [comment]
I suspect something is very messed up with your data.  In the first example:

<img width="468" alt="Screen Shot 2019-12-02 at 9 41 47 AM" src="https://user-images.githubusercontent.com/1892250/69981841-fd6cfa80-14e7-11ea-9be9-947c21d94079.png">


The demoserver says the route is 3.7km, but your local server gives >300km.  That is not right at all.

I would clear out *all* your datafiles and start again.  Based on the other ticket you posted, I suspect you may have partial/invalid datafiles that are mixed in with good ones somehow.

Start again from scratch and see if the problem persists.

**Comment by leungi** [comment]
Hi,

I'm facing similar issue, and have gone through the [docker workflow](https://github.com/Project-OSRM/osrm-backend#using-docker) three times, using different OpenStreetMap extracts from [Geofabrik](http://download.geofabrik.de/) - U.S.A., U.S. South, and Texas.

Using the same HTTP input (just different servers), I'm not able to replicate the response obtained from demo server; the demo server gives the correct output, but not personal server.

### Example
#### Demo Server
`http://router.project-osrm.org/route/v1/driving/-103.9526120,32.16099;-103.933119,32.163369?overview=false&alternatives=true`

> {"code":"Ok","waypoints":[{"hint":"wGbzhvNm84YrAAAAGQAAAAAAAACBAAAA8t7zQb0whkEAAAAA1Qc9QisAAAAZAAAAAAAAAIEAAABFTwAAPNDN-Yq86gEcz8353rzqAQAALwFHqdes","location":[-103.952324,32.160906],"name":""},{"hint":"CGfzhgtn84YAAAAAuwAAAAAAAADHBQAAAAAAABoOnEIAAAAAmXIjQwAAAAC7AAAAAAAAAMcFAABFTwAAzhbO-bLE6gFBG875KcbqAQAATxJHqdes","location":[-103.934258,32.162994],"name":""}],"routes":[{"legs":[{"steps":[],"weight":448.5,"distance":2235.1,"summary":"","duration":448.5}],"weight_name":"routability","weight":448.5,"distance":2235.1,"duration":448.5}]}

#### Personal Server
`my-server:5000/route/v1/driving/-103.9526120,32.16099;-103.933119,32.163369?overview=false&alternatives=true`

> {"code":"Ok","routes":[{"legs":[{"steps":[],"distance":271.6,"duration":39.1,"summary":"","weight":39.1}],"distance":271.6,"duration":39.1,"weight_name":"routability","weight":39.1}],"waypoints":[{"hint":"YBlAgGEZQIBWAgAAcQAAAJpPAAB9dAAAHiPPQ8lZnEJUIl1G0IWhRlYCAABxAAAAmk8AAH10AAC3BAAA7XvP-Xy76gEcz8353rzqAUQATwsSKCmm","distance":10353.719486,"name":"Buck Jackson Road","location":[-103.842835,32.160636]},{"hint":"YBlAgGEZQIDPAAAA-AEAAJpPAAB9dAAA7nwPQxp7rkNUIl1G0IWhRs8AAAD4AQAAmk8AAH10AAC3BAAA-HvP-QbF6gFBG875KcbqAUQATwsSKCmm","distance":8516.256528,"name":"Buck Jackson Road","location":[-103.842824,32.163078]}]}


Appreciate it if someone may enlighten where I may check for issue 🙏
