### ISSUE TITLE
Got ReferenceError: OSRM is not defined

### ISSUE THREAD

**Issue by bsnyh** [Project-OSRM/osrm-backend#5619]
Following api.md, I was trying to locate `node_modules/osrm/lib/binding/` and did not find it. Then, I found that I have network.osrm file ready by extracting, contracting command earlier. So, I create a .js file, using a simple example as the following:

```
var osrm = new OSRM('sweden.osrm');
var options = {
  coordinates: [[13.388860,52.517037]],
  number: 3,
  bearings: [[0,20]]
};
osrm.nearest(options, function(err, response) {
  console.log(response.waypoints); // array of Waypoint objects
});
```
When I was trying to run it using nodejs, I got a ReferenceError: OSRM is not defined. Could anyone let me know how to proceed? And where to locate `node_modules/osrm/lib/binding/`
Thank you a million.

**Comment by danpaz** [comment]
@bsnyh that's a JavaScript error, it means you're using a variable `OSRM` that isn't defined. You will need to import the OSRM module with `var OSRM = require('osrm');`, and make sure you have run `npm install osrm` to download the module.
