### ISSUE TITLE
what():  Could not find any metrics for MLD in the data. Did you load the right dataset?

### ISSUE THREAD

**Issue by bsnyh** [Project-OSRM/osrm-backend#5620]
Hi, when I was trying to run the example.cpp using Cmake, I got this strange message, saying that could not find any metrics for MLD in the data. Did you load the right dataset? 

```
$ ./osrm-example ~/Desktop/my_osrm_learning/myMap.osrm
terminate called after throwing an instance of 'osrm::util::exception'
  what():  Could not find any metrics for MLD in the data. Did you load the right dataset?
Aborted (core dumped)
```
I figured that the data have to be pre-processed to fit the algorithm MLD. I was wondering how to do that? What I did is building from the source to get this osrm-* binaries, and then using osrm-extract and osem-contract commands to preprocess the .osm.pbf file. After building osrm-example using Cmake, run the command ./osrm-example. Did I miss something? 

 Any comments are greatly appreciated.

**Comment by danpat** [comment]
There are two different pipelines, CH and MLD.

For MLD, you need to do `osrm-extract`, then `osrm-partition`, then `osrm-customize`.  Doing `osrm-extract`, then `osrm-contract` generates a CH dataset.

**Comment by bsnyh** [comment]
Thank you for your reply. It works. I updated the code as the following, 
```
const auto nodes = route.values["nodes"].get<json::Number>().value;
const auto weights = route.values["weights"].get<json::Number>().value;
const auto speed = route.values["speed"].get<json::Number>().value;

std::cout << "Distance: " << distance << " meter\n";
std::cout << "Duration: " << duration << " seconds\n";
std::cout << "Nodes: " << nodes << " \n";
std::cout << "Weights: " << weights << " \n";
std::cout << "Speed: " << speed << " \n"; 
```

I got the following error: 
```
terminate called after throwing an instance of 'mapbox::util::bad_variant_access'
  what():  in get<T>()
Aborted (core dumped)
```
Any suggestions or did I miss anything?

**Comment by meizhuwang** [comment]
I have the same error as above when doing table service
@bsnyh have you solved it?

**Comment by danpat** [comment]
I believe the problem is that you're not accessing valid members of the `route` object - take a look at a serialized JSON output (and take a look at the API docs) at http://project-osrm.org/docs/v5.22.0/api/#general-options to see what object members you can expect. 

I don't think you'll find "nodes", "weights", and "speed" properties on the "route" object, and if you do, at least "nodes" and "weights" will be arrays, not a Number.

**Comment by meizhuwang** [comment]
Hi Daniel, Thank you!
