### ISSUE TITLE
Compute route between two points based on a fixed travelling time

### ISSUE THREAD

**Issue by StefanoFioravanzo** [Project-OSRM/osrm-backend#5621]
Hi, is there a way to compute a path between two fixed points A and B given a fixed time, say 15 minutes? So this is not best path, but the most reasonable (or a set of) path(s) that would take that time.
Is this achievable with OSRM? Thank you!

**Comment by danpat** [comment]
Are you trying to ask "find me all paths that take 15 minutes"?  If so, then OSRM doesn't have a way to answer this question.  The core routing algorithms are based on Dijkstra - its goal is to find the *shortest* path.

To find all paths of length N, you would probably want to do a [breadth first search](https://en.wikipedia.org/wiki/Breadth-first_search) instead, and potentially permit loops if those are acceptable in your solution paths.
