### ISSUE TITLE
Running osrm-backend on doc with HTTPS

### ISSUE THREAD

**Issue by jbroomer** [Project-OSRM/osrm-backend#5623]
I have done a lot of research but haven't found exactly what I am looking for. Could someone point me to where I may find instructions on how to run my docker service over HTTPS so that my production site can make requests to it.

Thanks!:)

**Comment by systemed** [comment]
osrm-routed doesn't support https (and isn't a production webserver in any case), but you can put it behind an Apache proxy or similar:

````
<VirtualHost *:443>
DocumentRoot "/srv/my.awesome.routing.server/"
ServerName my.awesome.routing.server
ProxyPreserveHost On
ProxyRequests Off
ProxyPass / http://localhost:5000/
ProxyPassReverse / http://localhost:5000/
[...]
````
