### ISSUE TITLE
how to prevent accidental longitude and latitude flips?

### ISSUE THREAD

**Issue by bsnyh** [Project-OSRM/osrm-backend#5627]
This is a really interesting trick, however, I did not quite understand how. Moreover, I'm confused about the following template function. 

```
template <class T> Coordinate(const T &coordinate) : lon(coordinate.lon), lat(coordinate.lat)
    {
        static_assert(!std::is_same<T, Coordinate>::value,    // if T is the same type as Coordinate, then issue error message  
                      "This constructor should not be used for Coordinates");
        static_assert(std::is_same<decltype(lon), decltype(coordinate.lon)>::value,  // decltype is a keyword used to query the type of an expression
                      "coordinate types incompatible");
        static_assert(std::is_same<decltype(lat), decltype(coordinate.lat)>::value,
                      "coordinate types incompatible");
    }
```

For the first static_assert, what does it mean? For my understanding, it means if T is the same type as Coordinate, then issue an error message. But why T can not be the same type as Coordinate then?

**Comment by bsnyh** [comment]
@danpat any comments are greatly appreciated.

**Comment by SiarheiFedartsou** [comment]
@bsnyh as I understand it is needed if e.g. you have your own `Coordinate` class and want to copy it OSRM's `Coordinate`. This first assert guarantees that it is not used as copy constructor of OSRMs `Coordinate` itself.
