### ISSUE TITLE
Route leaving and immediately re-entering highway

### ISSUE THREAD

**Issue by geoneutrino** [Project-OSRM/osrm-backend#5634]
I'm running OSRM docker (backend and frontend) with MLD and car profile, german dataset, installed 5 weeks ago.
Calculating a route sometimes unnecessarily leaves and reenters the highway at some exits. E.g. calculating a route from Heidelberg to Karlsruhe has this effect at Bruchsal (https://www.openstreetmap.org/#map=17/49.14659/8.55846) and Karlsruhe Durlach ( https://www.openstreetmap.org/#map=18/49.00257/8.44952 ) but not at the other exits

![OSRM1](https://user-images.githubusercontent.com/48556918/71013499-1208df80-20f1-11ea-8a26-aa39fdffa130.PNG)

with text instructions

![OSRM2](https://user-images.githubusercontent.com/48556918/71013511-1634fd00-20f1-11ea-9f6f-22207b2813c5.PNG)

This happens in my system and on official routing.openstreetmap.de instance 
https://routing.openstreetmap.de/?z=11&center=49.200327%2C8.561096&loc=49.409358%2C8.694724&loc=49.006870%2C8.403420&hl=en&alt=0

but not on demo server
http://map.project-osrm.org/?z=11&center=49.200327%2C8.561096&loc=49.409358%2C8.694724&loc=49.006870%2C8.403420&hl=en&alt=0

Is this an error or an effect avoidable e.g. during data calculation ?

**Comment by danpat** [comment]
The connectivity on the network looks ok - so I'd guess that it's coming down to calculated road speeds.

The OSRM demoserver imports average traffic data from Mapbox, so poor speed estimates based on OSM tag often get overwritten, leading to generally more sensible results.

One way to debug this is to use the `/debug/` URL on your demoserver, after changing this line:

https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/debug/index.html#L128

to point to your `localhost` URL.  You can then browse to this location, and examine the speeds that are assigned to roads.

My guess would be that the bypases you're seeing are being marked as slightly faster.  The roads are broken into quite a few parts here, I don't hve time to really dive in, but I'd guess that either:

  1. Some small section is missing a `maxspeed` tag or something, leading to it being a bottleneck on the main highway
  2. The `width` tags are applying unexpected multipliers to the `maxspeed`, leading to the detour being considered faster.

**Comment by geoneutrino** [comment]
All segments have maxspeed 120, both main highway and the motorway_link
One section of the main highway has width 11.5, all others not

The calculated speeds vary between 95-97 on both, minimal faster on the motorway_link (so the question might be if average speed calculation on *_link can be faster than the main highway with same speed limit)

![grafik](https://user-images.githubusercontent.com/48556918/71101821-a6d61080-21b7-11ea-8d7f-5d45fa6f2bad.png)

![grafik](https://user-images.githubusercontent.com/48556918/71101863-b5242c80-21b7-11ea-8c2f-0e5c5cc1cc67.png)

![grafik](https://user-images.githubusercontent.com/48556918/71101886-bfdec180-21b7-11ea-98f4-d40341b301ff.png)

![grafik](https://user-images.githubusercontent.com/48556918/71101913-ccfbb080-21b7-11ea-80ca-bd40002ca418.png)

**Comment by danpat** [comment]
Hmm.  I suspect that it's going to come down to a very tiny ETA difference.  You can try adding a middle waypoint to force the route to follow the main highway - then take a look at the precise `duration` of the trip - my guess is that it's going to be very very close to the other path, and the error here may come down to rounding errors.

**Comment by geoneutrino** [comment]
you are right. Original route has duration 2480.2 with the middle waypoint it is 2480.3

 (?z=18&center=49.003408%2C8.451131&loc=49.409358%2C8.694724&loc=49.003073%2C8.450590&loc=49.006870%2C8.403420&hl=en&alt=0)

**Comment by frodrigo** [comment]
The route is now straight.
