### ISSUE TITLE
Adding paths using GPS data

### ISSUE THREAD

**Issue by Nerdyvedi** [Project-OSRM/osrm-backend#5641]
I have tracked GPS data of few cyclists. More often then not they travel on a path not shown on OSM. Is there an efficient way to find if there is a road actually present on the path taken by them and then add it to OSM ?

**Comment by danpat** [comment]
You can use the `/match` service to see if a trace snaps to an existing road.  If the match fails, or the `confidence` is very low, then the trace is a candidate for manual review to see if OSM has a path there.

OSRM doesn't have any ability to automatically generate geometry to be added to OSM - doing that is usually a bit contentious anyway.  There's a whole wiki page dedicate to automated edits: https://wiki.openstreetmap.org/wiki/Automated_edits
