### ISSUE TITLE
How to forbid to start a way half way through?

### ISSUE THREAD

**Issue by wolfAle** [Project-OSRM/osrm-backend#5645]
Hi all :-)

I've been using OSRM for a while now but I'm facing an issue for which I don't seem to find a way out, therefore here I am asking for help.

My use case is for tracking and routing of ski sessions on ski slopes and lifts. It's working for the most of it but my problem is in some particular cases with the routing.
Let's say that:
- I'm currently standing in a slope
- In the exact same coordinates there's a lift too, it's over my head. I'm not close to neither the starting or ending point of the latter, let's say half way. 
- I request a routing to reach the top/ending point of the lift

Because the engine doesn't now whether I'm standing on the slope or sitting on the lift, it assumes that I'm in the second case and it tells me to stay on the lift and proceed further till the end.

What I'm trying to achieve is **to find a way to tell the engine that it's not possible to enter a way of type "aerialway" but from the starting or ending point**. 
Can you help me in anyway with this?

Thanks for your help,
Alessandro

**Comment by systemed** [comment]
Does `is_startpoint` do what you want? (See https://github.com/Project-OSRM/osrm-backend/blob/714719c3776c5985a8881cba32f48f8a4de5a70a/profiles/lib/way_handlers.lua#L74 .)

**Comment by wolfAle** [comment]
Hi @systemed :-)

thanks for your reply. 
I tried with `is_startpoint` but from my understanding that's something you can only set on the whole way, not on a single node, and it would exclude the whole way from being a starting point.

In my case what I want to achieve is that a user can start its journey on a lift, but only from the initial node, not from the intermediate ones.

Alessandro

**Comment by danpat** [comment]
@wolfAle If you set "is_startpoint=false" on the way that maps the chairlift, and your input coordinate is near the lower or upper stations, and the ski-run ways connect to the bottom of the lift, then I think it will do what you expect.  The end of the ski run ways is the same location as the start of the chairlift ways.

**Comment by wolfAle** [comment]
Mate, you made my day! 😃 
I thought about that before but I didn't realised that the lifts would be accessible anyway through the common initial/final node with the ski-run. I run a few tests and it seems to work like a charm. 

Just waiting for confirmation from the customer about the possibility of edge cages like, for instance, a lift (one whole way) with an intermediate station where you can jump on, but without any ski-run connected to it. 
In that case we would need to split the lift in two ways.

Thanks for your help!

Alessandro
