### ISSUE TITLE
osrm-extract seems to be removing pieces of ways

### ISSUE THREAD

**Issue by Micrococonut** [Project-OSRM/osrm-backend#5648]
I have written a custom extraction script to exclusively route users along state and federal highways. Essentially anything with a trunk highway tag or above or any road with a state ref tag is included in the navgraph. It works great in most cases, but I have found a section of highway and road where some pieces are being left out.
<img width="911" alt="Screen Shot 2020-01-20 at 5 57 23 PM" src="https://user-images.githubusercontent.com/9060561/72767747-4ec56c00-3bb2-11ea-917c-7b25ba422a35.png">
<img width="472" alt="Screen Shot 2020-01-20 at 6 32 19 PM" src="https://user-images.githubusercontent.com/9060561/72768045-39047680-3bb3-11ea-9609-bd13654081a2.png">
Can anyone here think of why these sections might be excluded? My extraction script modification is very simple. It is just the default car.lua profile with these lines added 
`if (not data.highway or (data.highway ~= 'motorway'
                            and data.highway ~= 'trunk'
                            and data.highway ~= 'escape'
                            and data.highway ~= 'toll_gantry'
                            and data.highway ~= 'motorway_junction'
                            and data.highway ~= 'motorway_link'
                            and data.highway ~= 'trunk_link'
                            and data.highway ~= 'primary_link'
                            and data.highway ~= 'secondary_link'
                            and data.highway ~= 'tertiary_link'))
  then
    return
  end` 

This works on almost every other road I've examined, but select few are missing pieces of their ways for no discernable reason. We are missing segments of individual ways, not entire ways and that is very confusing for me.

**Comment by thucnc** [comment]
It is weird but I got the same symptom occasionally before. Our daily extraction sometimes makes unexplainable routes which will disappear in next day(s). Hope we have the same root cause.

**Comment by Micrococonut** [comment]
I don't know exactly where exactly I went wrong, but the issue was caused by some sloppy changefiles I had made and been merging in.
