### ISSUE TITLE
Does OSRM match uses live traffic speeds?

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5651]
Hello,
Does OSRM match service uses live traffic speeds (segment speed file data) for calculating the match service duration? Or it uses default speeds from lua profile?

Thanks

**Comment by danpat** [comment]
If you supply traffic speeds, then they replace any speed values that originally came from Lua.  The duration values on graph edges are replaced.  This means all services will see the traffic speed values you supply instead of the Lua profile values.

**Comment by safe-bug** [comment]
Thank you for your instant reply @danpat , and does it affect the route that match service return? (Do it do the routing between points, like the route service?)

**Comment by danpat** [comment]
Possibly a little bit - it will depend on how ambiguous your input trace is.  In some cases, traffic-data changes might change the path that the routing engine considers more likely.

For straightforward matches (no ambiguity) I wouldn't expect much change.

**Comment by safe-bug** [comment]
Thanks @danpat
