### ISSUE TITLE
Distance inconsistent in local configured server vs Demo Server (v5.22.0)

### ISSUE THREAD

**Issue by pavan612** [Project-OSRM/osrm-backend#5652]
**Demo Server**

Request
https://router.projectosrm.org/route/v1/driving/78.40010500000001,17.440206;79.9906015,15.94938930000001?overview=false

Response
{"routes":[{"legs":[{"summary":"","weight":18060.8,"duration":17752.2,"steps":[],"distance":320917.8}],"weight_name":"routability","weight":18060.8,"duration":17752.2,"distance":320917.8}],"waypoints":[{"hint":"BBd4g14XeIMSAAAAEAAAADQBAAArAwAAQAxjQCeZNkCaqmhCaRMZQwkAAAAIAAAAmwAAAJYBAABnYAAAAkqsBAseCgFpSqwEzh0KAQIAPw2joOp0","distance":12.857902449948151,"name":"","location":[78.400002,17.440267]},{"hint":"kPpBgDvmaIMzAAAAMgAAAHYQAAAiEQAA2ysVQur4DUJTEz5F8AhGRTMAAAAyAAAAdhAAACIRAABnYAAAwpDEBHFi8wBKj8QETV7zADkADxKjoOp0","distance":124.0083127367367,"name":"","location":[79.990978,15.950449]}],"code":"Ok"}

**Local Configured Server**

Request
http://localhost:5000/route/v1/driving/78.40010500000001,17.440206;79.9906015,15.94938930000001?overview=false

Response 
{"code":"Ok","routes":[{"legs":[{"steps":[],"distance":285594,"duration":13857.8,"summary":"","weight":13857.8}],"distance":285594,"duration":13857.8,"weight_name":"routability","weight":13857.8}],"waypoints":[{"hint":"yShFgNsoRYAHAAAABwAAAIQAAABZAQAAQAxjQCeZNkCaqmhCaRMZQwcAAAAHAAAAhAAAAFkBAACQAwAAAkqsBAseCgFpSqwEzh0KAQIAPw26up8e","distance":12.857902,"name":"","location":[78.400002,17.440267]},{"hint":"dmYGgAipNoAhAAAAIAAAALYKAAAjCwAA2ysVQur4DUJTEz5F8AhGRSEAAAAgAAAAtgoAACMLAACQAwAAwpDEBHFi8wBKj8QETV7zADkADxK6up8e","distance":124.008313,"name":"","location":[79.990978,15.950449]}]}

Demo Server gives distance of 320.9KM
Local Server giver distance of  285.5KM

It is just an example there are so many cases happening like this.
I had used docker to configure local server with Asia, India Data with car profile.

**Comment by systemed** [comment]
See https://github.com/Project-OSRM/osrm-backend/wiki/Frequently-Asked-Questions

(Can we get a link to the FAQ in the "New issue" page please?)
