### ISSUE TITLE
3 point car route in Munich (Germany) not found

### ISSUE THREAD

**Issue by cyril23** [Project-OSRM/osrm-backend#5654]
### Example URL
http://router.project-osrm.org/route/v1/driving/11.55291,48.143314;11.537716,48.14476;11.544544,48.147377?overview=false

### actual response
 `{"code":"NoRoute"}`

(time: Thu Jan 23 2020 12:49:03 GMT+0100)

### expected response
a car route between the three points, similar to Google: https://www.google.com/maps/dir/48.143314,11.55291/48.14476,+11.537716/48.147377,+11.544544/@48.147377,11.544544
![image](https://user-images.githubusercontent.com/5645872/72982096-97fa0380-3dde-11ea-86a5-b5f4c17097f2.png)

**Comment by danpat** [comment]
You should add `continue_straight=false` to your request.

What's happening is that when you arrive at the midpoint, the `continue_straight=true` default causes the route to continue south then west toward the building.  The road splits into two sections that are oneway (one going into the building, and one going out).

<img width="904" alt="Screen Shot 2020-01-23 at 8 24 32 AM" src="https://user-images.githubusercontent.com/1892250/73003134-f6f95180-3db9-11ea-9954-fba846a9f6d3.png">
 
OSRM will only do u-turns at the end of a road (like a cul-de-sac), but in this case, you can't do a u-turn when you get to the end, as the road is marked as oneway, so you're stuck.

**Comment by cyril23** [comment]
Thanks, that worked perfectly.
