### ISSUE TITLE
Match service: many gaps with dense GPS coordinates

### ISSUE THREAD

**Issue by JackCaster** [Project-OSRM/osrm-backend#5657]
I noticed that the OSRM matching service quality deteriorates when I supply dense GPS coordinates.

I collected GPS coordinates when driving at a sampling period of 25 s. Using OSRM matching I could recover the traveled path perfectly (i.e., single match with high confidence). I am running `osrm-routed` (v5.22.0) from the official docker image ([link](https://hub.docker.com/r/osrm/osrm-backend/)) using the `massachusetts-latest.osrm` map and the MLD algorithm. EDIT: these are the parameters sent to the server:
- 'steps':'true'
- 'gaps':'ignore'
- 'tidy':'false'
- 'annotations':'true'
- 'overview':'full'
- 'geometries':'geojson'

Then, I up-sampled the GPS coordinates to a higher sample rate. Now, the matching is poor and with many gaps. Do you know if this behavior is expected? If not, what could I do to improve the matching?

Please, have a look at the results I got here: https://codepen.io/jackcaster/pen/zYxQpyL . The blue marks are the raw GPS coordinates. The blue line is the matched path using the raw coordinates. The red dots are the up-sampled GPS coordinates. Finally, the darker, thicker red lines are the matching from these up-sampled coordinates. You can see that these path is broken in four pieces.

**Comment by danpat** [comment]
You're adding noise to an otherwise clean signal.

The GPS points you have are realistic - they measure an actual position.  When you're upsampling, you're assuming a straight-line between those points, but often the roads curve.  Your upsampled points have a much lower fidelity than the real GPS points, and they're failing to match.

The upsampled points (red) across this oval are pretty good demonstrations of this:

<img width="426" alt="Screen Shot 2020-01-29 at 1 42 18 PM" src="https://user-images.githubusercontent.com/1892250/73400128-616c2f00-429d-11ea-985c-aed08cd8e9f3.png">

The red points are too far from the actual road to be considered good candidates.

The other splits are similar, although a little bit less aggregious.

You have two options:

  1) Don't upsample - map-matching is already handling fidelity for you.
  2) Increase the "radiuses=" parameter for your upsampled points, because you don't actually know that they're on the actual road or not.

**Comment by JackCaster** [comment]
That's what I thought as well, that is up-sampling is creating a numerous unrealistic locations. I tried to increase the radius and it works---for this particular case---but I have other trips for which the radius does not help (the road network is too complex I believe).

I am looking for a way to up-sample the GPS coordinates to harmonize them with other data coming from other sensors in the car (e.g., speed, acceleration). What I am interested in the most is the metadata on road name, type etc. for each GPS coordinate. Do you know how I can go about it? 

Like, I am wondering how I can up-sample the GPS coordinates based on the matched path. To do so, I would need a way to pull out the timestamps for each segment in the matching.

**Comment by danpat** [comment]
I think all you need to do is perform your up-sampling in a different order.  Do the map-matching first using only real GPS positions, then calculate interpolated points along the matched geometry to align with your other sensor data.

Something like https://postgis.net/docs/ST_Segmentize.html would be a first approximation.  If you want to get fancy and handle changes in travel speed (assuming your map data has reasonable values), you can also look at the `annotations=duration` parameter to matching which will give you more detail about how long it takes to traverse the geometry along the matched path.

**Comment by JackCaster** [comment]
> If you want to get fancy and handle changes in travel speed (assuming your map data has reasonable values), you can also look at the `annotations=duration` parameter to matching which will give you more detail about how long it takes to traverse the geometry along the matched path.

I would like to get the timestamp for each coordinate in the geometry of the match. In this way the would could get a nice interpolation. However, I do not understand how to compute the time to travel the path. 

In the example I posted, the geometry of the match is composed by 321 coordinates. Then I have 25 legs (i.e., one leg between each supplied GPS coordinate that has been matched, not null). The annotation in each leg contains nodes instead of coordinates, and the number of nodes is 345---more than the number of coordinates in the geometry of the match. Some nodes are replicated and I do not understand why (the replications are marked with a star):
```
legs[0]['annotation']['nodes'] = [67492691, 67497280, 67443551, 67390081, 67467697, 67424684, 67493482, 67311374, 74131027, *74116852*, *74046500*]
legs[1]['annotation']['nodes'] = [*74116852*, *74046500*, 73937979, 73962411, 74200386, 74103606, 73968588, 73961950, 74001317]
```
It seems like the two last nodes of one leg and the last two of the next leg overlap. However, I would expect the duration in each segment to be the same then, but it is not
```
legs[0]['annotation']['duration'] = [2.4, 5.6, 1.6, 7.7, 6.6, 6.2, 1.5, 0.8, 4.6, *0.2*]
legs[1]['annotation']['duration'] = [*6.1*, 10.7, 5.7, 1.8, 5, 3.2, 5.5, 0.2]
```
And anyway, even by removing the duplicates the number of nodes do not match the number of geometry coordinates. 

How could I make use of `annotation=duration` to compute the timestamp at each coordinate in the path?

I understand that this may not be related to this issue any longer. If this has become out of topic I will close and post elsewhere.
