### ISSUE TITLE
How can I specify that it should continue across the road?

### ISSUE THREAD

**Issue by serbasii** [Project-OSRM/osrm-backend#5658]
A long route is being created by osrm starting in the yellow circle. But the vehicle crosses the road and continues to service. Can we proceed to OSRM that it should continue across the road?

![image](https://user-images.githubusercontent.com/6322619/73399002-87262200-42f7-11ea-8bc4-1b337f69e0ad.png)

**Comment by danpat** [comment]
Without seeing your actual map data, it's hard to know - but is there a connecting road inside the yellow circle?  If there is no join between those divided roads, OSRM will have no choice but to find another way.

If it's possible to cross the divided road at that point, you need to map that.

**Comment by serbasii** [comment]
there is no connecting road in osm file, so I want to force it to cross the other side. Maybe editing on osm file. Is it possible?

zoomed image of no link:
![image](https://user-images.githubusercontent.com/6322619/73424044-e22f3780-433e-11ea-8785-9ce24c246ca8.png)

**Comment by danpat** [comment]
Yes - you will need to add a connecting road - without it, OSRM does not know that you can travel between the sides of the divided road.

How to add that road is beyond the scope of OSRM.  If your data is from OSM itself, you can go to https://www.openstreetmap.org/ and edit the map directly, then fetch a fresh extract for use with OSRM.
