### ISSUE TITLE
Match Service

### ISSUE THREAD

**Issue by AlessandroMFerreira** [Project-OSRM/osrm-backend#5662]
Hi,

I have build my own OSRM server and i'm trying to use Match service, but when i call it from my application the google chrome console shows an error:

Routing error:

responseURL: "http://localhost:5000/match/v1/driving/-18.917308,-49.412377;-18.917425,-49.410578?overview=false&alternatives=true&steps=true"

response: "{"code":"InvalidQuery","message":"Query string malformed close to position 76"}"
responseText: "{"code":"InvalidQuery","message":"Query string malformed close to position 76"}"

It's my first time using it. Maybe this is some problem when a settiing up a server? any help will be welcome.

**Comment by jcoupey** [comment]
The position 76 points to the `alternatives` option, which happens to be valid for `route` requests, not `match`.
