### ISSUE TITLE
Backup and restore OSRM

### ISSUE THREAD

**Issue by umar18** [Project-OSRM/osrm-backend#5664]
Hello,
Sorry if it sounds stupid !! I have successfully deployed OSRM on my Linux environment, now i want to setup another machine as backup. I don't want to setup the new machine from scratch and wait for another 2 to 3 days. Can i make a backup of the existing docker and restore on the new machine ??

**Comment by danpat** [comment]
Make a copy of all the `.osrm*` files that were generated - you should be able to transfer those over an run `osrm-route yourfile.osrm` just fine.
