### ISSUE TITLE
RAM: peak bytes used: 11527680000

### ISSUE THREAD

**Issue by gabrielibis** [Project-OSRM/osrm-backend#5665]
I'm trying to run osrm in a hp server with 64GB of RAM. I use just brazil map (800MB). But when I run `docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/brazil-latest.osm.pbf`
I'm getting the following result:
`RAM: peak bytes used: 11527680000`
What can I do to solve the problem?

**Comment by jcoupey** [comment]
Unless you get another explicit error message, this is not a problem, just a report of memory usage during the extraction phase.
