### ISSUE TITLE
Compilation errors only for node bindings 

### ISSUE THREAD

**Issue by lgrd** [Project-OSRM/osrm-backend#5667]
Hi everybody, 

I use OSRM in a node app. I'm used to build OSRM binaries from the sources so as to create graphs. But I'm used to download node bindings with npm. 

But now, I would like to build the bindings from the sources. 

I'm using: 
- Centos 7
- gcc 8.3.1
- make 4.2.1
- osrm sources 5.20.0
- node source 12.14.1

When I build binaries, it works. But when I build the bindings (adding `-DENABLE_NODE_BINDINGS=ON` in the cmake options), I have errors during compilation. 

I've tried this DockerFile: 

```
FROM centos:7.7.1908

### MAJ
RUN yum -y update
RUN yum -y upgrade
RUN yum install -y yum-utils centos-release-scl epel-release
RUN yum-config-manager --enable rhel-server-rhscl-7-rpms

### Utilities
RUN yum -y install wget 

### NodeJS dependencies
RUN yum install -y python-2.7.5

### Recent tools
RUN yum -y install devtoolset-8

### NodeJS installation from sources 
WORKDIR /home/docker/nodejs
RUN wget -O node-v12.14.1.tar.gz "https://nodejs.org/dist/v12.14.1/node-v12.14.1.tar.gz"
RUN tar -xzf /home/docker/nodejs/node-v12.14.1.tar.gz
RUN scl enable devtoolset-8 bash && export CXX=/opt/rh/devtoolset-8/root/usr/bin/g++ && cd node-v12.14.1 && ./configure && make -j4 && make install

### OSRM dependencies
RUN scl enable devtoolset-8 bash && yum -y install cmake3 zlib-devel

### OSRM installation
WORKDIR /home/docker/osrm
RUN wget https://github.com/Project-OSRM/osrm-backend/archive/v5.20.0.zip && unzip v5.20.0.zip -d ./osrm-backend
WORKDIR /home/docker/osrm/osrm-backend/osrm-backend-5.20.0/build
RUN scl enable devtoolset-8 bash && export CC=/opt/rh/devtoolset-8/root/usr/bin/gcc && cmake3 .. -DCMAKE_BUILD_TYPE=Release -DENABLE_MASON=ON -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-8/root/usr/bin/g++ && make && make install

### Node bindings building
WORKDIR /home/docker/osrm/osrm-backend/osrm-backend-5.20.0/
RUN npm install --build-from-source 
WORKDIR /home/docker/osrm/osrm-backend/osrm-backend-5.20.0/build
RUN scl enable devtoolset-8 bash && export CC=/opt/rh/devtoolset-8/root/usr/bin/gcc && cmake3 .. -DCMAKE_BUILD_TYPE=Release -DENABLE_MASON=ON -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-8/root/usr/bin/g++ -DENABLE_NODE_BINDINGS=ON && make 

```

This is the output end of the `make` step during the building of the bindings: 
```
...
cc1plus: some warnings being treated as errors
make[2]: *** [src/nodejs/CMakeFiles/node_osrm.dir/node_osrm.cpp.o] Error 1
make[1]: *** [src/nodejs/CMakeFiles/node_osrm.dir/all] Error 2
make: *** [all] Error 2
```

The warning was: 
-` warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]`

I've seen some errors like: 
- `osrm-backend-5.20.0/include/nodejs/node_osrm_support.hpp:684:59: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)`
- `osrm-backend-5.20.0/build/src/nodejs/node/v12.14.1/include/v8.h:10004:16: error: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Werror=cast-function-type]`
- `osrm-backend-5.20.0/include/nodejs/node_osrm_support.hpp:1472:94: error: no matching function for call to 'v8::Value::NumberValue()`

Maybe, I'm missing something like an option, or something else, to build the bindings. Do you have an idea ?

**Comment by danpat** [comment]
We probably need to make changes to adapt to Node 12 - the last one properly tested was Node 10.

Try downgrading Node to 10.x and see if that works.

**Comment by lgrd** [comment]
Thanks for your help ! 

I've tried with NodeJS 10.13.0. But I have the same errors. And I've tried on debian:buster-20200130 in docker and I've got the same errors. 

Do you have an idea about something missing ?

**Comment by danpat** [comment]
Not sure - I can successfully build the latest OSRM code against Node 10 but not Node 12 - I get the same error as you above for node 12, but node 10 builds cleanly.

**Comment by lgrd** [comment]
So something goes wrong in my container...
When you build it, do you use the same options ? same steps (npm install, cmake, make...) ? 
Did you use on centos, debian ? ^^ 
What is your exact version of node 10 ?

**Comment by danpat** [comment]
I'm on macOS.

```
$ nvm use 10
Now using node v10.18.0 (npm v6.13.4)
$ npm install
....
$ mkdir build
$ cd build
$ cmake -DENABLE_NODE_BINDINGS=ON ..
...
$ make node_osrm
...
success
```

**Comment by lgrd** [comment]
I didn't kown the node_osrm option for make. 

I've tried with your node and npm versions. I didn't work. 

I have:
- make 4.2.1
- cmake 3.14.6
- gcc 8.3.1

Would you give me your version of make, cmake and gcc ? 

Thanks for your help ! :)

**Comment by lgrd** [comment]
I've tried with gcc 6.3.1 and it works ! 

I should have tried it before... Thanks for your help !!
