### ISSUE TITLE
Missing steps in generated route

### ISSUE THREAD

**Issue by aarzhou** [Project-OSRM/osrm-backend#5668]
The route function does not return full steps. Some steps might be missing.

Same problem is also found OSRM demo site. For example:
http://map.project-osrm.org/?z=18&center=40.033945%2C-76.311510&loc=40.033593%2C-76.310943&loc=40.034439%2C-76.311928&hl=en&alt=0

The 2nd step is actually turning right onto Saint Joseph street, then another step missing "Turn left onto West Filbert Street"

I also checked OSM map source and the map is correct. The middle segment is "Saint Joseph", not "West Filbert"

![image](https://user-images.githubusercontent.com/3170768/74116908-96bd2a80-4b83-11ea-89b4-5bccde00e07a.png)

**Comment by danpat** [comment]
This looks like a bug in instruction collapsing.  Without looking at the code, my guess is that the left turn is being classes as "obvious" because it's the only way you can go when you're heading north-east.  The left and right turns get merged together, and it looks like we're picking the wrong road name in the merged result in this case.

**Comment by aarzhou** [comment]
Thanks very much for the quick reply.

Yes. there is no need to show the left turn because it is the only way to go.

Could you please let me know when it will be fixed, or kindly tell me where to change in the source code so that I can compile by myself

Thanks

**Comment by prusswan** [comment]
@danpat is there any parameters that can be used to adjust/disable instruction collapsing? Based on this issue and the comment [here](https://github.com/Project-OSRM/osrm-backend/issues/3281#issuecomment-333471023) we probably want to disable instruction collapsing to prevent steps being skipped.
