### ISSUE TITLE
OSRM giving diffrent results

### ISSUE THREAD

**Issue by shivankgtm** [Project-OSRM/osrm-backend#5670]
On calling API  I am getting a 2x2 matrix. when I put the same coordinates with some more co-ordinates like this

it gives me expected 4x4 matrix. the issue is it's giving different distance(durations) matrix for points 78.4444076,11.6000205;78.5929274,11.5958152

**Comment by jcoupey** [comment]
> 78.4444076,11.6000205

Seems like you just have your coordinates mixed up in the second request, as the above longitude and latitude are used for different locations. As a result your two requests share no common location.
