### ISSUE TITLE
Erro in load page (SSL_ERROR_RX_RECORD_TOO_LONG)

### ISSUE THREAD

**Issue by uilll** [Project-OSRM/osrm-backend#5672]
Linux Ubuntu 18.04 (bionic)

Hello guys, my test server is working in http perfectly, but when I put in https, SSL, it is not working, showing this error: SSL_ERROR_RX_RECORD_TOO_LONG

The SSl certificate is installed and according to the SSLlabs website it is functioning normally, with only a few caveats. "This server supports TLS 1.0 and TLS 1.1. Grade capped to B."
https://www.ssllabs.com/ssltest/analyze.html?d=my_server

I'm new to SSL and OSRM certification.

But here's the configuration codes for NGINx

```
upstream osrm {
  server 0.0.0.0,5000;
  # server 127.0.0.1:443;
}

server {
    listen 443 ssl;
    ssl on;
    ssl_certificate / etc / letsencrypt / csr /;
    ssl_certificate_key / etc / letsencrypt / keys /;
    server_name my_server_name;
    proxy_ssl on;
    proxy_ssl_certificate /etc/letsencrypt/live/my_server_name/fullchain.pem;
    proxy_ssl_certificate_key /etc/letsencrypt/live/my_server_name/privkey.pem;

location / mypath {
        proxy_pass https: // my_server_IP: 5000;
        proxy_set_header Host $ https_host;
    }
````

I've done a search for similar errors, I found some, but it didn't solve my problem. Can someone help me?

**Comment by danpat** [comment]
This problem is nothing to do with OSRM, it's a mis-configuration or outdated version of the SSL libraries on your nginx server.

Just google "SSL_ERROR_RX_RECORD_TOO_LONG" and you'll find lots of articles on it.
