### ISSUE TITLE
Disallow u-turn at intersection

### ISSUE THREAD

**Issue by alinazari95** [Project-OSRM/osrm-backend#5673]
Hi, i need to customize car.lua for did not allow u-turn at intersection like below:
![Screenshot (121)](https://user-images.githubusercontent.com/57067038/74603955-65d27d80-50ce-11ea-9a1a-cbe2ad5a41b1.png)

i solve this problem by using Turn penalty data file but it is just accept 3 osm_id while for some intersection need more than 3 node to disallow u-turn.
how do i disallow u-turn at some intersection with more than 3 node?
thanks

**Comment by ben-hudson** [comment]
Hi! I had the same question. Due to the way OSRM builds it's routing graph, it doesn't see this route as two u-turns, but rather as 4 left hand turns.

#4368
