### ISSUE TITLE
Penalties in profile

### ISSUE THREAD

**Issue by counlin** [Project-OSRM/osrm-backend#5675]
Hello everyone,
I just started using OSRM and after reading trough the docs (at least what I have found), I need help with configuring the profile. In particular, I am completely lost about the penalties that I can add to the profile in order to account for traffic lights, turns, etc.

I am basing all my questions on the `car.lua` profile.

So here goes:
1) In relation to the `u_turn_penalty` , `traffic_light_penalty` , and `turn_penalty` what exactly do these values mean? 
I found a comment in the profile `testbot.lua` where it says that `traffic_light_penalty` is in seconds. Is it true? An if it is, is this time in seconds added to the duration of segments/turns containing a traffic light then? (if I understood the `process_turn` correctly, it adds these values to the duration of a turn).

2) These penalties effectively modify the weight of every edge of the shortest path? 
I mean, when using `time` as objective, I guess the weight is the duration, right? But when using `routability` , the weight is not only the duration.

3) This is not completely related to penalties, but is somewhat. What does `turn_bias` stand for and how does it relate to the turn penalties?

If there are places where I can find this information, please let me know. I read the full document in 
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md
but could not get all the information I needed.

Thanks,

**Comment by wangyoucao577** [comment]
I have a doc [How OSRM Calculate Weight and Duration](https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/how_osrm_calculate_weight_and_duration.md) may answer some of your questions.

**Comment by GitBenjamin** [comment]
@wangyoucao577 
when we use **routability**, can we consider both duration and distance?
