### ISSUE TITLE
bike profile routes on highway=construction + access=no

### ISSUE THREAD

**Issue by Luzandro** [Project-OSRM/osrm-backend#5677]
Hi,

[this bridge](https://www.openstreetmap.org/way/10657323/history) was deleted by a user in order to get OSRM to ignore it - which worked, but was a rather radical solution, so it was reverted and the bridge specified as highway=construction with access=no. While it's still ignored for cars, cyclists and pedestrians are suddenly routed over it again? At first I thought the underlying data is outdated, but this doesn't make sense if it was already ignored in the time the bridge was deleted.

**Comment by maraf24** [comment]
It seems to work correctly now.
