### ISSUE TITLE
[libOSRM] get coordinate by node id

### ISSUE THREAD

**Issue by HumamHelfawi** [Project-OSRM/osrm-backend#5678]
Thanks for the great work!

I am using libOSRM from C++ application. I would like to query Coordinates by NodeId. I could not find any public interface to do so. Is there any?
Thanks!

**Comment by danpat** [comment]
No, there's no interface to do that.  OSRM doesn't store any kind of nodeID -> coordinate lookup table.

**Comment by HumamHelfawi** [comment]
Thanks for your reply! Can I add it as a feature request?

**Comment by systemed** [comment]
OSRM is effectively in maintenance mode so you're probably only going to get features like that if you code them yourself.
