### ISSUE TITLE
Input file not found ebg 

### ISSUE THREAD

**Issue by donpaul120** [Project-OSRM/osrm-backend#5679]
Operating System : macOS
RAM : 16gb
Storage : 500gb 
 
Input file "/data/nigeria-latest.osrm.ebg

`docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/nigeria-latest.osm.pbf`

```
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: nigeria-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 4
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2020-02-29T21:59:02Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 82.6012 seconds
[info] Raw input contains 41651354 nodes, 4495665 ways, and 140 relations, 23 restrictions
[info] Sorting used nodes        ... ok, after 0.378385s
[info] Erasing duplicate nodes   ... ok, after 0.042422s
[info] Sorting all nodes         ... ok, after 8.57294s
[info] Building node id map      ... ok, after 0.123992s
[info] Confirming/Writing used nodes     ... ok, after 37.6029s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 15673305 nodes
[info] Sorting edges by start    ... ok, after 23.9034s
[info] Setting start coords      ... ok, after 38.773s
[info] Sorting edges by target   ... ok, after 50.633s
[info] Computing edge weights    ... ok, after 69.7959s
[info] Sorting edges by renumbered start ... ok, after 38.9597s
[info] Writing used edges       ... ok, after 23.1551s -- Processed 16296161 edges
[info] Writing way meta-data     ... ok, after 0.899622s -- Metadata contains << 1166232 entries.
[info] Sorting used ways         ... ok, after 0.761898s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0.02961s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 1.6e-05s
[info] Collecting start/end information on 23 restrictions...ok, after 0.088103s
[info] Collecting start/end information on 23 restrictions...ok, after 0.063068s
[info] writing street name index ... ok, after 0.113578s
[info] extraction finished after 377.681s
[info] Generating edge-expanded graph representation
```

The only generated files are
- nigeria-latest.osrm.timestamp
- nigeria-latest.osrm
- nigeria-latest.osrm.names
- nigeria-latest.osrm.properties

**Comment by donpaul120** [comment]
Okay, I increased the RAM associated to my DOCKER to 4gb and it seems to work.
I'd think this should be documented or perhaps i should submit a PR to document this?

**Comment by danpat** [comment]
You should check the exit code for your `docker run` commands - my guess is that it returned an error code when you were generating data.  Unfortunately, Docker simply kills the subprocess that's using too much memory, and doesn't log any messages to the console (there are usually things in your system logs).

**Comment by Raghuvaranpulijala** [comment]
Hii 
Ram :8gb
Memory:1TB
Unable to generate all files it only generated india-latest timestamps
docker run -t -v C:\osrm_data:/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/india-latest.osm.pbf

![IMG_20230725_165608_741.jpg](https://github.com/Project-OSRM/osrm-backend/assets/90614505/a3d99291-eca7-4ba8-b8ef-89befdae4e73)

**Comment by Raghuvaranpulijala** [comment]
@danpat iam new to docker and osrm.
When I try connect maps with osrm api it genarated only one file i.e india-latest.osrm.timestamp
![IMG_20230725_165608_741.jpg](https://github.com/Project-OSRM/osrm-backend/assets/90614505/3bc11a82-1167-445c-a481-39ee99a5ba3e)

It stopped here.
When I run this command
docker run -t -v C:\osrm_data:/data osrm/osrm-backend osrm-partition /data/india-latest.osm.pbf
It shows input file "/data/india-latest.osrm.ebg" not found !
I even changed docker memory to 4gb.
Please help me with this
