### ISSUE TITLE
how to find out reason of  {"message":"No route found between points","code":"NoRoute"} response?

### ISSUE THREAD

**Issue by morruth** [Project-OSRM/osrm-backend#5683]
one of route requests ( /route/v1) returns this response.

i'm removed points from request until only 3 points left
(let it be A,B,C)
if I make request /route/v1/driving/A;B;C ( profile car.lua, slightly modified, changed speed on tertiary roads ) on my server, it returning this error
if I'm removing _Any_ of this points, it's work OK
so 
A;B - OK
A;C - OK
B;C - OK
A:B:C - NoRoute

/walking/ (foot.lua profile) also works OK

What can it be and what  should I do next to find out reason of this error?

I'm using osrm-routed version 5.22.0-customsnapping.3 , maps downloaded from geofabrik.de

Can I somehow turn debuggiing log on?

I've tried --verbosity=DEBUG --verbosity DEBUG --vebosity 4 --verbosity=4 - no success
just [info] messages on stdout

**Comment by danpat** [comment]
Without knowing the exact points and exact map, I'd suspect that it's the `continue_straight=true` default that applies to the car profile.  Try adding `continue_straight=false` and see if that changes the result.

If point `B` is on a location that requires a u-turn to get to C when coming from A, then you can get `NoRoute` if the routing engine thinks it has to continue straight at that location (which is the default for the car profile).

**Comment by morruth** [comment]
thank you, 
your suggsetion helped.
with this parameter it's finds route
