### ISSUE TITLE
[Error] Input file not found

### ISSUE THREAD

**Issue by ovdavid28** [Project-OSRM/osrm-backend#5686]
I keep getting the error input file not found when I try to extract my data. 
I have tried in a thousand ways and I cannot avoid this error.
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              e7d92cdc71fe        8 weeks ago         5.59MB
osrm/osrm-backend   latest              4ca46ac970dc        2 months ago        100MB
hello-world         latest              fce289e99eb9        14 months ago       1.84kB
osrm/osrm-backend   v5.18.0             6147b727444d        22 months ago       20.5MB
osrm/osrm-backend   v5.16.1             384dedd64769        2 years ago         20.2MB
$ ls
driving_side.geojson  maxheight.geojson  spain-latest.osm.pbf  spain-latest.osm.pbf.1
$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/spain-latest.osm.pbf
[error] Input file C:/.../spain-latest.osm.pbf not found!
```
I have seen that many similar errors have been opened in issues, but no answer has solved my problem
I am using Windows 10
Please help.

**Comment by danpat** [comment]
Does `${PWD}` expand to the current directory correctly in whatever shell you're using on Windows?

**Comment by ovdavid28** [comment]
I have checked and ${PWD} expand to the current directory correctly. I have also tried replacing 
${PWD} by hard-coded path and it is still giving me the same error "Input file not found".
Could you give me a more precise example of how you would do it? Maybe I'm trying something wrong? @danpat thank you very much

**Comment by danpat** [comment]
What exactly does the path expand to?  Is it a Windows-style `C:\...` or a WSL-style `/something` ?

I suspect Docker expects a Windows-style path, maybe your shell session is using a Unix-style path that the Docker daemon doesn't understand?

**Comment by ovdavid28** [comment]
It is using WSL-style. It has to be something about Windows recognizing the path as you say, because I try the same with Linux and it is working as expected.

**Comment by danpat** [comment]
@ovdavid28 If you found the solution, could you post it here so that others can find it in the future?

Even if it was something silly/trivial.  **Especially** if it was something silly/trivial :-)
