### ISSUE TITLE
[error] Input file "/data/north-america-latest.osrm.ebg" not found!

### ISSUE THREAD

**Issue by SoulExtinction** [Project-OSRM/osrm-backend#5689]
I'm installing OSRM for North-America and this error came. Can someone tell me how to solve this? 
### nominatim@localadmin-VirtualBox:~/OSRM$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/north-america-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: north-america-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 8
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2020-03-15T21:59:02Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 2095.53 seconds
[info] Raw input contains 1182968945 nodes, 97829133 ways, and 87876 relations, 337298 restrictions
[info] Sorting used nodes        ... ok, after 7.36218s
[info] Erasing duplicate nodes   ... ok, after 1.58306s
[info] Sorting all nodes         ... ok, after 19.7707s
[info] Building node id map      ... ok, after 5.21016s
[info] Confirming/Writing used nodes     ... ok, after 47.8229s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 242634223 nodes
[info] Sorting edges by start    ... ok, after 27.5925s
[info] Setting start coords      ... ok, after 45.5425s
[info] Sorting edges by target   ... ok, after 30.3956s
[info] Computing edge weights    ... ok, after 145.675s
[info] Sorting edges by renumbered start ... ok, after 28.5085s
[info] Writing used edges       ... ok, after 73.2173s -- Processed 256455447 edges
[info] Writing way meta-data     ... ok, after 0.386483s -- Metadata contains << 28677544 entries.
[info] Sorting used ways         ... ok, after 0.08989s
[info] Collecting start/end information on 28 maneuver overrides...ok, after 1.49835s
[info] Collecting start/end information on 28 maneuver overrides...ok, after 0.000282s
[info] Collecting start/end information on 337298 restrictions...ok, after 6.42861s
[info] Collecting start/end information on 337298 restrictions...ok, after 1.30406s
[info] writing street name index ... ok, after 0.443842s
[info] extraction finished after 2553.02s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.197468
[info] Edge compression ratio: 0.239679
nominatim@localadmin-VirtualBox:~/OSRM$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/north-america-latest.osrm
[error] Input file "/data/north-america-latest.osrm.ebg" not found!

**Comment by danpat** [comment]
Check your Docker system logs and exit codes - `osrm-extract` did not complete.  It's probably insufficient memory available to your container.

**Comment by SoulExtinction** [comment]
@danpat I think I have sufficient memory. And I can see the extracted files also. I'll rerun the extract and try once more.

**Comment by danpat** [comment]
No - you do not have enough RAM.

The last few messages from `osrm-extract` should look like this:

```
[info] Writing edge-based-graph edges       ...
[info] ok, after 0.002349s
[info] Processed 9948 edges
[info] Expansion: 34693 nodes/sec and 41226 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "map.osrm"
[info] RAM: peak bytes used: 42962944
```

Check your Docker and/or system logs - what you're seeing is usually the result of the Linux Kernel OOM (out-of-memory) killer killing your process because it's a large RAM user.

Anecdotally, you probably need somewhere north of 50GB of RAM to successfully process the North America OSM extract.

**Comment by SoulExtinction** [comment]
@danpat Thanks for the help. I understand the problem now.

**Comment by hkurma** [comment]
@danpat I have been facing the same issue and landed on as a RAM issue. 

My question is do we need to keep that huge amount of RAM after extraction is complete and to run the osrm-backend container?

I was thinking of spinning up a EC2 on AWS with more RAM (>50GB) and complete the osrm-extract and probably use this extract data on another machine with less RAM (around 16GB) to run the docker container.

**Comment by wangyoucao577** [comment]
@hkurma OSRM will load all compiled map data(`*.osrm.*`) into memory when run `osrm-routed`, so you can not run it on another less RAM instance. For north americia, you'll need 40~50GB RAM to run the routine engine.

**Comment by hkurma** [comment]
@wangyoucao577 Thank you for your response and yes I've figured out that to run routing engine you need as much RAM as to compile the map data.

I've achieved it on a low capacity machine (16 GB) by using a larger swap file.

Thanks for your quick response though

**Comment by SoulExtinction** [comment]
> @wangyoucao577 Thank you for your response and yes I've figured out that to run routing engine you need as much RAM as to compile the map data.
> 
> I've achieved it on a low capacity machine (16 GB) by using a larger swap file.
> 
> Thanks for your quick response though

Hi, can you tell me which Map data did you extract and how much swap memory it is using after 16GB of RAM?

**Comment by MunishaTripping** [comment]
Hi , I am trying to run asia osrm-backend. The asia map file (.pbf) is ~17GB. The RAM of my machine is 52GB. I am monitoring the memory usage on my machine and not getting any memory spikes. Still I am getting  `Input file "/data/asia-latest.osrm.ebg" not found!` error in osrm-partition. 
 
These are my osrm-extract logs 

[2024-03-19T18:01:17.555457720] [info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[2024-03-19T18:01:17.562997673] [info] Using script /opt/car.lua
[2024-03-19T18:01:17.563039210] [info] Input file: asia-latest.osm.pbf
[2024-03-19T18:01:17.563058511] [info] Profile: car.lua
[2024-03-19T18:01:17.563071148] [info] Threads: 8
[2024-03-19T18:01:17.563777216] [info] Parsing in progress..
[2024-03-19T18:01:17.565334896] [info] input file generated by osmium/1.14.0
[2024-03-19T18:01:17.565642634] [info] timestamp: 2024-03-18T21:21:15Z
[2024-03-19T18:01:17.583529519] [info] Using profile api version 4
[2024-03-19T18:01:17.583992201] [info] Found 3 turn restriction tags:
[2024-03-19T18:01:17.584013912] [info]   motor_vehicle
[2024-03-19T18:01:17.584023641] [info]   motorcar
[2024-03-19T18:01:17.584038349] [info]   vehicle
[2024-03-19T18:01:17.584090827] [info] Parse relations ...
[2024-03-19T18:02:01.993465170] [info] Parse ways and nodes ...
[2024-03-19T18:02:02.011647106] [info] Using profile api version 4
[2024-03-19T18:02:02.015611580] [info] Using profile api version 4
[2024-03-19T18:02:02.022628788] [info] Using profile api version 4
[2024-03-19T18:02:02.026628464] [info] Using profile api version 4
[2024-03-19T18:02:02.030376066] [info] Using profile api version 4
[2024-03-19T18:02:02.034602793] [info] Using profile api version 4
[2024-03-19T18:02:02.039711400] [info] Using profile api version 4

Can someone please guide me.
