### ISSUE TITLE
Match service is not accurate when turning

### ISSUE THREAD

**Issue by tom3951769** [Project-OSRM/osrm-backend#5690]
This is through the match service :

![image](https://user-images.githubusercontent.com/37217970/76868342-b7268600-68a1-11ea-8125-c1795d70409a.png)

This is done with the original GPS coordinates:

![image](https://user-images.githubusercontent.com/37217970/76868427-e1784380-68a1-11ea-847c-91831bbfda0f.png)

When using the match service, I set tidy to true and passed timestapms. The effect is not very good. Is there any missing setting of other parameters? 

The sample:
http://10.10.0.100:5000/match/v1/driving/100.539144,13.736316;100.539128,13.736233?timestamps=1526521576;1526521577&tidy=true

Thank you very much for your reply from anyone

**Comment by danpat** [comment]
Which fields in the API response are you looking at to get the geometry?

**Comment by tom3951769** [comment]
First of all, thank you for your reply, I want the geometry that the API returns to be accurate, so what do I do

**Comment by danpat** [comment]
In order for me to help you, you need to answer my question.  Which field in the API response are you using to generate the maps in your original ticket?

**Comment by tom3951769** [comment]
> 为了帮助我，您需要回答我的问题。您使用API​​响应中的哪个字段来生成原始票证中的地图？

The position field under the trace point in the API response is used.

**Comment by tom3951769** [comment]
![image](https://user-images.githubusercontent.com/37217970/76934406-0fa16600-692a-11ea-91b1-d2f25e2deab2.png)
使用图片中红框处的坐标生成的地图

**Comment by danpat** [comment]
@tom3951769 I see - those are the *wrong* coordinates to use to make a map showing a detailed path.  Those are only where the input coordinates were matched to the map, but they do not have the geometry *between*.

You should use either:

  1. `matching[0].geometry` (this is a [polyline](https://github.com/mapbox/polyline) encoded string), or
  2. add `steps=true` to your request, and concatenate the `matching[n].legs[m].steps[o].geometry` fields.

For (1), you can have OSRM emit GeoJSON by doing `&geometries=geojson`, and I would also add `overview=full` to get a full-resolution response (by default, OSRM will [simplify](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) the response geometry to reduce the total API response size).

**Comment by tom3951769** [comment]
> @tom3951769 I see - those are the _wrong_ coordinates to use to make a map showing a detailed path. Those are only where the input coordinates were matched to the map, but they do not have the geometry _between_.
> 
> You should use either:
> 
> 1. `matching[0].geometry` (this is a [polyline](https://github.com/mapbox/polyline) encoded string), or
> 2. add `steps=true` to your request, and concatenate the `matching[n].legs[m].steps[o].geometry` fields.
> 
> For (1), you can have OSRM emit GeoJSON by doing `&geometries=geojson`, and I would also add `&overview=full` to get a full-resolution response (by default, OSRM will [simplify](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) the response geometry to reduce the total API response size).

Thank you very much，The problem of turning has been solved through your method。☺

But then there was a very low matching geometry, and I filtered 0 through the confidence field, and the result was an even weirder line,The line crosses the street

![image](https://user-images.githubusercontent.com/37217970/77132299-e273c580-6a99-11ea-9be5-978d84be94d0.png)

**Comment by danpat** [comment]
Can you please paste the full request and response that you're seeing?

**Comment by tom3951769** [comment]
> Can you please paste the full request and response that you're seeing?

The problem has been solved. Thank you for your patience
