### ISSUE TITLE
[Question] Table service API

### ISSUE THREAD

**Issue by Rakiah** [Project-OSRM/osrm-backend#5691]
Hello, I'm trying to use OSRM backend to do uber-like pickups,

basically I have two list of coordinates, one is my list of uber drivers (this is just an example)
and the second list of coordinates is my list of customers that needs to be picked up, I'm trying to compute the fastest routes for **ALL** customers to be picked up by those uber drivers, which mean i'm not trying to find the closest driver for each customer, but trying to find the scenario where ALL customers are picked up in the fastest way, this may increase the time that one customer is waiting but instead will improve the overall waiting time for multiple customers

I understood that to do this I can use the table service provided by osrm-backend, however I can't seem to wrap my head around how to use this API using the provided [documentation](http://project-osrm.org/docs/v5.5.1/api/?language=cURL#table-service)

What I am currently trying is putting first all list of my drivers coordinates separated by a ';' and then putting all list of my customers coordinates separated by a ';' aswell, and then I am trying to put in the sources parameter the indices corresponding of my uber drivers coordinates and in destinations parameter the indices corresponding of my customer

(you can plot the following coordinates in http://www.hamstermap.com/quickmap.php)

to give an example, those are my customers:

Customer A 48.8710241 2.2266687
Customer B 48.8695921 2.228921

and those are my drivers:
Driver A 48.871361, 2.226703
Driver B 48.871371, 2.224973

Technically, for a efficient table matching, driver A should go to customer B even though he is closest to customer A and driver B should go to customer A
see following screenshot explaining:
![image](https://user-images.githubusercontent.com/16012885/76882252-add5f300-687a-11ea-9416-5a666f96fc23.png)

Then my request is looking like this:
https://OSRM_SERVER/table/v1/driving/2.226703,48.871361;2.224973,48.871371;2.228921,48.8695921;2.2266687,48.8710241?sources=0;1&destinations=2;3
and yields me this response:
```
{
    "code": "Ok",
    "durations": [
        [
            105.7,
            140.4
        ],
        [
            64.9,
            99.6
        ]
    ],
    "destinations": [
        {
            "hint": "GDwngB08J4AAAAAACAAAAAAAAABOAAAAAAAAALZcCUEAAAAA5u6tQgAAAAAIAAAAAAAAAE4AAADrBAAAuQIiANiw6QK5AiIA2LDpAgAAzxLV46_z",
            "distance": 0,
            "name": "Rue du Bac",
            "location": [
                2.228921,
                48.869592
            ]
        },
        {
            "hint": "QDwngP___38AAAAATQAAAAAAAAAgAAAAAAAAADmmCUIAAAAAYLRjQQAAAABNAAAAAAAAACAAAADrBAAA7fkhAHC26QLt-SEAcLbpAgAA_wzV46_z",
            "distance": 0,
            "name": "Rue Alexandre Darracq",
            "location": [
                2.226669,
                48.871024
            ]
        }
    ],
    "sources": [
        {
            "hint": "QTwngP___385AAAAQgAAACoAAADRAAAAXOzNQbxscUB255JBBza5QjkAAABCAAAAKgAAANEAAADrBAAAKvohALi36QIP-iEAwbfpAgQAvwHV46_z",
            "distance": 2.21916,
            "name": "Rue Alexandre Darracq",
            "location": [
                2.22673,
                48.871352
            ]
        },
        {
            "hint": "4jsngN2MA4AFAAAAAwAAAAAAAAAAAAAAkqGBQFehzD8AAAAAAAAAAAUAAAADAAAAAAAAAAAAAADrBAAAb_MhAL236QJN8yEAy7fpAgAATw3V46_z",
            "distance": 2.940184,
            "name": "Rue Carnot",
            "location": [
                2.225007,
                48.871357
            ]
        }
    ]
}
```

And I can't seem to understand who is supposed to go where using what route ?

Thanks for your help

**Comment by danpat** [comment]
The table service is useful for calculating travel times between given sets of points - it doesn't have any logic to select the "best" - that's more of an [Operations Research](https://en.wikipedia.org/wiki/Operations_research) optimization question.  Typically, a travel-time matrix would be one of the inputs to further logic that needs to make the decision about which driver/passengers to pair up.

**Comment by Rakiah** [comment]
Thank you for your time, I believe that for my case, I could easily do this logic myself by retrieving the travel time matrix that have the lowest median between all pairs

If I understood how to read the travel time matrix, and what exactly I should put in the source and destination parameter I could do that but i'm quite lost, could you help me out on this ?

**Comment by danpat** [comment]
Ok - the field you should be looking at is `durations` - it's a table of travel times from the sources to the destinations.  If I format your result it might be clearer:

| sources↓ \| destinations→| C | D |
|-|-|-|
| **A** | 105.7 | 140.4 |
| **B** | 64.9 | 99.6 |

This is what the nested set of arrays in `durations` represents.

**Comment by Rakiah** [comment]
Thank you, In this case, based on the previous example,

A would be driver A and C would be customer A ?
B would be driver B and D would be customer B ?

**Comment by danpat** [comment]
Yes.

**Comment by Rakiah** [comment]
OK so there i've just made a random guess based on the points that i've seen, but, from an algorithm point of view, How would I discriminate that the first duration matrix is equal to a specific source point and destination matching and the second duration matrix is equal to another one ?

**Comment by danpat** [comment]
Everything in the response is consistently indexed.  Let me walk through it.

You supply 4 coordinates to the service, let's call them A, B, C, and D.

You specify that A and B are "sources", and C and D are "destinations" by using their positions in the coordinate array like so: `&sources=0;1&destinations=3,4`

You know you have two sources, and two destinations.  You can expect your result `durations` array to be a nested set of 2 arrays containing 2-element sub-arrays.

To access the route from A->D, you know this is from source 0 to destination 1, so your lookup is:

`let A_to_D_duration = result.durations[0][1];`

Hopefully that helps.  The table results are in a fixed order, derived from the order you supplied the coordinates and sources/destinations in the input URL.

**Comment by Rakiah** [comment]
Thank you I think I got it, in the previous example my algorithm would define that the best scenario is the second array, therefore if I want to know what routes I need to compute I could reverse lookup and knows that durations[1][0] is equal to source 1 going to destination 0 however durations[1][1] also means that source 1 is going to destination 1, which is not possible in my case, So I understand that the sub-array of durations[x] is not what I expected (a specific scenario where all sources are going to taking care of all destinations but without overlapping) but instead it is all the possibilities for a specific source to go to all destinations, In my case how would I find all non-overlapping possibilities ? what I mean by that is no two sources going to two different destination

**Comment by danpat** [comment]
Yes - for many use-case, a `table` response will have values you won't use.  OSRM doesn't have a "batch pairs" API (request durations between several specific pairs of points).  You can use the `table` service for this, but you would end up ignoring many of the results in the table.  There's no harm in this as long as OSRM is responding fast enough for your needs.

**Comment by Rakiah** [comment]
Yes i'm not afraid of OSRM response time, however the previous algorithm i've shown would only compute 5 possibilities out of the 120 that there is for drivers to pickup customers and therefore It will statistically take a bad choice, I could rework it to test all of the 120 possibilities but because this is a problem that is NP-Hard it will end up being too slow, computing all non-overlapping possibilities is a factorial determined, for 5 drivers to pickup 5 customers would be !5 (factorial) possibilities (120), but for 10 drivers to pickup 5 customers it would be !10 non-overlapping possibilities (3628800) or 10^10 overlapping possibilities which starts to get completely impossible to compute

**Comment by danpat** [comment]
Yes, you'll need to use some kind of heuristic approach to solving this.  Here's one example library (OR-Tools) that you could use to solve this kind of problem.

The example posted here:

https://developers.google.com/optimization/routing/pickup_delivery

could be extended to be multi-vehicle with known start locations, and undefined end locations.  The solver would then optimize for minimum total driving time (you can change this, but you would need to spend some time learning the OR-Tools library interface).

Solving NP-Hard [Vehicle Routing Problems](https://en.wikipedia.org/wiki/Vehicle_routing_problem) is a little beyond the scope of this repo.

**Comment by Rakiah** [comment]
Yes I believe it goes behind my solving abilities aswell, I've previously taken an example with driver and customer but its not really what i'm trying to solve, my real problem is for peoples to go to specific locations over the minimum combined time, what I mean by combine tdime is that the time that is important to me is the moment that ALL of them reach their destination, not each of them independently, so maybe the google optimization library could help, i'll dig that and move forward thanks
