### ISSUE TITLE
custom profile

### ISSUE THREAD

**Issue by SamirTidafi** [Project-OSRM/osrm-backend#5693]
whene writing custom profile.lua (cloning car.lua and do some speed changes)  i got same duration ,how i can customize profile ,
thanks

**Comment by danpat** [comment]
Did you re-generate your routing files with `osrm-extract`/`osrm-customize` ?

**Comment by SamirTidafi** [comment]
yes, iuse this comands: 
 osrm-extract -p /opt/moto.lua /data/moto/data.osm.pbf
 osrm-partition /data/moto/data.osm.osrm 
 osrm-customize /data/moto/data.osm.osrm

moto.lua is clone of car.lua without some speeds reduction
