### ISSUE TITLE
[error] Input file "/data/north-america-latest.osrm.ebg" not found!

### ISSUE THREAD

**Issue by SoulExtinction** [Project-OSRM/osrm-backend#5694]
I'm gettting this error after extracting North-America file.
### nominatim@localadmin-VirtualBox:~/OSRM$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/north-america-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: north-america-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 8
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2020-03-15T21:59:02Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 1873.47 seconds
[info] Raw input contains 1182968945 nodes, 97829133 ways, and 87876 relations, 337298 restrictions
[info] Sorting used nodes        ... ok, after 6.98191s
[info] Erasing duplicate nodes   ... ok, after 1.33036s
[info] Sorting all nodes         ... ok, after 19.7321s
[info] Building node id map      ... ok, after 4.74062s
[info] Confirming/Writing used nodes     ... ok, after 120.984s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 242634223 nodes
[info] Sorting edges by start    ... ok, after 27.0541s
[info] Setting start coords      ... ok, after 36.4272s
[info] Sorting edges by target   ... ok, after 25.8865s
[info] Computing edge weights    ... ok, after 141.938s
[info] Sorting edges by renumbered start ... ok, after 27.6111s
[info] Writing used edges       ... ok, after 104.096s -- Processed 256455446 edges
[info] Writing way meta-data     ... ok, after 0.393365s -- Metadata contains << 28677544 entries.
[info] Sorting used ways         ... ok, after 0.076102s
[info] Collecting start/end information on 28 maneuver overrides...ok, after 1.52816s
[info] Collecting start/end information on 28 maneuver overrides...ok, after 0.000218s
[info] Collecting start/end information on 337298 restrictions...ok, after 6.78505s
[info] Collecting start/end information on 337298 restrictions...ok, after 1.10456s
[info] writing street name index ... ok, after 0.588426s
[info] extraction finished after 2417.63s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.197468
[info] Edge compression ratio: 0.239679
[info]  graph compression removed 25722259 annotations of 28677544 in 1256.18 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 38903.6s
[info] Segregated edges count = 1096675
[info] Writing nodes for nodes-based and edges-based graphs ...
[info] Geometry successfully removed:
  compressed edges: 122766000
  compressed geometries: 512324684
  longest chain length: 6987
  cmpr ratio: 0.239625
  avg chain length: 4.17318
[info] Generating edge expanded nodes ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 117531191 nodes (21137 of which are duplicates)  and 256104720 segments in edge-expanded graph
[info] Generating edge-expanded edges 
[info] .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 13138970, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.460153&mlon=-83.154748
 10% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 41510510, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.214208&mlon=-77.111079
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 42504102, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.533973&mlon=-81.013553
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 48187966, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.17513&mlon=-95.425205
 20% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 61694374, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=34.925952&mlon=-98.098521
 30% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 75510173, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=36.851942&mlon=-86.912602
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 81929415, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.320735&mlon=-111.206618
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 96405686, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=34.940718&mlon=-80.666954
 40% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 108189372, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.17285&mlon=-75.175466
. 50% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 135628938, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=46.149721&mlon=-66.944733
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 143451924, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.376815&mlon=-61.855283
 60% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 148847387, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=21.857477&mlon=-101.599703
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 155953808, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.884403&mlon=-87.621391
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 164444048, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.111822&mlon=-122.011241
 70% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 177775612, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=33.742916&mlon=-118.287885
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 193788897, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=19.865221&mlon=-98.245847
 80% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 200747663, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.062794&mlon=-122.918649
. 90% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 224083121, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.068212&mlon=-83.159958
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 226778973, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=45.885885&mlon=-73.429043
.
[info] Sorting and writing 28 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 256104720 edge based node segments
[info] Node-based graph contains 117504782 edges
[info] Edge-expanded graph ...
[info]   contains 230335962 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 67.8507s
[info] Generating nodes: 25777.4s
[info] Generating edges: 77852.6s
[info] Generating guidance turns 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .
[info] done.
[info] Created 257 entry classes and 90966 Bearing Classes
[info] Handled: 350017 of 635334 lanes: 55.0918 %.
[info] Assigned 261297157 turn instruction types:
[info]   new name: 6047018 (2.31%)
[info]   continue: 13819067 (5.29%)
[info]   turn: 106194819 (40.64%)
[info]   merge: 114841 (0.04%)
[info]   on ramp: 182987 (0.07%)
[info]   off ramp: 127650 (0.05%)
[info]   fork: 1229882 (0.47%)
[info]   end of road: 44352373 (16.97%)
[info]   notification: 1559 (0.00%)
[info]   enter roundabout: 59025 (0.02%)
[info]   enter and exit roundabout: 3762 (0.00%)
[info]   enter rotary: 2770 (0.00%)
[info]   enter and exit rotary: 199 (0.00%)
[info]   enter roundabout turn: 21112 (0.01%)
[info]   enter and exit roundabout turn: 33 (0.00%)
[info]   (noturn): 25125012 (9.62%)
[info]   (suppressed): 63631689 (24.35%)
[info]   roundabout: 3818 (0.00%)
[info]   exit roundabout: 70966 (0.03%)
[info]   rotary: 226 (0.00%)
[info]   exit rotary: 3270 (0.00%)
[info]   roundabout turn: 24 (0.00%)
[info]   exit roundabout turn: 21387 (0.01%)
[info]   (stay on roundabout): 90466 (0.03%)
[info]   (sliproad): 193202 (0.07%)
[info] Assigned 261297157 turn instruction modifiers:
[info]   uturn: 11573344 (4.43%)
[info]   sharp right: 3571098 (1.37%)
[info]   right: 73818169 (28.25%)
[info]   slight right: 5420735 (2.07%)
[info]   straight: 85122000 (32.58%)
[info]   slight left: 5278241 (2.02%)
[info]   left: 72631922 (27.80%)
[info]   sharp left: 3881648 (1.49%)
[info] Guidance turn annotations took 48196.9s
[info] Writing Intersection Classification Data
[info] ok, after 978.432s
[info] Writing Turns and Lane Data...
[info] ok, after 40.2819s
[info] Saving edge-based node weights to file.
[info] Done writing. (742.015)
[info] Computing strictly connected components ...
### nominatim@localadmin-VirtualBox:~/OSRM$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/north-america-latest.osrm
[error] Input file "/data/north-america-latest.osrm.ebg" not found!

**Comment by danpat** [comment]
The first command did not complete successfully.  The last message printed `Computing strictly connected components ...` is *not* the last thing that `osrm-extract` prints.

I would suspect you have not allocated enough memory to your Docker container, and it is killing `osrm-extract` due to insufficient memory.  Check your Docker system logs for OOM (Out Of Memory) errors.
