### ISSUE TITLE
get fastest route

### ISSUE THREAD

**Issue by koussaimb** [Project-OSRM/osrm-backend#5696]
Hello, 

I would like to know if there is a method or option to know the fastest route without giving an order because if I understood correctly  the route service : Finds the fastest route between coordinates in the supplied order.
And trip service : The returned path does not have to be the fastest path.

I want to give mulitple point and I get the fastest shirt.

Thanks !

**Comment by P-mir** [comment]
Hi koussaimb, OSRM can only find the shortest path, you have to look for others routers if you're interested by the fastest path.

**Comment by jcoupey** [comment]
> I would like to know if there is a method or option to know the fastest route without giving an order 

This is what the trip plugin is for. It will order the input points for you.  The full quote from the docs is:

> The returned path does not have to be the fastest path. As TSP is NP-hard it only returns an approximation

It just means that there is no guarantee that the returned order is optimal.

**Comment by danpat** [comment]
I'll add that for 10 or fewer coordinates, OSRM does a brute-force search and will return the fastest order.  Above 10 coordinates, we use a heuristic that has no guarantee that the order will be the best.

**Comment by koussaimb** [comment]
thank you for your answers
I looked for another service it's heremap it gives 250k free request per month is enough for me
