### ISSUE TITLE
libosrm multiple routes

### ISSUE THREAD

**Issue by Mohammadabd** [Project-OSRM/osrm-backend#5697]
I’m trying to get 2 fastest routes from libosrm pretty much like the REST version. However, I’m getting index out of range error. Do I need to provide any params about number of routes to return? `const auto status = osrm.Route(params, result);`

Here is the code I’m getting error at:
```
auto &route1 = routes.values.at(0).get<json::Object>();
auto &route2 = routes.values.at(1).get<json::Object>();
```
and the error:
```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: vector
Abort trap: 6
```

**Comment by danpat** [comment]
OSRM isn't magic - it will find *the* fastest route.  Even if you supply `alternatives=N`, it only means *up to N* results may be returned, not that we guarantee to return N results.

**Comment by Mohammadabd** [comment]
Thank you so much for prompt response. But REST returns 2 routes. That’s the point. I cannot get the same result from libosrm though. I thought there might be some parameters to pass.
![image](https://user-images.githubusercontent.com/23286517/77489201-d37c7280-6e0d-11ea-8b16-942878b0aa1d.png)

**Comment by danpat** [comment]
You might need to set the `alternatives` property on the `libosrm` interface - maybe it defaults to 1, I'm not sure.  But you should always check the size of the `routes` object returned - don't assume that if you specify `alternatives=2` that you'll get two results.

**Comment by Mohammadabd** [comment]
One last question, is the results returned are sorted based on duration. So the second route is 2nd fastest route. right?

**Comment by danpat** [comment]
The first result will be the fastest.  Results after that will be slower, but not sorted.
