### ISSUE TITLE
road selected is neither shortest nor fastest

### ISSUE THREAD

**Issue by baptx** [Project-OSRM/osrm-backend#5699]
When using OpenStreetMap and selecting "Car (OSRM)", it takes 4 kilometers and 5 minutes more compared to "Car (GraphHopper)" when crossing a border between France and Germany.
Is there a way to fix this issue?
Here are the links of the directions (47.9413,7.4637 to 47.9967,7.8416):
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=47.9413%2C7.4637%3B47.9967%2C7.8416#map=12/47.9833/7.6527
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=47.9413%2C7.4637%3B47.9967%2C7.8416#map=12/47.9651/7.6527

**Comment by danpat** [comment]
@baptx I suspect that neither are correct for ETA - your best bet to know who is wrong is to go out and drive both routes with a stopwatch.

Both OSRM and Graphhopper estimate speeds using metadata in the OSM basemap.  Those estimates are used to find the "fastest" route, according to the estimated speeds.

OSRM and Graphhopper are reporting the fastest routes they found using the esimates they used - as they have different estimates, they came up with different paths, and different fastest ETAs.

To know which one is closest to correct, you'll have to go out and actually travel those routes with a stopwatch.

I don't know if anyone has tried to get OSRM and Graphhopper perfectly aligned wrt. speed estimates.  If they were perfectly the same, they would give the same result.

**Comment by baptx** [comment]
@danpat I took these directions and believe the route from GraphHopper is the fastest and shortest, like written on OpenStreetMap. It is also the direction that my TomTom GPS recommends.
Maybe I can verify with a stopwatch next time I take these directions.
What is the easiest way to test and correct the speed estimates of OSRM? In which part of the source code is it handled?

**Comment by baptx** [comment]
By the way, when using OSRM with Marble, I noticed the fastest route with the same time is selected, like when using GraphHopper on OpenStreetMap. Does it mean there is a bug in the OSRM version used by OpenStreetMap?

**Comment by systemed** [comment]
> By the way, when using OSRM with Marble, I noticed the fastest route with the same time is selected, like when using GraphHopper on OpenStreetMap. Does it mean there is a bug in the OSRM version used by OpenStreetMap?

No, it means that the instance used by openstreetmap.org has different speed values ("routing profiles"). You can see the profiles used at https://github.com/fossgis-routing-server/cbf-routing-profiles

If you look at the files in that repository, such as `car.lua`, you'll see what values are used. If you run your own instance of OSRM, you can change them.
