### ISSUE TITLE
Need help writing a lua script for public transit (bus)

### ISSUE THREAD

**Issue by carlospuk** [Project-OSRM/osrm-backend#570]
Hi there

I'm fairly new to DennisOSRM and am trying to figure out more about the .lua scripts in order to create a profile that would create sensible approximations of bus routes here in the UK.

Would anybody be able to give me some guidance?  So far I'm just modifying car.lua ad setting all the road speeds the same, e.g.

motorway=40
trunk=40
etc

...is there a better way?

**Comment by TheMarex** [comment]
Closing not actionable.
