### ISSUE TITLE
demo server data download

### ISSUE THREAD

**Issue by wave-light** [Project-OSRM/osrm-backend#5700]
Hey, do you provide a download of the data that you use for the demo server?
I would like to get the graph data for the whole world, but it takes a lot of processing from the osm files.
If you cannot provide the data for download, would you kindly be able to provide a recipe of how we can construct the same data that you use in the demo server?
Thanks!

**Comment by danpat** [comment]
We don't have a download available.  The demoserver integrates traffic data from Mapbox, which is not openly available.  Other than that, the demoserver uses a slightly tweaked version of `car.lua`.  The traffic data makes the biggest difference in results compared to what you'll get using the public Lua profiles.
