### ISSUE TITLE
Unrecognized parameter 'annotations'

### ISSUE THREAD

**Issue by Petkomat** [Project-OSRM/osrm-backend#5701]
I tried to retrieve the distances (in addition to the durations), however, neither my actual urls of interest nor the exemplary url

`http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance`

works. The response is `{"code":"Error","message":"Unrecognized parameter 'annotations'"}`.

Has the parameter been renamed?

**Comment by danpat** [comment]
No, but the demoserver is running a version of the routing server that doesn't support that parameter.

You'll need to run your own OSRM server to be able to use it.

**Comment by selting** [comment]
I was able to run my own OSRM server following these steps: https://github.com/Project-OSRM/osrm-backend#using-docker

When trying to use the table service (https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#table-service), the following is happening:

- `curl "http://127.0.0.1:5000/table/v1/driving/13.388860,52.517037;13.385983,52.496891"` works just fine
- `curl "http://127.0.0.1:5000/table/v1/driving/13.388860,52.517037;13.385983,52.496891?sources=0&destinations=0;1"` works just fine
- `curl "http://127.0.0.1:5000/table/v1/driving/13.388860,52.517037;13.385983,52.496891?annotations=duration,distance"` works just fine
- `curl "http://127.0.0.1:5000/table/v1/driving/13.388860,52.517037;13.385983,52.496891?sources=0&destinations=0;1?annotations=duration,distance"` fails with the following message: 
```
curl : {"message":"Query string malformed close to position 84","code":"InvalidQuery"}
At line:1 char:1
+ curl "http://127.0.0.1:5000/table/v1/driving/13.388860,52.517037;13.3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-W
   ebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebR
   equestCommand
```

1. Are my queries correct?
2. Why do the sources&destinations and the annotations option work individually but not combined?
3. Is there any workaround?

**Comment by datendelphin** [comment]
This issue popped up due to probably an already again deleted comment. The original query seems to work as expected
