### ISSUE TITLE
osrm-extract not generating files required by osrm-partition

### ISSUE THREAD

**Issue by sheldonreddy** [Project-OSRM/osrm-backend#5702]
Hi there, 

I am using the OSRM Dockerfile hosted on the OSRM DockerHub page ([Here](https://hub.docker.com/r/osrm/osrm-backend/).

### **Problem:**
**osrm-extract** creates a full set of files (23 files in total) for Berlin but not for countries like South Africa (7 files in total). The missing files ( osrm.ebg and osrm.cnbg_to_ebg files ) required by `osrm-partition` are not being generated by `osrm-extract`.

### **South Africa Workflow:**

1. Download the desired .osm.pbf file from GeoFabrik and store it in a directory on my local machine. 
2. Ensure Docker Desktop is running correctly. 
3. Open up PowerShell in Admin mode
4. Execute **osrm-extract.exe** using the following command: 

`docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/south-africa-latest.osm.pbf`

5. The command executes without error. The output on Powershell is as follows:

`[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: south-africa-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 2
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2020-04-01T20:59:02Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Parsing finished after 96.4135 seconds
[info] Raw input contains 27123719 nodes, 2129197 ways, and 1738 relations, 4241 restrictions
[info] Sorting used nodes        ... ok, after 0.530739s
[info] Erasing duplicate nodes   ... ok, after 0.039194s
[info] Sorting all nodes         ... ok, after 0.102179s
[info] Building node id map      ... ok, after 0.045732s
[info] Confirming/Writing used nodes     ... ok, after 1.05429s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 11675622 nodes
[info] Sorting edges by start    ... ok, after 1.72916s
[info] Setting start coords      ... ok, after 0.936663s
[info] Sorting edges by target   ... ok, after 1.10455s
[info] Computing edge weights    ... ok, after 2.89745s
[info] Sorting edges by renumbered start ... ok, after 1.06821s
[info] Writing used edges       ... ok, after 1.64583s -- Processed 12344785 edges
[info] Writing way meta-data     ... ok, after 0.005725s -- Metadata contains << 1060913 entries.
[info] Sorting used ways         ... ok, after 0.005289s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0.01091s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 1e-06s
[info] Collecting start/end information on 4241 restrictions...ok, after 0.054129s
[info] Collecting start/end information on 4241 restrictions...ok, after 0.005751s
[info] writing street name index ... ok, after 0.59034s
[info] extraction finished after 109.918s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.146196
[info] Edge compression ratio: 0.191091
[info]  graph compression removed 943212 annotations of 1060913 in 62.8983 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 98.7679s
[info] Segregated edges count = 41834
[info] Writing nodes for nodes-based and edges-based graphs ...
[warn] Clipped 4 segment weights to 4194302
[info] Geometry successfully removed:
  compressed edges: 4709900
  compressed geometries: 24658652
  longest chain length: 1803
  cmpr ratio: 0.191004
  avg chain length: 5.23549`

6. Inspect the directory, the following **7 files** are present after the above command [5]:

![image](https://user-images.githubusercontent.com/29771068/78251665-f683e200-74f1-11ea-8b53-d9a99c851bfe.png)

7. Execute **osrm-partition.exe** using the following Command:

`docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/south-africa-latest.osrm`

8. The output of the above command [7] is:

`[error] Input file "/data/south-africa-latest.osrm.ebg" not found!`

### **Berlin Workflow**

1. Download the desired .osm.pbf file from GeoFabrik and store it in a directory on my local machine. 
2. Ensure Docker Desktop is running correctly. 
3. Open up PowerShell in Admin mode
4. Execute **osrm-extract.exe** using the following command: 

`docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin.osm.pbf`

5. The command executes without error. The output on Powershell is as follows:

`[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: berlin-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 2
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2020-04-01T20:59:02Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Parsing finished after 17.0849 seconds
[info] Raw input contains 5458033 nodes, 806244 ways, and 1336 relations, 1291 restrictions
[info] Sorting used nodes        ... ok, after 0.015894s
[info] Erasing duplicate nodes   ... ok, after 0.001406s
[info] Sorting all nodes         ... ok, after 0.005134s
[info] Building node id map      ... ok, after 0.008242s
[info] Confirming/Writing used nodes     ... ok, after 0.022165s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 290981 nodes
[info] Sorting edges by start    ... ok, after 0.021746s
[info] Setting start coords      ... ok, after 0.027543s
[info] Sorting edges by target   ... ok, after 0.020929s
[info] Computing edge weights    ... ok, after 0.099285s
[info] Sorting edges by renumbered start ... ok, after 0.024384s
[info] Writing used edges       ... ok, after 0.007325s -- Processed 320964 edges
[info] Writing way meta-data     ... ok, after 0.000516s -- Metadata contains << 80689 entries.
[info] Sorting used ways         ... ok, after 0.000368s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0.000978s
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0s
[info] Collecting start/end information on 1291 restrictions...ok, after 0.003057s
[info] Collecting start/end information on 1291 restrictions...ok, after 0.001207s
[info] writing street name index ... ok, after 0.008697s
[info] extraction finished after 17.5218s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.37577
[info] Edge compression ratio: 0.43044
[info]  graph compression removed 67050 annotations of 80689 in 0.096051 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 0.503605s
[info] Segregated edges count = 5458
[info] Writing nodes for nodes-based and edges-based graphs ...
[info] Geometry successfully removed:
  compressed edges: 274600
  compressed geometries: 650024
  longest chain length: 57
  cmpr ratio: 0.422446
  avg chain length: 2.36717
[info] Generating edge expanded nodes ...
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ...
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 253821 nodes (67 of which are duplicates)  and 318911 segments in edge-expanded graph
[info] Generating edge-expanded edges
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .
[info] Sorting and writing 0 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 318911 edge based node segments
[info] Node-based graph contains 253537 edges
[info] Edge-expanded graph ...
[info]   contains 472395 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 0.006975s
[info] Generating nodes: 0.095973s
[info] Generating edges: 2.61932s
[info] Generating guidance turns
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .
[info] done.
[info] Created 43 entry classes and 2594 Bearing Classes
[info] Handled: 2845 of 5561 lanes: 51.1599 %.
[info] Assigned 575113 turn instruction types:
[info]   new name: 12407 (2.16%)
[info]   continue: 38184 (6.64%)
[info]   turn: 217027 (37.74%)
[info]   merge: 90 (0.02%)
[info]   on ramp: 213 (0.04%)
[info]   off ramp: 93 (0.02%)
[info]   fork: 1364 (0.24%)
[info]   end of road: 95464 (16.60%)
[info]   notification: 12 (0.00%)
[info]   enter roundabout: 57 (0.01%)
[info]   enter and exit roundabout: 2 (0.00%)
[info]   enter rotary: 63 (0.01%)
[info]   enter and exit rotary: 7 (0.00%)
[info]   enter roundabout turn: 28 (0.00%)
[info]   (noturn): 68552 (11.92%)
[info]   (suppressed): 141017 (24.52%)
[info]   roundabout: 2 (0.00%)
[info]   exit roundabout: 62 (0.01%)
[info]   rotary: 7 (0.00%)
[info]   exit rotary: 70 (0.01%)
[info]   exit roundabout turn: 28 (0.00%)
[info]   (stay on roundabout): 146 (0.03%)
[info]   (sliproad): 218 (0.04%)
[info] Assigned 575113 turn instruction modifiers:
[info]   uturn: 28462 (4.95%)
[info]   sharp right: 4810 (0.84%)
[info]   right: 161044 (28.00%)
[info]   slight right: 8588 (1.49%)
[info]   straight: 202545 (35.22%)
[info]   slight left: 8572 (1.49%)
[info]   left: 155795 (27.09%)
[info]   sharp left: 5297 (0.92%)
[info] Guidance turn annotations took 3.72078s
[info] Writing Intersection Classification Data
[info] ok, after 0.444663s
[info] Writing Turns and Lane Data...
[info] ok, after 0.079603s
[info] Saving edge-based node weights to file.
[info] Done writing. (0.037885)
[info] Computing strictly connected components ...
[info] Found 1314 SCC (1 large, 1313 small)
[info] SCC run took: 0.0196839s
[info] Building r-tree ...
[info] Constructing r-tree of 318911 segments build on-top of 290981 coordinates
[info] finished r-tree construction in 0.439817 seconds
[info] Writing edge-based-graph edges       ...
[info] ok, after 0.161948s
[info] Processed 472395 edges
[info] Expansion: 34585 nodes/sec and 30168 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "/data/berlin-latest.osrm"
[info] RAM: peak bytes used: 375238656`

6. Inspect the directory, the following **23 files** are present after the above command [5]:

![image](https://user-images.githubusercontent.com/29771068/78251951-5f6b5a00-74f2-11ea-9567-b75c7854bc34.png)

7. Execute **osrm-partition.exe** using the following Command:

`docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/berlin-latest.osrm`

8. The output of the above command [7] is:

`[info] Computing recursive bisection
[info] Loaded compressed node based graph: 274544 edges, 290981 nodes
[info]  running partition: 128 1.2 0.25 10 1000 # max_cell_size balance boundary cuts small_component_size
[info] Found 182064 SCC (1 large, 182063 small)
[info] SCC run took: 0.0756884s
[info] Full bisection done in 3.21466s
[info] Loaded node based graph to edge based graph mapping
[info] Loaded edge based graph for mapping partition ids: 943682 edges, 253821 nodes
[info] Fixed 122 unconnected nodes
[info] Edge-based-graph annotation:
[info]   level 1 #cells 1296 bit size 11
[info]   level 2 #cells 91 bit size 7
[info]   level 3 #cells 8 bit size 4
[info]   level 4 #cells 1 bit size 1
[info] Renumbered data in 1.1293 seconds
[info] MultiLevelPartition constructed in 0.054685 seconds
[info] CellStorage constructed in 0.025928 seconds
[info] MLD data writing took 0.181811 seconds
[info] Cells statistics per level
[info] Level 1 #cells 1296 #boundary nodes 25096, sources: avg. 12, destinations: avg. 17, entries: 371291 (2970328 bytes)
[info] Level 2 #cells 91 #boundary nodes 3614, sources: avg. 26, destinations: avg. 35, entries: 109475 (875800 bytes)
[info] Level 3 #cells 8 #boundary nodes 464, sources: avg. 37, destinations: avg. 49, entries: 20753 (166024 bytes)
[info] Level 4 #cells 1 #boundary nodes 0, sources: avg. 0, destinations: avg. 0, entries: 0 (0 bytes)
[info] Bisection took 5.88928 seconds.
[info] RAM: peak bytes used: 82800640`

### ** Questions**
1. Why is `osrm-extract` producing a different set of files for Berlin than South Africa? I tested with other countries like Botswana and Nigeria and found the same thing. The only difference being the `osm.pbf` file being used.

2. Is there anyway to force osrm-extract to generate the missing files for South Africa? 

3. Is there a way to generate the `osrm.maneuver_overrides` file separately? (see note below for reason)

### **Note**
I found a set of Windows OSRM Binaries which I used to process the South Africa `osm.pbf` file. 

I was able to run the `osrm-extract`, `osrm-partition`, `osrm-customize` and `osrm-contract` executables successfully. 

However, when attempting to deploy it using `osrm-route`, it provided the following message:

`[warn] Missing/Broken File: /fileshare/southafricalatest.osrm.maneuver_overrides
[error] Required files are missing, cannot continue`

This method ( OSRM Windows Binaries ) did not create the `osrm.maneuver_overrides` file for South Africa but worked for Berlin without any issues. 

**Any suggestions in this regard would be greatly appreciated.**

**Comment by danpat** [comment]
Couple of things:

  1. I believe the Windows binaries are out of date - nobody has been maintaining the build/publish system for them for a while, so I don't know what version they even are.  It's possible they're not generating all the same files that the latest release does.

  2.  You should check your Docker system logs.  `osrm-extract` silently failing before it's fully completed is a common symptom of Docker killing it due to insufficient RAM (Docker can limit RAM available to a process).  Unfortunately, there's not much we can do on the OSRM side, as the problem is Docker actively killing our process - we don't even get a signal to respond to as far as I know, so we can't even print out an error message.

**Comment by sheldonreddy** [comment]
Hi @danpat 

The issue was indeed insufficient RAM. 

Just some detail:

I spun up a quick Docker Container on Azure with 16GB RAM and used the latest OSRM DockerHub image to process the `south-africa-latest-osm.pbf` file. Once the process completed I shut down the Docker container and used the files to deploy OSRM with the Azure Kubernetes Service. 

The process seems pretty seemless and is working well.
