### ISSUE TITLE
osrm-extract takes long time

### ISSUE THREAD

**Issue by adhamenaya** [Project-OSRM/osrm-backend#5705]
Hi,
I am trying to extract the `.osrm` file for `osm.pbf` (4 counties aren't adjacent) of size 270 MB. I think the command is stuck as the point` [extractor] Compugin edge weights ...` I am running it on `Azamon EC2 (t2.micro) with 8 GB` as a swap file.

is it normal to take about more than 2 hours for this task? is there any way that I can check the progress without stopping the extraction?

**Comment by danpat** [comment]
I don't think a `t2.micro` (1vCPU, 1GB of RAM) will be enough to quickly generate routing files for a 270MB OSM PBF file.

You might be able to *route* (using `osrm-routed`) on an instance that size, but processing requires more resources to run efficiently.

For a baseline, I just ran `osrm-extract` on my laptop (2core, 16GB RAM) for `turkey-latest.osm.pbf` (about 290MB), and the last few lines of the output was:

```
[info] RAM: peak bytes used: 4270989312
```

So to efficiently process `turkey-latest.osm.pbf`, it needed about 4.2GB of RAM.  It took a few minutes (maybe 5? I didn't time it).

Your setup is probably proceeding _very very slowly_, using swap RAM heavily.  I don't know how long it will take overall, but maybe days or weeks?

I would temporarily rent a bigger server to do the processing, or just do it on a desktop machine you have handy that has more than 4GB of RAM.
