### ISSUE TITLE
Is it possible to get way_ids from osrm_routing service?

### ISSUE THREAD

**Issue by AlexKaravaev** [Project-OSRM/osrm-backend#5707]
Hi there! 
I wonder, if I can retrieve osm way_id directly from osrm routing response? 

For now, I just map node_id to way_id after parsing the route service response, however, since I can see street names in response, I though that I somehow can get way_ids. Did not found any parameter API documentation related to that. 

I saw #4591, however it was in 2017, and I see #5325 ticket proposing this feature, but I could not figure out, whether it is implemented or not.

**Comment by danpat** [comment]
No - OSRM doesn't store the `way_id`.  One way folks have worked around this in the past is to modify the Lua scripts to embed the OSM way ID into the `.name` field.  This can have some consequences for the quality of the turn-by-turn instructions emitted, but should work if you don't care about that.

**Comment by AlexKaravaev** [comment]
@danpat Okay, will look this up then. Thank you. Closing this.
