### ISSUE TITLE
No alternatives route when requesting with intermediate point

### ISSUE THREAD

**Issue by AlexKaravaev** [Project-OSRM/osrm-backend#5708]
How can I find alternative routes, when requesting route with intermediate points? 

For example here, I set alternatives to 20, and set intermediate route point, which results in one route.
![photo_2020-04-07_14-19-00](https://user-images.githubusercontent.com/30314738/78663858-8e5f4280-78db-11ea-8605-638f166f1882.jpg)

Here i set alternatives to 20, and no intermidate point, which results in quite a lot of alternatives
![photo_2020-04-07_14-19-12](https://user-images.githubusercontent.com/30314738/78663840-83a4ad80-78db-11ea-8975-625478273d14.jpg)

**Comment by AlexKaravaev** [comment]
Anyone?

**Comment by systemed** [comment]
Alternative routes don't support via points:

https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/plugins/viaroute.cpp#L119

**Comment by AlexKaravaev** [comment]
@systemed Thank you, I have looked it up. Do you have any ideas, whether it is going to be implemented ? At first glance, I would say that it is restricted by the algorithm to do that, but I am not sure though

**Comment by systemed** [comment]
There isn't really any active development happening on OSRM right now, so it won't be implemented unless someone interested steps up and provides a patch (and alternatives are a Hard Problem so I think that's unlikely).

**Comment by AlexKaravaev** [comment]
@systemed Alright, cheers. Closing then.
