### ISSUE TITLE
Grabbing all from/to osm ids

### ISSUE THREAD

**Issue by knasti** [Project-OSRM/osrm-backend#5712]
Is it possible to export all from/to osm_ids for applying [traffic data](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) to a graph in OSRM?

I understand that I can use annotations on [match service](http://project-osrm.org/docs/v5.7.0/api/#match-service), hence issue #5473, but that's, as I understand, geared toward GPS coordinates representing the speed of a single edge, and not to grab all of from/to osm_ids.

The points I have are traffic measurements, which I want to represent the speed for multiple edges, but I have found no way of joining that information onto the OSRM graph, as I don't know which from/to osm id pairs are available.

I've tried to grab the ids from the NAME.osrm.edges file, as I thought that it might contain the node ids, but that's a binary file, so it's hard to deal with.

Lastly I tried to create a graph with [OSM2PO](https://www.bostongis.com/PrinterFriendly.aspx?content_name=pgrouting_osm2po_1) and use the from/to osm_ids from that graph to mimic the OSRM's ids. This resulted in 120.717 edges updated with the new speeds, but also 6.520.373 edges that still use default values from the lua file. So the OSRM graph does not seem to be built the same way as OSM2PO.

Any help pointing me towards a solution is appreciated.

**Comment by wangyoucao577** [comment]
OSRM uses original(OSM Node) from/to node ID for traffic injection, which means you can grab all nodeIDs from OSM PBF directly.       
Since OSM's nodes are not fully connected, you'd better to grab ways from OSM also, because every way will have a series of nodes. Then you're able to know all connected nodes. Actually if you can mapping your traffic data on way, you don't need to build graph since every node pairs of way can be as input for OSRM.

**Comment by knasti** [comment]
Thanks @wangyoucao577! I'll definitely try that out 👍

**Comment by knasti** [comment]
This did indeed work. If other GIS people stumble upon this issue, be aware that QGIS does not load all nodes that are part of the OSRM graph from the osm.pbf file. I loaded the osm.pbf file into Postgres with osm2pgsql, and prepared the data in there.

Thanks again wang.

**Comment by nanilooper** [comment]
@knasti  can u share the queries you ran on Postgres to achieve the required traffic.csv from/to node id format ?
