### ISSUE TITLE
Table API fails when annotations flag used

### ISSUE THREAD

**Issue by JedStephens** [Project-OSRM/osrm-backend#5714]
Following the API documentation (latest version): [here](http://project-osrm.org/docs/v5.22.0/api/#table-service)

The example given is:
`http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=duration`

When a request is made the following is returned:
`{"code":"Error","message":"Unrecognized parameter 'annotations'"}`

This error occurs with any Table API query when annotations parameter is used.

**Expected behavior:** an API return with status OK.

**Comment by danpat** [comment]
The demoserver is running a slightly older version of the `osrm` codebase without support for the `annotations` flag.  By default, it returns durations, so your current query will work if you remove `annotations=duration`.  If you need distance durations, you'll need to run your own OSRM server.

**Comment by JedStephens** [comment]
> The demoserver is running a slightly older version of the `osrm` codebase without support for the `annotations` flag. By default, it returns durations, so your current query will work if you remove `annotations=duration`. If you need distance durations, you'll need to run your own OSRM server.

Great. All makes sense. Would help to have a pop up or something that says such on the demoserver.
