### ISSUE TITLE
JSON Number(double) Insufficient for Long NodeID

### ISSUE THREAD

**Issue by wangyoucao577** [Project-OSRM/osrm-backend#5716]
We use `annotations=true` to output `nodes` in route response, then we found the output `nodes` may invalid sometimes.     
After investigate, it's caused by the JSON util only has one number type `Number`, which defined as `double`:     
https://github.com/Project-OSRM/osrm-backend/blob/15f0ca8ddaa35c5b4d93c25afa72e81e1fb40c3e/include/util/json_container.hpp#L89-L94
It means whatever the internal number type is, it will be converted to `double` before output. For some long `std::uint64_t`, the value will be cut in this conversion.       

In our test, the nodeID `9280805980001101` will be cut to `9280805980001100`, which results invalid nodeID.     
Here's some test code:      
```c++
// Example program
#include <iostream>
#include <string>
#include <cstdint>
#include <iomanip>

int main()
{
  std::uint64_t id = 9280805980001101;
  double d_id = static_cast<double>(id);
  std::uint64_t convert_back_id = static_cast<std::uint64_t>(d_id);
  
  std::cout << id << std::endl;
  std::cout << std::fixed << std::setprecision(6) << d_id << std::endl;
  std::cout << convert_back_id << std::endl;
}

// output: 
9280805980001101
9280805980001100.000000
9280805980001100
``` 
Full story please refer to https://github.com/Telenav/osrm-backend/issues/276

Any suggestion? Is it possible to have more Number types in the JSON util?  
Many thanks in advance!

**Comment by awgrover** [comment]
The JSON spec does not appear to limit the range of a number at all(!) https://www.json.org/json-en.html. JSON Schema seems to, I think, as 32 bit signed: -2,147,483,648 ... 2,147,483,647 . Google notes a work around of

> a 64-bit integer must be represented as a string in JSON requests/responses. The type property will be set to "string", but the format property will be set to "int64" to indicate that it is a 64-bit integer

As a workaround in this case, is it possible for you to use a string-id instead (i.e. trivially convert to-string for osrm, then convert to-int on return)?

**Comment by wangyoucao577** [comment]
@awgrover  Actually I already returned `string` id as a workaround(see https://github.com/Telenav/osrm-backend/issues/276#issuecomment-615110149 and https://github.com/Telenav/osrm-backend/pull/285).      
However, refer to https://stackoverflow.com/questions/13502398/json-integers-limit-on-size, the number seems unlimited by JSON spec. I think return correctly `uint64` still will be better.
