### ISSUE TITLE
Including original OSM tags in response

### ISSUE THREAD

**Issue by sloreti** [Project-OSRM/osrm-backend#5717]
I have essentially the same question as what was asked in https://github.com/Project-OSRM/osrm-backend/issues/4668, but am opening a new issue as that one is 3 years old and closed. 

I want to use OSRM's `match` service and would like to know if there is a built-in way to include the OSM tags that were use to create the results.

If not, is the prescribed way to do this still to get node ids from the `annotations` of the `RouteLeg` and use a service like [mapbox/route-annotator](https://github.com/mapbox/route-annotator) to retrieve the tags? If I create my own profile, can I accomplish this using `classes`, or I am misunderstanding what `classes` are for?

Thank you!

**Comment by alt-13** [comment]
So far I did not find any other official solution than route-annotator.
I would like to use classes for railway:track_class but the `classes` table is restricted to size 8 and there are more different railway track classes. Why is this array limited?
