### ISSUE TITLE
Missing dependency building the project for Windows

### ISSUE THREAD

**Issue by ssuluh** [Project-OSRM/osrm-backend#5718]
Hi OSRM maintainer,

Even though building in Windows is not officially supported, but would it be possible to provide us of alternate way to resolve the build error when it's trying to download the following file:
`osrm-deps-win-x64-14.0-2017.09.7z`

The following s3 where this file is stored are now forbidden (403):
`Line 55: powershell Invoke-WebRequest https://mapbox.s3.amazonaws.com/windows-builds/windows-build-deps/$env:DEPSPKG -OutFile $env:PROJECT_DIR\$env:DEPSPKG`

**Comment by akashihi** [comment]
I moved test data to Wolt provided hosting, but i do not have a copy of osrm-deps-win-x64-14.0-2017.09.7z

I'll try to figure out, how to make it on my own, but it will take some time. In case you have copy of that file, i can upload it to the same hosting.

**Comment by danpat** [comment]
Last person I know who built/uploaded that file was @oxidase - and I'm not sure if there's script to do it or not.  I've been unable to find instructions for building it, nor a script to do it.

A lot of these deps have fallen victim to an over-zealous S3 bucket cleanup that happened inside Mapbox a few weeks ago.

**Comment by akashihi** [comment]
@danpat Is it originally from https://github.com/mapbox/windows-builds repo?

**Comment by danpat** [comment]
Ah-ha, bingo:

https://github.com/mapbox/windows-builds/blob/master/scripts/build_osrm_deps.bat

**Comment by akashihi** [comment]
Building windows dependencies is not a simple task for a non-windows person. The building script is running some older windows software, which is not distributes anymore, so i can't just run it :) I tried to make build manually, but it takes a lot of time, cause i have to fight with unexplored environment. 

So if there is somebody experienced with Windows, feel free to build it and i will host it. Otherwise it will take some time :)

**Comment by ssuluh** [comment]
@danpat , is what outlined in https://github.com/mapbox/windows-builds/blob/master/scripts/build_osrm_deps.bat is basically all the dependencies needed for osrm-backend windows build or is there more? 

@akashihi , I understand. I'll try to help, but I'm not super familiar with this tooling either.

**Comment by danpat** [comment]
@ssuluh As far as I know, yes, but I've never built them myself.

Windows has always been a bit of a second class citizen, and even more so since Docker became a thing, and WSL appeared on the scene.

**Comment by akashihi** [comment]
@ssuluh So, i made deps file: https://project-osrm.wolt.com/windows-build-deps/osrm-deps-win-x64-14.2-2019.01.7z

Will integrate it to the appveyor soon.

**Comment by ssuluh** [comment]
> @ssuluh So, i made deps file: https://project-osrm.wolt.com/windows-build-deps/osrm-deps-win-x64-14.2-2019.01.7z Built with MSVC2019 and up-to-date libraries. I was able to build the OSRM and binaries are starting, but haven't checked, whether it actually works.
> 
> Will integrate it to the appveyor soon.
Thank you very much. I'll test and let you know.

**Comment by akashihi** [comment]
@ssuluh @danpat So i updated appveyor build and it, well, builds. But it requires more ram for tests and appveyor vm doesn't have enough. Is there a way to make it bigger?
