### ISSUE TITLE
Bicycle network preference 

### ISSUE THREAD

**Issue by wieringen** [Project-OSRM/osrm-backend#5719]
There are different types of bicycle road networks. In OSM these different road networks are tagged with the tag: [network](https://wiki.openstreetmap.org/wiki/Tag:network%3Drcn).
Some networks are designed to be functional and others try to provide more scenic routes. 

Is there a way to prefer certain networks over others? Ideally I would like to give more weight to ways tagged with "network=rcn".

**Comment by systemed** [comment]
#5092 is an (unmerged) PR that uses cycle route relations to influence weighting. It should be reasonably simple to get this to look at the relation `network` tag and have a higher uplift for `network=rcn`.
