### ISSUE TITLE
way tags response 

### ISSUE THREAD

**Issue by barenn7** [Project-OSRM/osrm-backend#5721]
Hi ! 

I am using osrm to get the nearest road (2 nodes). This works fine.

Do you happen to know how to output with the nearest road also the tags of the way by osm  ?

Thank you for your help.
Best regards

**Comment by danpat** [comment]
OSRM does not store the way ID in the routing graph, so it cannot be returned.  It is not a general-purpose index of all the OSRM metadata, and doesn't store all tags (only the ones needed for making a routing graph, and much detail is dropped).

If you need some specific tags, one thing that some folks have done is modify `car.lua` and embed the tag values in the `name` field - then it'll be returned as the street name in the API response.

**Comment by barenn7** [comment]
Thank you very much for your reply.

I am able to read the street name of the 'nearest'.

But again, my aim is to be able to read the tags like highway_junction, motorway, A9, E45 etc....

It works when I read .osm.pbf file with python but i need to make it faster. 

A solution waould be to extract directly with 'nearest' the tags of the road.

Thank you again for your help
Best regards

**Comment by danpat** [comment]
I don't think you understood my comment.  OSRM does *not* store all tags.

You can "cheat", and embed all the tag values you want into the `name` field by modifying this section of `car.lua` before processing files:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua#L39-L42

isntead of simply setting

```
result.name = name
```

You can do something like 

```
result.name = name .. ",highway=" .. way:get_value_by_key("highway") .. ",oneway=" .. way:get_value_by_key("oneway")
```

It's not pretty, but it works.

If you want a general purpose queryable database of OSM data, you might be better off looking at some of the tools to load OSM data into a database with spatial capabilities, like https://wiki.openstreetmap.org/wiki/Osm2pgsql

**Comment by barenn7** [comment]
Hi,

Thank you again for your answer.

This is not pretty but it could work for what i am trying to do.

Unfortunatly, I looked for result.name in car.lua and i was not able to find it. 
I would like to edit the response as you said in the previous comment.

Do you know how i could fix that ? Where can i modify in car.lua ? 

Best regards,

**Comment by danpat** [comment]
I included a link to the file you need to modify in my comment.  Look in `lib/way_handlers.lua`

**Comment by barenn7** [comment]
Thank you very much for your reply,
The solution I used is osmium library to extract all .osm map info ! 

Thanks again for your help
