### ISSUE TITLE
getting relative position of matched points on OSM lines

### ISSUE THREAD

**Issue by aminissn** [Project-OSRM/osrm-backend#5722]
Hi all,
I am currently using the API for map matching and was wondering if one can (in an easy way) find out the position of the matched points on the corresponding OSM links? I am interested in doing aggregated speed analysis from the GPS data I have would like to split the OSM links into segments of e.g. 100m and aggregate the speed data for each segment.  
Thanks and sorry if this is not the right place to ask such a question!

**Comment by danpat** [comment]
For cross-referencing against OSM, two things will help:

  1. Use the `annotations=nodes` parameter - this will return a sequential list of OSM node pairs that are connected.  This makes it easy to directly look up OSM geometry.
  2. The `tracepoints` member in the matching result contains the location on the OSM geometry that the point was snapped to.  Each tracepoint corresponds to an input point in your request.

**Comment by aminissn** [comment]
Thanks for the quick answer. I set the "annotations=nodes" and I get the OSM node IDs in return. However, I assume these nodes are not identical to the matched points. Regarding the second answer, I don't see the location on OSM geometry in the response of tracepoints. I only get geometry points which I can't figure out on which OSM way and with which offset from the beginning of that way they are located.
