### ISSUE TITLE
OSRM is unable to generate Table for --max-table-size

### ISSUE THREAD

**Issue by IsaacDm** [Project-OSRM/osrm-backend#5725]
Hi team, I have built a OSRM on a server with following specifications:
1. Sever OS: CentOS 7
2. Cores: 32
3. RAM: 256 GB

Application is running on a docker:  sudo docker run -t -i -p 5000:5000 --cpus=32 --memory 192g -v "${PWD}:/data" osrm/osrm-backend osrm-routed --max-table-size=50000 --threads=1024 --algorithm=mld /data/us-latest.osrm

When I am trying to generate a table, which is having 40000 locations, I'm getting "too many arguments" error.

Please suggest a fix.

Thanks!!

**Comment by danpat** [comment]
Please supply more detail.  Is it an error when Docker is starting up, or when you make the request?  Do you see the error in the `osrm-routed` output, or on the client side?

`Too many arguments` sounds like an error with whatever client you're using to make the HTTP requests.

**Comment by IsaacDm** [comment]
Hi @danpat, thanks for responding.

No the docker is started without any issue. I'm getting this error when I am passing the curl http request through my python code. There are around 40000 coordinates for which i'm trying to generate a table.

Following is my http request which has generated 6*6 matrix as expected. 

str1 = "http://0.0.0.0:5000/table/v1/car/-99.803795,32.405683;-106.52510590000001,35.0863813;-80.267726,40.6102386;-117.9683223,33.8320893;-117.7911403,33.86424;-88.3737088,44.2657304;-97.1144198,32.735492"

But if I extend the same http request with 40000 coordinates, I'm getting the following error:

[centos@ip-172-31-25-171 src]$ python fullmatrixgen.py
Traceback (most recent call last):
  File "fullmatrixgen.py", line 14, in <module>
    data = duration_calculate(str1)
  File "fullmatrixgen.py", line 6, in duration_calculate
    process = subprocess.run(['curl', str1], check=True, stdout=subprocess.PIPE, universal_newlines=True)
  File "/home/centos/jupyterNotebook/anaconda3/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/centos/jupyterNotebook/anaconda3/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/centos/jupyterNotebook/anaconda3/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'curl'

**Comment by danpat** [comment]
This is a client-side error in your code, not an OSRM problem.  Sounds like you've exceeded the maximum command length your operating system supports.

You'll need to switch to not using `subprocess` and `curl`, but rather maybe something like https://docs.python.org/3/library/http.client.html
