### ISSUE TITLE
Get osm nodeid using coordinates for csv traffic data files

### ISSUE THREAD

**Issue by minhpc225** [Project-OSRM/osrm-backend#5726]
To use traffic data a csv file including osm node id is required. I have an external data consisting of smaller segments of the osm way which contains the coordinates of osm nodes. How do I get the osm node id using those coordinates?

**Comment by danpat** [comment]
You'd need to do this externally to OSRM - you'd need to store the OSM node IDs alongside the coordinates in whatever system you're using to generate traffic.
