### ISSUE TITLE
Different results between your server and Docker image

### ISSUE THREAD

**Issue by Riccardinho22** [Project-OSRM/osrm-backend#5728]
When I perform the following request to the online server:
curl 'http://router.project-osrm.org/route/v1/driving/-73.99924541608371,40.72151712198445;-74.03027032521503,40.77761395940928?steps=false'

I get this Json as result:
...
"routes":[
      {
         "geometry":"olpwFh~sbMgJfV}BjU_K|EiRlwCcC~OeJdR_Cnl@xCng@aj@`t@yGd]cJgGgr@iS_`Agx@mcBwdACyAzIjAyBsGdHiXsHiGuBcRyG{FiCjG",
         "legs":[
            {
               "summary":"",
               "weight":1794.9,
               "duration":1344.6,
               "steps":[

               ],
               "distance":12462
...
Therefore the distance (12462)  and the duration (1344.6,) are wrong, whereas using the local Docker image with the New York' s map, calling the same request I get the right result:
 "routes":[
      {
         "geometry":"olpwFh~sbMgJfVwA~QcD`J}Fk@aAtSaoA_Eyu@yLsNrBgGoAeN_Esm@u`@yMePae@qYrFrIrQrJwFtR",
         "legs":[
            {
               "steps":[

               ],
               "distance":7404.3,
               "duration":897.7,
I compared the distance's outcome with Google Maps and everything seems ok, why this different results?

**Comment by danpat** [comment]
The server at `router.project-osrm.org` uses Mapbox's traffic data.  This changes results compared to a pure-OSRM approach with no extra traffic data.

**Comment by Riccardinho22** [comment]
Ok thanks

**Comment by Rougree** [comment]
Is there a way to use Mapbox's traffic data (for free) locally (docker) @danpat

**Comment by danpat** [comment]
@Rougree No, but you can buy it by contacting the Mapbox sales team, see https://www.mapbox.com/traffic-data/.

Note to other readers - this ticket is stale, the demoserver is no longer hosted by Mapbox and does not use Mapbox's traffic data.
