### ISSUE TITLE
Reading ways data

### ISSUE THREAD

**Issue by HumamHelfawi** [Project-OSRM/osrm-backend#5730]
Hi,

Similar to `osrm::extractor::files::readNodes` that reads the OSM Node, is there other function(s) to read OSM Ways data (Id,Nodes, uni-directional...) ?

I searched but did not find a direct function to find OSM Ways. I think I should load one of the OSRM graphs and extract Ways from it but not sure.

Any clue is much appreciated!

Thanks!

**Comment by danpat** [comment]
Ways are not stored by OSRM - after parsing into a memory structure, they're split into the graph edges that are later used to construct the routing graph.  The concept of a "way" is lost at that point.
