### ISSUE TITLE
Additional parameters make API return InvalidQuery

### ISSUE THREAD

**Issue by thangdc94** [Project-OSRM/osrm-backend#5731]
I'm currently using mapbox to send request to OSRM backend.
Mapbox will send request with some additional parameters (E.g: `language=en`), these parameters have not been listed in OSRM API documenation. It means that OSRM is currently not using these param and should accept it as unknown.
But when send request with additional parameters, OSRM return error code `400` and `"code": "InvalidQuery"`
```
localhost:5000/route/v1/driving/105.8177375793457,21.022341604999767;105.79911231994629,21.023303016107928?language=en
```
Is there any config to make OSRM accept additional parameter?

**Comment by thangdc94** [comment]
I found [this unit test](https://github.com/Project-OSRM/osrm-backend/blob/master/unit_tests/server/parameters_parser.cpp#L43) in OSRM source code.

I think you guys intentionally throw error if there is any unknown parameter in URL. Can anyone explain me the reason why OSRM server should allow only known parameters?

**Comment by danpat** [comment]
I don't think there's any reason other than it was the developer's opinion that this is how we should do it.  The best argument for this behaviour (strict rejection of non-conforming requests) is probably described here:

https://en.wikipedia.org/wiki/Robustness_principle#Criticism

It is not required that you use `osrm-routed` to interface with OSRM itself - you can write your own HTTP server and accept any parameters you like, transforming them into the OSRM C++ library interface.

**Comment by thangdc94** [comment]
@danpat  Thanks for your advice. I modified `grammar` to add `unknown_param_rule`  in  `/include/server/api` to make `osrm-routed` work in our project.
