### ISSUE TITLE
U-turn when road splits in two

### ISSUE THREAD

**Issue by ben-hudson** [Project-OSRM/osrm-backend#5733]
I have the following intersection:
![Screenshot from 2020-05-06 15-15-20_1](https://user-images.githubusercontent.com/7964300/81221016-3e45cf80-8fb0-11ea-91dc-50ed0a89b740.png)

OSRM is producing the following route:
![Screenshot from 2020-05-06 15-15-20_2](https://user-images.githubusercontent.com/7964300/81222314-17889880-8fb2-11ea-92b6-5e6601ed075b.png)

I am guessing this route is permitted because the turn angle right at the arrow is not very sharp (~70 degrees), even though the turn is a u-turn.

Which parameters control how the angle of this turn is calculated? I have tried changing [LOOKAHEAD_DISTANCE_WITHOUT_LANES](https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/intersection/coordinate_extractor.cpp#L30) from 10m to 20m, with no effect.

Thanks!

**Comment by danpat** [comment]
The `LOOKAHEAD_DISTANCE_WITHOUT_LANES` value only affects whether OSRM *announces* a u-turn in the step-by-step instructions in the result.

To prevent this maneuver completely, you'll need to put a turn-restriction-relation in place (assuming you're constructing your own network here, based on the image).  You'll probably need the restrictions in place on each of these intersections to prevent the routing engine from finding weird shortcuts.

**Comment by ben-hudson** [comment]
Thanks for your response!

Is it correct that OSRM only sees the turn as a u-turn if it starts and ends on the same node? Otherwise it sees a sharp turn?

Then prevent this specific turn from happening, I would need to add a no_right_turn relation, not a no_uturn relation correct?

**Comment by danpat** [comment]
Yes, both of those statements are correct.  For the restriction relation, it's sufficient to have a `from` way, `via` node, and `to` way, and a `type` that begins with the string `no_`  - whether it's `no_right_turn` or `no_uturn` doesn't matter.

**Comment by ben-hudson** [comment]
Ok, I'll try implementing that. Thank you!
