### ISSUE TITLE
Distance field in tracepoints of match service

### ISSUE THREAD

**Issue by nurgasemetey** [Project-OSRM/osrm-backend#5734]
I have one question , what is the meaning of  `distance` field in `tracepoints`?

**Comment by danpat** [comment]
`tracepoints` are the location on the road network that each input coordinate snapped to (all the tracepoints will be right on top of the map geometry).

The `distance` property is the distance from the coordinate you supplied in the URL to the location it snapped to on the road.

**Comment by nurgasemetey** [comment]
Thanks for quick answer! Offtopic maybe, for example if particular tracepoint's legs shows several nodes(more than 2), does it mean that OSRM couldn't determine exact segment between two nodes?

**Comment by danpat** [comment]
I'm not sure I understand your question - I think you may misunderstand the structure of the API response.

Each `tracepoint` matches up with one of your input coordinates.

Each `leg` represents the path between *two* tracepoints.  Depending on how far apart your points are, that leg can span an arbitrary amount of OSM geometry, which may include many nodes.

If your input coordinates are very close together, then I'd suggest you've got a pair of input coordinates that are on either side of an OSM node.  In that case, the `leg` will have the node *before* the first input coordinate, the node *between* and the node *after* the second input coordinate.  There may be more *between* nodes, depending on the OSM geometry at that location, and how far apart your input coordinates are.

**Comment by nurgasemetey** [comment]
Thanks, that's what I meant. Thanks for explanation!
