### ISSUE TITLE
turn penalty setting in foot profile

### ISSUE THREAD

**Issue by mohamin1995** [Project-OSRM/osrm-backend#5735]
Hi,
how can I consider turn penalty for the foot profile correctly? in the foot profile, only u_turn penalty exists. I added turn penalty in profile properties and also the following line in the process_turn function:
**turn.duration = turn.duration + profile.properties.turn_penalty**
after it, I extract again.
I change my turn penalty value but there is no difference between result routes.
I use 5.0.18 version.

Thanks

**Comment by chaoyu0804** [comment]
Hi, maybe you can check the profiles/bicycle.lua for how to set up turn penalty. I guess the turn penalty parameter is set by **profile.turn_penalty** but not **profile.properties.turn_penalty**
