### ISSUE TITLE
Couldn't  run with new (truck.lua) profile

### ISSUE THREAD

**Issue by turing-cs** [Project-OSRM/osrm-backend#5736]
I'm trying to extract a map using osrm-extract map.osm. Then I have created my custom profile named as "truck_profile.lua".  I have clone osrm-backend code to local drive. After that i have added my truck profile under [osrm-backend/profiles/](https://github.com/Project-OSRM/osrm-backend/tree/master/profiles). 

While running below command docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/truck_profile.lua /data/berlin-latest.osm.pbf with mapping PWD , i am getting below error.

**[error] Profile /opt/truck_profile.lua not found!**

Any help would be appreciated.

**Comment by grib0** [comment]
I think it is a volume mapping problem, did you rebuild a new docker image with your truck_profile.lua inside ? If not you should add a volume mount with your truck_profile.lua
