### ISSUE TITLE
Table API - Unrecognized parameter 'annotations', also docs are missing information about annotations parameter

### ISSUE THREAD

**Issue by AasmundEndresen** [Project-OSRM/osrm-backend#5737]
Read conversation below.

![image](https://user-images.githubusercontent.com/28097617/82036162-d4f54900-96a0-11ea-8dbe-9310c95d373d.png)

Using the provided examples from Github produces the error above.

First edit:
> I am upgrading this issue from a question to a Feature Request - as it seems the endpoint currently can't serve my intended purpose.
> 
> It would be very useful if the Table endpoint would return more then just the `durations`-Matrix, in many cases its useful to compare other aspects of the Route between two Waypoints, such as destination, geometry or steps. Is it possible to change the Table API to return a `routes`-matrix containing the Route objects between the endpoints instead of just durations?  Or at the very least be able to specify what aspect of the Route you want to compare and thus get alternative responses with a `destinations` matrix or a `steps` matrix for example?

Original issue:
> Hi - I'm running an instance of OSRM on a server, and I'm trying to figure out the shortest distance from point A to point B, C, D, E, etc...  I don't want to use the Routing API for this as it would be many more requests then necessary, so after a little digging around I figured out I'm supposed to be using the Table API.
> 
> I find the documentation a little confusing though, and can't figure out what I'm doing wrong.
> 
> I'm supplying all coordinates seperated as `latA,lonA;latB,lonB;latC,lonC...` and then at the end of the string setting `?sources=0&destinations=1,2,3...`.
> 
> I'm not as interested in the durations as I am in the distances, but I'm confused because in the example from the documentation if I set the sources/destinations like this, there will also be a distance set on the one element that is returned in the sources array.  So what is this the distance to?  And then when I attempted with my own coordinates (which provides a distance when I use them in the Routing API), the distance to all destination are suddenly all 0.
> 
> Am I using it wrong or is the data just unreliable?

**Comment by jcoupey** [comment]
Looks like you have the coordinates ordering reversed. OSRM uses `lon,lat` and you mention `lat,lon`. That would explain the 0 distances, because then random points outside your dataset get snapped to the same nearest node.

**Comment by AasmundEndresen** [comment]
Actually I just typed that up in a hurry for the example - coordinates are correct - but it seems that the coordinates from the snapped node returned in a Waypoint object gives this result.

And I think this also explains my other problem, the distances seem way off.  This is because the 'distance' in a Waypoint object seem to refer to the distance from the coordinate to the snapped node.  This is a bit confusing, especially since its not mentioned at all in the documentation about the Waypoint objects, but also because 'distance' in a Route object refers to the distance between the Waypoint objects.

So it seems I cannot use this endpoint either for my purpose, because it only returns duration and not distance between Waypoints.

**Comment by jcoupey** [comment]
You need to use the `annotations` option to get distances, see [table service docs](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#table-service) with a couple examples below.

**Comment by AasmundEndresen** [comment]
> You need to use the `annotations` option to get distances, see [table service docs](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#table-service) with a couple examples below.

Thank you - this information was missing in http://project-osrm.org/docs/v5.15.2/api/?language=cURL#table-service

**Comment by AasmundEndresen** [comment]
> You need to use the `annotations` option to get distances, see [table service docs](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#table-service) with a couple examples below.

Actually when attempting (just by copy + pasting from the examples) what you linked I get the following error:
`{"code":"Error","message":"Unrecognized parameter 'annotations'"}`

So this functionality doesnt appear to be working

**Comment by jcoupey** [comment]
The ability to retrieve distance matrices with table requests was [added in `5.18.0`](https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#5180).

This is why you did not see the option for previous versions. You'll have to upgrade in order to use this feature.

**Comment by danpat** [comment]
Yeah - the demoserver is not running the latest `osrm-routed`.
