### ISSUE TITLE
OSRM route crash

### ISSUE THREAD

**Issue by tniira** [Project-OSRM/osrm-backend#5738]
[hs_err_pid17206.log](https://github.com/Project-OSRM/osrm-backend/files/4638657/hs_err_pid17206.log)
Hello!
I'm using the latest libosrm from master (v5.22.0?) which is called using JNI from Java code. The routing engine starts fine, but I get 
"`SIGSEGV (0xb) at pc=0x00007f2430ee1420, pid=17206, tid=0x00007f246572e700`"
exception when calling route method of the engine. Please, see full exception details and environment details in attached log file.

I will set up the routing machine as follows:

```
EngineConfig engineConfig;
engineConfig.algorithm = EngineConfig::Algorithm::MLD;
engineConfig.max_locations_distance_table = 110;
engineConfig.max_alternatives = 3;
engineConfig.use_shared_memory = false;
const char *lpath = env->GetLocalPath(path, JNI_FALSE);
log (lpath);
engineConfig.storage_config = storage::StorageConfig(lpath);

try {
    log("Starting OSRM engine...");
    OSRM routing_machine = OSRM(engineConfig);
    log("Started OSRM engine!");
}
```
And then the route parameters and the actual call:
```
        RouteParameters route_parameters;
        route_parameters.steps = false;
        route_parameters.alternatives = false;
        for (int i=i; i<pairArray.size(); i++) {
            std::pair<double,double> current = pairArray.at(i);
            double lat = current.first;
            double lng = current.second;
            route_parameters.coordinates.push_back(get_location(lng,lat));
        }
	// route_parameters.coordinates: [(62.6012, 29.7632), (62.365, 29.4425)]
        engine::api::ResultT result = json::Object();
        log("Calling Route...");
        engine::Status result_code = routing_machine->Route(route_parameters, result);
        log("Route: result_code " + std::to_string(result_code);
```
Any idea what might be the issue?

**Comment by systemed** [comment]
Have you tried making the same request through osrm-routed (i.e. as an HTTP request), and using the standard Node.js interface, to narrow down whether it's a JNI problem?

**Comment by danpat** [comment]
I agree with @systemed - try with `osrm-routed`.  If that works, then it narrows things down to how you're calling out to OSRM with your JNI bindings.

If `osrm-routed` works, next thing I'd try is writing a minimal Java test case that triggers the problem, re-compiling OSRM in debug mode (do `cmake -DCMAKE_BUILD_TYPE=Debug .. && make`), then run your test case via gdb - when it segfaults and pauses, you can get a backtrace by typing `bt`, and it'll point to the actual code location where the segfault occurred.  That'll tell us a lot more about what the problem is.

**Comment by tniira** [comment]
What I tried to do is actually _an almost minimal Java test case._ Just the start and endpoint coordinates are passed as parameters. When I print those coordinates just before calling the route() in C++ they are as follows: [(62.6012, 29.7632), (62.365, 29.4425)]. Everything else related to OSRM is done in C++ (as you can see in my initial message). Btw. did you take a look at hs_err_pid17206.log?

**Comment by tniira** [comment]
I messed up with one pointer, sorry! :-( Now works fine!
