### ISSUE TITLE
[Question] docker performance (of osrm-routed)

### ISSUE THREAD

**Issue by bjtaylor1** [Project-OSRM/osrm-backend#5740]
Does using a docker image have any impact on performance of osrm-routed vs extracting and contracting on the machine itself?
Mainly in terms of total osrm-routed response speed rather than time it takes to extract and contract, but pointers to the latter welcome as well.

i.e. is it be expected that a route request to an osrm server using docker would take any longer than the same route request to an osrm server that had extracted and contracted the data itself?
Either due to latency in docker passing on the request and marshalling the response to/from osrm-routed, or in terms of osrm-routed not running as fast within the docker container as on the machine itself.

Can anything affect the answer, e.g. use of STXXL, swap files, etc.

**Comment by danpat** [comment]
I would say generally no, no major impact.  However, you should always benchmark, as your own setup may have some peculiar restriction that leads to performance impact.

**Comment by SiarheiFedartsou** [comment]
Stale.
