### ISSUE TITLE
Build Dependencies and Run Dependencies

### ISSUE THREAD

**Issue by toton6868** [Project-OSRM/osrm-backend#5742]
This is not a bug. I just wanted to know within the below dependent tools which can be defined as a build dependency and which can be marked as a run dependency. I have a plan to remove the run dependency tools which doesn't need to run OSRM-Backend

```
sudo apt install build-essential git cmake pkg-config \
libbz2-dev libxml2-dev libzip-dev libboost-all-dev \
lua5.2 liblua5.2-dev libtbb-dev
```

**Comment by akashihi** [comment]
this list looks correct i think

**Comment by toton6868** [comment]
@akashihi Sir, I actually didn't mean the list is correct or not. I have successfully installed the OSRM backend with the provided list. But now I want to remove those tools from this list which have no dependency while running OSRM. Thanks

**Comment by akashihi** [comment]
I understood you incorrectly :) to run OSRM you do not need any of those, *but* you need their runtime counterparts:

* libbz2-1.0
* libxml2
* libzip5
* liblua5.2-0
* libtbb2
* libboost-atomic1.71.0
* libboost-chrono1.71.0
* libboost-date-time1.71.0
* libboost-filesystem1.71.0
* libboost-iostreams1.71.0
* libboost-program-options1.71.0
* libboost-regex1.71.0
* libboost-system1.71.0
* libboost-thread1.71.0

package names are valid for latest ubuntu.
