### ISSUE TITLE
Routing on foot appears to be completely off

### ISSUE THREAD

**Issue by stdedos** [Project-OSRM/osrm-backend#5743]
![image](https://user-images.githubusercontent.com/133706/83077808-e109df00-a080-11ea-9ad2-0f9f5065792e.png)

I can manually plot a route ~450m long vs the 725m reported for this one

**Comment by petschge** [comment]
To reproduce: that is the area around https://www.openstreetmap.org/#map=17/60.15269/24.88171

**Comment by petschge** [comment]
I guess the problem is that https://www.openstreetmap.org/way/30091349 is access=private instead of access=destination

**Comment by danpat** [comment]
Agreed, the problem here the `access=private` - you can move the origin location slightly to the south-west and find a much shorter path.  OSRM is finding the shortest path given that https://www.openstreetmap.org/way/30091349 is not considered passable.

**Comment by danpat** [comment]
Note: I deleted a comment that contained exact coordinates at the request of the original poster.  I left the remaining comments as still helpful.
