### ISSUE TITLE
Install on macOS Catalina 10.15.5 

### ISSUE THREAD

**Issue by LucianoIF** [Project-OSRM/osrm-backend#5747]
Dear I am getting the following error when I run the command "osrm-extract"

dyld: lazy symbol binding failed: Symbol not found: __ZN5boost16re_detail_10710027cpp_regex_traits_char_layerIcE4initEv
  Referenced from: /usr/local/bin/osrm-extract
  Expected in: /usr/local/opt/boost/lib/libboost_regex.dylib

dyld: Symbol not found: __ZN5boost16re_detail_10710027cpp_regex_traits_char_layerIcE4initEv
  Referenced from: /usr/local/bin/osrm-extract
  Expected in: /usr/local/opt/boost/lib/libboost_regex.dylib

Abort trap: 6

Any help suggestions?
Thanks

Luciano

**Comment by danpat** [comment]
How did you obtain OSRM on your mac?  The error seems to be that you've got a version of the boost libraries that aren't compatible with the binaries you have.

**Comment by LucianoIF** [comment]
Hi Daniel, I tried to install it in two ways: 
 - the first using git; and 
 - the second I used the brew according to site: https://brewinstall.org/Install-osrm-backend-on-Mac-with-Brew/.

Thanks for your help

**Comment by danpat** [comment]
I have no idea who maintains the OSRM brew package, but it looks like it's broken.

I would recommend you get Docker for Mac and use the published Docker images from https://hub.docker.com/r/osrm/osrm-backend
