### ISSUE TITLE
Unexpected behavior of traffic data

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5748]
hello
I'm using OSRM v5.18 for routing. I provide a traffic csv containing speed and rate columns, but the result is not the same as csv. I check the rate value in debug tiles and the value is different from csv (for example I set the rate column for all segments to 200 but the debug tiles show a rate value between 18.5 to 23.5)
How can I fix it?

**Comment by abdulwaheedsyed** [comment]
I am also looking for a solution for this.
