### ISSUE TITLE
match result looks bad

### ISSUE THREAD

**Issue by ChiWai-Choi** [Project-OSRM/osrm-backend#5749]
This is a great project. When using the match service, there are many gaps in the returned results. I have no idea.

### **This is my code:**
![Snipaste_2020-06-04_10-12-30](https://user-images.githubusercontent.com/22850130/83707176-f5834400-a64b-11ea-84f3-ef047bec781b.png)

### **This is the result that looks bad,that red point from requests and blue point from responses**
![Snipaste_2020-06-04_09-35-30](https://user-images.githubusercontent.com/22850130/83705731-4ee97400-a648-11ea-926a-9a0908a7750d.png)
![Snipaste_2020-06-04_09-36-25](https://user-images.githubusercontent.com/22850130/83705761-5ad53600-a648-11ea-94c8-8e00fe0ab0a1.png)
![Snipaste_2020-06-04_09-36-42](https://user-images.githubusercontent.com/22850130/83705789-6de80600-a648-11ea-9679-733eca0bd3a8.png)

**Comment by danpat** [comment]
Where does your map data come from?  I can see that some of the matches don't align with any of the underlying OpenStreetmap geometry.

**Comment by ChiWai-Choi** [comment]
Thank you for your reply. @danpat 
My data comes from osm download.geofabrik.de, as follows:
![Snipaste_2020-06-04_10-39-10](https://user-images.githubusercontent.com/22850130/83709093-62004200-a650-11ea-9ab2-26cc0c28f8f7.png)

I think that some of the matches align with some of the underlying OpenStreetmap geometry.
It looks like some roads are missing。
![Snipaste_2020-06-04_10-40-58](https://user-images.githubusercontent.com/22850130/83709346-e4890180-a650-11ea-9f93-e4bfc38e7aac.png)

**Comment by ChiWai-Choi** [comment]
When I import the data, they are the default parameters.
My debug map as follows:
![Snipaste_2020-06-04_11-16-27](https://user-images.githubusercontent.com/22850130/83711167-0e442780-a655-11ea-91aa-e94a86ad2dfb.png)

**Comment by danpat** [comment]
Ah-ha, that debug map is very telling.  There are whole sections of roads missing from your routing graph.

I think I can see the problem, for example, this section of road:

https://www.openstreetmap.org/way/254390565

has the tag `construction=motorway`.  By default, OSRM will exclude roads with construction tags on them.  I suspect this tag is stale.

You should modify `car.lua`, and comment out or remove this line:  https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L136

You will need to re-generate the routing files.  After you do that, check the debug map again and make sure those intersections are no longer pink, and that there are roads with speed values visible where you expect them to be.

**Comment by ChiWai-Choi** [comment]
Thank you again, my problem has been solved according to your suggestion. @danpat 

Another topic：

**Comment by danpat** [comment]
@ChiWai-Choi OSRM uses https://github.com/mapbox/vtzero to generate vector tiles on the fly.  You must be comfortable writing C++ to use it (see https://github.com/mapbox/vtzero/blob/master/doc/writing.md for examples).

What does your heatmap represent?

**Comment by ChiWai-Choi** [comment]
@danpat  Thank you for the detailed answer. The heatmap can display the following data:
1. How often the vehicle passes a certain section(this map)
2. Road section real-time congestion(to do)
3. Frequent disconnection of gps device(to do)
...  

All base the map match server. I am trying to do these things with the project' match server.

My English is terrible, I don't know if I express it clearly.

**Comment by danpat** [comment]
Your English is better than my <insert any other language here> I'm sure.

I understand what you're trying to do.  The big problem will be that when you view a heatmap of *all of China*, there is a _lot_ of geometry to process and render.

Fast dynamic maps of large geographic areas are normally achieved by simplifying the geometry ahead of time.  If you tried to get OSRM to generate an overview map of all of China, it would be pretty slow too, as it would render every road.

The key to faster rendering is to reduce the amount of work done at display time - remove roads from tile generation that aren't visible at the high-level, reduce the detail in road geometry, and possibly pre-generate the simplified details so you don't have to generate them each time for the high zoom level.

I don't have any experience with Geoserver unfortunately, so I can't give you anything more specific than that.

**Comment by ChiWai-Choi** [comment]
Your suggestions have helped me a lot.
Thank you again!
