### ISSUE TITLE
is OSRM back-end free server down?

### ISSUE THREAD

**Issue by abe542** [Project-OSRM/osrm-backend#5750]
I am using the osrm package in R, but when I try to use the osrmTable function  I get this error

`
![image](https://user-images.githubusercontent.com/66446691/83817802-541be280-a68b-11ea-983b-11b418e8b2bd.png)

_Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later._

Apache/2.4.38 (Debian) Server at router.project-osrm.org Port 80
`
The current query i am trying to do is this: 

_http://router.project-osrm.org/table/v1/driving/-74.07346,4.64830;-74.06948,4.61908;-74.07326,4.62201;-74.07478,4.63126;-74.06390,4.63880;-74.07511,4.64082;-74.07643,4.63453;-74.07549,4.62874;-74.05969,4.64102;-74.07346,4.64830;-74.06948,4.61908;-74.07326,4.62201;-74.07478,4.63126;-74.06390,4.63880;-74.07511,4.64082;-74.07643,4.63453;-74.07549,4.62874;-74.05969,4.64102?sources=0;1;2;3;4;5;6;7;8&destinations=9;10;11;12;13;14;15;16;17_

I don't know if my querys are wrong so i tried to use the examples from here: }

http://project-osrm.org/docs/v5.5.1/api/#table-service 

Those are the available examples

# Returns a 3x3 matrix:
curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219'

# Returns a 1x3 matrix
curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?sources=0'

# Returns a asymmetric 3x2 matrix with from the polyline encoded locations qikdcB}~dpXkkHz
curl 'http://router.project-osrm.org/table/v1/driving/polyline(egs_Iq_aqAppHzbHulFzeMe`EuvKpnCglA)?sources=0;1;3&destinations=2;4'`

the first and second one seems to look fine, but the thrid one seems to fail. I don't  know if i am doing something wrong, or if the server is having some troubles , but the problem seems to be in source-destinations params. Thank you and sorry for my bad english.

**Comment by danpat** [comment]
It looks like @DennisOSRM has pointed the `router.project-osrm.org` at `routing.openstreetmap.de.`.  I don't have insight as to which OSRM version this server is running.  It also looks like there might be a bad server behind their load balancer (the one returning the "Service unavailable" error).

Maybe @datendelphin can help?  This ticket seems to indicate that the `map.project-osrm.org` domain was moved, but didn't mention that `router.project-osrm.org` also swapped over.

https://github.com/Project-OSRM/osrm-backend/issues/5655#issuecomment-636476676

**Comment by datendelphin** [comment]
The fossgis server currently runs 5.18
The error message seems to come directly from the backend, not from the dispatcher switching between eurasia and americas.

**Comment by datendelphin** [comment]
Fixed, should work now

**Comment by abe542** [comment]
Thank you, I really appreciate your help.  So there was a problem in the backend of the service? I would like to know a bit more about the reason of the problem.

**Comment by datendelphin** [comment]
Not the osrm-backend, but rather the dispatcher: I run the americas as a separate graph the rest of the wrold as another. So the requests need to be forwarded to the correct osrm instance by that dispatcher. And there was a bug in interpreting the query string and splitting on semicolons. See https://github.com/fossgis-routing-server/request-by-coordinate/issues/1
