### ISSUE TITLE
[osrm profile] Adjust weight with a function of node/way distance

### ISSUE THREAD

**Issue by iedmrc** [Project-OSRM/osrm-backend#5752]
Hi

I want to adjust the weight of a node/way according to a function tied to its distance. I thought I can manipulate weight by manipulating `forward_rate` and `backward_rate` here: https://github.com/Project-OSRM/osrm-backend/blob/15f0ca8ddaa35c5b4d93c25afa72e81e1fb40c3e/profiles/lib/way_handlers.lua#L591 But I'm not sure how to get the distance of the node/way. How can I achieve this? 

Thanks!

**Comment by jcoupey** [comment]
> increase the cost of distant jobs

That does not sound totally like a pure routing requirement, as a "distant job" is related to some reference, maybe a depot or vehicle location.

Depending on your use-case, you might be able to toy around with job priorities on the optimization level.

**Comment by iedmrc** [comment]
Hi @jcoupey , it's nice to see you here :)

By saying "distant job", I mean, distant to their (vehicle's) current position on the map. Yes, you are right about priorities but we wondered what can we do at OSRM level to deliver that need. Actually, more or less, it's a research and we were looking for alternative solutions to compare.

**Comment by jcoupey** [comment]
Hi @iedmrc :-)

> distant to their (vehicle's) current position

Yes, that was my point: I don't really see how you could adjust weights on the routing level with a moving reference. The weights are baked into the OSRM data after extraction, while you'd like to adjust them depending on the start point at query time.

**Comment by iedmrc** [comment]
Yeah, but think about that, if we'd increased the values of costs matrix (for a minute, let's assume VROOM gets distance matrix rather than duration matrix as cost matrix) according to the quantity of each entry of the matrix, VROOM would choose the closest jobs mostly. And we could do this by adding such a middleware between VROOM and OSRM that applies an exponential function to each entry of the cost matrix before the matrix reaches to VROOM. That is one case. We want to find another way to apply this idea at the OSRM level. And by using OSRM profiles, we could increase the cost of distance with an exponential function. We have several methods/ideas like this and want to collect more to compare all of them to find best matching for our case. This one might be worst but still we want to test/simulate and observe the results :)

**Comment by jcoupey** [comment]
> VROOM would choose the closest job as first, mostly

I'm not sure I get precisely what you mean here. It could be:

1. you want to have the closest jobs included **first** in a route that also serves some further jobs later on
2. you want to have the closest jobs included in the routes by all means, while others can be unassigned

In the later case, this is already a natural tendency for the optimization results (closest jobs are cheapest to include), and besides that is precisely what jobs `priority` are for in VROOM.

If this turns into a discussion on adjusting costs/inputs for optimization, maybe we should switch to the VROOM repo. ;-)

**Comment by iedmrc** [comment]
> If this turns into a discussion on adjusting costs/inputs for optimization, maybe we should switch to the VROOM repo. ;-)

Totally right. Comments until now give us intuition about the idea. Let us discuss in our team and if we need further help, I'm going to create an issue on VROOM and would appreciate your help!

**Comment by SiarheiFedartsou** [comment]
Stale.
