### ISSUE TITLE
What should be released in the firewall

### ISSUE THREAD

**Issue by LucianoIF** [Project-OSRM/osrm-backend#5755]
Dear, I would like to know what type of access should I request at the firewall so that I can make the request? I already verified that the problem is in the firewall. But I don't know what to request for access.

Thanks

**Comment by danpat** [comment]
@LucianoIF You'll need to provide a bit more information.  What request are you trying to make?

By default, if you launch `osrm-routed`, it'll listen on on TCP port 5000 - but you can change that with the `--port` parameter.

If you want to make requests to `router.project-osrm.org`, then it listens on the standard HTTP ports 80 and 443.

**Comment by LucianoIF** [comment]
Hi @danpat the request I am making is as follows:
http://<my IP>:5000/route/v1/driving/-46.787230,-22.410850;-46.772254,-22.401745?steps=true&alternatives=true&geometries=geojson&overview=full

It is a linux ubuntu 18.04 LTS machine that is on the premises of my university, so the use of the firewall. Talking to the IT people, they told me that in the 1st test they left everything free and it worked. In the second test they released only the 5000 port, it didn't work anymore and finally let packets pass through the ip of the machine in the range of ports 3999-5000.

**Comment by danpat** [comment]
@LucianoIF Assuming you're using `osrm-routed`, then only access to a single TCP socket should be required.  `osrm-routed` listens on a single TCP port for incoming connections, then  uses HTTP over that connection to perform request/response.

It's pretty standard stuff.  I suspect your IT folks did not properly configure the firewall to pass through TCP connections.  The "destination" port will always be 5000, but the "source" port will be random (this is standard TCP behaviour).  If they have limited outgoing packets to "source port 5000" as well, then that won't work.  They must allow outgoing packets on any TCP port.  This is the same as every other TCP-based service.

I don't think there's anything extra that OSRM can do here - I think your IT folks need to re-examine how they configured the firewall.
