### ISSUE TITLE
Docker slowly eats memory

### ISSUE THREAD

**Issue by JohnMartin10000** [Project-OSRM/osrm-backend#5762]
I use osrm/osrm-backend docker instance (happy_knuth), with planet file added. All data was prepossessed and now it just optimizes routes.

It works fine, at the beginning docker needed 64 GB ram to work, now, after four month I see 131.2GiB when I call docker stats command:
MEM USAGE / LIMIT
131.2GiB / 251.9GiB

I tried do restart docker, but after start, memory usage is the same, and after few days, maybe week next 1GB will be needed.

I've osrm/osrm-backend:latest, created 2019-12-18T17:20:30.043307191Z, DockerVersion 18.03.1-ee-3.

What can I do to solve the problem, any advice?

**Comment by nilsnolde** [comment]
Ha, don't think that's a OSRM issue. I got THE EXACT SAME for an unrelated PostGIS container:
https://github.com/kartoza/docker-postgis/issues/253

Slightly newer Docker version: Docker version 18.09.7, build 2d0083d, and CE, not EE.

Maybe it's time to create a issue in Docker's repo (talking to myself).. I'll give a heads-up here when I did that and you can chime in @JohnMartin10000
