### ISSUE TITLE
route service optimisation by distance

### ISSUE THREAD

**Issue by morruth** [Project-OSRM/osrm-backend#5766]
can I tell osrm route service to optimize way by _distance_, not duration?
as annotations=distance in table service.
of course, I can generate map using fixed speed in profile and use it in another instance,
but this method will require almost double amount memory to work
(and time to generate map)

Does exist way to do it WITHOUT 2nd instance of osrm?

**Comment by jcoupey** [comment]
This is something you can adjust right [from the profile](https://github.com/Project-OSRM/osrm-backend/blob/365121dac435610825a131c5185e594f4bd64517/profiles/car.lua#L19-L23), just set `weight_name` to `distance`.

**Comment by morruth** [comment]
adjusting profile means i'll need second instance if i want switch per request between distance/duration.

It's exactly what i want to avoid.

**Comment by danpat** [comment]
It's not possible to do what you want without two datasets.  The `osrm-contract` (or `osrm-customize`) tools construct a speedup graph that's specifically structured around "shortest distance" or "shortest time" - it can't support both at the same time.

**Comment by jcoupey** [comment]
> In case of table service it's possible by using 'annotations' request parameter

Not exactly, OSRM will pick the "best" route based on whatever optimization objective is given in the profile, and `annotation` just provides another metric for the same route.

Say you optimize on `duration`: retrieving distances using `annotations` does not mean you optimize on distance; it means you get the associated distance for routes optimized on durations.

**Comment by morruth** [comment]
so only way is  a make new instance
thanks
