### ISSUE TITLE
returned Distance matrix is all [[0,0,0,0,0],[0,0,0,0,0]]

### ISSUE THREAD

**Issue by rkydhg** [Project-OSRM/osrm-backend#5768]
I have created OSRM table api call through java. attaching my API call code.
I have given 5 different location and trying to get distance matrix but all I get is [[0,0,0,0,0],[0,0,0,0,0]] matrix.
Please look at the code and inform me what could be wrong.

public class Table {

	public Table() {
	}

	/**
	 * Finds the fastest route between coordinates in the supplied order.
	 * 
	 * @param coordinates The string containing comma separated lon/lat. Multiple
	 *                    coordinate pairs are separated by a semicolon.
	 * @return A JSON object containing the response code, a 2d array of durations,
	 *         and arrays of waypoint objects representing sources, and an
	 *         destinations.
	 */
	public JSONObject generateTravelTimeMatrix(String coordinates) {
//		String url = String.format("http://router.project-osrm.org/table/v1/car/%s", coordinates);
		String url = "http://router.project-osrm.org/table/v1/driving/18.6151,73.765693;18.5809,73.6879;18.5793,73.9089;18.5951,73.7887;18.7053,73.7916?annotations=distance";
		HttpClient httpClient = HttpClients.createDefault();
		JSONObject result = null;
		try {
			URIBuilder builder = new URIBuilder(url);
			URI uri = builder.build();
			HttpGet request = new HttpGet(uri);
			request.addHeader("accept", "application/json");
			HttpResponse response = httpClient.execute(request);
			System.out.println("Response status " + response.getStatusLine().getStatusCode());
			result = new JSONObject(IOUtils.toString(response.getEntity().getContent()));
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		return result;
	}

}
 

also sharing response generated...

15:28:30.416 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
15:28:30.437 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
15:28:30.438 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://router.project-osrm.org:80][total available: 0; route allocated: 0 of 2; total allocated: 0 of 20]
15:28:30.459 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://router.project-osrm.org:80][total available: 0; route allocated: 1 of 2; total allocated: 1 of 20]
15:28:30.460 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {}->http://router.project-osrm.org:80
15:28:30.474 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to router.project-osrm.org/88.99.61.41:80
15:28:51.517 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connect to router.project-osrm.org/88.99.61.41:80 timed out. Connection will be retried using another IP address
15:28:51.518 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to router.project-osrm.org/2a01:4f8:10a:d68:0:0:0:2:80
15:28:51.885 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connection established 2402:3a80:8fe:7718:7938:d017:c21a:894d:51962<->2a01:4f8:10a:d68:0:0:0:2:80
15:28:51.885 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request GET /table/v1/driving/18.6151,73.765693;18.5809,73.6879;18.5793,73.9089;18.5951,73.7887;18.7053,73.7916?annotations=distance HTTP/1.1
15:28:51.886 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
15:28:51.887 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
15:28:51.889 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> GET /table/v1/driving/18.6151,73.765693;18.5809,73.6879;18.5793,73.9089;18.5951,73.7887;18.7053,73.7916?annotations=distance HTTP/1.1
15:28:51.889 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> accept: application/json
15:28:51.889 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: router.project-osrm.org
15:28:51.889 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
15:28:51.890 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.12 (Java/10.0.1)
15:28:51.891 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
15:28:51.891 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "GET /table/v1/driving/18.6151,73.765693;18.5809,73.6879;18.5793,73.9089;18.5951,73.7887;18.7053,73.7916?annotations=distance HTTP/1.1[\r][\n]"
15:28:51.891 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "accept: application/json[\r][\n]"
15:28:51.891 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: router.project-osrm.org[\r][\n]"
15:28:51.891 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
15:28:51.891 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.12 (Java/10.0.1)[\r][\n]"
15:28:51.891 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
15:28:51.891 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
15:28:52.436 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
15:28:52.436 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Thu, 25 Jun 2020 09:58:51 GMT[\r][\n]"
15:28:52.436 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: Apache/2.4.38 (Debian)[\r][\n]"
15:28:52.436 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 1786[\r][\n]"
15:28:52.436 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: close[\r][\n]"
15:28:52.436 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Origin: *[\r][\n]"
15:28:52.437 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Methods: GET[\r][\n]"
15:28:52.437 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Headers: X-Requested-With, Content-Type[\r][\n]"
15:28:52.437 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Disposition: inline; filename="response.json"[\r][\n]"
15:28:52.437 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/json; charset=UTF-8[\r][\n]"
15:28:52.437 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
15:28:52.438 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "{"code":"Ok","distances":[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]],"sources":[{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPAQ8CxwBPZNlBAQArxNkyXCd","location":[24.013495,71.081358],"name":""},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPASkhRsBXGNkBAQArxNkyXCd","location":[24.013495,71.081358],"name":""},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPARkfxsBpMJnBAQArxNkyXCd","location":[24.013495,71.081358],"name":""},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPAQcvRsBHO1lBAQArxNkyXCd","location":[24.013495,71.081358],"name":""},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPASUax0BcPhlBAQArxNkyXCd","location":[24.013495,71.081358],"name":""}],"destinations":[{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPAQ8CxwBPZNlBAQArxNkyXCd","location":[24.013495,71.081358],"name":""},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPASkhRsBXGNkBAQArxNkyXCd","location":[24.013495,71.081358],"name":""},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPARkfxsBpMJnBAQArxNkyXCd","location":[24.013495,71.081358],"name":""},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPAQcvRsBHO1lBAQArxNkyXCd","location":[24.013495,71.081358],"name":""},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPASUax0BcPhlBAQArxNkyXCd","location":[24.013495,71.081358],"name":""}]}"
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Thu, 25 Jun 2020 09:58:51 GMT
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: Apache/2.4.38 (Debian)
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 1786
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: close
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Origin: *
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Methods: GET
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Headers: X-Requested-With, Content-Type
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Disposition: inline; filename="response.json"
15:28:52.443 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/json; charset=UTF-8
Response status 200
15:28:52.462 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
15:28:52.463 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
15:28:52.463 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://router.project-osrm.org:80][total available: 0; route allocated: 0 of 2; total allocated: 0 of 20]
{"distances":[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]],"code":"Ok","sources":[{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPAQ8CxwBPZNlBAQArxNkyXCd","name":"","location":[24.013495,71.081358]},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPASkhRsBXGNkBAQArxNkyXCd","name":"","location":[24.013495,71.081358]},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPARkfxsBpMJnBAQArxNkyXCd","name":"","location":[24.013495,71.081358]},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPAQcvRsBHO1lBAQArxNkyXCd","name":"","location":[24.013495,71.081358]},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPASUax0BcPhlBAQArxNkyXCd","name":"","location":[24.013495,71.081358]}],"destinations":[{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPAQ8CxwBPZNlBAQArxNkyXCd","name":"","location":[24.013495,71.081358]},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPASkhRsBXGNkBAQArxNkyXCd","name":"","location":[24.013495,71.081358]},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPARkfxsBpMJnBAQArxNkyXCd","name":"","location":[24.013495,71.081358]},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPAQcvRsBHO1lBAQArxNkyXCd","name":"","location":[24.013495,71.081358]},{"hint":"8wW2jfQFto0WAAAAAAAAAEIAAAAAAAAAtbJzQQAAAADanDVCAAAAABYAAAAAAAAAQgAAAAAAAAAZHAEAt2puAY6dPASUax0BcPhlBAQArxNkyXCd","name":"","location":[24.013495,71.081358]}]}

It would be great help if you can helm me out. 

Thank you,
Ridhdhi

**Comment by jcoupey** [comment]
You have the order of your coordinates mixed-up, OSRM uses lon,lat. Check the difference between http://router.project-osrm.org/table/v1/driving/18.6151,73.765693;18.5809,73.6879?annotations=distance and http://router.project-osrm.org/table/v1/driving/73.765693,18.6151;73.6879,18.5809?annotations=distance.

**Comment by rkydhg** [comment]
Thank you so much for quick response. It has resolved my issue. 
I am closing this issuue.

Thanks & Regards,
Ridhdhi

**Comment by danpat** [comment]
Just to add a bit of detail to this:  when you flip your coordinates, and you only have a small map, the result is often that every location ends up snapping to the same point (whatever part of the small map is closest to your incorrect coordinates).  This is why the distances/durations are all 0.
