### ISSUE TITLE
Table service does not use traffic updates

### ISSUE THREAD

**Issue by njroussel** [Project-OSRM/osrm-backend#5769]
Algorithm: **MLD**

When using the `table` service to get route durations, it seems that traffic updates (applied with `osrm-customize`) are not being used/applied.

Reasoning:
1. I observed that for the same sources and destinations, the outputted durations of the `route` service differ with those of the `table` service.
2. The durations of the `route` result are coherent with the traffic updates (can be checked with the annoations). 
3. When running the same `table` request on a fresh OSRM build (no traffic updates), the output is unchanged.

Is this inconsistency between `route` and `table` intended behaviour ?Am I simply misunderstanding their individual use-cases?

**Comment by danpat** [comment]
`osrm-customize` just prepares the datafiles - you need to refresh `osrm-routed` by either:

  1. Restarting it, or
  2. Using `osrm-datastore` and `osrm-routed -s` in combination.

Simply running `osrm-customize` isn't sufficient to suddenly get updated results from a running `osrm-routed` process.

**Comment by njroussel** [comment]
I am using shared memory and updating it with `osrm-datastore`.

Maybe I wasn't clear enough, currently I'm observing something like this for a given source & destination:
(values are durations)
| Service | Before traffic update | After traffic update |
|---|---|---|
| Route | 120 | 180 |
| Table | 120 | 120 | 

Where the 180 duration is completely expected and correct for the update I made.

**Comment by knasti** [comment]
I experienced the same issue see #5723
