### ISSUE TITLE
How to do online map matching based on osrm.

### ISSUE THREAD

**Issue by ZhiWeiCui** [Project-OSRM/osrm-backend#5770]
I also know that osrm's route navigation has very good performance, and the results of the current batch of offline map matching are in line with my expectations.

My requirement is that GPS data for online map matching is based on kafka or spark stream. Currently I use [barefoot](https://github.com/bmwcarit/barefoot), but it is not fast enough. It is based on [1] and [2].

I want to know how to do online map matching based on osrm.

[1] P. Newson and J. Krumm. Hidden Markov Map Matching Through Noise and Sparseness. In Proceedings of International Conference on Advances in Geographic Information Systems, 2009.

[2] C.Y. Goh, J. Dauwels, N. Mitrovic, M.T. Asif, A. Oran, and P. Jaillet. Online map-matching based on Hidden Markov model for real-time traffic sensing applications. In International IEEE Conference on Intelligent Transportation Systems, 2012.

**Comment by wangyoucao577** [comment]
Try the [OSRM match service](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#match-service)?

**Comment by ChiWai-Choi** [comment]
osrm match server is a batch of offline map matching, and i'm already using this service.
My requirement is that GPS data for **online map matching** is based on kafka or spark stream.

**Comment by danpat** [comment]
OSRM has no capacity for storing any sense of "state", and thus has no online algorithms implemented.

However, you could approximate such a system by transmitting enough past data with each request.  It would require you to build some system that stores, say, the last 5 minutes of GPS traces, then submit the full 5 minutes with each matching request.

This won't be quite as fast as a system that already had the HMM model built, but I think you'd get reasonable results - with sufficient past data, the model should do quite well at deciding the location of the final coordinate in a trace (the most recent one).

**Comment by ChiWai-Choi** [comment]
Yes, this is also the simplest and fastest method I can think of based on osrm.

**Comment by thucdx** [comment]
Hi @ZhiWeiCui, one year has passed. Which solution did you come up with? Could you share any insights you got during your search ?

I'm facing the same problem. We could get a good result for real time map matching using (modified) Barefoot, but it's not fast enough. With OSRM, the only way I could think of is batching some last data points and match them with OSRM. Of course, there are some tradeoffs between accuracy and speedness when doing this way.

**Comment by SiarheiFedartsou** [comment]
Stale.
