### ISSUE TITLE
Question: Which dockerhub image version is the latest one? 

### ISSUE THREAD

**Issue by berfinyavuzaslann** [Project-OSRM/osrm-backend#5772]
When I look at at the Docker Hub, I see v5.22.0 tag before the latest. But on Github, latest seems as v.5.18.0. Which one is the latest version of the image?

**Comment by juliorenner** [comment]
Right now, the latest version on github is v5.26.0, while in docker hub an image with that version doesn't exist. It seems that it is suppose to be the image with the `latest` tag, however, if that's the case, the image should have both tags (v5.26.0 + latest)

**Comment by hoerup** [comment]
And new images will be published to ghcr.io instead of Docker Hub. See #6138
