### ISSUE TITLE
Copy OSRM data from one server to another

### ISSUE THREAD

**Issue by snoopy72** [Project-OSRM/osrm-backend#5777]
Hello,

i cannot find infos (or solutions) for copying OSRM data from one server to another.

my problem:

- i have two linux servers (both debian 10 servers, so pure bash without gui)
- one in my basement with 64 gb ram to calculate the whole data
- the 2nd one online for provideing locations and routes to my app
- the online server has "enough" am (24 gb) but way too less power to calculate (extract/contract) the data
- on the 2nd server my live app is running, so i cannot cahnge it "quickly" or for "testing"

my server in the basement has finished and extracted/contracted whole europe now.

how can i move the dataabses (data) to my online server, so that one can server the data ?

Thanks a lot !

**Comment by akashihi** [comment]
You can simply copy processed files with any copying tool, like scp or rsync etc

**Comment by snoopy72** [comment]
Thanks a lot for your quick and helpful response !

That might explain, WHY i cant find docs.
After installing there tools, you dont even think anymore in easy ways ;)
