### ISSUE TITLE
No routing on roads tagged with construction=*

### ISSUE THREAD

**Issue by boothym** [Project-OSRM/osrm-backend#5778]
Hope I've opened this issue in the correct place.

For example: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=53.9977%2C-1.5258%3B53.9982%2C-1.5224#map=18/53.99852/-1.52406&layers=N

Sanders Walk is tagged construction=residential, therefore OSRM does not use it for routing (whereas GraphHopper does).

Normally this tag is in place because although the highway tagged is changed from construction to residential, mappers often forget to remove the construction=* tag.

**Comment by akashihi** [comment]
I believe it is safer to exclude wrongly mapped road, then to route somebody to actually closed road

**Comment by boothym** [comment]
But the fact it is tagged as highway=residential means it's not closed? Construction=* is a sub tag basically to describe the type of road that is being built.

**Comment by akashihi** [comment]
I checked the wiki and found it is a edge case: construction=* shouldn't be used without highway=construction. So it's an open question, whether we should treat other highway value as an error or construction tag presence as an error.

**Comment by boothym** [comment]
Well, I think it is much more likely that someone has forgotten to delete construction=* when switching the highway value from construction to residential - rather than tagging construction=* to mean the road is closed.

The important tag is surely highway=*?

**Comment by Dimitar5555** [comment]
> The important tag is surely highway=*?

That's almost always the case. You can check https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=42.9070%2C22.9467%3B43.0122%2C22.7753#map=12/42.9613/22.8639 for an example and compare it with GraphHopper. The road is being upgraded to a motorway so the traffic is constantly redirected to the other side of the road (it changes from week to week). Mappers who go there update it, but they always forget to remove the `construction` tags.
