### ISSUE TITLE
Performance with extremely asymmetrical tables

### ISSUE THREAD

**Issue by scd31** [Project-OSRM/osrm-backend#5786]
Is there anything I can do to improve performance with extremely asymmetrical tables? I'm computing the durations between 1 point and ~50 thousand other points using the CH algorithm.

Another thing(should I open a new ticket?) - It would be awesome if there was a way to put a limit on the durations. In my previous example, I might only be interested in points that are only 20 minutes away or less. It seems like taking advantage of that would provide some performance benefits.

**Comment by danpat** [comment]
A 1:50000 table is likely bottlenecked by the initial coordinate snapping.  I would expect a 225x225 (which also has about 50k results) to be significantly faster.  Try to make sure the `.fileIndex` file (this is the main spatial index file) is fully in the page cache, either by doing something like `dd if=map.osrm.fileIndex of=/dev/null`, or mounting that file on a `tmpfs` volume so it's already in RAM.

If you have multiple CPUs, then a simple way to speed things up would be to split the request into multiple parts and run them concurrently.

As far as limiting - you could do a simple upper bounds check - find the straight line distance from your start point to every other point, then assume, say, max 150km/h for 20 minutes = 50km radius limit.  Don't submit points beyond 50km in your request.

**Comment by scd31** [comment]
Is it possible to tell OSRM to load that file into RAM? I'm personally not a fan of forcing things into the cache because it means it could get unloaded in the future. I'll experiment with a tmpfs volume.

> As far as limiting - you could do a simple upper bounds check - find the straight line distance from your start point to every other point, then assume, say, max 150km/h for 20 minutes = 50km radius limit. Don't submit points beyond 50km in your request.

This is what I'm doing now(without it, I would be calculating millions of points) but there is still room for improvement in things like cities, where 20 minutes equals a much smaller distance.

**Comment by danpat** [comment]
The CH structure is such that it's probably not worth having a termination critera inside the search - it only takes a few 10s of edges to traverse large distances (100s of km usually), so the speedup gained by stopping early will be pretty minimal overall.

Your case will be dominated not by the graph search/routing part, but by the initial nearest neighbour search that happens at the start, where we have to decide which edge a coordinate corresponds to to start the graph search.

OSRM uses an R-Tree for the nearest neighbour search.  There are possibly a few speedups that can be made here, like:

  https://github.com/Project-OSRM/osrm-backend/issues/3378
  https://github.com/Project-OSRM/osrm-backend/issues/3136

Or maybe someone could implement a faster spatial indexing method....

**Comment by scd31** [comment]
That makes sense, thanks!

**Comment by scd31** [comment]
Alright, I tried loading the file into RAM but I didn't see any performance improvement. I looked at CPU usage by process and it's obvious that it is CPU bottlenecked.
