### ISSUE TITLE
Routes go through gates (hospitals and ...)

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5787]
Hello
I'm facing an issue when getting routes near hospitals, universities and these kind of places that have gate. It seems that OSRM doesn't check the gate and gives a route that goes through the hospital. For example see this link:

http://map.project-osrm.org/?z=18&center=48.883161%2C2.352571&loc=48.883563%2C2.349797&loc=48.882557%2C2.351155&hl=en&alt=0&srv=0

It's not a good route because it guides people to go through hospital which is a private place. How can I solve this issue?

**Comment by fofanov** [comment]
The gate and the service roads inside the hospital are lacking [access tags](https://wiki.openstreetmap.org/wiki/Key:access#Road_with_restricted_access) that would restrict routing.

The default car profile will detect [common access](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L77) tags that restrict access and remove them those path from the routing graph.
