### ISSUE TITLE
Status code 400 for large distance matrix.

### ISSUE THREAD

**Issue by courtneyes** [Project-OSRM/osrm-backend#5790]
I am attempting to create a 10,000x10,000 distance/ duration matrix. The script I have works fine for 5,000, and 7,500 but breaks for 10,000 and 15,000. If I query my Docker image of OSRM it immediately returns a 400 status code 👿 . I have the `--max-table-size` set to 20,000 this shouldn't be an issue. I have incorporated Google Polyline into the request. I have a few questions:

Are matrices of this magnitude possible to generate, assuming resources aren't an issue? (FYI, I am running a t3.2xlarge 💪  EC2 instance).

If this is not a practical way of creating a large distance matrix, what is? Are there alternatives?

**Comment by jcoupey** [comment]
You should be able to get 10,000x10,000 matrices out of OSRM (I already did), provided everything is fine in term of resources. On the other hand, getting a `400` status code seem to indicate that something is wrong with the setup (Docker-related resources limitations? URL size?).

In any case, you should check out https://github.com/Project-OSRM/osrm-backend/issues/5181 for hints.

**Comment by danpat** [comment]
@jcoupey is correct - there is no intrinsic limit in `osrm-routed`.  Things to look for:

  1. Do you have a load balancer in front of your `osrm-routed` instance?  It may have URL length limits.
  2. Check that your client library code can support very long URLs.  I know that `curl` and `bash` have sufficiently large parameter limits to allow at least 10k x 10k.

When you say "I have incorporated Google Polyline into the request" what do you mean?

**Comment by courtneyes** [comment]
We will attack this by reducing the size of the matrix as it just makes more sense from a performance perspective. I will close this issue. Thanks for the quick and insightful responses.

**Comment by danpat** [comment]
For large symmetric matrices, single matrix calls are most efficient.  The coordinate lookup tends to dominate smaller request sizes.  If absolute performance matters to you, I would try to get to the bottom of the problem here - what you're trying to do is definitely possible.
