### ISSUE TITLE
Maxwidth incorrectly blocking cars from a route

### ISSUE THREAD

**Issue by tomchance** [Project-OSRM/osrm-backend#5793]
In this example, there is a way with maxwidth tag with a value of 6'0" on a stretch of road. OSRM sends cars in a diversion route to avoid it. But the stretch in question is designed for cars and to exclude larger vehicles, and that's very much how its used. Very few cars (in the UK at least) are wider than 6 feet (1.83m).

http://map.project-osrm.org/?z=18&center=51.414229%2C-0.075864&loc=51.414585%2C-0.075102&loc=51.413862%2C-0.076625&hl=en&alt=0&srv=0

The [car profile](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua) in line 43 defines the vehicle width as 1.9m and the comment says 'ways with narrow tag are considered narrower than 2.2m'. I'm not sure which figure is used in the routing engine (or rather how the 1.9 is processed) but it ought to permit cars to pass along a way or through a node with a maxwidth of 6 feet / 1.83m.

Not that we should slavishly follow them, but other common engines behind Google Maps etc all correctly show a car route passing along this way.

**Comment by fofanov** [comment]
The 2.2m max width is only used if narrow appears in the way tags (either `narrow=yes` or as value for a width key), which is not the case here.

As the way explicitly tags `maxwidth=6'0"`, the way handler will compare this value (~1.83m) with the 1.9m vehicle width in the profile and mark the way as inaccessible (see [WayHandlers.handle_width](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua#L487)).

You need to use a car profile with a `vehicle_width` reduced to < 1.83m for this way to be routable.

**Comment by tomchance** [comment]
Thanks for the information.

I was suggesting that perhaps the profile should be changed to treat a car as being perhaps 1.8m wide, rather than 1.9m.

In the UK at least most cars are narrower than 1.8m and it's not uncommon for roads to be narrowed to that width to allow cars through but to make it inaccessible to larger vehicles. As I say, other non-free map provides permit car routing through stretches of road with that width restriction.

**Comment by fofanov** [comment]
Ah I see. One of the core devs can probably comment on the default width choice. I suspect it's so the default routing is slightly conservative (better to avoid a road too narrow than to route through it).
