### ISSUE TITLE
Limit for total path cost

### ISSUE THREAD

**Issue by dburnsii** [Project-OSRM/osrm-backend#5796]
For my use case, I have to calculate a large matrix and perform processing based on the results of that matrix. Part of that processing involves looking at each value in the matrix and throwing away any values greater than a certain threshold I have set. My question is, since OSRM uses a variation of Dijkstra's, is there a way to sort of "give up" beyond a certain distance, to save myself the processing bandwidth? This functionality could benefit both in A->B routing and Matrix routing, since if there is no path available with the given constraint, there's no point in continuing to process.

I'm willing to contribute to this effort, but the codebase for this project is huge. If someone could point me in the right direction I'd be more than willing to write it myself and give it back to the community.

**Comment by danpat** [comment]
If you're using the CH algorithm, I don't think there's much to be gained by this.  A CH search will touch only maybe 100 edges finding paths that are quite far (10s to 100s of km) - terminating early is probably not worth it, the search is so fast.

In addition for the table plugin, it's using a specialized many-to-many variant of dijkstra - it's not so simple to just stop individual searches, as results are being shared between pairs.

**Comment by dburnsii** [comment]
Understandable. While I do think there could be value in OSRM being able to limit the extent of a search for performance reasons, there are other ways to achieve this without adding complexity to the OSRM codebase. My use case in particular is for a one-to-many table search, but at a minimum I can pre-process my points and throw away any that are outside of my range "limit" as the crow flies.

**Comment by danpat** [comment]
In the one-to-many case, the initial nearest-neighbour search (finding where on the graph to start) typically dominates Matrix calls.  OSRM uses an R-Tree to figure out where coordinates snap to - this is usually the slowest part.
