### ISSUE TITLE
Compile Issues on Ubuntu 20.04

### ISSUE THREAD

**Issue by woodpeck** [Project-OSRM/osrm-backend#5797]
Trying to compile v5.22 on Ubuntu 20.04 (gcc 9.3.0) I ran into two problems:

    error: redundant move in return statement [-Werror=redundant-move]

fixed by adding these compiler flags to cmake:

    cmake .. -DCMAKE_CXX_FLAGS="-Wno-pessimizing-move -Wno-redundant-move"

and

    error: call of overloaded ‘is_regular_file(<brace-enclosed initializer list>)’ is ambiguous

fixed by applying this patch I found over at ArchLinux:

https://aur.archlinux.org/cgit/aur.git/tree/fix-boost-fs.patch?h=osrm-backend

Just in case someone else stumbles across the same!

**Comment by akashihi** [comment]
IIRC it is fixed in master with https://github.com/Project-OSRM/osrm-backend/commit/018a9bc80449d85c0e40fa5215377d8a03264c88
