### ISSUE TITLE
TBB Warning when I launch osrm-extract

### ISSUE THREAD

**Issue by setooc** [Project-OSRM/osrm-backend#5798]
Hi!

I following the step in the github page, but when i launch the container to extract, this messages appears and the process was stoped

[root@slnxdock01 openmap-ruteo]# docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/south-america-latest.osm.pbf
Unable to find image 'osrm/osrm-backend:latest' locally
Trying to pull repository docker.io/osrm/osrm-backend ...
latest: Pulling from docker.io/osrm/osrm-backend
75cb2ebf3b3c: Pull complete
bbcf7ce6c321: Pull complete
400d688597e9: Pull complete
6fa89d0178dc: Pull complete
91e5fa7ea36b: Pull complete
Digest: sha256:a5cc4b9c4b3c58ef40a1d31f9a4cf0b62651ef2493f388775181bd97c5a1fc5f
Status: Downloaded newer image for docker.io/osrm/osrm-backend:latest
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: south-america-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 2
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2020-08-10T20:59:03Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4

TBB Warning: Exact exception propagation is requested by application but the linked library is built without support for it
terminate called after throwing an instance of 'tbb::captured_exception'
  what():  std::bad_alloc

any ideas??

Regards,
IB

**Comment by akashihi** [comment]
>what(): std::bad_alloc

You definitely need more RAM

**Comment by setooc** [comment]
oh ok! Thanks

**Comment by dnorton29** [comment]
@akashihi How much RAM would be needed though? I have a similar issue when trying to extract Asia-latest.osm.pbf, but my container is currently allocated 22.5GiB of RAM.

**Comment by danpat** [comment]
@dnorton29 The best way is to run the process on a very large box - `osrm-extract` logs the max memory used at the end.

For `asia-latest.osm.pbf` I'm *guessing* you need at least 50GB.  What I would do would be to rent a large box with 128GB for a few hours, and run the extraction process, and see what it prints out when it finishes.

**Comment by dnorton29** [comment]
@danpat I see. Seeing as this isn't time sensitive, I'll go the free route and use a swap file. That's what I ended up using for my latest run and it used just under 29GB of RAM (and more than a day of processing). Thanks for the advice though. If I end up needing to process the whole world or a much larger file, then renting a server would definitely be quicker.

**Comment by SiarheiFedartsou** [comment]
Closing as non-actionable(feel free to re-open though)
