### ISSUE TITLE
Ways data from OSM

### ISSUE THREAD

**Issue by jerrybach** [Project-OSRM/osrm-backend#5799]
Hi Team,

I've created the new ways on OSM with access tags = no, then download that data for OSRM. It seems doesn't work.
But if I edit the existing ways, osrm works perfectly.

Can anyone help me to advise what's wrong with my data ?

Thank you very much.

**Comment by akashihi** [comment]
May be you can describe your actions more detailed? Especially i'm interested in "download that data for OSRM" part, what you actually did here?

**Comment by jerrybach** [comment]
Hi @akashihi ,

Case 1:
1) Create new way on the top of OpenStreetMap data (and set the : access = no, highway = service)
![image](https://user-images.githubusercontent.com/48954316/90102254-617bda00-dd6a-11ea-9ff5-e7d2a08936d4.png)
2) Export the osm data ( for that area)
3) Extract osm data using osrm-extract and following by osrm-contract
4) Test the routing service => fail, system still route via the service street (the one I set to no)

Case 2: 
1) Select the existed way from OSM and set the access = no
![image](https://user-images.githubusercontent.com/48954316/90102498-f088f200-dd6a-11ea-9a89-817553e6e847.png)
Do the same step 2-3-4 above => system work perfectly.

In the real world case 1 should work with the same result as case 2 as in many cases the road is repared which we must update to service status.

Thanks

**Comment by akashihi** [comment]
Should be working as you mentioned indeed. Could you please share a link to that way from case one? 

and how did you made a data export? Public sources are usually lagging, so it may not appear in planet file/extracts immediately

**Comment by jerrybach** [comment]
Hi,
Thank you very much.
My custom way id is is 836671208 (https://www.openstreetmap.org/way/836671208)
The existing way id is 710203072 (https://www.openstreetmap.org/way/710203072)

My expectation is when set way 836671208 to access = 0, the routing from [21.02445,105.81356] to [21.02140,105.81568]  should not be route via way 836671208, but it did.

When I set the way id 710203072 with access tag = 0, it works perfectly.

Please help to advise.

**Comment by akashihi** [comment]
You way was updated like 7 hours ago, i'm quite sure it is not in any of the publiclly available extracts yet. I would wait or 1-2 weeks and try one more time.

**Comment by jerrybach** [comment]
Hi Akashihi,

Thank you.
I forgot to tell that I'm using osrm-backend on my docker container, after export data on openstreetmap into osm file using export function.
![image](https://user-images.githubusercontent.com/48954316/90149295-898d2c80-ddae-11ea-89e2-c3bd5bc35f91.png)
I open osm file and found that the way id has been exported successfully, it means data is available in exported files.

Thanks.

**Comment by danpat** [comment]
You can't just draw a new way over the top of the old one - the routing engine will find *any* path it can.  The old way (710203072) is still being used, even when the new way is connected to the same endpoints.  If you want to close 710203072, you should change it's tags to indicate it's closed.

If only part of 710203072 is closed, you should split it into two ways.

OSRM doesn't care about the spatial placement of the ways/nodes - it cares about how things are connected.  When you add your new way (836671208), OSRM will still happily use the old way (710203072).

**Comment by jerrybach** [comment]
Thank you. I got it.
Then, how to split it into 2 ways. Do I need to close the old one and create 2 new ways?

**Comment by danpat** [comment]
There's a wiki on way splitting here: https://wiki.openstreetmap.org/wiki/JOSM/Advanced_editing#Splitting_and_combining_ways

Both JOSM and iD have functions to split/merge ways.  At least in iD, you click on the *node* where you want to split, and there's a control menu to do it.  You would then set the `access=no` property on the split portion that is actually closed.

**Comment by jerrybach** [comment]
I see, this is very good. Thank you very much for your supports.
