### ISSUE TITLE
trip in version 4.9.1 returns route that is not usable by just changing order of lat lon being sent

### ISSUE THREAD

**Issue by huntw999** [Project-OSRM/osrm-backend#5803]
the 2 request get totally different route when order is changed - on route is not usable

the first one gives a great result the second is not usable:

https://dddashboard.net/trip?&loc=40.09157,-75.285995&loc=40.06159,-75.4158&loc=40.03165,-75.46512&loc=40.15835,-75.33122&loc=40.07223,-75.15494&loc=40.148502,-75.234314&loc=40.191055,-75.374466&loc=40.141396,-75.32572&loc=40.014015,-75.17221
https://dddashboard.net/trip?&loc=40.03165,-75.46512&loc=40.06159,-75.4158&loc=40.191055,-75.374466&loc=40.15835,-75.33122&loc=40.09157,-75.285995&loc=40.148502,-75.234314&loc=40.07223,-75.15494&loc=40.141396,-75.32572&loc=40.014015,-75.17221

i did find documentation for server api 

https://github.com/Project-OSRM/osrm-backend/wiki/Server-api/d3df08ef7fc4dbe4d1960bc6df92f441e1343b82#server-api-4x

It is hard to know if i am using the right parameters for the trip because of documentation - i will dig into code to get the answer - i am looking to solve this problem of an unusable route by finding a way to use this version of osrm with a better understanding from code - but - the final approach is to move to the latest version if i can't fix it with 4.9.1 with a reasonable effort - no matter what - this post is looking to solve the trip request showing crazy route

**Comment by jcoupey** [comment]
There is no guarantee that the `trip` plugin will return an optimal solution and yes, the underlying solving approach make it input-sensitive.
