### ISSUE TITLE
How to verify if extraction was successful? My terminal data is shown below.

### ISSUE THREAD

**Issue by SoulExtinction** [Project-OSRM/osrm-backend#5804]
nominatim@osrm-VirtualBox:~/OSRM$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/europe-north-america.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: europe-north-america.osm.pbf
[info] Profile: car.lua
[info] Threads: 1
[info] Parsing in progress..
[info] input file generated by osmium/1.7.1
[info] timestamp: n/a
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Parsing finished after 8897.32 seconds
[info] Raw input contains 3828897668 nodes, 414024597 ways, and 580979 relations, 947092 restrictions
[info] Sorting used nodes    	... ok, after 37.5893s
[info] Erasing duplicate nodes   ... ok, after 1.04025s
[info] Sorting all nodes     	... ok, after 558.071s
[info] Building node id map  	... ok, after 421.121s
[info] Confirming/Writing used nodes 	... ok, after 511.151s
[info] Writing barrier nodes 	... ok, after 0s
[info] Writing traffic light nodes 	... ok, after 0s
[info] Processed 544163466 nodes
[info] Sorting edges by start	... ok, after 410.447s
[info] Setting start coords  	... ok, after 841.206s
[info] Sorting edges by target   ... ok, after 578.699s
[info] Computing edge weights	... ok, after 831.95s
[info] Sorting edges by renumbered start ... ok, after 405.555s
[info] Writing used edges   	... ok, after 81.3321s -- Processed 571297154 edges
[info] Writing way meta-data 	... ok, after 5.09684s -- Metadata contains << 68551200 entries.
[info] Sorting used ways     	... ok, after 11.9455s
[info] Collecting start/end information on 29 maneuver overrides...ok, after 1.41371s
[info] Collecting start/end information on 29 maneuver overrides...ok, after 0.099228s
[info] Collecting start/end information on 947092 restrictions...ok, after 10.7298s
[info] Collecting start/end information on 947092 restrictions...ok, after 126.825s
[info] writing street name index ... ok, after 4.54716s
[info] extraction finished after 13785.8s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.193552
[info] Edge compression ratio: 0.230413
[info]  graph compression removed 61698526 annotations of 68551200 in 1814.36 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 15550.3s
[info] Segregated edges count = 1692642
[info] Writing nodes for nodes-based and edges-based graphs ...
[warn] Clipped 12 segment weights to 4194302
[info] Geometry successfully removed:
  compressed edges: 262776000
  compressed geometries: 1141139368
  longest chain length: 6987
  cmpr ratio: 0.230275
  avg chain length: 4.34263
[info] Generating edge expanded nodes ...
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ...
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 249758209 nodes (33858 of which are duplicates)  and 570227324 segments in edge-expanded graph
[info] Generating edge-expanded edges
[info] [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 3353413, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=36.386404&mlon=25.42941
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 10755123, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=49.972611&mlon=14.610308
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 10805809, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.808567&mlon=-116.964088
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 18601627, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.235804&mlon=-73.282519
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 19024312, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.460153&mlon=-83.154748
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 47810134, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.214208&mlon=-77.111079
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 48033603, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=53.483494&mlon=12.959619
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 48816147, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.533973&mlon=-81.013553
 10% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 54560200, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.17513&mlon=-95.425205
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 66456091, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.726113&mlon=-104.388261
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 68073669, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=34.925952&mlon=-98.098521
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 70572777, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=35.203096&mlon=-97.007773
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 70572777, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=35.203096&mlon=-97.007773
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 71451088, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=30.702555&mlon=-98.15127
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 74676874, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.613165&mlon=-80.593898
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 78282564, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=37.973642&mlon=-85.039928
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 81801427, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=36.851942&mlon=-86.912602
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 84774157, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=35.669448&mlon=-79.219801
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 89484141, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.259168&mlon=-103.323219
 20% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 113770565, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.90808&mlon=-76.529193
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 114998707, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.17285&mlon=-75.175466
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 134119582, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.312259&mlon=5.364165
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 140702617, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.837352&mlon=14.25475
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 146466611, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=57.661522&mlon=11.842368
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 149014140, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.281383&mlon=1.182903
 30% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 164304802, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.936638&mlon=12.660905
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 166874600, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.579586&mlon=39.711165
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 170553548, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=38.372215&mlon=26.137742
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 175025411, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=36.723513&mlon=25.272277
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 184521994, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.892064&mlon=8.590415
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 185393341, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=46.149721&mlon=-66.944733
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 209566476, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.537981&mlon=2.576274
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 213547470, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=50.811215&mlon=-1.094963
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 213547470, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=50.811215&mlon=-1.094963
 40% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 218234106, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.730732&mlon=15.894071
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 220991603, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.422593&mlon=-8.027353
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 221943787, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.22056&mlon=-8.678861
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 225965386, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=60.459803&mlon=26.223756
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 232327851, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.376815&mlon=-61.855283
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 233492420, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=46.58388&mlon=14.744743
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 254972203, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=38.12802&mlon=13.363759
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 258284334, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=45.395765&mlon=10.698378
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 258284337, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=45.395932&mlon=10.697223
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 259060057, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=46.001352&mlon=11.222207
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 260101401, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=44.21236&mlon=14.871777
 50% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 288335133, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=45.734762&mlon=4.834244
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 293507193, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=69.929894&mlon=23.273247
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 297839408, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.884403&mlon=-87.621391
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 301332972, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.503392&mlon=-86.035354
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 323669116, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.023437&mlon=1.340469
 60% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 327276473, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=44.762874&mlon=11.933356
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 327276473, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=44.762874&mlon=11.933356
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 327276473, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=44.762874&mlon=11.933356
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 335653463, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=36.948696&mlon=26.987285
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 361209523, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.647254&mlon=41.657242
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 361209523, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.647254&mlon=41.657242
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 361209523, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.647254&mlon=41.657242
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 373159447, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=52.098358&mlon=21.631291
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 374211561, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.787707&mlon=-3.483328
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 379015527, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=50.030213&mlon=21.952169
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 381009450, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.402342&mlon=-76.5681
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 381009450, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.402342&mlon=-76.5681
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 381009450, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.402342&mlon=-76.5681
 70% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 390009478, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=44.876509&mlon=-91.92906
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 395812055, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=49.213693&mlon=-0.368315
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 407629622, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=50.027803&mlon=36.366039
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 412831155, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=48.271072&mlon=19.8197
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 414608900, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=35.853484&mlon=14.531398
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 419060906, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.49786&mlon=20.263004
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 421415064, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.297026&mlon=-90.192487
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 421609870, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.556524&mlon=14.239077
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 421609870, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.556524&mlon=14.239077
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 421609870, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.556524&mlon=14.239077
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 421609870, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.556524&mlon=14.239077
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 421609870, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.556524&mlon=14.239077
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 421609870, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.556524&mlon=14.239077
 80% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 439131799, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=60.202556&mlon=11.410212
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 439739781, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.062794&mlon=-122.918649
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 440458169, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=52.380752&mlon=4.611615
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 447278122, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=50.453866&mlon=20.719331
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 450977480, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=49.236379&mlon=16.627606
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 451514449, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.919453&mlon=-97.029392
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 476016227, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=51.806127&mlon=-0.809903
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 476016227, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=51.806127&mlon=-0.809903
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 476016227, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=51.806127&mlon=-0.809903
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 476016227, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=51.806127&mlon=-0.809903
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 476016227, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=51.806127&mlon=-0.809903
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 476016227, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=51.806127&mlon=-0.809903
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 487003332, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.294701&mlon=23.122355
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 488708513, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.068212&mlon=-83.159958
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 492885075, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=45.885885&mlon=-73.429043
 90% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 523923787, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.647657&mlon=-99.013664
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 525349211, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=38.660294&mlon=-87.167102
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 525896644, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=21.318817&mlon=-158.029205
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 525896644, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=21.318817&mlon=-158.029205
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 525896644, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=21.318817&mlon=-158.029205
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 528579514, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=33.548615&mlon=-96.902825
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 536978658, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=30.762764&mlon=-86.425417
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 537897077, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.177364&mlon=-122.298449

[info] Sorting and writing 29 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 570227324 edge based node segments
[info] Node-based graph contains 249724351 edges
[info] Edge-expanded graph ...
[info]   contains 476350410 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 449.538s
[info] Generating nodes: 13502.1s
[info] Generating edges: 38413.3s
[info] Generating guidance turns
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .
[info] done.
[info] Created 347 entry classes and 153326 Bearing Classes
[info] Handled: 704346 of 1577995 lanes: 44.6355 %.
[info] Assigned 546345222 turn instruction types:
[info]   new name: 17015227 (3.11%)
[info]   continue: 36678179 (6.71%)
[info]   turn: 211942861 (38.79%)
[info]   merge: 241408 (0.04%)
[info]   on ramp: 314892 (0.06%)
[info]   off ramp: 228373 (0.04%)
[info]   fork: 3208419 (0.59%)
[info]   end of road: 92772100 (16.98%)
[info]   notification: 8184 (0.00%)
[info]   enter roundabout: 592207 (0.11%)
[info]   enter and exit roundabout: 25641 (0.00%)
[info]   enter rotary: 61558 (0.01%)
[info]   enter and exit rotary: 2170 (0.00%)
[info]   enter roundabout turn: 212762 (0.04%)
[info]   enter and exit roundabout turn: 79 (0.00%)
[info]   (noturn): 50781830 (9.29%)
[info]   (suppressed): 129718392 (23.74%)
[info]   roundabout: 25163 (0.00%)
[info]   exit roundabout: 740980 (0.14%)
[info]   rotary: 2235 (0.00%)
[info]   exit rotary: 72813 (0.01%)
[info]   roundabout turn: 68 (0.00%)
[info]   exit roundabout turn: 215362 (0.04%)
[info]   (stay on roundabout): 969567 (0.18%)
[info]   (sliproad): 514752 (0.09%)
[info] Assigned 546345222 turn instruction modifiers:
[info]   uturn: 28029046 (5.13%)
[info]   sharp right: 9282810 (1.70%)
[info]   right: 149503777 (27.36%)
[info]   slight right: 14220017 (2.60%)
[info]   straight: 174630326 (31.96%)
[info]   slight left: 13801739 (2.53%)
[info]   left: 146794684 (26.87%)
[info]   sharp left: 10082823 (1.85%)
[info] Guidance turn annotations took 38987.6s
[info] Writing Intersection Classification Data
[info] ok, after 196.438s
[info] Writing Turns and Lane Data...
[info] ok, after 139.643s
[info] Saving edge-based node weights to file.
[info] Done writing. (121.625)
[info] Computing strictly connected components ...
[info] Found 474419 SCC (29 large, 474390 small)
[info] SCC run took: 158.235s
[info] Building r-tree ...
[info] Constructing r-tree of 570227324 segments build on-top of 544163466 coordinates
[info] finished r-tree construction in 308.207 seconds
[info] Writing edge-based-graph edges   	...
[info] ok, after 20.7927s
[info] Processed 476350410 edges
[info] Expansion: 4060 nodes/sec and 1863 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "/data/europe-north-america.osrm"
[info] RAM: peak bytes used: 52588273664

**Just let me know if the process is completed or if any issue occurred. Thanks in advance.**

**Comment by danpat** [comment]
You should check the return code from the `docker run` command - if it's 0, then there was no error.

**Comment by SoulExtinction** [comment]
> You should check the return code from the `docker run` command - if it's 0, then there was no error.

Okay. I'll check on that. But can you tell me if the above step was completed or terminated?

**Comment by danpat** [comment]
No - the last message there *looks* ok, but you need to check the return code to ensure everything completed successfully.

Under a POSIX shell, you can do something like `docker run ... && echo "completed ok" || echo "exited with an error"`
