### ISSUE TITLE
Data not showing on OSRM frontend

### ISSUE THREAD

**Issue by SoulExtinction** [Project-OSRM/osrm-backend#5809]
Hi,

I have set up the OSRM server in a VM and I'm accessing that server outside VM through the bridge. When I put a source and destination for getting the distance and direction, inside VM I'm getting the data. But when I try to get the data outside VM, i.e through the connection established via a bridge, it doesn't display.

Can anyone tell me how to solve this issue?

I have assigned 50GB of RAM and 400 GB of Swap memory to VM.

**Comment by Nerdyvedi** [comment]
@SoulExtinction I am facing the same issue. Were you able to fix this ?

**Comment by danpat** [comment]
Requests to `osrm-routed` (the routing server) are made from the user's browser - you don't need a bridge between the `osrm-frontend` and `osrm-backend` containers, you need to give external access to the `osrm-backend` container to the outside world.

**Comment by SoulExtinction** [comment]
> @SoulExtinction I am facing the same issue. Were you able to fix this ?

No, I'm not able to as of now.

**Comment by SoulExtinction** [comment]
> Requests to `osrm-routed` (the routing server) are made from the user's browser - you don't need a bridge between the `osrm-frontend` and `osrm-backend` containers, you need to give external access to the `osrm-backend` container to the outside world.

The bridge is not between the Frontend and backend, it's between the VM and my system.

**Comment by courageuse** [comment]
Good morning all
I am new to using routing machines like OSRM
i managed to install osrm backend under ubuntu which is installed on a virtual machine now i need a link to show me the installation of the frontend OSRM under ubuntu under the virtual machine 
any one can help me and thanks in advance

**Comment by SoulExtinction** [comment]
Hi @courageuse , follow these steps to install osrm front-end and then access it:
a.	Open new Terminal
b.	su - ${USER}
c.	docker pull osrm/osrm-frontend
d.	docker run -p 9966:9966 -e OSRM_BACKEND='http://localhost:5000' osrm/osrm-frontend
Note - Here the URL in the above line is your OSRM backend URL that you have hosted
e.	To access Frontend: http://localhost:9966

**Comment by courageuse** [comment]
I thank you mr SoulExtinction for answering me
what I noticed is that these lines contain the keyword docker while in my case I have not used the docker but the virtual machine with ubuntu and what I am looking for is the link that allows me to install OSRM frontend under ubuntu under the virtual machine
thank you again

**Comment by SoulExtinction** [comment]
Hi @courageuse, these lines also work in Ubuntu only. I have done the same, installed VM and Ubuntu inside, and then installed OSRM back-end and front-end using docker. So my question to you is how did you install the OSRM backend and how are you accessing it? Did you install it using source code?

**Comment by courageuse** [comment]
Hello,
thank you for answering your question for the installation of the OSRM backend I followed this tutorial expressed in this url : 
http://blog.yatis.io/how-to-install-osrm-and-nominatim-on-ubuntu-16-02-google-maps-alternative/
for access I have not tried yet I wait once installed the frontend and I launch a route calculation request
now I am training to look for a tutorial to install OSRM frontend if you have an idea do not hesitate to pass it to me and thank you in advance

**Comment by courageuse** [comment]
Hello, 
I would like to do the installation without using the docker because I will install another route calculation engine other than OSRM and then make a comparison between the two

**Comment by nilsnolde** [comment]
the best way to run projects without docker is to look at their dockerfile: https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/docker/Dockerfile

osrm's frontend won't talk to other routing engines than osrm without quite a bit of work, in case that's what your plan was.

**Comment by courageuse** [comment]
Hello,
the object of my work is to make a comparison between two routing engines for example osrm and another
for a start i installed osrm backend under ubuntu under virtual machine now what i'm looking for is to have osrm frontend installed and all these installations i have to do without using the docker
thank you in advance.

**Comment by courageuse** [comment]
I accessed the link https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/docker/Dockerfile you sent me but I didn't understand how to use it

**Comment by nilsnolde** [comment]
you also didn't take a long time thinking/researching about it, which I suggest you do.. hints:

create envs:
https://github.com/Project-OSRM/osrm-frontend/blob/814ceeb2e9c46e08a62f13ce9c988843415744b3/docker/Dockerfile#L3-L9

install:
https://github.com/Project-OSRM/osrm-frontend/blob/814ceeb2e9c46e08a62f13ce9c988843415744b3/docker/Dockerfile#L18

start:
https://github.com/Project-OSRM/osrm-frontend/blob/814ceeb2e9c46e08a62f13ce9c988843415744b3/docker/Dockerfile#L26

**Comment by courageuse** [comment]
Hello,
thanks for the help but when I typed the commands from the url: https://github.com/Project-OSRM/osrm-frontend/blob/814ceeb2e9c46e08a62f13ce9c988843415744b3/docker/Dockerfile#L3-L9
in the terminal under ubuntu under the virtual machine I got a message indicating that ENV: command not found
and when I removed ENV and type only: OSRM_BACKEND = 'http: // localhost: 5000'
he showed me the message: no file in the folder of this type
for information in my case i don't use docker, rather i type these command lines in terminal under ubuntu which is installed in virtual machine.

**Comment by courageuse** [comment]
I got to execute the commands relating to envs and install, while for start it showed me CMD: not found and when I removed the CMD and I typed only ["npm", "start"] it showed me as message: [npm, command not found 
what can i do in this case

**Comment by danpat** [comment]
@courageuse Your questions are unrelated to OSRM at this point.  Please spend some time understanding how Docker works so you are able to properly read the `Dockerfile` that was linked here.

You can start here:

https://docs.docker.com/get-started/overview/

Yes, there is a lot to read, but using OSRM (or at least understanding its `Dockerfiles`) assumes you are familiar with that material.

I'm going to close this ticket as not actionable, I do not think our documentation or functionality is lacking here.

**Comment by datendelphin** [comment]
It seems to me @courageuse is not using docker but a VM. What I use are the instructions under the development heading https://github.com/Project-OSRM/osrm-frontend/#development 
You need npm installed and I think I also needed node-browserify-lite
then run npm install && npm run build which will generate the static files. Those files can be served by any web server

**Comment by Shailesh913** [comment]
Hi ,

Need help with respect to UI. I setup the frontend and backend on two dffferent Containers but when accessing the URL I can't see the Map. The UI elements like the start/end markers, zoom controls, and layer switcher are visible, but the actual map area is blank white. This suggests that there might be an issue with loading the map tiles. 

Any help highly appreciated as I'm completely new to OSRM and OSM.

Attached screenshot for any reference
![Screenshot from 2024-09-21 15-02-00](https://github.com/user-attachments/assets/d93a8ab6-ed32-4244-bf08-6c1416ffddc4)

**Comment by mikolyan** [comment]
Good day! If you have solved the problem, please write. I encountered the same problem. I launched the front and backend, and the maps are not displayed. I suspect that the backend only calculates routes, and the front either loads the maps online, or some other map server is needed. There is a menu at the bottom left in the web interface, there is an option to select maps online.
![maps1](https://github.com/user-attachments/assets/a5f00183-2c97-41d8-93bb-cfe34cb8468c)
![maps2](https://github.com/user-attachments/assets/4259246a-c7a5-433a-a1e9-564ce6901bd9)
