### ISSUE TITLE
Resulting Poly line from generated route is not accurate.

### ISSUE THREAD

**Issue by zzimickQ** [Project-OSRM/osrm-backend#5811]
here on the route I just created to test. it is showing me very close and correct results to the overall route. but I seem to not understand why it's jagged away from the map road lines. I'm I configuring it in some wrong way. or is this done intentionally. 
![take from the orsm-frontend](https://user-images.githubusercontent.com/20017216/91851094-4a445400-ec67-11ea-802b-41f3fcf60f24.png)

if it's a bug. please get back with me and let's try to fix it.

thanks.

**Comment by jcoupey** [comment]
The default is to simplify the polyline, see [the overview option](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#route-service). Depending on your zoom level, you may want to ask for a `full` geometry.

**Comment by zzimickQ** [comment]
> The default is to simplify the polyline, see [the overview option](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#route-service). Depending on your zoom level, you may want to ask for a `full` geometry.

Thanks @jcoupey for your replay. 

I've made my requests to overview=full. the overview=simplified is very low size. but in the overflow full, it's till not matching the map roads.

**Comment by danpat** [comment]
Is your background map generated from the same GIS data that your OSRM routing data is?  Is your PBF file old or outdated?

You can also increase the coordinate precision with `geometries=polyline6` or `geometries=geojson` - this will reduce rounding error in coordinates from 1m down to about 10cm, which depending on how far you've zoomed in on your map, may be a factor.

**Comment by zzimickQ** [comment]
I downloaded the orm.pbf file yesterday. I also used polyline6 and geojson in case polyline (default) was rounding. the data used to render the vector map and the one in OSRM are the same. so no matter how much I zoom in, it should have matched, unless there is any simplification done on the first time processing of the orm.pbf file.

**Comment by danpat** [comment]
@zzimickQ The `osrm-frontend` project doesn't use vector tiles - it uses an older raster tileset from Mapbox, that may no longer be getting updates.

What is the exact lon/lat of the screenshot above?  I suspect the map tiles you're viewing are old.

**Comment by zzimickQ** [comment]
the screenshot I sent above is from the `osrm-frontend`. it should match be latest. I mentioned the vector tile because I tried setting different `geometries` and `overview=full` on a vector map I was using. that might not be latests. but in the `osrm-frontend`.

outdated data can't be the cause for this irregularity, because if it was an update problem. is should match on some places. but the problem here is persistent everywhere. the possibility of it being like this because of outdated data is very low.

**Comment by danpat** [comment]
Did you modify `osrm-frontend` to point to a different tile source?

There are several sources of map tiles available by default:

https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/src/leaflet_options.js#L5-L19

and you haven't specified which map tiles are being shown on your screenshot.  Also, what is the exact coordinate of your screenshot so I can try to debug this?

**Comment by zzimickQ** [comment]
you're right, I was using an outdated mbtiles file. with respect to the osm.pbf for the routing machine. also the osrm-frontend is using an outdated later. if you can provide me with a link where I can find latest mbtiles to download. openmaptiles.org is paid for the lastest, so any other alternates would be fine.

**Comment by zzimickQ** [comment]
Thanks for the help. I'll be continuing to follow this project and is also considering to contribute as much as I can. Thank You. Amazing project. really impressed.
