### ISSUE TITLE
OSRM Backend gives wrong output

### ISSUE THREAD

**Issue by SoulExtinction** [Project-OSRM/osrm-backend#5812]
Hi,

I have installed OSRM backend and frontend for North America Map. When I send coordinates to it, the output gives 0 distance and the coordinates are changed automatically. What could be the reason? I'll give an example below:

Input URL: http://192.168.4.106:5000/route/v1/driving/42.065842,-72.620948;42.177620,-72.562566?overview=false

Output Jason:

 {"code":"Ok","routes":[{"legs":[{"steps":[],"distance":0,"duration":0,"summary":"","weight":0}],**"distance":0**,"duration":0,"weight_name":"routability","weight":0}],"waypoints":[{"hint":"GP-6gbH_uoEAAAAAPQAAAAAAAABsAwAAAAAAAEKZKUIAAAAA1gwYRAAAAAA9AAAAAAAAAGwDAACxkAAA0Ov3AcxmDwKy34ECbOSr-wAAjwJF5SBz","distance":11902035.872662,"name":"","location":**[33.024976,34.563788]**},{"hint":"GP-6gbH_uoEAAAAAPQAAAAAAAABsAwAAAAAAAEKZKUIAAAAA1gwYRAAAAAA9AAAAAAAAAGwDAACxkAAA0Ov3AcxmDwJUlIMCesis-wAAjwJF5SBz","distance":11896500.635443,"name":"","location":**[33.024976,34.563788]**}]}

As you can see I have given different coordinates as input and in output, they are changed to the above coordinates.

**Comment by jcoupey** [comment]
Looks like you have your coordinates switched, OSRM expects lon,lat. In that case, no error is thrown, the points outside the OSM extract are just snapped to the nearest node in the extract. If both input points are snapped to the same node, you get a trivial route with zero distance.

**Comment by SoulExtinction** [comment]
> Looks like you have your coordinates switched, OSRM expects lon,lat. In that case, no error is thrown, the points outside the OSM extract are just snapped to the nearest node in the extract. If both input points are snapped to the same node, you get a trivial route with zero distance.

Thank you so much. The mistake was this small. I was putting lat and long. Thank you
