### ISSUE TITLE
Problem with run container osrm-routed

### ISSUE THREAD

**Issue by setooc** [Project-OSRM/osrm-backend#5816]
Hi!!

We need help with this docker container:

What's wrong with that?

[root@slnxgeo01 openmap-ruteo]# docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/south-america-latest.osrm
[warn] Missing/Broken File: /data/south-america-latest.osrm.datasource_names
[error] Required files are missing, cannot continue
[root@slnxgeo01 openmap-ruteo]# ls -l south-america-latest.osrm
-rw-r--r-- 1 root root 4646804992 Aug 11 13:17 south-america-latest.osrm
[root@slnxgeo01 openmap-ruteo]# docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld south-america-latest.osrm
[warn] Missing/Broken File: south-america-latest.osrm.ramIndex
[warn] Missing/Broken File: south-america-latest.osrm.fileIndex
[warn] Missing/Broken File: south-america-latest.osrm.edges
[warn] Missing/Broken File: south-america-latest.osrm.geometry
[warn] Missing/Broken File: south-america-latest.osrm.turn_weight_penalties
[warn] Missing/Broken File: south-america-latest.osrm.turn_duration_penalties
[warn] Missing/Broken File: south-america-latest.osrm.datasource_names
[warn] Missing/Broken File: south-america-latest.osrm.names
[warn] Missing/Broken File: south-america-latest.osrm.timestamp
[warn] Missing/Broken File: south-america-latest.osrm.properties
[warn] Missing/Broken File: south-america-latest.osrm.icd
[warn] Missing/Broken File: south-america-latest.osrm.maneuver_overrides
[error] Required files are missing, cannot continue

Regards!
IB

**Comment by danpat** [comment]
Most likely your previous steps using `osrm-extract` and `osrm-contract` did not complete successfully.

**Comment by setooc** [comment]
Thanks!

yes, i did it!

And now i have new error:

[root@slnxgeo01 openmap-ruteo]# docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/south-america-latest.osrm
[info] starting up engines, v5.22.0
[info] Threads: 4
[info] IP address: 0.0.0.0 <---- this is bad??
[info] IP port: 5000

terminate called after throwing an instance of 'osrm::util::exception'
  what():  Could not find any metrics for MLD in the data. Did you load the right dataset?

**Comment by danpat** [comment]
You've supplied `--algorithm mld` - this means you must do `osrm-extract`, `osrm-paritition`, then `osrm-customize` as the pre-processing steps.  If you used `osrm-contract` instead of `osrm-partition/osrm-customize`, then remove the `--alghorithm mld` option.

**Comment by setooc** [comment]
Its Works!!

Thank you!
