### ISSUE TITLE
table durations all null

### ISSUE THREAD

**Issue by RuiLoureiro** [Project-OSRM/osrm-backend#5817]
I'm using the table service to get the durations and distances for the shortest path between an origin and a destination.

The response (included below) has two unexpected results:
1. I get a `distance` in the `sources` key. Not sure what this means.
2. Although I seem to get valid a distance (different than 0) in the `destinations` key, the `durations` and `distances` lists are null.

I'm using the latest version of OSRM backend, with the CH algortihm.
* osm.pbf file: https://download.geofabrik.de/europe/portugal-latest.osm.pbf
* profile: https://github.com/DoFabien/OSRM-Bus-profile

<details>
 <summary>Request URL</summary>

```
http://localhost:5000/table/v1/driving/-9.18889397602789,38.74728092470746;-9.181725564965069,38.74562083574992?bearings=280,2;125,2&sources=0&destinations=1&annotations=distance,duration
```

</details>
<details>
  <summary>Response JSON</summary>

```
{
  "code": "Ok",
  "sources": [
    {
      "hint": "UigXAOSmGIAAAAAAYQAAAAAAAAAAAAAAAAAAAATEIkIAAAAAAAAAAAAAAABhAAAAAAAAAAAAAAAUBQAAwM1z_7c7TwLiyXP_kTxPAgAALwZyRntG",
      "distance": 89.429783,
      "name": "Estrada de Benfica",
      "location": [
        -9.187904,
        38.747063
      ]
    }
  ],
  "destinations": [
    {
      "hint": "OQkAgDokFgAAAAAAQQAAAEUAAAAAAAAA9ONAPxi2Y0If8QlCAAAAAAAAAABBAAAARQAAAAAAAAAUBQAA4-Vz_xY2TwLi5XP_FTZPAgQA7wdyRntG",
      "distance": 0.141015,
      "name": "Estrada de Benfica",
      "location": [
        -9.181725,
        38.745622
      ]
    }
  ],
  "durations": [
    [
      null
    ]
  ],
  "distances": [
    [
      null
    ]
  ]
}
```
</details>

**_EDIT_:** I tried the route service and also got no route, because my source bearing was wrong. But I still don't understand why the `source` key has a `distance` and why I get valid distances in the `destinations` key.

**Comment by fofanov** [comment]
The `distance` field in the objects returned by the `sources` and `destinations` arrays refers to the distance from your input coordinates to the ones used in the routing computation.
This is because your input locations are snapped to the street network prior to running the query. You'll notice the location coordinates differ slightly from your input too.
