### ISSUE TITLE
Exclude ferry from route

### ISSUE THREAD

**Issue by SoulExtinction** [Project-OSRM/osrm-backend#5818]
Hi

I have installed OSRM backend using docker in my local. When I try to fetch distance data for many lanes it gives me lanes with ferry path included in it. I want to fetch road distance data. Can someone guide me on how to achieve that? 

I saw a few links like https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/21/truck-soft but I don't know how to change or edit profiles.

It will be a great help if someone can guide me with any other solution or how to use the profile.

Thank you.

**Comment by ioanvictorpantazi** [comment]
http://project-osrm.org/docs/v5.15.2/api/#general-options have a look at the exclude=ferry optional parameter you can pass to your request.

**Comment by SoulExtinction** [comment]
> http://project-osrm.org/docs/v5.22.0/api/#general-options have a look at the exclude=ferry optional parameter you can pass to your request.

Thank you @ioanvictorpantazi It's working for me. 👍
