### ISSUE TITLE
 i can not run osrm on docker

### ISSUE THREAD

**Issue by w8128835** [Project-OSRM/osrm-backend#5819]
hello，i met some problem while i try to setup osrm-backend.
while i use this command ：sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf；my terminal shows that ：Unable to find image 'osrm/osrm-backend:latest' locally
![image](https://user-images.githubusercontent.com/31956796/92324231-67679100-f072-11ea-9cc4-9d75c7079b47.png)

and i tried to pull the latest osrm-backend on the web use：docker pull osrm/osrm-backend；
![image](https://user-images.githubusercontent.com/31956796/92324264-af86b380-f072-11ea-813c-fef720cddec2.png)
i failed again， my terminal shows me this
![image](https://user-images.githubusercontent.com/31956796/92324297-02f90180-f073-11ea-8348-e877f614f6e5.png)
could you please tell me how solve that problem or down load the latest osrm on docker？

**Comment by SoulExtinction** [comment]
Just verifying. There were a few more commands before this command that you should run before the extraction command. Did you run those?

**Comment by wangyoucao577** [comment]
The error shows that you can not access the dockerhub... Fix your network connection please ..

**Comment by SoulExtinction** [comment]
Run the following commands:

1.	sudo apt update
2.	sudo apt install apt-transport-https ca-certificates curl software-properties-common
3.	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
(If the above command gives you error like ‘-’ directory not found then paste the command and press backspace and then again type ‘-‘ on your own)
4.	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
5.	sudo apt update
6.	apt-cache policy docker-ce
7.	sudo apt install docker-ce
8.	sudo systemctl status docker
9.	sudo usermod -aG docker ${USER}
10.	su - ${USER}
11.	id –nG
12. docker pull osrm/osrm-backend

Then continue with extraction commands. If you still get the same error then it's either your internet issue or some docker server issue. I have recently installed OSRM through docker and this error never came. Hope these commands solve your issue.
