### ISSUE TITLE
OSRM won't route through (fastest) valid road

### ISSUE THREAD

**Issue by RuiLoureiro** [Project-OSRM/osrm-backend#5822]
I'm requesting the following route:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=38.73786%2C-9.21651%3B38.73790%2C-9.21715#map=19/38.73776/-9.21754

![Screenshot 2020-09-08 at 12 19 19](https://user-images.githubusercontent.com/16242214/92476304-a31b6b80-f1d6-11ea-8d4f-f2f888134395.png)

However, I was expecting the route to pass through _**Avenida Bordalo Pinheiro**_, like the GraphHopper route:

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=38.73786%2C-9.21651%3B38.73790%2C-9.21715#map=19/38.73792/-9.21683

What keeps OSRM from routing through _**Avenida Bordalo Pinheiro**_?

**Comment by danpat** [comment]
There are some connectivity problems here:

<img width="732" alt="Screen Shot 2020-09-08 at 8 31 45 AM" src="https://user-images.githubusercontent.com/1892250/92497103-c8e04a80-f1ad-11ea-925d-cdd5e6683f3c.png">

The pink sections are OSRM detecting "small components" - parts of the graph that you can't exit *and* enter.  OSRM tries to snap the start/end coordinates to a "component" that both locations have in common.

See https://en.wikipedia.org/wiki/Component_(graph_theory) for some details on what a component is.

Basically, some of these roads can either *only* be entered, or *only* be exited, which makes no sense - it's typically an indication of a mapping issue in the area.

The *actual* issue here is, I think, this node:

https://www.openstreetmap.org/node/1589577471

which OSRM is treating as a barrier.  This is breaking bidirectional connectivity to some of these one-way roads.  https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkissing_gate - you should check if this is the right tag to have at this location, and maybe open a PR to add an exception for this type at https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L54

**Comment by RuiLoureiro** [comment]
Thank you for the explanation. The tag `kissing_gate` is not the correct one. As it is not an OSRM issue, I'll close this.
