### ISSUE TITLE
Routing GET request with lists of different sizes in one response annotation

### ISSUE THREAD

**Issue by kat-ka** [Project-OSRM/osrm-backend#5825]
I have a question. When I'm doing a routing GET request
http://router.project-osrm.org/route/v1/driving/13.381777,52.531677;9.993682,53.551086?steps=true&overview=full&annotations=true&geometries=geojson
I'm getting in the response an annotation nodes list with 2612 elements where the corresponding duration list has 2611 elements. Why do this lists have different sizes and how do I match their values?

**Comment by danpat** [comment]
The speed/duration/weight/etc annotations refer to the edges between the nodes.  If I have nodes A, B, and C, I'll have edges A->B, and B->C.  I.e. one less.

The `nodes` annotation should have the same number of entries as there are coordinates in the route, but the other annotations will be N-1 in length.

**Comment by kat-ka** [comment]
@danpat: Thanks for your explanation and fast reply. I was just wondering, because for a `maneuver` every point has a duration, so you get the same amount of points and durations there.

**Comment by danpat** [comment]
Not every node has a maneuver - curved roads will have many nodes/coordinates, but no maneuvers along their length.

**Comment by kat-ka** [comment]
Yes, as I understood it, `maneuver` points are driving instruction points  and `nodes` are route shaping points. Since the `nodes` are OSM ids I was wondering if the route geometry `coordinates` are the same points or do I need to use OSM to get the corresponding geo coordinates for every node?

**Comment by danpat** [comment]
Yes, the route overview geometry should align 1:1 with the `nodes` annotation.
