### ISSUE TITLE
Keep getting stuck

### ISSUE THREAD

**Issue by ghost** [Project-OSRM/osrm-backend#5827]
I am using ubuntu based server to install OSM algorithm. I have downloiad OpenStreetMap extracts and pre-processed with car profile. 

Now i ran this this cmd 
`docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf`

It doesn't do anything 

![image](https://user-images.githubusercontent.com/71131281/92922413-bb38f800-f42d-11ea-9be5-080285dac3e7.png)

After 10 to 15 mins of waiting, i get this

![MicrosoftTeams-image](https://user-images.githubusercontent.com/71131281/92922554-f3403b00-f42d-11ea-8da4-cb33ea34d58b.png)

**Comment by jcoupey** [comment]
The `osrm-routed` command from the first screenshot seems to suggest the data pre-processing went well since the server is up ("running and waiting for requests").

This command is not expected to "do" anything as long as you don't send routing requests, then requests are logged there. How you run requests locally is up to you, one way to get started is to lookup examples [in the docs](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#example-requests), making sure to adjust the server to `http://localhost:5000`.

**Comment by ShankStorm** [comment]
@jcoupey  is this correct way to make request?
![image](https://user-images.githubusercontent.com/71131281/92938055-01995180-f444-11ea-8ee0-f982bebc2ee5.png)

**Comment by jcoupey** [comment]
Replace `http://router.project-osrm.org` to point to your local setup, probably `http://localhost:5000` will do. You need to run this command from another terminal, then you should get a response there and see the request logged by `osrm-routed`.

**Comment by sppandey2001** [comment]
stuck at this place for local OSRM setup on ubuntu-16.04

![image](https://user-images.githubusercontent.com/1590110/94673632-a5d03300-0334-11eb-81c7-cae8cc9f065e.png)

**Comment by sppandey2001** [comment]
after "running and waiting for requests" nothing is displaying

**Comment by jcoupey** [comment]
Again, this is expected behaviour, the server is literally "waiting" for you to use it.  Run something like 

```
 curl "http://localhost:5000/route/v1/driving/77.36572,23.28171;78.39843,17.37161"
```

**from another terminal** and you'll get a response there, plus the request logged by the `osrm-routed` process.

**Comment by sppandey2001** [comment]
Thanks jcoupey!!!

One more thing as I have locally setup OSM map tiles server also.....how would I can see these on map? please help me in this if possible

**Comment by jcoupey** [comment]
Handling map tiles is outside of the scope of this project. You may be interested in https://github.com/Project-OSRM/osrm-frontend, the project that powers the OSRM demo.

**Comment by sppandey2001** [comment]
thanks jcoupey !!!
