### ISSUE TITLE
windows Binaries update

### ISSUE THREAD

**Issue by simGudim** [Project-OSRM/osrm-backend#5829]
Hello, 

The current windows binaries for osrm located at http://build.project-osrm.org/ are V5.16.0. I was wondering if it is possible to update them to the latest version v5.22.0. I have been trying to do it myself with these instructions https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation and running into some difficulties. Currently I get an error on this step:

downloading osrm-deps-win-x64-14.0-2017.09.7z
Invoke-WebRequest : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Invoke-WebRequest https://mapbox.s3.amazonaws.com/windows-builds/wind ...

Many Thanks

**Comment by simGudim** [comment]
When I download pre-complied binaries http://build.project-osrm.org/ , everything works excellent. However, v5.16.0 does not have the distance table, which is what I need. After  downloading the latest version of the osrm-backend I now get this:

Time Elapsed 00:04:50.73
running extractor-tests.exe ...
Running 18 test cases...

*** No errors detected
running engine-tests.exe ...
Running 28 test cases...

*** No errors detected
running util-tests.exe ...
Running 120 test cases...

*** No errors detected
running server-tests.exe ...
Running 13 test cases...

*** No errors detected


However, I don't see the osrm_Release.zip anywhere.

Thanks

**Comment by akashihi** [comment]
That wiki page definitely needs to be updated :( 

You can compile the windows binaries using that manual: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/windows-deps.md

Or just use docker images on windows :)

**Comment by simGudim** [comment]
Thanks, I would I really appreciate if someone can update the binaries! I know OSRM team doesn't really work on Windows, but I have no choice here and I can't be using docker unfortunately. Thanks!

**Comment by simGudim** [comment]
We company from Jamaica, trying to do some different thing. Unfortunately, we be using windows. If someone can compile the binaries, big man respect. We have big tries, but no fortune. 

Thanks for the software,

Big respect

**Comment by simGudim** [comment]
Straight talk tho.. Linux is the best
