### ISSUE TITLE
Speeding up 'route' request

### ISSUE THREAD

**Issue by patrickeala** [Project-OSRM/osrm-backend#5830]
I aim to calculate road distances between two locations(long,lat). I need to do this 25 million times. I understand that the 'route' request outputs the distance, duration, waypoints, etc.

Is there a way to speed up the 'route' request by modifying it to only output the road distance?

**Comment by akashihi** [comment]
Maybe you could use 'table' request?

**Comment by jcoupey** [comment]
Did you run some kind of benchmarking? OSRM is *very* fast so computing 25 million routes may not be such a big deal. All the more if you need many-to-many distances and can use `table` requests as suggested above.

Others may correct me here, but I don't think you would save anything from trying to get only the road distance anyway, because internally OSRM relies on weight costs. Actual distances are only retrieved after the cheapest route is computed and unpacked.

On the other hand, a significant part of the computing time is spent while deriving the actual position from the road network from input coordinates. If you want a speed-up on this side (and have locations showing up several times), you should dig the `hints` option.

**Comment by patrickeala** [comment]
Thanks for your tips @akashihi  and @jcoupey  I tried using the 'table' function and I achieved significant speedup.

However, I encountered two problems:
1. It outputs duration instead of road distance. Is there a way to get distance?
2. When attempting 100x100 locations I got the output "{'message': 'Too many table coordinates', 'code': 'TooBig'}". What is the max number of coordinates? My goal is to get a matrix for 5000x5000 locations. I can explore slicing the 5000x5000 matrix to address this.

**Comment by akashihi** [comment]
IIRC 'table' returns both distances and durations.

Default limit is 10000 (which is exactly 100x100), but it can be adjusted with `max-table-size` parameter

**Comment by danpat** [comment]
Just to clarify what @akashihi said:

  1. Add `annotations=duration,distance` to your request to get both shortest time, and distance of the shortest time path.
  2. `osrm-route --max-table-size 10000` - this will allow up to 10,000 coordinates in the URL to the `/table` service

Note that if you want 5000x5000, you'll need to make sure you're using a *client* that can support HTTP `GET` URL lines long enough.  `curl` works fine for this, but some client libraries have limits that you may hit.

**Comment by patrickeala** [comment]
thanks for the help @akashihi and @danpat! I got it to work. Cheers.

**Comment by amks1** [comment]
> Do you see any errors on the `osrm-routed` side? Can you make other smaller requests?

Yes I am able to make smaller requests. Also a few of the larger requests go through, but in some cases I get the above error. It seems like the container is restarting upon receiving these requests. I have set the loglevel to DEBUG, and these are the docker logs:

```
[info] starting up engines, v5.26.0
[info] Threads: 4
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:5000
[info] running and waiting for requests
[info] 13-01-2022 11:06:55 88532.4ms 5.36.78.254 - python-requests/2.26.0 200 /table/v1/car/<EXTREMELY LONG REQUEST STRING HERE>?annotations=distance
[info] 13-01-2022 11:15:41 2.85822ms 47.99.168.169 - - 400 /something?123456789?yydfwlyyds
[info] starting up engines, v5.26.0
[info] Threads: 4
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:5000
[info] running and waiting for requests
```

**Comment by danpat** [comment]
Is your docker container set to restart on crash?  The line:

```
[info] starting up engines, v5.26.0
```

indicates that `osrm-routed` was started again.  You should check the logs of your container manager (or check the `docker run ...` return code if you're just running a loop) to see if there was an exit code from the `osrm-routed` process.  Silent exiting like this sometimes indicates an out-of-memory problem with Docker, you need to check your _system_ logs, not the log output of the container itself.

**Comment by amks1** [comment]
@danpat 
This is the output of `journalctl -fu docker.service`, if that's what you mean:
```
Jan 13 20:52:58 dp-2 dockerd[1189]: time="2022-01-13T20:52:58.269851293Z" level=info msg="ignoring event" container=ff51ce948e94dd8644138041c00a4ef20cf69671ec31388860c186902817c741 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jan 13 20:52:58 dp-2 dockerd[1189]: time="2022-01-13T20:52:58.623614775Z" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Jan 13 20:52:58 dp-2 dockerd[1189]: time="2022-01-13T20:52:58.624252809Z" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]
```

**Comment by danpat** [comment]
On Linux systems, the child processes inside the container are still managed by the host kernel.  Things like the [OOM killer](https://support.cpanel.net/hc/en-us/articles/360052914574-What-Is-the-OOM-Killer-) log to syslog, not the docker service.

If OSRM is hitting your docker container memory limit (do you have one set?), it's possible the host kernel is killing the process - you get silent output from the services logs, but there should be something in the _kernel_ logs like:

```
Oct 25 07:28:34 nldedip4k031 kernel: [87976.525050] Out of memory: Kill process 764 (upstart-socket-) score 1 or sacrifice child
```

Have you tried running OSRM _outside_ docker to see if your requests work?

**Comment by amks1** [comment]
@danpat 
Thanks, you're right. I found this line in syslog:
```
Jan 13 20:52:57 dp-2 kernel: [5449273.753650] systemd-udevd invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=-1000
...
Jan 13 20:52:57 dp-2 kernel: [5449273.754257] Out of memory: Killed process 530065 (osrm-routed) total-vm:5591788kB, anon-rss:4685332kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:9388kB oom_score_adj:0
```

Now the question is, how much memory do I need? The machine has 8GB RAM and at least 4GB is free. My datasets are in the 5000-10000 locations range. I tried with both MLD and CH algorithms, and while CH seems to be faster, I'm running into the same issues in both.

**Comment by danpat** [comment]
The only numbers I have are posted in this ticket:

https://github.com/Project-OSRM/osrm-backend/issues/5181#issuecomment-417135981

which IIRC, was for CH.

I would guess that you simply need more RAM to do what you're trying to do - 10,000 x 10,000 is 100,000,000 routes calculated.

An alternative would be to split your large matrix up into multiple smaller requests, then stitch them together after the fact.  You can use the `sources=` and `destinations=` parameters to make asymmetric requests to populate parts of a larger table.

**Comment by amks1** [comment]
Thanks a lot @danpat that's really helpful.
