### ISSUE TITLE
osm.pbf file extraction with docker

### ISSUE THREAD

**Issue by simGudim** [Project-OSRM/osrm-backend#5831]
I am struggling to extract the osm map with docker. I am using windows 10 and have the canada-latest.osm.pbf file stored within the Z drive on the network: 

![image](https://user-images.githubusercontent.com/54817902/93377495-0df92200-f829-11ea-9f25-e444e10c1933.png)

However, i get an error saying that the file canada-latest.som.pbf not found!

Do you think it could potentially be some problem with the fact that I am storing the osm file on the network drive. I have also tried doing that from my local C drive but I get the same error. I have checked out other people who had this issue and I still can't seem to figure it out.

Thanks

**Comment by danpat** [comment]
The command line using `${PWD}` is a Unix/bash environment variable expansion.  You should change the `-v` option to match however your path looks on Windows.
