### ISSUE TITLE
Table not returning distance values for v.5.18.0 or v5.22.0 for CH algorithm

### ISSUE THREAD

**Issue by simGudim** [Project-OSRM/osrm-backend#5832]
Hello,

I know that options for distance table was added in the v5.18.0. However, annotations=distance doesn't work for at all. I have started  the server using docker on windows with the following command:

`docker run -t -i -p 5002:5002 -v C:\Users\sgudim\map:/data osrm/osrm-backend:v5.18.0 osrm-routed --algorithm ch --max-table-size=1000000 -p 5002 /data/canada-latest.osrm`

Everything runs good. However when I making the following request using curl:
`
http://127.0.0.1:5002/table/v1/driving/{0}?sources={1}&destinations={2}?annotations=distance`

I get the following response:

`{'message': 'Query string malformed close to position 1395230', 'code': 'InvalidQuery'}`

If the annotations option is taken out from the request, it runs smoothly and returns just durations and not distances. I have tried both 5.22.0 and v5.18.0 and I am certain I am running the CH algorithm.

Can someone please let me know how to troubleshoot from here.

I have tried this option on the demo server and it works fine, so I don't understand the issue with the latest osrm-backend

I have also looked at this issue #5062, but it still doesn't seem to work for me

**Comment by danpat** [comment]
Replace your `?annotations=` parameter with `&annotations` - normal URL syntax applies.

**Comment by simGudim** [comment]
Thank I appreciate that, everything works perfect now. The documentation has it as `?annotations `instead of `&annotations.`
