### ISSUE TITLE
Sudden increase of route response time

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5837]
Hello

I have a OSRM v5.18 setup on a server with traffic updates for every 3 minutes. The response time is OK most of the time (under 5ms) but suddenly it gets too high. I've checked the cpu, ram and disk io usage and there's nothing unusual as there is no limit for them. 

The routes that I've checked for this case are just random routes with source = destination coordinates (in order to remove long routes factor) but still the response gets high (200-300 ms) sometimes.

Does anybody have an idea what would be the problem?

**Comment by SiarheiFedartsou** [comment]
Closed as stale(feel free to re-open though).
