### ISSUE TITLE
Strange routing, how to avoid routing to the entrance to the building?

### ISSUE THREAD

**Issue by murr999888** [Project-OSRM/osrm-backend#5840]
[http://map.project-osrm.org/?z=18&center=47.088426%2C37.519560&loc=47.089089%2C37.518981&loc=47.088716%2C37.519442&hl=ru&alt=0&srv=0](http://map.project-osrm.org/?z=18&center=47.088426%2C37.519560&loc=47.089089%2C37.518981&loc=47.088716%2C37.519442&hl=ru&alt=0&srv=0)

![image](https://user-images.githubusercontent.com/46183704/94341509-88d4f080-0012-11eb-8979-485f4c24d007.png)

All roads around are free of barriers or restrictions. 
I need a route to be built to any nearest point in the building. How to do it?

I will explain why this is a problem for me. For some reason, this route is the only possible one to this point.
The road on the right is closed for repairs. I simulated this situation on a local server through [traffic data](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic), setting the speed to 0 for this section of road.
But now, if I request a route to this point, I get "No route found between points".

I can understand that the route was taken along the road closest to the point of arrival, but why isn't an alternative route suggested after the original route is no longer available?

![image](https://user-images.githubusercontent.com/46183704/94345906-d7de4e00-0031-11eb-8b3f-f682b90b2d46.png)

**Comment by fofanov** [comment]
As your target location is not on the road network, it will be snapped to the nearest connected segment for routing purposes, which in this case is the service road to the right of the building.

There is logic to avoid snapping to disconnected roads that are not routable between source/target, but in this case the road is connected - setting the speed to 0 won't disconnect the road for snapping purposes.

Connected component construction occurs during the graph extraction phase, so you will likely need to update OSM data to make this work (i.e. actually mark the road as closed if it's a long-term closure).

Alternatively, if the target location is not programmatically set, a [marginally small change](https://map.project-osrm.org/?z=18&center=47.088884%2C37.519062&loc=47.089089%2C37.518981&loc=47.088727%2C37.519410&hl=ru&alt=0&srv=0) will lead to snapping to the left service road

![image](https://user-images.githubusercontent.com/1063186/94491993-34cc3680-01e1-11eb-87b7-d33a751b9b59.png)

**Comment by murr999888** [comment]
Thank you for your comment.

Making changes to the main public OSM map for temporary local needs is not a solution. Keeping and adjusting a copy of the map on the local server or moving destination points - too.

Correcting traffic on certain road sections is a very handy tool. Not only for road repairs, but also in other cases when it is necessary to influence the routing - for example, the road is closed for the movement of trucks or only a specific entry to the client's territory needs to be used.

In my opinion, if there are "disconnected" road sections near the destination, the router should suggest an alternative route along another road within a certain radius from the destination. Then the traffic tool becomes really powerful. 
Let this be my wish for developers. ))

For now, as a partial solution, I set the driving speed to 1 kmh. In 99% of cases, routes are laid avoiding such sections of the road, the remaining 1% is considered an acceptable error. At least such sections are not "disconnected" and do not lead to errors in route calculation.

The question is closed, thanks.

**Comment by fofanov** [comment]
I agree it would be useful, somehow the RTree would need to be modifiable from traffic updates.

**Comment by danpat** [comment]
What we'd probably want here is to snap to the nearest N neighbours, assign a walking speed for the final section from the snap points to the target coordinate, then perform the shortest path search with the search heaps already populated with those sections.

This is related to https://github.com/Project-OSRM/osrm-backend/issues/4465 - OSRM really should seed the search heap with *several* start points and let the search find the best one, rather than narrowing it down to a single snapping point.
