### ISSUE TITLE
osrm-extract fails for `foot.lua` on MacOS

### ISSUE THREAD

**Issue by codemonkey800** [Project-OSRM/osrm-backend#5850]
Hello, I'm trying to run this locally with docker on in MacOS and I'm running into an issue with using `osrm-extract`. I'm using the OSM Southern California location data: https://download.geofabrik.de/north-america/us/california/socal.html

Currently I'm running:

```sh
docker run -t -v $PWD:/data osrm/osrm-backend osrm-extract -p /opt/foot.lua /data/socal-latest.osm.pbf
```

It eventually gets to this stage:

```
[info] Generating edge expanded nodes ...
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% .
```

But it stops around 70% or 80% and returns an error code. When I run the same command with the same data in WSL2 on my desktop, the command finishes successfully. Any help would be awesome 😄

**Comment by danpat** [comment]
Would you mind including the actual error code?  It usually explains why.

**Comment by codemonkey800** [comment]
@danpat ahh that makes sense actually. The error code is `137` and a quick Google search shows that it's a Docker out of memory error. My laptop has 16GB of RAM while my desktop has 128GB 

I suppose there's nothing really actionable here aside from me needing to use a machine with a lot of RAM. I'll go ahead and close this then. Thank you 😄

**Comment by danpat** [comment]
Make sure you've configured Docker to allow use of all your RAM - IIRC, by default, Docker for Mac only allows 2GB per container (last time I looked anyway).
