### ISSUE TITLE
Question regarding calculated distance in Route service with multiple coordinates

### ISSUE THREAD

**Issue by rvolwater** [Project-OSRM/osrm-backend#5852]
We have a previously calculated route with several stops. We determine the distance between each set of stops by using the Route service with start and stop of the distance, as follows:
https://router.project-osrm.org/route/v1/driving/06.01977000,50.89932000;06.02020000,50.89861000?overview=false

For better performance, we want to send 1 call to OSRM to get all distances between all the stops in a route, for instance with a 3rd added stop:
https://router.project-osrm.org/route/v1/driving/06.01977000,50.89932000;06.02020000,50.89861000;06.02202000,50.89990000?overview=false

However, the distance between the 2 first stops differs from the first and the second call (311.9 and 371.6). Why is the distance in the second call with 3 stops so much higher? Is this a bug or an intended feature? This also happens when we send an actual route with 50+ stops.

**Comment by danpat** [comment]
When you supply multiple waypoints to the `route` service, OSRM's car profile, by default, will try to depart from the opposite direction to which you arrive.  The assumption is that u-turns at waypoints are difficult.  This means that A->B->C may not follow the same path as A->B + B->C.

The simple fix is to add `&continue_straight=false` to your request.  Alternatively, you could use the `/table` service to get this data, if you're not interested in the route geometry.

**Comment by danpat** [comment]
I will add that whenever you encounter things like that, it always pays to look at the route geometry on a map - use `overview=full&geometries=geojson` and paste the route path into https://geojson.io/ - visualization often makes the answer obvious.

**Comment by rvolwater** [comment]
Ok, thank you for the quick response and the suggestion to use visualization.
