### ISSUE TITLE
Routing to wrong country

### ISSUE THREAD

**Issue by paultjevdh** [Project-OSRM/osrm-backend#5853]
Hi,
I let openstreetmap (OSRM, car) route from Dwingeloo to Heeg, both in the Netherlands. However I get a route from Dwingeloo (NL) to Heeg in Germany (Near Koblenz)! See the linked image.
Openstreetmap explicitly states Heeg in the Netherlands as end point, so I assume OSRM makes the mistake.

Best regards,
Paul
https://drive.google.com/file/d/1vj3wiG6oSyQJcgp0s_kCQ25qegPWzjKW/view?usp=sharing

**Comment by nilsnolde** [comment]
There's smth wrong with the geocoding on openstreetmap.org. Usually you type an address and it sorta autocompletes, so you can choose which Heeg you want. In any case it's not OSRM fault, which only receives lat/lon from geocoded addresses.

If I try "Dwingeloo" to "Heeg" I get all Dutch versions. Rather open an issue here https://github.com/openstreetmap/openstreetmap-website/issues. And let them know "autocomplete" is not working.

**Comment by paultjevdh** [comment]
How is autocomplete to blame? The screenshot shows that Heeg, the Netherlands is selected.

**Comment by nilsnolde** [comment]
When I'm trying to geocode places it's not giving me any choice at all, which (I thought) it always did. 

If you think it should've selected the right entry, then either the OSM data for geocoding is faulty (probably not) or Nominatim (the geocoder) finds the wrong place. Regardless, OSRM doesn't have anything to do with it.
