### ISSUE TITLE
Map-matching performance dependency on radius

### ISSUE THREAD

**Issue by karatemir** [Project-OSRM/osrm-backend#5854]
I have been trying out the map matching service on the original Seattle GPS data from the Microsoft HMM paper by Newson and Krumm. I noticed that the performance of the service depends on the radius parameter in an undesirable manner. As an example; 
for T=750 timestamps:
- radius=5m     --> the process takes around 600 ms
- radius=20m   --> 2.5-3 seconds
- radius=50m   --> 55-60 seconds
- radius=100m --> 12 min 20 s
for T=250 timestamps:
- radius=5m     --> 200 ms
- radius=20m   --> 1.25 seconds
- radius=50m   --> 26.5 seconds
- radius=100m --> 7 min 52 s
Now obviously for a larger radius value, there are more feasible road segments that can explain the observations so in a way it makes sense for the map-matching Viterbi estimation to take a longer time but I was wondering whether this much of an (exponential) variation is reasonable or not.
----
These results were obtained under the MLD pipeline. I tried out the CH pipeline as well but it actually took a longer time (around 3 times slower with CH). I don't know whether this is expected behavior but reporting it just in case.

p.s. I am using the whole washington.osm.pbf file downloaded from geofabrik instead of just the local Seattle area data, so the underlying road network graph might be large.

**Comment by danpat** [comment]
@karatemir This is expected behaviour, due to the growth of the number of combinations.  You should use the smallest possible radius that works for your data.

**Comment by karatemir** [comment]
@danpat thanks for the prompt answer. I expected the search to take a longer time for larger radius but the computation time growth seemed sort of exponential so I just wondered whether this was expected and whether any thing smarter could have been done on the engine side to improve the performance.

Another question, is it possible to prune the map-matching service to only include specific road classes (say primary and secondary only) to speed up the performance within OSRM? Externally, I can always extract the relevant roads from the osm file but I was wondering whether it is possible to restrict the search space within OSRM?
