### ISSUE TITLE
add multiple osm files?

### ISSUE THREAD

**Issue by Stan92** [Project-OSRM/osrm-backend#5856]
Hi,
Just a quick question (may sound stupid).
Is it possible to use serveral osm files on the same osrm instance?
I mean I would like to use specific countries (example : spain, argentina, canada).

**Comment by jcoupey** [comment]
You can't use several `*.osrm.*` datasets on the same instance, but you can easily merge the selected OSM files before applying the data preparation pipeline. Check out [osmium cat](https://docs.osmcode.org/osmium/v1.11.1/osmium-cat.html) or [Osmconvert](https://docs.osmcode.org/osmium/v1.11.1/osmium-cat.html) for this.

**Comment by mebymyself** [comment]
@jcoupey What is recommended way for merging multiple files?
Should I merge 2 *.pdb files first and then extract/convert the merged file to *.osrm file
OR
extract/convert both files separately and then merge 2 *.osrm files?

I am looking for a method that uses less memory when converting pdb to osrm file.

**Comment by nilsnolde** [comment]
you can't merge .osrm files (unfortunately). you should also avoid merging OSM files, they might have non-overlapping relations, other data statuses etc. best/safest is to have a bigger PBF than you need and `osmium extract` a portion out of it.
