### ISSUE TITLE
Inconsistent implementation between turn_indexes_write_buffer and turn_weight_penalties/turn_duration_penalties

### ISSUE THREAD

**Issue by wangyoucao577** [Project-OSRM/osrm-backend#5862]
All the `index/weight/duration` of turns are generated and written into file in [void EdgeBasedGraphFactory::GenerateEdgeExpandedEdges](https://github.com/Project-OSRM/osrm-backend/blob/9f80f6d64d7294a11cf3cba9bcaf39480c0816ad/src/extractor/edge_based_graph_factory.cpp#L436). However, their implementation are a little bit different.    

Both `turn_weight_penalties` and `turn_duration_penalties` are vectors that cross the function, and will be written into file once when the whole processing finished.      
https://github.com/Project-OSRM/osrm-backend/blob/9f80f6d64d7294a11cf3cba9bcaf39480c0816ad/src/extractor/edge_based_graph_factory.cpp#L472-L474

https://github.com/Project-OSRM/osrm-backend/blob/9f80f6d64d7294a11cf3cba9bcaf39480c0816ad/src/extractor/edge_based_graph_factory.cpp#L1164-L1167

By contrast, `turn_indexes_write_buffer` will be written to file per 1000. It leads to the `write to file` action dispersedly in a few places.                        
https://github.com/Project-OSRM/osrm-backend/blob/9f80f6d64d7294a11cf3cba9bcaf39480c0816ad/src/extractor/edge_based_graph_factory.cpp#L452-L454
https://github.com/Project-OSRM/osrm-backend/blob/9f80f6d64d7294a11cf3cba9bcaf39480c0816ad/src/extractor/edge_based_graph_factory.cpp#L490-L496
https://github.com/Project-OSRM/osrm-backend/blob/9f80f6d64d7294a11cf3cba9bcaf39480c0816ad/src/extractor/edge_based_graph_factory.cpp#L1057-L1064

After go through the codes, I think unify the process of `turn_indexes` same as `turn_weight_penalties/turn_duration_penalties` should be ok, right? Any concern?

**Comment by akashihi** [comment]
(I haven't checked the actual code) It could be saved in batches due to ram limits, which is not a concern in 2020:) so worth trying in my opinion.

**Comment by wangyoucao577** [comment]
@akashihi  I have file a PR, please help to review. thanks!

**Comment by akashihi** [comment]
@wangyoucao577 Done, sorry for delay :(
