### ISSUE TITLE
I'm installing OSRM for North-America and got this error. 

### ISSUE THREAD

**Issue by Chandni-Guidehouse** [Project-OSRM/osrm-backend#5863]

**Comment by Chandni-Guidehouse** [comment]
I'm installing OSRM for the United States of America and got this error. Can someone tell me how to solve this?
` docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/us-latest.osm.pbf`
 [osrm.log](https://github.com/Project-OSRM/osrm-backend/files/5409647/osrm.log)

I have 58GB available memory.
Attaching the logs for review @danpat

**Comment by danpat** [comment]
Check the return code from Docker - my guess would be that you've run out of RAM - Docker will silently kill the process.

The log message at the end is not the last message that should be printed.

**Comment by ChandniGH** [comment]
So then Can you please give an idea of what is the minimum RAM requirement to execute this US file?
