### ISSUE TITLE
build errors on mac OS

### ISSUE THREAD

**Issue by nspforever** [Project-OSRM/osrm-backend#5864]
Got below build errors on MacOS:

`
osrm-backend/src/util/timezones.cpp:157:21: error: loop variable 'v' of type 'const std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2, boost::geometry::cs::spherical_equatorial<boost::geometry::degree> > >, unsigned long>' creates a copy from type 'const std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2, boost::geometry::cs::spherical_equatorial<boost::geometry::degree> > >, unsigned long>' [-Werror,-Wrange-loop-analysis]
    for (const auto v : result)
                    ^
/Users/guannan.du/workspace/nspforever/osrm-backend/src/util/timezones.cpp:157:10: note: use reference type 'const std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2, boost::geometry::cs::spherical_equatorial<boost::geometry::degree> > >, unsigned long> &' to prevent copying
    for (const auto v : result)
         ^~~~~~~~~~~~~~
                    &
1 error generated.
make[2]: *** [CMakeFiles/UTIL.dir/src/util/timezones.cpp.o] Error 1
make[1]: *** [CMakeFiles/UTIL.dir/all] Error 2
`

Repro Steps:

1.  mkdir -p build
2. cd build
3. cmake ..
4. cmake --build .

OS: macOS Catalina(version 10.15.7)
Apple clang version 12.0.0 (clang-1200.0.32.2)
cmake version 3.18.4

**Comment by nspforever** [comment]
There is one more error after the error above:

`
/Users/guannan.du/workspace/nspforever/osrm-backend/src/guidance/segregated_intersection_classification.cpp:229:26: error: loop variable 'e' is always a copy because the range of type 'const osrm::util::range<unsigned int>' does not return a reference [-Werror,-Wrange-loop-analysis]
        for (auto const &e : edges1)
                         ^
/Users/guannan.du/workspace/nspforever/osrm-backend/src/guidance/segregated_intersection_classification.cpp:262:29: note: in instantiation of function template specialization 'osrm::guidance::findSegregatedNodes(const extractor::NodeBasedGraphFactory &, const extractor::NameTable &)::(anonymous class)::operator()<osrm::util::range<unsigned int> >' requested here
                            collect_edge_info_fn(edges1, node2),
                            ^
/Users/guannan.du/workspace/nspforever/osrm-backend/src/guidance/segregated_intersection_classification.cpp:284:31: note: in instantiation of function template specialization 'osrm::guidance::findSegregatedNodes(const extractor::NodeBasedGraphFactory &, const extractor::NameTable &)::(anonymous class)::operator()<osrm::util::NodeBasedEdgeData, osrm::util::range<unsigned int>, osrm::util::range<unsigned int> >' requested here
            if (isSegregatedFn(
                              ^
/Users/guannan.du/workspace/nspforever/osrm-backend/src/guidance/segregated_intersection_classification.cpp:229:14: note: use non-reference type 'unsigned int'
        for (auto const &e : edges1)
`

**Comment by danpat** [comment]
Looks like this happens with an upgrade to apple-clang 12 - it builds cleanly for me with apple-clang 11, but after upgrading I'm seeing the same errors.

**Comment by nspforever** [comment]
> Looks like this happens with an upgrade to apple-clang 12 - it builds cleanly for me with apple-clang 11, but after upgrading I'm seeing the same errors.

Yep, hopefully I can get this fix merged into master soon.

**Comment by nspforever** [comment]
[The pull request](https://github.com/Project-OSRM/osrm-backend/pull/5865) for fixing this issue has been successfully merged.

**Comment by nspforever** [comment]
[The pull request](https://github.com/Project-OSRM/osrm-backend/pull/5865) for fixing this issue has been successfully merged.
