### ISSUE TITLE
one to many MLD return null value whilst many to many MLD return valid value

### ISSUE THREAD

**Issue by Filipe-Tabosa** [Project-OSRM/osrm-backend#5869]
Hey guys. So i've found a potential error on some requests using one to many MLD.
One can verify this error using the osrm server example from wiki.
`http://router.project-osrm.org/table/v1/driving/-46.89499,-23.1790953;-46.894876,-23.179291?annotations=distance,duration&sources=0&destinations=1`
As one can see, I am using -46.89499,-23.1790953 as source and -46.894876,-23.179291 as destination. The distance and duration result for those points are null.
If one try to use the many to many MLD request, those points will work. A valid example would be to duplicate our sources and destinations with the same value, resulting in this request.
`http://router.project-osrm.org/table/v1/driving/-46.89499,-23.1790953;-46.89499,-23.1790953;-46.894876,-23.179291;-46.894876,-23.179291?annotations=distance,duration&sources=0;1&destinations=2;3`

**Comment by danpat** [comment]
@Filipe-Tabosa This case was fixed a few weeks ago:

https://github.com/Project-OSRM/osrm-backend/blame/master/CHANGELOG.md#L22

It's part of the OSRM 5.23.0 release - I suspect the folks at `openstreetmap.de` who operate `router.project-osrm.org` have not yet upgraded.

**Comment by Filipe-Tabosa** [comment]
Oh i.c. Thanks for the update =).
