### ISSUE TITLE
Can't build on macOS Catalina 10.15.6

### ISSUE THREAD

**Issue by ffparra303** [Project-OSRM/osrm-backend#5870]
Hi!

I've been trying to build OSRM following the wiki guidelines. After typing `cmake --build .`, I get the following error

> ccache: error: Failed to create temporary file for /Users/felipeparra/.ccache/tmp/timezones.stdout: Permission denied
> make[2]: *** [CMakeFiles/UTIL.dir/src/util/timezones.cpp.o] Error 1
> make[1]: *** [CMakeFiles/UTIL.dir/all] Error 2
> make: *** [all] Error 2

Does anyone how to solve this issue.

Thanks!

**Comment by danpat** [comment]
Try deleting away your ~/.ccache directory
