### ISSUE TITLE
Take entrance nodes into consideration when destination is an area

### ISSUE THREAD

**Issue by stefannagy** [Project-OSRM/osrm-backend#5871]
The [entrance=* key](https://wiki.openstreetmap.org/wiki/Key:entrance) describes the point where you can go into a building or enclosed area. However, OSRM (as other routing services) seems to ignore this tag. One example:

I want to visit Vienna and I plan to stay in Hotel Ananas. I'm going by car and use OSRM for routing. The tourism=hotel ([way 121670165](https://www.openstreetmap.org/way/121670165)) has an entrance=main ([node 1361284474](https://www.openstreetmap.org/node/1361284474)) in Sonnenhofgasse but OSRM leads me to a point in front of another building ([way 121670132](https://www.openstreetmap.org/way/121670132)) on Rechte Wienzeile – a much frequented road with no place to stop to take a closer look at the map…

As I understand it when the given destination is an area OSRM leads me as close as possible to the middle of that area. I think it would make sense to take existing (at least main) entrances into consideration.

**Comment by danpat** [comment]
OSRM only stores routable geometry.  When you give it a lon/lat to route to, it finds the nearest routable line, and starts/stops there.  Exactly where the route will snap will depend on the coordinate you supply - that building is quite long.

What you're describing would require us to store polygons for shapes like this, and check if the requested coordinate was inside one of these shapes, then use the entrance node as the routing point.

How are you coming up with the coordinate you supply OSRM in the first place?  Are you using a geocoding service to convert the address to a coordinate that you pass in?

**Comment by stefannagy** [comment]
OK, sorry – I guess this is no OSRM issue… But thank you very much for your help.

I'm using https://www.openstreetmap.org/directions – and there I type in 'Hotel Ananas Wien' as destination. So I guess Nominatim supplies OSRM with the so called centre point of this tourism=hotel (see [Details for W121670165](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=121670165&class=tourism)).

For a normal search on openstreetmap.org it makes a lot of sense to return this centre point, but not for routing. Another example: The weather is fine, so I decide to visit [Lainzer Tiergarten](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=27509828&class=boundary) and [go by car](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.1920%2C16.3551%3B48.1767%2C16.2202#map=13/48.1956/16.2610). The nearest entrance when I come from Ananas Hotel for example is [Nikolaitor](https://www.openstreetmap.org/node/289076313). It makes absolutely no sense to try to guide me to the centre point.

So the problem is that Nominatim supplies OSRM with the centre point of areas when I use https://www.openstreetmap.org/directions. Now I don't know where to report this issue…

**Comment by danpat** [comment]
Looks like there is a long-open issue in the Nominatim repo here: https://github.com/osm-search/Nominatim/issues/536

When the developer knows the geocoder is going to be used together with a routing service, the code that takes the geocoding results should look for routing-specific locations (if available) rather than general centroids for a better end-user experience.

I do think Nominatim would be the right place to address this, although it's not totally crazy to add support for something like this to OSRM to work around the lack of routing-specific geocoding support upstream.

**Comment by stefannagy** [comment]
A good reason to add support for this to OSRM is that a lot of areas have several entrances and it would make sense to guide the user to the nearest entrance (accessible by car / bicycle / foot). If I'm not mistaken Nominatim will never return more than one coordinate and to find the nearest entrance is a routing task.

I don't want to sound greedy. Right now I'd be happy if Nominatim would return the coordinate of entrance=main for areas.

**Comment by danpat** [comment]
<img width="459" alt="Screen Shot 2020-10-27 at 9 36 14 AM" src="https://user-images.githubusercontent.com/1892250/97332650-e9d12d80-1837-11eb-81ee-3d3840991593.png">

One issue with doing this in the routing engine is that the geocoder may return a calculated centroid, but it may be outside the polygon boundary.  This would lead to us picking the wrong building in the routing engine, and not really fixing the problem.

I think the ideal here would be:

  1. Have the geocoder return "routing specific" points, like building entrances.
  2. Add support to the routing engine to "route to one of several locations" - (note that this could already be done by making two calls, one to the `/table` with a 1-to-many request to find the fastest path, then a second `/route` request using the fastest location found in the `/table` request).
