### ISSUE TITLE
Where does "result" come from?

### ISSUE THREAD

**Issue by dressl** [Project-OSRM/osrm-backend#5874]
Hello, can anyone tell me where "result" comes from? In car.lua it is used to run the WayHandlers and also a few other times, but I can't see where it is implemented. And what does it refer to?
Best regards.

**Comment by systemed** [comment]
It's the structure (mapped from Lua to OSRM's native C++) that's used to return results from your profile functions.

For example, in `process_node`, you set `result.barrier=true` to say that this node is a barrier. When your Lua function returns, OSRM parses the result object, finds that `.barrier=true`, and acts accordingly.

The `result` attributes that you can set are documented in https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md .

**Comment by danpat** [comment]
Inside the `process_way` callback, the `result` object in Lua is mapped to this C++ object:

https://github.com/Project-OSRM/osrm-backend/blob/master/include/extractor/extraction_way.hpp

The same pattern applies for the `process_node` (see `extraction_node.hpp`) and other callbacks.
