### ISSUE TITLE
Segments untraversable in OSRM causing unexpected routing behaviour

### ISSUE THREAD

**Issue by GeoWonk** [Project-OSRM/osrm-backend#5875]
I am running a local instance of OSRM and have noticed a routing error on a section of the Reid Highway in Western Australia. The routing erroneously leaves a major road only to rejoin it later. As of the time of posting this error is replicated by the version of OSRM [here](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-31.8639%2C115.9880%3B-31.8620%2C115.9442#map=14/-31.8614/115.9669). The Graphhopper routing available on what I presume is the same underlying data [behaves as expected](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=-31.8639%2C115.9880%3B-31.8620%2C115.9442#map=15/-31.8622/115.9661).

Further investigation reveals that OSRM (but not Graphhopper) [cannot traverse the intervening ways at all, even when routing from one part of a segment to another](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-31.8637%2C115.9778%3B-31.8637%2C115.9770), so it does not appear to connectivity.

I have noticed in the past that OSM (not just OSRM( routing can be sensitive to tags - for instance it would force a turn off from a motorway if the node at which the motorway_link connected to the motorway was not labelled "motorway junction" but there is no obvious discrepancy between the affected ways and ways of the other side of the highway or further east/west. The affected area seems to be covered by[ this changeset](https://www.openstreetmap.org/changeset/90684856#map=15/-31.8621/115.9670) however.

**Comment by mjjbell** [comment]
The [debug tiles ](https://map.project-osrm.org/debug/#16.39/-31.86317/115.98156) show the westbound road has been filtered out completely.

The culprit appears to be the [construction=trunk](https://www.openstreetmap.org/way/664813186#map=16/-31.8633/115.9778) tag, which will be applied in the [default profile](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua#L641).

I imagine this is applied even if `highway=construction` is not set to be conservative in the routing results.

**Comment by GeoWonk** [comment]
Thank you! I guess this is expected behaviour on the OSRM side and I am happy for the issue to be closed.

**Comment by danpat** [comment]
As a practical matter, I'd suggest turning off `construction` support in your own profiles - remove this line: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L136

My experience has generally been that OSM `construction` tags are stale more often than they are good - we may be overall more often correct by not making this tag supported by default.
