### ISSUE TITLE
Figure out new CI setup

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#5877]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

OSRM will be affected by these changes.  Without a working CI setup, no new releases can be made.

**Comment by wangyoucao577** [comment]
I can help to setup some via the **free** [Github actions](https://github.com/features/actions). As you see, I have setup some in our [fork](https://github.com/Telenav/osrm-backend/tree/master/.github/workflows) and [they work very well](https://github.com/Telenav/osrm-backend/actions).       

Which one do you want to setup firstly?

**Comment by akashihi** [comment]
Hello!

As an alternative for github actions, we can use semaphoreci.com, but I
guess github is a safer choice: with all MS money they can afford keeping
it free for a longer time.



сб, 7 нояб. 2020 г. в 04:05, Jay Zhang <notifications@github.com>:

**Comment by systemed** [comment]
Github Actions work for me.

**Comment by danpat** [comment]
I migrated the `osrm-backend` repo to `travis-ci.com` yesterday (it's a one-click operation).  Builds are running again, but we're on the Free plan, which has a limit of 10,000 minutes per month.

**Comment by jcoupey** [comment]
> a limit of 10,000 minutes per month

My understanding is that Free plans comes with a **one time** allocation of 10,000 minutes for try-out only. There is a "OSS only credits" pool that can be replenished but this requires someone to send a request by email to the Travis support, as per [this FAQ](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source).

**Comment by SiarheiFedartsou** [comment]
Not actual anymore since we migrated to GitHub actions.
