### ISSUE TITLE
Immutable Version of OSRM

### ISSUE THREAD

**Issue by patrickeala** [Project-OSRM/osrm-backend#5881]
I will be using OSRM for a project for an extended period of time. I have integrated the OSRM queries in my programs. I am currently using the osrm-backend docker. I understand that the docker updates the osrm server automatically.

I am worried that when OSRM releases an update, it may cause errors in my program. Is there a way for me to setup an osrm server and prevent all updates from happening?

**Comment by danpat** [comment]
This isn't really an OSRM question, but more of a Docker one.

If you want to pin your code to a specific release, you should use a line like this in your Dockerfile:

```dockerfile
FROM osrm/osrm-backend:v5.23.0
```

The `v5.23.0` is a specific Docker tag - you can see the available tags here: https://hub.docker.com/r/osrm/osrm-backend/tags

The trick for immutable builds is not to depend on the `latest` tag, which is the one that gets used if you don't include a tag in your `FROM` line.  I.e. do not do:

```dockerfile
FROM osrm/osrm-backend
```

or 

```dockerfile
FROM osrm/osrm-backend:latest
```

This basic principle applies to most dependency management systems.
