### ISSUE TITLE
500 Internal Server Error with the demo server using US Locations

### ISSUE THREAD

**Issue by zhengcharlie8** [Project-OSRM/osrm-backend#5885]
Hi, I'm currently using the demo server for a project. I am trying to use the route service and the queries listed in the documentation work but I was trying to change them to US coordinates. When I input US coordinates, it gives me 500 Internal Server Error.

This is an example of a query I have been trying:
http://router.project-osrm.org/route/v1/driving/-105.044410,39.636111;-74.115622,40.665955

Please let me know if I am doing anything wrong since I am new at this.

**Comment by datendelphin** [comment]
Hi  zhengcharlie8. No you are doing nothing worng I think, you just had bad luck. This morning the copying of the new routing graph was incomplete, and osrm couldn't start. Should be fixed soon,

**Comment by zhengcharlie8** [comment]
Thank you. The issue seems to be resolved!
