### ISSUE TITLE
consider traffic on the map

### ISSUE THREAD

**Issue by NasserEspari** [Project-OSRM/osrm-backend#5889]
we want to consider traffic on the map
i read  link : [link](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) and know that we should provide a csv file but i dont know this 2 things : 

1- Where should we get from_osm_id and to_osm_id 
2- how should we consider traffic? using google api or there is another way to get speed per kilometer?

**Comment by danpat** [comment]
@NasserEspari There are no public sources of this data - you have to build it yourself.

Google will not permit you to scrape this data from their service.  Most typically, folks who do this have access to a repository of real GPS data, and they build a tool to match those GPS traces to the underlying OSM map (sometimes using the OSRM `/match` endpoint, with the `annotations=node` parameter) to generate the traffic data files.
