### ISSUE TITLE
Building on Ubuntu wiki page needs instructions for 20.04

### ISSUE THREAD

**Issue by mvl22** [Project-OSRM/osrm-backend#5890]
The wiki page at:
https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu

goes as far as Ubuntu 18.04, but Ubuntu 20.04 is now in general availability, so would be good to have added to this page. (I am unsure myself whether any changes are needed to the package list.)

It looks from issue #5797 that a fix 018a9bc80449d85c0e40fa5215377d8a03264c88 was made, which is tagged v5.23.0, so presumably the Wiki page, when amending to add 20.04, should note that 5.23.0 is presumably the earliest supported version on Ubuntu 20.04.

**Comment by akashihi** [comment]
Ubuntu 20.04 comes with GCC10 and newer CMake, that causes some issues with building. There is an ongoing work on fixing those issues, but i'm afraid it's too early to start supporting 20.04 officially

**Comment by dburnsii** [comment]
This is blocked by https://github.com/Project-OSRM/osrm-backend/issues/5858, which is currently in work.

**Comment by systemed** [comment]
I've successfully built current master out-of-the-box with Ubuntu 20.04, so I think we can close this. I've edited the wiki instructions.

(`build-essential` on Ubuntu 20.04 installs GCC9, not 10, FWIW.)
