### ISSUE TITLE
Route provided is terrible, and different than demo server

### ISSUE THREAD

**Issue by caleb87** [Project-OSRM/osrm-backend#5892]
I built OSRM on Ubuntu 18. I ran osrm-routed with MLD. 

OSRM demo gives a superb route. Example Route: http://map.project-osrm.org/?z=10&center=35.891831%2C-98.521957&loc=36.253133%2C-98.480072&loc=35.821432%2C-98.779449&hl=en&alt=0&srv=0

Mine OSRM server provides this route: http://map.project-osrm.org/?z=12&center=35.872777%2C-98.565731&loc=36.253133%2C-98.480072&loc=35.948273%2C-98.493805&loc=35.890441%2C-98.507881&loc=35.821432%2C-98.779449&hl=en&alt=0&srv=0

That route uses roads classified as residential, instead of 65mph secondary roads. 

This is using the default car profile. 

Traffic data shouldn't affect this, because there is no traffic data in my server, and the optimal route regardless of traffic is the one the OSRM demo provides.

![osrmbug](https://user-images.githubusercontent.com/6970514/100024163-80472f00-2da3-11eb-9437-983ecc573983.jpg)

**Comment by danpat** [comment]
@datendelphin Is the demoserver running unmodified versions of `car.lua`?  If not, do you have a link to the changes?

**Comment by datendelphin** [comment]
Hi! The profiles are stored here: https://github.com/fossgis-routing-server/cbf-routing-profiles/

**Comment by systemed** [comment]
I wonder if this might be an issue with differing maxspeed handling. The residential roads in this area all have `maxspeed=45 mph` as a result of an automated edit. That's fine but in reality you're unlikely to hit 45mph * 0.8 (`speed_reduction`) on these unpaved roads. (As ever in the rural US, the surface has generally not yet been tagged.)

**Comment by caleb87** [comment]
@systemed I suspected the same, and I actually made a PBF that removed all 45 MPH roads in Oklahoma counties. The route was still the same. I should have saved the PBF so others could have tested it, but I gave up and just ended up deleting the AWS instances I had it on.

I'm currently using Graphhopper for routing, but I'd still like to switch to OSRM because it seems to give better routes. I saw your debug script which seems like the best way to figure this out. Do you have a usage for dummies example? Is this something to run from the API or from terminal?
