### ISSUE TITLE
Clang-format version upgrade

### ISSUE THREAD

**Issue by dburnsii** [Project-OSRM/osrm-backend#5893]
Clang-format for this project is currently set at version 3.8, which is based on an old version of the compiler. The oldest version of clang-format currently offered by Arch only goes back to 3.9.

To keep this project modern, the clang-format version should be upgraded to version 10.0.1.

**Comment by danpat** [comment]
The reason it's pinned to older versions is that upgrading will introduce a bunch of formatting changes.  Unfortunately new defaults/rules in newer versions means that even with the `.clang-format` file we have, changes will get introduced.

If we upgrade, we should pin to a new version, and do a big "reformatting changes" commit.

**Comment by dburnsii** [comment]
I know we've been avoiding changing the entire repo with the formatting, but in this case, are you suggesting we upgrade the clang-format version and update all the *.hpp and *.cpp files?
