### ISSUE TITLE
Set OSRM to use max/default speeds, with no penalties (angle, lanes, intersection)

### ISSUE THREAD

**Issue by zerospin** [Project-OSRM/osrm-backend#5896]
Hi,

If there is a simple way to remove all penalties in OSRM, so only raw speed (max default or default speeds) is used in route calculations.

I have removed the turn penalties with success by changing in car.lua, but I have not succeeded in removing penalties from roads with angles with and roads up to and after intersections. 

Can this be achieved by changes in *.lua files (car.lua, way_handlers.lua) ? or is there some code in the core that overrides this. I'm using OSRM via docker

An example:
![image](https://user-images.githubusercontent.com/532518/100238597-b1089f00-2f30-11eb-90ad-813a8a03e98f.png)
The left turn lane, from south has a OSM max_speed of 50km/h, and is reduced to 19 km/h. WHich function/penalty is controlling this. I also looks like way before and after intersection are reduced in speed.

**Comment by wangyoucao577** [comment]
Didn't find the "left turn lane" you mentioned in the example.      
[How OSRM Calculate Weight and Duration](https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/how_osrm_calculate_weight_and_duration.md)  This wiki may help you.
