### ISSUE TITLE
traffic data -  debug log of missing edge relations

### ISSUE THREAD

**Issue by zerospin** [Project-OSRM/osrm-backend#5897]
Hi,

I'm adding speeds from GPS-data into osrm using the traffic updates
https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

It is working great, but the debug possibilities seems limited.  

My "osrm-contract" is outputting:

```
[info] Used 20 speeds from LUA profile or input map
[info] Used 311514 speeds from /data/car/cc_speed_data.csv
```

Is it possible to get a list of the egdes-relations/osm node-relations that get it speed from the lua file, and therefore are missing from  traffic update file ? or the other way around, an output of all edgde relations in osrm graph ?

**Comment by danpat** [comment]
The only readily available tool would be the debug tiles (https://github.com/Project-OSRM/osrm-frontend/tree/gh-pages/debug) - change the map style there to highlight (I like to use bright pink) edges that have a `datasource` property of `lua profile`, then browse around the map and look for them.
