### ISSUE TITLE
How to get the Lon/lats given Node IDs?

### ISSUE THREAD

**Issue by icyshenfighting** [Project-OSRM/osrm-backend#5898]
Hi, 
When I retrieve a route, I get a sequence of node ids in annotation[''nodes"]. 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/62524930/100393384-0e6b2180-2fff-11eb-8bd1-8b57dd6a00b4.png">

Is there any fast way to find the longitudes and latitudes of these node ids without decoding geometry?

 I just want to know the longitudes and latitudes and no other information, so dictionary of node id and (Lon, lat) would be better. But I cannot find that.

**Comment by danpat** [comment]
If you add `overview=full` to your request, then you'll get back the route coordinates in full detail.  Each coordinate maps 1:1 to an entry in the `annotation["nodes"]` array, except for the first/last nodes - these are the nodes before the snapped start coordinate, and after the snapped end coordinate, respectively (the input coordinates typically aren't precisely on a node).

**Comment by icyshenfighting** [comment]
Thanks for your reply. I know I can get the lon/lat using geometry, but I am wondering is there is any faster way to realize it. 
Since if I use the geometry code, I have to decode it and find every node information which adds more work.

**Comment by danpat** [comment]
No, there's no faster way.  Here is some sample Javascript code that will do what you want:

```
const request = require('request');

const server = 'router.project-osrm.org';
const origin = '-122.44030,37.792151';
const destination = '-122.4156,37.78482';

request(`https://${server}/route/v1/car/${origin};${destination}?overview=full&annotations=nodes&geometries=geojson`, { json: true }, (err, res, body) => {
  if (err) {
      return console.log(err);
  }
  body.routes[0].geometry.coordinates.forEach((coord, index) => {
    if (index === 0 || index === body.routes[0].geometry.coordinates.length -1) {
      console.log('Node for first/last coordinate is not known');
      return;
    }
    console.log(`${coord} = ${body.routes[0].legs[0].annotation.nodes[index]}`);
  });
});
```
