### ISSUE TITLE
support for postgis import

### ISSUE THREAD

**Issue by MichalPP** [Project-OSRM/osrm-backend#590]
osm2pgsql creates a nice postgis database which allows a lot of nice spatial features which could enhance routing: penalize footway too close to a noisy street, overlap highways and OSM relations to increase its attractiveness, relatively easy 3d support, increase/decrease way based on number of nearby pubs, name footway based on the name of nearby street, ...

a pgsql2osrm command would make this preprocessing a lot easier (though turn restrictions make this a lot harder).

or a framework to query a SQL database to get extra information on a way in order to use them in lua profile scripts.

additional thoughts:
an easy fix would be to:
connect to SQL somewhere
in settings create a variable to query to an edge/node tags using variables type (node/way), osm_id (of OSM database), lat,lon of first node of a way, lat,lon of the last node (to catch for split ways)
so something like
$way_query="select safety as safety from myways where osm_id=$osmd_id"
to query for a "safety" parameter (which i pre calculated based on traffic, road width, ..)
$node_query="select count(*) as num_of_pubs from poi where st_distance('POINT($lat,$lon)', way)< 100";
to query for number of nearby pubs in order to penalize a node during AA routing.

have this extra tags available in lua scripts.

**Comment by daniel-j-h** [comment]
There is a example lua profile that makes use of a postgis setup; this is exactly what you need.
