### ISSUE TITLE
map matching doesn't find the key 'matchings'

### ISSUE THREAD

**Issue by zehavi11** [Project-OSRM/osrm-backend#5904]
Hey,
I looked into this https://spatialthoughts.com/2020/02/22/snap-to-roads-qgis-and-osrm/
and tried to follow the steps, but when I was trying to run the python script from the QGIS I got the next error:

Traceback (most recent call last):
File "<string>", line 91, in processAlgorithm
KeyError: 'matchings'

seems that it doesn't get any results from the request. did someone else get the same error? what did you do?

Thanks in advance

**Comment by frodrigo** [comment]
The python script is not part of the OSRM project.
