### ISSUE TITLE
Why do not lock the variable in "processor_stage" at tbb::parallel__pipeline?

### ISSUE THREAD

**Issue by jdaeman** [Project-OSRM/osrm-backend#5905]
Hi.

Local variable "node_base_edge_count" is not synchronized in "processor_stage".
Code, edge_based_graph_factory.cpp
Line, 450, 753

Is that correct?

My osrm-backend version is 5.23

Thank you.

**Comment by danpat** [comment]
That's a bug.

Fortunately, all that variable is doing is tracking the count for eventual printout - it has no effect on any of the generated data.

Feel free to submit a pull request to fix it.
