### ISSUE TITLE
Incompatible files with backend

### ISSUE THREAD

**Issue by gtm144** [Project-OSRM/osrm-backend#5917]
I tried working with latest docker osrm-backend tool and this the issue that I get
`File is incompatible with this version of OSRM: /data/complete.osrm.cells prepared with OSRM 5.24.0 but this is v5.22.0 (at include/storage/tar.hpp:204)`

**Comment by danpat** [comment]
That message is intended to be fairly self explanatory - you cannot use files prepared with an earlier version of OSRM with a later one.

Delete your `*.osrm*` files and re-create them with the Docker image you're using.
