### ISSUE TITLE
Trans-Canada Highway not allowing eastbound traffic

### ISSUE THREAD

**Issue by DJohaneson** [Project-OSRM/osrm-backend#5919]
I have located an error on OSM that only occurs when I select OSRM routing--it works fine with Graphopper routing.

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.99802%2C-118.68869%3B50.99901%2C-118.68584#map=10/50.7751/-118.8148

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=50.9980%2C-118.6887%3B50.9990%2C-118.6858#map=18/50.99852/-118.68727

When I select Graphopper routing, this is a 228m & 0:00 time highway route. With OSRM routing, it is 173km and 4h12m routing. I have tried everything I can think of in OSM to correct this, but the problems seems to be only in OSRM. Any help would be great!

**Comment by systemed** [comment]
OSRM's default car profile avoids roads tagged as 'proposed'. Until 22nd December, the way had a `proposed=trunk` tag. On the 22nd this was removed: https://www.openstreetmap.org/way/364401129/history

After the daily update OSRM happily routes across it.
