### ISSUE TITLE
structure of the .osrm and .osrm.* files

### ISSUE THREAD

**Issue by ksv87** [Project-OSRM/osrm-backend#5920]
Good day!
Can you please tell me where to see the description of the .osrm and .osrm.* files?
What is the structure of these files?
I have a task to add one property for roads, this property will need to be used when laying routes.

PS: sorry for my English, this is machine translation.

**Comment by wangyoucao577** [comment]
Please refer to https://github.com/Project-OSRM/osrm-backend/wiki/Toolchain-file-overview and https://github.com/Telenav/open-source-spec/tree/master/osrm/doc/osrm-toolchain-files

**Comment by ksv87** [comment]
Thank you very much, this is what I need
