### ISSUE TITLE
Some turn restrictions are ignored

### ISSUE THREAD

**Issue by matkoniecz** [Project-OSRM/osrm-backend#5921]
See https://www.openstreetmap.org/relation/11787041

**Comment by jcoupey** [comment]
Based on [this comment](https://github.com/Project-OSRM/osrm-backend/pull/5907#issuecomment-752641934), you're aware that a related PR has recently been merged to `master`. I would not expect the demo server to reflect those changes yet. Do you mean that the linked relation is not correctly used when using current `master`, or are you using the demo server or OSM home page?

**Comment by matkoniecz** [comment]
Whops, sorry. I was researching what is happening, opened this issue, finished updating comparison of routers at OSM wiki, researched more, posted comment that you mentioned and in meantime forgot about this issue.
