### ISSUE TITLE
"foot" profile doesn't work 

### ISSUE THREAD

**Issue by nikmwra** [Project-OSRM/osrm-backend#5922]
Hello 

 I'm working on a project for my pregraduate thesis, I want to compare the travel-duration beetween "foot" and "car", for multiple random routes inside of a city. I tried to use the "http://router.project-osrm.org" server, but when I do a "foot" request I get a "car-profile" respond instead, even if the API documention says it is supported.  Also, how many requests can I do and how fast so I don't mess up with the server.

**Comment by datendelphin** [comment]
Here is an example request https://routing.openstreetmap.de/routed-foot/route/v1/driving/6.888427734375,51.43282203009056;7.0751953125,51.069016659603896?overview=false&alternatives=true&steps=true
Even though it's a different domain, it's the same server. For usage policy please see http://routing.openstreetmap.de/about.html
