### ISSUE TITLE
How to modify the car.lua profile

### ISSUE THREAD

**Issue by robbertwynn** [Project-OSRM/osrm-backend#5924]
Hi, it's a bit unclear to me how I modify the car.lua profile. I only need to change the variable `oneway_handling  = true` to `oneway_handling  = false`. I'm setting up OSRM using docker, but after downloading the osm file from Geofabrik, the following step according the documentation is to pre-process the extract with the car profile by running `docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf`. How do I modify the car.lua profile before that?

**Comment by frodrigo** [comment]
Just edit the `profiles/car.lua` before processing the data.
If you need to edit again the lua profile, you need to re-process the data again.

**Comment by robbertwynn** [comment]
I understand that I need to edit the car.lua before processing the data but how do I exactly do it? Do I need to clone the repository locally and modify the `profiles/car.lua` file there? But how then do I make sure that I am processing the data with the modified car profile? Running `docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf` will use the default car profile right?

**Comment by frodrigo** [comment]
Yes clone the repo. Edit the file, if you not comfortable with docker docker, do it without docker. In opposite just mount the car.lua or other edited files into the docker.

**Comment by robbertwynn** [comment]
So if I understand it correctly, after I cloned the repo locally and edited the file, I can mount the modified car.lua file into the docker container by running the following command: `docker run -t -v "${PWD}:/data" -v "/path/to/cloned/repo/osrm-backed-master/profiles/car.lua:/profiles" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf` ?

**Comment by TimMcCauley** [comment]
@robbertwynn no - you can put your lua file into the data folder where you osm file resides, this way you can change the -p argument into `-p /data/car-anyvan.lua` as it will be mounted into the container.

`docker run -t -v "${PWD}:/data" osrm/osrm-backend:v5.23.0 osrm-extract -p /data/car.lua /data/britain-and-ireland-latest.osm.pbf`

**Comment by robbertwynn** [comment]
Thanks, that worked!
