### ISSUE TITLE
Unsuccessful matching with high matching confidence

### ISSUE THREAD

**Issue by matchumen** [Project-OSRM/osrm-backend#5928]
Hi,

When I map match traces, sometimes I end up with partially matched trace but high confidence is given. There is no clear rule when this happens, even though when this problem occurs on a long trace (1000s of points), it can be solved by matching undersampled trace instead.

What can be the cause or did anybody else came across such problem?

(Running my own instance, launched with: docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/czech-republic-latest.osrm --max-matching-size 10000 --max-matching-radius 100)

![image](https://user-images.githubusercontent.com/30288863/104136558-54096100-5397-11eb-8483-1053119d824b.png)

Thank you

**Comment by danpat** [comment]
Check the `tracepoints` element in the result - there should be an entry in this array for every input coordinate.  If the number of coordinates you think you're submitting, and the number of tracepoints in the result differ, then it's likely your client is truncating your request.  `osrm-routed` has no limit on the GET request URL length, but many HTTP client libraries do.

**Comment by danpat** [comment]
I will note that undersampling is probably a good idea anyway.  It'll speed things up a lot, especially with a larger `radius=` value, and there would be very little loss of matching accuracy if you don't undersample too aggressively.

I would suggest looking at something like https://github.com/mapbox/geosimplify-js as an approach that will strip out redundant GPS coordinates without damaging the shape of the trace for matching purposes.

**Comment by matchumen** [comment]
It seems there were 2 different problems. 
Human error on my side - the shorter matchings were incomplete because I did not check all matchings (match was split in 2 parts).
Problem with Python Requests package - the request was indeed truncated.

Thank you for the help and the suggestions.
