### ISSUE TITLE
Trip plugin error message 

### ISSUE THREAD

**Issue by hannesaddec** [Project-OSRM/osrm-backend#5933]
In case one of the endpoints in trip are not reachable by the endpoint, OSRM throws just  "NoTrips" error message. 
It would be nice: 
a) if the endpoint could report which one is not reachable so this information could be used in the processing  of the response. 
b) if the trip would respond still without that specific location. 

Example: https://gisco-services.ec.europa.eu/route/v1/railway/13.77685546875,51.048301133312265;-0.1276474,51.5073219;-6.2602732,53.3497645?overview=false&alternatives=true&steps=true 

(due to non-existence of a railway ferry between UK and IE)

**Comment by jcoupey** [comment]
Not sure b) is such a good idea as then you'd constantly have to check the number of locations in "normal" responses to make sure none has been discarded.

About a), what you can simply do when encountering this error is to fire the same request to the `table` plugin. Infeasible routes will show up as `null` in the `durations` matrix.

https://gisco-services.ec.europa.eu/table/v1/railway/13.77685546875,51.048301133312265;-0.1276474,51.5073219;-6.2602732,53.3497645

**Comment by hannesaddec** [comment]
nice idea about a) - but can the table not be fired instead/in addition to the "noTrips" - just to make it more easier to handle that ?

**Comment by jcoupey** [comment]
In order to perform the optimization, the `trip` plugin does a many-to-many search to get durations, which amounts to the same work as a `table` request. So the `noTrips` error you get is *precisely* a consequence of the fact that there are `null` values in the durations matrix.

**Comment by jcoupey** [comment]
If you want to find out which inaccessible location is responsible for the error, you can simply go through the matrix to spot `null` values, then the row/column with the highest number of `null` values is the winner.

If it helps, check out [this loop](https://github.com/VROOM-Project/vroom/blob/5f905dc5d133af926008d811aaaea0c82a7e0acc/src/routing/http_wrapper.cpp#L150-L170) and [this check](https://github.com/VROOM-Project/vroom/blob/master/src/routing/wrapper.h#L43-L73) where I'm applying exactly this technique in a downstream project to report the relevant problematic location to end users.

**Comment by hannesaddec** [comment]
thx for the point - we will use something along the lines
