### ISSUE TITLE
is it possible to run as a service?

### ISSUE THREAD

**Issue by alexandremsouza1** [Project-OSRM/osrm-backend#5939]
is it possible to use osrm build as a service?

and whether it is also possible to use a port other than 5000?

I looked in the documentation and I didn't find

**Comment by danpat** [comment]
Your question isn't very clear.  You can run `osrm-routed` yourself any way you like - what exactly do you mean by "as a service" ?

To run `osrm-routed` on a port other than 5000, try doing `osrm-routed --help`.  There are several things you can configure, the port is one of them.

**Comment by alexandremsouza1** [comment]
It would run as an operating system service.

as a

sudo service apache2 start

on linux starting apache.

that way, I can log ssh on the server and do other things

thanks for the help tip

**Comment by danpat** [comment]
@alexandremsouza1 Our codebase doesn't include any of the configuration/code you'd need to do that.  The `service` command is part of the `systemd` operating system setup.

Take a look at https://linuxconfig.org/how-to-create-systemd-service-unit-in-linux for how to run any program as a daemon via `systemd`.

We do provide Docker images - there are many ways to run Docker containers persistently, like [Portainer](https://www.portainer.io/) or other system orchestration tools, like Kubernetes.
