### ISSUE TITLE
Turn penalty with multiple via-way restrictions

### ISSUE THREAD

**Issue by NguyenSen** [Project-OSRM/osrm-backend#5941]
I saw project had new feature [ add multiple via-way restrictions](https://github.com/Project-OSRM/osrm-backend/pull/5907)
I question for you update about update Turn penalty with multiple via-way restriction ?
Thanks OSRM team .

**Comment by danpat** [comment]
@NguyenSen Can you re-state the question?  Turn penalties apply to a maneuver from one way to an adjacent way.  The PR did not add support for specific penalties for "compound" maneuvers, if that's what you mean to ask.

**Comment by NguyenSen** [comment]
> @NguyenSen Can you re-state the question? I'm not sure what you want to know.
> 
> Turn penalties apply to a maneuver from one way to an adjacent way. The PR did not add support for specific penalties for "compound" maneuvers, if that's what you mean to ask.

@danpat i'm try use update turn panaty and follow [traffic](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic)

my country have turn restriction with time dependence

sorry @danpat  because my english is not good

**Comment by danpat** [comment]
@NguyenSen I think I understand now.  There is still no support for loading turn penalty data for complex turns using the turn penalty data.

However, you should now be able to add an `restriction:conditional=` tag to the relation in the map data (https://wiki.openstreetmap.org/wiki/Relation:restriction), and if you use `osrm-customize --use-conditionals-from <timestamp>`, complex restrictions should work.
