### ISSUE TITLE
Create 5.24.0 release

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#5946]
I want to make another release, primarily to get support for Node14 out in an official build.

I think we should try to get the following PRs merged before I go ahead with the release:

  - Cleanup the NodeJS dependencies https://github.com/Project-OSRM/osrm-backend/pull/5945
  - Revert changes to the binary interface that broke in 5.23.0 https://github.com/Project-OSRM/osrm-backend/pull/5861

@jcoupey Can you verify that #5861 lets [Vroom](https://github.com/VROOM-Project/vroom/) build again?

**Comment by jcoupey** [comment]
@danpat thanks for the initiative. I can confirm that the build problem is fixed by cherry-picking the commit in #5861 to current `master`. FWIW, the downstream code uses `Route` and `Table` functions from libosrm, not the other plugins.

**Comment by danpat** [comment]
The release is done.

https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.24.0
