### ISSUE TITLE
What OSRM files are read from disk?

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5948]
Hello

I want to know what files are read from disk? Is it possible to store all of them in memory? It seems that disk performance affects OSRM response time.

Thanks

**Comment by danpat** [comment]
If you just do `osrm-routed map.osrm`, then all files, except the `.fileIndex` file are loaded into RAM.

The `.fileIndex` file contains the spatial index - use for locating your coordinates on the road network.

**Comment by safe-bug** [comment]
@danpat Thanks for your reply. Isn't it possible to also load the .fileIndex into RAM? (To avoid disk latency effect on OSRM performance)

**Comment by danpat** [comment]
No, the code isn't written to load that file into a contiguous memory block.

However, you could move the file into a `tmpfs` or other ram disk volume and achieve the desired goal.  https://www.howtoforge.com/storing-files-directories-in-memory-with-tmpfs

**Comment by safe-bug** [comment]
Thanks very much @danpat
