### ISSUE TITLE
Can't compile example code

### ISSUE THREAD

**Issue by sws33** [Project-OSRM/osrm-backend#5949]
~/install/osrm-backend/example/build
$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building on a 64 bit system
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Found LibOSRM: /usr/local/lib  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/svs/install/osrm-backend/example/build

make VERBOSE=1 
/usr/bin/cmake -S/home/svs/install/osrm-backend/example -B/home/svs/install/osrm-backend/example/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/svs/install/osrm-backend/example/build/CMakeFiles /home/svs/install/osrm-backend/example/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: вход в каталог «/home/svs/install/osrm-backend/example/build»
make -f CMakeFiles/osrm-example.dir/build.make CMakeFiles/osrm-example.dir/depend
make[2]: вход в каталог «/home/svs/install/osrm-backend/example/build»
cd /home/svs/install/osrm-backend/example/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/svs/install/osrm-backend/example /home/svs/install/osrm-backend/example /home/svs/install/osrm-backend/example/build /home/svs/install/osrm-backend/example/build /home/svs/install/osrm-backend/example/build/CMakeFiles/osrm-example.dir/DependInfo.cmake --color=
make[2]: выход из каталога «/home/svs/install/osrm-backend/example/build»
make -f CMakeFiles/osrm-example.dir/build.make CMakeFiles/osrm-example.dir/build
make[2]: вход в каталог «/home/svs/install/osrm-backend/example/build»
[ 50%] Linking CXX executable osrm-example
/usr/bin/cmake -E cmake_link_script CMakeFiles/osrm-example.dir/link.txt --verbose=1
/usr/bin/c++   -std=c++14 -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/home/svs/install/osrm-backend/mason_packages/headers/boost/1.65.1/include -I/home/svs/install/osrm-backend/mason_packages/linux-x86_64/expat/2.2.0/include -I/home/svs/install/osrm-backend/mason_packages/linux-x86_64/lua/5.2.4/include -I/home/svs/install/osrm-backend/mason_packages/linux-x86_64/bzip2/1.0.6/include -I/home/svs/install/osrm-backend/mason_packages/linux-x86_64/tbb/2017_U7/include -I/usr/local/include -I/usr/local/include/osrm -O3 -DNDEBUG  -rdynamic CMakeFiles/osrm-example.dir/example.cpp.o  -o osrm-example -L/usr/local/lib -losrm -fuse-ld=gold -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -L/usr/local/lib -L/home/svs/install/osrm-backend/mason_packages/linux-x86_64/tbb/2017_U7/lib -losrm -fuse-ld=gold -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common /home/svs/install/osrm-backend/mason_packages/linux-x86_64/boost_libregex/1.65.1/lib/libboost_regex.a /home/svs/install/osrm-backend/mason_packages/linux-x86_64/boost_libdate_time/1.65.1/lib/libboost_date_time.a /home/svs/install/osrm-backend/mason_packages/linux-x86_64/boost_libfilesystem/1.65.1/lib/libboost_filesystem.a /home/svs/install/osrm-backend/mason_packages/linux-x86_64/boost_libiostreams/1.65.1/lib/libboost_iostreams.a /home/svs/install/osrm-backend/mason_packages/linux-x86_64/boost_libthread/1.65.1/lib/libboost_thread.a /home/svs/install/osrm-backend/mason_packages/linux-x86_64/boost_libsystem/1.65.1/lib/libboost_system.a -lpthread -ltbb -lrt -lz 
CMakeFiles/osrm-example.dir/example.cpp.o:example.cpp:function main: error: undefined reference to 'osrm::OSRM::Route(osrm::engine::api::RouteParameters const&, mapbox::util::variant<osrm::util::json::Object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, flatbuffers::FlatBufferBuilder>&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/osrm-example.dir/build.make:91: osrm-example] Error 1
make[2]: выход из каталога «/home/svs/install/osrm-backend/example/build»
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/osrm-example.dir/all] Error 2
make[1]: выход из каталога «/home/svs/install/osrm-backend/example/build»
make: *** [Makefile:84: all] Error 2

**Comment by mjjbell** [comment]
Hello, can you provide the output of the following command?

`pkg-config --modversion libosrm`

**Comment by sws33** [comment]
> pkg-config --modversion libosrm
5.24.0

**Comment by ExpliuM** [comment]
I'm getting the same issue, any ideas?

**Comment by SiarheiFedartsou** [comment]
Stale.
