### ISSUE TITLE
results from demo server front end differ from API request

### ISSUE THREAD

**Issue by vinnytwice** [Project-OSRM/osrm-backend#5950]
HI, I'm getting into building an OSRM server and I set up a bike route on the demo server 
http://map.project-osrm.org/?z=17&center=44.501839%2C11.340401&loc=44.501839%2C11.341270&loc=44.501770%2C11.340219&loc=44.500255%2C11.338867&loc=44.500217%2C11.337966&loc=44.501143%2C11.335863&hl=en&alt=0&srv=1

![Screen Shot 2021-02-01 at 20 54 29](https://user-images.githubusercontent.com/32189706/106521763-076cfd80-64df-11eb-86f0-cd6926709439.png)

 but when I make a request from my app I get completely different results.
 The green dotted polyline is the returned route from the api while the red polyline is the 5 coordinates I send with the request 
 'http://router.project-osrm.org/route/v1/bike/11.341211,44.501862;11.340225,44.501862;11.340225,44.501862;11.338931,44.500278;11.337891,44.500209;11.335789,44.501173?overview=false&geometries=geojson&steps=true&annotations=false'
  
![145906771_759508324986860_1883622757152765959_n](https://user-images.githubusercontent.com/32189706/106524683-36856e00-64e3-11eb-83b1-04b74b9f9091.png)

so I tried making multiple requests sending just 2 waypoints per request and rebuilding the route but still is not the same result as from the demo server front end...
 
 
![144722634_717248035848826_7578611594028690388_n](https://user-images.githubusercontent.com/32189706/106521700-ec9a8900-64de-11eb-826c-4ea2218d34bf.png)

What are those differences due to? I need the API to return a route like the 1st picture from this set of coordinates when requesting a route. I'm getting the coordinates from the 'coordinates' parameter in routes/legs/steps/geometry/coordinates and building the poly line myself.. Am I getting the wrong set of coordinates??
Thank you from the help

**Comment by danpat** [comment]
The coordinates you're supplying are not the same, so you'll get different routes:

```
Coordinates in the map.project-osrm.org link:
11.341270,44.501839
11.340219,44.501770
11.338867,44.500255
11.337966,44.500217
11.335863,44.501143

Coordinates in the router.project-osrm.org link:
11.341211,44.501862
11.340225,44.501862
11.340225,44.501862
11.338931,44.500278
11.337891,44.500209
11.335789,44.501173
```

Most of them differ by up to ~ 0.00005 degrees (5m) - this could easily lead to snapping them to different roads, forcing a different route.

**Comment by vinnytwice** [comment]
Oh you're right, I'lll try with the exact same coords.... but if this little varuation in coords is enough to scramble the route engine then it's pretty useless .. 
I will also try the matching engine to see if it held better results..
Thanks

**Comment by danpat** [comment]
The router picks the closest road to the points you request - if your coordinates are closer to back alleys, who's to say that's not where you actually want to go?  You need to supply enough precision in your input to get the output you desire.

**Comment by vinnytwice** [comment]
Sure, should I provide some more parameters in the query? I'm just starting with osmr and I'm trying to compensate for the poor gps tracking snapping the tracked route (red polyline) to a street/path  .
I see that there are parameters like weights or same curb that might just fine tune the response. Any hint will be very much welcomed. Thank you very much for the help.

**Comment by danpat** [comment]
Ah, if your points are coming from a noisy GPS trace and you want to reconstruct the most likely path, then you should be using the `/match` service, not `/route`.

The `/match` service calculates many routes from all possibilities nearby each coordinate, then selects the overall path that is the best match.  Results will depend a bit on the quality of your input - there's only so much magic the algorithms can do.

**Comment by vinnytwice** [comment]
Indeed the matching was my first try but didn't work out.  I see that (Android in this case) track gps signals with an hirizontal accuracy of 65% ( basically a 65 meters radius in which the true locatiin is), is there a way to pass this to the api to help the algorytm?

**Comment by danpat** [comment]
Have you looked at the API documentation at http://project-osrm.org/docs/v5.23.0/api/#match-service ?

**Comment by vinnytwice** [comment]
Great so indeed the accuracy can be passed in options.
on thing dough .. should I pass in just one accuracy or one per coordinate? 

http://router.project-osrm.org/match/v1/bike/11.341211,44.501862;11.340225,44.501862;11.340225,44.501862;11.338931,44.500278;11.337891,44.500209;11.335789,44.501173?overview=false&geometries=geojson&steps=true&annotations=false&radius=65

or 

http://router.project-osrm.org/match/v1/bike/11.341211,44.501862;11.340225,44.501862;11.340225,44.501862;11.338931,44.500278;11.337891,44.500209;11.335789,44.501173?overview=false&geometries=geojson&steps=true&annotations=false&radius=65&radius=65&radius=65&radius=65&radius=65

?
Many thanks again..

**Comment by vinnytwice** [comment]
@danpat here I am after a few tests but results are always the same as in 2nd pic..
as you correctly pointed out I was using a different set of coordinates so I did try using the same as for the from end ( 1st pc) with a request as :
```
'http://router.project-osrm.org/match/v1/bike/11.341270,44.501839;11.340219,44.501770;11.338867,44.500255;11.337966,44.500217;11.335863,44.501143?overview=false&geometries=geojson&steps=true&annotations=false'
```
or 
```
'http://router.project-osrm.org/match/v1/bike/11.341270,44.501839;11.340219,44.501770;11.338867,44.500255;11.337966,44.500217;11.335863,44.501143?overview=false&geometries=geojson&steps=true&annotations=false&radiuses=65;65;65;65;65'
```
but result didn't match front end result..

I then tried my different set of coordinates passing in also radiuses as:
```
'http://router.project-osrm.org/match/v1/bike/11.341211,44.501862;11.340225,44.501862;11.340225,44.501862;11.338931,44.500278;11.337891,44.500209;11.335789,44.501173?overview=false&geometries=geojson&steps=true&annotations=false&radiuses=65;65;65;65;65;65'
```
but al tests return the same ret of coordinates as in 2nd pic.

Any idea of what I'm doing wrong with my http request??
Thank you so much

**Comment by danpat** [comment]
Ah, now I see the problem.  The host `router.project-osrm.org` doesn't directly support the bike profile.

If you use a browser debugger and look at the URL requests being made by the OSRM UI, you'll see they look like this:

https://routing.openstreetmap.de/routed-bike/route/v1/driving/11.341291666030884,44.501835266715496;11.340219,44.50177;11.338867,44.500255;11.337966,44.500217;11.335863,44.501143?overview=full&alternatives=true&steps=false

It's a little confusing, but `https://routing.openstreetmap.de/routed-bike/route/v1/driving` is the URL prefix for returning a bike route.  I think the setup here is not quite complete (I don't run the demoserver any more).  The `router.project-osrm.org` server only supports car routing (i.e. no routes on bike-only paths), regardless of the `<profile>` part of the URL.

@datendelphin What are your thoughts on configuring your reverse proxy to return a 404 when the URL profile doesn't match the backend being selected, to avoid this kind of confusion?

**Comment by vinnytwice** [comment]
@danpat Got it.. that's why it always returns the same path from http requests no matter what profile I chose lol.. finally a little light at the end of the tunnel :) so I suppose that it will work properly once I deploy my own server..
>https://routing.openstreetmap.de/routed-bike/route/v1/driving is the URL prefix for returning a bike route

So this means that your server is using a proxy? (noob question I know but I am very noob in al this routing subject and still have to wrap my head around basic concepts I guess lol..)
I actually tried using car profile it held better results from the same set of coordinates ( different from the above ones )
Thanks for helping out.

**Comment by datendelphin** [comment]
reverse proxying? Yes it does. It also dispatches between the geographic regions.
@danpat I never quite understood the driving part of the url. One osrm server only delivers one profile. So would I be supposed to somehow alter the driving to something else for bike and foot?

**Comment by danpat** [comment]
@datendelphin It was put in as a placeholder for the future when OSRM supported loading multiple datafiles - that way, the interface wouldn't need to change.

In practical use, if you have a reverse proxy in place, the intent was you'd setup a mapping from a URL path to a backend like in this comment:

https://github.com/Project-OSRM/osrm-backend/issues/4517#issuecomment-330359238

**Comment by datendelphin** [comment]
How does osrm get the message that it needs to listen to walking instead of driving? Also, that example would exclude the debug tiles :) that was my motivation in the first place for prefixing it, so all "services" get forwarded and I don't need to care about api changes

**Comment by jesusdanielportillo** [comment]
@vinnytwice you must call the api with the query parameter overview=full in order to get the correct geometry to plot on your map.

So with the link your provided on first comment, if we change overview to full
http://router.project-osrm.org/route/v1/bike/11.341211,44.501862;11.340225,44.501862;11.340225,44.501862;11.338931,44.500278;11.337891,44.500209;11.335789,44.501173?**overview=full**&geometries=geojson&steps=true&annotations=false

you will get this on geometry field of route:
![image](https://user-images.githubusercontent.com/16390774/115636246-dfbe5200-a2e3-11eb-8efe-20018fa8e7c2.png)

**Comment by vinnytwice** [comment]
@jesusdanielportillo thanks for the info, the returned route is wrong anyways.  At the roundabout you see a full round where it should just take the first exit.. also in the middle there is a  little extra branch ..
