### ISSUE TITLE
Any suggestion on developing routing function for semi-tractor-trailer trucks with different dimensions?

### ISSUE THREAD

**Issue by JetBelson** [Project-OSRM/osrm-backend#5951]
Hi, OSRM teams. 

It is not an issue, but an inquiry from a beginner.

I am doing a project that needs to plan routes for semi-tractor-trailer trucks with different dimensions at a city level.

For now, I have adopted some motion planning methods to develop an "index" that can assess whether a truck with specific dimensions can go through a turn with a certain degree of performance.

 For example, when a truck with a length of 10.0m and a width of 2.5m go through a specific turn, it will have an index of 1.0; when a truck with a length of 12.0m and a width of 2.5m go through the same turn, it will have an index of 0.8. I have the road geometry data to calculate the "index" for each turn.

I would like to add this "index" to the turns so that a routine engine can use this information for routing. 

I am considering using OSM and OSRM to realize this purpose. 
After checking the documentation of OpenStreetMap and OSRM, my initial thoughts are:

1. Customized OSM data by adding the "index table" to turns by using the features *:conditioal=(value)@ (condition), e.g _restriction:conditional = 2.5 @(length=10.0 and width=2.5)_  
2. Customized the turn penalty by configuring the _process_node/process_way/process_turn_ to extract the index and then apply it to the turn penalty.

I really need to know whether the function I need can be developed by the current OSM and OSRM. Otherwise, I may need to look for another routine engine. Any suggestions on my designed function and initial thoughts. 

Thank you!

**Comment by frodrigo** [comment]
look at this
https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/21/truck-soft
and this
https://github.com/Project-OSRM/osrm-profiles-contrib/issues/11

**Comment by danpat** [comment]
This is doable, but note that you'll need to create a separate routing dataset for every truck configuration you support - OSRM can't customize the height/turn cost at query time.

**Comment by JetBelson** [comment]
> look at this
> https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/21/truck-soft
> and this
> [Project-OSRM/osrm-profiles-contrib#11](https://github.com/Project-OSRM/osrm-profiles-contrib/issues/11)

These links really helped a lot.

**Comment by JetBelson** [comment]
> This is doable, but note that you'll need to create a separate routing dataset for every truck configuration you support - OSRM can't customize the height/turn cost at query time.

Very useful reminders. Thank you!
