### ISSUE TITLE
car profile - penalty for bicycle_road=yes

### ISSUE THREAD

**Issue by flohoff** [Project-OSRM/osrm-backend#5952]
Hi,
on roads with bicycle_road=yes the Bicycles have priority on the road. So one might assume that the average travel speed may be significantly reduced. Probably this should also be considered a travel speed penalty as "single lane" roads, side roads etc.

Flo

**Comment by frodrigo** [comment]
Not sure about this. It is German only tag.
https://wiki.openstreetmap.org/wiki/Key:bicycle_road

According to taginfo it is used in combination with maxspeed.
https://taginfo.openstreetmap.org/keys/?key=bicycle_road#combinations

**Comment by flohoff** [comment]
The point is that the maxspeed is "Moot" when a bicycle is in front of you - It has priority and suddenly you are at walking speed ;) 

And yes it seems Belgium/Netherlands use "cyclestreet=" which is IMHO the same for a routing engine. You dont want to avoid those roads "at all cost" but they are more "expensive" time wise when using them.

And the Dutch/Belgium version is even more strict. You are not allowed to overtake a cyclist. Thats legal in the German version.

Flo

**Comment by SiarheiFedartsou** [comment]
Stale.
