### ISSUE TITLE
Web GUI: Replace Dropdown for car, bike, foot selection with three icons

### ISSUE THREAD

**Issue by foss-** [Project-OSRM/osrm-backend#5954]
**Currently**
The dropdown is difficult to handle and requires several clicks.
<img width="455" alt="dropdown" src="https://user-images.githubusercontent.com/5708172/106912062-f4d30e00-6702-11eb-8728-761db0bb7ef1.png">

**Expected**
Offering a bike, car and foot icon and display all three icons instead of the dropdown would make for much easier and quicker handling. Keeping the blue background in combination with white icons should provide good visibility.

**Comment by frodrigo** [comment]
Please report it to https://github.com/Project-OSRM/osrm-frontend

**Comment by foss-** [comment]
Of course: https://github.com/Project-OSRM/osrm-frontend/issues/335
