### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by ZhaoFan7** [Project-OSRM/osrm-backend#5955]
When I deployed OSRM using the same command on both machines( osrm-routed --algorithm=MLD  --threads 12  --max-matching-size 500 --max-table-size 1000 ../../data/china-latest.osrm),two machine has about the same amount of memory left,but the amount of time used varies greatly. 
http://192.168.8.106:5000/match/v1/driving/113.30168,23.066218;113.2998,23.066784;113.29768,23.067016;113.29552,23.0672;113.293384,23.06745;113.292448,23.06885;113.291968,23.070784;113.290536,23.07225;113.289144,23.073734;113.287768,23.075216;113.286368,23.076732;113.285288,23.0783;113.284864,23.080134;113.284784,23.082118;113.284448,23.084034;113.283288,23.085716;113.282048,23.087284;113.281648,23.089234;113.28104,23.09115;113.280232,23.092866;113.279448,23.09465;113.278688,23.096518;113.278128,23.098382;113.278112,23.1004;113.27724,23.101566;113.27528,23.1028;113.272432,23.10355;113.270216,23.10445;113.268048,23.105566;113.266432,23.105432;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.2654,23.1069;113.265448,23.1064;113.266184,23.104766;113.267064,23.102784;113.267936,23.100968;113.268864,23.098984;113.268184,23.097518;113.267856,23.0974;113.267856,23.0974;113.267856,23.0974;113.267856,23.0974;113.267856,23.0974;113.267856,23.0974;113.267856,23.0974;113.267856,23.0974;113.268152,23.097434;113.268152,23.097434;113.268152,23.097434;113.268152,23.097434;113.268152,23.097434;113.267984,23.0974;113.267984,23.097434;113.267752,23.09735;113.267752,23.09735;113.267752,23.09735;113.267752,23.09735;113.267752,23.09735;113.2684,23.097766?steps=false&geometries=geojson&overview=full&annotations=true&gaps=ignore&tidy=true&radiuses=80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80;80

One is 40 seconds, the other is 4 seconds.

**Comment by danpat** [comment]
The amount of time should be roughly equal between two equal machines, *assuming* they have no other load on them, and they have sufficient RAM to hold your data in memory.

If you are using swap memory, then performance will be highly dependent on the speed of your disks.  Fixing that is out of scope for this repo, OSRM is not optimized for read-from-swap performance.

You will need to look at system usage during a slow request to figure out what is going on.  Is it a network timeout/delay?  Is it excessive swap usage?  Is it another application running on one of these servers starving OSRM for resources?  It could be any of these things.
