### ISSUE TITLE
Manoeuvre override doesn't work when  the area is big

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5956]
Hello

I've followed [this wiki page](https://github.com/Project-OSRM/osrm-backend/wiki/Manoeuvre-override-tag) for adding maneuver overrides and it works well when the area is small, but when the osm file area goes bigger it doesn't apply any in OSRM. What is the problem?

Thanks

**Comment by SiarheiFedartsou** [comment]
Stale.
