### ISSUE TITLE
Country Changed after using osrm API

### ISSUE THREAD

**Issue by br4v0** [Project-OSRM/osrm-backend#5958]
I am getting a completely weird behavior from OSRM API, I input lat,olng  from completely different country Northridge Milwaukee Wisconsin United States with lat long: 43.181051429863,-88.011372301749 but it outputs with completely different lat long 67.468316, -73.259864. I am not sure why that is happening. Can anyone guide me what i am doing wrong ??

All Coordinated are fetched from database. 
Here is the api with all lat longs : 
[http://router.project-osrm.org/route/v1/driving/43.207386034393,-88.003270954114;43.215019321109,-88.001117594622;43.214430515523,-88.001156636113;43.213724561956,-88.000458713313;43.215045198768,-88.001728886798;43.215045198768,-88.001728886798;43.215098946236,-88.001724668937;43.200451644886,-88.003815920838;43.198327100205,-88.003834085621;43.196226698622,-88.003859749376;43.194110382391,-88.003906142595;43.192119976834,-88.003919079844;43.190419497548,-88.00409637526;43.189166104689,-88.004283366426;43.187873356063,-88.004353068638;43.186508034843,-88.004376715359;43.185204852903,-88.004447880775;43.183543838021,-88.004480124351;43.182629143513,-88.005698167441;43.181999800227,-88.00581708599;43.181140359852,-88.006508834482;43.180279361327,-88.007850768459;43.180245503505,-88.009575702465;43.18026940936,-88.010390577811;43.180642009293,-88.010933011558;43.181186541424,-88.011011389875;43.180806465704,-88.011491535851;43.18057603097,-88.012067002464;43.181051429863,-88.011372301749?overview=false](url)

Please help,
Thanks.

**Comment by frodrigo** [comment]
Coords should by in order longitude,latitude.
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#osrm-http-server
