### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ChintalJain** [Project-OSRM/osrm-backend#5959]
I am using project-osrm for basic routing service.
Currently the server is not reachable.
I am not able to fetch any nearest/routing request now.
The server gives response like 500 Internal Server Error routing backend is not reachable.

**Comment by jcoupey** [comment]
Thanks for reporting, I guess you mean the demo server (https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server). Then this is related to the update process to the latest OSRM version, and people volunteering to maintain this demo are aware of the problem and investigating.

Please note that this server is well, just a demo. If you want some uptime guarantees or have a heavy use of the service, you should really run your own instance.
