### ISSUE TITLE
Travel durations without traffic data

### ISSUE THREAD

**Issue by Rougree** [Project-OSRM/osrm-backend#5961]
Hi guys,

I'm running osrm local (with docker) as follows:

```
docker run -t -v %cd%/data:/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/netherlands-latest.osm.pbf
docker run -t -v %cd%/data:/data osrm/osrm-backend osrm-partition /data/netherlands-latest.osrm
docker run -t -v %cd%/data:/data osrm/osrm-backend osrm-customize /data/netherlands-latest.osrm

|
|
V

docker run --rm -t -i -p 5000:5000 -v %cd%/data:/data osrm/osrm-backend osrm-routed --max-table-size=10000 --algorithm mld /data/netherlands-latest.osrm

```

The travel durations are free flow durations. How can I include traffic information to return more realistic travel durations?

**Comment by jcoupey** [comment]
OSRM can ingest traffic data if you have some at hand, please read the dedicated wiki page: https://github.com/Project-OSRM/osrm-backend/wiki/Traffic.

**Comment by Rougree** [comment]
If i'm running at http://project-osrm.org/ traffic data is included? Is there a simple solution to have these solutions?

**Comment by datendelphin** [comment]
no it does not and there is not

**Comment by Rougree** [comment]
Why is the travel duration significant higher while running at http://project-osrm.org/ ? @datendelphin

**Comment by Rougree** [comment]
apparently it does: #5728 @datendelphin

**Comment by danpat** [comment]
@Rougree That ticket is stale - @datendelphin is now running the demoserver, so I think he'd know.

The routing profiles being used by the demoserver can be found here: https://github.com/fossgis-routing-server/cbf-routing-profiles
