### ISSUE TITLE
[warn] Missing/Broken File: north-america-latest.osrm.datasource_names [error] Required files are missing, cannot continue

### ISSUE THREAD

**Issue by katherine-shiqi** [Project-OSRM/osrm-backend#5965]
I got this error when trying to run the osrm-routed for north-america

`ubuntu@ip-xxx:~/osrm-backend$ osrm-routed --algorithm=MLD north-america-latest.osrm
[warn] Missing/Broken File: north-america-latest.osrm.datasource_names
[error] Required files are missing, cannot continue`

Basically i ran

`osrm-extract north-america-latest.osm.pbf
osrm-partition north-america-latest.osrm
osrm-customize north-america-latest.osrmscot`

here is my log

`ubuntu@XXX:~/osrm-backend$ osrm-extract north-america-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script profiles/car.lua
[info] Input file: north-america-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 72
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2021-02-17T21:42:03Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 300.203 seconds
[info] Raw input contains 1351368758 nodes, 116186184 ways, and 101274 relations, 367685 restrictions
[info] Collecting way information on 367685 restrictions...ok, after 4.77543s
[info] Collecting way information on 37 maneuver overrides...ok, after 0.725842s
[info] Sorting used nodes        ... ok, after 2.62546s
[info] Erasing duplicate nodes   ... ok, after 0.81203s
[info] Sorting all nodes         ... ok, after 1.05981s
[info] Building node id map      ... ok, after 3.37509s
[info] Confirming/Writing used nodes     ... ok, after 15.4214s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 285237209 nodes
[info] Sorting edges by start    ... ok, after 17.2368s
[info] Setting start coords      ... ok, after 30.5284s
[info] Sorting edges by target   ... ok, after 9.6519s
[info] Computing edge weights    ... ok, after 54.2839s
[info] Sorting edges by renumbered start ... ok, after 10.2173s
[info] Writing used edges       ... ok, after 12.3205s -- Processed 301118229 edges
[info] Writing way meta-data     ... ok, after 0.302587s -- Metadata contains << 34306005 entries.
[info] Collecting node information on 37 maneuver overrides...ok, after 0.000367s
[info] Collecting node information on 367685 restrictions...ok, after 0.714518s
[info] writing street name index ... ok, after 0.25998s
[info] extraction finished after 470.496s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.20245
[info] Edge compression ratio: 0.243498
[info]  graph compression removed 31235525 annotations of 34306005 in 93.1005 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 198.202s
[info] Segregated edges count = 1205853
[info] Writing nodes for nodes-based and edges-based graphs ...
[info] Geometry successfully removed:
  compressed edges: 146447100
  compressed geometries: 601582558
  longest chain length: 5973
  cmpr ratio: 0.243436
  avg chain length: 4.10785
[info] Removing invalid restrictions...removed 3303 invalid restrictions, after 0.088073s
[info] Constructing restriction graph on 358801 restrictions...ok, after 0.134505s
[info] Generating edge expanded nodes ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 140409655 nodes (27710 of which are duplicates)  and 300714526 segments in edge-expanded graph
[info] Generating edge-expanded edges 
[info] [info] Using profile api version 4
[info] Using profile api version 4
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 12232895, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.235804&mlon=-73.282519
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 24894874, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.603473&mlon=-112.009529
 10% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 46022864, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.17513&mlon=-95.425205
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 55801433, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.815809&mlon=-75.794265
 20% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 57378360, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.726113&mlon=-104.388261
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 57608602, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.87256&mlon=-104.173822
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 58919548, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=34.925952&mlon=-98.098521
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 61321130, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=35.203096&mlon=-97.007773
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 61321130, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=35.203096&mlon=-97.007773
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 63704610, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=29.707854&mlon=-95.412599
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 65196683, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.613165&mlon=-80.593898
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 72032195, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=36.851942&mlon=-86.912602
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 74922755, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=35.669448&mlon=-79.219801
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 79403946, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.259168&mlon=-103.323219
 30% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 104069928, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.17285&mlon=-75.175466
 40% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 124427891, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.774176&mlon=-122.342751
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 130517018, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=46.149721&mlon=-66.944733
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 137092199, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=44.561922&mlon=-123.2724
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 138288285, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.376815&mlon=-61.855283
 50% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 150685634, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.884403&mlon=-87.621391
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 151529480, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.503392&mlon=-86.035354
. 60% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 174232946, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=29.748136&mlon=-94.846537
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 174232946, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=29.748136&mlon=-94.846537
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 174232946, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=29.748136&mlon=-94.846537
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 174830580, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.402342&mlon=-76.5681
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 174830580, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.402342&mlon=-76.5681
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 174830580, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.402342&mlon=-76.5681
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 177897777, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=44.876509&mlon=-91.92906
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 180775489, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=29.716627&mlon=-95.412699
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 195026214, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.062794&mlon=-122.918649
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 199520145, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.919453&mlon=-97.029392
 70% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 220672794, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=45.885885&mlon=-73.429043
 80% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 231046581, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.287009&mlon=-71.72894
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 236540207, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=26.620796&mlon=-81.862021
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 249169536, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=30.762764&mlon=-86.425417
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 249753196, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.177364&mlon=-122.298449
 90% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 257593388, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.75537&mlon=-71.175895
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 268063945, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.292986&mlon=-79.873371
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 268063945, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.292986&mlon=-79.873371
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 271614161, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.616127&mlon=-88.656905
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 271624869, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.620707&mlon=-88.646749
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 274542835, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.67042&mlon=-71.803949
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 280400066, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=42.504589&mlon=-72.799273
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 285236146, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=44.718477&mlon=-66.779005

[info] Sorting and writing 37 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 300714526 edge based node segments
[info] Node-based graph contains 137602451 edges
[info] Edge-expanded graph ...
[info]   contains 272206453 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 4.62773s
[info] Generating nodes: 68.9546s
[info] Generating edges: 261.061s
[info] Generating guidance turns 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .
[info] done.
[info] Created 265 entry classes and 93548 Bearing Classes
[info] Handled: 393638 of 757403 lanes: 51.9721 %.
[info] Assigned 313014798 turn instruction types:
[info]   new name: 6993652 (2.23%)
[info]   continue: 16558799 (5.29%)
[info]   turn: 125567848 (40.12%)
[info]   merge: 115041 (0.04%)
[info]   on ramp: 188649 (0.06%)
[info]   off ramp: 130388 (0.04%)
[info]   fork: 1495930 (0.48%)
[info]   end of road: 53911249 (17.22%)
[info]   notification: 1635 (0.00%)
[info]   enter roundabout: 65023 (0.02%)
[info]   enter and exit roundabout: 3684 (0.00%)
[info]   enter rotary: 2968 (0.00%)
[info]   enter and exit rotary: 224 (0.00%)
[info]   enter roundabout turn: 23070 (0.01%)
[info]   enter and exit roundabout turn: 27 (0.00%)
[info]   (noturn): 36159083 (11.55%)
[info]   (suppressed): 71386472 (22.81%)
[info]   roundabout: 3710 (0.00%)
[info]   exit roundabout: 78027 (0.02%)
[info]   rotary: 266 (0.00%)
[info]   exit rotary: 3564 (0.00%)
[info]   roundabout turn: 22 (0.00%)
[info]   exit roundabout turn: 23372 (0.01%)
[info]   (stay on roundabout): 99057 (0.03%)
[info]   (sliproad): 203038 (0.06%)
[info] Assigned 313014798 turn instruction modifiers:
[info]   uturn: 14299336 (4.57%)
[info]   sharp right: 4277523 (1.37%)
[info]   right: 87741421 (28.03%)
[info]   slight right: 6633388 (2.12%)
[info]   straight: 102626325 (32.79%)
[info]   slight left: 6475968 (2.07%)
[info]   left: 86333189 (27.58%)
[info]   sharp left: 4627648 (1.48%)
[info] Guidance turn annotations took 458.334s
[info] Writing Intersection Classification Data
[info] ok, after 1.79083s
[info] Writing Turns and Lane Data...
[info] ok, after 1.2786s
[info] Saving edge-based node weights to file.
[info] Done writing. (1.78272)
[info] Computing strictly connected components ...
[info] Found 104975 SCC (22 large, 104953 small)
[info] SCC run took: 15.1757s
[info] Building r-tree ...
[info] Constructing r-tree of 300714526 segments build on-top of 285237209 coordinates
[info] finished r-tree construction in 50.9715 seconds
[info] Writing edge-based-graph edges       ... 
[info] ok, after 13.934s
[info] Processed 272206453 edges
[info] Expansion: 150867 nodes/sec and 74265 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "north-america-latest.osrm"
[info] RAM: peak bytes used: 90764779520
ubuntu@XXX:~/osrm-backend$ osrm-partition north-america-latest.osrm
[info] Computing recursive bisection
[info] Loaded compressed node based graph: 146447058 edges, 285237209 nodes
[info]  running partition: 128 1.2 0.25 10 1000 # max_cell_size balance boundary cuts small_component_size
[info] Found 227547137 SCC (7 large, 227547130 small)
[info] SCC run took: 19.5985s
[info] Full bisection done in 1591.55s
[info] Loaded node based graph to edge based graph mapping
[info] Loaded edge based graph for mapping partition ids: 544305346 edges, 140409655 nodes
[info] Fixed 37849 unconnected nodes
[info] Edge-based-graph annotation:
[info]   level 1 #cells 684131 bit size 20
[info]   level 2 #cells 52393 bit size 16
[info]   level 3 #cells 3274 bit size 12
[info]   level 4 #cells 107 bit size 7
[info] Renumbered data in 497.767 seconds
[info] MultiLevelPartition constructed in 24.5942 seconds
[info] CellStorage constructed in 15.3006 seconds
[info] MLD data writing took 64.0855 seconds
[info] Cells statistics per level
[info] Level 1 #cells 684131 #boundary nodes 12978475, sources: avg. 12, destinations: avg. 18, entries: 229979773 (1839838184 bytes)
[info] Level 2 #cells 52393 #boundary nodes 2279432, sources: avg. 29, destinations: avg. 40, entries: 87039778 (696318224 bytes)
[info] Level 3 #cells 3274 #boundary nodes 349458, sources: avg. 72, destinations: avg. 97, entries: 32074888 (256599104 bytes)
[info] Level 4 #cells 107 #boundary nodes 33745, sources: avg. 216, destinations: avg. 278, entries: 9729905 (77839240 bytes)
[info] Bisection took 2452.75 seconds.
[info] RAM: peak bytes used: 62536785920
ubuntu@ip-xxx:~/osrm-backend$ osrm-customize north-america-latest.osrmscot
[warn] Missing/Broken File: north-america-latestscot.osrm.ebg
[warn] Missing/Broken File: north-america-latestscot.osrm.partition
[warn] Missing/Broken File: north-america-latestscot.osrm.cells
[warn] Missing/Broken File: north-america-latestscot.osrm.ebg_nodes
[warn] Missing/Broken File: north-america-latestscot.osrm.properties
[warn] Missing/Broken File: north-america-latestscot.osrm.enw`

**Comment by frodrigo** [comment]
First you process `north-america-latest.osm.pbf` then try on `north-america-latest.osrmscot`
You did not process the right file.

```
osrm-extract north-america-latest.osm.pbf
osrm-customize north-america-latest.osrmscot
```

**Comment by katherine-shiqi** [comment]
Hi team, that's exactly what i did! Can you inform me what i did wrong?

osrm-extract north-america-latest.osm.pbf <br>
osrm-partition north-america-latest.osrm <br>
osrm-customize north-america-latest.osrmscot <br>

**Comment by katherine-shiqi** [comment]
are you saying i shouldn't do the osrm-partition north-america-latest.osrm?

**Comment by frodrigo** [comment]
No, remove the `scot` and the end.

**Comment by katherine-shiqi** [comment]
thank you. just to confirm. you are saying I should do this:

`osrm-extract north-america-latest.osm.pbf <br>

osrm-partition north-america-latest.osrm <br>

osrm-customize north-america-latest.osrm`

**Comment by frodrigo** [comment]
yes, as the readme say https://github.com/Project-OSRM/osrm-backend#using-docker

**Comment by katherine-shiqi** [comment]
thank you. it was resolved!! appreciate a ton!
