### ISSUE TITLE
Inconsistent routes when snapping endpoints to same way, with traffic updates

### ISSUE THREAD

**Issue by mjjbell** [Project-OSRM/osrm-backend#5969]
Documenting a quirk I found when writing tests for #5953. It touches on some OSRM implementation details which might be relevant in other scenarios.

## Issue 
Given a way and traffic updates that invalidate a segment of the way, routes between two endpoints snapped to this way are inconsistent.

N.B. This only affects the contraction hierarchy algorithm.

The problem can be summarised in this test feature:
```
Feature:

    Background: single way
        Given the node map
            """
            a   b   c   d
            """

        And the ways
            | nodes   |
            | abcd    |

        And the profile "turnbot"

    Scenario: invalid segment, fail to find route
        Given the contract extra arguments "--segment-speed-file {speeds_file}"
        And the customize extra arguments "--segment-speed-file {speeds_file}"
        And the speed file
        """
        3,4,0
        """

        When I route I should get
            | from | to | route      | weight |
            | b    | a  | abcd,abcd  | 20     |

        When I route I should get
            | from | to | code      |
            | a    | b  | NoRoute   |


    Scenario: invalid segment finds u-turn route
        Given the contract extra arguments "--segment-speed-file {speeds_file}"
        And the customize extra arguments "--segment-speed-file {speeds_file}"
        And the speed file
        """
        2,1,0
        """

        When I route I should get
            | from | to | route       | weight |
            | c    | d  | abcd,abcd   | 20     |
            | d    | c  | abcd,abcd   | 40     |

```
In an ideal scenario, all four queries would be routable. Furthermore, for the symmetric scenarios `from a to b` and `from d to c`, only one is routable, and the latter is only finds a path via a u-turn (see the additional weight).

### Input Snapping

A way can consist of multiple segments. Traffic updates can change the edge weights/speeds for individual segments. Segments can also be invalidated, indicating that it can not be used in a route.
![image](https://user-images.githubusercontent.com/1063186/108780211-fbb1ab80-755f-11eb-8748-ebd71ed7ee0e.png)

Input locations are snapped to a position along a way, i.e. a position on one of the segments.
The current behaviour for snapping locations to ways with invalid segments is as follows:

**Targets**: The snapped location is a valid target, as long as all segments before the snapped position are valid.

**Sources**: The snapped location is invalid if any of the segments are invalid, regardless of their relative position to the snapped location.
![image](https://user-images.githubusercontent.com/1063186/108780466-64008d00-7560-11eb-92b9-b534c56ec37e.png)

This asymmetry is due to the way in which route weights are calculated. Without going into the details, all segment weights of the first way are used in the search, so they all must be valid.

#### Scenario 1
Take the first scenario from the test feature. Here we invalidate segment `c->d`
The transformation from original graph to edge-based contraction hierarchy graph is as follows:

![image](https://user-images.githubusercontent.com/1063186/108781696-3288c100-7562-11eb-9efc-7a25b6a6ce4e.png)

It's worth noting the graph is so trivial that none of the contraction hierarchy ranking criteria apply, so the order between the two nodes is randomly selected. This is deterministic, so we always have `rank(reverse(abcd)) > rank(forward(abcd))`.

Applying the route search...

#### from b to a
- We can't snap a source to the forward way as it contains an invalid segment.
- Both the source and target snap to the reverse way with a positive weight path between them.
- ROUTE FOUND

![image](https://user-images.githubusercontent.com/1063186/108782995-83011e00-7564-11eb-865f-1d8987b1b461.png)

#### from a to b
- Again, we can't snap a source to the forward way. 
- Both the source and target snap to the reverse way, but the path between has negative weight.
- The graph edge from the forward way is not traversable, as the reverse way already exists in the backward heap with a smaller weight.
- NO ROUTE FOUND

![image](https://user-images.githubusercontent.com/1063186/108783050-a0ce8300-7564-11eb-9d26-75ba2a84a140.png)

#### Scenario 2
Take the second scenario from the test feature. Here we invalidate segment `b->a`
The transformation from original graph to edge-based contraction hierarchy graph is as follows:

![image](https://user-images.githubusercontent.com/1063186/108784286-f6a42a80-7566-11eb-935f-fd88d631b222.png)

Applying the route search...

#### from c to d
- We can't snap a source to the reverse way as it contains an invalid segment.
- Both the source and target snap to the forward way with a positive weight path between them.
- ROUTE FOUND

![image](https://user-images.githubusercontent.com/1063186/108785103-acbc4400-7568-11eb-92bd-7075ea9840ea.png)

#### from d to c
- Again, we can't snap a source to the reverse way. 
- Both the source and target snap to the forward way, but the path between has negative weight.
- We can traverse the graph edge representing the u-turn in the forward graph. From here we now have a match on the reverse way with a positive weight.
- ROUTE FOUND (with u-turn)

![image](https://user-images.githubusercontent.com/1063186/108785172-c9587c00-7568-11eb-83a9-b10e43f3c7c3.png)

## Summary

This issue has two characteristics.

- The asymmetry between target and source phantoms. Traffic updates to segments behind a source location can invalidate a route even if the path from the source to the first turn is valid.  Is there a way to alter the route weight calculation to accommodate this?

- Given the source/target asymmetry, the CH contraction order - and in this case the randomness of the rank selection - determines which routes are found. If the contraction node ranks are flipped, the no-route/u-turn results would also flip for the symmetric cases. I also noticed differences between results caused by CH contraction randomness in [another test](https://github.com/Project-OSRM/osrm-backend/pull/5953#issuecomment-782620999). Are there assumptions needed for CH to work that are not being adhered to in OSRM due to various real-life complexities (snapping, traffic updates, endpoints on same edge, etc)? Or are these test cases not representative of real-world graphs?

**Comment by felix-geovelo** [comment]
Hello ! 

I encouter the first problem (asymetry between source and target) since I invalidate some parts of some way of my graph with --segment-speed-file option (but I'm working with MLD here)
So, in particular situation, source might be snapped to a valid section of a way that contains invalid sections. This situation should be avoided at snapping time if valid section of a way that contains invalid section will never be a valid source

This problem lies in this part of the code I think : 
https://github.com/Project-OSRM/osrm-backend/blob/31e31a63d062fb804f5f4695ed3036ca7a269ead/include/engine/geospatial_query.hpp#L528-L539

When snapping, it only check if the selected section has valid edge weight but according to your post, source is not valid if one section in the same way is invalid, and target is not valid if previous section of the same way are invalid.

Then,  I propose the folliwing code to fix snapping logic and avoid snapping to _valid but invalid_ edge :

```
const auto forward_weights = datafacade.GetUncompressedForwardWeights(geometry_id);
if (std::find(forward_weights.begin(), forward_weights.end(), INVALID_SEGMENT_WEIGHT) ==
    forward_weights.end())
{
    forward_edge_valid = data.forward_segment_id.enabled;
}
const auto reverse_weights = datafacade.GetUncompressedReverseWeights(geometry_id);
if (std::find(reverse_weights.begin(), data.fwd_segment_position, INVALID_SEGMENT_WEIGHT) ==
    data.fwd_segment_position)
{
    reverse_edge_valid = data.reverse_segment_id.enabled;
}
```
