### ISSUE TITLE
Route ends in tunnel

### ISSUE THREAD

**Issue by Trollgeir** [Project-OSRM/osrm-backend#5971]
![image](https://user-images.githubusercontent.com/7591857/109390018-6d4a7a80-790f-11eb-8b3d-48ff79955864.png)

Here's a link to the actual route: 
http://map.project-osrm.org/?z=17&center=59.952040%2C10.754784&loc=59.953436%2C10.760776&loc=59.951792%2C10.745664&hl=en&alt=0&srv=0

Notice how moving it slightly will sometimes make the route snap to a route which isn't in the tunnel.

How can this be avoided?

**Comment by frodrigo** [comment]
Look at this
https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/18/does_not_starts_or_ends_in_the_midst_of_motorway_or_tunnel
