### ISSUE TITLE
osrm-extract does not create files required  by osrm-contract

### ISSUE THREAD

**Issue by dminaev** [Project-OSRM/osrm-backend#5972]
Hello,
I use dockerized osrm-backend to process planet-latest.osm.pbf downloaded from https://planet.openstreetmap.org/pbf/. First, I run:
`sudo docker run --rm -v /mnt/osrm:/osrm-data -v /tmp:/tmp -v /home/admin/car.lua:/opt/car.lua osrm/osrm-backend:v5.24.0 osrm-extract -p /opt/car.lua /osrm-data/planet-latest.osm.pbf"`

No errors are reported during this phase and the last lines produced by osrm-extract are:
```
Mar 02 12:08:33 [info] Computing strictly connected components ...
Mar 02 12:11:24 [info] Found 813428 SCC (259 large, 813169 small)
Mar 02 12:11:24 [info] SCC run took: 64.3064s
Mar 02 12:11:30 [info] Building r-tree ...
Mar 02 12:11:30 [info] Constructing r-tree of 1243195679 segments build on-top of 1186230775 coordinates
```

During this step, the following files are created:
```
planet-latest.osm.pbf           planet-latest.osrm.enw                 planet-latest.osrm.names         planet-latest.osrm.tld
planet-latest.osrm              planet-latest.osrm.fileIndex           planet-latest.osrm.nbg_nodes     planet-latest.osrm.tls
planet-latest.osrm.cnbg         planet-latest.osrm.geometry            planet-latest.osrm.properties    planet-latest.osrm.turn_duration_penalties
planet-latest.osrm.cnbg_to_ebg  planet-latest.osrm.icd                 planet-latest.osrm.restrictions  planet-latest.osrm.turn_penalties_index
planet-latest.osrm.edges        planet-latest.osrm.maneuver_overrides  planet-latest.osrm.timestamp     planet-latest.osrm.turn_weight_penalties
```
So, during the contraction step, I get this:
```
sudo docker run --rm -v /opt/osrm-data:/osrm-data -v /tmp:/tmp osrm/osrm-backend:v5.24.0 osrm-contract /osrm-data/planet-latest.osrm
[warn] Missing/Broken File: /osrm-data/planet-latest.osrm.ebg
[warn] Missing/Broken File: /osrm-data/planet-latest.osrm.ebg_nodes
```

Am I missing something?

**Comment by frodrigo** [comment]
https://github.com/Project-OSRM/osrm-backend#quick-start

By default it builds MLD, `contract` is for CH.
Use `osrm-partition` and `osrm-customize` for MLD.

**Comment by dminaev** [comment]
No, CH is what I want to get. The documentation doesn't mention any CH-specific options for osrm-extract and I thought that the first stage is the same for both algorithms.

**Comment by frodrigo** [comment]
> No, CH is what I want to get. The documentation doesn't mention any CH-specific options for osrm-extract and I thought that the first stage is the same for both algorithms.

You right.

Have you checked for free disk space? Or OSMR killed by the kernel for lake of memory?

**Comment by dminaev** [comment]
When I tried to run it in AWS on a x1e.xlarge machine with 244 GB RAM, extraction failed with memory allocation errors. Then I switched to r5a.12xlarge (384GB) and osrm-extract finally finished without errors (or so it seemed). I didn't check the logs for OOM errors, but the second hypothesis looks more feasible. I will have to double-check the disk space. Thanks for the idea

**Comment by jcoupey** [comment]
The `osrm-extract` output you provide does look truncated. This is the structure I get on a sample extract process as of the SCC part:

```
[...]
[info] Computing strictly connected components ...
[info] Found 1162 SCC (1 large, 1161 small)
[info] SCC run took: 0.0234607s
[info] Building r-tree ...
[info] Constructing r-tree of 1202890 segments build on-top of 1163448 coordinates
[info] finished r-tree construction in 0.207762 seconds
[info] Writing edge-based-graph edges       ... 
[info] ok, after 0.038024s
[info] Processed 792600 edges
[info] Expansion: 138715 nodes/sec and 52304 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "franche-comte-210301.osrm"
[info] RAM: peak bytes used: 650264576
```

The indication on RAM peak usage is the last info you should get in output.

A frequent cause of errors for Docker users is that although you seem to have plenty of resources at hand, the dockerized process may not be allowed to use all of it.

**Comment by dminaev** [comment]
Thank you. Sorry for bothering.
