### ISSUE TITLE
Compiling issue with Fedora 33 / Lua 5.4 / Sol2

### ISSUE THREAD

**Issue by giocomai** [Project-OSRM/osrm-backend#5973]
I could install flawlessly OSRM on previous versions of Fedora based on the details at the bottom of the [relevant wiki page](https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM). However, this does not seem to work on Fedora 33, apparently in relation to the fact that Fedora 33 comes with Lua 5.4.

An early error when running `cmake ..` can be overcome by including reference to Lua 5.4:

 `cmake .. -DLUA_INCLUDE_DIR="/usr/include/lua5.4"`

Running `make` then leads to this error: 

`error: ‘luaopen_bit32’ was not declared in this scope; did you mean ‘luaopen_math’?`

which can be solved as suggested in [this sol2 issue](https://github.com/ThePhD/sol2/issues/1086#issuecomment-742726566), i.e. adding the following close to the bottom of `/usr/include/luaconf-x86_64.h`

```
#undef LUA_COMPAT_5_1
#undef LUA_COMPAT_5_2
```

Things with `make` go a bit further, but not yet to the finish line, as it results in the following error:

```
error: undefined reference to 'lua_newuserdatauv'
```

I see this specific error has been dealt with in [other projects](https://github.com/glankk/n64/issues/12) based on Lua, but I have not been able to apply that wisdom to get past this point. 

I've seen  other OSRM issues related to Lua 5.4 and Sol2 have been opened, but I still decided to report this, to report some of my own troubleshooting, and  share details on unsuccessful compiling on the latest Fedora. As a solution to this emerges, I'll gladly add relevant information to the wiki.

**Comment by SiarheiFedartsou** [comment]
Shouldn’t be relevant anymore, but fell free to reopen.

**Comment by giocomai** [comment]
Right. To be clear, it doesn't build on the latest Fedora 36 following instructions on the Wiki, but it's a bunch of different issues.
