### ISSUE TITLE
[error] Input file /data/berlin-latest.osm.pbf not found!

### ISSUE THREAD

**Issue by Ivar9928** [Project-OSRM/osrm-backend#5975]
Hi all, 

I am trying to set up OSRM using Docker as shown here : https://hub.docker.com/r/osrm/osrm-backend/.
I downloaded the file using the following command: wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf

First I had to install the "wget" package for usage. 

Now i am stuck with the second command: docker run -t -v "/${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf
It gives the error:  Input file /data/berlin-latest.osm.pbf not found!

I am working with windows, I have read that I don't have to share my :C folder since this is automatically done. 
Someone said that the OSM file path must be in a docker image file system, but how?

I am trying to redo the following example: https://rpubs.com/mgei/drivingtimes.

Can someone help and explain to me what i'm doing wrong?

**Comment by jcoupey** [comment]
This is really Docker-related, see #5109 for a similar issue.

**Comment by Ivar9928** [comment]
Fixed it, used https://gist.github.com/AlexandraKapp/e0eee2beacc93e765113aff43ec77789
