### ISSUE TITLE
Cmake: Could NOT find LibOSRM Library Dirs (Windows 10)

### ISSUE THREAD

**Issue by L-Roth** [Project-OSRM/osrm-backend#5976]
Hi, thanks for the great projekt.
I successfully used the http api on Windows 10 with the pre-built Release.
But now I want to use osrm as a C++ library, but dont know how to include Lib-osrm.

When I built the given example directory at `osrm-backend/example` with `cmake -S. -B /out/Build/` i get the following error:

`-- Building on a 64 bit system
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibOSRM (missing: LibOSRM_LIBRARY_DIRS LibOSRM_CXXFLAGS
  LibOSRM_LIBRARIES LibOSRM_DEPENDENT_LIBRARIES LibOSRM_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibOSRM.cmake:58 (find_package_handle_standard_args)
  CMakeLists.txt:32 (find_package)`

**Where** should the LibOsrm directory be, to be found by cmake?
**What** should be in there?
I didnt found any static or dynamic library files for libOsrm.

Note: When I run `build-local.bat` no archive called `osrm_Release.zip` is generatet (as stated in the Windows Wiki). Maybe thats a part of the problem.

**Comment by mjjbell** [comment]
If the build is successful there should be a static library file `build\Release\osrm.lib` or `build\Debug\osrm.lib`.

I did a few bug fixes for Windows recently and also noticed the cmake build would not work for the example.  I expect some changes are required to `example/CMakeLists.txt` to support Windows.

Looking through the shell history, this is the command I ended up with to build the example. I'm not a Windows dev, so no doubt there's a better way.
```
cl /EHsc /MD /I \Users\mbell\osrm-backend\include /I
\Users\mbell\osrm-backend\osrm-deps\include /I
\Users\mbell\osrm-backend\third_party\variant\include /I
\Users\mbell\osrm-backend\third_party\flatbuffers\include example.cpp
\Users\mbell\osrm-backend\build\Release\osrm.lib /link
/LIBPATH:"\Users\mbell\osrm-backend\osrm-deps\lib"
```

**Comment by L-Roth** [comment]
Thanks!
Building with CL worked for me.
