### ISSUE TITLE
Retrieve timestamp and license plate information in returned map match response

### ISSUE THREAD

**Issue by robbertwynn** [Project-OSRM/osrm-backend#5977]
I have a GPS dataset of vehicles that besides `latitude` and `longitude` coordinates, also contains information about the `timestamp` (e.g. '2020-03-04 10:39:13') and the `license plate` of the vehicle. I have been able to successfully map match these GPS points using OSRM. However, I was wondering whether it is also possible to get information about which vehicle (based on the license plate information) and at what time (based on the timestamp) it drove through street X? All this information seems to be lost in the map match response

**Comment by danpat** [comment]
@robbertwynn OSRM has no interest in arbitrary metadata like that - you need to track which GPS data is linked to which license plate in your client-side code.

**Comment by robbertwynn** [comment]
Ok, and map matched time information won't be possible to retrieve at all?
