### ISSUE TITLE
Local server suddenly stops with large number of requests

### ISSUE THREAD

**Issue by thuzax** [Project-OSRM/osrm-backend#5978]
I am new with osrm and I am running osrm-backend (v5.24.0) as a mini-local server. I have a Python  script which makes a large number of "/route" requests. I need to calculate more than 10000 one-to-one route (I think using the "/table" option would make it calculate a lot of unnecessary routes, since it would calculate from all sources to all destinations, and all points are a source at least once).

During the requests the server stops without returning any value (I also tried making new requests using the a web browser). Before it stops all routes are calculated instantly. I thought it could be calculating the route, so I forcefully stopped the server and restarted it. After making the same request (using the browser) I received an instantly reply containing the calculated route.

After this I retried to reproduce the error, and the server stopped in a different request. I tried making the last request through my smartphone (to verify whether my PC IP was blocked due to the number of requests). The result was the same: no response. After restarting the server I tried to make the request again on the cellphone and got the response.

I am running the server in a Intel I7 - 7th gen and 8GB of RAM. The OS is Ubuntu 18.04.

Is it possible that the server is blocking new requests due to the high demand?

[Update]: As a temporary solution I inserted a random sleeping time between requests (0 to 10 miliseconds). It seems to work.

**Comment by Blagodarenko** [comment]
I got the same problem @ v5.24.0
I think problem in connection :
   'Connection': 'keep-alive',
   'Keep-Alive': 'timeout=5, max=512'
 try to close connection after each request
