### ISSUE TITLE
Map matching result is discontinuity from public road to private road.

### ISSUE THREAD

**Issue by zhysong** [Project-OSRM/osrm-backend#5982]
Summary: Matching result is discontinuity.

Steps To Reproduce:
1. Get a route by route service.
    origin: 39.14018,-94.54684     destination: 39.15423,-94.53151
    [link](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=39.14244%2C-94.54558%3B39.15423%2C-94.53151#map=16/39.1483/-94.5393)
2. Use the route geometries (polyline) to do map matching.
    match request: 
http://xxxxxx/match/v1/driving/polyline(mq{mFxda`Qw@BOL[|@INIBE@kAAIDi@pAKLm@Ci@CQOQMi@c@gAy@]WYU]Y[Um@e@cByAq@m@Uo@Sy@?aANsAn@{GZ_DBoAKaA]uAaCwEGMy@cAuAo@sDaB{DoBi@a@Y]MOSm@Qw@_AcHY{BE[E]_@LiBf@uA`@}@ZoEbB_@Jk@Lg@FYD]@I?a@B]Ae@?{@?aBKc@Ki@M_Cq@FW@GFa@Bk@?sB?gC@oD?y@?}C?oC)?generate_hints=false&annotations=false&overview=full&tidy=false

Expected Results:
There is one matching in the match result.
The route from matching service should be the same as that from route service.

Actual Results:
There are two matchings in the match result. The route is discontinuity at the red road.
![image](https://user-images.githubusercontent.com/63575514/110909334-f4094980-834a-11eb-8c41-18af8bc3947d.png)

Version:
v5.23.0

Note:
I found this issue occurred the route going through from public road to private road.

In route service we will add max_turn_weight from public road to private road
https://github.com/Project-OSRM/osrm-backend/blob/9d81eb327a74745be3af28308fcc798dd1a93723/profiles/car.lua#L487-L493

In match service we have an weight_upper_bound to calculate route distance.
https://github.com/Project-OSRM/osrm-backend/blob/9d81eb327a74745be3af28308fcc798dd1a93723/src/engine/routing_algorithms/map_matching.cpp#L220-L221
https://github.com/Project-OSRM/osrm-backend/blob/9d81eb327a74745be3af28308fcc798dd1a93723/src/engine/routing_algorithms/map_matching.cpp#L240-L256
weight_upper_bound is always lower than max_turn_weight, network_distance  = std::numeric_limits<double>::max(), so this path is pruned.

**Comment by frodrigo** [comment]
Can you give more details, please.

**Comment by zhysong** [comment]
matching request:
http://xxxxxx/match/v1/driving/polyline(mq{mFxda`Qw@BOL[|@INIBE@kAAIDi@pAKLm@Ci@CQOQMi@c@gAy@]WYU]Y[Um@e@cByAq@m@Uo@Sy@?aANsAn@{GZ_DBoAKaA]uAaCwEGMy@cAuAo@sDaB{DoBi@a@Y]MOSm@Qw@_AcHY{BE[E]_@LiBf@uA`@}@ZoEbB_@Jk@Lg@FYD]@I?a@B]Ae@?{@?aBKc@Ki@M_Cq@FW@GFa@Bk@?sB?gC@oD?y@?}C?oC)?generate_hints=false&annotations=false&overview=full&tidy=false
match result:
The result has two matchings, and the match route is interrupted at red route on the picture.
{"code":"Ok","matchings":[{"confidence":0.980307,"geometry":"mq{mFxda`Qw@B??OL??[|@??IN??IB??E@??kAA??ID??i@pA??KL??m@C??i@C??QO??QM??i@c@??gAy@??]W??YU??]Y??[U??m@e@??","legs":[{"steps":[],"distance":31.1,"duration":7.4,"summary":"","weight":7.4},{"steps":[],"distance":10.7,"duration":2.6,"summary":"","weight":2.6},{"steps":[],"distance":30.9,"duration":7.4,"summary":"","weight":7.4},{"steps":[],"distance":8.8,"duration":2.1,"summary":"","weight":2.1},{"steps":[],"distance":5.8,"duration":1.5,"summary":"","weight":1.5},{"steps":[],"distance":3.5,"duration":0.9,"summary":"","weight":0.9},{"steps":[],"distance":42.3,"duration":10.2,"summary":"","weight":10.2},{"steps":[],"distance":6.2,"duration":1.5,"summary":"","weight":1.5},{"steps":[],"distance":42.7,"duration":10.2,"summary":"","weight":10.2},{"steps":[],"distance":9,"duration":2.1,"summary":"","weight":2.1},{"steps":[],"distance":25.6,"duration":6.1,"summary":"","weight":6.1},{"steps":[],"distance":23.3,"duration":5.6,"summary":"","weight":5.6},{"steps":[],"distance":12.1,"duration":2.9,"summary":"","weight":2.9},{"steps":[],"distance":11.7,"duration":2.1,"summary":"","weight":2.1},{"steps":[],"distance":28,"duration":5.2,"summary":"","weight":5.2},{"steps":[],"distance":47.2,"duration":8.8,"summary":"","weight":8.8},{"steps":[],"distance":19.7,"duration":3.6,"summary":"","weight":3.6},{"steps":[],"distance":17.3,"duration":3.4,"summary":"","weight":3.4},{"steps":[],"distance":20.1,"duration":3.7,"summary":"","weight":3.7},{"steps":[],"distance":18.2,"duration":3.4,"summary":"","weight":3.4},{"steps":[],"distance":30.4,"duration":11.6,"summary":"","weight":11.6}],"distance":444.6,"duration":102.3,"weight_name":"routability","weight":102.3},{"confidence":0.980439,"geometry":"ii|mF``a`Q??q@m@??Uo@??Sy@???aA??NsA??n@{G??Z_D??BoA??KaA??]uA??aCwE??GM??y@cA??uAo@??sDaB??{DoB??i@a@??Y]??MO??Sm@??Qw@??_AcH??Y{B??E[??E]??_@L??iBf@??uA`@??}@Z?@oE`B??_@J??k@L??g@F??YD??]@??I???a@B??]A??e@???{@???aBK??c@K??i@M??_Cq@??FW??@G??Da@@?Bk@???sB???gC??@oD???y@???}C???oC","legs":[{"steps":[],"distance":34.2,"duration":3.9,"summary":"","weight":3.9},{"steps":[],"distance":23.9,"duration":2.6,"summary":"","weight":2.6},{"steps":[],"distance":27.6,"duration":3.1,"summary":"","weight":3.1},{"steps":[],"distance":28,"duration":3,"summary":"","weight":3},{"steps":[],"distance":37.2,"duration":4.3,"summary":"","weight":4.3},{"steps":[],"distance":125.4,"duration":14,"summary":"","weight":14},{"steps":[],"distance":70.7,"duration":7.9,"summary":"","weight":7.9},{"steps":[],"distance":34.5,"duration":3.8,"summary":"","weight":3.8},{"steps":[],"distance":29.1,"duration":3.3,"summary":"","weight":3.3},{"steps":[],"distance":40.8,"duration":4.6,"summary":"","weight":4.6},{"steps":[],"distance":118,"duration":9.4,"summary":"","weight":9.4},{"steps":[],"distance":7.6,"duration":1.2,"summary":"","weight":1.2},{"steps":[],"distance":43.7,"duration":6.3,"summary":"","weight":6.3},{"steps":[],"distance":52.1,"duration":7.5,"summary":"","weight":7.5},{"steps":[],"distance":108.7,"duration":15.6,"summary":"","weight":15.6},{"steps":[],"distance":115.1,"duration":16.5,"summary":"","weight":16.5},{"steps":[],"distance":27.6,"duration":3.9,"summary":"","weight":3.9},{"steps":[],"distance":19.4,"duration":2.8,"summary":"","weight":2.8},{"steps":[],"distance":10.4,"duration":1.5,"summary":"","weight":1.5},{"steps":[],"distance":22.7,"duration":3.2,"summary":"","weight":3.2},{"steps":[],"distance":26.2,"duration":3.8,"summary":"","weight":3.8},{"steps":[],"distance":130.9,"duration":18.8,"summary":"","weight":18.8},{"steps":[],"distance":55.5,"duration":8,"summary":"","weight":8},{"steps":[],"distance":12.8,"duration":3.9,"summary":"","weight":3.9},{"steps":[],"distance":13.4,"duration":9.5,"summary":"","weight":9.5},{"steps":[],"distance":18.8,"duration":1.2,"summary":"","weight":1.2},{"steps":[],"distance":61.4,"duration":3.8,"summary":"","weight":3.8},{"steps":[],"distance":50.1,"duration":3.1,"summary":"","weight":3.1},{"steps":[],"distance":36.6,"duration":4.3,"summary":"","weight":4.3},{"steps":[],"distance":123.4,"duration":7.7,"summary":"","weight":7.7},{"steps":[],"distance":18.5,"duration":1.2,"summary":"","weight":1.2},{"steps":[],"distance":25.2,"duration":1.5,"summary":"","weight":1.5},{"steps":[],"distance":22.5,"duration":3.4,"summary":"","weight":3.4},{"steps":[],"distance":14.6,"duration":0.9,"summary":"","weight":0.9},{"steps":[],"distance":16.7,"duration":1.1,"summary":"","weight":1.1},{"steps":[],"distance":5.6,"duration":0.3,"summary":"","weight":0.3},{"steps":[],"distance":18.9,"duration":1.6,"summary":"","weight":1.6},{"steps":[],"distance":16.7,"duration":1.3,"summary":"","weight":1.3},{"steps":[],"distance":21.1,"duration":1.7,"summary":"","weight":1.7},{"steps":[],"distance":33.4,"duration":2.6,"summary":"","weight":2.6},{"steps":[],"distance":54.8,"duration":4.3,"summary":"","weight":4.3},{"steps":[],"distance":20.6,"duration":1.7,"summary":"","weight":1.7},{"steps":[],"distance":24.2,"duration":1.9,"summary":"","weight":1.9},{"steps":[],"distance":74.7,"duration":10.5,"summary":"","weight":10.5},{"steps":[],"distance":11.4,"duration":1.6,"summary":"","weight":1.6},{"steps":[],"distance":3.6,"duration":0.5,"summary":"","weight":0.5},{"steps":[],"distance":15.3,"duration":2.2,"summary":"","weight":2.2},{"steps":[],"distance":19,"duration":2.6,"summary":"","weight":2.6},{"steps":[],"distance":50,"duration":7.2,"summary":"","weight":7.2},{"steps":[],"distance":58.7,"duration":8.6,"summary":"","weight":8.6},{"steps":[],"distance":75.9,"duration":10.9,"summary":"","weight":10.9},{"steps":[],"distance":25,"duration":3.6,"summary":"","weight":3.6},{"steps":[],"distance":68.1,"duration":9.8,"summary":"","weight":9.8},{"steps":[],"distance":62.1,"duration":9.1,"summary":"","weight":9.1}],"distance":2262.4,"duration":272.6,"weight_name":"routability","weight":272.6}],"tracepoints":[{"alternatives_count":0,"waypoint_index":0,"location":[-94.546852,39.14023],"name":"","distance":0.172952,"matchings_index":0},{"alternatives_count":0,"waypoint_index":1,"location":[-94.546871,39.140509],"name":"","distance":0.140722,"matchings_index":0},{"alternatives_count":0,"waypoint_index":2,"location":[-94.546943,39.140587],"name":"","distance":0.422165,"matchings_index":0},{"alternatives_count":0,"waypoint_index":3,"location":[-94.547252,39.140728],"name":"","distance":0.281443,"matchings_index":0},{"alternatives_count":0,"waypoint_index":4,"location":[-94.547328,39.14078],"name":"","distance":0.172952,"matchings_index":0},{"alternatives_count":0,"waypoint_index":5,"location":[-94.547348,39.14083],"name":"","distance":0.172952,"matchings_index":0},{"alternatives_count":0,"waypoint_index":6,"location":[-94.547359,39.14086],"name":"","distance":0.086476,"matchings_index":0},{"alternatives_count":0,"waypoint_index":7,"location":[-94.547349,39.14124],"name":"","distance":0.086476,"matchings_index":0},{"alternatives_count":0,"waypoint_index":8,"location":[-94.547376,39.141291],"name":"","distance":0.363282,"matchings_index":0},{"alternatives_count":0,"waypoint_index":9,"location":[-94.54779,39.1415],"name":"","distance":0,"matchings_index":0},{"alternatives_count":0,"waypoint_index":10,"location":[-94.547859,39.141561],"name":"","distance":0.140722,"matchings_index":0},{"alternatives_count":0,"waypoint_index":11,"location":[-94.547837,39.14179],"name":"","distance":0.259428,"matchings_index":0},{"alternatives_count":0,"waypoint_index":12,"location":[-94.547818,39.141999],"name":"","distance":0.205516,"matchings_index":0},{"alternatives_count":0,"waypoint_index":13,"location":[-94.547741,39.14209],"name":"Riverboat Drive","distance":0.086476,"matchings_index":0},{"alternatives_count":0,"waypoint_index":14,"location":[-94.547668,39.142179],"name":"Riverboat Drive","distance":0.205516,"matchings_index":0},{"alternatives_count":0,"waypoint_index":15,"location":[-94.547492,39.142391],"name":"Riverboat Drive","distance":0.205516,"matchings_index":0},{"alternatives_count":0,"waypoint_index":16,"location":[-94.547198,39.142749],"name":"Riverboat Drive","distance":0.205516,"matchings_index":0},{"alternatives_count":0,"waypoint_index":17,"location":[-94.547075,39.142898],"name":"Riverboat Drive","distance":0.486056,"matchings_index":0},{"alternatives_count":0,"waypoint_index":18,"location":[-94.546967,39.143029],"name":"Riverboat Drive","distance":0.282183,"matchings_index":0},{"alternatives_count":1,"waypoint_index":19,"location":[-94.546842,39.143181],"name":"Riverboat Drive","distance":0.205516,"matchings_index":0},{"alternatives_count":2,"waypoint_index":20,"location":[-94.546728,39.143319],"name":"Riverboat Drive","distance":0.205516,"matchings_index":0},{"alternatives_count":7,"waypoint_index":21,"location":[-94.546538,39.143549],"name":"","distance":0.205516,"matchings_index":0},{"alternatives_count":0,"waypoint_index":0,"location":[-94.546091,39.144051],"name":"Riverboat Drive","distance":0.140722,"matchings_index":1},{"alternatives_count":0,"waypoint_index":1,"location":[-94.545857,39.144299],"name":"Riverboat Drive","distance":0.282183,"matchings_index":1},{"alternatives_count":0,"waypoint_index":2,"location":[-94.54562,39.14441],"name":"Riverboat Drive","distance":0,"matchings_index":1},{"alternatives_count":0,"waypoint_index":3,"location":[-94.545325,39.144505],"name":"Riverboat Drive","distance":0.703608,"matchings_index":1},{"alternatives_count":0,"waypoint_index":4,"location":[-94.545,39.144505],"name":"Riverboat Drive","distance":0.555079,"matchings_index":1},{"alternatives_count":0,"waypoint_index":5,"location":[-94.544579,39.144433],"name":"Riverboat Drive","distance":0.344091,"matchings_index":1},{"alternatives_count":0,"waypoint_index":6,"location":[-94.543159,39.144193],"name":"Riverboat Drive","distance":0.344091,"matchings_index":1},{"alternatives_count":0,"waypoint_index":7,"location":[-94.542359,39.144054],"name":"Riverboat Drive","distance":0.452405,"matchings_index":1},{"alternatives_count":0,"waypoint_index":8,"location":[-94.54196,39.144033],"name":"Riverboat Drive","distance":0.333047,"matchings_index":1},{"alternatives_count":0,"waypoint_index":9,"location":[-94.541629,39.144085],"name":"Riverboat Drive","distance":0.561774,"matchings_index":1},{"alternatives_count":0,"waypoint_index":10,"location":[-94.541199,39.144238],"name":"Riverboat Drive","distance":0.238277,"matchings_index":1},{"alternatives_count":0,"waypoint_index":11,"location":[-94.540115,39.144885],"name":"Riverboat Drive","distance":0.703608,"matchings_index":1},{"alternatives_count":0,"waypoint_index":12,"location":[-94.540045,39.144926],"name":"Riverboat Drive","distance":0.619794,"matchings_index":1},{"alternatives_count":0,"waypoint_index":13,"location":[-94.53971,39.14522],"name":"Riverboat Drive","distance":0,"matchings_index":1},{"alternatives_count":0,"waypoint_index":14,"location":[-94.539472,39.145651],"name":"Riverboat Drive","distance":0.205516,"matchings_index":1},{"alternatives_count":0,"waypoint_index":15,"location":[-94.538976,39.146549],"name":"Riverboat Drive","distance":0.363282,"matchings_index":1},{"alternatives_count":0,"waypoint_index":16,"location":[-94.538423,39.147491],"name":"Riverboat Drive","distance":0.282183,"matchings_index":1},{"alternatives_count":0,"waypoint_index":17,"location":[-94.53825,39.1477],"name":"Riverboat Drive","distance":0,"matchings_index":1},{"alternatives_count":0,"waypoint_index":18,"location":[-94.538099,39.147829],"name":"Riverboat Drive","distance":0.140722,"matchings_index":1},{"alternatives_count":0,"waypoint_index":19,"location":[-94.538019,39.147899],"name":"Riverboat Drive","distance":0.140722,"matchings_index":1},{"alternatives_count":0,"waypoint_index":20,"location":[-94.537792,39.148002],"name":"Riverboat Drive","distance":0.281443,"matchings_index":1},{"alternatives_count":0,"waypoint_index":21,"location":[-94.537511,39.148092],"name":"Riverboat Drive","distance":0.238277,"matchings_index":1},{"alternatives_count":0,"waypoint_index":22,"location":[-94.53605,39.148409],"name":"Riverboat Drive","distance":0.111016,"matchings_index":1},{"alternatives_count":0,"waypoint_index":23,"location":[-94.53543,39.148541],"name":"Riverboat Drive","distance":0.111016,"matchings_index":1},{"alternatives_count":0,"waypoint_index":24,"location":[-94.535286,39.148568],"name":"Riverboat Drive","distance":0.411032,"matchings_index":1},{"alternatives_count":0,"waypoint_index":25,"location":[-94.53514,39.1486],"name":"North Chouteau Trafficway","distance":0,"matchings_index":1},{"alternatives_count":0,"waypoint_index":26,"location":[-94.53521,39.14876],"name":"North Chouteau Trafficway","distance":0,"matchings_index":1},{"alternatives_count":0,"waypoint_index":27,"location":[-94.535405,39.149291],"name":"North Chouteau Trafficway","distance":0.446404,"matchings_index":1},{"alternatives_count":0,"waypoint_index":28,"location":[-94.535581,39.14972],"name":"North Chouteau Trafficway","distance":0.086476,"matchings_index":1},{"alternatives_count":0,"waypoint_index":29,"location":[-94.535725,39.150029],"name":"North Chouteau Trafficway","distance":0.446109,"matchings_index":1},{"alternatives_count":0,"waypoint_index":30,"location":[-94.536219,39.15107],"name":"North Chouteau Trafficway","distance":0.086415,"matchings_index":1},{"alternatives_count":0,"waypoint_index":31,"location":[-94.536279,39.15123],"name":"North Chouteau Trafficway","distance":0.086415,"matchings_index":1},{"alternatives_count":0,"waypoint_index":32,"location":[-94.53635,39.15145],"name":"North Chouteau Trafficway","distance":0,"matchings_index":1},{"alternatives_count":0,"waypoint_index":33,"location":[-94.536391,39.15165],"name":"North Chouteau Trafficway","distance":0.086415,"matchings_index":1},{"alternatives_count":0,"waypoint_index":34,"location":[-94.536417,39.15178],"name":"North Chouteau Trafficway","distance":0.259245,"matchings_index":1},{"alternatives_count":0,"waypoint_index":35,"location":[-94.536432,39.15193],"name":"North Chouteau Trafficway","distance":0.17283,"matchings_index":1},{"alternatives_count":0,"waypoint_index":36,"location":[-94.536434,39.15198],"name":"North Chouteau Trafficway","distance":0.345659,"matchings_index":1},{"alternatives_count":0,"waypoint_index":37,"location":[-94.536445,39.15215],"name":"Northeast Chouteau Parkway","distance":0.432074,"matchings_index":1},{"alternatives_count":0,"waypoint_index":38,"location":[-94.536444,39.1523],"name":"Northeast Chouteau Parkway","distance":0.345659,"matchings_index":1},{"alternatives_count":0,"waypoint_index":39,"location":[-94.536437,39.15249],"name":"Northeast Chouteau Parkway","distance":0.259245,"matchings_index":1},{"alternatives_count":0,"waypoint_index":40,"location":[-94.536438,39.15279],"name":"Northeast Chouteau Parkway","distance":0.17283,"matchings_index":1},{"alternatives_count":0,"waypoint_index":41,"location":[-94.536375,39.15328],"name":"Northeast Chouteau Parkway","distance":0.432074,"matchings_index":1},{"alternatives_count":0,"waypoint_index":42,"location":[-94.536316,39.153459],"name":"Northeast Chouteau Parkway","distance":0.36305,"matchings_index":1},{"alternatives_count":0,"waypoint_index":43,"location":[-94.536247,39.15367],"name":"Northeast Chouteau Parkway","distance":0.259245,"matchings_index":1},{"alternatives_count":0,"waypoint_index":44,"location":[-94.535999,39.154313],"name":"Northeast 33rd Terrace","distance":0.344078,"matchings_index":1},{"alternatives_count":0,"waypoint_index":45,"location":[-94.535879,39.154271],"name":"Northeast 33rd Terrace","distance":0.140685,"matchings_index":1},{"alternatives_count":0,"waypoint_index":46,"location":[-94.53584,39.154259],"name":"Northeast 33rd Terrace","distance":0.111017,"matchings_index":1},{"alternatives_count":0,"waypoint_index":47,"location":[-94.535668,39.154225],"name":"Northeast 33rd Terrace","distance":0.581367,"matchings_index":1},{"alternatives_count":0,"waypoint_index":48,"location":[-94.53545,39.154201],"name":"Northeast 33rd Terrace","distance":0.111017,"matchings_index":1},{"alternatives_count":0,"waypoint_index":49,"location":[-94.53487,39.154199],"name":"Northeast 33rd Terrace","distance":0.111017,"matchings_index":1},{"alternatives_count":0,"waypoint_index":50,"location":[-94.53419,39.154197],"name":"Northeast 33rd Terrace","distance":0.33305,"matchings_index":1},{"alternatives_count":0,"waypoint_index":51,"location":[-94.53331,39.154193],"name":"Northeast 33rd Terrace","distance":0.33305,"matchings_index":1},{"alternatives_count":0,"waypoint_index":52,"location":[-94.53302,39.154192],"name":"Northeast 33rd Terrace","distance":0.222033,"matchings_index":1},{"alternatives_count":0,"waypoint_index":53,"location":[-94.53223,39.154189],"name":"Northeast 33rd Terrace","distance":0.111017,"matchings_index":1},{"alternatives_count":1,"waypoint_index":54,"location":[-94.53151,39.154186],"name":"Northeast 33rd Terrace","distance":0.444067,"matchings_index":1}]}

**Comment by zhysong** [comment]
Update the issue description.

**Comment by frodrigo** [comment]
The map matching and the routing are done in the same instance?
How private road are supported depend from profile.

https://github.com/Project-OSRM/osrm-backend/blob/9d81eb327a74745be3af28308fcc798dd1a93723/profiles/car.lua#L67-L99

**Comment by zhysong** [comment]
> The map matching and the routing are done in the same instance?
Yes.

> How private road are supported depend from profile.
https://github.com/Project-OSRM/osrm-backend/blob/9d81eb327a74745be3af28308fcc798dd1a93723/profiles/car.lua#L168-L183
https://github.com/Project-OSRM/osrm-backend/blob/9d81eb327a74745be3af28308fcc798dd1a93723/profiles/car.lua#L94-L99
https://github.com/Project-OSRM/osrm-backend/blob/9d81eb327a74745be3af28308fcc798dd1a93723/profiles/lib/way_handlers.lua#L246-L255
forward_restricted or backward_restricted will be transferred to turn.source_restricted or turn.target_restricted in C++ code, then add max_turn_weight.
And match service and route service share the same route algorithm.

**Comment by SiarheiFedartsou** [comment]
Stale.
