### ISSUE TITLE
Build from source for Android / iOS devices

### ISSUE THREAD

**Issue by lmarcelocc** [Project-OSRM/osrm-backend#5983]
Hi all,

We're using a hybrid application with routing (Grahhopper, at this moment), with a [nodejs](https://github.com/janeasystems/nodejs-mobile-cordova) server running on our devices.

At this moment we really want to give it a try for OSRM, that it seems awesome for our requirements.

So we need to build the **OSRM** from sources to android / iOS devices. Is that possible ? From what we see from this [page](https://github.com/Project-OSRM/osrm-backend), there's no documentation for Android or iOS devices.

Thank you.

Kind regards,
Marcelo

**Comment by systemed** [comment]
OSRM keeps its routing graph in memory, which means it's not really suited for running on resource-constrained mobile devices. A typical OSRM instance might use 64GB+ of RAM or potentially much more, depending on the area covered.

I believe maps.me formerly used an (old) version of OSRM for on-device routing, so it's not entirely impossible, but generally OSRM isn't a good fit for this use-case.

**Comment by lmarcelocc** [comment]
Thank you for your reply @systemed .

So, do you know any other alternatives, besides Graphhopper ?

**Comment by nilsnolde** [comment]
Valhalla is the best choice for mobile IMO: https://github.com/valhalla/valhalla

**Comment by danpat** [comment]
You can use OSRM in a `mmap`-ed mode which reduces the real RAM requirements, but I've seen problems on mobile devices where the virtual memory space was also limited and you couldn't `mmap` large files.

I agree with @nilsnolde - Valhalla has a better design for mobile device use-cases.  On mobile contexts, you are *usually* not needing to generate large numbers of route calculations, so you can afford a little bit of a performance reduction in the name of reduced resource requirements.
