### ISSUE TITLE
Trying to understand the timestamp on match api (New user.)

### ISSUE THREAD

**Issue by KaSakee** [Project-OSRM/osrm-backend#5984]
Hey guys!, I'm trying to understand the timestamp in the /match api with OSRM
All i know is this is a time stamp. (1615703474876 This timestamp source is android location.getTime()) so i should use it like (1615703474876;1615703474876)
Lets say?
If no please can someone explain to me what is the timestamp required for the api? and how to use it in an example <3
Don't mind me i'm a new user on spatial and location things (: <3

And how using timestamps are useful for more accurate matching?

**Comment by ZephD** [comment]
You need epoch seconds (not milliseconds, so floor(ms/1000) ), one per coordinate, and joined with a semi-colon.

**Comment by KaSakee** [comment]
Hey, t thanks for giving me time to answer me have any idea about how using timestamps is useful for more accurate matching? or why is it needed at all?

**Comment by KaSakee** [comment]
> You need epoch seconds (not milliseconds, so floor(ms/1000) ), one per coordinate, and joined with a semi-colon.

Hey, t thanks for giving me time to answer me have any idea about how using timestamps is useful for more accurate matching? or why is it needed at all?

**Comment by KaSakee** [comment]
And ill mention that I have it like this, timestamps=22373972258;22374941430
And it return "{"message":"Query string malformed close to position 73","code":"InvalidQuery"}"

Using it with these parameters.
radiuses=5;5&tidy=true&approaches=curb;curb&steps=true&overview=full

And if I take out the timestamps parameters everything works fine again anything wrong?

I got the timestamp ms and I Math.floor(ms/1000) as you suggested

**Comment by ZephD** [comment]
Say you have two roads side by side, and your GPS data goes up between them. One road is a motorway (70mph) and the other is a small side road (30mph). OSRM knows the speed limits and therefore the estimated speed of the roads, and it can use your timestamps to see if you were travelling fast up the route or slow, and therefore better match to the correct road (slow? 30mph, fast? 70mph).

**Comment by KaSakee** [comment]
> Say you have two roads side by side, and your GPS data goes up between them. One road is a motorway (70mph) and the other is a small side road (30mph). OSRM knows the speed limits and therefore the estimated speed of the roads, and it can use your timestamps to see if you were travelling fast up the route or slow, and therefore better match to the correct road (slow? 30mph, fast? 70mph).

Thank you so much <3
