### ISSUE TITLE
Adding time dependent oneway tag

### ISSUE THREAD

**Issue by Vedanta-Zomato** [Project-OSRM/osrm-backend#5985]
Hi, 
Is it possible to add oneway tag dependent on time.
For instance, A road segment is only oneway from 6AM to 6PM.

If we can add a tag on road segment, denoting the time, is there a way to handle this on the lua profile?

**Comment by frodrigo** [comment]
It is possible to prepare/contract the data for point in the time.
But it not possible to make a query  depending of the time.

(In fact it is not completely impossible and my use classes based on time, but require works, and not so flexible)
