### ISSUE TITLE
How use only roads?

### ISSUE THREAD

**Issue by carloshm91** [Project-OSRM/osrm-backend#5992]
In this case he use water.

![image](https://user-images.githubusercontent.com/37907824/112248419-450f1c80-8c2c-11eb-9c9d-a8673fab560a.png)

http://map.project-osrm.org/?z=15&center=23.143103,-82.346435&loc=23.130020,-82.377634&loc=23.155118,-82.333002&hl=en&alt=0&srv=1

I want to use only roads.

**Comment by danpat** [comment]
By default, the OSRM bike profile will use ferries - that is what is happening above.

You would need to run your own OSRM server.  Uncomment this line: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/bicycle.lua#L200  and you can add `&exclude=ferry` to your bike routing requests.

**Comment by SiarheiFedartsou** [comment]
Closing as answer provided.
