### ISSUE TITLE
Circular reference building flatbuffers for csharp

### ISSUE THREAD

**Issue by Karlpietsch** [Project-OSRM/osrm-backend#5993]
If you build csharp flatbuffers parsers the resulting code has a cicular reference error for table class.

I renamed table to tableresult in table.fbs and fbresult.fbs and it works

this might be a bug in flatbuffers flatc but also maybe words like struct and table are reserved words for class names in flatbuffers?

**Comment by SiarheiFedartsou** [comment]
Stale.
