### ISSUE TITLE
Can't extract map for germany by docker v5.24

### ISSUE THREAD

**Issue by djonik1562** [Project-OSRM/osrm-backend#5995]
Hello.
I download latest dach from [geofabrik](http://download.geofabrik.de/europe/dach.html), try extract, but can't. This all log from osrm:
```
user@doc:~$ docker run -t --rm --name osrm-extract -m 6G -v "/home/djonik/maps:/maps" -v "/home/djonik/sedi-docker/osrm:/data" osrm/osrm-backend:v5.24.0 osrm-extract -p /data/car-distance.lua /maps/dach-latest.osm.pbf
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /data/car-distance.lua
[info] Input file: dach-latest.osm.pbf
[info] Profile: car-distance.lua
[info] Threads: 4
[info] Parsing in progress..
[info] input file generated by osmium/1.8.0
[info] timestamp: 2021-03-27T21:22:01Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
```
This all. Nothing errors. 

I tryed download distinct germany, austria and switzerland. Germany same like dach. Austria extracted normally. Switzerland extracted normally.
Tryed version 5.23, 5.22. Same problem.

Where possible problem?

**Comment by djonik1562** [comment]
Latest image of osrm normally extract germany.

**Comment by nilsnolde** [comment]
Too low RAM I'd guess by the pattern you're describing (DACH & DE >> CH/AU, though I have little real experience with OSRM..

**Comment by djonik1562** [comment]
> Too low RAM I'd guess by the pattern you're describing (DACH & DE >> CH/AU, though I have little real experience with OSRM..

Maybe. I will try add memory to vm.
Thanks.

**Comment by djonik1562** [comment]
Yes, too low RAM. Close issue.

**Comment by danpat** [comment]
I will note that the return code from your `docker run` command will be non-zero - it's always good practice to do `docker run ... || echo "Command returned non-zero exit code"` so you notice errors like this.

Somewhere in your system logs there is probably a message like `Out of memory: Kill process 1234 (osrm-extract) score <something> or sacrifice child`, but Docker doesn't let you know this happened very clearly.

**Comment by djonik1562** [comment]
> I will note that the return code from your `docker run` command will be non-zero - it's always good practice to do `docker run ... || echo "Command returned non-zero exit code"` so you notice errors like this.
> 
> Somewhere in your system logs there is probably a message like `Out of memory: Kill process 1234 (osrm-extract) score <something> or sacrifice child`, but Docker doesn't let you know this happened very clearly.

Thank you for advise.
