### ISSUE TITLE
Use of barrier=kerb blocking routing on major highways

### ISSUE THREAD

**Issue by mjjbell** [Project-OSRM/osrm-backend#5996]
Whilst debugging a routing issue using the default `car.lua` profile,  I determined the cause was the use of the `barrier=kerb` tag on a node that is part of a major road. I believe the intention is for the barrier tag to describe the highway crossing, not the highway itself.

Here's an example: 
![image](https://user-images.githubusercontent.com/1063186/112768045-ebcf3080-9011-11eb-9b6c-8ee342bcf80c.png)
[node](https://www.openstreetmap.org/node/1175146901)

![image](https://user-images.githubusercontent.com/1063186/112768016-bcb8bf00-9011-11eb-872d-01f6c48b45d8.png)
[diverted route](https://map.project-osrm.org/?z=18&center=48.778356%2C9.201645&loc=48.777414%2C9.203174&loc=48.777658%2C9.202992&hl=en&alt=0&srv=0)

`barrier=kerb` is not included in the [whitelist](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L54) for the default car profile - the [OSM guidelines](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkerb) treat the use of this tag for a highway crossing as a mistake.

However, it appears its usage is [quite widespread](https://overpass-turbo.eu/s/15C4), which leads me to believe a one-off correction would not prevent these from being recreated.

Whilst this is not specifically an OSRM issue and can be fixed with profile changes, it does raise the issue of how the profile can be more resilient to OSM tagging mistakes.

### Related

There have been previous discussions around this topic. 
#5067 -  Routing over `barrier=kerb` may make sense over small private roads, e.g. driveways.
#3890 - Discusses changing whitelists to blacklists to deal with unexpected tags. This was applied for foot and bicycle profiles. The suggestion is this could also be applied to major highways for cars, where the list of applicable barriers is stable.

**Comment by danpat** [comment]
This is something we've adjusted on our internal deployment and I forgot to push back into the main repo.  Our diff looks like this:

```diff
diff --git a/profiles/car.lua b/profiles/car.lua
--- a/profiles/car.lua
+++ b/profiles/car.lua
@@ -361,7 +360,11 @@ function process_node(profile, node, result, relations)
       local bollard = node:get_value_by_key("bollard")
       local rising_bollard = bollard and "rising" == bollard

-      if not profile.barrier_whitelist[barrier] and not rising_bollard or restricted_by_height then
+      -- make an exception for lowered/flat barrier=kerb
+      local kerb = node:get_value_by_key("kerb")
+      local flat_kerb = kerb and ("lowered" == kerb or "flush" == kerb)
+
+      if not profile.barrier_whitelist[barrier] and not rising_bollard and not flat_kerb or restricted_by_height then
         result.barrier = true
       end
     end
```

**Comment by mjjbell** [comment]
Made #5999 to add this. 
Also included an additional clause for `highway=crossing` tags as there are still [some barriers](https://overpass-turbo.eu/s/15Cq) that the above change doesn't catch, including the example above.
