### ISSUE TITLE
503 Error: Service Unavailable?

### ISSUE THREAD

**Issue by sdewbois** [Project-OSRM/osrm-backend#5997]
I'm currently receiving a 503 Server Error: Service Unavailable error when trying to create a distance matrix. Any issues with the server now?

**Comment by danpat** [comment]
@sdewbois Are you running your own server?

The `router.project-osrm.org` demoserver has no uptime guarantees.  If you need reliability, you should operate your own instance.

**Comment by datendelphin** [comment]
Yes  indeed there are some issues currently. Somewhat tricky to track down though.
What I see is that osrm seems to take a very long time with a request or two. Which seems to trigger apache into some degraded state where only few requests get through.
Restarting osrm seems to resolve the problem, until the next such issue
