### ISSUE TITLE
Shared memory with osrm-datastore: Show message, when boost_interprocess cannot access C:\\ProgramData\boost_interprocess

### ISSUE THREAD

**Issue by SirTobias** [Project-OSRM/osrm-backend#5998]
Dear community,

first of all, thank you for this wonderful router. Just a suggestion for improving error messages in osrm-datastore: 

Considering the issue that sometimes osrm-datastore hangs up (Windows 10) and the boost::interprocess file lock cannot access C:\\ProgramData\boost_interprocess\* as an old "zombie" instance blocks the directory, the exception should be catched in 

`Storage::Run(int max_wait, const std::string &dataset_name, bool only_metric)`

as in my case osrm-datastore just quit silenced without any message. I had to build the debug version and attach Visual Studio to see the blocked directory, which was unsuccessfully tried to assign.

Best regards,
Tobias

**Comment by danpat** [comment]
@SirTobias pull requests to fix this are very welcome :-) (aka if you have the time, please submit a patch).
