### ISSUE TITLE
[error] Input file not found!

### ISSUE THREAD

**Issue by Madsreinhardt** [Project-OSRM/osrm-backend#6000]
Hi, I will preface this by saying I am a newbie.

Nonetheless, I tried to run the OSRM backend docker commands but I have one problem. When I run this command:

docker run -t -v "%cd%":/data osrm/osrm-backend osrm-extract -p /opt/foot.lua /data/denmark-latest.osm.pbf

I get the message: "[error] Input file /data/denmark-latest.osm.pbf not found!"

A few things to note is that I changed 

This: ${PWD} from the original command in the OSRM backend

To this: %cd%"

Because I run docker on a windows 10 not Linux - it is mentioned in this post: https://github.com/Project-OSRM/osrm-backend/issues/5206?fbclid=IwAR0nsHIW4YS9ykiY3EK05tgYFHugVw4yj2P9ZOAUx4JPozWSpa4KglzrVbk

A few posts also mention "shared drives" options as a solution but in my settings I don't have a "shared drive" option - which I think is because I run on WSL 2 (though I am not sure about that one). 

![Error_PNG](https://user-images.githubusercontent.com/78300587/113122846-4c2dc000-9214-11eb-952a-b995a057ad91.png)

**Comment by danpat** [comment]
This is not an OSRM issue, it's something to do with using Docker on Windows.

The key here is that you need to mount the directory that contains `denmark-latest.osm.pbf` into the `/data` path inside the container.  Instructions for mounting volumes with Docker can be found here:

  https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only

There are some Windows specific details there that you should read.
