### ISSUE TITLE
Skip compression in graph creation

### ISSUE THREAD

**Issue by petherick93** [Project-OSRM/osrm-backend#6001]
I'm hosting a local OSRM server with some custom OSM data. 

I'd like to specifically track each way name passed in the returned route through the `RouteStep`s.
Unfortunately I'm losing a lot of granularity in the graph compression as all degree 2 nodes are removed.

Is there a way to disable graph simplification/compression?

the following commands don't give any clues:
```
osrm-extract --help
osrm-partition --help
osrm-customize --help
```

**Comment by danpat** [comment]
As long as the way names are unique, then edges will be created for them and not merged.

What you're *probably* experiencing is the guidance simplification - we don't generate RouteStep's for maneuvers that are considered "obvious" (i.e. going straight across intersections).

There's no way to disable this at runtime - you'd need to tweak the C++ code somewhere around here:  https://github.com/Project-OSRM/osrm-backend/blob/50d9632ed7ce397b23663d392dc9728b076f1a16/include/engine/api/route_api.hpp#L908-L965
