### ISSUE TITLE
error when run osrm-routed

### ISSUE THREAD

**Issue by augustobritome** [Project-OSRM/osrm-backend#6003]
Hello, i'm getting this error when i try to run osrm-routed. Already check md5.
datasource_names
[error] Required files are missing, cannot continue

**Comment by danpat** [comment]
It sounds like your data processing steps may have failed and not generated all the needed files.  Try cleaning up and re-running the `osrm-extract` and `osrm-contract` commands - and check that they succeed (check the return code).
