### ISSUE TITLE
Missing segment on the OSRM network ?

### ISSUE THREAD

**Issue by fgmehlin** [Project-OSRM/osrm-backend#6005]
Hi,

It seems that OSRM is unable to map points to this particular segment (the curve part): 

https://goo.gl/maps/YMsLafZaRaz3nCh67

It either map to top or bottom straight part.  Is this a common use case ?

Thanks 

<img width="1679" alt="Screenshot 2021-04-07 at 17 14 27" src="https://user-images.githubusercontent.com/2466140/113890804-c89c4200-97c4-11eb-8d78-1a4111874ef8.png">

**Comment by datendelphin** [comment]
That is a railroad https://www.openstreetmap.org/way/654062814 You need a railroad profile and then it should match as expected.

**Comment by danpat** [comment]
It also looks like there are quite a few gravel service roads in that area that aren't mapped at all.  Agree with @datendelphin that this isn't OSRM's fault - the mapping here is incomplete for the `car` profile.
