### ISSUE TITLE
Adding some realistic traffic data

### ISSUE THREAD

**Issue by GreenRoutesGitHub** [Project-OSRM/osrm-backend#6007]
Hi guys,

I'm using osrm for a while now. However, I'm facing the problem that travel durations aren't realistic. This is because there is no traffic data into osrm. However, does osrm take traffic lights etc. into account? And can I find some data that I can add to osrm such that the durations are more realistic? I worked with mapbox, but for a table matrix of 3000x3000 it is really expensive. Right now, I'm mutiplying the elements in the duration matrix (table). Does someone know from experience what number is a realistic mutiplier for the durations.

**Comment by jcoupey** [comment]
OSRM allows to update speeds on a per-edge basis, see https://github.com/Project-OSRM/osrm-backend/wiki/Traffic. That's a technical ability only and I'm afraid the question of *where* you can find this kind of data is somehow out of scope here. You'll get some pointers by browsing existing issues mentioning traffic in this repo though.

**Comment by frodrigo** [comment]
You can also adapt the profile to better match you location or vehicle.
The default profile not match well urban only traffic.
EG you may look at this https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/18/urban-density

**Comment by GreenRoutesGitHub** [comment]
Ok thanks! @frodrigo How is this profile adapted? How does this profile know which roads are urban?

**Comment by frodrigo** [comment]
While parsing data, the profile query a data base with polygons of density area. I implemented it for Europe on Corine Land Corver data base. But other exits, or can be derivatived from OSM data.

**Comment by GreenRoutesGitHub** [comment]
Perfect, thanks!

**Comment by Rougree** [comment]
> While parsing data, the profile query a data base with polygons of density area. I implemented it for Europe on Corine Land Corver data base. But other exits, or can be derivatived from OSM data.

Does this approach affects the computation time to get data from osrm with docker? @frodrigo

**Comment by frodrigo** [comment]
Yes, affect the preprocessing time. But not the route or matrix computation time.
Note the usage of a redis cache in my implementation to speed up later preprocessing run.
