### ISSUE TITLE
osrm crash

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#601]
our OSRM server had a crash the other day. we're running a custom branch (https://github.com/ibikecph/Project-OSRM/tree/ibikecph), although i don't right away see how the changes would cause this crash.

in any case i though i would post this:

```
[info Server/RequestHandler.h:65] 28-02-2013 15:41:31 193.169.154.66 http://www.ibikecph.dk/ Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 1.0.3705; .NET CLR 1.1.4322; .NET CLR 3.0.04506.30; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; .NET4.0E) /viaroute?jsonp=jQuery18309183272573437813_1362062171310&z=16&output=json&checksum=-1557865517&instructions=false&alt=false&loc=55.66524,12.57518&loc=55.66732,12.55542&hint=OzEYAOMbAQDTAQAARgAAAK4PN65oy-s_CvFUAHEoEwB
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  Transport endpoint is not connected
Aborted
```

**Comment by mredbishop** [comment]
We get this occasionally possibly to do with using virtual memory. We're running an image that consumes around 108gb RAM and it's failed with this error a couple of times this month.

**Comment by danpat** [comment]
@mredbishop Note that this ticket is from 2013 - the OSRM codebase no longer emits this error (the code that did this has been removed).  You may want to try upgrading if you can.
