### ISSUE TITLE
OSRM route doesn't start

### ISSUE THREAD

**Issue by jimasian** [Project-OSRM/osrm-backend#6011]
I'm trying to run an instance of OSRM through docker on a google cloud compute instance and ran into this issue where it just doesn't start and just quits.

![Screenshot (3)](https://user-images.githubusercontent.com/82485788/114794215-9903b180-9d51-11eb-9a65-c56c5a7fc4c4.png)

I've tried multiple times and it worked perfectly fine yesterday.

**Comment by danpat** [comment]
Did you check your system logs and or the exit code from the `docker` command?

My first guess would be that you're exceeding the amount of memory your docker container allows, and the kernel OOM killer is terminating the process - check `syslog` on your host to see if there are OOM-killer messages.

I don't think this is specifically an OSRM issue - more likely your docker infrastructure.

**Comment by jimasian** [comment]
@danpat OOM killer is the problem but I checked using docker stats and its only using around 21/32 gb and then just dying

**Comment by danpat** [comment]
@jimasian If the OOM killer is being invoked, then the docker stats are incorrect.  The kernel is the ultimate authority of when memory needs to be reclaimed.

You need more memory - sounds like your `us-latest.osrm` fileset has grown bigger than the amount of memory you've got available.  Try it on a larger capacity machine.
