### ISSUE TITLE
PBF error: invalid BlobHeader size (> max_blob_header_size)

### ISSUE THREAD

**Issue by christopherdalton** [Project-OSRM/osrm-backend#6014]
I am trying to build a docker image which contains the osm.pbf data file rather than map a volume (end goal is to use fuse S3FS - so that when I build on Azure DevOps I don't need to have custom build agents with large data drives just for processing and storing the raw data, once the full docker image is built the data will of course be local).

Dockerfile;

```
FROM osrm/osrm-backend:v5.24.0

RUN apt-get update
RUN apt-get install -y wget 

# create data folder
RUN mkdir /data


RUN wget -o /data/andorra-latest.osm.pbf "http://download.geofabrik.de/europe/andorra-latest.osm.pbf"
RUN ["osrm-extract", "-p", "/opt/car.lua", "/data/andorra-latest.osm.pbf"]
```

Error Message;
```
=> ERROR [6/6] RUN ["osrm-extract", "-p", "/opt/car.lua", "/data/andorra-latest.osm.pbf"]                                                                     0.4s
------
 > [6/6] RUN ["osrm-extract", "-p", "/opt/car.lua", "/data/andorra-latest.osm.pbf"]:
#9 0.338 [info] Parsed 0 location-dependent features with 0 GeoJSON polygons
#9 0.338 [info] Using script /opt/car.lua
#9 0.338 [info] Input file: andorra-latest.osm.pbf
#9 0.338 [info] Profile: car.lua
#9 0.338 [info] Threads: 16
#9 0.339 [info] Parsing in progress..
#9 0.340 terminate called after throwing an instance of 'osmium::pbf_error'
#9 0.340   what():  PBF error: invalid BlobHeader size (> max_blob_header_size)
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [osrm-extract -p /opt/car.lua /data/andorra-latest.osm.pbf]: exit code: 139
```

N.B. if I build the image without the osrm-extract commands and then run `osrm-extract -p /opt/car.lua /data/andorra-latest.osm.pbf` from with-in the container I get the same problem and I have to re-run the wget command and replace the .pbf file and this works fine.

Any Ideas?

**Comment by danpat** [comment]
Sounds like your PBF is corrupt.  You can use md5sum or some other checksum to verify it before processing with `osrm-extract`.

**Comment by christopherdalton** [comment]
> Sounds like your PBF is corrupt. You can use md5sum or some other checksum to verify it before processing with `osrm-extract`.

I would agree if I didn't experience the same issue 10+ times, (after running Docker prune so cached layers are removed). 

The only difference I see is `wget` being run inside the container as part of the build instead of outside, pre-build.

**Comment by danpat** [comment]
You're invoking `wget` wrong.  You should be using `wget -O` or `wget ---output-document=FILE`.

The `-o` flag is the same as `--output-file=FILE` which saves `wget`'s _log mesages_ to the file you specify.
