### ISSUE TITLE
Is it possible to define height limitation on OSRM query?

### ISSUE THREAD

**Issue by johnnyGor** [Project-OSRM/osrm-backend#6015]
Hi
Is that possible to ask OSRM about the route excluding roads with specified max height limitation? I have found that it can be done with profiles but my expectation is to make it in on the call level.

I have also seen exclude option but it was more or less for the type of the vehicle rather then height ( or weight). Something like "exclude": ["heightMax:4m"]?

**Comment by frodrigo** [comment]
Short: No. The height is a filter at data compile time.

Long: A solution may be to use classes to flag height on way at compilation, and exclude classes at runtime. It is no so flexible, but it may be a solution. Especially if you interested in OSRM high computation speed.

**Comment by johnnyGor** [comment]
Thank you Frodrigo. 
Is that this same as setting it in the profile ( like: https://github.com/rodo/osrm-profiles/blob/master/truck.lua)   or this is something competely different ? 
do you know how to set it during compile time ?
Regards
Jan

**Comment by frodrigo** [comment]
Yes here https://github.com/rodo/osrm-profiles/blob/master/truck.lua#L132-L145
or here https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L42-L47

**Comment by johnnyGor** [comment]
Thank you very much
