### ISSUE TITLE
wrong node number in route

### ISSUE THREAD

**Issue by milos106** [Project-OSRM/osrm-backend#6016]
I would like to note you for a small mistake in your api.
When you run your api:
http://router.project-osrm.org/route/v1/driving/14.89857049,50.4026181;14.9366725,50.3229582?alternatives=false&annotations=nodes

All nodes are right from the same area in Czech Republic, but node nr.34819412 is from Norway!!!

I've treated it in my application, but it can be unpleasantly for others...

**Comment by danpat** [comment]
This looks like an overflow bug - we've got the coordinate correct here, at lon,lat 14.933584,50.327384 - the correct node is https://www.openstreetmap.org/node/8624754004

We're currently only allowing 33 bits for storing OSM node IDs - https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/include/extractor/packed_osm_ids.hpp#L14

8624754004 is 34 bits wide (1000000010000100110100110101010100 or 0x202134D54).  Looks like we need to bump up the hardcoded 33 value in packed_osm_ids if we want newly mapped regions to have correct annotations.

We support the full 64 bit number space during graph generation, so I don't think this will lead to weird routing errors, just incorrect node annotation values for newly mapped locations.
