### ISSUE TITLE
[Question] Table API execution time (even for small matrices)

### ISSUE THREAD

**Issue by aartigao** [Project-OSRM/osrm-backend#6018]
Hi there! I don't know if this is the right channel to ask questions but I haven't found another, so point me in the right direction if it isn't 🙏🏽 

First time trying the OSRM Backend project and I'm using the official Docker images to run `osrm-routed`. I've followed the instructions and created a France map with `Foot` profile and MLD. After that I start the Docker container with the following command:

```bash
docker run --rm -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld --max-table-size 10000 /data/france.osrm --mmap=0
```

I'm using Gatling to create some random 100x100 matrices for the Limoges area (77.45 km2), so the coordinates are relatively close (I'm not evaluating routes that traverse the whole France map, for example, if this has some performance penalty).

But the execution times seems a little bit high to me. For example, the following request required ~3.5s to complete:

```
[info] 24-04-2021 05:47:44 3603.25ms 172.17.0.1 - - 200 /table/v1/foot/1.28353,45.81275;1.23388,45.81145;1.25831,45.84524;1.21682,45.83512;1.28467,45.81650;1.26990,45.81306;1.22718,45.84415;1.24983,45.83207;1.25268,45.83984;1.22721,45.84695;1.27824,45.81372;1.28216,45.81816;1.24273,45.84115;1.26650,45.84055;1.22552,45.81053;1.24234,45.82363;1.24685,45.81925;1.23216,45.81874;1.22978,45.82071;1.23712,45.81705;1.23408,45.81830;1.27682,45.81653;1.25453,45.83343;1.28404,45.81604;1.22637,45.81175;1.27468,45.81584;1.22611,45.83248;1.25473,45.81328;1.24799,45.84095;1.21778,45.83039;1.28443,45.82261;1.28679,45.83018;1.28684,45.81833;1.27028,45.82570;1.24639,45.81359;1.24218,45.81040;1.28239,45.83853;1.23478,45.82176;1.25015,45.81762;1.27356,45.84845;1.24319,45.81749;1.25304,45.84516;1.25234,45.84445;1.26303,45.83522;1.26122,45.81156;1.26732,45.81384;1.24040,45.84766;1.23010,45.84946;1.27829,45.81598;1.24143,45.81424;1.28184,45.83044;1.28679,45.82794;1.25607,45.84597;1.25915,45.81708;1.25711,45.84065;1.22088,45.82306;1.28663,45.81143;1.27120,45.84045;1.27201,45.83961;1.22048,45.84827;1.26930,45.84607;1.27036,45.83022;1.21715,45.84569;1.23915,45.82696;1.28253,45.84977;1.27719,45.83935;1.28382,45.82860;1.25774,45.84514;1.25060,45.81986;1.24379,45.83713;1.23177,45.81656;1.25044,45.82030;1.28154,45.83187;1.28374,45.83166;1.24396,45.83455;1.23683,45.82379;1.24095,45.84238;1.23929,45.81956;1.27952,45.83075;1.25316,45.82357;1.25603,45.82163;1.23178,45.81920;1.22961,45.83988;1.23559,45.82036;1.25497,45.83934;1.25149,45.84709;1.22760,45.82874;1.24978,45.81480;1.27134,45.81860;1.25598,45.82945;1.27062,45.81831;1.24611,45.82657;1.21983,45.82145;1.28323,45.81696;1.23703,45.82953;1.23492,45.82997;1.27176,45.82877;1.24495,45.82357;1.27009,45.81989;1.23753,45.84725?skip_waypoints=false&annotations=duration,distance
```

And I suspect that I'm definitively doing something wrong because according to @danpat [comment](https://github.com/Project-OSRM/osrm-backend/issues/5704#issuecomment-609444444):

> I'll also note that it'd be worth simply experimenting. I've done quite a bit of benchmarking on various `table` sizes, and I can say that _route calculation_ doesn't really dominate the computation time until the matrices are quite large (like 10000x10000). Prior to that, the constant factor for each location (coordinate lookup in the spatial index) tend to dominate request times. A 10k x 10k table request is approximately 100,000,000 routes calculated, and it does that in about 8 seconds on my laptop. For a 1x10000 matrix, that's only, well, 10,000 routes calculated, so you can expect the route calculation part to only really contribute about 0.0008 seconds to the total response time. Note that OSRM _still_ has to do spatial lookups on the 10,000 coordinates, so that factor will likely dominate.

which is far beyond the results I'm getting locally (I don't even dare to try a 10k x 10k table)  😢 

From what I read, CH is faster, but MLD should handle this little matrices equally faster, isn't it?

For reference, here are my system specs:

```
Processor		: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Memory		        : 15968MB (14062MB used)
Machine Type		: Notebook
Operating System	: Ubuntu 20.04.2 LTS
User Name		: a.artigao (Alan Artigao Carreño)
Date/Time		: sáb 24 abr 2021 07:59:55
```

Any help will be much appreciated 🙏🏽

**Comment by mjjbell** [comment]
For `france-latest`, the OSRM routing graph structures for car and foot

| Profile      | Nodes         | Edges       |
|--------------|-----------------|----------------|
| foot          | 30,925,394 | 61,098,647  |
| car           | 16,707,316 | 30,381,040 |

And running your query on algorithm/profile permutations gives

| Algorithm | Profile | Time          |
| ------------- | ---------| -------------- |
|  MLD        | foot     |  0m2.581s |
|  MLD        | car      |  0m1.377s |
|  CH          | foot     |  0m0.226s |
|  CH          | car      |  0m0.089s |



So your result looks consistent with this. You'll get a ~10x+ improvement by switching to the CH algorithm if you can forgo the flexibility MLD provides.

Another point worth mentioning is that walking graphs are generally larger due to incorporating most roads - requests will be slower. Walking graphs might also have less of the properties (less hierarchical, uniform speed) that make CH routing graphs faster. This could explain why the `car` speed-up with CH is greater than `foot`.

> (I'm not evaluating routes that traverse the whole France map, for example, if this has some performance penalty).

If you're only interested in a sub-region, then yes there will be a performance penalty in the spatial lookup and the routing. The exact amount would require further benchmarking, but if you can get away with a smaller map region, it will only help.

**Comment by aartigao** [comment]
Ideally I would like to have OSRM instances by country/profile (and maybe, depending on future use cases, by algorithm too).

Glad to hear that my results are consistent 👍🏽 I'll definitively switch to CH, as the use case don't need at the moment the MLD features.

You said that there's a performance penalty for spatial lookup. I read somewhere that using `hints` can help with this. Is that a thing? Because the use case I'm trying to solve repeats a lot of locations and we ask over and over again for same locations (not exactly the same matrices, but similar). I'm asking because I tried the `hints` thing and didn't see a real improvement 🤷🏽

**Comment by mjjbell** [comment]
> You said that there's a performance penalty for spatial lookup. I read somewhere that using hints can help with this. Is that a thing?

Yes, hints allow you to reuse spatial lookups from previous requests. See danpat's [comment](https://github.com/Project-OSRM/osrm-backend/issues/5704#issuecomment-609476971) from the same thread, in particular under what conditions hints can be reused.
