### ISSUE TITLE
Unrouteable traffic light junction

### ISSUE THREAD

**Issue by zoharby** [Project-OSRM/osrm-backend#6021]
Hi,

We've encountered some unrouteable junctions in Columbus, Ohio, and can't figure out what causes the issue.
[An example](https://map.project-osrm.org/?z=17&center=39.957406%2C-82.999810&loc=39.958323%2C-82.999907&loc=39.959178%2C-83.000078&hl=en&alt=0&srv=0)

As soon as the route crosses the junction, the car mode routing will go around it and not route through the junction.
The node itself seems pretty normal:
https://www.openstreetmap.org/node/229953510

The same happens with other junctions in the vicinity (not all of them). 

Any help will be appreciated :)

**Comment by datendelphin** [comment]
The problems are the barriers: https://www.openstreetmap.org/node/5814495575
Mapped this way, they apply to both, the "sidewalk" way and the street.

None the less, I think barrier=kerb, kerb=lowered should be added to a whitelist for the car profile, maybe with a penalty. Most cars will be able to pass a lowered kerb.

**Comment by mjjbell** [comment]
A fix for kerb related issues like this was added to the default car profile in #5999

**Comment by datendelphin** [comment]
Ah, time to synchronize my stuff then, Thanks for the link

**Comment by zoharby** [comment]
Thanks for the details guys!
Since this is already resolved & merged, I'm closing the issue.

**Comment by datendelphin** [comment]
The fossgis routing sever, and therefore the demo map, now hast that profile change applied. You could check it

**Comment by zoharby** [comment]
Thanks! Indeed works as expected now
