### ISSUE TITLE
Penalty for 'winding roads'

### ISSUE THREAD

**Issue by datwelk** [Project-OSRM/osrm-backend#6023]
In the standard car profile, a turn penalty is implemented which in part relies on the turn angle. If I understand things correctly, a turn could only occur at intersections in OSRM terminology.

I am however interested in incurring a delay at nodes that connect two (routable) segments, for which the angle between those segments exceeds a certain number of degrees. For example, in the image attached below, there are four 90 degree turns towards the end of the suggested route, which due to obvious reasons are not qualified as a turn and as such do not incur a delay. 

I'm looking for suggestions as to what would be the best way to implement this. Thanks in advance!

<img width="922" alt="image" src="https://user-images.githubusercontent.com/1571141/115999535-73499880-a5ec-11eb-97d3-f7ad76d46355.png">

**Comment by datwelk** [comment]
One possible solution I can think of is check the angle between the edges in the graph_compressor: if it exceeds a certain number of degrees, add an artificial turn and don't collapse the edges. Not sure however is this has a severe impact on performance.

**Comment by frodrigo** [comment]
Ne need to split the edge, just add extra penalty to the segment.

This part already compute a penalty, but for turn
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L468

But, I am not sure about this. The sharp angle could be hard to drive, or bad map quality. As opposite the angle could well detailed in OSM and not see as sharp.

**Comment by datwelk** [comment]
Solved by calculating angle between u, v and w in the GraphCompressor for v nodes with 2 outgoing roads and depending on their angle, call into the lua scripting environment to assign the penalty. U is calculated depending on if forward_e1 is already compressed or not, if so we use its latest via node.
