### ISSUE TITLE
crossing=no is ignored

### ISSUE THREAD

**Issue by Dimitar5555** [Project-OSRM/osrm-backend#6025]
I've noticed that ``crossing=no`` is ignored when routing. This problem can be seen [here](https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=42.68796%2C23.31341%3B42.68935%2C23.31144#map=18/42.68869/23.31248). The router suggests to cross the street at that node while it should use the crossing that is a few meters to the side.

**Comment by datendelphin** [comment]
the wiki page on crossing=no is a bit sparse.
https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dno
https://wiki.openstreetmap.org/wiki/Key:crossing#Approved_tags
How is it supposed to work? Only applies to pedestrians? There are two roads crossing, how is it determined to which road it applies?

**Comment by Dimitar5555** [comment]
It should apply to pedestrians and cyclists. In my opinion it should apply to roads with sidewalk=separate. In other words you can cross the road that doesn't have separate sidewalk. If both roads don't have separate sidewalks then crossing in any direction at this point shouldn't be allowed. 

Note: this is my opinion and my way of thinking. There could be other opinions on this matter.

**Comment by matkoniecz** [comment]
Note that it is relevant only when some access tagging is missing. Part of https://www.openstreetmap.org/way/157694512#map=19/42.68843/23.31378 should have `foot=use_sidepath`

**Comment by SiarheiFedartsou** [comment]
Stale.
