### ISSUE TITLE
Changing places names in osrm database?

### ISSUE THREAD

**Issue by KaSakee** [Project-OSRM/osrm-backend#6028]
I have a full database of places names and all of them is up to date
I'm thinking if I can change the names that existed on the OSRM database to be used instead of the current names
For example, I have latitude longitude with an up-to-date name.
I need to get the id of the place, And then change it to the new name?
Any idea of how is this possible?

**Comment by danpat** [comment]
OSRM only stores _road names_, not place names.  The road names data structure is built during graph extraction and string offsets are calculated there.  There would be no easy way to modify values in that structure without re-building it and updating all the roads that reference names.  In addition, the name store only stores unique names - that means roads in different parts of the planet with the same name will share an entry - if you modify that entry, you'll change the name for two possibly unrelated roads.

So I would say no, there's no good way to update the names used by OSRM without re-building the data.

You'll need to figure out a way to modify the `.osm` or `.pbf` file you input to OSRM before processing it.

**Comment by KaSakee** [comment]
Thank you for answering make sense <3
