### ISSUE TITLE
In the Netherlands, OSRM should allow pedestrians (foot.lua) to traverse cycling roads.

### ISSUE THREAD

**Issue by martmists-gh** [Project-OSRM/osrm-backend#6029]
I was informed not to add foot=yes to cycling roads where this is allowed when editing the map data, hence why it's an issue on OSRM's implementation instead.

**Comment by jcoupey** [comment]
@martmists-gh could you share an example (maybe a link to a routing result from http://map.project-osrm.org/) that would showcase a typical wrong routing behavior with regard to this situation?

**Comment by martmists-gh** [comment]
Hm, it seems to work fine there, but using the same data on our self-hosted instance seems to fail on various routes, despite setting it to foot.lua
Is there any way for us to debug this?

**Comment by datendelphin** [comment]
The bike and foot profile there are quite different. See https://github.com/fossgis-routing-server/cbf-routing-profiles/ for what is currently used by the server behind [map.project-osrm.org](http://map.project-osrm.org/)

**Comment by martmists-gh** [comment]
Using the foot.lua from that repo seems to work fine.
