### ISSUE TITLE
`exclude` parameter not currently working in request url

### ISSUE THREAD

**Issue by EAweblog** [Project-OSRM/osrm-backend#6031]
Any time the exclude parameter is used in the request url in any manner it returns response 400 with message "Exclude flag combination is not supported" and code "InvalidValue". Whether exclude is given a value of multiple comma-separated values or just a single value.

As an example, the example url in the docs:
http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407?exclude=motorway

Here is the response when opened in browser:
{"message":"Exclude flag combination is not supported.","code":"InvalidValue"}

Also, related, how can I find a list of possible classes to exclude? I see there is "motorway" and "toll" and possibly "ferry" and possibly "restricted". Where can I see a list of all classes?

**Comment by datendelphin** [comment]
The server behind router.project-osrm.org can no longer support excludes due to capacity, sorry.
