### ISSUE TITLE
installation of OSRM-Backend

### ISSUE THREAD

**Issue by courageuse** [Project-OSRM/osrm-backend#6032]
Hello,
I am training to install OSRM-backend under ubuntu which is installed under the virtualbox and for its installation I followed this tutorial: https://www.yatis.io/how-to-install-osrm-and-nominatim- on-ubuntu-16-02-google-maps-alternative /
at the level of "Installing OSRM" once I typed the following command: osrm-extract data / map.osm.pbf -p osrm-backend / profiles / car.lua

I got as an error message:

[info] parsed O location-dependent features with 0 GeoJSON polygons
[info] using script osrm-backend/profiles/car.lua
[info] Input file: algeria-latest.osm.pbf
[info] Profiles: car.lua
[info] Threads: 1
[info]: parsing in progress ..
[info] input file generated by osmium/1/8.0
[info] timestamp: 2021-05-09T20:21:28Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info] motorcar
[info] motor_vehicle
[info] vehicle
[info] Paese relations ...
terminate called after throwing an instance of 'osmium :: pbf_error'
what (): PBF error: truncated data (EOF encountered)
abound (core dumped) 

that someone can help me solve it really it's urgent and thanks in advance

**Comment by nilsnolde** [comment]
Please be careful when asking for help in dedicated channels such as project-specific issue trackers. We assume you have _basic_ familiarity with OSM and Linux commands. I’d recommend you ask for help in other channels, such as coworkers or friends. Not even stackoverflow.com would respond kindly to your lack of research. Respect other people’s time, that’s really important or you’ll end up getting blocked from opening issues. It’s friendly advice at this point, please don’t take it the wrong way.

**Comment by courageuse** [comment]
thank you mister nilsnolde   for your advice
