### ISSUE TITLE
display of distance and time results at the backend osrm 

### ISSUE THREAD

**Issue by courageuse** [Project-OSRM/osrm-backend#6037]
Hello,
I managed to install osrm-backend and osrm-frontend under docker under virtualbox and in the same way I managed to make the connection between them.
the question I am currently asking is that the result relating to the distance and the time is given only at the level of the osrm-frontend while at the level of the backend I will have no results relating to the distance and the time which is the opposite when using the graphhopper route calculator in which the result relating to distance and time is given in both frontend and backend.
can anyone help me solve it?
and thanks in advance.

**Comment by danpat** [comment]
@courageuse I'm not sure what "while at the level of the backend I will have no results relating to the distance and the time" means.

Does graphhopper log the distance/time of each route as it's calculated?  Are you expecting OSRM to include the time/distance in the logged output lines in `osrm-routed`?  Why is that useful?

**Comment by datendelphin** [comment]
Have a look at http://project-osrm.org/docs/v5.24.0/api/#route-object there you find the distance and duration. Example back-end call: https://routing.openstreetmap.de/routed-bike/route/v1/driving/10.6787109375,50.254229882306205;7.437744140625,49.76707407366792

**Comment by courageuse** [comment]
Hello,

thank you for answering me Mr danpat yes it is useful for me to have these results at the level of the OSRM-backend because I am going to make a comparison with those obtained by the route calculation router: graphhopper

**Comment by datendelphin** [comment]
Hi @courageuse 
I am unsure if your problem is solved now or not. It sounds like you need some sort of software anyway that will do the comparison. You can just have that thing make the queries to osrm and graphhopper via http. And the responses will contain all the info you need to compare the two. No?

**Comment by jcoupey** [comment]
@courageuse are you aware that [route objects](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#route-object) in backend responses have a `duration` and `distance` key?

**Comment by nilsnolde** [comment]
Use cases like these (comparing different providers) are the reason why we created https://github.com/gis-ops/routing-py, though with all the recent changes in graphhopper it might be slightly outdated.

**Comment by danpat** [comment]
@courageuse as @jcoupey pointed out, you can trivially obtain the distance/duration of a route by parsing the JSON response from the OSRM backend service:

Example using `curl` and `jq` from the command-line:
```
$ curl http://localhost:5000/route/v1/car/-75.09,40.80;-74.17,40.81 | jq '.routes[0].duration'
983.2
```

Here, 983.2 is the number of seconds from -75.09,40.80 to -74.17,40.81.

I don't think there is anything we need to change with OSRM to support this case, it already does everything it needs to.

**Comment by courageuse** [comment]
Hello,
thanks to all for answering me.

when i run the osrm-backend from the command line : sudo docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed --algorithm mld /data/algeria-latest.osm

and the osrm--frontend from the command line : sudo docker run -p 9966:9966 osrm/osrm-frontend
and i type the command line: localhost:9966 in the browser.
after i type the coordinates of the start and end point in the osrm-frontend, i will have the following response displayed in the window relating to the osrm-backend: in witch i would not have the display distance and duration.
the response is : [info] 25-05-2021 08:55:37 34.9636ms 172.17.0.1 http://localhost:9966/ Mozilla/5.0(X11;Ubuntu;Linuxx86_64;rv:88.0)Gecko/20100101Firefox/88.0 200 /route/v1/driving/0.1379568,35.394081;-0.2874884,27.8733807?overview=false&alternatives=true&steps=true&hints=kKMfgP___38AAAAAJAAAAB4AAAAAAAAA4zbjPd9cxUEqmqhBAAAAAAAAAAAkAAAAHgAAAAAAAABeAQAAmhgCAG4RHALlGgIAIRIcAgEAPxUCLYx4;
Who can help me in this case and thanks in advance.

**Comment by courageuse** [comment]
following your exemple Mr Danpat  i typed the following line into the osrm-backend :
curl http://localhost:5000/route/v1/car/35.711953,-0.635834;35.854553,-0.310364 | jq '.routes[0].duration'
and i got the following message :
curl: (7) Failed to connect to localhost port 5000: Connexion refusée
35.854553,-0.310364 : commande introuvable
what can i do now.

**Comment by danpat** [comment]
@courageuse The message:

> Failed to connect to localhost port 5000: Connexion refusée

means that `curl` cannot connect to `osrm-backend`.  Is the `osrm-backend` container still running when you execute that command?  Are you executing that command from your container host, or inside one of your containers?

When you run `docker run -t -i -p 5000:5000 ...` it means that port 5000 is bound on the host and forwarded to the same port inside your container.  As long as the `osrm-backend` container is running, you should be able to execute the `curl` command from your host and request a route.

You can also try pasting "http://localhost:5000/route/v1/car/35.711953,-0.635834;35.854553,-0.310364" into your browser window.

**Comment by courageuse** [comment]
I put in the browser what you told me to paste : http://localhost:5000/route/v1/car/35.711953,-0.635834;35.854553,-0.310364, while I received the following result :


code | "Ok"
-- | --
routes | &nbsp;
0 | &nbsp;
geometry | "}yplCouuiA??"
legs | &nbsp;
0 | &nbsp;
steps | []
distance | 0
duration | 0
summary | ""
weight | 0
distance | 0
duration | 0
weight_name | "routability"
weight | 0
waypoints | &nbsp;
0 | &nbsp;
hint | "SZ0DgADEA4AAAAAARAAAAAAAAABWaQIAAAAAAKXfOkIAAAAArVjWRwAAAABEAAAAAAAAAFZpAgAOBQCAC8a6ANnkYQHR6yACRkz2_wAAXxUCLYx4"
distance | 3676229.279511
name | ""
location | &nbsp;
0 | 12.240395
1 | 23.192793
1 | &nbsp;
hint | "SZ0DgADEA4AAAAAARAAAAAAAAABWaQIAAAAAAKXfOkIAAAAArVjWRwAAAABEAAAAAAAAAFZpAgAOBQCAC8a6ANnkYQFfHCMCpEP7_wAAXxUCLYx4"
distance | 3660593.104264
name | ""
location | &nbsp;
0 | 12.240395
1 | 23.192793












can you make me understand what I received and thank you in advance

**Comment by danpat** [comment]
@courageuse I cannot make you understand - but I can point you to the documentation for this JSON data:

  http://project-osrm.org/docs/v5.24.0/api/#result-objects
