### ISSUE TITLE
OSRM: Getting output in Flatbuffers format for route service

### ISSUE THREAD

**Issue by mster3313** [Project-OSRM/osrm-backend#6038]
I hosted osrm v5.24.0 on my local machine using a dataset preprocessed with CH (Contraction Hierarchies) pipeline. And I need to get the output of route response in flatbuffers format. But I couldn't find the correct query for that.

Request I am using (Postman):
`/route/v1/driving/73.14568712144677,-0.6875788801118562;73.13504135080412,-0.682499947378062?overview=full&alternatives=false&steps=false&geometries=geojson&format=flatbuffers`

Response I get:
```
{
    "message": "Query string malformed close to position 156",
    "code": "InvalidQuery"
}
```
Can anyone help me on this matter ?

**Comment by danpat** [comment]
The syntax is not `&format=flatbuffers` - you need to append `.flatbuffers` before the `?` mark.

http://project-osrm.org/docs/v5.24.0/api/#general-options

> GET /{service}/{version}/{profile}/{coordinates}[.{format}]?option=value&option=value

where `.{format}` can be `.json` or `.flatbuffers`.

**Comment by mster3313** [comment]
Thanks for the response. Got it resolved
