### ISSUE TITLE
description of unnamed ways - and how to translate

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#604]
for bike routing, many routable ways does not have a name. it's very useful to at least use the type of way (highway tag) to describe the way.

however, translating this in the frontend can be awkward.

you can look for specific strings like 'cycleway', 'service', etc in the name field of an instruction and replace them with a translated string. or make up a escape pattern, like "[cycleway]" or "highway:cycleway" and look for that.

this should work for most practical cases. but a cleaner solution would be have a separate flag that indicates whether you're passing a name or other tags. or use 'name: ....' for named ways.

**Comment by daniel-j-h** [comment]
Superseded by https://github.com/Project-OSRM/osrm-backend/issues/2452. By now we expose name, ref, destination (and pronunciation which does not help much here :P). Closing in favor of https://github.com/Project-OSRM/osrm-backend/issues/2452.
