### ISSUE TITLE
Turn off an auto-detection of a nearest building in OSRM

### ISSUE THREAD

**Issue by Wh1teStr1pe** [Project-OSRM/osrm-backend#6041]
Can you tell me please how to turn off an auto-detection of a nearest building? It happens on demo maps while putting there coordinates, the same thing happens while using API or a server locally. For example, when I use google maps and put there coordinates, route starts exactly from the point which relates to coordinates. Can I turn off this option in OSRM?

**Comment by frodrigo** [comment]
There is no building in OSRM.
The start, end and via points are projected to the road network.
