### ISSUE TITLE
GEOJSON to string Conversion

### ISSUE THREAD

**Issue by mster429** [Project-OSRM/osrm-backend#6042]
Hi,
I am planning to use this c wrapper [libosrmc](https://github.com/daniel-j-h/libosrmc) for one of my go applications. I need to get the geojson of the route,table responses. For that I have added this new function inside the c wrapper.

```
char* osrmc_route_response_geom(osrmc_route_response_t response, osrmc_error_t* error) try {
  auto* response_typed = reinterpret_cast<osrm::json::Object*>(response);

  auto& routes = response_typed->values["routes"].get<osrm::json::Array>();
  auto& route = routes.values.at(0).get<osrm::json::Object>();

  const auto geom = route.values["geometry"].get<osrm::json::String>().value;

  char* geom_string = (char*) malloc(sizeof(char) * geom.length() + 1);
  strcpy(geom_string, geom.c_str()); 
  return geom_string;

} catch (const std::exception& e) {
  osrmc_error_from_exception(e, error);
  return NULL;
}
```

Issue I am facing is when I use this function with `geometries=geojson` and `overview=full` it returns a segmentation fault. But when using `geometries=polyline` and `overview=full` it works fine. Any help in resolving this issue appreciated. I cant understand what is going wrong here and also I am not good at c++ programming. Thanks

**Comment by mjjbell** [comment]
The geojson geometry will be returned as a `util::json::Object`. 

https://github.com/Project-OSRM/osrm-backend/blob/ec36319232f6b6558080c5586d21fc0bd150de44/include/engine/api/json_factory.hpp#L64-L68

There's also a suggestion for how to deal with values containing different types

https://github.com/Project-OSRM/osrm-backend/blob/ec36319232f6b6558080c5586d21fc0bd150de44/include/util/json_container.hpp#L47-L62

**Comment by mster429** [comment]
Thanks it may be the reason. I will look in to this.

**Comment by mjjbell** [comment]
@mster429 it depends on what you need from the response. 

You can either convert the response to a C object that you can access from Go, or create some wrapper functions like [this](https://github.com/daniel-j-h/libosrmc/blob/38e6af24c0389854eea8065235e626b608ff8b32/libosrmc/osrmc.cc#L155) to encapsulate the response.

For the specific issue of the seg fault, you need to change the type variant selection to be
```
  const auto geom = route.values["geometry"].get<util::json::Object>();
```

**Comment by mster429** [comment]
Thanks @mjjbell . Really appreciate your help on this.

**Comment by mster429** [comment]
Hi,
I went through the node bindings on how to convert the variant type to a string. I'm little bit confused on one thing. Before rendering the variant object to json string there is an additional `ParseResult(status, json_result)` function. What does it actually do ?
https://github.com/Project-OSRM/osrm-backend/blob/f7478ba80f04ee6777556661f93edff5bef85c90/src/nodejs/node_osrm.cpp#L152-L165

**Comment by mjjbell** [comment]
@mster429 I'm not too familiar with the code, but it looks like `ParseResult` strips the `code` and `message` keys as defined in the [HTTP docs](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#code) from the result object and does some exception handling.

You certainly don't _need_ to do this for the purposes of serializing the result to a string, but it's an indication of the type of error handling you might need to do in your own project.

**Comment by danpat** [comment]
The `renderJSONToBuffer` parameter for functions in the node bindings is an optimization for situations where you're dealing with large responses (e.g. very large matrix results, like 10,000 x 10,000) which can return hundreds of megabytes of serialized JSON data.

Converting millions of small V8 objects between OSRM's naive `osrm::json::Object` struct into V8's native objects becomes a pretty major bottleneck when responses are large.  It's actually faster (at least was last time I checked) to have the OSRM node bindings return a JSON string (OSRM serializes `osrm::json::Object` and returns a `v8::Buffer` (or whatever the class is), then parse using `JSON.parse()` in javascript than it is to pass all the little objects over the `nan` binding interface.

**Comment by mster429** [comment]
Thanks @mjjbell , @danpat for your explanations. My concern is not to output the v8 object. I just use a c wrapper to serialize the native object to json string and use it in my go application. I think this ParseResult() func won’t be necessary for the purpose according to your comments. Thanks for your help.
