### ISSUE TITLE
About nodejs with deprecated osrm package

### ISSUE THREAD

**Issue by KaSakee** [Project-OSRM/osrm-backend#6043]
Hey guys, How do you think I can get the newest OSRM features to work with node.js exactly like the deprecated one?
Do you think I can do that if yes any ideas about how?
Thank you so much

**Comment by danpat** [comment]
@KaSakee I'm sorry, you're going to have to supply some more detail.  What version do you have currently that is not a simple update?  What problems are you seeing when you try?

**Comment by KaSakee** [comment]
I wanted to use the new OSRM with Node.JS Like this https://github.com/Project-OSRM/node-osrm
As npm package, Inside the current server directly without any additional servers

**Comment by danpat** [comment]
@KaSakee we just moved the code into the main `osrm-backend` repo.  All you need to do is `npm install osrm` to use it.

Example here:

https://github.com/Project-OSRM/osrm-backend/blob/master/example/example.js

**Comment by KaSakee** [comment]
Wow, thank you so much! sorry I thought OSRM dopped support for it thanks!

**Comment by KaSakee** [comment]
Another question I'm sorry, I'm trying to use annotations = "speed" and I get an error: this 'annotations' param is not supported, Is there any problem? because I use the normal OSRM server it works is the node.js version different? and is there any way I get the speed with the steps?

**Comment by KaSakee** [comment]
Forgive me I was reading the code finally I discovered it has to be an Array of strings ["speed"] instead of "speed alone" thanks and sorry for bothering you! <3
