### ISSUE TITLE
OSRM for large distance, duration matrices

### ISSUE THREAD

**Issue by Deepak3994** [Project-OSRM/osrm-backend#6046]
Hi,

I am trying to query **500 location** (source to destination the matrix will be 500*500), but I get **status 400 error**. I have the --max-table-size set to 10,000 ryt now and which is running on **GCP instance** (memory, storage is not an issue).

Can anyone help me here to know where exactly I need to check into to resolve this issue. In future I will be needing to query a very large distance matrix maybe 1000*1000.

Kindly help.

**Comment by danpat** [comment]
There will be some text in the response - you should print it out and take a look at it what it says.  My guess would be that perhaps your client is truncating the URL length leading to an invalid URL.  The 400 response class typically indicates a mal-formed request.

I often use `curl` on the command line to request large matrices up to 10,000 x 10,000 without an issue.

**Comment by Deepak3994** [comment]
@danpat Hi get below message,

data:
      { message: 'Query string malformed close to position 15549',
        code: 'InvalidQuery' } }

**Comment by TimMcCauley** [comment]
@Deepak3994 which is telling you what is wrong I would say. Can you share your request via a gist?

**Comment by danpat** [comment]
@Deepak3994 That message is telling you that at character position 15549 in your request, something is invalid - likely an unexpected character, or suddenly terminated value.  Open up the URL in a text editor and go to position 15549 along it (most text editors can tell you which column you are on) and take a look and see if something looks strange.

**Comment by Deepak3994** [comment]
Yes, It was issue with the data format at few rows...

Thank you @danpat @TimMcCauley
