### ISSUE TITLE
libosrm c++ integration help

### ISSUE THREAD

**Issue by komalbb** [Project-OSRM/osrm-backend#6047]
Hi All,

I have build orsm-backend 
cmake -S . -DBUILD_SHARED_LIBS=ON -B build. // cmake version 3.20.3
cd build && make orsm

After that copy the libosrm.so to my project under lib folder

Then I have ran the following;  I followed similar steps with google or tools; libortools.so Was sufficient in linking. 
Can some help what else needs to be done and if possible share how to link lib/libosrm.so to my main project cMakelists.txt

Error:
[BBVRouting]: g++ main.cpp -losrm -Llib
In file included from /usr/local/include/osrm/match_parameters.hpp:31:0,
                 from main.cpp:1:
/usr/local/include/osrm/engine/api/match_parameters.hpp:31:10: fatal error: engine/api/route_parameters.hpp: No such file or directory
 #include "engine/api/route_parameters.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by datendelphin** [comment]
You either need to copy the header files into your directory, or better add an include path with `-I /path/to/your/osrm/header/dir` in the gcc compilation line. For cmake see include_directories which should do that

**Comment by komalbb** [comment]
@datendelphin thanks.

@datendelphin , i want to integrate libosrm with my golang project. I am new to this bindings. Any pointers would be helpful

**Comment by komalbb** [comment]
@datendelphin I have also tried copying the entire include directory of osrm-backed to my include folder. 
Still flat buffers issue is coming;

My lib folder has libosrm.so file. 

[BBVRouting]: g++ main.cpp -Iinclude -Llib -losrm
In file included from include/osrm/osrm.hpp:31:0,
                 from main.cpp:10:
include/engine/api/base_result.hpp:4:10: fatal error: flatbuffers/flatbuffers.h: No such file or directory
 #include <flatbuffers/flatbuffers.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[BBVRouting]:
