### ISSUE TITLE
How to Implement in angular using leaflet ?

### ISSUE THREAD

**Issue by pranami007** [Project-OSRM/osrm-backend#6052]

**Comment by jcoupey** [comment]
If this is about using OSRM from leaflet, you probably want to give a go at http://www.liedman.net/leaflet-routing-machine/ which is used under the hood by the `osrm-frontend` project.

How to include that in an angular project is beyond the scope of the core OSRM repo but you'll easily find tutorials that cover using leaflet with angular.
