### ISSUE TITLE
URL malformed : {"message":"URL string malformed close to position 341: \"Cim\/ts\"","code":"InvalidUrl"}

### ISSUE THREAD

**Issue by kk2491** [Project-OSRM/osrm-backend#6053]
Hi All,

I am using table service to get the duration and distance matrix for set of locations. I used google polyline to generate the URL to query the OSRM. 

Getting the below error in few cases. 

One of the instance is given below:  
```
http://serverip/table/v1/driving/polyline(a%7DdeGrup%60Onw_@qzmC%7Bty@xq_@prcAa%60hCwxS~%7DfJ_yGs~_Cxxe@cjdC%7Cf[lzAnkhDp_BqnaD%7DcpAomrAnyf@nkwCbhgAwbxC%7Dhc@plhBnmcAmfoAymE%7BvN%7BsuBx_lFdaF%7DkuFrnsFxtj@%7BvgHz~vAmel@kuvAvrrIjz~@_~vF~kzDjCran@znmBifwCnddCyotAusr@kckBd%7D%7BAzczCg%7CkBjuf@idJhbs@jovClAouuAixtBnVdnmAko%60ChtIpit@cdkEder@_vD_vpBlloCpzvAqzmEelDjozDmyrFaz%60BxfyF%7CqqAcdaCim/tsJnbw@hcXiB%7CFfbKabi@_fFfvKaxC~s/ipIg%60JqaNqpYKpB)?annotations=distance,duration
```

Programming language used: NodeJs. 

I have 2 questions.  
1. How would I solve the above error?
2. Is there any npm packages for osrm?

Any help would be much appreciated.

Thank you,

**Comment by danpat** [comment]
You've very likely got an escaping problem in your polyline string somewhere.  Polylines can include characters like `\` and backticks "`", so you need to pay close attention to how you're constructing the URL string and what escaping is happening along the way.

Did you try doing `npm install osrm` or searching npmjs.org for "osrm"?  We have a node module that's trivially easy to find.

**Comment by kk2491** [comment]
@danpat Thanks for your reply. 
For the first problem regarding the ```\```, I used the encodeURI() in nodeJs to generate the URLs. 

For the second question, I did find the ```osrm``` however I was bit confused about how I can use that to query remote osrm server to get the data. 

Thank you

**Comment by nilsnolde** [comment]
it's all included, not just a client: https://github.com/Project-OSRM/osrm-backend/blob/HEAD/docs/nodejs/api.md

**Comment by kk2491** [comment]
@danpat @nilsnolde Thanks for your replies. 
I was able to get the valid URLs by encoding the polyline URLs using [encodeURI()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI). 
This seems to be working fine. 

Thank you
