### ISSUE TITLE
Routing Error

### ISSUE THREAD

**Issue by xihnik** [Project-OSRM/osrm-backend#6061]
![image](https://user-images.githubusercontent.com/51298755/123102061-56d7aa00-d43d-11eb-9d63-2665cc4508a4.png)

**Comment by jcoupey** [comment]
@xihnik can you please provide some more context? You can't expect to get relevant feedback without explaining when this occurs, what you actually did or what you're trying to achieve.

**Comment by xihnik** [comment]
@jcoupey . I use a module for React called leaflet-routing-mashine (sort of like this) and just about an hour ago it stopped working.  After researching what exactly leads to the error, I found out that the request that goes to your demo site has stopped receiving a response from it.  As far as I understand you have a server.  The name of the demo site is indicated in the error logs (it is on the screen).

**Comment by jcoupey** [comment]
> I found out that the request that goes to your demo site has stopped receiving a response from it

That's not directly related to the core `osrm-backend` repo, you may have more luck reporting this to the demo server maintainers. Please check out https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server for more pointers. Also note that beside the usage policy, you're strongly advised to run your own OSRM stack if you need any uptime guarantee.

**Comment by datendelphin** [comment]
One of the processes crashed, leading to 503 responses (which does not have a CORS header, but it's not working anyway,)

**Comment by xihnik** [comment]
> > I found out that the request that goes to your demo site has stopped receiving a response from it
> 
> That's not directly related to the core `osrm-backend` repo, you may have more luck reporting this to the demo server maintainers (I just did). Please check out https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server for more pointers. Also note that beside the usage policy, you're strongly advised to run your own OSRM stack if you need any uptime guarantee.

I agree

**Comment by xihnik** [comment]
It works. Thanks to all
