### ISSUE TITLE
Weird driving directions / path generated in certain areas

### ISSUE THREAD

**Issue by aarzhou** [Project-OSRM/osrm-backend#6069]
I try to use OSRM to generate driving directions but it gives a weird result. I have checked the OSM data and I didn't see anything special there.

Can someone please help me find out whether this is an OSRM bug, or it is just a map issue that I can solve it by updating the OSM data.

I got the problem using version 5.25 built from source. But same problem can be directly reproduced on OSM website too. Here is an example:

![osm1](https://user-images.githubusercontent.com/3170768/124003018-707c7280-d9a4-11eb-9bd9-1d19cfbb070c.png)

I don't know why it does not just go straight and make a left turn at the end. The expected driving path can be generated using graphhopper though:

![osm2](https://user-images.githubusercontent.com/3170768/124003136-9570e580-d9a4-11eb-82ef-efc391aba32f.png)

Thanks a lot in advance!

**Comment by danpat** [comment]
@mjjbell There is a `no_u_turn` via-way restriction in place here - any chance this is a bug with your support for via-way restrictions?  I'm pretty sure you had a test case for this scenario.

**Comment by mjjbell** [comment]
@danpat this is a manifestation of an issue you pointed out in the [original PR](https://github.com/Project-OSRM/osrm-backend/pull/5907#issuecomment-748648815). 

The duplicated edges that make up restriction paths are not included in the R-tree, so they can't be waypoints. This is a problem here as the optimal path to the target is half-way through the u-turn restriction path, so it instead finds a path to the target that doesn't go through a duplicated edge.

I don't know if there's a quick fix for this unfortunately. After applying the hefty #5953, support for duplicate restriction edges as waypoints is possible with a relatively [small addition](https://github.com/mjjbell/osrm-backend/commit/5c8e7296a60b749fa0c26ad2e54d24c660229adc).

**Comment by mjjbell** [comment]
In case anyone has some suggestions, this is what OSRM is seeing in reduced form.

- Two edges are used to represent the target intersection. 
- Only some turns exist from/to the boulevard, shown in red.
- The blue edge is the duplicate that implements the restriction and prevents the u-turn. 
- The blue edge can not be a target for a route, so it's not possible to find a path via the one-way boulevard.

![via path bug](https://user-images.githubusercontent.com/1063186/124017122-42b41f80-d9de-11eb-93a3-c03b282ab493.png)

This is a single via-way restriction, so this issue pre-dates the multi-via PR, hence why I suspect there isn't an easy fix without supporting multiple waypoints at each input location.

**Comment by aarzhou** [comment]
Is there any way to bypass the issue by modifying the OSM data?

**Comment by mjjbell** [comment]
> Is there any way to bypass the issue by modifying the OSM data?

Only by removing the u-turn restriction, which isn't a good idea.

If you are already building from source, you can apply #5953 and https://github.com/mjjbell/osrm-backend/commit/5c8e7296a60b749fa0c26ad2e54d24c660229adc as a patch fix. 
Another report of the same issue [confirmed](https://github.com/Project-OSRM/osrm-backend/pull/5907#issuecomment-799230309) that this worked.
I've also been using these changes in my own instance without any issues.

**Comment by aarzhou** [comment]
@mjjbell ,

Thanks a lot for your reply.

Just want to confirm. I need two fixes mjjbell@3771e99 and mjjbell@5c8e729, right? 

And also, these two are from another repository, is there any difference? Can I just replicate these two changes to Project-OSRM I checked out, or I have to use mjjbell/osrm-backend?

Thanks again

**Comment by mjjbell** [comment]
> And also, these two are from another repository, is there any difference? 

It's just my personal fork of this repo. If you add it as a remote to your `Project-OSRM/osrm-backend` git directory, you should be able to cherry-pick those two commits over and make a build that fixes the issue.
