### ISSUE TITLE
Update RAM requirements

### ISSUE THREAD

**Issue by nilsnolde** [Project-OSRM/osrm-backend#6072]
Can someone who's regularly building planet files please update this section: https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements#pre-processing

A small table would be really cool, e.g. (dummy numbers)

|       07/2021, 58 GB PBF 	| CH     	| MLD    	|
|--------------	|--------	|--------	|
| Car profile  	| 286 GB 	| 257 GB 	|
| Foot profile 	| 325 GB 	| 299 GB 	|

That'd give a good guesstimate as to what's needed in terms of infrastructure.

**Comment by datendelphin** [comment]
I can't handle the full planet on a 256G machine, I need to split it into 3 regions. Maybe no one is currently processing the whole planet. Maybe some rough formula for input data size to needed ram could be derived

**Comment by nilsnolde** [comment]
> Maybe some rough formula for input data size to needed ram could be derived

that'd be cool. rough is enough, smth ~5 x PBF size for car & CH, with foot slightly more.

**Comment by merschformann** [comment]
I don't have a formula, but just ran extract+contract on the planet. I shared some details [here](https://github.com/Project-OSRM/osrm-backend/issues/6107#issuecomment-956290415). I hope it helps a bit as a reference. A full experiment as proposed above would indeed be great though.

Also: running OSRM on pre-built files seems to consume much less memory than what the peak in pre-processing the files requires.

**Comment by nilsnolde** [comment]
ha, just wanted to link your comment from the other issue. thanks for sharing, that's super useful. the "formula" is just OSM File Size / OSM planet size * your RAM findings. that definitely gets one the right ballpark of needed infrastructure for less than planet sized extracts, should be a reasonably linear relationship for the most part.

if no one else jumps at it, I can update the wiki (just recently discovered they're editable by everyone per default, feels kinds weird..)

**Comment by merschformann** [comment]
Yep. Judging based on observations of smaller files we experimented with, the relationship seems pretty linear indeed. :relaxed:

**Comment by merschformann** [comment]
@nilsnolde I did another run today for moving to the latest OSRM version (it fixed an issue we had with concurrent requests) and collected more details this time. I put all details [here](https://github.com/merschformann/random/tree/main/content/plots/osrm) (including the original log, summary, interactive plot, etc.). I hope this can be useful to you and/or others. :relaxed:

**Comment by datendelphin** [comment]
I updated the [requirements page](https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements#pre-processing) with some measurements of mine. I got a little bit higher than @merschformann, I think because I include tracks with grade1 and 2 in the graph.
