### ISSUE TITLE
Installation of npm osrm wrapper fails because OSRM binary not found for download

### ISSUE THREAD

**Issue by FlorianSeidelAWS** [Project-OSRM/osrm-backend#6073]
npm install osrm

...
http GET https://github.com/Project-OSRM/osrm-backend/releases/download/v5.25.0/node_osrm-v5.25.0-node-v88-darwin-x64-Release.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.25.0/node_osrm-v5.25.0-node-v88-darwin-x64-Release.tar.gz 
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.25.0/node_osrm-v5.25.0-node-v88-darwin-x64-Release.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /Users/flseidel/Projects/test-run-blog/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR! node-pre-gyp ERR! System Darwin 19.6.0
npm ERR! node-pre-gyp ERR! command "/usr/local/Cellar/node/15.11.0/bin/node" "/Users/flseidel/Projects/test-run-blog/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
npm ERR! node-pre-gyp ERR! cwd /Users/flseidel/Projects/test-run-blog/node_modules/osrm
npm ERR! node-pre-gyp ERR! node -v v15.11.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
npm ERR! node-pre-gyp ERR! not ok

**Comment by mjjbell** [comment]
The latest OSRM release does not have [pre-built binaries](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.25.0) for Node 15. Currently supported are the last three `LTS` releases (10, 12, 14) and `Current` (16). If you need an OSRM package for Node 15, you'll need to [build from source](https://github.com/Project-OSRM/osrm-backend#using-the-nodejs-bindings).

**Comment by FlorianSeidelAWS** [comment]
Upgrading to Node 16 solved it. Thanks!
