### ISSUE TITLE
How does OSRM find adjacent ways?

### ISSUE THREAD

**Issue by salilgupta1** [Project-OSRM/osrm-backend#6077]
I'm trying to figure out how to build an adjacency matrix with the list of OSRM ways that I have but I'm unsure how to do so. How does OSRM do it?

**Comment by danpat** [comment]
@salilgupta1 Can you provide a bit more detail about what you're trying to do?

What is an "adjacency matrix" in this context?  What is an "OSRM way"?  OSRM does not store way information, OSM ways are discarded during data pre-processing.

**Comment by salilgupta1** [comment]
hey @danpat we've basically taken OSM ways and overlayed them onto an embedded GoogleMaps interface in our UI and the OSM ways are clickable. The idea is that a user can click on a OSM way and view metadata about that specific entity. Since a highway is composed of many OSM ways we'd like the user to be able to click on a single way and the ways to the left and right of that way are also selected. In order to do that I need to know which ways are adjacent to each other. I'm unclear how OSRM is able to do route planning if it cannot know if two ways are next to each other. Does it discard the OSM way and just use the nodes that make up the way?

**Comment by danpat** [comment]
@salilgupta1 OSRM constructs a new graph that has "edges" and "nodes" at locations where choices need to be make.  The connectivity in this graph is derived from how the ways and nodes in the OSM data are made.  This doesn't map 1:1 to OSM's ways and nodes layout, although it is derived from it.  The ID of a way has no value for routing, so it's discarded during processing, which prevents us from linking back to the original OSM source data that generated an edge in the routing graph.

One possible workaround is to alter `car.lua` and set the `name` of each road to include the original OSM way ID value.  This will cause the OSRM routing graph to be more highly segmented, and when you generate a path with OSRM, you will see the consecutive way IDs in the `name` field in the output.  The main issue is that we sometimes suppress changes in name when maneuvers are considered "obvious" to a human - it's not intended for data analytics like you want, more for a human to follow instructions in the real world.

The one thing that OSRM does store that links directly back to OSM data is the _node_ IDs for each coordinate along a path.  Use the `annotations=nodes` API parameter and you will get back the sequences of OSM nodes that are traversed in order.  You would need a separate service/index outside OSRM to determine which ways each node belongs to.

**Comment by salilgupta1** [comment]
thank you @danpat! I'll fiddle with the `annotations=nodes` API param and mapping it back to ways

**Comment by shubham121297** [comment]
@salilgupta1 i am doing a project in which i need to paint all the edges of a route between any two points.Do u have any idea like how can i extract all the edges from osrm api?Thanks in advance.
