### ISSUE TITLE
Docker route faster than native exe under windows 10

### ISSUE THREAD

**Issue by vutle** [Project-OSRM/osrm-backend#6079]
Hi, I have tested running OSRM service offline using both docker and  windows exe build.
In my test, I round that docker is running faster than the native windows exe version?
Both using the same workflow:  extract  --> partition-->customize  --> route, using car profile, and  calling from python.

What could be the settings that makes docker perform faster than native windows exe version?  Is it the ram setting?

Thanks

**Comment by SiarheiFedartsou** [comment]
Stale.
