### ISSUE TITLE
File format description in wiki is wrong 

### ISSUE THREAD

**Issue by ekfriis** [Project-OSRM/osrm-backend#608]
I think the description of the .osrm file format is missing a byte corresponding to the "contraFlow" flag [1] in the wiki description:

https://github.com/DennisOSRM/Project-OSRM/wiki/OSRM-normalized-file-format 

There should be one more line after:

* **(bool (1 byte)):**  01 in case of accessRestricted; 00 otherwise

If someone more learned than me confirms this is true and I'm not just doing something dumb in my unpacking I can edit the wiki.

[1] https://github.com/DennisOSRM/Project-OSRM/blob/master/Extractor/ExtractionContainers.cpp#L256

**Comment by daniel-j-h** [comment]
Stale; closing here. I'll add a warning to the Wiki regarding the date of the description.
