### ISSUE TITLE
i want to generate all the edges between any two points but i think osrm doesnt have any api for that.is there an api for that?

### ISSUE THREAD

**Issue by shubham121297** [Project-OSRM/osrm-backend#6082]

**Comment by danpat** [comment]
Define what you mean by "edge"?  Exactly what data are you looking to get back from the API?

OSRM finds the minimum cost path across a graph between the points you supply, and can return the geographic shape of the path, along with the OSM node IDs for every coordinate along that path.

**Comment by shubham121297** [comment]
edge is like the small routes which constitute the route object. I think that's what is called route leg. And i want to extract the speed for each route leg so that when i click on a route leg in my application it can give me speed info about that leg.

**Comment by danpat** [comment]
@shubham121297 Have you read the documentation available at http://project-osrm.org/ ?  There is a description there of the API response and what it contains, and what options you have.  Please review that carefully and return here if anything is not clear.

**Comment by shubham121297** [comment]
actually i read that and what i understood is that the route api returns the annotations object which contains speed of each route step and if i want to get the speed of each route leg which constitutes of various route steps then i will not be able to get the speed directly from the api.Correct me if i have got something wrong.Thanks for your precious time.
I have attached annotations object ss.
![Screenshot (222)](https://user-images.githubusercontent.com/71139171/125912056-cf4ebb83-7fcf-4151-a9c4-caca51772426.png)

**Comment by shubham121297** [comment]
i understood it u can close it.
