### ISSUE TITLE
Generation of inefficient MLD partitions

### ISSUE THREAD

**Issue by mjjbell** [Project-OSRM/osrm-backend#6084]
## Issue

As [discovered](https://github.com/Project-OSRM/osrm-backend/pull/3645#issuecomment-876977956) by @zhudelong, the mapping from node-based edges to edge-based nodes (`osrm.cnbg_to_ebg`) does not include the duplicate nodes used to represent turn restrictions.

The MLD partitioner uses this mapping to assign nodes to a partition. Duplicate restriction nodes are not assigned, and end up in a special "invalid" partition.
https://github.com/Project-OSRM/osrm-backend/blob/f7478ba80f04ee6777556661f93edff5bef85c90/src/partitioner/partitioner.cpp#L102-L119

This special partition will break the spatial properties of the multi-level hierarchy - the partition and its super levels will have a large number of border nodes and very few internal paths between them. This will bloat the hierarchy and make queries slower due to reduced data locality.

This issue will have existed since via way restriction support was added in #4255, but will have become more prominent with the support of multi-via way restrictions in #5907.

## Fix
As `osrm.cnbg_to_ebg` is only used by the MLD partitioner, this can be fixed by simply including the duplicate restriction nodes in the mapping.

**Comment by zhudelong** [comment]
Nice work, cheers！
