### ISSUE TITLE
Difference between geometries=polyline6 and geometries=geojson

### ISSUE THREAD

**Issue by sampeters1** [Project-OSRM/osrm-backend#6086]
Hi I was wondering what the difference is between setting `geometries=polyline6` and `geometries=geojson`. I'm aware that both options have a higher coordinate precision than `geometries=polyline`. However, for very long queries I noticed that when I use `geometries=geojson`, the output sometimes doesn't seem complete (see below). Does that mean that for very long queries it is better to go with `polyline6`?

Small snippet:

```
      [4.930889, 52.393097],
      [4.930892, 52.393128],
      [4.9309, 52.393156],
      [4.930917, 52.393189],
      [4.930959, 52.393255],
      ...],
     'type': 'LineString'},
    'legs': [{'annotation': {'nodes': [8589765385,
        8589765386,
        969192,
        8589869861,
        8589869862,
```
etc.

**Comment by danpat** [comment]
OSRM will never emit the `...` thing you're seeing there.  That will be an artifact of whatever you're using to view the raw JSON response.  Look at the raw response text and it will contain the full array of coordinates.

**Comment by sampeters1** [comment]
Ok thanks for clarifying that up. And in terms of precision, do they both have the same coordinate precision?
