### ISSUE TITLE
add Lua version 5.4 & tbb@2021 support

### ISSUE THREAD

**Issue by robertsjchen** [Project-OSRM/osrm-backend#6087]
Hello, 

recently I tried to download & compile the entire project from my mac, I following those building instructions downloading dependency(boost, lua, tbb, etc) via brew, but the situation is, all dependency packages been downloaded latest by default, for example, as of today(Jul/2021), version of Lua is 5.4.3, version of tbb is 2021.3, cmake will fail with package can not found error. 

* In file "cmake/FindTBB.cmake", the hardcoded heading file "task_scheduler_init.h" been removed from tbb@2021:
```
find_path(TBB_INCLUDE_DIR
    tbb/task_scheduler_init.h
    HINTS ${TBB_INC_SEARCH_DIR} ENV CPATH
)
```
* In file "cmake/FindLua.cmake", the latest version of Lua been supported is 5.3(I added 5.4 locally fixed this issue):
```
function(_lua_set_version_vars)
    set(LUA_VERSIONS5 5.3 5.2 5.1 5.0)
    ...
```

Thanks
robert

**Comment by danpat** [comment]
You can try doing `cmake -DENABLE_MASON=ON ..` when you run `cmake` - this will download pre-built binaries for known-to-work dependencies, rather than using those available on your system or via homebrew.

Of course, a patch to upgrade the dependencies would also be welcome.

**Comment by mjjbell** [comment]
#5981 has been merged, which will fix the Lua 5.4 issue.

**Comment by robertsjchen** [comment]
thank you so much @mjjbell & @danpat !

**Comment by mjjbell** [comment]
For now, to continue building on a Mac, you'll need to install tbb@2020 and set a `TBB_INSTALL_DIR` environment variable to the install location (e.g. `/usr/local/opt/tbb@2020`), so that `FindTBB.cmake` can find it.
