### ISSUE TITLE
Question: is there a way to prevent waypoint to snap to a different road lane

### ISSUE THREAD

**Issue by slavanap** [Project-OSRM/osrm-backend#6095]
I.e. is there a way via supplying additional parameters to make second waypoint in the query to be projected to the same lane?
https://map.project-osrm.org/?z=18&center=40.902376%2C-74.090745&loc=40.902628%2C-74.090282&loc=40.902727%2C-74.090123&hl=en&alt=0&srv=0

**Comment by danpat** [comment]
You could try using the `match` feature - it will move waypoints around to find the "most likely" (aka shortest, considering all nearby snapping candidates).

The issue here is that `match` won't know whether to move the first or the second point - do _you_ know which is correct?
