### ISSUE TITLE
osrm returning a bi-directional snapped trip

### ISSUE THREAD

**Issue by grobins** [Project-OSRM/osrm-backend#6097]
I'm passing in a trip to a local osrm service

`localhost:5000/trip/v1/driving/175.7650,-40.31014;175.6343,-40.33699?overview=full&annotations=nodes`

This trip goes in one direction from A to B, so I'm expecting one geometry back from the service, but I get two

![image](https://user-images.githubusercontent.com/4343493/129137260-c271f299-9554-4ac5-a507-a3cd40c99483.png)

How can I force osrm to return the geometry from the first point to the second?

If I use the route service instead of the trip service, with the start and end location specified, it's great! I get one geometry.  But subsequent trips along the same roads return different geometries - i.e. they don't snap

![image](https://user-images.githubusercontent.com/4343493/129138292-d801da02-71ae-4dbc-b0cc-4d41011d1171.png)

**Comment by danpat** [comment]
By default, the `/trip` plugin returns a round-trip - it will return to the origin point, thus the extra leg.

Take a look at the `roundtrip`, `source` and `destination` options in the documentation here: http://project-osrm.org/docs/v5.24.0/api/#trip-service
