### ISSUE TITLE
Add a max weight parameter when calculation a Many-to-many matrix using table service 

### ISSUE THREAD

**Issue by sebgir** [Project-OSRM/osrm-backend#6098]
It would be great to have access to a "Max weight" parameter when computing many-to-many matrix on large maps.  If for example I don't want any leg to be larger than 500km, I don't need the values exceeding a weight of 500000 in my matrix.

A lot of computing power would be avoided and response would be faster. A null value would be returned in the distance/duration matrix.

**Comment by sebgir** [comment]
Thanks for your input, I checked and about 60% of my entries are "over-lengted".  I think gain would be significant.

I will do some benchmarking on my datasets and post my results here so everyone will be able to judge if it would be a relevant feature. I seen other routing engine with a similar parameter thought.

**Comment by sebgir** [comment]
I'm working on Canada's data with elements in my matrix exceeding 5000km.  I would aim a max distance parameter of 600km.

**Comment by danpat** [comment]
It's not strictly about the distance - it's about how many edges need to be traversed for the bidirectional search to meet.  Across much of Canada, the road network is very sparse, so the shortcuts will be very long and jump large distances with very few hops (aka not very expensive for OSRM to compute).  This is one of the reasons I'm not expecting to see a huge speedup.

**Comment by sebgir** [comment]
Your intuition were right, I cutted about 50% of my graph and I was only able to barely pull a 20% improvement in computing time.  On denser matrix I think the improvement will be marginal.  

I think I will close this discussion if will continue to think about it and if I find a real breakthrough I will create a new feature request. 

Thank for your help @danpat
