### ISSUE TITLE
Ferry segments have "pushing bike" mode in biking directions

### ISSUE THREAD

**Issue by noalevy** [Project-OSRM/osrm-backend#6099]
When using the bike profile, with no classes excluded, some routes include segments by ferry. However, the mode I see for these segments is "pushing bike", instead of "ferry". For example - a route from Berkeley, CA to San Francisco uses the ferry, but I wasn't able to find a way to know from the data that this is the case. For the driving profile, ferry mode is indicated correctly (as described here: https://github.com/Project-OSRM/osrm-backend/issues/283#issuecomment-266753482). Is there a way to include the correct mode in the response?

**Comment by SiarheiFedartsou** [comment]
Stale.
