### ISSUE TITLE
The router.project-osrm.org is returning a 502 bad gateway once in a while

### ISSUE THREAD

**Issue by williamrijksen** [Project-OSRM/osrm-backend#6102]
https://router.project-osrm.org/table/v1/driving/{coordinates}?annotations=distance,duration returns once in a while a 502.

How could I fix this?

**Comment by williamrijksen** [comment]
Same issue occurs here. https://routing.openstreetmap.de/ Might it be related?

**Comment by datendelphin** [comment]
That is the same server. There will be interruptions each time the routing graph is exchanged. But that is only a few minutes. There are lock ups from time to time in osrm. If that could be fixed, that would be great.

**Comment by williamrijksen** [comment]
@datendelphin thanks for the quick reply. It seems it occurs way more often than before. Is it caused by the same issue?

**Comment by datendelphin** [comment]
It depends on the load. Above 250 req/s it seems to be more likely to trigger the bug.

**Comment by mjjbell** [comment]
@datendelphin I've created PRs (#6112, #6113) to fix the `osrm-routed` issues I found a while back. I'm hoping they will help with some of these issues.
