### ISSUE TITLE
Travel time for highways in US far too long 

### ISSUE THREAD

**Issue by ppapasav** [Project-OSRM/osrm-backend#6103]
I'm redoing this entire question

I just processed the Colorado files to do some OSRM distance / driving time example

The issue I'm having is whether I test driving distance & Time on my own server or on the OSRM-Backed Server, on a very simple route on a Highway in Colorado (and many other examples), the times are way off from real-life and google maps.

1:45 for Google maps and 2:15+ with OSRM. I'd like to figure out where the contstraint is in the LUA file ... Is there a way to show debugging info if we use steps=true to see where the speed for that segment is being derived from? I've been seeing this on many routes nationwide with highways involved.

http://router.project-osrm.org/route/v1/driving/-103.69,39.26;-103.20,40.625?overview=false

Or show it with steps

http://router.project-osrm.org/route/v1/driving/-103.69,39.26;-103.20,40.625?overview=false&steps=true

Project OSRM Server: 
Duration: 7775.5: 129 minutes
Distance: 176308: 109.5 Miles

Local OSRM Server with latest build and included car.sua
Duration: 8311: 138 Minutes
Distance: 108.5 miles

Google:  https://www.google.com/maps/dir/'40.625,-103.20'/39.26,-103.69/@39.9403935,-104.1705795,9z/data=!3m1!4b1!4m7!4m6!1m3!2m2!1d-103.2!2d40.625!1m0!3e0
105 Minutes
110 Miles

---

I looked at the per-segment times and distances and they don't even come close to what the speed limit is for that road. I've tested this on many highways in the US and am seeing the same thing.

What is the best way to see what is restricting the segment speed so I can try to tweak the SUA file?

**Comment by TimMcCauley** [comment]
@ppapasav afaik these are the lua's used with the demo server, at least with these you should see the same results https://github.com/fossgis-routing-server/cbf-routing-profiles/

**Comment by jcoupey** [comment]
@ppapasav in order to easily browse per-segment speeds, you can use the debug view from the frontend, either locally or [on the demo server](https://routing.openstreetmap.de/debug/#16.15/40.62500/-103.20000).

Now in order to find out how the estimated speeds are computed, I'm afraid you'll have to dig into the lua profile logic. Your best starting point is to lookup the tags associated with the OSM way and see how they're used in the profile. Check out the `*speeds*` variables and the way they're used in e.g. `WayHandlers.speed` and `WayHandlers.maxspeed`.

**Comment by ppapasav** [comment]
I found something interesting in the .lua file 

speed_reduction = .8 - I changed this to 1.0 and the numbers are much closer to real life now. Every lua file I found has the .8 set and not quite sure why

Also adjusted some of the other speeds and I'm pretty close to where i need to be now

Thanks

**Comment by jcoupey** [comment]
Closing since you seem to have found what you needed to adjust.
