### ISSUE TITLE
All modes of transportation return the same results in python request

### ISSUE THREAD

**Issue by ZarahShibli** [Project-OSRM/osrm-backend#6104]
I tried to request route data between two points with the "Car" profile, but the response data is incorrect for the "Car" profile. I get the same results with "Car" and "Bicycle", which is illogical.

What is the solution to take into account the type of transportation?

![openmap_bicycle](https://user-images.githubusercontent.com/42017072/130446561-32a525a0-8e29-4eb4-98cc-7b5dbcfb5e03.png)
![openmap_car](https://user-images.githubusercontent.com/42017072/130446573-15e5f2c9-302d-4ca8-9521-b77cd22a2738.png)

**Comment by jcoupey** [comment]
By default the `profile` placeholder has no influence when using `osrm-routed` locally, so the result only depends on what profile what used to prepare the data prior to launching the server.

If you use the `routing.openstreetmap.de` entry point for the demo server, the requests are redirected to different OSRM instances:
- https://routing.openstreetmap.de/routed-foot/route/v1/driving/
- https://routing.openstreetmap.de/routed-car/route/v1/driving/
- https://routing.openstreetmap.de/routed-bike/route/v1/driving/

**Comment by ZarahShibli** [comment]
@jcoupey thanks for your comment.

I follow steps from this https://github.com/Project-OSRM/osrm-backend/issues/4941#issuecomment-440765542 to set up OSRM, using `gcc-states-latest.osm.pbf` and `profile =car.lua` and got this warning:

`[warn] Turn is a u turn but not classified as a u turn. Node ID: 2349826, O
SM link: http://www.openstreetmap.org/?mlat=25.2654&mlon=55.2912#map=19/25.2654/
55.2912`

This is the result after the setup is completed, all requests return the same response.
![image](https://user-images.githubusercontent.com/42017072/130630861-644258ce-56d7-40f9-87fb-d1bb877fd6b0.png)

**Comment by jcoupey** [comment]
My bet is you have your coordinates the wrong way around, OSRM expects lon,lat. In that case, requests with points outside your extract get snapped faaaaaaaaaar away to the nearest point on the border of your extract (here around [36.86, 31.64]).

**Comment by ZarahShibli** [comment]
I sent lat, lon. I fixed it as you said and it's working fine. 

Thank for your help @jcoupey
