### ISSUE TITLE
502 Bad Gateway using table/v1/driving

### ISSUE THREAD

**Issue by GISJohnECS** [Project-OSRM/osrm-backend#6105]
Currently getting a 502 Bad Gateway when making a request using the Table Service http://router.project-osrm.org/table/v1/driving. 

Wondering if the server is down? 
[Example Request](http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219)

**Comment by GISJohnECS** [comment]
I would like to add that everything appears to be working again!

In future is there anywhere I can look for server downtime/status?

Thanks

**Comment by jcoupey** [comment]
> In future is there anywhere I can look for server downtime/status?

AFAICT there is no public monitoring data available. Also note that in most situations you should not rely on the demo server but consider hosting your own stack, see [this page](https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server) for more.

Closing as solved.

**Comment by GISJohnECS** [comment]
Thank you!
