### ISSUE TITLE
Using Trip service to order points. How to rematch the ordered points with original list?

### ISSUE THREAD

**Issue by gwillig** [Project-OSRM/osrm-backend#6108]
I got the following list of unordered points: 
- Startpoint: 9.158766673,48.812529292;
1. 9.27509,49.08972; Pickup red package
2. 9.1475,48.89957; Pickup blue package
3. 9.15329,48.89247; Pickup green package
4. 9.15188,48.88986; Pickup green package
5. 9.14647,48.89061; Pickup green package
6. 9.13928,48.89152; Pickup green package
7. 9.15877,48.81253; Pickup yellow package
- Endpoint: 9.275092,49.089717

Which I send to the trip endpoint
`http://router.project-osrm.org/trip/v1/driving/9.158766673,48.812529292;9.27509,49.08972;9.1475,48.89957;9.15329,48.89247;9.15188,48.88986;9.14647,48.89061;9.13928,48.89152;9.15877,48.81253;9.275092,49.089717?source=first&destination=last`

The response is

<code>{"code":"Ok","trips":[{"geometry":"mu|hHgy{v@??yTim@wa@eYye@lRu~BhdGwYxR_~D_kCij@}rAyY|h@oOyKcCna@iKnAbKaArCm_@pNpI`KcKhOrGqJF|Et`@fK~b@wPbH|H_J`NpIzLoq@~ElBmmBkm@goA_Bkh@cUq]al@or@gkCuuA{pA}|@}aBglAocAa{Dwg@kmAyfAsoCy{@ggAceA{gA_RaxCegCyTbzB}L_S?A~JtVlN_hBzOuGdoCn{BlgAlQjfAvdAlrCr}@dlA`fAfyDpf@tmAndAz~@fdBlsA`nAhr@dkCp^`m@|d@bTlvAxC|sBz{@xbE~{CvnCmjH`g@}Trb@rYxThm@","legs":[{"steps":[],"distance":0.2,"duration":0,"summary":"","weight":0},{"steps":[],"distance":13577.4,"duration":1064.9,"summary":"","weight":1066.4},{"steps":[],"distance":1230,"duration":148.1,"summary":"","weight":148.1},{"steps":[],"distance":488.5,"duration":60,"summary":"","weight":60},{"steps":[],"distance":620.4,"duration":62.2,"summary":"","weight":62.2},{"steps":[],"distance":926,"duration":94.7,"summary":"","weight":94.7},{"steps":[],"distance":29201.5,"duration":1308,"summary":"","weight":1308},{"steps":[],"distance":0.4,"duration":0.1,"summary":"","weight":0.1},{"steps":[],"distance":38454.3,"duration":1945.8,"summary":"","weight":1945.8}],"distance":84498.7,"duration":4683.8,"weight_name":"routability","weight":4685.3}],"waypoints":[{"waypoint_index":0,"trips_index":0,"location":[9.158755,48.812545],"name":"Kärntner Straße","distance":1.985537,"hint":"9wqanRALmp1zAAAAMAAAAAAAAAAGAAAAPLCaQgl6-kEAAAAA7-h6QHMAAAAwAAAAAAAAAAYAAADAHwEAY8CLAAHS6AJvwIsA8dHoAgAATw-L7V1H"},{"waypoint_index":7,"trips_index":0,"location":[9.275134,49.089742],"name":"Hauptstraße","distance":4.039948,"hint":"ojfHnFk4x5wFAAAAEAAAAAAAAAAgAAAAXxJrQL4VJ0EAAAAAmr6rQQUAAAAQAAAAAAAAACAAAADAHwEA_oaNAM4M7QLSho0AuAztAgAA7wiL7V1H"},{"waypoint_index":2,"trips_index":0,"location":[9.147523,48.899571],"name":"Südliche Alleenstraße","distance":1.690874,"hint":"w1ibndxYm52UAAAACAAAACAAAAAAAAAAMN3FQtwXmUCT6QFBAAAAAJQAAAAIAAAAIAAAAAAAAADAHwEAg5SLAPMl6gJslIsA8iXqAgIAHwuL7V1H"},{"waypoint_index":3,"trips_index":0,"location":[9.153289,48.892472],"name":"Im Waldeck","distance":0.2342,"hint":"CA2bnRAUm50bAAAAAQAAAB8AAAAAAAAAoeOXQaXQLD9hNqpBAAAAABsAAAABAAAAHwAAAAAAAADAHwEACauLADgK6gIKq4sANgrqAgIAPw-L7V1H"},{"waypoint_index":4,"trips_index":0,"location":[9.151912,48.889861],"name":"Wöhlerstraße","distance":2.350059,"hint":"XxWbnfkZm50CAAAAWwAAAAAAAAAAAAAAc6YcQJc7ykIAAAAAAAAAAAIAAABbAAAAAAAAAAAAAADAHwEAqKWLAAUA6gKIpYsABADqAgAAbxaL7V1H"},{"waypoint_index":5,"trips_index":0,"location":[9.146475,48.890602],"name":"Daimlerstraße","distance":0.962301,"hint":"NhebnQcZm50FAAAAfQAAAAAAAACFAAAAPS_DQGGBCkMAAAAATm8UQwUAAAB9AAAAAAAAAIUAAADAHwEAa5CLAOoC6gJmkIsA8gLqAgAAXwSL7V1H"},{"waypoint_index":6,"trips_index":0,"location":[9.139257,48.891479],"name":"Hohenstaufenstraße","distance":4.861657,"hint":"vhWbnXEWm50CAAAAGwAAAAAAAAAhAgAA8TzoP_kPjUEAAAAAc_q1QwIAAAAbAAAAAAAAACECAADAHwEAOXSLAFcG6gJQdIsAgAbqAgAALxKL7V1H"},{"waypoint_index":1,"trips_index":0,"location":[9.158758,48.812546],"name":"Kärntner Straße","distance":1.985537,"hint":"9wqanRALmp1zAAAAMAAAAAAAAAAGAAAA7DGaQkhz_EEAAAAA7-h6QHMAAAAwAAAAAAAAAAYAAADAHwEAZsCLAALS6AJywIsA8tHoAgAATw-L7V1H"},{"waypoint_index":8,"trips_index":0,"location":[9.275136,49.089739],"name":"Hauptstraße","distance":4.039948,"hint":"ojfHnFk4x5wGAAAADwAAAAAAAAAgAAAAWduAQIlrIUEAAAAAmr6rQQYAAAAPAAAAAAAAACAAAADAHwEAAIeNAMsM7QLUho0AtQztAgAA7wiL7V1H"}]}
</code>

How can I match the response with my original list?

**Comment by mjjbell** [comment]
Use the `waypoint_index` to match to your original coordinate list. See the [/match](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#match-service) docs.
