### ISSUE TITLE
Wrong OSRM routes

### ISSUE THREAD

**Issue by PawelGW** [Project-OSRM/osrm-backend#6109]
Hello, about a week ago the route began to build not in an optimal way:

![1](https://user-images.githubusercontent.com/89509441/130743387-b9a24c2f-ddc9-43af-a718-b6ddd1e11903.png)
http://map.project-osrm.org/?z=18&center=52.125448%2C23.573179&loc=52.125641%2C23.573533&loc=52.125357%2C23.572578&hl=ru&alt=0&srv=0

![2](https://user-images.githubusercontent.com/89509441/130743447-be03817f-31da-47c5-8730-821eb03789c3.png)
http://map.project-osrm.org/?z=12&center=52.096488%2C23.689613&loc=52.141706%2C23.644295&loc=52.111566%2C23.561897&hl=ru&alt=0&srv=0

With OSM editor I could not find any problems in these data

**Comment by mjjbell** [comment]
The road immediately proceeding the border control in your first example is limited to HGV traffic only - it doesn't look like a [new change](https://www.openstreetmap.org/way/282927354/history#map=18/52.12438/23.57334).
![image](https://user-images.githubusercontent.com/1063186/131266798-44a7a99a-1edb-45d2-adcf-c000fce3020e.png)

This makes OSRM view the destination road as isolated and instead snaps  the destination to the more connected smaller road.

Can you provide more details about what changed in your setup a week ago?

**Comment by PawelGW** [comment]
nothing changed in the settings or in the data, but the route began to be built differently.
Eurasia data was uploaded on 03/20/2020 and I use the profile for trucks
[profile.zip](https://github.com/Project-OSRM/osrm-backend/files/7075279/profile.zip)

**Comment by mjjbell** [comment]
The examples you provided are from the hosted service using the car profile, not the truck profile.

Unless you've changed something in your location installation - either data, profile or OSRM version, I don't see how your results will have changed.
