### ISSUE TITLE
Shortest path ignoring waypoint order

### ISSUE THREAD

**Issue by sedir** [Project-OSRM/osrm-backend#611]
Hi guys, I looked everywhere and I didn't find a way to get this to work.
Let's suppose I want to know the shortest path from node A to D, but I have to pass through B and C in the way. 
I dont care if I put the params (lat/lng) is this order A -> B -> C -> D    or that    A -> C -> B -> D   because I should get the same result, the shortest path. 

This feature is similar to Google Maps option optimizeWaypoints="true"

Is that possible with OSRM?

**Comment by TheMarex** [comment]
Work on this is tracked in this branch https://github.com/Project-OSRM/osrm-backend/tree/feature/round_trip

**Comment by TheMarex** [comment]
This is now merged into `develop`.
