### ISSUE TITLE
No route found error and null values in osrm response

### ISSUE THREAD

**Issue by kk2491** [Project-OSRM/osrm-backend#6111]
Hi,

First of all, thanks for this wonderful and very useful repository. 

I have recently started using OSRM table service for my application. I am getting `null` value for some of the distance and duration matrix elements when the geo-coordinates are distance apart (possibly different countries). 

I would like to understand the point, could you please help me. 
* When can we expect `null`
* When can we expect No routes found error
* What is the difference between these 2.

Thanks in advance.

KK

**Comment by mjjbell** [comment]
Take a look at the HTTP docs for [route](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#route-service) and [table](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#table-service) requests, it explains the circumstances for these responses.
