### ISSUE TITLE
"Metrobüs" lane glitch causes horrendous routings in Istanbul 

### ISSUE THREAD

**Issue by vahdet** [Project-OSRM/osrm-backend#6115]
### Quick Clarification on the Metrobüs Lane

_Metrobüs_ lanes are [dedicated bus lanes](https://en.wikipedia.org/wiki/Metrobus_(Istanbul)) in Istanbul. Technically, the cars cannot take them. 

## Actual Behavior

The **car** routing in OSRM goes completely wrong if the [start](http://map.project-osrm.org/?z=13&center=40.992532%2C28.811817&loc=41.007674%2C28.897605&loc=41.002703%2C28.899536&hl=en&alt=0&srv=0) or [end](http://map.project-osrm.org/?z=14&center=41.035068%2C28.971115&loc=41.002703%2C28.899536&loc=41.007674%2C28.897605&hl=en&alt=0&srv=0) is on that _Metrobüs_ lane. The catch is: as the regular traffic lanes are literally adjacent to the _Metrobüs_ lanes (see the images in Wikipedia link above), the glitches are quite frequent and they result in erroneous results for both distance and duration: 2.9 km actual distance to 36 km, 6 min actual duration to 36 minutes or such.

As depicted in the example OSRM links above, the problem is guiding the route to one of the two terminuses of the _Metrobüs_ lane.

The result is similar for the programmatic API calls.

## Expected Behavior

Since a car virtually cannot use the _Metrobüs_ lane, it should be either:

- **neglected**, or
-  _Metrobüs_ lanes should not be identified as regular traffic lanes

while routing _car trips_. 

Finally, this piece of information may help about the way out of this case: I have noticed that, throughout that dedicated lane, the coordinates (waypoints) are always named as `Metrobüs` in the API call results.

**Comment by mjjbell** [comment]
This is an OSM data issue: https://www.openstreetmap.org/way/227911771#map=18/41.00728/28.89759

<img width="380" alt="Screenshot 2021-09-02 at 19 40 24" src="https://user-images.githubusercontent.com/1063186/131898818-63c4f3e8-1e82-4feb-aa83-e7840a70abb3.png">

`motor_vehicle=designated` allows cars to route via this road.
`access=private` means OSRM will avoid routing to this road unless it really has to (e.g. if you start or end your journey on the road).

In combination, you get the behaviour you are seeing.

Judging by your description, the access tags need to be changed to just `access=no` with specific transport exceptions that grant access (e.g. `psv=yes` is already providing access for buses).

See the OSM access page for full guidance: https://wiki.openstreetmap.org/wiki/Key:access

**Comment by mjjbell** [comment]
Once the tags are corrected, OSRM will no longer use the bus lanes even if the start/end of the journey is on it - it will instead move the start/end location to the nearest car routable road.

**Comment by vahdet** [comment]
> Judging by your description, the access tags need to be changed to just access=no with specific transport exceptions that grant access (e.g. psv=yes is already providing access for buses).

That makes sense. So, once the OSM data is set for `access=no`, cars won't be routed on Metrobus lane while public transportation would remain possible. Actually, this is how it should be.

> Once the tags are corrected, OSRM will no longer use the bus lanes even if the start/end of the journey is on it - it will instead move the start/end location to the nearest car routable road.

So it seems, as a logged-in OSRM user, I cannot manipulate the data I receive by monkeying with my [request](http://project-osrm.org/docs/v5.5.1/api/#requests). I attempted to propose an _edit_ on the [link you've shared](https://www.openstreetmap.org/way/227911771#map=18/41.00728/28.89759), however it spans only a partial section of that lane. Is there anything I can do to have _Metrobüs_ sections altered in Istanbul in bulk?

**Comment by systemed** [comment]
Bulk edits in OpenStreetMap are complex and require a lengthy approval process, because the chance of collateral damage is very high. It's honestly simpler in most cases to do a manual edit.

**Comment by matkoniecz** [comment]
I opened https://www.openstreetmap.org/note/2852366

**Comment by SiarheiFedartsou** [comment]
Stale.
