### ISSUE TITLE
Question: only driving profile available?

### ISSUE THREAD

**Issue by demiantres** [Project-OSRM/osrm-backend#6120]
Hello,

I tried to replace the "driving" profile with the public test server (http://router.project-osrm.org/route/v1/driving) with other profiles such as "bike" but I cannot get it working. Does the server support only "driving" profile?

**Comment by jcoupey** [comment]
This part of the URL in requests has no effect with a default OSRM setup. The demo server does have several profiles available, see e.g. #6104.
