### ISSUE TITLE
osrm-extract assert triggering on manoeuvre override relation

### ISSUE THREAD

**Issue by mjjbell** [Project-OSRM/osrm-backend#6126]
With the [Kentucky OSM extract](https://download.geofabrik.de/north-america/us/kentucky.html).

`osrm-extract` with the default bike profile triggers an assertion when compressing a manoeuvre override.

https://github.com/Project-OSRM/osrm-backend/blob/051e931091c19ce6f38c86202827e8ecd061aaa8/src/extractor/restriction_compressor.cpp#L228

The override is applied at an intersection between a private and public road: https://www.openstreetmap.org/relation/10547836#map=16/39.0284/-84.5417
<img width="1558" alt="Screenshot 2021-09-16 at 14 53 51" src="https://user-images.githubusercontent.com/1063186/133624761-65c7f2d6-21d3-429b-a16e-6612fed36ac3.png">

The private road is not accessible to the bike profile, so the node has degree two, allowing it to be compressed.
The via node of manoeuvre overrides are not exempt from being compressed, although the code appears to expect this to be the case. This inconsistency leads to the triggering of the assertion.

Furthermore, manoeuvre overrides do not support non-compressible nodes as part of the paths, meaning many are skipped or ignored. This was fixed for turn restrictions, a similar change is required for manoeuvres.

Other than fixing debug builds, there are only ~100 overrides in OSM data, so the impact on routing will be low.

**Comment by danpat** [comment]
I would be tempted to drop support for the maneuver override tag completely.  It was invented by us a while back as a way to influence the route guidance with data-driven properties, e.g. when the geometry/graph shape of an intersection can't capture how people experience an intersection in the real world, the maneuver override relation was supposed to allow users to explicitly map the type of instruction we should emit for a particular traversal.
