### ISSUE TITLE
Invalid Query : Query string malformed, parameter annotations ?

### ISSUE THREAD

**Issue by MaxiReb** [Project-OSRM/osrm-backend#6127]
Hi,

I use a local engine of OSRM (on Windows) and the package osrm in R. I have no problems with the function "osrmRoute" for example but when I use "osrmTable", I have this error : 
```
> dist<-osrmTable(src=source,dst=destination)
The OSRM server returned an error:
Error in doTryCatch(return(expr), name, parentenv, handler): object 'res' not found
```

I check in the command shell to see the requests and I get this : 
`[info] 20-09-2021 17:18:48 0.1394ms 127.0.0.1 - osrm_R_package 400 /table/v1/foot/1.35167,43.60747;1.43126,43.66120?sources=0&destinations=1&annotations=duration←[0m`
This line is repeated several times, and I have no results at the end...

I check this line on Chrome and I get this : 
```
http://localhost:5000/table/v1/foot/1.35167,43.60747;1.43126,43.66120?sources=0&destinations=1&annotations=duration

Response : {"code":"InvalidQuery","message":"Query string malformed close to position 73"}
```

And if I delete the annotations paramater, my result is OK : 
```
http://localhost:5000/table/v1/foot/1.35167,43.60747;1.43126,43.66120?sources=0&destinations=1

Response : {"sources":[{"location":[1.351546,43.607649],"name":"Voie Latérale Nord","hint":"avEBgBbxAYBFAQAABgEAAOQEAAAAAAAARQEAAAYBAADkBAAAAAAAAAEAAAB6nxQAYWaZAvafFACuZZkCAwD_A09TUk0="}],"destinations":[{"location":[1.431518,43.661217],"name":"Avenue de Fronton","hint":"-doKgFLbCoDIAAAAEgAAAD4BAACJAAAAyAAAABIAAAA-AQAAiQAAAAEAAADe1xUAoTeaAtzWFQCQN5oCAwAvFk9TUk0="}],"code":"Ok","durations":[[8288]]}
```

Where is the problem ? And how can I use osrmTable in R to avoid this problem (I already use osrmTable with the server online routing.openstreetmap.de and I have no problem with it) ?

Thanks

**Comment by danpat** [comment]
@MaxiReb Support for `annotations=` was added to OSRM in version [5.18](https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#5180) - I would guess that the version you're running at `localhost` is older than that.

**Comment by MaxiReb** [comment]
Ok, thanks for your answer. I install my version with the latest successful build that I found here : build.project-osrm.org
Is there a place where I can get a more recent version for Windows ?
How can I get the number of my version (command in shell ?) ? Or maybe can I use an older package in R to avoid the problem ?

**Comment by MaxiReb** [comment]
I try to use Docker but it's too complicated for me ! I did not succeed to run a local server with it...maybe I can retry, there is a simple tutorial ? 

In fact, I don't need the parameters annotation but I can't remove it because it's in the R package by default...

**Comment by danpat** [comment]
The instructions at https://hub.docker.com/r/osrm/osrm-backend have a "Quick start" section which has the step-by-step commands you need.

Otherwise, you need to downgrade or modify your R package to not pass the `annotations=` parameter.

There's not much else we can do here - the issue is an incompatibility between your OSRM version and your R package - you will need to change one or the other.

> it's too complicated for me

I have faith in you!  Give it another go :-)
