### ISSUE TITLE
Route drawn over map is not completely Snap To Road 

### ISSUE THREAD

**Issue by amanattri09** [Project-OSRM/osrm-backend#6132]
Hello Team,

I have been using **"Match service"** for Snap to Road but when number of locations are fewer for any trip then Snap to road locations comes out through Match Service Api are  even fewer so polyline drawn over map is not exactly "Snapped to Route". Can you tell us how to get enough Snap to Road locations so that route we draw over map is completely Snap to Road?

Thanks
Aman Attri

**Comment by danpat** [comment]
Look at the `overview=full` and `geometries=polyline6` options in the documentation here:  http://project-osrm.org/docs/v5.22.0/api/#general-options
