### ISSUE TITLE
Support Docker images for Apple Silicon/M1 arm64 platform

### ISSUE THREAD

**Issue by muthenberg** [Project-OSRM/osrm-backend#6133]
Hi,

Using the latest docker images on my MacBook Pro M1 with Apple Silicon I get the following warning:
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

It seems the image works fine, but I guess it uses Rosetta 2 for amd64 emulation. I would prefer a native image. Are there any plans to support this?

I would be willing to create those images on my machine and provide them to you, if you have no such MacBook. However I do not know, whether this is desired and whether I would be able to build the images. My C++ experience is pretty dated and based on using Visual Studio 6.0.

**Comment by hoerup** [comment]
I assume this will depend both on getting GH actions working for building docker image in general ( see https://github.com/Project-OSRM/osrm-backend/pull/6137 ) AND github adding support for M1 ( https://github.com/actions/virtual-environments/issues/2187 )

**Comment by muthenberg** [comment]
@hoerup That is a good question. I know that M1 has an ARM processor, but I am not very knowledgable about different kinds of those processors. Wikipedia tells me that the instruction set is arm V8.4-A. 

If you create such a PR I would be happy to try to run it on my machine and tell you the results.

**Comment by SiarheiFedartsou** [comment]
We already build M1 containers on CI, will be available in 5.27.

**Comment by Kradenko** [comment]
Hi, would this mean that 5.27 would then also work on Raspberry Pi? If so, when will 5.27 be available?

**Comment by SiarheiFedartsou** [comment]
@Kradenko hm, I think so, but it is to be tested. Could you build docker image from master and try? I can provide instructions on how it can be done if needed.

**Comment by Kradenko** [comment]
Please! I have been looking for a howto all day.

**Comment by SiarheiFedartsou** [comment]
> @SiarheiFedartsou Please! I have been looking for a howto all day.

You can just build Docker image like this:
```
docker build -t osrm-local --platform arm64 -f docker/Dockerfile .
```

Then you can just try to run OSRM [as usual](https://github.com/Project-OSRM/osrm-backend#using-docker), but changing `osrm/osrm-backend` to `osrm-local` to use image you just built rather then version from Docker Hub. Let me know if it is not clear.

**Comment by Kradenko** [comment]
> > @SiarheiFedartsou Please! I have been looking for a howto all day.
> 
> You can just build Docker image like this:
> 
> ```
> docker build -t osrm-local --platform arm64 -f docker/Dockerfile .
> ```
> 
> Then you can just try to run OSRM [as usual](https://github.com/Project-OSRM/osrm-backend#using-docker), but changing `osrm/osrm-backend` to `osrm-local` to use image you just built rather then version from Docker Hub. Let me know if it is not clear.

Will give it a go later tonight and let you know.

**Comment by Kradenko** [comment]
Apologies for the incredibly late response. This method has served me very well for using it on the Raspberry Pi. 

I only wish we had more memory to run the OSRM on the Pis. Will ask if there is a way to use swap space at some stage. For testing this is fine now.

**Comment by franc703** [comment]
In case anyone is still struggling with creating a local server using apple silicon, I found this very helpful: https://formulae.brew.sh/formula/osrm-backend.
