### ISSUE TITLE
Circular routes

### ISSUE THREAD

**Issue by systemed** [Project-OSRM/osrm-backend#614]
As well as A-B routes, it would be good to support A-B-A routes, particularly for cycling.

You can sort of simulate this right now by asking for an alternative route, then reversing that. But this doesn't support 'via' points - i.e. the route can't be draggable.

Ideally a circular route would be one like any other - i.e. an A-A route with B as the first via point, but you could add as many via points between A and B, and B and A, as you liked. The logic to make B-A different from A-B is already in AlternativePathRouting.h, I guess, though it might be desirable to decrease VIAPATH_GAMMA and increase VIAPATH_EPSILON for this case.

(If this were OSM trac I'd tag it as "wishlist" rather than "defect" - by no means a blocker, just a fun 'nice-to-have'!)

**Comment by TheMarex** [comment]
I don't see this as a service due to the heuristic nature. `trip` can do shortest round-trips, `viaroute` can be used to swap out route legs with alternatives if necessary.
