### ISSUE TITLE
OSRM proposes incorrect route

### ISSUE THREAD

**Issue by ariadacapo** [Project-OSRM/osrm-backend#6141]
In this case of two points separated by a 100 m on a secondary road, [OSRM proposes a very long route](https://map.project-osrm.org/?z=18&center=44.019862%2C7.311466&loc=44.020676%2C7.310833&loc=44.019507%2C7.310967&hl=en&alt=0&srv=0) and I can’t find an explanation for this in the OSM source data. Am I missing something? Thanks for your time!
![Screenshot from 2021-10-03 14-22-57](https://user-images.githubusercontent.com/8167850/135753476-9431fad8-f36e-4419-908c-91a23f0d62fc.png)

**Comment by hoerup** [comment]
Probably because the section here

![billede](https://user-images.githubusercontent.com/737393/135760571-2318d987-cfd0-4d67-9378-0ea6b779c40f.png)

is tagged as construction

**Comment by ariadacapo** [comment]
Indeed! This is not a bug at all. Sorry for bringing up a false positive. Thank you so much for your time.
