### ISSUE TITLE
strange route

### ISSUE THREAD

**Issue by RegularnaMatrica** [Project-OSRM/osrm-backend#6143]
Can someone please point me why route (using route service) through 2 points:

![image](https://user-images.githubusercontent.com/65914613/135997719-be0b5b0b-6041-43c6-bbf4-3604be7cbbfd.png)

http://router.project-osrm.org/route/v1/driving/polyline(slioEfx%7DnUsIcG)?alternatives=false&steps=true&geometries=polyline&overview=full&annotations=true&continue_straight=true

is making a detour:

![image](https://user-images.githubusercontent.com/65914613/135997910-2c0440b1-3b4b-4d61-b3c7-cf95aa247451.png)

**Comment by hoerup** [comment]
probably because the target point snaps to a point which is part of the loop - if you move the target point just a few meters to the left it seems correct

**Comment by RegularnaMatrica** [comment]
Do you know would higher decimal precision fix the problem?

**Comment by mjjbell** [comment]
OSRM stores coordinates to 6 decimal places, so we're already in the < 10cm of precision and unlikely to be a problem, although it could depend on where you are getting the input coordinates from?

**Comment by SiarheiFedartsou** [comment]
Stale.
