### ISSUE TITLE
Profile: Access `highway=` key in segment function

### ISSUE THREAD

**Issue by bda1986** [Project-OSRM/osrm-backend#6145]
Within the `process_way()` function in a profile, it is possible to obtain relevant keys using, e.g., `way:get_value_by_key('highway')`.
Is there a similar possibility to do so for the segment function?

I have used a modified version of the `rasterbot.lua` profile to include third-party raster elevation data and would like the slope of a segment to affect duration conditional on the surface or road type. 
For example, the same slope should assign a higher penalty on ways with `highway=track` than on `highway=primary`. 

However, keys/tags such as `highway=primary` are not listed among the available attributes in the `process_segment()` function, as described in [profiles.md](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md).
As far as I understand, the segments are subsets or parts of the ways, so the information specific to each way should be available for the segment somehow?

**Comment by mjjbell** [comment]
As the extraction is currently constructed this will be difficult, as the OSM tag context has been discarded by the time the extraction reaches `process_segment`.

Just to understand correctly, you want to _disproportionately_ apply a slope to the speed of a segment depending on the highway type?
E.g. Given a 5mph track and a 70mph motorway with identical uphill slope, you might want to scale the track to 3mph but motorways are scaled down less, so becomes 65mph?

**Comment by bda1986** [comment]
> Just to understand correctly, you want to _disproportionately_ apply a slope to the speed of a segment depending on the highway type? E.g. Given a 5mph track and a 70mph motorway with identical uphill slope, you might want to scale the track to 3mph but motorways are scaled down less, so becomes 65mph?

Exactly, this is what I was trying to achieve.


> As the extraction is currently constructed this will be difficult, as the OSM tag context has been discarded by the time the extraction reaches `process_segment`.

So any information related to the way, for example, the way_id is no longer available in the `process_segment` function? 
Do the segments themselves have some sort of identifier (other than the coordinates) that would make it possible to join external data?

**Comment by mjjbell** [comment]
Had a deeper look.

`process_segment` is called from `ProcessSegment` in the C++ extraction code.

https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/src/extractor/extraction_containers.cpp#L439-L440

At this point, it's iterating over a list of `InternalExtractorEdge` values. In addition to edge coordinates, it also has an embedded `NodeBasedEdgeWithOSM` value.

These internal edges are actually created when processing the output of `process_way` 
https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/src/extractor/extractor_callbacks.cpp#L405-L430

So it looks like the edge already has access to the OSM segment nodes, and a guidance classification that is almost a complete list of OSM highway types.

https://github.com/Project-OSRM/osrm-backend/blob/f7478ba80f04ee6777556661f93edff5bef85c90/profiles/lib/guidance.lua#L6-L27

Could this list be sufficient for your calculations?

We could also add the OSM way ID to the internal edge representation and pass that through instead.
This was already being proposed in #5325 to enabled way annotations, so perhaps that's not a bad option. 

Either way, there's a bit of additional plumbing required to pass these values through to `process_segment`, but it's still not keeping the full list of OSM tags available for inspection. I would expect doing that will be a lot of additional memory bloat for most use-cases.

**Comment by bda1986** [comment]
Thank you for pointing out these code snippets. 
This definitely makes it clearer to me how the information are passed through internally.


> Could this list be sufficient for your calculations?

For my case, it would be ideal to pass the `highway` and `surface` key to the segment function. 
However, the list of OSM highway types you've mentioned would already be very helpful, as the `surface` tag seems to have a lot of missing values anyway. So definitely yes, it would be sufficient.


> We could also add the OSM way ID to the internal edge representation and pass that through instead. This was already being proposed in #5325 to enable way annotations, so perhaps that's not a bad option.
> 
> Either way, there's a bit of additional plumbing required to pass these values through to `process_segment`, but it's still not keeping the full list of OSM tags available for inspection. I would expect doing that will be a lot of additional memory bloat for most use-cases.

I do understand that this would cause quite some memory bloat, especially for users who do not use this feature - which is probably the vast majority. 
Could using the way ID instead be a less memory-intensive alternative? I could then join the relevant data externally, as suggested in #5325.

**Comment by mjjbell** [comment]
> Could using the way ID instead be a less memory-intensive alternative? I could then join the relevant data externally, as suggested in #5325.

Yes, I think we can add the way ID to `NodeBasedEdgeWithOSM` and expose the values it contains to `process_segment`.
