### ISSUE TITLE
Terminate called after throwing an instance of 'osrm::util::exception

### ISSUE THREAD

**Issue by hm-lijojohn** [Project-OSRM/osrm-backend#6148]
Hi Everyone,

I am having an issue whenI am trying to start OSRM and its giving me a checksum error.

I am running the latest Docker build provided and the command I am using to start is: docker run -t -i -p 5000:5000 -v "%cd%":/data osrm/osrm-backend osrm-routed --algorithm mld /data/country.osrm

It fails to start. The full details of log is provided as below:

[info] starting up engines, v5.26.0
[info] Threads: 12
[info] IP address: 0.0.0.0
[info] IP port: 5000
terminate called after throwing an instance of 'osrm::util::exception'
  what():  Connectivity checksum 394345722 in /data/country.osrm.hsgr does not equal to checksum 2280019160 in /data/country.osrm.edges

How to solve this issue?  A similar issue mentioned above but closed without answer as user got it resolved. 

https://github.com/Project-OSRM/osrm-backend/issues/5531

**Comment by jcoupey** [comment]
You need to make sure to use the same OSRM build for data preparation (`osrm-partition`, `osrm-customize`) and for routing (`osrm-routed`). The suggestion in #5531 amounts to removing all `*.osrm.*` files previously generated, then relaunching data preparation steps as described in [the readme](https://github.com/Project-OSRM/osrm-backend#using-docker).
