### ISSUE TITLE
error in docker osrm-routed : include/storage/tar.hpp

### ISSUE THREAD

**Issue by komal4364** [Project-OSRM/osrm-backend#6152]
I am facing this error:
**[error] Unexpected end of file: /extractor/edges: Datatype size does not match file size. (at include/storage/tar.hpp:149)`
when osrm-routed in docker;**

Following steps are followed:

Run the following steps on host machine.
Step1: Download India pbf files
wget http://download.geofabrik.de/asia/india-latest.osm.pbf

india-latest.osm.pbf, suitable for Osmium, Osmosis, imposm, osm2pgsql, mkgmap, and others. This file was last modified 3 hours ago and contains all OSM data up to 2021-10-27T20:21:12Z. File size: 996 MB; MD5 sum: 9f03880937254afebfbeaa5040f413d9.

Step2: sudo chown -R $USER /usr/local/lib/node_modules
Step3: npm i osrm -g
Step4: export PATH=${PATH}:/usr/local/lib/node_modules/osrm/lib/binding/ set it in your environment
Step4: osrm-extract india-latest.osm.pbf -p bike.lua with left side driving.
Step5: osrm-partition india-latest.osrm
Step5: osrm-customize india-latest.osrm

Mount this on docker with osrm-backed: latest docker image
docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/india-latest.osrm

**Comment by Christian-Klempau** [comment]
Did you solve it? got the same problem

**Comment by herozhi** [comment]
> Did you solve it? got the same problem

Did you solve it? got the same problem too

**Comment by herozhi** [comment]
> 

thanks ,bro

**Comment by herozhi** [comment]
> 



> then

thanks ,bro
