### ISSUE TITLE
Is it possible to select paved/unpaved when using OSRM?

### ISSUE THREAD

**Issue by Engenia** [Project-OSRM/osrm-backend#6157]
On https://www.openstreetmap.org/directions when asked to find directions from -35.1352, 149.1963 to -35.1094, 149.2467, Bicycle (OSRM) chose an 11km route while Car (OSRM) [and curiously Bicycle (GraphHopper)] chose the more direct 5.7km route.
The reason appears to be the shorter route was unpaved. A selection of paved/unpaved could reveal this anomaly, or ensure that the road surface desired is in fact used, as it is not clear in OSM what the cause is, until the map is opened for editing.

(I have since corrected the offending OSM road section to paved, so the example given may soon not be indicative of the issue)

**Comment by systemed** [comment]
The OSRM instance accessible from openstreetmap.org has "Car", "Bike" and "Foot" routing graphs, each of which prioritises certain types of roads/paths. So in that way, it's certainly possible to set up an instance that has a "Bike, paved only" and a "Bike, unpaved fine" or even a "Bike, prefer unpaved" graph.

However, [the people who kindly operate the routing server](https://routing.openstreetmap.de/about.html) used by osm.org have chosen to operate those three graphs only. Adding more graphs would require a significant extra hardware commitment (=$$$). If you set up your own OSRM instance, you can customise it to prefer any sort of roads you like.

(footnote: if you're operating your own instance, you might also be able to do this by using OSRM's `exclude` feature, but I'm not sure how well that would scale up to areas with massive numbers of unpaved roads like the US Midwest)
