### ISSUE TITLE
Build process fails for arm-64

### ISSUE THREAD

**Issue by codek** [Project-OSRM/osrm-backend#6158]
If you try and follow the build instructions on an M1 mac it fails in the `cmake ../ -DENABLE_MASON=1` step

Like so:

```
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-arm64/boost_libfilesystem/1.73.0.tar.gz...
CMake Error at cmake/mason.cmake:80 (message):
  [Mason] Failed to download
  https://mason-binaries.s3.amazonaws.com/osx-arm64/boost_libfilesystem/1.73.0.tar.gz:
  curl: (22) The requested URL returned error: 403

Call Stack (most recent call first):
  CMakeLists.txt:468 (mason_use)


-- Configuring incomplete, errors occurred!
```

**Comment by mjjbell** [comment]
The Boost Mason dependency appears to be [x86 only](https://github.com/mapbox/mason/blob/0296d767a588bab4ca043474c48c0f269ccb8b81/scripts/boost/1.73.0/base.sh#L9).

You can ask Mapbox what their plan is for supporting ARM in Mason, but given they are no longer investing in OSRM, it probably makes sense that this repo evaluates other dependency management options, in particular those that will also support a Windows build.

In the meantime, you'll need to manage dependencies locally on your machine.

**Comment by SiarheiFedartsou** [comment]
Can be closed as we merged https://github.com/Project-OSRM/osrm-backend/pull/6284
