### ISSUE TITLE
alt=true/false returns different main route

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#616]
sometimes turning alternative route on/off causes the main route to differ. for example, the scenario features/bicycle/area.feature:31 passes with alt=true, but fails with alt=false.

the AlternativePathRouting class does not inherit from ShortestPathRouting. i don't know the innards of the algoeithm, but this seems to be why different results can occur.

**Comment by TheMarex** [comment]
@emiltin I see that we use `alt=false` per default now? So this is obsolete right?

**Comment by TheMarex** [comment]
Should be fixed. First route is always the fastest. Only problem is when multiple route with the same length exists. But they are at least deterministic on query time.
