### ISSUE TITLE
Table api returns null while route api returns a route

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#6161]
Hello

I'm using OSRM v5.18 table API and I see some strange behaviors in the log. There are many routes with null duration and distance, while the route API returns a route for that pair of source-destination. The only common feature that I see among these pairs, is that the source and destination are in the reverse direction of the way and they are close to each other (like this [screenshot](https://imgur.com/a/VScOUHS)). 

Another thing that I tested is that when I don't set sources, destinations index params in request it works well and returns a number (a duration for each 2x2 matrix cell). But when I want to get the duration for just a single source destination it returns null.

Do you have any idea why this happens?

Thanks

**Comment by mjjbell** [comment]
This sounds identical to the issue fixed by #5828, which was included in the `v.5.23.0` release. Please use this or a later version to resolve the problem.
