### ISSUE TITLE
Nearest street is not that near!

### ISSUE THREAD

**Issue by eliboni** [Project-OSRM/osrm-backend#6164]
I come across this randomly

https://router.project-osrm.org/nearest/v1/driving/-5.789794,35.146862.json?number=1

{"code":"Ok","waypoints":[{"nodes":[319791267,6291980852],"hint":"3s2RguPNkYIUAAAAAAAAAOsDAAAAAAAAS2gIQQAAAABItdBDAAAAABQAAAAAAAAA6wMAAAAAAAD75gAAamiq_55lJQKep6f_bkwYAgsAzww9lKb5",**"distance":96633.877814**,**"location":[-5.609366,36.005278]**,"name":"Carrretera de la Isla de las Palomas"}]}

am I doing something wrong? Of course is plenty of nearest streets

Thanks

**Comment by eliboni** [comment]
https://router.project-osrm.org/nearest/v1/driving/-83.28460693359376,40.492915026895815.json?number=1

{"code":"Ok","waypoints":[{"nodes":[4121016723,4121016699],"hint":"hPiRgfL0koEAAAAAKQAAAAAAAADhBQAAAAAAAHEYiUEAAAAAjOocRAAAAAApAAAAAAAAAOEFAADDcgGA9uVu_7ZtWQKBLQn7c99pAgAAnwU9lKb5","distance":6303549.078673,"location":[-9.509386,39.415222],"name":""}]}

Is router.project-osrm.org/nearest enabled for Europe only?

**Comment by mjjbell** [comment]
For context in case these API results change: 

Request 1: a location in Morocco returns the `nearest` as the southernmost road on mainland Spain.
Request 2: a location in Ohio, USA returns the `nearest` as the road on an island off the east coast of Portugal

I don't think this is an OSRM bug, as the demo server backing `router.project-osrm.org` creates continent sized networks and performs location-based routing to the correct OSRM graph instance. This looks like a potential issue with that routing. 

cc: @datendelphin

**Comment by datendelphin** [comment]
Yes that seems to be a bug in my dispatch function https://github.com/fossgis-routing-server/request-by-coordinate/
If you omit the .json, it works as expected: https://router.project-osrm.org/nearest/v1/driving/-83.28460693359376,40.492915026895815?number=1
