### ISSUE TITLE
Wrong intersection_node ID in edge based graph factory

### ISSUE THREAD

**Issue by samDB-gv** [Project-OSRM/osrm-backend#6166]
Hello, 

When running osrm-contract with osrm v5.26 (to take into account #6020 ), logs gives me something like : 

> [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 2539866, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=48.970389&mlon=2.282888

But this node id was deleted 15 years ago ^^
Since intersection_node is derived from NodeID, is this related to the fact that NodeID is still defined as uint32_t in typedefs.hpp ?  

Another hint comes from graph_contract_adaptors.hpp, where the warning "[warn] Edge weight large -> 1084267 : 1649465 -> 1649466" lead to deleted nodes. 

Thanks for your reply,

**Comment by mjjbell** [comment]
The log message is a bit misleading, it's referring to the OSRM Node ID and hoping you use the link to figure out the OSM details. We know the OSM ID at this point in the processing, it will just require a bit of plumbing to make it available to the log message.

> Since intersection_node is derived from NodeID, is this related to the fact that NodeID is still defined as uint32_t in typedefs.hpp ?

No, whilst OSM Node IDs now exceed `UINT32_MAX`, OSRM is still able to enumerate all the nodes it needs for creating 
routing networks within 32 bits (although for large planet size OSM extracts, it's starting to get [reasonably close](https://github.com/Project-OSRM/osrm-backend/issues/6159#issuecomment-981502982)).

**Comment by samDB-gv** [comment]
oh yes ok, I see. Thanks for your explainations !
