### ISSUE TITLE
Time condition oneway

### ISSUE THREAD

**Issue by RodrigoVm7** [Project-OSRM/osrm-backend#6167]
Hi guys
Does OSRM support time condition oneway tags in OSM?
![138031137-688c6bc0-0f01-4ee3-b890-4b5a5f8be299](https://user-images.githubusercontent.com/50917707/144920045-eb755cce-99b9-41ef-9f40-48d2549729af.png)

**Comment by mjjbell** [comment]
(Assuming you're asking about OSRM, and not [Valhalla](https://github.com/valhalla/valhalla/))

No, it doesn't. There is an open ticket for supporting [conditional way access](https://github.com/Project-OSRM/osrm-backend/issues/4231), which given the way OSRM is implemented, is most likely a prerequisite for conditional one-ways.

**Comment by GrishaPortnikov** [comment]
Is there any workaround to handle 'oneway:conditional' and/or 'motor_vehicle:conditional'?

**Comment by SiarheiFedartsou** [comment]
Stale.
