### ISSUE TITLE
Time dependent restrictions

### ISSUE THREAD

**Issue by GrishaPortnikov** [Project-OSRM/osrm-backend#6168]
Hi,

I've read several discussions and issues related to restrictions but I still don't understand what exactly can be covered and how.

Is it possible to consider any time dependent restrictions (e.g. 'oneway:conditional', 'motor_vehicle:conditional')?
Will such restrictions be considered by "[osrm-extract --parse-conditional-restrictions](https://github.com/Project-OSRM/osrm-backend/wiki/Check-conditional-restrictions)" command?

Thank you in advance

**Comment by mjjbell** [comment]
OSRM has limited support for conditional restrictions. It currently only supports time-based [turn restrictions](https://github.com/Project-OSRM/osrm-backend/pull/3841).

Any other [combination](https://wiki.openstreetmap.org/wiki/Conditional_restrictions) of routing property (access, speed) and condition (time, vehicle type) is not supported.

Conditional access restrictions support is being tracked in #4231

**Comment by GrishaPortnikov** [comment]
Thank you for the quick answer. 

Are there some workarounds?
Maybe real-time traffic data approach (some csv files) or something like that can be used to consider time dependent restrictions?

**Comment by mjjbell** [comment]
I don't think there are any reasonable workarounds, it just needs to be implemented.

**Comment by SiarheiFedartsou** [comment]
Stale.
