### ISSUE TITLE
Routing different route in demo then public and local routing api

### ISSUE THREAD

**Issue by stephenhenckaerts** [Project-OSRM/osrm-backend#6177]
I have a local server running with the belgium-latest.pbf. I have found out that there is a different route when using the local server then the demo.

Then I did some testing on the public API. This returns indeed the same route as the local server:
http://router.project-osrm.org/route/v1/foot/5.296676158905029,50.74547159568471;5.291118621826172,50.735776116522025

But I have found out that the demo uses a different endpoint:
https://routing.openstreetmap.de/routed-foot/route/v1/driving/5.296676158905029,50.74547159568471;5.291118621826172,50.735776116522025?overview=false&alternatives=true&steps=true

The problem is that I want the same routing as used in the demo. But I have no clue why they using a different API in the demo then the public API. The route used in the demo is a shortcut and better then the one suggested in the public API:

<img width="256" alt="Schermafbeelding 2021-12-15 om 12 46 17" src="https://user-images.githubusercontent.com/17426364/146183519-dfe46198-d3ec-4274-b3ea-0f01e8368e43.png">
<img width="256" alt="Schermafbeelding 2021-12-15 om 12 45 46" src="https://user-images.githubusercontent.com/17426364/146183532-97fdf4fd-efb5-436a-a3b9-e04d40caec1b.png">

**Comment by jcoupey** [comment]
Routing results may vary across instances depending on profile tuning. The profiles used for the demo server can be found at https://github.com/fossgis-routing-server/cbf-routing-profiles/.
