### ISSUE TITLE
Sometimes line between node and projection node cross rivers, railways

### ISSUE THREAD

**Issue by amatrosovs** [Project-OSRM/osrm-backend#6178]
![image](https://user-images.githubusercontent.com/96227588/146327091-5b7c4e17-ef68-4987-8cd2-0d61e9713fd7.png)
When between point is not any way, it starts to searching nearest way by making projection node and in this process rivers and railways do not block projection line(line between node and projection node) and for user it looks like car/bicycle fly over impassable object.
For example this screenshot. I think this is bug and if can be fixed by modifying osrm code, profiles lua code I want to fix this.

**Comment by amatrosovs** [comment]
![image](https://user-images.githubusercontent.com/96227588/146328456-d2a0eed5-20ed-4303-a21b-6d940683fa53.png)
This is a similar bug in OSRM demo server

**Comment by danpat** [comment]
While I agree that this is "wrong" behaviour, I'm not sure it's really feasible to store all the lake/river/water/fence/other barrier geometry in our spatial index and use it to prevent this.

We would also need to decide what the right behaviour is here - snap to another road that's further away but doesn't cross a barrier?

**Comment by amatrosovs** [comment]
I think that right behavior would be snap to another road that's further away but doesn't cross a barrier
