### ISSUE TITLE
Does not build with tbb 2021.4.0-1.1 on openSUSE_Tumbleweed

### ISSUE THREAD

**Issue by stoecker** [Project-OSRM/osrm-backend#6181]
For the newer tbb a lot of filenames changed. FindTBB.cmake does not find it, because tbb/task_scheduler_init.h and tbb/tbb_stddef.h do no longer exist. When I patch CMAKE to use tbb/task.h and oneapi/tbb/version.h it fails in build with missing tbb/atomic.h in include/util/packed_vector.hpp.

**Comment by zgdump** [comment]
I have the same trouble on the latest Majaro Linux. After patching FindTBB.cmake, build fails on including atomic headers

**Comment by stoecker** [comment]
Is there a release planned in next time or should I think about building a patched version?

**Comment by SiarheiFedartsou** [comment]
Yes, we are planning it (see https://github.com/Project-OSRM/osrm-backend/issues/6325), but not sure when it will happen.
