### ISSUE TITLE
Questions regarding rate in OSRM

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#6183]
Hello

I'm using OSRM v5.25 and I provide traffic data using a CSV file to the OSRM. If I provide rates for some segments it seems that the resulting routes are not as good as when I provide rates for all of the segments.

I want to know why this happens? and how does the rate affect the segment's weight? 

There's also another problem that when I provide just a speed for a segment, and the same speed=speed & rate=speed/3.6 the resulting weight is not the same. But as I read the documents, they should be the same. 

Thanks

**Comment by mjjbell** [comment]
Can you elaborate on what is not good about the resulting routes?
Do you have a CSV file that illustrates this?

**Comment by SiarheiFedartsou** [comment]
Stale.
