### ISSUE TITLE
Traffic doc missleading

### ISSUE THREAD

**Issue by AmirRouteFinder3** [Project-OSRM/osrm-backend#6191]
50267,27780,32,30.3     <- duration will be updated, weight will be updated with 30.3*length
25296,25295,24          <- duration will be updated, weight will be updated to match duration
34491,34494,3,          <- duration will be updated, weight will be unchanged
2837,23844,3,,junk      <- duration will be updated, weight will be unchanged, junk is ignored
1283974,2387,3,junk     <- will cause an error

Hello, I saw this table in the traffic doc and the first raw seems missleading to me. Isn't the weight adjusted with length / 30.3? This is what I saw while inspecting the code.

**Comment by mjjbell** [comment]
Yes, the [Traffic page](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) appears to be incorrect.

The fourth column represents the segment `rate`, which is described in the [profile](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md#understanding-speed-weight-and-rate) docs as:

> The rate is an abstract measure that you can assign to ways as you like to make some ways preferable to others. Routing will prefer ways with high rate.
> 
> The weight of a way is normally computed as length / rate. The weight can be thought of as the resistance or cost when passing the way. Routing will prefer ways with low weight.

So the weight will be calculated as `length/30.3` as you suggest. Thanks for spotting.

**Comment by mjjbell** [comment]
Traffic page updated.

**Comment by ccodeguru123** [comment]
25296,25295,24 <- duration will be updated, weight will be updated to match duration
This line is unclear to me, what is the formula applied to match the weight to duration?
