### ISSUE TITLE
Question regarding rates and weight_name='routability'

### ISSUE THREAD

**Issue by AmirRouteFinder3** [Project-OSRM/osrm-backend#6192]
Hello,

I have one question in regards to rates weight_name='routability'.
What is the difference between 'duration', 'routability' and 'distance'?
Providing a rate and 'routability' weight_name will the path be computed using the weights? and the weights computed as legnth/rate?
What about all other cases?
I could not find good documentation regarding this.

I guess my real question is if weight_name='routability' will the optimal path be computed as the sum all the resulted weights for each segment? And if provided the updates.csv file with speed and rates will the wieght of a street be equal with length/rate?

**Comment by mjjbell** [comment]
OSRM will always search for the optimal path using the segment weights. What can change is the meaning applied to the weights and how they are calculated.

The [profile docs](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md#process_wayprofile-way-result-relations) have a definition for rate:

> Routing weight, expressed as meters/weight (e.g. for a fastest-route weighting, you would want this to be meters/second, so set it to forward_speed/3.6)

Conversely (and as discussed in #6191), `weight = meters/rate`. 

Therefore for `duration` and `distance` we have the following:

weight_name | weight | rate | routing
--- | --- | --- | ---
duration  | seconds | meters/seconds (i.e. speed) | fastest duration route
distance |  meters   | meters/meters (i.e constant value of 1) | shortest distance route

`routability` is a special version of the `duration` fastest route, where additional penalties are added to weight values for segments which are not preferred. You can see how it's used in the [default profiles.](https://github.com/Project-OSRM/osrm-backend/search?l=Lua&q=routability)

As for why `rate` is used or needed in OSRM and doesn't just use the `weight` metric, I believe it enabled a more reliable map-matching algorithm. One of the old-timers can correct me on this though.

**Comment by AmirRouteFinder3** [comment]
Thank you so much! This helps me in understanding the concepts better!  👍
