### ISSUE TITLE
Version of OSRM project on the demo site

### ISSUE THREAD

**Issue by HitsuNabe** [Project-OSRM/osrm-backend#6196]
Hi, I'm having a problem. The latest version of OSRM builds different routes with the version you have on the demo. Is it possible to find out what version you have on the demo, or other reasons for this behavior?

**Comment by jcoupey** [comment]
Most likely this is related to the profile in use, see #6177. Other factors could be OSRM version indeed but also the OSM data extract version.

@datendelphin may comment on how to know which OSRM version the demo server runs (my guess would be current `master`).

**Comment by datendelphin** [comment]
Yes it is pretty close to master. You find the current versions linked from the about page: https://routing.openstreetmap.de/about.html
Probably slight differences in profile
