### ISSUE TITLE
arrival and departure directions

### ISSUE THREAD

**Issue by RegularnaMatrica** [Project-OSRM/osrm-backend#6197]
Is it possible to specify both arrival and departure direction for points (every point except start and end is intersection) in route service?

Use case of this is to choose angle of turns.

**Comment by danpat** [comment]
Yes, see the `bearings=` paramater in the documentation.

**Comment by RegularnaMatrica** [comment]
> Yes, see the `bearings=` paramater in the documentation.

Thank you for answer. I'am aware of `bearings` parametar. Using it I was only  able to put restriction on arrival or departure direction for each point and not both.
