### ISSUE TITLE
highway:turning_circle is not considered when a route

### ISSUE THREAD

**Issue by vasilyevd** [Project-OSRM/osrm-backend#620]
If there is a point on the road pointing to the possibility of reversal, it is ignored and the route goes by a different road.  In the OSM will be identified as highvay:
turning_circle

Here's a link to the example of describing the problem:
http://osrm.at/2WX 
   A left turn is prohibited. The route is laid across the bridge. And you can take a right turn to the site (which is ignored), turn around, and get to your destination.

![osrm1](https://f.cloud.github.com/assets/2834603/398994/0a10cb7e-a864-11e2-8030-05592c454e2a.jpg)

**Comment by daniel-j-h** [comment]
Routing over turning circles works by now, here's a test case:

http://www.openstreetmap.org/node/339860646#map=19/52.57299/13.37827&layers=D

![tc](https://cloud.githubusercontent.com/assets/527241/15652897/b7107b0c-2689-11e6-8c7f-34dd421ba8e6.png)

**Comment by mhicauber** [comment]
Quite old, but I'm stumbling on this issue today. I've updated some nodes in OSM to add the highway=turning_circle attribute, but OSRM won't let vehicles turn around.
I want to allow public bus to turn around in some remote country area, where they will turn around at the kids houses after picking them up.
Is there anything else to add ? 

Here's an exemple : https://www.openstreetmap.org/edit?relation=115162#map=21/45.50478/1.30020
The bus coming from the north turns around in front of the house.

Thank you.
