### ISSUE TITLE
Missing v5.26.0 tag in DockerHub

### ISSUE THREAD

**Issue by sgarcez** [Project-OSRM/osrm-backend#6201]
Not sure what version the `latest` tag refers to, the latest version tag is `v5.25.0`.

https://hub.docker.com/r/osrm/osrm-backend

**Comment by mjjbell** [comment]
The automated Docker build was broken during the `v5.26.0` release. See https://github.com/Project-OSRM/osrm-backend/issues/6134#issuecomment-929018194 for how to build it manually.
