### ISSUE TITLE
OSRM Node high response times but CPU usage is low

### ISSUE THREAD

**Issue by resulyrt93** [Project-OSRM/osrm-backend#6202]
Hi,

I am using OSRM Node and table service on AWS EKS and i am suffering high response times on slightly large duration/distance matrices (100x100). Small d/d matrices are not waiting too much. If payloads increase, i expect CPU or memory usage to increase, but instances cannot auto scale up because it does not. 

Note: I'm using AWS EFS for store map datasets. And i'm using MLD algorithm.

```
100-120 Requests per minute
100X100 matrices
0.5 Core and 5GB RAM (dataset ≈ 2GB) => Response time ≈ 6-8 sec
CPU utilization %5-10
Memory %40
```

1. Maybe i should ensure to much CPU core. But it's show approximately %5-10 usage. How can i detect tension on OSRM instances? I suppose memory is not true signal since it's included dataset. And cpu usage doesn't increase. 
2. If i would get same coordinate d/d matrices response time is low it's like it's caching result. If i testing random and irrelevant coordinates, response times is high. What kind of structure is here? Does it do a caching of recently requested regions?
3. Extra question: I know that CH is fast from MLD algorithms, but I think it is not successful in terms of accuracy. If wrong, is there an issue where MLD is weak?

Thank you.

**Comment by datendelphin** [comment]
That sounds like it is swapping
