### ISSUE TITLE
How can i get max_speed in osrm response?

### ISSUE THREAD

**Issue by mehdi1171** [Project-OSRM/osrm-backend#6203]
Hi every one.
i try to get **max_speed** of any road during the routing and show it in (Json) response. Example , for any legs we have information about, duration,distance, weight,....also i need to show max speed of any leg in response! 
how can i do it ?
which are files need to change and modify?

**Comment by SamuelBrucksch** [comment]
Related:
https://github.com/Project-OSRM/osrm-backend/issues/6281
https://github.com/Project-OSRM/osrm-backend/issues/5286
