### ISSUE TITLE
Parameters for setting up osrm servers all over the planet

### ISSUE THREAD

**Issue by levanluu** [Project-OSRM/osrm-backend#6205]
Hi,
What are the actual system requirements for the latest planet.osm.pbf?
how much Ram, how much memory do i need to run it
currently i have 64GB Ram, 200GB swap, and 60GB free memory
can you give it a stable estimate?

same question as this issue, but no exact answer about it yet
https://github.com/Project-OSRM/osrm-backend/issues/1845

thank you

**Comment by nilsnolde** [comment]
see this latest update from late last year: https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements
