### ISSUE TITLE
notify systemd when ready

### ISSUE THREAD

**Issue by woodpeck** [Project-OSRM/osrm-backend#6206]
I have a setup where there are several backend machines behind a load balancer; each backend machine runs an Apache web server which forwards requests to osrm-backend.

I would like to configure my systemd to start the Apache server only after osrm-backend is fully started up and accepting requests (because otherwise the load balancer will assume that, because Apache is up, it can send requests to this backend machine, and these requests will fail because OSRM isn't ready yet).

This would require a call to `sd_notify(0, "READY=1");` somewhere here https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/src/tools/routed.cpp#L307 (and introduce a dependency on libsystemd). 

Is this a pull request the maintainers would accept?

An alternative way to solve my problem would be writing a stand-alone osrm-backend wrapper that executes osrm-backend setting `SIGNAL_PARENT_WHEN_READY`, and then when https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/src/tools/routed.cpp#L310 triggers a SIGUSR1, call `sd_notify` from the wrapper. 

I'm happy to work on this, just wanted to ask for opinions first, or maybe someone has solved the issue in a different way?

**Comment by TimMcCauley** [comment]
What happens if you fire a request to the backend service while it is starting up? Will it somehow let you know that it isn't ready? I am asking because then you could potentially make it work using Apache watchdog/loadbalancer health checks https://httpd.apache.org/docs/2.4/mod/mod_proxy_hcheck.html

**Comment by woodpeck** [comment]
The backend will not even listen on the port while not started up, so you get a "connection refused" which the Apache proxy will translate into a "503 service unavailable". Come to think if it, it would probably be sufficient if the outside load balancer's "alive" request would, instead of just querying for `/` or something, make a request that is actually caught by the proxy rule and forwarded to the `osrm-backend` process. But I wouldn't want to compute something expensive for every alive request. So maybe I'd have to add a "ping" service or something to `osrm-backend` for that?

**Comment by TimMcCauley** [comment]
Could this even be a little easier? Apache is your load balancer. The osrm workers are running without Apache. Your Apache LB is configured something similar to this:

```
<Proxy balancer://osrm>
  BalancerMember http://osrm_worker1:port/ hcmethod=TCP hcinterval=5 hcpasses=2 hcfails=3
  BalancerMember http://osrm_worker2:port/ hcmethod=TCP hcinterval=5 hcpasses=2 hcfails=3
  BalancerMemberN...
</Proxy>

ProxyPass "/" "balancer://osrm"
ProxyPassReverse "/" "balancer://osrm"
```

From the docs: "the osrm workers are checked every 5 seconds by simply ensuring that the socket to that server is up. If the backend is marked as "down" and it passes 2 health check, it will be re-enabled and added back into the load balancer. It takes 3 back-to-back health check failures to disable the server and move it out of rotation." So this basically is your "ping".

**Comment by datendelphin** [comment]
I use systemd to run osrm on routing.openstreetmap.de I would find that nice, if osrm signalled when ready, given the non negligible start up time.

**Comment by danpat** [comment]
Personally, I think an appropriately `ifdef`-ed addition of `sd_notify()` would be just fine to include.  Here's what I did on another project a while back.

CMakeLists.txt
```
find_library(SYSTEMD_LIBRARY systemd)
if (SYSTEMD_LIBRARY)
  find_file(SYSTEMD_INCLUDE systemd/sd-daemon.h)
  if (NOT SYSTEMD_INCLUDE)
    message("WARNING: found systemd libraries, but not sd-daemon.h.  Not enabling systemd integration")
  else()
    add_definitions(-DHAS_SYSTEMD)
    target_link_libraries(your_target ${SYSTEMD_LIBRARY})
  endif()
else()
  message("SYSTEMD NOT FOUND")
endif()
```

In source:

```
#ifdef HAS_SYSTEMD
#include <systemd/sd-daemon.h>
#endif
```

and in the appropriate places, things like:
```
#ifdef HAS_SYSTEMD
    sd_notify(0, "READY=1");
#endif // HAS_SYSTEMD
```

**Comment by amandasaurus** [comment]
_(I work at the same place as @woodpeck, Geofabrik)_

> One option that wouldn't involve modifying `osrm-routed` to emit `sd_notify()`, would be to use `systemd`'s `ExecStartPost` with a command like this:

In the end, I have used this approach, but I use:

```systemd
ExecStartPost=/usr/bin/timeout 60m sh -c 'while ! curl --max-time 0.2 -s -o /dev/null http://127.0.0.1:PORT/ ; do sleep 1 ; done'
TimeoutStartSec=2h
```

with `PORT` being the TCP port you run `osrm-routed` on. IME, it takes ~20 minutes to start up, so the `TimeoutStartSec` needs to be raied from it's default of ~2 minutes. I also chose `curl` rather than `ss`, because it seems more based on what I want to check (which is “Is this answering HTTP on port `PORT`?”).

---

> it would probably be sufficient if the outside load balancer's "alive" request would, instead of just querying for `/` or something, make a request that is actually caught by the proxy rule and forwarded to the `osrm-backend` process. But I wouldn't want to compute something expensive for every alive request

I have also changed our load balancer's health check to be a proxy to OSRM `/nearest/v`1/car/LAT,LON`. IME it computes very fast, and it improves our LB.
