### ISSUE TITLE
can  i    run osrm-routed  tow cities  osrm  file  in  one docker container

### ISSUE THREAD

**Issue by jaxsu** [Project-OSRM/osrm-backend#6209]
can  i    run osrm-routed  tow cities  osrm  file  in  one docker container

**Comment by jcoupey** [comment]
The recommended way to deal with multiple OSM extracts is to merge them in a single file before OSRM processing. This way, you end up with a single set of *.osrm* files covering several places.

Several tools are available to do this, look at e.g. the `osmium merge` command https://docs.osmcode.org/osmium/latest/osmium-merge.html.

**Comment by jcoupey** [comment]
Closing as answered.
