### ISSUE TITLE
Osrm route issue

### ISSUE THREAD

**Issue by nurikk** [Project-OSRM/osrm-backend#6216]
Hello! I have a osm data file merged from a few another files, it included CA Quebec, Turkey and some SEA countries.
After I'm running `osrm-extract` + `osrm-contract` i'm starting `osrm-routed` with ch algorithm. The problem is when I'm trying to route somewhere where I don't have map data, it gives me a very strange route
<img width="1019" alt="Screenshot 2022-03-07 at 11 44 45 AM" src="https://user-images.githubusercontent.com/1525421/156964314-fac6ac5d-3c9e-4f08-b177-59ee9b206949.png">
[response.json.txt](https://github.com/Project-OSRM/osrm-backend/files/8194618/response.json.txt)

This is odd behaviour. I expected to get exception NoRoute or something more adequate, even Haversine straight route, but not what I'm getting

Appreciate any help

Probably same root cause as https://github.com/Project-OSRM/osrm-backend/issues/6174

**Comment by danpat** [comment]
The result hints that your OSM data isn't merged right - only the data in Turkey appears to be present (at least, that's the closest snappable edges to your input).

You can try adding `radiuses=100;100` parameters to your requests - this will cause OSRM to refuse to snap more than 100m from the inputs, which in your case, would result in a NoRoute.

But first I'd check your OSM data is merged like you expect - OSRM should've snapped to your Québec data for inputs in the US....

**Comment by nurikk** [comment]
> The result hints that your OSM data isn't merged right - only the data in Turkey appears to be present (at least, that's the closest snappable edges to your input).
> 
> You can try adding `radiuses=100;100` parameters to your requests - this will cause OSRM to refuse to snap more than 100m from the inputs, which in your case, would result in a NoRoute (the default is `radiuses=unlimited;unlimited`).
> 
> But first I'd check your OSM data is merged like you expect - OSRM should've snapped to your Québec data for inputs in the US....

Hi, @danpat ! Thanks for advice. 

I've tested both ideas, indeed using radiuses=100;100 helps with snapping.
But true cause of this problem was incorrectly merged osm graph. I recreated it using **osmium** sort+merge and now everything works as expected (before I was using **osmosis**)
