### ISSUE TITLE
Routing via wrong port

### ISSUE THREAD

**Issue by JakobRogstadius** [Project-OSRM/osrm-backend#6217]
I am working with a national dataset of simulated cargo transports by truck. Goods flows were calculated in the model between pairs of regions. Routes were calculated based on origin-destination pairs using OSRM and a recent dump of OSM-europe.

In this picture, the simulated and routed flows (red) are compared against observed average daily traffic (gray). Part of the traffic between Stockholm and mainland Europe has been incorrectly routed via a port further south (green), while it should be routed via a port just south of Stockholm (orange). I am not sure if the problem is with OSM or with OSRM, but without knowing the inner workings of OSRM, I suspect it could have something to do with default weighting of the cost of travel by sea vs. the cost of travel by land.

https://risecloud-my.sharepoint.com/:i:/g/personal/jakob_rogstadius_ri_se/EU3eeRutm3JIkCAjmw5BHlIB_rxynXH-F3sHTJCBXPn-IQ?e=Pvb5qp

**Comment by JakobRogstadius** [comment]
Thank you. I will not pursue this further, but thought it could be an indication that the default values may need tuning.

**Comment by jcoupey** [comment]
Maybe the ferry values are more sensitive than others, but *"default values may need tuning"* usually applies for most of the choices hard-coded in the profiles, depending on the use-case, profile, area etc.

> I will not pursue this further

Closing then.
