### ISSUE TITLE
How to get more alternative routes?

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#6225]
Hello

I'm using OSRM v.5.25 (MLD algorithm). Most of the time I get one route and there's no alternative route in response. How can I increase it? Is there any parameter inside OSRM that I can change to tune it?

Thanks

**Comment by safe-bug** [comment]
I found the parameters here https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/routing_algorithms/alternative_path_mld.cpp#L37-L57

so I close the issue

**Comment by danpat** [comment]
Just a note on this ticket: most acceleration graphs, by their nature, reduce the number of reasonable alternatives that can be found - it's a fundamental tradeoff - the graph has been changed in shape and there aren't as many ways to get from A->B as there are in an un-modified graph.

@safe-bug Definitely play with the settings you found in `alternative_path_mld.cpp`, but don't be too surprised if either (a) the alternatives returned aren't very nice, (b), it takes a long time to find many, or (c) you still don't get very many.

**Comment by safe-bug** [comment]
@danpat Thanks for your complete explanation.

**Comment by safe-bug** [comment]
@danpat Is there any other solution for achieving more alternative routes?

**Comment by danpat** [comment]
@safe-bug not without a lot of work.  There's an extensive paper on techniques for finding alternative routes here:

http://algo2.iti.kit.edu/documents/Dissertation_Kobitzsch_Moritz.pdf

by a former OSRM contributor (@Mokob), but there's quite a lot of understanding and implementation work to do.

**Comment by safe-bug** [comment]
@safe-bug Thanks
