### ISSUE TITLE
OSRM distance table calls are returning duration table

### ISSUE THREAD

**Issue by rumirras** [Project-OSRM/osrm-backend#6226]
Hey folks,

I built my own OSRM service and I'm currently using it quite extensively for duration matrix requests. However, I need to add some front-end functionality that deppends on distances.

My first thought was to leverage the simple "annotations" attribute as follows:

`**http://router.project-osrm.org**/table/v1/driving/-9.1078027,38.7570457;-8.6532477,41.1163392;-9.248158,38.711381?annotations=distance`

This works quite well. However, when I switch it to my private service, the response comes with the "durations" matrix instead of the "distance" one. My request is being done exactly in the same way I'm doing the previous one, just changing the Host:

`**<MY_HOST>**/table/v1/driving/-9.1078027,38.7570457;-8.6532477,41.1163392;-9.248158,38.711381?annotations=distance`

Some context info:

- PBF file: http://download.geofabrik.de/europe/portugal-latest.osm.pbf
- Install commands:
`#!/bin/bash
cd /opt
osrm-extract -p /opt/car.lua /data/portugal-latest.osm.pbf
osrm-partition /data/portugal-latest.osm
osrm-customize /data/portugal-latest.osm
osrm-routed --algorithm mld --max-table-size 1000 /data/portugal-latest.osm
###########`

**Comment by danpat** [comment]
Are you running at least OSRM 5.18 locally?  The annotations feature was only added then: https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#5180

**Comment by ruimirrasantos** [comment]
@danpat, this is my Dockerfile:

`##Dockerfile##
FROM osrm/osrm-backend
EXPOSE 5000
RUN apt update && apt install -y wget && mkdir -p /data && cd /data && wget http://download.geofabrik.de/europe/portugal-latest.osm.pbf
##above is the data feeding step which is required from url [1] ##
ADD script.sh /opt
ENTRYPOINT ["/bin/bash", "/opt/script.sh"]
#####`

I thought this was getting the latest automatically, no?

**Comment by ruimirrasantos** [comment]
Hi all! Can you please help here. I don't understand why this is not working. It seems to be an actual bug in the implementation. I already tried to force the version and can't get the distance table out of the service.
