### ISSUE TITLE
Returning values outside of OSRM functions in node.js

### ISSUE THREAD

**Issue by MaximCamilleri** [Project-OSRM/osrm-backend#6227]
I'm trying to use the OSRM package to calculate routes between to points. To do this i first want to run the points trough the nearest function:
```js
osrm.nearest(options, function (err, response) {
    console.log(response.waypoints[0]["location"]);
});
```
, and then trough the routing function. is there a way to return values outside of the OSRM function so they can be used elsewhere? I'm looking for something alone these lines:

```js
let x = osrm.nearest(options, function (err, response) {
    console.log(response.waypoints[0]["location"]);
});

console.long(x.response.waypoints[0]["location"]) // should print the same thing as the console.log() inside the function 
```

Any help is greatly appreciated

**Comment by danpat** [comment]
@MaximCamilleri This is not how it works at all - OSRM's functions are asynchronous, so `response` is only valid inside the callback function `function(err, response)`.

You might want to read up on how asynchronous coding works in the NodeJS environment here:

https://nodejs.org/en/knowledge/getting-started/control-flow/how-to-write-asynchronous-code/

**Comment by MaximCamilleri** [comment]
hi @danpat. Sorry for the stupid question I'm relatively new to the NodeJs environment. Thanks for your help.

**Comment by thelazyoxymoron** [comment]
Posting this in case anyone else wants to do something similar - you can wrap the osrm function to resolve to a promise.

```
export const calculateDistance = async (props) => {
    return new Promise((resolve, reject) => {
        // define your options
        osrm.table(options, (err, result) => {
            if (err) reject(err);

            const distance = result.distances
            resolve(distance);
}

const distance = await calculateDistance(coordinates);
```
