### ISSUE TITLE
Table service query

### ISSUE THREAD

**Issue by rcatlord** [Project-OSRM/osrm-backend#6228]
Hi - I'm using OSRM to create some drive-time polygons and wondered whether the [Table service](http://project-osrm.org/docs/v5.5.1/api/#table-service) uses real-world or optimal vehicle speeds? I'm guessing the latter but any confirmation would be really helpful. Thanks!

**Comment by systemed** [comment]
OSRM generally doesn't have real traffic data (unless you feed it with some yourself) so it's the latter.

**Comment by SiarheiFedartsou** [comment]
Closing as stale.
