### ISSUE TITLE
Match service does not snap to the nearest road

### ISSUE THREAD

**Issue by ThomasWilliamWallace** [Project-OSRM/osrm-backend#6230]
Dear OSRM team,

Firstly, thanks for your hard work on this tool!

# The Issue
I have been trying to use the OSRM 'match' service, and have been getting unexpected results, where 
the input GPS points have not been snapped to the nearest road.
Here is a minimal (artificial) example:
```
curl "https://router.project-osrm.org/match/v1/driving/-3.0144360400000001,51.5750787699999975;-3.0144610400000000,51.5750846600000017;-3.0144510699999998,51.5750888999999972?radiuses=10.0;10.0;10.0"
```
These 3 input points have been snapped to the bottom road, when there is a clearly another road closer to them.
Here are the output tracepoints.
![snapped_incorrect](https://user-images.githubusercontent.com/10775660/162744700-e2907868-ce39-479e-96b1-7e2f70f21601.png)

If I reduce the radius parameter:
```
curl "https://router.project-osrm.org/match/v1/driving/-3.0144360400000001,51.5750787699999975;-3.0144610400000000,51.5750846600000017;-3.0144510699999998,51.5750888999999972?radiuses=1.0;1.0;1.0"
```
they snap to the expected road. But I'm hoping to use a larger radius value, to match when further from the road.
![snapped_correct](https://user-images.githubusercontent.com/10775660/162743717-147e65ad-8ba1-4a19-b3f6-8fc7ab4b8657.png)

If I use no radius value at all:
```
curl "https://router.project-osrm.org/match/v1/driving/-3.0144360400000001,51.5750787699999975;-3.0144610400000000,51.5750846600000017;-3.0144510699999998,51.5750888999999972"
```
the output is still not as expected.
![partially_incorrect](https://user-images.githubusercontent.com/10775660/162743669-53ae8e83-d6dc-4856-8d73-fc7c44a9db80.png)

In general, this problem seems to occur when I have several input GPS points very close together, maybe going forwards and backwards (this happens when the vehicle is stationary, and the GPS points are wandering due to noise).

Requests and responses for each example are attached:
[request_and_response.txt](https://github.com/Project-OSRM/osrm-backend/files/8463394/request_and_response.txt)

# What I've tried

* I've checked the OSM tags for these two streets, and don't see any clues.
* I've have tried using a simplified OSM file, with no other roads or tags, and still find the same issue: 
[minimal OSM file](https://github.com/Project-OSRM/osrm-backend/files/8464329/newport_example.osm.txt)

* I've also tried modifying the lua profile, setting the `u_turn_penalty` to 0, setting `continue_straight_at_waypoint` to false and setting `turning_penalty` to 0.
* I've tried using the pedestrian lua profile.

None of these fixed the problem- I couldn't get all 3 points to match to the nearest road.

---

I'm wondering if I've misunderstood how the matching is meant to work?
I understand that matching will not always snap each point to the nearest road, but will attempt to find the best match across the whole input sequence. But I would have thought that if all the inputs are near a road, the outputs would be snapped to the same road. The above example is trivial, but I have more complex cases which seem to be failing in the same way.
Hopefully you can shed some light on this.

Regards,
Thomas

**Comment by ThomasWilliamWallace** [comment]
In https://github.com/Project-OSRM/osrm-backend/pull/1407, it is recommended:

> You should make sure to remove blobs (accumulated GPS points, when standing still)

So it seems that this is a known issue. In this case, I will try removing the stationary points as suggested.
Closing since I found an answer.

**Comment by danpat** [comment]
You can try using the `tidy=true` parameter, which will try to remove some of the forward/backward noise.

http://project-osrm.org/docs/v5.24.0/api/#match-service
