### ISSUE TITLE
Docker Hub 5.26.0 tag

### ISSUE THREAD

**Issue by t-tomek** [Project-OSRM/osrm-backend#6231]
Can you provide v5.26.0 tag on DockerHub?

Currently osrm/osrm-backend:latest image provides OSRM 5.26.0, but there's no such tag.
I cannot rely on :latest tag only. If I rebuild my image with :latest tag and it points to 5.27.0, I will end up with incompatible version error like this:

` [error] File is incompatible with this version of OSRM: car.osrm.icd prepared with OSRM 5.26.0 but this is v5.27.0`

I have already encountered such problem when my data was prepared with 5.24.0 version but my image (using :latest tag) was automatically rebuild with 5.26.0 version. Now I want to avoid this and stick to version 5.26.0

**Comment by mjjbell** [comment]
This project no longer has access to Docker Hub due to a change in their Terms of Service. The loss of access prevented the `v5.26.0` tag being pushed to Docker Hub during that release.

Docker Hub will be replaced with Github Container registry for the `v5.27` release (#6325). If you need a `v5.26` container, you should build and tag a container locally.

**Comment by tekeroth-snapcode** [comment]
Or if perhap @mjjbell would find it in his heart to put an image of 0.5.26 for the world to use? Would that be hard or you to do? :-D

I run commands like:

`docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf || "osrm-extract failed"`

and I guess the change would then be

`docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend:v0.5.26 osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf || "osrm-extract failed"`

if you would be able to put it up =)

**Comment by tekeroth-snapcode** [comment]
Update:

Actually, by cloning the [OsrmNet repo](https://github.com/osrmnet/osrmnet), you will get a ZIP-file  (in \libosrm\redist) containing binaries for Win 0.5.26.

Those files can be executed the same way as the docker instructions (same flags args etc), and doing that will produce osrm files that can be used with stuff that requires 0.5.26 (like osrmnet currently).
