### ISSUE TITLE
Upgrade to bullseye

### ISSUE THREAD

**Issue by abudis** [Project-OSRM/osrm-backend#6232]
Hey all 👋 ,

Is there a planned date for upgrading the osrm-backend Docker image to use debian:bullseye? I see that the image in master is using that already, however not really sure in which release this is going to be added.

Thanks in advance!

**Comment by SiarheiFedartsou** [comment]
I think it will be available in 5.27 https://github.com/Project-OSRM/osrm-backend/issues/6325
