### ISSUE TITLE
Is there any possibility to solve time dependent shortest path?

### ISSUE THREAD

**Issue by MINIMALaq** [Project-OSRM/osrm-backend#6233]
Is there any possibility to solve time dependent shortest path in OSRM feeding a dynamic graph?

**Comment by danpat** [comment]
No, OSRM implements non-time-dependent Contraction Hierarchies (CH), and Multi-Level Dijkstra (MLD).

**Comment by MINIMALaq** [comment]
> No, OSRM implements non-time-dependent Contraction Hierarchies (CH), and Multi-Level Dijkstra (MLD).
I know. I mean is it possible to develop some extra module for that and make it using dynamic weight for network graph? or it is not possible at all with the current structure of OSRM.

**Comment by danpat** [comment]
@MINIMALaq I mean, anything is possible if you have enough time.  There is a time-dependent version of the CH algorithm (http://algo2.iti.kit.edu/documents/routeplanning/tch_alenex09.pdf).  It would involve some fairly major surgery to the code to implement.

**Comment by MINIMALaq** [comment]
At the end of the day, I want a time dependent tsp that works on osm graph. Do you know any package that can help me for that?

**Comment by nilsnolde** [comment]
https://github.com/valhalla/valhalla

possibly in conjunction with https://github.com/VROOM-Project/vroom

**Comment by MINIMALaq** [comment]
> https://github.com/valhalla/valhalla
> 
> possibly in conjunction with https://github.com/VROOM-Project/vroom


Unfortunately they are not time dependent.

**Comment by nilsnolde** [comment]
How did you come to that conclusion? Might be that not everything you’re looking for is actually respected (eg IIRC time dependent access restrictions might still not be), but of course Valhalla has (mostly) proper time support.

**Comment by danpat** [comment]
@nilsnolde having looked very recently at Valhalla's `/sources_to_targets` - it's not time-dependent either :-P  I don't think VRoom has time-dependent support either, but @jcoupey can speak more to that.

@MINIMALaq time-dependent TSP is a much harder problem to solve, so there aren't many (if any?) open implementations.  I've certainly read papers where people have done it, but afaik none of the popular open routing/optimization solutions do it.

**Comment by nilsnolde** [comment]
Argh crap that’s true, totally overlooked that, apologies @MINIMALaq 😅

still, if you need it badly and have the (processing) time, you can use the time dependent routing and vrooms custom matrix input.

**Comment by MINIMALaq** [comment]
@nilsnolde I didn't used vrooms custom matrix before. Thank you for the comment. I will check it out. I hope it can solve the time dependent tsptw.

**Comment by jcoupey** [comment]
> I hope it can solve the time dependent tsptw.

No, feeding custom matrices to VROOM simply means bypassing OSRM for calculating the travel time matrices. In any case, taking time-dependency into account *at the optimization level* would require a major overhaul for VROOM (and any other such solving engine). That would also probably be a killer for performance.

There are different things at stake here: time-dependent routing means you'll take into account different situations along the route (e.g. traffic when arriving in Paris 3 hours from now). Even if you do this, that's still a single entry in your travel time matrix for optimization. What you want for real time-dependent TSPTW is a way to access this value as a function of time across the day. A corollary is that if you have mostly short trips and can do the approximation that traffic conditions don't change radically during a single trip, then you don't really need time-dependent routing. In that case you may use static routing with different traffic patterns, which would leave you with *only* the problem of time-dependency at the optimization level.
