### ISSUE TITLE
wget with a bounding box

### ISSUE THREAD

**Issue by shitathakin** [Project-OSRM/osrm-backend#6235]
Hi. I want to use a limited area within a geofabrik dataset.

I am wondering if I can use a wget call with a boundig box limitation. 

e.g. 
````
wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf&bbox=144.887112,-37.856539,145.012768,-37.770152
````

Thanks.

**Comment by datendelphin** [comment]
No, that is not a feature of the geofabrik download. You can use [osmium-tool](https://docs.osmcode.org/osmium/latest/osmium-extract.html) for that locally, or for very small areas you could use the [overpass api](https://wiki.openstreetmap.org/wiki/Overpass_API#The_map_query).
