### ISSUE TITLE
Instead of driving time the command is giving walking time between two lat longs in case of bike & car both

### ISSUE THREAD

**Issue by anjali2701** [Project-OSRM/osrm-backend#6239]

**Comment by jcoupey** [comment]
If you want help, you'll have to provide some more context. What do you mean by "the command", i.e. how are you using OSRM precisely?

**Comment by datendelphin** [comment]
router.project-osrm.org delivered the wrong profile. Please do not use that domain anymore. Fixed

**Comment by anjali2701** [comment]
Now started giving 502 error

r = requests.get(f"http://router.project-osrm.org/route/v1/bike/{lon_1},{lat_1};{lon_2},{lat_2}?overview=false""")
