### ISSUE TITLE
filtering out isolated islands, and still returning detailed geometry

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#624]
working on our iOS app, we have a problem when requesting routes.

when  we request a route, we need to use low z to make sure start/end marker does not get stuck in a small isolated island, but we need high z to get a detailed route geometry. but this is not possible in a single request.

would it be possible to add an option that filters out small isolated island when searching for start/end location (=low z), but at the same time returns detailed geometry (=high z)?

does nearest/ and locate/ filter our isolated islands?

**Comment by TheMarex** [comment]
This is obsolete as the `z` parameter does not affect snapping anymore.
