### ISSUE TITLE
Car routing api not working

### ISSUE THREAD

**Issue by philipphueber** [Project-OSRM/osrm-backend#6240]
as of today any requests to the /routing-car/ api return code 502

**Comment by datendelphin** [comment]
Only car europe and asia, but yes, that region is crashing currently on the demo server routing.openstreetmap.de

**Comment by MariaSKAF** [comment]
Does anyone know when this will be fixed, such that it can be used again?

**Comment by Spiekerooger** [comment]
@MariaSKAF : you may use www.osmap.asia with an active car profile worldwide for as long as datendelphin needs to fix this. German version can be found at www.osmap.at.

**Comment by MariaSKAF** [comment]
@Spiekerooger do you know if www.osmap.asia can be used through python with Request? Like i did below:

`r=requests.get(f"http://router.project-osrm.org/route/v1/car/{10.084395},{56.47156};{10.0650909},{56.43045}?alternatives=false&steps=true&overview=false""")`

**Comment by Spiekerooger** [comment]
@MariaSKAF I just set this up, this would be the address:

`r=requests.get(f"http://osrm-demo.routingapi.net/routing-car/{10.084395},{56.47156};{10.0650909},{56.43045}?alternatives=false&steps=true&overview=false""")`


Can you tell me if this working? It will be rate limited though.

**Comment by philipphueber** [comment]
> @Spiekerooger do you know if [www.osmap.asia](http://www.osmap.asia) can be used through python with Request? Like i did below:
> 
> `r=requests.get(f"http://router.project-osrm.org/route/v1/car/{10.084395},{56.47156};{10.0650909},{56.43045}?alternatives=false&steps=true&overview=false""")`

[www.osmap.asia](http://www.osmap.asia/) and (http://www.osmap.at/) did not work for me, 
However it looks like the error is fixed and the normal systems are back up and running

**Comment by philipphueber** [comment]
api working again

**Comment by MariaSKAF** [comment]
@Spiekerooger yes it is working, thanks for the help!
