### ISSUE TITLE
Tile service export png/jpg instead of mvt

### ISSUE THREAD

**Issue by djulbicb** [Project-OSRM/osrm-backend#6241]
Hello,
I would like to propose a feature implementation.

Adding an export option to tile service so it exports an image and not just a mvt file

This would allow users to use osrm-backend with frontend tiling frawemorks that use images and not vector.
For example leaflet would be enough, you wouldnt have to use mapbox gl....

I've researched a bit is this possible. Noticed this git repo
https://github.com/tumic0/QtPBFImagePlugin
https://github.com/Overv/openstreetmap-tile-server
Its a c++ implementation, plus it provides neat visualizations

The output of the function should be an image base64 encoded stream, 
which can be specified as img source in html

What is your opinion, would this be ok?

I am a java dev, no c++ skills. Tried to do it in java. 
Created a java middleware service that fetches mvt tile from osrm-backend and converts to 255x255 png. Seems legit. The speed seems ok, and right now it just simple wiremap.

If it sounds like a good idea,
maybe even i could try to do it in c++, if no volunteers. 

Also to creators of this osrm build, it really awesome. Like really cool.

**Comment by djulbicb** [comment]
Related question - 
Is it possible to specify layers that will be included in mvt file?
right now layers are speeds and osmnodes

**Comment by systemed** [comment]
Building a raster tile renderer into OSRM would seem like a bit of a stretch from the core purpose of the project. I'd suggest if you really want to have raster tiles, then the middleware approach you describe is better.
