### ISSUE TITLE
Multi Via Maneuver Support

### ISSUE THREAD

**Issue by YashowardhanTripathi** [Project-OSRM/osrm-backend#6243]
Hi, Now we have single via maneuver support if it possible to get turn into multi via support.

**Comment by mjjbell** [comment]
It is already supported. It happily parses multiple via ways.

https://github.com/Project-OSRM/osrm-backend/blob/79d4363d5972ea4d69abd92b26cda80de7941365/src/extractor/maneuver_override_relation_parser.cpp#L101-L103

However, there are a few open issues related to maneuver support.
See #6126 and #6215

**Comment by SiarheiFedartsou** [comment]
Closing as it seems we are done here(feel free to re-open though)
