### ISSUE TITLE
Lower RAM configuration is querying faster than higher RAM configuration 

### ISSUE THREAD

**Issue by kk2491** [Project-OSRM/osrm-backend#6247]
Hi All,

Good day.

We have hosted the OSRM server in the GCP. And trying to find the best cost effective configuration for the VM.  
While doing the tests we noticed that the VM with lower configuration is performing better in terms of the query time compared to VM with higher configuration.

Could you please help me in understanding if there is a specific technical reason for this?

Thank you,  
KK

**Comment by danpat** [comment]
I mean, you need to look at what's different.  Different CPU classes?  What about memory bandwidth/type?

Unfortunately in cloud environments, some of those low-level details may be abstracted away from you by the virtual machine interface.  Depending on what _type_ of VM you're launching, the underlying hardware may differ from launch to launch, leading to different performance.

If you disable swap (and you should), then OSRM performance will likely be dominated by CPU cache sizes, CPU frequency/efficiency, and memory latency and bandwidth.  Total amount of RAM is not that important once you go past the minimum.
