### ISSUE TITLE
question about libosrm

### ISSUE THREAD

**Issue by hogan-chu** [Project-OSRM/osrm-backend#6251]
Dear osrm contributors and osrm users

OSRM can be used as a library (libosrm) via C++ instead of using it through the HTTP interface and osrm-routed. This allows for fine-tuning OSRM and has much less overhead. Here is a quick introduction into how to use libosrm in the upcoming v5 release.

i found this and i implemented following code 
i have a question i want to use osrm-backend without https and i want to create libosrm.so for cython is there any reference that is compatible with latest release or binding? 

kind regards

**Comment by SiarheiFedartsou** [comment]
Stale.
