### ISSUE TITLE
Need truck.lua profile

### ISSUE THREAD

**Issue by gokumar** [Project-OSRM/osrm-backend#6254]
Is there a profile for truck that I can utilize? I need routing for trucks whose size vary from 3 wheeler to 22 wheeler.

**Comment by jcoupey** [comment]
Did you take a look at https://github.com/Project-OSRM/osrm-profiles-contrib?

**Comment by gokumar** [comment]
> Did you take a look at https://github.com/Project-OSRM/osrm-profiles-contrib?

Thank you so much for sharing this
