### ISSUE TITLE
One OSRM server for two modes of transportation?

### ISSUE THREAD

**Issue by Tagar** [Project-OSRM/osrm-backend#6255]
Is this possible to run one single OSRM server for both driving and walking modes? 

https://github.com/Project-OSRM/osrm-backend

Documentation has an example with nginx routing between two OSRM backends - one of driving, and another for walking. We'd like to avoid that and only run one backend for different modes of transportation.

Thanks

**Comment by nilsnolde** [comment]
short answer is: no. few foss routing engines can do that and always at the expense of runtime costs (i.e. takes longer to finish a request). but there is pgrouting (pinnacle of flexibility, relatively slow) & valhalla (good trade-off between flexibility & performance).
