### ISSUE TITLE
Configure car.lua to ignore "oneway" tags

### ISSUE THREAD

**Issue by RodrigoVm7** [Project-OSRM/osrm-backend#6256]
Hi, i need to use OSRM for emergency vehicles (ambulances and firetruck) and these types of vehicles can ignore certain traffic rules. Is there a way to configure the "car.lua" profile to ignore "oneway" tags? Thanks!

**Comment by danpat** [comment]
Change this line: https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L34
