### ISSUE TITLE
Indoor Navigation

### ISSUE THREAD

**Issue by dmenneck** [Project-OSRM/osrm-backend#6257]
I am currently facing the use case of navigating in buildings. Unfortunately I couldn’t find any examples so far and wanted to ask if some of you have already made experience with it and/or can estimate if indoor navigation with OSRM is possible.

The underlying OSM data will be tagged with schemas like IndoorOSM or Simple Indoor Tagging.

**Comment by datendelphin** [comment]
Indoor navigation is usually a very small graph, So it could be done client side. For OSRM you would need a way to route across areas. There is for example plazaroute https://github.com/PlazaRoute/plazaroute/tree/master/plaza_preprocessing which can preprocess OSM data to include the edges, such that OSRM can be used afterwards.
