### ISSUE TITLE
Profile in demo API set to foot instead of car?

### ISSUE THREAD

**Issue by humblydone** [Project-OSRM/osrm-backend#6258]
Hi all,

I wish you all a joyful day. 

Since some time ago, I have used the open OSRM API for experimentation. I use URLs like below to get geometry and decode it to draw turn-by-turn polylines on a map.

https://router.project-osrm.org/route/v1/driving/-121.8863286,37.3382082;-121.988583,37.5485396?overview=full

Since yesterday, I notice that the above URL returns an output different from what it used to. Looking at the returned "duration" and how the path, from geometry, between the two points are drawn, I think the output is from walking instead of driving. (20-min. distance changed to 6-hr distance as well as a totally different route drawn)

I will eventually have to set up my own server, but for the time being, does anyone have insight into the change I have observed? And is there a way for me to get duration and geometry with the "car" profile?

Thank you :)

**Comment by anjali2701** [comment]
I am facing the same issue.

**Comment by datendelphin** [comment]
Please use

https://routing.openstreetmap.de/routed-car/...
https://routing.openstreetmap.de/routed-bike/...
https://routing.openstreetmap.de/routed-foot/...

The other url is going away

**Comment by humblydone** [comment]
> 

Thank you for your reply, @datendelphin 

Could you please provide more complete example URLs? I tried URLs starting with the new path you gave, but they all return InvalidUrl code. Thank you so much!

**Comment by humblydone** [comment]
Demo API came back as normal, returning car travel time and geometry. But I will test the example @datendelphin gave and use the links provided before I set up my own server. Thank you!
