### ISSUE TITLE
Showing Foot travel time instead of Car travel time 

### ISSUE THREAD

**Issue by anjali2701** [Project-OSRM/osrm-backend#6259]
r = requests.get(f"http://router.project-osrm.org/route/v1/driving/{77.383551},{28.643367};{77.358407},{28.648673}?overview=false""")

Result shows:
'duration': 3161.5,
 'distance': 3951.5}

For 4km distance, the time travelled is 52 min which is foot travel time & not the driving time. Please look into the issue

**Comment by humblydone** [comment]
Demo API finally returns car travel time again. But like @datendelphin mentioned and helped me in my [issue](https://github.com/Project-OSRM/osrm-backend/issues/6258), anyone using the API should form his/her URLs like the following:

https://routing.openstreetmap.de/routed-car/route/v1/driving/-121.8863286,37.3382082;-121.988583,37.5485396?overview=full
