### ISSUE TITLE
Wrong coordinates in query response

### ISSUE THREAD

**Issue by Uma-Jan** [Project-OSRM/osrm-backend#6263]
Hello i have a problem with the route service 

When i use this query : [https://router.project-osrm.org/route/v1/driving/50.5221624,3.0584663;50.77033742426383,3.0480335477976612?geometries=geojson](url)
to get the route between  [50.5221624,3.058466 ] and [50.77033,3.048033] the start and end coordinates change and give me the route between these two : [48.003968,4.551169] and [48.044733,4.619029] and i don't understand why. Because of that the routes i plot are nowhere near the place they are meant to be.

Here is the full response [`{"code":"Ok","routes":[{"geometry":{"coordinates":[[48.003968,4.551169],[48.001719,4.551332],[48.00202,4.553041],[48.00129,4.555009],[47.996663,4.560404],[47.995008,4.563706],[47.992938,4.564712],[47.992694,4.569626],[47.991771,4.571497],[47.98372,4.573688],[47.978133,4.57672],[47.977453,4.57823],[47.974201,4.581443],[47.968701,4.585432],[47.967049,4.588202],[47.960526,4.59232],[47.959144,4.594571],[47.959751,4.596892],[47.958973,4.598103],[47.95676,4.59956],[47.953091,4.599359],[47.94668,4.60122],[47.933621,4.609725],[47.925091,4.613847],[47.917817,4.619229],[47.910505,4.62263],[47.884906,4.640483],[47.879233,4.644204],[47.877257,4.644763],[47.892194,4.647255],[47.907922,4.653684],[47.918753,4.659296],[47.929332,4.657472],[47.942842,4.656999],[47.951068,4.655165],[47.957304,4.652008],[47.969533,4.647362],[47.983917,4.640633],[47.987858,4.637232],[47.996398,4.633091],[48.001956,4.632879],[48.003404,4.63145],[48.005434,4.63196],[48.008571,4.630092],[48.015939,4.62705],[48.01777,4.627092],[48.021319,4.624927],[48.026066,4.623305],[48.030422,4.623223],[48.031935,4.624171],[48.037754,4.623859],[48.039079,4.622768],[48.04046,4.622631],[48.042522,4.620136],[48.044733,4.619029]],"type":"LineString"},"legs":[{"steps":[],"summary":"","weight":25312.8,"duration":25312.8,"distance":38995.7}],"weight_name":"routability","weight":25312.8,"duration":25312.8,"distance":38995.7}],"waypoints":[{"hint":"W0qXhrFYmIZCAAAAAAAAAEMPAgAAAAAA4kYSQQAAAABkNJJGAAAAAEIAAAAAAAAAQw8CAAAAAABvFwAAgHvcAgFyRQAy6AIDIqsuAFUETwW-MqNb","distance":324773.6824,"name":"","location":[48.003968,4.551169]},{"hint":"yWsOiPJrDogqAwAAAAAAAC8xAAAAAAAAppngQgAAAAA2d9pEAAAAACoDAAAAAAAALzEAAAAAAABvFwAAvRrdAhV7RgChsQYDYoIuABMAvwe-MqNb","distance":349040.186345,"name":"","location":[48.044733,4.619029]}]}`]

Thank you in advance for your help !

**Comment by nilsnolde** [comment]
Wrong coordinate order. Other than leaflet most foss and data formats do (lon, lat), not (lat, lon).
