### ISSUE TITLE
Mason is unmaintained

### ISSUE THREAD

**Issue by nilsnolde** [Project-OSRM/osrm-backend#6266]
I'll leave that here as well: https://github.com/mapbox/mason. doesn't mean it's going away or will be broken anytime soon, but since OSRM [is slowly getting really out of date on dependencies](https://github.com/Project-OSRM/osrm-backend/issues/6264), sooner or later another solution will have to be found. 

from my experience, [`conan`](https://conan.io/center/tbb) could be ok, been using it a few times. on first glance tbb is from 2019, could be working still. rest of the libs should be less of a problem.

**Comment by SiarheiFedartsou** [comment]
I started migration to Conan here https://github.com/Project-OSRM/osrm-backend/pull/6284 
Would be great to have some initial feedback.

**Comment by nilsnolde** [comment]
Thanks a ton @SiarheiFedartsou! I’d be happy to give this a shot and bits of review where I can (no write permission to this repo though). This has the potential to get rid of the crappy windows deps setup and let us install it all with conan!

**Comment by SiarheiFedartsou** [comment]
Can be closed as we merged https://github.com/Project-OSRM/osrm-backend/pull/6284

**Comment by mjjbell** [comment]
Let's keep it open until we've completely removed it. It's still being used to install CI worker dependencies.
