### ISSUE TITLE
Include Traffic Data 

### ISSUE THREAD

**Issue by ayrus96** [Project-OSRM/osrm-backend#6267]
Hi,
Is there any way to give routing along with live traffic data in OSRM ?

if anything there means, please share your thoughts..

or any alternatives OSRM can do with traffic data in routing

**Comment by danpat** [comment]
There is a Wiki page that describes how to import current traffic data into OSRM for routing:

https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

You will need to find a source of such traffic data however.  They're not common.

**Comment by MumMumMum** [comment]
Hi,
If i gave here.com traffic update response to OSRM, will it give me rerouting with exact osm edges

**Comment by fullstartweiyi** [comment]
> Hi,
> If i gave here.com traffic update response to OSRM, will it give me rerouting with exact osm edges

Hi, do you know how to contact here.com to get traffic update? Just calling the api or contact them.
