### ISSUE TITLE
Get routing at a specific time stamp?

### ISSUE THREAD

**Issue by JulianHirsch** [Project-OSRM/osrm-backend#6268]
Hi, 

I wonder, if there is the option to specify a specific date, so that the osm data is used for routing that was valid at this specific time stamp. 
[Here is my OP in SO](https://stackoverflow.com/questions/72728337/use-specific-historic-attic-date-of-osm-data-in-osrm). 
I could not find any information on this topic.

Any help is appreciated. Thank you very much!

**Comment by legalsylvain** [comment]
Hi @JulianHirsch. Facing similar issue. Do you find a solution ? 
thanks !
