### ISSUE TITLE
Distributed shared memory usage

### ISSUE THREAD

**Issue by iedmrc** [Project-OSRM/osrm-backend#6269]
Hi all,

As far as I know, we have two options in terms of memory usage:

1. Mmap enabled, which stores data -if needed- in mapped files rather than RAM
2. Mmap disabled, which stores whole data in memory

But I want/need a 3rd option:

Store data in a distributed in-memory cache database and connect directly to it in order to consume the map. Is it possible? If not, are there any workarounds or works for it (maybe some branches, or other 3rd party developments etc..)

It would be pretty nice if we could've such a feature to decrease memory usage without losing memory read speed significantly, especially for the systems which work on Kubernetes.

**Comment by iedmrc** [comment]
Thanks for the answer! Actually, we are doing the same now and a file system significantly differs from a memory (ram-based) cache data even though they are both on the network. So having NFS attached (if containers' memory is set lower than required) causes terrible response times. But if we would have a redis-like in-memory data storage on the network rather than an NFS, it would significantly be better. So that's what I'm actually looking for.

**Comment by danpat** [comment]
The performance hit you're seeing with NFS likely won't be a whole lot better if OSRM was trying to read blocks from a remote redis-like instance - it's the added network round-trip that kills performance, not the fact that it's on disk or in RAM on a remote service.

The table below highlights the problem.  If you add "round trip within the same datacenter" (500,000 nanoseconds per round trip) to every time OSRM needs data access, you'll kill performance - OSRM relies heavily on data reads falling into the "Main memory reference" (100 nanoseconds) or "L? cache reference" (<10 nanoseconds) buckets.

![image](https://user-images.githubusercontent.com/1892250/176494995-85aaaa9f-a49a-47ba-a63e-53db8f6ddb22.png)

Using `mmap` against files accessed over a network requires a "warmup" step, and careful management of memory/disk access on your machine.  The first time a file is read over NFS, yes, access is slow.  But subsequent reads to the _same part of the file_ should be fast, as long as those `mmap`-ed pages are still in your local [page cache](https://en.wikipedia.org/wiki/Page_cache).

If your box has swap configured, turn it off.  If you only have a small amount of local RAM available on your nodes, try to make sure that OSRM instance is only handling requests from a limited geographic area - this means that only a small section of the large datafiles is accessed, and it may be possible for it all to eventually end up in the locale page cache on your nodes, leading to good performance.
