### ISSUE TITLE
Could not find any metrics for MLD in the data. Did you load the right dataset?

### ISSUE THREAD

**Issue by adhamenaya** [Project-OSRM/osrm-backend#6272]
Hi- I have run the OSRM server successfully on the AWS EC2 instance, after doing the steps:

```
1. osrm-extract --profile ../profiles/car.lua all1.osm.pbf
2. osrm-partition all1.osrm
3. osrm-customize all1.osrm
4. osrm-routed --algorithm=MLD all1.osrm
```

then I copied the volume of that instance (containing all generated OSRM files e.g., all1.osrm) to another instance. And only in the new instance I try to run the command 4: `osrm-routed --algorithm=MLD all1.osrm` but I get the following error:

```
terminate called after throwing an instance of 'osrm::util::exception'
  what():  Could not find any metrics for MLD in the data. Did you load the right dataset?
```

what prevents me from running the same steps again in the new instance is that the new instance has lower capacity and it will take a much longer time to process osm files again.

so, what I did do wrong here? and is there a way to move the configurations of OSRM from once machine/instance to another without the need to re-run the steps again?

thanks,

**Comment by danpat** [comment]
Did you check that your commands worked without error?  Make sure that all commands return with a 0 exit code to ensure they actually worked properly.  I've seen the error you quoted when the datafiles were incompletely generated.

**Comment by SiarheiFedartsou** [comment]
Stale.

**Comment by OrangeDog** [comment]
@danpat they must have done, because it worked on the machine they were processed on, but not the machine they were copied to.

I too have the same issue (data processed with Linux Docker image, loaded with Windows Python bindings), and have confirmed that all the commands completed successfully.
