### ISSUE TITLE
one to many 

### ISSUE THREAD

**Issue by ayrus96** [Project-OSRM/osrm-backend#6276]
Hi,
    I am looking for API to achieve one source to many destination in routing...
but table service api doesn't return any gemetry to view in map...
   
how can i solve this in OSRM?
any ideas??

**Comment by danpat** [comment]
You will need to make multiple calls to the `/route` service to get geometry for many routes like that.  The `/table` service does not generate the full path geometry (even internally, which is one of the reasons it's so fast).

**Comment by handcath** [comment]
Use osrm node-bindings. [https://github.com/Project-OSRM/osrm-backend#using-the-nodejs-bindings](url).

Wrap your source-destination combos in promises and use await Promise.all(promises) to obtain all resolved queries.
This is fast, an order of magnitude faster than issuing multiple requests to the http api.

**Comment by SiarheiFedartsou** [comment]
Stale.
