### ISSUE TITLE
Distance Matrix Problem

### ISSUE THREAD

**Issue by aakokgetir** [Project-OSRM/osrm-backend#6277]
Hi,

I am trying to get distance matrix for 12 points. I have this [query](https://routing.openstreetmap.de/routed-foot/table/v1/foot/27.594375,37.234549;27.594341,37.234487;27.594330,37.234474;27.594200,37.234365;27.595673,37.234703;27.597251,37.234439;27.594560,37.232003;27.591030,37.234985;27.595501,37.237260;27.606180,37.235031;27.606651,37.236002;27.786632,37.310617?sources=0&annotations=distance). In the result, first 9 destinations are snapped into same position which are at least 3.3 km away from the original destinations and for last 3 destination osrm was unable to find route.

But if I remove the last destination from [query](https://routing.openstreetmap.de/routed-foot/table/v1/foot/27.594375,37.234549;27.594341,37.234487;27.594330,37.234474;27.594200,37.234365;27.595673,37.234703;27.597251,37.234439;27.594560,37.232003;27.591030,37.234985;27.595501,37.237260;27.606180,37.235031;27.606651,37.236002?sources=0&annotations=distance), Osrm is able to find proper distances in all 11 locations.

I am confused in this situation and I thought there might be somthing I am missing.

Any ideas on what is happening here and how can I overcome the problem?

Thanks for your time.

**Comment by mjjbell** [comment]
Take a look at the debug output for the foot profile: http://map.project-osrm.org/debug/foot.html#12.69/37.2254/27.6251

![image](https://user-images.githubusercontent.com/1063186/178058799-6b9a6160-f758-48d4-8674-feb6ff73d94e.png)

The pink highlighted areas indicate an isolated section that is disconnected from the main network. That is, according to the way OSRM parses the OSM tags, it can't guarantee a route between the pink paths and the non-pink paths.

So therein lies the answer. The first 10 locations are in the pink area, the 11th is part of the main network.

When you're routing between just the first 10, it's able to find the routes within the isolated network.

When the 11th is included, OSRM tries to be helpful and move the 10 waypoints to somewhere which has a better chance of finding a route to the 11th point. But given the remoteness of the area, it ends up moving them a long way (in this case, the same place) and even then, it still may not be routable. 

The fix, is to understand why the underlying OSM data is not allowing walking between these areas. If you expect it should be possible, check for missing tags that allow pedestrian access.

**Comment by SiarheiFedartsou** [comment]
Stale.
