### ISSUE TITLE
Local OSRM Server - osrmRoute() in R - Error: InvalidQuery Query string malformed close to position 14

### ISSUE THREAD

**Issue by maren1ka** [Project-OSRM/osrm-backend#6280]
Hallo all,

I am new to GitHub and new to raising an issue. 
_Warning: I am also no coding or programming specialist, so it is very likely that I will not have the most sophisticated and efficient code, but it worked for me so far._ 
I hope I have not missed a similar issue, but the ones I found were not able to solve mine...

My set-up:
I am running an OSRM server on a remote ubuntu machine/computer from my Windows computer:
`
osrm-extract /home/mmarkali/europe-150101.osm.pbf -p /srv/osrm/osrm-backend/profiles/car.lua
osrm-partition /home/mmarkali/europe-150101.osrm
osrm-customize /home/mmarkali/europe-150101.osrm
osrm-routed --algorithm mld --max-table-size 100000 /home/mmarkali/europe-150101.osrm
`

The server is running on port 5000 and waiting for reqeusts.

So I turn to use the osrm package in R. In particular I use the osrmRoute() command. I loop through a file of cities and their longitude and latitude to obtain duration, distance and the linestring of the route:

`
library(osrm)
df <- read.csv("/home/mmarkali/top10_geocoded_coordinates.csv") 
route <- list()
k = 0
for (i in 1:nrow(df)) { 
  for (j in 1:nrow(df)) { 
    k=k+1
    route[[k]] <- osrmRoute(src = c(df$long[i], df$lat[i]),
                            dst = c(df$long[j], df$lat[j]),
                            returnclass = "sf", overview=FALSE,
                            osrm.server = "http://129.217.137.80:5000/",osrm.profile = "car")
  }
}
df.routes <- data.frame(t(sapply(route,c)))
k= 0
for (i in 1:nrow(df)) { 
  for (j in 1:nrow(df)) { 
    k=k+1
    df.routes$source[[k]] <- df$nuts2[i]
    df.routes$source_city[[k]] <- df$city_name[i]
    df.routes$destination[[k]] <- df$nuts2[j]
    df.routes$destination_city[[k]] <- df$city_name[j]
  }
}

write.csv(data, "/home/mmarkali/2014_duration_distance.csv")
`

The error I get is: **The OSRM server returned an error: Error: InvalidQuery Query string malformed close to position 14**

When I run the code locally on my computer on a subset of cities and a smaller osrm file it perfetly works... 
I suspect that something with the set-up of the server is odd but I cannot figure out what it is...

I also ran the command on the remote computer for only one pair of coordinates, which should give me the route between Groningen and Oldambt in the Netherlands, but I get the same error.
`
route <- osrmRoute(src = c(53.21907, 6.56800),
                            dst = c(53.22234 7.068982),
                            returnclass = "sf", overview=FALSE,
                            osrm.server = "http://129.217.137.80:5000/",osrm.profile = "car")
`

Any help and comments are highly appreciated.

Should you need more information: I am happy to share all I have and know..

Thank you and best wishes,
Maren

**Comment by danpat** [comment]
Debugging the R library is a bit out of scope for this repo - we didn't write it.  However, based on the error you're getting, it seems like the URL that your R library is building then sending to OSRM is invalid.  Can you get the R OSRM library to print out the exact URL it is sending to OSRM?  Can you see any logs in the OSRM terminal window that might show the invalid request?

**Comment by maren1ka** [comment]
@danpat fair point.
And looking at the actual url that it sends helped a lot (indirectly). 
I checked manually in the ubuntu terminal whether curling a osrm route works, and it did..
So, turned out that I used a different name for the dataset in a previous R skript and that provoked the isse.. 

Thank you very much!
