### ISSUE TITLE
Routing on aeroway runway & taxiways

### ISSUE THREAD

**Issue by kevinosullivan** [Project-OSRM/osrm-backend#6288]
I would like to use OSRM in an airport environment, to route aircraft around a runway & taxiways. I have looked at https://github.com/Project-OSRM/osrm-backend/issues/4814 and adopted the `car.profile` to `aircraft.profile`. Issue #4814 also talks about updating WayHandler to `to set a mode for your data and the speed from your table` - but I can't figure out what to do.

When I add some debug logging to `WayHandler.speed`, it only gets called once  - which implies it isn't being called on each individual runway/taxiway?

```
WayHandlers.speed: key: aeroway value: aerodrome speed: 100
```

The end result looks like this:

![image](https://user-images.githubusercontent.com/116788/180955253-f55c90d3-111d-44f8-aeb0-aa1afd3c9fe9.png)

Any guidance greatly appreciated...

**Comment by SiarheiFedartsou** [comment]
Stale.
