### ISSUE TITLE
Wrong highway tag in bicycle.profile

### ISSUE THREAD

**Issue by davidmurray** [Project-OSRM/osrm-backend#6289]
Hello,

In the bicycle OSRM profile, there is a check for the `bicycle` highway tag in the `safety_handler` function.

https://github.com/Project-OSRM/osrm-backend/blob/06b1b980bbdfc838c4f8e8cb370cba6dfb0329b0/profiles/bicycle.lua#L546-L560

However, unless I am mistaken, there is no `highway=bicycle` tag in OSM, but rather a `highway=cycleway` tag: https://wiki.openstreetmap.org/wiki/Key:highway

Therefore, shouldn't this code check for "cycleway" rather than "bicycle"?

Thanks!

**Comment by SiarheiFedartsou** [comment]
Related https://github.com/Project-OSRM/osrm-backend/pull/6296

**Comment by SiarheiFedartsou** [comment]
Closing as this code does not exist anymore.
