### ISSUE TITLE
Node OSRM memory usage increases over time?

### ISSUE THREAD

**Issue by ntzm** [Project-OSRM/osrm-backend#6291]
First of all, thanks for this amazing project!

I have noticed that node OSRM memory usage increases over time whereas OSRM-routed's doesn't. 

Here is an example script:

```
var OSRM = require('osrm');

var osrm = new OSRM({ path: "gb.osrm", algorithm: 'MLD', mmap_memory: false });

const func = () => new Promise((r) => {
  const query = {
    coordinates: [[-3.397522,58.589730], [-1.669922, 51.041394]],
  }

  osrm.route(query, function(err, result) {
    const used = process.memoryUsage.rss();
    console.log(Math.round(used / 1024 / 1024 * 100) / 100);

    r();
  });
})

const funcs = Array(100).fill(func)

funcs.reduce((prev, cur) => prev.then(cur), Promise.resolve());
```

As you can see, the RSS memory usage will increase over time, before it levels out. This seems different to how routed works where it stays at the same (lower) memory usage all the time. It feels like maybe the OSRM node bindings are caching parts of the responses?

Thanks.

**Comment by SiarheiFedartsou** [comment]
Stale.
