### ISSUE TITLE
loading raster data in profile.lua with Docker 

### ISSUE THREAD

**Issue by Nich-K** [Project-OSRM/osrm-backend#6301]
Hello.

I am working on an application where i use third party raster data [Integrating third party raster data](https://github.com/Project-OSRM/osrm-backend/wiki/Integrating-third-party-raster-data) in my profile.

I use Docker. The issue I have is when I use ` raster:load(os.getenv("E:/path/to/raster.asc"))` the file is not found.
_terminate called after throwing an instance of 'sol::error'
  what():  lua: error: Problem opening file:  (possible cause: "File not found") (at src/extractor/raster_source.cpp:112)_

I don't know how to reference that file. I have tried to put it in the docker volume where the _location-latest.osm.pbf_ and _profile.lua_ file is located, but I don't know how to reference it in there.
I have tried every possible filepath I could think of.

I am unsure if this is even the right place to ask this, since i believe this is more of a Docker related problem, but maybe someone can help me anyway.

Thanks in advance.

**Comment by nilsnolde** [comment]
what's your docker command/docker-compose.yml? generally, if container-internal software should find the files, you'll have to specify the container-internal path, not the host machine path. if you mapped a docker volume with e.g. `E:/path/to:/data`, inside the container the file is available at `/data/raster.asc`.

**Comment by Nich-K** [comment]
> what's your docker command/docker-compose.yml? generally, if container-internal software should find the files, you'll have to specify the container-internal path, not the host machine path. if you mapped a docker volume with e.g. `E:/path/to:/data`, inside the container the file is available at `/data/raster.asc`.

I am very new to Docker
How do I view the compose.yml?

I try this command:
`docker run -t -v e:/docker:/data osrm/osrm-backend osrm-extract -p /data/bicycle_pollution.lua /data/utrecht-latest.osm.pbf`

I have already tried `/data/raster.asc` that gives me the same error

**Comment by Nich-K** [comment]
I am an Idiot. I have been using os.getenv().
Without it, it works.
