### ISSUE TITLE
osrm-extract using excessive memory from a certain point in the master branch (5.27.0).

### ISSUE THREAD

**Issue by MovieJo** [Project-OSRM/osrm-backend#6307]
I am using small data from [south-korea](http://download.geofabrik.de/asia/south-korea.html) (as small as 160M).

This data was smoothly extracted even from devices with 8G memory.

From the master branch at some point, even on a machine with 32GB of memory, I had OOM kills when extracting.

And when I build it again with 5.26.0 version, it is extracted normally.

**Comment by handcath** [comment]
As flagged up in #6297 .
OS kills osrm-extract process as it runs out of memory.

**Comment by SiarheiFedartsou** [comment]
Should be fixed by https://github.com/Project-OSRM/osrm-backend/pull/6304/files
