### ISSUE TITLE
high load performance

### ISSUE THREAD

**Issue by csoxothuk** [Project-OSRM/osrm-backend#6308]
Greetings.
we are solving the problem of deploying a highly loaded OSRM instance.
At the moment, on a configuration of 64 cores(AMD EPYC 7502P 32-Core Processor), 1TB of RAM, we get a performance of 2 requests per second per core, when accessing /table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219 (example from the documentation)

Target expected result is 20000 requests per second.

The issue of scaling is not transparently described in the documentation.
 What principles and technologies can be applied in our case to achieve the planned indicators? How can we optimize the performance?

**Comment by TimMcCauley** [comment]
There are a bunch of issues related to this to look through which may help you a little, one is https://github.com/Project-OSRM/osrm-backend/issues/3898
