### ISSUE TITLE
missing turn instructions (when name doesn't change).

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#631]
turn instructions are currently skipped if the way name doesn't change. this makes sense when the street doesn't turn.

but i think instructions are needed when you need to do a turn. in this example, you don't get any turn instructions, even though you do two 90 degree turns, because the side streets have the same name as the main street:

http://osrm.at/3fz

![screen shot 2013-05-15 at 5 42 51 pm](https://f.cloud.github.com/assets/66034/507754/36b7eea6-bd76-11e2-9f8b-878759fac272.png)

**Comment by TheMarex** [comment]
Closing in favour of https://github.com/Project-OSRM/osrm-backend/issues/1251
