### ISSUE TITLE
osrm-extract using over 124G of vRam to extract ontario-latest.osm.pbf

### ISSUE THREAD

**Issue by WorkGeorge** [Project-OSRM/osrm-backend#6310]
#### Terminal Output
```
osrm-extract /home/admin/web/osrm2.valleyeats.ca/public_html/osmosis/ontario-latest.osm.pbf --threads 4
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script profiles/car.lua
[info] Input file: ontario-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 4
[info] Parsing in progress..
[info] input file generated by osmium/1.14.0
[info] timestamp: 2022-08-15T20:21:33Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
Killed
```
## Server Setup
- On a AWS arm64 cloud server running ubuntu 20.04.
- The server has 8GB of ram and a 124GB swapfile.
- The server is using the default HestiaCP setup
- OSRM is build from source and is on it's own web domain as apposed to the root directory

## Background
Currently my issue is that as osrm-extract runs it will slowly over the course of about 10-15 min use up the entire swapfile capacity and then it kills itself.  I've managed to do the same setup on another machine a month ago as a test run with no swapfile but now I'm having trouble getting OSRM to extract the osrm file from the osm file. I've tried; extracting different maps (from Geofabrik), same result. Having and not having a swap file. Rebuilding OSRM from the start. I ensured all the dependencies are installed an up to date. I've seen in the documentation a mention of a .stxxl config file but from what I can tell that is depreciated info or osrm doesn't use it by default anymore. If you need more info do ask, sorry if my formatting for the ticket sucks it's my first time writing a ticket.

**Comment by mjjbell** [comment]
A fix for what appears to be the same issue was applied to master yesterday 51a84863757aa6e0837237ca8f7b941b5ac33971

Can you confirm if this commit is included in your local build?

**Comment by WorkGeorge** [comment]
That did the trick thanks!!! I hadn't tried rebuilding since a week and a half ago when I put the project on the back burning. Guess I should have checked the patch notes first, sorry about that.
