### ISSUE TITLE
"exclude" flag not working in Node API

### ISSUE THREAD

**Issue by pankajrandhe** [Project-OSRM/osrm-backend#6316]
I am trying to use `exclude` flag to exclude classes like ferry, motorway, toll while calculating the shortest path using /table API. 

I created data using osrm-backend v5.25.0 and setup OSRM native API and OSRM Node APIs. Exclude flag is working in the native API but not in the Node API.

**Comment by SiarheiFedartsou** [comment]
Could you provide example of request when it doesn't work?

**Comment by pankajrandhe** [comment]
@SiarheiFedartsou 

Request body for one of the examples I tried for the `/table` endpoint is following.

`{
    "coordinates": 
    [
        [139.694457, 35.583716],
        [139.48790, 35.93879]
    ],
    "exclude": ["motorway"]
}`

**Comment by SiarheiFedartsou** [comment]
@pankajrandhe how do you understand that it works in native API, but not in Node? Do you have concrete example? I am looking into code and don't see any issues: we seem to handle `exclude` parameter for Node properly.
