### ISSUE TITLE
Relation:restriction is invalid

### ISSUE THREAD

**Issue by GitBenjamin** [Project-OSRM/osrm-backend#6322]
#Hello, Everyone!  I have a question.
@danpat @mjjbell  @daniel-j-h

Through OpenStreetMap wiki, I learned that I could use Relation:restriction to solve some turning problems.
[https://wiki.openstreetmap.org/wiki/Relation:restriction](url)
For example,
![image](https://user-images.githubusercontent.com/51102038/185918479-05f4d5b2-a4b7-4b8d-9147-dd0484680705.png)

```
<relation id="1" changeset="1" timestamp="2022-08-22T06:58:29Z" user="zhou" uid="4437318">
 <member type="way" ref="a" role="from"/>
 <member type="way" ref="b" role="via"/>
 <member type="way" ref="c" role="to"/>
 <tag k="restriction" v="no_right_turn"/>
 <tag k="type" v="restriction"/>
</relation>
```

but, the.OSM file that i compiled with this format does not solve the turning problem.

Is it because OSRM doesn't support it yet?

Historically, this “way-vias” (fromWayId, viaWayId, toWayId) has been tried to handle
> https://github.com/Project-OSRM/osrm-backend/issues/2681

**Comment by mjjbell** [comment]
Restrictions are supported by OSRM.

Can you share an OSM link to the junction in question, or a link to the OSM file you are using?

**Comment by GitBenjamin** [comment]
> Restrictions are supported by OSRM.
> 
> Can you share an OSM link to the junction in question, or a link to the OSM file you are using?

Have “way-vias” (fromWayId, viaWayId, toWayId) and “node-vias” (fromWayId, viaNodeId toWayId)  been supported?
Is it because CH supports it, but MLD still doesn't?

I'm using SHP files to convert to OSM files, so the output file is huge. I can upload part of the file, could you please help to analyze it? The content format of the files is basically the same.

**Comment by mjjbell** [comment]
> Have “way-vias” (fromWayId, viaWayId, toWayId) and “node-vias” (fromWayId, viaNodeId toWayId) been supported?

Yes, it supports both

>  Is it because CH supports it, but MLD still doesn't?

Processing of restrictions happens prior to algorithm specific processing. It is supported by both.

> I'm using SHP files to convert to OSM files, so the output file is huge. I can upload part of the file, could you please help to analyze it? The content format of the files is basically the same.

It will be hard to reproduce correctly if the whole file is not available. Given that you're converting from another data source, I suspect the problem is somewhere in the conversion logic.

**Comment by GitBenjamin** [comment]
Maybe I'm using an older version? It's Version 5.23.0

> [Unreleased](https://github.com/Project-OSRM/osrm-backend/issues/5858)

This is part of the OSM file.

**Comment by nilsnolde** [comment]
having done this kind of exercise quite often, I also suspect connectivity problems for the relation. you can check that _somewhat_ with osmium, e.g. [`osmium getid --add-referenced <osm_file> <turn_restriction_id>`](https://docs.osmcode.org/osmium/latest/osmium-getid.html) which should output the right ways, i.e. find the ways by id and their node id's & coordinates. visualizing in josm also helps a lot if you break it down to a small area (josm gets really slow for larger extracts than a few MB).

**Comment by GitBenjamin** [comment]
> 

Well, thank you very much for your suggestion. I'll try it out.

**Comment by GitBenjamin** [comment]
> Maybe I'm using an older version? It's Version 5.23.0
> 
> > [Unreleased](https://github.com/Project-OSRM/osrm-backend/issues/5858)
> 
> This is part of the OSM file. [test.osm](https://github.com/GitBenjamin/Some-test-file/blob/main/test.osm)

@mjjbell  I wonder if this file will give us any clues. 

> https://github.com/Project-OSRM/osrm-backend/pull/5907
Does the latest master branch already contain the change? If so, can I try it with the latest master?

**Comment by GitBenjamin** [comment]
> > @mjjbell I wonder if this file will give us any clues.
> 
> Yes, the relations refer to ways and nodes that don't exist in the file. You'll need to figure out why that's happening.

The original data in the file contains these nodes and ways, because some nodes and ways are deleted randomly. 
The point is, is there a problem with the format?
Thank you very much for your answer. **_I will make some attempts according to your answer._**

Please do not close the issue yet.

**Comment by nilsnolde** [comment]
> The original data in the file contains these nodes and ways, because some nodes and ways are deleted randomly.

Can you use “osmium extract” for the extraction? By default it will complete ways, ie pull in all nodes of all ways which appear spatially in the bbox you’re extracting with. We need the full topology extracted from your OSM file.

**Comment by GitBenjamin** [comment]
> Maybe I'm using an older version? It's Version 5.23.0
> 
> > [Unreleased](https://github.com/Project-OSRM/osrm-backend/issues/5858)
> 
> This is part of the OSM file. [test.osm](https://github.com/GitBenjamin/Some-test-file/blob/main/test.osm)

@mjjbell  _**I suspect the 5.23.0 branch does not support via-ways.**_ 

i made a try, i routed it using the branch  [5.23.0](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.23.0) and my test.osm data, and the result was wrong. But, when i routed with the branch [5.26.0](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.26.0) and the same test data, the results were correct.

**Comment by mjjbell** [comment]
I see. Single via-ways are supported in 5.23.0 and [multiple via-ways](https://github.com/Project-OSRM/osrm-backend/pull/5907) were added in [5.24.0](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.24.0), so I suspect that's the change that made the difference.

**Comment by GitBenjamin** [comment]
> 

the test data does not contain **multiple via-ways**.
