### ISSUE TITLE
5.27 Release?

### ISSUE THREAD

**Issue by mjjbell** [Project-OSRM/osrm-backend#6325]
Given the recent activity with a number of fixes/improvements hitting master, it might be worth making a new release.

Here are some additional changes that I think should also be included:

- [x] Finalising the CI/build changes & Mason to Conan switch
#6300
#6324
#6387 
- [x] Updating the development docs to reflect the above changes & general tidying
#6150
#6383
- [x] Publish Windows Node builds 
`node-pre-gyp` has Windows support.
#6334
- [x] Publish Apple Silicon builds
#6360 
- [x] Fixes for debug build assertions
#6215
#6218
#6373
- [x] Snapping improvements/fixes to via restrictions
#5953
#6339
- [x] Support directional traffic lights
#6153

Any other suggestions/thoughts?

**Comment by SiarheiFedartsou** [comment]
> Publish Windows Node builds?

It effectively means configuring build with ENABLE_NODE_BINDINGS=ON on Windows and packaging resulting module on releases?

**Comment by SiarheiFedartsou** [comment]
@mjjbell 
Btw do you have access to Docker Hub? I am not sure how our release process is configured, but would be great to push it there too(https://github.com/Project-OSRM/osrm-backend/issues/6231)

**Comment by mjjbell** [comment]
> It effectively means configuring build with ENABLE_NODE_BINDINGS=ON on Windows and packaging resulting module on releases?

Yes, hopefully we can just reuse the Node [package/publish step](
https://github.com/Project-OSRM/osrm-backend/blob/8e74b7af9d86d837385abe01ff8940ccc8e86a7f/.github/workflows/osrm-backend.yml#L644-L659)

> Btw do you have access to Docker Hub? I am not sure how our release process is configured, but would be great to push it there too(https://github.com/Project-OSRM/osrm-backend/issues/6231)

No, we can no longer publish to Docker Hub due to a change in the TOS (hence the missing version). We've switched to using Github Packages  container registry (#6138), so it will publish [here](https://github.com/orgs/Project-OSRM/packages?repo_name=osrm-backend) in the next release. That's something else that we will need to update in the docs.

**Comment by SiarheiFedartsou** [comment]
Btw I would also think about publishing Node module for Apple Silicon Macs.

**Comment by mjjbell** [comment]
It's not possible yet with Github hosted runners: https://github.com/actions/runner-images/issues/2187

**Comment by SiarheiFedartsou** [comment]
> It's not possible yet with Github hosted runners: [actions/runner-images#2187](https://github.com/actions/runner-images/issues/2187)

AFAIR we can cross-compile for M1 on old Macs. I'll try to experiment with at some day.

**Comment by SiarheiFedartsou** [comment]
> > It's not possible yet with Github hosted runners: [actions/runner-images#2187](https://github.com/actions/runner-images/issues/2187)
> 
> AFAIR we can cross-compile for M1 on old Macs. I'll try to experiment with it at some day.

Well, it is possible: https://github.com/Project-OSRM/osrm-backend/pull/6360

Just need to clean it up and figure out how to properly build release package.

**Comment by mjjbell** [comment]
Release candidate is out. Looks like all the new deployment infrastructure is working :tada: 

- [Release](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.27.0-rc.1)
- [Node package](https://www.npmjs.com/package/@project-osrm/osrm) 
- [Docker container](https://github.com/Project-OSRM/osrm-backend/pkgs/container/osrm-backend)
