### ISSUE TITLE
hints on deprecated docs / SEO

### ISSUE THREAD

**Issue by Laubeee** [Project-OSRM/osrm-backend#6328]
For some reason, googling "osrm table api docs" first results leads me to [v5.5.1](http://project-osrm.org/docs/v5.5.1/api)

a hint and/or an easy way to switch api versions would be much appreciated (took me quite some time until I realized I was looking at an old doc). For inspiration, visit [an old sunpy docs page](https://docs.sunpy.org/en/v3.0.0/)

**Comment by mjjbell** [comment]
Can you create this issue over in https://github.com/Project-OSRM/project-osrm.github.com/?
That's the repo for the docs.
