### ISSUE TITLE
Deprecate .osrm file

### ISSUE THREAD

**Issue by mjjbell** [Project-OSRM/osrm-backend#6329]
The `.osrm` file contains a node-based graph representation of the OSM data, prior to compression and edge-expansion.

It's generated by `osrm-extract` and only read by `osrm-extract`. I believe it's a hangover from when the data was too large for RAM, so was first serialised to disk. However the file contents are [immediately read back into memory](https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/src/extractor/node_based_graph_factory.cpp#L37) anyway.

Assuming the file had value beyond the extraction phase, there are inconsistencies in which metadata components are serialised.
[Traffic signals and barriers](https://github.com/Project-OSRM/osrm-backend/blob/a98074a051ddd6fb95aa7e7d392420b9af0c0281/src/extractor/extraction_containers.cpp#L896-L933) are serialised to disk as part of the graph, but other metadata, [such as turn lanes, restrictions and manoeuvrer overrides ](https://github.com/Project-OSRM/osrm-backend/blob/91895604c9e458d1c804189b348e86dfdb2cc31c/src/extractor/extractor.cpp#L629-L631)are not. They are only kept in memory long enough for subsequent extraction steps.

Therefore, I propose that we scrap the disk serialise/deserialise step and stop generating this file.

`.osrm` is one of, if not the largest file generated during processing. Given we generate many other specific files for use in later processing stages, we can stop persisting the `.osrm` file entirely to save storage space, and if needed serialise its contents to more targeted files.

**Comment by mjjbell** [comment]
The[ toolchain file overview ](https://github.com/Project-OSRM/osrm-backend/wiki/Toolchain-file-overview) refers to `.osrm` as a temporary file. However, there is a dependency on [the file](https://github.com/Project-OSRM/osrm-backend/blob/91895604c9e458d1c804189b348e86dfdb2cc31c/src/tools/components.cpp#L46) in `osrm-components`.

I'm not sure of the maintenance status of that tool, I've never used it myself. In any case, we could make serialising an optional setting on `osrm-extract` for debug purposes such as this.

**Comment by SiarheiFedartsou** [comment]
Is it about the same? https://github.com/Project-OSRM/osrm-backend/issues/2055

**Comment by mjjbell** [comment]
Yes it sounds similar.

I would suggest holding off until #6153 is applied, as it has related changes.
What is the proposed fix? To make serialising to disk optional?

**Comment by SiarheiFedartsou** [comment]
> What is the proposed fix? To make serialising to disk optional?

I think so.

**Comment by SiarheiFedartsou** [comment]
Started experimenting in https://github.com/Project-OSRM/osrm-backend/pull/6354

**Comment by dooley** [comment]
So how do i get the components.geojson now (5.27.1)?
 

- [ok] osrm-extract -p ~/routing/trunk/profile/standard/car.lua germany.osm.pbf 
- [ok] osrm-contract germany
- [fail] osrm-components germany components.geojson

osrm-components germany small.geojson
terminate called after throwing an instance of 'osrm::util::RuntimeError'
  what():  Problem opening file: germany :  (possible cause: "No such file or directory") (at include/storage/tar.hpp:38)
Aborted (core dumped)
