### ISSUE TITLE
Content Encoding Default Value

### ISSUE THREAD

**Issue by nitko12** [Project-OSRM/osrm-backend#6330]
Hi,

I've ran into an issue while querying osrm-routed with latest master build (using boost::beast) using Python Requests library.

It seems the `Content-Encoding: deflate` has a bug, strangely enough it also seems it is the default encoding of Python Requests library.

```
requests.get(osrm_url)
requests.get(osrm_url, headers={"Accept-Encoding":"deflate"})
```

cause an error, specifically
```
ContentDecodingError: ('Received response with content-encoding: deflate, but failed to decode it.', error('Error -3 while decompressing data: invalid block type'))
```

while
```
requests.get(osrm_url, headers={"Accept-Encoding":""})
requests.get(osrm_url, headers={"Accept-Encoding":"gzip"})
```
successfully respond with http 200.

Could it be that https://github.com/Project-OSRM/osrm-backend/blob/e7185b4bcb7eb17ea4f85dc3d087880dbd309646/src/server/connection.cpp#L224

is encoding it wrong?

**Comment by nitko12** [comment]
I've also tried manually decompressing the output here: https://www.multiutil.com/deflate-to-text-decompress/

and got a message stating:

```Note: System detected that the input text is not a deflate and it is a gzip compressed text. So, it has been decompressed using gzip algorithm. For further gzip decompressions, use [gzip decompresstion tool](https://www.multiutil.com/gzip-to-text-decompress/).```

Data I've got was from running a command

```
res = requests.get(osrm_url, stream=True).raw.read() # later converted to base64 string
```

Which should use deflate (from my results above) but seems to have returned a gzip.

**Comment by mjjbell** [comment]
The `Boost.beast` change has flipped the compression precedence, despite what the comment says

https://github.com/Project-OSRM/osrm-backend/blob/e7185b4bcb7eb17ea4f85dc3d087880dbd309646/src/server/connection.cpp#L28-L38

So the question is if the deflate encoding issue is new, or if it's never been noticed because it was always defaulting to gzip.

**Comment by mjjbell** [comment]
> strangely enough it also seems it is the default encoding of Python Requests library.

I suspect the default is to accept gzip, deflate and others. But the OSRM behaviour has changed to return the buggy deflate response in that scenario.

**Comment by mjjbell** [comment]
I can reproduce the deflate error even after reverting #6294, so it appears to be a long-standing issue.

For now I'll change the compression precedence back to the previous order, this should fix the common default case.

**Comment by mjjbell** [comment]
@nitko12 the regression has been fixed on `master`. 
Deflate encoding still does not work, but we'll look into that as a separate issue.

**Comment by nitko12** [comment]
Awesome, I'll close this issue :)
