### ISSUE TITLE
OSRM make failed because TBB

### ISSUE THREAD

**Issue by Chiller2019** [Project-OSRM/osrm-backend#6332]
Hello,

I have a question because my install failed everytime.

Prerequisite installed from OSRM.
oneTBB installed newst version from master-banche.
GCC: 9.4.0
OS: Ubuntu 20.04 LTS

Commands:
> mkdir -p build
> cd build
> cmake ..
> cmake --build .
> sudo cmake --build . --target install

Error-Log:

> [ 44%] Linking CXX executable osrm-extract
> libosrm_extract.a(extractor.cpp.o):extractor.cpp:function tbb::detail::d1::enumera                                                                                                           ble_thread_specific<std::unique_ptr<osrm::extractor::LuaScriptingContext, std::def                                                                                                           ault_delete<osrm::extractor::LuaScriptingContext> >, tbb::detail::d1::cache_aligne                                                                                                           d_allocator<std::unique_ptr<osrm::extractor::LuaScriptingContext, std::default_del                                                                                                           ete<osrm::extractor::LuaScriptingContext> > >, (tbb::detail::d1::ets_key_usage_typ                                                                                                           e)1>::free_array(void*, unsigned long): error: undefined reference to 'tbb::detail                                                                                                           ::r1::cache_aligned_deallocate(void*)'
> libosrm_extract.a(extractor.cpp.o):extractor.cpp:function tbb::detail::d1::enumera                                                                                                           ble_thread_specific<std::unique_ptr<osrm::extractor::LuaScriptingContext, std::def                                                                                                           ault_delete<osrm::extractor::LuaScriptingContext> >, tbb::detail::d1::cache_aligne                                                                                                           d_allocator<std::unique_ptr<osrm::extractor::LuaScriptingContext, std::default_del                                                                                                           ete<osrm::extractor::LuaScriptingContext> > >, (tbb::detail::d1::ets_key_usage_typ                                                                                                           e)1>::create_array(unsigned long): error: undefined reference to 'tbb::detail::r1:                                                                                                           :cache_aligned_allocate(unsigned long)'
> libosrm_extract.a(extractor.cpp.o):extractor.cpp:function tbb::detail::d1::segment                                                                                                           _table<tbb::detail::d0::padded<tbb::detail::d1::ets_element<std::unique_ptr<osrm::                                                                                                           extractor::LuaScriptingContext, std::default_delete<osrm::extractor::LuaScriptingC                                                                                                           ontext> > >, 128ul>, tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::pad                                                                                                           ded<tbb::detail::d1::ets_element<std::unique_ptr<osrm::extractor::LuaScriptingCont                                                                                                           ext, std::default_delete<osrm::extractor::LuaScriptingContext> > >, 128ul> >, tbb:                                                                                                           :detail::d1::concurrent_vector<tbb::detail::d0::padded<tbb::detail::d1::ets_elemen                                                                                                           t<std::unique_ptr<osrm::extractor::LuaScriptingContext, std::default_delete<osrm::                                                                                                           extractor::LuaScriptingContext> > >, 128ul>, tbb::detail::d1::cache_aligned_alloca                                                                                                           tor<tbb::detail::d0::padded<tbb::detail::d1::ets_element<std::unique_ptr<osrm::ext                                                                                                           ractor::LuaScriptingContext, std::default_delete<osrm::extractor::LuaScriptingCont                                                                                                           ext> > >, 128ul> > >, 3ul>::clear(): error: undefined reference to 'tbb::detail::r                                                                                                           1::cache_aligned_deallocate(void*)'
> libosrm_extract.a(extractor.cpp.o):extractor.cpp:function tbb::detail::d1::segment                                                                                                           _table<tbb::detail::d0::padded<tbb::detail::d1::ets_element<std::unique_ptr<osrm::                                                                                                           extractor::LuaScriptingContext, std::default_delete<osrm::extractor::LuaScriptingC                                                                                                           ontext> > >, 128ul>, tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::pad                                                                                                           ded<tbb::detail::d1::ets_element<std::unique_ptr<osrm::extractor::LuaScriptingCont                                                                                                           ext, std::default_delete<osrm::extractor::LuaScriptingContext> > >, 128ul> >, tbb:                                                                                                           :detail::d1::concurrent_vector<tbb::detail::d0::padded<tbb::detail::d1::ets_elemen                                                                                                           t<std::unique_ptr<osrm::extractor::LuaScriptingContext, std::default_delete<osrm::                                                                                                           extractor::LuaScriptingContext> > >, 128ul>, tbb::detail::d1::cache_aligned_alloca                                                                                                           tor<tbb::detail::d0::padded<tbb::detail::d1::ets_element<std::unique_ptr<osrm::ext                                                                                                           ractor::LuaScriptingContext, std::default_delete<osrm::extractor::LuaScriptingCont                                                                                                           ext> > >, 128ul> > >, 3ul>::clear(): error: undefined reference to 'tbb::detail::r                                                                                                           1::cache_aligned_deallocate(void*)'
> [...]
> make[2]: *** [CMakeFiles/osrm-extract.dir/build.make:106: osrm-extract] Error 1
> make[1]: *** [CMakeFiles/Makefile2:211: CMakeFiles/osrm-extract.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2

Any ideas?

Kind regards

**Comment by SiarheiFedartsou** [comment]
Which version of OSRM are you using?

**Comment by Chiller2019** [comment]
> Which version of OSRM are you using?

Build from Master-Branche

**Comment by SiarheiFedartsou** [comment]
> TBB installed newst version from master-banche.

What exactly version it is? This one from master? https://github.com/oneapi-src/oneTBB

**Comment by SiarheiFedartsou** [comment]
> > TBB installed newst version from master-banche.
> 
> What exactly version it is? This one from master? https://github.com/oneapi-src/oneTBB

I just want to note that now we use oneTBB, which is not the same as TBB we used before.

**Comment by Chiller2019** [comment]
> > TBB installed newst version from master-banche.
> 
> What exactly version it is? This one from master? https://github.com/oneapi-src/oneTBB

Yes, excatly this Github-Repo

**Comment by SiarheiFedartsou** [comment]
Hm, an how did you install it? We use 2021.3.0 tag btw.

**Comment by Chiller2019** [comment]
> Hm, an how did you install it? We use 2021.3.0 tag btw.

Installed from source - Single-configuration generators

```
# Do our experiments in /tmp
cd /tmp
# Clone oneTBB repository
git clone https://github.com/oneapi-src/oneTBB.git
cd oneTBB
# Create binary directory for out-of-source build
mkdir build && cd build
# Configure: customize CMAKE_INSTALL_PREFIX and disable TBB_TEST to avoid tests build
cmake -DCMAKE_INSTALL_PREFIX=/tmp/my_installed_onetbb -DTBB_TEST=OFF ..
# Build
cmake --build .
# Install
cmake --install .
# Well done! Your installed oneTBB is in /tmp/my_installed_onetbb
```

**Comment by Chiller2019** [comment]
Idk, like it wasn't installed at 2% the installed was canceled with an error that tbb is missing, one directory with an loop.py (or what else).

**Comment by SiarheiFedartsou** [comment]
> Installed from source - Single-configuration generators

Could you try v2021.3.0 tag? I mean `git clone --branch v2021.3.0 --single-branch https://github.com/oneapi-src/oneTBB.git`. Let me know if it will work, if not I will try to look what is wrong.

**Comment by Chiller2019** [comment]
> > Installed from source - Single-configuration generators
> 
> Could you try v2021.3.0 tag? I mean `git clone --branch v2021.3.0 --single-branch https://github.com/oneapi-src/oneTBB.git`. Let me know if it will work, if not I will try to look what is wrong.

Ok, thx, I will try and comment.

**Comment by Chiller2019** [comment]
Building works with many warnings but now its 56%.

I will post the Makeing-Log later
