### ISSUE TITLE
Targets Ubuntu 16.04 : not true anymore

### ISSUE THREAD

**Issue by nicolaschaufette** [Project-OSRM/osrm-backend#6336]
Hello,

While compiling a recent version, I noticed a dependency with recent versions of libtbb.
Ubuntu up to 20.04 does not contain file tbb/parallel_pipeline.h : https://packages.ubuntu.com/impish/amd64/libtbb-dev/filelist
Compilation went fine on Ubuntu 22.04

Just so you know to have a up-to-date documentation :) 

Regards

PS : I just noticed, linked to https://github.com/Project-OSRM/osrm-backend/issues/6332

**Comment by mjjbell** [comment]
Thanks, it's on our radar. The docs will be update shortly.

**Comment by Chiller2019** [comment]
When you build oneTBB, there is in the installation oneTBB/include/parallel_pipeline.h.
https://github.com/oneapi-src/oneTBB - Building from Master-Branche
