### ISSUE TITLE
osrm-customize, cant start because libtbb.so.12 not found but exist

### ISSUE THREAD

**Issue by Chiller2019** [Project-OSRM/osrm-backend#6337]
Hey,

I have a new problem after my problem was solved with my oneTBB-Version (see here: https://github.com/Project-OSRM/osrm-backend/issues/6332)

oneTBB v2021.3.0
GCC: 9.4.0
OS: Ubuntu 20.04 LTS
OSRM: Master-Branche pull
libtbb2: installed with apt and the file is in `/usr/local/lib/libtbb.so.12` but this is a link to  `/usr/local/lib/libtbb.so.12.3`

I imported allthing but in the last step, "osrm-customize" I have a file error because this file doesn't exists.

Error:
```
>osrm-customize alarm.osrm
osrm-customize: error while loading shared libraries: libtbb.so.12: cannot open shared object file: No such file or directory
```

Any ideas?

**Comment by SiarheiFedartsou** [comment]
Try to /usr/local/lib to ldconfig like here https://github.com/Project-OSRM/osrm-backend/blob/bb18a2b4288f6230f854000fa5188b1a86a49942/docker/Dockerfile#L57

**Comment by Chiller2019** [comment]
> Try to add /usr/local/lib to ldconfig like here
> 
> https://github.com/Project-OSRM/osrm-backend/blob/bb18a2b4288f6230f854000fa5188b1a86a49942/docker/Dockerfile#L57

Hey,
problem is, its not a Docker-File, its standalone.
