### ISSUE TITLE
Triangular inequlity not respected while it seems it should

### ISSUE THREAD

**Issue by legraina** [Project-OSRM/osrm-backend#6348]
Hi,

When trying this table request (https://router.project-osrm.org/table/v1/driving/-74.00799561,40.72329712;-74.00470734,40.72145462;-74.00417328,40.73820114?annotations=distance,duration), I get these results:
- 0->1 => 46.6s and 374.1m
- 0->2 => 354.1s and 2786.1m
- 1->2 => 266s and 2151km

You can visualize the paths with those requests:
- 0->1 => https://map.project-osrm.org/?z=15&center=40.724250%2C-73.999400&loc=40.72329712%2C-74.00799561&loc=40.72145462%2C-74.00417328&hl=en&alt=0&srv=0
- 0->2 => https://map.project-osrm.org/?z=15&center=40.724250%2C-73.999400&loc=40.72329712%2C-74.00799561&loc=40.73820114%2C-74.00417328&hl=en&alt=0&srv=0
- 1->2 => https://map.project-osrm.org/?z=15&center=40.724250%2C-73.999400&loc=40.72145462%2C-74.00417328&loc=40.73820114%2C-74.00417328&hl=en&alt=0&srv=0

When you look at the map, there is no reason why you cannot take the path 0->1->2. Why is this path not proposed as a solution for 0->2 as it's faster and shorter ?

**Comment by SiarheiFedartsou** [comment]
Most likely duplicate/related https://github.com/Project-OSRM/osrm-backend/issues/6195

**Comment by mjjbell** [comment]
The `1` in your viz links does not match the `1` used in the `/table` request.

This is [0->1](https://map.project-osrm.org/?z=18&center=40.722435%2C-74.006220&loc=40.72329712%2C-74.00799561&loc=40.72145462%2C-74.00470734&hl=en&alt=0&srv=0)
![image](https://user-images.githubusercontent.com/1063186/187412054-b0b65763-73d9-4f9b-8ced-fcb304d56c5d.png)

[1->2](https://map.project-osrm.org/?z=15&center=40.730999%2C-74.008455&loc=40.721455%2C-74.004707&loc=40.738201%2C-74.004173&hl=en&alt=0&srv=0)
![image](https://user-images.githubusercontent.com/1063186/187412414-39892651-8c80-48f0-a28c-e5d157b6ffce.png)


So this is the same as #6195
The triangle inequality would only apply if you entered/exited `1` in the same direction.

**Comment by legraina** [comment]
Sorry, I didn't see the error in the link ! Thanks a lot for the quick answer.
