### ISSUE TITLE
Compilation error with CentOs 6.4 : bz2 library not found

### ISSUE THREAD

**Issue by AlexDas** [Project-OSRM/osrm-backend#635]
Hi,

I'm trying to install osrm on a server but when i compile i get this error : 

scons: Reading SConscript files ...
Using default C++ Compiler:  g++
Default platform
Checking for C++ library pthread... yes
Checking for C++ library luajit-5.1... yes
Checking for C header file omp.h... yes
Checking for C++ library bz2... no
bz2 library not found. Exiting

I checked if bz2 was already installed and it is. 
Can somebody help me ?
Thanks.

**Comment by olearytd** [comment]
AlexDas, this is an old issue but do you happen to remember what you did to get osrm to see your luabind build?
