### ISSUE TITLE
Foot route result not same (routing.openstreetmap.de vs router.project-osrm.org vs my local osrm)

### ISSUE THREAD

**Issue by dwibudut** [Project-OSRM/osrm-backend#6352]
Can anyone explain why the routing results are different (on field `duration` and `distance`) ?

Between:

1) https://router.project-osrm.org/route/v1/foot/106.634618,-6.192302;106.633547,-6.192157?overview=false&alternatives=false&steps=false

2) https://routing.openstreetmap.de/routed-foot/route/v1/driving/106.634618,-6.192302;106.633547,-6.192157?overview=false&alternatives=false&steps=false

3) http://127.0.0.1:5000/route/v1/foot/106.634618,-6.192302;106.633547,-6.192157?overview=false&alternatives=false&steps=false

The direction is from LonLat : **106.634618,-6.192302** to **106.633547,-6.192157**
 
cc: @DennisOSRM  @SiarheiFedartsou
 
Thx

**Comment by jcoupey** [comment]
Not getting the same result between the demo server and your local instance is not a surprise since you may be using (by rough impact order): different OSRM profiles, different OSM extracts and different versions of OSRM.

The profiles used for the demo server can be found at https://github.com/fossgis-routing-server/cbf-routing-profiles.

On your first URL, you need to be aware that the `foot` part has no impact on the selected profile: you'll get the same response using any other keyword, e.g. https://router.project-osrm.org/route/v1/foo/106.634618,-6.192302;106.633547,-6.192157?overview=false&alternatives=false&steps=false.

**Comment by dwibudut** [comment]
Hi @jcoupey can you guide me to run local osrm-routed to get the same response like point (2) with foot/walking option?

2. https://routing.openstreetmap.de/routed-foot/route/v1/driving/106.634618,-6.192302;106.633547,-6.192157?overview=false&alternatives=false&steps=false


I've tried in two versions of osrm-backend (build from git master & latest osrm-backend official docker)

##### My current step:

```
wget http://download.geofabrik.de/asia/indonesia.html
```
###### Latest osrm-backend official docker
```
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/foot.lua /data/indonesia-latest.osm.pbf
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-contract /data/indonesia-latest.osrm
docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed /data/indonesia-latest.osrm
```

###### Build from git master
```
IMAGE_NAME="xxxx/osrm-backend" DOCKER_TAG="latest" ./docker/hooks/build

docker run -t -v "${PWD}:/data" xxxx/osrm-backend osrm-extract -p /opt/foot.lua /data/indonesia-latest.osm.pbf
docker run -t -v "${PWD}:/data" xxxx/osrm-backend osrm-contract /data/indonesia-latest.osrm
docker run -t -i -p 5000:5000 -v "${PWD}:/data" xxxx/osrm-backend osrm-routed /data/indonesia-latest.osrm
```

Test
```
curl -v "http://127.0.0.1:5000/route/v1/foot/106.634618,-6.192302;106.633547,-6.192157?overview=false&alternatives=false&steps=false"
```

~Thx

**Comment by jcoupey** [comment]
I you want to use the profile from the demo server, you need to point to that specific file when calling `osrm-extract`:

```
osrm/osrm-backend osrm-extract -p /opt/foot.lua [...]
```

Replace `/opt/foot.lua` with the profile you want.

**Comment by dwibudut** [comment]
I've done the steps in your previous comment, and I've also explained my last comment

**Comment by dwibudut** [comment]
The problem is solved.

The difference is in the extraction profile `foot.lua` in `properties.weight_name`. The value `properties.weight_name` on osrm-backend docker image is `duration` and demo is `routability`

<br/>
~Thx
