### ISSUE TITLE
OSMID from match service

### ISSUE THREAD

**Issue by Yozpoz64** [Project-OSRM/osrm-backend#6356]
I am trying to obtain the OSMID of matched ways from the match service. I was originally following [this suggestion](https://github.com/Project-OSRM/osrm-backend/issues/5473) but `annotations=true` does not seem to affect the output of the match service. Does anyone know how to fix this, or know a better way of obtaining the OSMID from the match service output?

**Comment by jcoupey** [comment]
The response in the thread you link to actually mentions using `annotations=nodes`, did you try that?

**Comment by Yozpoz64** [comment]
> 

Yes, and the response is the same - no different from when the tag is not there. Although as far as I can see the `nodes` value is depreceated (I could only find it referenced in older versions of the documentation) anyway.

**Comment by jcoupey** [comment]
This is not what I'm seeing, e.g. from the demo server:

```
$ curl "https://routing.openstreetmap.de/routed-bike/route/v1/driving/8.68384,50.11303;8.6840,50.11244" | jq .routes[].legs[]
{
  "steps": [],
  "summary": "",
  "weight": 41.9,
  "duration": 41.9,
  "distance": 81.7
}
$ curl "https://routing.openstreetmap.de/routed-bike/route/v1/driving/8.68384,50.11303;8.6840,50.11244?annotations=nodes" | jq .routes[].legs[]
{
  "steps": [],
  "summary": "",
  "weight": 41.9,
  "duration": 41.9,
  "annotation": {
    "nodes": [
      4486716474,
      2380676641,
      34223602,
      628923207
    ]
  },
  "distance": 81.7
}
```

Using `annotations=true` returns that same nodes array plus some other stuff.

The same applies to `match` requests, under `.matchings[].legs[]`.
