### ISSUE TITLE
Compiling on M1 mac - Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by stlazzarimeli** [Project-OSRM/osrm-backend#6357]
### What?
Have someone manage to build the project on M1 mac?
I am facing this problem:

`[build] Undefined symbols for architecture arm64:

I have already ran the brew command to install all the dependencies. I`m also running MASON = ON.

If I run MASON = OFF I get the Not Finding TBB error message.

Could someone give me a hand, please? Thanks a lot

**Comment by SiarheiFedartsou** [comment]
Which version are you trying to compile? Mason does not support M1 builds, that's why we migrated to Conan(you can use `-DENABLE_CONAN=ON` to try it).

**Comment by BeyondWang** [comment]
> Which version are you trying to compile? Mason does not support M1 builds, that's why we migrated to Conan(you can use `-DENABLE_CONAN=ON` to try it).

Hi,

Got the following error building by Conan on MAC m1 chip machine, any idea? Thanks in advance.
Conan version 1.52.0
compiler=apple-clang;-s;compiler.version=13.1

> /bin/sh ../libtool --mode=link gcc  -O3 -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -arch arm64 iconv_no_i18n.o ../srclib/libicrt.a ../lib/libiconv.la  -o iconv_no_i18n
libtool: link: gcc -O3 -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -arch arm64 iconv_no_i18n.o -o iconv_no_i18n  ../srclib/libicrt.a ../lib/.libs/libiconv.a
ld: warning: ignoring file ../srclib/libicrt.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file ../lib/.libs/libiconv.a, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture arm64:
  "__libiconv_version", referenced from:
      _print_version in iconv_no_i18n.o
  "_iconv_canonicalize", referenced from:
      _main in iconv_no_i18n.o
  "_libiconv", referenced from:
      _subst_mb_to_uc_fallback in iconv_no_i18n.o
      _subst_uc_to_mb_fallback in iconv_no_i18n.o
      _subst_mb_to_wc_fallback in iconv_no_i18n.o
      _subst_wc_to_mb_fallback in iconv_no_i18n.o
      _convert in iconv_no_i18n.o
  "_libiconv_close", referenced from:
      _main in iconv_no_i18n.o
  "_libiconv_open", referenced from:
      _main in iconv_no_i18n.o
  "_libiconvctl", referenced from:
      _main in iconv_no_i18n.o
      _convert in iconv_no_i18n.o
  "_libiconvlist", referenced from:
      _main in iconv_no_i18n.o
  "_program_name", referenced from:
      _main in iconv_no_i18n.o
      _usage in iconv_no_i18n.o
      _error in iconv_no_i18n.o
  "_rpl_free", referenced from:
      _convert in iconv_no_i18n.o
  "_rpl_strerror", referenced from:
      _error in iconv_no_i18n.o
  "_safe_read", referenced from:
      _convert in iconv_no_i18n.o
  "_set_program_name", referenced from:
      _main in iconv_no_i18n.o
  "_uc_width", referenced from:
      _update_line_column in iconv_no_i18n.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [iconv_no_i18n] Error 1
make: *** [all] Error 2
libiconv/1.17: 
libiconv/1.17: ERROR: Package '7ec727264c42101960946864b79a21302d2b5668' build failed
libiconv/1.17: WARN: Build folder /Users/AAA/.conan/data/libiconv/1.17/_/_/build/7ec727264c42101960946864b79a21302d2b5668
ERROR: libiconv/1.17: Error in build() method, line 141
	autotools.make()
	ConanException: Error 2 while executing make -j8
CMake Error at cmake/conan.cmake:540 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:882 (old_conan_cmake_install)
  CMakeLists.txt:498 (conan_cmake_run)
