### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by albertoarmida** [Project-OSRM/osrm-backend#6358]
Reading last release appveyor-build.bat is missing.
Using an old appveyor-build.bat file, compilation hangs with errore message "Invoke-WebRequest : Impossibile risolvere il nome remoto.: 'project-osrm.wolt.com'" (the site is unreachable).

**Comment by SiarheiFedartsou** [comment]
project-osrm.wolt.com went offline(at least judging by https://github.com/Project-OSRM/osrm-backend/pull/6314). Use Conan to download dependencies on Windows `cmake -DENABLE_CONAN=ON ..`. 
You can use our CI script as an example: https://github.com/Project-OSRM/osrm-backend/blob/master/scripts/ci/windows-build.bat
