### ISSUE TITLE
Match service: how big the querry allowed to be? No response from the server

### ISSUE THREAD

**Issue by Andreas4242** [Project-OSRM/osrm-backend#6362]
Hi 

since updating to the current build (yesterday) by compiling it from Master branch, the same match query that worked before does not work anymore.

It has around 250 points to match with a radius of 10 each.
If i do several requests to a match service with around 200 points in each request in couple of seconds, there is just no response from the server.

Server is Intel Xenon E5 with 65 Gig of ram.

Here are my start parameters.

I cranked everything to the max ... just to be sure for this test.

`/usr/local/bin/osrm-routed --max-matching-size 1000 --max-viaroute-size 1000 --max-trip-size 1000 --max-table-size 1000 --max-nearest-size 1000 --algorithm=MLD --verbosity=INFO /srv/osrm/osrm-backend/germany-latest.osrm`

Is there a parameter I should adjust before handling this kind of request?

Please advice.
Thank you

**Comment by SiarheiFedartsou** [comment]
Could you share problematic request you are doing?

**Comment by andreas-ullrich** [comment]
The request is working in itself. 
The problem occurs if repeat that request several times in a short (seconds) period.

`http://myip:5000/match/v1/car/11.8296776,48.1080396999118;11.830006,48.1064633999122;11.8310606,48.1033010999129;11.8309893,48.1025808999131;11.8307815,48.1019317999133;11.8276887,48.0991409999139;11.8225219,48.0955067999148;11.8221303,48.0950693999149;11.8220986,48.094894899915;11.8213408,48.0940559999152;11.8207394,48.0931841999154;11.8186077,48.0891718999163;11.815527,48.0829185999179;11.8116318,48.0805670999184;11.8108052,48.0804971999184;11.8097247,48.0802723999185;11.8086941,48.0797268999186;11.8083032,48.0793967999187;11.8068801,48.077924299919;11.7914452,48.0712664999207;11.7893641,48.0705644999208;11.7865111,48.069734599921;11.7854853,48.0691632999211;11.7853476,48.0689187999212;11.77753,48.0608113999232;11.7759781,48.0603428999233;11.7756273,48.0601683999233;11.7735348,48.0600171999233;11.7719872,48.0600973999233;11.7724047,48.0590350999236;11.7726359,48.0582355999238;11.7721788,48.0569835999241;11.7710089,48.0561043999243;11.7645908,48.0502266999257;11.7638185,48.0492424999259;11.7644439,48.048770099926;11.7820285,48.0374748999287;11.7863894,48.0349348999293;11.8051003,48.0246557999318;11.8063574,48.0241109999319;11.8073801,48.023799099932;11.8105246,48.0231832999321;11.8116327,48.0228563999322;11.8127718,48.0222666999324;11.8130896,48.0216826999325;11.813831,48.0215788999325;11.8156686,48.0208095999327;11.8168685,48.0208924999327;11.817273,48.0207560999327;11.8194334,48.0192203999331;11.8441133,48.006932999936;11.8442724,48.0066186999361;11.8444916,48.0047203999366;11.8458207,48.002759499937;11.8500193,48.0001927999376;11.8504406,47.9997722999377;11.8511479,47.998807599938;11.8546707,47.9960305999386;11.8557809,47.994583699939;11.8586452,47.9931552999393;11.8615969,47.9922383999395;11.863926,47.9907654999399;11.8640566,47.99040139994;11.8641436,47.9885682999404;11.8650669,47.9879794999406;11.8658684,47.9876865999406;11.8661496,47.9874675999407;11.8666673,47.9872547999407;11.8680721,47.9869123999408;11.8691798,47.9866988999409;11.8697707,47.9866785999409;11.8711705,47.9867896999408;11.8729816,47.9866316999409;11.8754628,47.9857178999411;11.8786432,47.9850751999412;11.8838397,47.9853928999412;11.8845058,47.9856562999411;11.8862758,47.986131399941;11.8883442,47.9865055999409;11.8908963,47.9868132999408;11.8983834,47.9870224999408;11.9022036,47.985963299941;11.903002,47.9856182999411;11.9049978,47.9845564999414;11.9068958,47.9836949999416;11.912095,47.9824055999419;11.9125427,47.9824097999419;11.920511,47.986328799941;11.9404407,47.981907499942;11.9427838,47.9812728999422;11.952517,47.9796286999426;11.9528408,47.9796858999425;11.9531081,47.9800648999424;11.9713544,47.9916422999397;11.9716384,47.9922634999395;11.9720959,47.9938651999392;11.9723031,47.9953047999388;11.972764,47.9972739999383;11.9726164,47.9977122999382;11.9759593,47.9970481999384;11.9812758,47.994361599939;11.9819657,47.9942562999391;11.987168,47.994489499939;11.9881654,47.9942027999391;11.9913848,47.9941492999391;11.9927751,47.9933803999393;11.9956989,47.9924777999395;11.9989988,47.9918010999397;12.0013379,47.9915782999397;12.0048339,47.9920824999396;12.0053071,47.9921016999396;12.0041866,47.99039499994;12.0038026,47.9888180999404;12.0023603,47.9850983999412;12.0028561,47.9829618999417;12.0042412,47.977749499943;12.0070389,47.973669999944;12.0175405,47.9569577999479;12.0173485,47.956746999948;12.0177431,47.9564224999481;12.0182446,47.9558738999482;12.0186961,47.9549279999484;12.0207051,47.9518233999492;12.0233973,47.9520518999491;12.0246124,47.9518099999492;12.0264582,47.9517267999492;12.0285272,47.9507200999494;12.0346623,47.9509510999494;12.0355514,47.9500551999496;12.0356122,47.9464916999504;12.0365025,47.9459755999505;12.041854,47.9424318999514;12.0441204,47.9436108999511;12.0447124,47.9436214999511;12.0457962,47.9424045999514;12.0528074,47.9384820999523;12.0553118,47.9363712999528;12.0585959,47.9331383999536;12.0636358,47.9252584999555;12.0694524,47.9232696999559;12.0705708,47.9226669999561;12.0706521,47.9225118999561;12.0706755,47.9219413999562;12.0709759,47.9201582999567;12.0714828,47.9198194999567;12.0727848,47.9180216999572;12.0720474,47.9168336999574;12.0738941,47.9126157999584;12.074212,47.9122224999585;12.089588,47.9081481999595;12.0907143,47.9073322999597;12.091243,47.90616369996;12.0919413,47.9031958999607;12.0930099,47.9000980999614;12.0931623,47.8999285999614;12.1019344,47.8948909999626;12.1023309,47.8948124999626;12.1033743,47.8944287999627;12.1036785,47.893126099963;12.1036294,47.8921256999633;12.1046505,47.8907209999636;12.1061473,47.8898438999638;12.108732,47.8887064999641;12.1098823,47.8880412999642;12.1156849,47.8841177999652;12.1162123,47.8836724999653;12.1161944,47.8830700999654;12.115436,47.8825827999655;12.1144046,47.8811377999659;12.113475,47.8796760999662;12.1128802,47.8789761999664;12.1125978,47.8778688999666;12.1115126,47.8758436999671;12.111171,47.8754097999672;12.1110662,47.8751741999673;12.1106624,47.8734336999677;12.1106055,47.8699673999685;12.1102821,47.8672624999691;12.1096762,47.8645207999698;12.1096637,47.8640861999699;12.1111049,47.8619648999704;12.1112486,47.8615852999705;12.111346,47.8583199999712;12.1111664,47.8567422999716;12.1104175,47.8553494999719;12.1102904,47.854916699972;12.1103017,47.8545775999721;12.1098138,47.8539694999723;12.1087478,47.8533832999724;12.1079781,47.8528259999725;12.1076134,47.8526369999726;12.108949,47.8520602999727;12.1124166,47.8503315999731;12.1148702,47.8495231999733;12.1170737,47.8492497999734;12.1182556,47.8488590999735;12.1190171,47.8484913999735;12.1196335,47.8480263999737;12.1234874,47.8474691999738;12.1255054,47.8470982999739;12.1256494,47.846859099974;12.1249065,47.8459387999742;12.1242647,47.8445835999745;12.1237741,47.8432713999748;12.1227758,47.8420045999751;12.1223512,47.8413574999752;12.121968,47.8399841999756;12.1230325,47.8399890999756;12.1245103,47.8405573999754;12.1262847,47.8413901999752;12.1357162,47.8441864999746;12.14112,47.8434667999747;12.1533619,47.846470599974;12.1574194,47.846677999974;12.1604029,47.8451597999743;12.1622102,47.8435226999747;12.1640702,47.842388799975;12.1642099,47.8418793999751;12.1642427,47.8410417999753;12.1646828,47.8406330999754;12.1663582,47.8402177999755;12.1682074,47.8393672999757;12.1702961,47.838130499976;12.1717722,47.8373904999762;12.1758212,47.833760099977;12.1791655,47.8350075999767;12.1899885,47.8366097999763;12.1998035,47.8375697999761;12.201084,47.837896099976;12.206019,47.8383597999759;12.2074004,47.8384580999759;12.2077385,47.8384152999759;12.2075459,47.8386847999759?radiuses=3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3&steps=true&geometries=geojson&overview=full&annotations=true`

**Comment by andreas-ullrich** [comment]
One additional question: it seems the **nearest** endpoint accepts only one point / request. Is it possible to batch several points in a list similar to the **match** endpoint?

**Comment by SiarheiFedartsou** [comment]
> One additional question: it seems the **nearest** endpoint accepts only one point / request. Is it possible to batch several points in a list similar to the **match** endpoint?

Yes, only one point is accepted. https://github.com/Project-OSRM/osrm-backend/blob/96f5780f06e6f55013762c879c361d647036bd72/src/engine/plugins/nearest.cpp#L44

BUT at glance it looks as a not a big deal to hack this endpoint for your own purposes. I guess currently we only support single input coordinate just to not introduce breaking changes in response format.

**Comment by SiarheiFedartsou** [comment]
> If i do several requests to a match service with around 200 points in each request in couple of seconds, there is just no response from the server.

What do you mean by "no response from the server", server does not respond after reasonable time? Or what?

**Comment by SiarheiFedartsou** [comment]
Well, on current master:
```
mkdir build
cd build
cmake -DENABLE_CONAN=ON .. && make -j8 
wget http://download.geofabrik.de/europe/germany-latest.osm.pbf
./osrm-extract --profile ../profiles/car.lua germany-latest.osm.pbf
./osrm-partition ./germany-latest
./osrm-customize ./germany-latest
./osrm-routed --algorithm mld --max-matching-size 1000 ./germany-latest.osrm
```
and then
```
for i in {1..1000}
do
    echo "Sending request #${i}"
    curl "http://127.0.0.1:5000/match/v1/car/11.8296776,48.1080396999118;11.830006,48.1064633999122;11.8310606,48.1033010999129;11.8309893,48.1025808999131;11.8307815,48.1019317999133;11.8276887,48.0991409999139;11.8225219,48.0955067999148;11.8221303,48.0950693999149;11.8220986,48.094894899915;11.8213408,48.0940559999152;11.8207394,48.0931841999154;11.8186077,48.0891718999163;11.815527,48.0829185999179;11.8116318,48.0805670999184;11.8108052,48.0804971999184;11.8097247,48.0802723999185;11.8086941,48.0797268999186;11.8083032,48.0793967999187;11.8068801,48.077924299919;11.7914452,48.0712664999207;11.7893641,48.0705644999208;11.7865111,48.069734599921;11.7854853,48.0691632999211;11.7853476,48.0689187999212;11.77753,48.0608113999232;11.7759781,48.0603428999233;11.7756273,48.0601683999233;11.7735348,48.0600171999233;11.7719872,48.0600973999233;11.7724047,48.0590350999236;11.7726359,48.0582355999238;11.7721788,48.0569835999241;11.7710089,48.0561043999243;11.7645908,48.0502266999257;11.7638185,48.0492424999259;11.7644439,48.048770099926;11.7820285,48.0374748999287;11.7863894,48.0349348999293;11.8051003,48.0246557999318;11.8063574,48.0241109999319;11.8073801,48.023799099932;11.8105246,48.0231832999321;11.8116327,48.0228563999322;11.8127718,48.0222666999324;11.8130896,48.0216826999325;11.813831,48.0215788999325;11.8156686,48.0208095999327;11.8168685,48.0208924999327;11.817273,48.0207560999327;11.8194334,48.0192203999331;11.8441133,48.006932999936;11.8442724,48.0066186999361;11.8444916,48.0047203999366;11.8458207,48.002759499937;11.8500193,48.0001927999376;11.8504406,47.9997722999377;11.8511479,47.998807599938;11.8546707,47.9960305999386;11.8557809,47.994583699939;11.8586452,47.9931552999393;11.8615969,47.9922383999395;11.863926,47.9907654999399;11.8640566,47.99040139994;11.8641436,47.9885682999404;11.8650669,47.9879794999406;11.8658684,47.9876865999406;11.8661496,47.9874675999407;11.8666673,47.9872547999407;11.8680721,47.9869123999408;11.8691798,47.9866988999409;11.8697707,47.9866785999409;11.8711705,47.9867896999408;11.8729816,47.9866316999409;11.8754628,47.9857178999411;11.8786432,47.9850751999412;11.8838397,47.9853928999412;11.8845058,47.9856562999411;11.8862758,47.986131399941;11.8883442,47.9865055999409;11.8908963,47.9868132999408;11.8983834,47.9870224999408;11.9022036,47.985963299941;11.903002,47.9856182999411;11.9049978,47.9845564999414;11.9068958,47.9836949999416;11.912095,47.9824055999419;11.9125427,47.9824097999419;11.920511,47.986328799941;11.9404407,47.981907499942;11.9427838,47.9812728999422;11.952517,47.9796286999426;11.9528408,47.9796858999425;11.9531081,47.9800648999424;11.9713544,47.9916422999397;11.9716384,47.9922634999395;11.9720959,47.9938651999392;11.9723031,47.9953047999388;11.972764,47.9972739999383;11.9726164,47.9977122999382;11.9759593,47.9970481999384;11.9812758,47.994361599939;11.9819657,47.9942562999391;11.987168,47.994489499939;11.9881654,47.9942027999391;11.9913848,47.9941492999391;11.9927751,47.9933803999393;11.9956989,47.9924777999395;11.9989988,47.9918010999397;12.0013379,47.9915782999397;12.0048339,47.9920824999396;12.0053071,47.9921016999396;12.0041866,47.99039499994;12.0038026,47.9888180999404;12.0023603,47.9850983999412;12.0028561,47.9829618999417;12.0042412,47.977749499943;12.0070389,47.973669999944;12.0175405,47.9569577999479;12.0173485,47.956746999948;12.0177431,47.9564224999481;12.0182446,47.9558738999482;12.0186961,47.9549279999484;12.0207051,47.9518233999492;12.0233973,47.9520518999491;12.0246124,47.9518099999492;12.0264582,47.9517267999492;12.0285272,47.9507200999494;12.0346623,47.9509510999494;12.0355514,47.9500551999496;12.0356122,47.9464916999504;12.0365025,47.9459755999505;12.041854,47.9424318999514;12.0441204,47.9436108999511;12.0447124,47.9436214999511;12.0457962,47.9424045999514;12.0528074,47.9384820999523;12.0553118,47.9363712999528;12.0585959,47.9331383999536;12.0636358,47.9252584999555;12.0694524,47.9232696999559;12.0705708,47.9226669999561;12.0706521,47.9225118999561;12.0706755,47.9219413999562;12.0709759,47.9201582999567;12.0714828,47.9198194999567;12.0727848,47.9180216999572;12.0720474,47.9168336999574;12.0738941,47.9126157999584;12.074212,47.9122224999585;12.089588,47.9081481999595;12.0907143,47.9073322999597;12.091243,47.90616369996;12.0919413,47.9031958999607;12.0930099,47.9000980999614;12.0931623,47.8999285999614;12.1019344,47.8948909999626;12.1023309,47.8948124999626;12.1033743,47.8944287999627;12.1036785,47.893126099963;12.1036294,47.8921256999633;12.1046505,47.8907209999636;12.1061473,47.8898438999638;12.108732,47.8887064999641;12.1098823,47.8880412999642;12.1156849,47.8841177999652;12.1162123,47.8836724999653;12.1161944,47.8830700999654;12.115436,47.8825827999655;12.1144046,47.8811377999659;12.113475,47.8796760999662;12.1128802,47.8789761999664;12.1125978,47.8778688999666;12.1115126,47.8758436999671;12.111171,47.8754097999672;12.1110662,47.8751741999673;12.1106624,47.8734336999677;12.1106055,47.8699673999685;12.1102821,47.8672624999691;12.1096762,47.8645207999698;12.1096637,47.8640861999699;12.1111049,47.8619648999704;12.1112486,47.8615852999705;12.111346,47.8583199999712;12.1111664,47.8567422999716;12.1104175,47.8553494999719;12.1102904,47.854916699972;12.1103017,47.8545775999721;12.1098138,47.8539694999723;12.1087478,47.8533832999724;12.1079781,47.8528259999725;12.1076134,47.8526369999726;12.108949,47.8520602999727;12.1124166,47.8503315999731;12.1148702,47.8495231999733;12.1170737,47.8492497999734;12.1182556,47.8488590999735;12.1190171,47.8484913999735;12.1196335,47.8480263999737;12.1234874,47.8474691999738;12.1255054,47.8470982999739;12.1256494,47.846859099974;12.1249065,47.8459387999742;12.1242647,47.8445835999745;12.1237741,47.8432713999748;12.1227758,47.8420045999751;12.1223512,47.8413574999752;12.121968,47.8399841999756;12.1230325,47.8399890999756;12.1245103,47.8405573999754;12.1262847,47.8413901999752;12.1357162,47.8441864999746;12.14112,47.8434667999747;12.1533619,47.846470599974;12.1574194,47.846677999974;12.1604029,47.8451597999743;12.1622102,47.8435226999747;12.1640702,47.842388799975;12.1642099,47.8418793999751;12.1642427,47.8410417999753;12.1646828,47.8406330999754;12.1663582,47.8402177999755;12.1682074,47.8393672999757;12.1702961,47.838130499976;12.1717722,47.8373904999762;12.1758212,47.833760099977;12.1791655,47.8350075999767;12.1899885,47.8366097999763;12.1998035,47.8375697999761;12.201084,47.837896099976;12.206019,47.8383597999759;12.2074004,47.8384580999759;12.2077385,47.8384152999759;12.2075459,47.8386847999759?radiuses=3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3&steps=true&geometries=geojson&overview=full&annotations=true"
done
```


works for me without any issues.

The only thing is that I am on macOS, but I doubt there is should be some difference here. Take a look on my questions above please and check logs of server - may be something useful is there.

**Comment by andreas-ullrich** [comment]
> > If i do several requests to a match service with around 200 points in each request in couple of seconds, there is just no response from the server.
> 
> What do you mean by "no response from the server"? Server does not respond after reasonable time? Or what?

The server just hangs there is no response.
I have to cancel the request.
Ok ill check the logs maybe i see something but there were no errors.

Regarding your test example: those requests would be in sequence right? 
In my situation those are often parallel.
Thank you for takeing the time to look into this issue.

**Comment by SiarheiFedartsou** [comment]
@andreas-ullrich how many parallel requests are you sending?

**Comment by andreas-ullrich** [comment]
around 10

**Comment by SiarheiFedartsou** [comment]
Okay, will try to look, but this time definitely not today ;)

**Comment by SiarheiFedartsou** [comment]
> around 10

Well, I couldn't reproduce it with only 10 parallel requests, but it was easy with 1000:
```
for i in {1..1000}
do
    echo "Sending request #${i}"
    curl "http://127.0.0.1:5000/match/v1/car/11.8296776,48.1080396999118;11.830006,48.1064633999122;11.8310606,48.1033010999129;11.8309893,48.1025808999131;11.8307815,48.1019317999133;11.8276887,48.0991409999139;11.8225219,48.0955067999148;11.8221303,48.0950693999149;11.8220986,48.094894899915;11.8213408,48.0940559999152;11.8207394,48.0931841999154;11.8186077,48.0891718999163;11.815527,48.0829185999179;11.8116318,48.0805670999184;11.8108052,48.0804971999184;11.8097247,48.0802723999185;11.8086941,48.0797268999186;11.8083032,48.0793967999187;11.8068801,48.077924299919;11.7914452,48.0712664999207;11.7893641,48.0705644999208;11.7865111,48.069734599921;11.7854853,48.0691632999211;11.7853476,48.0689187999212;11.77753,48.0608113999232;11.7759781,48.0603428999233;11.7756273,48.0601683999233;11.7735348,48.0600171999233;11.7719872,48.0600973999233;11.7724047,48.0590350999236;11.7726359,48.0582355999238;11.7721788,48.0569835999241;11.7710089,48.0561043999243;11.7645908,48.0502266999257;11.7638185,48.0492424999259;11.7644439,48.048770099926;11.7820285,48.0374748999287;11.7863894,48.0349348999293;11.8051003,48.0246557999318;11.8063574,48.0241109999319;11.8073801,48.023799099932;11.8105246,48.0231832999321;11.8116327,48.0228563999322;11.8127718,48.0222666999324;11.8130896,48.0216826999325;11.813831,48.0215788999325;11.8156686,48.0208095999327;11.8168685,48.0208924999327;11.817273,48.0207560999327;11.8194334,48.0192203999331;11.8441133,48.006932999936;11.8442724,48.0066186999361;11.8444916,48.0047203999366;11.8458207,48.002759499937;11.8500193,48.0001927999376;11.8504406,47.9997722999377;11.8511479,47.998807599938;11.8546707,47.9960305999386;11.8557809,47.994583699939;11.8586452,47.9931552999393;11.8615969,47.9922383999395;11.863926,47.9907654999399;11.8640566,47.99040139994;11.8641436,47.9885682999404;11.8650669,47.9879794999406;11.8658684,47.9876865999406;11.8661496,47.9874675999407;11.8666673,47.9872547999407;11.8680721,47.9869123999408;11.8691798,47.9866988999409;11.8697707,47.9866785999409;11.8711705,47.9867896999408;11.8729816,47.9866316999409;11.8754628,47.9857178999411;11.8786432,47.9850751999412;11.8838397,47.9853928999412;11.8845058,47.9856562999411;11.8862758,47.986131399941;11.8883442,47.9865055999409;11.8908963,47.9868132999408;11.8983834,47.9870224999408;11.9022036,47.985963299941;11.903002,47.9856182999411;11.9049978,47.9845564999414;11.9068958,47.9836949999416;11.912095,47.9824055999419;11.9125427,47.9824097999419;11.920511,47.986328799941;11.9404407,47.981907499942;11.9427838,47.9812728999422;11.952517,47.9796286999426;11.9528408,47.9796858999425;11.9531081,47.9800648999424;11.9713544,47.9916422999397;11.9716384,47.9922634999395;11.9720959,47.9938651999392;11.9723031,47.9953047999388;11.972764,47.9972739999383;11.9726164,47.9977122999382;11.9759593,47.9970481999384;11.9812758,47.994361599939;11.9819657,47.9942562999391;11.987168,47.994489499939;11.9881654,47.9942027999391;11.9913848,47.9941492999391;11.9927751,47.9933803999393;11.9956989,47.9924777999395;11.9989988,47.9918010999397;12.0013379,47.9915782999397;12.0048339,47.9920824999396;12.0053071,47.9921016999396;12.0041866,47.99039499994;12.0038026,47.9888180999404;12.0023603,47.9850983999412;12.0028561,47.9829618999417;12.0042412,47.977749499943;12.0070389,47.973669999944;12.0175405,47.9569577999479;12.0173485,47.956746999948;12.0177431,47.9564224999481;12.0182446,47.9558738999482;12.0186961,47.9549279999484;12.0207051,47.9518233999492;12.0233973,47.9520518999491;12.0246124,47.9518099999492;12.0264582,47.9517267999492;12.0285272,47.9507200999494;12.0346623,47.9509510999494;12.0355514,47.9500551999496;12.0356122,47.9464916999504;12.0365025,47.9459755999505;12.041854,47.9424318999514;12.0441204,47.9436108999511;12.0447124,47.9436214999511;12.0457962,47.9424045999514;12.0528074,47.9384820999523;12.0553118,47.9363712999528;12.0585959,47.9331383999536;12.0636358,47.9252584999555;12.0694524,47.9232696999559;12.0705708,47.9226669999561;12.0706521,47.9225118999561;12.0706755,47.9219413999562;12.0709759,47.9201582999567;12.0714828,47.9198194999567;12.0727848,47.9180216999572;12.0720474,47.9168336999574;12.0738941,47.9126157999584;12.074212,47.9122224999585;12.089588,47.9081481999595;12.0907143,47.9073322999597;12.091243,47.90616369996;12.0919413,47.9031958999607;12.0930099,47.9000980999614;12.0931623,47.8999285999614;12.1019344,47.8948909999626;12.1023309,47.8948124999626;12.1033743,47.8944287999627;12.1036785,47.893126099963;12.1036294,47.8921256999633;12.1046505,47.8907209999636;12.1061473,47.8898438999638;12.108732,47.8887064999641;12.1098823,47.8880412999642;12.1156849,47.8841177999652;12.1162123,47.8836724999653;12.1161944,47.8830700999654;12.115436,47.8825827999655;12.1144046,47.8811377999659;12.113475,47.8796760999662;12.1128802,47.8789761999664;12.1125978,47.8778688999666;12.1115126,47.8758436999671;12.111171,47.8754097999672;12.1110662,47.8751741999673;12.1106624,47.8734336999677;12.1106055,47.8699673999685;12.1102821,47.8672624999691;12.1096762,47.8645207999698;12.1096637,47.8640861999699;12.1111049,47.8619648999704;12.1112486,47.8615852999705;12.111346,47.8583199999712;12.1111664,47.8567422999716;12.1104175,47.8553494999719;12.1102904,47.854916699972;12.1103017,47.8545775999721;12.1098138,47.8539694999723;12.1087478,47.8533832999724;12.1079781,47.8528259999725;12.1076134,47.8526369999726;12.108949,47.8520602999727;12.1124166,47.8503315999731;12.1148702,47.8495231999733;12.1170737,47.8492497999734;12.1182556,47.8488590999735;12.1190171,47.8484913999735;12.1196335,47.8480263999737;12.1234874,47.8474691999738;12.1255054,47.8470982999739;12.1256494,47.846859099974;12.1249065,47.8459387999742;12.1242647,47.8445835999745;12.1237741,47.8432713999748;12.1227758,47.8420045999751;12.1223512,47.8413574999752;12.121968,47.8399841999756;12.1230325,47.8399890999756;12.1245103,47.8405573999754;12.1262847,47.8413901999752;12.1357162,47.8441864999746;12.14112,47.8434667999747;12.1533619,47.846470599974;12.1574194,47.846677999974;12.1604029,47.8451597999743;12.1622102,47.8435226999747;12.1640702,47.842388799975;12.1642099,47.8418793999751;12.1642427,47.8410417999753;12.1646828,47.8406330999754;12.1663582,47.8402177999755;12.1682074,47.8393672999757;12.1702961,47.838130499976;12.1717722,47.8373904999762;12.1758212,47.833760099977;12.1791655,47.8350075999767;12.1899885,47.8366097999763;12.1998035,47.8375697999761;12.201084,47.837896099976;12.206019,47.8383597999759;12.2074004,47.8384580999759;12.2077385,47.8384152999759;12.2075459,47.8386847999759?radiuses=3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3&steps=true&geometries=geojson&overview=full&annotations=true" &
    pids[${i}]=$!
done

for pid in ${pids[*]}; do
    wait $pid
done
```

I got `[error] HandleAccept error: Too many open files`, but I doubt it is a reason of your issue: 10 is too small to exceed limit of opened files, but please pay attention if you have it or not in your server's output.

Any chance you have problems on client-side? How code like I shared above works for you locally(but change 1000 to smaller value please)?

**Comment by andreas-ullrich** [comment]
Just tested it. Local run seem not to have any problems. Strange. I run the sever behind ngnix. Ngnix is in proxy mode. Maybe there is where the hickup happens.

**Comment by andreas-ullrich** [comment]
While looking at ngnix logs and running this test i see this:

`11:00:43 [error] 21895#21895: *5944 upstream timed out (110: Connection timed out) while reading response header from upstream, client: myip`

So its not ORSM problem.

**Comment by andreas-ullrich** [comment]
Ok after investigating it further and increasing the proxy_read_timeout I think I know how it happens. 
Additional to **match** request I also do 250*10 requests for **nearest** points. So it could be that I reach `Too many open files` Limit on OSRM side. It would be great to batch the requests for  **nearest** points.

**Comment by andreas-ullrich** [comment]
FYI I reach *5944 upstream timed out i.e OSRM does not respond already with 50 parallel requests.
