### ISSUE TITLE
Turn durations mismatch

### ISSUE THREAD

**Issue by nitko12** [Project-OSRM/osrm-backend#6363]
Hi,

I'm trying to get turn durations in osrm match api.

I've added 

```
util::json::Array duration_until_turn;
util::json::Array duration_of_turn;

for (size_t i = 0; i < unpacked_path_segments[idx].size(); ++i)
{
    auto &segment = unpacked_path_segments[idx][i];

    duration_until_turn.values.push_back(segment.duration_until_turn);
    duration_of_turn.values.push_back(segment.duration_of_turn);
}

annotation.values["duration_until_turn"] = duration_until_turn;
annotation.values["duration_of_turn"] = duration_of_turn;
```

to MakeRoute function in route_api.hpp file.

After testing against a few asserts on lot of data it seems that in 0.3% of legs there is mismatch of more than 0.2 seconds between the reported leg duration and sum of annotation durations + sum of turn duration.

e.g.

when calling 

`http://localhost:5050/match/v1/car/-74.360493,40.523957;-74.36095,40.523611;-74.361978,40.522855;-74.363173,40.521956;-74.364422,40.521026;-74.365658,40.520147;-74.366971,40.519175;-74.368438,40.518233;-74.370061,40.517339;-74.37177,40.516556;-74.373379,40.515928;-74.375042,40.515268;-74.376622,40.514601;-74.378342,40.513871;-74.380191,40.513086;-74.381921,40.512358;-74.383502,40.511706;-74.384746,40.511179;-74.385227,40.510982;-74.385351,40.510918;-74.386178,40.510589;-74.38733,40.510116;-74.388703,40.509529;-74.390005,40.508908;-74.391408,40.508181;-74.392878,40.507399;-74.394344,40.50663;-74.395856,40.505833;-74.39737,40.505019;-74.398843,40.504232;-74.400252,40.503507;-74.401629,40.502773;-74.403048,40.502009;-74.404578,40.501187;-74.40604,40.50045;-74.407631,40.499623;-74.409276,40.498792;-74.410835,40.497891;-74.411997,40.496649;-74.412721,40.495161;-74.413067,40.493587;-74.413373,40.492032;-74.41372,40.490429;-74.414149,40.488738;-74.415063,40.487135;-74.416233,40.485768;-74.417393,40.484425;-74.41861,40.483029;-74.419889,40.481542;-74.421263,40.480066;-74.422802,40.478741;-74.424392,40.477448;-74.42599,40.476145;-74.427672,40.4748;-74.429319,40.473435;-74.430921,40.47212;-74.432563,40.470778;-74.434224,40.469434;-74.436048,40.468227;-74.438316,40.467443;-74.440596,40.466819;-74.442957,40.466194;-74.445252,40.465558;-74.447563,40.464944;-74.44983,40.464324;-74.452196,40.463663;-74.454545,40.463006;-74.456777,40.462394;-74.45908,40.461772;-74.461422,40.46113;-74.463602,40.460529;-74.465567,40.459999;-74.467416,40.459496;-74.469137,40.459012;-74.470959,40.458518;-74.472843,40.457995;-74.474821,40.457457;-74.476889,40.456905;-74.478991,40.456309;-74.481299,40.455872;-74.483509,40.455501;-74.485623,40.455053;-74.487673,40.454318;-74.489588,40.453328;-74.491324,40.452088;-74.492871,40.4508;-74.494394,40.449545;-74.495884,40.448316;-74.497336,40.447102;-74.498708,40.445989;-74.49942,40.445418;-74.499781,40.445168;-74.50037,40.444601;-74.501447,40.443721;-74.502717,40.442668;-74.50417,40.441501;-74.505566,40.440377;-74.507018,40.439198;-74.508384,40.438061;-74.509752,40.436915?annotations=true&overview=false&steps=true`

on north america map

sum(leg["annotation"]["duration"]) + sum(leg["annotation"]["weight_of_turn"]) on one leg is 8.2
while leg["duration"] is 10.2

Could it be an edge case with phantom nodes? 

I don't fully understand how they work, any hint or help would be appreciated :)

**Comment by mjjbell** [comment]
What are the values in `leg["annotation"]["duration"]`?

Looking at the demo server results, that alone sums to 8.2, so I wonder if there's an issue with your patch.

**Comment by SiarheiFedartsou** [comment]
Stale.
