### ISSUE TITLE
Is it possible to add an empty start location and an in-between stop?

### ISSUE THREAD

**Issue by astridx** [Project-OSRM/osrm-backend#6364]
I want to provide a link with an in-between stop via osrm on a website. Is it possible to add a blank `start location text field`, so that a website user can enter their _address_ or _current location_?

Currently I use this link which does not offer the empty start test field

https://map.project-osrm.org/?z=12&center=50.349451%2C7.221755&loc=50.279649%2C7.222463&loc=50.272885%2C7.265739&hl=de&alt=0&srv=0

**Comment by Paritosh-26dev** [comment]
No, it is not possible to provide an in-between stop. However you can try different methods to do so.

**Comment by astridx** [comment]
Thanks for your answer. What different methodes do you mean.?
