### ISSUE TITLE
CMAKE command throws an error (parallel_pipeline.h: No such file or directory)

### ISSUE THREAD

**Issue by tunc01** [Project-OSRM/osrm-backend#6366]
Hi

I am running into fallowing issue which throws a error and exits the script. I already tried to find a solution via google but cant….

This is the error …

command: cmake /srv/osrm/osrm-backend/

Scanning dependencies of target EXTRACTOR
[  0%] Building CXX object CMakeFiles/EXTRACTOR.dir/src/extractor/compressed_edge_container.cpp.o
[  2%] Building CXX object CMakeFiles/EXTRACTOR.dir/src/extractor/edge_based_graph_factory.cpp.o
/srv/osrm/osrm-backend/src/extractor/edge_based_graph_factory.cpp:35:10: fatal error: tbb/parallel_pipeline.h: No such file or directory
   35 | #include

**Comment by jcoupey** [comment]
Looks like a duplicate of #6361.

**Comment by tunc01** [comment]
> Looks like a duplicate of #6361.

Thanks! That worked for me :)
