### ISSUE TITLE
How to get route for large datasets

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#6367]
Hello
I want to run osrm for getting route for a large dataset of different countries. I know that running one instance of OSRM for all the dataset is expensive and in some issues it is suggested to split the dataset into different parts and run different instances. But my question is how can we get the route between these parts? If we have different osrms for different countries how can we get a route from different countries (with live traffic data updates)

Thanks

**Comment by datendelphin** [comment]
You can't. In that case you will have to go the expensive route and have a single instance

**Comment by safe-bug** [comment]
@datendelphin Thanks for your reply. So how is Mapbox handling world routing (with traffic updates)? Do they have large servers for handling it?

@danpat Mentioned [here](https://github.com/Project-OSRM/osrm-backend/issues/6208#issuecomment-1040879061) that the planet file should be cut into smaller pieces.

**Comment by datendelphin** [comment]
Don't know about mapbox. routing.openstreetmap.de, which I take care of, uses three regions. Most boundaries are in the sea so they won't be noticed.
