### ISSUE TITLE
OSRM Routing Specifying Starting and Endpoints Creates Some Issues in Routing Service

### ISSUE THREAD

**Issue by techGIAN** [Project-OSRM/osrm-backend#6368]
Hi, I'm new to OSRM and it seems like there seems to be wrong with the routing service? I have the following origin and destination points in Rome, Italy:
```
o_lon, o_lat  = 41.978746, 12.516148
d_lon, d_lat = 41.883337, 12.557252
```
And then defined the following method as per the following blog tutorial: https://www.thinkdatascience.com/post/2020-03-03-osrm/osrm/:
```
def get_route(pickup_lon, pickup_lat, dropoff_lon, dropoff_lat):
    
    loc = "{},{};{},{}".format(pickup_lon, pickup_lat, dropoff_lon, dropoff_lat)
    url = "http://127.0.0.1:5001/route/v1/driving/"
    r = requests.get(url + loc) 
    if r.status_code!= 200:
        return {}
  
    res = r.json()   
    routes = polyline.decode(res['routes'][0]['geometry'])
    start_point = [res['waypoints'][0]['location'][1], res['waypoints'][0]['location'][0]]
    end_point = [res['waypoints'][1]['location'][1], res['waypoints'][1]['location'][0]]
    distance = res['routes'][0]['distance']
    
    out = {'route':routes,
           'start_point':start_point,
           'end_point':end_point,
           'distance':distance
          }

    return out
```
I ran this method (of course after running the server through `docker` using the `centro-latest.osm.pbf` from the `Geofabrik` site: https://download.geofabrik.de/europe/italy/centro.html):
```
route_dict = get_route(o_lon, o_lat, d_lon, d_lat)
print(route_dict)
```
And I got the following result for the dictionary:
```
{'route': [(41.28146, 13.91196), (41.28146, 13.91196)],
 'start_point': [41.281455, 13.911961],
 'end_point': [41.281455, 13.911961],
 'distance': 0}
```
Clearly this is wrong because the origin and destination points I specified do not match the resulting `start_point` and `end_point` (i.e., a major difference in geocoordinates). And clearly it only specifies a single point instead of a series of line segments (i.e., the `route` specifies two identical points and the `distance` is 0). I'm not sure what is going on here and if it can be fixed. Although the resultant still specifies some coordinate in Italy, it does not seem to specify a coordinate in Rome, which I am after. Any resolution for this is highly appreciated. Thank you so much.

**Comment by nilsnolde** [comment]
You’re mixing lat/lon, see your first code block

**Comment by techGIAN** [comment]
> You’re mixing lat/lon, see your first code block

When you mean this, do you mean that the latitude goes first before the longitude in the url query below?
```
loc = "{},{};{},{}".format(pickup_lon, pickup_lat, dropoff_lon, dropoff_lat)
```

**Comment by nilsnolde** [comment]
This will work (switch lat/lon):
```
o_lat, o_lon  = 41.978746, 12.516148
d_lat, d_lon = 41.883337, 12.557252
```

**Comment by techGIAN** [comment]
Oh I'm so dumb. I clearly do not know the geocoordinates of Rome. Thanks for resolving!
```
{'route': [(41.97875, 12.51615),
  (41.97806, 12.51501),
  (41.97273, 12.52195),
  (41.96647, 12.52687),
  (41.96183, 12.52756),
  (41.95858, 12.53552),
  (41.95039, 12.54908),
  (41.94507, 12.55239),
  (41.93873, 12.55225),
  (41.93315, 12.55512),
  (41.93153, 12.56074),
  (41.9279, 12.56421),
  (41.92585, 12.56367),
  (41.92418, 12.56766),
  (41.92097, 12.56409),
  (41.91856, 12.56433),
  (41.91614, 12.56214),
  (41.91206, 12.55369),
  (41.90773, 12.55631),
  (41.88847, 12.56119),
  (41.88355, 12.56069),
  (41.88322, 12.55623),
  (41.88333, 12.55726)],
 'start_point': [41.978745, 12.516146],
 'end_point': [41.883332, 12.557258],
 'distance': 13922.5}
```

**Comment by SiarheiFedartsou** [comment]
Seems to be resolved, but feel free to re-open in the case if not.
