### ISSUE TITLE
Table api duration reporting weight

### ISSUE THREAD

**Issue by nitko12** [Project-OSRM/osrm-backend#6369]
Hi,

I've added a segment speed file to usa map, but only modified durations, not weights, 

like this: 

`3708256753,2128508369,39,`

and while route api returns different values for those two, table seems to return just the weight.

e.g.

`/table/v1/car/-74.569642,42.612666;-74.469137,42.674453`

```
	"durations": [
		[
			0,
			994.6
		],
		[
			574.6,
			0
		]
	],
```

while 

`/route/v1/car/-74.569642,42.612666;-74.469137,42.674453`

```
			"weight": 988.4,
			"duration": 819,
			"distance": 19937.4
```

is that intentional?

I've tried smaller maps, and Monaco seems to return the correct value.

I am using latest master and ch algorithm.

**Comment by mjjbell** [comment]
Do you still have this issue if you use a smaller OSM extract (e.g. New York state)?

**Comment by nitko12** [comment]
Hi,

issue seems to be gone, was probably my mistake,
sry for bothering you :)
