### ISSUE TITLE
Assertion makes osrm-extract fail

### ISSUE THREAD

**Issue by warrenwyf** [Project-OSRM/osrm-backend#6373]
I encountered an interruption while executing the osrm-extract command while using Armenia's OSM data:

```
[assert][0x7000029eb000] /Users/runner/work/osrm-backend/osrm-backend/src/guidance/turn_lane_matcher.cpp:181
in: bool osrm::guidance::lanes::canMatchTrivially(const osrm::guidance::Intersection &, const osrm::guidance::lanes::LaneDataVector &): lane_data[lane].from != INVALID_LANEID
libc++abi: terminating
[1]    87885 abort      node_modules/osrm/lib/binding/osrm-extract  -p
```

The test data can be downloaded from http://download.geofabrik.de/asia/armenia-latest.osm.pbf

It looks like there may be errors in the data, but because of the assertion, osrm-extract doesn't ignore the errors and interrupts the execution.

**Comment by SiarheiFedartsou** [comment]
Do you build OSRM manually? We probably should have disabled asserts in Release mode 🤔

**Comment by SiarheiFedartsou** [comment]
> Do you build OSRM manually? We probably should have disabled asserts in Release mode 🤔

I can reproduce only if I explicitly build OSRM like:
```
cmake -DENABLE_ASSERTIONS=ON .. && make -j8
```

**Comment by SiarheiFedartsou** [comment]
I localized the issue to this function call(after it one of TurnLaneData.from starts to be equal 255) https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/src/guidance/turn_lane_handler.cpp#L327

Link to current version of armenia-latest.osm.pbf with which problem is reproducible https://drive.google.com/file/d/116GlPrZOWSFYTMjcB9BnsH31OdGg047H/view?usp=sharing

**Comment by warrenwyf** [comment]
> 

No, I used the prebuilt binary from node-osrm:

https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v93-darwin-x64-Release.tar.gz

**Comment by warrenwyf** [comment]
> Do you build OSRM manually? We probably should have disabled asserts in Release mode 🤔

No, I used the prebuilt binary from node-osrm:

https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v93-darwin-x64-Release.tar.gz

**Comment by mjjbell** [comment]
OS X release builds have assertions enabled: https://github.com/Project-OSRM/osrm-backend/blob/660cea8fcc4af14f6c231e40057df713fb311126/.github/workflows/osrm-backend.yml#L276

It's probably a historical artifact that can be removed.

**Comment by mjjbell** [comment]
Actually, I'm also getting assertions on the Linux release build too. Now I am confused.

**Comment by warrenwyf** [comment]
> Actually, I'm also getting assertions on the Linux release build too. Now I am confused.

Yes, but the executable files in the docker image seems to be fine

**Comment by mjjbell** [comment]
This is the problematic intersection: https://www.openstreetmap.org/#map=19/40.17416/44.50071

![image](https://user-images.githubusercontent.com/1063186/192896181-413cab4d-e939-49a3-8407-e7343417d14d.png)

It includes a road whose only possible turn has a restriction applied: https://www.openstreetmap.org/relation/14065440
 
![image](https://user-images.githubusercontent.com/1063186/192896544-6fec3b66-5054-43c0-821d-35b9de936267.png)

Therefore 
a) This intersection could probably do with some remodeling in OSM.
b) OSRM intersection logic should be made robust to these types of mistakes.
