### ISSUE TITLE
Timestamps for logs

### ISSUE THREAD

**Issue by nilsnolde** [Project-OSRM/osrm-backend#6374]
I’d like to add timestamps to the processing logs of the various commands. I didn’t look into the code base yet, not sure if the logging is centralized, so it’d be quick to add, or it needs a logging abstraction.

We had some issues lately where custom PBFs take a whole longer to pass through osrm-contract. Timestamps would help to see in which phase of the pipeline it’s hanging. And it’s general good practice IMO. Shout out if any objections/thoughts.

**Comment by SiarheiFedartsou** [comment]
At glance it looks like it will be as easy as modifying this `Log` class. https://github.com/Project-OSRM/osrm-backend/blob/be353630d5e845b1dc64a4b5e467b6a4bc1addbf/include/util/log.hpp#L56

**Comment by nilsnolde** [comment]
Thanks, that was what I hoping for:)

**Comment by SiarheiFedartsou** [comment]
Here is draft https://github.com/Project-OSRM/osrm-backend/pull/6375
How it looks now for osrm-extract:
<img width="964" alt="Screenshot 2022-09-23 at 16 25 16" src="https://user-images.githubusercontent.com/266271/191983595-8f8297df-f0be-4b8d-b752-eed6453653de.png">

I still see some logs which have no timestamps though and also not sure we need one more dependency because of it, but fmtlib is nice library(and actually is the same as `std::format` from C++20)

**Comment by SiarheiFedartsou** [comment]
> I still see some logs which have no timestamps though

This `ok, after` is the "end" of `Collecting traffic signal information on 2292 signals...`. 

<img width="1492" alt="Screenshot 2022-09-23 at 16 35 53" src="https://user-images.githubusercontent.com/266271/191985936-2e213570-06f1-43ec-87e6-598d73d15203.png">

We use `UnbufferedLog` to output it https://github.com/Project-OSRM/osrm-backend/blob/be353630d5e845b1dc64a4b5e467b6a4bc1addbf/src/extractor/extraction_containers.cpp#L1196

I.e. if some other logs are happening in the middle(like these warnings in this case) they are "interleave" logs coming from this `UnbufferedLog`, tbh I'd stop using this.

**Comment by SiarheiFedartsou** [comment]
Current log system is prone to race conditions, i.e. if we are doing something like:

```
util::Log() << "Hello, " << "OSRM";
```

we have no guarantee that log will be outputted "atomically", instead we may have it interleaved by some another log happening in another thread. 

What about refactoring it a bit to something like:
```
util::Log::info("{} {}", "Hello, ", "OSRM");
```

This way we will be able to guarantee that logs are "atomic".


@mjjbell @nilsnolde would appreciate your opinion here

**Comment by nilsnolde** [comment]
>  I.e. if some other logs are happening in the middle(like these warnings in this case) they are "interleave" logs coming from this UnbufferedLog, tbh I'd stop using this.

Yeah, I agree, those could easily be refactored to use standard logging. No need for the "ok, after.. " bit if we have timestamps IMO (if it's not ok, it'll throw right). What doesn't take more than a minute is not worth measuring time on anyways;)

> What about refactoring it a bit to something like:
I'd put it in an issue, unless you really want to tackle it now:) It's true, but hasn't ever been reported or observed I think?

Thanks a ton for this @SiarheiFedartsou ! I'll immediately try your branch on our PBFs!

**Comment by nilsnolde** [comment]
Or we report down to milliseconds? Could do "22-09-23" instead to save some space?

**Comment by SiarheiFedartsou** [comment]
> Or we report down to milliseconds? Could do "22-09-23" instead to save some space?

Not sure I got it, but time stamps I output in this PR are precise up to second.

**Comment by nilsnolde** [comment]
Sorry that wasn't too clearly worded.. 

What I meant: we can get rid of `UnbufferedLog` in multi-threaded functions, I agree. There's some spots where it makes sense, e.g. when printing progress (in %) in single-threaded processes. 

But all the instances where it's printing it's busy with some processing and then later it adds "ok, after .." on the same line and reports the duration down to nanoseconds, they can be removed IMO (esp if they're running in multiple threads). Then, if we add timestamps which go down to milliseconds, I think that's all the resolution one needs (and we can add another line saying 
`<whatever_process> done` if we wanna be explicit).

What do you think @SiarheiFedartsou ? I'd like to help out, but got a weird error building tbb with `ENABLE_CONAN=ON`..

```
[cmake] [ 58%] Building CXX object src/tbb/CMakeFiles/tbb.dir/observer_proxy.cpp.o
[cmake] [ 60%] Linking CXX shared library ../../gnu_12.2_cxx11_64_release/libtbbbind_2_4.so
[cmake] /usr/bin/ld: error: /usr/lib: read: Is a directory
[cmake] collect2: error: ld returned 1 exit status
```

I'm on Arch Linux, `gcc 12.1.0`, `ld 2.39`. Any clue?

**Comment by SiarheiFedartsou** [comment]
> I also have https://github.com/Project-OSRM/osrm-backend/issues/6219#issue-1168477464 with ld not linking properly on Arch, I can try again with Ubuntu 22.04 later.

yeah, I would try on Ubuntu. I’ll probably try to build it in some Arch-based docker image one day - may be will find something.

And, yeah, agree about your “nanoseconds” point :)

**Comment by nilsnolde** [comment]
It's ok for me, there's now and then projects where I have to Ubuntu instead, I have it in dual-boot. But thanks for the offer. I'm really happy to see you pushing things again with @mjjbell !

There weren't many occurrences of `UnbufferedLog` where it's problematic. In fact, you found the only user-facing one:) Others will be mangled with Debug Logs in a very similar way, but IMO Debug is fine. Not that it's a huge deal anyways, I did a few changes here based on your branch: https://github.com/Project-OSRM/osrm-backend/compare/sf-log-timestamp...gis-ops:osrm-backend:nn-log-timestamp-cleanup?expa

Milliseconds is more trouble than it's worth. The C++20 spec says it should print milliseconds when using `:%S` format specifier, but `fmt` doesn't (yet). Since we're keeping most timers it's fine to only display seconds resolution IMO.

Regarding this:
```
we have no guarantee that log will be outputted "atomically", instead we may have it interleaved by some another log happening in another thread.
```

The `Log()` seems to be guarded by a `std::lock_guard`. Or is the problem the streaming? I might misunderstand smth basic here :sweat_smile:

**Comment by SiarheiFedartsou** [comment]
> The Log() seems to be guarded by a std::lock_guard. Or is the problem the streaming? I might misunderstand smth basic here

Yep, I am a bit wrong here. In case of `util::Log` there is no problem, because we have mutex here https://github.com/Project-OSRM/osrm-backend/blob/660cea8fcc4af14f6c231e40057df713fb311126/src/util/log.cpp#L113

But `UnbufferedLog` writes directly to `std::cout/std::cerr` as I can see, that's why we may have this problem I mentioned.

**Comment by nilsnolde** [comment]
I checked all usages of UnbufferedLog, it's not used in multi-threaded functions AFAICT. I only changed the one occurrence in traffic signals, where it was mangled with warnings. Others looked fine.

If you want you can implement my changes, for me this PR looks good either way:)

**Comment by SiarheiFedartsou** [comment]
I updated PR to also output fractional part of second. Implementation is a bit ugly on my test, but it works!
```
 const auto timestamp = std::chrono::system_clock::now();
            return fmt::format(
                "{}[{:%FT%H:%M:}{:%S}] [{}] ", is_terminal ? color : "", timestamp, timestamp.time_since_epoch(), level);
```
<img width="875" alt="Screenshot 2022-09-27 at 20 32 41" src="https://user-images.githubusercontent.com/266271/192608152-35630f3a-6861-468b-b0c6-770ffa5f0d80.png">

**Comment by SiarheiFedartsou** [comment]
Going to merge https://github.com/Project-OSRM/osrm-backend/pull/6375 soon.

> I only changed the one occurrence in traffic signals, where it was mangled with warnings.

btw IMO this is the main problem with UnbuferredLog - you never know if methods you are calling will log something or not. That's why I'd propose to get rid of it completely(at least I don't see any benefits of it)

**Comment by nilsnolde** [comment]
The benefit AFAICT is to print stuff on the same line, eg when reporting progress in percent, which is arguably nice for UX. It just the logs fairly concise. I’d personally keep it, but have not a very strong opinion about it.

**Comment by SiarheiFedartsou** [comment]
Closing as #6375 was merged.
