### ISSUE TITLE
osrm-extract error Floating point exception

### ISSUE THREAD

**Issue by pythonpanda-beep** [Project-OSRM/osrm-backend#6377]
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script profiles/car.lua
[info] Input file:xxx.osm.pbf
[info] Profile: car.lua
[info] Threads: 6
[info] Parsing in progress..
[info] input file generated by xxx
[info] timestamp: n/a
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
Floating point exception

when use sol.h set_associative_insert(is_associative(), L, self, it, key, std::move(value));

gcc 4.9.0
c++14

**Comment by SiarheiFedartsou** [comment]
Stale.
