### ISSUE TITLE
OSMR doesn't route through a tunnel

### ISSUE THREAD

**Issue by dafadllyn** [Project-OSRM/osrm-backend#6384]
For some unknown reason (is it`lanes=1`, `maxwidth=1.8` or `oneway=alternating`?), OSMR doesn't want to route cars through [this](https://www.openstreetmap.org/way/58733500) and the following tunnels (Strada delle Gallerie) and stops before it:

https://map.project-osrm.org/?z=16&center=44.250602%2C9.436719&loc=44.254590%2C9.432192&loc=44.246813%2C9.437792&hl=en&alt=0&srv=0

Note that Strada delle Gallerie is the main route for cars to get from Riva Trigoso (Sestri Levante) to Moneglia (or in the other direction).

**Comment by mjjbell** [comment]
It is `maxwidth=1.8`.

The demo site car profile sets a width of 1.9
https://github.com/fossgis-routing-server/cbf-routing-profiles/blob/16453fa5ded78671560dba15e124ea5bac6d52d3/car.lua#L43

**Comment by dafadllyn** [comment]
Okay, thanks for the clarification. This seems sensible.
