### ISSUE TITLE
Update underlying graph data with OSM diff.

### ISSUE THREAD

**Issue by DDAK** [Project-OSRM/osrm-backend#6389]
I have a sync script which pulls the latest version of the osm file from the geofabrik server, once every week. I run `osrm-extract` on this osm file, which takes about 3 hours, on average-- 3hrs every week. In my case, I am only interested in the road network and as such, I was thinking if we could leverage the diff of the current and previous osm files (using `osmium-diff`). Can we, somehow, make `osrm-extract` patch the underlying graph (which was created in the previous run) with the changes in the diff file only, thereby, reducing 3hr to minutes probably (assuming differences in the road network aren't many)? 

Any pointers and guidance would be of great help. 

Thanks.

**Comment by mjjbell** [comment]
Right now I think this will be difficult to achieve.
The further through the extract processing you are, the harder it is to track the impact an OSM change would have on the OSRM graph structure. So there's going to be a tradeoff between diff complexity and how much processing you'll have to redo.

If you are interested in trying, you can take a look at the [extraction containers](https://github.com/Project-OSRM/osrm-backend/blob/21888334dd1e0fbbd25cc62c725eb33bb7968147/include/extractor/extraction_containers.hpp). These are the entities extracted from OSM before the main graph transformations begin.
It could be possible to generate some diff functions for these structures, but as it's still quite early in the processing it might not save much time.

Making `osrm-extract` more diff-friendly by splitting extraction into sub-graphs and combining results would seem like the way this could be achieved. I expect there's academic literature around how to do this, but it would be a big change from how it currently works.

**Comment by DDAK** [comment]
@mjjbell Got it. I like the idea of splitting extraction into sub-graphs and then combining the results, this can allow `osrm-extract` to run in parallel over subregions and then combine the results.  

Thanks.
