### ISSUE TITLE
Obviously suboptimal route using bicycle.lua (UK trunk roads)

### ISSUE THREAD

**Issue by risicle** [Project-OSRM/osrm-backend#639]
Hi,

Certainly as of cc73ed19b3f83cc7e718a94580c79d02aea8567a (and my slightly older version from the cmake branch), using the test file:

http://ris.dev.openstreetmap.org/data/osrm_issues/edgware_road.osm.bz2

using bicycle.lua and performing the query:

/viaroute?loc=51.524672505361124,-0.17700517322947706&loc=51.524956109010468,-0.17625807070360855

sends me on a 1.6km, 472 second journey (these points are <100m apart and fairly straight-connected, plainly tagged with no funny restrictions I can see)

It's slightly erratic - if I include a slightly larger area in the extract it sends me on a >2km, >500s journey.

**Comment by MoKob** [comment]
This is part of a bigger issue (country based defaults). Closing here in favour of https://github.com/Project-OSRM/osrm-backend/issues/2772.
