### ISSUE TITLE
What is the required memory for each country?

### ISSUE THREAD

**Issue by shawara** [Project-OSRM/osrm-backend#6396]
I am trying to use `osrm-backend` in Kubernetes for Pakistan country, the instance keeps restarting because of the memory limit of 800MB, so is there a document that shows the memory requirement for each country?

**Comment by nilsnolde** [comment]
Nope but there is a fairly recent document for the planet: https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements

From there you can sorta eyeball it, you’ll probably be right within 10-50%, mostly depending on the ratio of roads to all the other stuff (like buildings) in the extract you choose (the lower that ratio, of course the less RAM you need compared to the planet’s average).
