### ISSUE TITLE
Provide instructions to put the berlin-latest* files in a folder

### ISSUE THREAD

**Issue by kevinlinxc** [Project-OSRM/osrm-backend#6398]
Bad:
![image](https://user-images.githubusercontent.com/44324811/195187585-3ca2bdf1-9bdb-40b2-b307-5b370ba398c3.png)

How can I adjust the docker commands to work with a subfolder of my current directory? (Imagine I have no Docker experience, which is pretty much the truth)

Small nit: wget is fake in Windows and requires a -O flag: https://unix.stackexchange.com/a/359977.

**Comment by SiarheiFedartsou** [comment]
Hi

> How can I adjust the docker commands to work with a subfolder of my current directory? 

what exactly do you mean here? You want to put all output files to sub folder? Or what?

**Comment by kevinlinxc** [comment]
Let's say I am in my root directory

~/app

I download berlin-latest.osm.pbf to a subfolder, ~/app/osrm-data.

I was trying to figure out how to modify the docker command so I could still run it from the root directory. 
```
docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf
```

The obvious answer is to change /data/berlin... to /data/osrm-data/berlin... which does work, it just wasn't obvious to me because the /data/ path is in the container, not the outside. I apologize, this issue is just my inexperience with Docker.
