### ISSUE TITLE
OSRM not routing based on Address 

### ISSUE THREAD

**Issue by MapsKrishna** [Project-OSRM/osrm-backend#6408]
Hi Team,
OSRM not routing based on Address.
But when i search with the building name for the same address the routing is possible.
I have the local instance of the OSRM FE and BE.
I have created  a map selecting a small area and tried to work. It doesnt show based on the address.
Can any one help ?

**Comment by jcoupey** [comment]
OSRM is not designed to ingest addresses, you can only put coordinates in actual routing requests. If you input an address (e.g. like in the demo frontend http://map.project-osrm.org), then there is an extra [geocoding](https://en.wikipedia.org/wiki/Address_geocoding) step involved.

From your description, it looks like you have more of a geocoding problem than a routing problem?

**Comment by MapsKrishna** [comment]
Thank you @jcoupey for the quick reply.
Yes, when location name is used routing is done without any issue.
Incase of Address used as you mentioned geocoding needs to be used.
Can you please guide me how to implement the geocoding for OSRM.

Thank You

**Comment by SiarheiFedartsou** [comment]
@MapsKrishna you can start from something like https://github.com/pelias/pelias

**Comment by jcoupey** [comment]
Another geocoding project, used on osm.org and the OSRM demo frontend is https://github.com/osm-search/Nominatim. Closing as this is not directly OSRM-related.
