### ISSUE TITLE
Map Data error or routing error on an edited junction?

### ISSUE THREAD

**Issue by UKChris-osm** [Project-OSRM/osrm-backend#6412]
Hi,

I'm very new to OSRM so this could simply be an error on my part.

I recently edited a [junction](https://www.openstreetmap.org/#map=18/51.02438/-3.07059) in my local town which has been redeveloped. At the junction, a driver used to be able to come from the West (on Toneway) and turn South (into Bridgwater Road). This turn has been removed, and a driver is now required to drive straight on, and use the following roundabout to double back.

![osrm-1](https://user-images.githubusercontent.com/59393694/196035335-8e8462b2-8aad-4afc-82cc-539e51ca5f4e.png)

Using the demo site, the [correct routing](http://map.project-osrm.org/?z=16&center=51.023210%2C-3.074198&loc=51.024054%2C-3.090017&loc=51.023986%2C-3.071129&hl=en&alt=0&srv=0) occurs up to a certain point, just before the driver joins Bridgwater Road.

![osrm-2](https://user-images.githubusercontent.com/59393694/196035621-598d3ce0-57d9-4185-bdc7-bdd0d3ac49d3.png)

However, if I extend the end point a little further down Bridgwater Road, the [routing changes](http://map.project-osrm.org/?z=16&center=51.023750%2C-3.074541&loc=51.024054%2C-3.090017&loc=51.023541%2C-3.071623&hl=en&alt=0&srv=0) from using the roundabout to double back, and instead suggests using a small business park to turn around.

![osrm-3](https://user-images.githubusercontent.com/59393694/196036499-17a1ea4d-4ac8-49b2-98e4-f831dbd6b499.png)

This technically isn't incorrect routing, as the route is accessible to cars & motorbikes, but a lorry wouldn't be able to route in this manor. It's also an inconvenient way to route towards Bridgwater Road.

Is this caused by an error with the map data on my part, or is OSRM using the shortest route as expected?

**Comment by mjjbell** [comment]
It's an OSRM issue. It evaluates the cost of the route via the business park to be cheaper than via the roundabout.

OSRM does penalise turns, with the penalty dependent on the angle. But it evaluates turns independently, so it's not taking into consideration the "smoothness" of the journey (e.g. taking multiple turns in quick succession), which is the difference here. I also suspect it's not treating the turn in the business park as a u-turn, which would normally be [heavily penalised.](https://github.com/Project-OSRM/osrm-backend/blob/5e5f1f4add6d86b097569545b670de513ebc6b04/profiles/car.lua#L26)

According to the [docs](https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/docs/profiles.md#process_turnprofile-turn) the turn function also has access to the road types involved in the turn, which the car profile is not taking advantage of. It might make sense to apply additional penalties when turning between roads of vastly different speeds (e.g. motorway->service road), as is the case here.

Interestingly, if I route with a  [truck profile](https://github.com/Project-OSRM/osrm-profiles-contrib/blob/master/5/21/truck-soft/car.lua) (which penalises turns more severely), it does select the roundabout route.

**Comment by SiarheiFedartsou** [comment]
Stale,
