### ISSUE TITLE
Node JS Binding issue with version 5.26 and 5.27 

### ISSUE THREAD

**Issue by kabilsharma** [Project-OSRM/osrm-backend#6414]
# Feature

Thank you guys for releasing version 5.27. We were hoping that it would be compatible with node js binding. We are geeting following issues 

This is our docker file 

FROM node:10-stretch

RUN apt-get update
RUN apt-get install -y make libstdc++
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# Install dependecies first (and keep them cached)
COPY app/package.json /usr/src/app/
RUN yarn install

# Bundle app source (doesn't require of installing the node_modules again)
COPY app/ /usr/src/app

EXPOSE 5000

CMD ["yarn", "start"]

We get error glib_2.27 not found error

I need to use nvm 16  i don't know why?

https://stackoverflow.com/questions/2856438/how-can-i-link-to-a-specific-glibc-version

following this 

https://www.npmjs.com/package/osrm

https://github.com/door2door-io/osrm-express-server-demo

**Comment by datendelphin** [comment]
Debian stretch doesn't even get security updates any more. Can't you migrate to bullseye? Or is that stretch not the Debian version?

**Comment by kabilsharma** [comment]
Is there any upgraded version of this package which is compatible with latest realease(5.27).  
(https://www.npmjs.com/package/osrm)

**Comment by mjjbell** [comment]
New packages are available here: https://www.npmjs.com/package/@project-osrm/osrm
Please read the repo README for upgrade instructions.

**Comment by glassonion1** [comment]
It's hard to set up a node.js server without a sample. I created a sample code for node.js.
https://github.com/glassonion1/osrm-server-demo

**Comment by SiarheiFedartsou** [comment]
Stale.
