### ISSUE TITLE
Longer parallel foot route instead of direct route on roads

### ISSUE THREAD

**Issue by boothym** [Project-OSRM/osrm-backend#6418]
Based off a report in this note: https://www.openstreetmap.org/note/3393725 which contains links.

Instead of taking the direct route on the primary road, OSRM shows a route which is 100m+ longer, and goes down/up two sets of steps. https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=55.95028%2C-3.18763%3B55.95331%2C-3.18874

![a](https://user-images.githubusercontent.com/16965772/197361178-a9df5e5e-8cd9-4d6b-b00d-2763146c3908.JPG)
There's also another one nearby, which again strays away from the road - though if you drag the end point slightly south it goes direct. https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=55.94763%2C-3.18631%3B55.95012%2C-3.18753

I'm basically wondering, if there is an explanation for this? 

Although the note mentions Komoot and brouter also having an issue, changing to GraphHopper provides the direct route, so it does seem to be more of a routing issue than OSM problem.

**Comment by mjjbell** [comment]
I get the expected behaviour with `master` and the [default foot ](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/foot.lua) profile.
