### ISSUE TITLE
osrm-prepare hangs at [info createHierarchy.cpp:120] Parsing speedprofile from profile.lua

### ISSUE THREAD

**Issue by thomaswilkins** [Project-OSRM/osrm-backend#642]
After building OSRM according to the instructions found at:

https://github.com/DennisOSRM/Project-OSRM/wiki/Building%20OSRM

on an Ubuntu 12.04 LTS machine running osrm-prepare on an extracted map of Europe from Geofabrik hangs after the following output:

````
[info createHierarchy.cpp:78] Using restrictions from file: ../maps/europe-latest.osrm.restrictions
[info createHierarchy.cpp:120] Parsing speedprofile from profile.lua
````

**Comment by daniel-j-h** [comment]
By now we show the progress for every binary; the debug mode shows additional information.
