### ISSUE TITLE
Using osrm package in R : Connecting to the network using a motorway creates a long route.

### ISSUE THREAD

**Issue by tra6sdc** [Project-OSRM/osrm-backend#6425]
Hello, I am using the osrm package in R to estimate some network travel distances and times. 

I have this origin/destination route and the distance isn't reasonable. What is happening is that the origin is connecting to a motorway, between junctions, then travelling down to the motorway exit, leaving the motorway and travelling back to the destination. This distance is 11.1km whilst the distance when the origin connects to a local road should be 300m (or 500m if we count the distance to connect to the road). 

http://map.project-osrm.org/?z=13&center=53.623925%2C-1.570873&loc=53.642224%2C-1.533966&loc=53.641620%2C-1.528497&hl=en&alt=0&srv=0

I have setup my own local server using these instructions: https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM .

I changed these two parameters in the car.lua files from the default (my .lua files are old, the date stamp is July, 2018):
````
properties.continue_straight_at_waypoint   = false
properties.left_hand_driving               = true
```` 

Is there a way to stop the connecting to certain types of road? Thanks.

**Comment by SiarheiFedartsou** [comment]
> when the origin connects

“connects” here means snapping of raw  coordinate to road graph, right? If so, could you please may be draw what you expect to have? Tbh this motorway seems to be the only good place to snap to in example you provided.

**Comment by tra6sdc** [comment]
The origin is a population weighted centroid for UK census data 'tracts' - so I have no influence on its location. I would like to be able to dis-allow connections to motorways. Motorways have very restricted access and exit locations, whilst non-motoway roads are more flexible. Indeed, it is **not possible** to access the motorway at the location that this journey does. So a connection to Cliff Road or Hollin Lane. Such a connection would provide a more accurate representation of the journey.

**Comment by SiarheiFedartsou** [comment]
@tra6sdc you are saying only about origin of route, right? The rest of the route may go through motorway if it works as you expect?

**Comment by tra6sdc** [comment]
Yes. The connection to the network is implausible. You can not join/leave a motorway at locations other than entrances/exits. 

I am happy to have a route that excludes motorways entirely, both as map matched connections and a route segment, if that prevents this issue. But otherwise I am OK for motorways to be used as part of the route, just so long as the connection occurs at an entrance/exit.

**Comment by SiarheiFedartsou** [comment]
Not sure, but I think you can somehow play with access tags in profile and exclude motorways completely this way https://github.com/Project-OSRM/osrm-backend/blob/b17cbb4c4723d2ecfb3f145734b3a0e1f2089405/profiles/car.lua#L68

**Comment by jcoupey** [comment]
I remember something like this being considered to avoid snapping starting points to a tunnel, which would be very similar. I can't recall if this was happening somewhere in https://github.com/Project-OSRM/osrm-profiles-contrib or the default profiles but probably others could comment here, maybe @frodrigo?

**Comment by tra6sdc** [comment]
Just by altering the origin longitude slightly eastward by 0.001966 degrees (~200m), the driving distance reduces from 11km to 330m. http://map.project-osrm.org/?z=18&center=53.641933%2C-1.529127&loc=53.642224%2C-1.532000&loc=53.641620%2C-1.528497&hl=en&alt=0&srv=0
