### ISSUE TITLE
Difference between Routability and Duration weight setting

### ISSUE THREAD

**Issue by tejavajha** [Project-OSRM/osrm-backend#6440]
Hi,

Raising the visibility on the comment that I've added on commit here: https://github.com/Project-OSRM/osrm-backend/commit/46f96af36096ac29c4df02639125455e0939b702#r88777408

Does anyone have an insight as to how travel_time could be better with Routability setting enabled, when compared with Duration setting. How is Routability setting different from duration or distance setting?

Thanks in advance.

**Comment by SiarheiFedartsou** [comment]
As far as I understand the difference is that “duration” is based only on speeds of road segments, i.e. it finds fastest route from ETA point of view. Routability also penalizes some roads, i.e. it may be not the fastest route from ETA point of view, but you may want to avoid certain roads while driving(e.g. service roads). See PR where it was added https://github.com/Project-OSRM/osrm-backend/pull/3636

also see https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md#understanding-speed-weight-and-rate
