### ISSUE TITLE
Route Modelling

### ISSUE THREAD

**Issue by isaacnti** [Project-OSRM/osrm-backend#6447]
Hello Everyone,
I am working on a project and I want OSRM to use specific route from point A to destination B. Is it possible to model specific route in OSRM? If so how can it be done. If there are sample projects I would be happy to have a look.

**Comment by SiarheiFedartsou** [comment]
What do you mean by “model specific route”?

**Comment by isaacnti** [comment]
@SiarheiFedartsou  What I meant is modelling a specific route and not use the algorithm of OSRM. Example from point A to B, I want the car to use a specific route due to city council regulations.
Question: Is it possible to model a route for the car to use? If so how or will appreciate some pointers.

**Comment by SiarheiFedartsou** [comment]
Stale.
