### ISSUE TITLE
Running osrm-extract on us-latest.osm.pbf

### ISSUE THREAD

**Issue by fitzg2** [Project-OSRM/osrm-backend#6448]
Has anybody tried to run 

> docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /opt/car.lua /data/us-latest.osm.pbf

on http://download.geofabrik.de/north-america/us-latest.osm.pbf ?

It's not generating the OSRM files to run osrm-partition and customize

**Comment by SiarheiFedartsou** [comment]
What do you have as an output of this command? Are you sure you have enough RAM?

**Comment by fitzg2** [comment]
It seems to be exiting correctly. It doesn't output any error. Tried with a GCP e2-standard-16 instance. So 64gb ram 16 cores.

**Comment by SiarheiFedartsou** [comment]
> It seems to be exiting correctly. It doesn't output any error. Tried with a GCP e2-standard-16 instance. So 64gb ram 16 cores.

Could provide output of command?

**Comment by fitzg2** [comment]
@SiarheiFedartsou here's the entire output

https://hastebin.com/raw/ajivivisap

**Comment by SiarheiFedartsou** [comment]
> @SiarheiFedartsou here's the entire output
> 
> https://hastebin.com/raw/ajivivisap

Succesfull `osrm-extract` run is usually finished with smth like:
```
[2022-11-09T16:57:38.626991] [info] RAM: peak bytes used: 596377600
```
What is not a case here. Can you try smaller .osm.pbf? E.g. berlin-latest.osm.pbf from README?

**Comment by williamknn** [comment]
I'm with the same problem, it seems apparently exited with success but the osrm file is not generated. See the output here: https://gist.github.com/williamknn/6e4418b83841ff9b1717b9b09df5f569

AWS m5.8xlarge (128.0 GiB | 32 vCPUs)
Ubuntu 20.04 
libboost1.73
lua5.3

**Comment by SiarheiFedartsou** [comment]
> but the osrm file is not generated

Do you expect file with `.osrm` extension to be generated? We recently got rid of it https://github.com/Project-OSRM/osrm-backend/pull/6354, it is was intermediate artefact of `osrm-extract` which is not actually not needed in other parts of OSRM.

**Comment by williamknn** [comment]
> > but the osrm file is not generated
> 
> Do you expect file with `.osrm` extension to be generated? We recently got rid of it #6354, it is was intermediate artefact of `osrm-extract` which is not actually not needed in other parts of OSRM.

So how do I build the map now? How can I run the contract? Sorry but after this release I don't find anything about this in [wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM).

PS: Using `--dump-nbg-graph` as an argument the file still not being generated.

**Comment by williamknn** [comment]
I think now I understood how this works... I thought that contract uses the .osrm file as input and then changes it but doesn't. The .osrm file generated by the extract is only for debug pourposes and contract uses the entire directory to generate the file. I'm I correct?

I think this needs to be clear in documentation.

**Comment by SiarheiFedartsou** [comment]
@williamknn exactly. I would be happy to approve and merge any PRs improving our documentation :)

**Comment by fitzg2** [comment]
@SiarheiFedartsou how much memory would it take to process https://download.geofabrik.de/north-america/us-latest.osm.pbf ?
would it be better to process special sub regions and serve them under different ports?

**Comment by fitzg2** [comment]
Got it to build on a 256gb ram + 32vcpu droplet for anyone interested. Didn't measure the time.
