### ISSUE TITLE
Multiple profiles (car, foot, bicycle) how to

### ISSUE THREAD

**Issue by rmaziere** [Project-OSRM/osrm-backend#6457]
I would like to know how to have multi profiles routing with OSRM.

I understand that the profile is applied to the raw data during the `osrm-extract` and the files resulting *.osrm.* are all about this profile.

So if I want car, foot and bicycle profiles, I need to have three different directories (for *{car|foot|bicycle}.osrm.*) and three instances of `osrm-routed`.
Is that right ?!

**Comment by morgoth** [comment]
@rmaziere Yes, we also looked for a way to have multiple profiles at once, but didn't find the clean solution.
Would you mind closing the ticket as it's answered?
