### ISSUE TITLE
osrm-extract doesn't generate .edges files when I use foot.lua or bicycle.lua

### ISSUE THREAD

**Issue by menthil** [Project-OSRM/osrm-backend#6460]
Hello,

I have downloaded the Spain's pbf file from Geofabrik. When I run the osrm-extract command:

docker run -t -v $(pwd):/data osrm/osrm-backend:latest osrm-extract -p /opt/walk.lua /data/spain-latest.osm.pbf 

it only creates this files:

```
# ll 
total 3837884
-rw-r--r-- 1 root root 1090227266 Nov 16 18:27 spain-latest.osm.pbf
-rw-r--r-- 1 root root 2830561280 Nov 16 18:34 spain-latest.osrm
-rw-r--r-- 1 root root    9180160 Nov 16 18:34 spain-latest.osrm.names
-rw-r--r-- 1 root root       6144 Nov 16 18:34 spain-latest.osrm.properties
-rw-r--r-- 1 root root       3584 Nov 16 18:27 spain-latest.osrm.timestamp
```

And when I run the osrm-contract command:

```
# docker run -t -v $(pwd):/data osrm/osrm-backend:latest osrm-contract /data/spain-latest.osrm
[warn] Missing/Broken File: /data/spain-latest.osrm.ebg
[warn] Missing/Broken File: /data/spain-latest.osrm.ebg_nodes
```

It doesn't work. When I use the car.lua profile all files are generated without any problem. Is there any problem with bicycle.lua or footer.lua files?

Thank you

**Comment by SiarheiFedartsou** [comment]
I bet osrm-extract doesn’t actually finish correctly - probably due to lack of memory.

**Comment by menthil** [comment]
Yes it was a problem due to lack of memory. I thought that if I can create the car's files the memory wasn't the problem, but I was mistaken. 
Thank you for your help
