### ISSUE TITLE
curl::curl_fetch_memory(utils::URLencode(url) => connection was reset

### ISSUE THREAD

**Issue by fjeuland** [Project-OSRM/osrm-backend#6461]
Hi !

I am a newbie into R and OSRM business...

I have access to a configured osrm-backend server, as https://osrm.mydomain/nearest/v1/driving/13.388860,52.517037?number=3&bearings=0,20 seems to respond correctly :

```
{"code":"Ok","routes":[{"legs":[{"steps":[],"distance":0,"duration":0,"summary":"","weight":0},{"steps":[],"distance":0,"duration":0,"summary":"","weight":0}],"distance":0,"duration":0,"weight_name":"routability","weight":0}],"waypoints":[{"hint":"xIMZgFXtGYAAAAAACQAAAEkCAAB3BAAAAAAAADedJEE9fiJEVOSeRAAAAAAJAAAASQIAAHcEAACNIACAEnp9AO9b6wI8TMwArVghAw8AbwgkchIt","distance":536626.261629,"name":"","location":[8.22325,48.978927]},{"hint":"xIMZgFXtGYAAAAAACQAAAEkCAAB3BAAAAAAAADedJEE9fiJEVOSeRAAAAAAJAAAASQIAAHcEAACNIACAEnp9AO9b6wKCbswA_4ghAw8AbwgkchIt","distance":537795.359385,"name":"","location":[8.22325,48.978927]},{"hint":"xIMZgFXtGYAAAAAACQAAAEkCAAB3BAAAAAAAADedJEE9fiJEVOSeRAAAAAAJAAAASQIAAHcEAACNIACAEnp9AO9b6wJL58wA03AhAw8AbwgkchIt","distance":538774.081837,"name":"","location":[8.22325,48.978927]}]}
```

Then, from rStudio, I passed the following parameters:
```
> options(osrm.server = "https://osrm.mydomain/", osrm.profile = "driving")
> matrix_dist_dur <- osrmTable(src = COM_POINT, dst= grid, measure= "duration")
```

And encountered the error:
```
Error: Error in curl::curl_fetch_memory(utils::URLencode(url), handle = req_handle):
   Send failure: Connection was reset
```

in which direction to explore to resolve this situation?

PS: for information, I try to reproduce the work documented here https://rcarto.gitpages.huma-num.fr/santelocal/

many thanks in advance

**Comment by nilsnolde** [comment]
That's not a OSRM issue, rather one with the [R package](https://github.com/riatelab/osrm). And even more likely an issue with your server as that R package seems pretty well maintained. Seems like hitting the wrong port or so but impossible to tell without you disclosing the actual URL and deployment details.
