### ISSUE TITLE
custom weight

### ISSUE THREAD

**Issue by littlTom** [Project-OSRM/osrm-backend#6462]
I have addde a tag called comfort to the osm.pbf map file. How could i use this tag and duration to customize the road weight? I do not know how to modify the code to make it? Could you help me? Thanks a lot.

**Comment by SiarheiFedartsou** [comment]
It should be as easy as modification of profiles(Lua scripts you have to pass to osrm-extract). See https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md

**Comment by littlTom** [comment]
Thanks for your suggestion! I will have a try today.

**Comment by littlTom** [comment]
> 它应该像修改配置文件一样简单（您必须传递给osrm-extract的Lua脚本）。见 https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md

**Comment by littlTom** [comment]
Thanks for your suggestion! I will have a try today.

**Comment by SiarheiFedartsou** [comment]
What do you mean by device here? Could you elaborate what actually are you doing?

**Comment by littlTom** [comment]
![image](https://user-images.githubusercontent.com/118588293/203004658-03446a31-eb9d-478d-8962-e4657637d95b.png)
I create the osrm-routing machine on ubuntu server,like this picture,and I build a wesite to use OSRM,then I use my phone and PC visit my routing-website at the same time,only my phone can see the routed path,but the browser on PC can't show the routed path when my phone visit my routing website.

**Comment by littlTom** [comment]
![image](https://user-images.githubusercontent.com/118588293/203007827-2ddf5685-62e3-4460-b2d4-9eebab910c40.png)
