### ISSUE TITLE
PBF error: illegal blob size

### ISSUE THREAD

**Issue by GitBenjamin** [Project-OSRM/osrm-backend#6465]
Hi, @mjjbell 
An error occurred  when I ran _osrm-extractor_  to extract my pbf data:
**terminate called after throwing an instance of 'osmium::pbf_error'
  what():  PBF error: illegal blob size**

It has to do with the size of the data that I put in, right?

**Comment by jcoupey** [comment]
This error is probably not related to OSRM at all. You should check that osmium is able to read your pbf outside OSRM, e.g. by running [osmium check-refs](https://docs.osmcode.org/osmium/latest/osmium-check-refs.html).

**Comment by GitBenjamin** [comment]
> osmium check-refs

ok, i will try it, thanks.

**Comment by GitBenjamin** [comment]
resolve
