### ISSUE TITLE
How to merge several countries or continents?

### ISSUE THREAD

**Issue by JohnMartin10000** [Project-OSRM/osrm-backend#6467]
I try to prepare osrm route for few countries (Germany, France and Spain) with MLD algorithm.

I can call osrm-extract, osrm-partition and osrm-customize on each country, but how to merge it for one osrm-routed ?

**Comment by nilsnolde** [comment]
https://docs.osmcode.org/osmium/latest/osmium-merge.html

**Comment by JohnMartin10000** [comment]
OK, but what if I want to process few continents (or full-planet) and processing in one file is too big for osrm-partition.

I just want to process one region then next one, it will allow to call osrm-partition and decrease memory requirements.

**Comment by nilsnolde** [comment]
That won't work. Those regions won't be connected. You **have to** process all areas in one go between which you want connectivity. The FOSSGIS community instance of OSRM processes one continent at a time on 256 GB RAM IIRC. But means you can't go e.g. from Europe to Africa which is of course possible in reality, but on the demo servers.

**Comment by nilsnolde** [comment]
FWIW, there are other alternatives which are a bit more RAM friendly (open-source routing engines in Google), but none as fast as OSRM. So if performance is of essence, this is it.
