### ISSUE TITLE
missing OSM segments from trip service

### ISSUE THREAD

**Issue by grobins** [Project-OSRM/osrm-backend#6469]
I am trying to snap around 28000 GPS traces to the road network and return a count of these GPS trips for each OSM segment.

I'm using a modified car.lua with `result.name = way:id()` to return the osm.id rather than the road name.

But I'm getting results that I can't explain, and I wondered if the community can help.

As the image shows, the count of trips on each segment goes from 27719 to 1465 to 27466 to 2786 to 27314.  There are no other entrances or exits that would explain the traffic drop-off, so for some reason, the trip service is not returning the OSM id for some of the trips but is for others.

I would expect the same result for all trips along this segment.  I am passing in the start and end of the trip, and all the GPS points as waypoints.  Does the returned osm id depend on the number of waypoints?  If I interpolated the trip to have points at every 10m would I expect to get all the segments?

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/4343493/204158987-0ee58d47-be8b-4279-a417-d4b88d2ba794.png">

**Comment by jcoupey** [comment]
Just to make sure: are you using the `match` endpoint to snap your traces? Asking since your message mentions the `trip` service which is not meant for this purpose.

**Comment by SiarheiFedartsou** [comment]
Btw may be node ids instead of way ids will work better for you? They are already available as part of annotations.
