### ISSUE TITLE
[Query] : Is there a way to increase the Max Limit for `excludables` ? Do we have any side effects of increasing it?

### ISSUE THREAD

**Issue by shravan20** [Project-OSRM/osrm-backend#6471]
Is there any way to skip the validation on excludable on seeding? Currently, we have a limit of 8 due to memory issues.

I want to understand if there is a way we can add a different combination of excludables, whose count could be greater than 8.

It would be great if anyone could guide me with this issue. TIA

Below is the snippet I am referring to:

```
    -- classes to support for exclude flags
    excludable = Sequence {
        Set {'toll'},
        Set {'motorway'},
        Set {'ferry'},
        Set {'tunnel'},
        Set {'ferry', 'toll'},
        Set {'ferry', 'motorway'},
        Set {'toll', 'motorway'},
        Set {'toll', 'tunnel'},
        Set {'motorway','tunnel'},
        Set {'ferry', 'toll', 'motorway'}
    },
```

Will change the static value for the validation in `class_data.hpp` help overcoming this issue, i.e., the below snippet?

```
using ClassData = std::uint8_t;
constexpr ClassData INAVLID_CLASS_DATA = std::numeric_limits<ClassData>::max();
static const std::uint8_t MAX_CLASS_INDEX = 8 - 1;
static const std::uint8_t MAX_EXCLUDABLE_CLASSES = 8;
```

Also, do we have any issues/cons of adding more profiles, as I had read in one of the query read "Memory Issues". Could you kindly give glimpse on what exactly do you mean here by the `memory issue`?

**Comment by shravan20** [comment]
Tagging for visibility: @deepaklocus @kartikeyam1

**Comment by SiarheiFedartsou** [comment]
For each excludable class we have to store quite a lot of additional data - i.e. the more classes you add the more potential memory issues you can have. Btw how big is data set you want to work with? If it is quite small(city or small country) it shouldn’t be probably a big issue.
Also I had some ideas recently about how to improve things there https://github.com/Project-OSRM/osrm-backend/issues/6394

**Comment by shravan20** [comment]
@SiarheiFedartsou: Should adding 8 classes be fine? Right now we've added 8 classes, would that cause memory issues?

Also, when you say memory issues, is it while scaling up or is it during that data pre-processing step?

**Comment by shravan20** [comment]
> can you just try and measure memory usage?

Thank you for your prompt reply. Let me check this and get back to you!

**Comment by SiarheiFedartsou** [comment]
Stale.
