### ISSUE TITLE
Debugging routing error (data problem)

### ISSUE THREAD

**Issue by MartenMM** [Project-OSRM/osrm-backend#6472]
I've discovered an unroutable way but do not currently have the knowledge to fix it. The island of Texel, The Netherlands, is not connected to the rest of the country for cars, although there is a ferry service. For modes bike and foot there is no issue. I think connectivity breaks on the bridge from the ferry to mainland, see [here](http://map.project-osrm.org/?z=18&center=53.004676%2C4.780053&loc=53.003906%2C4.780898&loc=53.004884%2C4.779852&hl=en&alt=0&srv=0). I suspect the problem is related to the bridge being tagged as 'oneway=reversible'. 

Am I correct? What would be the right way to fix this?

**Comment by robinhunteler** [comment]
We're having the same problem. We will do a test with an updated lua profile. Will share the results here.

**Comment by SiarheiFedartsou** [comment]
Stale.
