### ISSUE TITLE
Build fails for oneTBB 

### ISSUE THREAD

**Issue by khanziaullah** [Project-OSRM/osrm-backend#6473]
# Issue
The build fails on BeagleboneBlack Rev C.

# Steps to reproduce
Cloned the latest code on the device.
Installed dependencies apt-get packages
Ran into below error:

/root/oneTBB/src/tbbmalloc/frontend.cpp

[ 78%] Building CXX object src/tbbmalloc/CMakeFiles/tbbmalloc.dir/frontend.cpp.o
/root/oneTBB/src/tbbmalloc/frontend.cpp: In function ‘unsigned int rml::internal::getIndexOrObjectSize(unsigned int)’:
/root/oneTBB/src/tbbmalloc/frontend.cpp:829:30: error: there are no arguments to ‘getSmallObjectIndex’ that depend on a template parameter, so a declaration of ‘getSmallObjectIndex’ must be available [-fpermissive]
         unsigned int index = getSmallObjectIndex( size );
                              ^~~~~~~~~~~~~~~~~~~
/root/oneTBB/src/tbbmalloc/frontend.cpp:829:30: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/root/oneTBB/src/tbbmalloc/frontend.cpp: In instantiation of ‘unsigned int rml::internal::getIndexOrObjectSize(unsigned int) [with bool indexRequest = true]’:
/root/oneTBB/src/tbbmalloc/frontend.cpp:869:60:   required from here
/root/oneTBB/src/tbbmalloc/frontend.cpp:829:49: error: ‘getSmallObjectIndex’ was not declared in this scope
         unsigned int index = getSmallObjectIndex( size );
                              ~~~~~~~~~~~~~~~~~~~^~~~~~~~
/root/oneTBB/src/tbbmalloc/frontend.cpp: In instantiation of ‘unsigned int rml::internal::getIndexOrObjectSize(unsigned int) [with bool indexRequest = false]’:
/root/oneTBB/src/tbbmalloc/frontend.cpp:874:61:   required from here
/root/oneTBB/src/tbbmalloc/frontend.cpp:829:49: error: ‘getSmallObjectIndex’ was not declared in this scope
make[2]: *** [src/tbbmalloc/CMakeFiles/tbbmalloc.dir/build.make:89: src/tbbmalloc/CMakeFiles/tbbmalloc.dir/frontend.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: src/tbbmalloc/CMakeFiles/tbbmalloc.dir/all] Error 2
make: *** [Makefile:152: all] Error 2


If you're reporting an issue with https://map.project-osrm.org, please provide a link to the problematic request.

# Specifications

Please provide details of your development environment.
- OS: Linux beaglebone 4.19.94-ti-r73 #1buster SMP PREEMPT Fri Apr 15 21:38:30 UTC 2022 armv7l GNU/Linux
- Beaglebone Black Rev C - ARMv7l/32bit

**Comment by SiarheiFedartsou** [comment]
Would be great to provide exact command you were running. At glance it looks as problem in oneTBB, but not OSRM.

**Comment by khanziaullah** [comment]
I ran the docker build command.
