### ISSUE TITLE
[Query] Facing issue with `excludables` combination

### ISSUE THREAD

**Issue by shravan20** [Project-OSRM/osrm-backend#6483]
I have provided the below set as a combination of allowed excludable:

```
        Set {'toll'},
        Set {'motorway'},
        Set {'ferry'},
        Set {'tunnel'},
        Set {'ferry', 'toll'},
        Set {'ferry', 'motorway'},
        Set {'toll', 'motorway'},
        Set {'motorway','tunnel'}
```
`tunnel` was the latest addition to this set and one of its combinations as well. All of the combinations and tunnel alone are working.

Found a problem in the  `{'motorway','tunnel'}`, which I am not able to figure out. Can you please highlight what am I missing here?

API call throws as it is not supported. Can anyone guide me here?

**Comment by jcoupey** [comment]
This may be related to the fact that the number of excludable classes you can use is limited, see ongoing discussion in #6471.

**Comment by shravan20** [comment]
@jcoupey: But we have only 8 combinations here, would it cause an issue?

**Comment by jcoupey** [comment]
Well, the fact that precisely the eight combination is problematic is suspicious. If you shuffle the order of your combinations, is it always the last one that is causing trouble?

**Comment by shravan20** [comment]
@jcoupey: This doesnt seem to be the issue.

**Comment by SiarheiFedartsou** [comment]
Stale.
