### ISSUE TITLE
Side of road

### ISSUE THREAD

**Issue by JohnMartin10000** [Project-OSRM/osrm-backend#6485]
How I can set side of road for planned route?

I looked for any solution but I only see some mentions about approach=curb, but this is not what I wont, I just have to set left or right side.

**Comment by danpat** [comment]
You need to align a few things:

  1. When you process the data, make sure you use the file in `data/driving_side.geojson` - pass it to `osrm-extract --location-dependent-data data/driving_side.geojson ...` - this will ensure that all edges are properly marked with the correct driving side for each country.
  2. Use `approach=curb` in your requests.
  3. Make sure your input coordinate is set slightly off to the side of the road geometry your destination is actually on.

You said:
> I just have to set left or right side

but this does not make sense - there is no absolute "left" or "right" side of any road, it depends on the direction you are traveling along that road.

Point (3) above may be your main challenge - it will depend where you are getting your destination coordinates from - are you dropping markers on the map, or depending on a geocoding service to perform address-to-coordinate conversion?

**Comment by kabilsharma** [comment]
We are building our own data on top of osrm. dumped geojson and converted with ogr2osm and osmosis to make it osrm friendly. set left_drive true in car.lua added drive_direction = left in database. still when build with osrm it is taking right hand driving. wanted to try location dependent data approach. downloaded india admistrative from overpass. throwing location out of index.  what can i do more? where i could find driving_side.geojson?

**Comment by kabilsharma** [comment]
Thanks Danpat for prompt reply. Yes it was a mistake at my end it was drawing left hand routes just oneway tags in data were yes and no instead of Yes or no ( roundabout a well) .  It worked

**Comment by SiarheiFedartsou** [comment]
Stale.
