### ISSUE TITLE
Retrieve car route information using Curl 

### ISSUE THREAD

**Issue by marcobelli1981** [Project-OSRM/osrm-backend#6489]
Hello, I need to get a route from A to B using Curl to retrieve the points coordinates from json.
The problem is that I don't know how to get the Car route... For example I'm trying to use this url:
http://router.project-osrm.org/route/v1/driving/43.76,11.30;37.95,12.50?steps=true
but it always shows me a route via sea (it should be the result of the bike or foot profile)
So, which is the right curl command to have the car route?
Thank you in advance

**Comment by nilsnolde** [comment]
that could be kinda "undefined behavior" for the OSRM graphs as they're deployed (multiple, non-connected graphs). you sure you didn't mix up lon/lat? it expects the format [lon,lat], not [lat,lon]. 

please use the demo URL, it's much easier for us to reason about: https://map.project-osrm.org.  last but not least, you got a very old URL there, use https://routing.openstreetmap.de/routed-car/route/v1/driving/

**Comment by marcobelli1981** [comment]
Thank you for your answer.
Are you sure that the format is [lon, lat]? because I'm using the [lat,lon] and the start and end points are correctly displayed, I also tried the URL that you suggested but the result is the same. Making others tests I noticed that the retrieved route is totally different from the routes shown in OSM.
Take a look at these pics: the image 1 and 2 show the car and bike route and the last one the created vector using the path coordinates from the json. (I simply extracted all coordinates, put them into an array, and draw a line to connect the points). So...what am I doing wrong?

<img width="1019" alt="bike" src="https://user-images.githubusercontent.com/64930097/209096079-9ca582be-f53d-469e-9dd7-583154e9de4c.png">
<img width="997" alt="car" src="https://user-images.githubusercontent.com/64930097/209096129-511bbc06-97c1-4d6c-a89c-ea3aaeace869.png">
<img width="405" alt="resulted path" src="https://user-images.githubusercontent.com/64930097/209096149-a9058650-1fba-4ce2-834e-fd9c673a0f07.png">

**Comment by marcobelli1981** [comment]
> The bike profile is routing you on the ferry Livorno-Palerno (would have thought foot to do that also)

Ok but this route makes no sense. Why should I go in the hinterland and take the ferry 2 times? How can I retrieve the same coordinates used for the car route shown in the image?

**Comment by datendelphin** [comment]
Of course nilsnolde is sure that the order is lon,lat. The results as well. You are just interpreting the results the wrong way around as well, and as a result, you get a route that does not match the road network. Hint: look at the json you get from the above posted url. You'll see Arabic names. If it was Italy, it would have to be Italian.
Hint 2: You can use the developer tools to see the request made for the above pictures. It's the same server.

**Comment by marcobelli1981** [comment]
Yes...my apologize to Nils, I made the mistake as he supposed. I was
confused because the start and end coordinates were correct. However,
problem solved! Thank you for your support!

Il ven 23 dic 2022, 14:52 datendelphin ***@***.***> ha
scritto:
