### ISSUE TITLE
Core dump problem in using osrm in java

### ISSUE THREAD

**Issue by alinakhaee** [Project-OSRM/osrm-backend#6495]
# Issue

Hello everyone,
I have some issues with running OSRM on a server whose RAM and CPU are 16GB and 16 core respectively.
My Program is written in java and I use JNI to make a connection between C and Java classes.
And I ran into this error from time to time, which results into the program being reset, but after a reset everything works fine for a while.

This is the error:
```
# A fatal error has been detected by the Java Runtime Environment:
--
#
# SIGSEGV (0xb) at pc=0x00007f5a864c2358, pid=6, tid=0x00007f58dcbf8700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C [libosrmBinding.so+0x55358] osrm::engine::plugins::BasePlugin::SnapPhantomNodes(std::vector<std::pair<osrm::engine::PhantomNode, osrm::engine::PhantomNode>, std::allocator<std::pair<osrm::engine::PhantomNode, osrm::engine::PhantomNode> > > const&) const [clone .constprop.0]+0x438
#
# Core dump written. Default location: /opt/core or core.6
#
# An error report file with more information is saved as:
# /opt/hs_err_pid6.log
#
# If you would like to submit a bug report, please visit:
# http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

<br>
I wonder in what circumstances this problem does arise and how it can be fixed.
If anyone has had some related experience I will be thankful for any advise and guidance.

**Comment by DennisOSRM** [comment]
What's the input data?

**Comment by alinakhaee** [comment]
you mean the data for updating the traffic? (because the problems occurs when we want to update it)
it's in the following format: `from_osm_id, to_osm_id, edge_speed_in_km_h, edge_rate`
it may be possible that we put null as edge_rate sometimes. but speed will never be null.
it's a csv like this:
```
50267,27780,32,30.3
34491,34494,3,
50268,27781,32,30.3
```

Actually that's what we think it would be ideally. There may be a flaw in our CSV.
Under what circumstances this problem occurs? So that I can check the data thoroughly to look for a specific type of error.

**Comment by gurjarutkarsh** [comment]
This error message indicates that the Java Runtime Environment (JRE) has detected a segmentation fault (SIGSEGV) in native code, specifically in a function within the libosrmBinding.so library. This means that the issue is not with your Java code itself, but rather with the interaction between the Java Virtual Machine (JVM) and some native code.
There could be a number of reasons why this error occurred, including issues with memory allocation, null pointer exceptions, or other bugs in the native code that the JVM is interacting with.

**Comment by SiarheiFedartsou** [comment]
Stale.
