### ISSUE TITLE
tbb/parallel_pipeline.h: No such file or directory

### ISSUE THREAD

**Issue by TandelJainika** [Project-OSRM/osrm-backend#6497]
Hello everyone,
Currently I am trying to install OSRM routing service on Ubuntu machine. But while running cmake --build . command I am getting the following error.
/osrm/osrm-backend/src/extractor/edge_based_graph_factory.cpp:35:10: fatal error: tbb/parallel_pipeline.h: No such file or directory
   35 | #include <tbb/parallel_pipeline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/EXTRACTOR.dir/build.make:90: CMakeFiles/EXTRACTOR.dir/src/extractor/edge_based_graph_factory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:236: CMakeFiles/EXTRACTOR.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

I have installed the latest version of libtbb library. 
libtbb-dev - 2020.1-2

Try to install OSRM on Ubuntu 20.04
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

**Comment by datendelphin** [comment]
Three possibilities:

- use a newer Ubuntu LTS
- use this patch: https://github.com/Project-OSRM/osrm-backend/pull/6493
- build a newer tbb from source

**Comment by mvl22** [comment]
Just ran into this also.

**Comment by VDU8** [comment]
> Just ran into this also :(
> 
> The patch against the 5.27.1 release does compile fine:
> 
> ```
> wget -O patch-6497-fix-tbbparallelpipeline.patch https://patch-diff.githubusercontent.com/raw/Project-OSRM/osrm-backend/pull/6493.patch
> patch -p1 < patch-6497-fix-tbbparallelpipeline.patch
> ```

Hi thank you for this, I am in build directory after cloning the osrm-backend I created a directory build and in that on performing the commands
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .

I am getting the error posted above, after that I tried using your commands in the same build directory I am getting this error:

![1](https://github.com/Project-OSRM/osrm-backend/assets/61634425/fe0faeba-08bb-4de2-a31c-414cfe29bd63)

I am new to this so help would be appreciated

**Comment by scherbatsky-jr** [comment]
You have to fetch the patch inside the osrm-backend directory and run the patch there.
