### ISSUE TITLE
Build error for Arm cortex 32-bit chipset.

### ISSUE THREAD

**Issue by haozhiming21** [Project-OSRM/osrm-backend#6502]
Hi Dears,

Thanks for reading my quesion. I am trying to build OSRM for a arm cortext M3 chipset but failed. the configure and build setting is following, please help me to check what reason it may be.

### ### Tool chain setting
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_C_COMPILER /usr/local/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER /usr/local/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++)

SET(CMAKE_FIND_ROOT_PATH /usr/local/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-linux-gnueabihf/arm-none-linux-gnueabihf)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

### Configure and build cmd lines
LDFLAGS=-static-libstdc++ cmake -DENABLE_LTO=OFF -DBOOST_ROOT=~/boost-arm/ -DBOOST_INCLUDEDIR=~/boost-arm/ -DBOOST_LIBRARYDIR=~/boost-arm ~/boost-arm/lib/  -DCMAKE_TOOLCHAIN_FILE=/usr/local/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-linux-gnueabihf/arm-gnu-toochain -BOOST_DEBUG=ON -DCMAKE_BUILD_TYPE=Release ..

### Error information:
error:
-- Looking for strtof_l
-- Looking for strtof_l - not found
-- Looking for strtoull_l
-- Looking for strtoull_l - not found
-- Using toolchain file: /usr/local/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-linux-gnueabihf/arm-gnu-toochain.
-- Found Boost: /root/boost-arm/lib/cmake/Boost-1.81.0/BoostConfig.cmake (found suitable version "1.81.0", minimum required is "1.70") found components: date_time chrono filesystem iostreams program_options regex system thread unit_test_framework
-- Could NOT find TBB (missing: TBB_DIR)
CMake Error at cmake/FindTBB.cmake:142 (message):
  Required library TBB not found.
Call Stack (most recent call first):
  cmake/FindTBB.cmake:378 (findpkg_finish)
  CMakeLists.txt:406 (find_package)

Thanks

**Comment by SiarheiFedartsou** [comment]
I guess you will have to build TBB from source. May be using Conan can be an easy way here (-DENABLE_CONAN=ON)

**Comment by danpat** [comment]
I'm also not sure how well OSRM will work on a CPU with 32 bit words - there's a _very_ old ticket about this https://github.com/Project-OSRM/osrm-backend/issues/2502 - and to be honest, I have no idea if the code was all cleaned up.  At a _minimum_, I expect you'd need to generate datafiles on a matching 32bit platform for the datafiles to be compatible.

We have one build in CI (https://github.com/Project-OSRM/osrm-backend/blob/master/.github/workflows/osrm-backend.yml#L255-L266) that compiles the code with `-m32`, so I assume things are _mostly_ working, but 32bit support is not a highly tested thing.

**Comment by haozhiming21** [comment]
> I'm also not sure how well OSRM will work on a CPU with 32 bit words - there's a _very_ old ticket about this #2502 - and to be honest, I have no idea if the code was all cleaned up. At a _minimum_, I expect you'd need to generate datafiles on a matching 32bit platform for the datafiles to be compatible.
> 
> We have one build in CI (https://github.com/Project-OSRM/osrm-backend/blob/master/.github/workflows/osrm-backend.yml#L255-L266) that compiles the code with `-m32`, so I assume things are _mostly_ working, but 32bit support is not a highly tested thing.

Thanks for your replying. I am not sure if all the image have to be built by m32 complier besides osrm_routed image.
