### ISSUE TITLE
OSRM and frigate port 5000 issue

### ISSUE THREAD

**Issue by lukasig** [Project-OSRM/osrm-backend#6504]
Hi

I run nextcloud-AIO in docker and I would like to install osrm-backend for my nextcloud maps, but the issue is that port 5000 is already in use by the frigate docker container.

What are my options?
I do not want to mess with frigate because it is working well.

the commands I tried for installing osrm were:
`wget http://download.geofabrik.de/europe/romania-latest.osm.pbf`
`sudo docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /opt/car.lua /data/romania-latest.osm.pbf`
`sudo docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-partition /data/romania-latest.osrm`
`sudo docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-customize /data/romania-latest.osrm`
`sudo docker run -t -i -p 5000:5000 -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-routed --algorithm mld /data/romania-latest.osrm`

after the last command i get:

> Error starting userland proxy: listen tcp4 0.0.0.0:5000: bind: address already in use

thanks

**Comment by danpat** [comment]
Use the `osrm-routed -p 5001` and change the `-p 5000:5000` to `-p <your preferred external port>:5001`

See `osrm-routed --help` to see other options to customize how `osrm-routed` runs.  Port 5000 is just the default port.

**Comment by lukasig** [comment]
I'm sorry for the potentially annoying question, but could you be a bit more specific?
I am quite a noob to all this.
Where should I use osrm-routed? in my commands instead of osrm-backend?

**Comment by lukasig** [comment]
Thanks for the help and I apologize in advance for the potentially annoying question.

I am a noob, but as far as I understand, my last command should be something like:
 `sudo docker run -t -i -p 6000:5001 -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-routed --algorithm mld /data/romania-latest.osrm`

but where in my commands  should I use `osrm-routed -p 5001`?

thanks again
