### ISSUE TITLE
Why unknown directions return 0 distance

### ISSUE THREAD

**Issue by morgoth** [Project-OSRM/osrm-backend#6506]
I'm having an OSRM server with few countries included only (merged using osmium tool). When I request the path for missing country I get result with 0 distance and 0 duration. This is surprising as I would expect some error response or at least null values.

The request: `curl "my-osrm-server-address/table/v1/driving/18.94201,49.97816;19.04251,49.82155?annotations=distance,duration&destinations=1&exclude=ferry&generate_hints=false&sources=0"`
The response:
```
{"code":"Ok","distances":[[0]],"destinations":[{"distance":196872.930177167,"name":"Anglická alej","location":[16.921101,48.722935]}],"durations":[[0]],"sources":[{"distance":202552.157008644,"name":"Anglická alej","location":[16.921101,48.722935]}]}
```

Those 2 points (placed in Poland) are not present/"compiled" during OSRM data extraction.

Is there any reason for such behavior?
How to best recognize that given response is coming as "missing place" or just some "wrong data"?

**Comment by jcoupey** [comment]
OSRM will snap the points to the nearest available road segment that is included in your data extract. What happens typically when you use points outside your extract is that locations can be "far enough" to be snapped to the exact same location. Thus you get an empty route with a zero distance and duration.

You can restrict how far OSRM will search for a snapping match using the [radiuses parameter](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#requests). If you reduce that value, you'll get an error whenever no snapping is possible.

**Comment by morgoth** [comment]
I can see there is also "snapping" option - I'll play with both.
Thank you, that is very helpful.
