### ISSUE TITLE
osrm-extract failing

### ISSUE THREAD

**Issue by landorg** [Project-OSRM/osrm-backend#6508]
# Issue
After the update from 5.25.0 to 5.27.1 the osrm-extract command fails for unknown reason.
The output I get is:
```
+ osrm-extract -p /opt/bicycle.lua /data/dach-latest.osm.pbf
....
/script/init.sh: line 40:   285 Killed                  osrm-extract -p /opt/bicycle.lua /data/dach-latest.osm.pbf
```
The import for car worked but not for bicycle.
Resource usage seems to be ok. 
(RAM limited to 32GiB with kubernetes but no OOM events and worked in the old version)

Also the import for car was working fine but bicycle is failing.

# Steps to reproduce
```
    wget --no-verbose "http://download.geofabrik.de/europe/dach-latest.osm.pbf"
    osrm-extract -p /opt/bicycle.lua /temp/dach-latest.osm.pbf
```

# Specifications
Running in kubernetes v1.23.8

**Comment by nilsnolde** [comment]
Sounds very much like OOM to me. Can you post what car used on RAM? Bicycle uses slightly more RAM and probably just carried it over the edge. When was the last time you built DACH with 5.25.0 (if it's a while ago, OSM also increased in size, though not that crazy much probably, very well mapped region already)?

**Comment by landorg** [comment]
Hi and thanks for your reply.
It probably was but somehow it's not consistent.
After a couple of hours CrashLoops it suddenly got importet.

**Comment by danpat** [comment]
The `Killed` message is definitely the kernel OOM killer reaping your process.

For `osrm-extract`, thread concurrency matters too, and these could make results inconsistent.  If you get unlucky and many `osrm-extract` threads need memory at the same time, you may hit an OOM condition sometimes, but not others.

I would suggest try being explicit about the thread count - use the `--threads` parameter to `osrm-extract`.  By default it will detect how many CPUs you have available.  Look at logs from past runs to see how many it is detecting, and reduce that amount.  This will make things run slower, but slower and complete is better than never completing at all, right?
