### ISSUE TITLE
bicycle routing on highway=path

### ISSUE THREAD

**Issue by limes11** [Project-OSRM/osrm-backend#6517]
Either it has always been this way or it changed recently, but OSRM does not route bicycles on hw=path in many situations.

Considering that hw=path + foot=designated + bicycle=designated is the **standard tagging** for mixed foot-/cycleways
(see first example here https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath)

this does not make sense. It essentially renders OSRM-bicycle routing entirely useless.

I understand that is a hard to evaluate suitability of a simple hw=path and penalising such a path might be appropriate. 
But with bicycle=designated, no router should ever exclude such a way or assume low speed. OSRM even prefers a hw=footway without bicycle-tag (that mean, bicycle=no) to hw=path + bicycle=designated ???

There are myriads of examples, just take this one:

https://routing.openstreetmap.de/?z=16&center=49.475786%2C10.999364&loc=49.471373%2C11.002582&loc=49.477264%2C11.002765&hl=en&alt=0&srv=1

and compare with foot routing.

What am I missing here?

Thanks for any help

**Comment by datendelphin** [comment]
Maybe a regression from the recent sac_scale fix

**Comment by datendelphin** [comment]
I think I found the error: https://github.com/fossgis-routing-server/cbf-routing-profiles/commit/6bfa8aab9b14e005e4db27711144ba943e9e418f but it will take a few days untli the next new graph making this is visible

**Comment by limes11** [comment]
@datendelphin: Thanks for clarifying this quickly - It's back on track!
