### ISSUE TITLE
Get bool values from osrm::util::json::Object

### ISSUE THREAD

**Issue by aa0d** [Project-OSRM/osrm-backend#6521]
I'm using osrm-backend's `Route` interface in a custom implementation of a routing system. There, I try to extract the information out of the `osrm::utils::json::Object` result, e.g. like this:

```
if (status == osrm::Status::Ok)
{        
    //auto &routes = json_result.values["routes"].get<json::Array>();
    osrm::json::Array &routes = result.values["routes"].get<osrm::json::Array>();

    // Let's just use the first route
    osrm::json::Object &route = routes.values.at(0).get<osrm::json::Object>();
    auto overallDistance = route.values["distance"].get<osrm::json::Number>().value;
```

Extracting `osrm::json::Number` and `osrm::json::String` works fine, however I also want to extract the boolean values that appear for example in the `valid` field. They are created in the engine/api/json_factory.cpp as `osrm::utils::json::True/False` values, but I could not find a way to parse the field and get the `bool` value once again.
When looking into `include/utils/json_container.hpp`, it seems like the method to unwrap the True and False values is not defined:

```
/**
 * Typed floating point number.
 *
 * Unwrap the type via its value member attribute.
 */
struct Number
{
    Number() = default;
    Number(double value_) : value{value_} {}
    double value;
};

/**
 * Typed True.
 */
struct True
{
};

/**
 * Typed False.
 */
struct False
{
};
```
Is there any other way to access the values?

**Comment by danpat** [comment]
Boolean values are stored by _type_, not by value.  If you take a look in `json_renderer.hpp`, you'll see code that looks like this:

https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/json_renderer.hpp#L96-L100

```
template <typename Out> struct Renderer
{
   ...
   void operator()(const True &) { write<>("true"); }

    void operator()(const False &) { write<>("false"); }
   ...
}
```

This is an implementation of the https://en.wikipedia.org/wiki/Visitor_pattern and uses C++ template magic to figure out whether to print `true` or `false` on the output depending on the _type_ of the value stored.

To do a simple lookup of a boolean in the JSON structure, you have to look at the _type_ of the property, not the value, which would look something like.  The `is()`  function on the `mapbox::variant` type can do this:

```c++
  bool result = something["valid"].is<osrm::json::True>();
```
