### ISSUE TITLE
Error: OSRM API request failed [502]

### ISSUE THREAD

**Issue by maariananeves** [Project-OSRM/osrm-backend#6523]
Hello, I created a function with osrmRoute to get the distance and duration of a set of points. I tested it several times to find out as much as it could tell me in this role. The next day, when performing the same function again, it gave the error "Error: OSRM API request failed [502]".
Is there a deadline to apply for points? What would be the maximum number per day without having this problem? How could I resolve this error?

Thank you in advance for any contribution with clarifications.

**Comment by datendelphin** [comment]
The car profile in the Americas region is currently down and needs a graph recalculation. Might take another day until it is up again. Otherwise, see https://routing.openstreetmap.de/about.html for the usage policy.
