### ISSUE TITLE
OSRM gives 502 error with western-hemisphere coordinates

### ISSUE THREAD

**Issue by RobHSmith** [Project-OSRM/osrm-backend#6524]
# Issue

When using coordinates in the western hemisphere in the "nearest" or "routing" service, OSRM gives a 502 Bad Gateway error. This has occurred on different WiFi sources, so the WiFi itself may not be the issue.

# Steps to reproduce
I assume I am using the latest version of osrm-backend as these are requests given directly to the search bar on a web browser. The problem occurs in both Google Chrome and Microsoft Edge.

An example of the issue is in this URL: https://router.project-osrm.org/nearest/v1/driving/-82.8422684000000,34.6730268000000?number=3 

# Specifications
Operating System: Microsoft Windows 10 Home Version 10.0

**Comment by jcoupey** [comment]
See #6523, closing as duplicate.
