### ISSUE TITLE
 OSRM web api service capacity for an open source KNIME  Geospatial Analytics node

### ISSUE THREAD

**Issue by UrbanGISer** [Project-OSRM/osrm-backend#6527]
Hi, thank the OSRM project group, OSRM is such an amazing open-source data service.

We are developing an OSRM-based extension based on the open-source platform KNIME.
The node will highly depend on the web API to finish some OD matrix and route.

I would like to figure out if it is acceptable to get the result purely from the web API, or if the OSRM web service can support the request as the example provided by the OSRM website.

`http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?`

You can check the code here, it is called 
OSRM Matrix
https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/nodes/spatialnetwork.py

This is the icon we design for this node.
https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/icons/icon/Spatialnetwork/OSRMroute.svg

Really appreciate your feedback. We would like to release that next month. If the service capacity does not allow too many requests, we can also consider canceling this node to protect the valuable OSRM sources.

[ Spatial Data Lab](https://github.com/spatial-data-lab/knime-geospatial-extension)
 
Best
Lingbo

**Comment by danpat** [comment]
@datendelphin I think this is a question best answered by you, as the operator of the `router.project-osrm.org` service.

**Comment by datendelphin** [comment]
The usage policy of the current demo server can be found here: http://routing.openstreetmap.de/about.html
So usage should stay below 1/s
Also try to use routing.openstreetmap.de directly, not router.project-osrm.org
