### ISSUE TITLE
Following instructions on readme (docker), but curl returns empty result

### ISSUE THREAD

**Issue by wyzhao** [Project-OSRM/osrm-backend#6528]
Hi, I follow the instructions on the Readme by starting a docker locally, but the following request returns empty result:

curl "http://127.0.0.1:5000/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true"

I am using Mac.

**Comment by danpat** [comment]
@wyzhao Can you try the commands listed on the Docker wiki page:

https://github.com/Project-OSRM/osrm-backend/wiki/Docker-Recipes

those include some error checking to ensure that each step completed successfully.  If you're getting an empty result, then one of the earlier processing steps probably failed.  It is important that you confirm that each step completes properly, and the README doesn't exactly describe how to do that in precise detail.

**Comment by wyzhao** [comment]
It works now.

Thank you.

Daniel Patterson ***@***.***> 于2023年1月26日周四 19:11写道：
