### ISSUE TITLE
osrm-extract failed to extract a large pbf file

### ISSUE THREAD

**Issue by wyzhao** [Project-OSRM/osrm-backend#6533]
# Issue

Try to use docker to extract brazil pbf file (1.5G) but it quits without producing correct files. Previously it succeeded for smaller pbf files (200 MB). I have tried to run with dockers with memory allocation 8G and 16G but the problem remains.

It may be an out of memory issue. But it does not output any error message.

# Steps to reproduce 
Note below "~/osrm/brazil %" is the command prompt.
~/osrm/brazil %wget http://download.geofabrik.de/south-america/brazil-latest.osm.pbf 
~/osrm/brazil %ll                                                                                                                                                                                                   
total 3162376
-rw-r--r--  1 xxxxx  staff   1.5G Jan 30 19:31 brazil-latest.osm.pbf

~/osrm/brazil %docker run -t -v $(pwd):/data osrm/osrm-backend:v5.25.0 osrm-extract -p /opt/car.lua /data/brazil-latest.osm.pbf                                                                                                   
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: brazil-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 4
[info] Parsing in progress..
[info] input file generated by osmium/1.14.0
[info] timestamp: 2023-01-30T21:21:54Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4

Comment: after the last line is printed, the program just hang there for a long time (> 20min) before it exits silently.
 
~/osrm/brazil %ll                                                                                                                                                                                                   17:20:41
total 3162376
-rw-r--r--  1 xxxxx  staff   1.5G Jan 30 19:31 brazil-latest.osm.pbf
-rw-r--r--  1 xxxxx  staff   3.5K Jan 31 15:50 brazil-latest.osrm.timestamp

Comment: only the timestamp file is produced.

# Specifications
Please provide details of your development environment.
- Library/dependency versions: 
    Docker engine: colima version 0.5.2
    git commit: 6b5b6fe0540e708f0c9d6e8919fab292c671fc72
    runtime: docker
    arch: aarch64
    client: v20.10.18
    server: v20.10.11
    
    kubernetes
    Client Version: v1.23.13
    Server Version: v1.25.0+k3s1

- Operating system: MacOS 13.1 (22C65)
- Hardware: Apple M1 Max

**Comment by danpat** [comment]
This is an out of memory issue.

What happens is that Docker simply kills the container when all memory is used up.  OSRM cannot print an error message, as it is being killed by the operating system.

If you open up the macOS `Console` app, you might see entries like this in the Docker logs:

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/1892250/216035768-2809817e-3dcf-4c65-b54a-8c331d7985ce.png">

You can also try wrapping your `docker run` command in a shell, like:

```shell
docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend sh -c "osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf" || "osrm-extract failed"
```

Note the `sh -c "<command>"` in there - the Linux OOM killer usually kills the process that is eating all the memory.  In a Docker environment, if that process is PID 0 in the container (the first process), then the whole container will exit.  If you wrap it with `sh -c`, then the shell is PID 0, and will remain after `osrm-extract` gets killed, and `sh` will probably print a message like `Killed` on the console.

Either way, you need more RAM.

**Comment by wyzhao** [comment]
Thanks. I now allocate 30G to docker and I can see that the extraction is going. But it is really slow. After 8 hours (my laptop may sleep during the time), it reaches:

[info] Writing Turns and Lane Data...
[info] ok, after 3.83815s
[info] Saving edge-based node weights to file.
[info] Done writing. (3.38881)
[info] Computing strictly connected components ...
[info] Found 12803 SCC (7 large, 12796 small)
[info] SCC run took: 4.73303s
[info] Building r-tree ...
[info] Constructing r-tree of 78345616 segments build on-top of 74818674 coordinates
 
and the last message is there for the past hour.
Is there a way to adjust the log to show the timestamp? How long does it need to extract a 1.5G pbf file? I also downloaded and decompressed the .bz2 file, but it only results in one file which cannot be used to launch osrm-routed.

Thanks again!

**Comment by danpat** [comment]
The answer to "how long does it take" is "it depends".

If you computer is using disk-based memory (swap), then it will be veeeeeeery slow - try not to use swap if you can avoid it.  I see in your first ticket you are also only supplying 4 threads - that's not a lot, the process is able to speed things up with more CPUs.

In general, processing routing files is a slow, compute-heavy operation.  If you want it to go fast on bigger maps, you need to give it a hefty machine with lots of real RAM, disabled swap, and as many CPUs as you can find.

**Comment by harshal-gav** [comment]
It looks like the problem could be with the platform compatibility between your host machine and the Docker image you are trying to run. The host machine is running on "linux/arm64/v8" platform and the Docker image "osrm/osrm-backend:v5.25.0" is built for "linux/amd64". Try to find a Docker image compatible with the "linux/arm64/v8" platform or try running the image on a machine with "linux/amd64" platform.

Additionally, it may also be helpful to increase the memory limit for the Docker container to avoid running out of memory during the extraction process.

**Comment by wyzhao** [comment]
Thank you for the answers.

**Comment by diegodario88** [comment]
Hi everyone, I was reading through this thread and noticed that some people were having trouble running OSRM with larger OSM files, such as the 1.5 GB Brazil file. I was wondering if anyone has found a solution to this issue? If so, could you please share your solution or any tips that may be helpful? Thanks in advance for any assistance!

**Comment by danpat** [comment]
@diegodario88 The answer is pretty simple - get more RAM.  If you are using Docker, and you have lots of RAM, make sure Docker is not limiting how much your container can use.

**Comment by warioishere** [comment]
how much ram do you recommend for the europe file which is about 24gigs in size?
I tried with 32GB RAM but it also fails. 

After reading this I am not sure if this is possible at all. 1.6GB File of brazil fails even with 16GB of Ram?
How much RAM does a 24GB files takes then to extract?

**Comment by Nicolas-Lafontaine** [comment]
Hey, as a reference for people who might still be interested in this subject, I've just succeeded in extracting the .pbf file for Canada (5 GB) on my laptop (Windows 11 Home / 32 GB RAM / Default amount of memory allocated to WSL (16 GB in my case) / 10th gen i5 processor with 12 threads).

During the extracting process, the peak RAM usage approached 15 GB.

If you can't add more RAM to your computer and you run Docker on WSL like I do, you might be able to extract larger files by tweaking the .wslconfig file and allocating more RAM to WSL. For reference: https://learn.microsoft.com/en-us/windows/wsl/wsl-config

Here is my console log:

PS C:\osm-maps\osrm-canada> docker run -t -v "/c/osm-maps/osrm-canada:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/canada-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: canada-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 12
[info] Parsing in progress..
[info] input file generated by osmium/1.14.0
[info] timestamp: 2025-02-24T21:20:45Z
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 270.239 seconds
[info] Raw input contains 638969095 nodes, 38137867 ways, and 17035 relations, 69214 restrictions
[info] Collecting way information on 69214 restrictions...ok, after 0.185281s

(........)

[info] Writing edge-based-graph edges       ...
[info] ok, after 13.7617s
[info] Processed 17741483 edges
[info] Expansion: 165582 nodes/sec and 76379 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "/data/canada-latest.osrm"
[info] RAM: peak bytes used: 15377383424
