### ISSUE TITLE
[Date] [error] Input file Data/map-latest not found!

### ISSUE THREAD

**Issue by KaSakee** [Project-OSRM/osrm-backend#6539]
OS: `MacOS Version 13.2`
Laptop: `MacBook Pro, M1 Pro`
NodeJS: `v18.14.0`
Package: `@project-osrm/osrm Version 5.27.1`

I used this command to generate the files

`node_modules/@project-osrm/osrm/lib/binding/osrm-extract Data/map-latest.osm.pbf -p node_modules/@project-osrm/osrm/profiles/car.lua`

Generated everything that said without the original .osrm file which is a breaking change in the osrm new version I guess anyway.

Opinion: "It's very confusing and not handled in the docs."

Got:
`[Date] [info] To prepare the data for routing, run: ./osrm-contract "Data/map-latest"`

I did:
`node_modules/@project-osrm/osrm/lib/binding/osrm-extract "Data/map-latest"`

Got:
`[Date] [error] Input file Data/map-latest not found!`

I might be doing it wrongly, anyone can see anything?

**Comment by danpat** [comment]
It said do `osrm-contract` but you did `osrm-extract`.  Fix the command you called and it should work.

**Comment by KaSakee** [comment]
Thanks man, saved my time, I woke up now, and I missed up hahaha.
