### ISSUE TITLE
Issue in Distance Calculation

### ISSUE THREAD

**Issue by AdhilErattengal-Z** [Project-OSRM/osrm-backend#6542]
Assume  there are 3 locations A,B,C.
when i am calculating dist(A,B),dist(B,C),dist(A,C)
in some cases i am getting dist(A,C)>dist(A,B)+dist(B,C)
any possible reasons for this?why does it not show the shortest path?
i am using osrm web apis

**Comment by nilsnolde** [comment]
Better to give actual examples. The hosted OSRM version is surely not set up to optimize distance, rather cost (which can be very far away from "shortest"). 

Shortest path is the worst misnomer in routing history and it seems to stick unfortunately. Try to think of it as cheapest path, where the cost can be anything you define; it could be distance but it's usually not unless you specifically set it up that way.

**Comment by AdhilErattengal-Z** [comment]
@nilsnolde got it.wanted to know if there is any way i could find cheapest path in terms of distance using OSRM?

**Comment by nilsnolde** [comment]
Jep, I'm not sure exactly where in the lua, but somewhere you can specify what the metric should be, IIRC it's smth like "fastest", "shortest" and "routability" or so. But others can say more or you scan the issues a bit and you'll find it.

**Comment by AdhilErattengal-Z** [comment]
@nilsnolde  wanted to try this change mentioned here https://github.com/Project-OSRM/osrm-backend/issues/5766.how can i create a docker with this change,or do we have it already created?

**Comment by nilsnolde** [comment]
You edit the lua and re-build the graph inside the container, no need for a full docker image unless you wanna make it persistent. You'll find tons of tutorials for that.

It's still worth noting, in rare cases you might still not see what you expect. The reason could be that A->C is _not_ the same as A->B & B->C. A->B might end on a different edge than B->C starts on, which could lead to a minor detour. Not really sure how that's handled in OSRM, I _think_ it's still only expanding from a single edge, not multiple ones and selecting the best path, though I remember a PR by @mjjbell to add support for that, but not sure if that was finished/merged already.

**Comment by AdhilErattengal-Z** [comment]
@nilsnolde i have cloned the project and made changes in the .lua file.
i am new to Osrm and does not know how to proceed further.can you please guide me here.
for my usecase ,i have downloaded india-latest.osm.pbf

**Comment by AdhilErattengal-Z** [comment]
@nilsnolde Also wanted to know if there is any way to test out the weight_name property change online ?

**Comment by nilsnolde** [comment]
https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM

**Comment by AdhilErattengal-Z** [comment]
@nilsnolde  so following these instructions https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM
will be enough?
i tried just the instructions mentioned in the link https://github.com/Project-OSRM/osrm-backend but it didnt seem working

**Comment by nilsnolde** [comment]
It's enough for most people. Also "not working" is nothing anyone can give any advice on.

**Comment by AdhilErattengal-Z** [comment]
@nilsnolde sorry my bad it was working .

-   ~ docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /opt/car.lua /data/india-140101.osm.pbf || echo "osrm-extract failed"

- docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-partition /data/india-140101.osrm ||echo "osrm-partition failed"

- docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-customize /data/india-140101.osrm ||echo "osrm-customize failed"

these are the three commands i ran so that the docker was up and providing results.
i wanted to know what changes i should make in these commands so that the modification in car.lua that i made is working ?
