### ISSUE TITLE
Direction call returns empty result

### ISSUE THREAD

**Issue by wyzhao** [Project-OSRM/osrm-backend#6545]
# Issue
I set up a osrm backend server from docker by following the recipe at for Brazil Sudeste area:
https://github.com/Project-OSRM/osrm-backend/wiki/Docker-Recipes

But when I query it with latlong within the covered area, I got empty result.

# Steps to reproduce

```
%wget https://download.geofabrik.de/south-america/brazil/sudeste-latest.osm.pbf 
%docker run -t -v $(pwd):/data osrm/osrm-backend:v5.25.0 osrm-extract -p /opt/car.lua /data/sudeste-latest.osm.pbf
%docker run -t -v $(pwd):/data osrm/osrm-backend:v5.25.0 osrm-contract  /data/sudeste-latest.osrm || echo "Contract failed"
%docker run -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend:v5.25.0 osrm-routed /data/sudeste-latest.osrm
```

I issued a curl call:
`%curl 'http://localhost:5000/route/v1/driving/-22.914295,-43.248695;-22.917612,-43.246731'           
`

Result is empty.

# Specifications

Please provide details of your development environment.
`
%uname -a                                                                     
Darwin xxxx 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
`
Docker engine:
`
%colima start --arch aarch64 --cpu 8  --disk 100                      
`

**Comment by nilsnolde** [comment]
Good ol’ lat/lon lon/lat confusion innit?🕵️you’ll need to switch to lon/lat format.

**Comment by nilsnolde** [comment]
(Didn’t check the coords though, just guessing considering you’re looking at Brazil, hope I’m not that crazy far off in my geography estimation)

**Comment by wyzhao** [comment]
Thank you for the reply. 
I switched the request to put longitude before latitude, but still I got empty response.
`
curl 'http://localhost:5000/route/v1/driving/-43.248695,-22.914295;-43.246731,-22.917612'
`

**Comment by SiarheiFedartsou** [comment]
What does "result is empty" mean? No result? 200 http code with absolutely empty body? Or what?

**Comment by wyzhao** [comment]
The below is the result of two curl requests. There is no result, not even response code or empty json, after the first command.
`
~ %curl 'http://localhost:5000/route/v1/driving/-43.248695,-22.914295;-43.246731,-22.917612?steps=true'
~ %curl 'http://localhost:5000/route/v1/car/-43.248695,-22.914295;-43.246731,-22.917612?steps=true'
`
I also tried to test with osrm frontend:
`
docker run -p 9966:9966 osrm/osrm-frontend
`
I used a browser to connect to localhost:9966. The map showed nothing except boxes to enter locations. The addresses in the location boxes correspond to the latlong used in the curl tests.
 
<img width="594" alt="Screenshot 2023-02-16 at 5 57 53 AM" src="https://user-images.githubusercontent.com/9028815/219389128-5abb619a-7d45-41ec-945c-f0f72cd070f7.png">


If I selected "openstreets.map" layer, it showed the map.
<img width="523" alt="Screenshot 2023-02-16 at 5 58 56 AM" src="https://user-images.githubusercontent.com/9028815/219389182-2777eddf-1def-45e6-9e48-38097eb1cdcb.png">

The above tests seem to indicate the local osrm server does not contain the map data. However, both "extract" and "contract" commands seem to finish correctly, although both took long time (several hours).

**Comment by wyzhao** [comment]
After I switched to a bigger machine (ubuntu) and reran the extract and contract, I can get results successfully.
I think the problem is either due to memory constraint or Apple M1 cpu. Unfortunately, there is no good error message. 
Thank all who have responded.
