### ISSUE TITLE
how to make the changes made in car.lua live in localhost

### ISSUE THREAD

**Issue by AdhilErattengal-Z** [Project-OSRM/osrm-backend#6548]
I have cloned https://github.com/Project-OSRM/osrm-backend and has made changes in car.lua file by changing weight_name='distance'. how can i  test this change in local?.I am new to OSRM and any  help would be appreciated

**Comment by SiarheiFedartsou** [comment]
Hey if you only need to test changes in Lua profiles you don't even need to compile OSRM or smth like this. 

You can do everything the same as mentioned in README, but just use different folder for Lua profiles:
```
# assuming that car.lua is in current folder
wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /data/car.lua /data/berlin-latest.osm.pbf || echo "osrm-extract failed"
docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-partition /data/berlin-latest.osrm || echo "osrm-partition failed"
docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-customize /data/berlin-latest.osrm || echo "osrm-customize failed"
```

`-v "${PWD}:/data"` in first Docker command mounts current folder to `/data` folder inside container.

**Comment by AdhilErattengal-Z** [comment]
@SiarheiFedartsou just to clear things,suppose if i am not providing the custom .lua file,then how is the above commands fetching .lua file in general case

**Comment by AdhilErattengal-Z** [comment]
@SiarheiFedartsou what i wanted to test was the changes in result with and without the .lua changes.can i host multiple dockers at the same time to cross examine the results.if yes,where all should i make the changes?

**Comment by SiarheiFedartsou** [comment]
> @SiarheiFedartsou just to clear things,suppose if i am not providing the custom .lua file,then how is the above commands fetching .lua file in general case

Those lua profiles are “baked” into Docker image. If you are not familiar with Docker - it could be a good reason to get to know with it. This is a super powerful technology and you will definitely meet it in the fire again.

**Comment by SiarheiFedartsou** [comment]
> @SiarheiFedartsou what i wanted to test was the changes in result with and without the .lua changes.can i host multiple dockers at the same time to cross examine the results.if yes,where all should i make the changes?

Yes, you definitely can. If you want to run 2 osrm-routed instances in parallel you will probably need to assign different ports to them. But I would really recommend to start from some quick overview of Docker and how it works if it is your first experience with it.

**Comment by AdhilErattengal-Z** [comment]
@SiarheiFedartsou just wanted to know.to get shortest path between two points as result ,i should set weight_name='distance' in car.lua file right?

**Comment by AdhilErattengal-Z** [comment]
@SiarheiFedartsou also one more doubt,currently only in route api i can specifically see to what parameter the weight_name is set to.wanted to confirm if the change made in .lua file also reflects in the result whenever i call table api too?
