### ISSUE TITLE
[Error: NoSegment] Response in "@project-osrm/osrm" node package

### ISSUE THREAD

**Issue by erwinschrodinger1** [Project-OSRM/osrm-backend#6555]
# Issue

I am trying to use osrm to find the route between two coordinates. I have (https://medium.com/logistimo-engineering-blog/osrm-data-generation-and-deployment-2f5a66269342) followed this blog to create the osrm file of Berlin. I have downloaded osm.pbf file from geo-fabfric (https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf).

![image](https://user-images.githubusercontent.com/81609547/221526766-6ca20577-43f1-4868-9f1a-0913368f0b44.png)

![image](https://user-images.githubusercontent.com/81609547/221526875-409c21c9-b4ad-456d-9b56-98375c59ef1f.png)

![image](https://user-images.githubusercontent.com/81609547/221526948-a6a5c13c-f573-4d50-911b-5eaf531d8596.png)

The node code snippet looks like this:
![image](https://user-images.githubusercontent.com/81609547/221527074-6bc96e40-0135-4a31-9ae1-ce816d230e18.png)

And the response is 
[Error: NoSegment]

# Steps to reproduce

# Specifications

Please provide details of your development environment.
- Libraries related to osm:
-  "@project-osrm/osrm": "^5.27.1",
    "@turf/turf": "^6.5.0",
    "@types/project-osrm__osrm": "^5.27.0",

Node version: v16.16.0

**Comment by SiarheiFedartsou** [comment]
This error may mean that OSRM cannot find road graph data for region you query route for. 

As I can see here you run osrm-contract for nepal-latest.osrm https://user-images.githubusercontent.com/81609547/221526875-409c21c9-b4ad-456d-9b56-98375c59ef1f.png

Also you didn't provide how you initialize OSRM in NodeJs - would be great to see it to understand what is your problem.

**Comment by erwinschrodinger1** [comment]
![image](https://user-images.githubusercontent.com/81609547/221748636-c4ae901b-dd09-492c-8551-14b15ceda164.png)
This is how I have initialized in node.

To avoid the missing road of Nepal. I tried doing it for Berlin. Still the Same problem.

**Comment by SiarheiFedartsou** [comment]
First of all I think that you should pass path not to .osm.pbf, but to .osrm(see extension in pathS variable in your code) and also please check that it points to proper folder and it actually exists(but tbh we should throw exception if it is indeed the reason of problem)

**Comment by erwinschrodinger1** [comment]
I tried using .osrm too. And talking about the path I have verified it and it is the same exact path.

**Comment by erwinschrodinger1** [comment]
Anyone who can provide me example code that will work with node express ts ?

**Comment by SiarheiFedartsou** [comment]
May I ask you to provide exact steps of what you are actually doing in order to preprocess OSM data? And minimum example of Node application which doesn't work for you? It would nice to provide it not as screenshots, but as text in order to allow other people to also run it.

**Comment by erwinschrodinger1** [comment]
[https://github.com/erwinschrodinger1/osrm-example-node.git](https://github.com/erwinschrodinger1/osrm-example-node.git)

I have included the commands used and git repository. Can someone please have a look?

**Comment by SiarheiFedartsou** [comment]
I would recommend to check first if steps from README work for you https://github.com/Project-OSRM/osrm-backend#using-docker

Also you don’t need to run osrm-routed if you want to use generated data from Node - osrm-routed is just a demo server(I.e. you can just omit this step), BUT you can use it to verify that everything went well (in your case you can run osrm-extract/osrm-contract/osrm-routed and then check with curl that it returns correct response - see README)

And finally I see that you probably use Windows, support for Node bindings in Windows was added only recently and I can imagine that it contains bugs - probably you can try to pack your Node app into Linux-based Docker container and check if it works under Linux.

**Comment by erwinschrodinger1** [comment]
I found the problem. The problem was with the windows. While I tried the same thing in Linux it is working perfectly fine for me. For example you can refer to my git repo I would be pushing the example codes there. Thank you @SiarheiFedartsou  for your help !!

**Comment by SiarheiFedartsou** [comment]
Actually the fact that it doesn’t work properly on Windows is also problem 🤔

**Comment by erwinschrodinger1** [comment]
Can you leave the guide or bugs that should be solved to make it work on windows? I would be really interested to contribute in this project.
