### ISSUE TITLE
Deleting/ changing prefered route in OSRM (waterway)

### ISSUE THREAD

**Issue by NathanNguyen-Dev** [Project-OSRM/osrm-backend#6556]
Greetings, I am trying to make a routing calculation but for some business reason, the path that is taken while calling OSRM is not the preferred path. Is there a way to configure OSRM to delete a specific pathway, or changes it to an alternative route?

For example in this picture, I would like OSRM to always take the path below (which goes through Iloilo -> Bacaloid -> Cebu) and avoid having to go round trip (moving north and going to Boco(Cebu))
![image](https://user-images.githubusercontent.com/81554819/221740967-9fdacaca-5d20-4ae9-beb8-2e40b2f9414e.png)

**Comment by aa0d** [comment]
If I understand you correctly, you don't want the route to be using the ferry in the north from Bogo to Botongon. To alternate OSRM's behavior for specific highway/highway types you can build a custom version of car.lua. There you can for example disable the use of ferries or set a certain speed for a specific way. For more information refer to:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md

**Comment by NathanNguyen-Dev** [comment]
Thank you for the suggestion, I found a more straightforward way to make edit locally the .osm.pbf file by deleting the unwanted waterway and merging it back using osmium.
