### ISSUE TITLE
Mac CI requires higher Conan version

### ISSUE THREAD

**Issue by nilsnolde** [Project-OSRM/osrm-backend#6557]
GA is failing on Mac, e.g. https://github.com/Project-OSRM/osrm-backend/actions/runs/4233847758/jobs/7355363078.

Seems some recipe requires a higher version.

@SiarheiFedartsou should we make this a GSoC issue?

**Comment by SiarheiFedartsou** [comment]
Hey, not sure tbh - at glance it seems to be too easy to fix(it seems we just need to bump Conan version) and too boring for someone who wants to participate in GSoC(I assume people don't usually like to dig into such things) :) 

I will try to look into it in the nearest days.
