### ISSUE TITLE
GSoC 2023 announcement

### ISSUE THREAD

**Issue by nilsnolde** [Project-OSRM/osrm-backend#6558]
The project will be: officially supported OSRM Python bindings. See more here: https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2023/Project_ideas.

To regulate applications, please read the following wiki entry carefully, if you want to be considered:
https://github.com/gis-ops/valhalla-app/issues/67

**Comment by SiarheiFedartsou** [comment]
@nilsnolde sure, done 👍

**Comment by Zebreu** [comment]
Did anything happen here by the way?

I wrote python bindings as part of https://github.com/datakind/dk-routing/tree/main/dkroutingtool (you can build the docker image and interface directly with the table, nearest, and route C++ functions from the osrmbindings python library)

I can help anyone who wants to bring that out as an easily distributable library. I used pybind11 and it was straightforward enough. I'm about to make some changes for performance reasons so I'd be more than happy to work it into something more general and fast.

**Comment by nilsnolde** [comment]
Right, sorry for not giving any updates here. The project was very successful thanks to @whytro and the bindings are here: https://github.com/gis-ops/py-osrm (might still change to OSRM namespace). I've been super busy before going on a longer vacation (where I am currently), I didn't have any time yet to set up PyPI distribution workflows. Will still take a few weeks, but it'll surely still happen in 2023:)

Thanks for sharing your project. I didn't look into it too much, but seems like you're just exposing the table endpoint right? Would be cool if you could try our library once it's published (or feel free now), we'll want some people using and testing it:)

**Comment by Zebreu** [comment]
I'm exposing nearest, table and route and returns json, so I'll take a look at py-osrm and see if there are performance differences. Something I wanted to do was to have multiple route geometry results in a single request and potentially share memory objects (like numpy maybe?) to avoid parsing parameters and JSON every route, but if py-osrm is considerably faster I may be able to avoid that. Thanks!
