### ISSUE TITLE
Reason for rounding in vector tiles?

### ISSUE THREAD

**Issue by mattwigway** [Project-OSRM/osrm-backend#6561]
Speed and rate are [both rounded to one decimal place](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/plugins/tile.cpp#L499) in vector tiles. Particularly for rate this is causing me an issue, since the rates internally are represented in weight units per decisecond, so everything is rounding to the same value, because the walking rates I'm using range from 0.75 - 1.35 meter-equivalents per second, which all round to a rate of 0.1.

The tiles still present the results as floating-point values, so I'm not sure this rounding is saving any network bandwidth. What's the reason for rounding these values on the back-end, rather than allowing frontend viewers to round them as needed?

**Comment by SiarheiFedartsou** [comment]
I think there is no specific reason - probably when someone was writing this code he/she decided that 1 kmph precision is enough for visualization. I think you can just change it - doesn't seem to be difficult to do.
