### ISSUE TITLE
No line numbers in Lua runtime errors

### ISSUE THREAD

**Issue by mattwigway** [Project-OSRM/osrm-backend#6563]
# Feature

When a runtime error occurs in a Lua profile script, OSRM exits with a message that says what the error was, but not a traceback or a line number, e.g.

```
$ osrm-extract -p ../profiles/bicycle_lts.lua bicycle_lts/bicycle_lts.osm.pbf
[lots of intermediate output]
libc++abi: terminating with uncaught exception of type sol::error: lua: error: attempt to compare two nil values
```

It would make debugging profiles much easier if there were a traceback and line number. I have a patch for this, will submit PR shortly.

This is related to #3084, but I think it's not a duplicate as the discussion there focuses on syntax errors, which in the latest OSRM already display line numbers.

**Comment by SiarheiFedartsou** [comment]
Hey @mattwigway 
I think it is really nice idea :+1:, let me please know if I can help you somehow with your PR.

**Comment by mattwigway** [comment]
Thanks! If you have any thoughts on the second and third checklist items in #6564 that would be great, or about how to write a unit test - it seems like the tests that exist mostly check the output of a running server, rather than checking that a server crashes.
