### ISSUE TITLE
Disable ferry routes for all requests

### ISSUE THREAD

**Issue by wiim00** [Project-OSRM/osrm-backend#6571]
Hello,

my team and I are using OSRM in combiniation with VROOM to calcuate trips for public transport.

We are running into an issue where the calculated route contains a trip with the ferry, which is not applicable for us.
So we thought about disabling the ferry, which I tried with the attached profile.
In the `avoid` set I've added `ferry` so I assume no node with type `ferry` will be considered.
The `excluded=ferry` query param is not feasable for us because we don't want to fork VROOM (as the request params are hard-coded)

Making a request to the backend without the `excluded=ferry` query param results in this route:
[osrm_result_with_ferry.json.txt](https://github.com/Project-OSRM/osrm-backend/files/10931333/osrm_result_with_ferry.json.txt)
This result is not what we want as it takes the Ferry "Fähre Aken"

And excluding the ferry via URL results in the correct route:
[osrm_result_without_ferry.json.txt](https://github.com/Project-OSRM/osrm-backend/files/10931339/osrm_result_without_ferry.json.txt)
This result does not contain the Ferry "Fähre Aken" and drives with just a car.

This is the ferry we don't want:
![image](https://user-images.githubusercontent.com/43516739/224022957-c25e206c-c3ec-49fb-bbaf-4091247765f9.png)

Am I doing something wrong in the profile? Is there even a way to "globally" disable the ferry or is the only solution to modfiy VROOM to exclude the ferry?

Thanks in advance! :)

FYI:
- http://localhost:5000/route/v1/driving/12.040672,51.850943;12.084961,51.955903?overview=false&alternatives=true&steps=true(&excluded=ferry) is the request we are trying to find the correct route on

[car.lua.txt](https://github.com/Project-OSRM/osrm-backend/files/10931581/car.lua.txt)

**Comment by fbaierl** [comment]
Additionally, we noticed that we can only slow down a ferry up to a certain point by using:

```
route_speeds = {
   ferry = 0.01
}
```

Ideally, we would want to make the ferry route even slower (e.g. 0.0001), but that does not seem to have any further effect. Is there a reason for this?

**Comment by cyril23** [comment]
For excluding you Query param needs to be `exclude` instead of `excluded`, according to https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#requests
