### ISSUE TITLE
OSRM node binding not working in Ubuntu V.20.04

### ISSUE THREAD

**Issue by erwinschrodinger1** [Project-OSRM/osrm-backend#6573]
While using this projects' node binding. I am getting the following error.
![image](https://user-images.githubusercontent.com/81609547/225884957-cb4f7614-4848-485f-ae65-0e3f8df3181e.png)
The same piece of thing works on Ubuntu V.22

**Comment by danpat** [comment]
The error is right there - it says `Permission denied`.  Have you looked at the file permissions of the files you're pointing OSRM to?

**Comment by erwinschrodinger1** [comment]
![image](https://user-images.githubusercontent.com/81609547/225945944-84e628e9-53ac-4219-ac2e-5166550f3fd2.png)
These are the permissions of the osrm file data, all seems okay. I guess.

**Comment by danpat** [comment]
The file `nepal-latest.osrm.fileIndex` is only readable by the `root` user - are you running your nodeJS code as `root`?

I don't think this is an OSRM issue at all.  Here's a link to a tutorial for understanding how Unix file permissions work:

https://mason.gmu.edu/~montecin/UNIXpermiss.htm

**Comment by erwinschrodinger1** [comment]
Thank you for help @danpat . The problem was with fileIndex being available only to root user as @danpat mentioned. 

For beginner developer like me. The solution is to change the file permission to your desired permission. In my case I did it for all users by using chmod command.

```sudo chmod 755 nepal-latest.osrm.fileIndex```
