### ISSUE TITLE
Route Service Output Issue: Polyline and GeoJSON Coordinates not on the Road

### ISSUE THREAD

**Issue by LML-1900** [Project-OSRM/osrm-backend#6583]
Hi, I am new to OSRM and I am trying to obtain the coordinates along a route in GeoJSON format using the "geometry" parameter. I attempted to decode the polyline returned by the route service with the Interactive Polyline Encoder Utility provided by Google Maps Platform (as shown in Figure 1).As you can see, the line wasn't on the road at all. Initially, I thought that the issue was with Google Maps. However,  when I marked these coordinates on the map, I found that they were completely off the road, and they corresponded one-to-one with the points on the polyline previously resolved using Google Maps. (as shown in Figure 2). I also tried the demo server and it plotted the route correctly(as shown in Figure 3).
I am unsure if the issue is with the tools I am using or if I am not using the service correctly. Could you please help me identify the problem? Here are the HTTP requests that I used: 
**Polyline**: curl 'https://router.project-osrm.org/route/v1/driving/113.552005,22.216329;113.547819,22.222420?geometries=polyline'
**Geojson**: curl 'https://router.project-osrm.org/route/v1/driving/113.552005,22.216329;113.547819,22.222420?geometries=geojson'
**response**:
`{
    "code": "Ok",
    "routes": [
        {
            "geometry": {
                "coordinates": [
                    [
                        113.550893,
                        22.216442
                    ],
                    [
                        113.550947,
                        22.216902
                    ],
                    [
                        113.550972,
                        22.216992
                    ],
                    [
                        113.551016,
                        22.217051
                    ],
                    [
                        113.551062,
                        22.217094
                    ],
                    [
                        113.551139,
                        22.217143
                    ],
                    [
                        113.551251,
                        22.217197
                    ],
                    [
                        113.55142,
                        22.21727
                    ],
                    [
                        113.551624,
                        22.217366
                    ],
                    [
                        113.551809,
                        22.217462
                    ],
                    [
                        113.551893,
                        22.217509
                    ],
                    [
                        113.552011,
                        22.217604
                    ],
                    [
                        113.552056,
                        22.217664
                    ],
                    [
                        113.552049,
                        22.21775
                    ],
                    [
                        113.552042,
                        22.217856
                    ],
                    [
                        113.55232,
                        22.21834
                    ],
                    [
                        113.552514,
                        22.218681
                    ],
                    [
                        113.553002,
                        22.219538
                    ],
                    [
                        113.553154,
                        22.219804
                    ],
                    [
                        113.553187,
                        22.219866
                    ],
                    [
                        113.553207,
                        22.219924
                    ],
                    [
                        113.553211,
                        22.219951
                    ],
                    [
                        113.553214,
                        22.220002
                    ],
                    [
                        113.553202,
                        22.220137
                    ],
                    [
                        113.553232,
                        22.220206
                    ],
                    [
                        113.553265,
                        22.220264
                    ],
                    [
                        113.553458,
                        22.220582
                    ],
                    [
                        113.553509,
                        22.220698
                    ],
                    [
                        113.553512,
                        22.220807
                    ],
                    [
                        113.554354,
                        22.222259
                    ],
                    [
                        113.554275,
                        22.222295
                    ],
                    [
                        113.553591,
                        22.221096
                    ],
                    [
                        113.553349,
                        22.220671
                    ],
                    [
                        113.553295,
                        22.22061
                    ],
                    [
                        113.553233,
                        22.220553
                    ],
                    [
                        113.553166,
                        22.220493
                    ],
                    [
                        113.553082,
                        22.220434
                    ],
                    [
                        113.553002,
                        22.22038
                    ],
                    [
                        113.552869,
                        22.220368
                    ],
                    [
                        113.55283,
                        22.220365
                    ],
                    [
                        113.552771,
                        22.220357
                    ],
                    [
                        113.552707,
                        22.220348
                    ],
                    [
                        113.552625,
                        22.220338
                    ],
                    [
                        113.55164,
                        22.220194
                    ],
                    [
                        113.551412,
                        22.220172
                    ],
                    [
                        113.551367,
                        22.220234
                    ],
                    [
                        113.551371,
                        22.220268
                    ],
                    [
                        113.551378,
                        22.220302
                    ],
                    [
                        113.551385,
                        22.220331
                    ],
                    [
                        113.5514,
                        22.220369
                    ],
                    [
                        113.551416,
                        22.220402
                    ],
                    [
                        113.551509,
                        22.220582
                    ],
                    [
                        113.5516,
                        22.220762
                    ],
                    [
                        113.551718,
                        22.220996
                    ],
                    [
                        113.551808,
                        22.221254
                    ],
                    [
                        113.551916,
                        22.221455
                    ],
                    [
                        113.551951,
                        22.221523
                    ],
                    [
                        113.552012,
                        22.221635
                    ],
                    [
                        113.55203,
                        22.221678
                    ],
                    [
                        113.552259,
                        22.2222
                    ],
                    [
                        113.552495,
                        22.222733
                    ],
                    [
                        113.552534,
                        22.222836
                    ],
                    [
                        113.552574,
                        22.222932
                    ],
                    [
                        113.552366,
                        22.222986
                    ],
                    [
                        113.55221,
                        22.223007
                    ],
                    [
                        113.551664,
                        22.22308
                    ],
                    [
                        113.550907,
                        22.223181
                    ],
                    [
                        113.550515,
                        22.22314
                    ],
                    [
                        113.549852,
                        22.223069
                    ],
                    [
                        113.549248,
                        22.223005
                    ],
                    [
                        113.54921,
                        22.223001
                    ],
                    [
                        113.549178,
                        22.222997
                    ],
                    [
                        113.549133,
                        22.222992
                    ],
                    [
                        113.548519,
                        22.222927
                    ],
                    [
                        113.548364,
                        22.22291
                    ],
                    [
                        113.548203,
                        22.222886
                    ],
                    [
                        113.548058,
                        22.222867
                    ],
                    [
                        113.547794,
                        22.222829
                    ],
                    [
                        113.547758,
                        22.222824
                    ]
                ],
                "type": "LineString"
            },
            "legs": [
                {
                    "steps": [],
                    "summary": "",
                    "weight": 271.3,
                    "duration": 271.3,
                    "distance": 2026.5
                }
            ],
            "weight_name": "routability",
            "weight": 271.3,
            "duration": 271.3,
            "distance": 2026.5
        }
    ],
    "waypoints": [
        {
            "hint": "utCpipkm-Y17AAAA0gAAABkAAAAAAAAAc_ZMQt3nrkLUsyRBAAAAAHsAAADSAAAAGQAAAAAAAAC8-QAALabEBvr-UgGFqsQGif5SAQEArwuGF9Uq",
            "distance": 115.326321461,
            "name": "",
            "location": [
                113.550893,
                22.216442
            ]
        },
        {
            "hint": "PEJ9g7Rz3IkCAAAAMgAAABwAAAAAAAAA0ypwQCm7lkJBjSpCAAAAAAIAAAAyAAAAHAAAAAAAAAC8-QAA7pnEBugXUwErmsQGVBZTAQIAbxCGF9Uq",
            "distance": 45.176152173,
            "name": "侨光路",
            "location": [
                113.547758,
                22.222824
            ]
        }
    ]
}`
![image](https://user-images.githubusercontent.com/97895208/228516038-03a9952e-0bd0-4ed9-bf10-cf5d45e9b92d.png)
![image](https://user-images.githubusercontent.com/97895208/228515678-0904178c-c886-449c-9f23-bcecc5ba0a9c.png)
![image](https://user-images.githubusercontent.com/97895208/228519875-0dd8ca25-9bef-496e-a19e-375d1455199d.png)

**Comment by danpat** [comment]
If you plot your geometry over an WGS-84 visual map (like the one found at geojson.io), the alignment of the coordinates is good:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/1892250/228609374-55dabeab-0cf3-41e7-95a9-71901d9f1cbb.png">

The problem you're having is because you're drawing the geometry over the top of a Google Maps map - I suspect in your location, you are being given a map by Google that is warped according to GCJ-02 - see https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#GCJ-02

There are really just two possible fixes:

  1. Render the route returned by the `router.project-osrm.org` service on a non-GCJ-02 basemap.
  2. Adjust the coordinates you get from `router.project-osrm.org` to match the GCJ-02 projection so they align with the basemap you're using from Google.

Working with map data within China requires an understanding of the rules/laws of working with geographic data in that locale.  The results you are receiving from the `router.project-osrm.org` are coming from outside of China from a WSG-84 datum map data source.  It will not look correct if rendered on top of a GCJ-02 basemap.

**Comment by LML-1900** [comment]
@danpat Thank you very much! Your response has really helped me out.

However, I noticed that the start and end points in the route plotted by geojson.io are not the ones I intended to ask about. I suspect this is because I obtained the coordinates for the start and end points on a GCJ-02 basemap, and then the WGS-84 visual map caused a shift. Therefore, l want to know if there is any WSG-84 basemap allow me to mark a point on the map and return the corresponding latitude and longitude coordinates, as well as support me to input latitude and longitude coordinates and display the position on the map? (like Google Maps shown below)

![image](https://user-images.githubusercontent.com/97895208/228766973-ed30065a-e5ed-481d-9921-19fae2bec8ed.png)

Additionally, I’d like to ask about the distance between coordinates returned by geometry when `overview=full`. Based on my observations, the points are more densely distributed at turning points and sparser on straight segments. Is there any way to obtain the distance between each point?

**Comment by danpat** [comment]
The tool https://geojson.io/ is all WSG-84, regardless of where it is accessed from.  You both draw on the map and manipulate the GeoJSON text on the right-hand side of the screen to render geometry.

As for the distance between points - you will have to do some math.  In Javascript, the TurfJS library is commonly used for geographic measurement - see https://turfjs.org/docs/#distance for the distance between two points.  There are other geographic functions available in that library as well.

The distance between points comes from the raw map data - OpenStreetMap.  Each OSM "node" is returned as a point, and ultimately, humans draw these points, so there is no strict rule as to how dense they will be.  Some people draw curved roads with few points, other people draw many points.

**Comment by LML-1900** [comment]
@danpat You mentioned that the density of points comes from the OSM "node". Can I assume that the `coordinates` in `geometry` correspond one-to-one with the `nodes` in `annotation`? I noticed that there is also a distance array in the annotation object which describes the distance between each pair of nodes.

**Comment by danpat** [comment]
@LML-1900 Yes, that is correct, `annotations=distances` will give you the coordinate-to-coordinate distances along the route..

**Comment by LML-1900** [comment]
@danpat Thank you so much!!!
