### ISSUE TITLE
is it possible to avoid destination snap to motorway?

### ISSUE THREAD

**Issue by aibear-huang** [Project-OSRM/osrm-backend#6591]
i know WayHandlers.startpoint can avoid start point start on this way where routing.
but i also want to avoid some highway as the destination when snapping in the routing.
is it possible to avoid destination snap to some assigned highway (only change the profile) when routing? 
thank you~

**Comment by SiarheiFedartsou** [comment]
Hey @aibear-huang 
as far as I can judge by code `is_startpoint` should impact both origin and destination (and any waypoints in the middle). It seems our docs a bit confusing 🤔

**Comment by SiarheiFedartsou** [comment]
> > Hey @aibear-huang as far as I can judge by code `is_startpoint` should impact both origin and destination (and any waypoints in the middle). It seems our docs are a bit confusing 🤔
> 
> thanks for your reply, great~

But please take my words above with a grain of salt - I would recommend you to check it in practice(code is quite straightforward + I see some notes in some of our docs that it should impact both origin and destination, but probably I missed something).

**Comment by aibear-huang** [comment]
> > > Hey @aibear-huang as far as I can judge by code `is_startpoint` should impact both origin and destination (and any waypoints in the middle). It seems our docs are a bit confusing 🤔
> > 
> > 
> > thanks for your reply, great~
> 
> But please take my words above with a grain of salt - I would recommend you to check it in practice(code is quite straightforward though + I see some notes in some of our docs that it should impact both origin and destination, but probably I missed something).

yes, i checked it, it works when i set is_startpoint=false for both origin and destination. thanks for your remind.

**Comment by SiarheiFedartsou** [comment]
Thanks for confirmation, I am closing it :+1:
