### ISSUE TITLE
Server slow or down https://routing.openstreetmap.de/

### ISSUE THREAD

**Issue by Koxx3** [Project-OSRM/osrm-backend#6595]
Hello,
the demo server often return error 502 of has very slow answer, especially on bike routing.

Example:
https://routing.openstreetmap.de/routed-bike/route/v1/driving/2.334595,48.840769;2.365494,48.866522?overview=false&alternatives=true&steps=true

Regards !
Francois

**Comment by nilsnolde** [comment]
Thanks for the feedback. Is it still persisting?

Also a good reminder to not rely on free services which are meant as project demos:)

**Comment by Koxx3** [comment]
hello, seems much better now 😉
