### ISSUE TITLE
Discord link does not work

### ISSUE THREAD

**Issue by ntzm** [Project-OSRM/osrm-backend#6604]
![image](https://user-images.githubusercontent.com/3888578/232480369-dc244635-3fe8-4c9f-9aac-255bcd7b4c2a.png)

I think there is a way of creating an invite link that does not expire :)

**Comment by SiarheiFedartsou** [comment]
Hey, can you please try again? I set this link to never expire in Discord settings - should work now.

<img width="675" alt="Screenshot 2023-04-21 at 17 05 02" src="https://user-images.githubusercontent.com/266271/233670146-f600d324-afc2-447f-8f71-6cd175f4c9fe.png">

**Comment by ntzm** [comment]
Apologies, I needed to reauthenticate but discord UI doesn't make that clear
