### ISSUE TITLE
New repo for Python bindings

### ISSUE THREAD

**Issue by nilsnolde** [Project-OSRM/osrm-backend#6610]
Hi @DennisOSRM ,

we're about to start the GSoC project to publish proper Python bindings for OSRM. They'd ideally be hosted under the Project-OSRM namespace for some level of authenticity:) @SiarheiFedartsou and me are mentoring.

Are you ok with adding a repo there? The name is still a bit unclear, so no need for action yet. PyPI has already tons of OSRM packages. Since we already have a few others for similar projects and they all follow a pattern, I'd like to have OSRM following the same, i.e. calling it `pyosrm`. Which is of course taken.. I asked the author if he'd be ok yanking his project from PyPI: https://github.com/enricodvn/pyosrm/issues/8

**Comment by DennisOSRM** [comment]
Sounds excellent! Thumbs up from my side.

**Comment by DennisOSRM** [comment]
Do you want to transfer the repo over to the OSRM org?

**Comment by nilsnolde** [comment]
Jep, that’d be ideal I think, for visibility/credibility etc. At least if we can admin rights there, that’d be important. WDYT?

**Comment by DennisOSRM** [comment]
Sounds good to me.

**Comment by nilsnolde** [comment]
@DennisOSRM do you have time to look into this soon-ish? We're in the last week of GSoC now and it'd be cool to move to the official repo for the evaluation.

**Comment by nilsnolde** [comment]
To host it on PyPI, should we create a OSRM account there? How is npm handled? Is there already a shared email address we can use for this? Cc @SiarheiFedartsou
