### ISSUE TITLE
Sending 168 locations to map match results in {"message":"Too many trace coordinates","code":"TooBig"}

### ISSUE THREAD

**Issue by afarber** [Project-OSRM/osrm-backend#6612]
# Issue

Hello and thank you for working at this wonderful project! 

I have installed the latest osrm/osrm-backend docker image, but the issue I am describing below is also present at the https://router.project-osrm.org

Here a screenshot of my test case, but the issue is not about OSM or Javascript, it is about OSRM map match, please read on:

![Animation](https://user-images.githubusercontent.com/1884458/233773223-d5f42c28-8a85-48f0-9045-6f59c19475bf.gif)

When I send [4 locations](https://router.project-osrm.org/match/v1/driving/10.738617,52.417409;10.737587,52.428245;10.736987,52.437352;10.733468,52.444416?overview=simplified&radiuses=50;50;50;50&generate_hints=false&skip_waypoints=true&gaps=ignore&annotations=nodes&geometries=geojson) to the map match service it works well.

When I send [168 locations](https://router.project-osrm.org/match/v1/driving/9.535078,50.944164;9.536036,50.943869;9.536951,50.943518;9.537805,50.943120;9.538589,50.942679;9.539302,50.942196;9.539936,50.941679;9.540493,50.941131;9.540974,50.940552;9.541367,50.939948;9.541666,50.939331;9.541912,50.938694;9.542148,50.938044;9.542391,50.937387;9.542632,50.936729;9.542879,50.936071;9.543139,50.935416;9.543346,50.934769;9.543483,50.934124;9.543601,50.933485;9.543716,50.932852;9.543833,50.932219;9.543947,50.931584;9.544058,50.930948;9.544171,50.930310;9.544285,50.929672;9.544403,50.929043;9.544543,50.928427;9.544774,50.927836;9.545107,50.927277;9.545525,50.926755;9.546023,50.926270;9.546602,50.925815;9.547261,50.925404;9.547989,50.925025;9.548733,50.924642;9.549472,50.924256;9.550250,50.923905;9.551080,50.923621;9.551961,50.923387;9.552855,50.923176;9.553736,50.922941;9.554601,50.922663;9.555449,50.922318;9.556231,50.921901;9.556936,50.921428;9.557600,50.920911;9.558263,50.920387;9.558936,50.919856;9.559631,50.919315;9.560351,50.918783;9.561146,50.918268;9.562016,50.917780;9.562932,50.917299;9.563860,50.916819;9.564793,50.916341;9.565702,50.915873;9.566604,50.915405;9.567495,50.914943;9.568384,50.914486;9.569267,50.914030;9.570142,50.913577;9.571019,50.913129;9.571903,50.912674;9.572798,50.912221;9.573704,50.911784;9.574636,50.911369;9.575579,50.910990;9.576552,50.910636;9.577536,50.910298;9.578533,50.909960;9.579511,50.909626;9.580492,50.909292;9.581465,50.908943;9.582363,50.908551;9.583187,50.908102;9.583915,50.907601;9.584556,50.907048;9.585086,50.906476;9.585539,50.905850;9.585866,50.905204;9.586066,50.904537;9.586150,50.903854;9.586122,50.903176;9.585972,50.902494;9.585714,50.901825;9.585333,50.901171;9.584830,50.900531;9.584288,50.899891;9.583748,50.899253;9.583236,50.898626;9.582748,50.898005;9.582287,50.897419;9.581804,50.896836;9.581312,50.896257;9.580791,50.895665;9.580274,50.895065;9.579855,50.894447;9.579544,50.893806;9.579347,50.893153;9.579261,50.892488;9.579288,50.891857;9.579434,50.891237;9.579701,50.890633;9.580076,50.890048;9.580542,50.889498;9.581104,50.888987;9.581742,50.888518;9.582459,50.888096;9.583238,50.887734;9.584067,50.887428;9.584937,50.887177;9.585830,50.886990;9.586768,50.886861;9.587715,50.886794;9.588671,50.886771;9.589647,50.886763;9.590616,50.886757;9.591549,50.886716;9.592466,50.886608;9.593363,50.886425;9.594239,50.886176;9.595066,50.885873;9.595834,50.885515;9.596533,50.885110;9.597166,50.884660;9.597722,50.884166;9.598229,50.883651;9.598726,50.883143;9.599237,50.882625;9.599745,50.882102;9.600198,50.881552;9.600554,50.880987;9.600812,50.880408;9.600972,50.879809;9.601021,50.879201;9.601020,50.878585;9.601030,50.877960;9.601033,50.877329;9.600980,50.876712;9.600817,50.876095;9.600563,50.875508;9.600231,50.874975;9.599786,50.874439;9.599243,50.873935;9.598625,50.873458;9.597985,50.872990;9.597345,50.872521;9.596729,50.872034;9.596167,50.871533;9.595653,50.871028;9.595212,50.870513;9.594856,50.869990;9.594551,50.869481;9.594234,50.868982;9.593894,50.868468;9.593543,50.867938;9.593184,50.867396;9.592812,50.866835;9.592443,50.866272;9.592087,50.865727;9.591737,50.865195;9.591419,50.864668;9.591154,50.864147;9.590906,50.863620;9.590662,50.863091;9.590408,50.862561;9.590158,50.862027?overview=simplified&radiuses=50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50&generate_hints=false&skip_waypoints=true&gaps=ignore&annotations=nodes&geometries=geojson), then it responds with `{"message":"Too many trace coordinates","code":"TooBig"}` and 400 Bad Request.

I believe this is an issue, because from my understanding 168 locations should be not an unusual use case for map matching.

I have searched around and noticed that POST is not supported, so I have not tried a POST request.

Here a screenshot of the both curl calls:

![image](https://user-images.githubusercontent.com/1884458/233772218-9cfbe3ad-a041-4d1a-b070-ba7b847b1aab.png)

I have looked into Desktop Docker log files, but there was no additional information there:

![image](https://user-images.githubusercontent.com/1884458/233772279-65f87575-ce9d-4081-90cb-0c102ce8e13f.png)

# Steps to reproduce

Just click on [this link](https://router.project-osrm.org/match/v1/driving/9.535078,50.944164;9.536036,50.943869;9.536951,50.943518;9.537805,50.943120;9.538589,50.942679;9.539302,50.942196;9.539936,50.941679;9.540493,50.941131;9.540974,50.940552;9.541367,50.939948;9.541666,50.939331;9.541912,50.938694;9.542148,50.938044;9.542391,50.937387;9.542632,50.936729;9.542879,50.936071;9.543139,50.935416;9.543346,50.934769;9.543483,50.934124;9.543601,50.933485;9.543716,50.932852;9.543833,50.932219;9.543947,50.931584;9.544058,50.930948;9.544171,50.930310;9.544285,50.929672;9.544403,50.929043;9.544543,50.928427;9.544774,50.927836;9.545107,50.927277;9.545525,50.926755;9.546023,50.926270;9.546602,50.925815;9.547261,50.925404;9.547989,50.925025;9.548733,50.924642;9.549472,50.924256;9.550250,50.923905;9.551080,50.923621;9.551961,50.923387;9.552855,50.923176;9.553736,50.922941;9.554601,50.922663;9.555449,50.922318;9.556231,50.921901;9.556936,50.921428;9.557600,50.920911;9.558263,50.920387;9.558936,50.919856;9.559631,50.919315;9.560351,50.918783;9.561146,50.918268;9.562016,50.917780;9.562932,50.917299;9.563860,50.916819;9.564793,50.916341;9.565702,50.915873;9.566604,50.915405;9.567495,50.914943;9.568384,50.914486;9.569267,50.914030;9.570142,50.913577;9.571019,50.913129;9.571903,50.912674;9.572798,50.912221;9.573704,50.911784;9.574636,50.911369;9.575579,50.910990;9.576552,50.910636;9.577536,50.910298;9.578533,50.909960;9.579511,50.909626;9.580492,50.909292;9.581465,50.908943;9.582363,50.908551;9.583187,50.908102;9.583915,50.907601;9.584556,50.907048;9.585086,50.906476;9.585539,50.905850;9.585866,50.905204;9.586066,50.904537;9.586150,50.903854;9.586122,50.903176;9.585972,50.902494;9.585714,50.901825;9.585333,50.901171;9.584830,50.900531;9.584288,50.899891;9.583748,50.899253;9.583236,50.898626;9.582748,50.898005;9.582287,50.897419;9.581804,50.896836;9.581312,50.896257;9.580791,50.895665;9.580274,50.895065;9.579855,50.894447;9.579544,50.893806;9.579347,50.893153;9.579261,50.892488;9.579288,50.891857;9.579434,50.891237;9.579701,50.890633;9.580076,50.890048;9.580542,50.889498;9.581104,50.888987;9.581742,50.888518;9.582459,50.888096;9.583238,50.887734;9.584067,50.887428;9.584937,50.887177;9.585830,50.886990;9.586768,50.886861;9.587715,50.886794;9.588671,50.886771;9.589647,50.886763;9.590616,50.886757;9.591549,50.886716;9.592466,50.886608;9.593363,50.886425;9.594239,50.886176;9.595066,50.885873;9.595834,50.885515;9.596533,50.885110;9.597166,50.884660;9.597722,50.884166;9.598229,50.883651;9.598726,50.883143;9.599237,50.882625;9.599745,50.882102;9.600198,50.881552;9.600554,50.880987;9.600812,50.880408;9.600972,50.879809;9.601021,50.879201;9.601020,50.878585;9.601030,50.877960;9.601033,50.877329;9.600980,50.876712;9.600817,50.876095;9.600563,50.875508;9.600231,50.874975;9.599786,50.874439;9.599243,50.873935;9.598625,50.873458;9.597985,50.872990;9.597345,50.872521;9.596729,50.872034;9.596167,50.871533;9.595653,50.871028;9.595212,50.870513;9.594856,50.869990;9.594551,50.869481;9.594234,50.868982;9.593894,50.868468;9.593543,50.867938;9.593184,50.867396;9.592812,50.866835;9.592443,50.866272;9.592087,50.865727;9.591737,50.865195;9.591419,50.864668;9.591154,50.864147;9.590906,50.863620;9.590662,50.863091;9.590408,50.862561;9.590158,50.862027?overview=simplified&radiuses=50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50&generate_hints=false&skip_waypoints=true&gaps=ignore&annotations=nodes&geometries=geojson) sending 168 locations to map match service.

- `osrm-backend` version: **v5.26.0**
- OSM extract that was processed: germany-latest.osm.pbf
- Processing commands:

```
docker run -t -v c:/repos:/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/germany-latest.osm.pbf`
docker run -t -v c:/repos:/data osrm/osrm-backend osrm-partition /data/germany-latest.osrm
docker run -t -v c:/repos:/data osrm/osrm-backend osrm-customize /data/germany-latest.osrm
docker run --name osrm -t -i -p 5000:5000 -v c:/repos:/data osrm/osrm-backend osrm-routed --algorithm mld /data/germany-latest.osrm

```
- Server queries:

> https://router.project-osrm.org/match/v1/driving/9.535078,50.944164;9.536036,50.943869;9.536951,50.943518;9.537805,50.943120;9.538589,50.942679;9.539302,50.942196;9.539936,50.941679;9.540493,50.941131;9.540974,50.940552;9.541367,50.939948;9.541666,50.939331;9.541912,50.938694;9.542148,50.938044;9.542391,50.937387;9.542632,50.936729;9.542879,50.936071;9.543139,50.935416;9.543346,50.934769;9.543483,50.934124;9.543601,50.933485;9.543716,50.932852;9.543833,50.932219;9.543947,50.931584;9.544058,50.930948;9.544171,50.930310;9.544285,50.929672;9.544403,50.929043;9.544543,50.928427;9.544774,50.927836;9.545107,50.927277;9.545525,50.926755;9.546023,50.926270;9.546602,50.925815;9.547261,50.925404;9.547989,50.925025;9.548733,50.924642;9.549472,50.924256;9.550250,50.923905;9.551080,50.923621;9.551961,50.923387;9.552855,50.923176;9.553736,50.922941;9.554601,50.922663;9.555449,50.922318;9.556231,50.921901;9.556936,50.921428;9.557600,50.920911;9.558263,50.920387;9.558936,50.919856;9.559631,50.919315;9.560351,50.918783;9.561146,50.918268;9.562016,50.917780;9.562932,50.917299;9.563860,50.916819;9.564793,50.916341;9.565702,50.915873;9.566604,50.915405;9.567495,50.914943;9.568384,50.914486;9.569267,50.914030;9.570142,50.913577;9.571019,50.913129;9.571903,50.912674;9.572798,50.912221;9.573704,50.911784;9.574636,50.911369;9.575579,50.910990;9.576552,50.910636;9.577536,50.910298;9.578533,50.909960;9.579511,50.909626;9.580492,50.909292;9.581465,50.908943;9.582363,50.908551;9.583187,50.908102;9.583915,50.907601;9.584556,50.907048;9.585086,50.906476;9.585539,50.905850;9.585866,50.905204;9.586066,50.904537;9.586150,50.903854;9.586122,50.903176;9.585972,50.902494;9.585714,50.901825;9.585333,50.901171;9.584830,50.900531;9.584288,50.899891;9.583748,50.899253;9.583236,50.898626;9.582748,50.898005;9.582287,50.897419;9.581804,50.896836;9.581312,50.896257;9.580791,50.895665;9.580274,50.895065;9.579855,50.894447;9.579544,50.893806;9.579347,50.893153;9.579261,50.892488;9.579288,50.891857;9.579434,50.891237;9.579701,50.890633;9.580076,50.890048;9.580542,50.889498;9.581104,50.888987;9.581742,50.888518;9.582459,50.888096;9.583238,50.887734;9.584067,50.887428;9.584937,50.887177;9.585830,50.886990;9.586768,50.886861;9.587715,50.886794;9.588671,50.886771;9.589647,50.886763;9.590616,50.886757;9.591549,50.886716;9.592466,50.886608;9.593363,50.886425;9.594239,50.886176;9.595066,50.885873;9.595834,50.885515;9.596533,50.885110;9.597166,50.884660;9.597722,50.884166;9.598229,50.883651;9.598726,50.883143;9.599237,50.882625;9.599745,50.882102;9.600198,50.881552;9.600554,50.880987;9.600812,50.880408;9.600972,50.879809;9.601021,50.879201;9.601020,50.878585;9.601030,50.877960;9.601033,50.877329;9.600980,50.876712;9.600817,50.876095;9.600563,50.875508;9.600231,50.874975;9.599786,50.874439;9.599243,50.873935;9.598625,50.873458;9.597985,50.872990;9.597345,50.872521;9.596729,50.872034;9.596167,50.871533;9.595653,50.871028;9.595212,50.870513;9.594856,50.869990;9.594551,50.869481;9.594234,50.868982;9.593894,50.868468;9.593543,50.867938;9.593184,50.867396;9.592812,50.866835;9.592443,50.866272;9.592087,50.865727;9.591737,50.865195;9.591419,50.864668;9.591154,50.864147;9.590906,50.863620;9.590662,50.863091;9.590408,50.862561;9.590158,50.862027?overview=simplified&radiuses=50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50&generate_hints=false&skip_waypoints=true&gaps=ignore&annotations=nodes&geometries=geojson

# Specifications

Please provide details of your development environment.
- Windows 10, Docker Desktop (with 16 GB memory), osrm/osrm-backend
- HP Elitebook i7, 32 GB RAM

**Comment by danpat** [comment]
The `osrm-routed` command has various configuration options - do `osrm-routed --help` to list them.  One of them is an option to increase the number of coordinates permitted for map matching.

The `osrm-routed` HTTP server has no limit on the length of a `GET` request URL, nor does the `curl` command-line tool.  Other HTTP clients may not support unlimited URL lengths however, so YMMV.

**Comment by afarber** [comment]
Running with "--max-matching-size 1000" has helped me, thank you:

![image](https://user-images.githubusercontent.com/1884458/233791836-fa4be3dd-3ef1-4880-8f15-3c7a1fcbb2dc.png)
