### ISSUE TITLE
Does the routing take into account the lanes and the width?

### ISSUE THREAD

**Issue by GitBenjamin** [Project-OSRM/osrm-backend#6613]
hi, @SiarheiFedartsou 
**OSM** provides [key:lanes](https://wiki.openstreetmap.org/wiki/Key:lanes) and [Key:width](https://wiki.openstreetmap.org/wiki/Key:width) information, does the [5.27.1](https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#5271) routing take them into account and provide info on `the number of lanes` and `lane widths` of the return(accessed road)?

**Comment by SiarheiFedartsou** [comment]
No, it doesn’t return this information.

**Comment by GitBenjamin** [comment]
> No, it doesn’t return this information.
Thanks, so does it take that information into account and use it?

**Comment by GitBenjamin** [comment]
Thanks, so does it take that information into account and use it?


| |
chunyezhou
|
|
***@***.***
|
---- Replied Message ----
| From | Siarhei ***@***.***> |
| Date | 4/23/2023 21:36 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Project-OSRM/osrm-backend] Does the routing take into account the lanes and the width? (Issue #6613) |

No, it doesn’t return this information.

**Comment by danpat** [comment]
@GitBenjamin No, number of lanes isn't a factor in route selection.  You could customize `car.lua` to prefer roads with more lanes, if that's what you want.
