### ISSUE TITLE
osrm/osrm-backend image bug - Debian 9/stretch is not longer supported by Debian

### ISSUE THREAD

**Issue by acallejasz** [Project-OSRM/osrm-backend#6617]
# Issue

When you try to update the packects of the osrm/osrm-backend image (From [DockerHub](https://hub.docker.com/r/osrm/osrm-backend)) a error is output due to the fact that Debian 9/stretch is not longer supported by Debian [link](https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html). Thus, any command related with apt-get throughs an error. 

# Steps to reproduce
- Image: osrm/osrm-backend:latest
- apt-get install wget -y
- wget http://download.geofabrik.de/europe/spain/${city_name}-latest.osm.pbf -P /data

# Specifications
- Docker desktop

# Trace
osrm  | Ign:1 http://security.debian.org/debian-security stretch/updates InRelease
osrm  | Ign:2 http://security.debian.org/debian-security stretch/updates Release
osrm  | Ign:3 http://deb.debian.org/debian stretch InRelease
osrm  | Ign:4 http://deb.debian.org/debian stretch-updates InRelease
osrm  | Ign:5 http://deb.debian.org/debian stretch Release
osrm  | Ign:6 http://deb.debian.org/debian stretch-updates Release
osrm  | Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
osrm  | Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
osrm  | Ign:9 http://deb.debian.org/debian stretch/main all Packages
osrm  | Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
osrm  | Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
osrm  | Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
osrm  | Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
osrm  | Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
osrm  | Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
osrm  | Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
osrm  | Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
osrm  | Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
osrm  | Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
osrm  | Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
osrm  | Ign:9 http://deb.debian.org/debian stretch/main all Packages
osrm  | Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
osrm  | Err:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
osrm  |   404  Not Found [IP: 151.101.66.132 80]
osrm  | Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
osrm  | Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
osrm  | Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
osrm  | Ign:9 http://deb.debian.org/debian stretch/main all Packages
osrm  | Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
osrm  | Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
osrm  | Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
osrm  | Ign:9 http://deb.debian.org/debian stretch/main all Packages
osrm  | Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
osrm  | Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
osrm  | Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
osrm  | Ign:9 http://deb.debian.org/debian stretch/main all Packages
osrm  | Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
osrm  | Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
osrm  | Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
osrm  | Ign:9 http://deb.debian.org/debian stretch/main all Packages
osrm  | Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
osrm  |   404  Not Found
osrm  | Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
osrm  | Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
osrm  |   404  Not Found
osrm  | Reading package lists...
osrm  | W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
osrm  | W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
osrm  | W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
osrm  | E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.66.132 80]
osrm  | E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
osrm  | E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
osrm  | E: Some index files failed to download. They have been ignored, or old ones used instead.
osrm  | Reading package lists...
osrm  | Building dependency tree...
osrm  | Reading state information...
osrm  | E: Unable to locate package wget
osrm  | /build_osrm.sh: line 28: wget: command not found
osrm  | [error] Input file /data/madrid-latest.osm.pbf not found!
osrm  | [error] Input file "/data/madrid-latest.osrm.ebg" not found!
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.ebg
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.partition
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.cells
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.ebg_nodes
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.properties
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.enw
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.ramIndex
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.fileIndex
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.edges
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.geometry
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.turn_weight_penalties
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.turn_duration_penalties
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.datasource_names
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.names
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.timestamp
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.properties
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.icd
osrm  | [warn] Missing/Broken File: /data/madrid-latest.osrm.maneuver_overrides
osrm  | [error] Required files are missing, cannot continue
osrm exited with code 1

**Comment by danpat** [comment]
Please provide some more specific detail.  We don't currently publish Debian images with each release, perhaps someone has been maintaining a package repository you've been using?

**Comment by acallejasz** [comment]
> Please provide some more specific detail. We don't currently publish Debian images with each release, perhaps someone has been maintaining a package repository you've been using?

Sorry I have changed the tittle and content, I hope I clarify the issue
