### ISSUE TITLE
GCC-states .osrm file is not generated

### ISSUE THREAD

**Issue by venkat4p** [Project-OSRM/osrm-backend#6618]
I have executed osrm-extract command on gcc-states-latest.osm.pbf file and able to see all files except gcc-states-latest.osrm, where is this file located?  Below commands i have used.

`osrm-extract -p ../profiles/car.lua gcc-states-latest.osm.pbf`
`osrm-partition gcc-states-latest.osrm`
`osrm-customize gcc-states-latest.osrm`

<img width="999" alt="Screenshot 2023-04-27 at 10 07 13 AM" src="https://user-images.githubusercontent.com/110828217/234760752-6444f533-b698-4a1f-93d9-081f77d78ede.png">

**Comment by SiarheiFedartsou** [comment]
We do not generate this file anymore - it used to be generated, but it is just intermediate state of osrm-extract which is not needed for production work.

**Comment by venkat4p** [comment]
so i would be good to execute below command right?

New way
`osrm-routed --algorithm mld gcc-states-latest`

older way is 

`osrm-routed --algorithm mld gcc-states-latest.osrm`

**Comment by SiarheiFedartsou** [comment]
Yes, it should work.

**Comment by venkat4p** [comment]
When i run the command i am getting below error

this is the command

`osrm-routed --algorithm mld gcc-states-latest`


`terminate called after throwing an instance of 'osrm::util::exception'
  what():  Could not find any metrics for MLD in the data. Did you load the right dataset?
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted`
