### ISSUE TITLE
Path with "mountain_hiking" creates weird snapping on foot profile

### ISSUE THREAD

**Issue by jeabapLANG** [Project-OSRM/osrm-backend#6619]
Hi
When trying to connect two dots together OSM create a completely different path than the requested one (a much longer path than the original one).

I can't understand where this error can come from and have already tried different ways to remove it without success...
I also looked and the path seems to exist in the OpenStreetMap data.

If anyone has any idea what the problem might be, I really need help!
Thanks in advance ;)

![image](https://user-images.githubusercontent.com/92392189/235950591-8692e267-b5ae-4730-92f7-c566c34043c9.png)

**Comment by jeabapLANG** [comment]
> To test this issue :

Here is the road I obtain from OSRM :
https://map.project-osrm.org/?z=18&center=49.449513%2C6.355011&loc=49.448922%2C6.355993&loc=49.448702%2C6.355703&hl=en&alt=0&srv=2

![image](https://user-images.githubusercontent.com/92392189/235952741-2324c343-fd4b-495f-b829-a5925993a712.png)

Here is the road I wanted (approx due to snapping) :
https://map.project-osrm.org/?z=18&center=49.448770%2C6.355800&loc=49.448908%2C6.355988&loc=49.448702%2C6.355703&hl=en&alt=0&srv=2

![image](https://user-images.githubusercontent.com/92392189/235952851-3254eb51-cfdd-4bd5-8a03-8b348132e59e.png)

**Comment by nilsnolde** [comment]
best to add the URL to the way in question on https://openstreetmap.org, so we can see the tags

**Comment by jeabapLANG** [comment]
I'll do it right away ;)
Thx for your holy **** fast response

**Comment by jeabapLANG** [comment]
Here is the result for OSRM (Foot) :
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=49.44890%2C6.35594%3B49.44865%2C6.35562#map=19/49.44892/6.35566

![image](https://user-images.githubusercontent.com/92392189/235954218-82c44acc-7920-4c72-b864-a9bcb45c585c.png)

And here is the result for GraphHopper (Foot) :
https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=49.44890%2C6.35594%3B49.44865%2C6.35562#map=19/49.44879/6.35577

![image](https://user-images.githubusercontent.com/92392189/235954301-2ea16906-c3c6-4381-9dd3-5f5b264e20b5.png)

And really strange thing by GraphHopper it seems to work but by OSRM a big NOPE 🤔

**Comment by jeabapLANG** [comment]
As said above, what could potentially cause an error like this?

**Comment by nilsnolde** [comment]
Works for me for all routing engines on foot & bicycle: https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=49.44889%2C6.35592%3B49.44868%2C6.35546#map=19/49.44878/6.35572.

Car routing is obviously not possible there. You didn't mention which mode you want to use? I assume bike?

You need to look at the tags of the way(s), e.g. this one has explicit bike access. The only way how this would not be routable is if the router decided the `highway=path` is not bike-routable, but neither OSRM nor the others (rightfully) think so.

**Comment by jeabapLANG** [comment]
I was using the foot mode and when foot is selected OSRM creates an alternative path because the exact part mentioned above is not recognized as having a foot access

**Comment by nilsnolde** [comment]
Did you try the link I put there and change it to OSRM? It finds the way. If that's not what you want (though it's pretty exactly the route you were first posting), we need the URL of the **way**. 

I did notice you're using deprecated OSRM API URLs, it's hosted at https://routing.openstreetmap.de/ since a long time. Not sure if they're just linked by redirects, still better to use those URLs (e.g. look in the network tab when using osm.org).

**Comment by jeabapLANG** [comment]
I just double-checked but I think you got it wrong/took the right route.

As I explained above (see pictures),
OSRM does not completely connect the path and if the point is placed slightly higher, it creates a huge detour.
GraphHopper on the other hand manages to completely connect the two points no matter where they are located and does not create any detours (ref pictures above).

**Comment by nilsnolde** [comment]
Ok, this is the way: openstreetmap.org/way/203219837. It has `sac_scale=mountain_hiking` and seems OSRM doesn't like that. Nothing you can do other than PRing a fix to the foot.lua.

**Comment by jeabapLANG** [comment]
Thank you very much for your answer 😊
So what do I need to do to fix this?
A pull request?
Or sometimes editing the OpenStreetMap is enough to be able to update OSRM?
