### ISSUE TITLE
No segment returned for the whole table when not all destination points have a route

### ISSUE THREAD

**Issue by okssev** [Project-OSRM/osrm-backend#6620]
Hello, I’m using the tables API and I have a problem that some of my destination points don't have a route available in the data set. So, it’s either distance/duration is returned for every destination or no segment error for all and that means some of the routes are lost. Is there a possibility to get nulls or no data returned for the routes that are not found in the response table?

**Comment by jcoupey** [comment]
The `table` docs state that `distances[i][j]` and `durations[i][j]` values _"can be null if no route between `i` and `j` can be found"_ so what you're asking for is already the expected behavior.

Can you maybe elaborate on the exact problem you're facing? It's generally a good idea to include a minimal request/response example for illustration, ideally using the demo server to allow easy reproduction.

**Comment by okssev** [comment]
Yes, this is correct. However, I may not wrote clearly. The error I'm getting as a response is `Could not find a matching segment for coordinate`. Road segment matching one of the provided coordinates was not found. Example request - `https://router.project-osrm.org/table/v1/driving/151.21000000%2c-33.88000000%3b151.33551320%2c-33.51363350%3b151.20100000%2c-33.65100000%3b150.99244690%2c-33.76184587%3fsources%3d0%26destinations%3d1%3b2%3b3%26annotations%3dduration%2cdistance%26generate_hints%3dfalse%26radiuses%3d1000%3b1000%3b1000%3b1000`. This returns no segment because second coordinate seems incorrect. If I do the same request only with first destination coordinate, I get the result - `https://router.project-osrm.org/table/v1/driving/151.21000000%2c-33.88000000%3b151.33551320%2c-33.51363350%3fsources%3d0%26destinations%3d1%26annotations%3dduration%2cdistance%26generate_hints%3dfalse%26radiuses%3d1000%3b1000`

**Comment by jcoupey** [comment]
It looks like the error will take over here. On the other hand, if you really need to use radiuses, you should be able to test whether your input coordinates are individually OK with that using the `nearest` service.
