### ISSUE TITLE
Use OSRM with dynamic input data taken from overpassAPI

### ISSUE THREAD

**Issue by fededige** [Project-OSRM/osrm-backend#6622]
Hi there, 
I'll start by saying that I am a complete newbie when it comes to Docker, etc. 
I'm trying to use an OSRM Docker container to calculate the cost matrix that I need to use Vroom.
I managed to do it by downloading the data that I need from Geofabrik, using a small geographic area because of my limited hardware resources.

My question is: Is there a way to load the data in real-time without restarting the Docker container? In my use case, I'd like to ask the user for coordinates and download the OSM data around that point.

P.S. It's my first time using GitHub issues to ask a question, feel free to remove my question if it's not related or off-topic. 
Sorry for my broken English, and many thanks.

**Comment by alexanderzatko** [comment]
I am new to OSRM as well and I think I have a similar question, but let me first clarify the issue you are facing.

Why do you need to download just a portion of the known network (from the OSM db)? You can download a .pbf file that will contain all network segments your users might need to route on, which would eliminate the need to dynamically load your data sources, right? Is your intent to run your route queries against as small network as possible for performance (or resource constraint) reasons?

**Comment by fededige** [comment]
Yes, thats exactly the reason, I don't have enogh RAM capacity to preprocess a large pbf file. Also I don't really like to limit the user to a specific geographical area. 
For example, even if I had enough RAM and could preprocess the data for Italy (the specific geographical region I'm interested in), I wouldn't want to restrict user requests for other geographical areas.

**Comment by alexanderzatko** [comment]
...or there is no way to do this with OSMR, if I read the issue #6265 correctly.

**Comment by nilsnolde** [comment]
You can swap whole networks with shared memory, but you can't "append" edges/nodes to existing networks. None of the popular routing engines can do that (yet), but of course it'd be super interesting to be able to do that.

@fededige you'll need to build the graphs for those mini networks, no difference to larger networks conceptually, just less ressources & faster turnaround time. What you want to do doesn't scale well.

**Comment by alexanderzatko** [comment]
@nilsnolde., thank you for clarifying this for me.

**Comment by fededige** [comment]
@nilsnolde thanks for the explanation, in fact I realized that this solution is not very scalable, as it would be difficult to serve multiple users at the same time.
