### ISSUE TITLE
How are roads classified as 'Urban' or 'Rural'

### ISSUE THREAD

**Issue by Basiim** [Project-OSRM/osrm-backend#6626]
Hi,
I'm currently OSRM's car profile referring to #6002 I understand the precedence of speed. There is a [road](https://www.openstreetmap.org/way/342521051#map=17/54.88557/10.38321&layers=D) in Denmark whose tags should be:

- `highway=unclassified`
- `maxspeed=80`
- `surface=asphalt`

I have set the speed of unclassified type to 72, but as this road is in a rural area, I have set max speed of rural as 50 in:

```
maxspeed_table_default = {
      urban = 50,
      rural = 50,
      trunk = 110,
      motorway = 130
    },
```

- Calculating the speed between two points on the said road I get 72.
- I don't understand how OSRM is classifying a road as Urban or Rural. If the said road is in a rural area shouldn't the speed be overridden by 50?
- How does `Wayhandlers.maxspeed` actually work?

**Comment by ftrebien** [comment]
In car.lua, _maxspeed_table_ hints that OSRM uses [source:maxspeed](https://wiki.openstreetmap.org/wiki/Key:maxspeed#Implicit_maxspeed_values) somehow. car.lua defines that _WayHandlers.speed_ (which infers the speed from the way type) runs before _WayHandlers.maxspeed_ (which should then override it if a maxspeed tag is present). _WayHandlers.maxspeed_ defines that source:maxspeed will be used if maxspeed is not set on the way. This in turn calls _WayHandlers.parse_maxspeed_ which uses _maxspeed_table_default_ with the urban/rural/trunk/motorway suffix of _source:maxspeed_ values.

So if your way has neither _maxspeed_ nor _source:maxspeed_, the inferred speed is the one related to the way type. If it has only _source:maxspeed_, then it is inferred from the urban/rural type it specifies. If it has both _maxspeed_ and _source:maxspeed_, _maxspeed_ should be used.

**Comment by Basiim** [comment]
Perfect, it makes sense now.
Thanks.
