### ISSUE TITLE
Adding additional destinations to table query affects distances/durations of other destinations

### ISSUE THREAD

**Issue by mattwigway** [Project-OSRM/osrm-backend#6629]
# Issue

I'm seeing a situation where when I add an additional location to a distance matrix query, the durations between the other locations change dramatically. This is using an MLD-based network, using an OSM extract from Protomaps clipped using osmconvert, and using the `foot.lua` profile from fossgis-routing-server/cbf-routing-profiles.

# Steps to reproduce

Please provide the steps required to reproduce your problem.
- `osrm-backend` version being used: 5.28.0 (`d6afe91d8`)
- Processing commands (e.g. CH vs MLD processing): Standard osrm-extract, osrm-partition, osrm-customize

It's very dependent on the exact locations involved, and is rare. Here's one example (I don't see the same behavior on the demo server, perhaps it's using CH instead of MLD):

With only one destination: duration from source to dest is 323.5 seconds:
```
$ curl "http://localhost:5000/table/v1/walk/-93.045528,44.741725;-93.040551,44.736798?sources=0&destinations=1" | jq .durations
[
  [
    323.5
  ]
]
```

Adding another coordinate (that isn't even referenced as a source or destination, though nothing changes if it is), the distance between the first two coordinates is now 14199 (!) seconds:

```
$ curl "http://localhost:5000/table/v1/walk/-93.045528,44.741725;-93.040551,44.736798;-93.082025,44.796958?sources=0&destinations=1" | jq .durations
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   447  100   447    0     0  45864      0 --:--:-- --:--:-- --:--:-- 63857
[
  [
    14199.7
  ]
]
```

# Specifications

Please provide details of your development environment.
- Library/dependency versions: (would have to dig a bit, can do if it seems relevant)
- Operating system: seen on macOS and Windows Subsystem for Linux
- Hardware: Apple M1 and Intel Core i9

**Comment by jcoupey** [comment]
This may be due to a difference in snapping when adding the third coordinate, resulting in a significantly different route between the two initial points.

In order to dig a bit more, it would be interesting to see if you're able to replicate using the `route` endpoint: do you get the same discrepancy with A -> B and the first leg of A -> B -> C when routing?

**Comment by mattwigway** [comment]
Good thought, thanks! Yes, it's exactly the same when doing that, and that also lets me get geometries:
![Image showing a short and long route - likely due to snapping issue](https://github.com/Project-OSRM/osrm-backend/assets/566958/39299cfc-9f67-4761-9e87-2ff3cfebd35b)

It does look like a snapping issue - the start and end of the routes is different, and the input coordinates appear to be close to the midpoint between the selected points. Since the (pedestrian) network is disconnected in this area, this produces a huge discrepancy.

What confuses me, though, is that the "confounder" point C is not anywhere nearby (only visible in the inset map). I'm not very familiar with the snapping in OSRM, but the snapping issues I've debugged in other software in the past usually resulted from snapping uninitentionally changing the length of nearby edges.

**Comment by mattwigway** [comment]
Oh, I bet it's about disconnected components. The network is pretty disconnected here, and the first route takes place entirely on a disconnected bit of road network (service roads in some kind of plant). Adding the second destination I guess forces OSRM to snap to something that's connected to the rest of the world?

**Comment by mattwigway** [comment]
This is probably also the underlying cause for #6606 - evidently the table service requires that all the points requested be connected to one another, and snaps them to make sure that happens.

**Comment by jcoupey** [comment]
Well, you figured out all the rest by yourself! There is indeed an internal logic backed into OSRM to pick the right connected component based on the set of points in the query.

Good to note also that this kind of debugging can be made much easier by using the debug view from `osrm-frontend`, which can be pointed at your own instance: https://github.com/Project-OSRM/osrm-frontend/#changing-backends.
