### ISSUE TITLE
Readme.md example contains a typo

### ISSUE THREAD

**Issue by smhanov** [Project-OSRM/osrm-backend#6636]
The current example under "Using docker" is:

    docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf || "osrm-extract failed"

It should be:

    docker run -t -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf || echo "osrm-extract failed"

Without the echo, it always ends with this message, causing confusion

    osrm-extract failed: command not found

All of the examples in this section have the same problem.

**Comment by debarshikundu** [comment]
Hello Steve,
Thank you for your Issue request. I addressed the request by adding 'echo' to the three command lines
that were necessary to be edited.
You can let me know if there are any other edits you would like me to make.

Sincerely,

Debarshi Kundu
