### ISSUE TITLE
Error: Error in curl::curl_fetch_memory(utils::URLencode(url), handle = req_handle) :    Empty reply from server

### ISSUE THREAD

**Issue by jonathanbxl** [Project-OSRM/osrm-backend#6639]
Hi,

I'm just starting out with R and also with OSRM...
I installed OSRM in a Docker, to be able to send requests larger than the 10,000 allowed.

It worked...but it doesn't work any more...

When I run my : 

travel_time <- osrmTable(src = Departure_sf , dst=Arrival_sf, osrm.profile = "foot", osrm.server = "localhost:5000/")

I receive an error message....

Error: Error in curl::curl_fetch_memory(utils::URLencode(url), handle = req_handle) : 
  Empty reply from server

Can anyone help me?

**Comment by jcoupey** [comment]
>to be able to send requests larger than the 10,000 allowed.

If you're sending huge requests, this may be a limitation on the size of a GET request somewhere. I guess you're using `osrm-routed` which does not have a built-in limit. In any case you should check `osrm-routed` logs to see whether your requests get truncated or if anything else looks suspicious.
