### ISSUE TITLE
router.project-osrm.org seems down

### ISSUE THREAD

**Issue by frantzmiccoli** [Project-OSRM/osrm-backend#6647]
# Issue

http://router.project-osrm.org/ and request to it are failing in 502.

We are using more specifically "/table/v1/driving/".

I hope this is the right place to signal this issue.

# Steps to reproduce

1. Open your browser to https://router.project-osrm.org/
2. Get a 502

Or try a routing request :

1. `https://router.project-osrm.org/table/v1/driving/6.302797,49.66657;6.268498,49.630823;6.349145,49.688971;6.140544,49.698493;6.138659,49.674076;6.136095,49.662025;6.386746,49.6998;6.259068,49.602752?sources=0&destinations=1;2;3;4;5;6;7`
2. Get a 502

# Specifications

Irrelevant.

**Comment by ViktoriyaER** [comment]
Good afternoon. We also have a 502 error since the morning. Please tell me if you can find some new information?

**Comment by nilsnolde** [comment]
Just a gentle reminder that this is a **demo** service run by volunteers and no one should rely on having any uptime. The issue is created, people will get to it when they find a chance to get to it.

Also the base URL updated to https://routing.openstreetmap.de a few years ago. Lastly, it's only the car profile that's impacted, bike & ped work fine.

**Comment by LeoSlager** [comment]
Now in openstreetmap.org the links "Auto (OSRM)" en "Te Voet (OSRM)" are interchanged.
See:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=51.64942%2C3.94296%3B51.64993%2C3.94340

**Comment by johnymanuelli** [comment]
Same problem, any ideas ? Any alternatives?

**Comment by LeoSlager** [comment]
On screen the button "Auto (OSRM)" is calling the wrong script and shows a route for foot.
On screen the button "Te voet (OSRM)" is calling the wrong script and shows a route for cars.

**Comment by LeoSlager** [comment]
Dear Sebastian,

 

I am not familiar with programming but I can describe what is happening :

 

On screen the button "Auto (OSRM)" is calling the wrong script and shows a route for foot.
On screen the button "Te voet (OSRM)" is calling the wrong script and shows a route for cars.

 

Kind regards

Leo

 

Van: Sebastian Manuelli ***@***.*** 
Verzonden: zaterdag 8 juli 2023 7:43
Aan: Project-OSRM/osrm-backend ***@***.***>
CC: LeoSlager ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Project-OSRM/osrm-backend] router.project-osrm.org seems down (Issue #6647)

 

Same problem, any ideas ? Any alternatives?

**Comment by nilsnolde** [comment]
Dude, can you please chill.. Posting the same (entirely unrelated) stuff doesn't fix it either does it? Open a new issue and try some less pushy behavior. FWIW, what's you're saying is not true for English translation, "Car" calls car (and currently fails) and "Foot" calls foot.

**Comment by LeoSlager** [comment]
Thanks for your kind words.

New here, I was not aware that answering a message should cause a post in this topic.

 

But I will not bothering you further more

Leaving github.

deleting my account

bye

 

Van: Nils ***@***.*** 
Verzonden: zaterdag 8 juli 2023 11:07
Aan: Project-OSRM/osrm-backend ***@***.***>
CC: LeoSlager ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Project-OSRM/osrm-backend] router.project-osrm.org seems down (Issue #6647)

 

Dude, can you please chill.. Posting the same (entirely unrelated) stuff doesn't fix it either does it? Open a new issue and try some less pushy behavior. FWIW, what's you're saying is not true for English translation, "Car" calls car (and currently fails) and "Foot" calls foot.

**Comment by lonvia** [comment]
Should be fixed now. This issue tracker here might not be the best place to report operational issues. A mail to the administrators (see https://map.project-osrm.org/about.html) should have a better effect.

**Comment by frantzmiccoli** [comment]
@nilsnolde note taken about the demo aspect of the server. Thanks for the reminder.

@lonvia thanks for the notice and for the more relevant contact link.

**Comment by frantzmiccoli** [comment]
@nilsnolde replacing routing.openstreetmap.de in the URL actually leads to a 404.
