### ISSUE TITLE
Can latest OSRM image be pushed on docker hub?

### ISSUE THREAD

**Issue by hmnsh25** [Project-OSRM/osrm-backend#6651]
Hi,

Can latest OSRM image be pushed on docker hub as my project has it configured it with it and making changes to the configuration will take a lot of effort?

Thanks and Regards,
Himanshu Gupta

**Comment by nilsnolde** [comment]
No project admin, but I doubt it: Dockerhub has had some very erratic behavior in the past year and for the better or worse, GH’s registry is the best/safest alternative for OSS projects these days.

What’s so much effort of changing a URL? That’s literally all it takes, else you’re making things more complex than they need to be. Also, feel free to host your own OSRM docker image, then you’re in control.

**Comment by mjjbell** [comment]
This project no longer has access to Docker Hub due to a change in their Terms of Service.

**Comment by nilsnolde** [comment]
Actually they [reverted that change](https://github.com/valhalla/valhalla/issues/4029#issuecomment-1483612467) (access to their build infrastructure for OSS "teams", in case that's what you mean) a few days after the initial announcement hahah but the damage was done already. I moved all our docker image stuff to GHA as well.

**Comment by jcfj** [comment]
If somebody still has access, it would be nice to put a deprecation notice and a link to the ghcr package onto https://hub.docker.com/r/osrm/osrm-backend/ …
