### ISSUE TITLE
Which speed information is considered for routing in OSRM? One from .lua profile or the one from OSM maps? 

### ISSUE THREAD

**Issue by viveksagarghosh93** [Project-OSRM/osrm-backend#6652]
I am currently using OSRM to predict drive times and distances between two points. But I am trying to modify the 'maxspeed' information using traffic data in the OSM maps which is being fed to OSRM. I want to know if OSRM considers (in the routing algo) the 'maxspeed' parameter in the OSM maps first or the speed information by road type in the car.lua file first?? Would really appreciate any insight into this!

**Comment by jcoupey** [comment]
You'll have to dig a bit into the profile logic to see how it works in detail. TL;DR various handlers are called sequentially when parsing a way, and `speed` is called right before `max_speed`:

https://github.com/Project-OSRM/osrm-backend/blob/62e11fd5dbc8d5e888c6e2555505ae684d8a2759/profiles/car.lua#L433-L435

**Comment by jcoupey** [comment]
Closing as answered.
