### ISSUE TITLE
Returned value changed

### ISSUE THREAD

**Issue by aghand0ur** [Project-OSRM/osrm-backend#6653]
Hello, we are using the below unittest and noticed recently that the expected value changed from 82588.4 to 82578.4..
Any reason for that?

```
class TestOSMRrouter(unittest.TestCase):
  def test_osmr_router_beirut_tyre_distance(self):
    long1, lat1, long2, lat2 = 33.8938, 35.5018, 33.2705, 35.2038
    expected = 82578.4
    actual = location_manager.get_route(long1, lat1, long2, lat2)["routes"][0]["legs"][0]["distance"]
    return self.assertEqual(actual,expected)
```
   
cc  @AliSamhat07 @MhmdDimassi

**Comment by jcoupey** [comment]
Any change in the underlying road network described in the OSM data could cause this upon updating. You'd probably have to take a close look at the previous and current routes to spot the differences.

A change of 10 meters in a ~83km route does not sound like a big deal, and expecting (floating point) equality over time here is probably a bit optimistic.

**Comment by aghand0ur** [comment]
i see
thank you @jcoupey
