### ISSUE TITLE
why this can't be routed 

### ISSUE THREAD

**Issue by aibear-huang** [Project-OSRM/osrm-backend#6656]
i have a osm file , and it looks all right but there some wrong with the osrm-routed result 
curl "http://localhost:5000/route/v1/driving/115.80532793164787,40.330290797867036;115.80646532335652,40.330517716106336?steps=false&annotations=false&geometries=geojson&overview=full"
2419452 this node can not be pass ,  not cross this node is all right, can have expected route, when the  start end cross this node, there is a problem,  start end will not snap to incorrect position, could some one help me?very appreciate~!

![image](https://github.com/Project-OSRM/osrm-backend/assets/114399974/d92759cb-3c03-45ce-859e-a6221e897a81)

**Comment by aibear-huang** [comment]
the problem is my osm data or something wrong with my lua osrm-extract osrm-contract osrm-routed? some Weird

**Comment by aibear-huang** [comment]
i found start point and end point snap to the nearest way which is in small component, but the far away snapped node is in big component, so the result  use the big component route result. but it not my expected.
the best result should be pass node 2419452, the snap distance is very small (1 or 2meter), otherwise snap distance should be more than 100 meters.

**Comment by aibear-huang** [comment]
if the osm data is  from a country,  the motorway should be in big component, but from my log, it is not.  i have no idea about why the component is wrong.

**Comment by aibear-huang** [comment]
i debug the osrm-routed,  i found the way connect to node 2419452 have diff component id, both component is tiny component, is there something wrong with my osrm-extract or osrm-contract or my osm file?

**Comment by aibear-huang** [comment]
> I you want to debug the result of applying the profile to your data, you should definitely check out the debug view from osrm-frontend: https://github.com/Project-OSRM/osrm-frontend/#changing-backends
> 
> It will help you understand how OSRM sees the routing graph internally, as in http://map.project-osrm.org/debug/bike.html#17.43/52.38930/9.75552 where isolated components appear in purple.

thanks for your reply,  my osm data is a private data, and now my doubt is why the connected ways have different component id, could some one help?

**Comment by nilsnolde** [comment]
Ah then you’re likely doing smth wrong when producing that PBF? That no one can help you with though. Sounds like you have little connectivity, so the first thing I’d do is check an excerpt of the data in JOSM. Other than that, you can’t expect anyone to help you much, we can’t tel what you did to the data. It’s more than likely it’s not osrm, so good luck!

**Comment by aibear-huang** [comment]
> 

thank you the same, i have check my osm data carefully, and i found some adjoin ways have different nodeid. the problem solved.

**Comment by nilsnolde** [comment]
ok great, congrats! can you close the issue then?
