### ISSUE TITLE
Path along the canal de Marne a Rhin not considered for bicycle (Gondrexange - Rechicourt

### ISSUE THREAD

**Issue by vincentius63** [Project-OSRM/osrm-backend#6660]
If I look at https://map.project-osrm.org/debug/bike.html#17/48.68745/6.92630 I see that the path (signed cycling route) along the Canal de Marne a Rhin is not considered for cycling. Why?

The first ways:
https://www.openstreetmap.org/way/257021589
https://www.openstreetmap.org/way/257021549 (bridge)
https://www.openstreetmap.org/way/129628747 (just to the bridge with steps over the canal)
...
all have bicycle=designated 
and were last modified 5 years ago.

This is valid for the next ways too. I have cycled there along with no problem at all. What is the problem for OSRM?

**Comment by mjjbell** [comment]
This is an issue with the routing profile used by https://map.project-osrm.org, you'll need to open a ticket in https://github.com/fossgis-routing-server/cbf-routing-profiles

cc: @datendelphin https://github.com/fossgis-routing-server/cbf-routing-profiles/commit/6bfa8aab9b14e005e4db27711144ba943e9e418f appears to fix this.
