### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sanleshusheng** [Project-OSRM/osrm-backend#6668]
<img width="1363" alt="image" src="https://github.com/Project-OSRM/osrm-backend/assets/33344109/47e68d42-a1e3-4f5f-a6da-6d22f7d8d1e8">

**Comment by sanleshusheng** [comment]
the problem have been solved. Thanks. 
Need to stop the : CMake Treat Warnings as Errors.

**Comment by jiawlu** [comment]
I met the same issue. However, according to the wiki [page](https://github.com/Project-OSRM/osrm-backend/wiki/Coding-Standards), the developers suggest Treat Compiler Warning as Errors. If your code has compiler warnings in it, something is wrong. Any ideas on that?

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/opt/homebrew/Cellar/llvm/16.0.6/bin/clang++ -DCMAKE_C_COMPILER=/opt/homebrew/Cellar/llvm/16.0.6/bin/clang ..`

```
coordinate_calculation.cpp:326:5: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
    std::find_if(std::begin(lhs), std::end(lhs), compute_minimum_distance_in_rhs);
```

**Comment by DennisOSRM** [comment]
Please reopen should the error persist.
