### ISSUE TITLE
[object Object] showed for guidance instructions

### ISSUE THREAD

**Issue by gliderkite** [Project-OSRM/osrm-backend#6671]
# Issue

When querying for any route in the https://map.project-osrm.org/ the frontend displays `[object Object]` instead of the instruction description (the response returned by the backend seems to be correct as it contains all the `RouteStep` information).

<img width="331" alt="Screenshot 2023-08-07 at 10 49 43" src="https://github.com/Project-OSRM/osrm-backend/assets/9151098/50a48e69-8275-4490-9fc2-5372ab48aad0">

Please, feel free to move the issue to the right repository if this isn't.

**Comment by datendelphin** [comment]
Thank you, that was a regression while trying to fix the geocoder plugin. Fixed now in osrm-frontend
