### ISSUE TITLE
Have you considered upgrading from http1.0 to http1.1？

### ISSUE THREAD

**Issue by GitBenjamin** [Project-OSRM/osrm-backend#6672]
[The built-in HTTP server is a basic HTTP/1.0 server that supports a 'keep-alive' extension. Persistent connections are limited to 512 requests per connection and allow no more than 5 seconds between requests.](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md)
Hi, @mjjbell .I've found that osrm supports long connection, but it's not really http1.1. Have you considered upgrading to http1.1？

**Comment by mjjbell** [comment]
As mentioned in other `osrm-routed` improvements (e.g. #6113), the HTTP server is basically just the example from the Boost docs. So yes, an upgrade would make sense, but it requires someone to invest the time in doing it.

For now, if you need a production-grade HTTP server for OSRM you can:
1. Bind the OSRM lib to such an HTTP server using the C++/Node/Python bindings.
2. Put osrm-routed behind a reverse-proxy that is better suited for handling your networking needs.

**Comment by mjjbell** [comment]
There's also #6411, which i believe is close to the finish line.

**Comment by hy05190134** [comment]
void Connection::start()
{
    TCP_socket.async_read_some(boost::asio::buffer(incoming_data_buffer),
                               boost::bind(&Connection::handle_read,
                                           this->shared_from_this(),
                                           boost::asio::placeholders::error,
                                           boost::asio::placeholders::bytes_transferred));

    if (keep_alive)
    {
        // Ok, we know it is not a first request, as we switched to keepalive
        timer.cancel();
        timer.expires_from_now(boost::posix_time::seconds(keepalive_timeout));
        timer.async_wait(std::bind(
            &Connection::handle_timeout, this->shared_from_this(), std::placeholders::_1));
    }
}

@mjjbell  can you explain why should set async_wait repeatly when next request come in. keep-alive mode, I think the implement of keep-alive is not graceful and not effectable

**Comment by hy05190134** [comment]
@GitBenjamin I have review the support of osrm, I think if you set HTTP 1.0 to  HTTP 1.1 it can work and increase the performance well though it is not the whole feature of HTTP 1.1
