### ISSUE TITLE
Simplifying query results with multiple input points?

### ISSUE THREAD

**Issue by YordanYanakiev** [Project-OSRM/osrm-backend#6679]
Hello.
I have a trajectories with 1000 up to 15.000 input points made from vehicles, which i wanna fit on the closest road - so the best would be if the result is returning just the same amount of point but fit on the closest road.
As well I wish the result to be an array just from these points.

Is there a way to achieve these two goals ?

**Comment by mjjbell** [comment]
The `tracepoints` in the result returned by the [map matching API](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#match-service) should provide what you need.
