### ISSUE TITLE
Add toll attribute in route response

### ISSUE THREAD

**Issue by luca-saggese** [Project-OSRM/osrm-backend#6683]
HI, I would like to have toll attribute information in returned step data to allow me to compute toll cost on Italians highways.

could someone point me to the piece of code to modify?

thanks

**Comment by jcoupey** [comment]
What kind of attribute do you have in mind? AFAICT there is no such thing as a (monetary) cost for toll ways in OSM.

**Comment by danpat** [comment]
With the default config, we do record the boolean `toll` flag, and you can extract it from the API response in the `intersections.classes` object.  Best you can do is determine whether ways traversed are tolled or not, it'll be up to you to figure out how to calculate the toll amount.

**Comment by luca-saggese** [comment]
thanks for all the infos, but I'm unable to get the toll information in intersections.
I've build the latest source and also tested with public server:

curl "https://router.project-osrm.org/route/v1/driving/12.726345,41.997204;7.949142,45.062493?steps=true"

I know ti pass through an highway and that the toll info is available on osm

what I'm missing?

**Comment by luca-saggese** [comment]
Ok it was a strange fault, I've reconstruct the map and now it shows the classes
