### ISSUE TITLE
ref should not necessarily override name

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#67]
one of the well known streets in the center of copenhagen is called Vesterbrogade. officially it's part of the danish road nr 156, but nobody uses that designation. very few will even know about it.

http://www.openstreetmap.org/?lat=55.672907&lon=12.558384&zoom=18&layers=M

but osrm at the moment osrm uses ref instead of name if it's present:

1.	Head on Viktoriagade for 43 m
2.	Turn left on 156 for 36 m                       <--- this is actually Vesterbrogade
3.	You have reached your destination

perhaps it would make sense to use the same names as is rendered on the map?

**Comment by TheMarex** [comment]
Now tracking in https://github.com/Project-OSRM/osrm-backend/issues/1299
