### ISSUE TITLE
routing profile foot.lua results in spurious trails for New Zealand (suspect SH 6)

### ISSUE THREAD

**Issue by tombay** [Project-OSRM/osrm-backend#6701]
# Issue
I have created a dataset using foot.lua as the profile
This is described in the community forum
https://community.openstreetmap.org/t/issues-with-foot-lua-profile/103765
---------------------------------------------------------------------------------------------------------------
The profile is from git source.
Downloaded new-zealand-latest.osm.pbf. And set up two osrm data trees
new-zealand/car
new-zealand/foot
cd car
osrm-extract -p /opt/osrm/car.opt new-zealand-latest.osm.pbf
osrm-partition new-zealand-latest.osrm
osrm-customize new-zealand-latest.osrm
cd …/foot
osrm-extract -p /opt/osrm/foot.opt new-zealand-latest.osm.pbf
osrm-partition new-zealand-latest.osrm
osrm-customize new-zealand-latest.osrm
If i run osrm-routed -a MLD car/new-zealand-latest - the trail draws correctly
If i run osrm-routed -a MLD foot/new-zealand-latest - the trail draws garbage
---------------------------------------------------------------------------------------------------------------
This can be seen here :
https://map.project-osrm.org/?z=14&center=-41.230508%2C173.377562&loc=-41.212480%2C173.382840&loc=-41.210172%2C173.395951&hl=en&alt=0&srv=2

**Comment by danpat** [comment]
The issue is probably related to default access restrictions.  OSM has a wiki page on it here:

https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions

If you look at the tables there, you'll see that different counties have different defaults for different road classes.  The OSRM foot profile was written for one set of rules, and it doesn't do country-by-country differences.

This is absolutely a bug in OSRM, and patches to fix it would be quite welcome.  Honestly, most of the work is probably just in the `.lua` files, enabling/disabling various road classes depending on the country.  You would need to build the routing files with country-level polygon file so that the Lua scripts can know which country the edges are in to change the access rules for the profile you're generating.

https://github.com/Project-OSRM/osrm-backend/issues/6008 is a similar bug report from a couple of years ago.  Obviously, nobody has submitted a patch to fix this yet.  You could be the one!

**Comment by tombay** [comment]
I added trunk into the allowed highway list and now tracks are ok. However I think the solution may not be solvable just through lua files. Looking at the osrm names file (after osrm-extract with the original foot.lua) the trunk entries have been removed. To support multiple polygon areas the data would have to still be there. If polygon areas can be fed Into .lua then it would work, otherwise you need separate extracts per country. Osrm-routed could choose an extract based on polygon. I do have separate extracts for AUS and NZ and choose between them (not in software).  As it is now osrm-routed (and the api library) should report no route.

**Comment by danpat** [comment]
You misunderstand how the feature works.  The trunk roads are removed because OSRM flags them as inaccessible for walking.

Check the wiki page here: https://github.com/Project-OSRM/osrm-backend/wiki/Using-location-dependent-data-in-profiles

It includes an example showing how to obtain country borders in a GeoJSON format, then how to check the current country code (`ISO3166-1:alpha3`) for each OSM way as it is processed.  For some countries, you would _enable_ trunk roads, for other countries, you would disable them.  The emitted routing file would have trunk edges enabled in some places, and disabled in others.

**Comment by tombay** [comment]
Thanks for that Danpat. I did not realize all that functionality was there.
I downloaded the countries.geojson file as suggested. I created a local_motorways.lua file that supports localized settings for motorways and speeds. I modified way_handlers.lua and guidance.lua to check for the existence of localized settings.
My assumption was just (based on the country locale) just remove trunk, trunk_link from the motorway list.
with the speed if we failed the test just try again with trunk or trunk_link.
I tested successfully but have not gone throughj any test suite. (I retired from SD over 10 years ago %-?).
I can attach the files if you wish - but have only tried on NZL. 
Ciao

**Comment by tombay** [comment]
Actually just need the speed.
----------------------------------------
--- /home/tom/Downloads/software/Project-OSRM/osrm-backend/profiles/foot.lua
+++ /usr/local/share/osrm/profiles/foot.lua
@@ -130,6 +130,11 @@
     },
 
     smoothness_speeds = {
+    },
+    
+    uselocationtags = Set
+    {
+        'speeds',
     }
   }
 end
--------------
--- /home/tom/Downloads/software/Project-OSRM/osrm-backend/profiles/lib/way_handlers.lua
+++ /usr/local/share/osrm/profiles/lib/way_handlers.lua
@@ -7,6 +7,7 @@
 local get_turn_lanes = require("lib/guidance").get_turn_lanes
 local set_classification = require("lib/guidance").set_classification
 local get_destination = require("lib/destination").get_destination
+local get_extra_speeds = require("lib/local_motorways").get_extra_speeds
 local Tags = require('lib/tags')
 local Measure = require("lib/measure")
 
@@ -277,10 +278,23 @@
   local key,value,speed = Tags.get_constant_by_key_value(way,profile.speeds)
 
   if speed then
-    -- set speed by way type
     result.forward_speed = speed
     result.backward_speed = speed
-  else
+  else 
+    if profile.uselocationtags.speeds then
+        -- check for location tags to handle trunks 
+        local extra_speeds = get_extra_speeds(way)
+        if extra_speeds then
+            key,value,speed = Tags.get_constant_by_key_value(way,extra_speeds)
+            if speed then
+                -- set speed by way type
+                result.forward_speed = speed
+                result.backward_speed = speed
+            end
+        end
+    end
+  end
+  if not speed then
     -- Set the avg speed on ways that are marked accessible
     if profile.access_tag_whitelist[data.forward_access] then
       result.forward_speed = profile.default_speed
--------------
lib/local_motorways.lua
-- Assigns extra_speeds list based on location tag
--
local Sequence = require('lib/sequence')

local LocalMotorways = {}

local walking_speed = 5

local location_extra_speeds = Sequence
{
  highway = {
      trunk = walking_speed,
      trunk_link = walking_speed
    }
}

local location_speeds = {
	NZL = location_extra_speeds,
}

function LocalMotorways.get_extra_speeds(theway)
    if theway:get_location_tag('ISO3166-1:alpha3') then
	location = theway:get_location_tag('ISO3166-1:alpha3')
        if location_speeds[location] then
            local speeds = {} 
            speeds = location_speeds[location]
            return speeds
        end
    end
    return false    
end
return LocalMotorways

**Comment by tombay** [comment]
Actually just need the speed
[foot.lua.patch.txt](https://github.com/Project-OSRM/osrm-backend/files/12613547/foot.lua.patch.txt)
[way_handlers.lua.patch.txt](https://github.com/Project-OSRM/osrm-backend/files/12613552/way_handlers.lua.patch.txt)
[local_motorways.lua.txt](https://github.com/Project-OSRM/osrm-backend/files/12613562/local_motorways.lua.txt)

**Comment by tombay** [comment]
I think this is probably not the right forum for me to teach myself OSRM programming.
My previous test didn't even check if the highway was a trunk.
I have included my last version which has taken input from the openstreetmap wiki.
I will attach these and close this defect .
[foot.lua.patch.txt](https://github.com/Project-OSRM/osrm-backend/files/12640048/foot.lua.patch.txt)
[foot.lua.patch.txt](https://github.com/Project-OSRM/osrm-backend/files/12640051/foot.lua.patch.txt)
[foot.lua.patch.txt](https://github.com/Project-OSRM/osrm-backend/files/12640052/foot.lua.patch.txt)

[way_handlers.lua.patch.txt](https://github.com/Project-OSRM/osrm-backend/files/12640054/way_handlers.lua.patch.txt)
[bicycle.lua.patch.txt](https://github.com/Project-OSRM/osrm-backend/files/12640056/bicycle.lua.patch.txt)

[local_trunks.lua.txt](https://github.com/Project-OSRM/osrm-backend/files/12640057/local_trunks.lua.txt)

**Comment by tombay** [comment]
workaround in place
