### ISSUE TITLE
Match != working

### ISSUE THREAD

**Issue by adriantabirta** [Project-OSRM/osrm-backend#6714]
# Issue

Hi, 
I am using **osrm** from c++ like: [this](https://github.com/adriantabirta/osrm-backend-real-time/blob/master/osrm-realtime/osrm-match.cpp)

In terminal I run:
```
./osrm-match "resources/osrm/extracted-data/moldova-latest.osrm" 28.8575 47.00556 28.845421 47.063027
```

I get:
```
1 lat: 28.8575 long: 47.00556
2 lat: 28.845421 long: 47.063027
Code: NoMatch
Message: NoMatch
```
I`m trying to get nodeIds for 2 coordinates and osrm.Match says: **NoMatch** but for the same coordinates & [this](https://github.com/adriantabirta/osrm-backend-real-time/blob/master/osrm-realtime/osrm-realtime-routing.cpp) code everything work. In both cases I use **MLD** algorithm

Have no idea what is wrong ...
Please help.

Or

Is there any way to get node is from coordinate?

# Specifications

- Library/dependency versions: latest
- Operating system: Ubuntu 22.0
- Hardware: Cloud

**Comment by danpat** [comment]
Your code is calling `osrm.Match()` - that feature is designed to match a dense GPS trace to the likely path across a road network.  Coordinates need to be fairly close together.

The code you copied from is calling `osrm.Route()` - that will find a path between two coordinates even if they are very far apart.

Here are those two points plotted on a map.

<img width="610" alt="Screenshot 2023-10-13 at 10 11 26 am" src="https://github.com/Project-OSRM/osrm-backend/assets/1892250/1ab6ded7-79da-418c-ab3a-b07285ff2e7a">

This is too far for the matching algorithm.  A more reasonable match request spanning this distance would have a lot more coordinates that would follow the roads you want, like:

<img width="679" alt="Screenshot 2023-10-13 at 10 15 45 am" src="https://github.com/Project-OSRM/osrm-backend/assets/1892250/89962864-b910-4a19-8b03-35fbabf4ae47">

**Comment by adriantabirta** [comment]
@danpat 
Ohhh,
thank you, stupid mistake ...
By the way, isn't the better way to find near node id by calling **osrm.near()**?

Issue can be closed. Sorry
