### ISSUE TITLE
Weird Polyline Result

### ISSUE THREAD

**Issue by camcima** [Project-OSRM/osrm-backend#6715]
# Issue

I'm using a local OSRM docker instance (osrm/osrm-backend:latest) with a uruguay-latest extract downloaded at Geofabrik to create a simple short roundtrip route but there's a weird deviation on the first leg of the route that throws it to a completely wrong path.

This is the route I should get (using OSRM demo site)
![image](https://github.com/Project-OSRM/osrm-backend/assets/1918601/ff183fbf-9427-4cd1-b3ea-ef41d8b4ae22)

This is the route I'm getting.
![image](https://github.com/Project-OSRM/osrm-backend/assets/1918601/fcbbeaed-7dbb-4fa5-9de5-ec872a3dbec6)

# Steps to reproduce

Please provide the steps required to reproduce your problem.
- `osrm-backend` version being used: osrm/osrm-backend:latest docker image (v5.25?)
- OSM extract that was processed: uruguay-latest.osm.pbf (Geofabrik)
- Processing commands (e.g. CH vs MLD processing): mld
- Server queries:
> curl 'http://localhost:5000/route/v1/driving/-56.187188,-34.891312;-56.199562,-34.905812;-56.187188,-34.891312?overview=full'

```json
{"code":"Ok","routes":[{"geometry":"px}sEhb}uILi@DIFCn@XF@RHPq@?M@QAMEKGMKKIEKGm@U_@OwAi@[O]MKAK?I@GBMFKHIJKVUz@I`@]fBCR@RBLHRJPTPJDbA`@lAd@bA`@H@H@F?LCJGBAFK\\_@NOBMNAP?x@DR?TDNBpAf@LFzAl@fA`@|CnAfC`AlFtBnBt@l@TdBr@bAb@h@V\\NTN`@^VTHJFJBH@JBl@?JBH@BBBDBD@H?JAP?hBIbACTBZJbA^bE`B`A`@bCt@bExA^NNLpCjAHpCN~EN`FN~ELbF~AIFnA?LU?Q@y@BI@G@wAl@wAl@iBv@oB|@E@SHSw@}@uDc@UKUOiEM}EQcFM_FOcFMeEAWCg@A[cEeBWKw@WmBu@_EaBq@Ua@MeCaAoCgAmBu@mFuBiCcA}CmAsCgAOGaBq@UIkBu@HYJc@Gy@?M@QAMEKGMKKIEKGm@U_@OwAi@[O]MKAK?I@GBMFKHIJKVUz@I`@]fBCR@RBLHRJPTPJDbA`@lAd@bA`@H@H@F?LCJGBAFKTaASGq@WEGAKR}@","legs":[{"steps":[],"distance":2910.4,"duration":349.5,"summary":"","weight":349.5},{"steps":[],"distance":3035.5,"duration":351.8,"summary":"","weight":351.8}],"distance":5945.9,"duration":701.3,"weight_name":"routability","weight":701.3}],"waypoints":[{"hint":"kFUBgJJVAYBJAAAAMQAAAIAAAABfAAAAJIn0QeS0o0G32lNC-o0dQkkAAAAxAAAAgAAAAF8AAAA4AAAA86Wm_AOY6_3Mpqb80Jnr_QQA_wZ4IBDD","distance":54.854771,"name":"","location":[-56.187405,-34.891773]},{"hint":"2ioBgP___38JAAAAKgAAAA0AAAAAAAAAJlsVQTyNA0LQ6UhBAAAAAAkAAAAqAAAADQAAAAAAAAA4AAAAnXWm_CJh6_12dqb8LGHr_QEATxZ4IBDD","distance":19.859059,"name":"Ciudadela","location":[-56.199779,-34.905822]},{"hint":"kFUBgJJVAYBJAAAAMQAAAIAAAABfAAAAJIn0QeS0o0G32lNC-o0dQkkAAAAxAAAAgAAAAF8AAAA4AAAA86Wm_AOY6_3Mpqb80Jnr_QQA_wZ4IBDD","distance":54.854771,"name":"","location":[-56.187405,-34.891773]}]}
```

If you're reporting an issue with https://map.project-osrm.org, please provide a link to the problematic request.

# Specifications

Please provide details of your development environment.
- Library/dependency versions: Docker
- Operating system: Docker
- Hardware: Docker

**Comment by danpat** [comment]
Make sure you are handling the escaping in the polyline string correctly - there are backticks  and backslashes (`\`) that you need to be careful handling when you copy/paste the string.  Your symptoms of the string becoming slightly offset at some point kind of points to this kind of error - polyline strings are delta encoded, and it seems likely you've dropped a character which messes up all the subsequent delta values.

In the image "this is the route I'm getting" - you didn't say how you actually generated that map.  How did you take the string from the JSON response and pass it to something to render?  I suspect the mistake is in that step.

**Comment by camcima** [comment]
Yes, I've copied and pasted the string from the json response to https://www.freemaptools.com/create-and-plot-encoded-polyline-on-map.htm. I've also tried Google's Polyline Utility (https://developers.google.com/maps/documentation/utilities/polylineutility)  and it shows the same deviation.

![image](https://github.com/Project-OSRM/osrm-backend/assets/1918601/976fec56-2b9a-41bb-afdb-2733a4839105)

**Comment by danpat** [comment]
You can't just copy the value from the JSON and expect it to work - it is a "JSON escaped string" - you need the _unescaped_ string.

Replace all the `\\` with `\` - those are the escape characters in JSON string encoding.  If you do that, you'll see the polyline is correct:

<img width="796" alt="Screenshot 2023-10-13 at 9 46 57 pm" src="https://github.com/Project-OSRM/osrm-backend/assets/1892250/c7a7bc67-90e3-45c5-b01f-05a6f11b7294">

**Comment by camcima** [comment]
You're absolutely right. I've just tried with a geojson output and it displays the route correctly. Thanks a lot for your prompt response @danpat!
