### ISSUE TITLE
Connection timed out problem

### ISSUE THREAD

**Issue by RikyColo** [Project-OSRM/osrm-backend#6719]
# Issue

Hi to everyone!
I would start by saying that I am practically new to this world, so I hope you can help me.
I use OSRM to get distance and duration of all possible pairings of about 80 geographic points.
Since last night I have been getting this error:

TimeoutError: [Errno 110] Connection timed out
The above exception was the direct cause of the following exception:
ConnectTimeoutError                       Traceback (most recent call last)
ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7cf35e82ee90>, 'Connection to router.project-osrm.org timed out. (connect timeout=None)')

This has never happened to me in the last month and a half.
What can I do? 
Thank you very much for your help.

**Comment by frodrigo** [comment]
I guess your are talking about access to the demo server. It is only a demo service. You can run your own service.
