### ISSUE TITLE
Local version reporting nonsense distances

### ISSUE THREAD

**Issue by espoal** [Project-OSRM/osrm-backend#6727]
I'm trying to test OSRM as a distance calculation tool for my project, but I get very strange results. Let's take the distance between Berlin and Hamburg:

`${OSRM_URL}/table/v1/driving/52.52000659999999,13.404954;53.5488282,9.987170299999999?sources=0&destinations=1`

From `http://router.project-osrm.org/` I get: 

```json
{"code":"Ok","destinations":[{"hint":"64AfgKX2zYUAAAAAqwAAAAAAAAAZNQAAAAAAAFe2PUIAAAAABftrRQAAAACrAAAAAAAAABk1AAAVHAAAd8UPA7mangAcFzEDYmSYAAAAbxNI4YXX","distance":243478.706294391,"name":"","location":[51.365239,10.394297]}],"durations":[[850912.5]],"sources":[{"hint":"KL8XiCm_F4gtAAAAAAAAAHgJAAAAAAAAN6NJQQAAAACOTChEAAAAAC0AAAAAAAAAeAkAAAAAAAAVHAAAlIwvAxhLwQBHZCEDGovMABsA_xBI4YXX","distance":129546.521843189,"name":"","location":[53.447828,12.667672]}]}
```

From my local instance I get:

```json
{"code":"Ok","durations":[[1]],"destinations":[{"hint":"BKEGgGGhBoAAAAAAEQAAANEDAADcAAAAAAAAAPjTz0GPzb5EP-WrQwAAAAARAAAA0QMAANwAAABWFgAAG6fHADKZ1gIcFzEDYmSYAEMALw-XTeym","distance":5743920.314725,"name":"Roßfeldstraße","location":[13.084443,47.618354]}],"sources":[{"hint":"BKEGgGGhBoAIAAAAAAAAAL8DAAD3AAAASVVBQQAAAABXYbtEsYjAQwgAAAAAAAAAvwMAAPcAAABWFgAAsafHAI-Z1gJHZCEDGovMAEEAvw2XTeym","distance":5358237.061217,"name":"Roßfeldstraße","location":[13.084593,47.618447]}]}
````

Why is my local instance route me through `Roßfeldstraße`, which is completely out of the way, hence giving me a different result?
Why do I get different distances when trying the online [demo](https://map.project-osrm.org/?z=9&center=53.046167%2C11.725159&loc=53.550341%2C10.000654&loc=52.517037%2C13.388860&hl=en&alt=0&srv=0)?

**Comment by washaqq** [comment]
i have the same issue, 

![farkli sonuclar](https://github.com/Project-OSRM/osrm-backend/assets/16055736/aa1d9149-89e6-4886-b6c9-fc2f895753bc)

these 3 shows different result, for the same input.

**Comment by danpat** [comment]
@espoal Your input coordinates are swapped.  You've provided `<lat>,<lon>` of 52.52000659999999,13.404954 in your request, which is here:

<img width="469" alt="Screenshot 2023-11-03 at 6 51 20 am" src="https://github.com/Project-OSRM/osrm-backend/assets/1892250/f1e47086-1bcf-4632-b940-07aa3fb94403">

On the public server `router.project-osrm.org`, the global map is available, so it's calculating the route from Yemen.

On your map, it appears you've only imported Germany.  OSRM will snap to the "nearest edge", which from your coordinate in the ocean, appears to be 13.084443,47.618354.

**Comment by washaqq** [comment]
> @espoal Your input coordinates are swapped. You've provided `<lat>,<lon>` of 52.52000659999999,13.404954 in your request, which OSRM is interpreting as `<lon>,<lat>` and trying to route from here:
> 
> <img alt="Screenshot 2023-11-03 at 6 51 20 am" width="469" src="https://user-images.githubusercontent.com/1892250/280298242-f1e47086-1bcf-4632-b940-07aa3fb94403.png">
> On the public server `router.project-osrm.org`, the global map is available, so it's calculating the route from Yemen.
> 
> On your map, it appears you've only imported Germany. OSRM will snap to the "nearest edge", which from your coordinate in the ocean, appears to be 13.084443,47.618354 (`<lon>,<lat>`).
> 
> OSRM takes `<lon>,<lat>` order in the request URL. Flip your coordinates around and things should make a lot more sense.

I flipped the numbers, now i am having same result with very slight difference.
i got the numbers from openstreetmap's web site;
![image](https://github.com/Project-OSRM/osrm-backend/assets/16055736/0f066803-cfbb-4fee-ab3d-844c99ead5dc)
it doesnt tell which is lon. and which is lat. so i took them as it is.

it works now. Thank you.

**Comment by espoal** [comment]
I'm writing automatic tests to compare OSRM with other similar products (google maps, GraphHopper, HereMaps, ....) but for now it seems to work also for me. 
We can close the ticket and I will eventually update it / open a new one if I find any major discrepancies in the tests.

Thanks @danpat
