### ISSUE TITLE
Upgrade third party FMT to newer version

### ISSUE THREAD

**Issue by hannesaddec** [Project-OSRM/osrm-backend#6729]
# Issue

Third party extension FMT would need to be upgraded following https://github.com/fmtlib/fmt/commit/1c023c00876abdfd9d0149d73a152675dca72c34 

# Steps to reproduce

NA - 

# Specifications

NA

**Comment by donno** [comment]
It doesn't look like you referred to the right commit. The commit in `1c023c00876abdfd9d0149d73a152675dca72c34`  is an upgrade of Bootstrap (the HTML/CSS/JS package) used within the library's documentation site, so it won't have osrm-backend.

Was there another change in that library that would benefit osrm-backend?

Are you perhaps running some kind of scanning software that picks up bootstrap.min.js and sees that it is using old versions which is raising warning?

**Comment by hannesaddec** [comment]
FMT used an old version of bootstrap which is now fixed - however this in turn means that FMT in osrm-backend would need to be upgraded.  nad yes

**Comment by hannesaddec** [comment]
+1
