### ISSUE TITLE
Fixed coordinate return for any request - API OSRM

### ISSUE THREAD

**Issue by Isabela3Lauene** [Project-OSRM/osrm-backend#6735]
Hello, I am conducting some tests with OSRM. I extracted only a small part of a city in Brazil. However, any request I make returns a single point, as shown in the image below. 
Note that the returned coordinate is different from the coordinates provided in the request. This happens for any coordinate.

![image](https://github.com/Project-OSRM/osrm-backend/assets/123707650/ae235a05-2299-4bb5-9fb8-ec036943bd3e)

Note that the returned coordinate is different from the coordinates provided in the request. This happens for any coordinate.

I am using the MLD (Multi-Level Dijkstra) standard. I performed the extraction using the OSRM-EXTRACT command with the car.lua profile, followed by OSRM-PARTITION and then OSRM-CUSTOMIZE. No error messages were displayed during the extraction of the map.osm.

However, I noticed that there is no file named map.osrm in my extraction directory, and I am unsure if this file should exist.

![image](https://github.com/Project-OSRM/osrm-backend/assets/123707650/6422cafe-b85d-40ea-9b3f-d7cb402d2a24)

When running the osrm-routed command, I am using the following call: osrm-routed --algorithm=MLD map.osrm, and no errors are displayed.

The map in question is relatively small, about 1MB (only one neighborhood).
![image](https://github.com/Project-OSRM/osrm-backend/assets/123707650/619c246c-6c5f-4ab6-a2d6-c13e0243f02a)

Has anyone experienced this type of issue before?

**Comment by danpat** [comment]
<img width="950" alt="Screenshot 2023-11-16 at 11 58 08 am" src="https://github.com/Project-OSRM/osrm-backend/assets/1892250/17d85a93-058b-479a-ac8e-39175e7a4aae">

The coordinate you've supplied (49.9,22.22) is in the middle of Saudi Arabia is that what you meant?  I suspect you've got your coordinates back-to-front, OSRM takes `x,y` or `longitude,latitude` order in the request URL.

OSRM will snap to the nearest point to the input - if you've only generated a small map dataset, and you accidentally flip the coordinates making them very far away, it's then both will probably snap to the same spot on your smaller network, usually some piece that sticks out.

**Comment by Isabela3Lauene** [comment]
Thank you for the response. I actually performed some tests by swapping the positions of longitude and latitude. However, in both attempts, whether it's Lon x Lat or Lat x Lon, the same result is returned.

when i try this same coords in DEMO server i've notice a diference
 
![image](https://github.com/Project-OSRM/osrm-backend/assets/123707650/530ac8d9-f1c7-46b6-a094-85c4fdf51fe6)

 
Demo server (https://router.project-osrm.org/route/v1/driving/22.229214764302533,49.96341591566475;22.23288856896739,49.964410044388174)

**Comment by Isabela3Lauene** [comment]
After doing some tests, I noticed that by using the Google coordinate in the API it was showing some errors, when capturing longitudes and latitudes directly from inside the compiled map file the API worked correctly!

example used: /route/v1/driving/-49.9707073,-22.2335398;-49.9958829,-22.2328408

**Comment by danpat** [comment]
Yes - without the `-` sign, the coordinates you were supplying were on the other side of the planet.
