### ISSUE TITLE
tbb library error on  a M2 macbook

### ISSUE THREAD

**Issue by BryanG13** [Project-OSRM/osrm-backend#6743]
# Issue
Hello everyone

I am attempting to build the latest master branch of osrm-backend. When I try to run the make command I get the following error, and the build is terminated:

In file included from /opt/homebrew/Cellar/tbb/2021.11.0/include/tbb/enumerable_thread_specific.h:17:
/opt/homebrew/Cellar/tbb/2021.11.0/include/tbb/../oneapi/tbb/enumerable_thread_specific.h:310:5: error: '~ets_base' overrides a destructor but is not marked 'override' [-Werror,-Wsuggest-destructor-override]
    ~ets_base() {destroy_key();}
    ^
/opt/homebrew/Cellar/tbb/2021.11.0/include/tbb/../oneapi/tbb/enumerable_thread_specific.h:149:13: note: overridden virtual function is here
    virtual ~ets_base();  // g++ complains if this is not virtual
            ^
/opt/homebrew/Cellar/tbb/2021.11.0/include/tbb/../oneapi/tbb/enumerable_thread_specific.h:871:5: error: '~enumerable_thread_specific' overrides a destructor but is not marked 'override' [-Werror,-Wsuggest-destructor-override]
    ~enumerable_thread_specific() {
    ^
/Users/bryangalarza/osrm-backend/include/extractor/scripting_environment_lua.hpp:108:75: note: in instantiation of template class 'tbb::detail::d1::enumerable_thread_specific<std::unique_ptr<osrm::extractor::LuaScriptingContext>>' requested here
    tbb::enumerable_thread_specific<std::unique_ptr<LuaScriptingContext>> script_contexts;
                                                                          ^
/opt/homebrew/Cellar/tbb/2021.11.0/include/tbb/../oneapi/tbb/enumerable_thread_specific.h:149:13: note: overridden virtual function is here
    virtual ~ets_base();  // g++ complains if this is not virtual
            ^
2 errors generated.
make[2]: *** [CMakeFiles/EXTRACTOR.dir/src/extractor/scripting_environment_lua.cpp.o] Error 1
make[1]: *** [CMakeFiles/EXTRACTOR.dir/all] Error 2
make: *** [all] Error 2

I installed the latest version of libtbb: 
2021.11.0

# Steps to reproduce
- `osrm-backend` current master branch 
- Install the osrm branch on a M2 chip macbook with macOS sonoma 14.1.1
-  clang version 15.0.0 (clang-1500.0.40.1)
-  I had to add add_compile_definitions(_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION)
 and include_directories(path/to/.. /tbb/2021.11.0/include) to cmakelists.txt to fix previous errors

**Comment by DennisOSRM** [comment]
Seems to work with latest master branch. Please reopen in case the issue persists.
