### ISSUE TITLE
Builds an incorrect route

### ISSUE THREAD

**Issue by zarovDeveloper** [Project-OSRM/osrm-backend#6751]
Good time of day. My task is to build a route for pedestrians in Zaryadye Park. I'm creating a query for the foot profile, but it doesn't seem to take into account pedestrian paths. Also, the starting point goes to a completely different place, not the one that I originally set, also with the end point.

Everything works well on the website with the demo version of the map.
I am attaching a screenshot from the demo site, from my site, as well as the request along with the response.

![image](https://github.com/Project-OSRM/osrm-backend/assets/109274113/4f58e5a9-f6cf-4ae0-84c9-cf005aec49ed)
_Photo from demo_

![image](https://github.com/Project-OSRM/osrm-backend/assets/109274113/6a92883e-4137-43f1-96b8-2a9c9a6f4358)
_Photo from my server_

http://router.project-osrm.org/route/v1/hiki/37.625733017921455,55.75171597947999;37.63005673885346,55.75180659978079?geometries=polyline6
_response_

**Comment by zarovDeveloper** [comment]
I realized that by making a request even to foot, it outputs the car route. How can I fix this?

**Comment by jcoupey** [comment]
> making a request even to foot, it outputs the car route

Using several profiles requires to use several OSRM instances. So except if you use some kind of request proxying, the `profile` value in `route/v1/profile/` has no impact at all, only the data preparation steps determine what profile is in use.

My guess is that you're running an OSRM instance with a car profile locally. This is decided when extracting the OSM data for routing: the `osrm-extract` command has a `-p` flag that lets you point to the profile you want to use.
