### ISSUE TITLE
Dynamically load road information

### ISSUE THREAD

**Issue by xiongaaaa** [Project-OSRM/osrm-backend#6752]
How to load dynamic road information into OSRM service?
Such as road congestion, traffic restrictions, road closures and other road information.
Does OSRM support it?

**Comment by jcoupey** [comment]
Anytime you want to do a road geometry change (e.g. updating OSM data), then you need to run the full data preparation pipeline again.

If you want to update routing costs (duration and weight of individual route portions), then you should check https://github.com/Project-OSRM/osrm-backend/wiki/Traffic.

**Comment by xiongaaaa** [comment]
How to obtain the csv file? I see that the .csv file is not generated in OSRM.
Is this csv file imported from outside?

**Comment by jcoupey** [comment]
Yes, in this scenario the csv file has to be generated somehow outside of OSRM. In other words, it answers your original question of _"How to load dynamic road information"_. **Getting** dynamic road information is a different problem altogether.

**Comment by xiongaaaa** [comment]
> Yes, in this scenario the csv file has to be generated somehow outside of OSRM. In other words, it answers your original question of _"How to load dynamic road information"_. **Getting** dynamic road information is a different problem altogether.是的，在这种情况下，csv 文件必须在 OSRM 之外以某种方式生成。换句话说，它回答了您最初提出的“如何加载动态道路信息”的问题。获取动态道路信息完全是另一个问题。

I want to know how to get from_osm_id, to_osm_id and other information

**Comment by jcoupey** [comment]
Technically speaking, the osm ids are identifying consecutive nodes on a way where you want to apply changes, so you'd get them from the OSM data extract you used for OSRM data preparation in the first place.

Now if the real underlying question is how to get speed/traffic information, then AFAICT there is no open datasource for that. A typical approach is to generate this data yourself from GPS traces using the `match` endpoint. Covering this is outside the scope of this ticket/question but you may find many existing GitHub issues discussing this in the current repo.

**Comment by xiongaaaa** [comment]
> Technically speaking, the osm ids are identifying consecutive nodes on a way where you want to apply changes, so you'd get them from the OSM data extract you used for OSRM data preparation in the first place.从技术上讲，osm id 以您想要应用更改的方式识别连续节点，因此您将首先从用于 OSRM 数据准备的 OSM 数据提取中获取它们。
> 
> Now if the real underlying question is how to get speed/traffic information, then AFAICT there is no open datasource for that. A typical approach is to generate this data yourself from GPS traces using the `match` endpoint. Covering this is outside the scope of this ticket/question but you may find many existing GitHub issues discussing this in the current repo.现在，如果真正的潜在问题是如何获取速度/交通信息，那么 AFAICT 就没有开放的数据源。典型的方法是使用 `match` 端点从 GPS 轨迹自行生成此数据。涵盖此内容超出了此票证/问题的范围，但您可能会发现许多现有的 GitHub 问题在当前存储库中讨论此问题。

Regardless of how to obtain speed/traffic information, assume that a certain road is selected and a speed limit of 10 is given.
![1703134938341](https://github.com/Project-OSRM/osrm-backend/assets/88066256/80bf6c76-afd8-48c8-82c9-817d48ac5612)

from_osm_id = 479299959
to_osm_id = 71127148
edge_speed_in_km_h = 10
My updates.csv file is as follows：
479299959,71127148,10
Next is my operation：
osrm-extract  map.osm   -p ../profiles/car.lua
osrm-contract   map.osrm
osrm-routed   map.osrm
At this time, the service starts normally and the http response has result output.
Next import csv

osrm-contract data.osrm --segment-speed-file updates.csv
osrm-routed  data.osrm 
There is no change in the http response information before and after importing csv. Why is this?

**Comment by jcoupey** [comment]
From the traffic wiki page:

> The from/to ids are OSM node IDs that are directly connected. To update the speed for an entire way, you must list each node pair along the way in the CSV file. 

In you case nodes 479299959 and 71127148 are not directly connected. You have to provide updates for all 4 node pairs in between.

**Comment by xiongaaaa** [comment]
> From the traffic wiki page:从交通维基页面：
> 
> > The from/to ids are OSM node IDs that are directly connected. To update the speed for an entire way, you must list each node pair along the way in the CSV file.from/to ID 是直接连接的 OSM 节点 ID。要更新整个路径的速度，必须在 CSV 文件中列出沿途的每个节点对。
> 
> In you case nodes 479299959 and 71127148 are not directly connected. You have to provide updates for all 4 node pairs in between.在这种情况下，节点 479299959 和 71127148 不直接连接。您必须为中间的所有 4 个节点对提供更新。

After an afternoon of hard work, the road speed has been updated.
But now there is a problem. Every time a new csv file is imported to update the road speed, the OSRM service must be restarted to take effect. I think it is similar to the hot update method, without restarting the service, and directly loading it to replace the original service. Do you have other ways to deal with it? ?

**Comment by danpat** [comment]
@xiongaaaa Look at the `osrm-datastore` command - you can load the data into RAM before starting `osrm-routed`.  Then, you can use `osrm-datastore` again to swap the in-memory data without restarting `osrm-routed`.

**Comment by xiongaaaa** [comment]
> @xiongaaaa Look at the `osrm-datastore` command - you can load the data into RAM before starting `osrm-routed`. Then, you can use `osrm-datastore` again to swap the in-memory data without restarting `osrm-routed`.查看 `osrm-datastore` 命令 - 您可以在开始 `osrm-routed` 之前将数据加载到 RAM 中。然后，您可以再次使用 `osrm-datastore` 以交换内存中的数据，而无需重新启动 `osrm-routed` 。

<img width="465" alt="1703210896550" src="https://github.com/Project-OSRM/osrm-backend/assets/88066256/e8c6c3a4-96ca-4632-8a11-ed71f55514ed">
Start the OSRM service for the first time.
<img width="580" alt="1703210914806" src="https://github.com/Project-OSRM/osrm-backend/assets/88066256/8444088c-a58c-4a16-9c36-e3b59f018f35">
load csv.
Executing osrm-datastore map.osrm http response does not change anything.
If you restart the service at this time, the csv data can be updated.

If you continue to execute osrm-routed mao.osrm after osrm-datastore map.osrm
It is equivalent to opening a new OSRM service.
<img width="339" alt="1703211237088" src="https://github.com/Project-OSRM/osrm-backend/assets/88066256/e8df53e8-df88-4056-94b2-4a55630feed8">
If the data is reloaded, the service will not be restarted or a new service will be opened.
Thanks for your answer.

**Comment by jcoupey** [comment]
You need to make `osrm-routed` aware that it has to use data already stored in memory. Check the `--dataset-name` option for both `osrm-routed` and `osrm-datastore`.

**Comment by xiongaaaa** [comment]
> You need to make `osrm-routed` aware that it has to use data already stored in memory. Check the `--dataset-name` option for both `osrm-routed` and `osrm-datastore`.您需要知道 `osrm-routed` 它必须使用已存储在内存中的数据。选中 和 `osrm-routed` `osrm-datastore` 的 `--dataset-name` 选项。

A terminal performs the following operations：
osrm-extract  map.osm -p ../profiles/car.lua
osrm-contract map.osrm
osrm-datastore map.osrm
osrm-routed  --algorithm=MLD   map.osrm
At this point, the OSRM service is started and can run normally.

The content format of updates.csv is as follows:
2351948792,3492915813,150
3492915813,2351948792,150
10080193916,3492915811,150
3492915811,10080193916,150
2823641865,3492913956,150
3492913956,2823641865,150
2823641868,2823641866,150
2823641866,2823641868,150
2823641864,2823641865,150
2823641865,2823641864,150
3492913956,3492913957,150
3492913957,3492913956,150
3492915804,2823641868,150
2823641868,3492915804,150
............
............
Modify all speed values in updates.csv to 80.

Now I perform the following operations in terminal B:
osrm-partition  map.osrm
osrm-contract  map.osrm
osrm-customize map.osrm  --segment-speed-file updates.csv
osrm-routed --shared-memory=on

There are 2 OSRM services at this time.

lsof -i :5000
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
osrm-rout 13701  hei   10u  IPv4 197947      0t0  TCP *:5000 (LISTEN)
osrm-rout 13761  hei   11u  IPv4 194411      0t0  TCP *:5000 (LISTEN)

The results returned in the refresh http api response are sometimes different, but I think my above operation is a bit incorrect, but I don't know how to reload the data without restarting the OSRM service or opening more services.

**Comment by danpat** [comment]
You have misunderstood the sequence.  It is more like:

Do this sequence once:
```
osrm-extract map.osm -p ../profiles/car.lua
osrm-partition map.osrm
osrm-customize map.osrm --segment-speed-file updates.csv
osrm-datastore map.osrm
osrm-routed --algorithm=MLD -s
```

Then repeat this sequence over and over:
```
osrm-customize map.osrm --segment-speed-file updates.csv
osrm-datastore map.osrm
```

**Comment by salarnz** [comment]
Hi
@xiongaaaa  , @danpat 
i want to create traffic csv file . but i dont how to start! 
i have many gps trace records. 

can you help me in :
1 . how can i get node ids
2 . more important , how can i find the speed between two nodes?

Ragards

**Comment by DennisOSRM** [comment]
You can start by matching the traces against the road network. Check the 'match' service. 

If you don't mind me asking, how much is many traces?

**Comment by salarnz** [comment]
@DennisOSRM thanks for your reply . i`ll check the match service .
Actually we are a fleet management system provider in Iran and we have gps traces data for about 10 years.

at first step i want to make traffic file for Tehran City.

**Comment by salarnz** [comment]
I have test the match service with 2 coordinates : 

https://router.project-osrm.org/match/v1/driving/51.4233083,35.619995;51.4334733,35.6263249?overview=full&radiuses=10;10

and I received this reply : 

<?xml version="1.0" encoding="UTF-8" ?>
<code>Ok</code>
<matchings>
    <confidence>0.983626978</confidence>
    <geometry>w_lxE}rzxHOS{AmByAyBy@gAqGiJmBkDaBsCyFsLqBeFuAyDy@yBUo@</geometry>
    <legs>
        <summary></summary>
        <weight>58.1</weight>
        <duration>58.1</duration>
        <distance>1161.9</distance>
    </legs>
    <weight_name>routability</weight_name>
    <weight>58.1</weight>
    <duration>58.1</duration>
    <distance>1161.9</distance>
</matchings>
<tracepoints>
    <waypoint_index>0</waypoint_index>
    <matchings_index>0</matchings_index>
    <alternatives_count>0</alternatives_count>
    <hint>Uipegf___38dAAAAJAAAACkBAABJAAAA5eVqQuvWR0EWiBZEMpcRQx0AAAAkAAAAKQEAAEkAAACnBgEAd6gQA3mEHwJMqBADm4QfAgcAzwKqMhJP</hint>
    <distance>5.422565785</distance>
    <name>بزرگراه آزادگان</name>
    <location>51.423351</location>
    <location>35.619961</location>
</tracepoints>
<tracepoints>
    <waypoint_index>1</waypoint_index>
    <matchings_index>0</matchings_index>
    <alternatives_count>3</alternatives_count>
    <hint>tZ32g____38MAAAAIQAAADEBAADTAQAApcLIQWHgIkLmghhEsNtpRAwAAAAhAAAAMQEAANMBAACnBgEAFNAQAzidHwIB0BADVZ0fAgUA7wOqMhJP</hint>
    <distance>3.649039108</distance>
    <name>بزرگراه آزادگان</name>
    <location>51.433492</location>
    <location>35.626296</location>
</tracepoints>

Suppose I ran this service using 100 GPS points on the route of a car and got this output. Now what can I do with it to achieve my goal??(trrafic csv file )


Regards

**Comment by salarnz** [comment]
I have test match service with two points  A and B 
this point are from a gps trace data.

https://router.project-osrm.org/match/v1/driving/51.5233831107616,35.7413930998304;51.511649787426,35.7271005959249?overview=full&annotations=nodes&radiuses=10;10

and I received this out put : 

```
<?xml version="1.0" encoding="UTF-8" ?>
<code>Ok</code>
<matchings>
    <confidence>0.973130557</confidence>
    <geometry>qvcyEmdnyHjIfFp@^lP~J`FzCvCfBt@`@LFRJdF~CvGfE|BdBt@h@hBrATLTRrI`Hx@p@p@t@T\^l@Xl@Tj@Tt@Px@PjABV</geometry>
    <legs>
        <summary></summary>
        <weight>113.5</weight>
        <duration>113.5</duration>
        <annotation>
            <nodes>5816073588</nodes>
            <nodes>311215775</nodes>
            <nodes>723977508</nodes>
            <nodes>723977525</nodes>
            <nodes>1638071660</nodes>
            <nodes>311463636</nodes>
            <nodes>32052508</nodes>
            <nodes>11118259585</nodes>
            <nodes>3837252468</nodes>
            <nodes>32052368</nodes>
            <nodes>1638071525</nodes>
            <nodes>723977590</nodes>
            <nodes>1638071490</nodes>
            <nodes>3837252463</nodes>
            <nodes>206102813</nodes>
            <nodes>4430830311</nodes>
            <nodes>436130534</nodes>
            <nodes>4289090930</nodes>
            <nodes>6799633750</nodes>
            <nodes>206102806</nodes>
            <nodes>1638071320</nodes>
            <nodes>428643785</nodes>
            <nodes>1638071311</nodes>
            <nodes>206102819</nodes>
            <nodes>6799633753</nodes>
            <nodes>206102820</nodes>
            <nodes>1638071297</nodes>
        </annotation>
        <distance>1940.3</distance>
    </legs>
    <weight_name>routability</weight_name>
    <weight>113.5</weight>
    <duration>113.5</duration>
    <distance>1940.3</distance>
</matchings>
<tracepoints>
    <waypoint_index>0</waypoint_index>
    <matchings_index>0</matchings_index>
    <alternatives_count>0</alternatives_count>
    <hint>ho_ugP___38PAAAAhwAAAKYAAAAAAAAA9G7aQaOSVENL6JNDAAAAAA8AAACHAAAApgAAAAAAAACnBgEAZi8SA7xeIQI3LxID0V4hAgEAHw2qMhJP</hint>
    <distance>4.848875043</distance>
    <name>bagheri</name>
    <location>51.52343</location>
    <location>35.741372</location>
</tracepoints>
<tracepoints>
    <waypoint_index>1</waypoint_index>
    <matchings_index>0</matchings_index>
    <alternatives_count>2</alternatives_count>
    <hint>boVngf___38GAAAAJgAAAKcAAAAAAAAA_VEoQQFlP0KY74JDAAAAAAYAAAAmAAAApwAAAAAAAACnBgEAZQESA-wmIQJiARID_SYhAgkAXxCqMhJP</hint>
    <distance>1.905645632</distance>
    <name>bagheri</name>
    <location>51.511653</location>
    <location>35.727084</location>
</tracepoints>
```
now I know that with match service I can get continuous nodes between point A and B and I must use this nodes in my csv file like this : 
node1 , node 2 , speed in km/h
node2 , node 3 , speed in km/h
node3 , node4 , speed in km/h
.
.
until last node. Am I right so far? if yes , now how can I calculate speed? with gps average speed from Point A to Point B ?

Regards
