### ISSUE TITLE
How to Configure OSRM for Multiple Countries in a Single Path?

### ISSUE THREAD

**Issue by GuillaumeDorschner** [Project-OSRM/osrm-backend#6755]
Hello,

I have successfully set up individual paths in Berlin and France following the provided examples. These work flawlessly for single-country/city scenarios. However, I don't know how to configure a multi-country path encompassing both France and Germany. Do all the for all country/city. Maybe
- download
- extract
- osrm-partition
- osrm-customize

Next should be...
```bash
docker run -t -i -p 5000:5000 -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-routed --algorithm mld /data/*-latest.osrm
```

My question is, how can I modify this command to support a multi-country configuration?
![OSRM Backend Example](https://github.com/Project-OSRM/osrm-backend/assets/44686652/fb7f1d0c-c747-42c7-aa73-fc958aa5cc49)

Thank you in advance for your assistance!

**Comment by nilsnolde** [comment]
Look at osmium: https://docs.osmcode.org/osmium/latest/osmium-merge.html. Be careful with merging stuff from Geofabrik though (or any other sources). Should be mostly fine for OSRM routing purposes, but e.g. relations will not be border-complete.

Better way to go: download Europe and extract from it whatever you want: https://docs.osmcode.org/osmium/latest/osmium-extract.html.
