### ISSUE TITLE
OSRM not Compatible Version

### ISSUE THREAD

**Issue by farathza** [Project-OSRM/osrm-backend#6764]
So I tried to run 
sudo docker run -t -i -p 5000:5000 -v "${PWD}:/data" ghcr.io/project-osrm/osrm-backend osrm-routed --algorithm mld /data/java-latest.osrm
with java-latest.osrm but it seems it can't be run by current version, is there any solution?
![Screenshot from 2024-01-08 01-43-32](https://github.com/Project-OSRM/osrm-backend/assets/155912549/c7362970-6907-4244-b9de-1a7e74d71a5e)

**Comment by nilsnolde** [comment]
You’ll need to re-build the graph with the newer OSRM version

**Comment by nilsnolde** [comment]
Or use the same one the graph was built with of course
