### ISSUE TITLE
Docker not up to date

### ISSUE THREAD

**Issue by k-koehler** [Project-OSRM/osrm-backend#6767]
Latest docker tag as per https://github.com/project-osrm/osrm-backend/pkgs/container/osrm-backend is 5.27.1, but latest version when building from source is 5.28.0.

**Comment by danpat** [comment]
There are only docker images for tagged releases.  The 5.28.0 version specifier in the `master` branch is preparation for the next release - there is no `5.28.0` git tag, and no 5.28.0 release has been made.

We should probably make it `5.28.0-unreleased` or something in `master` to avoid this confusion.

**Comment by xSAVIKx** [comment]
Hey @danpat thx for the update. Are there any plans to do the 5.28.0 release any time soon? Or maybe there's some roadmap or timeline in mind?

Highly appreciate all the efforts and the project itself :pray:

**Comment by danpat** [comment]
The project is basically in an idle/hibernating state.  New releases get made on a "when we feel like it and have time" basis.
