### ISSUE TITLE
Can OSRM force snap to road?

### ISSUE THREAD

**Issue by NeboCode** [Project-OSRM/osrm-backend#6769]
![image](https://github.com/Project-OSRM/osrm-backend/assets/17943735/042cac03-f322-450e-a143-05d14edfffac)

Hello,

Is there anything I could do to get OSRM to output coordinates which closely follow roads?
Right now, it does some sort of lazy aggregating, if point A and B are far away, it's likely to just output coordinates which are at a higher distance apart instead of snapping to the road, example on the following image:

![image](https://github.com/Project-OSRM/osrm-backend/assets/17943735/7af54fd2-7fa1-45b4-8df3-10c12ca8e616)

**Comment by NeboCode** [comment]
`?geometries=geojson&steps=true&overview=full` fixed it in the URL params.

**Comment by danpat** [comment]
For future readers - by default, OSRM returns a simplified overview geometry.  The purpose of this is to reduce the API response size if you're rendering a route line on a zoomed-out map (much of the detail isn't visible until you zoom in).

If you require full resolution geometry, then either `overview=full`, or `steps=true` will add full geometry detail to the API response (in the case of `steps=true`, you would need to look at the `step` geometry property, as the overview would still be simplified by default).

**Comment by NeboCode** [comment]
I was writing a more detailed answer as well but got caught up at work before I could finish writing it.
Thanks for elaborating, @danpat .
