### ISSUE TITLE
why not osrm's file.index load with mmap function rather directly copy into memory

### ISSUE THREAD

**Issue by hy05190134** [Project-OSRM/osrm-backend#6771]

**Comment by danpat** [comment]
@hy05190134 You are welcome to make a pull request for that!

**Comment by hy05190134** [comment]
@danpat  we find that if we just use mmap with .indexfile, it will make disk I/O when started with a lot of requests, so we use. preheat method to product page fault activity, later I will make a pull request for that

**Comment by hy05190134** [comment]
@danpat https://github.com/Project-OSRM/osrm-backend/pull/6781/commits/da70b989324f635c0124401ca6d0d52a038aacdf
