### ISSUE TITLE
The leaf node of R-tree , a file named .osrm.fileindex, was loaded with mmap function rather directly copy into memory

### ISSUE THREAD

**Issue by CodeExplorerQuantumScripter** [Project-OSRM/osrm-backend#6772]
Sorry to interrupt, there is a question confusing me a lot. In the engine of osrm, R-tree can convert a true location node to a nearest edge based node, which is relying on shortest distance search.

**Comment by CodeExplorerQuantumScripter** [comment]
The R-tree is composed of two part, tree node saved in .osrm.ramIndex about 22M and leaf node saved in .osrm.fileIndex about 5G. Why .osrm.fileIndex of R-tree was loaded by mmap way when startup parameter without ‘--mmap’.

**Comment by CodeExplorerQuantumScripter** [comment]
Sincerely appreciate for your help

**Comment by hy05190134** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/6781
