### ISSUE TITLE
How to read the contents of .osrm files

### ISSUE THREAD

**Issue by Richard908** [Project-OSRM/osrm-backend#6775]
I'm in the testing phase and I'd like to check the content of the .osrm files generated with the osrm-extract command. 
Is there a way of doing this?

**Comment by jcoupey** [comment]
The osrm files are "just" serialized blobs of binary stuff so messing with them would be pretty hardcore... For debugging purposes, you can use the [test lua script](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/test.lua) on a per-way basis, or the tile endpoint with the [debug frontend](https://github.com/Project-OSRM/osrm-frontend/#changing-backends).

**Comment by Richard908** [comment]
Thank you for your reply. I'm going to continue by using the [test lua script](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/test.lua).
