### ISSUE TITLE
fancy ferry routing over the med sea with bicycle profile 

### ISSUE THREAD

**Issue by hannesaddec** [Project-OSRM/osrm-backend#6782]
# Issue

Make a bicycle route from Spain to Italy goes fancy via ferries over the mediterrean sea 
see https://map.project-osrm.org/?z=7&center=42.386951%2C6.042480&loc=40.446947%2C-0.175781&loc=42.098222%2C12.260742&hl=en&alt=0&srv=1

# Steps to reproduce
go to https://map.project-osrm.org and choose a spanish and Italian location - see link above. 
For sure someone can enable exclusion of ferries in the lua file  https://github.com/Project-OSRM/osrm-backend/blob/31e31a63d062fb804f5f4695ed3036ca7a269ead/profiles/bicycle.lua#L208 but I doubt that is really the intention.. 

The reason is that a ferry connection is faster than a bicycle land connection

**Comment by jcoupey** [comment]
> The reason is that a ferry connection is faster than a bicycle land connection

Looking at the example route you share, this sounds like a fair assumption. In which case this behavior is more of a feature than a bug.

If the plan is to avoid ferry routes altogether in output, this can indeed be done using exclusions, or even better yet by disabling ferry routes at the extract step on your custom instance.

**Comment by hannesaddec** [comment]
we have a "feature" ! - the workaround would be to add addional land based intermediate stops....
