### ISSUE TITLE
Maxheight for cars is still too high

### ISSUE THREAD

**Issue by trigpoint** [Project-OSRM/osrm-backend#6786]
Should SUVs be considered normal as a 2m height restriction causes unnecessary restrictions on routing for normal cars.
Eurotunnel has two routes through it teminals for passenger vehicles.

The trains are divided into two sections, a high vehicle section and a section for standard cars with a height limit of 1.85m. OSRM is unable to follow this route as car.lua has a maximum height of 2m. SUVs are carried in higher carriages at a higher fare.

The issue of car.lua also causes issues here https://map.project-osrm.org/?z=17&center=52.616433%2C-2.442065&loc=52.615993%2C-2.441604&loc=52.615302%2C-2.442162&hl=en&alt=0&srv=0

That one is marginal as 6'6" is only marginally under 2m.

https://www.geograph.org.uk/photo/4893893

Height restrictions of 6ft/1.8m are not uncommon on the entrance to car parks.

Should normal cars be restricted to places where SUVs can go?

**Comment by frodrigo** [comment]
I think you are right about the size of car and SUV.

The point is more a SUV is still a car ? If yes (and I think so), we cannot send SUV to not passable locations.
