### ISSUE TITLE
osrm-backend-5.27.1 not compiling on Sonoma14.2 on MacBook Air

### ISSUE THREAD

**Issue by 1ashishdixit** [Project-OSRM/osrm-backend#6791]
# Issue

I have been trying for last couple of days for OSRM to compile on my MacBook Air. I have tried everything that is available online, including downloading OSRM from homebrew https://formulae.brew.sh/formula/osrm-backend, as well as downloading OSRM from the source archives .

# Steps to reproduce
wget https://github.com/Project-OSRM/osrm-backend/archive/v5.27.1.tar.gz
tar -xzf v5.27.1.tar.gz
cd osrm-backend-5.27.1
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
At this stage I get following errors:
[  0%] Building CXX object CMakeFiles/UTIL.dir/src/util/coordinate_calculation.cpp.o
/opt/homebrew/Cellar/osrm-backend-5.27.1/src/util/coordinate_calculation.cpp:332:5: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
    std::find_if(std::begin(lhs), std::end(lhs), compute_minimum_distance_in_rhs);
    ^~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/homebrew/Cellar/osrm-backend-5.27.1/src/util/coordinate_calculation.cpp:1:
/opt/homebrew/Cellar/osrm-backend-5.27.1/include/util/coordinate_calculation.hpp:209:5: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
    std::adjacent_find(begin, end, compute_minimum_distance);
    ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/osrm-backend-5.27.1/src/util/coordinate_calculation.cpp:328:35: note: in instantiation of function template specialization 'osrm::util::coordinate_calculation::findClosestDistance<std::__wrap_iter<const osrm::util::Coordinate *>>' requested here
            std::min(current_min, findClosestDistance(coordinate, rhs.begin(), rhs.end()));
                                  ^
2 errors generated.
make[2]: *** [CMakeFiles/UTIL.dir/src/util/coordinate_calculation.cpp.o] Error 1
make[1]: *** [CMakeFiles/UTIL.dir/all] Error 2
make: *** [all] Error 2

# Specifications
- Downloaded all the dependencies for Mac OS: 
brew install boost git cmake libzip libxml2 lua tbb ccache pkg-config
brew install GDAL
- Operating system: Sonoma 14.1
- Hardware: MacBook Air

Please help me. I am stuck.

**Comment by nilsnolde** [comment]
> /opt/homebrew/Cellar/osrm-backend-5.27.1/src/util/coordinate_calculation.cpp:332:5

smth is wrong with your build (assuming you're not really building from /opt/homebrew). I'd remove the brew version and try again

**Comment by 1ashishdixit** [comment]
I even downloaded v5.27.0 in /Users/project/code directory. Same 2 errors as before:
error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
    std::find_if(std::begin(lhs), std::end(lhs), compute_minimum_distance_in_rhs);

: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
    std::adjacent_find(begin, end, compute_minimum_distance);
    ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by 1ashishdixit** [comment]
Any suggestions anyone?

**Comment by SiarheiFedartsou** [comment]
These errors are not actually errors, but warnings treated as errors. We treat all warnings as errors:
https://github.com/Project-OSRM/osrm-backend/blob/31e31a63d062fb804f5f4695ed3036ca7a269ead/cmake/warnings.cmake#L52
and basically in newer version of compiler new warnings were added… Ideally we should have an option to disable it, but I think as a workaround you can:
- comment this line above
- pass flags to disable warnings (can be done via CXXFLAGS env variable)

**Comment by 1ashishdixit** [comment]
Can someone help me please?

**Comment by 1ashishdixit** [comment]
After lot of research I was able to fix my problems, This thread can be closed.

In the "Build Phases" tab of the Xcode target settings, expand the "Link Binary with Libraries" section.
Click the "+" button and select the library you want to link against from the list. I added following libraries here:
libosrm.a, libboost_iostream.a, libboost_filesystem.a, libboost_thread-mt.a (please note that the libboost files were at /opt/homebrew/Cellar/boost/1.84.0/lib/ . I was unable to add the file from the XCode, so i just copied them to my libosrm/build folder and copied from there)

After that,  in XCode Project navigator on the left, drag these 4 files from under Frameworks and copy under the files which call libOSRM. And Voila - it ran!
