### ISSUE TITLE
OSRM Conda package on conda-forge?

### ISSUE THREAD

**Issue by OliverSchmitz** [Project-OSRM/osrm-backend#6793]
Most of the users of our software use the Conda package manager to install it. For some research projects we additionally use OSRM, and it would be convenient if that can be installed via Conda as well for an easy setup. Eventually I'd like to use the Python bindings of OSRM for route finding.
Does someone of your team know of anybody working on a Conda package for OSRM? Otherwise I'll give it a try and hope that you are willing to support...

**Comment by frodrigo** [comment]
I think you question is for this project, not directly for the OSRM project.

https://github.com/ustroetz/python-osrm
