### ISSUE TITLE
zoomed map(s) in printing window (feature request)

### ISSUE THREAD

**Issue by ConnyOnny** [Project-OSRM/osrm-backend#680]
For printing, only having one map showing the whole route is not very helpful. Instead one should have arbitrarily many maps with selectable clipping.
Then you could also make the route description clickable and on click insert a map showing one dedicated map for the clicked turn (of course still alterable as the other maps are).

**Comment by daniel-j-h** [comment]
The frontend rewrite is here: https://github.com/Project-OSRM/osrm-frontend-v2.
Please open a ticket there for feature requests.
