### ISSUE TITLE
missing turn instructions (shallow curves without key:turn/key:turn:lanes)

### ISSUE THREAD

**Issue by osmned** [Project-OSRM/osrm-backend#682]
In this situation: http://map.project-osrm.org/?hl=en&loc=48.174660,16.331610&loc=48.173400,16.329780&z=18&center=48.173647,16.329262&alt=0&df=0&re=0&ly=588398340

OSRM is not showing the turn left. Can this be improved?

**Comment by TheMarex** [comment]
Closing in favour of https://github.com/Project-OSRM/osrm-backend/issues/1251
