### ISSUE TITLE
OSRM-BACKEND ON  CENTOS9 / ALMALINUX  9

### ISSUE THREAD

**Issue by tomastn14** [Project-OSRM/osrm-backend#6849]
Hello, I am trying to install osrm-backend on AlmaLinux 9. In its repositories it comes with boost1.78 and compiler gcc-toolset-12 and gcc-toolset-13. I have tried compiling osrm-backend with both, and I have even compiled gcc 9 to try to compile osrm but it doesn't work either.

Does anyone have any ideas?

**Comment by DennisOSRM** [comment]
We'd need a bit more details on what actually failed.
