### ISSUE TITLE
Unknown instruction

### ISSUE THREAD

**Issue by svenluzar** [Project-OSRM/osrm-backend#685]
With the bicycle profile you get sometimes an unknown instruction. It's a bug, isn't it?

Here are three examples:

![bildschirmfoto 2013-07-30 um 11 54 26](https://f.cloud.github.com/assets/695812/877839/5920f4c4-f8fe-11e2-9e08-d515f8181af2.png)

![bildschirmfoto 2013-07-30 um 12 09 14](https://f.cloud.github.com/assets/695812/877918/2d825f36-f900-11e2-9c4d-f47d7cbfd14e.png)

![bildschirmfoto 2013-07-30 um 12 10 42](https://f.cloud.github.com/assets/695812/877923/56d4173a-f900-11e2-83d3-af563988a31c.png)

Feel free to test the bicycle profile at

* http://osrm.naviki.org/main.html

As a warning to you: It's only an experimental installation, preprocessed with a dataset of Europe and the profile bicycle.lua.

**Comment by TheMarex** [comment]
Outdated.
