### ISSUE TITLE
Docker with alpine (once again)

### ISSUE THREAD

**Issue by knowname** [Project-OSRM/osrm-backend#6956]
# Feature
I´d like to add a Dockerfile using alpine once again..

I created a second Dockerfile `Dockerfile-alpine` using alpine:3.20.0 as base image, see https://github.com/knowname/osrm-backend/commit/61154d656ee93f39cca946fb46410117dab87437

When testing it, I noticed a huge performance penalty, which seemed to have come from the  `malloc` command of the `musl` library. As suggested [here](https://www.linkedin.com/pulse/testing-alternative-c-memory-allocators-pt-2-musl-mystery-gomes) I switched to Microsofts mimalloc which is easily installable in Alpine.
This seems to do the trick, as using mimalloc in my test import of a small extract only needs 1/3 of the time.

Does anyone know of other obstacles regarding osrm with alpine I should know?
Are you interested in a PR?

**Comment by SiarheiFedartsou** [comment]
Hey @knowname 

> Are you interested in a PR?

Yes, definitely, I would be happy to review it :)

**Comment by SiarheiFedartsou** [comment]
Closing as done.
