### ISSUE TITLE
Wrong results with nearest service

### ISSUE THREAD

**Issue by icantspake** [Project-OSRM/osrm-backend#6980]
# Issue
When I try to obtain the nearest point in the street network to some locations, the API returns a point in the middle of nowhere. This is affecting the Table service too, as I can't correctly compute the driving distance between some points in a set.

# Steps to reproduce
Some of the problematic locations:
- (43.46165, -3.82461) is in a street in the middle of Santander (Spain); I obtain the coordinates (41.385842, -1.87573), which is in the countryside 315km away: https://router.project-osrm.org/nearest/v1/driving/43.46165,-3.82461
- (40.96877, -5.65997) is in the middle of Salamanca (Spain); I obtain the coordinates (39.820657, -5.306316), which is in the countryside 133km from the original location: https://router.project-osrm.org/nearest/v1/driving/40.96877,-5.65997
- (43.54844, -5.92352) is in Avilés (Spain); I obtain the coordinates (39.846307, -5.223144) which is in the countryside 417km from the original location: https://router.project-osrm.org/nearest/v1/driving/43.54844,-5.92352

# Screenshots
1st
![Captura2](https://github.com/Project-OSRM/osrm-backend/assets/124310363/6ce03ea9-a416-4d94-9462-3f8fb1c0fa81)

2nd
![Captura3](https://github.com/Project-OSRM/osrm-backend/assets/124310363/396be536-8780-4e4f-b800-2d0e720bdc9a)

3rd
![Captura4](https://github.com/Project-OSRM/osrm-backend/assets/124310363/85473044-3cc3-44b8-9b6f-e9797a97f6d4)

**Comment by jcoupey** [comment]
>  (43.46165, -3.82461) is in a street in the middle of Santander (Spain); I obtain the coordinates (41.385842, -1.87573), which is in the countryside 315km away

The 315km distance in itself hints at something wrong. You're simply using lat,lon instead of lon,lat (expected order in OSRM API). The coordinate you supply is somewhere in the sea west of Africa and the snapped location is in Kenya.

**Comment by icantspake** [comment]
Oh, how stupid of me! I mislabelled longitud and latitude in my table and it was driving me mad. Thank you so much!
