### ISSUE TITLE
Improve route_name heuristik

### ISSUE THREAD

**Issue by DennisSchiefer** [Project-OSRM/osrm-backend#699]
When adding a via node to a route, route_name does not always return the correct street names.

If I remember correctly, at some point in the past it was considered to return the street names beneath all markers in this way and not just of the start and end marker. Maybe the problem can be resolved by looking in that direction.

**Comment by TheMarex** [comment]
Updated the title. This a not really a bug, but the heuristic could probably be improved to always include the "relevant" streets.

**Comment by MoKob** [comment]
Not really a guidance issue. This is simply an API thing, presented in the route overview.

**Comment by MoKob** [comment]
With recent fixes, the API returns the two longest road segments. I am considering the issue resolved.
