### ISSUE TITLE
osrm file issue

### ISSUE THREAD

**Issue by sjkeerthi** [Project-OSRM/osrm-backend#7018]
I use osrm-backend 5.26.0 to generate osm.pbf to osrm when I tried this on 5.27.1 to convert I could not able to get the osrm file after I read this issue as refer https://github.com/Project-OSRM/osrm-backend/pull/6354.

But since as they mention no need of osrm without that when I tried to after my osrm-extract /  osrm-partition / osrm-customize
when I try to start the osrm-route I could not able to start it since we use the older version of osrm 5.26.0 we used to run as 

docker run -d --name osrm -v "/data/osrm:/data" -p 5000:5000 osrm-backend:5.26.0 osrm-routed -a MLD /data/gb_ireland.osrm

in the new version there is no clear doc how to start if I want to upgrade 5.27.1 any doc is there a way to generate osrm using or without osrm on 5.27.1

**Comment by jcoupey** [comment]
With 5.27.1, you can still run the same command using the `gb_ireland.osrm` file. For backward compatibility it works even if the file is not generated anymore. You can also simply use `gb_ireland` (no extension) as input to `osrm-routed`.
