### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by magmablinker** [Project-OSRM/osrm-backend#7028]
I was wondering, why have there been no new releases since late 2022? Are there any plans to make a new release?

**Comment by SiarheiFedartsou** [comment]
Hey! Unfortunately there are not that many active contributors around… It is something I keep in mind to do at some point in the future. But the thing is that at the moment it is even hard to get a review for PRs…

**Comment by magmablinker** [comment]
> Hey! Unfortunately there are not that many active contributors around… It is something I keep in mind to do at some point in the future. But the thing is that at the moment it is even hard to get a review for PRs…

Alright thank you for that information. I hope that you will be able to sort things out

**Comment by jcoupey** [comment]
See also #6747.
