### ISSUE TITLE
Allow export of the polyline's  nodes' coordinates

### ISSUE THREAD

**Issue by jidanni** [Project-OSRM/osrm-backend#7031]
In https://github.com/openstreetmap/openstreetmap-website/issues/5224
I mention how important it is to allow users to export routes,
instead of needing to pass internal browser strings to polyline decoders.

**Comment by jcoupey** [comment]
There is nothing actionable here as far as OSRM is concerned as it is already possible to get the geometry in geojson. See `geometries` option in [route service](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#route-service).
