### ISSUE TITLE
Excludable unpaved

### ISSUE THREAD

**Issue by lislainestachowoski** [Project-OSRM/osrm-backend#7051]
Hello everybody!

I need to add _exclude=unpaved_ in the OSRM endpoint request .

For this, I added in my car.lua:

`classes = Sequence {
        'toll', 'motorway', 'ferry', 'restricted', 'tunnel', 'unpaved'
    },
excludable = Sequence {
        Set {'toll'},
        Set {'motorway'},
        Set {'ferry'},
        Set {'unpaved'}
    },`

But, it's still returns 

`{
    "message": "Exclude flag combination is not supported.",
    "code": "InvalidValue"
}`

Can anyone help me?
Is it possible?

**Comment by jcoupey** [comment]
Closing in favor of #7052.
