### ISSUE TITLE
Timeout Error for Car Routing Endpoint

### ISSUE THREAD

**Issue by abdalwhabDrovox** [Project-OSRM/osrm-backend#7055]
Hello,

I am experiencing a timeout error when trying to use the car routing endpoint:

Endpoint:

https://routing.openstreetmap.de/routed-car/route/v1/driving/47.254261560738094,27.420104833223093;47.96630859375001,26.13571361317392?overview=false&alternatives=true&steps=true
The request fails with a timeout, while the bike routing endpoint works perfectly fine with the same coordinates:

Working Endpoint:

https://routing.openstreetmap.de/routed-bike/route/v1/driving/47.254261560738094,27.420104833223093;47.96630859375001,26.13571361317392?overview=false&alternatives=true&steps=true
Could you please investigate this issue? It seems that there might be a problem with the car routing service.

Thank you!

**Comment by tombay** [comment]
Works now %-)

**Comment by abdalwhabDrovox** [comment]
There was an issue, but it has been resolved. The cause was related to (mention the specific cause here if known)
