### ISSUE TITLE
Illegal turn 

### ISSUE THREAD

**Issue by iaroslavzif** [Project-OSRM/osrm-backend#7056]
Hello!

Why OSRM cannot process the illegal/dangerous turn and exclude them? 

The following turn should not be offered. Looks like a very often issue. It's well known but nothing was establish to tackle it. 

Thank you!

https://map.project-osrm.org/?z=18&center=52.215921%2C20.964095&loc=52.215437%2C20.960928&loc=52.216745%2C20.962971&hl=en&alt=0&srv=0

![Captură de ecran din 2024-10-28 la 14 20 58](https://github.com/user-attachments/assets/649b6ea7-a265-457e-89f0-4f4a5cb30f32)

**Comment by jcoupey** [comment]
Looks like you found the data fix: https://www.openstreetmap.org/relation/18220552 ; this will be reflected in the next demo server data update.

**Comment by iaroslavzif** [comment]
Hi @jcoupey !

Indeed for this case I could add an restriction. But there are so many other cases when we offer this wrong similar turn. 

Check this one: https://map.project-osrm.org/?z=18&center=52.191326%2C20.982929&loc=52.191016%2C20.982669&loc=52.191348%2C20.980899&hl=en&alt=0&srv=0

Or this one: https://map.project-osrm.org/?z=18&center=52.187798%2C20.992719&loc=52.187471%2C20.992695&loc=52.189187%2C20.989385&hl=en&alt=0&srv=0

Or this one: https://map.project-osrm.org/?z=18&center=52.195401%2C21.002257&loc=52.195429%2C21.001031&loc=52.195534%2C21.002727&hl=en&alt=0&srv=0

For the last exemple you can see that Valhalla knows how to deal with it, but OSRM does not: https://valhalla.openstreetmap.de/directions?profile=car&wps=21.002393960952762%2C52.195277486854614%2C21.002554893493652%2C52.19565234452091

This is a huge issue. 

Thank you!

**Comment by jcoupey** [comment]
It looks like the other examples are very similar, i.e. having a turn restriction in the data in the first place would fix the problem.

What would be interesting would be to know how Valhalla prevents this turn. Maybe the penalty for the sharp left turn is prohibitive. But then this sounds like a tricky decision, because in some situations this kind of turn may be totally legal and what one would expect even if not very convenient.

**Comment by iaroslavzif** [comment]
> It looks like the other examples are very similar, i.e. having a turn restriction in the data in the first place would fix the problem.
It's not so easy, we enounter cases in which the OSM community asked us to not add restriction because this cases should be handled by the routing engine

> What would be interesting would be to know how Valhalla prevents this turn. Maybe the penalty for the sharp left turn is prohibitive. But then this sounds like a tricky decision, because in some situations this kind of turn may be totally legal and what one would expect even if not very convenient.
Indeed it would be interesting. Another thing that may add value is to penalise the U-turns too, not the sharp ones.....
How we can penalise the sharp turn?

**Comment by jcoupey** [comment]
> Another thing that may add value is to penalise the U-turns too, not the sharp ones..... How we can penalise the sharp turn?

The turn penalties are computed in the `process_turn` profile function. You could adjust the logic there https://github.com/Project-OSRM/osrm-backend/blob/48e8382785f3db82852bb8f37567e866bf83251a/profiles/car.lua#L483-L493 (e.g. based on the `turn.angle` value) or simply try increasing the `turn_penalty` value.

There is also a `u_turn_penalty` variable at the top of the profile that you can tune.

**Comment by iaroslavzif** [comment]
Just look at this one:
https://map.project-osrm.org/?z=18&center=46.460693%2C30.698963&loc=46.460140%2C30.697674&loc=46.460819%2C30.696735&hl=en&alt=0&srv=0

The entire map is like that when using OSRM. 

![Captură de ecran din 2024-10-29 la 16 30 45](https://github.com/user-attachments/assets/345a66f9-0d9a-4bf3-9ea8-7b9f171e37f6)
