### ISSUE TITLE
How to get a polyline through a list of waypoints that respects the order of the waypoints

### ISSUE THREAD

**Issue by edadma** [Project-OSRM/osrm-backend#7057]
Is there a way of using OSRM to get a polyline route geometry that runs through a list of waypoints without reordering them? In my tests, OSRM tends to reorder the waypoints.

**Comment by danpat** [comment]
If you're doing `/route/v1`, then it doesn't re-order the waypoints.  If you use `/trip/v1` then it _will_ re-order the waypoints to find the overall fastest path.
