### ISSUE TITLE
OSRM Map Matching Confidence > 1?

### ISSUE THREAD

**Issue by RiegelGestr** [Project-OSRM/osrm-backend#7058]
Hi OSRM Team,

I’ve been working with the map matching service using some real-world trajectory data and have encountered an issue where the Confidence values returned exceed 1. For example, a recent request returned a confidence value of 4.
I understand that confidence values are generally expected to be within the range of 0 to 1, where higher values indicate a more accurate match to the road network. However, it seems that in certain cases, particularly with some input data, these values can exceed this expected range.
Could you provide clarification on how to interpret confidence values greater than 1? Is this a known issue, and are there any adjustments being considered in the algorithm to handle such occurrences?
Should I discard the matching or doing something different?
I found discussions on this topic in previous issues, like https://github.com/Project-OSRM/osrm-backend/issues/6694, which noted similar observations.

**Comment by fenwuyaoji** [comment]
yes, it's a known issue in OSRM, you can treat the Confidence in this case as 0.

**Comment by RiegelGestr** [comment]
> yes, it's a known issue in OSRM, you can treat the Confidence in this case as 0.

ok, thanks!
do you know also why sometimes the routing computed using duration/distance is not the fastest/shortest path?

**Comment by jcoupey** [comment]
> do you know also why sometimes the routing computed using duration/distance is not the fastest/shortest path?

See weight notion: https://github.com/Project-OSRM/osrm-backend/blob/becfd8a56d15bc30d472e08d1d94d00854c58cf7/docs/profiles.md#understanding-speed-weight-and-rate.

**Comment by fenwuyaoji** [comment]
> do you know also why sometimes the routing computed using duration/distance is not the fastest/shortest path?

could you give an example? I don't get your point. you mean, when you call route API with `annotation= duration, distance`, the route in response is different without this param?

**Comment by RiegelGestr** [comment]
Well, unfortunately I cannot share the traces but here it's a problem I encountered.
First, I do the map matching of list of gps points with the OSRM map matching api.
Then, I compute the shortest or the fastest path between the starting point and ending point.
If I compare the shortest path distance (fastest path duration) with the distance of map matched path (or the duration), then sometimes I find that the map matched path is shorter than the shortest path -- which seems a contradiction.
Large fractions of theses cases have confidence > 1, but not all. I wonder if I need to tweak some parameters of Lua profiles to correct this problem.

**Comment by fenwuyaoji** [comment]
How does your traces quality? Sometimes, in my matching usage, let's say my GPS heartbeat is 15s, if some GPS points are missing, or some points are very close to each other, or GPS error is large (under a bridge, in buildings, underground, etc). The trace could be split into several matches by OSRM match API, for some of them the confidence could be larger than 1. That means these trace are trustworthy. I'm not sure about your situation, but if you can, you should ignore these traces or improve your trace quality with some preprocessing. or you can just adjust the param `radiuses ` in URL.

**Comment by RiegelGestr** [comment]
Yeah, I have ignored those with confidence above 1; and also those splitted. However, I have still a not-tiny fraction (15%) where the shortest (/fastest) is not the shortest(/fastest). I am not sure whether I should remove these traces or doing something else.

**Comment by fenwuyaoji** [comment]
Have you ever seen whether your route and matched trace are the same? you can use this URL: https://valhalla.github.io/demos/polyline/?unescape=true or other tools to show on map.

**Comment by jcoupey** [comment]
> the map matched path is shorter than the shortest path

In that case it means it's "shorter" with regard to another metric than the one OSRM optimizes for. If you're using `routability` as your profile `weight_name`, then OSRM optimizes on weight, not distance nor duration. It is definitely possible to get a map-matched route that is *faster* (smaller duration) or *shorter* (smaller distance) but with a higher weight. See [above link](https://github.com/Project-OSRM/osrm-backend/issues/7058#issuecomment-2468107279) for more.

**Comment by RiegelGestr** [comment]
I have tried the duration and distance, as weight in the profile. However, the problem is still there.
Do you know if I have to change other parameters?
I think that I need to share some traces.

**Comment by fenwuyaoji** [comment]
anyway, even match API only returns 1 match, it could be shorter than your actual trace because only part of your trace is matched, some points may be ignored. you should check these cases on and show them on map.
