### ISSUE TITLE
Posibility to debug location pairs in matrix generation

### ISSUE THREAD

**Issue by urosjarc** [Project-OSRM/osrm-backend#7074]
Our team have found some of the triangle inequalities when generating distance matrixes >2000x2000, and for those cases there should be some method for debuging purposes in order to report more quality issues regarding errors while generating big matrixes. How can we debug such cases?

**Comment by jcoupey** [comment]
If you mean that there are situations where the triangle inequality does not hold in distance matrices, then that is not a bug if you're not targeting "shortest distance" routes from the routing profile. See #5178.
