### ISSUE TITLE
How to ignore certain route parts?

### ISSUE THREAD

**Issue by mrueegg** [Project-OSRM/osrm-backend#735]
I have a list of certain route parts which should not be considered by OSRM when it's calculating a shortest path. As an example, I want to calculate the shortest path between `A` and `D`, and OSRM might yield `A -> B -> C -> D` as its result, but the route between `B` and `C` is closed because of temporary road works.

How can I configure OSRM to ignore this route and hence to take the second closest result (e.g., `A -> B -> E -> D`)? Is this what the file `osrm.restrictions` is for (`B -> C` is restricted)? If yes, could you please provide an example in the wiki?

**Comment by shahrozecafu** [comment]
Hi @emiltin ,
I have a similar problem. I want to exclude a specific road. I am using OSRM instance of my machine. What exactly do i need to do in car.lua for this? The road I want to exclude is called 'Sheikh Zayed Road' in Dubai, UAE and has a ref of E11 in open street maps. Can you please provide some specific instructions? 

Secondly, if one is using docker image, is it possible to exclude a specific road?
