### ISSUE TITLE
[warn] Unhandled exception: Error in function stxxl::ufs_file_base::ufs_file_base(const string&, int): Info: ::open() rc=-1 path=/var/tmp/stxxl flags=16450 Invalid argument

### ISSUE THREAD

**Issue by phaza** [Project-OSRM/osrm-backend#743]
I'm getting this error when I try to run osrm-extract.

I'm running osrm in a Docker ubuntu raring container, in a vagrant ubuntu raring VM, on a macbook pro.
It sounds more complicated than it is. Basically I'm trying to run osrm in a linux container on a linux box.

I assume the error is related to stxxl and aufs, but I'm not sure, and I'm not very fluent with C++.

I can run the osrm-extract flawlessly on the same vagrant VM (i.e not in a lxc/docker container)

If you have any suggestions to how I can debug this, I'd gladly help out.

**Comment by daniel-j-h** [comment]
This pull request fixes docker's dio aufs mount issues: https://github.com/docker/docker/pull/10534.
If you're still seeing issues, please open another ticket.
