### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by sercoin** [Project-OSRM/osrm-backend#754]
Hi,

I'm using test server, it has 24 GiB physical and 200 GiB swap memory. I extracted osm file successfully but when i try to prepare osrm files i always get different memory errors. Sometimes bad:alloc sometimes just kill process. Is swap file can be use without error? Or just need physical memory?

Thanks.

**Comment by georgbachmann** [comment]
Could somebody tell me what the estimated system requirements for Europe would be? Also, if I'd like to provide different profiles (let's say walking and driving) I need two instances, right? So basically double the system requirements?

**Comment by georgbachmann** [comment]
Thanks for your quick reply!!! So basically the whole world needs 60GB of RAM for processing?
And what about the resources needed to let it run?

**Comment by daniel-j-h** [comment]
I would roughly say again 60+ GB of RAM (more or less) which was the reason the demo server had some issues serving an old dataset and at the same time pre-processing a new one in the 120 GB it had before we upped it.
