### ISSUE TITLE
Best way to get map of USA?

### ISSUE THREAD

**Issue by sbryfcz** [Project-OSRM/osrm-backend#756]
I was wondering if anyone had a best practice of build a osm file for the entire USA? I'm trying to use osmconvert to decompress the .pdb files for each region and then merge them all together. Seems to take a fairly long time. Anyone else have a different approach. It would be so nice to have 1 file for the USA.

**Comment by sysilviakim** [comment]
@DennisOSRM Hi, I'm having similar issues and the hyperlink has rotted away. Is there any other alternative for just the U.S. polygon?

**Comment by systemed** [comment]
You can use osmfilter/osmconvert to merge the US area extracts together into one whole-US extract.
