### ISSUE TITLE
How to modify the maxspeed of a route

### ISSUE THREAD

**Issue by CesarDublas** [Project-OSRM/osrm-backend#771]
Hi everyone, I´m working on a project using my own OSRM server and I would like to know (if posible) a way to modify certain routes max speed.

I mean, the max speed between two nearly nodes (A - B) is 60Km/h. Is there any way to set it temporarily to 30 Km/h? (for example because of an accident)

I´ve read this topic, but i´m not sure if it can be usefull for me:
https://github.com/DennisOSRM/Project-OSRM/issues/new

If possible, we would like to modify it on a running server.

**Comment by daniel-j-h** [comment]
We are able to do updates by now, see https://github.com/Project-OSRM/osrm-backend/wiki/Traffic.
