### ISSUE TITLE
Extract planet causes External memory block allocation error

### ISSUE THREAD

**Issue by clintharris** [Project-OSRM/osrm-backend#784]
I'm trying to run osrm-extract on planet-latest.osm and am getting the "memory block allocation error" shown below. I'm running Ubuntu 12.04 on a system with i7 x 8 cores, 30GB of memory, and a 1TB drive.

The system has plenty of free memory and very little load; I'm only seeing about 3.5 GB of the 30 GB memory being used while osrm-extract is running.  Perhaps it's some sort of system configuration issue?

Any ideas?

Thanks for any help or advice!

```
$ ./osrm-extract planet-latest.osm.pbf 
[info] Input file: planet-latest.osm.pbf
[info] Profile: profile.lua
[info] Threads: 8
[info] Using script profile.lua
[STXXL-MSG] STXXL v1.3.1 (release)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] 1 disks are allocated, total space: 1000 MiB
[info] Using turn restrictions
[info] Found 3 exceptions to turn restriction
[info]    motorcar
[info]    motor_vehicle
[info]    vehicle
[info] Parsing in progress..
[STXXL-ERRMSG] External memory block allocation error: 2097152 bytes requested, 0 bytes free. Trying to extend the external memory space...
[STXXL-ERRMSG] External memory block allocation error: 2097152 bytes requested, 0 bytes free. Trying to extend the external memory space...
[STXXL-ERRMSG] External memory block allocation error: 2097152 bytes requested, 0 bytes free. Trying to extend the external memory space...
```

**Comment by astritzeqiri** [comment]
How much space is needed to extract, prepare,  and route the europe map (16gb)

**Comment by daniel-j-h** [comment]
See https://github.com/Project-OSRM/osrm-backend/issues/1697 https://github.com/Project-OSRM/osrm-backend/issues/1698. Please open another ticket if you have specific questions.
This ticket was for an stxxl error from 2013.
