### ISSUE TITLE
Please set them or make sure they are set and tested correctly in the CMake files:  LUAJIT_LIBRARY (ADVANCED)

### ISSUE THREAD

**Issue by Bardo-Konrad** [Project-OSRM/osrm-backend#797]
I have the same issue like this one: https://github.com/DennisOSRM/Project-OSRM/issues/749

except here it is

-- System supports 64 bits.
-- Configuring OSRM in release mode
-- Looking for LuaJIT...
-- Found LuaJIT: /usr/lib/i386-linux-gnu/libluajit-5.1.so
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so
-- Looking for OSMPBF...
-- Found OSMPBF: /usr/lib/libosmpbf.a
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUAJIT_LIBRARY (ADVANCED)
    linked by target "osrm-extract" in directory /whatever/Project-OSRM
    linked by target "osrm-prepare" in directory /whatever/Project-OSRM

-- Configuring incomplete, errors occurred!

I removed the build directory, created a new one, executed cmake .. again but still the same error message.

**Comment by bravemaster3** [comment]
Hey Bardo-Konrad. Can you please share how you solved the problem?

**Comment by ErfolgreichCharismatisch** [comment]
> Hey Bardo-Konrad. Can you please share how you solved the problem?

Disgusting leech.
