### ISSUE TITLE
Make the Normalized File Format a supported feature

### ISSUE THREAD

**Issue by woodbri** [Project-OSRM/osrm-backend#825]
Currently `osrm-extract` extracts data from OSM into a Normalized File Format, that is documented on the Wiki. A few people, including myself, have made attempts to use these files to import non-OSM data into OSRM.

The problem currently is that the documentation is not being updated when the code changes. This requires users of these file to reverse engineer them after every release. In addition to that the UUIDs that are written in the file headers are reflect the state of the OSRM library files that read/write these files and have changed in size from the last version to the current version. Unfortunately these files are not packaged into an API for others can use them easily in their code that is intended to work with OSRM.

In an ideal world, it would make sense to minimize the effort of supporting this valuable feature of OSRM by creating a small C++ class and library for reading and writing these files that would only require documenting the Class. Then other parties can link to that library and OSRM would use the same. A high level API for writing the *.osrm, *.osrm.names and *.osrm.restrictions files might be packaged something like libOSRMio.h and libOSRMio.so or include it in the existing libOSRM.so or whatever makes sense.

A simple Class might looks something like:

```
OSRMio io(std::string base_filename);

io.writeNames(std::vector names);
io.writeVertices(std::vector vertices);
io.writeEdges(std::vector edges);
io.writeRestrictions(std::vector restrictions);
```

For very large graphs we might want to have an interface that is more iterative in nature, like:

```
io.writeNames(int count_of_names);
for (int i=0; i<count_of_names; i++) {
    io.writeName(names[i]);
}

io.writeVertices(int count_of_vertices);
for (int i=0; i<count_of_vertices; i++) {
    io.writeVertex(lat[i], long[i], id[i], flags[i]);
}
```

etc for edges and restrictions. In my use case I would not use an array but rather records coming out of a database that need to get written.

The idea being to hide the details of file headers, internal file formats, etc. I'm assuming that osrm-extract and osrm-prepare would/could be able to use this same API so everything stays in sync.

**Comment by sweco-semtne** [comment]
Is there any update on this?

**Comment by daniel-j-h** [comment]
No progress on this front. In a different project I implemented a zero-copy streaming Protobuf powered I/O layer for serializing and deserializing huge graph datastructures (think north america), with an optional transparent compression and uncompression  stream in between.

The implementation is not too hard, and had a lot of advantages: for example you could pre-process graphs on a larger machine (think aws ec2) and then move the portable serialized artifact to your laptop. Or write tools against the formalized Protobuf schema, even from different languages.

The huge disadvantage and the reason we do not yet have this for osrm-backend is the following: the overhead from serializing and deserializing, that is parsing and constructing the Protobuf messages. Byte-wise dumping and reading datastructures --- as bad as it is (and we are aware of this https://github.com/Project-OSRM/osrm-backend/issues/1682 https://github.com/Project-OSRM/osrm-backend/issues/1685) --- is orders of magnitude faster as Protobufs. This is something where Cap'n Proto or Flatbuffers might shine, but we have not yet explored these options.

If you consider this in the context of our recent [Traffic effort](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) where we strive to cut off every seconds possible from subsequent pre-processing steps, it's clear that the current byte-wise dumping is the baseline a portable format has to fight against.

**Comment by daniel-j-h** [comment]
Superseded by https://github.com/Project-OSRM/osrm-backend/issues/2242.

@danpat @ghoshkaj and @duizendnegen specced this out and are currently working on it. The first sweep over the code base abstracted all the manual read and writes behind types which can be re-used. See https://github.com/Project-OSRM/osrm-backend/issues/2242 for more details.
