### ISSUE TITLE
datastore.cpp:163:86 error on debian wheezy

### ISSUE THREAD

**Issue by vgrekov** [Project-OSRM/osrm-backend#832]
Hi, I'm trying to build OSRM on Debian GNU/Linux 7.2 (wheezy) i386.
I've followed the instructions in "Debian Wheezy" section from https://github.com/DennisOSRM/Project-OSRM/wiki/Building%20OSRM.
The first problem I've faced was this one:

CMake Error at CMakeLists.txt:115 (message):
  Fatal error: Boost (version >= 1.44.0) required.

As far as I can tell I'm using 1.49.0.1 version of Boost. So I thought that the problem is  in some missing part of Boost and I've installed libboost-all-dev. It took me a bit further and now I'm getting this (complete log):

-- System supports 64 bits.
-- Configuring OSRM in release mode
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
-- Found BZip2: /usr/lib/i386-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib/i386-linux-gnu/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/i386-linux-gnu/libbz2.so - found
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.7") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found.
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find Lua52 (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR) 
-- Found Lua51: /usr/lib/i386-linux-gnu/liblua5.1.so;/usr/lib/i386-linux-gnu/libm.so (found version "5.1.5") 
-- Looking for LuaJIT 5.1
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Found LibXml2: /usr/lib/i386-linux-gnu/libxml2.so (found version "2.8.0") 
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so  
-- Found Luabind: /usr/lib/libluabind.so
-- Found PROTOBUF: /usr/lib/libprotobuf.so  
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so  
-- Found STXXL: /usr/lib/libstxxl.so
-- Looking for OSMPBF...
-- Found OSMPBF: /usr/lib/libosmpbf.a  
-- Found OSMPBF: /usr/lib/libosmpbf.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/viktor/osrm/Project-OSRM/build
Scanning dependencies of target GITDESCRIPTION
[  4%] Building CXX object CMakeFiles/GITDESCRIPTION.dir/Util/GitDescription.cpp.o
Linking CXX static library libGITDESCRIPTION.a
[  4%] Built target GITDESCRIPTION
Scanning dependencies of target OSRM
[  8%] Building CXX object CMakeFiles/OSRM.dir/Library/OSRM.cpp.o
[ 13%] Building CXX object CMakeFiles/OSRM.dir/Descriptors/DescriptionFactory.cpp.o
[ 17%] Building CXX object CMakeFiles/OSRM.dir/DataStructures/SearchEngineData.cpp.o
[ 21%] Building CXX object CMakeFiles/OSRM.dir/Algorithms/PolylineCompressor.cpp.o
[ 26%] Building CXX object CMakeFiles/OSRM.dir/Algorithms/DouglasePeucker.cpp.o
[ 30%] Building CXX object CMakeFiles/OSRM.dir/Server/Http/Reply.cpp.o
Linking CXX shared library libOSRM.so
[ 30%] Built target OSRM
Scanning dependencies of target UUIDConfigure
[ 34%] Configuring UUID.cpp
[ 34%] Built target UUIDConfigure
Scanning dependencies of target UUID
[ 39%] Configuring UUID.cpp
[ 43%] Building CXX object CMakeFiles/UUID.dir/Util/UUID.cpp.o
Linking CXX static library libUUID.a
[ 43%] Built target UUID
Scanning dependencies of target osrm-datastore
[ 47%] Building CXX object CMakeFiles/osrm-datastore.dir/datastore.cpp.o
/home/viktor/osrm/Project-OSRM/datastore.cpp: In function ‘int main(int, const char*_)’:
/home/viktor/osrm/Project-OSRM/datastore.cpp:163:86: error: no matching function for call to ‘min(long unsigned int, std::basic_string<char>::size_type)’
/home/viktor/osrm/Project-OSRM/datastore.cpp:163:86: note: candidates are:
In file included from /usr/include/c++/4.7/bits/char_traits.h:41:0,
                 from /usr/include/c++/4.7/ios:41,
                 from /usr/include/c++/4.7/ostream:40,
                 from /usr/include/c++/4.7/iostream:40,
                 from /home/viktor/osrm/Project-OSRM/DataStructures/../typedefs.h:42,
                 from /home/viktor/osrm/Project-OSRM/DataStructures/QueryEdge.h:32,
                 from /home/viktor/osrm/Project-OSRM/datastore.cpp:28:
/usr/include/c++/4.7/bits/stl_algobase.h:187:5: note: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
/usr/include/c++/4.7/bits/stl_algobase.h:187:5: note:   template argument deduction/substitution failed:
/home/viktor/osrm/Project-OSRM/datastore.cpp:163:86: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘std::basic_string<char>::size_type {aka unsigned int}’)
In file included from /usr/include/c++/4.7/bits/char_traits.h:41:0,
                 from /usr/include/c++/4.7/ios:41,
                 from /usr/include/c++/4.7/ostream:40,
                 from /usr/include/c++/4.7/iostream:40,
                 from /home/viktor/osrm/Project-OSRM/DataStructures/../typedefs.h:42,
                 from /home/viktor/osrm/Project-OSRM/DataStructures/QueryEdge.h:32,
                 from /home/viktor/osrm/Project-OSRM/datastore.cpp:28:
/usr/include/c++/4.7/bits/stl_algobase.h:233:5: note: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
/usr/include/c++/4.7/bits/stl_algobase.h:233:5: note:   template argument deduction/substitution failed:
/home/viktor/osrm/Project-OSRM/datastore.cpp:163:86: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘std::basic_string<char>::size_type {aka unsigned int}’)
make[2]: *_\* [CMakeFiles/osrm-datastore.dir/datastore.cpp.o] Error 1
make[1]: **\* [CMakeFiles/osrm-datastore.dir/all] Error 2
make: **\* [all] Error 2

Unfortunately I have almost no knowledge of C++ (and last time I've faced it was like 10 years ago). Can anybody help me with this?

Thanks in advance
Viktor

**Comment by aj07mm** [comment]
Same here on OSX v10.9.5
