### ISSUE TITLE
Where would I remove the 25 'waypoints' limit for viaroute?

### ISSUE THREAD

**Issue by carlospuk** [Project-OSRM/osrm-backend#837]
Hi there

According to the Wiki, `osrm-routed` is currently limited to 25 'waypoints' when using the `viaroute` webservice method.

We have a usage scenario for `osrm-routed` where we require more than 25 waypoints.

I assume that removing this limit wouldn't break anything?

If so, could somebody please give me a pointer to the right place in the code where I can disable this test in our local copy of the code?

Best,

Carl

**Comment by MayurDynamo** [comment]
There is Limit for waypoint in OSRM 
`{
message: "Number of entries 527 is higher than current maximum (500)",
code: "TooBig"
}`

**Comment by daniel-j-h** [comment]
Check `osrm-routed --help` for default limits and how to change them.

[code ref.](https://github.com/Project-OSRM/osrm-backend/blob/0e39aa9488bff97cffda1d12fb18cdeb537e0c03/src/tools/routed.cpp#L106-L120)

**Comment by DR-var** [comment]
How to remove this limitation for my own server? I've set the docker backend and works perfectly, still docker commands to remove limitation seems to have no effect

![image](https://github.com/Project-OSRM/osrm-backend/assets/174608540/62975fc9-d2c6-4a32-b4d9-31e1d893e505)
![image](https://github.com/Project-OSRM/osrm-backend/assets/174608540/8ee3c39a-f8c5-49be-becb-840742e693a4)
![image](https://github.com/Project-OSRM/osrm-backend/assets/174608540/04539e6a-8400-41c4-a1d1-7a55c723a86e)
