### ISSUE TITLE
Phantom node on oneway cul-de-sac

### ISSUE THREAD

**Issue by frodrigo** [Project-OSRM/osrm-backend#858]
Hi,

When looking for route from geocoding the phantom node on road can fall in oneway cul-de-sac (e.g. underground parking access).
I'm looking for a way to deal with.

- I can use lua way_function to skip this kind of ways with external data tool. I can't do it only this OSRM and lua, can I ?
- An other way to solve the problem may be to drop impassable edge as begin/stop. May be is close to issue #156.

An other idea to solve the problem ?

Thank by advance.

**Comment by MoKob** [comment]
For restrictions like this, the new API of OSRM 5.0 contains the ability to use given bearings too find a fitting way.

Using these, finding a correct starting location is a query time process that should avoid such cul-de-sac entries if used correctly.
