### ISSUE TITLE
turn penalties for cars, to avoid sharp turns

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#860]
as a follow op to #859, shouldn't the car profile use turn penalties, to avoid very sharp turns?

the bike profile squares the angle (angle*angle), which works well:

```LUA
turn_penalty = 60
turn_bias      = 1.4

function turn_function (angle)
    -- compute turn penalty as angle^2, with a left/right bias
    k = turn_penalty/(90.0*90.0)
	if angle>=0 then
	    return angle*angle*k/turn_bias
	else
	    return angle*angle*k*turn_bias
    end
end
```
the bias should probably be set to 1, so that it works equally well for countries with left/right side driving.

**Comment by danpat** [comment]
These were added to the car profile with in https://github.com/Project-OSRM/osrm-backend/commit/b3822d5802e7cfd57500ff4bf37570062a2a3bb8 after some comparison of real-world routing behavior against OSRM with/without these penalties.  They definitely help decrease zig-zag routing in grid-like city regions.
