### ISSUE TITLE
Zebra crossing

### ISSUE THREAD

**Issue by HD24** [Project-OSRM/osrm-backend#862]
Hi,

We are developing an aplication for blind people, this app tries to guide people with the mobile phone.  That's the reason that we need to know if the node is or not a zebra crossing,etc.

We know that node information is mostly discarded for routing except when the node is some kind of barrier, but we would like to know in which part of the code this info is discarded and if its possible to avoid this step.

Thanks.

**Comment by daniel-j-h** [comment]
As already said, currently the workaround is to encode the information in the way attributes.
