### ISSUE TITLE
It would be nice to update the url in the address bar as we scroll and zoom the map.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [Project-OSRM/osrm-backend#864]
Just like it does in OSM main website.  It would also facilitate bug reporting.

Browser: Firefox 17 under Linux.

**Comment by daniel-j-h** [comment]
There is https://github.com/Project-OSRM/osrm-frontend-v2 by now.

**Comment by PauloCarvalhoRJ** [comment]
Much obliged!
