### ISSUE TITLE
Allow waypoints (route markers) to be entered via textbox, rather than clicking on the map only

### ISSUE THREAD

**Issue by rudolfmayer** [Project-OSRM/osrm-backend#875]
Currently if I want to do a route from A to C via B, I need to e.g. select A and C in the textboxes in the top-left corner, compute the route, and then click somewhere on the route to add a waypoint (route marker in OSRM naming), and then move that to where B is.

Ideally, I could click somewhere in the top-left "add waypoint", and I could enter it there.

(Feature Request / GUI / OSRM-Web)

**Comment by daniel-j-h** [comment]
There is https://github.com/Project-OSRM/osrm-frontend-v2 by now.
