### ISSUE TITLE
Show detailed route duration information

### ISSUE THREAD

**Issue by rudolfmayer** [Project-OSRM/osrm-backend#876]
OSRM Route Description could be extended to give more detailed indications to the user of the route; it would be nice if next to each segment of the route, besides writing the distance, it would also print the estimated duration for that.

Two use cases for this:

- To give more detailed indications to the user of the route so they know how long they'll drive on a specific segment.

- To allow inspection OSM data - OSRM is a great means to check whether OSM ways are tagged correctly, by checking a route along the way; one can quite frequently discover wrongly tagged ways that thus don't appear on the map, or that have a wrong classification and thus are considered for a too low speed, etc..
To enable even more detailed inspection on whether OSRM interprets the data as the mapper assumes, this feature would be useful.

(Feature Request / GUI / OSRM-Web)

**Comment by daniel-j-h** [comment]
There is https://github.com/Project-OSRM/osrm-frontend-v2 by now.
