### ISSUE TITLE
use destination tags/relations for instructions

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#882]
destination tags and relations are intented for providing better instructions in navigation apps, by providing info about signage that can be followed.

http://wiki.openstreetmap.org/wiki/Key:destination
http://wiki.openstreetmap.org/wiki/Relation:destination_sign

(not be be confused with access=destination)

**Comment by MoKob** [comment]
closing in favor of https://github.com/Project-OSRM/osrm-backend/issues/2267
