### ISSUE TITLE
make cucumber tests run faster - use osrm datastore?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#884]
By modifying wait time used when launching/shutting down OSRM during tests, I reduced the time it takes to re-run all cucumber tests from 1:13 to 0:23 on my Mac. However, if I reduce wait times further I get timeouts, because the TCP socket report OSRM as ready, but OSRM then doesn't repond, probably because it hasn't been fully initialized yet. So it's a bit tricky.

But this made me think if should use the new osrm-datastore during tests? Surely it would be much faster to just reload data, that relaunch OSRM?

**Comment by danpat** [comment]
This was implemented (a long time ago).
