### ISSUE TITLE
Getting on 101 at Cesar Chavez in SF

### ISSUE THREAD

**Issue by jfirebaugh** [Project-OSRM/osrm-backend#885]
OSRM produces the [same incorrect routing as Apple Maps](https://twitter.com/nelson/status/426411047994392576):

http://osrm.at/6cZ

The U turn is not technically illegal, just dangerous and contrary to the signed route.

What's the best way of fixing this? Increasing the U-turn penalty in the profile?

**Comment by daniel-j-h** [comment]
@jfirebaugh How does the following look to you?

![cesar](https://cloud.githubusercontent.com/assets/527241/12299086/6bd81f7c-ba15-11e5-8403-73dde3b72c1f.png)

If you can live with it, feel free to close this issue :)

**Comment by jfirebaugh** [comment]
Looks great, that's the signed route.
