### ISSUE TITLE
Strange "B" routing to/from Macon GA to Charleston SC

### ISSUE THREAD

**Issue by lordsutch** [Project-OSRM/osrm-backend#900]
The "A" routing makes sense (except for the minor data-related detail that the default profile's speed limit for motorways is too low, which means the router prefers a signalized arterial in Pooler that has a similar signed speed limit to the default)... but the "B" routing takes the driver 15 km out of the way to make a U-turn at an interchange... not even the nearest possible interchange. And it happens in both directions (if you reverse the route).

http://osrm.at/6iQ

A saner "B" routing is produced if I move the start point a few miles north:

http://osrm.at/6iR

**Comment by MoKob** [comment]
I cannot reproduce this error on any of the presented examples. Assuming its fixed for now, unless other examples pop up.
