### ISSUE TITLE
Please support oneway=reversible

### ISSUE THREAD

**Issue by Stemby** [Project-OSRM/osrm-backend#902]
For example: http://osrm.at/6iu

Thank you!

**Comment by socketpair** [comment]
http://osrm.at/cqU

![osrm_reversible](https://cloud.githubusercontent.com/assets/1157412/7691042/da37e58a-fdd0-11e4-9b95-81abef8967c5.png)

**Comment by socketpair** [comment]
Idea: switcher between "avoid reversible" and "consider reversible as twoways" at least.

**Comment by emiltin** [comment]
maybe just reduce speed by half if oneway=reversible, or lanes=1?

**Comment by TheMarex** [comment]
A behavior similar to `lanes=1` seems appropriate. Tracking here https://github.com/Project-OSRM/osrm-backend/issues/1388

**Comment by socketpair** [comment]
Interesting that during one time (during the daylight) it have one direction, and another direction otherwise.... So :) osrm should consider current time to decide. But seems it is another issue...

**Comment by daniel-j-h** [comment]
Closing this in favor of https://github.com/Project-OSRM/osrm-backend/issues/2837

Sorry we didn't catch the ticket as a dupe; the ticked linked has ore information on how to handle this.
