### ISSUE TITLE
Compile OSRM on raspberry pi

### ISSUE THREAD

**Issue by jekes** [Project-OSRM/osrm-backend#921]
Hi 

I try to compile OSRM on the raspberry (raspian distribution, kernel 3.10.25)
All the dependances are installed (Boost, xml2, cmake, stxxl, protobuf, gcc ...).

When i run the cmake command, I notice that the "system supports 64 bits", so the compilation failed. I try with master and developp version.

![compilation](https://f.cloud.github.com/assets/2369520/2206021/d7ef435e-9959-11e3-8c4c-7b2ffeb92918.png)

I compile osrm on x64 ubuntu server but I am neebie on embedded device.
Is it possible to compile osrm on a 32 bits arm architecture ?
Is it a way to run a 64 bit program (compile on my server) on a 32 bits architecture ?

**Comment by komms** [comment]
> It works now. Many thanks.

How did you do the cross compile of OSRM on an ARM machine?
