### ISSUE TITLE
Incremental updates

### ISSUE THREAD

**Issue by risicle** [Project-OSRM/osrm-backend#93]
Hi,

Just wondering whether you're ever planning on implementing incremental data updates, i.e. make it possible to update the routing database using minutely/hourly .osc files in the same way an osm2pgsql database can be maintained, rather than having to rebuild the whole thing every time you want it updated.

I would consider being able to maintain a routing server that's just a few minutes behind the live osm data a killer feature.

robert.

**Comment by zavan** [comment]
Hi guys, I've been searching for the best way to update the OSRM data, but no luck. Do any of you have any idea about this? 

From what I understood, for now, the only way is to rebuild the whole thing from time to time from the update planet file, right?

**Comment by TheMarex** [comment]
Supporting incremental updates to the actual road network is not going to happen. Updating the edge weights, maybe in the future.

IMHO the only way you can have something like that is if you run on top of a database, which is too slow for OSRM.

> From what I understood, for now, the only way is to rebuild the whole thing from time to time from the update planet file, right?

Yep.

**Comment by emiltin** [comment]
@TheMarex what do you think @DennisOSRM referred by when he wrote "Yes, there are plans to have minutely updates. While I know from a technical stand point how to implement this, time is scarce at the moment."

**Comment by TheMarex** [comment]
I think he was talking about edge weight updates. If you want to actually modify the graph structure at runtime in the end you will get something like a database. Having static data is a very good assumption that simplifies a lot of things and makes it possible to optimize.

Also you don't want to apply every change that comes from OSM. The street network is broken all the time and you want to do some sanity checks before you use the new data. I don't think that would be possible for minutely updates even with a database.

**Comment by emiltin** [comment]
ok. would the ability to update weights be a kind of reprocessing of the data, or something you could specify for each query?
what kind of sanity check are you doing on osm data?

**Comment by zavan** [comment]
Ok, thanks! I tested and rebuilding/extracting the areas that I'll be working with doesn't take that long, something like 14 minutes.

**Comment by mattkrick** [comment]
Does anyone have an example of a cron job they use to make this update? I was thinking about grabbing new data every couple weeks or so. Anyone do something similar?

**Comment by TheMarex** [comment]
@emiltin it is a kind of reprocessing, just much faster. Not really real time.
An easy methode to check the road network is to have a good test set of routes and compare the travel time of those after each data update. 

@mattkrick you can get a weekly planet file as pbf and just run osrm-extract and osrm-prepare on them.
