### ISSUE TITLE
Routing to the nearest viable point

### ISSUE THREAD

**Issue by samlown** [Project-OSRM/osrm-backend#930]
This is closely related to issue #926.

We're creating routes based on GPS data. Occasionally, the GPS indicates that a start or end location is situated in a place where there is no entry or exit, an island of sorts as described in #926, when the real location is probably on a main road a few meters away.

Is there any way to route between what I would call the "nearest viable point"? In effect, this would mean detecting when a point cannot be routed to and scanning for the nearest point that can be reached.

I believe this is similar to the `z` parameter, but adapted for when the nearest location cannot be routed to.

Example failing query to the API:

    http://router.project-osrm.org/viaroute?loc=40.4221205,-3.707557599999973&loc=40.4576797,-3.692164400000024&z=10

Thanks for any advice!

**Comment by DennisOSRM** [comment]
This is implemented now and will be part of the upcoming release.

**Comment by recallfx** [comment]
This is still not working: http://map.project-osrm.org/?hl=en&loc=54.696766,25.277030&loc=54.696654,25.279863&z=16&center=54.695675,25.274005&alt=0&df=0&re=0&ly=-1171809665

https://router.project-osrm.org/viaroute?z=16&output=json&loc=54.696766,25.277030&loc=54.696654,25.279863&instructions=true

**Comment by emiltin** [comment]
there is a barrier=cycle_barrier at https://www.openstreetmap.org/node/3341832207

**Comment by emiltin** [comment]
also is has no highway=*

**Comment by recallfx** [comment]
Is there some kind of radius variable that I could tweak?

**Comment by maxdeepfield** [comment]
I changed this constant and got bigger search radius https://github.com/Project-OSRM/osrm-backend/blob/4ec323c5ccb3db4b31df1bedb12e596a388d49d0/data_structures/static_rtree.hpp#L649

**Comment by wpcarlanderson** [comment]
I'm still seeing problems. Not getting a viable point for viaroute.
I start with a coordinate in the middle of a mountain. I use /nearest to get to the nearest road segment: http://localhost:5000/nearest?loc=37.6756461497,-119.467181647
However, this mountain road segment is closed in winter so I am still "impossible route" from viaroute. Nearest would have to provide the first open road segment down the mountain to provide a viable route.
