### ISSUE TITLE
Show actual location marker if different from routable location

### ISSUE THREAD

**Issue by waldyrious** [Project-OSRM/osrm-backend#948]
When a start or end location isn't routable, but there's a nearby location suitable for routing, the corresponding marker gets snapped to that location on the map. It would be nice to have the option (e.g. in the Mapping Tools) to still show markers for the actual user-picked location -- perhaps at half-transparency, with the "no route" dashed line connecting them to the OSRM-picked location.

**Comment by TheMarex** [comment]
This is implemented in https://github.com/perliedman/leaflet-routing-machine

**Comment by waldyrious** [comment]
@TheMarex but why close it here when http://map.project-osrm.org still doesn't implement the proposed behavior?

I suppose maybe this but should be opened at https://github.com/Project-OSRM/osrm-frontend then?

**Comment by TheMarex** [comment]
@waldyrious the website is legacy. I would not suggest using the old frontend but simply use LRM. The new website is also based on LRM: https://github.com/Project-OSRM/osrm-frontend-v2

**Comment by waldyrious** [comment]
@TheMarex the problem is that the website is still the default for the public. People will go to http://project-osrm.org and click through to http://map.project-osrm.org, rather than directly typing http://project-osrm.org/osrm-frontend-v2/ (which doesn't even seem to be linked from the home page). If v2 is ready to replace the old frontend, why not actually replacing it, or at least feature a prominent link in the home page to it?

Regardless, v2 doesn't implement this fix yet, so the point is moot for now, anyway.
