### ISSUE TITLE
osrm-datasource loads shared memory even if error occurs

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/osrm-backend#952]
On OS X I hit the below error because I had not modified my `sysctl.conf` settings like described at https://github.com/DennisOSRM/Project-OSRM/wiki/Configuring-and-using-Shared-Memory.

Ideally if an error like this occurs for this reason or any other during the load of up shared memory the segments should not be left live, right? It seems like a failed run should fail 100% and not partially.

```
$ osrm-datastore berlin-latest.osrm
[info] validator called for berlin-latest.osrm
[info] load names from: "berlin-latest.osrm.names"
[info] size: 9847
[info] allocating shared memory of 20933050 bytes
[warn] caught exception: Invalid argument, code 21
[warn] caught exception: Invalid argument
```

**Comment by springmeyer** [comment]
Just noticing this old ticket of mine: Next action is to figure out if this bug still exists.

**Comment by stepankuzmin** [comment]
I'm getting this message with OS X 10.10.3 El Capitan using osrm-backend v.4.9.0

**Comment by springmeyer** [comment]
This is stale: closing. Docs for OSX on configuring shared memory to work now clear at https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory/_compare/83a4587491c4cb55971a936c334d29900a9ce2a6...718b12d33ca13233fe6407c6fe28f22f289db55c
