### ISSUE TITLE
Wrong driving time across countries with different speed limits

### ISSUE THREAD

**Issue by dcdieci** [Project-OSRM/osrm-backend#957]
Hi,

I just prepared new data for an "inter-country" routing between germany and switzerland. Point being is that both countries have different speed limits. So I need to provide two different profiles for data preparation which I did not figure out how to do it.

Please don't bother about creating this ticket as an issue. I am not sure whether it is a feature request but imho the calculated routes are wrong due to this constraint. I would be very happy to hear back from you guys.

Best,
Philip

**Comment by TheMarex** [comment]
@dcdieci we allow for country specific `maxspeed` tags. Tagging a motorway inside switzerland with `maxspeed=ch:motorway` will do the right thing.
