### ISSUE TITLE
multiple proposal routes by OSRM

### ISSUE THREAD

**Issue by ksmiri** [Project-OSRM/osrm-backend#975]
Hi all,
i just wanna know if OSRM gives us multiple routes for one (source, destination) couple?
or it gives us just the best one?

**Comment by sanju74** [comment]
Hi, Any Progress in dynamically change the edge costs in OSRM? PGRouting has this but it is too slow. Please let me know if you have any suggestion on how to change the edge cost and block any node/edge from calculation. Thanks in advance.
