### ISSUE TITLE
No tiles by request

### ISSUE THREAD

**Issue by i-lex-r** [Project-OSRM/osrm-backend#990]
Hello, Dennis.
My name Alexander. 
I found your project Project-OSRM, and the project Project-OSRM-Web. I copied it from GitHab and had try to running this projects. Unfortunately there was some problems. Please explain the following points:
1) at the request of the tiles in the browser console displays the following mail message,:
[info] 25-04-2014 14:43:47 127.0.0.1 http://127.0.0.1/osrm/main.html Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium / 31.0.1650.63 Chrome/31.0.1650.63 Safari/537.36 / 14/11953/5560.png.
2) in the browser when get data by the address http://127.0.0.1:5000/14/11953/5560.png - get the following message:
400 Bad Request
Input seems to be malformed close to position
/ 14/11953/5560.png0
^
The number after the expansion ".png" always 0.
Please help me. Explain what i do wrong.

**Comment by Sozhia** [comment]
Hello Dennis.
I want to use my local tiles server with osrm do you know how can I do?
OS: Windows 7
TMS: MS4W
Thanks a lot
