### ISSUE TITLE
Generate link even with only one marker

### ISSUE THREAD

**Issue by awikatchikaen** [Project-OSRM/osrm-backend#999]
please add possibility to place a point and send the map to guests with only this marker.

It's useful to show a POI (even if, I know, it's not the main purpose of the app).
It's very useful to place the destination point and send the link to guests. Each one can see where to go and a add their start point to calculate their own route.

Thank you

**Comment by daniel-j-h** [comment]
The new frontend is now at https://github.com/Project-OSRM/osrm-frontend-v2.
